### ISSUE TITLE
Ads in the twitter UI refresh

### ISSUE THREAD

**Issue by sbrl** [uBlockOrigin/uAssets#4711]
### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

 - `https://twitter.com/home`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]
1. Navigate to Twitter's homepage in your web browser.
2. Opt-in to the new UI refresh.
3. Scroll down.

#### What should happen
I should not see any advertisements.

#### What actually happened
I see advertisements.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

![selection_115](https://user-images.githubusercontent.com/9929737/51639963-26cd0980-1f5a-11e9-9ede-7de21a5ddc6c.png)

### Versions

- Browser/version: 65.0b12 (64-bit)
- uBlock Origin version: v1.17.4

### Settings

- [List here all the changes you made to uBO's default settings]

**Settings:**

![selection_116](https://user-images.githubusercontent.com/9929737/51640006-45330500-1f5a-11e9-9aa6-8eaa5d136107.png)

**Filters:**

![selection_117](https://user-images.githubusercontent.com/9929737/51640037-64319700-1f5a-11e9-9093-7f99fd77c0fb.png)

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/blob/bc9b742e9d28f8df49527ffa0639b2be94631377/filters/filters.txt#L6268

or try pruge and update bulit-in "uBlock Filters".

**Comment by bogachenko** [comment]
> 
> 
> [uAssets/filters/filters.txt](https://github.com/uBlockOrigin/uAssets/blob/bc9b742e9d28f8df49527ffa0639b2be94631377/filters/filters.txt#L6268)
> 
> Line 6268 in [bc9b742](/uBlockOrigin/uAssets/commit/bc9b742e9d28f8df49527ffa0639b2be94631377)
>  twitter.com##[data-testid="tweet"]:has-text(/Promoted|Gesponsert/) 
> 
> or try pruge and update bulit-in "uBlock Filters".

![default](https://user-images.githubusercontent.com/8535285/51742625-3bacb880-2092-11e9-8e98-917fa6acf0e2.png)

**Comment by bogachenko** [comment]
This does not work. I added this filter to this "Реклама"  happened `twitter.com##[data-testid="tweet"]:has-text(/Promoted|Gesponsert|Реклама/)`. Look at the screenshot below.
![default](https://user-images.githubusercontent.com/8535285/51742743-8c241600-2092-11e9-811d-3511d86c4f26.png)

**Comment by krystian3w** [comment]
This is no`[data-testid="tweet"]` - as you wrote.

You can try find method to detect in sidebar?

**Comment by bogachenko** [comment]
@krystian3w Well .. this is of course the collective farm option. but the sidebar is `UserCell`, so
`twitter.com##[data-testid="UserCell"]:has-text(/Promoted|Gesponsert|Реклама/)`

But it breaks it .. then me need another cosmetic filter
![default](https://user-images.githubusercontent.com/8535285/51744134-c2fc2b00-2096-11e9-956d-13bc07fc34dc.png)

> This is no[data-testid="tweet"] - as you wrote.

??

**Comment by krystian3w** [comment]
> ??

Nevermind.

**Comment by krystian3w** [comment]
> and add something else to the sidebar. because the sidebar also has ads

how does works this:

```
twitter.com##[data-testid="tweet"],[data-testid="UserCell"]:has-text(/Promoted|Gesponsert|Реклама/)
```

**Comment by bogachenko** [comment]
> 
> 
> > and add something else to the sidebar. because the sidebar also has ads
> 
> how does works this:
> 
> ```
> twitter.com##[data-testid="tweet"],[data-testid="UserCell"]:has-text(/Promoted|Gesponsert|Реклама/)
> ```

Works.

**Comment by mapx-** [comment]
Does this work ?
`twitter.com##[data-focusable="true"]:has-text(/Promoted|Gesponsert|Реклама/)`

**Comment by bogachenko** [comment]
Yes. but it still breaks the sidebar @mapx-

**Comment by mapx-** [comment]
What is broken ?

**Comment by krystian3w** [comment]
> @krystian3w I insist.
> 
> > > ??
> > 
> > 
> > Nevermind.


I have added comments to my misunderstood [post](https://github.com/uBlockOrigin/uAssets/issues/4711#issuecomment-457542504).  I can not explain English or Russian better.

---

> Does this work ?

I can not test with attribute `[data-focusable = "true"]`.

**Comment by bogachenko** [comment]
space that was supposed to be advertising @mapx- 
![default](https://user-images.githubusercontent.com/8535285/51744853-08215c80-2099-11e9-8d6f-7d86271247c8.png)

**Comment by mapx-** [comment]
I'd say it's nothing broken ..

**Comment by bogachenko** [comment]
@mapx- Well ... how is it? Can u raise?

**Comment by bogachenko** [comment]
ага, конечто же нет. просто закрыть...

**Comment by mapx-** [comment]
I guess sometimes there are only 2 following guys there and so the space !?

**Comment by bogachenko** [comment]
@mapx- Мужик. Там 3 места. 1 под рекламу. 2 под людей. Релама стоит первым, послее ее удаления 2 последующие места смещаются вверх. Внизу образуется пространство.

**Comment by mapx-** [comment]
**Even if in the logger I see the the `data-focusable` filter** I still get 3 full places (99% of cases).
Sometimes (1%) I get only 2 places.

**Comment by krystian3w** [comment]
I suspect that not sooner than in the future edition of the uBO: https://github.com/uBlockOrigin/uBlock-issues/issues/382, if  can't be cut, without additional CSS.

**Comment by bogachenko** [comment]
@mapx- ...

**Comment by bogachenko** [comment]
@mapx- breaks the sidebar, as there is the inscription "Advertising", it can not be opened, it is not closed immediately
![default](https://user-images.githubusercontent.com/8535285/52396124-bfd85480-2b04-11e9-9828-81e01c413be7.png)

**Comment by bogachenko** [comment]
proof @mapx- 
![twitter](https://user-images.githubusercontent.com/8535285/52396592-93bdd300-2b06-11e9-9267-4d51687d8a81.gif)

**Comment by mapx-** [comment]
I commented for now the filter, I get no "promoted" placeholders right now

**Comment by bogachenko** [comment]
@mapx- do you open the sidebar ?

**Comment by bogachenko** [comment]
it seems everything works

**Comment by bogachenko** [comment]
![twitter](https://user-images.githubusercontent.com/8535285/52412911-3a6c9880-2b34-11e9-9d0b-8539c1f29b80.gif)
it closes automatically. I already wrote, there is a line "Реклама в Twitter"
![default](https://user-images.githubusercontent.com/8535285/52413076-a3eca700-2b34-11e9-99bd-33e8975601f1.png)
 it is the cause of (emergency) closure

**Comment by mapx-** [comment]
does this work for you ?
`twitter.com#@#[data-focusable="true"]:has-text(/Promoted|Gesponsert|Реклама/)`

**Comment by bogachenko** [comment]
@mapx- Hey, there is a place from advertising left .. he is clickable. and if you click on it then throws on the advertising post
![default](https://user-images.githubusercontent.com/8535285/52722276-663dc180-2fff-11e9-8635-beb38c447b02.png)

**Comment by mapx-** [comment]
@bogachenko  save the page (right click, save as ...), zip together folder + html, send me to this address:
`axis.trivia@gmail.com`

**Comment by bogachenko** [comment]
will not work. I saved it, opened it in another browser (where I am not logged in) and then look at the screenshot
![default](https://user-images.githubusercontent.com/8535285/52724873-43fa7280-3004-11e9-92f2-0abb048337fc.png)

does it suit you?

**Comment by bogachenko** [comment]
sended

**Comment by krystian3w** [comment]
Lost in Internet... try not from `mail.ru` send.

**Comment by bogachenko** [comment]
@krystian3w I do not have mail on mail.ru
@mapx- sent from yandex .. now with google I will try

**Comment by bogachenko** [comment]
I sent again from Google

**Comment by mapx-** [comment]
Did you logoff before saving the page ?

**Comment by bogachenko** [comment]
@mapx- No. I wrote you, before sending the message, I saved main page and opened in to check, but only the window with the password and login was loaded. I sent to this thread a screenshot that in my 2 browser (where I am not logged in) and asked if you need such a page? I waited for the answer minutes 5-10, you did not answer. I deleted this post. And I sent you a message with a page.

ну и что я делаю не так? 

![twitter](https://user-images.githubusercontent.com/8535285/52734441-5cc15300-3019-11e9-96d6-866914b92d99.gif)

**Comment by krystian3w** [comment]
Maybe @mapx-  copy text from html file and pase on opened twitter with developer tools...

**Comment by mapx-** [comment]
nvm, test this filter
`twitter.com##[data-testid="tweet"]:has-text(Promoted):xpath(..)`

**Comment by bogachenko** [comment]
mb Реклама? not Promoted?

**Comment by mapx-** [comment]
ok, see above

**Comment by bogachenko** [comment]
At the moment, no ads are visible, I will test. I will write

**Comment by bogachenko** [comment]
> 
> 
> does this work for you ? (no other custom filter)
> `twitter.com#@#[data-focusable="true"]:has-text(/Promoted|Gesponsert|Реклама/)`

will you delete?

**Comment by mapx-** [comment]
yeah, I'll replace it using the xpath one

**Comment by bogachenko** [comment]
thank u so much

**Comment by bogachenko** [comment]
![Безымянный](https://user-images.githubusercontent.com/8535285/54343601-16bad780-4637-11e9-8194-ab529c21d940.png)
again

**Comment by bogachenko** [comment]
This rule helps for ru `twitter.com##[data-testid="trend"]:has-text(Реклама от):xpath(..)`

**Comment by bogachenko** [comment]
tx

**Comment by bogachenko** [comment]
Hello @mapx- , there is no advertising, I just want to say if you remember (and if you are interested) for me (for the Russian-speaking region) [did not have a sidebar](https://github.com/uBlockOrigin/uAssets/issues/4711#issuecomment-461409610) and [you helped me fix it here](https://github.com/uBlockOrigin/uAssets/issues/4711#issuecomment-461428934), and you, [at my request, deleted this rule for the Russian-speaking region](https://github.com/uBlockOrigin/uAssets/commit/82b9e31555f02454cbee78df29ca575c22e99c35), and so (It seems, **check me**, maybe I'm wrong) i found how to fix it.

Look this rule

```
twitter.com##[data-focusable="true"]:has-text(/Promoted|Gesponsert|Реклама/):not(:xpath(//div[contains(text(),'Реклама в Твиттере')]))
```

**Comment by bogachenko** [comment]
@mapx- they changed the fucking design (again)
change it
`twitter.com##[data-focusable="true"]:has-text(/Promoted|Gesponsert|Реклама/):not(:xpath(//div[contains(text(),'Реклама в Твиттере')]))`
to that
`twitter.com##[data-focusable="true"]:has-text(/Promoted|Gesponsert|Реклама/):not(:xpath(//span[contains(text(),'Реклама в Твиттере')]))`

**Comment by gorhill** [comment]
I've removed the `data-focusable="true"` filter for now, this was the cause of really annoying jumpiness I was experiencing with Twitter. That filter had to go through a lot of DOM nodes, possibly causing it to be disabled/enabled randomly due to how uBO allocates execution time to expensive filters (just speculating). Without it, the jumpiness is gone on my side. Filters which are too expensive should not be added to "uBlock filters" -- for example `##[data-focusable="true"]` (which is the first part of the filter) returns 179 elements which will have to be visited to apply the rest of the operators. That first part of a filter should always be designed to select as few elements has possible.

**Comment by bogachenko** [comment]
@mapx- Duder
In Russian, there is a block on Twitter - `Продвигаемый твит` is an advertisement, [look at this](https://user-images.githubusercontent.com/8535285/82751575-dd1d5900-9e03-11ea-8565-d7e1f60cb98b.png).
In English, an empty block remained on Twitter, [look at this](https://user-images.githubusercontent.com/8535285/82751602-0d64f780-9e04-11ea-98d9-0c2f5cebc9af.png)
