### ISSUE TITLE
RaW Story disqus comments 

### ISSUE THREAD

**Issue by silat** [uBlockOrigin/uAssets#4712]
### URL(s) where the issue occurs

`[ https://www.rawstory.com/2019/01/trump-confidantes-lie-publicly-multiple-times-ordered-cohen-lie-congress-national-security-expert/?comments=disqus]`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: [ff android 6402]
- uBlock Origin version: [1174]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes
Go to https://www.rawstory.com/2019/01/trump-confidantes-lie-publicly-multiple-times-ordered-cohen-lie-congress-national-security-expert/?comments=disqus click on the join discussion Banner on any Raw Story article. And disqus will not load. Disable ublock origin and disqus on rawstory.com will load. Disqus loads on other sites I use like crooksandliars.com

**Comment by okiehsch** [comment]
I can't test with an android device but the comments were broken using the Firefox desktop version.
The fix works on my end, with that desktop version, so some feedback would be appreciated.

**Comment by silat** [comment]
I'm confused. The fix works? What fix would that be?

**Comment by okiehsch** [comment]
You can see the "okiehsch closed this in ......" message?

**Comment by silat** [comment]
I saw that. If I made some sort of error I apologize. I'm just trying to
get a fix for what ails me. Your post mentioned a fix. But it didn't follow
up with the fix.

**Comment by okiehsch** [comment]
No problem, have you updated your `uBO-filter` list. The fix I spoke about was added to that list.

**Comment by okiehsch** [comment]
If you have not updated that list or don't know how to update.
Add
````
rawstory.com#@#+js(abort-on-property-read.js, performance.getEntriesByName)
rawstory.com##+js(set-constant.js, performance.getEntriesByName, trueFunc)
````
to your filter list and try if the comments work for you.

**Comment by silat** [comment]
Thank you so much for your help. It's working as we speak. I hope I wasn't
too much trouble for you as I'm not completely computer illiterate. 😏
My partner says woof woof to you.
