### ISSUE TITLE
descargatelocorp.com

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#4713]
### URL(s) where the issue occurs

`https://www.descargatelocorp.com/yu-gi-oh-legacy-of-the-duelist-2016-pc-full-espanol/`

### Describe the issue

Anti-adblock

### Screenshot(s)

![5c13f6bb-d74b-440e-9bc7-348cdc176c91](https://user-images.githubusercontent.com/27441315/51656931-17be7980-1fa3-11e9-8cf2-90b425762ad4.png)

### Versions

- Browser/version: Chrome 61
- uBlock Origin version: 1.17.4

### Settings

- Default settings

### Notes

Scroll down and click on the download links.

**Comment by okiehsch** [comment]
Option1 works without an anti-adblock issue on my end.

**Comment by lain566** [comment]
Yes, that seems to work, but the problem is that these domains `vida-saludable24.com` `quehosting.club` change constantly

**Comment by okiehsch** [comment]
I don't think anything can be done about that.

**Comment by lain566** [comment]
You're right, I think that's better, than having nothing

**Comment by okiehsch** [comment]
Best I can come up with is 
````
acortar.xyz##+js(addEventListener-defuser.js, mousedown, trigger)
acortar.xyz##+js(set-constant.js, Ok, true)

````
That will disable right clicking altogether but I don't think that is really needed on that site, what do you prefer?

**Comment by lain566** [comment]
@okiehsch There's a new domain, can you add these filters?
```
eshort.live##+js(set-constant.js, t, true)
||eshort.live^$popunder
```

`https://www.descargatelocorp.com/windows-10-aio-x86x64-espanol/`

![dd93546d-bf67-4d60-84aa-db455c3abebb](https://user-images.githubusercontent.com/27441315/53520734-a2305680-3ad6-11e9-927a-478c2672114a.png)
