### ISSUE TITLE
Need help with filter on Mastergrad.com

### ISSUE THREAD

**Issue by fedorvinogradov** [uBlockOrigin/uAssets#472]
### URL(s) where the issue occurs

`http://www.mastergrad.com/`

### Describe the issue

If the website sees you're using an adblocking software it shows a big annoying warning. Creating a filter doesn't help - the warning window appears after a while.

### Screenshot(s)

Website warning:
![adblock_warning](https://user-images.githubusercontent.com/12083751/27508378-e392d202-58eb-11e7-9d5b-42c5a7691f1a.jpg)

Website without warning:
![how_it_should_be](https://user-images.githubusercontent.com/12083751/27508376-e334a376-58eb-11e7-87d2-622f2e4e3a94.jpg)

Filter which hides this warning at the moment of creation of the filter:
![suggested_filter](https://user-images.githubusercontent.com/12083751/27508375-e3341d3e-58eb-11e7-9b4a-a2829139649e.jpg)

Stored filter:
![created_filter](https://user-images.githubusercontent.com/12083751/27508374-e2f7d040-58eb-11e7-83a6-c7837ed3a501.jpg)

### Versions

- Browser/version: Firefox 54.0
- uBlock Origin version: 1.13.0

### Settings

- only 1 created filter (see screenshots)

### Notes

no notes

**Comment by mapx-** [comment]
add
`@@||mastergrad.com^$generichide`

**Comment by fedorvinogradov** [comment]
Thanks a lot.
Where can I read how to do these filters, so it doesn't look like magic? :)

**Comment by mapx-** [comment]
you could read:
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax
https://adblockplus.org/en/filters

**Comment by SMed79** [comment]
In uBo Filter lists tab, enable the **[Adblock Warning Removal List](https://adblockplus.org/subscriptions#type_other)**.

![https://easylist-downloads.adblockplus.org/antiadblockfilters.txt](http://i.imgur.com/Dz3eDHV.png)

**Comment by fedorvinogradov** [comment]
Thanks to all
