### ISSUE TITLE
torrentrapid.com

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#4728]
### URL(s) where the issue occurs

`http://torrentrapid.com/`

### Describe the issue

Website redirects when clicked anywhere on the page.

### Versions

- Browser/version: Chorme 71
- uBlock Origin version: 1.17.4

### Settings

- Default settings.

**Comment by smed79** [comment]
admeasures popup
```
||subdo.torrentrapid.com^
||domaintrp.torrentrapid.com^
```
mining
```
||tercabilis.info^
$csp=worker-src 'none',domain=torrentrapid.com
```
