### ISSUE TITLE
addictivetips.com - Anti Adb

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#474]
Anti adb warning is displayed on http://www.addictivetips.com.

**SS:** https://i.imgur.com/LiqV3Nu.png
**Error URL:** http://www.addictivetips.com/web/how-to-restart-chrome/

As can be seen in the screenshot they are using Admiral (https://www.getadmiral.com). One way to stop the anti adb warning is: `||shelterstraw.com^`

_**Note:** Using uBO 1.13.2 on Chrome 59 with the default filters and settings._

**Comment by okiehsch** [comment]
Already [fixed](https://github.com/uBlockOrigin/uAssets/commit/7da2415d0e4e375c221c9e69d98de507a6b42a46).

**Comment by gotitbro** [comment]
Sorry missed that. Thanks for fixing it.
