### ISSUE TITLE
reCAPTCHA not working on 4chan

### ISSUE THREAD

**Issue by wooque** [uBlockOrigin/uAssets#4740]
### URL(s) where the issue occurs

`https://boards.4chan.org/r9k/catalog`

### Describe the issue

Recaptcha does not work when you try to start a new thread.
URL blocked https://www.google.com/recaptcha/api2/reload?k=6Ldp2bsSAAAAAAJ5uyx_lx34lJeEpTLVkP5k04qc

### Screenshot(s)

![2019-01-27-000109_945x982_scrot](https://user-images.githubusercontent.com/1936195/51793805-c4c50c00-21c6-11e9-92c9-fe512b6cdd17.png)

### Versions

- Browser/version: Chromium 71.0.3578.98 on Arch Linux
- uBlock Origin version: 1.18.2

### Settings

None

### Notes

/

**Comment by mapx-** [comment]
update `ublock filters` then test again

**Comment by mapx-** [comment]
weird, I get only
`||www.google.com/recaptcha/api2/reload?k=6Ldp2bsSAAAAAAJ5uyx_lx34lJeEpTLVkP5k04qc$xmlhttprequest,domain=www.google.com`

**Comment by okiehsch** [comment]
With Chromium?

**Comment by mapx-** [comment]
chrome beta

**Comment by okiehsch** [comment]
Chrome stable also requests `google.com/recaptcha/.......$xmlhttprequest,domain=boards.4chan.org`

**Comment by wooque** [comment]
Updated the filters and now it's working. 
Thanks for the fix @okiehsch
