### ISSUE TITLE
politize.com.br

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#4745]
### URL(s) where the issue occurs

`https://www.politize.com.br/`

### Describe the issue

Email newsletter overlay annoyance. Wait for the page to load completely then move your mouse cursor to another tab.

### Versions

- Browser/version: Firefox 64.0.2 (64-bit)
- uBlock Origin version: 1.18.0

### Settings

+Adguard Annoyances + uBlock Origin Annoyances

**Comment by mapx-** [comment]
add
`politize.com.br##.popup-overlay, .popup-content`

and report it to `fanboys annoyances` or `Adguard Annoyances`

**Comment by adranger** [comment]
@AdamWr

**Comment by adranger** [comment]
@mapx- links stop working if the overly is only hidden.

**Comment by mapx-** [comment]
more details ? what to click, what does not work..?

**Comment by adranger** [comment]
The hidden overlay was blocking everything, but `​##.rdstation-popup-newsletter` solves it.
