### ISSUE TITLE
xhamster.*

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uAssets#4747]
### URL(s) where the issue occurs

"NSFW" 
`https://xhamster.one/videos/young-german-housewife-slut-real-sexdate-homemade-porn-10803193`

### Describe the issue

Sponsored videos

### Screenshot(s)

"NSFW" 
https://i.imgur.com/olVpin0.png

### Versions

- Browser/version: [1.18.3b0]
- uBlock Origin version: [Opera|Beta]

### Settings

-  uBO's default settings

**Comment by mapx-** [comment]
add
`xhamsterpremium.com##.aside-thumbs__main:has(a[href*="/click"])`

auto-promo ..

**Comment by P0Rtvine** [comment]
`https://xhamster.com/` `https://xhamster.*/`

### Screenshot(s)
<details>
<summary>Screen</summary>

![2021-02-05_091115](https://user-images.githubusercontent.com/57287308/107001442-4c6c8a80-6792-11eb-9e3e-0814423a17bc.png)
</details>

### Versions

- Browser/version: Google Chrome
- uBlock Origin version:  1.33.2

### Settings
<details>
<summary>Screen</summary>

![2021-01-22_100714](https://user-images.githubusercontent.com/57287308/105464158-c3395c00-5c99-11eb-965b-81215d8f7bec.png)
</details>

**Comment by P0Rtvine** [comment]
`https://xhamster.one/videos/german-young-teen-guy-fuck-his-teacher-milf-after-school-9480653`

### Screenshot(s)
<details>
<summary>Screen</summary>

![2021-02-05_091115](https://user-images.githubusercontent.com/57287308/107003667-d10cd800-6795-11eb-845d-4b111f72bba3.png)
</details>

**Comment by okiehsch** [comment]
Fixed the ad, can't reproduce the anti adblock message.

**Comment by P0Rtvine** [comment]
This is not an anti adblock

### Screenshot(s)
<details>
<summary>Screen</summary>

![2021-02-05_140728](https://user-images.githubusercontent.com/57287308/107031948-acc3f200-67bb-11eb-921d-0b9d30bed088.png)
</details>

[xhamster.zip](https://github.com/uBlockOrigin/uAssets/files/5932393/xhamster.zip) - Page snapshot

**Comment by okiehsch** [comment]
Ok, sorry I misunderstood.
You want us to circumvent the parental control warning.
I don't think that is possible without the ability to set a cookie and uBO does not support that.

**Comment by dportvine** [comment]
`https://xhamster.com/`

<details>
<summary>Screenshot(s)</summary>

![2023-08-24_141409](https://github.com/uBlockOrigin/uAssets/assets/111344219/b3cdbd66-482d-4e5f-a6aa-3803163a18df)
</details>

<details>

```yaml
uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 115847
 cosmetic: 61803
 scriptlet: 23258
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-annoyances: 5385-10, 1m
 default:
  user-filters: 0-0, never
  ublock-filters: 34342-36, 1m
  ublock-badware: 7776-0, 1m
  ublock-privacy: 535-0, 1m
  ublock-unbreak: 2116-1, 1m
  ublock-quick-fixes: 226-42, 1m
  easylist: 69599-258, 1m
  easyprivacy: 33308-84, 1m
  urlhaus-1: 5966-0, 1m
  plowe-0: 3726-1067, 1m
  RUS-0: 39749-162, now
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 cacheStorageAPI: indexedDB
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 1245 ms (selfie)
 maxAssetCacheWait: 674 ms
popupPanel:
 blocked: 35
 network:
  xhamster.com: 28
  googletagmanager.com: 1
  makemehappy.mom: 1
  tsyndicate.com: 2
  xhcdn.com: 3
 extended:
  ##.video-thumb[class*="__look-like-item"]
  ##div[class*="cams-widget"]
  ##[href*="/faphouse/out"]
  ##div[class*="premium-overlay"]
  ##+js(addEventListener-defuser, , pop)
  ##+js(set-constant, initials.yld-pdpopunder, )
  ##+js(set-cookie, ts_popunder, true, , reload, 1)
  ##+js(replace-node-text, script, popunder, , condition, popunder…
  ##+js(cookie-remover, video_view_count)
```
</details>

**Comment by dportvine** [comment]
`https://xhamster.com/`

<details>
<summary>Screenshot(s)</summary>

![2023-09-11_121116](https://github.com/uBlockOrigin/uAssets/assets/111344219/04620407-28fd-44bf-9b02-0546ab3e40fe)
</details>

<details>

```yaml
uBlock Origin: 1.52.0
Chromium: 116
filterset (summary):
 network: 114844
 cosmetic: 128815
 scriptlet: 26212
 html: 0
listset (total-discarded, last-updated):
 removed:
  urlhaus-1: null
  plowe-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 26354-18, now
  https://easylist-downloads.adblockplus.org/cntblock.txt: 1646-26, now
  https://www.awwwwesome.org/url-blocklist/url-blocklist.txt: 765-0, now
  fanboy-cookiemonster: 48379-413, now
  ublock-annoyances: 5458-59, now
  ublock-cookies-easylist: 288-288, now
 default:
  user-filters: 0-0, never
  ublock-filters: 34515-44, now
  ublock-badware: 7956-0, now
  ublock-privacy: 558-8, now
  ublock-unbreak: 2131-7, now
  ublock-quick-fixes: 261-44, now
  easylist: 70381-290, now
  easyprivacy: 33248-403, now
  RUS-0: 39911-289, now
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 cacheStorageAPI: indexedDB
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 1046 ms (selfie)
 maxAssetCacheWait: 608 ms
popupPanel:
 blocked: 15
 network:
  xhamster.com: 8
  channelvids.online: 1
  googletagmanager.com: 1
  tsyndicate.com: 2
  xhcdn.com: 3
 extended:
  ##.parental-bg
  ##.parental-control
  ##.video-thumb[class*="__look-like-item"]
  ##div[class*="cams-widget"]
  ##[href*="/faphouse/out"]
  ##div[class*="premium-overlay"]
  ##.twitter
  ##.footer__socials
  ##.cookies-modal:not(body):not(html)
  ##body,html:style(overflow: auto !important; position: initial !…
  ##.thumb-list > .video-thumb:style(margin-right: 0px !important;…
  ##+js(remove-class, xh-thumb-disabled, , stay)
  ##+js(addEventListener-defuser, , pop)
  ##+js(set-constant, initials.yld-pdpopunder, )
  ##+js(set-cookie, ts_popunder, true, , reload, 1)
  ##+js(replace-node-text, script, popunder, , condition, popunder…
  ##+js(cookie-remover, video_view_count)
  ##+js(no-fetch-if, ad.php)
```
</details>

**Comment by stephenhawk8054** [comment]
Hmmm... I can't reproduce with annoyance list enabled.

**Comment by dportvine** [comment]
At the moment I can't reproduce with/without annoyance list.
