### ISSUE TITLE
reddit.com - Missed Ads

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#475]
"**PROMOTED**" ads are displayed on the mobile site of **_reddit_** https://www.reddit.com.

**SS:** 
https://i.imgur.com/83itxhS.png (Full page screenshot showing ad on the page)
https://i.imgur.com/TJYKAtK.png (Network panel showing possible ad origin)

**Error URL:** https://www.reddit.com/r/technology

These ads seem to be loaded through webpack such as:
`webpack:///./src/app/actions/ads.js`

I don't know how to block these ads. Please see what can be done.

**PS:** Sourcepoint were also detecting adblock on their [website](https://www.sourcepoint.com/) using webpack. Not sure if they are now.

_**Note:** Using uBO 1.13.2 on Chrome 59 with the default filters and settings._

**Comment by gotitbro** [comment]
That was easier than I though, the promoted ads can be blocked by:
`||reddit.com/api/request_promo`

**Comment by SMed79** [comment]
`||reddit.com/api/request_promo.json?`

**Comment by okiehsch** [comment]
I can't reproduce so @gorhill will have to fix this issue.

**Comment by SMed79** [comment]
> I can't reproduce so

check using a mobile user agent; [https://reports.adblockplus.org/3e4d92ed-84be-4629-8db2-..](https://reports.adblockplus.org/3e4d92ed-84be-4629-8db2-32e10f761956)

**Comment by okiehsch** [comment]
Sorry, I missed the  "**mobile** site of reddit" part, I can reproduce and will fix it.
