### ISSUE TITLE
title and description

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#4756]
please add title and description in header in all uAssets, i.e.:

```
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt

```

**Comment by patrickdrd** [comment]
@ameshkov take a look at this:
![screenshot_20190129-115528](https://user-images.githubusercontent.com/24896778/51900204-5eeea500-23bd-11e9-8a55-bdd138b5da2b.png)

**Comment by patrickdrd** [comment]
the first one is badware and resource-abuse is displaying like this (it's missing from the picture),
the worst of them is privacy, which doesn't display anything!

**Comment by ameshkov** [comment]
@patrickdrd that's an issue of the previous AG for Android Nightly, I doubt it should be reported here.

Also, you can now specify the title for a custom filter when you add it.

**Comment by bogachenko** [comment]
@ameshkov 

> you can now specify the title

при каждом добавлении списка я самостоятельно должен вписывать? это перекладывание проблемы на пользователей.

**Comment by patrickdrd** [comment]
@ameshkov I reported it here because in all these three files both title and description is missing if you open it, the others (ublock ones) work fine, as you can see for unbreak above, maybe they should add it on top inside the file and not me, that's my suggestion
