### ISSUE TITLE
Remove "softonic.net" from "Badware risks"?

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uAssets#476]
I just received an email from Softonic, with the following statement:

> It has recently come to our attention that our site, softonic.com, is fully blocked by uBlock Origin.
I would like to discuss with you or with someone from your team about a reconsideration process: since early 2015 we have stopped completely our installer/downloader product and we have aggressively pushed out potentially dangerous software from our catalog, checking constantly our software against Virus Total and our URLs against Google Safe Browsing.
> In fact, the articles about Softonic that are listed in the Badware Risks list on your site (https://github.com/gorhill/uBlock/wiki/Badware-risks) are all prior to 2016.
> 
> We have worked hard these last years to offer to our users a clean and safe environment and it would be very nice that blockers like yours reflected those efforts. 

I would like people to confirm this. If confirmed, I will remove it from _Badware risks_.

**Comment by Hrxn** [comment]
Is this the same site as [Softonic.com](https://en.wikipedia.org/wiki/Softonic.com)? Seems like it..

> Softonic International 
Ed. Media TIC
Carrer de Roc Boronat, 117, Planta 6
08018 Barcelona, Spain

This should be it..
Apparently an [office building](https://goo.gl/maps/jyu8VLSgJ2R2) in Barcelona, Spain.
Maybe someone of the users here from Barcelona can tell more, or pay them a short visit or something, nothing beats in person experience ;-)

**Comment by SMed79** [comment]
Their browser hijacker `search.softonic.com` still alive.

softonic will still blocked my hosts file.

**Comment by gorhill** [comment]
@SMed79 I see a search web page at "search.softonic.com", what do you mean by "browser hijacker"?

I just want to know if their downloads still has a reputation of being ladden with badwares.

**Comment by okiehsch** [comment]
I checked a few files, all were clean downloads without any added downloader or installer.

**Comment by gorhill** [comment]
@okiehsch Thanks for checking. I will just go ahead and remove it for now, and put it back if cases of badware are reported.
