### ISSUE TITLE
AntiAdblock warnings, Cookies warnings and video playback.

### ISSUE THREAD

**Issue by Jose1971AB** [uBlockOrigin/uAssets#4760]
Hello friends ... I hope you are well. Let's see if you can solve this.

**First of all, excuse my translation. I have helped myself with the google translator.**

I have a laptop with Windows 7 home premium 64Bit

Mozilla Firefox64Bit 65.0

- Extensions
Cookie Autodelete
ImTranslator
TrafficLight (Bitdefender)
uBlock origin (see filters below)
Violentmonkey (with 2 scripts; Popup Blocker by AdGuard and AdsBypasser).

List of uBlock filters Filters (I can send the Custom URLs if required). See images ->
**http://img.fenixzone.net/i/02kPYic.png**
**http://img.fenixzone.net/i/H7PiQ8d.png**

For all the cases I have been deactivating and activating both extensions and filters, conjugating them randomly and I have not been able to solve anything (except in the 2nd case).

I put some URLs in which in each of them I explain the problem.

Start...

**1st CASE**
**https://www.technodyan.com/ -> AntiAdblock warning**
**https://www.elespanol.com/ -> AntiAdblock warning**
**https://www.atresplayer.com/directos/antena3/ -> AntiAdblock warning**

**Note 1:**
In the case of **https://www.elespanol.com/** it does not matter if you open directly the main page of that newspaper or through any link that I open from Facebook, Twitter or Gmail. I always get the warning.
 
In this case you can close by clicking on the "X" of the warning and you can continue browsing quietly, but it may be that in the not too distant future it can not be done, or, as with other websites, if you close the warning the page is unusable

**Note 2:**
In the case of **https://www.atresplayer.com/directos/antena3/** I think it's all over the web, not just in the Live section.

Also, whether you use the **Element Removal Mode** or the **Element Selection Mode** the page is obscured and unusable.

**Note 3:**
In the case of **https://www.technodyan.com/** most of the times the notice appears when entering the page. It can also happen that you enter it and it does not appear but if you refresh the page the warning appears. Similarly, if I enter the page and the notice does not appear when I click on any of the news when entering, it appears.

**See the images ->**
**https://www.technodyan.com/ --> http://img.fenixzone.net/i/z7n9jwe.png**
**https://www.elespanol.com/ --> http://img.fenixzone.net/i/aTDUNMp.png**
**https://www.atresplayer.com/directos/antena3/ --> http://img.fenixzone.net/i/7MYoFh1.png**

**2NDO CASE**
**http://www.periodistadigital.tv/los-terroristas-del-isis-atacan-un-avion-ruso-y-este-los-caza-como-conejos_bc7a2d39a.html ->**
**I can not play videos**, nor those that come in the video section of this newspaper (address that I indicate), nor those that are immersed in any normal news.

In this case I think it's because of **uBlock filter** (Included in the List of filters tab) because disabling it if you play it. I deactivated all the filters and I was testing one by one, playing the videos without problems, but when I reached the ublock filter and activated it, it was not played anymore.

I would not like to disable **uBlock filter** because it contains the url of the pages that detect Adblock (or uBlock) and if I deactivate it for that page, the others are unprotected.

**See the image -> http://img.fenixzone.net/i/1Vg8est.png**

**3rd CASE**
**https://wetransfer.com/ -> Cookies notice when you enter the homepage.**

It is not a window in which it presents the notice as it usually happens and I explain in the previous cases, but it includes the whole page. You have to accept force to use it. The page appears obscured until you accept cookies.

**See the image ->http://img.fenixzone.net/i/biFRacz.png**

Well ... this is all, I hope it can be solved.

**Good evening, thank you very much and greetings.**

**Comment by okiehsch** [comment]
1. `https://www.technodyan.com/ `
Fix:  `technodyan.com##+js(abort-on-property-read.js, anOptions)`

2. https://www.elespanol.com/
Fix: `@@||eestatic.com/*/adsbygoogle.js$script,domain=elespanol.com`

3. `https://www.atresplayer.com/directos/antena3`
Already fixed in the regional lists. Enable these two lists on your end.
![image](https://user-images.githubusercontent.com/16838044/51947767-4f577680-2426-11e9-8802-6b3f2518e5d6.png)

4. `http://www.periodistadigital.tv/los-terroristas-del-isis-atacan-un-avion-ruso-y-este-los-caza-como-conejos_bc7a2d39a.html`
Fix: `@@||static.sunmedia.tv/integrations/*$script,domain=periodistadigital.tv`

5. `https://wetransfer.com`
Can not be fixed with `uBO`, you will have to accept cookies.

**Comment by Jose1971AB** [comment]
Hi friend...

I want to tell you something ...

**1ERO**
**https://www.technodyan.com/ -> It works**
**https://www.elespanol.com/ -> It works**

**2NDO**
**You say for https://wetransfer.com/ ->**
You can try adding wetransfer.com ##. Welcome__container. the filter for https://wetransfer.com (wetransfer.com ##. welcome__container)

I have not added it because I do not know where or how to do it, I mentioned earlier that I was a very basic user and in the Help page that you indicated to me the previous time that you attended me, I can not find how to do it.

**Could you tell me how and where to do it? ...**

**3ERO -> Here comes the mess. I will try to explain ...**

**The tangle is caused by these two pages. ->
https://www.atresplayer.com/directos/antena3 And http://www.periodistadigital.tv/los-terroristas-del-isis-atacan-un-avion-ruso-y-este-los-caza-como-conejos_bc7a2d39a.html along with the two filters in Regions and languages ​​that you told me to activate for https://www.atresplayer.com/directos/antena3**

**spa: EasyList Spanish
spa, by: AdGuard Spanish / Portuguese filter**

Okay...

- **If I activate the two filters ->** it works for https://www.atresplayer.com/directos/antena
- **If I activate only spa, by: AdGuard Spanish / Portuguese filter ->** also works for https://www.atresplayer.com/directos/antena
- **If I activate only spa: EasyList Spanish ->** It does not work for https://www.atresplayer.com/directos/antena

**The supposed solution for https://www.atresplayer.com/directos/antena3 would** be to leave the two filters activated or only the one that works, logically.

**But now there is one thing that is where the mess is ..**.

**The filter that you sent me for http://www.periodistadigital.tv/los-terroristas-del-isis-atacan-un-avion-ruso-y-este-los-caza-como-conejos_bc7a2d39a.html causes conflict with one of the Regions and Languages ​​filters because it solves https://www.atresplayer.com/directos/antena** **but it does not solve http://www.periodistadigital.tv/los-terroristas-del-isis-atacan-un-avion-ruso- and-this-the-hunt-as-bunnies_bc7a2d39a.html**

If I deactivate one of the two filters so that it works http://www.periodistadigital.tv/los-terroristas-del-isis-atacan-un-avion-ruso-y-este-los-caza-como-conejos_bc7a2d39a.html **the opposite happens, which does not work for https://www.atresplayer.com/directos/antena**

Correct me, but **I think the filter that causes the conflict is spa, by: AdGuard Spanish / Portuguese filter**

**I know it is a little tangled, but if you read carefully you will realize what I want to explain to you.**

According to the configuration of filters that I sent you at the beginning and as it is now with the two Regions and languages ​​added ... **what solution could be given? ...**

I hope patiently.... thank you very much and greetings.

**Comment by Jose1971AB** [comment]
DISCUSS FRIEND ... DO NOT CLOSE THE CASE !!! ... I was wrong and I closed the case without noticing

**Comment by mapx-** [comment]
needing
@@||static.sunmedia.tv/integrations/$script,domain=api.gooru.live

**Comment by Jose1971AB** [comment]
Hello again friends ... mapx and okiehsch and to all who lend themselves to solve this.

First of all ... **DO NOT CLOSE THE CASE PLEASE**

To not repeat the same, if you read from the beginning this thread you can check what I'm going to say.

**It seems that everything works less for ->**

https://www.atresplayer.com/directos/antena3/ (Adblock notice)
http://www.periodistadigital.tv/los-terroristas-del-isis-atacan-un-avion-ruso-y-este-los-caza-como-conejos_bc7a2d39a.html

Right now I have added in uBlock everything that has been indicated to me so far, the last thing has been what mapx has indicated, add in My filters -> @@ || static.sunmedia.tv/integrations/$script, domain = api.gooru.live

Ok ... well, as I explained in my previous answer, which I closed by mistake, the same problem happens again.

Either it does not work https://www.atresplayer.com/directos/antena3/ (warning Adblock) or it does not work http://www.periodistadigital.tv/los-terroristas-del-isis-atacan-un-avion- russian-and-this-the-hunter-like-bunnies_bc7a2d39a.html

In this case and as a result of adding @@ || static.sunmedia.tv/integrations/$script,domain=api.gooru.live the missing page is https://www.atresplayer.com/directos/antena3/

With this filter the page is broken and unusable. Totally black.

I know it is because of the new filter (or parameter) because I have removed it from the My filters tab and it has been seen.

I have tried again deactivating and activating everything that has been indicated to me and combining them randomly, and after doing several tests I have come to the conclusion that there are two things that cause conflicts ...

One is the last indicated by mapx @@ || static.sunmedia.tv/integrations/$script,domain=api.gooru.live and the other is one of the two filters that okiehsch told me to activate in Filter Lists, which es spa, by: AdGuard Spanish / Portuguese filter

That is, that either one fails or the other fails

Well ... let's see what happens to you, I'll wait for you.

Thank you very much, good afternoon and greetings

**Comment by mapx-** [comment]
Well, your issue now is only with atresplayer, right ?
It's working fine for me.

1. reset uBo to the **default setup**.
2. then add **only the 2 spanish lists** (no other of the lists you posted above)
3. all the filters in this thread were already added in ublock filters, so **don't add other custom filters**.
4. test again.

**Comment by Jose1971AB** [comment]
Hello again mapx

Due to the google translator I do not know if I have understood what you are saying in your answer.

Once uBlock is reset, I think you are referring to the test as it is uBlock by default (with all the filters that activate by default). I'm going to try it this way. If you want me to do it with just the two Regions and Languages ​​filters, it tells me. By the way, the two filters that you say you activate are already activated by default in uBlock.

I will also take advantage of all the urls I have sent.

uBlock defaults to me like this. See the image

http://img.fenixzone.net/i/rj4sCMY.png

1.- I perform the tests only with the filters that uBlock brings by default

https://www.technodyan.com/ --> Adblock notice

http://img.fenixzone.net/i/JODgKqS.png

https://www.elespanol.com/ --> It works

https://wetransfer.com/ --> Cookie notice. In a white box.

http://img.fenixzone.net/i/Wu9JMLF.png

https://www.atresplayer.com/directos/antena3/ --> There is no Adblock notice but there is a "accept cookies" notice that occupies half screen and you have to accept to be able to browse.

http://img.fenixzone.net/i/ekTSwap.png
 
http://www.periodistadigital.tv/los-terroristas-del-isis-atacan-un-avion-ruso-y-este-los-caza-como-conejos_bc7a2d39a.html --> There is a notice to "accept cookies" that occupies half screen and that you have to accept forcefully to be able to navigate. When you close that warning, another one of the same type appears on the right side of the screen. The video if it plays.

http://img.fenixzone.net/i/iTC0BZY.png

When you accept the first notice of cookies, another one appears. See below the red box on the right side

http://img.fenixzone.net/i/LZExIOP.png

Well, friend, I'm waiting for you ...

Thank you

**Comment by mapx-** [comment]
The last issue is `technodyan` , right ?
Enable `uBlock filters – Annoyances` (from the first group of lists `incluidos`) and `technodyan` will work too.

The cookies are not a serious issue, however, you could try enabling this list `Fanboy's Cookie List`

Please - if you still have issues - report only the remaining issue (not all of fixed problems again)

**Comment by okiehsch** [comment]
- `technodyan.com`--> Adblock notice 
Enable `uBO-annoyances`
![image](https://user-images.githubusercontent.com/16838044/52084906-6e2f4780-25a3-11e9-897c-dc1cf65cf5e4.png)

- https://wetransfer.com/ --> Cookie notice.
Add `wetransfer.com##.welcome__container` to your own filter list.
![image](https://user-images.githubusercontent.com/16838044/52085150-01687d00-25a4-11e9-8782-d886b7537839.png)

**Comment by mapx-** [comment]
And - another thing: don't add all those initial lists => as you can see have the potential to break some pages. 
Here we can help if the user is using the standard (default) settings.

**Comment by Jap2-0** [comment]
uBlock filters - Annoyances doesn't fix it.  It only appears the first time you visit the site (removing cookies for technodyan.com shows it again).  It looks like the following two filters fix it:

`technodyan.com##.SBPDPynToCXz`
`technodyan.com##.SBPDPynToCXz-bg`

**Comment by Jose1971AB** [comment]
Hello mapx ...

The last subject in my answer let's say it's http://www.periodistadigital.tv/los-terroristas-del-isis-atacan-un-avion-ruso-y-este-los-caza-como-conejos_bc7a2d39a.html and https : //www.atresplayer.com/directos/antena3/ which are the ones that do not work.

Well ... I'm going to tell you about the tests.

The test I have done also including in the My filters tab the parameter indicated by my partner okiehsch, that is ->

**uBlock by default + Fanboy's Cookie List + wetransfer.com ##. welcome__container (My filters tab)**

The problematic pages remain the same. (the other url if they work) ->

- http://www.periodistadigital.tv/los-terroristas-del-isis-atacan-un-avion-ruso-y-este-los-caza-como-conejos_bc7a2d39a.html
- https://www.atresplayer.com/directos/antena3/

If you do not activate Fanboy's Cookie List, the cookie notice appears on http://www.periodistadigital.tv/los-terroristas-del-isis-atacan-un-avion-ruso-y-este-los-caza-como -connejos_bc7a2d39a.html **as in** https://www.atresplayer.com/directos/antena3/

**If Fanboy's Cookie List is active, only the cookies notice appears in** https://www.atresplayer.com/directos/antena3/ **and it also seems that it retains a little the load of the page**, the tab appears but stays for a moment blank until it loads, that's more or less, it has happened to me several times when trying with the pages, although this would have to observe it more carefully because it could be punctual, I do not know.

**Important note:** This is a mapx part. You say in one of your answers (if the google translator has not failed me) that you do not add again the filter lists that you had configured because they broke the pages, and that you lent support to us users, **do you mean the Personalized or custom lists?. When we finish this thread, if you do not mind, I would like and I would appreciate asking you something about this and to advise me.**

Well ... I wait for you and thank you very much always.

A greeting

**Comment by mapx-** [comment]
sorry, I don't understand your issues.

What does not work now ? Eventually explain in your language (spanish I guess).
`atresplayer` => I can test it partially because it asks me to subscribe something.

**Comment by mapx-** [comment]
If you don't use fanboys cookie list, close manually the cookies messages, does it work for you ?

**Comment by mapx-** [comment]
click "accept" only once and then you can use the site.

Well, that's nothing more we can do here, closing.

**Comment by Jose1971AB** [comment]
Hello again.

Looks like it's going better now.

Thank you very much to all of you who have advised me.

Greetings.
