### ISSUE TITLE
jiosaavn.com{Breakage}

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4761]
### URL(s) where the issue occurs

`https://www.jiosaavn.com/album/phool-aur-angaar/6etmWPjohJo_`

### Describe the issue

Not able to play song, probably broken by filters @smed79 @ryanbr
jiosaavn is big website here in india
### Versions

- Browser/version: firefox 65
- uBlock Origin version: 1.18.2

### Settings

- uBO's default settings

**Comment by mapx-** [comment]
@ryanbr
