### ISSUE TITLE
songspkmania.in

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4762]
### URL(s) where the issue occurs

`https://songspkmania.in/phool-aur-angaar-1993-mp3-songs-download/`

### Describe the issue

caught with malwares when visiting the website ,clicking `320kbps/download` and even if i do not save/download the file on click of 320kbps/download , malware got into system detected as `W32.Adware.Gen`
### Versions

- Browser/version: firefox65
- uBlock Origin version: 1.18.2

### Settings

- uBO's default settings

**Comment by mapx-** [comment]
try
```
songspkmania.in##[href^="http://type.fastdomain.site/"]
||update.chistilka.com^$document
||fastdomain.site^$document
```

@ryanbr

**Comment by ghajini** [comment]
still there are other unknown/malicious 3rd parties

**Comment by mapx-** [comment]
add also
```
||brendmus.xyz^
||usertag.online^
```

**Comment by mapx-** [comment]
Are you sure you got infected ? How to you know ? Sometimes the antivirus (especially if web shields are enabled) warns about the (malicious) links on page
