### ISSUE TITLE
Gamepedia Instart block breaks wikis

### ISSUE THREAD

**Issue by assignUser** [uBlockOrigin/uAssets#4767]
### URL(s) where the issue occurs

`https://pathofexile.gamepedia.com/The_Wretched`

### Describe the issue

The Instart block
`gamepedia.com##+js(abort-current-inline-script.js, RegExp, Instart)`
discussed in #2468 now seems to break the gamepedia wikis by blocking resource loading.
### Screenshot(s)

![image](https://user-images.githubusercontent.com/16141871/52045284-7d32dd00-2544-11e9-862d-839789136d62.png)

### Versions

- Browser/version: Chrome 72.0.3626.81
- uBlock Origin version: v1.17.4

### Notes

deactivating uBlock filter fixes this.

**Comment by okiehsch** [comment]
I can't reproduce
![image](https://user-images.githubusercontent.com/16838044/52046590-617d0600-2547-11e9-80b3-2e135198f817.png)

**Comment by mapx-** [comment]
However, I get `Instart` only as comment in the page source, otherwise `instart` or `INSTART`

**Comment by ghajini** [comment]
firefox affected

**Comment by mapx-** [comment]
no breakage in FF too, even using
`gamepedia.com##^script:has-text(/i10C/i)`

**Comment by okiehsch** [comment]
OK, I found the reason for the breakage, using Chrome if I disable `uBO-extra` the site breaks because of the g00 redirection.

**Comment by okiehsch** [comment]
I guess we can remove the filter, it does not work anymore anyway.

**Comment by mapx-** [comment]
adding
`gamepedia.com##+js(set-constant.js, JSON.parse, noopFunc)` 
or
`gamepedia.com##+js(set-constant.js, String.prototype.charAt, noopFunc)`

seems to reduce the number of g00 requests

**Comment by okiehsch** [comment]
> Well, yes, but they should all work the same, a generic filter wouldn't be possible?

````
gamepedia.com##+js(set-constant.js, JSON.parse, noopFunc)
gamepedia.com##+js(set-constant.js, String.prototype.charAt, noopFunc)
````
I still get redirected with those filters and they have the potential to break site functionality.
Maybe they don't I have not checked.
