### ISSUE TITLE
bild.de - Anti adb

### ISSUE THREAD

**Issue by spec1re** [uBlockOrigin/uAssets#477]
Since today bild.de is blocking Ad-blocker again

### URL(s) where the issue occurs

http://www.bild.de/

### Describe the issue

Redirected to block notice.

### Versions

- Browser/version: Firefox 54.0 (32-Bit)
- uBlock Origin version: v1.13.0

https://forums.lanik.us/viewtopic.php?p=120087#p120087

**Comment by AddyBlocky** [comment]
Yess, same here again, BILD.de changed something again, they wanna fight against uBlock Origin ;) But they will lose again, please fix!

![image](https://user-images.githubusercontent.com/29712965/27551940-b9e26b64-5aa5-11e7-9d60-c561044e5b49.png)

**Comment by spec1re** [comment]
https://forums.lanik.us/viewtopic.php?p=120093&#p120093

This is working for me. :)

**Comment by gotitbro** [comment]
They seem to be specifically targetting **_uBlock Origin_** users as is apparent by their message and their method of blocking access (for other adblock extensions they redirect to an anti adblocking page but an overlay message is presented to uBO users). Here is the message they display (translated by Google translate):

> Why do not I see BILD.de?
> A plugin in your browser corrupts the function of the website, so we can not give you access to the contents. 
> 
> You may be using Ublock Origin or another Adblocker plugin. If this is the case, please try to disable it.

@gorhill This needs to be looked into. Please check.

@spec1re The filter suggested in the EasyList forums `www.bild.de##script:contains(!de.bild.cmsKonfig)` does not work for me either in Google Chrome. One way to stop the anti adb message is:
`||bild.de$inline-script`

But this does break some functionality like the clicking of buttons.

**Comment by ghajini** [comment]
Another way is to use ublock protector extension if you are using chrome

`https://jspenguin2017.github.io/uBlockProtector/`

**Comment by spec1re** [comment]
@ghajini - This indeed works with Chrome. Thanks! :)

**Comment by AddyBlocky** [comment]
Yes, in Chrome the filter `www.bild.de##script:contains(!de.bild.cmsKonfig)` doesn't work at me either, and unfortunately I can't install the uBlockProtector extension at the moment. So I have to wait till the problem is solved directly in uBlock Origin and use filter `||bild.de$inline-script` (but this one breaks many functions) or allow ads for a time..

**Comment by gorhill** [comment]
> @gorhill This needs to be looked into. Please check.

Please. That is not the proper mindset. All the work here is done on a voluntary basis, never **demand** for somebody else to "look into" something. The proper mindset is to contribute a fix, not demand another specific volunteer to contribute a fix.

**Comment by spec1re** [comment]
> If I contribute a fix, I do it because I want to, not because you demanded it.

And this is very much appreciated! 💮

**Comment by okiehsch** [comment]
`bild.de##script:inject(abort-on-property-read.js, document.querySelector)`
fixes this issue but no clue if this breaks any site functionality.

**Comment by gorhill** [comment]
Does this work?

    bild.de##script:inject(abort-on-property-read.js, de.bild.cmsKonfig.a.a)

To try the above filter, the non-working one must be disabled first:

    bild.de#@#script:inject(abort-on-property-read.js, de.bild.cmsKonfig.a.b)

**Comment by okiehsch** [comment]
Your fix also works on my end and is far less likely to break anything.

**Comment by Hrxn** [comment]
> To try the above filter, the non-working one must be disabled first:

Explicitly disabled? Can't it just be removed from the 'My Filters' list?

**Comment by okiehsch** [comment]
It has been removed, he meant it had to be disabled for testing purposes.

**Comment by gotitbro** [comment]
@gorhill I apologize if it read like I was demanding a fix. Since the website was directly targeting uBO users I merely tried to bring your attention to it. 

I will keep in mind to maintain the wording in the ask for a response more precise. 


Thank you and all other contributors who work here on a voluntary basis.

**Comment by uBlock-user** [comment]
It's targeting every adblocker and not just uBO. It merely mentions uBO because that's the one actively bypassing it's anti adblock measures. Also this has been patched on uBlock Protector Extension so you don't need a fix if you have that installed.

**Comment by gotitbro** [comment]
@uBlock-user But it does mention **_uBlock Origin_** specifically and that seems concerning to me.

**Comment by spec1re** [comment]
uBlock/Firefox is blocked again. (Chrome is working fine with uBlockProtector)
