### ISSUE TITLE
softcore69.com [NSFW]

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#4773]
### URL(s) where the issue occurs

`softcore69.com`

### Describe the issue

Scroll down a bit to find an ad banner between the video list. Click any video to find an ad banner below it.

### Versions

- Browser/version: Firefox 65.0
- uBlock Origin version: 1.18.2

### Settings

Default

**Comment by okiehsch** [comment]
`softcore69.com##a[href^="https://trafficmedia.center/redirect/"]`

**Comment by in4u** [comment]
It works. Please update the filter list too. In fact, a generic rule like `##a[href^="https://trafficmedia.center/redirect/"]` might block ads from this network on other sites as well.

**Comment by mapx-** [comment]
@ryanbr

**Comment by in4u** [comment]
Guys, it's been over a fortnight and Easylist still hasn't included this in their list. Perhaps commit the filter suggested by @okiehsch in uBO at least.
