### ISSUE TITLE
sexvid.xxx [NSFW]

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#4777]
### URL(s) where the issue occurs

`sexvid.xxx`

### Describe the issue

Click any video to find an ad below it. Also, ads at the bottom of every video page (disguised as recommended section).

### Versions

- Browser/version: Firefox 65.0
- uBlock Origin version: 1.18.2

### Settings

Default

**Comment by okiehsch** [comment]
````
||sexvid.xxx/xdman/*$frame,1p
sexvid.xxx##.download_link
````
