### ISSUE TITLE
you-porn.com [NSFW]

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#4779]
### URL(s) where the issue occurs

`you-porn.com`

### Describe the issue

Click any video to play and then pause it to find an ad overlay.

### Versions

- Browser/version: Firefox 65.0
- uBlock Origin version: 1.18.2

### Settings

Default

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by mapx-** [comment]
I guess it's only annoyance
`you-porn.com##[id^="adblock"]`
