### ISSUE TITLE
doesn't work ordering.co

### ISSUE THREAD

**Issue by pol-ordering** [uBlockOrigin/uAssets#478]
### URL(s) where the issue occurs

*.ordering.co
orderingweb.ordering.co

eat247.ordering.co
www.eat247.co.uk

brandodelivery.ordering.co
www.brandodelivery.com

### Describe the issue

We're a company that make websites and apps, and all our pages that allowed in our domains couldn't be loaded. Blocks all the page.
It also happens with our clients who has our service in his own page. How to add ordering.co and all the websites who are an alias of our domain to a white-list?

Or what do we have to do to not block our page?

### Screenshot(s)
![image](https://user-images.githubusercontent.com/28957816/27555039-11ef04fa-5a76-11e7-9df5-c4c7126829b0.png)
![image](https://user-images.githubusercontent.com/28957816/27555129-66e615ca-5a76-11e7-9993-bc0e84234411.png)

### Versions

- Browser/version: All browsers.
- uBlock Origin version: 1.13.0

### Settings

- No changes

### Notes
If need to modify something in our code let us know, but we want that our page which doesn't have any ads be available for everyone.

**Comment by mapx-** [comment]
it's due to the easyprivacy filter
`-google-analytics.`

You have to report the issue to easylist forum, in this subforum:
https://forums.lanik.us/viewforum.php?f=64

**Comment by SMed79** [comment]
> Or what do we have to do to not block our page?

tell your developers to remove the dependency of the library "Angular Google Analytics".

**Comment by gorhill** [comment]
I question whether `-google-analytics.` is really needed. What is the point of this filter when `google-analytics.com` is already blocked?

It's common that the filter `-google-analytics.` will break pages, and a simple exception filter fixes the issue, without needing to create an exception filter for `||google-analytics.com^`, so what is there to gain with this filter?

**Comment by ryanbr** [comment]
Because there are wordpress scripts that implement google-analytics, and also standalone javascript implementation.

**Comment by gorhill** [comment]
> wordpress scripts that implement google-analytics

What do you mean by "implement google-analytics"?

[angular-google-analytics.js](https://github.com/revolunet/angular-google-analytics/blob/master/dist/angular-google-analytics.js) appears to be just an API layer on top of Google Analytics's own API, to be installed as a 1st-party script. Beside, such 1st party utility script is much more likely to deal graciously with the blocking of `google-analytics.com`, whereas custom 1st-party code will often fails to deal with this (as actually demonstrated here).

Isn't the end goal here to prevent **3rd-party** `google-analytics.com` from getting any data (including connection attempt), which end goal is still properly accomplished even if one allows that `angular-google-analytics.js` 1st-party script API layer?

**Comment by momala454** [comment]
the bug is back since the cname change

CNAME www.google-analytics.com ⇒
 www-google-analytics.l.google.com


the filter is -google-analytics.$3p

**Comment by mapx-** [comment]
Do you mean `orderingweb.ordering.co` is broken in FF on your end ? 
I cannot reproduce the issue.

Open the logger, refresh the page, select only the blocked items, post here the screenshots

**Comment by momala454** [comment]
ah, actually i tried the wrong url, i tried
`https://brandodelivery.ordering.co/`

but google analytics is blocked by the "ublock unbreak", due to the cname change

**Comment by gorhill** [comment]
> `https://brandodelivery.ordering.co/`

This site does not show anything even without uBO.

**Comment by momala454** [comment]
yes i noticed that but the problem is ublock unbreak is blocking google analytics on every site due to the cname change

**Comment by gorhill** [comment]
> ublock unbreak is blocking google analytics on every site due to the cname change

Exception filters are not overriden by cnamed hostnames. Please provide an actual case there is an issue.

**Comment by momala454** [comment]
you can see that on `https://orderingweb.ordering.co/` the query to
`https://www.google-analytics.com/analytics.js`
is blocked due to the filter
-google-analytics.$3p

from ublock unbreak

**Comment by gorhill** [comment]
It's blocked by Peter Lowe's list:

![a](https://user-images.githubusercontent.com/585534/79024463-fa96ac00-7b50-11ea-977a-512bd48b3d5d.png)

**Comment by momala454** [comment]
i don't use peter lowe

**Comment by momala454** [comment]
![image](https://user-images.githubusercontent.com/83005/79024587-bbce1980-7b83-11ea-96af-3b09c50c7744.png)

**Comment by gorhill** [comment]
So you do not use Peter Lowe's, neither EasyPrivacy, neither _"uBlock filters -- Privacy"_, but you use _"uBlock filters -- Unbreak"_ and want the latter to be modified to accommodate your custom configuration which would never ever be advised here?

Am I understanding this right?

**Comment by momala454** [comment]
i don't want any blocking of google analytics, i'm using unbreak as it seems to fix bugs on ublock, i don't see why unbreak should block google analytics ?

**Comment by gorhill** [comment]
We could move the whole section of rewritten block filters to _"uBlock filters -- Privacy"_ I suppose. These exist to unbreak what is in EasyPrivacy.

**Comment by momala454** [comment]
yes it seems to be the good solution.
But why those fix can't be done on easylist direct instead of relying on ublock specific fix ?
other adblockers don't support the features required ?

**Comment by gorhill** [comment]
> But why those fix can't be done on easylist direct

Maintainers of EasyPrivacy disagree with not blocking `-google-analytics`-like patterns as first party. I argued this too often breaks stuff and does not accomplish much since `google-analytics.com` is wholly blocked with default lists.

**Comment by gorhill** [comment]
I re-opening the issue since I can't make the change right now and I may end up forgetting about this. Meanwhile, maybe other maintainers will find an issue I am not thinking about if moving the rewritten EasPrivacy filters to _"uBlock filters -- Privacy"_.

**Comment by ryanbr** [comment]
There must be a better way to fix this.

`@@||www-google-analytics.l.google.com^$domain=google-analytics.com`  or `-google-analytics.$domain=~google-analytics.com` would that work?
