### ISSUE TITLE
sun-sentinel.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#4784]
### URL(s) where the issue occurs

`https://www.sun-sentinel.com/local/broward/pembroke-pines/fl-ne-pembroke-pines-hole-20190130-story.html`

### Describe the issue

Video/photos broken

### Notes

`@@trbas.com`

**Comment by yourduskquibbles** [comment]
@mapx- Other tronc sites also broken 

```
https://www.baltimoresun.com
https://www.capitalgazette.com
https://www.citypaper.com
https://www.dailypress.com
https://www.mcall.com
https://www.orlandosentinel.com
https://www.pacificsandiego.com
https://www.sandiegouniontribune.com
```

Domain format for the filter you can copy below
`baltimoresun.com,capitalgazette.com,citypaper.com,dailypress.com,mcall.com,orlandosentinel.com,pacificsandiego.com,sandiegouniontribune.com,`

Lemme know if you need example news pages or not, should be obvious just going to the main page though.

**Comment by mapx-** [comment]
Could you test this filter for all the domains ?
`@@||trbas.com/jive/$script,domain=baltimoresun.com|capitalgazette.com|chicagotribune.com|citypaper.com|dailypress.com|mcall.com|orlandosentinel.com|pacificsandiego.com|sandiegouniontribune.com|sun-sentinel.com`

**Comment by yourduskquibbles** [comment]
@mapx- looks good to me, images now work for all the sites and where I could find videos on the domains they all appear to work for me.

**Comment by yourduskquibbles** [comment]
@mapx- one exception can't get video to load on `https://www.mcall.com/sports/hockey/phantoms/mc-spt-flyers-rally-to-beat-bruins-20190131-story.html`

**Comment by yourduskquibbles** [comment]
Detailed test results

**video still broken:**
`https://www.mcall.com/sports/hockey/phantoms/mc-spt-flyers-rally-to-beat-bruins-20190131-story.html`

**video works for me:**
`https://www.baltimoresun.com/news/maryland/baltimore-city/bs-md-ci-wroblewski-killing-trial-20190131-story.html`

`https://www.capitalgazette.com/news/for_the_record/bs-md-fire-fighting-cold-20190131-story.html`

`https://www.chicagotribune.com/sports/`

`https://www.dailypress.com/videogallery/112751305-132.html`

`https://www.orlandosentinel.com/travel/112749702-132.html`

`https://www.sandiegouniontribune.com/visuals/112555255-132.html`

**Can't find video to test on:**
`https://www.citypaper.com/`

`https://www.pacificsandiego.com/`

**Comment by terrorist96** [comment]
> Detailed test results
> 
> **video still broken:**
> `https://www.mcall.com/sports/hockey/phantoms/mc-spt-flyers-rally-to-beat-bruins-20190131-story.html`

`@@ima3`

**Comment by yourduskquibbles** [comment]
Video broken on `chicagotribune.com`

Test site: `https://www.chicagotribune.com/sports/breaking/ct-spt-cubs-wscr-score-house-arizona-20190304-story.html`

Doesn't seem to be broken on any other site listed above
