### ISSUE TITLE
pinkertube.com (nsfw)

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#4785]
### URL(s) where the issue occurs

`[pinkertube.com]`

### Describe the issue

[Trying to watch a video will trigger anti-adblock.]

### Versions

- Browser/version: [Firefox mobile v63]
- uBlock Origin version: [1.18.2]

### Settings

- [default]

**Comment by mapx-** [comment]
mining stuff, to see the video you have to whitelist `coinhive.com` elements

**Comment by dumbusernameidk** [comment]
Possible to block any of the mining?

**Comment by okiehsch** [comment]
I get a connection timed out error.

**Comment by dumbusernameidk** [comment]
Same for as well which is odd since it was up earlier.

**Comment by mapx-** [comment]
if you want to enable coinhive mining try these filters:
@@||pinkertube.com^$generichide
@@||authedmine.com/lib/captcha.min.js$script,domain=pinkertube.com
@@||coinhive.com/lib/coinhive.min.js$script,domain=pinkertube.com
@@||coinhive.com/captcha/$subdocument,domain=pinkertube.com
@@||coinhive.com/captcha/captcha-ui.min.js$script,first-party
@@||coinhive.com/captcha/captcha.css$stylesheet,first-party

**Comment by dumbusernameidk** [comment]
does whitelisting these cause any mining? not very comfortable with sites hogging cpu resources.

**Comment by mapx-** [comment]
if you want to start the video first you have to click ok box (bellow the video) which will start the mining ! So, just abandon this crap ..

**Comment by dumbusernameidk** [comment]
Makes sense.
