### ISSUE TITLE
ctrl.blog 2

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#4787]
### URL(s) where the issue occurs

`https://www.ctrl.blog/entry/removing-webrequest-api`

### Describe the issue

Multiple issues:
- Randomized Anti-Adblock message
- Ads show up sometimes, originating from its own domain

### Screenshot(s)

![screenshot_2019-02-01 chrome is right to remove the webrequest extension api](https://user-images.githubusercontent.com/24980766/52151968-c9644700-2642-11e9-9cbd-d301f17d7e85.png)
---
![screenshot_2019-02-01 chrome is right to remove the webrequest extension api 1](https://user-images.githubusercontent.com/24980766/52151967-c9644700-2642-11e9-88fc-dd6670f2c8e5.png)

### Versions

- Browser/version: Windows 10 64-bit - Firefox 65
- uBlock Origin version: 1.18.2

### Settings

- All filters checked except "MVPS HOSTS" and all "Regional, languages" filters

### Notes

For the second issue, it looks like this was previously fixed per #2145, but it's not working anymore. Can be fixed using `||ctrl.blog/ac/*$subdocument,first-party`.

**Comment by okiehsch** [comment]
I don't see any anti-adblock message in your screenshot nor can I reproduce any on my end.

**Comment by mapx-** [comment]
maybe (I cannot reproduce the anti adb but there is `https://www.ctrl.blog/assets/js/adsbygoogle.js` )
```
ctrl.blog##+js(set-constant.js, _ctrl_vt.blocked.ad_script, false)
ctrl.blog##.boxa
```

**Comment by okiehsch** [comment]
Sure, can't hurt and should atleast avoid the detection.

**Comment by okiehsch** [comment]
I also don't see any requests originating from `ctrl.blog/ac/`.

**Comment by theinstantmatrix** [comment]
Hmm, that's weird. The message does show up on my end, sometimes either at the bottom or the top. The filter mapx- committed does not get rid of it, however using this, `ctrl.blog##+js(abort-on-property-read.js, a1lck)`, does.

**Comment by okiehsch** [comment]
OK, found it in `https://www.ctrl.blog/assets/cjs/3b6f1500-1543258240.min.js`

I will add your filter to `uBO-annoyances`.
