### ISSUE TITLE
Does uBO support allowing 3p-frames that load a specific domain?

### ISSUE THREAD

**Issue by RoxKilly** [uBlockOrigin/uAssets#479]
### URL(s) where the issue occurs

https://stackoverflow.com/questions/44748878/do-we-have-to-unsubscribe-when-using-switchmap-operator-in-rxjs-in-angular-2

### Describe the issue

When the `Run code snippet` blue button is pressed, the page opens a new frame in which it loads content. I have uBlock set to block 3p-frames by default. However I'd like to allow just this frame. So I tried:
```
stackoverflow.com * 3p-frame noop                  //works but is too broad
stackoverflow.com stacksnippets.net 3p-frame noop  //gets ignored
```
The first rule is too broad; I don't want any 3p-frame to load on the site, but just the `stacksnippets.net` frames. Does uBlock support blocking/allowing 3p-frames by specific domain?

### Versions

- Browser/version: Firefox 54
- uBlock Origin version: 1.13

PS: Is this the right place to post this?

**Comment by lassekongo83** [comment]
With static filtering - `||stacksnippets.net$subdocument`

> PS: Is this the right place to post this?
Nope.

**Comment by gorhill** [comment]
> Does uBlock support blocking/allowing 3p-frames by specific domain?

No. Use `stackoverflow.com stacksnippets.net * noop`.

**Comment by RoxKilly** [comment]
Thank you both.

**Comment by okiehsch** [comment]
`stackoverflow.com https://stacksnippets.net sub_frame noop`
should work shouldn't it?

**Comment by RoxKilly** [comment]
I just checked. That rule is sufficient to let the frame load, so you're right. In my case I still needed to noop scripts to get the contents to work
```
stackoverflow.com stacksnippets.net * noop
```
That line on its own will allow the frame to open and the script to run.
