### ISSUE TITLE
atabencot.net

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4795]
### URL(s) where the issue occurs

`http://atabencot.net/-1LPCZ/sNgL9?rndad=200167c2660425b004da-1549216400`

### Describe the issue

malicious redirects
### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.18.2

### Settings

- uBO's default settings

**Comment by okiehsch** [comment]
Already fixed. https://github.com/uBlockOrigin/uAssets/commit/543c2dc3332aeb433bc78de0c1272650c5bea18c
