### ISSUE TITLE
katmovie.de

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4800]
### URL(s) where the issue occurs

`https://katmovie.de/movies/thackeray/`

### Describe the issue

clicking on play button opens original site in new tab while original tab is loaded with ads
### Versions

- Browser/version: opera stable
- uBlock Origin version: 1.18.2

### Settings

- uBO's default settings

**Comment by ghajini** [comment]
`https://katmovie.ch/movies/thackeray/`
There's a popup

**Comment by ghajini** [comment]
`https://katmovie.mx/movies/super-30/`
popup ads

**Comment by mapx-** [comment]
I get no popup

**Comment by ghajini** [comment]
At firefox android stable/firefox desktop

**Comment by mapx-** [comment]
maybe @okiehsch will get it, still nothing here

**Comment by ghajini** [comment]
This work for me, 
Wild guesswork filter

`katmovie.*##+js(acis, Math, zfgloaded)`

**Comment by mapx-** [comment]
ok , added
