### ISSUE TITLE
Proposal to include smed79/LanikSJ list in uBO by default

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#4801]
[See here](https://github.com/uBlockOrigin/uAssets/issues/4201#issuecomment-458371163)
Full list: https://smed79.surge.sh/up/adb.txt
Itemized: https://github.com/LanikSJ/ubo-filters/tree/master/filters

Would be nice if this was integrated with EasyList but it isn't for whatever reason.

**Comment by krystian3w** [comment]
1. wrong place reported, should here: https://github.com/uBlockOrigin/uBlock-issues

2. Readme uBlock-issues:<blockquote> <b>Opening issues for adding new filter lists is now disallowed and such issues will be declined and closed.</b></blockquote>

**Comment by terrorist96** [comment]
If I open a new issue there, the template literally says

> Opening issues for adding new filter lists is now disallowed and such issues will be declined and closed.

So that's not the correct place to report.

**Comment by terrorist96** [comment]
@mapx- can you re-open, since uBlock-issues is not the correct place to post this.

**Comment by mapx-** [comment]
Usually, when we get a malicious domain it will be added to `ublock filters` the specific filter (killing the popups, redirects; often such external scripts are prepared using inline scripts which are killed by our filters). Lastly the specific domain is added as well to `ublock filters`.

There are also the malware domains where someone could report such domains.

**Comment by terrorist96** [comment]
So can we merge the list into `ublock filters`?

**Comment by mapx-** [comment]
There are a lot of dead domains, other already in easylist. There is no good reason to add such a list (> 14.000 filters !)

**Comment by okiehsch** [comment]
No new lists will be added to the stock filter lists at the moment, if that changes it could be added to the `multipupose` section, but it will certainly not be merged into `uBO-filters` or enabled by default.

**Comment by LanikSJ** [comment]
Let me know what I can do to make the process of approval easier.  @smed79 just dropped 4.000 lines from the filters he submitted.

**Comment by okiehsch** [comment]
It is not about approval really, right now no new lists will be added to the stock filter lists in fact the goal is to reduce the number of lists in the regional section if possible.
I would be in favour of adding your list to the `Multipurpose` section if ths changes.

**Comment by LanikSJ** [comment]
I have no problem with that as long as it's open to everyone with an easy ✅.

**Comment by terrorist96** [comment]
Why not divide it up? Add the anti-adblock bypass parts to `uBlock filters`, add the privacy parts of the list to `uBlock Privacy`, add the mining parts to the `uBlock Resource abuse` list, etc.

**Comment by okiehsch** [comment]
Just at a quick glance more then 400 of the 486 domains of the mining part are duplicates of `EasyPrivacy` or `uBlock Resource abuse` filters and more will be redundant because of filters in those lists.
Like I said already it will certainly not be merged into `uAssets` if you can point to specific filters that comply with https://github.com/uBlockOrigin/uAssets/blob/master/README.md they can be added.

**Comment by smed79** [comment]
What I recommend:
https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/propellerads-domains.txt
https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/hilltopads-domains.txt
https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/admaven-domains.txt
https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/admeasures-domains.txt
https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/admiral-domains.txt
https://raw.githubusercontent.com/LanikSJ/ubo-filters/master/filters/adback-domains.txt
