### ISSUE TITLE
temp-phone-number.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#4803]
URL(s) where the issue occurs

`https://www.temp-phone-number.com/receive-sms-online-poland`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 71 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.18.2

Settings

Default

**Comment by stephenhawk8054** [comment]
Not really anti-adblock, but it's an annoyance/nuisance. When opening the page in Private Window/Incognito, the site automatically redirects to

`https://www.temp-phone-number.com/adblockprivate`

URL: `https://www.temp-phone-number.com`

Looks like it's caused by this function:

<details>

```js
function adblockaction() {
	if (location.pathname.substring(location.pathname.lastIndexOf("/") + 1) == "view") {
		location.href = "/adblock"
	} else {
		showadmessage()
	}
}
if (!document.getElementById("pCJwiKFyMSdq")) {
	adblockaction()
} else {
	no_ad = 0;
	window.onload = function checkadblock() {
		setTimeout(function() {
			$.each($(".ads-block"), function(idx, ele) {
				if (ele.offsetHeight == 0) {
					no_ad++;
				}
			});
			if (no_ad > 0 && $(".ads-block").length > 0 && $(".ads-block").length == no_ad) {
				adblockaction()
			}
		}, 500);
	};
}
var db = window.indexedDB.open("test");
db.onerror = function() {
	location.href = "/adblockprivate"
};
```

</details>
in this script:

`https://www.temp-phone-number.com/files/js/bootstrap.min.js?v=1.1`

<details><summary>Settings</summary>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 77976
  cosmetic: 39683
  scriptlet: 16301
  html: 595
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30508-131, 43m
    ublock-badware: 3574-1, 43m
    ublock-privacy: 185-0, 43m
    ublock-abuse: 81-0, 43m
    ublock-unbreak: 1723-0, 43m
    easylist: 61707-456, 1h.53m
    easyprivacy: 26486-475, 43m
    urlhaus-1: 7817-0, 43m
    plowe-0: 3687-3, 43m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 670
  launchFromSelfie: false
popupPanel: 
  blocked: 0
```
</details>

Proposed filter:

`temp-phone-number.com##+js(aopr, db, "/adblockprivate")`
