### ISSUE TITLE
deepbrid.com[Antiadblock]

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4806]
### URL(s) where the issue occurs

`https://www.deepbrid.com/adblock?return_url=https%3A%2F%2Fwww.deepbrid.com%2Fdl%3Ff%3Dd83c2d4417569e78aee4150494bf8385`

### Describe the issue

antiadblock
### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.18.2

### Settings

- uBO's default settings

**Comment by mapx-** [comment]
the original link ?

**Comment by Jap2-0** [comment]
@mapx- it looks like https://www.deepbrid.com/dl?f=d83c2d4417569e78aee4150494bf8385 (from return_url)

**Comment by mapx-** [comment]
thx @Jap2-0

**Comment by ghajini** [comment]
steps @mapx- 
1. `https://www.deepbrid.com/downloader`
2.enter any link eg `https://www.youtube.com/watch?v=jVQDFB3AnVo`
3.follow steps further on site

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/12006
