### ISSUE TITLE
gigaleecher.com[Antiadblock]

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4807]
### URL(s) where the issue occurs

```
https://www.gigaleecher.com
https://www.xuxon.com
https://www.leechking.com
```
### Describe the issue

antiadblock
1. enter site
2. enter any link to leech eg `http://www.filefactory.com/file/63c3cbs0oo7b/thlnfdmbrd.br_300mbfilms.org.rar`
3.clicking leech now result in antiadblock
### Screenshot(s)
![screenshot 114](https://user-images.githubusercontent.com/20338483/52299211-e08c9700-29aa-11e9-87eb-e9b6965b78ec.png)

### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.18.2

### Settings

- uBO's default settings

**Comment by garry-ut99** [comment]
Many big ad placeholders on all of the sites:

`gigaleecher.com` ==> [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/217630074-c7d6ae3d-d58d-4b93-a8ea-119345bd88da.png), AA still appears with `ghide` off
`xuxon.com` ==> [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/217630080-fabe46ee-716f-46fc-819a-a54cca08c0d8.png), AA doesn't appear but I'm not sure coz it throws a message: "Please wait 10 minutes or Visit our sponsor. "
`leechking.com` ==> [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/217630068-c56238db-0613-4a6a-9646-f411ba2a398b.png), AA doesn't appear but I'm not sure coz it throws a message: "Please wait 10 minutes or Visit our sponsor. "
