### ISSUE TITLE
Edge easylist filter requesting to download .htm in youporn.com

### ISSUE THREAD

**Issue by dhigh88** [uBlockOrigin/uAssets#481]
### URL(s) where the issue occurs
youporn.com

### Describe the issue
It's been a long time this has been happening ; I maybe thought filter updates would fix this issue as youporn.com is still affected when the Easylist filter is enabled in Microsoft Edge. The website won't open but rather request to download the page. This issue was fixed with several sites when the Creators Update was released but it came back just with youporn for some reason.

### Screenshot(s)
![preview1](https://user-images.githubusercontent.com/26260953/27614748-b3423c18-5b71-11e7-92da-450a720db7f4.jpg)

### Versions

Browser/version: Microsoft Edge 40.15063.0.0
uBlock Origin version: 1.12.4

### Settings
Default

**Comment by okiehsch** [comment]
No problem with Chrome or Firefox so this appears to be a browser bug and should be reported
[here](https://github.com/nikrolls/uBlock-Edge#edge).
