### ISSUE TITLE
about:blank$[...] -> |about:blank|$[...]

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#4811]
filters.txt
`about:blank$popup,domain=vortez.net`
`about:blank$popup,domain=mitly.us`
`about:blank$popup,domain=zlshorte.net`
`@@about:blank$popup,domain=vipbox.live`

unbreak.txt
`@@about:blank$popup,domain=onlinevideoconverter.com`

**Comment by mapx-** [comment]
The other were removed
