### ISSUE TITLE
Ti.com :: False block

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#4812]
### URL(s) where the issue occurs

`http://www.ti.com/tool/OPT3101EVM#`

### Describe the issue

Top header is wrongly blocked.

### Versions

- Browser/version: Chrome 71.0.3578.98 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.18.2

### Settings

- Default

### Notes

This filter `||evergage.com^` is causing the issue. It is loaded from `Peter Lowe’s Ad and tracking server list`.
Check the page with `@@||evergage.com`, and you will see the header back again.

**Comment by nimasaj** [comment]
@mapx- Thanks. This one is also making problem `||ti.com/assets/js/headerfooter/$script`, loaded from `EasyPrivacy`.

**Comment by mapx-** [comment]
What problem ?

**Comment by nimasaj** [comment]
blocking header to load.
