### ISSUE TITLE
nohchipress.info (nsfw)

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#4814]
### URL(s) where the issue occurs

`[nohchipress.info]`

### Describe the issue

[Some sort of push type message in Russian at the bottom of the page. Note sure how to exactly describe it but it should be blocked seeing as it has malicious purpose.]

### Versions

- Browser/version: [Firefox mobile v63]
- uBlock Origin version: [1.18.4]

### Settings

- [default]

### Notes

- [sadly can't hide it with cosmetic filters as it changes its name every reload.]

**Comment by mapx-** [comment]
Do these help ?
```
||pushkahouse.com/sw.js$script
||nohchipress.info/sw.js$script,1p
```

**Comment by dumbusernameidk** [comment]
no it's still there. i was going to suggest a csp filter but the site validates your browser after not using it for some time.  i noticed that you can use a cosmetic filter it seems only the first 7 characters are the same while the rest are random `nohchipress.info##[id^="MTU0OTU"]`. but that's a band aid fix really. i notice there's a script for it in the source page can't make much sense of it though.

**Comment by mapx-** [comment]
test
```
||pushkahouse.com/sw.js$script
||nohchipress.info/sw.js$script,1p
nohchipress.info##+js(remove-attr.js, href, [href*="go.php"])
nohchipress.info###parent_popup
nohchipress.info##[class$="wrapper"]
```

**Comment by dumbusernameidk** [comment]
First and second work. Can't test the third one as I don't have chrome atm.
