### ISSUE TITLE
Content breakage [MVPS Hosts List]

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#482]
### URL(s) where the issue occurs

http://videos.marca.com/
http://videos.expansion.com/
http://videos.telva.com/
http://videos.elmundo.es/

### Describe the issue

MVPS HOSTS List will not let me play videos.

### Screenshot(s)

https://user-images.githubusercontent.com/27441315/27606153-6badb720-5b7f-11e7-8a52-e663b2abf572.png

https://user-images.githubusercontent.com/27441315/27606077-066a731c-5b7f-11e7-9353-26807eabc740.png

### Versions

- Browser/version: Firefox 54
- uBlock Origin version: 1.13.4

### Settings

- Default list + MVPS HOSTS + Dan Pollock's list + Easylist spanish

### Notes

`active.cache.el-mundo.net` is blocked, does its job, blocks ads and anti-adblock script
But the list does not have a specific filter to block objects (only domains)
`s_code.js` allows me to play videos in html5

These rules solves it
```
@@||active.cache.el-mundo.net/js/s_code$script
@@||active.cache.el-mundo.net^$font
```

**Comment by SMed79** [comment]
> ... report a bad link, or entry in the MVPS HOSTS file that should be added or removed, or any site problems, send this information or any other comments you may have to: winhelp2002@gmail.com

source http://winhelp2002.mvps.org/

**Comment by lain566** [comment]
@SMed79 I don't want it to be removed, does its job, blocks ads and anti-adblocker
but MVPS hosts  only add domains. Does not add specific rules

**Comment by okiehsch** [comment]
This will not be fixed in `uBO-filters` https://github.com/uBlockOrigin/uAssets/issues/423#issuecomment-305553681

**Comment by lain566** [comment]
@okiehsch Ok, but then why say this on Unbreak list?
```
# Needed to unbreak web sites, mostly because of hosts file-based filters:
#   Dan Pollock's, MVPS, Peter Lowe's
```
https://github.com/uBlockOrigin/uAssets/blob/master/filters/unbreak.txt#L1L2

**Comment by okiehsch** [comment]
I agree that this should be changed to something like 
`Needed to unbreak web sites, broken by uBO default filter lists.`
@gorhill are you OK with such a change or would you phrase it differently?

**Comment by gorhill** [comment]
Yes this should be changed. (In the early days of the project I was considering enabling these lists by default.)
