### ISSUE TITLE
aetv.com [Anti-AdBlock]

### ISSUE THREAD

**Issue by ClairelyClaire** [uBlockOrigin/uAssets#4824]
### URL(s) where the issue occurs
Example:
`https://www.aetv.com/shows/many-sides-of-jane/season-1/episode-1`

This is the case on all TV episode pages.

### Describe the issue

"It's not you...it's your ad blocker" is displayed instead of the video control.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Firefox Developer Edition 64-bit (66.0b4)
- uBlock Origin version: 1.18.4

### Settings

Filters:
uBlock filters​
uBlock filters – Badware risks​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
EasyList​
EasyPrivacy​
Malware Domain List​​​
Malware domains​
AdGuard Annoyances filter​
Anti-Facebook List​
Fanboy’s Annoyance List​
Fanboy’s Social Blocking List​
Peter Lowe’s Ad and tracking server list​
AakList (Anti-Adblock Killer)​​

I have no custom filters that apply to aetv.com.

### Notes

I've watched the logger to see where the anti-adblock script is hitting, and I can't find it.

Oddly, with Edge, I can disable uBlock Origin to load an episode's page, enable it, and it'll block ads without triggering the anti-adblock script.

**Comment by okiehsch** [comment]
I can't test, all episodes require an account.
![image](https://user-images.githubusercontent.com/16838044/52449896-2d05dd00-2b39-11e9-900e-ed2342b7b7a2.png)


I tried some videos that do not require an account, for example
`https://www.aetv.com/videos/biography-toni-braxton`
and there is no anti-adblock message on my end.

**Comment by mapx-** [comment]
https://forums.lanik.us/viewtopic.php?p=145574#p145574

> Further troubleshooting led to the problem being caused by Bitdefender Free AV. When the AV is disabled and UBO is running everything works as designed.

**Comment by okiehsch** [comment]
I don't think that is the same issue, I could reproduce 
`https://forums.lanik.us/viewtopic.php?f=64&t=42581`
without `Bitdefender Free AV` and fixed it in `uBO-unbreak`.
https://github.com/uBlockOrigin/uAssets/commit/8231775b60dc3e6678541a1c7b3675806d6dab59

**Comment by mapx-** [comment]
@ClairelyClaire  if you can (and want) to provide the credentials for an account just send them here: `axis.trivia@gmail.com` and re-open the thread
