### ISSUE TITLE
mediafire.com

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#4826]
`http://www.mediafire.com/file/r944lnx8khxa6wt/LuckyPatchers.com_Official_V8.1.4.apk`

When you go to `ttp://www.mediafire.com/file/r944lnx8khxa6wt/LuckyPatchers.com_Official_V8.1.4.apk/` there's a popup window that detects you have an adblocker. Is there a way to get rid of that? Thanks.

![mediafire com](https://user-images.githubusercontent.com/35790889/52456899-32f1c300-2b25-11e9-8646-3de094d0031e.jpg)

firefox 65.0 (64-bit)
ublock origin 1.18.4

**Comment by okiehsch** [comment]
I can't reproduce with a default setup.
![image](https://user-images.githubusercontent.com/16838044/52457276-461e8600-2b59-11e9-888e-4dfd0a159557.png)

**Comment by mapx-** [comment]
enable `uBlock filters – Annoyances`  in filters list section (dashboard)

**Comment by IoanPaleru** [comment]
![ublock origin mediafire](https://user-images.githubusercontent.com/35790889/52527522-dd89f300-2c97-11e9-8ccb-a50e4ab23735.jpg)

mapx, thanks but that didn't work. I enabled all the annoyances filters and it still shows the same popup window that detects you have an adblocker.

okiehsch, I created a brand new profile in firefox for testing purposes and installed only ublock origin with the default settings, but it still shows the same popup window that detects you have an adblocker when going to that website. I also purged the filter cache and updated the filters, but it still didn't work. uBlock Origin is a nice program, but it seems to require a lot of user customization to get it to block all ads and annoyances properly on most sites, so it would be nice if it could be fixed to work even better by default without the user having to configure anything. Is there another way to get rid of popup windows like that from that website that detect you're using an ad blocker? Thanks.

firefox 65.0 (64-bit)
ublock origin 1.18.4

**Comment by mapx-** [comment]
Did you enable `ublock filters- Annoyances`  ?

![image](https://user-images.githubusercontent.com/10303732/52527574-1db69900-2ccb-11e9-95a9-1c0036a9a2ee.png)

**Comment by okiehsch** [comment]
I can't reproduce even with `uBO-annoyances` disabled.

**Comment by IoanPaleru** [comment]
mapx, yes all of them (and updated them), but it still detects the adblocker.

okiehsch, ok if you can't reproduce it then that's weird but thanks anyways for trying. If it's a new firefox profile with only ublock origin installed with default settings, then I don't know what else could be causing my browser to show that popup window and not yours, but ublock origin is still a pretty good program. Have a good day.

**Comment by lain566** [comment]
Fake button, 
`https://www.mediafire.com/file/ysqoyqb4qlyyd3v/J.e-e_p_e.r.s.._c-r_e.e-p.e_r_s-.-i_i-i-.-2-0.1_7..-1.0.8_0-p_--d-u-a_l_-.l-a_t-.-m_p-4.zip`


![a1e0f968-1c75-4c42-9f6c-2e01476e5673](https://user-images.githubusercontent.com/27441315/53954184-bf1be980-40d5-11e9-8200-264d4ac34f9a.png)

**Comment by mapx-** [comment]
it seems to be when the download is blocked

add
`||static.mediafire.com/images/dl_desktop.png$image`
or
`mediafire.com##[href*="mfroute.com/"]`

to be added to easylist @ryanbr
