### ISSUE TITLE
ublock origin website settings

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#4827]
Hi, when select the options to block 3rd-party and 3rd-party scripts on any website, ublock origin doesn't seem to remember those settings after you restart firefox, but it used to. Is there a way to fix that? Thanks.

![yts pm](https://user-images.githubusercontent.com/35790889/52457100-1bffa080-2b26-11e9-8137-ace99f766e79.jpg)

firefox 65.0 (64-bit)
ublock origin 1.18.4

**Comment by okiehsch** [comment]
This is not a filter issue.
https://github.com/uBlockOrigin/uBlock-issues/issues

**Comment by IoanPaleru** [comment]
Ok, is there somewhere else I can ask questions about that?

**Comment by okiehsch** [comment]
I linked to it in my post.
https://github.com/uBlockOrigin/uBlock-issues/issues

**Comment by uBlock-user** [comment]
> Hi, when select the options to block 3rd-party and 3rd-party scripts on any website, ublock origin doesn't seem to remember those settings after you restart firefox

You didn't click on the padlock button, so rules didn't get saved.

**Comment by IoanPaleru** [comment]
uBlock-user, thanks so much for your post, that's exactly what I needed to know. I forgot about the padlock icon, and now ublock origin remembers the website settings. Have a great day.
