### ISSUE TITLE
pornhub.com: Ads By Traffic Junky -- a div element with random class name

### ISSUE THREAD

**Issue by stanlane** [uBlockOrigin/uAssets#483]
### URL(s) where the issue occurs

`https://www.pornhub.com/`

### Describe the issue

The ```<div class="hsuvbmr3fszxmsvk2sf">``` (random class name) should be blocked. The div is used for the classic *Ads By Traffic Junky*.

```
<div class="hsuvbmr3fszxmsvk2sf">
<a class="removeAdLink removeAdsStyle" onclick="triggerGatewayModal(event);" data-segment="straight" data-entrycode="RemAds-ftr">Remove Ads</a>
			

<iframe
	data-zone-id="5"
	class=""
	height="250"
	id="glxlym6k0kfxbpx"
	title="PornHub  Campaign bottom"
	width="950"
	frameborder="0"
	scrolling="no"
	src="https://cdn1d-static-shared.phncdn.com/iframe-1.1.5.html#zone_id=5&amp;channel%5Bcontext_tag%5D=cfnm%2Ccfnm+interview%2Cwatching+guy+wank%2Cdickflash%2Cdick+flash%2Cwank+for+me%2Cwanking+for+her%2Cgirl+watching+guy%2Cgirl+watches+guy%2Cfemale+voyeur%2Cjerking+off+watching%2Cjerking+off+for+her%2Cgirl+watch+guy%2Ccfnm+milf%2Ccfnm+milf+jerk+off%2Cstroking+for+woman&amp;channel%5Bcontext_category%5D=Amateur%2CBlonde%2CFetish%2CMILF%2CHD&amp;site_id=2&amp;channel%5Bsite%5D=pornhub"
	style="display:inline-block!important;opacity:1!important;visibility:visible!important;">
</iframe>



<script>
	page_params.zoneDetails['glxlym6k0kfxbpx'] = {
						'height' 		: '250',
		'width' 		: '950',
		'zoneId'		: '5',
		'special'		: '',
		'dynamicId' 	: 'hsuvbmr3fszxmsvk2s',
		'adTypeParent' 	: 'f',
		'adTypeChild' 	: '',
				'frameId'       : 'glxlym6k0kfxbpx'
	};
</script>
			<a class="ad-link" href="https://www.pornhub.com/information#advertising">Ads By Traffic Junky</a>
		</div>
```
### Screenshot(s)
The div element is located right to the video.

![screenshot from 2017-08-23 00 37 24](https://user-images.githubusercontent.com/25944158/29590672-44fefe70-879b-11e7-9b11-2bd4be951c87.png)

### Versions

- Browser/version: Firefox ESR 52.1.2
- uBlock Origin version: 1.13.4

### Settings
Default

**Comment by gorhill** [comment]
I don't see any _"Ads By Traffic Junky"_ in the URL you provided. Please provide a screenshot of what you are seeing.

**Comment by gotitbro** [comment]
Same issue as: https://github.com/uBlockOrigin/uAssets/issues/471

**Comment by gorhill** [comment]
@stanlane Does this work?

    pornhub.com##.nonesuch:has(> div[class] > a.removeAdLink)

**Comment by dhigh88** [comment]
@gorhill Hey there sir, sorry, is there any reason why there is no volunteer especially nikrolls helping people in the ublock edge issues page. I've posted a recent issue in there and someone else did too recently, as always no one helps us. Ublock edge is still stuck in version 1.12.4. Even this pornhub issue is very relevant on Edge as it allows ads once in a while. Was going to open an issue about it but already knew It would remain silent. This version of ublock edge can be so buggy at times.

**Comment by stanlane** [comment]
@gorhill 

> pornhub.com##.nonesuch:has(> div[class] > a.removeAdLink)

No, sorry.

Here's the screenshot you asked for.

![screenshot from 2017-08-11 04 28 09](https://user-images.githubusercontent.com/25944158/29199500-ba8c389e-7e4d-11e7-980d-1561eef15946.png)

**Comment by stanlane** [comment]
@gorhill If you give me a new filter I will evaluate it.

**Comment by gotitbro** [comment]
@stanlane A lengthy discussion about these leftover ad elements has already been carried out in https://github.com/uBlockOrigin/uAssets/issues/471. You should check that out.

**Comment by stanlane** [comment]
@gotitbro Thank you. I still think this issue should be open.

**Comment by stanlane** [comment]
https://github.com/uBlockOrigin/uAssets/issues/471
