### ISSUE TITLE
iomovies.to

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4830]
### URL(s) where the issue occurs

`https://www.iomovies.to/movie/ralph-breaks-the-internet-evAGo07G/watch#7jwKeXNVZQN5z7z2`

### Describe the issue
popup ads

annoying push notifications when trying to close in firefox android leads to ads

sometimes push notification don't give option whether to allow or block so that i can not even enter into site
### Versions

- Browser/version: opera browser/firefox android 65
- uBlock Origin version: 1.18.2

### Settings

- uBO's default settings

### Notes

**Comment by mapx-** [comment]
@ghajini  does it work now ?

**Comment by ghajini** [comment]
I see some popups on firefox androud

**Comment by ghajini** [comment]
Looks good,it was filter updating issue on my end

**Comment by mapx-** [comment]
removed the fake download buttons on the right side too
