### ISSUE TITLE
mail.ru

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#4845]
![default](https://user-images.githubusercontent.com/8535285/52525086-941dc000-2cf8-11e9-9834-8382e31327d1.png)
@mapx-  ads

**Comment by krystian3w** [comment]
@dimisa-RUAdList can you reproduce or block this?

**Comment by bogachenko** [comment]
@krystian3w I already know what he will say, he will advise me to install the JSFixAdlistRU script. But I do not want to install it, because can remove ads with ublock0

**Comment by dimisa-RUAdList** [comment]
Add
https://easylist-downloads.adblockplus.org/cntblock.txt
or
https://easylist-downloads.adblockplus.org/bitblock.txt

**Comment by bogachenko** [comment]
~Новый ответ, который не советует установить этот скрипт.~ И кстати это работает. Рекламы нет. спасибо

**Comment by dimisa-RUAdList** [comment]
Коверкать название скрипта совершенно не обязательно. И RU AdList по прежнему делает то, что невозможно реализовать в расширениях для блокировки.

**Comment by bogachenko** [comment]
~не коверкал~ просто не правильно написал

**Comment by smed79** [comment]
Please speak English when it is possible :nerd_face:

**Comment by dimisa-RUAdList** [comment]
@bogachenko 
Try to update the RU AdList and disable BitBlock and Counters.

**Comment by bogachenko** [comment]
@dimisa-RUAdList прикольно, рекламы нет.

кстати ответь на парочку вопросов

Почему ты не на гитхабе создаешь фильтры, а только на форуме?
В BitBlock и Counters есть очень много годных фильтров, которые хотелось бы видить в основном вашем списке, как на счет перенести?

**Comment by dimisa-RUAdList** [comment]
Sent a reply to email.
