### ISSUE TITLE
Dailymotion

### ISSUE THREAD

**Issue by rampaa** [uBlockOrigin/uAssets#485]
### URL(s) where the issue occurs

`http://www.dailymotion.com/video/x31l3y7`

### Describe the issue

Dailymotion videos doesn't play when "uBlock filters" is on.

### Versions

- Browser/version: Firefox 54.0
- uBlock Origin version: 1.13.4

### Notes

I've pinpointed that the issue arises because of "uBlock filters" by disabling all my filters and enabling them one by one.

**Comment by mapx-** [comment]
`dailymotion.com#@#script:inject(1136.js)`

**Comment by rampaa** [comment]
Thank you, it worked.
