### ISSUE TITLE
upload4earn.org

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#4862]
downloading from upload4earn is impossible with ublock filters enabled,
when I disable ublock filters, it works,
test link: `https://upload4earn.org/m2qymbin4ed4`

**Comment by okiehsch** [comment]
What exactly happens on our end? I get a "wrong IP" message even if I disable `uBO`.

**Comment by okiehsch** [comment]
I tried
`https://upload4earn.org/4vw05ccbtxq5`
and I can download the file with a default setup without issue.

**Comment by patrickdrd** [comment]
I'm not redirected to the download page

**Comment by okiehsch** [comment]
I tried again and I can download `https://upload4earn.org/m2qymbin4ed4` with Chrome or Firefox without issue on my end.

**Comment by mapx-** [comment]
no issues either
@patrickdrd you should reset uBo to the default setup and test again

**Comment by patrickdrd** [comment]
I didn't reset but now I can too

**Comment by ghajini** [comment]
`https://upload4earn.org/er6m6s4194j8`
Site is compromised? 
Starts downloading unknown apk if clicked on free download

**Comment by okiehsch** [comment]
The site seems to be non functional, I can't upload any file or sign up.
