### ISSUE TITLE
apkpedia.co

### ISSUE THREAD

**Issue by 241d2** [uBlockOrigin/uAssets#4863]
### URL(s) where the issue occurs
`https://apkpedia.co/file/D2AEF43CD362`

### Describe the issue
Not an issue but request a filter that speeds up timer

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]
![image](https://user-images.githubusercontent.com/45212341/52533515-1f1cab80-2d35-11e9-943c-dfb84d54be99.png)

### Versions
- Browser/version: Version 71.0.3578.98 (Officiel version) (64-bit)
- uBlock Origin version: 1.18.2

### Settings

- Vis antallet af blokerede forespørgsler på ikonet (disabled)

**Comment by Jap2-0** [comment]
Try this:
`apkpedia.co##+js(nano-setInterval-booster.js,,1200)`

@mapx- are timers something that are included in uBO lists?  I didn't think they were, but if they are I've run across several that have things like this.

**Comment by mapx-** [comment]
yes, there are already filters based on `nano-`

**Comment by Jap2-0** [comment]
@mapx- Cool, in that case another one I can think of off of the top of my head is `coolmathgames.com##+js(nano-setInterval-booster.js)`

Test case: `https://www.coolmathgames.com/0-2048`
