### ISSUE TITLE
keeplinks.co

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#4865]
### URL(s) where the issue occurs

`https://www.keeplinks.co/p25/5c52584e77ad2`

### Describe the issue

Popup

### Versions

- Browser/version: Chrome 72
- uBlock Origin version: 1.18.2

### Settings

- Default settings.

**Comment by ghajini** [comment]
Annoying opening window {`hellotechworlds.com`}

`https://keeplinks.live/view/XYNzERefT3EMYNhz1rO1`

**Comment by ghajini** [comment]
`https://www.keeplinks.co/p66/5cb0ca5eb9ffe`
when gone to destination link after captch solving, click in page popup ads appears , original page is closed
