### ISSUE TITLE
picodi.com [Annoyance] [pop-up] [tracking]

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#4869]
### URL(s) where the issue occurs

`https://www.picodi.com/uk/`

### Describe the issue

title modificator after change opened tab or clicked outside of the page:

<table><tr><td>

```html
<title>
Voucher Codes, 
Offers and Deals 
for the UK online stores
 - Picodi United Kingdom
</title>
````

![obraz](https://user-images.githubusercontent.com/35370833/52582476-959cd480-2e2d-11e9-8a02-09e13c7f546f.png)

</td><td>

:repeat: 

</td><td>

```html
<title>

Back to Picodi


</title>
```

![obraz](https://user-images.githubusercontent.com/35370833/52582523-acdbc200-2e2d-11e9-91e8-17c07764d493.png)

</td></tr></table>

### Screenshot(s)

In decription, better no possible send.

### Versions

- Browser/version: Firefox 65
- uBlock Origin version: uBO 1.18.4

### Settings

- uBO default + uBO Annoyance

### Notes

Possible safe disable this?

**Comment by mapx-** [comment]
test
`picodi.com##+js(addEventListener-defuser.js, focus)`

**Comment by krystian3w** [comment]
No works with Firefox, CSP or no use `focus` / `onfocus`... :zzz:  :sleeping:

**Comment by mapx-** [comment]
`picodi.com##+js(abort-on-property-write.js, titleBack)`

**Comment by krystian3w** [comment]
Break copy sale code: `https://www.picodi.com/uk/nikestore#cid=56968` after open popup.

Maybe give up title and block popup / popunder?

`||webgains.com^`
```
https://track.webgains.com/click.html?wgcampaignid=128625&wgprogramid=6373&clickref=5c61bf21f109075c00725fcd&wgtarget=https%3A%2F%2Fwww.nike.com%2Fgb%2Fen_gb%2F
```
`https://metric.picodi.net/uk/r/56968`

after click `Reveal the Code` e.g. on `https://www.picodi.com/uk/nikestore`

![obraz](https://user-images.githubusercontent.com/35370833/52586502-f6310f00-2e37-11e9-89f4-d03e52ef4156.png) |
--- |

**Comment by krystian3w** [comment]
No block copy sale code:

```
picodi.com##+js(abort-on-property-read.js, titleBack)
```

Try test with register account?

**Comment by yourduskquibbles** [comment]
@mapx- will these filters be added to uAssets Annoyances list or is it outside of scope?

**Comment by mapx-** [comment]
It seems to be outside of scope (and it seems is breaking some functionality - I don't have an account)
