### ISSUE TITLE
Ublock filters blocking dailymoion video

### ISSUE THREAD

**Issue by rayman89** [uBlockOrigin/uAssets#487]
"Ublock filters" is making dailymotion videos not load

ex link http://www.dailymotion.com/video/x5s5onm_woman-crosses-freeway-during-rush-hour-to-rescue-rooster_news

I'm on fireofx 55 beta x64 on windows 7

**Comment by SMed79** [comment]
Use search please https://github.com/uBlockOrigin/uAssets/issues/485#issuecomment-312056143
