### ISSUE TITLE
chefkoch.de

### ISSUE THREAD

**Issue by uBlockIsBest** [uBlockOrigin/uAssets#4870]
### URL(s) where the issue occurs

`https://www.chefkoch.de/`

### Describe the issue

Undetected picture ads from local domain

### Screenshot(s)

<img width="1903" alt="adpicture" src="https://user-images.githubusercontent.com/47333122/52583914-009bda80-2e31-11e9-8499-bb1c60199411.PNG">

### Versions

- Browser/version: [firefox 65.0 64-Bit]
- uBlock Origin version: [v1.18.4]

### Settings

- 
[my-ublock-backup_2019-02-11_19.14.27.txt](https://github.com/uBlockOrigin/uAssets/files/2852420/my-ublock-backup_2019-02-11_19.14.27.txt)

**Comment by krystian3w** [comment]
I do no see this ads.

**Comment by krystian3w** [comment]
Try disable `"fanboy-enhanced"` and reproduce?

**Comment by uBlockIsBest** [comment]
> 
> 
> Try disable `"fanboy-enhanced"` and reproduce?

The ads appear after 2-10 secs, when im disable `fanboy-enhanced` the ads dont get blocked

**Comment by krystian3w** [comment]
Me to after 5 minutes, maybe need new scriptlet?

**Comment by uBlockIsBest** [comment]
Im updated all lists, but at least i can block the ads when i block `www.chefkoch.de/ck.de`

**Comment by smed79** [comment]
```
||chefkoch-cdn.de/ck.de/*.min.js|$script,domain=chefkoch.de
```
