### ISSUE TITLE
praxistipps.focus.de

### ISSUE THREAD

**Issue by uBlockIsBest** [uBlockOrigin/uAssets#4871]
### URL(s) where the issue occurs

`https://praxistipps.focus.de/rohen-plaetzchenteig-essen-das-sollten-sie-beachten_56574#video-1_zxkl7byx`

### Describe the issue

Pre Video ad, "ANZEIGE" placeholder

### Screenshot(s)

<img width="1302" alt="unbenannt" src="https://user-images.githubusercontent.com/47333122/52584761-38a41d00-2e33-11e9-8e51-a1a139056715.PNG">

### Versions

- Browser/version: [Firefox 65.0 64-Bit]
- uBlock Origin version: [v1.18.4]

### Settings

- 
[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/2852503/Settings.txt)

### Notes

if the video doesnt load, reload the page or press the play button
[Werbung, Anzeige = ad]

**Comment by krystian3w** [comment]
for "Anzeige":

```
##.Article__Promo, div[id^="contentad-storyad"], hr[class^="m"][class$="-xs"]
```

**Comment by uBlockIsBest** [comment]
im already blocked "Anzeige"

**Comment by krystian3w** [comment]
Well, this will be an offer for EasyList DEU.

Unless it is an self promotion, then they will not reach.

I have not had ads on video player yet.

**Comment by uBlockIsBest** [comment]
that ad is a normal video ad from `ssl.1.damoh.chip.de` not a problem, u block have filters for that. The problem here is, the ad is coming from `ssl.1.damoh.curloc.com` so i cant block it, when i try to block it with  `/*$media,redirect=noopmp3-0.1s,domain=t` Attribute, the video will disappear

**Comment by krystian3w** [comment]
try use mp4 one second if no crash website (no only player)?

```
redirect=noopmp4-1s
```

https://github.com/uBlockOrigin/uAssets/blob/ce215ed7134238c11fd28f8b62143fbf21f5eb6c/filters/resources.txt#L74

If still cut player maybe help only dedicated scriplet filter.

**Comment by mapx-** [comment]
I get no video ad. Did you try `##+js(damoh-defuser.js)` ?

**Comment by uBlockIsBest** [comment]
> 
> 
> I get no video ad. Did you try `##+js(damoh-defuser.js)` ?

yes, but it doesnt work.

**Comment by JobcenterTycoon** [comment]
Seems to be `##+js(damoh-defuser)` is obsolete on `chip.de` and `praxistipps.focus.de` on both sites it works fine without too.
