### ISSUE TITLE
merkur.de

### ISSUE THREAD

**Issue by uBlockIsBest** [uBlockOrigin/uAssets#4872]
### URL(s) where the issue occurs

`https://www.merkur.de/wirtschaft/verletzungsgefahr-durch-metallteile-bmw-muss-rueckruf-wegen-airbags-starten-fast-100-000-autos-in-deutschland-betroffen-zr-11755814.html`

### Describe the issue

Undetected picture ads, huge ad spam. When you click one of the pictures, a popup will open, but it will get closed by uBlock for `paid.outbrain.com`

### Screenshot(s)

<img width="1904" alt="adpicture2" src="https://user-images.githubusercontent.com/47333122/52586889-ec5bdb80-2e38-11e9-9ce4-016496055df7.PNG">

### Versions

- Browser/version: [Firefox 65.0 64-Bit]
- uBlock Origin version: [v1.18.4]

### Settings

- 
[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/2852645/Settings.txt)

### Notes

- Its looks like normal content, but this is only a really huge ad spam from autbrain [Anzeige = ad] you must scroll down, when you scroll down, the ad spam will start.

**Comment by krystian3w** [comment]
Maybe possible kill by scriplet as procedural cosmetic filtering:

```css
##.id-Container-content > .id-Article + div:not([class]):not([id]):has(>div>div>img[src^="/bilder/"])
```

**Comment by mapx-** [comment]
test
`merkur.de##+js(set-constant.js, String.fromCharCode, noopFunc)`

**Comment by uBlockIsBest** [comment]
> 
> 
> test
> `merkur.de##+js(set-constant.js, String.fromCharCode, noopFunc)`

its works thanks! i hope it get added in the official ublock filter
