### ISSUE TITLE
selbstaendig-im-netz.de

### ISSUE THREAD

**Issue by uBlockIsBest** [uBlockOrigin/uAssets#4873]
### URL(s) where the issue occurs

`https://www.selbstaendig-im-netz.de/blogs/mein-neuer-blog-idee-start-und-erster-traffic-case-study-teil-1`

### Describe the issue

unblocked picture ads

### Screenshot(s)

<img width="1910" alt="adpicturr4" src="https://user-images.githubusercontent.com/47333122/52590402-79a32e00-2e41-11e9-8a81-0fee1233b5ca.PNG">

### Versions

- Browser/version: [Firefox 65.0 64-Bit]
- uBlock Origin version: [v1.18.4]

### Settings

- 
[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/2852884/Settings.txt)

### Notes

Its looks like content, but this are only ads [Werbung, Anzeigen = ads]

**Comment by smed79** [comment]
https://forums.lanik.us/viewtopic.php?f=90&t=42609
