### ISSUE TITLE
hawaiitribune-herald.com, thegardenisland.com, westhawaiitoday.com Incorrect blocking 

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#4876]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.hawaiitribune-herald.com/2019/02/11/hawaii-news/10-new-vehicles-for-police-headed-to-island/`

`https://www.thegardenisland.com/2019/02/11/hawaii-news/storm-delays-delivery/`

`https://www.westhawaiitoday.com/2019/02/11/hawaii-news/lane-closure-planned-tuesday-in-hamakua/`

### Describe the issue

Header logo, date & temperature is incorrectly removed by EasyList filter `##.header-ad`

These three sites are the only I found that seem to be impacted from the list of [black press media](https://www.blackpress.ca/publications/) sites.

### Screenshot(s)

![capture](https://user-images.githubusercontent.com/22258847/52610536-90e91800-2e4f-11e9-9f75-479bdd08b3f5.png)

Will provide for other sites needed

### Versions

- Browser/version: Chrome Version 73.0.3683.27 (Official Build) beta (64-bit)
- uBlock Origin version: uBlock Origin  1.18.5b0 (Latest Dev Build)
- uBlock Origin Extra 2.80

### Settings

- Test profile with default settings and lists.

### Notes

Exclusion filter `hawaiitribune-herald.com,thegardenisland.com,westhawaiitoday.com#@#.header-ad` fixes the issue for me

**Comment by okiehsch** [comment]
Thanks.
