### ISSUE TITLE
[incorrect blocking] cookinglight.com, ew.com, foodandwine.com, fortune.com, hellogiggles.com, myrecipes.com, people.com, time.com, travelandleisure.com nav & sidebar links to other stories

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#4878]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.cookinglight.com/good-food-fast/2018-taste-test-awards`

`https://ew.com/tv/supernatural-stars-take-you-behind-the-scenes-in-exclusive-ew-portraits/`

`https://www.foodandwine.com/news/buddy-vs-duff-ace-of-cakes-cake-boss-food-network`

`http://fortune.com/2019/01/17/china-apple-amazon-taiwan/`

`https://hellogiggles.com/beauty/ayesha-curry-unconventional-marriage-advice/`

`https://www.myrecipes.com/kids/kid-approved/kid-friendly-meals`

`https://people.com/crime/elizabeth-thomas-tad-cummins-abductor-sentenced-prison/`

`http://time.com/5505441/mark-zuckerberg-mentor-facebook-downfall/`

`https://www.travelandleisure.com/trip-ideas/best-places-in-us-to-travel-in-february`

### Describe the issue

The header circulator and read more links sidebar are blocked on the above domains by the [EasyList](https://easylist.to/easylist/easylist.txt) generic procedural filter `##div[data-native_ad]`

### Screenshot(s)

See screenshot below that I took after disabling easylist and then applying the filter `##div[data-native_ad]` from EasyList in the uBO element picker preview to see what is removed incorrectly. Only showing screenshots for fortune.com & time.com but can provide for all sites if necessary.

Fortune.com:
![fortune](https://user-images.githubusercontent.com/22258847/51331503-e3e5d000-1a47-11e9-9c7c-ae32093ad42a.png)

Time.com:
![time](https://user-images.githubusercontent.com/22258847/51342678-7f843a00-1a62-11e9-832c-4b8d4d1376dd.png)

### Versions

- Browser/version: Chrome Version 73.0.3683.27 (Official Build) beta (64-bit)
- uBlock Origin version: uBlock Origin  1.18.5b0 (Latest Dev Build)
- uBlock Origin Extra 2.80

### Settings

- Test profile with default settings and lists.

### Notes

Exclusion filter `cookinglight.com,ew.com,foodandwine.com,fortune.com,hellogiggles.com,myrecipes.com,people.com,time.com,travelandleisure.com#@#div[data-native_ad]` will fix the issue.

All of the domains above that are broken are owned by [Meredith Corporation](https://www.meredith.com/national-media/brands)

I opened this on [Easylist issue tracker](https://github.com/easylist/easylist/issues/2663) weeks ago but they don't seem to be responsive so thinking this can go in uAssets unbreak filter list.

**Comment by mapx-** [comment]
thx
