### ISSUE TITLE
www.netdoktor.de [Anti Adblock]

### ISSUE THREAD

**Issue by uBlockIsBest** [uBlockOrigin/uAssets#4880]
### URL(s) where the issue occurs

`www.netdoktor.de`

### Describe the issue

Anti Adblock

### Screenshot(s)

<img width="1912" alt="antiadblockpicture12" src="https://user-images.githubusercontent.com/47333122/52646963-0f8f9500-2ee4-11e9-8486-568d48b671a7.PNG">

### Versions

- Browser/version: [firefox 65.0]
- uBlock Origin version: [v1.18.4]

### Settings

- 
[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/2856459/Settings.txt)

**Comment by PerfectSalad** [comment]
Does `https://www.netdoktor.de/` have anti-adb?
