### ISSUE TITLE
Facebook sponsored posts are being displayed

### ISSUE THREAD

**Issue by nemoload** [uBlockOrigin/uAssets#4882]
### URL(s) where the issue occurs

`https://facebook.com`

### Describe the issue

Facebook use a "complex" HTML tags to evade UBlock.  

### Screenshot(s)
<image src="https://external-preview.redd.it/_g9tnUlglUH0VR3A3GHoTQPd4ttokussDIOQn_6izCg.jpg?width=455&auto=webp&s=390ff4d379944d14ea5691810841be8238415de4">
</image>
[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: 65.0
- uBlock Origin version: 1.18.4

**Comment by mapx-** [comment]
use this issue for any new FB problem
https://github.com/uBlockOrigin/uAssets/issues/3367
