### ISSUE TITLE
adblock-detect is not blocked

### ISSUE THREAD

**Issue by Voileexperiments** [uBlockOrigin/uAssets#4883]
Source: https://github.com/JeroenVdb/AdBlock-Detect

Example Usage: `https://www6.atwiki.jp/vpvpwiki`

A script needs to be injected that defines a no-op `adblockDetect` function. I do not see any from the resource library.

**Comment by Voileexperiments** [comment]
Update: After some investigations `adblock-detect` is triggered if EasyList filter is on.

**Comment by okiehsch** [comment]
Already fixed in `uBO-annoyances`.
