### ISSUE TITLE
clever-tanken.de breaks due to filter in uBlock filters.

### ISSUE THREAD

**Issue by hauk92** [uBlockOrigin/uAssets#4884]
### URL(s) where the issue occurs

`https://www.clever-tanken.de/`

### Describe the issue

The uBlock filters list breaks the selection of fuel type and location at the top of the page.

### Screenshot(s)

Broken page:
![image](https://user-images.githubusercontent.com/47572039/52657685-7ff4e100-2ef9-11e9-8568-592c7c92e90a.png)

Working page with filter disabled:
![image](https://user-images.githubusercontent.com/47572039/52657847-dbbf6a00-2ef9-11e9-847b-210c17d1d36f.png)

### Versions

- Browser/version: Chrome 71.0.3578.98
- uBlock Origin version: 1.18.2

### Settings

Standard filter lists, especially uBlock filters.

### Notes

`clever-tanken.de##+js(addEventListener-defuser.js, /^(?:DOMContentLoaded|load)$/, =!0)`
It seems that this rule blocks too much.

**Comment by mapx-** [comment]
if you disable the filter
`clever-tanken.de#@#+js(addEventListener-defuser.js, /^(?:DOMContentLoaded|load)$/, =!0)`

do you get some ad ?

**Comment by mapx-** [comment]
yep, there are ads (uisng a german ip)
