### ISSUE TITLE
video247.xyz

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#489]
http://video247.xyz/suits-s6e12-the-painting/

When clicking on the "TheVid" tab, then clicking the play button for the video, a bunch of tabs try to open and then are closed. This also happens on other websites as well using uBlock Origin. It seems that uBlock Origin lets tabs open briefly before closing them. Sometimes uBlock Origin doesn't even close the ads after it opens them. Also, it seems that uBlock Origin sometimes opens ads in windows as well. Is there a way to get uBlock Origin to block ads, without opening tabs, while letting the website work properly?

![couchtuner](https://user-images.githubusercontent.com/26278182/27748640-2c2899a0-5d9e-11e7-80bc-e9950f769232.jpg)

![adobe flash player](https://user-images.githubusercontent.com/26278182/27748665-41ef4e82-5d9e-11e7-9ec2-9478c097eae0.jpg)

Firefox Developer Edition 55.0b6 (32-bit)
uBlock Origin 1.13.0
Anti-Adblock Killer 10.0
uBlock Protector List 8.61
AdBlock Protector Script 7.33

**Comment by SMed79** [comment]
On which video player ?

```
http://thevideo.me/embed-4ebj8dbi42z0-540x330.html
http://vidto.me/embed-7ipzv89if422-540x330.html
http://vidup.me/embed-kgkfhdw5umty.html
http://vshare.eu/embed-laspdbtnugey-540x330.html
https://openload.co/embed/n1_0X7PKlts/
```

**Comment by js017** [comment]
See the updated post and screenshots for more details. On the "TheVid" tab, which is probably http://thevideo.me/embed-4ebj8dbi42z0-540x330.html. Thanks.

**Comment by okiehsch** [comment]
I don't get any popups on the "TheVid" tab. Have you updated your uBO-filter list?
A fix for `thevideo.me/tvad.me` was added before you opened this issue.

**Comment by SMed79** [comment]
for the thevideo.me and vidup.me i use these filters
```
$popup,domain=thevideo.me|vidup.me
$subdocument,~third-party,domain=thevideo.me|vidup.me
@@||vidup.me/adsense.js?$script,domain=vidup.me
@@||thevideo.me/js/jspc.js?ab|$script,domain=thevideo.me|vidup.me
```

**Comment by okiehsch** [comment]
@SMed79 is gorhills [fix](https://github.com/uBlockOrigin/uAssets/commit/5b999ed8caa437cef4f42b13cd99fc63ba7c9dee) not working for you?

**Comment by SMed79** [comment]
Work, already Edit my post before you post a reply.

**Comment by gorhill** [comment]
This was fixed earlier with 5b999ed8.

**Comment by SMed79** [comment]
It's possible to do the same for : http://**vidup.me**/embed-v2lw1osd24vu.html

`vidup.me##script:inject(abort-on-property-read.js, adsShowPopup)`

**Comment by js017** [comment]
When you go to this website: http://video247.xyz/suits-s6e12-the-painting/ and click the "Vshare" tab, then click to play the video, a bunch of tabs and windows open and then close instead of just blocking the ads on the website without opening any tabs or windows. Sometimes, if you reload the page and click the "Vshare" tab, then click to play the video again, the same thing happens, except a window with this website: http://newsoft2update.sophisticated2upgrade.site/?pcl=473xpUNVfQNieybtTPRINI9dF77oPMMFSU_tlKk5zKo.&sid=VjN8MzUxOHw5NjA3Mzh8NzA1MTY5fDE0OTg4NjIzODF8ZWQyNzNhZDktMmU2Ni00ODBkLWEwMmQtYWE2ZjkyNTE0NzAwfDk5LjI0NS4yMjUuMjM0fDF8MjgxYzE0NzA0NGY2N2YwM2Y3ZDQ2ZjdlODMyNTkwODE=&v_id=urGhMd8uRc6fp4Iu5aewYDPpYzOtZAfFkpgv_cjjtlw. stays open.

![ublock origin pop-up window](https://user-images.githubusercontent.com/26278182/27756329-927259dc-5dc4-11e7-90b9-f174883189b8.jpg)

This kind of issue happens on other sites as well where tabs and windows open and then close, but uBlock Origin doesn't seem to just block the ads without opening any annoying tabs or windows.
