### ISSUE TITLE
spiele-umsonst.de

### ISSUE THREAD

**Issue by uBlockIsBest** [uBlockOrigin/uAssets#4890]
### URL(s) where the issue occurs

`http://www.spiele-umsonst.de/fireboy-and-watergirl-5-t6382.html`

### Describe the issue

unblocked picture ads

### Screenshot(s)

<img width="1907" alt="adpicture12" src="https://user-images.githubusercontent.com/47333122/52662101-c8190100-2f03-11e9-9b0e-005b5c676240.PNG">

### Versions

- Browser/version: Firefox 65.0
- uBlock Origin version: v1.18.4

### Settings

- 
[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/2857307/Settings.txt)

### Notes

This filter will block all ads
`spiele-umsonst.de##div[class][style="float: left; color: rgb(255, 255, 255); font-size: 9px; display: block;"]`

**Comment by okiehsch** [comment]
They link to games on the same site and I would classify that as self-advertisement which will not be bocked. 
Also same as https://github.com/uBlockOrigin/uAssets/issues/4891
