### ISSUE TITLE
Videos hidden on NSFW free18.net

### ISSUE THREAD

**Issue by IDKwhattoputhere** [uBlockOrigin/uAssets#49]
### URL(s) where the issue occurs

NSFW: `http://www.free18.net/video-kalyn-arianna-anal-fucked-watch-18521.html`

### Describe the issue

The video is hidden by `##.addthis_toolbox` in `uBlock filters – Privacy‎`. Oddly the issue persists when subscribing to `Fanboy’s Social Blocking List‎` which contains a fix. The filter also doesn't show up in the logger after adding the list. Is this intended behavior?

### Screenshot(s)

![](https://cloud.githubusercontent.com/assets/16030872/15502416/0d5a63fe-21b4-11e6-825f-7315d244782d.png)

### Versions

- Browser/version: Chromium 51
- uBlock Origin version: 1.7.5b2

### Settings

- Default

### Notes

https://forums.lanik.us/viewtopic.php?f=64&t=30190

**Comment by gorhill** [comment]
> issue persists when subscribing to `Fanboy’s Social Blocking List‎` which contains a fix

The fix in `Fanboy’s Social Blocking List‎` works for me.

**Comment by IDKwhattoputhere** [comment]
Right. I was using `Fanboy’s Annoyance List‎` where it doesn't seem to work. I assumed the outcome would be the same. Odd.

**Comment by gorhill** [comment]
I confirm it does not work on my side either with `Fanboy’s Annoyance List‎`.

**Comment by gorhill** [comment]
`Fanboy’s Annoyance List‎` contains `##.addthis_default_style`. Need `free18.net#@#.addthis_default_style`.

**Comment by gorhill** [comment]
![a](https://cloud.githubusercontent.com/assets/585534/15506404/82923986-2195-11e6-95f3-195cacc1b48e.png)

**Comment by IDKwhattoputhere** [comment]
I see, thanks.
https://forums.lanik.us/viewtopic.php?p=94416#p94416
Should the first exception filter be added to uBO's filters too so the site works with default settings?

**Comment by gorhill** [comment]
That's right, I lost track of the primary issue.

**Comment by gorhill** [comment]
I imported as is the corresponding exception filter in `Fanboy's Social`.
