### ISSUE TITLE
nation.co.ke

### ISSUE THREAD

**Issue by kipyegonmark** [uBlockOrigin/uAssets#4902]
### URL(s) where the issue occurs

`nation.co.ke`
`https://www.nation.co.ke/lifestyle/dn2/Dreams-from-the-heartland/957860-4979434-ga7b1lz/index.html`

### Describe the issue

Ads on the homepage `nation.co.ke` and links within the site

### Versions

- Browser/version: Firefox Nightly 67.0a1 (2019-02-12) 
- uBlock Origin version: 1.18.4

### Settings

- Default

### Notes

N/A

**Comment by okiehsch** [comment]
I can't reproduce, I can see ads but no anti-adblock message.

**Comment by kipyegonmark** [comment]
That is an error on my end, I shall amend.

**Comment by okiehsch** [comment]
OK, if you update your `uBO-filters` list the ads should be gone.

**Comment by JobcenterTycoon** [comment]
They changed the domain to `https://nation.africa`

**Comment by JobcenterTycoon** [comment]
@mapx- 

please update

**Comment by mapx-** [comment]
test

`nation.africa##+js(aopr, evolokParams.adblock)`
