### ISSUE TITLE
rambler.ru

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#4904]
advertising (similar only) in firefox. _at least there are no ads in opera_

help me out @mapx- turn on your voodoo, how do I remove it? Plz

![2019-02-14 08 22 50-fullpage](https://user-images.githubusercontent.com/8535285/52744891-eb41ce80-3031-11e9-93c6-b4b14e4fbb3c.png)

**Comment by mapx-** [comment]
I get no such ads FF / chrome / opera

**Comment by bogachenko** [comment]
Try to clean the cookies, and scroll to the end of the page. I do not know...

I can throw off the saved page

**Comment by mapx-** [comment]
try in firefox
`rambler.ru##^script:has-text((Number,)`

**Comment by bogachenko** [comment]
It seems there is no advertising. You can remove the white block on the right (the very first in the screenshot, instead of advertising there is a white block)?

**Comment by mapx-** [comment]
try in opera / chrome
`rambler.ru##+js(setTimeout-defuser.js, (), 1000)`

**Comment by bogachenko** [comment]
so in the opera and so there is no advertising, it is only on firefox

**Comment by mapx-** [comment]
```
rambler.ru##^script:has-text((Number,)
rambler.ru##+js(setTimeout-defuser.js, (), 1000)
```

So, this couple of filters would work in FF / opera for you, right ?

**Comment by bogachenko** [comment]
only 1 works

**Comment by mapx-** [comment]
You mean the timeout filter does not work in opera ?

**Comment by bogachenko** [comment]
no

**Comment by bogachenko** [comment]
look. Lol now in opera there is an advertisement ...
![op](https://user-images.githubusercontent.com/8535285/52748159-e3862800-3039-11e9-9130-66eb6ac8d255.gif)

**Comment by mapx-** [comment]
Well, opera still needing a filter
