### ISSUE TITLE
virginmobile.ca

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#4909]
`https://www.virginmobile.ca/en/internet/index.html`

Hi, when going to `https://www.virginmobile.ca/en/internet/index.html`, and clicking on the "+ * legal stuff" option at the bottom of the page, it doesn't work if ublock origin is enabled, but then if you disable ublock origin, it works. Is there a way to fix that? Why doesn't ublock origin work properly? Thanks. Have a nice day.

![virgin mobile 2](https://user-images.githubusercontent.com/35790889/52809797-17c00f80-305f-11e9-9825-17a9ef33bc6a.jpg)

![virgin mobile 1](https://user-images.githubusercontent.com/35790889/52809785-10006b00-305f-11e9-8ba5-97eee4a51a4e.jpg)

firefox 65.0.1 (64-bit)
ublock origin 1.18.4

**Comment by mapx-** [comment]
@IoanPaleru  

> Why doesn't ublock origin work properly?

You've been an adblocker user for quite a while. You should know there are **filters issues**. 
(in this case its about a easyprivacy filter issue)

**Comment by IoanPaleru** [comment]
Yeah, there definitely are issues with it.

**Comment by IoanPaleru** [comment]
Can you fix those filters issues so that the program works better? Thanks.
