### ISSUE TITLE
NSFW "imagefap.com"

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#491]
NSFW "beta.imagefap.com"

When going to NSFW "beta.imagefap.com", the mobile version of imagefap.com on Android, there's a pop-up window that says "Oops! It appears your Ad Blocker is not playing nicely and is blocking critical parts of ImageFap. We support your decision to use an Ad Blocker and welcome you to Fap! As a solution consider using an alternative Ad Blocker or disabling it for ImageFap." and it doesn't let you view the website unless you disable uBlock Origin.

![screenshot_20170701-095415](https://user-images.githubusercontent.com/26278182/27763017-021dcdb8-5e4a-11e7-80db-d5abea9fc9c8.png)

Firefox for Android 54.0.1
uBlock Origin 1.13.4

**Comment by gorhill** [comment]
Caused by EasyList `|http://$script,domain=imagefap.com` and `|http://$xmlhttprequest,domain=imagefap.com` filters.

Report to maintainers of EasyList: <https://forums.lanik.us/viewforum.php?f=64>.

**Comment by ghajini** [comment]
@gorhill,little offtopic....when visiting page I get this error about avast which conflicts with ublock origin

http://prntscr.com/fqf1vo

...what does than

**Comment by gwarser** [comment]
@ghajini [https://github.com/gorhill/uBlock/issues/1170](https://github.com/gorhill/uBlock/issues/1170)

**Comment by mapx-** [comment]
https://forums.lanik.us/viewtopic.php?p=120359#p120359https://forums.lanik.us/viewtopic.php?p=120359#p120359
