### ISSUE TITLE
putlockernet.net

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4910]
### URL(s) where the issue occurs

`https://putlockernet.net`

### Describe the issue

popup ads
### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.18.4

### Settings

- uBO's default settings

### Notes

block these also like
```
||hantinlethemsed.info^$important
||jungloconding.info^$important
||rephartertonelin.info^$important
```
present on many sites

**Comment by ghajini** [comment]
`http://www1.putlockernet.net/watch/godzilla-king-of-the-monsters-2019.html`
popup ads

**Comment by dumbusernameidk** [comment]
@mapx- 
possible fix for `waaw.tv` not allowing dev tools? i tried `waaw.tv##+js(noeval)` to stop anti-debugger but after this it's just a white screen with "don't open developer tools message".

**Comment by mapx-** [comment]
example link ?

**Comment by dumbusernameidk** [comment]
the one ghajini posted works.

**Comment by mapx-** [comment]
see if works for you too

**Comment by dumbusernameidk** [comment]
yes works thank you.
