### ISSUE TITLE
putlockers-hd.stream/movies/

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4911]
### URL(s) where the issue occurs

`https://putlockers-hd.stream/movies/`

### Describe the issue
popup ads

### Versions
* Browser/version: opera browser
* uBlock Origin version: 1.18.4

### Settings
* uBO's default settings

### Notes

fake player `https://putlockers-hd.stream/movies/watch-west-side-story-1961-online-free-full-film/#option-2` at top clicking on it leads to malware sites

**Comment by lain566** [comment]
Can't click play button
`https://putlockers-hd.stream/movies/watch-avenging-angel-2007-online-free-full-film/`

Suggested filter
`putlockers-hd.stream###playeradds`

**Comment by ghajini** [comment]
`https://putlockers-hd.stream/movies/watch-at-eternitys-gate-2018-online-free-full-film/`
popup ads

**Comment by Mofazzal01** [comment]
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
https://www.ufc240livestream.com/ufc242/
