### ISSUE TITLE
protopage.com

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#4914]
### URL(s) where the issue occurs

`[http://protopage.com/ktreglia#Social_Media_in_Education]`

### Describe the issue

[Ad at the top of the page.]

### Versions

- Browser/version: [Chrome v71]
- uBlock Origin version: [1.18.4]

### Settings

- [default]

**Comment by okiehsch** [comment]
What ad? Do you mean
![image](https://user-images.githubusercontent.com/16838044/52832509-15020080-30d9-11e9-8d2b-1127d88f8e6f.png)

**Comment by dumbusernameidk** [comment]
Yeah that I can't even hide it with element picker so maybe a script is causing it to appear?

**Comment by okiehsch** [comment]
That appears even if you disable `uBO`, so it is not an anti-adblock message and won't be fixed.

**Comment by dumbusernameidk** [comment]
Is it technically possible to block? If not I can just close the issue.

**Comment by okiehsch** [comment]
You can hide it, I don't think you can block it.

**Comment by dumbusernameidk** [comment]
Alright also I made this post as the issue was posted on the subreddit as well. I'll close it if it cannot be hidden.

**Comment by okiehsch** [comment]
> can't even hide it with element picker

Using the element picker
````
protopage.com##body > div:nth-of-type(17)
protopage.com##body > div:nth-of-type(19)
````
works on my end.

**Comment by dumbusernameidk** [comment]
👌

**Comment by okiehsch** [comment]
Probably better
````
protopage.com##body > div:has-text(ad blocker)
protopage.com##body > div:has-text(Remove ads)
````
