### ISSUE TITLE
cyberciti.biz

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uAssets#4916]
### URL(s) where the issue occurs
`https://www.cyberciti.biz/tips/domain-check-script.html`

### Describe the issue
Anti-adblock message

### Screenshot(s)

![screenshot_20190215_141847](https://user-images.githubusercontent.com/19818572/52859308-a2bb0b80-312c-11e9-9ab5-80578d2a1ae7.png)

### Versions

- Browser/version: Vivaldi 2.3.1440.41 (based on Chromium 72.0.3626.82)
- uBlock Origin version: 1.18.4

### Settings
<img src="https://user-images.githubusercontent.com/19818572/51703016-8cca9700-2015-11e9-92aa-58d40f0f7e62.png">

### Notes
That helps => `@@||cyberciti.biz/js/ads.js` :smile:.

**Comment by mapx-** [comment]
Is it only an annoyance ?
