### ISSUE TITLE
Some German websites with Anti-Adblock measures 

### ISSUE THREAD

**Issue by TonyTough** [uBlockOrigin/uAssets#492]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`www.freiepresse.de`
`www.wz.de`
`www.andreas-unterberger.at`

### Describe the issue

On nearly all **subsites** of `www.freiepresse.de` and `www.wz.de` it says you have to deactivate your adblocker. On `www.wz.de` it is time depandant and is active after 1 minute.

These filters work, but maybe they are too "aggressive"
||freiepresse.de^$inline-script
||wz.de^$inline-script`

On `www.andreas-unterberger.at` the Anti-Adblock measure is active on the main site, but I havn't found a working filter yet.

### Versions

- Browser/version: Firefox 54.01
- uBlock Origin version: 1.13.4 with default filters + Easylist Germany

**Comment by okiehsch** [comment]
Does 
````
@@||andreas-unterberger.at/*/ads.js$script,first-party
freiepresse.de##script:inject(abort-on-property-read.js, fpo_hasAB)
wz.de##script:inject(abort-on-property-read.js, jsABLoaded)
````
work for you?

**Comment by TonyTough** [comment]
> @@||andreas-unterberger.at/*/ads.js$script,first-party
> wz.de##script:inject(abort-on-property-read.js, jsABLoaded)

These two work, but the one for freiepresse still shows the Anti-Adblock message.

**Comment by okiehsch** [comment]
1. Does `||andreas-unterberger.at/includes/js/helperFunctions.js$script,first-party` also work for you?
2. About freiepresse: The filter works on my end, you may have to delete cookies for this site-

**Comment by TonyTough** [comment]
> Does ||andreas-unterberger.at/includes/js/helperFunctions.js$script,first-party also work for you?

Yes, it works

> About freiepresse: The filter works on my end, you may have to delete cookies for this site-

OK, now it seems to work, thank you!
