### ISSUE TITLE
fabsdeals.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#4920]
URL(s) where the issue occurs

`https://fabsdeals.com/uksF1F`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 71 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.18.2

Settings

Default

**Comment by krystian3w** [comment]
related:  https://github.com/MajkiIT/polish-ads-filter/issues/12149

**Comment by krystian3w** [comment]
Show again on **`@`lukjan32** PC (Windows 7 + Opera + uBO 1.17.0); maybe webmasters read github or use uBlock Origin?

**Comment by krystian3w** [comment]
`https://geki.tech/uksF1F`

**Comment by krystian3w** [comment]
Again paid new domain:

```
https://yesmoviesapp.info/I6Jw
``§

**Comment by mapx-** [comment]
already fixed
https://github.com/uBlockOrigin/uAssets/issues/5071

**Comment by krystian3w** [comment]
Ok again fixed.

**Comment by krystian3w** [comment]
`viralnow.xyz/I6Jw` @mapx-  / @okiehsch

**Comment by mapx-** [comment]
@krystian3w  please don't spam `uAssets` reporting 3 times the same issue.
