### ISSUE TITLE
linkgen.xyz

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4924]
### URL(s) where the issue occurs

`https://linkgen.xyz/EklkR`

### Describe the issue

antiadblock
### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.18.4

### Settings

- uBO's default settings

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters

**Comment by okiehsch** [comment]
Already removed.
