### ISSUE TITLE
imagefap.com NSFW

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#4928]
`https://www.imagefap.com/signup.php` NSFW

Hi. When going to `https://www.imagefap.com/signup.php` and trying to create a new account, with ublock origin enabled, it doesn't show the google captcha above the "create account" button, which is necessary to create an account, but with ublock orgin disabled, it shows it. Is there a way to fix that? Thanks.

![imagefap 001](https://user-images.githubusercontent.com/35790889/52905046-2f83c900-3202-11e9-8769-cabf6f82426d.jpg)

![imagefap 002](https://user-images.githubusercontent.com/35790889/52905048-33175000-3202-11e9-9fe5-aa1a855e2921.jpg)

firefox 65.0.1 (64-bit)
ublock origin 1.18.4

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by IoanPaleru** [comment]
Why can't you reproduce? Aren't you using the latest versions of ublock origin and firefox? That's what I'm using. Thanks.
