### ISSUE TITLE
guerrillamail.com

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#4929]
guerrillamail.com

Hi, when going to guerrillamail.com, and clicking on the email "compose" tab, if ublock origin is enabled, it takes you to a page that shows a loading icon and says "error, connection to the server lost", but if you refresh the page then it loads the email composition window normally, however with ublock origin disabled, it just loads the email composition window normally in the first place. Is there a way to fix that? Thanks, and have a nice day.

![guerrillamail 001](https://user-images.githubusercontent.com/35790889/52905698-b1c4bb00-320b-11e9-8e63-8136e86b443f.jpg)

![guerrillamail 002](https://user-images.githubusercontent.com/35790889/52905700-b4bfab80-320b-11e9-8a88-af7ce6cbbee8.jpg)

![guerrillamail 003](https://user-images.githubusercontent.com/35790889/52905702-b7220580-320b-11e9-9522-b4271a512a3c.jpg)

firefox 65.0.1 (64-bit)
ublock origin 1.18.4

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by IoanPaleru** [comment]
Why can't you reproduce? Aren't you using the current version of ublock origin and firefox with the default settings? That's what I'm using. Thanks.
