### ISSUE TITLE
Promoted posts aren't blocked on Reddit desktop

### ISSUE THREAD

**Issue by CapacitorSet** [uBlockOrigin/uAssets#493]
### URL(s) where the issue occurs

`https://reddit.com/`

### Describe the issue

When browsing the desktop version of Reddit, promoted posts are occasionally displayed.

### Screenshot(s)

http://i.imgur.com/Ffyn0Ru.png

Note that this screenshot was taken when browsing with Reddit Enhancement Suite, so it looks different without the extension (RES adds a night mode and a few buttons). However, the ad is from Reddit.

### Versions

- Browser/version: FF 54.0
- uBlock Origin version: 1.13.4

### Settings

None that I remember of.

### Notes

It was successfully fixed adding the rule `##.suggestedlink`.

**Comment by SMed79** [comment]
Do you still see the promoted posts without RES addon?

**Comment by CapacitorSet** [comment]
Yes, I could reproduce it without RES: http://i.imgur.com/v48YTuH.png

The promoted post has the following HTML: `<div class=" thing id-t3_5lnzdw link promoted odd  promotedlink " id="thing_t3_5lnzdw" onclick="click_thing(this)" data-fullname="t3_5lnzdw" data-type="link" data-cid="t8_p7w4" data-imp-pixel="//pixel.redditmedia.com/pixel/of_doom.png?r=824603905&amp;hash=9fb87d8619c84c8dd80fd02df48f3406dc267fb6&amp;id=t3_5lnzdw-t8_p7w4-italy" data-adserver-imp-pixel="https://pixel.redditmedia.com/i.gif?e=[several lines of data]" data-adserver-retarget-pixel="https://engine.a.redditmedia.com/udb/5146/rt/93156/338721764/i.gif" data-adserver-click-url="https://engine.a.redditmedia.com/r?e=[several lines of data]" data-adserver-upvote-pixel="https://engine.a.redditmedia.com/e.gif?e=[several lines of data]" data-adserver-downvote-pixel="https://engine.a.redditmedia.com/e.gif?e=[several lines of data]" data-third-party-tracker-urls="[]" data-house="true" data-author="reddit_exchanges" data-author-fullname="t2_fc0l0" data-subreddit="promos" data-subreddit-fullname="t5_2r4w1" data-timestamp="1483395160000" data-url="//pixel.redditmedia.com/click?url=https%3A%2F%2Fengine.a.redditmedia.com%2F[several lines of data]" data-domain="redditgifts.com" data-rank="" data-comments-count="0" data-score="6626" data-context="request_promo" style="">` It probably suffices to blacklist `.promoted` or `.promotedlink`.

**Comment by gotitbro** [comment]
Was reproduced by me just once. This could be causing it: 
`https://www.reddit.com/api/request_recommended_link`

Not sure though.

**Comment by gotitbro** [comment]
@okiehsch These ads are loaded by the above mentioned XHR request almost certainly.

**SS:** 
http://i.imgur.com/WbqqATV.png (SS of ad)
http://i.imgur.com/3ZLxb06.png (SS of XHR request)

**Error URL:** https://www.reddit.com/ (If the ad loads for you. Check the XHR SS above)

This XHR request should be blocked:
`||reddit.com/api/request_recommended_link`

**Comment by okiehsch** [comment]
I can't reproduce any ads, I see the xhr request but no ads on my end.

**Comment by gotitbro** [comment]
@okiehsch The filter that I mention above which blocks the XHR request has been reported to be working by several people here as well: https://www.reddit.com/r/uBlockOrigin/comments/5zuyb0/recommended_by_reddit_ads/

I think it should be added.

**Comment by okiehsch** [comment]
Well, it is a filter that can be added to EasyList, maybe they can also reproduce an actual ad, I can't.

**Comment by gotitbro** [comment]
@okiehsch Reported to EasyList maintainers. Though I recommend adding the suggested filter as it has been proved to be working by multiple people and can also be deduced by looking at the screenshots above.

Or is it necessary for the issue to be reproduced by contributors? These ads occur infrequently can't say if they will be reproduced as when required.

**Comment by gorhill** [comment]
I've don't remember ever seeing a "recommended" post on reddit. Could be RES, or special custom settings on reddit itself. Best is that people who experienced this investigate to narrow the cause of why these "recommended" posts appear. Or at least provide repro steps so that other can investigate.

**Comment by gotitbro** [comment]
@gorhill I got these ads and as per the investigation reported above by me they are caused by this XHR request `reddit.com/api/request_recommended_link`. This can be blocked to block these recommended ads as has been reported multiple times: https://www.reddit.com/r/uBlockOrigin/comments/5zuyb0/recommended_by_reddit_ads/

There don't seem to be any repro steps as these ads appear sporadically. Please see if you can block the XHR URL, new issues for the same ads are being posted again: https://github.com/uBlockOrigin/uAssets/issues/677

**Comment by gotitbro** [comment]
@mapx- Has this been resolved? I still got these recommended posts and the above filter still works.
