### ISSUE TITLE
atresplayer.com

### ISSUE THREAD

**Issue by pizza90** [uBlockOrigin/uAssets#4931]
### URL(s) where the issue occurs

1. `https://www.atresplayer.com/`
2. `https://www.atresplayer.com/lasexta/programas/salvados/clips/salvados-arranca-temporada-con-los-actores-de-campeones_5bc4c6c27ed1a82a8e123286/`
3. `https://www.atresplayer.com/antena3/series/el-secreto-de-puente-viejo/fernando-mesia-contraataca/15-02-19_5c59d3e47ed1a8de2487d2b0/`
4. `https://www.atresplayer.com/antena3/series/amar-es-para-siempre/temporada-7/15-02-19_5c59caae7ed1a8de2487d283/`
5. `https://www.atresplayer.com/antena3/series/matadero/clips/video-descubre-quien-es-quien_5c34df537ed1a82b9541f1b9/`
6. `https://www.atresplayer.com/antena3/programas/la-voz/temporada-1/programa-12-audiciones-a-ciegas_5c5da03d7ed1a8e713185066/`
7. `https://www.atresplayer.com/antena3/snacks/el-diario-de-la-voz/temporada-1/la-habitacion-de-javier-erro-sandra-groove-y-laura-gonzalez_5c655cb27ed1a8b4dc87fde0/`

### Describe the issue

Ads in videos and website not blocked

### Screenshot(s)

in web: https://i.imgur.com/7b83Mmq.jpg
in video: https://i.imgur.com/YYw9Oxu.png

### Versions

- Browser/version: Chrome - Versión 72.0.3626.109 (Build oficial) (64 bits)
- uBlock Origin version: v1.18.4

### Settings

- Default  Settings

### Notes

the ads are shown sporadically, they are not always there.

the cursor over the banner, showed the following url of smartadserver, Example:  `www3.smartadserver.com/click? etc.. etc.. etc..`

i use this below filters for remove anti adblock, found in `forums.lanik.us`

```
@@||adpass.atresmedia.com/*/adjs.js$xmlhttprequest,domain=atresplayer.com
@@||adpass.atresmedia.com/*/index/advertisement.js
@@||adpass.atresmedia.com/*/advertisement.js$domain=atresplayer.com
@@||atresplayer.com^$generichide
@@||adpass.atresmedia.com/*/index/*/ad*.js$xmlhttprequest
```

**Comment by NubN** [comment]
`https://www.atresplayer.com/`

**aa**
`@@||assets.adobedtm.com^$xhr,domain=www.atresplayer.com`
