### ISSUE TITLE
uBlock bypassed by some ads with a dot

### ISSUE THREAD

**Issue by benkowwokned** [uBlockOrigin/uAssets#4932]
### URL(s) where the issue occurs

`https://tpbproxy.online/`
`www.hostingcloud.science./1IL4.js`

### Describe the issue

I've found a script include on a clone of the pirate bay, that script was bypassing uBlock in that way
```
<script src="https://www.hostingcloud.science./1IL4.js" type="fae6b08ae6566af1418bd51b-text/javascript"></script>

```
(https://i.imgur.com/BsB3FJE.png)

`www.hostingcloud.science./1IL4.js` is not blocked by uBlock (coin miner) but `www.hostingcloud.science/1IL4.js` (without the dot after science) is blocked by uBlock (||hostingcloud.science^ FRA: EasyList Liste FR  • EasyPrivacy )

(https://i.imgur.com/2AA9W2i.png
https://i.imgur.com/K5RCH7h.png)

Seems to not be reproduce by everybody, the problem is maybe in EasyList Liste FR  • EasyPrivacy
### Versions

- Browser/version: Chrome 72.0.3626.109 on Windows 10
- uBlock Origin version: 1.18.4

### Settings

Default settings

### Notes

N/A

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/52912149-ad50de80-32ad-11e9-8c65-ce2a6d14fd22.png)

As you can see `www.hostingcloud.science./1IL4.js` is blocked by `||hostingcloud.science^` as it should be.

**Comment by benkowwokned** [comment]
After trying with dev tools it looks like the script is blocked yep.
The problem occurs only if I browse the website
Thx for your time, I'm sorry for having bothered you :/

**Comment by okiehsch** [comment]
No problem
