### ISSUE TITLE
pch.com site is broken and my grandmother is upset

### ISSUE THREAD

**Issue by asdasdfgh** [uBlockOrigin/uAssets#4933]
https://www.pch.com/slotsgameplay/slotsgames/tournament-path/wild-west-slots-tournament-path/

One (or more) of the default filters is breaking this site now. 
https://www.reddit.com/r/uBlockOrigin/comments/9z8gx0/ublock_origin_on_publishers_clearing_house/
Found this thread of another user having the same issue. Can't quite figure out which of the filters lines is doing it though.

please help my grandmother just wants to play her dumb slot games i know the site is hot garbage but it makes her happy

**Comment by mapx-** [comment]
needing account => could you post all the blocked requests (from the logger) ?
In alternative, send me (here: `axis.trivia@gmail.com` ) the credentials for a test account

**Comment by dumbusernameidk** [comment]
Looks like a filter from adguard annoyance list breaks the site. Just disable that filter list if you have it on.

**Comment by mapx-** [comment]
Well, you have the fix (for your issue), just report the issue at adguard repository
https://github.com/AdguardTeam/AdguardFilters/issues
