### ISSUE TITLE
My website is not ad related (www.adnet.hr), please whitelist it.

### ISSUE THREAD

**Issue by Janjko** [uBlockOrigin/uAssets#494]
### URL(s) where the issue occurs

`www.adnet.hr`

### Describe the issue

All media on my website is blocked because of its unfortunate name adnet.hr. Clients with uBlock are asking us why we have such a poor website. Please unblock it. Here is a link to the web archive to prove I didn't change the site just to be whitelisted:

https://web.archive.org/web/*/adnet.hr

**Comment by gorhill** [comment]
This happens because of the filter `/adnet.` in EasyList. Report to maintainers of EasyList: <https://forums.lanik.us/viewforum.php?f=64>.

**Comment by mapx-** [comment]
easylist has this rule:
`/adnet.$domain=~adnet.hr`

so, could be uBo does not read correctly the filter ?
