### ISSUE TITLE
Unblocked picture ads

### ISSUE THREAD

**Issue by uBlockIsBest** [uBlockOrigin/uAssets#4951]
### URL(s) where the issue occurs

`https://regionalbraunschweig.de/kvg-macht-ernst-45-zusaetzliche-elektrobusse-bis-2023/`
`https://regionalsalzgitter.de/kvg-braunschweig-beschafft-weitere-10-elektrobusse/`
`https://regionalheute.de/`
`https://regionalwolfenbuettel.de/`
`https://regionalsport.de/`
`https://regionalleben.de/`

### Describe the issue

Unblocked animated ad pictures

### Screenshot(s)

<img width="1907" alt="adpicture13" src="https://user-images.githubusercontent.com/47333122/53023837-3e66b780-345e-11e9-9fcd-9b06c968e179.PNG">

### Versions

- Browser/version: Firefox 65.0
- uBlock Origin version: v1.18.4

### Settings

- 
[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/2880497/Settings.txt)

### Notes

Randomized source.
translation: [Anzeige, Werbung = ads]

**Comment by mapx-** [comment]
it should be fixed in the regional list @monzta

add
```
*$xhr,domain=regionalbraunschweig.de
@@||regionalleser.de/api/$xhr,domain=regionalbraunschweig.de
regionalbraunschweig.de##.card:has-text(/Anzeige/i)
```

**Comment by uBlockIsBest** [comment]
Thanks

**Comment by monzta** [comment]
Added to EasyList Germany: https://github.com/easylist/easylistgermany/commit/d583bf89d530b365199f9571edecc392cf5cfb0b
