### ISSUE TITLE
tapatalk.com forums

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#4953]
when I visited today tapatalk.com (and relevant) forums,
I was overwhelmed with ads for vip,
I got those rules, if anyone has any better suggestions,
feel free to post here

```
||tapatalk.com/*/vip_plus$subdocument
tapatalk.com##div.post:has(div > div.vip_ads_upgrade.content)
tapatalk.com##.lastpost.vip-plus-btn-event
tapatalk.com##div.signature

```

sample urls:
https://www.tapatalk.com/groups/macrodroid/viewtopic.php?t=5920

and here a thread about it:
https://www.tapatalk.com/groups/tapatalksupport/viewtopic.php?p=219928#p219928

**Comment by mapx-** [comment]
try only this 1, see if works (provide links for the pages still having vip stuff)
`tapatalk.com##+js(abort-on-property-read.js, IS_VIP_PLUS)`

**Comment by patrickdrd** [comment]
yes, it works, thanks

other similar pages are like this one:
https://www.tapatalk.com/groups/tapatalksupport/viewtopic.php?p=219798#p219798

but this rule covers them,
I even deleted the cookies and it worked,
thanks, you can commit it I guess

**Comment by okiehsch** [comment]
It is self-advertisement, so I would say fix it in `uBO-annoyances`.
