### ISSUE TITLE
shop.rewe.de and rewe.de blocked by "Peter Lowe’s Ad and tracking server list"

### ISSUE THREAD

**Issue by Weyoun-rewe** [uBlockOrigin/uAssets#4954]
Currently the domains rewe.de and shop.rewe.de are falsely blocked in uBlock Origin by the filter list "Peter Lowe’s Ad and tracking server list".

Please fix this bug so these two domains can play their content correctly.

**Comment by mapx-** [comment]
I don't see rewe.de blocked in that list, update all your lists and test again
