### ISSUE TITLE
Remove/unbreak block of squirrelhands.com

### ISSUE THREAD

**Issue by admiral-pubhelp** [uBlockOrigin/uAssets#4957]
### URL(s) where the issue occurs

`https://www.nbcnews.com/politics?preview-engage=1`

### Describe the issue

The site above uses squirrelhands.com for access control. Calls to that domains are currently circumvented by uBO and its integrated filters.

### Screenshot(s)

How it looks (active circumvention)
![image](https://user-images.githubusercontent.com/41959276/53118423-0bcec480-351b-11e9-8118-fa6d90e6e679.png)

How it should look (no circumvention)
![image](https://user-images.githubusercontent.com/41959276/53118464-25700c00-351b-11e9-8f46-bd33c86d1782.png)

Filter to remove/unbreak: ||squirrelhands.com^
Filter list: Peter Lowe’s Ad and tracking server list 

### Versions

- Browser/version: Google Chrome Version 72.0.3626.109 (Official Build) (64-bit)
- uBlock Origin version: 1.18.4

### Settings

- removed uBO and re-installed uBO for fresh settings

### Notes

This circumvention can be fixed by either not distributing the circumventing filters, removing those filters or unbreaking them. Addition of the following to My Filters removed the circumvention:
@@||squirrelhands.com^

**Comment by okiehsch** [comment]
In your other issue you said
``uBO policy on this has been recently clarified here: https://twitter.com/gorhill/status/1072990091625328641"
![image](https://user-images.githubusercontent.com/16838044/53120114-61be5f00-3551-11e9-9860-92926fd98a7a.png)

This sites anti-adblocker message is dismissable but it reappears after every pageload on my end, so declined.

**Comment by admiral-pubhelp** [comment]
The link provided is a preview link to guarantee that you see it for debug purposes.  Therefore, when you refresh after whitelisting you are just getting the same preview URL again.

**Comment by okiehsch** [comment]
Correct, my bad.
