### ISSUE TITLE
tubecorporate.com network (NSFW)

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#4958]
### URL(s) where the issue occurs

`txxx.com`
`upornia.com`
`hclips.com`
`hotmovs.com`
`voyeurhit.com`
`vjav.com`
`tubepornclassic.com`

### Describe the issue

On desktop, there is a `out.tubecorporate.com` popup upon clicking play on any video during the first site visit. Some other factors may have a role in triggering this popup so it can be a little hard to reproduce.

On mobile, an ad overlay is triggered upon clicking play on any video and the video doesn't start unless that overlay is dismissed.

### Versions

- Browser/version: Firefox 65.0.1 / Firefox for Android 65.0.1
- uBlock Origin version: 1.18.4

### Settings

Default

**Comment by okiehsch** [comment]
I can't reproduce on Desktop.

**Comment by in4u** [comment]
Yes, I am not sure what exactly triggers the popup on desktop. It's random even in my case that's why I mentioned it earlier. But the mobile issue is easily reproducible.

**Comment by ghajini** [comment]
On mobile firefox,
Clicking play triggers `continue to video` or `cross icon`,  clicking on either will start the video, so no aanoyance at all

**Comment by in4u** [comment]
While playing around with different user agents and screen sizes in private browsing mode, I realized that on desktop the popup appears not just on clicking the play button but clicking anywhere on the entire page. Like, on `tubepornclassic.com` I got `<a class="nopop" target="_new" href="//out.tubecorporate.com/[external link with some parameters]" style="position:absolute;width:100%;height:100%;z-index:800;top:0;left: 0;">&nbsp;</a>` as an overlay element on the video page. And on mobile `c.showInterstitial()` function gets triggered on clicking the video.

**Comment by dumbusernameidk** [comment]
the class "nopop" is to blame. you can just simply add `##.nopop` and it'll get rid of that popup stuff completely.

**Comment by mapx-** [comment]
@in4u  did you test `##.nopop` ?

**Comment by in4u** [comment]
@mapx- It seems to work on desktop, so far. Another thing I noted was that the desktop popup does not appear on `hclips.com`. Maybe the [previous](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aclosed+hclips) filters prevent that.

**Comment by KiLL4FuNK** [comment]
ADS

**Comment by KiLL4FuNK** [comment]
ADS

`https://hdzog.com/videos/47565/z69-cs-km/`
