### ISSUE TITLE
www.tichyseinblick.de

### ISSUE THREAD

**Issue by TonyTough** [uBlockOrigin/uAssets#496]
### URL(s) where the issue occurs

`www.tichyseinblick.de`

### Describe the issue

Site seems to use Addefend now, big banners on top and right.

### Versions

- Browser/version: Firefox 54.0.1
- uBlock Origin version: 1.13.4

### Notes

`tichyseinblick.de##script:inject(uabinject-defuser.js)`
works for me.

**Comment by okiehsch** [comment]
Already [added](https://github.com/uBlockOrigin/uAssets/commit/fa6210dbb7c0cc8b6dafda9facb1a3f518dd6433).

**Comment by TonyTough** [comment]
Oh, sorry, I should have manually updated the filter list before.

**Comment by okiehsch** [comment]
No problem.
