### ISSUE TITLE
bloombergquint.com

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#4960]
### URL(s) where the issue occurs

`https://www.bloombergquint.com/business/nasscom-wont-provide-fy20-guidance-releases-ceo-survey-instead`

### Describe the issue

Two issues:

1. Open the link in private browsing mode. Website detects it and blocks access to the article by requiring subscription or payment.

2. Select and copy large amount of text. Original selection on the page automatically gets deselected. Paste elsewhere to realize only partial content was actually copied along with a "Read more at" link to the article.

### Versions

- Browser/version: Firefox 65.0.1
- uBlock Origin version: 1.18.4

### Settings

Annoyances filter

**Comment by stephenhawk8054** [comment]
There's an incorrect blocking now with the site.

URL: `https://www.bloombergquint.com/`

Expect:

![image](https://user-images.githubusercontent.com/66517106/140631160-3d35d219-de26-4f54-8456-9989c790bcf7.png)

Issue:

![image](https://user-images.githubusercontent.com/66517106/140631178-4c8b6c2b-fc7d-4548-abb2-c9be7eecb25c.png)

Looks like blocking this script causes the issue:

`https://cdn.cxense.com/cx.js`

Firefox 94.0.1, ublock 1.38.6 default

Proposed filter:

`@@||cdn.cxense.com/cx.js$script,domain=bloombergquint.com`
