### ISSUE TITLE
Vev.io

### ISSUE THREAD

**Issue by ahoura** [uBlockOrigin/uAssets#4974]
### URL(s) where the issue occurs

`https://vev.io/6ko92j45exrp`

### Describe the issue

It seems that due to #4653 vev.io can no longer load videos. the loader appears indefinitely on the player. the initial state is needed for the application to start and your recent rule has made this impossible.

### Versions

- Browser/version: Chrome/72
- uBlock Origin version: 1.18.4

### Notes

console shows the following error:

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' * blob: data:". Either the 'unsafe-inline' keyword, a hash ('sha256-bifp/i8Q6D9SjEylTyqa6ozLE5fxWIuQBcyi5QxaCCQ='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by okiehsch** [comment]
Is your example link just a 10 seconds long bank video?

**Comment by ahoura** [comment]
yea indeed its a blank 10 sec video

**Comment by okiehsch** [comment]
OK, I was just curious if something was wrong on my end.

**Comment by ghajini** [comment]
Antiadblock for 1St time visit on Firefox android
`https://vev.io/6ko92j45exrp`

**Comment by KiLL4FuNK** [comment]
Anti adblock

`https://vev.io/6ko92j45exrp`

**Comment by JobcenterTycoon** [comment]
Anti Adblock

`https://vev.red/j0omnj9kd73m`

**Comment by ghajini** [comment]
Antiadblock

Firefox android stable

`https://vev.io/v0oeq6ymq0o6`

Screenshot=

`https://prnt.sc/phkj7l`

**Comment by mapx-** [comment]
I cannot reproduce, however try:
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=vev.io`

**Comment by ghajini** [comment]
Issue not on desktop browsers

View page source

`https://pastebin.com/r2DMhQPk`

**Comment by ghajini** [comment]
Doesn't work

**Comment by ghajini** [comment]
Also offtopic
`||popunders.bid^$third-party`
`||nhpfvdlbjg.com^$third-party`

present in both easylist/ublock filters

**Comment by mapx-** [comment]
I tested the link using an android device (FF + uBo) => no issue, no anti adb stuff

**Comment by ghajini** [comment]
Ohk don't know why iam getting adblock detection. ....
