### ISSUE TITLE
rfi.fr

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#4984]
### URL(s) where the issue occurs

`http://ha.rfi.fr/`

`http://en.rfi.fr/`

### Describe the issue

A large fixed header. Suggested solution: 

`rfi.fr##header:style(position:static !important;)`

### Versions

- Browser/version: 1.18.4
- uBlock Origin version: 65.0.1 

### Settings

+Annoyances

**Comment by krystian3w** [comment]
need better CSS #7072

**Comment by krystian3w** [comment]
`rfi.fr##body.u-header-sticky .o-header:style(position: absolute !important;)`
