### ISSUE TITLE
instagram.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#4985]
### URL(s) where the issue occurs

`https://www.instagram.com/europeanspaceagency/`

### Describe the issue

Large bar at the bottom asking you to create an account. Suggested solution:

`instagram.com##div[style="width: 100%;"]:has(button:has(>span[aria-label="Close"]))`

### Versions

- Browser/version: 1.18.4
- uBlock Origin version: 65.0.1 

### Settings

+Annoyances

**Comment by yourduskquibbles** [comment]
`instagram.com##button:has(>span[aria-label="Close"]):xpath(..)` removes close button on the followers/following popup modal when user is logged in and the complementary filter added from #5030 `instagram.com##.ZUqME:has(a[href^="/accounts/emailsignup/"])` still removes the large bar asking to create account.

Found this issue while working on `https://old.reddit.com/r/uBlockOrigin/comments/dimzi2/how_to_block_login_pop_up_on_instagram/`
