### ISSUE TITLE
animeindo.*

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#4986]
### URL(s) where the issue occurs

`http://animeindo.moe/hora-mimi-ga-mieteru-yo-season-2-episode-01.html`

### Describe the issue

Popup ads

### Versions

- Browser/version: Firefox android  65
- uBlock Origin version: 1.18.4

### Settings

- uBO's default settings

**Comment by lain566** [comment]
Anti-adblock warning appears, when you click on `Download` to get the download links.
<details><summary>Screenshots</summary>

![7a95f448-33a7-4b1c-9358-0e07d632027d](https://user-images.githubusercontent.com/27441315/53305532-ddd2e280-3882-11e9-8b58-75a487ce6425.png)

![e4715a4a-cdef-49c6-8470-06cefac8c989](https://user-images.githubusercontent.com/27441315/53305545-fcd17480-3882-11e9-9c1c-b72b588008b7.png)

![6a514fda-01fe-4099-86d2-76ef47069501](https://user-images.githubusercontent.com/27441315/53305555-2e4a4000-3883-11e9-83a7-8e7f56f61df2.png)
</details>
