### ISSUE TITLE
mobile.twitter.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#4987]
### URL(s) where the issue occurs

`https://mobile.twitter.com/gorhill`

### Describe the issue

"Get the most out of Twitter" annoyance on mobile devices. The Adguard lists cannot block it: https://github.com/AdguardTeam/AdguardFilters/issues/30008 .

### Screenshot(s)

![twitter](https://user-images.githubusercontent.com/35470489/53241415-633a7500-3680-11e9-8b7c-8f1a0a5c306b.png)

### Versions

uBlock Origin 1.18.4
Firefox 65 for Android

### Settings
+Adguard lists, uBlock Annoyances

**Comment by mapx-** [comment]
test
`mobile.twitter.com##span:has-text(/get the most/i):xpath(../../../../../..)`

**Comment by adranger** [comment]
It hides that element, but locks the scrolling both on my tablet and on the desktop version of Firefox with the "Responsive Design Mode" set to use `Galaxy S9` as its user-agent.

**Comment by mapx-** [comment]
add also
`mobile.twitter.com##body:style(overflow: auto !important;)`

**Comment by krystian3w** [comment]
Fixed in nordic list "🚪 Browse websites without logging in":

https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt

**Comment by adranger** [comment]
@mapx- your combo works.

**Comment by krystian3w** [comment]
Works also in Mobile Firefox / Yandex (uBO dev / Nano Adblocker:

```
mobile.twitter.com##body:style(overflow-y: visible !important; overscroll-behaviour-y: inherit !important)
!                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

:question:

**Comment by krystian3w** [comment]
No breakage this now mobile twitter?

**Comment by adranger** [comment]
@krystian3w I'm getting "Don’t miss what’s happening" overlays again with this user agent: `Mozilla/5.0 (Android 7.1.2; Tablet; rv:67.0) Gecko/67.0 Firefox/67.0`. Open some Twitter profile and keep scrolling up and down to see if you get it too.

![Screenshot](https://user-images.githubusercontent.com/35470489/61390959-1dca4e80-a892-11e9-85a3-c056f46da547.png)

**Comment by krystian3w** [comment]
OK.

This is new text in span.

---

bug "breaking" found yesterday:

`!mobile.twitter.com#?##react-root > div > div > div > main > div > div > div:-abp-contains(cookie)` 

cut too matach elements so disabled.

**Comment by krystian3w** [comment]
Latest `:nth-ancestor(6)` = `:xpath(../../../../../..)`?

**Comment by yourduskquibbles** [comment]
@adranger & @krystian3w can you test `mobile.twitter.com##div[tabindex="0"]:has-text(Don’t miss what’s happening)` ?

This kills the overlay for me and only shows as 1 matching element when I use it when the overlay signup wall is visible but I don't use twitter enough to know if the site is fully functional after adding.

**Comment by adranger** [comment]
@yourduskquibbles 

Now instead of an overlay, it shows me the same bar as in the original post. Most people use Twitter in their own languages, so a filter based on a text string wouldn't cover everyone.  Anyway, I don't use the site either.

**Comment by yourduskquibbles** [comment]
> Most people use Twitter in their own languages, so a filter based on a text string wouldn't cover everyone. 

@adranger Good point, makes that not a great solution.

New filter to test:
`mobile.twitter.com##div[tabindex="0"]:matches-css(position:fixed)`
This filter works for me and only targets 1 element and doesn't depend on the text string but the fact the overlay is using the position:fixed CSS attribute. Does this kill the bar from the original post for you? I can't recreate that bar only the full overlay so if it doesn't work, are you able to provide a screenshot of the Dev Tools inspector with the elements expanded?

**Comment by krystian3w** [comment]
This works, we can detect maybe blue ✖️ by:

```
##div[tabindex="0"]:has(div[style="margin-left: calc(0.75em - 15.5px);"]):matches-css(position:fixed)
```

if margin-left is stable.

**Comment by yourduskquibbles** [comment]
@krystian3w Are you able to test filter 
`mobile.twitter.com##div[tabindex="0"]:matches-css(position:fixed):has([href="/signup"])` 

This filter should remove the signup modal on page scroll down and not break the image expand from issue #6025. Expand image functionality should be testable using `https://mobile.twitter.com/KateAronoff/status/1156564030900834306`

I believe the addition of `:has([href="/signup"])` to the filter should work for users from all languages/regions since URL `"/signup"` should always be in English even if user language is not English. Since I think your language default is not English would be good if you were able to confirm this is true.

@llacb47 are you also able to test that this filter doesn't break any obvious `mobile.twitter.com` site function for you?

**Comment by krystian3w** [comment]
On real android popup promote app from iOS (no support avanced procedural cosmetic filtering in any AdBlocker) / Google Play Store:

![obraz](https://user-images.githubusercontent.com/35370833/62559064-821d7400-b87a-11e9-93b8-bbc942498eb4.png) |
--- |

```
##div[tabindex="0"]:matches-css(position: fixed):matches-css(min-height: 165px):not(:has([href="/signup"]))
```

**Comment by gwarser** [comment]
This prevent messages to load on scroll:

    mobile.twitter.com##body:style(overflow: auto !important; margin: 0 !important;)

@yourduskquibbles what it was doing?

**Comment by gwarser** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/kfqzmh/problem_on_androidfirefox_68110/

**Comment by bug-rules** [comment]
These is for recover scrolling home page feeds.

@Yuki2718  / @gwarser / @yourduskquibbles  test these options:

`overflow: visible !important`
`overflow: scroll !important`
`overflow: unset !important`
`overflow: revert !important`
`overflow: initial !important`
`overflow: inherit !important`

if all break, maybe guilty is `margin: 0 !important;`  or we should use `:remove()` in procedural filters:

https://github.com/uBlockOrigin/uAssets/blob/cc9d81fc093d38fb7168917b8875dc6ccb4eb5ba/filters/annoyances.txt#L1531-L1532

**Comment by gwarser** [comment]
Removing `margin: 0 !important;` from filter does not help.

Tested on `https://mobile.twitter.com/gorhill`

**Comment by bug-rules** [comment]
So needed test other options to recover scroll when is locked for pop-ups "sing up" / "app promotion".

**Comment by gwarser** [comment]
App and cookie dialogs, small on bottom, are hidden and everything seems working.

**Comment by yourduskquibbles** [comment]
> App and cookie dialogs, small on bottom, are hidden and everything seems working.

Tested and seems working for me on both `twitter.com` and `mobile.twitter.com` after @gwarser removing the bad filter `mobile.twitter.com##body:style(overflow: auto !important; margin: 0 !important;)` with just default uBO lists + `uBlock filters – Annoyances` ONLY.

It might have been a filter to bring back scrolling on an old mobile twitter site design as also isn't a filter I have in `Web Annoyances` either. Sorry was away not able to respond 4 days ago.
