### ISSUE TITLE
hdfull.me

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#4988]
### URL(s) where the issue occurs

`https://hdfull.me/serie/dragonball-super-2015/temporada-1/episodio-129`

### Describe the issue

There's a popup when clicked anywhere on the page.

### Versions

- Browser/version: Chrome 72
- uBlock Origin version: 1.18.4

### Settings

- Default settings.

### Notes

Click on streamplay.to and try to play the video, a popup will open.
<details><summary>Screenshot</summary>

![5425104f-178b-4091-9d15-0f9e7db54394](https://user-images.githubusercontent.com/27441315/53275272-a76a5b80-36fa-11e9-83ca-61999f404009.png)
</details>

---------------------------------------------------

Click on flix555.com, ad is shown when the video is paused.

<details><summary>Screenshot</summary>

![b7a72a45-b2e8-4bdc-8ce2-9cbeb1899f3c](https://user-images.githubusercontent.com/27441315/53275419-5a3ab980-36fb-11e9-8678-3199fea5fc19.png)
</details>

--------------------------------------------------

Gamovideo seems to be broken, if you go to the external link, there are popups when trying to play the video. `http://gamovideo.com/885whdif033r`

<details><summary>Screenshot</summary>

![73ff32bc-ee7e-4947-8df4-a9bb0c047257](https://user-images.githubusercontent.com/27441315/53275855-029d4d80-36fd-11e9-9733-b515e8d379c2.png)
</details>

**Comment by okiehsch** [comment]
- I get an "error loading media" message with all `flix555.com` videos, so you will have to tell me how to block any ad shown if you pause the video.
Go to `https://flix555.com/embed-t4hheuioufrv-920x360.html` and use the picker to find a working filter.

- I can't reproduce any popups at `http://gamovideo.com/885whdif033r`

**Comment by lain566** [comment]
@okiehsch if I use a VPN from Germany, for example, I can't reproduce any popups at gamovideo neither,
This filter blocks popups for me
`gamovideo.com##+js(abort-on-property-read.js, canRunAds)`

----------------------------------------------

This is the cosmetic filter that I get in flix555.com
`##.flix_fadein`

![ca3fefaf-7f0d-4abc-9c21-e281d622f5e1](https://user-images.githubusercontent.com/27441315/53281436-8f113580-3728-11e9-94a2-6792dfce84ad.png)

**Comment by okiehsch** [comment]
Well, with what location can I reproduce popups?

I tried US, spanish, brazilian and argentinian.

**Comment by lain566** [comment]
I can't reproduce any popups in any location, it's weird

**Comment by okiehsch** [comment]
So, this can be closed?
If you notice any popups in the future you can reopen.

**Comment by lain566** [comment]
Yes, close this issue

**Comment by lain566** [comment]
@okiehsch Can't you do anything with the popup of streamplay.to, right?

**Comment by okiehsch** [comment]
The popups are fixed on my end by https://github.com/uBlockOrigin/uAssets/commit/bc2f7dfcd003dd14005031c7f3a3c4bf28646ffd
````
! https://github.com/uBlockOrigin/uAssets/issues/4988
hdfull.me##+js(set-constant.js, n4bb.a3, noopFunc)
||ghlates.info^$p
||merylaural.info^$p
||popmonetizer.net^$3p
||revrtb.net^$3p
````
on my end, though can see two typos which I will fix.

**Comment by lain566** [comment]
I mean when you click on the streamplay.to player, a popup opens

**Comment by okiehsch** [comment]
None of the streamplay.to options work on my end.
All of them get
![image](https://user-images.githubusercontent.com/16838044/53283281-2b950100-3744-11e9-9cb5-77aaa4d38d9c.png)

**Comment by okiehsch** [comment]
If I click "Enlace externo" I can play the video at `https://streamp1ay.me/d4s92ffztpft`.
![unbenannt](https://user-images.githubusercontent.com/16838044/53283366-a6125080-3745-11e9-8bc7-ab5e6142f265.JPG)

I can't reproduce any popups at that site.

**Comment by lain566** [comment]
@okiehsch You can use a VPN from France, that sure works.

Yeah, only the popup opens in the embedded player.

**Comment by okiehsch** [comment]
Ok, I can reproduce, the problem is that defusing that popup without breaking the player is rather difficult. I don't see a fix at the moment.
For reference the popup is triggered by `https://streamp1ay.me/js/jquery-1.1.8-min.js` look for `c0ZZ.P0=function` to find the part responsible for the popup.
Aborting it will break the whole script and break video-playback.

`||eontent.streamplay.to^$popup` will close the popup immediately.

**Comment by mapx-** [comment]
I can go only with
```
||eontent.streamplay.to^$badfilter
|about:blank|$popup,domain=hdfull.me
```
(needing to click to get the real play button)

**Comment by mapx-** [comment]
I see this inline script

```
function getCalcReferrer() {
    return '' || document.referrer || (location.ancestorOrigins ? location.ancestorOrigins.item(location.ancestorOrigins.length-1) : ''); 
}
nrf = getCalcReferrer();
if(nrf) $.cookie('ref_yro', nrf, {expires: 5});
function getNrf(enc) { var r = getCalcReferrer(); return enc?encodeURIComponent(r):r;  };
function addBannerToContainer(source, bid, tout) {
    bid = bid || 'pst'; tout = tout || 7000;
    $('<iframe>', {src : source, width : '300', height : '250', scrolling : 'no', id : bid, sandbox : 'allow-scripts allow-same-origin', style : 'display:none'}).appendTo('body');
    setTimeout(function() {
        $('#' + bid).remove();
    }, tout);
};

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

 ga('create', 'UA-70084327-1', 'auto', {
     'alwaysSendReferrer' : true
 });
 ga('set', 'referrer', getNrf());
 ga('send', 'pageview');
 

(function(b){
	
	var cpop = '//eontent.streamplay.to/apv.hh?n=&zoneid=26&direct=1';  
	addBannerToContainer('//eontent.streamplay.to/apv.hh?direct=1&n=&zoneid=31', 'ac1', 15000);
	addBannerToContainer('//eontent.streamplay.to/apv.hh?direct=1&n=&zoneid=32', 'ac2', 20000);
	addBannerToContainer('//eontent.streamplay.to/apv.hh?direct=1&n=&zoneid=33', 'ac3', 20000);
	
	letgo = function() {
		var parts = /^.*\w{12}-(\d+)x(\d+).*$/.exec(b.self.location.pathname);
        if(parts) {
	        var size = parts.slice(1);
	        var src = self.location.pathname.replace(/\/embed-/, '/player-');
        } else {
        	var size = [Math.max(document.documentElement.clientWidth, window.innerWidth || 0),Math.max(document.documentElement.clientHeight, window.innerHeight || 0)];
        	var src = self.location.pathname.replace(/\/embed\-(\w{12})/, '/player-$1-'+size[0]+'x'+size[1]);
        }
        src = 'https://streamp1ay.me' + src; 
        b.location.assign(src);
	};
	
	delayGo = function() {
		setTimeout(letgo, 1000);
	}
	
	b.puOverlay(cpop, null, delayGo, false); /// pfu = true
	
})(window);
```

**Comment by okiehsch** [comment]
I would not `badfilter` `eontent.streamplay.to`, if you watch the embedded stream at the source that filter is needed.

**Comment by mapx-** [comment]
without badfilter I get no playable button

**Comment by okiehsch** [comment]
Hm, works fine on my end after clicking the video.

**Comment by mapx-** [comment]
testing in FF right now

**Comment by mapx-** [comment]
well, using the filters above at least the popup is closed and the video can be played

**Comment by mapx-** [comment]
no, ...you're right, no needing for badfilter

**Comment by okiehsch** [comment]
Well, I only tested with Chromium, testing with Firefox right now the video is indeed broken on my end.

**Comment by mapx-** [comment]
hmm, I'll test again in FF, clearing cookies

**Comment by mapx-** [comment]
it's ok in FF too for me, click => popup window => closed by about-blank filter => after a while the real play button appears ad the video is running fine

**Comment by okiehsch** [comment]
OK.

**Comment by lain566** [comment]
`|about:blank|$popup,domain=hdfull.me` works for me on chrome

@mapx- Can you reproduce popups on gamovideo?
`http://gamovideo.com/885whdif033r`

**Comment by mapx-** [comment]
no popup on `gamovideo` FF / chrome on `http://gamovideo.com/885whdif033r`

**Comment by lain566** [comment]
Ok

**Comment by ghajini** [comment]
i can reproduce popups on gamovideo
![screenshot 121](https://user-images.githubusercontent.com/20338483/53289162-74869d00-37b8-11e9-97c8-4df36d8a7cce.png)
filters over here by mapx- work
`https://github.com/uBlockOrigin/uAssets/issues/4572#issuecomment-452403485`

**Comment by lain566** [comment]
@mapx- There's a popup again on gamovideo
`http://gamovideo.com/zksp07mtr2d8`

Can you see this request blocked?
`http://gamovideo.com/js/ads.js`

![Anotación 2019](https://user-images.githubusercontent.com/27441315/55674187-45804280-58b1-11e9-9f98-ce2d67a6922d.png)

**Comment by mapx-** [comment]
I get no popup and see no `/js/ads` request

**Comment by lain566** [comment]
If I block this request, I don't get the popup, take a look.
`http://gamovideo.com/ades.js`

**Comment by mapx-** [comment]
Does this work ? (I see no such script)
`gamovideo.com##+js(set-constant.js, doOpen, noopFunc)`

**Comment by lain566** [comment]
It does not work

**Comment by lain566** [comment]
@mapx- This works.
`gamovideo.com##+js(set-constant.js, canRunAds, noopFunc)`

**Comment by okiehsch** [comment]
Weird, I tried a spanish IP and like mapx- I don't see that request and there is no such request in the source.

**Comment by lain566** [comment]
@okiehsch If I use a vpn from Spain, I will not see that request either, My real IP is from Spain

**Comment by okiehsch** [comment]
I beat you to it by a few seconds 😉

**Comment by mapx-** [comment]
:)

**Comment by KiLL4FuNK** [comment]
popup

`https://hdfull.me/serie/bia/temporada-1/episodio-21`

**Comment by spodermenpls** [comment]
Since `streamp1ay.me` was already mentioned in this thread, I'll report it here: there's a new, annoying pop-up/pop-under on this site, that deploys when you click somewhere on the page initially, and also periodically later: `https://streamp1ay.me/0teg6ppfbrtp` (as an example). @okiehsch

**Comment by okiehsch** [comment]
`streamp1ay.*##+js(aopr, puOverlay)`
works for me, does that also fix the "also periodically later" part?

**Comment by mapx-** [comment]
or
`streamp1ay.me##+js(acis, $, test)`

**Comment by okiehsch** [comment]
Hm, yes aborting the whole inline-script might be better.

**Comment by spodermenpls** [comment]
@okiehsch Yes, that also fixed the later occuring pop-ups, as far as I can tell. Thanks for the quick fix!
