### ISSUE TITLE
Facebook/Messenger broken because hash contans '_Ad'

### ISSUE THREAD

**Issue by hyperknot** [uBlockOrigin/uAssets#499]
### URL(s) where the issue occurs
https://www.facebook.com/messages/t/
https://www.messenger.com/t/

### Describe the issue
Messenger pages are totally blank / broken

### Screenshot(s)
Totally blank page on messenger.com, no point of screenshot. Facebook only contains header.

### Versions

- Browser/version: Chrome 59.0.3071.115
- uBlock Origin version: 1.13.2

### Notes
From the logger: todays random hash for an important Facebook Messenger JS file is `sxyhGVt_Ad6.js`, which gets blocked by EasyList. Full URL is https://static.xx.fbcdn.net/rsrc.php/v3/y9/r/sxyhGVt_Ad6.js

**Comment by ghajini** [comment]
This is fixed by easylist recently

**Comment by gorhill** [comment]
This was fixed hours ago: <https://github.com/jspenguin2017/uBlockProtector/issues/349>.
