### ISSUE TITLE
gogoanime.cloud

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#4991]
URL(s) where the issue occurs

`https://gogoanime.cloud/watch/dungeon-ni-deai-wo-motomeru-no-wa-machigatteiru-darou-ka-2nd-season.15xw/n686mk`

Describe the issue

video player doesn't start

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 72 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.18.2

Settings

Default

**Comment by okiehsch** [comment]
Looks like a site issue to me, the `Rapidvideo` and `MyCloud` option don't work even if I disable `uBO-filters`.

`Mp4upload` and  `OpenLoad` work fine.

**Comment by KonoromiHimaries** [comment]
popup 5-10sec after joining `https://gogoanime.cloud/gogoanime`

**Comment by ghajini** [comment]
`https://gogoanime.cloud/watch/lupin-iii-goodbye-partner-sub`
antiadblock.....
![Screenshot (11)](https://user-images.githubusercontent.com/20338483/58322393-76efa600-7e3e-11e9-94ed-d8addfdc9292.png)
