### ISSUE TITLE
www.hotpornfile.org ad box in bottom right [NSFW]

### ISSUE THREAD

**Issue by bobsage123** [uBlockOrigin/uAssets#4992]
There is an ad box that appears in the bottom right after clicking on any of the videos on `https://www.hotpornfile.org`.

Specific link example - `https://www.hotpornfile.org/whiteghetto-19-02-19-allison-lane-xxx-1080p-mp4-ktr/509678`

It might take 10-20 seconds before it appears. If it does not do a refresh or try another video.

Picture of box - `https://i.imgur.com/L4vzA0e.png`

I would appreciate a fix.

**Comment by okiehsch** [comment]
You do realize that hotlinking to sites with adullt content is not a good idea?

**Comment by bobsage123** [comment]
Yes, my mistake, sorry.

**Comment by bobsage123** [comment]
Thanks for fixing. How long should it take for this to appear in ublock filters after a cache purge and redownload?

**Comment by okiehsch** [comment]
If you manually update you should get it 5 minutes after the commit.

**Comment by bobsage123** [comment]
Thank you I see it now

**Comment by bobsage123** [comment]
Hello, I think they may have changed something. A popup in the bottom right is appearing again. You might need to refresh the page a few times and clear cookies before it pops up.

NSFW:
Pop up example: `https://i.imgur.com/y4MUpJb.png`

Page example: `https://www.hotpornfile.org/swallowed-19-03-24-brooklyn-gray-xxx-1080p-mp4-ktr/519176`

**Comment by bobsage123** [comment]
Damn this page is annoying - ads back on the bottom. Seems the site owner is monitoring the ublock filter and just making tweaks. 

`https://www.hotpornfile.org/brazzersexxtra-16-08-30-amara-romani-our-babysitters-butt-part-2-xxx-1080p-mp4-ktr/294667`
