### ISSUE TITLE
Tinder.com - Anti-adblock script

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uAssets#4996]
### Affected site:
`https://tinder.com/`

### Issue:
Anti-adblock script.

### Screenshot:

![filterissue-tinder](https://user-images.githubusercontent.com/9382674/53288956-cc5cde00-378f-11e9-96f1-1445b9571192.jpg)

### How to reproduce:
Click on the "LOG IN" or "SIGN UP" button, to open the "GET STARTED" window.
(You might have to close and re-open it, for the warning to trigger)

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.4.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.8 (XUL)

**Comment by Jap2-0** [comment]
This is caused by Fanboy's annoyance list, so technically it may not be within the scope of this list, but I'll see what I can come up with.

**Comment by Jap2-0** [comment]
It looks like `tinder.com#@#.button--facebook` works fine as a simple solution (although there may be a better solution in javascript).

**Comment by THEtomaso** [comment]
> It looks like `tinder.com#@#.button--facebook` works fine as a simple solution

No, this depends on which filters you're using.
There are a lot more Facebook elements being blocked on that site, by various social media filters.
Looks like every Facebook element needs to be whitelisted, which really isn't a very good solution.

**Comment by THEtomaso** [comment]
> This is caused by Fanboy's annoyance list

Not really.
The issue seems to be caused by blocking Facebook, which is done by a huge amount of different social media filters.
If you allow all the Facebook crap, then the adblock warning doesn't appear!
But needless to say, a different approach would be preferable.

**Comment by Jap2-0** [comment]
What lists are you using?  I'm using two dozen or so, including multiple social media filters, and whitelisting that single element, blocked only by fanboy's list, fixes it for me.
And yes, but I've looked into the javascript and I'm going to say that it will need someone a bit more knowledgeable than I.

**Comment by Jap2-0** [comment]
That disables all cosmetic filtering, right?
It does appear that all their detection is based around that.

**Comment by okiehsch** [comment]
`@@||tinder.com^$generichide` works even if I block all facebook requests.

**Comment by THEtomaso** [comment]
You're right, Jap2-0,I take back my previous statement.
The issue indeed seems to be caused by **Fanboy's** filters.
The other filter which was causing problems is my own, which also contains a lot of Facebook rules. :)

**Comment by mapx-** [comment]
@ryanbr

**Comment by okiehsch** [comment]
It disables all generic cosmetic filters. Specific ones will still work.


Off-topic: There seems to be a glitch with github on my end.
![image](https://user-images.githubusercontent.com/16838044/53290957-d096f480-37ab-11e9-8215-f255c9b25e29.png)

My comment will happen in the future. ;)

**Comment by Jap2-0** [comment]
Nah, it's entirely possible that others block it too.  I'd give you a better solution, but I'm not much of an expert in javascript.

**Comment by THEtomaso** [comment]
> There seems to be a glitch with github on my end.

Yeah, I encountered the very same thing.

**Comment by THEtomaso** [comment]
Reference (updated report):
https://github.com/ryanbr/fanboy-adblock/issues/950/
