### ISSUE TITLE
elii.cc

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#4999]
### URL(s) where the issue occurs

`[http://elii.cc/dssxe6]`

### Describe the issue

[popunder.]

### Versions

- Browser/version: [chrome v72]
- uBlock Origin version: [1.18.4]

### Settings

- [default]

**Comment by dumbusernameidk** [comment]
anti-adblock of some sort. loading the page redirects you to a "please disable ublock" page. if you disable it and reload the link the site loads properly.

**Comment by dumbusernameidk** [comment]
@okiehsch 

looks like that disable ublock page is gone so you can remove that script since it apparently conflicts with the download timer. it wont count down unless you allow 1p scripts.

**Comment by smed79** [comment]
This filter `||elil.cc/rizie.js$important,first-party,script` break the countdown.
==> clear cookies and cache before testing.

**Comment by dumbusernameidk** [comment]
popunder when clicking the continue to download button.

**Comment by dumbusernameidk** [comment]
Looks like it's back again there seems to be some iframe loaded onto the bottom section of the page. If i block it bottom section goes away, but trying to click on it or the continue button results in a popup. the popup is always `http://data.elil.cc/p.html`. can you reproduce? @okiehsch

**Comment by okiehsch** [comment]
Does
`|about:blank|$popup,domain=elil.cc`
work for you?

**Comment by dumbusernameidk** [comment]
yeah that works. wondering if it's at all possible to use a scriptlet. the only way i can stop the popups permanently is not allowing inline scripts to run. but doing that prevents the timer from counting down.

**Comment by okiehsch** [comment]
I don't see a working scriptlet that would not also break the timer, the site bundles it all in one script.
`http://elil.cc/rriz.js`.

**Comment by mapx-** [comment]
I get no popup / popunder  FF / chrome, very strange

**Comment by okiehsch** [comment]
If you search `http://elil.cc/rriz.js` for `latoniankeen` do you get a hit?
That is causing the about:blank popup.

**Comment by mapx-** [comment]
yeah, 4 `latoniankeen`

**Comment by okiehsch** [comment]
Well, then I can't explain why you don't see any popups I get them every time I don't even need to delete cookies to reproduce.

**Comment by dumbusernameidk** [comment]
i think it's dependent on where you click try clicking on the bottom section or anywhere near the continue button. see if reloading the page a few times does it.

**Comment by JobcenterTycoon** [comment]
I get Popups again
