### ISSUE TITLE
uBlock filters new version doesn't update

### ISSUE THREAD

**Issue by zymase** [uBlockOrigin/uAssets#5]
uBlock Origin 1.6.8 / Firefox 45.0.1 64-BIT / Windows 7 64-BIT

Hi,

I've just noticed that a new version was available for 3rd-party filters / uBlock filters.
Clicking as usual on _Update now_ proceeds with the update but once finished the update appears as still available.

Auto-update filter lists is disabled - Above mentioned concerns only uBlock filters (no other update available showing) : _uBlock filters‎ : 415 used out of 417 new version available_

**Comment by gorhill** [comment]
Can you try to force a reload of the dashboard page, and try to click the _"Update now"_ button again?

**Comment by gorhill** [comment]
Never mind, it was my fault, see #4. Should work now.

**Comment by zymase** [comment]
Just updated uBlock filters successfully.
For what's it's worth, a first try after reading your comment above, gorhill, proved unsuccessful. I restarted Firefox and then uBlock filters updated successfully
Thanks (for all of us of course).
