### ISSUE TITLE
About uBlockO settings backup file

### ISSUE THREAD

**Issue by zymase** [uBlockOrigin/uAssets#50]
Hi,

I've just noticed a parameter in the backup file of my uBlockO (my-ublock-backup_[date].txt) which puzzles me because I don't understand its relationship to my uBlockO actual settings:

userSettings : "experimentalEnabled": false

If this corresponds to  3rd-party filters, uBlock filters – Experimental‎ : it is checked and updated : why _false_ then?
Otherwise, to what does this _experimentalEnabled_ correspond to? Unable to find any other experimental feature in my uBlockO Dashboard settings.

Thanks

**Comment by gorhill** [comment]
There used to be a checkbox in the _Settings_ pane to enable/disable experimental features -- this was removed when the _local mirroring_ experimental feature was dropped. I will remove _experimentalEnabled_, [it's no longer used](https://github.com/gorhill/uBlock/search?utf8=%E2%9C%93&q=experimentalEnabled).
