### ISSUE TITLE
Radar Sweep Block

### ISSUE THREAD

**Issue by pjpreilly** [uBlockOrigin/uAssets#5005]
Can anybody help me block the radar sweep on [THIS](https://www.nbcphiladelphia.com/weather/maps/) page which consumes my processor & turns my laptop into a toaster? It happens in Storm Tracker 4 mode which is activated by zooming in(+). TIA

**Comment by uBlockIsBest** [comment]
`widgets-blue.media.weather.com$script` will block the radar

**Comment by mapx-** [comment]
well, your filter is blocking all the map .. OP wants to block only the animated radar on map I guess

**Comment by pjpreilly** [comment]
Only want to block the circular "sweep" which seems to be a graphics hog.

**Comment by mapx-** [comment]
I'll close the issue as it's not even an annoyance.... However I see no easy fix
