### ISSUE TITLE
peliculasgolden.com

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#5008]
### URL(s) where the issue occurs

`https://www.peliculasgolden.com/`

### Describe the issue

Popup
Steps to reproduce:
- Go to `https://www.peliculasgolden.com/` and wait for the notification box to appear. 
- Refresh page
- And click on anywhere on the page.

### Versions

- Browser/version: Chrome 72
- uBlock Origin version: 1.18.4

### Settings

- Default settings.

**Comment by okiehsch** [comment]
I can't reproduce any popups.
I can reproduce the notificatio which can be blocked by
`||peliculasgolden.com/sw.js$script,1p`
does this fix your issue?

**Comment by lain566** [comment]
Yes, that works.
