### ISSUE TITLE
Youtube Videos (googlevideo.com) blocked on Firefox

### ISSUE THREAD

**Issue by itworksjbo** [uBlockOrigin/uAssets#501]
### URL(s) where the issue occurs

Any Youtube Video

### Describe the issue

Running uBlock on my Desktop (suprisingly enough works perfectly fine on my laptop) it blocks videos on Youtube. Using Chromium with uBlock worked like a charm. Having a look into the logs, I noticed that for some reason googlevideo.com was being blocked.

### Screenshot(s)
Screenshots: Logfiles from Firefox and Chromium.

![screenshot_20170708_023451](https://user-images.githubusercontent.com/12223583/27981110-2fabf3e4-6387-11e7-8ca6-357b6d7c9e60.png)
![screenshot_20170708_023549](https://user-images.githubusercontent.com/12223583/27981111-2fb47640-6387-11e7-996b-cd3f2042d910.png)

### Versions

- Browser/version: 54.0.1 (64-bit) Mozilla Firefox for Arch Linux archlinux - 1.0
- uBlock Origin version: 1.13.4

### Settings

- default

### Notes

Manually unblocking googlevideo.com fixed the issue.

**Comment by okiehsch** [comment]
Force an update of `EasyList`, the filter causing your issue has been disabled https://github.com/easylist/easylist/commit/95229bebe6e20b39ce179ea4941ffbdde144325a

**Comment by itworksjbo** [comment]
Oh... thanks.
