### ISSUE TITLE
nypost.com recirculator bar removed erroneously by easylist

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#5012]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://nypost.com/2019/02/24/the-oscars-stage-this-year-strongly-resembles-donald-trumps-hair/`

### Describe the issue

Recirculator bar is erroneously removed by [easylist](https://easylist.to/easylist/easylist.txt) with filter `nypost.com,pagesix.com##.recirc`.

On nypost.com these aren't ads or sponsored articles from what I can tell, just links to other articles/content on nypost.com. 

As an aside, I don't even know if the filter is useful for pagesix.com as I couldn't find an article with a recirc bar on that domain.

### Screenshot(s)

![nypost](https://user-images.githubusercontent.com/22258847/53347544-4b185f00-38e7-11e9-9e76-29651a75e439.png)

### Versions

- Browser/version: Chrome Version 73.0.3683.46 (Official Build) beta (64-bit)
- uBlock Origin version: uBlock Origin  1.18.5b9 (Latest Dev Build)
- uBlock Origin Extra 2.80

### Settings

- Test profile with default settings and lists.

### Notes

Exclusion filter `nypost.com#@#.recirc` or `nypost.com,pagesix.com#@#.recirc` (if you want to override both domains) fixes the issue for me.

**Comment by mapx-** [comment]
I can reproduce the issue (for both sites ! ) only using a us ip (no such section for european ips)

**Comment by yourduskquibbles** [comment]
@mapx- With the override filter for `pagesix.com` the recirc doesn't appear for me unless I add `pagesix.com outbrain.com * allow` under My Rules or add the following static filters
```
@@||widgets.outbrain.com/outbrain.js?ver=1.0.0$script,domain=pagesix.com
@@||odb.outbrain.com/utils/get$script,domain=pagesix.com
``` 
Were you getting it to appear as the screenshot below without making that change from the default filters/settings?

![pagesix](https://user-images.githubusercontent.com/22258847/53378605-2e564880-3934-11e9-88d9-b5b51d9cf744.png)


Test site I used: `https://pagesix.com/2019/02/25/r-kelly-pays-100k-bond-needed-for-release/`

`nypost.com` seems fine for me without any other filters needed.

**Comment by yourduskquibbles** [comment]
@mapx- Any idea why the recirculator is loading fine on some pages of nypost.com but not others?

recirculator loads:
`https://nypost.com/2019/02/24/the-oscars-stage-this-year-strongly-resembles-donald-trumps-hair/` 

recirculator doesn't load: 
`https://nypost.com/2019/02/26/us-press-booted-from-vietnam-hotel-after-north-korean-officials-flipped-out/` 

Tested on both chrome and firefox test profiles, even adding nypost.com to filter below doesn't seem to get it to load on `https://nypost.com/2019/02/26/us-press-booted-from-vietnam-hotel-after-north-korean-officials-flipped-out/` - I have to disable uBO to get it to load and don't see anything obvious coming up for `outbrain` in the logger indicating why it would work fine on one page from same domain but not the other?

```
@@||widgets.outbrain.com/outbrain.js$script,domain=nypost.com,pagesix.com
@@||odb.outbrain.com/utils/get?url$script,domain=nypost.com,pagesix.com
```

**Comment by mapx-** [comment]
yeah, same filters, but your syntax above is wrong:

not `domain=nypost.com,pagesix.com`, but `domain=nypost.com|pagesix.com`

**Comment by yourduskquibbles** [comment]
> 
> 
> yeah, same filters, but your syntax above is wrong:
> 
> not `domain=nypost.com,pagesix.com`, but `domain=nypost.com|pagesix.com`

Thanks. Good to know I just created my own rabbit hole by forgetting the network filter syntax is different than cosmetic filter syntax and there isn't some other issue going on.

**Comment by stephenhawk8054** [comment]
@Yuki2718 Is the filter `nypost.com,pagesix.com##.recirc` in EL needed any more? Currently it causes same issue on uBOL.

**Comment by Yuki2718** [comment]
> Is the filter `nypost.com,pagesix.com##.recirc` in EL needed any more? Currently it causes same issue on uBOL.

[Removed](https://github.com/easylist/easylist/commit/16af488183ad65d5aec7b3d6dfffac726e5dbfaa)
