### ISSUE TITLE
skip.az [Anti-Adblock]

### ISSUE THREAD

**Issue by version365** [uBlockOrigin/uAssets#5014]
### URL(s) where the issue occurs

`https://skip.az/5CZL`

### Describe the issue

Anti-Adblock pop-up message..

### Screenshot(s)

https://i.imgur.com/ZcflLWt.png

### Versions

- Browser/version: Google Chrome 70
- uBlock Origin version: 1.18.4

**Comment by doio** [comment]
Doesn't seem to work anymore. 
Another link:
https://skip.az/QHb2

**Comment by mapx-** [comment]
still working for me
