### ISSUE TITLE
sdmy168.com (NSFW)

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#5015]
### URL(s) where the issue occurs

`http://m.sdmy168.com/index/5aWU6amwc29z.html`

### Describe the issue

Link redirects to porn. `sdmy168.com` and `m.sdmy168.com` do not however.

**Comment by mapx-** [comment]
The page redirects to `901209.com`

**Comment by terrorist96** [comment]
Redirects to different sites each time.
![smartselect_20190227-172559_chrome](https://user-images.githubusercontent.com/12802056/53527386-d4c95780-3ab4-11e9-81fc-dd8da30be490.jpg)

**Comment by okiehsch** [comment]
I get redirected to the same site every time.
![image](https://user-images.githubusercontent.com/16838044/53527664-e0824180-3ae7-11e9-9621-c7aabbaf8153.png)

**Comment by mapx-** [comment]
yeah, same here.

However, maybe we should block the domain

**Comment by okiehsch** [comment]
> Maybe we should block the domain

Why? I get no popups or any unwanted porn stuff in fact `901209.com` looks pretty much the same as `sdmy168.com`, though I can't speak the language so maybe there is a difference.

**Comment by mapx-** [comment]
just thinking the site was hacked

**Comment by mapx-** [comment]
@terrorist96  in the end we cannot reproduce multiple redirects, we get the same domain every single time.

**Comment by okiehsch** [comment]
The redirect is triggered by a first party-script I am trying to narrow it down.

**Comment by okiehsch** [comment]
Blocking `http://sdmy168.com/js/tujia.js` disables the redirection on my end.

**Comment by okiehsch** [comment]
I don't know what the point of that redirection is.

**Comment by mapx-** [comment]
- exactly, redirecting to the same cars page
- however `sdmy168.com` redirects to `http://www.901209.com/` with completely other content

**Comment by okiehsch** [comment]
We can block that script, but only the site  owner knows if the redirection is deliberate or if they have been hacked.

**Comment by mapx-** [comment]
for me  `sdmy168.com` redirects to different / random content (on `901209`)  on refreshing the page

**Comment by okiehsch** [comment]
@terrorist96 are your redirections fixed if you add
`||sdmy168.com/js/tujia.js$script,1p`
you have to bypass the cache one time for the filter to work.

**Comment by okiehsch** [comment]
> for me `sdmy168.com` redirects to different / random content (on `901209`) on refreshing the page

For me too but if I disable the redirection and refresh `sdmy168.com` the content on `sdmy168.com` also changes every time.

**Comment by okiehsch** [comment]
This is the page at `sdmy168`
![image](https://user-images.githubusercontent.com/16838044/53530215-71105000-3aef-11e9-9b35-0ff0d7e97614.png)

The page at `901209`
![image](https://user-images.githubusercontent.com/16838044/53530284-a3ba4880-3aef-11e9-8b5c-50f5b7402adb.png)

**Comment by terrorist96** [comment]
> @terrorist96 are your redirections fixed if you add
> `||sdmy168.com/js/tujia.js$script,1p`
> you have to bypass the cache one time for the filter to work.

Yes that works. I'm also now being redirected to 901209 (without that filter).

**Comment by mapx-** [comment]
for mobile they redirects to some crap using:
`http://www.901209.com/js/1.js`
