### ISSUE TITLE
clickrouter.com tracking on mailinator.com

### ISSUE THREAD

**Issue by billyinternet** [uBlockOrigin/uAssets#502]
### URL(s) where the issue occurs

`https://www.mailinator.com/inbox2.jsp?to=test#/#public_maildirdiv`

### Describe the issue

This inline script:

```
    <script type="text/javascript">
        function updateLinks(tree) {
            
            tree.find('a').each(function () {
                var href = $(this).attr('href');
                if (href && href.length > 0) {
                    if (href.indexOf('mailinator') > 0 || href.indexOf("clickrouter") > 0 || href == "/" ||
                            href.indexOf("stripe") > 0) {

                    } else {
                        //console.log(href);
                        href = escape(href);
                        href = "http://click1.clickrouter.com/redirect?token=a2258079c24c4c50a56b6b1ffb75d6e2&" +
                                "url=" + href;
                        $(this).attr('href', href);
                    }
                }
            });
            
        }

        
        var manyteam = false;
        

    </script>
```

Redirects all outbound urls to `http://click1.clickrouter.com/redirect` which is HTTP (even for HTTPS urls) and tracks every click.

Mailinator and ClickRouter are my by the same guy and 3rd party use of ClickRouter uses this script: `<script src='http://click1.clickrouter.com/js/cr.js?1'></script>` which I have submitted to EasyList. (EasyList doesn't like uBlock Origin only filters types)

### Versions

- Browser/version: Chrome/59.0.3071.115
- uBlock Origin version: 1.13.2

### Notes

I'm no expert but I think
```
mailinator.com##script:contains(clickrouter)
```

Would be the solution at least for Firefox.

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?f=62&t=37445
