### ISSUE TITLE
wetter.com

### ISSUE THREAD

**Issue by spodermenpls** [uBlockOrigin/uAssets#5023]
### URL(s) where the issue occurs

`https://www.wetter.com/`

### Describe the issue

The site deploys a useless cookie banner at the bottom of the side.

### Screenshot(s)

https://screenshotscdn.firefoxusercontent.com/images/d2b1ba7b-12e3-4704-ab5f-457824e4ae55.png

### Versions

- Browser/version: Firefox 65.0.1
- uBlock Origin version: 1.18.4

### Settings

[uBlock-settings.txt](https://github.com/uBlockOrigin/uAssets/files/2911231/uBlock-settings.txt)

### Notes

The existing Adguard Annoyances rule `##.cookieInfo:not(body):not(html)` (which works with Adguard) doesn't work with uBlock, is this a known issue with this type of syntax, or what's the reason behind it?

**Comment by dumbusernameidk** [comment]
enable fanboy's cookie list.

**Comment by spodermenpls** [comment]
@dumbusernameidk That makes no difference. 
I wonder why Adguard told me that the mentioned rule above blocks the cookie banner with their own extension, my homemade rule` www.wetter.com##.layout.portable-p-.p.cb-container` looks nothing like "cookieInfo"...

**Comment by dumbusernameidk** [comment]
wdym makes no difference? the rule in fanboy's cookie list `##div[class^="cookie-banner"]` blocks it just fine. Heck you can even do `wetter.com##.cookie-banner`. Either way both work just fanboy's cookie list works better since it blocks majority of these.

**Comment by mapx-** [comment]
yeah, no `cookieInfo` in that page, so its false alert

**Comment by spodermenpls** [comment]
@dumbusernameidk I mean that activating Fanboy's Cookie list doesn't block the banner, the "##.cookie-banner" rule works though. Could this correlate with me using Firefox and you a different one? Or what is wrong with my uBlock? 😲
I found a section in Adguard's Annoyance list that contains specific websites that get "##.cookie-banner" filtered out, so I'm gonna try to make someone over there add "wetter.com" to that line.

**Comment by dumbusernameidk** [comment]
I just tested it on firefox v65 ublock 1.18.4. So maybe something on your end? Make sure you didn't disable any cosmetic filtering.

**Comment by spodermenpls** [comment]
@dumbusernameidk This is weird.. I never deactivated cosmetic filtering on this system (as seen in the settings.txt above), I have no clue what else could be wrong.. conflicting extensions, Firefox settings? Who knows, it's not that bad.
