### ISSUE TITLE
vidlox.tv

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#503]
Popup ads are served when you click anywhere on pages on `https://vidlox.tv`. Anti adb warning is also displayed on some videos which are defined as such.  The video itself doesn't play when uBO is enabled.

**Error URL:** 
`https://vidlox.tv/zqljr7hjfpt2` (Anti adb & popup)
`https://vidlox.tv/aof6qs3r29x0` (Video play error)

This site also contains an ad leftover from `http://adskeeper.co.uk`, a "**_Loading..._**" element below the video player. This is an issue on many other websites which use **Adskeeper**.

_**Note:** Using uBO 1.13.2 on Chrome 59 with the default filters and settings._

**Comment by ghajini** [comment]
you can use ublock protector extension ....
`https://jspenguin2017.github.io/uBlockProtector/`

**Comment by okiehsch** [comment]
@gotitbro this site is buggy on my end, the video doesn't play even if I disable uBO.
Someone else will have to come up with a comprehensive solution, what I can tell you is that
`vidlox.tv##script:inject(noeval.js)` will fix your popup issue.

**Comment by mapx-** [comment]
try
```
@@||vidlox.tv$csp
@@*pop$script,domain=vidlox.tv|suspents.info
```

**Comment by gorhill** [comment]
Video playback is broken because of the filter `@@|blob:$domain=[...]|vidlox.tv` in EasyList. This is needed: `@@|blob:$domain=vidlox.tv`.

**Comment by gotitbro** [comment]
@okiehsch Video playback is fixed by the added filter.

The **_tawk.to_** chat widget is blocked on the site due to these filters in **EasyList**:
```
|https://$third-party,script,domain=vidlox.tv
|https://$third-party,subdocument,domain=vidlox.tv
|https://$third-party,xmlhttprequest,domain=vidlox.tv
```

Any fix for the anti adb? They use this script for checking: `https://ctrlv.it/javascript/35901/3069036032`

Also what would be a good cosmetic filter to hide the **AdsKeeper** leftover?

Thank You

**Comment by okiehsch** [comment]
Like I said I can't play the video, I get the same error with and without uBO enabled
````
XMLHttpRequest cannot load https://c23.vidlox.tv/hls/oudvgpzvlntk2yixv6aoeatskquf22o2p7xzmuyru,o3x4jmv5gllov6kq33a,vqx6jmv5gln2v6b4bfa,.urlset/master.m3u8. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://vidlox.tv' is therefore not allowed access. The response had HTTP status code 404.
````

**Comment by gotitbro** [comment]
@okiehsch Does the page load as expected? If so, what can be done about the anti adb warning and the Adskeeper element?

I guess the tawk.to issue can be resolved by: `@@||tawk.to^$domain=vidlox.tv`

**Comment by gotitbro** [comment]
`vidlox.tv##script:inject(noeval.js)` also breaks some functionality like the "**_Add to Favorites_**" button on the site.

**Comment by okiehsch** [comment]
`vidlox.tv##script:inject(nowebrtc.js)` should also work but I can't help with the antiadblock, all 
I see is a black screen and I have no time to do some extended troubleshooting.

**Comment by gotitbro** [comment]
@okiehsch The anti adb warning is stopped in **Adguard English filter** by:
`vidlox.tv#%#Object.defineProperty( window, 'adb', { get: function(){ return 0; } });`

I am not sure what an equivalent filter would be for this in uBO.

**Comment by okiehsch** [comment]
I still can't play the videos, but the anti adb warning is fixed with gorhills [commit](https://github.com/uBlockOrigin/uAssets/commit/af993a05f117d76324633f9e996ecd72dcf4ec9f), on my end.

**Comment by gotitbro** [comment]
Yes it is, thanks for the heads up. For some reason the filter wasn't getting applied, disabling and enabling uBO fixed it.
