### ISSUE TITLE
bmovie.cc

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#5044]
### URL(s) where the issue occurs

`https://bmovie.cc/movies/police-story-lockdown/`

### Describe the issue

Popup

### Versions

- Browser/version: Chrome 72
- uBlock Origin version: 1.18.4

### Settings

- Default settings.

**Comment by ghajini** [comment]
https://bmovie.cc/movies/ufc-236-holloway-vs-poirier-2/
malicious popups

**Comment by ghajini** [comment]
`bmovie.cc` page died, it redirects to `fmovie.cc`
