### ISSUE TITLE
pixel.homebook.pl tracking

### ISSUE THREAD

**Issue by kashir2000** [uBlockOrigin/uAssets#5045]
### URL(s) where the issue occurs

3 Examples: 
````
https://dekoracjeirys.pl/produkt/zegar-zegarek-metalowy-vintage-loft-scienny-60cm.html
https://sklep.emibig.com.pl/produkt/luna-3-black/
https://dekoracjeirys.pl/produkt/zegar-zegarek-metalowy-vintage-loft-scienny-60cm.html
````

### Describe the issue

Site that does not respect privacy. Tracking of users in shops (especially in Poland)
They track what users are watching and shopping.

### Screenshot(s)

none required

### Versions

- Browser/version: 65.0.2 Firefox
- uBlock Origin version: 1.18.4

### Settings

No changes made

#### 1 Pagevie call
`https://pixel.homebook.pl/tracker/trackView?drfr=`
GET /tracker/trackView?drfr= HTTP/1.1
Host: pixel.homebook.pl
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
Accept: image/webp,*/*
Accept-Language: pl,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: `https://dekoracjeirys.pl/produkt/zegar-zegarek-metalowy-vintage-loft-scienny-60cm.html`
DNT: 1
Connection: keep-alive
Cookie: userId=xxxxxxxxxxxxx; hb_ab2_BjpkN4OYRU2YAkGhQlGOMQ=-1; hb_ab2_xxxxxw=-1; hb_abd=True; hb_sid=xxxxxxx; PWA_adbd=1; _qg_fts=1312312312312; QGUserId=%312312312312312%22; _qg_cm=1; hb_reco_pids=32052582|32732882
Pragma: no-cache
Cache-Control: no-cache

#### 2 Purchase report 
`https://pixel.homebook.pl/tracker/trackSales?productsIds=526&orderValue=179&orderId=140&drfr=`

#### Their docs:
`https://www.homebook.pl/home/pixel`

**Comment by krystian3w** [comment]
@olegwukr ? / @ryanbr \ @Khrin.

**Comment by krystian3w** [comment]
@kashir2000 - this list help in Polish version sites:

https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/adblock.txt

:question:

**Comment by kashir2000** [comment]
@krystian3w Not sure if you ask me if linked list helps or suggest to post it there.
If first, it does not block pixel.homebook.pl

**Comment by mapx-** [comment]
@kashir2000  report to the list linked above or wait for @Khrin @ryanbr to include a fix in easyprivacy

**Comment by kashir2000** [comment]
@mapx- tbh, i will pass/wait then, there are way too many of those lists and I don't know which one is proper then.

**Comment by krystian3w** [comment]
For uBO :world_map: EasyPrivacy, for "freak" :poland:  maybe `Polish Privacy Filters`.
