### ISSUE TITLE
convallariaslibrary.com [Anti-Adblock]

### ISSUE THREAD

**Issue by uBlockIsBest** [uBlockOrigin/uAssets#5047]
### URL(s) where the issue occurs

`http://www.convallariaslibrary.com/`

### Describe the issue

Anti Adblock

### Versions

- Browser/version: firefox 65.0.2
- uBlock Origin version: v1.18.4

### Settings

- 
[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/2923335/Settings.txt)

### Notes

`@@www.convallariaslibrary.com$generichide` works, but its not the best resolution

**Comment by garry-ut99** [comment]
Ad placeholders all over the site, caused by `ghide` in "uBlock filters", example placeholder: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/214833181-630a3f8f-3b24-460b-beb3-36e2205497dc.png)
