### ISSUE TITLE
express.de

### ISSUE THREAD

**Issue by uBlockIsBest** [uBlockOrigin/uAssets#5049]
### URL(s) where the issue occurs

`www.express.de`

### Describe the issue

Unblocked ads

### Versions

- Browser/version: Firefox 65.0.2
- uBlock Origin version: v1.18.4

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/2923537/Settings.txt)

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/8deaf2ada46e2abb39baa026f4bec5a54665d442
