### ISSUE TITLE
Cosmetic Filtering - invalid filters in uBlock Filters List in Firefox only

### ISSUE THREAD

**Issue by jjohns71** [uBlockOrigin/uAssets#505]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt`

### Describe the issue

In Firefox, using the beta release, according to the uBlock logger, 2 cosmetic filters fail to load after forcing refresh of 'uBlock filters'.

`##.side-left /deep/ [id^="ecbr-"]`
`##.side-right /deep/ [id^="ecbr-"]`

The logger in Chrome Version 59.0.3071.115 (Official Build) (64-bit) using uBlock 1.13.2 shows no error.

I'm honestly not sure if this is a bug in uBlock or an error in the filter since it seems to load fine in Chrome but errors in Firefox. 

### Screenshot(s)

Screenshot of uBO Logger in Firefox (Error):

![firefox](https://user-images.githubusercontent.com/6795795/28082337-3145b260-6640-11e7-884a-5a749e03408f.png)

Screenshot of uBO Logger in Chrome (No Error):

![chrome](https://user-images.githubusercontent.com/6795795/28082312-2858016c-6640-11e7-81e1-4beed62e17b4.png)

### Versions

Error occurs in:
- Browser/version: Firefox 54.0.1 
- uBlock Origin version: uBlock Origin 1.13.7rc2

### Settings

Default Advanced User

### Notes

No idea if this filter does not work in Firefox because of a browser limitation, but figured it was worth reporting that there is a discrepancy between browsers/uBO versions in what is able to be parsed in the default 'uBlock Filters' list.

**Comment by gorhill** [comment]
By design. the filter is invalid on Firefox, uBO rejects it.

**Comment by gorhill** [comment]
Related: https://github.com/gorhill/uBlock/issues/2417
