### ISSUE TITLE
Rule under EasyPrivacy list is block _stats.js scripts

### ISSUE THREAD

**Issue by TiagoPortfolio** [uBlockOrigin/uAssets#5055]
### URL(s) where the issue occurs

`https://co.aptoide.com/account/my-stores/tiago-sousaapps/controlpanel/stats _(Need login to access this BO)_`

### Describe the issue

This BO is using a script named **my_stats.js** to build graphs and tables and, for some reason, it is being blocked because of a rule **(_stats.js?)** under **EasyPrivacy** list.

### Screenshot(s)

BO: https://imgur.com/ldssl9K
Rule: https://imgur.com/Vz7AL2E

### Versions

- Browser/version: Chromium Version 71.0.3578.98
- uBlock Origin version: v1.18.4

### Settings

- No changes to default settings.

### Notes

Like I said before in the issue description, scrips containing **_stats.js** in the filename will be blocked. This rule is too generic and I imagine there are other rules as generic as this one that are blocking scripts incorrectly. Would like if rules like this can be reviewed.

**Comment by mapx-** [comment]
Could you post (pastebin.com) the script blocked by that filter ?

@ryanbr

**Comment by TiagoPortfolio** [comment]
Direct link to the script: https://cdn6.aptoide.com/includes/js/2014/my_stats.js?timestamp=20190123
Pastebin link: https://pastebin.com/3AFxHFwp

**Comment by ryanbr** [comment]
could just change the filename..

**Comment by mapx-** [comment]
@TiagoPortfolio  if you work with/for `aptoide`, could you just rename that script ? (as for ryanbr suggestion)

**Comment by TiagoPortfolio** [comment]
That's what I did as a quick fix but don't you think these rules should be reviewed because of being too much generic? Blocking scripts just because the filename has **_stats.js** keyword or other rules similar to this one can block several scripts that have nothing to do with ads.

**Comment by mapx-** [comment]
well, this is up to easylist authors .. so, the current issue can be considered fixed (renaming the script in your case) ?

**Comment by TiagoPortfolio** [comment]
Would appreciate if this can be shared with easylist authors or if you can point me to some way to contact them about this.
Yes, I renamed the file so this can be considered fixed, thanks!

**Comment by mapx-** [comment]
@ryanbr which wrote above is an easylist author
