### ISSUE TITLE
itorrents.org

### ISSUE THREAD

**Issue by 241d2** [uBlockOrigin/uAssets#5056]
### URL(s) where the issue occurs

`http://itorrents.org/torrent/83821F7652A7501C4F9B921CA31F20AD2683B731.torrent`

### Describe the issue

It just closes without downloading after it checks for browser security. 

### Screenshot(s)

Can't take screenshot since it closes

### Versions

- Browser/version: Chrome Version 72.0.3626.109 (Officiel version) (64-bit)
- uBlock Origin version: v1.18.4

### Settings

- Disabled show number in icon (Vis antallet af blokerede forespørgsler på ikonet)
- Disabled "Peter Lowe’s Ad and tracking server list"

### Notes

If i disable adblock, it download the file

**Comment by mapx-** [comment]
I cannot reproduce the issue.
Could you provide the page where you found this torrent ?

**Comment by 241d2** [comment]
I found it on https://1337x.to/torrent/3568413/Windows-Server-2008-SP2-Standard-X64-3in1-JAN-2019-Gen2/
But all the torrents uses itorrents as a main link

I disabled EasyList and it worked

**Comment by mapx-** [comment]
yeah the issue is with 1337x, I killed the huge filter in easylist
