### ISSUE TITLE
cambro.tv [ADS][NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5058]
URL(s) where the issue occurs

`https://www.cambro.tv/17423/pavlovswhore-chaturbate-lesbian-dildo-fucking-fingering-nude-videos/`

Describe the issue

ADS

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 72 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.18.4

Settings

Default

**Comment by KiLL4FuNK** [comment]
ADS PLAY VIDEO

**Comment by smed79** [comment]
@okiehsch I get a popup + redirection. Can you reproduce?

**Comment by stephenhawk8054** [comment]
It's already hidden by `##a[href^="https://t.ajrkm3.com/"]` in EL for me
