### ISSUE TITLE
javhihi.com + javbuz.com + letfap.com + jav789.com  [ADS][NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5059]
URL(s) where the issue occurs

`http://javhihi.com/movie/saki-kobashi-fucked-with-toys-in-harsh-ways.3789.html`
`http://javbuz.com/movie/yu-ayana-no.7-1442.html`
`http://letfap.com/movie/dina-aislin-sex-in-red-810.html`
`http://jav789.com/movie/ray-passionate-sex-with-a-babe-603.html`

Describe the issue

ADS

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 72 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.18.4

Settings

Default

**Comment by KiLL4FuNK** [comment]
ADS

**Comment by mapx-** [comment]
test
```
jav789.com,javbuz.com,javhihi.com,letfap.com##+js(set-constant.js, String.prototype.charAt, noopFunc)
jav789.com,javbuz.com,javhihi.com,letfap.com##+js(set-constant.js, atob, noopFunc)
jav789.com,javbuz.com,javhihi.com,letfap.com##+js(set-constant.js, Math.random, noopFunc)
@@||letfap.com^$generichide
@@||jav789.com^$generichide
@@||javhihi.com^$generichide
@@||javbuz.com^$generichide
```
