### ISSUE TITLE
Unblocked ads on msn

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#506]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.msn.com/en-us/news/politics/peter-w-smith-gop-operative-who-sought-clintons-emails-from-russian-hackers-committed-suicide-records-show/ar-BBEmFpX?li=BBnb7Kz&ocid=iehp`

### Describe the issue

Unblocked ads. Sponsored by NextAdvisor in the body of article (this one shuffles; reloading it shows celebrity health tips, etc.); adchoices on the right column; sponsored topics at the bottom.
### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Chrome 59
- uBlock Origin version: 1.13.2

### Settings

Default settings

**Comment by mapx-** [comment]
test these filters
```
||taboola.com^$important
msn.com##a[href*="taboola.com"]
msn.com###promotedlinksplaceholder
msn.com##.adchoicesjs
msn.com##[id^=_mN_dy_]
@@||msn.com/advertisement.ad.js$script
```

**Comment by terrorist96** [comment]
That blocks some but not all ads.
![image](https://user-images.githubusercontent.com/12802056/28216175-afa727a2-687e-11e7-96e6-c6670ecb2528.png)

**Comment by okiehsch** [comment]
@terrorist96 this site uses [Instart Logic](https://github.com/uBlockOrigin/uAssets/search?q=g00&type=Issues&utf8=%E2%9C%93), the only way to fix your issue right now is
1. Use uBO-Extra and manually add `msn.com` which can lead to site breakage, all discussed here:
https://github.com/uBlockOrigin/uAssets/issues/458#issuecomment-313473020
2. Use Firefox, which is not affected by Instart Logic.

**Comment by terrorist96** [comment]
@okiehsch Thanks for letting me know. Why is Firefox immune but Chrome is not? Is this a limitation of uBO? And is it something that could it be fixed in a future version? Or is this not being pursued (absent installing the Extra addon and potential site breakages)?
Thank you.

**Comment by okiehsch** [comment]
Instart Logics code bails out if it detects that you use Firefox, so it has nothing to do with which adblocker you use.
If you use Firefox no Instart Logic redirects, ads etc.

**Comment by terrorist96** [comment]
Ok thanks. I also want to thank you for being so responsive. It's a nice change of pace compared to the [EasyList Github](https://github.com/easylist/easylist/issues) page where I have year old issues that still haven't been addressed or replied to. Glad I switched from ABP to uBO and don't have to rely solely on EasyList maintainers anymore.

**Comment by SMed79** [comment]
@terrorist96 read more https://github.com/uBlockOrigin/uAssets/issues/227

**Comment by mapx-** [comment]
@terrorist96 , what if you add also
`@@/^((?!revsci.net|advertising.com|googlesyndication.com|adnxs.com|amazon-adsystem|2mdn.net|media.net|chartbeat.com|quantserve.com|indexww.com|taboola.com|krxd.net|nexac.com|imrworldwide.com|googletagmanager.com|scorecardresearch.com|google-analytics.com|openx.net).)*$/$script,image,other,domain=msn.com`

**Comment by terrorist96** [comment]
@mapx- Thanks, but still see the ads with that filter too (combined with the first few filters you provided). :confused:

**Comment by Techman-** [comment]
I'm seeing g00 and injected Taboola widgets in the site with uBlock Enabled
![2017-08-11 14_52_54-](https://user-images.githubusercontent.com/5396240/29227921-d0d9b40c-7ea5-11e7-93c3-31282ee2b157.png)
![2017-08-11 14_53_49-apcent](https://user-images.githubusercontent.com/5396240/29227922-d0e06d56-7ea5-11e7-83b3-acca08672077.png)
![2017-08-11 14_54_07-](https://user-images.githubusercontent.com/5396240/29227923-d0e61b8e-7ea5-11e7-8d5f-eddb516a3fa4.png)

Last image is what happens when you hover over the first story in the first widget picture.

**Comment by gorhill** [comment]
It's because of all the exception filters in EasyList.

If you have the patience, you could craft a proper `csp=`-based filter to use the whitelist approach to defeat all the exception filters in EasyList. For example, this is a start:

    ||msn.com^$csp=default-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data: akamaized.net *.akamaized.net *.akamaized.net live.com *.live.com s-msn.com *.s-msn.com

**Comment by okiehsch** [comment]
I think he sees g00 stuff because msn.com is not part of uBO-extra.

**Comment by Techman-** [comment]
@gorhill I don't know what `csp` but I guess I'll look into that.

I do have uBlock Origin Extra installed. Maybe MSN.com needs to be added?

**Comment by gorhill** [comment]
New IL defuser approach, available in 2.35: <https://github.com/gorhill/uBO-Extra/releases/tag/2.35>.

I don't know msn.com enough to know whether this break anything or not. Would be nice if people can test. Keep in mind all the exception filters in EasyList.

**Comment by okiehsch** [comment]
I do not see any breakage on my end with videos, animations, login etc. and it "feels" much "smoother"
than IL-defuser v3.

**Comment by Techman-** [comment]
It definitely blocks the ads from showing up, but I still see the "AdChoices" button pop up next to where the ad would normally be. This is a low-priority issue to me as the actual ads are blocked, but I did want to point it out.
![2017-08-14 02_43_54-msn com](https://user-images.githubusercontent.com/5396240/29260876-89869768-809a-11e7-9aca-6635045afaf7.png)

**Comment by gorhill** [comment]
> I still see the "AdChoices"

That's probably because of all the exception filters, the 1st thing to take care of is defusing IL stuff without breaking any functionality on the site.

**Comment by okiehsch** [comment]
Site has been added to uBO-Extra and unnecessary script-exception filters have been fixed.

**Comment by ghajini** [comment]
@okiehsch 
i see this **` sponsored links by msn`** , when i click on that it go to ads `https://prnt.sc/jfso4l`

`https://www.msn.com/en-in/news/newsindia/at-kashmir-all-party-meeting-a-call-for-vajpayee-like-initiatives/ar-AAx0rnf?ocid=spartandhp`
![screenshot 4](https://user-images.githubusercontent.com/20338483/39833053-97a755b0-53e6-11e8-9449-35ea968c7f5a.png)

**Comment by mapx-** [comment]
firefox ? (version ?)

**Comment by ghajini** [comment]
google chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by ghajini** [comment]
its in nano defender

**Comment by ghajini** [comment]
@gorhill, @okiehsch @mapx- 
these ads comes back everytime,cosmetic filters are not enough.....

now i see ads from `sponsored links from taboola` though taboola is blocked as per logger
`https://www.msn.com/en-in/entertainment/bollywood/celebrity-deaths-that-shocked-india/ss-BBzXKsA?li=AA5a2m`
google chrome Version 67.0.3396.87 (Official Build) (64-bit)
***screenshot***
`http://prntscr.com/jv8oxz`

also microsoft edge  42.17134.1.0....

i felt this was intially edge problem as per @jspenguin2017 said
https://github.com/NanoAdblocker/NanoDoc/blob/master/en/ProtectedPages.MD 

but its also in chrome

**Comment by mapx-** [comment]
see if works
```
msn.com##.nativeadasideplaceholder
msn.com##.nativeadserversidecontentmodule
```

**Comment by ghajini** [comment]
works
1 query how despite having network blocking filter for taboola , ads are still shown?

**Comment by mapx-** [comment]
inline-scripts or directly:

![image](https://user-images.githubusercontent.com/10303732/41510624-42afddca-7268-11e8-8f95-e94ed1d5d3d9.png)
