### ISSUE TITLE
smotretanime.ru => ad and antiadp

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#5063]
`https://smotretanime.ru/catalog/mob-psycho-100-2nd-season-18887/1-seriya-184446/russkie-subtitry-2209424`

ad and antiadp @mapx-

**Comment by mapx-** [comment]
Video ads ?
I tried
`||quantum-phantom-moon.ru/route/$media,redirect=noopmp3-0.1s,domain=smotretanime.ru`

However, even disabling uBo, I get that message about ads, adblockers.

**Comment by bogachenko** [comment]
not working

**Comment by okiehsch** [comment]
For the pre-roll ads see https://github.com/uBlockOrigin/uAssets/issues/3131
Probably best be fixed by something like `RU AdList JS Fixes`.

**Comment by bogachenko** [comment]
`RU AdList JS Fixes` it does not fix
