### ISSUE TITLE
google.com HTML <a> ping

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#5064]
https://github.com/ryanbr/fanboy-adblock/issues/964#issue-417313518

> 
> ### List the website(s) you're having issues:
> 
> google search results:
> 
> ```
> <a href="https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns" ping="/url?sa=t&amp;source=web&amp;rct=j&amp;url=https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns&amp;ved=2ahUKEwiDqubUk-vgAhWFL6YKHf0dCQMQFjAJegQICRAB">
>   <h3 class="LC20lb">Referer header: privacy and security concerns - Web security | MDN</h3><br>
>   <div class="TbwUpd"><cite class="iUh30">https://developer.mozilla.org/en.../Referer_header:_privacy_and_security_concerns</cite></div>
> </a>
> ```
> 
> ### What happens?
> 
> When you click links on google search results page, it sends a tracking...
> ### List Subscriptions you're using:
> 
> Enhanced Trackers List (could cause some false positives, please report any issues)
> ### Your settings
> 
>     * OS/version: Windows 7
> 
>     * Browser/version: Chrome 72
> 
>     * Adblock Extension/version: adguard
> 
> 
> ### Other details:
> 
> ![2019-03-05 22_04_58-referrer privacy - google search](https://user-images.githubusercontent.com/1284845/53810845-cedee500-3f92-11e9-82ca-9e8e0dfb4ff1.jpg)
> 
> you can verify this on DevTools of chrome:
> 
> ![2019-03-05 21_51_43-devtools - developer mozilla org_en-us_docs_web_security_referer_header__privacy](https://user-images.githubusercontent.com/1284845/53810477-0305d600-3f92-11e9-9fe1-041e4e8a9523.jpg)
> 
> or I just misunderstand something...
> 
> ref:
> https://www.eff.org/deeplinks/2018/10/privacy-badger-now-fights-more-sneaky-google-tracking

https://github.com/ryanbr/fanboy-adblock/issues/964#issuecomment-469772816

> 
> ```js
> !#if env_chromium
> google.*##+js(remove-attr.js, ping, div[class] > a[ping])
> !#endif
> ```

**Comment by bogachenko** [comment]
@krystian3w ЧТДНТ?
![default](https://user-images.githubusercontent.com/8535285/53825883-413dce00-3f6f-11e9-8910-b12f70404bdb.png)

**Comment by gwarser** [comment]
This is disabled by default in uBO by "Disable hyperlink auditing" option.

**Comment by bogachenko** [comment]
@gwarser I turned it off for a while, but did not find the `ping`.

**Comment by krystian3w** [comment]
> This is disabled by default in uBO by "Disable hyperlink auditing" option.

So default disabled in Nano Adblocker?

**Comment by gwarser** [comment]
@bogachenko 

![image](https://user-images.githubusercontent.com/886325/53826400-d1ccdc00-3f78-11e9-8550-c6d13ab62f57.png)

**Comment by krystian3w** [comment]
@bogachenko  `ping` = `data-cthref`?

**Comment by bogachenko** [comment]
@gwarser Oke now i see

**Comment by gwarser** [comment]
@bogachenko Firefox? Pings are disabled in Firefox by Mozilla `browser.send_pings` is set to false, and google is doing this another way,

**Comment by bogachenko** [comment]
@krystian3w blyat, you're right/ lol

**Comment by gwarser** [comment]
> > This is disabled by default in uBO by "Disable hyperlink auditing" option.
> 
> So default disabled in Nano Adblocker?

Works fine in Nano Adblocker 1.0.0.90

**Comment by uBlock-user** [comment]
beacon  = `navigator.sendBeacon`

**Comment by mapx-** [comment]
> Adblock Extension/version: adguard

@krystian3w  did you report at adguard ?

**Comment by krystian3w** [comment]
Nope I no use AdGuard often (most only for test html filtering filters).

---

Besides, I've got lost so far as it fixes blocking bacon.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/29654#issuecomment-470939288 if you like track Aduard tracker.
