### ISSUE TITLE
photopea.com [Anti-adblock]

### ISSUE THREAD

**Issue by Ltcreed** [uBlockOrigin/uAssets#5065]
### URL(s) where the issue occurs

https://www.photopea.com/

### Describe the issue
Anti-adblock
popups every 5-10 seconds telling you to either make a premium account or turn off your adblocker

### Screenshot(s)
![screenshot 14](https://user-images.githubusercontent.com/47835511/53853957-9987c680-3f95-11e9-90da-6f0e5f9ea36e.png)

### Versions

Firefox version 65.0.2 (64-bit)
uBlock Origin v1.18.4

### Settings

Default

**Comment by landsman** [comment]
omg, just pay for great service or do not use that!

**Comment by photopea** [comment]
Guys, I changed the variable name from "ppCanRunAds" to "jsLoadedWell". So please, update your AdBlock program to this new variable name, so that I can change it again :D
