### ISSUE TITLE
adflow.com.au incorrectly blocked

### ISSUE THREAD

**Issue by chrisdt** [uBlockOrigin/uAssets#5068]
### URL(s) where the issue occurs

https://adflow.com.au

### Describe the issue

We are finding uBlock extension is incorrectly blocking scripts on the above domain. Assuming this is due to the domain including the word **ad** in it. It is possible to get this domain added to the exclusion list?

### Screenshot(s)

**When uBlock enabled:**
<img width="1331" alt="adflow_brokenlink" src="https://user-images.githubusercontent.com/8174726/53915063-44da6d80-40b3-11e9-8b11-7b4fb16e5b50.png">

**When uBlock Disabled:**
<img width="1318" alt="adflow_correctlink" src="https://user-images.githubusercontent.com/8174726/53915088-56237a00-40b3-11e9-9a3e-0f0c7e8ebc59.png">

### Versions

- Browser/version: Chrome (version 72.0.3626.119)
- uBlock Origin version: 1.18.4

### Settings

Happens with default filter lists.

**Comment by mapx-** [comment]
as you can see I already fixed your easylist issue
https://forums.lanik.us/viewtopic.php?p=146198#p146198
https://github.com/uBlockOrigin/uAssets/commit/a0cce20b126c5c16c10cfb6804f5110418d3480f

**Comment by mapx-** [comment]
However, for other adblockers you need a fix in easylist list

**Comment by chrisdt** [comment]
Thanks @mapx-
