### ISSUE TITLE
yesmoviesapp.info

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#5071]
### URL(s) where the issue occurs

`https://yesmoviesapp.info/Q2RDs`

### Describe the issue

Anti-Adblock script

### Screenshot(s)

![screenshot_2019-03-07 clicksfly shorten url and earn money](https://user-images.githubusercontent.com/24980766/53934600-716d9580-4071-11e9-8221-43fda7c965fa.png)

### Versions

- Browser/version: Firefox 66.0b13
- uBlock Origin version: 1.18.4

### Settings

- All filters enabled (except regional filters and uBlock Filters Experimental) + I don't care about cookies

### Notes

Appears to be using BlockAdBlock 3.2.1

**Comment by dumbusernameidk** [comment]
site renamed to `newskart.xyz`. link above works still.

**Comment by krystian3w** [comment]
Thx.

**Comment by krystian3w** [comment]
`viralnow.xyz/I6Jw`

**Comment by dumbusernameidk** [comment]
That was a fast name change makes me wonder if they're watching this repository 👀.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/c08be805b7f10f6f6d8c9b840cd8ab0b2cea32b8
