### ISSUE TITLE
Filter ##.side-right /deep/ [id^="ecbr-"] reported by uBO as invalid

### ISSUE THREAD

**Issue by setyb** [uBlockOrigin/uAssets#5072]
When updating uBlock Filters, uBO reports that the filter `##.side-right /deep/ [id^="ecbr-"]` is invalid.  Here is the error:

`Invalid generic cosmetic filter in ublock-filters: ##.side-right /deep/ [id^="ecbr-"]`

**Comment by gwarser** [comment]
This filter is (was?) working only on Chromium-based browsers.

`/deep/` is "shadow piercing combinator", there is also `>>>` and `::shadow`

It's deprecated, and probably not working in new versions of Chrome.

**Comment by setyb** [comment]
What's really weird is that `##.side-left /deep/ [id^="ecbr-"]` doesn't generate an error.  Any idea why?

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/53952286-a8bf5f00-40d0-11e9-8b6c-32cdcd723238.png)

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/3547ce83719a5c7eb371acf842aa94b3a8d6df8b

**Comment by setyb** [comment]
@gwarser Strange.  Only the `right` one generates an error  for me.  Obviously, they both should.  But I've seen some weird idiosyncratic errors with uBO's logger, so that's how it goes.
