### ISSUE TITLE
sinoptik.ua

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uAssets#5073]
### URL(s) where the issue occurs

`https://sinoptik.ua`

### Describe the issue

breaks the functionality of site, the line with the cities doesn't work
problem is in the filters (uBlock filters)
**P.S.**
`zmctrack.net` blocked in RU AdList
sites, that host ads from this service no longer need the old rules and are served by a RU AdList moderator, which uses the functionality of uBO.

### Screenshot(s)

![1](https://user-images.githubusercontent.com/28482376/53946148-d524ac80-40cb-11e9-91a7-f31458d0c038.gif)

### Versions

- Browser/version: [Opera|beta]
- uBlock Origin version: [1.18.5rc3]

**Comment by mapx-** [comment]
So, you are saying we can remove all sinoptik filters from ublock filters list ?

**Comment by PoRtvine** [comment]
all sinoptik filters and other sites with zmctrack.net

**Comment by mapx-** [comment]
take a look to this group of filters:
https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L8648

**Comment by PoRtvine** [comment]
Yes, this group of filters
