### ISSUE TITLE
Eurogamer ad removed but spacing left leaving large blank area on site

### ISSUE THREAD

**Issue by neilw1** [uBlockOrigin/uAssets#5074]
### URL(s) where the issue occurs

`https://www.eurogamer.net/`

### Describe the issue

Leaves an unsightly 25% of screen area as simply a blank space. All other ad-blockers collapse this.
fault is non-removal of: leaderboard.leaderboard.advert

### Versions

- Browser/version: Chrome 72
- uBlock Origin version: 1.18.4

### Settings

None

### Notes
leaderboard.leaderboard.advert not being zapped is at fault. Other blockers remove this fine.

**Comment by mapx-** [comment]
I get that area only disabling the cosmetic filters, check if you altered that setting
