### ISSUE TITLE
oceano.uy

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#5076]
### URL(s) where the issue occurs

`https://oceano.uy/todopasa/escuchame-una-cosa/16010-el-partido-digital-y-la-democracia-liquida?play=true`

### Describe the issue

The audio player is broken.

### Screenshot(s)

![22039ded-1b57-48e1-8845-01bcfb8393a0](https://user-images.githubusercontent.com/27441315/53966433-73783880-40f3-11e9-85a7-8d64d72127bf.png)

### Versions

- Browser/version: Chrome 72
- uBlock Origin version: 1.18.4

### Settings

- Default settings.

**Comment by mapx-** [comment]
@ryanbr
