### ISSUE TITLE
Washington Post anti-adblock

### ISSUE THREAD

**Issue by gitshopping** [uBlockOrigin/uAssets#5077]
### URL(s) where the issue occurs

Any page linked from ``https://www.washingtonpost.com'``
e.g.  
`https://www.washingtonpost.com/weather/2019/03/06/most-spectacular-rare-lightning-displays-electrifies-southern-california/?utm_term=.4fb9ce13fef0'`

### Describe the issue
Site using anti-adblock.   

### Screenshot(s)
N/A

### Versions
- Browser/version: FireFox Quantam 65.0.1 (64-bit)
- uBlock Origin version: uBlock Origin v1.18.4

### Settings
N/A

### Notes
Can disable the anti-adblock by blocking first-party scripts, in which case the page loads but many images are masked.  Have not been able to fix by trying to whitelist specific parts of the first party script.  Another workaround is immediately stopping the page load after reload, which must stop the page load before the problem script runs.  

Saw prior issues related to their paywall, but seems like a different message/anti-adbock, and, while you can subscribe to get access, it appears they are also quite fine with you simply disabling your adblocker so I don't view it as a paywall issue.   A previously suggested filter of `washingtonpost.com##script:inject(abort-on-property-read.js, WpPwapi2)` does not work.  Thx.

**Comment by mapx-** [comment]
already opened here
https://github.com/uBlockOrigin/uAssets/issues/5070
