### ISSUE TITLE
[Anti-adblock] http://ally.shortens.co

### ISSUE THREAD

**Issue by 1041319** [uBlockOrigin/uAssets#5078]
### URL(s) where the issue occurs

`[http://ally.shortens.co/SUG9x.]`

### Describe the issue

[The site detects that I'm using Adblock and asks me to disable tracking protection or adblock.]

### Screenshot(s)

[https://i.imgur.com/9erOCVn.png]

### Versions

- Browser/version: [Firefox Nightly 67.0a1]
- uBlock Origin version: [1.18.4]

### Settings

- [The only configuration I changed was IP leak protection, the filters were not changed, the only filter addition was from Nano Defender.]

### Notes

[The extensions I'm currently using are; Privacy Badger, Ublock, Decentraleyes and Nano Defender 15.106. The site is used as a redirect, usually used on sites that generate premium links. When accessing the site, it asks me to disable adblock or tracking protection, and if I disable firefox tracking protection, the site still asks me to disable tracking protection, and only works normally after it disables Privacy Badger as well.]

**Comment by okiehsch** [comment]
I can't reproduce using only Firefox and uBO with a default setup.

**Comment by mapx-** [comment]
something with Nightly perhaps, I cannot reproduce either

**Comment by okiehsch** [comment]
> When accessing the site, it asks me to disable adblock or tracking protection, and if I disable firefox tracking protection, the site still asks me to disable tracking protection, and only works normally after it disables Privacy Badger as well.

Or an issue with Privacy Badger ;)

@1041319 we can't fix issues caused by `non-uBO` extensions.
