### ISSUE TITLE
https://read.amazon.com/

### ISSUE THREAD

**Issue by Khosla1** [uBlockOrigin/uAssets#508]
### URL(s) where the issue occurs

`https://read.amazon.com`

### Describe the issue

Can't read a book when ublock is enabled

### Versions

- Browser/version: [Chrome59]
- uBlock Origin version: [ 1.13.2]

**Comment by gorhill** [comment]
Unable to reproduce.

You do not share any of your settings, filter lists, rules, so it's not possible to help you.

**Comment by okiehsch** [comment]
I can't reproduce either, without more information, nothing can be done.
