### ISSUE TITLE
rapidgator.net

### ISSUE THREAD

**Issue by 241d2** [uBlockOrigin/uAssets#5084]
### URL(s) where the issue occurs

`https://rapidgator.net/file/6824667ef86e8e4fc5332345e154e644/Eziriz._-Desire-_Net.Reactor.5.9.8.0..rar.html`

### Describe the issue

Request for time countdown boosting

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]
![image](https://user-images.githubusercontent.com/45212341/54070874-1781f100-4266-11e9-8068-7ca5db0dd481.png)

### Versions

- Browser/version: v1.18.4
- uBlock Origin version: Chrome Version 72.0.3626.109 (Officiel version) (64-bit)

### Settings

- Disabled show number in icon (Vis antallet af blokerede forespørgsler på ikonet)
- Disabled "Peter Lowe’s Ad and tracking server list"

**Comment by okiehsch** [comment]
The site validates the timer on the server side, so this can't be fixed.

Add 
`rapidgator.net##+js(nano-setInterval-booster.js)`
you will see that you boost the timer on your side but after it expires you will get an error message.

**Comment by 241d2** [comment]
oh ok thanks anyway
