### ISSUE TITLE
url.hulblog.com anti adb

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#5085]
### URL(s) where the issue occurs

`[http://url.hulblog.com/ZHyuY]`

### Describe the issue

[It show message to turn off adblocker]

### Screenshot(s)

[https://imgur.com/RrZXwYj]

### Versions

- Browser/version: [Firefox Quantum 65.0.2]
- uBlock Origin version: [1.18.4]

### Settings

- [https://pastebin.com/dYdy4TqG]

### Notes

[If i turned off UBO it works]

**Comment by exodius48** [comment]
@mapx- Thx for solve it, but why it neverending load countdown timer when i activate UBO?
If i turned of UBO, it load coundown timer?

**Comment by mapx-** [comment]
It's ok for me. Did you test keeping only uBo enabled (default setup !) and disabling all other addons ?

**Comment by smed79** [comment]
@exodius48 Do you have **Fanboy’s Annoyance List** enabled? If yes, test the below filter
```
@@||cdn.jsdelivr.net^*/jquery.particleground.min.js?$script,domain=url.hulblog.com
```

**Comment by exodius48** [comment]
@mapx- After reset to default setting it works

@smed79 Yes, im using that list. Your script work. Then where i report this bug? or @mapx- can include that script?

**Comment by mapx-** [comment]
you can report here the issue
https://github.com/ryanbr/fanboy-adblock/issues
or
https://github.com/easylist/easylist/issues

**Comment by exodius48** [comment]
@mapx- OK, thank you 👍
