### ISSUE TITLE
timesofindia.indiatimes.com{Breakage}

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5087]
### URL(s) where the issue occurs

`https://timesofindia.indiatimes.com/india/terror-financing-nia-summons-mirwaiz-geelanis-son-for-questioning-in-delhi/articleshow/68334840.cms`

### Describe the issue

video won't play on site
### Screenshot(s)

![Screenshot_2019-03-09 Terror financing NIA summons Mirwaiz, Geelani's son for questioning in Delhi - Times of India ►](https://user-images.githubusercontent.com/20338483/54075372-a02f7a00-42c4-11e9-8e3f-9fa13de2791c.png)

### Versions

- Browser/version: firefox desktop 65/ opera browser stable
- uBlock Origin version: 1.18.4

### Settings

- uBO's default settings+nano defender+decentraleyes

### Notes
same video is playable on firefox android so make sure your filter doesn't break firefox android ublock origin

**Comment by in4u** [comment]
Breakage again. Sometimes the video doesn't play and when it does then the seekbar as well as the play/pause button on top of the video gets blocked.

**Comment by mapx-** [comment]
@ryanbr

**Comment by in4u** [comment]
Breakage: Some videos either don't play or they play only after an additional click or two.

Example URL: `https://timesofindia.indiatimes.com/ultimate-revenge-how-a-sheep-had-the-last-laugh-against-this-man/videoshow/77042469.cms`

There's another breakage I've noticed but can't reliably reproduce so feel free to ignore it. In private browsing mode (maybe regular mode also, haven't checked), on `https://timesofindia.indiatimes.com/videos`, some videos don't play when their link is opened in a new tab but play fine when opened in the same tab.
