### ISSUE TITLE
Header on qz.com

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#509]
Hi, 

In [Ublock Filters](https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt) list, the two cosmetic filters for qz.com (starting on line 1143) don't actually keep the header bar from sticking to the top. 

I believe the additional filter below also needs to be added to the [Ublock Filters](https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt) list to get the intended effect of pinning the header to the top of the screen.

`qz.com##.logo:style(position: relative !important; top: 0 !important;)`

The reason why I am opening this issue & honestly not sure if this is a bug within uBO or not (could be timing/priority issue) but when you have [uBlock Filters](https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt) list selected and enabled, after you add 
`qz.com##.logo:style(position: relative !important; top: 0 !important;)` 
filter to 'My Filters' in uBo the header still drops down when you scroll up on the page.

However, if you unselect the [uBlock Filters](https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt) list and add the following filters (The first filter listed below is also present in [uBlock Filters](https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt)) to 'My Filters'

`qz.com###header:style(position: relative !important; top: 0 !important;)`
`qz.com##.logo:style(position: relative !important; top: 0 !important;)`

the header is pinned to the top as intended and has no issue when scrolling up.

You can test this by disabling the [uBlock Filters](https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt) list and using the following filters in 'My Filters' and reloading the [example page](https://qz.com/1007906/a-new-wave-of-tech-talent-is-emerging-not-from-indias-classrooms-but-its-hinterlands/) used in the [uBlock Filters](https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt) list .

`qz.com###header:style(position: relative !important; top: 0 !important;)`
`qz.com##.logo:style(position: relative !important; top: 0 !important;)`

Thanks!

**Comment by gorhill** [comment]
With uBO, the header bar behaves the same way as when uBO is disabled on the site. The header bar is meant to be visible when scrolling up, not when scrolling down.

**Comment by yourduskquibbles** [comment]
Thanks for looking into this.

Any idea why when you add the two filters listed above to 'My filters' they don't keep the header bar from reappearing when scrolling up when 'uBlock Filters' is also selected/enabled but as soon as 'uBlock Filters' is unloaded the filters seem to work as they should by keeping the header from appearing while scrolling up? Is it because uBO filter list takes precedence over 'My filters'?

Switching gears, is it possible to just remove the qz.com filters from 'uBlock Filters' list? If what you say is desired behavior I don't think they are actually providing any benefit since the site behaves in the same manner with uBO on/off. I believe this would also allow users to come up with their own solution / use a different filter list that pins the header bar in place properly.

**Comment by gorhill** [comment]
Your filter has the same specificity than the uBO's one. If you want to be sure it wins, you need to make it more specific. Try:

    qz.com###header#header:style(position: relative !important; top: 0 !important;)

I don't see the purpose of the `.logo` one, since the `.logo` element is a descendant of the `#header` one.

**Comment by gorhill** [comment]
> is it possible to just remove the qz.com filters from 'uBlock Filters' list?

I would have to be sure whatever that filter solved does not happen anymore. I can't remember why this was needed, I suspect there used to be a banner on top of the header bar.

**Comment by yourduskquibbles** [comment]
@gorhill 

Thanks for filter specificity suggestion, that seems to work.

Issue #256 had a discussion about the qz header, only relevant issue that I could find that mentions qz.com in [this repository](https://github.com/uBlockOrigin/uAssets/issues?utf8=%E2%9C%93&q=is%3Aissue%20qz) or [uBlock Origin issue tracker](https://github.com/gorhill/uBlock/issues?utf8=%E2%9C%93&q=is%3Aissue%20qz).

**Comment by gorhill** [comment]
I remove the styling filter, it seems obsolete.

I observed that there is an exception filter in EasyList, `@@||g.doubleclick.net/gampad/adx?$xmlhttprequest,domain=qz.com`. I can't figure its purpose, and all seems to still work fine if overriden using the `important` option, so I added the override filter to uBO's filters.

**Comment by gorhill** [comment]
I entered the wrong issue number is commit message. Fixed with 97d9e191b05a4378b226f4e0af03d41abd0450c4.

**Comment by yourduskquibbles** [comment]
Thank you sir.
