### ISSUE TITLE
www.tvinfo.de

### ISSUE THREAD

**Issue by alexara** [uBlockOrigin/uAssets#51]
### URL(s) where the issue occurs

www.tvinfo.de

### Describe the issue

Static ads above and right of the content

### Screenshot(s)

![tvinfo_ads_screenshot](https://cloud.githubusercontent.com/assets/13819719/15646341/60c4b80c-265d-11e6-9be1-7be68d620a3b.png)

### Versions

- Browser/version: FF 46.0.1
- uBlock Origin version: 1.7.0

### Settings

- All default filter activated + all advertising filters + Easy List Germany

### Notes

This can be fixed by
```
www.tvinfo.de###infoTop
www.tvinfo.de###infoRight
```

**Comment by gorhill** [comment]
I don't see any banner with default settings + EasyList Germany.

**Comment by IDKwhattoputhere** [comment]
Me neither. Only thing not blocked for me is what I posted [here](https://forums.lanik.us/viewtopic.php?p=94370#p94370).

**Comment by gorhill** [comment]
Anyways, such filters should be reported to maintainers of EasyList Germany: <https://forums.lanik.us/viewforum.php?f=90>.

**Comment by alexara** [comment]
> Anyways, such filters should be reported to maintainers of EasyList Germany: https://forums.lanik.us/viewforum.php?f=90.

Oh, I am sorry in that case. I misunderstood this part:
> The goal of this repository is to receive all the reports for the need of new filters

**Comment by gorhill** [comment]
You did not misunderstand the part. My chosen solution to the specific issue here is that it is best to have these trivial cosmetic filters be part of EasyList Germany.
