### ISSUE TITLE
yts.gs

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#510]
yts.gs

When you click on buttons on this website, like the "browse movies" button or the search bar, it seems like popup ads are trying to open briefly and then they close automatically, but is there a way to just block the ads without them opening and closing at all? Thanks.

![yts gs](https://user-images.githubusercontent.com/26278182/28226450-318d715c-68a4-11e7-8047-78a79368ee99.jpg)

Firefox Develper Edition 55.0b8 (32-bit)
uBlock Origin 1.13.4
Anti-Adblock Killer 10.0
Anti-Adblock Killer Continued 1.095

**Comment by SMed79** [comment]
test
```
yts.gs##script:inject(noeval.js)
yts.gs##script:inject(nowebrtc.js)
```

**Comment by okiehsch** [comment]
Fixed, update your `uBlock filters` list.

**Comment by SMed79** [comment]
Maybe, It is better if you merge all `nowebrtc` to the existing group [8eb5d75c3/filters/filters.txt#L1110](https://github.com/uBlockOrigin/uAssets/blob/df1c4ff6d16b63b91528eac57cc7f238eb5d75c3/filters/filters.txt#L1110).

**Comment by okiehsch** [comment]
I will merge all sites, which have `nowebrtc-popups` as their sole issue.
