### ISSUE TITLE
dailyuploads.net

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#5100]
### URL(s) where the issue occurs

`[https://dailyuploads.net/3j21yaigkdbx]`

### Describe the issue

[Popup when clicking on the page + site is requesting a lot of third party xhr.]

### Versions

- Browser/version: [chrome v72]
- uBlock Origin version: [1.18.4]

### Settings

- [default]

### Notes

[`dailyuploads.net##+js(abort-current-inline-script.js, RegExp, zfgloaded)` this filter got rid of the popups + third party xhr requests.]

**Comment by smed79** [comment]
@mapx- b626544 you mean `||chouftak.net^` without exclamation point.

**Comment by mapx-** [comment]
thx
