### ISSUE TITLE
readmng.com

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#5102]
### URL(s) where the issue occurs

`https://www.readmng.com/`

### Describe the issue

Anti adblock

### Screenshot(s)

![{6CDE0F4E-C713-4750-B6A3-9F2AB6FF94D7}](https://user-images.githubusercontent.com/27441315/54110048-a3b82380-43e0-11e9-909a-124e143035d6.png)

### Versions

- Browser/version: Chrome 72
- uBlock Origin version: 1.18.4

### Settings

- Default settings.

**Comment by lain566** [comment]
Chatbox is broken, this works for me.
```
readmng.com#@#[style] > iframe
readmng.com#@#div > iframe:first-child
```

![{2DA3C772-4FF6-46C0-8D39-BCC43341C9AD}](https://user-images.githubusercontent.com/27441315/54113292-3e683080-43e8-11e9-9b9c-3757ac2bc3ca.png)

**Comment by mapx-** [comment]
@ryanbr

**Comment by gwarser** [comment]
@mapx- latest update is breaking "all pages" mode - https://www.reddit.com/r/uBlockOrigin/comments/t06qog/readmngcom/

**Comment by mapx-** [comment]
removed
