### ISSUE TITLE
novinky.cz

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#5104]
`novinky.cz` - ads @mapx- @okiehsch 

this does not work #815

**Comment by mapx-** [comment]
it seems fixed using the regional list
`CZE, SVK: EasyList Czech and Slovak`

**Comment by bogachenko** [comment]
this does not work

**Comment by mapx-** [comment]
provide page link, screenshot with what ads still on page

**Comment by bogachenko** [comment]
I retard, this shit can be removed in 2 ways
`novinky.cz##+js(cookie-remover.js)` or `novinky.cz##^script:has-text(Number()`
however, in 2 way you need to manually delete cookies beforehand, but..
Lol
