### ISSUE TITLE
revolvermag.com modal popup

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#5107]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.revolvermag.com/culture/closer-strange-story-nine-inch-nails-enduring-strip-club-anthem`

### Describe the issue
Modal popup with scrollbar break

### Screenshot(s)

![revolver](https://user-images.githubusercontent.com/22258847/54128485-900dbc80-43e2-11e9-831a-39eb3b0ffe91.png)

### Versions

- Browser/version: Chrome Version 73.0.3683.67 (Official Build) beta (64-bit)
- uBlock Origin version: uBlock Origin  1.18.5rc4 (Latest Dev Build)
- uBlock Origin Extra 2.80

### Settings

- Test profile with default settings and lists.

### Notes

**Comment by smed79** [comment]
@yourduskquibbles please, test 
```
/emma-content-aggregates-prd.
```

**Comment by yourduskquibbles** [comment]
> 
> 
> @yourduskquibbles please, test
> 
> ```
> /emma-content-aggregates-prd.
> ```

@smed79 This also works for me on test profile using default uBO settings & lists. 

@okiehsch What is preferable filter solution to add to annoyances list in this scenario?

**Comment by mapx-** [comment]
You can keep your fix but add also the blocking filter (for eventually other cases like this 1)
