### ISSUE TITLE
livescience.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#511]
The share buttons on `https://www.livescience.com` are broken due to this filter in **_uBlock filters – Privacy_**:
`||googletagmanager.com/gtm.js$script`

**Error URL:** `https://www.livescience.com/42301-brain-death-body-alive.html`

Try clicking on any of the share buttons in the left sidebar they won't work.

_**Note:** Using uBO 1.13.2 on Chrome 59 with the default filters and settings._

**Comment by gorhill** [comment]
I notice a video in the middle of the article, which is broken as a result of an EasyList `|blob:` filter. Is the video legit or shouldn't it be cosmetically removed?

**Comment by okiehsch** [comment]
Hm I do not see any video at `https://www.livescience.com/42301-brain-death-body-alive.html`, even after 
disabling the `|blob:` filter.
I do think that `livescience.com##.right-rail` blocks legitimate content.

**Comment by gotitbro** [comment]
@gorhill I do not see a video on that page. Here is a page with a video in it and it plays perfectly fine for me: `https://www.livescience.com/59237-agile-soft-3d-printed-robot.html`

@okiehsch Yes that filter hides the sidebar, reported to EasyList maintainers.

**Comment by gotitbro** [comment]
@gorhill Same issue on `https://www.space.com`.

**Error URL:** `https://www.space.com/6132-father-seti.html`

**Comment by SMed79** [comment]
> I do think that livescience.com##.right-rail blocks legitimate content.

https://github.com/easylist/easylist/commit/44616805a45bba935a4f2247734c9cb82a3bf42c
