### ISSUE TITLE
marijuanamoment.net modal popup

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#5110]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.marijuanamoment.net/house-passed-legal-marijuana-bill-advances-in-new-mexico-senate/`

### Describe the issue
Modal popup

### Screenshot(s)
![marijuanamoment](https://user-images.githubusercontent.com/22258847/54129510-c8ae9580-43e4-11e9-88f9-53651d8a835c.png)

### Versions

- Browser/version: Chrome Version 73.0.3683.67 (Official Build) beta (64-bit)
- uBlock Origin version: uBlock Origin  1.18.5rc4 (Latest Dev Build)
- uBlock Origin Extra 2.80

### Settings

- Test profile with default settings and lists.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/146456

**Comment by mapx-** [comment]
What's the issue ? test link ?

**Comment by krystian3w** [comment]
>What's the issue ?

missed update:

`###boxzilla-overlay` to `##.boxzilla-overlay`



https://user-images.githubusercontent.com/35370833/228048366-b2a02d9f-b2f7-42c7-86fa-3b6f84201c73.png - exist

![obraz](https://user-images.githubusercontent.com/35370833/228048515-6ef2b602-abff-4c1b-8494-3974580decee.png) - no longer exist




> test link ? 

`https://thebaffler.com/latest/after-the-war-on-cancer-watson`

---

At end French/Română grammar with your wrote "?" with space.
