### ISSUE TITLE
tarnkappe.info [Anti-Adblock]

### ISSUE THREAD

**Issue by Scunkaneli** [uBlockOrigin/uAssets#5112]
### URL(s) where the issue occurs

`https://tarnkappe.info`

### Describe the issue

Using uBlock Origin (and allowing scripts from tarnkappe.info) leads to an Anti-Adblock message displayed on top of the site.

### Screenshot(s)

https://i.imgur.com/oBBoqdo.jpg

### Versions

- Browser/version: Firefox 66.0b14 (beta channel)
- uBlock Origin version: 1.18.4

### Settings

Default

### Notes

I tried to fix it myself but I was not able to get it working. 
Blocking `tarnkappe.info##.quSOOxlDSZqs` and `tarnkappe.info##.quSOOxlDSZqs-bg` works, but I doubt this is a permanent solution :/

**Comment by Scunkaneli** [comment]
`tarnkappe.info##+js(addEventListener-defuser.js, load)` works

**Comment by mapx-** [comment]
fixed as annoyance (enable ublock annoyances list)
