### ISSUE TITLE
Pulldown menus broken on AT&T report robocalls page

### ISSUE THREAD

**Issue by phillipremaker** [uBlockOrigin/uAssets#5114]
### URL(s) where the issue occurs

`https://www.att.com/esupport/report-call-or-text.html`

### Describe the issue

Pulldown menus for timezone and type of contact broken; am/pm radio button suppressed.

### Screenshot(s)

ublock on

<img width="699" alt="Screen Shot 2019-03-11 at 3 09 50 PM" src="https://user-images.githubusercontent.com/8801492/54161577-d4fc1800-440f-11e9-9fa5-fd09817d945a.png">

ublock off

<img width="747" alt="Screen Shot 2019-03-11 at 3 10 16 PM" src="https://user-images.githubusercontent.com/8801492/54161617-f1985000-440f-11e9-96be-60b5c3fe185b.png">

### Versions

- Browser/version: macOS  Chrome 72.0.3626.121 (Official Build) (64-bit)
- uBlock Origin version: 1.18.4

### Settings

- Default settings

**Comment by mapx-** [comment]
@ryanbr

**Comment by phillipremaker** [comment]
Thanks for the fast response. What more research should I have done before submitting here, or is a redirect acceptable? How do I best know where to report my issue so I don't waste volunteer time? Should I submit to EastList or will @ryanbr act on this report?

**Comment by mapx-** [comment]
Sure, you could report directly at easylist repository (all adblockers will benefit ..). Let's hope @ryanbr will see and add the exception to easylist

**Comment by phillipremaker** [comment]
Thanks. Resubnmitted at 'https://github.com/easylist/easylist/issues/3029'; Thanks for the feedback.
