### ISSUE TITLE
outdated rules and duplicates for Runet

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uAssets#5116]
!mail.ru!
go.mail.ru##.responses__wrapper > div > div:has([href^="http://an.yandex.ru/"])
||r.mail.ru^$popup
/
!seasonvar.ru!
seasonvar.ru##.td-for-left-block
seasonvar.ru##html > body:style(padding-top: 4px !important;)
seasonvar.ru###b_sl_51
/
!pikabu.ru!
pikabu.ru##.story:has(a[href*="pikabu.ru/html.php?id=ad"])
/
!fastpic.ru!
fastpic.ru##body > div:matches-css(position: absolute)
fastpic.ru##body:style(cursor: default !important;)
fastpic.ru##html:style(cursor: default !important;)
/
!happy-hack.ru!
happy-hack.ru##+js(noeval.js)
||pagead2.googlesyndication.com^$script,important,domain=happy-hack.ru
||google.com/ads/popudner/banner.jpg$image,important,domain=happy-hack.ru
happy-hack.ru##.adsbygoogle
happy-hack.ru##table[id^="blockblock"]
happy-hack.ru##body > *[id^="blockblock"]:style(visibility: visible !important; display: block !important;)
/
!qrz.ru!
qrz.ru##.content_row > div[class]:has(a[href="/help/adblock/"])
/
!rambler.ru!
championat.com,gazeta.ru,lenta.ru##+js(palacesquare.rambler.ru-defuser.js)
rambler.ru##^script:has-text((Number,)
!#if env_chromium
rambler.ru##+js(set-constant.js, Math.random, trueFunc)
!#endif
/
!rbc.ru!
rbc.ru##+js(setTimeout-defuser.js, t=null, 300)
/
!radikal.ru!
radikal.ru##+js(abort-current-inline-script.js, atob, void)
/
!cn.ru!
cn.ru##+js(abort-current-inline-script.js, parseInt, 676574456c656d656e747342795461674e616d65)
/
!ivi.ru!
||dfs.ivi.ru/mp4-hi/*/storage*.mp4|$media,redirect=noopmp3-0.1s,domain=ivi.ru
@@||ivi.tv^$generichide
/
allday2.com,itog.info,hdpicture.ru,hdrezka.*,kinogo.cc,tfile-soft.cc##+js(abort-current-inline-script.js, atob, constructor)
allday2.com##^script:has-text(26b215c9)
allday2.com##^script:has-text(KGZ1bmN0)
kinogo.cc##^script:has-text(3f87b0eaddd)
||amgload.net^$xmlhttprequest,redirect=nooptext,domain=kinogo.cc
||piguiqproxy.com^$xmlhttprequest,redirect=nooptext,domain=allday2.com|kinogo.cc
/
!ucoz!
at.ua,ucoz.com,ucoz.net,ucoz.ru,ucoz.ua##+js(abort-current-inline-script.js, atob, tabunder)
/
!sinoptik.com.ru!
sinoptik.com.ru###adsLeftZone
/
!wallpapershome.ru!
wallpapershome.ru##+js(set-constant.js, canRunAds, true)
/
!overclockers.ru!
overclockers.ru##+js(abort-current-inline-script.js, RegExp, '0x)
overclockers.ru##+js(set-constant.js, chkA, noopFunc)
/
!ognennoetv.ru!
ognennoetv.ru##+js(abort-on-property-read.js, anOptions)
/
!gidoroom.ru!
@@||gidoroom.ru^$generichide
/
!best-antidepressanty.ru,dayzmap.ru!
best-antidepressanty.ru,dayzmap.ru##+js(bab-defuser.js)
/
!tarkov-wiki.ru!
tarkov-wiki.ru##+js(set-constant.js, canRunAds, true)
/
!kinopoisk.ru!
kinopoisk.ru##+js(setInterval-defuser.js, (), 500)
kinopoisk.ru##[href*="adblock"]:xpath(..)
/
!yandex domains!
news.yandex.by,news.yandex.kz,news.yandex.ru,news.yandex.ua##+js(setTimeout-defuser.js, AdvManager)
news.yandex.by,news.yandex.kz,news.yandex.ru,news.yandex.ua##.sticky_visible
news.yandex.by,news.yandex.kz,news.yandex.ru,news.yandex.ua##[class*="_name_first"], [class*="_name_more"], [class*="_name_top"], [class*="_name_footer"]
!#if env_firefox
!||mc.yandex.ru/metrika/*$script,redirect=silent-noeval.js,domain=yandex.by|yandex.kz|yandex.ua
!||mc.yandex.ru/watch/*$script,redirect=silent-noeval.js,domain=yandex.by|yandex.kz|yandex.ua
!||mc.yandex.ru/metrika/*$script,first-party,redirect=silent-noeval.js
!||mc.yandex.ru/watch/*$script,first-party,redirect=silent-noeval.js
!||mc.yandex.ru/watch/*$script,redirect=none,domain=mail.yandex.ru
!||mc.yandex.ru/metrika/*$script,redirect=none,domain=mail.yandex.ru
!#endif
/
!picclock.ru!
picclock.ru##+js(abort-current-inline-script.js, atob, decodeURIComponent)
/
!simpsonsua.com.ua!
simpsonsua.com.ua##+js(abort-current-inline-script.js, atob, void)
simpsonsua.com.ua##+js(set-constant.js, canRunAds, true)
||megastock.ru/doc/*/azure_rus.gif$image,redirect=32x32-transparent.png,domain=simpsonsua.com.ua
*/preroll/*mp4$media,domain=td7vccbywda3.ru
@@||simpsonsua.com.ua^$csp,first-party
@@||simpsonsua.com.ua/adv$image,first-party
@@||simpsonsua.com.ua/test-ad.php$xmlhttprequest,first-party
simpsonsua.com.ua##.adsbyyottos
simpsonsua.com.ua##[href="https://krosogolik.com/"]
simpsonsua.com.ua#@#*
/
!segodnya.ua!
segodnya.ua##iframe:not([src]):style(max-height: 1px !important;)
/
!golovbukh.ua!
golovbukh.ua##.megaShadow
golovbukh.ua##body:style(overflow: auto !important;)
/
!sport.ua!
sport.ua##+js(abort-current-inline-script.js, parseInt, 676574456c656d656e747342795461674e616d65)
/
!0day.kiev.ua!
0day.kiev.ua##+js(abort-current-inline-script.js, String.fromCharCode, /\/\*[0-9a-f]{40}\*\//)
0day.kiev.ua##+js(abort-on-property-read.js, _mgq)
0day.kiev.ua##[id*="Composite"]
/
!dynamo.kiev.ua!
dynamo.kiev.ua##+js(set-constant.js, JSON.parse, noopFunc)
/
!gismeteo.ua!
gismeteo.ua##+js(set-constant.js, atob, noopFunc)
/
!imgsrc.ru!
imgsrc.ru##+js(abort-current-inline-script.js, parseInt, tabunder)
||imgsrc.ru^$csp=script-src 'self' 'unsafe-inline' *.yandex.ru *.google.com *.cloudflare.com
imgsrc.ru##+js(window.open-defuser.js)
imgsrc.ru##A[href$=".html"][rel="nofollow norefferer noopener"]
/
!auto62rus.ru!
@@||auto62rus.ru^$generichide
/
!dressupmix.ru!
@@||dressupmix.ru^$generichide
/
!teensgames.ru!
@@||teensgames.ru^$generichide
@@||cdnjs.cloudflare.com/ajax/*/fuckadblock.min.js$script,domain=dressupmix.ru|freegamescasual.com|khelnow.com|teensgames.ru
/
!smotret-anime.ru!
smotret-anime.ru##div[style*="opacity: 1; z-index: 9600;"]:style(opacity: 0 !important; pointer-events: none !important;)
||smotret-anime.ru^$csp=media-src *
/
!1snau.ru!
1snau.ru##+js(abort-on-property-read.js, anOptions)
/
!komionline.ru!
komionline.ru##+js(abort-on-property-write.js, adBlockDetected)
/
!turbominer.ru!
turbominer.ru##+js(abort-on-property-write.js, ai_adb_overlay)
/
!allnorilsk.ru!
allnorilsk.ru##+js(abort-on-property-write.js, onload)
/
!bdmbase.ru!
bdmbase.ru##+js(setTimeout-defuser.js, (), 2000)
/
!dnews.dn.ua!
dnews.dn.ua##+js(abort-current-inline-script.js, atob, /\/\*\w{40}\*\/$/)
||dnews.dn.ua/*banner
/
korrespondent.net##+js(set-constant.js, JSON.parse, noopFunc)
tapochek.net##+js(abort-current-inline-script.js, atob, void)
tapochek.net##+js(abort-current-inline-script.js, parseInt, tabunder)
tapochek.net##+js(window.open-defuser.js)
/
hvylya.net##+js(abort-current-inline-script.js, String.fromCharCode, /\/\*[0-9a-f]{40}\*\//)
/
2baksa.net##+js(set-constant.js, sopoof_asidas, true)
/
dok-film.net##+js(abort-on-property-write.js, adBlockDetected)
/
bookfi.net##+js(set-constant.js, atob, noopFunc)
/
kinozal.tv##^script:has-text(676574456c656d656e747342795461674e616d65)
!#if !env_firefox
||piguiqproxy.com/api$xmlhttprequest,redirect=nooptext,domain=kinozal.tv
!#endif

**Reason**: these rules are outdated, and on some sites can lead to the breakdown of their functionality.
**Recent example**: `https://forums.lanik.us/viewtopic.php?f=102&t=36036&p=146295#p146295`
**Suggestion**: when create new posts, about skipping advertising in the **CIS**, 
redirect them please to the forum **RuAdlist**: ` https://forums.lanik.us/viewforum.php?f=102`

Checked with the support of @dimisa-RUAdList
### Versions

- Browser/version: [Opera|Beta]
- uBlock Origin version: [1.18.5rc4]

**Comment by okiehsch** [comment]
About 
`||r.mail.ru^$popup`
That filter was added for a non russian site https://github.com/uBlockOrigin/uAssets/issues/1809#issuecomment-466825920.
Removing it would only make sense if it would break something.

**Comment by mapx-** [comment]
righ t, I'll add
`||r.mail.ru/$popup,domain=estrenos10.com`

**Comment by smed79** [comment]
@mapx-  
The filter you added will have no effect because the popup `r.mail.ru` is opened by the embed video.
`https://my.mail.ru/video/embed/9158856564302417833`

@okiehsch 
It is more appropriate to add the filter to the annoyances list because here it's not about a third party adver and the popup redirect to `my.mail.ru`.

**Comment by mapx-** [comment]
smed did you test in uBo or ABP ?

**Comment by smed79** [comment]
> uBo or ABP

ubo, [https://i.imgur.com/PNHDzBm.png](https://i.imgur.com/PNHDzBm.png)

> it's a popup

@dimisa-RUAdList Does the popup opened by the embed video can be considered as advert?

**Comment by mapx-** [comment]
smed, the filter I added is working fine in uBo. Check again.

**Comment by dimisa-RUAdList** [comment]
@smed79 
This pop-up window leads to the page of direct placement of this video, within the same domain. I do not think this is an advertisement.

**Comment by smed79** [comment]
> Check again.

you're right, I'm wrong.

> I do not think this is an advertisement.

That's what i have said.

**Comment by mapx-** [comment]
It's worse than an advertisment, it's a useless popup.

**Comment by okiehsch** [comment]
I agree that it is not advertising but **every** time one wants to pause the video by clicking the player the popup redirects you to the source of the video, that is more than an annoyance in my opinion.

**Comment by dimisa-RUAdList** [comment]
I agree. I somehow did not notice that this pop-up window appears infinitely, with every click.
https://hg.adblockplus.org/ruadlist/rev/f006f1fa4091

**Comment by smed79** [comment]
I appreciate your patience and indulgence with my insistence :elephant:

**Comment by dimisa-RUAdList** [comment]
Outdated:
```
kaztorka.org##+js(abort-current-inline-script.js, parseInt, 676574456c656d656e747342795461674e616d65)
kaztorka.org##[id*="Composite"]
```

**Comment by mapx-** [comment]
removed

**Comment by dportvine** [comment]
@mapx- 
Outdated:

```adb
dayzmap.ru##+js(nobab)
@@||dayzmap.ru/js/*/adsense.js$script,1p

semestr.ru##+js(nosiif, (), 1000)

@@||anime-365.ru/promo/embed/*$frame,domain=smotretanime.ru

!https://github.com/uBlockOrigin/uAssets/issues/3203#issuecomment-1519854664
my.mail.ru##+js(aopr, AdmanHTML)
my.mail.ru##+js(nowoif, clb670603)
||my.mail.ru/dstat?$image
||ad.mail.ru^$domain=my.mail.ru
*$popup,domain=mail.ru,badfilter

||smotret-anime-365.ru^$csp=script-src * 'unsafe-inline'

rp5.ru##+js(nostif, 0x)

customgames.ru##+js(acis, $, samAdBlockAction) !Fixed in RU AdList

track24.ru##+js(aopr, adBlockDetectet)
track24.ru##+js(set, ab, false)

tiver.ru##+js(aopw, blocked)

woodcraftsman.ru##+js(nosiif, visibility, 1000)

tehnobzor.ru##+js(no-setTimeout-if, mdp)

ipb-board.ru##+js(nostif, .offsetHeight)
ipb-board.ru##.ipsPad.ipsDataList_ciko.ipsWidget_inner

cyberleninka.ru##+js(norafif, getElementById)

imgbase.ru##+js(abort-current-script, JSON.parse, break;case $.)

club-vinyl.ru,empireg.ru,musiklip.ru##+js(abort-current-script, Math, break;case $.)

alimentprofi.ru,igra-tv.ru,krassota.com,pornopissing.ru,shkolazhisni.ru##+js(abort-current-script, document.createElement, 'script')

solnechnyj-kitaj.ru,transformator220.ru,vita-water.ru##+js(aost, String.prototype.charCodeAt, ai_)

nomery.ru##+js(aopw, _pop)

bitcolife.ru##+js(nobab), redirects to: ~> ipoteka-aizhk.ru

!Dead sites
cmp3.ru,mp3-vk.ru,nosong.ru,vkmp3s.ru##+js(acs, JSON.parse, break;case $.)

chuguevforum.com##+js(abort-current-script, document.createElement, 'script')

info-english.ru,pozdravlove.ru##+js(acis, decodeURI, decodeURIComponent)

!!!Although not Russian sites, but these are dead sites.
xendrive.ru##+js(acis, addEventListener, google_ad_client)
xendrive.ru##+js(aopw, adBDetect)

itdplus.ru##+js(nosiif, visibility, 1000)

@@||givemetunes.ru^$ghide

sukatu.ru##+js(aopr, app_vars.force_disable_adblock)
sukatu.ru##+js(nowoif)
sukatu.ru##+js(set, blurred, false)
sukatu.ru##.box-main > p
sukatu.ru##.banner
*$script,frame,3p,denyallow=google.com|gstatic.com|recaptcha.net|hcaptcha.com,domain=sukatu.ru

libangan.ru##+js(abort-current-script, Math, break;case $.)

de-sexy-tube.ru##+js(no-setTimeout-if, window.location.href)

vizstream.ru##+js(aopr, AaDetector)
||vizstream.ru/log/
!!!
```
