### ISSUE TITLE
ig.com.br

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#5118]
### URL(s) where the issue occurs

`https://economia.ig.com.br/empresas/2019-03-09/ford-deve-arcar-com-impactos.html`
`https://esporte.ig.com.br/futebol/internacional/2019-03-12/real-madrid-zidane-contratacoes.html`

### Describe the issue

Clipboard manipulation.

### Versions
Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.4
Firefox 65

**Comment by uBlockIsBest** [comment]
Type in a new tab **about:config** in and disable **dom.event.clipboardevents.enabled**

**Comment by adranger** [comment]
@uBlockIsBest That would break valid uses of clipboard events (e.g. web text editors). The `uBlock filters – Annoyances` list deals with sites that misuse them, and you can report them to this repository.

**Comment by adranger** [comment]
@mapx- please check this again.
