### ISSUE TITLE
Hearst stations

### ISSUE THREAD

**Issue by thow-8838** [uBlockOrigin/uAssets#5119]
### URL(s) where the issue occurs

`https://www.ketv.com/weather` and others, see below

### Describe the issue

Due to the filter `##+js(abort-on-property-read.js, adblockDetector)`, the page scripts stop loading prematurely, causing the content on the page to not be populated with weather information.

### Screenshot(s)

With filter: https://i.imgur.com/gGejTDD.png
Without filter: https://i.imgur.com/b8D6SOS.png

### Versions

- Browser/version: Chrome 72.0.3626.121
- uBlock Origin version: v1.18.4

### Settings

- Added the following custom filter lists: https://i.imgur.com/1LDJs0Z.png

### Notes

This problem also occurs on all of the following sites:

```
4029tv.com/weather
kcci.com/weather
kcra.com/weather
kmbc.com/weather
koat.com/weather
koco.com/weather
mor-tv.com/weather
mynbc5.com/weather
wapt.com/weather
wbaltv.com/weather
wcvb.com/weather
wdsu.com/weather
wesh.com/weather
wgal.com/weather
wisn.com/weather
wjcl.com/weather
wlky.com/weather
wlwt.com/weather
wmtw.com/weather
wmur.com/weather
wpbf.com/weather
wtae.com/weather
wvtm13.com/weather
wxii12.com/weather
wyff4.com/weather
```

due to the following rule in the filter list:

`4029tv.com,kcci.com,kcra.com,ketv.com,kmbc.com,koat.com,koco.com,mor-tv.com,mynbc5.com,wapt.com,wbaltv.com,wcvb.com,wdsu.com,wesh.com,wgal.com,wisn.com,wjcl.com,wlky.com,wlwt.com,wmtw.com,wmur.com,wpbf.com,wtae.com,wvtm13.com,wxii12.com,wyff4.com##+js(abort-on-property-read.js, adblockDetector)`

**Comment by mapx-** [comment]
Could you test again the sites first adding:
```
4029tv.com,kcci.com,kcra.com,ketv.com,kmbc.com,koat.com,koco.com,mor-tv.com,mynbc5.com,wapt.com,wbaltv.com,wcvb.com,wdsu.com,wesh.com,wgal.com,wisn.com,wjcl.com,wlky.com,wlwt.com,wmtw.com,wmur.com,wpbf.com,wtae.com,wvtm13.com,wxii12.com,wyff4.com#@#+js(abort-on-property-read.js, adblockDetector)
4029tv.com,kcci.com,kcra.com,ketv.com,kmbc.com,koat.com,koco.com,mor-tv.com,mynbc5.com,wapt.com,wbaltv.com,wcvb.com,wdsu.com,wesh.com,wgal.com,wisn.com,wjcl.com,wlky.com,wlwt.com,wmtw.com,wmur.com,wpbf.com,wtae.com,wvtm13.com,wxii12.com,wyff4.com##+js(setTimeout-defuser.js, (), 500)
```

**Comment by thow-8838** [comment]
@mapx- This fixed the issue. Thank you so much!
