### ISSUE TITLE
dailymail.co.uk

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#512]
Banners in the sidebars and below the header on `http://www.dailymail.co.uk`.

**SS:** https://i.imgur.com/asWBBrI.png

**Error URL:**
`http://www.dailymail.co.uk/health/article-4684782/Brain-dead-pregnant-woman-21-kept-alive-123-days.html`

They seem to be using an inline script to display the app banners.

_**Note:** Using uBO 1.13.2 on Chrome 59 with the default filters and settings._

**Comment by okiehsch** [comment]
Does 
`dailymail.co.uk##script:inject(abort-on-property-write.js, s_adblock)`
work for you?

**Comment by gotitbro** [comment]
@okiehsch Yes, the above filter works for me and stops the banners from loading.

This is an interesting way to implement anti adb, they are driving visitors to install their Windows app where adblocking is not a major possibility.

**Comment by terrorist96** [comment]
### URL(s) where the issue occurs

`https://www.dailymail.co.uk/news/article-6780303/Incredible-newly-restored-footage-shows-terrifying-power-1953-nuclear-bomb-tests.html`

### Describe the issue

Video at bottom broken

### Notes

`@@ima3.js`

**Comment by mapx-** [comment]
Which video .. the page is huge, tried some but no breakage here

**Comment by terrorist96** [comment]
At the very bottom.
![image](https://user-images.githubusercontent.com/12802056/53971065-174cee80-40ca-11e9-94ad-c3a63c3e8e86.png)

**Comment by terrorist96** [comment]
<details><summary>Logger output</summary>

```
+1
/ima3.js
--
www.dailymail.co.uk
3
script
https://imasdk.googleapis.com/js/sdkloader/ima3.js
```
```
+0
/ima3.js
--
www.dailymail.co.uk
3
script
https://imasdk.googleapis.com/js/sdkloader/ima3.js
```
```
+0
https://www.dailymail.co.uk/news/article-6780303/Incredible-newly-restored-footage-shows-terrifying-power-1953-nuclear-bomb-tests.html
```
</details>

**Comment by mapx-** [comment]
working fine that video here FF / chrome.

**Comment by terrorist96** [comment]
Is `https://imasdk.googleapis.com/js/sdkloader/ima3.js` in your logs? Whitelisting that for me fixes the video.

**Comment by mapx-** [comment]
yep, it is, blocked, but ... still working here

**Comment by mapx-** [comment]
let's waiting for other tests, other users etc

**Comment by terrorist96** [comment]
Actually now I'm getting inconsistent results. Sometimes the video loads, sometimes it doesn't, regardless of whitelisting `ima3.js`. Let me see if I can narrow it down..

**Comment by terrorist96** [comment]
I think the site just sucks at loading it.

**Comment by smed79** [comment]
> let's wait for other tests

* I can play the video with ABP https://vgy.me/bS3xlb.png

* No video with uBo https://vgy.me/7T01Dh.png
Issue caused by `dailymail.co.uk##+js(abort-on-property-read.js, I11C)`
Vid: https://streamable.com/e/xw7f6/tdommr

**Comment by mapx-** [comment]
I tested again uk ip and non uk ip, chrome / FF => the video is ok, playable for me

**Comment by smed79** [comment]
The video only if i disable **uBlock filters** https://imgur.com/a/0ARtL42
or if i add `dailymail.co.uk##+js(abort-on-property-read.js, I11C)` https://imgur.com/a/C8n2DmP

**Comment by okiehsch** [comment]
I can reproduce the breakage using Chromium and a UK IP and 
`dailymail.co.uk##+js(abort-on-property-read.js, I11C)`
is causing it.
I don't get any Instart Logic redirection, so removing that filter seems to cause no issue on my end.

**Comment by mapx-** [comment]
maybe because I'm using chrome beta

**Comment by okiehsch** [comment]
Do you have any issues if you remove
`dailymail.co.uk##+js(abort-on-property-read.js, I11C)`

**Comment by mapx-** [comment]
no problems here
