### ISSUE TITLE
reevown.com

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#5121]
### URL(s) where the issue occurs

`[https://reevown.com/]`

### Describe the issue

[Anti-adblock when you move your mouse to the `download file` button.]

### Versions

- Browser/version: [Chrome v72]
- uBlock Origin version: [1.18.4]

### Settings

- [Default]

**Comment by okiehsch** [comment]
Hm, looks like a bug on my end.
It works with Firefox, the only way to "fix" it with Chrome is to disable cosmetic filtering but that should make no difference because we already use generichide for the site and there are no specific cosmetic filters that I can find.
@mapx- can you reproduce?

**Comment by dumbusernameidk** [comment]
For chrome the anti-adblock still appears even with cosmetic filtering off.

**Comment by okiehsch** [comment]
I just updated my post, but I can't reproduce.

**Comment by dumbusernameidk** [comment]
strange i can reproduce consistently on both chrome and firefox. does the site let you move your mouse to the download file button?

**Comment by okiehsch** [comment]
Yes, the download button  dissapears for a few seconds and the reappears and I can click it without issue.
Looks like a site issue to me and not anti-adblock related.

**Comment by mapx-** [comment]
Same here (button disappearing included - only in chrome).

**Comment by dumbusernameidk** [comment]
This is what i get:

`https://gyazo.com/b23dadeca0f3a808f9e7575f1c18a712`

Alternatively can produce a similar type page by disabling inline scripts.

**Comment by okiehsch** [comment]
> This is what i get

That I can't reproduce.

**Comment by dumbusernameidk** [comment]
I'm not sure then maybe region specific? Although that would be an oddity.

**Comment by okiehsch** [comment]
The only way for me to reproduce your screenshot is to block
`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js`

I don't think such a site would use a geo-dependent ant-adblock detection.

**Comment by dumbusernameidk** [comment]
i'm not sure then i've whitelisted all 1p and 3p stuff on the site including turning off cosmetic filtering. still getting the anti-adb.

**Comment by okiehsch** [comment]
If you get the detection message even if you disable uBO it's either a faulty detection or another extension you use causes it.

**Comment by dumbusernameidk** [comment]
faulty most likely i disabled every extension and it still appeared.
