### ISSUE TITLE
www.symbolab.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#5124]
```
https://www.symbolab.com/solver/functions-calculator/68480%2F%5Cleft(2%2F24%2F365%5Cright)%3D1953518059%2Fx
```

Annoyance anti-adblock:

 
![obraz](https://user-images.githubusercontent.com/35370833/54316966-3e338500-45e2-11e9-85fe-bb1b1a0153a8.png) |
--- |

Fix in ND list:

![obraz](https://user-images.githubusercontent.com/35370833/54317013-64f1bb80-45e2-11e9-92d3-211676564f1a.png) |
--- |

AG: https://github.com/AdguardTeam/AdguardFilters/issues/11273
Fanboy's Enhanced Tracking List: https://github.com/ryanbr/fanboy-adblock/commit/e4b73d005667642b266b23efe0d3de612b89ba3f

**Comment by okiehsch** [comment]
I will fix it in `uBO-filters`, the message hides content after every reload

**Comment by krystian3w** [comment]
No problem.

**Comment by Crystal-RainSlide** [comment]
On `https://zs.symbolab.com/` and 
`https://www.symbolab.com/solver/order-of-operations-calculator` :

```
symbolab.com###googleAdSenseHomepage
symbolab.com##.googleAdsense
```

**BUT**, when I disable uBlock filters, I can't see this popup.
Then I see this entry in Fanboy’s Enhanced Tracking List in the logger:

```
symbolab.com##.tooltipster-show
```

By querySelector-ing `.tooltipster-show`, I reached its HTML code:

``` HTML
<!-- Beautified, style attribute stripped -->
<div class="tooltipster-base tooltipster-sidetip tooltipster-light tooltipster-top tooltipster-fade tooltipster-show" id="tooltipster-xxxxxx">
	<div class="tooltipster-box">
		<div class="tooltipster-content">
			<div class="sy-tooltip-content">
				<div>
					<div class="abmsg">Please do not run ad blocker on this site,<br> <a class="clickable a-underline" onclick='showSignUp("AdBlock", true);'>upgrade</a> is available to remove ads</div>
				</div>
				<a class="nl-smallGrayButton">Got it</a>
			</div>
		</div>
	</div>
	<div class="tooltipster-arrow">
		<div class="tooltipster-arrow-uncropped">
			<div class="tooltipster-arrow-border"></div>
			<div class="tooltipster-arrow-background"></div>
		</div>
	</div>
</div>
```

By searching a class of this popup, `abmsg`, in
`https://www.symbolab.com/public/auto/solutions.min.js`,
I reached this snippet:

``` JavaScript
// Beautified
if (
	!SOLUTIONS.subscribed &&
	a.getScrollHeight('.googleAdsense .adsbygoogle')         < 100 &&
	a.getScrollHeight('.googleAdsenseMiddle .adsbygoogle')   < 100 &&
	a.getScrollHeight('.googleLeftSkyScrapper .adsbygoogle') < 100
) {
	if ( $('#multipleSolutions').height() > 10 ) {
		showPointOfInterest(
			$('.solution_step_list_item:first'),
			'<div class=\'abmsg\'>Please do not run ad blocker on this site,\
			<br/> <a class=\'clickable a-underline\' onclick=\'' + (
				!a.udid
					? 'showSignUp("AdBlock", true);'
					: 'showSubscription("AdBlock");'
			) + '\'>upgrade</a> is available to remove ads</div>',
			{
				side: 'top',
				actionable: true,
				isDismissed: function() { return false },
				onDismiss: function() {
					symbolab_log('Solutions', 'DismissAdBlockTooltip')
				}
			}
		);
		symbolab_log('Solutions', 'ShowAdBlockTooltip')
	}
}
```

Refining the common rules:

```
symbolab.com###googleAdSenseHomepage
symbolab.com##.googleAdsense
symbolab.com##.googleAdsenseMiddle
symbolab.com##.googleLeftSkyScrapper
```

After all, it seems that `symbolab.com##.tooltipster-show` will also hide
other popups make by this `showPointOfInterest` function, or
[tooltipster](https://iamceege.github.io/tooltipster/).

While any of the rules below will effectively _only_ unseen the adblock warning popup:

```
symbolab.com##.tooltipster-show:has(.abmsg)
symbolab.com##+js(set, SOLUTIONS.subscribed, true)
```

Continue. I tracked down the `symbolab_log()` function.

``` JavaScript
function symbolab_log(b, d, c, a) {
	if (!a) {
		a = null
	}
	return $.ajax({
		type: 'POST',
		url: '/detailedLog',
		data: {
			type: b,
			info1: d,
			info2: c,
			query: a
		}
	})
}
```

Thus, another entry for privacy lists:

```
||symbolab.com/detailedLog$xhr
```

I confirmed everything upon on Firefox.

## Conclution

Add:

```
symbolab.com###googleAdSenseHomepage
symbolab.com##.googleAdsense
symbolab.com##.googleAdsenseMiddle
symbolab.com##.googleLeftSkyScrapper
```

Add one of them:

```
symbolab.com##.tooltipster-show:has(.abmsg)
symbolab.com##+js(set, SOLUTIONS.subscribed, true)
```

Add this to the privacy list:

```
||symbolab.com/detailedLog$xhr
```

Remove:

```
@@||symbolab.com^$ghide
```

Will report to Easylist & Easy Privacy, to add compatable rules onto those larger lists.
Will report to fanboy to enhance the rule, `symbolab.com##.tooltipster-show`, in Enhanced Tracking List, if possible.

**Comment by llacb47** [comment]
Why should this be removed?? `@@||symbolab.com^$generichide` This is taking care of anti-adblock. The only issue I see is the "detailedLog", which is not detailed at all.
![image](https://user-images.githubusercontent.com/16567977/78043601-8e8e9980-7341-11ea-9c79-d42a881564a9.png)

**Comment by krystian3w** [comment]
Maybe like race condition generated with `set-constant`.

**Comment by Crystal-RainSlide** [comment]
My idea is the anti-adblock can be simplely muted without `generichide` and your's should be that, this anti-adblock can be simplely masked with `generichide`.
That's OK, I only concerns that, generic hide rules may act well on some other elements like cookie warnings, so I prefers uBlock Origin's `:has` or `+js(set)` to `generichide`.
Tiny difference here actually.
