### ISSUE TITLE
assets.adobedtm.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#5125]
### URL(s) where the issue occurs

`https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3316573`

### Describe the issue

Click `Show Contact Information` then click `(email)`. Won't work.

### Notes

`@@||assets.adobedtm.com` fixes it. I've also noticed this issue on other websites where `mailto` email links do not work.

**Comment by okiehsch** [comment]
If you can remember the other websites just mention them here and I will add them to the fix.
