### ISSUE TITLE
es.wallapop.com

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#5127]
### URL(s) where the issue occurs

`https://es.wallapop.com/`

### Describe the issue

Breakage, suggested filter
`@@||cdn.taplytics.com/taplytics.min.js$script,domain=es.wallapop.com`

### Screenshot(s)

![Anotación 2019-03-14 183128](https://user-images.githubusercontent.com/27441315/54378603-eb140d80-4687-11e9-97d9-4de3b5968897.png)

### Versions

- Browser/version: Chrome 72
- uBlock Origin version: 1.18.8

### Settings

- Default settings.

**Comment by mapx-** [comment]
test (trying to kill at least part of what the script is doing) ad see if breaks something else
- I can note a little delay with the injecting filter
```
@@||cdn.taplytics.com/taplytics.min.js$script,domain=es.wallapop.com
es.wallapop.com##+js(abort-on-property-read.js, Date.prototype.toUTCString)
```

**Comment by lain566** [comment]
Can't click on the button to accept cookies

![Anotación 2019-03-14 185850](https://user-images.githubusercontent.com/27441315/54380223-4398da00-468b-11e9-9c85-e4fd82ed38e2.png)

**Comment by mapx-** [comment]
right, I'll add the filter above
