### ISSUE TITLE
theverge.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#5131]
### URL(s) where the issue occurs

`https://www.theverge.com/2019/3/14/18261915/tesla-model-y-announcement-live-stream-how-to-watch-elon-musk-date-time`

### Describe the issue

Twitter embedded images broken.

### Notes

`@@||pbs.twimg.com`

**Comment by stephenhawk8054** [comment]
Article audio (`Listen to this article` part) is missing.

URL:
`https://www.theverge.com/2022/1/7/22869528/norton-crypto-miner-security-software-reaction`

<details>
<summary>Expect</summary>

![image](https://user-images.githubusercontent.com/66517106/148643591-2d5e611b-9270-4433-a5ce-ea68a1b8a581.png)

</details>

<details>
<summary>Issue</summary>

![image](https://user-images.githubusercontent.com/66517106/148643598-1a2b252b-aff7-41d2-8601-3f1b22fdb18b.png)

</details>
<details>
<summary>Configuration</summary>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 77510
  cosmetic: 40392
  scriptlet: 16391
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30662-143, 55m
    ublock-badware: 3652-1, 55m
    ublock-privacy: 183-0, 55m
    ublock-abuse: 76-0, 55m
    ublock-unbreak: 1723-0, 55m
    easylist: 62783-468, 2h.11m
    easyprivacy: 26605-481, 55m
    urlhaus-1: 6782-0, 55m
    plowe-0: 3685-2, 55m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 210 ms (selfie)
popupPanel: 
  blocked: 21
```
</details>

Proposed filter:

`@@||cdn.vox-cdn.com/packs/js/concert_ads-*.js$script,domain=theverge.com`

**Comment by mapx-** [comment]
@ryanbr
