### ISSUE TITLE
twitch.tv

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#5138]
@mapx- @okiehsch @gorhill I feel bad, I see an advertisement
https://imgur.com/I7TK3RM

Extension: uBlock Origin 1.18.8
Browser: on the 1th `gif` Waterfox 56.2.7.1 (64-bit) (on the 2th `gif` Waterfox 56.2.8 (64-bit)), but on Firefox 65.0.2 (64) the same situation
~in (nasty) Opera everything is normal~

@mapx- So that there is no misunderstanding and wrong criticism (from our last conversation) I completely deleted my entire Waterfox profile and created a new one, right before your eyes. Look https://imgur.com/2gGBhhs
~And please do not say anything about other browsers. I checked in the opera there is no advertising. Cool. Surely in chrome, too, it is not. I am glad. But I am from this information neither cold nor hot. I do not want to use chrome. **I am only interested in Firefox based browsers**. Thank you for understanding.~

I am a Slowpoke, it turns out there are already topics on reddit (although there is just a discussion):
https://old.reddit.com/r/uBlockOrigin/comments/b1845y/ublock_no_longer_working_on_twitch_screenshot/
https://old.reddit.com/r/uBlockOrigin/comments/b1kf2e/i_think_twitch_just_changed_their_ad_system/

**Comment by gorhill** [comment]
Just to be sure, can you try with the latest dev build?

**Comment by bogachenko** [comment]
@gorhill no problem dude, i tried it. there is advertising
![Безымянный](https://user-images.githubusercontent.com/8535285/54477234-da85a380-47fd-11e9-8d59-85565290a0e1.png)

**Comment by bogachenko** [comment]
@gorhill By the way. In the topic threads, I wrote that is in the Opera is blocked, and so, I take my words back. In Opera (only that checked), too, there is advertisements. The problem is the scriptlet, I think.

**Comment by pixeltris** [comment]
I'm blind and didn't see this issue, I wrote some info on a workaround 
[here](https://github.com/streamlink/streamlink/issues/2357#issuecomment-473565335) with an accompaning url for userResourcesLocation https://gist.githubusercontent.com/pixeltris/1338ad540175499b90b3dc245de663be/raw/58154403783563f0370dd7a39bc1517c39a81c7c/gistfile1.txt I'm not sure if this workaround will work for long though.

**Comment by bogachenko** [comment]
@pixeltris Bro does not work. there is advertising

**Comment by lain566** [comment]
> I'm blind and didn't see this issue, I wrote some info on a workaround
> here with an accompaning url for userResourcesLocation https://gist.githubusercontent.com/pixeltris/1338ad540175499b90b3dc245de663be/raw/58154403783563f0370dd7a39bc1517c39a81c7c/gistfile1.txt I'm not sure if this workaround will work for long though.

It seems to work, I'm using Firefox and Chrome in incognito mode and I don't see pre roll ads, I used to get ads, now I do not.

**Comment by lain566** [comment]
@gorhill A small recording using chrome with uBO enabled and then in guest mode (no extensions) I get pre roll. The pixeltris workaround should be added.
https://vgy.me/u/MkfwEd

**Comment by bogachenko** [comment]
Checked on Firefox. It seems to work. There is no advertising.

It is unlikely that it will last long.

**Comment by gorhill** [comment]
Is `_` an officially supported value? What would be an officially supported value to make the fix less conspicuous server-side?

**Comment by pixeltris** [comment]
`platform` seems to be the only thing that impacts the ads showing, `player_type` / `baking_brownies` etc don't seem to have an impact now. I'm not sure if there is any official `platform` where ads aren't served. I'm not sure what the official `platform` values are but I assume it covers things like PS4, Xbox, etc (where ads are probably still shown).

**Comment by gorhill** [comment]
@pixeltris I created a new Gist based on the supplementary information you provide -- I removed most of the code but kept only the rewriting of `platform`. Here it is:

https://gist.githubusercontent.com/gorhill/da820c66af175d6c706ec95a5d99958a/raw/9e56176abf7b2c1e13cf999aaf878e8ee5c0ae02/twitch-videoad.js

Can people provide feedback as to whether this still works fine?

**Comment by cioaciaoicoaicoiaocioai** [comment]
Me and a lot of friends of mine have this issue! Twitch displays ads while using uBlock Origin.

**Comment by lain566** [comment]
@gorhill Works the same, I can reproduce ads easily, and adding your scriptlet I don't see ads
https://vgy.me/u/vhN9eK
