### ISSUE TITLE
Bitdefender picking up an Infected Web Resource from uBlockOrigin

### ISSUE THREAD

**Issue by Ankahra** [uBlockOrigin/uAssets#5139]
### URL(s) where the issue occurs

URL in issue: raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt?_=215656 

Several others also having this recently occur on a reddit post about the issue: https://www.reddit.com/r/uBlockOrigin/comments/b1lk0g/strange_ublock_related_hit_in_my_antivirus/

### Describe the issue

The past 24H Bitdefender has been repeatedly getting these hits of an infected web resources and attempting to block a page from this very Github, I'm unsure if it's an actual issue or it's doing anything bad (Hoping to get answers on whether it is!).

### Screenshot(s)

Image of the Bitdefender notification that comes up: https://i.gyazo.com/5739d86a4b257aa095a9e6eadc9fbcc2.png

### Versions

- Browser/version: Version 72.0.3626.121
- uBlock Origin version: 1.18.8

### Settings

Default I believe.

### Notes

N/A, hoping to find answers on whether is something dangerous that needs further attention.

**Comment by mapx-** [comment]
see also
https://www.reddit.com/r/uBlockOrigin/comments/b0579i/bitdefender_detected_web_threat_from_ublockorigin/

However, it's a not very intelligent approach on Bitdefender side which should act on **accessing** a certain dangerous link / page (like those listed in resource-abuse **text** file) and not **reading a list** including those links.

So, a simple false positive. You should be able in Bitdefender to exclude 
https://github.com/uBlockOrigin/uAssets/blob/master/filters/resource-abuse.txt
from Bitdefender scanning.
