### ISSUE TITLE
vev.io popups in firefox android

### ISSUE THREAD

**Issue by fightthepower** [uBlockOrigin/uAssets#5140]
### URL(s) where the issue occurs
Note: These video links are episodes to sons of anarcy and game of thrones full episodes.
```
https://vev.io/g9vrg86zeoz1 
https://vev.io/9jo1gp5vvpoe
```

### Describe the issue
I already mentioned my problem here https://github.com/uBlockOrigin/uBlock-issues/issues/460

### Versions

- Browser/version: Firefox-android latest
- uBlock Origin version: Latest

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes
I opened issue here because they  flaged this as a filter issue and I dont have any way to open or write on that issue.

**Comment by mapx-** [comment]
test these filters
```
vev.io##+js(set-constant.js, console.clear, trueFunc)
vev.io##+js(set-constant.js, __INITIAL_STATE__.ads, undefined)
```

**Comment by mapx-** [comment]
it's about android

**Comment by bogachenko** [comment]
yes I know.  but suddenly he forgot to do it at all.

**Comment by bogachenko** [comment]
but not. I take my words back. on android. this filter 
`vev.io##+js(window.open-defuser.js)`
is not working.
I'll check your filters now

**Comment by bogachenko** [comment]
your filters work. I checked.

**Comment by mapx-** [comment]
Let's wait @fightthepower  test too

**Comment by ghajini** [comment]
Nothing popups on android, not requiring said filters

**Comment by mapx-** [comment]
I got the popups using an android emulator

**Comment by fightthepower** [comment]
Can't test anyting now; vev.io started detecting and blocking uBlock now.

**Comment by bogachenko** [comment]
@mapx- again popups

**Comment by mapx-** [comment]
test 
`vev.io##+js(addEventListener-defuser, /^(?:click|mousedown|mouseup)$/, di())`

**Comment by bogachenko** [comment]
This breaks the playback of the player.

**Comment by mapx-** [comment]
Do you have a valid video page ?

**Comment by bogachenko** [comment]
NSFW `https://vev.red/qnoxpq6e1y30`

**Comment by mapx-** [comment]
test
```
vev.*##+js(addEventListener-defuser.js, /^(?:click|mousedown|mouseup)$/, di())
vev.*##+js(set-constant, console.clear, trueFunc)
@@||vev.*^$generichide
*$frame,3p,domain=vev.io|vev.red
||vev.*/sw.js$script,1p

vev.io#@#+js(addEventListener-defuser.js, /^(?:click|mousedown|mouseup)$/, hi())
vev.io#@#+js(addEventListener-defuser.js, adb.updated)
vev.io#@#+js(window.open-defuser.js)
vev.io#@#+js(set-constant.js, __INITIAL_STATE__.ads, undefined)
```

and see if the other mirrors are fixed using similar filters

**Comment by bogachenko** [comment]
it works

**Comment by ghajini** [comment]
`https://vidop.icu/enmnxz6pqw53`
player saying `disable adblock for a faster streaming speed`
is that true? or nuisance

**Comment by dumbusernameidk** [comment]
@mapx- Possible to break debugger trap on vidop.icu?

**Comment by okiehsch** [comment]
`vidop.icu##+js(noeval.js)`

**Comment by dumbusernameidk** [comment]
vev.red needs update it has popups + yellow lines in the video labeled "ad break" though this doesn't trigger for me. also if you select the video player and try to reload you get "changes might not be saved" popup.

here's a link with that player it's labeled "thevideo" `https://watchpornfree.info/the-dark-lady-watch-online-free`

**Comment by ghajini** [comment]
Firefox android stable
Ublock origin 1.27.11rc2

There are 2 issues
1.
Popup ads, antiadblock here
**NSFW**
`https://vev.red/1lokzjz0vnok`

https://user-images.githubusercontent.com/20338483/85122197-cb34a780-b243-11ea-823b-b2aefc246fea.jpg

2.
Video don't play here despite clicking play button several times

`https://vev.io/9jo1g4vym7oe`

**Comment by mapx-** [comment]
test
`vev.*##+js(nowoif, /^/, 1)`

You have to click 4-5 times to get the video running

**Comment by ghajini** [comment]
Sure it work...
3rd party xhr
`||cldom.com^`

**Comment by dumbusernameidk** [comment]
still have issue of "reload site? changes might not be saved" popup

**Comment by ghajini** [comment]
In opera it occurs. ...when opera blocks insecure content and then you allow that, opera asks like that
