### ISSUE TITLE
Anti-Adblock Virgin Media Player

### ISSUE THREAD

**Issue by germaloney11** [uBlockOrigin/uAssets#5141]
### URL(s) where the issue occurs

`https://www.virginmediatelevision.ie/player/live/`

### Describe the issue

Anti-adblock on Virgin Media Player - Location is Ireland

### Screenshot(s)

`https://i.imgur.com/Vxd0Fxm.png`

### Versions

- Browser/version: Version 72.0.3626.121 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.18.8

**Comment by germaloney11** [comment]
The player is stuck up at the top and ads still play on the videos.
Eg. `https://i.imgur.com/f4bMKvq.mp4`


There are three live channel players:

`https://www.virginmediatelevision.ie/player/live/virgin-media-one`

`https://www.virginmediatelevision.ie/player/live/virgin-media-two`

`https://www.virginmediatelevision.ie/player/live/virgin-media-three`

**Comment by germaloney11** [comment]
Would you mind also having a look at the non-live player when you get a chance please. Not anti-adblock, just playing ads.

`https://www.virginmediatelevision.ie/player/show/626`

**Comment by mapx-** [comment]
are you using fanboy's cookies list or annoyances ?

**Comment by mapx-** [comment]
these should fix both issues
```
@@||virginmediatelevision.ie/includes/js/cookienotice.js.pagespeed.$script,1p
||damoh.curloc.com/$media,redirect=noopmp3-0.1s,domain=virginmediatelevision.ie
```

The first should be fixed in fanboy's list @ryanbr 
For now I'll add it to ublock lists

**Comment by germaloney11** [comment]
> are you using fanboy's cookies list or annoyances ?

Yes I was.

Thanks for your help!

**Comment by germaloney11** [comment]
Ad's still playing on this site.

Eg. https://www.virginmediatelevision.ie/player/show/1718/0/0/Pat-Kenny%27s-Big-Debate

**Comment by okiehsch** [comment]
`||damoh.virginmediatelevision.ie^$media,1p,redirect=noopmp3-0.1s`
works on my end.

**Comment by germaloney11** [comment]
||damoh.virginmediatelevision.ie^$media,1p,redirect=noopmp3-0.1s


> `||damoh.virginmediatelevision.ie^$media,1p,redirect=noopmp3-0.1s`
> works on my end.

Yes also works on my end. Thank you.
