### ISSUE TITLE
Autoplay eagleplatform.com (gazeta.ru, lenta.ru, rambler.ru)

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#5142]
Is it possible with the help of uBlock Origin to block the autoplay here:
https://www.gazeta.ru/culture/2019/03/14/a_12242587.shtml
https://lenta.ru/news/2019/03/16/piggy/
https://news.rambler.ru/starlife/41881477-doktor-vynes-svoy-verdikt-tyazhelobolnoy-nachalovoy/
???

**Comment by krystian3w** [comment]
```
ru##+js(remove-attr.js, autoplay, video[id^="eagleplayer-video"])
```

?

**Comment by okiehsch** [comment]
Does not work on my end, go to
````
https://gazeta.media.eagleplatform.com/index/player?record_id=1221426&player_template_id=9318
````
is easier to test the issue but I don't see how to stop the video from auto-starting without breaking it using uBO-filters.

**Comment by dimisa-RUAdList** [comment]
I'm trying to do it like at RU AdList JS Fixes: https://greasyfork.org/ru/scripts/19993-ru-adlist-js-fixes/code
