### ISSUE TITLE
prestigedigital.net

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#5143]
### URL(s) where the issue occurs

`https://www.prestigedigital.net/`

### Describe the issue

Unblocked doubleclick banner ad.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/54479576-7d392480-47f4-11e9-8fad-12b3eeb6c87d.png)

**Comment by mapx-** [comment]
add
`prestigedigital.net##[href^="http://googleads.g.doubleclick.net/pcs/click"]`

@ryanbr
