### ISSUE TITLE
[NSFW] stream-mydirtyhobby.co

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#5145]
`https://www.stream-mydirtyhobby.co/video/44349/lovelylani-extrem-blasen`

antiadb + shitty popups
@mapx- Sensei Pls

**Comment by mapx-** [comment]
I get neither popups nor anti adb

**Comment by bogachenko** [comment]
opera. standard settings and filters. gif write?

**Comment by mapx-** [comment]
opera + default settings still no popup / antiadb

what is "gif write" ?

**Comment by bogachenko** [comment]
> what is "gif write" ?

I can record a gif as proof.

**Comment by mapx-** [comment]
- You should see in the logger what player / frame is playing the video, it's not always the same
- eventually post here directly the frame link

**Comment by bogachenko** [comment]
I'd better find another site, but thanks anyway for responding.
