### ISSUE TITLE
t-online.de [broken page]

### ISSUE THREAD

**Issue by team647** [uBlockOrigin/uAssets#5146]
### URL(s) where the issue occurs

`https://www.t-online.de/`

### Describe the issue

Broken page, it doesnt show pictures

### Screenshot(s)

![picture23637](https://user-images.githubusercontent.com/48632922/54481954-03c52480-483c-11e9-95d2-42506927c230.PNG)

### Versions

- Browser/version: 65.0.2
- uBlock Origin version: v1.18.6

### Settings

- default

### Notes

The new filter `t-online.de##.Tgboxh` breaking the page.
Its the filter from `https://github.com/uBlockOrigin/uAssets/commit/9af3c1df7ab37538efcb3df6952817e72106c9cc`

**Comment by okiehsch** [comment]
Thanks.
