### ISSUE TITLE
t-online.de [broken page 2]

### ISSUE THREAD

**Issue by team468** [uBlockOrigin/uAssets#5147]
### URL(s) where the issue occurs

`https://www.t-online.de/`

### Describe the issue

Broken page, it doesnt show pictures (scroll down to see that)

### Screenshot(s)

![Unbenannt](https://user-images.githubusercontent.com/48633919/54482313-cf546700-4841-11e9-8124-b7362c901a0b.PNG)

### Versions

- Browser/version: Firefox 65.0.2
- uBlock Origin version: v1.18.6

### Settings

- default

### Notes

The new Filter `t-online.de##^script:has-text((window);)` breaking the page. Its the new Filter from `https://github.com/uBlockOrigin/uAssets/commit/9af3c1df7ab37538efcb3df6952817e72106c9cc` 
Sorry for late reporting

**Comment by okiehsch** [comment]
Thanks for reporting, there is no need to open new issues for `t-online.de` if you find additional problems you can just comment on a closed one.

**Comment by team468** [comment]
> 
> 
> Thanks for reporting, there is no need to open new issues for `t-online.de` if you find additional problems you can just comment at a closed one.

ok, i do that next time. have a great day
