### ISSUE TITLE
sephora.com EasyPrivacy false positive

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#515]
### URL(s) where the issue occurs

`sephora.com`

### Describe the issue

Hover your mouse over the SHOP tab. Nothing happens if EasyPrivacy is enabled. Other tabs are unaffected.

### Versions

- Browser/version: Chrome 59
- uBlock Origin version: 1.13.2

### Settings

Default

**Comment by terrorist96** [comment]
`https://www.sephora.com/beauty/new-beauty-products`
Product list doesn't load.
`@@||edge1.certona.net/cd/*$script,domain=sephora.com`

**Comment by terrorist96** [comment]
Banner with promo code for sale doesn't load. Need to add: @@||sephora.com/js/ufe/isomorphic/thirdparty/VisitorAPI.js$domain=sephora.com
@mapx- @ryanbr

**Comment by mapx-** [comment]
where is that banner ?

**Comment by terrorist96** [comment]
> where is that banner ?

At the very top.
