### ISSUE TITLE
Pre Video ads

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5153]
### URL(s) where the issue occurs

`https://www.kabeleins.de/tv/mein-lokal-dein-lokal/videos/201862-im-rossini-gibt-es-italienisches-essen-nach-mamas-art-ganze-folge`
`https://www.sat1gold.de/tv/niedrig-und-kuhnt/video/5109-staffel-5-episode-109-jeder-gegen-jeden-ganze-folge`
`https://www.vox.de`

### Describe the issue

Pre Video ads, ads in the video

### Screenshot(s)

<img width="1335" alt="picture36870" src="https://user-images.githubusercontent.com/48647394/54490759-0154e000-48b9-11e9-944c-22861c9d7bb6.PNG">
<img width="879" alt="picture30689" src="https://user-images.githubusercontent.com/48647394/54490760-0154e000-48b9-11e9-81dd-b99c32e61ce3.PNG">

### Versions

- Browser/version: Firefox 65.0.2
- uBlock Origin version: v1.18.6

### Settings

- 
[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/2975123/Settings.txt)

### Notes

`||cdn.zomap.de^$media,redirect=noopmp4-1s,domain=kabeleins.de`
`||cdn.zomap.de^$media,redirect=noopmp4-1s,domain=sat1gold.de`
`||damoh.vox.de^$media,redirect=noopmp4-1s,domain=vox.de`
works for me. When these sites use Geolock, please use a german proxy. When no ad appear, please skip to the middle or to the end of the video, its like youtube. On Vox.de please scroll down and select a vid.

**Comment by JobcenterTycoon** [comment]
I get breakage on `https://www.vox.de/cms/videos.html` the video gets blank after the ad got skipped

**Comment by mapx-** [comment]
test

```
||damoh.vox.de^$media,redirect=noopmp4-1s,domain=vox.de,badfilter
vox.de##+js(no-xhr-if, svon)
```

**Comment by JobcenterTycoon** [comment]
yes works perfectly
