### ISSUE TITLE
BitDefender blocked raw content.

### ISSUE THREAD

**Issue by alwarren** [uBlockOrigin/uAssets#5154]
### URL(s) where the issue occurs

`https://wiseass.slack.com/messages/C5GNZPYGP/`

### Describe the issue

It's difficult to pointoint exactly where the issue came from as it was produced by BitDefender. The only website I was viewing at the time was a slack channel.

BitDefender blocked the following:

`raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt?_=215671`

### Screenshot(s)

See attached screenshot.
![Capture](https://user-images.githubusercontent.com/1012590/54493669-97304100-48a0-11e9-8732-5059b0d1e8a1.PNG)

### Versions

- Browser/version: FireFox 65.0.2
- uBlock Origin version: 1.18.6

### Settings

- All settings default.

### Notes

I examined resource-abuse.txt but was unable to see anything obvious. This could have been an issue with github content servers.

**Comment by yourduskquibbles** [comment]
From #5139 

> see also
> https://www.reddit.com/r/uBlockOrigin/comments/b0579i/bitdefender_detected_web_threat_from_ublockorigin/
> 
> However, it's a not very intelligent approach on Bitdefender side which should act on **accessing** a certain dangerous link / page (like those listed in resource-abuse **text** file) and not on **reading a list** including those links.
> 
> So, a simple false positive. You should be able in Bitdefender to [exclude](https://www.bitdefender.com/consumer/support/answer/2121/)
> https://github.com/uBlockOrigin/uAssets/blob/master/filters/resource-abuse.txt
> from Bitdefender scanning.

**Comment by smed79** [comment]
@alwarren @Ankahra Report the false positive here https://www.bitdefender.com/submit/

**Comment by alwarren** [comment]
I've had uBlockOrigin for quite some time without any issues. I noticed no one on the Reddit thread mentioned the query ?_=215671 tacked onto the end of the link. What's your take on that. I suspect it's just a penetration attempt and BitDefender recognizes it as such. But that said, Why haven't I had any issues until recently?

**Comment by gwarser** [comment]
It's timestamp (rounded to 2h) added by uBO to override cache.
