### ISSUE TITLE
wallstreet-online.de [broken page]

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5155]
### URL(s) where the issue occurs

`https://www.wallstreet-online.de/`

### Describe the issue

broken page, it doesnt show pictures

### Screenshot(s)

<img width="1477" alt="picture307848" src="https://user-images.githubusercontent.com/48647394/54494067-c366b480-48d6-11e9-8b2e-1cb8fb21066b.PNG">

### Versions

- Browser/version: Firefox 65.0.2
- uBlock Origin version: v1.18.6

### Settings

- 
[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/2975384/Settings.txt)

### Notes

Its must be a +js filter because nothing changed when i disable cosmetic filter on this page.

**Comment by mapx-** [comment]
see if helps
`wallstreet-online.de#@#^script:has-text(Inject=!)`

**Comment by JobcenterTycoon** [comment]
> 
> 
> see if helps
> `wallstreet-online.de#@#^script:has-text(Inject=!)`

it works
