### ISSUE TITLE
sport1.de [Anti-AdBlock]

### ISSUE THREAD

**Issue by Scunkaneli** [uBlockOrigin/uAssets#5156]
### URL(s) where the issue occurs

`https://www.sport1.de/`

### Describe the issue

Using uBlock Origin, an anti-adblock popup warning shows.

### Versions

- Browser/version: Firefox 66.0
- uBlock Origin version: 1.18.6

### Settings

Default

### Notes

Fixed by `www.sport1.de##+js(set-constant.js, window.s1AdDetection, true)`. 
Alternatively, `www.sport1.de##+js(abort-current-inline-script.js, adBlockerActive)` does work too.

**Comment by JobcenterTycoon** [comment]
Crazy i cant see any Anti-Adblock warning

**Comment by okiehsch** [comment]
I can't reproduce the filter
`||asadcdn.com/adlib/*$script,redirect=noopjs,domain=sport1.de`
still works on my end.

**Comment by Scunkaneli** [comment]
Very weird. Here are some screenshots to show the warning.

https://i.imgur.com/JBJeNrY.jpg
https://i.imgur.com/8c1WG81.jpg
https://i.imgur.com/PiNC1vN.png

**Comment by Scunkaneli** [comment]
Unblocking scripts for asadcdn.com in uMatrix works. When javascript is blocked via uMatrix, the warning shows up despite the rule being in place.

**Comment by okiehsch** [comment]
What OS are you using? MacOS is known to have issues with redirect filters.

**Comment by okiehsch** [comment]
If I neuter the redirection by adding
`||asadcdn.com/adlib/*$script,redirect=none,domain=sport1.de`
to my own filter list I can reproduce, so for some reason the redirection does not work as expected on your end.

**Comment by Scunkaneli** [comment]
My OS is Windows 10. I am pretty sure the issue is caused by uMatrix (or similar extentions) blocking scripts from asadcdn.com.

**Comment by okiehsch** [comment]
Sorry, I missed the part that mentioned that you also use uMatrix that can indeed cause the issue.
If uMatrix blocks the request before uBlock can redirect it the anti-adblock message will be triggered.

**Comment by Scunkaneli** [comment]
Okay so now that the reason for showing the popup are known, is this something that should/ will be fixed in uAssets or should I close this issue?

**Comment by okiehsch** [comment]
I will add 
`sport1.de##+js(set-constant.js, s1AdDetection, true)`
they change their bait script from time to time anyway and that filter will work no matter what script they use.

**Comment by Scunkaneli** [comment]
Thanks!

**Comment by okiehsch** [comment]
Note that normally no filters will be added if the issue is caused by a non `uBlock` extension.
In this case I consider your filter to be an improvement of the existing one.
