### ISSUE TITLE
Pre Video Ads

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5157]
### URL(s) where the issue occurs

`https://www.sixx.de/tv/total-dreamer-traeume-werden-wahr/video/125-staffel-1-episode-25-total-dreamer-traeume-werden-wahr-ganze-folge`

`https://www.kabeleinsdoku.de/tv/einfach-ueberirdisch-mit-william-shatner/video/310-ein-unbekanntes-lebewesen-ganze-folge`

### Describe the issue

Pre Video ads, ads in the Video.

### Versions

- Browser/version: Firefox 65.0.2
- uBlock Origin version: v1.18.6

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/2975653/Settings.txt)

### Notes

`||cdn.zomap.de^$media,redirect=noopmp4-1s,domain=sixx.de`
`||cdn.zomap.de^$media,redirect=noopmp4-1s,domain=kabeleinsdoku.de`

And the block for the black Background (its prevent you to do anythink on this site)

`kabeleinsdoku.de##.backdrop-overlay`
`sixx.de##.backdrop-overlay`
`sat1gold.de##.backdrop-overlay`
`kabeleins.de##.backdrop-overlay`

These Filters working for me. Its the same like `https://github.com/uBlockOrigin/uAssets/issues/5153`

**Comment by okiehsch** [comment]
Is the backdrop-overlay filter not redundant if the redirection is in place?
I mean it is only there for 2-3 seconds.

**Comment by JobcenterTycoon** [comment]
I think its looks better without any overlay, but its not really needed. Only these 2 Filters below the Notes are important to block the pre ads.

**Comment by JobcenterTycoon** [comment]
I get breakage on `https://www.vox.de/cms/videos.html` the video gets blank after the ad got skipped
