### ISSUE TITLE
[nsfw] lifeselector.com

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#5158]
`lifeselector.com`
antiadb
calling master @mapx-

**Comment by okiehsch** [comment]
Is some filter list blocking
`https://img.lifeselector.com/js/adbd.js`
on your end?
Blocking that request is the only way for me to reproduce an anti-adblock message.

**Comment by bogachenko** [comment]
@okiehsch idk what this
![Безымянный](https://user-images.githubusercontent.com/8535285/54499503-86b4b080-490a-11e9-9931-df0aa7967049.png)

**Comment by okiehsch** [comment]
You have to load bypassing the cache to see that request
![image](https://user-images.githubusercontent.com/16838044/54499528-40b01a80-4913-11e9-994b-fce8d612eb7a.png)

**Comment by bogachenko** [comment]
lol In the opera there is no, but in firefox there is. What? 
![Безымянный](https://user-images.githubusercontent.com/8535285/54499577-3b4ed200-490b-11e9-943a-908642c6f730.png)

**Comment by okiehsch** [comment]
I don't see any anti-adblock message at 
`https://lifeselector.com/game/DisplayPlayer/gameId/85901`
unless I block that request.
![image](https://user-images.githubusercontent.com/16838044/54499575-9d133a00-4913-11e9-940c-fd043fa6ac6e.png)

**Comment by bogachenko** [comment]
and by the way, you are right. the problem was this. I have blocked this script. now, no atiadb

**Comment by bogachenko** [comment]
@okiehsch just weird. in opera there is no such script at all, the problem (who would have thought) only on firefox (there is a script there)
![twitch](https://user-images.githubusercontent.com/8535285/54499693-89180a00-490c-11e9-96ec-00dab76aecf9.gif)
I do not understand.
