### ISSUE TITLE
dotesports.com

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#5159]
### URL(s) where the issue occurs

`https://dotesports.com/culture/news/a-streamer-predicted-why-ublock-origin-will-stop-working-on-twitch-3-months-ago`

### Describe the issue

Anti adblock

### Screenshot(s)

![Anotación 2019-03-18 055816](https://user-images.githubusercontent.com/27441315/54507723-e8910c80-4942-11e9-8a78-dc4dbf20ecfe.png)

### Versions

- Browser/version: Chrome 72
- uBlock Origin version: 1.18.8

### Settings

- Default settings.

**Comment by bogachenko** [comment]
`dotesports.com##+js(abort-current-inline-script.js, document.getElementsByTagName, script)`

**Comment by okiehsch** [comment]
Fixed in annoyances.
