### ISSUE TITLE
blockadblock.com anti-adblock

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#516]
### URL(s) where the issue occurs

`https://thepiratebay.run/?load=/browse`
`http://www.wallpapermania.eu/`
`https://blockadblock.com/`

### Describe the issue

Move around your mouse, scroll, etc. Anti-adblock warning appears.

### Versions

- Browser/version: Chrome 59
- uBlock Origin version: 1.13.2

### Settings

Default

**Comment by okiehsch** [comment]
Gorhill has declined to add a fix for `https://blockadblock.com`, he explains his reasoning here:
https://github.com/gorhill/uBlock/issues/1271#issuecomment-182831923

I fixed the other two plus a popup-issue at `https://thepiratebay.run/?load=/browse`
