### ISSUE TITLE
funnyquiz.blog{Antiadblock}

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5161]
### URL(s) where the issue occurs

`https://funnyquiz.blog/XL6JN`

### Describe the issue

Antiadblock
Fake click here button leading to ads

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Firefox android 65
- uBlock Origin version: 1.18.4

### Settings

- uBO's default settings

**Comment by bogachenko** [comment]
`funnyquiz.blog##+js(abort-on-property-read.js, adBlockDetected)`
