### ISSUE TITLE
anti-adblocker on nbcnews.com

### ISSUE THREAD

**Issue by paulv** [uBlockOrigin/uAssets#5174]
### URL(s) where the issue occurs

`https://www.nbcnews.com`

### Describe the issue

The anti-adblock functionality of the site prevents the site from being used. Sometimes the interstitial has a close button, but not always, as you can see from the screenshot below.

### Screenshot(s)

![Screenshot 2019-03-19 at 2 38 02 AM](https://user-images.githubusercontent.com/7901/54585532-b1793480-49f0-11e9-824f-a9049ac84108.png)

### Versions

- Browser/version: Version 72.0.3626.122
- uBlock Origin version: 1.18.8

### Settings

No changes to the settings.

**Comment by okiehsch** [comment]
Hm, it has a close button on my end, which is the reason this is fixed in `uBO-annoyances` and not by default.
`nbcnews.com##+js(abort-on-property-read.js, HTMLCanvasElement)`
is the working fix.

**Comment by okiehsch** [comment]
Well, I will fix it in `uBO-filters` I can see in your screenshot that you can't close the message and continue.

**Comment by gorhill** [comment]
If many instances of this behavior are reported, we will stop taking Admiral's request to "unbreak" their overlays.
