### ISSUE TITLE
uBlock Origin prevented the page from loading:

### ISSUE THREAD

**Issue by seriesgato** [uBlockOrigin/uAssets#5177]
when entering my domain seriesgato.tv ublock origin tells me the following message

http://prntscr.com/n030i5

how can I prevent this window from ever coming out again in my domain, I am the owner of it

**Comment by mapx-** [comment]
As I said, your domains are not blocked anymore, see 
http://dns-bh.sagadc.org/removed-domains-20190318.txt

(were removed yesterday)
