### ISSUE TITLE
vivo.sx

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5178]
### URL(s) where the issue occurs

`https://vivo.sx/6b3e3ee16a`

### Describe the issue

Sometimes popup ads are slipped through ublock filters 

### Versions

- Browser/version: firefox android 65
- uBlock Origin version: 1.18.6

### Settings

- uBO's default settings

**Comment by Elsensee** [comment]
The filter doesn't work anymore.

They create an empty subframe and use that one to overwrite the aeld.js and window.open-defuser.js, so it seems.
I tried to block it but with no success.

**Comment by mapx-** [comment]
We could use
`||vivo.sx^$csp=sandbox allow-forms allow-same-origin allow-scripts allow-modals allow-orientation-lock allow-pointer-lock allow-presentation allow-top-navigation`

no popup but the downside effect => the top buttons (sigup, contact etc) are not working

**Comment by okiehsch** [comment]
> the top buttons (signup, contact etc) are not working

They are still working on the homepage `vivo.sx` on my end, so if you think the minor breakage is justified by the better fix I will not object, ;)

**Comment by gwarser** [comment]
CSP filter causes redirection to ad in current tab - https://www.reddit.com/r/uBlockOrigin/comments/fhohz7/vivosx_redirects_to_ads_or_closes_tab/
