### ISSUE TITLE
NationalGeographic.com - Video playback issue (uBlock Legacy fix needed) 

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uAssets#5186]
### Affected site:
`https://www.nationalgeographic.com/`

### Issue:
Huge delay before video playback starts (relative to the length of a blocked video ad).

### Note:
Chromium browsers seems to be unaffected.

### Examples:
`https://video.nationalgeographic.com/`

### Known problem filters:
```
* EasyList:
.net/ad/$~object-subrequest
/admanager.$~object-subrequest,domain=~admanager.google.com
||fwmrm.net^$~object-subrequest,third-party

* Malvertising list by Disconnect:
fwmrm.net

* MVPS HOSTS:
1c6e2.v.fwmrm.net
m.v.fwmrm.net

* Schacks Adblock Plus liste:
||fwmrm.net
```

### Filter suitable for a potential fix:
* uBlock filters - Legacy

### Semi-fix (not a viable solution, since it also allows video ads):
`@@||v.fwmrm.net^$domain=nationalgeographic.com`

### Reference (Pale Moon forum):
`https://forum.palemoon.org/viewtopic.php?f=3&t=21694/`

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.4.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.10 (XUL)

**Comment by THEtomaso** [comment]
Think I've solved it..
By limiting the requests to `v.fwmrm.net` to scripts only, the ads seems to be skipped just fine!:
`@@||v.fwmrm.net^$script,domain=nationalgeographic.com`

**Comment by okiehsch** [comment]
Does
````
||fwmrm.net/ad/*$script,redirect=noopjs,domain=video.nationalgeographic.com
@@||fwmrm.net/*/fox_live/AdManager.js$script,domain=video.nationalgeographic.com
````
help?

**Comment by THEtomaso** [comment]
Yes, it helps.
With those rules in place, the ads are skipped, and the delay is much shorter than before.
I'd say that it's about 6 seconds for most videos now, although it's still as much as 13 seconds for some.

**Comment by okiehsch** [comment]
I can reproduce a delay using Firefox stable, so I added the Firefox specific filters to `uBO-filters`.

**Comment by THEtomaso** [comment]
With the `!#if env_firefox` in place, the rules doesn't work for Pale Moon though.

**Comment by okiehsch** [comment]
I also added them to the legacy list.
https://github.com/uBlockOrigin/uAssets/commit/b05bd23817a8f46f8c4b51ba94f6e4da5b89b7f1

**Comment by THEtomaso** [comment]
Great! :)

Just one question..
Shouldn't all of the conditions for issue #5120 be removed from the Legacy filter?
I mean, why would anyone use that filter in anything, except for a FF legacy based browser?

**Comment by okiehsch** [comment]
Users of Firefox 24 to Firefox 56 will also use the legacy list and could potentially benefit from the condition.
I can reproduce pre-roll ads if I add
`@@||svonm.com/hd-main.js$script,domain=kicker.de|kino.de|videos.giga.de|video.spieletipps.de`
using Firefox stable.

**Comment by THEtomaso** [comment]
OK.
Closing this one now.
