### ISSUE TITLE
www.mu2.mobi

### ISSUE THREAD

**Issue by bug-rules** [uBlockOrigin/uAssets#5187]
### URL(s) where the issue occurs

`http://www.mu2.mobi/` [NSWF]

### Describe the issue

Malware reddirect `http://check-prizes-now2.life/?u=kvypp0n&o=cekwcnh&t=www.mu2.mobi`

### Screenshot(s)

---

### Versions

- Browser/version: Chrome 73
- uBlock Origin version: uBO 1.18.8

### Settings

Default

### Notes

N/A [](https://github.com/AdguardTeam/AdguardFilters/issues/29654#issuecomment-474994630)

**Comment by mapx-** [comment]
test
```
mu2.mobi##+js(abort-on-property-read.js, marker)
mu2.mobi##+js(abort-current-inline-script.js, $, href)
```

**Comment by bug-rules** [comment]
Secound no works with videos:

`http://www.mu2.mobi/transljatsija-video/NnUzNU1hRkVXakE/`

**Comment by mapx-** [comment]
ok, so adding only the first 1 is ok, right ?

**Comment by bug-rules** [comment]
On videos section maybe used other inline script.

**Comment by mapx-** [comment]
If you add `mu2.mobi##+js(abort-on-property-read.js, marker)` did you still have other issues ?
`maybe` does not help

**Comment by bug-rules** [comment]
When this malware is gone.

**Comment by bug-rules** [comment]
```
http://mu2-mobi.pro/transljatsija-video/NnUzNU1hRkVXakE/
```

buyed new suffix / tld...
