### ISSUE TITLE
https://sonichits.com/ EasyList false positive

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#519]
### URL(s) where the issue occurs

`https://sonichits.com/`

### Describe the issue

EasyList breaks entire site. Won't load content.

**Comment by okiehsch** [comment]
Maybe we should cap the number of issues on user can open in 24 hours ;)

**Comment by terrorist96** [comment]
I'm just posting some of my issues that had been languishing on the EasyList github page. I'll slow down. :stuck_out_tongue_closed_eyes:
