### ISSUE TITLE
ndtv.com{breakage} 

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5190]
### URL(s) where the issue occurs

1.
`https://khabar.ndtv.com/news/bollywood/total-dhamaal-box-office-collection-day-27-ajay-devgn-anil-kapoor-madhuri-dixit-blockbuster-record-2010671?pfrom=home-topstories`

2. try news at these
`ndtv.com`
`sports.ndtv.com`
`gadgets.ndtv.com`
`food.ndtv.com`
`swirlster.ndtv.com`

### Describe the issue

1.
***what went wrong***
currently(with default settings) block of `taboola.com` hides some legit news stories at bottom of page

2
***how the page should be***
there should be no hide of legit content provided by taboola....also there should be blockage of sponsored ads by taboola

3. 
***what steps you have done in order to solve problem*** 
also in order to unbreak news content at bottom of page if i allow `taboola.com` ***it brings back sponsored ads as well*** alongwith unblocking news content

### Screenshot(s)

1.

***how the page looks with default settings***
https://user-images.githubusercontent.com/20338483/54755250-76882400-4bdd-11e9-9855-5736288dfc7f.jpg

2.
You need to allow taboola ***in order to see news content*** at bottom of page ***but this invites sponsored.ads as well***
https://user-images.githubusercontent.com/20338483/54755360-b64f0b80-4bdd-11e9-81e0-629bfb65e672.png

### Versions

- Browser/version: ***firefox android 66***
- uBlock Origin version: 1.18.6

### Settings

- uBO's default settings
***pls  try indian ip*** if you can't reproduce....
### Notes

issue you can reproduce on mobile device only i.e. firefox android

@Alex-302 adguard browser extension for firefox android also suffers from this breakage 
@jspenguin2017
@okiehsch

**Comment by jspenguin2017** [comment]
I can't test on that setup.

**Comment by okiehsch** [comment]
Me neither.

**Comment by kulfoon** [comment]
I confirm the both issues (breakage with blocked `taboola.com` & "Sponsored / Promoted Links" with unblocked `taboola.com`):
<details not-open>
<summary>screenshoot</summary>

![ss545](https://user-images.githubusercontent.com/43844449/54807921-ff0ad100-4c7e-11e9-81bb-c0503b0cd999.png)

</details>

Try these example fixes to hide the sponsored/promoted links:
`ndtv.com##.attribution-disclosure-link-hybrid`
`ndtv.com##.attribution-disclosure-link-sponsored`

In case anybody interested, they are generated by this script: 
`http://cdn.taboola.com/libtrc/ndtv-khabar/loader.js`

**Comment by Alex-302** [comment]
> `taboola.com` hides some legit news stories at bottom of page

It seems it is blocked by our `AdGuard Tracking Protection filter`. Need more detailed info.

**Comment by ghajini** [comment]
@Alex-302
Sorry sir IAM not pragrammer 
STR. Is already given
..
Go here

1. Eg
https://www.ndtv.com/entertainment/these-adorable-pics-of-taimur-are-the-perfect-cure-for-your-holi-hangover-2011371?pfrom=home-lateststories

2. Unblock taboola in order to display legit news content ......
3. Reload page
4. This is ad 
![Screenshot_2019-03-22-19-49-52-918_org mozilla firefox](https://user-images.githubusercontent.com/20338483/54829547-8d4a7b80-4cae-11e9-9e9a-eebfc7853065.png)

5.this is legit news content
![Screenshot_2019-03-22-19-50-32-564_org mozilla firefox](https://user-images.githubusercontent.com/20338483/54829621-b4a14880-4cae-11e9-9eb5-cbfa3602e82a.png)

**Comment by Alex-302** [comment]
@ghajini which filter causes it?

> Sorry sir IAM not pragrammer

just fill the template:)
https://github.com/AdguardTeam/AdguardFilters/issues/new

**Comment by ghajini** [comment]
@Alex-302 issue opened here
https://github.com/AdguardTeam/AdguardFilters/issues/31432

**Comment by ghajini** [comment]
@mapx-, @okiehsch, @jspenguin2017
Indian ip and and Firefox desktop browser

This us reproducible on desktop browser also
Check Firefox with ublock origin enabled and disabled.......
I see hidden stories with ubo enabled.......
With ubo disabled,  I see continuously loading legit stories at bottom of page

**Comment by mapx-** [comment]
@ghajini  test these filters
```
@@||cdn.taboola.com/libtrc/$script,domain=ndtv.com
@@||trc.taboola.com/ndtv/$script,domain=ndtv.com
```

**Comment by ghajini** [comment]
I see sponsored ads by taboola..''
`https://www.ndtv.com/india-news/niti-aayog-official-gets-poll-body-notice-for-comments-on-congress-scheme-2013388?pfrom=home-topscroll`

**Comment by mapx-** [comment]
save the page (html + folder) zip them together, upload on some server, send me the upload link (you still have that email I guess)

Are you talking about right side ads, in the middle etc ?

**Comment by ghajini** [comment]
I don't see ads on Firefox desktop browser......
Sorry ,I can't save page on Firefox android, there is no option like that on Firefox android nor any addon that can do that....
![IMG_20190327_135331](https://user-images.githubusercontent.com/20338483/55060723-f7c23980-5069-11e9-81e4-b678e8b6923a.jpg)
![IMG_20190327_135252](https://user-images.githubusercontent.com/20338483/55060731-06a8ec00-506a-11e9-9345-9f272b021620.jpg)
![IMG_20190327_135212](https://user-images.githubusercontent.com/20338483/55060772-26401480-506a-11e9-860b-e0d666680b86.jpg)
Ads are all over page,  in between articles

**Comment by mapx-** [comment]
`Sponsored links by taboola` is text or an image ?

**Comment by mapx-** [comment]
test
`ndtv.com##.trc-content-sponsored`

**Comment by ghajini** [comment]
When I click on them this appears ....blocked by adguards mobile filter
![Screenshot_2019-03-27-14-25-35-663_org mozilla firefox](https://user-images.githubusercontent.com/20338483/55062659-52f62b00-506e-11e9-878d-
3c827d4b5650.png)
![Screenshot_2019-03-27-14-29-25-873_org mozilla firefox](https://user-images.githubusercontent.com/20338483/55062874-b08a7780-506e-11e9-8f83-02164fd18f7e.png)

![Screenshot_2019-03-27-14-22-45-422_org mozilla firefox](https://user-images.githubusercontent.com/20338483/55062696-6903eb80-506e-11e9-8c9c-5a366f27411a.png)

**Comment by mapx-** [comment]
ok, did you test the filter above ?

**Comment by ghajini** [comment]
I will test properly once I got to home

**Comment by kulfoon** [comment]
> mapx: https://github.com/uBlockOrigin/uAssets/issues/5190#issuecomment-477042545
> mapx:  ok, did you test the filter above ?

Me did, they're working partially - for some links, but for some links not, just like my filters mentioned here: https://github.com/uBlockOrigin/uAssets/issues/5190#issuecomment-475530307, so the both solutions are complementary:

<details not-open>
<summary>kulfoon's solution's screenshoot</summary>

![ss550](https://user-images.githubusercontent.com/43844449/55138246-50113e00-5133-11e9-97a4-6825282f134b.png)

</details>

<details not-open>
<summary>mapx's solution's screenshoot </summary>

![ss549](https://user-images.githubusercontent.com/43844449/55138010-b9dd1800-5132-11e9-8f1d-ea8e9539af51.png)

</details>

> ghajini : Do we have any solution other than whitelisting like defusing taboola through scriptlets or any other?

That was the purpose why I posted the script https://github.com/uBlockOrigin/uAssets/issues/5190#issuecomment-475530307 which is responsible for creating the sponsored/promoted links, in case of anyone interested in creating an inject as an alternative way to solve the issue, if necessary of course.

**Comment by mapx-** [comment]
I added the filter above, do you still see ads in the middle ? or are you @kulfoon talking about promoted stuff on the right side ? are all of those links / sections real ads or only self-promoted parts ?

**Comment by mapx-** [comment]
( @ghajini  if you want to catch my/our attention don't simply replace your last comment with something else, better a new comment)

**Comment by mapx-** [comment]
Now the `trc.taboola.com` scripts are whitelisted for ndtv, do you still need the images too ?
`@@||trc.taboola.com/ndtv-ndtvmobile/$image,domain=ndtv.com`

**Comment by kulfoon** [comment]
> mapx : or are you kulfoon talking about promoted stuff on the right side ? are all of those links / sections real ads or only self-promoted parts ?

Yea, I was talking about the promoted links, I thought it was the same thing like the sponsored links, but sorry, now I'm not sure anymore...best to wait for ghajini to answer.

**Comment by ghajini** [comment]
I added
 https://github.com/uBlockOrigin/uAssets/issues/5190#issuecomment-477488484
Still.I can't access articles at bottom of page that were unblocked by taboola filter....
![Screenshot_2019-03-28-20-25-26-331_org mozilla firefox](https://user-images.githubusercontent.com/20338483/55168304-828a5d80-516a-11e9-97bf-171249129ee6.png)
![Screenshot_2019-03-28-20-26-39-399_org mozilla firefox](https://user-images.githubusercontent.com/20338483/55168381-a0f05900-516a-11e9-994b-3855d7c29465.png)
due to adguard mobile ads filter...'.
😃@kulfoon thanks for your contributions, I see no ads as.of now those were legit....what you see like sentence `sponsored /promoted links by taboola` is a placeholder.not a ad

**Comment by mapx-** [comment]
@ghajini  try:
`@@||trc.taboola.com/ndtv-ndtvmobile/$image,xhr,domain=ndtv.com`

**Comment by ghajini** [comment]
Nope still I see warning....
Something like this
`@@||trc.taboola.com/ndtv-ndtvmobile/log/*$domain=trc.taboola.com`
Unblocks articles for me. .....
I don't know if this adds tracking
Can't we noop these connections, I see similar taboola filter.in unbreak list for cnet

**Comment by mapx-** [comment]
Are all those requests `trc.taboola.com/ndtv-ndtvmobile/log/` only images ? png ?

**Comment by mapx-** [comment]
if images and png try
`||trc.taboola.com/ndtv-ndtvmobile/log/*$image,redirect=2x2-transparent.png,domain=trc.taboola.com`

**Comment by ghajini** [comment]
From logger what I see it originates as type `doc`

No that filter doesn't help

**Comment by ghajini** [comment]
New ads appeared at bottom of page....this appears after page load.....in between articles at navigation bar from left to.right 
`https://prnt.sc/n496h2`
`http://prnt.sc/n498wd`

**Comment by mapx-** [comment]
did you test
`ndtv.com##.composite-branding.branding` ?

**Comment by mapx-** [comment]
or 
`ndtv.com##.composite-branding.branding:has-text(/sponsored/i):xpath(..)`

**Comment by ghajini** [comment]
Tested
`ndtv.com##.composite-branding.branding:has-text(/sponsored/i):xpath(..)`
working finally.....

**Comment by ghajini** [comment]
Fix doesn't work here
`https://www.ndtv.com/india-news/lok-sabha-elections-2019-have-support-from-congress-says-bjps-nitin-gadkari-ahead-of-polls-2013902?amp=1&akamai-rum=off&amp_js_v=0.1&usqp=mq331AQECAEoAQ==`

**Comment by mapx-** [comment]
which one ? and means what ? still ads ? which ads ?

**Comment by ghajini** [comment]
No ads.....articles hidden

**Comment by mapx-** [comment]
mobile or desktop ?

**Comment by ghajini** [comment]
Now on Firefox android 66
Ublock origin 1.18.16

**Comment by mapx-** [comment]
test
`@@||trc.taboola.com/ndtv-ndtvmobile/log/$image,domain=ndtv.com`

**Comment by ghajini** [comment]
No that doesn't work......
Firstly I have to do some work in order to unblock articles
1. Whitelist `ampproject` in order to see taboola
2.whitelist taboola and as well as no cosmetic filtering for site because there are cosmetic filters in `adguards mobile ads filter` for taboola

3. Then you see articles unblocked
4. ***This offcourse invites sponsored ads***

**Comment by mapx-** [comment]
test
```
@@||cdn.ampproject.org/*amp-ad$script,domain=ndtv.com
@@||cdn.taboola.com/libtrc/ndtv-ndtvmobile/loader.js$script,domain=ampproject.net
@@||cdn.taboola.com/libtrc/impl.$script,domain=ampproject.net
@@||trc.taboola.com/ndtv-ndtvmobile/$script,domain=ampproject.net
ndtv.com#@#amp-embed[type="taboola"]
```

**Comment by ghajini** [comment]
Sponsored ads
![Screenshot_2019-03-30-14-13-26-191_org mozilla firefox](https://user-images.githubusercontent.com/20338483/55273810-289faa00-52c8-11e9-86ca-f9d4963329e1.png)

**Comment by mapx-** [comment]
I cannot reproduce on desktop (tried 3 user agent switcher)

**Comment by ghajini** [comment]
Yeah require
android device with Firefox browser android

**Comment by gwarser** [comment]
This is not ad?

![Screenshot_20190330-234636](https://user-images.githubusercontent.com/886325/55282603-5aa42100-5347-11e9-83d1-16c26e570c29.png)

Must be mislabeled, because is hidden by `##.trc-content-sponsored`

**Comment by ghajini** [comment]
Which URL, I will check.....

**Comment by kulfoon** [comment]
> ghajini: 
>
> Yeah require
> android device with Firefox browser android
> Whom among contributors have android device?.....

How many times need to repeat... https://github.com/uBlockOrigin/uAssets/issues/3482#issuecomment-433596075 + https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode

**Comment by gwarser** [comment]
For now https://addons.mozilla.org/android/addon/amp2html/

**Comment by mapx-** [comment]
@gwarser 

You mean needing the filters above 
https://github.com/uBlockOrigin/uAssets/issues/5190#issuecomment-478217396

or does work without them ?

**Comment by gwarser** [comment]
On HTML page sometimes legit (? Deepika) links are hidden, on AMP taboola thumbnails are not shown at all.

**Comment by kulfoon** [comment]
BTW at the link OP gave: https://github.com/uBlockOrigin/uAssets/issues/5190#issuecomment-478133586 / https://github.com/uBlockOrigin/uAssets/issues/5190#issuecomment-478206104 
I get some empty ad containers and labels on Firefox Desktop 
(both with and without https://github.com/uBlockOrigin/uAssets/issues/5190#issuecomment-478217396 ), so unrelated):

<details not-open>
<summary>spoiler</summary>

![Anim 001](https://user-images.githubusercontent.com/43844449/55287471-81933f00-53a9-11e9-9026-bfcf23f84620.gif)

</details>

**Comment by gwarser** [comment]
@mapx- with your exceptions, on html version ads are not hidden, looks like this: https://github.com/uBlockOrigin/uAssets/issues/5190#issuecomment-478221604

I'm not convinced these "Deepika"-like thumbnails are not ads, because they seems to link to random external domains and after click they redirect through the same tracker as ads.

**Comment by mapx-** [comment]
@gwarser  did you enable `AdGuard Mobile Ads filter` too ?

**Comment by gwarser** [comment]
Sorry - it's other way around, AMP ads are not hidde (accidentally swapped tabs). It's because I also have "Ignore generic cosmetic filters" checked (mobile default).

**Comment by mapx-** [comment]
last filters (still not getting those ads)
```
@@||cdn.ampproject.org/*amp-ad$script,domain=ndtv.com
@@||cdn.taboola.com/libtrc/ndtv-ndtvmobile/loader.js$script,domain=ampproject.net
@@||cdn.taboola.com/libtrc/impl.$script,domain=ampproject.net
@@||trc.taboola.com/ndtv-ndtvmobile/$script,domain=ampproject.net
ndtv.com#@#amp-embed[type="taboola"]
ndtv.com##[id^="adslot"]
ndtv.com##div[style]:has-text(/advertisement/i)
```

**Comment by mapx-** [comment]
However, without them the page is broken

**Comment by gwarser** [comment]
These unhidden ads are from `iframe` from `https://d-984640819716406753.ampproject.net/1903262220080/frame.html`

**Comment by kulfoon** [comment]
This https://github.com/uBlockOrigin/uAssets/issues/5190#issuecomment-478328943 fixed my issue https://github.com/uBlockOrigin/uAssets/issues/5190#issuecomment-478326826

**Comment by gwarser** [comment]
Any of these hides them:

```
ampproject.net##.trc-content-sponsored
ampproject.net##.trc_rbox .syndicatedItem
ampproject.net##.trc_rbox_border_elm .syndicatedItem
ampproject.net##.trc_rbox_div .syndicatedItem
```

**Comment by mapx-** [comment]
@ghajini  , test again after updating your lists

**Comment by ghajini** [comment]
@gwarser with due respect,
May I know which URL you get
https://github.com/uBlockOrigin/uAssets/issues/5190#issuecomment-478296564
I asked you this already previously so that I can understand your comment
https://github.com/uBlockOrigin/uAssets/issues/5190#issuecomment-478327909......in better way

**Comment by gwarser** [comment]
Heh, sorry, this was random page and I cannot find it in history now.

These thumbnails now link to hop.live/video

**Comment by ghajini** [comment]
@mapx thanks.....

**Comment by mapx-** [comment]
yeah, we know Deepika (- Novak story) ;)

**Comment by ghajini** [comment]
***Breakage***-

Article content is hidden...
URL-
`https://www.ndtv.com/india-news/watch-how-india-blasted-satellite-300-km-above-earth-with-mission-shakti-2019335?pfrom=home-topscroll`

***setup*** -
Firefox android 66
Ublock origin 1.18.16

Screenshots-

**Comment by mapx-** [comment]
tested 3 user agent:
- 2 of them => even disabling uBo I get no content or only the video
- 1 => I get the whole article like for desktop

**Comment by ghajini** [comment]
User agent changer not useful, try
https://github.com/uBlockOrigin/uAssets/issues/3482#issuecomment-433596075
if you can

**Comment by mapx-** [comment]
same result (and using indian ip via hola)

**Comment by gwarser** [comment]
www.ndtv.com#@#div[style]:has-text(/advertisement/i)

**Comment by mapx-** [comment]
I can replace that filter by
`ndtv.com##:xpath(//div[contains(text(),"Advert")])`

**Comment by gwarser** [comment]
Looks good.

**Comment by ghajini** [comment]
Yes that unblocked articles.....
@gwarser since it looks like you are closer to android setup, any filter needed or deducted in order to have minimum exception filters for site

**Comment by gwarser** [comment]
What you mean?

**Comment by ghajini** [comment]
***Firefox android***
Ublock origin 1.19.6

@mapx-
Does something changed in filters....

`https://www.ndtv.com/india-news/veteran-film-and-theatre-personality-girish-karnad-dies-at-81-2050674?pfrom=home-topscroll`

legit articles at bottom of page are inaccessible....

**Comment by mapx-** [comment]
scrolling and scrolling here ... no apparent issue, screenshot with what's missing on your side ?

**Comment by ghajini** [comment]
1.
Go here
`https://www.ndtv.com/india-news/veteran-film-and-theatre-personality-girish-karnad-dies-at-81-2050674?pfrom=home-topscroll`

2.
Wait for bottom articles to fetch ..scroll below

3. Click on them(bottom articles)
4. Result =they don't load on my side,may be they are blocked by adguards mobile ads filter `trc.taboola.com^`
Also blocking window is not displayed by ublock origin 1.19.6 firefox android

**Comment by mapx-** [comment]
does this work for you ?
`@@||trc.taboola.com/ndtv*/log/*$domain=trc.taboola.com`

**Comment by ghajini** [comment]
Perfect 👍

**Comment by NubN** [comment]
hello what about this for hide the promoted links: 

`ndtv.com##+js(aopr, _taboola)`

**Comment by mapx-** [comment]
Those promoted links are self promo, pointing to the same site articles, right ?

you can add
`gadgets.ndtv.com##.trc_rbox_container`

**Comment by ghajini** [comment]
`https://www.ndtv.com/india-news/wasnt-the-one-in-a-mask-aishe-ghosh-hits-back-at-delhi-police-claims-2162086?pfrom=home-topscroll`

Once again some filter from adguard mobile filters blocked articles at bottom of page

https://user-images.githubusercontent.com/20338483/72173610-fc3fbf00-33fd-11ea-94f3-be159be7878f.jpg

On clicking on them page go blank like this 
https://user-images.githubusercontent.com/20338483/72173663-14afd980-33fe-11ea-880a-b0870a1b0b33.jpg

**Comment by ghajini** [comment]
I wish some taboola defuser to run which will block ads and allow legit taboola articles used by news websites( as they are running on almost all news sites )

**Comment by ghajini** [comment]
This time
`@@||trc.taboola.com/ndtv-ndtvmobile/log/3/click$subdocument,domain=www.ndtv.com`
Unblock articles for me

**Comment by ghajini** [comment]
Promoted 3rd party (ads)

`https://food.ndtv.com/health/morning-coffee-may-not-be-a-great-option-for-the-diabetics-experts-explain-why-2305986`

### Platform =
Firefox android stable ,ublock origin 1.30

### screenshots=

https://user-images.githubusercontent.com/20338483/95286700-aa8b6e80-0881-11eb-8ad0-155958cffb3f.jpg

https://user-images.githubusercontent.com/20338483/95286736-c1ca5c00-0881-11eb-9dbf-28026a684007.jpg

**Comment by ghajini** [comment]
Amazon promotions ads

`https://gadgets.ndtv.com/telecom/news/jio-5g-service-launch-india-rollout-second-half-2021-mukesh-ambani-2335646?pfrom=topstory`

![Screenshot_2020-12-08-15-38-45-358_org mozilla fenix](https://user-images.githubusercontent.com/20338483/101470506-18304580-396c-11eb-82c7-cb3f84b6a093.png)

Firefox android, ubo stable

**Comment by mapx-** [comment]
test

```
gadgets.ndtv.com###header_ad_before_id
gadgets.ndtv.com##.__wdgt_rhs_kpc
gadgets.ndtv.com##._kpw_wrp_rhs_widget
```

**Comment by ghajini** [comment]
Missed
![Screenshot_2020-12-08-16-07-12-819_org mozilla fenix](https://user-images.githubusercontent.com/20338483/101473290-a22ddd80-396f-11eb-8da2-f1736717dbf3.png)

**Comment by mapx-** [comment]
what about (remove the filters above):

`||hotdeals360.com^$3p`

**Comment by ghajini** [comment]
> what about (remove the filters above):
> 
> `||hotdeals360.com^$3p`

Correct
