### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#5191]
This wasn't reproduced by Adguard - https://github.com/AdguardTeam/AdguardFilters/issues/30719. Please check these URLs with a clean profile/container.

Membership annoyance:

`https://www.youtube.com/watch?v=BGN8bP5uJvM`
![{F60736AA-4950-4EC4-AEB7-54C8C1CE81A1}](https://user-images.githubusercontent.com/35470489/54070774-17bcc500-4243-11e9-91e8-231d4b748291.png)

`https://www.youtube.com/channel/UCkJEpR7JmS36tajD34Gp4VA/videos`
![{817BD986-7A36-44AC-8394-8915D99C9BE1}](https://user-images.githubusercontent.com/35470489/54070778-38851a80-4243-11e9-985d-8b846b7640ad.png)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.6
Firefox 66

**Comment by mapx-** [comment]
I'm able to reproduce the annoyance on the second link above

test
`youtube.com##.ytd-popup-container`

@ryanbr

**Comment by krystian3w** [comment]
Smeels A/B Testing.

**Comment by yourduskquibbles** [comment]
FYI @mapx- `youtube.com##.ytd-popup-container` will block valid popups such as hamburger popup, the filter is too broad from my experience.

See: https://github.com/yourduskquibbles/webannoyances/issues/60

**Comment by mapx-** [comment]
right, probably something like
https://github.com/AdguardTeam/AdguardFilters/issues/30719#issuecomment-471222204

would work

**Comment by mapx-** [comment]
`youtube.com##.ytd-popup-container:has-text(/membership/i)`

**Comment by yourduskquibbles** [comment]
> youtube.com##.ytd-popup-container:has-text(/membership/i)

This works for me on second link

**Comment by krystian3w** [comment]
https://pl.reddit.com/r/uBlockOrigin/comments/b6yre7/cant_click_on_the_profile_button_on_youtube/ - maybe still broken.

**Comment by gwarser** [comment]
@krystian3w 	https://github.com/uBlockOrigin/uAssets/issues/5195

**Comment by krystian3w** [comment]
May version no bug this - amazing...

**Comment by krystian3w** [comment]
`##ytd-popup-container > .ytd-popup-container > #contentWrapper > .ytd-popup-container[style_="BUBBLE_HINT_STYLE_BLUE_TOOLTIP"]`

**Comment by planigan** [comment]
This cosmetic filter was breaking the notifications and account dropdowns for me as of earler today.  

```
! https://github.com/uBlockOrigin/uAssets/issues/5191
youtube.com##.ytd-popup-container:has-text(/membership /i)
```  
I disabled it in my filters, just an FYI in case others are seeing the same.

**Comment by krystian3w** [comment]
@mapx- still broken...

**Comment by krystian3w** [comment]
@planigan try:

```
youtube.com##.ytd-popup-container:has-text(/Membership /)
```

**Comment by mapx-** [comment]
removed

**Comment by krystian3w** [comment]
Thank you.
