### ISSUE TITLE
ebb.io [Anti-Adblock]

### ISSUE THREAD

**Issue by shinobumw** [uBlockOrigin/uAssets#5192]
### URL(s) where the issue occurs

`https://ebb.io/`

### Describe the issue

Anti-Adblock

### Screenshot(s)

![](https://i.imgur.com/3HbsYSS.jpg)

### Versions

- Browser/version: Chrome 73.0.3683.86
- uBlock Origin version: 1.18.8

### Settings

- Default settings

**Comment by mapx-** [comment]
it seems to be only an annoyance (the site isn't broken, the videos are running fine)

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/5346
