### ISSUE TITLE
semestr.ru

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#5199]
`https://math.semestr.ru/line/vector-product.php`

see #1571 and https://github.com/AdguardTeam/AdguardFilters/issues/11882

They seem to have changed their defense. Now does not work. Default settings (2 regional Russian subscriptions) tested on firefox and waterfox

**Comment by mapx-** [comment]
```
@@||semestr.ru/skin/show_ads.js$script,1p
semestr.ru#@#div[id^="bn_"]
semestr.ru#@##idbanner:style(max-height: 41px !important; opacity: 0 !important; pointer-events: none !important)
semestr.ru#@#.adsbygoogle:style(max-height: 4px !important)
semestr.ru#@#.well-google:style(max-height: 41px !important; opacity: 0 !important; pointer-events: none !important)
semestr.ru##.well-google:style(max-height: 121px !important; opacity: 0 !important; pointer-events: none !important)
```

@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
https://hg.adblockplus.org/ruadlist/rev/4f7619a7239c

**Comment by bogachenko** [comment]
@mapx- again

**Comment by bogachenko** [comment]
@mapx- incorrect
the problem look like https://github.com/uBlockOrigin/uAssets/issues/1571#issuecomment-366771422

**Comment by mapx-** [comment]
I get no issue, the site is loading fine for me.
