### ISSUE TITLE
convert2mp3.net [Popup]

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5203]
### URL(s) where the issue occurs

`http://convert2mp3.net`

### Describe the issue

Popup when you click anywhere on this site.

### Versions

- Browser/version: Firefox 66
- uBlock Origin version: v1.18.6

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3000366/Settings.txt)

### Notes
`convert2mp3.net##[href="//soagitet.net/2359307.html"]` blocks the overlay

**Comment by JobcenterTycoon** [comment]
@mapx- the filter doesnt work for me

**Comment by mapx-** [comment]
add also
```
convert2mp3.net##+js(abort-on-property-read.js, zfgloadedpopup)
||ithoahie.com^
```

test again

**Comment by mapx-** [comment]
and check your logger if you see all the filters added to the list

**Comment by JobcenterTycoon** [comment]
> 
> 
> add also
> 
> ```
> convert2mp3.net##+js(abort-on-property-read.js, zfgloadedpopup)
> ||ithoahie.com^
> ```
> 
> test again

it doesnt work for me

**Comment by mapx-** [comment]
You didn't check if all filters added above are reported in the logger.

add and test
`convert2mp3.net##+js(abort-on-property-read.js, decodeURIComponent)`

**Comment by JobcenterTycoon** [comment]
@mapx- 
> 
> 
> You didn't check if all filters added above are reported in the logger.
> 
> add in "my filters" and test
> `convert2mp3.net##+js(abort-on-property-read.js, decodeURIComponent)`
im added all but the popup still appears
<img width="521" alt="picture3948679" src="https://user-images.githubusercontent.com/48647394/54882527-3c2bba80-4e5b-11e9-8d4b-0d76c5659cc9.PNG">

**Comment by mapx-** [comment]
FF 66 is a little buggy, does not update (always) the lists, but if you added the filters manually it should work.

Try using the last dev uBo from:
https://github.com/gorhill/uBlock/releases

Eventually reset uBo to the default settings. Are you using other blockers (script blockers, adblockers) ?

**Comment by JobcenterTycoon** [comment]
> 
@mapx- 
> 
> FF 66 is a little buggy, does not update (always) the lists, but if you added the filters manually it should work.
> 
> Try using the last dev uBo from:
> https://github.com/gorhill/uBlock/releases
> 
> Eventually reset uBo to the default settings. Are you using other blockers (script blockers, adblockers) ?

Ah i have it, i must disable "AdGuard base filters" now it works. thanks mapx-

**Comment by JobcenterTycoon** [comment]
> 
> 
> FF 66 is a little buggy, does not update (always) the lists, but if you added the filters manually it should work.
> 
> Try using the last dev uBo from:
> https://github.com/gorhill/uBlock/releases
> 
> Eventually reset uBo to the default settings. Are you using other blockers (script blockers, adblockers) ?

The popup only appears when the site `pheegoab.click` is blacklisted. The AdGuard base filter blocking the site.

**Comment by krystian3w** [comment]
@adamwr / @alex-302 / @blaztd - https://github.com/uBlockOrigin/uAssets/issues/5203#issuecomment-475977036

**Comment by BlazDT** [comment]
URL not requested and no popup reproduced when I visit the site with Extension.

**Comment by bogachenko** [comment]
@mapx- 
``http://convert2mp3.net/assets/js/push.js`

![Безымянный](https://user-images.githubusercontent.com/8535285/54888271-bf690280-4e93-11e9-8df3-cea7fd387fad.png)

**Comment by okiehsch** [comment]
That is a popads-script, blocking it will be pretty pointless they always rename them.
Adding 
````
convert2mp3.net##+js(abort-current-inline-script.js, RegExp, zfgload)
convert2mp3.net##+js(abort-on-property-read.js, g133.c3)
````
will break the script and defuse additional crap.

**Comment by bogachenko** [comment]
okay. 1 question. Is this value not changing?

> g133.c3

**Comment by bogachenko** [comment]
i now just put  in this. Again nod32 swears.


> 
> 
> That is a popads-script, blocking it will be pretty pointless they always rename them.
> Adding
> 
> ```
> convert2mp3.net##+js(abort-current-inline-script.js, RegExp, zfgload)
> convert2mp3.net##+js(abort-on-property-read.js, g133.c3)
> ```
> 
> will break the script and abort additional crap.

**Comment by okiehsch** [comment]
> i now just put in this. Again nod32 swears.

`convert2mp3.net##+js(abort-on-property-read.js, g133.c3)`
breaks the script you can check it on your end.
![image](https://user-images.githubusercontent.com/16838044/54888564-5c309d80-4e9e-11e9-87d7-c45fc2314775.png)

I can add a blocking filter too.

**Comment by bogachenko** [comment]
in my console, too, so it is written. But Nod32 swears.

**Comment by okiehsch** [comment]
I have also blocked the script, so NOD32 should be OK with the site now.

**Comment by JobcenterTycoon** [comment]
This site got taken down because of Copyright. The filters are not needed in the future
@okiehsch
