### ISSUE TITLE
youtubemp4.biz [popup, Fake button]

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5220]
### URL(s) where the issue occurs

`https://youtubemp4.biz/`

### Describe the issue

Fake buttons, popup when you click on "download" 
<img width="1133" alt="picture3407837" src="https://user-images.githubusercontent.com/48647394/54919478-34265600-4f01-11e9-93a1-044d65d1a37e.PNG">
<img width="378" alt="picture405867" src="https://user-images.githubusercontent.com/48647394/54919479-34265600-4f01-11e9-850f-f3133533b5ec.PNG">

### Versions

- Browser/version: Firefox 66.0.1
- uBlock Origin version: v1.18.6

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3003215/Settings.txt)

**Comment by mapx-** [comment]
The download green buttons on the right are legitimate ones => you can right click in the opened window and save the song

add
`youtubemp4.biz##[href="/g-ban.php"]`

@ryanbr

**Comment by JobcenterTycoon** [comment]
> 
@mapx- 
> 
> The download green buttons on the right are legitimate ones => you can right click in the opened window and save the song
> 
> add
> `youtubemp4.biz##[href="/g-ban.php"]`
> 
> @ryanbr

When i click from mp4 to mp3 i get a popup

**Comment by mapx-** [comment]
Does this work for you
`youtubemp4.biz##+js(abort-on-property-read.js, ads)`

**Comment by JobcenterTycoon** [comment]
@mapx- 
> 
> 
> Does this work for you
> `youtubemp4.biz##+js(abort-on-property-read.js, ads)`

yes that works thanks. But can you please add `youtubemp4.biz##[href="/w.php"]`
to the list because these are fake buttons too

**Comment by mapx-** [comment]
I get no such buttons `##[href="/w.php"]` Are you talking about the green ones ? other ? screenshot ?

**Comment by mapx-** [comment]
right, I get them in chrome

**Comment by JobcenterTycoon** [comment]
> 
> 
> right, I get them in chrome

<img width="1262" alt="picture4306737" src="https://user-images.githubusercontent.com/48647394/54923313-4d7fd000-4f0a-11e9-967b-0b8e6d9b5599.PNG">

its when you use mp3 not mp4

**Comment by mapx-** [comment]
oh, ok => added

**Comment by JobcenterTycoon** [comment]
They changed the Domain to `https://ymp4.biz`
