### ISSUE TITLE
winfuture.de [Pre Video Ads]

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5223]
### URL(s) where the issue occurs

`https://winfuture.de/videos/Internet/URL-Shortener-Wie-man-hinter-verkuerzte-Links-schauen-kann-19046.html`

### Describe the issue

Pre video Ads

### Screenshot(s)
<img width="928" alt="picture340678" src="https://user-images.githubusercontent.com/48647394/54935388-7ca13c00-4f20-11e9-84b3-ef67bd1042d5.PNG">

### Versions

- Browser/version: Firefox 66.0.1
- uBlock Origin version: v1.18.6

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3004286/Settings.txt)

**Comment by mapx-** [comment]
I get no video ad, let's wait @okiehsch

**Comment by okiehsch** [comment]
I can't reproduce, after1 second the video pauses for a second or two but after that it plays without issue on my end.

**Comment by JobcenterTycoon** [comment]
@okiehsch 

> 
> 
> I can't reproduce, after 1 second the video pauses for a second or two but after that it plays without issue on my end.

I tested it again with a fresh Chrome and a fresh uBlock Origin with updated filters and get ads again. 
Chrome default settings:

<img width="1633" alt="picture682406" src="https://user-images.githubusercontent.com/48647394/54955217-f2bb9800-4f4c-11e9-8dd4-173634c99059.PNG">
Firefox with more filters:
<img width="1240" alt="picture340803" src="https://user-images.githubusercontent.com/48647394/54955314-3f9f6e80-4f4d-11e9-9391-35efc46fef54.PNG">

to reproduce please clear the cache, cookies, etc on this site.I have a 50% chance for a ad.

**Comment by mapx-** [comment]
try
`winfuture.de##+js(damoh-defuser.js)`

**Comment by JobcenterTycoon** [comment]
@mapx- 

> 
> 
> try
> `winfuture.de##+js(damoh-defuser.js)`

it doesnt work

**Comment by mapx-** [comment]
or
`||damoh.winfuture.de/$media,redirect=noopmp3-0.1s,domain=winfuture.de`

**Comment by JobcenterTycoon** [comment]
@mapx- 

> 
> 
> or
> `||damoh.winfuture.de/$media,redirect=noopmp3-0.1s,domain=winfuture.de`

It doenst work, the video disappear after 5 secs.

**Comment by okiehsch** [comment]
> I can't reproduce, after 1 second the video pauses for a second or two but after that it plays without issue on my end.

I still can't reproduce any pre-roll ads on my end but I can fix the video pausing after 1 second for a short time by adding
`winfuture.de##+js(setInterval-defuser.js, fireEvent, 500)`
does that maybe fix your issue?

**Comment by JobcenterTycoon** [comment]
> 
@okiehsch 

> 
> > I can't reproduce, after 1 second the video pauses for a second or two but after that it plays without issue on my end.
> 
> I still can't reproduce any pre-roll ads on my end but I can fix the video pausing after 1 second for a short time by adding
> `winfuture.de##+js(setInterval-defuser.js, fireEvent, 500)`
> does that maybe fix your issue?

Yes, thanks

**Comment by JobcenterTycoon** [comment]
Video ads are back again.

`winfuture.de##+js(json-prune, enabled, testhide)` will fix that

**Comment by JobcenterTycoon** [comment]
video ads are back
