### ISSUE TITLE
*.gamepedia.com shows Google Ads

### ISSUE THREAD

**Issue by leewdch** [uBlockOrigin/uAssets#5229]
### URL(s) where the issue occurs

`https://minecraft.gamepedia.com/19w12b`

### Describe the issue

There are Google Ads in the right side and top of the screen when visiting gamepedia.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/11262717/55000198-4ae8ad80-4fd2-11e9-9006-66c14329b636.png)

### Versions

- Browser/version: Google Chrome 73.0.3683.86 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin 1.18.10

### Settings

- Simply enabled the advanced menu so far

**Comment by mapx-** [comment]
For gamepedia you need `uBlock origin extra` too
https://chrome.google.com/webstore/detail/ublock-origin-extra/pgdnlhfefecpicbbihgmbmffkjpaplco

**Comment by krystian3w** [comment]
For own risk ☢️ 

```
gamepedia.com###content > div[id^="-"]
```

no kill reddirection.
