### ISSUE TITLE
http://tn.nova.cz/ videos are being blocked

### ISSUE THREAD

**Issue by pepablock** [uBlockOrigin/uAssets#523]
### URL(s) where the issue occurs

**example link** **–** `http://tn.nova.cz/clanek/tabor-kde-mel-nekdo-osahavat-deti-vypsal-na-pachatele-odmenu.html`

### Describe the issue

Instead of playing the video it displays a warning saying "Video can't be played. You may have problems with your connection or active AdBlock." Happens on any article with video included.

### Screenshot(s)

<img width="663" alt="screen shot 2017-07-16 at 8 10 25 am" src="https://user-images.githubusercontent.com/29940017/28245069-4b5a1b34-69fe-11e7-9348-49d4b9dbb084.png">

### Versions

- Browser/version: **Firefox 54.0.1 (64-bit)**
- uBlock Origin version: **1.13.4**

### Settings

Default

### Notes

–

**Comment by gorhill** [comment]
Do these filters work on your side?

    ||adserver.adtech.de^$xmlhttprequest,redirect=nooptext,domain=tn.nova.cz
    ||pro.hit.gemius.pl^$script,redirect=noopjs,domain=tn.nova.cz
    @@||static.cz.prg.cmestatic.com/static/shared/app/videojs/plugins/*$script,domain=tn.nova.cz

**Comment by lain566** [comment]
@gorhill It works on Chrome, but it's not working on Firefox.
Is There a Solution for Firefox?

**Comment by pepablock** [comment]
Not working anymore, they probably changed something and videos won't play if adblock is enabled.

**Comment by okiehsch** [comment]
`@@||adserver.adtech.de^$xmlhttprequest,domain=tn.nova.cz`
works on my end but you will see pre-roll ads if you use Firefox.

If you use Chrome with `EasyList Czech and Slovak` enabled add
`||adserver.adtech.de^$xmlhttprequest,important,redirect=nooptext,domain=nova.cz`.

**Comment by pepablock** [comment]
Working in firefox, is there a way of getting around the pre-roll ads?

**Comment by okiehsch** [comment]
Not if you use Firefox, the `xmlhttprequest-redirect` does not work with Firefox.
If you use Chrome and add the filter I suggested the video plays without pre-roll ads.

**Comment by pepablock** [comment]
I see, thanks.

**Comment by okiehsch** [comment]
@pepablock can you try if 
````
||adserver.adtech.de/?advideo/3.0/$xmlhttprequest,important,redirect=nooptext,domain=nova.cz
@@||adserver.adtech.de^$xmlhttprequest,domain=tn.nova.cz
````
works on your end with Firefox.

**Comment by pepablock** [comment]
Yes, it's working in firefox! I don't see any pre-roll ads.
