### ISSUE TITLE
earthgarage.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#5232]
### URL(s) where the issue occurs

`https://www.google.com/search?q=why+did+rear+wheel+steering+discontinue&oq=why+&aqs=chrome.0.69i59j69i65l3j69i57j69i61.1261j0j7&sourceid=chrome&ie=UTF-8`

### Describe the issue

Clicking first link 

```
The QuadraSteer System - Earthgarage.com
earthgarage.com/2018/02/05/the-quadrasteer-system/
```

will open the site but then it redirects. Redirected site blocked by https://github.com/uBlockOrigin/uAssets/pull/5231 but can the redirect be prevented from occurring to begin with? I provide the google search result link because I can only reproduce by clicking from there.
It happens inconsistently for me. Below I caught the log when it did happen.

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +181 |  |  | mail.google.com | 0,3 | xhr | `https://ssl.gstatic.com/ui/v1/icons/mail/images/cleardot.gif?zx=wumzygwmfxcy` |
| +136 |  |  | j72ud.tvnewtop.pro | 1 | inline-script | `https://j72ud.tvnewtop.pro/bot-detect?h=waWQiOjEwMDE2MDYsInNpZCI6MTAwMzIxNCwid2lkIjo4ODg3LCJzcmMiOjJ9eyJ&bbr=1&i=1` |
| +136 |  |  | j72ud.tvnewtop.pro | 3 | script | `https://serviceproworker.com/v1/sdk.js?h=waWQiOjEwMDE2MDYsInNpZCI6MTAwMzIxNCwid2lkIjo4ODg3LCJzcmMiOjJ9eyJ&d=tvnewtop.pro&tpl=4` |
| +136 |  |  | j72ud.tvnewtop.pro | 1 | image | `https://j72ud.tvnewtop.pro/images/bot-detect/robot-men.png` |
| +136 |  |  | j72ud.tvnewtop.pro | 1 | image | `https://j72ud.tvnewtop.pro/images/bot-detect/arrow.png` |
| +136 |  |  | j72ud.tvnewtop.pro | 1 | doc | `https://j72ud.tvnewtop.pro/bot-detect?h=waWQiOjEwMDE2MDYsInNpZCI6MTAwMzIxNCwid2lkIjo4ODg3LCJzcmMiOjJ9eyJ&bbr=1&i=1` |
| +135 |  |  | tvnewtop.pro | 1 | inline-script | `https://tvnewtop.pro/bot-detect?h=waWQiOjEwMDE2MDYsInNpZCI6MTAwMzIxNCwid2lkIjo4ODg3LCJzcmMiOjJ9eyJ&bbr=1&si1=&si2=` |
| +135 |  |  | tvnewtop.pro | 3 | script | `https://serviceproworker.com/v1/sdk.js?h=waWQiOjEwMDE2MDYsInNpZCI6MTAwMzIxNCwid2lkIjo4ODg3LCJzcmMiOjJ9eyJ&d=tvnewtop.pro&tpl=4` |
| +135 |  |  | tvnewtop.pro | 1 | image | `https://tvnewtop.pro/images/bot-detect/robot-men.png` |
| +135 |  |  | tvnewtop.pro | 1 | image | `https://tvnewtop.pro/images/bot-detect/arrow.png` |
| +135 |  |  | tvnewtop.pro | 1 | doc | `https://tvnewtop.pro/bot-detect?h=waWQiOjEwMDE2MDYsInNpZCI6MTAwMzIxNCwid2lkIjo4ODg3LCJzcmMiOjJ9eyJ&bbr=1&si1=&si2=` |
| +135 |  |  | earthgarage.com | 3 | font | `https://fonts.gstatic.com/s/opensans/v16/mem5YaGs126MiZpBA-UN7rgOUuhp.woff2` |
| +135 |  |  | earthgarage.com | 3 | font | `https://fonts.gstatic.com/s/opensans/v16/mem8YaGs126MiZpBA-UFVZ0b.woff2` |
| +135 |  |  | earthgarage.com | 3 | font | `https://fonts.gstatic.com/s/francoisone/v13/_Xmr-H4zszafZw3A-KPSZut9wQiR.woff2` |
| +135 |  |  | earthgarage.com | 1 | font | `http://earthgarage.com/wp-content/themes/Divi/core/admin/fonts/modules.ttf` |
| +135 |  |  | earthgarage.com | 3 | font | `https://fonts.gstatic.com/s/opensans/v16/mem5YaGs126MiZpBA-UNirkOUuhp.woff2` |
| +135 |  |  | earthgarage.com | 3 | script | `http://193.238.46.6/mRPPzC` |
| +135 |  |  | earthgarage.com | 3 | font | `https://fonts.gstatic.com/s/opensans/v16/mem5YaGs126MiZpBA-UN7rgOUuhp.woff2` |
| +135 |  |  | earthgarage.com | 3 | font | `https://fonts.gstatic.com/s/opensans/v16/mem8YaGs126MiZpBA-UFVZ0b.woff2` |
| +135 |  |  | earthgarage.com | 3 | font | `https://fonts.gstatic.com/s/francoisone/v13/_Xmr-H4zszafZw3A-KPSZut9wQiR.woff2` |
| +135 |  |  | earthgarage.com | 1 | font | `http://earthgarage.com/wp-content/themes/Divi/core/admin/fonts/modules.ttf` |
| +135 |  |  | earthgarage.com | 3 | font | `https://fonts.gstatic.com/s/opensans/v16/mem5YaGs126MiZpBA-UNirkOUuhp.woff2` |
| +134 |  |  | earthgarage.com | 1 | script | `http://earthgarage.com/wp-includes/js/wp-emoji-release.min.js?ver=5.1.1` |
| +134 |  |  | earthgarage.com | 1 | script | `http://earthgarage.com/wp-content/plugins/akismet/_inc/form.js?ver=4.1.1` |
| +134 |  |  | earthgarage.com | 1 | script | `http://earthgarage.com/wp-includes/js/wp-embed.min.js?ver=5.1.1` |
| +134 |  |  | earthgarage.com | 1 | script | `http://earthgarage.com/wp-content/themes/Divi/core/admin/js/common.js?ver=3.19.12` |
| +134 |  |  | earthgarage.com | 1 | script | `http://earthgarage.com/wp-content/themes/Divi/js/custom.min.js?ver=3.19.12` |
| +133 |  |  | earthgarage.com | 3 | css | `https://fonts.googleapis.com/css?family=Francois+One%3Aregular&ver=5.1.1#038;subset=vietnamese,latin,latin-ext` |
| +133 |  |  | earthgarage.com | 3 | css | `https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,latin-ext` |
| +133 |  |  | earthgarage.com | 1 | script | `http://earthgarage.com/wp-includes/js/comment-reply.min.js?ver=5.1.1` |
| +133 |  |  | earthgarage.com | 1 | css | `http://earthgarage.com/wp-content/plugins/kebo-twitter-feed/css/plugin.css?ver=1.5.12` |
| +133 |  |  | earthgarage.com | 1 | image | `https://earthgarage.com/wp-content/uploads/2015/02/EG_350x188.jpg` |
| +133 |  |  | earthgarage.com | 1 | css | `http://earthgarage.com/wp-content/cache/et/global/et-divi-customizer-global-15525774239715.min.css` |
| +133 | addthis.com/addthis_widget.js | << | earthgarage.com |  | script | `https://s7.addthis.com/js/300/addthis_widget.js?ver=5.1.1#pubid=wp-5c2c45dde745f8c9b8357a53d90387b8` |
| +133 | \|\|addthis.com^$important,third-party,domain=~missingkids.com\|~missingkids.org\|~sainsburys.jobs | -- | earthgarage.com | 3 | script | `https://s7.addthis.com/js/300/addthis_widget.js?ver=5.1.1#pubid=wp-5c2c45dde745f8c9b8357a53d90387b8` |
| +133 |  |  | earthgarage.com | 1 | script | `http://earthgarage.com/wp-admin/admin-ajax.php?action=addthis_global_options_settings&ver=5.1.1` |
| +133 |  |  | earthgarage.com | 1 | script | `http://earthgarage.com/wp-content/plugins/speakup-email-petitions/js/widget.js?ver=5.1.1` |
| +133 |  |  | earthgarage.com | 1 | script | `http://earthgarage.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1` |
| +133 |  |  | earthgarage.com | 1 | script | `http://earthgarage.com/wp-includes/js/jquery/jquery.js?ver=1.12.4` |
| +133 |  |  | earthgarage.com | 1 | css | `http://earthgarage.com/wp-includes/css/dashicons.min.css?ver=5.1.1` |
| +133 |  |  | earthgarage.com | 1 | css | `http://earthgarage.com/wp-content/plugins/addthis/frontend/build/addthis_wordpress_public.min.css?ver=5.1.1` |
| +133 |  |  | earthgarage.com | 3 | css | `http://fonts.googleapis.com/css?family=Francois+One%3Aregular&ver=5.1.1#038;subset=vietnamese,latin,latin-ext` |
| +133 |  |  | earthgarage.com | 1 | css | `http://earthgarage.com/wp-content/themes/Divi/style.css?ver=3.19.12` |
| +133 |  |  | earthgarage.com | 3 | css | `http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,latin-ext` |
| +133 |  |  | earthgarage.com | 1 | css | `http://earthgarage.com/wp-includes/css/dist/block-library/style.min.css?ver=5.1.1` |
| +133 |  |  | earthgarage.com | 1 | css | `http://earthgarage.com/wp-content/plugins/speakup-email-petitions/css/widget.css?ver=5.1.1` |
| +133 |  |  | earthgarage.com | 1 | doc | `http://earthgarage.com/2018/02/05/the-quadrasteer-system/` |
</details>

**Comment by okiehsch** [comment]
I can't reproduce, I don't see `earthgarage.com/2018/02/05/the-quadrasteer-system/`
in my search results if I go to
````
https://www.google.com/search?q=why+did+rear+wheel+steering+discontinue&oq=why+&aqs=chrome.0.69i59j69i65l3j69i57j69i61.1261j0j7&sourceid=chrome&ie=UTF-8
````
and if I change my search to "why did rear wheel steering discontinue earthgarage"
I can't reproduce any redirection if I click the link.

**Comment by mapx-** [comment]
I can reproduce the issue, I'll add a fix
