### ISSUE TITLE
slink.bid [Anti-Adblock]

### ISSUE THREAD

**Issue by doio** [uBlockOrigin/uAssets#5233]
### URL(s) where the issue occurs
`http://slink.bid/short/SFGuE`

### Versions

- Browser/version: Firefox 67.0 beta 5
- uBlock Origin version: 1.18.11b2

**Comment by ghajini** [comment]
Antiadblock
`https://slink.bid/B3vn`

**Comment by ghajini** [comment]
`https://slink.bid/HBNwjF`
Popup ads
