### ISSUE TITLE
3djuegos.com

### ISSUE THREAD

**Issue by pizza90** [uBlockOrigin/uAssets#5235]
**URL:**
`https://www.3djuegos.com/noticias-ver/191330/cygames-recluta-nuevo-personal-para-abarcar-granblue/`

### Describe the issue

Big annoying AD in background, not blocked correctly.

### Screenshot(s)

https://i.imgur.com/Zf01pKO.jpg

### Versions

- Browser/version: [Chrome - 73.0.3683.86 (Build oficial) (64 bits)]
- uBlock Origin version: [v1.18.10]
- uBlock Extra

### Settings

- [Default Settings]

### Notes

[maybe the filter (marked in the image) needs an adjustment]

**Comment by mapx-** [comment]
Are you using `spa, por: AdGuard Spanish/Portuguese filter` too ?

**Comment by pizza90** [comment]
No "mapx-"

**Comment by okiehsch** [comment]
That list is enabled by default for all users with a spanish browser locale and it fixes the issue on my end.

**Comment by mapx-** [comment]
well, @pizza90  just enable it

**Comment by pizza90** [comment]
ok solved ... I removed that filter list, because it gave me problems in other places.

Thanks.

**Comment by okiehsch** [comment]
If that list gives you problems and you don't want to enable it you can add
````
3djuegos.com#@#.bottomAd
3djuegos.com#@#.ad_300x250
````
to your filter list that should also work.

**Comment by pizza90** [comment]
also works.. but i cant see that filters, in the "module" of filters blocked / disabled.

but works well. thanks.

**Comment by okiehsch** [comment]
> i cant see that filters, in the "module" of filters blocked / disabled.

They are exception filters, meaning they disable the existing cosmetic filters and do not block anything.

**Comment by NubN** [comment]
`https://www.3djuegos.com/`

**AD:** https://i.imgur.com/k7VKTz3.png

working:
`3djuegos.com##[href^="https://www3.smartadserver.com/"]`

**Note:** in this script, (the numbers are changed periodically)
https://i.imgur.com/B0oqfIi.png

**Comment by mapx-** [comment]
`##[href*=".smartadserver.com"]`
@ryanbr
