### ISSUE TITLE
metin2tech.eu

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#5239]
`http://metin2tech.eu/` antiadb
@mapx- @okiehsch 
_default settings_
_browser Fox_

**Comment by JobcenterTycoon** [comment]
`@@metin2tech.eu$generichide` works for me

**Comment by bogachenko** [comment]
> browser Fox

![1](https://user-images.githubusercontent.com/8535285/55157288-f3724b00-5153-11e9-8475-33c1e83eeaf3.gif)

**Comment by JobcenterTycoon** [comment]
> 
> 
@bogachenko 
> > browser Fox
> 
> ![1](https://user-images.githubusercontent.com/8535285/55157288-f3724b00-5153-11e9-8475-33c1e83eeaf3.gif)

`@@metin2tech.eu$generichide` no `@@||metin2tech.eu$generichide`

**Comment by bogachenko** [comment]
it's the same thing
