### ISSUE TITLE
dailycaller.com video broken (EasyList)

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#524]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://dailycaller.com/2017/02/08/sen-tim-scott-reads-his-hate-mail-on-the-senate-floor-i-left-out-all-the-ones-that-used-the-n-word-video/`

### Describe the issue

When EasyList is active, the video in the article will not play.

### Notes

The custom filter provided [here](https://github.com/easylist/easylist/issues/280#issuecomment-278791045) no longer works either.

**Comment by gorhill** [comment]
> When EasyList is active, the video in the article will not play

Report to EasyList maintainers please.

**Comment by terrorist96** [comment]
@gorhill I have. See https://github.com/easylist/easylist/issues/280
They are very inactive on their github issue page. Wouldn't this be good to add to the Unbreak filter?
The whole reason I switched from ABP to uBO was because I got tired of waiting on Easylist maintainers.

**Comment by gorhill** [comment]
Looks like a `|blob:` filter in EasyList in breaking playback. Try:

    @@|blob:$domain=dailycaller.com

**Comment by terrorist96** [comment]
Thanks. That works, but I have to click on the video 3 times before it will play.

**Comment by terrorist96** [comment]
Actually I don't have to click it 3 times. It just stutters for the first second and then it will eventually play again. Without EasyList, the video plays immediately after clicking the big play button on the top left. With EasyList plus the blob filter, the video will play, but is delayed by a few seconds, so it works but not perfectly. Thanks :smiley:
