### ISSUE TITLE
liketvw.com

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#5240]
`liketvw.com`
@mapx- @okiehsch 
antiadbp
spa, por: AdGuard Spanish/Portuguese filter​​​​​ **enabled**
spa: EasyList Spanish **enabled**

**Comment by mapx-** [comment]
I tested 3-4 channels, no anti adb stuff for me. Some specific channel ?

**Comment by bogachenko** [comment]
not. I'm blocked everywhere

**Comment by bogachenko** [comment]
exp `http://www.liketvw.com/embed/telemundo`

**Comment by mapx-** [comment]
- please don't post anymore these horrible gifs
- tested => still ok FF / chrome
- reset to default, test again

**Comment by bogachenko** [comment]
>please don't post anymore these horrible gifs

What are such horrible ?

> reset to default, test again

I checked does not work. ~I can record gif~

**Comment by mapx-** [comment]
Purge caches & update the filter lists

**Comment by mapx-** [comment]
Do you see in the logger ?
`liketvw.com##+js(abort-on-property-write.js, adBlockDetected)`

**Comment by bogachenko** [comment]
I did it here.

>reset to default, test again
I checked does not work. I can record gif

and at all strange all of this.

**Comment by bogachenko** [comment]
> 
> 
> Do you see in the logger ?
> `liketvw.com##+js(abort-on-property-write.js, adBlockDetected)`

yep

**Comment by bogachenko** [comment]
okay, fine. we (you) tried

**Comment by mapx-** [comment]
Are you using some other blocking extension ? Did you test only in opera ?

**Comment by bogachenko** [comment]
Yes. But I turned them off. You can see it on my **horrible** gif.
and I tested it the same way on firefox

**Comment by mapx-** [comment]
maybe @okiehsch could reproduce the issue

**Comment by mapx-** [comment]
try the last filter

**Comment by okiehsch** [comment]
Well, I added the fix 12 hours ago https://github.com/uBlockOrigin/uAssets/commit/7b6b3f5712226159cc8b82ac468a89213e6d78d7
It works for me.
@bogachenko what is the `Fuck Fuckadblock` list you have enabled?

**Comment by bogachenko** [comment]
Strange. Now I have updated your filters, and the site is working. What the heck? What the hell is going on?

**Comment by okiehsch** [comment]
Well, the important thing is that it works ;)
Btw in regards to your gifs, if you post them it is probably better to post a link and not embed them, they can be rather distracting if they play non-stop.

**Comment by bogachenko** [comment]
Good. By the way, it would be great if Github had a function to stop and play gif images.
