### ISSUE TITLE
filter editor search enhancements

### ISSUE THREAD

**Issue by filbo** [uBlockOrigin/uAssets#5241]
Hi,

Within uBO options, when looking at / editing a specific filter list, I was looking for filter lines which would affect github.io.  I searched for `github` and was dismayed to see '1000+' hits in the main 'uBlock filters' list.

Now, there is a trivial workaround for my use case (actually enter `github.io`); but suppose I were truly looking for an issue with github.com?  The 1000+ mentions of `https://github.com/uBlockOrigin/uAssets/issues/%d` would block me completely.

... which led me to wish for two (and a half) things:

1. search-within-list which is comment-sensitive; that is, ignore lines which are comments
  a. suboption which includes comments which are valid rule syntax, ignoring only human-readable comments; obviously, not the default...

2. search-within-list which is domain-sensitive; that is, find rules which match the given domain or domain-wildcard.  This would do wildcard matching in both directions: I enter `github.io`, it matches rules looking for `github.io` and `github.*`; I enter `github.*`, it matches both of those + `github.com`.  Possibly 'domain' is the wrong concept; searching for `*.github.io/*.css` ought to be able to match rules with that specificity.

The UI could look something like:
![uBO-filter-search](https://user-images.githubusercontent.com/3022180/55194168-1c9bd700-5166-11e9-8c09-f5c32fd34ecc.png)

**Comment by okiehsch** [comment]
That should be opened at https://github.com/uBlockOrigin/uBlock-issues/issues
`uAssets` can't modify the search-within-list behaviour that would have to be done in uBO proper.

**Comment by mapx-** [comment]
in notepad++
`\v^([^!].*)?github`

**Comment by filbo** [comment]
Yes, I know how to search for things in a proper editor.  However, that will not at all match uBO's semantic knowledge of URL matching (for the 'Domain match' option).

And yeah, totally screwed up where I put this.  I'll repost it in the right place.
