### ISSUE TITLE
Bomcondutor.pt [anti-adblock]

### ISSUE THREAD

**Issue by RahManJunior** [uBlockOrigin/uAssets#5245]
### URLs where this issue occurs (Required)
`https://www.bomcondutor.pt`
Please use the domain as the title
-->

### Screenshots (Required)
https://i.imgur.com/aodkh7o.png
https://i.imgur.com/If6RiV7.png

### Screenshot of console (Required, press `F12` to open the console)
https://i.imgur.com/CfNrmRC.png

### Describe the issue (Optional if obvious)
Bomcondutor is a driver's license exams site and when you finnish an exam they block out the explanations to the questions if you have adblock on (the explanations are used with disqus)

### Reproduction Steps (Optional if trivial)
Go to "Testes de Codigo", Choose B, Choose any option and then "Iniciar Teste". Finish the exam and then try to read the explanations.

#### Environment (Required)

- Operating System and Version: Windows 10 Po
- Browser and Version: Firefox Quantom 66.0.2 
- Nano Adblocker Version: uBlock Origin 1.18.12 (I now realise maybe this is just for nano adblocker?)
- Nano Defender Version (Optional if you are not using it):  

Nano Defender 15.0.0.112

**Comment by mapx-** [comment]
test this filter
`@@||bomcondutor.pt^$generichide`

**Comment by RahManJunior** [comment]
>  `@@||bomcondutor.pt^$generichide`

Seems to have worked, thank you!

**Comment by RahManJunior** [comment]
> 
> 
> test this filter
> `@@||bomcondutor.pt^$generichide`
