### ISSUE TITLE
suntrust.com EasyPrivacy breaks layout

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#525]
### URL(s) where the issue occurs

`https://onlinebanking.suntrust.com/UI/movemoney#/paybills`

### Describe the issue

With EasyPrivacy active, the page looks like this:

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/28249055-0a9919a0-6a1d-11e7-8239-be01fc54fc47.png)

### Versions

- Browser/version: Chrome 59
- uBlock Origin version: 1.13.2

### Settings

Default

### Notes

Adding this fixes it:
`@@||fls.doubleclick.net/activityi`
Need to be logged in to reproduce.
Already reported [here](https://github.com/easylist/easylist/issues/333) but went ignored. Please add to Unbreak filter.

**Comment by okiehsch** [comment]
As a rule of thumb I will not add a filter for a issue I can't reproduce and  I can't loggin.
Can you post your logger output?

**Comment by terrorist96** [comment]
![image](https://user-images.githubusercontent.com/12802056/28250168-98653b2a-6a30-11e7-9356-6aa7940ec271.png)

**Comment by okiehsch** [comment]
Does 
`||fls.doubleclick.net/activityi$subdocument,redirect=noopframe,domain=suntrust.com`
work?

**Comment by gorhill** [comment]
I suspect this will need a `:style` cosmetic filter, probably the navigation bar at the top is assumed to be under some banner ad pushing it down.

**Comment by terrorist96** [comment]
>Does
||fls.doubleclick.net/activityi$subdocument,redirect=noopframe,domain=suntrust.com
work?

Yes.

**Comment by terrorist96** [comment]
>I suspect this will need a :style cosmetic filter, probably the navigation bar at the top is assumed to be under some banner ad pushing it down.

Could be, but there are no (visible) ads on the site when I disable uBO

**Comment by okiehsch** [comment]
Well is your issue fixed after adding `||fls.doubleclick.net/activityi$subdocument,redirect=noopframe,domain=suntrust.com`
or are there other problems?

**Comment by terrorist96** [comment]
Correct. No other issues once that is added to the Unbreak list.
Thanks!

**Comment by terrorist96** [comment]
### URL(s) where the issue occurs

`https://www2.onlinebanking.suntrust.com/UI/movemoney#/paybills`

### Screenshot(s)

Before:
![image](https://user-images.githubusercontent.com/12802056/93844091-1064dd00-fc6a-11ea-8a6b-61a9fa482ea8.png)

After:
![image](https://user-images.githubusercontent.com/12802056/93843912-8ae12d00-fc69-11ea-9d08-4fe002dd0530.png)


### Notes

`@@||fls.doubleclick.net^$subdocument,domain=billpay.suntrust.com`

**Comment by mapx-** [comment]
did you try a redirect filter like the previous one ?

`||fls.doubleclick.net^$frame,redirect=noopframe,domain=suntrust.com`

**Comment by terrorist96** [comment]
Doesn't work.

**Comment by mapx-** [comment]
could we remove the previous redirecting filter ?

`||fls.doubleclick.net/activityi$frame,redirect=noopframe,domain=suntrust.com,badfilter`

**Comment by terrorist96** [comment]
> could we remove the previous redirecting filter ?
> 
> `||fls.doubleclick.net/activityi$frame,redirect=noopframe,domain=suntrust.com,badfilter`

Yes
