### ISSUE TITLE
blacklistednews.com unblocked ads

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#526]
### URL(s) where the issue occurs

`http://www.blacklistednews.com/`

### Describe the issue

Unblocked ads on the right column. From around the web.
Also ipronetwork ad below that.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/28250437-566f1848-6a36-11e7-9bc0-55cf9098ccd3.png)

![image](https://user-images.githubusercontent.com/12802056/28250439-61009340-6a36-11e7-94c7-c0f972e7050f.png)

### Versions

- Browser/version: Chrome 59
- uBlock Origin version: 1.13.2

### Settings

Default

**Comment by mapx-** [comment]
```
||data.*.com/$domain=blacklistednews.com
||blacklistednews.com/images/July31stPRO.PNG$image
```

**Comment by terrorist96** [comment]
Works. Should be added.
Thanks
