### ISSUE TITLE
ofilmywap.co.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5263]
### URL(s) where the issue occurs

`https://www.ofilmywap.co.com/movie/3066/the-accidental-prime-minister-(2019)-hindi-full-movie.html`

### Describe the issue

popup ads

### Versions

- Browser/version: firefox 66
- uBlock Origin version: 1.18.14

### Settings

-uBO's default settings

**Comment by okiehsch** [comment]
What popups?
You should update your filter list, some guy has opened a whole bunch of issues lately.

**Comment by ghajini** [comment]
OK original issues fixed....but what I see when on Firefox android I.see.multiple download buttons....sometimes I fell to trap of clicking fake one... this is. True for many mobile sites....
