### ISSUE TITLE
theglobeandmail.com

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#5265]
`https://www.theglobeandmail.com/politics/article-federal-budget-expected-to-include-national-electric-vehicle-incentive/`

anti-adblock
@mapx- @okiehsch 
default settings

**if you disable the inline scripts the site works** but it breaks down the functional

pic. https://user-images.githubusercontent.com/5933394/55287405-4703b500-535d-11e9-9b9e-161500ecf97c.png

**Comment by bogachenko** [comment]
do you have thoughts?

**Comment by mapx-** [comment]
It's not anti adb, you'll get same behaviour even disabling uBo, it's paywall.
If you want to read the article (some minor breakage), try:
`||theglobeandmail.com/pb/resources/scripts/build/bundle-runtime.$script,1p`

**Comment by bogachenko** [comment]
Damn it. thank

**Comment by bogachenko** [comment]
> some minor breakage

blat` pictures don't load at all
