### ISSUE TITLE
4pda.ru. Removed links

### ISSUE THREAD

**Issue by Taumer** [uBlockOrigin/uAssets#527]
### URL(s) where the issue occurs

[4pda.ru](https://4pda.ru/forum/index.php?showtopic=783286)

### Describe the issue

Removed links from header post

### Screenshot(s)

[Screenshot with enabled uBlock](http://i.imgur.com/7AigBvr.png)
[Screenshot with disabled uBlock](http://i.imgur.com/PY0NUfe.png)

### Versions

- Browser/version: [Firefox Nightly 56]
- uBlock Origin version: [1.13.4]

### Settings

Default Settings
Filters list:
- uBlock filters
- uBlock filters – Unbreak
- EasyList
- EasyPrivacy
- RU AdList
- [RU AdList: Counters](https://easylist-downloads.adblockplus.org/cntblock.txt)

### Notes

I'm think that the rule `##a[rel][target]:not([attach_id]):has(> img)` from uBlock filters list removing this links
Some DOM without blocker: [gist](https://gist.github.com/Taumer/e8d7346f737ddc21a413337dbf1a5a21)

**Comment by gorhill** [comment]
You will have to provide an exact URL of where the issue can be seen.

**Comment by Taumer** [comment]
Header post at [this topic](https://4pda.ru/forum/index.php?s=&showtopic=783286&view=findpost&p=55002977)
You need open spoilers `Прошивки` and `China`
[Screenshot](http://i.imgur.com/YtlLC0z.png)
