### ISSUE TITLE
vidtodoo.com{Antiadblock}

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5273]
### URL(s) where the issue occurs

`https://vidtodoo.com/oiunmvs6m86s`

### Describe the issue

Antiadblock
Play buttton unclickable
Unblocked 3rd parties

Screenshots =

`https://user-images.githubusercontent.com/20338483/55349118-6529fc00-54a8-11e9-8de1-06bbb17f98d2.jpg`

### Versions

- Browser/version: Firefox android 66
- uBlock Origin version: 1.18.14

### Settings

- uBO's default settings

**Comment by mapx-** [comment]
`Antiadblock`  it's a simple text massage even if uBo is disabled

**Comment by ghajini** [comment]
If player is unclickable then?

**Comment by ghajini** [comment]
It was unable to play video.....so certainly against adblocker.......

**Comment by mapx-** [comment]
Now the `play` is clickable, ate least for me

**Comment by mapx-** [comment]
> It was unable to play video.....so certainly against adblocker.......

I replaced a filter to ulock the `play` button

**Comment by ghajini** [comment]
Yes I confirm that, fixed by your filters
