### ISSUE TITLE
Malware Domain is still targeting my domain as phishing

### ISSUE THREAD

**Issue by seriesgato** [uBlockOrigin/uAssets#5277]
A while ago my domains seriesgato.com was solved of this problem, but now my other domain seriesgato.tv continues having problems with the poster of ublock origin and malwaredomains where it indicates that it contains virus.

Can you help me solve please?

**Comment by mapx-** [comment]
I see no such filter in malware domains and your site is not blocked on my side.
Maybe you already reported to malware domains and they fixed the issue.
