### ISSUE TITLE
uBlock Origin 3rd-party scripts

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#528]
Is there a setting you can add to block 3rd-party scripts on every website instead of having to do that for each website individually from the advanced settings window? This seems to prevent tabs and windows opening automatically and then closing on certain websites. Thanks.

Firefox Developer Edition 55.0b9 (32-bit)
uBlock Origin 1.13.4

**Comment by mapx-** [comment]
go into options, "my rules", add this rule
`* * 3p-script block`

read more about dynamic filtering here:
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-rule-syntax

**Comment by js017** [comment]
Ok. Thanks. Also, with that rule is there a way to allow exceptions for certain websites?

**Comment by okiehsch** [comment]
`github.com * 3p-script noop` for example.
Reading the [Dynamic filtering: quick guide](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide) also helps.
