### ISSUE TITLE
aliexpress.com modal popup

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#5283]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.aliexpress.com/`

### Describe the issue
Modal popup on page load

### Screenshot(s)
![aliexpress](https://user-images.githubusercontent.com/22258847/55489144-5c980980-55ff-11e9-9e76-d1c3ebce1491.png)

### Versions

- Browser/version: Chrome Version 74.0.3729.40 (Official Build) beta (64-bit)
- uBlock Origin version: uBlock Origin 1.18.17b0 (Latest Dev Build)
- uBlock Origin Extra 2.80

### Settings

- Test profile with default settings and lists.

**Comment by nimasaj** [comment]
This filter is preventing shipping options window to open.
Test URL: `https://www.aliexpress.com/item/10Pcs-lot-2-54mm-2-x-40-Pin-Male-Double-Row-Right-Angle-Pin-Header-Strip/32951553145.html`
Picture: `https://pasteboard.co/I95axav.png`

**Comment by mapx-** [comment]
test these filters
```
aliexpress.com#@#.ui-mask, .ui-window
aliexpress.com##.close-layer:xpath(..)
aliexpress.com##.ui-mask
```

**Comment by nimasaj** [comment]
I can confirm that these filters do not intervene on shipping pop up.

**Comment by mapx-** [comment]
ok, I'll add (replace) them to annoyances list

**Comment by ediowar** [comment]
But now you can not change the country, language and currency

**Comment by mapx-** [comment]
I 'm able to change currency, language, do I need an account ?

**Comment by ediowar** [comment]
This is my mistake, used the medium mode.

**Comment by krystian3w** [comment]
#6184 ?

**Comment by ediowar** [comment]
These rules are obsolete and can be removed
```
! https://github.com/uBlockOrigin/uAssets/issues/5283
aliexpress.com,aliexpress.ru##.close-layer:xpath(..)
aliexpress.com,aliexpress.ru##.ui-mask
! https://github.com/uBlockOrigin/uAssets/issues/6184
aliexpress.com,aliexpress.ru##.next-overlay-wrapper:has(.newuser-container)
aliexpress.com,aliexpress.ru##body:style(overflow: auto !important; padding: 0 !important;)
! https://github.com/uBlockOrigin/uAssets/issues/6551
aliexpress.com,aliexpress.ru##.ui-newuser-layer-dialog.ui-window-transition.ui-window-normal.ui-window
```

**Comment by krystian3w** [comment]
Or your account is marked as "oldie"?

**Comment by ediowar** [comment]
Hastened, when clicking on short links (ali.pub) the message "New user" pops up.

**Comment by ediowar** [comment]
Filters 
```
! https://github.com/uBlockOrigin/uAssets/issues/5283
aliexpress.com,aliexpress.ru##.close-layer:xpath(..)
aliexpress.com,aliexpress.ru##.ui-mask
! https://github.com/uBlockOrigin/uAssets/issues/6184
aliexpress.com,aliexpress.ru##.next-overlay-wrapper:has(.newuser-container)
aliexpress.com,aliexpress.ru##body:style(overflow: auto !important; padding: 0 !important;)
! https://github.com/uBlockOrigin/uAssets/issues/6551
aliexpress.com,aliexpress.ru##.ui-newuser-layer-dialog.ui-window-transition.ui-window-normal.ui-window
```
no longer work. They need to be replaced with `aliexpress.com,aliexpress.ru##.coupon-poplayer-modal`
