### ISSUE TITLE
mlbshop.com modal popup

### ISSUE THREAD

**Issue by yourduskquibbles** [uBlockOrigin/uAssets#5284]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.mlbshop.com/`

### Describe the issue
Modal popup on page load

### Screenshot(s)
![mlbshop](https://user-images.githubusercontent.com/22258847/55489421-e21bb980-55ff-11e9-9768-42211375b5a9.png)

### Versions

- Browser/version: Chrome Version 74.0.3729.40 (Official Build) beta (64-bit)
- uBlock Origin version: uBlock Origin 1.18.17b0 (Latest Dev Build)
- uBlock Origin Extra 2.80

### Settings

- Test profile with default settings and lists.

### Notes

The same "deal" content displayed in the popup is also clearly displayed in header of the page so this is unnecessary annoyance popup requiring extra clicks to dismiss

**Comment by krystian3w** [comment]
@yourduskquibbles pop-up maybe was removed or no longer block scroll - then does not meet the requirement of reaching for the advanced syntax like `:style(`.
