### ISSUE TITLE
Wrong `Last updated` line in uBlock filters

### ISSUE THREAD

**Issue by mikhaelkh** [uBlockOrigin/uAssets#5287]
### Describe the issue
`! Last updated: 2017-10-10` in [uBlock filters](https://github.com/uBlockOrigin/uAssets/blob/206ccdfce606a13456610b86fe58eef1e767066f/filters/filters.txt#L15
)

### Versions
- Browser/version: Chromium 72.0.3626.121 (Official Build) (64-bit) 
- uBlock Origin version: v1.18.17b1

**Comment by mapx-** [comment]
It's about the date for the google filters bellow
```
! The following filters were taken out of EasyList and given an entity name,
! which makes them candidates to be injected early in the page.
! Last updated: 2017-10-10
google.*###center_col > #\5f Emc
```
