### ISSUE TITLE
elpais.com

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#5288]
### URL(s) where the issue occurs

`https://elpais.com/internacional/2019/04/03/actualidad/1554297555_947058.html`

### Describe the issue

[Anti Adblock]

### Screenshot(s)

`https://i.imgur.com/Fcw1WZn.png`

### Versions

- Browser/version: [Chrome: 73.0.3683.86 (Build oficial) (64 bits)]
- uBlock Origin version: [v1.18.16]
- uBlock Extra
### Settings

- [Default Settings]

**Comment by lain566** [comment]
Can't reproduce.

**Comment by okiehsch** [comment]
I can but only if I use a spanish IP, no issue with a US IP.

**Comment by lain566** [comment]
I have a Spanish IP and I can't reproduce,  weird.

**Comment by okiehsch** [comment]
Weird indeed, I tried a few random EU-IP's and I only see the ``google funding choices` message with the spanish IP, all others work without issue.

**Comment by pizza90** [comment]
at the moment solved with: `@@||elpais.com^$generichide`

without that filter i get anti adblock 

i update the filters but not in the lists, maybe I'll have to wait ^^ thanks "okiehsch"

**Comment by okiehsch** [comment]
> maybe I'll have to wait

You have to wait 4-5 minutes after the commit before the update will include it.
If you have manually updated the list in the last hour it can take longer.

**Comment by PIZZA90** [comment]
Self-promo Ad suscription blocked:

![Captura01](https://user-images.githubusercontent.com/33556647/123522924-e345cf00-d6c0-11eb-9711-385e80c5a6cc.PNG)

`krxd.net`

**Comment by mapx-** [comment]
I can see that subscription here:
https://elpais.com/economia/2021-06-26/los-interinos-podran-entrar-en-las-bolsas-de-trabajo-aunque-suspendan-la-oposicion.html

![image](https://user-images.githubusercontent.com/10303732/123523711-99abb300-d6c5-11eb-87b9-26225652d2ad.png)

**Comment by PIZZA90** [comment]
video break:
`https://elpais.com/internacional/2022-04-12/putin-advierte-de-que-no-parara-su-ofensiva-en-ucrania-hasta-controlar-donbas.html`

**Comment by stephenhawk8054** [comment]
> video break: `https://elpais.com/internacional/2022-04-12/putin-advierte-de-que-no-parara-su-ofensiva-en-ucrania-hasta-controlar-donbas.html`

I can play the video normally, can you copy paste your `Troubleshooting Information`?

**Comment by PIZZA90** [comment]
```
uBlock Origin: 1.42.4
Chromium: 100
filterset (summary): 
  network: 83309
  cosmetic: 48209
  scriptlet: 19460
  html: 0
listset (total-discarded, last updated): 
  removed: 
    ublock-quick-fixes: null
  added: 
    ublock-annoyances: 4324-7, now
  default: 
    user-filters: 0-0, never
    easylist: 65762-51, now
    easyprivacy: 26778-121, now
    plowe-0: 3687-808, now
    spa-0: 3869-34, now
    spa-1: 4334-168, now
    ublock-abuse: 74-0, now
    ublock-badware: 4057-93, now
    ublock-filters: 30506-152, now
    ublock-privacy: 208-2, now
    ublock-unbreak: 1752-43, now
    urlhaus-1: 7267-0, now
filterset (user): [empty]
trustedset: 
  added: [array of 4 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 163 ms (selfie)
  maxAssetCacheWait: 166 ms

```

**Comment by PIZZA90** [comment]
I need whitelist this filter in annoyances: `elpais.com##+js(nostif, run)`  for make work the video

**Comment by PIZZA90** [comment]
this filter was very good anyways `elpais.com##+js(nostif, run)` 😂😂

whit that filter I dont need subscription for read the articles 😭😭

**Comment by stephenhawk8054** [comment]
> this filter was very good anyways `elpais.com##+js(nostif, run)` 😂😂
> 
> whit that filter I dont need subscription for read the articles 😭😭

Yeah, I'm finding if there would be a better way for incognito detection.

**Comment by Yuki2718** [comment]
@PIZZA90 Test `elpais.com##+js(aost, ArcPOptions.paywallFunction, setTimeout)`

**Comment by PIZZA90** [comment]
What I need test.. or what should that filter do? 🤔

**Comment by Yuki2718** [comment]
Add the rule to My filters and Incognito won't be detected. Video works fine on my end with the rule although I have to click play button two times.

**Comment by PIZZA90** [comment]
I need click 2-3 times.. whit that filter too

**Comment by Yuki2718** [comment]
> I need click 2-3 times.. whit that filter too

It seems the behavior is same even without the filter.

**Comment by PIZZA90** [comment]
but is very good filter: `elpais.com##+js(aost, ArcPOptions.paywallFunction)` remove the account required for read posts 

example here:
`https://elpais.com/espana/2022-04-13/barometro-del-cis-el-pp-se-dispara-tras-la-llegada-de-feijoo-mientras-vox-frena-su-ascenso.html`

😍

**Comment by stephenhawk8054** [comment]
> @PIZZA90 Test `elpais.com##+js(aost, ArcPOptions.paywallFunction, setTimeout)`

Hmm... I still get incognito detected with that filter

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/163168606-c1a086a3-b00d-4a3b-be8f-d287f4949748.png)

</details>

**Comment by Yuki2718** [comment]
Yep, sometimes fails.

**Comment by stephenhawk8054** [comment]
> Yep, sometimes fails. Or do you get consistent result?

Yeah, I got consistent results with it.

**Comment by Yuki2718** [comment]
Does changing to `elpais.com##+js(aost, ArcPOptions.paywallFunction)` solves that?

**Comment by stephenhawk8054** [comment]
> Does changing to `elpais.com##+js(aost, ArcPOptions.paywallFunction)` solve that?

Yeah, I tried that before. It does remove incognito detection but the video won't play when clicking on it.

**Comment by Yuki2718** [comment]
Hmm, it seems even with setTimeout specified video doesn't play on private winodw.

**Comment by Yuki2718** [comment]
Okay, this is by design - the site requires cookie to play the video.

**Comment by PIZZA90** [comment]
🤔 No way for play video again.. even whit any of the filter of this post

example here:
`https://elpais.com/internacional/2022-04-13/mujeres-y-ninas-como-botin-de-guerra-ucrania-denuncia-violaciones-por-soldados-rusos-en-zonas-ocupadas.html`

**Comment by PIZZA90** [comment]
gallery break ( click in image )
`https://elpais.com/elpais/2022/04/27/album/1651083038_527904.html#foto_gal_2`

**Comment by Branzeturi** [comment]
> gallery break ( click in image ) `https://elpais.com/elpais/2022/04/27/album/1651083038_527904.html#foto_gal_2`

@PIZZA90 


@ryanbr `@@||elpais.com/t.gif$image,1p`

**Comment by PIZZA90** [comment]
Sorry guys... but why and what is unfixable here? I do not really understand very well this issue. I mean the "**can't fix**"

**Comment by Yuki2718** [comment]
Blocking the modal without side effect?

**Comment by PIZZA90** [comment]
I dont get anti adblock, what modal is? 😅

**Comment by Yuki2718** [comment]
I thought subscription modal https://github.com/uBlockOrigin/uAssets/issues/5288#issuecomment-1097505808

**Comment by PIZZA90** [comment]
Example videos:

```
https://elpais.com/economia/2022-06-12/de-compras-en-la-primera-tienda-fisica-de-moda-de-amazon-es-el-futuro.html
https://elpais.com/internacional/2022-06-13/melenchon-se-consolida-en-las-elecciones-legislativas-de-francia-como-principal-rival-de-macron.html
```

About the `2-3 click` for play the video, At least for me.. whitelisting this: `@@||pxlctl.elpais.com/pxlctl.gif` i cant reproduce the problem 😅

**Comment by mapx-** [comment]
> About the 2-3 click for play the video

1 click and the video is running fine

**Comment by PIZZA90** [comment]
yeah my bad, I didn't give uBO time to load.. if i wait 4-5 seconds no problem after refresh page XD
