### ISSUE TITLE
verpelis.info

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#5289]
### URL(s) where the issue occurs

`https://verpelis.info/movies/nancy-drew-y-la-escalera-secreta/`

### Describe the issue

There's a popup.

### Versions

- Browser/version: Chrome 73
- uBlock Origin version: 1.18.16

### Settings

- Default settings.

**Comment by lain566** [comment]
Can't get the download link if uBO is enabled, it only works the first time you try.
These filters fix it, same as https://github.com/uBlockOrigin/uAssets/issues/5270
```
verpelis.info##[class^="get-enlace"]:style(display: block !important;)
verpelis.info###fake
```



![Anotación 2019-04-04 020702](https://user-images.githubusercontent.com/27441315/55520877-a83dc800-567e-11e9-9b8d-9338bbad77e3.png)

**Comment by lain566** [comment]
There's a popup when clicking anywhere
`https://verpelis.info/ver-capitulo-online/`

**Comment by mapx-** [comment]
I cannot reproduce the issue

**Comment by lain566** [comment]
Try to delete cookies from the site

**Comment by mapx-** [comment]
does this work ?
`verpelis.info##+js(popads-dummy.js)`

**Comment by lain566** [comment]
Yes, that works
