### ISSUE TITLE
beta.tunein.com

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#529]
beta.tunein.com

When you go to this website it doesn't display the page properly and the search bar doesn't work, but if you add tunein.com to uBlock Origin's Whitelist and reload the page, then it displays everything properly.

![beta tunein com](https://user-images.githubusercontent.com/26278182/28251544-ad9cb1a4-6a4d-11e7-975e-67647f918b87.jpg)

Firefox Developer Edition 55.0b9 (32-bit)
uBlock Origin 1.13.4

**Comment by SMed79** [comment]
Test this filter
`@@||files.ampush.io/js/tracker.js$script,domain=tunein.com`
(https://forums.lanik.us/viewtopic.php?f=64&t=37550)

**Comment by js017** [comment]
Yeah that works. How do you find filters like that when you need them for certain websites? If I knew how to find filters, or if uBlock Origin could just work properly with every website automatically, then I wouldn't need to post anything on the forums. Thanks.


Sent: Sunday, July 16, 2017 at 6:07 PM
