### ISSUE TITLE
polsatnews.pl [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5291]
URL(s) where the issue occurs

`http://www.polsatnews.pl/wiadomosc/2019-04-04/po-wypadku-w-puszczykowie-kierowca-karetki-w-stanie-spiaczki-farmakologicznej/?ref=slider`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 73 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.18.14

Settings

Default

**Comment by krystian3w** [comment]
Hello "Speedy Gonzales"

now maybe better moddify to:

```
@@||gapl.hit.gemius.pl/gplayer.js$domain=redefine.pl
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=redefine.pl|redcdn.pl|polsatnews.pl|polsatsport.pl|twojapogoda.pl
```

https://github.com/AdguardTeam/AdguardFilters/commit/e4f63fec53c7ab85a5a7dde9c911be46b7c485ab

And maybe better give few days for @olegwukr.
