### ISSUE TITLE
priluki.bankomap.com.ua {antiadb}

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#5294]
`http://priluki.bankomap.com.ua`

@mapx- @okiehsch  why is this not working? explain plz

`bankomap.com.ua#$#.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links {display:block!important;}`

default settings

**Comment by mapx-** [comment]
Don't post here adguard issues.

**Comment by bogachenko** [comment]
But the site does not work for you either.

**Comment by mapx-** [comment]
ok, that's anti adb, but you posted an adguard filter.

**Comment by mapx-** [comment]
test
`@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js$script,domain=priluki.bankomap.com.ua`

**Comment by okiehsch** [comment]
Your filter works fine on my end but you also have to allow the request **mapx-** mentioned.

**Comment by bogachenko** [comment]
I tried it already, did not work @mapx-

**Comment by okiehsch** [comment]
Works for me, what about 
`@@||bankomap.com.ua^$generichide`

**Comment by bogachenko** [comment]
nope, I do not have @okiehsch

**Comment by mapx-** [comment]
well:

```
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js$script,domain=priluki.bankomap.com.ua
!bankomap.com.ua##.pub_300x250.pub_300x250m.pub_728x90.text-ad.textAd.text_ad.text_ads.text-ads.text-ad-links:style(display:block!important;)
```
or
```
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js$script,domain=priluki.bankomap.com.ua
@@||bankomap.com.ua^$generichide
```

**Comment by okiehsch** [comment]
Yes, both sets work for me using Chromium or Firefox.

**Comment by bogachenko** [comment]
```
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js$script,domain=priluki.bankomap.com.ua
@@||bankomap.com.ua^$generichide
```

**Comment by mapx-** [comment]
ok @bogachenko  ?

**Comment by okiehsch** [comment]
Maybe add 
`bankomap.com.ua##.adsbygoogle`
to remove the space we caused by the generic hide filter.

**Comment by bogachenko** [comment]
ye ok. this site works
