### ISSUE TITLE
Inquirer.net - Video playback issue (uBlock Legacy fix needed)

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uAssets#5295]
### Affected site:
`https://www.inquirer.net/`

### Issue:
15 seconds delay before video playback starts.

### Note:
Chromium browsers seems to be unaffected.

### Examples:
`https://videos.inquirer.net/`

### Problem filter:
* EasyList:
`||aniview.com^$third-party`

### Filter suitable for a potential fix:
* uBlock filters - Legacy
(unless some other browsers are affected too, besides Pale Moon)

### Possible fix (seems to fix the issue at my end):
`@@||player.aniview.com/script/*/AVmanager.js$domain=inquirer.net`

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.4.1 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.10 (XUL)

**Comment by mapx-** [comment]
same delay in FF 67
