### ISSUE TITLE
watchfreexxx.net (NSFW)

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#5297]
### URL(s) where the issue occurs

`[watchfreexxx.net]`

### Describe the issue

[Popups when clicking anywhere.]

### Versions

- Browser/version: [73.0.3683.103]
- uBlock Origin version: [1.18.16]

### Settings

- [default]

**Comment by JobcenterTycoon** [comment]
@okiehsch On this site are unblocked ads
