### ISSUE TITLE
veedi.com detects adblocking

### ISSUE THREAD

**Issue by josephcsible** [uBlockOrigin/uAssets#530]
### URL(s) where the issue occurs

http://www.bubblebox.com/gameinfo/pretentious5.htm?utm_source=notdoppler.com/&utm_medium=brandedgames&utm_campaign=pretentious5&utm_content=walkthrough
Note that the adblocking detection in question is all from a veedi.com iframe, but accessing the page outside of the iframe doesn't work at all.

### Describe the issue

Ten seconds after the video starts playing, a box saying "AdBlocker detected" pops up over it.

### Versions

- Browser/version: 64-bit Firefox 52 on Ubuntu 16.04
- uBlock Origin version: 1.13.4

### Settings

- All default

### Notes

I first noticed that the page contains an inline script that does `var adBlocker = true;`. It then tries to load http://www.veedi.com/player_v/player_sdk/js/ads/advert.js (which is blocked by `/advert.` in EasyList) that contains `adBlocker = false;`. Later on, it checks adBlocker and interrupts the video if it's true. I tried just adding this exception rule:
```
@@http://www.veedi.com/player_v/player_sdk/js/ads/advert.js
```
But this made the video not play at all. I then looked in http://player.h-cdn.com/loader.js?customer=veedi which does a two-pronged test for ad blocking: trying to load the script [http://player.h-cdn.com/ads.js.](http://player.h-cdn.com/ads.js.) (note the dot on the end), and testing element hiding. I added these rules to bypass these checks:
```
@@http://player.h-cdn.com/ads.js.
@@||veedi.com^$generichide
@@||bubblebox.com^$generichide
```
However, this was still ineffective. After further trial and error, I discovered that this rule alone works:
```
@@https://ad.doubleclick.net/favicon.ico?ad=300x250&ad_box=1&adnet=1&showad=1&size=250x250
```
I stopped digging at this point. I don't know why this works and the other rules don't, but it does.

**Comment by okiehsch** [comment]
I can't reproduce usingFirefox, the video play without issue.
I can however reproduce using Chrome,
````
||ad.doubleclick.net/favicon.ico$xmlhttprequest,redirect=32x32-transparent.png,domain=veedi.com
````
fixes the issue on my end, you would have to tell if this works for you using Firefox.

**Comment by josephcsible** [comment]
That works for me in both Firefox and Chrome.

**Comment by okiehsch** [comment]
Thanks for investigating by the way, makes it much easier for me.
