### ISSUE TITLE
http://btkitty.pet [NSFW]

### ISSUE THREAD

**Issue by bobsage123** [uBlockOrigin/uAssets#5300]
`http://btkitty.pet`

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

On the right side of the screen (highlighted in yellow below) a popup box is popping up. The actual ad inside is blocked, but you can still see the "X" to close the popup moving up and down

### Screenshot(s)
NSFW
`https://i.imgur.com/HhFwZi1.png`

### Versions

- Browser/version: Chrome latest
- uBlock Origin version: Latest

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
I cannot reproduce Using the chinese lists.
