### ISSUE TITLE
Twitch browse infinite scrolling not working

### ISSUE THREAD

**Issue by LeMarkel** [uBlockOrigin/uAssets#5302]
### URL(s) where the issue occurs

`https://www.twitch.tv/directory/all`
Same issue on almost any page of twitch with infinite scrolling.

### Describe the issue

Infinite scrolling does not work.

### Screenshot(s)

N/A - No visual issues.

### Versions

- Browser/version: Chrome - Consistent for months on several versions.
- uBlock Origin version: 1.18.16

### Settings

Default uBlock settings other than toggling costmetic filtering on and off for twitch.tv only.

### Notes

Inconsistently works when toggling cosmetic filtering (from on to off OR off to on) after refresh but will stop working randomly.

Seems to work 100% properly while uBlock Logger is open and logging on the page.

**Comment by mapx-** [comment]
Are you using some other blocking extension ?

**Comment by LeMarkel** [comment]
> Are you using some other blocking extension ?

The only other extension I have with permissions for twitch.tv is FrankerFaceZ (Version: 1.57) and as far as I know it doesn't block ads.  That being said, it definitely changes the UI of Twitch quite a bit.

Sorry, I should have thought of FFZ and experimented before posting.  I doubt FFZ is interfering but if I've learned anything from very rudimentary coding experience is that nothing plays nicely together.  I'll experiment more and reply when I can.

**Comment by LeMarkel** [comment]
> I'll experiment more and reply when I can.

That was quick.  Really easy to reproduce with FrankerFaceZ 1.57 enabled but it's still inconsistent. Sometimes works fine but cuts out a few "pages" down.  Shift+F5 no more than 1-2 times and it happens for sure.

Any chance these conflicting extensions could worth together in the future?  Personally they're both must-haves for my viewing preferences.

**Comment by mapx-** [comment]
You should report the issue at FrankerFaceZ repository
