### ISSUE TITLE
dausel.co [Anti-Adblock]

### ISSUE THREAD

**Issue by Robbie8592** [uBlockOrigin/uAssets#5304]
### URL(s) where the issue occurs

`https://dausel.co/oSjgj`

### Describe the issue

Getting a banner to disable my adblocker

### Screenshot(s)

![image](https://user-images.githubusercontent.com/29841633/55676711-85422c80-58a7-11e9-8e51-aad30759d9c2.png)

### Versions

- Browser/version: Firefox 66.0.2
- uBlock Origin version: 1.18.16

### Settings

Default Settings

### Notes

None

**Comment by KiLL4FuNK** [comment]
do not use several blockers

**Comment by KiLL4FuNK** [comment]
do not use several blockers together
