### ISSUE TITLE
Adding defunct or abused ex-list-hosting domains to Badware Risks

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#5307]
There's been made a fair few adblock lists over the years, a loose estimate being just north of two thousand. Some of those lists have also gone missing over the years, and may even have had the domains they were hosted on lapse. This could potentially lead to problems if people come across old links on forums to adblock lists, and click on them in the hopes of adding them to their adblockers, only for it to turn out that the domains have been picked up by shady people who use them for ads, malvertising, adclicker schemes, or potentially worse.

Snapped up and abused by shady parties (Accurate as of a few months ago):
* `adblock.gjtech.net` (Used to host *G&J Hosts*)
* `spam404bl.com` (Used to host *Spam404*)
* `securemecca.com` (Used to host *BadHosts*)

Currently shows 404 error pages (but who's to say they won't be snapped up in the future?):
* `hufilter.hu` (Used to host *hufilter*)
* `fredfiber.no` (Used to host *Norsk Adblockliste*)

Of particular note, is that AdAway *[spit]* still lists `adblock.gjtech.net` and `securemecca.com` [on their wiki](https://github.com/AdAway/AdAway/wiki/HostsSources) as vouched-for hosts files, and they're so slow at going through their issue reports that they'd probably never remove those links either.

Since none of the four anti-malware-specific 3rd-party lists that are included in uBO specialise in dealing with these kinds of problems, I recommend adding them to *uBlock Filters - Badware Risks*, or arguably even to the main *uBlock Filters*.

### Versions

- Browser/version: Google Chrome 73.0.3683.103 64-bit for Windows
- uBlock Origin version: Nano Adblocker 1.0.0.103

### Notes

I was tempted to also mention `startshop.no` as an ex-hosting site, but since it was a cashback service that took their money and ran, and whose whitelist for adblockers was not widely mentioned on forums or such, I figured it wouldn't be worth the effort to include it in *Badware Risks*.

**Comment by mapx-** [comment]
Could you prepare a PR ?

**Comment by DandelionSprout** [comment]
Indeed I can. Give me 15min.

**Comment by mapx-** [comment]
thx
