### ISSUE TITLE
Gazeta.ru dynamic ads cant be blocked at all by uBlock. Adguard extension blocks them however so its possible.

### ISSUE THREAD

**Issue by apassiou** [uBlockOrigin/uAssets#531]
### URL(s) where the issue occurs

`https://www.gazeta.ru/`

### Describe the issue

The site (and a lot of other sites) are starting use randomly generated ads. So blocking them with right click selector only blocks them until you refresh the page. AdGuard (extension not binary that you install) figured out how to block them. We need this functionality in uBlock.

After you load the page the ads load last, so give it about 5 seconds for them to pop up.

### Screenshot(s)
The ads are highlighted.
http://imgur.com/a/xbUUX

### Versions

- Browser/version: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- uBlock Origin version: 1.13.2

### Settings

Using the following filters, no other changes were made:
uBlock filters
uBlock filters - Badware risks
uBlock filters - Privacy
uBlock filters - Unbreak

Adblock warning Removal List
Anti-Adblock Killer | Reek
EasyList

EasyPrivacy

Malware Domain List
Malware domains

Peter Lowe's Ad and tracking server list

Rus: Adguard Russian Filter
Rus: BitBlock List
Rus: Ru AdLIst

### Notes

It appears that the URL changes every time you reload the page. Blocking element blocks it for that session but upon page reload the ads are back. Source for ads is yaindex direct (Яиндекс Директ). 

Example element: 

Element name example:
##.sausage-list-item.news_title.mtojdoo--uruvwmi.mtojdoo
after reloading the page it changed to:
##.sausage-list-item.news_title.jdrtufcasmx--nrfvanv.jdrtufcasmx
after reloading again changed to:
##.sdsrx--ryyaiiublj.sdsrx.sausage-list-item.news_title

and so on...

Installing the Chrome extension AdGuard without doing anything extra (other than subscribing to the Russian lists) it blocks everything successfully. So it is possible to do with a Chrome extension.

It appears that AdGuard is using this to block it but manually adding this list to custom lists in Ublock did not block the ads, so they are doing something extra:
https://github.com/AdguardTeam/AdguardFilters/blob/master/RussianFilter/sections/antiadblock.txt

**Comment by gorhill** [comment]
If I import Adguard scriptlet used for `gazeta.ru` as is, it works.

**Comment by apassiou** [comment]
Can you explain how to do that? And can it be incorporated into uBlock to be automatic (without users having to import stuff) ?

**Comment by gorhill** [comment]
I will import into uBO (AG also imported some uBO code into that `antiadblock.txt` file). Ideally it would be nice to merge efforts for anti-blocker scriptlets, but uBO and AG have a different approach on how to declare scriptlets.

**Comment by sergeevabc** [comment]
This solution seems to break display of comments on lenta.ru ([example][1]).

[1]: https://lenta.ru/comments/news/2017/07/21/sanders/
