### ISSUE TITLE
adback anti adblock

### ISSUE THREAD

**Issue by smed79** [uBlockOrigin/uAssets#5310]
adback anti adblock
```
lippycorn.com,catracalivre.com.br,enfermeriahoy.com##+js(abort-on-property-read.js, require)
||lansdaleweare.com^
```
(related https://github.com/uBlockOrigin/uAssets/issues/3818)

**Comment by mapx-** [comment]
I get no anti adb stuff on `catracalivre.com.br`, could you check again ?

**Comment by mapx-** [comment]
hmm, I get anti adb on video, but a generichide will fix it

**Comment by mapx-** [comment]
thx
