### ISSUE TITLE
emeraldchat.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#5312]
### URL(s) where the issue occurs

`https://www.emeraldchat.com/app`

### Describe the issue

This overlay annoyance keeps appearing at random times while you're chatting. People are already invited to register on the front page and can do it manually at any time from the menu.

### Screenshot(s)
![emerald](https://user-images.githubusercontent.com/35470489/55693322-eee43880-5984-11e9-9878-5e424a611d50.png)

### Versions

- Browser/version: Firefox 66
- uBlock Origin version: 1.18.16

### Settings
Adguard and uBlock Origin annoyances.

**Comment by mapx-** [comment]
Does this filter work for you ?
`emeraldchat.com##.notification-hatch`

**Comment by smed79** [comment]
```
||emeraldchat.com/user_is_temp
```

**Comment by adranger** [comment]
@smed79's suggestion seems to be the best. It has worked for me.

**Comment by smed79** [comment]
Why `/sw.js` ?
