### ISSUE TITLE
wastedamateurs.com [NSFW]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#5313]
### URL(s) where the issue occurs

`http://www.wastedamateurs.com/`

### Describe the issue

"popup" + redirection after clicking LMB anywhere on the page, at the first visit

### Versions

- Browser/version: Firefox 66.0.2 64bit / Opera 58 64bit
- uBlock Origin version: 1.18.17b1

### Settings

default

### Notes

Some example solutions:  `noeval.js`, `silent-noeval.js`, `noeval-if.js`

**Comment by mapx-** [comment]
Even with uBo disabled the videos / pages are broken

> Unable to perform query.
> More details about the event below:
> Field 'u_todays_in' doesn't have a default value
