### ISSUE TITLE
8buzz.fr

### ISSUE THREAD

**Issue by smed79** [uBlockOrigin/uAssets#5318]
anti adblock

```
https://8buzz.fr/wp-content/plugins/detect-adblock/js/ads.js
```
https:\/\/8buzz.fr/

**Comment by mapx-** [comment]
already in ublock filters
`@@/wp-content/plugins/detect-adblock/js/ads.js$first-party,script`

**Comment by smed79** [comment]
Sorry, the filter list has been disabled.
