### ISSUE TITLE
playbill.com

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#532]
Hi,

**URL**

`http://www.playbill.com/`

**Describe the issue**

Unblocked ads

**Screenshot**

- https://user-images.githubusercontent.com/1355374/28252100-d6dc8a84-6a49-11e7-8008-7c45591afcb9.png
- https://user-images.githubusercontent.com/1355374/28252106-f5232fa2-6a49-11e7-9d12-050134c5eaca.png

**Versions**

uBlock Origin 1.13.4 / Firefox 54 (64bit)

**Settings**

default settings

**Note**

source https://forums.lanik.us/viewtopic.php?f=62&t=37551

**Comment by okiehsch** [comment]
Looks like `uponit`, so we can use
`playbill.com##script:inject(noeval.js)`, or
`playbill.com##script:inject(abort-on-property-write.js, upManager)`, or
`||playbill.com^$csp=script-src 'self' * 'unsafe-inline' data:`.
all three solutions work on my end without any site breakage I can see.
@gorhill if all work which one do you prefer?

**Comment by gorhill** [comment]
I would say the `csp=` one, it can't be raced -- the `upManager` one is rather close to the top of the file.
