### ISSUE TITLE
www.digitaltrends.com anti-adblocker

### ISSUE THREAD

**Issue by joshua-friede** [uBlockOrigin/uAssets#5320]
### URL(s) where the issue occurs

`https://www.digitaltrends.com/photography/canon-eos-rebel-sl3-news/`

### Describe the issue

"Please allow ads" dialogue

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7959266/55850965-51237180-5b1c-11e9-89ba-eabb0ae1bb1b.png)

### Versions

- Browser/version: Google Chrome Version 73.0.3683.86 (Official Build) (64-bit)
- uBlock Origin version: 1.18.16

### Settings

- enable Adblock Warning Removal List

### Notes
I noticed that blocking the domain `fundingchoicesmessages.google.com` gets rid of the problem

**Comment by DandelionSprout** [comment]
Although this has thankfully already been reported and fixed (considering that I was about to report it myself just now), it seems to me personally that `digitaltrends.com##.fc-ab-root` could be an alternative and more broadly supported option.

**Comment by okiehsch** [comment]
> it seems to me personally that digitaltrends.com##.fc-ab-root could be an alternative and more broadly supported option.

The proper alterantive is
````
digitaltrends.com##.fc-ab-root
digitaltrends.com##body:style(overflow: auto !important;)
````
because your filter would remove the scrollbar.
I prefer to avoid the detection and the unnecessary third-party requests.

I am not sure what you mean by "more broadly supported option".

**Comment by DandelionSprout** [comment]
>The proper alternative would be (…) because your filter would remove the scrollbar.

Ah. Good catch.

>I am not sure what you mean by "more broadly supported option".

At the time, when I presumed that `digitaltrends.com##.fc-ab-root` was the only needed entry in my approach, such an entry would've also been usable for users of ABP/AB/AdGuard, and could've plausibly be submitted to AdGuard Base or ABP Anti-Circumvention.

**Comment by okiehsch** [comment]
Adblock/Pus will not add filters that circumvent anti-adblock walls, so submitting such rules is pointless anyway.
Adguard has some weird policy which I don't understand, basically they consider some anti-adblock walls to be paywalls and won't circumvent them.
digialtrends is one of those sites https://github.com/AdguardTeam/AdguardFilters/issues/29831#issuecomment-473304004

**Comment by DandelionSprout** [comment]
ABP started [its own anti-anti-adblock list](https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt) last year or late 2017, but it's painfully underdeveloped compared to e.g. *Nano Defender Integration*.

As for AdGuard's stance on it: I can kiiiind-of understand that they'd see it as a paywall, except I don't really think it truly is...

**Comment by okiehsch** [comment]
Their anti-adblock list only covers ad-reinsertion https://github.com/abp-filters/abp-filters-anti-cv#introduction
It will not cover anti-adblock walls https://github.com/abp-filters/abp-filters-anti-cv/issues/21#issuecomment-441550520

About adguard, I can see the reasoning behind their policy, it is how they apply it that I find difficult to comprehend.
What is the difference between digitaltrends and other sites using an anti-adblock wall covered in 
https://github.com/AdguardTeam/AdguardFilters/blob/master/EnglishFilter/sections/antiadblock.txt

Anyway this repo is about uBO, so I would not change the filters even if you filters could be added to other adblockers.
