### ISSUE TITLE
dailymail.co.uk

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#5321]
### URL(s) where the issue occurs

`https://www.dailymail.co.uk/health/article-6906593/Governments-plan-ban-junk-food-adverts-9pm-cut-just-TWO-calories-day.html`

If you don't see it, open the front page instead and then click on this headline.

### Describe the issue

Popup annoyance while browsing on a tablet.

### Screenshot(s)

![Screenshot](https://user-images.githubusercontent.com/35470489/55868992-f4e04200-5b5b-11e9-96ad-8b50d6d7313c.png)

### Versions

- Browser/version: `Mozilla/5.0 (Android 7.1.2; Tablet; rv:66.0) Gecko/66.0 Firefox/66.0`
- uBlock Origin version: uBlock Origin 1.18.16

### Settings

Adguard Base + Annoyances + Mobile + Portuguese + Russian + Social + Spyware
uBlock Origin lists

**Comment by mapx-** [comment]
I cannot reproduce, however test these filters
`dailymail.co.uk##+js(abort-on-property-read.js, navigator.userAgent.search)`
or
`dailymail.co.uk##+js(set-constant.js, navigator.userAgent.search, trueFunc)`

**Comment by adranger** [comment]
That's what they check, but for some reason your rules didn't work. This one did the trick:

`dailymail.co.uk##script:contains(We think our Android)`

**Comment by mapx-** [comment]
It's ok only for firefox, that syntax is deprecated but still alive
use:
`dailymail.co.uk##^script:has-text(We think our Android)`

**Comment by mapx-** [comment]
try 

`dailymail.co.uk##+js(abort-current-inline-script.js, navigator.userAgent.search)`

**Comment by kulfoon** [comment]
None of the injects defuse the popup (I've tried on the mobile mode on Firefox & Opera), perhaps race condition?

**Comment by mapx-** [comment]
I guess html filtering in FF is working, right ?
`dailymail.co.uk##^script:has-text(We think our Android)`

**Comment by kulfoon** [comment]
Html filtering yes.

**Comment by krystian3w** [comment]
`dailymail.co.uk##+js(abort-on-property-read.js, DM.later)`

But no tested how many elements break.

**Comment by krystian3w** [comment]
@mapx-  posible reproduce with Knidle:

![obraz](https://user-images.githubusercontent.com/35370833/56056442-7d2d3580-5d5c-11e9-84fd-8fe33d92417a.png) |
--- |

**Comment by kulfoon** [comment]
krystian3w: `dailymail.co.uk##+js(abort-on-property-read.js, DM.later)`

I've tried it already before my comment https://github.com/uBlockOrigin/uAssets/issues/5321#issuecomment-482563904 and it was not working, also tried several more different injects as well and none was working. If it works for you, this means that definately race condition is the issue.

**Comment by krystian3w** [comment]
For me works OK, no see aletr in `Responsive Design Mode`.

**Comment by krystian3w** [comment]
For me works OK, no see alert in `Responsive Design Mode`<sup>[\[i\]](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode "Responsive Design Mode &#10;&#10;&#10; https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode")</sup>.

**Comment by mapx-** [comment]
yep, I can confirm (emulation), @krystian3w filter is working
`dailymail.co.uk##+js(abort-on-property-read.js, DM.later)`

but I don't know if breaks something

**Comment by kulfoon** [comment]
Yes it's working, perhaps I was checking these:
`dailymail.co.uk##+js(abort-current-inline-script.js, DM.later, navigator.userAgent.search)`
`dailymail.co.uk##+js(set-constant.js, DM.later, undefined)` 
and seeing they're not working I skipped to `check abort-on-property-read/write` or forgot or just gave up as spent too much time on it. 

Perhaps this: `dailymail.co.uk##+js(abort-on-property-read.js, DM.later.go)` will break less.

**Comment by mapx-** [comment]
Strange, but blocking `DM.later.go` will break the above page in firefox. 
With `DM.later` I get o visible breakage

**Comment by krystian3w** [comment]
I suppose we now no need scriplet as long no possible uBo stable from google webstore in Yandex Android version.

**Comment by kulfoon** [comment]
> mapx: https://github.com/uBlockOrigin/uAssets/issues/5321#issuecomment-482739438

I confirm, so it actually breaks more instead of less.

**Comment by kulfoon** [comment]
.

**Comment by mapx-** [comment]
for firefox is already working, so I'll add for other browsers
```
!#if !env_firefox
!#if env_mobile
dailymail.co.uk##+js(abort-on-property-read.js, confirm)
!#endif
!#endif
```

**Comment by krystian3w** [comment]
This condition should turn on PC too... - still we no have solution for combined if.

**Comment by adranger** [comment]
What "other browsers" support this extension on portable devices?

**Comment by krystian3w** [comment]
Without Firefox forks - only I know about Yandex for Android.

Now in Yandex possible install manually stable uBO. But possible install Nano Adblocker / uBO dev from chrome web store.

**Comment by mapx-** [comment]
It should work now.

**Comment by kulfoon** [comment]
Previous solution https://github.com/uBlockOrigin/uAssets/issues/5321#issuecomment-482795939 was working fine, after last commit, not working on Opera anymore, because mobile Opera meets the both conditions (separately!): it's not Firefox + it's mobile which means the both filters (blocking + exception) are applied, thus the exception filter disables (overrides) the blocking filter... so the blocking filters is not applied because it's whitelisted.

The last commit should be reverted, because in this specific case there is no real issue with the previous commit, even despite the fact the issue theoriticaly has an effect, but practically it has not. The issue's details are here: https://github.com/uBlockOrigin/uBlock-issues/issues/270#issuecomment-429841056 , for example on desktop Opera the second condition `!#if env_mobile` will be ignored thus the filter won't apply, but hey - the second condition itself does want to be ignored / not applied on the desktop anyway, so the final effect with the issue is the same as the final effect without the issue: filter not applied on desktop browser.

**Comment by krystian3w** [comment]
<sup> No raczej chodzi by nie naprawiać tego w narzędziach developera (grzebiesz więcej na dailymail z emulowaniem tabletu niż czytasz to twoja sprawa) a na realnej platformie mobilnej. </sup>

Well, I mean not to fix it in the developer's tools (you're combing more on dailymail than reading your case) and on a real mobile platform.

**Comment by mapx-** [comment]
Now:
```
!#if env_firefox
dailymail.co.uk#@#+js(abort-on-property-read.js, confirm)
!#endif
!#if env_mobile
dailymail.co.uk##+js(abort-on-property-read.js, confirm)
!#endif
```

If opera mobile, the first one is not enabled but will be enabled the second one.
Note that now we have 2 separate (not combined) blocks.

**Comment by krystian3w** [comment]
What Opera Mobile 51 support uBO? @kulfoon  can you explain instruction install addon?

https://play.google.com/store/apps/details?id=com.opera.browser
https://play.google.com/store/apps/details?id=com.opera.touch

**Comment by kulfoon** [comment]
> mapx: https://github.com/uBlockOrigin/uAssets/issues/5321#issuecomment-482805542

 Ahh yes, stupid eyes mistake..., my eyes mistakenly mixed the old condition (`!env`) with the new condition (`env`) so I took the old one as the current one...+ followed by the fact the popup is still here on Opera Mobile (emulated) = it gave me Fata Morgana lolz

> krystian3w: What Opera Mobile 51 support uBO?  can you explain instruction install addon?

Doesn't it...? I never used Opera Mobile so I didn't know, but Opera Mobile (emulated) does and the popup is still here...lol, the question for you is why Opera does have mobile emulation then... ? lol

**Comment by krystian3w** [comment]
uBO no support emulation from dev tools as real plafrom so no works.

**Comment by ghajini** [comment]
@mapx- 

Platform= firefox A. Ublock origin 1.27.11b10

URL =
`https://www.dailymail.co.uk/news/article-8415101/BLM-activists-DEFY-Boris-Johnsons-calls-abandon-protests.html`

Issue= this filter `dailymail.co.uk##body:style(margin-top: -80px!important;)` from **adguard mobile ads filter** is breaking hamburger menu at top and social share buttons at top are hidden

Ublock enabled=
`https://prnt.sc/syog7v`

Adguard mobile ads filter disabled=
`https://prnt.sc/syoh8l`

**Comment by krystian3w** [comment]
Wait 1-3 h and update list, problem should gone.
