### ISSUE TITLE
unfiltered background advertisements+links

### ISSUE THREAD

**Issue by vladtepesch** [uBlockOrigin/uAssets#5322]
### URL(s) where the issue occurs

```
https://www.welt.de/
https://www.golem.de/
```

### Describe the issue

Many Websites (espescially german news pages) load some background stuff that leads to content jumping, since it seems to appear always after a few seconds.
Also the whole background is made a clickable link.

These ad images are are delivered from the own domain with randomly generated class names.

### Screenshot(s)

![grafik](https://user-images.githubusercontent.com/1601159/55870703-6d112c80-5b89-11e9-9406-515f629b5ab2.png)

### Versions

- Browser/version: Firefox 66.0.2 (64-Bit)
- uBlock Origin version: 1.14.18

### Settings
 - selected nearly all lists
 - activated expert mode
 - blocked third party scripts and frames
 - added exceptions very selectively (but these kind of Problem occurs in ublocks default settings as well)

### Notes
At general ads that pass the uBlock seems to have the following pattern:
 - They are loaded after the rest of the page
 - They are inserted at some special positions in the page with randomly generated class names/ids
 - The rest of the actual page does have clear class names/ids

So may be some heuristical blocking could be implemented based on that behaviour.

**Comment by mapx-** [comment]
I cannot reproduce your issue.
uBo current version is 1.18.16, yours is 1.14.18, outdated => update to the current version and force update all your lists, be sure you didn't disable uBo lists (first section on filter lists tab)

**Comment by vladtepesch** [comment]
strange - my firefox does not show any extension updates - maybe some corporate firewall blocks this.
But at home I have the same issues and there i am sure to have everything up to date.
As i told: i enabled nearly all the lists.
all but: 
 - Dan Pollock’s hosts file​
​​​​​​​​ - hpHosts’ Ad and tracking servers​
​​​​​​​​ - MVPS HOSTS​
​​​​​​​​ - regional (only enabled DEU)

**Comment by vladtepesch** [comment]
After manually deinstalling and reinstalling ublock origin it seems to work as intended. I will check it at home, if there is the same problem with updated extension.
