### ISSUE TITLE
https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewadvanced

### ISSUE THREAD

**Issue by NN---** [uBlockOrigin/uAssets#5323]
### URL(s) where the issue occurs
`https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewadvanced`

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue
The download link doesn't appear after selecting edition and language.
It does appear with ublock disabling.

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]
![image](https://user-images.githubusercontent.com/580536/55872083-c6328d80-5b94-11e9-8baa-5509f2cd52bb.png)

![image](https://user-images.githubusercontent.com/580536/55872201-0db91980-5b95-11e9-84b5-3bbc6f4b1c5d.png)

### Versions

- Browser/version: Firefox 66
- uBlock Origin version: 1.18.16

### Settings

- [List here all the changes you made to uBO's default settings]
Added lists:

ISR: EasyList Hebrew​
RUS: AdGuard Russian filter​​​​​

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
test
`@@||vlscppe.microsoft.com/fp/tags.js$script,1p`

**Comment by mapx-** [comment]
`/fp/tags.js?` @ryanbr

**Comment by NN---** [comment]
@mapx- Works !
