### ISSUE TITLE
20min.ch - all videos blocked

### ISSUE THREAD

**Issue by Brainc0re** [uBlockOrigin/uAssets#5329]
20min.ch

example:

https://www.20min.ch/schweiz/news/story/-Ich-bin-Mami-und-heimlich-Escort--28204376
https://www.20min.ch/schweiz/zuerich/story/-Wir-waren-erleichtert--dass-er-noch-lebt--25478866
https://www.20min.ch/schweiz/zentralschweiz/story/Engerlinge-fressen-Bauern-die-Haenge-kahl-29515297

All self hosted videos are blocked, except video from YouTube, Twitter and Co.

![image1457](https://user-images.githubusercontent.com/21007884/55923107-5b209f80-5c04-11e9-9128-cf9755cc42eb.jpg)

- Browser/version: Vivaldi 2.4.1488.35 (Stable channel) (64-Bit)
- uBlock Origin version:  v1.18.16

### Settings

Default - no custom lists/filters

**Comment by Brainc0re** [comment]
For a person who dont have any knowledge about coding... what? I dont understand https://github.com/uBlockOrigin/uAssets/commit/d39e86fe82b772b6e75b839725f26e3e94aef9ef#diff-597a9408879bda0da942803b82285184

**Comment by mapx-** [comment]
That indicates only that a commit (fix) was added to one of uBo lists.

You can wait the automatic updating of your list (few days) or force the update of all the lists or only of the modified list (in this case unbreak list)

How-to update:
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now

**Comment by Brainc0re** [comment]
Ahhh :) okay. Thank you

Forced the unbreak list update - videos work again :)
