### ISSUE TITLE
torrentdownloads

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#533]
### URL(s) where the issue occurs

`https://www.torrentdownloads.me/search/?search=linux`
SPONSORED SEARCH RESULTS at top; the first "real" result ("Linux") is also an external link that takes you to another site.*** However, the first result isn't always an external link (example: `https://www.torrentdownloads.me/view/popular/TV_Shows.html`) only appears to be that way if you do a search (vs. looking at categories)

`https://www.torrentdownloads.me/torrent/1662440002/Hacking+University+Senior+Edition+Linux+Optimal+beginner%27s+guide+to+precisely+learn+and+conquer+the+Linux+operating+system+%282016%29+%5BWWRG%5D`
Three download buttons at the top: only middle `Download Torrent` is real; `Download` and `Direct Download` are fake/ads; the blue download arrow below that is also fake; ad for `Movie4u` under `Stream: Watch Online @ Movie4u` (how you gonna stream a book?); flashing VPN ad.

Clicking around may trigger a popup; example popup URL:
`https://unformse.com/a2pYUGEKCDUk`

***That site is: `https://www.torrentdownload.ch/search?q=linux` which also happens to have unblocked `Sponsored Links` and also has popups to `unformse.com`

`https://www.torrentdownload.ch/7C1EE7C55E520BEF0CF5A34FCC68A8FB9D304AA2/kali-linux-2017-1-i386`
Top three options to download: only middle one (`iTorrents`) appears to be real; `Direct Download` and `Torrent VPN` are fake/ads. Fake/ads: `Stream: Download torrents safely and Anonymously with Free Torrent VPN by SpyOFF. Get SpyOFF Now` and `Stream: Watch Free Movies Online @ Movie4u`

### Versions

- Browser/version: Chrome/59
- uBlock Origin version: 1.13.2

### Settings

Default

**Comment by gorhill** [comment]
This seems to take care of the popups:

    ||dzcx04lyk9hjp.cloudfront.net^

**Comment by gorhill** [comment]
Ok, does that address the issues for `torrentdownloads.me`?

    ||dzcx04lyk9hjp.cloudfront.net^
    torrentdownloads.me##.download> li:has(a[href*="//www.duckssolutions.com"])
    torrentdownloads.me##.left_shadow:has(a[href*="//www.duckssolutions.com"])
    torrentdownloads.me##.grey_bar3:has(a:not([href^="/"]))

**Comment by terrorist96** [comment]
@gorhill Almost. Everything looks good except the `Stream: Watch Online @ Movie4u` is still visible.

**Comment by mapx-** [comment]
`torrentdownloads.me##.grey_bar1:has-text(Stream)`

**Comment by terrorist96** [comment]
Another mirror of the site: `torrentsdownload.co`

**Comment by terrorist96** [comment]
@gorhill 
Should I report this to EasyList or can it be added to uBO?

**Comment by terrorist96** [comment]
@ryanbr

**Comment by okiehsch** [comment]
@terrorist96 to summarize this thread, adding 
````
torrentdownloads.me##.download> li:has(a[href*="/redir.php"])
torrentdownloads.me##.inner_container:has(> .titl_4)
torrentdownloads.me##.grey_bar3:has(a:not([href^="/"]))
torrentdownloads.me##.inner_container > div > div:has(> a[href*="/redir.php"])
torrentdownloads.me##.inner_container > a[href*="//goo.gl/"]
torrentdownloads.me##.grey_bar1:has-text(Stream:)
````
fixes all your issues?

**Comment by terrorist96** [comment]
@okiehsch Yes, adding all those fixes all the issues on `torrentdownloads.me`. There will still be outstanding issues on `torrentsdownload.co` (same site, alternate TLD) and `torrentdownload.ch` (a related, but not the same, site) though.
Thanks

**Comment by okiehsch** [comment]
So
`````
torrentdownloads.me,torrentsdownload.co##.download> li:has(a[href*="/redir.php"])
torrentdownloads.me,torrentsdownload.co##.inner_container:has(> .titl_4)
torrentdownloads.me,torrentsdownload.co##.grey_bar3:has(a:not([href^="/"]))
torrentdownloads.me,torrentsdownload.co##.inner_container > div > div:has(> a[href*="/redir.php"])
torrentdownloads.me,torrentsdownload.co##.inner_container > a[href*="//goo.gl/"]
torrentdownloads.me,torrentsdownload.co##.grey_bar1:has-text(Stream:)
`````
works for both domains?

**Comment by terrorist96** [comment]
Yes, sir.

**Comment by okiehsch** [comment]
OK, I will add this fix later today.

**Comment by terrorist96** [comment]
Thank you.
The issues with torrentdownload.ch are:
`https://www.torrentdownload.ch/7C1EE7C55E520BEF0CF5A34FCC68A8FB9D304AA2/kali-linux-2017-1-i386`
Top three options to download: only middle one (`iTorrents`) appears to be real; `Direct Download` and `Torrent VPN` are fake/ads. Fake/ads: `Stream: Download torrents safely and Anonymously with Free Torrent VPN by SpyOFF. Get SpyOFF Now` and `Stream: Watch Free Movies Online @ Movie4u`

**Comment by okiehsch** [comment]
Could you open a seperate issue for that site please. I will have a look at it.

**Comment by terrorist96** [comment]
@okiehsch `https://www.torrentSdownload.co/torrent/1663553545/South+Park+S21E02+720p+HDTV+x264-AVS%5Brarbg%5D`
and
`https://www.torrentdownloadS.me/torrent/1663553545/South+Park+S21E02+720p+HDTV+x264-AVS%5Brarbg%5D`

Two fake download buttons visible again, middle one is legit. And blue anonymous download arrow visible on both (first one has extra text, second one only the arrow is visible).
Thanks!

**Comment by mapx-** [comment]
```
torrentsdownload.co##a[href^="/bing.php"]
torrentdownloads.me##a[href^="/bing.php"]
```

**Comment by okiehsch** [comment]
````
torrentdownloads.me,torrentsdownload.co##a[href^="/bing.php"]
torrentsdownload.co##.inner_container > div > div:has(> a[href*="/bing.php"])
````
The second one is necessary to deal with the extra text next to the blue download button at 
`torrentsdownload.co`

**Comment by gotitbro** [comment]
@gorhill Can uBO support wildcard `*` entries for cosmetic filters? It already does for uBO specific filters.

**Comment by terrorist96** [comment]
@okiehsch please also add the `torrentexx.com` domain for these rules.

**Comment by terrorist96** [comment]
Needs updating.

**Comment by mapx-** [comment]
"download torrent" should be ok ?!

see if works for you
```
torrentdownloads.me##.download:has([href*="search"])
torrentdownloads.me##[href*=".php"]
```

if "download torrent" is ok, you need only the second filter

**Comment by terrorist96** [comment]
Thanks. The `Download Torrent` button was also causing a redirect, but I realize it does actually download the torrent as well. All fixed now.

**Comment by ghajini** [comment]
`torrentdownloads.me/torrentdownloads.be/torrentdownloads.info`

Update scriptlet filter to `torrentdownloads.*##+js(acis, adcashMacros)`
This works for me

**Comment by garry-ut99** [comment]
On `torrentdownload.info` - popups after clicking anywhere on page.
