### ISSUE TITLE
rundschau-online.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5332]
### URL(s) where the issue occurs

`https://www.rundschau-online.de/region/koeln/ordnungsamt-vom-praktikant-zum-chef-3173240`

### Describe the issue

Unblocked Ads

### Versions

- Browser/version: Firefox 66.0.2
- uBlock Origin version: v1.18.16

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3069599/Settings.txt)

**Comment by mapx-** [comment]
I guess it's about the right side stuff
As there are no special ads you have to report at Easylist Germany repository / forum:
https://github.com/easylist/easylistgermany/issues
https://forums.lanik.us/viewforum.php?f=90

**Comment by JobcenterTycoon** [comment]
@mapx- 
<img width="1323" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/55974600-4dacf900-5c88-11e9-91cd-4188f3ddf942.PNG">
When i click on this i get redirectet to https://ad1.adfarm1.adition.com

**Comment by mapx-** [comment]
Even using your settigs ad a german ip I get no such red background. 
You mean clicking that background you'll get `https://ad1.adfarm1.adition.com` ?

Are you using some other strange addons ?

**Comment by mapx-** [comment]
wait .. now I get the red crap

**Comment by JobcenterTycoon** [comment]
> 
> 
> Even using your settings ad a german ip I get no such red background.
> You mean clicking that background you'll get `https://ad1.adfarm1.adition.com` ?
> 
> Are you using some other strange add-ons ?

Yes, the complete red background is clickable and i use only uBlock Origin. But i found a fix for that
`rundschau-online.de##^script:has-text((window);)` works for me

**Comment by mapx-** [comment]
see if works for you
`rundschau-online.de##+js(addEventListener-defuser.js, /^(?:DOMContentLoaded|load)$/, =!0)`
