### ISSUE TITLE
Futbin uBlock detection

### ISSUE THREAD

**Issue by sanjivsharma14** [uBlockOrigin/uAssets#5334]
### URL(s) where the issue occurs

`https://www.futbin.com/19/player/143/Cristiano%20Ronaldo/`

### Describe the issue

The site detects uBlock on every player page and hides the player price information until you turn off uBlock.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/39468258/55999991-173ba200-5cb9-11e9-9851-20a1e35d7de8.png)

### Versions

- Browser/version: Chrome 73.0.3683.103
- uBlock Origin version: uBlock Origin v1.18.16

### Settings

- None

### Notes

Previously this could be avoided by turning off cosmetic filtering but that loophole was closed within a couple of hours.

**Comment by garry-ut99** [comment]
Big ad placeholder caused by `ghide` in "uBlock Filters":

<details>
<summary>SCREENSHOOT</summary>

![ss](https://user-images.githubusercontent.com/72945564/215477106-ae8e8a11-24cf-4af7-9950-5aead3e6a56d.png)

</details>
