### ISSUE TITLE
upvid.pro(Antiadblock)

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5338]
### URL(s) where the issue occurs

`https://upvid.pro/8opes3ly33xy.html`

### Describe the issue

Antiadblock

### Screenshot(s)

`https://user-images.githubusercontent.com/20338483/56060700-37389780-5d85-11e9-81a8-d47cc8a870c0.png`

### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.18.16

### Settings
uBO's default settings

**Comment by garry-ut99** [comment]
`upvid.tv` - breakage: [screenshoot](https://user-images.githubusercontent.com/72945564/220985019-602a6385-8bea-4026-b1af-c4a512a72b4c.png), fixed: [screenshoot](https://user-images.githubusercontent.com/72945564/220985111-4b88993e-3427-4d02-8b54-d930e172152d.png)
