### ISSUE TITLE
upload.ac

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5340]
### URL(s) where the issue occurs

`https://upload.ac/1nygv2u1bndp/Jkkbvf4plZMg3raUrgW4woeXgAfd1m2ecY9EKj01jALRlHjwC.mkv`

### Describe the issue

popup ads

### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.18.16

### Settings

-  uBO's default settings

**Comment by ghajini** [comment]
would you add
* ivastoor.com * block
* tandeperoblitt.info * block
* tontwiredat.info * block
present on similar sites

**Comment by ghajini** [comment]
`upload.ac/n9qz9t33dp9c`

download doesn't start on clicking download,probably broken by some easylist filter

**Comment by mapx-** [comment]
test
`upload.ac#@#+js(remove-attr, checked, #chkIsAdd)`

**Comment by ghajini** [comment]
If By chance that `download with addons` is checked and I click download, I get Trojan infection (malware)

![Screenshot (228)](https://user-images.githubusercontent.com/20338483/72543906-6ea41980-38ac-11ea-858f-b6e8364efee7.png)

Please nullify that button

**Comment by mapx-** [comment]
with
```
upload.ac##+js(window.open-defuser)
upload.ac##.dl-plus
```

the crap does not open anymore but have to switch on / off the `Download with Addons` button (otherwise the true page does not open)

**Comment by uBlock-user** [comment]
https://github.com/uBlock-user/uBO-Scriptlets/issues/7#issuecomment-575298451

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/6101ebe0907d25321a48758f665e4dc960ebefb0
