### ISSUE TITLE
adslzone.net

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#5345]
### URL(s) where the issue occurs

`https://www.adslzone.net/`

### Describe the issue

Breakage, the images are not displayed correctly.

### Screenshot(s)

<details><summary>Screenshot</summary>

![Screenshot_2019-04-12 ADSLZone - Portal sobre ADSL, fibra óptica y tecnología](https://user-images.githubusercontent.com/27441315/56065422-12d4bf00-5d75-11e9-8cfd-d0a7982df7a9.png)
</details>

### Versions

- Browser/version: Chrome 73
- uBlock Origin version: 1.18.16

### Settings

- Default settings.

### Notes

Suggested filters
```
adslzone.net##+js(set-constant.js, canRunAds, true)
@@||www.adslzone.net/app/themes/adslzone-net-mykonos/assets/js/stickyAds.min.js$script,1p
```

`(set-constant.js, canRunAds, true)` fix [this](https://user-images.githubusercontent.com/27441315/56073513-9908f980-5da5-11e9-827a-2d82717ae25b.png), appears when exception filter is added.
`https://www.adslzone.net/operadores/recargas/recargar-saldo-lebara-movil/`

**Comment by lain566** [comment]
Same as https://github.com/uBlockOrigin/uAssets/commit/96abf6e645d58d6aed714b23c792375971a7296c for movilzona.es
`https://www.movilzona.es/`

```
movilzona.es##+js(set-constant.js, canRunAds, true)
@@||movilzona.es/app/themes/*/stickyAds.min.js$script,1p
```

<details>

![Screenshot_2019-04-13 Movil Zona Portal especializado en telefonía móvil](https://user-images.githubusercontent.com/27441315/56084543-a3be9f80-5e34-11e9-9893-e1d74fdf2d5f.png)


![Screenshot_2019-04-13 Movil Zona Portal e](https://user-images.githubusercontent.com/27441315/56084532-6b1ec600-5e34-11e9-9b64-8c10b3f4a8db.png)
</details>

------------------------------------
And for `redeszone.net`
`redeszone.net##+js(set-constant.js, canRunAds, true)`

`https://www.redeszone.net/redes/teamspeak-3-para-android-manual-de-configuracion-y-uso/`

<details>

![Anotación 2019-04-13 214224](https://user-images.githubusercontent.com/27441315/56084576-2b0c1300-5e35-11e9-9327-a2b1364973df.png)
</details>

**Comment by okiehsch** [comment]
`redeszone.net` does not also break site functionality, so I would consider the message an annoyance only.
