### ISSUE TITLE
ebb.io

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#5346]
### URL(s) where the issue occurs

`https://ebb.io/anime/469x800`

### Describe the issue

Anti-adblock
Issue has not been fixed 
`https://github.com/uBlockOrigin/uBlock-issues/issues/520`
`https://www.reddit.com/r/uBlockOrigin/comments/bbuy8e/how_to_play_anime_without_shut_down_ublock`

### Screenshot(s)

![Screenshot_2019-04-13 ebb io 動漫新番線上看](https://user-images.githubusercontent.com/27441315/56077292-c58b3880-5dda-11e9-8b31-c4c10367896d.png)

### Versions

- Browser/version: Chrome 73
- uBlock Origin version: 1.18.16

### Settings

- Default settings.

### Notes

Click on any of these numbers
<details>

![Anotación 2019-04-13 105844](https://user-images.githubusercontent.com/27441315/56077346-5c57f500-5ddb-11e9-8203-0ed9303d54ae.png)
</details>

**Comment by mapx-** [comment]
adding
`@@||pagead2.googlesyndication.com/pagead/$script,domain=ebb.io`

seems working ...but how can I play the video ?

**Comment by lain566** [comment]
You need an account

**Comment by mapx-** [comment]
if you have one, can you confirm is running ok now ?

**Comment by lain566** [comment]
I was looking for a google account that I no longer use, and yes, it works

**Comment by kulfoon** [comment]
Shouldn't be this removed then: https://github.com/uBlockOrigin/uAssets/commit/37e24401b77b06f5b0f835bd3b48ed331ac13a82 ?
Also because there are as well:
`/pagead2.` on EasyList and
`||googlesyndication.com^` on Peter Lowe’s Ad and tracking server list

**Comment by mapx-** [comment]
thx
