### ISSUE TITLE
hiidudehd.in

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5350]
### URL(s) where the issue occurs

`https://www.hiidudehd.in/Celebrity/shortner/?p=https://filesaver.pro/peq19wpanqyw.html`

### Describe the issue

popup ads

### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.18.16

### Settings

-  uBO's default settings

**Comment by JobcenterTycoon** [comment]
`hiidudehd.in##+js(abort-current-inline-script.js, atob, decodeURIComponent)` works for me

**Comment by ghajini** [comment]
site doesn't exist
