### ISSUE TITLE
jio.andyli.info

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5351]
### URL(s) where the issue occurs

`https://jio.andyli.info/goto/aHR0cHM6Ly9taXJyb3JhY2UuY29tL20vMXNjczM=`

### Describe the issue

popup ads

### Versions

- Browser/version: opera stable
- uBlock Origin version: 1.18.16

### Settings
uBO's default settings

**Comment by mapx-** [comment]
Provide the correct steps, I get:

>  You have been redirected through this website from a suspicious source. We prevented it and you are going to be redirected to our safe web site.

**Comment by ghajini** [comment]
sorry...
go here `https://jio.andyli.info/reign-of-the-supermen-2019-hdrip-720p-direct-links/`
then click `direct download`
in next page click anywhere
