### ISSUE TITLE
xhamster.com (nsfw)

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#5352]
### Describe the issue

[Trying to press the back button will place you on `xhamsterlive.com` the filter `xhamster.com##+js(addEventListener-defuser.js, popstate, backUrl)` should fix it but it doesn't anymore. I tried to abort the entire script `window.initials` but this prevents the videos from loading possibly other side effects. I can't seem to find anyway to prevent the `backUrl` from showing up.]

### Versions

- Browser/version: [Chrome v73.0.3683.103]
- uBlock Origin version: [1.18.16]

### Settings

- [default]

**Comment by dumbusernameidk** [comment]
It also shows up on FF.  I noticed they changed the name of the big script in the page source. It used to be `window.js_vars` now it's `window.initials`. Strangely the `xhamster.com##+js(addEventListener-defuser.js, popstate, backUrl)` never actually worked for me I had to abort the entire script but doing it now prevents videos loading/thumbnails swapping.

**Comment by okiehsch** [comment]
I can't reproduce with Chrome or Firefox,

**Comment by dumbusernameidk** [comment]
maybe a/b testing stuff? or geo related? does this look the same for you `https://gyazo.com/a75d57cbd33de5d00cd5db1d4b8a46b8` when you view page source?

**Comment by okiehsch** [comment]
Sorry, I misunderstood the issue, I can reproduce if I go to xhamster from a third-party site and then try to go back.

**Comment by dumbusernameidk** [comment]
I get it when just typing the site in the address bar and pressing the back button. Like if i go to my new tab page then go to xhamster and press back the url changes to `https://xhamster.com/#back_url`.

**Comment by okiehsch** [comment]
`xhamster.com##+js(addEventListener-defuser.js, /^(?:hashchange|popstate)$/)`
works but you have to click the backbutton twice.

**Comment by mapx-** [comment]
what about
`xhamster.com##+js(abort-on-property-read.js, initials.urls.backUrl)`

**Comment by okiehsch** [comment]
That is better.

**Comment by dumbusernameidk** [comment]
Yeah that works.

**Comment by LoreJon** [comment]
those filters are not working anymore.

a popunder after selecting a category

**Comment by dumbusernameidk** [comment]
there's also another xhamster site with the same issues. `xhamster.one`.

**Comment by LoreJon** [comment]
:+1: thanks.

**Comment by dumbusernameidk** [comment]
Popup when clicking on a video on mobile.

1. Use agent switcher to switch to android.
2. Clear cookies then refresh the page.
3. Click any video and the video opens in a new tab while the first tab redirects to `tsyndicate.com`.

**Comment by mapx-** [comment]
could you test if whitelisting last filter added here

`xhamster.*#@#+js(acis, Math.random, popunder)`

would provoke some other popup ?

**Comment by THEtomaso** [comment]
There's another popup, when right-clicking on a video from the front page.
This action also opens the video, instead of letting you use the right-click menu.

`xhamster.*##script:contains(click)` fixes the issue, but unfortunately it also breaks some videos.
..so, a more advanced script injection rule is needed.

**Comment by THEtomaso** [comment]
@mapx-:

Could you add these to '**uBlock filters - Legacy**' too?:
```
xhamster.*##+js(abort-on-property-read.js, wig-popunder)
xhamster.*##+js(abort-on-property-write.js, wil-popunder)
xhamster.*##+js(addEventListener-defuser.js, pop)
```

**Comment by mapx-** [comment]
You could just prepare PR for other such requests

**Comment by dumbusernameidk** [comment]
Videos have pre-roll ads in them now.

**Comment by okiehsch** [comment]
Do you have an example link?
I can't reproduce.

**Comment by dumbusernameidk** [comment]
It's on any video here are the steps I did to produce the ads.

- Clear Cookies/Local storage
- Refresh page
- Sign into an account
- Click on a video and an 8 second ad plays from the site `stripst.com`

**Comment by okiehsch** [comment]
> ad plays from the site stripst.com

Well, does
`||stripst.com^$3p`
work?

**Comment by dumbusernameidk** [comment]
I ended up going with `||stripst.com^$xhr,3p`.
