### ISSUE TITLE
Submitting 23 more entries

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#5353]
I admit to be unsure what the regulations and definitions are between "true" and "fake" paywalls, but I'm of the personal perception that all or almost all of the paywalls in the below entries are of the fake variety.

It's established by now that *uBlock Filters - Annoyances* can deal with forced logins, so I felt it was time for me to up the ante by submitting entries that bypass honest-to-gods paywalls, and see how it goes.

```
! Lyd og Billede
! https://lydogbillede.dk/test/mobil-tablet/motorola-moto-g7-plus/?hw=1
! Displays entire articles that are behind paywalls
lydogbillede.dk,lydogbilde.no,ljudochbild.se###content:style(min-height:2000px)
lydogbillede.dk,lydogbilde.no,ljudochbild.se##.postteas:style(overflow: visible !important)
lydogbillede.dk,lydogbilde.no,ljudochbild.se##.fader
lydogbillede.dk,lydogbilde.no,ljudochbild.se##.readwhole
lydogbillede.dk,lydogbilde.no,ljudochbild.se##.loginabo
lydogbillede.dk,lydogbilde.no,ljudochbild.se##.aboboxer
lydogbillede.dk,lydogbilde.no,ljudochbild.se##.aboboxerbold
lydogbillede.dk,lydogbilde.no,ljudochbild.se##.abolistbox
lydogbillede.dk,lydogbilde.no,ljudochbild.se##.abomainbox
lydogbillede.dk,lydogbilde.no,ljudochbild.se##.aboinfobunn
lydogbillede.dk,lydogbilde.no,ljudochbild.se##.hidefromgp

! eNotes
! https://www.enotes.com/homework-help/three-enlightenmet-ideas-used-declaration-471209
! Shows behind-paywall question responses on some questions
enotes.com##.hh-box__answer__text:style(filter: none !important; -webkit-filter: none !important; color: inherit !important; text-shadow: none !important)

! HowToLucid
! https://howtolucid.com/how-to-sleep-better/
! Removes a blur that covers most of the tutorial articles
howtolucid.com##.onp-sl-blur-area:style(filter: none !important)

! StudyCOM
! https://study.com/academy/flashcards/europe-flags-list-flashcards.html
! Makes the flashcard tables fully visible without being logged in
study.com##.paywall:style(display: table !important)
study.com##.paywall:after
! https://study.com/academy/lesson/what-is-a-graph-lesson-for-kids.html
! Makes the lesson articles fully visible
study.com###articleMain > div[class=hidden]:style(visibility: visible !important; display: block !important)
study.com##.faded-content:after

! Experts Exchange
! https://www.experts-exchange.com/questions/29116980/Read-and-parse-a-flat-file-format-in-Java.html
! Shows the approved answers to the questions
experts-exchange.com##.accepted.answer:style(display: block !important)
experts-exchange.com##.solutionIntertitialWrapper.body
experts-exchange.com##.bg3.interceptBackgroundBlocker.interceptContainer
! Note that the fake bottom answer is still being shown, even when the correct certified answer has been revealed through the above entries. If it is desirable to remove the fake answer as well, add "experts-exchange.com##.interceptBackgroundBlocker" as well.

! Futurestud.io
! https://futurestud.io/tutorials/coreos-platform-introduction-and-components
! Reveals the section jump menu called Moonshoot, which is otherwise behind a paywall
futurestud.io##.spoiler:style(filter: none !important; -webkit-filter: none !important)
futurestud.io##.fs-background.text-center.aside-info
```

### Versions

- Browser/version: Google Chrome 73.0.3683.103 64-bit for Windows
- uBlock Origin version: Nano Adblocker 1.0.0.103 + Nano Defender 15.0.0.129

### Settings

- I've made no changes that I personally think would've been able to affect the content of websites, apart from a wildly different set of list subscriptions.

### Notes

I was clued on to the latter five sites by browsing through r/assholedesign daily for a month or so this winter. However, after that subreddit deteriorated into infinite reposts (e.g. of the Cosmopolitan newsletter insultment) and uneducated comments (Many of which insulted ad-complaining OPs for "How else are they gonna earn money?"), I didn't really want to namedrop them as a credit anymore.

**Comment by okiehsch** [comment]
A "real" paywall is a wall that is present with uBO disabled, we will not intentionally circumvent it.

**Comment by DandelionSprout** [comment]
Huh, okay. I recall that Frellwit's understanding of it was that a "real" paywall was one where the content was not pre-loaded for non-paying users, whereas a "fake" paywall would pre-load the content and then use CSS to hide it.

If your explanation differs significantly from his, then I suppose that this issue report could in fact be closed entirely.

**Comment by okiehsch** [comment]
I agree that such paywalls are not very effective but they are applied indiscriminately to all users, so I think they are out of scope of uBO.

See https://github.com/uBlockOrigin/uAssets/issues/2317#issuecomment-392009540

**Comment by DandelionSprout** [comment]
If that thread's comments are still accurate for uAssets (as in that they haven't been superceded by another stance in the following 9 months), then it's a fair stance that I'll accept.

**Comment by jspenguin2017** [comment]
Everyone has their own definition of fake paywalls. AdGuard believes all paywalls are real, uAssets believes paywalls that are shown to all users are real, and I believe paywalls that cannot be broken by changing browser settings are real. 

Can't believe AdGuard decided to cover their wallet instead of fighting this nonsense, apparently you can't legally change your browser settings in Europe anymore.

**Comment by DandelionSprout** [comment]
Now that you mention it, I learned from https://github.com/uBlockOrigin/uAssets/issues/5320 that AdGuard even considers forced login prompts to be paywalls, which they in turn don't want to deal, to which my instinctive reaction is to be very confused.

In addition, I actually live in Europe, and even without looking things up in detail, there are several problems with AdGuard's alleged stance:

1) They're based in Russia, which is not covered by EU/EEC regulations **in the slightest**.
2) I am not aware of any laws whatsoever that prohibit the changing of browser settings, especially seeing how ABP has been able to fend off lawsuit after lawsuit from the very heart of the EU.
3) A lot of non-Europeans misunderstand virtually everything the European Parliament ever does.

**Comment by okiehsch** [comment]
> apparently you can't legally change your browser settings in Europe anymore.

What do you mean by that? Which EU-regulation prohibits the changing of browser settings.

**Comment by jspenguin2017** [comment]
AdGuard is a for-profit company, if they give the finger then they'll lose out on profits. I don't quite remember the exact details, but it's something like `bild.de` sued ABP for breaking their CSS-based encryption. I'll try to find the post...

**Comment by jspenguin2017** [comment]
https://forum.adguard.com/index.php?threads/policy-on-adblock-walls.26022/#post-155882

**Comment by okiehsch** [comment]
I know the case and  Adblock/Plus solution to the potential legal problems, i.e. do not circumvent any anti-adblock wall, is the more consistent policy.

To differentiate between anti-adblock walls that give the option to pay and anti-adblock walls without such an option is nonsensical if you agree with the premise that circumventing such walls is prohibited by § 95a UrhG.
That was the issue in the `bild` case you mentioned and a regional court ruled against someone who published a circumvention on youtube.

**Comment by DandelionSprout** [comment]
I'm having some problems trying to read up on all this fast enough, but [the recentmost stance](https://forum.adguard.com/index.php?threads/policy-on-adblock-walls.26022/page-2#post-170300) of AdGuard and/or the German court system on the matter confuses me:

>the court in Karlsruhe said the site owner can setup an anti-adblock page which is some kind of paywall as you can buy your way in back.

Just what on earth kind of anti-adblock wall has paid backdoors?

**Comment by okiehsch** [comment]
`The court said the usage is allowed, but the site owner can put up such paywall. Therefore we are not allowed to circumvent it.`

They said no such thing the court said the usage of an adblocker is allowed and the site owner can put up a paywall it did not say anything specific about the legality of circumventing it because that question was not relevant to the case.
My guess would be that they would rule it illegal in that specific case.
The case is about the possible violation of competiton law by Adblock/Plus

If you want to practice your german you can read the full ruling.
````
http://juris.bundesgerichtshof.de/cgi-bin/rechtsprechung/document.py?Gericht=bgh&Art=en&sid=b9d71af99212eefe3fe2ae964b85d1d0&nr=88498&pos=1&anz=2
````
😉

**Comment by okiehsch** [comment]
> A lot of the stuff is not in English, but it looks like bild.de claims that their anti-adblock wall uses encryption. Following that logic, if I disable JavaScript in my browser settings, that's going to break their encryption process, which in turn makes changing browser settings illegal?!

Try going to `bild.de` with javascript disabled.

**Comment by jspenguin2017** [comment]
Ah, interesting... For some reason I thought disabling JavaScript works. Well, scrap what I said earlier.

**Comment by okiehsch** [comment]
I woud argue you that an anti-adblock wall does not violate the quoted section because the mentioned protective measures should "protect a work" the mentioned works like "bild.de" are openly accessible to everybody with a browser, one is only blocked after the site concludes that the user has an adblocker.

If you go to a site with such an “access control” mechanism with your adblocker enabled, you can not access that site.
If you go to the same site with your adblocker disabled, you can access that site.
If you go to the same site and BLOCK the content and ALLOW the ads you can still access that site.
They do not control access to their copyrighted content, they protect the ads.

If a site can’t make me pay, and doesn’t want it’s content to be viewed unless I pay, simply don’t send me the content.
If payment is required for access, tell me before I continue to the resource or let me provide proof that I have already paid, e.g. logging in.
Just my two cents.

**Comment by jspenguin2017** [comment]
Thank to the way ABP defended itself, a lot of stuff are in the gray zone now... 

Now back to the initial topic -- what kind of paywalls are "real". I would argue that if the paywall can be broken by changing browser settings, then it's not "effective". 

The questions is, do I want to YOLO or play safe. I'm more inclined to say play safe, I'll probably carry though with my plan to move fake wall removal rules off NanoFilters.

**Comment by jspenguin2017** [comment]
But considering [this thing](https://github.com/iamadamdev/bypass-paywalls-chrome) exists... 

Tough decisions, touch decisions everywhere...

**Comment by DandelionSprout** [comment]
I am most definitely in the YOLO camp here. After all, I frequently maintain [a list](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/BrowseWebsitesWithoutLoggingIn.txt) whose entire purpose is to remove login nags (including of uncloseable walls), and I had a dream of getting it included in uBO until not too long ago, when I conceded defeat and began to submit entries from it to uAssets instead.
