### ISSUE TITLE
ffmovies.ru

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uAssets#5354]
### URL(s) where the issue occurs

`https://ffmovies.ru/`

### Describe the issue

AdBlock detected

### Screenshot(s)

![Безымянный](https://user-images.githubusercontent.com/28482376/56111613-496f2d00-5f61-11e9-8e03-9ac962afe708.png)

### Versions

- Browser/version: [Opera|Beta]
- uBlock Origin version: [1.18.17b1]

### Settings

- [uBO's default settings]

**Comment by smed79** [comment]
```
ffmovies.ru#@#.fa-rss
```
https://forums.lanik.us/viewtopic.php?f=64&t=42741

**Comment by mapx-** [comment]
Fixed as annoyance, even if not part of default setup but still anti adb messahe

**Comment by smed79** [comment]
same issue here
```
fmovies.to
fmovies.world
```
