### ISSUE TITLE
software-on.com

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#5355]
### URL(s) where the issue occurs

`https://software-on.com/online-kms-activation-script/`
`https://software-on.com/DownloadON/aHR0cHM6Ly93d3cudXAtNC5uZXQvMW10bW11aXQxd2Iz`

### Describe the issue

- Anti-Adblock Script
- Popunders
- Disabled right click & selection

### Versions

- Browser/version: Firefox 66.0.3
- uBlock Origin version: 1.18.16

### Settings

- All Filters Enabled + I don't care about cookies. Regional filters, uBlock Filters Experimental, and Anti-Facebook List disabled.

### Notes

Uses BlockAdBlock code within the website's scripts. They are also located inline when clicking on download links.

**Comment by JobcenterTycoon** [comment]
@mapx- 
Can you speed up the Countdown on `https://www.up-4.net/1mtmmuit1wb3` when its possible?

**Comment by mapx-** [comment]
I cannot reproduce, try
`up-4.net##+js(nano-setTimeout-booster.js)`
or
`up-4.net##+js(nano-setInterval-booster.js)`

**Comment by okiehsch** [comment]
`up-4.net##+js(nano-setTimeout-booster.js)`

They validate on the server side, you will get a"Skipped Countdown" message

**Comment by theinstantmatrix** [comment]
fyi, AdGuard Base has whitelisted the mdpDeBlocker path
`@@/wp-content/plugins/deblocker$~third-party`
so uBO users with that filterlist turned on will still get anti-adblock, see recent issue AdguardTeam/AdguardFilters#54342

i suggest instead `software-on.com##+js(aopr, mdp_deblocker)`

on the annoyances side, the anti-select is now working again.
