### ISSUE TITLE
linkedin.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#5356]
### URL(s) where the issue occurs

`https://www.linkedin.com/jobs/`

### Describe the issue

Top cookie notice annoyance (there's already a "Privacy Policy" link at the bottom). 

Requires a script-based solution: https://github.com/AdguardTeam/AdguardFilters/issues/32618#issuecomment-483626742.

### Versions

- Browser/version: 66.0.3
- uBlock Origin version: 1.18.16

### Settings
Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin lists

**Comment by mapx-** [comment]
Does this help ?
`linkedin.com##.global-alert--yield.global-alert, #global-alert-queue`

**Comment by mapx-** [comment]
@smed79  click companies too

**Comment by mapx-** [comment]
I guess my filters above are working only without logging in

**Comment by mapx-** [comment]
```
linkedin.com###artdeco-global-alert-container
linkedin.com##.global-alert--yield.global-alert, #global-alert-queue
```

**Comment by smed79** [comment]
> click companies too

login required.
if logged, i get no cookie notice

**Comment by mapx-** [comment]
No. Without logging in (and click "companies" too to get a different top message)
I get cookie message even logged in.

**Comment by smed79** [comment]
https://github.com/easylist/easylist/pull/3277/files

**Comment by adranger** [comment]
Did you check the warning here? https://github.com/AdguardTeam/AdguardFilters/issues/32618#issuecomment-483626742

**Comment by mapx-** [comment]
Are you able to reproduce such warning ? Provide the necessary steps.

**Comment by BlazDT** [comment]
<img width="672" alt="linkedin" src="https://user-images.githubusercontent.com/34266271/56307808-08843d80-6146-11e9-9779-5465954eee52.png">

That message shows if user used a now non-existent email address and they try to send you messages. First rule will hide that error message as shown in screenshot.

If cookie message is hidden the normal way (CSS and not removed from code) the warning is not displayed.

**Comment by adranger** [comment]
@mapx- Your question was answered above.

**Comment by mapx-** [comment]
If I understand correctly it's an improbable scenario

> That message shows if user used a now non-existent email address and they try to send you messages

**Comment by BlazDT** [comment]
Yes, that is correct, but should still not be hidden.

**Comment by mapx-** [comment]
ok, first filter removed
