### ISSUE TITLE
ayefiles.com

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#5359]
### URL(s) where the issue occurs

`[https://ayefiles.com/yahph5pi15fi]`

### Describe the issue

[Anti-adblock when clicking free download. Also a bunch of junk sites sending xhr requests.]

### Versions

- Browser/version: [Chrome latest build]
- uBlock Origin version: [1.18.16]

### Settings

- [default]

### Notes

[Strange with this one if you disable cosmetic filtering the download works but if you just remove the filters with exceptions you're still blocked.]

**Comment by okiehsch** [comment]
> Strange with this one if you disable cosmetic filtering the download works but if you just remove the filters with exceptions you're still blocked.

````
ayefiles.com#@#ins.adsbygoogle:style(max-height: 1px !important;)
ayefiles.com#@#[id^="aswift"]
````
does not work for you? It works on my end.

**Comment by mapx-** [comment]
and the ads
`ayefiles.com##+js(abort-on-property-read.js, NativeAd)`

**Comment by okiehsch** [comment]
I don't see any ads, if you do add whatever filters are necessary.

**Comment by mapx-** [comment]
I get the ads only in firefox, weird

**Comment by dumbusernameidk** [comment]
> > Strange with this one if you disable cosmetic filtering the download works but if you just remove the filters with exceptions you're still blocked.
> 
> ```
> ayefiles.com#@#ins.adsbygoogle:style(max-height: 1px !important;)
> ayefiles.com#@#[id^="aswift"]
> ```
> does not work for you? It works on my end.

seems to now. I guess i didn't include the second one since it didn't show up for me in the logger.

**Comment by okiehsch** [comment]
>  I guess i didn't include the second one since it didn't show up for me in the logger.

That is a known issue on some sites. https://github.com/uBlockOrigin/uBlock-issues/issues/521

**Comment by dumbusernameidk** [comment]
Also still the matter of the third party junk sites. The names change each time you reload too.

**Comment by okiehsch** [comment]
`ayefiles.com##+js(abort-on-property-read.js, popjs.init)` already neutralizes them, you can check for yourself just remove that filter.
You should be aware however that if you do popups will start automatically without the need to click anywhere.

**Comment by dumbusernameidk** [comment]
So the filter just makes them not do anything even if they still show up in the logger?

**Comment by mapx-** [comment]
if you want a clean logger add in your `my filters`
`||ayefiles.com^$csp=script-src 'self' 'unsafe-inline' *.googletagmanager.com *.cloudflare.com`

**Comment by okiehsch** [comment]
The filter breaks the script, so it will not do anything.

**Comment by JobcenterTycoon** [comment]
@mapx- 
This site have a unfixed Anti-Adblock message

**Comment by okiehsch** [comment]
Works for me but I don't get any `https://ayefiles.com/advertisements.js` requests on my end.
Does it work if you add
`@@||ayefiles.com/advertisements.js$script,1p`

**Comment by JobcenterTycoon** [comment]
> 
> 
> Works for me but I don't get any `https://ayefiles.com/advertisements.js` requests on my end.
> Does it work if you add
> `@@||ayefiles.com/advertisements.js$script,1p`

crazy now its working for me. But what is with these random number sites with these xhr requests?
<img width="721" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/56250775-0e7c0f00-60b1-11e9-9e53-5033321ad8dd.PNG">
(im hard blocked these sites to bring it out) is this tracking? when i block it, it doesn't break the site, but these sites set a cookie. Here is a list of all sites:
`ae7c783736eb2ff.com`
`8c32f38df7.com`
`7d66a95c481.com`
`55ad5a0546d9.com`
`9b51b7efc6d2a.com`
`301e5931499990.com`

**Comment by okiehsch** [comment]
It's a remnant of the ads **mapx-** fixed with `ayefiles.com##+js(abort-on-property-read.js, NativeAd)`.
I added some filters, you should not see them anymore.

**Comment by ghajini** [comment]
New 3rd parties
* etmewatuh.com * block
* xymtglljft.com * block

**Comment by ghajini** [comment]
Antiadblock again on clicking free download in next page 
![IMG_20190421_220635](https://user-images.githubusercontent.com/20338483/56472890-c44db180-6453-11e9-9a46-aaad86414b5a.jpg)

**Comment by dumbusernameidk** [comment]
No anti-adblock on my end.

**Comment by mapx-** [comment]
It seems they revert the last change

**Comment by ghajini** [comment]
Which one, I excepted CSP filter still antiadblock

**Comment by mapx-** [comment]
I mean ayefiles webmaster. No anti adb on my side.
If you still get it test:
`@@||ayefiles.com^$script,1p`

**Comment by ghajini** [comment]
Now I can't reproduce,  some race condition in filters...similar report filed here also
https://github.com/NanoMeow/QuickReports/issues/1039

**Comment by JobcenterTycoon** [comment]
This site try to open popups again. This site try to open `https://syndication.exdynsrv.com/splash.php?cat=&idzone=3365464&type=8&p=https%3A%2F%2Fayefiles.com%2Fyahph5pi15fi&sub=&block=1&el=&tags=&scr_info=aW5saW5lfHBvcE1hZ2ljfDEuMC4w` but its blocked by  Dan Pollock’s hosts file. (please delete cache, cookies on this site to reproduce)
