### ISSUE TITLE
http://themerkle.com/

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#536]
### URL(s) where the issue occurs

`http://themerkle.com/`
`https://themerkle.com/`

### Describe the issue

Unblocked orange Bitcoin IRA ad on right.

**Comment by mapx-** [comment]
I guess such very simple image ad should not be reported here. You could use "block element" to create a custom filter.

**Comment by terrorist96** [comment]
Yeah but it would still be unblocked for everyone else. Wouldn't it be better to get it added to the list so everyone can benefit?
`||themerkle.com/wp-content/uploads/2017/07/bitcoin-ira-300-600.png$image`

**Comment by mapx-** [comment]
I know, but such simple filters can be created by every uBo (other adblocker) user. 
IMO it's no need to have a giant list for such things. 

Well, it's up to uBo maintainers to include (or ..exclude) such filters.

**Comment by anewuser** [comment]
@mapx- You would need to argue why adding a filter for this is a bad idea. Saying that it gives people a "giant list" isn't an argument unless you prove that there's a noticeable performance impact _and_ that this specific site isn't worth being in the list, while all the other existing entries are.

**Comment by gorhill** [comment]
I suggest following filter is added to EasyList:

    /bitcoin-ira-*.png$image

fyi @ryanbr

**Comment by terrorist96** [comment]
How do we distinguish what gets added to the uBlock filter list and what is deemed better to be added to EasyList? As I mentioned before, I came here because I was tired of unresponsiveness from EasyList maintainers.

**Comment by okiehsch** [comment]
I would say
1. All issues that can only be solved by uBO-specific filters.
2. All issues that break functionality of a website because of a filter that is part of uBO-default setting.
3. All issues of websites using anti-adblock

should be added to the various `uBlock filter` lists, in my opinion.

**Comment by terrorist96** [comment]
@gorhill @okiehsch Have you attempted to gain merge permissions for EasyList from either @ryanbr @khrin or @monzta? It would be much more efficient and you guys are definitely qualified, IMO.

@okiehsch It's nice that reports of broken sites can be quickly dealt with here as reports for broken sites or unblocked ads are very slow (if at all) to be fixed on EasyList's Github issue page. :disappointed:

**Comment by okiehsch** [comment]
I do not want any merge permissions, if you have an issue you can open it here and it will remain open
until somebody comes up with a fix, that does not mean that any fix has to be part of the uBlock filter list.
