### ISSUE TITLE
Ublock Origin detect by player.pl

### ISSUE THREAD

**Issue by seba2282** [uBlockOrigin/uAssets#5360]
### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

Browser/Version: Firefox newest version
Ublock Origin version: newest

Settings: 
https://user-images.githubusercontent.com/16944478/56273948-18782f00-60fe-11e9-824b-0f47d76cc9cb.png
https://user-images.githubusercontent.com/16944478/56273957-1ca44c80-60fe-11e9-92e7-2d35660d3f2a.png
https://user-images.githubusercontent.com/16944478/56273967-2332c400-60fe-11e9-90bd-5a17664d98d3.png
https://user-images.githubusercontent.com/16944478/56273976-27f77800-60fe-11e9-9cad-887e2b1b9605.png

I reproduced my issue here: 
https://github.com/uBlockOrigin/uBlock-issues/issues/532
And have information about reproduce here.

Problem is: Ublock Origin is detect by player.pl and more sites.
Here link to example video:
`https://player.pl/programy-online/kuchenne-rewolucje-odcinki,114`

Screenshoot:
https://user-images.githubusercontent.com/16944478/56274302-c8e63300-60fe-11e9-8fca-de9297007bb8.png

Can I please help?

**Comment by mapx-** [comment]
- test again using **only the default setup** (you enabled a lot of lists and other custom lists - **as regional keep only the 2 official lists enabled**)
- be sure you have only a blocking extension (add-on) enabled
- did you first report here:
https://github.com/olegwukr/polish-privacy-filters/issues
- the video is visible only in Poland, so I'll be able to test (using a proxy) in few hours

**Comment by mapx-** [comment]
@olegwukr

**Comment by seba2282** [comment]
@mapx-, I didn't report that first for @olegwukr. Because is it big problem in all browsers and Adblockers extensions. Only Adguard and duet nano Adblocker with Defender skip that problem. I observed that. 
It was. But @olegwukr if you have suggest to fix, can you help?

**Comment by mapx-** [comment]
Did you read / test as I wrote above ?

**Comment by seba2282** [comment]
I made all without report that first to @olegwukr. On proxy is worse, default list active is more detect ublock Origin. And I used only ublock Origin to test. I don't care about cookies was disabled to test.

**Comment by kulfoon** [comment]
We've discussed it there https://github.com/olegwukr/polish-privacy-filters/issues/67 and it is unfixable by pure adblocker,  one must use an external script/addon to bypass it, like Nano Defender or one of these https://github.com/reek/anti-adblock-killer/issues/1854#issuecomment-246677465. So the issue can be closed.

**Comment by seba2282** [comment]
I saw all. But I want say thank you all for try helping. You are great. 👍🙂
