### ISSUE TITLE
android-dz.com

### ISSUE THREAD

**Issue by smed79** [uBlockOrigin/uAssets#5361]
**URL**

* `https://www.android-dz.com/red-dead-redemption-2-pc-42519`

**Describe the issue**

- Annoyance: 
  - disabled right click
  - disabled text selection
  - disabled text copy
  - disabled view source

**Comment by mapx-** [comment]
```
android-dz.com#$#abort-on-property-write.js nocontext
android-dz.com#$#abort-current-inline-script disableSelection reEnable
```
