### ISSUE TITLE
Anti-adblock in ebb.io again

### ISSUE THREAD

**Issue by SF90** [uBlockOrigin/uAssets#5363]
### URL(s) where the issue occurs
`https://ebb.io/anime/153x207`

### Describe the issue
Anti adblock 
Same problem as Issue #5346 I have tried to add 
@@||pagead2.googlesyndication.com/pagead/$script,domain=ebb.io 
in "my filters" but it still doesn't work

### Screenshot(s)
![ebbio](https://user-images.githubusercontent.com/49724790/56297821-a6d2cc00-6163-11e9-8a83-209b33333ad5.jpg)

### Versions

- Browser/version: firefox 66.0.3
- uBlock Origin version: 1.18.16
### Settings
Normal settings

### Notes

To play the video, a google account is required.

**Comment by mapx-** [comment]
followed steps :
- go to the above link
- click on the right side 1.11 or 2.22
- I get no anti adblock message
- I get:
![image](https://user-images.githubusercontent.com/10303732/56302241-a6254000-6139-11e9-9aaa-46fac546a3d9.png)

To get the anti adb message do I need an account ?

**Comment by mapx-** [comment]
@lain566 could you test again the ebb issue ?

**Comment by lain566** [comment]
It still works for me, I don't see any anti-adblock warning.

![Anotación 2019-04-17 182018](https://user-images.githubusercontent.com/27441315/56304081-9c054080-613d-11e9-9b52-a4e874b22afe.png)

**Comment by mapx-** [comment]
@SF90  it seems to be something on your side.
- check again your settings (if default ones), close / open browser, update lists etc
