### ISSUE TITLE
sozialversicherung-kompetent.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5365]
### URL(s) where the issue occurs

`https://sozialversicherung-kompetent.de/rentenversicherung/leistungsrecht/207-erwerbsminderungsrente-fuer-behinderte.html`

### Describe the issue

Unblocked Picture Ads

### Screenshot(s)

<img width="818" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/56318716-07600a00-6160-11e9-8f78-30cad0737f6d.PNG">

### Versions

- Browser/version: Firefox 66.0.3
- uBlock Origin version: v1.18.16

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3091437/Settings.txt)

### Notes

The filter `sozialversicherung-kompetent.de##^script:has-text((window);)` works for me

**Comment by JobcenterTycoon** [comment]
Ads are back again

**Comment by mapx-** [comment]
maybe @okiehsch could reproduce the ads, I get nothing

**Comment by okiehsch** [comment]
I can reproduce.
