### ISSUE TITLE
verystream.com pop up ads

### ISSUE THREAD

**Issue by ealgase** [uBlockOrigin/uAssets#5366]
### URL(s) where the issue occurs

`https://verystream.com/stream/E46hW7WYpyY/Rupture_%5BHD%5D_%282016%29_Bluray_1080p.mp4` (NSFW ads)

### Describe the issue

When clicking the "play button", a pop up ad opens. Eventually it redirects to runtnc.net, which is blocked.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: 73.0.3683.88 (Official Build) beta (64-bit)
- uBlock Origin version: 1.18.16

### Settings

- All Built-in, Ads, Privacy, Malware domains, Annoyances, and Multipurpose filters are enabled.

### Notes

This is a website similar to openload.co.  It appears to be using a modified version of popads.

**Comment by okiehsch** [comment]
I already added `verystream.com##+js(abort-on-property-read.js, open)` earlier today. https://github.com/uBlockOrigin/uAssets/commit/6334507ac274f0b9ed83f2f78ce92165d920f0e5

Do you still get popups if you update your `uBO-filters` list?

**Comment by ealgase** [comment]
Wow, thank you!
