### ISSUE TITLE
Disqus blocked

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#537]
### URL(s) where the issue occurs

`http://www.datpiff.com/50-Cent-Guess-Whos-Back-mixtape.72409.html`

### Describe the issue

EasyList blocks Disqus at the bottom

**Comment by okiehsch** [comment]
That exception filter will result in uponit-ads showing up on my end.
![upo](https://user-images.githubusercontent.com/16838044/28291320-3e99f0ac-6b4a-11e7-8e05-72b935b78271.JPG)

This site uses a slightly different `uponit` script.
Does
````
||datpiff.com^$csp=script-src 'self' * 'unsafe-inline' data:
datpiff.com#@#iframe[style]
````
work for you without breaking anything?

**Comment by mapx-** [comment]
weird, I get no ads ..

**Comment by terrorist96** [comment]
@okiehsch I'm also noticing that if you try to download a song or album, the captcha won't load.

**Comment by okiehsch** [comment]
@mapx-  the ads are loaded via webrtc on my end.
![unbent](https://user-images.githubusercontent.com/16838044/28291912-fbc176d0-6b4c-11e7-9daa-6c681f54fe76.PNG)

@terrorist96 captcha loads here with or without the added filters.

**Comment by terrorist96** [comment]
False alarm. Privacy Badger was blocking it. I'll report that there. Thanks

**Comment by ghajini** [comment]
Don't use privacy badger.....it will only cause false alarms

**Comment by gorhill** [comment]
@mapx- 

> weird, I get no ads ..

Are you using uBO with _"Prevent WebRTC from leaking local IP addresses"_ enabled? If so, the side effect of that setting is to prevent remote webtrtc connection attempts.

**Comment by mapx-** [comment]
Oh, probably yes (I'll check at home).

**Comment by mapx-** [comment]
yep, I confirm that setting is ON.
Can it defeat all the webrtc tricks ?

**Comment by gorhill** [comment]
My understanding is that it's a side effect of not using a proxy, since uBO uses `disable_non_proxied_udp` for `chrome.privacy.network.webRTCIPHandlingPolicy`.
