### ISSUE TITLE
Youtube occasional errors

### ISSUE THREAD

**Issue by geckolinux** [uBlockOrigin/uAssets#5370]
### URL(s) where the issue occurs
`https://www.youtube.com/watch?v=D5P5tm5nd3Q`

### Describe the issue

Intermittent error at the beginning of some Youtube videos. Probably intermittent because I'm in a geographical region with less ad targeting, so many Youtube videos don't have ads. When the error happens, it shows a black or "TV static" page with an error code. When I disable uBlock and reload the same video, it starts with an ad and later plays the video without issues. If I don't disable uBlock and the error appears, it starts playing the video with no ads after about 10 seconds.

### Screenshot(s)

- https://i.imgur.com/JF8spzz.png
- https://i.imgur.com/IjXBTtJ.png

### Versions

- Browser/version: Firefox/66.0.2 (openSUSE Tumbleweed x86-64)
- uBlock Origin version: 1.18.16

### Settings

No changes to default settings. Added additional "spa" "AdGuard Spanish/Portuguese" and "spa" "EasyList Spanish" filters.

**Comment by mapx-** [comment]
> at the beginning of some Youtube videos.

Provide the links

**Comment by geckolinux** [comment]
> > at the beginning of some Youtube videos.
> 
> Provide the links

Here's one:
https://www.youtube.com/watch?v=D5P5tm5nd3Q
[[screenshot](https://i.imgur.com/IjXBTtJ.png)]

**Comment by smed79** [comment]
no issue and no ads here. 

Post screenshos of [the logger](https://github.com/gorhill/uBlock/wiki/The-logger).

**Comment by geckolinux** [comment]
Like I said, I'm in a different region, so it won't behave the same.

For this video, which generated an error: `https://www.youtube.com/watch?v=32gyFIWecuw`
[[screenshot](https://i.imgur.com/yD8ldI6.png)]

**Comment by smed79** [comment]
test
```
@@||www.youtube.com/get_video_info?$xmlhttprequest
```

**Comment by mapx-** [comment]
see also https://adblockplus.org/forum/viewtopic.php?f=1&t=45200

Could be (broken) your YT account. Try another one.

**Comment by mapx-** [comment]
or try the same YT account using another browser (chromium for example)

**Comment by uBlock-user** [comment]
site issue, nothing to do with uBlock.
