### ISSUE TITLE
playvids, peekvids, pornflip (NSFW)

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#5371]
### Describe the issue

[If you click on a video then a newtab opens with the video you clicked while your first tab is redirected to `syndication.dynsrvtbg.com`. All three sites do this.]

### Versions

- Browser/version: [Chrome latest build]
- uBlock Origin version: [1.18.16]

### Settings

- [default]

**Comment by dumbusernameidk** [comment]
Doesn't seem the filter works. Clicking on a video still redirects you to `syndication.dynsrvtbg.com`. The only way I can fix it is with `##+js(abort-on-property-read.js, pop_target)`.

**Comment by mapx-** [comment]
That filter will kill the player.
try
`https://www.peekvids.com/v/soe-woman-busty-hana-haruna/cShMjlgZXHy`

**Comment by dumbusernameidk** [comment]
Seems to be working fine for me hm...

**Comment by okiehsch** [comment]
Hm, the current fix work for me with Chromium and Firefox. I get no popups clicking on the video at
`https://www.peekvids.com/v/soe-woman-busty-hana-haruna/cShMjlgZXHy`.

**Comment by dumbusernameidk** [comment]
Now I don't anymore.

**Comment by dumbusernameidk** [comment]
@mapx- 
another site to add `pornoeggs.com`

**Comment by dumbusernameidk** [comment]
ad when watching video has countdown timer. adding `||montafp.top^$3p` works.
