### ISSUE TITLE
thuglink.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5372]
URL(s) where the issue occurs

`https://thuglink.com/get/fn3TKxDsf5`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 73 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.18.16

Settings

Default

**Comment by Jap2-0** [comment]
`thuglink.com##+js(bab-defuser.js)`

**Comment by Jap2-0** [comment]
@mapx- I'm still getting a blockadblock popup when I update ublock filters.

**Comment by mapx-** [comment]
Did you get in the logger those filters ?

**Comment by Jap2-0** [comment]
Hmm, now it's working fine.  I wonder if Github has a few minutes of a delay or something?

**Comment by mapx-** [comment]
5 - 10 min of delay between the commit and a possible forced update

**Comment by Jap2-0** [comment]
Ah, okay.  I was wondering it it was Github or my sanity...
