### ISSUE TITLE
porngrey.com [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5373]
URL(s) where the issue occurs

`https://www.porngrey.com/video/heyzo-japanese-maid-sex/`

Describe the issue

the video looks small

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 73 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.18.16

Settings

Default

**Comment by KiLL4FuNK** [comment]
the video looks small

**Comment by mapx-** [comment]
test
```
@@||ads.exosrv.com/ads.js$script,domain=porngrey.com
@@||syndication.exosrv.com/ads-iframe-display.php$subdocument,domain=porngrey.com
```

**Comment by KiLL4FuNK** [comment]
It works well
