### ISSUE TITLE
swatchseries.to banner ads

### ISSUE THREAD

**Issue by Iaycomand** [uBlockOrigin/uAssets#5374]
### URL(s) where the issue occurs
`https://www1.swatchseries.to/episode/office_s5_e11.html`

### Describe the issue

this page shows banner ads up and right, doesn't pop up instantly  it takes about 1 second to shows up.

### Versions

- Browser/version: Google Chrome/Version 73.0.3683.103 (Official Build) (64-bit)
- uBlock Origin version:  v1.18.16

### Settings

- No changes to default settings.

**Comment by mapx-** [comment]
I fixed it today morning, update ublock filters, test again

**Comment by ghajini** [comment]
`https://www1.swatchseries.to/freecale.html?r=vecyJcjdCI6ImxzUlRJNpzYwbHZSU1uVtOWV1UnkjyaVFJbmNEdkdmXC9sMUJ3bm1zcURqWXdZUTZLenVmYkdrbFZSUTRTT1l5a1RpIiwiaXYiOiJkMjQ3NmUwZWE0NzA1YzU4NWYwODEwZTlmNGFiMjRlMiIsInMiOiIzMzk3MDk4MDYyODNhYWUxIn0=`

This rule
swatchseries.to##+js(set-constant, String.prototype.charCodeAt, trueFunc)

Is causing breakage
***click here to play***  button is hidden due to this filter.....

**Comment by ghajini** [comment]
`https://www1.swatchseries.to/freecale.html?r=lekyJzjdCI6Im5GYkZ5Sg0Y4NjF3XCz9qUEFuOXFjHXC9GM0E4aEVibE1ZUGduVTFtV3JrU0VUNkxlazlhcGRZallyYXhoNllxd1NSZyIsIml2IjoiNmYzYjU4MjRmZmM1YmM2MGEwNGVhYjU2YWFiM2QwNDkiLCJzIjoiODBkZGY5MjliYzRhZGEzNCJ9`

When clicked on `Click here to play` ,iam not getting navigated to destination site ie `onlystream.tv` but tab is closed due to some easylist erroneous  popup filter

**Comment by mapx-** [comment]
all fine on my end => FF / chrome desktop, are you about android ?

**Comment by ghajini** [comment]
No its opera desktop browser

**Comment by mapx-** [comment]
same behaviour on opera

**Comment by ghajini** [comment]
I tested on firefox android also
Problem occurs on 1st visit of site

This rule

 `/^https?:\/\/.*[&|%|+|=].*/$popup,domain=0123movies.com|1337x.to|1360nobs.com|3shktv.com|68dare-t.com|8gharb.com|9anime.vip|9rendezvous-l.com|absolutetechnology.ru|ahoypirate.in|ajournaledlife.us|akvideo.stream|all4music.ovh|allmyvideos.net|ancensored.com|ancient-origins.net|andomp3.com|androblanco.com|androidyes.com|animeflv.net|animetak.com|animetrick.com|anitube.cz|aniwatcher.com|aponu.org|avgle.com|avimobilemovies.co|bayception.pw|bayfiles.com|bestfullmoviesinhd.org|bestfunnypic.com|bestgist.com.ng|biobses.com|bit-url.com|bittorrent.am|bluromstockoficial.com|books4arab.com|c123movies.com|canonprintersdrivers.com|cdnx.stream|channel1vids.com|cimaclub.org|cinemaghar.com|cinemamkv.net|clicknupload.org|clipconverter.cc|clipwatching.com|cloudvideo.tv|cruzing.xyz|cvalfabeta.com|dashbo15myapp.com|dealzat.com|dospelis.com|downace.com|downloadpirate.com|drestha.com|dropapk.com|dvb-p.com|ebooksz.net|egoallstars.com|emule-island.co|escdn.co|escolhasegura.com|extreme-board.com|eztv.io|eztv.tf|eztv.yt|ffmovies.ru|fileone.tv|filme-bune.biz|filmlinks4u.is|flash-x.tv|flashsx.tv|flashx.cc|flashx.co|flashx.me|flashx.pw|flashx.run|flashx.sx|flashx.to|flashx.tv|flashx.ws|flashx1.tv|flvto.biz|fmovies.taxi|fmovies.to|fmovies.world|fmovieson.com|fp-news.com|freetv.gq|fullmatchesandshows.com|gaempire1.com|gambarupdate.com|gamez1a.com|gamezup.com|gelbooru.com|getlink.pro|glawheejoushpush.com|gnula.se|go-student.net|gogoanime.io|gomoviess.net|gostreams.net|gotwatch.net|grammarist.com|h-98reale.com|hackiee.mobi|hdvid.tv|healthline.com|hereishealth.com|hotshotgamers.net|igg-games.co|ilmutekniksipil.com|image-bugs.com|imagebam.com|imagefruit.com|imagerar.com|imgadult.com|imgbox.com|imgdew.pw|imgdrive.net|imgmaze.pw|imgshots.com|imgspice.com|imgtaxi.com|imgtown.pw|imgview.pw|imgwallet.com|indishare.org|indoxxi.tv|intoupload.net|iptvlinkshare.com|j69i-browser.com|jkanime.net|join4films.com|keratosispilaris101.com|kevindjakporblog.com|kimcartoon.to|kissanime.ru|kissasian.ch|kissasian.sh|kisscartoon.ac|klubesocial.com|kora-online.tv|latestsocial.com|latribunaonline.com|lawavedesign.com|limetorrents.info|linkotes.com|livrefilmeshd.net|load2u.com|lookbeauty.ir|m4ufree.com|m4ufree.tv|maghribtech.com|megafilmes.org|megaup.net|mixdrop.co|mmsubtitles.co|mobdropro.com|mobile5shop.com|mobilemovies.info|mobilephonedir.com|monova.org|monova.to|movie4k.is|movies2k.pro|moviesweb.info|moviewatcher.is|mp3fusion.net|mp3indirdur.mobi|mp4upload.com|mstream.cloud|musicdl.org|musicfocus.net|myfile.is|myreadingmanga.info|mywebtv.info|naijagospelnews.info|naijajobnews.com|naijatechdeals.com|narutoget.io|needrombd.com|newjobsinfo.in|newmusicalbum.host|newser.com|noobnoob.rocks|nosteamgames.ro|nowvideo.club|nutritioninsight.com|obourguide.com|ogario.ovh|ojimail.ru|olympicstreams.me|on4top.com|onlinevideoconverter.com|onvid.xyz|openloadmovies.bz|ourl.io|overdoseofprose.com|paidshitforfree.com|paifemouchoa.com|panduansaya.com|peggo.tv|pelisstar.com|phenomenologicalpsychology.com|piratebay.tel|piratebay.town|piratebayblocked.com|pirateiro.com|pirateproxy.sh|play4vid.com|playercdn.net|podslushano-goroda.ru|pornparadise.org|powvideo.net|pro100full.ru|prox4you.xyz|proxyindia.net|pushedwebnews.com|putlocker.fyi|putlocker.ninja|putlocker.style|putlockers.fm|putlockers.mn|putlockers.movie|putlockertv.to|q1-tdsge.com|q15homgeneral.com|queenfaucet.website|r2sa.net|rapidotorrents.net|rarbg.to|rarbgaccess.org|rarbgmirror.com|rarbgmirror.org|rarbgmirror.xyz|rarbgmirrored.org|rarbgproxy.org|rarbgprx.org|rarbgunblock.org|readcomiconline.to|repelis.net|romstorage.com|rule34hentai.net|safetricks.org|seedpeer.me|seehd.pl|sendit.cloud|sendspace.com|sendvid.com|series9.to|seriesonlinex.org|sexuria.com|sharemania.us|shuglaursech.com|shugraithou.com|skynetdownloads.net|socialvone.com|solarmoviesc.com|sportp2p.com|stickerdeals.net|stream2watch.org|stream2watch.ws|streamplay.to|superbay.link|surestakes.com|swatchseries.to|taiphanmemmienphi.com|taisachhay.com|techrecur.com|telepisodes.co|thefmovies.me|thepiratebay.kiwi|thepiratebay.org|thepiratebay10.org|tokusatsuindo.com|topeuropix.net|torlock.com|torrentdownloads.me|torrentfunk2.com|torrentz.to|torrentz2.eu|tricksmasters.com|tubidy.io|tv-direct.net|tvbd.live|tvnachat.net|uiz.io|ukmagazinesfree.com|ukpirate.org|unblockall.org|unblocked.is|unblocked.lol|unblocked.si|unblocker.cc|unblocktheship.org|up-load.io|upload-files.cc|upload.ac|uploadproper.com|uploadproper.net|uptobox.com|userscloud.com|ustreamix.com|v96-surf.com|vev.io|vidbull.tv|vidlox.me|vidoevo.com|vidotodo.com|vidoza.co|vidoza.net|vidtomp3.com|vidtoro.com|vidup.io|vidzi.tv|vipbox.live|vipleague.pw|vipstand.se|viralitytoday.com|washingmachineinside.com|watchcima.com|watchlivecricket.in|watchmovieonline.com|watchonlinemovies.com.pk|waudeesestew.com|wikiwiring.com|winnzo.com|wotcheatmods.com|xxxfun.online|y2mate.com|yify-movies.net|ymovies.to|yourbittorrent2.com|youwatch.org|youzik.com|ytd-downloader.com|zeitschriftpdf.com|zippyshare.com`

![Screenshot_2019-12-19-23-45-26-917_org mozilla firefox](https://user-images.githubusercontent.com/20338483/71199439-faca1d80-22bb-11ea-9d66-f4cf0e76fac5.png)

Causing existing valid tab to be closed(any valid popup is closed by that filter which matches sites mentioned)

Video captured =

`https://streamable.com/glwa0`

**Comment by mapx-** [comment]
I tested FF android too => all ok on my end

**Comment by ghajini** [comment]
I can consistently reproduce, like I try everyday, click `onlystream.tv`,which is opened in new tab then it is closed immediately by easylist popup filter....

Would you suggest custom filter against popup filter of easylist  for `onlystream.tv`
