### ISSUE TITLE
redensarten-index.de [Anti-Adblock]

### ISSUE THREAD

**Issue by Scunkaneli** [uBlockOrigin/uAssets#5378]
### URL(s) where the issue occurs

`https://www.redensarten-index.de/suche.php`

### Describe the issue

Adblock detection popup shows on top of the website.

### Screenshot(s)

https://i.imgur.com/sWAizPC.jpg

### Versions

- Browser/version: FF 67.0b11
- uBlock Origin version: 1.18.16

### Settings

Default

### Notes

fixed with `redensarten-index.de##+js(set-constant.js, is_banner, true)` because of this part of the website:
```
<script type="text/javascript" src="werbebanner.js"></script>
  <script type="text/javascript">
   if(typeof is_banner == 'undefined') 
   {
     document.getElementById('hinweis').style.display='block';
     document.getElementById('grau').style.display='block';
    }
</script>
```

**Comment by okiehsch** [comment]
Thanks.
