### ISSUE TITLE
provide anti adblock for dropapk.com

### ISSUE THREAD

**Issue by swathigrate** [uBlockOrigin/uAssets#5379]
https://dropapk.com/jk1mlpr4gfj4

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

Showing message of anti Adblock 

### Screenshot(s)

![Screenshot_2019-04-20-06-41-18-528_org mozilla firefox](https://user-images.githubusercontent.com/14991260/56449577-fef80280-630a-11e9-9356-a98bc9290cc2.png)

### Versions

- Browser/version: 66
- uBlock Origin version: 1.18.4

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by ghajini** [comment]
`https://dropapk.to/4p3gwg6p8bje`
Antiadblock
