### ISSUE TITLE
vox.com unblocked video ad

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#538]
### URL(s) where the issue occurs

`https://www.vox.com/2016/5/19/11701976/rapping-deconstructed-best-rhymers-of-all-time`

### Describe the issue

Unblocked ad in video.

**Comment by okiehsch** [comment]
I can't reproduce, video plays without ads using Chrome or Firefox on my end.

**Comment by terrorist96** [comment]
I just tried in a new profile with only uBO with default settings and still got the ad. Here's my log:

[uBlock₀ — Logger.zip](https://github.com/uBlockOrigin/uAssets/files/1154293/uBlock.Logger.zip)
I clicked play on the video at 19:50:54

**Comment by okiehsch** [comment]
Sorry I still can't reproduce, somebody who can will have to fix this issue, if possible, which is not a given
with some video ads.

**Comment by terrorist96** [comment]
@gorhill @mapx- @SMed79 can any of you reproduce this?

**Comment by SMed79** [comment]
Video plays instantly without ads for me too.

**Comment by terrorist96** [comment]
Can you try a US IP?

**Comment by gorhill** [comment]
Can't reproduce.

> new profile with only uBO with default settings

Did you force an update of the filter lists after install?

**Comment by SMed79** [comment]
@terrorist96 Use the logger https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by terrorist96** [comment]
@SMed79 I did, see [here](https://github.com/uBlockOrigin/uAssets/issues/538#issuecomment-315917978).

**Comment by terrorist96** [comment]
Here's a screenshot:
![image](https://user-images.githubusercontent.com/12802056/28334381-f060f032-6bc8-11e7-86e7-4e326e6a5a50.png)

The red line indicates where I played the video and the ad started.

**Comment by mapx-** [comment]
I can reproduce using a us ip.
Could be `brightcove` unblockable ads ? (SSAI - baked in the stream)

**Comment by mapx-** [comment]
It seems the video (but also the video ads) are broken in segments

```
xhr | https://once-aws-us-west-2-lb.unicornmedia.com/now/media/segment...
xhr | https://brightcove.vox-cdn.com/permutation/
```

**Comment by pepablock** [comment]
I'm having problem even playing the video, unless I disable uBlock. _(Firefox 54.0.1 (64-bit); uBlock Origin 1.13.4)_
<img width="1680" alt="01" src="https://user-images.githubusercontent.com/29940017/28354840-bdc50e44-6c61-11e7-9300-42ed91810b4a.png">
<img width="1680" alt="02" src="https://user-images.githubusercontent.com/29940017/28354841-bdc9ddc0-6c61-11e7-9eb4-be2d98ac1d08.png">

**Comment by terrorist96** [comment]
@pepablock If you have privacy badger, you need to temporarily move these two to the yellowlist:
https://github.com/EFForg/privacybadger/issues/1512

**Comment by pepablock** [comment]
@terrorist96 I don't use Privacy Badger.

**Comment by gorhill** [comment]
You have Firefox's Tracking Protection enabled?

**Comment by pepablock** [comment]
I had leftover enabled third-party list (hpHosts’ Ad and tracking servers​​​​​), when I disabled the filter everything was working as it should. My bad.

**Comment by terrorist96** [comment]
I can't reproduce this anymore.
