### ISSUE TITLE
vidup.io notice to disable my ad block for a faster streaming.

### ISSUE THREAD

**Issue by Iaycomand** [uBlockOrigin/uAssets#5382]
### URL(s) where the issue occurs

`https://vidup.io/eovw36g6jw50`

### Describe the issue

this site ask me to disable my adblock to provide more speed in my streaming video (appears as top right side notice within the video).

### Screenshot(s)

https://postimg.cc/y3K3LmBs

### Versions

- Browser/version: Google Chrome/Version 73.0.3683.103 (Official Build) (64-bit)
- uBlock Origin version: v1.18.16

### Settings

- No changes to default settings.

**Comment by ghajini** [comment]
Video pauses at yellow dots in video stream   for 5sec

**Comment by mapx-** [comment]
I get no pause - tested in firefox

**Comment by ghajini** [comment]
Antiadblock

`https://vidup.io/5pwz8q8ggw3q`

Firefox android stable

Screenshot=

`http://prnt.sc/phkswy`

**Comment by mapx-** [comment]
I cannot reproduce the issue.
However, I get a warning (top right on video) about slowing down due to adblocking

test these filters
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=vidup.io
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect=noopjs,domain=vidup.io
```

**Comment by ghajini** [comment]
Issue not on desktop browsers

View page source
`https://pastebin.com/hdMwscfT`

**Comment by mapx-** [comment]
> test these filters

?

**Comment by ghajini** [comment]
Doesn't work

**Comment by okiehsch** [comment]
> I cannot reproduce the issue.
However, I get a warning (top right on video) about slowing down due to adblocking

Same on my end if I use an Android Firefox user agent.
I can't test with an actual Android device.

**Comment by mapx-** [comment]
Ok, i tested using an android phone, no issues

**Comment by ghajini** [comment]
`vidup.io/p1w6kxkx0mx8`
`vidup.io/2p7e1d5y0w3j`

Popup ads
Opera showing website try to load insecure content

**Comment by ghajini** [comment]
Opera is blocking insecure content 
What's that about?

**Comment by mapx-** [comment]
mixed stuff (http + https) which opera can block before uBO

**Comment by uBlock-user** [comment]
> What's that about?
Nothing to do with uBO, site is serving mixed content and Opera is blocking it.

**Comment by ghajini** [comment]
`https://vidup.io/02w910oxq7dk`

Antiadblock
