### ISSUE TITLE
Block phishing website

### ISSUE THREAD

**Issue by filips123** [uBlockOrigin/uAssets#5386]
### URLs where the issue occurs

`http(s)://www.okom.wroc.pl/`

### Describe the issue

That website contains many phishing and malware sites. I will describe one of them that I received.

---

I received phishing email targeting Chase US. They send me an email that my banking account is not verified and I should verify it.

On the first website, there is a fake CAPTCHA (which looks like Google's). When you solve it, you are redirected to the main (phishing) page.

The website then asks you for your bank account email and password, personal details (name, social security number, date of birth, driving license and many other), email, it's password and credit card information.

After you enter all information, you are redirected to the real Chase US website.

---

Note that you should probably block site's IP addresses.

According to [VirusTotal Graph](https://www.virustotal.com/graph/g4f5b6d29959149a889c71beef8864f0782beed8f272343e8a141f1f9d00c900f) for this website, it's IPs are also used for other malware websites. And there are even more malware sites on that domain.

Please research that and block all malware and phishing sites that are related to it. I don't have much time to do this.

### Screenshots

I uploaded all screenshots to Imgur:
https://imgur.com/a/6yJkKeO

**Comment by mapx-** [comment]
I get only

> Database Error: Unable to connect to the database:Could not connect to MySQLDatabase Error: Unable to connect to the database:Could not connect to MySQL

**Comment by filips123** [comment]
This is because there is no phishing in the root of site. Most of the malware and phishing sites are in subdirectories (mostly `cache`).

One of them that I received is `http://www.okom.wroc.pl/cache/A61ebbe3bg5e0f928`. It contains phishing site.

But there are even more malware and phishing sites on that domain and IPs. You could see some of them with VirusTotal Graph or other similar software.
