### ISSUE TITLE
oko.sh [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5390]
URL(s) where the issue occurs

`https://oko.sh/UhVg1A7R`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 73 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.18.16

Settings

Default

**Comment by dumbusernameidk** [comment]
third party requests from random number sites `oko.sh##+js(abort-current-inline-script.js, Math.sin, vocabulary)` fixes it.

**Comment by dumbusernameidk** [comment]
popup second page.

**Comment by ghajini** [comment]
Popup ads
`https://oko.sh/ivzU13`

**Comment by ghajini** [comment]
`||d22sfab2t5o9bq.cloudfront.net^$important`

**Comment by ghajini** [comment]
`https://oko.sh/9n6C`

3rd party tracking

`||oko.sh/sw_*.js$important`

**Comment by ghajini** [comment]
`https://oko.sh/dF0kC75`

Popup ads at last page when clicking anywhere

Screenshot=

`https://prnt.sc/pechgu`

**Comment by mapx-** [comment]
maybe android from your screenshot

**Comment by mapx-** [comment]
I cannot reproduce, try a similar filter (come per ouo)

`oko.sh##+js(aopr, open)`

**Comment by ghajini** [comment]
Yes firefox android.....

Popup starts like about blank, then this IP 35.224.227.218 carry forward popups

No it doesn't work...

**Comment by mapx-** [comment]
try
`oko.sh##+js(nowebrtc)`

**Comment by ghajini** [comment]
Added

oko.sh##+js(nowebrtc)
oko.sh##+js(aopr, open)
Works on my end

**Comment by ghajini** [comment]
`https://oko.sh/OzsyVYfV`
3rd party tracking after captcha completion page....

`||beiven.pw^$important`

**Comment by KiLL4FuNK** [comment]
ADS

`https://oko.sh/Lm6Fhk5k`
