### ISSUE TITLE
ulrichesch.de [breaked]

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5394]
### URL(s) where the issue occurs

`https://ulrichesch.de/emojis-pc/`

### Describe the issue

Only a blank screen when ublock is enabled

### Versions

- Browser/version: Firefox 66.0.3
- uBlock Origin version: v1.18.16

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3101526/Settings.txt)

### Notes

`##.headersocial` from Fanboy’s Annoyance List is the problem filter here. With `ulrichesch.de#@#.headersocial` i can fix this.

**Comment by mapx-** [comment]
@ryanbr

**Comment by mapx-** [comment]
or report here (if Ryan does not react to this issue)
https://github.com/ryanbr/fanboy-adblock/issues
