### ISSUE TITLE
app.tallo.com  breaks when `statCount.directive.js` is blocked

### ISSUE THREAD

**Issue by iboyperson** [uBlockOrigin/uAssets#5395]
### URL(s) where the issue occurs

`https://app.tallo.com/`

### Describe the issue

`app.tallo.com/assets/javascripts/app/studentstats/statCount.directive.js` is blocked by uBlockOrigin. This causes the page to say "There has been an issue loading the page" 

### Versions

- Browser/version: Google Chrome: 73.0.3683.103
- uBlock Origin version: v1.18.16

### Settings

* Nano Defender filter additions as well as setting `userResourcesLocation` to `https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt`
* Cloud Storage

### Notes

Adding a custom filter such as: `@@||app.tallo.com/assets/javascripts/app/studentstats/statCount.directive.js$script,domain=app.tallo.com` fixes the issue but none the less I thought that it should be reported in case there is a more "proper" fix.

**Comment by okiehsch** [comment]
Thanks.
