### ISSUE TITLE
https://www.pluspremieres.nz

### ISSUE THREAD

**Issue by dbree1** [uBlockOrigin/uAssets#5396]
Here on this site id has a problem with the Ad Block Warning Removal

[### URL(s) where the issue occurs](https://www.pluspremieres.nz/2019/04/lolo-zouai-caffeine-single.html)

### Screenshot(s)

https://abload.de/img/23ykvz.jpg

### Versions

- Browser/version: Google Chrome Version 73.0.3683.103 (Offizieller Build) (64-Bit)
- uBlock Origin version: uBlock Origin 1.18.16

**Comment by mapx-** [comment]
update your lists
