### ISSUE TITLE
yts.am popup

### ISSUE THREAD

**Issue by ericzutter** [uBlockOrigin/uAssets#5397]
### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`
`https://yts.am/browse-movies`

### Describe the issue

On website yts.am, sometimes at some random time, a popup appears that plays a video. uBlock Origin removes the playing video in the popup, but doesn't remove the whole popup. The "X" from the popup is remaining.

When trying to remove X-button manually with uBlock Origin, uBlock Origin let you choose between following cosmetic filters :
###id7a816c7708cross7a816c7708
###id7a816c7708cross-container7a816c7708
###id7a816c7708close-cross7a816c7708
###id7a816c7708close7a816c7708
###id7a816c7708container7a816c7708
##body > div:nth-of-type(8)

When I choose any of these cosmetic filters, the X-button is removed but there are no scroll-bars anymore.

You have to manually mouseclick on the "X", to remove the popup and let the scroll-bars appear.

How can I automatically remove the whole popup and let the scroll-bars appear ?

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]
![image](https://user-images.githubusercontent.com/4773453/56498995-a7bd8200-6504-11e9-9040-f51f13de6317.png)

### Versions

- Browser/version: [here] SRWare Iron 73.0.3800.0 (64-bits) on Windows 7 64-bits
- uBlock Origin version: [here] 1.18.16

### Settings

- [List here all the changes you made to uBO's default settings]

My filters :+1:
! 17-3-2019 https://yts.am
! remove advanced search on top
yts.am###main-search

! 17-3-2019 https://yts.am
! prevent that YTS header stays when scrolling down
yts.am##.nav-bar:style(position: absolute !important)

! 17-3-2019 https://yts.am
! remove NordVPN ad
yts.am##.ibox-bordered

My rules :
no-popups: yts.am true

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

On website yts.am, sometimes at some random time, a popup appears that plays a video. uBlock Origin removes the playing video in the popup, but doesn't remove the whole popup. The "X" from the popup is remaining.

When trying to remove X-button manually with uBlock Origin, uBlock Origin let you choose between following cosmetic filters :
###id7a816c7708cross7a816c7708
###id7a816c7708cross-container7a816c7708
###id7a816c7708close-cross7a816c7708
###id7a816c7708close7a816c7708
###id7a816c7708container7a816c7708
##body > div:nth-of-type(8)

When I choose any of these cosmetic filters, the X-button is removed but there are no scroll-bars anymore.

You have to manually mouseclick on the "X", to remove the popup and let the scroll-bars appear.

How can I automatically remove the whole popup and let the scroll-bars appear ?

**Comment by mapx-** [comment]
I get no popup X - button.
Could you test in firefox or chrome (you can use a portable one) using only the default settings in uBo (no rules, no custom filters) ?

**Comment by ericzutter** [comment]
Like I wrote, the popup appears at random times. So sometimes there is no popup and sometimes there is a popup. For your information webbrowser SRWare Iron is based on webbrowser Chromium like webbrowser Chrome so they behave in the same way. I did what you ask and installed Chrome with no extensions, installed uBlock Origin with default settings and go to https://yts.am/browse-movies. Because the popup appears at random times, I don't see directly a popup. 

I saved the webpage "https://yts.am/browse-movies" with popup (SRWare Iron) and without popup (Chrome). When I compare the 2 html-files I see a difference.

The webpage without popup contains the following line :
&lt;html lang="en">

The webpage with popup contains the following line :
&lt;html lang="en" style="overflow: hidden;">

In the zipfile "yts.am.zip" you can find the webpage "https://yts.am/browse-movies" that contains the popup :

[yts.am.zip](https://github.com/uBlockOrigin/uAssets/files/3108162/yts.am.zip)

After I click manually on the "X", the popup disappears and the scroll-bar is enabled again. I saved the webpage after I clicked on the popup in the zipfile "yts.am.no.popup.zip" so that you can compare the two versions :

[yts.am.no.popup.zip](https://github.com/uBlockOrigin/uAssets/files/3108211/yts.am.no.popup.zip)

Both zipfiles contain the webpage "https://yts.am/browse-movies" on SRWare Iron. I haven't been able to reproduce in Chrome because the popup appears at random times.

I suppose that the problem can be solved by removing the popup and removing the "overflow:hidden".

Will the following filter remove the "overflow:hidden" ?
yts.am##html:style(overflow: initial !important)

There is still a problem with blocking the popup. Because the cosmetic filter that uBlock Origin proposes to block the popup is different every day. Today (= yts.am.zip) uBlock Origin proposes to block the popup with following cosmetic filter :
##.ewgh > div

When I execute the proposed cosmetic filter "##.ewgh > div" the popup is not removed, and uBlock Origin proposes again to block the popup with the cosmetic filter "##.ewgh > div" . But when I look in uBlock Origin "My filters" I see that the cosmetic filter has already been added :
! 23-4-2019 https://yts.am
yts.am##.ewgh > div

**Comment by yourduskquibbles** [comment]
> yts.am##html:style(overflow: initial !important)

That probably won't work (it's also missing the `;` sign after !important). 

Try adding `yts.am##html:style(overflow: auto !important;)` to My filters and see if issue is fixed for you.

**Comment by mapx-** [comment]
add
```
yts.am##[id*="container"]
yts.am##html:style(overflow: auto !important;)
```

**Comment by ericzutter** [comment]
I use a portable version of SRWare Iron. Every time I restart my webbrowser SRWare Iron, the popup directly appears after a few seconds. I reinstalled uBlock Origin with default settings and added your two filters to My Filters. When I restart my webbrowser SRWare Iron, the popup still appears but now next to the "X", it also plays the video inside the popup. So the two filters did not help. I made a backup of this portable version, so that I can easily use this to test this popup. 

I also noticed that yts.am creates a lot of cookies since they decided to add popups to their website. The old version of their website which had no popups didn't have so much cookies. yts.am also stores data in the localstorage (no other websites on my webbrowser have data stored in localstorage, so this is a very strange behavior). I think that yts.am uses the cookies to show the popup at random times. So I deleted the cookies from yts.am and blocked the cookies on yts.am. When I restarted webbrowser SRWare Iron the popup didn't re-appear. I can not be 100% sure that blocking the cookies will solve the problem, because the popup appears at random times, but right now it works.

I have kept the backup of my portable version of SRWare Iron, in case I would need it for future testing of this popup.

**Comment by mapx-** [comment]
Using your saved page I found those filters removing the overlay.

**Comment by ericb2038** [comment]
the yts.am##[id*="container"] filter is too broad, it blocks the quick search (id="quick-search-container") in the header, which removes the search functionality on the site, part of it at least: you can still search by going to the browse movie page, but it's annoying. Please retarget the containers that must be blocked more precisely.
Without ulbock :
![Screenshot_2](https://user-images.githubusercontent.com/50086092/56870155-449f8400-6a0b-11e9-8dd4-068833ce305f.png)

with ublock: 
![Screenshot_3](https://user-images.githubusercontent.com/50086092/56870163-5ed96200-6a0b-11e9-9f68-ddb439696f6f.png)

**Comment by ericzutter** [comment]
Since I blocked the cookies on yts.am (in my web browser settings), I had no popups anymore. So blocking the cookies on yts.am solved my problem, so there is no need to block the popup with uBlock Origin.

Also for identifying the popup with uBlock Origin there is the problem that every day uBlock Origin proposed a different filter to block the same popup because yts.am changed the identification of the popup every day.
