### ISSUE TITLE
mediaite now blocking ad blockers 

### ISSUE THREAD

**Issue by thexfile** [uBlockOrigin/uAssets#5399]
### URL(s) where the issue occurs

`https://www.mediaite.com/`

### Describe the issue

Now blocking ad blockers.

### Screenshot(s)

https://postimg.cc/Zvxqc4Zh

### Versions

Google Chrome v73
uBlock Origin development build v1.18.17b10

**Comment by yourduskquibbles** [comment]
Videos not loading/working on example page `https://www.mediaite.com/news/jeff-bezos-ridiculed-for-tone-deaf-victory-lap-thanking-amazon-workers-and-shoppers-you-guys-paid-for-all-this/` removing `mediaite.com##+js(aopr, adthrive.config)` seems to fix this with no ads coming through that I can see.
