### ISSUE TITLE
Cosmetic filtering blocks 'subscribe' button on Reddit

### ISSUE THREAD

**Issue by mat2py** [uBlockOrigin/uAssets#540]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

[www.reddit.com/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/comments/6i6g9b/cosmetic_filter_blocking_subscribe_button/)

### Describe the issue

Cosmetic filtering hides the subscribe button on Reddit. Toggling it off and refreshing, reveals it.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/16655368/28327364-c72ae152-6ba8-11e7-9eeb-384dad81bbf3.png)

'Subscribe' button should be to the left of '+shortcut'

### Versions

- Browser/version: Firefox 54.0 64bit
- uBlock Origin version: 1.13.4

### Settings

- Don't think anything is different

**Comment by anewuser** [comment]
Use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) to find out what list has hidden it, and report the problem to the maintainers of that list.

**Comment by jjohns71** [comment]
What browser / filter lists? I can not recreate.

**Comment by okiehsch** [comment]
I can not reproduce, here is `reddit.com/r/uBlockOrigin` on my end using uBO default settings.
![ddft](https://user-images.githubusercontent.com/16838044/28329883-d42ef67a-6beb-11e7-8853-9633d2383332.PNG)


And here if I also add the `reddit enhancement suite`
![eefsdfsnt](https://user-images.githubusercontent.com/16838044/28329894-ddde7236-6beb-11e7-8b76-3af07a1b3517.PNG)

**Comment by mat2py** [comment]
anewuser I opened the logger but I can't find which option is the one causing it to be blocked.

**Comment by mat2py** [comment]
Deleted the 3 "My filters" I had and it works now.. They were unrelated as far as I could tell but it seems that the subscribe button got caught in the net of their filter.. This can be closed
