### ISSUE TITLE
kutpay.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5404]
URL(s) where the issue occurs

`http://kutpay.com/FwlIJyT`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 73 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.18.16

Settings

Default

**Comment by Jap2-0** [comment]
`kutpay.com##+js(set-constant.js, checkAdblockUser, noopFunc)`

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/84580704/120016480-563e2600-bfed-11eb-823c-64f12040ea79.png)
