### ISSUE TITLE
S3 firefox addons contain ad/spy functionality, hidden popups

### ISSUE THREAD

**Issue by caviidae** [uBlockOrigin/uAssets#5409]
Sorry in advance if this is the wrong place to report. If there is a better place please let me know.

### The issue
A bunch of popular Firefox addons created by the same author have a pesky 'advertising' function built in and enabled by default which reports which websites you are visiting to their server. I started noticing random popups which open and then close immediately so I started investigating and found the following information. In my experience, the advertising option is enabled by default and the behaviour started recently even though I had told the addons I did not want to support their advertising in the past. It happens on several of their addons.

While browsing any website, there is a chance a popup/tab will open where a POST will be made from behind-the-scene to `http://discount.s3blog.org/addon.html` containing information about which of their addons triggered the request and the domain the user was visiting. It then redirects to another server, currently `dataprovider.biz`, passing on the same information. The popup/tab then closes instantly. Older forum posts about these addons indicate that it also previously redirected to `crvtck.com`.

Most, if not all of these addons, are rebooted versions of addons previously abandoned by their original authors. This person has done a good job to keep them active and working with newer versions of Firefox but has quietly added some nasty behaviour. A few of the addons seem to have disappeared from AMO recently, but many people most likely still have the addons installed. I have also noticed that the author has Chrome versions of some of these addons which may also have the same bad behaviour.

### Solution
Apart from not using these addons of course. To protect users who already have the addons or may install them.
I am not sure what the best course of action would be for uBlock/uMatrix/filter list maintainers.
But this is what I have currently in uMatrix to prevent the issue and possible changes by the author:
```
* discount.s3blog.org * block
* dataprovider.biz * block
* crvtck.com * block
behind-the-scene s3blog.org * block
```
IMO `discount.s3blog.org` should be considered a bad subdomain as it is the first request made each time and then it redirects to other domains. `dataprovider.biz` seems to be that current domain and `crvtck.com` was possibly the previous one. They should be considered bad domains. I blocked all behind-the-scenes for `s3blog.org` too just in case they switch to another subdomain.

### HTTP logs
Different times I visited `google.com` to and triggered the requests. Click:

<details>
<summary>request, post data and response - screengrab addon</summary>
<p>

```
POST /addon.html HTTP/1.1
Host: discount.s3blog.org
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 120
DNT: 1
Connection: keep-alive

addon=screengrab-fix-version
url=https://www.google.com
ref=https://www.google.com
x_frame=checkserver

HTTP/1.1 302 Found
Server: Apache/2.2.15 (CentOS) mod_fcgid/2.3.9 mod_ssl/2.2.15 OpenSSL/1.0.1e-fips
Location: https://dataprovider.biz/api?key=5853ecc71178be9962ad851ff3626443c30cd53a&out=https%3A%2F%2Fwww.google.com&uid=o256&format=txt
Cache-Control: max-age=25920000
Content-Length: 0
Connection: close
Content-Type: text/plain; charset=UTF-8
```

</p>
</details>
<details>
<summary>request, post data and response - menu wizard addon</summary>
<p>

```
POST /addon.html HTTP/1.1
Host: discount.s3blog.org
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 77
DNT: 1
Connection: keep-alive

addon=s3menu-wizard
url=https://www.google.com
ref
x_frame=checkserver

HTTP/1.1 302 Found
Server: Apache/2.2.15 (CentOS) mod_fcgid/2.3.9 mod_ssl/2.2.15 OpenSSL/1.0.1e-fips
Location: https://dataprovider.biz/api?key=5853ecc71178be9962ad851ff3626443c30cd53a&out=https%3A%2F%2Fwww.google.com&uid=o256&format=txt
Cache-Control: max-age=25920000
Content-Length: 0
Connection: close
Content-Type: text/plain; charset=UTF-8
```

</p>
</details>
<details>
<summary>request, post data and response - after the redirect</summary>
<p>

```
GET /api?key=5853ecc71178be9962ad851ff3626443c30cd53a&out=https%3A%2F%2Fwww.google.com&uid=o256&format=txt HTTP/1.1
Host: dataprovider.biz
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded
DNT: 1
Connection: keep-alive

key=5853ecc71178be9962ad851ff3626443c30cd53a
out=https%3A%2F%2Fwww.google.com
uid=o256
format=txt

HTTP/1.1 200 OK
Server: nginx
Content-Type: text/plain; charset=utf-8
Content-Length: 25
Connection: keep-alive
Set-Cookie: _la=1556007395
_lt=0
Referrer-Policy: no-referrer
```

</p>
</details>

I have only redacted the following headers: `User-Agent`, `Date`, `Expires` for my privacy

### Other posts online I found regarding these addons:
- https://forum.palemoon.org/viewtopic.php?t=12992
- https://forum.palemoon.org/viewtopic.php?t=19324
- https://discourse.mozilla.org/t/crvtck-com-tracker-in-addons-screengrab-and-s3-google-translator/29095/9
- https://www.reddit.com/r/firefox/comments/9mgfia/why_s3translator_web_extension_was_removed_of_amo/

#### - Menu Wizard
http://www.s3blog.org/s3menu-wizard.html
(Now removed from AMO)
#### - Download Manager (S3)
http://www.s3blog.org/s3download-statusbar.html
https://addons.mozilla.org/en-US/firefox/addon/s3download-statusbar/
71,176 users according to AMO
#### - Screengrab (fix version)
http://www.s3blog.org/screengrab.html
(Now removed from AMO)

#### - S3 Google Translator
Seems to have been removed from AMO etc.

### Other addons by the author
- Forecastfox (fix version)
- Worldwide Radio
- CryptoData
- Multi Web Search
I have checked these addons and could not find the same advertising code

Author of the addons: Oleksandr
Their AMO: https://addons.mozilla.org/en-US/firefox/user/5642089/
Their website: http://www.s3blog.org/

### My versions
- Firefox ESR 52.9.0 (64-bit)
- uBlock Origin 1.16.4.10
- uMatrix 1.0.0

**Comment by smed79** [comment]
Report extensions for abuse
https://support.mozilla.org/en-US/kb/reporting-extensions-and-themes-abuse

**Comment by krystian3w** [comment]
Firefox addon gone, Google no fast remove addon?
