### ISSUE TITLE
all-episodes.tv {antiadblock}

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#5410]
`https://all-episodes.tv/thegameofthrones/season8/series2b`

anti adblock - blocks HD quality @mapx- @dimisa-RUAdList @okiehsch 

only default settings

**Comment by smed79** [comment]
@bogachenko ping users every time you open a problem is not necessary and can be annoying.

**Comment by bogachenko** [comment]
@smed79 ok.

**Comment by mapx-** [comment]
test
```
@@||all-episodes.tv/retlplayer/downretl.js$script,first-party
||boostervideo.ru/client/boostervideo.js$script,redirect=noopjs,domain=all-episodes.tv
```

**Comment by dimisa-RUAdList** [comment]
Until the end of the day I will make the necessary changes.

**Comment by dimisa-RUAdList** [comment]
@mapx- 
This resource has migrated a long time ago ~> `all-episodes.one`. At the same time, all problems are solved in RU AdList.
