### ISSUE TITLE
itv.com

### ISSUE THREAD

**Issue by 241d2** [uBlockOrigin/uAssets#5411]
### URL(s) where the issue occurs

`https://www.itv.com/hub/car-crash-global-caught-on-camera/2a4668a0010`

### Describe the issue

Ads in video player each 15 min. Stops playing ads if you switch a tab (clever though...)

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]
![image](https://user-images.githubusercontent.com/45212341/56607689-6d89d880-6609-11e9-986e-de6809c5bfa0.png)

### Versions

- Browser/version: Version 73.0.3683.103 (Officiel version) (64-bit)
- uBlock Origin version: v1.18.16

### Settings

- Disable Show the number of blocked queries on the icon

**Comment by mapx-** [comment]
All the shows give me
![image](https://user-images.githubusercontent.com/10303732/56609034-74feb100-660c-11e9-9c33-7f73a7278536.png)

**Comment by Scunkaneli** [comment]
Here is an account for anyone who wants to try to remove the ads:

E-Mail: salas@byom.de
Password: salas@byom.de

You need to be in the UK to start the video, so a VPN is required if you are not. (https://i.imgur.com/0hKGaBf.jpg)

**Comment by mapx-** [comment]
I get that message above. So, you could open the logger, select only the `media`  requests and post here the screenshot.

**Comment by Scunkaneli** [comment]
I can confirm ads are playing after around 11min for me.

Full log until after the first few ads finished playing: https://pastebin.com/raw/RvTLLYsk

Only `media`: https://pastebin.com/raw/1Z0wMguL https://i.imgur.com/u1tcW2D.png

**Comment by Scunkaneli** [comment]
Just using `||toots-a.akamaihd.net/priority/*$media,domain=www.itv.com` throws this error: https://i.imgur.com/Mc7NJ7h.jpg Logfile for this case here: https://pastebin.com/raw/WnzzFfZL

**Comment by mapx-** [comment]
what is using
`||toots-a.akamaihd.net/priority/*$media,redirect=noopmp4-1s,domain=itv.com`

**Comment by Scunkaneli** [comment]
`||toots-a.akamaihd.net/priority/*$media,redirect=noopmp4-1s,domain=itv.com` works, no pre-rolls or in-video ads so far. But it shows a blackscreen for around 7 seconds at the place where the in-video ads would normally be.

Does still show the white dots in playing bar and the big blue button "Watch ad-free now" :https://i.imgur.com/7xTIeZz.jpg

**Comment by mapx-** [comment]
Test also
`||toots-a.akamaihd.net/priority/*$media,redirect=noopmp3-0.1s,domain=itv.com`

**Comment by mapx-** [comment]
for `Watch ad-free now` try the element picker to get some filter

**Comment by Scunkaneli** [comment]
Both filters together lead to around 1 second blackscreen

**Comment by mapx-** [comment]
Test only the second filter.

**Comment by Scunkaneli** [comment]
Okay so I use 
```
||toots-a.akamaihd.net/priority/*$media,redirect=noopmp3-0.1s,domain=itv.com
www.itv.com##.stage__upsell-button
www.itv.com##.seek-bar__ad
```
There is no blackscreen, video just resumes. No anti-adblock warning, no ad dots in the bar, no upsell button. Looks very good.

**Comment by Scunkaneli** [comment]
Ok we can't use this filters just yet. When deleting cookies and restarting browser, it gets into a loading cycle when the position of the ads is reached. 

This works best so far, with 1s blackscreen:
```
||toots-a.akamaihd.net/priority/*$media,redirect=noopmp3-0.1s,domain=itv.com
||toots-a.akamaihd.net/priority/*$media,redirect=noopmp4-1s,domain=itv.com
www.itv.com##.stage__upsell-button
www.itv.com##.seek-bar__ad
```

**Comment by Scunkaneli** [comment]
Watching the video with both filters enabled marks the ads as "seen" somehow. When I then disable the mp4 filter and repeat the same video, the ads still count as "seen" and are thus completely skipped with no blackscreen by the video player itself. Logging out and back in resets this "seen" flag of the ads and they are shown again. If I am still only using the mp3 filter there the video breaks, so both filters are needed.
Maybe it is possible to mark the ads as seen with uBlock somehow? The skipping of these seen ads has been the best one yet with no blackscreen or stuttering at all.

**Comment by mapx-** [comment]
thx

**Comment by 241d2** [comment]
Sorry, forgot to say you need account and VPN but many thanks for infomation and filters.
I will try it out tonight :)
