### ISSUE TITLE
news.hiphopearly.com Revcontent

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#542]
### URL(s) where the issue occurs

`http://news.hiphopearly.com/future-speaks-drakes-big-night-billboard-awards/`

### Describe the issue

Trending today. Sponsored.
Provided by Revcontent

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/28332688-aab3d20c-6bc3-11e7-90b8-1ced0e7e500a.png)

### Versions

- Browser/version: Chrome 59
- uBlock Origin version: 1.13.2

### Settings

Default

**Comment by mapx-** [comment]
try
`hiphopearly.com##script:inject(nowebrtc.js)`

**Comment by terrorist96** [comment]
Thanks!

**Comment by mapx-** [comment]
or
`||hiphopearly.com^$csp=script-src 'self' * 'unsafe-inline' data:`

**Comment by terrorist96** [comment]
Both work
