### ISSUE TITLE
ondemandkorea.com [Anti-Adblock]

### ISSUE THREAD

**Issue by ublockmatters** [uBlockOrigin/uAssets#5421]
### URL(s) where the issue occurs

`https://www.ondemandkorea.com/kbs-news-9-e20190423.html`

(all videos on site)

### Describe the issue

Anti-Adblock issue, video does not play, "are you using adblock" banner lights up on player

### Screenshot(s)

![Screen Shot 2019-04-23 at 6 38 50 PM](https://user-images.githubusercontent.com/49928924/56626595-272b7e00-65f7-11e9-9722-f8197c5220c6.png)

### Versions

- Browser/version: Chrome 73.0.3683.103 / Firefox 66.0.2
- uBlock Origin version: 1.18.16

### Settings

- n/a

### Notes

Tried adding these filters found online, does not work

@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=ondemandkorea.com
@@*$xhr,domain=ondemandkorea.com
ondemandkorea.com##.floatBanner
@@||googletagservices.com^$script,domain=ondemandkorea.com
@@||ondemandkorea.com/vendor/prebid/$script,1p
*/*$script,domain=ondemandkorea.com,redirect=noopjs,third-party
@@||cdnjs.cloudflare.com^$script,domain=ondemandkorea.com
@@||code.jquery.com^$script,domain=ondemandkorea.com
@@||bootstrapcdn.com^$script,domain=ondemandkorea.com
@@||amazon-adsystem.com^$script,domain=ondemandkorea.com
@@*$script,domain=ondemandkorea.com,3p

**Comment by mapx-** [comment]
remove those filters, add only
`@@*$script,domain=ondemandkorea.com,3p`

**Comment by KiLL4FuNK** [comment]
It works perfect

`@@*$script,domain=ondemandkorea.com,3p`

**Comment by ublockmatters** [comment]
Hmm, still not working for me. 
It's just that one line that I'm supposed to use, right?

**Comment by mapx-** [comment]
Yes. Be sure you have no other blocking extension enabled (or router with blocking rules, DNS - blocking settings, pi-hole etc)

**Comment by Scunkaneli** [comment]
Not working here :/

https://i.imgur.com/4YCdD7c.png
https://i.imgur.com/4oNtpgn.png

**Comment by mapx-** [comment]
@Scunkaneli  Reset uBo to the default settings (you disabled default lists), purge all caches and click "update now", then test again.

**Comment by Scunkaneli** [comment]
I did:
1. Reset uBo to Default in uBo settings
2. Clear caches
3. Delete all chrome browser data + restart
4. Copy `@@*$script,domain=ondemandkorea.com,3p` into "My filters"

I still get the same message. I do not own a pi-hole or other dns blocking tools.

Settings after restoring to default: https://i.imgur.com/uUGGlpW.png
These filters were automatically selected after restoring to default: https://i.imgur.com/0aIOmp2.png
My filters: https://i.imgur.com/NnQyjyN.png
Log: https://pastebin.com/w4eDaHtd

**Comment by mapx-** [comment]
add also
`@@*$image,domain=ondemandkorea.com,1p`

**Comment by Scunkaneli** [comment]
Not really better, just the image right next to the player is new
https://i.imgur.com/BwUoJfI.jpg

**Comment by mapx-** [comment]
It's working for me, tested on free clips.

**Comment by mapx-** [comment]
and that image is self-promo

**Comment by Scunkaneli** [comment]
Well seems to be an issue on my end then. Even disabling uBo completely does not work.

**Comment by mapx-** [comment]
Try other browser, or close / reopen the current one

**Comment by Scunkaneli** [comment]
Happens with Chrome (no other add-ons, after clearing browser-data) and Firefox, both with and without uBlock and also after restarting. 
It seems that this is not caused by uBlock, but something else.

**Comment by KiLL4FuNK** [comment]
Do you use any antivirus with advertising blocking?

**Comment by Scunkaneli** [comment]
Nope, it is very weird. Only explanation I can think of is that the VPN
I used (site was georestricted to america) does some undocumented
advertisement blocking...

**Comment by KiLL4FuNK** [comment]
ADS

`https://www.ondemandkorea.com/left-handed-wife-e103.html`
