### ISSUE TITLE
Cookie notice on www.oe24.at

### ISSUE THREAD

**Issue by practik** [uBlockOrigin/uAssets#5422]
### URL(s) where the issue occurs

`https://www.oe24.at/`

### Describe the issue

Giant cookie notice blocks/ blurs entire site.

### Screenshot(s)

![55687648-997c3d00-592c-11e9-8772-5f0f13630cf6](https://user-images.githubusercontent.com/12074235/56661937-0ea37e00-6660-11e9-80e6-46fe16895b5c.png)

### Versions

- Browser/version: Firefox 66
- uBlock Origin version: 1.18.16

### Settings

- advanced user features enabled
- prevent WebRTC leakage

### Notes

Fixes courtesy of @krystian3w at https://github.com/ryanbr/fanboy-adblock/issues/989#issuecomment-480616739:

`www.oe24.at##.cookiesOverlay2Box`
`www.oe24.at##.wrapper.blured:style(filter: none !important;)`

**Comment by krystian3w** [comment]
We can try report to AdGuard annoyance - maybe add css not cookie accept scriplet (this no works for uBO).

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/0b52cb671955d4dfdc2db6919f173eaef32f6007 - also in AdGuard.
