### ISSUE TITLE
pornhub.com (nsfw)

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#5429]
### Describe the issue

[I'm not sure but it seems one or more uBO filters are breaking videos on PH. Whenever you try watching a video sometimes you're presented with "Video is not available at the moment". I know it's coming from uBO main filter list because if I disable it the error message goes away completely.]

### Versions

- Browser/version: [Chrome latest build]
- uBlock Origin version: [1.18.16]

### Settings

- [default]

### Notes

[I can't be sure if anyone else can reproduce this but the message only appears when enabling main uBo filter list. Might require opening several videos and seeing which one breaks because it doesn't always happen.]

**Comment by dumbusernameidk** [comment]
seems this is the problem `https://gyazo.com/bf0319d4bf60a21904fa80767abcc1e3`

**Comment by okiehsch** [comment]
Do you have a link to a specific video?
All the ones I tried work fine on my end.

**Comment by dumbusernameidk** [comment]
It happens on any video. It's not really tied to a specific one. If I had this to my filter list `pornhub.com#@#+js(csp.js, img-src 'self' *; media-src 'self' *)` the error goes away. So maybe this is causing videos to be blocked or something?

**Comment by okiehsch** [comment]
Well, I can see that csp filter and I sometimes get a "Video is not available at the moment" message, but the video always plays fine if I simply reload the page.
Could be a site issue.

**Comment by dumbusernameidk** [comment]
I'm not sure if I add the exception the error doesn't display. But it could very well be a site problem because that filter is pretty old and it hasn't done anything like this before. Maybe see if anyone else gets the error with/without the filter.

**Comment by okiehsch** [comment]
Agreed, let's wait and see if others can reproduce and if the issue persists.

**Comment by uBlock-user** [comment]
That CSP cosmetic filter should be removed anyways, since we already have a `$csp` directive in place.

**Comment by mapx-** [comment]
I can reproduce the issue in chrome (FF is ok) every time I purged the cookies.
I'll remove the csp filter, does not seem to help anymore.
