### ISSUE TITLE
opencarry.org unblocked ads/anti-adblock

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#543]
### URL(s) where the issue occurs

`http://www.opencarry.org/`
`http://vb.opencarry.org/forums/forum.php`

### Describe the issue

Holster ads at top of each page.

`||www.opencarry.org/wp-content/uploads/2017/03/AGH_banner_468x103.gif`
`||www.opencarry.org/wp-content/uploads/2017/06/CB_SuperTuckHH_468x165.jpg`

**Comment by mapx-** [comment]
there is antiadblocking too:

add
```
||opencarry.org/*banner$image
opencarry.org##[id^=ad_global]
@@||opencarry.org^$generichide
```

**Comment by SMed79** [comment]
add
`||opencarry.org/wp-content/uploads/*_468x`

PS: _Report this kind of classic ad banners on easylist forum...._

**Comment by terrorist96** [comment]
> PS: Report this kind of classic ad banners on easylist forum....

I would if any of the maintainers would go through the issues on a regular basis. Prefer not to listen to my own echo over there.
What if we set up a rule? I report simple stuff like this on the EasyList issue page. If it's not fixed/merged by an easylist author, then I come and post it here. How is that?

**Comment by okiehsch** [comment]
I am pretty sure they are not ingnoring you on purpose and I do not know why you seem to think
that filter list maintainers are under some kind of obligation to resolve issues in a timely manner.

I will add the proposed ant-adblock fix for this site later today and I will include the filters for the banner-ads, because I think if I add a fix for a site I should add all ad-related filters.

**Comment by terrorist96** [comment]
The reason I think that is because they banned me on the lanik forums (where they happen to be more active) because I was posting too much lol. I know they have no obligation to do anything and that they are unpaid volunteers. But any suggestions I've offered, like allowing more people to have merge permissions if the current maintainers are too overwhelmed, have been shut down.
And this is why I'm thankful for you guys here for being so responsive and active. This place is my refuge. :smiley:

**Comment by SMed79** [comment]
> The reason I think that is because they banned me on the lanik forums 

That wrong ==> [viewprofile&u=4047](https://forums.lanik.us/memberlist.php?mode=viewprofile&u=4047) I do not remember unless you have banned your self.

**Comment by terrorist96** [comment]
![image](https://user-images.githubusercontent.com/12802056/28340390-9374693e-6bdd-11e7-8dfd-58a46be9e8d3.png)

Go ask Lanik.

**Comment by SMed79** [comment]
Sorry, but i am sure it is because of your behavior that you did not want to improve not your "much posting".

**Comment by LanikSJ** [comment]
> The reason I think that is because they banned me on the lanik forums (where they happen to be more active) because I was posting too much lol.
You were never banned, your posts are set to be moderated each time, because of your refusal to follow the rules.  I just tested your account and I can see every forum no problem.

**Comment by terrorist96** [comment]
Kinda hard to post when I can't even see any forums.
But it's fixed now.
