### ISSUE TITLE
razerflixs.com

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#5431]
### URL(s) where the issue occurs

`[https://razerflixs.com/JSzmz]`

### Describe the issue

[It force to disable adblocker addon]

### Screenshot(s)

[https://imgur.com/M3TvDse]

### Versions

- Browser/version: [Firefox Quantum 66.0.3 x86]
- uBlock Origin version: [1.18.16]

### Settings

- [https://pastebin.com/Setx9vUc]

### Notes

[If i turn off uBO it works]

**Comment by JobcenterTycoon** [comment]
`razerflixs.com##+js(addEventListener-defuser.js, load, onload)` works for me
