### ISSUE TITLE
xenforo.pk

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#5432]
### URL(s) where the issue occurs

`https://xenforo.pk/`

### Describe the issue

Anti-Adblock Script - BlockAdBlock, Bait Scripts

### Screenshot(s)

![Screenshot_2019-04-25 XenForo pk - Everything Free ](https://user-images.githubusercontent.com/24980766/56739534-df167380-673c-11e9-993d-347fee14b412.png)

### Versions

- Browser/version: Firefox 66.0.3
- uBlock Origin version: 1.18.16

### Settings

- All Filters Enabled + I don't care about cookies. Regional filters, uBlock Filters Experimental, and Anti-Facebook List disabled.

### Notes

BlockAdBlock code found inline. The message shown above is what happens when you also block the bait scripts `ads.min.js` and `advertising.js`. No way to dismiss them.

**Comment by JobcenterTycoon** [comment]
The filters
`xenforo.pk##+js(bab-defuser.js)`
`xenforo.pk##+js(abort-on-property-read.js, adblock)`
works for me
