### ISSUE TITLE
multiup.org

### ISSUE THREAD

**Issue by vdias** [uBlockOrigin/uAssets#5435]
### `https://multiup.org`

Examples:
```
https://multiup.org/3d6e5076aedfcb5af554f3e1df7f9ea4
https://multiup.org/285c879fbe0aa972db51e6964dacbff1
```

### Describe the issue
Multiple popups open on mouse click
JSEcoin coin miner banners

### Screenshot(s)
![2019-04-25 17_12_54-cpafiles01 - cpafiles01 - Remote Desktop Connection](https://user-images.githubusercontent.com/2320553/56747177-c9756e00-677d-11e9-88bb-fc41d50862d2.png)

### Versions
Firefox 66.0.3
uBlock Origin 1.18.16

### Settings
Default Settings

**Comment by mapx-** [comment]
No popups or jsecoin for me. Try updating all your lists (purge + update)

**Comment by vdias** [comment]
what list are you using...?

**Comment by mapx-** [comment]
@vdias  You have to tell us all the lists you are using (see what lists are enabled and if are updated)

**Comment by vdias** [comment]
My filters​​​​​0 used out of 0​​​​ 
uBlock filters​ ​​​​15,977 used out of 16,092​​
​​uBlock filters – Badware risks​ ​​​​119 used out of 119​​
​​uBlock filters – Privacy​​​​​ 156 used out of 158​​
​​uBlock filters – Resource abuse​​​​​ 110 used out of 110​​
​​uBlock filters – Unbreak​​​​​ 901 used out of 903​​
spa, por: AdGuard Spanish/Portuguese​​​​​ 2,753 used out of 2,826​​​​
​​

**Comment by mapx-** [comment]
Close firefox, open it again, reset to default settings (you have no easylist, easyprivacy, Peter Lowe's ), then click purge all caches, click update.

**Comment by ghajini** [comment]
`https://multiup.org/en/mirror/7ab5bfcde2419d3a4977c8c7c1cb53c3/J_M_IMS__2019__www.Jalshamoviez.Uk_720p_HDRip_x264_AAC_ESubs.mkv`
STR=
1. click on download in 1st page
2.issue is that when you open one of the file host in new tab  through rightclick on `download` button 
ads are loaded instead of target link
3.if you click download buttom in current tab ,new tab is opened for target link while original tab is laded with vpn ads,1fichier ads etc

**Comment by llacb47** [comment]
Destination link is hardcoded in DOM. Maybe a scriplet would work.
```
<a href="/redirect-to-host/ulozto.net/7ab5bfcde2419d3a4977c8c7c1cb53c3/3" onclick="location.href='/redirect-to-host/ulozto.net/7ab5bfcde2419d3a4977c8c7c1cb53c3' ; return true" ontouchend="this.onclick=false;location.href='/redirect-to-host/ulozto.net/7ab5bfcde2419d3a4977c8c7c1cb53c3'; if(navigator.userAgent.match(/ucbrowser/i)){window.open('/redirect-to-host/ulozto.net/7ab5bfcde2419d3a4977c8c7c1cb53c3/3', '_blank') ; return false;} ; return true;" onauxclick="return false;" namehost="ulozto.net" link="https://ulozto.net/!O1ej7zi3ecQe" validity="valid" datelastchecked="7/21/19, 8:09 AM" id="107778895" target="_blank" rel="noopener" class="host btn btn-md btn-default btn-block btn-3d hvr-bounce-to-right">
<i class="fa fa-fw fa-download"></i>
Download (3)
</a>
```

**Comment by llacb47** [comment]
@mapx- Issue needs to be reopened

**Comment by krystian3w** [comment]
bad attrib should remove:

```
multiup.org##+js(ra, onclick|ontouchend|target, .host)
```

change link to href only possible in AdGuard (uBO no have scriplet).

**Comment by uBlock-user** [comment]
> Destination link is hardcoded in DOM link attribute of a tag.


Not hardcoded, otherwise I wouldn't be able to change it at all.

https://github.com/uBlock-user/uBO-Personal-Filters/issues/7#issuecomment-505993687

I managed to change the destination link for one server -- upto, but doing it for all others is troublesome and fruitless.

**Comment by uBlock-user** [comment]
@llacb47 good idea, it works. 

Here's the scriptlet if anyone wants to use it --

```
linkfilterer.js application/javascript
(() => {
		let linkfilter = () => {
			let hosts = document.getElementsByClassName('host');
			for (let host of hosts) {
				 host.setAttribute('href', host.getAttribute('link'));
                                 host.removeAttribute('onclick');
                                 host.removeAttribute('ontouchend');
                                 host.removeAttribute('target');
			 }	 
		};
		if (document.readyState === 'interactive' || document.readyState === 'complete') {
			linkfilter();
		} else {
			addEventListener('DOMContentLoaded', linkfilter);
		}
})();
```

**Comment by ghajini** [comment]
Userscript version of that scriptlet @uBlock-user 
Because gorhill is not going to add single scriptlet for single site

**Comment by krystian3w** [comment]
This is dangerous if unlock for all sites.

**Comment by uBlock-user** [comment]
@ghajini 

```
// ==UserScript==
// @name Multi-up-defuser
// @namespace Multi-up-defuser User-Script
// @match *://multiup.*/*
// @grant none
// ==/UserScript==

(() => {
            'use strict';
            let linkfilter = () => {
			let hosts = document.getElementsByClassName('host');
			for (let host of hosts) {
				 host.setAttribute('href', host.getAttribute('link'));
                 host.removeAttribute('onclick');
                 host.removeAttribute('ontouchend');
                 host.removeAttribute('target');
			 }	 
		};
		if (document.readyState === 'interactive' || document.readyState === 'complete') {
                linkfilter();
		} else {
                addEventListener('DOMContentLoaded', linkfilter);
		}
})();
```

**Comment by ghajini** [comment]
Anyone can reproduce,I don't know why its not fixing.....😫
1. Go to `https://multiup.org/en/mirror/7ab5bfcde2419d3a4977c8c7c1cb53c3/J_M_IMS__2019__www.Jalshamoviez.Uk_720p_HDRip_x264_AAC_ESubs.mkv`
2. Click `download` on filehosts like filerio/uptobox ,you will get destination link in new tab and original tab is loaded with ads(multinews etc )
Or
Right click download to open link in new tab and you will get ads instead of destination link....

**Comment by krystian3w** [comment]
first suppose have other attrib as "`link="..."`".

**Comment by uBlock-user** [comment]
@ghajini I tested in ViolentMonkey and it works as expected there.

**Comment by ghajini** [comment]
Thanks @uBlock-user

**Comment by uBlock-user** [comment]
@ghajini You don't need VM for this, just copy paste this javascript into a text file and name it somename.txt, add the RAW version of that txt in advanced settings at `userResourcesLocation` That parameter supports multiple files, so there's no issue if you have more than one.

**Comment by krystian3w** [comment]
Or convert to bookmarklet scriplet.

**Comment by ghajini** [comment]
`https://multiup.org/download/776832992837d723d4a3937fa587c126/aladnd.br18_300mbfilms.com.mkv.003`
Something changed,
Clicking on `download` leads to ads

**Comment by uBlock-user** [comment]
They saw the scriptlet and filters I posted and fired back. Using those filters will block the page from opening the page you want to go to which is -- 

`https://multiup.org/en/mirror/7ab5bfcde2419d3a4977c8c7c1cb53c3/J_M_IMS__2019__www.Jalshamoviez.Uk_720p_HDRip_x264_AAC_ESubs.mkv`

**Comment by uBlock-user** [comment]
Nevermind, adding `multiup.org##+js(window.open-defuser)` fixes it for me.

**Comment by ghajini** [comment]
No it doesn't work for me....
Same bad attribs
Clicking on `download` leads to ads in current tab(`multinews.me`) while it opens file mirrors in new tab

**Comment by uBlock-user** [comment]
Someone will have test it in Firefox Android as I don't see use that.

**Comment by ghajini** [comment]
Firefox desktop/opera browser also doesn't work, may be need update to `linkfilterer.js` to work on this url 
`https://multiup.org/download/776832992837d723d4a3937fa587c126/aladnd.br18_300mbfilms.com.mkv.003`

I know it works on 
`https://multiup.org/en/mirror/776832992837d723d4a3937fa587c126/aladnd.br18_300mbfilms.com.mkv.003`

**Comment by uBlock-user** [comment]
I'm seeing different set of behaviours when trying to reproduce, once it gets stuck on `Please Wait....` then it didn't, so can't tell what's going on. There's not to fix in the scriptlet, it does what's it supposed to do.

**Comment by ghajini** [comment]
Okay here is video captured of whole problem
`streamable.com/4v216`

**Comment by uBlock-user** [comment]
You need to add `multiup.org##+js(window.open-defuser)` for popups which was mentioned in https://github.com/uBlockOrigin/uAssets/issues/5435#issuecomment-524610841

**Comment by ghajini** [comment]
Yeah added 
`multiup.org##+js(window.open-defuser)`
Doesn't work

**Comment by uBlock-user** [comment]
Use the modified version of the scriptlet I made -- https://github.com/uBlock-user/uBO-Scriptlets/blob/master/scriptlets.txt#L69

Filters

```
multiup.org##+js(ra, onsubmit|onclick|ontouchend)
multiup.org##+js(window.open-defuser)
multiup.org##+js(hyperlink-setter)
```
That does it for me on Firefox 70 desktop, new tab will open but for the download links only.

**Comment by ghajini** [comment]
No it won't work....sorry to say that...
Opera browser stable /Firefox desktop stable version/firefox android stable
`https://streamable.com/9o90y`

**Comment by uBlock-user** [comment]
> No it won't work....sorry to say that...

Works for me. Disable all extensions except uBO and the VPN extension you use. Some webfiltering extension seems to be interfering on your end.

**Comment by ghajini** [comment]
Yeah webfiltering extension(webroot) won't interfere, that's for website safety ratings.....
I will check with that extension disabled.....

Also 2nd thing, it doesn't work on firefox android also which has no such extension. ...

**Comment by gwarser** [comment]
I get popunders when using VPN extension.

**Comment by ghajini** [comment]
Iam using vpn because that site `multiup.org` is blocked on my isp....
Did you get ads like in 
`streamable.com/4v216`

**Comment by gwarser** [comment]
Correction - I get it only once after switching country.

**Comment by ghajini** [comment]
STR=
1. Go here 
`https://multiup.org/download/776832992837d723d4a3937fa587c126/aladnd.br18_300mbfilms.com.mkv.003`
2. In that page(`https://multiup.org/download/776832992837d723d4a3937fa587c126/aladnd.br18_300mbfilms.com.mkv.003`) you see `download` button ,clicking on that leads to ads (random ads)in current page and real mirror sites in new tab.....

**Comment by krystian3w** [comment]
```
<form 
action="/en/mirror/776832992837d723d4a3937fa587c126/aladnd.br18_300mbfilms.com.mkv.003"
method="post"
target="2037349134"
onsubmit="window.open('','2037349134','')">
````

So replace something: `onsubmit="window.open('','2037349134','')">`? 
Maybe AdGuard dynamic change `window.open` to "current.tab" - uBO no support scriplet for this...

**Comment by ghajini** [comment]
On this file not found page I get redirects if I click anywhere
`https://multiup.org/download/da841635216f5d3365dd7315a3ca03d0/`

**Comment by krystian3w** [comment]
Made with inline script e.g. `window.location` or meta tag:

```html
<meta id="link" http-equiv="refresh" content="1;url=/en/mirror/NOT_FOUND/LINK?t=0">
```

```
multiup.org##^meta[http-equiv="refresh"]
```

uBO can block meta tag with only html filtering, so on Chromium no possible remove?

**Comment by ghajini** [comment]
@mapx-, can you add

`||multinews.me^$all`
`||multinews.me^`

Until more definitive filters are found, you can call it `partially address/partial fix`

**Comment by krystian3w** [comment]
@ghajini 

`||multinews.me^$all` - uBO 1.20.0+

`||multinews.me^` - uBO 1.19.X and uBO legacy

**Comment by ghajini** [comment]
Yes iam on stable updated browsers/ublock origin

**Comment by ghajini** [comment]
Hello @okiehsch
1. Issue is no more with valid url's `https://multiup.org/download/776832992837d723d4a3937fa587c126/aladnd.br18_300mbfilms.com.mkv.003` with default Ublock origin settings

2. Issue is there with `file not found` pages
`https://multiup.org/download/da841635216f5d3365dd7315a3ca03d0/`
For this 
`||multinews.me^$all`
`||multinews.me` is enough .....

**Comment by ghajini** [comment]
that annoyance is back 

`https://multiup.org/en/mirror/585006cb98bae35de38df56d1fdd69b3/ExtraMovies.wiki_TABM219DAHC72HCHRFD.mkv`

clicking `download` under respective file servers doesn't lead to file server website....

also custom fix at https://github.com/uBlockOrigin/uAssets/issues/5435#issuecomment-515761024 doesn't work
@uBlock-user

**Comment by uBlock-user** [comment]
I can kill the popup with `multiup.org##+js(ra, action, form)` Regarding

> clicking download under respective file servers/mirror links doesn't lead to file server website....

Because they removed the <a href...> with <button> instead.

**Comment by uBlock-user** [comment]
Can't reproduce it anymore, they're watching this thread I think, they, changed `action` attribute to the link instead of a popup.

**Comment by ghajini** [comment]
Yes they seen us.....may be they will come with something nefarious😌

**Comment by uBlock-user** [comment]
Nevertheless, I updated my [scriptlet](https://github.com/uBlock-user/uBO-Scriptlets/blob/master/scriptlets.txt#L133)

**Comment by ghajini** [comment]
They changed something again

`https://multiup.org/en/mirror/c21c9313c591c0a6f0fb04a1e4dfb59d/ExtraMovies.wiki_WND19DAH72HRESD.mkv`

Clicking `download `button under various file mirrors leads to blocked ubo dialougue of `multinews.me` and never leads to real link
@uBlock-user

**Comment by uBlock-user** [comment]
You can disable the popup with filter posted in https://github.com/uBlockOrigin/uAssets/issues/5435#issuecomment-543750286

**Comment by ghajini** [comment]
URL =
`https://multiup.org/en/mirror/e48f4eb2ff37222ef0adfe9ac2e2cf48/ExtraMovies.wiki_LK19FMH48PDRFD.mkv`

1.
@mapx- this is what happened with ubo default settings,  I don't get file for download but ads only

`https://i.imgur.com/W7hgVWd.gifv`

2.
@uBlock-user with your settings ,I don't file but only current page is reloaded again n again, hope you help me with working fix

`i.imgur.com/64WgtXI.gifv`

**Comment by mapx-** [comment]
I see no different behaviour with uBo disabled, how does work this site ?

**Comment by ghajini** [comment]
1.
Ubo disabled I get target download site eg 1fichier.com or uptobox.com etc

`i.imgur.com/YTX2JPP.gifv`

2.
With ubo enabled iam stuck at multinews.me blocked dialogue and never proceeded to target site even if I allow temporarily blocked dialogue

**Comment by uBlock-user** [comment]
> ,I don't file but only current page is reloaded again n again, hope you help me with working fix

Removing the "action" attribute  will do that which is what the filter does to stop browsing to the blocked site. Unfortunately the new scriptlet I made doesn't work as expected. What you can do open dev tools and look for the link attribute to find the download link you want to go to and go there that way untill a solution is found.

**Comment by ghajini** [comment]
Is this correct userscript format @uBlock-user 
```
// ==UserScript==
// @name Multi-up-defuser
// @namespace Multi-up-defuser User-Script
// @match *://multiup.*/*
// @grant none
// ==/UserScript==
document.querySelectorAll("form>button[link]").forEach(b => {
  b.addEventListener("click", ev => {
    ev.preventDefault();
    location.href = b.getAttribute("link");
  }, true);
});

**Comment by uBlock-user** [comment]
@ghajini Aren't you using the scriptlet I made ? or is not working anymore ?

**Comment by krystian3w** [comment]
IMO fake:

![obraz](https://user-images.githubusercontent.com/35370833/78805327-91346300-79c1-11ea-92b7-89f6479786a2.png)

So should hidden?

**Comment by ghajini** [comment]
> @ghajini Aren't you using the scriptlet I made ? or is not working anymore ?

A lot of difficulties described over here
`https://github.com/uBlock-user/uBO-Scriptlets/issues/6`

**Comment by uBlock-user** [comment]
> A lot of difficulties described over here

None of them are caused by the scriptlet which I already addressed there and is based on what AdGuard's raw snippet, anyways your choice.

**Comment by ghajini** [comment]
Is that correct format (its working for me)?
codewise

**Comment by krystian3w** [comment]
Fake button maybe again visible - https://github.com/uBlockOrigin/uAssets/issues/5435#issuecomment-611038987 due change "Usenet" to "UseNet":

```diff
-multiup.org##.panel-body > .row > .col-md-4:has(:scope > .panel > .panel-footer > a[href^="/download-fast/"][namehost="Usenet"])
+multiup.*##a[href^="/download-fast/"][namehost="Usenet" i]:upward(.col-md-4)
```

or

```diff
+multiup.*##.panel-body > .row > .col-md-4:has(:scope > .panel > .panel-footer > a[href^="/download-fast/"][namehost="Usenet" i])
```
```diff
+multiup.*##.panel-body > .row > .col-md-4:has(:scope > .panel > .panel-footer > a[href^="/download-fast/"][namehost="UseNet"])
```
