### ISSUE TITLE
rushtime.in

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#5436]
### URL(s) where the issue occurs

`https://www.rushtime.in/download/windows-server-2012-download-free/`

### Describe the issue

Anti-Adblock Script - Admiral

### Versions

- Browser/version: Firefox 66.0.3
- uBlock Origin version: 1.18.16

### Settings

- All Filters Enabled + I don't care about cookies. Regional filters, uBlock Filters Experimental, and Anti-Facebook List disabled.

**Comment by JobcenterTycoon** [comment]
The filter 
`@@||rushtime.in^$generichide`
`rushtime.in##.adsbygoogle`
works for me
