### ISSUE TITLE
Joe.ie - Unable to scroll down on any page

### ISSUE THREAD

**Issue by germaloney11** [uBlockOrigin/uAssets#5437]
### `https://www.joe.ie`

`https://www.joe.ie/life-style/greta-thunberg-666667?fbclid=IwAR2_6cDu7Kfzat2LLLqu8GwRF2_U6htfEdje4rCplEYtWUleosSr0bh2Az4`

### Describe the issue

Unable to scroll down. Zapping the header seems to fix it.

### Versions

- Browser/version: Google Chrome - Version 74.0.3729.108 (Official Build) (64-bit)

- uBlock Origin version: 1.18.16

**Comment by germaloney11** [comment]
Still experiencing this issue

**Comment by mapx-** [comment]
I guess you are using fanboy's cookies list

add
```
@@||static.quantcast.mgr.consensu.org/$script,domain=joe.ie
joe.ie#@#.cookiePolicy
joe.ie#@#.qc-cmp-ui-container
```

@ryanbr

**Comment by germaloney11** [comment]
Yes I'm using the fb cookies list. Unfortunately above filters didn't fix it

**Comment by okiehsch** [comment]
Add also
`@@||vendorlist.consensu.org^$xmlhttprequest,domain=joe.ie`

**Comment by germaloney11** [comment]
Seems to be happening again

**Comment by germaloney11** [comment]
This issue is still happening. It seem's to be an issue with fanboy's cookies list filter. Is there a specific place to report this filter issue or is here ok?

**Comment by mapx-** [comment]
@ryanbr
