### ISSUE TITLE
filerio.in

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5438]
### URL(s) where the issue occurs

`https://filerio.in/lih0jbx5i51g`

### Describe the issue

Popup ads

### Versions

- Browser/version: firefox android latest stable
- uBlock Origin version: 1.18.16

### Settings

- uBO's default settings

**Comment by JobcenterTycoon** [comment]
The filter `filerio.in##+js(abort-current-inline-script.js, RegExp, zfgloaded)` works for me.

**Comment by ghajini** [comment]
`zfgloadedpopup,zfgloadedpushopt,atob,decodeURIComponent`,
If they change

**Comment by ghajini** [comment]
![IMG_20190809_002855](https://user-images.githubusercontent.com/20338483/62730016-ad38cc80-ba0e-11e9-8679-7ae14ddc779c.jpg)

Ads
`||dgw7ae5vrovs7.cloudfront.net^`

**Comment by mapx-** [comment]
provide example link

**Comment by ghajini** [comment]
oops sorry
`https://filerio.in/zribj7guck6e`

**Comment by ghajini** [comment]
`https://filerio.in/jmemrdab8kk7`
Filter=
@ryanbr 
`||baysexthy.com^`

**Comment by ghajini** [comment]
`https://filerio.in/dv38c8xix18q`

on clicking `download now`
`https://user-images.githubusercontent.com/20338483/159419429-9c161177-5540-4346-844b-e8bab987242c.png`

results in ads opened in new tab

**Comment by ghajini** [comment]
These are not required
```
||filerio.in/banners/*$image,1p
||i.ibb.co^$image,domain=filerio.in
||filerio.in/sw.js$script,1p
*$xhr,domain=filerio.in,3p
@@||filerio.in^$ghide
```
