### ISSUE TITLE
ckk.ai [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5439]
URL(s) where the issue occurs

`https://ckk.ai/mgAQO`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 73 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.18.16

Settings

Default

**Comment by dumbusernameidk** [comment]
second page popup & bunch of garbage xhr requests.

**Comment by KiLL4FuNK** [comment]
ADS

**Comment by ghajini** [comment]
Crap xhr's loading after captcha solving in next page.....'
`ckk.ai/YYQyOxa`

**Comment by ghajini** [comment]
`https://ckk.ai/7CWp`
3rd party garbage /tracking

`||ckk.ai/sw$first-party`

`||d2glav2919q4cw.cloudfront.net^$important`

**Comment by KiLL4FuNK** [comment]
popup ADS

**Comment by ghajini** [comment]
`https://ckk.ai/7CWp`

Popup ads in last page

May be add 

`||35.224.227.218^$important`

Quite common among URL shorteners

**Comment by mapx-** [comment]
still no luck, getting no popup, try a similar filter like ouo.io

**Comment by mapx-** [comment]
try
`ckk.ai##+js(nowebrtc)`

**Comment by ghajini** [comment]
`ckk.ai##+js(nowebrtc)`

Works on my end....

**Comment by dumbusernameidk** [comment]
Unwanted 3p frames + xhr requests on second page. I tried doing a csp filter and maybe this is too broad but it does work. Alternatively I did `ckk.ai##+js(acis, Math, atob)` maybe not the right filter (sorry not good with JS) but it does prevent the unwanted 3p trash.

This link still works `https://ckk.ai/7CWp`.

**Comment by okiehsch** [comment]
> Alternatively I did `ckk.ai##+js(acis, Math, atob)` maybe not the right filter

That is actually a perfectly fine filter to fix this issue. 👍 
The script causing those 3p frames + xhr requests is used on hundreds of sites and we use
`example.com##+js(acis, Math, zfgloaded)`
to fix all those cases but your filter would also work.

**Comment by ghajini** [comment]
`https://ckk.ai/aZCT4Pq`
3rd parties ,(privacy) in last page

**Comment by ghajini** [comment]
`https://ckk.ai/ent2ccC6`
DOmain now redirects to `https://tii.ai/ent2ccC6`...
ckk.ai is dead domain....

**Comment by mapx-** [comment]
it's not dead => `This domain is owned by hrnan!!` , so will be used again, `tii.ai` was fixed

**Comment by ghajini** [comment]
Okay thanks for clarifying, but filters related to `ckk.ai` will not apply and hence become obsolete,right?

**Comment by mapx-** [comment]
It will be used again ;)
