### ISSUE TITLE
anti adblock - onlineserieshd.com

### ISSUE THREAD

**Issue by pizza90** [uBlockOrigin/uAssets#5441]
### URL(s) where the issue occurs

`https://onlineserieshd.com/episodes/juego-de-tronos-8x2/`

### Describe the issue

Anti AdBlock

### Versions

- Browser/version: [Chrome / 73.0.3683.103]
- uBlock Origin version: [v1.18.16]

### Settings

- [Default]

**Comment by lain566** [comment]
The player is broken.
`https://onlineserieshd.com/episodes/shingeki-no-kyojin-1x1/`
