### ISSUE TITLE
porntube.com (NSFW)

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#545]
`https://www.porntube.com/`

Unblocked ad on right and bottom of page.

`https://www.porntube.com/videos/tiny4k-pink-pussy-rachel-james-fucked-facial_7263735`

Two unblocked ads on the right, one below the video, and three at the bottom.

**Comment by gorhill** [comment]
How about `porntube.com##.la-vane-frame`?

**Comment by okiehsch** [comment]
`||porntube.com/faloo.js` also prevents the popunder from being triggered.

**Comment by okiehsch** [comment]
What about
````
||porntube.com/faloo.js
porntube.com##.cpp:has(a[href*="porntube.com/channel-redirect/"])
````

**Comment by terrorist96** [comment]
Yes, that works. Thanks!

**Comment by terrorist96** [comment]
@okiehsch Thanks! Just noticed that the `PornTube Friends` listed at the bottom also have similar ads. Notably:
`https://www.fux.com/`
`https://www.fux.com/video/532679/pinup-sex-intense-sex-fabulous-hungarian-babe`

`https://www.pornerbros.com/`
`https://www.pornerbros.com/videos/Female-Fake-Taxi-Belgium-porn-stud-fucks-hot-driver_818746`

`https://www.4tube.com/`
`https://www.4tube.com/videos/443550/kinky-pussy-fucking-foursome-hung-stepbro`

**Comment by terrorist96** [comment]
@okiehsch in case you missed this ^
