### ISSUE TITLE
uploadbuzz.org

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5469]
### URL(s) where the issue occurs
`https://uploadbuzz.org/wfuh8wspnedo`

### Describe the issue
popup ads
fake download buttons

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.18.16

### Settings

-  uBO's default settings

### Notes

pls make generic filter for `ghoto-12.win` ,present on many sites as a fake download button

**Comment by mapx-** [comment]
click, captcha, then landing in this page: `https://www.parhlo.xyz/free-download/` but no way to get the download file ?!

**Comment by ghajini** [comment]
##[href^="https://ghoto-12.win/"]
Not getting applied,  not seen in logger....so to download uncheck `download with download manager` then click (upper/top)`download now`

**Comment by mapx-** [comment]
ok, now I can download the file.
However, the second (fake) download button is hidden by that filter for me

![image](https://user-images.githubusercontent.com/10303732/56861770-8a753180-69a4-11e9-8eb3-081f21d30ead.png)

**Comment by ghajini** [comment]
1. there's no problem on opera browser
2.
Firefox android


Filter doesn't get on my side whether I put in My filters or I just force updated. ..the scriptlet filter is getting applied but not the cosmetic one on firefox android....'
However I put
`uploadbuzz.org##[href^="https://ghoto-12.win/r/"]` from element picker, it worked

May be I should wait 2-3 days for filter update (though I force updated)

​

**Comment by ghajini** [comment]
`||uploadbuzz.org/sw.js$important`
3rd parties appeared

**Comment by ghajini** [comment]
`</script>
    
    <script type="text/javascript">
       function openWin() {
        window.open("https://www.parhlo.xyz/free-download");
        }
        $(document).ready(function(){
            $('#xfiletemplates').click(function(){
                if($(this).prop("checked") == false){
                   // alert(" real download");
    				 $("#downloadbtnad").hide();
           			 $("#downloadbtn").show();
                }
                else if($(this).prop("checked") == true){
                   // alert("ads.");
    				$("#downloadbtnad").show();
           			 $("#downloadbtn").hide();
                }
            });
        });`
Do you know the way to uncheck `checkbox` by default, so that download will start

**Comment by mapx-** [comment]
this trick seems working, test on your side
```
uploadbuzz.org##+js(remove-attr.js, checked)
uploadbuzz.org###downloadbtnad
uploadbuzz.org###downloadbtn:style(display: block !important)
```

**Comment by ghajini** [comment]
Thanks great👏

**Comment by ghajini** [comment]
`https://uploadbuzz.org/vudabogethh5`
fake download buttons
`uploadbuzz.org##[href^="https://7sdcksdc.space/r/"]`
`uploadbuzz.org##[href^="http://7sdcksdc.space/r/"]`
`uploadbuzz.org##b`

**Comment by ghajini** [comment]
`uploadbuzz.org/tymsuz49s0h5`
Shady xhr's

**Comment by ghajini** [comment]
`uploadbuzz.cc/6fsasal8epzw`

At final Download page, download link ID hidden due to xpath filter

**Comment by ghajini** [comment]
`https://uploadbuzz.cc/2lok3vyb32o1`

Download button is hidden due to some filters

**Comment by mapx-** [comment]
@ryanbr

**Comment by ghajini** [comment]
All filters wrt zfgloaded crap needs update imo.....

URL = `uploadbuzz.cc/9kmxxnxoyvid`

Popup ads
