### ISSUE TITLE
techtimes.com unblocked ad

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#547]
### URL(s) where the issue occurs

`http://www.techtimes.com/articles/151802/20160420/viber-adds-end-to-end-encryption-following-footsteps-of-whatsapp-and-apple.htm`

### Describe the issue

From our sponsor section at the bottom

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/28343973-b2d90ad0-6bee-11e7-9216-43d876b084de.png)

**Comment by smed79** [comment]
@okiehsch There is unblocked ads here.

@ryanbr @wizmak fyi.
