### ISSUE TITLE
on YTS.am, new yts.am##[id*=container] filter removes search functionality

### ISSUE THREAD

**Issue by ericb2038** [uBlockOrigin/uAssets#5475]
on yts.am, a new filter yts.am##[id*="container"] added 5 days ago in response to https://github.com/uBlockOrigin/uAssets/issues/5397, removes the quick search functionality from the site 
Searching is still possible by going to the browse movies pages, but does not do autocompletion, so that's a bit of a drag

Without ublock or previously to that filter :
![Screenshot_2](https://user-images.githubusercontent.com/50086092/56870208-4c135d00-6a0c-11e9-812b-bdd2df6b1714.png)

with ublock now:
![Screenshot_3](https://user-images.githubusercontent.com/50086092/56870215-6d744900-6a0c-11e9-9893-871c33e24d81.png)

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/736a12129300c5bf480fedd67aa1fdf02d7e888e

**Comment by ericb2038** [comment]
That did it, Thank you :)
