### ISSUE TITLE
shorto.io

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#5476]
### URL(s) where the issue occurs

`https://shorto.io/foGM4`

### Describe the issue

There's  a popup and  anti adblock

### Versions

- Browser/version: Chrome 73
- uBlock Origin version: 1.18.16

### Settings

- Default settings.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/62f4d746f239269b4ae2be764acbefe50f6af384
