### ISSUE TITLE
popups on tremember.info

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#548]
### URL(s) where the issue occurs

`http://tremember.info/T2doVUcuBRsheDoVBGgvOxMYcHQOQloTYn0hHzQzLA8NJzRhEwdwdQkNGi1wOVFfOD4kUAp7LzsKBA`

### Describe the issue

Unblocked popup if you click around

### Versions

- Browser/version: Chrome 59
- uBlock Origin version: 1.13.2

**Comment by okiehsch** [comment]
Well how did you end up at that site in the first place?

**Comment by terrorist96** [comment]
From here: `https://www.primewire.ag/watch-2796813-Baby-Driver`

**Comment by okiehsch** [comment]
Which version openload, vidtod, vidzi etc.?

**Comment by terrorist96** [comment]
`watchers.to`

**Comment by okiehsch** [comment]
Does
`watchers.to##script:inject(abort-on-property-write.js, Fingerprint2)`
work?

**Comment by okiehsch** [comment]
By work I mean you should not end up at `tremember.info`.

**Comment by terrorist96** [comment]
Yes, that works.
Many of the other links listed on primewire also have the same issue if you're interested. Or I could make separate issues.

**Comment by terrorist96** [comment]
> By work I mean you should not end up at tremember.info.

Oh. Yeah, it stops the redirect.

**Comment by okiehsch** [comment]
If `example.com##script:inject(abort-on-property-write.js, Fingerprint2)` works for all of them there is
no need for seperate issues.

**Comment by terrorist96** [comment]
By similar issue I mean unblocked popups and the like. Example: #549

**Comment by okiehsch** [comment]
I mean for sites that redirect you to `tremember.info` or similar sites just mention them here I will add them.

**Comment by terrorist96** [comment]
`https://www.primewire.ag/goto.php?title=Baby+Driver&url=aHR0cHM6Ly90aGV2aWRlby5tZS90cDF1d21xOGtyN3k=&domain=dGhldmlkZW8ubWU=&loggedin=0`
This one seems to redirect.
Should be `thevideo.me` but goes to `tvad.me`

**Comment by terrorist96** [comment]
`https://www.primewire.ag/goto.php?title=Baby+Driver&url=aHR0cHM6Ly93d3cubW92c2hhcmUubmV0L3ZpZGVvLzgzZTYzYmIzM2VhZjI=&domain=bW92c2hhcmUubmV0&loggedin=0`
This one too. `movshare.net` redirects to `wholecloud` then to `tremember`

**Comment by okiehsch** [comment]
That is a legitimate redirect, I tested all sites listed at `https://www.primewire.ag/watch-2796813-Baby-Driver` and will add a fix.

**Comment by terrorist96** [comment]
:heart:

**Comment by gotitbro** [comment]
@terrorist96 @okiehsch I think you should know if you don't already that the tremember.info domain is part of the RoughTed malvertising campaign directly targeting adblock users. Reposting my comment from a [EasyList thread](https://forums.lanik.us/viewtopic.php?f=62&t=33507&p=121250#p121250):

> As I mentioned in a post earlier (https://forums.lanik.us/viewtopic.php?p=120875#p120875) the **_RoughTed_** domains redirect you to their own websites with an iframe of the URL you originally visited.
> 
> They probably do this to stop domain specific filters from working on such domains. The website owners (such as _daclips.com_) which have implemented such a dangerous and malware ridden technology on their domains do not care about the visitors, I would stay away from such websites unless really necessary.
> 
> [Here](https://gist.github.com/malwareinfosec/73d10721cdb9868a05baff6a59a6bcbc#file-roughted_list) is a list of some of the domains part of the RoughTed campaign.
> 
> If you want to read more about RoughTed, the original **_Malwarebytes_** report:
> https://blog.malwarebytes.com/cybercrime/2017/05/roughted-the-anti-ad-blocker-malvertiser/

**Comment by okiehsch** [comment]
I do know but thanks for the heads-up.

**Comment by terrorist96** [comment]
I hope there's a special place in hell reserved for these people...
Thanks for the info.
