### ISSUE TITLE
peruanazotv.com

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#5481]
### URL(s) where the issue occurs

`http://www.peruanazotv.com/tv/espnmx.html`
`http://peruanazotv.com/tv/fmhot.html`

### Describe the issue

There's a popup when clicking anywhere.

### Versions

- Browser/version: Chrome 73
- uBlock Origin version: 1.18.16

### Settings

- Default settings + Spanish regional filters.

**Comment by mapx-** [comment]
necessary for FF

**Comment by pizza90** [comment]
hi, i test the filter and works fine and no popups.

but is normal these numbers that go up so fast.. it can be dangerous for the PC?

`https://i.imgur.com/fvrsPZ2.png`

this "issue" is not related to the filter. 

_I do not understand what those numbers are that go up so fast on that web page, maybe it's a stupid question xD_

**Comment by mapx-** [comment]
For firefox you can block those loops using
`peruanazotv.com##^script:has-text(cuentaatras)`

**Comment by okiehsch** [comment]
The errors are not caused by any adblock-related filter, looks like a site issue.
