### ISSUE TITLE
jelajahinternet.me

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#5482]
### URL(s) where the issue occurs

`[https://jelajahinternet.me/pdxDXySCu1F8]`

### Describe the issue

[It force to disable adblocker addon]

### Screenshot(s)

[https://imgur.com/fR46aKe]

### Versions

- Browser/version: [Firefox Quantum 66.0.3 x86]
- uBlock Origin version: [1.18.16]

### Settings

- [https://pastebin.com/Setx9vUc]

### Notes

[If i turn off uBO it works]

**Comment by JobcenterTycoon** [comment]
The filter `jelajahinternet.me##+js(addEventListener-defuser.js, load, onload)` works for me and
`jelajahinternet.me##.img-fluid` for the fake button
