### ISSUE TITLE
Unexpected URL rewrite or modification

### ISSUE THREAD

**Issue by hooblei** [uBlockOrigin/uAssets#5483]
### URL(s) where the issue occurs

`https://files.giga-video.de/f7/3a/86/c14f7a8c84d73586331aed7e08_ciAxOTUwA2ZhY2Y4NDM2MWQw.jpg`

### Describe the issue

We have experienced a strange issue, where uBlock Origin seems in some way modify or rewrite the URL above into the following one:

`https://files.giga-video.de/f7/3a/86/c14f7a8c84d73586331aed7e08_AQEBAQEBAQEBAQEBAQEBAQEB.jpg`

This URL is semantically correct but not existing.

Context URL for that issue is:

`https://videos.giga.de/embed/2102989937?autoplay=0`

The URL that triggers the behavior is just a video preview image also the domain serves these kind of preview images only and no ads.

The image URL itself is generated client side from the following source URL at run-time but when inspecting the DOM, the wrong URL is already there (see second screenshot).

`//files.giga-video.de/f7/3a/86/c14f7a8c84d73586331aed7e08_A2ZhY2Y4NDM2MWQw.jpg`

We experienced the issue only with uBlock Origin enabled and the latest version of "uBlock filters". For example when doing a fresh install of uBlock Origin and without updating the filter lists, the image loads as expected, as soon as we update the "uBlock filters" the described behavior occurs.

### Screenshot(s)

![Screenshot 2019-04-30 at 16 56 06](https://user-images.githubusercontent.com/84681/56971854-4d5a9c00-6b6a-11e9-9212-78c8a3a3c001.png)
![Screenshot 2019-04-30 at 16 56 56](https://user-images.githubusercontent.com/84681/56971852-4d5a9c00-6b6a-11e9-9b47-c5e83bc39de7.png)

### Versions

- Browser/version: Chome 74.0.3729.108, FireFox 66.0.3
- uBlock Origin version: 1.18.16 (Chrome), 1.18.6 (FF)

### Settings

- No changes where made to the default settings

### Notes

The error may in some way relate to code on our side but since this only happens with uBlock Origin enabled and with the latest version of "uBlock filters", so we are a bit baffled.

**Comment by okiehsch** [comment]
Should work as expected if you manually update `uBO-unbreak`.

**Comment by hooblei** [comment]
That fixed the issue - thanks.
