### ISSUE TITLE
infomaniakos.com

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#5486]
### URL(s) where the issue occurs

`https://infomaniakos.com/torrents/mula-hdrip-latino/`

### Describe the issue

Anti-adblock.

### Screenshot(s)

<details><summary>Screenshots</summary>

![Anotación 2019-04-30 195646](https://user-images.githubusercontent.com/27441315/56982912-acc4a600-6b82-11e9-8655-0716e93bdb55.png)

![Anotación 2019-04-30 195728](https://user-images.githubusercontent.com/27441315/56982927-b3531d80-6b82-11e9-9cfd-69d3f121e63f.png)
</details>

### Versions

- Browser/version: Chrome 73
- uBlock Origin version: 1.18.16

### Settings

- Default settings + Spanish regional

### Notes

Suggested filter.
`infomaniakos.com##+js(abort-on-property-read.js, openPop)`

**Comment by okiehsch** [comment]
Thanks.
