### ISSUE TITLE
http://streamplay.club/

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#549]
### URL(s) where the issue occurs

`http://streamplay.club/2r3oce3xnhaw`

### Describe the issue

Big fake video player ad. Have to click `Proceed to video` button
Unblocked popups.

**Comment by SMed79** [comment]
`##a[href*="://3wr110.xyz/"]`

**Comment by terrorist96** [comment]
Fake player successfully blocked.
Still popup

**Comment by okiehsch** [comment]
`streamplay.club##script:inject(abort-on-property-read.js, BetterJsPop)`

**Comment by terrorist96** [comment]
@okiehsch that blocks the popup when clicking on `Proceed to video` but there's also another one when clicking on the video itself.

**Comment by terrorist96** [comment]
(and just as soon as I say that, I can't reproduce the second popup anymore lmao)

**Comment by SMed79** [comment]
FYI, 
`http://streamplay.to/tf73s8t5ec17` redirect you to `http://streamplay.club/tf73s8t5ec17`
if an adblock is detected (see [#p120868](https://forums.lanik.us/viewtopic.php?p=120868#p120868)).

**Comment by okiehsch** [comment]
Thanks @SMed79 that helped.
````
streamplay.*##script:inject(abort-on-property-read.js, BetterJsPop)
streamplay.*##script:inject(abort-on-property-read.js, isAdb)
##a[href*="://3wr110.xyz/"]
````
works on my end. 
The video won't play on my end at `http://streamplay.club` but it does play fine without any popups
at `http://streamplay.to`

**Comment by terrorist96** [comment]
Interesting. If I include `streamplay.*##script:inject(abort-on-property-read.js, isAdb)` then the video's play button doesn't appear on `.club` (and I can't play it) but if I exclude it, the button appears, I get a popup, but the video will play. So including that second line prevents the video from playing for me.

**Comment by okiehsch** [comment]
What about 
````
streamplay.*##script:inject(abort-on-property-read.js, BetterJsPop)
@@||streamplay.to/js/popup2.js$script,first-party
@@||streamplay.club/js/popup2.js$script,first-party
##a[href*="://3wr110.xyz/"]
````

**Comment by terrorist96** [comment]
Perfect :+1:

**Comment by ghajini** [comment]
`https://streamp1ay.me/32ooa3a5vhqg`
new domain of streamplay, popup ads

**Comment by ghajini** [comment]
`https://streamp1ay.me/rps74bq5j1fn`
Antiadblock
![IMG_20190601_222817](https://user-images.githubusercontent.com/20338483/58751488-a3cf3900-848e-11e9-94cc-088b1a38f6ec.jpg)
Firefox android
Ublock origin 1.19.6

**Comment by ghajini** [comment]
`https://steamplay.cc/3no27e5924kt`
Variant of streamplay
Popup ads

**Comment by ghajini** [comment]
Block push notifications
tabless request
`||steamplay.cc/jquery-1.8.2.min.js$1p`

**Comment by ghajini** [comment]
Popups on clicking ***proceed to video***

`https://steamplay.me/b30i1u56o1le`

**Comment by ghajini** [comment]
Antiadblock & popup ads

`https://streamplay.life/dhp2d6dptm5w`

**Comment by ghajini** [comment]
Antiadblock
`https://streamp1ay.cc/5pin1b0hmdwm`

**Comment by ghajini** [comment]
popup ads
`https://steanplay.cc/ikqunzkmplpy`

**Comment by huyszn** [comment]
Fake button
`https://streampiay.fun/9lls6zxexpsa`

**Comment by playonevideo** [comment]
> Fake button. There are also pop-ups when you click the "Proceed to video" button and try to start the video. `https://stre4mplay.one/0zsgbewajf7s`

Same situation also on `https://stre4mpay.one/9nomeli6ind4`

**Comment by BlazeFTL** [comment]
fixed
