### ISSUE TITLE
Uploadfiles.pw

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5492]
### URL(s) where the issue occurs

`https://uploadfiles.pw/1f38333e56b1bd18`

### Describe the issue
3rd party keep increasing if blocked 

### Versions

- Browser/version: firefox android stable
- uBlock Origin version: 1.18.16

### Settings

- uBO's default settings

### Notes

`Uploadfiles.io` and `Uploadfiles.pw` are two different domains

**Comment by gorhill** [comment]
> 3rd party keep increasing

What does that mean?

**Comment by ghajini** [comment]
If I add
`* 41df76c67812005c.com * block`
then another 3rd party xhr is created on reload of page,  see logger after reload....if blocking one by one,number of that increased until all blocked....
Similar fix is available for other sites also,
https://github.com/uBlockOrigin/uAssets/commit/72267494122e0e562cb19d7f1cf2daf3002243c5

**Comment by ghajini** [comment]
This filter
uploadfiles.pw##+js(abort-current-inline-script.js, Math.sin, vocabulary)

prevents these unwanted 3rd party xhr's
![IMG_20190501_233021](https://user-images.githubusercontent.com/20338483/57033065-6d0dc500-6c3b-11e9-9436-6fc7b6ca3a63.jpg)

**Comment by gorhill** [comment]
How about:

    ||uploadfiles.pw^$csp=default-src 'self'

**Comment by okiehsch** [comment]
Is that preferable to aborting the offending inline-script?

**Comment by gorhill** [comment]
I personally prefer this if it works, this frees the browser from even executing the inline script.

**Comment by okiehsch** [comment]
The filter works and I don't see any breakage.

**Comment by ghajini** [comment]
`||uploadfiles.pw^$csp=default-src 'self'`skips countown timer
but if I click download and follow further steps,  I can download the file

**Comment by gorhill** [comment]
I suppose we could comsetically remove the broken countdown to avoid confusion -- the button still work.

**Comment by ghajini** [comment]
Further CSP filter breaks dropdown menu options
`https://user-images.githubusercontent.com/20338483/57035967-adbd0c80-6c42-11e9-869d-b51f9587214e.jpg`

**Comment by gorhill** [comment]
Try `||uploadfiles.pw^$csp=default-src 'self' 'unsafe-inline'`.

The countdown works, but the page is unable to pull in 3rd-party stuff.

**Comment by gorhill** [comment]
@okiehsch the latest filter does not prevent inline scripts but I still prefer it because it's a default-deny approach, more strict than what a scriptlet can accomplish.

**Comment by okiehsch** [comment]
Will keep that in mind for future issues, the problem I see with csp filters is the potential breakage on "complicated" sites, i.e. sites that include comments, pictures, video streaming, etc.
The debugging of a csp filter that causes the breakage is rather time consuming and not straightforward, atleast for me. ;)

**Comment by gorhill** [comment]
You have more experience than I do as filter list maintainer, so just do what you think is best for you -- I could very well change my mind if I would end up having to deal with the consequences.

I have given more thoughts lately on a `default-deny-allow=` option, which would tell which only 3rd-party to allow on a given site. Do you think this would help? Or would that be just the same as using CSP? (a `default-deny-allow=` would not prevent the blocked 3rd parties from appearing in the logger as opposed to `csp=`)

**Comment by okiehsch** [comment]
>  would not prevent the blocked 3rd parties from appearing in the logger as opposed to csp=)

That would  big issue I see with csp filters, I have to use the dev console to see what is blocked and then debug and  because of that sometimes even experienced filter list maintainers don't know that their csp filter is actually breaking site functionality. https://github.com/uBlockOrigin/uAssets/issues/2073#issuecomment-384157988

Seeing the blocked requests in the logger would make debugging straightforward for everybody.

**Comment by uBlock-user** [comment]
> I have to use the dev console to see what is blocked and then debug

That is the big issue I see with csp filters, that's the very nature of CSP filters, when you set a CSP policy, blocking is done by the browser, not by uBO.

**Comment by uBlock-user** [comment]
That is the big issue I see with csp filters I have to use the dev console to see what is blocked and then debug

That's the very nature of CSP filters, when you set a CSP policy, blocking is done by the browser, not by uBO.
