### ISSUE TITLE
galaxydestek.com

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#5493]
### URL(s) where the issue occurs

- `https://galaxydestek.com/samsung-galaxy-s6-edge-sm-g925f-stock-rom-download/`

### Describe the issue

- Anti-Adblock Script

### Screenshots

![Screenshot_2019-05-01 Samsung Galaxy S6 Edge SM-G925FQ Stock Rom Download GalaxyDestek com](https://user-images.githubusercontent.com/24980766/57016396-d5cb5200-6be7-11e9-9b32-b0a90a57f778.png)

### Versions

- Browser/version: Firefox 66.0.3
- uBlock Origin version: 1.18.16

### Settings

- All Filters Enabled + I don't care about cookies + Energized Spark Protection. Regional Filters, uBlock Filters Experimental, Adblock Warning Removal List, and Anti-Facebook List disabled.

### Notes

Relies on generic element blocking for detection.
Adding `@@||galaxydestek.com^$generichide` or whitelisting `#adcontent` fixes this problem.

**Comment by gorhill** [comment]
I reported to Adguard so that the fix can be included in Adguard Turkish.
