### ISSUE TITLE
fc.lc

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#5495]
```
fc.lc/WyZL
```

Anti-adblock  form "`fabsdeals.com`"?

**Comment by krystian3w** [comment]
```
fc.lc##+js(abort-on-property-read.js, app_vars.force_disable_adblock)
fc.lc##+js(abort-on-property-write.js, adBlockDetected)
fc.lc##+js(addEventListener-defuser.js, /^(?:click|mouseup)$/, [J])
/sw.js$script,domain=fc.lc
```

**Comment by JobcenterTycoon** [comment]
`||fc.lc/dw.html` for these fake buttons

**Comment by dumbusernameidk** [comment]
`||fc.lc/sw.js$script,1p`

**Comment by ghajini** [comment]
`fc.lc/aOeMz5Za`
Fake `watch now/download` buttons

**Comment by ghajini** [comment]
`fc.lc/GezvUI`
Popups after captcha completion on clicking ***get link***

**Comment by ghajini** [comment]
Popups are at `fc.lc`

Screenshots=

`https://prnt.sc/pjpetv`

**Comment by ghajini** [comment]
You added filter for earn-money-onlines.info
Is that correct,I mean iam reporting popups at fc.lc

**Comment by mapx-** [comment]
yes, I got popups only on `earn-money-onlines.info`

**Comment by ghajini** [comment]
`https://fc.lc/3kWO`
Popups on clicking ***get link***

**Comment by ViperCode7** [comment]
They've changed the address to fcdot.lc... any fc.lc wil redirect there.

**Comment by ghajini** [comment]
`fc.lc/8620S`

**Get link** button not visible after captcha verification page

**Comment by mapx-** [comment]
does this work ?
`||fc.lc^$3p,badfilter`

**Comment by ghajini** [comment]
Yes

**Comment by lain566** [comment]
I did not know that it directed to a third party page.

**Comment by ghajini** [comment]
https://github.com/uBlockOrigin/uAssets/commit/fd7bcea55cd730d33e0c18a063fdada3e2a7e16b

doesn't work for me
@lain566 did you get **get link** at end page

@mapx- filter work

**Comment by krystian3w** [comment]
@lain566  used `<form id="submit_data" action="https://redirecte.link/file.php" method="POST">` and something script send form:

```js
setTimeout(function() {
    document.getElementById('submit_data').submit();
}, 1000);
```

**Comment by lain566** [comment]
> @lain566 did you get **get link** at end page

Yes.


> [fd7bcea](https://github.com/uBlockOrigin/uAssets/commit/fd7bcea55cd730d33e0c18a063fdada3e2a7e16b)
> 
> doesn't work for me

@ghajini Open the logger, and show me the requests blocked by`||fc.lc^$3p,script`

**Comment by krystian3w** [comment]
None on `fcdot.lc` / `redirecte.link`, also with Android user-agent, may need use real phone with Firefox?

**Comment by ghajini** [comment]
> > @lain566 did you get **get link** at end page
> 
> Yes.
> 
> > [fd7bcea](https://github.com/uBlockOrigin/uAssets/commit/fd7bcea55cd730d33e0c18a063fdada3e2a7e16b)
> > doesn't work for me
> 
> @ghajini Open the logger, and show me the requests blocked by`||fc.lc^$3p,script`

Now it's working. ....

1hour before after you commited, I do force update ublock filters and/or added filter `||fc.lc^$3p,script` and even cleared cache, that time its not working. ..(only mapx- filter worked)

Why this happens everytime on firefox/opera(not get updated filters even after force update of filters)?
Sorry nuisance...but happens after everytime (I have to wait 2-3 hr after you people commit)

**Comment by krystian3w** [comment]
> or added filter `||fc.lc^$3p,script` and even cleared cache, that time its not working

because copied no disable old `||fc.lc^$3p`, only `,badfilter` can disable.

A correct test requires copying both filters to the My Filters tab.


`||fc.lc^$3p,badfilter`
`||fc.lc^$3p,script`

---

> Why this happens everytime on firefox/opera

Github cache on raw  file/resource may need wait 10 minutes if you still no see updated file/resource.

Also your Internet provider maybe block download latest file and you need use vpn  to show newest - `gist.gitchub.com` has such a bug as you do quickly with ~6 updates, then you don't see the latest raw version for long.

**Comment by uBlock-user** [comment]
@ghajini Set `updateAssetBypassBrowserCache` to `true` in Advanced Settings, that should help bypass cache from browser side of things.

**Comment by uBlock-user** [comment]
> Why this happens everytime on firefox/opera(not get updated filters even after force update of filters)?
Sorry nuisance...but happens after everytime (I have to wait 2-3 hr after you people commit to get filters to apply to page)

@ghajini Set `updateAssetBypassBrowserCache` to `true` in Advanced Settings, that should help bypass cache from browser side of things.

**Comment by ThinksHeIsCool** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/97239

filters:
```
@@||markipli.com^$ghide
markipli.com##+js(aopr, open)
markipli.com##+js(nano-sib)
```
