### ISSUE TITLE
programasvirtualespc.net

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#5498]
### URL(s) where the issue occurs

`https://www.programasvirtualespc.net/edicion/camtasia-studio-v9-1-2-build-3011-crear-videos-profesional-de-grabacion-de-pantalla-y-edicion-de-video/`

`https://pastepvp.org/?v=50`

### Describe the issue

Fake button

### Screenshot(s)

<details><summary>Screenshots</summary>

![Anotación 2019-05-01 144452](https://user-images.githubusercontent.com/27441315/57017618-2a8abf00-6c20-11e9-8bb7-a6d8b23ea817.png)

![Anotación 2019-05-01 144537](https://user-images.githubusercontent.com/27441315/57017624-34142700-6c20-11e9-918a-4ac18f22dd71.png)
</details

### Versions

- Browser/version: Chrome 73
- uBlock Origin version: 1.18.16

### Settings

- Default settings + Spanish regional

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

![2019-11-23_20h39_29](https://user-images.githubusercontent.com/36675858/69487005-a43f0000-0e31-11ea-924a-90928632f640.png)
![2019-11-23_20h39_38](https://user-images.githubusercontent.com/36675858/69487006-a6a15a00-0e31-11ea-8753-701539c4a7ff.png)
![2019-11-23_20h39_47](https://user-images.githubusercontent.com/36675858/69487009-a903b400-0e31-11ea-8b90-28bc683e30c0.png)
