### ISSUE TITLE
Block content div

### ISSUE THREAD

**Issue by kudataz** [uBlockOrigin/uAssets#55]
example i have `<div id="z2c7">blbalbalblab</div>`
how to block this div?

**Comment by kudataz** [comment]
where i must ask sir @gorhill ?

**Comment by IDKwhattoputhere** [comment]
You completely ignored the template that was there. Without even an example URL no one can help you.

**Comment by lewisje** [comment]
I'll go ahead and respond, even though you really should read the docs: Add the custom filter `###z2c7` assuming that id isn't randomly generated.
