### ISSUE TITLE
http://www.speedvid.net/

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#550]
### URL(s) where the issue occurs

`http://www.speedvid.net/33700tegmste`

### Describe the issue

Overlay (with blocked ads but still have to wait 5 seconds).
Unblocked popup if click on video.

**Comment by SMed79** [comment]
see if helps https://forums.lanik.us/viewtopic.php?f=62&t=32959

**Comment by terrorist96** [comment]
Thanks, but not really. I added all the ones you have listed, but I still get a popup when clicking on the video. The overlay also appears sometimes and sometimes it doesn't (even without any of your filters)
