### ISSUE TITLE
cablegratis.tv

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#5505]
### URL(s) where the issue occurs

`http://cablegratis.tv/canal-en-vivo/espn`
`http://cablegratis.tv/`

### Describe the issue

There's a popup when clicking on any channel on the homepage, and also by clicking on the player.

### Versions

- Browser/version: Chrome 73
- uBlock Origin version: 1.18.16

### Settings

- Default settings + Spanish regional

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`http://cablegratis.tv/canal-en-vivo/tyc-sports`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock ?

**Comment by okiehsch** [comment]
The filters I added fix the issue on my end.
![image](https://user-images.githubusercontent.com/16838044/59734087-66b9c380-9250-11e9-8ba4-0bc71c800390.png)

**Comment by KiLL4FuNK** [comment]
now it works well ready
