### ISSUE TITLE
bleepingcomputer.com video broken

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#551]
### URL(s) where the issue occurs

`https://www.bleepingcomputer.com/news/security/malvertising-campaign-finds-a-way-around-ad-blockers/`

### Describe the issue

Clicking on one of the recommended videos on the right doesn't work.

### Notes

Adding this fixes it:
`@@||a.tvpage.com/tvpa.min.js$script,domain=www.bleepingcomputer.com`

**Comment by anewuser** [comment]
Use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) to find out what list has blocked your request, and report it to the maintainers of that list.

**Comment by terrorist96** [comment]
@gorhill the code I provided works but the better fix you made doesn't work.
![image](https://user-images.githubusercontent.com/12802056/28378664-f3bc6638-6c7e-11e7-98f2-1bcd12d856aa.png)

**Comment by gorhill** [comment]
I am pretty sure it was working when I tried it.
