### ISSUE TITLE
cyfostreams.com

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#5510]
### URL(s) where the issue occurs

- `http://cyfostreams.com/cyfo11.html`

### Describe the issue

- Anti-Adblock Script - Bait Scripts
- Popups

### Screenshots

![Screenshot_2019-05-04 CYFO 11 Cycling Football Streams](https://user-images.githubusercontent.com/24980766/57181557-695c8700-6e63-11e9-8eb4-352480c5fa74.jpg)

### Versions

- Browser/version: Firefox 66.0.3
- uBlock Origin version: 1.18.16

### Settings

- All Filters Enabled + I don't care about cookies. Regional Filters, uBlock Filters Experimental, and Anti-Facebook List disabled.

### Notes

Whitelist `advertisement.js` to fix this issue.
Add `cyfostreams.com##+js(nowebrtc.js)` to defuse popups.

**Comment by KiLL4FuNK** [comment]
Popups
