### ISSUE TITLE
uBlock Detected [anti-adblock]NSFW

### ISSUE THREAD

**Issue by weijen6** [uBlockOrigin/uAssets#5511]
`https://firm-ware27.blogspot.com/2017/09/firmware-oppo-r9s-plus-cph1611.html`

`https://flash-reset.blogspot.com/2017/07/100-work-official-firmware-oppo-a39.html`

`https://www.444.coffee/shkd-782-%E8%A2%AB%E4%BE%B5%E7%8A%AF%E7%9A%84%E5%A5%B3%E6%A0%BC%E9%AC%A5%E5%AE%B6-%E9%80%A2%E6%BE%A4%E7%9C%9F%E9%87%8C%E4%BA%9E%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95.html`

`https://magiclen.org/macos-mojave-iso/`

**Comment by garry-ut99** [comment]
`https://magiclen.org/` - annoynace anti-adblock:
![jj](https://user-images.githubusercontent.com/72945564/218085394-ed292e07-d0e6-4d37-95af-63854493a277.png)
