### ISSUE TITLE
akuno.net [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5516]
URL(s) where the issue occurs

`https://akuno.net/CThFynruAD`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 73 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.18.16

Settings

Default

**Comment by krystian3w** [comment]
Comeback - https://github.com/timmyrs/Universal-Bypass/issues/219

> ![obraz](https://user-images.githubusercontent.com/35370833/57645525-befd0600-75be-11e9-87db-a433296511f2.png) |
> --- |


Maybe bug in non-stock filters... (so no need fix for stock recomend configuration).
