### ISSUE TITLE
bhaskar.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#552]
I am facing an issue on http://daily.bhaskar.com, whereby when I browse a slideshow and reach the 5th image and click next it automatically refreshes the page. This happens when uBO is enabled.

**SS:** https://streamable.com/shvda

**Error URL:** 
http://daily.bhaskar.com/news/LIF-WEW-funny-online-shopping-5649183-PHO.html

_**Note:** Using uBO 1.13.2 on Chrome 59 with the default filters and settings._

**Comment by mapx-** [comment]
It's the same behaviour even disabling uBo.

You could use the other slide (bellow).

**Comment by gorhill** [comment]
Does this work without negative side effects?

    daily.bhaskar.com##script:inject(abort-on-property-write.js, popupAdCall)

**Comment by gotitbro** [comment]
> It's the same behaviour even disabling uBo.
@mapx- No it isn't: https://streamable.com/1jbkr

@gorhill That filter works and I haven't noticed any breakage. There is also an ad leftover below the photo captions in the sildeshow.

**SS:** https://i.imgur.com/W8QpIge.png

**Error URL:**
http://daily.bhaskar.com/news/JM-SUC-perfect-ayurvedic-breakfast-5577723-PHO.html?seq=2

**Comment by SMed79** [comment]
> There is also an ad leftover below the photo captions in the sildeshow.

Just for reference purposes https://github.com/uBlockOrigin/uAssets/issues/188#issuecomment-309325916  :wink:

**Comment by gotitbro** [comment]
@SMed79 I was asking for help as I was unable to hide it myself.

**Comment by gorhill** [comment]
`##.slider-caption .artcontent:style(height: auto !important;)`
