### ISSUE TITLE
livetv.sx

### ISSUE THREAD

**Issue by lain566** [uBlockOrigin/uAssets#5527]
### URL(s) where the issue occurs

`http://cdn.livetvcdn.net/webplayer.php?t=ifr&c=1171160&lang=en&eid=798411&lid=1171160&ci=114&si=19`

### Describe the issue

Popup.

### Versions

- Browser/version: Chrome 73
- uBlock Origin version: 1.18.16

### Settings

- Default settings.

**Comment by lain566** [comment]
Popup when clicking on the player.
`http://cdn.livetvcdn.net/webplayer.php?t=ifr&c=1168258&lang=es&eid=798521&lid=1168258&ci=183&si=17`

**Comment by ghost** [comment]
Ad banner with counter on 

`https://livetv.sx/enx/eventinfo/336606135_botic_van_de_zandschulp_novak_djokovic/#webplayer_alieztv|245191|336606135|2911872|226|4|en`

https://github.com/user-attachments/assets/c195bf01-794e-4e23-abd7-398bfc4dbc6e" />

**Comment by mapx-** [comment]
```adb
/apl.*\.me/##[onclick="adr();"]:upward(3)
```
