### ISSUE TITLE
convertcase.net

### ISSUE THREAD

**Issue by mapx-** [uBlockOrigin/uAssets#553]
### URL(s) where the issue occurs

`convertcase.net`

### Describe the issue

unblocked ads at the top

### Screenshot(s)

https://reports.adblockplus.org/6aecac54-6681-4116-a4ca-10a4345ba1a0.png

Working filter:
`||convertcase.net^$csp=script-src 'self' * 'unsafe-inline' data:`

**Comment by okiehsch** [comment]
I will fix this and a whole host of sites with the same issue. I am just in the middle of testing
that nothing breaks on these sites if I add
`*$csp=script-src 'self' * 'unsafe-inline' data,:domain=example.com`

**Comment by mapx-** [comment]
Seems to be a tricky combination of webrtc, websocket

**Comment by okiehsch** [comment]
````
*$csp=script-src 'self' * 'unsafe-inline' data:,domain=acidcow.com|www.bolde.com|breaking911.com|convertcase.net|convertfiles.com|gostica.com|heraldweekly.com|neonnettle.com|powerpyx.com|tamilo.com|tfln.co|thecomeback.com|truthfeed.com
````
I had to drop `textsfromlastnight.com` because the csp breaks the ability to sign-up. 
`www.bolde.com` is not a typo `bolde.com` would break `shop.bolde.com`

**Comment by okiehsch** [comment]
@mapx- yes they -uponit- use webrtc, websockets or xhr requests to push their ads via iframes.
Blocking the webrtc does not always work.
For more information https://github.com/uBlockOrigin/uAssets/issues/394
