### ISSUE TITLE
playonlinux.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#5530]
### URL(s) where the issue occurs

`www.playonlinux.com`

### Describe the issue

Anti-Adblock

### Screenshot(s)

![ss_009](https://user-images.githubusercontent.com/43844449/57191617-efda9c80-6f27-11e9-974e-d4a8bec2e32b.png)

### Versions

- Browser/version: Firefox 66.0.3 64bit / Opera 60 64bit
- uBlock Origin version:  1.18.16

### Settings

Default

### Notes

Example solutions:

1
`@@||www.google-analytics.com/analytics.js$script,third-party,domain=www.playonlinux.com`
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,third-party,domain=www.playonlinux.com`

2
`www.playonlinux.com##+js(abort-current-inline-script.js, $, Advertising seems to be blocked by your browser)`

3 
`www.playonlinux.com##^script:has-text(Advertising seems to be blocked by your browser)` (for Firefox)

**Comment by mapx-** [comment]
Is it only about an annoyance, right ?

**Comment by kulfoon** [comment]
Yes.
