### ISSUE TITLE
golem.de anti adblocker

### ISSUE THREAD

**Issue by Inyaheyukan** [uBlockOrigin/uAssets#5532]
`golem.de/news/`  (every newssite)

`https://www.golem.de/news/hannes-ametsreiter-vodafone-muss-einige-mobilfunkstationen-wieder-abbauen-1905-141042.html`

### Describe the issue

Open a news site on golem.de and scroll down. A layer of information overlays the site.

### Screenshot(s)

![golem](https://user-images.githubusercontent.com/4369755/57200126-d9fcc400-6f87-11e9-9671-fa916d54f2ef.png)

### Versions

- Browser/version: [Firefox 66.0.3]
- uBlock Origin version: [1.18.16]

**Comment by gwarser** [comment]
Needs update https://www.reddit.com/r/uBlockOrigin/comments/dzhmw7/block_new_anti_adblock_measures_on_golemde/

They use now `{window.showAds&&"string"==typeof window.showAds&&window.showAds.match(/[a-z0-9]{5,}/)`

Maybe `golem.de##+js(set, adBlockerDetected, false)`?

**Comment by mapx-** [comment]
2 days ago I added
https://forums.lanik.us/viewtopic.php?p=151327#p151327

Now, even without that filter I cannot reproduce the issue
