### ISSUE TITLE
miniusa.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#5533]
### URL(s) where the issue occurs

`https://www.miniusa.com/tools/learning/models-build/build.html#/config/coopersecountrymanall4/build/0/?trim_code=coopersecountrymanall4&partcodes=ZHI,A94,20D,4BD,3AB&year=2019`

### Describe the issue

Doesn't load 

### Notes

`@@||www.miniusa.com/etc/designs/mini/js/vendor/tracking/adobe/sitecat.min.js?build=917d8afdc$script,domain=www.miniusa.com
@@||www.miniusa.com/etc/designs/mini/js/vendor/tracking/traknet/analytics.min.js?build=917d8afdc$script,domain=www.miniusa.com`

**Comment by okiehsch** [comment]
Is anything broken if you add
`||miniusa.com/etc/designs/mini/js/vendor/tracking/*$script,1p,redirect=noopjs`
and remove your exceptions?

**Comment by terrorist96** [comment]
That works.
