### ISSUE TITLE
VPN Providers disappear on privacytools.io (completly ad free website)

### ISSUE THREAD

**Issue by BurungHantu1605** [uBlockOrigin/uAssets#5537]
### URL(s) where the issue occurs
`https://www.privacytools.io/providers/vpn/`

### Describe the issue

A user mentioned the issue in [this forum thread](https://forum.privacytools.io/t/are-these-vpns-untrusted/337). It happens on our completly ad free website. Affected VPN Providers: ExpressVPN and OVPN.com. uBlock Origin is removing these entries as port of cosmetic filtering, so I'm not quiet sure if its a filter issue.

### Screenshot(s)
![vpn](https://user-images.githubusercontent.com/11730911/57219097-9f4b6800-7029-11e9-941d-263696aa79fc.png)

### Versions

- Browser/version: Firefox 66.0.4
- uBlock Origin version: 1.18.16

### Settings

Default settings

**Comment by mapx-** [comment]
What filter lists are enabled in uBo ? I cannot reproduce the issue.
Open the logger and see what filters are triggered and from what list.

**Comment by JobcenterTycoon** [comment]
I can reproduce. The bad filters are `##[href*=".expressvpn.com"]` and `##[href*=".ovpn.com"]` from Fanboy’s Enhanced Tracking List

**Comment by mapx-** [comment]
report here
https://github.com/ryanbr/fanboy-adblock/issues

@ryanbr
