### ISSUE TITLE
op-online.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5541]
### URL(s) where the issue occurs

`https://www.op-online.de/region/rodgau/rodgau-hessen-opel-kadett-flammen-zufahrt-gesperrt-12255585.html`

### Describe the issue
Unblocked Picture Ads

### Screenshot(s)

<img width="1060" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/57239239-a2475800-702b-11e9-8799-7a06be6c6e27.PNG">

### Versions

- Browser/version: Firefox 66.0.4
- uBlock Origin version: v1.18.16

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3148895/Settings.txt)

### Notes

The filter `op-online.de##+js(setTimeout-defuser.js, )&&)` works for me

**Comment by mapx-** [comment]
I get a lot of ads at the bottom
see if helps in your case

`op-online.de##+js(set-constant.js, String.prototype.charAt, noopFunc)`

**Comment by mapx-** [comment]
added yours to be consistent with .de sites
