### ISSUE TITLE
Dplay Login

### ISSUE THREAD

**Issue by JonnyThree** [uBlockOrigin/uAssets#555]
### URL(s) where the issue occurs

https://it.dplay.com/

### Describe the issue

Login with Facebook ID impossible

### Screenshot(s)

![1](https://user-images.githubusercontent.com/10285273/28441891-87a003d0-6dad-11e7-8195-fd266756f35b.jpg)

### Versions

- Browser/version: Firefox 54.0.1 x64
- uBlock Origin version: uBlock Origin 1.13.9.0

### Settings

- Filter: Anti-ThirdpartySocial (see warning inside list)

### Notes

Hello as described, i can't use the "Login with Facebook" prompt with the described Filter list. If i disable this filter, i can use that login prompt. I need this filter to stay active, but it's very boring every time to deactivate it only for this crap login.
Is possible to exclude this filter list only for this website?
Thanks for any suggestion.

**Comment by okiehsch** [comment]
Try 
`@@||connect.facebook.net/it_IT/sdk.js$script,domain=it.dplay.com`

**Comment by JonnyThree** [comment]
thanks for the answer. added this string. now the login button open another tab (before was doing nothing) with facebook url, but is a empty page and on dplay no changes (no login)
maybe another block in Anti-ThirdpartySocial filter? I have also Fanboy’s Social Blocking List active

**Comment by okiehsch** [comment]
If I add `@@||connect.facebook.net/it_IT/sdk.js$script,domain=it.dplay.com`
this is the result if I click `Accedi con Facebook`
![dolc](https://user-images.githubusercontent.com/16838044/28444079-bccfaac6-6dba-11e7-9622-e6959aaefff5.JPG)
even if I enable `Anti-ThirdpartySocial` and  `Fanboy’s Social Blocking`.

**Comment by JonnyThree** [comment]
really strange in my browser the facebook tab is empty.
i have uploaded my settings here
https://pastebin.com/dQXgWtr5

**Comment by kowith337** [comment]
If you use anti-3p social and/or Fanboy SocialBlocking, it also block social network login on 3d party sites (That's why you need to read the warning inside before active)

Try disable first and then reactivate when you're done logged in.

**Comment by JonnyThree** [comment]
i already know this, iknow that this is the possible side-effect of enabling this list.

but, this was my first question:

If i disable this filter, i can use that login prompt. I need this filter to stay active, but it's very boring every time to deactivate it only for this crap login.
Is possible to exclude this filter list only for this website?

so, i am only asking if it's possible to exclude this list only for this crap website. 
if it's not possible, or there arent any workarounds, thanks anyway for the support

**Comment by okiehsch** [comment]
I can't reproduce, even if I use exactly your filterlist, I can login.
You can allow all facebook requests at `https://it.dplay.com`
Add
````
@@||facebook.com^$domain=it.dplay.com
@@||connect.facebook.net^$script,domain=it.dplay.com
`````

**Comment by JonnyThree** [comment]
sooo many thanks now it's working. login is ok. i very appreciated your support
