### ISSUE TITLE
mimikama.at

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5552]
### URL(s) where the issue occurs

`https://www.mimikama.at/allgemein/der-power-generator-der-stadtwerke-muehlhausen`

### Describe the issue

Clickable Kaspersky Ads in the background, Sponsored Ads

### Screenshot(s)
<img width="1904" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/57320280-cf186f80-70fe-11e9-95c4-d91fb6436e9c.PNG">
<img width="265" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/57320538-6d0c3a00-70ff-11e9-9f09-27a1ed3e2bb4.PNG">

### Versions

- Browser/version: Firefox 66.0.4
- uBlock Origin version: v1.18.16

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3153848/Settings.txt)

**Comment by mapx-** [comment]
test
```
||mimikama.at/*promo$image,1p
mimikama.at##+js(abort-on-property-write.js, td_ad_background_click_link)
```

**Comment by JobcenterTycoon** [comment]
> 
> 
> test
> 
> ```
> ||mimikama.at/*promo$image,1p
> mimikama.at##+js(abort-on-property-write.js, td_ad_background_click_link)
> ```

it's working
