### ISSUE TITLE
adsviv.com

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#5554]
### URL(s) where the issue occurs

- `https://adsviv.com/su/ih8z0t36`

### Describe the issue

- Anti-Adblock Script - BlockAdBlock
- Popunders
- Ads
- Request for timer booster

### Versions

- Browser/version: Firefox 66.0.5
- uBlock Origin version: 1.18.16

### Settings

- All Filters Enabled + I don't care about cookies. Regional Filters, uBlock Filters Experimental, and Anti-Facebook List disabled.
- Also tested using default filters only

### Notes

Banner ads partially blocked; the other one is served from its own domain.
There's another popunder if you click on "SKIP AD", after solving reCAPTCHA and waiting.

```
@@||adsviv.com^$generichide
adsviv.com##+js(abort-current-inline-script.js, Math, zfgloaded)
adsviv.com##+js(nano-setInterval-booster.js, , 1000)
adsviv.com##+js(abort-on-property-write.js, _pop)
adsviv.com##+js(window.open-defuser.js, , c4free)
||adsviv.com/banner/$frame
```
Third party domains:
```
||botkano.info^
||ketapang.biz^
```

**Comment by okiehsch** [comment]
Thanks for investigating.

- `adsviv.com##+js(nano-setInterval-booster.js, , 1000)`
The second paramet defaults to 1000, so
`adsviv.com##+js(nano-setInterval-booster.js)`
will work. https://github.com/gorhill/uBlock/wiki/Resources-Library#nano-setinterval-boosterjs-

- `adsviv.com##+js(abort-on-property-write.js, _pop)` is not necessary and does not do anything as far as I can see.
