### ISSUE TITLE
uBlock filters list brokes "Danmaku" feature on bilibili.com

### ISSUE THREAD

**Issue by ryans233** [uBlockOrigin/uAssets#5556]
### URL(s) where the issue occurs
https://www.bilibili.com/video/av51836231
(it breaks every video withins' page.)

### Describe the issue
Recent updates on ublock filter blocked danmaku api xhr for bilibili.com, making bilibili users cannot watch danmaku on videos anymore. I have read the topic of this rule and I'm pretty sure that it's not necessary to block danmaku by default, as it's a key feature on that website and can be easily toggle on/off.
For those who don't know, "Danmaku" is a very popular key feature in bilibili and niconico douga, which basiclly a realtime floating comments.

### Versions

- Browser/version: [Firefox 67b18]
- uBlock Origin version: [1.18.16]

### Settings
Default

### Notes
https://github.com/uBlockOrigin/uAssets/commit/16cde855f1c4710533da4489eff663073e52b334#diff-728d382ab45d1e85df51bb432db0ce90

**Comment by mapx-** [comment]
> a key feature on that website and can be easily toggle on/off.

How can be done ?

**Comment by ryans233** [comment]
> 
> 
> > a key feature on that website and can be easily toggle on/off.
> 
> How can be done ?
https://imgur.com/a/K9l6ukH

**Comment by mapx-** [comment]
thanks
