### ISSUE TITLE
yourbittorrent.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#556]
### URL(s) where the issue occurs

`https://yourbittorrent.com/torrent/10854624/game-of-thrones-s07e01-web-h264-tbs.html`

### Describe the issue

Unblocked popup. Fake `Direct Link` and `Download Now` buttons (`Torrent File` is legit).

**Comment by ghajini** [comment]
`yourbittorrent.pw`

Popup ads
Opera browser
ubo Dev ver
