### ISSUE TITLE
9anime - F5 server pop-up

### ISSUE THREAD

**Issue by SheepKid12** [uBlockOrigin/uAssets#5563]
### URL(s) where the issue occurs

`https://9anime.ru/watch/sewayaki-kitsune-no-senko-san.pv2x` (or pretty much any episode that has the F5 server as an option).

### Describe the issue

When you try to pause a video (or maybe even just click inside the player) on the F5 server, you get a pop-up.

### Screenshot(s)

I don't think a screenshot is needed here. All I would show is just the video player paused.

### Versions

- Browser/version: Firefox 66.0.4
- uBlock Origin version: 1.18.16

### Settings

Default settings (I used to copy and paste every filter list I use, but it might be easier if I just use default settings for reporting issues).

### Notes

A user on the 9anime subreddit (who maintains their own filter list for 9anime specific fixes) found that `prettyfast.to##+js(abort-current-inline-script.js, adcashMacros)` removes the pop-up.

**Comment by okiehsch** [comment]
I can't reproduce.
Have you updated your filter list?
A filter for that issue was added yesterday https://github.com/uBlockOrigin/uAssets/commit/eddb9b31b12e95d461ad847e65f09011fc567915

**Comment by dumbusernameidk** [comment]
No popups on my end with latest filters.

**Comment by SheepKid12** [comment]
I guess I didn't update my filters.

**Comment by SheepKid12** [comment]
Sorry to re-open an old issue, but [popups are back](https://www.reddit.com/r/9anime/comments/butl32/popup_with_ublock_origin/?utm_source=share&utm_medium=ios_app&utm_name=ios_share_flow_optimization&utm_term=enabled) (links to Reddit post about the issue).

**Comment by okiehsch** [comment]
Does 
`prettyfast.to##+js(abort-current-inline-script.js, Math, zfgloaded)`
work for you?

**Comment by SheepKid12** [comment]
Just tested, and yes, it works.
