### ISSUE TITLE
Gamepedia 

### ISSUE THREAD

**Issue by itsamemarkus** [uBlockOrigin/uAssets#5565]
### URL(s) where the issue occurs

https://pathofexile.gamepedia.com/Winter_Orb
https://pathofexile.gamepedia.com/Infused_Channelling_Support
https://pathofexile.gamepedia.com/Greater_Multiple_Projectiles_Support

### Describe the issue

Path of Exile wiki is one of the only sites that shows ads for me with uBlock enabled.

### Screenshot(s)

![exilewikiscreenshot](https://user-images.githubusercontent.com/34944988/57537364-67ecfc00-7346-11e9-90d3-50e7acf4a77d.png)

### Versions

- Browser/version: Chrome 74.0.3729.131 (Windows 64 bit)
- uBlock Origin version: 1.18.16

### Settings

- active for incognito

### Notes

I tried to manually block the ads, they showed up again.

**Comment by yourduskquibbles** [comment]
`Gamepedia` uses `Instart Logic` - Install [uBlock Origin Extra](https://chrome.google.com/webstore/detail/ublock-origin-extra/pgdnlhfefecpicbbihgmbmffkjpaplco) if using Chrome.

See https://github.com/uBlockOrigin/uAssets/issues/5229#issuecomment-476631690
& https://github.com/uBlockOrigin/uAssets/issues?utf8=%E2%9C%93&q=is%3Aissue+gamepedia
