### ISSUE TITLE
http://www.torrentbit.net/

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#557]
### URL(s) where the issue occurs

`http://www.torrentbit.net/`

### Describe the issue

Unblocked popup if you click around.

**Comment by SMed79** [comment]
`||pussl4.com^$third-party`
or
`$script,third-party,domain=torrentbit.net`

admeasures ad servers https://forums.lanik.us/viewtopic.php?f=62&t=33320
