### ISSUE TITLE
imagetwist.com

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5571]
URL(s) where the issue occurs

`https://imagetwist.com/wu3xi54vp17o/Adorable-Teens.net_ATB_6411__46_.jpg`

Describe the issue

Incorrect Blocking

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 74 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.18.16

Settings

Default

**Comment by KiLL4FuNK** [comment]
image can not be seen

**Comment by okiehsch** [comment]
https://github.com/easylist/easylist/commit/94a4e3e77a13f3adea2f73707a65e4f1596671af
