### ISSUE TITLE
golem.de

### ISSUE THREAD

**Issue by Scunkaneli** [uBlockOrigin/uAssets#5575]
### URL(s) where the issue occurs

`https://www.golem.de/ticker/`

### Describe the issue

Scroll down to the entry "LED-Entwickler: Osram bringt Licht in die Augmented Reality". Indicated by "Anzeige" (=ad), this is a link that leads to an advertisement article.

### Screenshot(s)

https://i.imgur.com/nOKNmia.png

### Versions

- Browser/version: Chrome 74
- uBlock Origin version: 1.18.16

### Settings

Default

### Notes

Works with `www.golem.de##span[class*="icon-addy"]:xpath(..):xpath(..):xpath(..)`, maybe there is something more elegant?

**Comment by mapx-** [comment]
maybe it's enough
`golem.de##.sp-article`

to be sure I'll add:
`golem.de##.sp-article:has(span:matches-css-before(content:/Anzeige/i))`
