### ISSUE TITLE
General ask about Ublock Origin support on Edge legacy.

### ISSUE THREAD

**Issue by seba2282** [uBlockOrigin/uAssets#5576]
### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

Hello, 
After how one person said between his words about he will not support Ublock Origin for Microsoft Edge on old source, 
I have one question. It is possible support Ublock Origin for Edge legacy by you, @gorhill? I know, it is non sense question, but more people won't go to chromium Edge, bc it isn't final version. Final maybe will be after half year or later. Much people love Ublock Origin but they won't be testers. 
It was nice if here was Ublock Origin support for EdgeHtml too. Thank you for understanding. 
Best Regards

**Comment by okiehsch** [comment]
This repo is about filter issues it is not a general support forum.
https://www.reddit.com/r/uBlockOrigin

**Comment by seba2282** [comment]
I haven't Reddit and it was reason, why asked here about support Ublock Origin on MS Edge on EdgeHtml.
