### ISSUE TITLE
UBO filter no longer working on Firefox was working up till yesterday

### ISSUE THREAD

**Issue by Doorstop2** [uBlockOrigin/uAssets#5577]
### URL(s) where the issue occurs

**://uaw3vx1k0ttq74u9b2zfvt768eebh1.ext-twitch.tv**
**://wi08ebtatdc7oj83wtl9uxwz807l8b.ext-twitch.tv**
**://24u62kim5mn0slhwigdt7v4ybkwef5.ext-twitch.tv**
**://jrdw4tksb5f3442l2pas15ykvzu2i1.ext-twitch.tv**

**Removed HTTPS**

### Describe the issue

So those links above i was filtering such as

**||xxxxx://uaw3vx1k0ttq74u9b2zfvt768eebh1.ext-twitch.tv** which would remove a element on twitch below `extensions` now up till the other day this was working fine on Firefox but now since yesterday they have stopped working in the UBO logs i can see it shows in the list but it is not attempting to block it. So i also tested chrome and it works perfect with the same rules.

### Screenshot(s)

This link shows both what happens on Firefox's side & Chrome working/not working
https://imgur.com/a/3O6VxSQ

### Versions

- Browser/version: Firefox 65.0.5
- uBlock Origin version: 1.19.2

### Settings

none just those custom filters 

### Notes

Tested on chrome UBO version: 1.18.16 Seems to be working check imgur links above for debug

**Comment by bogachenko** [comment]
```
://uaw3vx1k0ttq74u9b2zfvt768eebh1.ext-twitch.tv
://wi08ebtatdc7oj83wtl9uxwz807l8b.ext-twitch.tv
://24u62kim5mn0slhwigdt7v4ybkwef5.ext-twitch.tv
://jrdw4tksb5f3442l2pas15ykvzu2i1.ext-twitch.tv
```
this value is dynamic. it's changing. to block the banner on twitch use
```
twitch.tv##a[href*="gg.bet"] > img
```

**Comment by Doorstop2** [comment]
I'm a little lost here i attempted to use those filters you posted but they don't seem to work what has changed that || no longer works? it still does on chrome but i can see the version difference i just want it to be removed just like the vids above show this stops it from using cpu/gpu resources

**Comment by bogachenko** [comment]
give me a link to twitch with a million banners and frames

**Comment by Doorstop2** [comment]
https://www.twitch.tv/timmac

my main thing is i'm blocking these `leaderboards` like the one on here https://www.twitch.tv/timmac

the stream elements one is what i want gone but it's like aextention on the site not just a simple link to block so doing 
**||https://uaw3vx1k0ttq74u9b2zfvt768eebh1.ext-twitch.tv**
removes the entire thing but no longer does on Firefox still does on chrome

**Comment by mapx-** [comment]
correct filter
`||uaw3vx1k0ttq74u9b2zfvt768eebh1.ext-twitch.tv`

**Comment by Doorstop2** [comment]
omg that works

**Comment by mapx-** [comment]
`|https` and not `||https`

**Comment by Doorstop2** [comment]
omg thank you man shit was driving me nuts i suppose chrome will be getting this change also?
