### ISSUE TITLE
pornid.xxx

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#5581]
### Describe the issue

[CSP filter prevents video thumbnails from loading.
`||pornid.xxx^$csp=script-src 'unsafe-inline' 'unsafe-eval' https://www.pornid.xxx/player/kt_player.js`]

### Versions

- Browser/version: [Chrome v74]
- uBlock Origin version: [1.19.2]

### Settings

- [default]

**Comment by okiehsch** [comment]
I don't see any issue without the csp, @mapx- is the csp still needed on your end?

**Comment by mapx-** [comment]
I was testing, it seems can be removed
