### ISSUE TITLE
Ad popup on click on index site

### ISSUE THREAD

**Issue by FreddieDev** [uBlockOrigin/uAssets#5584]
### URL(s) where the issue occurs
`http://indexof.ir/series/the-wire`

### Describe the issue
When page loads, first click opens ad in new tab.

### Versions
- Browser/version: Chrome 74.0.3729.131 (Official Build) (64-bit)
- uBlock Origin version: 1.19.2

### Settings
Filter to fix: 
`||mpqfzyh.com/bf/a3/27/bfa3275c2fbe8e35ea415ac7009114d0.js$script,domain=indexof.ir`

**Comment by krystian3w** [comment]
Too randomized name...?

**Comment by FreddieDev** [comment]
That's what I thought - I wondered what the correct way to go about targeting this is. Perhaps you could block the entire mpqfzyh.com domain, if it is only for hosting ad scripts? It's entirely unrelated to the site I found importing the script.

**Comment by krystian3w** [comment]
If this is not "1 day" domain (gone / chanded quickly to new). "The best" should by scriplet to abort this code.

**Comment by bogachenko** [comment]
generally it is a bad domain in easylist France it is blocked at all
