### ISSUE TITLE
fstore.biz

### ISSUE THREAD

**Issue by BMD4E** [uBlockOrigin/uAssets#5585]
### URL(s) where the issue occurs

`https://fstore.biz/file/A93050F30DBA`

### Describe the issue

Request for countdown booster

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50082021/57615822-e92dd400-757c-11e9-8692-67d6fefbadb0.png)

### Versions

- Browser/version: Chrome 74.0.3729.108
- uBlock Origin version: 1.18.16

### Settings

- Default

### Notes

Same owner and site as of 2speed.net

**Comment by krystian3w** [comment]
I have anti-adblock "wall" on Android with Firefox 65 + uBo 1.19.2 + Nano Defender.
