### ISSUE TITLE
pornsexer.com [ADS] [NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5586]
URL(s) where the issue occurs

`https://pornsexer.com/videos/50180/hot-teen-sluts-tight-leggings-jiggly-butts-thong-line/`

Describe the issue

ADS

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 74 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.18.16

Settings

Default

**Comment by dumbusernameidk** [comment]
ads are back.

**Comment by ghajini** [comment]
Antiadblock
Firefox android stable, ublock origin stable

**NSFW**
`https://m.pornsexer.xxx/videos/169302/sexy-teen-with-awesome-body-enjoying-sex/`

Screenshot=

`https://user-images.githubusercontent.com/20338483/103454380-56214f00-4d09-11eb-8aa7-ca5708eca594.png`

**Comment by ghajini** [comment]
@mapx- 
What's this message translate to

https://user-images.githubusercontent.com/20338483/103454889-34769680-4d0e-11eb-957d-3b2361c0ec45.jpg

This is shown on desktop browsers(pornsexer.com)

I can't read russian

**Comment by mapx-** [comment]
@ghajini In these cases you need an OCR "translation":

- go to `https://www.newocr.com/`
- upload the image with that russian text
- select russian language
- click OCR
- text => `Доступ к материалам сайта ограничен` => `Access to site materials is limited`

However, now the site is working fine

**Comment by ghajini** [comment]
Thank you @mapx- that message is seen on my side ,may be site is blocking my ip access
