### ISSUE TITLE
google contacts - hide "Overall, how satisfied are you with the Contacts experience?" annoyance

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#5590]
https://contacts.google.com/

how do I hide "Overall, how satisfied are you with the Contacts experience?" on the new google contacts site please?

Screenshot: https://i.imgur.com/f4ARM99.jpg

- uBlock Origin version: 1.19.2

**Comment by patrickdrd** [comment]
`contacts.google.com###hats2-iframe`  ??

**Comment by mapx-** [comment]
I cannot reproduce the issue. If that filter is working for you keep it as custom filter.
