### ISSUE TITLE
Fixed in EasyList/EasyPrivacy

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#5591]
`! https://forums.lanik.us/viewtopic.php?p=146765#p146765`
`/adcase.$badfilter`
`/adcase.$domain=~adcase.ru`
https://github.com/easylist/easylist/commit/a88a2f72b978adf8f74efbbfeefde17086c35c67

`! https://www.reddit.com/r/uBlockOrigin/comments/bgh4om/client_webpage_blocked_by_ublockorigin/`
`/openad.$badfilter`
`/openad.$domain=~openad.lv`
`.openad.$badfilter`
`.openad.$domain=~openad.lv`
https://github.com/easylist/easylist/commit/9d6bc05b7f6141f53abadf26a514c05f269de503

`! https://forums.lanik.us/viewtopic.php?f=64&t=42945`
`/estat.$domain=~estat.stat.ee,badfilter`
`/estat.$domain=~estat.ly|~estat.stat.ee`
https://github.com/easylist/easylist/commit/2f67b1e16760802c34503c96f45f7563846af4c6

**Comment by mapx-** [comment]
thx
