### ISSUE TITLE
Ublock Origin Blocks Too Much Content on 9now

### ISSUE THREAD

**Issue by Firedingo** [uBlockOrigin/uAssets#56]
9now.com.au

Ublock Origin Blocks the ads on 9now but it also blocks all the video content from loading. Simply turning off Ublock Origin allows the content as well as the ads to load.
This might be able to be fixed I am unsure but it is annoying. I've included 2 screenshots of the site with Ublock Origin active and disabled demonstrating the issue and indicated to the Ublock Icon.

### Screenshot(s)
![ublockoerror](https://cloud.githubusercontent.com/assets/15248850/15679132/1e45b372-2794-11e6-9ff8-4d4630c2854e.png)

![ublockoerror1](https://cloud.githubusercontent.com/assets/15248850/15679183/478ad226-2794-11e6-96ca-476c4ece0685.png)

### Versions

- Browser/version: Firefox 46.0.1
- uBlock Origin version: 1.7.0

### Settings

- No settings changed. At most a few element filters for a different site have been added.

### Notes

I have multiple Add-ons so in order to confirm that it was in fact Ublock and not another add-on as has been the case on other sites, I loaded a 2nd browser Light, A firefox Fork. Version: 41.0
and installed Ublock Origin into it and loaded the site and the issue occurred once again.

**Comment by gorhill** [comment]
I can't load a page with the URL you provided (`9now.com.au`).

**Comment by IDKwhattoputhere** [comment]
Me neither. (`ERR_CONNECTION_TIMED_OUT` aka `The connection has timed out`)
Which is weird because allegedly it's up.
http://isup.me/9now.com.au
http://www.isitdownrightnow.com/9now.com.au.html

**Comment by Firedingo** [comment]
That's strange as it most definitely is up as I was using moments before posting this issue.
Checked just now and yup it's up for me.

Try this link as it's working for me at least?
[https://www.9now.com.au/60-minutes/2016/episode-16](url)

**Comment by gwarser** [comment]
Probably geoblocked for Australia https://9now.zendesk.com/hc/en-us/articles/216163487-Out-of-town

**Comment by Firedingo** [comment]
Oh yeah......I forgot they love...just freaking love to geoblock everything inside and out of the country if they can :/
I'm sorry for that. My country lives in the stone age at times -_-

**Comment by IDKwhattoputhere** [comment]
> Try this link as it's working for me at least?

Please don't post clickable URLs.
I used an Australian VPN exit and got the site to load. Using [the logger](https://github.com/gorhill/uBlock/wiki/The-logger) I see two blocked scripts and allowing this one worked for me:
`@@||secure-dcr.imrworldwide.com/novms/js/2/ggcmb500.js$script,domain=9now.com.au`
Try the above filter (best after disabling all other blocking related add-ons, antivirus etc.).

**Comment by Firedingo** [comment]
Ah. Sorry I apologize about the link

**Comment by IDKwhattoputhere** [comment]
Sure, but does the filter work?

**Comment by Firedingo** [comment]
Sorry about the delay replying. That seems to let the content load yes. Thank you :)

**Comment by gorhill** [comment]
What is the filter blocking the resource `secure-dcr.imrworldwide.com/novms/js/2/ggcmb500.js`?

**Comment by Firedingo** [comment]
I'm not sure.

It seems the site identifies the filter blocking ads but doesn't seem to impact the loading of the content.
![9nowadblocker](https://cloud.githubusercontent.com/assets/15248850/15712002/df2343f6-2853-11e6-9b0b-b981a2c940ab.png)

**Comment by IDKwhattoputhere** [comment]
> I'm not sure.

How? Use the logger.
There's a filter `||imrworldwide.com^` in Peter Lowe’s but also `||imrworldwide.com^$third-party` in EasyPrivacy so I'd say report it [here](https://forums.lanik.us/viewforum.php?f=64&sid=bcf652ae1e8ade0d7407169b7b0cd788), @Firedingo, so it can be fixed.

**Comment by Firedingo** [comment]
I looked at the logger. I'm not completely sure what it says. I'm not always that good at understanding things. But thank you. If you say that's where I should report it then I will do that :)

**Comment by gorhill** [comment]
> There's a filter ||imrworldwide.com^ in Peter Lowe’s but also ||imrworldwide.com^$third-party in EasyPrivacy so I'd say report it here, @Firedingo, so it can be fixed.

Exactly, if the issue requires an exception filter in EasyPrivacy, this is the preferred fix. If the issue was specific to Peter Lowe's, the fix would be here.

**Comment by IDKwhattoputhere** [comment]
@Firedingo Read what I linked: https://github.com/gorhill/uBlock/wiki/The-logger#finding-from-which-lists-a-static-filter-originates
Open the logger and then load the 9now video site.
Red means a filter has been applied. Click the filter and then it will show you which list it comes from. The logger will also allow you to create filters like the expcetion filter I created above.

**Comment by Firedingo** [comment]
Ah ok. Thank you. That's very helpful :)

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/131fa4dbeff74ed2e97f067e841e4c31fe57248f
