### ISSUE TITLE
freeupload.info and uploadfree.info

### ISSUE THREAD

**Issue by BMD4E** [uBlockOrigin/uAssets#5604]
### URL(s) where the issue occurs

```
https://freeupload.info/file/E45A51CF5C95
https://uploadfree.info/file/E45A51CF5C95
```

### Describe the issue

There is anti-adblock message that tells me to disable adblock
Also request for countdown booster

### Screenshot(s)

![image](https://user-images.githubusercontent.com/50082021/57771311-a3a30f80-7712-11e9-9bfe-e6a0a573b8b2.png)

![image](https://user-images.githubusercontent.com/50082021/57771361-ca614600-7712-11e9-9a81-38f2219e33b0.png)

### Versions

- Browser/version: Chrome 74.0.3729.108
- uBlock Origin version: 1.18.16

### Settings

- Default

### Notes

None

**Comment by mapx-** [comment]
test
```
freeupload.info,uploadfree.info##+js(setInterval-defuser.js)
freeupload.info,uploadfree.info##+js(abort-current-inline-script.js, document.getElementById, undefined)
freeupload.info,uploadfree.info##+js(nano-setTimeout-booster.js, , 1400)
```

**Comment by BMD4E** [comment]
Works perfectly!
Thanks
