### ISSUE TITLE
piktag.net

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#5605]
### URL(s) where the issue occurs

- `https://piktag.net/tag/portugalball`

### Describe the issue

- Anti-Adblock Script - BlockAdBlock

### Versions

- Browser/version: Firefox 66.0.5
- uBlock Origin version: 1.19.2

### Settings

- All Filters Enabled + I don't care about cookies. Regional Filters, uBlock Filters Experimental, and Anti-Facebook List disabled.

**Comment by IThinkIAmCool** [comment]
@mapx- Could you take a look at the link given in the issue?

**Comment by IThinkIAmCool** [comment]
After clicking on the image or whatever I got redirected to `https://greenmode.biz/?p=gjswimdfg45gi3bpgmzdqojs&sub4=fandome`

**Comment by mapx-** [comment]
it seems to be a spam page now

`piktag.net###parent_popup`

**Comment by JobcenterTycoon** [comment]
so move to badware?
