### ISSUE TITLE
muhammadyoga.me

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#5606]
### URL(s) where the issue occurs

`[https://muhammadyoga.me/links/post/3-5-countries-with-the-most-weird-facts-in-the-world?a=I7ijG788t]`

### Describe the issue

[Site wont load until we turn off adblocker addon]

### Screenshot(s)

[https://imgur.com/gJyo63j]

### Versions

- Browser/version: [Firefox Quantum 66.0.5 x86]
- uBlock Origin version: [1.19.2]

### Settings

- [https://pastebin.com/W0LNH5Af]

### Notes

[Site load when i turned off uBO]

**Comment by JobcenterTycoon** [comment]
The filter `muhammadyoga.me##+js(addEventListener-defuser.js, load, onload)` works for me
