### ISSUE TITLE
naturalhealthy.xyz

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#5608]
### URL(s) where the issue occurs

`[https://naturalhealthy.xyz/6-best-foods-for-men-over-50/]`

### Screenshot(s)

[![2019-05-16_200539](https://user-images.githubusercontent.com/9832875/57857033-7e002e00-7818-11e9-8eb3-e4d045fd5a1e.png)]

Rest same as this https://github.com/uBlockOrigin/uAssets/issues/5606

**Comment by JobcenterTycoon** [comment]
The filters`@@naturalhealthy.xyz^$generichide` and `naturalhealthy.xyz##.adsbygoogle` works for me
