### ISSUE TITLE
limetorrents.cc

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#561]
### URL(s) where the issue occurs

`https://www.limetorrents.cc/-torrent-4585232.html`

### Describe the issue

Circled all things that need to be blocked.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/28446363-582e7966-6d98-11e7-9de3-1611e8b03482.png)

**Comment by SMed79** [comment]
```
##a[href*="/rel/index.cfm?RST="]
||onclickpulse.com^$third-party
```

**Comment by terrorist96** [comment]
My suggested filters to block all of the things:
Stream:
`www.limetorrents.cc##.torrentinfo > table > tbody > tr:nth-of-type(4) > td:nth-of-type(1)`
Movies4u:
`www.limetorrents.cc##.torrentinfo > table > tbody > tr:nth-of-type(4) > td:nth-of-type(2)`
Direct download:
`www.limetorrents.cc##.downloadareabig:nth-of-type(3)`
VPN ad:
`www.limetorrents.cc###content > table:nth-of-type(2)`

**Comment by terrorist96** [comment]
It's unblocked again. :\

**Comment by terrorist96** [comment]
@okiehsch Stream via Movie4u ad is visible again.

**Comment by okiehsch** [comment]
Thx.
