### ISSUE TITLE
Gelbooru.com (again - NSFW)

### ISSUE THREAD

**Issue by Lebon14** [uBlockOrigin/uAssets#5611]
### URL(s) where the issue occurs

`https://gelbooru.com/index.php?page=post&s=view&id=4737613` (NSFW)
Should be on any (at least) explicitely rated images.

### Describe the issue

Ads shows up.

### Screenshot(s)

https://i.gyazo.com/557b9f96764deb3cc0790194b1efa29d.png (semi-SFW screenshot)

### Versions

- Browser/version: Firefox 66.0.4
- uBlock Origin version: v1.19.2

### Settings

See screenshots:
https://i.gyazo.com/55c5c7f68673bf18f44c438310cfeca6.png
https://i.gyazo.com/1e0b9e911792747a640594378cc653d3.png
(And too much "My Filters"...)

### Notes

Started showing up again today along with some text I never seen before. I didn't try to block them myself. I didn't try to reset cache and cookies though...

Cheers.

**Comment by mapx-** [comment]
You could remove aak list from your custom lists => outdated no longer maintained.

**Comment by lain566** [comment]
The same issue to `thedoujin.com`
`http://thedoujin.com/index.php/categories/242031`
