### ISSUE TITLE
homeporno.pro(NSFW)

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uAssets#5612]
### URL(s) where the issue occurs

`http://homeporno.pro/4693-lyubov-starshey-sestry.html`

### Describe the issue

Miner `omine.org`

### Screenshot(s)

![Безымянный](https://user-images.githubusercontent.com/28482376/57904691-8f7b2180-787c-11e9-9435-382d607c4ea2.png)

### Versions

- Browser/version: [Opera|Beta]
- uBlock Origin version: [1.19.3b4]

### Settings

![Безымянный](https://user-images.githubusercontent.com/28482376/57904799-f567a900-787c-11e9-8fb6-dd102e79ebcb.png)

**Comment by okiehsch** [comment]
`omine.org` is already blocked in `EasyPrivacy` which is enabled by default.
I will disable the miner on the site.

**Comment by PoRtvine** [comment]
EasyPrivacy creates many problems in the RU & UA internet segment.
Thanks.
