### ISSUE TITLE
shortzon.com & healthfary.com

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#5616]
### URL(s) where the issue occurs

- `https://shortzon.com/zAm2`
- `https://healthfary.com/zAm2`

### Describe the issue

- Anti-Adblock Script - Customized alongside BlockAdBlock

### Versions

- Browser/version: Firefox 66.0.5
- uBlock Origin version: 1.19.2

### Settings

- All Filters Enabled + I don't care about cookies. Regional Filters, uBlock Filters Experimental, and Anti-Facebook List disabled.

### Notes

Shortzon.

**Comment by smed79** [comment]
domain changed to `healthfary.com`
