### ISSUE TITLE
magnetdl.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#562]
### URL(s) where the issue occurs

`http://www.magnetdl.com/file/1232467/eminem-straight-from-the-lab-.flac-version/`

### Describe the issue

PIA ad

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/28446403-8a9c6930-6d98-11e7-81be-fa572a66e9f2.png)

**Comment by SMed79** [comment]
`||magnetdl.com/img/pia.png`
or
`magnetdl.com##a[href^="https://www.privateinternetaccess.com/"]`

**Comment by okiehsch** [comment]
The suggested filters can be added to Easylist.
fyi @ryanbr
