### ISSUE TITLE
Hidden publication date?

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#5623]
`https://www.downloadsource.es` - center column
`https://www.downloadsource.es/desactivar-mensaje-de-traduccion-en-chrome-android-iphone/n/15244/` - header
`https://www.downloadsource.net/` - center column
`https://www.downloadsource.net/how-to-fix-nzxt-kraken-x61-x62-water-pump-stoppednot-working/n/15290/` - header

---

sugestion:

```
downloadsource.*##dd.date, p.date:style(display: block !important;)
```

or

```
downloadsource.*##.date:not(dt):style(display: block !important;)
```

**Comment by mapx-** [comment]
I don't understand what do you want to hide. Ads ? or is it really an annoyance ?

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/58003237-a752df80-7ae0-11e9-9019-2ae84b344b79.png)

After adding the proposed filter.
![image](https://user-images.githubusercontent.com/16838044/58003286-c5204480-7ae0-11e9-9749-df595ea0227e.png)

**Comment by mapx-** [comment]
oh, we can consider it as breakage.

**Comment by krystian3w** [comment]
Need revert, hidden with disabled uBO.

**Comment by llacb47** [comment]
Also it doesn't even work because the page is using `!important`:
![image](https://user-images.githubusercontent.com/16567977/81484754-30918380-9216-11ea-9fef-0d1187618402.png)

**Comment by krystian3w** [comment]
`!important;` in devtools is not as problem for uBo, for Nano AdBlocker with userCSS disabled does.

**Comment by llacb47** [comment]
OK, so it works in uBO but not Nano, weird.
