### ISSUE TITLE
derstandard.at [privacy-wall]

### ISSUE THREAD

**Issue by Scunkaneli** [uBlockOrigin/uAssets#5626]
### URL(s) where the issue occurs

`https://derstandard.at/2000103294525/Kuessel-ueber-Strache-Da-gab-es-einige-lustige-Auftritte-vielleicht`

### Describe the issue

You need to accept privacy notice before being redirected to the article.

### Screenshot(s)

https://i.imgur.com/T2Tuqxd.png

### Versions

- Browser/version: FF 67
- uBlock Origin version: 1.19.2

### Settings

- Default

### Notes

Probably related to #2352

**Comment by okiehsch** [comment]
It is basically the same issue as https://github.com/uBlockOrigin/uAssets/issues/2352.
This can't be fixed in `uAssets`,
`Nano` has a scriptlet that auto accepts cookies but the inclusion of that scriptlet into `uBO` was [declined](https://github.com/uBlockOrigin/uAssets/pull/2099).

**Comment by Scunkaneli** [comment]
Ok thank you! 
Sorry I did not really understand what Nano Defender had to do with #2352.
