### ISSUE TITLE
teltarif.de [popup, bad filter]

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5627]
### URL(s) where the issue occurs

`https://teltarif.de`

### Describe the issue

When you click on the blue area you get a popup, ads not correctly blocked.

### screenshots
Without Adblocker:
<img width="1903" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/58022938-df711700-7b0e-11e9-8406-f633477cd3c0.PNG">

With Adblock enabled:
<img width="1906" alt="Unbenannt1" src="https://user-images.githubusercontent.com/48647394/58022963-ec8e0600-7b0e-11e9-9332-4964068da71d.PNG">

Site without any breakage:
<img width="1907" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/58023645-991cb780-7b10-11e9-989d-a14bcf0848eb.PNG">

### Versions

- Browser/version: Firefox 66.0.5
- uBlock Origin version: v1.19.2

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3198029/Settings.txt)

**Comment by mapx-** [comment]
```
teltarif.de##.ttSkyR
teltarif.de##.ttWall.ttfull
```
or (still blue but the area is not clickable anymore)
```
teltarif.de#@#.ttWallTD
teltarif.de##+js(abort-on-property-read.js, ttWallClick)
```

**Comment by JobcenterTycoon** [comment]
> 
> 
> ```
> teltarif.de##.ttSkyR
> teltarif.de##.ttWall.ttfull
> ```
> 
> or (still blue but the area is not clickable anymore)
> 
> ```
> teltarif.de#@#.ttWallTD
> teltarif.de##+js(abort-on-property-read.js, ttWallClick)
> ```

its works, but is this possible to block it completly so its looks like the third picture one?
To reproduce to get this:
1. go to `teltarif.de`
2. Disable adblocker
3. reload
4. enable adblocker and reload again
5. click on a random article
now you have a site without breakage and no ads.

**Comment by mapx-** [comment]
Do you mean the home page background to be as an article page ? Otherwise I get no breakage with both solutions above.

**Comment by JobcenterTycoon** [comment]
With filters (and the white space is part of the screenshot)
<img width="1910" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/58037922-e60f8680-7b2e-11e9-8aa3-124a79648e21.PNG">

Site without blue background and no ads
<img width="1908" alt="Unbenannt1" src="https://user-images.githubusercontent.com/48647394/58037923-e60f8680-7b2e-11e9-9115-89e89e598196.PNG">

i think its must be a script thats make the background blue.
When its no script and its not fixable you can close the issue.

**Comment by mapx-** [comment]
I provided 2 sets of filters.
Did you test separately ?

**Comment by JobcenterTycoon** [comment]
no

**Comment by mapx-** [comment]
It's exactly what you have to do.

**Comment by JobcenterTycoon** [comment]
OK this are the best solution

**Comment by mapx-** [comment]
Which one ? ;)

**Comment by JobcenterTycoon** [comment]
`teltarif.de##.ttWall.ttfull` `teltarif.de#@#.ttWallTD` `teltarif.de##+js(abort-on-property-read.js, ttWallClick)` at once

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/75a03aa87f99141d3237d9e06cd838cf9f2d7eb6
