### ISSUE TITLE
tweaktown.com

### ISSUE THREAD

**Issue by doclucas** [uBlockOrigin/uAssets#563]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[http://www.tweaktown.com/reviews/8040/asrock-fatal1ty-z270-gaming-k6-motherboard-review/index11.html]`

### Describe the issue

[The  page selection dropdown menu doesn't work when I am using ublock origin with either easylist or easylist without element blocking.
When disabling easylist, the page selection dropdown menu works fine.
This issue has been reported in easylist forums first, and they advised to post it here.
Original forum thread: https://forums.lanik.us/viewtopic.php?p=121608]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: [Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)]
- uBlock Origin version: [uBlock Origin v1.13.2]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Settings are default. Original analysis can be found here: https://forums.lanik.us/viewtopic.php?p=121608]

**Comment by okiehsch** [comment]
![unbennnt](https://user-images.githubusercontent.com/16838044/28472325-71e11e7e-6e40-11e7-92aa-9aa384b997f3.JPG)
on my end with uBO default settings if I hover over "Reviews". 
Seems to work or should it look differently?

**Comment by doclucas** [comment]
I mean the page selection dropdown:
https://lh3.googleusercontent.com/-3te2RO59_A8/WXIxmb3sabI/AAAAAAAAJCI/BGEQmy46izAT4nOd_QuszccqwJbTTahyACHMYCw/s0/chrome_2017-07-21_23-53-44.png

**Comment by okiehsch** [comment]
Sorry for the confusion, does
`@@||cdn.jsdelivr.net^$script,domain=tweaktown.com`
work for you?

**Comment by doclucas** [comment]
Thanks.
I put this line in the "My filters" tab and then clicked "Apply changes" and it seems to fix the issue.
Is that the right place to put it?
Should I also click "Import and append" button at the bottom of that window?

**Comment by okiehsch** [comment]
Force an update of the `uBO unbreak` filter list. 
https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters#update-now

**Comment by okiehsch** [comment]
And  if you add a filter to "My filters" tab you only need to click "Apply changes",, nothing more.

**Comment by doclucas** [comment]
perfect! thank you so much! :)
