### ISSUE TITLE
linkszone.in [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5632]
URL(s) where the issue occurs

`https://linkszone.in/VNtkPD`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 74 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.19.2

Settings

Default

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/84580704/120098861-f35da380-c140-11eb-91d5-f111402cea4d.png)
@mapx- @uBlock-user @okiehsch
