### ISSUE TITLE
http://www.clubedohardware.com.br/forums/ anti adb

### ISSUE THREAD

**Issue by mapx-** [uBlockOrigin/uAssets#564]
### URL(s) where the issue occurs
`http://www.clubedohardware.com.br/forums/`

### Describe the issue
anti adblocking overlay / message

### Versions

- Browser/version: chrome 60
- uBlock Origin version: 1.13.8

Working filter
`clubedohardware.com.br##script:inject(overlay-buster.js)`

or
`||clubedohardware.com.br/cdn-cgi/apps/head/*4.js$script,domain=clubedohardware.com.br`
or
`@@||update.noadblock.net/testMethodsRemote.min.js$script,domain=clubedohardware.com.br`

**Comment by okiehsch** [comment]
Same issue as https://github.com/gorhill/uBlock/issues/2804

**Comment by mapx-** [comment]
needing updating:

could be:
`clubedohardware.com.br##script:inject(abort-on-property-read.js, _0xde46)`

**Comment by gorhill** [comment]
Doesn't this work?

    ||clubedohardware.com.br/cdn-cgi/apps/head/02LF67km1GrnR94cjKxRMVIBL3w.js

**Comment by mapx-** [comment]
yes
`||clubedohardware.com.br/cdn-cgi/apps/head/$script`

**Comment by gorhill** [comment]
Actually, given this is a Cloudflare plug-in injected early in the page, and the only one, this also works:

    ||clubedohardware.com.br/cdn-cgi/apps/head/$script

**Comment by gorhill** [comment]
So will this be added to EasyList? If so, will the exception filter `@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$domain=clubedohardware.com.br` be removed?

**Comment by mapx-** [comment]
Well, lately no so many filters are / were added to easylist (especially no such filters fixing anti adb). So, I doubt will be add to EL.
Having a centralized list (like EL) seems a vulnerabilty in these times.  Probably (if doable) a p2p list would be the solution.
