### ISSUE TITLE
gq-magazine.co.uk

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uAssets#5643]
### URL(s) where the issue occurs

`https://www.gq-magazine.co.uk/`

### Describe the issue

AdBlock detected

### Screenshot(s)
![2019-05-22_135535](https://user-images.githubusercontent.com/28482376/58169505-96010300-7c99-11e9-9164-d81afe2cb0fc.png)

**It's tracking?**
![2019-05-22_140051](https://user-images.githubusercontent.com/28482376/58169773-40792600-7c9a-11e9-97b6-bcdd12e1075d.png)
`geolocation.onetrust.com`
### Versions

- Browser/version: [Opera|Beta]
- uBlock Origin version: [1.19.3b11]

### Settings

![2019-05-22_135935](https://user-images.githubusercontent.com/28482376/58169621-de202580-7c99-11e9-8732-8abc5cf454a2.png)

**Comment by mapx-** [comment]
It seems to be only annoyance, otherwise the site is readable, right ?

**Comment by PoRtvine** [comment]
Yes

**Comment by bogachenko** [comment]
`@@*/ads.js$domain=gq-magazine.co.uk`
