### ISSUE TITLE
frustfrei-lernen.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5644]
### URL(s) where the issue occurs

`https://www.frustfrei-lernen.de/biologie/biologie-uebersicht.html`

### Describe the issue

Unblocked Picture Ads

### Screenshot(s)

<img width="947" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/58192683-9f9e6100-7cc1-11e9-8190-c7224172c71b.PNG">

### Versions

- Browser/version: Firefox 67
- uBlock Origin version: uBlock Origin v1.19.2

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3208415/Settings.txt)

**Comment by mapx-** [comment]
I cannot reproduce the ads.
Purge all caches and then click "update now". Test again.

**Comment by JobcenterTycoon** [comment]
> 
> 
> I cannot reproduce the ads.
> Purge all caches and then click "update now". Test again.

It doesn't work. is this because of the new update to Firefox 67.0?

**Comment by mapx-** [comment]
try
`frustfrei-lernen.de##+js(set-constant.js, Criteo, noopFunc)`

**Comment by JobcenterTycoon** [comment]
It doesn't work for me :( im reinstalled ublock and restarted the browser, but the ads still appears. Im tested another sites but these are still ok.

**Comment by mapx-** [comment]
Now I can reproduce but not consistently.
@okiehsch  when I delete all cookies / localstorage stuff in FF 67, refresh the page, then (only on the first refresh) I get a page with a clickable red background.

**Comment by mapx-** [comment]
for the moment something like (but could break some functionalities)
```
||frustfrei-lernen.de^$inline-script
frustfrei-lernen.de##.noContentBannerArea
```

**Comment by okiehsch** [comment]
Should work now.

**Comment by okiehsch** [comment]
> It doesn't work. is this because of the new update to Firefox 67.0?

No, they updated their re-insertion script and the Firefox fix for those sites needed to be updated because of it.
The Chromium/Chrome fix still works.

**Comment by JobcenterTycoon** [comment]
Thanks. But can you please add `frustfrei-lernen.de##.noContentBannerArea` for the empty placeholder please?
