### ISSUE TITLE
deezer.com

### ISSUE THREAD

**Issue by Neurotoxin001** [uBlockOrigin/uAssets#5649]
### URL(s) where the issue occurs
`https://www.deezer.com/en/playlist/your_playlist_id`

### Describe the issue
When I click "edit" on my playlist - I can't see popup of edit menu, because of this:
`deezer.com##.modal-backdrop`
Or maybe this:
`deezer.com##.modal-wrapper`
In
`uBlock filters – Annoyances`
When I disable `uBlock filters – Annoyances` all is fine.

### Versions

- Browser/version: Google Chrome 74.0.3729.157
- uBlock Origin version: 1.19.2

**Comment by mapx-** [comment]
these should work, test on your side:
```
deezer.com#@#.modal-backdrop
deezer.com#@#.modal-wrapper
deezer.com###modal_login:xpath(../..)
```

**Comment by Neurotoxin001** [comment]
Yes, this is works.

**Comment by DandelionSprout** [comment]
The entries that were in `uBlock Filters - Annoyances` were written before the very recent Deezer redesign, to try to remove an obtrusive login prompt. The new entry seems at first sight to work better in that regard.
