### ISSUE TITLE
nbcnewyork.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#5662]
### URL(s) where the issue occurs

`https://www.nbcnewyork.com/news/local/Nadler-Congressman-Appears-to-Almost-Pass-Out-at-de-Blasio-Presser--510382851.html`

### Describe the issue

Video broken

### Notes

`@@||www.nbcnewyork.com/includes/AppMeasurement.js$script,domain=www.nbcnewyork.com`

**Comment by terrorist96** [comment]
See also #3363

**Comment by THEtomaso** [comment]
`nbclosangeles.com` and `nbcsandiego.com` are affected too:
https://github.com/easylist/easylist/issues/3523/

**Comment by yourduskquibbles** [comment]
@terrorist96 can you test if other `nbc$local.com` domains also affected? 

Other Domains:
```
nbcbayarea.com
nbcchicago.com
nbcdfw.com
nbcmiami.com
nbcphiladelphia.com
nbcwashington.com
```

**Comment by terrorist96** [comment]
Confirmed. Videos broken at all those domains.
