### ISSUE TITLE
uploadever.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5664]
### URL(s) where the issue occurs

`uploadever.com/f/mbnyci-cqrtx7cu2lxql`

### Describe the issue

Popup ads

### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.19.6

### Settings

- uBO's default settings

**Comment by ghajini** [comment]
##[href^="https://ghoto-12.win/"] 
This broad filter ALWAYS doesn't work on firefox android.....

**Comment by krystian3w** [comment]
We no have android phones to tests...

**Comment by ghajini** [comment]
Solved.....firefox android ublock origin has default setting enabled - `ignore generic cosmetic filters`
And filter being generic is discarded by this setting

**Comment by ghajini** [comment]
`https://uploadever.com/f/l579p0-rdcf5tqi7dcxx`
`/glx_*.js$script,important`
`||arearmark.club^$important`

**Comment by ghajini** [comment]
`https://uploadever.com/f/3xm1r8-pcpirpb348t8h`
Shady xhr's increasing if blocked 1 by 1....

**Comment by ghajini** [comment]
`uploadever.com/f/un3qst-7q93s3u7t6mz5`

filter=

`||uploadever.com/sw.js`
`||niforniadistollie.info^`

**Comment by ghajini** [comment]
URL =
`https://uploadever.com/binlw6nkrrds`

Platform = firefox A. Ublock origin

Issue= popup ads  when clicking **free Download**

Filter

`||t6ibq24c5.com^`
