### ISSUE TITLE
hevchub.com(antiadblock)

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5665]
### URL(s) where the issue occurs

`hevchub.com/tag/300mbmovies/`

### Describe the issue

Antiadblock after few seconds after loading of site

### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.19.6

### Settings

- uBO's default settings

**Comment by krystian3w** [comment]
BAB...

```
@@||hevchub.com^$generichide
```

for me enough, maybe no recover ads or empty boxs.

**Comment by ghajini** [comment]
Popups arises after this filter in website

**Comment by krystian3w** [comment]
So wait for fix better as:

`hevchub.com##+js(bab-defuser.js)`

**Comment by ghajini** [comment]
site unavailable ,filters not req.
