### ISSUE TITLE
xtube.com, new layer [NSFW]

### ISSUE THREAD

**Issue by doio** [uBlockOrigin/uAssets#5671]
### URL(s) where the issue occurs
xtube.com profile page, bottom
`https://www.xtube.com/profile/satoko-6603573`

### Describe the issue
At the bottom of profile pages,
`Remove all Ads` layer on top of video description, rendering link unclickable. 

### Versions

- Browser/version: Firefox 67.0
- uBlock Origin version: 1.19.7b0

### Settings

- Default Settings

**Comment by mapx-** [comment]
video ?  the video (ad) removed by the filters ?
screenshot ?

**Comment by doio** [comment]
<details><summary>With UBO disabled: </summary>
<p>

![2019-05-26_16-16-58](https://user-images.githubusercontent.com/4461202/58379186-1b0a5600-7fd3-11e9-8071-cf4045f9e337.png)

</p>
</details>


<details><summary>With UBO on (EasyList and uBlock Filters from logger):</summary>
<p>

![2019-05-26_16-17-13](https://user-images.githubusercontent.com/4461202/58379243-cddab400-7fd3-11e9-925d-88fe845dd895.png)

</p>
</details>

<details><summary>"Remove all Ads" and this layer: </summary>
<p>

![2019-05-26_16-18-38](https://user-images.githubusercontent.com/4461202/58379248-ddf29380-7fd3-11e9-86b1-ca6556b00aef.png)

</p>
</details>

**Comment by mapx-** [comment]
I cannot reproduce the issue
Ading `xtube.com##.undefined` will remove `Remove all Ads` too (without any breakage) on my side
