### ISSUE TITLE
stratege.ru

### ISSUE THREAD

**Issue by electrifying** [uBlockOrigin/uAssets#5673]
`https://www.stratege.ru/#args:ajax=1`

### Describe the issue

advertising background and ad unit at the very bottom of the site

### Screenshot(s)

https://imgur.com/ZrvnrEI

### Versions

- Browser/version: google chrome 72.0.3626.121
- uBlock Origin version: 1.19.6

### Settings

uBO's default settings

### Notes

none

**Comment by electrifying** [comment]
@okiehsch 
Hi after your rules at the very bottom of the site there is an empty green block, could you remove it?

https://imgur.com/6rxGAVY

**Comment by dimisa-RUAdList** [comment]
These rules are no longer needed.

**Comment by dimisa-RUAdList** [comment]
Up!
