### ISSUE TITLE
uploadrar.com

### ISSUE THREAD

**Issue by version365** [uBlockOrigin/uAssets#5674]
### URL(s) where the issue occurs

`https://uploadrar.com/iuvqej5zthw1`

### Describe the issue

Skip the timer on free download option.

### Notes

`uploadrar.com##+js(nano-setTimeout-booster.js)` works for me..

**Comment by ghajini** [comment]
`uploadrar.net/5hopydp4bcd3`

Antiadblock.....

**Comment by stephenhawk8054** [comment]
There are 3rd-party ads link at the final page of the site, which causes popup when clickin on `Click Here To Download`.

URL:
`https://uploadrar.com/u692sln9qor1`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/149666704-62b8de42-6c74-406b-9280-1a16d79a2f3d.png)

</details>

Videos:
`https://youtu.be/0RqStrJg-3c`
`https://youtu.be/5GoWQ4mMqMQ`

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 79488
  cosmetic: 40528
  scriptlet: 16425
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30751-30, now
    ublock-badware: 3728-1, now
    ublock-privacy: 187-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1734-0, now
    easylist: 63047-586, now
    easyprivacy: 26627-480, now
    urlhaus-1: 8471-0, now
    plowe-0: 3682-2, now
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 483 ms
popupPanel: 
  blocked: 10
```
</details>

I'm not sure if this inline script causes that

<details><summary>Script</summary>

```js
(function(d, z, x, s, e, o) {
  s.src = '//' + d + '/tag.min.js';
  x.withCredentials = true;
  x.open('GET', '//' + d + '/5/' + z + '/?oo=1&aab=1', !0);
  s.onerror = x.onerror = E;
  s.onload = x.onload = g;
  x.send();
  (document.body || document.documentElement).appendChild(s);

  function g() {
    o = this.response ? JSON.parse(this.response) : o;
    o && window.kkp4a5x5tv && window.kkp4a5x5tv(o);
  }

  function E() {
    e && e();
    e = null;
  }
})('ausoafab.net', 4622433, new XMLHttpRequest(), document.createElement('script'), _luqbcyu)
```

</details>

but looks like this filter prevents it:

`uploadrar.*##+js(acis, document.documentElement)`
