### ISSUE TITLE
Globalvoices.org has assets blocked unrelated to ads

### ISSUE THREAD

**Issue by jerclarke** [uBlockOrigin/uAssets#5688]
### URL(s) where the issue occurs

`https://globalvoices.org/`

### Describe the issue

A bunch of valid assets (in my repeatable case, our funder logos which show in the final right-hand block of the page footer) are being blocked by uBlock. 

These particular assets are stored on an Amazon S3 bucket. Neither our site nor that S3 bucket displays or hosts any kind of advertising. We're an ad-free non-profit journalism site. 

Some of my users are finding that scripts are also being blocked, which crashes all JS rendering on the page. I couldn't reproduce that with a vanilla installation of uBlock in Firefox but will try to figure out what is different for them. 

### Screenshot(s)

<img width="922" alt="footer-with-missing-funder-graphics" src="https://user-images.githubusercontent.com/139995/58497938-fdf89300-814a-11e9-96c8-acdcd1e771f3.png">

<img width="1289" alt="blocked-files-ublock" src="https://user-images.githubusercontent.com/139995/58497949-04870a80-814b-11e9-8c21-21b1d2d2bd92.png">

### Versions

- Browser/version: Firefox Quantum 67.0 (64-bit)
- uBlock Origin version: 0.9.6.16

### Settings

- Default settings

### Notes

- Mentioned everything above: No ads on either server, some S3 files work while others are blocked, some users have JS scripts blocked too which crashes all JS.

**Comment by mapx-** [comment]
0.9.6.16 ?  Are you sure ? Could you check again if your adblocker is `ublock origin` or only `ublock` (a spam version) ?

Current version of uBo for firefox is 1.19.6

**Comment by gwarser** [comment]
https://github.com/easylist/easylist/commit/9e8fac65f3422915414ae777fa866f6931a5f6f3 interesting

**Comment by jerclarke** [comment]
<img width="208" alt="Screen Shot 2019-05-28 at 13 42 33 PM" src="https://user-images.githubusercontent.com/139995/58499607-84fb3a80-814e-11e9-9761-755a16cf6a25.png">

This is a spam version? Got it from https://www.ublock.org/ is that you?

**Comment by mapx-** [comment]
No. That one is the spam version. Remove it and install the real one. Yours is not `origin`

**Comment by jerclarke** [comment]
Ah geez, they come up first in google and that domain seems real. Thank you for understanding. Will continue testing with the real one.

**Comment by mapx-** [comment]
real one:
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

**Comment by mapx-** [comment]
yep, is a google ranking issue

**Comment by jerclarke** [comment]
Okay, I've disabled ABP, that is a good point. I only installed  UB to diagnose the problem. 

On the bright side, the real UB (v.1.19.6) has the same effect as the fake one: 

<img width="1508" alt="Screen Shot 2019-05-28 at 13 50 21 PM" src="https://user-images.githubusercontent.com/139995/58500129-8ed16d80-814f-11e9-8004-e56034229a53.png">

**Comment by mapx-** [comment]
I already fixed the issue, just update all the lists (click "purge all caches" then click "update now") the refresh the page

**Comment by mapx-** [comment]
The fix is regarding only uBo, for other adblockers you need to report at easylist repository or forum
https://github.com/easylist/easylist/issues
http://forums.lanik.us/

**Comment by jerclarke** [comment]
Okay thanks!
