### ISSUE TITLE
www.klix.ba images not clickable because of blocked www.googletagmanager.com

### ISSUE THREAD

**Issue by AsocialSurvival** [uBlockOrigin/uAssets#5689]
### URL(s) where the issue occurs

`https://www.klix.ba/vijesti/bih/stanarka-zgrade-koju-opcina-u-sarajevu-zeli-srusiti-ovdje-sam-od-rodjenja-tu-zelim-i-umrijeti/190528059`

### Describe the issue

umatrix and ublock cause images on www.klix.ba to be not clickable, meaning can't view another image in the list than the currently displayed one, because they block https://www.googletagmanager.com/gtag/js?id=UA-63707-9 by default (stuff after ? may be dynamic)

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Firefox 67.0
- uBlock Origin version: 1.19.2 (and umatrix 1.3.16)

### Settings

- default

### Notes

tried turning off umatrix and ublock completely and issue is resolved, tried re-enabling www.googletagmanager.com via umatrix or it javascript only, while turning off ublock, and issue is resolved, tried all other options (allowing all other but blocking only that domain, and issue is not resolved, meaning i am 100% sure it is the culprit), also verified via logger of both umatrix and ublock, together and if using only one extension (each)

**Comment by mapx-** [comment]
already fixed by easyprivacy

![image](https://user-images.githubusercontent.com/10303732/58506310-4fc30c80-818f-11e9-919c-6d7fc2ba8f89.png)

Update all the lists and test again

**Comment by AsocialSurvival** [comment]
> 
> 
> already fixed by easyprivacy
> 
> ![image](https://user-images.githubusercontent.com/10303732/58506310-4fc30c80-818f-11e9-919c-6d7fc2ba8f89.png)
> 
> Update all the lists and test again

True, fixed in ublock, but what about umatrix?

**Comment by mapx-** [comment]
Add your own rule, I don't use umatrix
