### ISSUE TITLE
popup tabunder

### ISSUE THREAD

**Issue by suyee89** [uBlockOrigin/uAssets#5694]
### URL(s) where the issue occurs

`https://underpic.club/img-5ced139fcf688.html`

### Describe the issue

popup, tabunder, banners

### Versions

- Browser/version: 74.0.3729.169
- uBlock Origin version: 1.19.6

### Settings

default

**Comment by okiehsch** [comment]
Please don't post clickable links to sites with NSFW content, use one backtick before and after the example link.
