### ISSUE TITLE
Unbreak [NSFW]

### ISSUE THREAD

**Issue by suyee89** [uBlockOrigin/uAssets#5695]
### URL(s) where the issue occurs

`https://picbaron.com/fubt657t9xyp/FTDS-005_s.jpg.html`

### Describe the issue

Ads is blocked nicely, however it breaks some of the feature, at the content page i get a resized image but i cant click to enlarge the content due to ublock

### Versions

- Browser/version: 74.0.3729.169
- uBlock Origin version: 1.19.6

### Settings

default

**Comment by okiehsch** [comment]
I already told you, don't post clickable links, use `backticks`.

**Comment by P0Rtvine** [comment]
`https://picbaron.com/n6rg2lasi5dq/WakeUpNFuck_Barbie_Esm_-_WUNF_325_11.01.2021_rq.mp4.jpg.html`

Click to **Continue to image...** content is hidden.

### Versions

- Browser/version:  Google Chrome
- uBlock Origin version:  uBO 1.32.4

### Settings

<details>
<summary>Screen</summary>

![image](https://user-images.githubusercontent.com/57287308/104311922-8ffb0e00-54de-11eb-9ba9-c9217d860aa3.png)
</details>

**Comment by mapx-** [comment]
test

```
picbaron.com##+js(aopr, loadTool)
picbaron.com###fadeinbox
*$frame,domain=picbaron.com
||picbaron.com/*.gif$image
picbaron.com##[href*="/redirect"]
```
