### ISSUE TITLE
zmctrack

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#5696]
### URL(s) where the issue occurs
```
https://dynamo.kiev.ua/news/320322-derlis-gonsales-zabil-v-vorota-meksiki-video
https://gagadget.com/
https://www.okino.ua/film/dzhon-uik3-614109/
https://ringside24.com/ru/video/2984/
```
### Describe the issue
Advertisement embedded using zmctrack code.
### Screenshot(s)
https://i.imgur.com/MYiaLnh.jpg
https://i.imgur.com/KpX7tXD.jpg
https://i.imgur.com/Q9MjRi3.jpg
https://i.imgur.com/dcPJFdm.jpg
### Versions
- Browser/version: Google Chrome 74.0.3729.169
- uBlock Origin version: 1.19.6
### Settings
uBO's default settings
### Notes
For okino.ua can use: `okino.ua##+js(set-constant.js, Function.prototype.toString, trueFunc)`, however, in other cases, some functions will be broken, for example - search.

**Comment by mapx-** [comment]
for `dinamo.kiev.ua` test
```
/(pagead2|metrika|doubleclick|gemius.pl)/$important,domain=dynamo.kiev.ua,badfilter
kiev.ua##+js(set-constant.js, String.prototype.charCodeAt, trueFunc)
dynamo.kiev.ua###aswift_0
```
first one to unbreak the video on the page

**Comment by mapx-** [comment]
test also
```
gagadget.com##+js(set-constant.js, String.prototype.charCodeAt, trueFunc)
ringside24.com##+js(set-constant.js, String.prototype.charCodeAt, trueFunc)
```

**Comment by mapx-** [comment]
I guess similar filter is working for `okino` as well (if soes not break something else)

**Comment by dimisa-RUAdList** [comment]
https://hg.adblockplus.org/ruadlist/rev/26cc136832d5

**Comment by bogachenko** [comment]
`narod.i.ua`
only firefox!

adblock

**Comment by mapx-** [comment]
I get no anti adb stuff

**Comment by bogachenko** [comment]
block the first inline script

**Comment by dimisa-RUAdList** [comment]
Google Chrome 84.0.4147.135
uBlock Origin 1.29.0 
default + RU AdList

Rules: `112.ua,4mama.ua,autoua.net,avtovod.com.ua,buhgalter.com.ua,businessua.com,censor.net.ua,dengi.ua,ditey.com,eknigi.org,enovosty.com,epravda.com.ua,eurointegration.com.ua,facenews.ua,football-ukraine.com,football24.ua,footballtransfer.com.ua,gagadget.com,gismeteo.ua,glavcom.ua,gorod.dp.ua,hvylya.net,i.ua,inforesist.org,internetua.com,isport.ua,kolobok.ua,kp.ua,kriminal.tv,lifedon.com.ua,liga.net,mama.ua,mport.ua,nashamama.com,newsyou.info,nnovosti.info,obyava.ua,okino.ua,ostro.org,~passport.i.ua,pogoda.meta.ua,pravda.com.ua,real-vin.com,ringside24.com,segodnya.ua,sinoptik.ua,smak.ua,socportal.info,strana.ua,stravy.net,telegraf.com.ua,tochka.net,tv.ua,tvgid.ua,udoktora.net,vesti.ua,vsetv.com,www.bigmir.net,zdorovia.com.ua,zn.ua##+js(set-constant, String.prototype.charCodeAt, trueFunc)` no longer work.

Example: `https://112.ua/mir/v-minske-prizemlilsya-samolet-tu-214-rossiyskoy-fsb-smi-546940.html`
Ukrainian ip required. You can use [Hola](https://chrome.google.com/webstore/detail/hola-free-vpn-proxy-unblo/gkojfkhlekighikafcpjkiklfbnlmeio).

This problem is not observed when using uBlock Origin 1.28.4.

**Comment by P0Rtvine** [comment]
@gorhill

**Comment by mapx-** [comment]
alternatives ?

1. `@@||112.ua^$ehide`

or
2. (could break something)
```
||112.ua^$csp=style-src *
112.ua##body > svg
112.ua##.random-img
112.ua##[src*="counter.png"]
112.ua##[style="display:none"]
```

**Comment by dimisa-RUAdList** [comment]
The problem is observed only in version 1.29.0. Something is wrong with `set-constant`. There will be hundreds of alternative rules for all of the listed sites and will take many hours of work to compile. This is not an option.

**Comment by okiehsch** [comment]
Probably caused by this commit. 
https://github.com/gorhill/uBlock/commit/c33de41660de0b7c982a40f4bfde31f32180a2ee#diff-d7616deaf3a39e3f19f8d70d098bfe7a

**Comment by mapx-** [comment]
another idea, tested on `112.ua, 4mama.ua`

`*##+js(acis, HTMLIFrameElement.prototype.contentWindow)`

**Comment by P0Rtvine** [comment]
`##+js(acis, HTMLIFrameElement.prototype.contentWindow)`

Yes, it's working fine.

**Comment by dimisa-RUAdList** [comment]
This rule will break functionality. For example here: `https://www.okino.ua/` - search is broken.

**Comment by mapx-** [comment]
test (search working fine on my side)
`*##+js(aopw, HTMLElement.prototype.insertAdjacentHTML)`

**Comment by gorhill** [comment]
The question is how did this even work before. Investigating using `https://112.ua/`, I can see code in there that explicitly checks `'I'.charCodeAt(0) === 49`, so the site detects when uBO overloads `charCodeAt()`.

**Comment by gorhill** [comment]
I am stumped as to why the previous version of `set-constant` did not trigger the anti-blocker. Functionally it's essentially the same as the current one. Help in pinpointing the reason is welcome.

**Comment by dimisa-RUAdList** [comment]
@mapx- 
> test (search working fine on my side using this filter)
> `*##+js(aopw, HTMLElement.prototype.insertAdjacentHTML)`

Yes, the search works, but the [detector](https://i.imgur.com/5lIdVRV.jpg) is also triggered and ads are loaded.

**Comment by mapx-** [comment]
- yes, the detector is triggered but the ads are killed on my side
- if I disable the russian list (keeping my filter) I get only text ads

![image](https://user-images.githubusercontent.com/10303732/90662667-ed997000-e248-11ea-910d-d271b12ed735.png)

**Comment by P0Rtvine** [comment]
on my side

`okino.ua##+js(aopw, HTMLElement.prototype.insertAdjacentHTML)`
`okino.ua#@#+js(set-constant, String.prototype.charCodeAt, trueFunc)`

![2020-08-19_215959](https://user-images.githubusercontent.com/57287308/90678455-61e30c00-e267-11ea-8535-03a84c4172ea.png)
![2020-08-19_215959](https://user-images.githubusercontent.com/57287308/90678568-8808ac00-e267-11ea-954d-6567e3299215.png)

**Comment by dimisa-RUAdList** [comment]
When using this rule, there will be a lot of empty spaces on the sites, and they do not always have the same color as the main background.

Example: https://www.gismeteo.ua/

**Comment by P0Rtvine** [comment]
> When using this rule, there will be a lot of empty spaces on the sites.

Yes, this scriplet is not suitable.

![2020-08-19_221919](https://user-images.githubusercontent.com/57287308/90680207-2dbd1a80-e26a-11ea-8dfb-d207dbbcffb8.png)

**P.S.**
It's a pity that no one can solve this problem.

**Comment by dimisa-RUAdList** [comment]
I think **gorhill** will find a solution.

**Comment by mapx-** [comment]
@dimisa-RUAdList you should add
`@@||video.112.ua.cdn.cloudflare.net^$script,domain=112.ua` for FF (cname) => video broken

and now test this other filter:
`*##+js(acis, XMLHttpRequest)`

**Comment by dimisa-RUAdList** [comment]
@mapx- 
> you should add
> `@@||video.112.ua.cdn.cloudflare.net^$script,domain=112.ua` for FF (cname) => video broken

Ok: https://hg.adblockplus.org/ruadlist/rev/69d0aaf37c24#l1.12

> and now test this other filter:
> `*##+js(acis, XMLHttpRequest)`

Same.

> empty spaces only in chrome ..

Unfortunately, Firefox is not the most widely used browser.

**Comment by mapx-** [comment]
@dimisa-RUAdList the empty spaces are there in chrome even without any new filters, right ? so, it's a specific gismeteo issue, the filters are working fine for all other pages on your side ?

**Comment by mapx-** [comment]
however, for `sinoptik.ua` is working `*##+js(aopr, HTMLElement.prototype.insertAdjacentHTML)` but not:
`*##+js(acis, XMLHttpRequest)`

**Comment by dimisa-RUAdList** [comment]
Empty spaces are not only on the gismeteo site, they are everywhere. When using version 1.28.4, they are not.

**Comment by dimisa-RUAdList** [comment]
Empty spaces appear only if the advertising code zmctrack has worked. At the same time, a shadow-root appears, which makes it impossible to remove empty spaces.

Example: `https://www.pravda.com.ua/news/2020/08/20/7263568/`, [screen](https://i.imgur.com/5iWkGlW.jpg)
