### ISSUE TITLE
news.yahoo.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#5699]
### URL(s) where the issue occurs

`https://news.yahoo.com/latest-white-house-says-told-mueller-might-speak-141544632--politics.html`

### Describe the issue

Unblocked preroll video ad.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/58585193-04a80880-8226-11e9-8975-322077914cd7.png)

**Comment by yourduskquibbles** [comment]
Related: https://github.com/NanoMeow/QuickReports/issues/1220

The ad doesn't seem to load when I am connected to US VPN, it may be location or residential US IP based to be triggered.

**Comment by mapx-** [comment]
@terrorist96  
test
`||edgecast-vod.yimg.com/$media,redirect=noopmp3-0.1s,domain=news.yahoo.com`

**Comment by terrorist96** [comment]
That works. Thanks!

**Comment by terrorist96** [comment]
@mapx- expand it to yahoo in general, as I can also reproduce the ad in the issue @yourduskquibbles posted.

**Comment by NubN** [comment]
what about this script: `https://s.yimg.com/aaq/news/js/react-adblock-promo.ff842bdd8c24d8a5f345.min.js`

showing, 300x250 "unclikable" image with uBO ON, and different image with uBO OFF.
`https://news.yahoo.com/coronavirus-live-updates-donald-trump-092521108.html`

😷

**Comment by llacb47** [comment]
@ryanbr
