### ISSUE TITLE
supertelevisionhd.com [Fake Button]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5700]
URL(s) where the issue occurs

`http://www.supertelevisionhd.com/tnt-en-vivo-online/`

Describe the issue

Fake Button

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 74 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.19.6

Settings

Default

**Comment by KiLL4FuNK** [comment]
PLAY VIDEO

**Comment by mapx-** [comment]
well, report at adgurd (classic filter, no other filters for the site)
add
`aohdonline.info###anuncio`

**Comment by KiLL4FuNK** [comment]
Fake Button

`http://www.supertelevisionhd.com/espn-2-en-vivo/`

**Comment by KiLL4FuNK** [comment]
Fake Button

`http://www.supertelevisionhd.com/el-trece-en-vivo/`

**Comment by KiLL4FuNK** [comment]
Fake Button

`http://www.supertelevisionhd.com/tyc-sports-en-vivo/`

**Comment by KiLL4FuNK** [comment]
PLAY VIDEO [Pop-up]

`http://www.supertelevisionhd.com/espn-2-en-vivo/`
