### ISSUE TITLE
wowtoken.info

### ISSUE THREAD

**Issue by Neurotoxin001** [uBlockOrigin/uAssets#5702]
### URL(s) where the issue occurs
wowtoken.info

### Describe the issue
High CPU usage on that page

### Screenshot(s)
![image](https://user-images.githubusercontent.com/39812401/58654444-95630f00-8320-11e9-9bbf-3a0546d05f24.png)

### Versions

- Browser/version: Google Chrome 74.0.3729.169
- uBlock Origin version: 1.19.6

### Notes
I use `uBlock filters – Resource abuse` but it's doesn't help, can you please help to find what is loads CPU on this site?

**Comment by okiehsch** [comment]
I don't see anything mining related happening at `wowtoken.info`
My CPU settles at a normal level after the site finishes loading.

**Comment by Neurotoxin001** [comment]
> My CPU settles at a normal level after the site finishes loading.

Even with all disabled extensions I see this:
![image](https://user-images.githubusercontent.com/39812401/58660073-30fa7c80-832d-11e9-83cc-fb5f08f169e3.png)
Even in incognito mode, and only this site...

**Comment by dumbusernameidk** [comment]
Normal usage on my end 1-3%.

**Comment by Neurotoxin001** [comment]
If I block this:
`https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js`
All is fine. But this is only with single site... Even if I put this script in my own site or any page and open it - all is fine.

I don't know what it's can be.

**Comment by okiehsch** [comment]
`https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js` is needed for the site to load properly, I get a short CPU spike while the site is loading the graphics but after that everyting is fine on my end.

**Comment by Neurotoxin001** [comment]
I ask friend to check this site - he's too got 100% CPU usage. Ok then, it's not uBlock issue I think, twitted to site dev about it:
https://twitter.com/Neurotoxin001/status/1134195026764992518
