### ISSUE TITLE
majesy.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5703]
### URL(s) where the issue occurs

`http://majesy.com`

### Describe the issue

anti-Adblock

### Versions

- Browser/version: Firefox 67.0
- uBlock Origin version: v1.19.6

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3238346/Settings.txt)

**Comment by mapx-** [comment]
fixed today, see  https://github.com/uBlockOrigin/uAssets/issues/1197#issuecomment-497305108

**Comment by JobcenterTycoon** [comment]
The site disable rightclick
