### ISSUE TITLE
stocktwits adblock popup dialog

### ISSUE THREAD

**Issue by ashishthukral** [uBlockOrigin/uAssets#5709]
### URL(s) where the issue occurs

`https://stocktwits.com/`

### Describe the issue

Pops up anti adblock banner with following language 
`Sponsors allow us to provide you the most up-to-date stock, crypto and futures information and connect traders to profit, learn, and have fun - all for free! Please support us by disabling your adblocker and whitelisting Stocktwits.com`

### Screenshot(s)

`https://imgur.com/DAcurVf`

### Versions

- Browser/version: Chrome Version 74.0.3729.169 (Official Build) (64-bit)
- uBlock Origin version: 1.19.6

### Settings

- None

### Notes

tried blocking elements with zapper but it blocks the Scroll function of the website

**Comment by mapx-** [comment]
Enable `uBlock filters – Annoyances` list and test again

**Comment by ashishthukral** [comment]
> Enable `uBlock filters – Annoyances` list and test again

Worked, thanks. the list was hidden in pluggin setting. Thanks a lot.

**Comment by mapx-** [comment]
yeah, `uBlock filters – Annoyances` is not enabled by default

For the site above you could just click "continue without supporting us" => just annoyance, the site still working after that
