### ISSUE TITLE
AntiAdblock warnings 

### ISSUE THREAD

**Issue by Jose1971AB** [uBlockOrigin/uAssets#5710]
Hello friends, greetings to all ...

> **Excuse me, I'm with the help of the Google translator.**

### URL(s) where the issue occurs
[ **https://esradio.libertaddigital.com/fonoteca/
https://windowsaplicaciones.com/vista-de-lectura-en-firefox-trucos/** ]

### Describe the issue
[ **https://esradio.libertaddigital.com/fonoteca/** ]
If I click on the X of the notice or anywhere on the screen is removed but clicking the button does not work.
It happens in the two links, not only in the links that I present specifically, but in general.

### Screenshot(s)
[ **https://esradio.libertaddigital.com/fonoteca/** ] --> 
**http://img.fenixzone.net/i/bWdf8im.png**

[ **https://windowsaplicaciones.com/vista-de-lectura-en-firefox-trucos/** ] --> 
**http://img.fenixzone.net/i/kzUqyDi.png**

### Versions
- Browser/version: [**Mozilla Firefox 67.0**]
- uBlock Origin version: [**v1.19.6**]

### Settings
**Configuration uBlock origin**
**http://img.fenixzone.net/i/lXHgRyv.png
http://img.fenixzone.net/i/1Bwds5J.png
http://img.fenixzone.net/i/zwhO3on.png --> See note below
http://img.fenixzone.net/i/6W5mjCH.png
The My Rules section is by default**

### Notes
This configuration of uBlock that I present is according to a previous case that I resolved in this forum. Since then I have not modified it.
Custom filters surrounded in red are combos that include several of those above Default. Less filters, less consumption of resources. They are taken from [ **https://filterlists.com/** ]

Regards, and thank you very much

**Comment by okiehsch** [comment]
Update your `uBO-filter` list or add
````
esradio.libertaddigital.com###mega-atf
@@||esradio.libertaddigital.com/ad/*$xhr,1p
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=esradio.libertaddigital.com
windowsaplicaciones.com##+js(abort-on-property-read.js, anOptions)
````
to your filter list.
