### ISSUE TITLE
filmywap.world [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5716]
URL(s) where the issue occurs

`https://filmywap.world/guddiyan-patole-full-movie-free-download/`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 74 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.19.6

Settings

Default

**Comment by ghajini** [comment]
sister sites(realted/unrelated?)
popup ads
`https://www.filmywap.com`
`https://filmywapofficial.com`
`https://filmywap.net`
