### ISSUE TITLE
themesradar.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5717]
URL(s) where the issue occurs

`https://themesradar.com/go/BRwK6M5RIr`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 74 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.19.6

Settings

Default

**Comment by dumbusernameidk** [comment]
Site also disables right click and copy/paste. I only have the anti-adblock and right click. Can't fix the copy/paste for some reason.

`themesradar.com##+js(addEventListener-defuser.js, contextmenu)`
`themesradar.com##+js(setTimeout-defuser.js, checkAdblockUser)`

**Comment by okiehsch** [comment]
````
<style>
--
  |  
  | /*----- Disable Text Selection with CSS Code-------*/
  | body {
  | -webkit-user-select: none !important;
  | -moz-user-select: -moz-none !important;
  | -ms-user-select: none !important;
  | user-select: none !important;
  | }
  |  
  | </style>
````
Disables copy/paste.
````
themesradar.com##body:style(-webkit-user-select: text !important;-moz-user-select: text !important;-ms-user-select: text !important;user-select: text !important;)
````
fixes it.

**Comment by dumbusernameidk** [comment]
Ah right I keep forgetting you can fix that with CSS. I'll have to keep that in mind next time.
