### ISSUE TITLE
softonic.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#572]
Banner ads are displayed all over the pages on `https://www.softonic.com`. These are loaded when the page detects that normal ads have been blocked (anti adb).

**SS:** https://i.imgur.com/4KVvJWn.png

**Error URLs:**
```
https://en.softonic.com
https://articulos.softonic.com/egolf-coche-electrico-branded
```

They use inline-scripts to detect adblock.

_**Note:** Using uBO 1.13.8 on Chrome 59 with the default filters and settings._

**Comment by gotitbro** [comment]
@okiehsch The ads are still loaded on the site.

**Error URLs:** 
```
https://en.softonic.com
https://www.softonic.com/windows
```

**Comment by okiehsch** [comment]
1. `https://en.softonic.com` I only get blank ad spaces does
````
softonic.com###show_banner_leaderboard
softonic.com###show_banner_medium_rectangle
````
work for you?
2. `https://www.softonic.com/windows` does 
`@@||softonic.com/shared/abp_detection/$script,first-party`
work for you?

**Comment by gotitbro** [comment]
@okiehsch Yes, it does work.

Some blank ads in the articles as well. 
**Error URL:** `https://features.en.softonic.com/7-common-mistakes-job-hunting-eng`

Can be hidden by: `softonic.com##.leaderboard-editorial`

**Comment by gotitbro** [comment]
@okiehsch I am seeing ads (anti adb) on the software download pages as well.

**SS:** https://i.imgur.com/A3DDcXA.png
**Error URL:** `https://utorrent.en.softonic.com/`
