### ISSUE TITLE
Jquery on Openloed.co blocked, breaking the site

### ISSUE THREAD

**Issue by andrewprivate** [uBlockOrigin/uAssets#5722]
I apologize in advance for not following the template layout. 

### Ublock blocks ALL third party scripts on certain websites, including the essential libraries like jquery

UBlock Origin has this item in the filter:

`*$script,third-party,domain=openloed.co`

This blocks all third party scripts, including the JQuery library, from a page on openloed.co. This breaks the site.

<img width="1280" alt="Screen Shot 2019-06-01 at 12 40 47 PM" src="https://user-images.githubusercontent.com/32175943/58751273-8b4d2780-846a-11e9-83c6-10d2a6f2902f.png">

<img width="1245" alt="Screen Shot 2019-06-01 at 12 55 14 PM" src="https://user-images.githubusercontent.com/32175943/58751451-8a1cfa00-846c-11e9-8265-498bf3a829a0.png">

https://github.com/uBlockOrigin/uAssets/blob/d40829ba3084bbbd12f86ebe6dc621229185ac90/filters/filters.txt#L289

With more digging, I found that there were several other sites in the filter where third party scripts were blocked. Those websites could have a similar problem. In my opinion, blocking all third party scripts for any site is a bad idea.

### Side issue

As a temporary fix, I have put my own custom entry in the filter:

`@@||cdnjs.cloudflare.com^`

This used to work fine. But recently, there has been a problem where it does not work (but works the instant you save the custom filter - therefore, it is probably with the priority of the filter entries that is causing the bug)

**Comment by ghajini** [comment]
Test link?

**Comment by andrewprivate** [comment]
Sorry, I dont have one for you. However, according to the filter list, the addition to the filter was connected with https://github.com/uBlockOrigin/uAssets/issues/4159

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/f6eed7be5d5e65d25ed1bdfcfe0fa5ef1db7ed67

**Comment by mapx-** [comment]
example video
`https://openloed.co/embed/bs1NWj1dCag`
but I get no jquery blocked

**Comment by okiehsch** [comment]
@andrewprivate if you don't have an example link how did you take your screenshot?
<img width="1280" alt="Screen Shot 2019-06-01 at 12 40 47 PM" src="https://user-images.githubusercontent.com/32175943/58751273-8b4d2780-846a-11e9-83c6-10d2a6f2902f.png">


<img width="1245" alt="Screen Shot 2019-06-01 at 12 55 14 PM" src="https://user-images.githubusercontent.com/32175943/58751451-8a1cfa00-846c-11e9-8265-498bf3a829a0.png">

**Comment by andrewprivate** [comment]
@mapx- @okiehsch The problem is that for the link provided, the server serves its own jquery. But, there are other pages where they do not - instead using cloudflare's cdn. However, I cannot give you this link since it is generated uniquely for the user. People with different IPs than the intended client will not be able to view the page.

**Comment by okiehsch** [comment]
If adding
`@@||cdnjs.cloudflare.com/ajax/libs/jquery/*$script,domain=openloed.co`
fixes the issue I will add it to `uBO-unbreak`

**Comment by andrewprivate** [comment]
Thanks!

**Comment by andrewprivate** [comment]
@okiehsch 
However, like I mentioned before, I think that this problem may apply to other websites that have similar problems. My logic goes, that most websites need certain libraries to function - not all third party scripts are bad. Also, we do not know exactly what libraries they are using now, nor do we know about the future since we do not have access to all of the website's pages, nor do we continually monitor them. Furthermore, finding the root cause of this sort of behavior is extremely difficult to most people - people might not know exactly what library is causing the problem. For example, in my case, most people would not know what `$` traditionally is, and as a result, won't be able to determine the root cause of the error thrown easily (`$ is not defined`). As a result, this means that if a website breaks because of these sorts of filters (which I guarantee that it happens more often than expected), we will not be aware of it for a long time - if ever - while the users are inconvenienced. Therefore, I think that it is bad practice to block ALL third party scripts from any working website.


As a temporary fix, I think that having a whitelist of common libraries that apply to all websites should be present, such as jquery.

**Comment by okiehsch** [comment]
>  think that this problem may apply to other websites that have similar filters. 

I can see your point but such filters
`*$script,third-party,domain=example.com`
are very rare, `uAssets` has three of them, all warez/streaming or porn sites, so I don't think this is a huge issue.

**Comment by andrewprivate** [comment]
@okiehsch That is a fair point. But I think such filters should be discouraged in the future.
