### ISSUE TITLE
banners [nsfw]

### ISSUE THREAD

**Issue by suyee89** [uBlockOrigin/uAssets#5725]
### URL(s) where the issue occurs

`https://unporn.site/img-5cf1325625da0.html`

### Describe the issue

banners

### Versions

- Browser/version: 74.0.3729.169
- uBlock Origin version: 1.19.6

### Settings

default

**Comment by mapx-** [comment]
I get no banner, screenshot ?
Try updating all your lists and be sure you still have enabled the lists from the default installation

**Comment by mapx-** [comment]
Try updating all your lists ("purge all caches" , then click "update now")

**Comment by okiehsch** [comment]
The fix for https://github.com/uBlockOrigin/uAssets/issues/5701 still works on my end, there is no need to open a new issue for the same domain.
