### ISSUE TITLE
welt.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5726]
### URL(s) where the issue occurs

`https://www.welt.de/vermischtes/article159579575/Tourist-rutscht-aus-und-loest-sich-in-heisser-Quelle-auf.html`

### Describe the issue

Pre Video Ads

### Screenshot(s)
![Unbenannt](https://user-images.githubusercontent.com/48647394/58753160-b3b14200-84bb-11e9-98c6-3fddf7d7d4b6.PNG)

### Versions

- Browser/version: Firefox 67.0
- uBlock Origin version: v1.19.6

### Settings

default

### Notes

The filter `||damoh.welt.de^$media,redirect=noopmp4-1s,domain=welt.de` works for me

**Comment by okiehsch** [comment]
That filter breaks the video playback on my end only the audio still works.

**Comment by JobcenterTycoon** [comment]
> 
> 
> That filter breaks the video playback on my end only the audio still works.

Now i can reproduce. Its because Firefox 67.0 disable Autoplay by default now. The ad only appears when autoplay is disabled. My filter breaks the video playback when autoplay is enabled but its working when autoplay is not enabled.

**Comment by okiehsch** [comment]
Hm, the ad appears on my end with auto play enabled and it breaks the video playback no matter what, tested with Chromium and Firefox.
I don't see a way to disable the pre-roll ad without breaking the player at the moment.

**Comment by kulfoon** [comment]
No ads here (Firefox & Opera).

**Comment by okiehsch** [comment]
I need a german IP to reproduce the ads.

**Comment by kulfoon** [comment]
I already used german IP before creating my commen above.
I've checked again now on a different german IP and still no video ads.
This is the proxy I've used: `194.25.183.3:39662`
Can you share the proxy you used, I\ll check if can reproduce on your proxy.

**Comment by okiehsch** [comment]
I used 
````
https://chrome.google.com/webstore/detail/hola-free-vpn-proxy-unblo/gkojfkhlekighikafcpjkiklfbnlmeio?hl=en
````
I also am pretty sure that the OP is from Germany.

**Comment by JobcenterTycoon** [comment]
I get ads with your proxy `194.25.183.3:39662`

**Comment by kulfoon** [comment]
Have tried several more times with `194.25.183.3:39662` and `195.201.227.202:8080` and finally I've randomly reproduced but can very rarely reproduce like 1 per 10 visits.

Then have tried the addon okiehsch : https://github.com/uBlockOrigin/uAssets/issues/5726#issuecomment-498062402 suggested and can reproduce every time.

Don't know why and what't the difference between a typical proxy (my proxy were described as "High anonymous") and this kind of addon.

> okiehsch : https://github.com/uBlockOrigin/uAssets/issues/5726#issuecomment-497979974 : That filter breaks the video playback on my end only the audio still works.

Yes, for me too.

**Comment by JobcenterTycoon** [comment]
> 
> 
> Have tried several more times with `194.25.183.3:39662` and `195.201.227.202:8080` and finally I've randomly reproduced but can very rarely reproduce like 1 per 10 visits.
> 
> Then have tried the addon okiehsch : [#5726 (comment)](https://github.com/uBlockOrigin/uAssets/issues/5726#issuecomment-498062402) suggested and can reproduce every time.
> 
> Don't know why and what't the difference between a typical proxy (my proxy were described as "High anonymous") and this kind of addon.
> 
> > okiehsch : [#5726 (comment)](https://github.com/uBlockOrigin/uAssets/issues/5726#issuecomment-497979974) : That filter breaks the video playback on my end only the audio still works.
> 
> Yes, for me too.

Yes for me too now. I'm tried again and get the same results now. It's impossible for me to block this ad without breaking the Video player.

**Comment by lain566** [comment]
@okiehsch Can you test this filter?
`welt.de##+js(abort-on-property-read.js, funkotron.config.switches.StickyVideoRewrite)`

by mistake I accessed with my real ip, and I can no longer see pre-roll ads, even if I use a German ip

**Comment by okiehsch** [comment]
Works on my end using a german IP, nice find.

**Comment by lain566** [comment]
@okiehsch If the filter does not break anything, can you add it to the list?

and can you check this site? I think the website is broken
`https://www.queerpride.de/maenner-leggings-der-modetrend-fuer-selbstbewusste-maenner-176946`

![Anotación 2019-05-27 223457](https://user-images.githubusercontent.com/27441315/59809133-80feaa80-92ff-11e9-9914-34813ecfee9c.png)

**Comment by okiehsch** [comment]
Will do and yes that website is completely broken.

**Comment by okiehsch** [comment]
The article is marked as an advertorial,  but the cosmetic filter hides basically the whole website, so I think removing it is the correct call.
