### ISSUE TITLE
xstreamcdn.com

### ISSUE THREAD

**Issue by version365** [uBlockOrigin/uAssets#5727]
### URL(s) where the issue occurs

`https://xstreamcdn.com/f/6mo26r-jd9r`
`https://xstreamcdn.com/f/1lo6q502lv5`
`https://xstreamcdn.com/f/mz9kwz-319q`

### Describe the issue

Timer boosting

### Notes

adsbypasser/adsbypasser#3123

`xstreamcdn.com##+js(nano-setTimeout-booster.js)`

**Comment by gwarser** [comment]
@lain566 why did you removed issue link?

Looks like another case: https://www.reddit.com/r/uBlockOrigin/comments/cmxap7/embedded_youtubeads_inside_streaming_videos/ew6h7h8/

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/afc651acd3a5bf46b943529c870164c10d53f2e9

**Comment by lain566** [comment]
@gwarser Because this issue is not directly related, maybe this https://github.com/uBlockOrigin/uAssets/commit/f4265037725fcc1798c111deed5ef99ea5d69220#commitcomment-33760279
nobody had reported that issue so far
