### ISSUE TITLE
Breaks Gmail as of around 30th of May.

### ISSUE THREAD

**Issue by gordan-bobic** [uBlockOrigin/uAssets#5731]
### URL(s) where the issue occurs

Gmail:
`https://mail.google.com/mail/u/0/?tab=rm&ogbl#inbox`

### Describe the issue

Moving mail to a different folder from the inbox doesn't work.

### Screenshot(s)

No screenshot possible, the email just doesn't move when the relevant buttons are pressed.

### Versions

- Browser/version: Latest Google Chrome as of around 30th of May.
- AdNauseam 3.7.x and 3.8.x

### Settings

AdNauseam's defaults.

### Notes

Disabling the "uBlock Filders" block list restores correct behaviour.

**Comment by Hrxn** [comment]
WTH is AdNauseam?

**Comment by mapx-** [comment]
@gordan-bobic  test your issue using uBo. If still in trouble reopen this issue.
