### ISSUE TITLE
mandatory.com

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#5732]
`https://www.mandatory.com/fun/616695-best-episode-ever-26-terminator-the-sarah-connor-chronicles`

It shows a popup window saying that it detected your adblocker and asks you to disable it. It would be nice if ublock origin could work without websites giving error messages like that. Is there a way to fix that? Thanks. Have a nice day.

![mandatory com](https://user-images.githubusercontent.com/35790889/58764625-7c807680-8537-11e9-9ea3-6c88ba9f11f4.jpg)

Firefox 67.0 (64-bit)
ublock origin 1.19.6

**Comment by mapx-** [comment]
1. click "continue without supporting us"
or
2. enable uBlock filters – Annoyances​​​​​ list (in built-in section)
