### ISSUE TITLE
ghacks.net

### ISSUE THREAD

**Issue by TonyTough** [uBlockOrigin/uAssets#574]
### URL(s) where the issue occurs

`www.ghacks.net`

### Describe the issue

Anti-Adblock message immediately after the site or a subsite loads:

> Something interfered with this website loading
> This could be a temporary problem with your network, or due to your adblocker
> Try:
>     Check your internet connection and reload the page
>     If you are using an adblocker disable it by clicking on the adblock icon in your browser toolbar
>     If the problem persists, consider leaving a message on the adblock user forums

### Versions

- Browser/version: Firefox 54.0.1 (64bit)
- uBlock Origin version: 1.13.8

### Settings

- default + Easylist Germany

**Comment by okiehsch** [comment]
Are you sure you are using a default setup?
If you open your logger are these two requests  blocked?
![unbenannt](https://user-images.githubusercontent.com/16838044/28534206-25d4ed14-70a0-11e7-8362-9f9f4c5bfef3.PNG)

I ask because the only way to reproduce your issue is to block them.

**Comment by SMed79** [comment]
I have browsed many pages without seeing an anti adblock http://i.imgur.com/weIDrSf.png !!

@TonyTough Disable all other extensions, test again.

**Comment by okiehsch** [comment]
@SMed79 the anti-adblock is there, it uses the same method as `drudgereport.com`,
To reproduce delete all your `ghacks.net`-cookies, add 
`||adiode.com/http$xmlhttprequest,domain=ghacks.net` to your filters and then go to `ghacks.net`.

**Comment by SMed79** [comment]
Sorry, you're right http://i.imgur.com/V0Q9GWp.png

**Comment by TonyTough** [comment]
I deleted the cookies and refreshed again the filter lists and now it works.

Thanks for your help,
I will close the topic.

**Comment by gwarser** [comment]
On my side adiode was blocked by uBlock Protector List

**Comment by okiehsch** [comment]
I will add a fix for ghacks.net so anybody who wants to block `adiode.com` can block it.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/c3ee2551cdac39e2886ad2b5354bcd070056564e

**Comment by uBlock-user** [comment]
@mapx- `ghacks.net##+js(abort-current-inline-script, jQuery, aba_detector)` is invalid and should be removed fro uBlock Annoyances.
