### ISSUE TITLE
newsyou.info {ads}

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#5740]
`newsyou.info`
ads.
Region RU/UA, I subscribed to 2 regional subscriptions.
On the side, in the center, and below is also an advertisement {highlighted in blue or red or green, they change, you will immediately see}
It is impossible for her (I can not/Cosmetic filters included) to select it with the "Element selection", since everyone except her is selected. Can anything be done?

Default settings. Version-last beta. Firefox, the same situation on Opera

**Comment by mapx-** [comment]
upload a screenshot indicating the ads

**Comment by bogachenko** [comment]
`https://newsyou.info/izrailskaya-armiya-nanesla-moshhnyj-udar-po-sirii-video`
![Безымянный](https://user-images.githubusercontent.com/8535285/58781534-e8daa300-8627-11e9-83dc-c55d9e83ba69.png)

**Comment by bogachenko** [comment]
By the way, there are a lot of scum 3p sites, eg `dl6pkf7e.ru` (these are inline scripts), of course they are blocked by the rule `*$script,third-party,domain=newsyou.info` in RU AdList. 
but how about this
`newsyou.info##+js(abort-current-inline-script.js, document.createElement, 'script')`

**Comment by mapx-** [comment]
using the default settings and the 2 russian lists I get no such ads.

for your last filter => @dimisa-RUAdList

for element picker - if you provide the necessary steps - you could report here:
https://github.com/uBlockOrigin/uBlock-issues/issues

**Comment by bogachenko** [comment]
>using the default settings and the 2 russian lists I get no such ads.

>Default settings. Version-last beta. Firefox, the same situation on Opera

![large_p19d7nh1hm1i37tnuim11ebqo5c1](https://user-images.githubusercontent.com/8535285/58782733-052c0f00-862b-11e9-9fe2-182827361d1b.jpg)

**Comment by mapx-** [comment]
> I can not/Cosmetic filters included

?

**Comment by bogachenko** [comment]
>Cosmetic filters included

A day earlier, I turned them off (eats a lot of RAM) and then I could not block ads, I wrote to you, but I answered `okiehsch`/ Therefore, I write that there would be no difficulties, on this site I turned on cosmetic filters.

> I can not

Everything is highlighted except for blocks with advertising.

**Comment by dimisa-RUAdList** [comment]
@bogachenko 
Try to disable the AdGuard Russian filter.

**Comment by bogachenko** [comment]
@dimisa-RUAdList  Well, what should be the result? Advertising has remained. Pipette not working.

**Comment by bogachenko** [comment]
Да пофигу, тред закрылся не успев открыться. Странно что не ограничили возможность комментирования, как это делают в соседнем репозитории здесь. Не важно. Не работает и не работает. Кому есть до этого дело.

**Comment by mapx-** [comment]
@bogachenko are you using only uBo (with cosmetic filters ON) or something else ? (adblockers, tampermonkey etc)

**Comment by okiehsch** [comment]
The ads are inside a `#shadow-root container` I think the picker does not work because of that.
![image](https://user-images.githubusercontent.com/16838044/58785227-69c47b00-85e5-11e9-992b-b0aab81d77dc.png)

I can only reproduce the ads if I disable the russian lists.

**Comment by dimisa-RUAdList** [comment]
I do not see any problems on this site, but simultaneous use of two Russian filters is a very, very bad idea, which unfortunately is implemented by default.

**Comment by gwarser** [comment]
> The ads are inside a `#shadow-root container` I think the picker does not work because of that.

Known in general, but I don't think we have issue for this. This is closed shadow root, so hiding filters will not work. Some special procedural is needed to drill into it or scriptlet to prevent closing. 

Ameshkov created thread on https://hub.filterlists.com/t/circumvention-via-shadow-root/34 asking for preferred solutions.

**Comment by gwarser** [comment]
Ah - Picker. Yes, weird. Can also be effect of closed shadow root, picking twitter widgets [here](https://www.tv2.no/nyheter/10359148/) works.

Or maybe because it's shadow inside shadow(?): 

![image](https://user-images.githubusercontent.com/886325/58799173-d9962e00-8604-11e9-81e2-903204cab060.png)


uBO picks `.main` - _outer_ shadow?
