### ISSUE TITLE
Digitalocean cloud control panel doesn't load at all

### ISSUE THREAD

**Issue by emilfihlman** [uBlockOrigin/uAssets#5743]
### URL(s) where the issue occurs

`https://cloud.digitalocean.com/`

### Describe the issue

No content is shown, see screenshots

### Screenshot(s)

![image](https://user-images.githubusercontent.com/9070088/58823218-d4a39f80-8641-11e9-964a-0c0d2c9f0849.png)

![image](https://user-images.githubusercontent.com/9070088/58823228-d8cfbd00-8641-11e9-92ea-09ac6a067a5e.png)

### Versions

- Browser/version: Versio 74.0.3729.169 (Virallinen koontiversio) (64-bittinen)
- uBlock Origin version: 1.19.6

### Notes

Also opened an issue with DO support, lets see what they have to say.

**Comment by mapx-** [comment]
needing account.

However, try:

first:
||assets.digitalocean.com/prism/prism.js$script,redirect=noopjs,first-party

then (if still does not work)
@@||assets.digitalocean.com/prism/prism.js$script,1p

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/836e0795977726f52b546ef8d73c014e76d5a57d

**Comment by okiehsch** [comment]
If you update your `uBO-unbreak` list it should work again.

**Comment by emilfihlman** [comment]
Yup, works, thank you!
