### ISSUE TITLE
White bar on the top of Youtube fullscreen video

### ISSUE THREAD

**Issue by antoinepernot** [uBlockOrigin/uAssets#5759]
### URL(s) where the issue occurs

`https://www.youtube.com/watch?v=q9d5ht7mQUU`

### Describe the issue

_Sorry for my bad English._

When I toogle any video from Youtube, a white bar on the top of the screen appears. 

### Screenshot(s)

![Capture d’écran_2019-06-03_23-26-45](https://user-images.githubusercontent.com/1910415/58835927-96b17600-8657-11e9-826d-a96f49f17581.png)

### Versions

- Browser/version: Firefox 67.0 64 bits / Ubuntu 18.04
- uBlock Origin version: 1.19.6

### Settings

_No custom setting applied._

### Notes

After some research on this issue, this white bar can be removed by adding this rule : 

`youtube.com##.no-scroll #page-manager:style(margin-top: 0px !important)`

Source of the specific rule : [https://www.reddit.com/r/firefox/comments/bmxgbh/what_causes_this_white_bar_to_appear_in_the/eo8wpsq?utm_source=share&utm_medium=web2x](url)

**Comment by okiehsch** [comment]
Fixed in `uBO-annoyances`.

**Comment by gwarser** [comment]
Can be removed? https://bugzilla.mozilla.org/show_bug.cgi?id=1550759#c56
