### ISSUE TITLE
ebates/rakuten

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#5764]
### URL(s) where the issue occurs

`https://www.ebates.com/`
`https://www.rakuten.com/help`

### Describe the issue

Doesn't redirect to Rakuten, as it should. Requires log in.
Rakuten broken, can't click items on help page.
### Notes

`@@||www.ebates.com/dist/static/rev/global/analytics/stats-d2745e1ae9.js$script`
`@@||www.rakuten.com/dist/static/rev/global/analytics/stats-d2745e1ae9.js$script`

**Comment by terrorist96** [comment]
Just for clarity, the `rakuten` issue can be reproduced without logging in.

**Comment by okiehsch** [comment]
Does the redirection
`||ebates.com/dist/static/*/analytics/*$script,1p,redirect=noopjs`
work on your end or is the exception
``@@||ebates.com/dist/static/*/analytics/*$script,1p`
needed?

**Comment by terrorist96** [comment]
> Does the redirection
> `||ebates.com/dist/static/*/analytics/*$script,1p,redirect=noopjs`
> work on your end

No

> or is the exception
> `@@||ebates.com/dist/static/*/analytics/*$script,1p`
> needed?

Yes

> Make sure to remove the exception before you test the redirection and to load the site bypassing the cache,

I did. :smiley:

**Comment by okiehsch** [comment]
Thanks.
