### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#5766]
how to remove?

```js

<script language=JavaScript>
--
  |  
  | <!-- Begin
  | var how_many_ads = 5;
  | var now = new Date()
  | var sec = now.getSeconds()
  | var ad = sec % how_many_ads;
  | ad +=1;
  | if (ad==1) { txt= "";url="https://{shit.com}"; alt="{title}"; banner="https://{shit.gif}"; width="360"; height="300";}
  | if (ad==2) { txt= "";url="https://{shit.com}"; alt="{title}"; banner="https://{shit.gif}"; width="360"; height="300";}
  | if (ad==3) { txt= "";url="https://{shit.com}"; alt="{title}"; banner="https://{shit.gif}"; width="360"; height="300";}
  | if (ad==4) { txt= "";url="https://{shit.com}"; alt="{title}"; banner="https://{shit.gif}"; width="360"; height="300"; }
  | if (ad==5) { txt= "";url="https://{shit.com}"; alt="{title}"; banner="https://{shit.gif}"; width="360"; height="300"; }
  | document
  | document.write('<center>');
  | document.write('<a href=\"' + url + '\" target=\"_blank\">');
  | document.write('<img src=\"' + banner + '\" width=')
  | document.write(width + ' height=' + height + ' ');
  | document.write('alt=\"' + alt + '\" border=0>');
  | document.write('<small>' + txt + '</small></a>');
  | document.write('</center>');
  | // End -->
  |  
  | </script>

```

**Comment by gwarser** [comment]
`+js(abort-current-inline-script.js, document.write, shit.com)`

**Comment by bogachenko** [comment]
there are 3-5 different sites `shit.com` (prescribe for each long / many) is there another way?

***
ANYWAY thx

**Comment by gwarser** [comment]
`shit.com` is just a string unique to this `<scipt>` to abort only this one (scripts without it will not be aborted).

**Comment by bogachenko** [comment]
You do not understand, on one pornsite many such codes `<script>` from 3-5 in each code `<script>` different sites `shit.com`.
`+js(abort-current-inline-script.js, document.write)`
fits perfectly. nothing breaks and all in one line

**Comment by mapx-** [comment]
which is the site ?

**Comment by bogachenko** [comment]
never mind

**Comment by bogachenko** [comment]
`https://7mmtv.tv/zh/censored_content/70048/[DDOB-029]軟体ツルペタビッチ妻柔軟なカラダで男を喰いまくる超性欲人妻%20鈴木みか/index.html`
New question how to decrypt inline-`decryptoJS`?

**Comment by llacb47** [comment]
@bogachenko Close this issue and create a new one.

**Comment by bogachenko** [comment]
@llacb47  This issue is already closed. And I don't want to spam by creating new questions. If they not responded = not know / ignore / not have read, but will read

**Comment by okiehsch** [comment]
If you mean
````
decrypto('130g302g243g324g110g253g250g255g321g321g131g104g324g243g302g303g245g103g320g245g325........
````
I don't know. ;)

**Comment by bogachenko** [comment]
I googled on this topic, it seems xor js cryptor. need a password to decrypt it. but I can't find it on that page. so I just asked.

**Comment by gwarser** [comment]
@bogachenko do you want to decrypt this manually? In console? Then this is easy, script is already in source with keys. Looks like this beautified:

```html
magic = 15;

function decrypto(param_str) {
    let inArray = [];
    let outArray = [];
    magic = magic <= 25 ? magic : magic % 25;
    let param_str_SEP = String.fromCharCode(magic + 97);
    inArray = param_str.split(param_str_SEP);
    for (let i = 0; i < inArray.length; i++) {
        let outCharCode = parseInt(inArray[i], magic);
        /** @param_str {number} */
        outCharCode = outCharCode * 1 ^ xor_mask;
        let outChar = String.fromCharCode(outCharCode);
        outArray.push(outChar);
    }
    let dfgfhfgh = outArray.join("");
    return dfgfhfgh;
}

xor_mask = 8;
```

**Comment by bogachenko** [comment]
@gwarser Thank you, this script is nothing special, but I don't quite understand how you did it. The console browser displays only errors and warnings. Can you explain by control points?

***
I load sites with script blocking enabled, watch guts and if there is nothing I allow a scripts. But how can I check **this** inline-script **without loading** it, because if I do not allow the scripts, then this script will not appear in the console, yep? maybe, it is a virus?

**Comment by bogachenko** [comment]
How to remove `SHIT_URL.COM` from this button and leave only `NORMAL_URL.NET` ???
@gwarser 

```js
<a href="SHIT_URL.COM" onclick="location.href='SHIT_URL.COM';" onauxclick="return false;" nameHost="NORMAL_URL.NET" link="NORMAL_URL.NET" validity="valid" dateLastChecked="0/00/00, 0:00 AM" id="123456789" target="_blank" class="host btn btn-md btn-default btn-block btn-3d hvr-bounce-to-right">
    <i class="fa fa-fw fa-download"></i>Download
</a>
```

**Comment by bogachenko** [comment]
Any ideas on how to make a cosmetic filter that will bypass it?

**Comment by bogachenko** [comment]
Breaks video viewing.

```
! https://www.reddit.com/r/uBlockOrigin/comments/h7auye/noodlemagazinecom_ads/
*.mp4|$media,domain=noodlemagazine.com
```
