### ISSUE TITLE
Arc uses bandwidth without opt-in

### ISSUE THREAD

**Issue by wh0** [uBlockOrigin/uAssets#5771]
### URL(s) where the issue occurs

`https://arc.io/product/`

This is a page about the script, which itself uses the script.

`https://hypem.com/popular`

### Describe the issue

Arc uses bandwidth and isn't opt-in. From the description (emphasis added):

> While on this website, Arc unites a little unused **bandwidth from your device** with millions of others to form a people-powered cloud network. Companies rent this community network and proceeds reward users and sustain sites, like Arc.io.
> 
> **Without doing** or giving up **anything** (including your privacy, personal data, or device performance), **users crowdfund** their favorite websites with spare **bandwidth**, not their wallets. And a portion goes to open Internet advocates, like Wikipedia.
> 
> **By visiting Arc-powered sites**, you help shape a better Internet… with less advertising, more privacy, and faster websites.
> 
> Arc.io welcomes you to the community and thanks you for your support! 

### Screenshot(s)

n/a

### Versions

- Browser/version: Firefox 67.0
- uBlock Origin version: v1.19.6

### Settings

n/a

### Notes

Their installation instructions say to add this script to a page:

```html
<script async src="https://arc.io/widget.js?[YOUR_WIDGET_ID]&cdn=False"></script>
```

or this script:

```html
<script async src="https://arc.io/widget.js?[YOUR_WIDGET_ID]&cdn=True"></script>
```

Also, I found a service worker in my browser with the script https://arc.io/arc-sw-loader.js

Their opt-out page: https://arc.io/optOut/

**Comment by eplayerclick** [comment]
You do not want ads, you do not want anything, you just want people to work and give you free content.
