### ISSUE TITLE
uBlockOrigin for Chrome Erroneously Blocking my Site

### ISSUE THREAD

**Issue by davecom** [uBlockOrigin/uAssets#5773]
### URL(s) where the issue occurs

`https://btvdaily.com`

### Describe the issue

I had a user report that uBlock Origin is blocking my site as malware. It's not malware.

### Screenshot(s)

N/A

### Versions

They said it was uBlock Origin Plugin for Chrome
- Browser/version: Chrome
- uBlock Origin version: ?

### Settings

- N/A

### Notes

This was reported to me by a user. It's erroneous. I'd be interested in knowing why my site was blocked.

**Comment by okiehsch** [comment]
> This was reported to me by a user.

I can report to you that I can access your site without issue with uBO enabled.
![image](https://user-images.githubusercontent.com/16838044/59085981-a9020d00-8900-11e9-8779-f91ecd267a15.png)

Have you tried yourself?

**Comment by mapx-** [comment]
maybe it's about some elements blocked by fanboy's annoyances list, such as
`PopupSignupForm_0` but @davecom  you have to test yourself and report what functionality is broken

@ryanbr

**Comment by davecom** [comment]
Ah makes sense; we do have a popup. Thank you.
