### ISSUE TITLE
mlwbd.website

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5776]
### URL(s) where the issue occurs

`https://mlwbd.website/movie/omerta-2018-480p-720p-x264/`

### Describe the issue
popup ads
### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.19.6
### Settings

- uBO's default settings

**Comment by yourduskquibbles** [comment]
@mapx- FYI I pushed an update for an empty floating div left behind forgot to put this # in push though so wasn't shown here

https://github.com/uBlockOrigin/uAssets/commit/0efa2efdfbd8bd9cc1a15164d46a9cd64419da5c

**Comment by ghajini** [comment]
scriptlet filters no longer req.

`https://mlwbd.casa/movie/desire-to-kill-2010-full-movie-online-download/`
