### ISSUE TITLE
torrentz.colorask.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#579]
### URL(s) where the issue occurs

`https://torrentz.colorask.com/search/?q=tv`

### Describe the issue

gomovies123 ad

fix:
`##.col-sm-2 > div > div:nth-of-type(1)`

**Comment by okiehsch** [comment]
`torrentz.colorask.com##.col-sm-2` can be added to Easylist.
fyi @ryanbr
