### ISSUE TITLE
yts.lt

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#5791]
yts.lt

Hi, when you go to yts.lt, and block "3rd-party" and "3rd-party scripts" in ublock origin's advanced settings for that page, then click on "browse movies" in the top right corner, a ublock origin popup tab/window (depending on your browser setting) automatically appears that says 

> uBlock Origin has prevented the following page from loading:
> `https://pegloang.com/1655785.html?q`
> 
> Because of the following filter
> ||pegloang.com^
> Found in: uBlock filters 
> 
> Disable strict blocking for pegloang.com.

 

Is there any way to fix that so that? I've already purged and updated all the filter lists. Thanks. Have a nice day.

![yts lt](https://user-images.githubusercontent.com/35790889/59151674-3f1f5b80-8a05-11e9-9c35-3fc8300eb2d7.jpg)

![ublock origin](https://user-images.githubusercontent.com/35790889/59151676-434b7900-8a05-11e9-802d-fdb46800adbe.jpg)

firefox 67.0.1 (64-bit)
ublock origin 1.19.6

**Comment by IoanPaleru** [comment]
Ok, thanks. Do I need to do anything with this "! https://yts.am/movie/cars-3-2017
! https://github.com/uBlockOrigin/uAssets/issues/2100
! https://github.com/uBlockOrigin/uAssets/issues/5397
yts.am##+js(abort-current-inline-script.js, Math, zfgloaded)
yts.*##+js(abort-current-inline-script.js, Math, zfgloaded)
yts.am##[id*="container"][id^="id"]
yts.am##html:style(overflow: auto !important;)" from "https://github.com/uBlockOrigin/uAssets/commit/6a2927ff992653e9447f053eb2d12850d14efba8" like paste it into the settings or something, or does that page just mean that it's been update in ublock origin? Thank you. Have a nice day.

**Comment by mapx-** [comment]
go into dashboard / settings, `filter lists` tab, update `uBlock filters`
