### ISSUE TITLE
goodnewsnetwork.org (caused by gcomrarlta.com)

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#5792]
Continued on from https://forums.lanik.us/viewtopic.php?f=62&t=43117 (in which most of the relevant info is listed, except I didn't know at the time that it only caused problems when using adblockers), after I realised that it was probably going to be stuck in EasyList's GitHub PR tracker for the next few months, thus I'm bringing it to uAssets instead.

### URL(s) where the issue occurs

`https://www.goodnewsnetwork.org/`, `https://www.yummytummyaarthi.com/2019/02/easy-mutton-curry-recipe.html`, `http://www.alifeinbalance.net/`

### Describe the issue

`gcomrarlta.com` seems to be a tracking server, which on non-adblock-using setups seem to behave pretty much like normal tracking servers, but which when using adblockers goes absolutely ballistic instead, trying to load several dozen/hundreds of tracking images and JavaScript files, bringing the browser to a screeching halt after ~15sec, using 40-80% of the CPU, and can even cause unrelated element hiding rules to fail.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/22780683/59154190-2054af80-8a6d-11e9-8b81-c691756e58f9.png)

### Versions

Tested on at least two different setups, one of them being:

- Browser/version: Chrome 75.0.3770.80 64-bit for Windows
- uBlock Origin version: Nano Adblocker 1.0.0.114

### Settings

My Chrome setup has had too many changes to list. I can list my Vivaldi test setup instead on request.

### Notes

Other accounts of `gcomrarlta.com` causing very severe problems:
* https://forum.palemoon.org/viewtopic.php?t=22235&p=168423
* The comment at the bottom of `https://www.yummytummyaarthi.com/2019/02/easy-mutton-curry-recipe.html`

**Comment by okiehsch** [comment]
It's actually an ad-reinsertion script, you can see that it pulls ads if it detects one uses an adbocker.
It is ridiculously heavy and basically makes the site unusable.
`gcomrarlta.com` is already blocked in `uAssets`.
https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L21192

**Comment by okiehsch** [comment]
If you add
````
alifeinbalance.net,goodnewsnetwork.org,yummytummyaarthi.com##+js(abort-current-inline-script.js, document.createElement, ='\x)
````
you should not see any `gcomrarlta.com` requests at all.

**Comment by DandelionSprout** [comment]
I must admit that I was unaware of https://github.com/uBlockOrigin/uAssets/commit/576a41b47dfca98fa5429ac3607fd6f938414ce2#diff-728d382ab45d1e85df51bb432db0ce90. Had I known that it had already been fixed in uAssets, I most probably wouldn't have ended up writing this issue report after all, and would simply have refreshed my list in the extension settings instead. 😅

Nevertheless, I thank you (and mapx-) quite a lot for all this research and for this very thorough multi-approach fix for this which seems to fixed the problem.
