### ISSUE TITLE
dreamfancy.org

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#5797]
### URL(s) where the issue occurs

- `https://www.dreamfancy.org/`

### Describe the issue

- Anti-Adblock Script - Antiblock

### Versions

- Browser/version: Firefox 67.0.1
- uBlock Origin version: 1.19.7rc2

### Settings

- Default filters

**Comment by llacb47** [comment]
Can't reproduce.  Can you take a screenshot?

**Comment by llacb47** [comment]
Try 
`dreamfancy.org##+js(addEventListener-defuser.js, click)
*$popup,third-party,domain=dreamfancy.org`

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/59169321-219fde00-8b3a-11e9-8e10-43e831fa0759.png)

**Comment by bogachenko** [comment]
@okiehsch forgot to block ads (SALTANATMT2 ADVERTISE) => https://github.com/uBlockOrigin/uAssets/issues/5797#issuecomment-500268853
