### ISSUE TITLE
doshort.info

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#5798]
### URL(s) where the issue occurs

- `http://doshort.info/GUK`

### Describe the issue

- Anti-Adblock Script - BlockAdBlock
- Request for timer boost

### Versions

- Browser/version: Firefox 67.0.1
- uBlock Origin version: 1.19.7rc2

### Settings

- Default filters

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
