### ISSUE TITLE
pornhub.com [NSFW]

### ISSUE THREAD

**Issue by distren** [uBlockOrigin/uAssets#5799]
### URL(s) where the issue occurs

`https://www.pornhub.com/view_video.php?viewkey=ph5cd3984c39c73`
 (NSFW) for example, but it seems to occur on every video

### Describe the issue

Advertisements are showing up in the right column instead of the recommended videos.

### Screenshot(s)

https://imgur.com/50XwbfB

### Versions

- Browser/version: Firefox Developer Edition 68.0b8 20190606101422
- uBlock Origin version: 1.19.6

### Settings

- I have a bunch of other filter lists enabled, but I tested with a fresh profile + default uBO and the ads still show up.

### Notes

The ads started showing up for me a few days ago. The ads don't appear in Chrome + uBO. The ads seem to come from an inline script after the closing `</html>` tag:
```
...
</html>
<script>window.zone_6={"zone_id":"6","link":"http:\/\/cp.cbbp1.com.\/_z\/eyJjbGljayI6Imh0dHBz...
</script>
```
I have added this filter
```
www.pornhub.com##^script:has-text(window.zone_)
```
which seems to work.

**Comment by dumbusernameidk** [comment]
ads are back this time they are inside a shadow root. can hide them with `##dmuhx` but that is an ugly fix.

**Comment by okiehsch** [comment]
Does
`pornhub.com##+js(abort-current-inline-script.js, Math, createShadowRoot)`
work without breaking anything?

**Comment by dumbusernameidk** [comment]
everything seems to be working and the ads are gone.

**Comment by dumbusernameidk** [comment]
ads back again they sit inside a shadowroot again. like if you look at the DOM it just goes `#shadow-root (closed)`

**Comment by mapx-** [comment]
Could you test
`pornhub.com##+js(aopr, HTMLElement.prototype.attachShadow)`

**Comment by dumbusernameidk** [comment]
Sorry for the late response but yes that filter does work thank you.

**Comment by in4u** [comment]
Please update rules to include `pornhub.org` and `pornhub.net` mirrors as well, like was done for [onion](https://github.com/uBlockOrigin/uAssets/commit/202365c6363d02f8ed83500d6b2e6d9eea65a941).

**Comment by in4u** [comment]
Clicking any video thumbnail on the first visit of homepage in private browsing mode is triggering a popup. Subsequent clicks anywhere in the same session don't seem to trigger it.

**Comment by THEtomaso** [comment]
@mapx-

### Issue:
Video playback fails @ `pornhub.com`, when using Pale Moon + uBO Legacy.

### How to reproduce:
1 - First, this UA override needs to be added in Pale Moon, to circumvent Pornhub's faulty UA sniffing (in `about:config`):
```
general.useragent.override.pornhub.com
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
```

2 - Try to play a video @ `pornhub.com`.

Result: Playback fails!

### Problem filter:
* uBlock filters

### Problem rule:
`pornhub.*,pornhubthbh7ap3u.onion##+js(aopr, HTMLElement.prototype.attachShadow)`

### Possible fix (for 'uBlock filters - Legacy'):
`pornhub.*,pornhubthbh7ap3u.onion#@#+js(aopr, HTMLElement.prototype.attachShadow)`

### Note:
As a result of disabling the problem rule, additional blocking rule(s) will be necessary.
I've come up with a couple rules, and posted them here:
`https://forum.palemoon.org/viewtopic.php?f=3&t=23825&start=20#p185749`
..but I'm not sure if they're completely good ones.

### PS:
Perhaps Pornhub's faulty UA sniffing can be circumvented with a `##+js` rule too?

**Comment by uBlock-user** [comment]
> As a result of disabling the problem rule, additional blocking rule(s) will be necessary.
I've come up with a couple rules, and posted them here:

Does `pornhub.*,pornhubthbh7ap3u.onion##+js(set-constant.js, HTMLElement.prototype.attachShadow, null)` work instead ?

**Comment by THEtomaso** [comment]
Yes, that seems to do the trick! :)

**Comment by uBlock-user** [comment]
any additional filters required ?

**Comment by mapx-** [comment]
Even without that replacing filter I get no ads (on right side)

**Comment by THEtomaso** [comment]
> any additional filters required ?

Well, there seems to be some empty containers on the front page.
This rule (which I posted in the Pale Moon forum) seems to take care of them:
`pornhub.*,pornhubthbh7ap3u.onion##.alpha`
Not sure if it has any side-effects, although I don't see any at the moment.

**Comment by uBlock-user** [comment]
> pornhub.*,pornhubthbh7ap3u.onion##.alpha

That hides lots of thumbnails on Firefox and one menu component too.

**Comment by THEtomaso** [comment]
This takes care of the menu component:
`pornhub.com##.alpha:not(.menu)`
Don't see any missing thumbnails though.

**Comment by uBlock-user** [comment]
@THEtomaso I added `pornhub.*,pornhubthbh7ap3u.onion##.alpha` in the Legacy list.

**Comment by THEtomaso** [comment]
Think you've better remove it.
I'm not all that familiar with the site, and which things should be shown there.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/f9d8b8281de88adf20603f4f2322238e0d4224e6

I confirm: it's a wrong filter in palemoon too, removed

**Comment by uBlock-user** [comment]
> Aren't there any ampty containers in other browsers?

Oh I see one the right hand side on every video, but targetting it only hides two other child elements, not the parent element unfortunately.

**Comment by THEtomaso** [comment]
Like I pointed out, adding `:not(.menu)` at the end takes care of the broken menu item.
Could you post a link with broken thumbnails?

**Comment by mapx-** [comment]
It happens on the home page.

**Comment by uBlock-user** [comment]
On Firefox ? The homepage itself.

**Comment by THEtomaso** [comment]
I don't see it, but some of the **+More Videos** buttons are moved to offset positions.
Guess those empty containers really doesn't matter that much, anyway.

But what about that nasty UA sniffing of theirs..
Could it be remedied through a script injector rule?

**Comment by uBlock-user** [comment]
> I don't see it,

Put the ##.alpha and then click Preview and undo Preview, notice the difference.

**Comment by THEtomaso** [comment]
Actually, that function doesn't work for me.
Neither in Pale Moon, nor in Chromium-ungoogled.
When pressing "Preview", the page simply seems to gets a modal overlay.

**Comment by in4u** [comment]
There's a breakage. The related videos in the right hand sidebar are blocked.

Also, on `.org` (for Indian IP address) and perhaps on `.net` mirror too, there's an ad overlay box which is coming up on pausing the video. This was an old problem which was solved when @mapx- updated the filters to include the mirror domains. It has come back after today's changes.

**Comment by Vangelis66** [comment]
Pale Moon **28.8.4** 32-bit; uB0-legacy **1.16.4.19**; filters hard-refreshed to their latest versions. 
Perhaps one of you filter wizards can solve the following PornHub puzzle: 

Sample URL : `https://www.pornhub.com/view_video.php?viewkey=ph5e5eac0502707` 

With either `uBlock filters`, `Easylist` or **both** enabled, the right-hand sibebar space is completely empty: 
![ph-bad](https://user-images.githubusercontent.com/9669492/76710941-2cfce700-6714-11ea-8a77-016c9b084e34.JPG)
and it's empty all the way down if you scroll...

With both `uBlock filters` and `Easylist` **both disabled**, the sidebar contains first two empty containers (the space where ads normally show up is `www.pornhub.com##.clearfix.RANDOMSTRING > div:nth-of-type(3) > div`) followed by two **needed** sections, the **Related Videos** and the **Live Cam Models** one: 
(NSFW) `https://imgur.com/ZxYSmEj`
Disabling `Easylist` unfortunately causes other annoyances in PornHub, e.g. pre-video ads, overlay ads when you pause the video playback, etc... 
Unfortunately, I have close to no experience in filter lists but, the way I see it, 
1. Both `Easylist` and `uBlock filters` have some overlap in their capacity to kill **fully** the right-hand sidebar...
2. The `Easylist` pornhub "sidebar" rule has to be negated (probably an issue to be reported to its maintainers), while the `uBlock filters` pornhub "sidebar" rule has to be amended to allow those two wanted sections (just below the two ad containers when uB0 is disabled on pornhub) ...

I hope it's an issue that can be tackled... Thanks in advance, thanks to all for your outstanding efforts in providing those filters to such wide communities! 👍 

EDIT: Though on Firefox, I think @in4u's comment

> The related videos in the right hand sidebar (of the currently playing video) are blocked.

contains the same issue as the one I'm experiencing under latest Pale Moon with uB0-legacy!

**Comment by mapx-** [comment]
@in4u  I cannot test .net / .org

However, I used an UK vpn and I can reproduce the missing right column
test
`pornhub.*#@#+js(aopw, AdDelivery)`

**Comment by in4u** [comment]
I may not be available for a little while but just quickly tested .com with a US IP and the sidebar seems to be back.

Not sure about .net but you can test .org with HTTPS on Indian IP (`https://www.pornhub.com` gets redirected to `https://www.pornhub.org` in that case).

**Comment by mapx-** [comment]
@Vangelis66 

test
```
pornhub.*#@#script:inject(set-constant.js, atob, trueFunc)
pornhub.*#@#script:inject(abort-on-property-write.js, AdDelivery)
```

**Comment by Vangelis66** [comment]
@mapx- 

Thanks for looking into this 👍 ; I tested your code in `My filters` (PM 28.8.4, uB0-legacy 1.16.4.19) and two problems: 

1. `Easylist` **disabled**, `uBlock filters` **enabled**: The **Related Videos** and **Live Cam Models** sections **do reappear** in the right sidebar, but not **until I scroll down considerably** (pay attention to the tab content scrollbar in the linked screengrab): 

(NSFW) `https://imgur.com/fzeff3R`

That vertical gap can be reduced considerably by the following cosmetic rule: 

`||cdn1d-static-shared.phncdn.com/iframe-1.1.5.html$subdocument`

The bit at the top that still remains is of code: 

`##.clearfix.randomalphanumericstring`

2. Once `Easylist` is **re-enabled**, the "sidebar" again turns completely empty 💢 Optimally, we would want a solution with `Easylist` enabled, for reasons outlined in my previous comment 😜 

I browsed quickly the latest `Easylist` code and there are **419** (!) occurrences of the string `pornhub` in it, it's quite hard for me to pinpoint the rule responsible for wiping out the right sidebar...
BTW, it's 02:30 (am) here, so I'll be turning in soon... 
Perhaps @THEtomaso (our PM specialist!) can devise something once the new day dawns...

**Comment by Vangelis66** [comment]
@mapx- 

(Posting a new comment so as you get properly re-notified!) 

My report on my immediately previous comment was based on your initial code: 
```
pornhub.*#@#script:inject(set-constant.js, atob, trueFunc)
pornhub.*#@#script:inject(abort-on-property-write.js, AdDelivery)
```
However, you edited the code while I was composing my report and **I was not notified by GitHub**... Sorry!
Testing now the amended code: 

```
pornhub.*,pornhubthbh7ap3u.onion#@#script:inject(set-constant.js, atob, trueFunc)
pornhub.*,pornhubthbh7ap3u.onion#@#script:inject(abort-on-property-write.js, AdDelivery)
@@||static.trafficjunky.com/ab/ads_test.js$script,domain=pornhub.com|pornhub.net|pornhub.org|pornhubthbh7ap3u.onion
```
I am **pleased to report** that _it appears to be doing the trick fine_ 🥇 with **both** `uBlock filters` & `Easylist` **enabled**; a job very well executed! 👍 

Other testers on **other browsers** should also confirm my findings... Will keep an eye for when the code is merged... Many thanks again!

**Comment by in4u** [comment]
Oh man, I just finished testing your filters and was coming here to report results only to see you made a fresh commit! I'll share the results anyway:

With https://github.com/uBlockOrigin/uAssets/issues/5799#issuecomment-599276681, .com was ok but .org still had breakage and pause overlay.

With https://github.com/uBlockOrigin/uAssets/issues/5799#issuecomment-599279485, .com was ok but .org still had breakage, pause overlay plus weird problems on playing certain videos. Like some video wouldn't play unless it was clicked on at least 4-6 times (and play button control was disabled during that time). In one instance, the video eventually started playing but with a small black rectangle overlay stating that "Video is not available at the moment".

With the recent commit, .com is ok but .org still had breakage and pause overlay. However, enabling Adguard Annoyances filter gets rid of the breakage and sidebar comes back. Strange! Pause overlay still remains though.

**Comment by mapx-** [comment]
> enabling Adguard Annoyances filter gets rid of the breakage and sidebar comes back

that list has 3 pornhub.com filters, I don't understand how could fix the issue

I tried some free socks5 for India , does not work

**Comment by in4u** [comment]
If I disable Adguard Annoyances list and just test with their 3 rules separately, it doesn't work. I suspect some content is perhaps being loaded through another CDN or site which is somehow being addressed by AG.

**Comment by in4u** [comment]
The sidebar in one of the broken modes and pause overlay mention ads from TrafficJunky. Maybe it's one of the ad serving domains or CDN which is impacting things. How to investigate what's happening?!

**Comment by in4u** [comment]
See if you can find any working HTTP/S proxy from [here](http://free-proxy.cz/en/proxylist/country/IN/https/ping/all). It worked for me with `https://www.pornhub.org`. Somehow any SOCKS based proxy doesn't seem to work.

**Comment by mapx-** [comment]
with firex:

> Your requested URL has been blocked as per the directions received from Department of Telecommunications, Government of India. Please contact administrator for more information.

**Comment by mapx-** [comment]
it seems firefox needs this filter too
`@@||static.trafficjunky.com/ab/ads_test.js$script,domain=pornhub.com|pornhub.net|pornhub.org|pornhubthbh7ap3u.onion`

**Comment by in4u** [comment]
Bingo! After adding that filter, the sidebar is back even without AG. Now only the pause overlay remains.

**Comment by mapx-** [comment]
Did you try the element picker for the overlay ?

**Comment by in4u** [comment]
Here's a screenshot of the pause overlay:

![ss](https://user-images.githubusercontent.com/43062185/76765231-10b48500-67bc-11ea-8f50-9d47c882aad7.png)

Order of rogue layers in element picker is: ###pb_block and then ###pb_template. With ###pb_template rule, I see no problem with play/pause and overlay gone.

**Comment by mapx-** [comment]
`pornhub.*,pornhubthbh7ap3u.onion###pb_template` => is breaking the pages ?

**Comment by in4u** [comment]
No, that filter is fine and not causing any problem.

It's probably due to previous filters or something else. What I noticed is that randomly a video will not load and the orange loading spinner will keep on spinning. On reloading the page, everything will be normal. If choosing to wait instead of reloading then after a while it may display overlay message "Video is not available at the moment" just as the video starts playing.

On one video the reloading trick didn't work and the spinner kept on spinning waiting for video to load. Refreshed 3-4 times. Finally, wondering what resource was it waiting for I opened the network monitor and reloaded the page. But the next load was the fastest the site ever loaded a video, at par with .com version! (Not sure why but .org takes slightly longer to start playing a video than .com)

**Comment by ghajini** [comment]
@mapx- if you want to test yourself, try tunnelbear vpn for PC...browser extension proxies never work in india

**Comment by mapx-** [comment]
thx @ghajini finally I got it running

**Comment by uBlock-user** [comment]
Those proxies are transparent, they will never work anywhere else either.

**Comment by in4u** [comment]
@Alex-302 If you are still struggling with https://github.com/AdguardTeam/AdguardFilters/issues/51307 then can you please try the above suggestion by @ghajini and test using Tunnelbear VPN for PC?

**Comment by Alex-302** [comment]
@in4u nothing:(

**Comment by in4u** [comment]
@Alex-302 I just checked the HTTP proxy `117.255.222.64:53281` which worked well. Another is `14.140.131.82:3128` but it's very slow and just barely redirects from `.com` to `.org` and fails to load full content. Let me know if they help you test the redirection.

**Comment by Alex-302** [comment]
This is impossible to select specific proxy in Tunnel Bear.
I can check it using AnyDesk.

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/77544701-08da9c00-6eb2-11ea-96d7-0de3cc18aba6.png)

**Comment by in4u** [comment]
@Alex-302 I have a feeling that scientists will develop a vaccine for COVID-19 sooner than you can figure out a way to reproduce this `.com` to `.org` redirection, haha! BTW have you tried every single proxy I listed [here](https://github.com/AdguardTeam/AdguardFilters/issues/51307#issuecomment-603491837) at one go in a single session? It's very unlikely that all those proxies are down simultaneously. I checked randomly and found a few still up.

**Comment by ghajini** [comment]
Hello @in4u most of ip you are suggesting or (proxies in web for india) are from airtel/idea/vodafone/bsnl ISP on which pornhub/pornhub alternative sites are strictly blocked on govt orders,so no matter how you convince alex-302/ or uassets contributors ,they will not be able to reproduce unless they are good ip address......

**Comment by uBlock-user** [comment]
These transparent proxies will be detected and blocked, use a VPN that offers end to end tunnel.

**Comment by in4u** [comment]
I know @ghajini but not all Indian ISPs have blocked these mirrors. I only shared those specific proxies which were personally tested by me and found unblocked. The only problem is their chances of going offline increase with the delay between my sharing them and the time they are put to test. To overcome this, I has listed a bunch of proxies in the other thread in the hope that not all 10 of them would be offline simultaneously.
