### ISSUE TITLE
deadline.com

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#58]
Hi, 
when you block ads on `deadline.com` from subdomains (cdn2. & cdn3.) you get redirection to anti-adblock page http://i.imgur.com/xJ1owoZ.png
```
||cdn*.deadline.com^
||deadline.com^$inline-script
```

Thank you.

**Comment by gorhill** [comment]
I don't get the redirections. These cosmetic filters however helped:

    deadline.com###masthead-sticky-wrapper ~ div
    deadline.com##[id^="baseContainer_"]

**Comment by SMed79** [comment]
Thanks for the filter.
Btw, i still get redirection !
https://a.pomf.cat/vqwwes.webm

**Comment by mapx-** [comment]
already fixed by easylist

**Comment by uBlock-user** [comment]
@okiehsch Anti Adblock on deadline.com : 

![](https://i.gyazo.com/efa7fed8f94b0e504628785f93119014.png)

Filter - `deadline.com##script:inject(abort-on-property-write.js, _sp_)`

**Comment by terrorist96** [comment]
### URL(s) where the issue occurs

`https://deadline.com/2018/12/harvey-weinstein-lawyer-witnesses-lied-claim-new-york-district-attorney-1202518505/`

### Describe the issue

Wait 10 seconds to be redirected. Can it be bypassed?

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/49892619-68c14680-fe17-11e8-9e09-0bdb58a05b46.png)

**Comment by mapx-** [comment]
Does work for you ?
`deadline.com##+js(set-constant.js, pmc_admanager.interrupt_timer, noopFunc)`

**Comment by terrorist96** [comment]
> Does work for you ?
> `deadline.com##+js(set-constant.js, pmc_admanager.interrupt_timer, noopFunc)`

No. It just removed the countdown but keeps the rest.
![image](https://user-images.githubusercontent.com/12802056/49897008-e9d20b00-fe22-11e8-8d2f-df0a22ca570c.png)

**Comment by mapx-** [comment]
What about

`||wp.com/wp-content/themes/vip/pmc-plugins/$script,domain=deadline.com`

**Comment by terrorist96** [comment]
> What about
> 
> `||wp.com/wp-content/themes/vip/pmc-plugins/$script,domain=deadline.com`

Yes

**Comment by ghost** [comment]
https://github.com/user-attachments/assets/c263beda-86b8-477e-8bb1-54f74643b330)

"Loading ad" screen on the player

`https://deadline.com/2026/01/trump-netflix-warner-bros-paramount-comments-1236702915/`

**Comment by mapx-** [comment]
I see no differences with / without uBO enabled, same delay

"ad loading" could be hidden using
`deadline.com##.ad-label`
