### ISSUE TITLE
123movies.net popup

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#580]
### URL(s) where the issue occurs

`http://123movies.net/watch/0v85o1xw-the-fate-of-the-furious.html`

### Describe the issue

Clicking on the video or version will cause a popup to `35.184.169.188`

**Comment by terrorist96** [comment]
@okiehsch still getting popups even if you inject the nowebrtc.js file.
![image](https://user-images.githubusercontent.com/12802056/28549315-2da64b1c-70a7-11e7-88b2-ba1f3875fdf3.png)

**Comment by okiehsch** [comment]
I can't reproduce, adding `123movies.net##script:inject(nowebrtc.js)` fixes the popups from
`35.184.169.188`.
Open your console and look for this entry
![webr](https://user-images.githubusercontent.com/16838044/28549493-b003b508-70da-11e7-8545-a54c1ec658da.PNG)
if it is there no popup should occur.

**Comment by terrorist96** [comment]
Yeah, that entry in the console is there. But still get the popup. However, the popup is blocked when trying on a test profile with only uBO. Hmm..

The problem was blocking referrers for the site. If I allow referrers for that site, the popup doesn't happen. Weird.

**Comment by lain566** [comment]
There are fake buttons

`https://www1.123movies.la/movie/the-kid-who-would-be-king-zelo7ey/watching.html`

**Comment by lain566** [comment]
@okiehsch  There's a popup 

`https://xstreamcdn.com/v/yxv376egqol`

**Comment by okiehsch** [comment]
Have you updated your filter list?

**Comment by lain566** [comment]
My bad, sorry

**Comment by ghajini** [comment]
`123movies.net`
Propeller ads crap
