### ISSUE TITLE
penpaland.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#5802]
### URL(s) where the issue occurs

`https://www.penpaland.com/`

### Describe the issue

Anti-adblock JS warning.

### Versions

- Browser/version: Firefox 67
- uBlock Origin version: 1.19.6

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin lists

**Comment by bogachenko** [comment]
`penpaland.com##+js(setTimeout-defuser.js, afs_ads, 2000)`
