### ISSUE TITLE
comingsoon.net

### ISSUE THREAD

**Issue by lassekongo83** [uBlockOrigin/uAssets#5806]
### URL(s) where the issue occurs

`https://www.comingsoon.net`

### Describe the issue

Admiral anti-adblock popup after a sec or two.

### Screenshot(s)

Not needed, as the problem is obvious.

### Versions

- Browser/version: Firefox 67.0.1
- uBlock Origin version: 1.19.6

### Settings

- Default settings.
- SWE and NOR regional filters.

### Notes

Current admiral fix seems to work: `comingsoon.net##+js(abort-on-property-read.js, googletag)`

**Comment by mapx-** [comment]
as annoyance
