### ISSUE TITLE
[Question] regarding a commit in #5644

### ISSUE THREAD

**Issue by LeuX** [uBlockOrigin/uAssets#5807]
### URL(s) where the issue occurs

I'm writing on behalf of the team behind `mentor.duden.de`; The site is currently broken with uBlock - however: we are trying to work around the issue

### Describe the issue

Our team discovered that the Duden Mentor has issues with uBlock - and we could identify the line ``duden.de##+js(abort-on-property-read.js, document.cookie)`` to be the culprit. 
Please note, that even though we share the same subdomain, both sites are technically quite different. 
We also found issue #5453 - for which which the lines *below* were added. 
The filter rule that caused issues on our end is in https://github.com/uBlockOrigin/uAssets/commit/3fce55bbf#diff-728d382ab45d1e85df51bb432db0ce90R19639 - for which the commit is referencing an unrelated issue, #5644 . 
What we'd like to know now is why this rule was added - since that rule might be likely to cause us issues in the future (I'm talking features, not ads here :) )

### Screenshot(s)

Not applicable

### Versions

Not applicable

### Settings

Not applicable

### Notes

We will roll out a workaround for the Issue to the site soon. However - we'd like to learn more about what the rule exactly adresses, which is why we'd like to find the actual issue that the commit from above fixes. 

Thank you for your help!

**Comment by mapx-** [comment]
What is broken ? steps to reproduce the issue ?
Are you using the same tisoomi ads ?

**Comment by PatrickBauer** [comment]
@mapx- Our whole react app isn't loading properly on https://mentor.duden.de/. 
There is an endless `Ladevorgang ...` message which is German for "Loading...".

**Comment by mapx-** [comment]
> Are you using the same tisoomi ads ?

**Comment by PatrickBauer** [comment]
I'm not sure about tisoomi ads. Our ad provider is https://www.yieldlove.com/. 
But our react app is completely independent of all ads.

**Comment by mapx-** [comment]
In few hours I'll be able to test the site and inhibit the rule if no tisoomi ads are enabled
an exception like this 1 should fix your issue
`mentor.duden.de#@#+js(abort-on-property-read.js, document.cookie)`

**Comment by LeuX** [comment]
Thanks! 
However as iI said above, we will likely have deployed a workaround later - so you might not be able to reproduce it.
This is what it currently looks like: [https://imgur.com/a/6huSc2F](https://imgur.com/a/6huSc2F)
So - do I understand you correctly: you use the ``abort-on-property-read.js, document.cookie``
on sites that use tisoomi?

**Comment by mapx-** [comment]
I can already reproduce the issue, but I need a german ip to completely review the page.
Yes, that filter is anti tisoomi for now.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/8d34367dfcbef92839cb101c89533916798dc18c
I removed the script injection for your subdomain. I can't see any ad-reinsertion.

**Comment by okiehsch** [comment]
>  for which the commit is referencing an unrelated issue

That issue is about the same ad-reinsertion script, there are dozens of sites using it, so I just referenced one issue and fixed all sites.

**Comment by LeuX** [comment]
Okay - thanks for your help!
I did not expecxt such a fast solution and answer; You people are awesome!
