### ISSUE TITLE
palemoon.org

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#581]
palemoon.org

When you go to palemoon.org it says, "We love ad blockers as much as you, but we depend on ad revenue to fund various sites and services. We use responsible ad services to keep your visit to our websites a safe and uninterrupted one. To ensure our continued operation, please disable your ad blocker for this site or support us another way.". Is there a filter to use for that website? Also, it seems lately that a lot of websites are detecting the adblocker, is there a way to make an adblocker that websites don't detect, so that you don't have to create a custom filter each time a website detects the adblocker? Is there any filter that will work to get rid of adblocker detected warning messages on all or most websites? Thanks.

![palemoon org](https://user-images.githubusercontent.com/26278182/28583880-c0061c30-7138-11e7-909e-3f6588d5b3d0.jpg)

Firefox Developer Edition 55.0b11 (32-bit)
uBlock Origin 1.13.8

**Comment by okiehsch** [comment]
1. `@@||palemoon.org/ads.js$script,first-party` fixes your issue but will not be added to uBO-filters
list as I would classify this as an annoyance, the message does not block any actual content.

2.  > is there a way to make an adblocker that websites don't detect, so that you don't have to create a custom filter each time a website detects the adblocker?

     No, take this issue as an example palemoon deliberately named a small javascript file `ads.js`
     and used it as "bait". If the website detects that it was blocked it displays the message you see.
     If it loads, no message. They can rename that script to whatever they want to trigger a hit by Easylist.

**Comment by js017** [comment]
Well that's interesting, it seems that a lot of those people try to detect adblockers in a way that tries to fool the adblockers. It's really good though that there's people like you that try and make good adblockers so that people can browse the internet without as many annoying ads. Keep up the good work. Thanks.
