### ISSUE TITLE
bs.to fighting back with ads

### ISSUE THREAD

**Issue by xmaestro21** [uBlockOrigin/uAssets#5811]
### URL(s) where the issue occurs

bs.to
burningseries.co

### Describe the issue

Can't access Site with uBlock Origin enabled

### Versions

- Browser/version: Firefox 67.0.2
- uBlock Origin version: 1.19.6

### Settings

- Advanced User, some additional Filterlists

### Notes

So recently i reported the Site for their Ads, and you solved it:
https://github.com/uBlockOrigin/uAssets/issues/5790

But it seems like they are fighting back. Now i can't access the site with uBlock Origin enabled. I have to disable it first.

I hope it's ok to keep reporting it here

**Comment by mapx-** [comment]
see if works for you

```
bs.to,burningseries.co#@#[onclick]
bs.to,burningseries.co##+js(remove-attr.js, onclick)
```

**Comment by xmaestro21** [comment]
Yes thank you now it's working again!
