### ISSUE TITLE
blick.ch

### ISSUE THREAD

**Issue by tnr20** [uBlockOrigin/uAssets#5812]
### Describe the issue

Problems with this domain blick.ch. if i click a new site (blick.ch/new-url.html) it did not open.

### Screenshots
![t](https://user-images.githubusercontent.com/49328456/59353471-5622be00-8d23-11e9-842a-9a2f142b2550.png)

### Versions

- Browser/version: FireFox 67.02 (64Bit)
- uBlock Origin version: 1.19.6

### Notes

If i deactivate uBlockOrigin all works fine, but if activate again the problem is the same and i cant open any site on this domain blick.ch

Can you please help?
thanks

**Comment by mapx-** [comment]
> if i click a new site (blick.ch/new-url.html) it did not open

I don't understand what's your issue. I can navigate the site, click on various articles.

**Comment by krystian3w** [comment]
Try export your uBo settings and upload into this issue?
