### ISSUE TITLE
filld.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#5815]
### URL(s) where the issue occurs

`https://filld.com/gasdelivered/`

### Describe the issue

Prices don't load

### Notes

`@@||geoip-js.maxmind.com^$xmlhttprequest,domain=filld.com`
`@@||js.maxmind.com/js/apis/geoip2/v2.1/geoip2.js$script,domain=filld.com`

**Comment by mapx-** [comment]
@ryanbr
