### ISSUE TITLE
www.semprot.com & 46.166.167.16 [alternative IP for www.semprot.com] [NSFW]

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#5818]
### URL(s) where the issue occurs

`[http://46.166.167.16/threads/my-perfect-gf-updated.1319652/]`
`[http://www.semprot.com/threads/my-perfect-gf-updated.1319652/]`

### Describe the issue

[Can't see image when activate adblocker addons]

### Screenshot(s)

[**https://imgur.com/6PHhQho**]

### Versions

- Browser/version: [Firefox Quantum 67.0.2 x86]
- uBlock Origin version: [1.19.6]

### Settings

- [https://pastebin.com/gemPfNhL]

### Notes

[Turned off uBO, then i can see the image]

**Comment by What-Zit-Tooya** [comment]
@okiehsch 
new IP address changed to `93.115.24.210`
also it full of img ads

seems it fix image ads?
||gambar123.com^$image,domain=semprot.com|93.115.24.210

**Comment by okiehsch** [comment]
> Can't see image when activate adblocker addons

I don't see any breakage.
The only issue are the ads?

**Comment by What-Zit-Tooya** [comment]
> 
> 
> > Can't see image when activate adblocker addons
> 
> I don't see any breakage.
> The only issue are the ads?

Try this link `https://www.semprot.com/threads/toket-temen.1397891/` [need account]
Seems anti-adb triggered.
and also yes ads image
![1](https://user-images.githubusercontent.com/9832875/131249114-72475ca2-8f67-4e05-b735-6c0f6495acb4.png)

**Comment by okiehsch** [comment]
Well, I don't have an account and I don't speak indonesian.
Do you have a working fix for the site?

The ads on sites that don't need an account can be removed with 
````
||gambar123.com^$script,image,domain=93.115.24.210
93.115.24.210##.semprotnenenmontok_adalah_pujaan_hatiku
93.115.24.210##a[href^="/yum.php"]
````

**Comment by What-Zit-Tooya** [comment]
> 
> 
> Well, I don't have an account and I don't speak indonesian.
> Do you have a working fix for the site?
> 
> The ads on sites that don't need an account can be removed with
> 
> ```
> ||gambar123.com^$script,image,domain=semprot.com|93.115.24.210
> semprot.com,93.115.24.210##.semprotnenenmontok_adalah_pujaan_hatiku
> semprot.com,93.115.24.210##a[href^="/yum.php"]
> ```

It works. :)
To test througly, i can give you username & pw here: `https://snippet.host/nwxh`

**Comment by uBlock-user** [comment]
Should be reported to https://github.com/ABPindo/indonesianadblockrules/issues, as this doesn't require uBO's extended syntax.

**Comment by What-Zit-Tooya** [comment]
> 
> 
> Should be reported to https://github.com/ABPindo/indonesianadblockrules/issues, as this doesn't require uBO's extended syntax.

I saw same issue on it , created since March, but not fixed till now, probably abandoned?

**Comment by uBlock-user** [comment]
> I saw same issue on it

link ?

**Comment by okiehsch** [comment]
@uBlock-user 
https://github.com/ABPindo/indonesianadblockrules/issues/181

**Comment by uBlock-user** [comment]
Yeah I found out, hence deleted the comment, he hasnt been active in weeks, should we wait ?

**Comment by okiehsch** [comment]
Let's add the filters for now and ping the maintainer.

@gmarcher

**Comment by What-Zit-Tooya** [comment]
@okiehsch seems botton ads placeholder still exist
![1](https://user-images.githubusercontent.com/9832875/131251791-df89a70b-be00-4b70-9f98-488d47d2c48d.png)

**Comment by caripurel2024** [comment]
video klip

www,nobokep,my,id

**Comment by dirgahayutni2024** [comment]
kekuatankita persatuankita

www,flavaofc,com

**Comment by overthemoonnew** [comment]
mampus rox

www,kontenterabox,com

**Comment by benedictagisha2025** [comment]
parahhh macett

www,3gpterbaru,com
