### ISSUE TITLE
Inoreader.com

### ISSUE THREAD

**Issue by SergeGardien** [uBlockOrigin/uAssets#582]
### URL(s) where the issue occurs

`[http://www.inoreader.com/]`
Requires a free subscription (login with Google account is fine too).

### Describe the issue

I'm trying to eliminate the right ads bar on inoreader.com.
By using the following uBlock handmade filter I've been able to remove a layer but I still have an empty bar on the right:
```
! 7/24/2017, 10:14:54 PM https://www.inoreader.com/feed/*
www.inoreader.com###sinner_container
```
Any idea how I can remove such bar and expand the text of the articles?

### Screenshot(s)

Without the filter: [https://anonimag.es/i/5357c3e44c6282cab67ad259cb5bff7e.png](https://anonimag.es/i/5357c3e44c6282cab67ad259cb5bff7e.png)
With the filter: [https://anonimag.es/i/fb53724ba89612d1f84c752e8ea9862b.png](https://anonimag.es/i/fb53724ba89612d1f84c752e8ea9862b.png)

### Versions

- Browser/version: Firefox 54.0.1 and Google Chrome 60.0.3112.78 (Official Build) (64-bit)
- uBlock Origin version: 1.13.8

### Settings

- Not many changes on settings apart from 2 personal filters (unrelated to inoreader.com) and whitelist

### Notes

- I've already opened 2 threads, one on EasyList forum [https://forums.lanik.us/viewtopic.php?f=62&t=37631](https://forums.lanik.us/viewtopic.php?f=62&t=37631) and another on reddit/uBlockOrigin [https://www.reddit.com/r/uBlockOrigin/comments/6pb8ie/inoreadercom_feed_reader_removing_right_bar_ads/](https://www.reddit.com/r/uBlockOrigin/comments/6pb8ie/inoreadercom_feed_reader_removing_right_bar_ads/) without a solution yet.
- I've noticed that the ads bar disappears if I open my bookmarks sidebar in Firefox and I refresh the page (e.g., by moving to another feed). Probably Inoreader recognize that the screen is squeezed from the left and removes the ads bar. Still, it comes back soon as I close the bookmarks sidebar and I refresh the page.
  - Here are 2 screenshots:
    - With bookmarks sidebar open: [https://anonimag.es/i/87340df98840b2177971cc7de0534e79.png](https://anonimag.es/i/87340df98840b2177971cc7de0534e79.png)
    - With bookmarks sidebar closed: [https://anonimag.es/i/f2fac182c016b50f3c0c66b71ad4fb38.png](https://anonimag.es/i/f2fac182c016b50f3c0c66b71ad4fb38.png)
  - The main difference is that in the list of cosmetic filters I see:
    - With bookmarks sidebar open: ###reader_pane.reader_pane_view_style_0
    - With bookmarks sidebar closed: ###reader_pane.reader_pane_view_style_0.reader_pane_sinner
  - Can I use this information somehow? E.g., by forcing the use of [###reader_pane.reader_pane_view_style_0]

**Comment by SMed79** [comment]
```
inoreader.com###reader_pane:style(padding-right: 0px !important;)
inoreader.com###sinner_container
```
see https://forums.lanik.us/viewtopic.php?p=121822#p121822

**Comment by adranger** [comment]
@okiehsch  @mapx- Inoreader is showing an anti-adblock message to logged-in users (you can log in with a Google account).

**Comment by mapx-** [comment]
As you can see I added a commit 3 hours ago, just update your lists.

**Comment by rpodric** [comment]
Thanks, but that commit, while hiding the warning, doesn't actually allow you to use the keyboard afterwards since the dialog is really still there (just hidden).

I think it'll take preventing the dialog from coming up in the first place.

**Comment by mapx-** [comment]
Test this filter, see if works
`||inoreader.com/adv/$script,redirect=noopjs,first-party`

**Comment by rpodric** [comment]
That restored kb use in Chrome, but didn't in my main browser (based on Chromium). I eventually figured out that was because in that browser I'm running a userscript for the site, and that userscript must counteract your line. Unclear if it's possible to use them together.

**Comment by rpodric** [comment]
OK, so you reverted the previous change and went with that line, which works (the issue I mentioned aside), but with this line in EasyList, why did it turn out to be needed?  It seems like they should both effectively do the same thing, but clearly not.
```
.com/adv/
```

**Comment by mapx-** [comment]
read about redirecting
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect

**Comment by rpodric** [comment]
Yes, I had read that. So, in one case, it's redirected to a dummy resource. And in the other case, it's blocked. Two different ways, seemingly, of accomplishing the same thing.

**Comment by mapx-** [comment]
In this case the site is testing if  `https://www.inoreader.com/adv/www/delivery/ajs.php` still exists, if not => the anti adb overlay is enabled

`$v.html().indexOf('/adv/www/delivery/ajs.php')===-1`

**Comment by rpodric** [comment]
I see that you further refined it. Still works great, but I'm wondering if this is the best place to bring up an issue also beyond me that predates the most recent one: the "scroll tracking" feature (Mark items as read when you scroll past them) doesn't work in some circumstances. It's mainly noticeable in list view, where you'll see that scrolling only goes so far, if it goes at all, breaking the feature. It happens in some other views too, depending on the number/size of the articles.

I think it's something to do with the way that ads, or maybe the spacing, above and below the content are being handled . This can be seen by disabling EasyList, which reveals large gaps above and below the content, with "Remove ads" links nearby. Scroll tracking works when it's in that state, but of course that's not a great state. I have a feeling that a tweak to the filter that handles these ads/spacing would fix it.

**Comment by rpodric** [comment]
@mapx - Looks like the problem is back today.

**Comment by mapx-** [comment]
I get it randomly, test this filter:
`@@||inoreader.com/adv/$first-party,script,image`

**Comment by rpodric** [comment]
Yes, it was random, but those changes seem to have fixed it. They do leave a gap above the articles, but coincidentally that solves the scrolling issue I mentioned yesterday.

**Comment by okiehsch** [comment]
The filters for this site have now disable the sign in functionality....

**Comment by okiehsch** [comment]
There are some other entries that are not needed as far as I can see, for example the exception filters, but the site will no doubt change up in a matter of hours/days anyway.

**Comment by Smultie** [comment]
I'm getting adblock detected screens again!

**Comment by mapx-** [comment]
Did you force an update right now ?

**Comment by Smultie** [comment]
Yessir!

**Comment by mapx-** [comment]
If you still see a setTimeout filter in your logger => the update failed => purge & update your lists

**Comment by Smultie** [comment]
Yes of course

**Comment by Smultie** [comment]
Just had one again. Fully updated

**Comment by mapx-** [comment]
add
```
inoreader.com##[id*="modal_overlay"]
inoreader.com##.adb_left:xpath(../..)
```

**Comment by mapx-** [comment]
or ... being an annoyance you could simply click "not for this session" button (or something like that)

**Comment by mikhaelkh** [comment]
Getting adblock detected. (Adguard Base Filters enabled)
`@@||inoreader.com/adv/$first-party,script,badfilter` or `||inoreader.com/adv/$first-party,important` - no detect.

**Comment by mikhaelkh** [comment]
They're setting `aguineapigtrickedme` cookie for 1 day which hides the dialog.

**Comment by mikhaelkh** [comment]
They're setting `aguineapigtrickedme` cookie for 1 day which hides the "adblock detecteed" dialog.

**Comment by rpodric** [comment]
Don't use those lines.

**Comment by cannafu** [comment]
> Don't use those lines.
Then a popup appears

**Comment by rpodric** [comment]
Once a day, which is better than no hotkeys.

**Comment by maboloshi** [comment]
I have hidden the "adblock detecteed" dialog. However, I hope that inoreader has enough funds to support free users. I don't provide the code directly here. Actually the complete code is in my gist.
Tip Use [:not](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectnotarg)

**Comment by mikhaelkh** [comment]
@maboloshi, hotkeys with your rules doesn't work too.

**Comment by cannafu** [comment]
> @maboloshi, hotkeys with your rules doesn't work too.
> Better solution is click `not now` and protect the cookie `aguineapigtrickedme`.

Thanks. Is it possible to extend the validity period or only one day?
[url=https://s8.hostingkartinok.com/uploads/images/2018/12/28a3c66309b096e2dbc0eb5ef52fbe64.jpg][img]https://s8.hostingkartinok.com/uploads/thumbs/2018/12/28a3c66309b096e2dbc0eb5ef52fbe64.png[/img][/url]

**Comment by maboloshi** [comment]
@mikhaelkh According to your idea, you can solve it with a simple userjavascript file.
```
// ==UserScript==
// @name Hide Inoreader Ad
// @include http://www.inoreader.com/*
// @include https://www.inoreader.com/*
// @icon http://www.inoreader.com/favicon.ico
// @grant none
// ==/UserScript==
document.cookie = "aguineapigtrickedme=1; path=/; secure=false";
```

**Comment by mikhaelkh** [comment]
@maboloshi I manually increased duretion of the cookie to 1 year, works so far

**Comment by maboloshi** [comment]
@mikhaelkh, I forgot to click ‘not now‘ before I tried the userjavascript. Now, the hotkeys work properly.  Thank you ideas.

**Comment by Smultie** [comment]
Any way to do this with uBlock?

**Comment by cannafu** [comment]
> @maboloshi, hotkeys with your rules doesn't work too.
> Better solution is click `not now` and protect the cookie `aguineapigtrickedme`.

Thanks

**Comment by mzso** [comment]
[**@maboloshi**](https://github.com/maboloshi) commented on [2018. dec. 19. 16:50 CET](https://github.com/uBlockOrigin/uAssets/issues/582#issuecomment-448643240 "2018-12-19T15:50:00Z - Replied by Github Reply Comments"):
> [@mikhaelkh](https://github.com/mikhaelkh) According to your idea, you can solve it with a simple userjavascript file.
> 
>     // ==UserScript==
>     // @name Hide Inoreader Ad
>     // @include http://www.inoreader.com/*
>     // @include https://www.inoreader.com/*
>     // @icon http://www.inoreader.com/favicon.ico
>     // @grant none
>     // ==/UserScript==
>     document.cookie = "aguineapigtrickedme=1; path=/; ";
> 
> Before trying userjavascript, you need to click "not now". Now, the hotkeys work properly.

What is this supposed to do? I still get the adblock detected warning.

**Comment by rpodric** [comment]
That's because the site no longer uses a cookie for that (I expect that they're subscribed to this thread).

**Comment by mzso** [comment]
[**@rpodric**](https://github.com/rpodric) commented on [2019. jan. 7. 18:10 CET](https://github.com/uBlockOrigin/uAssets/issues/582#issuecomment-452007796 "2019-01-07T17:10:14Z - Replied by Github Reply Comments"):
> That's because the site no longer uses a cookie for that (I expect that they're subscribed to this thread).

Oh, well... That didn't last long.

**Comment by mikhaelkh** [comment]
What's the point in exception filters if they don't prevent anti-adblock popup?

**Comment by maboloshi** [comment]
Use userjavascript shielding function `adb_detected`.

**Comment by mapx-** [comment]
Did you test the site ? is working for now
