### ISSUE TITLE
Quoka.de upload pictures

### ISSUE THREAD

**Issue by MinIsMin** [uBlockOrigin/uAssets#5821]
### URL where the issue occurs

`https://www.quoka.de/inserieren/anzeige-aufgeben.html` (requires login)

### Describe the issue

When using UBlock filters I am unable to upload pictures on that website.
This error doesn't occur without UBlock filters (see Notes below) and the upload works fine.

### Console output

![console error](https://user-images.githubusercontent.com/18466226/59430835-cc322e00-8dd2-11e9-9e89-e46a8e3c3fc4.png)

### Versions

- Browser/version: Firefox 67.0
- uBlock Origin version: v1.19.6

### Settings

Default settings, disabled all filterlists except uBlock filters

### Notes

Seems to happen because of these js inserts
```
##+js(setTimeout-defuser.js, 0&&)
​##+js(setTimeout-defuser.js, )&&)
##+js(addEventListener-defuser.js, /^(?:DOMContentLoaded|load)$/, ||()​​
​##+js(set-constant.js, atob, trueFunc)
```

**Comment by krystian3w** [comment]
I cannot reproduce on Firefox 67.0.2...

![obraz](https://user-images.githubusercontent.com/35370833/59453254-ce66ad80-8e0f-11e9-8ffd-1dca58215b92.png)

**Comment by MinIsMin** [comment]
Strange, here's a video: https://streamable.com/ldfje

**Comment by krystian3w** [comment]
Website detect GNU/Linux?

**Comment by MinIsMin** [comment]
It shouldn't, my UA string is
`Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0`

I'll test with Windows now.

**Comment by okiehsch** [comment]
It also works fine on my end using Chromium/Chrome with Linux or Windows.
I will remove the ​`##+js(set-constant.js, atob, trueFunc)` filter because it is obsolete anyway.
Maybe that will fix your problem.
Try adding
`quoka.de​#@#+js(set-constant.js, atob, trueFunc)`
to our filter list.

**Comment by MinIsMin** [comment]
@okiehsch 
Adding that line works!

**Comment by okiehsch** [comment]
Ok, the filter has been removed by me https://github.com/uBlockOrigin/uAssets/commit/31c65f896a40a4a69ddfe98d72e64eb7d08bee37, so if you update your `uBO-filters` list you can remove that line from your list.
