### ISSUE TITLE
yandex.ru/chat

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#5823]
### URL(s) where the issue occurs
```
https://yandex.ru/chat
```
### Describe the issue
The use of the scriptlet `yandex.ru##+js(set-constant.js, Math.random, trueFunc)` leads to the blocking of websockets `wss://uniproxy.messenger.yandex.ru/uni.ws`, however, without it, advertising on the rest of the domain will not be blocked, for example, here: https://yandex.ru/images/search?text=папортник
### Versions
- Browser/version: Google Chrome 75.0.3770.90
- uBlock Origin version: 1.19.6
### Settings
uBlock filters
Adblock Warning Removal List
EasyList
RUS: RU AdList

**Comment by mapx-** [comment]
Where are the ads using the search page you posted above ? (I disabled the `Math.random` filter in my test)

I get

![image](https://user-images.githubusercontent.com/10303732/59508998-150be480-8eb0-11e9-8f2c-2479f2c454d8.png)

**Comment by mapx-** [comment]
hmm, maybe are hidden by adguard filters

**Comment by mapx-** [comment]
even reenabling `math.random` filter (and disabling adguard list) I get the same ads ?!

**Comment by dimisa-RUAdList** [comment]
Most likely, the presence of advertising depends on geolocation and accumulated cookies. I deleted the scriptlet due to the problems it creates. I will look for ways to use other rules, including hiding.

**Comment by mapx-** [comment]
Could you upload a screenshot with the page with ads ?

**Comment by dimisa-RUAdList** [comment]
https://i.imgur.com/FMTwgpx.jpg
I did wrong by specifying a direct link. In order to have an advertisement, you need to perform a search query on the main page `https://yandex.ru/`, and then select the pictures in the search results. At the moment, advertising is not blocked, but is hidden by the rule `yandex.ru##div[aria-label="Реклама"]`. Previously deleted scriptlet blocked this ad. But apparently, he just lost relevance.
