### ISSUE TITLE
new brainly ad issue

### ISSUE THREAD

**Issue by TristramGreenman** [uBlockOrigin/uAssets#5824]
### URL(s) where the issue occurs

 `https://brainly.com/`

### Describe the issue

Basically after looking at a few different questions you will get an ad that will cover the answer asking you to watch an ad. I made a post previously on this situation and i got a custom filter that fixed it but the issue has returned.
https://github.com/uBlockOrigin/uAssets/issues/4645

### Screenshot(s)

 https://gyazo.com/27a82e5311b9a1d636e4532bfdb5bc0c

As you can see in the screenshot below the question they make me watch an ad before viewing the answer.

### Versions

- Browser/version: chrome/newest
- uBlock Origin version: 1.19.6

### Settings

- I have ublock annoyance filter on and this custom filter active, brainly.com##+js(setTimeout-defuser.js, trigger, 0) .

**Comment by mapx-** [comment]
test & see if breaks the site / functionality
`brainly.com##+js(abort-on-property-read.js, jsData)`

**Comment by TristramGreenman** [comment]
Before : https://gyazo.com/64dfd13634d3c7fe58c8620df13cc89a
After : https://gyazo.com/9e1e7738a89accd280fe6e9067f24aca
Yeah it does.

**Comment by mapx-** [comment]
> Yeah it does

What is broken ? more details ?

**Comment by llacb47** [comment]
I think @tristramgreenman means that the filter works?

**Comment by TristramGreenman** [comment]
For example when you type in a question in the search bar none of the questions load, and the filter turns off the ads if but you have to click on the question first then enable the adblock and refresh the page for the ads to dissapear.

**Comment by okiehsch** [comment]
Try
`brainly.com##+js(abort-on-property-write.js, jsData)`
works for me and the questions still load on my end.

**Comment by TristramGreenman** [comment]
Yeah that works fine for me, thanks a lot man :)
