### ISSUE TITLE
torlock.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#583]
### URL(s) where the issue occurs

`https://www.torlock.com/torrent/6295565/king-arthur-legend-of-the-sword-1080p-truehd-7-1-atmos-fgt.html`

### Describe the issue

Fake `Fast Download` and `Safe Download` buttons, plus popup if you click around.

`||l.xxcdn.pw/dlbutton38342842.png$image`
`||l.xxcdn.pw/dlbutton16883420.png$image`

**Comment by SMed79** [comment]
`##a[href*=".europeantorrents.download/"]`

**Comment by ghajini** [comment]
`www.torlock.icu`
Popup ads

Responsible on many torrent domains 

`||35.232.188.118^`

**Comment by ghajini** [comment]
Still popups
`torlock.icu`
