### ISSUE TITLE
google.com [mobile only]

### ISSUE THREAD

**Issue by dooglius** [uBlockOrigin/uAssets#5830]
### URL(s) where the issue occurs

`https://www.google.com/search?q=car+insurance`

### Describe the issue

Ads appear above search results, clearly marked with "Ad" in a green box. Only began seeing this today.

### Versions

- Browser/version: Firefox 67.0.2 for Android
- uBlock Origin version: 1.20.0

### Settings

- Default settings, happens on fresh reinstall of add-on and reset to factory settings

### Notes

- ONLY happens on mobile; enabling "Request desktop site" gives ad-free pages
- I do get "2 or 66%" requests blocked on the page
- Happens regardless of whether I'm using a normal or a private tab

**Comment by krystian3w** [comment]
Maybe bug with nested if?

https://github.com/uBlockOrigin/uAssets/blob/160405c0720b20c83cc98dc9b033cf941d10b53e/filters/filters.txt#L84-L89
