### ISSUE TITLE
wikitrik.com

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#5835]
### URL(s) where the issue occurs

`[https://wikitrik.com/jCgXS]`

### Screenshot(s)

[
![2019-06-17_182701](https://user-images.githubusercontent.com/9832875/59601693-054e0380-912f-11e9-8df6-16e1c5908873.png)
]

Rest same like this: https://github.com/uBlockOrigin/uAssets/issues/5829

**Comment by IThinkIAmCool** [comment]
ad placeholders on `https://wikitrik.com`

**Comment by garry-ut99** [comment]
> ad placeholders on https://wikitrik.com/

Yes, ad placeholders all over the site, caused by `ghide` from "uBlock Filters", 
on both main page and subpages: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/219793116-fb1af153-f4ac-461b-80b1-bc1976149515.png), I get no AA with `ghide` off.

**Comment by mapx-** [comment]
we need a real link (shortener) to test

**Comment by garry-ut99** [comment]
No other links, just a main page, just like here: https://github.com/uBlockOrigin/uAssets/issues/5835#issuecomment-875375389
And just like there: https://github.com/uBlockOrigin/uAssets/issues/8745#issuecomment-1429958283 + https://github.com/uBlockOrigin/uAssets/issues/8745#issuecomment-1429977092
