### ISSUE TITLE
cepmuzikindir.me

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#5836]
### URL(s) where the issue occurs

`[https://cepmuzikindir.me/links/post/17-25-unique-places-in-the-real-world-it-s-coming-from-a-fantasy-movie?a=xFXBgaFAm9G]`

### Screenshot(s)

[
![2019-06-17_182701](https://user-images.githubusercontent.com/9832875/59601849-7beb0100-912f-11e9-8d23-ca3f46052f3a.png)
]

Rest same like this: https://github.com/uBlockOrigin/uAssets/issues/5829

**Comment by JobcenterTycoon** [comment]
`cepmuzikindir.me##+js(addEventListener-defuser.js, load, onload)` works for me
