### ISSUE TITLE
docs.google.com

### ISSUE THREAD

**Issue by kalakuru** [uBlockOrigin/uAssets#5837]
### URL(s) where the issue occurs

https://docs.google.com/spreadsheets/u/0/

### Describe the issue

White screen while loading sheet.

### Screenshot(s)

No need screenshots at this point as it just white screen

### Versions

- Browser/version: 1.19.6
- uBlock Origin version: 74.0.3729.169

### Settings

- Disable Peter Lowe’s Ad and tracking server list which is known to break something

### Notes

To reproduce, open the url above and create new sheet or open any sheet you like

**Comment by exodius48** [comment]
I can open and create the spreadsheet. No issue on my side

![2019-06-17_191413](https://user-images.githubusercontent.com/9832875/59603690-4694e200-9134-11e9-96cf-8c67ce990464.png)

**Comment by mapx-** [comment]
- did you test using only default lists ? some other regional list ?
- open the logger, refresh the page, post here only the blocked requests

**Comment by mapx-** [comment]
no feedback => closing
