### ISSUE TITLE
nytimes.com [cookie bar]

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5839]
### URL(s) where the issue occurs

`https://www.nytimes.com/`

### Describe the issue

Cookie bar (annoyance)

### Versions

- Browser/version: Firefox 67.0.2
- uBlock Origin version: v1.20.0
### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3298510/Settings.txt)

### Notes

The cookie bar is not blockable by Fanboy’s Annoyance List

**Comment by mapx-** [comment]
Did you try ?
`nytimes.com##.gdpr`

**Comment by yourduskquibbles** [comment]
Your missing some description of issue info so only guessing you are on EU IP?

Does adding the following filter to 'My Filters' fix the issue for you?

`nytimes.com##.gdpr[data-testid="gdpr-dock"]`

**Comment by JobcenterTycoon** [comment]
> 
> 
> Your missing some description of issue info so only guessing you are on EU IP?
> 
> Does adding the following filter to 'My Filters' fix the issue for you?
> 
> `nytimes.com##.gdpr[data-testid="gdpr-dock"]`

it’s works thanks.
