### ISSUE TITLE
demonoid ads

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#584]
### URL(s) where the issue occurs

`https://www.demonoid.pw/files/details/3630906/`

### Describe the issue

VPN ad at top and bottom.
`demonoid.*###bbb`

Download anonymously link.
`demonoid.*##a[href="/tzr.php"]`

`https://www.demonoid.pw/files/`
Uncollapsed ad space on right
`demonoid.*###rbid`

They have multiple TLDs (e.g. `demonoid.click`), so using * is appropriate

**Comment by okiehsch** [comment]
Your suggested filters work and can be added to EasyList
fyi @ryanbr

**Comment by terrorist96** [comment]
I'm just really confused now. Similar reported ads would be added to ublock's filter list but now it's being deferred to EasyList (which won't add it anytime soon).

**Comment by okiehsch** [comment]
I told you already under which circumstances I add a filter https://github.com/uBlockOrigin/uAssets/issues/536#issuecomment-316147281.
I do not see how this issue falls under one of the mentioned categories.
