### ISSUE TITLE
uploadhaven.com timer boost - bug

### ISSUE THREAD

**Issue by uploadhaven** [uBlockOrigin/uAssets#5840]
`https://uploadhaven.com/download/d928edf2775edfeda6327752d99cdd31`

### Describe the issue

Timer boost is breaking the website, since the countdown is accelerated the user submits the form too early, resulting in an expired session.

### Notes

Original pull request: #5705 

More information: https://github.com/timmyrs/Universal-Bypass/issues/252

**Comment by ealgase** [comment]
Very rarely do we see a website operator here.

**Comment by marcussacana** [comment]
haha, and isn't fixed
