### ISSUE TITLE
imperfectproduce.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#5841]
### URL(s) where the issue occurs

`https://www.imperfectproduce.com/account/referrals`

### Describe the issue

Referral element doesn't load.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/59641608-3a0e8a80-9130-11e9-957f-e484047c57a9.png)

### Notes

```
@@||friendbuy.com^$domain=imperfectproduce.com
@@||djnf6e5yyirys.cloudfront.net/js/friendbuy.min.js$script,domain=imperfectproduce.com
```

**Comment by mapx-** [comment]
test account ? send me it at `axis.trivia@gmail.com` (and necessary steps to get the issue)

**Comment by mapx-** [comment]
Could you test
```
@@||djnf6e5yyirys.cloudfront.net/js/friendbuy.min.js$script,domain=imperfectproduce.com
@@||friendbuy.com^$xhr,frame,domain=imperfectproduce.com
```

**Comment by terrorist96** [comment]
That works.

**Comment by mapx-** [comment]
@ryanbr
