### ISSUE TITLE
animeyt2.tv

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#5843]
shit xhr

`animeyt2.tv/xvideo.js` or `animeyt2.tv##+js(abort-on-property-write.js, _0x7918)`

**Comment by okiehsch** [comment]
Does
`animeyt2.tv##+js(set-constant.js, String.prototype.charCodeAt, trueFunc)`
break anything?

**Comment by bogachenko** [comment]
y. I tried with him. like no

**Comment by bogachenko** [comment]
Will you add to yourself?

**Comment by okiehsch** [comment]
Of course.
