### ISSUE TITLE
documents on docs.google.com is just a blank page

### ISSUE THREAD

**Issue by romojt** [uBlockOrigin/uAssets#5846]
### URL(s) where the issue occurs

Create a document on https://docs.google.com

### Describe the issue

Google docs displays a blank page instead of the document, and starts working again when I disable uBlock Origin

The following message is printed to console:
 "Content Security Policy: The page's settings observed the loading of a resource at inline ("script-src"). A CSP report is being sent." See full message here: https://pastebin.com/6kHfQ23x

<details><summary>Blocked requests</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +23 | \|\|docs.google.com/*/logimpressions?$xmlhttprequest,domain=docs.google.com | -- | docs.google.com | 1 | xhr | `https://docs.google.com/spreadsheets/d/1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo/logImpressions?id=1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo&token=AC4w5ViO7vCbsxsCAagdsjw4ZlODpcdvSg%3A1560878591100&includes_info_params=true` |
| +20 | \|\|docs.google.com/*/logimpressions?$xmlhttprequest,domain=docs.google.com | -- | docs.google.com | 1 | xhr | `https://docs.google.com/spreadsheets/d/1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo/logImpressions?id=1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo&token=AC4w5ViO7vCbsxsCAagdsjw4ZlODpcdvSg%3A1560878591100&includes_info_params=true` |
| +19 | \|\|docs.google.com/*/logimpressions?$xmlhttprequest,domain=docs.google.com | -- | docs.google.com | 1 | xhr | `https://docs.google.com/spreadsheets/d/1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo/logImpressions?id=1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo&token=AC4w5ViO7vCbsxsCAagdsjw4ZlODpcdvSg%3A1560878591100&includes_info_params=true` |
| +16 | \|\|docs.google.com/*/logimpressions?$xmlhttprequest,domain=docs.google.com | -- | docs.google.com | 1 | xhr | `https://docs.google.com/spreadsheets/d/1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo/logImpressions?id=1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo&token=AC4w5ViO7vCbsxsCAagdsjw4ZlODpcdvSg%3A1560878591100&includes_info_params=true` |
| +14 | \|\|docs.google.com/*/logimpressions?$xmlhttprequest,domain=docs.google.com | -- | docs.google.com | 1 | xhr | `https://docs.google.com/spreadsheets/d/1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo/logImpressions?id=1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo&token=AC4w5ViO7vCbsxsCAagdsjw4ZlODpcdvSg%3A1560878591100&includes_info_params=true` |
| +11 | \|\|docs.google.com/*/logimpressions?$xmlhttprequest,domain=docs.google.com | -- | docs.google.com | 1 | xhr | `https://docs.google.com/spreadsheets/d/1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo/logImpressions?id=1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo&token=AC4w5ViO7vCbsxsCAagdsjw4ZlODpcdvSg%3A1560878591100&includes_info_params=true` |
| +10 | \|\|docs.google.com/*/logimpressions?$xmlhttprequest,domain=docs.google.com | -- | docs.google.com | 1 | xhr | `https://docs.google.com/spreadsheets/d/1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo/logImpressions?id=1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo&token=AC4w5ViO7vCbsxsCAagdsjw4ZlODpcdvSg%3A1560878591100&includes_info_params=true` |
| +7 | \|\|docs.google.com/*/logimpressions?$xmlhttprequest,domain=docs.google.com | -- | docs.google.com | 1 | xhr | `https://docs.google.com/spreadsheets/d/1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo/logImpressions?id=1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo&token=AC4w5ViO7vCbsxsCAagdsjw4ZlODpcdvSg%3A1560878591100&includes_info_params=true` |
| +3 | ##:xpath(//span[(text()='Ad')]/../../../..) |  | docs.google.com |  | dom | `https://docs.google.com/spreadsheets/d/1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo/edit#gid=786911136` |
| +0 | \|\|google.com/log?$other | -- | docs.google.com | 1 | beacon | `https://play.google.com/log?hasfast=true&auth=SAPISIDHASH%200a1e2a03402af1baa45abb38e0f61336ad63e474&authuser=0&format=json` |
| +0 | \|\|docs.google.com/*/logimpressions?$xmlhttprequest,domain=docs.google.com | -- | docs.google.com | 1 | xhr | `https://docs.google.com/spreadsheets/d/1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo/logImpressions?id=1ZubNOBx2sS5uetTOFjHE2Pds7ZSXE7QqmJeOh7uCcuo&token=AC4w5VhfacxVOGK8sT7BokYBXcSA_VPAcQ%3A1560878358349&includes_info_params=true` |
</details>

### Screenshot(s)
No screenshots as it is just a blank page

### Versions

- Browser/version: Firefox 67.0.2
- uBlock Origin version: 1.20.0

### Settings

- No changes to settings

### Notes

I have also observed this in Google Chrome, not sure which version it was

**Comment by mapx-** [comment]
update all your lists (`purge all caches` + `update now`) then test again

**Comment by ealgase** [comment]
No issues for me.

**Comment by romojt** [comment]
> 
> 
> update all your lists (`purge all caches` + `update now`) then test again

This fixed it. Thanks
