### ISSUE TITLE
https://carbuzz.com/

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#5849]
### URL(s) where the issue occurs

`https://carbuzz.com/news/will-the-new-nissan-gt-r-look-like-this`

### Describe the issue

The hyperlink `Vladimir Gololobov` is broken. Can only click it if you click towards the bottom half.

### Notes

```
#@#.ad-placement
#@#.ad-slot
```

**Comment by okiehsch** [comment]
The link is not broken as you mention it is still clickable and removing the cosmetic filters will result in whitespaces, so I will decline.

**Comment by terrorist96** [comment]
No solution to keep the whitespace hidden but fix the link?

**Comment by okiehsch** [comment]
If somebody comes up with such a filter I will reopen and apply the fix.

**Comment by yourduskquibbles** [comment]
Does 

`carbuzz.com##.cb-post-block-images-swiper .cb-post-block__comments:style(top: -100px !important;)`

work?

**Comment by terrorist96** [comment]
Yes, perfect! Thanks!

**Comment by yourduskquibbles** [comment]
Possible better fix for multiple screen resolutions @terrorist96 can you test?


`carbuzz.com##.cb-post-block-images-swiper .cb-post-block__comments:style(margin-bottom: 0 !important; top: -100px !important;)`

**Comment by terrorist96** [comment]
> `carbuzz.com##.cb-post-block-images-swiper .cb-post-block__comments:style(margin-bottom: 0 !important; top: -100px !important;)`

This exposes the whitespace. The first filter was better.

**Comment by yourduskquibbles** [comment]
> 
> 
> > `carbuzz.com##.cb-post-block-images-swiper .cb-post-block__comments:style(margin-bottom: 0 !important; top: -100px !important;)`
> 
> This exposes the whitespace. The first filter was better.

These two filters together better?

```
carbuzz.com##.cb-post-block-images-swiper .cb-post-block__comments:style(margin-bottom: 0 !important; top: -100px !important;)
carbuzz.com##.cb-post-block-images-swiper .cb-post-block__comments .collapseable-comments__collapse:style(margin-bottom: -40px !important;)
```

**Comment by terrorist96** [comment]
> These two filters together better?
> 
> ```
> carbuzz.com##.cb-post-block-images-swiper .cb-post-block__comments:style(margin-bottom: 0 !important; top: -100px !important;)
> carbuzz.com##.cb-post-block-images-swiper .cb-post-block__comments .collapseable-comments__collapse:style(margin-bottom: -40px !important;)
> ```

Looks good.

**Comment by okiehsch** [comment]
@yourduskquibbles you can add it to `uBO-unbreak`.

**Comment by yourduskquibbles** [comment]
I will when I find a better fix, I'm still testing and with just those 2 filters, makes it impossible to login on the comment login option when expanded.

**Comment by terrorist96** [comment]
I don't even see a comment section on a test profile.

**Comment by yourduskquibbles** [comment]
> 
> 
> I don't even see a comment section on a test profile.

Click the number 6 icon floating on the car pic and comments get expanded. Can't login with filters above.

Kind of a lot of filters for such a small fix but seems like these work for me. Can someone else test?

```
carbuzz.com##.cb-comments__create-form:style(margin-top: 30px !important;)
carbuzz.com##.cb-post-block-images-swiper .cb-post-block__comments .collapseable-comments__collapse:style(margin-bottom: 0px !important;)
carbuzz.com##.cb-post-block-images-swiper .cb-post-block__comments:style(margin-bottom: 0 !important; top: -97px !important;)
carbuzz.com##.cb-post-block-images-swiper .collapseable-comments__collapseable:style(margin-bottom: -80px !important;)
carbuzz.com##.cb-post-block__comments:style(padding-bottom: 0 !important;)
```

**Comment by terrorist96** [comment]
Looks good to me. The whitespace is just _slightly_ larger than without the filters, but it's not a big deal at all.

**Comment by yourduskquibbles** [comment]
> 
> 
> Looks good to me. The whitespace is just _slightly_ larger than without the filters, but it's not a big deal at all.

That extra white space is what allows that link to be clickable now 😉
