### ISSUE TITLE
idope.se

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#585]
### URL(s) where the issue occurs

`https://idope.se/torrent-list/tv/`
`https://idope.se/torrent/tv/4cf050bc9c81cb3ffd34ff8960b307a0941556a7/`

### Describe the issue

VPN ad.
This works for the results page:
`idope.se###categorydiv`
But I can't figure out how to block the ad on the torrent page.
Blocking `||idope.se/static/blog/pc/imgs/images/vpn1.png` doesn't work.

**Comment by okiehsch** [comment]
`idope.se###VPNAdvert` can be fixed in EasyList.
fyi @ryanbr
