### ISSUE TITLE
pornstarbyface.com [NSFW]

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#5852]
### URL(s) where the issue occurs

`pornstarbyface.com`

### Describe the issue

Upload a picture (any picture will do). Unblocked `Sponsored` stuff. Additionally, if you select the `WebCam Girls (beta)` tab, the results load overtop the `Porn Stars/WebCam Girls (beta)` category switcher and the top row doesn't load the pictures.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/59805692-f8ace500-92bf-11e9-9f83-04e3eb5a5628.png)

### Notes

`#@#a[href^="//awejmp.com/"]` for the second issue, but `awejmp.com` also is used for ads (you can see if you disable uBO and check the `WebCam Girls (beta)` tab).

**Comment by mapx-** [comment]
add
```
pornstarbyface.com##[id^="sponcored-content-"]
pornstarbyface.com#@#a[href^="//awejmp.com/"]
```

I get no `awejmp.com` ads 

@ryanbr
