### ISSUE TITLE
Is http://ublockerext.com a legitimate Ublock domain?

### ISSUE THREAD

**Issue by netsap** [uBlockOrigin/uAssets#5854]
I'm seeing connections on my firewall call out to this domain. Wondering whether it's malicious or not, can't find much information on it though.

**Comment by okiehsch** [comment]
> Is http://ublockerext.com a legitimate Ublock domain?

No.

**Comment by mapx-** [comment]
used to spread malware => badware

**Comment by gwarser** [comment]
Why `document` option?

OP said: "I'm seeing connections on my firewall call out to this domain."

These connections can be in background.

I see a lot of `document` in badware list, hmmm.

This may be problem:

![image](https://user-images.githubusercontent.com/886325/59844265-bedcec80-935a-11e9-836c-636afc2e5794.png)


Maybe `document` should also apply to iframes?

**Comment by okiehsch** [comment]
Yes, for a site that triggers background connections
`||example.com^`
is the proper fix.
Originaly the `badware` list was mainly for 
"..... The sites are documented to contain badware and other programs that have unwanted hidden functionality. Not all downloads on a site may be affected. The block page is there to remind users to be cautious, particularly non-technical users."
For those sites the `document` option makes sense. For "pure" malware sites `||example.com^` is better.

**Comment by krystian3w** [comment]
maybe `$all` for uBo 1.20+ - also block inline crap if anybody disable strict blocking?
