### ISSUE TITLE
dostfilms.*,intel.com,kimovil.*

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#5856]
Websites with blocked select text:

https://github.com/AdguardTeam/AdguardFilters/issues/30380

```css
dostfilms.*,intel.com,kimovil.*##*:style(-webkit-touch-callout: default !important; -webkit-user-drag: element !important; -webkit-user-select: text !important; -moz-user-select: text !important;  -ms-user-select: text !important; user-select: text !important;)
```

---

`https://downloadcenter.intel.com/en/product/80939` - blocked copy from table

`https://dostfilms.cc/publ/uzhasy/poka-nikto-ne-poranilsya-2018/5-1-0-6896` - on all site?

**Comment by okiehsch** [comment]
What specific domain is `kimovil.*`?
No need to inject styles in `kimovil.com`.

**Comment by krystian3w** [comment]
ru?

```
.noselect {
 -webkit-touch-callout:none;
 -webkit-user-select:none;
 -khtml-user-select:none;
 -moz-user-select:none;
 -ms-user-select:none;
 user-select:none
}
```

`https://www.kimovil.ru/build/fold-css.ccd99004.css`

**Comment by krystian3w** [comment]
Also removed prefix `-o` for Opera 12 and older, `-khtml` for Konqueror.

**Comment by XX-J** [comment]
> ru?

 Not only.

 On [https://www.kimovil.com/en/opinions/samsung-galaxy-s10-plus](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.kimovil.com/en/opinions/samsung-galaxy-s10-plus) any translated review is unselectable. Cause: [https://www.kimovil.com/build/app-css.fc48f658.css](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.kimovil.com/build/app-css.fc48f658.css)

<details><summary>Screenshot:</summary>

![2019 06 22-1](https://user-images.githubusercontent.com/17948007/59958781-789ba080-94b4-11e9-8eb4-b6522d75082f.png)
</details>

**Comment by krystian3w** [comment]
@yourduskquibbles maybe remove prefixes for Opera 12 (`-o-`) or  Konqueror (`-khtml-`), both no support uBO 1.8.0. I suppose no body created fork for these browsers.

Also recomend no prefixed user-select move on last position in CSS filter.

**Comment by XX-J** [comment]
@krystian3w

 Doesn't the `-khtml` prefix refer to Safari?

**Comment by krystian3w** [comment]
Nope, safari use `-webkit-`.

**Comment by yourduskquibbles** [comment]
@krystian3w Just to be clear you just want me to update the filter 

**from** 
`dostfilms.*,downloadcenter.intel.com,kimovil.*##*:style(-webkit-touch-callout: default!important; -webkit-user-drag: element!important; -webkit-user-select: text!important; -moz-user-select: text!important; -khtml-user-select: text!important; -o-user-select: text!important; -ms-user-select: text!important; user-select: text!important;)` 
**to**
`dostfilms.*,downloadcenter.intel.com,kimovil.*##*:style(-webkit-touch-callout: default!important; -webkit-user-drag: element!important; -webkit-user-select: text!important; -moz-user-select: text!important; -ms-user-select: text!important; user-select: text!important;)`
?

**Comment by krystian3w** [comment]
Yes.

**Comment by yourduskquibbles** [comment]
Updated - Thanks for confirming.
