### ISSUE TITLE
opensubtitles.org

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#5859]
`https://www.opensubtitles.org/en/search/sublanguageid-all/idmovie-5614`

Hi. When you go to "`https://www.opensubtitles.org/en/search/sublanguageid-all/idmovie-5614`", or any other movie page on opensubtitles.org, it doesn't show the country language icon (see screenshots) if ublock origin is enabled, but displays everything properly (albeit with ads) if ublock origin is disabled. Is there a way to fix that? Thank you.

![ublock origin on](https://user-images.githubusercontent.com/35790889/59885143-4b51d400-9388-11e9-9563-777af8739bc5.jpg)

![ublock origin off](https://user-images.githubusercontent.com/35790889/59885151-50168800-9388-11e9-9ebe-830585251ebb.jpg)

firefox 67.0.4 (64-bit)
ublock origin 1.20.0

**Comment by okiehsch** [comment]
I can't reproduce
![image](https://user-images.githubusercontent.com/16838044/59888583-b3c0a580-93c8-11e9-81cf-a1a2b61b81bf.png)

**Comment by mapx-** [comment]
Reset uBo to the default settings, test again.Don't use (during the test) any other blocking addon.

**Comment by exodius48** [comment]
Works for me with uBO enabled

![2019-06-21_133635](https://user-images.githubusercontent.com/9832875/59903542-76413400-942b-11e9-96ce-41e144556930.png)

This is my settings `[https://pastebin.com/DZeJdZZN]` @IoanPaleru
