### ISSUE TITLE
sharecool.us

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#586]
Hello,

**URL**

`http://www.sharecool.us/ps/embed/4886217558/`

**Describe the issue**

Anti adblock http://i.imgur.com/ujClZaF.png

**Versions**

uBlock Origin 1.13.8 / Firefox 54

**Settings**

default settings

**Suggested filters**

`sharecool.us##script:inject(overlay-buster.js)`

**Note**

source: https://forums.lanik.us/viewtopic.php?f=62&t=37655

**Comment by gorhill** [comment]
No need to use a scriptlet if plain filters work fine -- `overlay-buster.js` should be used as a last resort, it can be glitchy visually.

**Comment by SMed79** [comment]
Ok, thank you.
