### ISSUE TITLE
pornult.com [NSFW]

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#5863]
### Describe the issue

[Ads and popups.]

### Versions

- Browser/version: [Chrome v75]
- uBlock Origin version: [1.20.0]

### Settings

- [default]

**Comment by kulfoon** [comment]
Ads (extremely high number of ads at the bottom) and popups again, main page.

**Comment by huyszn** [comment]
`https://pornult.com/video/doctor-helped-to-her-patient-to-cum-7306.html`

A 5 second video ad plays before the video starts.
