### ISSUE TITLE
computerfrage.net

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5864]
### URL(s) where the issue occurs

`https://www.computerfrage.net/frage/gamer-pc-keine-leistung-beim-zocken-gpu`

### Describe the issue

Anti Adblock

### Versions

- Browser/version: Firefox 67.0.3
- uBlock Origin version: v1.20.0

### Settings

default

### Notes

The filter `@@||computerfrage.net^$generichide` works for me

**Comment by okiehsch** [comment]
Looks like the same issue as `finanzfrage.net,gesundheitsfrage.net,gutefrage.net`, so I will use the same filter `##+js(abort-on-property-read.js, _sp_._networkListenerData)`.
Are there more such frage-sites that you know of?

**Comment by JobcenterTycoon** [comment]
Now i have a list:
1. `https://www.sportlerfrage.net`
2. `https://www.autofrage.net`
3. `https://www.motorradfrage.net`

**Comment by okiehsch** [comment]
Thanks.
