### ISSUE TITLE
{miner} servers.fivem.net

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#5872]
`https://servers.fivem.net/`

**Comment by mapx-** [comment]
steps to see the miner running ?

**Comment by bogachenko** [comment]
steps

1. open the site
2. admiring mining

**Comment by bogachenko** [comment]
1 tab is open

![Безымянный](https://user-images.githubusercontent.com/8535285/59973441-b94a0580-95eb-11e9-9346-cc8192e1a187.png)

**Comment by dumbusernameidk** [comment]
i think the site does have a miner(?) the script itself appears in the logger as `https://servers.fivem.net/worker.fb6581c12465e40cab4a.js`. But blocking this has a knock-on effect of preventing the tags/names in the boxes from loading. But it does stop the huge CPU utilization.

**Comment by okiehsch** [comment]
That script is certainly responsible for the high CPU usage but don't think it is mining related.
Seems to me like a site issue.
If I block `||servers-live.fivem.net/api/servers/stream/*$xhr`
the CPU-usage is normal but the site is completely broken.

**Comment by dumbusernameidk** [comment]
yeah i was skeptical about it at first i wanna assume the high cpu usage is from the server stuff in the box but that's just a guess.

**Comment by bogachenko** [comment]
@dumbusernameidk

>the server stuff in the box

This shit eats processor more than any game

@okiehsch so what? nothing can be done? do some magic...

**Comment by okiehsch** [comment]
What do you want me to do?
File a complaint with the site owner.
The only way for uBO to "fix" the high CPU is to break their stream.
