### ISSUE TITLE
NSFW hanime.tv

### ISSUE THREAD

**Issue by TsukikagamiTooya** [uBlockOrigin/uAssets#5873]
### URL(s) where the issue occurs
`https://hanime.tv`

### URL(s) where the issue occurs
`https://hanime.tv/hentai-videos/ail-maniax-1`

### Describe the issue
anti-adblocker block UBO and web player can't be show

### Screenshot(s)
![未命名](https://user-images.githubusercontent.com/43428424/59974846-bb13c900-95eb-11e9-88d2-f7d7feb842da.png)

### Versions
- Browser/version: firefox version 67.0.4
- uBlock Origin version: 1.20.0

**Comment by mapx-** [comment]
I cannot reproduce the issue. 
Try resetting uBo to the default settings / lists, update all the lists, test again.

**Comment by JobcenterTycoon** [comment]
i can reproduce. pls delete all cookies on this site and test again.

**Comment by JobcenterTycoon** [comment]
`<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 | `##iframe[src^="https://ads.trafficjunky.net/"]` |  | hanime.tv |  | dom | `https://hanime.tv/hentai-videos/ail-maniax-1` |
| +1 | ##.htvad |  | hanime.tv |  | dom | `https://hanime.tv/hentai-videos/ail-maniax-1` |
| +1 | \|\|trafficjunky.net^$important,third-party | -- | hanime.tv | 3 | frame | `https://ads.trafficjunky.net/ads?zone_id=1775861&site_id=16981&format=HTML&cache=1519396679` |
| +1 | \|\|trafficjunky.net^$important,third-party | -- | hanime.tv | 3 | frame | `https://ads.trafficjunky.net/ads?zone_id=1775851&site_id=16981&format=HTML&cache=1519396666` |
| +1 | @@\|\|htvassets.club/images/partners^ | ++ | hanime.tv | 3 | image | `https://htvassets.club/images/partners/300x250-sara.gif` |
| +1 | ##.htv-video-player > iframe:style(display:block!important;) |  | hanime.tv |  | dom | `https://hanime.tv/hentai-videos/ail-maniax-1` |
| +1 | ##.golden-saucer-bar:style(position: absolute!important; left: -3000px!important;) |  | hanime.tv |  | dom | `https://hanime.tv/hentai-videos/ail-maniax-1` |
| +0 | \|\|googletagmanager.com^ | -- | hanime.tv | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-64196020-9` |
| +0 | @@\|\|cdn.hanime.tv/exoclick.ads*.js | ++ | hanime.tv | 1 | script | `https://cdn.hanime.tv/exoclick.ads.1.0.0.js` |
| +0 | \|\|googletagmanager.com^ | -- | hanime.tv | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-64196020-9` |
| +0 | ##+js(set-constant.js, ABLK, false) |  | hanime.tv |  | dom | `https://hanime.tv/hentai-videos/ail-maniax-1` |
| +0 | ##+js(abort-current-inline-script.js, BetterJsPop) |  | hanime.tv |  | dom | `https://hanime.tv/hentai-videos/ail-maniax-1` |
| +0 | @@\|\|hanime.tv^$generichide | ++ | hanime.tv | 1 | generichide | `https://hanime.tv/hentai-videos/ail-maniax-1` |
</details>
`

**Comment by uBlock-user** [comment]
> delete all cookies

That's what causes the issue to appear, this isn't anti adblock, the site expects certain site data and cookies to be present at all times.

**Comment by dumbusernameidk** [comment]
I can semi-produce it. Some videos work but if i click through more videos then they'll have the error. But it goes away usually if you refresh.
