### ISSUE TITLE
1tv.ru again detects ublock

### ISSUE THREAD

**Issue by vitalif** [uBlockOrigin/uAssets#5874]
### URL(s) where the issue occurs

`https://www.1tv.ru/live`

### Describe the issue

Video player detects uBlock and limits the quality

### Screenshot(s)

![image](https://user-images.githubusercontent.com/945339/60007213-8864e180-967a-11e9-80be-350d61c65065.png)

### Versions

- Browser/version: Firefox 67.0.3
- uBlock Origin version: 1.18.6

### Settings

No changes

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
@vitalif 
When using the actual version of uBlock Origin, I can not reproduce this problem. Try updating uBO to version 1.20.0. More detailed discussion is possible here: https://forums.lanik.us/viewforum.php?f=102

**Comment by vitalif** [comment]
I updated uBlock to 1.20.0 and purged all filter list caches, also I tried the same with a new empty firefox profile - the issue still persists

**Comment by dimisa-RUAdList** [comment]
@vitalif 
Let's discuss it here: https://forums.lanik.us/viewforum.php?f=102
