### ISSUE TITLE
FILTER not working on: https://www.zentrum-der-gesundheit.de/intervallfasten-haeufigsten-fehler-910608.html

### ISSUE THREAD

**Issue by SEXXES** [uBlockOrigin/uAssets#5875]
### URL(s) where the issue occurs

`https://www.zentrum-der-gesundheit.de/intervallfasten-haeufigsten-fehler-910608.html`

### Describe the issue

[Ads called "Anzeige" between lines and on the side. Newsletter overlay.]

### Screenshot(s)

![xxx](https://user-images.githubusercontent.com/42209961/60010519-3fac2900-9678-11e9-8a02-aab4a1a6b271.png)

### Versions

- Browser/version: Chrome Version 75.0.3770.100 (Offizieller Build) (64-Bit, FF 67.0.4
- uBlock Origin version: [1.20.0]

### Settings

![xx](https://user-images.githubusercontent.com/42209961/60010904-00320c80-9679-11e9-9521-5cbd80ad5d29.png)

### Notes

I removed them manually:
! 23.6.2019 https://www.zentrum-der-gesundheit.de
www.zentrum-der-gesundheit.de###sidebar
www.zentrum-der-gesundheit.de###div-zdg_inarticle2 > .products--inner.products
www.zentrum-der-gesundheit.de###div-zdg_inarticle3 > .products--inner.products
www.zentrum-der-gesundheit.de###div-zdg_inarticle1 > .products--inner.products
www.zentrum-der-gesundheit.de###div-zdg_inarticle4 > .products--inner.products
www.zentrum-der-gesundheit.de###div-zdg_inarticle5 > .products--inner.products
www.zentrum-der-gesundheit.de###div-zdg_inarticle6 > .products--inner.products
www.zentrum-der-gesundheit.de###div-zdg_inarticle7 > .products--inner.products
www.zentrum-der-gesundheit.de###div-zdg_inarticle8 > .products--inner.products
www.zentrum-der-gesundheit.de###div-zdg_article_end > .products--inner.products

**Comment by SEXXES** [comment]
Chrome Version 75.0.3770.100 (Offizieller Build) (64-Bit)
FF 67.0.4

**Comment by mapx-** [comment]
or
`zentrum-der-gesundheit.de##[id^="div-zdg_inarticle"]`

@monzta

**Comment by SEXXES** [comment]
zentrum-der-gesundheit.de##[id^="div-zdg_inarticle"]
does NOT remove the sidebar add and the bottom add.
Will they be added to a filter list, if yes to which one?

**Comment by okiehsch** [comment]
````
zentrum-der-gesundheit.de##[id^="div-zdg_inarticle"]
zentrum-der-gesundheit.de##.products__wrapper
zentrum-der-gesundheit.de##.products
````

They could be added the `EasyList Germany`.

**Comment by mapx-** [comment]
yeah, @monzta should add them to easylist Germany

alternative filter
`zentrum-der-gesundheit.de##.products:has([href*="myfairtrade.com"])`

**Comment by mapx-** [comment]
@SEXXES you can report here too:
https://github.com/easylist/easylistgermany/issues

**Comment by JobcenterTycoon** [comment]
Ads are back they change their code after a few hours after a fix got added to EasyList germany

**Comment by mapx-** [comment]
@monzta

`zentrum-der-gesundheit.de##.noprint:has(span:has-text(AN))`
