### ISSUE TITLE
nonktube.com [NSFW]

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#5877]
### Describe the issue

[Popups when clicking on videos.]

### Versions

- Browser/version: [Chrome v75]
- uBlock Origin version: [1.20.0]

### Settings

- [default]

**Comment by mapx-** [comment]
@okiehsch 
Did you try in FF ? still getting a popup on the first clicking any video on home page.

**Comment by dumbusernameidk** [comment]
yeah doesn't seem to work in firefox.

**Comment by okiehsch** [comment]
Yes, I can reproduce with Firefox. The popup is blocked and closed on my end.
The site opens the legitimate videos in a popup, so I don't see a way to prevent the popups without breaking the site.

**Comment by dumbusernameidk** [comment]
yeah it seems to already get blocked anyway by default. still a minor annoyance but not a big deal.

**Comment by JobcenterTycoon** [comment]
When i block `xclickers.com` i can prevent the redirect to another sites without breakting the video.

**Comment by ghajini** [comment]
Firefox android checked.....
Site doesn't need `xclickers.com` popup for playing legitimate videos....
Clear data then open any video,popup opened ,popup closed by some filter but this does not open actual video....now click on any video, legitimate video opens without going through `xclickers.com`.....
