### ISSUE TITLE
lavoz.com.ar [blocked page]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5878]
URL(s) where the issue occurs

`https://www.lavoz.com.ar/`

Describe the issue

Anti-Adblock

![](https://k62.kn3.net/2/F/5/2/9/A/D7A.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![](https://k50.kn3.net/B/7/A/3/5/4/6AC.png)
Google Chrome Version : 75 (Official Build) (64-bit)

![](https://k50.kn3.net/D/D/4/5/E/9/CDB.png) 
uBlock Origin Version: 1.20.0

Settings

Default

**Comment by dumbusernameidk** [comment]
site doesn't work even if i disable ubo.

**Comment by okiehsch** [comment]
It works if I add
````
@@||doubleclick.net/gampad/*$script,domain=lavoz.com.ar
@@||doubleclick.net/gpt/$script,domain=lavoz.com.ar
@@||googletagservices.com/tag/js/gpt.js$script,domain=lavoz.com.ar
@@||storage.googleapis.com/adcase.io/dist/*$script,domain=lavoz.com.ar
````
If you have the `uBO-experimental` list enabled, you have to disable it for this site because there is an `important` filter in it that breaks the site.

**Comment by dumbusernameidk** [comment]
i can only load the webpage if i take off the `.ar` part. and i'm not even sure if it's the same webpage.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/60142375-d2a0ac80-97b9-11e9-84ba-8953669745d3.png)

Works on my end if I add the mentioned exception filters.

**Comment by okiehsch** [comment]
Are you maybe using Firefox with the Firefox tracking protection enabled?

**Comment by dumbusernameidk** [comment]
No i'm trying it in chrome but yeah even with ubo and cookies cleared the site doesn't load. maybe based on ip?

**Comment by okiehsch** [comment]
What IP location do you have if you don't me asking.
My screenshot above has a US based IP.

**Comment by dumbusernameidk** [comment]
I'm using a us ip as well which is strange mobile version loads but not normal site. if i disable ubo and look at the console it says `https://www.googletagservices.com/tag/js/gpt.js` ERR_NAME_NOT_RESOLVED. same for `stats.g.doubleclick.net` and `static.chartbeat.com`.

**Comment by okiehsch** [comment]
> ERR_NAME_NOT_RESOLVED

Sounds like you have DNS problems. Though if they appear in the logger .... 
Don't know I am no expert.
`https://www.googletagservices.com/tag/js/gpt.js needs` to be loaded properly for this site to function.

**Comment by dumbusernameidk** [comment]
yeah strange why it doesn't work.
