### ISSUE TITLE
mybanktracker.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#5879]
### URL(s) where the issue occurs

`https://www.mybanktracker.com/news/avoid-getting-shortchanged-coin-counter-machine-coinstar`

### Describe the issue

`Sponsored Savings Rates` on right column.

### Notes

`##div.ng-scope:nth-of-type(2) > .ng-scope.featured-rates`

**Comment by mapx-** [comment]
`mybanktracker.com###stackableAdsTarget`

@ryanbr

**Comment by terrorist96** [comment]
Also ads at the bottom of articles.

`||widgets.mbtmedia.com/widgets/1286ce/p/sav-article-savings-bundle/savings-product`

**Comment by mapx-** [comment]
maybe

`mybanktracker.com###article-content > .lazyloaded`

@ryanbr

**Comment by terrorist96** [comment]
> maybe
> 
> `mybanktracker.com###article-content > .lazyloaded`
> 
> @ryanbr

Works for me.

**Comment by ryanbr** [comment]
Which ads? I'm not seeing ads here

**Comment by terrorist96** [comment]
@ryanbr 
![image](https://github.com/uBlockOrigin/uAssets/assets/12802056/476294b3-2547-4eda-9bb3-8d81c4f60c46)

**Comment by stephenhawk8054** [comment]
@ryanbr Seems need US IP. I can reproduce when using VPN to US.
