### ISSUE TITLE
Madmimi blocked

### ISSUE THREAD

**Issue by siffegh** [uBlockOrigin/uAssets#5880]
### URL(s) where the issue occurs

`lifelyforlife.com`

### Describe the issue

The host site `https://sable.madmimi.com` is being blocked by the hpHosts filter.

### Screenshot(s)

`https://www.dropbox.com/s/3pvazga9x0t9gau/Screenshot_1.png?dl=0`

### Versions

- Browser/version: FF 67.0.4
- uBlock Origin version: 1.2.0

### Settings

-{
"timeStamp": 1561428140874,
  "version": "1.20.0",
  "userSettings": {
    "advancedUserEnabled": true,
    "alwaysDetachLogger": true,
    "autoUpdate": true,
    "cloudStorageEnabled": false,
    "collapseBlocked": true,
    "colorBlindFriendly": false,
    "contextMenuEnabled": true,
    "dynamicFilteringEnabled": true,
    "externalLists": "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt\nhttps://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt",
    "firewallPaneMinimized": false,
    "hyperlinkAuditingDisabled": true,
    "ignoreGenericCosmeticFilters": true,
    "largeMediaSize": 50,
    "parseAllABPHideFilters": false,
    "prefetchingDisabled": true,
    "requestLogMaxEntries": 1000,
    "showIconBadge": true,
    "tooltipsDisabled": false,
    "webrtcIPAddressHidden": false
  },
  "selectedFilterLists": [
    "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt",
    "plowe-0",
    "hphosts",
    "fanboy-annoyance",
    "easyprivacy",
    "easylist",
    "awrl-0",
    "ublock-filters",
    "user-filters"
  ],
  "hiddenSettings": {
    "allowGenericProceduralFilters": false,
    "assetFetchTimeout": 30,
    "autoCommentFilterTemplate": "{{date}} {{origin}}",
    "autoUpdateAssetFetchPeriod": 120,
    "autoUpdateDelayAfterLaunch": 180,
    "autoUpdatePeriod": 7,
    "cacheStorageAPI": "unset",
    "cacheStorageCompression": true,
    "cacheControlForFirefox1376932": "no-cache, no-store, must-revalidate",
    "consoleLogLevel": "unset",
    "debugScriptlets": false,
    "disableWebAssembly": false,
    "ignoreRedirectFilters": false,
    "ignoreScriptInjectFilters": false,
    "manualUpdateAssetFetchPeriod": 500,
    "popupFontSize": "unset",
    "requestJournalProcessPeriod": 1000,
    "selfieAfter": 3,
    "strictBlockingBypassDuration": 120,
    "suspendTabsUntilReady": "unset",
    "userResourcesLocation": "unset"
  },
  "netWhitelist": "about-scheme\napp.starbucks.com\nchrome-extension-scheme\nchrome-scheme\nfilext.com\nmoz-extension-scheme\nopera-scheme\notc.tax.ny.gov\npayments.ncdot.gov\nsecure.bankofamerica.com\nshop.mercola.com\nshopsafe.bankofamerica.com\ntierrafarmstore.com\nvivaldi-scheme\nws04.nyenet.state.ny.us\nwww.cpuid.com\nwww.freefilefillableforms.com\nwww.vitacost.com\nwww7b.tax.ny.gov\nwyciwyg-scheme",
  "dynamicFilteringString": "behind-the-scene * * noop\nbehind-the-scene * inline-script noop\nbehind-the-scene * 1p-script noop\nbehind-the-scene * 3p-script noop\nbehind-the-scene * 3p-frame noop\nbehind-the-scene * image noop\nbehind-the-scene * 3p noop",
  "urlFilteringString": "",
  "hostnameSwitchesString": "no-large-media: behind-the-scene false\nno-scripting: behind-the-scene false\nno-cosmetic-filtering: * true",
  "userFilters": ""
}

### Notes

Disabled the hpHosts filter which allows the site to load.

**Comment by mapx-** [comment]
does this exception help ?
`@@||madmimi.com/signups/$frame,domain=lifelyforlife.com`

**Comment by siffegh** [comment]
Hmm, I sent this via email last night; it never got here:

> does this exception help ?

Doesn't seem to, if I've done it correctly; I added it to 'My filters' 
and imported it into the Whitelist.

**Comment by mapx-** [comment]
Do you see the exception in the logger ? What is still wrong ?

**Comment by mapx-** [comment]
You can update unbreak list.

> imported it into the Whitelist. 
only in "my filters" or update unbreak list

**Comment by siffegh** [comment]
I'm not familiar with the logger or the unbreak list. How do I subscribe to that?

I put the filter into My filters and am getting the same response as before - `https://www.dropbox.com/s/3pvazga9x0t9gau/Screenshot_1.png?dl=0`.

**Comment by mapx-** [comment]
Explain how to get the issue, steps, what to click, which moment do you get it

**Comment by mapx-** [comment]
read about the logger
https://github.com/gorhill/uBlock/wiki/The-logger

read how to update the lists (unbreak list is already enabled by default in uBo)
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now

**Comment by mapx-** [comment]
I tested th subscription, working fine for me (it's where madmimi is used on page, right ?)

**Comment by siffegh** [comment]
I know how to update but had disabled Unbreak :-)

I discovered why it won't work for me: I've been clicking a link in an email which says `lifelyforlife.com`, which I originally mis-reported as the URL that won't work.

The actual url for that link is (`https://sable.madmimi.com/c/255209?id=3690.8.1.5090dfd2e7d4cfebc46588a502fec97a`), as is seen in my Screenshot. What you see there is what I get when I click `lifelyforlife.com` in the email. There is nothing noted in the logger (thanks for the pointer to logger info).

Going to `lifelyforlife.com` external from the email works fine even with Unbreak disabled. Going to `https://sable.madmimi.com/c/255209?id=3690.8.1.5090dfd2e7d4cfebc46588a502fec97a` external from the email does not work with it enabled.

**Comment by mapx-** [comment]
Now should work.

**Comment by siffegh** [comment]
Thanks, it does work now.
