### ISSUE TITLE
quicksleeper.pl

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#5882]
`http://quicksleeper.pl` right click blocked (also on mobile)

**Comment by krystian3w** [comment]
Sister site with same block:

`http://coag.pl`

**Comment by JobcenterTycoon** [comment]
The filters `quicksleeper.pl##+js(abort-on-property-write.js, document.oncontextmenu)` and
`coag.pl##+js(abort-on-property-write.js, document.oncontextmenu)` works for me

**Comment by mapx-** [comment]
test & tell me is breaks something
`coag.pl,quicksleeper.pl##+js(abort-on-property-read.js, document.oncontextmenu)`

**Comment by krystian3w** [comment]
All works fine.
