### ISSUE TITLE
discordapp.com

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#5883]
### URL(s) where the issue occurs

Any random server or thread on `https://discordapp.com`

### Describe the issue

This is somewhat related to https://forums.lanik.us/viewtopic.php?f=64&t=43113, but I now have an additional example and a decent-ish solution:

When pasting certain links into Discord channels/chats, their embed images fail to load due to generic blocking rules in various lists (Usually EasyList).

* Example 1: Paste https://adguard.com/en/adguard-windows/overview.html (Image fails to load due to `/adguard.$domain=~adguard.com|~adguard.mobi|~adguard.oneskyapp.com|~greinr.com` in EasyList).
* Example 2: Paste https://www.ispot.tv/ad/7Jao/lactaid-milk-dont-forget-the-milk (Image fails to load due to `
.net/ad/$image` in EasyList; the link leads to what seems to be an online video site and therefore does not need to be code-bracketed.)

The solution I propose for Discord only: `@@||discordapp.net$image,domain=discordapp.com`

### Screenshot(s)

* Example 1: 
![image](https://user-images.githubusercontent.com/22780683/60284884-f1638800-990c-11e9-8fc9-5c999f3feee2.png)
* Example 2: 
![image](https://user-images.githubusercontent.com/22780683/60284802-c37e4380-990c-11e9-81a7-02e4f4c9f781.png)

### Versions

- Browser/version: Google Chrome 75.0.3770.100 64-bit for Windows
- uBlock Origin version: Nano Adblocker 1.0.0.118 + Nano Defender 15.0.0.153

### Settings

* Lists used: 
![image](https://user-images.githubusercontent.com/22780683/60284972-2b348e80-990d-11e9-80db-57ce51a6c2fa.png)
* Advanced settings: 
![image](https://user-images.githubusercontent.com/22780683/60284996-3be50480-990d-11e9-8de9-71c7783bbaad.png)

### Notes

I was not able to get `@@||discordapp.com$generichide` to work, and I was not personally able to figure out why.

I could not see any existing blocking rules in EasyList, uAssets Base or AdGuard Base that targeted Discord images of any kind, so I presume it's okay to whitelist `discordapp.net` as a whole.

Additionally, it seems that `.net/ad/$image` caused problems with the video suggestions on `iSpot` as well, such that I propose adding `@@||.cloudfront.net/ad/$image,domain=ispot.tv` as well: 
![image](https://user-images.githubusercontent.com/22780683/60285295-e9f0ae80-990d-11e9-9a0b-60451f2d1831.png)

**Comment by okiehsch** [comment]
`@@||discordapp.com^$generichide`
works fine on my end.
![image](https://user-images.githubusercontent.com/16838044/60297279-203b2780-9928-11e9-8efa-207672994348.png)

> Additionally, it seems that .net/ad/$image caused problems with the video suggestions on iSpot as well, such that I propose adding @@||.cloudfront.net/ad/$image,domain=ispot.tv as well:

Can you point me to those video suggestions?

**Comment by DandelionSprout** [comment]
>`@@||discordapp.com^$generichide` works fine on my end.

Ah, okay. I'll take your word for it, then.

>Can you point me to those video suggestions?

They should be beneath the video information values: 
![image](https://user-images.githubusercontent.com/22780683/60323902-a2a50500-9983-11e9-9cbd-e2fbca29d31f.png)

**Comment by krystian3w** [comment]
direct links?

**Comment by DandelionSprout** [comment]
Presuming you're talking about iSpot ([Example link is the same as in the Discord part of the issue report](https://www.ispot.tv/ad/7Jao/lactaid-milk-dont-forget-the-milk)), I believe they probably serve as direct links, but that images are supposed to show up above the grey links. Here's how the oranged part above (and apparently also the *Screenshots* section) looks like with `@@||.cloudfront.net/ad/$image,domain=ispot.tv`: 
![image](https://user-images.githubusercontent.com/22780683/60368573-817afd80-99f1-11e9-8242-00afa1be7769.png)

**Comment by krystian3w** [comment]
or:

```
@@||cloudfront.net/ad/*-small-*$image,domain=ispot.tv
@@||cloudfront.net/img/events/event-placeholder.png$image,domain=ispot.tv
```

i no block "big" photos?

**Comment by okiehsch** [comment]
I don't use `discordapp`, can you narrow the exception or is that not possible?
What are the requests blocked in your examples 1 and 2.

**Comment by krystian3w** [comment]
for discord works only:

`@@/adguard.$image` IMO.

**Comment by krystian3w** [comment]
> can you narrow the exception or is that not possible?

works:

```
/adguard.$domain=~adguard.com|~adguard.mobi|~adguard.oneskyapp.com|~greinr.com,badfilter
/adguard.$domain=~adguard.com|~adguard.mobi|~adguard.oneskyapp.com|~greinr.com|~discordapp.net|~discordapp.com
```

**Comment by krystian3w** [comment]
> can you narrow the exception or is that not possible?

NO... works:

```
/adguard.$domain=~adguard.com|~adguard.mobi|~adguard.oneskyapp.com|~greinr.com,badfilter
/adguard.$domain=~adguard.com|~adguard.mobi|~adguard.oneskyapp.com|~greinr.com|~discordapp.net|~discordapp.com
```

**Comment by DandelionSprout** [comment]
>What are the requests blocked in your examples 1 and 2.

Example 1: ![image](https://user-images.githubusercontent.com/22780683/60373080-2f40d900-99ff-11e9-962f-c89687e55573.png)
Example 2: ![image](https://user-images.githubusercontent.com/22780683/60373109-4e3f6b00-99ff-11e9-8b0c-342d221dc652.png)

>can you narrow the exception

That is possible, but would only work for example 1, and not with any other kinds of links at all.

**Comment by krystian3w** [comment]
IMO discord no have ads, so we can add exception or on EasyList:

```
@@||discordapp.net/external/*/img$image,domain=discordapp.com
```

**Comment by okiehsch** [comment]
`@@||discordapp.net/external/*/img$image,domain=discordapp.com`
won't work for Example 2 or am I mssing something?

**Comment by krystian3w** [comment]
I see..., `/img/` is from AdGuard URL only.

```
@@||discordapp.net/external/*$image,domain=discordapp.com
```

**Comment by DandelionSprout** [comment]
I realised a couple of minutes late that your (okiehsch) question was not about EasyList's rule, but about my suggested blocking rule.

**Comment by krystian3w** [comment]
EasyList use both fix if you analize filters.


The only explanation is the size of the letters in the url...
