### ISSUE TITLE
http://bestoflaptops.com

### ISSUE THREAD

**Issue by KingHavok** [uBlockOrigin/uAssets#5887]
### URL(s) where the issue occurs

`http://bestoflaptops.com/87CX`

### Describe the issue

[WELCOME!
IT LOOKS LIKE YOU'RE USING AN AD BLOCKER. THAT'S OKAY. WHO DOESN'T?
But without advertising-income, we can't keep making this site awesome.

I understand, I have disabled my ad blocker. Let me in!]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Chrome Version 75.0.3770.100 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.20.0

### Settings

- [Nil]

### Notes

[Tried blocking https://www.google.com/js/bg/ as every time the page loads it tries to load
https://www.google.com/js/bg/NAME_CHANGES_EVERY_TIME.js.]

**Comment by mapx-** [comment]
`http://bestoflaptops.com/87CX` redirects to `http://talkittechy.com/87CX` which is already fixed
