### ISSUE TITLE
Lifewire.com displaying ads(whitelisted for some reason) and blocking inspect element

### ISSUE THREAD

**Issue by Plazmaz** [uBlockOrigin/uAssets#589]
### URL(s) where the issue occurs

`https://www.lifewire.com/shortening-long-links-3486603`

### Describe the issue
Lifewire.com seems to be displaying doubleclick ads due to being whitelisted on EasyList with this line:
`@@||g.doubleclick.net/gpt/pubads_impl_$script,domain=baltimoresun.com|boston.com|calgaryherald.com|capitalgazette.com|carrollcountytimes.com|chicagotribune.com|chroniclelive.co.uk|citypaper.com|cnet.com|courant.com|dailypress.com|deathandtaxesmag.com|edmontonjournal.com|edmunds.com|everquest.allakhazam.com|financialpost.com|gofugyourself.com|hearthhead.com|ibtimes.com|idigitaltimes.com|infinitiev.com|latimes.com|leaderpost.com|lifewire.com|lolking.net|mcall.com|metacritic.com|montrealgazette.com|msn.com|nasdaq.com|nationalpost.com|orlandosentinel.com|ottawacitizen.com|ranker.com|sandiegouniontribune.com|saveur.com|sherdog.com|spin.com|sporcle.com|sun-sentinel.com|thebalance.com|theprovince.com|thespruce.com|thestarphoenix.com|timeanddate.com|tmn.today|twincities.com|vagazette.com|vancouversun.com|vibe.com|windsorstar.com`

I'm not sure why this site was whitelisted, but their behavior seems pretty shady. They seem to delete their ads and change their source code when the chrome dev console is opened, though I am unsure of how they achieved this.

### Screenshot(s)

![Source changing](https://i.imgur.com/m7NyHen.gif)

### Versions

- Browser/version: 59.0.3071.115 (Official Build) (64-bit)
- uBlock Origin version: 1.13.8

### Settings

- Enabled WebRTC leak blocking
- Custom filters:
```
! 3/17/2017, 7:18:47 PM http://en.freedownloadmanager.org/Windows-PC/Autorun-inf-Check-FREE.html
||restaurants.infcdn.net/img/fdm728.gif$image

! 3/17/2017, 7:18:53 PM http://en.freedownloadmanager.org/Windows-PC/Autorun-inf-Check-FREE.html
||restaurants.infcdn.net/img/siclient.gif$image

! 4/17/2017, 9:31:36 AM https://www.nbmcw.com/concrete/564-an-overview-of-some-development-in-concrete-technology.html
||www.nbmcw.com/images/nbm-media/common-files/HolyOffer/Anniversary-Offer.gif$image

! 4/17/2017, 9:32:04 AM https://www.nbmcw.com/concrete/564-an-overview-of-some-development-in-concrete-technology.html
||www.nbmcw.com/images/banners/*$image

! 6/23/2017, 1:37:07 PM http://www.url-encode-decode.com/
www.url-encode-decode.com##.box-content > .row:nth-of-type(1)

! 7/6/2017, 10:40:57 AM http://smallseotools.com/backlink-checker/
smallseotools.com##.hide_on_mobile.col-sm-5

! 7/6/2017, 10:41:11 AM http://smallseotools.com/backlink-checker/
smallseotools.com###img1

! 7/6/2017, 10:41:22 AM http://smallseotools.com/backlink-checker/
||smallseotools.com/images/1234.png$image

! 7/14/2017, 8:53:00 AM http://www.littlemissmomma.com/2011/01/how-to-get-sponsors-for-your-blog.html
||a.interactivead.network/ad_id/*$subdocument

! 7/17/2017, 8:58:47 AM http://smallbusiness.chron.com/bluetooth-headset-unable-connect-61027.html
||embed.sendtonews.com/player2/*$subdocument

! 7/17/2017, 8:58:53 AM http://smallbusiness.chron.com/bluetooth-headset-unable-connect-61027.html
smallbusiness.chron.com##.s2nPlayer-YAaYpzmO

! 7/22/2017, 4:17:11 PM http://ark.gamepedia.com/Module:Achievement/list
ark.gamepedia.com###zergnetContainer
```

### Notes

It would certainly be worth figuring out how the script changing is accomplished. I think chromium team may be interested in knowing about it. You can get the page source using curl or wget if needed.

**Comment by okiehsch** [comment]
`lifewire.com` uses [Instart Logic](https://github.com/uBlockOrigin/uAssets/issues/227), the only way to fix your issue is to
1. Use [uBO-Extra](https://github.com/gorhill/uBO-Extra/wiki/Sites-on-which-uBO-Extra-is-useful)
2. Use Firefox, which is not affected by Instart Logic.
