### ISSUE TITLE
wixsite.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#5892]
### URL(s) where the issue occurs

`https://shiroqueen01.wixsite.com/shiroqueen/single-post/2016/07/26/Cultura-Nipo-Kakigori-Raspadinha-de-gelo`
`https://shostkashans92.wixsite.com/shans`
`https://enzanseikotuin.wixsite.com/home`

### Describe the issue

Annoyance: sticky bar at the top.

### Versions

- Browser/version: 67
- uBlock Origin version: 1.20.0

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin lists

**Comment by mapx-** [comment]
just use
`###WIX_ADS`
