### ISSUE TITLE
dispatch.com

### ISSUE THREAD

**Issue by rkenimer** [uBlockOrigin/uAssets#5896]
### URL(s) where the issue occurs

`https://www.dispatch.com/entertainmentlife/20190630/circumstances-prompt-bexley-couple-to-sell-beloved-home-only-months-after-building-it`

### Describe the issue

Site loads modal subscription windows, and prevents scrolling once the modals are removed.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Chrome 75.0.3770.100
- uBlock Origin version: 1.20.0

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

I started by posting on the lanik forum and they provided the following filters that work, hopefully they could be included in your lists:

> dispatch.com##.tp-modal
> dispatch.com##.tp-active.tp-backdrop
> dispatch.com##body:style(overflow: auto !important;)

**Comment by mapx-** [comment]
@rkenimer , yep I (_intense_ from lanik forum) provided those filters and I already added them to uBo annoyances list (in the first `Built-in` section just enable `uBlock filters – Annoyances​​`​​​ list)
