### ISSUE TITLE
Prevent videos from playing automatically

### ISSUE THREAD

**Issue by tobbi** [uBlockOrigin/uAssets#59]
### URL(s) where the issue occurs

http://www.chip.de/news/Bei-Aldi-Notebook-Medion-Akoya-E6424_92379607.html
### Describe the issue

I am not sure if other people agree with me, but I'd like to block videos playing automatically (which I deem to be terrible website design) unless people specifically expect a video to play (this includes video sites like YouTube). I think it's rather obnoxious and annoying when all you want is read a nice article and a video starts to play which you have to stop manually (because you really don't care about the video). 

If the video could be blocked from loading in the first place, that would be great.
### Versions
- Browser/version: Firefox Nightly, 49.0a1
- uBlock Origin version: 1.7.4

**Comment by IDKwhattoputhere** [comment]
What about:
`about:config` -> `media.autoplay.enabled` -> set to `false`

**Comment by tobbi** [comment]
> What about:
> about:config -> media.autoplay.enabled -> set to false

This would disable auto-play globally. I'd rather want to prevent videos from loading on a per-site basis.

**Comment by IDKwhattoputhere** [comment]
You could [block large media elements on the site](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-large-media-elements) (set a higher threshold in the settings if you want) and toggle it off and click on the player in case you want to watch the video.

**Comment by tobbi** [comment]
The interesting thing is: Even after setting the "Block media elements larger than" to 0 KB, the video still plays automatically. I should possibly report this to the other repo?

**Comment by gwarser** [comment]
>the video still plays automatically

From cache.

**Comment by tobbi** [comment]
No, even after disabling the cache (or loading a new private browsing window which circumvents the cache), it still automatically plays.

**Comment by gorhill** [comment]
I will personally decline working on this. Anybody feel free to create the solution -- if any. If it is sane, I will consider importing it.

**Comment by happysurf** [comment]
The solution is simple and already present in Firefox:
`media.autoplay.enabled  from true to false`

**Comment by IDKwhattoputhere** [comment]
@happysurf https://github.com/uBlockOrigin/uAssets/issues/59#issuecomment-223699913

**Comment by happysurf** [comment]
@IDKwhattoputhere sorry, my fault.
