### ISSUE TITLE
DailyMotion Player not loaded on beIN SPORTS

### ISSUE THREAD

**Issue by remitamine** [uBlockOrigin/uAssets#5900]
### URL(s) where the issue occurs

`https://www.beinsports.com/us/laliga/video/ray-hudson-neymar-should-go-back-to-barca/1231676`

### Describe the issue

videos on beIN SPORTS website can't be loaded(hosted on DailyMotion).

### Versions

- Browser/version: Firefox Developer Edition/68.0b14
- uBlock Origin version: 1.20.0

### Settings

- Block CSP.
- Prevent WebRTC from leaking local IP addresses.
- I'm an advanced user.

### Notes

the reason for the videos not been loaded is that the code for loading the player is enclosed in this block after loading the `analytics.js` script.
```js
    ga(function(tracker) {
...
    });
```
the issue happen when at least one of this cases apply:
- `googletagmanager.com/gtm.js` blocked -> `hpHosts’ Ad and tracking servers` list enabled
- `google-analytics.com/analytics.js` blocked -> blocked by multiple lists.
`AdGuard Tracking Protection` list has unblocking rule specific for `analytics.js` on `beinsports.com` domain.
-  `uBlock filters – Experimental​` list enabled, even with unblocking rules for the mentioned scripts were added(i know that list is expirimental but at least there should be a way to fix website breakup while keeping the list enabled).

i would've opened a PR with the rules that i'm using now, but i'm not sure how to deal with the experimental list problem.
```
@@||googletagmanager.com/gtm.js$domain=beinsports.com
@@||google-analytics.com/analytics.js$domain=beinsports.com
```

**Comment by remitamine** [comment]
after looking at the unbrick list it does contain a rule for `gtm.js` script on beIN SPORTS but specific to the Turkish website, so it would be better to relax the domain part(just `beinsport.com` instead of `tr.beinsports.com`).

**Comment by mapx-** [comment]
this should work
```
@@||googletagmanager.com/gtm.js$script,domain=beinsports.com
@@||google-analytics.com/analytics.js$script,domain=beinsports.com
||google-analytics.com/analytics.js$script,redirect=google-analytics.com/analytics.js,important,badfilter
||google-analytics.com/analytics.js$script,redirect=google-analytics.com/analytics.js,important,domain=~beinsports.com
```
