### ISSUE TITLE
hotgameplus.com

### ISSUE THREAD

**Issue by kenviet** [uBlockOrigin/uAssets#5901]
### URL(s) where the issue occurs

`https://www.hotgameplus.com/`

### Describe the issue

Detecting adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24647715/60518568-0f046900-9ce2-11e9-90b9-194c38fbe6ee.png)

### Versions

- Browser/version: Opera Version:62.0.3331.18
- uBlock Origin version: 1.20.0

### Settings

- All default

### Notes

None

**Comment by kenviet** [comment]
Scrollbar is missing

**Comment by mapx-** [comment]
Are you using fanboy's annoyances list ?

**Comment by kenviet** [comment]
No not at all
Here is the list if you want to know

![image](https://user-images.githubusercontent.com/24647715/60737191-20f04100-9f5a-11e9-8f2d-dddeb032b991.png)
