### ISSUE TITLE
sockshare.net  -  opens new browser window ads.... 

### ISSUE THREAD

**Issue by beansncheese** [uBlockOrigin/uAssets#591]
### URL(s) where the issue occurs

`[http://free.internetspeedtracker.com/index.jhtml?partner=^BBQ^xpu042&s1=1062804&s2=348391265888&s3=&s4=&s5=&rt=1]`

`[http://sockshare.net/watch/rdmB67vX-elementary-season-4.html]`

about every 2nd or 3rd click on shockshare produces a new browser window / tab pop up style ad .

### Screenshot(s)

![screenshot 2017-07-28 12 56 40](https://user-images.githubusercontent.com/30516114/28701911-711c79ee-7394-11e7-89aa-359aae02f3dd.png)

### Versions

Firefox 54.0.1  - 32bit
Ublock Origin 1.13.8

### Settings

No changes

### Notes
I'm not technically minded so mercy... but i couldn't find any solution on reddit, googling etc..

**Comment by okiehsch** [comment]
Does
`sockshare.net##script:inject(abort-on-property-write.js, Q8w56)`
work or are there any other popups?

**Comment by beansncheese** [comment]
Hi thanks for your quick reply.

I'm afraid I'm kind of inexperienced about coding and things, sorry.

 And I'm away from my computer now.

The 'script' ? you provided me ( 
sockshare.net##script:inject(abort-on-property-write.js, Q8w56)

Do I input that into ublock orgin somehow? (I assume I can add it to 
filters area)?

I will research it when I get back in. Thanks!

**Comment by SMed79** [comment]
@beansncheese Test the filter above as a custom filter.
see https://streamable.com/s/jlv0t/fnpphm

**Comment by beansncheese** [comment]
Ok
thanks!

**Comment by beansncheese** [comment]
thanks for the clear screen movie instruction!  in input the filter and have poked around many pages and links and it seems successful!
  
Merci Beaucoup, Muchas Gracious Arigatos!!

**Comment by ghajini** [comment]
`http://www1.sockshare.icu/watch/kvYNeyWx-the-lego-movie-2-the-second-part.html`
malicious ads
