### ISSUE TITLE
lifo.gr anti adb

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#5916]
![Clipboard01](https://user-images.githubusercontent.com/24896778/60673959-b79cff00-9e81-11e9-91cd-e9637c9ae3bd.jpg)

sample link:
`https://www.lifo.gr/now/greece/243417/aparadektes-synthikes-sto-metro-en-meso-kaysona`

thanks

**Comment by mapx-** [comment]
```
@@||googletagservices.com/tag/js/gpt.js$script,domain=lifo.gr
@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$script,domain=lifo.gr
@@||securepubads.g.doubleclick.net/gampad/$script,domain=lifo.gr
```

**Comment by okiehsch** [comment]
Fixed in annoyances.
