### ISSUE TITLE
uwatchfree.st

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5917]
### URL(s) where the issue occurs

`https://www.uwatchfree.st/2019/07/karenjit-kaur-2019-season-3-complete/`

### Describe the issue

popup ads

### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.20

### Settings

-  uBO's default settings

### Notes
same ads
`http://1uwatchfree.online/spider-man-far-from-home-2019-v2-new-hindi-dubbed-full-movie-watch-online-hd-print-free.html`

**Comment by ghajini** [comment]
same like site
`https://www.uwatchfreetv.online/2019/05/watch-indias-most-wanted-2019.html`
popup ads

**Comment by ghajini** [comment]
`uwatchfree.st` redirects to 
`https://www.uwatchfree.ai/`
Popup ads
Firefox android

Domains `1uwatchfree.online` ,`uwatchfreetv.online` are not available

**Comment by ghajini** [comment]
`https://uwatchfree.bz/netutv.php?vid=oH0m4MCd0MP1`

**firefox android stable** ubo stable
Does video start ,clicking multiple times,no problem on desktop browsers

For popups 
`netu.in##+js(nowoif)`

**Comment by mapx-** [comment]
`||netu.in/js/d_check.js$script,1p` is breaking the video on my end

**Comment by ghajini** [comment]
How to prevent site from gathering device info

**Comment by ghajini** [comment]
`http://www.uwatchfree.tech/`
Propeller Ads

**Comment by mapx-** [comment]
test

`uwatchfree.*##+js(aost, Math.floor, , 2)`

for breakage

**Comment by ghajini** [comment]
Yeah make it as a 
`uwatchfree.tech##+js(aost, Math.floor, , 2)`

Because involving all domains will break domains such as `uwatchfree.mn`

So
```
uwatchfree.tech##+js(aost, Math.floor, , 2)
||voawhooh.net^
||suptaibo.com^
||glogoowo.net^
```
