### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by Neurotoxin001** [uBlockOrigin/uAssets#5919]
### URL(s) where the issue occurs
https://twitter.com/Neurotoxin001/status/1146853206523371520

### Describe the issue
Can't see my own tweet

### Versions

- Browser/version: Google Chrome 75.0.3770.100
- uBlock Origin version: 1.20.0

### Notes
Because of this rule:
`twitter.com##article:has-text(/Promoted|Gesponsert|Реклама|Promocionado/):xpath(../..)`
In uBlock filters.

**Comment by mapx-** [comment]
Did you remove `Реклама` from your tweet ?

**Comment by Neurotoxin001** [comment]
> Did you remove Реклама from your tweet ?
It's not in my tweet, it's in link description...

**Comment by mapx-** [comment]
> Can't see my own tweet

I don't see the filter above going to that tweet

**Comment by Neurotoxin001** [comment]
It's because of this:
![image](https://user-images.githubusercontent.com/39812401/60700934-739e0e80-9f02-11e9-9ee4-191aab07a5ac.png)

**Comment by mapx-** [comment]
test
```
twitter.com#@#article:has-text(/Promoted|Gesponsert|Реклама|Promocionado/):xpath(../..)
twitter.com##:xpath(//span[(text()='Promoted' or text()='Gesponsert' or text()='Реклама' or text()='Promocionado')]/../../../../..)
```

and see if `Реклама` posts are still hidden

**Comment by Neurotoxin001** [comment]
> test

Now I can see my tweet, thanks.
