### ISSUE TITLE
script:inject(...) filters

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#592]
Please add the following domains:
globes.co.il, mako.co.il, reshet.tv, walla.co.il, yad2.co.il, ynet.co.il

to the filter:
101greatgoals.com,allthetests.com,ancient-origins.net,biology-online.org,calcalist.co.il,eurweb.com,grammarist.com,jerusalemonline.com,roadracerunner.com,textsfromlastnight.com,trifind.com,x17online.com##script:inject(abort-on-property-write.js, upManager)

(calcalist.co.il already included)

I want to remove all _script:inject_ filters from Easylist Hebrew. Issues with ABP - https://github.com/easylist/EasyListHebrew/issues/262

Thanks

**Comment by Modified** [comment]
I suspect this rule breaks yad2.co.il for me. (A specific feature: stupid side hides phone numbers for rentals, forcing you to click a link, triggering — log shows — lots of AJAX and other traffic/activity, most of which I actually want blocked, but, I'm guessing, rendering of the fetched phone data is blocked/broken, unfortunately.)

Haven't figured out how to circumvent/whitelist this "filter" (or is it "rule"?), yet.

Help? 
(BTW, I'm a web dev.)

**Comment by okiehsch** [comment]
> Haven't figured out how to circumvent/whitelist this "filter" (or is it "rule"?), yet.

`yad2.co.il#@#script:inject(abort-on-property-write.js, upManager)``
