### ISSUE TITLE
gostream.nu

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5921]
### URL(s) where the issue occurs
`https://gostream.nu/film/stranger-things-season-3-2019-1080p/watching.html`

### Describe the issue

popup ads

### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.20

### Settings

- uBO's default settings

**Comment by mapx-** [comment]
I cannot reproduce the issue

**Comment by ghajini** [comment]
Strange I got sometimes my av alert of blocking phishing site
Now also not reproducing....
