### ISSUE TITLE
appandroider.com fake Google reCaptcha site

### ISSUE THREAD

**Issue by lyndmi** [uBlockOrigin/uAssets#5923]
### URL(s) where the issue occurs

http://appandroider.com/tai-file.php?id=Y29tLmd0YS5uc2xtMi1bdjEuMTQuMi4zXS1NZW51LU1vZF0tU2lnbmVkLmFwaw==
http://appandroider.com/download.php?id=Y29tLmJpZ3Nob3RnYW1lcy5sZWdlbmRhcnlJdGVtX21vZF9zaWduZWQuYXBr

### Describe the issue

fake Google reCaptcha. If you click on it, it will require you to use surveys which are scam

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24647715/60729358-c7304c80-9f42-11e9-9318-6a057a4ad350.png)

### Versions

- Browser/version: Opera Version:62.0.3331.18
- uBlock Origin version: uBlock Origin 1.20.0

### Settings

- Default

### Notes
Request for blocking the domain

Why? Because the following sites:
https://gamemod.pro/mod-request/
http://taigameandroid.asia/

If you click any download links (gamemod.pro: only in mod request section), you will arrive at appandroider (URL(s) where the issue occurs) that you need to click on fake Google reCaptcha which contains survey scam

Highly recommended to block the domain to avoid anyone being tricked and scammed by fake Google reCaptcha.

**Comment by ealgase** [comment]
There are thousands of these fake survey/scam sites.

**Comment by krystian3w** [comment]
OK, I block for Polish Peoples.

**Comment by dumbusernameidk** [comment]
pretty sure this wont be fixed seeing as these sites are used for scamming/pushing junkware.

**Comment by krystian3w** [comment]
@mapx- / @okiehsch 

```
gamemod.pro,taigameandroid.asia##[href*="//appandroider.com]
||appandroider.com^
```

**Comment by krystian3w** [comment]
@mapx- / @okiehsch 

```
gamemod.pro,taigameandroid.asia##[href*="//appandroider.com"]
||appandroider.com^
```

**Comment by ealgase** [comment]
If we're going to block all these fake sites, we'll have a lot of work on our hands.  Not saying whether we should or shouldn't, but this is a bigger issue than just one site.

**Comment by krystian3w** [comment]
So steal records from Google Badware and merge via script into "Badware risk".

**Comment by ealgase** [comment]
Google Badware doesn't block most of these sites.  You'd have to block the "free VBucks" sites, the "watch TV now" sites, etc.

**Comment by krystian3w** [comment]
@lyndmi can you send pictures with fake buttons on `gamemod.pro,taigameandroid.asia`

Maybe AdGuard Base / Anti tracking (spyware) block this?
