### ISSUE TITLE
Fmovies related

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5926]
### URL(s) where the issue occurs

`https://01fmovies.com/tv-series/the-handmaids-tale-season-3/0U47CIiq/UYLx8Q8A-watch-online-free.html`

`https://www1.fmovies.mx/movies/spider-man-far-from-home-2372/`

`https://thefmovies.me/series/love-island/`

`https://5movies.cloud/film/crown-and-anchor-28910/watching.html?ep=28910_1_1`

`https://ww4.fmovieson.com/movies/red-joan-2019-free-1/?watch-token=JJSUGIpUwBJbjF23`

`https://fmovie.info/watch-free/chase/3AZDY`

`https://fmovies123.cc/movies/aladdin/`

`https://5movies.live/the-nightshifter-2018-watch-online-free/`
### Describe the issue

1. Preroll/Midroll ads 

`https://01fmovies.com/tv-series/the-handmaids-tale-season-3/0U47CIiq/UYLx8Q8A-watch-online-free.html`

2. Shady xhr's 

//`https://www1.fmovies.mx/movies/spider-man-far-from-home-2372/`

3.popup ads 
//`https://thefmovies.me/series/love-island/`

//`https://5movies.cloud/film/crown-and-anchor-28910/watching.html?ep=28910_1_1`

//`https://fmovie.info/watch-free/chase/3AZDY`

//`https://ww4.fmovieson.com/movies/red-joan-2019-free-1/?watch-token=JJSUGIpUwBJbjF23`

//`https://fmovies123.cc/movies/aladdin/`

//`https://5movies.live/the-nightshifter-2018-watch-online-free/`
### Versions

- Browser/version: firefox android 67
- uBlock Origin version: 1.20

### Settings

- uBO's default settings

**Comment by dumbusernameidk** [comment]
`5movies.live`:
 
`||pushqwer.com^`

`||oodraune.com^`

`5movies.live##+js(abort-current-inline-script.js, Math, zfgloaded)`

`fmovies123.cc`:

`fmovies123.cc##+js(abort-current-inline-script.js, Math.sin, vocabulary)`

`fmovieson.com`:
`||fmovieson.com/sw.js$script,1p`
`fmovieson.com##[href^="https://bit.ly/"]`

`fmovie.info`:
`fmovie.info##+js(abort-current-inline-script.js, Math, zfgloaded)`

`5movies.cloud`:
`5movies.cloud##+js(abort-current-inline-script.js, Math, zfgloaded)`

`stream365.live###overlay-ads`

`01movies.com`:
`||01fmovies.com/mmmasdfl-asd$xhr,1p`

I can't get rid of the floating gif images a lot of stuff on this site is using randomized class names.

`fmovies.mx`:
`fmovies.mx##+js(abort-on-property-read.js, XMLHttpRequest)`

I tried the usual `##+js(abort-current-inline-script.js, Math.sin, vocabulary)` filter but it doesn't work for me for some reason.

**Comment by okiehsch** [comment]
> Preroll/Midroll ads
https://01fmovies.com/tv-series/the-handmaids-tale-season-3/0U47CIiq/UYLx8Q8A-watch-online-free.html

The loadshare stream does not work on my end.
Does
`||loadshare.org/custom/$media,redirect=noopmp4-1s,domain=01fmovies.com`
work for you?

**Comment by okiehsch** [comment]
> fmovies.mx:
fmovies.mx##+js(abort-on-property-read.js, XMLHttpRequest)
I tried the usual ##+js(abort-current-inline-script.js, Math.sin, vocabulary) filter but it doesn't work for me for some reason.

`fmovies.mx##+js(abort-on-property-read.js, XMLHttpRequest)` breaks the video in the middle of the site.
The usual filter does not work because of a race condition. There is no way to prevent the script from running using Chromium/Chrome.
`*$xhr,3p,domain=fmovies.mx`
is probably the best fix.

**Comment by dumbusernameidk** [comment]
yes the loadshare filter works although there's still the annoying floating images with randomized classes.

**Comment by okiehsch** [comment]
> although there's still the annoying floating images with randomized classes.

You mean this?
![image](https://user-images.githubusercontent.com/16838044/60761631-c4ba1980-a04c-11e9-8290-db515ccdc0f5.png)

**Comment by dumbusernameidk** [comment]
yeah there's a few of them.

**Comment by okiehsch** [comment]
Does
````
01fmovies.com##+js(addEventListener-defuser.js, DOMContentLoaded, checkVPN)
01fmovies.com##[src^="/addons/"]
````
work for you?

**Comment by dumbusernameidk** [comment]
yeah that works though doesn't kill the one on the video player labeled "interferes with ads".

**Comment by okiehsch** [comment]
I only see 

![Unbenannt](https://user-images.githubusercontent.com/16838044/60761762-f7b1dc80-a04f-11e9-9628-db614fcd93c1.PNG)

on my end.

**Comment by dumbusernameidk** [comment]
![image](https://user-images.githubusercontent.com/25139338/60761778-16977b00-a01e-11e9-952f-13094b400995.png)

Hm must be different for everyone I guess.

**Comment by okiehsch** [comment]
`01fmovies.com##.jw-logo`

**Comment by dumbusernameidk** [comment]
yep that's what i used but wasn't sure if it would block something else on the player elsewhere on the site.

**Comment by okiehsch** [comment]
If it does I can remove it but I don't think so.

**Comment by okiehsch** [comment]
And thanks for the help by the way.

**Comment by dumbusernameidk** [comment]
No problem.

**Comment by ghajini** [comment]
By the way this commit https://github.com/uBlockOrigin/uAssets/commit/a4456e5be0a31fc5eee0fbd105fee62f336362d4
Has bring back popup ads on `fmovie.cc`
Already  previous report here https://github.com/uBlockOrigin/uAssets/issues/3613#issuecomment-508214941

**Comment by okiehsch** [comment]
That was a typo, I intended to add
````
fmovie.*##+js(abort-current-inline-script.js, Math, zfgloaded)
fmovie.*##+js(abort-on-property-write.js, _pop)
````

**Comment by ghajini** [comment]
Yeah pretty confusion between changing site names

**Comment by ghajini** [comment]
Also for this
https://github.com/uBlockOrigin/uAssets/issues/5926#issuecomment-508955155

||01fmovies.com/mmmasdfl-asd$xmlhttprequest,first-party
Is sufficient rather than scriptlet filter....
Difference is in scriptlet filter I have to wait 2s
Above filter is strictly blocks that commercial

**Comment by ghajini** [comment]
Popups
`https://thefmovies.me/episode/love-island-season-5-episode-1`

**Comment by mapx-** [comment]
fixed

**Comment by ghajini** [comment]
`https://www.fmovies.fun/watch/?spies-in-disguise`

Popup ads when clicking play, changing between players

**Comment by JobcenterTycoon** [comment]
For what are the `[href="/user/profile/premium-membership"]` filter? Its just a annoyance?

**Comment by mapx-** [comment]
After 3 years .. it's difficult to say something about it

**Comment by JobcenterTycoon** [comment]
Example: `https://ww1.01fmovies.com/film/avengers-endgame/oyu1VRMf-watch-online-free.html` the filter hiding the "BUY PREMIUM" button.

<img width="645" alt="screenshot" src="https://github.com/uBlockOrigin/uAssets/assets/48647394/707ce470-3ebd-432b-b907-acb8402cceb5">

**Comment by mapx-** [comment]
We should remove it
