### ISSUE TITLE
oplata.kykyryza doesnt work

### ISSUE THREAD

**Issue by 2423047205** [uBlockOrigin/uAssets#5927]
### URL(s) where the issue occurs
`https://oplata.kykyryza.ru/`
`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue
endless loading site
[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions
firefox 56, ubo 1.20, uBlock filters – Privacy​​​​​
- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes
without subscription uBlock filters – Privacy​​​​​ site is loading normally
[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by dumbusernameidk** [comment]
works for me on chrome + default filters.

**Comment by okiehsch** [comment]
Works fine with  Firefox, you use an outdated and unsupported version for which no filters will be added to `uAssets`.
You can try to allow the google-analytics script.
`@@||google-analytics.com/analytics.js$script,domain=oplata.kykyryza.ru`
