### ISSUE TITLE
autotracer.org

### ISSUE THREAD

**Issue by Hrxn** [uBlockOrigin/uAssets#5928]
### URL(s) where the issue occurs

`https://www.autotracer.org/`

### Describe the issue

Huge banner on the right side (appears with slight delay, consistently).

### Versions

- Browser/version: 75.0.3770.100 (64-bit) (Latest stable)
- uBlock Origin version: 1.20.0

### Settings

- All default settings
\+ EasyList DE

**Comment by gorhill** [comment]
That is at most self-promotion.

**Comment by Hrxn** [comment]
Are we seeing the same thing?

![1](https://user-images.githubusercontent.com/12064918/60770062-435b9900-a0d7-11e9-82b2-22ac80ead72b.png)

**Comment by gorhill** [comment]
Now I am seeing what is your screenshot, earlier I got a banner seen below, I had to reload a couple of times before I could get it back:

![a](https://user-images.githubusercontent.com/585534/60770217-abde5200-a0a6-11e9-9df1-d350d2264b08.png)

How about:

    ||autotracer.org/cnc/*&p=rightcol$xhr,1p

**Comment by Hrxn** [comment]
Seems to work for me, thanks.
