### ISSUE TITLE
onlystream.tv

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5929]
### URL(s) where issue occurs

`https://onlystream.tv/vjmyaxpwluo6`

### Describe the issue

Popups/popunders

### Versions

- Browser/version: firefox android 67
- uBlock Origin version: 1.20

### Settings

-uBO's default settings

**Comment by ghajini** [comment]
Clicking on `back /forward` button also results in popups/popunders🙄

**Comment by JobcenterTycoon** [comment]
The filter `onlystream.tv##+js(abort-on-property-read.js, open)` works for me
