### ISSUE TITLE
1fichier anti-anti-adblock

### ISSUE THREAD

**Issue by Mattwo** [uBlockOrigin/uAssets#5931]
### URL(s) where the issue occurs

`https://1fichier.com`

### Describe the issue

Can't download anything on this site because I have ablock enabled.
### Screenshot(s)

On download pages: https://i.gyazo.com/ba2ab0fa70a6ac505f0364e290407eb0.png
When hitting download: https://i.gyazo.com/60c6c73b67912b8e7e92f404efc9f2bd.png

### Versions

- Browser/version: Firefox Quantum 67.0.4 (64-bit)
- uBlock Origin version: uBlock Origin v1.20.0

### Settings

https://i.gyazo.com/a3007d8eb0eefc6768775f026667da7a.png

### Notes

https://i.gyazo.com/d24d525401cd593647d5d07cfb7287b0.png

**Comment by ghajini** [comment]
This is just stupid website, just leave it....
`https://github.com/uBlockOrigin/uAssets/issues/4614`
`https://github.com/AdguardTeam/AdguardFilters/issues/27628`

**Comment by ghajini** [comment]
Link to reproduce=
`https://1fichier.com/?5zn48fd5pxk534rfnlam`

**Comment by Mattwo** [comment]
Looking at those threads I discovered the problem was DNT was enabled. Go ahead and close this.
