### ISSUE TITLE
Blocking services on www.aireuropa.com

### ISSUE THREAD

**Issue by JoaquinAEA** [uBlockOrigin/uAssets#5933]
### URL(s) where the issue occurs

The problem occurs on: www.aireuropa.com

### Describe the issue

The uBlockOrigin extension is blockin a lot of services on our web site. 

### Screenshot(s)

![pantallazo1](https://user-images.githubusercontent.com/52574315/60789041-68dfb580-a15e-11e9-9794-d7f56db35e2c.png)

![pantallazo2](https://user-images.githubusercontent.com/52574315/60789110-890f7480-a15e-11e9-87aa-a9c21f3dce5d.png)

### Versions

- Browser/version: Chrome Versión 70.0.3538.110 (Build oficial) (32 bits)
- uBlock Origin version: 1.20.0

**Comment by okiehsch** [comment]
What is broken? How do I reproduce any breakage?

**Comment by uBlock-user** [comment]
Run the logger, find out what's broken and which filterlist is responsible for that breakage and report that here.

**Comment by okiehsch** [comment]
Closing due to lack of feedback.
