### ISSUE TITLE
Add womenarestupid.site document filter (spam/malware)

### ISSUE THREAD

**Issue by SoniEx2** [uBlockOrigin/uAssets#5934]
### URL(s) where the issue occurs

`womenarestupid.site`

### Describe the issue

Spam/malware/harassment campaign.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Firefox 67.0.4
- uBlock Origin version: 1.20.0

### Settings

- N/A

### Notes

Spam/malware/harassment campaign.

**Comment by okiehsch** [comment]
I don't see any malware.
I guess you want me to block the site because the content shows an antiquated, offensive world view.
`uAssets` filter lists are meant for issues about  ads, trackers, etc.
If you want to block all websites with offending content you are free to start a new filter list.

**Comment by SoniEx2** [comment]
what part of "spam" do you not understand?

**Comment by okiehsch** [comment]
Define spam.

**Comment by SoniEx2** [comment]
"spam" is when someone keeps constantly linking that thing addressed to ppl unprompted in some sort of communications medium. as has been happening here.

**Comment by okiehsch** [comment]
>  is when someone keeps constantly linking that thing addressed to ppl unprompted in some sort of communications medium. as has been happening here.

So someone has constantly send you links to `womenarestupid.site`?

**Comment by halcy** [comment]
I've been asked to chime in: This site has, in fact, been aggressively promoted via spam bots on the so-called "fediverse" federated social network, on my small (~80 daily active users) instance alone, I've easily had to suspend 20 accounts so far that all do nothing but post  the same message linking to this website. I am not sure if blocking sites that are massively promoted via spam is in scope for ublock origin, but if it is, this website should qualify.

**Comment by okiehsch** [comment]
Thanks for the clarification, @gorhill what do you think?

**Comment by pianycist** [comment]
https://mastodon.cloud/@AllYourBasesBelongToUsNow/with_replies


http://archive.is/tQB5V

the spam bot replies to unrelated posts with this same message. there have been others, but the accounts are being deleted before administrators can take action.

**Comment by gorhill** [comment]
This should be reported to [Spam404](https://www.spam404.com/report.html).

If the site itself does not contain badware, there is not place for it in any of the maintained filter lists here.
