### ISSUE TITLE
telegraaf.nl

### ISSUE THREAD

**Issue by PoRtvine** [uBlockOrigin/uAssets#5935]
### URL(s) where the issue occurs

`telegraaf.nl` redirect to =>

`https://tmgonlinemedia.nl/consent/consent/?return=https%3A%2F%2Fwww.telegraaf.nl%2F&clienttime=1562650412542&version=5&guid=1d0cde76-7120-d4f3-a76f-5c4dc48a7f92&detect=true`

### Describe the issue

Cookies, can this be circumvented?

### Screenshot(s)

![2019-07-09_084102](https://user-images.githubusercontent.com/28482376/60862111-4cf31700-a225-11e9-95af-1234bf03e964.png)

### Versions

- Browser/version: [Opera|Beta]
- uBlock Origin version: [1.20.3rc1]

### Settings

![2019-07-09_084301](https://user-images.githubusercontent.com/28482376/60862211-93487600-a225-11e9-9811-29c9bc876a33.png)

**Comment by okiehsch** [comment]
`telegraaf.nl##+js(abort-on-property-write.js, TMG)`
This could break some functionality, videos, comments, etc. 
I don't speak dutch, if you don't see any breakage I can add the filter to the annoyance list.

**Comment by okiehsch** [comment]
Actually this is already fixed in `AdGuard Annoyances`, so no filter will be added to `uBO-annoyances`.

You can enable `AdGuard Annoyances` or add 
`telegraaf.nl##+js(abort-on-property-write.js, TMG)`
to your filter list.
