### ISSUE TITLE
gdtot.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5937]
### URL(s) where the issue occurs

`https://gdtot.com/TXeVWeS/bpdvd-40mb-desiremovies-pro-1-mkv`

### Describe the issue
popup ads

### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.20

### Settings

-  uBO's default settings

**Comment by gorhill** [comment]
How about:

    gdtot.com##+js(addEventListener-defuser.js, DOMContentLoaded)

**Comment by ghajini** [comment]
popup are avoided....in next page unwanted xhr's requests
![Screenshot (43)](https://user-images.githubusercontent.com/20338483/60918226-6f7e4200-a2b0-11e9-9769-768e63bec5f9.png)

**Comment by gorhill** [comment]
I an unable to reproduce these network requests.

**Comment by JobcenterTycoon** [comment]
i can reproduce. 

Browser: Firefox 67.0.4
uBlock Origin version: v1.20.0
Settings: 

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3374683/Settings.txt)

**Comment by okiehsch** [comment]
I can reproduce the xhr-requests with `gdtot.com##+js(addEventListener-defuser.js, DOMContentLoaded)`
in place after clicking "Click gere to unlock the video".

**Comment by okiehsch** [comment]
Seems to be a race conditon, the same happens if I add
`gdtot.com##+js(abort-current-inline-script.js, Math.sin, vocabulary)`

**Comment by gorhill** [comment]
I think your solution is better, `DOMContentLoaded` seems to be used also for legit purpose in there -- I need to work more of filters to catch up with the usual solutions.

Question: isn't `*$xhr,3p,domain=gdtot.com` good enough for both Firefox and Chromium?

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/379b9337cd5facaca7e6f305fe9f65b8c124e8d6

I added
gdtot.com##^script:has-text(vocabulary)
!#if env_chromium
*$xhr,3p,domain=gdtot.com
!#endif

**Comment by gorhill** [comment]
Yes, that's why I ask why not use `*$xhr,3p,domain=gdtot.com` for both browsers instead of having one filter specific to each? From a filter maintenance perspective, a single filter which work on both sounds better?

**Comment by okiehsch** [comment]
See my edit above ;)

**Comment by ghajini** [comment]
`https://gdtot.com/aHQqlmA/katmovie-club-marjavan-2019-hindi-predvd-70mb-x264-ac-mkv`

Update `gdtot.com##+js(abort-current-inline-script.js, Object.defineProperty, vocabulary)`

**Comment by ghajini** [comment]
URL= 
`new.gdtot.com/file/1304227187`

`https://gdtot.com/TXeVWeS/bpdvd-40mb-desiremovies-pro-1-mkv`

Popup ads

update scriptlet filter to 

`gdtot.com##+js(acis, String.fromCharCode, btoa)`
