### ISSUE TITLE
tusfiles.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5938]
### URL(s) where the issue occurs

`https://tusfiles.com/7ngjbfvysq0k`

### Describe the issue

unwanted 3rd party xhr's

### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.20

### Settings

-  uBO's default settings

**Comment by JobcenterTycoon** [comment]
The best option are for me to block this sites by default. The xhr issues get more and more.

`||6868bbe42af8e518.com^`
`||aa53df329975c325.com^`
`||41df76c67812005c.com^`
`||ae25079147984d4d.com^`
`||a1a5ab31bcd1bc68.com^`
`||e6081b73afec581f.com^`
`||fd9523b31ff93b5c.com^`
`||e7393e33565ce805.com^`
`||b60228e270e363f6.com^`
`||47f624b2e6c6072e.com^`
`||564d28256cddaeba.com^`
`||b13481647cf775c5.com^`
`||e6081b73afec581f.com^`
`||2d7bd9e6eb370143.com^`

i hope this list is complete

**Comment by ghajini** [comment]
no they are random names...
on some times they remain dormant but on many sites they are responsible for popup ads

**Comment by JobcenterTycoon** [comment]
these sites are blacklisted in the AdGuard Base List, uBlock only block a few of this.

**Comment by gorhill** [comment]
Again, if I add

    tusfiles.com##+js(addEventListener-defuser.js, DOMContentLoaded)

I don't get the random fetches. I do get them if I do not have the above filter.

**Comment by okiehsch** [comment]
> `tusfiles.com##+js(addEventListener-defuser.js, DOMContentLoaded)`

That works on my end too.

We use 
`example.com##+js(abort-current-inline-script.js, Math.sin, vocabulary)`
to abort the offending inline-script for those random xhr-fetches.

**Comment by gorhill** [comment]
@okiehsch Ok, feel free to add the filter.

**Comment by okiehsch** [comment]
The issue is fixed with your filter no need to add another.

**Comment by ghajini** [comment]
Popup ads

`tusfiles.com/zg2jm4m6frka`
`tusfiles.com/zh9gahwghgai`
