### ISSUE TITLE
uploadfiles.io

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#594]
### URL(s) where the issue occurs

`https://uploadfiles.io/cqelu`

### Describe the issue

Adblocker Detected 
Please consider whitelisting Uploadfiles. Our service relies on ads, we promise you will never find popups or intrusive ads here.

`##.ad-blocked`

**Comment by okiehsch** [comment]
I would classify this as an annoyance, I can still download files from `uploadfiles.io`,
Example link: `https://uploadfiles.io/b2acj`, are you restricted in your usage of that site in any way
other than being reminded that you use an adblocker?

**Comment by terrorist96** [comment]
No other restrictions. Just the notice.

**Comment by okiehsch** [comment]
Then this is just an annoyance and no fix will be added to `uBO-filters` for now
https://github.com/uBlockOrigin/uAssets/issues/322#issuecomment-287567598
