### ISSUE TITLE
webcamsdolls.com [Anti-Adblock][NSFW]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5940]
URL(s) where the issue occurs

`http://webcamsdolls.com/index/lilneko-trahaet-sebya-palchikami.php`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 75 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.20.0

Settings

Default

**Comment by KiLL4FuNK** [comment]
PLAY VIDEO

**Comment by JobcenterTycoon** [comment]
@okiehsch there are unblocked ads at bottom of the video and

`bxjch.top`
`mwcvu.com`
`kpqnj.top`

looks like trash sites (tracking)
