### ISSUE TITLE
Australia Post: Postage Calculator options menu does not open

### ISSUE THREAD

**Issue by numbermaniac** [uBlockOrigin/uAssets#5943]
### URL(s) where the issue occurs

`https://auspost.com.au/parcels-mail/calculate-postage-delivery-times/#/option/domestic/3000/2000`

### Describe the issue

With uBlock Origin activated, the "Features & Options" dropdown (next to "Express Post" or "Parcel Post") does not work. Clicking on it does nothing on the page, but it causes a JavaScript error in the console. If I turn off uBlock Origin and reload the page, the dropdown appears correctly.

### Screenshot(s)

![Screen Shot 2019-07-10](https://user-images.githubusercontent.com/5206120/60936107-5658ae00-a30f-11e9-9a2a-8a895bc887be.png)

### Versions

- Browser/version: Firefox 67.0.4, macOS 10.14.4
- uBlock Origin version: 1.20.0

### Settings

- No changes that I can remember

### Notes
JavaScript error mentioned earlier:
```
angular.js:12416:23
Error: $window._satellite is undefined
self.trackFeatureOptionClick@https://auspost.com.au/parcels-mail/calculate-postage-delivery-times/scripts/app.js:1:366499
controller/$scope.showHideSection@https://auspost.com.au/parcels-mail/calculate-postage-delivery-times/scripts/app.js:1:417674
fn@https://auspost.com.au/parcels-mail/calculate-postage-delivery-times/scripts/app.js line 1 > Function:4:405
callback@https://auspost.com.au/parcels-mail/calculate-postage-delivery-times/scripts/app.js:1:232873
$eval@https://auspost.com.au/parcels-mail/calculate-postage-delivery-times/scripts/app.js:1:131598
$apply@https://auspost.com.au/parcels-mail/calculate-postage-delivery-times/scripts/app.js:1:131929
compile/</<@https://auspost.com.au/parcels-mail/calculate-postage-delivery-times/scripts/app.js:1:232980
eventHandler@https://auspost.com.au/parcels-mail/calculate-postage-delivery-times/scripts/app.js:1:27942
```

**Comment by okiehsch** [comment]
Should work after updating your `uBO-unbreak` list.
