### ISSUE TITLE
gamefront.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#5946]
`https://www.gamefront.com/files/autorun-eater-2-6/download`

1) Ads - EasyList?

---

2. speed up download "Games"?

**Comment by llacb47** [comment]
1. Can't reproduce ads.

2. This filter works to speed up the download. 
`www.gamefront.com##+js(nano-setTimeout-booster.js,window.location.href,10000)`

**Comment by krystian3w** [comment]
![Screenshot_2019-07-11 Autorun Eater 2 6 - Tools Utilities Mods, Maps, Patches News - GameFront](https://user-images.githubusercontent.com/35370833/61081191-f2c1a400-a426-11e9-850d-9fff647e0ee7.png)

`##.ad__desk`

@khrin / @ryanbr

**Comment by lain566** [comment]
@krystian3w Try these
```
gamefront.com##+js(abort-current-inline-script.js, $, AdBlock)
gamefront.com##+js(nano-setTimeout-booster.js, , 10000)
```

**Comment by krystian3w** [comment]
Report this ad into EasyList "Anti-cv"? Or this is detection anti-adblock?

**Comment by okiehsch** [comment]
No it is ad-reinsertion.

**Comment by krystian3w** [comment]
I reported anyway.
