### ISSUE TITLE
https://www.beermoneyforum.com/

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#5947]
### URL(s) where the issue occurs

`https://www.beermoneyforum.com/`

### Describe the issue

Excessive ads

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/61103931-24943400-a442-11e9-8a79-fc2538f53706.png)

**Comment by okiehsch** [comment]
````
beermoneyforum.com##.notice-content
beermoneyforum.com##.samBannerUnit
````

**Comment by terrorist96** [comment]
@ryanbr
