### ISSUE TITLE
uBlockOrigin causing video controls to disappear on Twitch 

### ISSUE THREAD

**Issue by xellosmetallum** [uBlockOrigin/uAssets#5949]
### URL(s) where the issue occurs

https://twitch.tv/richard_hammer

### Describe the issue

When ublock origin is enabled for the site and you go into theater mode on the video or full screen the video controls disappear and you have to refresh the page to get them back.

### Screenshot(s)

https://imgur.com/WLX9HZ7

### Versions

- Browser/version: Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.20.0

### Settings

- Using Default settings.

### Notes

I have disabled all addons in chrome and one at a time enabled them and tried to go into theater mode, It worked for every single extention i have but when i enabled ublock it caused the issue of the controls to disappear.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/61121206-eb3de180-a49e-11e9-8137-9f8d61cdbeee.png)

I can't reproduce.

**Comment by uBlock-user** [comment]
Run the logger and start disabling any cosmetic filters(reload on each change) until the controls appears again.

**Comment by xellosmetallum** [comment]
Well for some reason it has started to work again with no change from me. Think it fixed itself.
