### ISSUE TITLE
tvporn.cc [NSFW]

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#5951]
### Describe the issue

[clicking anywhere opens a popup in a new tab.]

### Versions

- Browser/version: [Chrome v75]
- uBlock Origin version: [1.20.0]

### Settings

- [default]

**Comment by dumbusernameidk** [comment]
Found a few clones of the site above `peetube.cc`, `onlinexxx.cc`, `gonzoporn.cc`, `bdsmporn.cc`. All have the same popup issue.

**Comment by okiehsch** [comment]
`peetube.cc` and `bdsmporn.cc` are slightly different.
They look like clones of https://github.com/uBlockOrigin/uAssets/issues/4646

**Comment by dumbusernameidk** [comment]
yeah i mean't more so video hosting clones sorry. but they all exhibit the same popup behavior.

**Comment by okiehsch** [comment]
I added all of them, thanks.

**Comment by dumbusernameidk** [comment]
@okiehsch found a couple more sites for you to add `streamextreme.cc` `freepornstream.cc`.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/52a9f7f74a41735f75d47e4ae65868c8ee858262

**Comment by dumbusernameidk** [comment]
another one `porntube18.cc`.
