### ISSUE TITLE
merkur.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5952]
### URL(s) where the issue occurs

`https://www.merkur.de/leben/karriere/absagen-ihre-bewerbungen-kassiert-eine-frau-dieses-detail-weglaesst-zr-9202399.html`

### Describe the issue
Pre Video Ads

### Screenshot(s)

![Unbenannt](https://user-images.githubusercontent.com/48647394/61171560-77bcd280-a579-11e9-9e64-213dee4a0745.PNG)

### Versions

- Browser/version: Firefox 68
- uBlock Origin version: uBlock Origin v1.20.2

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3388759/Settings.txt)

### Notes

Please scroll down to watch the Video. The title is: "Video: So sollten Sie sich nicht bewerben!"

**Comment by lain566** [comment]
I can't reproduce pre-roll ads using a german IP, I can reproduce only if I disable uBlock.

**Comment by JobcenterTycoon** [comment]
Another example: on `https://www.merkur.de/` scroll down, you will see a video with the name "Top Videos" click on the big play button.

**Comment by lain566** [comment]
Does this filter work for you?
`player.glomex.com##+js(abort-on-property-read.js, XDomainRequest)`

**Comment by okiehsch** [comment]
Works for me you can add it and remove the existing `player.glomex.com` filters.

**Comment by JobcenterTycoon** [comment]
@lain566 @okiehsch 
glomex ads are back

**Comment by lain566** [comment]
Does work for you?
`player.glomex.com##+js(set-constant.js, Math.ceil, trueFunc)`

**Comment by okiehsch** [comment]
I get an anti-adblock message with that filter.
For testing purposes
````
https://component-vvs.glomex.com/embed/1/index.html?playerId=excq22d8j45jjyr8&playlistId=v-bgf7mv01k73d
`````
is probably easier than using `merkur.de`.

**Comment by okiehsch** [comment]
`player.glomex.com##+js(set-constant.js, Math.ceil, trueFunc)`
works on my end.

**Comment by lain566** [comment]
I don't get anti adblock message using this filter 
`player.glomex.com##+js(set-constant.js, Math.ceil, trueFunc)`

This filter breaks the player for me
`player.glomex.com##+js(set-constant.js, Math.ceil, noopFunc)`

**Comment by lain566** [comment]
@okiehsch You're right. I did the tests using these filters
```
player.glomex.com##+js(set-constant.js, Math.ceil, trueFunc)
||player-feedback-*.glomex.com/pf/*$xhr
```

**Comment by okiehsch** [comment]
Hm
`player.glomex.com##+js(set-constant.js, Math.ceil, noopFunc)`
does not break the player on my end, but

````
player.glomex.com##+js(set-constant.js, Math.ceil, trueFunc)
||player-feedback-*.glomex.com/pf/*$xhr`
````
works for me too, so let's add those filters.

**Comment by lain566** [comment]
Done.

**Comment by JobcenterTycoon** [comment]
Thanks lain566 and okiehsch. But one more question: When visit this site i get after ~10 seconds a xhr request from a .space domain. Is this tracking?
![siorehgio](https://user-images.githubusercontent.com/48647394/62220935-2736d900-b3b1-11e9-90de-b1e59e64fe02.PNG)

**Comment by JobcenterTycoon** [comment]
Glomex use now a anti adblock
![Unbenannt](https://user-images.githubusercontent.com/48647394/68530804-30b6d200-030c-11ea-9562-9ac3b33a4c8b.PNG)

`https://component-vvs.glomex.com/embed/1/index.html?playerId=excq22d8j45jjyr8&playlistId=v-bgf7mv01k73d`

**Comment by mapx-** [comment]
test these filters
```
*/*$script,redirect-rule=noopjs,domain=player.glomex.com
*/*$xhr,redirect-rule=nooptext,domain=player.glomex.com
player.glomex.com#@#+js(set-constant, Math.ceil, trueFunc)
```

**Comment by JobcenterTycoon** [comment]
Yes it works, thank you

**Comment by lain566** [comment]
@okiehsch easyprivacy decided to completely block the glomex player  https://github.com/easylist/easylist/commit/09c3eea629e2077311b0dea0835d0ffcc96e916f

**Comment by okiehsch** [comment]
Yes, the videos on sites using glomex mentioned here https://github.com/uBlockOrigin/uAssets/issues/5952#issuecomment-511148047 are all broken.
We can badfilter it or add `@@||config-vvs.glomex.com/teaser$script,3p` for now, what do you think?

**Comment by lain566** [comment]
has already been fixed

**Comment by mapx-** [comment]
@lain566 do you want to enter in the slack group (it's where I notified ryan about this issue) ? the invitation link has been posted in our team discussions

**Comment by lain566** [comment]
Ok, when I can I will create an account, I've already seen the invitation link.

**Comment by JobcenterTycoon** [comment]
the glomex videos doesn’t load anymore

**Comment by lain566** [comment]
@mapx- I can reproduce anti-adblock after your commit on gmx https://github.com/uBlockOrigin/uAssets/issues/7508#issuecomment-706657508
`https://www.gmx.net/magazine/unterhaltung/stars/michael-wendler-angst-schlagersaenger-eklat-35162506`

**Comment by mapx-** [comment]
if I add
`||zomap.de^$xmlhttprequest,domain=player.glomex.com,badfilter`

I get no anti adb on gmx but I get video ads

**Comment by mapx-** [comment]
Now on merkur the videos are not blocked but gmx will have video ads

**Comment by lain566** [comment]
Actually, they are not showing ads right now on merkur, that's why you can only reproduce ads on gmx.

<details>

![Captura de pantalla 2020-10-16 235749](https://user-images.githubusercontent.com/27441315/96312225-75aeb280-100b-11eb-8c87-c05ac6363d78.png)
</details>


Adding this, works on my side, but I would have to revert all your changes for glomex.

```
||zomap.de^$media,domain=player.glomex.com,redirect=noopmp3-0.1s,badfilter
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=player.glomex.com,badfilter
@@||player-feedback*.glomex.*^$xhr,domain=player.glomex.com,badfilter
player.glomex.com#@#+js(set, Object.prototype.disableAds, true)

player.glomex.com##+js(set, Object.prototype._getSalesHouseConfigurations, noopFunc)
```

**Comment by mapx-** [comment]
great ! go ahead with your changes
