### ISSUE TITLE
elkhbrelyoumy.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#5962]
URL(s) where the issue occurs

`http://elkhbrelyoumy.com/DuxW`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 75 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.20.0

Settings

Default

**Comment by okiehsch** [comment]
I can't connect.

**Comment by krystian3w** [comment]
For my works and see anti-adblock after Google  recaptcha v2.

>![obraz](https://user-images.githubusercontent.com/35370833/61177308-605e0380-a5d2-11e9-9567-6fb92d88a923.png) |
> --- |

**Comment by okiehsch** [comment]
Does
`elkhbrelyoumy.com##+js(abort-on-property-read.js, app_vars.force_disable_adblock)`
work for you?

**Comment by krystian3w** [comment]
Alert gone; but no see button to next steep after checked  recaptcha (accessibility/connections problems are now on my PC).

**Comment by krystian3w** [comment]
The page is probably not for use today.

> ![obraz](https://user-images.githubusercontent.com/35370833/61177383-6e148880-a5d4-11e9-96fd-e61857739a31.png)

Getting link... is disabled by server overload?

**Comment by okiehsch** [comment]
Well, now  I can connect and the "getting link" button does not work for me too.
The issue is on their side, the button does not work if I disable `uBO`.
