### ISSUE TITLE
NSFW rule34hentai.net

### ISSUE THREAD

**Issue by catshitz** [uBlockOrigin/uAssets#5964]
uBlock filters on nano adblocker causing video player (page)fullscreen button won't response.
eg. https://rule34hentai.net/post/view/353122

**Comment by dimisa-RUAdList** [comment]
Blocked right click on pictures.
`rule34hentai.net##+js(addEventListener-defuser, contextmenu)`

**Comment by dimisa-RUAdList** [comment]
@uBlock-user 
Look at this please
