### ISSUE TITLE
ruegenwalder.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5966]
### URL(s) where the issue occurs

`https://www.ruegenwalder.de`

### Describe the issue

can’t accept cookies because the "cookies Akzeptieren" button is broken. (cookie layer is not correctly blocked)

### Screenshot(s)
With cosmetic filter (broken one)
![Unbenannt](https://user-images.githubusercontent.com/48647394/61185042-96dc6280-a654-11e9-8262-b0edc97896a2.PNG)

without cosmetic filter:
![Unbenannt1](https://user-images.githubusercontent.com/48647394/61185054-b70c2180-a654-11e9-8430-2f81966ad84a.PNG)

### Versions

- Browser/version: Firefox 68.0
- uBlock Origin version: uBlock Origin v1.20.2

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3389996/Settings.txt)

### Notes

the problem filter is `###cookieconsent` by `AdGuard Annoyances` and `Fanboy’s Annoyance List`

**Comment by krystian3w** [comment]
So report into EasyList:
https://github.com/ryanbr/fanboy-adblock/issues/ or
https://github.com/easylist/easylist/issues

 and here https://reports.adguard.com/en/new_issue.html

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/36834

**Comment by krystian3w** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/1097

**Comment by JobcenterTycoon** [comment]
Thanks.
