### ISSUE TITLE
uiz.io [Anti-Adblock]

### ISSUE THREAD

**Issue by Robbie8592** [uBlockOrigin/uAssets#5967]
### URL(s) where the issue occurs

`https://uiz.io/eIQ8`

### Describe the issue

Getting a banner to disable my adblocker

### Screenshot(s)

![image](https://user-images.githubusercontent.com/29841633/61196387-5b658680-a69c-11e9-88ca-bf90e85d2124.png)

### Versions

- Browser/version: Firefox 68.0
- uBlock Origin version: 1.20.2

### Settings

Default Settings

### Notes

None

**Comment by okiehsch** [comment]
Already fixed earlier today. https://github.com/uBlockOrigin/uAssets/commit/d46078e1fab8125f44762245c1a16fca355a7c5f
Update your `uBO-filters` list.

**Comment by JobcenterTycoon** [comment]
i updated the filter lists but the anti adblock message still appear

**Comment by krystian3w** [comment]
Pruge all cache in browser with:

<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + </kbd>Delete</kbd>


and try again update uBO lists.


Or paste to my filters:

---

```
uiz.io#@#+js(abort-on-property-read.js, app_vars.force_disable_adblock)
uiz.io#@#+js(setTimeout-defuser.js, checkAdblockUser)

@@||uiz.io/custom_theme/js/sw.js$script,1p
@@||uiz.io/js/ads.js$script,1p
@@||mc.yandex.ru/metrika/watch.js$script,xhr,domain=uiz.io
```

**Comment by ghajini** [comment]
Firefox android stable 
With all default settings ,Condition worsened....whenever I try to solve captcha box, always popup ads opens and never opens captcha solving
![IMG_20190715_231917](https://user-images.githubusercontent.com/20338483/61237119-42ef7d80-a729-11e9-962a-189a39330312.jpg)

**Comment by JobcenterTycoon** [comment]
> 
> 
> Pruge all cache in browser with:
> 
> Ctrl + Shift + Delete
> 
> and try again update uBO lists.
> 
> Or paste to my filters:
> 
> ```
> uiz.io#@#+js(abort-on-property-read.js, app_vars.force_disable_adblock)
> uiz.io#@#+js(setTimeout-defuser.js, checkAdblockUser)
> 
> @@||uiz.io/custom_theme/js/sw.js$script,1p
> @@||uiz.io/js/ads.js$script,1p
> @@||mc.yandex.ru/metrika/watch.js$script,xhr,domain=uiz.io
> ```

now i know why its because im enabled tracking protection in firefox. Now its works.

**Comment by okiehsch** [comment]
Fixed the popup. https://github.com/uBlockOrigin/uAssets/commit/2f7759bd91b3a0a1682e53d02e02efe7bfd94f4d

**Comment by ghajini** [comment]
Crappy xhr's
`https://uiz.io/ftQTW`

**Comment by krystian3w** [comment]
| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 |  |  | uiz.io | 3 | xhr | `https://66713dbe44.com/` |
| +2 |  |  | uiz.io | 3 | xhr | `https://01ced816b84.com/` |
| +2 |  |  | uiz.io | 3 | xhr | `https://919ba151b6f5.com/` |
| +1 |  |  | uiz.io | 3 | xhr | `https://c26c8951ef23f.com/` |
| +1 |  |  | uiz.io | 3 | xhr | `https://544c27b3f0aae2.com/` |

**Comment by krystian3w** [comment]
But this no block fake flash:

![obraz](https://user-images.githubusercontent.com/35370833/65393962-1d659c80-dd88-11e9-9b2c-6071628cb2f7.png) |
--- |

```
uiz.io##.modal:has-text(Flash)
uiz.io##.modal-backdrop
uiz.io##body:style(overflow: auto !important;)
```

**Comment by okiehsch** [comment]
> But this no block fake flash

The commit by **mapx-** blocks the fake flash modal.
To be specific `uiz.io##+js(acis, $, load)` does it.

**Comment by krystian3w** [comment]
My post was no about scriplet... 🐗.

**Comment by mapx-** [comment]
@krystian3w I told you about **DeepL**, is working for Polish too, use it to have a very good translation, so we'll understand better what you want to tell us

**Comment by llacb47** [comment]
@krystian3w another translator you can try is Yandex `https://translate.yandex.com/translator/Polish-English`

**Comment by krystian3w** [comment]
...

I meant that manual blocking of xhr by the domain did not hide the pop-up.

EOT.
