### ISSUE TITLE
ftopx.com [NSFW]

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5971]
### URL(s) where the issue occurs

`https://ftopx.com`

### Describe the issue

popup

### Versions

- Browser/version: Firefox 68.0
- uBlock Origin version: uBlock Origin v1.20.2

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3399746/Settings.txt)

**Comment by okiehsch** [comment]
Please remember to always mark such sites as NSFW.

**Comment by JobcenterTycoon** [comment]
ok
