### ISSUE TITLE
hardware.info

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5974]
### URL(s) where the issue occurs

`https://nl.hardware.info/`

### Describe the issue

can’t accept cookies because the cookie banner is blocked (cookie banner not correctly blocked)

### Screenshot(s)

With cosmetic filter (broken one):
![fdhjgfjgf](https://user-images.githubusercontent.com/48647394/61342913-3152c680-a84c-11e9-96e9-564be8c2cee6.PNG)

without cosmetic filter:
![reuihtbni8zb](https://user-images.githubusercontent.com/48647394/61342926-3fa0e280-a84c-11e9-9a6c-7b7a852bcac4.PNG)

### Versions

- Browser/version: Firefox 68.0
- uBlock Origin version: uBlock Origin v1.20.2

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3399857/Settings.txt)

### Notes

The problem filter is `nl.hardware.info##body > div:nth-of-type(1) > div` by `uBlock filters – Annoyances `

**Comment by okiehsch** [comment]
Thanks for reporting my badfilter. ;)
