### ISSUE TITLE
news-tech.xyz

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#5975]
### URL(s) where the issue occurs

`[https://news-tech.xyz/links/review/drive.google.com?a=ctO3]`

### Describe the issue

[Force to turn off adblocker]

### Screenshot(s)

Same like this: https://github.com/uBlockOrigin/uAssets/issues/5860

### Versions
Rest same like this https://github.com/uBlockOrigin/uAssets/issues/5945

**Comment by JobcenterTycoon** [comment]
same filter `news-tech.xyz##+js(addEventListener-defuser.js, load, 2000)`

**Comment by ghajini** [comment]
Simple generichide exception filter should do the job

**Comment by uBlock-user** [comment]
```
@@||news-tech.xyz^$generichide
news-tech.xyz##.adsbygoogle
```

**Comment by JobcenterTycoon** [comment]
> 
> 
> Simple `generichide exception` filter should do the job

it doesn’t work for this site

**Comment by uBlock-user** [comment]
@JobcenterTycoon It does, see my post above. The trap checks for generic elements being hidden or not.

**Comment by JobcenterTycoon** [comment]
you need to unblock a fake ad domain. `/ads160.`
![dummy](https://user-images.githubusercontent.com/48647394/61400473-a23bc200-a8d0-11e9-9433-31234a5c5f38.PNG)

`@@||news-tech.xyz^$generichide`

`news-tech.xyz##.adsbygoogle`

`@@||news-tech.xyz/safelinkudomain.png#/ads160./adstracking./adv/ads/ad/advertising-/carsadtaggenerator.js/omb-ad-/recommendations/ad./rightnavadsanswer./webadverts/ad_feast_ad.`

**Comment by uBlock-user** [comment]
Not on my end, those filters work fine. Yours must be from the cache, do a full page reload via CTRL + R.

**Comment by okiehsch** [comment]
`generichide` will not work with Firefox it never has with that particuar anti-adblock script, see https://github.com/uBlockOrigin/uAssets/issues/4808 https://github.com/uBlockOrigin/uAssets/issues/5481
It works fine with Chromium/Chrome.
