### ISSUE TITLE
youku.com [preroll video ads] 

### ISSUE THREAD

**Issue by discusssth** [uBlockOrigin/uAssets#5976]
`https://v.youku.com/v_show/id_XNDIyMjQ5Njc5Mg==.html?spm=a2ha1.12675304.m_2556_c_8261.d_2&s=a4de6bdc5675415ea280&scm=20140719.manual.2556.show_a4de6bdc5675415ea280`

![20190718100652](https://user-images.githubusercontent.com/45059308/61423862-f6cc5500-a943-11e9-9c69-a61900b9906d.jpg)

If you can't reproduce the problem, maybe you need a VPN in China.

**Comment by discusssth** [comment]
i can provide VPN  ....
just leave your email

**Comment by lain566** [comment]
@discusssth Do these filters work for you?
```
||cibntv.net^$media,domain=youku.com
youku.com##+js(nano-setTimeout-booster.js, , ,0)
youku.com##.h5-ext-layer
```

**Comment by llacb47** [comment]
Can't test because I get a message about cookies.

**Comment by discusssth** [comment]
@lain566     works for me, thank you very much
