### ISSUE TITLE
neowin.net

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5979]
### URL(s) where the issue occurs

`https://www.neowin.net/`

### Describe the issue

Anti-Adblock (only annoyance)

### Screenshot(s)

![Unbenannt](https://user-images.githubusercontent.com/48647394/61562358-7441b380-aa71-11e9-9859-d826bc86434d.PNG)

### Versions

- Browser/version: Firerfox 68.0.1
- uBlock Origin version: uBlock Origin v1.20.2

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3412561/Settings.txt)

### Notes
Issue from https://github.com/ryanbr/fanboy-adblock/issues/1106#issue-470468254

**Comment by uBlock-user** [comment]
`neowin.net##+js(set-constant, _sp_.mms.startMsg, null)`

**Comment by okiehsch** [comment]
Fixed in annoyances.
