### ISSUE TITLE
electrek.co

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#598]
### URL(s) where the issue occurs

`https://electrek.co/2017/06/10/tesla-autopilot-update-smooth-autopark/`

### Describe the issue

Solar roof ads at top and middle of article.

uBO specific rule:
`electrek.co##script:inject(abort-on-property-read.js, canRunAds)`

**Comment by SMed79** [comment]
`9to5google.com,9to5mac.com,9to5toys.com,electrek.co##script:inject(abort-on-property-read.js, canRunAds)`
