### ISSUE TITLE
sdi-tool.org

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#5984]
(Note that the problem is already long since fixed in *AdGuard Mobile Ads*, which is unfortunately not a default list for most users, so I'm submitting this here as well. As this issue is about malware, the fact that it's also been seemingly accidentally fixed in EasyPrivacy doesn't count.)

### URL(s) where the issue occurs

`https://sdi-tool.org/download/`

### Describe the issue

For puzzling reasons, the download link for *SDI Lite* seems to change into one for *Driverpack Online* after about a second, the latter of which is considered by any sane anti-malware tool (as well as many angry ex-users of SDI) to be malware full of backdoors and whatnot. Even more puzzlingly, blocking `||google-analytics.com^` prevents the links from changing, thus displaying the correct (for end-users) links.

### Screenshot(s)

Without `||google-analytics.com^`:
![image](https://user-images.githubusercontent.com/22780683/61579908-c2a39080-ab0b-11e9-9914-04a8ac8ed2a0.png)

With `||google-analytics.com^`:
![image](https://user-images.githubusercontent.com/22780683/61579929-f1ba0200-ab0b-11e9-8e42-70160a5b8968.png)

### Versions

- Browser/version: Chrome 75.0.3770.142 64-bit for Windows
- uBlock Origin version: Nano Adblocker 1.0.0.121 + Nano Defender 15.0.0.155

### Settings

![image](https://user-images.githubusercontent.com/22780683/61579948-3f366f00-ab0c-11e9-914a-2e7debf2a05d.png)

### Notes

It wasn't until yesterday, while helping someone set up a laptop (thus I was thinking it was safe to use Edge without an adblocker to try to download SDI), that I realised why nerds, enthusiasts, and SDI Origin's creator have all been livid since 2016 about `SDI Tool`'s practices. Now I understand them.

My suggested fix: `||google-analytics.com^$domain=sdi-tool.org`

**Comment by krystian3w** [comment]
Website also block F5 button no Firefox (sic!).

**Comment by krystian3w** [comment]
Bugged on only Chromium?

For Firefox any network filters is no needed...

**Comment by DandelionSprout** [comment]
Okay, so while looking into Firefox, it seemed on my end to also need `||google-analytics.com^`, but I also came to realise that it's been fixed in so many other lists that it's making my case look pretty weak (Peter Lowe, uAssets Privacy, uAssets Experimental), just not any of the anti-malware lists that are known to exist out there (except from *Dandelion Sprout's Anti-Malware List* as of two hours ago).

**Comment by krystian3w** [comment]
`http://sdi-tool.org/releases/SDI_R1904.zip`

with used:

`@@||google-analytics.com^`

**Comment by krystian3w** [comment]
Also no have any google analytics, only blocked tag manager:

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 | ##.social_network |  | sdi-tool.org |  | dom | `https://sdi-tool.org/download/` |
| +1 |  |  | sdi-tool.org | 1 | image | `https://sdi-tool.org/html/images/favicon.ico` |
| +1 |  |  | sdi-tool.org | 1 | image | `https://sdi-tool.org/html/images/arrow-right.png` |
| +1 |  |  | sdi-tool.org | 1 | image | `https://sdi-tool.org/html/images/arrow-left.png` |
| +0 | /images/social- | -- | sdi-tool.org | 1 | image | `https://sdi-tool.org/html/images/social-network-sprite.png` |
| +0 |  |  | sdi-tool.org | 1 | image | `https://sdi-tool.org/html/images/arrow-down.png` |
| +0 |  |  | sdi-tool.org | 1 | image | `https://sdi-tool.org/html/images/logo2m.png` |
| +0 | \|\|yadro.ru^ | -- | sdi-tool.org | 3 | image | `https://counter.yadro.ru/hit?t26.6;r;s1536*864*24;uhttps%3A//sdi-tool.org/download/;hDownload;0.3029634811204257` |
| +0 | \|\|mc.yandex.ru^ | -- | sdi-tool.org | 3 | script | `https://mc.yandex.ru/metrika/tag.js` |
| +0 |  |  | sdi-tool.org | 1 | image | `https://sdi-tool.org/html/images/slides/si-award-epick5.png` |
| +0 |  |  | sdi-tool.org | 1 | image | `https://sdi-tool.org/html/images/slides/abouttech.png` |
| +0 |  |  | sdi-tool.org | 1 | image | `https://sdi-tool.org/html/images/slides/ghacks.png` |
| +0 |  |  | sdi-tool.org | 1 | image | `https://sdi-tool.org/html/images/slides/technible.png` |
| +0 |  |  | sdi-tool.org | 1 | image | `https://sdi-tool.org/html/images/slides/get-into-pc-icon.png` |
| +0 |  |  | sdi-tool.org | 1 | image | `https://sdi-tool.org/html/images/slides/major-geeks-logo.png` |
| +0 |  |  | sdi-tool.org | 1 | image | `https://sdi-tool.org/html/images/vff4.png` |
| +0 | googletagmanager.com/gtm.js | << | sdi-tool.org |  | script | `https://www.googletagmanager.com/gtm.js?id=GTM-P6LR8C4` |
| +0 | \|\|googletagmanager.com/gtm.js$script | -- | sdi-tool.org | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-P6LR8C4` |
| +0 |  |  | sdi-tool.org | 3 | script | `https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js` |
| +0 |  |  | sdi-tool.org | 1 | script | `https://sdi-tool.org/html/live/js/show_sources.js?2` |
| +0 |  |  | sdi-tool.org | 1 | script | `https://sdi-tool.org/html/live/js/slider.js?2` |
| +0 |  |  | sdi-tool.org | 1 | css | `https://sdi-tool.org/html/live/styles/mobile.css` |
| +0 |  |  | sdi-tool.org | 1 | css | `https://sdi-tool.org/html/live/styles/style.css` |
| +0 |  |  | sdi-tool.org | 1 | doc | `https://sdi-tool.org/download/` |
</details>

**Comment by DandelionSprout** [comment]
That gives us a bit of a difficulty in reaching a consensus, because on at least two PCs in my household the site tries to run a script from `https://www.google-analytics.com/gtm/js?id=GTM-5GHDWHF&t=gtm2&cid=1765750579.1563632206`, whose near-unique-in-history use of `"vtp_mode":"REPLACE",` seems more than a little malware-like to me.

**Comment by krystian3w** [comment]
So maybe same results in no cleaned:

```
https://www.googletagmanager.com/gtm.js?id=GTM-P6LR8C4
```

**Comment by DandelionSprout** [comment]
Now that I think about it, `SDI Tool` have been accused of being in cahoots with more than one malware distribution method (incl. adware stuff), so I wouldn't hold it past them to try to push multiple things based on IP addresses.

**Comment by DandelionSprout** [comment]
Okay, so with the burden of proof being pretty heavily on me, I decided to push aside my plans to clean my kitchen and discovered some more stuff related to all this:

* `https://sdi-tool.org/search.html` seems to redirect to `https://drp.su/en/catalog?utm_source=sdi-tools&utm_medium=redirect&utm_campaign=search_button`, without any script reliance at all.
* The script does not seem to be triggered by OS, IP addresses, or by previously having used SDI, as the script was still being triggered on *Firefox for Android* with mobile data.
* The script also causes an Opera download affiliate paragraph to show up on `https://sdi-tool.org/` (The front page), while also breaking the English translation of parts of the site:
![image](https://user-images.githubusercontent.com/22780683/61582274-25efeb80-ab29-11e9-90c4-7ffd15ca9b39.png)

**Comment by krystian3w** [comment]
I have too this redirect.

```
<head>
<meta http-equiv="refresh" content="1;URL=https://drp.su/catalog?utm_source=sdi-tools&utm_medium=redirect&utm_campaign=search_button" />
</head>
```

for Firefox 57+ and uBO 1.15.0+ possible remove with html filtering:

`sdi-tool.org##^meta[http-equiv="refresh"][content*="drp.su"]`

for some people this is still JavaScript or something similar.

---

Cyrylic infection no detected for me:

![Screenshot_2019-07-20 Snappy Driver Installer - Install and Update Drivers for Free](https://user-images.githubusercontent.com/35370833/61582410-d8747e00-ab2a-11e9-90c1-ccaf31c3214c.png)

**Comment by krystian3w** [comment]
I have too this redirect.

```
<head>
<meta http-equiv="refresh" content="1;URL=https://drp.su/catalog?utm_source=sdi-tools&utm_medium=redirect&utm_campaign=search_button" />
</head>
```

> I no see `meta charset` so no possible block by HTML Filtering too? But for some reasons filter works for me:
> 
> `sdi-tool.org##^meta[content*="drp.su"]`
>
> *(on suported platform and latest stable addon version)*

(...)

This is still script should only blocked by disable all JS on site:

`no-scripting: sdi-tool.org true`

without custom scriplet "`abort-meta-refresh`" if andybody create it.

---

"Cyrillic" 'infection' no detected for me:

![Screenshot_2019-07-20 Snappy Driver Installer - Install and Update Drivers for Free](https://user-images.githubusercontent.com/35370833/61582410-d8747e00-ab2a-11e9-90c1-ccaf31c3214c.png)

**Comment by okiehsch** [comment]
> My suggested fix: ||google-analytics.com^$domain=sdi-tool.org

Is already blocked with a default setup.
Filters to `uAssets` will only be added for issues that can be reproduced with a default setup.

**Comment by okiehsch** [comment]
> Also no have any google analytics, only blocked tag manager:

Yes the google-analytics script depends on `googletagmanager.com/gtm.js` running first on my end.
To reproduce the "Driverpack Online" issue I have to allow googletagmanager and google-analytics.
Both are blocked by default

**Comment by okiehsch** [comment]
> `https://sdi-tool.org/search.html` seems to redirect to `https://drp.su/en/catalog?utm_source=sdi-tools&utm_medium=redirect&utm_campaign=search_button`, without any script reliance at all. This means that it's extremely unlikely that sdi-tool.org had simply been unknowingly hacked.

![image](https://user-images.githubusercontent.com/16838044/61586244-6bcfa280-ab6f-11e9-96e7-3eaad6de1ce6.png)

The site uses meta refresh to create a client side redirect.
The "content=1" part means that the user will be redirected to the specified URL after 1 second.
I can break the redirection for Firefox users but the result would be a blank page.

**Comment by krystian3w** [comment]
So no any visible text on site and no `meta charest` tag is not problem for html filtering in this case @gwarser?

**Comment by gwarser** [comment]
remove-attr.js?

**Comment by krystian3w** [comment]
this works too late for meta refresh...

---

Why this works when website have only head without charset endcoding metatag:

```
sdi-tool.org##^meta[content*="drp.su"]
```

**Comment by gwarser** [comment]
For unknown encodings utf-8 is assumed.
