### ISSUE TITLE
Ads in beginning and during video on IMDB TV channel using Prime Video

### ISSUE THREAD

**Issue by Movisivi** [uBlockOrigin/uAssets#5988]
### URL(s) where the issue occurs

Any series under IMDB TV (first link is Leverage, second is Fringe, third is Heroes, fourth Warehouse 13)
`https://www.amazon.com/gp/video/detail/B00C15UUU2`
`https://www.amazon.com/gp/video/detail/B002PK2OES`
`https://www.amazon.com/Genesis/dp/B000U6C35O`
`https://www.amazon.com/A-New-Hope/dp/B008JSO21S`

### Describe the issue

When playing any episode on a show that is on Amazon Prime with IMDB tv, an ad plays before the episode starts, and has 4-6 60-90 seconds breaks dispersed throughout the episode. 

### Screenshot(s)

http://prntscr.com/ohxa1y
http://prntscr.com/ohxa4i
http://prntscr.com/ohxa84

### Versions

- Browser/version: Firefox Nightly 70.0a1
- uBlock Origin version: 1.20.2

### Settings

- Enabled extra filters: http://prntscr.com/ohxafm

### Notes

Tried with a clean profile and default uBO config with no success. I don't believe this has been worked on yet as IMDB TV is a recent addition.

**Comment by Movisivi** [comment]
I'm not sure if i should open a new issue or come back here since its the same site acting up.  I resubbed to Prime Video and noticed ads were back. First thing I loaded was https://www.amazon.com/gp/video/detail/B005V2IZ3Q. Firefox Nightly 81 with uBlock Origin v1.28.4 on MacOS 11

**Comment by mapx-** [comment]
open the logger, refresh the page, see what media type requests you get in the logger, post them here

**Comment by llacb47** [comment]
I tested and got no ads

![image](https://user-images.githubusercontent.com/16567977/89682973-a06ee300-d8c5-11ea-8f13-1a8a24dab503.png)

**Comment by Movisivi** [comment]
The logger shows no media type requests even though ads play

**Comment by llacb47** [comment]
Can you copy and paste the logger output when an ad is playing and put it in a comment?

**Comment by Movisivi** [comment]
Got it after a couple reloads. This is from one of the commercial breaks


22:49:05​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3A747303ed-ba14-4f1e-8449-107ccbd90517&consumptionId=%5BCONSUMPTIONID%5D
22:49:05​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3A22814118-726a-4efd-9800-26e99dc4e47d&consumptionId=%5BCONSUMPTIONID%5D
22:48:36​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3A7ae404c9-8202-4fe9-8ac5-7d8e5d406485&consumptionId=%5BCONSUMPTIONID%5D
22:48:35​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3A7ae404c9-8202-4fe9-8ac5-7d8e5d406485&consumptionId=%5BCONSUMPTIONID%5D
22:48:35​||amazon.*/batch/*/oe/$ping​--​www.amazon.com​1​beacon​https://fls-na.amazon.com/1/batch/1/OE/
22:48:34​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3A654b2ad4-43ab-4d6b-9aff-de232ef9aff7&consumptionId=%5BCONSUMPTIONID%5D
22:48:32​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3Ab6b29ec1-fb11-46a4-bf91-70380081674f&consumptionId=%5BCONSUMPTIONID%5D
22:48:31​||amazon.*/batch/*/oe/$ping​--​www.amazon.com​1​beacon​https://fls-na.amazon.com/1/batch/1/OE/
22:48:30​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3A9f301d11-1585-46af-bd64-7d1f1b08006b&consumptionId=%5BCONSUMPTIONID%5D
22:48:28​||amazon.*/batch/*/oe/$ping​--​www.amazon.com​1​beacon​https://fls-na.amazon.com/1/batch/1/OE/
22:48:25​@@||amazon.*/*uedata$image,1p​++​www.amazon.com​1​image​https://fls-na.amazon.com/1/batch/1/OP/ATVPDKIKX0DER:130-5638383-5252769:D1Y0G83BATA1SC7WEAZA$uedata=s:%2Fgp%2Fuedata%3Fld%26v%3D0.213489.0%26id%3DD1Y0G83BATA1SC7WEAZA%26ctb%3D1%26sc0%3DGetDetailPage%26tc0%3D0%26bb0%3D512%26be0%3D513%26pc0%3D513%26ld0%3D513%26t0%3D1596858505809%26pty%3DDetail%26spty%3DTVSeason%26pti%3DB005V2IZ3Q%26tid%3DYNJ7Z24JX8G2RBNDQ7DN%26aftb%3D1:17031
22:48:25​@@||amazon.*/*uedata$image,1p​++​www.amazon.com​1​image​https://fls-na.amazon.com/1/batch/1/OP/ATVPDKIKX0DER:130-5638383-5252769:D1Y0G83BATA1SC7WEAZA$uedata=s:%2Fgp%2Fuedata%3Fld%26v%3D0.213489.0%26id%3DD1Y0G83BATA1SC7WEAZA%26ctb%3D1%26sc0%3DGetTitles%26tc0%3D0%26bb0%3D282%26be0%3D283%26pc0%3D283%26ld0%3D283%26t0%3D1596858505583%26pty%3DDetail%26spty%3DTVSeason%26pti%3DB005V2IZ3Q%26tid%3DYNJ7Z24JX8G2RBNDQ7DN%26aftb%3D1:16805
22:49:55​​​www.amazon.com​3​image​https://media.amazon.map.fastly.net/
22:49:55​​​www.amazon.com​3​image​https://m.media-amazon.com/images/M/MV5BMTA0NTg3OTk3MjheQTJeQWpwZ15BbWU4MDc5NzY4NTAy._V1_SX164_CR0,0,164,246_.jpg
22:49:54​||amazon.com^*/events/$domain=~aws.amazon.com​--​www.amazon.com​1​beacon​https://unagi.amazon.com/1/events/com.amazon.csm.csa.prod
22:49:54​​​www.amazon.com​3​image​https://media.amazon.map.fastly.net/
22:49:54​​​www.amazon.com​3​image​https://m.media-amazon.com/images/M/MV5BNzA2OTg5MDE2Ml5BMl5BanBnXkFtZTgwMzI0MTAwNzE@._V1_SY246_CR16,0,164,246_.jpg
22:49:54​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3A2b52fc88-dd4d-4ab7-98c3-6fa9d80fc19e&consumptionId=%5BCONSUMPTIONID%5D
22:49:52​||amazon.*/batch/*/oe/$ping​--​www.amazon.com​1​beacon​https://fls-na.amazon.com/1/batch/1/OE/
22:49:50​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3A266f95ae-8e2d-42bd-b675-17e4767cfeff&consumptionId=%5BCONSUMPTIONID%5D
22:49:50​||amazon.*/batch/*/oe/$ping​--​www.amazon.com​1​beacon​https://fls-na.amazon.com/1/batch/1/OE/
22:49:46​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3A2c16be70-d3f9-4d5b-92e1-a094b4ef0079&consumptionId=%5BCONSUMPTIONID%5D
22:49:42​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3A33ea8d0c-2274-44f8-8a48-aef4e795179a&consumptionId=%5BCONSUMPTIONID%5D
22:49:39​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3Ad34a3570-16fa-47c6-89ef-0edb53a6a32c&consumptionId=%5BCONSUMPTIONID%5D
22:49:39​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3A2fb2d062-575e-4570-b25b-4cec5e77df6e&consumptionId=%5BCONSUMPTIONID%5D
22:49:39​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3A21efbdf6-05df-45f5-b1e1-0974883e95e2&consumptionId=%5BCONSUMPTIONID%5D
22:49:38​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3A21efbdf6-05df-45f5-b1e1-0974883e95e2&consumptionId=%5BCONSUMPTIONID%5D
22:49:32​||amazon.*/batch/*/oe/$ping​--​www.amazon.com​1​beacon​https://fls-na.amazon.com/1/batch/1/OE/
22:49:31​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3A549bb67b-db23-4036-a563-b3a11a324b02&consumptionId=%5BCONSUMPTIONID%5D
22:49:23​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3A4792cbc7-0544-4a6b-812a-6534d8973c55&consumptionId=%5BCONSUMPTIONID%5D
22:49:23​||amazon.*/batch/*/oe/$ping​--​www.amazon.com​1​beacon​https://fls-na.amazon.com/1/batch/1/OE/
22:49:16​​​www.amazon.com​3​image​https://ters.us-east-1.aiv-delivery.net/v1/ReportEvent?shortened=true&data=yoda%3A%3A1a5db51a-839d-4e8d-8b53-9e35f7ec8755%3A%3Adb99d1a8-4f29-496e-9d3d-b5d637ec2d08&consumptionId=%5BCONSUMPTIONID%5D
22:49:11​||amazon.*/batch/*/oe/$ping​--​www.amazon.com​1​beacon​https://fls-na.amazon.com/1/batch/1/OE/
22:49:10​||amazon.com^*/events/$domain=~aws.amazon.com​--​www.amazon.com​1​beacon​https://unagi.amazon.com/1/events/com.amazon.csm.csa.prod
22:49:07​||amazon.*/batch/*/oe/$ping​--​www.amazon.com​1​beacon​https://fls-na.amazon.com/1/batch/1/OE/
22:49:05​||amazon.*/batch/*/oe/$ping​--​www.amazon.com​1​beacon​https://fls-na.amazon.com/1/batch/1/OE/

**Comment by gwarser** [comment]
@llacb47 are you able to check this? 

- https://www.reddit.com/r/uBlockOrigin/comments/jivnw3/adblock_and_ublock_doesnt_block_imdb_ads_im/
- https://www.reddit.com/r/uBlockOrigin/comments/jjyw2z/imdbtv_ads_are_back/
