### ISSUE TITLE
Cosmetic filter doesn't work properly

### ISSUE THREAD

**Issue by shnaps** [uBlockOrigin/uAssets#599]
### URL(s) where the issue occurs

[Site where i have found it](https://4pda.ru/forum/index.php?s=&showtopic=755846&view=findpost&p=50934196)

### Describe the issue

Enabled cosmetic filter's option make some links and op post image invisible

### Screenshot(s)

[1 screenshot with disabled cosmetics](https://image.prntscr.com/image/DKxizA9UQkaiDFShPTfYLQ.png)

[2 screenshot with enabled cosmetics](https://image.prntscr.com/image/VWJWy8CgStCNrwG7r3u0UQ.png)

### Versions

- Browser/version: [Chrome 59.0.3071.115]
- uBlock Origin version: [uBlock Origin v1.13.8]

### Settings

- Nothing

### Notes

I found out that problem relates to cosmetic filter. Look at attached screenshots' links

**Comment by gorhill** [comment]
There is nothing wrong, that is the result of applying whatever cosmetic filters is active on that site. You are not making the case there is something wrong with uBO, you are just not happy that there is a blank area where the hidden elements are located. This is a filter issue, not a uBO issue.

**Comment by gorhill** [comment]
Ugh sorry, I thought I was on /uBlock, did not realize I was at /uAssets.

**Comment by gorhill** [comment]
The problem is the filter

    4pda.ru##a[rel][target]:not([attach_id]):has(> img:not([data-src]))

Which was added for #409.

**Comment by shnaps** [comment]
All fine, gonna try #409

**Comment by gorhill** [comment]
#409 does not look so well anymore on my side on the front page. This is because of lack of user styles on Chromium-based browsers.

**Comment by gorhill** [comment]
Looks better when enabling Adguard Russian filters.

**Comment by shnaps** [comment]
Without RU Adlist?

**Comment by shnaps** [comment]
Yep. Seems like Ru Adguard works here. Got only 3 cosmetic filters against 15 in RU Adlist.
