### ISSUE TITLE
racaty.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5990]
### URL(s) where the issue occurs

`racaty.com/fac4mv9cm9sg`

### Describe the issue

Popup ads on clicking download on intermediate pages

Shady xhr's

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.20.2

### Settings

-uBO's default settings

**Comment by JobcenterTycoon** [comment]
`racaty.com##+js(addEventListener-defuser.js, DOMContentLoaded)` will block it

**Comment by ghajini** [comment]
`racaty.net/92araidxnwfb`
Popup ads in opera browser

`racaty.*##+js(nowebrtc)` works

**Comment by ghajini** [comment]
`https://racaty.net/nkrcwudtyp7m`

Popup ads upon clicking download and in next tab also....

`racaty.net##+js(aopw, Fingerprint2)`
`racaty.net##+js(aeld, , _0x)`
`||vendnibtemp.com^`
`||weaknickgale.icu^`

**Comment by ghajini** [comment]
`https://racaty.net/5afppyranrkq`

These buttons don't work 

https://user-images.githubusercontent.com/20338483/92327046-72232580-f074-11ea-9ad8-669210bf4d0c.jpg

Firefox mobile nightly
ublock origin stable

**Comment by ghajini** [comment]
`https://racaty.net/ao5hkaamoq93`
Firefox, ublock stable

Update to `racaty.*##+js(aopr, btoa)`

**Comment by mapx-** [comment]
> new 3rd party ads

You mean 3 new bad scripts / domains ? I cannot reproduce

**Comment by ghajini** [comment]
Yes there was 3rd party ad named ovaidan.com(something like that)

Now I can't reproduce

Check with opera also
