### ISSUE TITLE
beeload.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#5991]
### URL(s) where the issue occurs

`beeload.com/f/21j8ij-q6drjls7c3so6`

### Describe the issue
Popup ads after captcha completion at final download page

### Versions

- Browser/version: opera browser 
- uBlock Origin version: 1.20.2

### Settings

- uBO's default settings

**Comment by JobcenterTycoon** [comment]
`beeload.com##+js(abort-on-property-read.js, BetterJsPop)` works for me
