### ISSUE TITLE
tvnow.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#5995]
### URL(s) where the issue occurs

`https://www.tvnow.de/serien/verdachtsfaelle-248/2019-07/episode-9-baby-verschwindet-in-waschanlage-1644114`

### Describe the issue

The Video player try to play Video Ads. This is fixed with: `||damoh.tvnow.de/*$media,redirect=noopmp3-0.1s,domain=tvnow.de`

The problem here is the player try to play multiple Video Ads in a row. uBlock Origin try to skip these Ads but on the second one the video stuck in the middle and you need to click on the small play botton at bottom left. no problem here, but 1. you need to click 2 or 3 times on the play button to play and 2. when you are unlucky you need to do this with 3-4 stucked Video ads in a row. a example:

The Video Player try to play a ad, uBlock Origin skip this but the player plays a second ad. this ad stuck and you need to play this manually. After 7 mins of normal content the player plays again video ads and you have the same problem again. This is a little bit annoying when you want to watch a 45 min movie with this. I hope you know what I mean. A expample Picture with logger:
### Screenshot(s)

<img width="1344" alt="tvnow" src="https://user-images.githubusercontent.com/48647394/61670081-b0c81600-ace2-11e9-9af5-f5465175b403.PNG">

### Versions

- Browser/version: Firefox 68.0.1
- uBlock Origin version: uBlock Origin v1.20.2

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3419397/Settings.txt)

### Notes

I hope it's possible to find a better filter to prevent the player to play Ads.
@lain566 is this possible to block these ads completely like these glomex ads?

Thanks.

**Comment by lain566** [comment]
Fixed.

**Comment by JobcenterTycoon** [comment]
Thanks lain566

**Comment by JobcenterTycoon** [comment]
@lain566 

but one problem: When the Video player try to play the next Kapitel (left bottom these numbers) the player will freeze. It’s not possible to select manually a new Kapitel because the control bar dissapear to.

**Comment by lain566** [comment]
This should fix the issue, can you check it?

**Comment by JobcenterTycoon** [comment]
Yes it works, thanks.
