### ISSUE TITLE
Mobile newsletter walls

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#5998]
https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-511467029

# url-s

```
https://www.secretescapes.de/
```

```
https://travelbird.be
https://travelbird.dk
https://travelbird.de
https://travelbird.fr
https://travelbird.nl
https://travelbird.no
https://travelbird.at
https://travelbird.ch
https://travelbird.fi
https://travelbird.se
```

# environment

* Android 8.1,
* Kiwi Browser 75 ("Genie" in Google Play Store), 
* uBO 1.20.0 (as for now no possible download latest without export setting and unistall old).

# other details

PC have only FancyBox plugin pop-up ~~maybe blocked in Fanboy / AdGuard Annoyance.~~

 Tested, no blocked for any these lists on PC...

**Comment by mapx-** [comment]
`##.fancybox-overlay, .fancybox-mobile`

**Comment by krystian3w** [comment]
no kill mobile wall:

![obraz](https://user-images.githubusercontent.com/35370833/61904553-579cf400-af27-11e9-8f79-d47040b8cae5.png) |
--- |

**Comment by krystian3w** [comment]
On PC also possible remove no needed horizontal scrolling by:

```
secretescapes.de,travelbird.be##body:style(overflow: auto !important;)
```
