### ISSUE TITLE
blackberrymobile.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#5999]
`https://blackberrymobile.com/emea/`

Website broken by EasyPrivacy:

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 | /site_tracking. | -- | blackberrymobile.com | 1 | script | `https://blackberrymobile.com/emea/core/modules/bwp-minify/min/?f=wp-content/plugins/woocommerce/assets/js/js-cookie/js.cookie.min.js,wp-content/plugins/woocommerce/assets/js/frontend/woocommerce.min.js,wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min.js,wp-content/plugins/activecampaign-subscription-forms/site_tracking.js,wp-content/plugins/email-subscribers/widget/es-widget-page.js,wp-content/themes/blackberry-global-child/dist/scripts/main.js,wp-content/themes/blackberry-global-child/dist/scripts/vendor/slick.min.js,wp-content/themes/blackberry/js/modernizr.js,wp-content/themes/blackberry/js/jquery.fancybox.min.js,wp-content/themes/blackberry/js/superfish.js` |
| +1 | /site_tracking. | -- | blackberrymobile.com | 1 | script | `https://blackberrymobile.com/emea/core/modules/bwp-minify/min/?f=wp-content/plugins/woocommerce/assets/js/js-cookie/js.cookie.min.js,wp-content/plugins/woocommerce/assets/js/frontend/woocommerce.min.js,wp-content/plugins/woocommerce/assets/js/frontend/cart-fragments.min.js,wp-content/plugins/activecampaign-subscription-forms/site_tracking.js,wp-content/plugins/email-subscribers/widget/es-widget-page.js,wp-content/themes/blackberry-global-child/dist/scripts/main.js,wp-content/themes/blackberry-global-child/dist/scripts/vendor/slick.min.js,wp-content/themes/blackberry/js/modernizr.js,wp-content/themes/blackberry/js/jquery.fancybox.min.js,wp-content/themes/blackberry/js/superfish.js` |
</details>

Possible fix:

`@@||blackberrymobile.com/emea/core/modules/bwp-minify/min/?f=wp-content*$script,1p`

**Comment by mapx-** [comment]
@ryanbr
