### ISSUE TITLE
login issue with ublock

### ISSUE THREAD

**Issue by S3ndG** [uBlockOrigin/uAssets#6]
Hi, when I go on this website: http://www.vulgaris-medical.com/forum-sante
I got an issue if If click on "Rejoignez Vulgaris !
**Je m'inscris Je m'identifie**" at the top left on the page. It stops loading. I cannot login on this website with ublock enabled.
Here is a screenshot so you can click on the right link : http://ratm6.free.fr/vulgaris_ublock_issue.JPG

My settings:
firefox 45.0.1 x64 for windows
uBlock Origin version: 1.6.8

I use the default user lists.

Could you tell me what can I do in order to login on this website with ublock enabled?
thanks! :)

**Comment by gorhill** [comment]
Purge the cache of any one of your filter list then force an update. Confirm whether this fixes the issue please.

**Comment by S3ndG** [comment]
OK it works well now.
Thanks!
