### ISSUE TITLE
No Video Playback chip.de

### ISSUE THREAD

**Issue by akks1981** [uBlockOrigin/uAssets#60]
No Video Playback @ chip.de 

look @

http://www.chip.de/news/Windows-vs-iPhone-Diese-Kurve-erklaert-das-Microsoft-Apple-Drama_94639161.html

http://www.chip.de/news/Kein-Bock-auf-Windows-10-Diese-Grafik-zeigt-das-groesste-Problem-von-Microsoft_94583966.html

http://www.chip.de/news/Besser-als-die-Hoellenmaschine-Pure-Grafikpower-in-Asus-Notebook_94634806.html

http://www.chip.de/news/Unsere-11-zur-EM-Fernseher-Fitness-Armband-Tablet-und-mehr_94775090.html

### Describe the issue
the video loads +- 15 sec and ends with a witescreen

### Versions

- Browser/version: Firefox 47 rc3
- uBlock Origin version: 1.7.5 rc1

### Settings

standart settings
flashplayer disabled

**Comment by gwarser** [comment]
Static filter ||s3.amazonaws.com/homad-global-configs.schneevonmorgen.com/hd-main.js$domain=chip.de|computerbild.de|cdnapi.kaltura.com|focus.de|spiegel.de|stern.de|t-online.de,script found in:

    uBlock filters

**Comment by akks1981** [comment]
ok dk why now it works well again @ chip.de

**Comment by Hrxn** [comment]
Please close if everything is working again as it should..

**Comment by akks1981** [comment]
yes it can be closed!

**Comment by Hrxn** [comment]
Tip: As the issue opener, you should be able to close it yourself :wink:

**Comment by akks1981** [comment]
omg how? sry

**Comment by Hrxn** [comment]
Okay, seems you found it :wink:

**Comment by akks1981** [comment]
:-) sry

**Comment by Hrxn** [comment]
No problem ^^
