### ISSUE TITLE
https://star.txstate.edu/

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#600]
### URL(s) where the issue occurs

`https://star.txstate.edu/`

### Describe the issue

The name of the site is being covered (probably as a side effect from blocking a banner ad)

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/28749593-5a804cb8-749a-11e7-9ff6-4729fb7cde78.png)

**Comment by okiehsch** [comment]
````
star.txstate.edu#@#.td-ad
star.txstate.edu#@#.td-header-ad-wrap
````
fyi @ryanbr
