### ISSUE TITLE
wetteronline.de

### ISSUE THREAD

**Issue by AlleSchonWeg** [uBlockOrigin/uAssets#6000]
### URL(s) where the issue occurs

`https://www.wetteronline.de/wetter-aktuell-toplisten` or `https://www.wetteronline.de/regenradar?wrp=periodCurrentHighRes`

### Describe the issue

Site displays no data. Enable addblock results in empty table.

### Versions

- Browser/version: Google Chrome  75.0.3770.142 (Offizieller Build) (64-Bit)
- uBlock Origin version:  v1.21.6

### Notes

**Comment by Hrxn** [comment]
I think that site uses IL now..

For Chromium-based browsers you might need to try [uBlock-Extra](https://github.com/gorhill/uBO-Extra).

**Comment by mapx-** [comment]
@AlleSchonWeg  did you test using only the default settings ? disabling all other extensions ?

**Comment by AlleSchonWeg** [comment]
Hi,
i test with the default settings and with disabling all other extensions:
![Unbenannt](https://user-images.githubusercontent.com/6727366/61931847-2271bf80-af82-11e9-9d3e-0c3ef5771ef3.PNG)
### With Adblock disabled:
![Unbenannt](https://user-images.githubusercontent.com/6727366/61931948-6a90e200-af82-11e9-984e-d4131abab262.PNG)
### With Adblock enabled:
![Unbenannt](https://user-images.githubusercontent.com/6727366/61932215-0fabba80-af83-11e9-9479-477a6bd221aa.PNG)

**Comment by mapx-** [comment]
for this site you have to install uBo extra too (dealing with nasty ads)
https://chrome.google.com/webstore/detail/ublock-origin-extra/pgdnlhfefecpicbbihgmbmffkjpaplco

**Comment by okiehsch** [comment]
I can't reprodue on my end.
![image](https://user-images.githubusercontent.com/16838044/61932897-cb211e80-af84-11e9-8c28-60004a9da1aa.png)

**Comment by AlleSchonWeg** [comment]
Thanks.
i testet with incoknito mode with adblock enabled.
First page load the data was displayed correct and ads filtered. I press ctrl+f5 and no data was displayed. Then i delete all cookies, reload and data was displayed.

**Comment by okiehsch** [comment]
Meaning the issue is now fixed or do you still have the problem if you press ctrl+ f5?

**Comment by AlleSchonWeg** [comment]
No, Not fixed. If i press crtl + f5 again i still have  the problem. Only deleting all cookies works one time.

**Comment by okiehsch** [comment]
You have installed uBO-extra?

**Comment by AlleSchonWeg** [comment]
Not yet. Should i try it?

**Comment by okiehsch** [comment]
Yes,  see my "Edit" at https://github.com/uBlockOrigin/uAssets/issues/6000#issuecomment-515337035

**Comment by AlleSchonWeg** [comment]
It works with uBO-extra.
Thanks
