### ISSUE TITLE
ratemyprofessors.com - IL ads

### ISSUE THREAD

**Issue by W4rH0rse** [uBlockOrigin/uAssets#6001]
### URL(s) where the issue occurs

`https://www.ratemyprofessors.com/search.jsp?query=Madeleine+Albright`

### Describe the issue

Site seems to be circumventing uBlock, even with fully updated filters site is covered with ads.

### Versions

- Browser/version: Brave Version 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)
- uBlock Origin version: v1.21.6

**Comment by mapx-** [comment]
@okiehsch  does this filter work for you ?
`ratemyprofessors.com##+js(abort-on-property-read.js, console.error)`

**Comment by okiehsch** [comment]
I still get redirected, the ads are gone but it breaks the site on my end using Chrome/Chromium.
I can't filter the results by "Professors" or "Schools" anymore.

**Comment by mapx-** [comment]
right, this 1 does not break the site (even with some redirecting), no ads for me
`ratemyprofessors.com##+js(set-constant.js, JSON.parse, trueFunc)`

**Comment by okiehsch** [comment]
We can add it and make it Chrome-specific. 
Will close the issue after **gorhill** has uploaded the next uBO-extra version.

**Comment by okiehsch** [comment]
Fixed in uBO-extra 2.83.
