### ISSUE TITLE
golem.de video ad

### ISSUE THREAD

**Issue by GiftWolf** [uBlockOrigin/uAssets#6002]
### URL(s) where the issue occurs

`https://video.golem.de/auto/23080/e-bike-neuerungen-von-bosch-angesehen.html`

### Describe the issue

When starting the news video an ad video might be shown. If not, it might be shown when pausing the video or switching the video quality from "SD" to "HD".

### Screenshot(s)

![image](https://user-images.githubusercontent.com/992940/60298063-eb2fd480-9929-11e9-9cee-a3891fa3db80.png)

### Versions

- Browser/version: Firefox 68.0
- uBlock Origin version: 1.20.2

### Settings

- disabled content blocking in Firefox

### Notes

using `||golemde.hmediacdn.com/*$media,redirect=noopmp4-1s` will block the ad but the wanted video will be a black rectangle with only the sound being played.

**Comment by okiehsch** [comment]
Does
`video.golem.de##+js(set-constant.js, rmp3pi, noopFunc)`
work for you?

**Comment by GiftWolf** [comment]
Yes, it works. Thank you!
