### ISSUE TITLE
claro.com.br

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#6003]
### URL(s) where the issue occurs

`https://www.claro.com.br/`

### Describe the issue

Overlay annoyance when you move your cursor to another tab.

### Versions

- Browser/version: Firefox stable
- uBlock Origin version: 1.20.2

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin lists

**Comment by mapx-** [comment]
test these filters
```
claro.com.br##.intervencao.modal
claro.com.br##.in.modal-backdrop
claro.com.br##body:style(overflow: auto !important;)
```

**Comment by adranger** [comment]
That works. There's also this:

 `https://planos.claro.com.br/monte-sua-combinacao`

Enter this info: 
CEP 01420-000
Número 616

![net](https://user-images.githubusercontent.com/35470489/61295693-05353800-a7af-11e9-9fda-689f858a9ecd.png)

The overlay when you move the cursor out of the page:

![net2](https://user-images.githubusercontent.com/35470489/61295789-3877c700-a7af-11e9-8e70-cba78ada5282.png)

**Comment by mapx-** [comment]
test
`planos.claro.com.br##.cdk-overlay-container`

**Comment by adranger** [comment]
That breaks scrolling for me.

**Comment by mapx-** [comment]
```
claro.com.br##.intervencao.modal
claro.com.br##.in.modal-backdrop
claro.com.br##html:style(overflow: auto !important;)
planos.claro.com.br##.cdk-overlay-container
```

**Comment by adranger** [comment]
@mapx- they've made changes to their site. Please remove these rules because they're now blocking an overlay with important information that used to open as a popup. If you want to test it, use the same data provided in https://github.com/uBlockOrigin/uAssets/issues/6003#issuecomment-515516977, pick a plan then try to click on this link:

![overlay](https://user-images.githubusercontent.com/35470489/86492446-8d0bad80-bd44-11ea-98ba-3fb649689d24.png)

**Comment by mapx-** [comment]
removed
