### ISSUE TITLE
softwaretestinghelp.com

### ISSUE THREAD

**Issue by bug-rules** [uBlockOrigin/uAssets#6013]
`https://www.softwaretestinghelp.com/usertesting-review/`

Pop-ups campanions:

* `Freelance Software Testing Job Opportunities`
* `Our Premium eBook free for LIMITED PERIOD!`

```
www.softwaretestinghelp.com##body:style(overflow: auto !important;)
www.softwaretestinghelp.com##.CampaignType--popup.Campaign[id^="om-"]
```

**Comment by mapx-** [comment]
do these filters work for you for both cases ?
```
softwaretestinghelp.com##.Campaign
softwaretestinghelp.com##body:style(overflow: auto !important;)
```
