### ISSUE TITLE
jmail.ovh

### ISSUE THREAD

**Issue by bug-rules** [uBlockOrigin/uAssets#6014]
ads in emails

> ![obraz](https://user-images.githubusercontent.com/43518394/62012280-89f75d00-b184-11e9-8cd8-e4661348647e.png) |
> --- |

```
/img/banners/*$1p,image
```

![obraz](https://user-images.githubusercontent.com/43518394/62012287-9d0a2d00-b184-11e9-93d0-14bd1de09410.png) |
--- |
![obraz](https://user-images.githubusercontent.com/43518394/62012293-b14e2a00-b184-11e9-9eae-679e05513c30.png) |

**Comment by mapx-** [comment]
You should report here
https://github.com/easylist/easylist/issues

**Comment by bug-rules** [comment]
And wait 2 years?

**Comment by mapx-** [comment]
@ryanbr

**Comment by bug-rules** [comment]
"Good ad" in EasyList opinion.

**Comment by ryanbr** [comment]
Its an image in an email, so yeah?

**Comment by bug-rules** [comment]
Nope, this advert no contains with readed e-mail on jmail.
