### ISSUE TITLE
Medium.com :: False block

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#6016]
### URL(s) where the issue occurs

`https://medium.com/p/e7e1fe62cb74/responses/show`

### Describe the issue

The following filter in `uBlock filters – Annoyances` list wrongly prevents overly to be shown.
`medium.com##.overlay`
When you click on "Write a response ..." in the middle of the page or "Sign-in" at top right of the page, nothing happens, unless you disable it by `medium.com#@#.overlay`

### Versions

- Browser/version: Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)
- uBlock Origin version: v1.21.6

**Comment by yourduskquibbles** [comment]
@mapx- How about update filter to `medium.com##.overlay:not(:has-text(Welcome back)):not(:has-text(write a response))`

This should be better filter than `##.overlay` for all Medium based domains and keeps the benefits of https://github.com/uBlockOrigin/uAssets/pull/5851 & it's [update commit ](https://github.com/uBlockOrigin/uAssets/commit/2a4202a866ca1895f460e80ab12cb2fe78c762f8)extending to more domains
