### ISSUE TITLE
neowin.net [Anti-Adblock]

### ISSUE THREAD

**Issue by busamisode** [uBlockOrigin/uAssets#6017]
### URL(s) where the issue occurs

`https://www.neowin.net`

### Describe the issue

They added a pesky anti-adblock pop-up everytime you load a page last week.

### Screenshot(s)

https://i.ibb.co/K6Hc1CK/Capture.png

### Versions

- Browser/version: Chrome 75.0.3770.142
- uBlock Origin version: 1.21.6

### Settings

Default Settings

### Notes

I've tried to block it manually but didn't work. I don't have the knowledge to do more than that.

**Comment by mapx-** [comment]
it's annoyance, you can:
- enable ublock filters- Annoyances list (in the first group of uBo lists)
or
- click "continue with adblocker"

**Comment by krystian3w** [comment]
Duplicate of #5979

**Comment by krystian3w** [comment]
Duplicate of https://github.com/ryanbr/fanboy-adblock/issues/1106#issue-470468254
