### ISSUE TITLE
Zerohedge.com -- most features of site are disabled with uBlock on, on android phone but not on desktop computer

### ISSUE THREAD

**Issue by BrianRoberts1** [uBlockOrigin/uAssets#6018]
### URL(s) where the issue occurs

`https://www.zerohedge.com`

**DESCRIBE THE ISSUE**

Starting around 2 days ago, **only on the mobile version of the site**, I noticed that all comments weren't there (as though no one posted yet), and I wasn't able to comment, even being logged into the site. Additionally, there is a context menu on the mobile version (top left) which is unusable. The only functionality of the site is I can click on any article hyperlink, or the main zerhohedge hyperlink at the top.

HOWEVER, on my desktop computer this site works fine without any problems. I can see other's posts, and I'm able to post myself.

**VERSIONS**

- Browser/version: Firefox / 68.0.1 (32-bit)
- uBlock Origin version: 1.21.2

(versions on both desktop and mobile are the same)

**SETTINGS**

No changes made to default settings

**NOTES**

Even when I request the desktop version of the site on my android phone, it doesn't change anything. Also, I noticed another poster on the site claim he is having the same issue (not able to see posts, and not able to post himself) using the Brave Browser, if this helps at all.

**Comment by okiehsch** [comment]
The filter causing your issue has been removed.
https://github.com/easylist/easylist/commit/9e6089c73e2a0f2a5018c0a10c5d8c5ec9bf97f2

Update your filter lists.

**Comment by BrianRoberts1** [comment]
Thank you for responding. Forgive my ignorance, but I'm not totally sure how to update my filter lists. I'm in options and see the various tabs. How do I proceed from there?

Am I copy/pasting that line in?

**Comment by okiehsch** [comment]
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now

Click the clock icon next to `EasyList` then click "Update now".

**Comment by BrianRoberts1** [comment]
Thank you once again. I appreciate it!
