### ISSUE TITLE
alluc.ee

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#602]
Hello,

**URL**

`https://www.alluc.ee/stream/2017`

**Describe the issue**

usenet Ads link http://i.imgur.com/9DSUaGQ.png

**Versions**

uBlock Origin 1.13.8 / Firefox 54

**Settings**

default settings

**Suggested filters**

`alluc.ee##.clickable:has(img[src*="/icoad."])`

**Note**

Other classic filters are posted at **EL** forum https://forums.lanik.us/viewtopic.php?f=62&t=36319

**Comment by gotitbro** [comment]
@okiehsch alluc.ee is conecting to the domain `piguiqproxy.com`.

This domain has been identified as malicious and was also recently seen on 4chan https://github.com/uBlockOrigin/uAssets/commit/43eb4648ba1126a58c933177da00154d469536dd.

**Error URL:** `http://www.alluc.ee/`

Looks like issues regarding this domain have been opened before. From what it seems blocking it causes the pages not to load. Any idea why is that?

_**Note:** Using 1.14.22 on Chrome 63 with the default filters and settings._

**Comment by okiehsch** [comment]
What is your issue exactly?
The connection to `piguiqproxy.com` is disabled after the first xhr-request by the filter
````
alluc.ee##script:inject(abort-current-inline-script.js, parseInt, 676574456c656d656e747342795461674e616d65)
 ````
which is already part of `uBlock-filters`.

**Comment by gotitbro** [comment]
@okiehsch I still see XHR requests to that domain for some reason with this whole block loaded: https://ctrlv.it/javascript/71709/3776192818

**Comment by okiehsch** [comment]
Your logger shows these 2 xhr-requests to `piguiqproxy.com`, does it not?
![pig](https://user-images.githubusercontent.com/16838044/34279012-a676b46e-e6ae-11e7-9636-ab8ad3f9bd3a.PNG)

**Comment by gotitbro** [comment]
@okiehsch Yes I get these requests https://i.imgur.com/a1g7KnE.png. Is this normal/expected?

**Comment by okiehsch** [comment]
Now disable the filter I mentioned by adding
````
alluc.ee#@#script:inject(abort-current-inline-script.js, parseInt, 676574456c656d656e747342795461674e616d65)
````
then reload and count the `piguiqproxy.com` connections, you will also notice ads appearing.

**Comment by okiehsch** [comment]
You can't block `piguiqproxy.com/api`, because that will break the site and a redirect only works with Chrome, so this is best solution as it prevents the site from pushing the ads.

**Comment by gotitbro** [comment]
@okiehsch You are right. I just noticed its requesting the malicious "argon" script in the last XHR request in my SS above https://i.imgur.com/a1g7KnE.png (See **X-Meta-Data**) the filter uBlock probably blocks this request.

I got worried as it was connecting to the `piguiqproxy.com` in the first place. Thanks for letting me know why it can't be blocked simply.

**Comment by gotitbro** [comment]
@okiehsch The domain seems to belong MGID, a known advertising network. They hid their connections with the malicious domain. Its sad when advertising companies do things like these but the blame is put on adblock users.

**H/T:** `https://www.reddit.com/r/TwoBestFriendsPlay/comments/7l6rli/security_psa_if_you_use_4chan_the_site_ran_ads/`
