### ISSUE TITLE
watson.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#6021]
### URL(s) where the issue occurs

`https://www.watson.de/leben/facebook/191547306-aldi-kunde-schimpft-ueber-menstruationstassen-fans-eilen-dem-konzern-zu-hilfe`

### Describe the issue

Ad pictures

### Screenshot(s)
![picture](https://user-images.githubusercontent.com/48647394/62134821-757ca700-b2e1-11e9-8ef3-68d65cd24f8c.PNG)

### Versions

- Browser/version: Firefox 68.0.1
- uBlock Origin version: uBlock Origin v1.21.2

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3447079/Settings.txt)

**Comment by mapx-** [comment]
For now (I'll test a german ip too) I get anti adb msg / popup

`watson.de##+js(set-constant.js, bAdBlocker, false)`

**Comment by JobcenterTycoon** [comment]
when i disable `AdGuard Annoyances` i can reproduce. Your filter works but i still get these ad pictures. When click on that picture i get redirected to `https://ad13.adfarm1.adition.com/redi?lid=6719473285168760039&gdpr=0&gdpr_consent=&gdpr_pd=0&userid=6719473285168563431&sid=4422470&kid=3142618&bid=10010195&c=33665&keyword=&sr=3&clickurl=`
