### ISSUE TITLE
[Annoyance, countdown] shrink.yt

### ISSUE THREAD

**Issue by llacb47** [uBlockOrigin/uAssets#6022]
### URL(s) where the issue occurs

`https://shrink.yt/u18j`

### Describe the issue

Annoyance timer on url shortener site, cannot be bypassed with `nano-setInterval-booster` because of server-side validation.

### Screenshot(s)

![Annoyance timer](https://user-images.githubusercontent.com/16567977/62141396-7ea64d80-b2ba-11e9-95fe-29d7b30a902d.png)

### Versions

- Browser/version: Tested in Chromium 70.0.3538.110 and Firefox Quantum 68.0.1
- uBlock Origin version: N/A, using Nano Adblocker 1.0.0.123

### Settings

- Tested with default settings in Firefox

### Notes

This filter prevents the timer from stopping when you stop focusing on the site window:
`shrink.yt##+js(set-constant.js, blurred, false)`

**Comment by JobcenterTycoon** [comment]
i get Anti-adblock overlay. The filter `shrink.yt##+js(bab-defuser.js)` will block it.

**Comment by llacb47** [comment]
I don't. What filter lists are you using?

**Comment by JobcenterTycoon** [comment]
[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3447513/Settings.txt)

**Comment by krystian3w** [comment]
Server side counter, IMO no possible speed-up.

**Comment by llacb47** [comment]
I know, but filter can be added for `onfocus` annoyance.
