### ISSUE TITLE
activistpost.com

### ISSUE THREAD

**Issue by pizza90** [uBlockOrigin/uAssets#6024]
### URL(s) where the issue occurs

`https://www.activistpost.com/`

### Describe the issue

Infected of any script of ads, showing ads below the screen.

### Screenshot(s)

Log: `https://i.imgur.com/C59LU3L.png`
Ads: `https://i.imgur.com/vLM3Nao.png`
### Versions

- Browser/version: [Chrome / 76.0.3809.87]
- uBlock Origin version: [v1.21.6]
- uBlock Extra

### Settings

- [Default / Spanish]

**Comment by mapx-** [comment]
Could you test this filter ? (some crap still in the logger but the page loading should be faster enough and no ad)
`activistpost.com##+js(set-constant.js, JSON.parse, trueFunc)`

**Comment by llacb47** [comment]
No ads for me with that filter

**Comment by pizza90** [comment]
no ads for me too

**Comment by llacb47** [comment]
Why not `||oaqjwapqdho.com^` 
page seems to work fine

**Comment by mapx-** [comment]
`oaqjwapqdho` are random crap, they can change periodically

**Comment by llacb47** [comment]
Well with admiral adblocker, every time a domain is found it is added to the filterlist.

**Comment by pizza90** [comment]
one incovenence here the comments of disqus is break? maybe?
`https://www.activistpost.com/2019/07/hacked-highways-connected-cars-could-gridlock-entire-cities-study-warns.html`

**Comment by llacb47** [comment]
How about `activistpost.com##+js(abort-current-inline-script.js, document.createElement)`
WIll probably break things as well.

**Comment by pizza90** [comment]
still the ads with that filter `llacb47`

**Comment by JobcenterTycoon** [comment]
@mapx- my browser still connect to these random domains. I get cookie banners from these domains too.
![Unbenannt](https://user-images.githubusercontent.com/48647394/62224757-77b13500-b3b7-11e9-8ffc-eca5a1095a38.PNG)
Browser: Firefox 68.0.1

**Comment by mapx-** [comment]
well, changing to
```
activistpost.com#@#+js(set-constant, JSON.parse, trueFunc)
activistpost.com##+js(set-constant, atob, trueFunc)
```

disqus not broken anymore, no ads, but (as I said already) some crap still in the logger

**Comment by JobcenterTycoon** [comment]
i can confirm

**Comment by mapx-** [comment]
Could someone test (reduced crap scripts to 1) for breakage ?
```
activistpost.com##+js(abort-on-property-read.js, XMLHttpRequest)
activistpost.com#@#+js(set-constant, atob, trueFunc)
activistpost.com#@#+js(set-constant, JSON.parse, trueFunc)
```
(last 2 exceptions only to be sure you don't use previous filters)

**Comment by llacb47** [comment]
@mapx- Tested those, they seem to work fine.

**Comment by mapx-** [comment]
thanks

**Comment by okiehsch** [comment]
`activistpost.com##+js(abort-current-inline-script.js, document.head.appendChild, ='\x)`
prevents the inline script pulling the `oaqjwapqdho` requests in the first place.
Up to you if you want to change it your filter fixes the issue just fine and I don't see any breakage.

**Comment by pizza90** [comment]
the ads returns :/

**Comment by mapx-** [comment]
test
`activistpost.com##+js(abort-on-property-read.js, Math.random)`

see if breaks something on site

**Comment by pizza90** [comment]
😊 no ads, disqus not working, but f*ck Disqus. other adblockers (ABP) does not show disqus on this site. 😤

**Comment by pizza90** [comment]
facebook widget also not working

**Comment by pizza90** [comment]
disqus not working, but not is the problem of that filter:

`activistpost.com##+js(abort-on-property-read.js, Math.random)`

**Comment by pizza90** [comment]
what about this:
```
$script,domain=activistpost.com
@@||activistpost.com/wp-includes/js/wp-emoji-release.min.js$script,domain=activistpost.com
@@||connect.facebook.net^$script,domain=activistpost.com
@@||platform.twitter.com/js/*$script,domain=activistpost.com
@@||theactivistpost.disqus.com^$script,domain=activistpost.com
```

**Comment by mapx-** [comment]
remove math.random filter, add only
`activistpost.com##+js(abort-on-property-read.js, String.fromCharCode)`

no ads and disqus working for me

**Comment by pizza90** [comment]
good work mapx-

**Comment by llacb47** [comment]
This commit fixes the sidebar clickbait ads?

**Comment by mapx-** [comment]
yes

**Comment by pizza90** [comment]
This guys never tired.. `FeelsSadMan`

`https://www.activistpost.com/`

**Comment by JobcenterTycoon** [comment]
Ad pictures at the bottom
![Unbenannt](https://user-images.githubusercontent.com/48647394/62412582-36ae6000-b605-11e9-838b-87bff24bc609.PNG)

**Comment by pizza90** [comment]
working for me: 🥶

`||activistpost.com/wp-content/uploads/*/*/logefieldlite-*.png`

**Comment by mapx-** [comment]
`*.png$image,domain=activistpost.com,redirect=2x2-transparent.png`

**Comment by pizza90** [comment]
no way to block this `.jpg` script?
`https://www.activistpost.com/ZfPTg/OdkXNzvtpJ/TgPfEvqICJA.jpg`

mapx- tested here:

`https://www.activistpost.com/category/economy`

with that filter: https://i.imgur.com/CJKsbxX.png
without filter: https://i.imgur.com/W4nHdoM.png

**Comment by pizza90** [comment]
I don't want to be annoying ... but the garbage and ads came back

**Comment by mapx-** [comment]
It was fixed hours ago, update your lists

**Comment by pizza90** [comment]
I'm sorry, I reset the settings, but I forgot to update the filters .. Apparently you have to update them after doing the reset?

The site is clean and no trash..

**Comment by mapx-** [comment]
yes, update always the lists after resetting the settings

**Comment by NubN** [comment]
hello, i dont know if i need reopen post or not. but anti adblock - paywal here

`https://www.activistpost.com/2019/10/us-to-send-thousands-more-troops-to-saudi-arabia.html`

`https://i.imgur.com/LsyaHSY.png`

**Comment by mapx-** [comment]
add
`||mediapass.com^$3p`

@okiehsch  here we have a mix paywall + anti adb stuff

**Comment by mapx-** [comment]
or 
```
###tmbox
###tmbluemask
```

**Comment by NubN** [comment]
if you mean:
```
activistpost.com###tmbox
activistpost.com###tmbluemask
```

facebook widget not working. maybe?

**Comment by okiehsch** [comment]
If the only way to circumvent the anti-adblock message is a filter that also breaks the paywall we add the filter.

**Comment by NubN** [comment]
other reference site (this site not have that waypall anti adblock today)
`https://forums.lanik.us/viewtopic.php?f=103&t=42385&p`

bye
