### ISSUE TITLE
Click to expand images on mobile.twitter.com is broken by annoyances filter

### ISSUE THREAD

**Issue by havlock128** [uBlockOrigin/uAssets#6025]
### URL(s) where the issue occurs

`mobile.twitter.com`

### Describe the issue

When clicking on a image on Twitter to expand it, the overlay that would show the expanded image appears for just a moment before vanishing. The URL still changes on click, appending 'photo/1' or 'photo/[whatever]' as usual. Clicking on the (smaller) image in the tweet at this point acts the same as clicking on a link to the tweet itself.

This issue first appeared for me two days ago, on the 29th of July.

### Versions

- Browser/version: Vivaldi 2.6.1566.49 (Stable channel) (32-bit)
- uBlock Origin version: 1.21.6

- Browser/version: Firefox 68.0.1 (64-bit)
- uBlock Origin version: 1.21.2

### Notes

Tested enabling and disabling uBlock Origin filter lists in both Vivaldi and Firefox on my machine and in Vivaldi on another machine and narrowed the issue cause down to 'uBlock filters – Annoyances.' Disabling that filter, applying the changes and reloading a mobile.twitter.com page allows expanding images in tweets properly again.

I also discovered that disabling 'Parse and enforce cosmetic filters' also allows image expanding in tweets to work properly again.

**Comment by yourduskquibbles** [comment]
Are you able to provide an example twitter profile with an image in the first series of tweets so I can recreate?

**Comment by llacb47** [comment]
I can reproduce, no account needed. Test URL: `https://mobile.twitter.com/KateAronoff/status/1156564030900834306`

**Comment by yourduskquibbles** [comment]
I've tested in chrome & firefox both logged in and not logged in and spoofing user agent to mobile as well with various screen resolutions and I can not reproduce with stock filters + uBO Annoyance list. 

@havlock128 or @llacb47 can you test adding `mobile.twitter.com#@#div[tabindex="0"]:matches-css(position:fixed)` to My Filters and see if the problem goes away?

**Comment by yourduskquibbles** [comment]
Was able to reproduce finally, adding that exception filter fixes the issue so I will remove and will need to find a better updated fix for #4987

**Comment by llacb47** [comment]
That fixes it.

**Comment by havlock128** [comment]
> I've tested in chrome & firefox both logged in and not logged in and spoofing user agent to mobile as well with various screen resolutions and I can not reproduce with stock filters + uBO Annoyance list.
> 
> @havlock128 or @llacb47 can you test adding `mobile.twitter.com#@#div[tabindex="0"]:matches-css(position:fixed)` to My Filters and see if the problem goes away?

I did add that string to My Filters and it appears to have fixed the issue.

**Comment by yourduskquibbles** [comment]
> 
> 
> > I've tested in chrome & firefox both logged in and not logged in and spoofing user agent to mobile as well with various screen resolutions and I can not reproduce with stock filters + uBO Annoyance list.
> > @havlock128 or @llacb47 can you test adding `mobile.twitter.com#@#div[tabindex="0"]:matches-css(position:fixed)` to My Filters and see if the problem goes away?
> 
> I did add that string to My Filters and it appears to have fixed the issue.

Thanks for confirming - I've remove the problem filter from the Annoyances list so you can purge cache and update your Annoyance list and you should be able to remove that filter from My Filters.

**Comment by havlock128** [comment]
Removed that filter from My Filters, purged filter list cache, updated filter lists and it looks like everything's working right with image expansion on click on mobile.twitter.com. Thanks!

**Comment by krystian3w** [comment]
IMO this for now no touch gallery:

```
mobile.twitter.com##body > div > div > div > div > div > div > div > div > div[tabindex="0"]:matches-css(position:fixed)
```


but maybe too long for #4987?

**Comment by yourduskquibbles** [comment]
I will have to revisit #4987 when I have some free time to play around with their redesign, I will need to try and come up with something more targeted so isn't possible to match anything else that could come up.
