### ISSUE TITLE
www.codeproject.com input box disappeared.

### ISSUE THREAD

**Issue by vungsung** [uBlockOrigin/uAssets#6026]
### URL(s) where the issue occurs

`https://www.codeproject.com/script/Membership/Modify.aspx`

### Describe the issue

input box disappeared due to the uBlock rules on `www.codeproject.com`.

### Versions

- Browser/version: Google Chrome 76.0.3809.87 x64 on Windows 10
- uBlock Origin version: v1.21.6

**Comment by mapx-** [comment]
What filter lists are enabled in uBo ?
Click those filters in your logger and see what is the triggered list

**Comment by yourduskquibbles** [comment]
If it is caused by the `##[style*="base64"]` filter it is part of EasyList but can't tell if that is what is causing the issue because looks like you need to login or use language encoding other than English to possibly recreate?

@vungsung try adding `codeproject.com#@#[style*="base64"]` to "My Filters" and see if fixes the issue

**Comment by vungsung** [comment]
@mapx- 	Sorry, I forgot that, but seems @yourduskquibbles has solved it.
@yourduskquibbles Yes, `codeproject.com#@#[style*="base64"]` did temporary fix that, how you inferences this?
OK, I spent some time investigating this, I figured it out. It's the `LastPass` extension, which injects the code to every input element.
#### So
`style="width:209px;"`
#### became
`style="width: 209px; background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABHklEQVQ4EaVTO26DQBD1ohQWaS2lg9JybZ+AK7hNwx2oIoVf4UPQ0Lj1FdKktevIpel8AKNUkDcWMxpgSaIEaTVv3sx7uztiTdu2s/98DywOw3Dued4Who/M2aIx5lZV1aEsy0+qiwHELyi+Ytl0PQ69SxAxkWIA4RMRTdNsKE59juMcuZd6xIAFeZ6fGCdJ8kY4y7KAuTRNGd7jyEBXsdOPE3a0QGPsniOnnYMO67LgSQN9T41F2QGrQRRFCwyzoIF2qyBuKKbcOgPXdVeY9rMWgNsjf9ccYesJhk3f5dYT1HX9gR0LLQR30TnjkUEcx2uIuS4RnI+aj6sJR0AM8AaumPaM/rRehyWhXqbFAA9kh3/8/NvHxAYGAsZ/il8IalkCLBfNVAAAAABJRU5ErkJggg==&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%;"`

Which matches the rule `[style*="base64"]` on codeproject.com.

**Comment by mapx-** [comment]
We could add that exception to unbreak list and you should report the issue at LastPass site / repository

**Comment by mapx-** [comment]
However, easylist should contain such exception .. @ryanbr
