### ISSUE TITLE
deadstate.org malicious redirect via mediapass.com

### ISSUE THREAD

**Issue by lpar** [uBlockOrigin/uAssets#6028]
### URL(s) where the issue occurs

`https://deadstate.org/`

### Describe the issue

Malicious redirect to an anti-adblock page happens on any page load with scripts disabled.

### Versions

- Browser/version: Firefox 68.0
- uBlock Origin version: 1.21.2

### Settings

The relevant change is that I disable JavaScript by default and allow it for domains I trust.

### Notes

Appears to be implemented by putting a noscript element in the head of the page:

```
<noscript><meta http-equiv="REFRESH" content="0; url=https://www.mediapass.com/subscription/noscriptredirect?key=6678&asset=7281&uri=deadstate.org"></noscript>
<script type="text/javascript" src="https://www.mediapass.com/static/js/mm.js"></script>
<script type="text/javascript">MediaPass.init(6678, { asset:7281 });</script>
</head>
```

A possible fix is to just block everything from www.mediapass.com. Since it's a paywall platform I don't imagine there's anything worthwhile to be found there? Might want to come up with something more fine-grained though.

Have also reported the issue on the EasyList forums.

**Comment by llacb47** [comment]
Test `deadstate.org##^meta[http-equiv="refresh"]`

**Comment by lpar** [comment]
Works for me.

**Comment by okiehsch** [comment]
> The relevant change is that I disable JavaScript by default and allow it for domains I trust.

I use the same setup, however filters will only be added to `uAssets` for issues that can be reproduced with a default setup, so the suggested working filter will not be added.

**Comment by llacb47** [comment]
@okiehsch can you add `||mediapass.com^$third-party,script`, as they provide paywall and anti-adblock services.

Please see  `https://www.mediapass.com` and `https://theislandnow.com` -- click on 6 articles and you will be paywalled by mediapass.


![Subscription nag powered by mediapass](https://user-images.githubusercontent.com/16567977/62333415-5755a900-b491-11e9-9a92-d23856e30efb.png)

![Paywall powered by mediapass](https://user-images.githubusercontent.com/16567977/62333435-6ccad300-b491-11e9-904a-c6cb321b2d3a.png)

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/2317#issuecomment-392009540

**Comment by okiehsch** [comment]
I don't know what the confused emoji means.
The linked comment from **gorhill** is pretty clear to me.
`uBO` will not circumvent paywalls. 
The difference between a paywall and an anti-adblock wall - as far as uBO is concerned - is that a paywall blocks every user from accessing the content regardless if one uses an adblocker or not.

`http://tooeleonline.com` uses a genuine paywall. It is laughably easy to circumvent it but it is a paywall nonetheless.
