### ISSUE TITLE
spankbang.com [NSFW]

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#6029]
### Describe the issue

[Visiting the site for the first time and clicking on a video opens a new tab (the video) while the previous tab redirects to `ero-advertising.com`. I can get this to trigger every time I clear cookies.]

### Versions

- Browser/version: [Chrome v75]
- uBlock Origin version: [1.21.6]

### Settings

- [default]

**Comment by nenfard** [comment]
The fix has made SpankBang unusable. It blocks all of their interface click triggers and the site uses JS for most of its features.

**Comment by dumbusernameidk** [comment]
Yes it does seem a few different buttons don't work like login/register or minor things like download.

**Comment by okiehsch** [comment]
> minor things like download.

I would say breaking the download functionality is not exactly a "minor" issue. ;)

**Comment by okiehsch** [comment]
Fixed.

**Comment by nenfard** [comment]
> Fixed.

Thanks a lot buddy!

**Comment by dumbusernameidk** [comment]
Is there a possible better filter for this? I looked into `https://static.spankbang.com/static_desktop/gen/packed.v4.main.c22a3657.js` and i tried the filter `spankbang.com##+js(std, document.location.assign, 25)` this prevents the popunder but creates the second tab which is an annoyance.

Then i tried `spankbang.com##+js(aopr, analytics_track_event)` but this gives two errors in the console saying it's been declared (sorry not great at JS so idk if that's bad or not). but this does prevent the popunder and it doesn't create the second tab.

**Comment by llacb47** [comment]
try `spankbang.com##+js(set, window.open, noopFunc)`

**Comment by okiehsch** [comment]
`spankbang.com##+js(set, open, noopFunc)`
works for me.
You don't need the `window` part, it is implied for the first argument.

**Comment by dumbusernameidk** [comment]
yeah that works for me too.

**Comment by nenfard** [comment]
Hi @okiehsch 

It seems your change has completely blocked window.open function on this site. Some of the site's functionalities (downloading, uploading, etc) are completely broken.

I looked at how Adguard is blocking pops (https://github.com/AdguardTeam/AdguardFilters/commit/6afc271f86d85d01bbca4ca7436eb5817964ea2c), they set bbm_pp_mobile cookie to 1. On desktop it seems to be bbm_pp_desktop that needs to be set.

What do you think?

Thanks!

**Comment by mapx-** [comment]
could you test downloading / uploading using these filters ?
```
spankbang.com#@#+js(set, open, noopFunc)
spankbang.com^$csp=sandbox allow-forms allow-same-origin allow-scripts allow-modals allow-orientation-lock allow-pointer-lock allow-presentation allow-top-navigation
```

**Comment by dumbusernameidk** [comment]
I tried it and it wont let you even click the download button.

**Comment by okiehsch** [comment]
> site's functionalities (downloading, uploading, etc) are completely broken.

I don't have an account, which appears to be needed to download, but if that is the case we will have to remove the filter.

> they set bbm_pp_mobile cookie to 1.

`uBO` does not support the possibilty to set cookies because of security reasons.

**Comment by dumbusernameidk** [comment]
possible to bypass the interstitial page that gets created? i know it's currently being suppressed with its own filter but if you visit the site for the first time (or delete the corresponding cookie) then you can actually 'click' on any video. weirdly you can still right click but that seems like a weird bypass.

**Comment by stephenhawk8054** [comment]
> possible to bypass the interstitial page that gets created? i know it's currently being suppressed with its own filter but if you visit the site for the first time (or delete the corresponding cookie) then you can't actually 'click' on any video. weirdly you can still right click but that seems like a weird bypass.
> 
> of course you could just refresh the page and then you're allowed to freely click on anything but the cookie is deleted every 24 hours. seems like small nuisance if you ask me.

I can click on the video normally at the first time (open in Private Window and Firefox set to clearing cookies and history after exit).

**Comment by dumbusernameidk** [comment]
> > possible to bypass the interstitial page that gets created? i know it's currently being suppressed with its own filter but if you visit the site for the first time (or delete the corresponding cookie) then you can't actually 'click' on any video. weirdly you can still right click but that seems like a weird bypass.
> > of course you could just refresh the page and then you're allowed to freely click on anything but the cookie is deleted every 24 hours. seems like small nuisance if you ask me.
> 
> I can click on the video normally at the first time (open in Private Window and Firefox set to clearing cookies and history after exit).

firefox thing? try chrome and delete any cookie named `pg_interstitial_v5`. then after loading the page and trying to click any video on the homepage for example you will be unable to left-click open anything.

**Comment by stephenhawk8054** [comment]
> firefox thing? try chrome and delete any cookie named `pg_interstitial_v5`. then after loading the page and trying to click any video on the homepage for example you will be unable to left-click open anything.
> 
> in case anyone is interested in the script `https://assets.sb-cd.com/static/desktop/gen/universal.master.5.56.main.packed.b33a9a8b.js`.

Ah right, I didn't realize you were using Chrome above. Yeah I confirm it happens to me in Chrome too.

**Comment by stephenhawk8054** [comment]
@dumbusernameidk Can you check if this filter works or causes any breakages for other functions of the site?
`spankbang.com##+js(set, chrome, undefined)`

**Comment by dumbusernameidk** [comment]
from the little stuff i tested it seems like everything still functions.

**Comment by stephenhawk8054** [comment]
> from the little stuff i tested it seems like everything still functions.

Does it solve the issue (have to click twice) on your side?

**Comment by dumbusernameidk** [comment]
> > from the little stuff i tested it seems like everything still functions.
> 
> Does it solve the issue (have to click twice) on your side?

late reply but yeah. seems to have fixed the issue of not being able to click (bypassing the invisible interstitial page).

**Comment by AntiAdvert** [comment]
**Warning: NSFW domain name**

```
spankbang.com##.livecamv2-rotate
spankbang.com###interstitial_div_v2
spankbang.com##.video-item:has([src*="://deliver."])
||trans2bay6742.spankbang.com^$xhr,1p
||strpst.com^$domain=spankbang.com
```

https://github.com/AdguardTeam/AdguardFilters/issues/134650

if there's no reproduction of the issue, did you search on the site?
