### ISSUE TITLE
Gelbooru.com header being blocked

### ISSUE THREAD

**Issue by lowercase-donkey** [uBlockOrigin/uAssets#603]
### URL(s) where the issue occurs

`https://gelbooru.com/index.php?page=post&s=view&id=3787796` Website NSFW, this image is ok though.  Problem is across all images on gelbooru.

### Describe the issue

uBlock filter blocks:
```
Static filter ||gelbooru.com^$inline-script found in:

    uBlock filters
```

### Screenshot(s)
The default behavior, filtering $inline-script, blocks this functional blue header from appearing.
![capture](https://user-images.githubusercontent.com/28416282/28762588-ca337878-7585-11e7-88c7-6f2fd4db9e36.PNG)

### Versions

- Browser/version: [FF 54.0.1]
- uBlock Origin version: [1.13.8]

### Settings

- [None that apply here, pretty vanilla]

### Notes

I tried to make a `gelbooru.com * * allow` rule with many variations but it won't take.  I may be doing something wrong.  However, the bar does come back when I disable uBlock for the page.  However, so do ads.

**Comment by kowith337** [comment]
Try purge uBlock Filter cache, in my side, I didn't see this filter block the inline-script.

**Comment by gorhill** [comment]
> I tried to make a `gelbooru.com * * allow` rule with many variations but it won't take. I may be doing something wrong. However, the bar does come back when I disable uBlock for the page.

There are **two** filters causing the issue here.

`gelbooru.com * * allow` does prevent inline script filter from being blocked, as expected.

However it's not just the inline script filter which is causing the issue, it's also the EasyList filter `|https://$script,domain=gelbooru.com` which causes the resource `https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js` to be blocked.

So you will also need a filter or rule to unblock `https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js` on `gelbooru.com`.

So try:

    @@||gelbooru.com^$inline-script
    @@||.googleapis.com^$domain=gelbooru.com

Please see/report if this causes ads to come back.


Advice: use uBO's logger to diagnose filtering issue, the console is not that helpful in such case. With the logger you can see what gets blocked/unblocked and act on it to find out what works.

**Comment by lowercase-donkey** [comment]
That did the trick.

Oddly, I had disabled Easylist earlier and was still having problems.  This is with Easy list disabled, and the rule I described applied:

![asdfasdfaf](https://user-images.githubusercontent.com/28416282/28793614-8868ca48-7601-11e7-8814-b082e0e9e410.PNG)
![adsfasef](https://user-images.githubusercontent.com/28416282/28793617-89bf77f2-7601-11e7-825c-8fc67cc6a89a.PNG)

**Comment by gorhill** [comment]
> the rule I described applied

Where did you enter that rule in uBO?

**Comment by lowercase-donkey** [comment]
Entering any of those into "my rules" and committing them to permanent failed to have an effect.  Yes, I confirmed they didn't disappear.  They showed up under permanent rules.

Then I disabled Easylist, still had a problem.  Then I came here.

Now with :
```
@@||gelbooru.com^$inline-script
@@||ajax.googleapis.com^$script,domain=gelbooru.com
```
it works fine, even when I turn Easylist back on.

**Comment by gorhill** [comment]
> committing them to permanent

You don't need to make them permanent. Also, why not use the dynamic filtering panel to just create the appropriate `allow` rule with one single click? Only explanation I can see is that you manually created an incorrect rule which was rejected by uBO.

**Comment by kowith337** [comment]
Allowing `inline-script` and jQuery scripts from `ajax.googleapis.com` can solve this.
```
@@||ajax.googleapis.com/ajax/libs/jquery$script,domain=gelbooru.com
@@||gelbooru.com$inline-script,first-party
```
![screenshot 6](https://user-images.githubusercontent.com/16535467/28807093-e4996a42-769d-11e7-90ef-0487662811c9.png)

But I don't know is any point to allow bootstrap scripts too?
`@@||bootstrapcdn.com/bootstrap$script,domain=gelbooru.com`
Maybe some function to use that site (especially when you're logged in) will depend on that...

And I've found missed ad above image list now, what to do next?
![screenshot 3](https://user-images.githubusercontent.com/16535467/28807219-8b6d1102-769e-11e7-8365-01412baad917.jpg)

**Comment by lowercase-donkey** [comment]
That's pretty easy: I didn't know about the dynamic filtering panel.  Didn't know till I just googled it that there was an advanced user mode.  I'm not sure why the user friendly UI way is hidden from user while manual rules are exposed, but that reversal left me assuming I had to learn the text based approach.
