### ISSUE TITLE
can not block unencrypted redirects

### ISSUE THREAD

**Issue by FlorianSteenbuck** [uBlockOrigin/uAssets#6030]
### URL(s) where the issue occurs
everywhere

### Describe the issue
I want to block all unencrypted http traffic, even redirects. This is totally important because every browser got a http:// as prefix when you not manually type in the protocol. Also you could redirected to a unencrypted website.

Please do not compare the Internet with the mobile network. This is just a stupid block argument that everyone tries use to defend voip. This is the reason because almost every internet voice/video chat room or id verification is broken. 

Please do not say it is a part of the http protocol. This argument is mainly used by people who think it is a good idea to follow every norm, to stay "safe". Which totally bullshit as webrtc starts with unencrypted connections to end a dtls connection. Is it a good idea to follow the unencrypted part of the webrtc norm ? no no no no of course no. You are the reason the Internet is not in a safe encrypted state today.

### Screenshot(s)

nope

### Versions

- Browser/version: Firefox Quantum 68.0.1
- uBlock Origin version: uBlock Origin v1.21.2

### Settings

Filters
- `|http:*`

Whitelist
- `127.0.0.1`
- `Router Gateway IPv4`

### Notes

Even when I got a unencrypted connection that redirects to a unencrypted connection it got executed.

**Comment by llacb47** [comment]
Not a filter issue

**Comment by mapx-** [comment]
to be discussed here:
https://www.reddit.com/r/uBlockOrigin/

**Comment by FlorianSteenbuck** [comment]
@llacb47 any reason why this is not a filter issue ?

**Comment by gwarser** [comment]
Try `|http:*$all`

**Comment by FlorianSteenbuck** [comment]
@gwarser working perfectly

**Comment by llacb47** [comment]
> @llacb47 any reason why this is not a filter issue ?

I misunderstood the question, sorry. However, this repo is for issues with uAsset's filter lists, not with writing filters in general.
