### ISSUE TITLE
[Annoyance, countdown] foodyindians.in

### ISSUE THREAD

**Issue by llacb47** [uBlockOrigin/uAssets#6032]
### URL(s) where the issue occurs

`http://foodyindians.in/ObOHi`

### Describe the issue

Duplicate of https://github.com/uBlockOrigin/uAssets/issues/6022

Annoyance timer on url shortener site, cannot be bypassed with `nano-setInterval-booster` because of server-side validation.

Also, there is an annoyance modal.

### Screenshot(s)

![Annoyance timer](https://user-images.githubusercontent.com/16567977/62330933-3dfc2f00-b488-11e9-9c19-735a9d13f72e.png)

![Annoyance modal](https://user-images.githubusercontent.com/16567977/62331029-8f0c2300-b488-11e9-8b0f-90cfddcd25c5.png)

### Versions

- Browser/version: Tested in Firefox Quantum 68.0.1
- uBlock Origin version: N/A, using Nano Adblocker 1.0.0.123

### Settings

- Tested with default settings in Firefox

### Notes

Add these filters:
```
! for timer onfocus annoyance
foodyindians.in##+js(set-constant.js, blurred, false)
! for modal annoyance
foodyindians.in##+js(abort-current-inline-script.js, $, modal)
```

**Comment by JobcenterTycoon** [comment]
This site have Anti-Adblock too

**Comment by llacb47** [comment]
Can't reproduce, test these filters and can you add a screenshot?
```
foodyindians.in##+js(bab-defuser.js)
foodyindians.in##+js(abort-on-property-read, app_vars.force_disable_adblock)
```

**Comment by llacb47** [comment]
Another domain `clk.ink` test link `https://clk.ink/4f5hnrGd`

Add `clk.ink##+js(set-constant.js, blurred, false)`

**Comment by okiehsch** [comment]
@llacb47 there is an existing `clk.ink` issue https://github.com/uBlockOrigin/uAssets/issues/4707
This is not a big deal but commenting in that thread is preferable from an organizational point. 😉

**Comment by gwarser** [comment]
New domain `foodyindians.in` -> `dailyworldupdates.in`
