### ISSUE TITLE
dikmean.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#6035]
URL(s) where the issue occurs

`https://dikmean.com/q1yOEiC`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 75 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.21.6

Settings

Default

**Comment by llacb47** [comment]
Can't reproduce.

Popups, fake download button, and `onfocus` annoyance:
```
dikmean.com##+js(window.open-defuser.js)
dikmean.com##.blog-content > p:has(img)
dikmean.com##+js(set-constant.js, blurred, false)
```

**Comment by okiehsch** [comment]
Can't connect.
![image](https://user-images.githubusercontent.com/16838044/62335249-69ecd400-b4cb-11e9-9c66-8bef1f650260.png)

**Comment by llacb47** [comment]
Screenshot: 
![image](https://user-images.githubusercontent.com/16567977/62335936-f1225380-b49b-11e9-971f-a8b189450158.png)

**Comment by okiehsch** [comment]
Thanks.
