### ISSUE TITLE
motorauthority.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#604]
### URL(s) where the issue occurs

`http://www.motorauthority.com/news/1107647_feel-the-rawness-of-the-ferrari-fxx-k-as-it-takes-on-daytona`

### Describe the issue

Youtube video doesn't display.

### Notes

Disabling EasyList fixes it.

**Comment by okiehsch** [comment]
I can't reproduce, the Youtube video plays fine on my end.
Tested with Chrome and Firefox.

**Comment by terrorist96** [comment]
Sometimes it will load, but if I do `ctrl + F5`, it won't load. It's weird.
It looks like this for me:
![image](https://user-images.githubusercontent.com/12802056/28799583-31f5d258-7617-11e7-8475-8ea8cdcab9b6.png)

**Comment by okiehsch** [comment]
Does not matter if I bypass the cache or not, I can't reproduce, the video "shows up" and plays without issue on my end.

**Comment by gorhill** [comment]
Can't reproduce either, Chrome, Nightly + default settings.

**Comment by terrorist96** [comment]
Interesting.. I'm looking through the log of when I load the page, and the video loads, and when I bypass cache and reload (and video doesn't load), and the first page load actually has more stuff being blocked than the second. Everything blocked in the second is also blocked in the first, so I don't know..
Doing a regular refresh fixes it for me. But then bypassing cache and refreshing breaks it again. If no one else can reproduce, I'll just close this.
