### ISSUE TITLE
gpcoder.com

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#6041]
### URL(s) where the issue occurs

- `https://gpcoder.com/4365-huong-dan-java-design-pattern-abstract-factory/`

### Describe the issue

- Anti-Adblock Script - Admiral

### Versions

- Browser/version: Firefox 68.0.1
- uBlock Origin version: 1.21.2

### Settings

- Default filters

### Notes

Annoyance.

**Comment by okiehsch** [comment]
Why do you think this is Admiral?
It is not on my end.

**Comment by llacb47** [comment]
Because it is:
` <script>!(function(o,n,t){t=o.createElement(n),o=o.getElementsByTagName(n)[0],t.async=1,t.src="https://steadfastsystem.com/v2/0/..."...</script>`

**Comment by okiehsch** [comment]
````
"text/javascript">var anOptions ={"anOptionChoice":"2","anOptionStats":"1","anOptionAdsSelectors":"adsbygoogle","anOptionCookie":"1","anOptionCookieLife":"1","anPageRedirect":"","anPermalink":"undefined","anOptionModalEffect":"fadeAndPop","anOptionModalspeed":"350","anOptionModalclose":true,"anOptionModalOverlay":"rgba( 0,0,0,0.8 )","anAlternativeActivation":false,"anAlternativeElement":"","anAlternativeText":"<p><strong>AdBlock detected!<\/strong><\/p>\n<p>Please add <a title=\"https:\/\/getadmiral.com?utm_medium=plugin&utm_campaign=abn&utm_source=abnlinks\" href=\"https:\/\/getadmiral.com?utm_medium=plugin&utm_campaign=abn&utm_source=abnlinks\" target=\"_blank\">www.getadmiral.com<\/a> to your adblocking whitelist or disable your adblocking software.
````
This is causing the message on my end.
