### ISSUE TITLE
How disable SmoothScroll without html filtering?

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6047]
### URL(s) where the issue occurs

`https://spece.it/tworzymy-bootowalny-pendrive-np-instalator-systemu-windows-wbudowanym-programem-diskpart/`

### Describe the issue

Smooth scroll break scrolling with mouse roller - I cannot scroll more than 1 line of text. 

### Screenshot(s)

N/A

### Versions

- Browser/version: FX 68.0.1
- uBlock Origin version: 1.21.7.3

### Settings

- Default

### Notes

`spece.it##^script:has-text(SmoothScroll)`

```js
<script type='text/javascript'>
/* <![CDATA[ */
var HUParams = {
    "_disabled": [],
    "SmoothScroll": {
        "Enabled": true,
        "Options": {
            "touchpadSupport": false
        }
    },

// (...)

};
/* ]]> */
</script>
```

**Comment by llacb47** [comment]
`spece.it##+js(abort-on-property-write.js, HUParams)`

**Comment by krystian3w** [comment]
Both break slider on top home page. I suppose no possible fix without userscript 😣.

**Comment by llacb47** [comment]
@krystian3w try `spece.it##+js(set-constant.js, smoothScroll, noopFunc)`

**Comment by krystian3w** [comment]
OK this works OK. 

But maybe report this to Logitech? If I disabled `Logitech SetPoint` addon problem also gone...

> ![obraz](https://user-images.githubusercontent.com/35370833/62427881-3217a380-b6fa-11e9-8190-ff203208ca09.png) |
> --- |

**Comment by krystian3w** [comment]
`http://www.thebat.com.pl/` Also bugged with Logitech addon...

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/14330
