### ISSUE TITLE
xooimg.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#6048]
### URL(s) where the issue occurs

`https://xooimg.com/img-59fc96b33ab38.html`

### Describe the issue

Anti-Adblock

### Versions

- Browser/version: Firefox 68.0.1
- uBlock Origin version: uBlock Origin v1.21.2

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3465351/Settings.txt)

**Comment by AntiAdvert** [comment]
![image](https://user-images.githubusercontent.com/117537631/200176595-d066fdf0-4ff2-416e-84a9-d4e3a8067cad.png)
