### ISSUE TITLE
Wildcard (*) doesn't block 

### ISSUE THREAD

**Issue by Lightningblade** [uBlockOrigin/uAssets#605]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[https://9anime.to/watch/hunter-x-hunter-2011.295/nkz24l (or any other site with their player)]`

### Describe the issue

The site is full of ads and shit so first of all be careful before you go to it. 
There is an overlay that appears every ~hour invisible but covering the whole site so you can only click on it. its a simple a href="Shady virus domains", so i used element picker to block them a few times. 
It's always domains like this:
da60995df247712.com/1308557.html
da12793ef123891.com/1308557.html
etc etc some hex number.

So to automaticly block them i want to use the * instead of the shifting domain names like from:
9anime.to##a[href="//da60995df247712.com/1308557.html"]
9anime.to##a[href="//*.com/1308557.html"]

This doesn't work although it says in the documentation:

Wildcard character
This stands for any number of characters

Is there a way for uBlockOrigin to block this?

(Optional) Also what happens if someone would make a * in a URL that's necessary?

### Versions

- Browser/version: [FF 54.0.1 (64-bit)]
- uBlock Origin version: [ 1.13.8]

### Settings

- [More filters (my own and third party) don't think it really matters]

**Comment by gwarser** [comment]
https://adblockplus.org/en/filters#elemhide_attributes

**Comment by okiehsch** [comment]
I will fix the root cause of your popup isssue.

**Comment by uBlock-user** [comment]
`9anime` acting up again

**Comment by uBlock-user** [comment]
@okiehsch 

9anime anti adblock acting up again - https://i.gyazo.com/0e404e32181031d5314314487f4827c6.png

https://www4.9anime.is/watch/tokyo-ghoul.7w06/m663ov

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/7d4e05e118c9b51d07b323b5b8273021a70cf7ee

**Comment by mapx-** [comment]
No anti adb message here (after updating ublock filters)

**Comment by okiehsch** [comment]
You have to wait 5 seconds before the video starts after first load. If you click the video immediately there will be an anti adblock message, which I can't circumvent without breaking the video.

**Comment by dubesor** [comment]
Waiting makes zero difference on my end. Waited 5 seconds, 10 seconds, doesn't matter, always message. Firefox, chrome as well as restore to factory settings+renew all filters (purge and update), So, no custom issue. I tested on Attack No.1 EP1

**Comment by okiehsch** [comment]
Well, I do not know what to tell you, if I update uBO-filters, or manually add
`9anime.is#@#script:inject(setTimeout-defuser.js, (), 5000)`
it works on my end.
Example link: `https://www4.9anime.is/watch/shiyan-pin-jiating-chinese-dub.l9q3/93pmjm`

![unbenannt](https://user-images.githubusercontent.com/16838044/39234999-0f50ed88-4875-11e8-963f-cb976ba97961.JPG)

**Comment by okiehsch** [comment]
>  I'm not sure what you mean by wait 5 seconds

You have to wait until the sad looking smiley appears.

**Comment by uBlock-user** [comment]
Added that exception filter, no change whatsoever.

> You have to wait until the sad looking smiley appears.

That thing never appears, I disabled cosmetic filtering completely.

The only way I can watch videos is if I whitelist the entire first party resources, which pulls ads if done.

**Comment by okiehsch** [comment]
The smileys appear they are blocked by:
````
9anime.is##div[class*="message"]
Fanboy’s Enhanced Tracking List
````
or 
````
9anime.is##.this-message-does-not-harm-to-you-dont-remove-it
Adguard’s Annoyance List
````
if I enable one of those lists, I will also get the anti-adblock message.

**Comment by Lightningblade** [comment]
I started this Topic because there was an invisible overlay on the entire page that was clickable, and would redirect you to probably some shady site. Well, GL getting your problems solved, I haven't seen my problem in at least half a year.

**Comment by uBlock-user** [comment]
@Lightningblade The filter you were looking for is `9anime.to##a[href^="//"]`

**Comment by uBlock-user** [comment]
@okiehsch 9anime acting up again!

**Comment by I92** [comment]
![ucscreenshot20180521212501](https://user-images.githubusercontent.com/39501477/40329009-19524126-5d40-11e8-87b4-2a85267736ae.png)
TI WILL WORK <<O.K.L.M>>

**Comment by dashbash5** [comment]
how come it is working?

**Comment by dashbash5** [comment]
it stoped working telling me to disable adblock

**Comment by okiehsch** [comment]
All 9anime issues post in https://github.com/uBlockOrigin/uAssets/issues/2333#issuecomment-390803246
from now on, no need for half a dozen different issues for one site.
