### ISSUE TITLE
pichau.com.br

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#6051]
### URL(s) where the issue occurs

`https://www.pichau.com.br/computadores`

### Describe the issue

Annoyance: jumpy scrolling at the top.

### Versions

- Browser/version: Firefox stable
- uBlock Origin version: 1.21.2

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin lists

**Comment by okiehsch** [comment]
`pichau.com.br##+js(addEventListener-defuser.js, scroll)`
This will break the sticky bar at the top.

**Comment by adranger** [comment]
@okiehsch okay, thanks for looking into it.
