### ISSUE TITLE
bitcoinera.com

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#6053]
### Describe the issue

From the looks of it, it's a hardcore scam service that is investing huge efforts into writing fake news articles in numerous languages and target countries around the world, in which celebrities "endorse" using them to "invest" in Bitcoin. There are a lot of reports of people being scammed by significant amounts of money by them.

Explanations from scam investigators:

* Anglosphere: https://scamcryptorobots.com/bitcoin-era-review-scam/
* Norway (PS: The article author's grammar is so utterly bad that there's no way it can be Google-translated): https://www.datahjelperne.no/bitcoin-svindel-oker-i-omfang-pa-facebook/

It doesn't seem to be covered by any uBO-included list that I'm aware of, so I decided to submit it to you guys, unless you want to (and know how to) forward this submission to another list maker.

### URL(s) where the issue occurs

N/A, but is most often seen on `Facebook`.

### Screenshot(s)

The explanation links above provide several on-point screenshots.

### Versions

- Browser/version: Chrome 76.0.3809.87 64-bit for Windows
- uBlock Origin version: Nano Adblocker 1.0.0.123 + Nano Defender 15.0.0.158

### Settings

![image](https://user-images.githubusercontent.com/22780683/62533949-2afeab80-b848-11e9-9bd7-5a42eaf4e99f.png)

### Notes

My suggested entry: `||bitcoinera.com^$doc,domain=~ Warning displayed due to: Bitcoin scam fraudsters.`

If you guys want to expand *uBlock Filters - Badware Risks* into dealing with altcoin fraud sites on a large/permanent basis, I also suggest looking into if these sites are blockworthy (Note that all source articles are in Norwegian, but all or nearly all of these scams seem to target multiple countries):

```
! As mentioned in https://www.dagbladet.no/kultur/jeg-blir-hver-dag-kontaktet-av-folk-som-faktisk-tror-pa-denne-svindelen/70487841
breakoutstory24.com
thefivereport.online
abafort.us
! https://www.tv2.no/nyheter/10493336/
rnbinance.com
brightertrade.com
! https://www.nrk.no/ytring/1.14496024
cost2buy.net
! https://www.faktisk.no/faktasjekker/YAb/nei-olav-thon-har-ikke-investert-850-millioner-kroner-i-bitcoin-program
101mesh.com
gokkw.com
earnmoneyglobal.com
! https://www.datahjelperne.no/stein-erik-hagen-og-fredrik-skavlan-misbrukes-i-bitcoin-svindel/
trendyn.me
```

**Comment by mapx-** [comment]
`bitcoinera.com` seems to be down ?

**Comment by mapx-** [comment]
However, you could prepare a PR
