### ISSUE TITLE
tvnow.de

### ISSUE THREAD

**Issue by nifker** [uBlockOrigin/uAssets#6054]
### URL(s) where the issue occurs

https://www.tvnow.de

### Describe the issue

When starting a VOD its not playing and just flickering with light blue color.

### Screenshot(s)

![Screenshot_07-08-2019_00-47-56](https://user-images.githubusercontent.com/5812753/62582540-202a3200-b8ad-11e9-9fa8-821ebd561364.png)

### Versions

- Browser/version: FF 60.8.0ESR
- uBlock Origin version: [here]

### Settings

DEFAULT

**Comment by nifker** [comment]
The ad seems to be showed using a script from 2mdn.net

**Comment by JobcenterTycoon** [comment]
The video ads are back again.
Example link: `https://www.tvnow.de/serien/hilf-mir-jung-pleite-verzweifelt-2506/2019-07/episode-238-der-schoene-schein-242323`

Browser: Firefox 68.0.1

@okiehsch @lain566

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by lain566** [comment]
I can't reproduce video ads either.

**Comment by JobcenterTycoon** [comment]
I tried again with default settings and with a fresh uBlock Origin addon but i still get ads. Steps to reproduce:

1. Install uBlock origin on firefox
2. update all filter lists
3. go to tvnow

**Comment by lain566** [comment]
Yeah, now the player is broken for me, this morning it worked fine.
Try these filters, Does work for you?
```
tvnow.de#@#+js(abort-on-property-read.js, hdUtils.loadFile)
tvnow.de##+js(abort-on-property-read.js, ext506384.loadFile)
```

**Comment by JobcenterTycoon** [comment]
yes it works

**Comment by jannismain** [comment]
I'm still seeing video ads (preroll, in between) [here](https://www.tvnow.de/shows/kitchen-impossible-7887/2019-10/episode-3-tim-maelzer-vs-klaus-erfort-1454670)

Can you verify, that it is still working for you?

**Comment by mapx-** [comment]
Can you see this filter in the logger ?

`tvnow.de##+js(json-prune, enabled, testadtags)`

**Comment by okiehsch** [comment]
See https://github.com/uBlockOrigin/uAssets/issues/6349#issuecomment-535431715

Still works on my end, if you don't want to use the dev version you will have to wait until the next stable release.

**Comment by JobcenterTycoon** [comment]
The Video Ads are back again

`https://www.tvnow.de/serien/hilf-mir-jung-pleite-verzweifelt-2506/2019-10/episode-10-ich-bin-anders-schrei-doch-wenn-du-willst-der-superheld-die-rache-der-schlaegerbraut-1890009`

**Comment by JobcenterTycoon** [comment]
Now i have the same problem like https://github.com/uBlockOrigin/uAssets/issues/5995

Do you know any `+js` filter to fix that? Or is that a bug in uBlock Origin?

**Comment by mapx-** [comment]
Does this filter work for you 
`tvnow.de##+js(json-prune, enabled, testhide)`

**Comment by JobcenterTycoon** [comment]
Yes this work, thank you.

**Comment by JobcenterTycoon** [comment]
Video ads are back again

`https://www.tvnow.de/serien/familien-im-brennpunkt-247/2019-12/episode-122-mutter-wirft-schwangere-teenietochter-aus-dem-haus-2599239`

**Comment by okiehsch** [comment]
I can't reproduce the pre roll ads are successfully redirected by
![image](https://user-images.githubusercontent.com/16838044/70981132-dfd98c80-20b4-11ea-854c-0bd6f1b36440.png)
on my end usin Chromium or Firefox.

**Comment by JobcenterTycoon** [comment]
ok now it works

**Comment by lain566** [comment]
@okiehsch  I could reproduce pre roll ads when trying to play the next Kapitel, but only once, I can no longer reproduce pre-roll ads.

`tvnow.de##+js(json-prune, server.0)`
this filter blocks ads, at least you will not see media file requests in the logger, you can add it if you want.

**Comment by JobcenterTycoon** [comment]
The player freeze when the player try to play a ad in the middle of the video. The new filter will fix that
