### ISSUE TITLE
Ladbible.com anti-adblock

### ISSUE THREAD

**Issue by C0nw0nk** [uBlockOrigin/uAssets#6055]
### URL(s) where the issue occurs

`http://www.ladbible.com/news/news-builder-cant-go-anywhere-because-he-looks-too-much-like-brad-pitt-20190806`

### Describe the issue

Blank white pages anti adblock it seems.

### Versions

- Browser/version: Firefox quantum latest
- uBlock Origin version: Latest

### Settings

Default

### Notes

Anti adblock blank white pages on articles.

`http://www.ladbible.com/news/news-builder-cant-go-anywhere-because-he-looks-too-much-like-brad-pitt-20190806`

**Comment by mapx-** [comment]
I get no blank page.
Could you test
`@@||ladbible.com/assets/js/ads.js$script,1p`

**Comment by C0nw0nk** [comment]
@mapx- 

Did not work :( its so strange.

**Comment by mapx-** [comment]
- open the logger, select all blocked items
- refresh the page
- post here all blocked items

**Comment by C0nw0nk** [comment]
@mapx- 

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 | `\|\|static.quantcast.mgr.consensu.org/v23/cmpui-popup.js$script,domain=www.ladbible.com` | -- | `www.ladbible.com` | 3 | script | `https://static.quantcast.mgr.consensu.org/v23/cmpui-popup.js` |
| +2 | `\|\|static.quantcast.mgr.consensu.org/v23/cmpui-popup.js$script,domain=www.ladbible.com` | -- | `www.ladbible.com` | 3 | script | `https://static.quantcast.mgr.consensu.org/v23/cmpui-popup.js` |
| +2 | `\|\|api.quantcast.mgr.consensu.org^$domain=www.ladbible.com` | -- | `www.ladbible.com` | 3 | xhr | `https://api.quantcast.mgr.consensu.org/CookieAccess` |
| +1 | /fbevents.js | -- | `www.ladbible.com` | 3 | script | `https://connect.facebook.net/en_US/fbevents.js` |
| +1 | google-analytics.com/analytics.js | << | `www.ladbible.com` |  | script | `https://www.google-analytics.com/analytics.js` |
| +1 | \|\|google-analytics.com^ | -- | `www.ladbible.com` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +1 | /assets/ads. | -- | `www.ladbible.com` | 1 | script | `http://www.ladbible.com/assets/ads.e2b73c95b113eca2e2ec.js` |
| +1 | \|\|native.ai^$third-party | -- | `www.ladbible.com` | 3 | script | `https://cdn.native.ai/js/current/nativeai.js?1564617600000` |
| +1 | /atrk.js | -- | `www.ladbible.com` | 3 | script | `https://d31qbv1cthcecs.cloudfront.net/atrk.js` |
| +1 | /assets/ads. | -- | `www.ladbible.com` | 1 | script | `http://www.ladbible.com/assets/ads.e2b73c95b113eca2e2ec.js` |
| +1 | \|\|permutive.com^ | -- | `www.ladbible.com` | 3 | script | `https://cdn.permutive.com/c8ee9446-97ed-462f-a5e9-1af66c8e9104-web.js` |
| +1 | \|\|googletagmanager.com/gtag/$third-party | -- | `www.ladbible.com` | 3 | script | `https://www.googletagmanager.com/gtag/js?id=UA-1645798-19` |
| +1 | \|\|adsafeprotected.com^ | -- | `www.ladbible.com` | 3 | script | `http://cdn.adsafeprotected.com/iasPET.1.js` |
| +1 | \|\|indexww.com^ | -- | `www.ladbible.com` | 3 | script | `http://js-sec.indexww.com/ht/p/184653-8082876442921.js` |
| +1 | googletagservices.com/gpt.js | << | `www.ladbible.com` |  | script | `http://www.googletagservices.com/tag/js/gpt.js` |
| +1 | \|\|googletagservices.com^ | -- | `www.ladbible.com` | 3 | script | `http://www.googletagservices.com/tag/js/gpt.js` |
</details>

**Comment by C0nw0nk** [comment]
If it helps i see the page loaded for like 2 seconds then it all goes blank like a script is deleting the html content.

**Comment by mapx-** [comment]
- reset uBo to default settings
- close / reopen your broswer
- test again

**Comment by ghajini** [comment]
I can reproduce, page show for 2sec and goes blank then

**Comment by okiehsch** [comment]
I also can't reproduce.

**Comment by dumbusernameidk** [comment]
I was able to produce it once so I disabled UBO then tried again with it back on and the site loads fine now.

**Comment by C0nw0nk** [comment]
Using ublock to disable all javascript on that site is the only soloution i could find i uninstalled ublock re-installed it all default still same issue.

**Comment by gwarser** [comment]
`body` height is set to 0 by something.

**Comment by gwarser** [comment]
Exception for `http://www.googletagservices.com/tag/js/gpt.js` helps.

**Comment by okiehsch** [comment]
Weird, now I can reproduce.
The suggested exception works on my end.

**Comment by gwarser** [comment]
Redirecting also helps `||www.googletagservices.com/tag/js/gpt.js$script,domain=www.ladbible.com,redirect=noopjs`

**Comment by okiehsch** [comment]
Interesting I tried 
````
||googletagservices.com/tag/js/gpt.js$script,redirect=googletagservices.com/gpt.js,domain=ladbible.com
````
and that redirection does not work on my end.

**Comment by okiehsch** [comment]
The fix will not work if one uses `uBlock filters – Experimental`.
