### ISSUE TITLE
puromarketing.com

### ISSUE THREAD

**Issue by pizza90** [uBlockOrigin/uAssets#6059]
### URL(s) where the issue occurs

`https://www.puromarketing.com/13/32284/omnicanalidad-obsesion-para-marcas.html`

### Describe the issue

AD banners

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [v1.21.6]

### Settings

- Default / Spanish

**Comment by pizza90** [comment]
ad banners in image and text

**Comment by mapx-** [comment]
You should report at adguard repository (the other spanish list has no active maintainer)
https://github.com/AdguardTeam/AdguardFilters/issues

However, add:
```
###PuCol
###PuMedium
###PuHeader
```

@Alex-302
