### ISSUE TITLE
bild.de - Anti adb

### ISSUE THREAD

**Issue by spec1re** [uBlockOrigin/uAssets#606]
Since the last weekend bild.de is blocking Ad-blocker again

### URL(s) where the issue occurs

http://www.bild.de/

### Describe the issue

Redirected to block notice.

![grafik](https://user-images.githubusercontent.com/11883076/28816552-c3ad5518-7694-11e7-9b3d-ddd3b70aa6c0.png)

### Versions

- Browser/version: Firefox 54.0.1 (32-Bit)
- uBlock Origin version: v1.13.8
- uBlock Protector List up2date

Chrome 60 with uBlock Protector works just fine

**Comment by okiehsch** [comment]
Works fine with default settings.
If you use the `uBlock Protector List` **without** the `uBlock Protector Extension` you will indeed
not be able to use `bild.de`.
The filter `bild.de##script:inject(abort-on-property-read.js, de.bild.cmsKonfig.a.b.a)` **still** fixes the 
anti-adblock issue and is part of `uBO-filters`
The filter `bild.de#@#script:inject(abort-on-property-read.js, de.bild.cmsKonfig.a.b.a)` is part of the
`uBlock Protector List`.

**Comment by ghajini** [comment]
@jspenguin2017, have a look at it

**Comment by jspenguin2017** [comment]
The white list is intentional.

**Comment by jspenguin2017** [comment]
When I said the filter list doesn't work alone, I meant it. I have many integration filters that will cause a lot of problems if uBlock Protector Extension is not installed: https://github.com/jspenguin2017/uBlockProtector/blob/1ec41cb68b06c8d02797bf51206961b12cd63d62/List%20Compiler/List/Rules%20Part%201.txt#L4-L32

**Comment by spec1re** [comment]
Sorry, there is a uBlock Protector Extension for firefox, I tought its just for Chrome? Firefox with default setting and uBlock Protector List do not work here.

Adding this

```
bild.de##script:inject(abort-on-property-read.js, de.bild.cmsKonfig.a.b.a)
bild.de#@#script:inject(abort-on-property-read.js, de.bild.cmsKonfig.a.b.a)
```
to custom filters, doesn't work as well with firefox.

**Comment by jspenguin2017** [comment]
It's not available for Firefox doesn't mean you don't need it.

**Comment by spec1re** [comment]
@okiehsch - Okay, now I got it! Thanks a bunch! :)

**Comment by ghajini** [comment]
This issues can be prevented if ublock protector list is not default in ublock origin becoz every user is not aware that that list is for `chrome only` and is to be used with `ublock protector extension`

**Comment by jspenguin2017** [comment]
It is not on by default. But I think it is good to add "read instruction inside" as I proposed.

**Comment by Snow8** [comment]
I am not sure if this qualifies to post on here or reopen the topic, as I am not sure if this has something to do with uBlock itself or the filterlist.

I have run into the following issue.

As soon as I block "3rd-party" or "3rd-party scripts" I get the following message on bild.de:

![screenshot-2017-8-18 aktuelle nachrichten - bild de](https://user-images.githubusercontent.com/11486958/29446098-af71e65a-83ea-11e7-8736-f963e162cf65.png)

Translation:

> Why do I not see Bild.de?

> A browser plugin is damaging functions on our website, which is why we cannot allow you to access to our content.

> It is possible, that you are using uBlock Origin or a different adblocker. If that is the case, please deactivate it.

I am running Firefox Nightly 57a, run the basic lists + EasylistGermany + Privacy, Social and Multipurpose. But this even happens with just the basic lists + 3rd party global blocking.

Of course I can simply deactivate the the "3rd party" global blocking, but at least would love to get the site to work with "3rd-party scripts" enabled.

Any ideas?

**Comment by gorhill** [comment]
> as I am not sure if this has something to do with uBlock itself or a filterlist.

Neither. This is a support issue, there is nothing to change here at `/uAssets` or at ` /uBlock` -- the rules are strictly yours, you set them as you wish, and you have to be ready to un-break sites broken by your rules.
