### ISSUE TITLE
www.chatta.it - anti adb

### ISSUE THREAD

**Issue by Giova84** [uBlockOrigin/uAssets#6060]
The website in subject is a social network: `www.chatta.it`
As you go on such website with Any AdBlocker enabled, is recognized and you are forcedly redirected to a page [1] which invite you to disable the  AdBlocker: furthermore you are forced to wait 60 seconds: if you disable scripts (eg using noscript addon) this doesn’t occurs, but obviously will break the whole site, which is also composed of  subdomains, like bacheca.chatta.it, messaggi.chatta.it and so on, so a rule I  think should be applied  as *.chatta.it

[1] The page on which you are forcedly redirected is 
`http://www.chatta.it/informazioni/aiuto/sito-gratuito.aspx` 
and if you look at the code of such page, you will notice that such countdown is present as CountDownTimer and remindMeAfterTotMinutes = 30; (in facts, if you wait, you ar not annoyed for 30 mins), but obviously would be better totally get rid of detector

Firefox 68.0.1
uBlock Origin v1.21.2

**Comment by mapx-** [comment]
When are you redirected ? only after logging in ?

**Comment by Giova84** [comment]
Yes, I noticed that occurs after the log in

**Comment by mapx-** [comment]
Test & see if breaks some functionality / page on site
`chatta.it##+js(std, Adv)`

**Comment by Giova84** [comment]
`chatta.it##+js(std, Adv)`
Seems that works OK without break functionality, but I will test it more accurately: if something will go wrong, I will edit this post.

**Comment by mapx-** [comment]
add a new comment, don't edit the same one
