### ISSUE TITLE
up-load.io

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#6063]
### URL(s) where the issue occurs

`https://up-load.io/0jcixnw0dshr/smokepatch19.part01.rar.html`

### Describe the issue

- Anti-Adblock Script
- Popunder Script
- Request for timer boost

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24980766/62803784-60f69680-bab9-11e9-867d-b200d466b3d8.png)

### Versions

- Browser/version: Firefox 68.0.1
- uBlock Origin version: 1.21.2

### Settings

- All Filters

### Notes

From: `https://smokelinks.blogspot.com/p/p19-smokepatch19.html`
Source for countdown: `https://up-load.io/ds1/js/countdown.js?rand=dfgfg`

**Comment by mapx-** [comment]
I get no popup

**Comment by mapx-** [comment]
maybe you could test
`up-load.io##+js(acis, Math, zfgloaded)`

**Comment by theinstantmatrix** [comment]
Getting popunders again, this time coming from an external script

`https://up-load.io/ds1/js/nt.js`

**Comment by ghajini** [comment]
URL= direct URL not available(`up-load.io/download.htmx`, site didn't showed, you have to take it from `mirrorace.com/m/2h8ap`

Issue=

Saying ***skipped countdown*** when clicking create download link

**Comment by ghajini** [comment]
`https://up-load.io/gmk211xdizj3`
Update scriptlet filters.....

**Comment by psonnosp** [comment]
The Disable AdBlock thing is there again. Is it possible to fix it again?
The link that @ghajini posted above still work if you need a referens.

**Comment by mapx-** [comment]
I get no anti adb stuff

**Comment by psonnosp** [comment]
> I get no anti adb stuff

That's odd, may I ask what lists you are using?
Cause I've been trying with enable/disable the ones I have, plus other addons, and can't find out what is causing the notice to appear.

**Comment by mapx-** [comment]
- Use always the **default settings** (when you report an issue)
- Don't use any other blocking addon/ extension
- Provide browser / uBO versions
- After resetting uBO to default => update all the lists ("purge all caches" + "update now")
