### ISSUE TITLE
direct-link.net, link-to.net, direkt-wissen.com

### ISSUE THREAD

**Issue by llacb47** [uBlockOrigin/uAssets#6065]
### URL(s) where the issue occurs

`https://direct-link.net/35228/Despacito`
`https://direct-link.net/28042/Madden`
`https://link-to.net/9879/Abcthg`
`https://direkt-wissen.com/l/1284/SkyPvPMapsetc`

Domains are part of the Linkvertise `https://linkvertise.net/` URL shortening website.

### Describe the issue

Link shortener site with annoyance tasks, captcha, and countdown timers

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Chromium 70.0.3538.110
- uBlock Origin version: N/A

### Settings

N/A

### Notes

Reddit discussion: `https://www.reddit.com/r/uBlockOrigin/comments/cmaoe1/set_javascript_variable/`

The destination URL is hardcoded inside a Vue function. Maybe we need a new scriptlet for running functions onload using `onload` or event listener? Or a scriptlet to set variables constant to any string? It would be a simpler fix due to how the site checks for completion, but here's a workaround with current scriptlets.

```
direct-link.net,link-to.net,direkt-wissen.com##+js(set-constant, app.addonIsInstalled, trueFunc)
direct-link.net,link-to.net,direkt-wissen.com##+js(nano-sib, web_counter)
direct-link.net,link-to.net,direkt-wissen.com##+js(nano-sib, video_counter)
direct-link.net,link-to.net,direkt-wissen.com##+js(nano-sib, countdown)
```

**Comment by okiehsch** [comment]
Who actually uses that crap?
There are countless link shorteners but this one is hilarious.
In order to get to my destination I have to read an article, watch a video, allow push notifications **and** install some obscure extension.
🤣

**Comment by okiehsch** [comment]
I should probably block all of those sites as malicious.

**Comment by okiehsch** [comment]
I also get an anti-adblock message at two of those domains.

**Comment by okiehsch** [comment]
Thanks for investigating, the `https://direkt-wissen.com/l/1284/SkyPvPMapsetc` link does not work on my end after I solve the captcha.
I added your filters anyway, they work fine for the other two domains.

**Comment by llacb47** [comment]
Add `direct-link.net###video_modal > .modal-dialog > .modal-content > .modal-body` to hide the video player?

**Comment by llacb47** [comment]
More filters needed for Firefox @okiehsch:

```
direct-link.net,link-to.net##.redirect-overlay
direct-link.net,link-to.net##+js(nano-setTimeout-booster.js, notification_state, 12000)
! impression tracking (Easylist?)
||direct-link.net^$xmlhttprequest,first-party
||link-to.net^$xmlhttprequest,first-party
@@||direct-link.net/*/click$xmlhttprequest,first-party
@@||link-to.net/*/click$xmlhttprequest,first-party
```

**Comment by llacb47** [comment]
@okiehsch Filters broken... see `https://old.reddit.com/r/uBlockOrigin/comments/d931ex/linkvertise_linktonet_started_detecting_an/`

**Comment by okiehsch** [comment]
Have you tried with an updated `uBO-filters` list?

**Comment by llacb47** [comment]
Just did, I can't get past the add-on and video.

**Comment by okiehsch** [comment]
Sorry, I only noticed the anti-adblock message before the captcha, that was fixed earlier.
For the rest see https://github.com/uBlockOrigin/uAssets/issues/6065#issuecomment-520114591 and https://github.com/uBlockOrigin/uAssets/issues/6065#issuecomment-520114651.
I will add working filters but I won't bother investigating a site I consider malicious.

**Comment by ghajini** [comment]
Offtopic=
Just bypass them
https://github.com/timmyRS/Universal-Bypass

**Comment by ghajini** [comment]
Got antiadblock

`https://linkvertise.com/26117/144.56032313524415/dynamic?r=aHR0cDovLzE2My4xNzIuODMuMTQ1L2RlYi9hcGkvYXBpMjYvP2Fkcz1hSFIwY0Rvdkx6RTJNeTR4TnpJdU9ETXVNVFExTDJSbFlpOWhjR2t2WVhCcE1EVXZQMlJzUFdOaVl6a3pOMlkwWVdGaFpXTmpOUT09`

**Comment by prateekrastogi** [comment]
Despite multiple issues to fix Bing Ads, there has been no response whatsoever and agitation from repo maintainers:
So, referencing my issue here:
https://github.com/uBlockOrigin/uAssets/issues/6887#issuecomment-578509029

Let's name and shame ublock origin until their ego issues get resolved.

**Comment by llacb47** [comment]
@uBlock-user you missed one

**Comment by ghajini** [comment]
Actually it was fixed by some default filters...
Just you have to click ***Discover articles*** , overlay will come then click cancel `×` button.....
***Continue*** button is visible then....
click `Direct Access to Website`......

**Comment by JobcenterTycoon** [comment]
Linkvertise has a new step to do so `data.meta.require_related_topics` need to be added
<img width="400" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/149377422-01bbb7ef-ce92-48a9-a3a0-004f00660128.PNG">
`https://linkvertise.com/225133/Resolution/1`

finished filter: `linkvertise.com##+js(json-prune, data.meta.require_addon data.meta.require_captcha data.meta.require_notifications data.meta.require_og_ads data.meta.require_video data.meta.require_web data.meta.require_related_topics)`
