### ISSUE TITLE
rlslog.net pop up

### ISSUE THREAD

**Issue by aphelion1** [uBlockOrigin/uAssets#6067]
`rlslog.net` 
when i try to watch page 2 in this site a pop up is opened: `d0f85db8ee56f5c6.com`
a fix for this please
chrome 76.0.3809.100 
uBlock Origin
 1.21.6

**Comment by stephenhawk8054** [comment]
Popup when clicking any link below in the site.

URL:
`https://www.rlslog.net/`

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 79004
  cosmetic: 40483
  scriptlet: 16407
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30729-30, now
    ublock-badware: 3708-1, now
    ublock-privacy: 183-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1728-0, now
    easylist: 62917-582, now
    easyprivacy: 26622-481, now
    urlhaus-1: 8106-0, now
    plowe-0: 3684-2, now
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 663 ms
popupPanel: 
  blocked: 2
```
</details>

Using `##+js(nowoif)` makes you need to click on each link twice to load.

Proposed filter:

`rlslog.net##+js(set, window.localStorage, undefined)`

**Comment by mapx-** [comment]
I get a lot of breakages on this site with / without uBO clicking the right side categories for example

**Comment by stephenhawk8054** [comment]
> I get a lot of breakages on this site with / without uBO clicking the right side categories for example

Yeah, the right side looks broken, but the links below or next page (at the bottom) still works fine.

**Comment by okiehsch** [comment]
The layout is broken on my end. Chromium. I don't have a "right side".
![image](https://user-images.githubusercontent.com/16838044/149377079-03e9d1c8-6275-402d-8be9-e344569ef398.png)
![image](https://user-images.githubusercontent.com/16838044/149377347-2207a48f-2fad-48a5-abfb-2050873a4c8b.png)

**Comment by mapx-** [comment]
yeah, randomly I get that corrupt layout on chrome

**Comment by stephenhawk8054** [comment]
Oh, I didn't know that. The site loads fine for me in chromium and edge. However, it doesn't have popup like in Firefox.
