### ISSUE TITLE
Hardcoded "ads" texts

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6069]
`https://www.file-up.org/yzamat3xs0i7`

```
www.file-up.org##.page-wrap.text-center[style="margin-bottom: 20px;"]::first-line:style(color: #0000 !important;)
www.file-up.org##.page-wrap.text-center[style="margin-bottom: 20px;"] > div:not([id]):not([class]):nth-of-type(2)::first-line:style(color: #0000 !important;)
www.file-up.org##.page-wrap.text-center[style="margin-bottom: 20px;"] > div:not([id]):not([class]) > .row > div > .blocktxt::first-line:style(color: #0000 !important;)

```

---

###### Note:

https://caniuse.com/css-rrggbbaa
https://caniuse.com/#feat=css-rrggbbaa

**Comment by mapx-** [comment]
When you report in uAssets please add all the details to **identify what you want to block / hide**

A screenshot could help

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/62834406-fb86df00-bc4b-11e9-97f9-c495f904bf28.png)


fix with CSS3 `::first-line` and black transparent color coded in `#rrbbggaa`

**Comment by krystian3w** [comment]
Also maybe better with `:xpath` if uBO full support override texts: https://developer.ibm.com/answers/questions/323189/xpath-to-change-the-value-of-text-node/

**Comment by gwarser** [comment]
I think, this "arrow" `->` feature is proprietary extension of this https://developer.ibm.com/urbancode/docs/using-update-xml-xpath-step/

**Comment by krystian3w** [comment]
So wait for implemantation in AdGuard Extension.

**Comment by gwarser** [comment]
@mapx- this actually was my idea to hide these words by `::first-line` styling. There does not seem to be another way to select only `ads`.

Krystian asked here: https://github.com/MajkiIT/polish-ads-filter/issues/14379#issuecomment-520224841 (AdGuard issues inside)

I have no idea how AdGuard want to fix this "by `xpath`" without hiding content deeper in DOM tree.

**Comment by krystian3w** [comment]
`font-size: 0` should "disable" select lines.

**Comment by mapx-** [comment]
I cannot see the filters above in the logger (FF)

**Comment by krystian3w** [comment]
Because AG use scriplets (no compatible with uBO) and no body Added these CSS to hide first line.

Or bug in logger with `::first-line` pseudoselector: https://developer.mozilla.org/en-US/docs/Web/CSS/::first-line

**Comment by mapx-** [comment]
@gorhill `::first-line` filters not visible in the logger
