### ISSUE TITLE
topserialy.to

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#607]
Hello,

**URL**

`https://www.topserialy.to/serialy/twin-peaks-s03e12`

**Describe the issue**

anti adblock http://i.imgur.com/mNZRCZb.png

**Versions**

uBlock Origin 1.13.8 / Firefox 54

**Settings**

default settings

**Comment by ghajini** [comment]
got error ''This content can not be displayed'' in ublock off...

**Comment by SMed79** [comment]
classic filters 
```
@@||topserialy.to^$generichide
@@||www.topserialy.to/js/googlead.js$script
```
https://forums.lanik.us/viewtopic.php?p=119586#p119586

**Comment by okiehsch** [comment]
Your screenshot is not an anti-adblock message, it tells you that you are geo-blocked, as am I.

**Comment by SMed79** [comment]
Thank you.
