### ISSUE TITLE
bosch-easycontrol.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6070]
```
https://www.bosch-easycontrol.com/gb/en/easycontrol/overview/
```

Cookie pop-up with locked scrolling

No fixed in Fanboy's Cookie list (no see solutions) and AdGuard Annoyance (no recover scrolling and no remove `.modal-backdrop` - @BlazDT)

![obraz](https://user-images.githubusercontent.com/35370833/62834513-1a867080-bc4e-11e9-899c-abf702e2fea7.png)

---

```
bosch-easycontrol.com###cookielaw, .modal-backdrop
bosch-easycontrol.com##.modal-open:style(overflow: auto !important; padding-right: 0 !important;)
```

**Comment by BlazDT** [comment]
@krystian3w 
Was fixed in other commit for AdGuard meanwhile.
