### ISSUE TITLE
k2nblog anti-adblock adf.ly/oui.io (several redirects): destination mediafire

### ISSUE THREAD

**Issue by Movisivi** [uBlockOrigin/uAssets#6071]
### URL(s) where the issue occurs

`https://k2nblog.com/single-white-day-shine-on-light-mp3/`

`https://k2nblog.com/mini-album-busters-pinky-promise-mp3/`

### Describe the issue

When clicking on the adf.ly link under Mediafire on any given download at K2n, I am redirected to these sites and stonewallled by anti adlblock. Upon disabling adblock, I am forced through 3-4 different landing pages before getting to the download. Ideally, the countdown timer would speed up and prevent any pop unders/redirects

### Screenshot(s)

https://prnt.sc/or9zzm

### Versions

- Browser/version: Firefox Nightly 70.0a1 20190811095640
- uBlock Origin version: 1.20.2

### Settings

https://prnt.sc/ora0ab

**Comment by mapx-** [comment]
anti adb was fixed some days ago, update your lists and test again (I added an anti popups filter)

**Comment by Movisivi** [comment]
Ah beautiful! Works now.
