### ISSUE TITLE
recantodasletras.com.br

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#6073]
### URL(s) where the issue occurs

`https://www.recantodasletras.com.br/gramatica/1616594`

### Describe the issue

Anti-text copy annoyance.

### Versions

- Browser/version: Firefox stable
- uBlock Origin version: 1.21.2

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin lists

**Comment by llacb47** [comment]
Anti right-click.

`||www.recantodasletras.com.br/scripts/licenseman.js`
