### ISSUE TITLE
###bio_ep - detect blocked scroll?

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6076]
https://github.com/uBlockOrigin/uAssets/issues/5953

### broken page:

`https://www.kei.pl/blog/weryfikujemy-rzeczywistego-nadawce/`

Version with locked scrolling.

![image](https://user-images.githubusercontent.com/35370833/63000856-6e719f00-be72-11e9-9f22-ed12dda4c468.png) |
--- |

Website have `a discount code` after few minutes or detect card (in)activity.

---

Maybe accepted fix:

```
##body:not([style*="overflow:hidden"]):not([style*="overflow: hidden"]) #bio_ep
```

**Comment by hawkeye116477** [comment]
There another sites also => `pozyczkabezbanku.pl` and `parkmania.pl`
In Polish Annoyance Filters we are using `##+js(setTimeout-defuser.js, bioEp.showPopup)`
