### ISSUE TITLE
www.chatta.it - insistent cookies consent banner

### ISSUE THREAD

**Issue by Giova84** [uBlockOrigin/uAssets#6077]
On `www.chatta.it`, and occurs  especially  on the subdomain `cerca.chatta.it`
Often appears the cookies consent banner:

https://ibb.co/GMN0znx

I always reject them by clicking on  "Più opzioni" (in english "More options) and  then click on “Accetto”  (in english “I accept”) but this  cookies banner (which, furthermore, cover all the page) insists to appears.

I tried by blocking it by using these rules:
```

cerca.chatta.it##.qc-cmp-consent-content
cerca.chatta.it###qcCmpUi
cerca.chatta.it##.qc-cmp-showing.qc-cmp-ui-container
```

Which works, but the downside is that I can no longer scroll the page because  the scrollbars disappears.

**Comment by mapx-** [comment]
Did you test `fanboy's cookie list` ?
