### ISSUE TITLE
udn.com

### ISSUE THREAD

**Issue by candela97** [uBlockOrigin/uAssets#6078]
### URL(s) where the issue occurs

`https://udn.com/news/story/6811/3989440?from=udn-ch1_breaknews-1-0-news`

### Describe the issue

sidebar ads and ad rows near the bottom

### Screenshot(s)

![註解 2019-08-14 215525](https://user-images.githubusercontent.com/54083835/63027575-cd213200-bedf-11e9-8293-c44f0cf8c391.jpg)

### Versions

- Browser/version: [Chrome 77.0.3865.19 beta]
- uBlock Origin version: [1.21.6]

### Settings

default settings and lists (including EasyList China)

### Notes

`||p.udn.com.tw/upf/2014_banners/Special/*$image` gets rid of the sidebar ads

the current filter in Easylist `/outwebad_` only blocks the request of one of the ad rows, and using `/outwebad` blocks both

**Comment by mapx-** [comment]
report here:
http://abpchina.org/forum/forum.php
