### ISSUE TITLE
bombuj.eu

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#608]
Hello,

**URL**

`http://www.bombuj.eu/online-film-balerina`

**Describe the issue**

anti adblock http://i.imgur.com/wEdngDu.png

**Versions**

uBlock Origin 1.13.8 / Firefox 54

**Settings**

default settings

**Comment by okiehsch** [comment]
No anti-adblock on my end with default setting, i.e `EasyList Czech and Slovak` enabled.
The video is geo-blocked.

**Comment by SMed79** [comment]
Thank you.
