### ISSUE TITLE
filmysign.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6080]
### URL(s) where the issue occurs

`https://filmysign.com/stake-land-2010-hollywood-hindi-dubbed-full-movie-watch-online-free-download/`

### Describe the issue

Popup ads

### Versions

- Browser/version: opera browser stablw
- uBlock Origin version: ubo stable version

### Settings

- uBO's default settings

**Comment by ghajini** [comment]
Fix doesn't work for me

`http://prnt.sc/osxvr1`
`http://prnt.sc/osxw4q`

Firefox android

**Comment by okiehsch** [comment]
I can reproduce a popup using Chromium.
````
filmysign.com##+js(std, [$()
filmysign.com##+js(window.open-defuser)
````
works on my end.

**Comment by mapx-** [comment]
in FF, responsive mode (choosing kindle fire), I get a popup (positioned as the last tab !)
`https://filmysign.com/wp-content/uploads/2017/05/filmysign_logo.png`

The logger shows no popup, your filters don't work either

**Comment by ghajini** [comment]
Filters at
https://github.com/uBlockOrigin/uAssets/issues/6080#issuecomment-521578729

Doesn't work on firefox android

**Comment by ghajini** [comment]
@okiehsch @mapx-
You can test on firefox desktop browser also fix doesn't work either.....

**Comment by okiehsch** [comment]
`|about:$popup,domain=filmysign.com`

**Comment by ghajini** [comment]
Hello @gorhill,@gwarser,@jspenguin2017 devs why the fix
`https://github.com/uBlockOrigin/uAssets/issues/6080#issuecomment-521578729`
doesn't work for firefox browser....

**Comment by krystian3w** [comment]
User on Android:

- Yandex Browser
- Kiwi Browser

?

**Comment by jspenguin2017** [comment]
@ghajini For issues specific to Firefox, contact LiCybora.

**Comment by ghajini** [comment]
@LiCybora.....

**Comment by krystian3w** [comment]
BTW Are you using: 

`https://github.com/LiCybora/NanoDefenderFirefox/releases/download/v15.0.0.158/nano_defender-15.0.0.158-an+fx.xpi`

or

`https://addons.mozilla.org/en-US/firefox/addon/nano-defender-firefox/`

**Comment by LiCybora** [comment]
> 
> 
> Hello @gorhill,@gwarser,@jspenguin2017 devs why the fix
> `https://github.com/uBlockOrigin/uAssets/issues/6080#issuecomment-521578729`
> doesn't work for firefox browser....

Because of CSP, none of scriptlet (+js) can be inject in Firefox (on this site).
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1267027

But... I cannot reproduce any popup as at the time writing this comment.

**Comment by ghajini** [comment]
Popup might be closed on your side by https://github.com/uBlockOrigin/uAssets/commit/a084e2b261bfd99075f96d0a516285cbca1fce79

`https://filmysign.com/why-cheat-india/`

**Comment by krystian3w** [comment]
`about:config` change key to false:

```
security.csp.enable;false
```

**Comment by ghajini** [comment]
Link to reproduce>

`https://filmysign.com/why-cheat-india/`

How adguard filters work perfectly in firefox if page has CSP issue @LiCybora

**Comment by krystian3w** [comment]
Maybe have implemented CSP hacks? 

Latest ViolentMonkey / TamperMonkey has this implemented with warming about possible breakage site.
