### ISSUE TITLE
iqiyi.com [preroll video ad]

### ISSUE THREAD

**Issue by discusssth** [uBlockOrigin/uAssets#6082]
URL: https://www.iqiyi.com/v_19rtkhruvk.html

![image](https://user-images.githubusercontent.com/45059308/63073003-2bd6c200-bf59-11e9-8d45-56ac2cb9a60b.png)

**Comment by uBlock-user** [comment]
`/videos/other^$domain=iqiyi.com`

Does that help ?

**Comment by lain566** [comment]
How about this filter
`iqiyi.com##+js(aopr.js, DOMParser)`

**Comment by discusssth** [comment]
@lain566    works for me , thank you.    It's perfect..

**Comment by discusssth** [comment]
@uBlock-user   it will trigger anti-adblock hint...

**Comment by uBlock-user** [comment]
@discusssth I don't see any anti adblock, that rule is already present in Adguard Base list.

**Comment by discusssth** [comment]
...I didn't subscribe Adguard Base list。。。

**Comment by discusssth** [comment]
@mapx- 
please add  `iqiyi.com##+js(aopr.js, DOMParser)`  into uBlock filters

**Comment by discusssth** [comment]
https://www.iqiyi.com/a_19rrht40ft.html

still have preroll video ad

help  @lain566
