### ISSUE TITLE
clk.* false positive

### ISSUE THREAD

**Issue by DuncanFairley** [uBlockOrigin/uAssets#6086]
### URL(s) where the issue occurs

`http://clk.dev# http://clk.csr#`

### Describe the issue

Our internal-only domains are getting caught up in the `clk.*` filter.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/1350420/63111910-a85ea600-bf43-11e9-9e10-c8f1a2ca9656.png)

### Versions

- Browser/version: Chrome 76.0.3809.100
- uBlock Origin version: 1.21.6

### Settings

- None

### Notes

The following seemed to add the rules:
https://github.com/uBlockOrigin/uAssets/issues/4030

**Comment by mapx-** [comment]
Provide example pages and explain the issue

**Comment by DuncanFairley** [comment]
As mentioned, they're internal domains.
ublock origin is blocking valid Javascript, present in screenshot.

**Comment by mapx-** [comment]
If you don't provide any detail we cannot help you.

**Comment by mapx-** [comment]
If your issue is about `noeval` filter , I tried disabling it but I get popups.
So, if you are using `eval` for internal goals you should remove the popups generator and we can remove the `noeval` filter

**Comment by DuncanFairley** [comment]
The popups are not advertisements in the internal web application I'm using. It's just UI. 
I'm just asking that the filters that were added for `clk.*` are made more explicit to the domains that you're targetting: `clk.icu`, `clk.press` so that they are no longer targetting my domains, `clk.dev#`, `clk.csr#`, please.

**Comment by mapx-** [comment]
I removed the noeval filter, replacing it.
Update your lists and test again.

**Comment by mapx-** [comment]
or test directly
```
clk.*#@#+js(noeval)
clk.*##+js(window.open-defuser)
```

**Comment by DuncanFairley** [comment]
It no longer blocks my popup. Thank you.

**Comment by okiehsch** [comment]
I get popups using Chromium
Example link: `clk.ink/HMoDP` after solving the captcha and continuing to the countdown site.
I will add the noeval filter.
For your internal testing  I suggest that you add
`clk.*#@#+js(noeval)` 
to your personal filter list.

**Comment by DuncanFairley** [comment]
This is a web platform for 30 users. I can't modify their filter lists.
Could you please filter only the clk domains you are interested in blocking
instead of a wildcard?

**Comment by okiehsch** [comment]
I won't they change all the time and I won't bother adding countless TLD's.

What I am willing to do is add exceptons for your internal sites does
`clk.csr,clk.dev#@#+js(noeval)`
work for you?

**Comment by DuncanFairley** [comment]
Sorry, I don't understand the syntax for whitelisting something.
The domains are clk.csr# and clk.dev# where # is any integer.
Eg. clk.csr1, clk.csr2, etc.

Thanks.

**Comment by mapx-** [comment]
just add in "my filters"
`clk.csr1,clk.csr2,clk.csr3,clk.csr4,clk.csr5,clk.dev1,clk.dev2,clk.dev3#@#+js(noeval)`

adding to the filter above all your internal domains

**Comment by DuncanFairley** [comment]
There's 30 or so users, I don't have access to all of their "my filters" lists. Some of them work from home.

**Comment by mapx-** [comment]
@okiehsch could you test:
```
clk.*#@#+js(noeval)
clk.*##+js(set-constant.js, parseInt, trueFunc)
```

same you @DuncanFairley  with these last filters do you still get some breakage ?

**Comment by DuncanFairley** [comment]
I added those two to My Filters and it made it worse than usual, unfortunately. 
It blocked XHR requests that previously were succeeding.

**Comment by mapx-** [comment]
another idea:
- create a custom list: https://adblockplus.org/forum/viewtopic.php?p=144195&sid=6a69bd58f69e16796a5bab8da0114cd0#p144195

- add whatever filters you want in that list (the filter I told you above)
- ask your users just to click the `subscription link`

**Comment by okiehsch** [comment]
> where # is any integer.

Well, that complicates things. ;)

We can change the filter to 
````
clk.*#@#+js(noeval)
clk.*##+js(aeld, /^(?:click|mouseup)$/, [J])
````
works on my end with Chromium/Chrome and Firefox.

@DuncanFairley any problems if you add the above mentioned filters?

**Comment by gorhill** [comment]
> another idea [...] This custom list is necessary to be subscribed only by your users using uBo

That's the better idea -- I don't like the idea of adding exception filters in uBO list for private domains not accessible from outside, this opens the door for actual sites to leverage those exceptions to bypass uBO. Volunteers can assist in finding a solution but ultimately the solution is to be found by whoever manages those private domains.

Users are free to disable uBO on this internal `clk.dev1` site, that would take care of the issue.
