### ISSUE TITLE
www.coolpc.com.tw popup

### ISSUE THREAD

**Issue by candela97** [uBlockOrigin/uAssets#6087]
### URL(s) where the issue occurs

`https://www.coolpc.com.tw/evaluate.php`

### Describe the issue

popup on every page load, disappears when clicked outside

### Versions

- Browser/version: [Chrome 77.0.3865.35 beta]
- uBlock Origin version: [1.21.6]

### Settings

default settings and lists

### Notes

`||www.coolpc.com.tw/eval-mesg.php` makes the site unusable

**Comment by mapx-** [comment]
Does this work for you ?
`coolpc.com.tw##+js(aopr, SkipMsg)`

**Comment by candela97** [comment]
the filter seems to break some functionality - e.g. after selecting an item, the total price at the bottom and a box showing item information doesn't appear
tested by clicking on the first row and selecting "Acer Windows Mixed Reality"

**Comment by krystian3w** [comment]
Try:

```
coolpc.com.tw##iframe#mycookie, span[style*="position: absolute;"]
coolpc.com.tw##+js(ra, oncontextmenu|onselectstart|onkeyup|style, body)
```

**Comment by bug-rules** [comment]
Why no report to https://github.com/cjx82630/cjxlist/issues

**Comment by candela97** [comment]
> Try:
> 
> ```
> coolpc.com.tw##iframe#mycookie, span[style*="position: absolute;"]
> coolpc.com.tw##+js(ra, oncontextmenu|onselectstart|onkeyup|style, body)
> ```
total prices and information boxes seem to function normally
only a few things left broken:
1. header image disappears `https://www.coolpc.com.tw/home/img/top.html`
2. after selecting an item, clicking the button flashing grey and red on the "floating row" at the bottom freezes the site (a popup is supposed to appear asking you to fill out personal information) 
3. after selecting an item, clicking the red box with the letter "C" on the top left corner freezes the site (a popup is supposed to appear that lets you generate a list of items that you ordered)

**Comment by krystian3w** [comment]
So header exist in `<SPAN>` tag.

**Comment by candela97** [comment]
if it's too much trouble to deal with a minor popup, feel free to close the issue
just a note though, the `#mycookie` filter in fanboy's annoyance list breaks this site in a similar manner to `||www.coolpc.com.tw/eval-mesg.php`

**Comment by krystian3w** [comment]
```
!Annoyance block
coolpc.com.tw##+js(ra, oncontextmenu|onselectstart|onkeyup)

! Ad Pop-up?
coolpc.com.tw#@##mycookie
coolpc.com.tw##span[style*="position: absolute;"]
coolpc.com.tw##+js(ra, style, body)
coolpc.com.tw##+js(ra, style, #hid[style])
coolpc.com.tw###hid:style(visibility: visible !important;)
```

Maybe recover header, but IDK how fix frozen troubles.

**Comment by krystian3w** [comment]
```
!Annoyance block right click / select / move
coolpc.com.tw##+js(ra, oncontextmenu|onselectstart|onkeyup)

! Ad Pop-up?
coolpc.com.tw#@##mycookie
coolpc.com.tw##span[id][style*="position: absolute;"]
coolpc.com.tw##body:style(overflow: auto !important;)
coolpc.com.tw###hid:style(visibility: visible !important;)
```

Should header, but IDK how fix frozen troubles maybe better use `coolpc.com.tw##body:style(overflow: auto !important;)` to recover scrolling.
