### ISSUE TITLE
www.sinya.com.tw popup

### ISSUE THREAD

**Issue by candela97** [uBlockOrigin/uAssets#6088]
### URL(s) where the issue occurs

`https://www.sinya.com.tw/diy`

### Describe the issue

popup on first page load, disappears when clicked outside

### Versions

- Browser/version: [Chrome 77.0.3865.35 beta]
- uBlock Origin version: [1.21.6]

### Settings

default settings and lists

### Notes

blocking the image still dims the site until clicked outside

**Comment by mapx-** [comment]
test
```
sinya.com.tw###cboxOverlay
sinya.com.tw###colorbox
```

**Comment by candela97** [comment]
the filters work and doesn't seem to break any functionality

**Comment by mapx-** [comment]
@ryanbr

**Comment by krystian3w** [comment]
Yeah colorbox is problematic https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/1324 - Polish newsletter and gallery use same node "element".
