### ISSUE TITLE
odkrywamyzakryte.com

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#6091]
### URL(s) where the issue occurs
Main site: `https://www.odkrywamyzakryte.com/`
or any example article: `https://www.odkrywamyzakryte.com/konopie-wszechstronne-zastosowania/`

### Describe the issue

Images hidden

### Screenshot(s)

<details not-open>
<summary>with uBlock filters and / or Fanboy Enhanced Tracking list enabled:</summary>

![screenshot-www odkrywamyzakryte com-2019 08 15-18_35_42_empty](https://user-images.githubusercontent.com/43844449/63120488-a7109600-bfa2-11e9-82cc-84966cc579fc.png)

</details>

<details not-open>
<summary>without uBlock filters and  Fanboy Enhanced Tracking list enabled:</summary>

![screenshot-www odkrywamyzakryte com-2019 08 15-18_35_42](https://user-images.githubusercontent.com/43844449/63120486-a7109600-bfa2-11e9-84e7-f9771cce3888.gif)

</details>

### Versions

- Browser/version: Firefox 68.0.2 / Opera 52
- uBlock Origin version: 1.21.7b8

### Settings

- Default

**Comment by bug-rules** [comment]
No default list, report in bad repository.

**Comment by bug-rules** [comment]
@uBlockOrigin please lock.

**Comment by bug-rules** [comment]
```
@@||www.odkrywamyzakryte.com/wp-content/plugins/bwp-minify/min/*$script,domain=www.odkrywamyzakryte.com
```

```
*/wp-adblock-$script,redirect=fuckadblock.js-3.2.0
```

bad...

**Comment by kulfoon** [comment]
> bug-rules: No default list, report in bad repository.
> bug-rules:  @uBlockOrigin please lock.

What...

1) - "[List here all the changes you made to uBO's default settings]" which means the template allows to have non-default settings, perhaps fix the template then?
2)  even considering the above, my issue doesn't contain non-default settings as it's clearly written:
 with uBlock filters **and / or** Fanboy Enhanced Tracking list enabled, which means even having no - Fanboy Enhanced Tracking list enabled, the issue still occurs, the purpose was just to inform you **by the way** that the issue affects also one of Fanboy's lists.., just such a favor. 

seems the bot must be fixed...

**Comment by bug-rules** [comment]
Ban my polish troll...

you are a Bot...

**Comment by bug-rules** [comment]
Ban my polish troll...

you are a Bot...
