### ISSUE TITLE
kachelmannwetter.com needs defuser scriptlet

### ISSUE THREAD

**Issue by TheRealCuran** [uBlockOrigin/uAssets#6092]
### URL(s) where the issue occurs

`https://kachelmannwetter.com/de/wetter/2950159-berlin`

### Describe the issue

When loading any page on `kachelmannwetter.com` with an adblocker (uBlock Origin and uMatrix in my case) enabled you will get redirected to `https://kachelmannwetter.com/de/site/adblockuser`. The reason for this lurks in `https://kachelmannwetter.com/js/function.js`, lines 160ff:
```javascript
    if ($('#paywall-account-type').attr('data-value') !== 'payaccount') {

        try {
            nx.cmd.push(function () {
                nx.trigger('rescan');
            });
        } catch(err) {};

        a457c035a6dd2ca7c69(function(ret, triggerText) {
            var adblocker = 'Unknown';

            if(ret) {
                adblocker = 'Enabled';
                var infocounter=0;
                $('.md').each(function() {
                    infocounter++;
                    $(this).css('background-color','#f7284b');
                    $(this).css('color','#ffffff');
                    $(this).css('height','100%');
                    $(this).css('font-size','13px');
                    $(this).removeAttr("data-nx-container");
                    if (!isGoogle()) {
                        $(this).html(adblock_txt);
                    }
                    else {
                        $(this).html(adblock_txt2);
                    }
                    if (infocounter>=2) {
                        return false;
                    }
                });
            }
            else {
                adblocker = 'Disabled';
            }

            if(typeof ga !=='undefined'){
                ga('send', 'event', 'Adblocker', adblocker, { nonInteraction: true});
            } else if(typeof _gaq !=='undefined'){
                _gaq.push(['_trackEvent','Adblocker',adblocker,undefined,undefined,true]);
            }

            console.log({adblocker: adblocker, trigger: triggerText, isAdblockInfoSite: $('#noadblock-info').attr('data-value') === 'true'});

            var urlpath = get_url_path();
            if (urlpath.length == 0) { urlpath = '/'; }
            if (adblocker === 'Enabled' && $('#stop-redirect').attr('data-value') !== 'true' && $('#noadblock-info').attr('data-value') !== 'true' && !isGoogle()) {
                if(location.href.indexOf('adpreview=true') !== -1)
                    location.href = get_url_path()+'/site/adblockuser?adpreview=true';
                else
                    location.href = get_url_path()+'/site/adblockuser';
            }
            else if (adblocker === 'Disabled' && $('#noadblock-info').attr('data-value') === 'true' && !isGoogle()) {
                if(location.href.indexOf('adpreview=true') !== -1)
                    location.href = urlpath + '?adpreview=true';
                else
                    location.href = urlpath;
            }
            else if($('#stop-redirect').attr('data-value') !== 'true' && checkCookie() === 'cookiefail' && !isGoogle()) {
                showCookieFail();
            }
            else if ($('#nocookies-info').attr('data-value') === 'true' && checkCookie() !== 'cookiefail' && !isGoogle()) {
                location.href = urlpath;
            }

        });
    }
```
The easiest way to disable this is to set the attribute `data-value` of the HTML DOM element with the ID `paywall-account-type` to `payaccount`.

### Versions

- Browser/version: Firefox/68.0.2
- uBlock Origin version: 1.21.2

### Settings

Not a settings issue, see above.

### Notes

I failed to implement the fix in a custom scriptlet myself, but when I execute
```javascript
(function() {
    document.getElementById('paywall-account-type')
      .setAttribute('data-value', 'payaccount');
})();
```
as a Greasemonkey script the page is working as intended again, ie. no longer redirects to that ad block user page.

If that is possible, it might be an option to block that specific redirect. Or replace parts of functions.js. Otherwise this solution is possibly rather fragile. Though other options are visible from the code snippet posted above.

**Comment by mapx-** [comment]
Did you update uBo lists ?

**Comment by TheRealCuran** [comment]
Yes, I could view the scriplet from uBo's resource viewer and it showed the same content as the version I had put on a server (which was basically the four line solution from my report plus the name and content type line above it). The file looked like this:
```js
kachelmanwetter.com.js application/javascript
(function() {
    document.getElementById('paywall-account-type')
      .setAttribute('data-value', 'payaccount');
})();
```
uBo told me it was using five of five filters (which I guess meant lines in this context) from that file.

When I added a filter like `kachelmannwetter.com##+js(kachelmanwetter.com.js)` nothing happened. I even added an `alert()` to make sure I notice if the snippet triggers and it didn't.

**Comment by mapx-** [comment]
The filter in uBo filters list still working for me:
`kachelmannwetter.com##+js(sid, adsJsLoaded)`

**Comment by TheRealCuran** [comment]
Oh, the main filter was stuck on a two day old version, I see.

**Comment by asdfxD** [comment]
Fixed, we need new bypass.

**Comment by uBlock-user** [comment]
or you could just remove the attribute itself instead of adding another scriptlet --

`kachelmannwetter.com##+js(ra, data-value)`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/cffb66aa2901a574fab42c7abdb28514949d39bb

**Comment by Prince-Kassad** [comment]
Doesn't work here. Updated scripts and the hardblock still triggers.

**Comment by mapx-** [comment]
Do you see in the logger this last filter ?
https://github.com/uBlockOrigin/uAssets/commit/cffb66aa2901a574fab42c7abdb28514949d39bb

**Comment by Prince-Kassad** [comment]
No. I only see the other two JS filters and ##dkpw-billboard-margin DOM filter but not this one.

**Comment by mapx-** [comment]
well, just update your lists

**Comment by mapx-** [comment]
or use:
`kachelmannwetter.com,meteologix.com##+js(set-constant.js, requestAnimationFrame, trueFunc)`

**Comment by mapx-** [comment]
or
```
@@||tag.partner.mairdumont.com^$script,domain=kachelmannwetter.com
@@||tag.md-nx.com^$script,xhr,domain=kachelmannwetter.com
```

**Comment by Prince-Kassad** [comment]
> `kachelmannwetter.com,meteologix.com##+js(set-constant.js, requestAnimationFrame, trueFunc)`

This line does the trick for me. The line from the commit just doesn't match, even if copied in as a custom filter. On the other hand, adding this as a custom filter works like a charm.

**Comment by mapx-** [comment]
yeah, I used an abbreviation (`set` for `set-constant` ) which maybe is not in uBo stable yet (I use the last dev build)

**Comment by mapx-** [comment]
update your lists

**Comment by uBlock-user** [comment]
@TheRealCuran my set-attr scriptlet if you're looking for a working one -- https://github.com/uBlock-user/uBO-Scriptlets/blob/master/scriptlets.txt#L427

`kachelmannwetter.com##+js(set-attr, data-value, payaccount, #paywall-account-type)`

**Comment by TheRealCuran** [comment]
Thanks I'll check that out; for now I've just implemented that solution as a Greasemonkey script, because the current rule set of uBlock no longer works for me. (I suspect I would have to unblock the ad domains in uMatrix, but that will never happen. I don't want to be tracked, if I can avoid it.)

**Comment by mapx-** [comment]
for now the uBo filters are working. Remove any other custom filter for the site from "my filters"

**Comment by TheRealCuran** [comment]
No, they are not working for myself.

I don't have any custom filters for kachelmann.com, yet I still get redirected to the anti ad-block page once I disable my Greasemonkey script.

The only custom settings I have is under "My rules":
```
no-remote-fonts: kachelmannwetter.com false
no-scripting: kachelmannwetter.com false
```
and neither should matter.

I also just purged my filters cache and reloaded to make sure I have the latest filter lists, still no luck. The filters I see are:
```
! https://github.com/uBlockOrigin/uAssets/issues/2883
! https://github.com/uBlockOrigin/uAssets/issues/6092
@@||kachelmannwetter.com/js/ads.js$script,1p
kachelmannwetter.com##.dkpw-billboard-margin
@@||tag.partner.mairdumont.com^$script,domain=kachelmannwetter.com
@@||tag.md-nx.com^$script,xhr,domain=kachelmannwetter.com
```

(I tested with disabled uMatrix as well and that didn't help either.)

The last idea I had was that another of the standard filter lists might interfere, so I deactivated all of them. But again: as soon as I disable my Greasemonkey script I get redirected to the anti ad-block page.

Just for reference, my Greasemonkey script looks like this:
```javascript
// ==UserScript==
// @name        Defuse kachelmannwetter.com AdBlock detection
// @description New adblock "detection", fix it...
// @include     https://kachelmannwetter.com/*
// @version     0.1
// @grant       none
// ==/UserScript==

(function() {
    document.getElementById('paywall-account-type')
      .setAttribute('data-value', 'payaccount');
})();
```

**Comment by mapx-** [comment]
tested in FF / chrome, default settings, no issue for me

**Comment by Prince-Kassad** [comment]
Confirming @TheRealCuran as it doesn't work for me either.

**Comment by TheRealCuran** [comment]
I tried resetting my settings of uBlock. Still no lock with a vanilla uBlock.

These are my extensions. If you want me to test with one or all of them disabled, let me know.
![image](https://user-images.githubusercontent.com/3419202/64066409-7aeb4b00-cc19-11e9-89b2-f0b02f4c2638.png)

**Comment by mapx-** [comment]
Keep only uBo enabled and test again.

**Comment by theinstantmatrix** [comment]
Anti-Adblock Script at `https://weather.us/`

AdguardTeam/AdguardFilters#50937
