### ISSUE TITLE
starblast.io

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6093]
### URL(s) where the issue occurs

`https://starblast.io/`

### Describe the issue

block ads detection

### Screenshot(s)

![obraz](https://user-images.githubusercontent.com/35370833/63125394-daa4ed80-bfad-11e9-9b55-7de5d157b827.png)

`##.adblock`

### Versions

- Browser/version: FX 68.0.2
- uBlock Origin version: 1.21.2

### Settings

- Default + Nano Defender

### Notes

Also website blocked right click?

**Comment by mapx-** [comment]
Is it only an annoyance ?

**Comment by JobcenterTycoon** [comment]
@mapx- can you please remove the filter ` starblast.io##+js(ra, oncontextmenu)` because you need to right click to move the ship but with that filter you open the context menu and this is bad

**Comment by trottor** [comment]
I retested this using Chromium 119.0.6045.105 & installed only uBlock Origin on a new browser profile. Looks like it's doing some anti-adblock measures now.

![image](https://github.com/uBlockOrigin/uAssets/assets/87971343/e6c1bd80-8718-48a0-92ce-053f194ebffb)

### Steps to reproduce
1. Click on PLAY
2. Die
3. Click on Continue
4. Click on Respawn

### Configuration:
uBlock Origin: 1.52.2
Chromium: 119
filterset (summary):
 network: 105875
 cosmetic: 43382
 scriptlet: 18821
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  easylist: 75128-16, 3h.35m
  easyprivacy: 32842-64, 3h.35m
  plowe-0: 3721-1073, 3h.35m
  ublock-badware: 7430-135, 3h.35m
  ublock-filters: 35153-148, 3h.35m
  ublock-privacy: 652-7, 3h.35m
  ublock-quick-fixes: 140-84, 3h.35m
  ublock-unbreak: 2133-31, 3h.35m
  urlhaus-1: 12585-0, 3h.35m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 515 ms
 maxAssetCacheWait: 203 ms

**Comment by automatediceberg** [comment]
This has become an issue again on Safari 26.0.1 using uBlock Origin Lite 2025.928.1920 

Default settings (filtering mode optimal). No other extensions.

**Comment by automatediceberg** [comment]
@stephenhawk8054 could you take a look at this? trotter's report has become an issue again/they circumvented the block

**Comment by stephenhawk8054** [comment]
What are the steps to reproduce the issue?

**Comment by automatediceberg** [comment]
Same as trottor's report

Click on PLAY
Die
Click on Continue
Click on Respawn
