### ISSUE TITLE
Invalid redirect rule in ublock-experimental

### ISSUE THREAD

**Issue by mikhaelkh** [uBlockOrigin/uAssets#6094]
### Describe the issue
During filters update, this pops up in uBO Logger:
```
Invalid redirect rule in ublock-experimental: ||google-analytics.com/analytics.js$script,redirect=google-analytics.com/analytics.js,important,domain=~beinsports.com
```

### Versions

- Browser/version: Chromium 76.0.3809.100 (Official Build) (64-bit)
- uBlock Origin version: v1.21.7b8

**Comment by gwarser** [comment]
Negated `domain` option.

**Comment by mapx-** [comment]
fixed
https://github.com/uBlockOrigin/uAssets/commit/0459457a2d558a2457ad856094cebf3c96e04efd
