### ISSUE TITLE
hulkpop.com multiple redirects + anti adblock (destination mega/mir.cr)

### ISSUE THREAD

**Issue by Movisivi** [uBlockOrigin/uAssets#6096]
### URL(s) where the issue occurs

`https://hulkpop.com/ans-wonderland-single/`

### Describe the issue

https://imgur.com/a/nTBDV4l

same behavior as https://github.com/uBlockOrigin/uAssets/issues/6071
### Versions

- Browser/version: Firefox Nightly 70.0.a1
- uBlock Origin version: 1.20.2

### Settings

- https://prnt.sc/ora0ab

**Comment by dumbusernameidk** [comment]
the site is using url shorteners so of course it'll have multiple redirects. as for anti-adblock i don't get any.

**Comment by mapx-** [comment]
test
```
hulblog.com,hulkpop.com##+js(aopr, decodeURIComponent)
hulblog.com,hulkpop.com##+js(aopr, Base64)
```

**Comment by dumbusernameidk** [comment]
those filters work on my end.
