### ISSUE TITLE
oxy.cloud

### ISSUE THREAD

**Issue by lyndmi** [uBlockOrigin/uAssets#6098]
### URL(s) where the issue occurs

`https://oxy.cloud/d/pyH`

### Describe the issue

Asking me to allow notification. If not, it will redirect to other subdomain of oxy.cloud and ask again and again. If i disable notification entirely, it will redirect many times then stuck forever. If I allow it, it will redirect to download page

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24647715/63195404-c24ad680-c072-11e9-9b91-adbfd622d1ab.png)

### Versions

- Browser/version: Opera 62.0.3331.116
- uBlock Origin version: 1.21.6

### Settings

- Have Adblock Warning Removal List enabled

### Notes

None

**Comment by llacb47** [comment]
Found this: `https://greasyfork.org/en/scripts/382794-oxy-cloud-download-helper/code`

**Comment by lyndmi** [comment]
Thanks

**Comment by krystian3w** [comment]
#5890

**Comment by krystian3w** [comment]
UserScript down?

**Comment by dumbusernameidk** [comment]
the userscript works for me.

**Comment by krystian3w** [comment]
So updated, I see v1.0.2 🥇

**Comment by mapx-** [comment]
added here:
https://github.com/uBlockOrigin/uAssets/issues/5890
