### ISSUE TITLE
vaughnlive.tv

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#61]
Hi, 
Firefox 46 / Chrome 50 + uBo 1.7 / 1.7.2 Default settings.

anyway to block these "Ads by VaughnSoft" on `http://vaughnlive.tv/art_bell_classics` ?

Thanks!

**Comment by gorhill** [comment]
It's a Flash-based player -- I decline to investigate when it's Flash-based, since Flash is essentially a proprietary blob.

**Comment by SMed79** [comment]
Ok, Thanks for your reply.

**Comment by lewisje** [comment]
I also believe this was the subject of much hard, but ultimately fruitless, work at the Adblock Plus and EasyList forums.
