### ISSUE TITLE
http://fas.li/ – Please disable Adblock

### ISSUE THREAD

**Issue by pepablock** [uBlockOrigin/uAssets#610]
### URL(s) where the issue occurs

**example link** **–** `http://fas.li/4ypbQ`

### Describe the issue

Instead of redirecting to the destination page, you get this message "Please disable Adblock".

### Screenshot(s)

<img width="1680" alt="01" src="https://user-images.githubusercontent.com/29940017/28910322-a05ccb22-782c-11e7-9b9e-d72eb1d4b182.png">

### Versions

- Browser/version: **Firefox 54.0.1 (64-bit)**
- uBlock Origin version: **1.13.8**

### Settings

Default

### Notes

–

**Comment by SMed79** [comment]
`@@||fas.li^$generichide`
(https://forums.lanik.us/viewtopic.php?p=113269#p113269)

**Comment by okiehsch** [comment]
@SMed79 `shink.in` anti-adblock is already [fixed](https://github.com/uBlockOrigin/uAssets/commit/da57b0b9c0d645358e189859578e365520d0d1d3).

**Comment by ThinksHeIsCool** [comment]
`https://i.gyazo.com/f32a147abfb27cb3d3dd92e6a792a5da.png`
