### ISSUE TITLE
google.*

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#6103]
### URL(s) where the issue occurs

`google.com`

### Describe the issue

Ad links, redirect to `www.googleadservices.com`

### Screenshot(s)

![Screenshot_20190817-220044_Firefox](https://user-images.githubusercontent.com/48647394/63216766-e4a82700-c13a-11e9-862d-e852eae78b91.jpg)

### Versions

- Browser/version: Firefox 68.0.2
- uBlock Origin version: v1.21.2

### Notes

Mobile only (Android 8)

**Comment by mapx-** [comment]
Does work for you ?
`google.*##a[href*="aclk"]:xpath(//span[(text()='Ad') or (text()='Anzeige')]/../../../..)`

**Comment by JobcenterTycoon** [comment]
Yes

**Comment by krystian3w** [comment]
These no works: `www.google.com#@#header[id="hdr"] ~ div#main > div[class="ZINbbc xpd O9g5cc uUPGi"]`
