### ISSUE TITLE
fullhdxxx.com [NSFW]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#6106]
### URL(s) where the issue occurs

`https://www.fullhdxxx.com/pl/catfhx/1353/young/` (example subpage)

### Describe the issue

While clicking video thumbnail to watch the video, an additional unwanted & unrelated new window is being opened.

### Versions

- Browser/version: Firefox 68.0.2 / Opera 62
- uBlock Origin version: 1.21.7b9

### Settings

- Default

**Comment by dumbusernameidk** [comment]
Also fake push notifications.

**Comment by mapx-** [comment]
some filters:
```
fullhdxxx.com##+js(aopr, ExoLoader)
fullhdxxx.com,viptube.com##+js(window.open-defuser)
fullhdxxx.com##+js(aeld, popstate)
fullhdxxx.com##+js(set-constant, adv, true)
viptube.com##+js(set-constant, canRunAds, true)
||daynews.support^
```

**Comment by dumbusernameidk** [comment]
works for me.

**Comment by kulfoon** [comment]
Works, and btw I didn't know there is so many crap on this site.

**Comment by dumbusernameidk** [comment]
viptube popups on mobile.

1. Clear cookies for `viptube.com`
2. Use agent switcher so the site is on `m.viptube.com`
3. Click a video and the first tab gets redirect to a junk site.

**Comment by okiehsch** [comment]
Does
`m.viptube.com##+js(aopw, mobilePop)`
work for you?

**Comment by dumbusernameidk** [comment]
yes that works.
