### ISSUE TITLE
kickass.best

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6109]
### URL(s) where the issue occurs

`https://kickass.best/t3-Batla-House-2019-UntoucheD-Pre-DVD-NTSC-Exclusive-tt3944981.html`

### Describe the issue

Vpn ads on clicking anywhere in page

### Versions

- Browser/version: firefox android browser
- uBlock Origin version: 1.21.2

### Settings

- uBO's default settings

**Comment by ghajini** [comment]
`https://kickass.best` redirects to `https://kickass-kat.com/`

`https://kickass-kat.com/t3-Batla-House-2019-UntoucheD-Pre-DVD-NTSC-Exclusive-tt3944981.html`

torrent ads

**Comment by ghajini** [comment]
New site `https://kickassteam.net/movies/` has popups of vpn promotion, also crap ads

This filter 
`kickassteam.net##+js(acis, String.fromCharCode, /btoa|break)`
has race condition in firefox /opera/chrome when page is  refreshed few times

**Comment by mapx-** [comment]
what do you want to do using that filter ? I get no `btoa` or `break` on that page. To be correct you need another slash

`kickassteam.net##+js(acis, String.fromCharCode, /btoa|break/)`

**Comment by mapx-** [comment]
test

```
kickassteam.net##+js(aopr, document.write)
kickassteam.net##+js(aeld, click, Target)
```

**Comment by ghajini** [comment]
Sorry that was typing mistake for `/`
Basically that crap I want to avoid
https://user-images.githubusercontent.com/20338483/101261042-1abb5100-375a-11eb-8817-e8794020b499.jpg

Your filter work

**Comment by ghajini** [comment]
popup ads
`https://kick4ss.com/movies/`
`https://kickass-kat.com/`
`https://kickass.best/t3-Batla-House-2019-UntoucheD-Pre-DVD-NTSC-Exclusive-tt3944981.html`

**Comment by ghajini** [comment]
popup ads

`https://kickass.onl`
