### ISSUE TITLE
madchensex.com [NSFW]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#6113]
### URL(s) where the issue occurs

`http://www.madchensex.com/`

### Describe the issue

Ads, also new tab and redirection while clicking at video thumbnail to watch the video.

### Versions

- Browser/version: Firefox 68.0.2 / Opera 62
- uBlock Origin version: 1.21.7b10

### Settings

- Default

**Comment by mapx-** [comment]
I get no redirection, only ads
```
madchensex.com##+js(aopr, ExoLoader)
madchensex.com###side-spot
```

**Comment by okiehsch** [comment]
No redirection on my end either,

**Comment by kulfoon** [comment]
> I get no redirection, only ads

- the redirection and new tab occurs only on Firefox.
- nn Opera there is no redirection, but there is a new window which popups for a sec and is closed quickly by some ABP popup filter I think.
- all the redirection, new tab and new window occurs at the first vist only

Anyway with your filters I don't get the new tab, new window and redirection anymore, so it's fixed.
