### ISSUE TITLE
nakenprat.com [NSFW]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#6126]
### URL(s) where the issue occurs
`https://www.nakenprat.com/`

### Describe the issue

Ads. (even with NOR list and AdGuard Base Filter)

### Versions

- Browser/version: Firefox 68.0.2 / Opera 62
- uBlock Origin version: 1.21.7b10

### Settings

- Default

**Comment by okiehsch** [comment]
@DandelionSprout

`nakenprat.com##+js(aopr, document.dispatchEvent)`
fixes the issue.
