### ISSUE TITLE
who-called.co.uk

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#614]
**URL(s) where the issue occurs**

`http://who-called.co.uk/`

**Describe the issue**

Anti-Adblock nag screen.

**Screenshot(s)**

- http://i.imgur.com/ug1If79.png

**Filters**

`who-called.co.uk##script:inject(setTimeout-defuser.js)`

**Versions**

- Operating system: Manjaro 17.0.2
- Browser/version: Firefox / 54.0 (64bit)
- uBlock Origin version: 1.13.8
- Other installed addons/extensions: 
-- Smart Referer
-- Decentraleyes
-- Self-Destructing Cookies

**Settings**

- Default settings.

**Comment by gorhill** [comment]
`||who-called.co.uk/cdn-cgi/apps/head/*$script`

Works?

**Comment by okiehsch** [comment]
Yes, that will work, [they](https://noadblock.net) changed their code and the current fix for sites using `noadblock`
`##script:inject(abort-on-property-read.js, CloudflareApps.installs)` does not work anymore.

**Comment by okiehsch** [comment]
If you prefer a uBO-specific filter
`who-called.co.uk##script:inject(abort-on-property-read.js, _0xde46)` works on my end.
