### ISSUE TITLE
inside-digital.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#6141]
### URL(s) where the issue occurs

`https://www.inside-digital.de/handys/samsung-galaxy-s10-5g`

### Describe the issue

Ads

### Screenshot(s)

<img width="1048" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/63372169-def25180-c385-11e9-9250-d47f0f5c76dd.PNG">

### Versions

- Browser/version: Firefox 68.02
- uBlock Origin version: v1.21.2

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3521976/Settings.txt)

**Comment by mapx-** [comment]
test this filter if breaks something 
`inside-digital.de##+js(abort-current-inline-script.js, Number.isNaN)`

**Comment by JobcenterTycoon** [comment]
it works

**Comment by sugarfreesweetener** [comment]
`inside-handy.de` => `inside-digital.de` (idk if it was an IP-related thing)

and
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/113248817/192147295-bfd5b9fc-35ef-4853-b636-60848e99fc16.png)

</details>

**Comment by JobcenterTycoon** [comment]
The image from your screenshot is self advertisment which not getting fixed

**Comment by sugarfreesweetener** [comment]
> The image from your screenshot is self advertisment which not getting fixed

Oh, I saw the `Bosch` thing

**Comment by JobcenterTycoon** [comment]
When i click on it i get redirected to `https://www.inside-digital.de/energie` so this is not an ad.
