### ISSUE TITLE
tubepornclassic.com [NSFW]

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#6143]
### Describe the issue

[Ads and redirects.]

### Versions

- Browser/version: [Chrome v76]
- uBlock Origin version: [1.21.6]

### Settings

- [default]

**Comment by dumbusernameidk** [comment]
popups again when pressing play on a video.

**Comment by okiehsch** [comment]
Reload the site bypassing the cache one time after updating the filter list.

**Comment by dumbusernameidk** [comment]
Ads coming this script `spareton.online`.

**Comment by okiehsch** [comment]
Does
`tubepornclassic.com##+js(aopr, RegExp.prototype.toString)`
work without breaking anything?

**Comment by dumbusernameidk** [comment]
seems to be work and nothing is broken yet.

**Comment by dumbusernameidk** [comment]
`tubepornclassic.com##+js(aopr, RegExp.prototype.toString)` needs to be removed it breaks the buttons when trying to cycle through pages or any dropdown.

**Comment by dumbusernameidk** [comment]
`https://tubepornclassic.com/videos/59768/proposta-oscena/?fr=59768`
Ads.

**Comment by okiehsch** [comment]
Does adding

````
@@||tubepornclassic.com/likhni/*$script,1p
tubepornclassic.com#@#+js(acs, adver)
````
to your filter list work for you?

**Comment by Yuki2718** [comment]
@taskforceken I already updated rules. Remove the rules you have added and force-update filters.
