### ISSUE TITLE
flashingjungle.com [NSFW]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#6144]
### URL(s) where the issue occurs

`https://flashingjungle.com/`

### Describe the issue

Unwanted popup & redirection after clicking photo to view it.

### Versions

- Browser/version: Firefox 68.0.2 / Opera 62
- uBlock Origin version: 1.21.9b0

### Settings

- Default

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0421417087966ecc4ab380c5fb458a0660280dc7
