### ISSUE TITLE
wegner.tech Bug

### ISSUE THREAD

**Issue by falfan2018** [uBlockOrigin/uAssets#6147]
URL(s) where the issue occurs
`https://wegner.tech/gZwiSDsj`

Describe the issue
after boosting countdown get bad request and stuck

Versions
Browser/version: Version 76.0.3809.100 (Official Build) (64-bit)
uBlock Origin version: 1.21.6

Screenshot(s)
![Annotation 2019-08-21 030313](https://user-images.githubusercontent.com/9379770/63410961-a9e60d80-c41e-11e9-8ea0-55cab37fc089.png)

Settings
Default+nano defender filter

**Comment by okiehsch** [comment]
There is no countdown boosting filter for this site in `uAssets`.
You will have to investigate on your end and then disable that filter. 
That site validates the countdown on the server side and boosting it  on the client side will result in a bad request.
