### ISSUE TITLE
Giantbomb.com video player is broken by uBlock

### ISSUE THREAD

**Issue by apassiou** [uBlockOrigin/uAssets#615]
### URL(s) where the issue occurs

`[https://www.giantbomb.com/videos/unfinished-ex-metroid-samus-returns-08022017/2300-12430/]`

`[https://www.giantbomb.com/videos/quick-look-hellblade-senuas-sacrifice/2300-12429/]`

### Describe the issue

[The video player stays at "Loading Video" forever if uBlock is enabled.]

### Screenshot(s)

[http://imgur.com/a/chSfC]

### Versions

- Browser/version: [Version 59.0.3071.115 (Official Build) (64-bit)]
- uBlock Origin version: [1.13.8]

### Settings

- [Everything is default. Subscribed to EasyList, EasyPrivacy, Anti-Adblock killer, Adblock warnin removal list, Malware Domain list, malware domains, and the 3 RUS lists.]

### Notes

[Disabling uBlock makes video appear.]

**Comment by gorhill** [comment]
Force an update of "uBlock filters -- Unbreak", this [was fixed yesterday](https://github.com/uBlockOrigin/uAssets/commit/33e4ccb81081c160e1c8d370bdcfc157d823b0e9).
