### ISSUE TITLE
silkengirl.com [NSFW]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#6151]
### URL(s) where the issue occurs
`https://www.silkengirl.com/yana-west-in-red-and-black-lingerie/`

### Describe the issue

Ads (even with AdGuard Base Filter).

### Versions

- Browser/version: Firefox 68.0.2 / Opera 62
- uBlock Origin version: 1.21.9b0

### Settings

- Default

**Comment by dumbusernameidk** [comment]
Another domain `silkengirl.net`. Also has a script like `silkengirl.net/gallery-name/fload.js`. Site also has iStripper images that are loaded as well.

**Comment by mapx-** [comment]
I get nothing on `silkengirl` site, no ads, no `iStripper`, no `fload` script

**Comment by dumbusernameidk** [comment]
try this link `https://www.silkengirl.net/stunning-playboy-model-sarah-stephens/`.

**Comment by mapx-** [comment]
fixed, thanks

**Comment by kulfoon** [comment]
> dumbusernameidk : https://github.com/uBlockOrigin/uAssets/issues/6151#issuecomment-523600942 : Probably best to globally block the fload script a lot of these gallery websites use it.

Also the filter should go rather to EasyList than to uBlock filters, coz:

 - it will cover more users (Adblock Plus users and not uBlock Origin users only)
- there is already a dedicated section for such kind of filters on EasyList: 
https://github.com/easylist/easylist/blob/0326619a5a3d8113cdff02e46516174b6c221653/easylist/easylist_general_block.txt#L7975-L7997

**Comment by mapx-** [comment]
@ryanbr

**Comment by kulfoon** [comment]
Ok, so here I've done some analysis - I've checked the EXADS scripts 's fake names count in `https://publicwww.com`:

First some stats about the orginal names
- (from EasyList) `/frontend_loader.js`  - [326 web pages](https://publicwww.com/websites/%22%2Ffrontend_loader.js%22/)
- (from EasyList) `/backend_loader.php`  - [374 web pages](https://publicwww.com/websites/%22%2Fbackend_loader.php%22/)

And now stats about the fake names:

- (from EasyList) `/fro_lo.js`  - [81 web pages](https://publicwww.com/websites/%22%2Ffro_lo.js%22/)
- (from dumbusernameidk) `fload.js`  - [38 web pages](https://publicwww.com/websites/%22%2Ffload.js%22/)
- (from EasyList) `/ebloader.`  - [23 web pages](https://publicwww.com/websites/%22%2Febloader.%22/)
- (from EasyList) `/exo-loader/*`  - [13 web pages](https://publicwww.com/websites/%22exo-loader%22/)
- (from EasyList) `/floader.js`  - [5 web pages](https://publicwww.com/websites/%22%2Ffloader.js%22/)
- (from EasyList) `/frontend_loador.js`  - [1 web page](https://publicwww.com/websites/%22%2Ffrontend_loador.js%22/)
- (from EasyList) `/ebldr.php`  - [0 web pages](https://publicwww.com/websites/%22%2Febldr.php%22/)
- (from EasyList) `/ex/b.php`  - [0 web pages](https://publicwww.com/websites/%22%2Fex%2Fb.php%22/)
- (from EasyList) `/exo_frnd_`  - [0 web pages](https://publicwww.com/websites/%2Fexo_frnd_/)

And now...I've found new fake names, more numerous ones, even than the original names!:

- (new, from me) `/nb/frontend.js`  - [428 web pages](https://publicwww.com/websites/%22%2Fnb%2Ffrontend.js%22/)
- (new, from me) `/nb/b_lo.php`  - [388 web pages](https://publicwww.com/websites/%22%2Fnb%2Fb_lo.php%22/)
- (new, from me) `/fel456.js`  - [81 web pages](https://publicwww.com/websites/%2Ffel456.js/)
- (new, from me) `/bel456.php`  - [81 web pages](https://publicwww.com/websites/%2Fbel456.php/)
- (new, from me) `/js/nvrblck.js`  - [53 web pages](https://publicwww.com/websites/%22%2Fjs%2Fnvrblck.js%22/)
- (new, from me) `/nvr_bcknd.php`  - [53 web pages](https://publicwww.com/websites/%22%2Fnvr_bcknd.php%22/)
- (new, from me) `/be568.js`  - [23 web pages](https://publicwww.com/websites/%22%2Fbe568.js%22/)
- (new, from me) `f_load.js`  - [4 web pages](https://publicwww.com/websites/%22%2Ff_load.js%22/)
- (new, from me) `/b_load.php`  - [3 web pages](https://publicwww.com/websites/%22%2Fb_load.php%22/)
- (new, from me) `/b_l.php`  - [4 web pages](https://publicwww.com/websites/%22%2Fb_l.php%22/)

Adding the new ones will remove ads on great number of websites.

**Comment by kulfoon** [comment]
Ads on pornsites - EXADS Anti-AdBlock solution - 121 webpages [NSFW]



### URL(s) where the issue occurs

<details not-open>
<summary>Spoiler - 121 websites NSFW</summary>

```
18teenporno.tv
3teentube.com
4gaycocks.com
50yearoldsluts.com
adult-home-videos.com
amateur-cougar.com
amateur-nude.com
amateurmaturewives.com
babeswp.com
bannedbdsm.com
bdsmaz.com
bdsmsecrets.net
bestboyshardcore.com
besttwinkass.com
bigbangtube.com
bizarre-club.com
bondage-club.net
bondagevideo.org
bondagewaytube.com
cekc-tube.ru
celebritytubeporn.com
celebxvideo.com
cidertube.com
crazygayporn.com
dailygayvideo.com
desimms.co
digisesso.com
dusktube.com
elmtube.com
enterfreegaysex.com
etitz.com
experiences-gay.com
femdomdaily.com
fieldstube.com
footfetish-slave.com
freebesttwinks.com
freegranny6.com
freematurelovers.com
freematureswomen.com
gay-place.com
gayfuckingtube.com
gaypornxxxtube.com
goodtgp.net
gporn.xyz
grannysfucking.net
hdbbwmovies.com
helloshemale.com
hiddencamsluts.com
homevoyeurvideo.net
hornygrannytube.net
hqvintagetube.net
hugeboobswomen.com
indiancunts.net
indianporndaily.com
indianpornqueens.org
indiansexfree.net
javbobo.com
kuboys.net
latinapornworld.com
latinaxxxvideos.com
matures-loving-sex.com
maturesandnylon.com
meporno.com
mikesmatures.com
momsfuckboys.com
moreasiansex.com
mybbwtube.com
mygrannyporn.com
myowntits.com
nakedolders.com
naughtyjapaneseteens.com
nicegrannys.com
nudemilfwomen.com
nudeteenshub.com
nylonbabez.net
nyloncunts.com
nylonglamourlegs.com
nylonpornpictures.net
older-wives.com
pantyhoseminx.com
paulsmatures.com
porngoeshd.com
pornoplum.com
pornvideoh.com
pornvideos.host
raventube.com
retropornzone.com
ritzyamateursex.com
sexrura.com
sexytwinkcock.com
stockingspornpics.com
teen-tube-18.com
teen-tube-19.com
teen-tube-21.com
teen-tube-porn.com
teenporn.ws
teenpornvideo.me
teensexvideos.xxx
teensfacialized.com
teensonporn.com
teentube-18.com
thevintagemovies.com
timetoteens.com
tube-teen-18.com
tubebikini.com
tubehd.xxx
ultragranny.com
uniformcunts.com
videosexyteen.com
videosmadeathome.com
vintagesextapes.com
vipoldies.net
wildfemdom.com
wildretroporn.com
wowpornlist.xyz
xxx-hd-teens.com
xxx-hd-tube.com
xxxmegaboobs.com
yatranny.com
yourbdsmmovie.com
yourfreepantyhosegalleries.com
```

</details>


### Describe the issue
Ads on pornsites.
Second attempt to fight against 
EXADS Anti-AdBlock solution: [EXADS 1](https://github.com/sanosay/exads-adblock), [EXADS 2](https://www.exads.com/ ).
The previous attempt was in [my previous comment](https://github.com/uBlockOrigin/uAssets/issues/6151#issuecomment-524312826). Many ads on pornsites was removed thanks to finding popular script names and adding generic filters to EasyList, but unfortunately, some pornsites still generate random script names, so they have to be fixed in uBO.

### Screenshot(s)

`https://ibb.co/kgwm3tp`  main page - ads on the main page most often at the bottom
`https://ibb.co/7QW7Mb0` subpage - ads on subpages most often at the right 

### Versions

- Browser/version: Firefox 76.0.1
- uBlock Origin version: 1.27.0

**Comment by mapx-** [comment]
just a quick fix for the ads, maybe needing some filter for popunders

**Comment by kulfoon** [comment]
Ads fixed on almost all sites, except these 8, despite they have been included in the commit, it might be that they require some other additional or harder fix: `mikesmatures.com` , `nakedolders.com`
`nudemilfwomen.com` , `paulsmatures.com` , `pornoplum.com` , `teensfacialized.com` , `wowpornlist.xyz`

Another thing is that I'm surprised that most of the 121 sites have been fixed by simple ABP-compatible filter ( I thought they will require some uBO injection like `(aopr, ExoLoader)` ) If I knew that,  I would report them to EasyList rather to uBO tracker, anyway I leave the final decision to you whether to keep them in uBO list or to move to EasyList.

**Comment by mapx-** [comment]
yeah, @ryanbr could add `php` filters or generic ones like these ones:
```
/frtd_ldr_$script,1p
/bknd_ldr_$script,1p
```

**Comment by kulfoon** [comment]
OK, all the 8 sites are fixed now.

Yes, also he could block the annoying empty ad containers, there are plenty of them on many pornsites.

**Comment by mapx-** [comment]
added a filter for the empty stuff
`pornoplum.com,vulgarmilf.com,oldgirlsporn.com,mikesmatures.com,maturell.com,nakedolders.com,nudemilfwomen.com,paulsmatures.com,widewifes.com##iframe:upward(2)`

**Comment by kulfoon** [comment]
Yes, all mentioned are fixed now, however still a few more pornsites  with empty ad containers left: 
`besttwinkass.com` , `nylonbabez.net` , `nylonpornpictures.net` , `sexrura.com` , `stockingspornpics.com`

**Comment by felix-22** [comment]
Several more sites (ExoAds):
```
girlsfucking.net
hairy-amateurs.com
maturevideos.site
milfera.com
onlylesbianvids.com
teen-porn-tube.com
```

**Comment by felix-22** [comment]
Any problems appending above domains to the last commit?: https://github.com/uBlockOrigin/uAssets/commit/54dab4145edba7500ce1252e34a71c97b634ca2a#diff-9fb4521620852750c69b0a32afd561d817334eb3d2e6bcbc79586ea32f52e90eL1347

**Comment by felix-22** [comment]
Any problems appending above domains to the last commit?: https://github.com/uBlockOrigin/uAssets/commit/54dab4145edba7500ce1252e34a71c97b634ca2a#diff-9fb4521620852750c69b0a32afd561d817334eb3d2e6bcbc79586ea32f52e90eL1347

**Comment by adbl0cking** [comment]
`https://www.older-wives.com/`
```
! Neverblock
older-wives.com##+js(rmnt, script, /myEl|Exo/)
! In-house popunder
older-wives.com##+js(aopr, userout)
```

**Comment by Omega-6** [comment]
dead sites

```
mybbwtube.com
nakedolders.com
hugeboobswomen.com
```
