### ISSUE TITLE
homemature.net [NSFW]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#6161]
### URL(s) where the issue occurs
`https://homemature.net/` (main page)

### Describe the issue

Popup while clicking at the video thumbnail to watch the video (even with AdGuard Base Filter).

### Versions

- Browser/version: Firefox 68.0.2 / Opera 62
- uBlock Origin version: 1.21.9b0

### Settings

- Default

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/aa0762e1f15e0b3b431a714632c5694a2f75b322
