### ISSUE TITLE
soyoungteens.com [NSFW]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#6162]
### URL(s) where the issue occurs
`http://soyoungteens.com/x.php?path=MTIwNjg5NzleeGgudmlkZW8vdi96aEN1&cat=teen&d=eXVtbXleMzowMg==` (example video subpage)

### Describe the issue

Ads (even with AdGuard Base Filter).

### Versions

- Browser/version: Firefox 68.0.2 / Opera 62
- uBlock Origin version: 1.21.9b0

### Settings

- Default

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a12a55b85eabc0ef42d9b05aca061a9609e1b306
