### ISSUE TITLE
kingsofteens.com [NSFW]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#6163]
### URL(s) where the issue occurs
`https://kingsofteens.com/` (main page)
`https://kingsofteens.com/videos/4152/cum4k-multiple-cum-filled-creampies-compilation.html` (example video subpage)

### Describe the issue

Ads (even with AdGuard Base Filter).

### Versions

- Browser/version: Firefox 68.0.2 / Opera 62
- uBlock Origin version: 1.21.9b0

### Settings

- Default

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/e629c0285d6d2d43c184b80098e71fe03f68f924

**Comment by mapx-** [comment]
test these filters
```
kingsofteens.com##+js(aopw, base64_decode)
kingsofteens.com##+js(window.open-defuser)
```

**Comment by mapx-** [comment]
does this help ?
`||kingsofteens.com/js/KernelTeam$script,1p`

**Comment by mapx-** [comment]
not all the video links on main page are for the same site.

test
`||arda0hylt58g4wg0.pro^`

**Comment by mapx-** [comment]
Are you talking about these links ?
`href="https://arda0hylt58g4wg0.pro/v2/a/skm/51786?tburl=https://kingsofteens.com/videos/4144/teen-girl-hot-squirt.html"`

**Comment by mapx-** [comment]
I added the first 2 filters for popunders - other "normal" popups

**Comment by mapx-** [comment]
maybe we need an official scriptlet like this 1:
https://github.com/uBlock-user/uBO-Scriptlets/blob/master/scriptlets.txt#L588

@uBlock-user  @gorhill

**Comment by ghajini** [comment]
1.
@mapx- query stripping mean like get direct url `https://kingsofteens.com/videos/1844/free-teen-sex-video-featuring-pretty-teenager-taylor-reed-stepsis-bliss.html` without any 3rd party porn sites intervening from
`https://arda0hylt58g4wg0.pro/v2/a/skm/51786?tburl=https://kingsofteens.com/videos/1844/free-teen-sex-video-featuring-pretty-teenager-taylor-reed-stepsis-bliss.html`

i added `kingsofteens.com##+js(query-stripper, /\?fbclid=\w+/)` but i don't getting original url

2.
popups on
`https://kingsofteens.com/videos/1844/free-teen-sex-video-featuring-pretty-teenager-taylor-reed-stepsis-bliss.html`

click play button

**Comment by mapx-** [comment]
2. still no popup for me - did you use last filters ?
1. `fbclid` is for FB stuff, let's see from @uBlock-user if can be used here with other parameters

**Comment by ghajini** [comment]
safe to block `arda0hylt58g4wg0.pro`

**Comment by bogachenko** [comment]
>i added kingsofteens.com##+js(query-stripper, /\?fbclid=\w+/) but i don't get redirect to original url

This scriptlet was **not** created for this.

And by the way `?tburl=` and `?fbclid=`

**Comment by mapx-** [comment]
https://github.com/uBlock-user/uBO-Scriptlets/issues/5#issuecomment-526867425
