### ISSUE TITLE
Gamespot Viewplayer and image viewer

### ISSUE THREAD

**Issue by tsunami2311** [uBlockOrigin/uAssets#617]
reference to https://github.com/gorhill/uBlock/issues/2835

image viewer and player is broke again thought i suspect it has something to do with easylist as
whitelisting
https://static.gamespot.com/js/compiled/tracking.js

restores function not sure if you want me to keep reporting this cause Gamespot is notrious to  changes things more then once week and in turn breaking things, I just reporting it here cause you asked me to report it here

**Comment by okiehsch** [comment]
This is already fixed by the filter `/compiled/tracking.$badfilter` which is part of the `uBO-unbreak` list.
Force an update of your `uBO-unbreak` list.
