### ISSUE TITLE
linksht.com [Anti-Adblock]

### ISSUE THREAD

**Issue by RaveN0X87** [uBlockOrigin/uAssets#6175]
URL(s) where the issue occurs
`https://linksht.com/b835c50`

Describe the issue
anti adblock

Versions
Browser/version: Google Chrome v76.0.3809.100 (Official Build) (64-bit)
uBlock Origin version: 1.21.6

Settings
Default

**Comment by mapx-** [comment]
- reset uBo to the default settings, update the lists
- disable any other blocking extension
- test again
