### ISSUE TITLE
Multiple WordPress-based sites seemingly blocked August 24,2019

### ISSUE THREAD

**Issue by CarlFink** [uBlockOrigin/uAssets#6179]
### URL(s) where the issue occurs

`http://dangermouse.net/`
`http://theworstthingsforsale.com/2019/08/23/the-hell-baby/`

### Describe the issue

Pages show a blank white screen. 

### Screenshot(s)

![ublock_issue_hellbaby](https://user-images.githubusercontent.com/35018539/63636639-fa888100-c63f-11e9-9c27-9bd539457f90.png)

### Versions

- Browser/version: Waterfox 56.2.12 (64-bit)
- uBlock Origin version:  v1.21.2

### Settings

- 

### Notes

Page source indicates many scripts blocked by uBlock Origin, presumably including the one that loads content. (I have not tried to analyze the problem beyond this.) Note: no content, just blocked scripts.

**Comment by mapx-** [comment]
- no issue for me in waterfox 56.2.13 (64-bit)
- reset to the default settings and test again

**Comment by gwarser** [comment]
No issue on 1.21.2

Something more blocked?

![image](https://user-images.githubusercontent.com/886325/63637137-355adb00-c679-11e9-9f37-4edf2913ec29.png)

**Comment by krystian3w** [comment]
For tests is needed GNU/Linux?

**Comment by CarlFink** [comment]
Apologize for wasting people's time. There's some weird issue with Waterfox in the current version that fooled me. Certain sites won't load if you click on a link that opens in a new tab, but will open if you copy/paste the URL into an empty tab. Reload per se does not work, but the reload that uBlock Origin does after you change the setting did work. Tricked me into believing it was the setting change that did it. I'm closing this, and thanks for investigating, and again, sorry about the time wasted.
