### ISSUE TITLE
latestseoupdate.com

### ISSUE THREAD

**Issue by lyndmi** [uBlockOrigin/uAssets#6180]
### URL(s) where the issue occurs

`https://latestseoupdate.com/zBBEN2N`

### Describe the issue

Counting down and freezes if browser is out of focus
Request for countdown booster

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24647715/63653003-69142e80-c767-11e9-8040-448879e9f533.png)

### Versions

- Browser/version: 62.0.3331.116
- uBlock Origin version: 1.21.8

### Settings

- Default

### Notes

Owner of the domain is by UrlShortx

**Comment by mapx-** [comment]
not doable (controlled on server side => "Bad Request.")

**Comment by llacb47** [comment]
@mapx- filter can be added for focus annoyance

**Comment by mapx-** [comment]
thanks
