### ISSUE TITLE
de.quora.com: sign in

### ISSUE THREAD

**Issue by ChristophHeilmann** [uBlockOrigin/uAssets#6181]
### URL(s) where the issue occurs

de.quora.com

### Describe the issue

sign in

### Screenshot(s)

![de quora com_](https://user-images.githubusercontent.com/9595209/63653831-3f143980-c772-11e9-8bfa-755668a9616c.png)

### Versions

- Browser/version:  Chrome 76
- uBlock Origin version: 1.21.6

### Settings

none

**Comment by mapx-** [comment]
just get a quora link on google search and you can navigate freely, for example go to 
`https://www.quora.com/What-can-we-learn-from-Elon-Musk`

and then you can navigate wherever you want (using the search quora box for example)
