### ISSUE TITLE
Aliexpress hard broken pop-up 

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6184]
### URL(s) where the issue occurs

`https://ali.ski/dr4oaP`
```
https://www.aliexpress.com/item/32858789424.html?dp=329eaca846424e261e242c804b49b980&af=102623&cv=47843&afref=&mall_affr=pr3&dp=329eaca846424e261e242c804b49b980&af=102623&cv=47843&afref=&mall_affr=pr3&aff_platform=aaf&cpt=1566769777621&sk=VnYZvQVf&aff_trace_key=c3a8bba525fa44dbb1602ec8cd50af4b-1566769777621-07132-VnYZvQVf&terminal_id=500264287d474ba090f02ddc611aae8d
```

### Describe the issue

Pop-up broken by `||mmstat.com^`?

```css
style='background-image: url("//ae01.alicdn.com/kf/HTB1dsNDc8TH8KJjy0Fi763RsXXa6.png");'
```

### Screenshot(s)

No see PNG, website block scrolling

![obraz](https://user-images.githubusercontent.com/35370833/63656591-10a85580-c796-11e9-99f0-305d0f147f3b.png)

### Versions

- Browser/version: Firefox 68.0.2
- uBlock Origin version: 1.21.2

### Settings

- Default + PL

### Notes
```
aliexpress.com##.next-overlay-wrapper:has(.newuser-container)
aliexpress.com##body:style(overflow: auto !important; padding: 0 !important;)
```

**Comment by okiehsch** [comment]
I can't reproduce with a default setup + PL lists.

![image](https://user-images.githubusercontent.com/16838044/63656632-9f1cd700-c796-11e9-8a9e-dd4ffab9a82e.png)

**Comment by krystian3w** [comment]
So also no remove this pop-up?

**Comment by okiehsch** [comment]
I thought the issue was about site breakgage, I can remove the popup in annoyances,

**Comment by krystian3w** [comment]
if uBO still like :xpath / :nth-ancestor https://github.com/uBlockOrigin/uAssets/issues/6184#issuecomment-524668811

**Comment by okiehsch** [comment]
Why not use your first suggested filter?

`aliexpress.com##.next-overlay-wrapper:has(.newuser-container)`

**Comment by okiehsch** [comment]
With your xpath filter
`aliexpress.com##.next-dialog-close:xpath(../..)`

I still have a "greyed" background.

![image](https://user-images.githubusercontent.com/16838044/63656742-9200e780-c798-11e9-9dbe-1efad85f53ff.png)


`aliexpress.com##.next-overlay-inner:nth-ancestor(1)`
would be the better filter.
