### ISSUE TITLE
WP Comment Button Stopped Working

### ISSUE THREAD

**Issue by TommyLeeBennett** [uBlockOrigin/uAssets#6187]
### URL(s) where the issue occurs

`https://www.washingtonpost.com/opinions/2019/08/26/is-trump-liar-or-fantasist-neither-option-is-good/`

### Describe the issue

The comment button in Washington Post articles no longer works with uBlockOrigin enabled. Normal function returns when uBlockOrigin is disabled for the site. You will need to be signed into a WP account to reproduce the issue.

### Screenshot(s)

Not applicable.

### Versions

- Browser/version: Chrome 76.0.3809.100 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.21.6

### Settings

- Default settings. Default filter lists.

### Notes

Let me know what to do! I'll gladly help ...

**Comment by mapx-** [comment]
Does this filter work ?
`@@||coral-talk.ext.nile.works/talk/static/embed.js`

**Comment by okiehsch** [comment]
Add
`@@||washingtonpost.com/*/default-article/tools/feature-loader/render.js$script,1p`
The comment button works on my end after adding it.

**Comment by okiehsch** [comment]
I don't need it on my end, you can update the uBO-unbreak list and remove 
`@@||washingtonpost.com/*/default-article/tools/feature-loader/render.js$script,1p`
I already uploaded that filter,
