### ISSUE TITLE
hentaihere anti-adblock [NSFW]

### ISSUE THREAD

**Issue by distren** [uBlockOrigin/uAssets#6193]
### URL(s) where the issue occurs

`https://hentaihere.com/m/S29071/1/1/`
(NSFW), and every other comic on the site

### Describe the issue

Banner ads on the top and bottom

### Versions

- Browser/version: [Firefox 69 DE]
- uBlock Origin version: [1.21.2]

### Settings

- "Fanboy Enhanced Tracking List" enabled, among other lists

### Notes

There's some code in js/app-*.js near `ARFfwk.Advertisement` that seems complicated to block.

`@@||hentaihere.com/app/assets/js/showads.js`

worked once (content is `ads=1`) but doesn't work now.

**Comment by mapx-** [comment]
I cannot reproduce the issue.
