### ISSUE TITLE
Kachelmannwetter.com: Anti Ad/Tracking Block

### ISSUE THREAD

**Issue by ericschdt** [uBlockOrigin/uAssets#6199]
### URL(s) where the issue occurs

`https://kachelmannwetter.com/`

### Describe the issue

If you open the page with uBlock Origin activated and additionally block some trackers, you will be redirected to
`https://kachelmannwetter.com/de/site/adblockuser/2/`

### Screenshot(s)

![Kachelmann com](https://user-images.githubusercontent.com/43318127/63836056-574da980-c968-11e9-91d8-170a999d0f92.png)

### Versions

- Browser/version: FF 68
- uBlock Origin version: 1.21.1

### Settings

- Added all non-language-specific filter lists minus uBO Experimental
- German Easy List
- Block 3rd party scripts and frames by default
- Block all found trackers on the website

### Notes

I tried a new FF with the default settings of uBO + Easy List Germany.
Once md-nx.com has been blocked, the anti adblock was triggered. However, it seems there are more triggers overall.

**Comment by mapx-** [comment]
> Block 3rd party scripts and frames by default, Block all found trackers on the website

using the default settings no issue anymore

**Comment by okiehsch** [comment]
@ericschdt fyi the triggers are `md-nx.com` and `tag.partner.mairdumont.com` the detection code is in 
`https://kachelmannwetter.com/js/function.js?v5.86a`
Breaking that first party script will also break site functionality.
