### ISSUE TITLE
uBlock Origin blocks flash plugin on a website

### ISSUE THREAD

**Issue by knzudgt** [uBlockOrigin/uAssets#62]
This post was removed from uBlock Origin's issues because I only suppose it was a filter-related issue.
An user (IDKwhattoputhere) suggested that "The logger shows there's a problematic filter in @reek's list".
Please be helpful in suggesting me if I eventually have to readdress this issue to **Reek**.

uBlock Origin blocks the visualisation of the player for www.supertennis.tv
I am using firefox 47.0 on a Ubuntu machine, with flash plugin version 11.2.202.621
To watch the stream I have to add the whole website to the whitelist, otherwise I am able to see only the white background

Ubuntu 14.04 LTS
uBlock Origin version: 1.7.0
Firefox version: 47.0
Flash plugin version 11.2.202.621

3rd party filters: uBlock filters + uBlock filters – Badware risks + uBlock filters – Privacy‎ + uBlock filters – Unbreak‎ + Anti-Adblock Killer | Reek + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Malware domains‎

My filters: @@||abysstream.com/ads.js

My rules: behind-the-scene * 3p noop + behind-the-scene * 3p-frame noop

![screenshot from 2016-06-11 14 20 18](https://cloud.githubusercontent.com/assets/15718033/15985571/976274aa-2ff2-11e6-8f72-c27521a69fd8.png)
![screenshot from 2016-06-11 14 21 22](https://cloud.githubusercontent.com/assets/15718033/15985570/9761f1c4-2ff2-11e6-8978-60ffe3030250.png)

**Comment by gorhill** [comment]
> This post was removed from uBlock Origin's issues

Don't make up stuff please: No post were _"removed from uBlock Origin's issues"_. The issue was **locked** because it was not the place to post such issues, as clearly stated in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment]
On my side, even when disabling uBO I can't play the video at the provided URL `www.supertennis.tv`.

**Comment by reek** [comment]
@knzudgt 
Sorry, I will remove the rule that causes this problem, pending please add this rule manually.

Rule:
`@@||p.jwpcdn.com/6/8/jwplayer.flash.swf`

https://github.com/reek/anti-adblock-killer/wiki/Add-filter

**Comment by knzudgt** [comment]
Many thanks @reek! I really appreciate, thank you very much.

Many thanks @gorhill. To be honest, I suppose that, apart from the creator and contributors of uBlock Origin, there might exist people like me, totally newbies on uBlock Origin, who do not have an encyclopedic knowledge of the rules which are stated here. So no intention from me to 'make up stuff' and I do not see any reason to show susceptibility on this. The post might be 'locked' as you say but I do not see it any more, so from my point of view it was removed, I did not use the verb 'remove' to show disrespect or offend or anything like this but because it was to my humble opinion correct. If you think that conceptually the verb 'remove' was wrong, please someone give me the link were I can retrieve my old post.

Also, apart from correct use of verbs, there was not possibility I could know that my issue was caused by someone's filter when I posted my message and before someone suggested me this possibility, and even after that, nobody, included you, confirmed that IDKwhattoputhere's suggestion was correct.

@gorhill you probably are unable to watch that stream because from your country it is not possible. Even I, when I use a vpn, am not allowed to watch it

**Comment by IDKwhattoputhere** [comment]
Just read the rules, no encyclopedic knowledge needed.
You made up that the post was removed. See:
https://github.com/knzudgt
https://github.com/gorhill/uBlock/issues?q=is%3Aissue+is%3Aclosed
Also you could have known that the issue was caused by a filter. Simply use the logger. Here's an explanation how: https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by knzudgt** [comment]
Thanks again @IDKwhattoputhere.

**Comment by gorhill** [comment]
> If you think that conceptually the verb 'remove' was wrong, please someone give me the link were I can retrieve my old post.

<https://github.com/gorhill/uBlock/issues/1711>.

**Comment by gorhill** [comment]
> there was not possibility I could know that my issue was caused by someone's filter when I posted my message

When a web page breaks, the default is to assume filter issue.

For issues proper to uBO's code base, one needs to make the case -- provide convincing evidence that there is an issue with uBO _itself_. This means taking the time to investigate and collecting evidence.
