### ISSUE TITLE
otakusave.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KagaKouko99** [uBlockOrigin/uAssets#6202]
URL(s) where the issue occurs
`https://otakusave.com/solo-leveling-chapter-45-bahasa-indonesia/`

Describe the issue
anti adblock

Versions
Browser/version: Google Chrome v76.0.3809.100 (Official Build) (64-bit)
uBlock Origin version: 1.21.6

Settings
Default

**Comment by mapx-** [comment]
The pages seem to be broken, no image, even adding the necessary filter to defeat the anti adblocking stuff
`@@||otakusave.com^$generichide`

**Comment by KagaKouko99** [comment]
yes it is broken but the animation site is not 
`https://otakusave.com/trickster-edogawa-ranpo-shounen-tanteidan-yori-subtitle-indonesia/`
