### ISSUE TITLE
https://www.cadlinecommunity.co.uk/

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#6204]
### URL(s) where the issue occurs

`https://www.cadlinecommunity.co.uk/hc/en-us/articles/115000475245-Free-Viewer`

### Describe the issue

Blank page

### Notes

`#@#.sidebar_advert`

**Comment by spirillen** [comment]
Hi, Try blocking [gatorleads.co.uk|zdassets.com|autodesk.com] in ex. your hosts file, adding all 3 of them to my local dns fixed the issue, they now returns NXDOMAIN and the site shows up

**Comment by mapx-** [comment]
`||gatorleads.co.uk^$3p`
@ryanbr

**Comment by spirillen** [comment]
Hi @mapx- why not `||gatorleads.co.uk^all` or what the right way is to completely block that domain ?? See [this](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/166) issue

**Comment by mapx-** [comment]
It's a normal marketing / ads site, not a malicious / mining / etc one

**Comment by spirillen** [comment]
> It's a normal marketing / ads site,

Exactly why I asking :smiley:

**Comment by mapx-** [comment]
`$all` if you can demonstrate they are pushing malicious redirections, popups, popunders
