### ISSUE TITLE
v.youku.com

### ISSUE THREAD

**Issue by discusssth** [uBlockOrigin/uAssets#6205]
`https://v.youku.com/v_show/id_XNDMwNzk2NTEzMg==.html?spm=a2ha1.12675304.m_2556_c_8261.d_4&s=247d76efbfbdefbfbd0e&scm=20140719.manual.2556.show_247d76efbfbdefbfbd0e`

![image](https://user-images.githubusercontent.com/45059308/63905121-c947f080-ca45-11e9-8470-940f17f1d83c.png)

**Comment by mapx-** [comment]
test these filters
```
||valipl.cp31.ott.cibntv.net^$media,redirect=noopmp3-0.1s,domain=youku.com
youku.com#@#.h5-ext-layer
@@||valipl.cp31.ott.cibntv.net$xhr,domain=youku.com
```

**Comment by discusssth** [comment]
@mapx-  works perfect !!  
thanks

**Comment by houzi-** [comment]
@mapx-

**Comment by houzi-** [comment]
@mapx- 
`youku.com##+js(nano-stb, , ,0)`
Hello! Ask you a question. "+Js (nano-stb, , ,0)" later in this rule is a bit unclear， 

-  `nano-stb` means: insert two scripts "nano-setInterval-booster.js" and "nano-setInterval-booster.js"?

-  ", , ,"  what does this parameter mean immediately?

-  "0"  what does this `0` mean?

**Comment by mapx-** [comment]
https://github.com/gorhill/uBlock/wiki/Resources-Library#nano-stbjs-

**Comment by houzi-** [comment]
OK! thanks
