### ISSUE TITLE
tvnow.de displaying preroll ads

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#621]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
`https://www.tvnow.de/ntv/n-tv-dokumentation/durchblick-am-himmel-lotsen-in-aktion-2017-08-12-00-10-00/player`

***new test link*** =

`https://www.tvnow.de/rtl2/curvy-supermodel/die-grosse-tanzchallenge/player`

### Describe the issue

i see preroll ads....when blocking preroll ads.....when blocked with filters from dynamic filtering antiadblock displays

geolock=
germany
requires flash
### Screenshot(s)

![chrome_2017-08-13_23-00-07](https://user-images.githubusercontent.com/20338483/29251907-546d84ca-807b-11e7-85cf-73a20982dc4a.png)

### Versions

- Browser/version: google chrome Version 60.0.3112.90 (Official Build) (32-bit)
- uBlock Origin version: 1.13.8

### Settings

- uBO's default settings+anti popads filter+ublock protector
tried alone with ublock origin also.....
### Notes

using justproxy vpn for geolock-germany

tried even easylist germany with default settings, still see preroll ads

**Comment by okiehsch** [comment]
> requires flash

Somebody else will have to try to find a solution.

**Comment by ghajini** [comment]
Why so😭..Google chrome has inbuilt flash support....

**Comment by ghajini** [comment]
this extension actually working.....
https://chrome.google.com/webstore/detail/tv-now-adblock-werbefreie/kpmcfodpngaecgfkmpjfiicfppkojcj

**Comment by ghajini** [comment]
anyone reproduce this issue of preroll ads....specifically german user @gorhill ,@monzta, @khrin....@mapx...@smed79....
with default ublock origin settings
can anyone help here???

**Comment by ghajini** [comment]
logger=
`https://streamable.com/mty2e`

console=
https://streamable.com/qdxga

antiadblock scripts @gorhill 
`https://cdn.static-fra.de/tvnow/app/7803d699.angular.js`
`https://cdn.static-fra.de/tvnow/app/aaea358e.main.js`
its deep inside.....

**Comment by SMed79** [comment]
Not sure if the videoplaza preroll ads can be blocked in this case... 

test
```
/advertisements?
||cdn.static-fra.de/now/vp/vp_$script,redirect=noopjs,domain=tvnow.de
```

**Comment by ghajini** [comment]
playback doesn't start then....when i click play button nothing works but i see this in console
`http://prntscr.com/g9gnd5`

logger output
`http://prntscr.com/g9gnlp`
`http://prntscr.com/g9gnn0`
`http://prntscr.com/g9gnoq`
`http://prntscr.com/g9gnq9`

**Comment by SMed79** [comment]
test again with **only**
`||cdn.static-fra.de/now/vp/vp_$object,redirect=nooptext,domain=tvnow.de`

**Comment by ghajini** [comment]
working.....thanx @SMed79
