### ISSUE TITLE
fandom.com

### ISSUE THREAD

**Issue by ip012** [uBlockOrigin/uAssets#6210]
https://www.fandom.com/curated/31-nights-on-twitter

When you go to "https://www.fandom.com/curated/31-nights-on-twitter", if ublock origin's disabled it shows the pictures on the page properly, but if it's enabled, some pictures don't load properly. (See screenshots.) How do you fix that? Thanks.

![fandom ublock origin off](https://user-images.githubusercontent.com/54560985/63982960-a68ff900-ca92-11e9-8e40-c56debc74ebd.jpg)

![fandom ublock origin on](https://user-images.githubusercontent.com/54560985/63982961-a68ff900-ca92-11e9-9f49-5f23fbdc79d2.jpg)

firefox 68.0.2 (64-bit)
ublock origin 1.21.2

**Comment by okiehsch** [comment]
What is your setup?
I can't reproduce with a default setup.

**Comment by krystian3w** [comment]
No broken by Fanboy Annoyance?

**Comment by krystian3w** [comment]
@ryanbr
