### ISSUE TITLE
Shortlinks [Ads]

### ISSUE THREAD

**Issue by RaveN0X87** [uBlockOrigin/uAssets#6217]
URL(s) where the issue occurs
```
https://amarsr.com/a//9cvfOs
https://tecnaudio.top/post/cTOEgyO
https://viralusablog.us/hkdG
https://hokiwiki.org/8qPKj
https://powerdatatech.com/NLIN
```

Describe the issue
fake continue button + ads

Versions
Browser/version: Google Chrome v76.0.3809.100 (Official Build) (64-bit)
uBlock Origin version: 1.21.6

Settings
Default

**Comment by mapx-** [comment]
fixed the sites with anti adblocking issues or / and popups

the others should be reported at easylist repository @ryanbr
