### ISSUE TITLE
After 10-11 sec  no Video playback @Chip.de 

### ISSUE THREAD

**Issue by akks1981** [uBlockOrigin/uAssets#622]
### URL(s) where the issue occurs

http://www.chip.de/news/AMD-Radeon-RX-Vega-64-Unboxing-der-GTX-1080-Konkurrenz_120604522.html

http://www.chip.de/news/Wer-bietet-mehr-Kostenlose-Virenscanner-gegen-Bezahlversion_120499954.html

http://www.chip.de/news/Telemedienauftrag-Reform-soll-ARD-Co.-mehr-Freiheiten-bringen_120376019.html
### Describe the issue

After 10-11 sec  no Video playback @Chip.de 

### Versions

- Browser/version: Firefox Setup 56.0b2x64
- uBlock Origin version: uBlock Origin 1.13.9rc1

### Settings

- uBO's default settings

### Notes

with ublock off it works, with ublock on not!

**Comment by okiehsch** [comment]
Update your uBO-filter list, should work fine after that.

**Comment by akks1981** [comment]
ok now it works. THX
