### ISSUE TITLE
uBlock Filters (built-in filter) breaks weather network website.

### ISSUE THREAD

**Issue by LocutusX** [uBlockOrigin/uAssets#6221]
### URL(s) where the issue occurs

`https://www.theweathernetwork.com/ca/weather/ontario/richmond-hill`

### Describe the issue

Website is broken when Built-in filter "uBlock Filters" is enabled.
In particular: the current temperature and "Feels Like" are both not shown when the filter is enabled.

### Screenshot(s)

No screenshot necessary, easy to reproduce following written instructions.

### Versions

- Browser/version: Google Chrome 76.0.3809.132,  64-bit
- uBlock Origin version: 1.21.6

### Settings

- n/a

### Notes

Leaving all filters at default EXCEPT disabling "uBlock Filters" is sufficient to workaround the issue, and cause the Weather Temperatures to be displayed on the above website.

**Comment by gwarser** [comment]
Still  broken? https://www.reddit.com/r/uBlockOrigin/comments/cxq13j/ublock_filters_break_weather_network/

**Comment by mapx-** [comment]
working fine for me

**Comment by LocutusX** [comment]
Yes, you need to add the following to My Filters to allow things to work (as someone mentioned on the Reddit thread):

@@||twnmm.com/js/*

**Comment by mapx-** [comment]
Do you update the lists ?

If yes, test these filters

```
||twnmm.com/js/*/dfpad$script,redirect=noopjs
||twnmm.com/js/*/adobe_audience_manager$script,redirect=noopjs
```
