### ISSUE TITLE
cablehd.online [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#6223]
URL(s) where the issue occurs

`http://cablehd.online/directv-sports-en-vivo/`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 76 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.21.6

Settings

Default

**Comment by KiLL4FuNK** [comment]
PLAY VIDEO

**Comment by mapx-** [comment]
- first 2 for anti adblocking, the others to get the video running. 
- still video ads for now
```
@@||hqq.tv^$generichide
@@||hqq.tv^$script,xhr,1p
@@||cdn.jsdelivr.net/npm/videojs-contrib-ads/$domain=hqq.tv
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=hqq.tv
@@||signal.netu.tv/$websocket,domain=hqq.tv
hqq.tv#@#+js(setTimeout-defuser, check, 100)
@@||deliver.vkcdnservice.com/api/spots/$script,domain=hqq.tv
@@||syndication.exosrv.com^*mp4link.com$xmlhttprequest,domain=imasdk.googleapis.com
@@||static.exosrv.com^$media,domain=hqq.tv
```

**Comment by okiehsch** [comment]
The "video" is black without sound on my end.

**Comment by okiehsch** [comment]
With your filterset I get the pre-roll ads followed by the mentioned blank 100 minutes long video.

![image](https://user-images.githubusercontent.com/16838044/64069659-27472480-cc4e-11e9-8843-261d22def80b.png)

**Comment by okiehsch** [comment]
````
hqq.tvh#@#+js(abort-on-property-read.js,  mscript)
@@||hqq.tv^$generichide
@@||hqq.tv^$script,xhr,1p
@@||cdn.jsdelivr.net/npm/videojs-contrib-ads/$domain=hqq.tv
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=hqq.tv
````
The blank video starts immediately without any pre-roll ads.

**Comment by okiehsch** [comment]
I have found a `hqq.tv` video with a working video.
`https://dangotoons.com/ver/sword-art-online-3-22`

````
hqq.tvh#@#+js(abort-on-property-read.js,  mscript)
@@||hqq.tv^$generichide
@@||hqq.tv^$script,xhr,1p
@@||cdn.jsdelivr.net/npm/videojs-contrib-ads/$domain=hqq.tv
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=hqq.tv
````
works fine on my end.

**Comment by mapx-** [comment]
yes, I see the timer going on but the video is blank

**Comment by okiehsch** [comment]
Actually `hqq.tv#@#+js(abort-on-property-read.js,  mscript)` is not necessary, though I don't see any mining activity on my end if I disable the filter.

Do you get any mining stuff after updating?

**Comment by mapx-** [comment]
No, I get no mining stuff.

**Comment by dumbusernameidk** [comment]
hqq.tv annoyances:

* debugger trap.
* console clearing.
* if debugger trap is bypassed you get a message saying "Don't open dev tools".

**Comment by mapx-** [comment]
for console 
`xhqq.*##+js(aopr, console.clear)`

**Comment by dumbusernameidk** [comment]
yep those worked.

**Comment by AndRo-Marian** [comment]
Some code was removed from this issue:
```
hqq.*##div[style="position: fixed; display: block; width: 100%; height: 100%; inset: 0px; background-color: rgba(0, 0, 0, 0); z-index: 300000;"]
```
And is not working anymore. I Refreshed the Firefox and reinstall the uBlock maybe the software was bugged. But seams to be a filter issue.

**Comment by mapx-** [comment]
> is not working anymore

What does not work ? example link ? browser ?

**Comment by AndRo-Marian** [comment]
Any browser. I can't single click to play the video because that div stops me to interact with the main video. I need to click like 24 time just to play a video because that code was removed.

**Comment by mapx-** [comment]
Try after updating the list

**Comment by AndRo-Marian** [comment]
Now is working as before. Thanks.
