### ISSUE TITLE
avhf.com doesn't load when blocking ads

### ISSUE THREAD

**Issue by josephcsible** [uBlockOrigin/uAssets#6237]
### URL(s) where the issue occurs

`http://www.avhf.com/html/Evaluation/HazardAttitude/Hazard_Attitude_Intro.htm`

### Describe the issue

When visiting avhf.com, the entire page is hidden, except for the single word "Advertisement".

### Versions

- Browser/version: Chrome 76.0.3809.132
- uBlock Origin version: 1.21.6

### Settings

- All defaults

### Notes

This happens because the entire content of the page is inside of `<div id="adsense">`, and is thus hidden by the `###adsense` rule from EasyList.

**Comment by llacb47** [comment]
File an issue on https://github.com/easylist/easylist as well

**Comment by josephcsible** [comment]
easylist/easylist#3951

**Comment by josephcsible** [comment]
EasyList fixed this on their end. Do we still need our fix?
