### ISSUE TITLE
chosun.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#6240]
### URL(s) where the issue occurs

`http://news.chosun.com/site/data/html_dir/2019/05/16/2019051600916.html`

### Describe the issue

Clipboard manipulation annoyance.

### Versions

- Browser/version: Firefox 69
- uBlock Origin version: 1.22.0

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin lists

**Comment by okiehsch** [comment]
Can you read the language?
`news.chosun.com##+js(set-constant.js, NewsSource.init, trueFunc)`
fixes the issue but I have no clue if that breaks anything.

**Comment by llacb47** [comment]
@yous ?

**Comment by okiehsch** [comment]
I found a "safer" solution.
`news.chosun.com##+js(aeld, copy, getSelection)`
that should not break anything and I will add it.
