### ISSUE TITLE
cutpaid.com [Popups/ads]

### ISSUE THREAD

**Issue by RaveN0X87** [uBlockOrigin/uAssets#6242]
URL(s) where the issue occurs
```
https://cutpaid.com/rhQX6cTL
https://tmearn.com/02iX
https://shopmoon.in/6aPaRLjK
```

Describe the issue
popups

Versions
Browser/version: Google Chrome v76.0.3809.100 (Official Build) (64-bit)
uBlock Origin version: 1.21.6

Settings
Default

**Comment by mapx-** [comment]
the last is about anti adblocking, open separate issues in the future
