### ISSUE TITLE
digitallearn.online [Popups]

### ISSUE THREAD

**Issue by KagaKouko99** [uBlockOrigin/uAssets#6243]
URL(s) where the issue occurs
`https://digitallearn.online/oZTakq`

Describe the issue
Popups

Versions
Browser/version: Google Chrome v76.0.3809.100 (Official Build) (64-bit)
uBlock Origin version: 1.21.6

Settings
Default

**Comment by dumbusernameidk** [comment]
also can't reproduce op are you sure you have:

`digitallearn.online##+js(window.open-defuser)`?

**Comment by spirillen** [comment]
No popup here either ...
