### ISSUE TITLE
Cosmetic filter broke page content

### ISSUE THREAD

**Issue by shnaps** [uBlockOrigin/uAssets#625]
### URL(s) where the issue occurs

[Link to one of the pages of site](http://abroadunderhood.ru/teroff13/). I have this problem on every non root page - http://abroadunderhood.ru/*. * - child page with problem. 

### Describe the issue

Cosmetic filter blocks content of page

### Screenshot(s)

[non working](https://prnt.sc/g89dvt) [working](https://prnt.sc/g89e0r)

### Versions

- Browser/version: [chrome 60]
- uBlock Origin version: [latest ublock from market]

### Settings

- default filter with russian adguard filter

### Notes

Some cosmetic filter broke page.

**Comment by gorhill** [comment]
Unable to reproduce with Adguard and RU AdList, I see no cosmetic filters applied on that page.

Use the logger to find out what cosmetic filter(s) from what lists are applied on your side.

There is no filters in uBO's own filters for `abroadunderhood.ru`, report to the proper filter list maintainers please.

**Comment by SMed79** [comment]
For me the content (tweets) is hidden by this filter `##.tweets` found in **Fanboy's Annoyance List**.

**Comment by shnaps** [comment]
So, what should i do with this?

**Comment by gorhill** [comment]
You will have to investigate what is the issue on your side, as said, I can't reproduce with defautl lists + AdGuard or default lists + AdGuard _ RU AdList. Also as said above: use the logger.

**Comment by shnaps** [comment]
Seems like problem is in Fanboy's Annoyance List.  [link](https://prnt.sc/g8h6n6)
With this filter disabled i see content.

**Comment by SMed79** [comment]
Next time give the correct infos (uBo Settings) :-P

Report you issue here https://github.com/ryanbr/fanboy-adblock/issues
