### ISSUE TITLE
[NSFW] members.metart.com|v2.metart.com [Popups/ads]

### ISSUE THREAD

**Issue by yspmedia** [uBlockOrigin/uAssets#6253]
### URL(s) where the issue occurs

```
https://v2.metart.com/model/candice-b/gallery/20190901/WATER_SPORT
https://v2.metart.com/galleries/latest
https://members.metart.com/model/candice-b/gallery/20190901/WATER_SPORT
https://members.metart.com/galleries/latest
```

### Describe the issue

Every time you log in, you get a popup banner and a banner line in top of the page

### Screenshot(s)

[Screenshot_2019-09-05_Candice_B_in_Water_Sport_-_MetArt](https://gitlab.com/yspmedia-web/support/uploads/e074ebe36551ee37e0dd744ee09dbd91/Screenshot_2019-09-05_Candice_B_in_Water_Sport_-_MetArt.jpg)

### Versions

- Browser/version: FF 68.0.2 (64-bit)
- uBlock Origin version: v1.22.0

### Settings

- ! 29/07/2019 https://members.metart.com
- members.metart.com##.custom-hover-cams.hidden-xs.hidden-sm.hidden-md > .pull-left

- ! 29/07/2019 https://www.systutorials.com
- www.systutorials.com###ez-cookie-dialog-wrapper

- ! 29/07/2019 https://members.metart.com
- members.metart.com##div.custom-cams-container.row:nth-of-type(4)

- ! 29/07/2019 https://v2.sexart.com
- v2.sexart.com##.show.modal.fade
- v2.sexart.com##.show.modal-backdrop.fade
- v2.sexart.com##[href="/upgrade"]
- v2.sexart.com##.live-girls-wrapper.hidden-sm.hidden-xs

- ! 29/07/2019 https://v2.metartx.com
- v2.metartx.com##.show.modal-backdrop.fade
- v2.metartx.com##.live-girls-wrapper.hidden-sm.hidden-xs
- v2.metartx.com##[href="/upgrade"] > p

- ! 29/07/2019 https://v2.thelifeerotic.com
- v2.thelifeerotic.com##.show.modal-backdrop.fade
- v2.thelifeerotic.com##[href="/upgrade"]
- v2.thelifeerotic.com##.live-girls-wrapper.hidden-sm.hidden-xs

### Notes

Haven't been able to locate the js script that do this :unamused: 

The source code can be found [here](https://gitlab.com/yspmedia-web/support/issues/3#note_212909407)

**Comment by dumbusernameidk** [comment]
these adult sites require you to pay for membership you'll have to most likely block the element on your own.

**Comment by mapx-** [comment]
- if you want to be helped you should provide an account for that site
- you can provide it in private for example on reddit 
https://www.reddit.com/r/uBlockOrigin/

to one of the guys in the team (on the right side)

**Comment by yspmedia** [comment]
Hi @mapx- and @dumbusernameidk 

After a lot of reading on how to build rules it looks like the following solves it

```
##.live-girls-wrapper.hidden-sm.hidden-xs
##.show.modal-backdrop.fade
##.show.modal.fade
##.upgrade-strip
##.upgrade-open.
##.cams.container.row
```

Optionally they should be prefixed with

```regex
[v2.sexart.com|v2.metartx.com|v2.thelifeerotic.com|(v2|members).metart.com]
```

However haven't seen any docs on this :grey_question: 

PS: don't have any reddit

**Comment by dumbusernameidk** [comment]
most likely these wont be added to ublock filter lists. should try for easylist but since it's a pay site it also seems negligible to add to easylist.

**Comment by mapx-** [comment]
ok, closing - filters for easylist and no account to test it (easylist guys will ask for an account too)

**Comment by yspmedia** [comment]
After a deeper investigation, I've come up with the following rules

```
/api/location$xmlhttprequest^domain=alsscan.com|domai.com|eroticbeauty.com|errotica-archives.com|eternaldesire.com|goddessnudes.com|live.tv|lovehairy.com|metart.com|rylskyart.com|sexart.com|stunning18.com|thelifeerotic.com|vivthomas.com
/api/upgradable-sites$xmlhttprequest^domain=alsscan.com|domai.com|eroticbeauty.com|errotica-archives.com|eternaldesire.com|goddessnudes.com|live.tv|lovehairy.com|metart..com|metart.com|rylskyart.com|sexart.com|stunning18.com|thelifeerotic.com|vivthomas.com
/media/promotions/^domain=metart.com|metart.com|sexart.com|thelifeerotic.com|vivthomas.com|lovehairy.com|errotica-archives.com|domai.com|goddessnudes.com|eroticbeauty.com|alsscan.com|rylskyart.com|eternaldesire.com|stunning18.com|live.tv
/sw.js$script^domain=alsscan.com|domai.com|eroticbeauty.com|errotica-archives.com|eternaldesire.com|goddessnudes.com|live.tv|lovehairy.com|metart.com|rylskyart.com|sexart.com|stunning18.com|thelifeerotic.com|vivthomas.com
alsscan.com,domai.com,eroticbeauty.com,errotica-archives.com,eternaldesire.com,goddessnudes.com,live.tv,lovehairy.com,metart.com,rylskyart.com,sexart.com,stunning18.com,thelifeerotic.com,vivthomas.com##.container.content > div:nth-of-type(1) > div > .hidden-xs
alsscan.com,domai.com,eroticbeauty.com,errotica-archives.com,eternaldesire.com,goddessnudes.com,live.tv,lovehairy.com,metart.com,rylskyart.com,sexart.com,stunning18.com,thelifeerotic.com,vivthomas.com##.live-girls.more-girls
alsscan.com,domai.com,eroticbeauty.com,errotica-archives.com,eternaldesire.com,goddessnudes.com,live.tv,lovehairy.com,metart.com,rylskyart.com,sexart.com,stunning18.com,thelifeerotic.com,vivthomas.com##.page-content > div:nth-of-type(3)
alsscan.com,domai.com,eroticbeauty.com,errotica-archives.com,eternaldesire.com,goddessnudes.com,live.tv,lovehairy.com,metart.com,rylskyart.com,sexart.com,stunning18.com,thelifeerotic.com,vivthomas.com##.upgrade-strip
! 09/10/2019 https://v2.metart.com
alsscan.com,domai.com,eroticbeauty.com,errotica-archives.com,eternaldesire.com,goddessnudes.com,live.tv,lovehairy.com,metart.com,rylskyart.com,sexart.com,stunning18.com,thelifeerotic.com,vivthomas.com##.col-xs-12.col-sm-12.col-md-12.col-lg-4
```

These rules should be applied for the following domains:
```
alsscan.com
domai.com
eroticbeauty.com
errotica-archives.com
eternaldesire.com
goddessnudes.com
live.tv
lovehairy.com
metart.com
rylskyart.com
sexart.com
stunning18.com
thelifeerotic.com
vivthomas.com
```

Please test and/or optimize these rules

**Comment by mapx-** [comment]
> ok, closing - filters for easylist and no account to test it (easylist guys will ask for an account too)

@ryanbr
