### ISSUE TITLE
latestseoupdate.com

### ISSUE THREAD

**Issue by lyndmi** [uBlockOrigin/uAssets#6254]
### URL(s) where the issue occurs

`https://latestseoupdate.com/ChFQuy`

### Describe the issue

Waiting countdown and detects if browser is out of focus or opening another tabs 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24647715/64347115-a85a3f00-cff3-11e9-861a-af1c4d59904c.png)

### Versions

- Browser/version: Opera 63.0.3368.53
- uBlock Origin version: 1.21.8

### Settings

- Default

### Notes

Request for countdown booster

**Comment by mapx-** [comment]
- out of focus is already fixed in uBo annoyances list => just enable it in uBo dashboard
- the countdown is managed on the server side => nothing we can do

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://latestseoupdate.com/T46T9`
