### ISSUE TITLE
educational site scholastic.com content being blocked

### ISSUE THREAD

**Issue by flashmasta** [uBlockOrigin/uAssets#6255]
### URL(s) where the issue occurs

<the school district's server name>.education.scholastic.com/r180ng/loader/

Note that each school district has a unique name at the start of the subdomains so any filter change would need to accommodate for that.

### Describe the issue

Content is being blocked in the educational course for Read180 because it contains the word "advertising" in it and is getting caught in a generic filter for that word we believe.  We contacted their help desk and they said it was because of "advertising" in the course the students are accessing and requested uBlock be removed to fix the issue.  When we turn off uBlock for the site it functions as expected.

### Screenshot(s)

https://imgur.com/a/dgNOakT

### Versions

- Browser/version: Chrome v76
- uBlock Origin version: v1.21.6

### Settings

All settings as default.  We use the Google Admin console to force-install the extension to users but do not apply any configurations on top of that.

### Notes

We have tested the content by having uBlock on and off for the site and when off it functions as expected.  Is it possible to whitelist *.scholastic.com?

**Comment by mapx-** [comment]
Provide an example of such site `something.education.scholastic.com` , otherwise we can check your issue

**Comment by flashmasta** [comment]
For example; https://h100003095.education.scholastic.com

**Comment by dumbusernameidk** [comment]
Maybe you can open the logger and check what filter list is blocking the site's content.

**Comment by mapx-** [comment]
I arrived here:
https://h100003095.education.scholastic.com/slms/studentaccess/read180ng

click read180 next generation, a new window opens .. ding the test for the name and so on, no issue for me

**Comment by mapx-** [comment]
ohhh, you have to provide me a test account 

send it here: `axis.trivia@gmail.com`

**Comment by mapx-** [comment]
like @dumbusernameidk said the alternative is open the logger and post here what filters are triggered

**Comment by gwarser** [comment]
About:

>We use the Google Admin console to force-install the extension to users but do not apply any configurations on top of that.

You can completely whitelist `scholastic.com` by adding it to Whitelist and pushing new configuration. However I don't know how to do this through Google Admin console, only can give you this: https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin (maybe this: https://github.com/gorhill/uBlock/issues/832#issuecomment-222020186 ?).

**Comment by flashmasta** [comment]
When you install a config file like that with a whitelist then your users are no longer allowed to add/remove their own sites so that isn't a great solution in our environment.

**Comment by dumbusernameidk** [comment]
Can't fix anything if we don't know what's causing the breakage.

**Comment by mapx-** [comment]
@flashmasta did you use the logger ?

**Comment by gwarser** [comment]
https://github.com/gorhill/uBlock/wiki/The-logger
