### ISSUE TITLE
dmi.dk [ads]

### ISSUE THREAD

**Issue by spirillen** [uBlockOrigin/uAssets#6256]
### URL(s) where the issue occurs

`dmi.dk`

### Describe the issue

Banners on page

### Screenshot(s)

Shouldn't be needed

### Versions

- Browser/version: F 68.0.2 (64-bit)
- uBlock Origin version: v1.22.0

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes
These rules solves the banner issues

```
www.dmi.dk##.hidden-print.add-top.add-container
www.dmi.dk###adMiddle
www.dmi.dk##div.columns.small-12.medium-6.large-6:nth-of-type(1)
```
Please feel free to optimize :smiley:

**Comment by mapx-** [comment]
report here for Denmark
https://github.com/DandelionSprout/adfilt/issues

@DandelionSprout
