### ISSUE TITLE
Poki html5 games as broken...

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6257]
### URL(s) where the issue occurs

example game: 

`https://www.paisdelosjuegos.com.ar/juego/stickman-hook.html`

```
poki.at
poki.be
poki.by
poki.cn
poki.co.il
poki.com
poki.com.br
poki.com/ar
poki.com/id
poki.com/kr
poki.com/ru
poki.com/th
poki.com/ua
poki.cz
poki.de
poki.dk
poki.gr
poki.it
poki.jp
poki.nl
poki.no
poki.pl
poki.pt
poki.ro
www.1001oyun.com
www.123pelit.com
www.hrajhry.sk
www.jeuxjeuxjeux.ch
www.jeuxjeuxjeux.fr
www.megajatek.hu
www.megaspel.se
www.moiteigri.com
www.paisdelosjuegos.cl
www.paisdelosjuegos.co.ve
www.paisdelosjuegos.com.ar
www.paisdelosjuegos.com.co
www.paisdelosjuegos.com.do
www.paisdelosjuegos.com.ec
www.paisdelosjuegos.com.mx
www.paisdelosjuegos.com.pa
www.paisdelosjuegos.com.pe
www.paisdelosjuegos.com.uy
www.paisdelosjuegos.cr
www.paisdelosjuegos.es
www.spielyeti.ch
www.trochoi.net
```

[](https://github.com/MajkiIT/polish-ads-filter/issues/14605)

### Describe the issue

Endless load lop circles... 

![obraz](https://user-images.githubusercontent.com/35370833/64451788-36fab900-d0e5-11e9-8f82-b34bd3499b9a.png)

`https://www.paisdelosjuegos.com.ar/juego/stickman-hook.html`

### Screenshot(s)

![obraz](https://user-images.githubusercontent.com/35370833/64451966-99ec5000-d0e5-11e9-813e-c05eb6eb3c9d.png)

### Versions

- Browser/version: Firefox 69
- uBlock Origin version: 1.21.2

### Settings

- Default + PL

### Notes

Please test all languages, no fix only Argentina.

**Comment by mapx-** [comment]
if all those sites are using poki frames, test:
`@@||game-cdn.poki.*^$frame,1p`

if no, provide more details, test pages, etc

**Comment by krystian3w** [comment]
OK. Work for Argentina domain and USA domain (`poki.com`) so should fix all.

@ryanbr - bad `&ref=*&tag=` privacy or play games.

**Comment by krystian3w** [comment]
Related: https://github.com/uBlockOrigin/uAssets/issues/11370
