### ISSUE TITLE
iqiyi.com [preroll video ad] 

### ISSUE THREAD

**Issue by discusssth** [uBlockOrigin/uAssets#6258]
`https://www.iqiyi.com/v_19rt3q8008.html?src=focustext_1_20130410_2`

![20190907105203](https://user-images.githubusercontent.com/45059308/64468983-9d232280-d15d-11e9-8e0c-dc763f6935fc.png)

**Comment by discusssth** [comment]
The problem still exists. Can someone help me? Thank you

**Comment by discusssth** [comment]
There may be a geo lock that requires the IP of the Chinese region to reproduce the problem.

**Comment by ZaphodBeebblebrox** [comment]
Does 
```
||data.video.iqiyi.com/videos/other/*$xhr,1p
||static.iqiyi.com/js/common/mars_v.js$script,1p
````
 work for you?  I have trouble telling as the video buffers for me after the first 15 seconds even if uBO is disabled.

**Comment by discusssth** [comment]
@Zalastax 
works for me,  thank you very much.
This rule successfully removed the video ad.

**Comment by discusssth** [comment]
@uAssets Stuff
 please commit it
