### ISSUE TITLE
AAK not work for clubedohardware.com.br

### ISSUE THREAD

**Issue by HenriqueFel** [uBlockOrigin/uAssets#626]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

https://s18.postimg.org/qojj3ky7d/Sem_t_tulo.jpg

### Versions

- Browser/version: Firefox 54.0.1 32 bits
- uBlock Origin version: 1.13.0.8

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by okiehsch** [comment]
It works with uBO-default settings on my end, so the issue is with AAk, you should report
here: https://gitlab.com/xuhaiyang1234/AAK-Cont/issues

**Comment by ghajini** [comment]
tamiltunes.live using noadblock

**Comment by SMed79** [comment]
> tamiltunes.live using noadblock

Better if you don't post anywhere, create new issue for each site with details [#627](https://github.com/uBlockOrigin/uAssets/issues/627).
