### ISSUE TITLE
StopAd.io

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6262]
broken by EasyPrivacy:

`@@||api.stopad.io/link/v1/pixel?refSource=https://www.google.com/*$image,first-party`

I have endless loop loading as once allow tracker, ~~no tested redirect~~.

if anybody find more broken websites, possible use:

```
*/v1/pixel?$image,redirect=1x1.gif
```

---

for reproduce need open from e.g. Google:

```
https://www.google.com/search?q=StopAd.io
```

**Comment by llacb47** [comment]
Ironic, the ad blocker has trackers on their website.

The `refSource` param will change to whatever the referer is, so better filter is:

`||api.stopad.io/link/v1/pixel$image,redirect=1x1.gif`

**Comment by krystian3w** [comment]
Or abort EOL app if I tested downlad.

https://hub.filterlists.com/t/hall-of-shame-of-low-quality-adblockers/22/17

**Comment by krystian3w** [comment]
Who block `raven.min.js` no saw in logger 2 h ago.

**Comment by llacb47** [comment]
> Who block `raven.min.js` no seen in logger 2h ago.

I do, it's one of my lists... maybe in others too

**Comment by krystian3w** [comment]
Hmm..., ok.
