### ISSUE TITLE
cvs.com [Breakage]

### ISSUE THREAD

**Issue by perfectdarkzero** [uBlockOrigin/uAssets#6263]
### URL(s) where the issue occurs

Any product page. Example:
`https://www.cvs.com/shop/listerine-cool-mint-antiseptic-mouthwash-for-bad-breath-prodid-1011676`

### Describe the issue

Page loads correctly initially but subsequently becomes blank after a failed request to `https://www.cvs.com/shop-assets/js/VisitorAPI.js`

### Versions

- Browser/version: Chrome 76.0.3809.132 (Windows 10)
- uBlock Origin version: 1.22.0

### Notes

Can be fixed by adding this rule (based on existing rules for other domains):
`@@||cvs.com/shop-assets/js/VisitorAPI.js$script,first-party`

**Comment by krystian3w** [comment]
Also geolocked for US only 🇺🇸...
