### ISSUE TITLE
mediapunta.net [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#6264]
URL(s) where the issue occurs

`http://mediapunta.net/directv-sports-plus-en-vivo/`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 76 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.22.0

Settings

Default

**Comment by krystian3w** [comment]
Need scriplet or network filter - https://github.com/uBlockOrigin/uBlock-issues/issues/688

**Comment by okiehsch** [comment]
Works fine on my end if I add
````
@@||mediapunta.net^$generichide
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js$script,domain=mediapunta.net
soloveo.com##+js(nowebrtc)
````

**Comment by krystian3w** [comment]
Works better also please remove: `Anuncios` containers.

**Comment by KiLL4FuNK** [comment]
Anti-Adblock
