### ISSUE TITLE
Protect firefox from instart logic/g00

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6265]
@mapx- 

This issue is FOR  ***FIREFOX desktop*** ,
Seperate issue is opened for chrome at UBO EXTRA REPO

### URL(s) where the issue occurs
`https://www.atvrider.com/`
`baggersmag.com`
`https://www.diversitybestpractices.com/`
`floridatravellife.com`
`https://www.hotbikeweb.com/`
`https://www.scubadiving.com/`
`https://www.sportdiver.com/`
`https://www.streetchopperweb.com/`
`https://www.utvdriver.com/`
`https://www.workingmother.com/`

### Describe the issue
instart logic loading....
longer loading time of sites

### Versions

- Browser/version: firefox 69.0
- uBlock Origin version: 1.22.0

### Settings

- uBO's default settings

### Notes

using decentraleyes
ip= indian 

would you also lookup for `fundingchoicesmessages.google.com` 3rd party for its tracking purpose or not?

**Comment by mapx-** [comment]
`fundingchoicesmessages.google.com` we have already this sort of filters, report any other site using it and will see case by case

**Comment by ghajini** [comment]
Okay will leave `fundingchoicesmessages.google.com` towards easyprivacy @ryanbr fyi

**Comment by llacb47** [comment]
I thought Instart only affected
Chrome?

**Comment by mapx-** [comment]
> I thought Instart only affected
> Chrome?
https://github.com/uBlockOrigin/uAssets/issues/227#issuecomment-325188758
