### ISSUE TITLE
dplay.dk

### ISSUE THREAD

**Issue by lyndmi** [uBlockOrigin/uAssets#6266]
### URL(s) where the issue occurs

`https://www.dplay.dk/programmer/politijagt`

### Describe the issue

Adblock warning message

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24647715/64492894-8bcf3880-d279-11e9-831d-fe19d714f942.png)

### Versions

- Browser/version: Opera 63.0.3368.71
- uBlock Origin version: 1.21.8

### Settings

- All default

### Notes

May require danish VPN but I think you can watch Episode 1 without VPN and without account

**Comment by llacb47** [comment]
Nope, region restricted. `Du har ikke lov til at se denne video i dit område.`

**Comment by llacb47** [comment]
Test `@@||imasdk.googleapis.com/pal/sdkloader/pal.js$script,domain=dplay.dk`

**Comment by mapx-** [comment]
@DandelionSprout 

yes, it seems `@@||imasdk.googleapis.com/pal/sdkloader/pal.js$script,domain=dplay.dk`
it's ok

**Comment by DandelionSprout** [comment]
Using `@@||imasdk.googleapis.com/pal/sdkloader/pal.js$script,domain=dplay.dk` causes unskippable ads for 7-Eleven to be played before the videos, so I declare that fix to be unsatisfactory for my list, and that a better fix is needed.

**Comment by mapx-** [comment]
still working
`||imasdk.googleapis.com/pal/sdkloader/pal.js$script,redirect=noopjs,domain=dplay.dk`

**Comment by mapx-** [comment]
working for me
```
||imasdk.googleapis.com/pal/sdkloader/pal.js$script,redirect=noopjs,domain=dplay.dk
||dni-adops-proxy-prod-adopsmediaconverter.mercury.dnitv.com/$media,redirect=noopmp3-0.1s,domain=dplay.dk
```

**Comment by DandelionSprout** [comment]
That seems much better to me as well. Will add to my list right away.

**Comment by mapx-** [comment]
It's a fix, not a "much better".

**Comment by DandelionSprout** [comment]
I meant of course that the fix was much better than the first attempt at a fix, if there was any confusion about it.

**Comment by mapx-** [comment]
@lyndmi  you should use `NOR, DNK, ISL: Dandelion Sprouts nordiske filtre`

**Comment by lyndmi** [comment]
Thank you. It worked!

**Comment by spirillen** [comment]
Hey guys

I know this is a bit older issue, but as I was working on one of my own older [tickets](http://wiki.mypdns.org/ticket/101#comment:3) i found this issue as one of the only related whit a commit that could help solving the issue.

Would other records I have been able to find, that could  be interesting to block is:

```
dni-adops-proxy-prod-adopsmediaconverter.mercury.dnitv.com
dni-adops-proxy-uat-adopsmediaconverter.mercury.dnitv.com
[dws.reporting.dnitv.com|reporting.dnitv.com]
static.dnitv.com
```

My hope is now that anybody with access to `dplay.com` if they could give a report on blocking these domains _and_ if any of them actually still is active
