### ISSUE TITLE
google.com (Google self-promotion on 'site:' searches)

### ISSUE THREAD

**Issue by jakejarvis** [uBlockOrigin/uAssets#6268]
### URL(s) where the issue occurs

`https://www.google.com/search?q=site%3Ajarv.is`
`https://www.google.com/search?q=site%3Agithub.com`

### Describe the issue

A "Try Google Search Console" banner ad/promotion has started appearing when I use the `site:` paramater when searching Google on desktop.

Simply blocking `###wmxmsg` cosmetically seems to have worked.

### Screenshot(s)

<img width="791" alt="Screen Shot 2019-09-08 at 4 05 31 PM" src="https://user-images.githubusercontent.com/1703673/64493960-e1451e80-d254-11e9-9748-87c1b207200e.png">

<img width="1128" alt="Screen Shot 2019-09-08 at 4 05 52 PM" src="https://user-images.githubusercontent.com/1703673/64493957-ca063100-d254-11e9-90f0-126b26232725.png">

### Versions

- Browser/version: Firefox 70.0b4 on macOS 10.14.6
- uBlock Origin version: v1.22.0

### Settings

For the sake of this issue I've tested this in a fresh browser with factory lists/settings.

### Notes

No clue if this is something Google has just added or if an existing rule needs to be updated (I'm guessing the former).

Seems 100% consistent on domains that Google knows that I own (via my Google Analytics account and some other creepy methods I'm sure) and sometimes appears for domains that I don't (ex: `site:github.com`). 

Thanks! ☺️

**Comment by mapx-** [comment]
it's stuff for fanboy's annoyances list
@ryanbr
