### ISSUE TITLE
Adblocker warning https://qoshe.com/ and http://www.holedk.com/

### ISSUE THREAD

**Issue by Jose1971AB** [uBlockOrigin/uAssets#6269]
Good morning. 
Excuse my level of English, I am with the help of the google translator.

### URL(s) where the issue occurs
`https://qoshe.com/`
`http://www.holedk.com/` (Adult page)

### Describe the issue
In `https://qoshe.com/` just when you open the page the notice appears. Sometimes it can be closed and the page works, but sometimes it breaks.

At `http://www.holedk.com/` when you click on the play button of any video the warning appears and does not let it play, it happens in all that I have tried.

When the notice appears in any video, I do not consider it appropriate to send the specific url, but if you require it, I will send it.

### Screenshot(s)
`https://qoshe.com/` --> https://ibb.co/r4f7mjf
`http://www.holedk.com/` --> `https://ibb.co/FKbZZKJ` [NSFW]

### Versions
- Browser/version: **Firefox 64 Bit 69.0**
- uBlock Origin version: **1.22.0**

### Settings
**My configuration of uBlock origin. See the images ->**

**https://ibb.co/Pg4ksR6**
**https://ibb.co/SXC87Tw**
**https://ibb.co/VBrFv5K**

Regards, and thank you very much.

**Comment by okiehsch** [comment]
I fixed `https://qoshe.com`.
I can't reproduce the issue at `http://www.holedk.com` all videos I tried play without any anti adblock message.

**Comment by uBlock-user** [comment]
@Jose1971AB 

add `hqq.tv##+js(set-constant, checkad, false)` and try.

**Comment by Jose1971AB** [comment]
**Good afternoon, @okiehsch @uBlock-user**

I answer both of you ...

> **@okiehsch**
> I fixed https://qoshe.com.
> I can't reproduce the issue at http://www.holedk.com all videos I tried play without any anti adblock message.

I would swear that the warning appeared on http://www.holedk.com, and you could check it by the image I sent you. I've tried 8-10 videos and it works, I don't know what will have happened.

**I have done the tests after updating uBlock, maybe that's why it works now. Anyway I will have to go watching it to see what happens.**

> **@uBlock-user**
> add hqq.tv##+js(set-constant, checkad, false) and try.

I could not check that parameter because it seems to work now. **If the AdBlocker warning reappears, I will add it to check it**. I'll have it written down in case the warning reappears.

Greetings friends ... and thank you very much for everything
