### ISSUE TITLE
Site pops up with a window displaying "Request failed: error"

### ISSUE THREAD

**Issue by EnthusiastAnon** [uBlockOrigin/uAssets#6272]
### URL(s) where the issue occurs

`https://www.motika.com.mk/smeshni-sliki-1909/smesnite-12-8/`

### Describe the issue

When I switch between pictures (on the arrows left and right) it displays a window with error.

### Screenshot(s)

https://i.imgur.com/RKnyzOW.jpg

### Versions

- Browser/version: Firefox 69.0
- uBlock Origin version: 1.22.0

### Notes

Sorry I'm not able to do any investigation...

**Comment by uBlock-user** [comment]
`motika.com.mk##+js(aopr, myCall)` fixes it.

**Comment by EnthusiastAnon** [comment]
> 
> 
> `motika.com.mk##+js(aopr, myCall)` fixes it.

Am I easily able to implement this at my end or do I need to wait for another version of uBlock?

**Comment by mapx-** [comment]
just update unbreak list

**Comment by uBlock-user** [comment]
You can add it to my filters.

**Comment by EnthusiastAnon** [comment]
Thank you both. I love when a community is helpful and fast like this. Keep up the good work guys.
