### ISSUE TITLE
[POPup/ADS] zerodot1.gitlab.io

### ISSUE THREAD

**Issue by spirillen** [uBlockOrigin/uAssets#6273]
### URL(s) where the issue occurs

`https://zerodot1.gitlab.io/CoinBlockerListsWeb/downloads.html`

### Describe the issue

Click on any of the "Download" buttons an a popup for redirection appears...

### Screenshot(s)

Unable to upload, as github wouldn't allow me

### Versions

- Browser/version: FF 69.0 (64-bit)
- uBlock Origin version: v1.22.2

### Settings

- [List here all the changes you made to uBO's default settings]

**Comment by uBlock-user** [comment]
right click also disabled, so ironic.

**Comment by dumbusernameidk** [comment]
I dont even get any popups.

**Comment by mapx-** [comment]
added @uBlock-user  filter

**Comment by uBlock-user** [comment]
`zerodot1.gitlab.io##p:has([href*="https://amzn.to"])`

for the amazon ad when the modal popups for the download link
