### ISSUE TITLE
Weather.us - Anti-Ad Block

### ISSUE THREAD

**Issue by Skates1616** [uBlockOrigin/uAssets#6276]
### URL(s) where the issue occurs

`https://weather.us/`

### Describe the issue

Using NanoDefender / uBlock combo, the site sends you to a anti-adblock site after a few minutes of being on their main page.  `https://weather.us/site/adblockuser/10/`

### Screenshot(s)

https://i.imgur.com/AmwIkV0.png

### Versions

- Browser/version: Chrome 77.0.3865.70
- uBlock Origin version: v1.22.2

### Settings

Only change is the addition of NanoDefender and its subsequent filter lists/advanced settings that needed to be added.

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by Dormanil** [comment]
Any issues that happen on `weather.us` also pertain to `meteologix.com` and `kachelmannwetter.com`, as they are the same service under different names.

**Comment by okiehsch** [comment]
Both domains work fine on my end with up to date filters.

**Comment by Skates1616** [comment]
Doesn't work here, it loads the same link after doing a manual update to filters.

Is there a specific filter that I should be selecting for this?

On Mon, Sep 9, 2019 at 7:02 PM okiehsch <notifications@github.com<mailto:notifications@github.com>> wrote:

Both domains work fine on my end with up to date filters.

**Comment by mapx-** [comment]
tested again, all fine here.

filters
```
@@||meteologix.com/js/ads.js$script,1p
@@||weather.us/js/ads.js$script,1p
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=meteologix.com|weather.us
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$script,domain=meteologix.com|weather.us
meteologix.com,weather.us##.gad-billboard-pos
meteologix.com,weather.us##[id^="aswift"]
@@||meteologix.com^$generichide
@@||weather.us^$generichide
```

Be sure you have no other blocking extension enabled and use the default settings in uBo.
