### ISSUE TITLE
theweedtube.com - showing video ads

### ISSUE THREAD

**Issue by Sopor** [uBlockOrigin/uAssets#6277]
### URL(s) where the issue occurs

`https://www.theweedtube.com/video/huge-thc-crystals-24838`

### Describe the issue

It seems that every video is starting with a video ad. So is this possible to remove?

### Versions

- Browser/version: Firefox 69
- uBlock Origin version: 1.22.2

**Comment by llacb47** [comment]
You made a typo and put mp3 instead of mp4 in the commit @mapx-

**Comment by mapx-** [comment]
no typo, I prefer mp3 (0.1 s) instead of mp4 (1 s)
