### ISSUE TITLE
Ads on apps.facebook.com

### ISSUE THREAD

**Issue by songdavid98** [uBlockOrigin/uAssets#628]
### URL(s) where the issue occurs

`[https://apps.facebook.com/tetris_battle/]`

I'm not sure if it is only Tetris Battle on Facebook, but if there are ads here, there are probably adds on other Facebook ads as well.

### Describe the issue

There are ads on the sides of the app. The advertisements started appearing a few days ago, I believe. I don't really remember when.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/9341394/29372162-56393c1e-8278-11e7-8ea6-32d4264d7f38.png)

### Versions

- Browser/version: Windows 10 Google Chrome Version 60.0.3112.101 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.13.8

### Settings

- I have never changed any settings before, so I guess they are default.

### Notes

The ads weren't there in the past.

**Comment by songdavid98** [comment]
Here's another screenshot

![image](https://user-images.githubusercontent.com/9341394/29372680-d37fefd2-8279-11e7-8b7f-c8ed5f58afb3.png)

**Comment by gorhill** [comment]
Does this work?

    tbc.tetrisfb.com##script:inject(abort-current-inline-script.js, btoa, upManager)

**Comment by songdavid98** [comment]
ah, it worked! Thank you!
