### ISSUE TITLE
Washington Post anti-Adblock

### ISSUE THREAD

**Issue by TemporaryUsername12481** [uBlockOrigin/uAssets#6280]
### URL(s) where the issue occurs

`https://www.washingtonpost.com/national-security/trump-pronounces-taliban-agreement-dead-and-peace-talks-over/2019/09/09/d302135a-d33f-11e9-9610-fb56c5522e1c_story.html`

### Describe the issue

Anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/11603778/64619572-4feabf00-d3b0-11e9-83fc-696ea6c0d268.png)

### Versions

- Browser/version: Chrome 76.0.3809.102
- uBlock Origin version: v1.22.2

### Settings

Medium mode, although issue persists in easy mode
All built-in filter lists enabled except for regional lists.

### Notes

Already a few issues about this but they're all closed.

**Comment by mapx-** [comment]
Update uBo lists the test again

**Comment by TemporaryUsername12481** [comment]
Wow, you are impressive.

**Comment by mapx-** [comment]
Well, it was fixed 9 hours again, it's why I asked you to update the lists

**Comment by TemporaryUsername12481** [comment]
Yeah, I updated before making the issue but forgot that I had to purge the cache first.
