### ISSUE TITLE
Warning adblocker adult sites and pop-up pages (I don't put the pages in the title by discretion)[NSFW]

### ISSUE THREAD

**Issue by Jose1971AB** [uBlockOrigin/uAssets#6281]
Hello friends again.

Sorry for my level of English, I am with the help of the google translator.

### URL(s) where the issue occurs

[**https://www.peliculaspornomega.net/
https://iguarras.com/
https://solopajeros.com/**]

### Describe the issue

**In the 3 pages**, when clicking on the play button the warning appears and at the same time an advertising tab opens.

### Screenshot(s)

- Adblocker warning screenshots
[https://www.peliculaspornomega.net/] **--> https://ibb.co/XD2LDdX**
[https://iguarras.com/] **--> https://ibb.co/5KJscq1**
[https://solopajeros.com/] **--> https://ibb.co/4KT0vDf**

- Capture pop-up ad tab
**https://ibb.co/LR3n4t0**

**Note**: I only put an example capture of this because it is the same in all three

### Versions

- Browser/version: **Firefox 64 Bit 69.0**
- uBlock Origin version: **1.22.2**

### Settings

**My configuration of uBlock origin. See the images ->**

**https://ibb.co/Pg4ksR6
https://ibb.co/SXC87Tw
https://ibb.co/VBrFv5K**

### Notes

If you want me to provide some more information let me know

Regards, and thank you very much.

**Comment by dumbusernameidk** [comment]
For `peliculaspornomega.net` and `iguarras.com` I added:

`||publicidadpro.com^`
`||ishort.site^`
`##.dimmed`  --Fixes popup on video player.

And `solopajeros.com`:
`||solopajeros.com/*.php$script,1p`

I don't get any anti-adblock just the popups and other junk (fake push notifications).

**Comment by okiehsch** [comment]
> `peliculaspornomega.net,iguarras.com##.dimmed`

are you sure about that?
On my end it is 
````
peliculaspornomega.net##.dimmed
iguarras.com###dimmed
````
I can add your filters as well if those are needed for you.

**Comment by dumbusernameidk** [comment]
Ah I see the sites were using the same setup so I assumed the video player issue would be the same as well.

**Comment by Jose1971AB** [comment]
Greetings to both of you ... @okiehsch @dumbusernameidk

It seems to have been fixed ...

> @dumbusernameidk
> I don't get any anti-adblock just the popups and other junk (fake push notifications).

Yes, but from the images I sent you, you will have been able to verify that the adblocker warning appears.

Thank you very much friends ... greetings
