### ISSUE TITLE
tally-weijl.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6282]
### URL(s) where the issue occurs

`https://www.tally-weijl.com/en_UK/square-neck-hh-7612958587309.html?frosmo=1`

### Describe the issue

Broken shop by generic EasyPrivacy Filter

### Screenshot(s)

![Screenshot_20190911-152604](https://user-images.githubusercontent.com/35370833/64701376-f619f000-d4a8-11e9-904a-64781ce3e6a8.png) | ![Screenshot_20190911-152658](https://user-images.githubusercontent.com/35370833/64701389-fc0fd100-d4a8-11e9-8d7a-3e6b5cf0e0bf.png)
--- | ---
Broken | What should visible

### Versions

- Browser/version: Firefox 68.1
- uBlock Origin version: 1.22

### Settings

- default

### Notes

    https://d2wzl9lnvjz3bh.cloudfront.net/frosmo.easy.js

[](https://github.com/MajkiIT/polish-ads-filter/issues/14648)

**Comment by mapx-** [comment]
@ryanbr

**Comment by krystian3w** [comment]
```
https://www.tally-weijl.com/en_UK/new-in/new-arrivals-de.html?market=en_UK&pageId=0&category=1639&frosmo=1
```

waiting for:

    @@||tally-weijl-product-listing.cs-eu-west-1.frosmo.com/tally-weijl-product-listing/products$xmlhttprequest,domain=www.tally-weijl.com
