### ISSUE TITLE
videoplayerscript.club

### ISSUE THREAD

**Issue by bugreporter6** [uBlockOrigin/uAssets#6283]
`https://videoplayerscript.club/rounder/rounderak.php`

Malicious redirect.

**Comment by mapx-** [comment]
https://forums.lanik.us/viewtopic.php?f=62&t=43483

**Comment by bugreporter6** [comment]
@mapx- Yes, that's me, but you should add `||videoplayerscript.club^$document` in the uBlock filters – Badware risks
