### ISSUE TITLE
The built-in Privacy and Unbreak filters break Disqus comments on cyclingnews.com

### ISSUE THREAD

**Issue by biwqn** [uBlockOrigin/uAssets#6284]
### URL(s) where the issue occurs

Any article off of `http://www.cyclingnews.com/`.
For example:
`https://www.cyclingnews.com/news/we-did-a-team-time-trial-of-220km-says-vuelta-a-espana-stage-winner-gilbert/`

(Note that it takes a couple seconds for the Disqus comments to load at the bottom of the page.)

### Describe the issue

The built-in Privacy and Unbreak filters break Disqus comments on cyclingnews.com. If you have either the Privacy or Unbreak filters enabled, Disqus comments at the very bottom of the article do not load. When the Privacy and Unbreak filters are disabled, the Disqus comments successfully load.

This has been happening for many weeks, even with latest Ublock origin versions.

### Screenshot(s)

N/A, as very easy to see. Make sure to go to the very bottom of each article page to see the Disqus comments or lack thereof. Note that it takes a couple seconds for the Disqus comments to load at the bottom of the page.

### Versions

- Browser/version: Google Chrome Version 77.0.3865.75 (Official Build) (64-bit)
- uBlock Origin version: 1.22.2

### Settings

- No default changes, easy mode.

### Notes

Turning off/on the Privacy and Unbreak filters and loading those articles (shift-control/command-r to not use the browser cache).

**Comment by okiehsch** [comment]
I can reproduce the issue but it is unrelated to the Unbreak list.
I am not sure how the Unbreak list is causing issues on your end.
Anyway `@@||googletagmanager.com/gtm.js$script,domain=cyclingnews.com` fixes the issue on my end.
