### ISSUE TITLE
iqiyi.com [Do not display the bullet screen]

### ISSUE THREAD

**Issue by lanmaoaiwo** [uBlockOrigin/uAssets#6290]
### URL(s) where the issue occurs

`[iqiyi.com]`

### Describe the issue

[Do not display the bullet screen]

### Versions

- uBlock Origin version: [v1.22.2]

### Settings

- [uBlock filters​​​​​​​​​]

**Comment by discusssth** [comment]
没问题啊，说清楚一些，截图或录视频更好。      你UBO都订阅了什么规则？

**Comment by mapx-** [comment]
> Do not display the bullet screen

screenshot ?
