### ISSUE TITLE
msfn.org

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6291]
https://msfn.org/board/topic/175560-mozilla-thunderbird-450-ignores-glass8-any-ideas/

Ani-adblock notify:

![Screenshot_20190913-145301](https://user-images.githubusercontent.com/35370833/64863916-35c21280-d636-11e9-93e8-0699b3937d7a.png) |
--- |

**Comment by mapx-** [comment]
notification even disabling uBo
