### ISSUE TITLE
unbreak request: eksisozluk.com

### ISSUE THREAD

**Issue by ahmedtds** [uBlockOrigin/uAssets#6295]
### URL(s) where the issue occurs

`[https://eksisozluk.com]`

### Describe the issue

Site doesn't respond to first click if ad blocker is active. I mean open it and try to click a link on the page, it will only respond after second click.

### Versions

- Browser/version: Firefox 69
- uBlock Origin version: latest

### Settings

- all default

**Comment by mapx-** [comment]
test
```
@@||googletagservices.com/tag/js/gpt.js$script,domain=eksisozluk.com
@@||securepubads.g.doubleclick.net/gpt/pubads_impl_$script,domain=eksisozluk.com
```

@okiehsch if you find some other fix ..

**Comment by mapx-** [comment]
@ahmedtds 

test this filter and see if breaks something
`eksisozluk.com##+js(stif, !rejectWith)`

**Comment by ahmedtds** [comment]
> 
> 
> @ahmedtds
> 
> test this filter and see if breaks something (and disable the filters above)
> `eksisozluk.com##+js(stif, !rejectWith)`

yes, this breaks whole site, a lot of things, buttons, text boxes etc..

**Comment by ahmedtds** [comment]
> 
> 
> test
> 
> ```
> @@||googletagservices.com/tag/js/gpt.js$script,domain=eksisozluk.com
> @@||securepubads.g.doubleclick.net/gpt/pubads_impl_$script,domain=eksisozluk.com
> ```
> 
> @okiehsch if you find some other fix ..

tried these but it didn't fix the issue, still have to click twice

**Comment by mapx-** [comment]
> > test
> > ```
> > @@||googletagservices.com/tag/js/gpt.js$script,domain=eksisozluk.com
> > @@||securepubads.g.doubleclick.net/gpt/pubads_impl_$script,domain=eksisozluk.com
> > ```
> > 
> > 
> > @okiehsch if you find some other fix ..
> 
> tried these but it didn't fix the issue, still have to click twice

working for me, after a delay of 1-2 seconds

**Comment by mapx-** [comment]
what about
`eksisozluk.com##+js(stif, ,!100)`

**Comment by ahmedtds** [comment]
> 
> 
> > > test
> > > ```
> > > @@||googletagservices.com/tag/js/gpt.js$script,domain=eksisozluk.com
> > > @@||securepubads.g.doubleclick.net/gpt/pubads_impl_$script,domain=eksisozluk.com
> > > ```
> > > 
> > > 
> > > @okiehsch if you find some other fix ..
> > 
> > 
> > tried these but it didn't fix the issue, still have to click twice
> 
> working for me, after a delay of 1-2 seconds

oh right, noticed that now, it works after a few seconds but still annoying to have a delay



> 
> 
> what about
> `eksisozluk.com##+js(stif, ,!100)`

this seems to be working, what exactly that line does, just curious?

**Comment by mapx-** [comment]
defusing a function ri() executed by:

`setTimeout(function(){ri()},100)`

```
    function ri() {
        n("a").click(function(i) {
            var u, r, o, s, h;
            i.isDefaultPrevented() || (u = i.currentTarget, i.metaKey || i.ctrlKey || u.target !== "" || u.href === "") || (r = y === "true" ? n(".ad-mobilewebinterstitial") : n(".ad-doubleclickwebinterstital"), r.length !== 0) && (o = n("#overlay"), s = n("#interstitial-close-link-source"), s.length === 0 && (h = n("<div/>", {
                id: "interstitial-close-link-source",
                "data-link": i.currentTarget.href
            }), f = i.currentTarget.href, n(o).after(h), i.preventDefault(), r.length >= 1 && rt(r)), t.setTimeout(function() {
                typeof r[0].children[0].children[0].children[0] == "undefined" && typeof e == "undefined" && t.open(f, "_self")
            }, 2e3))
        })
```

**Comment by mapx-** [comment]
read about https://github.com/gorhill/uBlock/wiki/Resources-Library#settimeout-ifjs-

**Comment by 5l1v3r1** [comment]
eksisozluk logs ips locations and user info and shares them with the dictatorial regime of erdogan. better to block it all.
