### ISSUE TITLE
xda-developers.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#630]
### URL(s) where the issue occurs

`https://forum.xda-developers.com/apps/magisk/beta-magisk-v13-0-0980cb6-t3618589`

### Describe the issue

Unblocked ad below first post

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/29386947-e79775c6-82ab-11e7-87fe-f98870142df3.png)

### Settings

Default

### Notes

xda already had `script:inject(abort-on-property-write.js, adonisHash)` but seems like they bypassed it.

**Comment by gorhill** [comment]
How about:

    forum.xda-developers.com##.postbit-wrapper:if(.postbit-userinfo-cell:has-text(Sponsor Content))

**Comment by terrorist96** [comment]
Yes, that works. Thanks
