### ISSUE TITLE
YouTube TV?

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6303]
`https://www.youtube.com/`

on homepage self-promotion:

![obraz](https://user-images.githubusercontent.com/35370833/64911060-7d6f9980-d71d-11e9-99ed-567e31609ae6.png) |
--- |
![obraz](https://user-images.githubusercontent.com/35370833/64911076-a55efd00-d71d-11e9-9cf5-bed2a7dd1787.png) |

**Comment by mapx-** [comment]
> self-promotion

maybe only as annoyance, I cannot reproduce it

@ryanbr

**Comment by krystian3w** [comment]
Maybe needed is US proxy I am testing:


https://web.archive.org/web/*/https://private-network.firefox.com/dist/secure-proxy.xpi

**Comment by mapx-** [comment]
right,

`youtube.com###promo-info`

**Comment by krystian3w** [comment]
`###dismissable.ytd-primetime-promo-renderer:-abp-has(a[href^="https://tv.youtube.com/?pid="])`

All with procedural filtering to no cut too match elements.

**Comment by uBlock-user** [comment]
> Maybe needed is US proxy, I am testing:

https://web.archive.org/web/*/https://private-network.firefox.com/dist/secure-proxy.xpi

Does that work ? You need Firefox account

**Comment by krystian3w** [comment]
For my works (Also have account: https://addons.mozilla.org/pl/firefox/user/11058780/), few cookie notification gone (detect my as out of Europe), IP detectors show US Cloudflare, no tested sites locked for US only (no known any).

**Comment by mapx-** [comment]
@krystian3w  you could use a very useful app (I hope you are using windows - but I see some deepL for linux too ) to translate from polish to english

https://www.deepl.com/en/app/

(it's the best translator nowadays)

**Comment by krystian3w** [comment]
So why you wrote name language by small letters...

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/64912037-be6dab00-d729-11e9-8766-a34d5856a424.png)

**Comment by mapx-** [comment]
Well, pretty good level in English :-)

**Comment by ryanbr** [comment]
So youtube.com###promo-info doesn't cause any issues?

**Comment by krystian3w** [comment]
This is need two simple filters:

`###promo-info`
`###promo-list`

The graphics left behind without a description look strange.

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/64914738-7b2a3100-d757-11e9-9322-ad74e82855a7.png)
