### ISSUE TITLE
pornoxo.com [NSFW]

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#6306]
### Describe the issue

[Using the mobile version of the site clicking on a video redirects the first tab to another site while video opens in another tab.]

### Versions

- Browser/version: [Chrome v77]
- uBlock Origin version: [1.22.0]

### Settings

- [default]

**Comment by dumbusernameidk** [comment]
also should add `||pornoxo.com*/js/popundr/*$script,1p` script contains annoyance stuff like clearing console and mentions of popunders.

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by dumbusernameidk** [comment]
use an agent switcher so the site is on `m.pornoxo.com` then clear cookies and click a video. I can get it to trigger every time.

**Comment by okiehsch** [comment]
I am on `m.pornoxo.com` and I can trigger the popunder every time **if** I remove the filter **mapx-** added.

> also fix doesn't seem to work i still get the first tab redirecting to m.ashemaletube.com

I can't reproduce this, the fix works on my end.

**Comment by dumbusernameidk** [comment]
![image](https://user-images.githubusercontent.com/25139338/64915576-4d81bf80-d738-11e9-98fe-22415eaab1d4.png)

this is what happens when i go on mobile with an agent switcher and after clearing cookies.

**Comment by okiehsch** [comment]
To block the popunder on your end
`*$popunder,3p,domain=m.pornoxo.com`

**Comment by ghajini** [comment]
I can reproduce(firefox android ),

View page source

`https://pastebin.com/p5zmrzSY`

**Comment by mapx-** [comment]
@ryanbr added 
`/popundr/*` to easylist .. but very strange the list is stuck at 14 / 09 / 2019

**Comment by mapx-** [comment]
You should restart firefox - I noted strange issues with the lists not updated

**Comment by okiehsch** [comment]
My chromium `EasyList` version is also still from yesterday after updating.

**Comment by mapx-** [comment]
yeah, I reverted 2 commits for this reason

**Comment by gwarser** [comment]
EasyList travis-ci are failing for few hours https://travis-ci.org/easylist/easylist/builds

**Comment by mapx-** [comment]
same for easyprivacy

**Comment by ghajini** [comment]
`*$popunder,3p,domain=m.pornoxo.com`
can be added, fixes issue

**Comment by gwarser** [comment]
I'm pretty sure building fails because cloning whole EasyList repo takes more than 10 minutes, and not produces any output.

>[Build Timeouts #When a job produces no log output for 10 minutes.](https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts)

And last good build [took 597.78s](https://travis-ci.org/easylist/easylist/builds/584973913)

cc: @ryanbr
