### ISSUE TITLE
kinox.to 

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#6309]
### URL(s) where the issue occurs

`kinox.*`
`kinoz.to`

### Describe the issue

popups

### Versions

- Browser/version: Firefox 69.0
- uBlock Origin version:  v1.22.2

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3614050/Settings.txt)

**Comment by mapx-** [comment]
example for `kinox` ?

`https://kinox.lol/Stream/Yesterday-2.html` => seems ok, no popup

**Comment by JobcenterTycoon** [comment]
`kinox.to`

**Comment by mapx-** [comment]
no popup for `kinox.to`

**Comment by JobcenterTycoon** [comment]
sure?
<img width="863" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/64925746-a3686d00-d7f5-11e9-9461-d25aaf6c6233.PNG">

**Comment by mapx-** [comment]
does work for you
`kinox.*##+js(aopr, decodeURI)`

**Comment by mapx-** [comment]
@okiehsch 

I tested in FF 69. Sometimes in the source code I can see `iociley` domain (blocked in our list) => no external script in the logger.  Could you reproduce this weird issue ?

**Comment by JobcenterTycoon** [comment]
> does work for you ?
`kinox.*##+js(aopr, decodeURI)`

Yes it works
