### ISSUE TITLE
[Popup] translation.babylon-software.com

### ISSUE THREAD

**Issue by spirillen** [uBlockOrigin/uAssets#6311]
### URL(s) where the issue occurs

`https://translation.babylon-software.com/danish/to-english/`

### Describe the issue

Annoying popup

### Screenshot(s)

![translation babylon-software com](https://user-images.githubusercontent.com/44526987/64951816-0d792480-d87f-11e9-8903-72a0db37820e.png)

### Versions

- Browser/version: FF 69.0 (64-bit) and Tor Browser 8.5.4
- uBlock Origin version: uBlock Origin v1.22.2

### Settings

![Ublock-Settings](https://user-images.githubusercontent.com/44526987/64952057-9abc7900-d87f-11e9-8675-7758657e4262.png)

### Notes
These Rules seems to work for me at least

```
translation.babylon-software.com##.pc-popup-new
```

**Comment by mapx-** [comment]
```
translation.babylon-software.com##.pc-popup-new
translation.babylon-software.com###dimScreen
```

the filters should go to `fanboy's annoyance list`

@ryanbr
