### ISSUE TITLE
apnews.com

### ISSUE THREAD

**Issue by redx113** [uBlockOrigin/uAssets#6313]
### URL(s) where the issue occurs

`www.apnews.com`

### Describe the issue

They have added promoted content in between other articles that appear on a news story you have read, it is below them

### Screenshot(s)
https://i.imgur.com/q4SYFV2.jpg
![image](https://user-images.githubusercontent.com/55429291/65017752-7ac79c80-d8f5-11e9-8e7a-3be008cb3c9f.png)

### Versions

- Browser/version: Firefox Nightly 70.0b6 (64-bit)
- uBlock Origin version: 1.22.2

### Settings

Everything is on default

### Notes

I tried to remove with the element picker, but it only removed the one promoted ad.

**Comment by mapx-** [comment]
I see no ad, how to reproduce them ? steps ?

**Comment by redx113** [comment]
It appeared on this url https://apnews.com/04ac3771d88a47a1b10e4081646e871c

When I scrolled down prevoous it had ad content. It seems to sometimes be blocked on some articles and on another it will get through. Its interesting and odd

**Comment by mapx-** [comment]
Did you whitelist taboola ?

**Comment by redx113** [comment]
No

no-large-media: behind-the-scene false
behind-the-scene * * noop
behind-the-scene * 1p-script noop
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
behind-the-scene * 3p-script noop
behind-the-scene * image noop
behind-the-scene * inline-script noop

about-scheme
chrome-extension-scheme
chrome-scheme
moz-extension-scheme
opera-scheme
vivaldi-scheme
wyciwyg-scheme

**Comment by mapx-** [comment]
I can reproduce `ad content` only whitelisting `taboola` and disabling cosmetic filtering

**Comment by mapx-** [comment]
try resetting your uBo to default settings and test again (backup your current installation)
