### ISSUE TITLE
DailyMail - MailOnline

### ISSUE THREAD

**Issue by ZombieMachinery** [uBlockOrigin/uAssets#6314]
### URL(s) where the issue occurs

`dailymail.co.uk`

### Describe the issue

I'm getting a "We see that you're using an add blocker" message and the website freezes every single time I enter.

### Screenshot(s)

https://imgur.com/mhPl7pP

### Versions

- Browser/version: 76.0.3809.132
- uBlock Origin version: 1.22.2

### Settings

- None

### Notes

I blocked the message and the blur screen effect but the website still freezes so I deleted the changes to get it back to normal

**Comment by mapx-** [comment]
Why are you using 2 adblockers ? remove ABP completely and test again using uBo default settings ?

**Comment by ZombieMachinery** [comment]
Why? Because is better LOL! But you were right, it wasn't on your side, I deactivated Adblock Plus and the website is back to normal. Thank you so much.

**Comment by mapx-** [comment]
No. It's wrong (not LOL) keeping 2 adblockers (conflicts as this one, memory hog, redundant filters, slowing down navigation), use only uBo.
