### ISSUE TITLE
unbreak request: porn.com [NSFW]

### ISSUE THREAD

**Issue by whataprude** [uBlockOrigin/uAssets#6317]
### URL(s) where the issue occurs

https://www.porn.com "NSFW"

### Describe the issue

Rules disable ajax on the site, breaking the video player and menus.

### Versions

- Browser/version: Google Chrome: iOS Version 77.0.3865.69
- uBlock Origin version: latest

### Settings

- all default

### Notes

this addition to the filters list appears to be causing the problem
||porn.com^$xhr,1p

**Comment by mapx-** [comment]
I get no issue with the player (still running) and menus
What exactly is broken ?

Does this help ?
`@@||porn.com/ajax/$xhr,1p`

**Comment by whataprude** [comment]
apologies, I mean the video menu so when I try to add to playlist or like a video it's being blocked. It looks like search recommendations as well while typing
![under_player](https://user-images.githubusercontent.com/55460840/65076086-388a7380-d966-11e9-996e-012852ee9786.JPG)
![search](https://user-images.githubusercontent.com/55460840/65076088-3b856400-d966-11e9-88ff-9bb354713a0b.JPG)

**Comment by mapx-** [comment]
Did you test the filter ?

Then delete it and test these other filters
```
||porn.com^$xhr,1p,badfilter
porn.com##+js(set, $sppc.detectAB, trueFunc)
```

**Comment by bug-rules** [comment]
`@@||porn.com/ajax/$xhr,1p` fixes broken vote up/down and add to `my favorite` / `watch latter`.

**Comment by mapx-** [comment]
Test the other 2 filters (disabling the above 1)

**Comment by bug-rules** [comment]
`||porn.com^$xhr,1p,badfilter` does not work, maybe other filter also block xhr.

`porn.com##+js(set, $sppc.detectAB, trueFunc)` this remove empty box in right column only?

**Comment by mapx-** [comment]
again .. 

delete `@@||porn.com/ajax/$xhr,1p`

and **test together** these 2 filters:
```
||porn.com^$xhr,1p,badfilter
porn.com##+js(set, $sppc.detectAB, trueFunc)
```

**Comment by bug-rules** [comment]
@gorhill  see this:

```js
! FRA EasyList
||porn.com^*?$xhr,badfilter

! EasyList (EN / International)
||porn.com^$xhr,badfilter

! uBO filters
||porn.com^$1p,xhr,badfilter
```

uBO logger no see all combinations.

---

https://github.com/uBlockOrigin/uAssets/issues/6317#issuecomment-532779936 No help because EasyList EN / FRA uses other filters.
