### ISSUE TITLE
xe.gr >>> anti adb 

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#6318]
"it looks like you are using an ad blocker" message on
site: `https://www.xe.gr`

example link:
`https://www.xe.gr/jobs/search?Item.category__hierarchy=117113&Item.master_type=114485&System.item_type=xe_stelexos&Transaction.type_channel=117518&sort_by=System.creation_date&Geo.area_id_new__hierarchy=82490`

https://user-images.githubusercontent.com/24896778/65148992-f591d400-da29-11e9-963c-20be0d849b33.jpg

**Comment by mapx-** [comment]
test
`xe.gr##+js(std, modal)`

However, it's an annoyance, you can click on page and continue to navigate

(you will need uBo annoyances list to be enabled when I'll add the filter)

**Comment by patrickdrd** [comment]
yes, I've got annoyances enabled, thanks
