### ISSUE TITLE
Newslaundry shows a blank page

### ISSUE THREAD

**Issue by thy6** [uBlockOrigin/uAssets#632]
### URL(s) where the issue occurs

`https://www.newslaundry.com/`

### Describe the issue

None of the pages on the Newslaundry website are displayed when uBlock is on. I have tried disabling all the 1st party, Inline, 3rd Party scripts and frames.

However, it works fine if I noop 3rd Party scripts in the dynamic filters.

### Versions

- Browser/version: Firefox Nightly 57.0a1 (2017-08-17) (64-bit)
- uBlock Origin version: uBlock Origin v1.13.9rc4

### Settings

- Blocked all 3rd Party, 3rd Party scripts and 3rd Part frames in the dynamic filters.

### Notes

I tried injecting some scripts from resources.txt but I wasn't able to fix this issue with them.

**Comment by okiehsch** [comment]
So how do you conclude that this is a filter issue?
If you are blocking all 3rd party requests via dynamic filtering, you will have site breakage.
No filter can fix that.
To fix your "`newslaundry.com` shows a blanke page issue", you have to atleast noop `rawgit.com`.
