### ISSUE TITLE
dvdwap.best/dvdwap.us

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6321]
### URL(s) where the issue occurs

`dvdwap.best`
`dvdwap.us`

### Describe the issue

Popup ads

### Versions

- Browser/version: opera browser
- uBlock Origin version: 1.22.2

### Settings

- uBO's default settings

**Comment by ghajini** [comment]
`undefined` crap (page loads forever) like ubo shows >3k entries blocked, any general blocking on extension level for all unknown sites....

**Comment by okiehsch** [comment]
I can't test with Opera, does the redirection not work?
I fixed it for Firefox. There is a race condition, so I can't abort the script consistently using Chromium based browsers .

**Comment by ghajini** [comment]
I see 1 request of `undefined` script in logger for chromium based browsers

Anyone ,firefox just not working, I don't see html filter in logger and undefined persists

**Comment by okiehsch** [comment]
> I see 1 request of undefined script in logger for chromium based browsers

That's the best we can do for chromium browsers.
mapx- commit should fix the Firefox issue for good.

**Comment by ghajini** [comment]
Yes mapx- commit fixed for firefox

By the way acis not work on chrome/firefox due to race condition...can we just harden abort current inline script scriptlet?
@gorhill

**Comment by ghajini** [comment]
@llacb47, why so laugh, downthumb emoji for comment?

**Comment by gorhill** [comment]
The no-popups switch does not work on that site in Chromium 81? Is it just me?

I thought something was wrong in uBO but it turns out the browser does not fire the [webNavigation.onCreatedNavigationTarget()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/onCreatedNavigationTarget) event.

**Comment by ghajini** [comment]
acis not work that's the issue here for chrome/firefox...
classical filter nowadays in ublock filters not work here
`dvdwap.*##+js(acis, String.fromCharCode, "shift")`

**Comment by llacb47** [comment]
How is uBo going to fix a race condition? That is a browser issue.

**Comment by gorhill** [comment]
> acis not work that's the issue here

I know what is the issue, Chromium's extension API is lacking compared to Firefox. For now I just want to understand how the page is able to open popup tabs/windows despite the no-popups switch. I want to confirm this is a browser issue.

**Comment by llacb47** [comment]
I can confirm that popads is able to open popups despite the `no-popups` switch being active.

**Comment by gorhill** [comment]
I suppose rules such as:

    *$script,domain=dvdwap.store,denyallow=facebook.net|googleapis.com|sharethis.com

will be handy since they keep generating randomly named servers to host popads scripts?

**Comment by okiehsch** [comment]
> The no-popups switch does not work on that site in Chromium 81. Is it just me?

I noticed something similar a few days ago. The logger also does not indicate any popup ever took place. The new window closes automatically on my end however.
https://github.com/NanoMeow/QuickReports/issues/3746#issuecomment-623242899

They have since updated the script and I can reproduce again.
Example link:
````
https://animepahe.com/play/82c447c5-e4f2-d791-8b4e-c8aa3c3f8be8/bb114233c0343c21f53265d90be7f460d12f9f592dcb37ad19102b5772c20c59
````

**Comment by gorhill** [comment]
I can't reproduce a popup at `animepahe.com`, including after disabling "uBlock filters". If you find other cases, let's share these in uBO Team section.

**Comment by ghajini** [comment]
Both pages not exist now
