### ISSUE TITLE
uBlockOrigin blocks legitimate content

### ISSUE THREAD

**Issue by Black69Silver** [uBlockOrigin/uAssets#6326]
### URL(s) where the issue occurs

`https://www.youtube.com/upload`
`https://www.namecheap.com/`
`https://transferwise.com/invite`

### Describe the issue

When uBlock Origin is on: 
- on youtube: clicking on Upload doesn't open the Upload video / Go live menu at all. On the screenshot uBlock Origin is disabled and the menu is visible at the right end. 
- on namecheap: Search, both regular and beast mode, does not work - search does not produce any results. On third namecheap screenshot uBlock Origin is disabled and search results are visible. 
- on transferwise: Invite page is blank. Screenshots show the same page with uBlock Origin enabled and disabled. Login might be required to reach this page, but it is free. 

### Screenshot(s)

![youtube ](https://user-images.githubusercontent.com/55551355/65291788-8ae1b500-db5d-11e9-9a53-6948b7debe89.png)

![namecheap 1 ](https://user-images.githubusercontent.com/55551355/65291931-0ba0b100-db5e-11e9-915f-fad457f4879e.png)
![namecheap 2 ](https://user-images.githubusercontent.com/55551355/65291938-10fdfb80-db5e-11e9-953c-e46dd6be75c6.png)
![namecheap 3 ](https://user-images.githubusercontent.com/55551355/65291945-13f8ec00-db5e-11e9-9002-7034f6d897ed.png)

![transferwise on ](https://user-images.githubusercontent.com/55551355/65292186-1b6cc500-db5f-11e9-9b4f-7c97591cd24f.png)
![transferwise off ](https://user-images.githubusercontent.com/55551355/65292199-2293d300-db5f-11e9-98e1-1890f125265b.png)

![uBlock Origin settings 1](https://user-images.githubusercontent.com/55551355/65292761-45bf8200-db61-11e9-9fca-26d6e4d181b1.png)
![uBlock Origin settings 2](https://user-images.githubusercontent.com/55551355/65292765-4bb56300-db61-11e9-95d6-6b85e96cc483.png)

### Versions

- Browser/version: 66.0.3 (64-bit)
- uBlock Origin version: 1.22.2

### Settings

- I've attached screenshots of the settings.
- My filters are mostly related to cookie banners

**Comment by mapx-** [comment]
- disable all other extensions, keep only uBo enabled, test again
- backup your uBo settings (to file), reset uBo to default, keep other extensions disabled, test again
- update FF to the last version

**Comment by uBlock-user** [comment]
In all the three cases you have NoScript, no doubt that's the cause of this breakage.

**Comment by krystian3w** [comment]
What broken uBo on youtube when you disable filtering on this site?

**Comment by krystian3w** [comment]
Try update Firefox to 69 release?

**Comment by dumbusernameidk** [comment]
everything works on my end.

**Comment by Black69Silver** [comment]
mapx, thank you for the suggestions. It turned out that some of my filters were causing the troubles. With them removed and Firefox updated, all is smooth now. Thanks!
