### ISSUE TITLE
imgur.com front page 'promoted' posts

### ISSUE THREAD

**Issue by tofof** [uBlockOrigin/uAssets#6328]
### URL(s) where the issue occurs

`https://imgur.com/`

### Describe the issue

'Promoted' posts now appear on the front page, repeatedly.

### Screenshot(s)

![MXEDYiv](https://user-images.githubusercontent.com/3980843/65348172-2e56b800-dba6-11e9-8c66-ff296fe3ccef.png)

### Versions

- Browser/version: Chrome Version 76.0.3809.132 (Official Build) (64-bit)
- uBlock Origin version: 1.22.2

### Settings

- none

### Notes

I don't think there's a way to get them without using the 'has' functionality...

`imgur.com##div:has(> a > div > div.Post-item-external-ad)`

### EDIT

Mystified by the response below, I tried a clean minimal install and discovered imgur only serves these advertised posts to users who are **logged in**! Unexpected, certainly, but doesn't solve the problem.

**Comment by yourduskquibbles** [comment]
I can not reproduce what OP sees in firefox or chrome

**Comment by krystian3w** [comment]
Logon required?

**Comment by mapx-** [comment]
I have an account but I get no such promoted stuff

**Comment by tofof** [comment]
https://blog.imgur.com/2015/05/31/about-promoted-posts/

I'm not making it up.

**Comment by llacb47** [comment]
Update your filter lists and see if they are still shown

**Comment by krystian3w** [comment]
Or use this: https://cable.ayra.ch/tampermonkey/view.php?script=imgur_old_design.user.js

**Comment by okiehsch** [comment]
> I'm not making it up.

Nobody accuses you of "making it up". 

https://github.com/easylist/easylist/pull/4052
If/when this pull request is merged your reported issue should be fixed.
