### ISSUE TITLE
Ads not blocked at Tampermonkey.net

### ISSUE THREAD

**Issue by graciecat** [uBlockOrigin/uAssets#633]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://tampermonkey.net/`

### Describe the issue
Advertisement not blocked. Can clearly see box with word "Advertisement" and the ad itself.

### Screenshots
https://s6.postimg.org/ywxsq9z5d/Tampermonkey_ad.png
https://s6.postimg.org/kt1xhvrxt/Ad_on_Tampermonkey_2.png
https://s6.postimg.org/pszdptxkh/Ad_on_Tampermonkey_3.png

### Versions

- Pale Moon 27.4.1 (64-bit) on Ubuntu 14.04.5
- uBlock Origin 1.13.8

### Settings
Filters enabled:

- uBlock filters‎
- uBlock filters – Badware risks‎ (github.com)
- uBlock filters – Privacy
- uBlock filters – Unbreak‎
- Adblock Protector List
- Adblock Warning Removal List‎ (forums.lanik.us)
- Anti-Adblock Killer | Reek‎ (github.com)
- EasyList‎
- uBlock Protector List
- Basic tracking list by Disconnect
- EasyPrivacy
- Fanboy's Enhanced Tracking List
- Malware Domain List‎ (malwaredomainlist.com)
- Malware domains‎ (www.malwaredomains.com)
- Fanboy's Annoyance List
- Peter Lowe’s Ad and tracking server list

Dynamic filtering NOT enabled

Other settings enabled:

- Hide placeholders of blocked elements
- Show the number of blocked requests on the icon
- Make use of context menu where appropriate 
- Disable pre-fetching (to prevent any connection for blocked network requests)
- Disable hyperlink auditing
- Prevent WebRTC from leaking local IP addresses

### Notes
Used element picker to create these filters to block first ad:

```
||tampermonkey.net/wikibuy/2/003.jpg$image
tampermonkey.net##tr:nth-of-type(2) > td > .noborder > tbody > tr > td > .adventing > .advent_head

```
But when page reloaded with Ctrl-R or F5, a new ad came in its place

**Comment by SMed79** [comment]
Try these filters https://forums.lanik.us/viewtopic.php?p=122147#p122147

**Comment by graciecat** [comment]
This custom filter seemed to work:
`||tampermonkey.net/*/*.*$image`

I don't know whether `tampermonkey.net##.adventing` would work better.

**Comment by okiehsch** [comment]
Fixed in [Easylist](https://github.com/easylist/easylist/commit/0f2341396e5acfe6051782dbd5fe05880f4bac5f).
