### ISSUE TITLE
another unbreak request for eksisozluk.com

### ISSUE THREAD

**Issue by ahmedtds** [uBlockOrigin/uAssets#6331]
this issue was resolved: https://github.com/uBlockOrigin/uAssets/issues/6295

and it was all fine but it looks like today they made another change in site and site is broken again. a lot of functionality is broken when adblocker is active. can you fix it again please?

thanks.

**Comment by okiehsch** [comment]
Does 
`@@||ekstat.com/js/ek$i-combo.js$script,domain=eksisozluk.com`
fix all issues?

**Comment by ahmedtds** [comment]
>  `@@||ekstat.com/js/ek$i-combo.js$script,domain=eksisozluk.com`

no, it fixes some but still some functions are broken

**Comment by okiehsch** [comment]
Well, can you give an example of a broken function?

**Comment by ahmedtds** [comment]
> 
> 
> Well, can you give an example of a broken function?
> My turkish is rather bad.

auto-complete in search box at top
some links in user profiles, example profile: https://eksisozluk.com/biri/ssg
try to click "istatistikler" button, you can't

probably there's more, just noticed these for now

**Comment by okiehsch** [comment]
Thanks, `@@||ekstat.com/js/ek$script,domain=eksisozluk.com` works on my end.

**Comment by ahmedtds** [comment]
> 
> 
> Thanks, `@@||ekstat.com/js/ek$script,domain=eksisozluk.com` works on my end.

should I delete the previous one before trying this?

**Comment by okiehsch** [comment]
No, should work either way.

**Comment by ahmedtds** [comment]
thanks, seems working
