### ISSUE TITLE
ryuukoi.web.id

### ISSUE THREAD

**Issue by Arsindy** [uBlockOrigin/uAssets#6332]
URL(s) where the issue occurs
`https://ryuukoi.web.id/boruto-naruto-next-generations-125-subtitle-indonesia/`

Describe the issue
Anti adblock

Screenshot(s)
![Annotation 2019-09-22 212409](https://user-images.githubusercontent.com/55402429/65389363-9ad8df00-dd7f-11e9-809e-f1989f58d4d2.png)

Versions
Browser/version: Google Chrome v 77.0.3865.90 (Official Build) (64-bit)
uBlock Origin version: 1.22.2

Settings
uBO's default settings

**Comment by krystian3w** [comment]
Should enough:

`@@||ryuukoi.web.id^$generichide`

I no see leftovers after blocked ads.

**Comment by krystian3w** [comment]
Maybe possible cut as annoyance:

```
##.top div.top-content.widget_text:nth-of-type(-n+2)
```

**Comment by Arsindy** [comment]
@krystian3w thanks
