### ISSUE TITLE
t-online.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#6337]
### URL(s) where the issue occurs

`https://www.t-online.de/nachrichten/panorama/id_86495628/klimakrise-wie-new-york-gegen-den-steigenden-meeresspiegel-kaempft.html`

### Describe the issue

Video Ads

### Versions

- Browser/version: Firefox 69.0.1
- uBlock Origin version:  v1.22.2

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3640312/Settings.txt)

**Comment by okiehsch** [comment]
Same issue as `giga.de` I can fix the video ads but it will only work in the dev version, if you don't want to use it you will have to wait until the next stable release.

**Comment by JobcenterTycoon** [comment]
ok but can you add this to the filterlist please?

**Comment by okiehsch** [comment]
I am in the process of doing just that. 😉

**Comment by JobcenterTycoon** [comment]
Thanks

**Comment by mapx-** [comment]
@JobcenterTycoon maybe we should adjust the filter for this site too, could you test it - if getting video ads ?

**Comment by JobcenterTycoon** [comment]
It works for this site too

**Comment by JobcenterTycoon** [comment]
Video ads are back again

`https://www.t-online.de/nachrichten/ausland/usa/id_86850330/impeachment-anhoerung-sondland-belastet-trump-pompeo-und-pence.html`
