### ISSUE TITLE
Google.*

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6338]
EasyList breakage by generic network filter.

---

`https://www.google.com/partners/agency?id=9241133033`

Website is empty without:

```
@@||gstatic.com/*/adwords/partnerspublic/partners_public_*/partners/main.dart.js
 ```

Use path form URL, can exclude write ~193 domains (I assume that every country has a company with a Google partner award.).

---

Optionally, use a badfilter modifier:

`/adwords/*$badfilter`

**Comment by mapx-** [comment]
@ryanbr

**Comment by krystian3w** [comment]
P.S. In ABP is needed disable "acceptable ads" to reproduce.
