### ISSUE TITLE
Washington post anti-adblock. 

### ISSUE THREAD

**Issue by Marsfan** [uBlockOrigin/uAssets#6339]
### URL(s) where the issue occurs

`https://www.washingtonpost.com/nation/2019/03/29/decades-garfield-telephones-kept-washing-ashore-france-now-mystery-has-been-solved/`

### Describe the issue

Anti-Adblock popup is still appearing on Washington Post

### Screenshot(s)

![image](https://user-images.githubusercontent.com/9311953/65471593-8e5a9200-de24-11e9-885e-4f9d21d39df7.png)

### Versions

- Browser/version: Firefox 70 Beta
- uBlock Origin version: 1.22.2

### Settings

- All Filters Enabled. Advanced User Enabled. 

### Notes

The adblock popup is identical to #6280. I am still seeing it despite updating all filters.

**Comment by okiehsch** [comment]
I can't reproduce with a deault setup using Chromium or Firefox.

**Comment by krystian3w** [comment]
@seba2282 this is your report with fake account?

**Comment by seba2282** [comment]
@krystian3w, mam jedno konto. - > I have one account.

**Comment by uBlock-user** [comment]
@Marsfan 
```
washingtonpost.com##[class] > div:has-text(blocking ads)
washingtonpost.com##html:style(overflow: auto !important)

```
You can try those.

**Comment by krystian3w** [comment]
No recover right column:

![Screenshot_2019-09-24 For decades, Garfield telephones kept washing ashore in France Now the mystery has been solved ](https://user-images.githubusercontent.com/35370833/65542261-23d25080-df0f-11e9-95bb-326f902826d8.png) |
--- |

**Comment by VernonStow** [comment]
I've been having the same issue over the past 4 or 5 days. It occurs randomly and I can mitigate it by refreshing the page 2 or 3 times.

I created a filter `@@||washingtonpost.com^$generichide` which did not make any difference. I also tried disabling cosmetic filtering on the site, which also made no difference.

I use default uBO filters with the addition of Fanboy's Enhanced Tracking List and the anti-blocker list from [https://github.com/bogachenko/fuckfuckadblock](url). I use Firefox 69.0.1 portable on Windows 10 Home 64, build 1809.

**Comment by uBlock-user** [comment]
> I've been having the same issue over the past 4 or 5 days. It occurs randomly and I can mitigate it by refreshing the page 2 or 3 times.

Race condition is affecting you then.

**Comment by okiehsch** [comment]
There should not be any race condition problem using Firefox because we are using 
`washingtonpost.com##^script:has-text(("0x)`

@VernonStow can you see that filter in the logger?
![image](https://user-images.githubusercontent.com/16838044/65573986-7d1c9d00-df6c-11e9-8162-b30324562a45.png)

**Comment by VernonStow** [comment]
> 
> 
> There should not be any race condition problem using Firefox because we are using
> `washingtonpost.com##^script:has-text(("0x)`
> 
> @VernonStow can you see that filter in the logger?
> ![image](https://user-images.githubusercontent.com/16838044/65573986-7d1c9d00-df6c-11e9-8162-b30324562a45.png)
> 
> If you can see it and still get the anti-adblock message do you have the Firefox tracking protection enabled and what other extensions do you use?

I do see the filter. I left "tracking protection" on for WaPo (although I find I have to disable it at most websites that display charts and graphs). I also use the paywall add-on at [https://github.com/iamadamdev/bypass-paywalls-firefox](url), although when I toggled it on and off yesterday and refreshed the page several times, I couldn't get WaPo to display the adblock warning.

**Comment by mapx-** [comment]
if you still see the anti adb stuff, try:
`washingtonpost.com##+js(raf-if, !jQuery.fx.tick)`

**Comment by VernonStow** [comment]
I just got a screen grab from it with the new filter added and "tracking protection" turned off. `https://www.washingtonpost.com/opinions/impeachment-will-define-the-2020-election/2019/09/25/7b931390-df82-11e9-be96-6adb81821e90_story.html`

![WAPO 1](https://user-images.githubusercontent.com/15573459/65664470-3d969500-dfee-11e9-8847-f7f0b5e8432e.jpg)
![WAPO 2](https://user-images.githubusercontent.com/15573459/65664481-45eed000-dfee-11e9-95f4-234ecc312686.jpg)

**Comment by okiehsch** [comment]
I don't see 
`washingtonpost.com##^script:has-text(("0x)`

**Comment by VernonStow** [comment]
I didn't see it listed under Blocked or Allowed, although I had added it to my filters.

**Comment by mapx-** [comment]
You should disable bypass-paywalls, keep tracking protection OFF, reopen FF and test again.

or
as above but reset uBo to default settings, update the lists and test again

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/65664783-617fc800-e03a-11e9-94b6-34ee450afe18.png)
Your link on my end using Firefox. There is no need to add it to my filters it is already part of `uBO-filters`.

**Comment by VernonStow** [comment]
Sorry, I had confused that with the `washingtonpost.com##+js(raf-if, !jQuery.fx.tick)` filter.

**Comment by okiehsch** [comment]
No problem, `washingtonpost.com##^script:has-text(("0x)` should work if you use Firefox unless some external extension or Firefox itself get's in the way.
Can you reproduce the anti adblock message if you disable the tracking protection and disable all extensions except `uBO`?

**Comment by VernonStow** [comment]
I have cleared cookies and disabled tracking protection and the paywall add-on, and cannot get the anti-adblock page to reappear after opening and refreshing 12 article links. I can see the `washingtonpost.com##^script:has-text(("0x)` filter as the first item blocked on each page. It would appear that the paywall add-on is interfering with uBO.

**Comment by okiehsch** [comment]
Thanks for testing.

**Comment by VernonStow** [comment]
Glad to be of help.

**Comment by yourduskquibbles** [comment]
I can reproduce anti-adb *sometimes* [with this article](https://www.washingtonpost.com/local/virginia-news/millions-of-dollars-are-missing-the-sheriff-is-dead-a-small-virginia-town-wants-answers/2019/09/24/1a0be2fe-c061-11e9-b873-63ace636af08_story.html) in Chrome with only uBO installed with default filters.

![wapo](https://user-images.githubusercontent.com/22258847/65697564-2769f280-e049-11e9-96c2-33135a1e8620.png)

![wapo2](https://user-images.githubusercontent.com/22258847/65697920-becf4580-e049-11e9-81a3-c037d80076a0.png)



Cosmetic filters with extended syntax appear to work on my end to solve this, can someone else who is seeing the notice test the following filters work to remove the overlay notice and add the page scrollbar back?

```
washingtonpost.com##div:has-text(We noticed you’re blocking ads.)
washingtonpost.com##html[style="overflow: hidden;"]:style(overflow: auto !important;)
```

**Comment by uBlock-user** [comment]
They will because the ones I posted are similar to yours, https://github.com/uBlockOrigin/uAssets/issues/6339#issuecomment-534698785

**Comment by yourduskquibbles** [comment]
> 
> 
> They will because the ones I posted are similar to yours, [#6339 (comment)](https://github.com/uBlockOrigin/uAssets/issues/6339#issuecomment-534698785)

Missed that somehow - thanks

**Comment by yourduskquibbles** [comment]
> 
> 
> No recover right column:

`washingtonpost.com##.db-ns[style="height: 1250px;"]` work?

**Comment by okiehsch** [comment]
> I can reproduce anti-adb sometimes with this article in Chrome

A race condition is possible using Chromium/Chrome.
