### ISSUE TITLE
Ad showing on aniwatcher.com

### ISSUE THREAD

**Issue by mrehanabbasi** [uBlockOrigin/uAssets#6340]
### URL(s) where the issue occurs

```
https://aniwatcher.com/kono-yo-no-hate-de-koi-wo-utau-shoujo-yu-no-episode-25
https://aniwatcher.com/black-clover-tv-episode-102
...
```

### Describe the issue

A banner ad is showing on any anime episode page of https://aniwatcher.com.

### Screenshot(s)

![Screenshot (2)](https://user-images.githubusercontent.com/19202888/65530417-5e3ced00-df11-11e9-93cf-0912ed4b7308.png)

### Versions

- Browser/version: Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)
- uBlock Origin version: 1.22.2

### Settings

- Using default settings.

### Notes

1. Opening multiple pages of the same website.
2. Restarted and browser as well as the system.
3. Tried multiple browsers i.e. Firefox and Edge.

**Comment by mapx-** [comment]
@ryanbr
