### ISSUE TITLE
chowhound.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6341]
```
https://www.chowhound.com/food-news/138950/marmite-and-vegemite-what-s-the-difference/
```

Newsletter with locked scrolling (fake scroll on screenshot):

![obraz](https://user-images.githubusercontent.com/35370833/65537516-a5bd7c00-df05-11e9-9259-1973f74e5490.png) |
--- |

**Comment by krystian3w** [comment]
I can not recover scrolling with CSS, rly crap!

**Comment by krystian3w** [comment]
```
chowhound.com##.fb_lightbox-margin.preloaded_lightbox, .fb_lightbox-overlay-fixed.fb_lightbox-overlay
chowhound.com##html.fb_lightbox-lock:style(overflow: auto !important;)
```

OMG...

**Comment by yourduskquibbles** [comment]
Does the following work for you? Works ok for me.

```
chowhound.com##.fb_lightbox-overlay
chowhound.com##.preloaded_lightbox
chowhound.com##.fb_lightbox-lock:style(overflow-x: hidden !important; overflow-y: scroll !important;)
```

**Comment by krystian3w** [comment]
No compatible with Nano Adblocker + Chromium.

**Comment by yourduskquibbles** [comment]
> 
> 
> No compatible with Nano Adblocker + Chromium.

Those 3 filters work for me on uBO stock latest dev build on test profile on chromium, why would it not be compatible with Nano Adblocker?

**Comment by yourduskquibbles** [comment]
I just tested with Nano and you're right it doesn't work. @jspenguin2017 any ideas why `chowhound.com##.fb_lightbox-lock:style(overflow-x: hidden !important; overflow-y: scroll !important;)` doesn't work to keep the vertical scroll bar visible with Nano Adblocker but work fine with uBO dev build?

**Comment by krystian3w** [comment]
Copy to NanoDefender or use path from website CSS file?

**Comment by jspenguin2017** [comment]
If you need UserCSS, you should use uBlock Origin. This is an annoyance, so I won't enforce the CSS in ND.

**Comment by yourduskquibbles** [comment]
Thanks, I wasn't aware that was a difference between ND and uBO.
