### ISSUE TITLE
Ads in Zooqle.com

### ISSUE THREAD

**Issue by unknowboy1991** [uBlockOrigin/uAssets#6342]
### URL(s) where the issue occurs

Any page on `zooqle.com`, here's one for example:

`https://zooqle.com/aladdin-2019-uhd-bluray-2160p-hdr-truehd-atmos-7-1-hevc-ddr-e-xgxe8.html#files`

This page is for the Aladdin (2019) movie, which I picked as sample.

### Describe the issue

This is a legitimate torrent indexing / search website; however, it also has a link button **Direct download** that serves (potentially) malware.

At the moment, the button links to these url(s) in order:
- `https://redsittalvetoft.pro/simani?q=Aladdin%202019%20UHD%20BluRay%202160p%20HDR%20TrueHD%20Atmos%207%201%20HEVC-DDR%5BE`
- `http://tray.recessmask.pw/Aladdin%202019%20UHD%20BluRay%202160p%20HDR%20TrueHD%20Atmos%207%201%20HEVC-DDR%5BE/bin/744/NJ6s7bq9FMYpECjp5rng67VoHDJlzcUEUlonAad47SVm_EuJqtvQGoAg9WTTyDX6g333Upgpq_DXKt5kphSekmR2okeJ6T9cDjSXpBd5brfooCT-/`
- `http://dinner.circlerabbits.info/b16b63d4c894b83329672ef49d45f5ef41215d60b5833ddec881a9e2/`

Which serves to something called [**Utilitool**](https://www.google.com/search?q=Utilitool) which I believe to be a malware / hijacker.

I would like to ask you block all of the domains that are used to redirect to the malware, so the downstream projects (such as Pi-hole and/or EnergizedProtection) that use uAssets filters, will also benefit from the whole domain blocks.

### Screenshot(s)

**The fake "Direct Download" link button:**
![dl_zooq](https://user-images.githubusercontent.com/30636501/65562302-bd6f2180-df52-11e9-89e4-450f32436828.png)

**The malware that it leads too after may redirects:**
![utilitool1](https://user-images.githubusercontent.com/30636501/65562345-ebecfc80-df52-11e9-8961-6f1d2bcbf25b.png)

### Versions

- Browser/version: Chrome 77.0
- uBlock Origin version: 1.22.2

### Settings

Left as default

### Notes

The focus of my comment is mainly on the malware/redirect domains, but I'd appreciate if you could also remove that useless button from the webpage.

As I said above, whole-domain blocks will be useful for any downstream projects that parses your lists, and it will improve the security of users by blocking these malware serving domains.

**Comment by okiehsch** [comment]
> I'd appreciate if you could also remove that useless button from the webpage.

Done.
