### ISSUE TITLE
Ads in Torrentz2 website

### ISSUE THREAD

**Issue by unknowboy1991** [uBlockOrigin/uAssets#6343]
### URL(s) where the issue occurs

- `https://torrentz2.eu/e1af5f59f021775254627ec1d9a861695dc20b0e`
- `https://torrentz2.is/e1af5f59f021775254627ec1d9a861695dc20b0e`

### Describe the issue

The following ads (banner) are shown:

### Screenshot(s)

![img](https://web.archive.org/save/https://torrentz2.eu/img/xpressvpn_4.png)

### Versions

- Browser/version: Chrome 77
- uBlock Origin version: 1.22.2

### Settings

Left as default

### Notes

This filter blocks the banners for me:
```
torrentz2.eu##.xpressa
torrentz2.is##.xpressa
```

Also, thank you for all the work you do :)

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/dfc2c2264297d5298fce6c3be1a55b79a3055323

Just fyi there is no need to open a new issue you can just comment in the closed issue https://github.com/uBlockOrigin/uAssets/issues/4272.

**Comment by unknowboy1991** [comment]
@okiehsch Oh, sorry, I wasn't aware of that.

Thanks!
