### ISSUE TITLE
`bluehouse.is` spam blocker popup

### ISSUE THREAD

**Issue by spirillen** [uBlockOrigin/uAssets#6344]
### URL(s) where the issue occurs

`https://www.bluehouse.is/`

### Describe the issue

POPup blocker that requires to `book now`

### Screenshot(s)

![Screenshot_2019-09-25 Blue House B B](https://user-images.githubusercontent.com/44526987/65593494-df879480-df90-11e9-8887-1dd44f2ada44.jpg)

### Versions

- Browser/version: FF 69.0.1
- uBlock Origin version: 1.22.2

### Settings
- Full House
  - Except:
    - Ignore generic cosmetic filters
    - Regions, languages (0/36)
  - Custom (2/2) lists
    - AnonymousPoster – Andblock Rules
    - Schacks Adblock Plus liste

### Notes

Scroll down a bit on screenshot to see the popup banner

**Comment by krystian3w** [comment]
In no Block scrolling report this to Fanboy / Adguard.

**Comment by krystian3w** [comment]
Also before report in uAssets reset uBO to stock lists - nobody activate ~40 lists.

**Comment by mapx-** [comment]
add
```
bluehouse.is###customForm
bluehouse.is###PopupOverLay_WA_0
```

@ryanbr

**Comment by spirillen** [comment]
Thanks for your comments @krystian3w This will be my last commit to this project.

To every one else... Have a blast of better surfing

**Comment by mapx-** [comment]
> This will be my last commit to this project.

from https://github.com/uBlockOrigin/uAssets/blob/master/README.md
```
If an issue can be fixed without using extended syntax, i.e. scriptlet injection, redirect, procedural cosmetic filters, etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

Issues involving

anti-adblock
ad-reinsertion
popups/popunders
site breakage
video ads
will always be fixed in uAssets even if they don't require extended syntax.

If the ABP-compatible fixes are for high-traffic sites, they should be added to uBO filters until they are added to EasyList.
```

**Comment by krystian3w** [comment]
Don't require someone to activate more than 40 lists for you because you like to be active all.

**Comment by ryanbr** [comment]
Seems to be a self promo? not sure if a filter is needed

**Comment by spirillen** [comment]
I did actually only stumbled on this site in another matter and would like to share the site to you , so you could improve you lists.

But with this kind of thanks....

**Comment by krystian3w** [comment]
You had to show the damaged with **two short screenshoots** and not kilometers  screen (useless).
