### ISSUE TITLE
GamesRadar uBlock block

### ISSUE THREAD

**Issue by draconei** [uBlockOrigin/uAssets#6346]
### URL(s) where the issue occurs

`[https://www.gamesradar.com/borderlands-3-katagawa-ball/]`

### Describe the issue

Has a pop-up asking for uBlock to be disabled or pay a fee for a week of ad-free access

### Screenshot(s)

N/A

### Versions

- Browser/version: Firefox
- uBlock Origin version: 0.5.9.21

### Settings

- Enabled adblock warning removal list

### Notes

N/A

**Comment by okiehsch** [comment]
> uBlock Origin version: 0.5.9.21

I can't reproduce and that version of uBlock Origin does not exist.

**Comment by krystian3w** [comment]
Remove crap "0.5.9.21" and install version 1.22.2 from AMO.

> https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

**Comment by draconei** [comment]
Don't know how the hell I got such an outdated version installed. Updated to 1.22.2 and problem is solved. Thanks all.
