### ISSUE TITLE
Block javascript confirm dialog

### ISSUE THREAD

**Issue by mb300sd** [uBlockOrigin/uAssets#6347]
### URL(s) where the issue occurs

Any older BMC. URLs are (or at least should be!) in private address space. For Supermicro:
`https://<ip>/cgi/url_redirect.cgi?url_name=sys_info`

Probably useful for a lot of other sites that pop up confirm() dialogs. (like "Are you sure you want to leave?")

### Describe the issue

Browser Java is dead. Trying to get rid of the annoying popup with no luck with either uBlock or TamperMonkey. Purely blocking deployJava.js breaks the page since the function is called inside code that populates data in it. I'm looking for a way to block confirm() similar to blocking alert() in #8/alert-buster.js. Possibly allowing setting the return value to true/false. Although I'm not sure of the implications of allowing true, false should be safe since that's the Cancel button.

### Screenshot(s)

https://i.imgur.com/ro7EhIy.png

### Versions

- Browser/version: Brave 0.68.141 Chromium: 77.0.3865.90
- uBlock Origin version: 1.22.2

### Notes

Already implemented if accepted.

```
confirm-buster.js application/javascript
(function() {
	var cValue = '{{2}}';
	window.confirm = function(a) {
		console.info(a);
		if ( cValue === 'true' ) {
			return true;
		} else if ( cValue === 'false' ) {
			return false;
		}
	};
})();
```

or if we don't want to allow true

```
confirm-buster.js application/javascript
(function() {
	window.confirm = function(a) {
		console.info(a);
		return false;
	};
})();
```

**Comment by mb300sd** [comment]
Very difficult to reproduce the exact issue - BMC = Board Management Controller, an embedded controller on servers that allows you (among other things) to power off/on/reboot them and install an operating system remotely. Obviously a massive security hole if publicly accessible. Older ones used Java and constantly prompt you to install it when it's not available in the browser, even though they only use it for jnlp which still works.

Being able to block confirm() should be applicable to many other sites though, if an example is 100% required, I can search around for a spammy site that uses it.

**Comment by mapx-** [comment]
Did you try (if the function is `confirm`)

`example.com##+js(set, confirm, trueFunc)`
?

**Comment by mb300sd** [comment]
That actually did it! Spent an hour trying different rules and userscripts to get rid of it and it was that simple lol. Thanks. Closing.

**Comment by mb300sd** [comment]
For anyone that comes across this in the future. The better filter for install Java popups is

`<YOUR_IP>##+js(set, deployJava.versionCheck, trueFunc)`

Works on Supermicro and Intel BMCs, but even better, it looks like deployJava.js is a file directly from Sun/Oracle, so it should work on anything uses the script to check for Java. Tested on a random Chinese IP camera and it works there too! Might as well use it for the whole internet since there's no reason to see the Java check anywhere.
