### ISSUE TITLE
tvnow.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#6349]
### URL(s) where the issue occurs

`https://www.tvnow.de/serien/familien-im-brennpunkt-247/2019-09/episode-79-maedchen-terrorisiert-die-ganze-strasse-1729321`

### Describe the issue

Vide Ads are back

### Versions

- Browser/version: Firefox 69.0.1
- uBlock Origin version: v1.22.2

### Settings

default

**Comment by okiehsch** [comment]
No need to open a new issue for that site next time you can just comment in one of the closed ones.
https://github.com/uBlockOrigin/uAssets/search?q=tvnow.de&type=Issues

IThe fix I added only works with the `uBO-dev` version.

**Comment by krystian3w** [comment]
> one of the closed ones.

worse if he kicked by author of older topic, then can write nothing without create multi-account.

**Comment by AnAncientMonk** [comment]
> No need to open a new issue for that site, next time you can just comment in one of the closed ones. https://github.com/uBlockOrigin/uAssets/search?q=tvnow.de&type=Issues
> 

@okiehsch 

the ads are back (:

https://www.tvnow.de/shows/die-bachelorette-7739/staffel-9/episode-2-folge-2-2022-06-22-20-15-00-4840468

**Comment by okiehsch** [comment]
I can't reproduce, the existing filters work on my end.
I get no pre-roll ads unless I disable `uBO-filters`.

**Comment by AnAncientMonk** [comment]
Hm they're now gone after a page refresh for me too. I swear i had them 20 minutes ago. I intentionally updated purged and updated the filter lists before commenting here. I even double checked with my SO. Weird. 

Sorry for bothering and thanks for taking a look (:
