### ISSUE TITLE
Ads not blocked 1337x

### ISSUE THREAD

**Issue by Dinervity** [uBlockOrigin/uAssets#635]
### URL(s) where the issue occurs

`https://1337x.to/home/`

Ads URL

`https://fi.quasargaming.com/?btag=656186_9F9612950B77454C8B1E657E40DC6AD6&pid=2840280`

`https://fi.quasargaming.com/online-casino?btag=656186_F35E12E9A7D14CCBB87DDF1F04BD5054&pid=2840280`

`https://offers.nordvpn.com/special/?utm_source=aff1308&utm_medium=affiliate&utm_term=wpNPp-NR-40MEWG6&utm_content=66269%2A%2A53fdag6TQnpT6r0aCqaizvfLdkKG84c&utm_campaign=off93`

### Describe the issue

When you click at the starting page and want to download torrent you choose one of the products. After that you want go home page by using 1337x in left corner icon. It will pop up ads.

### Screenshot(s)

Don't have.

### Versions

- Browser/version: Mozilla Firefox 55.0.2
- uBlock Origin version: [here] 1.13.8

### Settings

Haven't done anything on the settings.

### Notes

It shows in easylist that ublock have notice it, but still not remove it.

**Comment by gorhill** [comment]
Force an update of "uBlock filters". Might need to wait a few minutes before GitHub makes the updated filter list available for retrieval by uBO.

**Comment by Dinervity** [comment]
Thanks =D
