### ISSUE TITLE
anime-odcinki.pl - slide broken + popups

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6350]
https://github.com/uBlockOrigin/uAssets/blob/bd6188490d03c35cd380c7e70e9cb90444d2a86f/filters/filters.txt#L12130

No repair homepage...

I must use `exception`, `redirect` or `badifltering`:

<ul><li>

```css
@@||anime-odcinki.pl/wp-content/plugins/jgc-adblocker-detector/js/jgcabd-detect-adblock.js$script
```

<li>

```css
*/jgcabd-detect-$script,redirect=nofab.js
```

<li>

```perl
/jgcabd-detect-$badfilter
/jgc-adblocker-$badfilter
-adblocker-detector/$badfilter
-detect-adblock.$badfilter
```

</ul>

>  >  `/jgcabd-detect-`
>  >  `/jgc-adblocker-`
>  >  `-adblocker-detector/`
>  > `-detect-adblock.` 
>
> are "generic" in EasyList.

## Broken are narrows in sliders:

![obraz](https://user-images.githubusercontent.com/35370833/65783834-f07f0400-e150-11e9-9485-7e6b5e110c18.png)

click no load next "slide".

**Comment by krystian3w** [comment]
Badilter report:

```perl
/jgcabd-detect-$badfilter
/jgc-adblocker-$badfilter
-adblocker-detector/$badfilter
-detect-adblock.$badfilter
```

Still generic, so why no works generichide?

**Comment by mapx-** [comment]
you need - maybe could be added to one of the polish lists ?
```
@@||anime-odcinki.pl^$script,1p
anime-odcinki.pl##+js(aopr, _pop)
anime-odcinki.pl##.size-full
```

`generichide` is working for classic cosmetic filters

**Comment by krystian3w** [comment]
So this is modern blocking:



```perl
    /jgcabd-detect-
    /jgc-adblocker-
    -adblocker-detector/
    -detect-adblock.
```

OMG.
