### ISSUE TITLE
megagames.com [danger?] [anti-adblock]

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6351]
### URL(s) where the issue occurs

`https://megagames.com/patches/singles-2-triple-trouble-v12-patch`

`https://megagames.com/download-ready/252118/0`

### Describe the issue

Adblock Detections

### Screenshot(s)

![obraz](https://user-images.githubusercontent.com/35370833/65785801-7c932a80-e155-11e9-850d-515e27e10353.png) |
--- |

![obraz](https://user-images.githubusercontent.com/35370833/65785580-00004c00-e155-11e9-9e3f-3460192f3471.png) |
--- |

### Versions

- Browser/version: FX 69.0.1
- uBlock Origin version: 1.22.2

### Settings

- Default + Annnoyance + PL

### Notes

```
https://megagames2.online/downloads.php?file=singles2patch_1_2.exe&646965504532567d5954262e5a=1
```

Blacklisted in AdGuard DNS so maybe all website should by blocked:

> # `||megagames.com^`

**Comment by mapx-** [comment]
even whitelisting the page then will land on a broken page (invalid certificate ?)

**Comment by llacb47** [comment]
Certificate is fine for me

**Comment by mapx-** [comment]
yeah, in chrome seems working, and in the end it's an annoyance issue, right ? (the downloading is starting on `megagames2`)

**Comment by llacb47** [comment]
`megagames.com##+js(acis, jQuery, adblock)`

**Comment by okiehsch** [comment]
I have to close the anti adblock message after every reload., so it should be fixed in `uBO-filters`.
