### ISSUE TITLE
phoneinfo.com.br

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#6353]
### URL(s) where the issue occurs

`https://www.phoneinfo.com.br/lg-g7-fit-hard-reset-passo-a-passo/`

### Describe the issue

Anti right-click annoyance.
### Versions

- Browser/version: Firefox stable
- uBlock Origin version: 1.22.2

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin lists

**Comment by llacb47** [comment]
`phoneinfo.com.br##+js(aopw, document.oncontextmenu)`

Also gets rid of anti-select annoyance
