### ISSUE TITLE
TheVideo.me - Popups on click. Everything is a link?

### ISSUE THREAD

**Issue by forkoz** [uBlockOrigin/uAssets#636]
### URL(s) where the issue occurs

https://thevideo.me/claw88jmf1em

### Describe the issue

Play/Pause/Fullscreen the video and it acts as a link to popups. Even over flashblocked video.

### Versions

- Browser/version: FF / Chromium
- uBlock Origin version: 1.13.8

### Settings

Chromium has uMatrix + uBlock

### Notes

This looks vaguely similar to primewire from before.  Is there a way to genericize this filter? I.e limit sites hot linking a large area.

**Comment by okiehsch** [comment]
@forkoz 
`thevideo.me##script:inject(addEventListener-defuser.js, click, void)`
works on my end with Chrome, I can't test with Firefox because the video won't play for me even with
uBO disabled, so could you test this filter with Firefox on your end?

**Comment by SMed79** [comment]
> could you test this filter with Firefox

No popups and no issue to play the video http://i.imgur.com/eZvhhz5.png

**Comment by okiehsch** [comment]
Thanks for testing.

**Comment by forkoz** [comment]
Popups still open when I click on the video. Also had a fake modal display.

Its better but not perfect.
![videome](https://user-images.githubusercontent.com/12354546/29502148-7f315b6e-85f3-11e7-8f61-fcd7abb9bb55.png)

**Comment by forkoz** [comment]
BTW this is what I did to the modal:

! 8/20/2017, 10:00:03 PM https://thevideo.me/jvwr3yba0lot
!thevideo.me##.vjs-modal-dialog.vjs-error-display > .vjs-modal-dialog-content

! 8/20/2017, 10:00:27 PM https://thevideo.me/jvwr3yba0lot
!thevideo.me##.vjs-modal-dialog.vjs-error-display

**Comment by okiehsch** [comment]
I can't reproduce any popups or a fake dialog at `https://thevideo.me/jvwr3yba0lot`
with Chrome and default settings.
I get a sign up link, which will redirect if clicked. fixed with
`thevideo.me##.inplayer_signup_link`
![unbenant](https://user-images.githubusercontent.com/16838044/29502363-a2cc2568-862f-11e7-8871-0ad55fb953bc.JPG)

**Comment by forkoz** [comment]
Its working great on chrome. I just opened up a show there.

**Comment by okiehsch** [comment]
Ah okay if you only have problems with Firefox I can't help, like I said the player won't load no matter what on my end, no clue why.

**Comment by forkoz** [comment]
Every little bit helps. Your player on FF won't load, right now mine won't connect. Ping is 120ms here though, 20 ms where it works.

**Comment by SMed79** [comment]
Tested again in Firefox / uBo default settings https://streamable.com/s/uc2xl/vscegv

> https://github.com/uBlockOrigin/uAssets/commit/48a501ffe3c4be9f792ce9776bf59d246023a610

That not an advert and should not be removed.

**Comment by okiehsch** [comment]
If I click on it it gets blocked by 
`||thevideo.me^$popup,domain=thevideo.me|vidup.me`, so it is not functional
but after allowing the popup I can see that you are right, I will revert the fix.
