### ISSUE TITLE
digicular.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6363]
```
https://digicular.com/private-dns-over-tls-android/
```

double scroll:

![obraz](https://user-images.githubusercontent.com/35370833/65822372-efc69a80-e242-11e9-83ad-0a959f976729.png)

**Comment by krystian3w** [comment]
@yourduskquibbles  what do you think?

**Comment by mapx-** [comment]
`digicular.com##html:style(overflow: hidden !important;)`

**Comment by krystian3w** [comment]
for My filters panel or you add this into e.g. `unbreak.txt`?

**Comment by mapx-** [comment]
in `annoyances` list
