### ISSUE TITLE
2mdn.net and -contrib-ads/ break video

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#637]
### URL(s) where the issue occurs

`https://www.radiojavan.com/videos/video/mojan-yz-saman-pi-chalim-2-(ft-ho3ein)`

### Describe the issue

Video broken

### Notes
EasyList and Peter Lowe both break the video. If EasyList is disabled and Peter Lowe is enabled, Peter Lowe will block `2mdn.net` which breaks the video. If Peter Lowe is disabled and EasyList is enabled, EasyList will block `-contrib-ads/` which breaks the video.

**Comment by ghajini** [comment]
clicking on 480p/720p starts video

**Comment by terrorist96** [comment]
You're right. However, when EasyList and Peter Lowe are both disabled, the video will start without having to click on 480p/720p. Weird.

**Comment by mapx-** [comment]
`@@||cdnjs.cloudflare.com/ajax/libs/videojs-contrib-ads/$script,domain=radiojavan.com`

**Comment by terrorist96** [comment]
@mapx- Thanks, that works!

**Comment by SMed79** [comment]
Fixed https://github.com/easylist/easylist/commit/f1a3a78b9abf1b5d9a92c458270c9f94934216c6
