### ISSUE TITLE
delfi.lt

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6372]
### URL(s) where the issue occurs

`https://www.delfi.lt`

### Describe the issue

Ad in header back...

### Screenshot(s)

![obraz](https://user-images.githubusercontent.com/35370833/65991002-f0eb0800-e48c-11e9-848a-09efc0431d6f.png) |
--- |

### Versions

- Browser/version: Chrome 77
- uBlock Origin version: 1.22.4

### Settings

- Default + Annoaynce + PL

### Notes

https://github.com/AdguardTeam/AdguardFilters/issues/41420

Noob solution for header:

```css
delfi.lt###header-top-banner + [class]:not(.container):has(> img[src*="cdn"])
```

right column:

```css
delfi.lt##.container.bb2 > .row > [class]:has(> *:has(> img[src*="cdn"]))
```

**Comment by krystian3w** [comment]
`||adform.net/banners/scripts/adx.js$script,redirect=noopjs`

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/41420
https://github.com/uBlockOrigin/uAssets/issues/6372
https://github.com/abp-filters/abp-filters-anti-cv/issues/57

**Comment by mapx-** [comment]
> `||adform.net/banners/scripts/adx.js$script,redirect=noopjs`

it does not work for me

**Comment by krystian3w** [comment]
So maybe afected with DoH...

https://github.com/curl/curl/wiki/DNS-over-HTTPS#publicly-available-servers I changed to AdGuard service.

**Comment by mapx-** [comment]
test
`delfi.lt##+js(std , banner)`

working too: `delfi.lt##+js(aopr, _dlf._ab)`  but they are changing it periodically
