### ISSUE TITLE
cimaclub.com [New-tap Ad]

### ISSUE THREAD

**Issue by Iaycomand** [uBlockOrigin/uAssets#6373]
### URL(s) where the issue occurs

`https://m.cimaclub.com/jojo-no-kimyou-na-bouken-الموسم-5-الحلقة-29-مترجمة/`

### Describe the issue

it opens a new-tap ad when you click on the video to play.

### Versions

- Browser/version: Google chrome Version 77.0.3865.90 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin  v1.22.4

**Comment by krystian3w** [comment]
I can reproduce if I pause video (not start).

**Comment by krystian3w** [comment]
When the blinking doesn't interfere:

`|about:$popup,domain=cimaclub.com|govid.me`

Scirplet can works faster and better.

**Comment by llacb47** [comment]
```
||areantaid.site^
||gvesgrun.online^
```
