### ISSUE TITLE
the-voice-of-germany.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#6374]
### URL(s) where the issue occurs

`https://www.the-voice-of-germany.de/video/96-die-weiter-entwicklung-der-rea-garvey-klammer-clip`

### Describe the issue

Pre Video Ads

### Versions

- Browser/version: Firefox 96.0.1
- uBlock Origin version: uBlock Origin v1.22.4

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3678544/Settings.txt)

**Comment by mapx-** [comment]
test
```
the-voice-of-germany.de##+js(aopr, $ADP)
||cdn.zomap.de^$media,redirect=noopmp3-0.1s,domain=the-voice-of-germany.de
```

**Comment by okiehsch** [comment]
Works fine on my end with Chromium and Firefox.
