### ISSUE TITLE
howwebiz: banners

### ISSUE THREAD

**Issue by unknowboy1991** [uBlockOrigin/uAssets#6382]
### URL(s) where the issue occurs

**NSFW**
`https://www.howwebiz.ug/news/celebrity/16863/selena-gomez-suffers-nip-slip-wardrobe-malfunction-in-white-top.php`

### Describe the issue

1) Banners at the each side of the page are shown
2) Sidebar displays empty grey bars with the text "Advertisements"
3) Top ads (`.___top-ad-wrap`)

### Screenshot(s)

1) [banners](https://www.howwebiz.ug//ads/airtel/Aug-3-2019/140-600-PX.png)
2) [sidebar](https://user-images.githubusercontent.com/30636501/66037462-884b6c00-e51c-11e9-8521-69c2b3066d40.png)
3) can provide if needed

### Versions

- Browser/version: 77.0
- uBlock Origin version: 1.22.4

### Settings

Left as default

#### 1. for banners
The offending image:
```
https://www.howwebiz.ug//ads/airtel/Aug-3-2019/140-600-PX.png
```

Proposed filters:
```
||www.howwebiz.ug/*/ads/*
howwebiz.ug##div.sticky_item a[target="_blank"]
```

#### 2. for sidebar
Proposed filters:
```
howwebiz.ug##.with_title._300_ad
```

or even:
```
##._300_ad
```

#### 3. for top ads
Proposed filters:
```
howwebiz.ug##.___top-ad-wrap
howwebiz.ug##._inr___top-ad-wrap
```

or
```
##.___top-ad-wrap
##._inr___top-ad-wrap
```

**Comment by uBlock-user** [comment]
`/ads/*$1p,image
`

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by mapx-** [comment]
to be reported here (classic ads)
https://github.com/easylist/easylist/issues

**Comment by unknowboy1991** [comment]
@mapx- I made one https://github.com/easylist/easylist/issues/4110
