### ISSUE TITLE
shrinkme.io

### ISSUE THREAD

**Issue by WaferNabati** [uBlockOrigin/uAssets#6387]
URL(s) where the issue occurs
`https://shrinkme.io/umhXW6ot`

Describe the issue
Popups

Versions
uBlock Origin version: 1.22.4

Browser/version
Chrome 77.0.3865.90 (Official Build) (64-bit)

Settings
uBO's default settings

**Comment by ghajini** [comment]
`shrinkme.io/okFteujx`
3rd party tracking xhr's

**Comment by ghajini** [comment]
`shrinkme.io/hTmcLIbF`

Filter=

`*$script,3p,domain=shrinkme.io`

**Comment by llacb47** [comment]
![image](https://user-images.githubusercontent.com/16567977/79129826-e1217a00-7d73-11ea-86b4-23e854d9a8bf.png)

**Comment by ghajini** [comment]
Link updated

**Comment by llacb47** [comment]
`https://ntvsw.com/code/native.js?h=waWQiOjEwMTgzMzQsInNpZCI6MTAzODQ0Miwid2lkIjo3MDIzMywic3JjIjoyfQ==eyJ`

`||ntvsw.com^$3p`

**Comment by doio** [comment]
https://shrinkme.io/SH9IEUa

Recaptcha box will not show

**Comment by mapx-** [comment]
I cannot reproduce your issue, however I modified a filter, wait 10 min then update uBO filters list and test again
