### ISSUE TITLE
aii.sh [Popups]

### ISSUE THREAD

**Issue by WaferNabati** [uBlockOrigin/uAssets#6389]
URL(s) where the issue occurs
`https://aii.sh/xYmNE`

Describe the issue
Popups

Versions
uBlock Origin version 1.22.4

Browser/version
Chrome 77.0.3865.90 (Official Build) (64-bit)

Settings
uBO's default settings

**Comment by ghajini** [comment]
`https://aii.sh/TNR1l`

Popup ads

Block `ctzs.pw` high risk site(`https://prnt.sc/pll1co`)

**Comment by ghajini** [comment]
`https://aii.sh/EBwLw`
Popup ads

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/d250fbcf29052298fab05698680b65dbbf20bd56

**Comment by ghajini** [comment]
`||fixsirrod.site^`

**Comment by mapx-** [comment]
`aii.sh###cookie-pop`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/6e675dadaa04af9618ff3c31b37dd25830d9523c
