### ISSUE TITLE
digitallearn.online [Popups]

### ISSUE THREAD

**Issue by WaferNabati** [uBlockOrigin/uAssets#6390]
URL(s) where the issue occurs
`https://digitallearn.online/xepJbVtL`

Describe the issue
Popups

Versions
uBlock Origin version 1.22.4

Browser/version
Chrome 77.0.3865.90 (Official Build) (64-bit)

Settings
uBO's default settings

**Comment by dumbusernameidk** [comment]
no popups on my end either.
