### ISSUE TITLE
turkleech.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6393]
### URL(s) where the issue occurs

`http://turkleech.com/indir/?id=133990&f=Um9jY28gRSBMZSBUb3AgTW9kZWwgRGVsIENhenpvLnBhcnQ=&s=NTAwIE1C`

### Describe the issue
Page got blank/broken (may be due to detection of Adblock)

### Screenshot(s)

`https://prnt.sc/penllb`

### Versions

- Browser/version: firefox android stable
- uBlock Origin version: 1.22.4

### Settings

-  uBO's default settings

### Notes
Just reload if unable to reproduce

**Comment by ghajini** [comment]
Adblock warning banner,

`||turkleech.com/indir/img/tlbg.jpg`

**Comment by okiehsch** [comment]
That banner is visible even if I disable `uBO`.

**Comment by ghajini** [comment]
Okay
