### ISSUE TITLE
uiz.io [Anti adblock]

### ISSUE THREAD

**Issue by RaveN0X87** [uBlockOrigin/uAssets#6394]
URL(s) where the issue occurs
`https://uiz.io/ftQTW`

Describe the issue
Anti adblock

Screenshot(s)
`https://i.imgur.com/E8pG0gF.png`

Versions
uBlock Origin version 1.22.4

Browser/version
Google Chrome v77.0.3865.90 (Official Build) (64-bit)

Settings
uBO's default settings+nano defender

**Comment by ghajini** [comment]
So many crap xhr's still there alongwith 3rd party. ....
Firefox android

**Comment by ghajini** [comment]
page becomes unscrollable after loading is complete.

Tried ubo disabled, scrolling is smooth.....

**Comment by mapx-** [comment]
ok, I 'll add
`uiz.io##body:style(overflow: auto !important;)`

**Comment by KiLL4FuNK** [comment]
Anti adblock

**Comment by ghajini** [comment]
`uiz.io/MPeK7l`
Popup ads in intermediate pages

**Comment by ghajini** [comment]
`https://uiz.io/2Sgl`
Antiadblock 
On visiting the site redirects to antiadblock page

![IMG_20200118_133954](https://user-images.githubusercontent.com/20338483/72660762-1417d400-39f8-11ea-8764-826debc56d61.jpg)

**Comment by ghajini** [comment]
`https://uiz.io/Y6CF?rc3f=1`

Filters =
`||ampallall.site^`
`||2.13i.org^`
`||ashaidbit.club^`
`||ashamparm.site^`

**Comment by ghajini** [comment]
Clicking on `continue/download`  results in popup which is closed by easylist filter

https://user-images.githubusercontent.com/20338483/73195878-a0429d80-4154-11ea-8546-75de83751b94.jpg

**Comment by ghajini** [comment]
Antiadblock 
`https://moon7.xyz/xuFR0` (uiz.io site)

**Comment by mapx-** [comment]
I get no anti adb but is going directly (without waiting for a click or other action) to `ouo.press` or `ouo.io`

**Comment by ghajini** [comment]
Screenshot=
`https://prnt.sc/s3hwr6`

Source page= `https://pastebin.com/mLBg2BHc`

Firefox android
Try new ip/clear cookies
