### ISSUE TITLE
Block spamrl - the fake email Real-time Blackhole List

### ISSUE THREAD

**Issue by HLFH** [uBlockOrigin/uAssets#6395]
### URL(s) where the issue occurs

`https://spamrl.com`
`https://www.solarwindsmsp.com/`
`https://www.spamexperts.com/`

### Describe the issue

> [SolarWinds](https://en.wikipedia.org/wiki/SolarWinds) Inc. is an American company that develops software for businesses to help manage their networks, systems, and information technology infrastructure. SolarWinds is headquartered in Austin, Texas.

> During 2015, SolarWinds announced its acquisition of Librato (a monitoring company),[42] and Capzure Technology (an MSP Manager software to N-able which SolarWinds had previously acquired).

> In June 2016, SolarWinds acquired LogicNow, a rival remote monitoring software company. A new subsidiary SolarWinds MSP was formed by merging LogicNow and N-able Technologies. The company announced that the subsidiary will be led by LogicNow's former CEO Walter Scott with a new title of executive vice president.

> Between 2017 and 2019, SolarWinds acquired SpamExperts (an email security company).

SolarWinds MSP maintains a [Real-time Blackhole List](https://en.wikipedia.org/wiki/DNSBL
) `spamrl.com` which meets one criticism criteria: 

> Some lists have unclear listing criteria and delisting may not happen automatically nor quickly. A few DNSBL operators will request payment (e.g. uceprotect.net)[21] or donation (e.g. SORBS). 

On `spamrl.com` website, it admits the following:

> If your message was wrongly rejected, please try to find other means to reach out to the recipient so they can release & train the email from their spam quarantine and report your wrongly classified email to their antispam provider [= SolarWinds Mail Assure only]. This will not only resolve the immediate reputation issue, but also helps in improving your IP/domain reputation for the future. Although it was rejected with a 5xx error at SMTP level, they really can still access and release & train the email from their quarantine. 

You can often be wrongly rejected by this RBL compared to the efficient ones such as [SpamHaus](https://www.spamhaus.org/). Because in the last two to three years, the business model of SolarWinds Mail Assure became the following:

1. Either you contact a client of SolarWinds MSP that blocks you such as the veterinary service hackney [at] goddardvetgroup.co.uk because they use `SolarWinds Mail Assure` that implements the spamrl.com RBL with a huge load of false-positives. And you cannot contact them from your blocked mailserver. You probably need to contact the SolarWinds client from a Gmail or Outlook.com/MS Exchange solution to avoid being blocked as false-positive.

2. The solution one rarely works because it not something that is easily done by SMBs that have other things to do than realize the antispam solution `SolarWinds Mail Assure` is not working. So I would need to subscribe myself to SolarWinds Mail Assure to send an email from my previous mail server to their system and release & train my false-positive rejected email from their spam quarantine.

Their fake antispam would reject the email sent by your Postfix MTA with these details:

Final-Recipient: rfc822; email-of-a-solarwinds-mail-assure-client@example.com
Original-Recipient: rfc822;email-of-a-solarwinds-mail-assure-client@example.com
Action: failed
Status: 5.0.0
Remote-MTA: dns; mx1.mtaroutes.com [38.111.198.182]
Diagnostic-Code: smtp; 550 High probability of spam

Even if you are whitelisted in every available RBL, you can be wrongly rejected by `spamrl.com` and they don't say why.
Instead of buying their antispam solution that has numerous false-positives, I would recommend to classify their product as badware.

### Versions

- Browser/version: Version 77.0.3865.90 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.22.4

### Settings

No changes.

### Notes

I have added the following in my custom filter and I am pushing a PR to this repo.
https://github.com/uBlockOrigin/uAssets/pull/6396

> ||spamrl.com
||solarwindsmsp.com
||spamexperts.com

### Sources
https://uk.trustpilot.com/review/spamrl.com
<img width="443" alt="Screenshot 2019-10-04 at 18 19 33" src="https://user-images.githubusercontent.com/2359059/66226783-92fc3180-e6d3-11e9-867a-b78d67eabf12.png">

https://www.reddit.com/r/sysadmin/comments/4xv5ck/rbl_spamrlcom_anyone_have_experience_with_them_or/
<img width="836" alt="Screenshot 2019-10-04 at 17 37 55" src="https://user-images.githubusercontent.com/2359059/66224430-be7c1d80-e6cd-11e9-96ed-7d3d576f3330.png">
https://www.webhostingtalk.com/showthread.php?t=1598238

**Comment by okiehsch** [comment]
To summarise the request, you argue that the mentioned domains should be added to the badware list because their antispam filter list is inefficient, has many false positives and removing entries is near impossible unless one purchases their "toolbox service"?

**Comment by HLFH** [comment]
All these domains are directly related to their antispam filter. Yes, it is more than inefficient, has many false positives, and removing entries is near impossible unless one purchases their SolarWinds Mail Assure product. I consider it to be a fraudulent DNSBL at the time. That why I recommend to block these domains as long as they have a bad DNSBL policy [not compliant with RFC6471](https://www.ietf.org/rfc/rfc6471.txt). Because of its lack of transparency, I don't know how fake it is, SpamHaus encountered partial similar experiences with `[nszones.com](https://www.spamhaus.org/organization/statement/008/fake-dnsbl-uncovered-nszones.com)`:

> Nszones operates a 'remove your IP' scam charging naive internet users to be removed from the [...] nszones DNSBLs. Nszones also attempts to sell 'commercial subscriptions' to the [...] nszones DNSBLs.

As well as `[Protected Sky](https://www.spamhaus.org/organization/statement/015/fraudulent-dnsbl-uncovered-protected-sky-bad.psky.me)`:

> The Protected Sky web site contained almost no information on its data, procedures or policies, nor offered any way to request delisting/removal (one of the most important Best Practices as defined by RFC6471)

> However, user comments (as seen in the links above) also indicate high false positive rates

I

**Comment by okiehsch** [comment]
> That's why I recommend to block these domains as long as they have a bad DNSBL policy not compliant with RFC6471.

@gorhill do you think that such issues should be blocked in the badware list.

**Comment by gorhill** [comment]
Their is Spam404 for such requests, badware is not for this.

**Comment by HLFH** [comment]
> There is Spam404 for such requests, badware is not for this.

[Done](https://www.spam404.com/report.html). We'll see how it goes.

**Comment by HLFH** [comment]
[Spam404 said the following](https://twitter.com/Spam404Online/status/1181194593729175553):

> We add domains to our blacklist that have clear malicious intent. If you have any supporting evidence for that, we'd be happy to review again.

To discover what is going on, you have to:

 1. Register for the [trial](https://www.solarwindsmsp.com/products/mail-assure/trial) of Solarwinds Mail Assure.
 
2. From their admin web interface, add a mail domain such as an unused domain name with the free mail offer of your registrar ; you can use for that the registrar OVH with its free hosting plan Start10M linked to your unused domain name.

3. Create an email address in your registrar such as postmaster@example.com.

4. Remove the email redirection if the registrar has created one by default.

5. Update your MX records on your unused domain name to the [global MX records of Solarwinds](https://documentation.solarwindsmsp.com/mail-assure/documentation/qsg/Content/Topics/incoming-filtering/change-your-mx-records.htm).

6. Send the false-positive email to postmaster@example.com.

7. Raise the [quarantine threshold](https://documentation.solarwindsmsp.com/mail-assure/documentation/Content/C_Domain%20Level/incoming/manage-quarantine-filter-settings.htm) to 0.9.

8.  Send some other tests with some changes on the subject line of the email or the message.

9. Check the differences of the [Mail Assure combined score](https://success.solarwindsmsp.com/kb/mail_assure/What-does-the-classification-Combined-Score-mean).

10. You will likely realize it is not about sender issues in terms of SPF, DKIM and DMARC policies but more about the content scanner for subject line & message which contributes to the Mail Assure combined score. If you avoid some spam trigger words and humanize more your message, it should finally go through the Mail Assure spam filter. 

11. A normal email which has not been entirely optimized in terms of subject line & message can get a combined score of 0.77 or even a bit more, so you can get easily a false-positive for no good reason. Their content scanner is flawed.

12. Solarwinds says the following about the Combined Score:

> Combined Score
The "combined" result provides a weighted classification score of the different classifiers. Depending on the configured "quarantine threshold", the message will be rejected as spam or accepted. A quarantine threshold score of 0.9 is recommended. To be more tolerable for senders using a wrong HELO/PTR/IP configuration, a score of 0.91 can be set. The lower the quarantine threshold, the more messages will be quarantined as spam. The SMTP message returned for this classification is "High probability of spam" to the sender. **Please ensure to release the message from quarantine if it's legitimate, this will adjust the scoring in our various databases**

I am checking if a normal email that has been classified as unsure with a Combined Score of 0.77 can have his score adjusted/reduced with a [release & train procedure](https://documentation.solarwindsmsp.com/mail-assure/documentation/Content/C_Domain%20Level/incoming/release-and-train-quarantined-messages.htm) from quarantine. If it is the case, I will be able to confirm Mail Assure can be _somewhat_ efficient.
