### ISSUE TITLE
tunein.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#6397]
### URL(s) where the issue occurs

`https://tunein.com/podcasts/Electronic-Garage/Dub-City-Steppers-p395036/`

### Describe the issue

Overlay annoyance.

### Versions

- Browser/version: Firefox stable
- uBlock Origin version: 1.22.4

### Settings
Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin lists

**Comment by mapx-** [comment]
test
```
tunein.com##.dark-theme-dialog__dialogBody___106Di
tunein.com##.dark-theme-dialog__dialogBody___106Di:nth-ancestor(4)
```

**Comment by adranger** [comment]
That works for me.

**Comment by krystian3w** [comment]
`:nth-ancestor(4)` no hide both (imo enough one filter).

**Comment by uBlock-user** [comment]
@mapx- Getting anti-adblock notice at the footer when trying to play the music..

`*/$xhr,redirect-rule=noop.txt,domain=tunein.com`

Does the music play after adding that filter ?

**Comment by mapx-** [comment]
this filter is working fine in chrome / FF
`*$xhr,redirect-rule=noop.txt,domain=tunein.com`

**Comment by THEtomaso** [comment]
@mapx-:
With your current fix, a modal overlay remains at first load, and the scrollbar is locked.
It solves itself when you click on something, but it would be nice to have it fixed, regardlessly.
I tried messing around with it myself, but it turned out to be more complicated than expected. :)

**Comment by mapx-** [comment]
@THEtomaso are you talking about legacy version ?

**Comment by mapx-** [comment]
maybe for legacy needing
`tunein.com##div[style]:has(.dark-theme-dialog__dialogBody___106Di)`

**Comment by THEtomaso** [comment]
> are you talking about legacy version ?

Oh, that's right..
uBO Legacy doesn't convert `:upward` yet
In this case `:xpath(../../../..)` would fix it.

@JustOff:
Any chance of updating the conveter anytime soon?

**Comment by THEtomaso** [comment]
For the time being, perhaps this could be added to the Legacy list?:
```
tunein.com##.dark-theme-dialog__dialogBody___106Di
tunein.com##.dark-theme-dialog__dialogBody___106Di:xpath(../../../..)
```

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/6397#issuecomment-640218659

**Comment by THEtomaso** [comment]
OK, so I now see that `:nth-ancestor` aren't used anymore at all, and all of the rules which used that syntax has been replaced with `:upward`.
This makes a uBO Lagacy update much more important!

**Comment by THEtomaso** [comment]
Amongst the filters which I'm currently using, I only found one rule that has the old `:nth-ancestor` syntax.
It's this one (found in '**Browse websites without logging in**'):
`deezer.com###modal_login:nth-ancestor(2)`
@DandelionSprout: Perhaps you could update it?
