### ISSUE TITLE
DI.FM - works on Linux not on Windows

### ISSUE THREAD

**Issue by Hakun1n** [uBlockOrigin/uAssets#6399]
### URL(s) where the issue occurs
`https://www.di.fm`

### Describe the issue
I have two workstations.
- One is running Fedora 29 + FireFox 69.0.1 + uBlockOrigin 1.22.4. Ad-Blocking works nicely on di.fm and music plays continuously w/o ads or triggering anti-adblock protection. All good here.
- Second is running Windows 7 with the same FireFox 69.0.1 and uBlockOrigin 1.22.4. Music stops working after about ~10mins because anti-adblock gets triggered and page jumps to `https://www.di.fm/about-blockers`

Note that you have to be logged-in as **"free user"**, not an "anonymous listener" (anon does not have adds but ends after few mins asking for registration)

I don't have any custom filters nor white-listed items. List of enabled filters bellow.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/12685294/66252846-e14f1600-e74f-11e9-81ee-fd6890c73b3d.png)

### Versions
- Browser/version:  69.0.1
- uBlock Origin version: 1.22.4

### Settings
No changes, just added extra language-specific filters.

### Notes
Frankly i have no idea how to debug this. It seems to me that some filters are parsed differently on Linux/Windows so it works only on Linux.
Attaching FF console network export and uBlock log, not sure if it has any value.

[www.di.fm_Archive [19-10-05 09-16-41].zip](https://github.com/uBlockOrigin/uAssets/files/3693049/www.di.fm_Archive.19-10-05.09-16-41.zip)
[ub_log.txt](https://github.com/uBlockOrigin/uAssets/files/3693051/ub_log.txt)

Let me know if you want me to provide more info or test/try something. Thank you !

**Comment by mapx-** [comment]
- Test using ONLY the default lists (settings) => you could backup the current setup, reset uBo to default settings. Then update all your (default) lists => click "purge all caches" then click "update now"

- be sure keeping enabled (for test) only uBo as blocking addon => disable all other similar addons

**Comment by Hakun1n** [comment]
Wow, that was superfast and easiest then i thought! Yes after reset to default + cache purge it works again!

Thank you for your reply/solution and sorry that i haven't done this by myself but raised an incident. Next time i have issues i will do the reset first and then start asking questions :]

Alex
