### ISSUE TITLE
gamestar.de

### ISSUE THREAD

**Issue by AetherMcLoud** [uBlockOrigin/uAssets#64]
www.gamestar.de still shows the anti-adblock banner, and the video player seems to block adblock too.

For videos that use the built in site player, with uBlock Origin and AAK the player will switch to a low-resolution player that shows the anti-adblock banner. With adblock off, the player UI is black instead of white, and it will show HD videos.

Example of low rez video player with uBlock and AAK on: https://i.imgur.com/l6zIWEQ.jpg
The low rez player is a flash plugin by default, when disabling flash in Chrome, it switched to a HTML5 low rez player so that didn't help either. The HD player is always HTML5 I think.

Same site with uBlock off, showing the default HD player: https://i.imgur.com/G9UJ5Bl.jpg

Site for that video: http://www.gamestar.de/videos/e3,106/the-legend-of-zelda-breath-of-the-wild,89161.html

The default site, www.gamestar.de shows the "please disable adblock" banner in the middle like this: https://i.imgur.com/K2E2sdU.jpg

I really hope this is fixable, because the site has good content but the ads are getting more annoying each day.

Edit: I added some personal filters I got from reddit:

```
www.gamestar.de##script:contains(uabInject)

gamestar.de##div[id$="-outer"]

gamestar.de##div[id][style="display: inline-block;"]

||gamestar.de/spiele/combine.js*royalslider$script,domain=gamestar.de

```

These seemed to remove the anti adblock banner, and most importantly now the video player stays on the HD mode instead of switching to the low rez player. 

They make their embedded video player on content sites unusable (play button does nothing): http://www.gamestar.de/hardware/konsolen/microsoft-xbox-one/news-artikel/xbox_one_project_scorpio,483,3274179.html

But clicking the link below the video which opens it it a new site, now uses the HD player: http://www.gamestar.de/videos/trailer,3/xbox-one-project-scorpio,89080.html

 I don't exactly know what those filters do though and if they break something else on the site.

**Comment by gorhill** [comment]
> Example of ads still going thru uBlock and AAK, also a embedded youtube video playing an ad: http://i.imgur.com/SPShSgi.jpg
> 
> Link for that example: http://www.gamestar.de/news/vermischtes/3274493/star_wars.html

It's as if you disabled your blocker for that page, on my side the page is clean (default settings + EasyList Germany):

![a](https://cloud.githubusercontent.com/assets/585534/16155966/de413550-347f-11e6-9b5d-763bbf81284d.png)

**Comment by AetherMcLoud** [comment]
Oh, you're right, I must have deactivated ublock for testing on that specific site. With it on the 2 banner ads are gone and the youtube embed is without ads again :) I edited my first post and removed those issues, but the big issue with the site's built in player switching to a low resolution mode still stands sadly.

**Comment by pcworld** [comment]
The website replaces the player under the condition `typeof window.uabInject !== 'undefined' && window.uabInject === true`. When I execute `delete window.uabInject;` in Chromium's developer console shortly after the website is loaded, the player does not get replaced.

I tried adding the delete statement as a new resource into 1.9.4_0/assets/ublock/resources.txt on my installation of the extension in Chromium, even updated the checksums.txt, but I can't get uBlock to actually inject the script (I tried `gamestar.de##script:inject(uabinject-delete.js)` where `uabinject-delete.js` is the name of my new resource). Unfortunately I couldn't find documentation on how to add and test new resources.
Can anyone point me in the right direction?

**Comment by gorhill** [comment]
Is it that `gamestar.de` no longer needs `uabinject-defuser.js`? Could you try with 1.9.7rc0 with the filter `gamestar.de#@#script:inject(uabinject-defuser.js)`? If all works is fine with that filter, then I will remove `gamestar.de` from the filter which inject `uabinject-defuser.js`.

**Comment by pcworld** [comment]
You're correct, with 1.9.7rc0 and `gamestar.de#@#script:inject(uabinject-defuser.js)` the video player doesn't get replaced and I don't see any ads on the site.
By the way, it would be nice if inject filters were shown in the logger.

**Comment by pcworld** [comment]
You should also remove gamepro.de from that list, that website is owned by the same company and has the same problem ([example url](http://www.gamepro.de/videos/forza-horizon-3-test-video-zum-besten-rennspiel-des-jahres,90407.html)), `gamepro.de#@#script:inject(uabinject-defuser.js)` fixes it for me.
