### ISSUE TITLE
Disable Ad-Block message appears over video player on KissAsian.ch/com

### ISSUE THREAD

**Issue by MarsWanKenobi** [uBlockOrigin/uAssets#640]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://kissasian.ch/`
`http://kissasian.com/`

### Describe the issue

Anti-adblock message not  blocked. The ads surrounding the sidebars and above the video player on any show are not shown but I think the video itself is protected somehow and it blasts its Adblock warning message. Site is practically unusable without uBO enabled.

### Screenshot(s)

https://screenshots.firefox.com/7obrFrPIQkmfBP1G/kissasian.ch

### Versions

- Browser/version: Nightly 57.0a1 (08-20-2017 64-bit) on Ubuntu 16.04.2
- uBlock Origin version: 1.13.9rc4

### Settings

- enabled extra filters, left it at default mostly. Blocked one or two ads using Element Picker but not on 
the problematic site in question

Filters enabled:

- uBlock filters
- uBlock filters - Badware Risks
- uBlock filters - Privacy
- uBlock filters - Unbreak
- AdBlock Warning Removal List
- Easylist
- EasyPrivacy
- Malvertising filter list by Disconnect
- Malware Domain List
- Malware domains
- Anti-ThirdPartySocial
- Fanboy's Annoyance List
- Peter Lowe's Ad and tracking server list
- KOR: Fanboy's Korean
- KOR: Korean Adblock List
- AAK-Cont Filter for uBlock Origin

### Notes

Using the Element Picker to block the ad within the video failed and video did not play. Adblock warning came up again on a reload.

**Comment by okiehsch** [comment]
I can't reproduce, I think gorhill fixed this already https://github.com/uBlockOrigin/uAssets/commit/430b6be91ed913baa615570a70eb31c38daff01c, if you  update your uBO-filter list can you still reproduce?

**Comment by MarsWanKenobi** [comment]
I was just typing a reply to gorhill on Reddit. Indeed, this is not reproducible anymore after updating uBO filters and clearing browser cache.
