### ISSUE TITLE
hqporner.com [anti-adblock] [NSFW] [porn]

### ISSUE THREAD

**Issue by Samwisegee90** [uBlockOrigin/uAssets#6400]
### URL(s) where the issue occurs

All videos, example `https://hqporner.com/hdporn/93843-our_daughters_wedding_day.html`

### Describe the issue

Videos normally have a variety of quality options (360p, 720p, 1080p, 4k) but after a recent change, a popup appears that says "AdBlock detected. Only low quality video will be available" and the quality options disappear.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Firefox 69.0.1 (64-bit)
- uBlock Origin version: 1.22.4

### Settings

- default with Adblock warning removal list
### Notes

Don't judge me

**Comment by Samwisegee90** [comment]
The site appears to have been updated which breaks the previous fix. They now use 'hasAdblock' instead of 'canRunAds'

**Comment by uBlock-user** [comment]
> They now use 'hasAdblock' instead of 'canRunAds'

They still use the same, no change in variable -- `https://mydaddy.cc/js/ads.js`

**Comment by playonevideo** [comment]
Fake "Live Sex" button that, when clicked, opens a popup:

https://github.com/user-attachments/assets/d56b678a-40e5-454f-a9a8-faa3b8c33be9" />
https://github.com/user-attachments/assets/f3ae7d44-7959-49d4-a6c3-fdef2bd41945" />

Also, when you first enter the site, any video you click on the page wants to open a popunder:
https://github.com/user-attachments/assets/bfd32f7c-8618-4933-82e1-9834bde0977f" />
