### ISSUE TITLE
https://www.spokesman.com/

### ISSUE THREAD

**Issue by troysjanda** [uBlockOrigin/uAssets#6402]
### URL(s) where the issue occurs

`https://www.spokesman.com/`

### Describe the issue

huge popup and article blocking

### Screenshot(s)

Not able to take screen

### Versions

- Browser/version: Firefox 69.0.2
- uBlock Origin version: Ubo 1.22.5rc1

### Settings

- No changes to settings using a few custom lists
### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by uBlock-user** [comment]
```
||ayc0zsm69431gfebd.xyz^$3p
||czx5eyk0exbhwp43ya.biz^$3p
```

Should do it..

**Comment by troysjanda** [comment]
Thanks you confirmed to be working.
