### ISSUE TITLE
Page not load on fandango.lat while ublock is on 

### ISSUE THREAD

**Issue by seb233** [uBlockOrigin/uAssets#6408]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by okiehsch** [comment]
@mapx- can you reproduce? The site loads fines on my end.

**Comment by mapx-** [comment]
No issue for me.

@seb233  provide all the necessary info: browser version, uBo version, filter lists enabled in uBo.
Disable any other blocking extension and test again with default settings in uBo.

**Comment by krystian3w** [comment]
I have broken slider:

![obraz](https://user-images.githubusercontent.com/35370833/66271401-e4d0c300-e85d-11e9-850a-2dd66c991974.png) | ![obraz](https://user-images.githubusercontent.com/35370833/66271406-f619cf80-e85d-11e9-89ac-fc2bbfc07f02.png)
--- | ---
Broken | uBO disabled
