### ISSUE TITLE
rs-online.com

### ISSUE THREAD

**Issue by chengsun** [uBlockOrigin/uAssets#641]
### URL(s) where the issue occurs

`http://uk.rs-online.com/web/c/semiconductors/discrete-semiconductors/bipolar-transistors/`

### Describe the issue

Component filter/sort are broken. The error console shows `ReferenceError: rs is not defined` multiple times. The object `rs` is initialised in the blocked script `http://uk.rs-online.com/js_08032017_091956/analytics.min.js`.

### Versions

- Browser/version: Chromium Version 60.0.3112.78 (Developer Build) (64-bit)
- uBlock Origin version: 1.13.8

### Notes

Blocked by blanket rule `/analytics.min.` in EasyPrivacy. Fixed using exception:
```
@@rs-online.com^$first-party,script
```
Note that this may or may not enable analytics events to be sent, have not investigated further.

**Comment by SMed79** [comment]
`@@||rs-online.com/js_*/analytics.min.js$script,~third-party`

**Comment by chengsun** [comment]
Works fine for me.

**Comment by SMed79** [comment]
reported at easylist forum https://forums.lanik.us/viewtopic.php?f=64&t=37909
