### ISSUE TITLE
google.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6413]
### URL(s) where the issue occurs

`https://www.google.com/search?q=youtube&hl=en`

### Describe the issue

Dragging the video link to the browser tab bar is blocked.

### Screenshot(s)

![obraz](https://user-images.githubusercontent.com/35370833/66274227-97b01980-e87c-11e9-9429-0721111d7270.png) |
--- |

### Versions

- Browser/version: Firefox 69.0.2
- uBlock Origin version: 1.22.4

### Settings

- Default + Annoyance + PL

### Notes

blocked by JavaScript?

**Comment by mapx-** [comment]
- sure, by JS, you can try disabling JS for google and you'll get what you want

add (but maybe some functionalities will be broken)
`google.com##+js(aeld, , a.call(b.src,b.listener,c))`
