### ISSUE TITLE
Hellenic Bank personal banking. Top menu bar isn't shown.

### ISSUE THREAD

**Issue by nicexe** [uBlockOrigin/uAssets#6415]
### URL(s) where the issue occurs

`https://www.hellenicbank.com/portalserver/hb-en-portal/en/personal-banking`

### Describe the issue

This is the portal for hellenic bank's personal banking. The navigational bar on top is hidden which includes the login button and other links.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/867535/66329581-69434480-e937-11e9-8584-b94aa6d2174f.png)

![image](https://user-images.githubusercontent.com/867535/66329524-53ce1a80-e937-11e9-993f-7890c3231a3b.png)

### Versions

- Browser/version: 69.0.2 (64-bit)
- uBlock Origin version: v1.22.4

### Settings

- Enabled all Build-in filters except from the experimental one.
- Enabled all Ads filters
- Enabled all Privacy filters
- Enabled all Malware domains filters
- Enabled all Annoyances filters
- Enabled all Multipurpose filters
- Enabled GRC filter from the Regions, languages filters

### Notes

Changing the display property of this element at least makes the elements show up. No real text in the elements, just placeholders.
`body > div.pageContainer > div#main.bp-page.bp-portal-area > div.lp-page-children.bp-area.--area > div.bp-widget.bp-ui-dragRoot > div.bp-widget-body > div.widget-hb-header-and-megamenu`
Clicking on the login button does nothing.

**Comment by mapx-** [comment]
You should always test using the default settings / lists and report the issue accordingly (to the specific repositories)

Your issue is a fanboy's annoyances / cookie list

add 
@@||hellenicbank.com/portalserver/*/cookies-consent.js$script,1p

@ryanbr
