### ISSUE TITLE
[ad network] gelirartisi - app.gelirartisi.com

### ISSUE THREAD

**Issue by ahmedtds** [uBlockOrigin/uAssets#6418]
it's an ad network: http://www.gelirartisi.com/index.php?lang=eng

makes this request which slows pages a little:
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +0 |  |  | eksisozluk.com | 3 | script | `https://app.gelirartisi.com/withdfp.js?sid=6` |
</details>

not sure if this fits into adblocking or privacy filters but app.gelirartisi.com should be blocked

**Comment by llacb47** [comment]
Is it not in the Turkish regional list?

**Comment by ahmedtds** [comment]
I think it's not in any list

**Comment by mapx-** [comment]
Provide the steps to arrive to that domain. What's the issue ? popups ? redirecting ? only normal ads ?
Otherwise you should report it to turkish list or easylist repository

**Comment by okiehsch** [comment]
var GART_TIMEOUT_4383682 = 500;
var GART_DEBUG = 0;

function topScript4383682(code) {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.src = code; ga.async = true;
    window.top.document.head.appendChild(ga);
}

function image4383682(url) {
    var t = Boolean(navigator.appVersion.match(/msie/i)) ? new Image : document.createElement('img');
    t.width = 1; 
    t.height = 1; 
    t.style.display = 'none'; 
    t.src = url;
}

(function () {
    topScript4383682("//app.gelirartisi.com/gart.dfp.js?v=1.0");
    // topScript4383682("//app.gelirartisi.com/jquery.min.js?v=1.0");
})();

var adUnits_4383682 = [{"code":"/1024435/mobile_web_bottom","sizes":[["300","250"]],"mediaTypes":{"banner":{"sizes":[["300","250"]]}},"bids":[{"bidder":"theadx","params":{"pid":"1","wid":"74","tagId":"534"}},{"bidder":"rubicon","params":{"accountId":"11252","siteId":"222410","zoneId":"1096982","floor":"4.5"}},{"bidder":"adform","params":{"mid":"646793"}},{"bidder":"rtbhouse","params":{"publisherId":"hSzhCGhVLKqZkJAaoag6","region":"prebid-eu","bidfloor":"3.40"}}]}];
var zoneRatios_4383682 = {"criteo":"25","theadx":"50","rubicon":"40","adform":"35","rtbhouse":"25"};
var zoneRequestIDs_4383682 = {"/1024435/mobile_web_bottom":"60fdde80-e995-11e9-87c5-db1e60932117"};

window.top.gartdfp = window.top.gartdfp || {};
window.top.gartdfp.que = window.top.gartdfp.que || [];

function f_4383682(allBids) {
    if(GART_DEBUG) {
        console.log("GelirArtisi - All Bids", allBids);
    }
    
    if (window.top.gartdfp.initAdserverSet) return;

    /*
    for(var c in allBids) {
        if(allBids[c].bids.length > 1) {
            for(s = 0; s < allBids[c].bids.length; s++) {
                image4383682('//app.gelirartisi.com/bids?rid=' + zoneRequestIDs_4383682[allBids[c].bids[s].adUnitCode] + '&cpm=' + parseInt(allBids[c].bids[s].cpm * 1000) + '&isdfp=1&ratio=' + zoneRatios_4383682[allBids[c].bids[s].bidderCode] + '&bidder=' + allBids[c].bids[s].bidderCode + '');
            }
        }
        else {
            image4383682('//app.gelirartisi.com/bids?rid=' + zoneRequestIDs_4383682[allBids[c].bids[s].adUnitCode] + '&cpm=' + parseInt(allBids[c].bids[0].cpm * 1000) + '&isdfp=1&ratio=' + zoneRatios_4383682[allBids[c].bids[s].bidderCode] + '&bidder=' + allBids[c].bids[0].bidderCode + '');
        }
    }
    */

   window.top.gartdfp.que.push(function() {
        window.top.gartdfp.setTargetingForGPTAsync();
        // window.top.googletag.pubads().refresh();
    });

    window.top.gartdfp.initAdserverSet = true;
}

window.top.gartdfp.que.push(function () {
    window.top.gartdfp.addAdUnits(adUnits_4383682);
    window.top.gartdfp.setConfig({
        debug: GART_DEBUG,
        currency: {
            adServerCurrency: 'TRY',
            bidderCurrencyDefault: {
                criteo: 'TRY', rubicon: 'USD', theadx: 'TRY', adform: 'USD', rtbhouse: 'USD'
            },
        },
        priceGranularity: {
            buckets: [{
                precision: 2,
                min: 2.5,
                max: 27.25,
                increment: 0.25
            }]
        }
    });

    window.top.gartdfp.bidderSettings = {"criteo":{"bidCpmAdjustment":function(t) {return t * 0.75}},"theadx":{"bidCpmAdjustment":function(t) {return t * 0.5}},"rubicon":{"bidCpmAdjustment":function(t) {return t * 0.6}},"adform":{"bidCpmAdjustment":function(t) {return t * 0.65}},"rtbhouse":{"bidCpmAdjustment":function(t) {return t * 0.75}}};

    window.top.gartdfp.requestBids({
        adUnits: adUnits_4383682,
        bidsBackHandler: f_4383682,
        timeout: GART_TIMEOUT_4383682
    });

    window.top.gartdfp.onEvent('bidWon', function(data) {
        if(zoneRequestIDs_4383682[data.adUnitCode]) {
            image4383682('//app.gelirartisi.com/ixc?rid=' + zoneRequestIDs_4383682[data.adUnitCode] + '&isdfp=1&cpm=' + parseInt(data.cpm * 1000) + '&ratio=' + (100 - zoneRatios_4383682[data.bidderCode]) + '&bidder=' + data.bidderCode + '');
        }
        
        if(GART_DEBUG) {
            console.log("Bid Won", data);
        }
    });
});

setTimeout(function () {
    if(GART_DEBUG) {
        console.log("GelirArtisi - All Bids - Timeout");
    }
    // f_4383682();

**Comment by krystian3w** [comment]
AdGuard Turkish have only:

<pre><code>@@/js/adblockDetector<b>With</b>GA.js$domain=fox.com.tr
                     ^^^^
</code></pre>
