### ISSUE TITLE
uBlock filters: pornhub.com reCAPTCHA blocked

### ISSUE THREAD

**Issue by stanlane** [uBlockOrigin/uAssets#642]
### URL(s) where the issue occurs
https://www.pornhub.com/support

### Describe the issue
uBlock filters

> *$third-party,script,domain=gaytube.com|pornhub.com|redtube.com|redtube.it|tube8.com|tube8.es|tube8.fr|xtube.com|youjizz.com|youporn.com|youporngay.com

blocks https://www.google.com/recaptcha/api.js?onload=initCaptcha&render=explicit used to display the CAPTCHA at https://www.pornhub.com/support

It didn't help to whitelist google.com (this should be regarded **separate bug** I think).

> www.pornhub.com google.com * allow

### Screenshot(s)
![screenshot from 2017-08-23 01 02 17](https://user-images.githubusercontent.com/25944158/29591413-b96055d6-879e-11e7-9a3d-4c263534b27c.png)

### Versions

- Browser/version: Firefox ESR 52.3.0
- uBlock Origin version: 1.13.8

### Settings
All filters disabled except **uBlock filters**.

**Comment by stanlane** [comment]
Sorry, no AAK-Cont used, just the default settings. I did reset uBO.

**Comment by okiehsch** [comment]
> All filters disabled except uBlock filters.

With this setting you will have to allow `google.com` and `gstatic.com`.

The captcha is blocked if you use uBO with default settings on my end, so I will fix **this** issue.

**Comment by stanlane** [comment]
@okiehsch Thank you.

**Comment by stanlane** [comment]
@okiehsch You seem to be good at writing filters. Can you please have a look on https://github.com/uBlockOrigin/uAssets/issues/483 ?

**Comment by gotitbro** [comment]
@stanlane That is why he's a maintainer here ;). These filters work for PH on my side:
```
pornhub.com##body > .wrapper + div[class]:if(> .removeAdLink)
pornhub.com##.sectionWrapper > div[class*=" "]:if(> div[class]:only-child > a.removeAdLink)
pornhub.com##.sectionWrapper > div.sectionTitle+div[class*=" "]:not([class="sectionTitle"]):not([class="reset"]):not([class="gifsWrapper "])
```

They are from the Adguard English filter.

**Comment by stanlane** [comment]
@gotitbro Can you please merge that comment to https://github.com/uBlockOrigin/uAssets/issues/483 so we can continue the discussion there?

**Comment by stanlane** [comment]
@gotitbro The filters didn't work but please do not respond in this issue.

**Comment by stanlane** [comment]
https://github.com/easylist/easylist/issues/454

**Comment by stanlane** [comment]
@gotitbro Should your filters be applied too?

**Comment by stanlane** [comment]
@okiehsch Should @gotitbro [filters](https://github.com/uBlockOrigin/uAssets/issues/642#issuecomment-324449254) be applied too?

**Comment by mapx-** [comment]
@stanlane  do you still have issues ?

**Comment by stanlane** [comment]
@mapx- No.
