### ISSUE TITLE
portalportuario.cl

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#6421]
### URL(s) where the issue occurs

`https://portalportuario.cl/sube-tension-entre-representaciones-de-chile-y-bolivia-por-alza-tarifaria-en-el-puerto-de-arica/`

### Describe the issue

Clipboard manipulation.

### Versions

- Browser/version: Firefox stable
- uBlock Origin version: 1.22.4

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin lists

**Comment by mapx-** [comment]
ads

```
||portalportuario.cl/*.gif$image
||portalportuario.cl/*banner$image
portalportuario.cl##.banner
portalportuario.cl###secondary
```
