### ISSUE TITLE
pornhub.com

### ISSUE THREAD

**Issue by SebaK666** [uBlockOrigin/uAssets#6422]
Title: uBlock filters

For a week, maybe a little longer on  Pornhub.com filter now hide all thumbnails videos
![pornhub](https://user-images.githubusercontent.com/33153803/66437806-0df27e80-ea2b-11e9-9daf-ff229c1d033b.jpg)

**Comment by okiehsch** [comment]
Works fine on my end with a default setup. 
Default setup meaning these filter lists are enabled.
![image](https://user-images.githubusercontent.com/16838044/66438880-421b6e80-ea2e-11e9-9b7f-ee2311b1da0c.png)

**Comment by krystian3w** [comment]
Maybe needed `Serpent (Basilisk)` + Windows XP + old uBO 1.17.X (last works with Firefox ~51 - 55).

**Comment by dumbusernameidk** [comment]
Check logger for anything blocking the thumbnails (maybe your own filters?)

**Comment by SebaK666** [comment]
No, because unchecking only this filter causes thumbnail visibility:

![pornhub2](https://user-images.githubusercontent.com/33153803/66441132-e05f0280-ea35-11e9-8830-724c9ee9abeb.jpg)

**Comment by SebaK666** [comment]
Probably one of these filters:
![pornhub3](https://user-images.githubusercontent.com/33153803/66441392-f6b98e00-ea36-11e9-9b32-4f7376a70800.jpg)

**Comment by okiehsch** [comment]
> unchecking only this filter causes thumbnail visibility

I can see all thumbnails and I have that list enabled as you can see in my screenshot.

**Comment by okiehsch** [comment]
> Probably one of these filters:

Um, some of the filters in your screenshot have been removed months ago.

**Comment by SebaK666** [comment]
Probably UBO 1.17.4 is to blame - - last available for my browser. But it worked fine two weeks ago.

**Comment by okiehsch** [comment]
What browser are you using?
For example the `pornhub-popup-defuser` filter in your screenshot was removed on the [4th of July](https://github.com/uBlockOrigin/uAssets/commit/ee7c9938d35aeebfa11131eb383693d640e90f66#diff-8809d5783978a0b5b88f93d7dab99de0)

**Comment by okiehsch** [comment]
The csp filter could cause the breakage, you can try to disable the csp filter add
`@@||pornhub.com^$csp`
to your filter list.

**Comment by SebaK666** [comment]
Serpent - based on Firefox, because Firefox is not now updated for my system XP

**Comment by okiehsch** [comment]
Can you give me the complete path of the `csp` filter in your screenshot?

**Comment by SebaK666** [comment]
Add for my filters @@||pornhub.com^$csp not change anything
This screen filter for you
![pornhub4](https://user-images.githubusercontent.com/33153803/66442147-d9d28a00-ea39-11e9-9b03-64a843d57cf7.jpg)

**Comment by okiehsch** [comment]
> `@@||pornhub.com^$csp`

That won't work which is why I deleted my comment
change the `##` part in the filter to `#@#`.

**Comment by okiehsch** [comment]
If that does not work change the `##` part to `#@#` for all of the filter you highlighted
![pornhub3](https://user-images.githubusercontent.com/33153803/66441392-f6b98e00-ea36-11e9-9b32-4f7376a70800.jpg)

**Comment by SebaK666** [comment]
But how can I edit the filter manually? Editing is blocked

**Comment by okiehsch** [comment]
> You must remember that some use older versions of UBO and the filter must be compatible

There is nothing we can do those filters are not part of the up to date lists. 
Looking at the numbers of filters for `EasyPrivacy` in your screenshot looks to me like all your filter lists are out of date.

**Comment by SebaK666** [comment]
Regularly filters updates, also click on Purge all catches. So I don't know how outdated filters may still be

**Comment by okiehsch** [comment]
Well I believe you that it shows that the filters are up to date but like I mentioned some of the highlighted filters have been removed months ago, so for whatever reason you don't actually get up to date filters.

**Comment by SebaK666** [comment]
Is it possible to edit the path to the original built-in filters? Probably not. Updated paths need to be added as custom?

You're right, the filter is old. I thought the built-in filter path was correct. I will have to look for the current and manually add
![filtr](https://user-images.githubusercontent.com/33153803/66443190-60896600-ea3e-11e9-9212-4349b3456437.jpg)

**Comment by okiehsch** [comment]
> I will have to look for the current and manually add

Yes.

**Comment by krystian3w** [comment]
Try use uBO legacy 1.16 maybe... https://github.com/gorhill/uBlock/releases/tag/firefox-legacy-1.16.4.11

Maybe can download lastest lists files.

**Comment by krystian3w** [comment]
If no, so maybe @roytam1 broke in firefox fork.

**Comment by SebaK666** [comment]
I can't filters update, I have to try 1.16
 krystian3w - on githib private message is it possible?
