### ISSUE TITLE
Soundcloud audio ads coming through

### ISSUE THREAD

**Issue by issue-report** [uBlockOrigin/uAssets#6423]
### URL(s) where the issue occurs

Anywhere on `soundcloud.com`; for example `https://soundcloud.com/jaegerofficial/vertigo`.

### Describe the issue

Occasionally audio ads will come through; just started today; haven't had this happen once this year until today.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/8127593/66525510-b48a5e00-eac3-11e9-85f7-4c90a8f3cb26.png)
![image](https://user-images.githubusercontent.com/56370905/66526630-6e36fe00-eac7-11e9-8e4c-fab079f6b018.png)

### Versions

- Google Chrome Version 77.0.3865.90 (Official Build) (32-bit)
- uBlock Origin v1.22.4

### Settings

- All default

### Notes

Looks like a request to `/audio-ads` is making it out.  It returned links to `https://cont-1.p-cdn.us/public/full-128kbps-mp3/r/a/a/d/w/y/w/a/daarv21288794idawyw-1-1-full-128kbps.mp3` (audio ad), `https://cont-1.p-cdn.us/images/public/devicead/w/y/w/a/daarv21288794idawyw_500W_500H.jpg` (picture ad), and some other stuff.

**Comment by okiehsch** [comment]
I can reproduce audi ads but they appear to have a different path on my end. 
Maybe geo-dependent.
`||sndcdn.com/audio/*$media,redirect=noopmp3-0.1s,domain=soundcloud.com`
blocks the audio ads on my end.

**Comment by llacb47** [comment]
I haven't gotten any ads yet (and can't reproduce), but you should add
```
||api-v2.soundcloud.com/audio-ad
||api-v2.soundcloud.com/promoted
```

(I've had these in my filters for months and never gotten ads)

**Comment by okiehsch** [comment]
````
||soundcloud.com/audio-ad$1p,?
||soundcloud.com/promoted$1p,?
````
I can add those but I like to be more specific, what type of request do you get on your end, script, media, etc?

**Comment by llacb47** [comment]
xhr
