### ISSUE TITLE
cashlinks.co

### ISSUE THREAD

**Issue by simoconfa** [uBlockOrigin/uAssets#6427]
### URL(s) where the issue occurs

`http://cashlinks.co/Qjwu`

### Describe the issue

Adblock detected

### Screenshot(s)

![immagine](https://user-images.githubusercontent.com/8224154/66701519-36190080-ecfd-11e9-983c-870936efc8c8.png)

### Versions

- Browser/version: FF latest
- uBlock Origin version: 1.22.4 (latest)

### Settings

- None

### Notes

The problem is inside this script: `http://cashlinks.co/cloud_theme/build/js/script.min.js?ver=6.3.0`
This script contains :
```
function checkAdblockUser(){
if("1"!==getCookie("ab")){
document.cookie="ab=2; path=/";var t=$("#ad-banner");if((0===t.filter(":visible").length||t.filter(":hidden").length>0||0===t.height())&&(document.cookie="ab=1; path=/","1"===app_vars.force_disable_adblock)){
var e='<div class="alert alert-danger" style="display: inline-block;">'+app_vars.please_disable_adblock+"</div>";$("#link-view").replaceWith(e),$(".banner-page a.get-link").replaceWith(e),$(".interstitial-page div.skip-ad").replaceWith(e)
}}}
```

**Comment by simoconfa** [comment]
@mapx- Adblock is still detected in my case, captcha is hidden. 
I use the default config with easylist_ITA

**Comment by mapx-** [comment]
Do you see my filters in the logger ?
Any other blocking addon enabled in your FF ?

**Comment by mapx-** [comment]
More, are you using the default settings ?

**Comment by uBlock-user** [comment]
> @mapx- Adblock is still detected in my case, captcha is hidden.
I use the default config with easylist_ITA

You need to update uBlock Filters for it to work.

**Comment by simoconfa** [comment]
> 
> 
> More, are you using the default settings ?
> 
> > I use the default config with easylist_ITA
> 
> well, in this case: close / reopen FF, reset uBo, click "purge all caches", click "update now"

Now works. I have tried that 10 minutes later after issue closure. I have also new installed ublock origin into chrome (which I don't use) for testing but it did not work. Now works, that is the only thing that matters.
Sorry for the inconvenience.
