### ISSUE TITLE
eleventhlevelinteractive.com

### ISSUE THREAD

**Issue by WaferNabati** [uBlockOrigin/uAssets#6428]
URL(s) where the issue occurs
`https://www.eleventhlevelinteractive.com/2019/10/is-affiliate-in-demand.html#?o=d5bd1e687547838d25276d55028b65018969aba267b56906b7a58dd2114026b52d590c4a00e5e580258cb017f4307db3ba68af49cd1035cc5f2314bf4588834d53056dfb77363a3d`

Describe the issue
blocking get link (Anti adblock)

Versions
uBlock Origin version 1.22.4

Browser/version
Chrome 77.0.3865.90 (Official Build) (64-bit)

Settings
Ublock Origin default settings+nano defender

**Comment by mapx-** [comment]
I cannot reproduce your issue, clicking twice the "get link" then landing on zippyshare page, no anti adb message, no other blocking

**Comment by uBlock-user** [comment]
Can't reproduce.

```
@@||eleventhlevelinteractive.com^$generichide
eleventhlevelinteractive.com##.adsbygoogle
```

That should fix it for you.

**Comment by WaferNabati** [comment]
I'm sorry, I think it's because of the Indonesian filter region problem

**Comment by mapx-** [comment]
yeah, you need:
`@@/safelink$script,domain=eleventhlevelinteractive.com`

**Comment by WaferNabati** [comment]
ok thanks.
