### ISSUE TITLE
bluemediafiles.com

### ISSUE THREAD

**Issue by bug-rules** [uBlockOrigin/uAssets#6432]
### URL(s) where the issue occurs

`http://bluemediafiles.com/creatinglinkspVVJ52BobqWRSUq8QydNlxYtPL1syhnl2VLm2FE0h4JMfQa8LP5RIPio92gInvzG57ExsOZK0tvq7oaMk36alzo7dBLnUdmoM3D?xurl=s://tusfiles.com/rpw0uajr1l75`

https://github.com/NanoMeow/QuickReports/issues/2034

### Describe the issue

Event click on `<html>` element with fake site: `boriouseruwer.info`?

### Screenshot(s)

> ![obraz](https://user-images.githubusercontent.com/43518394/66719158-40fe8e80-edec-11e9-968e-a6da15a5504b.png) |
> --- |
> 

### Versions

- Browser/version: Firefox 69.0.3
- uBlock Origin version: 1.22.4

### Settings

- default

### Notes

Good workaround (kill timer and minmalize risk open fake site `boriouseruwer.info`): https://github.com/Creepler13/Skip-Bluemediafiles.com/blob/master/Programm.js

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/09966d308d3d701801039ad91d9506974dc31311
