### ISSUE TITLE
YouTube Shopping Suggestions (Sponsored)

### ISSUE THREAD

**Issue by PolarisBeaver** [uBlockOrigin/uAssets#644]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.youtube.com/watch?v=UTYphVO-bFg`

### Describe the issue

Sponsored shopping results are displayed below certain videos based on identified products (can you believe this?!)

### Screenshot(s)

![2017-08-22 20_50_32-this fake gameboy color is better than original - youtube](https://user-images.githubusercontent.com/10394552/29598096-a25c8bd4-877b-11e7-9e7f-8da874c1ad80.png)

### Versions

- Browser/version: Google Chrome 60.0.3112.101 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin 1.13.8

### Settings

![2017-08-22 20_52_37-ublock dashboard](https://user-images.githubusercontent.com/10394552/29598151-ee29cbbc-877b-11e7-9e11-9fa09117decb.png)

### Notes

None.

**Comment by PolarisBeaver** [comment]
Also I don't know if this helps, but it seems to be identified as `###promotion-shelf`

![2017-08-22 21_00_15-twitter](https://user-images.githubusercontent.com/10394552/29598314-0034d044-877d-11e7-9db5-e3e68263d711.png)

**Comment by gorhill** [comment]
I can't reproduce on my side. However I do see a `<div id="promotion-shelf" class="promotion-shelf-slot yt-card yt-card-has-padding hid"></div>` element (empty) in the DOM. I will assume it's filled with ads in for some people. Given the name of the `div`, seems safe to assume it's for ads, so I will add the filter even if I can't reproduce.
