### ISSUE TITLE
videobin.co [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#6440]
URL(s) where the issue occurs

`https://videobin.co/fx3whfu1ki46/zdfghdfsxhfgth_23.avi`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 76 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.22.4

Settings

Default

**Comment by ghajini** [comment]
`https://videobin.co/bt7mj4erx78u`

Crap xhr's requests
`||videobin.co/sw.js$script,1p`

**Comment by ghajini** [comment]
Popup ads

`videobin.co/ls44fmnoaqx7`

Update 

`videobin.co#@#+js(acis, Math, zfgloaded)`
`videobin.co##+js(acis, String.fromCharCode, btoa)`
`videobin.co##+js(aopw, Fingerprint2)`

**Comment by okiehsch** [comment]
`videobin.co##+js(aopw, Fingerprint2)` is good enogh no?

**Comment by ghajini** [comment]
Yes

**Comment by seedoils** [comment]
<details> <summary> Screenshot: </summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/133573395/0d67173a-fe15-4117-8263-05329d2c5c50)

</details>
