### ISSUE TITLE
uBlockOrigin blocks site ? xtool.ru

### ISSUE THREAD

**Issue by trustr** [uBlockOrigin/uAssets#6443]
uBlockOrigin blocks the loading of pages of the site analysis service `https://xtool.ru` is possible to solve the problem on your part or hang a message for users to delete uBlockOrigin?

**Comment by mapx-** [comment]
You didn't provide any requested info: browser (version), uBo version, filter lists. Other blocking extensions ?

**Comment by uBlock-user** [comment]
Site is not blocked, you must have blocked it yourself or installed a filterlist that blocking it. Try on default settings

**Comment by trustr** [comment]
введите урл в форму и нажмите кнопку, ваше расширение в итоге меняет урл на некорректный13:27, 16 октября 2019 г., Saitama <notifications@github.com>:Site is not blocked, you must have blocked it yourself or installed a filterlist that blocking it. Try on default settings

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by mapx-** [comment]
@dimisa-RUAdList could you help here ?

**Comment by dimisa-RUAdList** [comment]
@trustr 
Опишите пожалуйста проблему на форуме RU AdList: https://forums.lanik.us/viewforum.php?f=102

Как это правильно сделать, описано здесь: https://forums.lanik.us/viewtopic.php?f=102&t=24280

**Comment by trustr** [comment]
uBlock Origin 1.22.4  firefox 69.0.3
To see the problem you need to enter any url in the form on the main page https://xtool.ru and press the button.
Screen without uBlock Origin:
https://prnt.sc/pk5878
Screen with uBlock Origin:
https://prnt.sc/pk5byd

**Comment by dimisa-RUAdList** [comment]
Welcome: https://forums.lanik.us/viewforum.php?f=102

**Comment by trustr** [comment]
I do not want to register anywhere else, I have already described everything here

**Comment by dimisa-RUAdList** [comment]
Disable filters one at a time until a problematic one is detected. After that, leave only the problematic filter on and do the following: https://forums.lanik.us/viewtopic.php?f=102&t=23908

**Comment by trustr** [comment]
Problematic -  EasyPrivacy
https://prnt.sc/pk5ux6

**Comment by trustr** [comment]
https://prnt.sc/pk5xiy

**Comment by mapx-** [comment]
@ryanbr
