### ISSUE TITLE
nfmovies.com anti-adblock

### ISSUE THREAD

**Issue by discusssth** [uBlockOrigin/uAssets#6444]
`https://www.nfmovies.com/`

![image](https://user-images.githubusercontent.com/45059308/66969387-e4d18e00-f0bb-11e9-8400-521a82a95349.png)

**Comment by coinvpn** [comment]
> `https://www.nfmovies.com/`
> 
> ![image](https://user-images.githubusercontent.com/45059308/66969387-e4d18e00-f0bb-11e9-8400-521a82a95349.png)

they update their code for defending.
tried this one.
```
www.nfmovies.com##+js(abort-current-inline-script, decodeURIComponent, atob)
```

**Comment by mapx-** [comment]
It's about popups / anti adb ? Translate that message for us

**Comment by coinvpn** [comment]
It's anti adb.
The message is that for this website can survive, please add this site to the while list of adb. I, webmaster, thank you.
they use the encrypted js code to do anti adb function.
And, you can translate the sentence with google translate. 
"为了本网站能够生存, 请您将本站点加入广告拦截软体的白名单, 站长在此感谢您!"

**Comment by mapx-** [comment]
Tested this video
`https://www.nfmovies.com/video/?39996-0-0.html`

no warning  / alert window for me

**Comment by mapx-** [comment]
both chinese lists enabled

**Comment by discusssth** [comment]
@coinvpn 
This problem has been fixed five days ago.
Subscribe to these rules to resolve the issue.
![image](https://user-images.githubusercontent.com/45059308/67255018-956fd100-f4b2-11e9-8256-03489981ce0e.png)
