### ISSUE TITLE
(nfsw) fullxxxmovies.net popups

### ISSUE THREAD

**Issue by swathigrate** [uBlockOrigin/uAssets#6446]
### URL(s) where the issue occurs

`http://fullxxxmovies.net/`

### Describe the issue

ads are opening when click any thing and search  anything ...

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]
![c](https://user-images.githubusercontent.com/14991260/66989859-c6cb5400-f0e2-11e9-8641-d7f5baba0173.jpg)

### Versions

- Browser/version: 68
- uBlock Origin version: 1.22.4

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
test on your side if there is any breakage

**Comment by swathigrate** [comment]
thanks @mapx-  working fine
