### ISSUE TITLE
bs.to back at it again

### ISSUE THREAD

**Issue by xmaestro21** [uBlockOrigin/uAssets#6447]
So since i reported this site multiple times already, but they fight back every once in a while, i will just copy paste my last report, with updated information. I hope its Ok:

### URL(s) where the issue occurs

bs.to
burningseries.co
(same site but different URL because bs.to is blocked for many people by their provider)

### Describe the issue

There is an Overlay on the whole site which opens a popup when you click. It is also timer-based so it happens again after a while. Also i'm not sure but i think they use different ads on different browsers.

### Versions

    Browser/version: Firefox 69.0.3 (64-Bit)
    uBlock Origin version: 1.22.4

### Settings

    Advanced User, a few additional Filter Lists

### Notes

I would like to ask if you can add it in your Filter lists, so everyone can benefit from it.
Thank you.

**Comment by mapx-** [comment]
alternative
`bs.to,burningseries.co##+js(acis, parseInt)`
