### ISSUE TITLE
Doesn't Block Ads On Kupujem Prodajem Website

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uAssets#6450]
uBlock Origin doesn't block ads on Kupujem Prodajem website
 `https://www.kupujemprodajem.com/index.php`

![5345345](https://user-images.githubusercontent.com/18757054/67120745-3415dc80-f1ea-11e9-9a06-7867a7a1fd97.jpg)
![34534253](https://user-images.githubusercontent.com/18757054/67120746-3415dc80-f1ea-11e9-87c7-0ee4ef9f94f5.jpg)

**Comment by mapx-** [comment]
Bosnian language ? I see no such list for the sites in Bosnia, in this case should be easylist taking care of them.

see if helps:
```
||contributor.google.com^$domain=kupujemprodajem.com
||fundingchoicesmessages.google.com^$domain=kupujemprodajem.com
kupujemprodajem.com##.bnrBox
```

and let's see what will say an easylist author: @ryanbr

**Comment by GKid94** [comment]
@mapx- It's Serbian language

**Comment by GKid94** [comment]
@mapx- It keeps showing the anti adblock popup

![5435345](https://user-images.githubusercontent.com/18757054/67124886-cb336200-f1f3-11e9-9c64-0e6abdbfa97f.jpg)

**Comment by mapx-** [comment]
dos this help ? (I cannot reproduce the issue)
`kupujemprodajem.com##+js(set-constant.js, canRunAds, true)`

**Comment by llacb47** [comment]
add `kupujemprodajem.com##+js(acis, atob, googlefc)` to uBlock filters, there is already alot of domains where this scriptlet is used https://github.com/uBlockOrigin/uAssets/commit/9bf3411b2c634fdea822f6f948541945d8871343 so just add the domain

**Comment by GKid94** [comment]
@mapx- How do I add those filters

**Comment by mapx-** [comment]
click uBo icon, open the dashboard (last icon on the right under the big blue button), "my filters" tab, add the filters above, click "apply changes", test again.

**Comment by GKid94** [comment]
@mapx- It still keeps showing the anti adblock popup https://www.kupujemprodajem.com/Kompjuteri-Desktop/Kablovi-i-adapteri/Adapter-DVI-24-5-M-na-VGA-15-F-NEWMB-N-DVD-VGA-72279816-oglas.htm?filter_id=289743655

**Comment by GKid94** [comment]
https://www.kupujemprodajem.com/Mobilni-tel-Oprema-i-delovi/Punjaci-i-autopunjaci/Power-Bank-Samsung-30000mAh-Novo--41330212-oglas.htm?filter_id=490175916

**Comment by mapx-** [comment]
still cannot reproducing anti adb msg or ads

**Comment by GKid94** [comment]
@mapx- Just block the ads and refresh the pages a couple of times

**Comment by mapx-** [comment]
Do you see my filters in the logger ?

**Comment by GKid94** [comment]
@mapx- Logger?

**Comment by mapx-** [comment]
read wiki, it's all there:
https://github.com/gorhill/uBlock/wiki

**Comment by GKid94** [comment]
Here

![53453453](https://user-images.githubusercontent.com/18757054/67129036-d1c6d700-f1fd-11e9-8a0b-ee08f9213501.jpg)

23:20:30​​​www.kupujemprodajem.com​3​script​https://www.gstatic.com/0emn/f/p/14d7a3a2caf9f64f.js?usqp=CA0
23:20:30​​​www.kupujemprodajem.com​3​script​https://www.gstatic.com/0emn/f/p/14d7a3a2caf9f64f.js?usqp=CA0
23:20:30​.div-gpt-ad​​www.kupujemprodajem.com​​dom​https://www.kupujemprodajem.com/Kompjuteri-Desktop/Kablovi-i-adapteri/Adapter-DVI-24-5-M-na-VGA-15-F-NEWMB-N-DVD-VGA-72279816-oglas.htm?filter_id=289743655
23:20:30​||fundingchoicesmessages.google.com^$third-party​--​www.kupujemprodajem.com​3​xhr​https://fundingchoicesmessages.google.com/l/AGSKWxW6jGSkcdXIRxMIYdu2DL7-kIAsiprbSIIOgb5dwZwU0-kPXiL-h0_YRT7IKnIkaLVtDO-z3OpsAQrWitN7?ab=1&sbf=1
23:20:30​​​www.kupujemprodajem.com​3​script​https://www.gstatic.com/0emn/f/p/14d7a3a2caf9f64f.js?usqp=CA0
23:20:30​​​www.kupujemprodajem.com​1​image​https://www.kupujemprodajem.com/favicon.ico
23:20:30​​​www.kupujemprodajem.com​1​other​https://www.kupujemprodajem.com/manifest.json
23:20:30​div[id^="div-gpt-ad"]​​www.kupujemprodajem.com​​dom​https://www.kupujemprodajem.com/Kompjuteri-Desktop/Kablovi-i-adapteri/Adapter-DVI-24-5-M-na-VGA-15-F-NEWMB-N-DVD-VGA-72279816-oglas.htm?filter_id=289743655
23:20:30​.bnrBox​​www.kupujemprodajem.com​​dom​https://www.kupujemprodajem.com/Kompjuteri-Desktop/Kablovi-i-adapteri/Adapter-DVI-24-5-M-na-VGA-15-F-NEWMB-N-DVD-VGA-72279816-oglas.htm?filter_id=289743655
23:20:29​​​www.kupujemprodajem.com​1​image​https://www.kupujemprodajem.com/bShowTrack.php?t=%5B%7B%22banner_id%22%3A94495%2C%22info2%22%3A%22wGC9WRtSheXwPRjL5eS/pmDFYVI5/DWSPmBCliB1F+95r8mLa6XZ5cJDn9l9y8RBM6zudhd7jgkRDb4FhVtvV9lRBylSzbF9j8D0HltkSxo%3D%22%7D%2C%7B%22banner_id%22%3A94482%2C%22info2%22%3A%22wGC9WRtSheXwPRjL5eS/pmDFYVI5/DWSPmBCliB1F+95r8mLa6XZ5cJDn9l9y8RBM6zudhd7jgkRDb4FhVtvV9lRBylSzbF9j8D0HltkSxo%3D%22%7D%2C%7B%22banner_id%22%3A94512%2C%22info2%22%3A%22wGC9WRtSheXwPRjL5eS/pmDFYVI5/DWSPmBCliB1F+/+XhjoHagD6h9hejV3rkmzocnxxaujS0TwKWVs1Gr2mP/7BKf/fcGzIcUbxrMDiVrOs4up03xqScKxO2UeEKGOE5b4HEnsgDU3s7lJnlqi0n+7+/zjrhwLcMY9ZQLlQm66UG/5tXiu3RBazyGg7L1LRGpIMeYHO+HdHFKkyJqLodVYR1YV5DJkV4AYBv+P84WbHkJ1cI4F3Znyv97SmXpZ%22%7D%2C%7B%22banner_id%22%3A94518%2C%22info2%22%3A%22wGC9WRtSheXwPRjL5eS/pmDFYVI5/DWSPmBCliB1F+95r8mLa6XZ5cJDn9l9y8RBM6zudhd7jgkRDb4FhVtvV9lRBylSzbF9j8D0HltkSxo%3D%22%7D%2C%7B%22banner_id%22%3A94381%2C%22info2%22%3A%22wGC9WRtSheXwPRjL5eS/pmDFYVI5/DWSPmBCliB1F+95r8mLa6XZ5cJDn9l9y8RBM6zudhd7jgkRDb4FhVtvV9lRBylSzbF9j8D0HltkSxo%3D%22%7D%5D&ts=1571433629626
23:20:29​||fundingchoicesmessages.google.com^$third-party​--​www.kupujemprodajem.com​3​script​https://fundingchoicesmessages.google.com/f/AGSKWxU0WC3C3g-z8crwmqhPSGLYETZbBx9QeF5C-Y5qu4oIfiypIp3tLlCVSncYNZmvGZfGOiqXwmDFuHWNnaCU
23:20:29​​​www.kupujemprodajem.com​3​frame​https://staticxx.facebook.com/connect/xd_arbiter.php?version=44#channel=f7f1dfbbe895a&origin=https%3A%2F%2Fwww.kupujemprodajem.com
23:20:29​||fundingchoicesmessages.google.com^$third-party​--​www.kupujemprodajem.com​3​script​https://fundingchoicesmessages.google.com/f/AGSKWxU0WC3C3g-z8crwmqhPSGLYETZbBx9QeF5C-Y5qu4oIfiypIp3tLlCVSncYNZmvGZfGOiqXwmDFuHWNnaCU
23:20:29​​​www.kupujemprodajem.com​3​script​https://connect.facebook.net/en_US/sdk.js?hash=86f970fd2cc73c01bbcbfb866a4062dd&ua=modern_es6
23:20:29​||googlesyndication.com^​--​www.kupujemprodajem.com​3​script​https://pagead2.googlesyndication.com/pagead/show_ads.js
23:20:29​||fundingchoicesmessages.google.com^$third-party​--​www.kupujemprodajem.com​3​script​https://fundingchoicesmessages.google.com/f/AGSKWxU0WC3C3g-z8crwmqhPSGLYETZbBx9QeF5C-Y5qu4oIfiypIp3tLlCVSncYNZmvGZfGOiqXwmDFuHWNnaCU
23:20:29​​​www.kupujemprodajem.com​3​script​https://connect.facebook.net/en_US/sdk.js
23:20:29​/fbevents.js​--​www.kupujemprodajem.com​3​script​https://connect.facebook.net/en_US/fbevents.js
23:20:29​google-analytics.com/analytics.js​<<​www.kupujemprodajem.com​​script​https://www.google-analytics.com/analytics.js
23:20:29​||google-analytics.com^​--​www.kupujemprodajem.com​3​script​https://www.google-analytics.com/analytics.js
23:20:29​||gemius.pl^$third-party​--​www.kupujemprodajem.com​3​script​https://gars.hit.gemius.pl/xgemius.js
23:20:29​||gemius.pl^$third-party​--​www.kupujemprodajem.com​3​image​https://rs.hit.gemius.pl/_1571433628933/redot.gif?id=zIE1LPCIeXk7HvqlxkY2pdWZj_fNuMOY26Dwe9DXum3.F7&nc=1&extra=_unique%3D63501571433628933%7C_order%3D2
23:20:29​||adocean.pl^​--​www.kupujemprodajem.com​3​image​https://alt.adocean.pl/_1571433628933/redot.gif?id=bIs7KxC.1NzBu9kaZtBN96dD78egbILawD_2Jp.yur..n7&nc=1&extra=_unique%3D63501571433628933%7C_order%3D1
23:20:29​||hudb.pl^$third-party​--​www.kupujemprodajem.com​3​image​https://alt.hudb.pl/_1571433628933/repoint.gif?id=bIuV7xC.iTDBu7AfZtB5lKdD7zGgbILm9neWobNP_lH.s7&nc=1&extra=_unique%3D63501571433628933%7C_order%3D0
23:20:29​||fundingchoicesmessages.google.com^$third-party​--​www.kupujemprodajem.com​3​script​https://fundingchoicesmessages.google.com/f/AGSKWxU0WC3C3g-z8crwmqhPSGLYETZbBx9QeF5C-Y5qu4oIfiypIp3tLlCVSncYNZmvGZfGOiqXwmDFuHWNnaCU
23:20:29​​​www.kupujemprodajem.com​1​image​https://www.kupujemprodajem.com/photos/banner/2/51/94512/94512_5d8c7503df0c91-32271093Baneri-za-SoGe-Krediti-projekat-160x300-24OKT-v-02.jpg
23:20:29​​​www.kupujemprodajem.com​1​image​https://www.kupujemprodajem.com/phone_72279816_MVPEV3.png
23:20:28​||googlesyndication.com^​--​www.kupujemprodajem.com​3​script​https://pagead2.googlesyndication.com/pagead/show_ads.js
23:20:28​​​www.kupujemprodajem.com​1​css​https://www.kupujemprodajem.com/css/oglas-view.css,oglas-ocene.css,banner.css,photo-gallery-2.css,dummy564.css?v=564
23:20:28​||contributor.google.com^$domain=kupujemprodajem.com​--​www.kupujemprodajem.com​3​xhr​https://contributor.google.com/scripts/14d7a3a2caf9f64f:D:7779d0491104a56a/checksub

**Comment by mapx-** [comment]
well, the filters are enabled but you still have the anti adb warning, right ?

**Comment by GKid94** [comment]
Yes

**Comment by okiehsch** [comment]
What browser are you using?

**Comment by GKid94** [comment]
@okiehsch Chrome 77.0.3865.120 (Official Build) (64-bit)

**Comment by okiehsch** [comment]
See the edit in my post above, updating the `uBO-filters` list should fix the issue for you

**Comment by GKid94** [comment]
@okiehsch Ok thx
