### ISSUE TITLE
DI.FM AdBlocker detected

### ISSUE THREAD

**Issue by Hakun1n** [uBlockOrigin/uAssets#6454]
### URL(s) where the issue occurs
`https://www.di.fm`

### Describe the issue
2 weeks ago I've reported #6399 and the fix was easy (UBO config reset). Sadly the problem is back and this time nothing helps. Stream stops after ~10mins and i get redirected to `https://www.di.fm/about-blockers` . This is on Windows 7 workstation. (I can't confirm if the same is happening on my linux machine at this point. I can do that latter this week)

What I've tried:
- "Forget about page" to flush cookies/cache/HSTS of the page
- UBO reset to default + purge/Update all default filter lists (no extra lists enabled)
- Browser restart
- Try again -> same result :/

As you can see in attached logs it detects adblock:
_[13:42:32.800] WebplayerApp.Ads.Supervisor: Adblocker detected, redirecting to adblock wall application-7e36dd64911ae968a002687f4c886dc5.js:30:141299_

Note that you have to be logged-in as **"free user"**, not an "anonymous listener" (anon does not have adds but ends after few mins asking for registration.

### Screenshot(s)
![difmscr](https://user-images.githubusercontent.com/12685294/67146552-b26e8f00-f27b-11e9-8545-d180abd381b2.png)

### Versions
- Browser/version:  69.0.3
- uBlock Origin version: 1.22.4

### Settings
No changes at all, neither additional filters or rules.

### Notes
Attaching FF console and network exports +uBlock log.
[difm_ubo.zip](https://github.com/uBlockOrigin/uAssets/files/3746763/difm_ubo.zip)

Let me know if you want me to provide more info or test/try something. Thank you !

**Comment by mapx-** [comment]
after listening to the radio for 12 minutes still no problem for me

**Comment by Hakun1n** [comment]
Could it be country specific? Or maybe account-specific? Can i somehow collect more detailed logs? I understand that it is hard to do anything with it if you can not reproduce the issue :/

**Comment by lain566** [comment]
@Hakun1n Do these filters work for you?
```
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,redirect=nooptext,domain=di.fm
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=di.fm,badfilter
```

**Comment by Hakun1n** [comment]
@lain566 Hi! I just tested and seems like the filters did the trick.

- First I've checked that the anti-adblock still gets triggered. Yes and I got redirected in 4 mins.
![difmscr2](https://user-images.githubusercontent.com/12685294/67167737-c1913200-f38c-11e9-9a91-148edc37c89f.png)

- Ten I've added your filters, saved and reloaded the page. Now the console shows three attempts for ads and all of them failed. Stream was not interrupted.
![difmscr3](https://user-images.githubusercontent.com/12685294/67167750-e84f6880-f38c-11e9-8a58-c28ec3606618.png)

- 4 mins later the same situation, again all prevented.
![difmscr4](https://user-images.githubusercontent.com/12685294/67167776-087f2780-f38d-11e9-9efa-8bcde848620c.png)

- 7 mins later another attempt and again OK!

So seems like it works but please give me few days to verify.

Thanks a lot!!

**Comment by mapx-** [comment]
feedback ?

**Comment by Hakun1n** [comment]
Yop, filters from @lain566 still working flawlessly.
