### ISSUE TITLE
Disable YouTube autoplay

### ISSUE THREAD

**Issue by cup** [uBlockOrigin/uAssets#6455]
TLDR: Can uBlock Origin disable YouTube autoplay? If so, how?

I am sick and tired of the YouTube "recommended for you". I dont want a
personalized experience. I dont sign in. I pause and clear my watch history
and search history from here:

https://www.youtube.com/feed/history

but still, YouTube just goes ahead and ignores all of that, and puts
"recommended for you" in my face. So today I had enough and have just completely
blocked cookies on `https://www.youtube.com`. However this has a drawback since
autoplay preference is maintained in a cookie.

**Comment by llacb47** [comment]
Subscribe to this list by @dandelionsprout: `https://raw.githubusercontent.com/DandelionSprout/adfilt/master/StopAutoplayOnYouTube.txt`

**Comment by cup** [comment]
Looks like this works as expected:

~~~
youtube.com/*/endscreen.js
~~~
