### ISSUE TITLE
POPUPS in similar websites

### ISSUE THREAD

**Issue by NubN** [uBlockOrigin/uAssets#6459]
### URL(s) where the issue occurs

```
https://www.elitegoltv.org/
https://www.pirlotvonline.org/
http://www.tarjetarojatv.org/
https://www.pirlotv.soccer/
https://www.rojadirectaonlinetv.com/
https://www.extremotvplay.com/
http://vipirlotv.fr/

```

### Describe the issue

popups, when you click in a link in main pages

### Screenshot(s)

none

### Versions

- Browser/version: Chrome
- uBlock Origin version: 1.22.4

### Settings

- Default

### Notes

All websites has the same appearance. and redirect to others

**Comment by mapx-** [comment]
test these filters
```
capodeportes.net##+js(aopw, _pop)
elitegoltv.org,extremotvplay.com,vipirlotv.fr,tarjetarojatv.org,pirlotv.soccer,pirlotvonline.org,rojadirectaonlinetv.com##+js(aopr, open)
```

**Comment by NubN** [comment]
super clean, good work
