### ISSUE TITLE
NSFW Give some suggestion for 520cc.cc

### ISSUE THREAD

**Issue by coinvpn** [uBlockOrigin/uAssets#6460]
### URL(s) where the issue occurs

520cc.cc 

### Describe the issue

It has inline script with obfuscation such as `function(p,a,c,k,e,r) {...}`, which is for anti-adblock.
And, I tried to figure it out and contributed these customed rule as follows:
 ```
520cc.cc##+js(set-constant, ADS_BLOCKED1, false)
520cc.cc##+js(set-constant, ADS_BLOCKED2, false)
520cc.cc##+js(set-constant, ADS_BLOCKED3, false)
520cc.cc##+js(set-constant, ADS_BLOCKED4, false)
520cc.cc##+js(set-constant, ADS_BLOCKED5, false)
```
if you have other better ways, just share with me. :)

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version:  77.0.3865.120
- uBlock Origin version: 1.22.4

### Settings
 ```
520cc.cc##+js(set-constant, ADS_BLOCKED1, false)
520cc.cc##+js(set-constant, ADS_BLOCKED2, false)
520cc.cc##+js(set-constant, ADS_BLOCKED3, false)
520cc.cc##+js(set-constant, ADS_BLOCKED4, false)
520cc.cc##+js(set-constant, ADS_BLOCKED5, false)
```

### Notes

it works~ :p

**Comment by mapx-** [comment]
screenshot with anti adb message ? We don't read chinese

**Comment by coinvpn** [comment]
> screenshot with anti adb message ? We don't read chinese

Yes, I captured the image.
https://imgur.com/a/7VS3peU
This message means that add our webstite to the white list of ABP.

**Comment by mapx-** [comment]
Do I need an account ? Clicking the various links will go to a signup form

**Comment by NubN** [comment]
in the video mapx-

`https://www.520cc.cc/thread-428258-1-1.html`

**Comment by mapx-** [comment]
I enabled both chinese lists, then I get only an inplayer frame on video which can be removed using this filter:
`520call.me###inplayer`

no other anti adb stuff

![image](https://user-images.githubusercontent.com/10303732/67225404-6e25ef00-f433-11e9-9b35-c739a96a59d5.png)

**Comment by NubN** [comment]
with the chinese lists no anti adblock for me. (only that black screen also). 
Without the CHN lists, yes 🥶

**Comment by mapx-** [comment]
- for the chinese lists this is the default: uBo lists + chinese regional ones
- if you don't use chinese lists just copy the necessary filters in your custom filters
- you could ask chinese lists maintainers to include this filter `520call.me###inplayer`

**Comment by coinvpn** [comment]
> * for the chinese lists this is the default: uBo lists + chinese regional ones
> * if you don't use chinese lists just copy the necessary filters in your custom filters
> * you could ask chinese lists maintainers to include this filter `520call.me###inplayer`

which chinese list do you use ? I don't install any extra list except original one.

**Comment by mapx-** [comment]
both chinese lists => see regional section in uBo filter lists
