### ISSUE TITLE
voxc.org [Anti-Adblock]

### ISSUE THREAD

**Issue by Robbie8592** [uBlockOrigin/uAssets#6461]
### URL(s) where the issue occurs

`http://voxc.org/bdx6Rw`

### Describe the issue

Getting a banner to disable my adblocker

### Screenshot(s)

![image](https://user-images.githubusercontent.com/29841633/67250553-d081ee00-f439-11e9-8e41-a20040af3c02.png)

### Versions

- Browser/version: Firefox 69.0.3
- uBlock Origin version: 1.22.4

### Settings

Default Settings

### Notes

None

**Comment by doio** [comment]
`http://voxc.org/04Hixpgd`

Now the page has endless "Click to Continue" with a popup ad every time

**Comment by doio** [comment]
`http://voxc.org/Qgmg`

The page has endless "Click here to Continue" since a couple of days ago.

**Comment by mapx-** [comment]
Tested in chrome, no issue for me. Are you using some other blocking extension ?
