### ISSUE TITLE
https://online-dvdrip.com/ anti-adblock

### ISSUE THREAD

**Issue by etintos** [uBlockOrigin/uAssets#6462]
URL(s) where the issue occurs
`https://online-dvdrip.com/`

Describe the issue
Anti-adblock.

Screenshot(s)
![image](https://user-images.githubusercontent.com/20620277/67261405-22406d80-f466-11e9-917b-103e9bb2b3ca.png)

Versions
Browser/version: Chrome v770.8865.120 64 bits
uBlock Origin version: 1.22.4
Settings
Default

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/d5aa1408c71405994e5991d620124c4e5691f1be
