### ISSUE TITLE
dailymail.co.uk

### ISSUE THREAD

**Issue by NubN** [uBlockOrigin/uAssets#6464]
### URL(s) where the issue occurs

`https://www.dailymail.co.uk/home/index.html`

### Describe the issue

Anti AdBlock

### Screenshot(s)

https://i.imgur.com/tp12a0V.png

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [v1.22.4]

### Settings

- Default

### Notes

i have mi filters updated.

Today i can reproduce anti adblock in `dailymail.co.uk`

**Comment by NubN** [comment]
again:
`https://www.dailymail.co.uk/home/index.html`

**Comment by NubN** [comment]
hi double scroll here, really a annoyance to navigate the page

I think it's because of the video (load at the bottom of the page, when it shouldn't be like this)

`https://www.dailymail.co.uk/home/index.html`

**Comment by lain566** [comment]
I can't reproduce any double scroll bar, can you show it in a screenshot? and the steps to follow to reproduce this issue.

**Comment by NubN** [comment]
sorry was disabling UBO.

if you turn OFF uBO and load a page all ok with ads.

but if after you turn ON uBO and reload the same page, happens that issue.

my bad

**Comment by NubN** [comment]
https://i.imgur.com/MnuoYIP.png

**Comment by NubN** [comment]
hey **lain566** are you getting this spam in the logs?

https://i.imgur.com/lVdmJ2r.png

i can see hundreds of those lines in the logs when i visit dailymail

sorry for the inconvenience 😃

**Comment by NubN** [comment]
ok haha is a incrusted map

`https://www.arcgis.com/apps/opsdashboard/index.html`

nevermind

**Comment by NubN** [comment]
`https://animeflv.net/ver/54292/jashinchan-dropkick-s2-4`

https://i.imgur.com/sqiI6TI.png
