### ISSUE TITLE
Github lazyload

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6466]
Anybody can break (stop it / abort) the script with this blue charging bar at top?

![obraz](https://user-images.githubusercontent.com/35370833/67415493-67c77c80-f5c5-11e9-8e21-09481bf63af7.png)

I am not interested in CSS hiding animations: https://dev.webonomic.nl/how-to-disable-css-transforms-transistions-and-animations/comment-page-1.

**Comment by mapx-** [comment]
it's not an issue, ask for suggestions on uBo reddit
