### ISSUE TITLE
wordcounter.net

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#647]
### URL(s) where the issue occurs

`wordcounter.net`

### Describe the issue

Unblocked Grammarly ad

**Comment by ghajini** [comment]
Hey you probably not template....please follow template

**Comment by mapx-** [comment]
add
`||wordcounter.net/images/wc-gly-instant.png`

press ctrl-F5

**Comment by terrorist96** [comment]
> such minor issues to be reported to easylist or adding to your custom filters with the help of ubo logger

Yes, but I wasn't sure if it could be blocked by uBO specific filters since Grammarly is known to bypass ABP.

> add
||wordcounter.net/images/wc-gly-instant.png

Thanks

**Comment by okiehsch** [comment]
Can be fixed by EasyList.
fyi @ryanbr

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?f=62&t=37952
