### ISSUE TITLE
How could I remove the ads in videos for nfmovies.com?

### ISSUE THREAD

**Issue by coinvpn** [uBlockOrigin/uAssets#6473]
### URL(s) where the issue occurs

`https://www.nfmovies.com/video/?17126-3-21.html`

### Describe the issue

Using "`https://www.nfmovies.com/video/?17126-3-21.html`", it will display trademark on top of the upper right corner.
However, I used to its source from
"`https://iqiyi.com-t-iqiyi.com/20190510/2434_b4d33ef4/1000k/hls/index.m3u8`" through the vlc player.
It won't show any ads texts.
I was wondering that it embeded the texts by code with the embeded player at the website.
How could I remove it? maybe change the embeded player ? how to do?

### Screenshot(s)
with ads texts 
https://imgur.com/a/rFAyTc8
### Versions

- Browser/version: 77.0.3865.120
- uBlock Origin version: 1.22.4

### Settings

 default settings

**Comment by lain566** [comment]
> it will display trademark on top of the upper right corner.

Do you mean the website logo? `www.nfmovies.com/templets/default/images/logos/06.png`

If that is then add this filter.
`nfmovies.com##[class="dplayer-logo"]`

**Comment by discusssth** [comment]
老兄，这些赌场广告是视频压制的时候嵌入的，无论如何都去除不了的。

**Comment by coinvpn** [comment]
please, using English.
Be polite!

**Comment by mapx-** [comment]
no feedback
