### ISSUE TITLE
xfinity.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#6474]
### URL(s) where the issue occurs

`https://www.xfinity.com/mobile/`

### Describe the issue

Chat button on top right doesn't work.

### Notes

`@@||analytics.analytics-egain.com/onetag/*$script,domain=xfinity.com`

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Not seeing this.

**Comment by ryanbr** [comment]
Pasting the actual scripts being affected would help, but analytics-egain.com doesn't show as a blockable item

**Comment by mapx-** [comment]
Did you click the chat button ?
