### ISSUE TITLE
Photobucket anti-adblock bypass

### ISSUE THREAD

**Issue by thorlancaster** [uBlockOrigin/uAssets#6476]
### URL(s) where the issue occurs

`[https://photobucket.com/recentuploads?page=1]`

### Describe the issue

When attempting to access most URLs on PhotoBucket, a modal message appears that prevents you from browsing the site. Due to JS modification of CSS, using uBlock to block the modal does not make the page usable. It remains blurred.

### Versions

- Browser/version: [76.0.3809.132 64-bit Linux]
- uBlock Origin version: [1.22.4]

### Settings

All of the settings are the default. Removing all of my filters doesn't change the issue.

### Notes and Fix

Adding the following line to "My Filters" blocks the anti-adblock message. Perhaps you should add it to the anti-adblock blocker list to fix the issue for all users.
`photobucket.com/resources/common/js/prompt.js`

**Comment by okiehsch** [comment]
Have you tried updating your filter lists? 
I am pretty sure that this was already fixed earlier today with
https://github.com/uBlockOrigin/uAssets/commit/755c7d1a7b705da3b38d99fc8029855333494eb0

**Comment by thorlancaster** [comment]
I just did a force-update and commented out my custom filter. It blocks the popup.
Your solution that blocks the SWAL modals is probably better than mine that blocks just the anti-adblock script. Next time I'll just do a force update first.
Thanks for fixing the issue.

**Comment by yourduskquibbles** [comment]
CSS Style only filters I found that also work to remove the warning in case any one needs them to test in the future are below.

`photobucket.com##.swal2-container`
`photobucket.com##body.swal2-shown > [aria-hidden="true"]:style(filter: unset !important;)`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://s1137.photobucket.com/user/emt-shawn/media/Mobile%2520Uploads/IMG_20160414_095721777.jpg.html`
