### ISSUE TITLE
thesilphroad.com just a background image?

### ISSUE THREAD

**Issue by jidanni** [uBlockOrigin/uAssets#6477]
Is `https://thesilphroad.com/` just a background image for anybody else?

**Comment by okiehsch** [comment]
No.
![image](https://user-images.githubusercontent.com/16838044/67555966-a159ce00-f712-11e9-811a-771e41c7962e.png)

**Comment by uBlock-user** [comment]
Why would that be the case?

**Comment by mapx-** [comment]
no obviously issues, no explanation

for other such questions use reddit:
https://www.reddit.com/r/uBlockOrigin/

**Comment by jidanni** [comment]
Must be some other of my extensions...
![5080-1](https://user-images.githubusercontent.com/1230959/67613709-2d3b2b00-f7e3-11e9-982e-4f1e76f24263.jpg)
