### ISSUE TITLE
rottentomatoes.com

### ISSUE THREAD

**Issue by nasht00** [uBlockOrigin/uAssets#6479]
### URL(s) where the issue occurs

`https://www.rottentomatoes.com/m/gemini_man_2019`

(this is true for any movie page)

### Describe the issue

Even though I marked Rotten Tomates as safe in uBlock, all the images are disabled.  
When I completely disable the extension, the images appear.

### Screenshot(s)

<img width="1123" alt="Screen Shot 2019-10-25 at 17 00 52" src="https://user-images.githubusercontent.com/329834/67581987-38da1380-f749-11e9-95db-59504d463256.png">
<img width="1107" alt="Screen Shot 2019-10-25 at 17 02 44" src="https://user-images.githubusercontent.com/329834/67582034-50190100-f749-11e9-947c-a71dcb318c62.png">

### Versions

- Browser/version: Chrome Version 77.0.3865.120 (Official Build) (64-bit)
- uBlock Origin version: 1.22.4

### Settings

No changes to default AFAIK, apart from adding websites to the whitelist, through the UI.

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
No issue for me chrome / uBo last dev version.

Try resetting uBo to the default settings, purge + update the filter lists.
