### ISSUE TITLE
instagram.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6481]
mobile version have other url:

```html
<a href="/accounts/signup/phone">
<span class="_7UhW9   xLCgt       qyrsm      gtFbE    se6yk        ">Sign up</span>
</a>
```

![obraz](https://user-images.githubusercontent.com/35370833/67597698-186f8080-f76c-11e9-82dc-ed290dd33332.png) |
--- |

---

```
instagram.com###react-root ~ div[class*=" "][class$=" "][role="presentation"]:-abp-has(a[href^="/accounts/"][href*="signup/"])
```

---

And links gone if Instagram detect logon on Facebook:

![obraz](https://user-images.githubusercontent.com/35370833/67597909-8d42ba80-f76c-11e9-94dd-5564b4c74e1a.png) |
--- |

Button `Continuar como krystian3w` and `Cambiar de cuenta` have event js listener (click/mouseover).

**Comment by yourduskquibbles** [comment]
Are you suggesting update `uBlock Filters - Annoyances`?

`instagram.com###react-root ~ div[class*=" "][class$=" "][role="presentation"]:has(a[href="/accounts/emailsignup/"])` 
to be replaced with 
`instagram.com###react-root ~ div[class*=" "][class$=" "][role="presentation"]:has(a[href^="/accounts/"][href*="signup/"])`

**Comment by krystian3w** [comment]
Yep.

If version `Continuar como ...` (fb account) no have solution no based on language, you can ignore it.

**Comment by yourduskquibbles** [comment]
I tested the updated suggested filter and confirm it works for mobile and desktop so will update the filter to `instagram.com###react-root ~ div[class*=" "][class$=" "][role="presentation"]:has(a[href^="/accounts/"][href*="signup/"])` 

However I can't recreate the change in modal if facebook is logged in to see if additional filter is possible. What software are you using to emulate android with firefox browser so I can try testing with same setup.

**Comment by krystian3w** [comment]
1. logon on `facebook.com`
2. open `homepage instagram`, change language (in footer exisit link) to `Español` or other "exotic".
3. Try emulate Samsung Galaxy S9/S9+
4. open any profile and you should see pop-up with your detected facebook account

As an emulated example of Samsung S9 is not real, I can try to do it on one of my two phones in Firefox / Kiwi Browser / Yandex Browser.

**Comment by yourduskquibbles** [comment]
`instagram.com` updated their site so if you click on a picture on a profile it forces a login modal that was not being shown because of the previous filter that was removed by @gorhill in https://github.com/uBlockOrigin/uAssets/commit/1ca98cc3a7219740d85a30a4724995b89bca1fc4#diff-92ce64631591b876fb9571e6e19a534aL1668

Blocking the scrolling overlay when you scroll down the page still seems to be fixed with an updated filter proposed by @krystian3w in https://github.com/yourduskquibbles/webannoyances/issues/211#issue-601509253 `instagram.com###react-root ~ div[class*=" "][class$=" "][role="presentation"]:has(a[href^="/accounts/"][href*="signup/"]):not(:has(button[type="button"] > svg[aria-label][width="18"][height="18"][viewBox*="48"]))`. 

I've tested on `https://www.instagram.com/toddphillips1/` in English and seems to work fine with no obvious breakage. 

I will add this updated filter back to `uBlock Filters - Annoyances` so page is still scrollable without logging in but would appreciate any comments if someone finds issue with the filter.

**Comment by okiehsch** [comment]
> comments if someone finds issue with the filter.

https://github.com/uBlockOrigin/uAssets/issues/7758
 I commented it out for now.

**Comment by krystian3w** [comment]
Instagram added `div` between `button` and `svg`.

```
instagram.com###react-root ~ div[class*=" "][class$=" "][role="presentation"]:has(a[href^="/accounts/"][href*="signup/"]):not(:has(button[type="button"] > div > svg[aria-label][width="18"][height="18"][viewBox*="48"]))
```

Optionally, this can be checked less precisely by skipping the "child" combinator (`>`).

**Comment by yourduskquibbles** [comment]
> Instagram added `div` between `button` and `svg`.
> 
> ```
> instagram.com###react-root ~ div[class*=" "][class$=" "][role="presentation"]:has(a[href^="/accounts/"][href*="signup/"]):not(:has(button[type="button"] > div > svg[aria-label][width="18"][height="18"][viewBox*="48"]))
> ```
> 
> Optionally, this can be checked less precisely by skipping the "child" combinator (`>`).

This works for me and still allows the login modal to popup when you click on an individual picture. 

Still no way to view a full post from a profile page without logging in from what I can tell unless you have the direct link.

e.g. clicking on the first picture on `https://www.instagram.com/toddphillips1/` will fire the login modal prompt, but if you have the [direct url](https://www.instagram.com/p/CCwiU5gpa2O/) to the picture it will load not logged in. Very user-hostile behavior so they can track you by forcing log-ins to view any content 👎

**Comment by krystian3w** [comment]
> This works for me and still allows the login modal to popup when you click on an individual picture.

Good.

> Still no way to view a full post from

Unfortunately, there's not even a safe way to whip it up with `aeld` (because the video playback button is damaged, which is not blocked by account requirements).

I converted the Polish version to text checking, so if the filter disappears completely from uBO it still stays in the optional project "`Polish Filters of annoying elements`", because in AdGuard they don't want to play with detection pop-up after clicking on image should appear.

**Comment by Hrxn** [comment]
> > Instagram added `div` between `button` and `svg`.
> > ```
> > instagram.com###react-root ~ div[class*=" "][class$=" "][role="presentation"]:has(a[href^="/accounts/"][href*="signup/"]):not(:has(button[type="button"] > div > svg[aria-label][width="18"][height="18"][viewBox*="48"]))
> > ```
> > 
> > 
> > Optionally, this can be checked less precisely by skipping the "child" combinator (`>`).
> 
> This works for me and still allows the login modal to popup when you click on an individual picture.
> 
> Still no way to view a full post from a profile page without logging in from what I can tell unless you have the direct link.
> 
> e.g. clicking on the first picture on `https://www.instagram.com/toddphillips1/` will fire the login modal prompt, but if you have the [`direct url`](https://www.instagram.com/p/CCwiU5gpa2O/) to the picture it will load even if you are not logged in. Very user-hostile behavior so they can track you by forcing log-ins to view any content 👎

True. But the "direct url" example you use here is simply the URL to the post itself. And that still works.
Agreed, this is user-hostile, but you can still use any Instagram profile page by simply doing `Right Click -> Open Link in New Tab`

**Comment by krystian3w** [comment]
or scroll click - 1 click less.

**Comment by yourduskquibbles** [comment]
https://github.com/uBlockOrigin/uAssets/pull/7764 from @llacb47 fixes the left click on a post login hijack

**Comment by kuchenstrudel** [comment]
they now redirect to the login page (https://www.instagram.com/accounts/login/) if you go to the main page of a user ( https://www.instagram.com/$USERNAME/), if you go directly to a post id (https://www.instagram.com/p/$POSTID/) it still works.

**Comment by krystian3w** [comment]
Maybe this need json-prune like YT with dynamic updated core of page (xhr / Ajax).
