### ISSUE TITLE
opensubtitles.org

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#6484]
### URL(s) where the issue occurs

`https://www.opensubtitles.org/en/subtitles/7907255/morocco-tr`

### Describe the issue

The "Download" button starts downloading a Firefox extension before the subtitles.

### Versions

- Browser/version: Firefox stable
- uBlock Origin version: 1.23.0

### Settings
Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin lists

**Comment by mapx-** [comment]
test these filters
```
opensubtitles.org##+js(nano-sib)
opensubtitles.org##+js(ra, data-ff-code)
opensubtitles.org##+js(window.open-defuser)
opensubtitles.org##.ui-dialog, .ui-widget-overlay
```

**Comment by adranger** [comment]
They work. Thanks.
