### ISSUE TITLE
gamepedia.com

### ISSUE THREAD

**Issue by NubN** [uBlockOrigin/uAssets#6485]
### URL(s) where the issue occurs

```
https://terraria.gamepedia.com/Plants
https://albedonwars.gamepedia.com/Untouched
https://7daystodie.gamepedia.com/Health
```

### Describe the issue

Problematic filter **in uBlock filters – Annoyances**:

`gamepedia.com###bodyContent:style(width:100%!important)`

**maybe a fix**:
`terraria.gamepedia.com###siderail_terraria_gamepedia` 
for terraria site, (anyone can create as more generic filter)

### Screenshot(s)

none

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [v1.23.0]

### Settings

- Default + uBlock filters – Annoyances

**Comment by llacb47** [comment]
What is the problem?

**Comment by NubN** [comment]
for example.. the width pages or.. that item not blocked (scrolling down).
https://i.imgur.com/5S7XMu6.png

try: withelisting the first filter: 
```
gamepedia.com#@##bodyContent:style(width:100%!important)
terraria.gamepedia.com###siderail_terraria_gamepedia
```

in: `https://terraria.gamepedia.com/Plants`

**Comment by okiehsch** [comment]
What is problematic about `gamepedia.com###bodyContent:style(width:100%!important)`?
Adding 
`gamepedia.com##[id^="siderail_"]`
looks fine on my end.

**Comment by NubN** [comment]
the width of the articles, but looks better with that filter yes 🤣

and your filter working fine:
`gamepedia.com##[id^="siderail_"]` 👍

**Comment by NubN** [comment]
the width of articles.. although nothing important

and the filter `gamepedia.com##[id^="siderail_"]` working fine
