### ISSUE TITLE
linkvertise.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#6487]
URL(s) where the issue occurs

`https://linkvertise.com/9879/Abcthg`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 77 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.22.4

Settings

Default

**Comment by JobcenterTycoon** [comment]
can you bypass the "addon hinzufügen" point? Because i dont want to install unknown Addons

**Comment by okiehsch** [comment]
There is an open issue about that https://github.com/uBlockOrigin/uAssets/issues/6065

**Comment by JobcenterTycoon** [comment]
Linkvertise has a new step to do so `linkvertise.com##+js(json-prune, data.meta.require_addon data.meta.require_captcha data.meta.require_notifications data.meta.require_og_ads data.meta.require_video data.meta.require_web)` need to be extended
<img width="400" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/149377422-01bbb7ef-ce92-48a9-a3a0-004f00660128.PNG">
`https://linkvertise.com/225133/Resolution/1`
