### ISSUE TITLE
http://www.mejoratuescuela.org/

### ISSUE THREAD

**Issue by alex-mayorga** [uBlockOrigin/uAssets#649]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://www.mejoratuescuela.org/`

### Describe the issue

Most part of the main content is blocked.

### Screenshot(s)

![screenshot-2017-8-24 mejora tu escuela](https://user-images.githubusercontent.com/649262/29683445-0489c16a-88d4-11e7-8594-84c949e8a1f1.png)

### Versions

- Browser/version: Firefox Nightly 57.0a1
- uBlock Origin version: 1.13.8rc5

### Settings

-

**Comment by mapx-** [comment]
add
`mejoratuescuela.org#@#.container-ads`

**Comment by diaux** [comment]
Fixed in EasyList Spanish. Thank you.
