### ISSUE TITLE
gamemod.io

### ISSUE THREAD

**Issue by lyndmi** [uBlockOrigin/uAssets#6491]
### URL(s) where the issue occurs

```
https://gamemod.io/garena-free-fire-ob18-1-41-3-v6-mod-pink-body-data-anntena-hand-full-high-aim-damage-aroumr/
https://gamemod.io/downloads/?url=https%3A%2F%2Fdl.gamemod.io%2Ffile%2FSF8762C14B6B
```

### Describe the issue

Adblocker must be disabled to show ads and you must click on ads and go back in order to download.
There is video tutorial how to do it: https://youtu.be/rh5_6wkWQqc

### Screenshot(s)

Before:
![image](https://user-images.githubusercontent.com/24647715/67670446-38719080-f974-11e9-8d2a-3b5af7d01909.png)

After:
![image](https://user-images.githubusercontent.com/24647715/67670488-4aebca00-f974-11e9-8202-7bb792f6c60d.png)

### Versions

- Browser/version: Opera 64.0.3417.61
- uBlock Origin version: 1.22.4

### Settings

- Default

### Notes

Request to bypass it if possible

**Comment by mapx-** [comment]
I guess you need some userscript, to be included in this category:
https://github.com/uBlockOrigin/uAssets/issues/5890

**Comment by krystian3w** [comment]
But Google ads?

**Comment by uBlock-user** [comment]
Can't reproduce any anti adblock, downloads work as expected.

**Comment by krystian3w** [comment]
I have speed timer, works, maybe JsPengiun added scriplet in `Nano - Annoyance` (better copy into uBO - Annoyance)?

**Comment by okiehsch** [comment]
If I click any of the download options
![image](https://user-images.githubusercontent.com/16838044/67739705-a5883300-fa13-11e9-8be3-c0f2f8a50070.png)
I get this choice
![image](https://user-images.githubusercontent.com/16838044/67739752-c9e40f80-fa13-11e9-8b39-350c26d892a4.png)

`gamemod.io##+js(nano-stb)`
works on my end.

**Comment by krystian3w** [comment]
`https://dl.gamemod.io/file/SF8762C14B6B`

    dl.gamemod.io##+js(nano-sib)

Worms, recover for subdomain please.
