### ISSUE TITLE
camera.aeonax.com [Anti-Adblock]

### ISSUE THREAD

**Issue by tillcash** [uBlockOrigin/uAssets#6496]
URL(s) where the issue occurs
`https://camera.aeonax.com/#predownloads` 

Describe the issue
Anti-adblock.

Screenshot(s)
https://i.imgur.com/i3n7Es9.png

Versions

- Browser/version: Firefox 70 (Official Build) (64-bit)
- uBlock Origin version: v1.23.0

**Comment by mapx-** [comment]
Do you see in the logger these filters /exceptions ?
```
@@||aeonax.com^$generichide
@@||pagead2.googlesyndication.com/pagead/$script,domain=aeonax.com
```

**Comment by krystian3w** [comment]
If we're using generichide, we could use a little something like that:

`aeonax.com##td:has(.adsbygoogle)`

**Comment by uBlock-user** [comment]
`||googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect=googlesyndication_adsbygoogle.js,important` works.

**Comment by krystian3w** [comment]
why you no cut withe spaces `Google Ads`...

@okiehsch

**Comment by llacb47** [comment]
New redirect resource?

**Comment by krystian3w** [comment]
Very old..., also works `noopjs` 😉.

**Comment by uBlock-user** [comment]
> also works noopjs 

Not for this case. The anti adblock checks if number of iframes created is > 2 or not, noopjs, doesn't create any iframes for the page, so won't work.
