### ISSUE TITLE
dl.gamemod.io [nano-sib] [timer]

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6498]
`https://dl.gamemod.io/file/SF8762C14B6B`

    dl.gamemod.io##+js(nano-sib)

Works, recover for subdomain please.

https://github.com/uBlockOrigin/uAssets/commit/6d1183114e5c19570db3fefd29d63af71d830755

**Comment by mapx-** [comment]
What's the reason  / issue ?

**Comment by krystian3w** [comment]
Because possible speed up download form `dl.gamemod.io/file/SF8762C14B6B`
New filter no speed up on `dl.gamemod.io`

try pruge uBlock filters and test filter.

---
@okiehsch

**Comment by mapx-** [comment]
You mean we need both filters ?
```
gamemod.io##+js(nano-stb)
gamemod.io##+js(nano-sib)
```

**Comment by krystian3w** [comment]
Both or exclusion:

```
gamemod.io,~dl.gamemod.io##+js(nano-stb)
~gamemod.io,dl.gamemod.io##+js(nano-sib)
```

**Comment by mapx-** [comment]
my filters are working fine
