### ISSUE TITLE
dailymail.co.uk Not Working on Pale Moon

### ISSUE THREAD

**Issue by indiuscartha** [uBlockOrigin/uAssets#6499]
### URL(s) where the issue occurs

`http://www.dailymail.co.uk/home/index.html`

### Describe the issue

Can't access DailyMail.co.uk on Pale Moon, working fine on Firefox 70.0 / Ublock Orgin 1.21.2.
Caches purged and fully updated filters.

### Screenshot(s)

![a](https://user-images.githubusercontent.com/57152701/67799844-12381780-fa7e-11e9-8c94-4032a2f85e35.png)

![b](https://user-images.githubusercontent.com/57152701/67800484-36e0bf00-fa7f-11e9-8fa7-a54dfd431fdb.png)

### Versions

- Browser/version: [Pale Moon 28.7.2]
- uBlock Origin version: [1.16.4.11]
### Settings

- [No changes made.]

**Comment by mapx-** [comment]
The reason is uBo legacy version is not using the last syntax.
I added the filter in the old syntax in the legacy list

add this legacy lits to your uBo as custom list from:
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/legacy.txt
