### ISSUE TITLE
Delayed Ads with redirect/popup on watchseriesfree.to

### ISSUE THREAD

**Issue by xH4wK** [uBlockOrigin/uAssets#650]
### URL(s) where the issue occurs

`[https://watchseriesfree.to/episode/Daredevil-1_s2_e5.html]`

### Describe the issue

[There are multiple ads that become active after a while and after click anywhere on the page they perform redirect on current page "A" which loads page "B" with the ad and then opens a new popup with previous page "A"]

### Versions

- Browser/version: [Chrome Version 60.0.3112.101 (Official Build) (64-bit)]
- uBlock Origin version: [1.13.8]

### Settings

- [None in settings, activated some additional filters]

### Notes

[Discussed this on EasyList forums, got suggestion to post here. https://forums.lanik.us/viewtopic.php?f=62&t=37936&sid=85a0623320cfb222d69172eabde46aaf]

**Comment by mapx-** [comment]
it should work
`watchseriesfree.to##script:inject(noeval.js)`

**Comment by gorhill** [comment]
The page is pulling the popunder js payload from a css file, to work around EasyList's `/\.com\/[0-9]{2,9}\/$/$third-party,script` filter.

First proposed solution which would just prevent the page to connect to anything else than what is legit:

    ||watchseriesfree.to^$csp=default-src 'self' www.google.com 'unsafe-inline' 'unsafe-eval'

Does this break any functionality on the site?

**Comment by xH4wK** [comment]
This does not break any functionality based on my testing and I do not see the ads now - so far.
It seems to have helped ! Thanks !

**Comment by SMed79** [comment]
> The page is pulling the popunder js payload from a css file (`https://a9d7c19f0282.com/1321604.css`), to work around EasyList's /\.com\/[0-9]{2,9}\/$/$third-party,script filter.

a filter was suggested two months rather https://github.com/easylist/easylist/commit/ea5591665da679164f9b6aba194c0f184fe4d24d#commitcomment-23743140

**Comment by Hrxn** [comment]
Right now, site does not work for me at all..
Is it down?
