### ISSUE TITLE
Infranken.de anti adblock video overlay

### ISSUE THREAD

**Issue by katzabrack** [uBlockOrigin/uAssets#6500]
### URL(s) where the issue occurs

`https://www.infranken.de/regional/miltenberg/klingenberg-im-kreis-miltenberg-18-jaehriger-hantiert-mit-machete-polizist-schiesst-mit-dienstwaffe;art165840,4527970`

### Describe the issue

Video doesnt play, instead anti-adblock-message is shown.

### Screenshot(s)

![asdsads](https://user-images.githubusercontent.com/57179422/67856120-1f074a80-fb14-11e9-9a6e-525231f6ad34.jpg)

### Versions

- Browser/version: Firefox 70.0 64 bit
- uBlock Origin version: 1.23.0

**Comment by mapx-** [comment]
test this filter
`||player-feedback-*.glomex.com/pf/$xmlhttprequest,badfilter`

**Comment by okiehsch** [comment]
@mapx- can you reproduce?
The video plays without issue on my end with Firefox or Chromium using a german IP.

**Comment by mapx-** [comment]
Yes .. but after many refreshes it's pretty inconsistent

**Comment by okiehsch** [comment]
If I add your filter I can reproduce the anti adblock message consistently on my end using Chromium, so that seems to be a no go.

**Comment by okiehsch** [comment]
Same with Firefox if I use the badfilter I always get the ant-adblock message. Without it the video plays fine.

**Comment by mapx-** [comment]
Weird, exactly the opposite

**Comment by okiehsch** [comment]
Looking at it the filter `||player-feedback-*.glomex.com/pf/$xmlhttprequest` was added to fix an anti adblock message.
https://github.com/uBlockOrigin/uAssets/issues/5952#issuecomment-516714291 and the following discussion.
It also still works at those `merkur.de` links in that issue thread on my end.

**Comment by ZaphodBeebblebrox** [comment]
If it helps, I tested in in chrome then firefox.
For chrome, my first load of the page triggered the anti-adblock, and all subsequent loads did not, even when I cleared cookies. When I added the badfilter, I consistently triggered the anti-adblock.
For firefox, I did not trigger the anti-adblock without the badfilter, but I did with the badfilter.

**Comment by lain566** [comment]
@okiehsch I can't reproduce any anti adblock using a german IP.
I can reproduce anti adblock only if I add `||player-feedback-*.glomex.com/pf/$xmlhttprequest,badfilter`

**Comment by okiehsch** [comment]
Thanks.
@katzabrack are you using a default setup?

**Comment by mapx-** [comment]
I still get (not consistently - tested with german ip too) anti adb stuff.

tested

```
https://player.glomex.com/integration/1.185.0/iframe-player.html?integrationId=excq22d8j45jjyr8&playlistId=v-bgf7mv01k73d
http://player.glomex.com/integration/1.185.0/iframe-player.html?integrationId=3gr5vmeqrjg7ra0nk&playlistId=v-by2t3r4yzjip-fa&width=588&height=330&origin=glomex-player
```

using these filters seem to fix the issue on my end:
*$xhr,redirect-rule=nooptext,domain=player.glomex.com
player.glomex.com#@#+js(set-constant, Math.ceil, trueFunc)

**Comment by mapx-** [comment]
@katzabrack could you test the filters ?

**Comment by katzabrack** [comment]
At the moment the videos work without adding the filter. It seems they removed the anti-adblock-script.

**Comment by okiehsch** [comment]
````
*$xhr,redirect-rule=nooptext,domain=player.glomex.com
player.glomex.com#@#+js(set-constant, Math.ceil, trueFunc)
````
works fine on my end, I still can't reproduce but if you can feel free to change the fix that way.

**Comment by mapx-** [comment]
still keeping `Math.ceil`  I got video ad in the last test
