### ISSUE TITLE
Videos don't play on mlb.com

### ISSUE THREAD

**Issue by josephcsible** [uBlockOrigin/uAssets#6503]
### URL(s) where the issue occurs

`https://www.mlb.com/news/field-of-dreams-game-tickets-and-faqs`

### Describe the issue

When I click the Play button on either of the two videos on the above page, I remain at a gray screen indefinitely.

### Versions

- Browser/version: Firefox 70.0
- uBlock Origin version: 1.23.0

### Settings

- All defaults

### Notes

The following exception rule fixes it for me:
```
@@||doubleclick.net/gampad/ads*mlb.com$xhr,domain=imasdk.googleapis.com
```
This seems to be a recurring issue across multiple sites (search for "gampad" in unbreak.txt). I wonder if there's a better way we can fix it for all of them, than to keep adding these one-off rules.

**Comment by okiehsch** [comment]
Thanks for investigating, redirecting does only work for a few sites - `mlb.com` is not one of those, so the one-off exceptions are the best way to fix those issues I can see.

Now back to watching Game 7. :wink:
