### ISSUE TITLE
Instagram Breaks

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uAssets#6506]
Instagram breaks when you block the "Login to continue" popup

![34534534](https://user-images.githubusercontent.com/18757054/67997004-5aa82e80-fc52-11e9-9dd9-70f4a0c33edc.jpg)

**Comment by okiehsch** [comment]
I need an example link, the template is there for a reason.

**Comment by GKid94** [comment]
Here https://www.instagram.com/pivokosa/?hl=en, try scrolling down and blocking the popup, and then reload the page and scroll down again

**Comment by llacb47** [comment]
It is already blocked in uBO annoyances.

**Comment by GKid94** [comment]
@llacb47 Ok thx

**Comment by okiehsch** [comment]
So can this be closed?

**Comment by GKid94** [comment]
@okiehsch Ok

**Comment by yourduskquibbles** [comment]
Related: https://github.com/uBlockOrigin/uAssets/issues/6481

Issue described here should be fixed with https://github.com/uBlockOrigin/uAssets/commit/05a3fea080d06d4f06d1dae729f2f4aa3d0af0c7
