### ISSUE TITLE
newsbeast.gr video ads

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#6508]
when you start the video, there are 9 seconds ads

### URL(s) where the issue occurs
newsbeast.gr
example:
 `https://www.newsbeast.gr/world/arthro/5585760/i-sokaristiki-stigmi-poy-dimosiografos-mathainei-live-oti-echei-karkino`

- uBlock Origin version: 1.23.0

**Comment by mapx-** [comment]
Does this help ?
`||vidads.gr^$3p`

**Comment by patrickdrd** [comment]
yes, great! thanks a lot!

**Comment by mapx-** [comment]
@kargig
