### ISSUE TITLE
MVPS blocks images at chip.de

### ISSUE THREAD

**Issue by sdfasdfgawe456h4356** [uBlockOrigin/uAssets#651]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://www.chip.de/news/iPhone-8-Apple-baut-ein-Speichermonster_105537750.html`

### Describe the issue

Some pictures dont show in articles on chip.de with MVPS enabled. (standard config)
I think thats a job for uBlock filters - Unbreak.

### Screenshot(s)

![mvps](https://user-images.githubusercontent.com/23087597/29726495-35e63598-89d0-11e7-8164-3b1554ab354b.jpg)

### Versions

- Browser/version: Firefox 55
- uBlock Origin version: 1.13.8

### Settings

- MVPS is standard.

### Notes

Its MVPS.

**Comment by okiehsch** [comment]
Add
`@@||ad-js.chip.de/static/jquery.js$script,first-party`
This issue will not be fixed by `uBO-unbreak`
https://github.com/uBlockOrigin/uAssets/issues/423#issuecomment-305553681

**Comment by SMed79** [comment]
Reported / fixed.

> that entry has been disabled and this will reflect in the next update.
> `# 0.0.0.0 ad-js.chip.de #[affects images]`
