### ISSUE TITLE
gelbooru.com broken [NSFW]

### ISSUE THREAD

**Issue by sfan5** [uBlockOrigin/uAssets#6510]
### URL(s) where the issue occurs

`https://gelbooru.com/index.php?page=post&s=list&tags=all` (<b>NSFW</b>)

### Describe the issue

Gallery view does not show any content.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/1042418/68036574-43a32400-fcc6-11e9-8de3-4c9b5ae14a9e.png)

### Versions

- Browser/version: Firefox 70.0
- uBlock Origin version: v1.23.0

### Settings

No changes to default settings necessary to reproduce.

### Notes

The problematic filter is contained in ublock-filters:
https://github.com/uBlockOrigin/uAssets/blob/b7df9c6839f468807c5aa6a1700d9ac8c83af446/filters/filters.txt#L962
Excluding it by adding the following to "My Filters" fixes the issue:
```
gelbooru.com#@#:xpath(//*[contains(text(),"disable")])
```

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/653af41be611db711b668e1860b682a912d371e4
