### ISSUE TITLE
{Verystream.me/verystreamtv.com/verystream.it}

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6511]
### URL(s) where the issue occurs
`https://verystream.me/movies/terminator-dark-fate/`

`https://verystreamtv.com/movies/maleficent-mistress-of-evil-2019/`

`https://verystream.it/avengers-endgame/`

### Describe the issue

Popup ads
3rd party tracking 

### Versions

- Browser/version: firefox android stable
- uBlock Origin version: 1.23.0

### Settings

-uBO's default settings

### Notes
1.
Connections to oload.party seen despite recent takedown by ace = is that suspicious? 

2.duplicate 

`||logger.pw^$3p` 
 present both in ublock filters and easyprivacy

**Comment by ghajini** [comment]
1. Are you able to load players because loading loop continuously. ...

`https://verystream.me/movies/terminator-dark-fate/`

2.I still see popups here

`https://verystream.it/avengers-endgame/`

3.
Duplicate filters

`||qumagee.com^$3p`
`||86a6b542l7.com^$3p`

**Comment by mapx-** [comment]
> Are you able to load players because loading bars continuously. ...

now is working => it was a wrong filter

**Comment by ghajini** [comment]
No problem,you are already hardworking to make ublock origin best and you are best🤗

**Comment by ghajini** [comment]
`https://hd.verystream.it/after/`
Undefined crap

`hd.verystream.it##+js(acis, String.fromCharCode, 'shift')`
