### ISSUE TITLE
Twitter's advanced search and reply window are blank

### ISSUE THREAD

**Issue by Hawks91** [uBlockOrigin/uAssets#6513]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
When I try to use the advanced search feature on twitter or reply to a tweet, it only shows a blank pop up panel. And no, this is not related to a virus. The panel where you could search advanced is just simply blank. When I turn off Ublock it works. It probably has something to do with one of the default filter lists.
[Description of the bug or feature]

### A specific URL where the issue occurs
https://twitter.com/search-advanced
https://twitter.com/compose/tweet

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: Latest
* Browser Name and version: Chrome Latest
* Operating System and version: Win10 Pro

**Comment by mapx-** [comment]
I cannot reproduce any of the issues above.
Reset uBo to the default settings and test again.

**Comment by krystian3w** [comment]
try:

    mobile.twitter.com#@#span:has-text(/get the most/i):xpath(../../../../../..)
    mobile.twitter.com#@#div[tabindex="0"]:matches-css(position:fixed):has([href="/signup"])

**Comment by yourduskquibbles** [comment]
I can't reproduce with default settings/lists either.

What custom lists do you have enabled?
