### ISSUE TITLE
Surfline.com detecting uBlock

### ISSUE THREAD

**Issue by CapeData** [uBlockOrigin/uAssets#6516]
### URL(s) where the issue occurs

`https://www.surfline.com/surf-report/sebastian-inlet/5842041f4e65fad6a7708a9f`

### Describe the issue

Adblock detected

### Screenshot(s)

![2019-11-04_104804](https://user-images.githubusercontent.com/22532320/68134893-c7405900-fef0-11e9-9823-c61a14ab1dd6.jpg)

### Versions

- Browser/version: Firefox 70.0.1
- uBlock Origin version: 1.23.0

### Settings

- Default settings

### Notes

Attempted install of Nano Defender, however, it made no difference.

**Comment by auburnham** [comment]
Please remove this from the built-in uBlock Filter list (v2019-06-01 line 20612, surfline.com##+js(aopr, __BACKPLANE_API__)). It is breaking site functionality.

**Comment by mapx-** [comment]
please provide more details: what's broken, steps to reproduce the issue ?

**Comment by auburnham** [comment]
Site: surfline.com

In the default state, with this filter enabled from the built-in uBlock Filter list, when hovering the mouse over the top-page menu items "CAMS & REPORT" or "FORECASTS", the menus display "undefined".

However, when adding the following custom static filter (My Filter):
surfline.com#@#+js()
These menus are filled with content and function correctly.

**Comment by mapx-** [comment]
without that filter do you get anti adblocking stuff ?

**Comment by CapeData** [comment]
@auburnham I just checked using FF 76.0.1 and am not seeing the behavior you described. I did not test the filter you suggested.

**Comment by mapx-** [comment]
@CapeData I get undefined issue in both chrome / FF

**Comment by auburnham** [comment]
@mapx- No, when using the custom static filter there is no ad-block notice
@CapeData I am on Chrome 81.0.4044.138 (64-bit)

**Comment by mapx-** [comment]
@CapeData if you add
`surfline.com#@#+js(aopr, __BACKPLANE_API__)`

do you get the anti adblocking original issue ?

**Comment by mapx-** [comment]
I'll remove the breaking filter, I get no anti adb on my side too

**Comment by CapeData** [comment]
@mapx- I vist the site frequently and the anti adblocking msg has been sporadic recently (even when the filter was enabled). Actually, right now, I am not receiving the msg with the filter disabled.

**Comment by mapx-** [comment]
maybe because they are trial-oriented ?

**Comment by auburnham** [comment]
@mapx- Thank you. Update tested & site functions as expected without custom filter. 

@CapeData I checked premium & visitor functionality with similar results, but I'll update here if anything changes.

**Comment by CapeData** [comment]
@mapx- @auburnham Good work guys!
