### ISSUE TITLE
Normal (non-ad) images blocked on gizmodo.com.au and lifehacker.com.au

### ISSUE THREAD

**Issue by ararat698** [uBlockOrigin/uAssets#6518]
uBlock Origin is blocking images on gizmodo.com.au and lifehacker.com.au

I suspect that this is an effort on the part of the website operators to force us to whitelist their websites. Disabling the ad blocker enables the site to display properly.

### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by gwarser** [comment]
Link? Screenshot?

I cannot reproduce.

**Comment by gwarser** [comment]
Like this: 


![image](https://user-images.githubusercontent.com/886325/68197116-f79ffa00-ffb9-11e9-9201-0b0d955cc719.png)

?

**Comment by ararat698** [comment]
On the main thread of articles. Not the bottom or top banners.

Like this:
<img width="891" alt="Capture" src="https://user-images.githubusercontent.com/57387877/68197782-e9c89400-000e-11ea-8ba3-341c5f8d046b.PNG">

It is meant to look like this:
<img width="890" alt="Capture7" src="https://user-images.githubusercontent.com/57387877/68197797-f51bbf80-000e-11ea-9ed4-eeba3e44ce17.PNG">

**Comment by mapx-** [comment]
Reset uBo to the default settings (and then update the lists). Test again.

**Comment by gwarser** [comment]
Images disappear after visiting two articles.

**Comment by ararat698** [comment]
It's a fresh install onto a fresh device without ANY altered settings. This device was reset 2 days ago, and the issue is reproducible on all of my devices.

But I have done what you have asked regardless, and the issue remains.

Using Chrome 78, and uBO 1.23.0

**Comment by mapx-** [comment]
this should help for lifehacker
`@@||taboola.com^$script,domain=lifehacker.com.au`

**Comment by okiehsch** [comment]
`@@||googletagmanager.com/gtm.js$script,domain=lifehacker.com.au`
woks on my end, allowing the taboola script is not necessary as far as I can see.

**Comment by mapx-** [comment]
indeed
`@@||googletagmanager.com/gtm.js$script,domain=gizmodo.com.au|lifehacker.com.au`

**Comment by okiehsch** [comment]
Actually my filter does not work if I reload, hmm very weird.
It workd only if I reload bypassing the cache.

**Comment by mapx-** [comment]
does taboola work for you ?
`@@||taboola.com^$script,domain=gizmodo.com.au|lifehacker.com.au`

**Comment by okiehsch** [comment]
Yes, that works consistently on my end, sorry for myfirst reply I should have tested more thorough.
Your filter is the better ix.
