### ISSUE TITLE
iddeas.xyz [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#6519]
URL(s) where the issue occurs

`https://iddeas.xyz/og1w`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 77 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.23.0

Settings

Default

**Comment by dumbusernameidk** [comment]
`iddeas.xyz##+js(acis, Math, zfgloaded)`

popups, 3p frames, etc.

**Comment by okiehsch** [comment]
> can't seem to reproduce

The source looks clean `view-source:https://iddeas.xyz/og1w` on my end.

**Comment by dumbusernameidk** [comment]
It is odd because I noticed it on one page but then after I tried to double check it wouldn't show up anymore.

**Comment by okiehsch** [comment]
Well, now I can see it in the source, I will add your filter.
![image](https://user-images.githubusercontent.com/16838044/68450879-de32c400-01ec-11ea-9ce9-4811580d7acf.png)

**Comment by JobcenterTycoon** [comment]
anti-Adblock is back

**Comment by ZaphodBeebblebrox** [comment]
Example link takes me to eio.io

**Comment by JobcenterTycoon** [comment]
Anti Adblock on `https://myenemy.club/?go=og1wsfurl`
