### ISSUE TITLE
Ads appear after a few seconds in http://slideplayer.com.br/slide/6082138/

### ISSUE THREAD

**Issue by pedrogarcia** [uBlockOrigin/uAssets#652]
### URL(s) where the issue occurs

`http://slideplayer.com.br/slide/6082138/`

### Describe the issue

Ads are not blocked at all at http://slideplayer.com.br/slide/6082138/. After a few seconds after the page has completely been loaded, the elements in the screen move and ads are loaded. 

### Screenshot(s)

![screenclip 1](https://user-images.githubusercontent.com/2473545/29737483-94d1aeb6-89e4-11e7-852b-502d90860a43.png)

### Versions

- Browser/version: Chrome 60.0.3112.101 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.13.8

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

Using the logger, I managed to make the ads disappear using these filets
´´´
! 8/25/2017, 10:33:42 PM slideplayer.com.br
||slideplayer.com.br/slide/*$xmlhttprequest,first-party
! 8/25/2017, 10:31:01 PM slideplayer.com.br
||slideplayer.com.br/static/js/657f/total_blue.js$script,first-party
! 8/25/2017, 10:31:33 PM slideplayer.com.br
||slideplayer.com.br/static/way/*$script,first-party
´´´

**Comment by okiehsch** [comment]
`slideplayer.*##script:inject(abort-on-property-read.js, service.mode)`
