### ISSUE TITLE
klix.ba embedded youtube videos don't work

### ISSUE THREAD

**Issue by AsocialSurvival** [uBlockOrigin/uAssets#6521]
### URL(s) where the issue occurs

`https://www.klix.ba/vijesti/crna-hronika/kako-je-izgledala-potjera-za-napadacem-iz-sarajeva-pucao-je-na-policiju-a-ubio-se-bombom/191105097`

### Describe the issue

When using default enabled filters, updated now manually, ublock prevents clicking play or any part of embedded youtube videos. It shows one minus sign in 'requests blocked' or 'domains connected' window for youtube.com. 

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Firefox 70.0
- uBlock Origin version: 1.23.0

### Settings

- disabled auto update of filters
- blocked csp reports
- disabled webrtc

### Notes

Disabling ublock fixes it.

**Comment by llacb47** [comment]
Test URL: `https://www.klix.ba/xplayer?v=o0p9FkoMo80&sifra=191105097&Segment=Vijesti&Podkategorija=Crna%20hronika&Platform=Desktop`

**Comment by mapx-** [comment]
@ryanbr
