### ISSUE TITLE
Gamespot Website Broken

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uAssets#6526]
Gamespot website breaks `https://www.gamespot.com/news/`

![432423424](https://user-images.githubusercontent.com/18757054/68459399-99ffed80-0205-11ea-9696-cc36726961e0.jpg)

**Comment by mapx-** [comment]
Did you test using only the default settings ?

**Comment by GKid94** [comment]
I'm already using default settings

**Comment by mapx-** [comment]
I cannot reproduce any breakage

**Comment by mapx-** [comment]
wait .. it's broken for chrome, it's instart crap

**Comment by GKid94** [comment]
The images won't show and the search bar doesn't work

**Comment by mapx-** [comment]
and the address contgains g00, right ?

**Comment by okiehsch** [comment]
It is not broken on my end using chrome, I added some filters [yesterday](https://github.com/uBlockOrigin/uAssets/commit/de8799c1655dcb704bc5588017e57b798b84f9d7), make sure that your `uBO-filters` list is up to date.

**Comment by GKid94** [comment]
@mapx- Yes

**Comment by mapx-** [comment]
@okiehsch , so the `generichide` did the trick
@GKid94 force updating the lists

**Comment by GKid94** [comment]
How long does it take for the filter lists to get updated, some of them haven't been updated for a day

**Comment by mapx-** [comment]
3-4 days, just update now

**Comment by GKid94** [comment]
I've updated the filter lists and now the website works fine, can you make the filter lists to update more often

**Comment by okiehsch** [comment]
> so the generichide did the trick

Yes generichide the existing filters
````
/g00/*$ping,1p
*/ad?i10c.getabdurl=*&ad_channel=$media,1p,redirect=noop.txt
*?&ad_$image,redirect-rule=1x1.gif
````
seems to work fine with the newer Instart Logic versions.

**Comment by okiehsch** [comment]
> I've updated the filter lists and now the website works fine, can you make the filter lists to update more often

GitHub Pages sites have a soft bandwidth limit of 100GB per month.
https://help.github.com/en/github/working-with-github-pages/about-github-pages#usage-limits
We already use **way** more bandwidth, so that will probably not happen.

**Comment by GKid94** [comment]
@okiehsch Sorry my bad, I should contact uBlock Origin about that not you, you only manage the filter list

**Comment by jspenguin2017** [comment]
> GitHub Pages sites have a soft bandwidth limit of 100GB per month.

Are you using GitHub Pages to serve filters? `raw.githubusercontent.com` isn't GitHub Pages, `github.io` is. If you're concerned, why not use a proper CDN? There're a couple free ones with unlimited bandwidth.

**Comment by okiehsch** [comment]
> If you're concerned

If I remember correctly **gorhill** has mentioned in the past that he is mindful of the traffic generated by `uAssets`, that is why I mentioned the bandwith limit.

**Comment by okiehsch** [comment]
Found a comment by gorhill:
"The reason is to lower abusive behavior toward the servers which host the filter lists. Nobody pays for that bandwidth, and once it will be deemed abused, we will all be in trouble -- last thing I want is GitHub asking me to find a host elsewhere. I might even raise the limit to 3 days if I judge it's for the best.
