### ISSUE TITLE
broken site: eksisozluk.com

### ISSUE THREAD

**Issue by ahmedtds** [uBlockOrigin/uAssets#6529]
site functions are broken when ublock is active

**Comment by mapx-** [comment]
> site functions are broken

Provide all the details / steps to reproduce the issue(s)

**Comment by ahmedtds** [comment]
> 
> 
> > site functions are broken
> 
> Provide all the details / steps to reproduce the issue(s)

it seems they fixed it themselves, it's ok now. things were broken for a while when they added some new ads, didn't think they would fix it for adblocker users so opened issue but there is no issue now so closing it.
