### ISSUE TITLE
Unblocked ad on web2.0calc.com

### ISSUE THREAD

**Issue by Hrxn** [uBlockOrigin/uAssets#653]
### URL(s) where the issue occurs

`https://web2.0calc.com/`

### Describe the issue

Unblocked ad on the center left with default settings for uBO

### Screenshot(s)

![2017-08-26_211424](https://user-images.githubusercontent.com/12064918/29744350-a67d2be4-8aa3-11e7-834d-666b3bcae32a.png)

### Versions

- Browser/version: Chrome 60.0.3112.113 (Official Build) (64-bit)
- uBlock Origin version: 1.13.8

### Settings

- Default Settings
- EasyList DE
- 

### Notes

This should work, I think:

```
web2.0calc.com##.text-center
```

**Comment by okiehsch** [comment]
`web2.0calc.com##script:inject(abort-on-property-read.js, doads)` is preferable in my opinion.

**Comment by Hrxn** [comment]
Yeah, sure. I did not properly investigate this. All I know is Selector syntax, and static filter syntax, like ABP etc.

Not sure about this script stuff, you probably need some tool for it?
To deal with all this obfuscated JS code..

**Comment by okiehsch** [comment]
No obfuscation, the sites uses a simple bait-script `https://web2.0calc.com/js/ads.js`.

**Comment by Hrxn** [comment]
`web2.0calc.com##script:inject(abort-on-property-read.js, doads)` 

Works as well, can confirm. I don't see it in the logger, but maybe that's expected?

> No obfuscation, the sites uses a simple bait-script `https://web2.0calc.com/js/ads.js`

How do you find these scripts in a straightforward way? I mean, some documents have lots of JS, how to find the right one?

**Comment by okiehsch** [comment]
> Works as well, can confirm. I don't see it in the logger, but maybe that's expected?

script:injext filters are not shown in the logger.

> How do you find these scripts in a straightforward way? I mean, some documents have lots of JS, how to find the right one?

In cases like this the use of a bait script is most common in my opinion, so you look for blocked first-party scripts. They are usually named ads , or advertising etc., to make sure that they are blocked.
