### ISSUE TITLE
Metacritic slideshows

### ISSUE THREAD

**Issue by rpodric** [uBlockOrigin/uAssets#6537]
### URL(s) where the issue occurs
```
https://www.metacritic.com/pictures/oscar-best-picture-predictions-2019
https://www.metacritic.com/pictures/november-2019-tv-preview
```
### Describe the issue

All slideshows on Metacritic (two examples provided above) require making an exception for the given URL (or the site in general, which is a bad idea to do) in order to progress in the slideshow.

### Versions

- Browser/version: Vivaldi 2.9.1705.41 (Chromium 78) and Firefox 78.0.1
- uBlock Origin version: 1.23.0 (and Extra 2.88 for Vivaldi)

### Settings

Using 6 of the 7 Built-in filters (except Experimental). Also using Fanboy's Annoyance List. But those are the only changes from defaults as I remember the defaults to be. The changes don't affect this issue.

### Notes

The cause seems to be some weird combination of EasyPrivacy, EasyList, and Peter Lowe's. Oddly, the problem doesn't seem to be with just one of them alone.

Thanks

**Comment by okiehsch** [comment]
````
||doubleclick.net/gpt/pubads_impl_rendering_$script,domain=metacritic.com,important
@@||doubleclick.net/gpt/pubads_impl$script,domain=metacritic.com
@@||doubleclick.net/tag/js/gpt.js$script,domain=metacritic.com
````
works on my end.

**Comment by rpodric** [comment]
Yes, looks like it's working in both browsers, thanks!
