### ISSUE TITLE
How to address 1st-party tracker blocking?

### ISSUE THREAD

**Issue by aeris** [uBlockOrigin/uAssets#6538]
Helle here!

Since friday, we hit a case of 1st-party tracking that seems to be unblockable.

This occurs on https://www.liberation.fr/, embedding a 1st-party tracker `f7ds.liberation.fr`, which point to a ugly tracking provider Eulerian via the CNAME `liberation.eulerian.net`.

This provider clearly states it provide unblockable tracker
![EJAeTXvWwAAqTPz](https://user-images.githubusercontent.com/51246/68544670-8b5c3680-03bd-11ea-94e1-5684430d16a5.png)
![EJAwd5wWkAAjmsN](https://user-images.githubusercontent.com/51246/68544673-8eefbd80-03bd-11ea-81ec-4a38399d4b43.png)

Seems Criteo starts to ask the same to their customer, with 1st-party tracking pointing to `*.dnsdelegation.io` subdomain.

In this case, it seems really difficult to block such tracker by tools like uBlock:

 * subdomain is mostly random (`f7ds.example.org`), even if we found some `ea.*` pattern
 * detection can sometime be done with CNAME resolution (to `*.eulerian.net` or `*.dnsdelegation.io`), but this is difficult to integrate to browser (those steps are internal to DNS client resolver)
  * IP filtering is not efficient, tracker provider can easily change IP without notifying it customers. CNAME change is more complex, but provider can generate quite a bunch on random subdomain in advance and ask it customer to change the subdomain in case of too high blocking (or proactively trigger a rotation each X days).

Do you have any way to detect then block such content from the browser?
The only (not so) efficient way I have at the moment is using DNS tools like PiHole to blacklist range of IP and CNAME pattern resolution (with regex, hostfile not usable here). And even this way, it doesn't cover all the possible case… Even tools like µMatrix seems totally inefficient on such tracker…

**Comment by llacb47** [comment]
Maybe a scriplet? Are there other sites on which this tracking is used?

**Comment by aeris** [comment]
With DNS analysis, we found at least those customers.
Acadomia, Attractiv World, Conforama, Carrefour, Center Parks, Celio, Corsair, Devialet, Leclerc, Easy Voyage, La Redoute, Futuroscope, Française des Jeux, FNAC, Look Voyage, Lafuma, Malakoff Médéric, Michelin, Monoprix, Numericable, Office Dépôt, Ooreka,  Photobox, Petit Bateau, Pixmania, PMU, Tam Tam, Promofarma, Quiksilver, Skoda, Smartbox, Locasun, Vente Unique, Voyage Privé, Voyages SNCF, Virgin Mobile, and so more (700+ domains found).
It doesn't say it's currently on production, but DNS delegation and CNAME are ready to be deployed.

**Comment by aeris** [comment]
At least one already in production on oui.sncf
![2019-11-10T15-02-30](https://user-images.githubusercontent.com/51246/68545221-e3496c00-03c2-11ea-93c0-c2611e138f84.png)
![2019-11-10T15-03-56](https://user-images.githubusercontent.com/51246/68545231-fb20f000-03c2-11ea-8f72-91cacb151633.png)

**Comment by llacb47** [comment]
@aeris add:

`liberation.fr,officedepot.fr,oui.sncf##+js(acis, document.createElement, 3600000)`

**Comment by okiehsch** [comment]
> Do you have any way to detect then block such content from the browser?

We can disable the inline-script that triggers the 1st party scripts
![image](https://user-images.githubusercontent.com/16838044/68551891-8fb23f00-0411-11ea-8bef-6260720b204e.png)

I added 
`liberation.fr,officedepot.fr,oui.sncf##+js(acis, document.createElement, '.js')`
to `uBO-privacy`.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/a988faf5017b3369e3b58d1da239d6e91ac69df8

**Comment by aeris** [comment]
Next step… :rage: 
Libération change it config to host tracker directly with a A/AAAA instead of a CNAME to Eulerian…
And hide Eulerian behind a proxy…
![2019-11-26T09-49-47](https://user-images.githubusercontent.com/51246/69613617-239b2200-1032-11ea-9757-e05399fdc1ef.png)
![2019-11-26T09-50-36](https://user-images.githubusercontent.com/51246/69613650-36155b80-1032-11ea-9f13-c3a1812c2f6b.png)

**Comment by guillaumef** [comment]
This domain is owned by a https://uniregistry.com ... a registrar reseller.
The domain is for sale...

$ dig +short aeris.liberation.net
69.172.201.153
It is called a wildcard ... 
*.liberation.net IN A 69.172.201.153

You made a typo and you have a lot of imagination, conspiracy theory ?
Eulerian is using f7ds.liberation.fr and nothing changed.

**Comment by aeris** [comment]
Oh my god, I miss the domain :sob: Sorry… :fearful:

**Comment by uBlock-user** [comment]
`https://trackingthetrackers.com/`

Should help filterlist maintainers collecting/checking domains there before adding.
