### ISSUE TITLE
pinpng.com

### ISSUE THREAD

**Issue by NubN** [uBlockOrigin/uAssets#6539]
### URL(s) where the issue occurs

`https://www.pinpng.com/picture/hmmbThh_neon-frame-ftestickers-lilac-hd-png-download/`

### Describe the issue

Impossible download images in the website.

The "Free Download" button not working with uBO enabled.

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.23.0]

### Notes

other site:

`https://www.pngfind.com/`

`https://www.pngfind.com/mpng/ibRhbho_memes-para-stickers-png-png-download-surprised-pikachu/`

**Comment by mapx-** [comment]
@ryanbr
