### ISSUE TITLE
torrentdownload.ch

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#654]
### URL(s) where the issue occurs

`https://www.torrentdownload.ch/7C1EE7C55E520BEF0CF5A34FCC68A8FB9D304AA2/kali-linux-2017-1-i386`
`https://www.torrentdownload.ch/search?q=tv`

### Describe the issue

First link: Top three options to download: only middle one (iTorrents) appears to be real; Direct Download and Torrent VPN are fake/ads. Fake/ads: Stream: Download torrents safely and Anonymously with Free Torrent VPN by SpyOFF. Get SpyOFF Now and Stream: Watch Free Movies Online @ Movie4u
Second link: sponsored

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/29753925-45111838-8b49-11e7-9fbb-83697438b5c1.png)
![image](https://user-images.githubusercontent.com/12802056/29753929-533e12b2-8b49-11e7-9d7a-191d208ce375.png)

### Versions

- Browser/version: [Chrome 60]
- uBlock Origin version: [1.18.8]

### Settings

Default

**Comment by mapx-** [comment]
`torrentdownload.ch##[href^="/redir."]
torrentdownload.ch##[href="https://goo.gl/h0rNAu"]
torrentdownload.ch##TR:has-text(Stream:)`

**Comment by ghajini** [comment]
Popunders
Crap xhrs

`www.torrentdownload.info`
