### ISSUE TITLE
web.de, gmx.net, gmx.at

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#6541]
### URL(s) where the issue occurs

`https://web.de/magazine/wissen/natur-umwelt/insektenschwund-deutschland-stille-sterben-insekten-34145488`
`https://www.gmx.net/magazine/wissen/natur-umwelt/gift-kegelschnecke-schmerztherapie-helfen-34164788`
`https://www.gmx.at/magazine/gesundheit/kinder-leiden-haeufig-kopfschmerzen-34166518`

### Describe the issue

Video get blocked

### Screenshot(s)

<img width="1580" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/68549213-240ea880-03f6-11ea-8316-c0f5d110ccff.PNG">

### Versions

- Browser/version: Firefox 70.0.1
- uBlock Origin version: v1.23.0

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3828865/Settings.txt)

**Comment by JobcenterTycoon** [comment]
Video ads on `https://www.golem.de/`

`golem.de##+js(json-prune, enabled, testhide)` will fix that

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/4440a107e74b1b1649d918f1491eba08d417617a

**Comment by JobcenterTycoon** [comment]
Video ads on `https://winfuture.de/videos/Internet/URL-Shortener-Wie-man-hinter-verkuerzte-Links-schauen-kann-19046.html`

`winfuture.de##+js(json-prune, enabled, testhide)` will fix that

**Comment by JobcenterTycoon** [comment]
video ads are back again

**Comment by mapx-** [comment]
test
`*$media,redirect=noopmp3-0.1s,domain=web.de|gmx.net|gmx.at,3p`

**Comment by JobcenterTycoon** [comment]
doesnt work

**Comment by lain566** [comment]
@JobcenterTycoon  These filters should work for you.

```
gmx.*,web.de#@#+js(json-prune, enabled, testhide)
gmx.*,web.de##+js(json-prune, enabled, force_disabled)
```

**Comment by JobcenterTycoon** [comment]
Yes it works, thank you. 
Here a list with more sites that are use the same ad system:

`t-online.de##+js(json-prune, enabled, force_disabled)`
`winfuture.de##+js(json-prune, enabled, force_disabled)`
`golem.de##+js(json-prune, enabled, force_disabled)`
`giga.de##+js(json-prune, enabled, force_disabled)`

**Comment by JobcenterTycoon** [comment]
Video Ads are back again

**Comment by JobcenterTycoon** [comment]
Video ads on `focus.de`

**Comment by okiehsch** [comment]
I can't reproduce with Chromium or Firefox using a german IP.
Example links;
````
https://www.gmx.net/magazine/panorama/australische-buschfeuer-rettet-koala-flammen-34196752
https://video.golem.de/games/23813/razer-blade-stealth-13-test.html
````

**Comment by okiehsch** [comment]
I can reproduce video ads at ` focus.de`.
`focus.de##+js(json-prune, enabled, force_disabled)`
fixes the issue on my end.
Example link:
````
https://www.focus.de/wissen/mensch/deutschland-die-suche-nach-toten-soldaten_id_11399140.html
````

**Comment by JobcenterTycoon** [comment]
I get only ads in firefox. The first video have no ads but when i switch to another one i get video ads

**Comment by okiehsch** [comment]
I can't reproduce. @lain566 can you reproduce?

@JobcenterTycoon does the filter for `focus.de` work on your end?

**Comment by JobcenterTycoon** [comment]
yes

**Comment by JobcenterTycoon** [comment]
Ok now it works and i get less video ads on all sites, after a few more tests i know its only a rare chance to get Video ads (100% chance without filter, 10% with filter), so you can ignore this

**Comment by lain566** [comment]
It's strange for me, I could reproduce ads, but now I don't.
for example, I could reproduce ads on these sites, now the player is broken for me with Firefox
```
https://www.kino.de/film/captain-marvel-2019/
https://www.spieletipps.de/artikel/9902/1/
```

**Comment by okiehsch** [comment]
I can reproduce ads on both sites.
````
kino.de,spieletipps.de##+js(json-prune, enabled, force_disabled)
````
works on my end.

**Comment by lain566** [comment]
@okiehsch  Yes, that fixed the player for me
Can you reproduce pre roll ads on this site?
`https://www.videogameszone.de/Bless-Spiel-19102/News/mmorpg-steam-geld-zurueck-1332270/`

**Comment by okiehsch** [comment]
Yes, same filter works for me.
`videogameszone.de##+js(json-prune, enabled, force_disabled)`

**Comment by lain566** [comment]
@okiehsch Can you check these sites?

```
https://www.pcgameshardware.de/Borderlands-3-Spiel-54615/Videos/Trailer-DLC-Moxxis-Ueberfall-Handsome-Jackpot-1337576/
https://www.pcgames.de/Star-Wars-Episode-9-Film-259018/News/Neuer-Werbespot-zeigt-weitere-Szenen-aus-dem-Film-1337606/
https://www.gamesaktuell.de/Alien-Isolation-Spiel-2938/News/nintendo-switch-release-horror-1337624/
https://www.buffed.de/World-of-Warcraft-Classic-Spiel-42973/News/PvP-Schlachtfelder-und-Elementar-Invasionen-im-Dezember-1337528/
```

I can't reproduce pre roll ads on `videogameszone.de`

**Comment by okiehsch** [comment]
I can only reproduce pre roll ads on `gamesaktuell.de`. The rest has the same "issue" you described.
"the video stops for a few seconds, but then the playback of the video continues normal"

**Comment by lain566** [comment]
Before I could reproduce ads from all those sites that I mentioned https://github.com/uBlockOrigin/uAssets/issues/6541#issuecomment-559364610
but I didn't add a solution, because I couldn't reproduce ads anymore

**Comment by okiehsch** [comment]
> Before I could reproduce ads from all those sites that I mentioned #6541 (comment)
but I didn't add a solution, because I couldn't reproduce ads anymore

I assume the solution is the same filter `##+js(json-prune, enabled, force_disabled)`?
Adding it does fix the "video stops for a few seconds" issue, so if you want to add it for all sites that have this minor issue. 👍 
Probably something is wrong on their end and the ads will reappear soon enough

**Comment by lain566** [comment]
When I could reproduce ads, this filter `##+js(json-prune, enabled, force_disabled)` didn't work for me.
especially on this site https://github.com/uBlockOrigin/uAssets/issues/6541#issuecomment-559362411 and `kino.de` and now it seems to work.

I can add  `##+js(json-prune, enabled, force_disabled)`  I will add it at night.

**Comment by Procyon-b** [comment]
While using gmx.net webmail, I've seen `+js(json-prune, enabled, force_disabled)` appearing in the logger.

The current filter is:
```
! https://github.com/uBlockOrigin/uAssets/issues/6541
focus.de,gamesaktuell.de,gmx.*,kino.de,spieletipps.de,videogameszone.de,web.de##+js(json-prune, enabled, force_disabled)
```

This is unnecessary on that site.

Could you fix this by refining the domain and use `www.gmx.net` in the filter instead of `gmx.net`.
The filter target is too wide. It's like shooting at all `.com` when you are aiming at `github.com`.
And narrowing it to `www.gmx.net/magazine` could even be better (but that, I'm not sure).

**Comment by krystian3w** [comment]
If it does not spoil the web version of the mail, then uAssets does not restrict the operation of filters.

**Comment by Procyon-b** [comment]
I've noticed a weird thing with this url.
`https://www.gmx.net/magazine/wissen/natur-umwelt/gift-kegelschnecke-schmerztherapie-helfen-34164788`

For the test I've disabled all "uBlock filters" and only enabled the following lists:
```
Adblock Warning Removal 
EasyList
EasyPrivacy
Malware Domain List
Malware domains
Fanboy’s Social Blocking List
Peter Lowe’s Ad and tracking server list
FRA: EasyList Liste FR
```
And the video plays correctly.

Once I add `DEU: EasyList Germany` that's when the video doesn't play.
If I look at the logger, the only filter applied from DEU is a cosmetic filter.

**Comment by krystian3w** [comment]
`Deu: EasyList` no support `##+js(` and no fix issues with anti-adblock (I suppose this is anti-adblock in player).

**Comment by Procyon-b** [comment]
@krystian3w Apparently that something the list is doing that is breaking the video. And it's still broken with "uBlock" lists enabled (cache purged and reloaded).

**Comment by krystian3w** [comment]
Also site maybe again change someting in `json` - strange webmasters.

**Comment by Procyon-b** [comment]
@krystian3w 
DEU and FR aren't playing along

**Comment by krystian3w** [comment]
@smed79  imo also no fix anti-adblock in FR list.

**Comment by Procyon-b** [comment]
What I can tell is that if I enable DEU and FR, the above fix doesn't work. The 2 lists are not playing well together.

Don't bother with that. I'm not a user of the DEU list.  ;)

**Comment by mapx-** [comment]
a bad filter from Liste FR
add and test:
`/homad-global-$badfilter`

**Comment by Procyon-b** [comment]
@mapx- The weird thing is that the url (homad) is not even loaded by the website if DEU is not combined with FR. FR alone, no "homad".
They are probably using alternatives for storing "configs".

**Comment by mapx-** [comment]
I get `homad` on my end (with uBo filters + FR + DE enabled)

**Comment by Procyon-b** [comment]
Yes, and that's the culprit in that situation (FR+DE). But when it's FR alone, the url `...naws.com/homad-global-configs...` is not accessed.
Anyways, thanks, but it wasn't needed for me.

I understand better now, why all those ublock lists are useful to fix other lists. The more (lists) you add, the more potentials conflicts you have.  :)

**Comment by mapx-** [comment]
yeah, there are "normal" issues with the general lists and there are issues with regional lists like Liste FR (the maintainer added a lot of generic and regex filters not only for french pages)

**Comment by JobcenterTycoon** [comment]
Video ads on `https://www.tvnow.de/serien/verdachtsfaelle-248/2019-11/episode-46-schluesseldienst-laesst-fremden-in-die-wohnung-2464258`

**Comment by JobcenterTycoon** [comment]
i still get video ads on `web.de`, `gmx.*`, `pcgameshardware.de`, `pcgames.de`, `gamesaktuell.de` and `buffed.de`

**Comment by krystian3w** [comment]
Webmasters follow commits or the new scriptlet is detected by the tracking system on the pages too fast (server logs).

**Comment by JobcenterTycoon** [comment]
video ads are back again on `t-online.de`

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/86de3f9b60d1513c2971cf4c0dcb568d4eec3078

**Comment by JobcenterTycoon** [comment]
Video ads back again on `web.de` `gmx.*` `golem.de` `pcgameshardware.de` `videogameszone.de` `pcgames.de` `gamesaktuell.de` `buffed.de` `t-online.de` and `golem.de`

looks like they change every day the config to go avoid that form of blocking

**Comment by okiehsch** [comment]
Does
`example.com##+js(aopr, CustomEvent)`
work for you with all sites?
Before I add that filter we would have to be sure that it does not break anythin vital on those sites.

**Comment by JobcenterTycoon** [comment]
it breaks the videoplayer on `spieletipps.de` and `kino.de`

**Comment by okiehsch** [comment]
How about
`kino.de,spieletipps.de##+js(aopr, CustomEvent)`?
for those two sites?

**Comment by JobcenterTycoon** [comment]
Yes you can add this

**Comment by Procyon-b** [comment]
@mapx- , your comment & commit: https://github.com/uBlockOrigin/uAssets/issues/6541#issuecomment-559876625
The issue with the "easylist liste FR" has been fixed [here](https://forums.lanik.us/viewtopic.php?f=91&t=43944) by expanding an exception filter. I think it is safe to remove the badfilter.

**Comment by mapx-** [comment]
thx

**Comment by JobcenterTycoon** [comment]
I get video ads on `https://www.golem.de/`

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0b0aadec9c67912916c46397b88c925243e00e00
Fixed for chromium/chrome/edge. 

Still needs a working Firefox fix that does not break the video....

**Comment by lain566** [comment]
@JobcenterTycoon Does this filter work for you?
`golem.de##+js(set, SwfVideo.pushRmp3Pi, null)`

**Comment by okiehsch** [comment]
Works for me using Firefox.

**Comment by lain566** [comment]
The filter I added for `tvnow` https://github.com/uBlockOrigin/uAssets/commit/169af97a4ce64c9d285f4a7aa726d7ebb9030c28  should also work for `n-tv.de`

**Comment by okiehsch** [comment]
Yes. Thanks, I tried in vain to find a working json-prune filter last night.

**Comment by JobcenterTycoon** [comment]
Video ads on `https://www.fitforfun.de/abnehmen/diaeten/grundumsatz-wie-funktioniert-abnehmen_aid_10400.html`

**Comment by JobcenterTycoon** [comment]
Video ads on `https://www.stern.de/digital/webvideo/fake-or-no-fake/duschende-ratte---suesser-internet-hit-oder-traurige-geschichte--8377780.html`

**Comment by lain566** [comment]
I'm using a German IP and no video appears.

**Comment by JobcenterTycoon** [comment]
oh ... breakage here whitelist `privacy-mgmt.com` to see the video (forgot to report sorry)

**Comment by lain566** [comment]
@okiehsch Should we badfilter it or add an exception filter for  `privacy-mgmt.com`?

**Comment by okiehsch** [comment]
It's a Firefox only issue as far as I can see. I added an exception.

**Comment by JobcenterTycoon** [comment]
Video dissapear on `https://www.giga.de/`

**Comment by mapx-** [comment]
please provide example links

**Comment by JobcenterTycoon** [comment]
`https://www.giga.de/downloads/windows-10/tipps/windows-10-zuruecksetzen-auf-werkseinstellungen/`

**Comment by JobcenterTycoon** [comment]
the video still dissapear after i try to play

**Comment by mapx-** [comment]
do you get this exception in the logger ?

`@@||cdn.privacy-mgmt.com/wrappermessagingwithoutdetection.js$script,domain=giga.de`

**Comment by lain566** [comment]
Fixed. https://github.com/uBlockOrigin/uAssets/commit/7c8023d5ff52bdea1b973f8790c0c9a4903f5333

**Comment by JobcenterTycoon** [comment]
Video ads on golem.de `https://www.golem.de/news/gaming-kfc-stellt-konsole-mit-haehnchen-warmhaltekammer-vor-2012-153016.html`

And typo on line 143 between `finya.de` and `frankfurter-wochenblatt.de`
<img width="82" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/102998702-fcaa6a80-4527-11eb-98de-a6983bae8211.PNG">

**Comment by JobcenterTycoon** [comment]
Video ads are back on `giga.de` (Video on the startpage)

**Comment by mapx-** [comment]
maybe  `giga.de##+js(no-fetch-if, damoh)` ?

**Comment by JobcenterTycoon** [comment]
Very good

**Comment by JobcenterTycoon** [comment]
Video ads on `https://www.wetter.de/cms/die-naechste-tropennacht-temperaturen-bleiben-oft-ueber-20-grad-4435004.html`

When i stop the video and try to continue a ad starts

**Comment by JobcenterTycoon** [comment]
@lain566 do you know any fix for the `wetter.de` issue ?

**Comment by lain566** [comment]
Actually we have an internal discussion about this issue, but I'm not sure if this is going to be fixed in `uBO filters`

**Comment by krystian3w** [comment]
@montza fyi

**Comment by JobcenterTycoon** [comment]
There are damoh video ads on `https://www.autobild.de/artikel/bmw-520i-e34-sechszylinder-handschalter-rostfrei-tuev-neu-h-kennzeichen-ebay-21131623.html`

**Comment by budear** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/114869

anti-adb (encountered while using Tor + uBO)

**Comment by JobcenterTycoon** [comment]
Does anyone get damoh ads back on varios domains? Examples:

`https://www.stern.de/panorama/raetsel--diese-rechnung-besteht-aus-symbolen---wissen-sie-die-loesung--31894762.html`
`https://www.computerbild.de/artikel/cb-Tipps-Software-Office-Service-Pack-kostenlos-20085981.html`
`https://www.golem.de/news/prehistoric-planet-danke-apple-fuer-so-grandiose-dinosaurier-2205-165645.html`

**Comment by okiehsch** [comment]
Does 
`example.com##+js(no-xhr-if, damoh)`
work for all domains?

**Comment by mapx-** [comment]
working fine on my side, but I get no ads on golem

**Comment by okiehsch** [comment]
Me neither, that's why I asked. I can reproduce on the other two provided links.

**Comment by JobcenterTycoon** [comment]
Works fine but the video stops so a user need to click 2 times to play the video. Maybe it can be defused.

I will check all known damoh domains to catch all ads

**Comment by JobcenterTycoon** [comment]
Catched and fixed unblocked damoh ads:

```
https://www.autobild.de/artikel/elektroauto-bmw-kia-mercedes-hyundai-audi-skoda-mazda-smart-tesla-opel-volvo-vw-toyota-20921697.html
https://www.computerbild.de/artikel/cb-Tipps-Software-Office-Service-Pack-kostenlos-20085981.html
https://www.golem.de/news/prehistoric-planet-danke-apple-fuer-so-grandiose-dinosaurier-2205-165645.html
https://www.desired.de/liebe/hochzeit/eiserne-hochzeit-geschenke-und-sprueche/
https://www.giga.de/
https://www.stern.de/panorama/raetsel--diese-rechnung-besteht-aus-symbolen---wissen-sie-die-loesung--31894762.html
https://www.t-online.de/nachrichten/ausland/id_92266828/ukraine-krieg-diese-raketenwerfer-sollen-putins-truppen-stoppen-video.html
```

**Comment by okiehsch** [comment]
Can we remove the existing filters dealing with damoh video ads on those sites?
For example
````
autobild.de##+js(no-fetch-if, damoh.autobild.de)
computerbild.de##+js(no-fetch-if, damoh.computerbild.de)
`````

**Comment by JobcenterTycoon** [comment]
Yes it works fine without

**Comment by okiehsch** [comment]
Keep your new merged filter and remove the obsolete filters.

**Comment by JobcenterTycoon** [comment]
@Yuki2718 @AdamWr I get damoh ads on Adguard too on these sites:


```
https://www.autobild.de/artikel/elektroauto-bmw-kia-mercedes-hyundai-audi-skoda-mazda-smart-tesla-opel-volvo-vw-toyota-20921697.html
https://www.desired.de/liebe/hochzeit/eiserne-hochzeit-geschenke-und-sprueche/
https://www.giga.de/
https://www.t-online.de/nachrichten/ausland/id_92266828/ukraine-krieg-diese-raketenwerfer-sollen-putins-truppen-stoppen-video.html
https://www.videogameszone.de/Bless-Spiel-19102/News/mmorpg-steam-geld-zurueck-1332270/
https://www.pcgameshardware.de/Borderlands-3-Spiel-54615/Videos/Trailer-DLC-Moxxis-Ueberfall-Handsome-Jackpot-1337576/
https://www.pcgames.de/Star-Wars-Episode-9-Film-259018/News/Neuer-Werbespot-zeigt-weitere-Szenen-aus-dem-Film-1337606/
https://www.gamesaktuell.de/Alien-Isolation-Spiel-2938/News/nintendo-switch-release-horror-1337624/
https://www.buffed.de/World-of-Warcraft-Classic-Spiel-42973/News/PvP-Schlachtfelder-und-Elementar-Invasionen-im-Dezember-1337528/
https://www.kino.de/film/captain-marvel-2019/
```

**Comment by Yuki2718** [comment]
Need German (or maybe EU) IP. On `https://www.desired.de/liebe/hochzeit/eiserne-hochzeit-geschenke-und-sprueche/` existing rule `||damoh.*.de^$redirect=nooptext,domain=stern.de|desired.de|pcgames.de|t-online.de|vox.de|giga.de|spieletipps.de|wetter.de|golem.de` seems to be working.

**Comment by Yuki2718** [comment]
Added missing domain but I don't know the reason for NOT_PLATFORM. Also I think they can generically be blocked by rules like
```
://ssl.1.damoh.$xhr,redirect=nooptext
://ssl.2.damoh.$xhr,redirect=nooptext
://ssl.3.damoh.$xhr,redirect=nooptext
```

**Comment by JobcenterTycoon** [comment]
@Yuki2718 the Adguard filter works fine - except on `giga.de` the video gets blank and just the audio get played

Thats also why i needed to remove the general filter because it breaks the video on `web.de` and a few more

**Comment by Yuki2718** [comment]
Yes...confirmed breakage. The rule worked in the first few domain so I wrongly assumed it's all okay.
@AdamWr Sorry for bothering you but can you check the rest domain I added? I don't have time any more.

**Comment by okiehsch** [comment]
Yes.

**Comment by JobcenterTycoon** [comment]
No

**Comment by JobcenterTycoon** [comment]
@mapx-  does this work

```
||js.stroeermediabrands.de/metaTag$script,domain=giga.de,redirect=noopjs
||damoh.giga.de^$script,1p,redirect=noopjs
giga.de#@#+js(set-constant, CustomEvent, noopFunc)
```

**Comment by mapx-** [comment]
no .. I get alpenmilch werbung after 4-5 tests

**Comment by JobcenterTycoon** [comment]
Pretty sure they rotate. At the beginning i get a media query with the ad and after a few reloads i get the `damoh.giga.de` script which can be blocked with the filter i mentioned without breakage

**Comment by JobcenterTycoon** [comment]
@okiehsch can you take a look on the damoh stuff on `giga.de`? Im unable to find a fix. Example: `https://www.giga.de/video/partner-gefunden-e-autos-von-sony-kommen-giga-insights/`

**Comment by okiehsch** [comment]
`giga.de##+js(no-xhr-if, stroeermediabrands)`
gets rid of the ads on my end but there is still some time until the video starts after clicking play.

**Comment by okiehsch** [comment]
Strike that now the ads still play....

**Comment by JobcenterTycoon** [comment]
So a new `damoh-defuser.js` is needed because the old one is outdated and not getting used anymore @gorhill

**Comment by okiehsch** [comment]
A german IP is needed to reproduce.

**Comment by gorhill** [comment]
This works?

    giga.de##+js(json-prune, ad_fallback)

**Comment by okiehsch** [comment]
It works sometimes but not consistently on my end.
Test with the "Top Videos" section on the homepage, you have to scroll down a little bit.

**Comment by JobcenterTycoon** [comment]
Works fine for me

**Comment by okiehsch** [comment]
Does the real video start immediately on your end or do you see a black screen first?

**Comment by okiehsch** [comment]
With Firefox
![image](https://user-images.githubusercontent.com/16838044/188585338-718ce536-1b0f-4fd7-9c15-1a3e3fc603d2.png)

**Comment by JobcenterTycoon** [comment]
I see a black screen first

**Comment by okiehsch** [comment]
Interesting, that what I see most of the time but at your example link
`https://www.giga.de/video/partner-gefunden-e-autos-von-sony-kommen-giga-insights/`
I get the disney ad in my screenshot every time.

Well, the filter is still a massive improvement.

**Comment by JobcenterTycoon** [comment]
Without the filter i get this

<details>
<summary> screenshot </summary>

<img width="641" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/188616265-3a3eea7f-db81-4c86-9014-dd274c1b5a08.PNG">

</details>

First they ask what ad i want and when i select none it plays a random one after 10 seconds. With the filter i habe a second a blank screen and after this the real video plays

What i know is that they change the behavior when the user often visit the site/reload many times. I test every time with a clear browser

**Comment by JobcenterTycoon** [comment]
@okiehsch @gorhill

`giga.de##+js(json-prune, ad_fallback)` doesn’t work anymore. When i read the old comments `json-prune` never works for a longer time https://github.com/uBlockOrigin/uAssets/issues/6541#issuecomment-560972095 https://github.com/uBlockOrigin/uAssets/issues/6541#issuecomment-561761634
