### ISSUE TITLE
prostream.to

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6544]
### URL(s) where the issue occurs

`https://prostream.to/diuhnm0gbg3y.html`

### Describe the issue

Popup ads

### Versions

- Browser/version: opera browser /firefox stable
- uBlock Origin version: 1.23

### Settings

- uBO's default settings

**Comment by ghajini** [comment]
Popup ads

`prostream.to` now redirect to another domain `procdnvids.net`

`https://procdnvids.net/t7h5edbyky1l`

**Comment by ghajini** [comment]
Now it redirects to `https://storageplay.net/`
Page is compromised?

**Comment by okiehsch** [comment]
Yes, looks like it. I will add all three domains to the badfilter list.
