### ISSUE TITLE
Aliexpress does not work properly with the enabled annoyances list

### ISSUE THREAD

**Issue by ediowar** [uBlockOrigin/uAssets#6551]
### URL(s) where the issue occurs

`https://ru.aliexpress.com/`

### Describe the issue

Aliexpress does not work properly with the enabled annoyances list

### Screenrecord

https://drive.google.com/open?id=1qOizO1eq9FdlLpwPPcUVe0-8ysdCHYuK

### Versions

- Browser/version: Chromium Version 78.0.3904.70 (Official Build) Built on Ubuntu
- uBlock Origin version: development build v1.23.1b11

### Settings

- annoyances list enabled

### Notes

Adding a filter restores site functionality:
`aliexpress.com##.ui-newuser-layer-dialog.ui-window-transition.ui-window-normal.ui-window`

**Comment by krystian3w** [comment]
#5283 

#6184

**Comment by ediowar** [comment]
Is the annoyances list on?

**Comment by krystian3w** [comment]
Yes with uBO Annoyance, guilty is old:
https://github.com/uBlockOrigin/uAssets/blob/f0fa7d418cc11b276f5b8c609715aebb048b6cf9/filters/annoyances.txt#L2031


`aliexpress.com#@#.close-layer:xpath(..)`

IMO any pop-up possible have ❌, maybe better base on class `ui-newuser-layer-dialog` if now is stable.

**Comment by ediowar** [comment]
Try to turn off POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda

**Comment by krystian3w** [comment]
Poland no remove this pop-up - I aded in other Polish project "`Polskie Filtry Elementów Irytujących`": https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/b3cb9fa8874a59e8b69d0b945b93cb9324bdf901

**Comment by ediowar** [comment]
Which pop-up? 
![Screenshot from 2019-11-12 02-29-18](https://user-images.githubusercontent.com/44164186/68631223-1262f900-04fb-11ea-877b-04735926abe3.png)

**Comment by krystian3w** [comment]
That:

![Screenshot_20191112-065638](https://user-images.githubusercontent.com/35370833/68645864-b9ef2400-0519-11ea-8952-3f05e6e31f63.png)

**Comment by ediowar** [comment]
I can not reproduce. Place a link to Google Drive with screenrecord. At the same time, show the settings there.

**Comment by mapx-** [comment]
@ediowar could you provide the steps to get the issue ? I don't really understand from the video

**Comment by ediowar** [comment]
Links that are in the area `aliexpress.com##.ui-newuser-layer-dialog.ui-window-transition.ui-window-normal.ui-window` become unclickable. [https://drive.google.com/file/d/1SNy8Ok93_HxEUOd2kt0UsgzvtxqhF4nu](https://drive.google.com/file/d/1SNy8Ok93_HxEUOd2kt0UsgzvtxqhF4nu)

**Comment by ediowar** [comment]
@mapx-, please, add domain ru to fixes [#5283](https://github.com/uBlockOrigin/uAssets/commit/6022674f921d481ae73d297bb4f585a0cf2bf3d1) [#6184](https://github.com/uBlockOrigin/uAssets/commit/5bfea96f5be37c053db3618346987341f27da1bb) [#6551](https://github.com/uBlockOrigin/uAssets/commit/d1048ae296b63120441d0de1efba14b199eba2fe) in annoyances list.

**Comment by mapx-** [comment]
meaning `aliexpress.com,aliexpress.ru` ?

**Comment by ediowar** [comment]
aliexpress.com,ru##.close-layer:xpath(..)

**Comment by ediowar** [comment]
Why com?
! https://github.com/uBlockOrigin/uAssets/issues/5283
aliexpress.com,ru##.close-layer:xpath(..)
aliexpress.com,ru##.ui-mask
! https://github.com/uBlockOrigin/uAssets/issues/6184
aliexpress.com,ru##.next-overlay-wrapper:has(.newuser-container)
aliexpress.com,ru##body:style(overflow: auto !important; padding: 0 !important;)
! https://github.com/uBlockOrigin/uAssets/issues/6551
aliexpress.com,ru##.ui-newuser-layer-dialog.ui-window-transition.ui-window-normal.ui-window

**Comment by llacb47** [comment]
@mapx- you added `aliexpress.com` again

**Comment by krystian3w** [comment]
no better `*`?

Maybe other countries use "regional" TLD instead of "`.com`" or sudomain "`XX.aliexpress.com`"?

**Comment by ediowar** [comment]
> Maybe other countries use "regional" TLD instead of "`.com`" or sudomain "`XX.aliexpress.com`"?

Aliexpress only for Russia uses "regional" TLD. The rules for the domain also apply to the subdomain.

**Comment by ediowar** [comment]
@krystian3w, found Aliexpress's bug.
After changing the language to Polish at the top of the page, it is impossible to change the language.

Steps to Reproduce
1. Go to any Aliexpress domain exept pl.aliexpress.com
2. Not sign in, change language to Polish
3. At the top of the page, change the language to any other.

Expected behavior:
The language is any other.

Actual behavior:
The language is Polish.

Chromium version 80.0.3987.163 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
Note: the domain pl.aliexpress.com has the http protocol, not https, as when changing the language to Polish at the bottom of the page (AliExpress Multi-Language Sites.)
You can report a bug to https://home.aliexpress.com/survey.htm
