### ISSUE TITLE
cutlinks.pro has anti-adblock

### ISSUE THREAD

**Issue by thienha1** [uBlockOrigin/uAssets#6553]
### URL(s) where the issue occurs
`https://cutlinks.pro/CBwchmby7bt`
`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue
This site has anti-adblocker 
[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)
[https://i.imgur.com/1yW6D68.png](url)
[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: 78.0.3904.87
- uBlock Origin version: 1.0.0.130

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by okiehsch** [comment]
> uBlock Origin version: 1.0.0.130

You are not using `uBlock Origin`, the site works fine on my end.

**Comment by uBlock-user** [comment]
That's [Nano Adblocker](https://github.com/NanoAdblocker/NanoCore/releases/tag/v1.0.0.130)

**Comment by okiehsch** [comment]
Thx, can you reproduce?

**Comment by uBlock-user** [comment]
@okiehsch you can still fix the countdown timer though -- `cutlinks.pro##+js(nano-sib, /.?/, 1000, 0.01)`

**Comment by uBlock-user** [comment]
> Thx, can you reproduce?

Already fixed by uBlock Filters with `cutlinks.*##+js(aopr, app_vars.force_disable_adblock)` as per the logger.

**Comment by okiehsch** [comment]
> @okiehsch you can still fix the countdown timer though -- `cutlinks.pro##+js(nano-sib, /.?/, 1000, 0.01)`

That resuts in a "bad request" on my end.

**Comment by uBlock-user** [comment]
Ah, yes happens to me too. So this is a non-issue. OP should report this to Nano's repository here on out.

**Comment by okiehsch** [comment]
@jspenguin2017 fyi in case you can reproduce.

**Comment by jspenguin2017** [comment]
Fixed.
