### ISSUE TITLE
hna.de Video blocked

### ISSUE THREAD

**Issue by AlleSchonWeg** [uBlockOrigin/uAssets#6554]
### URL(s) where the issue occurs

`https://www.hna.de/sport/fussball/doppelpass-sport1-uli-hoeness-fc-bayern-muenchen-anruf-beschwerde-bizarr-zr-13208325.html`

### Describe the issue

Video get blocked. Messsage:
"**AdBlocker erkannt**
Sie nutzen ein werbefinanziertes Angebot. In Ihrem Browser ist ein AdBlocker installiert, der Werbung blockiert. Bitte deaktivieren Sie den AdBlocker, um die Videos ansehen zu können."

### Versions

- Browser/version: Chrome 78.0.3904.87 (Offizieller Build) (64-Bit)
- uBlock Origin version: 1.23.0

**Comment by okiehsch** [comment]
Have you updated your filter list? I can't reproduce an anti adblocker warning.

**Comment by AlleSchonWeg** [comment]
Ups. Sorry, I updated again. Now it works.

**Comment by lain566** [comment]
@okiehsch Can you reproduce anti-adblock warning?

**Comment by okiehsch** [comment]
No.
![image](https://user-images.githubusercontent.com/16838044/100529148-ad04a780-31e4-11eb-8b60-e12fcdb2cc26.png)

**Comment by lain566** [comment]
Have you tried it with uBO dev?

**Comment by okiehsch** [comment]
The screenshot was taken with 1.31.1b6.

**Comment by okiehsch** [comment]
OK, with 1.31.1b8 after clicking play I get
![Uploading image.png…]()

**Comment by lain566** [comment]
This Easylist filter does not appear in the logger
`@@||imasdk.googleapis.com/js/core/bridge*.html$subdocument,domain=~spotify.com`

**Comment by okiehsch** [comment]
Yes, looks like a bug in the dev version.
@gorhill

**Comment by okiehsch** [comment]
If I add
`@@||imasdk.googleapis.com/js/core/bridge*.html$subdocument
to my filter list uBO  does not apply it according to the logger.
If I add `@@||imasdk.googleapis.com/js/core/*$subdocument
it is applied.

**Comment by gorhill** [comment]
I am not at the computer at the moment but I suspect it's caused by the commit re. `queryprune` yesterday, I changed how token is extracted and I think I overlooked to take into account wildcards adjacent to extracted token.

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/1367
