### ISSUE TITLE
Online Video Converter Website Error

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uAssets#6555]
This website shows an error when you try to download a video 

`https://www.onlinevideoconverter.com/youtube-converter`

![4324324](https://user-images.githubusercontent.com/18757054/68688437-044ec000-056f-11ea-897f-fec1a7de6562.jpg)

**Comment by mapx-** [comment]
I get that error even disabling uBo

**Comment by krystian3w** [comment]
abandonware website?

Someone probably pays every "two years", because he has an order set on his bank account for a few years or somehow the site makes more money than the cost of the server and the domain and don't even need to fix bugs with the new YouTube API.

**Comment by GKid94** [comment]
Ok than close this issue

**Comment by llacb47** [comment]
@krystian3w why "two years"?

**Comment by krystian3w** [comment]
...Well, there are probably offers not to pay every year for hosting and domain and not buying a "WWW" server for the home.

**Comment by llacb47** [comment]
@krystian3w sorry but that did not make much sense. How about write it in Polish and I will try and translate it myself?
