### ISSUE TITLE
AMD Website Missing Buttons

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uAssets#6557]
The "Share this page" buttons are missing when you enable uBlock

![5435345](https://user-images.githubusercontent.com/18757054/68700044-8d242680-0584-11ea-8cf8-995ded8e3a6d.jpg)
![53453234234](https://user-images.githubusercontent.com/18757054/68700117-ae851280-0584-11ea-8e6f-14792d348cdd.jpg)

**Comment by llacb47** [comment]
Fill in the issue template.

**Comment by mapx-** [comment]
test case:
`https://www.amd.com/en/gaming/featured-games`

test

```
||addthis.com^$important,third-party,domain=~missingkids.com|~missingkids.org|~sainsburys.jobs|~sitecore.com,badfilter
||addthis.com^$important,third-party,domain=~missingkids.com|~missingkids.org|~sainsburys.jobs|~sitecore.com|~amd.com
@@||addthis.com/js/*/addthis_widget.js$script,domain=amd.com
@@||addthisedge.com/live/$script,domain=amd.com
```

**Comment by GKid94** [comment]
Do I need to update the filter lists to fix the issue

**Comment by llacb47** [comment]
Yes

**Comment by GKid94** [comment]
Thx it worked

**Comment by krystian3w** [comment]
What's the difference between unlocking social buttons here and unlock social share on serialomaniak.pl?

https://github.com/uBlockOrigin/uAssets/issues/2764

serialomaniak have more tracking than global AMD?
