### ISSUE TITLE
Do not filter properly on Firefox in NGA site

### ISSUE THREAD

**Issue by nncy** [uBlockOrigin/uAssets#6559]
### URL(s) where the issue occurs

`[https://bbs.nga.cn/]`

### Describe the issue

[When I was browsing this site, chrome could normally block ads on the page as well as a pop-up ad page. But on Firefox it doesn't work.]

### Screenshot(s)
On Firefox:
<img src="https://i.loli.net/2019/11/13/rUSnpi5FZKQuqXD.png" />
<img src="https://i.loli.net/2019/11/13/RQwSNdA4xfasYrK.png" />
<img src="https://i.loli.net/2019/11/13/MDlRYyIFrjxodV6.png" />

On Chrome:
<img src="https://i.loli.net/2019/11/13/H7ADkoLl1FsqUf4.png" />
<img src="https://i.loli.net/2019/11/13/Hh8sfLgWe4S69zQ.png" />
<img src="https://i.loli.net/2019/11/13/xwkdU6ZhPuargbS.png" />
### Versions

- Browser/version: 
[Firefox:68.2.0esr (64-bit) for Arch Linux] 
[Chrome: Version 78.0.3904.97 (Official Build) (64-bit)]
- uBlock Origin version: [1.23.0 (both of Firefox and Chrome)]

### Settings

- [I don't change any settings]

### Notes

[Sorry,i can find angthing wrong.]

**Comment by lain566** [comment]
Fixed in the regional filter list, you have to enable `Easylist China`
It's very likely that you have it enabled in uBO for Chrome.

**Comment by nncy** [comment]
Thanks.It works.

**Comment by krystian3w** [comment]
Anybody still support `Easylist China`?

**Comment by ZaphodBeebblebrox** [comment]
I do not know about Easylist China, but CJX's EasyList Lite is maintained by @cjx82630
