### ISSUE TITLE
adshrink.it [adblock detected]

### ISSUE THREAD

**Issue by simoconfa** [uBlockOrigin/uAssets#6560]
### URL(s) where the issue occurs

`https://adshrink.it/t6hZR5`

### Describe the issue

Adblock detected

### Screenshot(s)

![immagine](https://user-images.githubusercontent.com/8224154/68772030-610eb100-0629-11ea-9757-7cf092b73dad.png)

### Versions

- Browser/version: FF latest
- uBlock Origin version: latest 

### Settings

- Easylist Italy

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/84580704/119253615-bd597600-bbba-11eb-8199-71bb799d8f23.png)
@pgl

**Comment by IThinkIAmCool** [comment]
Also, after cling on "Temporarily", the website/webpage is broken.

**Comment by IThinkIAmCool** [comment]
`https://adshrink.it/` looks off for me.
enabled-by-dfaault filter lists +Fanboy's Annoyance + uBlock filters -- Annoyances

**Comment by pgl** [comment]
It's an ad server.
