### ISSUE TITLE
How to block auto ads video in this site

### ISSUE THREAD

**Issue by Fuyuppe** [uBlockOrigin/uAssets#6561]
### URL(s) where the issue occurs

https://movie2z.com/The%20Girl%20Next%20Door%20%E0%B8%AA%E0%B8%B2%E0%B8%A7%E0%B8%82%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%AA%E0%B8%B0%E0%B8%81%E0%B8%B4%E0%B8%94%E0%B8%AB%E0%B8%B1%E0%B8%A7%E0%B9%83%E0%B8%88%E0%B8%AB%E0%B8%A7%E0%B8%B4%E0%B8%A7

### Describe the issue

When I want to watch video. Auto ads video  will show and I have to click for skip
Most website in Thailand using ads like this 
Sorry for my bad english
Thanks in advance!

### Screenshot(s)

![ภาพ](https://user-images.githubusercontent.com/43577606/68814512-a07de180-06ab-11ea-8922-ecfce3147c5f.png)

### Versions

Firefox 70.0.1

- uBlock Origin version: 1.23.0

### Settings

![ภาพ](https://user-images.githubusercontent.com/43577606/68815060-f69f5480-06ac-11ea-85c3-ab77a34e4921.png)

### Notes

If it's possibble I want solution to block ads video like this 
This mean a lot to me and Thailand people
Thanks in advance

**Comment by okiehsch** [comment]
I can't access the website.
![image](https://user-images.githubusercontent.com/16838044/68816975-84b11600-0680-11ea-802f-211db38b2b06.png)

**Comment by Fuyuppe** [comment]
> 
> 
> I can't access the website.
> ![image](https://user-images.githubusercontent.com/16838044/68816975-84b11600-0680-11ea-802f-211db38b2b06.png)

![ภาพ](https://user-images.githubusercontent.com/43577606/68817622-d5426680-06b4-11ea-98d5-9ad5e658b605.png)
Around 8.00 AM in Thailand 
I can access normally

https://movie2z.com/

**Comment by okiehsch** [comment]
Well, I tried with a Thailand IP with the same result, so we will have to wait and see if others can access the site to find a possible fix.

**Comment by llacb47** [comment]
I can access the site. Banners are not fixed by regional lists. The player is an iframe at this URL `https://stream.osami.xyz/video/wlBkSwvjh8yvlnz/`.

Test these filters
```
||cdn.osamime.ml^$media,domain=stream.osami.xyz,redirect=noopmp3-0.1s
! banners
||movie2z.com/img/*.gif$image
```

**Comment by okiehsch** [comment]
Thanks I can access `https://stream.osami.xyz/video/wlBkSwvjh8yvlnz/` and your redirection works fine.
Regarding the banners at `movie2z.com` @Fuyuppe does 
`||movie2z.com/img/*.gif$image`
fix that?

**Comment by Fuyuppe** [comment]
> ||cdn.osamime.ml^$media,domain=stream.osami.xyz,redirect=noopmp3-0.1s
> ! banners
> ||movie2z.com/img/*.gif$image

Thanks it's worked 
If another website like this 
https://www.ดูหนังออนไลน์.com/22032/midway-%e0%b8%ad%e0%b9%80%e0%b8%a1%e0%b8%a3%e0%b8%b4%e0%b8%81%e0%b8%b2%e0%b8%96%e0%b8%a5%e0%b9%88%e0%b8%a1%e0%b8%8d%e0%b8%b5%e0%b9%88%e0%b8%9b%e0%b8%b8%e0%b9%88%e0%b8%99.html
How I can get url video like https://stream.osami.xyz for another website

**Comment by Fuyuppe** [comment]
> 
> 
> Thanks I can access `https://stream.osami.xyz/video/wlBkSwvjh8yvlnz/` and your redirection works fine.
> Regarding the banners at `movie2z.com` @Fuyuppe does
> `||movie2z.com/img/*.gif$image`
> fix that?

Fixed it Thanks 
But I have another question 
How I can get url video like https://stream.osami.xyz for another website
Because most of Thailand website using ads video like that
This is another website 
https://www.ดูหนังออนไลน์.com/22032/midway-%e0%b8%ad%e0%b9%80%e0%b8%a1%e0%b8%a3%e0%b8%b4%e0%b8%81%e0%b8%b2%e0%b8%96%e0%b8%a5%e0%b9%88%e0%b8%a1%e0%b8%8d%e0%b8%b5%e0%b9%88%e0%b8%9b%e0%b8%b8%e0%b9%88%e0%b8%99.html
Thanks in advance again

**Comment by mapx-** [comment]
test
```
##.ads-center
*.gif$image,domain=stream1688.com
*$media,domain=stream1688.com,redirect=noopmp3-0.1s
```
the first button seems to be dedicated only to the video ads

**Comment by Fuyuppe** [comment]
Thank you all you guy.
Now my problem was fixed.
I disable another adblock extension then video ads iwill not show anymore
