### ISSUE TITLE
upfile.us

### ISSUE THREAD

**Issue by lyndmi** [uBlockOrigin/uAssets#6562]
### URL(s) where the issue occurs

`https://upfile.us/file/ISUYB374D7C6`

### Describe the issue

Countdown 8 seconds

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24647715/68875185-ad79ef80-0702-11ea-871a-deaa783d010f.png)

### Versions

- Browser/version: 64.0.3417.92
- uBlock Origin version:  1.22.4

### Settings

- Default

### Notes

Request to bypass countdown

**Comment by krystian3w** [comment]
`upfile.us##+js(nano-stb)`
