### ISSUE TITLE
ancensored.com (NSFW) | Breakage

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#6563]
### URL(s) where the issue occurs

`http://ancensored.com`

### Describe the issue

Search suggestions don't appear while typing in the search box. The videos don't work or play.

### Versions

- Browser/version: Firefox 70.0.1
- uBlock Origin version: 1.23.0

### Settings

Default

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/6341858a6e8d40a5bc26d94046c0e065325a6f4a
