### ISSUE TITLE
imdb.com

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#6565]
### URL(s) where the issue occurs

`https://www.imdb.com/title/tt7908628/mediaindex`

### Describe the issue

While browsing the photo gallery of any movie, show, actor, etc. on the website an advertisement of Amazon Prime keeps showing up randomly (perhaps after every 3rd photo?) on navigating through the slideshow.

### Screenshot(s)

https://sendvid.com/ne2u6que

### Versions

- Browser/version: Firefox 70.0.1
- uBlock Origin version: 1.23.0

### Settings

Default

**Comment by mapx-** [comment]
I cannot reproduce the ads

**Comment by in4u** [comment]
Maybe they're geo-targeted or something. I tried a proxy and the ads didn't show up then.

**Comment by in4u** [comment]
Okay, can you try 182.74.243.39:3128 as proxy? I could reproduce the ad with that proxy server. Just keep browsing the gallery. Ad doesn't load up immediately but when it eventually does it keeps recurring after every 3 photos.

**Comment by mapx-** [comment]
That proxy does not work for me, however I get another indian ip (via Hola) and still no ad

**Comment by in4u** [comment]
Weird! I tried the top few proxies from [this](http://free-proxy.cz/en/proxylist/country/IN/https/speed/level1) list and got ad on all occasions, except for a couple of IPs. But the ads don't load immediately though, sometimes they start showing up after going through 5-10 photos.

Well, let's see if anyone else can reproduce this issue.

**Comment by ghajini** [comment]
No proxy, ISP default Indian ip used, still not reproduced

**Comment by in4u** [comment]
Maybe their algorithm takes into account some other criteria as well. :thinking: 

I clicked on an ad and it's URL is in the following format:

`https://aax-eu.amazon-adsystem.com/x/c/[Some long ID which varies from ad to ad]/https://www.amazon.com/gp/video/offers/ref=dvm_us_jh_cs_imdb_ntnmdtbr?ie=UTF8&amp;tag=imdb_nm_nativead_india`

**Comment by Procyon-b** [comment]
Can't reproduce either (new profile, default uBo config, with/without proxy).
In uBlock's dashboard, can you tell us which filter lists are selected.
Have you rules/filters in "My filters", "My rules" and "Whitelist" ?

**Comment by in4u** [comment]
Ah, thanks for pointing that out. I just checked and found out that `Fanboy's Enhanced Tracking List` was enabled. The culprit seems to be this `@@||amazon-adsystem.com^*/getad$script,domain=imdb.com` rule.

I tried `@@||amazon-adsystem.com^*/getad$script,domain=imdb.com,badfilter` and the issue was resolved.

**Comment by ghajini** [comment]
Question

How a whitelist sits into `fanboy enhanced tracking list`🤔

**Comment by okiehsch** [comment]
Maybe a script checks if it is blocked and tracks the usage of an Adblocker that way, hence the whitelisting of it.
I am just speculating.

**Comment by Procyon-b** [comment]
> How a whitelist sits into fanboy enhanced tracking list

About a third of all its rules is whitelisting. That's the reason I don't use this particular one.

**Comment by in4u** [comment]
There is an issue while playing some trailers. Unable to reproduce on all trailers but certainly in some cases. What happens is the trailer immediately skips to the next in queue without playing the one which is actually clicked.

The problem goes away on disabling the default `uBlock filters`.

Example URL: `https://www.imdb.com/title/tt1822395/`

Possibly related issues seen on Reddit: [1](https://old.reddit.com/r/uBlockOrigin/comments/e2nc95/imdb_issue/), [2](https://old.reddit.com/r/firefox/comments/e42i2x/imdb_videos_skipping_to_the_end_since_last_update/)

**Comment by mapx-** [comment]
test this filter
`@@||imdb-video-wab.media-imdb.com^$media,domain=imdb.com`

**Comment by okiehsch** [comment]
I changed the existing exception to 
`@@||media-imdb.com^$media,domain=imdb.com`
should fix the issue.

**Comment by in4u** [comment]
The fix by @okiehsch seems to be working. Will report back if anything else is amiss.

**Comment by in4u** [comment]
There's one annoyance: Right click on trailer videos is disabled.

*Off-topic and personal query*: On way too many sites these days, the video stretches to full width of monitor while adjusting height accordingly which causes the video height to exceed that of the viewport on wide screen displays. Is there any way I can apply a CSS `max-height` based `:style` rule or something for the `video` element universally and not just site-specific?
