### ISSUE TITLE
msn.com video blocked

### ISSUE THREAD

**Issue by Procyon-b** [uBlockOrigin/uAssets#6566]
### URL(s) where the issue occurs

`https://www.msn.com/nl-be/video/kijken/geweld-gebruiken-om-een-politieke-mening-te-uiten-is-gewoon-terrorisme-meryame-kitir/vi-BBWL38W?ocid=mailsignout`

### Describe the issue

I don't know if it is reproducible everytime, or everywhere (geolocation?). Is the "akamaized" subdomain constant, or is this part of a pool? (see current exception filter below)

Here is the element that is filtered:
```
Filter        *$3p,media,domain=msn.com
Filter list   uBlock filters 
Context       www.msn.com
Partyness     (3) msn.com ⇒ akamaized.net
Type          media
URL           https://wus-streaming-video-msn-com.akamaized.net/fb162fcb-2952-40fa-bbaa-c0f09d0929e1/90a5f00a-cbc0-429c-ad7c-6c63b75f_2250.mp4
```

The video tries to load then an error message replaces the image placeholder.

### Versions

- Browser/version: chrome
- uBlock Origin version: 1.23.0

### Notes

Here are the filters that apply to this case (from "uBlock filters"):
```
*$media,redirect=noop.txt,domain=msn.com,3p
@@||eus-streaming-video-msn-com.akamaized.net^$media,domain=msn.com
```
replacing the second line with:

`@@||*-streaming-video-msn-com.akamaized.net^$media,domain=msn.com`

can fix the problem.

**Comment by llacb47** [comment]
Oops again...

**Comment by okiehsch** [comment]
@llacb47 your filter works with the US version of msn.com, so that was not really an "Oops". ;)
