### ISSUE TITLE
AdBlock detect can't access 

### ISSUE THREAD

**Issue by Fuyuppe** [uBlockOrigin/uAssets#6567]
https://series-d.com/

AdBlock detect can't access 
### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

![ภาพ](https://user-images.githubusercontent.com/43577606/68912629-3f2d3f80-078b-11ea-90aa-2e29051fdd6b.png)

### Versions

Firefox 70.0.1
- uBlock Origin version: 1.23.0

### Settings

![ภาพ](https://user-images.githubusercontent.com/43577606/68912754-b5ca3d00-078b-11ea-90bc-c8b142b30003.png)

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by Fuyuppe** [comment]
||i.imgur.com/Q87cTEy.gif$image
series-d.com##.text-center.mt-5.container
series-d.com##.inactive-mobile.kosana-container

Now I can access 
But new problem is this script
##.ads-center
*.gif$image,domain=series-d.com
*$media,domain=series-d.com,redirect=noopmp3-0.1s
I want to set time to this script stop after 10s  
How I can do 
Thanks in advance

**Comment by okiehsch** [comment]
Jeez those thailand specific sites/ads are a danger for users with photosensitive epilepsy.
````
*$media,domain=series-d.com,redirect=noopmp3-0.1s
||imgur.com/*.gif$image,domain=series-d.com
@@||cdn.jsdelivr.net/npm/*/fuckadblock$script,domain=series-d.com
series-d.com##.mb-3.text-center.container-fluid
@@||series-d.com^$generichide
````
works for me.

> I want to set time to this script stop after 10s
I don't understand what you mean by that.

**Comment by Fuyuppe** [comment]
> *$media,domain=series-d.com,redirect=noopmp3-0.1s
> ||imgur.com/*.gif$image,domain=series-d.com
> @@||cdn.jsdelivr.net/npm/*/fuckadblock$script,domain=series-d.com
> series-d.com##.mb-3.text-center.container-fluid
> @@||series-d.com^$generichide

https://series-d.com/love-me-if-you-dare/
Select Ep 2 
You will understand after that

**Comment by okiehsch** [comment]
I can see the issue but episode 2 does not play pn my end there appears to be an error server side.
Episode 3 has the same issue
````
@@||googleusercontent.com^$media,domain=series-d.com
@@||googlevideo.com/videoplayback$media,domain=series-d.com
````
works on my end.

**Comment by Fuyuppe** [comment]
> 
> 
> I can see the issue but episode 2 does not play on my end there appears to be an error server side.
> Episode 3 has the same issue
> 
> ```
> @@||googleusercontent.com^$media,domain=series-d.com
> @@||googlevideo.com/videoplayback$media,domain=series-d.com
> ```
> 
> works on my end.
Thank you
If I had another question about script  
I will asking here again
