### ISSUE TITLE
MSN.com ad reinsertion on Firefox 70

### ISSUE THREAD

**Issue by VernonStow** [uBlockOrigin/uAssets#6568]
### URL(s) where the issue occurs

Original link was `https://www.msn.com/` but it redirected to
`https://www.msn.com/g00/?i10c.ua=2&i10c.encReferrer=&i10c.dv=15`

### Describe the issue

msn.com is now redirecting Firefox 70 to g00 ad reinsertion site and partially disabling uBO.

### Screenshot(s)
![MSN  Outlook, Office, Skype, Bing, Breaking News, and Latest Videos 2019-11-14](https://user-images.githubusercontent.com/15573459/68918811-f6469e00-072c-11ea-8721-629d4a1e4258.png)

### Versions

- Browser/version: 70.0.1 (64-bit)
- uBlock Origin version: 1.23.0

### Settings

- See screenshot:
![filter lists](https://user-images.githubusercontent.com/15573459/68918803-ecbd3600-072c-11ea-998d-e19460ae4429.png)

### Notes

Disabling my custom filters made no difference.

**Comment by okiehsch** [comment]
Have you enabled `uBo-filters`
![image](https://user-images.githubusercontent.com/16838044/68919167-519a7f80-0771-11ea-969d-e1b6784292b0.png)

**Comment by uBlock-user** [comment]
I can reproduce it, i10C is not longer found in the source code. Use INSTART instead in the filter.

**Comment by okiehsch** [comment]
Hm, still works on my end?
Does `IXC_` work for you, we use that for most Instart sites.

**Comment by uBlock-user** [comment]
> Does IXC_ work for you,

Yes, that still does. That latest Instart Version was updated on Oct 30th. You're probably being served an older version where `i10C` is still present. I still recommend using `INSTART` because that's never going to get removed, rather `IXC` is just another variable they can replace.

**Comment by okiehsch** [comment]
They can also rename INSTART if they really want to.

**Comment by uBlock-user** [comment]
They could but `INSTART` is present since the beggining aka 2016, so they could if they wanted to but they haven't in 3 years.

**Comment by NubN** [comment]
uBO does nothing today here, uBlock Extra is necessary for `msn.com` 

`https://www.msn.com/es-es/estilo/moda/estos-han-sido-los-mejores-looks-de-2019/ss-BBYhlPq`

**Comment by llacb47** [comment]
I can reproduce on the homepage `https://www.msn.com/es-es` on default filters, g00 crap getting thru.

**Comment by NubN** [comment]
hello! **llacb47**  is a useless filter,  but with this filter I don't see ads in the main page 😸

`msn.com##+js(aopr, RegExp)`

but the site is broken inside articles

i found that here:

https://i.imgur.com/eBcOx0N.png

cheers

**Comment by PIZZA90** [comment]
heyyy is this site working fine? im taking errors..

`https://www.msn.com/`

![Captura](https://user-images.githubusercontent.com/33556647/105397421-51bdc700-5c21-11eb-9e5e-978c5c051899.PNG)
