### ISSUE TITLE
How to block URLs? 

### ISSUE THREAD

**Issue by joeparkerz** [uBlockOrigin/uAssets#657]
I want to block the following URLs permanently but it's not working.

https://www.google.si/_/chrome/newtab?espv=2&ie=UTF-8
https://www.google.si/_/chrome/newtab-serviceworker.js

Here is my filter.
`||.*/_/chrome/newtab[^|].*`

**Comment by lewisje** [comment]
To use regex characters, you need to make the whole filter a regex, like this: `/\/_\/chrome\/newtab[^|]/`

**Comment by gorhill** [comment]
`||google.si/_/chrome/newtab` should work

**Comment by joeparkerz** [comment]
What I am trying to do is prevent google new tab from showing ^^

**Comment by SMed79** [comment]
Maybe, [**Empty New Tab Page**](https://chrome.google.com/webstore/detail/empty-new-tab-page/dpjamkmjmigaoobjbekmfgabipmfilij) you are searching for?!

**Comment by lewisje** [comment]
Yeah, I don't think uBO can block on pages that aren't HTTP or HTTPS (including browser-specific URI schemes like CHROME).
