### ISSUE TITLE
This website video did't show

### ISSUE THREAD

**Issue by Fuyuppe** [uBlockOrigin/uAssets#6570]
`https://www.zone-anime.net/`

1.This website `https://www.zone-anime.net/`
Video did't show 
How to fix it 
2. How to auto skip this website `https://nungsodhd.com`
Becuase this script 
`*$media,domain=ro8p.ru,redirect=noopmp3-0.1s`
Did't work

### Screenshot(s)
![ภาพ](https://user-images.githubusercontent.com/43577606/68929208-7832d780-07be-11ea-8385-9292bf553b3d.png)
![ภาพ](https://user-images.githubusercontent.com/43577606/68929405-e6779a00-07be-11ea-9d78-7feba715f2c1.png)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Firefox 70.0.1
- uBlock Origin version: 1.23.0

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

Thanks in advance

**Comment by Fuyuppe** [comment]
> 
> 
> test these filters for `nungsodhd`
> 
> ```
> ||nungsodhd.com/*Ads$media,1p
> ||nungsodhd.com/*banner/$image
> nungsodhd.com###link-ads
> ```

Did't work 
![ภาพ](https://user-images.githubusercontent.com/43577606/68986031-f25e6d00-084d-11ea-9e30-ba583d901dfc.png)
How to fix it

**Comment by okiehsch** [comment]
What does the message your screenshot translate to in english?
After the preroll the video never plays on my end even if I disable `uBO`.

**Comment by Fuyuppe** [comment]
> 
> 
> What does the message in your screenshot translate to in english?
> After the preroll the video never plays on my end even if I disable `uBO`.

Cannot find module MIME
https://nungsodhd.com/view.php?ID=50
This link could play
I don't want to have button for skip in the right top corner But nerver mind it acceptable
