### ISSUE TITLE
news18.com

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#6571]
### URL(s) where the issue occurs

`https://www.news18.com/news/india/plastic-eating-bacteria-discovered-by-indian-scientists-from-wetlands-of-greater-noida-2340439.html`

### Describe the issue

Wait for the page to load completely. Start scrolling down one :arrow_down:  key press at a time. The tab / browser will soon become very sluggish and/or unresponsive due to extraordinarily high memory or resource usage. Keep scrolling up/down using arrow keys and Firefox will eventually crash on systems with relatively low memory if the tab is kept active for long enough.

### Versions

- Browser/version: Firefox 70.0.1
- uBlock Origin version: 1.23.0

### Settings

![L](https://user-images.githubusercontent.com/43062185/68961537-a208f000-07f8-11ea-88df-a1ef372c9338.png)

### Notes

Please feel free to close this issue if it's irrelevant or non-reproducible. Am just wondering if it's a problem with the website, Firefox or my system. I suspect it may be due to some bloated or poorly implemented widget on the site. There's a fancy unnecessary progressbar type widget at the bottom of page which tracks the article position w.r.t. scrolling. That may be the cause or something else IDK. Anyway, if there's something that can be fixed via annoyances or other relevant filter list then it would be great!

**Comment by mapx-** [comment]
test
```
news18.com##+js(aopr, getAdsScripts)
news18.com##+js(acis, $, scroll)
news18.com##+js(aeld, scroll)
```

**Comment by gwarser** [comment]
`news18.com##+js(aeld, scroll, getElementById)` allows for infinite scroll (lazyloading).

**Comment by in4u** [comment]
Okay guys, combining your rules like:

`news18.com##+js(aopr, getAdsScripts)`

`news18.com##+js(acis, $, scroll)`

`news18.com##+js(aeld, scroll, getElementById)`

Everything works perfectly and the page browsing becomes light as a breeze. No more hangs or crashes!

Please do include these rules in a relevant filter list.

**Comment by ghajini** [comment]
Checked on firefox android....

Wait, with mapx- filter articles don't show its full content 
Also

**Comment by mapx-** [comment]
@ghajini 
```
news18.com##+js(aopr, getAdsScripts)
news18.com##+js(acis, $, scroll)
news18.com##+js(aeld, scroll, getElementById)
```

Are these filters breaking something on page ? What ? How to reproduce ?

**Comment by mapx-** [comment]
@ghajini test on android only this filter
`news18.com##+js(aeld, scroll, getElementById)`

**Comment by ghajini** [comment]
Wait a bit sir i will show

**Comment by in4u** [comment]
@mapx- I tested with Firefox for Android UA in responsive design mode and can reproduce the problem raised by @ghajini. The article gets cut off and there's a `Read more` link which gets hidden or overlapped by the TV/video widget. Thus the article's content remains inaccessible.

**Comment by mapx-** [comment]
@in4u did you test **only** that filter ?

`news18.com##+js(aeld, scroll, getElementById)`

**Comment by ghajini** [comment]
1)these filters on firefox desktop significantly reduces memory usage from 2GB to 300-400MB but not helpful for firefox android

`news18.com##+js(aopr, getAdsScripts)`
`news18.com##+js(acis, $, scroll)`
`news18.com##+js(aeld, scroll, getElementById`


2.
This rule breaks article content only half article content is shown

`news18.com##+js(aeld, scroll, getElementById)`

**Comment by in4u** [comment]
I tested the following:

`!#if !env_mobile`
`news18.com##+js(aeld, scroll, getElementById)`
`!#endif`

This gets rid of the issue in desktop without affecting mobile. Otherwise, without the mobile directive, the article's `Read more` button gets hidden on Firefox for Android as mentioned earlier.

But the site lags quite a bit on Firefox for Android too. In fact, I had to force close the browser once while testing. So, there should be a solution for mobile as well.

**Comment by ghajini** [comment]
Yeah very lag on firefox android, other tabs also reload when switching to them

**Comment by mapx-** [comment]
Test in android

`news18.com##+js(aeld, scroll, Mgid)`

**Comment by in4u** [comment]
Works for me!

**Comment by ghajini** [comment]
Memory usage still High on firefox android...
Can you add for firefox android,no breakage so far

`news18.com##+js(aopr, getAdsScripts)`
`news18.com##+js(acis, $, scroll)`
