### ISSUE TITLE
lewat.club blocking too much

### ISSUE THREAD

**Issue by Arsindy** [uBlockOrigin/uAssets#6573]
### URL(s) where the issue occurs

`https://autoratio.com/SRdeoTOuQ`
`https://autoratio.com/x39LhrlEU`

### Describe the issue

[blocking generate link]

### Screenshot
`https://i.imgur.com/9NaOcMD.png`

### Versions

- Browser/version: chrome v78
- uBlock Origin version: v1.23.0

### Settings

- uBO's default settings

**Comment by dumbusernameidk** [comment]
fine on my end.
