### ISSUE TITLE
rutube.ru

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#6574]
ADS in the player.
`https://rutube.ru/play/embed/12974816`
_This only on Firefox, on Chrome-invalids everything is fine._
Of course fucking of course, the latest version of uBO and Firefox, only the default settings and yes, i have already reset my profile. Nothing.
![1](https://user-images.githubusercontent.com/8535285/68990827-d2f62d00-08ab-11ea-8b52-763ea6580f43.png)

**Comment by okiehsch** [comment]
I get this message going to `https://rutube.ru/play/embed/12974816`
![image](https://user-images.githubusercontent.com/16838044/68990913-3440e080-0859-11ea-89c0-6146503db3d3.png)

**Comment by bogachenko** [comment]
it is written here - geolock. Use RUS/URK/BLR proxy

**Comment by okiehsch** [comment]
Thanks for the translation, I can't use a VPN at the moment sorry.

**Comment by llacb47** [comment]
Is the whole site geolocked or just some videos?

**Comment by bogachenko** [comment]
idk, i have no west IP.

**Comment by llacb47** [comment]
even if video is not geolocked, midrolls only served to russian IP... I'm using proxy and got midrolls on these videos:

```
https://rutube.ru/video/e34b634dc2906677434c907d5b46c878/
https://rutube.ru/video/46d05294f03bf5e5fdcff0cd5145b70e/
https://rutube.ru/video/4f7545205d3b8d0b5e1853dde32c7f5c/
```

**Comment by llacb47** [comment]
It's SSAI, meaning the ads are inside of the m3u8 stream, nothing can be done.

However, add this to be able to skip through ads: `rutube.ru##+js(json-prune, cuepoints)`

**Comment by krystian3w** [comment]
Maybe AdGuard can override m3u8 with replace: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#replace-modifier

**Comment by uBlock-user** [comment]
> Maybe AdGuard can override m3u8 with replace

That may be the solution to SSAI

**Comment by bogachenko** [comment]
There are no problems so far. It works, but for a long time?
