### ISSUE TITLE
How to skip video ads in this website

### ISSUE THREAD

**Issue by Fuyuppe** [uBlockOrigin/uAssets#6577]
`https://www.doomovie-hd.com/?r=movie_view&id=16268`

How to skip video ads in this website

### Screenshot(s)

![ภาพ](https://user-images.githubusercontent.com/43577606/68995248-1194e300-08be-11ea-8269-df6e4906713a.png)

### Versions

- Browser/version: Firefox 70.0.1
- uBlock Origin version: 1.23.0

### Notes
This is my script

*.gif$image,domain=doomovie-hd.com
*$media,domain=lh3.youlive-cdn.com,redirect=noopmp4-0.1s

**Comment by krystian3w** [comment]
`display: block !important;` for hidden skip button?

**Comment by krystian3w** [comment]
`*.gif$image,domain=doomovie-hd.com` - this is not script

**Comment by okiehsch** [comment]
````
omovie-hd.com##+js(json-prune, adParam)
||doomovie-hd.com/assets/img/banner-new/*$image,1p
````
works on my end.

**Comment by Fuyuppe** [comment]
> 
> 
> ```
> omovie-hd.com##+js(json-prune, adParam)
> ||doomovie-hd.com/assets/img/banner-new/*$image,1p
> ```
> 
> works on my end.

Thank you
