### ISSUE TITLE
is possible fix this site - mundoaoe.com

### ISSUE THREAD

**Issue by NubN** [uBlockOrigin/uAssets#6579]
### URL(s) where the issue occurs

`https://www.mundoaoe.com`

### Describe the issue

this site has redirections, i dont know if is possible fix with uBO

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [v1.23.0]

### Settings

- Default (Spain Region)

**Comment by krystian3w** [comment]
`||buyittraffic.com^$script,domain=mundoaoe.com`

but this also break site.

**Comment by okiehsch** [comment]
The site looks broken even if you don't block  `buyittraffic.com`.
Adding
`mundoaoe.com##+js(aopr, pp)`
will break the redirection caused by this script `https://to.buycongestion.com/9dBrLf`.

@NubN I don't know the site has it always looked that way?

**Comment by okiehsch** [comment]
This seems to be a site issue. 
I will fix the redirection but in my opinion the site is completely broken and not usable.

**Comment by NubN** [comment]
I dont know about this site.. I found this site via google, looking for age of empires.

maybe it will be temporary.

https://i.imgur.com/QXe8frV.png

**Comment by NubN** [comment]
maybe they fix that "issue" i cant find nothing of `buyittraffic`  now 🥶 and the web is working.

was a virus in the website? 🥴

Maybe you have to remove the filter? sorry for the inconvenience.

**Comment by krystian3w** [comment]
Remove imo no needed - infected resources from code gone and imo any no use pp function.

**Comment by okiehsch** [comment]
I will leave the `buycongestion.com` filter in place, thanks for the feedback.
