### ISSUE TITLE
journaldev.com detects adblocking

### ISSUE THREAD

**Issue by josephcsible** [uBlockOrigin/uAssets#658]
### URL(s) where the issue occurs

`http://www.journaldev.com/1392/factory-design-pattern-in-java`

### Describe the issue

After visiting any page on journaldev.com for more than a few seconds, it will be covered with a message that makes you turn off your adblocker.

### Versions

- Browser/version: Firefox 55.0.2
- uBlock Origin version: 1.13.10

### Settings

- No changes (tested on new profile with all defaults)

### Notes

The page is covered by a div with a class of "k7d9f6-container", but the first 6 characters are randomly generated and are different every time. Also, here's a beautified version of the responsible code: https://gist.github.com/josephcsible/612e54ca7595b289c82431a9dbc40bdd

**Comment by okiehsch** [comment]
Does
`journaldev.com##script:inject(abort-on-property-write.js, KillAdBlock)`
work for you?

**Comment by josephcsible** [comment]
Yep! I tried it in Firefox and Chrome.
