### ISSUE TITLE
Adblock detect

### ISSUE THREAD

**Issue by Fuyuppe** [uBlockOrigin/uAssets#6584]
https://anime-i.com/

### Describe the issue

Adblock detect this website

### Screenshot(s)

![ภาพ](https://user-images.githubusercontent.com/43577606/69018410-efdf4d00-09de-11ea-83ea-3a72102fd163.png)

### Versions

- Browser/version: Firefox 70.0.1
- uBlock Origin version: 1.23.0

**Comment by okiehsch** [comment]
@Fuyuppe I fixed your issue you just have to update your filter lists.

**Comment by okiehsch** [comment]
Also so there is no need to open another thread about the same site.
If you have a question or don't understand what to do you can use this one even if it is closed.

**Comment by Fuyuppe** [comment]
> 
> 
> Also there is no need to open another thread about the same site.
> If you have a question or don't understand what to do you can use this one even if it is closed.

Thank you
I just want to know why is issue closed 
I thought I was wrong about rules 
Then I opened another thread 
Sorry for not knowing that

**Comment by okiehsch** [comment]
> I just want to know why is issue closed

I closed with the commit 0c61308, that commit added the filter 
`anime-i.com##+js(nostif, nextFunction, 2000)`
to the `uBO-filters` list. That filter fixes the issue.
