### ISSUE TITLE
[Anti-Adblock] https://www.fcportables.com/ (Filter included)

### ISSUE THREAD

**Issue by Makazzz** [uBlockOrigin/uAssets#6585]
### URL(s) where the issue occurs

https://www.fcportables.com/

### Describe the issue

This website has recently added blockadblock script inside and I found the code for removing it and I am sharing it here.

### Screenshot(s)

![fcportable-blockadblock](https://user-images.githubusercontent.com/49844464/69020640-37d08680-0983-11ea-883a-da66517906df.png)

### Versions

- Browser/version: Mozilla Firefox 70.0.1
- uBlock Origin version: 1.23.0

### Settings

In My filters list I added this and it worked:
www.fcportables.com##script:contains(DMCA)

### Notes

In the screenshot, there is a white text in the left corner where this link is showing.
http://bit.ly/2NSXHz1 ----> https://blockadblock.com/#61647

**Comment by okiehsch** [comment]
Your filter works fine but is Firefox specific, that is why I used one that works with Chromium/hrome and Firefox.

**Comment by krystian3w** [comment]
@okiehsch locked drag / selection:

```
https://www.fcportables.com/page/7/
```

**Comment by dimisa-RUAdList** [comment]
Recidiv!

`fcportables.com##+js(abort-on-property-write, ai_front)`
or
`fcportables.com##div[class^="chp_ads_blocker"]`

**Comment by TheRealGramdalf** [comment]
Website has new adblock prevention measures, but it can be blocked with the element zapper. Here is the offending code:
`//*[@id="195495"]` - XPath
```
<div class="popup195495box"><h2 class="bclass-195495">Adblock Detected</h2><h3 class="aclass-195495">Please consider supporting us by disabling your ad blocker</h3>
<a class="refresh-195495-btn" onclick="location.reload();">Refresh Page</a><div id="36958371"></div></div>
```
^ offending HTML div
Offending link: https://www.fcportables.com/

**Comment by x-R0b0T-x** [comment]
`https://www.fcportables.com/extra-releases/`

https://github.com/user-attachments/assets/c620cf35-3b5e-4c50-8945-5f84e8a45424

**Comment by mapx-** [comment]
no detection on my end
