### ISSUE TITLE
chip.de

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6587]
Button is back with randomized JS function: 

> https://github.com/uBlockOrigin/uAssets/issues/178, https://github.com/uBlockOrigin/uAssets/issues/42, https://github.com/gorhill/uBlock/issues/673

`https://www.chip.de/downloads/CCleaner_16317939.html`

![](https://i.imgur.com/Rdo1bKl.png) |
--- |

**Comment by uBlock-user** [comment]
`##[href^="javascript:"]`

**Comment by krystian3w** [comment]
So add into `badware risk`? EasyList Germany no block these elements...

**Comment by mapx-** [comment]
Did you report here ?
https://github.com/easylist/easylistgermany/issues

@monzta

**Comment by krystian3w** [comment]
I decided that this was an international problem and not only for the German-speaking population.

---

If something has changed since 2016, I would update the [Wiki entry](https://github.com/gorhill/uBlock/wiki/Badware-risks) about the Badware risks list and maybe even add it to readme (for better visibility).

**Comment by okiehsch** [comment]
We already fixed the same Chip downloader in the badware list
````
! https://github.com/uBlockOrigin/uAssets/issues/42
! 2015-05-04: http://www.randombrick.de/downloads-von-chip-de-ueber-den-chip-installer-vermeiden/
! 2015-04-??: http://anleitung.trojaner-board.de/chip-installer
````
so it makes sense to update that filter as suggested.

**Comment by mapx-** [comment]
> so it makes sense to update that filter as suggested.

Sure, I only asked krystian3w if he reported at the german repository

**Comment by okiehsch** [comment]
Ok, I misunderstood I thought you meant that it should be only fixed in the regional list.

**Comment by JobcenterTycoon** [comment]
The button is back

**Comment by krystian3w** [comment]
too specific?

**Comment by krystian3w** [comment]
`https://www.chip.de/downloads/AdwCleaner_58118522.html`

maybe better: `##a[title]:has(.Button[onclick])`

**Comment by JobcenterTycoon** [comment]
The button is back again

**Comment by JobcenterTycoon** [comment]
The button is back again

**Comment by krystian3w** [comment]
Nope - this need daily update if website change code daily.

**Comment by JobcenterTycoon** [comment]
Good, you can add this filter

`chip.de##a > button:has(*:matches-css-before(content: /K/))`

**Comment by krystian3w** [comment]
Nope for GNU/Linux.

**Comment by JobcenterTycoon** [comment]
The button is back

**Comment by krystian3w** [comment]
`Cat - mouse = play...`

`##a:not([href*="http://"]):has(*:matches-css-before(content: /K/))`

**Comment by JobcenterTycoon** [comment]
The button is back again

They never give up ...

**Comment by krystian3w** [comment]
Removed text from `content:` and `href=""` attribute.

**Comment by krystian3w** [comment]
GNU/Linux still have hidden "manuelle download".

**Comment by krystian3w** [comment]
@okiehsch what do you think about add this:

`||www.chip.de/n_downloader/*$document,domain=chip.de`

Will stop download any `* - installer.exe` with adware search / homepage changer in browser.

**Comment by okiehsch** [comment]
Good idea.

**Comment by JobcenterTycoon** [comment]
The filter doesn’t work anymore

**Comment by krystian3w** [comment]
`||chip.de/installer/?lastchange`

or comeback to procedural cosmetic filtering (and `mapx-` should use GNU/Linux to avoid blocking completely download by people who do not use the Windows)?

**Comment by JobcenterTycoon** [comment]
The button needs javascript so my idea is to use a filter like `chip.de##+js(aeld, click, r)` to break the click event listener behind the button. (i hope the idea is good but i'm not sure)

**Comment by krystian3w** [comment]
As long "`r`" exist in event listener.

**Comment by mapx-** [comment]
test
`chip.de##+js(aeld, , params)`

**Comment by JobcenterTycoon** [comment]
I did and works for me.

**Comment by krystian3w** [comment]
For me too, but I cannot test all event listener on site (impossible for human).

The idea of not closing on `click` event alone is very good (they can use `keydown` / `mousedown`).

**Comment by JobcenterTycoon** [comment]
The filter doesn’t work anymore

**Comment by krystian3w** [comment]
Maybe recover blacklist:

```
@@||chip.de/download/|$doc

#if !env_safari
||chip.de/download/$doc
#endif

#if !env_mobile
||chip.de/download/$doc
#endif
```

**Comment by okiehsch** [comment]
Does
`chip.de##+js(aopr, initDownloadButtonsRedesign)`
work for you?

**Comment by JobcenterTycoon** [comment]
Yes very good filter

**Comment by JobcenterTycoon** [comment]
The filter doesn’t work anymore

looks like we have a new facebook here

**Comment by okiehsch** [comment]
Does 
`chip.de##+js(aopr, DYurlencode)`
work OK?

**Comment by JobcenterTycoon** [comment]
yes it works

**Comment by JobcenterTycoon** [comment]
The filter doesn’t work anymore

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7589

**Comment by JobcenterTycoon** [comment]
They bypassed the filter again

**Comment by okiehsch** [comment]
They **really** need the money apparently.

**Comment by JobcenterTycoon** [comment]
And the adware is the best way to get money because they only need to modify the script a little bit to avoid filtering

**Comment by okiehsch** [comment]
They could do that with any banner if they really wanted but they seem to get many users to install their crap "installer" so it's worth their time making sure that it is displayed.

**Comment by krystian3w** [comment]
```
||chip.de/intern/dl/*https%3A%2F%2Fwww.chip.de%2Finstaller%2F$all
||chip.de/installer/$all
```
If update only script in the feature.

**Comment by uBlock-user** [comment]
They deserve to be put in the badware list for distributing PUPs

**Comment by llacb47** [comment]
Who is even getting fooled by this adware? It's detected by most popular antivirus... `https://www.virustotal.com/gui/file/11fc0220d869096a186f737539ec406e888c908e023001974ccdf72eba4f3195/detection`

**Comment by JobcenterTycoon** [comment]
They think this is a false positive because `chip.de` is a big site

**Comment by JobcenterTycoon** [comment]
Chip installer is back again

**Comment by uBlock-user** [comment]
How about removing the `href` attribute of the button, so that will render the button useless

**Comment by JobcenterTycoon** [comment]
Chip have a few downloads without installer but with the same button. Example:
 `https://www.chip.de/downloads/TubeMate-YouTube-Downloader-Android-App_48231612.html`

so remove `href` will break this button too

**Comment by uBlock-user** [comment]
Works with `chip.de##+js(ra, href, a[href*="withinstaller"])`

**Comment by krystian3w** [comment]
GNU/Linux, macOS and Android also see only clean version (I suppose `chip.de` no use `.dmg` macOS file with adware any more).

**Comment by krystian3w** [comment]
@uBlock-user - no, "you are bad, very bad Gaga".

![Przechwytywanie](https://user-images.githubusercontent.com/35370833/93325629-e2ba0700-f817-11ea-88ac-5688b4fb6ae4.JPG) | ![Przechwytywanie](https://user-images.githubusercontent.com/35370833/93325748-11d07880-f818-11ea-9c7c-d5866d6c7dad.JPG)
--- | ---

**Comment by uBlock-user** [comment]
@krystian3w updated

**Comment by krystian3w** [comment]
I wonder how quickly they will find a way around this.

**Comment by JobcenterTycoon** [comment]
the filter doesn’t work for me

**Comment by mapx-** [comment]
`chip.de##+js(aopr, decodeURIComponent)`
or
`||chip.de/installer/`
?

**Comment by krystian3w** [comment]
For my both works, but I cannot exclude breakage due disable obfuscated useful codes or useful javascript hidden as php file in their folder.

**Comment by JobcenterTycoon** [comment]
The last one breaks videos but the other one works fine

**Comment by okiehsch** [comment]
Breaks search.

**Comment by JobcenterTycoon** [comment]
The button is broken now its not possible to download anything

**Comment by JobcenterTycoon** [comment]
` ||chip.de/installer/` works fine for me

**Comment by JobcenterTycoon** [comment]
The chip installer is back again ... now its coming from `chip.de/securedownload`

**Comment by krystian3w** [comment]
No better move this to slack, also add @JobcenterTycoon and @adamwr?

**Comment by mapx-** [comment]
does this work ?

`||chip.de/*&`

**Comment by JobcenterTycoon** [comment]
no it breaks videos

**Comment by okiehsch** [comment]
`||chip.de/*&$script,1p`

**Comment by JobcenterTycoon** [comment]
perfect it works
