### ISSUE TITLE
Video ads => [https://www.doo4k.com]

### ISSUE THREAD

**Issue by Fuyuppe** [uBlockOrigin/uAssets#6589]
`https://www.doo4k.com/pearl-harbor/`

### Describe the issue

How to remove video ads on this website

### Screenshot(s)

![ภาพ](https://user-images.githubusercontent.com/43577606/69069052-65d3ca80-0a58-11ea-94d0-6c7abb5482ee.png)

### Versions

- Browser/version: firefox 70.0.1
- uBlock Origin version: 1.23.0

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

this filter does't work
*$media,domain=doo4k.com,redirect=noopmp3-0.1s

**Comment by mapx-** [comment]
working for me:
```
##.header-menu-bottom-ads
##.rkads
###bt-ads
*.gif$domain=doo4k.com,image
*$media,domain=doo4k.com,redirect=noopmp3-0.1s
@@||cdn.ekcdn.me/video.mp4$media,domain=doo4k.com
```

**Comment by peace2000** [comment]
Redundant? When I open https://www.doo4k.com/pearl-harbor/ there will be this kind of page:

![kuva](https://user-images.githubusercontent.com/17256841/128605421-adf011ef-95a7-434a-9890-a25b56dccc7a.png)
