### ISSUE TITLE
skymovies.live

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6590]
### URL(s) where the issue occurs

`skymovies.live/list/file/12728.html`

### Describe the issue

Ads by runative
Shady xhr's 
### Versions

- Browser/version: opera browser stable
- uBlock Origin version: ublock origin dev

### Settings

- uBO's default settings

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by ghajini** [comment]
`https://skymovies.live/list/download/12728.html`

How to disable this

**Comment by mapx-** [comment]
try
`skymovies.live##+js(set, confirm, noopFunc)`

**Comment by ghajini** [comment]
1.
That works,

2.
Also when clicked on `download file....` ,popup of newoctads is opened
