### ISSUE TITLE
oceanofmovies.pw

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6591]
### URL(s) where the issue occurs

`oceanofmovies.pw`

### Describe the issue
Popup ads

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: Dev version 1.23.1b11

### Settings

- uBO's default settings

### Notes
1.
I think fake player thumbnail/player itself
`oceanofmovies.pw/2019/09/08/avengers-endgame-2019`

2. Also `download in Hindi ` button not working(site expects popups on clicking, but working link is there inside )

**Comment by mapx-** [comment]
> download in Hindi button

Where is that button ?

**Comment by ghajini** [comment]
`download in Hindi`

Your commit fixed it

**Comment by uBlock-user** [comment]
`##.spu-bg`

for the overlay

**Comment by mapx-** [comment]
Which overlay ? after adding my filter ?

**Comment by uBlock-user** [comment]
Yes. I can reproduce it, only on desktop browsers.

**Comment by ghajini** [comment]
> `##.spu-bg`
> 
> for the overlay

Hey bro no generics(https://github.com/uBlockOrigin/uAssets/issues/6587#issuecomment-554903843),it caused download link to disappear here(https://github.com/uBlockOrigin/uAssets/issues/1407#issuecomment-555057668)

**Comment by mapx-** [comment]
right, I've tested only in FF, I get the overlay only for chrome

**Comment by uBlock-user** [comment]
>  I've tested only in FF

tested on Nightly only and it occurs after a delay of few secs.

**Comment by uBlock-user** [comment]
> Hey bro no generics🤣(#6587 (comment) caused download link to disappear here(#1407 (comment))

@mapx- knows what I mean by those generic appearing filters, don't you worry ;)
