### ISSUE TITLE
Kaspermovies.pw

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6592]
### URL(s) where the issue occurs

`kapsermovies.pw`

### Describe the issue
Popup ads

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: Dev 

### Settings

- uBO's default settings

**Comment by mapx-** [comment]
> The site could be temporarily unavailable or too busy. Try again in a few moments.

> This site can’t be reachedkapsermovies.org’s server IP address could not be found.

**Comment by ghajini** [comment]
`kaspermovies.org/chandni-chowk-to-china-2009-hindi-450mb/`

Popups closed by existing filter,after certain intervals same popups and then closed by filter,
if its nonissue then its fine....

**Comment by ghajini** [comment]
Page died
