### ISSUE TITLE
Musixmatch

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6594]
https://www.musixmatch.com/lyrics/Daria-Zawia%C5%82ow/Punk-Fu

Blocked selection by CSS and right click with JS.

**Comment by uBlock-user** [comment]
for text selection -- `musixmatch.com##body:style(user-select: text !important)` 

Both of them are dynamically set by injecting attributes on body tag.

**Comment by krystian3w** [comment]
So `ra` start too late, Holly crap 👼.

![](https://gamepedia.cursecdn.com/bindingofisaacre_gamepedia/c/c7/Holy_Mantle_Icon.png) ![](https://gamepedia.cursecdn.com/bindingofisaacre_gamepedia/d/db/Wooden_Cross_Icon.png)

**Comment by uBlock-user** [comment]
> So ra start too late, Holly crap

No, because it runs very early and only once. You need to run the scriptlet via MutationObserver -- https://github.com/uBlock-user/uBO-Scriptlets/blob/master/scriptlets.txt#L104

**Comment by krystian3w** [comment]
> You need to run the scriptlet via MutationObserver for this case

Or idea from AdGuard: add light "loop" for scriptlet - if MutationObserver no fight too fast in own "loop".

AdGuard uses "loop" for `ra` and `rc`.

**Comment by krystian3w** [comment]
#7881

**Comment by uBlock-user** [comment]
> AdGuard uses "loop" for ra and rc.

It's a delayed loop, the delay is set to `20 ms`.  I loop using `requestAnimationFrame` so the delay is set as per the user's screen refresh rate.
