### ISSUE TITLE
UBlock being detected on hdflix.net

### ISSUE THREAD

**Issue by u9bte** [uBlockOrigin/uAssets#6595]
### URL(s) where the issue occurs

`https://hdflix.net/`

### Describe the issue

The website hdflix.net had set up a creative bypass to detect ad-blockers and I have no idea how it works. Every click when UBlock is enabled is redirected to their logo, while the website works fine without UBlock. Any idea how to bypass this?

### Versions

- Browser/version: Firefox 17.0.1
- uBlock Origin version: 1.23.0

### Settings

None
### Notes

Tried switching UBlock on/off and the issue seems to be UBlock. Don't have any other filtering addons installed.

**Comment by uBlock-user** [comment]
> Every click when UBlock is enabled is redirected to their logo, while the website works fine without UBlock. 

`hdflix.net##+js(acis, Math, zfgloaded)`
