### ISSUE TITLE
YouTube / Google / Gmail (etc...) to ban your account if you avoid advertising ...

### ISSUE THREAD

**Issue by aspadistra** [uBlockOrigin/uAssets#6599]
YouTube ban your account if you avoid advertising ...
`https://www.funzen.net/2019/11/13/youtube-ban-your-account-if-you-avoid-advertising/`

Yes recently You received a notification on your YouTube account when watching videos, or an email, which indicates that the world's most popular online video platform has changed its terms and conditions of service, this has been received by all users who use this platform.

YouTube has changed its policies, which They will be effective as of December 2019.

And there are some points within these changes that have not left the community happy at all.

One of the most controversial changes, when the new terms and conditions were announced, is that YouTube may ban the accounts of users who use some type of advertising blocker. 

In other words, if you use Adblock or some type of app or extension to not see the advertising that appears on YouTube, well Your account may be banned forever.

The specific point that mentions this says the following: YouTube may cancel your access or access your Google account to the Service in part or in whole if it reasonably determines that providing the Service is no longer commercially viable.

This makes it very clear that not only can they ban you from YouTube, they can also unsubscribe your Gmail account, Adsense, Adwords and all services related to the Google world. 

When is it no longer commercially viable for Google?

Unfortunately, we have not found any information related to this topic within the new Terms and Conditions. 

Some content creators, YouTubers, have said that they will ask Google to explain specifically what it means when they mention the phrase commercially viable, Well, so far no company manager has clarified this issue.

From here, We recommend you disable any extension or application that blocks advertising on YouTube, because you could run the risk of permanent banning. 

Remember that you can add exceptions so that the app or extension does not work on certain websites. For what it is not necessary uninstall said tool to not be banned by Google.

When we learn more about this type of action that Google plans to take with YouTube, which will be in effect as of December 10, 2019, we will add more information. For now, we are as baffled as you...

**Comment by Valmar33** [comment]
Just Google abusing their monopoly again...

**Comment by mapx-** [comment]
> The basis of this article simply isn't true at all, it's just wild speculation by users (particularly on Reddit). There's no reason to think that YouTube will ban your Google account for using an ad blocker, that's just silly. Running an article like this is misleading and irresponsible.

a comment from: 
`https://www.gizchina.com/2019/11/11/watch-out-youtube-could-ban-your-account-if-you-block-ads/`
