### ISSUE TITLE
folha.uol.com.br

### ISSUE THREAD

**Issue by anewuser** [uBlockOrigin/uAssets#66]
### URL(s) where the issue occurs

`http://www1.folha.uol.com.br/esporte/olimpiada-no-rio/2016/06/1782736-atletismo-da-russia-esta-fora-dos-jogos-olimpicos-do-rio-afirma-bbc.shtml`

### Describe the issue

A paywall attempts to limit the number of stories a user can read. If the page detects that the paywall is being blocked, it redirects users to `http://www1.folha.uol.com.br/paywall/adblock.shtml?http://www1.folha.uol.com.br/esporte/olimpiada-no-rio/2016/06/1782736-atletismo-da-russia-esta-fora-dos-jogos-olimpicos-do-rio-afirma-bbc.shtml`, which instructs them to disable uBlock Origin.

### Versions

- Browser/version: Firefox 47.0
- uBlock Origin version: 1.7.0

### Settings

I've been blocking the paywall with these custom filters:
`paywall$domain=uol.com.br`
`paywall$domain=folha.com.br`

The new protection against that can be disabled with this: `folha.uol.com.br##script:contains(paywall)`

**Comment by gorhill** [comment]
Does that work: `||paywall.folha.uol.com.br/wall.jsonp$script,domain=folha.uol.com.br`?

**Comment by leuthier** [comment]
This is another link to test this issue. @gorhill Doesnt work with me.

`http://www1.folha.uol.com.br/paywall/adblock.shtml?http://www1.folha.uol.com.br/esporte/olimpiada-no-rio/2016/06/1782736-atletismo-da-russia-esta-fora-dos-jogos-olimpicos-do-rio-afirma-bbc.shtml`

### Versions 

* Browser/version: Google Chrome 51.0.2704.84 m
* AdBlock version: 2.59


The new protection against that can be disabled with this: '@@||folha.uol.com.br/$script'

**Comment by anewuser** [comment]
@leuthier This is a repository for the assets of the [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) extension. Also, if you disable all scripts, it will break the image galleries and other features of that website.

@gorhill That doesn't work because of the function that checks whether the paywall is being blocked: https://gist.github.com/anewuser/4297fc5c3c1112422987ad8024097e06 . That's why I used that inline script filter.

**Comment by anewuser** [comment]
@gorhill They've moved some of their content to the  `blogfolha.uol.com.br` subdomain, which uses the same paywall. Example page: `http://bompracachorro.blogfolha.uol.com.br/2016/08/05/cadela-ganha-irmao-gato-inseparavel-e-ate-carrega-filhote-nas-costas/`

**Comment by hsantanna** [comment]
The rule folha.uol.com.br##+js(folha-de-sp.js) will prevent users from commenting posts. There are a verifying checkbox at the commenting view that uses this javascript to allow commenting.
