### ISSUE TITLE
adblocker detection on chip.de hides download button

### ISSUE THREAD

**Issue by remusao** [uBlockOrigin/uAssets#660]
Hello,

### URL(s) where the issue occurs

On download pages of chip.de:
`http://www.chip.de/downloads/c1_downloads_auswahl_35246472.html?t=1504190432&v=3600&s=bca48a4751927bae8f4592650acc975c`
If the previous link is expired, just go on this one and click "Download" (blue button): `http://www.chip.de/downloads/CCleaner-Portable_35246459.html?icp=sigExpired`

### Describe the issue

On download pages of chip.de when an adblocker is detected, they hide the download button and replace it by a mandatory ad (you then need to click and watch a video ad to access the download).

### Screenshot(s)

Without the adblocker (the blue download button is here + plainty of ads):
![chip_adblocker_off](https://user-images.githubusercontent.com/1299873/29929722-8c89a8f8-8e6c-11e7-9b95-7963279f22f1.png)

With the adblocker (download button is hidden and replaced by an ad-wall):
![chip_adblocker_on](https://user-images.githubusercontent.com/1299873/29929723-8c8ee8a4-8e6c-11e7-9b0a-142d2ae7510a.png)

### Versions

- Browser/version: Firefox 55
- uBlock Origin version: 1.13.10

### Settings

It seems that enabling only the `EasyList` filters list is enough to reproduce the issue.

### Notes

I found out that to detect the presence of an adblocker, they check the presence of `window.TfmediaExtFolEngineLoaded` and if I inject it using a custom entry in `resource.txt` it seems to work:

```js
chip.js application/javascript
(function() {
	window.TfmediaExtFolEngineLoaded = true;
})();
```

As well as the filter:
```
chip.de##script:inject(chip.js)
```

But it might not be the best way to solve this issue (if there is already generic resource doing something similar?).

Thanks,

**Comment by okiehsch** [comment]
I do not see a better way.
`@@||a.bf-ad.net/makabo/ads_fol_init.js$script,domain=chip.de`
also works and could be added to EasyList or EasyList Germany
fyi @ryanbr

**Comment by okiehsch** [comment]
> they hide the download button and replace it by a mandatory ad

@remusao I can not reproduce anymore, I only get the "fake" looking link underneath the real one.
I can fix that if I add
`chip.de##script:inject(abort-current-inline-script.js, String.fromCharCode, InstallTrigger)`
on my end.

**Comment by okiehsch** [comment]
I will close the issue, I can not reproduce the mentioned issue anymore and the fake download button has been fixed with https://github.com/uBlockOrigin/uAssets/commit/886eac35aa189401d843eba7ba87f7e1eb546b91

**Comment by remusao** [comment]
Thank you so much @okiehsch

**Comment by gorhill** [comment]
>     chip.js application/javascript
>     (function() {
>     	window.TfmediaExtFolEngineLoaded = true;
>     })();

So I suppose a generic scriptlet such as `define-bool.js` and which accept a variable name and true/false as arguments would be useful?

**Comment by okiehsch** [comment]
It would be useful for issues like this one, in my opinion, yes.
