### ISSUE TITLE
Breaks GroupMe signup with Apple or Microsoft login

### ISSUE THREAD

**Issue by wesinator** [uBlockOrigin/uAssets#6601]
### URL(s) where the issue occurs

`https://web.groupme.com/signup`

### Describe the issue
Click `Continue with Microsoft` , or Apple

doesn't work with uBlock enabled 

### Versions

- Browser/version: Firefox 70.0.1
- uBlock Origin version: 1.23.0

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
broken even disabling uBo

**Comment by ZaphodBeebblebrox** [comment]
Not broken for me without uBO, @wesinator does `@@||cdn.mxpnl.com/libs/mixpanel-*-latest.min.js$script,domain=groupme.com` fix it for you?

**Comment by mapx-** [comment]
I tested again FF / chrome, microsoft / apple are blocked for me even disabling uBo (even using US IP)

**Comment by okiehsch** [comment]
Same on my end, it is broken with uBO disabled.
If the filter works for you and the OP add it.

**Comment by wesinator** [comment]
> 
> 
> Not broken for me without uBO, @wesinator does `@@||cdn.mxpnl.com/libs/mixpanel-*-latest.min.js$script,domain=groupme.com` fix it for you?

Yes adding that to My filters seems to fix

It doesn't work at all in Private Browsing, if you were testing there it won't work even with uBo disabled.
