### ISSUE TITLE
desirehub.me

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6602]
### URL(s) where the issue occurs

`desirehub.me/the-spy-2019-s01-dual-audio-hindi-720p-web-dl-2-6gb/`

### Describe the issue

Popup ads
### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.23.1b19

### Settings

-  uBO's default settings

**Comment by uBlock-user** [comment]
`desirehub.me##+js(acis, Math, zfgloaded)`

**Comment by ghajini** [comment]
Site redirects to `movieshub.link`

**Comment by ghajini** [comment]
update to
`movieshub.link##+js(acis, Math, XMLHttpRequest)`
or any other filter

**Comment by ghajini** [comment]
Update to 

`movieshub.*##+js(abort-current-inline-script, String.fromCharCode, btoa)`
