### ISSUE TITLE
Facebook: there is new banner to block

### ISSUE THREAD

**Issue by Giova84** [uBlockOrigin/uAssets#6603]
As shown in the following image. Seems that such banner points to `www.facebook.com/ad_campaign`

![Facebook_AD_banner](https://user-images.githubusercontent.com/3594780/69258774-72256800-0bbd-11ea-82c5-386af876fb17.png)

**Comment by krystian3w** [comment]
No needed uBO syntax?

**Comment by mapx-** [comment]
@ryanbr
