### ISSUE TITLE
Fully remove youtube autocomplete box

### ISSUE THREAD

**Issue by pascalbrahma** [uBlockOrigin/uAssets#6604]
### URL(s) where the issue occurs

`https://youtube.com`

### Describe the issue

It seems I have already blocked part of Youtube's autocomplete box, I followed this instruction from Reddit https://www.reddit.com/r/uBlockOrigin/comments/bbhrws/getting_rid_of_youtube_search_autocomplete/.

But upon editing the search box within video page, the box appear again— the dropdown box disappear soon as I click anything on the page.

### Screenshot(s)

![kurapika](https://user-images.githubusercontent.com/44594524/69321792-4d40fb80-0c76-11ea-8976-bd1ea65b40da.gif)

### Versions

- Browser/version: Mozilla Firefox Quantum 66.0.2
- uBlock Origin version: uBlock Origin v1.23.0

### Settings

- I added this filter to remove the autocomplete box, it is from reddit.

`|https://clients1.google.com/complete/search$domain=youtube.com`

**Comment by mapx-** [comment]
It's not an issue, continue on reddit

**Comment by gwarser** [comment]
<div class="gstl_50 sbdd_a" dir="ltr" style="min-width: 573px; top: 56px; position: fixed; text-align: left; left: 280px; display: block;">

`youtube.com##.gstl_50`?

**Comment by pascalbrahma** [comment]
> ```
> <div class="gstl_50 sbdd_a" dir="ltr" style="min-width: 573px; top: 56px; position: fixed; text-align: left; left: 280px;">
> ```
> 
> `youtube.com##.gstl_50`?

It's working, thanks man!
