### ISSUE TITLE
[BlockAdBlock] Animestreaming.biz

### ISSUE THREAD

**Issue by raza28** [uBlockOrigin/uAssets#6607]
### URL(s) where the issue occurs

`https://www.animestreaming.biz/forum/`

### Describe the issue

BlockAdBlock

### Versions

- Browser/version: firefox 68.2
- uBlock Origin version: 1.24

**Comment by mapx-** [comment]
fixed only as annoyance (see "questo messaggio verra visualizzato solo una volta" ), so you have tio enable the `uBlock filters – Annoyances` list
