### ISSUE TITLE
[Req] Proboards viglink/vglnk redirect disabling

### ISSUE THREAD

**Issue by Gotolei** [uBlockOrigin/uAssets#661]
An example: http://support.proboards.com/thread/638506/custom-page-height
Check the targets of any outgoing link, such as the one to i.imgur.com or those in the signatures.
Ideal condition would be no redirects applied, while not generating errors (see below).

Currently I have this applied...
```
||http://cdn.viglink.com/api/vglnk.js
proboards.com##script:inject(abort-on-property-read.js, vglnk)
```
...however it often creates some coded error or another (image) when changing pages in a thread. (ex: http://support.proboards.com/thread/638492/personal-messages)

Firefox 55, uBO 1.14.0

![image](https://user-images.githubusercontent.com/7553595/29947664-67da0d12-8e9a-11e7-97b0-cf1065dc8ace.png)

**Comment by okiehsch** [comment]
1. `||http://cdn.viglink.com/api/vglnk.js` is not neccessary if you use uBO with default settings, the 
filter `/vglnk.js` in EasyPrivacy already blocks that request.
2.   the filter `proboards.com##script:inject(abort-on-property-read.js, vglnk)`, **or** the filter
`proboards.com##script:inject(abort-current-inline-script.js, $, vglnk)` should fix your issue without any 
error message.
3. @gorhill do you always prefer `abort-current-inline-script.js`?

**Comment by gorhill** [comment]
> @gorhill do you always prefer `abort-current-inline-script.js`?

It's a judgment call -- each have their advantages/disadvantages and on a per-case basis -- so it's up to you.

**Comment by theinstantmatrix** [comment]
Anti-Adblock Script - Message can be closed

`https://ssblifeitself.proboards.com/thread/3403/joker-steal-heart`

Scroll down to trigger message. If it isn't showing, clear cookies

**Comment by krystian3w** [comment]
> https://github.com/uBlockOrigin/uAssets/blob/bfcc3c99787d7a79fa9c67b80e392f9cf6149d16/filters/filters.txt#L3293

I think possible replace by:
```adb
freeforums.net,boards.net,proboards.com##^script:has-text(cdn.viglink.com/api)
freeforums.net,boards.net,proboards.com##+js(remove-node-text, script, cdn.viglink.com/api)
```

Due `acs` on jQuery `$` no longer works at `https://dobreprogramy.freeforums.net/` / `https://gdforum.freeforums.net`.
