### ISSUE TITLE
"uBlock filters – Privacy" VS "pochta.ru"

### ISSUE THREAD

**Issue by serrufs** [uBlockOrigin/uAssets#6613]
The site 
`https://www.pochta.ru/tracking` 
does not work correctly when the "uBlock filters - Privacy" filter is turned on.
If you are registered on this website and logged in, then when you turn on this filter, it hides the list of your tracking.

**Comment by mapx-** [comment]
We cannot reproduce the issue, so you should post here (enable the logger, refresh the page) the blocked elements (a screenshot)

**Comment by serrufs** [comment]
"uBlock filters – Privacy" = On
![001](https://user-images.githubusercontent.com/15975674/69480907-edd12000-0e1c-11ea-9e83-f73a63c9abdb.JPG)
"uBlock filters – Privacy" = OFF
![002](https://user-images.githubusercontent.com/15975674/69480908-ee69b680-0e1c-11ea-9d46-2a5100878726.JPG)

**Comment by mapx-** [comment]
Does this filter fix your issue ?
`@@||googletagmanager.com/gtm.js$script,domain=pochta.ru`

**Comment by serrufs** [comment]
No ((
![003](https://user-images.githubusercontent.com/15975674/69481236-a3ea3900-0e20-11ea-8557-16c06bc86a6f.JPG)

**Comment by mapx-** [comment]
add also
`@@||google-analytics.com/analytics.js$script,redirect=domain=pochta.ru`

if works keep only this filter, remove the other one and test again

**Comment by serrufs** [comment]
>  `@@||google-analytics.com/analytics.js$script,redirect=domain=pochta.ru`

uBlock Origin v1.24.0 does not understand it as a filter
![0000](https://user-images.githubusercontent.com/15975674/69481744-e1e95c00-0e24-11ea-9832-c3a7cb9a3b98.JPG)

**Comment by mapx-** [comment]
see again the filter above, I corrected it

**Comment by serrufs** [comment]
Together, these filters yielded results!
Separately, the second does not work without the first

@@||googletagmanager.com/gtm.js$script,domain=pochta.ru
@@||google-analytics.com/analytics.js$script,domain=pochta.ru
