### ISSUE TITLE
How to auto skip video ads => https://series-d.com

### ISSUE THREAD

**Issue by Fuyuppe** [uBlockOrigin/uAssets#6614]
`https://series-d.com/psychopath-diary/`

### Describe the issue

This website has a problem again 
I can't auto skip video ads on this website

### Screenshot(s)

![ภาพ](https://user-images.githubusercontent.com/43577606/69468198-e3336e00-0dbd-11ea-86d1-bd3d21b1f365.png)

### Versions

- Browser/version: firefox 70.0.1
- uBlock Origin version: 1.23.0

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes
Thanks in advance

**Comment by llacb47** [comment]
Best I could do:

```
series-d.com##+js(nano-sib, curAd)
series-d.com##+js(window.open-defuser)
```

**Comment by ZaphodBeebblebrox** [comment]
I have been messing around with it for a bit, and I can almost get it working. If you set `curAd` to a high value, it does not play any ads. However, the `let curAd = 0;` in `inzjwp.js` errors, so the rest of the script cannot run, which causes there to be no video player. So I can do it with a breakpoint, but not with `set`.

**Comment by mapx-** [comment]
using the current:
- I have to click skip 3 times and then the video is starting
- I get anti adblocking too, I'll fix it

**Comment by Fuyuppe** [comment]
> 
> 
> using the current filters:
> 
>     * I have to click skip 3 times and then the video is starting
> 
>     * I get anti adblocking too, I'll fix it

So don't have solution to fix it right ?
I alway to click 3 times to watching video right ?

**Comment by mapx-** [comment]
I guess you need a custom solution (userscript) or to use adguard (which permits injecting "random" user scripts - uBo is allowing only its scriptlets )

**Comment by Fuyuppe** [comment]
> 
> 
> I guess you need a custom solution (userscript) or to use adguard (which permits injecting "random" user scripts - uBo is allowing only its scriptlets )

So it mean if I use adguard instead uBo. 
You can fix this problem to me right?

**Comment by mapx-** [comment]
You can try asking for help at adguard repository.

**Comment by Fuyuppe** [comment]
> 
> 
> You can try asking for help at adguard repository.

Last qeustion 
uBo and adguard can using both together ? 
or it has affect

**Comment by mapx-** [comment]
Never use 2 adblockers together.

**Comment by uBlock-user** [comment]
> If you set curAd to a high value, it does not play any ads.

Setting it to `4` basically means all ads have played but because its defined via `let`, that will break the player.

**Comment by uBlock-user** [comment]
I also tried removing ad property from the 'source' array via my [property-pruner scriptlet](https://github.com/uBlock-user/uBO-Scriptlets/blob/master/scriptlets.txt#L501), that did what I was expecting but the first ad is somehow still inserted, so got stuck there.

Adguard is using ||series-d.com/vod/$replace=/(inzplyr\.setup\(\{'ad':\[)[\s\S]*?]/\$1]/ as per https://github.com/AdguardTeam/AdguardFilters/commit/9d2af8ce3d21aa484fd6f2915422f45808a3abef#diff-48cd1634a8224e1bf6ce278856af9f2aR6371

**Comment by mapx-** [comment]
However `$replace` is supported only by `AdGuard's Firefox add-on`.

**Comment by uBlock-user** [comment]
Maybe now's the time to consider adding `$replace`

**Comment by llacb47** [comment]
yes, then instead of defusing the script, the call to `inzplyr.setup` could be rewritten before execution

**Comment by huyszn** [comment]
A lot of ad banners are displayed at the top of the site.
