### ISSUE TITLE
kissanime.ru (media is hidden due adblock)

### ISSUE THREAD

**Issue by Iaycomand** [uBlockOrigin/uAssets#6617]
### URL(s) where the issue occurs

`https://kissanime.ru/Anime/Boku-no-Hero-Academia-4th-Season/Episode-067?id=163863&s=beta`

### Describe the issue

The media is hidden and left a blank space and it works normally without the adblock.

### Screenshot(s)

`https://imgur.com/kbbCgR5`
`https://imgur.com/I1jyFux`

### Versions

- Browser/version: Google chrome Version 78.0.3904.108 (Official Build) (64-bit).
- uBlock Origin version: v1.23.0.

### Note
Someone from reddit came up with this solution but it's not permanent.
He added this line to the console:
`document.getElementById("divContentVideo").style.display = "inline";`
But is it possible to have this as permanent resolve please?

**Comment by Iaycomand** [comment]
I've updated the filter lists and the issue still remain the same.
Do I have to do anything else?

**Comment by mapx-** [comment]
check the logger if you still see this filter

`kissanime.ru##+js(abort-on-property-read.js, InitCloseButton)`

or add directly (in case your lists are still outdated)
`kissanime.ru#@#+js(abort-on-property-read.js, InitCloseButton)`

**Comment by mapx-** [comment]
nevermind, update again your filters in 5 minutes, I added @uBlock-user filter from
https://www.reddit.com/r/uBlockOrigin/comments/e0mzre/kissanime_is_now_not_loading_the_videos/

**Comment by uBlock-user** [comment]
@mapx- They're hiding `#divContentVideo` via an inline-script, not sure removing that filter would fix something that's hidden on purpose.

**Comment by mapx-** [comment]
First I removed that filter, but I got after 30 seconds anti adb stuff so I added your filter
