### ISSUE TITLE
Malvertising on watch32.is

### ISSUE THREAD

**Issue by WormChickenWizard** [uBlockOrigin/uAssets#6619]
### URL(s) where the issue occurs

`http://watch32.is`

### Describe the issue

Malwarebytes keeps picking up malvertising from websites called madslims.com (198.134.112.243) on port 64151 and ye185hcamw.com (198.134.112.241) on port 64022

### Versions

- Browser/version: Version 78.0.3904.108 (Official Build) (64-bit)
- uBlock Origin version: v1.23.0

**Comment by okiehsch** [comment]
`ye185hcamw.com` is already blocked in `EasyList`.
I will block `madslims.com`.
