### ISSUE TITLE
Antiblock.org anti-adblocker on liferayiseasy.blogspot.com

### ISSUE THREAD

**Issue by josephcsible** [uBlockOrigin/uAssets#662]
### URL(s) where the issue occurs

`http://liferayiseasy.blogspot.com/`

### Describe the issue

A new anti-adblocker (antiblock.org) prevents access to sites it's installed on.

### Versions

- Browser/version: Firefox 55.0.2
- uBlock Origin version: 1.14.0

### Settings

- None (tested on stock profile)

### Notes

Here's a prettified version of the responsible code (note that `THE_ELEMENT`, `THE_ID`, and `THE_ARRAY` are dynamically generated): https://gist.github.com/josephcsible/df854ca12bb3e5a9aefb1083d044d29f

This filter seems like a good way to fix it:
```
liferayiseasy.blogspot.com##script:inject(addEventListener-defuser.js,load,getComputedStyle)
```
I'm wondering if there's some generic way we can put a stop to this, or if we'll have to list every host that ever starts using antiblock individually.

**Comment by okiehsch** [comment]
Thanks for investigating.
Does
````
@@||liferayiseasy.blogspot.com^$generichide
@@||resources.blogblog.com/*.png$image,domain=liferayiseasy.blogspot.com
````
work for you?

> I'm wondering if there's some generic way we can put a stop to this

No ;).

**Comment by okiehsch** [comment]
I forgot to mention, your filter works, but gorhill has [stated](https://github.com/uBlockOrigin/uAssets/commit/f340633dc681d6e0fb696359e06f5498dd5e0c39#commitcomment-20429199) that he prefers the genericide solution if
applicable.

**Comment by josephcsible** [comment]
Yes, your filters work for me. (Personally, I'd rather break their scripts than disable element hiding, but unless sites start abusing that, I guess it doesn't matter.)
