### ISSUE TITLE
yusepjaelani.blogspot.com [Anti adblock]

### ISSUE THREAD

**Issue by RaveN0X87** [uBlockOrigin/uAssets#6621]
URL(s) where the issue occurs
`https://yusepjaelani.blogspot.com/?kareeI=aHR0cHM6Ly9rdWxpYWhtYXRlbWF0aWthLm15LmlkL2RyaXZlLz9pZD1TbkF2VlZweVNWVlpRMk5xTWpBeVVHZG1OWGhIV0VKdVRXcEtOMVZHV1hGWFpVTjFVbXB6UWpCVGNucG5aMVZZVG5OQmIzQXhXbmRYTUVKelFYWkJXQT09fHxHbyBUbyBMaW5rfHx8fF9zZWxmfHx0cnVlfHx0cnVlfHx0cnVlfHx0cnVlfHxmYWxzZXx8`

Describe the issue
Anti adblock + blocking generate link

Versions
Browser/version: chrome 78.0.3904.108 (Official Build) (64-bit)
uBlock Origin version: v1.23.0

Settings
uBO's default settings

**Comment by uBlock-user** [comment]
```
yusepjaelani.blogspot.com###showadblock, .modal-backdrop
yusepjaelani.blogspot.com##body:style(overflow: auto !important)
```

**Comment by okiehsch** [comment]
There are two about:blank popups if one clicks "GotoLink", so you will have to click three times before you can go to your destination link.
