### ISSUE TITLE
https://www.underarmour.co.uk/en-gb/ blocked tracking prompt

### ISSUE THREAD

**Issue by adblockeruser1234** [uBlockOrigin/uAssets#6622]
### URL(s) where the issue occurs

`https://www.underarmour.co.uk/en-gb/`

### Describe the issue

When I visit 
`https://www.underarmour.co.uk/en-gb/` 
without uBlock Origin enabled a cookie/tracking dialogue appears, which you can click through and then interact with the site as usual (presumably whilst being tracked).

If I enable uBlock Origin this dialogue box is blocked and is not shown to the user. However, when I try to click any buttons on the site I can't, as there's an invisible layer over them. I can delete this layer in Firefox -> right click -> inspect element -> press delete key, but I have to do this on every page I visit on the site. Please can you fix uBlock Origin's interaction with this site.

### Versions

- Browser/version: MacOS Mojave 10.14.6, FireFox 70.0.1 (64-bit)
- uBlock Origin version: 1.24.0

### Settings

- Under "filter lists" everything is ticked (when I first visit the page/don't expand any of the +'s) except "ignore generic cosmetic filters" and "import..."

### Notes

Disabled uBlock Origin and the site worked as expected.

**Comment by mapx-** [comment]
fanboy's cookie list issue
@ryanbr 

add
```
underarmour.co.uk#@#.truste_overlay
underarmour.co.uk#@#.truste_box_overlay
```
