### ISSUE TITLE
wrong blocking behaviour on cyberpower site

### ISSUE THREAD

**Issue by abulka** [uBlockOrigin/uAssets#6623]
### URL(s) where the issue occurs

`https://www.cyberpower.com/au/en/company/worldwide`

### Describe the issue

Click on support / call us via the menu

but no phone numbers appear with ad blocking enabled.  Turning off ad blocking reveals lots of phone numbers!

### Versions

- Version 78.0.3904.108 (Official Build) (64-bit) Mac
- uBlock Origin version: 1.23.0

### Notes

Phone numbers are not an AD and should not be blocked.

**Comment by okiehsch** [comment]
Update the `uBO-unbreak` list, should work after that.

**Comment by abulka** [comment]
Thanks. Not sure how to do that - I found [this wiki page](https://github.com/gorhill/uBlock/wiki/Tutorial:-how-to-unbreak-a-site-using-the-dynamic-filtering-pane) but that seems very complex, so I simply disabled uBlock on the site using the GUI.

I was hoping that by reporting the site, it would be added to some global list and benefit other users.

**Comment by okiehsch** [comment]
`uBO-unbreak` is a "global list", i.e. it is enabled  by default for all `uBO-users`.
I added a filter that will fix your issue to that list https://github.com/uBlockOrigin/uAssets/commit/edbde988209d700a1b07d8f490fcbff714dd1a47

You can manually update any filter list by following this instructions. https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now
