### ISSUE TITLE
uploadship.com

### ISSUE THREAD

**Issue by lyndmi** [uBlockOrigin/uAssets#6625]
### URL(s) where the issue occurs

`https://www.uploadship.com/4eb2b8a4a8f17c05`

### Describe the issue

Countdown is too long

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24647715/69545628-758c6b00-0f92-11ea-8a08-461a04b9b2ec.png)

### Versions

- Browser/version: 65.0.3467.38
- uBlock Origin version: 1.23.0

### Settings

- Default

### Notes
Request to boost countdown if possible

**Comment by uBlock-user** [comment]
`uploadship.com##+js(nano-sib, /.?/, 1000, 0.01)`

**Comment by mapx-** [comment]
Are you able to finish the complete job ? (downloading the file)

**Comment by uBlock-user** [comment]
There's another timer in the form of clock animation losing the dark blue color to light blue, server-sided or client-sided not sure. Even after completing that, Click her to download loads the same page again and again...

**Comment by okiehsch** [comment]
> Are you able to finish the complete job ? (downloading the file)

No, clicking download leads to an infinte reloading loop on my end.

**Comment by lyndmi** [comment]
Ok thanks for trying
