### ISSUE TITLE
anpal.gov.it should be removed from lists.

### ISSUE THREAD

**Issue by DeXeDeXeD** [uBlockOrigin/uAssets#6626]
### URL(s) where the issue occurs

`https://www.anpal.gov.it/cittadini/servizi/dichiarazione-di-disponibilita-al-lavoro`

### Describe the issue

uBlock blocks anpal.gov.it. uBlock should not block this site because Anpal is an italian public authority. The page was fully white but after I whitelisted the page, it has no longer any issues with my browsers, even whitout whitelisting it. But the site should still be removed from lists.

### Screenshot(s)
![anpal](https://user-images.githubusercontent.com/21258130/69546158-7a055380-0f93-11ea-9ccc-d7f97689e0c3.jpg)

### Versions

- Browser/version: 78.0.3904.108 (Official Build 64 bit)
- uBlock Origin version: 1.23.0

### Settings

- Default settings

**Comment by gwarser** [comment]
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +155 | /ruxitagentjs_ | -- | `www.anpal.gov.it` | 1 | script | `https://www.anpal.gov.it/ruxitagentjs_ICA2SVfqru_10179191120132458.js` |

</details>
