### ISSUE TITLE
https://multiup.org/

### ISSUE THREAD

**Issue by maxvlas** [uBlockOrigin/uAssets#6627]
### URL(s) where the issue occurs

https://multiup.org/en/mirror/8a997f0d5accc6868e09225006b95b3c/1Password.7.3.684..rar

### Describe the issue

Here I decided to download. after clicking on the download, I got a window (screenshot below)

### Screenshot(s)
![2019-11-25_184300](https://user-images.githubusercontent.com/11572859/69559863-c9f81080-0fbb-11ea-8e35-134d7eb60f5c.png)

### Versions

- Browser/version: Google Chrome Version 78.0.3904.108 (Official Build), (32 bit)
- uBlock Origin version: uBlock Origin 1.23.0

### Settings

![2019-11-25_184454](https://user-images.githubusercontent.com/11572859/69560116-48ed4900-0fbc-11ea-9683-e2bf7ef535c8.png)

### Notes

The uBlock filters rules for this site are probably outdated and need to be edited.

**Comment by uBlock-user** [comment]
`multiup.org##.mfp-bg, .mfp-wrap`

**Comment by ghajini** [comment]
How to stop ad redirects on reaching this website URL,no matter how I block their ad sites, they come up with new revolving ad server

`https://multiup.org/download/399e61c35204186855cf20c48b60c1c2/`

**Comment by okiehsch** [comment]
Does
`multiup.org##+js(nostif, location, 4000)`
work for you?

**Comment by ghajini** [comment]
With this `multiup.org##+js(nostif, location, 4000)`
Iam stuck at ***just a moment*** cloudfare page,can you pass this page

**Comment by okiehsch** [comment]
Yes, I am stuck too. I did not notice it because I tried the filter after already passing the test.
`multiup.org##+js(nostif, window.location, 4000)`
works for me.

**Comment by ghajini** [comment]
Thus far no breakage with

`multiup.org##+js(nostif, window.location, 4000)`

**Comment by ghajini** [comment]
> How to stop ad redirects on reaching this website URL,no matter how I block their ad sites, they come up with new revolving ad server
> 
> `https://multiup.org/download/399e61c35204186855cf20c48b60c1c2/`

This is back

`https://multiup.org/download/acec1908f1aa546138ea63d99a505114/`

**Comment by mapx-** [comment]
does this help ?
`multiup.org##+js(nostif, mightThrow)`

**Comment by uBlock-user** [comment]
Won't work, race condition.

**Comment by mapx-** [comment]
was working only for FF, this 1 seems ok for both FF / chrome
`multiup.org##+js(nostif, submit)`

**Comment by uBlock-user** [comment]
> was working only for FF,

Not on my end on Firefox, the script is the very first that gets parsed. If it worked for you, then it was only by chance.

**Comment by ghajini** [comment]
1st suggested filter not work

filter `multiup.org##+js(nostif, submit)`
 here partially work, sometimes redirection to ads

@mapx- 
Check at this URL ,
`https://www.multiup.org/download/e1e676bac97803350aac4c17ebb0874f/MBUP16HBRFMD300MB.mkv`

**Comment by uBlock-user** [comment]
`multiup.org##+js(nostif, /^/)` seems to be working always, not seeing any visible breakage.

**Comment by uBlock-user** [comment]
@ghajini try `multiup.org##+js(nostif, /submit/)`

**Comment by okiehsch** [comment]
`multiup.org##+js(nostif, /^/)` breaks the indication if a link is still valid or not,
Example:
 `https://multiup.org/en/mirror/cf7300ee9c478bedb13d23ae6b737a63/DDLValley.me_the.chi.s03e03.720p.web.h264-btx.mkv`

**Comment by uBlock-user** [comment]
@okiehsch any breakage with `multiup.org##+js(nostif, /submit/)`

**Comment by okiehsch** [comment]
Nothing obvious on my end.

**Comment by uBlock-user** [comment]
Just to be a little safe, we can go with `multiup.org##+js(nostif, /.submit()/)`

**Comment by ghajini** [comment]
I have slow internet please test at file not found URL and valid download page URL

**Comment by uBlock-user** [comment]
I tested at both, no obvious breakage and no race condition either.
