### ISSUE TITLE
abandonmail.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#6628]
### URL(s) where the issue occurs

`https://www.abandonmail.com/`

### Describe the issue

Blocks Private tab

### Screenshot(s)

<img width="1127" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/69571145-a768f600-0fc1-11ea-8145-2593ce746da4.PNG">

### Versions

- Browser/version: Firefox 70.0.1
- uBlock Origin version: v1.24.2

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3888344/Settings.txt)

**Comment by mapx-** [comment]
test
`abandonmail.com##+js(aopr, indexedDB.open)`

**Comment by JobcenterTycoon** [comment]
yes it works, thank you

**Comment by JobcenterTycoon** [comment]
They block private tabs again

**Comment by mapx-** [comment]
test these filters (not together), see if there are breakages

`abandonmail.com##+js(aost, indexedDB, )`
then
`abandonmail.com##+js(aopr, indexedDB.open)`

**Comment by JobcenterTycoon** [comment]
both works
