### ISSUE TITLE
Block .online-metrix.net

### ISSUE THREAD

**Issue by timkgh** [uBlockOrigin/uAssets#6629]
### URL(s) where the issue occurs

`https://www.coinbase.com/` (but it's not always there, or maybe you have to be logged in)

### Describe the issue

online-metrix.net is a bad tracker. Does device fingerprinting, others accuse it of malware. It seems to track via DNS requests to various domains of the form:
`<xxx...>-<yyy...>.d.aa.online-metrix.net` (but many other subdomains before online-metrix.net

I don't think anybody will miss them if you just block online-metrix.net

### Screenshot(s)

None, it happens in the background.

### Versions

- Browser/version: Chrome
- uBlock Origin version: 78.0.3904.108

### Settings

defaults

### Notes

Checked DNS logs, these tracking domains always resolve to 127.0.0.1

**Comment by timkgh** [comment]
This is what they do:
https://developer.paysafe.com/en/classic-apis/hosted-payments/test-and-go-live/implementing-threatmetrix-for-a-silent-post-order/

**Comment by ZaphodBeebblebrox** [comment]
Already blocked in `Peter Lowe’s Ad and tracking server list`, which is enabled by default.
