### ISSUE TITLE
YouTube Sidebar Ad Placeholder (Semiblocked)

### ISSUE THREAD

**Issue by PolarisBeaver** [uBlockOrigin/uAssets#663]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.youtube.com/watch?v=eHMHxECElDo`

### Describe the issue

A box where an ad would appear is sucessfully blocked by uBlock, but the element is not entirely removed.

### Screenshot(s)

![2017-09-01 06_40_40-sonic mania_ ice cap zone remix theme extended - youtube](https://user-images.githubusercontent.com/10394552/29972568-60a4c5cc-8ee1-11e7-96bb-de4057e0ea61.png)
![2017-09-01 06_44_18-sonic mania_ ice cap zone remix theme extended - youtube](https://user-images.githubusercontent.com/10394552/29972569-60a7be30-8ee1-11e7-970a-f43dd803f171.png)

### Versions

- Browser/version: Google Chrome 60.0.3112.113 (Official Build) (64-bit)
- uBlock Origin version: 1.13.8

### Settings

![Settings](https://user-images.githubusercontent.com/10394552/29598151-ee29cbbc-877b-11e7-9e11-9fa09117decb.png)

### Notes

The ad is blocked, but the element is not being removed entirely.

**Comment by Hrxn** [comment]
Manually enabled the new YouTube site design?

**Comment by SMed79** [comment]
@PolarisBeaver Disable all other installed extensions, keep only uBo and test again.

**Comment by ghajini** [comment]
Its privacy badger interfering

**Comment by okiehsch** [comment]
I can reproduce only if I also use privacy badger, like @ghajini sais, so this is not a uBO-filter issue.

**Comment by PolarisBeaver** [comment]
Please open the issue again. I disabled 100% of all my extensions except for uBlock Origin, and it still is not removing the empty space. Yes, "technically" there is no ad there. But the empty space is there, and this problem never happened before the youtube redesign.

![2017-09-02 16_56_48-sonic mania_ ice cap zone remix theme extended - youtube](https://user-images.githubusercontent.com/10394552/29999491-cfe43f52-8fff-11e7-8b3d-d3dfbd4e1b34.png)

**Comment by PolarisBeaver** [comment]
Additionally, I removed all of my custom filters just to see. No change.

**Comment by PolarisBeaver** [comment]
tagging @okiehsch just in case it doesn't notify

**Comment by okiehsch** [comment]
@PolarisBeaver the only way to reproduce your screenshot on my end is to allow this request.
![yout](https://user-images.githubusercontent.com/16838044/29999628-542d7e22-9050-11e7-964b-52eb81796be4.PNG)
This request is blocked if you use uBO with a default setup, can you check your logger if it is blocked on your end.

**Comment by SMed79** [comment]
@PolarisBeaver test using **chrome portable** https://portableapps.com/apps/internet/google_chrome_portable
