### ISSUE TITLE
Emmi Shop Website Showing Ads

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uAssets#6631]
This website is still showing ads `https://www.emmi.rs/naslovna_stranica.1.html`

**Comment by ZaphodBeebblebrox** [comment]
```
||emmi.rs/upload/images/banners/$image
emmi.rs##[href*="mmi.rs/landingpage"]
emmi.rs###flashBanner
```
This does not require any uBO specific filters, so it should be reported to the relevant regional list.

**Comment by mapx-** [comment]
@ryanbr
