### ISSUE TITLE
Unbreak CrossCountry Trains

### ISSUE THREAD

**Issue by chrisgid** [uBlockOrigin/uAssets#6632]
### URL(s) where the issue occurs

`https://www.crosscountrytrains.co.uk`

### Describe the issue

The script `/js/analytics.js` is being blocked breaking all functionality on the 'Find my train' panel

### Screenshot(s)

![fyt](https://user-images.githubusercontent.com/15443972/69737634-a3a5b280-112c-11ea-8461-68b081200b43.png)

### Versions

- Browser/version: Chrome 78.0.3904.108
- uBlock Origin version: 1.23.0

### Settings

Default

### Notes

The filter below seems to fix the issue:
`@@||crosscountrytrains.co.uk/js/analytics.js$script`

**Comment by mapx-** [comment]
@ryanbr
