### ISSUE TITLE
shrtwin.com [Anti-Adblock] [NSFW]

### ISSUE THREAD

**Issue by doio** [uBlockOrigin/uAssets#6635]
### URL(s) where the issue occurs
`http://shrtwin.com/MT4V`

### Versions

- Browser/version: Firefox 68.2.0esr
- uBlock Origin version: uBlock Origin 1.24.3b1

**Comment by dumbusernameidk** [comment]
`@@||shrtwin.com^$ghide`
`shrtwin.com##+js(aopr, app_vars.force_disable_adblock)`

also popups `shrtwin.com##+js(window.open-defuser)`

also can't right click.
