### ISSUE TITLE
gmx.net filter

### ISSUE THREAD

**Issue by Procyon-b** [uBlockOrigin/uAssets#6637]
This is related to #6541 but I feel that since that issue is closed, my comment will be unnoticed. 
Here is the comment I made there.

While using gmx.net webmail, I see `+js(json-prune, enabled, force_disabled)` appearing in the logger.

The current filter is:
```
! https://github.com/uBlockOrigin/uAssets/issues/6541
focus.de,gamesaktuell.de,gmx.*,kino.de,spieletipps.de,videogameszone.de,web.de##+js(json-prune, enabled, force_disabled)
```

This is unnecessary on that site.

Could you fix this by refining the domain and use `www.gmx.*` in the filter instead of `gmx.*`.
The filter target is too wide. It's like shooting at all `.com` when you are aiming at `github.com`.
And narrowing it to `www.gmx.*/magazine` could even be better (but that, I'm not sure).

**Comment by krystian3w** [comment]
>And narrowing it to `www.gmx.*/magazine` could even be better (but that, I'm not sure).

If mail service no works on subdomain* we can't create exception / exclusion.

--

\* - e.g.: `mail.gmx.net`

**Comment by krystian3w** [comment]
@lain566 you have mail on GMX and web client works on only `mm.gmx.net` subdomain?

**Comment by Procyon-b** [comment]
It's not an issue of not working. It's the fact that the filter is applied to pages and subdomain where it's not needed.
I haven't followed the original problem, but from what I can read, the example page is on `https://www.gmx.net/magazine/`. I don't see the point of targeting `*.gmx.*` instead of `www.gmx.*`. That's all I say.  ;)
Gmx has other subdomains ; at least 6 for the webmail portal.

**Comment by lain566** [comment]
I don't have a GMX mail account.
@Procyon-b You say it is unnecessary, but what is the breakage or does it just bother you that the filter is applied to all subdomains?

**Comment by Procyon-b** [comment]
Let me be clear.   :)

The original problem, as described in #6541 , is that videos were blocked on www.gmx.net/magazine, which is a news portal.
The filter created for this issue applies to all gmx.* subdomains. It doesn't cause any problem on the webmail portal, but it is useless there, since, afaik, there are not video played on that site (not a www.gmx.* domain).

The reasoning behind my remarks is that, if the same logic is applied to most situations (applying fixes to a wider domain range than the original problem) we might end up sometimes with filters causing problems elsewhere.

Beyond that it doesn't bother me.

**Comment by lain566** [comment]
Ok, I did not add the filter `gmx.*` I don't know the site either, I'm not sure if the site could use any subdomain to show the videos, so I would not like to make a decision without first consulating it with the person who added the filter, especially if the filter is not causing any breakage.
@okiehsch Do you think we should modify  `gmx.*` filter to `www.gmx.*`?

**Comment by mapx-** [comment]
If we know the free video subdomains we could add filters like this one:
`search.gmx.com#@#+js(json-prune, config, server)`

**Comment by krystian3w** [comment]
or `~search.gmx.com` uBO translate this into `domain#@#` (*ABP / AdGuard nope**).

**Comment by okiehsch** [comment]
> The reasoning behind my remarks is that, if the same logic is applied to most situations (applying fixes to a wider domain range than the original problem) we might end up sometimes with filters causing problems elsewhere.

I don't think I see the same potential issues, we always use script:injections for the whole site and never check if some subdomains don't really need the filter.

Saying all that you have pointed out that we can change it to `www.gmx.*##+js(json-prune, config, server)` and so I am not against modifiying the filter.

What I have observed is that if I add
`www.gmx.*##+js(json-prune, config, server)`
to my filter list and disable `uBO-filters`. I see this in the logger.
![image](https://user-images.githubusercontent.com/16838044/69891619-1dd96100-12fe-11ea-9f4d-c4744e666295.png)
I can reproduce with Chromium and Firefox 
@gorhill

**Comment by Procyon-b** [comment]
@okiehsch 
I have already seen this behavior ("could not be found") while playing with my user filters. I have been able to reproduce, but IIRC closing and reopening the logger fixes the issue (when reloading the page).
I think it happens when a list filter is replaced by a similar (but not identical) user filter.

**Comment by okiehsch** [comment]
> I think it happens when a list filter is replaced by a similar (but not identical) user filter.

Not on my end.
I have committed the new filter, so now to reproduce I just have to update the `uBO-filter` list and go to `gmx.com`.

**Comment by Procyon-b** [comment]
I have found a way to reproduce it.
Load any page with the logger opened. Choose a line that is filtered. Clic to see which filter has been applied. Go to uBo dashboard, disable that list, "update now". Go back to the logger, and open the same filter dialog. Now it displays "Static filter ... could not be found in any of the currently enabled filter lists"

If you have the exact same filter in another list (or in the user filters) the dialog displays that list's name instead.

**Comment by okiehsch** [comment]
Well, right now I don't have any gmx-related filter in my filter list.
The only script:inject filter for that site is 
`www.gmx.*##+js(json-prune, config, server)`
in `uBO-filters`. If I go to `gmx.com`
![image](https://user-images.githubusercontent.com/16838044/69892656-1ae36e00-1308-11ea-8a30-2fc39ec6f9e9.png)

**Comment by lain566** [comment]
I can reproduce the same as **okiehsch** 
If i go to `gmx.com`, `gmx.net` or `gmx.at`

**Comment by Procyon-b** [comment]
Same here.
All my lists are enabled and I see the "could not be found" message.

**Comment by gwarser** [comment]
> I have found a way to reproduce it.
> Load any page with the logger opened. Choose a line that is filtered. Clic to see which filter has been applied. Go to uBo dashboard, disable that list, "update now". Go back to the logger, and open the same filter dialog. Now it displays "Static filter ... could not be found in any of the currently enabled filter lists"

This is how it should work.

**Comment by Procyon-b** [comment]
@gwarser Correct. :)  In that situation the text is self-explanatory.

But @okiehsch example doesn't fall into that category.

**Comment by krystian3w** [comment]
glitch with logger exisist also in 1.23 `Commit/a5601b8`

**Comment by gwarser** [comment]
This started with https://github.com/gorhill/uBlock/commit/a73dd0a9f26df59cfb4b68e98d1184ac042c90ea and obviously before this commit scriptlet is not even logged.

**Comment by gwarser** [comment]
`^gmx\.\*$` does not match `www.gmx.com` in `reverselookup-worker.js`

**Comment by okiehsch** [comment]
Can be closed, the issue of the OP has been fixed and the logger issue has been opened in https://github.com/uBlockOrigin/uBlock-issues
