### ISSUE TITLE
tv.kakao.com videos not playing due to daumcdn.net/tiara block

### ISSUE THREAD

**Issue by Infinitay** [uBlockOrigin/uAssets#6638]
### URL(s) where the issue occurs

`https://tv.kakao.com/channel/3049413/cliplink/404295898`

### Describe the issue

Video playback is being blocked on tv.kakao due to a block on on `https://t1.daumcdn.net/tiara/js/v1/tiara.min.js` by the EasyPrivacy filter according to uBlock's logger. For further clarification, the player frame gets loaded, but the video does not, and when I say "filter" what I really mean is that that specific url containing tirara.min.js. 

### Screenshot(s)

What I see when filter is enabled: https://i.imgur.com/iWtw4Aq.png
What I see when the filter is disabled: https://i.imgur.com/Uaz5ijk.png

### Versions

- Browser/version: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.23.0

### Settings

- The only major change is adding Nano Defender integration

### Notes

As I said, by allowing tiara.min.js via `@@||t1.daumcdn.net/tiara/js/v1/tiara.min.js$script,domain=tv.kakao.com` filter or [clicking allow under the URL rule tab](https://user-images.githubusercontent.com/6964154/69906179-6e4bcf80-138d-11ea-9c8b-f54906f62395.png) the video loads properly.

**Comment by mapx-** [comment]
@ryanbr

**Comment by Infinitay** [comment]
I would like to bring up that I noticed by adding that filter, it allows one tracking image to be requested that isn't blocked by the EasyPrivacy filter as I covered at the very bottom of https://github.com/easylist/easylist/issues/4402. 

So adding `||track.tiara.kakao.com/queen/footsteps$image,domain=tv.kakao.com` blocks that new tracking image and still allows videos to be loaded properly.

**Comment by Infinitay** [comment]
@mapx- 
I probably should have tagged you in the post I just made, but I don't know if editing the post will still notify you.

My mistake.

**Comment by krystian3w** [comment]
> post will still notify you.

Still if no unsubscribe issue also possible have subscribe notify about comment on any commit or this is visible in "admin" repository tool.

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/commit/6e17e1f87b1b46ff8dca70a3670daebf0e7a770c - we can remove remove from uBO unbreak in `[9 - 15] December 2019`.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0c247fe4352d6ee2cca054ffb2ba1b8742970d02
