### ISSUE TITLE
[Anti-Adblock] lapresse.ca

### ISSUE THREAD

**Issue by ACapitalOffense** [uBlockOrigin/uAssets#6640]
### URL(s) where the issue occurs

`https://www.lapresse.ca/actualites/politique/201912/02/01-5252031-partielle-dans-jean-talon-la-population-a-fait-son-choix.php`

### Describe the issue

Anti-adblock on every news article

### Screenshot(s)

![image](https://user-images.githubusercontent.com/58451687/70012990-1b684880-1544-11ea-859b-20242be8157f.png)

### Versions

- Browser/version: Chrome 78.0.3904.108
- uBlock Origin version: 1.23.0

### Settings

- Default

### Notes

I have tried blocking every element of the anti-adblock, but it still prevents the user from scrolling down afterwards. I have also disabled javascript on the website, but it prevents images from loading properly on the homepage. I have tried using Nano Defense with the default settings, but it had no effect on the anti-adblock pop-up.

**Comment by okiehsch** [comment]
I can't reproduce, I can see that the site uses sourcepoint.
Does adding
`lapresse.ca##+js(aopr, _sp_._networkListenerData)`
to your filter list fix the issue on your end?

**Comment by ACapitalOffense** [comment]
Your solution appears to have solved the problem! Thank you very much. Would adding website.com##+js(aopr, _sp_._networkListenerData) to my filter list solve a similar problem on any other website that uses sourcepoint?

**Comment by mapx-** [comment]
> Would adding website.com##+js(aopr, sp._networkListenerData) to my filter list solve a similar problem on any other website that uses sourcepoint?

There could variations, so it's always better to report here (`uAssests issues`) to include the fixes in the official list
