### ISSUE TITLE
(Annoyances) Christmas sparkle banner on Norwegian newssites

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#6642]
### URL(s) where the issue occurs

Most (if not all) newssites owned by `Amedia`, incl. `https://www.ba.no/`, `https://www.op.no/`, and `https://www.ifinnmark.no/`, among more than a dozen others.

### Describe the issue

During the month of December, the logo banner on top has animated sparkles that are pretty bright and attention-grabbing.

I propose this entry for uAssets Annoyances: `##foxfield-xmas`. For simplicity's sake, and in the off-chance that any non-`Amedia` sites are also using such sparkly banners, I believe the entry should be generic.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/22780683/70142529-b7f02f00-1699-11ea-8bad-805feee1ef84.png)

### Versions

- Browser/version: Chrome 78.0.3904.108 64-bit for Windows 
- uBlock Origin version: Nano Adblocker 1.0.0.130 + Nano Defender 15.0.0.170

### Settings

![image](https://user-images.githubusercontent.com/22780683/70142758-406ecf80-169a-11ea-988d-e01a61209191.png)

### Notes

I am not a fan of how overblown and super-serious Christmas has become in many peoples' eyes in the past few years, so I'd more than happily tone down the celebrations a bit by e.g. removing holiday website effects like these.

I have also double-checked if AdGuard's or Fanboy's annoyances lists were already blocking those sparkles, which they didn't.

**Comment by mapx-** [comment]
@ryanbr
