### ISSUE TITLE
adflow.genoudsa.ch incorrectly blocked

### ISSUE THREAD

**Issue by stef740** [uBlockOrigin/uAssets#6643]
### URL(s) where the issue occurs

`https://adflow.genoudsa.ch`

### Describe the issue

We are finding uBlock extension is incorrectly blocking scripts on the above domain. Assuming this is due to the domain including the word adflow in it. It is possible to get this domain added to the exclusion list?

### Screenshot(s)

When uBlock enabled:
![Capture d’écran 2019-12-04 à 13 46 32](https://user-images.githubusercontent.com/58515650/70143730-a8beb080-169c-11ea-8fe9-b009f9bbb5c9.png)

When uBlock Disabled:
![Capture d’écran 2019-12-04 à 13 46 46](https://user-images.githubusercontent.com/58515650/70143760-b7a56300-169c-11ea-9b91-65dcea105a87.png)

### Versions

- Browser/version: Firefox/70.0.1 (64 bits)
- uBlock Origin version: uBlock Origin v1.24.2

### Settings

- Default settings

### Notes
We try to find blacklists of our domain (adflow), there are lots of them. AdFlow is a professional tool for managing the production flow for advertising companies. 

Have a nice day

**Comment by mapx-** [comment]
However, it should be fixed in easylist (to be available for all adblockers) @ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/9e1d1b7fdc1a41835329830f9f9ff9c2a4a31f69
