### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#665]
https://github.com/gorhill/uBlock

After uBlock Origin updated automatically to version 1.14.4, it completely reset all the settings and deleted all custom settings. You should design that better. Thanks.

![ublock origin](https://user-images.githubusercontent.com/26278182/29996431-3f7d3a6e-8fcc-11e7-9819-7df1fd6dd3df.jpg)

Firefox Developer Edition 56.0b8
uBlock Origin 1.14.4

**Comment by Hrxn** [comment]
Pretty sure it's not uBO itself. Did you verify with a clean profile?

Also: wrong repository.

**Comment by js017** [comment]
Why should I have to install a completely new profile and all it's settings, for Firefox, and Firefox Developer Edition, because that's what I have to do to get both those programs to work properly after using the profile manager to create a new profile, when previous uBlock Origin version updates didn't delete all the settings? What is the right repository?
 

Sent: Saturday, September 02, 2017 at 11:22 AM

**Comment by okiehsch** [comment]
This repo is for **filter** issues.

**Comment by gorhill** [comment]
@js017 Minimum that is asked from you is to read the Release notes.
