### ISSUE TITLE
www.classic-retro-games.com block ad block (bab)

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uAssets#6652]
Site `www.classic-retro-games.com` uses a known block ad block (bab) script to tell adblock users to disable their adblock.

![kuva](https://user-images.githubusercontent.com/17256841/70309833-0d9e1600-1817-11ea-89fd-b5f27611d45a.png)

Would this general filter be a good addition to Ubo's internal filters as bab is a known anti adblock script?

`/bab.min.js$script`

`https://blockadblock.com/`

**Comment by okiehsch** [comment]
Almost all of the sites use `https://blockadblock.com` in their inline-script, so the filter would only fix a very small number of sites.
`/bab.min.js$script` would also block for example `http://cdn.pelcro.com/js/bab/min.js`.
We could add `/bab.min.js$script,1p`, @mapx- what do you think?

**Comment by mapx-** [comment]
sure, why not .. even if I guess they will rename the script
