### ISSUE TITLE
glory-link.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#6653]
### URL(s) where the issue occurs

`http://glory-link.com/pq71Tv`

### Describe the issue

They try to open infected files

### Screenshot(s)

<img width="914" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/70318147-aa64b180-181f-11ea-91fd-2b57e4cfe8e1.PNG">

### Versions

- Browser/version: Firefox 71
- uBlock Origin version: v1.24.2

### Settings

[settings.txt](https://github.com/uBlockOrigin/uAssets/files/3931814/settings.txt)

**Comment by okiehsch** [comment]
Hm, I get a different cloudfront request on my end, one that is already blocked.
Do you still get the download prompt if you add
`||a1fafile.com^`?

**Comment by JobcenterTycoon** [comment]
No
