### ISSUE TITLE
file-up.org

### ISSUE THREAD

**Issue by lyndmi** [uBlockOrigin/uAssets#6655]
### URL(s) where the issue occurs

`https://www.file-up.org/7fy0nn263twh`

### Describe the issue

The countdown

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24647715/70375004-8aa1bc00-18f9-11ea-9b9f-76f4511faefb.png)

### Versions

- Browser/version: 65.0.3467.48
- uBlock Origin version: 1.23.0

### Settings

- Default

### Notes

Just wondering if countdown can be boosted

**Comment by uBlock-user** [comment]
Detects skipped countdown, so probably server-sided.

**Comment by lyndmi** [comment]
Ok
