### ISSUE TITLE
booking.com annoyances

### ISSUE THREAD

**Issue by dadosch** [uBlockOrigin/uAssets#6657]
### URL(s) where the issue occurs

`booking.com`

### Describe the issue

this removes the annoyances ("x people bought this room in the last 10 minutes") and so on
### Rules
```
www.booking.com###alternative_rewards__collapsed_banner
www.booking.com##.sr_rooms_left_wrap.only_x_left
www.booking.com##.sold_out_property
www.booking.com##.sr-booked-x-times.clearfix.shrink_lbsr.lbsr
www.booking.com##.notice-item
www.booking.com##.fe_banner__red.fe_banner__w-icon.fe_banner__scale_small.fe_banner__accessible.fe_banner
```

**Comment by mapx-** [comment]
It's questionable if those are annoyances or site features. 
However, even if it would be about normal banners / ads, no extended syntax is requested.

You eventually could report at easylist repository (to be included in fanboy's annoyances list)
