### ISSUE TITLE
[unbreak][annoyance] putlock.org

### ISSUE THREAD

**Issue by alexchandel** [uBlockOrigin/uAssets#6659]
### URL(s) where the issue occurs

`https://putlock.org/player/embed_player.php?vid=QUhjSWVpZndpdnRFUXBBRDZQL0pjZz09`

### Describe the issue

This website calls `debugger` to detect if the developer console is open, and deletes the page's contents if it finds it.  Additionally, the site successfully detects ublock origin and deletes the page contents.

Hostility towards developers and developer tools is unacceptable.

### Versions

- Browser/version: Chrome latest
- uBlock Origin version: 1.23.0

**Comment by llacb47** [comment]
Better test link needed

**Comment by mapx-** [comment]
The site seems to be broken.

**Comment by mapx-** [comment]
@alexchandel could you provide the page where the above video was embedded ?

**Comment by mapx-** [comment]
no feedback => closing

**Comment by llacb47** [comment]
Test here: `https://europixhd.io/mov/jumanji-the-next-level-2019-online-free-hd-with-subtitles-europix`

Server 1

**Comment by mapx-** [comment]
somebody could test
```
hindipix.*,hqq.tv,putlock.org##+js(set, console.debug, trueFunc)
hindipix.*,hqq.tv,putlock.org##+js(set, console.clear, trueFunc)
hindipix.*,hqq.tv,putlock.org##+js(set, h, noopFunc)
```
