### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#666]
https://github.com/gorhill/uBlock

It says on uBlock Origin's website "uBlock Origin is compatible with SeaMonkey, Pale Moon, and possibly other browsers based on Firefox.", but actually it isn't. When you go to the add-ons for SeaMonkey page at https://addons.mozilla.org/en-US/seamonkey/, it isn't even there, and if you download the version 1.14.4 .xpi file for it from the add-ons for Firefox page at https://addons.mozilla.org/en-US/firefox/, and try to install it, it says "The add-on downloaded from unknown host could not be installed because it appears to be corrupt.", but version 1.13.8 did install properly. If you try to go to debug add-ons and select "load temporary add-on", then select the 1.14.4 .xpi file, it says "There was an error during installation: ns is undefined". The add-on converter for SeaMonkey page at http://addonconverter.fotokraina.com/, won't even convert it, because it says "install.rdf not found in installer". You should update that information, or make it compatible with SeaMonkey. Thanks.

![ublock origin](https://user-images.githubusercontent.com/26278182/29996626-08855eca-8fd0-11e7-9fd5-cce01eabeaf0.jpg)

![ublock origin compatibility 2 48](https://user-images.githubusercontent.com/26278182/29996655-7822b5ca-8fd0-11e7-81e2-de1778329cea.jpg)

![ublock origin debug add-ons](https://user-images.githubusercontent.com/26278182/29996632-16a65c5c-8fd0-11e7-969c-78bc92ef0838.jpg)

SeaMonkey 2.48

**Comment by Hrxn** [comment]
That information was correct, but it might be outdated by now.

First of all, the latest official Seamonkey release version is v. 2.48, 2.46 is really ancient compared to that and no one should be using it.

And 2.48 is basically like Firefox 51, as far as I know, and I think the min. version requirement for uBO on Firefox has been changed recently, don't know, v52 maybe?
Which is also old..

And this is the wrong repository, by the way..

**Comment by js017** [comment]
I didn't say anything about version 2.46, the topic post mentions version 2.48, which is the latest SeaMonkey version on their main website. If your website says uBlock Origin is compatible with SeaMonkey, then that would mean that it should work with the latest version. If it doesn't, you should probably update your website information. What is the right repository, by the way?
 

Sent: Saturday, September 02, 2017 at 11:19 AM

**Comment by okiehsch** [comment]
> What is the right repository, by the way?

https://github.com/gorhill/uBlock for reproducable bugs caused by uBO.
https://www.reddit.com/r/uBlockOrigin/ for general support questions.
