### ISSUE TITLE
Old Syntax

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#6660]
Files:
`annoyances.txt`
`badware.txt`
`filters.txt`
`privacy.txt`
`resource-abuse.txt`
`unbreak.txt`

Please use _Search & Replace_.
Make sure there is a comma, _$_ or _##_ before!

`$third-party    ->    $3p`
`,third-party    ->    ,3p`

`$~third-party    ->    $1p`
`,~third-party    ->    ,1p`

`$first-party    ->    $1p`
`,first-party    ->    ,1p`

`$xmlhttprequest    ->    $xhr`
`,xmlhttprequest    ->    ,xhr`

`$stylesheet    ->    $css`
`,stylesheet    ->    ,css`

`$subdocument    ->    $frame`
`,subdocument    ->    ,frame`

`##script:inject    ->    ##+js`
(only two filters in `filters.txt`)

By the way, you can replace the `#` with `!` in the comments in `experimental.txt`.
(only one `#` there is not used as a comment - `#issuecomment`)

Thanks!

**Comment by llacb47** [comment]
there is nothing wrong with the old syntax. this is not an issue.

**Comment by uBlock-user** [comment]
It's not an old syntax, it's an alternative syntax. `$1p` = `$first-party`, both are valid. One is short-hand.

**Comment by okiehsch** [comment]
> Plus preserving old syntax is nice to waterfox users and other users of the legacy extension versions.

What would really hurt those users is using the shorter syntax of the scriptlets, for example converting all `addEventListener-defuser.js` filters to `aeld`.
That would make  90% of `uBO-filters` useless for legacy users.
