### ISSUE TITLE
broadwayworld.com [breakage]

### ISSUE THREAD

**Issue by llacb47** [uBlockOrigin/uAssets#6663]
### URL(s) where the issue occurs

`https://www.broadwayworld.com/videoplay/BWW-TV-Meet-the-Cast-of-A-SOLDIERS-PLAY-on-Broadway-20191209`
`https://www.broadwayworld.com/article/Breaking-Samantha-Barks-To-Play-Elsa-In-FROZEN-West-End-20191205`
`https://www.broadwayworld.com/`

### Describe the issue

Old and probably unneeded CSP filter breaking video (1st link), sidebar layout (2nd link), latest news column (3rd link)

### Versions

N/A

### Settings

N/A 

### Notes

Filter added with https://github.com/uBlockOrigin/uAssets/commit/ce8671818859c47ca7667104f91d83a4613cec4d

Filter can probably be removed

**Comment by okiehsch** [comment]
Yes, I don't see any anti adblock script, so the filter can be removed.
