### ISSUE TITLE
medium.com

### ISSUE THREAD

**Issue by lyndmi** [uBlockOrigin/uAssets#6665]
### URL(s) where the issue occurs

`https://medium.com/squallygame/we-open-sourced-our-steam-game-and-why-it-was-a-good-idea-2d5ac72c9802`

### Describe the issue

Annoying popup that tells I read on Medium before and want me to sign in

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24647715/70551523-f42efe00-1b77-11ea-9c09-c02e9a62a5fb.png)

### Versions

- Browser/version: 1.23.0
- uBlock Origin version: Opera 65.0.3467.62

### Settings

- Default

### Notes

I'm not happy how Medium is making annoyance popup and trying to force anyone to login to collect data and share it with service providers. Popups makes me stressed
I saw someone had worked with filters for uAssets but it's not working anymore it seems

**Comment by okiehsch** [comment]
I can't reproduce. There is a filter in `uBO-annoyances` that deals with the "pardon the interruption" modal.
Is your issue fixed if you enable the `uBO-annoyances` list?
