### ISSUE TITLE
startimez.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6668]
### URL(s) where the issue occurs

`http://startimez.com/2019/10/30/hello-world/`
### Describe the issue

countdown timer stopped,not getting destination link

### Versions

- Browser/version: firefox android stable
- uBlock Origin version: ublock origin 1.24.2

### Settings

-  uBO's default settings

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
How do you get the `countdown timer` ? steps ?

**Comment by krystian3w** [comment]
typo with url / domain?

**Comment by ghajini** [comment]
no typo 
,pass this `http://wi.cr/ds7wD22Sg` you will get above url

**Comment by krystian3w** [comment]
So typo, you should send `wi.cr` here #5890 ?

**Comment by krystian3w** [comment]
typo you hidden redirect / referer...
