### ISSUE TITLE
harblaze.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6669]
### URL(s) where the issue occurs

`http://harblaze.com/ads/?file=1dec7f989f`

### Describe the issue
`continue & download` button not working

### Versions

- Browser/version: firefox android stable
- uBlock Origin version: 1.24.2

### Settings

-  uBO's default settings

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
test
`@@||harblaze.com/ads/js/jquery$script,1p`

**Comment by ghajini** [comment]
👍
