### ISSUE TITLE
seancody.com [NSFW]

### ISSUE THREAD

**Issue by bug-rules** [uBlockOrigin/uAssets#6670]
### URL(s) where the issue occurs

`https://www.seancody.com/model/17845/lane`

### Describe the issue

No possible drag graphic from "similar videos" into "`browser tabs`" section.

### Screenshot(s)

`https://user-images.githubusercontent.com/43518394/70560658-4b899a00-1b89-11ea-8642-fdbbee111575.png`

### Versions

- Browser/version: Chrome 76
- uBlock Origin version: 1.24.2

### Settings

- uBO Annoaynce

### Notes

IMO needed kill `eventListener` on `<BODY>`.

`seancody.com#+js(aeld, ...)`

**Comment by mapx-** [comment]
working for me in chrome 78 (brave), not in firefox

**Comment by mapx-** [comment]
However, not a uBo issue or filter issue

**Comment by bug-rules** [comment]
Yes, filter issue similar as blocked right click / selection - @gorhill.
