### ISSUE TITLE
Reddit Clickjacking possibly others

### ISSUE THREAD

**Issue by h1z1** [uBlockOrigin/uAssets#6671]
### URL(s) where the issue occurs

`https://old.reddit.com`

### Describe the issue

Reddit is doing what I can only describe as clickjacking where links are being intercepted and replaced with others, on click.   Some end up as trampoline links while others like r/random have utm tracking added

ex

`https://old.reddit.com/r/quotes/?utm_campaign=redirect&utm_medium=desktop&utm_source=reddit&utm_name=random_subreddit`

### Screenshot(s)

NA

### Versions

- Browser/version: Firefox and Chrome
- uBlock Origin version: v1.24.3b5

### Settings

- Reproducible with defaults

### Notes

Click event is attached to the links, and while r/random is fairly consistent in the hijack, Reddit randomly adds it to others.

```
function() {
  return e.apply(t || this, r.concat(slice.call(arguments)))
}```

**Comment by DandelionSprout** [comment]
Where do the hijacked links lead to (if anywhere)?

**Comment by llacb47** [comment]
Example- click on the link in this comment: `https://old.reddit.com/r/IAmA/comments/dwaa36/when_i_graduated_college_i_had_interviews_at/f7hll1j/`

Tracking parameters are added and quickly removed. Same with clicking random in the header.

Try `reddit.com##+js(aopr, r.utils.replaceUrlParams)`

**Comment by bug-rules** [comment]
no use subdomain `old` - language specific is also bugged:

```
https://de.reddit.com/r/uBlockOrigin/
https://ru.reddit.com/r/uBlockOrigin/
https://ko.reddit.com/r/uBlockOrigin/
https://pt.reddit.com/r/uBlockOrigin/
https://es.reddit.com/r/uBlockOrigin/
```

**Comment by llacb47** [comment]
Does my filter still work? The language subdomains still use the old reddit design, if that matters.
