### ISSUE TITLE
(Annoyances) Full-page animated snowfall on certain Swedish shopping sites

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#6672]
### URL(s) where the issue occurs

(Involved script URLs are in paranthesis.)

* `nordiskehandel.se` (`https://nordiskehandel.se/site/themes/redwood/js/snow.js`)
* `medistore.se` (`https://www.medistore.se/INC/js/snow.js`)
* `simbutiken.se` (`https://my.nordiskehandel.se/Scripts/customer/christmas/snow.js`)

### Describe the issue

It appears to me that the Swedish merchant template maker `Nordisk E-Handel` has made a fullpage animated snowfall overlay for use during the month of December, which is being used by them and a seemingly small but random selection of their client sites.

My proposed entry to remove the overlays is `/snow.js|`, or perhaps `s/snow.js|`.

### Screenshot(s)

(It doesn't really show up well in stillshots.)
![image](https://user-images.githubusercontent.com/22780683/70579882-2f4e2300-1bb2-11ea-871e-326e95bacb86.png)

### Versions

- Browser/version: Chrome 78.0.3904.108 64-bit for Windows
- uBlock Origin version: Nano Adblocker 1.0.0.130 + Nano Defender 15.0.0.170

### Settings

![image](https://user-images.githubusercontent.com/22780683/70579923-560c5980-1bb2-11ea-8558-09e2fab4dddd.png)

### Notes

I can confirm that neither AdGuard's or Fanboy's annoyances lists are removing the overlays at the moment.

**Comment by llacb47** [comment]
Way too generic IMO, how about `nordiskehandel.se,medistore.se,simbutiken.se##canvas#canv`

**Comment by ZaphodBeebblebrox** [comment]
It would be better to do it as `/snow.js|$script,domain=...` than as a cosmetic filter because the snow also causes significant CPU usage, so just hiding it does not really negate its effects.

**Comment by llacb47** [comment]
Well then for that reason, add the filter to resource abuse list instead?

**Comment by ZaphodBeebblebrox** [comment]
Sounds fine to me, but I am not around enough to feel comfortable making that call. I'll let okiehsch and mpax- add it or not.
