### ISSUE TITLE
amazon.jobs

### ISSUE THREAD

**Issue by Paul-E** [uBlockOrigin/uAssets#6673]
### URL(s) where the issue occurs

`amazon.jobs`

### Describe the issue

The filter criteria on the left side of the page do not work. see image for example of criteria

### Screenshot(s)

![image](https://user-images.githubusercontent.com/4206484/70588785-df646180-1b9b-11ea-9ba9-fb76b28ddce8.png)

### Versions

- Browser/version: Firefox 71 on Ubuntu
- uBlock Origin version: 1.24.2

### Settings

**Comment by llacb47** [comment]
`@@||amazon.jobs/assets/analytics-$script,1p`
