### ISSUE TITLE
sdk-gcp.privacy-center.org (Didomi CMP)

### ISSUE THREAD

**Issue by MaximePlancke** [uBlockOrigin/uAssets#6676]
### URL(s) where the issue occurs

`https://www.lesechos.fr/`
Everywhere else with our CMP and uBlock Origin activated

### Describe the issue

Hello, I am contacting you because your filter list is blocking our Didomi CMP on our clients websites. This is impacting our work and doesn't allow the user to give is consent or not on those websites. Our CMP is suppose to open a banner or popup to let the user the choice to give or not his consent to display or not ads, within the RGPD laws. Blocking this script is not applicable. 

### Screenshot(s)

<img width="1440" alt="Didomi" src="https://user-images.githubusercontent.com/5814860/70702899-56e6dd80-1ccf-11ea-9d35-b6357f21aaeb.png">

### Versions

- Browser/version: Chrome 78
- uBlock Origin version: 1.23.0

### Settings

- None

### Notes

Our script is coming from 2 domains: 
-sdk-gcp.privacy-center.org
-sdk.privacy-center.org

and can have several paths, loader.js, sdk..., ui.... Plus we are using commit IDs so our paths are dynamics. Please whitelist our entire subdomains. 

Thank you,

Maxime

**Comment by mapx-** [comment]
removed

**Comment by MaximePlancke** [comment]
Thank you
