### ISSUE TITLE
lolalytics.com antiadblock

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#668]
### URL(s) where the issue occurs
`https://lolalytics.com/ranked/worldwide/platinum/plus/champion/Vladimir/`
`http://lolalytics.com/leaderboard/`

### Describe the issue

there is antiadblock 
### Screenshot(s)

`http://prntscr.com/gg99jh`
### logger
`http://prntscr.com/gg99rx`
`http://prntscr.com/gg9a2d`
### Versions

- Browser/version: google chrome Version 60.0.3112.113 (Official Build) (32-bit)
- uBlock Origin version: 1.13.8+ uBo extra

### Settings

- uBO's default settings

### Notes

This issue Discussed here 
`https://github.com/jspenguin2017/uBlockProtector/issues/478`
but fix is being is being constantly patched by lolalytics

**Comment by mapx-** [comment]
```
@@||lolalytics.com^$generichide
@@||pagead2.googlesyndication.com$script,domain=lolalytics.com
lolalytics.com##[id^=aswift]

```

**Comment by ghajini** [comment]
Any solution @gorhill because whiteling ad server is not a option....

**Comment by jspenguin2017** [comment]
They removed their anti-adblock... For some reason.

**Comment by uBlock-user** [comment]
They gave up finally. Although knowing them, they will come back with another script just to get that patched too.

**Comment by gorhill** [comment]
Judging by the picture, this was not an anti-blocker preventing access to content?

**Comment by jspenguin2017** [comment]
It makes the content transparent after couple refreshes, so yes, it does prevent access.

**Comment by ghajini** [comment]
somehow they removed antithing,so closing this issue...if ever it came back i will open

**Comment by lain566** [comment]
> They removed their anti-adblock... For some reason.

@jspenguin2017 They never did, they simply changed their anti-adblock system. [Enabled](https://user-images.githubusercontent.com/27441315/30422744-210c5f5a-9941-11e7-90e8-8d3ec7044231.png) - [Disabled](https://user-images.githubusercontent.com/27441315/30427456-2f6fea12-9950-11e7-9019-4810a1f230d6.png)
`https://lolalytics.com/ranked/worldwide/platinum/plus/champion/Vladimir/`

--

> Judging by the picture, this was not an anti-blocker preventing access to content?

@gorhill This site changes all of the icons and items if uBO is enabled, so yes, the content shown is false.

**Comment by gorhill** [comment]
`@@||pagead2.googlesyndication.com$script,domain=lolalytics.com` as suggested by @mapx- works.

Otherwise the other solution is a scriptlet to fill in the `.adsbygoogle` with DOM elements which will not render to visual nuisance. The page checks the `innerHTML` value of the `.adsbygoogle`: it has to be longer than some specific unknown length.

**Comment by ghajini** [comment]
@gorhill , Is there any solution other than (those provided by `mapx` ) available?

**Comment by sigtus** [comment]
Just tested the ``@@||pagead2.googlesyndication.com$script,domain=lolalytics.com`` filter. It didn't work. It's weird, it seems sometimes they just remove it and sometimes it comes back.
