### ISSUE TITLE
Tab opened via right-click google search from piknu.com, getting closed when clicking on instagram.com result

### ISSUE THREAD

**Issue by mica** [uBlockOrigin/uAssets#6680]
This is a strange one... 

1. Open a piknu account page, e.g: https://piknu.com/u/obviousplant

2. Highlight and right-click > search the username

3. Click instagram.com/username result, and behold as the tab is inexplicably closed

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/366058bdd5432a8765ad2635f6c8828757436643

**Comment by monzta** [comment]
@mapx- Wouldn't it be better to fix the issue on piknu.com instead of disabling a filter that blocks popups on nearly 400 domains?

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/952b726e6c2312572ec1122cea359c7bca8e1d46

**Comment by IsraeliUser** [comment]
When EasyList's authors will add a new domain to the list, this solution won't work anymore.
A better approach is the add a whitelist rule to `piknu.com`, which can be overridden by a blocking rule (using `$important`) if necessary.

**Comment by okiehsch** [comment]
I can't see any popups at `piknu.com` and think that the domain should be removed by `EasyList`.
@ryanbr

**Comment by Khrin** [comment]
Now you can remove your filters.
