### ISSUE TITLE
Video ADS => www.doofree88.com

### ISSUE THREAD

**Issue by Fuyuppe** [uBlockOrigin/uAssets#6681]
### URL(s) where the issue occurs

`www.doofree88.com`

### Describe the issue

Video ADS => `www.doofree88.com`

### Screenshot(s)

![ภาพ](https://user-images.githubusercontent.com/43577606/70806124-32812300-1ded-11ea-8360-85b3da48a103.png)

### Versions

- Browser/version: 71.0
- uBlock Origin version: 1.24.2

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by ZaphodBeebblebrox** [comment]
Ads missed by the regional list:
```
||doofree88.com/storage/go/banner*.gif$image
doofree88.com##.placeholder
```
Popup:
```
doofree88.com##.go-hard
```
Can't manage to figure out how to deal with the video ads, and I gets CORS errors if I try to redirect them.

**Comment by okiehsch** [comment]
> Can't manage to figure out how to deal with the video ads

Best I can come up with is "tricking" the site that the ads is playing by blocking the second  `.ts`segment and not the first one.

Example link:
````
https://www.doofree88.com/movie/midsommar-2019%e0%b9%80%e0%b8%97%e0%b8%a8%e0%b8%81%e0%b8%b2%e0%b8%a5%e0%b8%aa%e0%b8%a2%e0%b8%ad%e0%b8%87

Filter: `||cdnn.ufaclub8.com/*seg-2$xhr,redirect=nooptext,domain=doofree88.com`
That way the ad stops almost immediately and one can click the skip button to view the actual video.

**Comment by ZaphodBeebblebrox** [comment]
Seems pretty good to me. Throw in a `doofree88.com##+js(nano-sib, js-btn-skip, 1000)` as well so the button is ready sooner?
