### ISSUE TITLE
(Annoyances) Fake smudge background on maskmagazine.com

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#6683]
### URL(s) where the issue occurs

`https://maskmagazine.com/` (although its SSL certificate is broken).

### Describe the issue

That particular site does for some reason have a white background with small black spots on it, which can be misinterpreted as monitor smudge by people who are worried about monitor smudge (Me included).

My proposed entry is `||maskmagazine.com/assets/substrate.png`.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/22780683/70836369-38ccca80-1e00-11ea-86d8-5acea82cdf27.png)

### Versions

- Browser/version: Chrome 79.0.3945.79 64-bit for Windows
- uBlock Origin version: Nano Adblocker 1.0.0.130 + Nano Defender 15.0.0.170

### Settings

![image](https://user-images.githubusercontent.com/22780683/70836439-6580e200-1e00-11ea-9bf3-f7de230a3228.png)

### Notes

I can confirm that neither AdGuard's or Fanboy's annoyances lists seem to remove the smudge background either.

**Comment by mapx-** [comment]
@ryanbr
