### ISSUE TITLE
How to ban Quora's ADs

### ISSUE THREAD

**Issue by xieqingdong** [uBlockOrigin/uAssets#6684]
### URL(s) where the issue occurs

`https://www.quora.com`

### Describe the issue

I wan to remove Quora's ADs using a certain filter
`www.quora.com##div.ciijC.Box-sc-9env3-0:nth-of-type(1)`

but there are too many similar ADs, such as
```
www.quora.com##div.ciijC.Box-sc-9env3-0:nth-of-type(6)
www.quora.com##div.ciijC.Box-sc-9env3-0:nth-of-type(7)
```
...........................................................................
```
www.quora.com##div.ciijC.Box-sc-9env3-0:nth-of-type(11)
www.quora.com##div.ciijC.Box-sc-9env3-0:nth-of-type(21)
```
...........................................................................
```
www.quora.com##div.ciijC.Box-sc-9env3-0:nth-of-type(46)
www.quora.com##div.ciijC.Box-sc-9env3-0:nth-of-type(47)
```

**How to write a single filter which can replace all the above filters**

### Versions

- Browser/version: Firefox 68.2
- uBlock Origin version: v1.24.2

### Settings

none of the filter lists is used, except the "My filters​​​​​"

**Comment by uBlock-user** [comment]
Post the URL where it happens like it's done here -- https://github.com/uBlockOrigin/uAssets/issues/4093

**Comment by krystian3w** [comment]
Possible repoen old topic?

**Comment by mapx-** [comment]
no feedback

**Comment by ghajini** [comment]
SOme quora ads appeared

`https://www.quora.com/Where-can-I-watch-Homeland-for-free`

Filters from element picker=

`www.quora.com##div.qu-gutterBottom.spacing_log_question_page_ad.q-box:nth-of-type(1)`

`www.quora.com##div.qu-gutterBottom.spacing_log_question_page_ad.q-box:nth-of-type(7)`

`www.quora.com##.qu-gutterBottom.spacing_log_question_page_ad.q-box`

**Comment by mapx-** [comment]
I get no ad logged on / logged off

**Comment by krystian3w** [comment]
@ghajini  on mobile version only?

**Comment by krystian3w** [comment]
@ghajini  on mobile version only?

 > ![obraz](https://user-images.githubusercontent.com/35370833/78495948-23323680-774a-11ea-8a79-eb006a48e05b.png) |  _____________________________________________________ <br><br> example of sponsored ad maybe... <br> blocked with `#if env_mobile` condition. <br> _____________________________________________________ 
> --- | ---

Also need use mobile phone instead of <kbd>**devtools**</kbd> - <kbd>**RWD test tool**</kbd> (`env_mobile` newer support devtools emulator).

**Comment by ghajini** [comment]
URL = `https://www.quora.com/Where-can-I-watch-Homeland-for-free`
Quora not logged in,  ip = indian

Browser= firefox android stable

These are  the ads
![IMG_20200405_210641](https://user-images.githubusercontent.com/20338483/78503001-9acf8800-7781-11ea-8948-a519a52b93c9.jpg)

![IMG_20200405_210621](https://user-images.githubusercontent.com/20338483/78503006-a0c56900-7781-11ea-98b5-1e2805f23ece.jpg)

3rd ad PIC I forgot to capture, it is not appearing but it was duckduckgo ad(`www.quora.com##.qu-gutterBottom.spacing_log_question_page_ad.q-box`)

**Comment by ghajini** [comment]
Also is it fixable by ublock origin possibly in annoyances section
https://user-images.githubusercontent.com/20338483/78503631-88574d80-7785-11ea-810f-84dc5ba5e898.png

to reproduce you have to click more articles

**Comment by mapx-** [comment]
I removed today such filter
https://github.com/uBlockOrigin/uAssets/commit/ee3c3f00c733d0941ca2766241372834d4a69ab5

we cannot break normal functionalies

**Comment by ghajini** [comment]
Correct, perhaps I can use that as custom filter😜 thanks

**Comment by ghajini** [comment]
`https://www.quora.com/Is-there-any-Ayurvedic-treatment-for-bone-fractures`

I can't select/select all(copy text) ,any filter for that?

**Comment by mapx-** [comment]
only for mobile
