### ISSUE TITLE
ranker.com video ad

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#669]
### URL(s) where the issue occurs

`http://www.ranker.com/list/realistic-grotesque-pokemon-fan-art/sergio-solorzano`

### Describe the issue

Unblocked video ad appears on the bottom right after you scroll down a bit.
Here is a direct link to one:
`http://tu9srvbirvvtmjqkcjmtls1zbi1wnxfzn243zc5jljjtzg4ubmv0.g00.ranker.com/g00/2_d3d3LnJhbmtlci5jb20%3D_/TU9SRVBIRVVTMjQkaHR0cHM6Ly9yMy0tLXNuLXA1cXM3bjdkLmMuMm1kbi5uZXQvdmlkZW9wbGF5YmFjay9pZC81MGZhODY1OGVlNDIxYWFiL2l0YWcvMzQ0L3NvdXJjZS9kb3VibGVjbGlja19kbW0vcmF0ZWJ5cGFzcy95ZXMvYWNhby95ZXMvaXAvMC4wLjAuMC9pcGJpdHMvMC9leHBpcmUvMzYzNzUxMDE3Ni9zcGFyYW1zL2FjYW8sZXhwaXJlLGlkLGlwLGlwYml0cyxpdGFnLG1pcCxtbSxtbixtcyxtdixwbCxyYXRlYnlwYXNzLHNvdXJjZS9zaWduYXR1cmUvMTQyQTUxRDM2NTVDMUNCM0RFQTYxMTcwRDZFNkY0Q0EwOTk2RDU4QS43QTQyODNCQUJGMTE3QTkyNENEODk0MjBGQzg4RjhDMkM2NDM3NTVCL2tleS9jbXMxL2Ntc19yZWRpcmVjdC95ZXMvbWlwLzE1OS4xODAuNzUuMTQvbW0vNDIvbW4vc24tcDVxczduN2QvbXMvb25jL210LzE1MDQzOTc0MTEvbXYvbS9wbC8yNC9maWxlL2ZpbGUubXA0P2kxMGMubWFyay52aWRlby50eXBl_$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$/$`

Seems to be the g00 crap. If unfixable without uBO-extra, then close this please.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/29999531-5f954190-901a-11e7-94ad-92078dd8801d.png)

### Versions

- Browser/version: Chrome 60
- uBlock Origin version: 1.13.8

**Comment by okiehsch** [comment]
I am sorry but I can only reproduce without uBO-Extra, so using uBO-Extra would be the way to go.
