### ISSUE TITLE
FirebaseUI Apple login broken

### ISSUE THREAD

**Issue by Christilut** [uBlockOrigin/uAssets#6691]
### URL(s) where the issue occurs

https://fir-ui-demo-84a6c.firebaseapp.com/

### Describe the issue

Logging in with Apple with the [FirebaseUI](https://github.com/firebase/firebaseui-web) is broken. The popup after logging in display a white screen and doesn't continue. 

Whitelisting the FirebaseUI demo site doesn't help. Only disabling the uBlock extension works.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/3471363/71002516-b71abc80-20df-11ea-8b27-95afc788b1c5.png)

### Versions

- Browser/version: Chrome 79
- uBlock Origin version: 1.23.0

### Settings

Defaults

### Notes

The FirebaseUI is used in a lot of websites and Apple support was only added recently.

**Comment by gwarser** [comment]
"Sign in with Apple"? Nothing at all is blocked on my side. Page needs some time to load.

**Comment by Christilut** [comment]
Not sure what the problem is then. I always get that white screen if uBlock is enabled. If I turn off uBlock entirely, the problem goes away.

I don't have any custom rules. What else could be causing this?

**Comment by gwarser** [comment]
Try "Purge all caches" -> "Update now" or reset uBO to default settings.

**Comment by Christilut** [comment]
I turned off filter lists one by one and it's EasyList that's causing this.
