### ISSUE TITLE
Site blocked 1st time I try to open it, but not 2nd time

### ISSUE THREAD

**Issue by dafechtor** [uBlockOrigin/uAssets#6693]
### URL(s) where the issue occurs

`[https://login.aol.com]`

### Describe the issue

[Sorry in advance for what may be a stupid question. I'm an old geezer who's still using an AOL email address. When I go to https://login.aol.com and enter my user name and password, I get a message from UBlockOrigin saying that the site has been blocked because of an advertising.com filter (see screen shot below), but if I then click the "Go Back" button and immediately try again to log into my AOL account, I get in without a problem. Why is it that uBlockOrigin would block the site the *first* time I try to open it, but not the *second* time? Any help or advice you can give me (other than switching email providers!) would be greatly appreciated.]

### Screenshot(s)

[![uBlockOrigin problem?](https://user-images.githubusercontent.com/9560698/71008175-32677880-20b6-11ea-867a-8337b7d075f1.png)]

### Versions

- Browser/version: [Firefox 71.0]
- uBlock Origin version: [1.24.2]

### Settings

- [No changes made to uBO's default settings]

### Notes

[My wife doesn't have the same problem on her MacBook, which is running the same operating system and the same version of Firefox, but she uses the Adblock Plus extension rather than uBlockOrigin.]

**Comment by uBlock-user** [comment]
@pgl

**Comment by pgl** [comment]
Hiya. So, I guess the AOL login page is redirecting people to `advertising.com` straight after login, which is a bit weird. I would guess that it doesn't happen the second time is because they're doing some sort of A/B testing where they don't always redirect - or it's an ad that's only supposed to be shown once perhaps.

I don't really want to remove `advertising.com` from my list. Is this something that can be fixed via the unbreak rules?

**Comment by dafechtor** [comment]
pgl, I can certainly understand your not wanting to remove advertising.com from your list! Unfortunately, I'm not technically savvy enough to know whether the problem can be fixed via the unbreak rules. Could you (or someone else) tell me whether Fix #6693 was actually applied or merely added to a list of potential future fixes? If it *was* actually applied, it doesn't seem to have worked, as I updated the uBlockOrigin extension just a minute or two ago, then tried to log into my AOL account, and the results were just the same as before: i.e., I was blocked the first time around, but I got into my AOL mail on the second attempt. Do you have possible solutions to suggest?

**Comment by pgl** [comment]
I think the fix should be included in the next release, and won't be available until that happens.

For now, you can go ahead and click "Permanently" on the page you're seeing, to whitelist `advertising.com`.

**Comment by dafechtor** [comment]
Thanks! Much appreciated.

**Comment by uBlock-user** [comment]
@dafechtor Force update un-break list.

**Comment by dafechtor** [comment]
Perfect! I updated my unbreak list, and now everything works fine. Thanks so much!

**Comment by pgl** [comment]
Yes, sorry, what I said was absolute bollocks. Apologies for that.

**Comment by dafechtor** [comment]
No worries, pgl! Everything's working fine now, so problem solved. Many thanks, all.
