### ISSUE TITLE
9Gag Showing Promoted Posts

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uAssets#6694]
![4324234](https://user-images.githubusercontent.com/18757054/71015430-e0ddde80-20f3-11ea-98b5-da349607c324.jpg)

**Comment by mapx-** [comment]
I get no promoted stuff.

**Comment by GKid94** [comment]
Another one

![345345](https://user-images.githubusercontent.com/18757054/71079608-df5ff500-218b-11ea-9e2d-156316bf7311.jpg)

**Comment by GKid94** [comment]
Why is this post closed

**Comment by mapx-** [comment]
You should see => `closed this in 0d85830` => click that "code / link" and you'll see the commit fixing your issue

**Comment by GKid94** [comment]
Oh ok

**Comment by Procyon-b** [comment]
The site has changed a little. Now posters are identified. To target promoted post these filters works:
I don't know which solution is more efficient.

First solution: this type of "article" doesn't have a tag list.
```
9gag.com##article:not(:has(:scope > .post-tag))
```
Second solution: match the poster's name.
```
9gag.com##article > header > .post-header > .ui-post-creator:has-text(/^Promoted$/):upward(article)
```

**Comment by Procyon-b** [comment]
@mapx- how have I missed the `.promoted` classname ? ... 
Either their are still playing with their design, or I was too tired...  :)

**Comment by mapx-** [comment]
I guess they'll change it pretty soon ;)
