### ISSUE TITLE
Cannot load comments on ZDNet

### ISSUE THREAD

**Issue by SumatraPeter** [uBlockOrigin/uAssets#6698]
Clicking on the Show Comments button at the bottom of any article on `https://www.zdnet.com` fails to load the comments section.

**Comment by okiehsch** [comment]
I can't reproduce.
![image](https://user-images.githubusercontent.com/16838044/71052982-575afa80-214d-11ea-9d7c-05485f52baf2.png)

**Comment by SumatraPeter** [comment]
I'm using uBlock Origin 1.24.2 with Firefox 71.0. I have FF's Enhanced Tracking Protection turned off for ZDNet. I suppose you can't reproduce @okiehsch because you have different filter lists loaded than me. Here's what I have currently selected:

![image](https://user-images.githubusercontent.com/15380332/71053839-d2380b80-2175-11ea-94f0-4c04c6044869.png)

**Comment by SumatraPeter** [comment]
You know what - please ignore. I turned Firefox's Enhanced Tracking Protection off and back on, and also purged all filter caches and updated, and now it seems to work again. 🤷‍♂
