### ISSUE TITLE
Can't comment on github issues

### ISSUE THREAD

**Issue by guiniol** [uBlockOrigin/uAssets#67]
### Notes

EasyPrivacy prevents commenting on github issues. Whitelisting `github.com` fixes the problem, at the cost of privacy. Are there any solutions?

### URL(s) where the issue occurs

Try commenting on this very page

### Describe the issue

I use the configuration described here: https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode
For github, there is no specific whitelisting. I'm subscribed to EasyPrivacy (this is the default I think).

When I try to comment on a github issue, I get `Sorry! We couldn't save your comment. Please try again.`

If I whitelist `github.com`, then the comment can be saved.

### Screenshot(s)

![ublock](https://cloud.githubusercontent.com/assets/3483433/16187932/5a9ac472-36d3-11e6-8f6c-6980c8cfe957.png)

### Versions

- Browser/version: Firefox 47.0
- uBlock Origin version: 1.7.0

### Settings

I'm using this as baseline: https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode
And the problem comes from the EasyPrivacy list.

**Comment by gorhill** [comment]
I can post without any issue with EasyPrivacy. How did you conclude EasyPrivacy is the issue? Since you are using medium mode, did you try noop-ing 3rd-party scripts and frames before concluding EasyPrivacy is the issue?

**Comment by gorhill** [comment]
I don't see piwik in my logger by the way.

**Comment by gorhill** [comment]
Ok I see, you tried to comment on piwik repo, and EasyPrivacy got in the way. So the issue is specific to commenting on the piwik repo, not a widespread issue of being unable to comment on GitHub with uBO. Report the issue to [EasyPrivacy maintainers](https://forums.lanik.us/viewforum.php?f=64), they will obviously have to make an exception for pages such as `https://github.com/piwik/docker-piwik/issues/30`.

**Comment by gorhill** [comment]
Paging @ryanbr.

**Comment by guiniol** [comment]
Sorry for the noise. I had a similar problem yesterday, and I didn't realize it was on the piwik repo.
I concluded it was easyprivacy, because the in the logs, I could see only one thing blocked on github.com and it was from easyprivacy.

**Comment by guiniol** [comment]
And I didn't need to change anything to post my previous comment.

Also, thanks a lot for the reply (and for ublock0)

**Comment by guiniol** [comment]
For info, this is what led me to believe it was easyprivacy:
![screenshot from 2016-06-20 16-40-14](https://cloud.githubusercontent.com/assets/3483433/16198293/bbd63d48-3705-11e6-950f-06d39722baf5.png)

**Comment by guiniol** [comment]
And now I see how I was misled, and the actual problem is the presence of `piwik` in the url.

![screenshot from 2016-06-20 16-42-26](https://cloud.githubusercontent.com/assets/3483433/16198372/ffe5a7da-3705-11e6-9d49-67f94e31b501.png)
