### ISSUE TITLE
Not a uB0 issue but an IndexedDB issue with a profile on a RAMDisk

### ISSUE THREAD

**Issue by mazesy** [uBlockOrigin/uAssets#670]
This is not a uB0 issue but my simple experience with a Webextension (in this case uB0 1.4.x Webextension) using Firefox's IndexedDB to store data in the user's profile / Storage folder. It appears for me all is OK if the profile is on a hard disk and data storage is KO if the profile is on a RAMDisk.

Because this does not concern uB0 specifically I first exposed my experience at https://github.com/ghacksuserjs/ghacks-user.js/issues/211#issuecomment-326823101 but because IndexedDB has been so strongly focused by uB0 in the add-on to Webextension odyssey I believe Gorhill or a talented user may bring some light to this issue : why does indexedDB's Webextension data storage not work correctly when the profile is on a RAMDisk and work perfectly well when the profile is on the hard disk? I precise that sites using IndexedDB to store data in the storage folder do it correctly, it's only the Webextension's data which doesn't do it on a RAMDisk.

Thanks.

**Comment by gorhill** [comment]
indexedDB is an API, whatever happens behind that API is the implementator's responsibility, i.e. the browser. There is absolutely nothing uBO can do for you issue, it's completely outside of its realm, uBO has no knowledge of file system, OS, etc.
