### ISSUE TITLE
cinecalidad.to [Fake Button]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#6700]
URL(s) where the issue occurs

`https://www.cinecalidad.to/pelicula/ad-astra-hacia-las-estrellas-2019-online-descarga/`

Describe the issue

Fake Button

Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 78 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.23.0

Settings

Default

**Comment by lain566** [comment]
Where's the fake button? I don't see any fake button.

**Comment by KiLL4FuNK** [comment]
![Capturar_2019_12_18_19_54_05_927](https://user-images.githubusercontent.com/36675858/71130237-338cc880-21d0-11ea-9bcc-533da2ce51b7.png)
