### ISSUE TITLE
upstream.to { Antiadblock }

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6702]
### URL(s) where the issue occurs

`upstream.to/hp1xib5k866u`

### Describe the issue

Antiadblock

### Screenshot(s)
![1576769028246153773139](https://user-images.githubusercontent.com/20338483/71185591-bd589680-22a1-11ea-9ab8-020d64549f4b.jpg)

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.22.4

### Settings

-  uBO's default settings

**Comment by uBlock-user** [comment]
upstream.to##+js(set, cRAds, null)

**Comment by ghajini** [comment]
`https://upstream.to/mkp1iys4hq7j`
Popups

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/94d26eaec1bffdd0d23abd9f51c7024231959ae2

**Comment by dumbusernameidk** [comment]
`https://upstream.to/7a1d8bik5lp4/reed-amber4.mp4`

-Debugger Trap
-Anti right-click
-Forced to disable adblock and allow popups to view video

**Comment by ghajini** [comment]
### link=
`https://upstream.to/embed-qv6lu1y7p8fw.html`

### Issue=

Ddos guard won't allow to proceed to page after verfying captcha
![IMG_20201113_234402](https://user-images.githubusercontent.com/20338483/99106494-54d97d00-260a-11eb-91dc-4684ac7bdd32.jpg)
 

due to 
![IMG_20201113_234334](https://user-images.githubusercontent.com/20338483/99106387-2cea1980-260a-11eb-8074-e56c001e0e42.jpg)

(Try to visit from proxy to invoke ddosguard protection on site)
