### ISSUE TITLE
TechRepublic.com - Blocked videos (Peter Lowe's Ad and tracking server list)

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uAssets#6703]
### Affected site:
`https://www.techrepublic.com/`

### Issue:
Videos are blocked.

### Example:
`https://www.techrepublic.com/videos/irobot-2-0-how-the-company-set-itself-up-for-its-next-gen-robots/`

### Problem filter:
* Peter Lowe's Ad and tracking server list

### Problem rule:
`cbsi.com`

### Blocked script:
`https://production-cmp.isgprivacy.cbsi.com/dist/optanon.js`

### Reply from Peter Lowe (after reporting the issue to him):

> Thanks. But this is probably better submitted to the uBlock Origin
> issues page.
> They can add a rule to the unbreak list.

### Possible fix (for 'uBlock filters - Unbreak'):
`@@||cbsi.com/dist/optanon.js$domain=techrepublic.com`

### Other issue (fix needed for 'uBlock filters - Legacy'):
https://github.com/easylist/easylist/issues/4185#issuecomment-567586648

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.8.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.12 (XUL)

**Comment by mapx-** [comment]
@pgl

**Comment by pgl** [comment]
Thanks @mapx- - I actually directed @THEtomaso here.

I'm really not sure about unlisting `cbsi.com`. It is responsible for a lot of dodgy stuff:

 * https://threatcrowd.org/domain.php?domain=cbsi.com

The script that's blocked (https://production-cmp.isgprivacy.cbsi.com/dist/optanon.js) is to do with ads as well.

Any thoughts?

**Comment by mapx-** [comment]
Some days ago `zdnet` was broken as well for the same script. I guess we have to deal with the ads without breaking the domain (it seems to be well integrated in the page functionalities)

**Comment by pgl** [comment]
OK, thanks for that. I've removed it from my list.
