### ISSUE TITLE
www.playok.com

### ISSUE THREAD

**Issue by gomoku** [uBlockOrigin/uAssets#672]
https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/142

**Comment by gomoku** [comment]
1) Just out of curiosity:

a) Why not: `playok.com##script:inject(abort-on-property-write.js, abask)`
I'm guessing: to keep compatibility with ADP syntax and/or to be more efficient?

b) Why not just `#@#.adsbygoogle`
I'm guessing: preventively for the future?

2) Would be possible to additionaly add `playok.com##.adsbygoogle:style(height: 1px !important; width: 1px !important;)` to hide the unsightly empty boxes:

![](https://s3.dodajfote.pl/2017/09/04/combined_48688b.png)

**Comment by okiehsch** [comment]
> Why not: playok.com##script:inject(abort-on-property-write.js, abask)

https://github.com/uBlockOrigin/uAssets/commit/f340633dc681d6e0fb696359e06f5498dd5e0c39#commitcomment-20429199

> Anyway, would be possible to additionaly add playok.com##.adsbygoogle:style(height: 1px !important; width: 1px !important;) to hide the unsightly empty boxes:

[Done](https://github.com/uBlockOrigin/uAssets/commit/aec540c99edd8111c3e02e394f659c7b156e6c89).
