### ISSUE TITLE
wohnungsboerse.net

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#6720]
### URL(s) where the issue occurs

`https://www.wohnungsboerse.net/mietspiegel-Heidelberg/362`

### Describe the issue

Ads and Anti-Adblock

<img width="760" alt="picture645457" src="https://user-images.githubusercontent.com/48647394/71322199-4b609700-24c5-11ea-9ace-33abaebf0dec.PNG">

### Versions

- Browser/version: Firefox 71
- uBlock Origin version: uBlock Origin v1.24.2

### Settings

[Settings.txt](https://github.com/uBlockOrigin/uAssets/files/3992491/Settings.txt)

**Comment by JobcenterTycoon** [comment]
These ads still appear

**Comment by mapx-** [comment]
reproducible only with german ip on my end

test `wohnungsboerse.net##+js(aopr, Number.isNaN)` for breakage

**Comment by JobcenterTycoon** [comment]
you can add this
