### ISSUE TITLE
Incorrectly blocked websocket endpoints

### ISSUE THREAD

**Issue by sorpaas** [uBlockOrigin/uAssets#6721]
### URL(s) where the issue occurs

```
wss://cc3-5.kusama.network/
wss://rpc.kulupu.network/ws
```

### Describe the issue

Those are legit non-ad-related urls at all, but it seems to be incorrectly blocked by "EasyPrivacy" list, with the following regex:

```
/^(https?|wss?):\/\/([0-9a-z\-]+\.)?([0-9a-z\-]+\.)(accountant|bid|cf|club|cricket|date|download|faith|fun|ga|gdn|gq|loan|men|ml|network|ovh|party|pro|pw|racing|review|rocks|ru|science|site|space|stream|tk|top|trade|webcam|win|xyz|zone)\/(.*)/$3p,websocket,domain=~file.pizza|~instant.io|~kiedywakacje.pl|~mellivora.pro|~mellivora.trade|~myinterview.com|~webtorrent.io
```

This causes websites like https://polkadot.js.org/apps to break.

### Versions

- Browser/version: Firefox 70.0.1
- uBlock Origin version: 1.24.2

**Comment by mapx-** [comment]
@ryanbr

**Comment by mapx-** [comment]
> This causes websites like https://polkadot.js.org/apps to break.

How can be tested the breakage ?

**Comment by mapx-** [comment]
no feedback, closing
