### ISSUE TITLE
This rule hide the "PAY" button at bottom, you should remove or change it.

### ISSUE THREAD

**Issue by iamsurfing** [uBlockOrigin/uAssets#6726]
url:https://www.pixiv.net/premium.php

rule:pixiv.net##div:has(:scope > iframe:not([src]))

list:uBlock filters

**Comment by gwarser** [comment]
@DandelionSprout

**Comment by DandelionSprout** [comment]
As the entry remains functional and necessary elsewhere on Pixiv, my best proposal for a fix would be to simply modify it to `pixiv.net##div:not(.submit-area):has(:scope > iframe:not([src]))`.

I'll need to keep in mind to apply the same fix to Nano Placeholder Buster, but am unsure if this is a legit reason to do an @ of JSpenguin or not.

**Comment by krystian3w** [comment]
https://github.com/NanoAdblockerLab/NanoContrib/commit/31e2c940613efe961efecd78a6333e21aa369b43, so recommend edit in ` filters/filters.txt` only.

**Comment by okiehsch** [comment]
The filter breaks the captcha if one wants to create an account.,
https://github.com/uBlockOrigin/uAssets/commit/47850b9beaca86965d3491ff724dc68593003e1c
