### ISSUE TITLE
https://getfreecourses.me

### ISSUE THREAD

**Issue by LiemLT** [uBlockOrigin/uAssets#6727]
### Describe the issue

I cannot bypass BlockAdBlock on this website, even with Nano Defender.

### Screenshot(s)

https://i.ibb.co/5j2BbqW/1.png

### Versions

- Browser/version: Opera 65.0.3467.78
- uBlock Origin version: uBlock Origin v1.23.0

### Settings

- [List here all the changes you made to uBO's default settings]

**Comment by JobcenterTycoon** [comment]
`getfreecourses.me##+js(bab-defuser.js)` will fix that

**Comment by uBlock-user** [comment]
Won't work because of race condition, the script is placed at the top, so make sure it executes first.

**Comment by JobcenterTycoon** [comment]
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=getfreecourses.me`

that works for me too
