### ISSUE TITLE
safetxt.us

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#6732]
### URL(s) where the issue occurs

`[https://safetxt.us/ZVwzQ7NRsu41J2GTYXuZ]`

### Describe the issue

[AntiAdblock]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: [1.24.2]
- uBlock Origin version: [Firefox 71]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by krystian3w** [comment]
`@@||safetxt.us^$generichide`

maybe:

`safetxt.us##+js(nobab)`

---

I suppose website is broken:

`https://openspeedtest.com/Get-widget.php` 

glitch: 

![obraz](https://user-images.githubusercontent.com/35370833/71449564-73632b00-274f-11ea-9b27-99695ca2b339.png)
