### ISSUE TITLE
cryptominers served by cloud-miner.eu

### ISSUE THREAD

**Issue by kgbghjqq** [uBlockOrigin/uAssets#6734]
### URL(s) where the issue occurs

`http://piratebayztemzmv.onion/`

### Describe the issue

The domain cloud-miner.eu seems to serve cryptominer scripts, for example 
`https://cloud-miner.eu/tkefrep/tkefrepp.js?tkefrep=bs?nosaj=faster.moneroocean`

**Comment by mapx-** [comment]
it can be tested here:
`piratebayztemzmv.onion.pet`

**Comment by mapx-** [comment]
@ryanbr
