### ISSUE TITLE
youporn.com [NSFW]

### ISSUE THREAD

**Issue by electrifying** [uBlockOrigin/uAssets#6735]
`https://www.youporn.com/watch/14999273/busty-teen-schoolgirl-mila-azul-solo-masturbation/`

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

video not working and empty black block at the bottom of the video

`https://imgur.com/8iTcs0q`

### Versions

- Browser/version: google chrome 78.0.3904.108
- uBlock Origin version: 1.23.0

### Settings

uBO's default settings

### Notes

none

**Comment by exodius48** [comment]
No issue here. All videos can be played.
Tested on:
1. Firefox 71.0 x64 UBO 1.24.2 
2. Chrome Official 79.0.3945.88 x64 UBO 1.23.0 + uBlock Protector
3. Vivaldi 2.10.1745.23 (Stable channel) (64 bit) UBO 1.23.0 + uBlock Protector

**Comment by Yuki2718** [comment]
Video works on my end, tested on Brave 1.1.23 (its blocker turned off) w/ uBO 1.24.2 (default setting).
For the black box
`youporn.com##aside.clearfix`
works.
`youporn.com##aside.clearfix:has(a.ad-remove)`
might be better to avoid possible FPs tho.
