### ISSUE TITLE
https://www.elamigos-games.com

### ISSUE THREAD

**Issue by Jorge9811** [uBlockOrigin/uAssets#6737]
### URL(s) where the issue occurs

`https://www.elamigos-games.com/`

### Describe the issue

I went to this page and I can very clearly see an ad on the main page.

### Screenshot(s)

![firefox-2019-12-26_07-18-53](https://user-images.githubusercontent.com/54429803/71471993-0e8bed00-27b0-11ea-832d-293e204e0c9a.png)

### Versions

- Browser/version: Mozilla Firefox v71.0 x86
- uBlock Origin version: 1.24.2

### Settings

https://i.imgur.com/9n9q0WA.png

Because I'm using Nano Defender, I also have userResourcesLocation adjusted accordingly.

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by uBlock-user** [comment]
Already fixed with `elamigos-games.com##[href^="https://track.wg-aff.com/"]` found in uBlock Filters. Force update your list.

**Comment by Jorge9811** [comment]
> Already fixed with `elamigos-games.com##[href^="https://track.wg-aff.com/"]` found in uBlock Filters. Force update your list. If cosmetic filtering is disabled enable it back.
That didn't work earlier in the morning, but it seemed to work right now, so fixed.
