### ISSUE TITLE
fmovies.to

### ISSUE THREAD

**Issue by aldiener58** [uBlockOrigin/uAssets#6738]
I am new to this website and would appreciate your patience if I post incorrectly. I was referred to this site by a contributor on the forum.lanik.us website.

I am having new issues with the above referenced website. New popups are occurring or preventing playing of videos. 

An example is `https://fmovies.to/film/everybody-hates-chris-4.n3lkm/z85r6m`
The problem only affects the MyCloud links and not the F5-HQ links.

Sample popup ads, in the event this is helpful:
`https://mcloud.to/embed/gxz2zv?key=061e4582af34fb1cbc0f7f41a7d07bd3`
`https://www.google.com/favicon.ico`
`https://postlnk.com/1/2649272/?var=2649272&rid=wfxzsvAkbQDjdtH2xjZy_Q%3D%3D`

I have updated my filters.

Any support would be appreciated.

Thank you.

uBo 1.23.0
Chrome 79.0.3945.88 (Official Build) (64-bit)

**Comment by uBlock-user** [comment]
`mcloud.to##+js(acis, Math, zfgloaded)`

**Comment by aldiener58** [comment]
Thank you. However, this filter appears to have made all of the F5-HQ links complete disappear. Is that possible?

**Comment by uBlock-user** [comment]
> However, all of the F5-HQ links have now disappeared from fmovies.to

The filter only applies to `mcloud.to` domain, so not possible.

**Comment by aldiener58** [comment]
Thank you, @uBlock-user for your prompt and clear response.
Your proposed solution has worked and I am grateful.
