### ISSUE TITLE
connect.squareup.com

### ISSUE THREAD

**Issue by maxbeatty** [uBlockOrigin/uAssets#6741]
### URL(s) where the issue occurs

`https://connect.squareup.com/payments/analytics/frame.html`
`https://connect.squareupsandbox.com/payments/analytics/frame.html`

### Describe the issue

[Square Payment Form](https://developer.squareup.com/docs/payment-form/what-it-does) allows merchants to accept payments online. To prevent buyer fraud, Square collects additional information at the time a potential buyer is presented the payment form. This data is not given to the merchants. Developers and potential customers are unable to complete their payments as a result of this frame being blocked.

### Versions

- Browser/version: Chrome 79
- uBlock Origin version: 1.23.0

### Settings

- default

### Notes

You can reproduce this by going through the purchase flow for a [Square Reader](https://squareup.com/shop/hardware/us/en/products/free-credit-card-reader). When you get to the payment form, you will see this error in the developer console:

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://connect.squareup.com') does not match the recipient window's origin ('null').
```

**Comment by krystian3w** [comment]
Rather as long as you can buy it, nobody's gonna fix it.
