### ISSUE TITLE
umidigi.com

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#6744]
https://www.umidigi.com/page-umidigi_power3_activity.html

Hi, when you go to https://www.umidigi.com/page-umidigi_power3_activity.html and click buy now, it tries to open a new tab and then automatically closes it when ublock origin's enabled, but when ublock origin's disabled, it works fine. I already updated the addon and filters. Is there a way to fix that? Thanks.

![umidigi 1](https://user-images.githubusercontent.com/35790889/71490360-90a00400-27f8-11ea-9307-569ca5e6ed04.jpg)

![umidigi 2](https://user-images.githubusercontent.com/35790889/71490367-94cc2180-27f8-11ea-8d09-1d8f7f1dc1da.jpg)

Firefox 71.0 (64-bit)
uBlock Origin 1.24.2

**Comment by everaldoalves220** [comment]
Tem com fazer root ou estalar twrp

**Comment by everaldoalves220** [comment]
No umidigi power3 tem como fazer root e estalar twrpp
