### ISSUE TITLE
bing.com

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#6745]
bing.com/translator

Hi, when you go to bing.com/translator and type some text in the original text box nothing appears in  the translated text box with ublock origin enabled, but if you disable ublock origin, text appears in the translated text box just fine. How do you fix that? I've already updated ublock origin and the filters. Thanks. Have a nice day.

![bing translate](https://user-images.githubusercontent.com/35790889/71490537-44a18f00-27f9-11ea-957e-1d036918e46b.jpg)

Firefox 71.0 (64-bit)
uBlock Origin 1.24.2

**Comment by llacb47** [comment]
Works fine for me, what filter lists are you using? What other extensions? Any custom filters?

**Comment by IoanPaleru** [comment]
AdGuard Annoyances​​​​​ 21,377 used out of 23,965​​
​​
AdGuard Social Media​
​​​​9,737 used out of 9,763​​
​​
Anti-Facebook​
​​​​68 used out of 68​​
​​
EasyList Cookie​
​​​​16,324 used out of 16,327​​
​​
Fanboy’s Annoyance​
​​​​13,020 used out of 55,897​​
​​
Fanboy’s Social​
25,191 used out of 26,313​​​​

**Comment by krystian3w** [comment]
disable these:

> 
> Anti-Facebook​
> ​​​​68 used out of 68​​
> ​​
> EasyList Cookie​
> ​​​​16,324 used out of 16,327​​
> ​​
> Fanboy’s Annoyance​
> ​​​​13,020 used out of 55,897​​
> ​​
> Fanboy’s Social​
> 25,191 used out of 26,313​​​​

**Comment by IoanPaleru** [comment]
Ok, thanks. So there's no way to get it to work with those filter lists enabled is there?

**Comment by krystian3w** [comment]
In logger: https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by IoanPaleru** [comment]
Thanks for the help and excellent information, I appreciate it.
