### ISSUE TITLE
drive.google.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6748]
## URL(s) where the issue occurs

`https://drive.google.com/drive/folders/1gV6kYi-qP0lUIxtVcklMrusd8p2q9d08`

or example direct:

`https://drive.google.com/open?id=1GsZDLdUZEqj6kzp6X4lLLQN7gF6aQ4WN`

## Describe the issue

EasyPrivacy:

```
||google.com^*/viewerimpressions?
```

break Google scan files, so unnecessarily extended waiting to download 7z archive - normally a scan takes a few seconds, with the problematic EasyPrivacy filter, the scan is extended up to a minute and ends in an error.

Blocked right click / selection of text:

`drive.google.com/open?...`

## Screenshot(s)

Error generated after a minute of trying scan file by Google.

![](https://user-images.githubusercontent.com/35370833/71496431-8eb75e80-2853-11ea-903f-308cd1dc9f1f.png) |
--- |

As for me, such a delay is not worth the "increased" privacy towards Google.

## Versions

- Browser/version: Firefox 71
- uBlock Origin version: 1.24.2
### Settings

- Default + Block reports CSP

## Notes

Works only these:

Filter:

`||google.com^*/viewerimpressions?$badfilter`

or Rule:

```
drive.google.com https://clients6.google.com/drive/v2internal/viewerimpressions xmlhttprequest allow
```

---

for some reasons this no works: `@@||google.com^*/viewerimpressions?` (block reports CSP guilty?)

**Comment by krystian3w** [comment]
https://github.com/LiCybora/NanoDefenderFirefox/issues/161

**Comment by Yuki2718** [comment]
At least for that site, it's not a matter of uBO or CSP. I get the error even with uBO disabled. The error in this case was due to size limit for the virus scan (100MB). Maybe you can find another link?

As a side note, these may be added to Privacy filter:
`||drive.google.com/drive/logImpressions
||ssl.gstatic.com/docs/common/cleardot.gif$image,redirect=1x1-transparent.gif`

I haven't noticed any problem by them so far but they need to be checked by others.

**Comment by krystian3w** [comment]
For my only block `CSP reports` glitch exception.

**Comment by Yuki2718** [comment]
> 
> 
> For my only block `CSP reports` glitch exception (so `badfilter` or `my "dynamic" rules`).

Given everything was reproduced w/ default settings (so "block CSP report" is not checked), probably it's not relevant to this case.

**Comment by krystian3w** [comment]
There is also an option that my Windows 10 or Firefox is corrupted: https://github.com/PolishFiltersTeam/PolishCookieConsent/issues/45

---

On my refreshed profile, I got broken a new "activity-stream" addon for `about:newtab` / `about:home` (pages are blank...).

> https://wiki.mozilla.org/Firefox/Activity_Stream

**Comment by Yuki2718** [comment]
Sometimes scan & download goes successfully even w/out the exception on Firefox.

**Comment by krystian3w** [comment]
Maybe it depends on what type of file you are downloading, I see problems with how I am downloading 7z archives, and files above a certain size cannot be scanned and if we have a direct link to the file this download is much easier.

**Comment by Yuki2718** [comment]
I initially thought of that and searched, some says the maximum for scan is 25MB and others 100MB, but the file is below 25MB. Now the error occured even on Firefox w/ the exception. I'll leave this matter to experts here.

**Comment by krystian3w** [comment]
Hook up, is there support for filtering embedded graphics/texts/nodes in emails?

---

Currently, you can only filter an add-on store or a domain opened in a new help card: 

https://addons.thunderbird.net/en-US/thunderbird/addon/open-tab/

**Comment by krystian3w** [comment]
How will he be able to filter files/text/nodes emails, not before.

**Comment by krystian3w** [comment]
@mapx- / @okiehsch  possible recover right click on:


`https://drive.google.com/open?id=1GsZDLdUZEqj6kzp6X4lLLQN7gF6aQ4WN`

**Comment by mapx-** [comment]
I cannot reproduce the issue FF / chrome.
Could you test again ?

**Comment by krystian3w** [comment]
blocked right click:

`https://drive.google.com/file/d/1GsZDLdUZEqj6kzp6X4lLLQN7gF6aQ4WN/view` - nobody try fix it...

Block CSP Reports still generate breakage with EasyPrivacy:

`https://drive.google.com/drive/folders/1gV6kYi-qP0lUIxtVcklMrusd8p2q9d08`

**Comment by krystian3w** [comment]
Maybe it is time for:

```
!if CSP_Block
||google.com^*/viewerimpressions?$badfilter
!endif
```

**Comment by mapx-** [comment]
tested in FF / chrome (+ Block reports CSP), no issue on my end

**Comment by krystian3w** [comment]
# And still no fixed right click on:

```
https://drive.google.com/file/d/1GsZDLdUZEqj6kzp6X4lLLQN7gF6aQ4WN/view
```

use subdomain `drive` if break `maps.google.com`

**Comment by mapx-** [comment]
test
`drive.google.com##+js(aeld, contextmenu)`
