### ISSUE TITLE
Firefox plugin 1.14.4 prevents www.motor-talk.de from refresh

### ISSUE THREAD

**Issue by mygithuber** [uBlockOrigin/uAssets#675]
### URL(s) where the issue occurs
`https://www.motor-talk.de/forum/welches-motoroel-t230315.html?page=5850`
Try at bottom of page reaching previous or next page, it isn't loaded/displayed.
All internal links on motor-talk.de are involved.

### Describe the issue
This issue has been introduced since Firefox 55.0.3 (32bit Windows) and uBlock origin 1.14.4.
There is a dissusion going on at:
'https://www.motor-talk.de/forum/motortalk-firefox-t6046306.html?page=7#post51169047'

### Screenshot(s)
[not necessary...]

### Versions
- Browser/version: Firefox 55.0.3 (32bit)
- uBlock Origin version: 1.14.4
- Win 7 prof 64 bit

### Settings
standard

### Notes
It seems to be depended to uBlock. If uninstalling, everything works...

Thx for help

**Comment by okiehsch** [comment]
Works on my end, this is not a filter issue.

https://github.com/gorhill/uBlock/releases/tag/1.14.6
> There are many reports of people experiencing issues with some web sites, or images not loading, etc. Turns out many of these are a result of using some legacy extensions along uBO/webext. For instance, Reek's AAK in GreaseMonkey has been causing issues with images not loading.
If you experience such issue, you will have to disable all your legacy extensions and see if this fixes your issue. If so, then you will have to re-enable your legacy extension one by one to find the one(s) causing the problem.
Everything is moving to WebExtensions, so it might be just a good time to start giving up on legacy extensions, they are not going to be supported at all in a couple of weeks when Firefox 57 is released.
Another option is to install uBO 1.13.8 and disable auto-update for it.

**Comment by meyergru** [comment]
Correct. It is not a filter issue. The mere presence of uBO does trigger the behavior. The site works correctly only if uBO is deactivated completely. It does not suffice to disable uBO for the site or any of its prerequisites, so no specific filter can be the issue.

**Comment by okiehsch** [comment]
> The mere presence of uBO does trigger the behavior

Well it works on my end, so the mere presence of uBO does not trigger the behaviour as I use 
Firefox 55.0.3 (64 bit) with only one extension - uBO.

**Comment by meyergru** [comment]
OK, I stand corrected. If I enable **only** uBO, there is indeed no problem.

However - adding other plugins on top triggers the behavior. I tried "MM3 Proxy Switch" and "Live HTTP Headers" (error is present) and "KeeFox" (no errors).

Disabling uBO makes the problem go away in any case, so the impression people get is that uBO is causing the problem.

So probably there was a change in how certain API calls/events are being cascaded through addons by Firefox and some event is not being transferred any more?

**Comment by gorhill** [comment]
Legacy extensions can cause this when used with uBO/webext. Follow the steps in 1.14.6 to find out which extension(s) causes this. If you think the legacy extensions should not interfere, open an issue at bugzilla.mozilla.org. Keep in mind legacy extensions will no longer be loaded in a few weeks, when FF57 is released.
