### ISSUE TITLE
https://www.fcportables.com/

### ISSUE THREAD

**Issue by maxvlas** [uBlockOrigin/uAssets#6753]
### URL(s) where the issue occurs
https://www.fcportables.com/
Open and wait a few seconds

### Describe the issue

Here I decided to download. after clicking on the download, I got a window (screenshot below)

### Screenshot(s)
![taRKeCYKan](https://user-images.githubusercontent.com/11572859/71541694-024d8e80-296e-11ea-800a-b071470c3965.gif)

### Versions

- Browser/version: Google Chrome Version 79.0.3945.88 (Official Build), (32 bit)
- uBlock Origin version: uBlock Origin 1.23.0

### Settings

![2019-12-28_122613](https://user-images.githubusercontent.com/11572859/71541707-37f27780-296e-11ea-97e8-c88cdb1f4420.png)

### Notes

The uBlock filters rules for this site are probably outdated and need to be edited.

**Comment by P0Rtvine** [comment]
Enable - **uBlock filters**

**Comment by maxvlas** [comment]
> Включить - **фильтры uBlock**

Everything is decided, forgot uBlock filters
