### ISSUE TITLE
mixdrop.to

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6754]
### URL(s) where the issue occurs

`https://mixdrop.to/e/6pfpw`

### Describe the issue

Popup ads

### Versions

- Browser/version: opera browser stable/firefox android stable
- uBlock Origin version: 1.24.2

### Settings

-  uBO's default settings

### Notes
See if this works good

`mixdrop.to##+js(aeld, click, dtnoppu)`

`||www.gearbest.com^$domain=mixdrop.to`
`||www.gearbest.com^$domain=mixdrop.co`

**Comment by llacb47** [comment]
Second filter is bad, gearbest is a real site. Popups go there because of ad fraud I think.

**Comment by ghajini** [comment]
1.
`gearbest.com` is used for ad request(push notifications) on my side

2.
These are required on firefox android
`||www.paupbxxmhh.com^`
`||www.nlbnegea.com^`

**Comment by llacb47** [comment]
Test
```
mixdrop.to##+js(aopw, _pop)
mixdrop.to##+js(acis, document.addEventListener)
mixdrop.to##div[onclick]
```

**Comment by ghajini** [comment]
Still `||www.gearbest.com^$domain=mixdrop.to`
Is required .......

**Comment by llacb47** [comment]
Really? what script is loading `gearbest.com`?

**Comment by ghajini** [comment]
Over here
`https://watchonlinemovies.net/2241-housefull-4-2019-hindi-720p-bluray-x264-ac3-51.html`
1st add
`*$subdocument,3p,domain=watchonlinemovies.net,badfilter` to ubo
Then
Click media server 1,wait for complete video to load, now pause that, then click media server 3, wait for complete load, `gearbest.com` is loaded and ubo logger is bombarded with so many useless requests

**Comment by llacb47** [comment]
Even with my filters?

**Comment by ghajini** [comment]
Yes

**Comment by ghajini** [comment]
URL =
`mixdrop.to/e/tjea2`
`mixdrop.co/e/aw5mv`
IP =try european ip 

Filter=

`mixdrop.*##+js(acis, String.fromCharCode)`
prevents these unnecessary requests

 and help to reduce memory usage

**Comment by llacb47** [comment]
US IP works fine, no unnecessary requests using filters from https://github.com/uBlockOrigin/uAssets/issues/6754#issuecomment-569442663

**Comment by ghajini** [comment]
because your filters doesn't work, I explained already here
https://github.com/uBlockOrigin/uAssets/issues/6754#issuecomment-569449046....

being on low memory device, I don't want these unnecessary requests to consume memory on my side(video plays on my side without requiring these requests)....
This filter exactly works at good
`mixdrop.*##+js(acis, String.fromCharCode)`

Regarding ip when I access `mixdrop.to/e/tjea2` ,video player doesn't load on my side due to some cors policy ,403 forbidden error  (console) but when I change my ip to Europe region(opera vpn) I can access the video....

**Comment by llacb47** [comment]
Ok, it works for me as well

**Comment by ghajini** [comment]
So your filter 
`mixdrop.*##div[style*="z-index"][onclick]`
doesn't get applied on media server 3 here

`https://watchonlinemovies.net/2241-housefull-4-2019-hindi-720p-bluray-x264-ac3-51.html`

Is it some bug or limitation of that filter

**Comment by ghajini** [comment]
Play button unclickable here from mixdrop.to

`https://watchonlinemovies.net/2253-pati-patni-aur-woh-2019-hindi-720p-bluray-x264-ac3-51.html`

**Comment by mapx-** [comment]
> We are Fixing All Movies Streaming Links Kindly Be Patient...

**Comment by ghajini** [comment]
Just whitelist site in ubo and it works

**Comment by mapx-** [comment]
it should work now

**Comment by ghajini** [comment]
`https://mixdrop.co/f/fg9x0hcrhl60y`

Shady 3p (xhr's & CSS) requests appearing

**Comment by ghajini** [comment]
`mixdrop.*##+js(acis, $, String.fromCharCode)`

Prevents those 
 https://github.com/uBlockOrigin/uAssets/issues/6754#issuecomment-569533297 requests......

No breakages so far(nor in embedded sites `moviesghar.xyz` or original `mixdrop.*` ).....

**Comment by huyszn** [comment]
New mixdrop domain: `mdfx9dc8n.net`

**Comment by mapx-** [comment]
Example link ?

**Comment by huyszn** [comment]
@mapx- `https://mdfx9dc8n.net/f/xomzrojxtg8743`

**Comment by huyszn** [comment]
New mixdrop domain: `mdzsmutpcvykb.net`

`https://mdzsmutpcvykb.net/f/pkdm786pamzodq`
