### ISSUE TITLE
www.tagesanzeiger.ch / The video window gets smaller and smaller until it disappears.

### ISSUE THREAD

**Issue by drifter-x** [uBlockOrigin/uAssets#6755]
### URL(s) where the issue occurs
for example https://www.tagesanzeiger.ch/video/?video_id=412893

The problem still exists.

It looks like the filter
tagesanzeiger.ch##body:style(position: unset !important; overflow-x: hidden !important; overflow-y: scroll !important; user-select: text !important;)
is responsible for it.

**Comment by llacb47** [comment]
Can't reproduce, there is an annoying scrollbar on the video caused by that filter I think.
