### ISSUE TITLE
Zillow web page turns white with built-in "uBlock filters - Privacy"

### ISSUE THREAD

**Issue by meanhacker** [uBlockOrigin/uAssets#6758]
### URL(s) where the issue occurs

`https://www.zillow.com/homedetails/2001-Wood-St-Eureka-CA-95501/18818489_zpid/`

### Describe the issue

The webpage would finish loading and after a few seconds, it would turn white.

### Versions

- Browser/version: Firefox 71.0 (64-bit)
- uBlock Origin version: 1.24.2

### Settings

- To fix the Zillow webpage turning white issue, simply add this to your "My filters" list:

```
! 12/28/2019 zillow.com
@@||www.googletagservices.com/tag/js/gpt.js$script,domain=www.zillow.com
```

### Notes

I recently noticed Zillow wasn't working correctly with uBlock filters enabled. After a few minutes of investigation, using the logger and disabling filter lists, I found that "uBlock filters - Privacy" under "Built-in" is causing the issue. I narrowed it down to one offending script which, if left unblocked, inhibits the issue.

**Comment by krystian3w** [comment]
After few seconds images gone:

![obraz](https://user-images.githubusercontent.com/35370833/71551061-221c9b00-29de-11ea-81e8-a635c6b0f28f.png)
