### ISSUE TITLE
fontsfree.pro

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6759]
`https://fontsfree.pro/base-web-fonts/sans-serif-grotesque/503-helvetica-neue-cyr.html`

detect block ads:

![obraz](https://user-images.githubusercontent.com/35370833/71550999-d7e6ea00-29dc-11ea-9f1e-9b7d0b835b81.png)

**Comment by krystian3w** [comment]
`window.adBlock = false;`

`fontsfree.pro##+js(set, adBlock, fales)`

or try with `apow`/`apor`...

**Comment by krystian3w** [comment]
```js
window.adBlock = false;
```

---

`fontsfree.pro##+js(set, adBlock, falese)`

or `apor`/`apow`...

**Comment by krystian3w** [comment]
```js
window.adBlock = false;
```

---

`fontsfree.pro##+js(set, adBlock, false)`

or `apor`/`apow`...

**Comment by okiehsch** [comment]
Fixed in annoyances.
