### ISSUE TITLE
time.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#676]
Multiple blank ad spaces in articles and sections on `http://time.com`. Sponsored ads in articles as well.

**SS:**
http://i.imgur.com/xC5noZ1.jpg (Sponsored as at the top of article and blank spaces all over)
http://i.imgur.com/x12iaoa.jpg (Blank ad spaces all over section page)
http://i.imgur.com/ZSbUnkt.jpg (Blank ad spaces on the Life.com section)

**Error URLs (_Respectively_):**
```
http://time.com/4927440/iphone-8-edition-names/
http://time.com/section/tech/
http://time.com/photography/life/
(http://life.com/)
```

_**Note:** Using uBO 1.14.8 on Chrome 61 with the default filters and settings._

**Comment by gotitbro** [comment]
Most ads are hidden by these filters from the Adguard English filter:
```
time.com##._2bnZiB_7
time.com##.column > .tWo0WoSf
time.com##.column > .row > div[data-reactid="137"]
```
@gorhill I think you said something along the lines of incorporating the Adguard English Filter as the default filter sometime ago, I really think that would be beneficial for all. Any update on this?

**Comment by gotitbro** [comment]
@gorhill This might be relevant: https://github.com/uBlockOrigin/uAssets/issues/471#issuecomment-310874872

Would really love to hear your thoughts about the Adguard Filters.

**Comment by jv84** [comment]
These filters are not working anymore.

**Comment by stephenhawk8054** [comment]
@jv84 Can you give exact link where you see the issue and screenshot how the issue looks like?

**Comment by jv84** [comment]
> [@jv84](https://github.com/jv84) Can you give exact link where you see the issue and screenshot how the issue looks like?

https://time.com/7271378/republicans-reactions-democrats-resignations-waltz-hegseth-atlantic-group-chat-leak/

![Image](https://github.com/user-attachments/assets/b36f9e33-c578-4680-838e-c087c1ea8887)

https://time.com/7272563/earthquake-myanmar-thailand-impact-photos/

![Image](https://github.com/user-attachments/assets/efd8669f-ddff-4ecb-b5d7-c63744d4f231)
