### ISSUE TITLE
The Star Wars Wiki (aka Wookieepedia)

### ISSUE THREAD

**Issue by Jorge9811** [uBlockOrigin/uAssets#6761]
### URL(s) where the issue occurs

`https://starwars.fandom.com/wiki/Darth_Malgus`

### Describe the issue

I went to this page and I can very clearly see an ad on the main page.

### Screenshot(s)

![waterfox-2019-12-29_06-40-07](https://user-images.githubusercontent.com/54429803/71555073-41c7b980-2a06-11ea-8668-db110671dbcb.png)

### Versions

- Browser/version: Mozilla Firefox v71.0 x64
- uBlock Origin version: 1.24.2

### Settings

https://i.imgur.com/9n9q0WA.png

Because I'm using Nano Defender, I also have userResourcesLocation adjusted accordingly.

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by uBlock-user** [comment]
`fandom.com##[class^="affiliate-unit"]`
