### ISSUE TITLE
lordoftheseries - no snow please

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#6764]
hello,
help with disabling the script that does the snow fall please?

https://lordoftheseries.gr/

thanks

**Comment by uBlock-user** [comment]
`lordoftheseries.gr.wp-super-snow-flake`

**Comment by krystian3w** [comment]
```html
<script type='text/javascript'>/* <![CDATA[ */ var wpt = {"ajax_url":"https:\/\/lordoftheseries.gr\/lordrings170813\/admin-ajax.php"}; /* ]]> */</script>
```

❓ 

`lordoftheseries.gr##+js(aopr, wpt)`

`lordoftheseries.gr##^script:has-text(/wpt = {/)`

**Comment by krystian3w** [comment]
@okiehsch  possible remove filter - webmaster disabled plugin.

**Comment by okiehsch** [comment]
Thanks for the heads up.
