### ISSUE TITLE
uptobox.com|uptostream.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6765]
### URL(s) where the issue occurs

`uptobox.com/b5jf378dfw6n`

`uptobox.com/1ou816zz2ue9`

`https://uptostream.com/1ou816zz2ue9`

### Describe the issue

Popup ads

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.24.2

### Settings

-  uBO's default settings

**Comment by gwarser** [comment]
To allow subtitles blocked by CNAME what option should be used
```

@@||uptobox.com^$xhr,domain=uptostream.com
@@||uptobox.com^$cname,domain=uptostream.com
@@||uptobox.com^$xhr,cname,domain=uptostream.com
```

?

https://www.reddit.com/r/uBlockOrigin/comments/fzzua6/no_subtitle_on_uptostream_with_firefox/

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/3a4347519035e046c0d2677a1f7b7f05eb246cdf

**Comment by gwarser** [comment]
Other filters are enclosed in `!#if env_firefox` and I see two without exclamation mark.

**Comment by mapx-** [comment]
fixed
