### ISSUE TITLE
sphinx_materialdesign_theme.css is considered to be malware

### ISSUE THREAD

**Issue by KOLANICH** [uBlockOrigin/uAssets#6766]
### URL(s) where the issue occurs
https://prjxray.readthedocs.io/en/latest/architecture/configuration.html

### Describe the issue
https://github.com/myyasuda/sphinx_materialdesign_theme/blob/e25b92381011847aee500ba42f774e1ed2ee6d72/src/scss/_root.scss#L5L6

Issue about this [has been created](https://github.com/myyasuda/sphinx_materialdesign_theme/issues/7) but is ignored for a long time.

### Settings

- JS disabled

### Notes

We may want to parse CSS and detect such kind of sabotage automatically.

**Comment by gwarser** [comment]
readthedocs.io##body:style(display:block!important)

**Comment by KOLANICH** [comment]
It gonna solve the issue only for readthedocs. But it won't solve the problem of the mentioned malicious free software used by people who use free software recklessly.

**Comment by gorhill** [comment]
The issue is with the stylesheet, this is where this has to be solved.

**Comment by KOLANICH** [comment]
When someone is spreading malware are AV vendors just politely asking the malware author not to spread the malware or just add the malware into their bases and block it?

**Comment by gorhill** [comment]
Your issue is that a web page is not rendering properly with javascript disabled -- this is not unexpected.
No filters will be added to filter lists for issues which arise as a result of custom rules.
