### ISSUE TITLE
earnload.com{ Anti-adblock }

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6767]
### URL(s) where the issue occurs

`https://earnload.com/9osn`

### Describe the issue

Antiadblock in next page after clicking verify

### Screenshot(s)

![IMG_20200101_021036](https://user-images.githubusercontent.com/20338483/71633723-f39bfb80-2c3b-11ea-9aaa-ed06754706f7.jpg)

### Versions

- Browser/version: firefox android stable
- uBlock Origin version: 1.24.2

### Settings

- uBO's default settings

**Comment by llacb47** [comment]
Test
```
earnload.com##+js(aopr, app_vars.force_disable_adblock)
! junk requests
earnload.com##+js(acis, Math, zfgloaded)
||earnload.com/sw.js$script,1p
! countdown focus annoyance
earnload.com##+js(set, blurred, false)
```

**Comment by ghajini** [comment]
`earnload.co##+js(abort-current-inline-script, Math, XMLHttpRequest)`

**Comment by ghajini** [comment]
`http://earnload.co/Milk2`

Filters update
```
earnload.co##+js(acis, String.fromCharCode, break)
earnload.co##+js(disable-newtab-links)
*$image,3p,domain=earnload.co
```
