### ISSUE TITLE
goulburnpost.com.au - newspaper pages not rendering correctly 

### ISSUE THREAD

**Issue by joporta** [uBlockOrigin/uAssets#6769]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by gwarser** [comment]
##.subscriber-hider:style(display:block!important)?

**Comment by gorhill** [comment]
The site is broken by the blocking of `piano.io` by Peter Lowe's.

I will fix with the cosmetic filter to avoid to have to connect to 3rd-party `piano.io`, given what I see on their [front page](https://piano.io/).

**Comment by joporta** [comment]
Thanks for the prompt fix. 

Sure appreciate it. 

    On Wednesday, January 1, 2020, 7:21:54 AM PST, Raymond Hill <notifications@github.com> wrote:  
 
 
The site is broken by the blocking of piano.io by Peter Lowe's.

I will fix with the cosmetic filter to avoid to have to connect to 3rd-party piano.io, given what I see on their front page.

**Comment by joporta** [comment]
It looks like a similar situation at another news site:
https://www.newcastleherald.com.au/story/6565877/scorched-in-seven-days-a-look-back-at-the-week-that-was/

https://www.newcastleherald.com.au/story/6573750/hunters-tamil-students-shine-in-state-library-of-nsw/


    On Wednesday, January 1, 2020, 7:21:54 AM PST, Raymond Hill <notifications@github.com> wrote:  
 
 
The site is broken by the blocking of piano.io by Peter Lowe's.

I will fix with the cosmetic filter to avoid to have to connect to 3rd-party piano.io, given what I see on their front page.

**Comment by michaelburton** [comment]
Same issue on another news site from the same publisher, fixable using the same filter rules

https://www.maitlandmercury.com.au/story/6859919/time-for-leniency-over-as-vic-shuts-down/?cs=7

**Comment by llacb47** [comment]
This issue probably happens on all Australia Community Media sites: `https://www.acmadcentre.com.au/brands/`

I absolutely despise paywalls, but isn't the policy that `Circumventing a paywall is considered out of scope.`? 

This fix is technically circumventing the paywall broken by Peter Lowe's list. 

`piano.io` is used for paywalls: `https://piano.io/product/vx/`

Should uBO badfilter this rule from Peter Lowe's list totally? Easylist/easyprivacy do not block this domain.

**Comment by mapx-** [comment]
uBO unbreak has this replacing filter: `||piano.io^$3p`

As for paywall, @gorhill what to you think about ?

**Comment by llacb47** [comment]
@gorhill did you see this?

**Comment by gorhill** [comment]
I don't see a paywall when I try the link `https://www.goulburnpost.com.au/story/6558708/the-rfs-needs-more-resources-a-firefighters-story-from-the-front-line/` with either AdGuard or ABP. We will also have to take this into account, if users find the site working with either AdGuard or ABP, it should work as well with uBO.

**Comment by llacb47** [comment]
There is article access metering -- powered by piano. Tested here: `https://www.maitlandmercury.com.au/story/6859919/time-for-leniency-over-as-vic-shuts-down/?cs=7`

ABP defaults: 
![image](https://user-images.githubusercontent.com/16567977/90559017-fe73b400-e16a-11ea-8e11-085f9c44b8ab.png)

Adguard defaults: 
![image](https://user-images.githubusercontent.com/16567977/90559160-37138d80-e16b-11ea-8df4-be85ab28e905.png)

uBo defaults -- no access metering: 
![image](https://user-images.githubusercontent.com/16567977/90559268-55798900-e16b-11ea-812b-7496caf8c412.png)

**Comment by gorhill** [comment]
> Should uBO badfilter this rule from Peter Lowe's list totally? Easylist/easyprivacy do not 3p block this domain.

Unless the filter breaks a lot of site, we shouldn't badfilter it, just create an exception for the site here.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/16666
