### ISSUE TITLE
midiavip.com

### ISSUE THREAD

**Issue by lyndmi** [uBlockOrigin/uAssets#6770]
### URL(s) where the issue occurs

https://midiavip.com/QNG-AY

If link above not work, click this link first and continue https://midvip.xyz/down.html?xurl=QNG-AY

### Describe the issue

Adblock warning message in portugal

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24647715/71644317-dceeb680-2cc6-11ea-9e8e-6b653e8e7d0f.png)

### Versions

- Browser/version: 65.0.3467.78
- uBlock Origin version: 1.23.0

### Settings

- Default settings

### Notes
None

**Comment by krystian3w** [comment]
This is need scriplet, because this not help:

> 
> ```
> ||midiavip.com^$generichide
> midiavip.com##.adsbygoogle
> ```

`midiavip.com##+js(nobab)`
