### ISSUE TITLE
linkvietvip.com

### ISSUE THREAD

**Issue by lyndmi** [uBlockOrigin/uAssets#6771]
### URL(s) where the issue occurs

`https://linkvietvip.com/WcXk`

### Describe the issue

Adblock warning message

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24647715/71667410-44f3da00-2d65-11ea-8a41-69835f8de9bd.png)

### Versions

- Browser/version:  Opera 65.0.3467.78
- uBlock Origin version:  1.23.0

### Settings

- Default settings

### Notes
Also add countdown booster if possible

**Comment by okiehsch** [comment]
> Also add countdown booster if possible

Not possible, the site validates the timer on the server side.
