### ISSUE TITLE
freejpmusic.net

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#6775]
### URL(s) where the issue occurs

`https://freejpmusic.net/album-%E6%B0%B4%E6%9C%A8%E4%B8%80%E9%83%8E-%E6%B0%B4%E6%9C%A8%E4%B8%80%E9%83%8E-%E3%83%99%E3%82%B9%E3%83%88%E3%83%BB%E3%82%AA%E3%83%96%E3%83%BB%E3%82%A2%E3%83%8B%E3%82%AD%E3%83%B3%E3%82%B0/`

### Describe the issue

Anti-Adblock Script

### Screenshot(s)

![Screenshot_2020-01-04  Album  水木一郎 – 水木一郎 ベスト・オブ・アニキング-赤の魂+青の魂- (2004 08 04 MP3+FLAC RAR) - FreeJPMusic Net](https://user-images.githubusercontent.com/24980766/71770926-45c17300-2f01-11ea-8196-acfb497dc9c3.png)

### Versions

- Browser/version: Firefox 71.0
- uBlock Origin version: 1.24.3b7

### Settings

- Default filters

**Comment by theinstantmatrix** [comment]
Anti-Adblock Script

Now uses WordPress plugin deAdblocker.
Can be closed this time.

**Comment by theinstantmatrix** [comment]
Anti-Adblock Script

**Comment by theinstantmatrix** [comment]
mdpDeBlocker removed from FJPM and added into the following domains:
```
usnovels.biz
starviet.site
tapchipi.com
```
Follow download link on `https://freejpmusic.net/album-%e7%a6%8d%e3%81%a4%e3%83%b4%e3%82%a1%e3%83%bc%e3%83%ab%e3%83%8f%e3%82%a4%e3%83%88-%e3%82%aa%e3%83%aa%e3%82%b8%e3%83%8a%e3%83%ab-%e3%82%b5%e3%82%a6%e3%83%b3%e3%83%89%e3%83%88%e3%83%a9%e3%83%83-3/`

**Comment by mapx-** [comment]
if still getting anti adb provide exact link where you can see it
