### ISSUE TITLE
Delayed click ads on vidgg.to

### ISSUE THREAD

**Issue by xH4wK** [uBlockOrigin/uAssets#678]
### URL(s) where the issue occurs

`[http://www.vidgg.to/video/223a193385bc9]`

### Describe the issue

This site somehow adds an infinite amount of click ads after certain amount of time..
eg. at first there is just one click/popup ad which goes away and you can click play, but if you pause video or simply watch it and after some time passes there is more and more ads that add up indefinitely so after some time you simply never click on the video controls again you will keep clicking on ads.

### Versions

- Browser/version: [Version 60.0.3112.113 (Official Build) (64-bit)]
- uBlock Origin version: [v1.14.8]

### Settings

- [None in settings, activated some additional filters]

**Comment by gorhill** [comment]
How about

    ||vidgg.to^$inline-script

?

**Comment by xH4wK** [comment]
Seems to be working, no more ads so far, thanks !
