### ISSUE TITLE
new  ads in 1tamilmv.com

### ISSUE THREAD

**Issue by swathigrate** [uBlockOrigin/uAssets#6780]
`https://www.1tamilmv.com`

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

opening new page ads  
### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: firefox 71
- uBlock Origin version:  v1.24.2

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by swathigrate** [comment]
Still ads r  appearing ... 
Please solve this

**Comment by okiehsch** [comment]
The site changed it's TLD from `.com` to `.net`.
`1tamilmv.*##+js(acis, Math, zfgloaded)`
works for me.

**Comment by swathigrate** [comment]
1tamilmv.*##+js(nowebrtc.js)
1tamilmv.*##+js(abort-current-inline-script.js, atob, decodeURIComponent)
||1tamilmv.*/sw.js$script,xhr,1p
Already i added thus. But not working

**Comment by okiehsch** [comment]
Do you still see ads after updating the `uBO-filters` list?
![image](https://user-images.githubusercontent.com/16838044/72040726-b245c480-32a9-11ea-92b1-d573b2856bd0.png)
