### ISSUE TITLE
latimes.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6782]
```
latimes.com##html[data-dss-meterup], html[data-dss-meterup] > body:style(overflow: visible !important;)
latimes.com##+js(aeld, scroll, event.dispatch)
```

Paywall after opening few articles https://github.com/uBlockOrigin/uAssets/issues/4175

**Comment by mapx-** [comment]
I get no such issue. However, even getting a paywall => it's not something uBo is addressing.

**Comment by krystian3w** [comment]
> I get no such issue
 
locked scrolling on site with CSS and JS (need try open 2-3 articles).

**Comment by llacb47** [comment]
@krystian3w no need cosmetic, add `latimes.com##+js(aopr, trb.data.user)`

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/60ff8b94a7661706d912088fe9844e5f4facfeca

**Comment by llacb47** [comment]
Anti-adblock on latimes.com, google funding choices crap @okiehsch 

`https://www.latimes.com/california/story/2020-01-28/deputies-patrol-kobe-bryant-crash-site-trespassers-face-arrest`


![image](https://user-images.githubusercontent.com/16567977/73319324-09d0b380-420a-11ea-85f9-7962c79c2c91.png)

**Comment by okiehsch** [comment]
I can't reproduce. TRied with  US and EU IP.

Is the usual `##+js(nostif, removeChild, 100)` working on your end?

**Comment by llacb47** [comment]
Strange, now I can't reproduce and the requests aren't even being made, nor is there any trace of it in the code. Maybe an A/B test or something-- I'm going nuts

**Comment by okiehsch** [comment]
Your not the only one with that issue when it comes to google contributor, see https://github.com/uBlockOrigin/uAssets/commit/08958cacab69ae2682248dee8c6df063b6a707a7#commitcomment-36972730
