### ISSUE TITLE
cheatsquad.gg

### ISSUE THREAD

**Issue by Janmm14** [uBlockOrigin/uAssets#6783]
Add
https://github.com/easylist/easylist/issues/3662#issuecomment-570925585

**Comment by krystian3w** [comment]
IMO your html filtering will be better:

https://github.com/easylist/easylist/issues/3662#issuecomment-570925585

**Comment by THEtomaso** [comment]
That fix doesn't work for me, neither for Pale Moon, nor Chromium.
This one works though!:
https://github.com/AdguardTeam/AdguardFilters/issues/47143#issuecomment-570925589

**Comment by krystian3w** [comment]
PaleMoon no support syntax: `##^` and `:min-text-length(6000)` so can does not work.

**Comment by THEtomaso** [comment]
As I mentioned; it doesn't work for me with Chromium either.

**Comment by krystian3w** [comment]
Chromium need scriplet, imo newer support "html filtering" syntax `##script:contains`.

**Comment by THEtomaso** [comment]
> Chromium need scriplet

So, you fix is for Google Chrome only?
If so, that's a good reason why Janmm14's fix should be used instead!

**Comment by krystian3w** [comment]
uAssets rarely does it add emergency `css` or `html filtering` as you don't see any "race condition" problems.
