### ISSUE TITLE
Rendering of website in Chrome/Edge is incorrect when uBlock Origin is enabled  - https://www.dcu.org/chat-session.html

### ISSUE THREAD

**Issue by mpurohit7** [uBlockOrigin/uAssets#6784]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ * ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [* ] uBlock Origin is the only extension
    - [* ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [* ] I am running the latest version of uBlock Origin
- [* ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
See attached screenshot
### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]
https://www.dcu.org/chat-session.html
### Steps to Reproduce

1. [First Step] Install and Enable uBlock origin
2. [Second Step] Navigate to https://www.dcu.org/chat-session.html
3. [and so on...] Expected rendering to work (as shown in expected image)
The issue repros on Edge Beta as well
### Expected behavior:

[What you expected to happen]
![image](https://user-images.githubusercontent.com/17639312/71814169-a091d080-30a1-11ea-9e87-38f84cb08d57.png)

### Actual behavior:

[What actually happened]
![image](https://user-images.githubusercontent.com/17639312/71814137-8ce66a00-30a1-11ea-9989-e8b94c055ffe.png)

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version:  
1. Google Chrome is up to date Version 79.0.3945.88 (Official Build) (64-bit)
2. Microsoft Edge Version 79.0.309.58 (Official build) beta (64-bit) (https://www.microsoftedgeinsider.com/en-us/download/)
* Operating System and version: Windows 10

**Comment by mapx-** [comment]
@ryanbr

**Comment by ghajini** [comment]
@ryanbr
