### ISSUE TITLE
On proprofs.com, there is a bar that says "You are seeing this message because ad or script blocking software is interfering with this page." at the bottom.

### ISSUE THREAD

**Issue by fffelix-jan** [uBlockOrigin/uAssets#6786]
### URL(s) where the issue occurs

`https://www.proprofs.com/quiz-school/story.php?title=single-displacement`

### Describe the issue

On proprofs.com, there is a bar that says "You are seeing this message because ad or script blocking software is interfering with this page." at the bottom.

### Screenshot(s)

![Capture d’écran, le 2020-01-06 à 20 43 06](https://user-images.githubusercontent.com/38475999/71861686-32f79b80-30c5-11ea-924a-dd6136126260.png)

### Versions

- Browser/version: Chrome Version 79.0.3945.88 (Build officiel) (64 bits) Mac
- uBlock Origin version: 1.24.2

### Settings

- Enabled the following lists:

- EasyList China
- EasyList Liste FR
- Anti Adblock Killer

### Notes

N/A

**Comment by llacb47** [comment]
`proprofs.com##+js(acis, atob, googlefc)`
