### ISSUE TITLE
leechall.download { Anti-Adblock }

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6789]
### URL(s) where the issue occurs

`https://leechall.download/go/2AR8BF5P3HUYIN7`

### Describe the issue

Antiadblock 

### Versions

- Browser/version: firefox android 68
- uBlock Origin version: 1.24.2

### Settings

-  uBO's default settings

**Comment by ghajini** [comment]
On your side `get link` button is clickable?
STR=
Go to

 1.`leechall.com`
2.enter any link eg https://rapidgator.net/file/92cf32a47bdea8af131d03558643d574
3.next page iam not getting generated link

**Comment by mapx-** [comment]
test again

**Comment by ghajini** [comment]
Yes working

**Comment by dumbusernameidk** [comment]
`leechall.*##+js(set, isAdsDisplayed, true)` also works. Btw why was the countdown booster removed?

**Comment by okiehsch** [comment]
I don't see any countdown to boost.

**Comment by dumbusernameidk** [comment]
There used to be a `leechall.*##+js(nano-sib) filter but it's gone now.

**Comment by okiehsch** [comment]
What I meant is that I don't see a countdown at leechall that could be boosted by `leechall.*##+js(nano-sib)`..

**Comment by dumbusernameidk** [comment]
The site that uses it is technically just `leechall.download` but here's a link with the actual timer on it `https://leechall.download/file/aHR0cCUzQSUyRiUyRnMwMS5sZWVjaGFsbC5jb20lM0EyMDgyJTJGZCUyRiUzRmZpbGUlM0RjMTdlZmEyNjdl`

**Comment by okiehsch** [comment]
Thanks for the link. I will readd the filter.

**Comment by githubuser615** [comment]
@mapx- They blocking the adblock again.

**Comment by mapx-** [comment]
using the last link above I get  `Error 522` upon clicking `Download now`

**Comment by okiehsch** [comment]
I can't reproduce.
`https://leechall.download/go/NK0HFOXWYURMZ6E`
works on my end.

**Comment by githubuser615** [comment]
@mapx- use this link https://1fichier.com/?et3qqa94lf

**Comment by uBlock-user** [comment]
I can reproduce, the filter I added last should work but is not working today, not sure why as they only changed the height they're checking against which is already covered by the height I set in the filter(500px). Anyways, if you're on dev-build, this will work --

`leechall.*##div[id^="taboola-"]:remove()`

**Comment by uBlock-user** [comment]
@githubuser615 fixed, force update uBlock Filters list after a while.

**Comment by githubuser615** [comment]
@uBlock-user Thanks, I forced update uBlock Filters list, but I still got (Please disable AD BLOCKER to download) message.

**Comment by uBlock-user** [comment]
@githubuser615 force update again, GitHub sometimes serves the old cache, so likely you didn't get the latest filter.

**Comment by githubuser615** [comment]
@uBlock-user Thanks, I force update again, it's works for me.
