### ISSUE TITLE
WetterOnline.de functionalities broken

### ISSUE THREAD

**Issue by franticBIT** [uBlockOrigin/uAssets#679]
### URL(s) where the issue occurs

`http://www.wetteronline.de/wetter/berlin`

### Describe the issue

Some functionalities of the webpage are broken, for example the weather timeline for the day.

### Screenshot(s)

<img width="669" alt="screen shot 2017-09-09 at 09 03 02" src="https://user-images.githubusercontent.com/7360440/30237960-e2e19ada-953d-11e7-9532-7658b730db12.png">
<img width="670" alt="screen shot 2017-09-09 at 09 04 05" src="https://user-images.githubusercontent.com/7360440/30237961-e4acec5c-953d-11e7-9264-4efb4084d728.png">

### Versions

- Browser/version: Google Chrome 60.0.3112.113
- uBlock Origin version: 1.14.8

### Settings

- None

### Notes

I can only say that it is definitely caused by the `uBlock filters` list. I will help where I can, if you have any further question or ideas on how to investigate this.

**Comment by gorhill** [comment]
Works fine here, using default settings + up to date default lists + EasyList Germany.

**Comment by franticBIT** [comment]
Just reinstalled it to check again and you're right. Don't know what went wrong there. Thanks for the quick reply!
