### ISSUE TITLE
Antiadblocks

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6790]
### URL(s) where the issue occurs

`http://superonleech.online/free/`

`http://informaxonline.com/?file=f73919e558`

### Describe the issue
Antiadblock 

### Versions

- Browser/version: firefox android 68
- uBlock Origin version: 1.24.2

### Settings

- uBO's default settings

**Comment by mapx-** [comment]
provide indications on how to reproduce the issues

**Comment by ghajini** [comment]
1.
Here going 
`http://superonleech.online/free/`
security ID is 123456 ,wait for site load, antiadblock appears

2.
I forgot exact STR

**Comment by ghajini** [comment]
` http://superonleech.online/free/`

nonexistent domain
