### ISSUE TITLE
a site works fine with ADP, but not with uBO

### ISSUE THREAD

**Issue by motorar** [uBlockOrigin/uAssets#6794]
### Prerequisites

- 

-  [ yes ] I verified that this is not a filter issue

    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ yes ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ yes  ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ yes  ] uBlock Origin is the only extension
    - [ yes  ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ yes  ] I am running the latest version of uBlock Origin
- [ yes  ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
The ads keep showing at the reported website, but the ads won't appear when I use ABP extension with chrome.
I have checked many time to assure that all subscriptions of uBO and ABP are same.

### A specific URL where the issue occurs

https://www.btbtt.co/

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: 79.0.3945.88（chrome） （64 ）
* Operating System and version: win7 x64

**Comment by mapx-** [comment]
> The ads keep showing at the reported website, but the ads won't appear when I use ABP extension with chrome.

what ads are you still seeing on page ? provide screenshots

**Comment by ghajini** [comment]
Subscribe to language specific filters, easylist china

**Comment by motorar** [comment]
uBO is working all right today with that site. Maybe you have fixed that issue. Thanks.

**Comment by mapx-** [comment]
No issue specifically fixed on uBo / uAssests side. Maybe your filter lists were simply outdated.
