### ISSUE TITLE
coinmarketcap.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#680]
"**_Ads by CoinTraffic_**" on `https://coinmarketcap.com`.

**SS:** https://i.imgur.com/11ucliT.png
**Error URL:** `https://coinmarketcap.com/`

These are the ad domains of CoinTraffic making connections on the site:
```
ctnet2.in
koinser.in
lacerta.space
```
Other ad domain: `lijit.com`

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?f=62&t=38135
