### ISSUE TITLE
zillow.com listings not loading properly with uBlock Experimental Filters Enabled

### ISSUE THREAD

**Issue by theawningbusted** [uBlockOrigin/uAssets#6803]
### URL(s) where the issue occurs
Example listing:
`https://www.zillow.com/homedetails/12336-235th-Pl-NE-Redmond-WA-98053/61186341_zpid/`

Should be repeatable on any other listing on zillow though

### Describe the issue

When `uBlock Filters - Experimental` list is enabled home listings will load and then flash to blank white.

### Screenshot(s)

![zillow](https://user-images.githubusercontent.com/59698578/72080256-75d69080-32ca-11ea-9615-9ab8e3918711.png)

### Versions

- Browser/version: Tested on Firefox 72.0.1 & Chrome Version 79.0.3945.117 (Official Build) (64-bit)
- uBlock Origin version: Latest uBlock dev build

### Settings

- using stock filters/settings/browser **AND subscribe** to uBlock Filters - Experimental

**Comment by mapx-** [comment]
maybe it's time to remove `uBlock Filters - Experimental`  @gorhill  ?!

**Comment by gorhill** [comment]
Yes, it's pointless since there is no mechanism in uBO to report issues specific to a list, so it can't be evaluated.

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/commit/0ae1e9b1fea8c1197ae09afef93b082ea1f8062b

**Comment by theawningbusted** [comment]
Sorry if not following all the way, does this mean experimental filters list should be deleted by users from the `Custom` Filter list section now that you removed from `Built-in` filters and if already subscribed it doesn't remove users subscription?

![experimental](https://user-images.githubusercontent.com/59698578/72084937-6b1ff980-32d2-11ea-911b-ef2801e5b607.png)


and [wiki page](https://github.com/gorhill/uBlock/wiki/Experimental-filters) maybe deleted or updated too?

**Comment by gorhill** [comment]
You do what you want, you can still use it if you want. It just mean it's no longer a supported list and issues with it should no longer be opened here.
