### ISSUE TITLE
camera.aeonax.com

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#6804]
### URL(s) where the issue occurs

`https://camera.aeonax.com/#downloads`

### Describe the issue

[Can't load downloads link if UBO enabled]

### Screenshot(s)

[https://imgur.com/NV1J2Jr]

### Versions

- Browser/version: [Firefox Quantum 72.0.1 x64]
- uBlock Origin version: [1.24.2]

### Settings

- [https://pastebin.com/raw/fN63SaSJ]

### Notes

[I disabled UBO and it works]

**Comment by mapx-** [comment]
If I refresh the page (F5) => all fine on my end
If I bypass the cache (ctrl + F5) => I get the anti adb stuff
