### ISSUE TITLE
nowgoal refuses to load the matches if getad.aspx is blocked

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#6806]
nowgoal refuses to load the matches if getad.aspx is blocked (blocked by AdGuard Base filter & EasyList)

rule that made it load the matches:
`@@||www.nowgoal.com/Control/GetAd.aspx$script,1p`

page:
`http://www.nowgoal.com/?type=all&infoid`

can we have GetAd.aspx blocked and site loading?

thanks

**Comment by uBlock-user** [comment]
Site breaks because of the blockage, unblocking also brings in some ads which can be hidden with

`nowgoal.com##[href^="/ad/"]`
