### ISSUE TITLE
chuppito.fr

### ISSUE THREAD

**Issue by potpot59** [uBlockOrigin/uAssets#6807]
### URL(s) where the issue occurs

`https://chuppito.fr/index.php`

### Describe the issue

1) When the page load, a fullscreen warning appair:

> Notre site Web présente des publicités en ligne à nos visiteurs pour couvrir les coûts d'hébergement.
> 
> Pensez à nous soutenir en désactivant notre site Web dans votre bloqueur d’annonces ou à nous faire un petit don (nous contacter par MP pour vous enlever les publicités)
> 
> La fenêtre se fermera toute seule
> 
> DÉSACTIVEZ VOTRE ADBLOCKER SUR NOTRE WEB POUR PROFITER DU CONTENU SANS INTERRUPTION.

2) When clicking a link, a warning appair:

> Il est nécessaire d’accepter la « Politique des cookies » pour accéder aux différentes pages de ce forum.

### Screenshot(s)

<img width="1602" alt="Capture d’écran 2020-01-10 à 12 08 32" src="https://user-images.githubusercontent.com/11508710/72148852-18157780-33a2-11ea-8f0b-1d9e390ccfe8.png">

<img width="445" alt="Capture d’écran 2020-01-10 à 12 08 07" src="https://user-images.githubusercontent.com/11508710/72148846-15b31d80-33a2-11ea-9f09-62cbc373d326.png">

### Versions

- Browser/version: Google Chrome 79.0.3945.117 (Build officiel) (64 bits)
- uBlock Origin version: uBlock Origin 1.24.2

### Settings

- default settings

**Comment by potpot59** [comment]
Thanks @mapx- 
The anti adblock fix works great, but the (blocking) warning that appair when clicking a link is still present

**Comment by mapx-** [comment]
You mean cookie warning ? I added other filter for it, you mean does not work ? is it blocking ? what way ? do I need an account ?

**Comment by uBlock-user** [comment]
`||chuppito.fr/ext/david63/privacypolicy/styles/all/template/remove_url.js^$script,1p` does that work ?

**Comment by potpot59** [comment]
> You mean cookie warning ? I added other filter for it, you mean does not work ? is it blocking ? what way ? do I need an account ?

Without account you can go there: https://chuppito.fr/app.php/privacypolicy/policy and click on "Index du forum" to reproduce.

I think `chuppito.fr##.cookie-box` is already filtered by an another filter (don't know which, annoyances?) and can be deleted.

> `||chuppito.fr/ext/david63/privacypolicy/styles/all/template/remove_url.js^$script,1p` does that work ?

Yeah it works, thanks :)

**Comment by mapx-** [comment]
if I go to `https://chuppito.fr/app.php/privacypolicy/policy` I get no warning.

the cookie filter from fanboy's annoyances list has been disabled by my generichide filter, that's why is necessary

**Comment by uBlock-user** [comment]
@mapx- it's about the alert -- https://user-images.githubusercontent.com/11508710/72148846-15b31d80-33a2-11ea-9f09-62cbc373d326.png

That will not be stopped with a cosmetic filter.

**Comment by uBlock-user** [comment]
Browse to `https://chuppito.fr/` and then click on `Règles du forum` link and then an alert will appear which will also not allow you navigate to that link.

**Comment by mapx-** [comment]
ah, ok, now I see it
