### ISSUE TITLE
menshealth.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#681]
Anti adb warning is displayed on `http://www.menshealth.com`.

**SS:** https://i.imgur.com/AH18Eh3.png
**Error URL:** `http://www.menshealth.com/guy-wisdom/iphone-7-hack-headphone-jack`

They ask for an email to "unlock" the articles and while entering one does unlock the content this is specifically targeted against adblock users.

_**Note:** Using uBO 1.14.8 on Chrome 61 with the default filters and settings._

**Comment by SMed79** [comment]
```
menshealth.com#@#.OUTBRAIN
@@||www.menshealth.com/Mac/pubads.$script,domain=menshealth.com
```

**Comment by okiehsch** [comment]
I am pretty sure that this filter
````
bicycling.com,menshealth.com,prevention.com,rodale.tv,rodalesorganiclife.com,rodalewellness.com,runnersworld.com,womenshealthmag.com##script:inject(setTimeout-defuser.js, showForm, 100)
````
in `uBO-filters`does not work anymore for any of the listed domains.
````
bicycling.com,menshealth.com,prevention.com,rodale.tv,rodalesorganiclife.com,rodalewellness.com,runnersworld.com,womenshealthmag.com##script:inject(abort-on-property-read.js, adBlockPromise)
````
should fix the issue, it does for `http://www.menshealth.com` on my end but I have no time right now to check all domains for possible breakage.

**Comment by SMed79** [comment]
`rodalewellness.com` ==> i get not anti adblock
`rodale.tv` ==> website offline

**Comment by okiehsch** [comment]
So
````
bicycling.com,menshealth.com,prevention.com,rodalesorganiclife.com,runnersworld.com,womenshealthmag.com##script:inject(abort-on-property-read.js, adBlockPromise)
````
works on your end without any obvious site breakage?

**Comment by uBlock-user** [comment]
Can't reproduce.
