### ISSUE TITLE
realmadryt.pl

### ISSUE THREAD

**Issue by datainvestor** [uBlockOrigin/uAssets#6816]
`https://www.realmadryt.pl/news/93476-niemoralny-final`

### Describe the issue

Any news on this website is hidden behing anti adblock killer. Integrating nano defender does not work

**Comment by krystian3w** [comment]
Try enable:

`POL: Oficjalne polskie filtry przeciwko alertom o Adblocku`

And see problem agian - because I unable reproduce with regional "suplements".
