### ISSUE TITLE
linkedin.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6819]
### URL(s) where the issue occurs

`https://www.linkedin.com`
`https://www.linkedin.com/feed/`
`https://www.linkedin.com/m/logout/`
`https://www.linkedin.com/check/manage-account`

#### Many errors:

`https://www.linkedin.com/feed/`:

![obraz](https://user-images.githubusercontent.com/35370833/72225958-c2042800-358b-11ea-8691-a2477c7640b2.png) |
--- |
When I click in "home" ("🏠") button. |

![obraz](https://user-images.githubusercontent.com/35370833/72226009-5d959880-358c-11ea-9756-67247e8c7ba0.png) |
--- |

`https://www.linkedin.com/check/manage-account`:

![obraz](https://user-images.githubusercontent.com/35370833/72226080-2a073e00-358d-11ea-8367-8850ae201afc.png) |
--- |

Does not work logout page:

`https://www.linkedin.com/m/logout/`

I need manually delete cookies to logout.

### Screenshot(s)

See description

### Versions

- Browser/version: Firefox 72
- uBlock Origin version: uBO 1.24.2

### Settings

- Default

### Notes

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 | \|\|cedexis.net^$3p | -- | `www.linkedin.com` | 3 | beacon | `https://2-01-2c3e-003c.cdx.cedexis.net/` | `aliasURL=https://www.linkedin.com/li/track` |
| +2 | \|\|cedexis.net^$3p | -- | `www.linkedin.com` | 3 | frame | `https://2-01-2c3e-003c.cdx.cedexis.net/` | `aliasURL=https://www.linkedin.com/uas/logout?csrfToken=ajax%3A6402347111377547400&session_redirect=%2Fvoyager%2FloginRedirect.html` |
| +2 | \|\|scorecardresearch.com^ | -- | `www.linkedin.com` | 3 | image | `https://sb.scorecardresearch.com/b?c1=2&c2=6402952&c3=&c4=&c5=&c6=&c15=&ns__t=1578865059527&ns_c=UTF-8&c7=https%3A%2F%2Fwww.linkedin.com%2Fm%2Flogout%2F&c9=` |
| +1 | \|\|cedexis.net^$3p | -- | `www.linkedin.com` | 3 | xhr | `https://2-01-2c3e-003c.cdx.cedexis.net/` | `aliasURL=https://www.linkedin.com/voyager/api/voyagerGlobalAlerts?q=findAlerts` |
| +0 | \|\|cedexis.net^$3p | -- | `www.linkedin.com` | 3 | beacon | `https://2-01-2c3e-003c.cdx.cedexis.net/` | `aliasURL=https://www.linkedin.com/li/track` |

**Comment by krystian3w** [comment]
Logout repair:

```
@@||cedexis.net^$xmlhttprequest,domain=www.linkedin.com
@@||cedexis.net^$ping,domain=www.linkedin.com
@@||cedexis.net^$subdocument,domain=linkedin.com
```

**Comment by llacb47** [comment]
Needs account.

**Comment by krystian3w** [comment]
Yep... 😢

**Comment by mapx-** [comment]
No issues even logged in

**Comment by krystian3w** [comment]
For my is broken form with verify data:

`https://www.linkedin.com/check/manage-account`

Logout function:

`https://www.linkedin.com/m/logout/`

And feed page when try open without hard refresh (`Ctrl+F5`).

---

Logger no show more filters than `EasyPrivacy` / "`Peter Lowe HOSTS adservers`".

**Comment by llacb47** [comment]
Issues only happen if CNAME uncloaking is active.

**Comment by krystian3w** [comment]
DoH affected - I use AdGuard DNS by DoH technology.
