### ISSUE TITLE
spiegel.de, safari

### ISSUE THREAD

**Issue by grgr12** [uBlockOrigin/uAssets#682]
### URL(s) where the issue occurs

`[http://www.spiegel.de]`

### Describe the issue

anti-adblocker popup, on the start-page and in the articles

### Screenshot(s)

![spiegel 2017-09-10 at 11 43 37](https://user-images.githubusercontent.com/25546620/30247924-ac8b6434-961e-11e7-9993-84c4596b4d94.png)

### Versions

- Browser/version: Safari 10.1.2
- uBlock Origin version: 1.13.11b

### Settings

- "Easy List Germany"; "Anti-Adblock-Killer I Reek" active 

### Notes

No such issue with Firefox

**Comment by gorhill** [comment]
Can't reproduce, using `.de` VPN.

**Comment by grgr12** [comment]
Have you tried to navigate a bit through the site? The warning doesn't appear immediately - but rather soon.

**Comment by okiehsch** [comment]
I can reproduce the screenshot with Chrome and Firefox if I disable https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L2013, so the filter
`spiegel.de##script:inject(abort-on-property-write.js, adBlockDetected)` still fixes the issue for
Chrome and Firefox users.

**Comment by gorhill** [comment]
> "Easy List Germany"; "Anti-Adblock-Killer I Reek" active

I was assuming this was in addition to default lists. Is it?

**Comment by grgr12** [comment]
Yes, it is!

**Comment by SMed79** [comment]
@grgr12 Try disabling "Anti-Adblock-Killer I Reek"
or
backup your setting / bookmarks / password and reset safari to default.

**Comment by grgr12** [comment]
@SMed79 No changes after either of the steps.

**Comment by okiehsch** [comment]
Does
`spiegel.de##script:inject(setTimeout-defuser.js, adBlockBlocker.check, 1)`
work for you?

**Comment by grgr12** [comment]
No, unfortunately it doesn't.

**Comment by okiehsch** [comment]
Very weird, that filter also fixes the issue with Chrome, Firefox and Edge on my end.
I do not have access to a macOS device, so I can not even try to reproduce.

**Comment by Hrxn** [comment]
Not really a surprise, I guess, considering the differences between the `el1t/uBlock-Safari` fork and git master. Not fundamentally different, to be clear, and compared to other forks in genera etc., but still enough to cause issues, so this would likely be required to dissect manually..

**Comment by grgr12** [comment]
Disabling cosmetic filtering on spiegel.de or, alternatively, disabling generic cosmetic filters in general ublock-settings seem to do the trick for now (Safari 11.0).

For Safari 10.1.2, either of these two filter strings seemed also to be effective:
www.spiegel.de##.ua-webkit.ua-detected
www.spiegel.de##DIV[class="ua-detected ua-webkit"]

**Comment by okiehsch** [comment]
If adding `@@||spiegel.de^$generichide` fixes your issue, I can add it to uBO-filter, it is already part of
[EasList](https://github.com/easylist/easylist/blob/master/easylist/easylist_specific_block.txt#L5775) but because of https://github.com/gorhill/uBlock/issues/2283 wil not work with uBlock-stable until 1.14.12 has been released.

**Comment by grgr12** [comment]
The fix works for my configuration, so I think adding it to uBO-filter would make sense.

**Comment by voodoomatz** [comment]
I might add that for me (with cosmetic filters generally activated) adding `@@||spiegel.de^$elemhide` fixed the issue. None of the above helped in the first place.
