### ISSUE TITLE
medium blacklisted as website with bad reputation

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6820]
https://github.com/MajkiIT/polish-ads-filter/commit/105b84aeaa12a440540a67fbb843d307a9dc9091#diff-711027ed0794992ae3b8710d874f3df7R4107

Possible why:

https://github.com/PolishFiltersTeam/KAD/issues/971 - fake news publicated by Internet trolls...

**Comment by krystian3w** [comment]
Follow:

https://github.com/MajkiIT/polish-ads-filter/pull/15524 - AdGuard try remove this blockade.

**Comment by mapx-** [comment]
I don't understand your issue. 
Provide steps to reproduce it or close the issue.

**Comment by krystian3w** [comment]
POL filters `Version: 2020011202` banned website by:

`||medium.com^`
