### ISSUE TITLE
clickurls.site

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#6821]
`https://clickurls.site/ezOlAFQ`

> ![obraz](https://user-images.githubusercontent.com/43518394/72226819-8a9a7900-3595-11ea-9a51-c8791c16bf3e.png)

**Comment by llacb47** [comment]
Did this person delete their whole account?

**Comment by okiehsch** [comment]
Yes, "ghost" means that the comment is from a deleted account.

**Comment by uBlock-user** [comment]
Yes, ghost account is the placeholder for deleted accounts.
