### ISSUE TITLE
Confused why addEventListener-defuser.js disabledEvent & preventDefault was removed

### ISSUE THREAD

**Issue by JonasNo** [uBlockOrigin/uAssets#6824]
I am confused and cant find any answer to why this ability was removed.
`##+js(addEventListener-defuser.js, mousedown, preventDefault)`

Many filters still use this and ublock ignores it without notification (I understand why):
`##+js(addEventListener-defuser.js, mousedown, disabledEvent)`
Since the syntax change so often (frustrating) maybe it is time for a filter syntax checker so filter maintainers can keep up with all the syntax changes? Useful if the checker also told us the reason for the change / remove of a feature and recommend alternative method.
Or maybe just a filter syntax change log would be easier? <- I like this one.

**Comment by okiehsch** [comment]
> I am confused and cant find any answer to why this ability was removed.
`##+js(addEventListener-defuser.js, mousedown, preventDefault)`

That filter has not been removed. The syntax was updated in https://github.com/uBlockOrigin/uAssets/commit/a8e57b830ebfa7f5da9a22def87f9e85478dd257
