### ISSUE TITLE
www.reddit.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#6826]
### URL(s) where the issue occurs

https://www.reddit.com/r/uBlockOrigin/

### Describe the issue

Annoyance. When you first visit the page on mobile device, a popup appears. This can be hidden by
`reddit.com##.XPromoPopup`
(AdGuard Annoyances already include it); however, now they has implemented new prevention for scrolling so now a simple style rule alone such as
`www.reddit.com##body:style(overflow-y: scroll !important;) `
doesn't work.

### Screenshot(s)

![reddit](https://user-images.githubusercontent.com/58900598/72315182-3ac2cb80-36d5-11ea-80c0-59ece020759a.png)
(SS was taken on PC for convenience, but is almost identical to actual mobile device.)

### Versions

- Browser/version: Firefox Android 68.4.1
- uBlock Origin version: 1.24.2

### Settings

- Default + uBlock Annoyances => popup
- Default + OLD AdGuard Annoyances => no popup, but not scrollable

### Notes

It seems they added an event listener to prevent scrolling in
`https://www.redditstatic.com/mweb2x/Mweb.1d4eba339ddf70ef12a3.js`
so I tried something but no success.

**Comment by patrickdrd** [comment]
great! thanks for posting this, 
I think @ameshkov should be notified

**Comment by ameshkov** [comment]
Thanks for the heads up!
https://github.com/AdguardTeam/AdguardFilters/issues/47727

**Comment by Yuki2718** [comment]
Never mind, now I could scroll w/ the style rule by AdGuard Annoyances filter.
Maybe these rules can be added to uBlock Annoyances, but IDK.

**Comment by mapx-** [comment]
@Yuki2718 what filters can be added for uBo ?

**Comment by Yuki2718** [comment]
> 
> 
> @Yuki2718 what filters can be added for uBo ?

`reddit.com##.XPromoPopup`
`reddit.com##body.scroll-disabled:style(overflow: visible!important; position: static!important;)`
since:
1) Similar popups on e.g. mobile.twitter.com, quora.com, etc. are already in the filter.
2) AdGuard Annoyances is not enabled by default.

**Comment by mapx-** [comment]
thanks

**Comment by mrturkeytoe** [comment]
These rules added by this fix now cause the page on firefox to return to the top of the page and lose the scrollbar

**Comment by stephenhawk8054** [comment]
Test in another Firefox profile with only default settings > Enable your external filter lists one by one to see which one causes the issue.

**Comment by mrturkeytoe** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/16676120/7dd19ae4-9292-4ce3-a956-dbaafb052cb9)
This is how it looks without being logged in or having the cookie for having confirmed age.

Gets rid of the popups but retains the blur (scroll bar still missing)
Fanboy's Annoyance List

All three of these get rid of the dialog popups for the QR code and login/age confirm and the blur (scroll bar missing)
AdGuard Annoyances filter
EasyList – Notifications
AdGuard – Mobile App Banners

**Comment by ElhemEnohpi** [comment]
These lines in "uBlock filters - Annoyances" were added in relation to this, but cause an issue with scrolling on the desktop browser:

```
reddit.com##body.scroll-disabled:style(overflow: visible!important; position: static!important;)
reddit.com##body[style$="overflow: hidden;"]:style(overflow: auto !important;)
```
See https://github.com/easylist/easylist/issues/17354 for details.
