### ISSUE TITLE
webcamsdolls.com [NSFW]

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#6828]
### URL(s) where the issue occurs

`http://webcamsdolls.com/index/web-lesbian-bbs-6372afc4fb6a2209.php`

### Describe the issue

[After pressing play the video will be replaced with a picture about adblock. Also you cannot progress through the video timeline (maybe related to the adblock)? + numerous ads and ad placeholders (this site is kinda messy).]

### Versions

- Browser/version: [Chrome v79]
- uBlock Origin version: [1.24.2]

### Settings

- [default]

**Comment by dumbusernameidk** [comment]
@mapx- 
Possible to add the sites serving the ads?
`bxjch.top`
`kpqnj.top`
`mwcvu.com`

**Comment by mapx-** [comment]
already blocked by `RUS: RU AdList`

**Comment by dumbusernameidk** [comment]
Ah I don't use the regional filter lists.
