### ISSUE TITLE
nnm-club.name not removed adv.

### ISSUE THREAD

**Issue by UnclWish** [uBlockOrigin/uAssets#683]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://nnm-club.name`

### Describe the issue

Visual advertising

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Brouser version: Chromium 64-bit last version
- uBlock Origin version: last version

### Settings

- Enabled all ublock filters and anti-ads filters

### Notes

Advertising not removing by ublock.

**Comment by okiehsch** [comment]
Do you have  `RU AdList` enabled?

**Comment by UnclWish** [comment]
Yes, RU Adlist is enabled by deafault and I didn't disabled it.
And yes, when I add yoir string in manual filter list, advertising on the site disappears!
Thank you a lot!

P.S. Maybe this filter must be added to update for all?

**Comment by okiehsch** [comment]
I just wanted to know if it fixes your issue, before I add it to uBO-filter.

**Comment by UnclWish** [comment]
Yes, it works perfect.
And please add the same filter for nnmclub.to site. It's old adress of the nnm-club.name and many people use old adress with proxy because it restricted in Russia.
