### ISSUE TITLE
ads on https://ww.electrek.co

### ISSUE THREAD

**Issue by skialpine** [uBlockOrigin/uAssets#6831]
### URL(s) where the issue occurs

`https://ww.electrek.co/2020/01/15/tesla-director-james-murdoch-attacks-familys-media-over-climate-crisis-denial/`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

I am now seeing adds on `https://ww.electrek.co`  as an example on the following page I see ads to the right of the story

`https://ww.electrek.co/2020/01/15/tesla-director-james-murdoch-attacks-familys-media-over-climate-crisis-denial/`

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Edge Version 79.0.309.65 on Mac
- uBlock Origin version: v1.23.0

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by skialpine** [comment]
Here are some filters that help temporarily that were created by ublock zapping

ww.electrek.co###lttlqj_fix_nkwfrj_\/1049447\/Fzymtw_0
ww.electrek.co###lttlqj_fix_nkwfrj_\/1049447\/Jqjhywjp-300c250-YtuXnijgfwRfns-W_0
ww.electrek.co###aswift_0

**Comment by mapx-** [comment]
I tested in edge, same version, no ads on my end.
Provide a screenshot showing the ads.

go into dashboard, filter lists tab, click `purge all caches` , click `update now`, test again

**Comment by skialpine** [comment]
purge all caches  and  click update now seems to have solved the issue. I had done the update now prior to the initial report but it seems a purge was also required.
