### ISSUE TITLE
Taboola sponsored articles on popsci.com

### ISSUE THREAD

**Issue by nobelharvards** [uBlockOrigin/uAssets#6832]
### URL(s) where the issue occurs

`https://www.popsci.com/install-use-windows-powertoys/`

### Describe the issue

Taboola sponsored articles appear at the bottom of the article. Not specific to that article, can be reproduced on most pages on that site. Only appears when simultaneously subscribed to "AdGuard Annoyances" and "uBlock filters" lists. They do not appear when unsubscribed from both or only subscribed to one of the two.

### Screenshot(s)

<details><summary>Current behaviour</summary>

![image](https://user-images.githubusercontent.com/9457934/67817020-0c831600-fb00-11e9-8c0a-ff3e6d9030b4.png)
</details>

<details><summary>Expected behaviour</summary>

![image](https://user-images.githubusercontent.com/9457934/67817201-b498df00-fb00-11e9-8276-2570b3ae7780.png)
</details>

### Versions

- Browser/version: Brave version 1.2.42, based on Chromium 79.0.3945.117 (64-bit)
- uBlock Origin version: Nano Adblocker v1.0.0.135, based on uBlock Origin Version/1.24.3b5+4

### Settings

- All default settings apart from filter lists
- Filter lists:
  - Nano Defender Integration
  - Nano filters
  - Nano filters - Annoyance
  - Nano filters - Whitelist
  - uBlock filters
  - uBlock filters - Annoyances
  - uBlock filters - Badware risks
  - uBlock filters - Privacy
  - uBlock filters - Resource abuse
  - uBlock filters - Unbreak
  - Adblock Warning Removal List
  - AdGuard Base List
  - EasyList
  - Nano contrib filter – Placeholder buster
  - AdGuard Tracking Protection
  - EasyPrivacy
  - Fanboy's Enhanced Tracking List
  - Malvertising filter list by Disconnect​​​​​
  - Malware Domain List, Malware domains
  - Spam404
  - AdGuard Annoyances
  - Fanboy's Annoyance List
  - Dan Pollock's hosts file
  - hpHosts' Ad and tracking servers
  - NoCoin Filter List
  - Peter Lowe's Ad and tracking server list

<details><summary>Screenshot of filter lists</summary>

![Subscriptions](https://user-images.githubusercontent.com/9457934/67818808-b06fc000-fb06-11e9-8b81-71651367ddb7.png)
</details>

### Notes

[I've already reported this on the AdGuardFilters repository](https://github.com/AdguardTeam/AdguardFilters/issues/43178) and they updated their lists, but the issue still persisted. They claim they cannot reproduce it on their end.

**Comment by llacb47** [comment]
@mapx- can you remove these lines from uBlock filters - causing the issue and not needed anymore?

```
@@||cdn.taboola.com/libtrc/$script,domain=popsci.com
@@||trc.taboola.com/bonnier-popscinew/$script,domain=popsci.com
```
