### ISSUE TITLE
fotor.com 

### ISSUE THREAD

**Issue by NubN** [uBlockOrigin/uAssets#6833]
### URL(s) where the issue occurs

`https://www.fotor.com/create/design/`

### Describe the issue

some way to block 728x90 spaces?

### Screenshot(s)

https://i.imgur.com/MKWmCq5.png

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [v1.24.2]

**Comment by llacb47** [comment]
```
fotor.com##[id^="guanggaos-"]
fotor.com###main:style(right:0!important;bottom:0!important)
```

**Comment by okiehsch** [comment]
`fotor.com###main:style(right:0!important;bottom:0!important)`
That works for you?

`fotor.com##+js(nostif, Bait)`
disables the reinsertion, though I will fix it in annoyances because it's self advertisement as far as I can see.

**Comment by NubN** [comment]
these filters works well, good job.
```
fotor.com##+js(nostif, Bait)
fotor.com##.guanggao_close_group
```

**Comment by R-Ata** [comment]
this issue is back
`https://www.fotor.com/photo-editor-app/editor/text`

I test this filter, but the "spaces" still in the site
`||www.fotor.com/photo-editor-app/assets/img/*adblock.*.jpg$image`
