### ISSUE TITLE
web.de Layout messed up

### ISSUE THREAD

**Issue by thaliel** [uBlockOrigin/uAssets#6834]
### URL(s) where the issue occurs
`https://web.de/`

### Describe the issue

The new site layout is dislocated to the left, so that part of the actual page is missing. This is fixed when I uncheck Ublock filters
### Screenshot(s)

https://i.imgur.com/n4Ej4H7.png

### Versions

- Browser/version: Firefox 72.0.1
- uBlock Origin version: 1.24.2

### Settings

no settings changed, personal filters do not cause this to happen. 

### Notes
Tested deactivating UBO completely, then went through the lists one by one. Thus I found the Ublock filters list is responsible

**Comment by mapx-** [comment]
provide specific link for that page

**Comment by thaliel** [comment]
https://web.de/

**Comment by mapx-** [comment]
I get a different page at that address, it's why I asked for the specific page in your screenshot

**Comment by krystian3w** [comment]
That is homepage.

**Comment by thaliel** [comment]
here you can see it. Maybe thhe page is different for people outside of Germany?
![webde](https://user-images.githubusercontent.com/5956255/72551280-d3537a00-3894-11ea-98dc-14e252fed8a8.png)

**Comment by mapx-** [comment]
on my side:

![image](https://user-images.githubusercontent.com/10303732/72551656-93d95d80-3895-11ea-8d62-9cf345baa96f.png)

**Comment by thaliel** [comment]
that is their old layout, which I cannot get to appear whenever I open the page

**Comment by krystian3w** [comment]
Can you zip cookies for `web.de` by:

https://github.com/ysard/cookie-quick-manager

**Comment by thaliel** [comment]
by zip you mean export?

**Comment by krystian3w** [comment]
Yes if @mapx- unable reproduce new layout with `Hola VPN` "proxy".

**Comment by krystian3w** [comment]
Glitched grid should fix:

> https://www.w3schools.com/css/css_grid.asp

```
web.de##body > #app > .main:style(grid-template-columns: calc(var(--col-count)*var(--teaser-width) + (var(--col-count) - 1)*var(--grid-column-gap) + 2*var(--grid-border)) !important;)
```

**Comment by thaliel** [comment]
well, I was just looking at cookies for this site and thought hey, might as well clear them just to check. And whaddaya know, that already helped

**Comment by krystian3w** [comment]
`https://js.ui-portal.de/homepage/cs/2020/1.30/webde/homepage.css`

```diff
-[data-ad-type="event-flagship"] .main, [data-ad-type="event-sitebar"] .main, [data-ad-type="flagship"] .main, [data-ad-type="sitebar"] .main {
-    grid-template-columns: calc(var(--col-count)*var(--teaser-width) + (var(--col-count) - 1)*var(--grid-column-gap) + 2*var(--grid-border)) minmax(var(--sitebar-width),1fr);
-}
```
```diff
+.main {
+    grid-template-columns: calc(var(--col-count)*var(--teaser-width) + (var(--col-count) - 1)*var(--grid-column-gap) + 2*var(--grid-border));
+}
```

**Comment by krystian3w** [comment]
https://streamable.com/tio67

**Comment by okiehsch** [comment]
@thaliel do you still get this issue after you refresh and if so does the suggested fix by **krystian3w**
````
web.de##body[data-ad-type] > #app > .main:style(grid-template-columns: calc(var(--col-count)*var(--teaser-width) + (var(--col-count) - 1)*var(--grid-column-gap) + 2*var(--grid-border)) !important;)
web.de##+js(ra, data-ad-type, body)
````
work for you?

**Comment by thaliel** [comment]
as I already mentioned, I simply had to clear cookies. Sometimes one id blind for the most obvious solutions XD

**Comment by thaliel** [comment]
> 
> 
> https://streamable.com/tio67

sorry, I do not understand this at all

web.de##body[data-ad-type] > #app > .main:style(grid-template-columns: calc(var(--col-count)*var(--teaser-width) + (var(--col-count) - 1)*var(--grid-column-gap) + 2*var(--grid-border)) !important;)
web.de##+js(ra, data-ad-type, body)

or this, where/how do add this?

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/72593742-0b46d580-3906-11ea-9dc7-054d80902899.png)

**Comment by thaliel** [comment]
thanks, let's see if this does the trick

**Comment by thaliel** [comment]
nah, no change here. I am close to loosung my sanity about this.

**Comment by krystian3w** [comment]
Simplifed CSS:

```
web.de##.main:style(grid-template-columns: calc(var(--col-count)*var(--teaser-width) + (var(--col-count) - 1)*var(--grid-column-gap) + 2*var(--grid-border)) !important;)
```

I removed:

```diff
-body[data-ad-type] > #app >
```

**Comment by thaliel** [comment]
still no change

> 
> 
> Simplifed CSS:
> 
> ```
> web.de##.main:style(grid-template-columns: calc(var(--col-count)*var(--teaser-width) + (var(--col-count) - 1)*var(--grid-column-gap) + 2*var(--grid-border)) !important;)
> ```
> 
> I removed:
> 
> ```diff
> -body[data-ad-type] > #app >
> ```

does not help either

what I would need is this
https://i.imgur.com/dxtD8eO.png

but you cannot save any changes you make here...arrrrrrrrrrrrrrrrrrrrrgh!

**Comment by krystian3w** [comment]
100% width?

`web.de##body > #app > .main:style(display: block !important;)`

**Comment by thaliel** [comment]
> 
> 
> 100% width?
> 
> ```
> web.de##body > #app > .main:style(display: block !important;)
> web.de##.main [data-ac]:empty
> ```

looks good for now, fingers crossed it stays that way

**Comment by krystian3w** [comment]
@okiehsch  this is still needed:

`web.de##+js(set, CustomEvent, noopFunc)` https://github.com/uBlockOrigin/uAssets/issues/6541

after disable also remove effect:

> "The new site layout is dislocated to the left,"

**Comment by okiehsch** [comment]
> this is still needed:
`web.de##+js(set, CustomEvent, noopFunc)`

Yes, it is still needed without it I get pre-roll ads.
I will add 
````
web.de##body > #app > .main:style(display: block !important;)
web.de##.main [data-ac]:empty
````
to the `uBO-filters` list. 

@krystian3w thanks for the help. 👍

**Comment by JobcenterTycoon** [comment]
please remove `web.de##body > #app > .main:style(display: block !important;)` because the site looks messed up with that filter

**Comment by JobcenterTycoon** [comment]
and add `gmx.*##.main [data-ac]:empty` for gmx

**Comment by krystian3w** [comment]
@okiehsch  test proposition by Jobcenter.
