### ISSUE TITLE
www.searchenginejournal.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6835]
`https://www.searchenginejournal.com/google-is-adding-favicons-to-mobile-search-results/309135/`

Pop-ups with locked scrolling:

![obraz](https://user-images.githubusercontent.com/35370833/72550464-1280cb80-3893-11ea-9929-5f7559e8ffd1.png) |
--- |

![obraz](https://user-images.githubusercontent.com/35370833/72550534-3ba15c00-3893-11ea-896e-89052099b168.png) |
--- |

**Comment by mapx-** [comment]
+
`searchenginejournal.com##.avert-text`

@ryanbr
