### ISSUE TITLE
crazyegg.com marketing & login unavailable

### ISSUE THREAD

**Issue by imtall** [uBlockOrigin/uAssets#6838]
### URL(s) where the issue occurs

`www.crazyegg.com`
app.crazyegg.com/login

### Describe the issue

Due to crazyegg.com (accurately) being listed in Peter Lowe's Ad and Tracking List the marketing site and login for Crazy Egg is unavailable. 

A similar product, HotJar, is also listed on Peter Lowe's list, but they have an exception in the `unbreak.txt`:

https://github.com/uBlockOrigin/uAssets/blob/master/filters/unbreak.txt#L308

As a result HotJar's marketing site loads as expected. Can we please get an exception also so that the Crazy Egg marketing site and login work? Thank you!

### Screenshot(s)

<img width="607" alt="www crazyegg com" src="https://user-images.githubusercontent.com/10137906/72652257-d99c3180-393a-11ea-88a6-00f60f188dda.png">
<img width="613" alt="app crazyegg com" src="https://user-images.githubusercontent.com/10137906/72652258-da34c800-393a-11ea-94f4-f0df8abaf7c2.png">

### Versions

- Browser/version: Version 80.0.3987.42 (Official Build) beta
- uBlock Origin version: 1.24.2

### Settings

Default settings, fresh install.

**Comment by mapx-** [comment]
@pgl

**Comment by okiehsch** [comment]
We can simply badfilter it. 
`||crazyegg.com^$third-party`
is part of `EasyPrivacy` and I don't think @pgl should remove his entry altogether, it is a valid filter in that list.

**Comment by imtall** [comment]
As a note, I also concur that crazyegg.com should stay in @pgl list. It fits the criteria he's defined. 

Thank you @okiehsch for the super fast turn-around!

**Comment by pgl** [comment]
Hey guys. Thanks for the ping, @mapx-. I agree with other people, I'm going to keep `crazyegg.com` on the list. For the record, it was added Sun, 04 Mar 2018 19:02:17.

**Comment by krystian3w** [comment]
In hosts try use:

```
18.210.125.76 www.crazyegg.com
35.168.154.113 app.crazyegg.com
```

maybe help for some users with moddifed HOSTS.
