### ISSUE TITLE
1tv.ru detects ublock ads

### ISSUE THREAD

**Issue by UnclWish** [uBlockOrigin/uAssets#684]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.1tv.ru/live`

### Describe the issue

Site video player detects that it's adblock installed and disables HD quality

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Edge last version
- uBlock Origin version: last version

### Settings

- All filters by default + enabled all ublock filters and anti-ad filters.

### Notes

In chromium it's a ublock protector extension available. But for edge it's absent and site detects ublock and disable HD quality for video it translates.

**Comment by mapx-** [comment]
add
```
1tv.ru##.branding
@@||static.1tv.ru/player/config/banner.gif
```

**Comment by UnclWish** [comment]
Good. It works! Thanks!

**Comment by mapx-** [comment]
for russian sites see also:
https://forums.lanik.us/viewtopic.php?f=102&t=22512
