### ISSUE TITLE
wealthh.xyz { Anti-Adblock }

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6840]
### URL(s) where the issue occurs

`https://wealthh.xyz/02a8`

### Describe the issue

Antiadblock + popup ads

### Versions

- Browser/version: firefox android 68 stable
- uBlock Origin version: 1.24.2

### Settings

- uBO's default settings

**Comment by ghajini** [comment]
@mapx- 

Can you add 

`||exe.io/ad-m.js`

For
`https://exe.io/MtNUJH`....
Wealthh.xyz is variation of exe.io

**Comment by ghajini** [comment]
`exe.io/JBrj6`
3rd party exposure

**Comment by ghajini** [comment]
URL=
`http://exe.io/kvZAvfXN`

WHOLE DOMAIN blocked

https://user-images.githubusercontent.com/20338483/96690497-629c3980-13a1-11eb-9117-243a781fa555.png

very very bad filter @ryanbr

**Comment by okiehsch** [comment]
https://github.com/easylist/easylist/commit/a3a6c3b7f7ed6fe5e8396af55a47e1caa760f1c0
