### ISSUE TITLE
EasyList is Broken

### ISSUE THREAD

**Issue by LucianAndries** [uBlockOrigin/uAssets#6842]
Hello.

From 24 hours ago, or more, every EasyList is broken. It blocks Disqus on some websites.
I have done all I could to make the ad blocker extension, to bypass/exclude Disqus from its filter lists, but it just DOES NOT WORK. I don't know why...  :cry:  :cry: 

I want to tell that I am new at working with ad blocks. I'm currently using uBlock Origin btw.

I reported this here, because I see this is where the "EasyList" originates from?

So, like I said, ALL the filter lists that have "EasyList" in the name, are broken. It does not work just by disabling 1 specifically, I have to disable all of them. :|
The lists are:
- EasyList;
- EasyList without element hiding rules;
- Fanboy+Easylist-Merged Ultimate List.

Cleared site cookies, updated lists, nothing. It's not like it loads for a second then goes away, it doesn't want to load at all.
How I figure it out? By disabling each filter, one by one.

Link to one of the websites having the issue:
https://aniwatcher.com/fate-grand-order-zettai-majuu-sensen-babylonia-episode-14

- OS/version: Windows 10 64bit
- Browser/version: Chrome v79.0.3945.130 (Official Build) (64-bit)
- Adblock Extension/version: uBlock Origin v1.24.2

I hope it will get fixed, as I'm one of those that actually like Disqus...

Thank you!

**Comment by mapx-** [comment]
test
`@@||disqus.com^$script,domain=aniwatcher.com`

what other pages ?

**Comment by mapx-** [comment]
Use ONLY EasyList, remove / disable the other 2

**Comment by LucianAndries** [comment]
> test
> `@@||disqus.com^$script,domain=aniwatcher.com`
> 
> what other pages ?

Wow, this really works!!!! Showed up at first refresh! <3

Yeah, I tried only 1 at a time, but it wasn't working unless I disabled all 3. Seems they're all based on the same list...

But now with this it works!
So If I do this to all websites, changing the domain, it should work? Or is this code specific to the site I gave you?

**Comment by mapx-** [comment]
To help other persons just **report here all the broken pages**.

**Comment by mapx-** [comment]
As you can see above I commited a more general filter
`@@||disqus.com/embed.js$script` which should work on all pages using embedded disqus

**Comment by LucianAndries** [comment]
> As you can see above I commited a more general filter
> `@@||disqus.com/embed.js$script` which should work on all pages using embedded disqus

Oh, thank you! You saved my life! :p

Ok, while this fixed Disqus, I think the filters should still be rechecked and updated, coz who knows what other important stuff they might be blocking...

Now I don't know if I should lease this open for others, or just close it?

**Comment by ryanbr** [comment]
Have fixed in EL

**Comment by peace2000** [comment]
> Have fixed in EL

How this is fixed for Easylist if it's fixed for Ubo users only?

**Comment by krystian3w** [comment]
try `@@||disqus.com/embed.js$script,badfilter` to test where is fixed?

I suppose ulgy filter gone from EasyList.
