### ISSUE TITLE
solarmovie.news

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6845]
`https://solarmovie.news/8364-cold-moon-for-free.html`

fake buttons:

![obraz](https://user-images.githubusercontent.com/35370833/72685282-da72c600-3ae8-11ea-98d8-c13492daae49.png) |
--- |

```
||solarmovie.*/templates/Solar/images/button*_.png
solarmovie.*##.fkplayer2
```

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/7f44fb4b33c854059e9ec941d64e0ef1b162a3d9
