### ISSUE TITLE
solarmovie.ink

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6846]
`https://www.solarmovie.ink/film/watch-27567046-Depraved/watching.html`

fake sources in table:

![obraz](https://user-images.githubusercontent.com/35370833/72685335-82888f00-3ae9-11ea-9424-a6f0f257af14.png) |
--- |

`##table.movie_version > tbody > tr:has(> td:has-text(Promo Host))`

And maybe fake buttons:

![obraz](https://user-images.githubusercontent.com/35370833/72685393-f32fab80-3ae9-11ea-85c9-4fbdbc4d3fe6.png) |
--- |

`##.btn3d.btn-successful`

**Comment by ghajini** [comment]
Easylist compatible filters....

**Comment by krystian3w** [comment]
EasyList no cut fake?

**Comment by krystian3w** [comment]
Also Avoid use `-abp-has`.

**Comment by mapx-** [comment]
@ryanbr

**Comment by krystian3w** [comment]
Zero reaction from EasyList / Fanboy Annyance...

**Comment by okiehsch** [comment]
We have existing filters for that site in `uBO-filters`, i.e. extended syntax is needed for the site.

**Comment by ghajini** [comment]
`https://www.solarmovie.design/episodes/the-bridge-3-season-1-episode-1/`
video blocked due to **denyallow** filter
