### ISSUE TITLE
uta-net.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#6848]
### URL(s) where the issue occurs

`https://www.uta-net.com/song/187704/`

### Describe the issue

Copy protection.

### Versions

- Browser/version: Firefox stable
- uBlock Origin version: 1.24.2

### Settings
Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin lists

**Comment by adranger** [comment]
@mapx- There's a 1px image covering the lyrics too.

**Comment by mapx-** [comment]
added

**Comment by Yuki2718** [comment]
The mobile site (sp.uta-net.com) is still copy-protected.

**Comment by mapx-** [comment]
done
