### ISSUE TITLE
[anti-adblock] mobilereset99.com, emui.altervista.org, easy-firmware.com

### ISSUE THREAD

**Issue by weijen6** [uBlockOrigin/uAssets#6850]
```
https://www.mobilereset99.com/flash-file-honor-8a-pro/
https://emui.altervista.org/guide/firmware-upgrade.html
https://easy-firmware.com/index.php?a=login
```

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/bea14fa19c50cd411e89a217291d226e479d9023

**Comment by uBlock-user** [comment]
Not seeing any anti adblock` https://easy-firmware.com/index.php?a=login`

**Comment by mapx-** [comment]
me neither, maybe needing account

**Comment by weijen6** [comment]
sorry, easy-firmware.com needing account

**Comment by mapx-** [comment]
send an account here: `axis.trivia@gmail.com`

**Comment by weijen6** [comment]
![image](https://user-images.githubusercontent.com/32688959/72749358-c61bef80-3bf4-11ea-9703-d43107c5153a.png)

**Comment by llacb47** [comment]
just type anything for username and password to reproduce @mapx-

**Comment by mapx-** [comment]
test
`@@||easy-firmware.com/templates/default/html/en/assets/js/fingerprint2.min.js$script,1p`

**Comment by weijen6** [comment]
it work, I appreciate you.

**Comment by JobcenterTycoon** [comment]
`emui.altervista.org` blocks right click and select
