### ISSUE TITLE
hydrax.net anti adblock

### ISSUE THREAD

**Issue by aldiener58** [uBlockOrigin/uAssets#6851]
I am having new issues with this website. New anti adblock message appear for every [b]Hydrax[/b] link but not any [b]MyCloud[/b] link.

An example is `https://fmovies.to/film/everwood-3.m2m9x/vv0lry7`

I have updated my filters.

Any support would be appreciated.

Thank you.

uBo 1.24.2
Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/143597a9fe1a5b16deb640fa6fc0b98d566ca0a4

**Comment by mapx-** [comment]
@aldiener58 for anti adb stuff please report only here (uAssets), not needing on easylist forum

**Comment by mapx-** [comment]
> but not any MyCloud link.

not very clear: do you mean there are `MyCloud` links too where you get anti adb ? example in this case ?

**Comment by uBlock-user** [comment]
mycloud is fine, no issues there.

**Comment by aldiener58** [comment]
I regret the lack of clarity. No issues on MyCloud links.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/f468d8f41b1b874466fa7b78bf71e894cdde8397

**Comment by ghajini** [comment]
Firefox A.

Antiadblock
![IMG_20200510_185403](https://user-images.githubusercontent.com/20338483/81500477-175d0580-92f0-11ea-8561-da2a20690886.jpg)

Go here `https://www5.watchmovie.movie/series/awoken-episode-0`
Click hamburger menu in player - server hydrax -Antiadblock appears

**Comment by okiehsch** [comment]
Does 
````
hydrax.net##+js(aopr, AaDetector)
hydrax.net##+js(nostif, debugger)
hydrax.net##+js(window.open-defuser, /^/, 1)
@@||hydrax.net^$ghide
````
work?

**Comment by mapx-** [comment]
and 
`*$subdocument,3p,domain=vidcloud9.com,badfilter`

for french users @smed79

**Comment by ghajini** [comment]
Nope

**Comment by okiehsch** [comment]
Works on my end,can't test with Android.

**Comment by mapx-** [comment]
if "nope" mean you still get the red warning => that will appear even disabling uBO
add also:
`watchmovie.movie##.error_external`

to remove that warning

**Comment by okiehsch** [comment]
@ghajini does the fix for the sister site `playhydrax` work on your end?

Example link NSFW:
`https://www5.javmost.com/SSNI-757/`

**Comment by okiehsch** [comment]
> that will appear even disabling uBO

Do you still get it using Chromium or Firefox on a non Android platform?

**Comment by mapx-** [comment]
yes, getting it on FF desktop

**Comment by okiehsch** [comment]
You mean this?
![image](https://user-images.githubusercontent.com/16838044/81501374-53846c00-92d8-11ea-9514-49d1733da3f5.png)

You can play the video?

**Comment by mapx-** [comment]
yes, the red warning thing, and no issue when I play the video

**Comment by mapx-** [comment]
uBO disabled, the red warning still there:

![image](https://user-images.githubusercontent.com/10303732/81501486-e58c7480-92d8-11ea-9da7-51d558788cfd.png)

**Comment by okiehsch** [comment]
Thanks for the clarification, I can reproduce that warning.
I thought you could reproduce the anti adblock warning in **ghajini's** screenshot.

**Comment by ghajini** [comment]
Give me some time pls

**Comment by ghajini** [comment]
This works for me

`hydrax.net##+js(aopr, isClick)`

**Comment by mapx-** [comment]
tested right now in FF - real android => no anti adblocking on my side

**Comment by ghajini** [comment]
It is there in opera too

https://user-images.githubusercontent.com/20338483/81506840-cf9da480-9316-11ea-93f4-88de9f61b8d1.png

**Comment by llacb47** [comment]
Not due to firefox/opera tracking protection?

**Comment by ghajini** [comment]
Google chrome with ubo+ubo extra

https://user-images.githubusercontent.com/20338483/81507173-1ee4d480-9319-11ea-9eaa-f28f2bdf350d.png

Iam on computer now, you can ask any info about debugging this,I try

**Comment by mapx-** [comment]
FF / chrome / opera => all fine for me

**Comment by ghajini** [comment]
Antiadblock from hydrax

firefox stable,ubo stable

 ### Link=
`https://myflixerhd.ru/watch-movie/class-of-83-63566.3445387`

click on hydrax player & click play; after that
![image](https://user-images.githubusercontent.com/20338483/107532282-bb5b4080-6be3-11eb-8e69-017ebdc65660.png)

**Comment by ghajini** [comment]
Antiadblock

**Comment by mapx-** [comment]
for now just .. getting popups 
```
redirect-ads.com#@#+js(no-setInterval-if, over)
redirect-ads.com#@#div#over:remove()
redirect-ads.com#@#+js(no-setTimeout-if, over)
redirect-ads.com#@#+js(window.open-defuser, /^/, 2)
*$popup,3p,domain=redirect-ads.com,badfilter
```
