### ISSUE TITLE
streamz.cc

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6852]
### URL(s) where the issue occurs

`https://streamz.cc/fbTBmNnFxNGpjaGJ0NGJV`

### Describe the issue

Popup ads

### Versions

- Browser/version: Firefox android stable
- uBlock Origin version: 1.24.2

### Settings

- uBO's default settings

### Notes
Tried 
`streamz.cc##+js(acis, Math, zfgloaded)`
Still popup ads are generated on 1st visit

**Comment by mapx-** [comment]
test
```
||streamz.cc/sw.js$1p
streamz.cc##+js(aopr, decodeURI)
```

**Comment by uBlock-user** [comment]
What about `streamz.cc##+js(acis, Math, zfgloaded)` ?

**Comment by ghajini** [comment]
Both said filters work
