### ISSUE TITLE
bearteach.com & www.coreldraw.com issue

### ISSUE THREAD

**Issue by weijen6** [uBlockOrigin/uAssets#6853]
`https://bearteach.com/`
Next and Previous Buttons not work

`https://www.coreldraw.com/en/product/coreldraw/`
BUY NOW Button not work

**Comment by mapx-** [comment]
> Next and Previous Buttons not work

where are those buttons ?

**Comment by weijen6** [comment]
At the bottom
![image](https://user-images.githubusercontent.com/32688959/72752600-93c2c000-3bfd-11ea-956d-18a93705e45f.png)
