### ISSUE TITLE
instagram.com

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#6855]
URL(s) where the issue occurs

`https://streamable.com/bug58`

Describe the issue

instagram does not advance  several days this is happening to me

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 78 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.24.2

Settings

Default

**Comment by yourduskquibbles** [comment]
Unable to reproduce - what filter lists are you subscribed to?

**Comment by KiLL4FuNK** [comment]
![Capturar_2020_01_21_00_05_43_110](https://user-images.githubusercontent.com/36675858/72772093-d70f3580-3be1-11ea-8c4a-d6407ab2b817.png)

**Comment by yourduskquibbles** [comment]
Still unable to reproduce with exact same filter set, do you have other extensions installed or have ` dynamic filtering rules` under `Mis reglas` aka `My rules`?

**Comment by KiLL4FuNK** [comment]
it's not ublock origin 
I deactivated it and the problem continues
