### ISSUE TITLE
Washington Post is making me pay (but not in Incognito)

### ISSUE THREAD

**Issue by fffelix-jan** [uBlockOrigin/uAssets#6856]
### URL(s) where the issue occurs

`https://www.washingtonpost.com/lifestyle/home/bleach-isnt-so-scary--if-you-know-how-to-use-it-correctly/2019/01/07/decb5514-0470-11e9-b5df-5d3874f1ac36_story.html`

### Describe the issue

![Capture d’écran, le 2020-01-20 à 22 26 44](https://user-images.githubusercontent.com/38475999/72773094-09b23180-3bd4-11ea-9368-d118a4ab8052.png)

### Versions

- Browser/version: Chrome Mac Version 79.0.3945.117 (Build officiel) (64 bits)

- uBlock Origin version: 1.24.2

### Settings

- Added the following filter lists: Easylist FR, Easylist 中文, Anti Adblock Killer

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/blob/master/README.md

Circumventing a paywall is considered [out of scope](https://github.com/uBlockOrigin/uAssets/issues/2317#issuecomment-392009540)

**Comment by NubN** [comment]
Now in most online-media, there are these types of payment walls, where there is only a small part of the article. and you need pay, to read it whole. I think if the adblockers didn't exist. this type of payment walls would not exist either.

The question is, and just out of curiosity, a content blocker, could you make an article appear completely, for example?. or I'm already delirious. Just to know if it would be possible.

sorry for bad english, and my ignorance.

cheers.

**Comment by uBlock-user** [comment]
>  could you make an article appear completely, for example?. or I'm already delirious. Just to know if it would be possible.

https://www.reddit.com/r/uBlockOrigin/comments/e3qd06/washington_post_at_it_again_changed_their_nagwall/f9pfdev/
