### ISSUE TITLE
nyafilmer.lol Anti Adblock

### ISSUE THREAD

**Issue by Morku** [uBlockOrigin/uAssets#6868]
### URL(s) where the issue occurs

`[https://nyafilmer.lol/solan-og-ludvig-jul-i-flaklypa/]`

### Describe the issue

[With uBlock Origin 1.42.2 and enabled "uBlock filters", you get a popup about an active Adblocker, preventing you from browsding the page. When you uncheck "uBlock filters" and reload, the page loads fine.]

### Screenshot(s)

[https://user-images.githubusercontent.com/6276915/73004863-51b99a00-3e08-11ea-8db0-28bccc64225b.png]

### Versions

- Browser/version: [Firefox 72.0.2]
- uBlock Origin version: [1.42.2]

### Settings

- [Default settings.]

### Notes

[I disabled any other filterlist to make sure, the issue is in "uBlock filters". Of course the Popup also appear when you go for EasyList only, but as I know, uBlock filters is going to prevent Anti Adblock. The issue also occur when no EasyList is active and only uBlock filters is checked. The issue also occur when you go for EasyList and uBlock filters.]

**Comment by JobcenterTycoon** [comment]
I get a blank screen

**Comment by uBlock-user** [comment]
> I get a blank screen

Where ?
