### ISSUE TITLE
winhelponline.com anti adb

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#6870]
[Description of the bug or feature]

winhelponline.com detects ublock origin and gives a popup window asking to turn it off before it lets you use the site.

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

winhelponline.com

### Steps to Reproduce

1. [First Step]

Connect to internet.

2. [Second Step]

Open browser.

3. [and so on...]

Go to winhelponline.com.

### Expected behavior:

[What you expected to happen]

The website should load and work normally (as it does when ublock origin in disabled).

### Actual behavior:

[What actually happened]

winhelponline.com detects ublock origin and gives a popup window asking to turn it off before it lets you use the site.

### Your environment

* uBlock Origin version: 1.24.2
* Browser Name and version: Firefox 72.0.2 (64-bit)
* Operating System and version: Windows 10 Pro

![winhelponline com](https://user-images.githubusercontent.com/35790889/73013226-e9f25780-3de5-11ea-9772-d7d68d1c9a65.jpg)

**Comment by mapx-** [comment]
enable `uBlock filters – Annoyances` list, already fixed
