### ISSUE TITLE
eurosport embedded video unwatchable

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#6871]
`https://www.tennis24.gr/o-kyrgios-chlevazei-ti-routina-tou-nadal-sto-servis-video/`

there's a video which I cannot figure how to display,
I found its url from the source somehow and it played,
but embedding seems impossible to make work,
at least for me/my settings etc,

could sb help?

thanks in advance

**Comment by patrickdrd** [comment]
great but there was one more thing:

I'm blocking third party cookies, but this one needs an exception to allow cookies for:
video.eurosport.com in order to work

**Comment by okiehsch** [comment]
> I'm blocking third party cookies

How? Do you have a list enabled or are you blocking them in your browser settings?

**Comment by patrickdrd** [comment]
in browser settings ;)

**Comment by okiehsch** [comment]
Then I would suggest that you allow third-party cookies for this site. ;)

**Comment by patrickdrd** [comment]
yes, I did, already added
