### ISSUE TITLE
https://www.wcoanimedub.tv/dubbed-anime-list Has anti-adblock that can detect uBlock Origin.

### ISSUE THREAD

**Issue by Demonlord90** [uBlockOrigin/uAssets#6873]
### URL(s) where the issue occurs

`[https://www.wcoanimedub.tv/dubbed-anime-list]`

### Describe the issue

Click on any video link on this website and it'll bring up a video that's blocked by a big red anti-adblock notification that wants you to make an account and subscribe to their payment plans. This started within the last week. It prevents you from watching any videos unless you subscribe to their stuff.

### Screenshot(s)
![Anti-adblock issues](https://user-images.githubusercontent.com/60244263/73035757-63ef0480-3e17-11ea-89f2-0552c99ec673.jpg)

### Versions

- Browser/version: Mozilla Firefox version 72.0.2 (64-bit)
- uBlock Origin version: Version 1.24.2

### Settings

- 
![image](https://user-images.githubusercontent.com/60244263/73035938-e4156a00-3e17-11ea-8625-94bbc06a5521.png)

### Notes

I've tried using the website with both the Adblock Warning Removal and AakList (Anti-Adblock Killer) lists but neither seems to help. The website is still able to detect uBlock Origin and display the anti-adblock thing that blocks you from watching any videos on the website. I've also tried using both uBlock Origin and Nano Defender together with no results.

**Comment by okiehsch** [comment]
Update your `uBO-fiters` list. It was fixed earlier today.
https://github.com/uBlockOrigin/uAssets/commit/e57d176172d654ac309f570b6237c0ff2584e6cc
