### ISSUE TITLE
remove obsolete filters

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#6876]
### Describe the issue

No issue, just suggesting to remove these as they are already addressed by EL/EP:
`@@||jra.webcdn.stream.ne.jp/web/*/referrer.js$script,1p`

`*$3p,image,domain=rd.com,badfilter`
`*$3p,xmlhttprequest,domain=rd.com,badfilter`

`@@||imasdk.googleapis.com/js/sdkloader/*$script,domain=bloomberg.co.jp`

### Notes

Is pull request better for this? But then I need to create my repository...

**Comment by mapx-** [comment]
still there
`$image,third-party,xmlhttprequest,domain=rd.com`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/5e672e23f3aba01e9a2ac44bf1d50c7712b4fa3f

**Comment by Yuki2718** [comment]
> 
> 
> still there
> `$image,third-party,xmlhttprequest,domain=rd.com`

At least an original issue I reported seems to be addressed.
https://forums.lanik.us/viewtopic.php?f=64&t=44087
Not sure if there's other problem by that aggressive filter.
