### ISSUE TITLE
www.theregister.co.uk

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#6877]
`https://www.theregister.co.uk/`

### Describe the issue

Annoyance, uBO syntax is not required but a high-traffic site. A banner asking to disable ad-blocker.

### Screenshot(s)

![theregister](https://user-images.githubusercontent.com/58900598/73085046-69c91080-3f11-11ea-9816-c62abe3f149f.png)

### Versions

- Browser/version: Firefox 72.0.2
- uBlock Origin version: 1.24.2

### Settings

- Default

### Notes

Already reported to AdGuard by someone: https://github.com/AdguardTeam/AdguardFilters/issues/47491
On my end this seems to be enough:
`||s3-us-west-2.amazonaws.com/js/adtoniq-www-theregister-co-uk.js`

**Comment by llacb47** [comment]
Maybe only in annoyances list, or not at all @mapx-

**Comment by uBlock-user** [comment]
Can't reproduce it.

**Comment by mapx-** [comment]
getting the annoyance with US IP
