### ISSUE TITLE
ebay.co.uk gdpr banner

### ISSUE THREAD

**Issue by ayumi-cloud** [uBlockOrigin/uAssets#6878]
### URL(s) where the issue occurs

Example link: `https://www.ebay.co.uk/`

### Describe the issue

uBlock completely doesn't work on this website and when you right click the mouse button and try to open the uBlock extension nothing happens.

Trying to block ebay gdpr banner

It has the following tags `id="gdpr-banner"` and `class="gdpr-banner--slideup"`

I have tried adding the following manually and doesn't do anything:

```
ebay.co.uk###gdpr-banner
ebay.co.uk##gdpr-banner
ebay.co.uk##.gdpr-banner
ebay.co.uk##.gdpr-banner--slideup
```

### Screenshot(s)

![image](https://user-images.githubusercontent.com/57409060/73088772-c6560c80-3ecc-11ea-80df-6ac75feeb314.png)

### Versions

- Browser/version: Google Chrome Version 81.0.4036.0
- uBlock Origin version: uBlock Origin v1.24.2

### Settings

```
ebay.co.uk###gdpr-banner
ebay.co.uk##gdpr-banner
ebay.co.uk##.gdpr-banner
ebay.co.uk##.gdpr-banner--slideup
```

Plus screenshot:

![image](https://user-images.githubusercontent.com/57409060/73088908-17660080-3ecd-11ea-915d-96075247156c.png)

### Notes

uBlock completely doesn't work on the whole ebay.co.uk website currently.

**Comment by mapx-** [comment]
- the gdpr stuff is already fixed by `AdGuard Annoyances`
- right click working fine on my end
- if still in trouble backup your settings, remove ebay custom filters (if any), reset uBO to default settings and test again
- you should enable the specific uBO list for annoyances `uBlock filters – Annoyances`

**Comment by ayumi-cloud** [comment]
@mapx- 

Thank you, confirmed turning on `uBlock filters – Annoyances` fixes the issue. 👍
