### ISSUE TITLE
[Breakage] ....intel.com

### ISSUE THREAD

**Issue by b00sher** [uBlockOrigin/uAssets#6879]
### URL(s) where the issue occurs

https://plan.seek.intel.com/PSG_WW_NC_LPCD_FR_2018_FPGAforDummiesbook

### Describe the issue

Blocks some external style-sheets, displays properly with uBO disabled, no cosmetic filters applied.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/54773665/73100776-52812780-3eff-11ea-95ce-5a747cafe02f.png)

### Versions

- Browser/version: Firefox 72 
- uBlock Origin version: v1.24.2

**Comment by gwarser** [comment]
>Filter||en25.com^
>Filter listPeter Lowe’s Ad and tracking server list
