### ISSUE TITLE
spaste.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#688]
Text ads above the content on `http://www.spaste.com`.

**SS:** https://i.imgur.com/nepfwXL.png
**Error URL:** `http://www.spaste.com/p/?c=eSmGUA4587`

Can be blocked by: `||plufdsa.com^`

_**Note:** Using uBO 1.14.8 on Chrome 61 with the default filters and settings._

**Comment by gotitbro** [comment]
@okiehsch Again seeing text ads on `http://www.spaste.com`.

**Example URL:** `http://www.spaste.com/p/?c=c0VNv29506`

**Comment by gotitbro** [comment]
@okiehsch Seeing the ads again.

**Error URL:** `http://www.spaste.com/p/?c=c0VNv29506`

**Comment by okiehsch** [comment]
`spaste.com###template-contactform-message`
that could hide some functionality at `spaste.com`, I am not sure.
