### ISSUE TITLE
enrt.eu

### ISSUE THREAD

**Issue by lyndmi** [uBlockOrigin/uAssets#6884]
### URL(s) where the issue occurs

`https://enrt.eu/Modmenu1`

### Describe the issue

Countdown

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24647715/73127549-3e522e80-3fc2-11ea-8a7c-361878a202d9.png)

### Versions

- Browser/version: Opera v66.0.3515.44
- uBlock Origin version: 1.23.0

### Settings

- Default

### Notes

Countdown booster if possible

**Comment by mapx-** [comment]
It's managed server side

![image](https://user-images.githubusercontent.com/10303732/73127600-08fa1080-3fc3-11ea-99e2-2df790155f41.png)

**Comment by lyndmi** [comment]
Ok thanks for trying
