### ISSUE TITLE
Bing.com Ads

### ISSUE THREAD

**Issue by prateekrastogi** [uBlockOrigin/uAssets#6886]
Referencing a closed issue as that issue is still not fixed, and has been closed prematurely:
https://github.com/uBlockOrigin/uAssets/issues/5724

**Comment by mapx-** [comment]
test
`bing.com##+js(set, Blob, noopFunc)`

https://www.reddit.com/r/uBlockOrigin/comments/etcj8a/bing_script_targets_adblockers_whats_the_solution/fffvc04/?context=1

**Comment by llacb47** [comment]
> test (if does not break some functionality)

That filter is only for when the ads are being inserted as images, as in https://github.com/NanoAdblocker/NanoFilters/issues/439.

**Comment by prateekrastogi** [comment]
No, the ads or search results are not being inserted in as images in original from server side(It will debilitate search results page performance). It's after the results have been fetched that Bing is converting them to image on canvas. Here's my temporary fix i.e. ublock origin filter that has been working great for me for past 24 hours:
bing.com##^#b_results > .b_ad

**Comment by mapx-** [comment]
@prateekrastogi I asked you to test that filter: does work for you ?

**Comment by prateekrastogi** [comment]
@mapx Would that be the fix?

**Comment by llacb47** [comment]
After seeing this reddit post (`https://old.reddit.com/ggd1ko/`) I discovered that bing ads are getting through again. Testing on uBo defaults, Chrome 81.0.4044.138, Windows 10.
![image](https://user-images.githubusercontent.com/16567977/81503535-14432480-92b2-11ea-8f7f-0e060220b6d1.png)
Test URL: `https://www.bing.com/search?q=lose+weight+fast`
Fix: `bing.com##+js(set, AdMon.getBlockedAdElementsV2, noopFunc)`


For future reference: 
Bing is putting their anti-adblock code inside of a `<div>` (?)
![image](https://user-images.githubusercontent.com/16567977/81503599-756af800-92b2-11ea-9a1f-a10bb5397e8e.png)
Here is the code: `https://pastebin.com/eQuP8gCU`

@mapx-

**Comment by mapx-** [comment]
tested on various ip (european / us) .. but I cannot reproduce the ads, let's see others

**Comment by llacb47** [comment]
Maybe it is an A/B test... if you evaluate `AdBTrack` and `AdMon` in the console are they undefined for you?

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/81504564-55572b00-92ea-11ea-82c3-04e2e0698ab2.png)

**Comment by mapx-** [comment]
You mean replacing 
```
bing.com##+js(set, Blob, noopFunc)
bing.com##+js(set, AdBlockerTracking.AdBlockMonitor, noopFunc)
```
by `bing.com##+js(aopr, AdMon)`  ?

if it's working for you just push a PR

**Comment by llacb47** [comment]
I'll make a PR but not replacing the existing rules.
