### ISSUE TITLE
Bing Ads

### ISSUE THREAD

**Issue by prateekrastogi** [uBlockOrigin/uAssets#6887]
Referencing older issues. Since there has been no efforts at global fixing this persistent bug despite multiple opened issues:
https://github.com/uBlockOrigin/uAssets/issues/6886#event-2979951730

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a9acc48148c0febc27d151b4ab1499c77f0f98c0

**Comment by uBlock-user** [comment]
force update your filters

**Comment by grahamperrin** [comment]
Can we take action against @prateekrastogi for off-topic spamming?

**Comment by uBlock-user** [comment]
@grahamperrin Reported to Github for spamming and to @gorhill in team discussions.
