### ISSUE TITLE
short.am – Please disable Adblock

### ISSUE THREAD

**Issue by pepablock** [uBlockOrigin/uAssets#689]
### URL(s) where the issue occurs

**LINK** **–** `short.am/bKKEeR`

### Describe the issue

Please disable Adblock notification.

### Screenshot(s)

–

### Versions

- Browser/version: **Firefox 55.0.3 (64-bit)**
- uBlock Origin version: **1.14.4**

### Settings

Default

### Notes

–

**Comment by mapx-** [comment]
add
`@@||short.am/*ad$script`
