### ISSUE TITLE
snapito.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6893]
`https://snapito.com/`

Adblock detected:

![obraz](https://user-images.githubusercontent.com/35370833/73219843-53af9000-415d-11ea-8f75-49a0355bd351.png)

`###no-ads-banner`

**Comment by krystian3w** [comment]
![obraz](https://user-images.githubusercontent.com/35370833/73220064-dafd0380-415d-11ea-8cd3-15bf0b6f3db0.png)

**Comment by okiehsch** [comment]
Fixed in annoyances.
