### ISSUE TITLE
finance.yahoo.com on mobile

### ISSUE THREAD

**Issue by shuhaowu** [uBlockOrigin/uAssets#6896]
### URL(s) where the issue occurs

- `https://finance.yahoo.com` (mobile site)

### Describe the issue

Ad on the top of the page.

Blocked by the filter: 

```
finance.yahoo.com##.ys-mobileFeaturedAd
```

### Versions

- Browser/version: Firefox 68.4.2 Mobile Android
- uBlock Origin version: uBlock 1.24.2

### Settings

- None

**Comment by mapx-** [comment]
@Alex-302 @ryanbr
