### ISSUE TITLE
industiiz.com { Anti-Adblock }

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#6898]
### URL(s) where the issue occurs

`https://industiiz.com/ST9aaOT`

### Describe the issue

Antiadblock 

### Versions

- Browser/version: firefox android stable
- uBlock Origin version: 1.24.2

### Settings

-  uBO's default settings

**Comment by ghajini** [comment]
Add also
`||industiiz.com/ad-m.js$1p`

**Comment by okiehsch** [comment]
I don't see that request on my end, but blocing it can't hurt.

**Comment by ghajini** [comment]
On 
Firefox android/firefox desktop browser
