### ISSUE TITLE
dpstream.net

### ISSUE THREAD

**Issue by SMed79** [uBlockOrigin/uAssets#69]
Hi, 
popunder on `http://www.dpstream.net/`

`||dpstream.net^$popunder`

Thanks.

**Comment by gorhill** [comment]
I did get a popunder, but the destination was `http://ads.affiliation-france.com/dppl/[...]`, not `dpstream.net`, and it was properly closed by the filter `://ads.$popup` in EasyList.

What you are suggesting will prevent the site from opening links to itself.

**Comment by SMed79** [comment]
:see_no_evil: issue come from corrupted profile, sorry.

Thanks for your time.
