### ISSUE TITLE
prosieben.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#6905]
### URL(s) where the issue occurs

`https://www.prosieben.de/tv/germanys-next-topmodel/video/151-pailletten-posen-kleine-pannen-so-meistern-die-models-ihre-erste-fashion-show-clip`

### Describe the issue

Anti Adblock

### Screenshot(s)

![pic457456](https://user-images.githubusercontent.com/48647394/73574293-a64abe00-4475-11ea-8419-c6d9885fc6ee.PNG)

### Versions

- Browser/version: Firefox 72.0.2
- uBlock Origin version:  v1.24.2

### Settings

default

**Comment by mapx-** [comment]
test
`@@||zomap.de/$xhr,domain=prosieben.de`

**Comment by mapx-** [comment]
Could you test in chrome too ?

**Comment by JobcenterTycoon** [comment]
> test
@@||zomap.de/$xhr,domain=prosieben.de

it works

> Could you test in chrome too (without the filter above) ?

Sorry no because i am use a another computer
