### ISSUE TITLE
https://ehubsoft.herokuapp.com/chmviewer/ (an online .CHM/.HLP viewer) asks me to disable ad blocking to use the website.

### ISSUE THREAD

**Issue by fffelix-jan** [uBlockOrigin/uAssets#6907]
### URL(s) where the issue occurs

`https://ehubsoft.herokuapp.com/chmviewer/`

### Describe the issue

It asks me to disable adblock to use the website.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/38475999/73594338-9665c500-44db-11ea-8d50-30c9255a9368.png)

### Versions

- Browser/version: Chrome 79.0.3945.130 (Build officiel) (64 bits)
- uBlock Origin version: 1.24.2

### Settings

- added the following filters: EasyList FR, 中文, and Anti Adblock Killer (tried disabling them but it didn't work either)

**Comment by mapx-** [comment]
remove completely `Anti Adblock Killer` => causing issues (outdated)
