### ISSUE TITLE
Google search for site:<whatever> shows an ad

### ISSUE THREAD

**Issue by moon-chilled** [uBlockOrigin/uAssets#6909]
If you do a google search for `site:<whatever.com>`, a google sponsored ad pops up.  Consider, for instance, [this](https://www.google.com/search?q=site%3Asdlfjdsfl.com), which looks like [this](https://files.catbox.moe/cd9ajv.png) for me.

Firefox 72/Linux.

**Comment by krystian3w** [comment]
`google.*###topstuff`

**Comment by krystian3w** [comment]
but unable reproduce pop-up.

**Comment by uBlock-user** [comment]
@ryanbr fixed in Enhanced tracking list, but not in `EasyPrivacy/EasyList` ?

**Comment by mapx-** [comment]
Eventually it is self promotion, so not blockable in the official lists
