### ISSUE TITLE
[NSFW] hentai2read.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#691]
Popup ads and banner ads are loaded on https://hentai2read.com.

**Error URL:** https://hentai2read.com/happy_mommy_yuiko/1/

_**Note:** Using uBO 1.14.8 on Chrome 61 with the default filters and settings._

**Comment by mapx-** [comment]
ads
`hentai2read.com##a[href^="//www.nutaku.net/"]`

getting no popup

**Comment by Blutgang** [comment]
Ads:
`||hentaicdn.com/cdn/v2.assets/weekly5/5_*.mp4$domain=hentai2read.com`

Popup/Popunder?
`||script.hentaicdn.com/cdn/v2.assets/js/script.h2r.v2710ki.js$domain=hentai2read.com`

Not sure if those filters will break anything on that site...
