### ISSUE TITLE
yify-movies.to

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#692]
https://yify-movies.to/home

uBlock Origin is a great program for blocking most ads, which is pretty much a necessity on the internet, but when you go to https://yify-movies.to/home and click in the search area on the top right corner of the site, a popup window opens with an ad and stays open, also it seems like some other popup windows try to open in new tabs, but then are closed automatically. Is there a way to fix that? Thanks.

![yify movies ad](https://user-images.githubusercontent.com/26278182/30505582-8a0b736c-9a43-11e7-9743-d22b733123d6.jpg)

Firefox Developer Edition 56.0b12
uBlock Origin 1.14.8

Even using the yify-movies.to * 3p block, and yify-movies.to gstatic.com * block rules, the ads still appear. Until recently, uBlock Origin used to block all popup windows on that site properly.

**Comment by okiehsch** [comment]
Does
````
yify-movies.to##script:inject(addEventListener-defuser.js, /^(click|mousedown|mousemove|touchstart|touchend|touchmove)/, system.popunder)
````
work for you?

**Comment by js017** [comment]
Does "yify-movies.to##script:inject(addEventListener-defuser.js, /^(click|mousedown|mousemove|touchstart|touchend|touchmove)/, system.popunder)" go all on one line in the "my filters" settings? If so, then no it didn't seem to work. Still getting the popup window that stays open, and the other popups that try to open in new tabs, and then close automatically. The popup window says something about rogers, which is the name of my internet service provider, but it doesn't seem to be anything official from them, it looks more like an ad. If there's no way to get rid of the popups on that site then that's fine, but this is a website that I use often enough that I'd like to be able to get rid of the popup windows if possible. Thanks.

**Comment by js017** [comment]
Actually it seems that putting "yify-movies.to##script:inject(addEventListener-defuser.js, /^(click|mousedown|mousemove|touchstart|touchend|touchmove)/, system.popunder)" all on one line in my filters, didn't seem to do anything. Still getting the popup window, which seems to be able to detect that I'm a rogers internet customer, because it mentions rogers, but doesn't look like anything official from them, it just looks like an ad. I use that site often enough that I'd like to be able to get rid of the popup windows if possible. Thanks.

**Comment by okiehsch** [comment]
Adding the filter fixes the popup issue on my end, you can try adding
`||yify-movies.to/js/rx/*.js$script,first-party`

**Comment by okiehsch** [comment]
I can reproduce popup-issues but they are fixed with the proposed filters on my end, so I will add a fix.

**Comment by gwarser** [comment]
New domain `https://yifymovies.to/`

**Comment by js017** [comment]
Using ||yify-movies.to/js/rx/*.js$script,first-party there's still some popups that close automatically, and a popup window that stays open but is blank. Interestingly enough, when I go to yify-movies.to/home (which apparently has now changed back to the yifymovies.to/home domain address) using Pale Moon with uBlock Origin, even without the extra filters, I can click in the search box and there aren't any popups at all. Thanks.
