### ISSUE TITLE
oxy.cloud

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#6921]
### URL(s) where the issue occurs

`https://oxy.cloud/d/moab`

### Describe the issue

It won't download a file unless you disable adblocker. Gets stuck forever

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24647715/73757333-63386580-4769-11ea-80d0-c9eb97a35096.png)

### Versions

- Browser/version: 66.0.3515.44
- uBlock Origin version: 1.23.0

### Settings

- Default

### Notes

Not asking for notification bypass (https://github.com/uBlockOrigin/uAssets/issues/5890)
You must pass it to go to download page

**Comment by mapx-** [comment]
Fake page ? Even disabling uBO still does not work

**Comment by LGLTeam** [comment]
No it's not fake. Sometime it doesn't work but using VPN works
