### ISSUE TITLE
gplinks.co

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#6922]
### URL(s) where the issue occurs

https://gplinks.co/aDFojO0

### Describe the issue

Anti-adblock + countdown

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24647715/73769184-87e90900-477a-11ea-8797-e77746ed34fb.png)

### Versions

- Browser/version: 66.0.3515.44
- uBlock Origin version: 1.23.0

### Settings

- Default

### Notes

None

**Comment by ghajini** [comment]
`https://gplinks.co/8cmwdf`

Stuck at `getting link` in final download page, perhaps CSP filter `||gplinks.co^$csp=style-src *;connect-src` from ublock filters
is breaking ***get link*** button

**Comment by ghajini** [comment]
`gplinks.co/gNIHeu`
Fake continue at end of page
