### ISSUE TITLE
Should cosmetic filtering be removing simple text links?

### ISSUE THREAD

**Issue by bughit** [uBlockOrigin/uAssets#6923]
### URL(s) where the issue occurs

https://github.com/w3ctag/design-reviews/issues/467#issuecomment-581944600

### Describe the issue

The above github comment contains a link to doubleclick.net (to illustrate chrome's x-client-data header), which becomes unclear when the link is removed.

What is the upside of removing text links? I don't want to disable cosmetic filtering entirely, because presumably it removes something like large obnoxious ad sections. But then it should be less aggressive and leave simple text links alone.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]
![image](https://user-images.githubusercontent.com/895588/73772946-295a6580-474f-11ea-978f-c782b02fdeb6.png)

![image](https://user-images.githubusercontent.com/895588/73773010-4d1dab80-474f-11ea-9935-0dc03c9d3e96.png)

### Versions

- Browser/version: Fx 72.0.2
- uBlock Origin version: 1.24.2

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by uBlock-user** [comment]
It's not a `text link`, the link is parsing the url to `https://ad.doubleclick.net/` which is an ad server and get hidden by Easylist's generic filter -- `##a[href^="https://ad.doubleclick.net/"]`

**Comment by mapx-** [comment]
just add
`@@||github.com^$ghide`

**Comment by bughit** [comment]
No doubt it can be worked around, however I am suggesting that cosmetic filtering should be blocking large obnoxious block content. There is not sufficient justification to remove inline text links. The downside is greater than the upside. Why does a user need to be protected from seeing a text link to doubleclick?

**Comment by krystian3w** [comment]
Remove from HTML code?

Only HTML filtering can delete that links (uBo no have scriplet for Chrome) IF website no block this by use rare characters encoding e.g.: `ISO-` / `windows-`.
