### ISSUE TITLE
redecanais.bz [anti-adblock]

### ISSUE THREAD

**Issue by johnmathew2** [uBlockOrigin/uAssets#6928]
### URL(s) where the issue occurs
`https://redecanais.bz/o-exterminador-do-futuro-destino-sombrio-dublado-2019-1080p_2790d25e9.html`
`https://redecanais.bz/vingadores-ultimato-dublado-2019-1080p-60fps_b8ce96cc4.html`
`https://redecanais.bz/os-simpsons-30a-temporada-episodio-19-a-menina-da-banda_d3b98276c.html
`

### Describe the issue
Many ads and problem when watching videos with ublock origin enabled.
To reproduce the problem, it is necessary to click on “assisitr” to be able to open the player, which goes through several redirects before the final destination. It is necessary to click because the real link only works through a POST form, the player's direct link doesn't work.

### Screenshot(s)
Real player after several redirects: `https://i.imgur.com/YXTQzjl.jpg`

### Versions
- Browser/version: Firefox 72.0.2
- uBlock Origin version: 1.24.4

### Settings
FILTERS: uBlock filters​​​​​​​, uBlock filters Badware risks​, ​​​​uBlock filters Privacy, ​​uBlock filters Resource abuse​​​​​, ​​uBlock filters Unbreak​​​​​, EasyList​​​​​, EasyPrivacy​​​​​, Peter Lowe’s Ad and tracking server list, FRA: EasyList Liste FR, ​​​spa, por: AdGuard Spanish/Portuguese​.
​​

### Notes
Some domains for the player that the main site uses:
`encripted-encripted-encripted-encripted-encripted-encripted1.encripted-encripted-encripted-encripted-encripted-encripted.fun`
`homeingles.com`
`bemestarglobal.com.br`
`noticiasfix.com`
`nutricionistafitness.com.br`

**Comment by mapx-** [comment]
- brazilian stuff needing brazilian ip
- any video chosen on` https://redecanais.bz` home page (after clicking assisitr):
`404 Not Found The page that you have requested could not be found.`
