### ISSUE TITLE
gigaho.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6929]
Anti-adblock

> ![obraz](https://user-images.githubusercontent.com/35370833/73973324-a1c55000-4922-11ea-932d-44c8811e786b.png) |
> --- |

[](https://github.com/AdguardTeam/AdguardFilters/issues/48715)

```
gigaho.com##^script:has-text(/window\.onload.*document\.getElementsByClassName.*adsbygoogle/):has-text(/[\w\W]{600,1200}/)
```

maybe possible kill with scriplet.

**Comment by krystian3w** [comment]
please follow, we are use AG Japanese and this no support EasyList bugs:

https://github.com/easylist/easylist/issues/4863

**Comment by mapx-** [comment]
Easylist wont add filters for anti adblocking. You should close the issue in easylist repository.

**Comment by krystian3w** [comment]
`easylist/easylist#4863` Closed without add exceptions, also I suppose no reported / fixed in removed "EasyList Japanese".

https://github.com/k2jp/abp-japanese-filters/commits/master

@mapx- / @okiehsch

**Comment by mapx-** [comment]
Who cares about a list not supported by uBO ?
Do you still get any anti adblocking ?

**Comment by krystian3w** [comment]
Pop-up gone, EasyList no tried recover text in article:

![obraz](https://user-images.githubusercontent.com/35370833/75094229-982a2200-5589-11ea-8e27-4b39b68bf6e1.png) |
--- |
hidden text in article |

![obraz](https://user-images.githubusercontent.com/35370833/75094240-a8420180-5589-11ea-8512-5b21a1ab8c97.png) |
--- |
blank space - article gone

**Comment by krystian3w** [comment]
Also no tried repair for Brave users:

https://github.com/brave/adblock-lists/pulls?q=is%3Apr+author%3Aryanbr
