### ISSUE TITLE
wstream.video and italianshare.info

### ISSUE THREAD

**Issue by bup4gr** [uBlockOrigin/uAssets#693]
### Filter for wstream.video 
`||wstream.video/imgad/$image,redirect=2x2-transparent.png,first-party`
don't work and you see the anti adblock.
For link and screenshot: https://github.com/uBlockOrigin/uAssets/issues/400

### Filter for italianshare.info
```
italiashare.info##script:inject(nowebrtc.js)
@@||italiashare.info^$generichide
@@||italiashare.info^$image,first-party
italiashare.info###adblockplus
```
don't work and you see the anti adblock.
Previous fix: https://github.com/uBlockOrigin/uAssets/issues/440

**Comment by nimasaj** [comment]
http://www.italiashare.life/ needs a new fix
