### ISSUE TITLE
[Anti-adblock popup] u.gg

### ISSUE THREAD

**Issue by SakhJack** [uBlockOrigin/uAssets#6931]
### URL(s) where the issue occurs

`https://u.gg/lol/tier-list`

### Describe the issue

First time you visit the website every day a popup shows up asking to disable adblock

### Screenshot(s)
<details><summary>popup</summary>

![image](https://user-images.githubusercontent.com/10335530/74007856-5d9b7500-494d-11ea-9773-7b7aba1795db.png)

</details>

### Versions

- Browser/version: Firefox 72.0.2 x64
- uBlock Origin version: 1.24.4

### Settings

All default filters are enabled

### Notes

Blocking this removes popup and translucent overlay, but not sure if it breaks functionality:

`##.show-all-modal`

**Comment by mapx-** [comment]
fixed as annoyance (enable `uBlock filters annoyance` list)

**Comment by SakhJack** [comment]
It's still present even after updating filter

**Comment by mapx-** [comment]
still working, did you enable uBlock filters annoyance list ?
