### ISSUE TITLE
Disqus comment section in Electrek.co

### ISSUE THREAD

**Issue by Lustuccc** [uBlockOrigin/uAssets#6933]
### URL(s) where the issue occurs

`[https://electrek.co/2020/02/07/tesla-aluminum-alloys-die-casting-in-electric-car-parts/]`

### Describe the issue

[Before last week it always ran smoothly, no adds thanks to U, but it appears they found a way to block UBO and the whole Disqus comment section is missing now, with zero(0) comment displayed under the main picture of the articles. Had to whitelist it GRRR! On Windows 7-10 with Firefox and Chrome. ]

### Screenshot(s)

[
![Blocked](https://user-images.githubusercontent.com/47488776/74036865-17650680-498b-11ea-875b-fb1a4d317c77.jpg)
![Unblocked](https://user-images.githubusercontent.com/47488776/74036866-17650680-498b-11ea-865c-c2a8a91b4577.jpg)
]

### Versions

- Browser/version: [Firefox 72.0.2 and Chrome 79.0.3945.130]
- uBlock Origin version: [1.24.4]

### Settings

- [None, I tried the 5 icon options at the bottom of the UBO interface one after the other, but no result

]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by jimmysofat6864** [comment]
Sample url is 

https://electrek.co/2025/03/26/nissan-leaf-all-grown-up-first-look-new-ev/

**Comment by stephenhawk8054** [comment]
I can't reproduce. The comment section appears normally for me.

**Comment by jimmysofat6864** [comment]
I enabled all the filter lists in ublock origin lite. It still wouldn’t
work even on the lowest filtering setting and only disabling it worked.

**Comment by stephenhawk8054** [comment]
Don't do that.

Uninstall and reinstall uBOL + use "Complete" mode. Then enable other lists one-by-one to see which one causes the issue. We never recommend enabling all filter lists and we can't investigate with that configuration.

**Comment by jimmysofat6864** [comment]
> Don't do that.
> 
> Uninstall and reinstall uBOL with default lists + use "Complete" mode. Then enable other lists one-by-one to see which one causes the issue. We never recommend enabling all filter lists and we can't investigate with that configuration.

I've traced it down to Steven Black’s Unified Hosts (adware + malware) causing the problem. Enabling everything except that allows the site to work but disabling everything and having Steven Black’s Unified Hosts (adware + malware) enabled causes the comments to not load.
