### ISSUE TITLE
gamereactor.fi anti adblock nag

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uAssets#6937]
How to make a rule to circumwent this?

![kuva](https://user-images.githubusercontent.com/17256841/74088742-41f5b300-4aa2-11ea-813a-80694f765035.png)

The script that causes this can be accessed directly through this link: `https://www.gamereactor.fi/lay/js/adblock_desktop.js?v303
`
It's probably very simple for you, but my tries were futile... :D

Note: if you refresh the page that nag will go away, you have to clear cookie etc. too see it again.

**Comment by uBlock-user** [comment]
I can't reproduce.

Try `gamereactor.fi##+js(aopr, adblockEnabled)` or `gamereactor.fi##+js(aopw, adblockEnabled)`

**Comment by mapx-** [comment]
or `gamereactor.fi##+js(nostif, Ads)`

**Comment by peace2000** [comment]
Thanks!

Both of these two rules work:
`gamereactor.fi##+js(aopr, adblockEnabled)`
`gamereactor.fi##+js(aopw, adblockEnabled)`

This doesn't:
`gamereactor.fi##+js(nostif, Ads)`

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/1cc1ab49ac62c3f92c916fe69915fa5597b627b4
