### ISSUE TITLE
Skins on namemc.com are flagged as ads(?)

### ISSUE THREAD

**Issue by MastaNub** [uBlockOrigin/uAssets#6939]
### URL(s) where the issue occurs
```
https://namemc.com/skin/ad80e21ba21e6d0f
https://namemc.com/profile/Arvein.4
https://namemc.com/skin/adcdbf7fc0141c2c
```

### Describe the issue
Some skins are not shown when using uBlock.

### Screenshot(s)
```
https://prnt.sc/qzon8c
https://prnt.sc/qzon9v
https://prnt.sc/qzond4
```

### Versions
- Browser/version: Version 80.0.3987.87 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin 1.24.4

### Settings
n/a

**Comment by uBlock-user** [comment]
broken by a postive match in Easylist filter, 

filter - `@@||texture.namemc.com/$image,1p`

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a758aa439d9fb124e956bf1132fb1011473fc1b8
