### ISSUE TITLE
Implement jsonp-prune scriptlet

### ISSUE THREAD

**Issue by ghcsd** [uBlockOrigin/uAssets#6941]
https://github.com/uBlockOrigin/uBlock-issues/issues/891

### Describe the issue

Some [video websites](https://v.youku.com/v_show/id_XMzg0MTE2NjEyOA==.html) include AD and normal video content in [JSONP](https://acs.youku.com/h5/mtop.youku.play.ups.appinfo.get/1.1/?jsv=2.5.7&appKey=24679788&t=1581341537645&sign=e3f0e00968c7bf76f4dc15320bab2219&api=mtop.youku.play.ups.appinfo.get&v=1.1&timeout=20000&YKPid=20160317PLF000211&YKLoginRequest=true&AntiFlood=true&AntiCreep=true&type=jsonp&dataType=jsonp&callback=mtopjsonp1&data=%7B%22steal_params%22%3A%22%7B%5C%22ccode%5C%22%3A%5C%220502%5C%22%2C%5C%22client_ip%5C%22%3A%5C%22192.168.1.1%5C%22%2C%5C%22utid%5C%22%3A%5C%22CEnIFunK%2FlICAXeF0wqhmA6w%5C%22%2C%5C%22client_ts%5C%22%3A1581341537%2C%5C%22version%5C%22%3A%5C%221.10.22%5C%22%2C%5C%22ckey%5C%22%3A%5C%22122%23gOkhjE5nEE%2Bv4EpZy4p0EJponDJE7SNEEP7ZpJRBuDPLJFQLpCGwWyZDEJEL7SwBEyGZpJLlu4Ep%2BFQLpoGUEELWn4yE7SNEEP7ZpERBuDPE%2BBNPpC76EJponDJLKMQEI%2B5FXDdT%2BGKAz4KW06sEtF%2Fpnd39KSEmtswdU0NVgxso7fRe01ahC3I97aew8oL6Ja%2FNd81xqW32Dac2RG72uOqEELVZ8oLUJNEEyBvtqW3bE5VsX5qIeO5EDIRr8CLU%2BDWEyF3mqW32E5pangL4ulqEELVZ8oL6JNEEyBfDqMfbDEpxnSp1uOsHDLVruCmUJzEEyF1S4juq3%2BtaG0fBeIDb%2Bx8kKSSoC%2BkxOBTGzqNPJubbELdLIi1yfKKBNd9GKCxHgBQ6Bc7aKgo3ZdiavdWtkbEc0Apu6x3yvhSl9RY5tndMtSDqED2sonQiS7qz0vvT2%2BnTboIV6OOLMhn%2FSoBbW%2BaYqpOEHWNMFFPmxAzBan%2Fj%2BdsLr3M5Mpf3eo%2BBcoq0Ch5fLMhwFzz1wZKpDMMp%2BsfxWPOtz8TJgRvYBycaftbLjUhk3f57xR%2BQnlmxY8%2B1T57yUEzFc5YRLBQwEKQGy1m5d7DJL1hE2yj8YRSsT6lgWHh%2FpvdhVmPQHwZeUuG%2BvJV4oqnTgv3J%2FZ4B9aUqEBYzal%2FPj7Co%2Be5aZ0oSlmvmGiGk4mbbTDEFOMn9YnOw%2BnBKCwm0jw5IWjLrxwp%2Biq7J98azbNN%3D%5C%22%7D%22%2C%22biz_params%22%3A%22%7B%5C%22vid%5C%22%3A%5C%22XMzg0MTE2NjEyOA%3D%3D%5C%22%2C%5C%22play_ability%5C%22%3A5376%2C%5C%22current_showid%5C%22%3A%5C%22416753%5C%22%2C%5C%22drm_type%5C%22%3A3%2C%5C%22key_index%5C%22%3A%5C%22web01%5C%22%2C%5C%22encryptR_client%5C%22%3A%5C%222ReY64L4lJ%2BvYbuhbZLIaA%3D%3D%5C%22%2C%5C%22preferClarity%5C%22%3A99%2C%5C%22master_m3u8%5C%22%3A1%2C%5C%22media_type%5C%22%3A%5C%22standard%2Csubtitle%5C%22%2C%5C%22app_ver%5C%22%3A%5C%221.10.22%5C%22%7D%22%2C%22ad_params%22%3A%22%7B%5C%22vs%5C%22%3A%5C%221.0%5C%22%2C%5C%22pver%5C%22%3A%5C%221.10.22%5C%22%2C%5C%22sver%5C%22%3A%5C%222.0%5C%22%2C%5C%22site%5C%22%3A1%2C%5C%22aw%5C%22%3A%5C%22w%5C%22%2C%5C%22fu%5C%22%3A0%2C%5C%22d%5C%22%3A%5C%220%5C%22%2C%5C%22bt%5C%22%3A%5C%22pc%5C%22%2C%5C%22os%5C%22%3A%5C%22win%5C%22%2C%5C%22osv%5C%22%3A%5C%2210%5C%22%2C%5C%22dq%5C%22%3A%5C%22auto%5C%22%2C%5C%22atm%5C%22%3A%5C%22%5C%22%2C%5C%22partnerid%5C%22%3A%5C%22null%5C%22%2C%5C%22wintype%5C%22%3A%5C%22interior%5C%22%2C%5C%22isvert%5C%22%3A0%2C%5C%22vip%5C%22%3A0%2C%5C%22emb%5C%22%3A%5C%22Ajk2MDI5MTUzMgJ2LnlvdWt1LmNvbQIvdl9zaG93L2lkX1hNemcwTVRFMk5qRXlPQT09Lmh0bWw%3D%5C%22%2C%5C%22p%5C%22%3A1%2C%5C%22rst%5C%22%3A%5C%22mp4%5C%22%2C%5C%22needbf%5C%22%3A2%7D%22%7D) returned by their servers (in this case [https://v.youku.com/v_show/id_XMzg0MTE2NjEyOA==.html], the existing rules already have scriptlet (nano-setTimeout-booster.js) available, but I think jsonp-prune will be more efficient.).

I hope to use jsonp-prune (similar to [json-prune](https://github.com/uBlockOrigin/uBlock-issues/wiki/Resources-Library#json-prunejs-)) to remove the AD content.

Parameters design:
- required, string/regular expression, matching in the callback function's name
- optional, string, a list of space-separated properties to remove
- optional, string, a list of space-separated properties which must be all present for the pruning to occur

What is JSON-P：
- https://en.wikipedia.org/wiki/JSONP
- https://web.archive.org/web/20160304044218/http://www.json-p.org/

JSON-P Demo:
- https://api.jquery.com/jQuery.getJSON/#example-0

Sorry for my bad English.

**Comment by mapx-** [comment]
I get no video ad.

I added a filter to unblock the video itself (otherwise the video was blocked with a message 
`由于您的浏览器禁用了COOKIE，视频无法正常播放 请设置开启COOKIE后刷新页面` => `The video does not play properly because COOKIE is disabled in your browser - Please refresh the page after opening COOKIE`)
https://github.com/uBlockOrigin/uAssets/commit/882af970ce8945ae3c361143ddceb3da5973b707

**Comment by mapx-** [comment]
The video ads are already blocked by 
`CHN: EasyList China (中文)` filter:
`||vali*.cibntv.net^*.mp4?$media,domain=v.youku.com`
and by `uBlock filters` filter
`||cibntv.net/youku/$media,domain=youku.com`

**Comment by mapx-** [comment]
So, in order to ask a new scriptlet you should come with examples unfixable with the current filters / scriptlets. Closing.
