### ISSUE TITLE
v.qq.com video ads

### ISSUE THREAD

**Issue by ghcsd** [uBlockOrigin/uAssets#6942]
### URL(s) where the issue occurs
```
https://v.qq.com/x/cover/bzfkv5se8qaqel2.html
https://v.sports.qq.com/#/cover/otyvvz9w2g189xf/z0033qq1v7h
https://new.qq.com/omv/video/d306363646k
```

`qq.com##+js(json-prune, ad, vinfo)`
Can solve the above video advertising.

**Comment by ghcsd** [comment]
@mapx- 
updated:
`qq.com##+js(json-prune, ad)`

Countdown advertisement appears at the end of the video.

```
https://v.qq.com/x/page/c0030g4bdn7.html?start=5327
https://v.qq.com/x/page/l00313tto3b.html?start=4226
```

**Comment by mapx-** [comment]
for the adv does this work for you ?
`*level=$media,domain=v.qq.com`

**Comment by ghcsd** [comment]
> 
> 
> for the adv does this work for you ?
> `*level=$media,domain=v.qq.com,redirect=noopmp3-0.1s`

No, if only this rule is used without `qq.com##+js(json-prune, ad)`, even normal video cannot be played.
`https://v.qq.com/x/cover/2tnso5kl5npka7e.html`

**Comment by mapx-** [comment]
I already added your proposal, I was talking only about that final adv
