### ISSUE TITLE
NSFW xhamster.com - Popups

### ISSUE THREAD

**Issue by NubN** [uBlockOrigin/uAssets#6947]
### URL(s) where the issue occurs

`xhamster.com`

### Describe the issue

pop-up window open when you press anything

the issue is only the first time when you visit this site, if the cookies are deleted, the popup back.

### Settings

- uBlock Origin (Filters updated)
- uBlock Extra

**Comment by NubN** [comment]
hey thanks, i see a small issue here 😁

no popups.. but below the videos, this function not working with that filter: https://i.imgur.com/bFEqU2v.png

(check deleting cookies) ^^

**Comment by uBlock-user** [comment]
Site is broken, doesn't work without the filter either.

**Comment by mapx-** [comment]
now is fixed
