### ISSUE TITLE
shink.in – ad + blank space

### ISSUE THREAD

**Issue by pepablock** [uBlockOrigin/uAssets#695]
### URL(s) where the issue occurs

**LINK** **–** `http://shink.in/4stRx`

### Describe the issue

There's an ad above the reCAPTCHA and also leftover blank space from a blocked ad (see screenshot) "Loading... "

### Screenshot(s)

<img width="1680" alt="img_01" src="https://user-images.githubusercontent.com/29940017/30518607-197fe9b6-9b83-11e7-8aa2-44cca9a85374.png">

### Versions

- Browser/version: **Firefox 55.0.3 (64-bit)**
- uBlock Origin version: **1.14.8**

### Settings

Default

### Notes

–

**Comment by mapx-** [comment]
```
shink.in##[id*=ScriptRoot]
shink.in##a[href*="adk2x"]
```
