### ISSUE TITLE
BlockAdblock.com AdBlock blocker / Used by : https://erai-raws.info/

### ISSUE THREAD

**Issue by ShadowOfHarbringer** [uBlockOrigin/uAssets#6951]
### URL(s) where the issue occurs

https://erai-raws.info/

### Describe the issue

uBlock origin is detected and browsing the site is totally disabled by the scripts.

### Screenshot(s)
https://i.imgur.com/ttSRAay.png

### Versions

- Browser/version: Waterfox 56.2.x
- uBlock Origin version: 1.24.4

### Settings

- Default

### Notes
- There are specialized services now that block adblock and ublock. They work and cannot be blocked. Especially there is a lot of them in Poland
- This situation persists for months. I have not reported it before, because I did not believe it can be fixed. Can it?

### Experimentation
- Added and updated "Adblock Warning Removal​​​​​" filters
​​- Added and updated"AdGuard Base​" filters
- Tried to block external scripts using uMatrix
Didn't help.

### Workaround that works

Disable Javascript totally. Using uMatrix to block any external websites doesn't help. The script is apparently embedded in main site

**Comment by ShadowOfHarbringer** [comment]
PS.

I have also tried installing NanoDefender.

Did not help. Erai-Raws still hides the site.

**Comment by ShadowOfHarbringer** [comment]
Also tried enabling and updating following filters:

- Adblock Warning Removal​​​​​
- AdGuard Base

Did not help as well.

**Comment by ShadowOfHarbringer** [comment]
Why did you close the issue?

**Comment by uBlock-user** [comment]
Closed in https://github.com/uBlockOrigin/uAssets/commit/346498be9ae6e4c85275af5966f124b5284f6fb1

force update uBlock Filters in few mins.

**Comment by ShadowOfHarbringer** [comment]
Well, OK. I will try to do it in 30-60 minutes.

**Comment by ShadowOfHarbringer** [comment]
OK, I force-updated all filters, everything works now. Thanks.
