### ISSUE TITLE
Mocospace detection

### ISSUE THREAD

**Issue by tamathehutt** [uBlockOrigin/uAssets#6956]
### URL(s) where the issue occurs

`https://www.mocospace.com/`

### Describe the issue

Ublock Origin is detected as soon as you log in.

### Screenshot(s)

https://ibb.co/XbXq9Pb

### Versions

- Browser/version: Microsoft Edge (Chromium) 80.0.361.54 (Official build) (64-bit)
- uBlock Origin version: 1.24.4
- uBlock Origin Extra version: 2.88

### Settings

All default + "I am an advanced user" and "Adblock warning removal."

### Notes

Disabling uBO removes the detection warning, website is then populated with banner and other ads.

**Comment by ghajini** [comment]
Logins here work

`http://bugmenot.com/view/mocospace.com`

**Comment by Carm01** [comment]
I know this is closed but here is what you need to do in My Filters:
mocospace.com#.header
mocospace.com##.jqmOverlay
mocospace.com#DIV + * + * + * + * > DIV.content
www.mocospace.com##DIV[id="dialog-adblocker"][class="jqmWindow jqm-init"]
