### ISSUE TITLE
clicknupload.co 

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#6959]
### URL(s) where the issue occurs

`[https://clicknupload.co/krjkr9q3f1ng]`
`[*.clicknupload.co/*************]`

### Describe the issue

[Can't enter the captcha number while UBO is active]

### Screenshot(s)

[
![2020-02-15_171804](https://user-images.githubusercontent.com/9832875/74586195-ce125800-5017-11ea-8f0a-e628bb4b1fdb.png)
]

### Versions

- Browser/version: [Firefox 73.0]
- uBlock Origin version: [1.24.4]

### Settings

- [All of my UBO settings : https://pastebin.com/2uaswdNA]

### Notes

[Deactivated UBO and all are good]

**Comment by KiLL4FuNK** [comment]
Popup Create Download Link

`https://clicknupload.co/cjxo55qvmgtf`

**Comment by mapx-** [comment]
No issue here, did you update all lists ?

**Comment by ghajini** [comment]
Opera browser

Popup ads

`clicknupload.co/ro0bnxh4aq2c`
