### ISSUE TITLE
keraf NoCoin list

### ISSUE THREAD

**Issue by impredicative** [uBlockOrigin/uAssets#696]
https://raw.githubusercontent.com/keraf/NoCoin/master/blacklist.txt

Can the above list be added as an option?

**Comment by impredicative** [comment]
This is really rude. Why is this declined without an explanation?

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uAssets/commit/8cbb35c59bf416e3309ae5bb5811526a76d118a9

**Comment by gorhill** [comment]
Search the existing issue before opening a new one next time please.
