### ISSUE TITLE
[NSFW] jav.guru

### ISSUE THREAD

**Issue by djc920** [uBlockOrigin/uAssets#6960]
### URL(s) where the issue occurs

`https://jav.guru/85030/bazx-223-recruiting-in-business-suits-vol-001/`

### Describe the issue

2 ads on the right side, 1 ad in the middle when you scroll down

### Screenshot(s)

`https://i.imgur.com/sYDfIQO.jpg`

### Versions

- Browser/version: Google Chrome 80.0.3987.106 (Official Build) (64-bit)
- uBlock Origin version: 1.24.4

### Settings

- default settings

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/blob/master/README.md

**Comment by uBlock-user** [comment]
@ryanbr
