### ISSUE TITLE
miuipro.info

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#6961]
### URL(s) where the issue occurs

`[https://miuipro.info/roms/]`

### Describe the issue

[Devices selection when try to download rom does nto displayed because of UBO activated]

### Screenshot(s)

[
![2020-02-16_093929](https://user-images.githubusercontent.com/9832875/74598226-46246080-50a0-11ea-95ef-1f25160e95d8.png)
]

### Versions

- Browser/version: [73.0]
- uBlock Origin version: [1.24.4]

### Settings

- [All of my UBO settings : https://pastebin.com/2uaswdNA]

### Notes

[Disabled UBO and device displayed]

**Comment by okiehsch** [comment]
Add 
`@@||miuipro.info/wp-content/plugins/*/social-likes.min.js$script,1p`
to your filter list.

The breakage is caused by 
````
/social-likes.min.js$domain=~animego.org|~zastenchivosti.net|~gorod-812.ru|~sputnik.by|~sputnik-news.ee|~animalreader.ru|~ichip.ru|~keddr.com|~kino-max.com|~kino24x7.com|~make-3d.ru|~miuipro.ru|~omelchuck.ru|~podfm.ru|~serial-online.com|~sputniknews.com|~trinixy.ru|~kinogo-kinopoisk.net|~bobfilm-online.ru|~westernfilm.ru|~bobfilm.tv|~kinokrik.net|~kinogo720.net|~kinogo-net-co.ru|~kinoklad.net|~intex-press.by|~kino-max.org|~farming-simulator15.ru|~trikky.ru|~trv-science.ru|~unzensuriert.at|~lizaalert.beeline.ru|~megapolisonline.ru|~sputniknews.ru
`````
in `AdGuard Social Media`.
@Alex-302 fyi

**Comment by exodius48** [comment]
> 
> 
> Add
> `@@||miuipro.info/wp-content/plugins/*/social-likes.min.js$script,1p`
> to your filter list.
> 
> The breakage is caused by
> 
> ```
> /social-likes.min.js$domain=~animego.org|~zastenchivosti.net|~gorod-812.ru|~sputnik.by|~sputnik-news.ee|~animalreader.ru|~ichip.ru|~keddr.com|~kino-max.com|~kino24x7.com|~make-3d.ru|~miuipro.ru|~omelchuck.ru|~podfm.ru|~serial-online.com|~sputniknews.com|~trinixy.ru|~kinogo-kinopoisk.net|~bobfilm-online.ru|~westernfilm.ru|~bobfilm.tv|~kinokrik.net|~kinogo720.net|~kinogo-net-co.ru|~kinoklad.net|~intex-press.by|~kino-max.org|~farming-simulator15.ru|~trikky.ru|~trv-science.ru|~unzensuriert.at|~lizaalert.beeline.ru|~megapolisonline.ru|~sputniknews.ru
> ```
> 
> in `AdGuard Social Media`.
> @Alex-302 fyi

Thx, it works. Waiting for permanent fixes. :)

**Comment by Alex-302** [comment]
Thanks, fixed.
