### ISSUE TITLE
webtor.io

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#6964]
### URL(s) where the issue occurs

`https://webtor.io`

### Describe the issue

VPN ad `##.sticky.alerts` on top of the page. Click on Demo to find another ad `##.me-ad-container` below the video.

Randomly, a popup seems to be triggered on playing or seeking the video. Not sure what's the real trigger so ignore if it's non-reproducible.

### Versions

- Browser/version: Firefox 73.0
- uBlock Origin version: 1.24.4

### Settings

Default

**Comment by uBlock-user** [comment]
> VPN ad ##.sticky.alerts on top of the page. Click on Demo to find another ad ##.me-ad-container below the video.

> If an issue can be fixed without using extended syntax, i.e. scriptlet injection, redirect, procedural cosmetic filters, etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

@ryanbr 

fixed popup, force update uBlock Filters list.
