### ISSUE TITLE
[Anti-Adblock] nirjonmela.com

### ISSUE THREAD

**Issue by version365** [uBlockOrigin/uAssets#6965]
# URL(s) where the issue occurs

`https://nirjonmela.com/forums/collected-choti.91/` (possible NSFW)

### Describe the issue

The pages redirects to a thread with instructions on how to disable adblocker on that site.

### Versions

- Browser/version: Firefox 73
- uBlock Origin version: 1.24.4

**Comment by version365** [comment]
It's showing anti-adblock warning again!

**Comment by mapx-** [comment]
still ok on my end

**Comment by version365** [comment]
It was an issue on my end, sorry for the trouble..
Apparently, it was a third party filter I had installed long ago, what was causing the problem.
