### ISSUE TITLE
ekino.pw [broken embeded player] [pop-ups]

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6966]
`https://ekino.pw/pewnego-razu-w-hollywood/`

forozen/broken embeded player:

`https://waaw.tv/player/embed_player.php?#iss=MTg4LjE0Ny4zOS4yOA==`

also play button generate many pop-ups:

```html
<div id="play_clicker" class="tooltipd" style="width:100%; height:100%;position:absolute;top:0px;left:0px;z-index:1;cursor:zoom-in;" title="open video" ontouchstart="openpopplayerin('fCcB0fc2rqtd',event);" onclick="openpopplayerin('fCcB0fc2rqtd',event);">
<span id="tooltip-span" style="top: 255px; left: 292px;">
<h4>&nbsp; open video &nbsp;</h4>
</span>
</div>
```

```js
function onclick(event) {
  openpopplayerin('fCcB0fc2rqtd', event);
}
```

So possible repair embeded player or this is scam site to blacklist by:

```
||ekino.pw^$all
```

**Comment by mapx-** [comment]
The player is not broken on my side, the video will open in a separate window and runs fine
