### ISSUE TITLE
encurta.eu

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#6967]
### URL(s) where the issue occurs

`https://encurta.eu/rkBt9rW6`

### Describe the issue

Anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/61142621/74678717-14a0b780-51bc-11ea-97fc-3023eda205f0.png)

### Versions

- Browser/version: 66.0.3515.72
- uBlock Origin version: 1.23.0

### Settings

- Default

### Notes

None

**Comment by sugarfreesweetener** [comment]
```
4br.me##.banner-inner
4br.me##[href*="://ads."]
```

@Yuki2718 `AG Spanish`?

**Comment by Yuki2718** [comment]
> AG Spanish

No in case of these short links.
