### ISSUE TITLE
probléme mise a jour flitres en mode auto

### ISSUE THREAD

**Issue by war789** [uBlockOrigin/uAssets#697]
bonjour a tous
voila j'ai un problème avec ublock origin car a chaque fois que je quitte mon navigateur firefox  je suis obliger de mettre manuellement les filtres malgré la case coché en automatique

![](https://user.oc-static.com/upload/2017/09/12/15052377541832_GetAttachmentThumbnail.jpeg)

aider moi si vous plait
merci
paramètres
    version: Windows 7, x32
    Navigateur / version: Firefox 55.0.3 x86
    uBlock Version d'origine: v1.14.8

**Comment by gotitbro** [comment]
@war789 I don't know French but from what **_Google Translate_** tells me it seems you have a problem with the auto-update functionality of filter lists in uBO on Firefox. 

This issue might be resolved by disabling and enabling the extension again, if you haven't done that already. If even that doesn't solve the issue try installing the extension afresh.

**PS:** It would be nice if you could post in English here as more users will be able to help you. Also this is not exactly an issue for this repository, you should check this out as well https://github.com/gorhill/ublock.

**Comment by gorhill** [comment]
https://github.com/gorhill/uBlock/issues/2925#issuecomment-325968653
