### ISSUE TITLE
forum.notebookreview.com is not usable

### ISSUE THREAD

**Issue by Leon422** [uBlockOrigin/uAssets#6971]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X ] uBlock Origin is the only extension
    - [X ] uBlock Origin with default lists/settings
    - [X ] using a new, unmodified browser profile
- [X ] I am running the latest version of uBlock Origin
- [X ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

http://forum.notebookreview.com/forums/hardware-components-and-aftermarket-upgrades.27/

### Steps to Reproduce

1. Enable the "Adguard Annoyances" filter list
2. Try to use the site
3. You can't

### Expected behavior:

The cookies popup should not appear and you should be able to use the page

### Actual behavior:

[What actually happened]

The website goes gray and the popup never appears, and you can't use the site.

* uBlock Origin version: v1.24.4
* Browser Name and version: Firefox 73.0
* Operating System and version: Windows 10 1909

**Comment by uBlock-user** [comment]
`||cdn.ttgtmedia.com/cmp/sourcepoint/$script,3p`

**Comment by Alex-302** [comment]
Thanks, fixed.
