### ISSUE TITLE
Pages not displayed correctly with 1.25

### ISSUE THREAD

**Issue by Yaron10** [uBlockOrigin/uAssets#6974]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
Pages not displayed correctly with 1.25.
**No problem with 1.24.**

### A specific URL where the issue occurs
https://www.ynet.co.il/home/0,7340,L-8,00.html
![תמונה](https://user-images.githubusercontent.com/10229320/74858990-e30c2580-534e-11ea-97cc-06ca4f4003c6.png)

https://news.walla.co.il/
![תמונה](https://user-images.githubusercontent.com/10229320/74859146-21094980-534f-11ea-9993-16d415f46761.png)

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.25
* Browser Name and version: Firefox 73.
* Operating System and version: Windows 7.

**Filter Lists:** EasyList + EasyList  Hebrew.

**Comment by uBlock-user** [comment]
Broken by `/^(?![a-zA-Z0-9\-]+\:\/+([^\/\:\.]+\.)*(facebook|fbcdn|dmcdn|slideshare|cloudfront|brightcove|jsdelivr|akamai|akamaihd|akamaized|ctedgecdn|2mdn|edgesuite|azurewebsites|azureedge|windows|hwcdn|zencdn|llnwd|boltdns|msecnd|bitsngo|nocookie|datatables|docdroid|algolia|anvato|twitchcdn|ttvnw|jtvnw|ampproject|dailyuploads|recaptcha|yastatic|8ch|behance|edgefonts|typekit|deviantart|vodgc|hlsplayer|web-view|streamgates|cdnwz|playgorithm|vidiom|chartbeat|doubleclick|advsnx|pagefair|liveadserver|freegeoip|upapi|total-media|sc-static|artipbox)\.net\.?([\/\:]|$))^[a-zA-Z0-9\-]+\:\/+[^\/\:]+\.net\.?([\/\:]|$)/$3p,domain=calcalist.co.il|pplus.ynet.co.il|www.ynet.co.il|xnet.ynet.co.il` by EasyList Hebrew.

v1.25 uncloakes CNAMEs, and that filter is causing a match with the CDN server of that website,

**Comment by Yaron10** [comment]
Thank you.

**Comment by llacb47** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Just to confirm this wasn't an Easylist issue eh?

**Comment by llacb47** [comment]
Sorry, I pinged you by mistake.
