### ISSUE TITLE
uploadship.com

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#6975]
### URL(s) where the issue occurs

`https://www.uploadship.com/1827b3a527410f0a`

### Describe the issue

Detect adblock and redirect to error page

### Screenshot(s)

![image](https://user-images.githubusercontent.com/61142621/74861171-30d25f00-534a-11ea-8a1d-4c5886dbe8f2.png)

### Versions

- Browser/version: Opera Version:66.0.3515.95
- uBlock Origin version: 1.23.0

### Settings

- All default

### Notes

N/A

**Comment by mapx-** [comment]
update your lists

**Comment by LGLTeam** [comment]
Ok i forgot to update it. the error is gone today even i didn't update the lists. seems the web master already seen this and make changes so countdown increases if adblock is enabled
