### ISSUE TITLE
Incorrectly blocking https://mcp.educationapps.vic.gov.au/

### ISSUE THREAD

**Issue by borisqbf** [uBlockOrigin/uAssets#6977]
### URL(s) where the issue occurs

Blocking `https://mcp.educationapps.vic.gov.au/` - educational web side build by Department of Education and Training Victoria, Australia. The site is used by 250K students state wide

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
@borisqbf  open the uBO logger, refresh the page in trouble, select only the blocked items, post here the results (or provide a test account indicating how to get the issue)

**Comment by krystian3w** [comment]
try:

`@@||mcp.educationapps.vic.gov.au^$generichide`

or 

`@@||mcp.educationapps.vic.gov.au^$all`

**Comment by mapx-** [comment]
no feedback, closing

**Comment by krystian3w** [comment]
I suppose website no have ads / tracking so possible safe add:

`@@||mcp.educationapps.vic.gov.au^$ghide,all`

**Comment by mapx-** [comment]
@krystian3w nothing to do without a feedback from OP. Please don't insist on this matter.
