### ISSUE TITLE
Need to whitelist Paypal to login to Mastercard

### ISSUE THREAD

**Issue by alex-clay** [uBlockOrigin/uAssets#6978]
### URL(s) where the issue occurs

Paypal Mastercard login (I redacted potentially sensitive data):
`https://www.paypal.com/signin/authorize?client_id=[REDACTED]&response_type=code&redirect_uri=[REDACTED]&state=[REDACTED]`

### Describe the issue

Need to whitelist `www.paypal.com` & <s>`paypal.syf.com`</s> to login to the Paypal Mastercard service account. When I don't do that, the page displays an infinite loading screen.
(Edit: I found out that paypal.syf.com is unrelated to this issue.)

The way login works in this Paypal service is by redirecting the browser to a series of links:
1- `https://www.paypal.com/signin/authorize?client_id=[REDACTED]&response_type=code&redirect_uri=[REDACTED]&state=[REDACTED]`  
2- `https://www.paypal.com/signin/consent`  
3- `https://paypal.syf.com/ESecuritySSO/PayPal/transition.action?code=[REDACTED]`  
4- `https://paypal.syf.com/ESecuritySSO/PayPal/login.action`  
5- `https://paypal.syf.com/eService/AccountSummary/initiateAccSummaryAction.action`

### Versions

- Browser/version: Firefox Version 73.0 (64-bit). Running on Ubuntu 18 LTS
- uBlock Origin version: uBlock Origin v1.24.4

### Settings

- No changes

**Comment by mapx-** [comment]
open the uBO logger, refresh the page in trouble, select only the blocked items, post here the results

**Comment by alex-clay** [comment]
I found out that `paypal.syf.com` is unrelated to this issue. I only need to whitelist `www.paypal.com`

To reproduce the infinite loading screen, I removed the `www.paypal.com` whitelist and filtered for only the blocked items in the logger:

<details><summary>Logger output</summary>

```
+2
||t.paypal.com^
--
www.paypal.com
1
image
https://t.paypal.com/ts?v=1.3.34&t=1582305803388&g=480&e=im&pgrp=main%3Aunifiedlogin%3A%3A%3Alogin&page=main%3Aunifiedlogin%3A%3A%3Alogin%3A%3A%3A&tmpl=unifiedloginnodeweb%2Fpublic%2Ftemplates%2Ftransition.dust&pgst=1582305801680&lgin=%3A%3A&vers=unifiedlogin&calc=50487de3dab60&nsid=0E47g2kr8_ikSvb20_WJLunxQQRIGzjw&rsta=en_US&pgtf=Nodejs&env=live&s=ci&ccpg=US&csci=f7e881db88d54770844afa198b4aa779&comp=unifiedloginnodeweb&tsrce=unifiedloginnodeweb&cu=1&gacook=1979630969.1561661948&cust=2XH777246GKWU&party_id=2XH777246GKWU&acnt=personal&aver=verified&rstr=unrestricted&cnac=US&transition_name=process_ul_browser_render&token_status=success&thirdpartylogin_client_id=[REDACTED]&thirdpartylogin_channel=ul&thirdpartylogin_client_name=PaypalEbayApply&pglk=main%3Awalletweb%3Asummary%3A%3Amain%7CpayPalMCHeader&view=%7B%22t10%22%3A80%2C%22t11%22%3A1628%2C%22tcp%22%3A831%2C%22nt%22%3A%22navigate%22%2C%22bt%22%3A546%7D&ru=https%3A%2F%2Fwww.paypal.com%2Fmyaccount%2Fsummary&cd=24&sw=1536&sh=864&dw=1920&dh=1080&bw=1536&bh=689&ce=1&t1=80&t2=593&t4d=390&t4=394&t4e=3&tt=1078&res=%7B%7D
```
```
+1
/gtag.js
--
www.paypal.com
3
script
https://www.paypalobjects.com/pa/mi/3p/gtag/gtag.js
```
```
+1
/gajs/analytics.js
--
www.paypal.com
3
script
https://www.paypalobjects.com/gajs/analytics.js
```
```
+1
/pageview.js
--
www.paypal.com
3
script
https://www.paypalobjects.com/web/res/38e/9ac625dfacd492454a92f22ea2318/js/view/pageView.js
```
```
+0
https://www.paypal.com/signin/authorize?client_id=[REDACTED]&response_type=code&redirect_uri=https%3A%2F%2Fpaypal.syf.com%2FESecuritySSO%2FPayPal%2Ftransition.action&state=eyJmbG93X2lkIjoiNCIsIlZSUiI6IkFTRDI2VjQ5UFEyNDgifQ%3D%3D
```
```
+0
||t.paypal.com^
--
www.paypal.com
1
image
https://t.paypal.com/ts?v=1.3.34&t=1582305801502&g=480&e=cl&page=main%3Awalletweb%3Asummary%3A%3Amain%3A%3A%3A&pgrp=main%3Awalletweb%3Asummary%3A%3Amain&type=casualSeller&vers=customer&pgtf=Nodejs&comp=summarynodeweb&rsta=en_US&ccpg=US&cust=[REDACTED]&lcid=[REDACTED]&xe=[REDACTED]&xt=[REDACTED]&domain_type=CREDIT&card_type=%20&card_id=%20&COORD_X=%20&link=CREDIT%7CpayPalMCHeader&pglk=main%3Awalletweb%3Asummary%3A%3Amain%7CpayPalMCHeader&pgln=main%3Awalletweb%3Asummary%3A%3Amain%3A%3A%3A%7CpayPalMCHeader&gacook=1979630969.1561661948
```
</details>

**Comment by mapx-** [comment]
Try fisr only:

`*$script,redirect-rule=noopjs,domain=paypal.com`

If does not work these (but one at a time then combinations)
```
@@||paypalobjects.com/*/gajs/analytics.js$script,domain=paypal.com
@@||paypalobjects.com/*/gtag.js$script,domain=paypal.com
@@||paypalobjects.com/*/pageView.js$script,domain=paypal.com
```

**Comment by alex-clay** [comment]
After trying all of them, the only filter that solved the loading screen is the last one:
`@@||paypalobjects.com/*/pageView.js$script,domain=paypal.com`

**Comment by mapx-** [comment]
added to `unbreak` list

**Comment by mapx-** [comment]
@ryanbr
