### ISSUE TITLE
Monero JS crypto miner running without user consent

### ISSUE THREAD

**Issue by HarveyWilliams** [uBlockOrigin/uAssets#698]
### URL(s) where the issue occurs

`https://coin-hive.com/`

### Describe the issue

JS crypto miners can utilize computer resources to mine crypto through the web. Because it's just JS running in the browser, a website does not need to tell the user that the miner is going to be run.

Coinhive says:

> While it's possible to run the miner without informing your users, we strongly advise against it. You know this. Long term goodwill of your users is much more important than any short term profits. 

However, we can no doubt be sure that this breed of miners will be abused at some point.

I feel like uBlock should make an attempt to block these scripts from running.

### Versions

- Browser/version: FF55.0.3 (64-bit)
- uBlock Origin version: 1.14.8

### Notes

`pr0gramm.com` is an image sharing site which utilizes this miner to help fund itself (`http://miner.pr0gramm.com/`). It does this in a manner which the user can clearly see so the user will need to know to disable their blocker for sites where they give consent (it should probably be up to the website to realise that the miner script has been blocked and to tell the user to disable their blocking).

I'd like to hear other users thoughts about this issue. You can run this script to max out your CPU so the idea of any website using this instead of adverts isn't exactly preferable unless I give consent.

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uAssets/issues/690
