### ISSUE TITLE
leechall.download

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#6981]
### URL(s) where the issue occurs

`https://leechall.download/go/HJ3RKTZW4UEQO0G`

### Describe the issue

Anti adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/61142621/75058630-a6ba0000-54db-11ea-9bd5-ac0221a268fb.png)

### Versions

- Browser/version: Opera Version: 66.0.3515.103
- uBlock Origin version: 1.23.0

### Settings

- All default

### Notes

If cannot reproduce:

1. Go to https://leechall.com/
2. Put this link in the box `https://rapidgator.net/file/0eb8842477f4cbf8b43f4aaef3ed7648/asoiadevv17826.rar.html`
3. click download and it will generate
4. click on generated link

**Comment by ghajini** [comment]
Antiadblock
`https://leechall.download/go/SAK6TR7J851DIM4`
