### ISSUE TITLE
stfly.io

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#6982]
### URL(s) where the issue occurs

`https://stfly.io/LybBiyeH`

### Describe the issue

Countdown

### Screenshot(s)

![image](https://user-images.githubusercontent.com/61142621/75059763-e5e95080-54dd-11ea-86fb-d0c2f9aa66c4.png)

### Versions

- Browser/version: Opera Version: 66.0.3515.103
- uBlock Origin version: 1.23.0

### Settings

- All default

### Notes

Request countdown booster

**Comment by mapx-** [comment]
checked on server side
`Bad Request.`

**Comment by LGLTeam** [comment]
Ok thanks for trying
