### ISSUE TITLE
uBlock doesnt block opensubtitles.com

### ISSUE THREAD

**Issue by Dinervity** [uBlockOrigin/uAssets#699]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
Web page
https://www.opensubtitles.org/fi

Popup url:
http://35.188.14.213/W29iamVjdCBNb3VzZUV2ZW50XS8xMzA1OTg5W29iamVjdCBNb3VzZUV2ZW50XS8weWhzeHR6ejF4

another is 

http://trk.ablogica.com/router?code=HFKF1WX&traffic_source=197544&pcn=HFKF1WX&sub_id=1718355

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`
![popup](https://user-images.githubusercontent.com/31162876/30546492-6a40b8fe-9c95-11e7-9659-a89a20f7ac98.png)

### Describe the issue
When you choose movie subs at start page and then push download button a ad pops up.

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

Added. Sry for FIN text.

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: [55.0.3 Mozilla 64-bit] FIN
- uBlock Origin version: [1.14.8]

### Settings
Nothing
- [List here all the changes you made to uBO's default settings]

### Notes

Thanks!

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by gorhill** [comment]
Does the following work? (clear cookies for opensubtitles.org before trying)

    opensubtitles.org##script:inject(abort-current-inline-script.js, atob)

**Comment by Dinervity** [comment]
Yes it work thanks!
