### ISSUE TITLE
The blockadblock.com homepage is strict blocked by uBO

### ISSUE THREAD

**Issue by KINGTVBOX** [uBlockOrigin/uAssets#6990]

**Comment by okiehsch** [comment]
@pgl is `blockadblock.com` really used as a 3rd-party ad/tracking domain?

**Comment by pgl** [comment]
@okiehsch It loads assets which are used to get around ad blockers, so ads and trackers can be loaded. Unless I'm wrong?

**Comment by okiehsch** [comment]
> It loads assets which are used to get around ad blockers

Do you have an example site? I've never seen ads or trackers loaded by that domain.
What blockadblock does is explained at `https://blockadblock.com/blockadblock_basic_script.php` and `https://blockadblock.com/configure.php`
If you can't access those sites  add `blockadblock.com##+js(nobab)` to your filter list.

I have modified your filter, so uBO-users will only block all 3rd-party requests originating from `blockadblock.com` to fix this issue.
