### ISSUE TITLE
https://m.bulbapedia.bulbagarden.net

### ISSUE THREAD

**Issue by Jorge9811** [uBlockOrigin/uAssets#6994]
### URL(s) where the issue occurs

`https://m.bulbapedia.bulbagarden.net`

### Describe the issue

I went to this page and I can very clearly see an ad on the lower part of the page.

### Screenshot(s)

![firefox-2020-02-23_13-59-47](https://user-images.githubusercontent.com/54429803/75116226-d2a4c500-5644-11ea-93a8-018da1fe4fd7.png)

### Versions

- Browser/version: Mozilla Firefox v73.0.1 x86
- uBlock Origin version: 1.24.2

### Settings

https://i.imgur.com/9n9q0WA.png

Because I'm using Nano Defender, I also have userResourcesLocation adjusted accordingly.

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
`m.bulbapedia.bulbagarden.net##[href="https://dailybits.news/"]`
or
`||bulbagarden.net/*banner$image`

to be included in easylist @ryanbr

**Comment by uBlock-user** [comment]
@mapx- I fixed it in the list.
