### ISSUE TITLE
100% CPU and Page Lockup on Grubhub for Restaurants

### ISSUE THREAD

**Issue by stephenliang** [uBlockOrigin/uAssets#6997]
### URL(s) where the issue occurs

`https://restaurant.grubhub.com`

### Describe the issue

When you loading the login page, the page renders but immediately becomes unresponsive. Task manager shows the page at 100% CPU.

### Screenshot(s)

N/A - Can reproduce by going to the website. No visual issues as the page becomes unresponsive.

### Versions

- Browser/version: Version 79.0.3945.130 (Official Build) (64-bit)
- uBlock Origin version: 1.24.4

### Settings

- Using default settings

### Notes

100% CPU Usage on the login page for Restaurants for Grubhub. Disabling uBlock fixes the website.

**Comment by llacb47** [comment]
@okiehsch `@@||tags.tiqcdn.com/utag/grubhubseamless/restaurant.grubhub.com/prod/utag.js$script,domain=restaurant.grubhub.com`

**Comment by okiehsch** [comment]
I know. ;)
