### ISSUE TITLE
purpleads.io and usefathom.com

### ISSUE THREAD

**Issue by gmariani** [uBlockOrigin/uAssets#6998]
### URL(s) where the issue occurs

`https://wpaudit.site/`

### Describe the issue

Pop-up/notification style ad still displayed in bottom right corner.

### Screenshot(s)

![screenshot](https://user-images.githubusercontent.com/5058619/75189456-3817b500-571c-11ea-8d6b-e9a52dbefc25.png)

### Versions

- Browser/version: Firefox/73.0.1
- uBlock Origin version: 1.24.4

### Settings

- ! 2/24/2020 Purpleads.io
||purpleads.io/load.js

! 2/24/2020 usefathom.com analytics
||usefathom.com/tracker.js

### Notes

I have never seen the ads from purpleads before, but neither those or usefathom were blocked at all. Just surprised me and wanted to report it SOMEWHERE. Hopefully this is detailed enough.

**Comment by llacb47** [comment]
@ryanbr

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/blob/master/README.md

````
If an issue can be fixed without using extended syntax, i.e. scriptlet injection, redirect, procedural cosmetic filters, etc. the issue will, as a rule of thumb, **not be fixed** by uAssets, because fixing it in EasyList if possible is preferable.
````
