### ISSUE TITLE
apps.jeurissen.co

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#6999]
`https://apps.jeurissen.co/g-app-launcher/updated?version=21.4`
`https://apps.jeurissen.co/shortcuts-for-google/updated?version=21.3`
`https://apps.jeurissen.co/shortcuts-for-google/installed`

anti-adblock annoyance / dotation background if ads no possible load:

![obraz](https://user-images.githubusercontent.com/35370833/75190077-da04c500-574f-11ea-8f9d-5d5df455dd60.png) |
--- |

**Comment by mapx-** [comment]
maybe `*$image,redirect-rule=2x2.png,domain=apps.jeurissen.co`

**Comment by krystian3w** [comment]
Into `my filters` panel only?

**Comment by ayla1987** [comment]
I don't really understand what this is about, but that is the address used with what I believe is the source of malware on my computer. That was the first time I saw something that wasn't right, I believe the Black Menu for Google extension was responsible. It totally looked like a fake page, but I'm also getting browser redirects, usually for something that looks like a game or horoscopes.

**Comment by krystian3w** [comment]
Maybe try delete addons created by programmer "`apps.jeurssen.co`" and maybe check adddon code on:

> `https://robwu.nl/crxviewer/`

if you must report addon as malware.

PS. Google turned on "Dark" theme for text searches (PC/Tablet mode), if you logged on any Google account:

> `https://www.google.com/preferences?hl=en`
>
> ![Screenshot_2021-03-01 Search Settings](https://user-images.githubusercontent.com/35370833/109466501-173e1a00-7a6a-11eb-83a6-97f86f3cd803.png)

Maybe this option is better altetnative than `Black Menu for Google™` by company "`apps.jeurissen.co`...?

**Comment by krystian3w** [comment]
I see again this annoyance placeholder.
