### ISSUE TITLE
The site http://www.aranzulla.it/ intercept uBO

### ISSUE THREAD

**Issue by happysurf** [uBlockOrigin/uAssets#70]
The site http://www.aranzulla.it/ recognize UBO.

Example: http://www.aranzulla.it/come-pulire-il-pc-lento-gratis-37137.html)

### Screenshot(s)
![screenshot_1](https://cloud.githubusercontent.com/assets/13637587/16362546/b78d3538-3bb1-11e6-80b9-a3a4c1df9a44.png)

### Versions

- Browser/version: [Firefox 48beta3]
- uBlock Origin version: [1.7.6]

### Settings

- [default settings]

### Notes

[Impossible for me fix this problem also by logger info.]

**Comment by IDKwhattoputhere** [comment]
Not a good solution but works for the moment: https://forums.lanik.us/search.php?keywords=aranzulla.it

**Comment by gorhill** [comment]
> works for the moment

Are you sure? I don't see it working with EasyList Italy, which is supposed to contains the fix if I understand correctly.

**Comment by happysurf** [comment]
@IDKwhattoputhere Thank you for info.

On Easy List Italy forum I found these code that works (included on Easy List Italy):

`@@|http://*$script,xmlhttprequest,image,subdocument,domain=aranzulla.it`
`aranzulla.it##.banner.adsbygoogle`
`aranzulla.it##.adsbygoogle`

**Comment by IDKwhattoputhere** [comment]
> which is supposed to contains the fix

I don't see it in EasyList Italy. I added it manually since the last update seems to be [this one](https://forums.lanik.us/viewtopic.php?p=96717#p96717).

**Comment by gorhill** [comment]
> `@@|http://*$script,xmlhttprequest,image,subdocument,domain=aranzulla.it`

That's really not ideal, this essentially disable all filtering for a lot of network requests. On the left, remote servers reached with the above solution:

![a](https://cloud.githubusercontent.com/assets/585534/16362853/4a890ebe-3b87-11e6-9c23-1d219b502e6c.png)

If it's only to read articles, disabling inline scripts work better -- page load fast and no unwanted 3rd-parties.

**Comment by happysurf** [comment]
@IDKwhattoputhere You are right, will be included in the next update.
@gorhill You are right, disabling inline scripts on site http://www.aranzulla.it/ fix the block (my error was disabling only on single page article).

**Comment by IDKwhattoputhere** [comment]
In case anyone doesn't know how to:
![](https://cloud.githubusercontent.com/assets/16030872/16362913/017a0bc2-3bbb-11e6-85f2-f11df7d5ec27.png)
![](https://cloud.githubusercontent.com/assets/16030872/16362915/05448e26-3bbb-11e6-9192-48694884d8e4.png)

**Comment by gorhill** [comment]
I will provide a fix for this.

**Comment by gorhill** [comment]
> You are right, will be included in the next update

Well that is bad for uBO users.

**Comment by IDKwhattoputhere** [comment]
> will be included in the next update

Where does it say that, @happysurf?

**Comment by happysurf** [comment]
@IDKwhattoputhere I think that the solutions provided on the forum will be included by the author list.

**Comment by happysurf** [comment]
The filter included on uBlock filters‎ `||aranzulla.it$inline-script` no more work in Aranzulla web site like in http://www.aranzulla.it/word-gratis-54587.html.
