### ISSUE TITLE
hondafinancialservices.com/account-management

### ISSUE THREAD

**Issue by jorgegonzalez** [uBlockOrigin/uAssets#7000]
### URL(s) where the issue occurs

`https://www.hondafinancialservices.com/account-management`

### Describe the issue

User is unable to login if `Fanboy’s Enhanced Tracking List`​​​​​​​​​ is enabled. 

### Screenshot(s)

![Screen Shot 2020-02-24 at 7 19 16 PM Redacted](https://user-images.githubusercontent.com/12901172/75203076-30b3d400-573b-11ea-863f-be88f1ce95e5.png)

### Versions

- Browser/version: Microsoft Edge (Chromium) 80.0.361.57 on macOS Catalina 10.15.3
- uBlock Origin version: v1.24.4

### Settings

I typically turn on every filter list, and so I was able to determine that `Fanboy’s Enhanced Tracking List` is the culprit through trial and error.

<img width="619" alt="Screen Shot 2020-02-24 at 7 21 22 PM" src="https://user-images.githubusercontent.com/12901172/75202949-db77c280-573a-11ea-94c3-fdf9763ad582.png">

**Comment by okiehsch** [comment]
@ryanbr fyi
`@@||hondafinancialservices.com/static/js/s_code.js$script,1p`


@jorgegonzalez 
`uAssets` will only fix issues reproducable with a default setup. `Fanboy’s Enhanced Tracking List`​​​​​​​​​ is not enabled by default.
I notified the maintainer of that list. In the meantime you can add 
`@@||hondafinancialservices.com/static/js/s_code.js$script,1p`
to your personal filter list to fix the issue on your end.

**Comment by jorgegonzalez** [comment]
Thank you!
