### ISSUE TITLE
notebookreview forums completely broken (only shows plain text)

### ISSUE THREAD

**Issue by Leon422** [uBlockOrigin/uAssets#7002]
`http://forum.notebookreview.com/threads/nvidia-optimus-reduces-gaming-performance.828776/page-5`

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

The forum is shown in plain text only

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: Firefox 73.0.1
- uBlock Origin version: v1.25.0

### Settings

Default settings

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
`@@||xenforo-lb.techtarget.com^$css,domain=forum.notebookreview.com`

**Comment by Leon422** [comment]
Still getting the issue, is the fix not live yet?

**Comment by uBlock-user** [comment]
force update unbreak list

**Comment by Leon422** [comment]
> 
> 
> force update unbreak list

Fixed, thanks!
