### ISSUE TITLE
hepsiburada.com doesn't work

### ISSUE THREAD

**Issue by mbnoimi** [uBlockOrigin/uAssets#7005]
### URL(s) where the issue occurs

hepsiburada.com

### Describe the issue

uBlock breaks down all the website but in case of manipulating filters something goes right while others still wrong for that I think this issue related to filters.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/284547/75336902-0a0dae80-589d-11ea-8c4f-126e3e40a1c7.png)

### Versions

- Browser/version: 73.0.1 (64-bit)
- uBlock Origin version: 1.25.0

### Settings

- I use the default settings except I just added some extra filter lists
![image](https://user-images.githubusercontent.com/284547/75337448-16463b80-589e-11ea-89c4-76a56ae30044.png)

**Comment by okiehsch** [comment]
Caused by cnameUncloak.
`@@||cdx.cedexis.net^$domain=hepsiburada.com`
"works" on my end.

**Comment by mbnoimi** [comment]
>  "works" on my end.

it works on my end too.
Thank you @okiehsch . Now this issue will be fixed on the next release of uBO or I've to always use this filter?

**Comment by mapx-** [comment]
force update unbreak list

**Comment by mbnoimi** [comment]
I've similar problem for
https://www.jula.no/

**Comment by mapx-** [comment]
I get no issue on `jula`

**Comment by mbnoimi** [comment]
I have a problem with `jula` on my end
![image](https://user-images.githubusercontent.com/284547/75354360-e60e9500-58bd-11ea-98de-f295e4e05a59.png)

**Comment by mbnoimi** [comment]
This is after disabling uBO
![image](https://user-images.githubusercontent.com/284547/75354478-13f3d980-58be-11ea-874a-55b6da6e0928.png)

**Comment by mapx-** [comment]
try updating all the lists => purge all caches + update

**Comment by mbnoimi** [comment]
> try updating all the lists => purge all caches + update

Done that. Didn't fix the issue

**Comment by mapx-** [comment]
open the logger, refresh the page, select only the blocked items, post them here

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/75399794-833cee00-58fd-11ea-9258-5c1926a7ec07.png)
Site looks fine with `uBO` enabled on my end.
