### ISSUE TITLE
"has" selector is not working

### ISSUE THREAD

**Issue by finejustice** [uBlockOrigin/uAssets#7009]
### URL(s) where the issue occurs

`https://gall.dcinside.com/mgallery/board/lists/?id=manjuugame&exception_mode=recommend`

### Describe the issue

I created custom filter like below:
gall.dcinside.com##tr:has([user_name$="운영자"])
It works in element zapper mode (see secreenshot below), but it does not works when it added to "My Filters". 
The <tr> element should be filtered but is shown.
last known working version: 1.22.4
the problem is reproduced from version 1.23.0

### Screenshot(s)
![image](https://user-images.githubusercontent.com/5276596/75362638-648a2780-58fc-11ea-9507-017814718bef.png)

### Versions

- Browser/version: Waterfox  	2020.01
- uBlock Origin version: 
last known working version: 1.22.4
the problem is reproduced from version 1.23.0

### Settings

My Filters
- gall.dcinside.com##tr:has([user_name$="운영자"])

**Comment by mapx-** [comment]
You should use uBO legacy
https://github.com/gorhill/uBlock-for-firefox-legacy/releases

**Comment by mapx-** [comment]
`Waterfox is not officially supported` => report to waterfox devs or use uBO legacy

**Comment by gwarser** [comment]
```
3f074d7908c405bb24aa9d303b010253ecbdec03 is the first bad commit
commit 3f074d7908c405bb24aa9d303b010253ecbdec03
Author: Raymond Hill <rhill@raymondhill.net>
Date:   Mon Sep 30 07:50:35 2019 -0400

    Use `self` when testing for `vAPI` presence
```

https://github.com/gorhill/uBlock/commit/3f074d7908c405bb24aa9d303b010253ecbdec03
