### ISSUE TITLE
ft.com blocked (with subscription)

### ISSUE THREAD

**Issue by radusw** [uBlockOrigin/uAssets#701]
### URL(s) where the issue occurs

`https://www.ft.com/`

### Describe the issue

ft.com blocks the site, even if you have a subscription. They will block the UI until you whitelist the domain.
What worked for me: blocking https://h2.ft.com/static-files/sp/prod/long/sp/sp-2.js  

### Screenshot(s)

![ScreenShot](https://i.imgur.com/BaPHULl.png)

### Versions

- Browser/version: Firefox 55.0.3
- uBlock Origin version: 1.14.8

### Notes

https://h2.ft.com/static-files/sp/prod/long/sp/sp-2.js needs to be blocked from what I can tell.

**Comment by okiehsch** [comment]
I do not have a subscription, does
`ft.com##script:inject(abort-on-property-read.js, _sp_._networkListenerData)`
work without breaking anything on your end?

**Comment by radusw** [comment]
Yes, that's perfect

**Comment by gotitbro** [comment]
@okiehsch @gorhill Interesting things, if you look at the JS provided by @radusw:
`https://h2.ft.com/static-files/sp/prod/long/sp/sp-2.js`


It seems like that js is trying to figure out exactly which adblocker is being used. Not sure though, you should definitely have a look at it.

A syntax formatted version of the js: `https://pastebin.com/Lku3GBHT`

**Comment by okiehsch** [comment]
@gotitbro ithe site uses `sourcepoint` and they alway use this kind of script for example
`http://sp148.global.ssl.fastly.net/messaging.js`
