### ISSUE TITLE
eliteacompanhantes.com.br/forum/ NSFW

### ISSUE THREAD

**Issue by Barack-Obama2** [uBlockOrigin/uAssets#7010]
### URL(s) where the issue occurs

`https://eliteacompanhantes.com.br/forum/` NSFW

### Describe the issue

There are many banners and pop-ups in this website that are not being blocked
`http://eliteacompanhantes.com.br/carousel-iframe/`
`#floatBnrElitehtml`

### Screenshot(s)

`https://i.postimg.cc/KYbQDvBw/Captura-de-tela-de-2020-02-26-17-27-08.png`

`https://i.postimg.cc/bwmHkHYD/Captura-de-tela-de-2020-02-26-17-26-20.png`

### Versions

- Browser/version: Firefox Browser 73.0.1 (64-bits)
- uBlock Origin version: uBlock Origin 1.25.0

### Notes

Here are the filters i suggest:
||eliteacompanhantes.com.br/bnr
||eliteacompanhantes.com.br/carousel-iframe
eliteacompanhantes.com.br###floatBnrElite

**Comment by mapx-** [comment]
report here (regional lists)
https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by mapx-** [comment]
@Alex-302
