### ISSUE TITLE
gp-guia.net NSFW 

### ISSUE THREAD

**Issue by Barack-Obama2** [uBlockOrigin/uAssets#7011]
### URL(s) where the issue occurs

`https://www.gp-guia.net/forum2015/`

### Describe the issue

There are a lot of banners in this website that are not being blocked:

`bserver.gp-guia.net/view/serv/www/dd/afrance.php?zoid=26`
`bserver.gp-guia.net/view/serv/www/dd/afrance.php?zoid=40`
`bserver.gp-guia.net/view/serv/www/dd/afrance.php?zoid=39`
`bserver.gp-guia.net/view/serv/www/dd/afrance.php?zoid=27`

### Screenshot(s)
`https://i.postimg.cc/KzQ41QD4/Captura-de-tela-de-2020-02-26-18-03-22.png`

`https://i.postimg.cc/mrBb7CD9/Captura-de-tela-de-2020-02-26-18-03-27.png`

### Versions

- Browser/version: Firefox Browser 73.0.1 (64-bits)
- uBlock Origin version: uBlock Origin 1.25.0

### Notes

I also opened a topic in `https://forums.lanik.us/viewtopic.php?f=62&t=44359` (EasyList).
Is is redundant for me to open a issue here for you guys to update the uBlock filters list too?
I had taught of this rule:
`||bserver.gp-guia.net$subdocument`
but then a better one was sugested by the user **intense**:
`*$subdocument,domain=gp-guia.net`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/blob/master/README.md

> If an issue can be fixed without using extended syntax, i.e. scriptlet injection, redirect, procedural cosmetic filters, etc. the issue will, as a rule of thumb, not be fixed by uAssets, because fixing it in EasyList if possible is preferable.

In this case it's about classic filters - to be added to easylist or - even better - to the regional list (spa, por: AdGuard Spanish/Portuguese maintained by adguard: https://github.com/AdguardTeam/AdguardFilters/issues)

**Comment by mapx-** [comment]
@Alex-302
