### ISSUE TITLE
forum.outerspace.com.br

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#7015]
### URL(s) where the issue occurs

`https://forum.outerspace.com.br/index.php`

### Describe the issue

Anti-adblock overlay.

### Versions

- Browser/version: Firefox stable
- uBlock Origin version: 1.25.0

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin lists

**Comment by uBlock-user** [comment]
already fixed, force update uBlock Filters list.
