### ISSUE TITLE
utaten.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7018]
### URL(s) where the issue occurs

`https://utaten.com/lyric/Eve/%E5%BF%83%E4%BA%88%E5%A0%B1/`

### Describe the issue
Right click & copy disabled

### Versions

- Browser/version: Firefox 73.0.1
- uBlock Origin version: 1.24.4

### Settings

- Default

### Notes

`utaten.com##+js(ra, onContextmenu|onselectstart)`
`utaten.com##.lyricBody:style(user-select: text !important; -moz-user-select: text !important; -webkit-user-select: text !important; -ms-user-select: text !important; -o-user-select: text !important)`

**Comment by lunaflight** [comment]
Asking for a relook on this issue since it seems to have broken again; reproduceable with the same link from the original post
