### ISSUE TITLE
amnews.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#7019]
### URL(s) where the issue occurs

`https://www.amnews.com/2020/01/14/boyle-names-itself-a-second-amendment-county/`

### Describe the issue

Overlapping text.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/75496561-87b1e700-598f-11ea-9df8-057187236667.png)

### Notes

Related to cosmetic filters. And I got this when trying to determine further, so...
![image](https://user-images.githubusercontent.com/12802056/75496650-ce9fdc80-598f-11ea-86aa-e8ba95242ace.png)

**Comment by terrorist96** [comment]
@okiehsch another example:
`https://www.jessaminejournal.com/`

**Comment by terrorist96** [comment]
@okiehsch `https://www.winchestersun.com/`
There's probably much more out there. Any idea on how to find them all?

**Comment by okiehsch** [comment]
No. ;)

**Comment by llacb47** [comment]
I'm in mobile so I don't know if these sites have the issue, but you can try: `https://publicwww.com/websites/%22_bwtp.userStatus%22/`

**Comment by okiehsch** [comment]
> if these sites have the issue

Thanks, those sites look fine on my end.

**Comment by terrorist96** [comment]
Why did you add `https://www.glasgowdailytimes.com/`? It looked fine for me.

**Comment by okiehsch** [comment]
Um, that was a mistake I looked at that site to see if it had the same issue.
Don't know how I managed to put it in the commit.
