### ISSUE TITLE
pomponik.pl

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#7024]
https://github.com/uBlockOrigin/uAssets/commit/c63c49da6fafa744decf01935916cd6c826d5d81

recover social share button:

`pomponik.pl##.is-facebook.share-link`

![obraz](https://user-images.githubusercontent.com/35370833/75570767-20139e80-5a58-11ea-9ded-4a92c791748e.png)

Possible add filter into uBO annoyance?

**Comment by uBlock-user** [comment]
How about `##.share-link` ?

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/203936ec4daeeb2a98e395295cf5424eedf9713f

**Comment by krystian3w** [comment]
Cut comment button and is generic. You should no hide "45" and white cloud.

**Comment by krystian3w** [comment]
`https://www.pomponik.pl/plotki/news-tomasz,nId,4352892`

**Comment by krystian3w** [comment]
Pop-up is back.

`https://www.pomponik.pl/plotki/news,nId,4366255`
