### ISSUE TITLE
remaxhd.com [NSFW]

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#7025]
### URL(s) where the issue occurs

`https://remaxhd.com`

### Describe the issue

Breakage: Unable to type in the search box on top right.

Annoyances: Unable to select text. Unable to drag text / links.

### Versions

- Browser/version: Firefox 73.0.1
- uBlock Origin version: 1.25.0

### Settings

Default + Annoyances Filter

**Comment by in4u** [comment]
Weirdly, the fix doesn't seem to work all the time. Try reloading the page in private browsing mode (or bypass cache using `Ctrl+F5`) a few times and on random occasions the fix fails to work.

**Comment by mapx-** [comment]
I tested again in FF / chrome, no issue on my end

**Comment by in4u** [comment]
Try this: Open the site in a private browsing window in Firefox. Check the fix. Reload with `F5` (do NOT bypass cache). Check the fix. Repeat by reloading (but NOT bypassing cache) 4-5 times. If that doesn't work, navigate to 4-5 different pages and check the fix on each page.

It definitely happens in my case. Unfortunately, I can't pinpoint exact steps to reproduce the issue since it's random.

**Comment by mapx-** [comment]
add this filter and test again
`remaxhd.com##^script:has-text(zfgloaded)`

**Comment by in4u** [comment]
Alright, after adding that filter the issue can no longer be reproduced. I guess it works!

**Comment by mapx-** [comment]
well, I'm able to reproduce in chrome too and that filter does not work (FF specific)

test this filter (disabling the filter above) and see if breaks something
`||remaxhd.com^$csp=script-src *`

**Comment by mapx-** [comment]
this 1 seems to work too
`remaxhd.com##+js(aopr, String.fromCharCode)`

**Comment by in4u** [comment]
Yup, both of them seem to work. Haven't noticed any other breakage either.

**Comment by in4u** [comment]
Now there's a breakage. The images are getting blocked.

**Comment by mapx-** [comment]
add & test both issues in FF / chrome
`||remaxhd.com^$csp=script-src *,badfilter`

**Comment by in4u** [comment]
I tested on FF and badfiltering that rule does brings back images but also causes the original problem of fix failing randomly as per your STR.

However, adding your ` remaxhd.com##+js(aopr, String.fromCharCode)` rule from before seems to work without breaking anything.

Not tested on Chrome since I don't use it.

**Comment by mapx-** [comment]
does this 1 still work for you ?
`remaxhd.com##^script:has-text(zfgloaded)`

**Comment by in4u** [comment]
Yup, still works.

**Comment by ghajini** [comment]
Chromium based browsers

`remaxhd.com##+js(acis, String.fromCharCode, 'shift')

in case popads wants to resurface that `undefined` crap
