### ISSUE TITLE
Fidelity 529 contribution page doesn't work with uBlock origin, due to dependence on ensighten.com "Bootstrap.js" script

### ISSUE THREAD

**Issue by dholbert** [uBlockOrigin/uAssets#7026]
### URL(s) where the issue occurs

`https://digital.fidelity.com/prgw/digital/familygifting/mlgLandingPage?uuid=e9f92d7e8ae54c61af7320a3dcf4d84f&ccsource=LK529NH`

...and similar URLs for gifting to Fidelity 529 education savings accounts, all of which start with "`https://digital.fidelity.com/prgw/digital/familygifting/`".

(Note: I don't know the owner of the above account, but I found it posted publicly at https://www.instagram.com/lippalife/ , so I'm assuming it's OK with them for me to post it publicly here as well.  I actually ran into this with a Fidelity 529 page for another child, and the owner of that page would like me to keep their URL private; hence, I searched and found this similar publicly-accessible one.)

### Describe the issue

If you click "Give a Gift", the page is supposed to navigate, but in fact nothing happens, and instead you get an error in the browser console: `ReferenceError: "Bootstrapper is not defined"`

If I open uBlock origin's logger, I can see that it's due to a rule from Peter Lowe's list, which blocks connections to ensighten.com.

### Screenshot(s)
![screenshot](https://user-images.githubusercontent.com/426803/75589798-9ef4e100-5a30-11ea-9cdc-26a5e977295d.png)

### Versions
- Browser/version: Firefox 73.0.1 (64-bit)
- uBlock Origin version: 1.25.0

### Settings

- No changes to default settings. This reproduces on a fresh Firefox profile with a fresh install of uBlock origin.

### Notes
I can work around it by adding this exception to "My Filters" in uBlock origin, to allow the script load:
```
@@||nexus.ensighten.com/fidelity/prod/Bootstrap.js$script,domain=digital.fidelity.com
```

(I'm not experienced at crafting/adding exceptions to uBlock origin lists so I'm not sure if that's an appropriately-specific/correct rule or not. It does work for me, though.)

**Comment by uBlock-user** [comment]
Broken because of `||ensighten.com^$3p` in EasyPrivacy.

**Comment by mapx-** [comment]
@ryanbr
