### ISSUE TITLE
nflstreams.me

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#703]
### URL(s) where the issue occurs

`http://www.nflstreams.me/505604/1/us-sports-tv-channels-live-stream-online.html`

### Describe the issue

Unblocked ads/ad elements. Clicking close opens popup

### Screenshot(s)

![untitled](https://user-images.githubusercontent.com/12802056/30562501-a55cdfb6-9c8c-11e7-931a-a7d2211b9a5c.png)

**Comment by okiehsch** [comment]
How do play the video, I can fix the "Stream in HD" and the popups with
````
nflstreams.me##script:inject(abort-on-property-write.js, Fingerprint2)
nflstreams.me##script:inject(nowebrtc.js)
nflstreams.me##script:inject(popads.net.js)
nflstreams.me##a[href^="http://www.downloadplayer2.com/sportstreaming/"]
nflstreams.me##a[href^="http://www.movie4all.co/VIPremium/index.html"]
````
but I do not see any video.

**Comment by terrorist96** [comment]
Probably that one doesn't work. This one works: `http://www.nflstreams.me/6455/1/nfl-network-live-stream-online.html`

**Comment by terrorist96** [comment]
Also apply whatever blocking to their sister sites (listed at the bottom of the homepage)
`https://www.mlbstream.me/ | https://www.nhlstreams.me/ | https://www.nbastreams.me/ | NFL Streams | https://www.fbstreams.me/`

**Comment by okiehsch** [comment]
Well, do the suggested filters work for you?
At `http://www.nflstreams.me/6455/1/nfl-network-live-stream-online.html`  I can play the video without any popups on my end.
![dgdfg](https://user-images.githubusercontent.com/16838044/30570859-351706fc-9ce4-11e7-9369-bb3d746baffc.JPG)

**Comment by terrorist96** [comment]
Yes, they work. I still see this though:

![image](https://user-images.githubusercontent.com/12802056/30570923-50fa5b4e-9cb2-11e7-9cff-29105890a460.png)

**Comment by okiehsch** [comment]
Hm, I don't, does it still trigger a popup or can you close  it without issue?

**Comment by terrorist96** [comment]
No pop up. Can be closed by hovering over (not clicking) the right X button:
![image](https://user-images.githubusercontent.com/12802056/30571166-db7ed4f6-9cb3-11e7-9259-7ee621e8e9b7.png)

Which then immediately moves the X further to the right (to trick you to click on the would-be ad):
![image](https://user-images.githubusercontent.com/12802056/30571172-eacd6c06-9cb3-11e7-9260-61ff228c814e.png)

Clicking that will then allow you to click the X on the left, and then it's all good.

**Comment by okiehsch** [comment]
I added 
````
fbstreams.me,mlbstream.me,nbastreams.me,nflstreams.me,nhlstreams.me##script:inject(abort-on-property-write.js, Fingerprint2)
fbstreams.me,mlbstream.me,nbastreams.me,nflstreams.me,nhlstreams.me##script:inject(nowebrtc.js)
fbstreams.me,mlbstream.me,nbastreams.me,nflstreams.me,nhlstreams.me##script:inject(popads.net.js)
fbstreams.me,mlbstream.me,nbastreams.me,nflstreams.me,nhlstreams.me##a[href^="http://www.downloadplayer2.com/sportstreaming/"]
fbstreams.me,mlbstream.me,nbastreams.me,nflstreams.me,nhlstreams.me##a[href^="http://www.movie4all.co/VIPremium/index.html"]
````
to fix the issues I can reproduce.

**Comment by SMed79** [comment]
The hiding filters should be added as generic
```
##a[href^="http://www.downloadplayer2.com/"]
##a[href^="http://www.movie4all.co/"]
```
https://pastebin.com/raw/a58J7qZU

**Comment by KiLL4FuNK** [comment]
Pop-up
