### ISSUE TITLE
Teslarati

### ISSUE THREAD

**Issue by Lustuccc** [uBlockOrigin/uAssets#7030]
### Prerequisites

- [x ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [ x] uBlock Origin with default lists/settings
    - [ x] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin
- [x ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

For about one week, this site loads only html titles, no pictures, no texts. Happens in Firefox on 2 computers, and on the new firefox for chrome.

### A specific URL where the issue occurs

`https://www.teslarati.com/`
### Steps to Reproduce

1. go to the url.
2. [Second Step]
3. [and so on...]

### Expected behavior:

Normal loading

### Actual behavior:

Only plain html titles

### Your environment

* uBlock Origin version: v1.25.0
* Browser Name and version: Firefox 73.0.1 (64 bits) 
* Operating System and version: Windows 10 1909 64 bits.
![Snipaste_2020-02-28_20-20-11](https://user-images.githubusercontent.com/47488776/75598173-cfa43d00-5a67-11ea-8e67-15e16a7cdae4.jpg)

**Comment by uBlock-user** [comment]
fixed, force update unbreak list.
