### ISSUE TITLE
mobilelegends.shop

### ISSUE THREAD

**Issue by AndnixSH** [uBlockOrigin/uAssets#7031]
### URL(s) where the issue occurs

https://mobilelegends.shop/FhEK

### Describe the issue

Countdown in indonesia

### Screenshot(s)

![image](https://user-images.githubusercontent.com/40742924/75607555-92d45680-5af8-11ea-8304-8293eb92068d.png)

### Versions

- Browser/version: Google Chrome 80.0.3987.122
- uBlock Origin version: 1.24.4

### Settings

- Show numbe on icon unchecked
- Peter Lowe’s Ad and tracking server list unchecked

### Notes

No notes

**Comment by krystian3w** [comment]
https://github.com/gorhill/uBlock/wiki/Resources-Library#nano-sibjs-
https://github.com/gorhill/uBlock/wiki/Resources-Library#nano-settimeout-boosterjs-

**Comment by krystian3w** [comment]
```
mobilelegends.shop##+js(nano-sib)
```

**Comment by krystian3w** [comment]
Also possible CSS only:

`mobilelegends.shop###download:style(display: block !important;)`
