### ISSUE TITLE
Ads are being replaced with error screens on YouTube

### ISSUE THREAD

**Issue by numbermaniac** [uBlockOrigin/uAssets#7034]
### URL(s) where the issue occurs

`https://www.youtube.com/watch?v=3S-GuR2P0E0` (any video with advertising should work)

### Describe the issue

If a video has ads, it looks like YouTube is trying to play the ad, then running into an error because ads are blocked.

### Screenshot(s)

![Screen Shot 2020-03-01 at 3 14 02 pm](https://user-images.githubusercontent.com/5206120/75619392-5889b880-5bcf-11ea-8241-0a3c973768b3.png)

### Versions

- Browser/version: Firefox 73.0.1
- uBlock Origin version: 1.25.0

### Settings

- Reset to default settings and it still happens.

### Notes

After a few seconds, it tried to play a 2nd video ad and showed the same error (but with a different ID). A few seconds after that, the actual video appeared - so the issue doesn't completely stop me from watching anything, but it does add a delay of maybe 10 - 15 seconds before I can start watching.

Here are the console errors, if it helps anyone:

![Screen Shot 2020-03-01 at 3 23 26 pm](https://user-images.githubusercontent.com/5206120/75619498-9f2be280-5bd0-11ea-8c2a-443d8a3a0c18.png)

**Comment by uBlock-user** [comment]
Reset to default settings, update the default lists and try again.

**Comment by numbermaniac** [comment]
Very strange. I did do exactly that, as I said in the issue, but for some reason doing it a second time might have fixed it. I'll close it for now, and reopen this if it comes back.

**Comment by okiehsch** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/fas0iy/youtube_is_suddenly_showing_ads_with_ublock_on/

Your not the only one who has noticed some problems with youtube in the las few days.
The exact reasons are unknown.
I can't reproduce ads or playback errors on my end.

**Comment by uBlock-user** [comment]
This happens only when you allow some scripts/xhrs from google's ad-server, but not ads, so something is allowed, but ads are still blocked, by resetting, whatever exception filter or a bad dynamic rule was making a connection to the ad-server now is firmly stopped and that error doesn't occur again.

**Comment by gwarser** [comment]
There are also reports form people without adblocker or with whitelisted YT:
- https://www.reddit.com/r/firefox/comments/fb23ph/youtube_error_on_loading_video_on_ff_72/
- https://www.reddit.com/r/youtube/comments/fawkgc/bug_im_constantly_getting_this_error_in_youtube/
- old thread on YT support forum, also happens with YT whitelisted and then without Adblock: https://support.google.com/youtube/thread/3903898?hl=en

Some people report that turning off personalized ads helped them:

>I was able to fix this by going to my google ad settings at `https://www.google.com/settings/u/0/ads` and turning off personalized ads. It fixed my problem so I turned it back on and the problem stayed fixed.

https://support.google.com/youtube/thread/3903898?hl=en

Some other that disabling hardware acceleration also helps: https://support.google.com/youtube/thread/10329866?hl=en

**Comment by uBlock-user** [comment]
Those must be different then. Those are not fixable by updating filterlists and reseting to default settings. This one is the type where the user made an error and as a consequence sees playback errors. I have this kind of issue on reddit so many times.

**Comment by numbermaniac** [comment]
Since yesterday I've been having this issue again. Happens on just about any video that has ads before the video. My guess is that YouTube changed something recently, but I don't know whether it's an issue that is fixable by uBO.

**Comment by okiehsch** [comment]
> There are also reports form people without adblocker or with whitelisted YT:
https://www.reddit.com/r/firefox/comments/fb23ph/youtube_error_on_loading_video_on_ff_72/
https://www.reddit.com/r/youtube/comments/fawkgc/bug_im_constantly_getting_this_error_in_youtube/
old thread on YT support forum, also happens with YT whitelisted and then without Adblock: https://support.google.com/youtube/thread/3903898?hl=en

I don't think it has anything to do with `uBO`.
I can use youtube without issue.

**Comment by dojima** [comment]
I'm having this issue only while 'uBlock filters' under the Built-in section is checked.  The moment I uncheck this filter and refresh the page, the video loads fine, and there is no advertisement.

**Comment by mapx-** [comment]
Update uBO lists and test again. If still does not work provide the video / page link

**Comment by dojima** [comment]
Have done so many times, but tried again just to be sure.  Same issue.  The YouTube video in question is https://www.youtube.com/watch?v=ZzUkObS_Yvs.  I'm also using Chromium 80.0.3987.87 64-bit, if that's relevant.

**Comment by mapx-** [comment]
wow, right now I got this message from YT (and the video is running fine)

> "Adblock" prevents Local YouTube Downloader from working. So it is recommended to use "uBlock Origin" instead, and uninstall "Adblock".

**Comment by llacb47** [comment]
Always test on default setup 😆

**Comment by dojima** [comment]
Troubleshooting it a bit more, it seems to be some strange conflict with those uBlock filters and another extension I have called AutoplayStopper.  If I disable AutoplayStopper, the video works fine (although it automatically starts playing, of course).  Weird.

**Comment by mapx-** [comment]
> Always test on default setup 😆

testing chrome / brave, but on brave I have that downloader ;)

**Comment by gwarser** [comment]
> I guess is not from YT itself but maybe from tampermonkey userscript `Local YouTube Downloader` !?

https://www.reddit.com/r/uBlockOrigin/comments/fn3i5v/need_help_blocking_the_adblock_message_from_the/

**Comment by gwarser** [comment]
@mapx- video blocked for me on https://www.reddit.com/r/youtubehaiku/comments/fnhsjr/poetry_florida_vs_the_world/

I see 

    https://www.youtube.com/get_video_info?html5=1&video_id=iAIuaN9D7yA&cpn=7tsCzYR_wwo1YuL3&eurl=https%3A%2F%2Fwww.redditmedia.com%2Fmediaembed%2Ffnhsjr&el=embedded&hl=en_US&sts=18338&lact=8&c=WEB_EMBEDDED_PLAYER&cver=20200319&cplayer=UNIPLAYER&cbr=Firefox&cbrver=76.0&cos=X11&width=600&height=338&ei=ftR4Xu-3Lo-GyAWQkZSQCA&iframe=1&embed_config=%7B%7D&playerretry=2

Upper case `EMBEDDED`? uBO is case-sensitive in query parameters?

**Comment by llacb47** [comment]
Works for me (Nano)?

![image](https://user-images.githubusercontent.com/16567977/77334030-a8edc500-6cfa-11ea-9064-f38e8a184c75.png)

**Comment by gwarser** [comment]
And it also have lower-case `embedded` (I did not notice). Why it does not work for me then?

**Comment by mapx-** [comment]
working fine for me
`https://www.youtube.com/get_video_info?html5=1&video_id=iAIuaN9D7yA&cpn=BGlfGsk1EQkKMgwe&eurl=https%3A%2F%2Fwww.redditmedia.com%2F&el=embedded&hl=en_US&sts=18338&lact=3&c=WEB_EMBEDDED_PLAYER&cver=20200319&cplayer=UNIPLAYER&cbr=Chrome&cbrver=81.0.4044.69&cos=Windows&cosver=10.0&width=692&height=389&authuser=0&ei=TNh4Xpb8Jsru1gLBv4XoCQ&iframe=1&embed_config=%7B%7D&ancestor_origins=https%3A%2F%2Fwww.redditmedia.com%2Chttps%3A%2F%2Fwww.reddit.com`

**Comment by gwarser** [comment]
Then must be something on my side, sorry.

**Comment by llacb47** [comment]
since there is a lowercase `embed_config` the filter `@@||youtube.com/get_video_info?*embedded$xmlhttprequest,1p` could be changed to `@@||youtube.com/get_video_info?*embed$xmlhttprequest,1p` if needed

**Comment by mapx-** [comment]
@numbermaniac 
- Are you watching the video on YT page ?
- open the logger, refresh YT page, select on logger page only the blocked elements
- provide the screenshots with the blocked elements

Try
```
*$xhr,redirect-rule=nooptext,domain=youtube.com
*$script,redirect-rule=noopjs,domain=youtube.com
```

**Comment by krystian3w** [comment]
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#match-case-modifier

IMO no exist in uBo.

**Comment by lassekongo83** [comment]
NanoDefender can also be an issue apparently. https://www.reddit.com/r/Adblock/comments/fqzg3k/youtube_playback_error_while_using_nanodefender/

**Comment by mapx-** [comment]
@jspenguin2017

**Comment by jspenguin2017** [comment]
@lassekongo83 @mapx- That's not possible, YouTube is whitelisted. I use YouTube everyday and I never encountered any issues.

**Comment by jspenguin2017** [comment]
`youtu.be` and `youtube.com` are both whitelisted in ND. Does YouTube have other domains?

**Comment by jspenguin2017** [comment]
@lassekongo83 @mapx- 

`youtu.be` and `youtube.com` are both whitelisted in ND. Unless YouTube has other domains, that's not possible. 

Also, I use YouTube everyday and I have never encountered any issues.

**Comment by mapx-** [comment]
@numbermaniac update uBO filters list + easylist and test again

**Comment by krystian3w** [comment]
Maybe video banned/removed on YT

![obraz](https://user-images.githubusercontent.com/35370833/78046527-8d785f00-7377-11ea-91e8-d7a3f1e81c15.png)

```
http://www.zobaczfilm.com/film/664-365-dni-2020-2020-lektor-pl.html
```

**Comment by llacb47** [comment]
The site didn't embed right.

![image](https://user-images.githubusercontent.com/16567977/78048095-3d81a400-7347-11ea-9da9-a38933670897.png)

What they embedded: `https://www.youtube.com/embed/J79D3hny`

What they meant to: `https://www.youtube.com/embed/J79D3hny-e8`
