### ISSUE TITLE
False positive url blocking via CNAME

### ISSUE THREAD

**Issue by HanabishiRecca** [uBlockOrigin/uAssets#7039]
### Description

False positive url blocking via CNAME. For example:
![image](https://user-images.githubusercontent.com/13597663/75631972-59dfd300-5c19-11ea-97d7-7d5358f1ee39.png)

Google fonts blocked at ALL sites. `||gstaticadssl.l.google.com^$3p` blocks `fonts.gstatic.com` which obviously is not intended.

Also exclusion rule `@@||fonts.gstatic.com` can't override this behavior. And this is the real problem.

### Versions

* Browser/version: Firefox 74b9 (developer)
* uBlock Origin version: 1.25.0

**Comment by llacb47** [comment]
Read: https://github.com/gorhill/uBlock/releases/tag/1.25.0

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by HanabishiRecca** [comment]
@llacb47 ok then. Sorry, I don't noticed latest changes.
But I don't see any option such as "Enable / disable CNAME matching". I've also tried to exclude url by the custom rule `@@||fonts.gstatic.com` but it doesn't work. So seems like there is nothing EasyList maintainers can do.

**Comment by HanabishiRecca** [comment]
Fortunately dynamic rule `* fonts.gstatic.com * allow` works and able to override CNAME rules.

![image](https://user-images.githubusercontent.com/13597663/75632640-e7bebc80-5c1f-11ea-81a7-a18164e7ba87.png)

**Comment by llacb47** [comment]
Related: https://github.com/lightswitch05/hosts/issues/136

**Comment by uBlock-user** [comment]
> I've also tried to exclude url by the custom rule @@||fonts.gstatic.com but it doesn't work

That wouldn't work because that domain is not blocked, this will -- 

```
||gstaticadssl.l.google.com^$3p,badfilter
||gstaticadssl.l.google.com^$3p,domain=~youtube.com
```

**Comment by HanabishiRecca** [comment]
@uBlock-user this is obvious. But looks like `gstaticadssl.l.google.com` is the actual ad-service url.

**Comment by mapx-** [comment]
maybe only for font type

**Comment by okiehsch** [comment]
Is that not already fixed by 
````
! https://github.com/gorhill/uBlock/commit/a16e4161de5b
! fonts.gstatic.com is alias of gstaticadssl.l.google.com (blocked by EasyList)
||gstaticadssl.l.google.com^$3p,badfilter
||gstaticadssl.l.google.com^$3p,~font
````
in `uBO-unbreak`?

**Comment by HanabishiRecca** [comment]
@okiehsch this doesn't fix the problem. `gstaticadssl.l.google.com` actually is not a bad filter and url should still be blocked. This is no more than dirty workaround.
Also this is just 1 exact url, such CNAME behavior can break many other sites.

**Comment by okiehsch** [comment]
The filter I mentioned blocks all 3rd-party `gstaticadssl.l.google.com` requests with the exception of `font` requests.

**Comment by HanabishiRecca** [comment]
@okiehsch this is still just workaround for this 1 particular case, not the fix for the problem itself.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/75634845-6e1fd200-5c11-11ea-9dcd-9f28196e626a.png)

As you can see no fonts are blocked on my end with a default setup. Are you sure that the  `uBO-unbreak` list is enabled.

**Comment by okiehsch** [comment]
> this is still just workaround for this 1 particular case, not the fix for the problem itself.

Could you clarify the problem as you see it?

**Comment by okiehsch** [comment]
If your issue is with blocking via CNAME as a whole you can disable it via advanced settings.
https://github.com/gorhill/uBlock/wiki/Advanced-settings#cnameuncloak
Set it to false to disable the setting.

**Comment by HanabishiRecca** [comment]
> As you can see no fonts are blocked on my end with a default setup. Are you sure that the `uBO-unbreak` list is enabled.

I've already fixed fonts for myself via dynamic rule https://github.com/uBlockOrigin/uAssets/issues/7039#issuecomment-593137743

> Could you clarify the problem as you see it?

At least it **must** consider exclusion filters. `@@||fonts.gstatic.com` **must** work.

> If your issue is with blocking via CNAME as a whole you can disable it via advanced settings.

CNAME is not bad feature itself. But it should obey the rules.

**Comment by okiehsch** [comment]
> At least it must consider exclusion filters. @@||fonts.gstatic.com must work.

I don't see how this is possible and that would be a uBO-core issue and not a `uAssets` issue.
@gorhill

**Comment by uBlock-user** [comment]
> At least it must consider exclusion filters. @@||fonts.gstatic.com must work.

That's not how exception filter logic works.

**Comment by HanabishiRecca** [comment]
Hmm I found `cnameIgnoreExceptions` in advanced settings. It seems to be related to the problem. But switching it doesn't change anything.

**Comment by HanabishiRecca** [comment]
> That's not how exception filter logic works.

Maybe this should've been considered before implementing doubtful feature that can't be unbreaked?

**Comment by uBlock-user** [comment]
> Maybe this should've been considered before implementing doubtful feature that can't be unbreaked?

It's already unbroken with the unbreak list, the filter logic comes from [ABP syntax](https://adblockplus.org/filter-cheatsheet#exceptions) which has nothing to with uncloaking CNAMEs.

**Comment by okiehsch** [comment]
> implementing doubtful feature that can't be unbreaked?

You can disable the doubtful feature.

**Comment by llacb47** [comment]
> > That's not how exception filter logic works.
> 
> Maybe this should've been considered before implementing doubtful feature that can't be unbreaked?

Maybe you can be a little more polite?

**Comment by HanabishiRecca** [comment]
> uBlock-user closed this

> It's already unbroken with the unbreak list

> You can disable the doubtful feature.

Ya ya, 10/10 software development. Maybe we will try to resolve the issue? Pff who da hell cares 👍

**Comment by okiehsch** [comment]
The existing filter syntax does not allow for something like `@@||fonts.gstatic.com must work`.
So the best possible alternative is to disable the feature if you disagree with it's current implementation.

> Maybe we will try to resolve the issue?

This repo is for issues that can be fixed with the current filter syntax, your issue can't be fixed in this repo, it is not possible.

**Comment by HanabishiRecca** [comment]
> This repo is for issues that can be fixed with the current filter syntax, your issue can't be fixed in this repo, it is not possible.

Not mine decision
![image](https://user-images.githubusercontent.com/13597663/75635969-53af1e00-5c3c-11ea-8d8c-fc41e0ea2cf8.png)

I've just wanted to help. Do what you want guys.

**Comment by uBlock-user** [comment]
> Not mine decision

because you reported site breakage so instead of closing the issue, I transfered it here. This isn't a uBO issue.

**Comment by llacb47** [comment]
`Also exclusion rule @@||fonts.gstatic.com can't override this behavior. And this is the real problem.`

Arguably this was the original issue being reported, should this be reported on `uBlock-issues`?

**Comment by okiehsch** [comment]
I could transfer it back seeing as the OP basically suggests to update/upgrade the existing filter syntax but I already pinged **gorhill** so let's wait.

**Comment by uBlock-user** [comment]
> seeing as the OP basically suggests to update/upgrade the existing filter syntax 

I will transfer it back, since I transfered it here originally.
