### ISSUE TITLE
nibelungen-kurier.de [Anti-Adblock]

### ISSUE THREAD

**Issue by Scunkaneli** [uBlockOrigin/uAssets#7043]
### URL(s) where the issue occurs

`https://nibelungen-kurier.de/erster-bestaetigter-fall-von-corona-virus/`

### Describe the issue

Access to site not possible due to uBlock detection

### Versions

- Browser/version: Chrome v80
- uBlock Origin version: 1.24.4

### Notes

Site has updated their detection. I am not sure if the old rule `nibelungen-kurier.de##+js(set, __blockAds, true)` is still needed. 

In order to bypass the new detection, `nibelungen-kurier.de##+js(set, window.nlf.custom.userCapabilities, false)` works. Relevant detection code can be found in lines 548f. at `https://nibelungen-kurier.de/wp-content/themes/wp-bold109/custom_user.js?ver=1.0.5`

**Comment by okiehsch** [comment]
Thanks.
