### ISSUE TITLE
fstore.biz, uploadfree.info and freeupload.info

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#7049]
### URL(s) where the issue occurs

`https://fstore.biz/file/DE75340792D6
`
### Describe the issue

Ublock currently bypasses to show blue download button while countdown. The download button no longer working
Instead it will show links below download button after countdown

### Screenshot(s)

![image](https://user-images.githubusercontent.com/61142621/75758197-fb5b4780-5d33-11ea-8edc-dd05bf27e4b1.png)

### Versions

- Browser/version: Opera Version:67.0.3575.38
- uBlock Origin version: 1.23.0

### Settings

- All default

### Notes
I'm worried this changes might be server-sided. Can you try boost countdown to see if it works?

**Comment by mapx-** [comment]
addressed fstore, could you provide examples for the other 2 servers ?

**Comment by okiehsch** [comment]
Can you actually download the file?
I get an error message even if I disable `uBO`?

**Comment by mapx-** [comment]
I'm using the 3 alternative servers bellow not the main link

**Comment by LGLTeam** [comment]
try this one
they works basically same but with different domains
```
https://freeupload.info/file/8f04909F72725378276DD220b747F0b6
https://uploadfree.info/file/8f04909F72725378276DD220b747F0b6
```

**Comment by LGLTeam** [comment]
don't click on blue download button

**Comment by okiehsch** [comment]
From the OP
> The download button no longer working

> don't click on blue download button

I am confused.

The download button does not work no matter what  on my end. 
The alternative download servers work even if you don't comment out the  one filter.

**Comment by mapx-** [comment]
mmhmm , right, I'm confused too now

**Comment by uBlock-user** [comment]
> blue download button

No blue button found, I get the red download button.

**Comment by okiehsch** [comment]
>  I get the red download button.

After you solve the captcha and click continue?

**Comment by uBlock-user** [comment]
No, at the website itself

**Comment by LGLTeam** [comment]
Ok it's working !

**Comment by okiehsch** [comment]
Hm, well I am now even more confused. ;)
Can you download the file without using an alternative server?

**Comment by uBlock-user** [comment]
Nevermind, I found the blue download link, that's fake, so yeah don't click on it, better yet block the blue download button itself -- `freeupload.info###at-btn-download`

**Comment by LGLTeam** [comment]
I meant blue "Download now" button like the screenshot above
yeah they replaced the mirror page "Who are you?"

**Comment by uBlock-user** [comment]
Fixed with -- 

```
fstore.biz,uploadfree.info,freeupload.info##+js(nano-sib)
fstore.biz,uploadfree.info,freeupload.info###at-btn-download
```
