### ISSUE TITLE
Remove probably-obsolete rules in Annoyances

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7055]
Rules for `noodletowntranslated.com` in Annoyances filter (including one for KillAdBlock) seems to be no more needed as well as ones for `gordiando.com.br`. Also it seems `okaeriworld.com` is dead. Please check them.

**Comment by okiehsch** [comment]
`gordiando.com.br` still has the same issue in fact an additional filter is needed. ;)
