### ISSUE TITLE
quotev.com

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#7056]
### URL(s) where the issue occurs

`https://www.quotev.com/story/12370983/The-Kids-Arent-Okay`

### Describe the issue

Annoyance - text selection disabled

### Versions

- Browser/version: Firefox 73.0.1
- uBlock Origin version: 1.25.1rc2

### Settings

- All filters

### Notes

Any page starting with `/story/` are unselectable, even with CTRL+A

**Comment by mapx-** [comment]
working only for firefox:
```
quotev.com##*:style(-webkit-touch-callout: default !important; -webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)
quotev.com##+js(ra, onselectstart|ondragstart)
quotev.com##^style:has-text(::selection)
quotev.com##^script:has-text(document.body.onselectstart)
```

I cannot find something working in chrome

**Comment by mapx-** [comment]
However, for chrome you can click a paragraph and use ctrl-C => the text will be copied
It's working ctrl-A too
(highlighting is disabled)

**Comment by uBlock-user** [comment]
My scriptlet works, you can use that for a filter if you want a fix.

**Comment by JobcenterTycoon** [comment]
They disabled right click and hotkeys now
