### ISSUE TITLE
itorrents.org

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#7057]
### URL(s) where the issue occurs

`http://itorrents.org/torrent/C54FCD0B3C100C0495C9D21C4AAB591AC48F59CE.torrent`

or

`https://www.1337x.to/torrent/4329448/WIN-10-AIO-19H2-1909-Build-18363-657-With-Office-2019-More-Preactivated-Feb-2020-johdrxrt/`

and click on itorrents mirror

### Describe the issue

Tab closes after browser check

### Screenshot(s)

not applicable

### Versions

- Browser/version: Opera Version: 67.0.3575.38
- uBlock Origin version: 1.23.0

### Settings

- All default

### Notes

not applicable

**Comment by mapx-** [comment]
@LGLTeam  please don't post clickable links anymore
