### ISSUE TITLE
k-vid.net

### ISSUE THREAD

**Issue by KonoromiHimaries** [uBlockOrigin/uAssets#7059]
### URL(s) where the issue occurs

`https://k-vid.net/load.php?id=`

### Describe the issue

ads popup on the player page

### Versions

- Browser/version: ff latest
- uBlock Origin version: ubo latest

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/75956305-e5768f80-5eb7-11ea-811c-2b5a13cab881.png)

**Comment by KonoromiHimaries** [comment]
@mapx- try with proxy `https://www.proxysite.com/`

**Comment by mapx-** [comment]
working now (without any proxy), however I get no popup

**Comment by Yuki2718** [comment]
The link is obviously wrong, anyway tested several videos on k-vid.net with some different streaming servers and I see no popup. Fx 73.0.1 + uBO 1.25.0 with default settings.

**Comment by KonoromiHimaries** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/15143
