### ISSUE TITLE
viki.com new media player detects adblocker

### ISSUE THREAD

**Issue by michaelshumake** [uBlockOrigin/uAssets#7062]
### URL(s) where the issue occurs

`https://www.viki.com/videos/1116593v-strong-woman-do-bong-soon-special-episode-0`

### Describe the issue

Viki.com updated to a new media player that detects adblockers and no longer plays videos.

### Versions

- Browser/version: Firefox 73.0.1 (64-bit)
- uBlock Origin version: 1.25.0

**Comment by mapx-** [comment]
It was fixed days ago, did you update uBo filters ?

**Comment by michaelshumake** [comment]
I just now updated my filters, the player is still pausing to show an adblock warning and stops playing the video entirely after a few minutes.

**Comment by mapx-** [comment]
I tested in FF 73.0.1, still working on my end.
Did you test using the default settings / lists ? 
Some other blocking addon in your FF ?

**Comment by michaelshumake** [comment]
I tried disabling other addons, didn't work.
Then purged my filter cache in uBO and redownloaded the lists, it's working now!

Thanks for your help!

**Comment by lain566** [comment]
@mapx- Are you sure it is fixed?  I can reproduce anti adblock

![Anotación 2020-03-06 102734](https://user-images.githubusercontent.com/27441315/76070909-a0c12600-5f95-11ea-892d-ead1e57b5e04.png)

**Comment by mapx-** [comment]
still working on my end FF / chrome

**Comment by lain566** [comment]
So I'm the only one who can reproduce the anti adblock.
I have the solution, no need to whitelist,

**Comment by mapx-** [comment]
> I have the solution, no need to whitelist

I can test it, if is working for me too you could replace the current fix

**Comment by lain566** [comment]
I see the problem, I was trying it in Firefox with Tracking Protection enabled.

there you go, only one filter is necessary.
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=viki.com,badfilter
@@||viki.com^$ghide,badfilter
@@||viki.io/cms-uploads/uncategorized/ima3.js,badfilter
@@||pubads.g.doubleclick.net/gampad/ads*viki.com$xhr,domain=imasdk.googleapis.com,badfilter
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,redirect=noopjs,domain=viki.com,badfilter
*expire=$media,redirect=noopmp3-0.1s,domain=viki.com,badfilter

||imasdk.googleapis.com/js/sdkloader/ima3.js$script,redirect-rule=noop.js,domain=viki.com
```

**Comment by mapx-** [comment]
great ! add your changes

**Comment by vylmen** [comment]
Commit d9a6f37 makes the video player stuck, because null is not a function. This has the annoying side effect that myfilters are applied before ublock filters, so I cannot override it. I had to disable the filters, copy them and create my own override in myfilters to make things work again.

As a side note, i have a paid account with ads disabled and this now disables my viewing. Fix incoming.

**Comment by uBlock-user** [comment]
> Commit d9a6f37 makes the video player stuck

I can't reproduce that when I tested, video plays fine, how is it getting stuck exactly ? Does it happens when you're logged in only ?
