### ISSUE TITLE
dplay.dk

### ISSUE THREAD

**Issue by AndnixSH** [uBlockOrigin/uAssets#7064]
### URL(s) where the issue occurs

`https://www.dplay.dk/programmer/strgvagterne`

### Describe the issue

Ads are not blocked in player

### Screenshot(s)

![image](https://user-images.githubusercontent.com/40742924/76022762-12fb2180-5f28-11ea-8040-30ba9197c0b2.png)

### Versions

- Browser/version: Chrome 80.0.3987.122 (Officiel version) (64-bit)
- uBlock Origin version: 1.24.4

### Settings

- Show numbers on icon unchecked
- Peter Lowe’s Ad and tracking server list

### Notes
You can play any episodes you want

**Comment by mapx-** [comment]
> Velkommen! Du skal have et abonnement for at se det valgte program. Tilmeld dig nu, og få adgang til vores univers af dokumentarer, serier og reality

@DandelionSprout

**Comment by DandelionSprout** [comment]
`https://www.dplay.dk/programmer/kongsvik-helsesenter` seems to be another example page that requires neither payment or user accounts, and which hopefully shouldn't be region-locked either (hopefully).

**Comment by DandelionSprout** [comment]
Among the 6 entries I copied over from Frellwit during testing, two in particular seem to me to remove this specific ad (unless I'm screwing up heavily here):

```
@@||fwmrm.net/ad/$script,domain=dplay.dk
||dnitv.com^$media,domain=dplay.dk
```

I'll add those (or very similar) entries after I've finished eating my supper.

**Comment by mapx-** [comment]
only this filter needed on my side
`*$media,domain=dplay.dk,redirect=noopmp3-0.1s`

**Comment by DandelionSprout** [comment]
I'm pretty surprised that such a broad filter as `*$media,domain=dplay.dk,redirect=noopmp3-0.1s` would actually work (which it does), but I feel that the loading times are marginally smaller with the two entries I used above.
