### ISSUE TITLE
kissanime.com that involves with Cloudflare is looping forever until I disable ublock

### ISSUE THREAD

**Issue by Iaycomand** [uBlockOrigin/uAssets#7068]
### URL(s) where the issue occurs

`kissmanga.com`

### Describe the issue

loading screen looping forever in the screenshot provided below unless I disable ublock "and can turn it on again after".

### Screenshot(s)
![image](https://user-images.githubusercontent.com/39984795/76138544-e0e5de80-6051-11ea-9468-5b6b2e03ad6a.png)

### Versions

- Browser/version: Version 80.0.3987.132 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.24.4

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7067
