### ISSUE TITLE
telegraph.co.uk

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#707]
### URL(s) where the issue occurs

`http://www.telegraph.co.uk/news/2017/09/15/winners-insight-astronomy-photographer-year-2017-photo-competition/winners-insight-astronomy-photographer-year-2017-photo-competition/`

### Describe the issue

Anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/30727397-fdba9c9a-9f1e-11e7-9319-f07075c96eef.png)

**Comment by gotitbro** [comment]
@gorhill @okiehsch I thought these types of messages were allowed as they do not block content but only inform users about their adblock usage. Why has a filter been added here then?

**Comment by terrorist96** [comment]
It continuously pops up. It doesn't go away for good after clicking close.

**Comment by uBlock-user** [comment]
There's no such policy here. Easylist must have that.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/blob/master/README.md

> The rationale on whether to include a specific filter in one of uBO's own filter lists is the same as outlined by EasyList/EasyPrivacy policies, also taking into account whether a filter requires uBO's extended filter syntax.

**Comment by gotitbro** [comment]
@okiehsch And according to the EasyList policy and from what I have seen here till now anti adb messages that can be dismissed and do not block content have never been blocked. This is also backed by the fact that a filter for this site hasn't been added.

@gorhill Please clarify.

**Comment by uBlock-user** [comment]
Does that apply to filters for anti adblock scripts too ?

**Comment by okiehsch** [comment]
@gotitbro to clarify when I will add a filter to deal with an anti-adblock message.
If the message itself blocks legitimate content, like in this issue, I will add a filter.

If a message itself does not block legitimate content I consider it an annoyance and will not add a filter. for example https://github.com/uBlockOrigin/uAssets/issues/581
![ant](https://user-images.githubusercontent.com/16838044/30776318-92c7fa18-a0a4-11e7-8570-592d918e4120.JPG)

or `http://www.gamestar.de`
![anti](https://user-images.githubusercontent.com/16838044/30776340-a7d78996-a0a4-11e7-904b-44810c839291.JPG)


By the way, the filter I added is part of [Adblock Warning Removal List](chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=awrl-0), which links to 
https://easylist.to/2013/05/10/anti-adblock-guide-for-site-admins

**Comment by gotitbro** [comment]
@okiehsch Thanks for taking the time to explain really appreciate it. I was just trying to find the rationale behind decisions hope you don't mind.

**Comment by terrorist96** [comment]
`https://www.telegraph.co.uk/politics/2019/12/12/general-election-2019-vote-news-exit-polls-results-live-latest/`

Youtube video at top blocked. This fixes it but I don't think it's ideal.
`@@||static.telegraph.co.uk/telegraph-advertising/tmg-gpt.min.js$script,1p`

Any other ideas on how to fix?

**Comment by mapx-** [comment]
no other idea
