### ISSUE TITLE
Google fonts don't load on developer.android.com

### ISSUE THREAD

**Issue by sfan5** [uBlockOrigin/uAssets#7071]
### URL(s) where the issue occurs

`https://developer.android.com/reference`

### Describe the issue

Font missing resulting in incorrect looking page content.

### Screenshot(s)

![pic](https://user-images.githubusercontent.com/1042418/76145623-528e4e80-608b-11ea-982a-67912700b7e5.png)

### Versions

- Browser/version: Firefox 73.0.1 (64-Bit)
- uBlock Origin version: uBlock Origin v1.25.0

### Notes

This is caused by the following EasyList rule:
![pic](https://user-images.githubusercontent.com/1042418/76145659-cd576980-608b-11ea-8c56-c1893ab8606d.png)

Related filters that fix the same issue in a different context:
https://github.com/uBlockOrigin/uAssets/blob/f3530bc29fe42549a5d8f41a2993efa5c90d26a1/filters/unbreak.txt#L2942-L2945

**Comment by uBlock-user** [comment]
Does adding `||gstaticadssl.l.google.com^$3p,~font,~xhr` fix it ?

**Comment by sfan5** [comment]
No, adding that rule in the "My Filters" tab doesn't fix it.

**Comment by llacb47** [comment]
Add this too: ` ||gstaticadssl.l.google.com^$3p,~font,badfilter`
