### ISSUE TITLE
rfi.fr

### ISSUE THREAD

**Issue by codl** [uBlockOrigin/uAssets#7072]
### URL(s) where the issue occurs

`http://www.rfi.fr/en/`

### Describe the issue

The site's menu starts open and obscures the page. Clicking the menu button only pushes the menu downwards.

### Screenshot(s)

How it is:
![](https://user-images.githubusercontent.com/315139/76152527-ceef5480-60c0-11ea-81a2-6ea5bb864663.png)

With cosmetic rules disabled:
![](https://user-images.githubusercontent.com/315139/76152519-c3039280-60c0-11ea-87aa-ec99a2acb55f.png)

### Versions

- Browser/version: Firefox 73.0.1
- uBlock Origin version: v1.25.0

### Notes

It seems to be coming from a cosmetic rule in the annoyances list.

**Comment by mapx-** [comment]
> It seems to be coming from a cosmetic rule in the annoyances list.

which one ? uBo annoyances ? fanboy's annoyances ?

**Comment by mapx-** [comment]
ok, it seems to be 
`rfi.fr##header:style(position:static !important;)`

**Comment by codl** [comment]
Wow that was fast, thank you!

**Comment by krystian3w** [comment]
`##body.u-header-sticky .o-header:style(position: absolute !important;)`

**Comment by krystian3w** [comment]
@yourduskquibbles
