### ISSUE TITLE
Add DuckDuckGo's Tracker Radar

### ISSUE THREAD

**Issue by nunesgh** [uBlockOrigin/uAssets#7073]
DuckDuckGo has released a new data set of cross-site trackers, [Tracker Radar](https://github.com/duckduckgo/tracker-radar). It is automatically generated and maintained through continuous crawling and analysis, as described in their [blog post](https://spreadprivacy.com/duckduckgo-tracker-radar/).

The data set is publicly available for generating tracker block lists and may be a good addition to uBlock Origin's set of third party tracker lists.

**Comment by llacb47** [comment]
Not a good fit in my opinion

**Comment by gwarser** [comment]
Surrogates can be interesting, but not included (categories and breakage data also missing). Rules are regexes (simple, but sometimes highly specific). Someone can create filter list basing on this, but this is not something that can be used directly.

**Comment by uBlock-user** [comment]
> Someone can create filter list basing on this

https://gitlab.com/michelt/ddg-tracker-radar-hostfile/-/raw/master/hostlist-full.txt

**Comment by nunesgh** [comment]
> Not a good fit in my opinion

@llacb47 would you mind elaborating?

**Comment by llacb47** [comment]
> > Not a good fit in my opinion
> 
> @llacb47 would you mind elaborating?

Sure, the list seems to make no distinction between CDNs and trackers, and blocking CDNs, especially with CNAME uncloaking in uBO, would have many false positives. 

https://github.com/duckduckgo/tracker-radar/issues/2#issuecomment-595450185

**Comment by gwarser** [comment]
> > Someone can create filter list basing on this
> 
> [gitlab.com/michelt/ddg-tracker-radar-hostfile/-/raw/master/hostlist-full.txt](https://gitlab.com/michelt/ddg-tracker-radar-hostfile/-/raw/master/hostlist-full.txt)

This is just stupid. Many of these domains are just normal web pages. Even blndly blocking them as 3p will break lot of stuff.

**Comment by uBlock-user** [comment]
That's that they compiled, lots of domains who are not trackers or ad-servers are present.

**Comment by gwarser** [comment]
If assumed that everything should be blocked, it can be converted to very inefficient Regular Expression filter by:

    for F in *.json; do jq --raw-output '.resources[] | "/\(.rule)/$third-party"' "$F"; done

**Comment by yokoffing** [comment]
Here the the filter list the [Vivaldi browser](https://vivaldi.com/) is using for its tracker blocking, based on Duckduckgo's Tracker Radar: `https://downloads.vivaldi.com/ddg/tds-v2-current.json`.

**Comment by gorhill** [comment]
> Surrogates can be interesting

They come from uBO, see <https://twitter.com/gorhill/status/1273263811001290752>. They might have some which are not from uBO, in which case it would been nice that they contribute them to uBO as a good gesture given that they use uBO's surrogates in their extension.

**Comment by Yuki2718** [comment]
> 
> , they are all from uBO.

That means they violated GPL v3.

**Comment by gorhill** [comment]
After I posted the above it occurred to me DDG Privacy Essentials (DDGPE) gets those surrogate scripts in a way that is forbidden by Mozilla, i.e. from a remote server.

I can't see any good reason for doing so -- these are packaged in uBO as [web-accessible-resources](https://github.com/gorhill/uBlock/tree/master/src/web_accessible_resources), meaning they are injected safely (i.e. without triggering CSP violations) and with [complying with Mozilla policy of no remote code](https://github.com/gorhill/uBlock/commit/126110c9a0a0630cd556f5cb215422296a961029).

It's as if DDG went out of its way to avoid committing the uBO code in their repo, and worst, Mozilla is making [an exception](https://github.com/gorhill/uBlock/commit/126110c9a0a0630cd556f5cb215422296a961029#commitcomment-23987144) with DDGPE (which is a _recommended_ extension) by allowing them to download these scripts from a remote server from within their extension.

**Comment by gwarser** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1653403

**Comment by gwarser** [comment]
`https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/469`
