### ISSUE TITLE
katalog.trojmiasto.pl

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#7074]
#5677 

`https://katalog.trojmiasto.pl/op12779/`

![obraz](https://user-images.githubusercontent.com/35370833/76165230-99487b00-6155-11ea-8605-27795f74a747.png) | ![obraz](https://user-images.githubusercontent.com/35370833/76165251-c563fc00-6155-11ea-833c-620c6b315aaa.png)
--- | ---
normal mode | Private mode

> W trosce o wiarygodność opinii, dbamy o to, aby mogli wystawiać je użytkownicy, którzy regularnie korzystają z portalu Trojmiasto.pl. **Dodawanie opinii w trybie prywatnym/incognito nie jest możliwe.** Zostań naszym stałym czytelnikiem bądź zmień tryb ustawień. 

> In order to ensure the credibility of opinions, we make sure that they can be issued by users who regularly use the Trojmiasto.pl portal. **Adding opinions in private/incognito mode is not possible.** Become our regular reader or change the settings mode. 

IMO similar troubles as repair right click / selection - Polish law limitation.

**Comment by mapx-** [comment]
Even disabling uBO I get the second screen

**Comment by krystian3w** [comment]
In normal mode you are detected as incognito?

Maybe geolocked for Poland and very good blocked use VPN/Proxy - vnc / teamviewer needed?

**Comment by krystian3w** [comment]
Also try no use "<kbd>Firefox containers</kbd>" - generate false alarm about private mode.

**Comment by mapx-** [comment]
Tested again in chrome, getting a polish ip via hola, same baheviour.
Do you have a working filter ?

**Comment by krystian3w** [comment]
Need bake/create cookies, website check only cookies exsist.
