### ISSUE TITLE
Youtube shows video ad error and a banner ad at the homepage

### ISSUE THREAD

**Issue by Iaycomand** [uBlockOrigin/uAssets#7075]
### URL(s) where the issue occurs

`https://www.youtube.com/`

### Describe the issue

the error doesn't go with refreshing page the banner just show up at all time.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/39984795/76166956-82ad1e80-616b-11ea-99fc-5e3686517fb9.png)

### Versions

- Browser/version: google chrome Version 80.0.3987.132 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.24.4

**Comment by krystian3w** [comment]
Self-promotion.

**Comment by uBlock-user** [comment]
Is that the new youtube layout ?

**Comment by uBlock-user** [comment]
Can you pick the element with the picker ?

**Comment by Iaycomand** [comment]
I don't understand.

**Comment by krystian3w** [comment]
https://github.com/gorhill/uBlock/wiki/Element-picker

**Comment by Iaycomand** [comment]
Done, strange that it appears recently.

**Comment by uBlock-user** [comment]
So were you able to pick the element ? if not cosmetic filtering is disabled, which can cause that, and in that case, enable cosmetic filtering.

**Comment by gwarser** [comment]
@uBlock-user "Parse and enforce cosmetic filters" works like this. Cosmetic filters from lists are not enforced, but "My filters" work.

**Comment by uBlock-user** [comment]
@gwarser My question was whether he disabled cosmetic filtering or not, but in a round-about way.

**Comment by gwarser** [comment]
@uBlock-user yes, but "Disable cosmetic filtering" will broke Element Picker, where "Parse and enforce cosmetic filters" will not.
