### ISSUE TITLE
blackmod.net

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#7079]
### URL(s) where the issue occurs

`https://blackmod.net
`
### Describe the issue

It gets stuck on checking browser. It works if you disable adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/61142621/76195669-1ec93b00-61e9-11ea-97d1-7842abf294d1.png)

### Versions

- Browser/version: Opera Version: 67.0.3575.53
- uBlock Origin version: 1.23.0

### Settings

- All default

**Comment by uBlock-user** [comment]
@AdamWr fyi, `bab-defuser` needs to be removed from Adguard Base as well.

**Comment by AdamWr** [comment]
Done, thank you.
