### ISSUE TITLE
BlockAdBlock

### ISSUE THREAD

**Issue by RockyMM** [uBlockOrigin/uAssets#708]
### URL(s) where the issue occurs

`http://syriancivilwarmap.com/` 

### Describe the issue
After the page loads, the entire page is replaced with the info about disabling adblocker.

### Screenshot(s)
![screenshot](https://user-images.githubusercontent.com/1906065/30739818-ff1f3670-9f8e-11e7-9615-a6c754c9b5ad.png)

### Versions

- Browser/version: Firefox Windows 55.0.3 (64-bit)
- uBlock Origin version: uBlock Origin 1.14.10

### Settings
- all on default

### Notes

/

**Comment by mapx-** [comment]
add
`@@||syriancivilwarmap.com^$generichide`

**Comment by SMed79** [comment]
@mapx- you mean
`syriancivilwarmap.com##script:inject(bab-defuser.js)`

**Comment by mapx-** [comment]
It works only with generichide for me. When generichide it works it's preferred over injecting scriptlets.

**Comment by gotitbro** [comment]
When generichide works it's preferred over injecting scriptlets.
@mapx- Why so? Isn't generichide is limiting the functionality of the blocker?
