### ISSUE TITLE
notebookreview forums - can't reply to threads

### ISSUE THREAD

**Issue by Leon422** [uBlockOrigin/uAssets#7081]
I am once again asking you to fix this website lol

`http://forum.notebookreview.com/threads/is-there-a-gaming-laptop-that-doesnt-have-fans-that-are-so-high-pitched.832057/
`
### Describe the issue

The reply box at the bottom of the page can't be interacted with (You need to have an account and be logged in in order to test this)

### Versions

- Browser/version: Firefox 73.0.1
- uBlock Origin version: 1.25.0

### Settings

Default

**Comment by mapx-** [comment]
I got an account and posted in that same thread (`test test`) 
What's the real issue ?

**Comment by mapx-** [comment]
USe the default filter lists and test again

**Comment by Leon422** [comment]
> 
> 
> USe the default filter lists and test again

I am using the default filters. The reply box appears like this and I can't interact with it.
![Captura](https://user-images.githubusercontent.com/15913880/76244665-6cb66100-6232-11ea-87d7-a0d60e75f712.PNG)
