### ISSUE TITLE
Remove browser-update.org from privacy list or reclassify as annoyance

### ISSUE THREAD

**Issue by josselex** [uBlockOrigin/uAssets#7084]
Browser-update.org is not tracking users in any way. As such I think it should be removed from the privavy list.

Browser-update.org is an open source project to inform about insecure and unsupported old browsers.
No identifying cookie is set, see
https://github.com/browser-update/browser-update/wiki/Privacy

The only cookie set always has the value browserupdateorg=pause and is justed used to show a message once per visitor in order not to annoy visitors.

It may be filed unter annoyances, but I think we are trying to be less annoying than all custom solutions that websites implement, and think that it would be better if it is not blocked.

Some discussion on what we do is already here:
https://github.com/uBlockOrigin/uAssets/issues/5795#issuecomment-549251136

**Comment by uBlock-user** [comment]
This was already discussed once via internal discussion, so whats changed after all these months ?

**Comment by okiehsch** [comment]
> Some discussion on what we do is already here:
#5795

`browser-update-org` has since been added to `EasyPrivacy`.
![image](https://user-images.githubusercontent.com/16838044/76305078-c36c7b00-62c4-11ea-95bf-535bde053c80.png)
https://github.com/easylist/easylist/commit/2a028cbeb7692f1c155208e951f53664aa656a49

**Comment by uBlock-user** [comment]
@okiehsch In that case, we should remove it from uBO-Privacy.

**Comment by okiehsch** [comment]
Yes, it has become redundant.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/41d7811256fdeacf088c618df598f7734cab140b

**Comment by josselex** [comment]
> This was already discussed once via internal discussion, so whats changed after all these months ?

I just wanted to say that we do not track in anyway and respect privacy. That's why it should not be filed under privacy. I guess this is useful information.

**Comment by okiehsch** [comment]
`browser-update.org` is also blocked  and in [`Adguards Tracking Protection filter`](https://github.com/AdguardTeam/AdguardFilters/blob/ee206278af8002c519de8386e90ff61be2821e76/SpywareFilter/sections/tracking_servers.txt#L741)

**Comment by uBlock-user** [comment]
> I just wanted to say that we do not track in anyway and respect privacy. 

You collect **_some data_** no matter how insiginificant you think it may be, and obviously other filter lists disagree with you too.

**Comment by josselex** [comment]
But we do not track! For every 1000th visitor we record which browser was used. That's all (see the code). And fo me it seems the lists copy from each other.

**Comment by okiehsch** [comment]
> and for me it seems the lists copy from each other.

Well, we did not copy it, we added it because at the time `EasyPrivacy` did not block it.
@ryanbr do you want to chime in?

**Comment by ryanbr** [comment]
A third-party script checking user agents and setting cookies, that is tracking. It's staying

**Comment by josselex** [comment]
But we are not tracking.
1) The cookie is the same for all users. It has no specific information. it just says: browserupdateorg=pause.
So we can not identify users in any way.
2) The cookie only lasts 24 hours. It is only set to the current domain. We cannot track in any way across domains.
3) We do not record data except for a random sample of the browser used for every 1000th user. This can not be used in any way to track anybody. You can check the script to verify this.

Please, if you say it's tracking, say why or what your definition is.

**Comment by krystian3w** [comment]
`https://updatemybrowser.org/widget`

**Comment by Kristinita** [comment]
**Type: Question** :question:

> But we are not tracking.
> 
> 1. The cookie is the same for all users. It has no specific information. it just says: browserupdateorg=pause.
> 
> 2. So we can not identify users in any way.
> 
> 3. The cookie only lasts 24 hours by default. It is only set to the current domain. We cannot track in any way across domains. It is just used to show a message only once per user and 24hours.
>
> We do not record data except for a random sample of the browser used for every 1000th user. This can not be used in any way to track anybody. You can check the script to verify this.
>
> Please, if you say it's tracking, say why or what your definition is.

@josselex, could you give arguments why it’s so important that you left it, despite the fact that Browser Update is included in the ad blockers blocklists? [**32.8% of internet users worldwide use ad blocking tools at least sometimes**](https://backlinko.com/ad-blockers-users), many of them may not see notifications from Browser Update. Also, website developers may refuse to use Browser Update because ad blockers block it. I would do what the blocklist developers require, so that Browser Update is removed from the blocklists. It seems to me that the benefit of removing Browser Update from blocklists far outweighs the benefit of retaining features that are unwanted, in the opinion of blocklist developers.

Thanks.
