### ISSUE TITLE
semawur.com

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#7086]
### URL(s) where the issue occurs

`https://semawur.com/gNU0MuhTu`

### Describe the issue

Countdown timer in 10 secs

### Screenshot(s)

![image](https://user-images.githubusercontent.com/61142621/76328200-4f919900-62eb-11ea-988e-2a47e8fb3f88.png)

### Versions

- Browser/version: Opera Version: 67.0.3575.53
- uBlock Origin version: 1.23.0

### Settings

- All default

**Comment by chelseaislan** [comment]
I want to add these links from the same domain that have double 10 seconds countdown:

- https://semawur.com/advang5
- https://semawur.com/driverspd
- https://semawur.com/upgrader23

However, the domain redirects to `ayobelajarbareng.com` with random URL and content. After waiting for 10 seconds, I have to wait for another countdown from the same domain to view the contents I want to download.
