### ISSUE TITLE
cbs.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#709]
Anti adb warning is displayed on videos on `http://www.cbs.com`.

**SS:** https://i.imgur.com/1RQ3uho.png
**Error URL:** `http://www.cbs.com/shows/the_young_and_the_restless/video/NTewNieMZpK7YXG4AC2noQNzRydSCKA3/the-young-and-the-restless-9-21-2017/`

_**Note:** Using uBO 1.14.8 on Chrome 61 with the default filters and settings._

**Comment by gorhill** [comment]
Seems that using "Adguard Base Fitlers" list fixes the issue.

**Comment by mapx-** [comment]
https://forums.lanik.us/viewtopic.php?p=123615#p123615

**Comment by gotitbro** [comment]
@gorhill What do you mean by Adguard Base filters? Which filter list is that?

**Comment by uBlock-user** [comment]
It's located in 3rd Party Filters tab, in Ads Section - https://i.gyazo.com/98ee5681d097c2e900ca6fc464cb1b56.png

**Comment by okiehsch** [comment]
How about
````
||fastly.net^$image,important,redirect=2x2-transparent.png,domain=cbs.com
|fastly.net^$script,important,redirect=noopjs,domain=cbs.com
@@||cbs.com^$generichide
````
Works on my end with this non geo-locked video
````
http://www.cbs.com/shows/60_minutes/video/_SAqgmJQyP_vEW8uIDjbLtZarr6T9kp9/the-storm-after-the-storm-enhancing-the-bike-new-kid-on-the-block/
````

**Comment by gotitbro** [comment]
@uBlock-user Thanks for that didn't notice it as I have the tabs collapsed.

@okiehsch You don't necessarily need a non geo locked video as the Anti adb message is always shown before the geo locked error message. I checked the filter on both the videos (geo-locked and non geo-locked) and they worked.

**Comment by okiehsch** [comment]
@gotitbro I used a non geo-locked video to be sure that my filters circumvent the anti-adblock message
and do not cause any playback issue.

**Comment by gotitbro** [comment]
@uBlock-user Can you tell me which version of uBO are you on as I still don't see the Aguard Base Filter option.

**Comment by uBlock-user** [comment]
`$generichide` alone works for me.

**Comment by uBlock-user** [comment]
@gotitbro I'm on v1.14.8. Version doesn't matter here. It's updated when you _Purge all caches_ and reload uBlock Origin in Chromium.

**Comment by refack** [comment]
**cbs.com** (the part that was CBS All Access) is moving to **paramountplus.com** so Ad Block Detection is back.

For me this rule solved it:
```
@@||s0.2mdn.net/instream/html5/ima3.js$script,domain=paramountplus.com
```

**Comment by stephenhawk8054** [comment]
I think

```adb
||fastly.net^$image,important,redirect=2x2.png,domain=cbs.com
||fastly.net^$script,important,redirect=noopjs,domain=cbs.com
```

is not needed any more?

**Comment by refack** [comment]
> Are the filters
> `...`
> still needed?

As far as I can tell, no.
"CBS all access" does not exist anymore, and the current CBS.com stream is not integrated with `fastly.net`
