### ISSUE TITLE
bestprosoft.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#7090]
`http://bestprosoft.com/microsoft-iso-downloader-premium-2020-1-7-multilingual/`

fake download button at bottom.

> "![obraz](https://camo.githubusercontent.com/758e6c196e444581a0801684c1530bd31acbc71d/687474703a2f2f6265737470726f736f66742e636f6d2f77702d636f6e74656e742f706c7567696e732f696e7374616c6c6361706974616c2f696d616765732f646f776e6c6f61642d627574746f6e2f646f776e6c6f61642d372e706e67)"

---

`/images/download-button/download-*.$image,domain=bestprosoft.com`

or

`bestprosoft.com##.affiliate_download_imagebutton_container`

maybe:

`bestprosoft.com##a[href^="https://anonymz.com/"]`

**Comment by mapx-** [comment]
classic filters @ryanbr

**Comment by krystian3w** [comment]
But this is not an ad / tracker... 😢.
