### ISSUE TITLE
www.ushareit.com issue

### ISSUE THREAD

**Issue by weijen6** [uBlockOrigin/uAssets#7092]
`https://www.ushareit.com/zh/index.html`

button not work
l
![image](https://user-images.githubusercontent.com/32688959/76531723-9bda0600-64b0-11ea-92d4-2a48680c9cac.png)

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/76536725-06714e80-647d-11ea-8318-2381a83453a7.png)

**Comment by weijen6** [comment]
My bad
https://www.ushareit.com/zh/index.html
