### ISSUE TITLE
www.foreignaffairs.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7093]
### URL(s) where the issue occurs

`https://www.foreignaffairs.com/`

### Describe the issue

Annoyance: leftover of a modal (blackout), scroll is locked.

### Screenshot(s)

![foreignaffairs](https://user-images.githubusercontent.com/58900598/76581173-d75aeb80-6515-11ea-9de8-f04d71815f7f.png)

### Versions

- Browser/version: Firefox 73.0.1
- uBlock Origin version: 1.25.2

### Settings

- Default + Fanboy Annoyances + uBlock Annoyances

### Notes

foreignaffairs.com##+js(nostif, noscroll, 3000)

**Comment by Yuki2718** [comment]
@ryanbr can you do something for those non-uBO users?

**Comment by okiehsch** [comment]
Thanks for investigating and finding a working fix.
