### ISSUE TITLE
yavli filters breaking pages

### ISSUE THREAD

**Issue by TheStinkySkunk** [uBlockOrigin/uAssets#7094]
Hi,

@mapx does anything with your tools and does not understand that a function like JSON.parse is used by many scripts including Jquery, recaptcha, ...

Since yesterday, impossible to valid "cloudflare antibot check" on a lot of website.

Don't make bullshit job, It is not for nothing that you have a JSON.prune filter, it is because this function is sensitive ...

Once again, I see that you DON'T test anything before dispatching a rule ...

**Comment by uBlock-user** [comment]
> Since yesterday, impossible to valid "cloudflare antibot check" on a lot of website.

which websites ?

**Comment by TheStinkySkunk** [comment]
https://github.com/uBlockOrigin/uAssets/commit/15fabb306c5e6d8263ee6abeb8a0d6088bc0d343

**Comment by Yuki2718** [comment]
IDK how insulting one can be helpful. Randomly picked several domains from the rule and no problem, except that required to solve recaptcha only once - after solving I could visit the page w/out any issue. So what the exact URL?

**Comment by Yuki2718** [comment]
`redhotchacha.com` in the rule seems to be dead so it can be removed.

**Comment by mapx-** [comment]
@TheStinkySkunk waiting for what's broken, steps to reproduce.

**Comment by TheStinkySkunk** [comment]
ok i will see with my legal team.

**Comment by mapx-** [comment]
disabled for now - `allthingsvegas.com` captcha broken

**Comment by Yuki2718** [comment]
Confirmed also on `http://reviveusa.com/`. (Again I forgot to purge and update.) Still most of sites on the rule are accessible with the rule enabled tho.

**Comment by Yuki2718** [comment]
@mapx- `redhotchacha.com` still have 5 hits and I guess all of them can be removed.

**Comment by mapx-** [comment]
removed, thx
