### ISSUE TITLE
enrt.eu

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#7102]
### URL(s) where the issue occurs

`https://enrt.eu/sDPPe`

### Describe the issue

Countdown

### Screenshot(s)

![image](https://user-images.githubusercontent.com/61142621/76700020-64877700-66b3-11ea-8c55-54dde80d0e92.png)

### Versions

- Browser/version: Opera Version: 67.0.3575.53
- uBlock Origin version: 1.23.0

### Settings

- All default

**Comment by mapx-** [comment]
@LGLTeam I have already asked you not to publish clickable links anymore.

Just select the link, then click the spcial tag: 
![image](https://user-images.githubusercontent.com/10303732/76700121-7ddcf300-66b4-11ea-9829-eb014fc3b741.png)

**Comment by mapx-** [comment]
However, the countdown is controlled on server-side.

**Comment by LGLTeam** [comment]
Ok and sorry I didn't saw what you said
