### ISSUE TITLE
camera.aeonax.com [Anti-Adblock]

### ISSUE THREAD

**Issue by tillcash** [uBlockOrigin/uAssets#7103]
### URL(s) where the issue occurs

`https://camera.aeonax.com/#predownloads`

### Describe the issue

Anti-adblock.

### Screenshot(s)

https://i.imgur.com/Et0Kf2H.png

### Versions

- Browser/version: 68.6.0esr (64-bit)
- uBlock Origin version: 1.25.0

**Comment by mapx-** [comment]
Did you first update all your lists ? (purge all caches + update)

**Comment by uBlock-user** [comment]
Was addres just two days ago -- https://github.com/uBlockOrigin/uAssets/issues/7095
