### ISSUE TITLE
pinterest.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#7104]
### URL(s) where the issue occurs

`https://www.pinterest.de/pin/73183562674172462/?d=t&mt=login`

### Describe the issue

unblocked Background

### Screenshot(s)

<img width="1387" alt="unblockedbackground" src="https://user-images.githubusercontent.com/48647394/76701329-94894700-66c0-11ea-9439-3300bb2092a8.PNG">

### Versions

- Browser/version: Firefox 74
- uBlock Origin version: v1.25.2

### Settings

[settings.txt](https://github.com/uBlockOrigin/uAssets/files/4334183/settings.txt)

**Comment by mapx-** [comment]
try
`pinterest.de##[style^="background-color: rgba(0, 0, 0, 0.6); opacity: 1; position: fixed; top: 0px; bottom: 0px; left: 0px; right: 0px; z-index: 1000;"]`

**Comment by JobcenterTycoon** [comment]
it doesn't work

**Comment by mapx-** [comment]
what about
`pinterest.de##[style^="background-color: rgba(0, 0, 0"]`

**Comment by JobcenterTycoon** [comment]
yes

**Comment by krystian3w** [comment]
Possible with other language:

`https://www.pinterest.fr/pin/73183562674172462/?d=t&mt=login`
`https://www.pinterest.ca/pin/73183562674172462/?d=t&mt=login`
`https://www.pinterest.com/pin/73183562674172462/?d=t&mt=login`
