### ISSUE TITLE
playtube.ws

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#7106]
Anti-adblock in player:

    https://playtube.ws/embed-8hy77dwag0ol.html

[](https://github.com/MajkiIT/polish-ads-filter/issues/15780#issuecomment-599200306) [](https://github.com/AdguardTeam/AdguardFilters/issues/51565)

> ![obraz](https://user-images.githubusercontent.com/35370833/76705440-5c91fc00-66e0-11ea-9f8d-2ce087d55af6.png) |
> --- |

**Comment by ghajini** [comment]
`https://playtube.ws/ut6ee3mea963/Mortal.Torden.2020.Web-Dl.HC.ENG.mp4.html`

Popup ads

**Comment by krystian3w** [comment]
again pop-ups embeded in player https://github.com/MajkiIT/polish-ads-filter/issues/17471#issuecomment-716399456

@zaba-monika reccommend:


```diff
-playtube.ws##+js(aopw, _pop)
+playtube.ws##+js(aopw, _run)
```

**Comment by ghajini** [comment]
@mapx- @okiehsch 
Better test link=
NSFW

`https://playtube.ws/embed-6d8wbw4jj8id.html`

Popup ads
Firefox ubo1.30.6

**Comment by ghajini** [comment]
Filter `playtube.ws##+js(acis, Math, XMLHttpRequest)`
Doesn't work when downloading from website....

Update scriptlet filter to

`playtube.ws##+js(acis, String.fromCharCode, btoa)`
Or anything

**Comment by okiehsch** [comment]
I did not add `playtube.ws##.overlay`.
The only filters I added were
````
playtube.ws##+js(nowoif)
@@||playtube.ws^$xhr,1p
````

**Comment by krystian3w** [comment]
Only "sorted", other story is:

![Screenshot_2020-10-27 PolishFiltersTeam PolishSocialCookiesFiltersDev](https://user-images.githubusercontent.com/35370833/97270270-2e0c0000-182f-11eb-9364-73523445e8fd.png) |
--- |
I don't touched old `.`... |




Why does the preview of the changes assume that the "dot" character is old and I have not inserted a new one without touch old.

**Comment by ghajini** [comment]
`https://playtube.ws/grvywhn43mt5`

video player is blocked here

**Comment by mapx-** [comment]
I get no video, however I corrected a filter, report back

**Comment by uBlock-user** [comment]
> https://playtube.ws/grvywhn43mt5

404

**Comment by ghajini** [comment]
`https://playtube.ws/grvywhn43mt5`
(link still works fine)

Videoplayer is still blocked, only thumbnail is visible like this
![IMG_20210523_010740](https://user-images.githubusercontent.com/20338483/119238947-56f53900-bb63-11eb-9540-40cce716102a.jpg)

To unbreak add like this(if you want to keep denyallow filter)

`*$script,3p,denyallow=googleapis.com|gstatic.com|fastly.net|jwpcdn.com|cloudflare.com|static.statictube.xyz,domain=playtube.ws`
{there is no cloudfare.com request on my end}

**Comment by mapx-** [comment]
example working link
`https://playtube.ws/jt9nimiteugh`
