### ISSUE TITLE
ADS detect in => www.anime-sugoi.com 

### ISSUE THREAD

**Issue by Fuyuppe** [uBlockOrigin/uAssets#7107]
### URL(s) where the issue occurs

https://www.anime-sugoi.com/play/130540/the-record-of-unusual-creatures-1.html

### Describe the issue

Ads detect in  this website 
Can't play video 

### Screenshot(s)

![ภาพ](https://user-images.githubusercontent.com/43577606/76718025-ffda2400-6767-11ea-8510-528db174d727.png)

### Versions

- Browser/version: Firefox 74.0
- uBlock Origin version: 1.25.2

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by Yuki2718** [comment]
Not reproduced with default settings on Firefox 74.0 or Brave 1.4.96. Does it requires some user action?

**Comment by Fuyuppe** [comment]
Now is fine 

![ภาพ](https://user-images.githubusercontent.com/43577606/76737803-08e4e880-679c-11ea-8987-caa3ecef083c.png)
