### ISSUE TITLE
japan-academy-prize.jp

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#7109]
### URL(s) where the issue occurs

`https://www.japan-academy-prize.jp/`

### Describe the issue

Copy protection.

### Versions

- Browser/version: Firefox stable
- uBlock Origin version: 1.25.2

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin lists

**Comment by llacb47** [comment]
Test `japan-academy-prize.jp##+js(ra, onmousedown|onselectstart|oncontextmenu, [onmousedown])`
