### ISSUE TITLE
rwarms.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#7111]
### URL(s) where the issue occurs

`https://www.rwarms.com/`

### Describe the issue

Image doesn't load

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/76900495-d7d5e800-686f-11ea-8be1-37430866dcb4.png)

### Notes

```
@@||www.googletagmanager.com/gtag/js?id=UA-120126060-1$script,domain=rwarms.com
@@||*.doubleclick.net/,domain=rwarms.com
```
Adding these fixed it for me.

**Comment by mapx-** [comment]
adding only
`@@||googletagmanager.com/gtag/js$script,domain=rwarms.com`

it's enough on my end FF / chrome
