### ISSUE TITLE
Wrong website in filter list of Ublock Origin, How to remove it ?

### ISSUE THREAD

**Issue by neuronpartners** [uBlockOrigin/uAssets#7112]
### URL(s) where the issue occurs

`https://sex.cam` NSFW

### Describe the issue

The url was added by mistake because of an external ad where the domain name where visible on the image.
Here is the previous issue linked https://github.com/uBlockOrigin/uAssets/issues/892#issuecomment-522310582
The website doesn't use any prohibited method or script.

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

How could it be remove please ?

**Comment by uBlock-user** [comment]
`sex.cam` is not blocked.

**Comment by uBlock-user** [comment]
Hyperlinks to `sex.cam` are as they're used to load ads -- `##[href^="https://sex.cam/"]`

**Comment by Yuki2718** [comment]
Maybe make it more strict? Current rule will hide virtually any link to the site.

**Comment by okiehsch** [comment]
> Maybe make it more strict?

I can't see any `sex.cam` ads at the link of https://github.com/uBlockOrigin/uAssets/issues/892#issuecomment-522310582, so I would not know how to update the filter.

`##[href^="https://sex.cam/"]` will also break google search results for that site. 
I will comment it out for now,

**Comment by llacb47** [comment]
Looking at `https://publicwww.com/websites/%22https%3A%2F%2Fsex.cam%22/`, it seems a more appropriate filter would be `##[href^="https://sex.cam/"][href*="?o="]`

**Comment by Yuki2718** [comment]
> ##[href^="https://sex.cam/"][href*="?o="]

Well, I've found that rule hides just a link on `http://simplenu.com/`. We need to find an actual ads for some page. BTW it may be slightly better `##[href^="https://sex.cam/" i][href*="?o="]`

**Comment by uBlock-user** [comment]
Just make it site specific, and that would solve the issue at hand.

**Comment by neuronpartners** [comment]
Hi,

thank you all for your answers. So i don't see any change for the moment. How does it works ? I should make it on the filters file ? 
Sorry for the dumb question.

**Comment by mapx-** [comment]
```
! Title: uBlock filters
! Expires: 4 days
```

every 4 days

**Comment by neuronpartners** [comment]
> 
> 
> ```
> ! Title: uBlock filters
> ! Expires: 4 days
> ```
> 
> every 4 days

Thank you !
