### ISSUE TITLE
ign.com video playback issue

### ISSUE THREAD

**Issue by Mezito80** [uBlockOrigin/uAssets#7113]
### The video initially loads but when I click to unmute the video, since Firefox mutes all videos, it will load an intro screen for the video and then a black screen - the video doesn't play. 
-The first screenshot shows how the page loads.
-The second screenshot is the intro screen shown after clicking the unmute button.
-The third screenshot is end result, a black screen.

### Screenshot(s)
![1](https://user-images.githubusercontent.com/33856202/76925972-8a7a6a80-68b1-11ea-98d9-5e4830212b27.png)
![2](https://user-images.githubusercontent.com/33856202/76926301-6cf9d080-68b2-11ea-9a1f-2764d66b3336.png)
![3](https://user-images.githubusercontent.com/33856202/76926311-6ff4c100-68b2-11ea-844c-62dbec4ac2fa.png)

### Versions

- Browser/version: Firefox 74
- uBlock Origin version: 1.25.2

**Comment by okiehsch** [comment]
I get the black screen with `uBO` disabled.

**Comment by lain566** [comment]
Removed badfilter.
