### ISSUE TITLE
ripsave.com - Ads

### ISSUE THREAD

**Issue by ArmynC** [uBlockOrigin/uAssets#7114]
### URL(s) where the issue occurs

`[https://ripsave.com/]`

### Describe the issue

On top right there are 2 boxes with ads.

### Screenshot(s)

![Capture](https://user-images.githubusercontent.com/16375271/76977018-6f553c80-693d-11ea-9685-c088f7a35f6e.PNG)

### Versions

- Browser/version: 80.0.3987.132 (Official Build) (64-bit)
- uBlock Origin version: 1.24.5b4

### Settings

[- [List here all the changes you made to uBO's default settings]](https://github.com/ArmynC/ArminC-uBlock-Settings)

### Notes

-

**Comment by llacb47** [comment]
`||inpagepush.com^` already in Easylist, are you on default settings?

**Comment by ArmynC** [comment]
> `||inpagepush.com^` already in Easylist, are you on default settings?

I have the EasyList but the thing is that I have the Lite version, which apparently don't have this particular entry. Thanks!
