### ISSUE TITLE
Live chat not working in Best Buy cart

### ISSUE THREAD

**Issue by loganrosen** [uBlockOrigin/uAssets#7116]
### URL(s) where the issue occurs

`https://www.bestbuy.com/cart`

### Describe the issue

If you click the Help tab on the right side (along the scrollbar), there's a live chat option. When uBlock Origin is enabled, it says that live chat is "not currently available." If you disable it and try again, live chat works (although you may have to wait a few seconds for it to show as available).

### Screenshot(s)

![image](https://user-images.githubusercontent.com/512317/77029886-62ebd680-6973-11ea-8452-f90e6c7db8da.png)

![image](https://user-images.githubusercontent.com/512317/77029865-57001480-6973-11ea-95b1-2bfc97190618.png)

### Versions

- Browser/version: Firefox 74.0
- uBlock Origin version: 1.25.2

### Settings

- Peter Lowe’s Ad and tracking server list disabled

### Notes

N/A

**Comment by okiehsch** [comment]
Do I have to be logged in ?
I get the currently not available message with `uBO` disabled.

**Comment by gwarser** [comment]
www.bestbuy.com 247-inc.net * allow
	www.bestbuy.com https://www.bestbuy.com/~assets/bby/ script allow

**Comment by llacb47** [comment]
```
@@||bestbuy.com/~assets/bby/_com/analytics-dotcom/*$script,1p
@@||247-inc.net^$subdocument,domain=bestbuy.com
```

**Comment by gwarser** [comment]
Narrowed it down to

```
www.bestbuy.com 247-inc.net * allow
www.bestbuy.com https://www.bestbuy.com/~assets/bby/_com/analytics-dotcom/analyticsInit-e5c96f24f0adf38550e73dbf3d022127.js script allow
www.bestbuy.com https://www.bestbuy.com/~assets/bby/_com/analytics-dotcom/chunks/tfsInit-a8b844756679ca992204.js script allow
```

but I'm not sure chat actually works..
