### ISSUE TITLE
first party CNAME blocked as third party

### ISSUE THREAD

**Issue by jk2** [uBlockOrigin/uAssets#7117]
### URL(s) where the issue occurs

On all LeanLab customer sites using `leanlabcloud.leanlab.co` or `leanlab-cloud.leanlab.co` as CNAME for their site. E.g.
 
`https://vaikuttajat.hsl.fi`

### Describe the issue

The LeanLab is a collaboration platform companies are using under their own domains for creating online communities their customers can register to. It's a SaaS service and CNAME is used to reference the LeanLab cloud.

The following entry:
`||leanlab.co^$third-party`

on EasyPrivacy list (`https://easylist.to/easylist/easyprivacy.txt`) is preventing loading of images/css/javascript on LeanLab sites because of CNAME check. So even that it's third-party filter it still blocks content loaded from the same vaikuttajat.hsl.fi domain as the site itself, see the screenshot below.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/1262988/77044248-c142a480-69c7-11ea-8231-af6d18ad9360.png)

### Versions

- Browser/version: Firefox/74.0
- uBlock Origin version: 1.25.2

### Settings

- default settings

**Comment by uBlock-user** [comment]
@rynabr

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Fixed. @uBlock-user
