### ISSUE TITLE
cnet.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7118]
### URL(s) where the issue occurs

`https://www.cnet.com/videos/lg-g7-vs-galaxy-s9-design-and-hardware-comparison/`

### Describe the issue

An exception rule
`@@||cbsinteractive.com^*/lib/tracking/comscore/$script`
was added to EasyPrivacy by https://github.com/easylist/easylist/commit/14349961317bfb77b65ef8b085bf71879bead50b but this tracking script used around many CNET sites don't need to be allowed on uBO as a redirect rule
`||vidtech.cbsinteractive.com^*/tracking/$script,redirect=noop.js,important`
works without breaking the video.

### Screenshot(s)

![cnet](https://user-images.githubusercontent.com/58900598/77054635-5ae37380-6a13-11ea-877c-67ab08ddc679.png)

### Versions

- Browser/version: Brave 1.5.112
- uBlock Origin version: 1.24.4

### Settings

- Default

### Notes

Please add the rule (with adjustments if needed) to Privacy filter.

**Comment by mapx-** [comment]
I'm not sure if your filter could break cbs site for example, see the filter
`@@||vidtech.cbsinteractive.com^$script,domain=cbs.com`

**Comment by Yuki2718** [comment]
> 
> 
> I'm not sure if your filter could break cbs site for example, see the filter
> `@@||vidtech.cbsinteractive.com^$script,domain=cbs.com`

I was not aware of the rule; however, it seems the rule was added due to anti-adblock https://github.com/uBlockOrigin/uAssets/issues/4651 and at least not for the payment issue https://github.com/uBlockOrigin/uAssets/issues/4908. I can watch their video at least if not logged in (accessed from Los Angeles for geo-lock).
![cbs](https://user-images.githubusercontent.com/58900598/77070497-ac98f780-6a2d-11ea-85c8-af153746c302.png)

**Comment by mapx-** [comment]
added
