### ISSUE TITLE
out-of-scope bloat added to easylist tracking list

### ISSUE THREAD

**Issue by funkydude** [uBlockOrigin/uAssets#712]
This is in regards to this ticket: https://github.com/easylist/easylist/issues/630

Unfortunately the author appears to be a bit dim, and does not understand project scope.
He has added a website that hosts legitimate javascipt bitcoin miners to the list dedicated for trackers.
These are totally legitimate scripts and can potentially be used as a total replacement for advertising. They are not used for tracking.

Unfortunately he is too afraid to even discuss it, as such, he locked out the ticket. Probably because he knows this is a total hack on his part, that should be in a separate "miners" list.

He has taken the decision to block the entire domain, because the pirate bay made the awful decision of not alerting its users before placing this on a trial period on their live website instead of a beta page.

He is completely ignoring the fact that other websites use this with full user interaction.

Would it be possible to temporarily overwrite this filter in uBO so we can gain this functionality back, and in future, add a toggle option for users?

The latter shouldn't be needed as it should be a separate list, but alas, this is the situation we are in.

**Comment by SMed79** [comment]
See https://github.com/uBlockOrigin/uAssets/issues/698

**Comment by gotitbro** [comment]
@funkydude I understand that you are upset with the particular addition but you don't need to name call the author. It is already taken care of in uBO as the crypto miner has been blocked in a separate filter list.

As to if this has privacy implications, yes it does as no user consent is taken before using resources. @ryanbr can shed light on his own opinion.

**Comment by funkydude** [comment]
The user consent is up to the website implementing it, that still does not make it a tracker. Feel free to provide evidence of it exhibiting tracking behaviour.

**Comment by gotitbro** [comment]
@funkydude The majority of the websites are abusing user consent though. Privacy doesn't only mean tracking, they are invading my privacy by abusing resources on my PC.

**Comment by okiehsch** [comment]
The discussion tkes place at https://github.com/uBlockOrigin/uAssets/issues/690
