### ISSUE TITLE
http://onlinebr.xyz/ads/ detects uBlock Origin

### ISSUE THREAD

**Issue by sanGtH** [uBlockOrigin/uAssets#7120]
[What you expected to happen]
The page : `http://onlinebr.xyz/ads/?file=4f844234a6` should not detect uBlock.
### Actual behavior:
The page should detects uBlock. When i press **Continue & Download** button, it doesn't go
to the next page. 
![image](https://user-images.githubusercontent.com/13797193/77080712-9edc7580-6a1f-11ea-91a7-609c2756d3cb.png)

### Your environment
* uBlock Origin version:  **uBlock Origin 1.24.4**
* Browser Name and version: **Chrome v80.xx**
* Operating System and version: **Win 7 64 bit**

**Comment by uBlock-user** [comment]
`.xyz/ads/` from Easylist is breaking the page.

**Comment by llacb47** [comment]
`@@||onlinebr.xyz^$1p`

**Comment by sanGtH** [comment]
How to use this filter ? @llacb47

**Comment by gwarser** [comment]
@sanGtH Paste into [uBO Dashboard](https://github.com/gorhill/uBlock/wiki/Dashboard) -> [My filters](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) tab and apply changes.

**Comment by sanGtH** [comment]
Thanks @gwarser Its working. But will this workaround be incorporated in the next update ?
