### ISSUE TITLE
uBlock Origin caused issue on my telco site

### ISSUE THREAD

**Issue by cshong87** [uBlockOrigin/uAssets#7125]
### URL(s) where the issue occurs

Website of my telco: `https://www.digi.com.my/`
Telco blll payment site: `https://www.digi.com.my/selfcare/bills/pay-bill`

### Describe the issue

On my telco site, with uBlock Origin enabled, some of the features or functions on the website were not working properly. I am unable to do bill payment.

### Screenshot(s)

uBlock Origin was enabled.
Here are the screenshots for URL: `https://www.digi.com.my/selfcare/bills/pay-bill`

Following screenshot shows the errors in console before I fill the required information.

<img width="960" alt="1 - before filling payment info" src="https://user-images.githubusercontent.com/55344914/77218997-54b4da80-6b6c-11ea-8789-3f6820e40144.PNG">

Following screenshot shows the errors in console after I fill in required information and click the "pay now" button.

<img width="960" alt="2 - After filling payment info and click pay button" src="https://user-images.githubusercontent.com/55344914/77219143-bd508700-6b6d-11ea-8f45-c0be4bcaaefb.PNG">

### Versions

- Browser/version: Google Chrome 80.0.3987.149, Firefox 74.0
- uBlock Origin version: 1.24.4 (for Google Chrome), 1.25.2 (Firefox)

### Settings

In the settings, I did change nothing.

### Notes

After disabled uBlock Origin, the website works properly, and the payment was done successfully.

**Comment by okiehsch** [comment]
Well, it obviously needs an account to test properly.
Does adding
`@@||images.digi.com.my/*c/google_tag/*$script,1p`
to your filter list work?

**Comment by mapx-** [comment]
no feedback ?

**Comment by cshong87** [comment]
Sorry for the late reply. Adding to the filter does work.

> 
> 
> Well, it obviously needs an account to test properly.
> Does adding
> `@@||images.digi.com.my/*/google_tag/*$script,1p`
> to your filter list work?

Sorry for the late reply. Adding to the filter does work.

**Comment by okiehsch** [comment]
Added to `uBO-unbreak`.
