### ISSUE TITLE
Could redirect filter be favored over whitelist?

### ISSUE THREAD

**Issue by kasper93** [uBlockOrigin/uAssets#713]
### URL(s) where the issue occurs

`https://support.amd.com/`

### Describe the issue

It is known issue that blocking gtm.js will break sites that use "no-flicker" feature, but seems like recently something changed and redirect in ublock-privacy is not applied

`||googletagmanager.com/gtm.js$script,redirect=googletagmanager.com/gtm.js`

I needed to mark as bad those two filters

easy privacy:
`@@||googletagmanager.com/gtm.js?$badfilter,domain=airasia.com|bhaskar.com|broadcom.com|computerworlduk.com|desigual.com|drumstick.com|ebuyer.com|elevationscu.com|gamepix.com|git-tower.com|google.com|itv.com|jobs.net|keygames.com|magicjack.com|moviefone.com|nestio.com|newsy.com|optus.com.au|rebtel.com|rockstargames.com|rollingstone.com|rozetka.com.ua|sixflags.com|support.amd.com|talktalk.co.uk|techradar.com|toto.co.jp|usmagazine.com`

ublock unbreak:
`@@||www.googletagmanager.com/gtm.js$badfilter,script,domain=support.amd.com`

What I'm wondering is that filter in unbreak list has been there for two years, so something must have changed in filters parsing. Because now it is favored over redirect.

Anyway this is just example of the problem that we currently have. Filter list like Easylist are likely to whitelist scripts that break site if blocked. But uBlock has ability to redirect/fix scripts and therefore fix the issue without white listing the problematic script. Because Easylist like list can't know about this feature, uBlock should prioritize redirect filters in my opinion. And have its own whitelist ($important) if redirect doesn't work. 

What do you think? 

### Versions

- Browser/version: Firefox 58.0a1 (2017-09-22)
- uBlock Origin version: 1.14.11rc0

**Comment by gorhill** [comment]
`googletagmanager.com/gtm.js` is often used to deliver custom scriptlets from the server, so redirecting can still break a site. I remember having to create exceptions filters to fix such cases.

So I won't blanket mark exception filters for `googletagmanager.com/gtm.js` as bad filters. Every single case will have to be investigated and see if they still suffer the original issue reported which caused the exception to be created.

**Comment by kasper93** [comment]
Ok, I understand. Let's consider this report specifically about `https://support.amd.com/` then, where to the best of my knowledge "redirect" works fine. The original report was here https://github.com/gorhill/uBlock/issues/780

**Comment by kasper93** [comment]
@gorhill: Could you extend for whole `amd.com` or at least `community.amd.com`? The same issue community pages and it seems to work fine with redirect.

**Comment by gorhill** [comment]
I don't see any delay in page rendering. You have a specific URL with the issue? No point adding filter if it ends accomplishes nothing.

**Comment by kasper93** [comment]
Right, it is `Adguard Spyware Filters` now. This one is responsible.  `@@||googletagmanager.com/gtm.js$domain=amd.com`

Not sure, maybe this could be fixed in Adguard list itself?
