### ISSUE TITLE
YouTube ads aren't being Blocked

### ISSUE THREAD

**Issue by phikal** [uBlockOrigin/uAssets#7131]
### URL(s) where the issue occurs

Any YouTube video with advertisements, here's a random one from the front page 
`https://www.youtube.com/watch?v=-Mkp4oavz2M`

### Describe the issue

The advertisements before a YouTube video aren't being blocked, but instead appear without any option to skip. I haven't seen advertisements for a few years,  so I don't know if it's normal that two 10+ second videos should be watched entirely, or that advertisements appear in sequence.

### Screenshot(s)

N/A

### Versions

- Browser/version: `Mozilla Firefox 68.5.0esr`
- uBlock Origin version: 1.25.2

### Settings

My filter contains only this additional rule:

```
! 30/12/2019 https://www.youtube.com
www.youtube.com##.opened
||consent.google.com/?continue=https://www.youtube.com/&origin=https://www.youtube.com&pc=yt&hl=en-GB&gl=DE&if=1&m=0&l=0$subdocument
www.youtube.com###dialog
```

### Notes

N/A

**Comment by NubN** [comment]
no ads for me in youtube.

**Comment by mapx-** [comment]
maybe it's something wrong with ESR version of FF ?

**Comment by NubN** [comment]
wooooops i can reproduce the ads with Firefox.

i was using Chrome.

**Comment by mapx-** [comment]
No ads FF / chrome

**Comment by phikal** [comment]
@NubN what version?

**Comment by gwarser** [comment]
Add `@@||youtube.com/get_video_info?$xmlhttprequest,badfilter` to My filters.

**Comment by NubN** [comment]
74.0 firefox

**Comment by NubN** [comment]
the ads, you cant skip

example video:
`https://www.youtube.com/watch?v=ZnR90566uKo`

**Comment by llacb47** [comment]
Probably easylist is hiding the skip button?

**Comment by NubN** [comment]
the filter of **gwarser** is working:

`@@||youtube.com/get_video_info?$xmlhttprequest,badfilter`

**Comment by maple3142** [comment]
I am an author of a [YouTube video downloading userscript](https://greasyfork.org/en/scripts/369400-local-youtube-downloader), and this change seems to break it functionality.
I have [update the script and instruct users](https://greasyfork.org/zh-TW/scripts/369400-local-youtube-downloader/diff?v1=783446&v2=783419) to add `@@||youtube.com/get_video_info?$1p` to rules so that the script will still working, but I don't know whether adding that will break current adblocking.
Is there a better unbreak rule to add than `@@||youtube.com/get_video_info?$1p`? My script require `https://www.youtube.com/get_video_info?video_id=VIDEO_ID&el=detailpage` to be accessible to work.

**Comment by mapx-** [comment]
does this work ?
`@@||www.youtube.com/get_video_info?*=detailpage$xhr,domain=youtube.com`

see https://www.reddit.com/r/uBlockOrigin/comments/fn3i5v/need_help_blocking_the_adblock_message_from_the/

**Comment by maple3142** [comment]
> does this work ?
> `@@||www.youtube.com/get_video_info?*=detailpage$xhr,domain=youtube.com`
> 
> see [reddit.com/r/uBlockOrigin/comments/fn3i5v/need_help_blocking_the_adblock_message_from_the](https://www.reddit.com/r/uBlockOrigin/comments/fn3i5v/need_help_blocking_the_adblock_message_from_the/)

Thanks! It works perfectly, so I just changed the rule.

**Comment by gwarser** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/fnh39w/bug_playback_problem_on_youtube_videos/

>Apparently this only occurs when I open a youtube link in a new tab. Following that, if I open a new youtube link on the same tab (such as any recommended video on the right panel) and turn back, the problem doesn't reappear. This is my workaround for now.

Can someone reproduce this?
