### ISSUE TITLE
website adblock detection

### ISSUE THREAD

**Issue by Iaycomand** [uBlockOrigin/uAssets#7132]
### URL(s) where the issue occurs

`https://www.egyanime.com/watch?w=17545`

### Describe the issue

a targeted message asking me to turn off the adblock and can't interact with media player but not sure if that related to adblock causing media to not work.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/39984795/77233475-4dafbb80-6bb0-11ea-9208-6881247e0b50.png)

### Versions

- Browser/version: Google Chrome Version 80.0.3987.149 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.24.4

**Comment by mapx-** [comment]
Try purge + update your lists, it's ok on my end

**Comment by Iaycomand** [comment]
I reset to default settings but still having the issue, do I miss something?

**Comment by uBlock-user** [comment]
Does `egyanime.com##+js(set, adsBlocked, null)` work for you ?

**Comment by mapx-** [comment]
after resetting the settings you have to purge + update

**Comment by Iaycomand** [comment]
> after resetting the settings you have to purge + update

I did that again but no response.

> Does `egyanime.com##+js(set, adsBlocked, null)` work for you ?

yes, that did the job, thank you!

**Comment by mapx-** [comment]
Do you see in the logger this exception ?
`@@||egyanime.com/*/ads.js$xmlhttprequest,1p`

**Comment by Iaycomand** [comment]
no, or can't see it
![image](https://user-images.githubusercontent.com/39984795/77234628-9e2b1700-6bb8-11ea-954e-3be0eceae92c.png)

**Comment by uBlock-user** [comment]
@laycomand Remove the filter I posted and then refresh again, the exception filter should appear.

**Comment by Iaycomand** [comment]
I removed the filter but still can't find it?

**Comment by krystian3w** [comment]
try paste into field:

`ads.js`

 and try found much easier.

**Comment by mapx-** [comment]
purge + update failed, try again

**Comment by krystian3w** [comment]
https://support.google.com/accounts/answer/32050?hl=en

maybe help download latest file from github if browser cannot update file with url attrib `?_=X`

e.g. `https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt?_=8`

**Comment by Iaycomand** [comment]
I cleared my browser data but still I'm not able to update ublock? is there another way to update it manually or something?

**Comment by krystian3w** [comment]
Possible:

1. Open uBO logger
2. in filter results "input" paste: `/uAssets/master/filters/filters.txt`
3. Open uBO dashboard :arrow_right: "My Filters"
4. Click on "clock" 🕐 next to:

   >   ![obraz](https://user-images.githubusercontent.com/35370833/77253556-57dac400-6c5b-11ea-91c6-005a4e49cbde.png) |
    >    --- |

5. try update filter, and now combeck to uBO logger
6. click on found: `https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt?_=` "arrow".

   >    ![obraz](https://user-images.githubusercontent.com/35370833/77253601-94a6bb00-6c5b-11ea-999f-3ff702b9a21b.png) |
   >    --- |

7. Refresh the opened card with the <KBD>Ctrl<KBD>+<KBD>F5</KBD> shortcut.

8. Back to uBO dashboard and again try update:

   >   ![obraz](https://user-images.githubusercontent.com/35370833/77253556-57dac400-6c5b-11ea-91c6-005a4e49cbde.png) |
    >    --- |

**Comment by Iaycomand** [comment]
oh that was from chrome, after I allowed ads on it; it worked, sorry for wasting time for you'all since it has nothing to do with ublock.
