### ISSUE TITLE
Reddit promoted that starts with "thing_t3_"

### ISSUE THREAD

**Issue by klui2k1** [uBlockOrigin/uAssets#7134]
### URL(s) where the issue occurs

www.reddit.com

### Describe the issue

Using right click (uBlock) Block element... menu in FF allows me to block that specific promotion but there is a random hex id that follows thing_t3_ for each promotion. A refresh basically allows the same element to be displayed again. The rule shows up under My filters. I can't use the rule 
www.reddit.com###thing_t3* in the picker because it states it's an error.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]
![image](https://user-images.githubusercontent.com/19586153/77236504-7453ff00-6b7c-11ea-931f-2534e2660a82.png)

![image](https://user-images.githubusercontent.com/19586153/77236518-89c92900-6b7c-11ea-8790-298f34a79b0d.png)

### Versions

- Browser/version: [Firefox Nightly/76.0a1 (2020-03-21)]
- uBlock Origin version: [1.25.2]

### Settings

- [List here all the changes you made to uBO's default settings]
Items checked:
Hide placeholders of blocked elements
Show number of blocked requests on the icon
Make use of context menu where appropriate
I am an advanced user

Disable pre-fetching
Disable hyperlink auditing

**Comment by uBlock-user** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/fmg728/promoted_posts_and_reddit_premium_banner_showing/fl46hj8/

Nightly is currently broken and won't work.

**Comment by llacb47** [comment]
Resolved 3 minutes ago: https://hg.mozilla.org/mozilla-central/rev/a1bea41f99f4

**Comment by klui2k1** [comment]
Thanks for the quick response. The latest update released just now resolved it.
