### ISSUE TITLE
short syntax

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#7135]
I want to move to the new short syntax.
https://github.com/easylist/EasyListHebrew/blob/master/EasyListHebrew-uBO.txt

`abort-on-property-read.js` -> `aopr`
`abort-on-property-write.js` -> `aopw`
`abort-current-inline-script.js` -> `acis`
`nowebrtc.js` -> `nowebrtc`
`cookie-remover.js` -> `cookie-remover`
right?

What about
`set-constant.js`
`setTimeout-defuser.js`
`addEventListener-defuser.js`
?

Thanks

**Comment by uBlock-user** [comment]
set-constant.js -> https://github.com/uBlockOrigin/uBlock-issues/wiki/Resources-Library#setjs-
setTimeout-defuser.js - https://github.com/uBlockOrigin/uBlock-issues/wiki/Resources-Library#nostifjs-
addEventListener-defuser.js - https://github.com/uBlockOrigin/uBlock-issues/wiki/Resources-Library#aeldjs-

**Comment by IsraeliUser** [comment]
Can you tell me with what should I replace the following rules?
`+js(set-constant.js, String.fromCharCode, noopFunc)`
`+js(set-constant.js, showAds, true)`
`+js(setTimeout-defuser.js, (), 1500)`
`+js(addEventListener-defuser.js, scroll)`

Thanks

**Comment by mapx-** [comment]
```
+js(set, String.fromCharCode, noopFunc)
+js(set, showAds, true)
+js(nostif, (), 1500)
+js(aeld, scroll)
```

**Comment by NubN** [comment]
the "classic" typo will stop works? 

haha is awesome, you have filter for everything :D

**Comment by IsraeliUser** [comment]
https://github.com/easylist/EasyListHebrew/commit/22c0112b7b8d98689e25d96af307cacf833afa0a

Thanks

**Comment by okiehsch** [comment]
https://github.com/DandelionSprout/adfilt/issues/7#issuecomment-573217954
