### ISSUE TITLE
Remove Quantcast popup globally?

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#7137]
### URL(s) where the issue occurs

```
https://www.phoronix.com/
https://www.xda-developers.com/
```
And many other sites using Quantcast

### Describe the issue

Popup that asking you to collect data

### Screenshot(s)

![image](https://user-images.githubusercontent.com/61142621/77247866-6ca46100-6c35-11ea-866b-4744bbc81b25.png)

### Versions

- Browser/version: 67.0.3575.79
- uBlock Origin version: 1.24.4

### Settings

- All default

### Notes

I hate popups on front on my screen, they are so annoying, and sometime they will come back after a day after i clicked accept.

Possible to have it blocked globally except some sites that require downloading? or auto-click to accept? or whatever is possible to get rid of this globally

**Comment by mapx-** [comment]
There are no general solutions.
However, these "popups" are managed by specific lists:
Fanboy’s Annoyance
or/ and Adguard annoyances.

**Comment by uBlock-user** [comment]
`||consensu.org^$3p` should block any such popups everywhere.

**Comment by mapx-** [comment]
Unfortunately lot of pages will be broken (see the exception filters in fanboy's list)

**Comment by uBlock-user** [comment]
> Unfortunately lot of pages will be broken

It's already blocked like this in Adguard Annoyances, haven't seen any breakage so far.

**Comment by mapx-** [comment]
- our unbreak list has 3 filters to unbreak such breakages
- fanboy's list 3 exceptions
- adguard list other 23 exceptions.

**Comment by uBlock-user** [comment]
and what does it break anyway ?

**Comment by llacb47** [comment]
Sometimes videos/other embeds rely on cookie scripts to load properly

**Comment by mapx-** [comment]
`sourceforge.net` case => the downloads (countdown) are broken

**Comment by uBlock-user** [comment]
> sourceforge.net case => the downloads (countdown) are broken

It's not broken, it's fastens on my side and I get the download immediately. I tested all the 3 cases from unbreak list, one doesn't use that third-party script anymore, another has no issue whether you load that script or block it and the source-forge one as mentioned fastens the countdown timer and you get the download immediately.

**Comment by mapx-** [comment]
It was added time ago, so I don't with default settings how is right now.

**Comment by LGLTeam** [comment]
Ok I will try both annoyances list
