### ISSUE TITLE
sledujserialy.to anti-adblock

### ISSUE THREAD

**Issue by pepablock** [uBlockOrigin/uAssets#7139]
### URL(s) where the issue occurs

`https://sledujserialy.to/episode/magicians-the-s05e09`

### Describe the issue

anti-adblock (Vypnite AD Block v prehliadači)

### Screenshot(s)

![obrazek](https://user-images.githubusercontent.com/29940017/77256393-359e7180-6c6e-11ea-9c53-7c86daaeed20.png)

### Versions

- Browser/version: Firefox 74.0 (64-bit)
- uBlock Origin version: uBlock Origin 1.25.2

### Settings

default settings

### Notes

―

**Comment by mapx-** [comment]
needing account ?

**Comment by Fikus444** [comment]
No account needed.

**Comment by Fikus444** [comment]
You might need a Slovak or Czech IP, not sure about that, as I havent tried it with other IPs.

**Comment by mapx-** [comment]
yeah, needing czech ip

**Comment by uBlock-user** [comment]
Yes you need one, it says right there - `Pre sledovanie zo zahraničia je potrebné sa registrovať.(For monitoring from abroad it is necessary to register.)`

**Comment by mapx-** [comment]
yeah, I got one via hola, fixed already

**Comment by pepablock** [comment]
Thanks for a quick fix, but still having some issues when trying to play a video as it won't start playing. Any way to fix this?

**Comment by mapx-** [comment]
I clicked on the right side of the video, click again on one of those thumbnails and then I an able to play the video

**Comment by Fikus444** [comment]
I was able to workaround it the same way you did, but not anymore, after updating the filters the screen is "frozen", I can click how much I want, nothing happens, not even with the right side with the multiple sources for the video.

**Comment by mapx-** [comment]
ok, I removed a bad filter. Now is like before (you can use again the workaround)

**Comment by uBlock-user** [comment]
The ad-iframe will appear again without that filter, what was it breaking ?

**Comment by mapx-** [comment]
> after updating the filters the screen is "frozen", I can click how much I want, nothing happens

**Comment by uBlock-user** [comment]
That happens with all Netu video players, play button never works

**Comment by mapx-** [comment]
Now it works after removing that filter.

**Comment by Fikus444** [comment]
Yeah, now I just click the "X" 3 times, and after that I can click on the right side of the player and choose one of the sources and the video will play. But also that workaround stopped working for a bit today, even before your filter, and it said "turn of ad block in your broowser" (thats why we posted here), but after your last commit it just works as before, no idea why .

**Comment by mapx-** [comment]
It works now due to the first filter in this thread:
https://github.com/uBlockOrigin/uAssets/commit/717fe9753af233d20e05de041bd4a2a9b92234b3

**Comment by Fikus444** [comment]
Oh ok, thank you for that then.

**Comment by uBlock-user** [comment]
Was missing an additional filter --

```
||sledujserialy.to/theme/json/episode.ad.php^$subdocument
sledujserialy.to##div[id][style="position: absolute; top: 0; left: 0; width: 100%; height: 380px; text-align: center;"]

```
Try that out. Works as before, but without that ad-frame and without having to close it 3 times.

**Comment by Fikus444** [comment]
Yeah it works now, I dont have to click the "X" as there isnt any, I just click the right side and choose a source. Thanks

**Comment by uBlock-user** [comment]
Thanks, I will add those filters then.

**Comment by mapx-** [comment]
adding now `waaw.tv#@#+js(aopr, BetterJsPop)`
You don't need the workaround anymore, a new window opens and get there the running video

**Comment by uBlock-user** [comment]
@mapx- That will now cause a popup to appear. Instead replace that filter with `waaw.tv##+js(window.open-defuser)` , no popups/under and the play button works without a workaround.
