### ISSUE TITLE
nwolb.com

### ISSUE THREAD

**Issue by matthew1471** [uBlockOrigin/uAssets#714]
### URL(s) where the issue occurs

https://www.nwolb.com/

### Describe the issue

Natwest have progressively been increasing their adverts and nags. The homepage now has an overlay encouraging you to install something.

### Notes

Have created my own filters to block but not sure how to get them included:

! Natwest Adverts
|https://www.natwest.com/images/campaigns/personal/olb/|
www.nwolb.com###ctl00_header_ctl00_globalTopNav
www.nwolb.com###ctl00_salesOnline_ctl00_ourProducts
www.nwolb.com###ctl00_mainContent_AS5PC1_yourMessagesContainer
www.nwolb.com###splash-*

**Comment by SMed79** [comment]
The site require a login! 
Post screenshots of the ads and [the logger](https://github.com/gorhill/uBlock/wiki/The-logger).

**Comment by matthew1471** [comment]
I don't really want to provide screenshots to my bank account. Would someone else with a Natwest account be able to test?
