### ISSUE TITLE
newsbreak.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#7140]
### URL(s) where the issue occurs

`https://www.newsbreak.com/news/0NvSAGa7/supervisors-pass-firearm-safe-haven-resolution`

### Describe the issue

`An unexpected error has occurred.`

### Notes

`@@outbrain.com`

**Comment by llacb47** [comment]
`newsbreak.com##+js(set, OBR.extern.renderSpaWidgets, noopFunc)`
