### ISSUE TITLE
13tv.co.il / 13news.co.il - anti-adblock

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#7142]
https://github.com/easylist/EasyListHebrew/issues/338

Video is blocked.
Default settings + EasyList Hebrew

What do you suggest?

Thanks

**Comment by llacb47** [comment]
This video (`https://13tv.co.il/item/featured-series/shnot-hashmonim/season-05/clips/lbomh-2007292/`) is working fine for me

**Comment by mapx-** [comment]
All fine for me too - but only using am israelian ip

**Comment by uBlock-user** [comment]
`@@||13tv.qamesh.com/Images/advert.png^$image,domain=13tv.co.il` 

How about that ?

**Comment by mapx-** [comment]
@uBlock-user test using the hebrew list

**Comment by uBlock-user** [comment]
Can't reproduce, this filter is already present there, although video doens't play or gets fetched. geo locked ?

**Comment by IsraeliUser** [comment]
I get an anti-adblock message... no video.
Maybe try clicking on multiple videos / live streaming.

**Comment by llacb47** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7142#issuecomment-602720867 It appears that it's supposed to be geolocked, with us ip i get 403 forbidden with one browser but the video plays fine in another

**Comment by mapx-** [comment]
I get anti adb only disabling hebrew list, otherwise the video is working fine with isr ip

**Comment by IsraeliUser** [comment]
Can you have a look at their anti-adblock source code? Maybe it applies only to users from Israel.
Also try using Private Browsing.

**Comment by mapx-** [comment]
in private browsing does not work but still no anti adb message

**Comment by mapx-** [comment]
try replacing 
`@@/advert.$image,domain=13news.co.il|13tv.co.il`

```
@@/advert.$image,domain=13news.co.il|13tv.co.il,badfilter
*$image,redirect-rule=2x2.png,domain=13tv.co.il
```

**Comment by IsraeliUser** [comment]
OK
What do you get in private browsing?

**Comment by mapx-** [comment]
black screen even using isr ip

**Comment by IsraeliUser** [comment]
Strange, because private browsing works for me with anti-adblock

**Comment by IsraeliUser** [comment]
@KuchiSofts
Can you reproduce?

**Comment by KuchiSofts** [comment]
> @KuchiSofts
> Can you reproduce?

so after updating the EasyListHebrew-uBO.txt it still not working ...
then I tried private browsing and still not working
then I used nordvpn (Israeli IP) is worked 
and after I closed the nordvpn it's still working

**Comment by krystian3w** [comment]
Backup settings in uBO and try reset to stock configuration?
