### ISSUE TITLE
Search Engine of Chrome and uBO logs

### ISSUE THREAD

**Issue by NubN** [uBlockOrigin/uAssets#7143]
Hi, maybe this is a stupid post, but I never noticed before this issue

when i want to find a specific word in uBO logs (**Ctrl + F**), only appears if is displayed on the screen.

example with no results: https://i.imgur.com/ssZ3bPF.png

i need scroll down for find the words:  https://i.imgur.com/hEkVd3c.png

I mean, the search engine doesn't take me directly to the speficic word.

**Comment by uBlock-user** [comment]
Use the filter box of uBO logger instead of using browser's search feature, that will do as you want.

**Comment by NubN** [comment]
ok sorry for the inconvenience.

**Comment by gwarser** [comment]
Why this happens: https://github.com/uBlockOrigin/uBlock-issues/issues/946#issuecomment-599216314
