### ISSUE TITLE
YouTube History Progress Bar Broken

### ISSUE THREAD

**Issue by macheteBadger** [uBlockOrigin/uAssets#7148]
### URL(s) where the issue occurs

`https://www.youtube.com/` (logged in)

### Describe the issue

The watch history progress bar that appears on the bottom of YouTube thumbnails does not progress from the starting point (0:00) no matter if the video has been watched in its entirety or half way through, only occurs when uBlock Origin is enabled across multiple browsers, reverts to default behaviour when disabled.

### Screenshot(s)

![proof](https://user-images.githubusercontent.com/30734970/77436695-758b6300-6dec-11ea-9108-8c4b20c97c66.png)

### Versions

- Browser/version: Chrome 80.0.3987.149 / Firefox 74.0
- uBlock Origin version: 1.24.4 / 1.25.2

### Settings

- Default settings

### Notes

As someone who relies on the recommendations of videos on YouTube's homepage and sidebar, this populates them with all the videos I've already watched and won't be discarded as watched and to apply to the algorithm for new videos. Issue began happening about a week ago, around the time possibly when YouTube ads were not being blocked for a while, YouTube is perhaps looking for the presence of ads to monitor the position of the video and could be broken. Tested on Chrome, Firefox and Edge, on Windows and Linux, with a VPN on and off, and videos only report their correct watched positions when uBlock Origin is disabled.

**Comment by gwarser** [comment]
Try adding `@@||youtube.com/api/stats/watchtime*` to My filters.

Related: https://www.reddit.com/r/uBlockOrigin/comments/flfftx/bug_youtube_not_saving_progress_in_long_videos/

Some people still report problems: https://www.reddit.com/r/uBlockOrigin/comments/fn1ays/youtube_watch_history_wont_progress/

**Comment by mapx-** [comment]
@macheteBadger did you update all your lists ?
a fix was added yesterday by easyprivacy:
https://github.com/easylist/easylist/commit/f0ad685fbf887b87f5b672e27a2e4555bd092f62

**Comment by macheteBadger** [comment]
Yes, thank you everything is good now! I will close the issue.
