### ISSUE TITLE
poiskvps.ru

### ISSUE THREAD

**Issue by FindVPS** [uBlockOrigin/uAssets#7149]
### URL(s) where the issue occurs

`https://poiskvps.ru/` 

### Describe the issue

Too much ads on header and footer and uBlock do not help

### Versions

- Browser/version: Chromium  80.0.3983.0 
- uBlock Origin version: 1.24.4

### Settings

I try to enable all filters

### Notes

Please help to hide ads on this site

**Comment by mapx-** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Ok: https://hg.adblockplus.org/ruadlist/rev/9fa0a92891df

**Comment by FindVPS** [comment]
> Ok: https://hg.adblockplus.org/ruadlist/rev/9fa0a92891df

Please add also this green blocks (this is ad too)
`<div class="forumbg forumbg-table" style="background-image:none; background-color:#00A857;">`

**Comment by mapx-** [comment]
@FindVPS for other issues with russian sites just report directly here:
https://forums.lanik.us/viewforum.php?f=102

**Comment by dimisa-RUAdList** [comment]
https://hg.adblockplus.org/ruadlist/rev/322b7a92b94e
