### ISSUE TITLE
Costco.com

### ISSUE THREAD

**Issue by Khosla1** [uBlockOrigin/uAssets#715]
### URL(s) where the issue occurs
`https://www.costco.com/Kirkland-Signature-Diced-Tomatoes-14.5-oz-8-pack.product.100334857.html`

### Describe the issue

Click on Reviews
Click Write a review
Can't submit review

### Screenshot(s)

![costco](https://user-images.githubusercontent.com/30167016/30778928-bdbe7dcc-a0af-11e7-8f0b-1170ee0bb21e.png)

### Versions

- Browser/version: Chrome 61.0.3163.100 (Official Build) (64-bit)
- uBlock Origin version:  1.14.8

### Notes
Is this caused by hlserve being blocked?

**Comment by okiehsch** [comment]
Does adding
`||mpsnare.iesnare.com/snare.js$script,redirect=noopjs,domain=costco.com`
to your filter list work for you?

**Comment by Khosla1** [comment]
No. Can't submit a review. Should hlserve be allowed?

**Comment by okiehsch** [comment]
> Get  the message "Please disable any ad blockers, which can prevent successful review submission."

You still get that message after adding `||mpsnare.iesnare.com/snare.js$script,redirect=noopjs,domain=costco.com`?
I don't.

>  Should hlserve be allowed?

Does not work for me, I still get the message if I add `@@||hlserve.com/Delivery/*$script,domain=costco.com`

**Comment by Khosla1** [comment]
The issue is that I can't submit review. I've edited the original: https://github.com/uBlockOrigin/uAssets/issues/715

**Comment by okiehsch** [comment]
Ah, ok sorry, I misunderstood. so can you submit a review if you allow hlserve by adding
`@@||hlserve.com/Delivery/*$script,domain=costco.com`

**Comment by Khosla1** [comment]
No, see https://www.costco.com/Kirkland-Signature-Diced-Tomatoes-14.5-oz-8-pack.product.100334857.html

**Comment by okiehsch** [comment]
`@@||mpsnare.iesnare.com/snare.js$script,domain=costco.com`
works for me,

**Comment by Khosla1** [comment]
Works for me with:
@@||hlserve.com/Delivery/*$script,domain=costco.com
@@||mpsnare.iesnare.com/snare.js$script,domain=costco.com

**Comment by gotitbro** [comment]
@okiehsch But the use said allowing only `iesnare` doesn't work even `hlserve` has to be allowed. Allowing only `iesnare` worked for you? Is what works on the developers side always taken into consideration?

**Comment by okiehsch** [comment]
I tried with Chrome and Firefox and it works on my end.
How about you
1. Disable `@@||hlserve.com/Delivery/*$script,domain=costco.com` by overwriting it via `important`
2. Go to 
`https://www.costco.com/Kirkland-Signature-Diced-Tomatoes-14.5-oz-8-pack.product.100334857.html`
3. Register, you can use a junk mail account and
4. Click on Reviews
5. Click Write a review
6. Click on for example  4 stars
7. Click Post Review
Result: The screenshot of the op.
8. Now the same steps without overwriting the filter
Result, it works on my end-

**Comment by gotitbro** [comment]
I didn't add the `hlserve` filter at all and just whitelisting `iesnare` worked for me as well. So yeah your fix should work.

Also what did you mean by the first step?

> Disable @@||hlserve.com/Delivery/*$script,domain=costco.com by overwriting it via important

**Comment by Khosla1** [comment]
I'm able to post a review with only @@||mpsnare.iesnare.com/snare.js$script,domain=costco.com

**Comment by okiehsch** [comment]
@gotitbro if you had already updated the `uBO-filter` list you would have to add
`||hlserve.com/Delivery/*$script,important,domain=costco.com`, to be able to reproduce the original issue.

@Khosla1 thx for the feedback
