### ISSUE TITLE
Youtube Music not working with uBlock filter

### ISSUE THREAD

**Issue by NogrTL** [uBlockOrigin/uAssets#7152]
### URL(s) where the issue occurs
`https://music.youtube.com/`

### Describe the issue

Filter `||youtube.com/get_video_info?$1p` stops service from playing music

### Versions

- Browser/version: MS Edge Version 82.0.453.2
- uBlock Origin version: v1.23.0

### Settings and Log

https://gist.github.com/NogrTL/3e243f7b0cf475a8e2fdbcaccb8206a9

### Notes
It works when I added `||youtube.com/get_video_info?$1p,badfilter` to my static filters

**Comment by mapx-** [comment]
if you update easylist (better purge all caches + update) you'll get in the logger this exception:
`@@||youtube.com/get_video_info?$xmlhttprequest,domain=music.youtube.com|tv.youtube.com`
