### ISSUE TITLE
imagebam.com pop-under

### ISSUE THREAD

**Issue by kasper93** [uBlockOrigin/uAssets#716]
### URL(s) where the issue occurs

`http://www.imagebam.com/image/b309bb594936573`

### Describe the issue

1. Clear or disable cookies for this site
2. Go to next image in gallery (arrow button)
3. Pop under will be opened. Some delivery site will redirect you to advert page. Sometimes it is closed, but most time it is not. Preferably delivery site should be blocked to prevent the issue.  (beware, it might redirect to nsfw content)

### Versions

- Browser/version:  58.0a1 (2017-09-23)
- uBlock Origin version: 1.14.11rc0

**Comment by mapx-** [comment]
`imagebam.com##script:inject(abort-on-property-read.js, __ads)`
or
`@@||imagebam.com^*ad$script`

**Comment by gotitbro** [comment]
@gorhill Are static/conventional filters always preferred over script injecting ones?

**Comment by SMed79** [comment]
an alternative
`/syndication.*?idzone=$popup`

**Comment by kasper93** [comment]
@SMed79 : Doesn't work. And that's weird because it should. I've added `/syndication.*?idzone=$popunder,popup,document` and popunder is not closed, but as expected it is blocked because of `document` part. Can you confirm that popunder is not closed?

**Comment by kasper93** [comment]
@SMed79: Probably need to mark it as popunder `||syndication.*?idzone=$popunder,popup,document` 

Not sure how common it is, but might actually help also with other sites.
