### ISSUE TITLE
kissanime updated there ad-block detection

### ISSUE THREAD

**Issue by Iaycomand** [uBlockOrigin/uAssets#7162]
### URL(s) where the issue occurs

`https://kissanime.ru/`

### Describe the issue

the site blocked me for using ublock and showing access denied page after certain amount of time.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/39984795/77790210-17b97e00-706d-11ea-8151-918a6a8c439f.png)

### Versions

- Browser/version: Google Chrome Version 80.0.3987.149 (Official Build) (64-bit)
- uBlock Origin version: v1.24.4

**Comment by uBlock-user** [comment]
Don't use a VPN or a proxy there, you will be banned and see that page.

**Comment by Iaycomand** [comment]
I don't use vpn nor porxy, also there's an unofficial subreddit for this site and all users was talking about having the same issue.

**Comment by uBlock-user** [comment]
Remove all your cookies and foce update uBlock Filters list, the anti-adblock issue was resolved yesterday itself.

**Comment by mapx-** [comment]
chrome, beta server, no issues on my side

**Comment by Yuki2718** [comment]
Brave & beta server, no issue - video is working more than 10 min without any problem.

**Comment by llacb47** [comment]
On default settings, I get this anti-adblock:

![image](https://user-images.githubusercontent.com/16567977/77862337-c33b0d80-71e8-11ea-8cc8-709884e82642.png)


Fixed with `kissanime.*##+js(acis, AddCloseButton)`
