### ISSUE TITLE
http://www.risultati.it/tennis/

### ISSUE THREAD

**Issue by mapx-** [uBlockOrigin/uAssets#717]
`http://www.risultati.it/tennis/`

- click somewhere on page ==> a popup is generated and  closed by this rule:
`||bet365.com^*affiliate=$popup`

To reproduce again just delete the `popunder` entry in the local storage.

How can be completely inhibited the popup / popunder (without breaking the page) ?

Version 62.0.3202.29 (Official Build) beta (64-bit)
uBo  1.14.8, default filters

**Comment by gorhill** [comment]
How is the following?

    risultati.it##script:inject(abort-on-property-read.js, open)

**Comment by gorhill** [comment]
Never mind, I see the site make use of legitimate popup windows.

**Comment by gorhill** [comment]
I created a new scriptlets to enable filtering `window.open` according to the URL argument, but then I can no longer reproduce the popup issue on that site.

**Comment by mapx-** [comment]
Me neither.
However, the code seems to be still there (in the main page and in the core js)

The deobfuscated code from `http://www.risultati.it/x/js/core_6_1358000000.js`
https://mega.nz/#!fIZRiJYK!BrT0o3p9iqRVDGuuWAmx-naCYMKoCFkeaT6naVLvkQ0

**Comment by gorhill** [comment]
I tried again and still no popups, so closing.
