### ISSUE TITLE
foreignpolicy.com paywall

### ISSUE THREAD

**Issue by HermannBjorgvin** [uBlockOrigin/uAssets#7170]
### URL(s) where the issue occurs

`https://foreignpolicy.com/2020/03/25/blame-china-and-xi-jinping-for-coronavirus-pandemic/`

### Describe the issue

Modal popup with a paywall

I'm creating a pull request now for this issue.

### Versions

- Browser/version: Firefox 74.0-2
- uBlock Origin version: 1.25.2

### Settings

```
foreignpolicy.com##div.tp-modal
foreignpolicy.com##div.tp-backdrop
foreignpolicy.com##.tp-active.tp-backdrop
foreignpolicy.com##html>body.tp-modal-open:style(overflow: auto !important; height: auto; -webkit-overflow-scrolling: auto;)
```

### Notes

After hitting a paywall I created the following rules to start with:  
```
foreignpolicy.com##div.tp-modal
foreignpolicy.com##.tp-active.tp-backdrop
```

Then started with adding breakpoints to <body> since I noticed it is replacing classes for the paywall to appear. the class `tp-modal-open` on the <body> tag was blocking scrolling on the page so I created a filter which has more specific selector which overwrites those blocking values to `auto`.

`tp-modal-resizing` is a class that gets added to the <body> tag but it doesn't affect the page visual so I didn't create a rule for it.

At this point the paywall was removed but there was still a quick flash of black on the page when it popped up and before it was removed after a bit of investigating and adding breakpoints to the page to catch DOM attribute modifications I noticed `div.tp-backdrop.tp-active` was modifying it's class attribute and removing the `tp-active` class, this breaks the rules I added to block the paywall. It's a simple fix, create two rules, one with and one without the `tp-active` class.

**Comment by uBlock-user** [comment]
> Circumventing a paywall is considered out of scope
