### ISSUE TITLE
Ads on RARLAB (makers of WinRAR)

### ISSUE THREAD

**Issue by ericfriesen** [uBlockOrigin/uAssets#7172]
Ads on RARLAB (makers of WinRAR)

### URL(s) where the issue occurs
`https://www.rarlab.com/`

### Describe the issue
Ads in middle of screen:

> _Download featured software (advertisement)
> Protect your Windows Browser against dangerous websites on the internet. Totally free forever.
> 	Download Now
> 	Test Free Browser Protection
> Get Detailed Information about Threat Sites from leading Internet Security Companies on Mouseover. Protect your PC quickly and easily._

### Screenshot(s)
![image](https://user-images.githubusercontent.com/25352077/77973659-74f63f00-72ba-11ea-9892-8262e8d064c4.png)

### Versions
- Browser/version: [Firefox 74.0, Edge 80.0.361.103]
- uBlock Origin version: [1.25.2 for Firefox, 1.23.0 for Edge]

### Settings
- all default

### Notes
Has unsavory link to "Download Now" which one may inadvertently click in order to download WinRAR

**Comment by llacb47** [comment]
`rarlab.com##table:has(>tbody>tr>td>table>tbody>tr>.buyitems)`

**Comment by ericfriesen** [comment]
That works, just kills their store page. Real sad to see them do this.

**Comment by mapx-** [comment]
`_our shop_` is ok (self promo)

```
rarlab.com##.tplain:has(.adv)
rarlab.com##.rshift:has(.adv):nth-ancestor(1)
rarlab.com##.tbar2:has-text(advert)
```

**Comment by uBlock-user** [comment]
Self promos are not fixed as per Easylist policy.
