### ISSUE TITLE
uiz.app

### ISSUE THREAD

**Issue by RaveN0X87** [uBlockOrigin/uAssets#7174]
URL(s) where the issue occurs
`https://uiz.app/lopfb`

Describe the issue
Anti adblock

Screenshot(s)
<details>

![uiz](https://user-images.githubusercontent.com/39649317/78015922-476dcc00-7374-11ea-8856-e46949fafdd4.png)

</details>

Versions
uBlock Origin version 1.24.4

Browser/version
Google Chrome v80.0.3987.149 (Official Build) (64-bit)

Settings
uBO's default settings+nano defender

**Comment by uBlock-user** [comment]
Can't reproduce. Disabled all other extensions and test with uBO only.

**Comment by krystian3w** [comment]
Race condition with `aopr`?

**Comment by llacb47** [comment]
![image](https://user-images.githubusercontent.com/16567977/78048247-715cc980-7347-11ea-9a8e-54e3f5430a79.png)

I get this unless I disable Nano Defender. Weird
