### ISSUE TITLE
blocked by easylist

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#7179]
### URL(s) where the issue occurs

`d31mxuhvwrofft.cloudfront.net`
`d1qc76gneygidm.cloudfront.net`
`thefuncoolstuff.com`
`gadskis.com`
`powerapp.download`
`ampallall.site`
`ashamparm.site`
`aniashboy.club`
`special-offers.online`

third-party

`dc5k8fg5ioc8s.cloudfront.net`
`pushlat.com`
`pushosub.com`
`opsivesh.net`
`class2deal.com`
`psitchie.com`
`sadsoks.com`
`cadsabs.com`
`choogeet.net`
`dgafgadsgkjg.top`
`ig8al3mkou.com`
`7lstw4cd.top`
`onestepproductions.online`
`iskkrmwivxfmdjwxme.bid`
`koutobey.net`
`adgeiros.pw`
`dynamicadx.com`
`z6vmw.top`
`addan.xyz`
`doghoust.net`
`u595sebqih.com`
`zinrora.pw`
`s24hc8xzag.com`
`meryjane.pro`
`badsbads.com`
`superonclick.com`
`indlzxgptf.com`
`7hor9gul4s.com`
`newjulads.com`
`digitalpush.org`
`rgvqcsxqge.com`
`ehu96t2p.com`
`fadspmz.com`
`ogeemolt.net`

### Describe the issue

already blocked by easylist so no longer be needed in uBlock filters

**Comment by mapx-** [comment]
thx

**Comment by ghajini** [comment]
Some duplicates
```
||passeura.com^
##a[href^="http://mob1ledev1ces.com/"]
||asewlfjqwlflkew.com^
