### ISSUE TITLE
Styling/content broken for tabletpcreview.com

### ISSUE THREAD

**Issue by PrototypeNM1** [uBlockOrigin/uAssets#7181]
### URL(s) where the issue occurs

`http://www.tabletpcreview.com/`
`http://forum.tabletpcreview.com/`

### Describe the issue

Content (images) are broken while uBlock is enabled with default filters, excluding images in the title bar for the main page.

Content and styling seems broken for the forums.

### Screenshot(s)

Broken elements obvious.

### Versions

- Browser/version: Firefox 74.0
- uBlock Origin version: 1.25.2

### Settings

- Default settings, purged cache then updated filters.

### Notes

Verified page works when uBlock Origin is disabled for the site.

**Comment by mapx-** [comment]
CNAME
maybe
```
||techtarget.com^$badfilter,3p
||techtarget.com^$~image,3p
```

@ryanbr

**Comment by okiehsch** [comment]
There are also many scripts that are blocked by it.

**Comment by okiehsch** [comment]
The filter was added with https://github.com/easylist/easylist/commit/1f0f0a4a785606242c35e5684c4cedff68172a49

Maybe only block `trk.techtarget.com` or block the whole domain except `wptg-lb.techtarget.com` which appears to be their CNAME domain.

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/58311419e668d36a3ed004477de5d0dbdc041cfc

**Comment by PrototypeNM1** [comment]
The main website `http://www.tabletpcreview.com/` seems to be fixed so I assume the listed changes have taken place.

The forums `http://forum.tabletpcreview.com/` are still broken (see images). Should I create a new bug report?
![tpr broken](https://user-images.githubusercontent.com/2732021/78163866-cb1fcb00-73fd-11ea-9a62-ad830dc30a46.png)
![tpr working](https://user-images.githubusercontent.com/2732021/78163875-cc50f800-73fd-11ea-95bf-8a47f8a432eb.png)

**Comment by mapx-** [comment]
fixed
