### ISSUE TITLE
Tapatalk's forum post message's editor's toolbar is missing with uBlock filters – Annoyances​​​​​​​​​ subscription.

### ISSUE THREAD

**Issue by antdude** [uBlockOrigin/uAssets#7183]
### URL(s) where the issue occurs

`https://www.tapatalk.com/groups/tapatalksupport/posting.php?mode=post&f=98
or any forum to post in like my https://www.tapatalk.com/groups/antfarm/ (requires an account)` 

### Describe the issue

Tapatalk's forum post message's editor's toolbar is missing with uBlock filters – Annoyances​​​​​​​​​ subscription.

### Screenshot(s)
![TaptalkForumPostuBlockFiltersAnnoyances​​​​​​​​​](https://user-images.githubusercontent.com/998681/78179799-a5eb8680-7416-11ea-9d51-617a0d2fdab8.gif)

### Versions

- Browser/version: 64-bit SeaMonkey v2.53.1 and Firefox v74 in a decade old, 64-bit W7 HPE SP1 PC.
- uBlock Origin version: V1.16.4.20 legacy in SeaMonkey v2.53.1 and V1.25.2 in Firefox v74.

### Settings
Only checking "uBlock filters – Annoyances" in UO's Filter lists' Annoyances section after resetting UO's settings back to defaults.

### Notes
I was unable to figure out what is blocking it in UO's logger that showed no blockages.  Maybe it is this, but I can't figure how to allow this line to test (maybe missing something since I am still learning how to use UO to analyze):

`Details
 
Filtertapatalk.com##+js(abort-on-property-read, IS_VIP_PLUS)
Filter listuBlock filters – Annoyances 
Contextwww.tapatalk.com
Typedom
URLhttps://www.tapatalk.com/groups/tapatalksupport/posting.php?mode=post&f=98`

Copied and pasted from table's table and plain log formats:
`+1	##+js(abort-on-property-read, IS_VIP_PLUS)		www.tapatalk.com		dom	https://www.tapatalk.com/groups/tapatalksupport/posting.php?mode=post&f=98

+1
##+js(abort-on-property-read, IS_VIP_PLUS)
www.tapatalk.com
dom
https://www.tapatalk.com/groups/tapatalksupport/posting.php?mode=post&f=98`

**Comment by antdude** [comment]
Thank you for the quick fix, mapx! How long do I have to wait for this fix to be released?

**Comment by mapx-** [comment]
go into options / dashboard, `filter lists` tab, click `purge all caches`, click `update`
or wait for automatic updating but copy this filter in your `my filters` tab

`tapatalk.com#@#+js(abort-on-property-read, IS_VIP_PLUS)`

**Comment by antdude** [comment]
Thank you again, mapx-. :)
