### ISSUE TITLE
The domain adv.ec is broken

### ISSUE THREAD

**Issue by cesarizu** [uBlockOrigin/uAssets#7188]
### URL(s) where the issue occurs

`https://adv.ec/`

### Describe the issue

ADVEC is the (nascient) Ecuadorian Video-game Developers Association ("Asociación de Desarrolladores de Videojuegos Ecuatorianos" in spanish).

### Screenshot(s)

All pages are broken. This is the home page for example:
![Screenshot_2020-04-03 ADVEC – Asociación de Desarrolladores de Videojuegos Ecuatorianos](https://user-images.githubusercontent.com/658725/78371000-03a1df00-758d-11ea-8deb-bbde9b2d98c5.png)

### Versions

- Browser/version: Firefox / 74.0 (64-bit)
- uBlock Origin version: 1.25.2

### Settings

- Default

### Notes

It seems it's blocked because there are rules for `adv.DOMAIN` that assume that adv stands for advertisement.

**Comment by mapx-** [comment]
It has to be fixed in easylist => this way will be fixed for all adblockers
@ryanbr
