### ISSUE TITLE
Ad on https://kenshi.fandom.com/wiki/Shinobi_Thieves

### ISSUE THREAD

**Issue by KittyJutsu** [uBlockOrigin/uAssets#7190]
### URL(s) where the issue occurs

`https://kenshi.fandom.com/wiki/Shinobi_Thieves`

### Describe the issue

There's a video ad at the top of the page.

### Screenshot(s)

https://files.catbox.moe/v1mzln.png

### Versions

- Browser/version: Firefox Nightly 76.0a1
- uBlock Origin version: 1.25.2

### Settings

- Default lists + EasyListFR

**Comment by mapx-** [comment]
I get the video only disabling uBO.
Try resetting uBO to the defaulot settings, then purge all caches + update the lists

**Comment by THEtomaso** [comment]
@lain566:

> https://github.com/uBlockOrigin/uAssets/commit/ce9e0ed5e09bc31d78d257598937d3609b89aa01

This rule prevents some pages from opening:
`fandom.com##+js(set, ads, null)`

Example (try clicking on the big images):
`https://www.fandom.com/explore/`
