### ISSUE TITLE
Symbolab tells us to disable ad blocker.

### ISSUE THREAD

**Issue by fffelix-jan** [uBlockOrigin/uAssets#7192]
### URL(s) where the issue occurs

`https://www.symbolab.com/solver/step-by-step/9%2B10`

### Describe the issue

We get a popup telling us not to use our ad blocker.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/38475999/78404741-04f2fc00-75cd-11ea-889f-4ff4b5a550b4.png)

### Versions

- Browser/version: Chrome 80.0.3987.163
- uBlock Origin version: 1.24.4

### Settings

- Added EasyList Chinese and French

**Comment by uBlock-user** [comment]
Can't reproduce, this was updated recently, did you update uBlock Filters list ?

**Comment by fffelix-jan** [comment]
I tried updating all the filter lists, but it didn't work. Here's all the lists I have enabled:
![image](https://user-images.githubusercontent.com/38475999/78405190-f6591480-75cd-11ea-9ffd-ebb2bebc192f.png)

**Comment by uBlock-user** [comment]
Can you reproduce with only default lists ? Might want to try that.

**Comment by uBlock-user** [comment]
Nevermind I can reproduce it now.

**Comment by mapx-** [comment]
```
symbolab.com#@#.googleLeftSkyScrapper
symbolab.com##.adsbygoogle:style(max-height: 100px !important;)
```

**Comment by uBlock-user** [comment]
or

`symbolab.com##.tooltipster-content`

**Comment by mapx-** [comment]
maybe `symbolab.com##.tooltipster-box`
