### ISSUE TITLE
NSFW dood.watch

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7193]
### URL(s) where the issue occurs

`https://dood.watch/e/vph7z3b4lagb4e00xrfi6ae1x0weits`

### Describe the issue

Anti-adblock: this fix https://github.com/NanoMeow/QuickReports/issues/3437 doesn't work on Chromium (~~but works on Firefox~~ EDIT: I forgot to remove the whitelist so not sure).

### Screenshot(s)

<details>

![dood](https://user-images.githubusercontent.com/58900598/78414880-51841900-7659-11ea-9c42-b6d0e66f6ee2.png)

</details>

### Versions

- Browser/version: Brave 1.5.115 & 1.5.123 (its blocker turned off)
- uBlock Origin version: 1.24.4

### Settings

- Default
### Notes

`@@||i.doodcdn.com/ads/pop.js|$script,domain=dood.watch` worked and three properties are set by this script.

**Comment by Yuki2718** [comment]
It seems their server is very unstable and I now can't access.

**Comment by okiehsch** [comment]
> Anti-adblock: this fix NanoMeow/QuickReports#3437 doesn't work

That issue and the corresponding fix was not about an anti-adblock message.
I can't access either, I get a connection timed out error.

**Comment by uBlock-user** [comment]
site is down

**Comment by Yuki2718** [comment]
> 
> That issue and the corresponding fix was not about an anti-adblock message.

Sorry, missed that. BTW AdGuard's fix: https://github.com/AdguardTeam/AdguardFilters/issues/51861

**Comment by uBlock-user** [comment]
Site is now accessible, but the link is 404, need a working link/

**Comment by Yuki2718** [comment]
> 
> 
> Site is now accessible, but the link is 404, need a working link/

Not only that particular link, all links I could find. I guess dudestream.com (which calls dude.watch) is still down.
![dudestream](https://user-images.githubusercontent.com/58900598/78425115-67bbc480-76ad-11ea-9d2e-632b5d62be70.png)

**Comment by uBlock-user** [comment]
`https://dood.watch/e/aqk4vrexlnuc` is working.

**Comment by Yuki2718** [comment]
Yet I don't see anti-adblock for the link.

**Comment by uBlock-user** [comment]
script is present though, so I added it anyways incase it decides to flare up.
