### ISSUE TITLE
[Anti-AdBlock] `https://www.businessinsider.com`

### ISSUE THREAD

**Issue by Dentrax** [uBlockOrigin/uAssets#7196]
### URL(s) where the issue occurs

`https://www.businessinsider.com/meet-zoom-billionaire-eric-yuan-career-net-worth-life`

### Describe the issue

It detects that i am using an ad-blocker.

### Screenshot(s)

![Annotation 2020-04-04 200722](https://user-images.githubusercontent.com/16493751/78457011-efa2ce00-76af-11ea-86dd-5b6950f4f252.png)

### Versions

- Browser/version: `Firefox 74.0.1`
- uBlock Origin version: `1.25.2`

### Settings

- `default`

**Comment by okiehsch** [comment]
Works fine on my end.
