### ISSUE TITLE
Fanboy’s lists are breaking NextCloud servers

### ISSUE THREAD

**Issue by kolAflash** [uBlockOrigin/uAssets#7199]
If a user enables one of the Fanboy’s filter lists, the `Share` button in NextCloud won't be accessible anymore.
- `Fanboy’s Social​​​​​`
- `Fanboy’s Annoyance​​​​​​​​​`
&nbsp;

See here for details:
https://github.com/nextcloud/server/issues/19908

You can use this public NextCloud installation for testing.
https://try.nextcloud.com
Nevertheless don't forget: This affects every NextCloud installation, not just *.nextcloud.com

Tested with: Firefox-74 (Linux & Windows)

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by uBlock-user** [comment]
Does adding `@@||nextcloud.com^$ghide` unbreak the site ?

**Comment by kolAflash** [comment]
> Does adding `@@||nextcloud.com^$ghide` unbreak the site ?

Please try yourself on https://try.nextcloud.com

Nevertheless: A fix for a single domain isn't helpfull. There are a lot of NextCloud servers out there.
It's a software like WordPress, not a single website.

**Comment by uBlock-user** [comment]
> Please try yourself on https://try.nextcloud.com

I did and works for me.

> Nevertheless: A fix for a single domain isn't helpfull. There are a lot of NextCloud servers out there. It's a software like WordPress, not a single website.

It's not a part of default filterlists in uBO so won't be fixed in uBO's unbreak list. I have though contacted the Fanboy lists maintainer as to let him know about this.

**Comment by kolAflash** [comment]
> I have though contacted the Fanboy lists maintainer as to let him know about this.

Thanks!
Is there an issue for Fanboy which I can follow?

**Comment by uBlock-user** [comment]
@kolAflash https://github.com/ryanbr/fanboy-adblock/issues

**Comment by kolAflash** [comment]
thx !
https://github.com/ryanbr/fanboy-adblock/issues/1225

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/51643#issuecomment-599787060

helps only global disable 2 filters:

```
#@##sharing
#@#.icon-share
```
