### ISSUE TITLE
Gamepedia anti-ads

### ISSUE THREAD

**Issue by madisotenurm** [uBlockOrigin/uAssets#72]
### URL(s) where the issue occurs

`minecraft.gamepedia.com`
`dota2.gamepedia.com`
`terraria.gamepedia.com`
and other Gamepedia subdomains

### Describe the issue

Despite using several default ad lists, there are still some ads on Gamepedia articles at the top, right and bottom. Note that rightmost ads scroll with the page.

### Screenshot(s)

[Imgur album](https://imgur.com/a/9rai9). Signed in username (top right) has been blacked, no other changes are made.

### Versions

- Browser/version: Google Chrome 52.0.2743.49 beta-m (64-bit)
- uBlock Origin version: v1.7.6

### Settings

- Hide blocked element placeholders
- Cloud storage
- Privacy options: disable preload, disable audit/beacon, prevent WebRTC leaks
- [Filters enabled](https://imgur.com/CpcK5cw) + cosmic filters enabled
- Custom filters: mostly Facebook-related, irrelevant
- 2 irrelevant rules
- several pages whitelisted

### Notes

Made custom filters with element picker to remove those ads, proposing to add them to uBlock filters list:

`minecraft.gamepedia.com###siderail`
`minecraft.gamepedia.com###btflb`
`minecraft.gamepedia.com###atflb`

Note that the subdomains can vary as described above, I just don't know uBlock's wildcard syntax.

**Comment by IDKwhattoputhere** [comment]
Try:
`||cdm.cursecdn.com^$third-party`

**Comment by madisotenurm** [comment]
@IDKwhattoputhere That mostly works, but leaves empty space to top and bottom banners, and some of the sidebar remains.
https://gyazo.com/9d131e4384756953856467f89ec92032

**Comment by gorhill** [comment]
> Note that the subdomains can vary as described above, I just don't know uBlock's wildcard syntax.


It's just standard ABP filter syntax:

    gamepedia.com###siderail
    gamepedia.com###btflb
    gamepedia.com###atflb

The filters propagate to all subdomains as well. Can you submit these to [EasyList maintainers](https://forums.lanik.us/viewforum.php?f=62)?

**Comment by madisotenurm** [comment]
Thanks, done!
