### ISSUE TITLE
BlockAdblock

### ISSUE THREAD

**Issue by rakmaty1** [uBlockOrigin/uAssets#7200]
### URL(s) where the issue occurs

`https://blockadblock.com/`
`https://superuser.cz/`

### Describe the issue

If you visit website with this BlockAdblock script, after few seconds, the content is replaced with a notice that you should turn off your adblock.

### Versions

- Browser/version: Firefox 74.0.1
- uBlock Origin version: 1.25.2

### Settings

- Only added my regional filters.

**Comment by okiehsch** [comment]
I fixed `superuser.cz`.

`blockadblock.com` will not be fixed in uAssets. It is considered a proof of conceipt.
https://github.com/gorhill/uBlock/issues/1271#issuecomment-182831923
Add
`blockadblock.com##+js(nobab)`
to your filter list.
