### ISSUE TITLE
mega.nz video AD

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#7202]
### URL(s) where the issue occurs

`https://animeblix.com/boku-no-hero-academia-temporada-4-episodio-25-UzyNwErv`

### Describe the issue

Ad in video

### Screenshot(s)

click in mega: https://i.imgur.com/zheu5ZC.png

ad: https://i.imgur.com/PToFSHC.png
### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [v1.24.4]

### Settings

- Default

### Notes

embed video in `animeblix.com`:

`https://mega.nz/embed#!XUhVXbSD!yjeq5-igC6lQpVZjOrezJlPduqRbMCZXGEbq42ZGkUI`

**Comment by uBlock-user** [comment]
Mega sets a CSP so scriptlets will not work on Firefox and `json-prune` doesn't stop the ads from getting loaded even we disable CSP on Firefox.

**Comment by uBlock-user** [comment]
Setting localStorage item `pra` to `{"1":5488572}` works.

**Comment by uBlock-user** [comment]
For Chromium browsers, where site CSP is not an issue, this scriptlet works --

```
(() => {
		'use strict';
		const item = '{{1}}';
		if ( item === '' || item === '{{1}}' ) { return; }
		const setItem = ev => {
		 			   if (ev) { window.removeEventListener(ev.type, setItem, true); }
					   try {
							if (localStorage.getItem(item) !== null) { return; }
							localStorage.setItem(item, '{"1":9999999}');
					   } catch { }
		};
		if (document.readyState === 'loading') {
		    	    window.addEventListener('DOMContentLoaded', setItem, true); 
	   	} else {
		    	    setItem();
	   	}
})();
```

**Comment by mapx-** [comment]
not fixable with the current weapons

**Comment by ghajini** [comment]
Why labelled "won'tfix" if there are chances gorhill will fix in near future?

May be good label= ***Currently No Solution***

**Comment by llacb47** [comment]
Probably to add a localstorage scriptlet we would need a few more use cases on other sites.

**Comment by uBlock-user** [comment]
> Why labelled "won'tfix" if there are chances gorhill will fix in near future?

It will be removed when a fix is added, untill label is clarification.

**Comment by gorhill** [comment]
I am not subscribed to receive notifications from here.

Whenever there are cases that are unsolvable with current arsenal, please mentions me. I have to be aware of all these case for me to understand what is missing in uBO and what is worth to work on. It's also useful to know whether other blockers can deal with these.

**Comment by llacb47** [comment]
The code is open source: https://github.com/meganz/webclient/blob/8bbb12ca0489de74792274459584aed485270f76/js/utils/media.js#L1434

**Comment by PIZZA90** [comment]
a filter of this style would work?: `Content-Security-Policy` 

`||mega.nz^$csp=script-src etc..` 🤔

**Comment by llacb47** [comment]
why closed?

**Comment by gwarser** [comment]
@llacb47 They stopped playing ads? I think someone mentioned this on Reddit.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/9528#issuecomment-873414958

**Comment by MixusMinimax** [comment]
There are ads again as of today in mega.

**Comment by stephenhawk8054** [comment]
@MixusMinimax Can you give exact link where you see the issue? Also please open new tab > reproduce the issue and on that page > click on uBO icon > 💬 [Report button](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-tools) > scroll to the bottom > click on Troubleshooting Information and copy paste it here.
