### ISSUE TITLE
adshrink.it adblock detected

### ISSUE THREAD

**Issue by simoconfa** [uBlockOrigin/uAssets#7206]
### URL(s) where the issue occurs

`https://adshrink.it/5AP7F3`

### Describe the issue

Adblock detected

### Screenshot(s)

![immagine](https://user-images.githubusercontent.com/8224154/78794808-7ad3da80-79b4-11ea-826b-370ea6fa4183.png)

### Versions

- Browser/version: FF latest
- uBlock Origin version: latest

### Settings

No filters affecting it. Filters just updated. I have disabled cosmetic filter.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/bb63f3002badcc835c3c9bce35c8db61d7eb39cb

**Comment by stephenhawk8054** [comment]
Incorrect blocking now.

URL: `https://adshrink.it/BNZfOP` (NSFW)

Expect:

![image](https://user-images.githubusercontent.com/66517106/140729673-5159b2f4-e907-482d-8492-ba9724a8d31a.png)

Issue:

![image](https://user-images.githubusercontent.com/66517106/140729715-49a836e5-514b-41a5-ae04-91713b2661ea.png)

Firefox 94.0.1, ublock 1.38.6 default settings.

Proposed filters:

```
||adshrink.it^$document,csp=style-src *,badfilter
@@||cdn.trackjs.com/agent/v*/latest/t.js$script,domain=adshrink.it
```
