### ISSUE TITLE
Anti-adblock on aternos.org

### ISSUE THREAD

**Issue by Thedeur** [uBlockOrigin/uAssets#7207]
### URL(s) where the issue occurs

aternos.org/server/

### Describe the issue

Every page is plagued with an adblock page, and clicking "Continue with adblocker anyway" leads to a 3-second countdown before content is loaded. Using Element Picker doesn't work, as the entire body of the page is erased as well. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/49797800/78930296-16228980-7a61-11ea-9fb0-aa25d9b0bde4.png)

### Versions

- Browser/version: Firefox 75.0 (x64)
- uBlock Origin version: 1.26.0

### Settings

Everything here should be default. 

### Notes

I'm aware that this seems to be a recurring thing, uBlock warring with this site. I wasn't sure whether to open a new issue or comment on the existing one, which was already marked closed.

**Comment by llacb47** [comment]
Update your filter lists.

**Comment by llacb47** [comment]
https://github.com/uBlockOrigin/uAssets/pull/7208

**Comment by Thedeur** [comment]
Sorry for late response-- I updated my filters (by purging current caches, then clicking "Update Now"), and I still see the adblock page? I also disabled Firefox's tracking protection and Privacy Badger, if that helps.

**Comment by llacb47** [comment]
I can't reproduce... when you run this in the console what do you get? 
`$(".ad.responsive-leaderboard").css("min-height")`


Also what is the number displayed on the anti-adblock screen?

**Comment by Thedeur** [comment]
The Firefox console, right? I get "0.0333333px". The number on the block screen is #2711.

**Comment by llacb47** [comment]
Somehow this filter is not working: `aternos.org##+js(aeld, /error|load/, /^(.*_url)((?!-= 1).)*$/)`.

Do you see it in the logger?

**Comment by Thedeur** [comment]
Yes, I see it. 

![image](https://user-images.githubusercontent.com/49797800/79052178-e6ef5200-7bf1-11ea-9893-1b022d5a534e.png)

**Comment by llacb47** [comment]
if you add 
```
aternos.org#@#+js(aeld, /error|load/, /^(.*_url)((?!-= 1).)*$/)
aternos.org##+js(aeld, /error|load/)
```
to your custom filters do you  see error number 3139 on the anti adblock screen?

**Comment by Thedeur** [comment]
In the "My filters" section, right? I applied those, but it still doesn't change (I only closed and reopened the tab, so my cookies are still the same). Opening it in a new private window returns a different number, 27476.

**Comment by llacb47** [comment]
It seems like the scriptlet is not working correctly and your installation of ubo could be broken.
What do you see at `https://firefox-storage-test.glitch.me/`?

**Comment by Thedeur** [comment]
Firefox seems to report itself fine. 

![image](https://user-images.githubusercontent.com/49797800/79052420-a264b600-7bf3-11ea-98d9-808927443d5a.png)

Maybe I'll try this on another computer, and see if it works.

**Comment by llacb47** [comment]
You can also try:
1. reinstalling uBO
2. creating another firefox profile
3. refreshing firefox

**Comment by Thedeur** [comment]
I tried creating another profile, with uBO installed and with filters updated, and it's still the same result. 

Perhaps you should take a break first? I only raised this issue out of curiosity of why this one site wasn't working, and it's still somewhat usable while adblocked. Thanks for taking so much time.

**Comment by uBlock-user** [comment]
> I only raised this issue out of curiosity of why this one site wasn't working, and it's still somewhat usable while adblocked.

They're spying on this repo and they're on GitHub too, so they're checking the new filters added and undoing them everyday.

**Comment by Thedeur** [comment]
Lol. Reminds me of the days of 3dsthemeplaza, where the serial escalation eventually caused the owner to break his own site for regular users, then finally give up. I wonder how long it'll take for them on this one.

**Comment by llacb47** [comment]
Out of curiosity, does it work for you with the test login in https://github.com/NanoMeow/QuickReports/issues/25#issuecomment-516672774 @okiehsch @mapx- ?

**Comment by Thedeur** [comment]
I do believe it blocks the ad space elements after the page is loaded (which I realized I never tried), but not the initial blocking page. 

I think I'll try a script that auto-clicks the button for now.

**Comment by llacb47** [comment]
Working solution in Nano Adblocker:
```
aternos.org##+js(nanop-click-elements-onready, .btn.lUJybRrvyrOylolnlfmTTgffAChdGdqiz)
aternos.org##+js(nano-sib, clearInterval, 1000)
aternos.org##.ad-replacement
```

**Comment by Thedeur** [comment]
Nice. Though of course, that button element string seems to be randomized for different users. It works pretty well otherwise.

**Comment by llacb47** [comment]
Oh, now I might now why it doesn't work for you. Can you view source and copy and paste the content of the first <script> tag?

**Comment by llacb47** [comment]
https://github.com/uBlockOrigin/uAssets/pull/7230
