### ISSUE TITLE
Promoted Posts on Reddit (New Design) Showing Up

### ISSUE THREAD

**Issue by healsdata** [uBlockOrigin/uAssets#7210]
### URL(s) where the issue occurs

https://www.reddit.com/

### Describe the issue

Started seeing ads on the Reddit new design this week or so. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/787979/78956845-9a9cf880-7ab1-11ea-8e04-0e96f2d046c9.png)

### Versions

- Browser/version: Firefox 74.0.1 (64-bit)
- uBlock Origin version: uBlock Origin v1.26.0

### Settings

- Default filter lists, just a few custom filters. https://github.com/healsdata/filterlist/blob/master/list.txt

### Notes

![image](https://user-images.githubusercontent.com/787979/78956933-e18aee00-7ab1-11ea-8a3e-4994862888ca.png)

**Comment by okiehsch** [comment]
Fixed in `EasyList`.
