### ISSUE TITLE
Youtube Sidebar Vanishes

### ISSUE THREAD

**Issue by shirikoo** [uBlockOrigin/uAssets#7212]
### URL(s) where the issue occurs

`https://www.youtube.com/watch?v=J_3v7DEkjsk` or any video I open in youtube, really

### Describe the issue

The entire "up next/recommendations" sidebar in youtube vanishes when ublock is turned on. I disabled my filters and tried that, same thing. Seeing others report this on reddit as well. It re-appears when ublock is disabled on that page and the page is reloaded.

### Versions

- Browser/version: Version 81.0.4044.92 (Official Build) (64-bit)
- uBlock Origin version: 1.24.4

### Settings

I left everything at default, only disabled "my filters"

### Notes

Others are reporting on reddit, figured it'd be a good idea to report it here too. It may have something to do with the ads popped up on the sidebar now, above the "next in line" and recommendations

**Comment by okiehsch** [comment]
On my end the up next section is gone even if I disable uBO.

**Comment by uBlock-user** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/53295#issuecomment-611916602

happening with or without uBO, seems an intermittent site issue

**Comment by SephirothSG** [comment]
Confirmed, it does appear to be a site issue
https://twitter.com/TeamYouTube/status/1248541264355692545
