### ISSUE TITLE
streamdreams rule breaking hCaptcha

### ISSUE THREAD

**Issue by ronjones4** [uBlockOrigin/uAssets#7216]
### URL(s) where the issue occurs

`https://streamdreams.org/shows/`

### Describe the issue

* Streamdreams is hosted on CloudFlare
* CloudFlare recently switched to using hCaptcha instead of Google's reCaptcha
* When hCaptcha decides you need to solve something, instead of being able to solve it you get the error `Your browser plugins or privacy policies are blocking the hCaptcha service. Please disable them for hCaptcha.com`

### Screenshot(s)

<img width="1010" alt="Screen Shot 2020-04-10 at 10 35 21 PM" src="https://user-images.githubusercontent.com/63484421/79033373-50914100-7b9d-11ea-94e0-69917934b5c4.png">

### Versions

- Browser/version: Firefox 75
- uBlock Origin version: 1.26.0

### Notes

- The blocking is by virtue of this rule in `uBlock filters`:
```
! https://forums.lanik.us/viewtopic.php?f=62&t=41412
streamdreams.org##+js(aopw, encodeURIComponent)
```
Appreciate any help!

**Comment by okiehsch** [comment]
Update your `uBO-filters` list, the captcha should work after that.
The layout of the site is completely broken on my end. That is unrelated to uBO.
