### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7217]
### URL(s) where the issue occurs

`https://twitter.com/intent/follow?screen_name=mesitsu`

### Describe the issue

Annoyance: a popup

### Screenshot(s)

![twitter](https://user-images.githubusercontent.com/58900598/79043816-994c0700-7c3c-11ea-8296-ac412c145b30.png)

### Versions

- Browser/version: Firefox Android 68.7.0
- uBlock Origin version: 1.26.0

### Settings

- Default + uBlock Annoyances

### Notes

`twitter.com##span:has-text(Want to log):upward(7)`
`twitter.com##body:style(overflow-y: scroll !important)`
work if your UI language is English, but better to use more universal filter.

**Comment by llacb47** [comment]
`intent/follow` is a URL for following users. I don't think the modal on this page should be hidden. On regular profile pages, yeah.

**Comment by ghajini** [comment]
There is `No, thanks` button so what you called annoyance is ***dismissable*** why need filter then?

**Comment by krystian3w** [comment]
Locked scroll so not for Fanboy Annoyance @ghajini

**Comment by Yuki2718** [comment]
@llacb47 I'm not sure - if a user wanna follow, can't he still do this by logging in and taking an action? I don't use Twitter so use follow buttons only to see Tweets but not to follow if there's no other link to an owner's Twitter.

**Comment by mapx-** [comment]
I'd say such filters could easily break twitter "tomorrow" and we have `no, thanks` button as @ghajini said.

**Comment by Yuki2718** [comment]
> 
> 
> I'd say such filters could easily break twitter "tomorrow" and we have `no, thanks` button as @ghajini said.

I have no idea what the "tomorrow" is, but got it.

**Comment by krystian3w** [comment]
Problematic is language specific, no works with other than English.

IMO stable:

```html
<a href="/i/flow/signup" dir="auto" role="link" data-focusable="true" >
```

**Comment by DandelionSprout** [comment]
Yuki forgot to mention that it could only be triggered with a mobile useragent; as a desktop useragent instead showed a *completely* different fullpage overlay for me at that example page.

Under which circumstances would `https://twitter.com/intent/follow?screen_name=mesitsu` be accessed through casual web browsing? Is it e.g. used in biography/company SoMe links? Or can it *only* be accessed through whichever type of Follow button on Twitter?

**Comment by Yuki2718** [comment]
> 
> 
> Yuki forgot to mention that it could only be triggered with a mobile useragent; as a desktop useragent instead showed a _completely_ different standalone fullpage for me at that example page.
> 
> Under which circumstances would `https://twitter.com/intent/follow?screen_name=mesitsu` be accessed through casual web browsing? Is it e.g. used in biography/company SoMe links? Or can it _only_ be accessed through whichever type of Follow button on `Twitter`?

You're right, it's mobile UA only. It was accessed from a follow button bottom of this page:
`https://www.hotpepper.jp/mesitsu/entry/yuuyuu/2020-00055`
![hotpepper](https://user-images.githubusercontent.com/58900598/79129338-021fb480-7de0-11ea-966d-a884cca03331.png)
