### ISSUE TITLE
Facebook ads getting through

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#722]
### URL(s) where the issue occurs

`facebook.com`

### Describe the issue

uBO previously always blocked FB ads. Seeing them again for the first time today.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/30947694-2bd36652-a3d9-11e7-9288-e262fc83b6a0.png)

### Versions

- Browser/version: Chrome/60
- uBlock Origin version: 1.14.8

### Settings

Default

### Notes

Could be connected with ABP's recent change? https://adblockplus.org/blog/consumers-again-declare-independence-from-relentless-facebook-ads

**Comment by gorhill** [comment]
I added support in 1.14.11rc7 for `:-abp-has` and `:-abp-contains` now used by EasyList. Can you see if these ads are taken care of by that version of uBO + an up to date EasyList?

**Comment by terrorist96** [comment]
I prefer to stay on the stable build so I'll wait til you push out the next update. :)

**Comment by okiehsch** [comment]
He meant for you to install 114.11rc7, so you can test if the issue is fixed after that you can remove 
114.11rc7 and use the stable build.
I can't test, because I do not have a Facebook account.

**Comment by terrorist96** [comment]
Ok, I installed the test version and can confirm Facebook ads are blocked. Thanks!

**Comment by SMed79** [comment]
> I prefer to stay on the stable build

You can use a [portable version](https://portableapps.com/apps/internet) of a web browser or create [2nd profile](https://www.howtogeek.com/139705/how-to-use-multiple-browser-profiles-in-any-browser/) for testing.

**Comment by gorhill** [comment]
Will remove the added filters once 1.14.12 is out and widespread.

**Comment by gotitbro** [comment]
@SMed79 In the comments of the ABP blogpost Ben mentions this 

> EasyList(s). As for update regularity, it’s now at 48 hours

Wasn't it always 48 hours?

**Comment by SMed79** [comment]
The [update interval](https://adblockplus.org/filters#special-comments) up to the list maintainer.
I remember it was 4 days before but they have changed to 2 days probably because of those sites that use a revolving adservers.

e.g
- https://github.com/easylist/easylist/commit/298aaafdc6139117ad5200cbd79ac4caa9e7c304
- https://github.com/easylist/easylist/commit/b0b9580409e666d934de069a99fb590d48076dd0
