### ISSUE TITLE
Broken Embedded YouTube Videos on Eurogamer

### ISSUE THREAD

**Issue by SideSwipe9th** [uBlockOrigin/uAssets#7220]
### URL(s) where the issue occurs

`https://www.eurogamer.net/articles/2020-04-08-the-double-a-team-a-breezy-summer-fling-with-civilization-revolution`
`https://www.eurogamer.it/articles/2020-04-11-news-videogiochi-sekiro-giocato-in-multiplayer-co-op-risultati-interessanti`
`https://www.eurogamer.de/articles/2020-04-09-spielt-the-crew-2-am-wochenende-kostenlos-auf-ps4-und-pc`

Or any other Eurogamer article with embedded YouTube videos. 

### Describe the issue

Embedded YouTube videos in Eurogamer articles do not load when uBlock Filters list is enabled. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/47156505/79056898-184c3a00-7c53-11ea-96f2-8c2e947e172f.png)

### Versions

- Browser/version: Firefox 75.0 / Chrome 81.0.4044.92
- uBlock Origin version: 1.26.0 / 1.24.4

### Settings

No changes made from uBO's default settings. 

### Notes

The issue appears to be the following filter on line 840 of uBlock filters: `20min.ch,al.com,alphr.com,autoexpress.co.uk,autofrage.net,bento.de,bikeradar.com,blick.ch,chefkoch.de,computerfrage.net,cyclingnews.com,digitalspy.com,democratandchronicle.com,denofgeek.com,esgentside.com,eurogamer.de,eurogamer.es,eurogamer.it,eurogamer.net,eurogamer.pt,evo.co.uk,exclusivomen.com,finanzfrage.net,ft.com,gala.de,gala.fr,gesundheitsfrage.net,gutefrage.net,heatworld.com,itpro.co.uk,livingathome.de,masslive.com,maxisciences.com,metabomb.net,mlive.com,motherandbaby.co.uk,motorcyclenews.com,motorradfrage.net,muthead.com,neonmag.fr,newyorkupstate.com,ngin-mobility.com,nj.com,nola.com,ohmirevista.com,ohmymag.*,oregonlive.com,pcgamer.com,pennlive.com,programme.tv,programme-tv.net,radiotimes.com,silive.com,simplyvoyage.com,sportlerfrage.net,stern.de,syracuse.com,theweek.co.uk,ydr.com##+js(aopr, _sp_._networkListenerData)` 

I have tested this by disabling the uBlock Filters list, and copying the six Eurogamer filters to My Filters. If I disable the above filter, as in the image below, the embedded YouTube videos in the article display as expected. If this filter is enabled however the embedded videos do not appear. This filter breaks embeds across the Eurogamer family of websites. It does not however appear to break embedded YouTube videos on PCGamer or Radio Times. 

![image](https://user-images.githubusercontent.com/47156505/79057243-0b314a00-7c57-11ea-9adf-c5c4525db601.png)

~~Adding the following exception filter allows embedded YouTube videos to work with uBlock Filters list enabled: `@@||eurogamer.net##+js(aopr, _sp_._networkListenerData)`~~

Apologies, adding this exception filter does not work as it appears to be getting overridden by the uBlock Filters list. The remainder of the troubleshooting in the troubleshooting of the notes is still valid on my browsers however.

**Comment by okiehsch** [comment]
Thanks for investigating.

`@||eurogamer.net##+js(aopr, _sp_._networkListenerData)`
is the wrong syntax, `@@` is an exception used for [static filters](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#static-network-filtering)
For [script-injections](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#scriptlet-injection) `#@#` is used, so in your example the correct filter is
`eurogamer.net#@#+js(aopr, _sp_._networkListenerData)`.

**Comment by PIZZA90** [comment]
URL:
`https://www.eurogamer.net/articles/digitalfoundry-2021-the-matrix-awakens-compared-against-the-original-movie-and-its-shockingly-close`

Video no load:

![Captura1](https://user-images.githubusercontent.com/33556647/148018650-9627299d-07ad-48c2-bdc2-0f49c54eb105.PNG)

Blocking this: `||bbvms.com^` works:

![Captura2](https://user-images.githubusercontent.com/33556647/148018738-2ba5ab3d-aa5a-46be-b587-669d3d15f440.PNG)

**Comment by mapx-** [comment]
`@@||s0.2mdn.net/instream/html5/ima3.js$script,domain=eurogamer.net`

**Comment by mapx-** [comment]
@ryanbr

**Comment by PIZZA90** [comment]
Not possible found the whitelisted filter in the logs? or the logs not showing all 🤔

**Comment by mapx-** [comment]
Do you see the exception in unbreak list ?

**Comment by PIZZA90** [comment]
yes ofc, i mean in **uBO requests log**

**Comment by PIZZA90** [comment]
example:

![Captura3](https://user-images.githubusercontent.com/33556647/148027770-57d887c7-02e4-440d-b37a-2ae338b93b41.PNG)

should be appears whitelisted in green?

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/148028217-6666d68e-b666-4d91-89c5-3d29c5f36d60.png)

**Comment by PIZZA90** [comment]
I just reinstalled uBO, with full default updated filters and nothing whitelisted:

![Captura33](https://user-images.githubusercontent.com/33556647/148028724-80cc8f1a-6a5f-4212-80d8-5958e75b5a8a.PNG)

**Comment by PIZZA90** [comment]
Tested in **firefox**: showing the whitelisted filters
but no in Chrome for me

**Comment by mapx-** [comment]
Did you keep your bbvms filter ?

otherwise this should work for you:

`||gamernetwork.bbvms.com/json/$xhr,domain=eurogamer.net`

**Comment by PIZZA90** [comment]
it was a cookie problem..
after deleting the cookies of the last 24 hours works.. 
but I did not have that filter added, I had reinstalled uBO

it's like having the filter added : `||bbvms.com^`  the same symptoms ... it's as if the filter was saved in the cookies 🤣🤣

solved! thx :)
