### ISSUE TITLE
rexdlfile.com

### ISSUE THREAD

**Issue by swathigrate** [uBlockOrigin/uAssets#7221]
`https://rexdlfile.com/index.php?id=candy-crush-saga-apk-mega-mod-unlimited-all-patcher`

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

 opening new page ads and some pop up ads

### Screenshot(s)

**.]
![Screenshot_2020-04-12-09-03-46-946_org mozilla firefox](https://user-images.githubusercontent.com/14991260/79059904-0d070780-7c6f-11ea-9bb8-7a344d89f339.jpg)

### Versions

- Browser/version: firefox 68.3
- uBlock Origin version: 1.26

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by llacb47** [comment]
Can't reproduce.

**Comment by okiehsch** [comment]
To reproduce the scrrenshot of the OP you have to scroll down and click "Go to download page"
