### ISSUE TITLE
No filtering for mittellaendische.ch

### ISSUE THREAD

**Issue by SEXXES** [uBlockOrigin/uAssets#7222]
### 

`https://www.mittellaendische.ch`

### Screenshot(s)

![ZEITUNG](https://user-images.githubusercontent.com/42209961/79069163-56397480-7ccc-11ea-8091-89963a50d261.png)

### Versions

- Browser/version: [Chrome Version 81.0.4044.92]
- uBlock Origin version: [1.24.4]

### Settings

- [N/A]

**Comment by mapx-** [comment]
try `mittellaendische.ch##aside`
@ryanbr
