### ISSUE TITLE
intergate.info

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7226]
### URL(s) where the issue occurs

`https://intergate.info/conan-fistofbluesapphire`

### Describe the issue

Annoyance: right-click disabled

### Versions

- Browser/version: Brave 1.5.123
- uBlock Origin version: 1.24.4

### Settings

- Default + uBlock Annoyances

### Notes

`intergate.info##+js(aopw, document.oncontextmenu)`
works but has some side effect such as blocking requests to Facebook since it is in the middle of a script:
`https://intergate.info/wp/wp-content/cache/autoptimize/js/autoptimize_ec2164bf1153e0e8a88c320ee31444d9.js.pagespeed.jm.zW8GvTLIAr.js`

**Comment by mapx-** [comment]
> has some side effect such as blocking requests to Facebook

meaning ?

**Comment by mapx-** [comment]
does this help ?
`intergate.info##+js(set, document.oncontextmenu, null)`

**Comment by Yuki2718** [comment]
> 
> 
> > has some side effect such as blocking requests to Facebook
> 
> meaning ?

With my rule, requests to `https://www.facebook.com/v2.3/plugins/page.php?` didn't happen which may be problem for those who use FB. Yes, your rule works!
