### ISSUE TITLE
how to only disable video ads on youtube

### ISSUE THREAD

**Issue by homamgamer** [uBlockOrigin/uAssets#7227]
### URL(s) where the issue occurs

`[https://www.youtube.com]`

### Describe the issue

[It's not an issue but since you don't have a forum I had to ask here, what i wanna do is block just the video ads that are unskippable if you don't wait for 5 or so seconds, ads on the page are fine because they don't bother me ]

### Screenshot(s)

[no need i guess]

### Versions

- Browser/version: [Firefox 75.0]
- uBlock Origin version: [v1.26.0]

### Settings

- [nothing]

### Notes

[didn't find anything that answers my questions, just found filters or people telling me to install a script plugin like tampermonkey or whatever]

**Comment by uBlock-user** [comment]
> It's not an issue but since you don't have a forum

User Support is at https://old.reddit.com/r/uBlockOrigin/
