### ISSUE TITLE
speisekarte.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#7228]
### URL(s) where the issue occurs

`https://www.speisekarte.de/`

### Describe the issue

Anti Adblock

and please take a look at this domain `https://spkrth.scw.systems` because it looks like fingerprint tracking

<img width="584" alt="pic745" src="https://user-images.githubusercontent.com/48647394/79149741-e5778280-7dc7-11ea-845a-75a35e5673a5.PNG">

### Versions

- Browser/version: Firefox 75
- uBlock Origin version: v1.26.0

**Comment by mapx-** [comment]
try and see if it breaks something
`speisekarte.de##+js(aopr, onload)`

otherwise we could use
`speisekarte.de##.test-adblock-overlay`

**Comment by uBlock-user** [comment]
anti-adb script is third-party,  so `||steadyhq.com^$3p,domain=speisekarte.de` works.

**Comment by JobcenterTycoon** [comment]
no breakage for me

**Comment by lain566** [comment]
How about
`speisekarte.de##+js(set, SteadyWidgetSettings.adblockActive, false)`

**Comment by JobcenterTycoon** [comment]
A tracking and ad looking script coming from `https://speisekarte.h5v.eu/42/moli_18791df205fac5b958b6.min.mjs`

<img width="510" alt="Unbenannt1" src="https://user-images.githubusercontent.com/48647394/132105936-675f29c4-60b4-4a1a-976a-b4e2ef9ded95.PNG">
