### ISSUE TITLE
[NSFW] Unblockable Redirecting Link Appearance

### ISSUE THREAD

**Issue by elsy04** [uBlockOrigin/uAssets#723]
**### URL(s) where the issue occurs**

`http://www.xmoviesforyou.com/*`

**### Describe the issue**

This site is plagued by a bunch of different kind of ads, which I already managed to mitigate, but there is this little piece of sh*t which still can't be blocked. Despite I tried to know its exact origin how to block it, I don't know what is triggering it. I already tried with several different filter lists, rules and configurations but to no avail.

The automatic redirection will take place every now and then, while browsing the site, but an straightforward way of "activating" the redirecting link without actually let it do its thing, will be this one:

Right after opening the main website for the first time, if you make a left or even right click on the scrolling bar or the lowest part of the page, that will activate a kind of "invisible mouse trap" which will cover half the page size approximately. You will note it since the original links from the upper half part, will really point to "c75b9ac5103e5d125b8(dot)com/1264725.html" in the status bar, instead the intended ones. The links from the lower half part will not be altered, but (if clicked) the redirecting link will be active in the next new page right away.

**### Screenshot(s)**

[Will post them if needed]

**### Versions**

- Browser/version: [Firefox ESR v52.3.0 x86]
- uBlock Origin version: [1.14.10]

**### Settings**

No changes but updating the default filters' list.

**### Notes**

The only way of blocking it I have found so far, is by using the "element picker" to block the invisible trap, but that's more a workaround than a real fix; besides, it will break the text selection/copy from the pages.

**Comment by mapx-** [comment]
see if works
```
xmoviesforyou.com##script:inject(abort-current-inline-script.js, __htapop)
/cdn-cgi/apps/head/*$script,domain=xmoviesforyou.com
.com/*.css$stylesheet,domain=xmoviesforyou.com,third-party
xmoviesforyou.com##script:inject(abort-on-property-read.js, V8R9O)
```

**Comment by SMed79** [comment]
@kasper93 

for popads add
`/^https?:\/\/www\.[a-z]{8,14}\.bid\/[a-z]{1,6}\.js$/$script,third-party`

for propellerads
https://github.com/easylist/easylist/commit/ea5591665da679164f9b6aba194c0f184fe4d24d#commitcomment-23743140

**Comment by kasper93** [comment]
Indeed those works. Also need to mark following filter as bad, because it breaks the page. `https://ajax.cloudflare.com/cdn-cgi/scripts/c2b63e8a/cloudflare-static/rocket.min.js` shouldn't be blocked.

```
|https://$third-party,script,domain=29443kmq.video|xmoviesforyou.com,badfilter
```

**Comment by SMed79** [comment]
Suggestion
```
/out?zoneId=
/out?zoneId=$popup
.com/p?zoneId=*-$script,third-party
/cdn-cgi/pe/bag2?r*cpaofferstat.com
```

**Comment by gorhill** [comment]
> if you make a left or even right click on the scrolling bar or the lowest part of the page, that will activate a kind of "invisible mouse trap" which will cover half the page size approximately

How about:

    xmoviesforyou.com##script:inject(addEventListener-defuser.js, /^mouse/)

**Comment by okiehsch** [comment]
`xmoviesforyou.com##script:inject(abort-current-inline-script.js, parseInt, tabunder)`
kills the inline-script that pulls the `/1264725.css` and triggers the popup.
I can not see any other popups on my end.

Why would you allow  `/cloudflare-static/rocket.min.js`?
I can watch the videos, which is clearly the main/only reason anybody uses such a site, so what essential
site functionality is broken.

**Comment by kasper93** [comment]
> Why would you allow /cloudflare-static/rocket.min.js?

It prevents legitimate scripts to load. This page is just indexer for videos hosted on other sites, so there is literally none functionality to break. But there is one visual issue that you can notice. Item grid looks bad without JS. When you let scripts to load, grid is nicely fixed. I don't know if this is something regular user of this page care about. IMHO the whole page should be considered malicious with the amount of ads and coin-hive embedded.

**Comment by okiehsch** [comment]
>  the whole page should be considered malicious with the amount of ads and coin-hive embedded.

I agree with that but people will use such sites anyway and so I would not allow a script that leads to even more exposure to ads malicious or not, if it only leads to some layout breakage.

**Comment by okiehsch** [comment]
OK, I think
````
xmoviesforyou.com##script:inject(abort-current-inline-script.js, parseInt, tabunder)
streamcherry.com##script:inject(abort-on-property-write.js, _0xd959)
streamcherry.com##script:inject(abort-on-property-write.js, N5ii.M4)
streamcherry.com##script:inject(abort-on-property-write.js, JiLk)
````
also takes care of all popups occuring if you click to play a video, atleast on my end.
NSFW example link: `http://www.xmoviesforyou.com/2017/09/blacked-gina-valentina-give-it-to-me-now.html``

**Comment by gotitbro** [comment]
@okiehsch So the script which is needed for layout hasn't been blocked right?

> I agree with that but people will use such sites anyway

You are right about that with the kind of ads this site injects (most of which make it unusable) it is indeed quite [popular](https://www.alexa.com/siteinfo/xmoviesforyou.com). 

> so I would not allow a script that leads to even more exposure to ads, malicious or not, if it only leads to some layout breakage.

I do not agree with this as only the most viable solution should be chosen. If an adblocker is blocking additional things then its not doing what it was supposed to.

**Comment by gorhill** [comment]
> I do not agree

Then go ask EasyList maintainers for a fix. We will no add an exception filter here just for the sake of addressing a minor visual glitch caused by a filter in another list:

![a](https://user-images.githubusercontent.com/585534/30990706-452a6910-a470-11e7-9ea9-26329f973a88.png)

Locking this thread because no point adding more to it.

**Comment by okiehsch** [comment]
Well, EasyList has added `@@||ajax.cloudflare.com/cdn-cgi/scripts/$script,third-party`, so now 
`rocket.min.js` loads, which means the layout is now immaculate but we now have popunders and `coin-hive` request spamming.

**Comment by kasper93** [comment]
I've seen the problem with rocket loader on few sites already, it basically bypass the filters. I locally have 
```
/cdn-cgi/pe/bag2^$xmlhttprequest,first-party
```
to force fallback to normal script load which will go through blocking unlike `bag2` requests. I proposed to do that in Easylist, but no response yet. https://github.com/easylist/easylist/issues/649

**Comment by SMed79** [comment]
> I proposed to do that in Easylist, ...

@kasper93 Your filter will break a lot of sites so it is sure no one will add it.

**Comment by kasper93** [comment]
And how it will break it?

**Comment by SMed79** [comment]
> And how it will break them?

e.g https://forums.lanik.us/viewtopic.php?p=102108#p102108
