### ISSUE TITLE
brick-hill.trade anti-adblock

### ISSUE THREAD

**Issue by dragonianx** [uBlockOrigin/uAssets#7231]
### URL(s) where the issue occurs
`hhttps://brick-hill.trade/items`

### Describe the issue

Site injects this piece of JavaScript at the bottom of the page:
```js
<script type="0ccfc8cbe391f7cccffe81aa-text/javascript">
	if (!document.getElementById('qSoXcbJQsvPl')) {
		if (!document.getElementById('qSoXcbJQsvPl')) {
			document.body.innerHTML = `<pre>Advert-blocking software detected.
Your request was blocked.
Brick Hill Trade is free for you to use but depends on advertising revenue to pay for the server.
Advertisements on Brick Hill Trade are non-intrusive and will not disrupt your experience.

Until you disable the software, you will not be permitted to use Brick Hill Trade, thank you.</pre>`
		}
	}
</script>
```

This overwrites the innerHTML of the page making the site unusable until you disable adblock.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/59402367/79174999-72234000-7dca-11ea-8e14-b17f16459e0f.png)

**Comment by ivolong** [comment]
jake piss off and let me block ads in peace
