### ISSUE TITLE
footballnews.jp

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7235]
### URL(s) where the issue occurs

`https://www.footballnews.jp/`

### Describe the issue

Anti-adblock,

### Screenshot(s)

![footballnews](https://user-images.githubusercontent.com/58900598/79203990-d0a5f800-7e76-11ea-8d17-dfc00b1f2309.png)

### Versions

- Browser/version: Brave 1.5.123
- uBlock Origin version: 1.24.4

### Settings

- Default

### Notes

`footballnews.jp##+js(acis, document.addEventListener, google_ad_client)`

**Comment by mapx-** [comment]
"classic" alternative => `footballnews.jp##+js(nostif, getComputedStyle, 250)`

**Comment by uBlock-user** [comment]
Doesn't work, because of race condition, the script is positioned to be the very first to execute.

**Comment by mapx-** [comment]
right, is working only in chrome on my end but not for firefox

**Comment by okiehsch** [comment]
For Firefox we could use HTML filters.

**Comment by uBlock-user** [comment]
I only added the suggested filter as it works for him on Brave and for me on Firefox, otherwise I would have gone with `ghide` and `redirect-rule` as I suggested above.

**Comment by okiehsch** [comment]
`footballnews.jp##^script:has-text(antiblock.org)`

**Comment by uBlock-user** [comment]
Is it needed ?

**Comment by okiehsch** [comment]
I can reproduce with Firefox.

**Comment by Yuki2718** [comment]
On my end the rule works on Firefox too. But I have a similar case which the rule didn't work and I had to use HTML filter, I'll create an issue.
