### ISSUE TITLE
Countdown "anti-adblocker"

### ISSUE THREAD

**Issue by smege1001** [uBlockOrigin/uAssets#7245]
### URL(s) where the issue occurs

`https://vidlii.com/channels`

### Describe the issue

Everytime you try to visit a page in vidlii.com, you have to wait 56-22 seconds and then it refreshes.

The problem is that the countdown value is located in the countdown HTML element (`#abp_countdown`)
There are no scriptlets for changing the contents of HTML elements

And boosting the interval will make it refresh like crazy

### Screenshot(s)

![vidlii](https://user-images.githubusercontent.com/59537482/79340200-e02e4b00-7f21-11ea-9f47-cdbc6c300c7d.png)

### Versions

- Browser/version: Firefox 74.0
- uBlock Origin version: 1.26.0

### Settings

- Advanced user enabled

### Notes

Countdown also shows up for users who aren't using any adblocker

**Comment by uBlock-user** [comment]
> And boosting the interval will make it refresh like crazy

then it's server sided and cannot be fixed.

**Comment by uBlock-user** [comment]
You can try `/cdn-cgi/apps/body/*$script,1p` and `/cdn-cgi/apps/head/*$script,1p` if that helps.

**Comment by smege1001** [comment]
> 
> 
> > And boosting the interval will make it refresh like crazy
> 
> then it's server sided and cannot be fixed.

Oh.

**Comment by uBlock-user** [comment]
You can see for yourself with `vidlii.com##^script:has-text(abp_countdown)` it will disable the script, but the broken halted countdown msg will still be there.

**Comment by smege1001** [comment]
I guess this is only possible with a userscript
