### ISSUE TITLE
skymovieshd.link

### ISSUE THREAD

**Issue by swathigrate** [uBlockOrigin/uAssets#7246]
### URL(s) where the issue occurs
https://skymovieshd.link/
### Describe the issue

1. opening new page ads when the click the any link inpage 
2. Frequently they are changing their domain also like .link, .cafe, etc

https://skymovieshd.link/

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: firefox 68.3
- uBlock Origin version: 1.26

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by swathigrate** [comment]
Hello sir ,
Showing this type ad
Please slove it
Tq

![Screenshot_2020-04-23-20-39-32-623_org mozilla firefox](https://user-images.githubusercontent.com/14991260/80115694-958d7e00-8574-11ea-8a77-197d09818c58.jpg)

**Comment by ghajini** [comment]
`skymovieshd.*##+js(aopr, __CF$cv$params)`
`||eveteaemo.com^`

**Comment by ghajini** [comment]
Popup ads

Platform - firefox A.

URL=skymovieshd.link

Filter=
`||sf9yvla26s5t.com^`

**Comment by swathigrate** [comment]
Showing this type of ads in  Firefox android


![Screenshot_2020-05-01-22-17-58-878_org mozilla firefox](https://user-images.githubusercontent.com/14991260/80823152-9d2fd100-8bcb-11ea-8594-4c5a99ae4275.jpg)

**Comment by mapx-** [comment]
Where ? home page ? specific link ?

**Comment by ghajini** [comment]
@swathigrate is talkingvabout those fake **download/[download now]**
Fix is simple ,uncheck/untick **ignore generic cosmetic filters** in ublock origin settings

![IMG_20200501_225648](https://user-images.githubusercontent.com/20338483/80827107-fb2adb80-8c00-11ea-8200-2ba2addb3720.jpg)

**Comment by swathigrate** [comment]
> Where ? home page ? specific link ?

Yes .. main page and other pages


skymovieshd.link##center:nth-of-type(1) > a[href^="http://azmobilestore.co/cs.php"]:nth-of-type(1) > div

Not working this code also

**Comment by swathigrate** [comment]
> Test link= `https://skymovieshd.link/movie/Baaghi-3-(2020)-Hindi-720p-HEVC-HDRip-x265-AAC-ESubs-Full-Bollywood-Movie-[750MB].html`
> 
> @swathigrate is talking about those fake **download/ [ download file ]**
> 
> Fix is simple ,uncheck/untick **ignore generic cosmetic filters** in ublock origin settings
> 
> ![IMG_20200501_225648](https://user-images.githubusercontent.com/20338483/80827107-fb2adb80-8c00-11ea-8200-2ba2addb3720.jpg)

Not working this trick....

**Comment by mapx-** [comment]
@swathigrate @ghajini is right .. untick that settings, confirm and refresh the page

**Comment by swathigrate** [comment]
Changed thair domin ... Again new page ads are opening with click any links 

https://skymovieshd.life/
Plz fix it

**Comment by mapx-** [comment]
I cannot reproduce the issue.

Please don't post anymore clickable links, use `Insert code` - see bellow:
![image](https://user-images.githubusercontent.com/10303732/83968344-d5ac8400-a8c8-11ea-96d3-633e43c745f2.png)

**Comment by swathigrate** [comment]
Hello sir ,

Opening new page ads ..

https://skymovieshd.life/category/Hot-Short-Film.html.  When i click  on any link automatically opening some new page ads ... One time opening ... One time not opening ads 

```http://newgoland.com/?groupds=11&clientId=164&productId=1424&tracking=d6k76564t4cQqiA8AatBnrtQdjNk&publisher_id=1928_38242`

Plz fix it
