### ISSUE TITLE
www.airfrance.co.jp

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7247]
### URL(s) where the issue occurs

`https://www.airfrance.co.jp/`

### Describe the issue

Annoyance: a cookie popup (or leftover of it if Fanboy Annoyance is enabled) with scroll locked

### Screenshot(s)

With Fanboy Annoyances
![airfrance1](https://user-images.githubusercontent.com/58900598/79447665-27e4cd80-801b-11ea-9723-f7912d109171.png)
![airfrance1-2](https://user-images.githubusercontent.com/58900598/79447923-8f028200-801b-11ea-8e91-56620a08bd75.png)

Without
![airfrance2](https://user-images.githubusercontent.com/58900598/79447704-36cb8000-801b-11ea-8f06-0d304444a317.png)

### Versions

- Browser/version: 1.7.92
- uBlock Origin version: 1.24.4

### Settings

- Default + uBlock Annoyances (+ Fanboy Annoyances)

### Notes
`airfrance.co.jp##body:style(overflow: scroll !important)`
doesn't work.
`airfrance.co.jp##+js(ra, style, body)`
works (with `airfrance.co.jp###gdpr_popin`) but maybe
`airfrance.co.jp##+js(aopw, gdpr_popin_path)`
is better?

**Comment by Yuki2718** [comment]
@ryanbr

**Comment by uBlock-user** [comment]
@ryanbr CNAME breakage due to `||cedexis.net^$3p` in EasyPrivacy.

**Comment by mapx-** [comment]
> @ryanbr CNAME site breakage due to `||cedexis.net^$3p` in EasyPrivacy.

I get no breakage, what exactly is blocked ? or .. better .. fix it directly

**Comment by okiehsch** [comment]
I don't see any cedexis requests on my end.

**Comment by ryanbr** [comment]
Cname checks should state from which geo region, so we can vpn to confirm

**Comment by uBlock-user** [comment]
It was via a VPN from Australia, can't reproduce it either. Now I'm served via AkamaiEdge.
