### ISSUE TITLE
Remove GTM / Google Tag Manager as a tracker

### ISSUE THREAD

**Issue by cosminstefanxp** [uBlockOrigin/uAssets#7250]
### URL(s) where the issue occurs
`https://www.googletagmanager.com/gtm.js?`

### Describe the issue
I would like to propose the removal of Google Tag Manager as a privacy tracker. My feeling is that **it hurts the environment a lot, both for developers and for users, without bringing in any real gains**, since the loaded tags would get blocked anyway, if they are trackers.

It's not tracking anything by itself. It's a tool for managing different JS based tools. If the tracking tools themselves are blocked (e.g. Google Analytics or Facebook Pixel), there's no reason to block Google Tag Manager.

For example, via GTM, some websites might provide support features, based on user actions. This is not tracking in any way and the user ends up being hurt by this.

Another example is: mozilla-services/shavar-prod-lists#46, where GCP stackdriver console is broken due to this.

Further examples of situations where GTM would be beneficial:

- adding support tools for users, depending on the place they are in the app (e.g. the "it seems you're stuck on this. Do you need help?";
- monitoring of performance of remote dependencies;
- consoles (such as GCP's);

Furthermore, Google has made it clear that they are not persisting or using any tracking data in their policy.

### Versions

- Browser/version: Firefox
- uBlock Origin version: 1.24.4

**Comment by mapx-** [comment]
@gorhill

**Comment by gorhill** [comment]
Having a page page causes a connection to `googletagmanager.com` is the problem in the first place.

The ideal case is zero 3rd parties -- this is the ideal which motivates uBO's default configuration. Also, it does not matter whether a 3rd party makes promise of not using the data, from a user's point of view this is unverifiable, and uBO serves user interests first.

Declined.

**Comment by cosminstefanxp** [comment]
On a serious note I still believe my point to be valid. Tag Manager itself **is a tool**. Considering that whatever is inside would be blocked anyway if harmful, blocking it does not serve users' interests first, as it blocks **all content**, without evaluating its benefit and/or utility for the user. Furthermore, users will not know they are missing on useful content.

That being said, the fact that the experience of **millions of people** worldwide is possibly affected negatively (without even knowing) by a **single person'**s quickly made decision on a github issue is in itself a serious issue in my view, but let's keep the ethics and politcs out of it.

PS: I'm an uBlock user and have been for years. But only recently I've hit this issue as a developer  and I've realised how serious it is and that many times I had problems with websites due to this single issue.

// I really can't believe you've just said "The ideal case is zero 3rd parties". I would challenge you to build an entire, serious website, without any 3rd party software or libraries.

**Comment by gorhill** [comment]
> millions of people worldwide is possibly affected negatively (without even knowing) by a **single person'**s quickly made decision on a github issue

`googletagmanager.com` has been blocked by EasyPrivacy for years. uBO just added ability to redirect the blocked request to a local neutered version which lowers likelyhood of breakage.

**Comment by kulfoon** [comment]
Yes, perhaps cosminstefanxp wanted to create an issue about GTM in [EasyPrivacy's issue tracker](https://github.com/easylist/easylist/issues) , as this is the main list that blocks GTM in the first place, for years already, and "uBlock filters – Privacy" only adds a redirection, to the EasyPrivacy's GTM filter, to make it less destructive, hence it's not uBO who should be blamed for blocking BTW in the first place.
