### ISSUE TITLE
deezer.com

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#7255]
### URL(s) where the issue occurs

`https://www.deezer.com/us/login?redirect_type=page&redirect_link=%2Fus%2Ftrack%2F755061132`

### Describe the issue

I can't login with my Google account. It is caused by Fanboy's annoyance that blocks `apis.google.com`. see screenshot below

### Screenshot(s)

![image](https://user-images.githubusercontent.com/61142621/79556077-daab3f00-80a0-11ea-8dc8-afa3ed7bc559.png)

### Versions

- Browser/version: Opera 67.0.3575.137
- uBlock Origin version: 1.26.0

### Settings

- AdGuard Annoyances
- Fanboy’s Annoyance

**Comment by okiehsch** [comment]
@ryanbr
