### ISSUE TITLE
oncehelp.com

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#7257]
### URL(s) where the issue occurs

`https://oncehelp.com/wmw1vE7`

### Describe the issue

Countdown and fake download buttons

### Screenshot(s)

![image](https://user-images.githubusercontent.com/61142621/79566397-c53f1080-80b2-11ea-957e-719edcc5b8fe.png)

![image](https://user-images.githubusercontent.com/61142621/79566422-d0923c00-80b2-11ea-87ac-db5e6406c5f5.png)

### Versions

- Browser/version: Opera 67.0.3575.137
- uBlock Origin version: 1.26.0

### Settings

- AdGuard Annoyances
- Fanboy’s Annoyance

**Comment by mapx-** [comment]
Countdown => server side
