### ISSUE TITLE
Pleated Jeans

### ISSUE THREAD

**Issue by Viscouse** [uBlockOrigin/uAssets#7258]
### URL(s) where the issue occurs

`https://pleated-jeans.com/`

### Describe the issue

Anti-adblocker Admiral prevents ad blocking

### Versions

- Browser/version: Chrome
- uBlock Origin version: v1.24.4

### Settings

-Peter Lowe’s Ad and tracking server list
-Fanboy’s Enhanced Tracking List​​
-EasyList​​
-AdGuard Base​​​​​​​​​
-AdGuard Mobile Ads​​​​

### Notes
Ads displayed incite large machine usage issues.

**Comment by mapx-** [comment]
@pgl

**Comment by pgl** [comment]
Added, thanks.

**Comment by mapx-** [comment]
@pgl  I guess you added the wrong one and not
`massivemark.com`

**Comment by pgl** [comment]
@mapx- Oof, thanks for catching that! Replaced the entry with `massivemark.com`.
