### ISSUE TITLE
Anti-adblock on onemanhua.com

### ISSUE THREAD

**Issue by erosman** [uBlockOrigin/uAssets#7261]
uBlock Origin 1.26.0
uMatrix 1.4.0

### URL(s) where the issue occurs

`https://www.onemanhua.com/`

### Describe the issue

1- Even with uBlock Origin disabled on the site, the  anti-adblock blocks the pages.

> 浏览器屏蔽了重要元件无法加载页面，请确保没有开启任何小插件，影响页面加载！ 实在不行请更换浏览器！ 推荐 UC/搜狗浏览器。 有网友反馈nod32 之类的杀软也会屏蔽一些东西

N.B. Disabling uMatrix loads adult-ads

2- Although not as important as the first one, site also pop up an add tab, that gets blocked by uMatrix but the pop-up happens nonetheless. The pop-up occurs randomly on clicking links (not on every link).

### Screenshot(s)
1- 
![image](https://user-images.githubusercontent.com/6458876/79630901-6fc63a80-816a-11ea-8657-d60a41f22f56.png)

2- 
![image](https://user-images.githubusercontent.com/6458876/79630973-00047f80-816b-11ea-8467-7a52491baa7a.png)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: 77.0a1 (2020-04-17) (64-bit)
- uBlock Origin version: 1.26.0

### Settings

- default

### Notes
none.

**Comment by uBlock-user** [comment]
Why are you disabling uBO on that site ?

**Comment by Yuki2718** [comment]
Not reproduced as well on Brave and Firefox, accessed from Japan.

**Comment by mapx-** [comment]
Reset uBO to default settings, purge all caches + update, disable uMatrix for that site and test again.

**Comment by erosman** [comment]
> Why are you disabling uBO on that site ?

It wasn't working before with uBO enabled on the site and was disabled for testing.

> Reset uBO to default settings

As mentioned it is default settings

> disable uMatrix for that site and test again.

I will test more with uBO enabled and uMatix allowed.

**Comment by erosman** [comment]
It seems to be fine now. Thank you.

Closing .....

**Comment by xukongop** [comment]
The same issue in
https://www.ohmanhua.com

**Comment by mapx-** [comment]
fixed yersterday

**Comment by uBlock-user** [comment]
@xukongop https://github.com/uBlockOrigin/uAssets/commit/fab34801555f702f385324e09e5475571c747082

**Comment by xukongop** [comment]
> @xukongop [fab3480](https://github.com/uBlockOrigin/uAssets/commit/fab34801555f702f385324e09e5475571c747082)

Thank you.
