### ISSUE TITLE
phrasemix.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7262]
### URL(s) where the issue occurs

`https://www.phrasemix.com/`

### Describe the issue

Annoyance: a modal with scroll locked

### Screenshot(s)

![phrasemix](https://user-images.githubusercontent.com/58900598/79631633-9d74a900-8195-11ea-941e-ade4a912be99.png)

### Versions

- Browser/version: 1.7.92
- uBlock Origin version: 1.24.4

### Settings

- Default + uBlock Annoyances + Fanboy Annoyances

### Notes

`phrasemix.com##body:style(overflow auto !important)`
didn't work. Maybe
`phrasemix.com##+js(acis, $, showEmailNewsletterModal)`
`||phrasemix.com/assets/new_$image`

**Comment by llacb47** [comment]
That network rule seems a little broad.

**Comment by Yuki2718** [comment]
> 
> 
> That network rule seems a little broad.

Admittedly, but so far I haven't found a false positive and can't think of better one - `||www.phrasemix.com/assets/new_*.jpg|$image` is possible but I think the suggested rule is slightly more efficient.
