### ISSUE TITLE
Blank Google search results Firefox Android

### ISSUE THREAD

**Issue by yaakovfeldman** [uBlockOrigin/uAssets#7267]
### URL(s) where the issue occurs

`https://www.google.com/search?client=firefox-b-m&sxsrf=ALeKk00SfzGAwI679TO9Lr_u8HR4KH5i4g%3A1587251221352&q=coronavirus+russia&oq=coronavirus+russia&aqs=heirloom-srp.`

### Describe the issue

Search results are blank, with just the search box and the next button visible. Disabling ublock origin shows full results. Screenshot shows the relevant cosmetic filter. This does not occur on other google searches using this device. It only occurs with this exact search term. I suspect it is related to the Covid-19 box.

### Screenshot(s)

Firefox inspector remote debugging with ublock origin disabled:

![firefox inspector](https://user-images.githubusercontent.com/17687145/79682290-e0c42b80-8218-11ea-90cd-5450ea58450c.png)

Page with ublock origin enabled:

![Screenshot_20200419-083149_Firefox](https://user-images.githubusercontent.com/17687145/79682291-e15cc200-8218-11ea-9400-4c09aa3de8eb.png)

Logger:

![Screenshot_20200419-083126_Firefox](https://user-images.githubusercontent.com/17687145/79682292-e1f55880-8218-11ea-932f-3a89b53de499.png)

Page with ublock disabled:

![Screenshot_20200419-083139_Firefox](https://user-images.githubusercontent.com/17687145/79682293-e1f55880-8218-11ea-859c-efd049b3bcc8.jpg)

### Versions

- Browser/version: Firefox Android 68.7.0
- uBlock Origin version: 1.26.0

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

Note that (if trying to recreate) some Firefox Android users see different search results to others as Firefox Android sometimes silently spoofs Useragent to Google so that users will get richer search results, Chrome style. Mine is unspoofed. https://bugzilla.mozilla.org/show_bug.cgi?id=1620883

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0e85ac1a239ebf6249da9fe6bcd7ecfb52c0ede4#comments

Did you force update uBO lists ?

**Comment by ghajini** [comment]
BUt why covid19 results blocked?😅 not others😀(fix is working for me,don't worry)
