### ISSUE TITLE
2leep.com (ad provider) on englishrussia.com - taboola style

### ISSUE THREAD

**Issue by mparnelldmp** [uBlockOrigin/uAssets#727]
### URL(s) where the issue occurs

http://englishrussia.com

### Describe the issue

Annoying taboola style ads, image and text elements in a div.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/25654372/30990122-b8845aac-a465-11e7-827c-5f248f8a8c7b.png)

**Comment by gorhill** [comment]
The same way `taboola.com` is wholly blocked in Peter Lowe's, shouldn't we wholly block these two domains?

    ||2leep.com^$third-party
    ||likecontrol.com^$third-party

**Comment by mparnelldmp** [comment]
Blocking them wholly with my own user filter does a good job.

**Comment by gotitbro** [comment]
@gorhill It is already blocked in **_Adguard Base Filters_** in exactly the same way and as I said in my reply in a different thread making it default would drastically reduce the number of new issues and improve blocking.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/a13086f8f56507a21997872951c6fac08d025f8c
