### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by emiliou4756** [uBlockOrigin/uAssets#7270]
Ariva.de Homepage:

`https://www.ariva.de`

![image](https://user-images.githubusercontent.com/64039438/79791325-6a751580-834d-11ea-81ae-b6856de0a095.png)

![image](https://user-images.githubusercontent.com/64039438/79791447-9c867780-834d-11ea-8486-ea8478406062.png)

`https://www.ariva.de/x-dax-index/kursliste`

![image](https://user-images.githubusercontent.com/64039438/79791532-c2ac1780-834d-11ea-8d09-a275f409bc2e.png)

`https://www.ariva.de/fresenius_medical_care-aktie`

![image](https://user-images.githubusercontent.com/64039438/79791617-ee2f0200-834d-11ea-824c-6e0ef517ca39.png)

`https://www.ariva.de/news/dax-gibt-leicht-nach-141-punkte-verloren-8357269`

![image](https://user-images.githubusercontent.com/64039438/79791849-42d27d00-834e-11ea-8837-b00230f99382.png)

**Comment by emiliou4756** [comment]
finanznachrichten.de

https://www.finanznachrichten.de/

![image](https://user-images.githubusercontent.com/64039438/79792158-ba081100-834e-11ea-92c3-5cd758c46c28.png)


https://www.finanznachrichten.de/nachrichten-aktien/flir-systems-inc.htm

![image](https://user-images.githubusercontent.com/64039438/79792262-e328a180-834e-11ea-91e9-a592e9694394.png)

https://www.finanznachrichten.de/nachrichten-2020-04/49424919-aktie-von-trane-technologies-unter-druck-kurs-faellt-um-5-02-prozent-013.htm

![image](https://user-images.githubusercontent.com/64039438/79792388-1703c700-834f-11ea-8a58-b767936aaf6e.png)


Godmodetrader:

https://www.godmode-trader.de/indizes/dax-performance-index-kurs,133962

![image](https://user-images.githubusercontent.com/64039438/79792545-621dda00-834f-11ea-9114-8616ac02c9fb.png)

![image](https://user-images.githubusercontent.com/64039438/79792620-811c6c00-834f-11ea-8180-ce694dfdcce5.png)

https://www.godmode-trader.de/aktien/fresenius-medical-care-kurs,118686

![image](https://user-images.githubusercontent.com/64039438/79792704-a315ee80-834f-11ea-8479-f688adecd20f.png)

https://www.godmode-trader.de/analyse/fresenius-medical-care-widerstand-voraus,8296186

![image](https://user-images.githubusercontent.com/64039438/79792762-c04abd00-834f-11ea-8824-4284465b88e3.png)

https://www.godmode-trader.de/aktien/merck-kurs,121841


![image](https://user-images.githubusercontent.com/64039438/79792842-e40e0300-834f-11ea-8f25-aaae237dda57.png)

**Comment by emiliou4756** [comment]
wallstreet-online.de

https://www.wallstreet-online.de/

![image](https://user-images.githubusercontent.com/64039438/79793391-c42b0f00-8350-11ea-9b2e-ed898e38f3a9.png)


![image](https://user-images.githubusercontent.com/64039438/79793391-c42b0f00-8350-11ea-9b2e-ed898e38f3a9.png)

https://www.wallstreet-online.de/indizes/dax

![image](https://user-images.githubusercontent.com/64039438/79793503-fa688e80-8350-11ea-85c6-e0201b93b77d.png)

**Comment by Yuki2718** [comment]
Unless uBO-specific syntax is required, ads should be reported to an according filter maintainer such as EasyList Germany.

**Comment by mapx-** [comment]
easylist germany https://github.com/easylist/easylistgermany/issues
