### ISSUE TITLE
cwtvembeds.com [NSFW]

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#7271]
### URL(s) where the issue occurs

`[http://www.cwtvembeds.com/embed/69007]`

### Describe the issue

[Popup when pressing play/pause on the video.]

### Versions

- Browser/version: [Chrome v81]
- uBlock Origin version: [1.24.4]

### Settings

- [default]

**Comment by mapx-** [comment]
test
```
||wpnrtnmrewunrtok.xyz^$badfilter
cwtvembeds.com##.fp-ui
```

without the first one `I get Video file not found`
Is that video you want to watch from `CamWhores` ?

**Comment by dumbusernameidk** [comment]
this site `http://nudespree.com/videos/101236/nicolereed-squirt-cumshow/` but the popup comes from `cwtvembeds.com`

**Comment by mapx-** [comment]
Did you test the filters above ??

**Comment by dumbusernameidk** [comment]
yeah, they seem to work.

**Comment by mapx-** [comment]
I replaced the second filter with a better one (to get the play button), test again
