### ISSUE TITLE
Ublock has been blocking our sites

### ISSUE THREAD

**Issue by TeamZenler** [uBlockOrigin/uAssets#7272]
Hi Support,

 

We are New Zenler an All in one Course creation, Delivery and marketing platform.

Our customers have reported that while using U Bloc add on they cannot access the following site
(https://tutorials.newzenler.com/)
(https://getnzlr.newzenler.com/)
We need to know the reason as well as how to prevent it. This is an issue regarding the authenticity of our website. We have several other sites with the same subdomain only this particular one has the issue above mentioned.

We are looking for a solution ASAP as well as the reason for its occurrence.

Thank you in advance.

**Comment by uBlock-user** [comment]
> they cannot access the following site

I can access both sites, ask your customers if they're using any custom filterlists which are not part of the defauly settings.

**Comment by mapx-** [comment]
for the second test link I fixed some missing content
https://github.com/uBlockOrigin/uAssets/commit/afb462cb3e04945a30c61b39ec50ba326f83083e

You should tell us exactly what is wrongly blocked, missing stuff, how to reproduce, if we need an account etc

**Comment by TeamZenler** [comment]
I will post what exactly My customer said to me

"Looks like my son whitelisted it on mine to allow in the settings but that does not help us when clients click, can't proceed, and leave.
I was not using any custom filter lists when it happened. or ever.
Just out of the box Ublock."
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/64133832/80056586-344cb700-8542-11ea-9a6d-0d26d48d8de6.jpg)

**Comment by okiehsch** [comment]
I can acces the site just fine but I can't enroll into classes on my end. 
Is that the only breakage your clients report?
Ask them if adding
`@@||cloudfront.net/js/tracking.js$script,domain=newzenler.com`
to their filter list fixes all issues.
