### ISSUE TITLE
superdataresearch.com

### ISSUE THREAD

**Issue by 894-572** [uBlockOrigin/uAssets#7276]
### URL(s) where the issue occurs

`https://www.superdataresearch.com/`

### Describe the issue

A modal overlay appears on the website when scrolling down.

### Screenshot(s)

![Screenshot_2020-04-23 Worldwide digital games market — SuperData, a Nielsen Company](https://user-images.githubusercontent.com/44001490/80086241-f606c600-8548-11ea-91dd-68d6cb4e1256.png)

**Comment by mapx-** [comment]
add
`superdataresearch.com##.sqs-slide-wrapper`

@ryanbr
