### ISSUE TITLE
Disable class="noSelect" on site?

### ISSUE THREAD

**Issue by raulvasquez** [uBlockOrigin/uAssets#7278]
Can I make a rule with ublock to never allow a specific site to set class="noSelect" on content?

**Comment by uBlock-user** [comment]
website link ?

Classes can be removed with remove-class scriptlet.

**Comment by mapx-** [comment]
@raulvasquez requested details ?

**Comment by krystian3w** [comment]
yes with latest uBO:

```
*##+js(rc, noSelect)
```

---

`https://kinokrad.co/` locked header of title (center column).

![obraz](https://user-images.githubusercontent.com/35370833/80221124-25026200-8645-11ea-8dcb-b60a746f2568.png) |
--- |
