### ISSUE TITLE
movie1168.com

### ISSUE THREAD

**Issue by T-H-O-R** [uBlockOrigin/uAssets#7281]
### URL(s) where the issue occurs
`https://www.movie1168.com/movie/%e0%b9%84%e0%b8%9a%e0%b8%84%e0%b9%8c%e0%b9%81%e0%b8%a1%e0%b8%99-%e0%b8%a8%e0%b8%b1%e0%b8%81%e0%b8%a3%e0%b8%b4%e0%b8%99%e0%b8%97%e0%b8%a3%e0%b9%8c%e0%b8%95%e0%b8%b9%e0%b8%94%e0%b8%ab%e0%b8%a1%e0%b8%b6-F6oREmk7sY`

### Describe the issue
How to skip video ads in this website

### Screenshot(s)

![ส่งUBO1](https://user-images.githubusercontent.com/63744737/80234902-189cfa00-8683-11ea-8643-019a1f43f745.jpg)

### Versions

- Browser/version: [Chrome Version 79.0.3945.117]
- uBlock Origin version: [v1.26.0]

### Notes

This is my script

movie1168.com##div.go-hard
movie1168.com/*.gif$image
$media,3p,domain=laos-tech.com,redirect=noopmp4-0.1s

**Comment by llacb47** [comment]
Banners fixed in `https://github.com/realodix/AdBlockID` (not even a Thai list, lol).

Prerolls can't be skipped on my end.

```
movie1168.com##.go-hard
movie1168.com##.go-content
movie1168.com##+js(nano-sib, can_skip)
```

**Comment by mapx-** [comment]
yeah, only killing the countdown
```
*.gif$domain=www.movie1168.com,image
movie1168.com##go-hard
movie1168.com##+js(nano-sib)
```

**Comment by llacb47** [comment]
`movie1168.com##go-hard` missing `.`

**Comment by mapx-** [comment]
Weird, I re-tested using
`*$media,3p,domain=movie1168.com,redirect=noopmp3-0.1s`

and now seems working fine ..
