### ISSUE TITLE
uploadhub.club

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#7283]
### URL(s) where the issue occurs

`https://uploadhub.club/f/gxc3ah-9a1ynr70mm506`

### Describe the issue

Popup ads

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version: firefox A 68.7
- uBlock Origin version: 1.26.2

### Settings

 uBO's default settings

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by ghajini** [comment]
`https://uploadhub.club/157whqyp6tor`

Timer can be boosted

`uploadhub.*##+js(nano-setTimeout-booster)`

**Comment by stephenhawk8054** [comment]
There are ads in `uploadhub.ws`

URL: `https://uploadhub.ws/f/t6rmw3-4ma9rasqgwn68`

![image](https://user-images.githubusercontent.com/66517106/141897828-f7bfda49-5cf8-4b92-bdfe-a394adda6438.png)

Firefox 94.0.1, ublock 1.38.6 default

Proposed filter:

`uploadhub.*##+js(acis, JSON.parse, break;case $.)`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a829dfc033d1c83dcda259c512bc8018895fc46d
