### ISSUE TITLE
Anti-adblock on looopings.nl

### ISSUE THREAD

**Issue by joepie91** [uBlockOrigin/uAssets#7284]
### URL(s) where the issue occurs

`https://www.looopings.nl/`

### Describe the issue

Produces a "turn off your adblocker" blockade with uBlock Origin enabled (with default filter lists, I believe).

### Screenshot(s)

![Selection_981](https://user-images.githubusercontent.com/1663259/80290089-68db9100-8743-11ea-9701-87f4c1e9d84d.png)

### Versions

- Browser/version: Firefox 75.0, Linux
- uBlock Origin version: v1.26.2

### Settings

- No custom settings that I can recall, other than a few custom rules for specific other sites; those shouldn't affect this.

### Notes

Implemented using BlockAdblock and a common JS obfuscator (I forgot what it's called, it's the `(p,a,c,k,e,d)` one).

Can be fixed by adding the following rule, but I'm not sure in which list it should go:

```
www.looopings.nl##^script:has-text(p,a,c,k,e,d)
```

Blocks only the obfuscated BlockAdblock code.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/4f634806c4c8fa454e55d3ad826ad4b2be840f6b

force update uBlock Filters list.

**Comment by joepie91** [comment]
Thanks!

Out of curiosity, what does the `^$ghide` rule do? I can't find any documentation about it, and AFAIK all the BlockAdblock elements were randomly named.

**Comment by llacb47** [comment]
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#generichide

**Comment by joepie91** [comment]
Aha, so it breaks the adblocker detection by not doing cosmetic filtering, rather than removing the adblocker wall. Makes sense, thanks :)

**Comment by uBlock-user** [comment]
It's not the only way, though. Just one of many.
