### ISSUE TITLE
Filter for nordbayern.de not working anymore

### ISSUE THREAD

**Issue by noir-Z** [uBlockOrigin/uAssets#7286]
### URL(s) where the issue occurs

`nordbayern.de`
`https://www.nordbayern.de/politik/polizei-stoppt-illegale-keller-friseure-in-franken-jetzt-drohen-strafen-1.10055723`

### Describe the issue

Ads load as gifs from `*.t.nordbayern.de` and are not blocked

### Versions

- Browser/version: Vivaldi Stable 3.0.1874.32
- uBlock Origin version: 1.26.0

### Settings

- enabled advanced user to integrate nano defender

### Notes

Ads loaded as gifs from `*.t.nordbayern.de` are not blocked unless overwritten through a custom filter tagged with ,important
i added `||*.nordbayern.de/*.gif$image,important` as i don't want to see gifs on this website anyways and assume that the subdomain **t**.nordbayern.de might change frequently but i have not confirmed this.
note that it will not work without `,important` probably due to the exception for nordbayern in this filterlist.

**Comment by mapx-** [comment]
screenshot with the ads ?

**Comment by noir-Z** [comment]
![2020-04-26 15 43 50 www nordbayern de f417756ea8d6](https://user-images.githubusercontent.com/45096516/80309685-d97fbd80-87d6-11ea-9035-a11e80543f74.png)

**Comment by mapx-** [comment]
- still no such ads on my end
- test again using the default settings in uBO
- if still does not work test this filter:
`nordbayern.de##+js(acis, jQuery, #web)`

**Comment by mapx-** [comment]
Could also be some interference from vivaldi own blocker ?! (if already enabled)

**Comment by noir-Z** [comment]
oof, i am sorry for wasting your time. 
i did not expect that the vivaldi adblocker would interfere, idk when i turned it on but turning it off fixed it. ads are now blocked with default settings and restored previous settings. 
on my gfs machine abp was causing the interference.
