### ISSUE TITLE
Foxnews.com live video

### ISSUE THREAD

**Issue by AlexMcArdle** [uBlockOrigin/uAssets#729]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://video.foxnews.com/v/1241186546001/?#sp=watch-live`

### Describe the issue

Recently (first noticed 9/28) Foxnews.com live player is not loading. Fox recently updated their video player to show a live preview (~10 minutes) before you sign in so it could have something to do with that.

Gist of the logger: https://gist.github.com/AlexMcArdle/29fb524e51d66597596de617457ed2e0

### Screenshot(s)

![fnc](https://user-images.githubusercontent.com/941476/31018652-79c28518-a4f2-11e7-978b-e375de3a0b78.PNG)

### Versions

- Browser/version: Chrome Windows x64 61.0.3163.100
- uBlock Origin version: 1.14.8

### Settings

- none

### Notes

Provided gist above. Not working in Firefox either.

**Comment by mapx-** [comment]
add
```
||cdn.krxd.net^$script,redirect=noopjs,domain=video.foxnews.com
@@||global.fncstatic.com/$script,domain=video.foxnews.com
```

**Comment by terrorist96** [comment]
### URL(s) where the issue occurs

`https://insider.foxnews.com/2019/01/15/judge-andrew-napolitano-bob-mueller-sole-issue-william-barr-confirmation`

### Describe the issue

Video won't play

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/51253500-7618a600-196c-11e9-95ac-65c2f5edef5f.png)

### Notes

EasyList is the issue. Haven't been able to narrow it down to what filter exactly yet.

**Comment by mapx-** [comment]
does this work for you ?
`@@||video.insider.foxnews.com/$script,1p`

**Comment by terrorist96** [comment]
No.

**Comment by terrorist96** [comment]
`@@/ima3.js` fixes it.

**Comment by mapx-** [comment]
No `ima3.js` request  for me using european ip.
Only using us ip I get the issue.

**Comment by terrorist96** [comment]
`https://video.foxnews.com/v/6083433910001#sp=show-clips`

Video doesn't load.

`@@||static.foxnews.com/static/isa/app/lib/VisitorAPI.js$script,domain=static.foxnews.com`

**Comment by okiehsch** [comment]
https://github.com/easylist/easylist/commit/7ce1e64e449333976874b6242d7e9dec7f6c52c4
