### ISSUE TITLE
vkmag.com video blacked out, possible smart anti-adblock

### ISSUE THREAD

**Issue by ahydronous** [uBlockOrigin/uAssets#7293]
### URL(s) where the issue occurs

`https://www.vkmag.com/magazine/jachtluipaard_zoekt_het_hogerop_voor_rustige_maaltijd`
, slightly NSFW

This only happens for some videos on the site, those that are embedded from dailybuzz.nl (an affiliated site of vkmag.com). Instagram or YouTube videos work fine as long as the relevant urls are nooped or allowed.

### Describe the issue

uBlock is being detected even with all URLs locally allowed ('greenlit), a black layer is placed in front of the video but the video still plays. Turning off uBlock with the big blue power button in the extension menu, or completely disabling the extension via extension management allows the video to play normally

### Versions

- Browser/version: v1.26.2
- uBlock Origin version: Firefox 75.0

### Settings

- uBlock is in medium blocking mode (default deny of 3rd party scripts and frames), but the issue happens even if uBlock is used in completely default configuration and default lists

### Notes

It doesn't matter which filters are disabled, or even if all the urls are locally allowed or globally allowed. The only thing that works is turning off uBlock with the power button, or disabling the extension entirely.

**Comment by llacb47** [comment]
It works fine for me.

**Comment by okiehsch** [comment]
Do you have `Fanboys Annoyance List` enabled?

**Comment by llacb47** [comment]
Good find, that rule is too risky IMO.

`dailybuzz.nl#@#.vjs-share`

**Comment by okiehsch** [comment]
@ryanbr to reproduce go to
`https://dailybuzz.nl/buzz/embed/19405`

**Comment by ahydronous** [comment]
@okiehsch apologies! I thought Fanboy his list is part of the default (there is no way to reset lists to default).

That leaves me wondering though, shouldn't greenlighting an url (either locally or globally) disable all filtering for that particular url? I don't understand how Fanboys filter could still cause troubles then..

**Comment by llacb47** [comment]
There is a way to reset lists to default. 
![image](https://user-images.githubusercontent.com/16567977/80620345-dfaead80-8a13-11ea-8760-e81453e30f22.png)

I don't know about the local and global allowing not disabling cosmetic filters.

**Comment by ahydronous** [comment]
I think this might be what is causing it

![Problem](https://user-images.githubusercontent.com/57762816/80621085-1520be80-8a47-11ea-8033-475bfa8ec73b.png)
