### ISSUE TITLE
www.paginasiete.bo video ads

### ISSUE THREAD

**Issue by magicalthaw** [uBlockOrigin/uAssets#7295]
URL(s) where the issue occurs
`www.paginasiete.bo`

Describe the issue
after a few seconds i visit the site appears a video in a corner that's quite annoying any fix please

chrome 81.0.4044.129
uBlock Origin v1.26.0

**Comment by magicalthaw** [comment]
looks like it's fixed thanks

**Comment by uBlock-user** [comment]
which  list?

**Comment by magicalthaw** [comment]
@uBlock-user i am not sure but. it was a small pop up youtube video in the left corner is not anymore there, now there are a facebook video above that is played automatically

**Comment by uBlock-user** [comment]
Ads first must be reported at Easylist Spanish since they can be blocked without the extended syntax.

**Comment by magicalthaw** [comment]
> Ads first must be reported at Easylist Spanish since they can be blocked without the extended syntax.

ok, i will do that then thanks

**Comment by uBlock-user** [comment]
Yes.

**Comment by magicalthaw** [comment]
i want to open again this issue please: 
`https://www.paginasiete.bo/sociedad/2020/5/7/la-historia-del-asambleista-que-violo-abuso-de-ninos-254757.html
`
that embed audio in the right corner don't allow me read properly

**Comment by mapx-** [comment]
@magicalthaw
`paginasiete.bo##.inview-bottom-left`

**Comment by magicalthaw** [comment]
@mapx thanks it works, could you add this to filters please? or where i should request this?

**Comment by mapx-** [comment]
Well, it's annoyance - not an ad - you could report it to some spanish list (Easylist - but I saw you deleted your post on EL forum - or Adguard spanish list)

**Comment by magicalthaw** [comment]
> Well, it's annoyance - not an ad - you could report it to some spanish list (Easylist - but I saw you deleted your post on EL forum - or Adguard spanish list)

i reported in github easylist spanish also, i hope they can add this to the list, thanks again
