### ISSUE TITLE
debrid-file.com (Anti-Adblock)

### ISSUE THREAD

**Issue by P0Rtvine** [uBlockOrigin/uAssets#7296]
`https://debrid-file.com/index.php`

### Describe the issue

Waiting for 30-40 seconds.

### Screenshot(s)
![2020-04-29_173213](https://user-images.githubusercontent.com/57287308/80608407-6462f100-8a3f-11ea-9ef3-f3da95919bf2.png)

### Versions

- Browser/version: **Opera|Stable**
- uBlock Origin version: **1.26.2**

### Settings
![2020-04-29_173058](https://user-images.githubusercontent.com/57287308/80608319-41d0d800-8a3f-11ea-9e53-3456477bd2fb.png)

**Comment by ediowar** [comment]
@P0Rtvine https://postimg.cc/zydYC1x2
> Bonjour à tous,
comme vous avez pu le remarquer depuis le 27 avril 2020 notre site debrid-file.com n'est plus disponible, nous avons des soucis avec notre script, malheureusement cela dépasse nos compétences, nous avons besoin d'engager un codeur pro afin de vérifier notre code et de le sécuriser, pour cela nous avons ouvert une cagnotte sur Lepotcommun afin de récolter des fonds pour pouvoir payer un codeur avec de l'expérience et qui pourra nous rétablir au plus vite notre site en toutes sécurités, je remercie tous ceux qui pourront nous aider dans notre situation.
Carbone78 / File-debrid

**Comment by uBlock-user** [comment]
The script is not present at the time of repro.

**Comment by P0Rtvine** [comment]
> The script is not present at the time of repro.

![1](https://user-images.githubusercontent.com/57287308/80634087-8b7eea00-8a62-11ea-8ca4-1aedd64a23e2.gif)

**Comment by llacb47** [comment]
`@@||debrid-file.com^$ghide`

**Comment by P0Rtvine** [comment]
> `@@||debrid-file.com^$ghide`

Or `debrid-file.com##+js(nobab)`

**Comment by uBlock-user** [comment]
@P0Rtvine You didn't provide the password to reproduce neither the image before, otherwise this would have been addressed earlier.
