### ISSUE TITLE
spiegel, zeit anti adb

### ISSUE THREAD

**Issue by emiliou4756** [uBlockOrigin/uAssets#7298]
`https://www.spiegel.de/netzwelt/apps/kampf-gegen-das-coronavirus-die-eierlegende-wollmilch-app-a-8d657487-cf5a-468a-b207-8a4841ac51ed`

### Describe the issue
sometimes this layer appeas

### Screenshot(s)
![image](https://user-images.githubusercontent.com/64039438/80616436-3383bb80-8a41-11ea-9148-20dbed778759.png)

### Versions

- Browser/version: firefox latest version
- uBlock Origin version: 1.26.2

spiegel.de
![image](https://user-images.githubusercontent.com/64039438/80617061-ece29100-8a41-11ea-85dd-5974f32bf858.png)

Zeit.de
![image](https://user-images.githubusercontent.com/64039438/80616673-79d91a80-8a41-11ea-92d0-c425c96d522c.png)

**Comment by okiehsch** [comment]
The `zeit.de` screenshot is not an anti adblocker message, you will get that modal after deleting cookies with uBO disabled. Just click "Einverstanden" and you can use the site without issues.

I can reproduce the spiegel anti adblock issue.

**Comment by JobcenterTycoon** [comment]
I get a error screen with that filter when i click on "akzeptieren"

<img width="538" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/80728616-6d1efa00-8b07-11ea-926b-845d67471b03.PNG">

**Comment by mapx-** [comment]
- spiegel seems broken indeed.
- disabling `_sp_.mms.startMsg` filter I get the anti adb stuff

for now:
1. `spiegel.de##+js(aopr, document.cookie)` works for layer / anti adb, but .. breaks at least the comments 
2. working filters (but disabling all specific hiding)
```
*$script,redirect-rule=noopjs,domain=spiegel.de
*$xhr,redirect-rule=noopjs,domain=spiegel.de
@@||spiegel.de^$shide
```

I'll remove for now the breaking filter

**Comment by okiehsch** [comment]
Hm, now I can't reproduce the anti adblock message.

**Comment by emiliou4756** [comment]
just open several tabs, suddenly its there. not always.

**Comment by okiehsch** [comment]
Have you tried updating the filter list using android?
The filter causing the can't save cookies message has been removed.

**Comment by emiliou4756** [comment]
all ok! first party cookies must be enabled.
