### ISSUE TITLE
Tracking Server / Analytics

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#7299]
https://github.com/easylist/easylist/issues/5304
Please temporarily add `||analyti.io^$3p` (found in `13tv.co.il` / `13news.co.il`) to **privacy.txt** till it will be added to EasyPrivacy. Sometimes it takes them many days to respond...

**Comment by llacb47** [comment]
Can be removed now: https://github.com/easylist/easylist/commit/a22800e0fd5f900645fa3ac3073881e67ec47eb8
