### ISSUE TITLE
NSFW Ads adult sites

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#7301]
### URL(s) where the issue occurs

**NSFW**

`https://beegsexxx.com/` /fixed

`https://beeg.party/video/novice-dishonest-wifey` /fixed

`https://www.pornhd.com/` fixed

`https://m.spankbang.com/`  fixed

`https://spankbang.name` /fixed

`https://xnxxxvideos.co/` /fixed

`https://spankbang.cc/` /fixed

`https://www.porndig.com/` fixed

`https://www.vporn.com/` fixed

`https://www.pornflip.com` fixed

`https://www.tubxporn.com/` /fixed

`https://www.peekvids.com/`  - **clicking on video results in strict block page and not video** /fixed

`https://www.pornid.xxx` fixed

`https://www.pinflix.com/` fixed

`https://www.pornrox.com/` fixed

`https://www.youporn.com/watch/15890956/stepdad-woke-up-his-stepdaughter-and-then-she-started-fuck-with-him/` - **video not playing**

`Txxx.com`

`http://v.xtapes.to/` fixed

### Describe the issue

Popup ads, popunders ,crap xhr's 
Clicking on homepage videos results in ads

### Versions

- Browser/version: firefox A.
- uBlock Origin version: 1.26.2

### Settings

-  uBO's default settings

**Comment by mapx-** [comment]
`youporn` + `txxx` are ok on my end

**Comment by ghajini** [comment]
NSFW
`https://txxx.com/videos/1263243/black-guy-fucks-nicole-and-gives-her-facial/`

hamburger menu is inaccessible

**Comment by mapx-** [comment]
it seems `txxx.com##+js(aeld, click, target)` is to keep only for desktop, can you confirm (and will have still the popunder) ?

**Comment by ghajini** [comment]
Wait there are popunders on every click

**Comment by mapx-** [comment]
first 2-3 on my end

**Comment by ghajini** [comment]
Isn't that annoying popunders though blocked results in reload of page everytime?
What can be done to stop that?

**Comment by mapx-** [comment]
We could stop popunders using `||txxx.com/covad/`

**Comment by ghajini** [comment]
All looks good👍

**Comment by ghajini** [comment]
**NSFW**
`https://txxx.tube/videos/2933210/megan-sage-tommy-gunn-in-shake-your-money-maker-brazzers/`

Popup ads

**Comment by ghajini** [comment]
Popup ads

`https://www.pornid.name`

`https://www.pornhdin.com`

**Comment by mapx-** [comment]
`pornhdin.com` redirects to `pornhd.com` on my side & no popups

**Comment by ghajini** [comment]
try with Indian ip
`pornhdin.com` is for indian region specific

**Comment by mapx-** [comment]
test
`pornhdin.com##+js(acis, document.querySelectorAll, popMagic)`

**Comment by ghajini** [comment]
Doesn't work, there is ad of `syndication.dynsrvwer.com` which then propagates to random ads

**Comment by ghajini** [comment]
Page served
`https://pastebin.com/BV2z7PjW`

**Comment by mapx-** [comment]
maybe you forgot to say it's on mobile

test
```
pornhdin.com##+js(acis, document.querySelectorAll, popMagic)
pornhdin.com##+js(aopr, ExoLoader.serve)
pornhdin.com##+js(aopr, open)
```

**Comment by ghajini** [comment]
Most of the time iam on mobile (sorry I forgot tell you)

Given filters work
