### ISSUE TITLE
Anti-adblock on animexin.xyz

### ISSUE THREAD

**Issue by erosman** [uBlockOrigin/uAssets#7302]
### URL(s) where the issue occurs
`https://animexin.xyz/`

### Describe the issue

Anti-adblock from `blockadblock.com`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/6458876/80807336-2d711480-8bd2-11ea-9dae-b75b676c4ac5.png)

### Versions

- Browser/version: 77.0a1 (2020-04-30) (64-bit)
- uBlock Origin version: 1.26.2

### Settings

- default

Also reset to default and updated

### Notes
mone

**Comment by IThinkIAmCool** [comment]
ads -- at least one of them seems to be for a casino
