### ISSUE TITLE
stickr.co

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#7306]
### URL(s) where the issue occurs

`https://campaign.stickr.co/quiz1`

### Describe the issue

Can't finish quiz.

### Notes

`@@||d26b395fwzu5fz.cloudfront.net/keen-tracking-1.0.3.min.js$script,domain=campaign.stickr.co`

**Comment by mapx-** [comment]
I used a redirect, working for me, could you test too ?

**Comment by krystian3w** [comment]
loop on `https://campaign.stickr.co/quiz-2?surveyoutcome=default&surveyresults=true`

maybe need 1 more redirect or exception.

**Comment by terrorist96** [comment]
It seems to be working fine for me.
