### ISSUE TITLE
receive-a-sms.com 

### ISSUE THREAD

**Issue by mapx-** [uBlockOrigin/uAssets#731]
Chrome Version 62.0.3202.38 (Official Build) beta (64-bit)
default filters

go to `https://receive-a-sms.com/USA`
=> redirected here: `https://receive-a-sms.com/adblock`

(`https://receive-a-sms.com/USA2` works fine like other addresses see bellow the inline script)

working filter:
`@@||receive-a-sms.com/*ad$xmlhttprequest`

This filter does not work:
`||receive-a-sms.com/showads.js$xmlhttprequest,redirect=nooptext`

Executing in console `$.ajax('showads.js')` I get `statusText = "error"`
Do we need another type which returns `statusText = "success"` ?

```
<script>
$(document).ready(function() {
$.ajax('showads.js').fail(function(d){if(d.status===0 || d.statusText == 'error'){ $('html').addClass('ab'); $(".ab").css("display", "inline-block");

var chick = window.location.href.indexOf('USA2') > -1;
var chick2 = window.location.href.indexOf('UK2') > -1;
var chick3 = window.location.href.indexOf('Sweden') > -1;
var chick4 = window.location.href.indexOf('Canada2') > -1;
var chick5 = window.location.href.indexOf('usa2') > -1;

if ((!chick)&&(!chick2)&&(!chick3)&&(!chick4)&&(!chick5)) {
window.location.href = "http://receive-a-sms.com/adblock";
}
}});
});
</script>
```

**Comment by mapx-** [comment]
or `$.ajax('showads.js')` is failing due to some CSP security directive ?

`Failed to load data:text/plain;base64,: Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response.`

**Comment by okiehsch** [comment]
`receive-a-sms.com##script:inject(abort-current-inline-script.js, $, chick)`
works for me.

**Comment by mapx-** [comment]
Why this 1:
`receive-a-sms.com##script:inject(abort-current-inline-script.js, chick)`

does not work ?

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/618#issuecomment-321842729
You need a global hook and then you can narrow it down by requiring a match with the text content of the current inline script, in this example chick.

**Comment by uBlock-user** [comment]
I'm using this - `receive-a-sms.com##script:inject(abort-current-inline-script.js, $, showads.js)`

**Comment by gotitbro** [comment]
@okiehsch I am again getting the anti adb warning on: `https://receive-a-sms.com/USA`

**Comment by mapx-** [comment]
```
receive-a-sms.com##script:inject(abort-current-inline-script.js, $, showads.js)
receive-a-sms.com##[id^=aswift]
```

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://www.receive-a-sms.com/USA2?noads=adblock`
