### ISSUE TITLE
qBittorrent forum URL blocked

### ISSUE THREAD

**Issue by FranciscoPombal** [uBlockOrigin/uAssets#7310]
### URL(s) where the issue occurs

`forum.qbittorrent.com`

### Describe the issue

This URL gets blocked as a badware risk - why? It's under the control of the qbittorrent team and currently redirects to `https://qbforums.shiki.hu/`.

### Screenshot(s)

Not applicable.

### Versions

- Browser/version: Firefox 75.0 (`75.0+build3-0ubuntu0.18.04.1`)
- uBlock Origin version: 1.26.2

### Settings

- all filter lists are enabled, with the exception of: any list from the "Regions, languages" section.
- everything else default

### Notes

The offending rule reads:
`||qbittorrent.com^$document`,
when viewing `ublock-badware` in the asset viewer.

**Comment by gwarser** [comment]
Are you confusing `.com` with `.org`?

**Comment by llacb47** [comment]
It's a fake site. Official site is `qbittorent.org`. 

`https://www.bleepingcomputer.com/news/security/fake-websites-for-keepass-7zip-audacity-others-found-pushing-adware/`

By the way, above each entry/entries is a comment to the relevant issue that caused it to be added.

**Comment by gwarser** [comment]
https://qbforums.shiki.hu/viewtopic.php?t=5375

**Comment by FranciscoPombal** [comment]
@gwarser Interesting. Recently I've been working in some PRs, where I have been told by other project members to use `forum.qbittorrent.com` in preference to `https://qbforums.shiki.hu/` in documentation links.

That forum exchange is 3 years old. I wonder if it still accurately reflects the state of affairs, and if it does, I wonder if the other project members are not aware of the situation. I'll investigate further, thanks.

**Comment by FranciscoPombal** [comment]
Never mind, I'm just retarded, the real link is supposed to be forum.qbittorrent.**org**
