### ISSUE TITLE
abcvideo.cc { Antiadblock }

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#7311]
### URL(s) where the issue occurs

`https://abcvideo.cc/vf4gmaa16j6m.html`

### Describe the issue

Antiadblock, audio running, video not available to see replaced by Adblock warning

### Screenshot(s)

https://user-images.githubusercontent.com/20338483/80955512-0e19f780-8e1d-11ea-9674-92eba938d52b.jpg

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.26.2

### Settings

-  uBO's default settings

**Comment by ghajini** [comment]
Popups
`https://abcvideo.cc/h9kjx96uy9t3.html`

Filter 
`abcvideo.cc##+js(acis, Math, zfgloaded)`

**Comment by mapx-** [comment]
other filters which could replace csp one:
`abcvideo.cc##+js(aopw, _pop)`
or
`abcvideo.cc##+js(aopr, AdservingModule)`

**Comment by ghajini** [comment]
`proceed to video` button doesn't result in video page....

`https://abcvideo.cc/4r9rttkkkl10.html`

Firefox A., ublock origin 1.27.7.3
