### ISSUE TITLE
Spiegel.de: element pickup and cosmetic filters are disabled when using current build-in 'ublock filters'

### ISSUE THREAD

**Issue by LonelyHellhound** [uBlockOrigin/uAssets#7312]
### URL(s) where the issue occurs
`https://www.spiegel.de`

### Describe the issue
The current 'ublock filters' contains a rule for spiegel.de that disabled all cosmetic filters and the possiblity to pickup an element.
This issue occurs only on spiegel.de.

### Versions

- Browser/version: tested with Firefox 76, Edge, Vivaldi 3.0
- uBlock Origin version: 1.26.2

### Notes
The rule that causes the issue can be found in line 4920:

**@@||spiegel.de^$shide**

As soon as this rule was removed ublock works as expected.

**Comment by mapx-** [comment]
Without that filter you'll get anti adblocking stuff

**Comment by LonelyHellhound** [comment]
But if this filter is enabled, cosmetic filters and the pickup functionality are completely disabled :-|

For example I hide the complete header (via the pickup feature)

If rule @@||spiegel.de^$shide is disabled:
![Screenshot at 2020-05-04 17-40-45](https://user-images.githubusercontent.com/58397162/80984970-19b9ee00-8e1e-11ea-9d9f-816f92ee775b.png)

If rule @@||spiegel.de^$shide is enabled:
![Screenshot at 2020-05-04 17-38-56](https://user-images.githubusercontent.com/58397162/80985063-3bb37080-8e1e-11ea-9f95-e96195b4a8e2.png)

**Comment by uBlock-user** [comment]
> But if this filter is enabled, cosmetic filters and the pickup functionality are completely disabled

Yes, it's a uBO bug, hasn't been fixed yet.

**Comment by mapx-** [comment]
Hmm, cannot be fixed, `shide` will disable any filter created by the picker

**Comment by okiehsch** [comment]
You can add
````
||spiegel.de^$shide,important
spiegel.de#@#.asset-affiliatebox
spiegel.de#@#.nativead
spiegel.de#@#.nativead + .headline-date
spiegel.de#@#a[href^="http://paid.outbrain.com/network/redir?"]
spiegel.de#@#a[href^="https://paid.outbrain.com/network/redir?"]
spiegel.de#@#a[data-nvp*="'trafficUrl':'https://paid.outbrain.com/network/redir?"]
spiegel.de#@#a[onmousedown^="this.href='https://paid.outbrain.com/network/redir?"]
spiegel.de#@#a[onmousedown^="this.href='http://paid.outbrain.com/network/redir?"]
````
to your filter list. The picker will work and you should not see any anti adblock message,

**Comment by RolfWojtech** [comment]
Just wanted to confirm that the solution by okiehsch works for me. Is there a reason why the filter list cannot be adjusted to reflect these changes?

**Comment by mapx-** [comment]
done
