### ISSUE TITLE
Please unbreak camclips.cc [NSFW]

### ISSUE THREAD

**Issue by khand100** [uBlockOrigin/uAssets#7313]
### URL(s) where the issue occurs
NSFW
`https://camclips.cc/video/gQ7G`

### Describe the issue
The filter `camclips.cc##+js(aopr, __INITIAL_STATE__)` from https://github.com/uBlockOrigin/uAssets/commit/15dfbd04e3cd5b7b7aea9b5b9b12df8ddfe4a2bd#diff-728d382ab45d1e85df51bb432db0ce90R10586 is way to strict. It basically blocks all javascript on the site. Thus no interaction is working. Like add a video to favorites or get preview thumbnails also it only shows the native browser player instead of the sites customized player.

### Screenshot(s)

[Screenshot of nativ browser player](https://i.imgur.com/x7v9muY.png)
[Screenshot of correct player](https://i.imgur.com/vpgw6kR.png)

### Versions

- Browser/version: Firefox 75.0
- uBlock Origin version: 1.26.2

**Comment by llacb47** [comment]
Screenshots also NSFW.

**Comment by khand100** [comment]
Thanks that was fast.
