### ISSUE TITLE
Legacy filters - long expires time

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#7318]
`! Expires: 11 days`
I think there is no reason not to set it to 4 days like all the others in uAssets.

**Comment by uBlock-user** [comment]
@gorhill WDYT ?

**Comment by gorhill** [comment]
What is "Legacy filters"?

**Comment by gorhill** [comment]
This? <https://github.com/uBlockOrigin/uAssets/blob/master/filters/legacy.txt>

According to the commit history, it's not updated very often, there is no reason to worry about 11 days -- if there is no reason to burden GitHub's bandwidth with fetches which are not needed.

**Comment by IsraeliUser** [comment]
@gorhill 
It's a very small file (<2KB) and it's only used by a small minority of uBO's users. No need to worry about GitHub servers...
If an urgent fix is needed (a very popular site becomes broken, a bad commit that breaks many sites) - then the long expires time becomes a problem.
You are owner of this project and I will respect any decision you make.

**Comment by uBlock-user** [comment]
A cdnUrls implemention like in WebExtensions version can be take the brunt of fetches with 4 days setting while the github list still remains at 11 days.

@JustOff

**Comment by JustOff** [comment]
Given the fairly small number of users of the uBO legacy, I don't really feel using CDN is necessary unless we are forced to. And even in the case, setting different expiration times for the same filter on GitHub and CDN does not seem possible anyway.
