### ISSUE TITLE
speedtest.net

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#732]
"Adblocker error" is shown on `http://beta.speedtest.net`.

**SS:** https://i.imgur.com/2kXdYsm.png
**Error URL:** `http://beta.speedtest.net/`

The error appears after the speed test is started. They also ask to add their own custom filters as can be seen in the screenshot. This filter seems to be the one that is causing the issue: `|http://$xmlhttprequest,domain=speedtest.net`

_**Note:** Using 1.14.8 on Chrome 61 with the default filters and settings._

**Comment by mapx-** [comment]
`@@*nocache=$xmlhttprequest,domain=beta.speedtest.net`

**Comment by SMed79** [comment]
Why a wildcard (*) filter instead of a specific one?

`@@||speedtest.sanpedrowifi.com:8080/*?nocache=$xmlhttprequest,domain=beta.speedtest.net`

**Comment by okiehsch** [comment]
That filter would not work for everybody because the `sanpedrowifi.com`part of it depends on your location.

**Comment by gotitbro** [comment]
@okiehsch is right @SMed79, the server domain requests are dependent on location and the server selection. You can even test this by just choosing a different server.

We could make a filter like `@@||*.speedtest.*?nocache=$xmlhttprequest,domain=beta.speedtest.net`

But we cannot be sure that would work because different Speedtest partners could use different URL structures.

**Comment by gorhill** [comment]
Can't `||speedtest.*nocache=` be used instead?

`*nocache=` will cause uBO to test the filter for every request of type xmlhttprequest, because no token can be extracted.

**Comment by SMed79** [comment]
I confirm after a test behind a vpn but the port does not change for me.

(Reported https://forums.lanik.us/viewtopic.php?p=125033#p125033)

**Comment by gotitbro** [comment]
@gorhill I think you meant `@@||speedtest.*nocache=`. Yes that could work but can we be sure that all Speedtest servers use that URL structure? While I have only seen that structure in play (e.g. speedtest.unionwireless.com) but we cannot say confirmingly that all servers follow the same. If we could find Speedtest documentation that says this it would help.

**Comment by gotitbro** [comment]
@SMed79 Yes even I have only seen the same port being used.

**Comment by gotitbro** [comment]
@gorhill Okay we can add the filter as suggested above. i found documentation confirming the same:
https://support.ookla.com/hc/en-us/articles/234578568

@SMed79 It even mentions the 8080 port in the documentation as well.

**Comment by gorhill** [comment]
I will change to `@@||speedtest.*.com:8080^$xmlhttprequest,domain=beta.speedtest.net` if nobody raises a good argument against.

**Comment by SMed79** [comment]
> we can add the filter as suggested above

Not sure, see
http://i.imgur.com/dhPGvg4.png
http://i.imgur.com/9i3ApQs.png

I suggest
```
@@:8080/hello?nocache=*-$xmlhttprequest,third-party,domain=beta.speedtest.net
@@:8080/upload?nocache=*-$xmlhttprequest,third-party,domain=beta.speedtest.net
```

**Comment by gorhill** [comment]
Alright then, I guess @SMed79's solution seems the right one. I just propose using one filter?

    @@:8080/*?nocache=$xmlhttprequest,third-party,domain=beta.speedtest.net

**Comment by SMed79** [comment]
and an ip adress here http://i.imgur.com/w7Mm4oj.png

**Comment by okiehsch** [comment]
@SMed79 that does not work you also have to allow 
`@@:8080/download?nocache=*-$xmlhttprequest,third-party,domain=beta.speedtest.net`

**Comment by gorhill** [comment]
Ugh...

Well then `?nocache=$xmlhttprequest,third-party,domain=beta.speedtest.net`?

**Comment by gotitbro** [comment]
@gorhill Not `.com` as a site can use any tld. I am not even sure of their speedtest URL structure as different examples are given in https://support.ookla.com/hc/en-us/articles/234578628.

Different ports are mentioned there as well.

**Comment by gotitbro** [comment]
@SMed79 Well that is weird as they say they do not allow IP hostnames:

> My submission is being denied because of IP hostnames?
> 
> > We require all server URLs to use public DNS resolvable hostnames. This is a requirement to support planned future functionality such as IPv6.
> > 
> > Not allowed:
> > 
> > http://192.168.10.10/speedtest/upload.php
> > 
> > Allowed:
> > 
> > http://speedtest.mycompany.com/speedtest/upload.php

**Comment by okiehsch** [comment]
How abot we just use the filters speedtes itself suggests
````
@@/hello^$xmlhttprequest,domain=speedtest.net 
@@/ping^$xmlhttprequest,domain=speedtest.net @@/download^$xmlhttprequest,domain=speedtest.net @@/upload^$xmlhttprequest,domain=speedtest.net
````

**Comment by gotitbro** [comment]
@okiehsch Lol, yeah I was thinking the same. But probably not as they have at multiple instances abused whitelist filters.

**Comment by gorhill** [comment]
I got an error on my side with this being blocked:

    http://srv12.mtlcx03.fibrenoire.ca:8080/download?size=100000&nocache=5c0be73d-2b4a-45bd-8ebd-abbb033020a7

We also need `@@/download^`.

**Comment by gotitbro** [comment]
Lets use their suggested filters but limit them to the `beta.speedtest.net` domain for now.

**Comment by okiehsch** [comment]
`@@/download^$xmlhttprequest,domain=speedtest.net` is part of speedtest suggested filterset, I don'see
a reason for `@@/ping^$xmlhttprequest,domain=speedtest.net` on my end.

**Comment by SMed79** [comment]
> How about we just use the filters speedtest itself suggests

or
```
@@:8080/hello?nocache=$xmlhttprequest,third-party,domain=beta.speedtest.net
@@:8080/ping?nocache=$xmlhttprequest,third-party,domain=beta.speedtest.net
@@:8080/download?nocache=$xmlhttprequest,third-party,domain=beta.speedtest.net
@@:8080/upload?nocache=$xmlhttprequest,third-party,domain=beta.speedtest.net
```

**Comment by gotitbro** [comment]
@SMed79 But in your IP address screenshot there are no ports being used: http://i.imgur.com/w7Mm4oj.png?

**Comment by SMed79** [comment]
> But in your IP address screenshot there are no ports being used

+1

**Comment by gotitbro** [comment]
@SMed79 Cannot limit to third-party and XHR as well because Speedtest hosts their own server as well which uses websockets and is first party https://i.imgur.com/GzlXIXM.png.

**Comment by okiehsch** [comment]
So to sum up
`````
@@/ping^$xmlhttprequest,domain=beta.speedtest.net 
@@/download^$xmlhttprequest,domain=beta.speedtest.net 
@@/upload^$xmlhttprequest,domain=beta.speedtest.net
````
are needed on my end.
Does anybody need
`@@/ping^$xmlhttprequest,domain=speedtest.net`?

**Comment by gotitbro** [comment]
@okiehsch I haven't seen the ping request but probably not any harm in adding it.

**Comment by SMed79** [comment]
All what i see `/hello` and `/upload`.

**Comment by gotitbro** [comment]
@mapx- Can you see if you get the ping requests?

**Comment by mapx-** [comment]
it's ok using only
```
@@/hello^$xmlhttprequest,domain=speedtest.net 
@@/download^$xmlhttprequest,domain=speedtest.net 
@@/upload^$xmlhttprequest,domain=speedtest.net
```

**Comment by uBlock-user** [comment]
Why not just patch the SourcePoint script instead ?

`speedtest.net##script:inject(abort-on-property-write.js, _sp_)` 

That patches the anti adblock notice on my end.
