### ISSUE TITLE
twitter.com: cover Japanese too

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7321]
### URL(s) where the issue occurs

`https://twitter.com/`

### Describe the issue

Please expand the current rules for promoted tweets in uBlock filters to cover Japanese too.

### Screenshot(s)

Unfortunately I can't reproduce now, but the rules are obvious.

### Notes

`twitter.com##:xpath(//span[(text()='Promoted' or text()='Gesponsert' or text()='Реклама' or text()='Promocionado' or text()='Sponsorisé' or text()='Uitgelicht' or text()='推荐' or text()='プロモーション')]/../../../../..)`
`twitter.com##[data-testid="trend"]:has-text(/推荐|Promoted|Gesponsert|Реклама|Promocionado|Sponsorisé|Uitgelicht|プロモーション/):xpath(..)`

Why don't you update the first rule to
`twitter.com##span:has-text(/推荐|Promoted|Gesponsert|Реклама|Promocionado|Sponsorisé|Uitgelicht|プロモーション/):upward(5)`?

**Comment by dimisa-RUAdList** [comment]
It looks like this rule hides the unnecessary on the home page if the user is not logged in: https://i.imgur.com/UusfVoM.jpg

**Comment by krystian3w** [comment]
@mapx- filter break homepage in Russia.

**Comment by mapx-** [comment]
@dimisa-RUAdList 
if I remove `Реклама` from the filter bellow is it ok ? 

twitter.com##:xpath(//span[(text()='Promoted' or text()='Gesponsert' or text()='Реклама' or text()='Promocionado' or text()='Sponsorisé' or text()='Uitgelicht' or text()='推荐' or text()='プロモーション')]/../../../../..)

**Comment by dimisa-RUAdList** [comment]
Yes, in this case the home page does not break. True, I do not know what will happen with the promo posts.

**Comment by mapx-** [comment]
I don't know how to test it, I changed the language in FF, choose a russian ip..

**Comment by krystian3w** [comment]
Just install the Russian language in the settings, move on top in pop-up, restart Firefox, refresh Twitter page without cache (`Ctrl+F5`).

Editing only the `intl.locale.requested` entry seems to no work without a language pack...

**Comment by krystian3w** [comment]
Change lang on account is here:

`https://twitter.com/settings/language`

**Comment by llacb47** [comment]
It's easy, just do this @mapx- `http://twitter.com/home?lang=ru`

**Comment by Yuki2718** [comment]
Is it Russian specific?

**Comment by krystian3w** [comment]
Uses `Реклама` / "`Reklama`".

---

> Is it Russian specific?

Yes, these laout use same word for ads and self-promotion.

---

PS. Poland use `/^Promowane$/`.

**Comment by krystian3w** [comment]
EL now use:
```
twitter.com##div[data-testid="placementTracking"]:has(svg + div[dir="auto"] > span:has-text(/Promoted|Gesponsert|Promocionado|Sponsorisé|Sponsorizzato|Promowane|Promovido|Реклама|Uitgelicht|Sponsorlu|Mainostettu|推廣|推广|推薦|推荐/))
                                                   twitter.com##div[data-testid="UserCell"]:has-text(/Promoted|Gesponsert|Promocionado|Sponsorisé|Sponsorizzato|Promowane|Promovido|Реклама|Uitgelicht|Sponsorlu|Mainostettu|推廣|推广/)
```

**Comment by Yuki2718** [comment]
An anonymous user reported a leftover of promoted tweet which I could reproduce (but not always):

![twitter](https://user-images.githubusercontent.com/58900598/90124285-16c68600-dd9b-11ea-8dd3-10766f27b70a.png)

I'm aware of [this](https://github.com/uBlockOrigin/uAssets/commit/8fd12b060148cfde8e53e70012733b089abf65bc#commitcomment-39037147) comment but in this case I guess span:has-text is really necessary as no useful attributes found in parent or grand-parent - as you see aria-label will be language-dependent. `upward(3)` is minimum-working, `upward(6)` maximum. So it's possible just to add "プロモツイート" to the current xpath rule as it's equivalent to `upward(5)`. Making "プロモーション" to "プロモ" should also work but IDK if it's safe against FP as I don't use Twitter. If making "Promoted" to "Pro" is safe in English, it'll also be safe. Probably better to check in each language, so far I don't see English version though.
