### ISSUE TITLE
alphapolis.co.jp

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7325]
### URL(s) where the issue occurs

`https://www.alphapolis.co.jp/novel/515275725/825286264/episode/2011447`

### Describe the issue

Annoyance: context menu, copy/select, and screen capture (PrintScreen) disabled; screen is hidden if dev tools are turned on.

### Screenshot(s)

![alphapolis1](https://user-images.githubusercontent.com/58900598/81312365-86a0e280-90c1-11ea-9239-791fd5230496.png)

### Versions

- Browser/version: Brave 1.8.90
- uBlock Origin version: 1.26.0

### Settings

- Default + uBlock Annoyances

### Notes

Dev tools: `alphapolis.co.jp###TopLayer`
Context menu `alphapolis.co.jp##+js(aopw, document.oncontextmenu)`
All the rest:
`alphapolis.co.jp##+js(aopw, document.onselectstart)`
`alphapolis.co.jp##+js(aeld, /^(?:DOMContentLoaded|copy|load)$/)`

My concern is this aeld may be too broad.

**Comment by llacb47** [comment]
Try `||alphapolis.co.jp/js/content-viewer.js$script`

I reloaded the page once and got blocked from the site...

**Comment by Yuki2718** [comment]
Nice, it worked and it appears the script is only for annoyances. Maybe they're doing geofence?

**Comment by llacb47** [comment]
Content of the script if anyone else is blocked: `https://pastebin.com/m4ent6qE`

**Comment by hirorpt** [comment]
The current solution prevents manga in the website from displaying.

URL: `https://www.alphapolis.co.jp/manga/official/138000030/46`
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/82331005/114357036-37eea900-9bac-11eb-8abc-faba73c3900a.png)
</details>

> Try `||alphapolis.co.jp/js/content-viewer.js$script`
This filter may be a good alternative.

**Comment by hirorpt** [comment]
Copy disabled again.

**Comment by uBlock-user** [comment]
@hirorpt you need to force update uBlock Annoyances list.

**Comment by hirorpt** [comment]
Of course, I created new profile with latest uBO, and clicked purge all cashes and update now before reporting.
You can select and drag texts on the page, but Ctrl + C is disabled.

**Comment by uBlock-user** [comment]
>  but Ctrl + C is disabled.

Works fine, tested at `https://www.alphapolis.co.jp/`

**Comment by hirorpt** [comment]
I tested at URL suggested by the issue author. `https://www.alphapolis.co.jp/novel/515275725/825286264/episode/2011447`
In addtion to disabled copy, I don't know how to reproduce, but the screen also sometimes hidden just like the screenshot posted by him.
