### ISSUE TITLE
mmo-champion.com

### ISSUE THREAD

**Issue by milotic** [uBlockOrigin/uAssets#7327]
### URL(s) where the issue occurs

`https://www.mmo-champion.com/content/`

### Describe the issue

Now open video ads in every page

### Screenshot(s)

![Captura](https://user-images.githubusercontent.com/1099848/81361308-40388d00-909b-11ea-9b1e-96d383100c8a.PNG)

### Versions

- Browser/version: firefox 77
- uBlock Origin version: 1.26.2

### Settings

- [List here all the changes you made to uBO's default settings] none

### Notes

manually blocking the video not working other appear refreshing the page

**Comment by llacb47** [comment]
Try `||cursecdn.com^$script,domain=mmo-champion.com`

**Comment by milotic** [comment]
i try but still happening

**Comment by milotic** [comment]
and when try manual block a video the rule is like this:

||cdn5.anyclip.com/AXHwQl7th79lkwsaMkJc/1588873963143_480x270_video.mp4?wid=0011r00002Sgfyv_1574

but the same video can get diferent ids everytime doing f5

**Comment by llacb47** [comment]
So sorry, I was looking at the wrong thing.

Try `||anyclip.com^$script,domain=mmo-champion.com`

**Comment by milotic** [comment]
thanks finally works and video ads are gone now

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by krystian3w** [comment]
@yourduskquibbles  if EasyList ban at all anyclip revert these: https://github.com/yourduskquibbles/webannoyances/issues/193

https://github.com/yourduskquibbles/webannoyances/commit/2df5646c2eaafae7ce77937cbae21151cefe38b4

```
gameplay.tip
thewindowsclub.com
```
