### ISSUE TITLE
speedtest.net/global-index

### ISSUE THREAD

**Issue by kasper93** [uBlockOrigin/uAssets#733]
### URL(s) where the issue occurs

`http://www.speedtest.net/global-index`

### Describe the issue

Adblocker detected because of this rule `|http://$script,domain=speedtest.net` and since all scripts are blocked the page is broken, graphs doesn't show when you click on the country and so on.

### Notes

Could probably be fixed by, but won't fix other pages where  scripts are also blocked.
`@@||www.speedtest.net/global-index/public/`

Dunno why easylist have blocked all scripts on speedtest.net.

Funny thing is that even they say `Speedtest Global Index will not show ads.` yet we cripple the site by blocking scripts.

**Comment by okiehsch** [comment]
How about
`@@||speedtest.net/*/*bundle$script,first-party`?
That also allows necessary scripts at for example
`http://www.speedtest.net/insights/blog/norway-fastest-mobile-2017`.

**Comment by kasper93** [comment]
Fine with me. I don't see any obvious breakage on their sites anymore.

**Comment by okiehsch** [comment]
Well, I do at `http://www.speedtest.net/reports/united-kingdom`, you have to scroll down to 
"City Leaders", the map won't show.

**Comment by uBlock-user** [comment]
BadFilter from Easylist - `|http://$xmlhttprequest,domain=speedtest.net`
