### ISSUE TITLE
mp4upload.com

### ISSUE THREAD

**Issue by Jorge9811** [uBlockOrigin/uAssets#7330]
### URL(s) where the issue occurs

`https://mp4upload.com`

### Describe the issue

This page hosts videos. They recently *(last 24 or 48 hours)* changed their player and introduced some ad-blocker killing code.

### Screenshot(s)

This is what happens when you try to play a video hosted there with uBlock Origin enabled
![firefox-2020-05-08_19-56-37](https://user-images.githubusercontent.com/54429803/81455682-3c257180-9166-11ea-8861-cd18fc84ca0e.png)

### Versions

- Browser/version: Mozilla Firefox v76.0.1 x64
- uBlock Origin version: 1.26.2

### Settings

https://i.imgur.com/9n9q0WA.png

Because I'm using Nano Defender, I also have userResourcesLocation adjusted accordingly.

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/8d8beb3e6233797580a64abf7f59d37137c51862
https://github.com/uBlockOrigin/uAssets/commit/a1236773f7f23f66f6d1c540d18cfa6c44070cbb

Did you force update uBlock Filters list ?

**Comment by Jorge9811** [comment]
> 
> 
> [8d8beb3](https://github.com/uBlockOrigin/uAssets/commit/8d8beb3e6233797580a64abf7f59d37137c51862)
> [a123677](https://github.com/uBlockOrigin/uAssets/commit/a1236773f7f23f66f6d1c540d18cfa6c44070cbb)
> 
> Did you force update uBlock Filters list ?

Yes, I had the purge my cache and update to try out an unofficial filterlist that attempts to address the issue, but I still have it happen on my end with that filterlist or without it.

**Comment by uBlock-user** [comment]
Disable Nano Defender and all other extensions, test again.

**Comment by Jorge9811** [comment]
I was just able to fix it. Turns out I had the domain apus.tech blocked
Unblocking it solved the problem on my end.

**Comment by llacb47** [comment]
Tested and working fine with Nano Adblocker + Defender and updated lists.

**Comment by uBlock-user** [comment]
There's a better solution where we don't have to create an exception for the ad-server, but currently the AA is detecting the style of the iframe which is set inline by uBO in Firefox, once https://github.com/gorhill/uBlock/issues/2848 is addressed, I will remove the exception filter.

**Comment by ghajini** [comment]
`https://www.mp4upload.com/embed-mmuhf0odb914.html`

Issue=

Player controls like play /pause/ fast forward/fast backward/download etc are hidden are not available

Ublock origin 1.27.11rc5
firefox A.

Ublock enabled= 

https://user-images.githubusercontent.com/20338483/85648551-a23a6980-b6be-11ea-8db3-710d88833ac7.jpg

Ublock disabled =

https://user-images.githubusercontent.com/20338483/85648599-b8482a00-b6be-11ea-8b9d-c955da1209b0.jpg
