### ISSUE TITLE
[Full HD] [DPI] youtube.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#7332]
https://github.com/uBlockOrigin/uAssets/issues/5623

`https://www.youtube.com/watch?v=6p-lDYPR2P8`

Hidden date of publication with long phrase `views`.

![obraz](https://user-images.githubusercontent.com/35370833/81475252-5b2a0f00-920b-11ea-959c-12601e7044f6.png) |
---- |
wyświetleń 🇵🇱 |

![obraz](https://user-images.githubusercontent.com/35370833/81475314-a0e6d780-920b-11ea-88a0-9668568dc7ae.png) |
--- |
visualizaciones 🇪🇸 |

![obraz](https://user-images.githubusercontent.com/35370833/81475342-c5db4a80-920b-11ea-94ac-2d1bb52a4663.png) |
--- |
visualizações 🇵🇹 |

![obraz](https://user-images.githubusercontent.com/35370833/81475393-2ff3ef80-920c-11ea-8e49-5165b68784b7.png) |
--- |
Russian without `просмотров` (no visible) 🇷🇺 |

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/81475929-5e26fe80-920f-11ea-8886-4014e3d36ef4.png)

**Comment by krystian3w** [comment]
Need Full HD + DPI 120 / 125%.

**Comment by mapx-** [comment]
@krystian3w 
1. if you are not able to provide all the necessary info, why this hysterical / childish / disrespectful use of thumbs down ?
2. Can your issue be reproduce turning uBO OFF ? ( see https://github.com/uBlockOrigin/uAssets/issues/7340 )

**Comment by krystian3w** [comment]
so revert #5623 also hidden date after disable.
