### ISSUE TITLE
tii.ai

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#7335]
`https://tii.ai/y1ld63jy`

```
tii.ai##+js(aopr, app_vars.force_disable_adblock)
```

https://github.com/AdguardTeam/AdguardFilters/issues/55176

![obraz](https://user-images.githubusercontent.com/35370833/81478726-6424db80-921f-11ea-89cd-eab1b052732f.png) |
--- |

**Comment by krystian3w** [comment]
maybe race condition:

https://github.com/uBlockOrigin/uAssets/issues/5439#issuecomment-589928791

> `tii.ai` was fixed

**Comment by ghajini** [comment]
`tii.ai/UHKnxnMO`
Popup ads after captcha verification in next page
