### ISSUE TITLE
aixFOAM.*

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#7338]
https://github.com/AdguardTeam/AdguardFilters/issues/55182

I no see `GDPR` directly in pop-up:

```
aixfoam.*###cc-notification
aixfoam.*##.content-blurred:style(filter: none !important;)
```

**Comment by llacb47** [comment]
What? That is a GDPR cookie consent popup...

**Comment by uBlock-user** [comment]
@krystian3w They have a popup with variable for cookies settings, an accept button and a data-protection readme, removed.
