### ISSUE TITLE
NSFW yourporn.sexy popups

### ISSUE THREAD

**Issue by mapx-** [uBlockOrigin/uAssets#734]
go to `https://yourporn.sexy/`

click on page ==> popups

working filter:
`yourporn.sexy##script:inject(window.open-defuser.js)`
or
`yourporn.sexy##script:inject(abort-current-inline-script.js, setTimeout)`

**Comment by okiehsch** [comment]
The site uses [Admaven](https://blog.malwarebytes.com/cybercrime/2017/05/roughted-the-anti-ad-blocker-malvertiser/) so, to be consistent, I will use
`yourporn.sexy##script:inject(abort-on-property-write.js, Fingerprint2)`

**Comment by in4u** [comment]
There's a popup on playing videos. Also, an ad banner above videos.
