### ISSUE TITLE
log.quora.com blocked via Google search

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#7341]
Google `site:log.quora.com` and click on one of the results.

My suggestion:
`||log.quora.com^$badfilter`
`||log.quora.com^$domain=~log.quora.com`
`||log.quora.com/ajax/`

**Comment by llacb47** [comment]
It just redirects to the main site. I don't think anyone is sending links to `log.quora.com`, so I don't see the need for this.

**Comment by IsraeliUser** [comment]
I get links to `log.quora.com` from Google by doing a simple search (typing _quora_ and some phrase).
The site specific search is just an example how to reproduce the issue.

**Comment by ryanbr** [comment]
why `site:log.quora.com` and not `site:quora.com` ?

**Comment by kulfoon** [comment]
> IsraeliUser: I get links to `log.quora.com` from Google by doing a simple search (typing quora and some phrase).

I agree, typing "quora mathira" results in google showing a link `https://log.quora.com/topic/Mathira` at 2nd place in it's search results.

-------------------------------------------------------------------------------------------------------------
> ryanbr: why `site:log.quora.com` and not `site:quora.com` ?

The answer is already here:

> https://github.com/uBlockOrigin/uAssets/issues/7341#issuecomment-626245843: IsraeliUser:  The site specific search is just an example how to reproduce the issue.
-------------------------------------------------------------------------------------------------------------

(regardless of whether it'll be decided to fix the issue or not):

> IsraeliUser: My suggestion:
> `||log.quora.com/ajax/`

This is better:
`||quora.com/ajax/`
Or if it's not safe to block all ajax calls, then one of these:
`||quora.com/ajax/batched_log_POST`
`||quora.com/ajax/batched_log_`
`||quora.com/ajax/batched_log`
`||quora.com/ajax/*_log_`
`||quora.com/ajax/*_log`
`||quora.com/ajax/*log`
> IsraeliUser: I get links to `log.quora.com` from Google by doing a simple search (typing quora and some phrase).

I agree, typing "quora mathira" results in google showing a link `https://log.quora.com/topic/Mathira` at 2nd place in it's search results.

-------------------------------------------------------------------------------------------------------------
> ryanbr: why `site:log.quora.com` and not `site:quora.com` ?

The answer is already here:

> https://github.com/uBlockOrigin/uAssets/issues/7341#issuecomment-626245843: IsraeliUser:  The site specific search is just an example how to reproduce the issue.
-------------------------------------------------------------------------------------------------------------

(regardless of whether it'll be decided to fix the issue or not):

> IsraeliUser: My suggestion:
> `||log.quora.com/ajax/`

This is better:
`||quora.com/ajax/`
Or if it's not safe to block all ajax calls, then one of these:
`||quora.com/ajax/batched_log_POST`
`||quora.com/ajax/batched_log_`
`||quora.com/ajax/batched_log`
`||quora.com/ajax/*_log_`
`||quora.com/ajax/*_log`
`||quora.com/ajax/*log`

**Comment by ryanbr** [comment]
So if someone google searches a specific filter item, "See your filter is broken". This could be applied to any Easylist filter.

**Comment by kulfoon** [comment]
While that is technically possible, the actual case was that he actually didn't find broken google search link by specific filter item, he provided the specific search only as a better example to reproduce the issue: "an example how to reproduce the issue." Actually he found broken google search link "by doing a simple search (typing quora and some phrase)." So perhaps the question is whether to:
- fix such issues regarding to all possible theoretical/technical cases
- fix such issues regarding only to reported actual cases
- not fix such issues at all, and instead tell an user to add repair filters to his My-Filter pane, but on the other hand one might say that if something is broken by the list, then it should be fixed in the list

That's an interesting question.

**Comment by IsraeliUser** [comment]
@mapx- 
Please reconsider it.
As @kulfoon wrote: it's a real case, not a theoretical case!
> I agree, typing "quora mathira" results in google showing a link https://log.quora.com/topic/Mathira at 2nd place in it's search results.

@okiehsch  @uBlock-user 
What do you think?

**Comment by uBlock-user** [comment]
`log.quora.com` shouldn't be appearing in the google search results in the first place. It's a domain for POST requests only and not GET, so basically internal use for Quora itself, its appearance is a screw up in the google crawler bot setting by Quora and the crawler crawled a page result which it wasn't meant to, but in the end it does't mean we have to facilliate a mistake made by the Quora team.
