### ISSUE TITLE
dood.watch [NSFW]

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7343]
### URL(s) where the issue occurs

`https://dood.watch/e/f23ulfhsu7jrc1bhpjqj2scfmztu3ck`

### Describe the issue

1. A popup window on playing the video
2. An annoying message on upper-right, not sure if it is an annoyance or ad

### Screenshot(s)

<details>

![dood](https://user-images.githubusercontent.com/58900598/81490377-a4866700-92bc-11ea-9502-b4a5b674ef39.png)
</details>

### Versions

- Browser/version: Brave 1.8.95
- uBlock Origin version: 1.26.0

### Settings

- Default + Annoyances

### Notes

Popup: `dood.watch##+js(acis, DoodPop)`
Message: `||zi8ivy4b0c7l.com^` works on my end, not sure whether this random-looking name is stable.

**Comment by okiehsch** [comment]
I get a popup triggered by the inline-script.
Ads triggered by `zi8ivy4b0c7l.com`
Disabled right click functionality triggered by the inline-script.

**Comment by okiehsch** [comment]
Shortcuts are also disabled by the inline-script.

**Comment by Yuki2718** [comment]
> 
> 
> Shortcuts are also disabled by the inline-script.

Yeah, I forgot to report that. Thx for fixing it too.

**Comment by ghajini** [comment]
Antiadblock popups
Domain changed
`https://doodstream.com/d/6tdbmgw9lao4
`> `https://dood.to/d/6tdbmgw9lao4`

Screenshot=

https://user-images.githubusercontent.com/20338483/82419621-4e73a980-9a9c-11ea-9d03-380cf543c2f3.png

**Comment by ghajini** [comment]
dood.to and dood.watch ,same but filters seems to broke. ....

`https://dood.watch/d/9yhzp0mztpla`

Page broken, download now not working

**Comment by mapx-** [comment]
easylist breakage
`*$stylesheet,3p,domain=dood.watch,badfilter`

@ryanbr

**Comment by ryanbr** [comment]
Need more info, like what the whitelist is needed.

**Comment by ghajini** [comment]
> { `doodstream.com` >`dood.to` } and `dood.watch`  ,slightly different but filters seems to broke `dood.watch`. ....
> 
> `https://dood.watch/d/9yhzp0mztpla`
> 
> **Page broken, download now** not working
> 
> https://user-images.githubusercontent.com/20338483/82435412-e62fc280-9ab1-11ea-9de9-158458b749dc.jpg



> Need more info, like what the whitelist is needed.

**Page broken, download now** not working

Screenshot=

https://user-images.githubusercontent.com/20338483/82435412-e62fc280-9ab1-11ea-9de9-158458b749dc.jpg

**Comment by mapx-** [comment]
all css in the pic are needed
![image](https://user-images.githubusercontent.com/10303732/82446709-6997e680-9aa7-11ea-93cf-3b0d9a530859.png)

**Comment by ghajini** [comment]
There is so much whitelists from easylist, not much required for ublock origin?

**Comment by mapx-** [comment]
I don't see anything unnecessarily whitelisted

**Comment by huyszn** [comment]
Other domains like `ds2play.com` (`ds2play.com/d/6tdbmgw9lao4`) and `doods.pro` (`doods.pro/d/6tdbmgw9lao4`) still have debugger traps so more domains should be added to the
`dood.*##+js(nostif, debugger)` filter.

**Comment by mapx-** [comment]
@ghajini feel free to fix the breakages.

**Comment by mapx-** [comment]
I tested the first link in edge, firefox, chrome => no issue on my end, the video running fine after an initial delay
`https://ds2play.com/d/qhse9qx13xl2`

LE: tested the second one too, still no issue (no delay in this case)

**Comment by D4niloMR** [comment]
@ghajini  this works on your side without breakages? `doods.*,ds2play.com##+js(set, console.clear, undefined)`

**Comment by huyszn** [comment]
New domain: `d0o0d.com`

**Comment by dimisa-RUAdList** [comment]
New mirror: `d000d.com`
Example: `https://d000d.com/d/9tkk8j8njx8n`

**Comment by dimisa-RUAdList** [comment]
New mirror: `dooodster.com`
Example: `https://dooodster.com/d/zcu7zlozegw0`
