### ISSUE TITLE
wikidata.org whitelist

### ISSUE THREAD

**Issue by tbertels** [uBlockOrigin/uAssets#735]
### URL(s) where the issue occurs

`wikidata.org`

### Describe the issue

Wikimedia website: no ads, so should be whitelisted.

### Versions

- Browser/version: Firefox 52.4.0 ESR
- uBlock Origin version: 1.14.4

**Comment by gorhill** [comment]
What is the issue exactly?

uBO does not "whitelist" sites, it's for you to decide.

**Comment by tbertels** [comment]
Indeed, my bad.
