### ISSUE TITLE
anti adb yahoo mail ?

### ISSUE THREAD

**Issue by nojoegopotato** [uBlockOrigin/uAssets#7352]
### URL(s) where the issue occurs

`https://mail.yahoo.com/d/folders/1`

### Describe the issue

login to mail.yahoo.com
unethical request to whitelist yahoo rectangle appears
open ubo picker
only random garbage shows that does not allow creation of a filter that works more often than once

Maybe this is a filter issue. idk.  I started it as an ubo issue.

https://mail.yahoo.com/d/folders/1

### Screenshot(s)

![unethical whitelist thread from yahoo webmail](https://user-images.githubusercontent.com/65205196/81630529-bcdcab80-93ba-11ea-9f2f-ea7a8c0dfdb4.png)

ubo picker providers random, garbage identifiers that work exactly once

### Versions

- Browser/version: 73.0.1 until there is an update to ghack user.js 
- uBlock Origin version: 1.26.2

### Settings

- adding my own filters from picker

### Notes

new daily profile
import my ubo filters

evil rectangle probably doesn't show without adblock but I'm not disabling it to find out

(it's evil to suggest others behave in a way that harms themselves)

**Comment by krystian3w** [comment]
Race condition or in uBO 1.26.2 no exist embeded fix (may no possible embed new file)?

https://github.com/uBlockOrigin/uAssets/blob/2d91881eb76ac9822a6c405db912c83a7a79bf86/filters/filters-2020.txt#L829-L830

try pruge "uBlock Filters" list and **force** update.
