### ISSUE TITLE
ohmybrush.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#7355]
### URL(s) where the issue occurs

`https://ohmybrush.com/en/`

### Describe the issue

Anti-Adblock

### Screenshot(s)

![1](https://user-images.githubusercontent.com/43844449/81662713-41bcd900-943e-11ea-93e6-abecd8b5ca58.gif)

### Versions

- Browser/version: Firefox 75.0.1 / Opera 68
- uBlock Origin version: 1.26.2 / 1.26.0

### Settings

Default

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ba55faa48031109f07887f97fee104135544a791
