### ISSUE TITLE
thatav.net [NSFW]

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7357]
### URL(s) where the issue occurs

<details>

`https://thatav.net/`

`https://thatav.net/video/41033/tpro-001-%E4%BA%BA%E6%B0%97av%E5%A5%B3%E5%84%AA%E6%9C%89%E6%9D%91%E5%8D%83%E4%BD%B3-%E3%82%A2%E3%83%8B%E3%83%A1%E3%82%B3%E3%82%B9%E3%83%97%E3%83%AC-%E6%9C%AC%E8%83%BD%E5%89%A5%E3%81%8D%E5%87%BA%E3%81%97%E3%83%87%E3%82%A3%E3%83%BC%E3%83%97%E3%82%AD%E3%82%B9%E4%B8%AD%E5%87%BA%E3%81%97%E6%80%A7%E4%BA%A4`

(embedded video)
`https://digjav.com/v/1lo65225lv5`
</details>

### Describe the issue

Popunder when:
1. you choose any video on the HP.
2. you play the video.

### Screenshot(s)

![thatav](https://user-images.githubusercontent.com/58900598/81668357-87e65c80-947f-11ea-8083-dadbf4894020.png)

### Versions

- Browser/version: Brave 1.8.95
- uBlock Origin version: 1.26.0

### Settings

- Default

### Notes

1: `thatav.net##+js(acis, document.querySelectorAll, adConfig)`
2: `||digjav.com^$inline-script`

**Comment by Yuki2718** [comment]
@mapx- It turned out the popup still appears. Test this URL: `https://thatav.net/video/21704/sama-919-%E5%AF%86%E5%AE%A4%E3%81%A7%E3%82%BB%E3%83%B3%E3%82%BA%E3%83%AA%E3%82%92%E8%A6%8B%E3%81%9B%E3%82%89%E3%82%8C%E7%B6%9A%E3%81%91%E3%81%9F%E7%B4%A0%E4%BA%BA%E5%A8%98%E3%81%AF%E4%B8%80%E4%BD%93%E3%81%A9%E3%81%86%E3%81%84%E3%81%86%E5%8F%8D%E5%BF%9C%E3%82%92%E3%81%99%E3%82%8B%E3%81%AE%E3%81%8B`

![thatav](https://user-images.githubusercontent.com/58900598/81841559-9dde4500-9585-11ea-8707-896f4f210fb6.png)

**Comment by mapx-** [comment]
test again

**Comment by Yuki2718** [comment]
> 
> 
> test again

Thx, that perfectly fixed the issue!
