### ISSUE TITLE
whispersinthecorridors.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#736]
Ad overlay on each and every visit to the homepage on https://www.whispersinthecorridors.com. The page waits for this overlay delaying page load. Multiple blank ads between article sections as well.

**SS:** 
https://i.imgur.com/Jvs8TC1.png (Ad overlay)
https://i.imgur.com/0e3PkAa.png (Blank ads, scroll down page to see)

**Error URL:** https://www.whispersinthecorridors.com/

_**Note:** Using uBO 1.14.8 on Chrome 61 with the default filters and settings._

**Comment by mapx-** [comment]
```
whispersinthecorridors.com###myModal
whispersinthecorridors.com##.modal-backdrop
||whispersinthecorridors.com/*.gif$image
whispersinthecorridors.com##.space
```

**Comment by gotitbro** [comment]
@mapx- Thanks for the filters but why block the image? The ads are already blocked by Easylist plus using the above filter would block legitimate images such as the site logo as well.

**Comment by mapx-** [comment]
right, use only 
`||whispersinthecorridors.com/uploads/media/inhouse.gif`

blocking this crap:
`https://www.whispersinthecorridors.com/uploads/media/inhouse.gif`

or remove totally that filter if you like that image

**Comment by gotitbro** [comment]
@mapx- Thanks for clarifying. The image is self promotion just so you know though I'll block it.
