### ISSUE TITLE
tanya-tanya.com / kiddnation.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#7362]
### URL(s) where the issue occurs

`https://tanya-tanya.com/`
`https://www.kiddnation.com/`

### Describe the issue

Anti-Adblock

### Screenshot(s)

![capture_011_12-05-2020_15-28-39](https://user-images.githubusercontent.com/43844449/81697449-52347a00-9465-11ea-987f-a8d2791d188f.gif)

![capture_013_12-05-2020_15-35-09](https://user-images.githubusercontent.com/43844449/81698373-2c5ba500-9466-11ea-8ec0-4f141904ff88.gif)

### Versions

- Browser/version: Firefox 76.0.1
- uBlock Origin version: 1.26.2

### Settings

Default

**Comment by kulfoon** [comment]
I've found one more.

**Comment by garry-ut99** [comment]
Big ad placeholder in critical place at the top due to `ghide` from "uBlock filters": 
![s](https://user-images.githubusercontent.com/72945564/217262801-b5ff2a91-f201-4fcf-a600-8ed2084ff614.png)

**Comment by mapx-** [comment]
@garry-ut99 

since you're hunting the ad placeholders, could you take another step? => disable thr ghide filter
`@@||example.com^$ghide,badfilter`  and test if that page still has an anti-adblocking mechanism

**Comment by garry-ut99** [comment]
ok I'll try
