### ISSUE TITLE
splitshire.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#7365]
### URL(s) where the issue occurs

`https://www.splitshire.com/`

### Describe the issue

Anti-Adblock

### Screenshot(s)

![capture_015_12-05-2020_15-39-34](https://user-images.githubusercontent.com/43844449/81698848-d804f500-9466-11ea-93f7-e84afe89c4b1.gif)

### Versions

- Browser/version: Firefox 76.0.1
- uBlock Origin version: 1.26.2

### Settings

Default

**Comment by garry-ut99** [comment]
Ad placeholders due to `ghide` in uBlock Filters: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218756577-8dfa2ae1-ea17-4f06-b45a-9d910bf64f3a.png)
No AA for me with `ghide` off, but still AA in the source code, so most likely: `splitshire.com##.ezoic-ad`.
