### ISSUE TITLE
theguardian.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7377]
### URL(s) where the issue occurs

`https://www.theguardian.com/international`
Some interaction is required.

### Describe the issue

Annoyance (maybe): a big yellow banner requesting donation.

### Screenshot(s)

![theguardian](https://user-images.githubusercontent.com/58900598/81710712-f5a97d00-94ad-11ea-8486-7ff45d9d665a.png)

### Versions

- Browser/version: Brave 1.8.95/Firefox 76.0.1
- uBlock Origin version: 1.26.0/1.26.2

### Settings

- Default + uBlock Annoyances

### Notes

It doesn't appear if I added `theguardian.com##^script:has-text(adBlockers)` on Firefox but I guess blocking this inline-script can cause false positive.

**Comment by Yuki2718** [comment]
Also `theguardian.com##+js(acis, InstallTrigger, ad-blocker)` in uBlock filters seems to be outdated.

**Comment by mapx-** [comment]
maybe it's enough
`theguardian.com##.site-message--banner`

**Comment by llacb47** [comment]
There is also unblocked ad with class `.dumathoin`. I don't know if my PC is crappy, or what, but my custom cosmetic filters are very slow to take effect on this site, with noticeable flickering.

**Comment by valynor** [comment]
A similar "it's your (cookie) choice" overlay has been added to all Guardian pages recently. 
I block all cookies with uMatrix and this overlay pops up every time you switch pages on The Guardian, VERY annoying.

**Comment by mapx-** [comment]
`theguardian.com##[id^="sp_message_container"]`

@ryanbr

**Comment by SeriousHoax** [comment]
@Yuki2718 Can something be done about it? Adguard Annoyance in Adguard extension can take care of it but uBO can't. Is it one of those where it doesn't work unless you accept cookies? 
`https://www.theguardian.com/commentisfree/2022/jul/10/long-childhood-humans-earths-most-complex-animal`
Browser: Firefox, Chrome
![image](https://user-images.githubusercontent.com/29574622/178447782-bfb20fd3-6892-42b8-af9d-d53a9c6d722a.png)

**Comment by SeriousHoax** [comment]
> `theguardian.com##[id^="sp_message_container"]`
> 
> @ryanbr

Wondering why it hasn't been added to the filter list yet! Can you or @Yuki2718 do something about it? 
![image](https://user-images.githubusercontent.com/29574622/178448317-51f6b35d-9ec9-46e2-a2d0-6f44349a8d8b.png)

**Comment by AdamWr** [comment]
As I recall, if cookie notice is not accepted then video player doesn't work - https://github.com/AdguardTeam/AdguardFilters/issues/112632

**Comment by Yuki2718** [comment]
What about `patrons.theguardian.com##.gu-banner-fix-to-bottom`?

**Comment by dportvine** [comment]
Cookies https://github.com/AdguardTeam/AdguardFilters/issues/220134

<details>

```yaml
uBlock Origin: 1.68.0
Firefox Mobile: 147
filterset (summary):
 network: 188576
 cosmetic: 129470
 scriptlet: 35210
 html: 3003
listset (total-discarded, last-updated):
 removed:
  UKR-0: null
 added:
  https://easylist-downloads.adblockplus.org/bitblock.txt: 24802-26, 4m
  ublock-experimental: 13-0, 50m Δ
  adguard-cookies: 36338-334, 4m
  ublock-cookies-adguard: 5129-72, 4m
  ublock-annoyances: 4632-41, 50m Δ
  RUS-0: 42120-268, 4m
  RUS-1: 1851-263, 4m
 default:
  user-filters: 0-0, never
  ublock-filters: 42551-126, 50m Δ
  ublock-badware: 10956-32, 50m Δ
  ublock-privacy: 3552-3, 50m Δ
  ublock-unbreak: 2774-4, 50m Δ
  ublock-quick-fixes: 412-35, 50m Δ
  adguard-mobile: 11735-10, 4m
  easylist: 84102-191, 50m Δ
  easyprivacy: 55001-132, 50m Δ
  urlhaus-1: 29555-6, 4m
  plowe-0: 3483-1059, 4m
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 webrtcIPAddressHidden: true
hiddenSettings:
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 471 ms (selfie)
 maxAssetCacheWait: 220 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 19
 network:
  theguardian.com: 14
  guardianapis.com: 1
  youtube-nocookie.com: 4
 extended:
  ##div[id^="dfp-ad-"]
  ##.top-banner-ad-container
  ##.ad-slot-container
  ##.js-ad-slot
  ##.ad-slot:not(.adsbox):not(.adsbygoogle)
  ##.ad-slot--top-above-nav
  ##.ad-slot--mpu-banner-ad
  ##.ad-slot--rendered
  ##.ad-slot--right
  ##.ad-slot--mostpop
  ##.ad-text
  ##.adSense
  ##.adBlock
  ##.adContent
  #@#.ad-slot
  #@#.ad_unit
  ##+js(json-prune, entries.[-].command.reelWatchEndpoint.adClient…
  ##+js(json-prune-fetch-response, reelWatchSequenceResponse.entri…
  ##+js(json-prune, playerResponse.adPlacements playerResponse.pla…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
```
</details>

**Comment by mapx-** [comment]
already fixed
