### ISSUE TITLE
www.roxtec.com rendering breaks with uBlock

### ISSUE THREAD

**Issue by wesinator** [uBlockOrigin/uAssets#7378]
### URL(s) where the issue occurs

`https://www.roxtec.com/`

### Describe the issue

Site rendering breaks with uBlock enabled

### Screenshot(s)

<img width="1568" alt="image" src="https://user-images.githubusercontent.com/5124946/81711266-7a11e680-9441-11ea-82f4-40b341437267.png">

### Versions

- Browser/version: Firefox 76.0.1 
- uBlock Origin version: 1.26.2
Reproduced on mac and Linux

### Notes

Renders correctly with just FF tracking protection

**Comment by mapx-** [comment]
does it render correctly only FF + uBO default settings (FF tracking OFF) ?
