### ISSUE TITLE
https://shorten.sh/cSNhUJ --------- Screen appears

### ISSUE THREAD

**Issue by sanGtH** [uBlockOrigin/uAssets#7379]
### Description
There is a nasty screen to install an addon appears on this page : 
`https://shorten.sh/cSNhUJ`

![image](https://user-images.githubusercontent.com/13797193/81720367-f0dbcd80-949b-11ea-96de-77d28bd597a3.png)

### A specific URL where the issue occurs
`https://shorten.sh/cSNhUJ`
### Expected behavior:
The screen shouldn't appear.
### Your environment

* uBlock Origin version: **1.26.0**
* Browser Name and version: Chrome v80+
* Operating System and version: Win7 64 bit

**Comment by sanGtH** [comment]
Even after updating the filter lists, i still find that screen

**Comment by mapx-** [comment]
try adding manually
```
||theweblocker.net^$3p
shorten.*###chromepop
```

**Comment by sanGtH** [comment]
Thanks dear @mapx- It works. Please close this issue.
