### ISSUE TITLE
made-by.org [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#7393]
### URL(s) where the issue occurs

`https://www.made-by.org/`

### Describe the issue

Anti-Adblock

### Screenshot(s)

![capture_044_13-05-2020_15-44-16](https://user-images.githubusercontent.com/43844449/81820270-ad7f6e80-9530-11ea-9f05-73dc1ea1c82a.gif)

### Versions

- Browser/version: Firefox 76.0.1
- uBlock Origin version: 1.26.2

### Settings

Default

**Comment by mapx-** [comment]
do you see in the logger

`made-by.org##+js(nostif, ads)`

**Comment by Yuki2718** [comment]
Not reproduced on Brave, `made-by.org##+js(nostif, ads)` seems to be working.

**Comment by uBlock-user** [comment]
Reproduable on Firefox, likely due to race condition.

**Comment by mapx-** [comment]
tested in FF too, no issue on my end

**Comment by Yuki2718** [comment]
Tested again, now reproduced on Firefox.
![made-by](https://user-images.githubusercontent.com/58900598/81824219-2a7e0880-9570-11ea-86f0-4a53200429c5.png)

**Comment by uBlock-user** [comment]
jerky race condition...happens and then it doesn't.
