### ISSUE TITLE
reference.medscape.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#7397]
### URL(s) where the issue occurs

`https://reference.medscape.com/viewarticle/929339`

### Describe the issue
Can't view comments after 1st time....
Go to above URL
click comments thumbnail
now cancel cross sign of comments
Again try to view comments, doesn't show comments

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser/version:firefox a.
- uBlock Origin version: 1.26.2

### Settings

- uBO's default settings

### Notes

Most likely caused by easyprivacy

**Comment by ghajini** [comment]
Doesn't work for me....such exception filter you added even not shown in logger

**Comment by mapx-** [comment]
I guess your list is still old. I tested in FF on android => all fine on my end

**Comment by ghajini** [comment]
Firefox is weired, I added as custom filter but it doesn't work that time. ...now it works
