### ISSUE TITLE
batmanstream.com

### ISSUE THREAD

**Issue by knzudgt** [uBlockOrigin/uAssets#74]
### URL(s) where the issue occurs

`http://www.batmanstream.com/`
`http://www.batmanstream.com/tennis-live-streaming-video-2016-12.html`

### Describe the issue

There is a banner attached at the bottom of the page that uBlockOrigin does not block by default.
The banner changes at every refresh of the page.

### Screenshot(s)

![screenshot from 2016-07-01 09 18 33](https://cloud.githubusercontent.com/assets/15718033/16515693/c936824c-3f73-11e6-82b9-b921ff767e5b.png)

### Versions

- Browser/version: Firefox 47.0
- uBlock Origin version: 1.7.6
- OS: Ubuntu 14.04 LTS

### Settings

- Anti-Adblock Killer | Reek‎
- My filters:
```
@@||abysstream.com/ads.js
@@||p.jwpcdn.com/6/8/jwplayer.flash.swf
```

### Notes

NoScript would block the banner but the website would not be browsable, because the drop-down menus of the second link for instance would not work.

I tried to attach the following custom filters with no results:

```
batmanstream.com##div[style="position:fixed;bottom:18px;left:319px; display:block !important; width:728px;height:90px;visibility: visible !important;"]
batmanstream.com##body > div:nth-child(7) > a:nth-child(1) > img:nth-child(2)
batmanstream.com##img[style="visibility: visible !important; display:block!important; width:728px;height:90px;"]
batmanstream.com##a[style="visibility: visible !important; display:block!important;]
```

**Comment by gorhill** [comment]
I am unable to repro with only uBO 1.7.6 installed, or uBO + Reek's.

**Comment by gorhill** [comment]
I can block it fine with 1.7.7b5 and the filter `batmanstream.com##a[href^="data:text/html;"]`. You mind using the dev build? It's on AMO: <https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta>.

**Comment by knzudgt** [comment]
Thanks @gorhill !!! With 1.7.7b5 and your filter the ad is blocked :+1:

**Comment by gorhill** [comment]
Can you submit the filter to [EasyList maintainers](https://forums.lanik.us/viewforum.php?f=62)? (it also works for ABP.)

**Comment by knzudgt** [comment]
Reported to the EasyList maintainers

**Comment by mapx-** [comment]
or add
@@||batmanstream.com^$generichide
@@||s3.amazonaws.com/inject_ads/advertisement.js
