### ISSUE TITLE
businessinsider.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#7401]
### URL(s) where the issue occurs

`https://www.businessinsider.de/international/comparing-genetic-similarity-between-humans-and-other-things-2016-5/?r=US&IR=T#even-bananas-surprisingly-still-share-about-60-of-the-same-dna-as-humans-8`

### Describe the issue

ads

### Screenshot(s)

<img width="1203" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/81875205-117d5380-9580-11ea-8cd3-82434aa10cac.PNG">

### Versions

- Browser/version: Firefox 76.0.1
- uBlock Origin version: v1.26.2

**Comment by llacb47** [comment]
```
businessinsider.de##+js(nostif, .call(null))
! placeholders in slideshow
businessinsider.de##.slideshow__mobile-ad
businessinsider.de##.slideshow__middle-ad-container
businessinsider.de##.slideshow__desktop-ad:style(max-height:20px)
```

**Comment by llacb47** [comment]
I can reproduce in chrome, you should add non-html filtering fix too. (the one above)

**Comment by okiehsch** [comment]
The chrome filter is part of the commit.
![image](https://user-images.githubusercontent.com/16838044/81890484-603de400-95a6-11ea-9694-78898c02c8b7.png)

**Comment by llacb47** [comment]
Oops, sorry, my bad.
