### ISSUE TITLE
mangahost.site

### ISSUE THREAD

**Issue by marcussacana** [uBlockOrigin/uAssets#7402]
### URL(s) where the issue occurs

https://mangahost.site/

### Describe the issue

Ad blocker detected

### Screenshot(s)

![image](https://user-images.githubusercontent.com/10576957/81882600-85603180-9569-11ea-9e13-36b590e44fad.png)

### Versions

- Browser/version: Edge Chromium 
- uBlock Origin version: Nano Adblocker 1.0.0.142

### Notes

this site disables the detector occasionally, so stay tuned if you don't see the problem.

**Comment by llacb47** [comment]
Please test: `mangahost.site##+js(acis, window.onload)`

**Comment by marcussacana** [comment]
Worked

**Comment by marcussacana** [comment]
Hey, looks like the update broken the disqus comment from the site

**Comment by marcussacana** [comment]
@okiehsch thanks for the fix, but this site is really a pain in the ass, now they changed the domain;
This is usually, they have many domains and change it Randomly
`mangahost2.com` is the current
Others domains:
```
mangahost.site
mangahosted.com
mangahost1.com
mangahost.net
br.mangahost.com
mangahost.com (disabled)
```
And more... as you can see, it's better do a wildcard to the domain, also, I already saw varions in the domain like `mangashost` and `mangahosted`

**Comment by jspenguin2017** [comment]
> this is one of the reasons that make me wanted wanted learn fix it

I have listed the resources you need to get started here: https://github.com/NanoAdblocker/NanoCore/issues/328#issuecomment-628689941

Have fun, also please share your solution when you find one.

**Comment by marcussacana** [comment]
I know, but nahh, the `##+js(acis, window.onload)`` still working, I just updated the domain...

**Comment by llacb47** [comment]
I'll make a PR with the domains.

**Comment by llacb47** [comment]
I tested `##+js(acis, window.onload)` and I don't think it's breaking comments, can you give me a page where that happens @marcussacana?

**Comment by llacb47** [comment]
https://github.com/uBlockOrigin/uAssets/pull/7430 Looks good?

**Comment by marcussacana** [comment]
Yeah, he just redirect, it's like they have many domains but only keep one working, than after a time, they just change to another one.
Also, I think you forgot to cover the `mangahost1.com` and `mangahosted.com` domains

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/9d824471b66906633c9a238c6ac1741b2c7ee9fa

**Comment by marcussacana** [comment]
looks like they updated the code and isn't working again...
i create a new issue or just comment here is enough?

PS: Looks like the snippet that detect the adblocker do a self-deletion after verify, then you will need use the view-source:

**Comment by llacb47** [comment]
![image](https://user-images.githubusercontent.com/16567977/85230027-5e441d80-b3bb-11ea-8fe3-6ac8d46a4da4.png)

🤔

**Comment by marcussacana** [comment]
They really think can do something against ad blockers?

**Comment by llacb47** [comment]
I don't get any anti-adblock.

**Comment by llacb47** [comment]
@lain566 the `@@||mangahost2.com^$ghide` was there for a reason.
![image](https://user-images.githubusercontent.com/16567977/85236934-797d5000-b3f0-11ea-8322-4b4025ad7333.png)

**Comment by lain566** [comment]
@llacb47 Do you have the Spanish / Portuguese regional filter enabled?

**Comment by llacb47** [comment]
> @llacb47 Do you have the Spanish / Portuguese regional filter enabled?

ah, ok, sorry

**Comment by marcussacana** [comment]
Fixed, thank you
