### ISSUE TITLE
nobab traps DDoS protection and causes the page stuck

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7403]
### URL(s) where the issue occurs

`http://reevown.com/`

### Describe the issue

Cloudflare's DDoS protection never stops its job if nobab is applied to the page.

### Steps to reproduce

1. Enable AdGuard Base or manually add `reevown.com##+js(nobab)` to My filters.
2. Visit the URL

### Screenshot(s)

![nobab](https://user-images.githubusercontent.com/58900598/81921734-08d75c80-9616-11ea-8a32-1a1997fddb34.png)
### Versions

- Browser/version: Firefox 76.0.1/Brave 1.8.95/Firefox Android 68.8.0
- uBlock Origin version: 1.26.2/1.26.0/1.26.2

### Settings

- Default + AdGuard Base

### Notes

Even without the rule/AG Base I was required to solve CAPTCHA, but anyway could proceed. AdGuard also has the issue.

**Comment by uBlock-user** [comment]
AdGuard Base is not one of the default lists, so the fix won't be applied in uAssets.

**Comment by Yuki2718** [comment]
Okay.
