### ISSUE TITLE
Many ads on several web pages

### ISSUE THREAD

**Issue by emiliou4756** [uBlockOrigin/uAssets#7406]
i listed them here but perhaps easylist germany is not correct? nothing happens...perhaps they can be fixed here. thank you

see: 

https://github.com/easylist/easylistgermany/issues/72

https://github.com/easylist/easylistgermany/issues/73

all from down from this comment: https://github.com/easylist/easylistgermany/issues/71#issuecomment-623628557

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by krystian3w** [comment]
If need scriplets, because easylist germany no support `#include` for uBO / AdGuard.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/223ca5e3ddd67bf47d5f5a04358f2dd24e9705d0

**Comment by mapx-** [comment]
- a lot of other self promo stuff
- test the pages again just to be sure we were not breaking some content

**Comment by emiliou4756** [comment]
>>test the pages again just to be sure we were not breaking some content
@mapx- 
Done! greetings and thx - if you think some are not ads just mention them i take look into
