### ISSUE TITLE
addictinggames.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#7409]
### URL(s) where the issue occurs

`https://www.addictinggames.com/action/the-worlds-hardest-game`

### Describe the issue

Anti adblock Annoyance
### Screenshot(s)

<img width="1193" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/82000525-e9adee80-9658-11ea-9ebd-59e2579704bf.PNG">

### Versions

- Browser/version: Firefox 76.0.1
- uBlock Origin version:  v1.26.2

**Comment by okiehsch** [comment]
The modal shows up after every reload, so it will be fixed in `uBO-filters`.
