### ISSUE TITLE
BlockAdblock

### ISSUE THREAD

**Issue by ialexryan** [uBlockOrigin/uAssets#741]
### URL(s) where the issue occurs

`https://www.demolandia.net/downloads.php?id=73498539`
`https://blockadblock.com/`

### Describe the issue

Site content is completely obscured by BlockAdblock overlay.

### Screenshot(s)

<img width="1079" alt="screen shot 2017-10-06 at 11 31 59 am" src="https://user-images.githubusercontent.com/2292782/31292902-0206a002-aa8a-11e7-9808-239fd110d9d1.png">

### Versions

- Browser/version: Chrome 61
- uBlock Origin version: 1.14.8

### Settings

None

### Notes

None

**Comment by SMed79** [comment]
add
`@@||demolandia.net^$generichide`
or
`demolandia.net##script:inject(bab-defuser.js)`

([62&t=38496](https://forums.lanik.us/viewtopic.php?f=62&t=38496))
