### ISSUE TITLE
facebook problem, trying to remove user from group, self closing

### ISSUE THREAD

**Issue by zlotowinfo** [uBlockOrigin/uAssets#7412]
### Description

[Description of the bug or feature]

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. click 3 dots in user
2. click on remove from group
3. & confirmation self closing fast

### Expected behavior:

see confirmation to delete user

### Actual behavior:

when i click delete user from group facebook, no see menu to confirm, its self closing

### Your environment

last
firefox
win7

**Comment by mapx-** [comment]
Did you test using ONLY the default settings in uBO ?

**Comment by mapx-** [comment]
zero feedback => closing

**Comment by ghajini** [comment]
@zlotowinfo , i just checked working with default settings....

**Comment by zlotowinfo** [comment]
really dont know what was that day
next day wasnt problems
posible some bug in facebook

first time i tried with & without ub, without ub worked fine
after few minutes was problem with & without ub
