### ISSUE TITLE
Proposal: Block Facebook-owned *.giphy.com when third-party

### ISSUE THREAD

**Issue by DeltaFlush** [uBlockOrigin/uAssets#7413]
### URL(s) where the issue occurs

`N/A`

### Describe the issue

At 5/15 [Facebook had bought GIPHY](https://twitter.com/Facebook/status/1261305542519083008). GIPHY is a popular GIF sharing site and used on many websites (such as Buzzfeed) and messaging clients (such as Twitter). Since it is now owned by Facebook, it is essentially a tracker that can be used to fingerprint you not (as of current) being blocked by uBlock Origin. GIPHY images are hosted at `media*.giphy.com`, where `*` represents a wildcard.

Proposal: Block `*.giphy.com` when third-party in privacy.txt.

### Screenshot(s)

N/A

### Versions

- Browser/version: Firefox/77.0b5 (64-bit)
- uBlock Origin version: 1.26.2

**Comment by llacb47** [comment]
Will break embeds across the web. Until there is evidence of facebook adding a new tracker to Giphy or abusing their ownership of it, I would not add this.
