### ISSUE TITLE
streamZ.cc anti-adblocker

### ISSUE THREAD

**Issue by bandi88** [uBlockOrigin/uAssets#7421]
### URL(s) where the issue occurs

`https://streamz.vg/wdu?nqyllopx5b0zwm5i2bplcv4j65x1rtueks05hp3n14mxqsgt35ef1jz8oxafr4ub`

### Describe the issue

This website does not allow to play the video contents if uBlock Origin is on.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/23141180/82124074-0b17f300-979d-11ea-8197-502574f0173e.png)

### Versions

- Browser/version: Mozilla Firefox 68.8.0esr 
- uBlock Origin version: 1.22.2

### Settings

Used with Nano Defender together.

**Comment by llacb47** [comment]
Link doesn't work, can you instead share which website links to this site `streamz.vg`?

**Comment by ghajini** [comment]
@llacb47 
Try videos from homepage `streamz.cc`

**Comment by uBlock-user** [comment]
back to `*$script,redirect-rule=noopjs,domain=streamz.vg`

**Comment by ghajini** [comment]
`https://streamz.ws/fYmJ4anFkenk0ZmM4djV5`

Issue= 
`Skip ads` button that can't be cancelled by clicking on it, stays there when watching the videos

Screenshot=

https://user-images.githubusercontent.com/20338483/92356083-210e4280-f103-11ea-9264-3f1db6650184.jpg

Also remove unnecessary exceptions.....

Firefox nightly mobile
Ublock origin 1.29.2

**Comment by ghajini** [comment]
`https://streamzz.to/fNDB1ZXhsYWtqOXR2VzZu`=

`https://streamz.vg/x7ea6747aa02be021f125523587363d5a`

Video replaced by antiadblock

![IMG_20201004_231050](https://user-images.githubusercontent.com/20338483/95022772-e57d7e80-0696-11eb-84ff-a25beac0f9fc.jpg)

Firefox A. ,ublock origin 1.30

**Comment by mapx-** [comment]
dead streams, provide the source

**Comment by llacb47** [comment]
@mapx- first link in @ghajini still works for me. 

The source is this website `www.skymovieshd.nl`. find a movie like `https://www.skymovieshd.nl/movie/Mulan-(2020)-English-720p-HEVC-HDRip-Full-Hollywood-Movie-x265-AAC-ESubs-[600MB].html` and click on the download links and one of them is `streamz.cc`.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/2bf1038a781561d21709d0c9ddb869595a0d3e1c
