### ISSUE TITLE
Lowes.com - JavaScript stops working in some places

### ISSUE THREAD

**Issue by veggiespam** [uBlockOrigin/uAssets#7428]
### URL(s) where the issue occurs

`https://www.lowes.com/`
`https://www.lowes.com/mylowes/preferences`
more on same site.

### Describe the issue

Some of the website is unusable with uB enable.  One example is clicking submit the zipcode on the main page to get your pricing information.  Another is going to the preferences page and trying to change your password.  With uB off, things work again.

1. Go to main `lowes.com` page
1. Click on "head and shoulders" icon and sign into your account
1. After authtentication, Click on "head and shoulders" icon and go to preferences
1. Click on "Manage Profile" (aka `https://www.lowes.com/mylowes/preferences`)
1. Click on any of the "Edit" buttons, password / address / etc, and observe that none are functional

### Screenshot(s)

Unnecessary.

### Versions

- Browser/version: FF Developer Edition / 77.0b7
- uBlock Origin version: 1.27.2

### Settings

- no changes from defaults

### Notes

This works with uB off and even without re-authenticating or clearing any cookies.

**Comment by llacb47** [comment]
Test `@@||adobedtm.com^*/mbox-contents-$script,domain=lowes.com`

**Comment by veggiespam** [comment]
Tested using `@@||adobedtm.com^*/mbox-contents-$script,domain=lowes.com` and most everything under profiles worked.  So far, the site is usable.  This might be the only needed fix.

Did not test second solution after you updated the comment.  

I will do a big online order in a few days to test that flow.

**Comment by llacb47** [comment]
The second one is for the `Deals, Inspiration and Trends` form at the bottom of the homepage.

**Comment by llacb47** [comment]
https://github.com/easylist/easylist/commit/c21fc5b14cf0625a0fe0b80644b103c4307a4528
