### ISSUE TITLE
diariosur.es (vocento.com subsidiary)

### ISSUE THREAD

**Issue by alvgalrus** [uBlockOrigin/uAssets#7429]
### URL(s) where the issue occurs

`https://www.diariosur.es/`

### Describe the issue

A JS library is heavily abusing system resources when it can't connect, showing the following message several times per second:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://insights-collector.newrelic.com/v1/accounts/1145621/events. (Reason: CORS request did not succeed).`
`Error: Network Error`

### Versions

- Browser/version: Firefox v76.0.1
- uBlock Origin version: v1.27.0

### Settings

- https://static.vocento.com/voonto2/latest/voonto.js*
- https://static.vocento.com/*

### Notes

I tried to reach them about the issue, but they ignored the matter after a week. That JS library seems to be intended to track events from the users and sending them to a New Relic panel.

**Comment by mapx-** [comment]
test this filter for breakages
`diariosur.es##+js(aopr, webpackJsonpVoonto)`

**Comment by NubN** [comment]
break site, with that filter (scroll down in main page)

I don't understand the issue of this post 😁

**Comment by mapx-** [comment]
maybe this one:
`@@||insights-collector.newrelic.com/v1/accounts/*/events$xhr,domain=diariosur.es`

**Comment by llacb47** [comment]
I can't reproduce on default settings, or with your filters.

**Comment by mapx-** [comment]
yeah, something similar to popads crap, firefox issue

**Comment by kulfoon** [comment]
llacb47 not all issues always happen on all browsers, perhaps it's something new for you, but not for me, I encountered many cases, in the past, of issues that can be reproduced in one browser but not in the other, in both directions Firefox <==> Opera. For example, today, I was wondering why uBlock-user added [this commit](https://github.com/uBlockOrigin/uAssets/commit/a3c310c8cfe665c590e7ddd1d9ec5a3a3a8dcbd3) for the anti-adblock, coz I couldn't reproduce on Firefox, so I tried on Opera and could reproduce.

**Comment by alvgalrus** [comment]
Thank you for the fix, sorry that I didn't keep an eye on the same day.

**Comment by Catastrophi** [comment]
The same behavior is observed with other vocento subsidiaries. For example:
https://www.elcorreo.com/
https://www.diariovasco.com/

Both reproducible on Firefox and Edge

**Comment by garry-ut99** [comment]
On `https://www.diariovasco.com/` a big ad placeholder caused by `ghide` in "uBlock filters": [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/214873976-f8054227-d1e2-4885-8a80-1953cd1edde6.png)
