### ISSUE TITLE
SendInBlue links blocked

### ISSUE THREAD

**Issue by Ragowoh** [uBlockOrigin/uAssets#7432]
### URL(s) where the issue occurs

`https://2wqt8.r.ag.d.sendibm3.com/mk/cl/f/mc_2Lw08Z2TgcpMhS5gyqFHgUooaeOSuxcYtaE3qY_bVxVHAj2nI9ue7ZPh9ihizixSHiraU8_PGOusw2ZaFDqOwj4LDLPU6BHg53s23nbZgM2NrsF1JSpZv6XQ35bEa9lgeXEDWBwZ-XHxEZqVmWqbhKPdnP9D_hwVI9aN_yZEB-JYIk7cwBzPDR18h`
`https://bhhibdi.r.bh.d.sendibt3.com/tr/cl/K-FPJCqssFSFMle6Pjw1HLyYsga1bGxbqrLieWFYJm3MloYIl0a90vpO8ud1IHXdocs2PHNiUVYnioAV8XwSlGd8jHpDnlT5PBsnQzMHAWtbq62ZQIThQOJj-a2xlWzJ-n_AUBIflebPYwkem6xs2rFLulO4sFXpr9C4mt-46FP7X3UY05LCZwL1y5iLQEQGIDpq1IDi_xIUDzAppdnQhn2YoBTDsUFkavXkDTWMPYkxLfUFbwU5xkS49_TqqI8rL6OjEjJwg_m_ArB7MT7FCymMwhJeN2x-E8r-ou7x4b4ku3mcmhngJKzworhPievjfh-hvXhX3EciPF7Qn14`

### Describe the issue

These URL were in an e-mail sent by a NGO via the emailing platform SendInBlue, supposed to be a redirection link to the website `https://et-si.alternatiba.eu/`
When I clicked on them, a blank page opened. It was the same for a lot of people, whereas a majority of people were correctly redirected. We discovered that all people who get the blank page used uBlock Origin. And when we switch off uBlock, the redirection works properly.

### Screenshot(s)

(well, there's nothing but white to be shown ^^)

### Versions

- Browser/version: Firefox 76.0
- uBlock Origin version: 1.27.0

### Settings

- None

**Comment by llacb47** [comment]
Works fine for me.

**Comment by funkycram** [comment]
I can confirm that Sendinblue URLs are blocked since a new version of Ublock (maybe one month ago). Example of URL (modified from original) : http://r.subdomain.domain.tdl/tr/cl/N6V-tXnxJUse97jgPIJQw8UpcYh3NjpwuELvNLbLHI5ePCU69-oG7toNLQAb3IHJEGEgMO23RlfAUZGdNCNcqbv1VNfezzJFsk_KgnZyCrr6JRwRJJYarAjw1qyR4AgWOhrabwcW-eJiEVn8CiKbHYxDRYZp6FYA6c4CKkNipBVSc8yfZYBkdyKb17Sz2w2UakhyRhEFYqW_VqBfJjTwQC3NOyaddbCPK9RCeGrmh8wA6RsVOiS7da7oGw6lFA

**Comment by mapx-** [comment]
I added a fix for the op issue.
Provide a real link to be able to test it or:
- open the uBO logger
- follow the steps to get the blank page or broken page
- select only the blocked items in the logger and post them here (as screenhots)

**Comment by funkycram** [comment]
Sorry, I didn't check the last release. You're right, it works now. Thanks.
