### ISSUE TITLE
delta.theta.casa

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#7434]
### URL(s) where the issue occurs

`https://delta.theta.casa/johnson`

### Describe the issue

BlockAdBlock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/82396140-2f810300-9a1b-11ea-8a81-d7fa765eed07.png)

**Comment by llacb47** [comment]
also needing `##+js(acis, Math, zfgloaded)`

**Comment by llacb47** [comment]
How long is this page? It's eating my memory. 🙁

**Comment by terrorist96** [comment]
Pretty long lol

**Comment by okiehsch** [comment]
Uses more than 1GB of Ram on my end. Impressive.

**Comment by llacb47** [comment]
This also works to test: `https://delta.theta.casa/testublockblah` 💯

**Comment by terrorist96** [comment]
FYI this caused a BSOD for me and my computer wouldn't back up due to memory issues (I have 16GB). I literally had to unseat and reseat my RAM to fix it. I've collapsed the link in the OP.

**Comment by okiehsch** [comment]
> I literally had to unseat and reseat my RAM 

That sounds more like a hardware issue no?

**Comment by ghajini** [comment]
Too much memory hogger

**Comment by dbayham** [comment]
![20220406_094727](https://user-images.githubusercontent.com/79125833/162032032-7cd5b6d6-4d85-4b1d-896d-255d5d62cdcc.jpg)
