### ISSUE TITLE
cadenaser.com - 404 infinite loop

### ISSUE THREAD

**Issue by NubN** [uBlockOrigin/uAssets#7439]
### URL(s) where the issue occurs

`https://play.cadenaser.com/?autoplay=true`

### Describe the issue

Go to: `https://play.cadenaser.com/?autoplay=true`
and skip the region ( press X )

getting infinite 404 errors ( very fast )

### Screenshot(s)

https://i.imgur.com/zIREBUH.png

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [v1.26.0]

### Settings

- https://i.imgur.com/cDu5dHi.png

### Notes

also this site has SSAI audio ads when the radio start, similar issue:

`https://forums.lanik.us/viewtopic.php?f=103&t=43784`

**Comment by NubN** [comment]
🤔.. the horrible spam in the ubo logs:

https://i.imgur.com/G2mW3gv.png

**Comment by uBlock-user** [comment]
@NubN Add `*$image,redirect-rule=1x1.gif,domain=cadenaser.com` refresh the page and report back if it still happens.

**Comment by mapx-** [comment]
it should work, just test it
`*$image,redirect-rule=1x1.gif,domain=play.cadenaser.com`

**Comment by mapx-** [comment]
@ryanbr 
`@@||omtrdc.net/b/ss/$image,domain=play.cadenaser.com`

**Comment by NubN** [comment]
the filters working

**Comment by NubN** [comment]
but you can reproduce that issue too?

**Comment by mapx-** [comment]
sure
