### ISSUE TITLE
ksta.de

### ISSUE THREAD

**Issue by UserNameA1** [uBlockOrigin/uAssets#744]
### URL(s) where the issue occurs 
`ksta.de`

### Describe the issue
The site ksta.de start to show some ads

### Screenshot(s)
![unbenannt](https://user-images.githubusercontent.com/29185143/31307016-0fb9b658-ab5c-11e7-8b95-2491be7e630e.JPG)

### Versions

- Browser/version: Firefox 56
- uBlock Origin version: 1.14.10

### Settings
No changes, default settings

### Notes
This issue could be fixed by adding `ksta.de##script:inject(uabinject-defuser.js)`

**Comment by KiLL4FuNK** [comment]
Anti-Adblock

`https://www.ksta.de/koeln/koelner-karneval-rosenmontagszug-findet-statt---aber-ohne-pferde-und-grossfiguren-32140952`
