### ISSUE TITLE
Greatist.com - Broken page (uBlock filters - Annoyances) [GDPR]

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uAssets#7440]
### Affected site:
`https://greatist.com/`

### Issue:
The page doesn't load properly (no images).
This is caused by a blocked GDPR popup, which needs to be accepted in non-Chromium browsers (tested with Pale Moon and SeaMonkey).

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* uBlock filters - Annoyances

### Problem rule:
`greatist.com###modal-host`

### Note:
Apparently, this other rule (also found in **uBlock filters - Annoyances**) is supposed to circumvent the issue, but doesn't seem to have the desired effect in non-Chromium browsers:
`greatist.com##body:style(overflow: auto !important;)`

### Possible fix:
Preferably, the problem rule(s) should be modified to work for all browsers.
Otherwise, these whitelistings will have to be added to **uBlock filters -Legacy**:
```
greatist.com#@##modal-host
greatist.com,medicalnewstoday.com#@$##modal-host { display: none !important; }
healthline.com#@$##modal-host { display: none !important; }
```
(The latter two whitelisting are for the other problem filter, listed below)

### Other problem filters:
* AdGuard Annoyances filter
```
greatist.com,medicalnewstoday.com#$##modal-host { display: none !important; }
healthline.com#$##modal-host { display: none !important; }
```
https://github.com/AdguardTeam/AdguardFilters/issues/55796/

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.9.3 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.20 (XUL)

**Comment by uBlock-user** [comment]
Can't reproduce with Firefox. Seems to be specific to Firefox XUL forks, if so, we can address this in legacy list.

**Comment by THEtomaso** [comment]
@mapx-:
It doesn't look like the Adguard team is going to fix this issue.
Could you please add the last two whitelisting rules (which I suggested in my previous post) to uBO's Legacy filter too?
I realize that this isn't standard procedure, since AdGuard Annoyances filter isn't enabled by default in uBO.
..but it's a very rare occurrence that these type of browser-specific fixes are needed at all, and the Legacy list is the only filter which can help us out with them!

**Comment by mapx-** [comment]
just push a PR for legacy list (you mixed above uBO and adguard filters) and I'll approve it

**Comment by THEtomaso** [comment]
> just push a PR
Never figured out how to do it. :)

**Comment by mapx-** [comment]
just put them here in uBO syntax

**Comment by THEtomaso** [comment]
`greatist.com,healthline.com,medicalnewstoday.com,#@##modal-host:style(display: none !important;)`

**Comment by llacb47** [comment]
@THEtomaso easiest way is to go to whichever file you want to edit and click the pencil icon, commit your changes, and then submit the PR.

**Comment by THEtomaso** [comment]
Thanks, I'll give it another shot the next time! :)
