### ISSUE TITLE
laptopmag.com

### ISSUE THREAD

**Issue by Shaunathanz** [uBlockOrigin/uAssets#7441]
### URL(s) where the issue occurs

`https://www.laptopmag.com/`

### Describe the issue

There is something happening behind the scenes on this website, and I believe it may be a bitcoin miner. My temps on my 16" Macbook Pro spike 10 degrees Celsius in 60 seconds time when visiting the page and not interacting or anything. The page can just be static images, no video or animated elements, and the site still spikes the CPU.

### Screenshot(s)

n/a

### Versions

- Browser/version: 76.0.1 (64-bit)
- uBlock Origin version: 1.27.0

### Settings

- n/a

### Notes

Visiting website adds 27 cookies to the browser. The act of viewing the website seems to activate the mining. Switching tabs leads to immediate temperature drops.

**Comment by llacb47** [comment]
If you add this filter to your filters does it still happen?

`||futurecdn.net^*/header.js$script,3p`

**Comment by okiehsch** [comment]
@llacb47 Can you reproduce?
I don't see any CPU spike on my end.

**Comment by llacb47** [comment]
Yeah, opening the homepage makes firefox go to 45% cpu utilization.

**Comment by llacb47** [comment]
I'm not an expert at understanding this, but look at this: `https://perfht.ml/3bRrsZA`
It looks like there is a `setInterval` statement running over and over or something...

**Comment by okiehsch** [comment]
> Can't reproduce in chrome.

OK, that's the reason I could not reproduce.
Does 
`laptopmag.com##^script:has-text(bordeaux)`
work for you?

**Comment by llacb47** [comment]
> > Can't reproduce in chrome.
> 
> OK, that's the reason I could not reproduce.
> Does
> `laptopmag.com##^script:has-text(bordeaux)`
> work for you?

That breaks `RECOMMENDED VIDEOS FOR YOU...` on `https://www.laptopmag.com/best-tablets`

**Comment by okiehsch** [comment]
Hm, I don't see any videos even without my filter.
Anyway it is a site issue. 
`https://vanilla.futurecdn.net/laptopmag/180679/media/js/header/impact-lazyload-format-responsive.js`
is causing it.
That is clearly not a miner.
Blocking it will fix the CPU spike.

**Comment by llacb47** [comment]
You have to wait 10 seconds for the videos to appear 🙂

**Comment by okiehsch** [comment]
OK, so blocking the mentioned script will also break the videos?

**Comment by llacb47** [comment]
> OK, so blocking the mentioned script will also break the videos?

That `lazyload` script is only loaded on the homepage, the CPU issue is on article pages too.

**Comment by okiehsch** [comment]
````
||futurecdn.net/*/media/js/header/n-format-format-responsive.js$script,3p
||futurecdn.net/*/media/js/header/impact-lazyload-format-responsive.js$script,3p
````
works on all sites I tried.

**Comment by okiehsch** [comment]
i still can't see any video even after 10 seconds, don't know why.
I was talking about the videos if you only block those scripts.

**Comment by llacb47** [comment]
> ```
> ||futurecdn.net/*/media/js/header/n-format-format-responsive.js$script,3p
> ||futurecdn.net/*/media/js/header/impact-lazyload-format-responsive.js$script,3p
> ```
> 
> works on all sites I tried.

Yup, that works. Videos still work.

**Comment by okiehsch** [comment]
@Shaunathanz 
You can add
````
||futurecdn.net/*/media/js/header/n-format-format-responsive.js$script,3p
||futurecdn.net/*/media/js/header/impact-lazyload-format-responsive.js$script,3p
````
to your filter list until the site fixes it's own issue.
