### ISSUE TITLE
adblocker blocker

### ISSUE THREAD

**Issue by OProfile** [uBlockOrigin/uAssets#7442]
### Versions

- Browser/version: [81.0.4044.138 (Official Build) (64-bit)]
- uBlock Origin version: [uBlock Origin 1.26.0]

### Settings

- [Default]

### Notes

[I've tried using AAK and enabling all filters]

**Comment by mapx-** [comment]
- aak is outdated crap, just remove it completely 
- keep only the default settings (backup your current setup, reset uBO to default, "purge all caches" and click "update now")
- don't use other blocking extensions
- Can you reproduce the issue only logging in the site ?

**Comment by OProfile** [comment]
All done, this issue is only reproduced if I'm logged in to the site. If I access the site in incognito, I can visit it with ublock origins.

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back again

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back again

**Comment by uBlock-user** [comment]
`memoryhackers.org##+js(nostif, [native code], 2000)`

**Comment by JobcenterTycoon** [comment]
perfect

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back
