### ISSUE TITLE
Liveticker "Corona" blocked :((

### ISSUE THREAD

**Issue by ucolaf** [uBlockOrigin/uAssets#7443]
### URL(s) where the issue occurs

`https://www.radiorur.de/`

### Describe the issue

Not Show Liveticker "Corona" 

### Screenshot(s)

not need

### Versions

- Firefox 76.0.1
- uBlock Origin version: [1.27.6]

### Settings

- all default

### Notes

disable ublock, i can see the liveticker

**Comment by mapx-** [comment]
@ryanbr
