### ISSUE TITLE
opennet.ru

### ISSUE THREAD

**Issue by theerhan** [uBlockOrigin/uAssets#7445]
PaleMoon 28.9.3
uBlock origin 1.16.4.20
Screenshot -  https://imgur.com/a/fwroLxF

**Comment by theerhan** [comment]
Confused the domain, here is the domain with advertising - https://www.opennet.ru/

**Comment by mapx-** [comment]
already fixed in `RU AdList`

**Comment by llacb47** [comment]
Any ads should be blocked in russian lists.
