### ISSUE TITLE
Cleaning Ublock filters from the miners' filters

### ISSUE THREAD

**Issue by TheFinalCut83** [uBlockOrigin/uAssets#745]
### Describe the issue

Almost a week ago these 4 filters was moved to a separate subscription (uBlock Origin -- Resource-abuse filters):
- ||edgeno.de^$script,third-party,domain=~edgemesh.com
- /edgemesh.*.js$script,domain=~edgemesh.com|~edgeno.de 
- ||coin-hive.com^$third-party 
- ||jsecoin.com^$third-party

but at the same time they present in "Ublock filters". Maybe it's time to remove them from "Ublock filters"?

### Versions

- Browser/version: Firefox 56.0.1 / Cent Browser 2.9.4.39
- uBlock Origin version: any from at least 1.14.8

**Comment by gorhill** [comment]
At no time did I lose sight I need to remove these filters at some point. "Resource abuse" was [added 9 days ago](https://github.com/gorhill/uBlock/commit/5a0c7c53838349b3fb16a01beb05c5c1128e302a#diff-3a60e352058734090fa5b0a6fa8fa674), while [`assets.json` updates every 13 days](https://github.com/gorhill/uBlock/blob/229edd6c0ed90079f00d983b73a6b1a9a82e682f/assets/assets.json#L4), hence I will remove the filters once it is guarantee users who update will get _"Resource abuse"_ before the removal of the filters in "uBlock filters".
