### ISSUE TITLE
kawanfilm21 duplicates?

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#7453]
```
! https://github.com/NanoMeow/QuickReports/issues/2819
kawanfilm21.org##+js(aeld, contextmenu)
kawanfilm21.org##+js(set, document.onselectstart, null)
```

and new:
```
! https://github.com/realodix/AdBlockID/issues/158
kawanfilm21.*##+js(aeld, /^(?:contextmenu|selectstart)$/)
kawanfilm21.*##+js(aopr, document.onselectstart)
```

**Comment by krystian3w** [comment]
Also copied to regional (without use `*`):

https://github.com/realodix/AdBlockID/commit/28426418847b5e0d642d4547b8a7260882f35b91#diff-805d99e74bf98985a07f8bf21e5a9501R175

https://github.com/realodix/AdBlockID/commit/28426418847b5e0d642d4547b8a7260882f35b91#diff-805d99e74bf98985a07f8bf21e5a9501R179

**Comment by jspenguin2017** [comment]
That is not the regional filter that uBO uses.

**Comment by jspenguin2017** [comment]
The non-default regional filter is not in the assets manifest, uBlock annoyance should not rely on it.

**Comment by llacb47** [comment]
What is the process for regional lists proposal - replacing ABPindo? Anyone have opinions on this?

**Comment by jspenguin2017** [comment]
@llacb47 You have to post in the GitHub Teams internal board, which we don't have access to.

**Comment by krystian3w** [comment]
I think AdGuard has end switched.

**Comment by krystian3w** [comment]
@llacb47 can you try test need use `set` instead `aopr`?

**Comment by mapx-** [comment]
`.org` filters were already removed
