### ISSUE TITLE
marca.com

### ISSUE THREAD

**Issue by NubN** [uBlockOrigin/uAssets#7455]
### URL(s) where the issue occurs

`https://www.marca.com/futbol/real-madrid/2020/05/24/5ecaa73046163fd7218b45c5.html`

### Describe the issue

**this item not works with uBO** (unclickable)

![Captura](https://user-images.githubusercontent.com/46612842/82765767-cb46b080-9e19-11ea-9c08-befedf415dae.PNG)

The **error** in console:

![Captura2](https://user-images.githubusercontent.com/46612842/82765842-7ce5e180-9e1a-11ea-8736-226b1b465b9a.PNG)

### Notes

possible solution:
`marca.com##+js(set, envioBTSC, trueFunc)`

Im not sure.. but if is a **AD**, just block that item 😝

**Comment by llacb47** [comment]
Your solution works 👍
