### ISSUE TITLE
Blocks links that contain "-ad1" from valid domain (Azure domain)

### ISSUE THREAD

**Issue by galyech** [uBlockOrigin/uAssets#7456]
### Description

Blocks links that contain "-ad1" from valid Microsoft Azure domain

### A specific URL where the issue occurs

This is a URL that similar to the actual URL we tried to open. 
the issue was that the "-ad1" or "-ad3" in the url was detected as an ad while this is a valid url with a valid domain.

https://portal.azure.com/#blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/prod-ad1
https://portal.azure.com/#blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/prod-ad3

### Steps to Reproduce

trying to open this valid URL.

### Expected behavior:

browser should open this valid URL
azure.com shouldn't be included in the filters.

### Actual behavior:

uBlock has blocked this website.

### Your environment
![image](https://user-images.githubusercontent.com/29915265/82807324-36cb6500-9e90-11ea-93d9-03acf8df9487.png)

* uBlock Origin version:
* Browser Name and version: Chrome and Firefox.
* Operating System and version:

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by okiehsch** [comment]
````
-ad1.$domain=~oraclecloudapps.com,badfilter
-ad1.$domain=~azure.com|~oraclecloudapps.com
````

**Comment by okiehsch** [comment]
@uBlock-user we should keep the fix in uBO-unbreak until the EasyList update issues are solved.

**Comment by uBlock-user** [comment]
@okiehsch I know, I'm merely letting him know about this, by pinging him.

**Comment by galyech** [comment]
Thanks for your super quick responses!
Just want to add a comment if I may, that we had this issue 3 times in the URL , with 
'-ad1' , '-ad2', '-ad3' ..
I suggest to exclude*.azure.com from the filters, and not only the "-ad1" filter.

**Comment by okiehsch** [comment]
> I suggest to exclude*.azure.com from the filters, and not only the "-ad1" filter.

It is not specifically included, filters like 
`-ad1.$domain=~oraclecloudapps.com``
translate to "block every request that inclides the string `-ad1` except those with the context of the domain `oraclecloudapps.com`.
EasyList could add something like `@@*$domain=azure.com` but that "looks" out of place in my opinion.
If you work with Microsoft Azure you should really just whitelist the domain.

**Comment by uBlock-user** [comment]
How about `-ad*.$domain=~oraclecloudapps.com|~azure.com` ?

**Comment by okiehsch** [comment]
How would that work?
You mean `@@-ad*.$domain=~oraclecloudapps.com|~azure.com`?

**Comment by uBlock-user** [comment]
> How would that work?

Same as before, if `*` is supported ?

**Comment by okiehsch** [comment]
You would also have to disable the countless  ad*. filters in EasyList and that filter is way to broad imo.
You would break countless sites.

**Comment by uBlock-user** [comment]
Hmmm, so just go with `@@-ad*.$domain=oraclecloudapps.com|azure.com`

**Comment by okiehsch** [comment]
That would make some sense. 
I do think users should simply whitelist such a domain. The average user will never access that domain period.

**Comment by gorhill** [comment]
`@@-ad*.` is an untokeniable pattern, best to avoid.

EasyList goes from `-ad0.` to `ad5.`, best to have five tokenizable filters than one untokenizable.

**Comment by gorhill** [comment]
To be clear, and according to information available in this trhead, this seems best to me:

    @@-ad1.$domain=oraclecloudapps.com|azure.com
    @@-ad2.$domain=azure.com
    @@-ad3.$domain=azure.com
    @@-ad4.$domain=azure.com
    @@-ad5.$domain=azure.com

**Comment by kulfoon** [comment]
And waht about `-ad0.`
