### ISSUE TITLE
Linuxize: some ads are not blocked

### ISSUE THREAD

**Issue by B0pol** [uBlockOrigin/uAssets#7457]
### URL(s) where the issue occurs

`https://linuxize.com/post/how-to-remove-untracked-files-in-git/`
### Describe the issue
There are ads on the right side of the website that aren't blocked. 
One leads to `https://www.serverhunter.com/landing/?ad=linuxize&utm_source=linuxize&utm_medium=cpc&utm_campaign=sidebar&utm_content=adblock`
one to `https://www.vultr.com/?ref=8389060-6G`

### Screenshot(s)
![image](https://user-images.githubusercontent.com/58657617/82816912-4d77b900-9e9c-11ea-8faa-59b39a4b19a0.png)

### Versions

- Browser/version: Firefox 76.0.1, with strict protection from trackers in firefox settings. 
- uBlock Origin version: v1.27.6

### Settings
I have found this with my own configuration, but I could reproduce with default settings.

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/cd7963682d7d04a7b8b6ed8c7e9c5559a3ad7fbe
