### ISSUE TITLE
https://www.2giga.link/

### ISSUE THREAD

**Issue by Zhangsun321** [uBlockOrigin/uAssets#746]
my anti virus picked up the problem..
however umatrix did not..
https://i.imgur.com/NGVpncB.png
i dont know squat bout js code beyond picking up on the 'name' of the js.
apparently it is using a proxy to get into coinhive
I don't know if something can be done to detect it..
thanks
Eddie

**Comment by gorhill** [comment]
> however umatrix did not

uMatrix blocks according to the rules you set, so if you not block 1st-party scripts, then of course uMatrix won't block miners served as 1st-party scripts.

**Comment by Zhangsun321** [comment]
oh.. i see... im thinking of it wrong....    i was thinking it would 'list'
1st party scripts on the list like it does 3rd party...
i know umatrix works...

**Comment by ghajini** [comment]
`https://www.2giga.link/d/82JA7A2`
popup ads on click

**Comment by bogachenko** [comment]
@mapx- https://www.2giga.link/download/a128Y
redirect
`2giga.link##+js(setTimeout-defuser.js, (), 1900)`
