### ISSUE TITLE
Store and ublock

### ISSUE THREAD

**Issue by karsebrian** [uBlockOrigin/uAssets#7465]
### URL(s) where the issue occurs
Www.thepopularstuff.com
`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

Www.thepopularstuff.com 
Describe the issue

[Hi, i have made an shopify store, and when people opens it it says that there is malware
on the site  and one of them sand i should say that it was the Chrome ublock extension. Im sorry but I really dont know anything, i have posted a screenshot from one of my customers ]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]
![Screenshot_20200526-193105_Reddit](https://user-images.githubusercontent.com/65938358/82931837-d3246300-9f87-11ea-9c75-828775c18b98.jpg)

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by uBlock-user** [comment]
Why is your domain on that list ?

**Comment by mapx-** [comment]
I fixed the issue for uBO but you @karsebrian should report the issue here (so your site will be removed from malware list): `malwaredomains@riskanalytics.com`
