### ISSUE TITLE
pictures are being blocked (ublock-origin, ubuntu20.04, firefox-latest)

### ISSUE THREAD

**Issue by mrkapqa** [uBlockOrigin/uAssets#7467]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Hello,

i noticed on Ubuntu 20.04 that when the extension is enabled, pictures on this website are not loaded

https://www.corriere.it/moda/cards/da-lady-amelia-windsor-a-sophie-wessex-10-volti-quasi-sconosciuti-royal-family/louis-spencer.shtml?refresh_ce-cp

after disabling it, the pictures load normally.

[Description of the bug or feature]

### A specific URL where the issue occurs

https://www.corriere.it/moda/cards/da-lady-amelia-windsor-a-sophie-wessex-10-volti-quasi-sconosciuti-royal-family/louis-spencer.shtml?refresh_ce-cp

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

Pictures shoud load.

### Actual behavior:

Pictures are not being loaded.
### Your environment

Ubuntu 20.04 64bit
Firefox 76.0.1
uBlock Origin v1.27.6

**Comment by mapx-** [comment]
- it seems to be only a large delay
- test this filter, it should fix the delay
`*$script,redirect-rule=noopjs,domain=corriere.it`

**Comment by mrkapqa** [comment]
sorry, i don't know what to do with the filter.
have seen this behaviour on other pages aswell if remember correctly.

**Comment by mapx-** [comment]
I added the filter in unbreak list, just update that list, eventually then restart firefox and see if works for you

**Comment by mrkapqa** [comment]
won't function

**Comment by mapx-** [comment]
- Use only uBO, no other blocking extensions / addon
- reset uBO to default settings
- in "filters list" tab click "Purge all caches" button then "Update now"
- restart FF
- test again
