### ISSUE TITLE
platuku.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7469]
### URL(s) where the issue occurs

`http://platuku.com/` (may need some action)

### Describe the issue

Anti-adblock

### Screenshot(s)

![platuku](https://user-images.githubusercontent.com/58900598/83051854-845ef200-a089-11ea-8717-31674cfd305a.png)

### Versions

- Browser/version: Firefox 76.0.1/Brave 1.9.72
- uBlock Origin version: 1.27.6/1.26.0

### Settings

- Default

### Notes

Scriptlet injection doesn't work reliably. 
`@@||platuku.com^$ghide`
works, also on Firefox
`platuku.com##^script:has-text(広告ブロッカー)`
`platuku.com##^#f218`
too.

**Comment by sugarfreesweetener** [comment]
`https://www.hugedomains.com/domain_profile.cfm?d=platuku.com`
