### ISSUE TITLE
pageviews.toolforge.org

### ISSUE THREAD

**Issue by dikiaap** [uBlockOrigin/uAssets#7475]
### URL(s) where the issue occurs

`https://pageviews.toolforge.org/?pages=Main_Page&project=en.wikipedia.org`

### Describe the issue
pageviews.toolforge.org is on of the tools used by Wikimedia projects, including Wikipedia (it's linked on [history page](https://en.wikipedia.org/w/index.php?title=Main_Page&action=history)). The EasyPrivacy blocks a request from Wikimedia's API which contains word of "pageviews".

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by uBlock-user** [comment]
AA fixed in https://github.com/uBlockOrigin/uAssets/commit/615f47a28031bff6839af79c2d7b9a5876fbb439
