### ISSUE TITLE
Doubtful meaning of rules 

### ISSUE THREAD

**Issue by gallegonovato** [uBlockOrigin/uAssets#7477]
Good afternoon:

First of all, I'd like to apologize if this is not the place to ask these kinds of questions. But I didn't know where to turn up.

It turns out that in ublock in my rules I showed up:

blank.out-scheme * 3p-frame allow and m.forocoches.com * 3p-frame allow

The second I understand is from foroches but I don't know what the *3p-frame allow

No idea at first.

As far as I know, I didn't put them there. That's why I wanted to ask you if you could tell me what they mean.

A hug

**Comment by uBlock-user** [comment]
> But I didn't know where to turn up

https://www.reddit.com/r/uBlockOrigin/
