### ISSUE TITLE
vazilee.com

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#7478]
### URL(s) where the issue occurs

`https://vazilee.com/PixelGun3D1762`

### Describe the issue

The countdown won't start counting because something takes long time to load. after load it starts counting

### Screenshot(s)

![image](https://user-images.githubusercontent.com/61142621/83325439-7b7a4600-a26c-11ea-8e31-51bb89155165.png)

### Versions

- Browser/version: Opera 68.0.3618.125
- uBlock Origin version: 1.26.0

### Settings

- AdGuard Annoyances​​​​​
- Fanboy’s Annoyance

### Notes

Hope it is possible to boost it

**Comment by uBlock-user** [comment]
> something takes long time to load

revmods.xyz is down, so it goes into an infinite loop of trying to load the images. Timer only starts after the entire page loads, so make that happen just block `||revmods.xyz^` or click on the stop button to force stop loading of the page. Timer cannot be boosted on these pages. Either way, this is a site issue.

**Comment by LGLTeam** [comment]
Oh ok, thanks
Yeah the site moved to other domain
