### ISSUE TITLE
Remove free space from ads on Android Firefox 

### ISSUE THREAD

**Issue by helperman** [uBlockOrigin/uAssets#7480]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
On Android Firefox, after removing an ads there is a free space.
Could it be deleted? Since I found on other sites it is deleted successfully.

### A specific URL where the issue occurs

`https://yandex.ru/q/question/pochemu_tak_dolgo_proizvodiat_vaktsinu_ot_080a5545/`

### Steps to Reproduce

1. Open URL on Firefox Android with uBlock origin installed
2. scroll down until you see a huge white free space

### Expected behavior:

No free space

### Actual behavior:

Free space.
See the screenshot:
![1213](https://user-images.githubusercontent.com/8351863/83332289-ff4f2500-a2a2-11ea-9a13-e9fe69a00154.jpg)

### Your environment

* uBlock Origin version: 1.27.10
* Browser Name and version: Firefox 68.8.1 
* Operating System and version: Android 10

**Comment by xlollomanx** [comment]
I don't know if it can help but this issue happend to me always in amp pages but pratically never in regular pages.

**Comment by uBlock-user** [comment]
Did you report this RU:Adlist first ? 

@dimisa-RUAdList

**Comment by helperman** [comment]
> 
> 
> Did you report this RU:Adlist first ?
> 
> @dimisa-RUAdList

They have blocked the ad itself. Isn't it uBlock's issue?

**Comment by dimisa-RUAdList** [comment]
I study the problem, I will answer in more detail later.

**Comment by uBlock-user** [comment]
@dimisa-RUAdList Is this filter added in your list ?

**Comment by uBlock-user** [comment]
@helperman Regional sites are fixed in regional lists first.

**Comment by dimisa-RUAdList** [comment]
The layout has a fixed minimum height for this item. Correcting this in the rules would be possible if this project existed on its own subdomain. However, this is not so and I do not see how to make such a rule unique so that it does not break something in other sections of the Yandex portal.

Previously, each project had its own subdomain: pogoda.yandex.ru, news.yandex.ru, etc.

Now almost all of them are on the main domain: yandex.ru/pogoda, yandex.ru/news, etc.

Sometimes this makes compiling unique rules an impossible task. This case is just one of those.

**Comment by uBlock-user** [comment]
`yandex.ru##div[class^="_"][style*="height"]`, does it work ? Any breakages ?

**Comment by dimisa-RUAdList** [comment]
Yandex is one of the largest Russian portals. And its layout is adaptive and depends on many conditions: browser, cookies, availability of authorization, screen resolution, etc. The idea of removing empty space for one of the mobile versions of the layout using such a general rule does not seem attractive to me. With a 100% probability, page breaks will occur in so many places and configurations. Even if you simply open this page in the desktop version of Google Chrome, we will see the following: https://i.imgur.com/SSSUTkn.jpg

It’s better not to touch anything.

**Comment by helperman** [comment]
OK. Nevermind. 
Anyway, thanks for your attempt.
And for blocking all these terrible ads.

**Comment by dimisa-RUAdList** [comment]
https://hg.adblockplus.org/ruadlist/rev/1b9617dc6bf2
