### ISSUE TITLE
youku.com can't skip ads

### ISSUE THREAD

**Issue by realhuyang** [uBlockOrigin/uAssets#7484]
### URL(s) where the issue occurs

`[https://v.youku.com/v_show/id_XMTI5MTI0MTM5Ng==.html?spm=a2hbt.13141534.app.5~5!2~5!2~5~5~5!2~5~5!2~5!2~5!2~5~A!10&s=cc001f06962411de83b1]`

### Describe the issue

[can't skip ads]

### Screenshot(s)

[]

### Versions

- Browser/version: [Chrome 83.0.4103.61]
- uBlock Origin version: [1.27.10]

### Settings

- [default]

### Notes

[It used to be skipped automatically, but not now]

**Comment by lain566** [comment]
The test link you provided has geo lock, I have tried another video and I can't reproduce any ad, but I can reproduce anti-adblock with a countdown timer.

Is that the issue you are referring to?

![Anotación 2020-06-01 021447](https://user-images.githubusercontent.com/27441315/83366255-1b8bb880-a3ae-11ea-9597-a32e4d13e9be.png)

**Comment by realhuyang** [comment]
Yes, `youku.com` this domain is unblockable for all ads.

How to use the countdown timer?

**Comment by lain566** [comment]
Does this filter work for you?
`||alicdn.com^*yksdk/*sdk.js$script,domain=youku.com`

**Comment by realhuyang** [comment]
It's work! thank you!

**Comment by lain566** [comment]
@cjx82630 FYI
this filter seems to block youku ads
`||alicdn.com^*yksdk/*sdk.js$script,domain=youku.com`

**Comment by uBlock-user** [comment]
Did you test with both Chinese lists activated ? I don't see any ads or anti-adblock at the aformentioned link.

**Comment by lain566** [comment]
> Did you test with both Chinese lists activated ?

I always do when it comes to a Chinese site.

**Comment by uBlock-user** [comment]
I posed the question for the OP.

**Comment by lain566** [comment]
If I can reproduce with both regional Chinese lists enabled, presumably he must have both lists enabled as well, don't you think?

Anyway, this issue is already resolved.

**Comment by uBlock-user** [comment]
I can't reproduce no matter what, so asking the question itself is the next logical step.

**Comment by lain566** [comment]
Ok, but I can reproduce this issue,

**Comment by uBlock-user** [comment]
Should add that filter then.

**Comment by lain566** [comment]
The suggested filter has been added in Easylist China.
