### ISSUE TITLE
mail.google.com

### ISSUE THREAD

**Issue by cdancette** [uBlockOrigin/uAssets#749]
### Describe the issue

I just noticed that gmail ads appear after loading the page, with ublock origin activated.

### One or more specific URLs where the issue occurs

mail.google.com

### Steps for anyone to reproduce the issue

Not sure how to reproduce, I just noticed some ads twice today on gmail (just above the list of mails).

### Your settings

- OS/version:  Ubuntu Gnome / 16.10
- Browser/version:  Firefox 57 beta
- uBlock Origin version: 1.14.14

##### Your filter lists

default filters

**Comment by gorhill** [comment]
uBO has been updated in the last hours. Was your Gmail page force-reloaded since uBO was updated?

**Comment by cdancette** [comment]
I'm not sure, I'll check if this happens again ..

**Comment by mapx-** [comment]
reopen the issue if still happens

**Comment by cdancette** [comment]
It happens to me yesterday

**Comment by mapx-** [comment]
> The ad sometimes appear when I switch tabs in gmail.

What do you mean ?

**Comment by cdancette** [comment]
I open gmail, I don't have ads in my main tab, but when I switch to the "Promotion" tab for example, ad appear above the emails.

Usually I notice this when gmail has been opened for a while, and it doesn't happen very often.

**Comment by mapx-** [comment]
I cannot reproduce the ads.

**Comment by cdancette** [comment]
Here is the html of two ads that appeared in the Promotion tab
https://gist.github.com/cdancette/d3a0c8e8409e2373e2d73ddd40e0e08c

They also appeared in the social network tab

**Comment by SMed79** [comment]
Screenshot?

**Comment by cdancette** [comment]
I reloaded the page and they disappeared. I'll take a screenshot next time they appear, I don't know how to reproduce it

**Comment by gorhill** [comment]
> I'll take a screenshot next time they appear

What would help is to inspect the HTML code for the ad, so that we can verify whether there is really an existing filter for it. For example, just a few existing filters for Google Mail:

    mail.google.com##.aeF > .nH > .nH[role="main"] > .aKB
    mail.google.com##.aeF > .nH > .nH[role="main"] > .afn:first-child + .mq
    mail.google.com##.aeF > .nH > .nH[role="main"] > .mq:first-child

**Comment by cdancette** [comment]
I provided a gist to the html code in a message above

**Comment by cdancette** [comment]
I just restarted firefox, and the ad appeared again on gmail. Here's a screenshot

![capture du 2017-12-08 18-18-53](https://user-images.githubusercontent.com/10550327/33777235-52aed6be-dc44-11e7-95e7-f8cd62249ee4.png)

**Comment by cdancette** [comment]
@gorhill where are those filters in the repository? I can't find them

**Comment by mapx-** [comment]
Is gmail your start page ? Do you see the ads only on firefox start ?

**Comment by gorhill** [comment]
You say `gmail.com` in the title, but is it really the hostname for the Gmail page? Isn't `mail.google.com`?

**Comment by cdancette** [comment]
I think it's only on firefox start yes. If I reload the page, the ad disappears.

The domain is mail.google.com

**Comment by cdancette** [comment]
I updated the gist, it missed a few levels of <div>

https://gist.github.com/cdancette/d3a0c8e8409e2373e2d73ddd40e0e08c

**Comment by mapx-** [comment]
Well, it seems to be about: https://github.com/gorhill/uBlock/issues/1327

**Comment by gorhill** [comment]
> I updated the gist, it missed a few levels of 

Well these filters _maybe_ match but I can't tell, missing information, your HTML excerpt is too narrow:

    mail.google.com##.aeF > .nH > .nH[role="main"] > .aKB
    mail.google.com###\:rr > .nH > .nH[role="main"] > .aKB

**Comment by cdancette** [comment]
@mapx- Ok well I guess it's not a filter problem, thanks.

@gorhill I expended the HTML a bit earlier, it's just surrounded by a 
```<div class="BltHke nH oy8Mbf aE3" style="" role="main">```
