### ISSUE TITLE
loadout.tf vertical bar

### ISSUE THREAD

**Issue by Perkzitos** [uBlockOrigin/uAssets#7490]
### URL(s) where the issue occurs

`http://loadout.tf/`

### Describe the issue

In the right corner of the page, there is a vertical bar that is supposed to show an ad, but since uBlock Origin blocks the ad, the bar just stays all black. The bar is not removed by uBlock Origin.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/30274161/83366874-1e73b280-a388-11ea-82ab-7697b1600182.png)

### Versions

- Browser/version: Google Chrome 83.0.4103.61 64 bits (Official version)
- uBlock Origin version: 1.27.10

### Settings

All settings are with their default values.

### Notes

I used a custom filter to remove the bar and it worked, but since the bar is useless to stay visible, I think that the removal of it should be global.

**Comment by uBlock-user** [comment]
Sounds like a leftover placeholder bar, @ryanbr fyi
