### ISSUE TITLE
https://9anime.ru

### ISSUE THREAD

**Issue by Jorge9811** [uBlockOrigin/uAssets#7495]
### URL(s) where the issue occurs

`https://9anime.ru/watch/douluo-dalu-2nd-season.0kk7/m22q44v`

### Describe the issue

I went to 9anime.ru to watch some anime and whenever I click on the video player, a popup ad opens.

### Screenshot(s)

https://i.imgur.com/KQVfaro.gif

### Versions

- Browser/version: Mozilla Firefox v76.0.1 x86
- uBlock Origin version: 1.26.2

### Settings

https://i.imgur.com/Wr3vm9R.png

Because I'm using Nano Defender, I also have userResourcesLocation adjusted accordingly.

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by uBlock-user** [comment]
streamtape.com is already fixed in uBO with 

```
streamtape.com##+js(aopr, open)
streamtape.com##+js(aopw, _pop)
```

**Comment by Jorge9811** [comment]
I cleared my cache, updated and the popup ads are still happening though. Closing this issue without giving me the chance to respond was a super rude thing to do. @uBlock-user @mapx-

**Comment by llacb47** [comment]
It was fixed. Not rude.
