### ISSUE TITLE
allmyvideos.net iframe ad

### ISSUE THREAD

**Issue by MarkTheLover** [uBlockOrigin/uAssets#75]
### URL(s) where the issue occurs

http://couchtuner2.to/linkss/644806/

### Describe the issue

An ad scriptlet or something like that [for a lack of a better word] loads over the video player which blocks the video player from playing and when clicked on leads to another website. How do I block that from appearing ?

### Screenshot(s)

![](https://i.gyazo.com/2377ff474854e34b0bdb7b8a0b9c5b26.png)

### Versions

- Browser/version: Chrome 51.0.2704.106 m
- uBlock Origin version: uBlock Origin 1.7.6

### Settings

All privacy settings activated
All other settings EXCEPT "Disable Tooltips" and "Color-blind friendly" are activated.

### Notes

I have tried blocking xhrs, few objects and few scripts but that thing still loads and I have been not able to get rid of it, so I'm posting this as an issue.

**Comment by gorhill** [comment]
Try this is 1.7.7 beta:

    allmyvideos.net###mabl_html_img
    allmyvideos.net###mabl_link > [src="/images/close_gray.png"]:style(bottom:0!important;left:0!important;opacity:0;right:0!important;top:0!important;)

You can't get rid of it because you need it to load the video, but I could restyle it so that you do not end up opening another site.

**Comment by MarkTheLover** [comment]
Thanks but what about 1.7.6 ? No solution for that ?

Wow, seems like impossible to remove it completely. If you manage to remove it via a static filter or something, then the player script wont always load, so you can't play it either. Sucks.

**Comment by gorhill** [comment]
Time is a finite resource.

**Comment by MarkTheLover** [comment]
Didn't answer my question, can you do the filters for 1.7.6 or not ?

**Comment by IDKwhattoputhere** [comment]
How did it not answer your question? He won't. Just click the X if you want to wait until it works in stable.

**Comment by MarkTheLover** [comment]
He deflected it with some bullshit about time. Apparently, this is his style of saying no. Yes, I'm already doing that.

**Comment by gorhill** [comment]
> some bullshit

I gave you the solution -- [I did not have to](https://news.ycombinator.com/item?id=12000746#12001539), nobody forced me but I felt like helping. You did not like it and demanded more from me, making me regret instantly having bothered to spend time on this. In such case, best is that you craft your own.

**Comment by IDKwhattoputhere** [comment]
It's not his "style", not having time to work on a solution is a legitimate reason. He already spent time on a solution that works with the beta and you're just being unthankful.

**Comment by MarkTheLover** [comment]
> I gave you the solution

A solution which is of no help to me but yet I started my response with "thanks". So no thanks. Post something which helps me and if you can't, just say it, don'y make me ask and waste my time. The only thing you have time for is to whine about time and make people work on your demands and style, that's not how collaboration works when working on an issue and when I posted here, I didn't ask for your help, I posted here so everyone else can help, not just you. Infact you acting like a tool makes me instantly regret posting here again.

You didn't help, you post something, it doesn't work on your way, you post some bullshit reply and close the thread, that's all you do. Apparently, you have time to post bullshit and arguments but rather offer a genuine and a straight answer, instead of closing the thread. Keep your shit to yourself, I don't need your help. I run my own filters on gitlab fyi. This is the second time I regretted posting here, tools like you never change. It's your way or the high way and that doesn't work in my world, so adios. 

> you're just being unthankful.

and who made you his attorney ? If you think he's so above it all, go ahead, lick his ass. Are you fucking high or something ? I already said Thanks in my FIRST response, fucking read it kid or get lost! He has all time in the world to close my thread, post some bullshit about time, but he doesn't have a single response which can straighten my issue, yeah keep telling yourself that. 

If you don't have time, then shut down this operation and logout, I'm not gullible. Unlike you I dont spend my time here, I have a job and responsibilities. Learn to make time, that's how it works.
