### ISSUE TITLE
citi.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#750]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://accountonline.citi.com/cards/svc/EditAccntProfPrefNext.do?SYNC_TOKEN=XXXXXXXXXXXXXXXXX&JFP_TOKEN=XXXXXXXXXXXXX#`

Have to be logged in.

### Describe the issue

Clicking save changes does not work.

### Notes

Adding `@@https://accountonline.citi.com/cards/svc/js/tracking.js` fixes it.

**Comment by okiehsch** [comment]
I do not have an account, does
`@@||citi.com/cards/*/tracking.js$script`
work for you?

**Comment by terrorist96** [comment]
Yes.

**Comment by terrorist96** [comment]
### URL(s) where the issue occurs

`https://online.citi.com/US/ag/statements?accountInstanceId=xxxxxx&JFP_TOKEN=xxxxxx` requires log in

### Describe the issue

Desired pop up blocked

### Notes

`@@blob:$popup`

**Comment by terrorist96** [comment]
@okiehsch it's not fixed. I confirm I see your update in the unbreak list, but I still see this in the logs:
![image](https://user-images.githubusercontent.com/12802056/59140879-d3d87980-8971-11e9-8fa3-a48f29be3bdc.png)

**Comment by okiehsch** [comment]
Sorry, it should have been
`@@blob:$domain=citi.com`
which should work.

**Comment by terrorist96** [comment]
> `@@blob:$domain=citi.com`

That doesn't work either. Strange.

**Comment by okiehsch** [comment]
No? Well our filter would globally allow blob popups.

**Comment by terrorist96** [comment]
Even `@@blob:` doesn't work. It needs the `$popup`

> No? Well your filter would globally allow blob popups.

Yeah, I know.

**Comment by okiehsch** [comment]
Try
`@@blob:$popup,domain=citi.com`

**Comment by terrorist96** [comment]
`@@blob:$popup,domain=citi.com` works

**Comment by terrorist96** [comment]
Posted at the same time. :rofl:

**Comment by terrorist96** [comment]
`@@|blob:$popup,domain=citi.com` also works, if that is better (`|` before `blob`)

**Comment by terrorist96** [comment]
`https://fm.info6.citi.com/ats/url.aspx?cr=617&wu=1&we=1&url=https%3A%2F%2Fonline.citi.com%2FUS%2FJRS%2Finfrastructure%2Fnewretarget.do%3Fnext_page%3Djfp%257CCardAccountSummary%26app_store%3DY%26enid%3D6BBE57CA974A84DA99F54036354CDF2607BF&linkName=CT_CAAS_URL&transId=H2020021800186716`

Page won't redirect.

`@@||sts.eccmp.com/sts/scripts/conversen-SDK.js$script,domain=citi.com`
