### ISSUE TITLE
businessinsider.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#7501]
### URL(s) where the issue occurs

`https://www.businessinsider.com/how-to-check-edit-history-on-google-docs`
`https://www.businessinsider.com/how-to-get-subtitles-on-amazon-prime`

https://www.google.com/search?client=firefox-b-d&q=site%3Abusinessinsider.com+%22Check+out+the+products+mentioned%22

### Describe the issue

These ads with affiliate links pointing at different domains have been added to many articles, but aren't going to be hidden by the Adguard lists  (https://github.com/AdguardTeam/AdguardFilters/issues/56422):

```
businessinsider.com##h3:has-text(/Check out the products/)
businessinsider.com##h3:has-text(/Check out the products/)~h4
```

### Screenshot(s)

![affiliate links](https://user-images.githubusercontent.com/35470489/83302188-40770480-a1d1-11ea-8a42-4f7b1e0d490c.png)

### Versions

- Browser/version: Firefox stable
- uBlock Origin version: 1.27.10

### Settings
Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin lists

**Comment by mapx-** [comment]
considering that stuff part of article / review I'm agreeing Alex-302.

**Comment by adranger** [comment]
How is this different from other ad engines that show links and banners based on random words in a text? These aren't product reviews. The user opens a tutorial about a website or program and then gets third-party ads for specific computers and phones.

Even if the articles were reviews about the products themselves, automated third-party e-commerce links would still be ads, though.  If that's not true, then hundreds of filters need to be dropped.

Their system is also adding referral links within the articles that look just like their internal links, and larger ad sections with pictures:

![referral links](https://user-images.githubusercontent.com/35470489/83802859-e28b6680-a681-11ea-8d7f-149765eb5ea2.png)

![ad banners](https://user-images.githubusercontent.com/35470489/83802890-ef0fbf00-a681-11ea-8544-dad6080b1348.png)

**Comment by IEnjoyDrinkingGoodWater** [comment]
space(s) on `https://www.businessinsider.com/category/adblock-plus`

**Comment by mapx-** [comment]
maybe

```
businessinsider.com##.taboola-container
businessinsider.com##.right-rail-min-height-250
```
