### ISSUE TITLE
https://comandotorrents.org/

### ISSUE THREAD

**Issue by Ronam22** [uBlockOrigin/uAssets#7502]
### URL(s) where the issue occurs
```

https://comandotorrents.org/
https://comandotorrents.org/lupin-iii-o-primeiro-torrent
```

### Describe the issue

Download options don't show up because it's detecting adblock

### Versions

- Browser/version: [Chrome Version 83.0.4103.61]
- uBlock Origin version: [1.27.10]

### Settings

Default
-

### Notes

Tried with incognito mode and regular no luck

**Comment by uBlock-user** [comment]
Already fixed in spa, por: AdGuard Spanish/Portuguese
