### ISSUE TITLE
jfdb.jp

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#7506]
### URL(s) where the issue occurs

`https://jfdb.jp/search/title/?GENRE=5`
`https://jfdb.jp/title/9184`

### Describe the issue

Script preventing right-clicks on images. <kbd>CTRL</kbd> hides them.

### Versions

- Browser/version: Firefox stable
- uBlock Origin version: 1.27.10

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin lists

**Comment by llacb47** [comment]
@okiehsch is this a cant-fix?
```
    $(window).on("keydown", function(e) {
        17 != e.keyCode && 91 != e.keyCode && 44 != e.keyCode && 18 != e.keyCode || $(".fig").each(function() {
            if ($(this).data("imgsrc")) {
                var e = $(this).find("img")[0];
                $(e).attr("src", "/global/images/jfdb_noimage.png"),
                $(this).addClass("fig-noimage")
            }
        }),
        80 == e.keyCode && i()
    })
```

There is no way to defuse just this part of this script (`https://jfdb.jp/assets/js/project/project.util.min.js`) without breaking the rest of it.
