### ISSUE TITLE
vw-sklep.pl

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uAssets#7509]
### URL(s) where the issue occurs

`https://vw-sklep.pl/order`

### Describe the issue

Click button on popup, then choose anything, then scroll a little and click to add something to the basket. Then go to basket and you should be able to click „Dalej", but it's not working, because uBlock filters – Privacy blocks gtm.js.

### Screenshot(s)

![2020-06-04_18-21](https://user-images.githubusercontent.com/19818572/83782880-4321a000-a690-11ea-8ebe-676faa32fc41.png)

![2020-06-04_18-22](https://user-images.githubusercontent.com/19818572/83783447-6f3d2100-a690-11ea-8ce0-b0669753f98a.png)

### Versions

- Browser/version: Vivaldi | 3.0.1874.38

- uBlock Origin version: 1.27.8 

### Settings

![2020-06-04_18-25](https://user-images.githubusercontent.com/19818572/83784570-cba04080-a690-11ea-821b-46a56e989927.png)

### Notes
Fix => `@@||www.googletagmanager.com/gtm.js$script,domain=vw-sklep.pl`

**Comment by mapx-** [comment]
@ryanbr

**Comment by krystian3w** [comment]
why not in Polish Official filters?

**Comment by hawkeye116477** [comment]
Cuz it's problem in international Privacy filterlists, so if they broke that, they should fix that :smile:
