### ISSUE TITLE
Crunchyroll video ads not blocked by uBlock Origin

### ISSUE THREAD

**Issue by valoeghese** [uBlockOrigin/uAssets#7512]
### URL(s) where the issue occurs

`https://www.crunchyroll.com/a-certain-scientific-railgun/episode-14-dragon-strike-jaw-of-the-dragon-king-795449`

### Describe the issue

The midroll and preroll video ads on crunchyroll ads are no longer being blocked by uBlock origin. See below screenshot.
 

### Screenshot(s)
![image](https://user-images.githubusercontent.com/46117728/83854660-24440c00-a76b-11ea-824e-f933ef98576d.png)

### Versions

- Browser/version: Opera
- uBlock Origin version: 1.26.0

### Settings

- (no changes)

### Notes

(the issue is pretty self explanatory and simple - shouldn't need any further investigation)

**Comment by uBlock-user** [comment]
Does removing cookies and site data help ?

**Comment by valoeghese** [comment]
I couldn't seem to get that blocking the ads. Though maybe I'm missing something

**Comment by krystian3w** [comment]
Try disabled AdBlock embeded in Opera setting - IMO you have turned on.

**Comment by lain566** [comment]
I can reproduce ads on Chrome, suggested filter doesn't work for me https://github.com/uBlockOrigin/uAssets/issues/7512#issuecomment-639663115
and removing cookies works, but he will have ads again later.

I am unable to reproduce ads with Firefox.
