### ISSUE TITLE
tver.jp

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7514]
### URL(s) where the issue occurs

1: `https://tver.jp/corner/f0052235`

2: `https://tver.jp/corner/f0052158`

3: `https://tver.jp/corner/f0052228`

### Describe the issue

1 & 2: again questionnaire (annoyances), but you'll also get anti-adblock.

3. video can't be played; reported but not yet fixed.

### Screenshot(s)

(No SS for 3.)

![tver1](https://user-images.githubusercontent.com/58900598/83861966-3ff3e600-a75c-11ea-94c8-fc75f5c7fe0c.png)

![tver2](https://user-images.githubusercontent.com/58900598/83861985-47b38a80-a75c-11ea-89de-f41921218e04.png)

![tver3](https://user-images.githubusercontent.com/58900598/83862703-4767bf00-a75d-11ea-83b9-e6e7b313c080.png)

### Versions

- Browser/version: Brave 1.9.76 with its blocker completely turned off (necessary for Brave to avoid the anti-adblock)
- uBlock Origin version: 1.27.10

### Settings

- Default + Fanboy Annoyances + uBlock Annoyances

### Notes

Geo-restricted

1: `tver.jp##+js(set, enquete.checkDispEQ, falseFunc)`
Anti-adblock:
`tver.jp#@#.adspace`
`@@||tver.jp/css/adspace.css$css,1p`

3. `@@||pubads.g.doubleclick.net/gampad/ads?$xhr,domain=tver.jp`

Help me for 2.

**Comment by mapx-** [comment]
`tver.jp#@#.adspace` already in jp list - no anti adb stuff

**Comment by Yuki2718** [comment]
> 
> 
> `tver.jp#@#.adspace` already in jp list - no anti adb stuff

Yeah, I should have mentioned that - I tend to assume Default doesn't include JP list as it's enabled only if your browser locale is JP.

**Comment by krystian3w** [comment]
This need: `nanop-click-elements-onready.js` / `nanop-click-elements-onload.js` or better clicker?

**Comment by Yuki2718** [comment]
@krystian3w Not sure if it's Can't fix without such a function, will investigate again after I have done some other chores.

**Comment by uBlock-user** [comment]
That questionaire as an `onclick` event attached to it, you block that questionaire, you block that `onclick` event from ever occuring as you won't be able to click to trigger the `onclick` event and hence video will never appear.

@gorhill

**Comment by krystian3w** [comment]
At the next step of the survey, they ask about the year of birth and the postal code (I assume it must be Japanese).

Such data should not be filled in by an uBO / Nano Adblocker / AdGuard.

**Comment by Yuki2718** [comment]
@uBlock-user Thx for clarification.
@krystian3w You're right, it looks more like a pay-wall. I found that until you tell this to me I haven't even read the sentences in the modal which says "Please fill in a questionaire **before** watching." :(

**Comment by Yuki2718** [comment]
Closed as it's no different from https://github.com/uBlockOrigin/uAssets/issues/7576. Only those beyond annoyances will be worth being kept open.
