### ISSUE TITLE
Youtube ads currently bypass uBlock

### ISSUE THREAD

**Issue by sundayLOOKplants** [uBlockOrigin/uAssets#7516]
### URL(s) where the issue occurs
`https://www.youtube.com/watch?v=ZZPjLP5QBgg`

### Describe the issue

 
Intro ads have started appearing on youtube videos again with uBlock active.

### Versions

- Browser/version: Firefox 76.0.1 stable
- uBlock Origin version: v1.18.6

### Settings

EasyList, EasyPrivacy, the malware lists, and Peter Lowe's advanced tracking list are active.

**Comment by ghajini** [comment]
1.
Get a updated version of ublock origin and reset to default settings

2. Make filters upto date

**Comment by gwarser** [comment]
I expanded `json-prune` alredy for https://www.reddit.com/r/uBlockOrigin/comments/gx19kt/ads_on_youtube_as_of_today/

https://github.com/uBlockOrigin/uAssets/commit/451b7b52062d81974a893903ba38ba2e3a5d4e3f

**Comment by gwarser** [comment]
>uBlock Origin version: v1.18.6

You should really update uBO.

**Comment by sundayLOOKplants** [comment]
Apologies, and thank you for the quick response. Everything is correct after updating.
