### ISSUE TITLE
nyoooz.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#752]
Ads in the right sidebar, in between article content and below headers on https://www.nyoooz.com.

**Error URLs:**
https://www.nyoooz.com/news/mumbai/927830/elphinstone-stampede-dying-woman-molested-on-bridge-by-bystander-video-shows/ (Article ads)
https://www.nyoooz.com/news/delhi/, https://www.nyoooz.com/entertainment/ (Ad below header)

_**Note:** Using uBO 1.14.8 on Chrome 61 with the default filters and settings._

**Comment by SMed79** [comment]
add
```
/ads/mobiles/*
||omgpm.com^$third-party
||d2ids9961d0d8k.cloudfront.net^
```
@ryanbr @Khrin `omgpm.com` Should be moved to easylist.

**Comment by Khrin** [comment]
> `omgpm.com` Should be moved to easylist ??
Yes, I have moved it.
