### ISSUE TITLE
anitube.be

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7520]
### URL(s) where the issue occurs

`https://anitube.be/player/99135`

### Describe the issue

Annoying chat message on upper-right.

### Screenshot(s)

![anitube](https://user-images.githubusercontent.com/58900598/83942864-7308a900-a832-11ea-8028-42046b024cc3.png)

### Versions

- Browser/version: Brave 1.9.76
- uBlock Origin version: 1.27.10

### Settings

- Default

### Notes

Maybe `||1uno1xkktau4.com^`
AdGuard Base blocks this by regex rule tho.

**Comment by okiehsch** [comment]
Hm, I don't get those messages. I can reproduce a popup triggered by `1uno1xkktau4.com`.

**Comment by Yuki2718** [comment]
Yeah, forgot to report the popup. Anyway blocking that seems to block the message (can be geo-dependent?) too.

**Comment by okiehsch** [comment]
Does the script inject filter alone also block the messages on your end?

**Comment by Yuki2718** [comment]
> 
> 
> Does the script inject filter alone also block the messages on your end?

Yes.

**Comment by Yuki2718** [comment]
> 
> 
> Hm, I don't get those messages. I can reproduce a popup triggered by `1uno1xkktau4.com`.

Just FYI: I found I don't get the message always even without the filters, but instead now I got this:

![anitube2](https://user-images.githubusercontent.com/58900598/83943361-5a9a8d80-a836-11ea-8f10-495f8a885b7a.png)

**Comment by okiehsch** [comment]
I can't reproduce that.
I have added another filter for it to take effect you have to reload the site bypassing the cache one time.

**Comment by Yuki2718** [comment]
> 
> 
> I can't reproduce that.
> I have added another filter for it to take effect you have to reload the site bypassing the cache one time.
> 
> The filters purpose is to get rid of all the `patithatspartal.pro` requests.

That seems to be anyway blocked by the injection rule.
uBlock filters has `@@||anitube.be^$script,1p` so the added filter won't work?

**Comment by Yuki2718** [comment]
`anitube.be` has switched to `anitube.cx` so rules need to be updated.
`anitube.cx##+js(set, ATESTADO, 1)`
for their new anti-adblock. I also get popup on clicking any videos.

**Comment by uBlock-user** [comment]
Did you update Spanish list ? Fixed in there.

**Comment by Yuki2718** [comment]
I didn't, okey will test with that. I guess anyway rules for `anitube.be` can be removed from uBlock filters.
