### ISSUE TITLE
Quora ads

### ISSUE THREAD

**Issue by mbnoimi** [uBlockOrigin/uAssets#7521]
### URL(s) where the issue occurs

`https://www.quora.com/Is-it-hard-to-start-and-run-a-video-game-company`

### Describe the issue

How to get ride of Quora ads?
I tried many filters but nothing worked fine!

### Screenshot(s)

![image](https://user-images.githubusercontent.com/284547/83945674-f87d6080-a814-11ea-84b6-58a584ac2ce6.png)

### Versions

- Browser/version: Firefox 77.0.1 (64-bit)
- uBlock Origin version: 1.27.10

### Settings

All the settings set to the defaults.

**Comment by mapx-** [comment]
I get no such ad. 
right click on page, "save as..", zip together html + folder => upload on some server, post here the link

**Comment by mbnoimi** [comment]
> I get no such ad.
> right click on page, "save as..", zip together html + folder => upload on some server, post here the link

https://send.firefox.com/download/9bdadedaf21424c3/#RJ3aCJuwODj2P0tHLYnc8A

**Comment by mapx-** [comment]
save it again, something went wrong:

![image](https://user-images.githubusercontent.com/10303732/83946879-d0d9c880-a813-11ea-8acd-b4fc7f4b5552.png)

**Comment by mbnoimi** [comment]
> save it again, something went wrong (save as => quora.html for example, not the long article name):

This is really weird!
I launched the link once again for saving it but I didn't see any ads!!!
I didn't modify uBlock configurations!

![image](https://user-images.githubusercontent.com/284547/83947041-48f8bc00-a81d-11ea-88f0-5a05c5ed4220.png)

**Comment by mbnoimi** [comment]
Very sorry for wasting your time
