### ISSUE TITLE
Facebook forces to install Messenger when trying to view messages on mobile

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uAssets#7525]
### URL(s) where the issue occurs

`https://m.facebook.com/messages/`

### Describe the issue

Facebook tries to force to install Messenger when trying to view messages on a mobile phone browser. This happens at least when trying to open messages on Firefox and Chrome (probably other mobile browsers are affected as well). (However, if Opera is being used, no forcing happens and messages open normally  for some reason.)

Would it be possible to tackle this with Ubo some way so that Facebook messages could be viewed on other (Ubo supported) mobile browsers as well?

### Screenshot(s)

![messenger](https://user-images.githubusercontent.com/17256841/83958259-6149f480-a878-11ea-9144-ebaae4024eb8.PNG)

### Versions

- Browser/version: Firefox for Android 68.8.1
- uBlock Origin version: v1.27.10

### Notes

This can also be tested on a desktop browser by using an user agent switcher.

I have used these user agents for testing:

(Android 8 & Firefox 68)
`Mozilla/5.0 (Android 8.0; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0`

(Android 8 & Opera 58)
`Mozilla/5.0 (Linux; Android 8.0.0; F5321) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Mobile Safari/537.36 OPR/58.2.2878.53403`

**Comment by peace2000** [comment]
@uBlock-user That cannot be reproduced if the Messenger app is already installed. It's an official policy that they force to install it: https://www.facebook.com/help/community/question/?id=598873660281691

**Comment by mapx-** [comment]
It seems to be on server side. I disabled the scripts and still happens.

**Comment by uBlock-user** [comment]
I don't have the app neither Android browser, I tried by setting userAgent you supplied in the post on th desktop version of Firefox.

**Comment by peace2000** [comment]
All right. Thank you anyway. So user agent is the only way to go with this.

**Comment by krystian3w** [comment]
https://addons.mozilla.org/pl/firefox/addon/uaswitcher/

but no compatible with Firefox **mobile** 78 before 2021.

**Comment by peace2000** [comment]
That works actually on my Firefox mobile.
