### ISSUE TITLE
[Breakage] Problems in Youku

### ISSUE THREAD

**Issue by winterbear33** [uBlockOrigin/uAssets#7526]
### Description
我在使用优酷的时候虽然广告被屏蔽掉了，但同时我却只能用空格和鼠标左键暂停视频页面，无法再次点击从而继续播放
[Description of the bug or feature]

> When I use Youku, although the ad is blocked, at the same time, I can only pause the video page with blank space and left mouse button, and can't click again to continue playing

### A specific URL where the issue occurs
`https://www.youku.com/`

### Expected behavior:

[What you expected to happen]
在使用优酷时既可以去掉广告，空格键控制视频也可以正常使用

> When I use Youku, advertisement will be removed, and I will be able to control the video with the space bar

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:uBlock Origin v1.27.10
* Browser Name and version:chrome
* Operating System and version:win10

**Comment by Yuki2718** [comment]
Not reproduced without Chinese lists, with CJX's alone added, with EL China alone added, and with both added on Brave. On Firefox I got a "cookie disabled" warning despite Tracking protection didn't block anything (as set to Private only) - indeed turning it off and manually adding youku.com to Firefox' cookie whitelist doesn't help. Anyway that's no uBO issue and OP uses Chrome.
URL: `https://v.youku.com/v_show/id_XNDY5NTkyOTUwMA==.html?spm=a2hcb.12675304.m_2556_c_8261.d_4&s=efbfbd645cefbfbdefbf&scm=20140719.manual.2556.show_efbfbd645cefbfbdefbf`
![youku](https://user-images.githubusercontent.com/58900598/83974949-daeeea80-a92b-11ea-99bf-b50293edfe9e.png)

**Comment by llacb47** [comment]
@lain566 so what was the issue? Just curious

**Comment by lain566** [comment]
Cannot resume playback when clicking on video or pressing space bar.

**Comment by Yuki2718** [comment]
@lain566 How you could reproduce that? For testing I blocked all yksdk staff by a slightly modified rule (to avoid your badfilter) but still can freely resume either by click or by space bar.

![youku](https://user-images.githubusercontent.com/58900598/84049797-d851cb00-a9e7-11ea-8a8a-dc5028b8b986.png)

(Environment is the same as above, both Chinese filters enabled; tested URL: `https://v.youku.com/v_show/id_XNDY5NTkyOTUwMA==.html?spm=a2hcb.12675304.m_2556_c_8261.d_4&s=efbfbd645cefbfbdefbf&scm=20140719.manual.2556.show_efbfbd645cefbfbdefbf`)
Maybe it depends on videos or need to viewed from mainland China?

**Comment by lain566** [comment]
I just realized it's still broken, the filter I added doesn't fix it.

@Yuki2718 maybe it's your IP, or that you need to refresh the page one more time, I don't know, but I can reproduce the breakage using Chrome and Firefox.

**Comment by lain566** [comment]
@Yuki2718 Try again with this link using Firefox in incognito mode if you want, when the video has loaded, refresh the page, now try to pause and resume by clicking on the video.
`https://v.youku.com/v_show/id_XNDY2MzQxMjQ4NA==.html`

**Comment by Yuki2718** [comment]
@lain566 Same, I can still resume even after several refreshes. Apparently Firefox's Tracking Protection is irrelevant. Only thing I feel a bit weird is that comments flows even when paused. But IIRC they made somewhat different connection on different IPs in past.

![youku](https://user-images.githubusercontent.com/58900598/84147815-f9262900-aa98-11ea-807d-4d41ea07112b.png)

**Comment by Yuki2718** [comment]
@lain566 I'm not sure if they really changed something in the whole service, yet something changed on my end - last I tested `log.mmstat.com` could not be blocked https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/359. But now I can block it without breakage, instead it seems `@@||alicdn.com/alilog/$script,domain=v.youku.com` is required to play the video. Maybe it's time to revisit? Without your last rule ads are inserted in video, and the CJX's more aggresive rule blocks tiny ad banner too, so I wonder if they still cause the issue.
