### ISSUE TITLE
tomshardware.com [Anti-Adblock]

### ISSUE THREAD

**Issue by tillcash** [uBlockOrigin/uAssets#7527]
### URL(s) where the issue occurs

`https://www.tomshardware.com/`

### Describe the issue

Anti-adblock.

### Screenshot(s)

https://i.imgur.com/h0sGHg3.png

### Versions

- Browser/version: Firefox 77.0 (64-bit)
- uBlock Origin version: 1.27.10

**Comment by uBlock-user** [comment]
Can't reproduce unless I block third-party scripts.

**Comment by uBlock-user** [comment]
fix -- `tomshardware.com##+js(aopw, _sp_)`
