### ISSUE TITLE
dropgalaxy.com

### ISSUE THREAD

**Issue by AndnixSH** [uBlockOrigin/uAssets#7528]
### URL(s) where the issue occurs

`https://dropgalaxy.in/yfrppx01u7r2`

### Describe the issue

Adblock is detected

### Screenshot(s)

![image](https://user-images.githubusercontent.com/40742924/83975135-72cfe280-a8f2-11ea-98d6-ecad1919762a.png)

### Versions

- Browser/version: Chrome Version 83.0.4103.61 (Officiel version) (64-bit)
- uBlock Origin version: 1.27.10

### Settings

- Disable show number on icon

**Comment by uBlock-user** [comment]
`dropgalaxy.*##+js(set-constant, usrblock, noopFunc)` will work but would require `dropgalaxy.com##+js(remove-attr, disabled, .downloadbtn)` and `remove-attr` only runs once, so button will never be clickable.

**Comment by mapx-** [comment]
on my side the OP link will redirect to
`https://dropgalaxy.com/825-change-your-car-insurance-and-pay-less.html`

and no anti adb stuff

**Comment by uBlock-user** [comment]
I can reproduce and even on default settings on Firefox despite the redirection.

**Comment by mapx-** [comment]
I tested now in FF too, still working on my side, I can download the file

**Comment by okiehsch** [comment]
I get redirected to `dropgalaxy.com` and can download the file without issue.

**Comment by uBlock-user** [comment]
Working today...not sure why it didn't before.

**Comment by JobcenterTycoon** [comment]
Anti adblock overlay is back
<img width="957" alt="Unbenannt1" src="https://user-images.githubusercontent.com/48647394/92747092-262df480-f384-11ea-819e-e3b8ddd27523.PNG">

**Comment by JobcenterTycoon** [comment]
The counter doesn’t work anymore

**Comment by mapx-** [comment]
it was already fixed , update your lists

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back again

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back again

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back

**Comment by JobcenterTycoon** [comment]
`@@||contextual.media.net/dmedianet.js?cid=$domain=dropgalaxy.com`
`@@||contextual.media.net/*/fcmain.js$domain=dropgalaxy.com`
`dropgalaxy.com##iframe[id*="_mN_main_"]`

is the best think i can do.

**Comment by ghajini** [comment]
`https://dropgalaxy.in/olo4at78sidb`

@mapx- 
There so many exception filters and noop filters there for this site, would you revise....
I put up these filters in my filters and I can download the file
```
||dropgalaxy.com^$generichide,1p,important
||pagead2.googlesyndication.com^$script,domain=dropgalaxy.com,important
||contextual.media.net^$script,domain=dropgalaxy.com,important
||googleads.g.doubleclick.net^$subdocument,domain=dropgalaxy.com,important
*$script,redirect-rule=noopjs,domain=dropgalaxy.com,badfilter
*$image,redirect-rule=2x2.png,domain=dropgalaxy.com,badfilter
@@.jpg$image,domain=dropgalaxy.com,badfilter
@@.png$image,domain=dropgalaxy.com,badfilter
```

**Comment by JobcenterTycoon** [comment]
Looks like there is no anti adblock active on your link. On my link `https://dropgalaxy.in/nuxd85nycfdz` i get anti adblock

**Comment by mapx-** [comment]
ok, re-added

**Comment by JobcenterTycoon** [comment]
The fake button is back

**Comment by JobcenterTycoon** [comment]
The site detects VPN but when i block this overlay with `dropgalaxy.com##.modalpop` i can download the file.

<img width="908" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/99660630-ead63300-2a62-11eb-916c-1ef4abb606fa.PNG">

Do you think it can be blocked as annoyance?

**Comment by t0ma5** [comment]
this is a tough one. I have been trying for a while without luck :(

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back

**Comment by t0ma5** [comment]
> @@||googletagmanager.com/gtag/js?id=*$xhr,domain=dropgalaxy.com

not for me :(

**Comment by mapx-** [comment]
provide example link

**Comment by ghajini** [comment]
This one
`https://dropgalaxy.in/8miqb03l3wbx`

![Screenshot_2020-12-01-22-55-35-920_org mozilla fenix](https://user-images.githubusercontent.com/20338483/100774762-70c18900-3428-11eb-9b47-26567c4e863f.png)

**Comment by mapx-** [comment]
desktop all fine, I even don't need the filter above

**Comment by t0ma5** [comment]
> 
> 
> desktop all fine, I even don't need the filter above but you tested android

can u fill the captcha and download the file from the link? I am on FF desktop and it doesn't work, with or without the filter suggested by JobcenterTycoon

**Comment by mapx-** [comment]
yes, I can download the file

**Comment by ghajini** [comment]
@mapx- you can use debugging on firefox nightly ,connected to firefox desktop

**Comment by ghajini** [comment]
Just block their timer(redirect rule already their😄)
`||tmp.dropgalaxy.in/js/countd.js$script,domain=dropgalaxy.com`

**Comment by t0ma5** [comment]
> ||tmp.dropgalaxy.in/js/countd.js$script,domain=dropgalaxy.com

genius! :) it worked

**Comment by JobcenterTycoon** [comment]
omg it works even without any exeptions

**Comment by ghajini** [comment]
They are checking here and their, I used firefox nightly android, got antiadblock, after few mins, refreshing antiadblock gone....then I used firefox stable android, got antiadblock then blocked that timer script....now even w/o that block script, I get no antiadblock. ....on first visit they detect adblock

**Comment by t0ma5** [comment]
> 
> 
> Just block their timer(redirect rule already there😄)
> `||tmp.dropgalaxy.in/js/countd.js$script,domain=dropgalaxy.com`

it doesn't work anymore. it says "Skipped Countdown"

**Comment by ghajini** [comment]
Which link it is?
Iam using this override
```
dropgalaxy.*##+js(set, navigator.userAgent, '')
||tmp.dropgalaxy.in/js/countd.js$script,domain=dropgalaxy.com
||tmp.dropgalaxy.in/js/ads.js$script,domain=dropgalaxy.com
*$image,redirect-rule=2x2.png,domain=dropgalaxy.com,badfilter
*$script,redirect-rule=noopjs,domain=dropgalaxy.com,badfilter
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=dropgalaxy.com,important
||contextual.media.net/dmedianet.js$script,domain=dropgalaxy.com,important
||tpc.googlesyndication.com^$script,domain=dropgalaxy.com,important
||dropgalaxy.com^$generichide,important
```

**Comment by t0ma5** [comment]
any dropgalaxy link @ghajini 
tried your last code.. no change, the timer stops but no download link can be gotten "Skipped countdown"
it seems like dropgalaxy spend a fair amount of time working it's way around adblocking

**Comment by ghajini** [comment]
Provide link where this happens

**Comment by uBlock-user** [comment]
If you're blocking the anti-adblock script, you will have to wait 15 seconds physically.

**Comment by t0ma5** [comment]
> 
> 
> If you're blocking the anti-adblock script, you will have to wait 15 seconds physically(countdown will remain stuck at 15 seconds.)

did you read my post? it still works 100% fine if captcha is done via audio BUT not if u use the visual captcha

@ghajini like I said, any link ... random example: https://dropgalaxy.in/23uhfmy8ynj7

**Comment by ghajini** [comment]
Yes I read,can't reproduce anything

**Comment by t0ma5** [comment]
> 
> 
> Yes I read,can't reproduce anything

you have no problem downloading the file with visual and/or audio captcha?

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back again

**Comment by ghajini** [comment]
Does this work alongwith https://github.com/uBlockOrigin/uAssets/issues/7528#issuecomment-739504695 @JobcenterTycoon 

`||dropgalaxy.*^$inline-script`

i know it breaks site functionalities but it works on my side ,i can download the file ....gorhill has given immense power to ublock origin

**Comment by JobcenterTycoon** [comment]
looks so simpel but it works perfect

**Comment by JobcenterTycoon** [comment]
I get popups on `https://dropgalaxy.in/23uhfmy8ynj7`

**Comment by okiehsch** [comment]
I don't get that request on my end.
`buipovexhav.com` is blocked in `EasyList`.

**Comment by JobcenterTycoon** [comment]
Good this fixes the issue

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back

**Comment by JobcenterTycoon** [comment]
`@@||dnhfi5nn2dt67.cloudfront.net/ui-bootstrap-tpls.min.js`
`dropgalaxy.*##+js(nowoif)`
`dropgalaxy.*#@#+js(abort-current-inline-script, $, getScript)`
`dropgalaxy.*#@#+js(abort-on-property-write, _pop)`

Is the best think i can do

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back

**Comment by JobcenterTycoon** [comment]
ok just remove `dropgalaxy.com###modalpop` (its triggers anti adblock and they check VPN/Proxy serverside now)

**Comment by ghajini** [comment]
adblock detected

`https://dropgalaxy.in/klvlmdxqadht`

**Comment by Dark-Yox** [comment]
No one managed to bypass this new detection ?

**Comment by JobcenterTycoon** [comment]
@Dark-Yox 

```
@@||tmp.dropgalaxy.in/advertisement/$subdocument,domain=techyneed.com
techyneed.com###iframe
```

**Comment by stephenhawk8054** [comment]
I think I cannot click on the `Free Download` button in `dropgalaxy.com`.

URL: `https://dropgalaxy.in/w4848ff63hqf`

It redirects to `dropgalaxy.com`. Click on `Free Download`, it cannot continue going to next page. Also there are 3rd-party tracking domains.

![image](https://user-images.githubusercontent.com/66517106/144434542-03eeddb3-2764-4677-aaea-6db0e1d46cc5.png)

Firefox 94.0.2, ublock 1.39.0 default

<details><summary>Settings</summary>

```yaml
uBlock Origin: 1.39.0
Firefox: 94
filterset (summary): 
  network: 78194
  cosmetic: 39349
  scriptlet: 16139
  html: 600
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30339-118, 9m
    ublock-badware: 3512-1, 9m
    ublock-privacy: 187-0, 9m
    ublock-abuse: 74-0, 9m
    ublock-unbreak: 1709-0, 9m
    easylist: 61360-445, 9m
    easyprivacy: 26407-482, 9m
    urlhaus-1: 8190-0, 8m
    plowe-0: 3700-3, 8m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  firewallPaneMinimized: false
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 254
  launchFromSelfie: true
```

</details>

Proposed filters:

```
dropgalaxy.*##+js(acis, globalThis, break;case)
dropgalaxy.*#@#+js(window.open-defuser)
```

**Comment by JobcenterTycoon** [comment]
@Yuki2718 new variant of amazonaws `https://4a91682a975409cd1eeabf4126ef9e5f7bec6c3b319cca515dab.s3.amazonaws.com/79a28619a4`
