### ISSUE TITLE
###divclose global filter rule

### ISSUE THREAD

**Issue by setyb** [uBlockOrigin/uAssets#7530]
Is there any documentation as to why the global filter rule `###divclose` is included in the default uBO filter list and is being applied to every website?

After a bit of back and forth regarding a report of a broken non-public-facing website, it turns out this global filter was causing the issue for the client.

Can this filter rule be safely removed from the default uBO filter list?

**Comment by krystian3w** [comment]
try

`#@##divclose`

for domains where element is annoying try:

`EXMAPLE.DOMAIN###divclose[id]`

**Comment by mapx-** [comment]
removed
