### ISSUE TITLE
https://shorten.sh/ indefinite re-directions

### ISSUE THREAD

**Issue by sanGtH** [uBlockOrigin/uAssets#7531]
### URL(s) where the issue occurs
`https://shorten.sh/NHcJGnBJ`

### Describe the issue
Refer to the screenshot. When you click on that continue button, the site re-directs to a 
new site in a new tab. No matter how many times you click that button, the site keeps
re-directing to other sites indefinitely.  Those sites are malicious as reported by antivirus.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/13797193/84055077-f0b6eb00-a9d1-11ea-8cc7-42687eb0151e.png)

### Versions

- Browser/version: [here] Chrome **v83.x**
- uBlock Origin version: [here] **v1.27.10**

### Settings
All settings are in their default state.

**Comment by ghajini** [comment]
`||shorten.sh/sw.js$script,1p`
