### ISSUE TITLE
a2zapk.com adblock detect

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#7535]
### URL(s) where the issue occurs:
`https://a2zapk.com/832182-sd-maid-system-cleaning-tool-4-15-12-final-pro-dark-venom-mod-a2z.html`

(press "go to download page" and you are redirected to page `https://a2zupload.com/urlpage.html`
where there's the message:

"You are totaly safe with A2ZAPK we never use POP-ADS, Adult ADS Or anything which might harm your device also we allow you to download anything you need for free so please whitelist (a2zupload.com) from your ADBlock software."

and the "adblock detect" on "direct link")

thanks in advance

**Comment by mapx-** [comment]
- working fine FF / chrome
- reset uBO to default settings, `purge all caches`, click `update now`
- disable any other blocking addon / extension

**Comment by krystian3w** [comment]
I see on few seconds (5 or less):

​
![wyszukiwarka2](https://user-images.githubusercontent.com/35370833/84150269-eba17c80-aa61-11ea-80a8-f6e1845a8d1f.JPG) |
--- |

**Comment by gwarser** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/g35o6q/ublockorigin_not_working_on_specific_a2zapkcom/

I was able to reproduce sometimes on real phone. Sadly, I cannot attach debugger.

Using these steps was easier to repro: https://www.reddit.com/r/uBlockOrigin/comments/g35o6q/ublockorigin_not_working_on_specific_a2zapkcom/fox8inl/

**Comment by ghajini** [comment]
@patrickdrd you just click Adblock detect button, page will refresh, giving you direct link

**Comment by patrickdrd** [comment]
I'm clicking on it but I'm redirected on the same page

**Comment by stephenhawk8054** [comment]
Can't right click in some link.

URL:
`https://a2zapk.com/Search/Launcher/`

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 79482
  cosmetic: 41908
  scriptlet: 19205
  html: 624
listset (total-discarded, last updated): 
  added: 
    ublock-annoyances: 4357-4, 55m
  default: 
    ublock-filters: 30778-30, 55m
    ublock-badware: 3733-1, 55m
    ublock-privacy: 191-0, 55m
    ublock-abuse: 76-0, 55m
    ublock-unbreak: 1696-0, 55m
    easylist: 63178-591, 1h.56m
    easyprivacy: 26637-481, 1h.56m
    urlhaus-1: 8152-0, 55m
    plowe-0: 3681-2, 55m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 732 ms
popupPanel: 
  blocked: 6
```
</details>

Proposed filter:

`a2zapk.com##+js(acis, document.oncontextmenu, nocontext)`
