### ISSUE TITLE
Additions to resource abuse

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#754]
I noticed [this ](https://github.com/xd4rker/MinerBlock/blob/master/assets/filters.txt) list has some entries not included within the resource abuse list. Should they be added?
Specifically:
```
reasedoper.pw
mataharirama.xyz
listat.biz
lmodr.biz
jyhfuqoh.info
```

**Comment by passjs** [comment]
https://blog.eset.ie/2017/09/15/cryptocurrency-web-mining-in-union-there-is-profit/

**Comment by okiehsch** [comment]
@passjs thanks for the link.

**Comment by terrorist96** [comment]
@okiehsch what about `jyhfuqoh.info`?

**Comment by okiehsch** [comment]
That is a domain used by `oload.info` and already fixed with 
`||info^$script,third-party,domain=oload.info`, if you can find another site that uses it, I will add it.

**Comment by terrorist96** [comment]
Also found this. May have some entries not included here:
https://github.com/hoshsadiq/adblock-nocoin-list/blob/master/nocoin.txt

**Comment by passjs** [comment]
https://github.com/keraf/NoCoin/
https://raw.githubusercontent.com/keraf/NoCoin/master/src/blacklist.txt

**Comment by okiehsch** [comment]
Which of these entries do you think should be added to `resource-abuse.txt`?
And an example page to reproduce would be nice.

**Comment by SMed79** [comment]
Probably these domains:
```
||cnhv.co^$third-party
||reasedoper.pw^$third-party
||minecrunch.co^$third-party
||lmodr.biz^$third-party
||listat.biz^$third-party
||mataharirama.xyz^$third-party
--
||gus.host/coins.js
||miner.pr0gramm.com^$third-party
||miner.pr0gramm.com^$websocket
||miner.pr0gramm.com/cryptonight-worker.js
```

**Comment by okiehsch** [comment]
````
reasedoper.pw
modr.biz
listat.biz
listat.biz
````
already added.

`minecrunch.co` the domain is for sale.

`gus.host/coins.js`  fetches coin-hive and does not mine itself as far as I can see.

`nhv.co` redirects to coin-hive and does not mine itself, example: `https://cnhv.co/29w8`

`miner.pr0gramm.com/cryptonight-worker.js` isthis not a custom script only for that website and actually only if you go to `miner.pr0gramm.com` specifically?

**Comment by SMed79** [comment]
> minecrunch.co the domain is for sale.

I saw that it is always embed for e.g. at `francescocrema.it` but you're right the file does not exist.

**Comment by okiehsch** [comment]
@SMed79 just out of curiosity, do you know of another domain with an embedded `minecrunch.co/web/miner.js`?

**Comment by SMed79** [comment]
Sorry, I missed your comment.
> do you know of other domains with an embedded minecrunch.co

No, I can't find another example.

... and just fyi, even if a domain is parked (for sale) it's can still used to push ads or popup.
for e.g `bokepabc.com` at these **nsfw** sites: `asia88.info`, `barat88.info` or `korea88.info`

```
http://bokepabc.com/okiehsch.js
```

**Comment by okiehsch** [comment]
@gwarser regarding the sites you mentioned at https://github.com/gorhill/uBlock/issues/3151

````
*://minecrunch.co/web/*
*://coinerra.com/lib/*
*://miner.pr0gramm.com/xmr.min.js*
*://kiwifarms.net/js/Jawsh/xmr/xmr.min.js*
*://anime.reactor.cc/js/ch/cryptonight.wasm
*://joyreactor.cc/ws/ch/*
*://kissdoujin.com/Content/js/c-hive.js*
*://minero.pw/miner.min.js*
````
- I added `coinerra.com` and `minero.pw`.

- `minecrunch.co` and `pr0gramm.com` see https://github.com/uBlockOrigin/uAssets/issues/754#issuecomment-335978534

- `kiwifarms.net/js/Jawsh/xmr/xmr.min.js` does not exist.

- `kissdoujin.com/Content/js/c-hive.js` fetches coinhive which is blocked.

- The `joyreactor.cc` and `reactor.cc` entries do not prevent mining on these websites, `||joyreactor.cc/v/*$script` does but I can not read Cyrillic, so I have no clue if this breaks anything.

**Comment by SMed79** [comment]
@okiehsch 
> kiwifarms.net/js/Jawsh/xmr/xmr.min.js does not exist.

==> kiwifarms.net/js/Jawsh/xmr/xmr.min.js?kill-yourself-sammy-hahahahahahahahaha

**Comment by okiehsch** [comment]
@SMed79 hm now `kiwifarms.net` has been added to the `Malware Domain List` and several host-files so you can't easyly access the site at all.

**Comment by SMed79** [comment]
Also blacklisted by Malwarebytes.

**Comment by gotitbro** [comment]
@SMed79 kiwifarms.net/js/Jawsh/xmr/xmr.min.js?**kill-yourself-sammy-hahahahahahahahaha**

What is that referencing?
