### ISSUE TITLE
linksly.co { Antiadblock }

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#7540]
### URL(s) where the issue occurs

`https://linksly.co/iA94u3`

### Describe the issue

Antiadblock 

### Versions

- Browser/version: firefox A.
- uBlock Origin version: 1.27.10

### Settings

 uBO's default settings

### Notes
Generic rule for adservers(propellerads)
 `/tag.min.js$important`

https://user-images.githubusercontent.com/20338483/84183618-ce909c00-aaa9-11ea-98ce-fb3216d545ab.png

as per discussed here 
https://github.com/uBlockOrigin/uAssets/commit/bd59b295f00ae861634ab99db4abafd6580db0bb

**Comment by ghajini** [comment]
`https://linksly.co/htai`

||linksly.co/sw.js$script,1p

**Comment by PerfectSalad** [comment]
should `linksly.co##.banner` be added?
