### ISSUE TITLE
PDF files not displayed on Yammer.com with cosmetic filters on

### ISSUE THREAD

**Issue by Mel34** [uBlockOrigin/uAssets#7544]
### URL(s) where the issue occurs

`https://www.yammer.com`

### Describe the issue

PDF files aren't displayed in Mozilla Firefox on Yammer website. My school organization is using it and all the PDF files are displayed as gray rectangles, their contents not displayed. PDF viewer controls are also not displayed. Using Full screen option Yammer offers when viewing a PDF file somebody uploaded, the black and white loading bar appears and stays on screen forever, with actual PDF file never being rendered.

### Screenshot(s)

Cosmetic filtering on:
![Screenshot from 2020-06-11 12-52-10](https://user-images.githubusercontent.com/13254332/84377503-f6374f80-abe2-11ea-8f06-807fc099ddc7.png)
Cosmetic filtering off:
![Screenshot from 2020-06-11 12-51-34](https://user-images.githubusercontent.com/13254332/84377553-0b13e300-abe3-11ea-9a97-be0752de26c5.png)
Fullscreen PDF document cosmetic filtering on:
![Screenshot from 2020-06-11 12-52-29](https://user-images.githubusercontent.com/13254332/84377586-1f57e000-abe3-11ea-8fc7-55500e20d932.png)
Fullscreen PDF document cosmetic filtering off:
![Screenshot from 2020-06-11 12-53-02](https://user-images.githubusercontent.com/13254332/84377614-30085600-abe3-11ea-97f6-9bd24875d05c.png)
Note: some personal information was redacted to protect the identities of people involved.

### Versions

- Browser/version: [Mozilla Firefox 76 - 79]
- uBlock Origin version: [v1.27.10]

### Settings

- I am an advanced user toggled ON
- RUS: RU AdList toggled ON

### Notes

PDF files are displayed correctly when
- cosmetic filter is disabled from uBlock origin's interface
- Ignore generic cosmetic filters is set to ON in uBlock origin's settings

**Comment by uBlock-user** [comment]
requires account ? pdf page link ?

**Comment by Mel34** [comment]
> requires account ? pdf page link ?

It does. I authenticate over national education network.

**Comment by uBlock-user** [comment]
Can you provide a dummy account for further troubleshooting ?

**Comment by Mel34** [comment]
`https://www.yammer.com/o365.skole.hr/#/files/442941390848`
Try the above URL.
I am not sure you will be able to access the file.
I don't have the authority to generate accounts on skole.hr domain which are used to authenticate.

**Comment by uBlock-user** [comment]
So you will have to help troubleshoot this, add `@@||yammer.com^$ghide` and try to reproduce the issue.

**Comment by Mel34** [comment]
Added `@@||yammer.com^$ghide` to my filters list, confirming that it works now with cosmetic filtering ON. Tested with multiple PDF documents in both preview and full screen mode.

**Comment by llacb47** [comment]
I have access to a yammer instance so I can help with testing.

**Comment by uBlock-user** [comment]
> Added @@||yammer.com^$ghide to my filters list, confirming that it works now with cosmetic filtering ON. 

Please also test in default uBO settings.

**Comment by Mel34** [comment]
> > Added @@||yammer.com^$ghide to my filters list, confirming that it works now with cosmetic filtering ON.
> 
> Please also test in default uBO settings.

Settings reset to default,  nothing in my filters list, PDF's display normally. Guess it was on my end?

**Comment by uBlock-user** [comment]
> PDF's display normally. Guess it was on my end?

Without having to add `@@||yammer.com^$ghide` ?

**Comment by Mel34** [comment]
> > PDF's display normally. Guess it was on my end?
> 
> Without having to add `@@||yammer.com^$ghide` ?

That's right. It just works now.

**Comment by Mel34** [comment]
> > PDF's display normally. Guess it was on my end?
> 
> Without having to add `@@||yammer.com^$ghide` ?

I've restored my original uBo settings from backup file and removed the `@@||yammer.com^$ghide` from the rules list - it works without it with cosmetic filtering disabled.

**Comment by Mel34** [comment]
In any case, problem solved for me, thank you for helping me out!

**Comment by uBlock-user** [comment]
>with cosmetic filtering disabled.

Why are you disabling cosmetic filtering ?

**Comment by Mel34** [comment]
> > with cosmetic filtering disabled.
> 
> Why are you disabling cosmetic filtering ?

I'm not, it was a lapsus, I meant to say enabled.
