### ISSUE TITLE
Captcha blocked

### ISSUE THREAD

**Issue by kurobara31694** [uBlockOrigin/uAssets#7545]
### URL(s) where the issue occurs
9anime.ru

### Describe the issue
The hCaptcha box is blocked on 9anime.ru
 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/14954885/84519683-0cebae00-ac98-11ea-830a-0638509ff4d5.png)

### Versions

- Browser/version: 83.0.4103.97 
- uBlock Origin version: Nano Adblocker 1.0.0.149 (but the issue is the basic uBlock filter)

### Settings

-

### Notes
I believe I get the captcha because I use a VPN, so I am sorry if this is difficult to replicate

**Comment by kurobara31694** [comment]
Dallas!

**Comment by uBlock-user** [comment]
Can you reproduce on this settings ? if so, using the logger post name of the filter and the list it resides in(clicking on the filterin the logger will show.)

**Comment by uBlock-user** [comment]
Can you reproduce on default settings ? if so, using the logger post name of the filter and the list it resides in(clicking on the filterin the logger will show.)

**Comment by kurobara31694** [comment]
yes, I can

The filter is the regular ublock filter. Whenever I disable it it shows fine
![image](https://user-images.githubusercontent.com/14954885/84523639-41626880-ac9e-11ea-8788-c3eceaed1b7b.png)

Is this what you meant? I'm sorry!
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt

**Comment by mapx-** [comment]
> if so, using the logger post name of the filter and the list it resides in(clicking on the filter in the logger will show.)

**Comment by kurobara31694** [comment]
<details><summary>Logger output</summary>

```
+0
9anime.ru
1
image
https://9anime.ru/favicon.ico
```
```
+0
9anime.ru
1
image
https://9anime.ru/cdn-cgi/images/trace/captcha/nojs/h/transparent.gif?ray=5a24ec204c8fc7f2
```
```
+0
@@||9anime.*^$generichide
++
9anime.ru
1
generichide
https://9anime.ru/watch/sorcerous-stabber-orphen.36ky
```
```
+0
||9anime.*^$script,1p
--
9anime.ru
1
script
https://9anime.ru/cdn-cgi/scripts/hcaptcha.challenge.js
```
```
+0
9anime.ru
1
css
https://9anime.ru/cdn-cgi/styles/cf.errors.css
```
```
+0
##+js(aopr, AaDetector)
9anime.ru
dom
https://9anime.ru/watch/sorcerous-stabber-orphen.36ky
```
```
+0
##+js(acis, Math, zfgloaded)
9anime.ru
dom
https://9anime.ru/watch/sorcerous-stabber-orphen.36ky
```
```
+0
9anime.ru
1
doc
https://9anime.ru/watch/sorcerous-stabber-orphen.36ky
```
```
+0
https://9anime.ru/watch/sorcerous-stabber-orphen.36ky
```
</details>

**Comment by kurobara31694** [comment]
I'm so sorry! I figured it out right after I posted it!

**Comment by mapx-** [comment]
does this work ?

`@@||9anime.ru/cdn-cgi/scripts/hcaptcha$script`

**Comment by kurobara31694** [comment]
Yes it does, thank you

**Comment by uBlock-user** [comment]
Bad filter -- `||9anime.*^$script,1p`
