### ISSUE TITLE
wav.tv

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7546]
### URL(s) where the issue occurs

[NSFW]
1 & 2: `https://wav.tv/m/13265524/230ORE-653_%E3%81%AF%E3%82%8B%E3%81%AA`
3: `https://en.wav.tv/`
`https://wav.tv/`
`https://tw.wav.tv/`

You will be automatically redirected, to access wav.tv (not en.wav.tv or tw.wav.tv) choose Japanese flag on upper right drop-down or set browser locale to JP.

### Describe the issue

1. Ad remnants over the player

2. Popup on clicking any thumbnails under the video; looks conditional, so far only occurred on Firefox.

3. Popunder on clicking thumbnails, only on Chromium.

### Screenshot(s)

1: 
![wav](https://user-images.githubusercontent.com/58900598/84525283-5975ce80-ad16-11ea-918a-f9c01630bcd6.png)

2:

![wav2](https://user-images.githubusercontent.com/58900598/84525295-5ed31900-ad16-11ea-9289-3eba8df06154.png)

### Versions

- Browser/version: Brave 1.9.76 for 1, 3 and Firefox 77.0.1 for 1, 2
- uBlock Origin version: 1.27.10

### Settings

- Default (including JP filter)

### Notes

1. `||pokoran.com^`
2. `wav.tv##+js(window.open-defuser)`
3. `wav.tv##+js(aeld, click)` works but somehow I can't find a proper second parameter, maybe looking wrong place? I believe it's l672 of `https://en.wav.tv/assets/am.wav.unminified.js` (though no network request for this script).

**Comment by Yuki2718** [comment]
@mapx- Still getting 2 & 3 but I used wrong term, 3 is also popup.

2:
![wav22](https://user-images.githubusercontent.com/58900598/84558857-ec435700-ad70-11ea-8212-24397fec73c3.png)

3:
![wav3](https://user-images.githubusercontent.com/58900598/84558858-f1a0a180-ad70-11ea-8314-7f1c273ae5e4.png)

Maybe need to be accessed from Japan? Both leads to click.dtiserv2.com.

**Comment by okiehsch** [comment]
Does
`wav.tv##+js(ra, data-popup-url)`
work for you?

**Comment by Yuki2718** [comment]
@okiehsch Working both on Firefox and Brave, ty!
