### ISSUE TITLE
n1.ru menu ads

### ISSUE THREAD

**Issue by vladostman** [uBlockOrigin/uAssets#7547]
### URL(s) where the issue occurs

`https://ekaterinburg.n1.ru/`

### Describe the issue

There is a menu at the top of the page, the last element in that menu is an ad. They seem to be custom crafted/native ads.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66869331/84566518-ff1f5100-ad9b-11ea-8595-1a91fb5061f2.png)

### Versions

- Browser/version: Firefox 77.0.1 64 bit
- uBlock Origin version: AdNauseam 3.9.104

### Settings

AdNauseam uses uBlock list by default, no settings changes.

### Notes

Adding this filter: `n1.ru##.top-panel-menu__item._banner` seems to make it go away.

**Comment by uBlock-user** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
Ok: https://hg.adblockplus.org/ruadlist/rev/cc791f9f1c38
