### ISSUE TITLE
ad over video not blocked 9anime.ru

### ISSUE THREAD

**Issue by kurobara31694** [uBlockOrigin/uAssets#7548]
### URL(s) where the issue occurs
`https://9anime.ru/watch/the-8th-son-are-you-kidding-me.4p47/52220mv`

### Describe the issue
When you press play, an ad pops up on the left side of the video and you have to close it
 

### Screenshot(s)
![image](https://user-images.githubusercontent.com/14954885/84572118-8b5e5380-ad5d-11ea-96b7-30b0cb34c87d.png)

### Versions

- Browser/version: Version 83.0.4103.97
- uBlock Origin version: 1.27.10

### Settings
Default

### Notes
When I tried to use the picker to grab the ad I couldn't, purging the cache and updating everything also did not help.

**Comment by uBlock-user** [comment]
Does adding `||d3v3bqdndm4erx.cloudfront.net^` work ?

**Comment by krystian3w** [comment]
Nope, other solution?

My:

`*##.drts`

**Comment by uBlock-user** [comment]
It's `||dl5ft52dtazxd.cloudfront.net^`, disregard the above one.

**Comment by krystian3w** [comment]
`||striplesthosen.club/floater$xhr,domain=www.mp4upload.com`


if down: `||dl5ft52dtazxd.cloudfront.net^`

**Comment by kurobara31694** [comment]
> ||striplesthosen.club/floater$xhr,domain=www.mp4upload.com

this does work for me

**Comment by uBlock-user** [comment]
Blocking `dl5ft52dtazxd.cloudfront.net` prevents connection attempt to `striplesthosen.club`
