### ISSUE TITLE
homeguides.sfgate.com generates billions of requests and never stops

### ISSUE THREAD

**Issue by nijaz-kulenovic** [uBlockOrigin/uAssets#7549]
### URL(s) where the issue occurs

`https://homeguides.sfgate.com/identify-squash-melon-plants-51753.html`

### Describe the issue

When I use ublock origin and the following lists:

EasyList
EasyPrivacy
Fanboy's Annoyance List
uBlock filters
uBlock filters -- Annoyances
uBlock filters -- Unbreak
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse

I get unlimited loading of page which never stops and in few seconds ublock shows already over 3000 requests, this increasing to higher numbers quickly. Also my laptop overheats, and I hear cpu fan working hard.

### Screenshot(s)

https://postimg.cc/N9w2XBWD

### Versions

- Browser/version: google chrome 83
- uBlock Origin version: 1.27.10

### Settings

turned on additionally to default settings: Prevent WebRTC from leaking local IP addresses, Block CSP reports and used above mentioned custom filter lists

### Notes

disabling ublock then restarting page fixes problem, reenabling ublock makes problem not reappear, probably because image or something else is loaded from cache then

trying in incognito with ublock active makes problem appear

changing ip via vpn does not fix problem

disabling other extensions like https everywhere does not fix problem

ublock logger shows billions of entries reappearing: `https://homeguides.sfgate.com/public/images/logo-fallback.png`

**Comment by krystian3w** [comment]
What happend after disable non-stock:

```
Fanboy's Annoyance List
```

Maybe this is guilty.

**Comment by nijaz-kulenovic** [comment]
even if i disable that one, problem persists

**Comment by krystian3w** [comment]
try disable AdBlock embeded in chrome:

```
chrome://settings/content/ads
```


![obraz](https://user-images.githubusercontent.com/35370833/84573761-e1091f00-ada2-11ea-86b4-be52af2a6323.png) |
--- |

to

![obraz](https://user-images.githubusercontent.com/35370833/84573770-ebc3b400-ada2-11ea-9dcf-8af2512694ed.png) |
--- |

**Comment by nijaz-kulenovic** [comment]
i turned it to Allowed (from left to the right), but unfortunately the problem is still present

**Comment by uBlock-user** [comment]
Disable all other extensions except uBO and test with uBO on default settings.

**Comment by nijaz-kulenovic** [comment]
Then problem is gone. But I noticed that problem is gone in all other cases like (while always trying in new incognito window and closing it after each try or holding shift key while clicking refresh button of chrome):
default settings + other extensions in same state + normal window (not incognito)
my previous settings + all filters exceot my filters disabled

The cause is my filter. When I put `!` symbol before this filter (which i forgot to mention i used), it is gone: `||homeguides.sfgate.com/public/images/logo-fallback.png$image`

That was the problem.

But then it is still not solved problem, because I don't understand why would not ublock simply block that image, and that is it? Some js is retrying to load that image, so I should block it too?

The same problem appears in umatrix when I block images in umatrix but do not block that item in ublock, the only difference is that now large number of blocked elements being displayed is on umatrix icon instead of ublock icon.

The problem disappears when I disable scripts for that site in umatrix.

And forgot to mention, number keeps increasing even if I abort page load in chrome.
Probably some script trying to load that image forever.

**Comment by krystian3w** [comment]
```
||homeguides.sfgate.com/public/images/logo-fallback.png$image,redirect=32x32.png
```

or

```
||homeguides.sfgate.com/public/images/logo-fallback.png$image
*/logo-fallback.png$redirect-rule=32x32.png,domain=homeguides.sfgate.com
```

**Comment by krystian3w** [comment]
```
||homeguides.sfgate.com/public/images/logo-fallback.png$image,redirect=32x32.png
```

or

```
||homeguides.sfgate.com/public/images/logo-fallback.png$image
*/logo-fallback.png$image,redirect-rule=32x32.png,domain=homeguides.sfgate.com
```
