### ISSUE TITLE
vogue.in

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#755]
Anti adblock warning is shown on `https://www.vogue.in`.

**SS:** https://i.imgur.com/IalZlCO.png
**Error URL:** `https://www.vogue.in/content/ultimate-guide-bridal-jewellery-every-kind-bride/`

Similar anti adblock notice is shown on:
```
https://www.gqindia.com/
https://www.cntraveller.in/
https://www.architecturaldigest.in/
```

_**Note:** Using uBO 1.14.8 on Chrome 61 with the default filters and settings._

**Comment by mapx-** [comment]
```
@@||vogue.in^*ads$script
@@||gqindia.com^*ads$script
@@||cntraveller.in^*ads$script
@@||architecturaldigest.in^*ads.js$script
```

**Comment by uBlock-user** [comment]
`*/ads.js$script,important,redirect=noopjs,domain=gqindia.com|cntraveller.in|architecturaldigest.in|vogue.in`
