### ISSUE TITLE
community.spiceworks.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#7550]
`https://community.spiceworks.com/topic/296996-defrag`

Logon annoyance pop-up with locked scroll:

![obraz](https://user-images.githubusercontent.com/35370833/84575088-1e71aa80-adab-11ea-9984-9a2e83d1e9dc.png) |
--- |

```
community.spiceworks.com##.join-login-alt--six-second.join-login-alt.join-login-wrapper
community.spiceworks.com##body.sui-u-no-scroll:style(overflow:auto !important;)
```

Pop-up from "![obraz](https://user-images.githubusercontent.com/35370833/84575105-4234f080-adab-11ea-9317-a300e91c2811.png)" have another HTML.

![obraz](https://user-images.githubusercontent.com/35370833/84575118-61cc1900-adab-11ea-9ee2-aba9e3137379.png) | ![obraz](https://user-images.githubusercontent.com/35370833/84575152-83c59b80-adab-11ea-946e-af6d3954838a.png)
--- | ---
⚪ login | 🟠 join

---

#7217 - I suppose better no cut also on `community.spiceworks.com`?

**Comment by krystian3w** [comment]
Open site with cleaned cookies and wait in topic ~ 6 seconds.

**Comment by uBlock-user** [comment]
I waited 2 minutes, still nothing.

**Comment by krystian3w** [comment]
So must scroll to down/top, maybe javascript detect `onscroll` event listener.

**Comment by uBlock-user** [comment]
Reproduced in private browsing mode

**Comment by krystian3w** [comment]
Page added pop-up for revisited guests: https://github.com/uBlockOrigin/uAssets/issues/10387
