### ISSUE TITLE
[NSFW] movies.hentaistream.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7551]
### URL(s) where the issue occurs

`https://movies.hentaistream.com/`

### Describe the issue

Popup on clicking any video.

### Screenshot(s)

![hentaistream1](https://user-images.githubusercontent.com/58900598/84598794-367b2400-aea8-11ea-966d-4a24e1941eda.png)

### Versions

- Browser/version: Brave 1.9.80
- uBlock Origin version: 1.27.10

### Settings

- Default + AdGuard Japanese

### Notes

`hentaistream.com##+js(window.open-defuser)`

**Comment by uBlock-user** [comment]
`||trunblock.com^` works

**Comment by Yuki2718** [comment]
So better to report to EL? Not sure what country this site is. I also see a red "please support us" messages which AdGuard Base already addressed.

**Comment by uBlock-user** [comment]
I'm thinking of going with `*$3p,script,denyallow=vjs.zencdn.net,domain=hentaistream.com` these people can adding such garbage 3p domains anytime they want.

**Comment by Yuki2718** [comment]
Yeah, likely. I just ping @ryanbr .
