### ISSUE TITLE
linkshorten.xyz

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#7558]
### URL(s) where the issue occurs

`https://linkshorten.xyz/66jO5aI3`

### Describe the issue

anti adblock, popups and onfocus annoyance

### Versions

- Browser/version: Firefox 77.0.1
- uBlock Origin version: v1.27.10

**Comment by uBlock-user** [comment]
already fixed in https://github.com/uBlockOrigin/uAssets/commit/522bc70ce2a883eda836b24d46f037658bfdbefd
