### ISSUE TITLE
lemonde.fr issue

### ISSUE THREAD

**Issue by S3ndG** [uBlockOrigin/uAssets#7559]
`https://www.lemonde.fr/`

### Describe the issue
This banner appears at the bottom of the page : "you are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page."

### Screenshot(s)
http://ratm6.free.fr/captures_decran/lemonde_ublock_issue.jpg
### Versions

- Browser/version: firefox 77.0.1 x64
- uBlock Origin version: v1.27.10

### Settings
no changes

**Comment by mapx-** [comment]
does this work for you ?

`lemonde.fr##+js(nostif, f.parentNode.removeChild(f), 100)`

**Comment by S3ndG** [comment]
Yes thank you could you add this to your list?
THanks.

**Comment by mapx-** [comment]
added
