### ISSUE TITLE
rollingstone.com - video blocked

### ISSUE THREAD

**Issue by mapx-** [uBlockOrigin/uAssets#756]
ublock 1.14.11.114 , default setup

go to `http://www.rollingstone.com/music/news/watch-eminem-demolish-donald-trump-in-bet-awards-freestyle-w508187`

the video at the top of article is blocked

disabling `ublock filters - privacy` these filter shoud work (probably is working `redirect` too, don't tested):
```
@@||assets.wennermedia.com/rollingstone/js/ads-bundle.min.$domain=rollingstone.com
@@||securepubads.g.doubleclick.net^$script,domain=rollingstone.com
@@||amazon-adsystem.com^$script,domain=rollingstone.com
```

filter necessary when `ublock filters - privacy` is ON:
`@@||googletagservices.com/tag/js/gpt.js$script,domain=rollingstone.com`

if `ublock filters - experimental` is ON => another filter should be disabled (I added `badfilter` keyword):
`||googletagservices.com/tag/js/gpt.js$important,script,badfilter`

Sure, a fix could be added as dynamic rule:
`www.rollingstone.com googletagservices.com * allow`

**Comment by gorhill** [comment]
If there are not many pages broken like this throughout the site, I rather wait to take the time to investigate whether I can avoid allowing `doubleclick.net`, `amazon-adsystem.com` and `googletagservices.com` over all `rollingstone.com`.

**Comment by gorhill** [comment]
I was about to agree to add the exception filters, but now the video is playing on my side with default settings. Is it just me?

**Comment by mapx-** [comment]
I can confirm, working fine now.

Initially reported here:
https://adblockplus.org/forum/viewtopic.php?p=171799#p171799

**Comment by gorhill** [comment]
I see only `googletagmanager.com` being excepted when I load the page, so it seems the site changed something on their side.
