### ISSUE TITLE
Outlook.com Anti-Adblock

### ISSUE THREAD

**Issue by claell** [uBlockOrigin/uAssets#7562]
### URL(s) where the issue occurs

outlook.com

### Describe the issue

Anti-Adblock message is using over 100 px of height, so should be blocked by default. Notice that they ask you to pay to get the space back.

 

### Screenshot(s)

![grafik](https://user-images.githubusercontent.com/6171135/84786474-1c972980-afed-11ea-9ce1-0a8348f23cf1.png)

**Comment by krystian3w** [comment]
unable reproduce, still works:

```
##a[href="https://windows.microsoft.com/outlook/ad-free-outlook"]:upward(4)v
```

**Comment by krystian3w** [comment]
Also need enable `uBlock - Annoaynce` (non-stock / non-default).

**Comment by krystian3w** [comment]
No break mail so copied into Annoyance.

**Comment by claell** [comment]
> Also need enable `uBlock - Annoaynce` (non-stock / non-default).

Sorry, basically I was requesting to have it added in a default list.

> @claell You misinterpreted the EasyList criteria. Though it may not fulfill all the "what we allow" requirements, it also does not fulfill any of the "do not allow" criteria. For your quote, it's
> 
> > Content with a height over 100px **and** a combined area larger than 105,000px.
> 
> The default size of the anti adb you see is 165 * 254.2 = 41,943 px. What we regard as hard anti-adb is usually much more annoying and can not be ignored - I have long been just ignoring this Outlook c**p message.

Actually, you are also wrong. I did not notice the **and** in that sentence when opening this issue. Still the area covered is larger than 105,000px. The size of the screenshot I took is 165×894 = 147510px. On the [EasyList criteria](https://easylist.to/2013/05/10/anti-adblock-guide-for-site-admins.html) it says: "This includes the size of unnecessary empty areas caused by the message."

**Comment by mapx-** [comment]
enable uBO annoyances list

**Comment by uBlock-user** [comment]
> On the EasyList criteria it says: "This includes the size of unnecessary empty areas caused by the message."

We do not follow Easylist criteria for anti-adblock fixes.

**Comment by Yuki2718** [comment]
@claell I said **default** size. If you use larger screen ofc the size of SS will be larger. You need to use dev tools to know the default size.

**Comment by claell** [comment]
> > On the EasyList criteria it says: "This includes the size of unnecessary empty areas caused by the message."
> 
> We do not follow Easylist criteria for anti-adblock fixes.

Really? The README sounds different: 

> The rationale on whether to include a specific filter in one of uBO's own filter lists is the same as outlined by EasyList/EasyPrivacy policies, also taking into account whether a filter requires uBO's extended filter syntax.

On the policy site you find https://easylist.to/2013/05/10/anti-adblock-guide-for-site-admins.html

Should the README be updated then? Is there a different place where the actual policy that is followed is documented?



> @claell I said **default** size. If you use larger screen ofc the size of SS will be larger. You need to use dev tools to know the default size.

Well, the policy from EasyList does talk about "the size of unnecessary empty areas caused by the message." That reads to me like the *actual* needed spaced, as they use the verb *caused*. The screenshot was taken on a FHD screen, which is probably what the Easylist maintainers had in mind when writing the policy.

**Comment by uBlock-user** [comment]
@claell Yes, for ads and all that stuff, I did say "for anti-adblock fixes."

**Comment by claell** [comment]
> @claell Yes, for ads and all that stuff, I did say "for anti-adblock fixes."

The README talks about filters and to me that includes also anti-adblock fixes, as they are also filters that are maintained in this repo and also listed on the linked policy.

> > On the policy site you find https://easylist.to/2013/05/10/anti-adblock-guide-for-site-admins.html
> 
> No, this is the policy for Anti-adblock - [#7563 (comment)](https://github.com/uBlockOrigin/uAssets/issues/7563#issuecomment-644885838)

Maybe that should be officially documented somewhere if this really is the current policy.

**Comment by Yuki2718** [comment]
@claell Then any size specification goes nonsense, whatever size it is just use large enough screen and you can fulfill any size requirements. It's a kinda common sense which was not clearly stated.

**Comment by uBlock-user** [comment]
> Maybe that should be officially documented somewhere if this really is the current policy.

I don't see the need, this policy is for the maintainers to be aware, not for users to worry about. Users merely have to activate the Annoyance list **once**(those who haven't done it already)

**Comment by claell** [comment]
> @claell Then any size specification goes nonsense, whatever size it is just use large enough screen and you can fulfill any size requirements. It's a kinda common sense which was not clearly stated. In addition, it was written in 2013 when FHD was not common.

I know that this is a bit nonsense. But they are talking about the areas "caused", not the default theoretic ones. I'd argue that FHD actually was common in 2013 for computer monitors.

> I don't see the need, this policy is for the maintainers to be aware, not for users to worry about. Users merely have to activate the Annoyance list once(those who haven't done it already)

I'd really prefer a correct README so everybody has the same common sense and decisions can be understood by everybody. Having to activate it on every single device and operating system I use is rather annoying itself unfortunately.

**Comment by Yuki2718** [comment]
@claell We're volunteers spending out spare time to address issues, not to discuss all he details of words. We filter writers (in broad sense) naturally assume it's the default size, as otherwise the sentence is nonsense. Whatever you discuss here, I believe, none of us see any reason to block that staff by default.

**Comment by krystian3w** [comment]
Only annoying not break outlook and MS no hide completly interface.
