### ISSUE TITLE
Deezer.com Anti-Adblock

### ISSUE THREAD

**Issue by claell** [uBlockOrigin/uAssets#7563]
### URL(s) where the issue occurs

deezer.com

### Describe the issue

Anti-Adblock message exceeds 100 px of height.

 

### Screenshot(s)

![grafik](https://user-images.githubusercontent.com/6171135/84787277-181f4080-afee-11ea-86b5-f6a604656151.png)

**Comment by krystian3w** [comment]
```
! https://forum.adguard.com/index.php?threads/deezer-com-antiadblock.21269/
@@||deezer.com^$generichide
```

**Comment by krystian3w** [comment]
maybe also works:

`deezer.com##+js(nofab)`

**Comment by mapx-** [comment]
no issue on my end - tested FF / chrome (and different ips)

blocked items:

![image](https://user-images.githubusercontent.com/10303732/84800958-d9de4d00-affe-11ea-8a8f-1247f1a3543d.png)

**Comment by mapx-** [comment]
@claell provide all the requested info (browser, uBO versions, test only using uBO default settings / lists)

**Comment by claell** [comment]
@mapx- I am using Firefox, most current version, uBO most current version, default settings and lists.

This is only on the Annoyances list and I suggest to add it onto the default list (coming from https://github.com/uBlockOrigin/uBlock-issues/issues/1111#issuecomment-644766812). Sorry that I did not make that clear in the first place.

**Comment by mapx-** [comment]
well, like outlook, it will stay in annoyances list, soft (warning) anti adb

**Comment by claell** [comment]
Since this is a bit confusion and I expected otherwise, is there documented criteria for differentiating between soft and hard anti-adb and what exactly goes onto the annyoances list vs. lists that are enabled by default? I could not really find any.

**Comment by uBlock-user** [comment]
@claell https://twitter.com/gorhill/status/1072990091625328641 & https://twitter.com/gorhill/status/1072991301237440513

**Comment by claell** [comment]
This is about blocker walls and does not include the differentiation between soft and hard anti-adb. Was it included in the tweet that this was a reply to? I don't see that, unfortunately.

**Comment by uBlock-user** [comment]
> This is about blocker walls

No, this is about anti-adblock and other such anti-user mechanisms.

**Comment by claell** [comment]
It does not seem to be, this is the whole tweet:

> About "uBlock [Origin] has a pretty firm stance on these popups under its manifesto"
> 
> uBO's stance regarding anti-blocker wall: if it is dismissable, it will not be foiled in uBO's default lists. If not dismissable, it will be deemed anti-user and foiled in uBO's default lists.

Where is this about differentiating between soft and hard anti-adb? It is talking about which anti-blocker walls are allowed and which aren't. That is different from defining what constitutes soft vs. hard anti-adb in general and there is also no criteria given to what lists filters for those respective categories go.

Second tweet for reference:

> Twist: if the anti-blocker wall is dismissable but constantly reappear at every page load on a site, it will also be deemed anti-user.

**Comment by uBlock-user** [comment]
> soft and hard anti-adb?

Those terms are never used amoung the uBO team, so you won't find them anywhere.

**Comment by claell** [comment]
Alright, did not now that, although I'd actively doubt it has literally been never used.

However my actual point still stands. The tweets are only about anti-adblock walls and not about banners or other stuff at all, which leaves a policy missing for banner related stuff. Plus I don't think a tweet is a good source for a policy.

**Comment by Yuki2718** [comment]
> 
> Those terms are never used amoung the uBO team, so you won't find them anywhere.

Nevertheless, I found the terms are convenient. If they were invented by @llacb47 I'd like to give him a prize lol ;)
