### ISSUE TITLE
meineorte.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#7566]
### URL(s) where the issue occurs

`https://www.meineorte.com/p/7xlehb/daenemark-das-passiert-wenn-du-mit-25-noch-unverheiratet`

### Describe the issue

ad pictures

### Screenshot(s)

<img width="1095" alt="Unbenannt3" src="https://user-images.githubusercontent.com/48647394/84864317-bd7df700-b076-11ea-9dd5-15625c043e25.PNG">

### Versions

- Browser/version: Firefox 77.0.1
- uBlock Origin version: v1.27.10

**Comment by sugarfreesweetener** [comment]
ads
