### ISSUE TITLE
zeit.de

### ISSUE THREAD

**Issue by bandi88** [uBlockOrigin/uAssets#7567]
### URL(s) where the issue occurs

`https://www.zeit.de/zustimmung?url=https%3A%2F%2Fwww.zeit.de%2Fkarriere%2Fberuf%2F2011-12%2Ffaq-ehrenamt-arbeitsrecht`

### Describe the issue

Website try to force visitors to disable ad-blocker.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/23141180/84881095-b1e9fa80-b08d-11ea-8e1f-6de58e26380b.png)

### Versions

- Browser/version: Google Chrome 83.0.4103.97
- uBlock Origin version: 1.27.10

### Settings

Used with Nano Defender together.

**Comment by JobcenterTycoon** [comment]
Look like a GDPR overlay

**Comment by bandi88** [comment]
@JobcenterTycoon, you may have right, but not exactly. It is both GDPR-overlay and anti adblocker together. Therefore the uBlock origin has to handle this.

**Comment by mapx-** [comment]
I get that screen even without uBO

**Comment by uBlock-user** [comment]
Neither, GDPR nor anti-adblock, server-sided consent wall, can't be fixed.

**Comment by uBlock-user** [comment]
same as https://github.com/uBlockOrigin/uAssets/issues/5626

**Comment by okiehsch** [comment]
It is a GDPR modal click "hier" to go to the sites specific data protection declaration.
It has nothing to do with adblockers.
