### ISSUE TITLE
dailyuploads.net

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#7568]
### URL(s) where the issue occurs

`https://dailyuploads.net/9jgsmhjz6fru`

### Describe the issue

Keeps opening new tab when i click anywhere

### Screenshot(s)

N/A

### Versions

- Browser/version: Opera 68.0.3618.125
- uBlock Origin version: 1.27.10

### Settings

- Default

**Comment by ghajini** [comment]
`https://dailyuploads.net/56eyjgghgzuv`

push notification ads
update existing scriptlet filters

**Comment by llacb47** [comment]
`$3p,domain=dailyuploads.net,denyallow=google.com|gstatic.net` ?

**Comment by ghajini** [comment]
crushing the ads

`dailyuploads.*#@#+js(abort-current-inline-script, Math, zfgloaded)`
`$3p,domain=dailyuploads.net,denyallow=google.com|gstatic.net`
`dailyuploads.*##+js(abort-current-inline-script, String.fromCharCode, btoa)`
`dailyuploads.net##+js(acis, Math, XMLHttpRequest)`
