### ISSUE TITLE
Ultrahorny.com blocking UBO

### ISSUE THREAD

**Issue by thrwat** [uBlockOrigin/uAssets#757]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

ultrahorny.com

### Describe the issue

UBO is getting blocked.

### Versions

- Browser/version: Chrome 61
- uBlock Origin version: latest

### Settings

Default

### Notes

They seem to be using a custom solution...

**Comment by SMed79** [comment]
@thrwat Please warn about NSFW content http://i.imgur.com/kAY9lrE.png !!!
