### ISSUE TITLE
Tweakers.net cookie wall

### ISSUE THREAD

**Issue by notDavid** [uBlockOrigin/uAssets#7576]
### URL(s) where the issue occurs
`https://tweakers.net/`

### Describe the issue
`tweakers.net` is already listed in the "EasyList Cookie List". However it does not work from everywhere: the cookie wall/popup is still displayed.

### Screenshot(s)
https://imgur.com/jcr4EuP

### Versions
- Browser/version: [Firefox 77.0.1]
- uBlock Origin version: [v1.27.10]

### Notes
If i open this website in the TorBrowser, and start clicking the "New circuit for this site" button, i notice that they are displaying a different cookie banner/wall depending on your IPs originating country;
1. For Netherlands and Germany for example, they are displaying the "cookie wall" (or whatever it's called) as shown in the screenshot
2. For other countries they are displaying a simple light-blue cookie banner

"2" is being blocked by the "EasyList Cookie List , "1" is not being blocked.

Is it possible to block "1" with uBlock Origin ?

**Comment by uBlock-user** [comment]
Server-sided cookie wall, blocking it results in site breakage.

**Comment by krystian3w** [comment]
Fixed in Addon `I don't care about cookies`.

@DandelionSprout  you converted script for this domain to "`nanop-set-cookie`" or "`nanop-click-element-on-ready`" for Nano Adblocker users?

**Comment by krystian3w** [comment]
I found this for `Nano Adblocker` users:

`tweakers.net##+js(nanop-click-elements-onready, #cookieAcceptForm button[value="accept"])`

in Nano Annoyance.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/pull/2099 - old discussion.

> For other countries they are displaying a simple light-blue cookie banner

Poland 🇵🇱 have server side cookie wall.

**Comment by DandelionSprout** [comment]
There was a conversion at one point, but Jspenguin's rules for allowing lists to use `##+js(nanop-` were so ultra-strict that the permission process ended up in a standstill, and the list was deleted after ~6 months.

**Comment by notDavid** [comment]
Thanks all for your replies, too bad it can't be blocked with uBO.

@krystian3w Nano Adblocker + Nano Annoyance works indeed, thanks.

Also installing the [I don't care about cookies](https://www.i-dont-care-about-cookies.eu) extension blocks this.

**Comment by uBlock-user** [comment]
> Also installing the I don't care about cookies extension blocks this.

It's clicking the button for you same as Nano does as mentioned in https://github.com/uBlockOrigin/uAssets/issues/7576#issuecomment-646874479 , no extension can block it without causing site breakage.
