### ISSUE TITLE
gofundme.com sub-page is complete empty if uBlock Origin is on

### ISSUE THREAD

**Issue by bandi88** [uBlockOrigin/uAssets#7578]
### URL(s) where the issue occurs

`https://www.gofundme.com/c/fundraising-tips/sharing`

### Describe the issue

If the uBlock Origin is on, then the page above cannot be loaded (is simply empty, see screenshot). After temporary deactivate the UBO, then the page loads.

### Screenshot(s)

With UBO ON: 
![image](https://user-images.githubusercontent.com/23141180/85196594-73497f80-b2db-11ea-85ba-7ab8c5ed532d.png)

With UBO OFF: 
![image](https://user-images.githubusercontent.com/23141180/85196601-82303200-b2db-11ea-9f57-93bb0e7ea33f.png)

### Versions

- Browser/version: Google Chrome 83.0.4103.97
- uBlock Origin version: 1.27.10

### Settings

Used with Nano Defender together.

**Comment by mapx-** [comment]
broken by fanboy's annoyances list - not part of the default setup

add
`gofundme.com#@#.sharing`

@ryanbr
