### ISSUE TITLE
Frankfurter Allgemeine

### ISSUE THREAD

**Issue by RockyMM** [uBlockOrigin/uAssets#758]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[http://www.faz.net/aktuell/politik/]`

### Describe the issue

The content is visible for a short while, but after couple of seconds it is replaced with a warning in German to either turn off "adblock", install their own adblock or to log in.

### Screenshot(s)

<img width="984" alt="screen shot 2017-10-12 at 23 23 22" src="https://user-images.githubusercontent.com/1906065/31519929-62a99706-afa4-11e7-8fca-d3ce1c49a0ce.png">

### Versions

- Browser/version: Safari 10.1.1 
- uBlock Origin version: 1.10.0

**Comment by mapx-** [comment]
add
`@@||faz.net^$generichide`

**Comment by okiehsch** [comment]
@RockyMM I do not have Safari and this is already fixed using Chrome or Firefox on my end, so I would
need to know if `@@||faz.net^$generichide` works for you.

@mapx- did you test with Safari?

**Comment by mapx-** [comment]
no, I disabled ublock filters and it needs only the generichide filter.
Probably uBo on safari cannot use the same advanced (injecting) filters ?!

**Comment by Hrxn** [comment]
> Versions
Browser/version: Safari 10.1.1
uBlock Origin version: 1.10.0

Also, this is a pretty old version of uBO for Safari.

**Comment by okiehsch** [comment]
`generichide` is indeed sufficient, I did not check when I added
`faz.net##script:inject(abort-current-inline-script.js, $, _sp_._networkListenerData)`
That fix also disables `doubleclick` and `0914.global.ssl.fastly` requests, so I will keep it.

**Comment by RockyMM** [comment]
Sorry, the notifications are not coming through for me for some reason. I'll try updating uBO and test it out again.
