### ISSUE TITLE
americastestkitchen paywall block

### ISSUE THREAD

**Issue by pepablock** [uBlockOrigin/uAssets#7580]
### URL(s) where the issue occurs

`https://www.americastestkitchen.com/recipes/10906-easy-pancakes`

### Describe the issue

annoying paywall that blurs the recipe...

### Screenshot(s)

—

### Versions

- Browser/version: Firefox 77.0.1
- uBlock Origin version: v1.27.10

### Settings

default settings

### Notes

—

**Comment by uBlock-user** [comment]
Circumventing a paywall is considered [out of scope](https://github.com/uBlockOrigin/uAssets/issues/2317#issuecomment-392009540).
