### ISSUE TITLE
Block youtube's "stay at home" promoted channels

### ISSUE THREAD

**Issue by andradadad** [uBlockOrigin/uAssets#7581]
### URL(s) where the issue occurs

youtube.com

### Describe the issue

Youtube's mainpage seems to be promoting lgbt content and black lives matter related stuff, which a lot of them looking quite racist and gender disorienting. Cosmetic filtering doesn't seem to catch their specific box, and are very generic in names.
![git](https://user-images.githubusercontent.com/52493254/85208924-6b550400-b30a-11ea-856f-1baf0a4c9467.jpg)
 

### Versions

- Browser/version: 78.0b9 (64-bit)
- uBlock Origin version: 1.27.10

### Settings

-

### Notes

Adding "###content > .ytd-rich-section-renderer.style-scope" in the pick up tool, blocks my personal youtuber posts in their profile pages.

**Comment by krystian3w** [comment]
try use:

```
###content > .ytd-rich-section-renderer.style-scope:has-text(Assista e Aprenda)
```

if `#content > .ytd-rich-section-renderer.style-scope` hide too much.

**Comment by krystian3w** [comment]
Poland 🇵🇱 🇪🇺 🌍 have promotion "live" concerts:

> ![obraz](https://user-images.githubusercontent.com/35370833/85209243-96ede380-b336-11ea-9895-95a72febd769.png) |
> --- |

**Comment by uBlock-user** [comment]
Those are YT recommendations/suggestions and they appear only after user watches a video of that category.

**Comment by andradadad** [comment]
No, I never watched anything of that category. This is a common issue reported by thousands of users recently.
I don't understand why you **closed** the issue. Is it because you support youtube's corporativism?

I don't like that "first-page" recommended youtubers, and there's no other word than ADS.
Blocking advertising is the only reason of this software, not supporting partisan militancy.

**Comment by llacb47** [comment]
Just block it yourself. It's not an ad. And please show me where thousands of users reported it. On the easylist repo, where you should've reported this? 

![image](https://user-images.githubusercontent.com/16567977/85210307-cab41380-b30c-11ea-8566-57ee51b7bc12.png)

**Comment by uBlock-user** [comment]
> I don't like that "first-page" recommended youtubers

So add the filter as suggested to my filters. Recommended videos !== ADS.
