### ISSUE TITLE
iseekgirls.com [NSFW]

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#7585]
### URL(s) where the issue occurs

`https://www.iseekgirls.com/2013/12/20/bailey-knox-rubbing-pussy-nude-video/`
`https://www.iseekgirls.com/2020/06/17/gabbie-carter-big-natural-tits-riding-dick-property-sex/`

### Describe the issue

[15 second ad when starting video.]

### Versions

- Browser/version: [Chrome v83]
- uBlock Origin version: [1.27.0]

### Settings
[default]

**Comment by uBlock-user** [comment]
@gorhill
