### ISSUE TITLE
elitepvpers shows ads

### ISSUE THREAD

**Issue by nuttenpreller** [uBlockOrigin/uAssets#7586]
`https://www.elitepvpers.com/forum/elite-gold-trading/4778720-erfahrung-mit-telegram-bots-b-e-g-geld.html`
![Screenshot_2020-06-23 Erfahrung mit Telegram Bots (B) e g Geld](https://user-images.githubusercontent.com/67310926/85373814-1bf21c00-b534-11ea-9b79-622a2eac18ed.png)

**Comment by mapx-** [comment]
classic ads, to be reported / added in easylist list

@ryanbr
