### ISSUE TITLE
chip.de 

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#7589]
### URL(s) where the issue occurs

`https://www.chip.de/news/Bereits-vor-dem-1.-Juli-Preise-in-Supermaerkten-veraendern-sich-drastisch_182780453.html`

### Describe the issue

I can’t play the video i get only a blank screen

### Screenshot(s)
<img width="624" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/85397047-266fde00-b553-11ea-9b42-6e0c86b90c66.PNG">

### Versions

- Browser/version: Firefox 77.0.1 
- uBlock Origin version: v1.27.10

### Settings

[settings.txt](https://github.com/uBlockOrigin/uAssets/files/4818942/settings.txt)

### Notes

`||svonm.com/hd-main.js$script,important,domain=chip.de|cinema.de|cdnapi.kaltura.com` is the problem filter for me but when i whitelist it i get video ads back

**Comment by okiehsch** [comment]
Does
`chip.de##+js(json-prune, enabled, force_disabled)`
work for you?
It takes a while for the video to load on my end but I don't get any pre roll ads.

**Comment by JobcenterTycoon** [comment]
Yes

**Comment by JobcenterTycoon** [comment]
i have again breakage (its not the new filter i disabled every +js filter but i still can’t play videos)

**Comment by okiehsch** [comment]
> i disabled every +js filter but i still can’t play videos)

Hm, `chip.de#@#+js(aopw, _sp_)` works for me.
Example link:
`https://www.chip.de/news/Kali-Linux-2020-Jetzt-laeuft-es-unter-Windows-10_113646719.html`

**Comment by JobcenterTycoon** [comment]
ok now for me too after a cookie accept

**Comment by okiehsch** [comment]
`+js(aopw, _sp_)` was added to defuse an anti adblock wall but I don't see one on my end at the moment.

**Comment by JobcenterTycoon** [comment]
Now i get the same issue like https://github.com/uBlockOrigin/uAssets/issues/7872
Its not possible to play the video without cookie accept but the site `cdn-217.privacy-mgmt.com` is blocked.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/61907#issuecomment-687306455

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/6587
