### ISSUE TITLE
Middle click issues closes windows

### ISSUE THREAD

**Issue by mihp** [uBlockOrigin/uAssets#759]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://www.triglav.si/zavarovanja/posamezniki/zavarovanja_na_potovanjih/zdravstveno-zavarovanje-na-potovanjih-v-tujini-z-asistenco/zdravstveno-zavarovanje-na-potovanjih-v-tujini-z-asistenco`

### Describe the issue

1. Open the above URL
2. Middle click the red button with text "Sklenite zavarovanje - popust do 20 %" that leads to https://skleni.triglav.si/isklepanje/zdravstveno/

Expected result: The link should open in new tab
Actual result: The link opens in a new tab AND the current window is closed. To the user it looks like the link was opened in the same tab and tab history deleted, because the back button is disabled (no history).
--

### Screenshot(s)

No screenshots.

### Versions

- Browser/version: Firefox Nightly 58.0a1 (2017-10-12) (64-bit)
- uBlock Origin version: uBlock Origin 1.14.14

### Settings

- None

### Notes

- If I turn uBlock Origin off, the behaviour is as expected.
- I have noted this unwanted behaviour with middle click on other sites, too.

**Comment by gwarser** [comment]
`||triglav.si/$popup` found in: SVN: Slovenian List?

**Comment by mihp** [comment]
If the link is opened with uBlock Origin disabled, it doesn't open in new window or pop-up.
If this link is blocked (I see no reason for it) then I would expect the link to be blocked, not as is now: the link opens, but the original widow closes.

**Comment by gwarser** [comment]
Fixed in [1.14.15b1](https://github.com/gorhill/uBlock/releases/tag/1.14.15b1)
