### ISSUE TITLE
fulltube.online

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#7590]
### URL(s) where the issue occurs

`https://fulltube.online/love-aaj-kal-2-2020/`

### Describe the issue

Popup ads

### Versions

- Browser/version: firefox A.
- uBlock Origin version: 1.27.10

### Settings

uBO's default settings
-

**Comment by uBlock-user** [comment]
Does `fulltube.online##+js(acis, Math, delete)` work for you ?

**Comment by okiehsch** [comment]
>Does fulltube.online##+js(acis, Math, delete) work for you ?

Works too.

**Comment by ghajini** [comment]
All works good

**Comment by ghajini** [comment]
Over here `https://fulltube.online/khuda-haafiz-2020/`

server 1 when playing video clicked in gives ads (`player.opencd.xyz/e/Ykk2QkpVclBPWG5WVUl5dDRRajBqZz09`)

opera browser stable ublock origin dev
