### ISSUE TITLE
Impostor/scam sites of 9anime.to

### ISSUE THREAD

**Issue by Dobidop** [uBlockOrigin/uAssets#7597]
URL(s) where the issue occurs

```
https://9animes.ru
https://www1.9animes.io
https://www.9anime.nl
```

Describe the issue

These are impostor/scam sites which either completely or partially replicate the site 9anime.to (all official URLs can be found in their official subreddit https://www.reddit.com/r/9anime/). These sites allow for member logins, potentially stealing usernames and passwords.

If nothing else users could be warned of these sites.

**Comment by mapx-** [comment]
> potentially stealing usernames and passwords.

Report real / demonstrable issues, provide the steps to reproduce such issues.
