### ISSUE TITLE
[NSFW] txxx.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7599]
### URL(s) where the issue occurs

`https://txxx.com/videos/1455129/the-nampa-tsurekomi-hidden-camera-118-yuzunashi-25-year-old-hobo-s/`

### Describe the issue

The video broken only on Firefox.

### Screenshot(s)

![txxx-fx](https://user-images.githubusercontent.com/58900598/85851299-5e904e80-b7e9-11ea-8880-320a7630d010.png)

### Versions

- Browser/version: Firefox 77.0.1
- uBlock Origin version: 1.27.10

### Settings

- Default

### Notes

The culprit is `||txxx.*^$csp=script-src  'self' 'unsafe-eval' 'unsafe-inline'`, but no problem on Brave on my end. Badfiltering the rule causes many ads to be loaded though they're hidden by cosmetic filters:

<details>
![txxx-fx-no-ehide](https://user-images.githubusercontent.com/58900598/85851441-a616da80-b7e9-11ea-9935-bffa1730fb0a.png)
</details>

It seems
`txxx.com##+js(set, adver, noopFunc)`
works, and I suggest to expand it to
`hclips.com,txxx.com,vjav.com##+js(set, adver, noopFunc)`
as in the other two domains the rule blocks those hidden by `##.__nat_link`, saving bandwidth.

**Comment by mapx-** [comment]
test the committed filter

**Comment by Yuki2718** [comment]
@mapx- Working fine!
