### ISSUE TITLE
NSFW pornhub.com unblock user broken by uBlock filters

### ISSUE THREAD

**Issue by sdfasdfgawe456h4356** [uBlockOrigin/uAssets#760]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.pornhub.com/user/blocks#`

### Describe the issue

With "uBlock filters" enabled i cant unblock users on the provided website. It jumps back to top of the website when i click the button.

### Screenshot(s)

would be useless the website looks normal the button just doesnt work.

### Versions

- Browser/version: Firefox 52.4.0 ESR
- uBlock Origin version: 1.14.14 legacy

### Settings

only uBlock filters enabled

### Notes

You obviously need a pornhub account and need to block at least one user in order to reproduce.

**Comment by mapx-** [comment]
still in trouble ? provide what's blocked while doing that operation.

**Comment by mapx-** [comment]
tested FF ESR 52.5.0 (64-bit), default setup in uBo 1.14.14, all fine here.
