### ISSUE TITLE
gamebrew.org

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#7600]
### URL(s) where the issue occurs

`https://www.gamebrew.org/wiki/BoltThrower`

### Describe the issue

Anti-Adblock Script - BlockAdBlock

### Versions

- Browser/version: Firefox 77.0.1
- uBlock Origin version: 1.27.11rc7

### Settings

- Default filters

**Comment by garry-ut99** [comment]
Again:

![ss](https://user-images.githubusercontent.com/72945564/215479435-ef4f7a04-f243-489f-bf05-f501e1898db4.png)
