### ISSUE TITLE
drtuber.com [NSFW]

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7601]
### URL(s) where the issue occurs

`https://www.drtuber.com/`

### Describe the issue

A popup on clicking any video

### Screenshot(s)

<details>
![drtuber](https://user-images.githubusercontent.com/58900598/85908368-bf527200-b84f-11ea-809c-5d7922d1fa18.png)
</details>

### Versions

- Browser/version: Brave 1.10.97
- uBlock Origin version: 1.27.10

### Settings

- Default

### Notes

`drtuber.com##+js(window.open-defuser)` works.

**Comment by ghajini** [comment]
NSFW
`https://www.drtuber.desi/video/3708726/sexy-couple-doing-sex-found-each-on-hotcamgirls-in`

popup ads

**Comment by mapx-** [comment]
self-promotion
