### ISSUE TITLE
atlaq.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7604]
### URL(s) where the issue occurs

`https://basketballking.jp.atlaq.com/`
(Just an example, you can search for any domain on `https://atlaq.com/`)

### Describe the issue

Annoyance: drag disabled 

### Versions

- Browser/version: Firefox 77.0.1
- uBlock Origin version: 1.27.10

### Settings

- Default + uBlock Annoyances

### Notes

`atlaq.com##+js(aeld, mousedown, document)` works.

**Comment by mapx-** [comment]
it's not an annoyance but a side effect of zfg crap

**Comment by uBlock-user** [comment]
This would be the first one of its kind where I don't see any popups or popunders.

**Comment by Yuki2718** [comment]
Ah, thought the scripts are too complicated for anti-drag. Thx for clarification.
