### ISSUE TITLE
racefans.net antiadblock

### ISSUE THREAD

**Issue by gerry1gerry** [uBlockOrigin/uAssets#7605]
### URL(s) where the issue occurs

`https://www.racefans.net/2020/05/29/williams-considering-sale-of-team-and-announces-immediate-termination-of-rokit-sponsorship-deal/`

### Describe the issue

some warnings on the page about disabling ad block

### Versions

- Browser/version: Firefox 77.0.1
- uBlock Origin version: 1.27.10

### Settings

default
-

**Comment by mapx-** [comment]
Enable `uBlock filters – Annoyances`, warning already fixed
