### ISSUE TITLE
glomex problems once again

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#7607]
hello,
I've got problems with glomex video player once again..

I mean in the following two url addresses for example:

`https://www.real.gr/athlitismos/arthro/pio_konta_ston_ypobibasmo_h_magiorka_binteo-649594/`

`https://www.sport24.gr/football/Spain/PrimeraDivision/thelta-mpartselona-2-2-odynhrh-gkela-gia-toys-mplaoygkrana.5725766.html`

the video doesn't even show up,
![image](https://user-images.githubusercontent.com/24896778/85942140-2c3d3900-b930-11ea-9a16-4af689a41011.png)

I've found out that it only plays if/when I whitelist:
`player.glomex.com##+js(set, Promise.race, noopFunc)` (ublock filters)

but in this case I'm seeing ads in the player,

so please check and fix

**Comment by DandelionSprout** [comment]
Since the videos are region-locked, that would probably cause at least some delays in figuring out better entries. Hopefully someone on the fulltime uAssets team have VPNs with Greek servers.

At least I found some placeholders and sponsored links that I'll try to submit to *Greek Adblock Filter*.

**Comment by lain566** [comment]
This filter should block ads, but it only works with dev version.
`player.glomex.com##+js(json-prune, [].schedule.start.[].url)`
