### ISSUE TITLE
animenewsnetwork.cc

### ISSUE THREAD

**Issue by CelticMinstrel** [uBlockOrigin/uAssets#761]
It's basically a synonym for `animenewsnetwork.com`, but filtering does not occur at all. The rules for `animenewsnetwork.com` need to be applied also for `animenewsnetwork.cc`.

I have uBlock Origin 1.13.8, though I doubt that's relevant.

**Comment by okiehsch** [comment]
> The rules for `animenewsnetwork.com` need to be applied also for `animenewsnetwork.cc`.

`uAssets` has no filters for `animenewsnetwork.com`, so this is an `EasyList` issue.
@ryanbr fyi

**Comment by CelticMinstrel** [comment]
Suddenly started working again, so I guess he must've fixed it.
