### ISSUE TITLE
youav.com [NSFW]

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7610]
### URL(s) where the issue occurs

`https://www.youav.com/video/15601/myba-003-%E4%BA%BA%E5%A6%BB%E3%81%AE%E8%8A%B1%E3%81%B3%E3%82%89%E3%82%81%E3%81%8F%E3%82%8A-%E6%A1%91%E7%94%B0%E3%81%BF%E3%81%AE%E3%82%8A`
`https://www.youav.com/video/34808/ssni-575-%E5%A4%B1%E7%A6%81-%E6%BD%AE%E5%90%B9%E3%81%8D-%E3%83%8F%E3%83%A1%E6%BD%AE%E3%82%B9%E3%83%97%E3%83%A9%E3%83%83%E3%82%B7%E3%83%A5-%E8%8A%B8%E8%83%BD%E4%BA%BA%E3%81%AE%E5%A4%A7%E5%A4%A7%E5%A4%A7%E6%B4%AA%E6%B0%B4%E3%82%AA%E3%83%BC%E3%82%AC%E3%82%BA%E3%83%A0-%E3%81%B2%E3%81%AA%E3%81%9F%E3%81%BE%E3%82%8A%E3%82%93`

(Any videos on `https://www.youav.com/`)

### Describe the issue

Infinite blockages of undefined scripts causes either significant delay for video playing or no start at all only on Firefox. See https://github.com/easylist/easylist/issues/5613, reported here thx to @llacb47 's advice. 

### Screenshot(s)

![youav](https://user-images.githubusercontent.com/58900598/86007787-db723100-ba52-11ea-9548-14410be552f6.png)

### Versions

- Browser/version: Firefox 77.0.1
- uBlock Origin version: 1.27.10

### Settings

- Default

### Notes

In the above EasyList issue I mentioned
`$script,third-party,domain=youav.com`
but more exactly blocking `displayvertising.com` causes this. Probably you guys and llacb47 know better.

**Comment by Yuki2718** [comment]
@mapx- Thanks, now working fine!

**Comment by Yuki2718** [comment]
Is badfilter still needed? With the added rules I don't see requests to displayvertising.com.

**Comment by mapx-** [comment]
The video was broken for me and that filter is blocking legitimate stuff
```
https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js
https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js
```

**Comment by Yuki2718** [comment]
Ah okay, probably that's IP/geo-dependent staff.
