### ISSUE TITLE
kissanime.monster

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7611]
### URL(s) where the issue occurs

`https://kissanime.monster/watch-movie/girls-und-panzer-der-film-sub-eng/lTLZs59S/uiHh5RIo-watch-free.html`

### Describe the issue

Fantastically many ads and annoyances

### Screenshot(s)

![kissanime1](https://user-images.githubusercontent.com/58900598/86019247-56424880-ba61-11ea-998d-9cba42f9bd25.png)

![kissanime2](https://user-images.githubusercontent.com/58900598/86019264-593d3900-ba61-11ea-8983-c4e844c20616.png)

### Versions

- Browser/version: Brave 1.10.97
- uBlock Origin version: 1.27.10

### Settings

- Default + Fanboy Annoyances + uBlock Annoyances

**Comment by mapx-** [comment]
```
*.gif$domain=kissanime.monster,image
kissanime.monster##[href="/user/profile/premium-membership"]
kissanime.monster##.ico.close
kissanime.monster##.hhotnews
kissanime.monster##.aattention
```

@ryanbr

**Comment by Yuki2718** [comment]
Middle of the first SS.
`kissanime.monster##._animeKiss > div > div > div > div:has-text(Favorites)`
or
`kissanime.monster##a[id] + div`
or something.

**Comment by Yuki2718** [comment]
@mapx- It turned out EL hasn't addressed these annoying popup/messages. Could you please temporary add the rules suggested in https://github.com/easylist/easylist/issues/5773#issuecomment-662524233 or whatever their equivalents?

**Comment by mapx-** [comment]
added

**Comment by terryecwid** [comment]
Hello,
This is Terry from Ecwid Team. Ecwid is an eCommerce solution: [https://www.ecwid.com/](url)
In this Issue, you've blocked one of our CDN — dpbfm6h358sh7.cloudfront.net 
A screenshot: [https://ecwid.d.pr/bgX1Bf](url) 
We use it for the images of our Instant Sites, and not for ads or tracking. 
I should say, the reported store — kissanime.monster — is built NOT on Ecwid. They are not our customers. 
Please unblock our CDN dpbfm6h358sh7.cloudfront.net, millions of our merchants use our Instant Sites and this issue affects them. 
Thank you!

**Comment by mapx-** [comment]
We are not blocking `dpbfm6h358sh7.cloudfront.net` , it's easylist blocking it. 

@ryanbr

**Comment by stephenhawk8054** [comment]
A kissanime site seems can't play the video:
`https://kissanime.si/Anime/douluo-dalu-2nd-season-sub.57391/Episode-007?id=151563`

The video player is stuck at this screen:

![image](https://user-images.githubusercontent.com/66517106/141663977-c796834e-f3ce-404c-b8c4-85d0c1ae9100.png)

Firefox 94.0.1, ublock 1.38.6 default.

If I allow these subdocument and scripts, it can play normally, but I'm not sure if it can cause any ads or not.

```
@@||geoip.redirect-ads.com^$subdocument,domain=kissanime.si
@@||geoip.redirect-ads.com/js/*$script,1p
```

**Comment by mapx-** [comment]
@ryanbr
