### ISSUE TITLE
piwik.pro domain blocked 

### ISSUE THREAD

**Issue by Marcin-PiwkPRO** [uBlockOrigin/uAssets#7613]
### URL(s) where the issue occurs

`https://piwik.pro/`

### Describe the issue

uBlockOrigin blocks all the URLs containing "/piwik.". It's a problem for us becouse the company is called "Piwik PRO" and so is the domain. uBlockOrigin blocks scrypts, stlyes and pictures on our website making it unoperable for the users.  

### Screenshot(s)

![ublockorigin](https://user-images.githubusercontent.com/67640881/86130745-e675a180-bae4-11ea-90eb-c295e3721251.png)

### Versions

- Browser/version: Google Chrome 83.0.4103.116
- uBlock Origin version: uBlock Origin 1.27.10

### Settings

uBlockOrigin on default settings. 

### Notes

We suggest changing default filter settings to not block "Piwik.pro" the domain.

**Comment by mapx-** [comment]
@ryanbr

**Comment by Marcin-PiwkPRO** [comment]
@mapx- @ryanbr

**Comment by Marcin-PiwkPRO** [comment]
@mapx- @ryanbr <br> there's another filter blocnikg our webiste. Can you make another exception?
![piwik-pro](https://user-images.githubusercontent.com/67640881/86455001-502dbf80-bd20-11ea-9b98-9e295e5c729a.png)
