### ISSUE TITLE
rt.pornhub.com NSFW

### ISSUE THREAD

**Issue by electrifying** [uBlockOrigin/uAssets#7616]
`https://rt.pornhub.com/view_video.php?viewkey=ph5e9f62ee68179`

`

### Describe the issue

when you click on the link and click on the video, it will start playing as usual, but if you select any video from the block on the right, open it, it will stop starting and there will be no preview image on it. Or it will start, but only 3 or 4 times.

### Screenshot(s)

`https://imgur.com/pr3mbuw`

### Versions

- Browser/version: google chrome 83
- uBlock Origin version: 1.27.10

### Settings

default ubo settings

### Notes

none

**Comment by electrifying** [comment]
if you can’t reproduce the problem, maybe you need Russian ip

**Comment by mapx-** [comment]
I cannot reproduce the issue, when choosing a russian ip is asking some kind of check on age ?!

Perhaps @dimisa-RUAdList could tell more about

**Comment by electrifying** [comment]
> choosing a russian ip is asking some kind of check on age ?!

use this rules 
pornhub.com##div[id^="age-verification"]

**Comment by dimisa-RUAdList** [comment]
https://hg.adblockplus.org/ruadlist/rev/5b852134c09a#l1.12

**Comment by mapx-** [comment]
tested with russian ip too, no issues FF / chrome on my end

**Comment by uBlock-user** [comment]
@electrifying That filter is already present in RUAdlist.
