### ISSUE TITLE
Spotify banner ads container not blocked

### ISSUE THREAD

**Issue by PantherJohn** [uBlockOrigin/uAssets#7620]
### URL(s) where the issue occurs

```
open.spotify.com
```

### Describe the issue

Not exactly an issue. Rather I'm asking you guys to add the following rule to the default filters to get rid of the blank ad container at the bottom of the page. 
```
open.spotify.com##.Root__main-view > :not(.main-view-container)
```

### Screenshot(s)

Well the page will come off a lot cleaner as you can imagine.

### Versions

- Browser/version: Latest
- uBlock Origin version: Latest

### Settings

- None

**Comment by Yuki2718** [comment]
Although the suggested rule shows 2 hits, I don't see any change by adding the rule. Does it requires login?

**Comment by krystian3w** [comment]
Yes need logon:

![obraz](https://user-images.githubusercontent.com/35370833/86407328-225f6100-bcb5-11ea-826d-fbc247566254.png)

**Comment by krystian3w** [comment]
EasyList can maybe add someting like this:

```
open.spotify.com#?#.Root__main-view > div:not([class]):not([id]):-abp-has(> div[class*="-scss"] > div > iframe#leaderboard-ad-element)
```
![obraz](https://user-images.githubusercontent.com/35370833/86407948-4e2f1680-bcb6-11ea-83c1-93849bf6beb8.png)

**Comment by PantherJohn** [comment]
@krystian3w `:has` is sufficient to be honest.
```
open.spotify.com##.Root__main-view > div:not([class]):not([id]):has(> div[class*="-scss"] > div > iframe#leaderboard-ad-element)
```
