### ISSUE TITLE
cointelegraph.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7621]
### URL(s) where the issue occurs

`https://cointelegraph.com/news/bitcoin-based-payment-facilitator-purse-io-shuts-down`

### Describe the issue

Ads

### Screenshot(s)

![cointelegraph1](https://user-images.githubusercontent.com/58900598/86350210-5038ab80-bc9d-11ea-98d1-522213428533.png)

![cointelegraph2](https://user-images.githubusercontent.com/58900598/86350235-59297d00-bc9d-11ea-8825-2713ab24a3b8.png)

### Versions

- Browser/version: Brave 1.10.97
- uBlock Origin version: 1.27.10

### Settings

- Default

### Notes

Cosmetic filters work but I'm not comfortable that so many ads loaded in background.
`||cointelegraph.com/_nuxt/058e532e2e17ec3b0f8f.js`
blocks them perfectly but has side effects so I guess scriptlet can be used. Of note the site detects ad-blocker but
`cointelegraph.com##+js(set, adblockDisabled, true)`
doesn't help.

**Comment by uBlock-user** [comment]
Blocking that whole script could result in some functionality breakage. 
```
cointelegraph.com##a[href^="javascript:void"]
cointelegraph.com##.bnr-adbutler
```

works fine.

**Comment by Yuki2718** [comment]
Then how about adding
`||cointelegraph.com/images/1160_$image,1p`
`||cointelegraph.com/images/348_$image,1p`
? I don't see false positive but if that matters a regex rule will be possible instead, e.g.
`/images/(?:1160|348)_aHR0cHM6Ly9zMy5jb2ludGVsZWdyYXBoLmNvbS9zdG9yYWdlL3VwbG9hZHMvdmlldy[0-9a-zA-Z]{40,}5qcGc=\.jpg$/$image,domain=cointelegraph.com`

**Comment by gorhill** [comment]
The fix I committed does not work?

**Comment by llacb47** [comment]
It works. 

There is still an ad in the bottom right corner of homepage, should be handled by Easylist I guess.

![image](https://user-images.githubusercontent.com/16567977/86380419-0a0e2880-bc5a-11ea-803e-315a00d2f1ae.png)

**Comment by gorhill** [comment]
I can't reproduce this tradesanta ad on my side.

**Comment by Yuki2718** [comment]
@gorhill Sorry, I missed your commit. It works!

**Comment by llacb47** [comment]
Unblocked ads and tracking:
```
||vendo.cointelegraph.com^
||zoa.cointelegraph.com^
||sentry.cointelegraph.com^
```

**Comment by mapx-** [comment]
or
```
||*.cointelegraph.com^$xhr,1p
cointelegraph.com##.banner-blocked
```

**Comment by llacb47** [comment]
Well I think there is one subdomain we shouldn't block. I'm not at my computer anymore so I don't remember which it was

**Comment by Yuki2718** [comment]
@ryanbr 
So `||gp.cointelegraph.com^` needs to be replaced by `||vendo.cointelegraph.com^`. `||zoa.cointelegraph.com^` is a tracking pixel (image). `||sentry.cointelegraph.com^` bug report. There are other two first-party xhr that are `conpletus.cointelegraph.com` and `cointelegraph.com/api/v1/auth/check`, not sure if blocking them causes issue but that's likely as the site has login.

**Comment by llacb47** [comment]
`conpletus.cointelegraph.com` should not be blocked, looks like innocent graphql to me.

**Comment by llacb47** [comment]
@Yuki2718 in chrome and firefox it works fine

![image](https://user-images.githubusercontent.com/16567977/88601505-d64ad680-d03e-11ea-965b-e397500ee0c1.png)

![image](https://user-images.githubusercontent.com/16567977/88601589-04301b00-d03f-11ea-820c-3a73c0ffeba6.png)

**Comment by Yuki2718** [comment]
@llacb47 Sometimes hits, other times not regardless of browser:

![cointelegraph3](https://user-images.githubusercontent.com/58900598/88652582-fdb8a680-d105-11ea-9e5a-ef1e7006be2f.png)

![cointelegraph4](https://user-images.githubusercontent.com/58900598/88652587-00b39700-d106-11ea-97d0-c84a6d716314.png)

I also occasionally get the tradesanta you reported.

![cointelegraph](https://user-images.githubusercontent.com/58900598/88652627-1032e000-d106-11ea-92f1-6e03b43649b3.png)

![cointelegraph1](https://user-images.githubusercontent.com/58900598/88652746-30629f00-d106-11ea-80cb-f4ef197472fb.png)

Or a bit different one:

![cointelegraph2](https://user-images.githubusercontent.com/58900598/88652788-39ec0700-d106-11ea-9b17-6909d1400f95.png)

BTW how about adding `cointelegraph.com##.posts-listing__item:has(.nbr-adbutler)` for the front page?
