### ISSUE TITLE
EasyList breaks lanaciondigital.es

### ISSUE THREAD

**Issue by Jose1971AB** [uBlockOrigin/uAssets#7623]
Hi, good afternoon.
I don't know if my problem corresponds to this site, please tell me where it would correspond if it wasn't here 

### URL(s) where the issue occurs
`https://www.lanaciondigital.es/`

### Describe the issue
uBlock Origin EasyList filter breaks `https://www.lanaciondigital.es/`

I have tried disabling each filter I have in the configuration one by one and it seems that the only one that breaks the page is EasyList filter

 

### Screenshot(s)
**With EasyList filter activated**
https://user-images.githubusercontent.com/44229110/86403967-022ca380-bcaf-11ea-9262-13cec9ef4fa4.png

**With EasyList filter deactivated**
https://user-images.githubusercontent.com/44229110/86403995-0f499280-bcaf-11ea-9d56-6be3f54f78f9.jpg

### Versions

- Browser/version: [Firefox Browser 64-Bit v78.0.1]
- uBlock Origin version: [v1.27.10]

### Settings
https://user-images.githubusercontent.com/44229110/86404526-17560200-bcb0-11ea-8c3e-5b6add619228.PNG
https://user-images.githubusercontent.com/44229110/86404547-1f15a680-bcb0-11ea-8a47-aa6420dab3e4.PNG

-

**Comment by krystian3w** [comment]
CNAME issue:


```
!#if env_firefox
@@||pxys.ezoic.net^$image,css,script,domain=www.lanaciondigital.es
!#endif
```

**Comment by llacb47** [comment]
@krystian3w the logger literally shows that xhr is needed...
