### ISSUE TITLE
laredoute.nl and laredoute.lu media from CDN are blocked

### ISSUE THREAD

**Issue by noopole** [uBlockOrigin/uAssets#7629]
### URL(s) where the issue occurs

`https://www.laredoute.nl`
`https://www.laredoute.lu`

### Describe the issue

On the home pages of these 2 e-commerce websites, the images from cdn.laredoute.com are blocked while they should be displayed (it work correctly for other countries like `www.laredoute.be`)

### Screenshot(s)

n/a

### Versions

- Browser/version: All (Chrome, Firefox)
- uBlock Origin version: 1.27.10

### Settings
 
Defaults

**Comment by noopole** [comment]
I've corrected the initial post: the images that are blocked are coming from `https://cdn.laredoute.com/marketing`

**Comment by noopole** [comment]
I see in file easyprivacy.txt that some root domains have been whitelisted like laredoute.be or laredoute.com or laredoute.fr.
But the 2 laredoute.lu and laredoute.nl are missing.

Could they be added to the whitelist? Or is it managed by someone else?

**Comment by uBlock-user** [comment]
I don't see a single image from `laredoute.com` blocked as per the logger on either domains.

**Comment by noopole** [comment]
![image](https://user-images.githubusercontent.com/11869690/86483870-3fe40780-bd55-11ea-9c7e-f319693f5d3d.png)

Here is a screenshot

**Comment by noopole** [comment]
Maybe a per-language related list? (I don't konw if it exists...)

**Comment by uBlock-user** [comment]
That's from the devtools in Chrome, that won't tell you which extensions is blocking. Disable all other extensions and make sure you're on default settings in uBO, then try again.

**Comment by llacb47** [comment]
Also check the logger to see which rule is blocking it.

**Comment by noopole** [comment]
Thank you for the pieces of advice.

**Filter** `||laredoute.com/marketing/$3p,domain=~laredoute.be|~laredoute.ch|~laredoute.co.uk|~laredoute.com|~laredoute.es|~laredoute.fr|~laredoute.gr|~laredoute.hr|~laredoute.it|~laredoute.kr|~laredoute.ma|~laredoute.pl|~laredoute.pt|~laredoute.ru|~laredouteliban.com`

**Filter list**
`FRA: EasyList Liste FR `

https://cdn.laredoute.com/marketing/Studio/BE/AH19/AOUT/FORMATS/0108_BRADERIE/FR/btob2.jpg

![image](https://user-images.githubusercontent.com/11869690/86484590-d6fd8f00-bd56-11ea-999a-dbde4a747ace.png)

**Comment by mapx-** [comment]
@smed79

**Comment by uBlock-user** [comment]
Easylist FR adding filters for sites that're not-french(.nl and others) is what caused this issue and as to why they're doing is beyond me.

**Comment by noopole** [comment]
Ok thank you for your help. I posted a request on the Easylist forum https://forums.lanik.us/viewtopic.php?f=91&t=44852
... that is read by @smed79 in the end :-)

**Comment by krystian3w** [comment]
Firefox 78 added "blocked by uBlock Origin": https://www.ghacks.net/2020/05/24/firefox-78-comes-with-option-to-view-blocked-resources/

**Comment by noopole** [comment]
Thank you for the fix @uBlock-user !
