### ISSUE TITLE
uol.com.br

### ISSUE THREAD

**Issue by johnmathew2** [uBlockOrigin/uAssets#7630]
### URL(s) where the issue occurs
`https://www.uol.com.br/universa/noticias/redacao/2020/05/24/movel-em-lugar-errado-atrapalha-sono-mas-cristais-e-cores-ajudam-aprenda.htm`

### Describe the issue
Hide ads space on mobile page?
below the word 'publicidade'

### Screenshot(s)
`https://i.imgur.com/Bf07E09.png`

### Versions
- Browser/version: Firefox 78.0.1
- uBlock Origin version: 1.27.10

### Settings
FILTERS: AdGuard Mobile Ads, default uBlock, EasyList​​​​​, EasyPrivacy, ​​​​​Fanboy’s Enhanced Tracking List, Peter Lowe’s Ad and tracking server list, FRA: EasyList Liste FR, ​​​spa, por: AdGuard Spanish/Portuguese​.

**Comment by mapx-** [comment]
You should report here (the filter should be added in `AdGuard Mobile Ads`)
https://github.com/AdguardTeam/AdguardFilters/issues

working filter
`uol.com.br##.tm-ads`
