### ISSUE TITLE
emoji.gg - BlockAdBlock triggered

### ISSUE THREAD

**Issue by Ivan0xFF** [uBlockOrigin/uAssets#7631]
### URL(s) where the issue occurs
https://emoji.gg

### Describe the issue
A couple seconds after visiting the page, the entire content of it will be replaced with a BlockAdBlock message

### Versions
- Browser/version: Firefox 79.0b1
- uBlock Origin version: 1.27.10

### Notes
Adding the following custom filter fixes the page
`@@||emoji.gg^$ghide
emoji.gg###block-adb-not-enabled:style(display: block !important)
emoji.gg###block-adb-enabled
`

**Comment by krystian3w** [comment]
similar https://github.com/AdguardTeam/AdguardFilters/issues/58484
