### ISSUE TITLE
hdsector.to and mirrors

### ISSUE THREAD

**Issue by theinstantmatrix** [uBlockOrigin/uAssets#7635]
### URL(s) where the issue occurs

- `https://hdsector.theproxy.app/`
- `http://hdsector.siteunblocked.info/torrents-search.php`

### Describe the issue

- Popups
- Debugger abuse

### Versions

- Browser/version: Firefox 78.0.1
- uBlock Origin version: 1.28.1b3

### Settings

- Default filters

**Comment by llacb47** [comment]
```
/g12.js$domain=theproxy.app|siteunblocked.info
/app14.js$domain=theproxy.app|siteunblocked.info
||i99i.org^$3p
```


Happens on other subdomains like `https://predb-org.theproxy.app/` and `https://vidcloud.siteunblocked.info/`

**Comment by okiehsch** [comment]
How about 
````
siteunblocked.info,theproxy.app##+js(nowoif)
||i99i.org^$3p
````
?

**Comment by llacb47** [comment]
My filters take care of the debugger trap too

**Comment by ghajini** [comment]
popup ads
ublock origin & firefox android stable
```
https://yts.siteunblocked.info/movies/dune-2021
http://primewire.siteunblocked.info/
```

**Comment by mapx-** [comment]
test
`siteunblocked.info##+js(aost, Object, , 2)`

**Comment by ghajini** [comment]
`https://yts.siteunblocked.info/movies/dune-2021`

breaks this section here![Screenshot_20211030-210317-907.png](https://user-images.githubusercontent.com/20338483/139539652-88f28b6b-ed28-42c3-9a5a-fe5d975f1b9f.png)

**Comment by mapx-** [comment]
what exactly is broken ? how can I download even without the filter above ?

**Comment by mapx-** [comment]
try instead:

```
||siteunblocked.info^$csp=script-src 'unsafe-inline' 'self' *.cloudflareinsights.com *.addthis.com
siteunblocked.info##[id^="cookieConsent"]
siteunblocked.info##.antoic
||socialnetwork-adblocker.com^$all
||declk.com^$all
||unshiftryr.com^$3p
```

**Comment by ghajini** [comment]
can download subtitles only

**Comment by ghajini** [comment]
doesn't prevent propeller crap over here
`http://thepiratebay.siteunblocked.info/`

how about(working on my end)
```
||unshiftryr.com^$all
||ultralove.net^$all
||bgaxgjre.xyz^
||tapsirsa.net^
siteunblocked.imfo##+js(aopr, GetWindowHeight)
siteunblocked.info##+js(aopr, decodeURIComponent)
/hy.js$script,domain=siteunblocked.info
||siteunblocked.info/zpp/*$script,domain=siteunblocked.info
siteunblocked.info##+js(aost, Math.random, /\st\.[a-zA-Z]*\s/)
siteunblocked.info##.antoic
siteunblocked.info##[id^="cookieConsent"] 
||socialnetwork-adblocker.com^$all
||declk.com^$all
||zoukooso.com^
```

**Comment by JobcenterTycoon** [comment]
`tapsirsa.net`
`bgaxgjre.xyz`
`zoukooso.com`

can be removed, it got added to EL
