### ISSUE TITLE
shrinkme.in - anti-adblock

### ISSUE THREAD

**Issue by doio** [uBlockOrigin/uAssets#7638]
### URL(s) where the issue occurs
`https://shrinkme.in/PqsF`

### Versions

- Browser/version: Firefox 68.10.0esr (64-bit)
- uBlock Origin version: 1.28.1b0

**Comment by JobcenterTycoon** [comment]
fake button
<img width="649" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/89224300-89d03f80-d5d8-11ea-8ae2-3b39e6bc00b0.PNG">
