### ISSUE TITLE
sythe.org

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#7639]
### URL(s) where the issue occurs

`https://www.sythe.org/`
### Describe the issue

bottom ads

### Screenshot(s)

<img width="932" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/86565508-3ed6f400-bf68-11ea-860e-9b006677c400.PNG">

### Versions

- Browser/version: Firefox 78.0.1
- uBlock Origin version: v1.27.10

### Settings

default

**Comment by uBlock-user** [comment]
```
sythe.org###topadplaceholder
sythe.org##div[style="width: 100%; display: block; text-align: center;"]
```

**Comment by JobcenterTycoon** [comment]
`||sythe.org/*.php` need to be removed it breaks the CSS on the page

**Comment by uBlock-user** [comment]
@gorhill

**Comment by uBlock-user** [comment]
> the rule is ||sythe.org/*.php$~css,all but css is still blocked

@gorhill

**Comment by mapx-** [comment]
maybe `$all` (wrongly) overwrites all the exceptions

**Comment by gorhill** [comment]
> maybe `$all` (wrongly) overwrites all the exceptions

But "wrongly" is debatable though, as `all` explicitly means all network types, `inline-script`, `inline-font`, `document`, and `popup`, so the exception is overwritten as a result. This works however:

    ||sythe.org/*.php$all,~css

When using:

    ||sythe.org/*.php$~css

The "all network types" is implicit, so there is no ambiguity, while when using `all`, it's explicit and there is an ambiguity, should `css` be blocked or not? In such case, the order of appearance disambiguate.

**Comment by mapx-** [comment]
The question is: I want to use $all for a certain page but with some exception (css), as you've written above is not possible in the current implementation, right ?

**Comment by gorhill** [comment]
Possible, as mentioned:

    ||sythe.org/*.php$all,~css

Just put the exception(s) after `all`.

**Comment by mapx-** [comment]
oh, the order ..

**Comment by gorhill** [comment]
Usually the order does not matter because there is no ambiguity, but here since `all` means explicitly block all network request types, an ambiguity arise, so the order ends up sorting it out.

**Comment by uBlock-user** [comment]
With `$all` does the order matter even without negation ?

**Comment by gorhill** [comment]
No, `all` there is no possible ambiguity with non-type options.

**Comment by gorhill** [comment]
Gave more thoughts about this, I could give the negated types, higher precedence so they don't get overwritten by non-negated ones.
