### ISSUE TITLE
ivoox.com - podcasts not working

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#7644]
### URL(s) where the issue occurs

`https://www.ivoox.com/hititas-por-dioses-lbp-audios-mp3_rf_48708708_1.html`

### Describe the issue

Podcasts not working..

conflicting filters.. because in **easylist spanish** exist this rule: `||sunmedia.tv^$3p`

### Screenshot(s)

![Captura](https://user-images.githubusercontent.com/33556647/86684441-d852e400-c002-11ea-9607-03af74c91401.PNG)

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.27.10]

### Settings

- Default Spain region

Cheers! 😊

**Comment by PIZZA90** [comment]
is me.. or the issue continue here. ( i updated my filters ) 🤔

`https://www.ivoox.com/aguas-turbias-111-mortal-kombat-mortal-audios-mp3_rf_53795126_1.html`

![Captura](https://user-images.githubusercontent.com/33556647/87544171-4dc75000-c6a6-11ea-9f3a-98f3ff660e4e.PNG)

**Comment by mapx-** [comment]
test
`@@||services.sunmedia.tv/geotarget/geocity.php$xhr,domain=ivoox.com`

**Comment by mapx-** [comment]
@BlazDT

**Comment by PIZZA90** [comment]
for me working well 👍

**Comment by PIZZA90** [comment]
again issues here.

example URL: 

`https://www.ivoox.com/08-31-08-20-lhdw-preguntas-oyentes-para-audios-mp3_rf_55884969_1.html`

maybe a solution:
`@@||sdk.privacy-center.org^$script,domain=ivoox.com`

**Comment by PIZZA90** [comment]
similar case in videos of **lavanguardia.com**

Example URL (try play the video in the post):

`https://www.lavanguardia.com/vida/20200901/483264387730/padres-hijos-afectados-coronavirus-baja-laboral.html`

`@@||sdk.privacy-center.org^$script,domain=lavanguardia.com`

**Comment by okiehsch** [comment]
Update uBO-unbreak should work after that.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ace0968b4bf70953e36a22570b9aafaef63786ce

**Comment by krystian3w** [comment]
#7411

**Comment by peace2000** [comment]
_||privacy-center.org/ui-gdpr-*.js_

Seems to be safe to block.

**Comment by dimisa-RUAdList** [comment]
I think there is no longer a need for this rule. The EasyList Cookie has already been corrected for the above cases. At the same time, where this rule is needed, it does not work now. Example:  `https://euronews.com/`

**Comment by krystian3w** [comment]
IDCAC maybe no added fixes for `sdk.privacy-center.org`.

**Comment by dimisa-RUAdList** [comment]
"I don't care about cookies" - is not a preset filter.

**Comment by PIZZA90** [comment]
Updating **lavanguardia**

`https://www.lavanguardia.com/vida/20200901/483264387730/padres-hijos-afectados-coronavirus-baja-laboral.html`

`@@||sb.scorecardresearch.com/c2/plugins/streamingtag_plugin_jwplayer.js$script,domain=www.lavanguardia.com`

**Comment by dimisa-RUAdList** [comment]
This is already an EasyPrivacy problem.

@ryanbr 
Look at this please.

**Comment by krystian3w** [comment]
unbreak.txt also cover EP issues.

**Comment by dimisa-RUAdList** [comment]
@krystian3w 
It's always better to notify the author of the filter, isn't it?

**Comment by PIZZA90** [comment]
but the issue is in "peter lowe's" list right?

**Comment by R-Ata** [comment]
`https://www.ivoox.com/milenio-live-t3x36-doble-investigacion-audios-mp3_rf_71636046_1.html`

filters breaking the podcasts where is necessary account

```
ivoox.com##.in.fade.modal-backdrop
ivoox.com##.in.fade.modal.remote-submit
```

![Captura](https://user-images.githubusercontent.com/33556647/133308735-ef8e3576-10e9-4c63-a5a6-279347fa0122.PNG)

**Comment by R-Ata** [comment]
that `pop-pup`  is blocked

**Comment by krystian3w** [comment]
But who made this filter? uAssets, EL, EP, Fanboy Annoyance, Polish Annoyance Filters?
