### ISSUE TITLE
NanoMeow issue breaks niuhuskies.com

### ISSUE THREAD

**Issue by tempissue** [uBlockOrigin/uAssets#7646]
### URL(s) where the issue occurs

`https://niuhuskies.com/`

### Describe the issue

This [issue](https://github.com/NanoMeow/QuickReports/issues/2153 ) in the Ublock filters is meant to fix adblock detection, but is now blocking the page from loading completely.

It breaks a ton of sidearmsports.com sites (many, many universities)

This is the offending rule: ||cloudfront.net/assets.sidearmsports.com/*/bettor_detector.$script,3p

### Screenshot(s)

<img width="1532" alt="Screen Shot 2020-07-07 at 2 03 18 PM" src="https://user-images.githubusercontent.com/32878098/86823279-a8cfc600-c05a-11ea-889e-f5d6653cf2df.png">

### Versions

- Browser/version: Chrome 83/Firefox 78.0.1
- uBlock Origin version: 1.27.10

### Settings

-

### Notes

Whitelisting the domain works, but brings back the adblock detection nag.

**Comment by mapx-** [comment]
What other sites are broken ?

**Comment by uBlock-user** [comment]
`@@||dbukjj6eu5tsf.cloudfront.net/assets.sidearmsports.com/statcollector/$script,domain=niuhuskies.com` can be replaced with `*$script,redirct-rule=noopjs,domain=niuhuskies.com`

**Comment by llacb47** [comment]
@mapx- https://publicwww.com/websites/%22%2Fsidearm.sites%2F%22/
