### ISSUE TITLE
onwebchange.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#7647]
### URL(s) where the issue occurs

`https://onwebchange.com/`

### Describe the issue

Bottom cookie notice annoyance. Adguard won't hide it because they believe it has low traffic.

### Screenshot(s)

![cookies](https://user-images.githubusercontent.com/35470489/86545892-1fa87a00-bf08-11ea-90d8-985d2a2cd498.png)

### Versions

- Browser/version: Firefox stable
- uBlock Origin version: 1.27.10

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin lists

**Comment by llacb47** [comment]
https://github.com/uBlockOrigin/uAssets/issues/4123#issuecomment-439232886 ...

**Comment by adranger** [comment]
@llacb47 `uBlock filters -- Annoyances` now has rules with the string `cookie` and `gdpr`.

**Comment by JobcenterTycoon** [comment]
No cookie banner for me when i enable EasyList Cookie and Fanboy’s Annoyance

**Comment by adranger** [comment]
@JobcenterTycoon I use the Adguard lists instead, as I've pointed out in the report.

**Comment by okiehsch** [comment]
> `uBlock filters -- Annoyances` now has rules with the strings cookie and gdpr.

The readme clearly states that GDPR modals won't be addressed in uAssets.
uBlock-user does add filters for cookie messages to the annoyance list.

**Comment by okiehsch** [comment]
Looking at all `gdpr` strings in the annoyance list, the only one that blocks a GDPR modal is the one for `imaginetricks.com` as far as I can see. I will remove that one.

**Comment by uBlock-user** [comment]
> uBlock filters -- Annoyances now has rules with the strings cookie and gdpr.

Websites use "gdpr" and "cookie" as prefixes for their CSS selectors, that's not something we can control and they're cookie notices, so they get blocked.

**Comment by uBlock-user** [comment]
As for this case, add `onwebchange.com##.cookie-bg` to my Filters.

**Comment by krystian3w** [comment]
@okiehsch IMO removed half selectors only recover anti-select in pop-up.

If filter have puted `:style()` it's not standard practice to hide if you don't reach for `display: none !important;` or `visibility: hidden !important; height: 0 !important; width: 0 !important;` inside brackets.
