### ISSUE TITLE
UOL Paywall

### ISSUE THREAD

**Issue by isantolin** [uBlockOrigin/uAssets#765]
### URL(s) where the issue occurs

https://www.uol/educacao/especiais/entrevista-com-fernando-haddad.htm#no-palanque-da-educacao

### Describe the issue

Bug referenced on #124 Still occurs because moved domain

### Screenshot(s)

![no palanque da educacao uol educacao](https://user-images.githubusercontent.com/264640/31587378-ae3b75dc-b1bf-11e7-9351-946a54e03f73.png)

### Versions

- Browser/version: Chrome 62
- uBlock Origin version: 1.14.12

### Settings
To fix, i replicated the rules but fixing the URLs

> www.uol##.overlay-lightbox
> www.uol##.content-lightbox
> www.uol###banner-stick

### Notes

Anyone can merge to main filters?

**Comment by okiehsch** [comment]
Does
`www.uol##script:inject(abort-on-property-write.js, detectingAdblocks)`
work for you?

**Comment by isantolin** [comment]
@okiehsch Doesnt works :(

**Comment by okiehsch** [comment]
Is `www.uol###banner-stick` necessary on your end, or is already fixed with
````
www.uol##.overlay-lightbox
www.uol##.content-lightbox
````

**Comment by isantolin** [comment]
@okiehsch Already fixed with

> www.uol##.overlay-lightbox
> www.uol##.content-lightbox
