### ISSUE TITLE
indianexpress.com

### ISSUE THREAD

**Issue by BlitW0** [uBlockOrigin/uAssets#7651]
### URL(s) where the issue occurs

`https://indianexpress.com/article/entertainment/web-series/robert-pattinson-the-batman-to-get-a-tv-spinoff-series-6499803/`

### Describe the issue

Ad placeholders are not removed completely, and there is also an annoying floating read in app button on the right and an e-paper banner too.

### Versions

- Browser/version: Firefox Beta Android
- uBlock Origin version: 1.27.10

### Settings

- Enabled all annoyances filters except Fanboy's Social

### Notes

Figured out the below filters on my own:
```
indianexpress.com##.epaper-banner
indianexpress.com##.top-ads-mobile
indianexpress.com##.app-btn
indianexpress.com##.adboxtop
```

**Comment by mapx-** [comment]
report here (mobile filters) https://github.com/AdguardTeam/AdguardFilters/issues
or at easylist repository:
https://github.com/easylist/easylist/issues

**Comment by krystian3w** [comment]
@ryanbr
@BlazDT

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/issues/5705
