### ISSUE TITLE
YouTube video page stuck on loading

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uAssets#7654]
### Describe the issue

When I open a video on YouTube the video page get's stuck on loading and I get the Chrome page unresponsive message 

### Versions

- Browser/version: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.27.10

### Settings

! 6/19/2020 https://www.youtube.com
www.youtube.com##.ytp-button.ytp-miniplayer-button

**Comment by mapx-** [comment]
I had to remove tons of useless info (for github ?). 

No useful info here.

Just use uBO only with default settings and the lists updated. No other blocking extension.

**Comment by GKid94** [comment]
@mapx- Maybe this will help
[Console log.txt](https://github.com/uBlockOrigin/uAssets/files/4912601/Console.log.txt)

![Screenshot_1](https://user-images.githubusercontent.com/18757054/87307444-e7152b80-c519-11ea-8c6f-f73212d5fcef.png)

**Comment by gwarser** [comment]
```
1000content-script-functions.js:1 Uncaught (in promise) TypeError: Cannot read property 'textContent' of undefined
    at getFPS (content-script-functions.js:1)
    at changeQuality (content-script-functions.js:1)
    at prepareToChangeQuality (content-script-functions.js:1)
    at MutationObserver.observe.childList (content-script-initialize.js:1)
```

Do you have any other YT add-on?

**Comment by GKid94** [comment]
@gwarser 
1)These are my extensions on the image below
2) No, I keep getting the page unresponsive Chrome popup when the video page won't load

![Screenshot_2](https://user-images.githubusercontent.com/18757054/87761172-48d2df80-c811-11ea-844d-01da118b13d6.png)

![hqdefault](https://user-images.githubusercontent.com/18757054/87761177-4bcdd000-c811-11ea-9df1-af643e11a99c.jpg)

**Comment by gwarser** [comment]
It's "YouTube Auto HD + FPS" - `https://chrome.google.com/webstore/detail/youtube-auto-hd-%2B-fps/fcphghnknhkimeagdglkljinmpbagone?hl=en` [source](https://robwu.nl/crxviewer/?crx=https%3A%2F%2Fclients2.google.com%2Fservice%2Fupdate2%2Fcrx%3Fresponse%3Dredirect%26os%3Dlinux%26arch%3Dx86-64%26os_arch%3Dx86-64%26nacl_arch%3Dx86-64%26prod%3Dchromiumcrx%26prodchannel%3Dunknown%26prodversion%3D9999.0.9999.0%26acceptformat%3Dcrx2%2Ccrx3%26x%3Did%253Dfcphghnknhkimeagdglkljinmpbagone%2526uc&q=!prepareToChangeQuality&qf=scripts%2Fcontent-script-functions.js&qb=1&qh=1). It also has ability to execute arbitrary JS: `script-src 'self' 'unsafe-eval';` - you should remove it.

**Comment by GKid94** [comment]
@gwarser I contacted the developer of that extension and he says that he doesn't have an issue with it

![Screenshot_3](https://user-images.githubusercontent.com/18757054/87844715-35cb1880-c8c0-11ea-9c7b-87eefde21d8b.png)

**Comment by gwarser** [comment]
> he says that he doesn't have an issue with it

It's what the console log reports - the exception I quoted above is from this extension (and it says it was logger 1000 times). I did not tried reproducing (especially when this extension can execute `unsfe-eval`). It's possible content scripts of **your** other YT add-ons/user scripts interfere with it.

**Comment by GKid94** [comment]
What is the unsfe-eval

**Comment by gwarser** [comment]
Security feature https://en.wikipedia.org/wiki/Content_Security_Policy

`unsafe-eval` directive allows to execute arbitrary text as JavaScript code with add-on permissions.

**Comment by avi12** [comment]
> It's "YouTube Auto HD + FPS" - `https://chrome.google.com/webstore/detail/youtube-auto-hd-%2B-fps/fcphghnknhkimeagdglkljinmpbagone?hl=en` [source](https://robwu.nl/crxviewer/?crx=https%3A%2F%2Fclients2.google.com%2Fservice%2Fupdate2%2Fcrx%3Fresponse%3Dredirect%26os%3Dlinux%26arch%3Dx86-64%26os_arch%3Dx86-64%26nacl_arch%3Dx86-64%26prod%3Dchromiumcrx%26prodchannel%3Dunknown%26prodversion%3D9999.0.9999.0%26acceptformat%3Dcrx2%2Ccrx3%26x%3Did%253Dfcphghnknhkimeagdglkljinmpbagone%2526uc&q=!prepareToChangeQuality&qf=scripts%2Fcontent-script-functions.js&qb=1&qh=1). It also has ability to execute arbitrary JS: `script-src 'self' 'unsafe-eval';` - you should remove it.

The reason it's using `script-src 'self' 'unsafe-eval'` is that the pop-up window is using Vue.js.
Regarding the "page-freezing" problem, I am aware of it, but I don't have a solution to it yet.
This is occurring to me only when I'm watching a bunch of videos, one after the other.
As soon as I will, I will update the extension.
