### ISSUE TITLE
Peter Lowe's adservers list license is GPL-incompatible

### ISSUE THREAD

**Issue by rathann** [uBlockOrigin/uAssets#7657]
### URL(s) where the issue occurs

https://github.com/uBlockOrigin/uAssets/tree/master/thirdparties/pgl.yoyo.org/as

### Describe the issue

As noted in [README.md](https://github.com/uBlockOrigin/uAssets/blob/master/thirdparties/pgl.yoyo.org/as/README.md) , Peter Lowe's adservers list is distributed under `McRae General Public License (version 4.r53)`, which explicitly forbids commercial use. That makes it non-free and GPL-incompatible, so you cannot distribute it together with the rest of uAssets/uBlock Origin and claim everything is GPLv3-licensed.

Arguably, you cannot distribute the adservers list with uBlock Origin while keeping the result under GPLv3 at all, as it's not an "[aggregate](https://github.com/uBlockOrigin/uAssets/blob/master/LICENSE#L239)", but rather an extension of uBlock.

**Comment by uBlock-user** [comment]
@pgl

**Comment by gwarser** [comment]
@gorhill 

Also: https://github.com/gorhill/uBlock/issues/885

**Comment by gorhill** [comment]
> it's not an "aggregate", but rather an extension of uBlock

I disagree, The list is not compiled into uBO in an indistinguishable blob, it has its own distinct directory, shipped as is in its original unmodified form, and with a appropriate license/readme files.

**Comment by pgl** [comment]
It's a joke license. I don't expect anyone to print it out and stick it up their arse if they use it for commercial use.

**Comment by rathann** [comment]
> It's also a joke license. I don't expect anyone to print it out and stick it up their arse if they don't agree to its terms.

Please change it to something standard, free and GPL-compatible. Lawyers don't have a sense of humour and you're making life harder for downstreams.

**Comment by rathann** [comment]
Here's a story from a project that had a seemingly innocent clause "use for good, not evil" in its license and finally decided to remove it. Please read it: http://mikepennisi.com/blog/2020/you-may-finally-use-jshint-for-evil/ and especially http://mikepennisi.com/blog/2020/jshint-watching-the-ship-sink/ . While the severity of the issue is perhaps lower here, there are similarities. In the end, downstream redistributors like Debian or Fedora [have to assume that any license is potentially enforceable. I.e. there really is no such thing as a "joke" license](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/message/K6NAGPQO7BUSGFA5LG7NGTUO2DKQQ4M5/).

@pgl , please reconsider changing the license to something standard and GPL-compatible and doing away with the joke. Jokes really have no place in legal matters.

For reference, Debian is patching out Peter's list (and some other files) from [their package](https://salsa.debian.org/webext-team/ublock-origin/-/blob/master/debian/clean-dfsg.sh) precisely because the licenses do not follow the [DFSG](https://www.debian.org/social_contract#guidelines).

As Fedora package maintainer, I have to do the same. There are far fewer non-free files in the current version that I'm packaging in Fedora, though, so thank you for that at least.

**Comment by pgl** [comment]
@rathann Debian or Fedora assuming that the license is potentially enforceable is ridiculous. There is no way it is enforceable. I have no legal right to demand anyone print out anything and stick it up their arse, even if I ask nicely.

> Jokes really have no place in legal matters

This is not a legal matter. It's a 25-year old joke that isn't very funny to the vast majority of people but makes me smile.

And what is being asked here is far more than removing the joke license, it's asking that I _impose_ a GPL-compatible license. That's a much bigger question, that I don't even want to get into.

**Comment by gorhill** [comment]
> Debian is patching out Peter's list (and some other files) from their package precisely because the licenses do not follow the DFSG.

I consider @pgl's list a key list for uBO, and it's unfortunate it's being removed from the package -- however I expect uBO to still fetch it at first install at least, just not from the package.

**Comment by rathann** [comment]
I agree it's unfortunate, but I don't have any other choice as long as the license, even if jokingly, explicitly forbids commercial use and distribution. Debian and Ubuntu are in the same position.

I haven't checked Debian packaging in detail, but in case of Fedora package your expectation is correct. I'm only patching out "local assets" distributed with the package. URL is left intact. The actual patch is [here](https://src.fedoraproject.org/rpms/mozilla-ublock-origin/blob/master/f/mozilla-ublock-origin-nonfree.patch).

Thank you for unlocking the conversation, by the way.

**Comment by gorhill** [comment]
Right, there was no reason to lock the thread, you made a fair point and the JSHint case was an interesting read.

> The actual patch is [here](https://src.fedoraproject.org/rpms/mozilla-ublock-origin/blob/master/f/mozilla-ublock-origin-nonfree.patch).

Shouldn't you also remove the trailing comma at the end of the URL left in there? If there is a comma left dangling, this would cause the file to no longer be JSON-valid, I expect this would quite break uBO.

**Comment by rathann** [comment]
Great catch, I'll fix the patch.
