### ISSUE TITLE
Questions about the new filter Online Malicious URL Blocklist 

### ISSUE THREAD

**Issue by Jose1971AB** [uBlockOrigin/uAssets#7659]
Hello 

I don't know if this incidence corresponds here. **Please, if it's somewhere else, tell me the url or address**.

### Describe the issue

I have questions about the new Online Malicious URL Blocklist filter. As a basic user, my questions may be a little strange to you.

I have been doing some research [on this page](https://github.com/gorhill/uBlock/releases/tag/1.28.1b7) and I think it says (correct me) that this filter replaces the Malware domains and Malware Domain List filters, it talks about removing the Malware domains and Malware Domain List filters and leaving only the Online Malicious URL Blocklist...

![URLhaus Malicious URL blocklist](https://user-images.githubusercontent.com/44229110/87255877-d79cd080-c48e-11ea-9fea-0c507e7f1197.png)

 **Will I be equally protected by leaving only the Online Malicious URL Blocklist?**

**2.- According to [URLhaus Malicious URL blocklist](https://gitlab.com/curben/urlhaus-filter)** there is an online and an offline version (lite), the one that presents uBlock seems to be the lite version (online), but there is also another one that links both --> https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter.txt. then ... **could you put this one in Custom?**

 

### Versions

- Browser/version: [Firefox 64-bit 78.0.2]
- uBlock Origin version: [v1.28.0]

### Settings

![1](https://user-images.githubusercontent.com/44229110/87256083-226b1800-c490-11ea-82a0-9636f54e4857.jpg)
![2](https://user-images.githubusercontent.com/44229110/87256089-27c86280-c490-11ea-8120-51dd0f7c980d.PNG)

-

### Notes

Thank you very much and a greeting

**Comment by mapx-** [comment]
for questions use uBO reddit thread
https://www.reddit.com/r/uBlockOrigin/

**Comment by krystian3w** [comment]
Where report badware now? Here or on Gitlab?

**Comment by mapx-** [comment]
We have an own badware list.
