### ISSUE TITLE
cian.ru menu ads

### ISSUE THREAD

**Issue by vladostman** [uBlockOrigin/uAssets#7660]
### URL(s) where the issue occurs

`https://krasnoyarsk.cian.ru/`

### Describe the issue

There is a menu at the top of the page, the last element in that menu is an ad. They seem to be custom crafted/native ads.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66869331/87271625-fab29900-c4fd-11ea-8531-890a4237050a.png)

### Versions

- Browser/version: Firefox 77.0.1 64 bit
- uBlock Origin version: AdNauseam 3.9.104

### Settings

AdNauseam uses uBlock list by default, no settings changes.

### Notes

`cian.ru##li#special-promo-link-container` should do it.

**Comment by mapx-** [comment]
report here (RUAdList): https://forums.lanik.us/viewforum.php?f=102

**Comment by vladostman** [comment]
This is some archaic forum that requires registration (and doesn't accept my yandex email). Is there really no way to instead use github (the one proper place) to report such issues? 

My previous contribution was accepted without problems or delays: https://github.com/uBlockOrigin/uAssets/issues/7547

@mapx-

**Comment by mapx-** [comment]
just notify @dimisa-RUAdList in the future (RUAdList maintainer)

**Comment by dimisa-RUAdList** [comment]
Ok: https://hg.adblockplus.org/ruadlist/rev/66c2ecc76288
