### ISSUE TITLE
Quora is blurring again

### ISSUE THREAD

**Issue by annonymatus** [uBlockOrigin/uAssets#7662]
### URL(s) where the issue occurs

`https://www.quora.com/Can-you-answer-my-question-with-questions
`
Select a question from Related Questions in the right

### Describe the issue

Quora is blurring

 

### Screenshot(s)

https://i.imgur.com/D1NjS71.png

### Versions

- Browser/version: Edge 83.0.478.61
- uBlock Origin version: 1.28.0

### Settings

Default

-

**Comment by uBlock-user** [comment]
Subscribe to uBlock Annoyances list.
