### ISSUE TITLE
Gelbooru [NSFW]

### ISSUE THREAD

**Issue by Jorge9811** [uBlockOrigin/uAssets#7663]
### URL(s) where the issue occurs

`https://gelbooru.com/index.php?page=post&s=list&tags=all`

### Describe the issue

Gallery view does not show any content.

### Screenshot(s)

With uBlock Origin enabled:
https://i.imgur.com/eIAkHGu.png

With uBlock Origin disabled:
https://i.imgur.com/pQiB4Hh.png

### Versions

- Browser/version: Mozilla Firefox v79.0b7 x86
- uBlock Origin version: 1.28.2

### Settings

https://i.imgur.com/WQZrluK.png

Because I'm using Nano Defender, I also have userResourcesLocation adjusted accordingly.

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by dumbusernameidk** [comment]
Works for me.

**Comment by Jorge9811** [comment]
It wasn't working for me, but after resetting my configuration and reincorporating Nano Defender and Gelbolube, things are working just fine. Idgi, but whatever. Sorry for bothering.
