### ISSUE TITLE
NSFW javhub.net

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7665]
### URL(s) where the issue occurs

`https://javhub.net/play/d7iQY8UGE2Z_zQ0rYowl5tKG782bTnr-oOKdSdaqQ-s/kkj-103-serious-serious-persuasion-nampa-brought-sex-voyeur-posted-without-permission-handsome-immediate-teacher-paco-video-32`

### Describe the issue

Dev tools are blocked.

### Screenshot(s)

<details>

![javhub](https://user-images.githubusercontent.com/58900598/87420154-b7484f80-c60f-11ea-8567-b9d0d2749aa2.png)
</details>

### Versions

- Browser/version: Brave 1.10.97/Firefox 78.0.2
- uBlock Origin version: 1.27.10/1.28.0

### Settings

- Default + uBlock Annoyances + AG JPN

**Comment by mapx-** [comment]
does this work (the first 1)

```
javhub.net##+js(nosiif, _0x)
javhub.net##+js(nowoif)
```

**Comment by uBlock-user** [comment]
```
javhub.net##+js(nosiif, _0x)
javhub.net##+js(nostif, _0x)
```
Those work as expected.

**Comment by mapx-** [comment]
still not working => open dev tools => refresh the page => same debugger issue

**Comment by uBlock-user** [comment]
Cause - `https://javhub.net/av/js/p.js`

**Comment by mapx-** [comment]
exactly

**Comment by uBlock-user** [comment]
Player is also embedded alongside...

**Comment by mapx-** [comment]
yeah, mixed code trying to kill some functions will kill the player too

**Comment by uBlock-user** [comment]
I mean player doesn't appear if the script is blocked in its entirety.

**Comment by dumbusernameidk** [comment]
Stuff like this you'd need a tampermonkey script.

**Comment by gorhill** [comment]
In Chromium-based browser, you can right click in the gutter of the `debugger` instruction and select _"Never pause here"_, this will disable the `debugger` instruction. Firefox has that feature too but I couldn't make it work.

**Comment by uBlock-user** [comment]
Related -- https://bugzilla.mozilla.org/show_bug.cgi?id=1300934, https://bugzilla.mozilla.org/show_bug.cgi?id=1247198

**Comment by Yuki2718** [comment]
Indeed worked on Brave, thx!

**Comment by mapx-** [comment]
well, now at least we have a method to use, closing
