### ISSUE TITLE
maps.google.*

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#7666]
### URL(s) where the issue occurs

`https://www.google.de/maps/@52.4144102,16.9511694,3a,75y,148.18h,1t/data=!3m6!1e1!3m4!1sJ8pGYh2AH3fRS26pVYpXpg!2e0!7i13312!8i6656`

`https://www.google.pl/maps/@52.4144102,16.9511694,3a,75y,148.18h,1t/data=!3m6!1e1!3m4!1sJ8pGYh2AH3fRS26pVYpXpg!2e0!7i13312!8i6656`

### Describe the issue

Empty buttons on "regional" Google "street" view due by CNAME.

### Screenshot(s)

![Przechwytywanie](https://user-images.githubusercontent.com/35370833/87433115-3a09e400-c5e9-11ea-8942-8b1ccc97a330.PNG) |
--- |

### Versions

- Browser/version: Firefox 78
- uBlock Origin version: uBO 1.28.2

### Settings

stock

### Notes

`||gstaticadssl.l.google.com^$image,3p`

`@@||gstaticadssl.l.google.com^$image,3p,domain=google.*` - but don't work with uBO older than 1.28.0

> <details><summary>Logger output</summary>
> 
> | | | | | | | | |
> |:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
> | +504 | \|\|gstaticadssl.l.google.com^$image,3p | -- | `www.google.de` | 3 | image | `https://gstaticadssl.l.google.com/` | `aliasURL=https://fonts.gstatic.com/s/i/googlematerialicons/keyboard_arrow_right/v6/white-24dp/2x/gm_keyboard_arrow_right_white_24dp.png` |
> | +504 | \|\|gstaticadssl.l.google.com^$image,3p | -- | `www.google.de` | 3 | image | `https://gstaticadssl.l.google.com/` | `aliasURL=https://fonts.gstatic.com/s/i/googlematerialicons/keyboard_arrow_left/v6/white-24dp/2x/gm_keyboard_arrow_left_white_24dp.png` |
> | +0 | \|\|gstaticadssl.l.google.com^$image,3p | -- | `www.google.pl` | 3 | image | `https://gstaticadssl.l.google.com/` | `aliasURL=https://fonts.gstatic.com/s/i/googlematerialicons/keyboard_arrow_right/v6/white-24dp/2x/gm_keyboard_arrow_right_white_24dp.png` |
> | +0 | \|\|gstaticadssl.l.google.com^$image,3p | -- | `www.google.pl` | 3 | image | `https://gstaticadssl.l.google.com/` | `aliasURL=https://fonts.gstatic.com/s/i/googlematerialicons/keyboard_arrow_left/v6/white-24dp/2x/gm_keyboard_arrow_left_white_24dp.png` |
> </details>

**Comment by mapx-** [comment]
does this work ?
`@@||google.*^$cname`
