### ISSUE TITLE
[Anti-Adblock] WatchCartoonOnline

### ISSUE THREAD

**Issue by SheepKid12** [uBlockOrigin/uAssets#7668]
### URL(s) where the issue occurs
Any episode page on `thewatchcartoononline.tv`.

### Describe the issue
Anti-AdBlock message when trying to watch anything. Simple as that.

### Screenshot(s)

![Screenshot_2020-07-14](https://user-images.githubusercontent.com/60110745/87463793-a2e86080-c5d7-11ea-99f7-a67a4229d41f.png)

### Versions
- Browser/version: Latest version of Firefox on Manjaro
- uBlock Origin version: 1.28.2

### Settings
- Default settings + I actually checked this time to make sure all filters were up-to-date before posting.

### Notes
Adding `thewatchcartoononline.tv##+js(set, isAdBlockActive, false)` to my filter list fixes the issue.

**Comment by uBlock-user** [comment]
It's `google_jobrunner` script.
