### ISSUE TITLE
atresplayer.com - Update

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#7669]
### URL(s) where the issue occurs

`https://www.atresplayer.com/`

### Describe the issue

the site is "break"

### Screenshot(s)

![Captura](https://user-images.githubusercontent.com/33556647/87508046-c7dbe280-c66e-11ea-8cda-5b646d1aebc0.PNG)

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [v1.27.10]

### Settings

- Default, Spain region

### Notes

in **uBO**: `@@||assets.adobedtm.com^$xhr,domain=atresplayer.com`
**with**: `@@||assets.adobedtm.com^$script,xhr,domain=atresplayer.com` **works well**.

**Comment by mapx-** [comment]
Did you update your lists ?

**Comment by PIZZA90** [comment]
Maybe it's because of my new computer.. anyway I update the filters 3-4 days ago.. 🤔 excuse me,  closing..

**Comment by mapx-** [comment]
I fixed it 2 days ago (reddit reporting)

**Comment by lain566** [comment]
@mapx- Does the video player work for you?
`https://www.atresplayer.com/directos/neox/`

**Comment by okiehsch** [comment]
It works insofar I can see the video,  for it to play I need a subscription.

**Comment by PIZZA90** [comment]
not necesary subscription for: `https://www.atresplayer.com/directos/neox/`

**Comment by okiehsch** [comment]
Hm, I get redirected to `https://www.atresplayer.com/antena3/series/mujer/temporada-1/capitulo-3_5ebec22c7ed1a8470a02d983/`
I will try with another browser.

**Comment by lain566** [comment]
maybe geolock, the video playback freezes for me anyway

**Comment by mapx-** [comment]
neox seems to be ok using a spanish ip

**Comment by okiehsch** [comment]
Using a spanish IP the videoplayback freezes for me too.

**Comment by mapx-** [comment]
> maybe geolock, the video playback freezes for me anyway

mmhmm .. if I click picture in picture then play is working

**Comment by okiehsch** [comment]
````
@@||assets.adobedtm.com/extensions/*/AppMeasurement_Module_ActivityMap.min.js$script,domain=atresplayer.com
@@||assets.adobedtm.com/extensions/*/AppMeasurement_Module_AudienceManagement.min.js$script,domain=atresplayer.com
````
fixes the issue on my end.

**Comment by mapx-** [comment]
yeah, needing whitelisting

**Comment by okiehsch** [comment]
Ups you beat me to it, I will remove my commit.

**Comment by PIZZA90** [comment]
**OFFTOPIC:**

hello I did not know where to put this post, but i cant loging in **forums.lanik** i dont have the password saved in this computer, and i get a fatal error when i try to reset the pasword, because i forgot her.

![Captura](https://user-images.githubusercontent.com/33556647/87855171-c0d6fd80-c916-11ea-94b6-7a03110451f2.PNG)

I was going to report that the filter: `##a[href^="https://is.ltroute.com/"]` in **easylist** looks not working for example here: `https://www.ancient-code.com/study-finds-that-inbreeding-and-other-demographic-problems-alone-could-have-wiped-out-neanderthals/`

![Captura2](https://user-images.githubusercontent.com/33556647/87855272-668a6c80-c917-11ea-9ca3-f91d0ca6cb30.PNG)

**Comment by mapx-** [comment]
yeah because they are using now upper case
`##[href^="https://IS.ltroute.com/click.track"]`

**Comment by LanikSJ** [comment]
@PIZZA90 Follow the instructions [here](https://forums.lanik.us/user/forgot_password).

**Comment by PIZZA90** [comment]
@LanikSJ  I already did that and received an email for the first time, and then an error appeared.

Then I have tried 2 or 3 more times, but I do not receive more emails. 🤔

i did the step, but no emails receive
![Captura](https://user-images.githubusercontent.com/33556647/87857525-c7ba3c00-c927-11ea-9c33-9d9eb167ce0b.PNG)

maybe is because: _**you have requested multiple password resets within a short time frame**_

**Comment by PIZZA90** [comment]
i remember, the first time i write the new password two times.. and latter that error appears. 🤔

**Comment by LanikSJ** [comment]
I'll send you an email from the board let me know if you get it.

**Comment by LanikSJ** [comment]
Sent you another email with instructions.

**Comment by LanikSJ** [comment]
Okay there we go I saw a login that went through please confirm. 😁

**Comment by PIZZA90** [comment]
thanks! all ok LanikSJ 👍

**Comment by PIZZA90** [comment]
Antiadblock again...  needing account:

`https://www.atresplayer.com/flooxer/programas/unas/temporada-3/la-zowi_5f5601cb7ed1a8739ff7cf84/`

i test this filter and is working:

`atresplayer.com##+js(no-fetch-if, /conversion_async.js)`

Video-example with filter and no filter:

https://www.youtube.com/watch?v=E4EwIo_sOns
