### ISSUE TITLE
unblocked mid-article advertisement

### ISSUE THREAD

**Issue by feld** [uBlockOrigin/uAssets#767]
### URL(s) where the issue occurs

https://theoutline.com/post/2402/the-new-macbook-keyboard-is-ruining-my-life

### Describe the issue

Large animated ad in the middle of the page. Chews up lots of CPU.

### Screenshot(s)

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/1686547/31728858-1284c57c-b3f3-11e7-810a-6da0e29558f5.png">

### Versions

- Firefox 56.0
- uBlock Origin version: 1.14.15b1

### Settings

No changes made to settings

### Notes

Tried to use Picker to select the element and it failed miserably.

**Comment by mapx-** [comment]
```
||outline-brand.imgix.net$image
theoutline.com##.card-stack--fan.card-stack
theoutline.com##.general-disclaimer
theoutline.com##.stack-embed__headline
```
