### ISSUE TITLE
Menu icon is blocked on Google Maps in .pl domain

### ISSUE THREAD

**Issue by marcingarski** [uBlockOrigin/uAssets#7670]
### URL(s) where the issue occurs
`https://www.google.pl/maps/`

### Describe the issue
The menu icon (`https://fonts.gstatic.com/s/i/googlematerialicons/menu/v6/black-24dp/1x/gm_menu_black_24dp.png`) is blocked, if you visit `https://www.google.com/maps/ ` the same menu icon with the same URL is not blocked.
 

### Versions

- Browser/version: Firefox 78.0.2
- uBlock Origin version: 1.28.2

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/6ff5ebe73403cc64b9499026d8533211475b46ab

did you update unbreak list ?

**Comment by marcingarski** [comment]
After updating all lists Google Maps works fine.
