### ISSUE TITLE
all Videos on the www.chip.de site cannot be played

### ISSUE THREAD

**Issue by akks1981** [uBlockOrigin/uAssets#7672]
### URL(s) where the issue occurs

```
https://www.chip.de/news/Thunderbird-78.0-Riesen-Update-fuer-Gratis-Mailclient_138911396.html
https://www.chip.de/news/Firefox-und-Chrome-verlieren-im-Security-Check_182844419.html
https://www.chip.de/news/iOS-13.6-zum-Download-Neue-Features-fuers-iPhone_168719539.html
```

### Describe the issue

all Videos on the `www.chip.de` site cannot be played

### Screenshot(s)
-
### Versions

- Browser/version: [Firefox 79b7x64]
- uBlock Origin version: [uBlock Origin v1.28.5b0]

### Settings

uBlock Origin standard filter

### Notes
-

**Comment by mapx-** [comment]
with some delay but working
