### ISSUE TITLE
daimangajiten.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7674]
### URL(s) where the issue occurs

`https://daimangajiten.com/`
and its subpages

### Describe the issue

Annoyances: copy & context menu disabled with a popup message

### Versions

- Browser/version: Firefox 78.0.2
- uBlock Origin version: 1.28.2

### Settings

- Default + uBlock Annoyances

### Notes

Maybe
```
daimangajiten.com##+js(aeld, contextmenu)
daimangajiten.com##*:style(-ms-user-select:auto !important; -moz-user-select:auto !important; -webkit-user-select:auto !important; -webkit-touch-callout:defautl !important; user-select:auto !important)
```

**Comment by krystian3w** [comment]
typo: `defautl`...?

`https://dictionary.cambridge.org/dictionary/english/default`

---

other story is support Kiwi / Yandex / https://git.droidware.info/wchen342/ungoogled-chromium-android#user-content-extensions on mobile phones.

**Comment by krystian3w** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-touch-callout, https://caniuse.com/#search=touch-callout

Suggesting the tables we can remove this attribute in bulk from the filters: <ul> Apple on iOS Safari has a very limited "`Content Blocker`" API that only a simple cosmetic and network filter works.

**Comment by mapx-** [comment]
typo corrected, thx

**Comment by Yuki2718** [comment]
Thx!
