### ISSUE TITLE
dekki.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7675]
### URL(s) where the issue occurs

`https://dekki.com/en/?page=1`

### Describe the issue

Ads (more ads on Firefox than on Chromium)

### Screenshot(s)

Brave:

![dekki1](https://user-images.githubusercontent.com/58900598/87661640-e5f33100-c79b-11ea-9607-a5735a65f0c6.png)

Firefox:

![dekki2](https://user-images.githubusercontent.com/58900598/87661652-ee4b6c00-c79b-11ea-9b18-ee8aa624ffb9.png)

### Versions

- Browser/version: Firefox 78.0.2/Brave 1.10.97/Chrome 84.0.4147.89
- uBlock Origin version: 1.28.2/1.27.10/1.27.10

### Settings

- Default (+AG JPN)

### Notes

The ads are called from `https://cdn.dekki.com/assets/js/dekki.a5a2ca61ad.js` but the whole script can't be blocked. I wonder whether selectively blocking the ads is possible, rather than hiding, so reported here.

**Comment by mapx-** [comment]
`||cdn.dekki.com/assets/images/*/campaign/$image`
@ryanbr

**Comment by Yuki2718** [comment]
Ah, well that covers all, I was stupid.
