### ISSUE TITLE
Assets with UUID are blocked even if from own origin

### ISSUE THREAD

**Issue by stephanemagnenat** [uBlockOrigin/uAssets#7676]
### URL(s) where the issue occurs

`https://cand.li/runtime.html?game=e4885b062d295f68b92d1c54b254e856`

### Describe the issue

We are building a web-based game creation tool, and we serve game assets as UUIDs.

They are being blocked by the `EasyPrivacy` list:
```
Filter /^https?:\/\/.*\/(public|resources|static|assets)\/([a-f0-9]){28,32}$/$xmlhttprequest,1p
Filter list EasyPrivacy 
Context cand.li
Partyness(1) cand.li ⇒ cand.li
Type xhr
URL https://cand.li/api/assets/8ff9dc65046c52308aaf54586d8a040e
```
However, the source `EasyPrivacy` list has a slightly different rule that only applies to third-parties:
```
/^https?:\/\/.*\/(public|resources|static|assets)\/([a-f0-9]){28,32}$/$script,~third-party,xmlhttprequest
```
We updated the list today.

### Versions

- Browser/version: Firefox, 77.0.1.
- uBlock Origin version: v1.28.2

### Settings

- no change to default settings, just updated filters to their latest version.

### Notes

It seems to us that this blocking rule should indeed only apply to third-parties, as it is honest and genuine for a web site to serve its own assets as UUID.

**Comment by uBlock-user** [comment]
`~third-party` = `first-party` in blocking syntax fyi

@ryanbr
