### ISSUE TITLE
Youtube.com New Ad under Recommended

### ISSUE THREAD

**Issue by norsehealer** [uBlockOrigin/uAssets#7677]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Today I've noticed that youtube has an ad as the first Recommended video. There isn't a title.  using the Inspect feature of Chrome/Brave I see ad listed just after the <ytd-display-ad-renderer.

### A specific URL where the issue occurs

www.youtube.com

### Steps to Reproduce

1. [First Step] visit youtube.com
2. [Second Step] look at first 'recommend' video, you'll see no title but the 3 dots.

### Expected behavior:

I expect to not see this ad.

### Actual behavior:

I see this ad.

### Your environment

* uBlock Origin version: uBlock Origin v1.27.10
* Browser Name and version: Brave Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
* Operating System and version: Windows 10 some early build. i dont update it.

**Comment by devmattrick** [comment]
I can confirm this issue:
![image](https://user-images.githubusercontent.com/5848320/87740474-28fed580-c797-11ea-9356-765acdd4d511.png)

**Comment by gwarser** [comment]
This may work: 

to shift thumbnails to the left:

    youtube.com##ytd-rich-item-renderer:has(ytd-display-ad-renderer)

to leave empty space:

    youtube.com##ytd-display-ad-renderer

https://redd.it/hse8n7
