### ISSUE TITLE
alienwarearena.com annoying twitch player (consuming resource on low end machines)

### ISSUE THREAD

**Issue by aquila35** [uBlockOrigin/uAssets#7680]
### URL(s) where the issue occurs

[alienwarearena.com]

### Describe the issue

[On the main page of the alienwarearena.com there is an embedded twitch player. It is active 7/24 mostly promoting streamers, it auto plays and consuming CPU, searches for an active stream from their predefined streamers list indefinitely, makes it harder to load the page.]

### Screenshot(s)

[I believe it is not needed for this issue.]

### Versions

- Browser/version: [Firefox 78.0.2]
- uBlock Origin version: [1.28.2]

### Settings

[Default settings]
-

### Notes

[We can use "alienwarearena.com##^#twitch-player" to remove player.]

**Comment by mapx-** [comment]
you should try
`||player.twitch.tv/js/embed/v1.js$script,domain=alienwarearena.com`

eventually could be considered an annoyance @ryanbr
