### ISSUE TITLE
Photopea detects uBlock and presents a popup every 20s or so

### ISSUE THREAD

**Issue by BrandonDeaner** [uBlockOrigin/uAssets#7683]
### URL(s) where the issue occurs

`https://www.photopea.com`

### Describe the issue

Photopea detects uBlock and presents a popup every 20s or so.

### Screenshot(s)

https://imgur.com/a/uaTlZzq

### Versions

- Browser/version: [Chrome Version 83.0.4103.116]
- uBlock Origin version: [1.27.10]

### Settings

-

**Comment by Yuki2718** [comment]
I can't reproduce either. Do you really have uBlock filters enabled?

**Comment by llacb47** [comment]
https://github.com/NanoMeow/QuickReports/issues/2684#issuecomment-616601155

**Comment by BrandonDeaner** [comment]
Yes

**Comment by uBlock-user** [comment]
Can reproduce now, requires you to start a new project and play around for a while.

**Comment by photopea** [comment]
The first ad-blocking message is shown in Photopea after six seconds since opening. Then, every 30 seconds.
