### ISSUE TITLE
gamebanana.com

### ISSUE THREAD

**Issue by Tiagoquix** [uBlockOrigin/uAssets#7685]
### URL(s) where the issue occurs

https://gamebanana.com/

### Describe the issue

 

There is a message saying to please consider unblocking the site from the ad blocker.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/30274161/87887113-a07f6f80-c9f8-11ea-8371-d50cceebef7b.png)

### Versions

- Browser/version: Chrome 64 Bits 84.0.4147.89
- uBlock Origin version: 1.27.10

### Settings

I did not change anything from the default settings.

### Notes

None.

**Comment by uBlock-user** [comment]
Subscribe to uBlock Annoyances.
