### ISSUE TITLE
kabum.com.br is broken

### ISSUE THREAD

**Issue by Tiagoquix** [uBlockOrigin/uAssets#7686]
### URL(s) where the issue occurs

`https://www.kabum.com.br/`

### Describe the issue

 

When is your first time entering in this website, it becomes totally red (doesn't happen with the extension disabled). It wasn't happening before. It seems that uBlock is blocking ``themes.kabum.com.br``, which probably causes the issue.

And, when you properly generate the website's cache (by disabling uBlock and reloading the page), you can enable uBlock again and use it normally. However, a banner on the website becomes invisible.

### Screenshot(s)

Extension disabled (the website is working normally):
![image](https://user-images.githubusercontent.com/30274161/87976180-104a3480-caa3-11ea-9f99-dd888c13c86e.png)

Extension enabled (when entering the website for the first time):
![image](https://user-images.githubusercontent.com/30274161/87976732-fbba6c00-caa3-11ea-8dca-35efe24abf07.png)

Extension enabled (the website is working normally, but without the banner from the center of the screen. The banner is an animated banner.):
![image](https://user-images.githubusercontent.com/30274161/87977074-7be0d180-caa4-11ea-997b-f6318152bcb2.png)

### Versions

- Browser/version: Google Chrome - Version 84.0.4147.89 (Official version) 64 bits
- uBlock Origin version: 1.27.10

### Settings

I use the default settings.

### Notes

None.

**Comment by Tiagoquix** [comment]
@uBlock-user The animated banner stills invisible.

**Comment by Tiagoquix** [comment]
@uBlock-user The animated banner remains invisible.

**Comment by uBlock-user** [comment]
Did you update the uBlock unbreak list ?

**Comment by Tiagoquix** [comment]
> Did you update the uBlock unbreak list ?
> 
> "animated banner" is blocked by Easylist because it's an ad-banner ??

Yes I did update. And thank you for the explanation about the banner.
