### ISSUE TITLE
users.skynet.be now blocked in uBO by new list (Online Malicious URL Blocklist)

### ISSUE THREAD

**Issue by Procyon-b** [uBlockOrigin/uAssets#7687]
### URL(s) where the issue occurs

All users' sites on `http://users.skynet.be/`
For real sites you can find a list in this message on one of this ISP boards `https://fr.forum.proximus.be/internet-10/sites-users-skynet-be-en-panne-50507?postid=685545#post685545`. (I didn't want to promote my personal page here)

### Describe the issue

 
"users.skynet.be" belongs to ISP Proximus, one of the big ISP of Belgium. It is one of the oldest name of that provider and is hosting users' personal pages.

With uBO replacing "Malware Domain List" and "Malware domains" by "Online Malicious URL Blocklist", this site is now blocked.

### Versions

- Browser/version: chrome
- uBlock Origin version: 1.27.10

### Settings

- "Online Malicious URL Blocklist" is used

### Notes

Can this be temporarily fixed in uBO while I try to investigate the issue with `https://gitlab.com/curben/urlhaus-filter#urlhaus-malicious-url-blocklist`?
But with only 17 issues archived on the site, I'm not sure that it's the right place to do it. (I won't have time to do it today anyway).

Can someone here contact them directly to at least know which site is malicious?

**Comment by okiehsch** [comment]
>Can someone here contact them directly to at least know which site is malicious?

I guess `https://urlhaus.abuse.ch/browse.php?search=skynet.be`

**Comment by okiehsch** [comment]
I blocked that page specifically.
 `http://users.skynet.be` should not be strict blocked if you update `uBO-unbreak`.

**Comment by Procyon-b** [comment]
It works correctly now. Thanks

> I guess `https://urlhaus.abuse.ch/browse.php?search=skynet.be`
> Specifically `http://users.skynet.be/crisanar/` a site that offers software cracks.

I searched only on gitlab.

**Comment by uBlock-user** [comment]
@curbengh

**Comment by gwarser** [comment]
Has VirusTotal report https://www.virustotal.com/gui/file/69bed44509161a6f3c25d2e51d56aceee84315baf75ee93364511d457cefb190/detection

**Comment by curbengh** [comment]
[Added](https://gitlab.com/curben/urlhaus-filter/-/commit/2ac6e89b77d196c64af7a55998ad4ad8664350e2) `users.`[skynet.be](https://en.wikipedia.org/wiki/Proximus_Skynet) to exclusion list. Blocklist is scheduled to be updated in 2 hours.

> But with only 17 issues archived on the site, I'm not sure that it's the right place to do it.
I would advice users to raise future issue to https://gitlab.com/curben/urlhaus-filter as I closely monitor that repo.
