### ISSUE TITLE
www.oploverz.in [annoyance popup]

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#7688]
`https://www.oploverz.in/`

### Versions

- Browser/version: [Firefox 78.0.2 x64]
- uBlock Origin version: [1.28.2]

### Settings

- https://pastebin.com/raw/n8AbtXGp

**Comment by kurosaki98** [comment]
Can't confirm it, using your own settings. the best you can try purge all cache and tap update maybe can solved and don't forget clear cache browser

**Comment by exodius48** [comment]
> 
> 
> Can't confirm it, using your own settings. the best you can try purge all cache and tap update maybe can solved and don't forget clear cache browser

Need sometimes until popup appear.
Here for the vid: http://s000.tinyupload.com/index.php?file_id=96628439905637128416
Just skip till minuute 1:50
