### ISSUE TITLE
space.com

### ISSUE THREAD

**Issue by nu8** [uBlockOrigin/uAssets#7689]
> AD BLOCKER INTERFERENCE DETECTED

`https://www.space.com/apollo-11-disaster-deepfake-video-tech.html`

**Comment by mapx-** [comment]
Did you enable `uBlock filters – Annoyances` ?

**Comment by nu8** [comment]
Still a problem with the Filter you suggest

**Comment by nu8** [comment]
This seems to resolve it:

1. Dashboard
2. Filter lists
3. Annoyances
4. AdGuard Annoyances

**Comment by mapx-** [comment]
provide the necessary info: broser / uBO versions, test using default setup + uBO annoyances list

**Comment by nu8** [comment]
This seems to resolve it:

1. Dashboard
2. Filter lists
3. Annoyances
4. AdGuard Annoyances
