### ISSUE TITLE
infighting between ublock origin and umatrix

### ISSUE THREAD

**Issue by Zhangsun321** [uBlockOrigin/uAssets#769]
https://i.imgur.com/uy4qLMd.png
has only started as of late... with the whole mess on twitter.. with the google analytics stuff

**Comment by okiehsch** [comment]
This is not a filter issue and has been reported to uBlocks issue tracker many, many times.
Duplicate of https://github.com/gorhill/uBlock/issues/1170 and https://github.com/gorhill/uBlock/issues/3041 and the list goes on.
