### ISSUE TITLE
Gelbooru [NSFW]

### ISSUE THREAD

**Issue by Jorge9811** [uBlockOrigin/uAssets#7694]
### URL(s) where the issue occurs

`https://gelbooru.com/index.php?page=post&s=view&id=5428643`

### Describe the issue

The picture does not appear and an advertising banner appears on the page.

### Screenshot(s)

With uBlock Origin enabled:
![firefox-2020-07-22_14-12-56](https://user-images.githubusercontent.com/54429803/88207095-aa39ea80-cc25-11ea-81b3-4fa5a26fe461.png)

With uBlock Origin disabled:
![firefox-2020-07-22_14-13-04](https://user-images.githubusercontent.com/54429803/88207107-ae660800-cc25-11ea-8384-f7d9222c1abb.png)

### Versions

- Browser/version: Mozilla Firefox v78.0.2 x86
- uBlock Origin version: 1.28.2

### Settings

https://i.imgur.com/WQZrluK.png

Because I'm using Nano Defender, I also have userResourcesLocation adjusted accordingly.

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
I added a filter for the ads at the top but the page is ok on my side.
Test using the default lists / settings

**Comment by Jorge9811** [comment]
It turns out that somehow, I had some filters for Gelbooru added to My Filters that were blocking out the pictures. I don't know how did that happen, but I feel extremely dumb. Sorry. I'm closing this right away.
