### ISSUE TITLE
slickdeals.net

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#7695]
### URL(s) where the issue occurs

`https://slickdeals.net/forums/register.php?do=change_username_eor` 
 Need to be logged in.

### Describe the issue

Cannot change username.

### Notes

`@@||slickdeals.net/scripts/306/SD_Analytics.js?8346$script,1p`
`@@||slickdeals.net/scripts/306/js-campaign-tracking.js?8346$script,1p`

**Comment by okiehsch** [comment]
Does the redirection work?
````
||slickdeals.net/scripts/*/SD_Analytics.js$script,1p,redirect=noop.js
||slickdeals.net/scripts/*/js-campaign-tracking.js$script,1p,redirect=noop.js
````

**Comment by terrorist96** [comment]
Yes.
