### ISSUE TITLE
phimmedia.info

### ISSUE THREAD

**Issue by vothisau** [uBlockOrigin/uAssets#7697]
I still see many Ads on `https://www.phimmedia.info/`, please fix it.

**Comment by mapx-** [comment]
You should report here:
```
CONTACT INFOMATION

Any inquiries or contributions you may send via email: support@abpvn.com
Or Fanpage: ABPVN Facebook fanpage: https://www.facebook.com/abpvn.org
```

However you can add as custom filters:
*.gif$domain=phimmedia.info,image
phimmedia.info##[target="_blank"]

**Comment by mapx-** [comment]
I'll add a fix for anti right click in annoyances list

**Comment by mapx-** [comment]
"Done in ABPVN List" => from  `ABPVN List` maintainer
