### ISSUE TITLE
ionos.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#7699]
### URL(s) where the issue occurs

`https://www.ionos.de/digitalguide/online-marketing/web-analyse/browser-fingerprinting-tracking-ohne-cookies/`

### Describe the issue

scroll blocked
### Versions

- Browser/version: Firefox 78.0.2
- uBlock Origin version: v1.28.4

### Settings

default with `uBlock filters – Annoyances` enabled

**Comment by okiehsch** [comment]
Caused by a filter in `uBO-annoyances`, I will fix it in that list.

**Comment by krystian3w** [comment]
Pop-up back in right corner due remove bad generic `###bio_ep, #bio_ep_bg` (no protected to detect locked scroll by `:not(..., ...)`.

I recommend join all `+js(nostif, bioEp.showPopup)` into one file with many link headers.

Also kei.pl no longer have bioEp in code as active so possible remove undeded unlocking scroll, due `auto` can break scrolling if custom webmaster on subdomain enfroced e.g. `visible` / `scroll` value.
