### ISSUE TITLE
Chart buttons not working on finanzen.net

### ISSUE THREAD

**Issue by tobbi** [uBlockOrigin/uAssets#77]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
http://www.finanzen.net/devisen/britische_pfund-euro-kurs

### Describe the issue
Clicking the "Push", "Intraday", "1 Woche", "3 Wochen"... headers doesn't work with uBlock Origin 1.7.7. The chart stays as it is.

### Versions

- Browser/version: Firefox Nightly 50.0a1 (2016-07-03)
- uBlock Origin version: 1.7.7

### Notes
Unfortunately, I can't find which file the JS belongs to that isn't being loaded (or whatever the problem is), so you need to investigate yourself. I checked the JS files blocked by uB0, and those appear to be ad-related ones.

**Comment by gorhill** [comment]
EasyPrivacy's `||googletagmanager.com/gtm.js?$third-party` is causing the issue, report to maintainers: <https://forums.lanik.us/viewforum.php?f=64>.

Solution: `@@||www.googletagmanager.com/gtm.js$script,domain=finanzen.net`.

**Comment by tobbi** [comment]
Thanks!
