### ISSUE TITLE
add to resource abuse list pls

### ISSUE THREAD

**Issue by Zhangsun321** [uBlockOrigin/uAssets#770]
https://authedmine.com/
coin miner.. 'opt in my ass'....

**Comment by jspenguin2017** [comment]
The opt in is not bypassable by the site using it after a quick analysis, it is shown in a secure `iframe`. The whole point of resource abuse list is so that mining becomes opt-in, I don't think this as a threat until they start abusing it.

**Comment by okiehsch** [comment]
I agree with @jspenguin2017, I had a look at `https://authedmine.com` yesterday and unless someone can provide an example of a site using `authedmine` without an explicit opt-in, I will not add it to the resource abuse list.

**Comment by Zhangsun321** [comment]
ok.... understood...

**Comment by uBlock-user** [comment]
The notice is cookie based. As long as the cookie and site data is NOT removed after being permitted once, it won't ask and will start mining.

**Comment by jspenguin2017** [comment]
They said on their website that the cookie is valid for up to 24h.

**Comment by lain566** [comment]
@okiehsch This, for example

`https://mylink.st/OqQzF7J`
<details>

![ublock _ _registro_de_peticiones_de_red_-_google_c_2017-10-19_23-41-12](https://user-images.githubusercontent.com/27441315/31795692-17a6ae14-b527-11e7-9d64-a5d580a61309.png)
</details>

**Comment by jspenguin2017** [comment]
Well, if you click the Captcha, it's like giving consent. It does not load CryptoNight before you click it. 
![image](https://user-images.githubusercontent.com/7283682/31796992-30c7939c-b4e9-11e7-91dc-f55de626c915.png)

**Comment by okiehsch** [comment]
Correct me if I am wrong but it looks to me like all mylink.st-links will only be displayed after you mine for some time, so blocking `authedmine.com` makes `mylink.st` non-functional.

**Comment by jspenguin2017** [comment]
I'll exclude `authedmine.com` from my filters until I can see by myself that it mines automatically without letting you know. 
I consider a Captcha box to be enough of a consent.

**Comment by lain566** [comment]
@jspenguin2017 Of course, I clicked, but not everyone is informed about this.

**Comment by jspenguin2017** [comment]
@lain566 
The box itself is enough of a consent IMO, disabling uBO was used as a "consent box" because for those automatic miners we didn't really have other choices. But the side effect is that trackers and other stuff are unblocked as well, and when the Captcha finishes, you get redirected and you'll have a white list that you need to go into uBO settings panel to remove. 
It's just my opinion and I'm OK with what ever @okiehsch does.

**Comment by okiehsch** [comment]
In the end it is @gorhill decision, but like I said I agree with @jspenguin2017

**Comment by lain566** [comment]
@jspenguin2017 That captcha has changed, before, they used `coinhive.com`, now they use this `authedmine.com`, I guess it's a tactict, I never said that this should be blocked, I thought there was a solution, to pass without loading cryptonight

**Comment by jspenguin2017** [comment]
A solution to bypass it? Where?

**Comment by terrorist96** [comment]
@okiehsch the `https://mylink.st/` site has anti-adblock as well.

**Comment by jspenguin2017** [comment]
Yea, it's Antiblock.org v3.

**Comment by okiehsch** [comment]
mylink.st##script:inject(abort-current-inline-script.js, document.getElementById, nextFunction())
will lead to 
![unbenan](https://user-images.githubusercontent.com/16838044/31800622-5cc7f082-b542-11e7-8bbd-8dc526bb263b.PNG)

`@@||mylink.st^$generichide` works  on my end.

**Comment by terrorist96** [comment]
@okiehsch There's also some VPN ads after you "prove you're human" (i.e. mine for like 20 seconds).
![image](https://user-images.githubusercontent.com/12802056/31800728-e4af1a34-b510-11e7-8839-e03398c14026.png)

**Comment by jspenguin2017** [comment]
> after you "prove you're human" (i.e. mine for like 20 seconds).

I don't have any analysis data, but I think a Captcha like that is effective, since botnets are usually only composed of low power (IoT) or old and broken systems, neither is able to quickly mine coins. And if there are many requests from one IP they can just raise the difficulty to slow you down.

**Comment by SMed79** [comment]
@okiehsch The `$generichide` filter does not fix anti adblock for me.
need `@@.png#$image,domain=mylink.st`

- http://i.imgur.com/C3RIKMc.png
- http://i.imgur.com/57eXzWm.png

**Comment by jspenguin2017** [comment]
Actually, just `mylink.st###y219` would work, the ID is static after installation.

**Comment by okiehsch** [comment]
`mylink.st###y219` does not reliably work on my end, I sometimes get a blank screen, so I added the redirect. https://github.com/uBlockOrigin/uAssets/commit/e308746e8f11359f3da2f4f93986ae77ee463e78

**Comment by uBlock-user** [comment]
They're holding the link hostage unless you mine for them, same as `cnhv.co` Nope, not gonna whitelist it.

**Comment by ghajini** [comment]
Is there any global script based approach to stop these .....Like "no popup" switch present in ublock origin....they can use random domains ,every time can't block domains......
https://blog.eset.ie/2017/09/15/cryptocurrency-web-mining-in-union-there-is-profit/

**Comment by uBlock-user** [comment]
Some interesting discussion going around on bug tracker - https://bugs.chromium.org/p/chromium/issues/detail?id=766068

**Comment by gorhill** [comment]
> Is there any global script based approach to stop these

I did implement a `no-web-workers` switch at some point: <https://github.com/uBlockOrigin/uAssets/issues/690#issuecomment-330401913>. Typically coin miners use web workers, though some may use `setTimeout`, but that last one is more difficult to abuse because it can cause lot of janks on a page. The problem with the `no-web-workers` switch is that it can't be implemented in Firefox, has it does not yet support the `worker-src` CSP directive required to block web workers.

**Comment by gwarser** [comment]
Firefox have `dom.workers.enabled` in `about:config`, but this will break a lot.

**Comment by uBlock-user** [comment]
It's WIP at FF - https://bugzilla.mozilla.org/show_bug.cgi?id=1302667

**Comment by jspenguin2017** [comment]
> Some interesting discussion going around on bug tracker - https://bugs.chromium.org/p/chromium/issues/detail?id=766068

Browser level interventions ain't going to work. Implement it and I'll get you 3 ways to get around it.

**Comment by Hrxn** [comment]
I'd disagree here.

If our browser makers would _really_ want to do something about stuff like this, they would.
But they lack the cojones.
They could change all of this, autoplay etc. to make it click-to-play. Everything, without exception. Hard whitelist for everything, for every site. 
Maybe their realization will kick in, sooner or later.

**Comment by jspenguin2017** [comment]
Sounds good in theory, not going to happen without help from AI. It is an unreasonable amount of work to police every website, and good luck operating on a white list, every time someone updates his website, it breaks in your browser. 
If you think it's doable, I'd like to see you implement it.

**Comment by Hrxn** [comment]
Huh? AI?

By whitelisting, I mean to whitelist by the user, i.e. manually. That's definitely doable.

I always wanted to write my own web browser, sure.

**Comment by uBlock-user** [comment]
All of these clones are bent on manipulating users to mine Monero coins for them which they should be doing rather on their own and on their own rig, also all the tools they need are available on Monero's official page.

**Comment by jspenguin2017** [comment]
@Hrxn So you mean every user will maintain their own filter list? That's really a lot of work for the user, and most people wouldn't have enough knowledge about web development to make a good decision.

**Comment by Hrxn** [comment]
No, I mean that the browser should keep and maintain those lists, basically. Similar to what browsers actually do right now, by setting content options (JS, images, cookies etc.) on a per-site basis. Although that is buried deep in the settings menus.

All that is needed is some form of UI element, a prompt, if unobtrusive, or better some notification "area" as part of the address bar or something, that asks the user for permission, i.e. "Allow this site to use Auto-play/Web Workers/WebRTC and whatever else". No need to know anything about web technologies, only necessary to know if you can trust a site. This could optionally be limited to secure sites with EV certificates or something, which can be overridden of course, for more advanced users. This is only a question of doing the User Experience right, everything else should be straightforward.

**Comment by jspenguin2017** [comment]
> Similar to what browsers actually do right now, by setting content options (JS, images, cookies etc.) on a per-site basis. 

So the browser *stores* the filter (or permission rules) list and the user set them on a per-site basis? That's literally the definition of maintained by the user. 
If you mean preloaded permission settings, then Brave has it, and... that's it. Pretty much none of the other browsers have them. Browsers right now have only one default permission settings and it apply to all websites unless the user manually update (maintain) it. 

> No need to know anything about web technologies, only necessary to know if you can trust a site. 

Given a website, how do you know if you can trust it? And how many people even know what web workers and WebRTC are?

**Comment by okiehsch** [comment]
@gorhill `EasyPrivacy` has added the filter `||authedmine.com^$third-party`, apart from the fact that an explicitly opt-in miner shouldn't be blocked in my opinion, this filter makes sites like
`mylink.st/OqQzF7J` non-functional with uBO-default settings.
Would you agree to adding `||authedmine.com^$third-party,badfilter` to `uBO-unbreak`?

**Comment by SMed79** [comment]
The content is **blocked** and the mening is **forced**. In my opinion, the `opt-in` here is just replacing an anti-adblock.

What if an adserver adopte the same approach?

**Comment by okiehsch** [comment]
I can see your point and I would have no problem adding 
`||authedmine.com^$third-party,domain=example.com`, I just don't think the uBO-default setup should block an explicitly opt-in miner.

**Comment by SMed79** [comment]
> uBO-default setup should block an explicitly opt-in miner.

If they are not used to block the content.

**Comment by okiehsch** [comment]
I already said, I agree that using a miner as a defacto "paywall", should not be allowed by uBO, but right now, all `authedmine` opt-in usage is blocked by `uBO-default` setup, which removes the choice of all "normal" uBO users.

**Comment by gorhill** [comment]
> Would you agree to adding `||authedmine.com^$third-party,badfilter` to uBO-unbreak?

Yes, if it's entirely opt-in in a respectful way, there is not point blocking this. Was this added because of an instance of the miner being not respectful?

**Comment by jspenguin2017** [comment]
I think EasyPrivacy blocks everything that would send the performance data of your device to a third party.

**Comment by okiehsch** [comment]
The commit message states that they sync  with the [adblock-nocoin-list](https://github.com/easylist/easylist/commit/3ef91c1515ea2490da5d5022a85ef473a25394fc) or sync with ["mining servers"](https://github.com/easylist/easylist/commit/ce27cb3a0702ad67b8bfd211f2ce11d557aad95f).

**Comment by gotitbro** [comment]
@okiehsch @gorhill I came upon a website that uses authedmine. And even if you click "Cancel" to disallow mining it keeps asking again and again but does not ask again and again if you allow it.

@coinhive-com You might want to take a look at this behavior. If a users disallows mining it shouldn't ask repeatedly.

**Comment by gorhill** [comment]
Consider this a web site error, that's completely out of the scope of the repo here, its purpose is not to fix site's coding errors.

**Comment by gotitbro** [comment]
@gorhill Seems like they, authedmine, don't store a cookie when a user disallows the mining request. Just wanted to bring that to attention as it was being considered to be whitelisted.

If another website can be seen with same authedmine behavior then we can say for sure if they repeatedly ask for mining.

**Comment by coinhive-com** [comment]
The AuthedMine library provides functionality to test for opt-outs before showing the popup again, as [detailed in the docs](https://coinhive.com/blog/best-practices), e.g.:

```js
// Only start on non-mobile devices and if not opted-out
// in the last 14400 seconds (4 hours):
if (!miner.isMobile() && !miner.didOptOut(14400)) {
	miner.start();
}
```

**Comment by jspenguin2017** [comment]
@gorhill Maybe they did it on purpose? It keeps poping up in order to pressure the user to click allow? 

@coinhive-com You need to enforce a cooldown for asking again, you can't expect websites to responsibly use your API to check for opt out.

**Comment by uBlock-user** [comment]
Abusal of API is nothing new, this was bound to happen at some point.

**Comment by gotitbro** [comment]
@uBlock-user Sorry didn't get that. Who's evading what?
