### ISSUE TITLE
webstreamlive.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#7700]
### URL(s) where the issue occurs

`webstreamlive.com/dci/in/260720`

### Describe the issue

Unable to login/(insert email ID) to website due to blockade of ipstack.com from Peter Lowe's list

### Screenshot(s)

**Ublock enabled**

I can't enter anything in this box

![Screenshot_2020-07-26-16-19-54-267_org mozilla firefox](https://user-images.githubusercontent.com/20338483/88477294-6ebc5a80-cf5c-11ea-84d1-04433c9171e4.png)

**Ublock disabled=**
I can enter email id

![Screenshot_2020-07-26-16-22-22-540_org mozilla firefox](https://user-images.githubusercontent.com/20338483/88477307-aa572480-cf5c-11ea-9990-d6c8b24ebff5.png)

### Versions

- Browser/version: firefox stable
- uBlock Origin version: ubo dev

### Settings

 uBO's default settings
-

### Notes

1. Live session, I don't know whether URL accessible to you after live ends

2. Also why green allow rule coloumn is removed from ubo popup screen, its completely useless to click grey button and that doesn't work
So removing green allow rule is completely disastrous for me....although I can simplety whitelist website. .....
@gwarser

**Comment by uBlock-user** [comment]
Breakage caused by `||ipstack.com^` in Peter Lowe's list,

> its completely useless to click grey button and that doesn't work

noop button doesn't unbreak breakage caused by static filters. It's meant to disable Dynamic Filtering only.

**Comment by ghajini** [comment]
So allow  green coloumn not work?

**Comment by mapx-** [comment]
@ghajini see how to have back the green button
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide#allow-rules

**Comment by mapx-** [comment]
@ryanbr maybe you could add to EP this exception
`@@||api.ipstack.com/check?access_key=$xhr`
