### ISSUE TITLE
Video play is loading to infinite

### ISSUE THREAD

**Issue by AndRo-Marian** [uBlockOrigin/uAssets#7702]
### URL(s) where the issue occurs

Found another post here: https://github.com/uBlockOrigin/uAssets/issues/6223

### Describe the issue

When playing the video on Netu the video is loading to infinite and the prompt to seek to where i left of not appear.

### Screenshot(s)

Not sure if needed for now.

### Versions

- Browser/version: Firefox
- uBlock Origin version: 1.28.4

### Settings

Default

### Notes

Seams the issue to be from: hqq.*##+js(aopr, console.clear)

**Comment by mapx-** [comment]
provide an example video (which is playing fine when uBO is disabled)

**Comment by AndRo-Marian** [comment]
The video from the other issue http://cablehd.online/directv-sports-en-vivo/ works fine if i remove the `hqq.*##+js(aopr, console.clear)` from list.

**Comment by okiehsch** [comment]
I only get a blank video but with the filter `hqq.*##+js(aopr, console.clear)` in place I can reproduce the infinite loading screen.

**Comment by mapx-** [comment]
> blank video

the reason I asked a real example video

**Comment by AndRo-Marian** [comment]
What you mean a real video?
Is that fake or what you don't understand ?

**Comment by ghajini** [comment]
possibly subsites of hqq.tv/waaw.*/netu.in etc
video embed `https://gotoons.org/e/dGFHcXlaRmU0a0d1cGVWZmpYSDlhUT09`
here `https://www2.123movies.movie/love-weddings-and-other-disasters-2020/`

this 
`||gotoons.org/js/optscript/script-2.12.5.js$script,1p or gotoons.org##+js(nowoif)` &

`||gotoons.org/cdn-cgi/trace$xmlhttprequest,1p`

**Comment by ghajini** [comment]
there are more crapy mirrors of `waaw` 
`https://www.movi.pk/naxalbari-2020-hindi-season-1-complete-2/`

popups from `https://player.movi.pk/e/bjllbGZtc1VsNDFaNUV5eVVkY2FuZz09`

**Comment by ghajini** [comment]
Popups ,sometimes valid video embed site is closed
From `https://openload.casa/f/LUvkEr7yKfNe` found here `https://123movies.ar/movie/love-lights-hanukkah/`

**Comment by mapx-** [comment]
> sometimes valid video embed site is closed

some more details, steps ?

**Comment by ghajini** [comment]
Its just firefox odd behaviour due to popunders
ie valid video site is closed and popups in new tab....defusing via `nowoif` work

**Comment by ghajini** [comment]
`@@||hqq.tv^$xmlhttprequest,1p` in ublock filters leads to whitelist of `https://hqq.tv/cdn-cgi/trace`
Test link = `https://www2.5movierulzfree.me/bigg-boss-2020-telugu-season-4-day-100/full-movie-watch-online-free.html`
hqq.tv player 1

**Comment by ghajini** [comment]
**NSFW**
`https://waaw1.tv/watch_video.php?v=UkDOe6YBZNEv`

Popup ads

**Comment by ghajini** [comment]
`http://waaw.to/f/HeCjEmAFjyCl`

Clicking many times, playback doesn't start.....
Start when manually whitelist site, then again ublock activated on this site (no whitelist), playback start....any workaround(just click click click and get frustrated)

**Comment by mapx-** [comment]
maybe you should clear all storage (cache + cookies), after that is working fine

**Comment by ghajini** [comment]
These web players of (past and present ) openload,streamango,waaw,netu,hqq always gave these frustrating problem(click,click,click)

**Comment by ghajini** [comment]
`https://ply.msubplix.com/watch_video.php?v=VG93b0V5Uk9hKzFUZTBxbDUvUXpVRGVOYlFVV1lVZkYvNEtqcnR6OHpTeEdFQVVWUDRmQjdFQ2I2TGZmL0ppNQ%3D%3D#iss=MTUyLjU3LjEyNS40Mg==`

link came from `https://ww1.movisubmalay.me/legenda-puteri-felora/` server 1

popup ads

``
ply.msubplix.com##+js(window.open-defuser.js)
||ply.msubplix.com/cdn-cgi/trace$xhr,domain=ply.msubplix.com
``

**Comment by ghajini** [comment]
popup ads ,variant of waaw

`https://oyohd.com/e/aFIvRk5GOUoyeHQ3QkJlV0xXeUo3dz09`
link came from 
`https://www.bolly2tolly.tv/movie/vaanku-2021-hd`

these work
```
oyohd.com##+js(nowoif)
||oyohd.com/cdn-cgi/trace$xhr,1p
```

**Comment by ghajini** [comment]
popup ads ,variant of waaw

`http://netu.view47.com/f/4qTcLFcaxJMC`

Link came from
`http://www1.movie25com.com/watch/the-howling-2020.html`

These work
```
netu.view47.com##+js(nowoif)
||netu.view47.com/cdn-cgi/trace$xhr,1p
```

**Comment by ghajini** [comment]
popup ads ,variant of waaw

`https://ply.mp4cage.com/e/S1BOKy93aEZjUTdLWUFjWkxEbi94UT09`

Link came from
`https://curimovie.link/movies/kya-kehna/`

This work
```
ply.mp4cage.com##+js(nowoif)
||ply.mp4cage.com/cdn-cgi/trace$xhr,1p
```

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/108470797-cae52400-728a-11eb-9d7e-ce5dfc79b5db.png)

**Comment by ghajini** [comment]
context menu block & site says 'Don't open developer tools'
```
https://hqq.tv/player/embed_player.php?vid=2zqnJWxSr2pV
https://www22.movierulzfree.is/waaw/?l=2zqnJWxSr2pV
```

firefox stable 97
