### ISSUE TITLE
verizon.com/speedtest

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#7706]
### URL(s) where the issue occurs

`https://www.verizon.com/speedtest/`

### Describe the issue

Speed test won't commence.

### Notes

`@@||www.verizon.com/speedtest/newdesign/scripts/siteCatalyst.js$script,1p`

**Comment by llacb47** [comment]
Test `verizon.com##+js(set, newPageViewSpeedtest, noopFunc)`

**Comment by terrorist96** [comment]
Doesn't work.

**Comment by llacb47** [comment]
Works for me 🤷‍♂️

**Comment by terrorist96** [comment]
Actually it works. The site is just trash.
