### ISSUE TITLE
How do we get off the blacklist?

### ISSUE THREAD

**Issue by mreilytechler** [uBlockOrigin/uAssets#7707]
### URL(s) where the issue occurs

```
https://phr2.charmtracker.com/login.sas
https://ehr2.charmtracker.com/ehr/main.do
https://phr.charmtracker.com/login.sas?serviceurl=%2Fmain.do
http://ehrdemo.weebly.com/schedule-appointment.html

```
### Describe the issue

My customers call me every day with these issues about Ublock origin and other services blocking our website.

It has been bothering us for a while. it seems to do with the pages logging in will not display entirely.

While white-listing or turning off Ublock origin entirely solves the problem, I'd like to see us get to the bottom of this. Our company is not in the business of selling user data. Charm Health is a SAAS product made to service Doctors and Patients. We make money from selling services to our customers so that they can service their customers.

If we are on the black list, is there a way to get removed? Ublock origin is a very popular ad blocker and installed on Google chrome by default. We want to make it work for the most commonly used browsers to service our customers without too much complexity for users to use. 

### Versions

- Browser/version: Firefox and Google chrome (i think the most recent versions) This is a common issue.
             recently tested on Firefox 78.0.2 (64-bit)

- uBlock Origin version: uBlock Origin v1.28.4 (perhaps some others too)

### Settings

These are the default settings in most of these browsers
-

### Notes

These issues can be resolved if the clients add the following to the whitelist:

for the patient portal pages:
phr.charmtracker.com
phr2.charmtracker.com

for the EHR pages:
ehr.charmtracker.com
ehr2.charmtracker.com

I"m still not sure how to make work for http://ehrdemo.weebly.com/schedule-appointment.html (a testing site with an iframe hosted by us. Many of our customers schedule appointments for their business with our iframe scheduler.) We have to disable Ublock origin entirely for it to work.

**Comment by mreilytechler** [comment]
Please give a recommendation for how to make our customers work with both Ublock Origin and Charm.

**Comment by uBlock-user** [comment]
force update uBO Unbreak list in a while for the fix.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/f8267a4c8ac859602482350ff6debc9751cbe387
