### ISSUE TITLE
pinterest.dk

### ISSUE THREAD

**Issue by Toshiba1127** [uBlockOrigin/uAssets#7708]
### URL(s) where the issue occurs

`https://www.pinterest.dk/pin/380906080983580813/`

### Describe the issue

Ask me to login and a bigger dialog appear if you scroll down
I don't want to login because I know it's a trick to collect more data. Is it possible to bypass it?

### Screenshot(s)

![image](https://user-images.githubusercontent.com/64008639/88817414-c4dc0880-d1bd-11ea-8816-373e14239ff6.png)

![image](https://user-images.githubusercontent.com/64008639/88817363-b5f55600-d1bd-11ea-87d0-204461cd36b8.png)

### Versions

- Browser/version: Chrome 84.0.4147.89
- uBlock Origin version: v1.28.4

### Settings

- All defaults

**Comment by mapx-** [comment]
enable `uBlock filters – Annoyances`
