### ISSUE TITLE
coolermaster.com

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#7709]
### URL(s) where the issue occurs

`https://www.coolermaster.com/power-supply-calculator/`

### Describe the issue

Breakage: The power supply calculator doesn't load.

### Versions

- Browser/version: Firefox 79.0
- uBlock Origin version: 1.28.4

### Settings

Default

### Notes

Strangely the logger didn't show me any blocked requests. Experimenting with the filter lists indicates that breakage occurs after enabling either `uBO Privacy`, `EasyPrivacy` or `Adguard Tracking Protection`.

**Comment by tmccombs** [comment]
This appears to be broken again.
