### ISSUE TITLE
new miner: coinerra.com

### ISSUE THREAD

**Issue by b1nary** [uBlockOrigin/uAssets#771]
### URL(s) where the issue occurs

`https://coinerra.com/`

### Describe the issue

The site is a new service just like coinhive.com

### Notes

Seems to be just like `coinhive.com`

**Comment by b1nary** [comment]
i am stupid ... already there

**Comment by SMed79** [comment]
https://github.com/uBlockOrigin/uAssets/issues/754#issuecomment-338064784
