### ISSUE TITLE
Warning to accept cookies at https://bitly.com/ 

### ISSUE THREAD

**Issue by Jose1971AB** [uBlockOrigin/uAssets#7712]
Hey, guys, good night. 

### URL(s) where the issue occurs

[https://bitly.com/]

### Describe the issue

The warning to accept cookies appears at [https://bitly.com/] 

I have used Block Item Mode, Delete Item Mode and Select Item Mode without success, when you reload the page or open it in a new tab it appears again.

### Screenshot(s)
![3](https://user-images.githubusercontent.com/44229110/88970126-2bdae980-d2b2-11ea-96b3-46ed5a0531f8.jpg)

### Versions

- Browser/version: [Firefox 64-bit 79.0]
- uBlock Origin version: [v1.28.4]

### Settings

![2-uBloc Predeterminados](https://user-images.githubusercontent.com/44229110/88970365-968c2500-d2b2-11ea-98c0-2b8e2d815f4d.jpg)

### Notes

Good night and a greeting

**Comment by mapx-** [comment]
add
```
bitly.com###banner-cookie
bitly.com###banner-spacer
```

@ryanbr

**Comment by Jose1971AB** [comment]
Hello @mapx-, good afternoon.

I don't know if I did anything wrong. I suppose it was to add to the section of My filters, but **the warning to accept cookies still appears.**. And I've reloaded the page several times, both uBlock and [https://bitly.com/] 

> add
> 
> ```
> bitly.com###banner-cookie
> bitly.com###banner-spacer

**Is it in the section of My filters where I have to include them?** Look at the image

![BB](https://user-images.githubusercontent.com/44229110/89064354-2640da80-d36a-11ea-8d9f-6d10bcbe25f8.jpg)

Greetings, my friend.

**Comment by mapx-** [comment]
working fine on my end

**Comment by gwarser** [comment]
@Jose1971AB is cosmetic filtering enabled? Is My filters list selected in Filter lists tab?

**Comment by Jose1971AB** [comment]
Hey, buddy, good night.

**Still not working**

@mapx-

>working fine on my end

I don't understand @mapx-, I don't know what could be happening. I don't know why it works for you and not for me.

@gwarser

> @Jose1971AB is cosmetic filtering enabled? Is My filters list selected in Filter lists tab?

Do you mean this? If that's it, marking it disables it, right? Then I think it's okay. **I have it like this**

![bb](https://user-images.githubusercontent.com/44229110/89080114-48495580-d388-11ea-8b28-d9336b483941.PNG)

I'm a basic user and I may say something crazy, but could it be the IP... that it won't work the same in different countries? I don't understand.

Greetings friends

**Comment by gwarser** [comment]
Exceptions in AdGuard lists:

	[rdk@on filter-lists-tools-git]$ grep -r '#@##banner-cookie'
	filterlists.com_resources/2191_AdGuard Annoyances Filter (Optimized).txt:bitly.com#@##banner-cookie
	filterlists.com_resources/375_All-in-One Customized Adblock List.txt:bitly.com#@##banner-cookie
	filterlists.com_resources/169_AdGuard Annoyances Filter (AdGuard for Chromium).txt:bitly.com#@##banner-cookie
	filterlists.com_resources/169_AdGuard Annoyances Filter.txt:bitly.com#@##banner-cookie
	filterlists.com_resources/2212_AdGuard Annoyances Filter (uBlock Origin).txt:bitly.com#@##banner-cookie
	assets.json_resources/adguard-annoyance_AdGuard Annoyances.txt:bitly.com#@##banner-cookie
	[rdk@on filter-lists-tools-git]$

**Comment by mapx-** [comment]
well, so it's adguard ..
@Jose1971AB add in "my filters"

`bitly.com###banner-cookie, .fake`

or disable adguard and use only fanboy's annoyances

**Comment by Jose1971AB** [comment]
Hello @mapx- good afternoon.

> well, so it's adguard ..
> @Jose1971AB add in "my filters"
> 
> `bitly.com###banner-cookie, .fake`
> 
> or disable adguard and use only fanboy's annoyances

**Now it works!!!**... I added `bitly.com###banner-cookie, .fake` in My Filters and it works.

Thank you very much @mapx- and also thank @gwarser and @ryanbr for their collaboration.

Greetings and have a good weekend.
