### ISSUE TITLE
kaskus.co.id have blank spot

### ISSUE THREAD

**Issue by kurosaki98** [uBlockOrigin/uAssets#7717]
### URL(s) where the issue occurs

`https://www.kaskus.co.id/`

### Describe the issue

Some Ads "spot" still remaining on the site , the remaining as blank spots somewhat disturbing view XD

### Screenshot(s)

https://imgur.com/a/ywRmo18
https://imgur.com/a/D2w1f6h

### Versions

- Browser/version:  Firefox 79.0
- uBlock Origin version: v1.28.4

### Settings

- Default Filter
- AdGuard Base
- AdGuard Tracking Protection
- Fanboy’s Enhanced Tracking List
- Online Malicious URL Blocklist
- AdGuard Annoyances
- Fanboy’s Annoyance
- AdBlockID Plus

### Notes

Using manual pick i got this

! 8/1/2020 https://www.kaskus.co.id
```
www.kaskus.co.id###div-gpt-ad-r1
www.kaskus.co.id###div-gpt-ad-r2
www.kaskus.co.id###crt-1c6eb790
```

**Comment by mapx-** [comment]
report at `ABPindo` repository
https://github.com/ABPindo/indonesianadblockrules/issues

First test again the page using only the default settings
