### ISSUE TITLE
uBO on Chrome not blocking fox.com

### ISSUE THREAD

**Issue by dXterminator017** [uBlockOrigin/uAssets#772]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`fox.com/watch/818529c3d72584486365f78ae851fa67/`

### Describe the issue

Ads are no longer blocked while using uBO

### Screenshot(s)

![image](https://user-images.githubusercontent.com/1355374/31820060-4863366c-b554-11e7-9711-afd1da61ac62.png)

### Versions

- Browser/version: Chrome 62.0.3202.62
- uBlock Origin version: 1.14.12

### Settings

- added uBlock Protector List, EasyList, Adblock Warning Removal List and the following filters:

`@@||fox.com^$elemhide`
`@@||fxnetworks.com^$elemhide`
`@@||simpsonsworld.com^$elemhide`
`@@||adm.fwmrm.net/p/fox_live/*`
`@@||player.foxdcg.com^$xmlhttprequest,domain=fox.com|fxnetworks.com`

### Notes

Only blocked `uplynk.com` on uBO, not working.

**Comment by mapx-** [comment]
probably nothing to do
see `https://help.aolonnetwork.com/hc/en-us/articles/215852983-How-to-Setup-Server-Side-Ad-Insertion-with-UpLynk-Overview-`

https://www.reddit.com/r/uBlockOrigin/comments/5fn9c7/serverside_ad_insertion_and_ad_blockers/

**Comment by dXterminator017** [comment]
Reopening until solution found

**Comment by mncraig** [comment]
Please leave this issue open until a definitive solution has been found

**Comment by jspenguin2017** [comment]
Hold on, the player does know when it is playing an ad, it is going to be possible to skip the ads, although the difficulty can be quite high as deep patching player might be required.

**Comment by jspenguin2017** [comment]
I can see the ads request, it's an XHR but somehow I can't hook onto it with `a.loopbackXHR`. I can hard code a rule in extension background page but then it only works for one page.

**Comment by jspenguin2017** [comment]
OK, I did some in depth analysis, @mapx- is right that the ads are in the stream, but theoretically, we can still skip them, as we know when the ads play as well. 
However, it is horrifyingly hard to properly implement a system that is able to do that. 

On Firefox only, [Nano Defender](https://addons.mozilla.org/en-US/firefox/addon/real-nano-defender/) will force the player to show the progress bar even when playing ads, allowing you to drag it and bypass the ads. I tried everything on Chromium and I just can't touch that request. 

![image](https://user-images.githubusercontent.com/7283682/34324071-a8587f7e-e820-11e7-8bce-9ab838260f1c.png)

Under the hood: Nano Defender will intercept the video request and strip ads placement info, then, optionally, log them in the background page console for inspection. 

I really don't know how would you implement an ads auto-skipping logic. It's possible and impossible at the same time.

**Comment by jspenguin2017** [comment]
The code
```js
if (a.isFirefox) {
    {
        //https://github.com/jspenguin2017/uBlockProtector/issues/660
        a.dynamicServer(
            [
                "*://*.uplynk.com/preplay/*",
            ],
            [
                "xmlhttprequest",
            ],
            (details) => {
                let payload = "";

                let filter = browser.webRequest.filterResponseData(details.requestId);
                let decoder = new TextDecoder("utf-8");
                let encoder = new TextEncoder();

                filter.ondata = (e) => {
                    payload += decoder.decode(e.data, { stream: true });
                };
                filter.onstop = () => {
                    try {
                        payload = JSON.parse(payload);
                    } catch (e) {
                        filter.write(encoder.encode(payload));
                        filter.disconnect();
                        return;
                    }

                    //@pragma-if-debug
                    if (a.debugMode) {
                        console.log(payload.ads);
                    }
                    //@pragma-end-if

                    payload.ads = {
                        breakOffsets: [],
                        breaks: [],
                        placeholderOffsets: [],
                    };

                    filter.write(encoder.encode(JSON.stringify(payload)));
                    filter.disconnect();
                };
            },
            [
                "fox.com",
            ],
            true,
        );
    }
}
```

**Comment by ghajini** [comment]
abp dev version fix confirmed to be working...
`geolock-usa`
@mapx- 
make label `geolock-usa` for reference

**Comment by jspenguin2017** [comment]
Huh, how they fixed it? Link the commit?

**Comment by ghajini** [comment]
`https://github.com/uBlockOrigin/uBlock-issues/issues/46`

Used abp dev version
And filters
`||content.uplynk.com/api/v3/preplay/*
/(content.uplynk.com\/ext\/.*\.m3u8)\?.*$/$rewrite=$1`

**Comment by jspenguin2017** [comment]
Are you sure that works? I don't see requests for them: 
![image](https://user-images.githubusercontent.com/7283682/40390015-17da7f2a-5dd1-11e8-8168-811e0908a873.png)

**Comment by jspenguin2017** [comment]
Have you tried ND in debug mode? Also which exact rule does ABP use? The rules you shown clearly do not work.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/1905

For all websites using SSAI

**Comment by krystian3w** [comment]
@[mapx-](https://github.com/mapx-) mapx- added the[ SSAI ](https://github.com/uBlockOrigin/uAssets/labels/SSAI)label [on 7 Apr 2018](https://github.com/uBlockOrigin/uAssets/issues/1905#event-1562292997)
@[jspenguin2017](https://github.com/jspenguin2017) [jspenguin2017](https://github.com/jspenguin2017) mentioned this issue on 9 May 2018
[Ads] cwtv.com NanoAdblocker/NanoFilters#25
Closed
@jspenguin2017 jspenguin2017 mentioned this issue on 3 Jun 2018
nbc.com #2409
Closed
@[okiehsch](https://github.com/okiehsch) okiehsch changed the title Cwtv video ads Websites using SSAI (server side ad injection) [on 3 Jun 2018](https://github.com/uBlockOrigin/uAssets/issues/1905#event-1659832690)
This was referenced on 3 Jun 2018
Viceland Video Ads #1541
Closed
uBO on Chrome not blocking fox.com #772
Closed
abc7.com #794
Closed
@[jspenguin2017](https://github.com/jspenguin2017) jspenguin2017 mentioned this issue on 22 Jul 2018
[Anti-adblock] investigationdiscovery.com #2966
Closed
@[SkeletalDemise](https://github.com/SkeletalDemise) SkeletalDemise mentioned this issue on 22 Jul 2018
anti Adblocker on discovery.com sciencechannel.com #2931
Closed
@[terrorist96](https://github.com/terrorist96) terrorist96 mentioned this issue on 2 Sep 2018
Ads Loading gorhill/uBO-Extra#76
Closed
@[jspenguin2017](https://github.com/jspenguin2017) jspenguin2017 mentioned this issue on 15 Sep 2018
Ads while watching shows on FOX #3486
Closed
@[uBlock-user](https://github.com/uBlock-user) uBlock-user mentioned this issue on 27 Oct 2018
Midroll Ads Aren't being blocked CityTV.com #3847
Closed
@[mapx-](https://github.com/mapx-) mapx- mentioned this issue on 17 Nov 2018
rediff.com | Tracking #4138
Closed
@[terrorist96](https://github.com/terrorist96) terrorist96 mentioned this issue on 23 Nov 2018
Fails to Block Ads on The CW - http://thecwtv.com #4179
Closed
@[stoically](https://github.com/stoically) stoically mentioned this issue on 20 Mar 2019
ALL twitch.tv issues #5184
Open
@[okiehsch](https://github.com/okiehsch) okiehsch mentioned this issue on 11 Jun 2019
https://www.brighteon.com/ #5803
Closed
@[llacb47](https://github.com/llacb47) llacb47 mentioned this issue on 17 Jun 2019
discovery.com videos not working easylist/easylist#3636
Closed
@https://github.com/uBlockOrigin uBlockOrigin deleted a comment from [prateekrastogi](https://github.com/prateekrastogi) [on 26 Jan 2020](https://github.com/uBlockOrigin/uAssets/issues/1905#event-2979959103)
@[uBlock-user](https://github.com/uBlock-user) uBlock-user added the[ can't fix ](https://github.com/uBlockOrigin/uAssets/labels/can%27t%20fix)label [on 17 Jun 2020](https://github.com/uBlockOrigin/uAssets/issues/1905#event-3453347081)
@[nebchan](https://github.com/nebchan) nebchan mentioned this issue on 29 Sep 2020
Twitch TV now injecting ads #7968
Closed
@[llacb47](https://github.com/llacb47) llacb47 mentioned this issue on 1 Nov 2020
Add queryprune filters to deal with SSAI #8131
Merged
@[uBlock-user](https://github.com/uBlock-user) uBlock-user mentioned this issue on 16 Aug 2021
pluto.tv: Ads not being blocked #9764
Closed
6 tasks
@[subby2006](https://github.com/subby2006) subby2006 mentioned this issue on 1 Sep 2021
sbs.com.au ondemand has a new player and it detects ublock #7836
Closed
[uBlock-user](https://github.com/uBlock-user) added a commit that referenced this issue on 20 Jan
@uBlock-user
[update](https://github.com/uBlockOrigin/uAssets/commit/eb9148f1e001b8862c044b8884a27c09a607fe1a) https://github.com/uBlockOrigin/uAssets/issues/1905#issuecomment-394129540
[eb9148f](https://github.com/uBlockOrigin/uAssets/commit/eb9148f1e001b8862c044b8884a27c09a607fe1a)
This was referenced on 21 Jan
go.tlc.com: ads #11419
Closed
go.discovery.com: ads #11420
Closed
@[uBlock-user](https://github.com/uBlock-user) uBlock-user closed this as [completed](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/uBlockOrigin/uAssets/commit/ac8860312f726292bd3e7c2f34a82f6d20614dbe [on 9 Feb](https://github.com/uBlockOrigin/uAssets/issues/1905#event-6035560189)
@[uBlock-user](https://github.com/uBlock-user) uBlock-user reopened this [on 9 Feb](https://github.com/uBlockOrigin/uAssets/issues/1905#event-6035564682)
[uBlock-user](https://github.com/uBlock-user) added a commit that referenced this issue on 9 Feb
@uBlock-user
[append](https://github.com/uBlockOrigin/uAssets/commit/fe89b1b850dc070f09914e36b5520e955a5ad3a6) https://github.com/uBlockOrigin/uAssets/issues/1905#issuecomment-1033865488
[fe89b1b](https://github.com/uBlockOrigin/uAssets/commit/fe89b1b850dc070f09914e36b5520e955a5ad3a6)
@[uBlock-user](https://github.com/uBlock-user) uBlock-user mentioned this issue on 17 Feb
discovery plus italy showing ads #11772
Closed
6 tasks
@https://github.com/uBlockOrigin uBlockOrigin deleted a comment [on 9 Mar](https://github.com/uBlockOrigin/uAssets/issues/1905#event-6207603084)
@[mapx-](https://github.com/mapx-) mapx- mentioned this issue on 25 Mar
hulu.com: ads #12407
Closed
8 tasks
This was referenced on 27 Mar
philo.com: ads #12469
Closed
player.stv.tv: ads #12513
Closed
@[stephenhawk8054](https://github.com/stephenhawk8054) stephenhawk8054 mentioned this issue on 4 Apr
mech-plus.com: ads #12589
Closed
8 tasks
@[stephenhawk8054](https://github.com/stephenhawk8054) stephenhawk8054 mentioned this issue on 4 May
amc.com: ads #13065
Closed
8 tasks
This was referenced on 4 Jul
primevideo.com: ads #13906
Closed
animalplanet.com: ads #13969
Closed
tvbanywherena.com: video ads #13978
Closed
This was referenced 23 days ago
vix.com: ads #14213
Closed
discoveryplus.com: ads #10870
Closed
discoveryplus.com: ads #14365
Closed
@[mapx-](https://github.com/mapx-) mapx- mentioned this issue 6 days ago
go.tlc.com: ads #14451
Closed
8 tasks
@[MasterKia](https://github.com/MasterKia) MasterKia mentioned this issue 5 days ago
primevideo.com: ads #14512
