### ISSUE TITLE
Cannot view Disqus Section at Gizmodo Brazil

### ISSUE THREAD

**Issue by albertdick** [uBlockOrigin/uAssets#7720]
### URL(s) where the issue occurs

[https://gizmodo.uol.com.br/lancamentos-amazon-prime-video-agosto-2020/](https://gizmodo.uol.com.br/lancamentos-amazon-prime-video-agosto-2020/)
(or any article link)

### Describe the issue

Cannot view embedded disqus section comment when the "uBlock filters" item is enabled.

### Screenshot(s)

![uBlock filters disabled](https://i.imgur.com/dW0gjSa.jpg)

___

![uBlock filters enabled](https://i.imgur.com/kgU4eJV.jpg)

### Versions

- Browser/version: Mozilla Firefox 79.0 (64-bit)**
- uBlock Origin version: v1.28.4

** It hasn't been working on previous versions for some time.

### Settings

I can view the disqus section only disabling the first option "uBlock filters".
![uBlock settings](https://i.imgur.com/tc9TULS.jpg)

**Comment by llacb47** [comment]
@mapx- change `uol.com.br##+js(nostif, removeChild, 100)` to `uol.com.br##+js(nostif, f.parentNode.removeChild, 100)`
