### ISSUE TITLE
[disableadblock.com] html-cleaner.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#7722]
`html-cleaner.com`

Anti-adblock based on generic class/id from EasyList, version based on `/ads.js` can't work: #7721 

![obraz](https://user-images.githubusercontent.com/35370833/89110788-83ae5780-d44e-11ea-8259-a601cc75fb39.png) |
--- |
3-rd column

---

`https://disableadblock.com/developers/`

```html
<div id="fixvnnjjbouydc"><div class="adBanner">.</div></div> 
<script> 
document.addEventListener("DOMContentLoaded", function() {
    setTimeout(function() {
        document.getElementById("fixvnnjjbouydc").offsetHeight ? document.getElementById("fixvnnjjbouydc").style.display = "none" : document.getElementById("fixvnnjjbouydc").innerHTML = '<iframe></iframe>'
    }, 1e3)
});
</script>
```

maybe block frames:

`https://disableadblock.com/widget/thief/`
`https://disableadblock.com/widget/developer/`
`https://disableadblock.com/widget/how/`
`https://disableadblock.com/widget/small/`

`||disableadblock.com/widget/$frame,3p`

**Comment by llacb47** [comment]
Annoyance: `https://disableadblock.com/developers/`
