### ISSUE TITLE
UFZ.de impossible to scroll with blocked cookie banner overlay

### ISSUE THREAD

**Issue by ericschdt** [uBlockOrigin/uAssets#7724]
### URL(s) where the issue occurs

`https://www.ufz.de/index.php?de=37937`

### Describe the issue

When the cookie banner is blocked by the filter rule `###cookie-banner` it's impossible to scroll the website. 

### Versions

- Browser/version: FF79 and Chromium 84.0.4147.89
- uBlock Origin version: 1.28.4

### Settings

- Default
- EasyList 
- AdGuard Annoyances

### Notes

Filter: ###cookie-banner
Type: dom
Blocked by: 
* EasyList Cookie
* AdGuard Annoyances

**Comment by uBlock-user** [comment]
Add `ufz.de##body:style(overflow:auto !important)` to bring back scroll.

Breakage created by non-default filterlists is not addressed in uBO lists.

**Comment by ericschdt** [comment]
Thanks, I will keep it in mind!
