### ISSUE TITLE
voba-rll.de: Cookie consent overlay only partially blocked

### ISSUE THREAD

**Issue by ericschdt** [uBlockOrigin/uAssets#7725]
### URL(s) where the issue occurs

`https://www.voba-rll.de/startseite.html`

### Describe the issue

When the cookie consent overlay is blocked by the filter rule 
`##.cookie-consent:not(body):not(html)`
OR
`##.cookie-consent:not(body)`  + `##div[class^="cookie-consent_"]`
 there's still a an overlay and a empty box rendering the website unusable.

![Screenshot_20200803_140801](https://user-images.githubusercontent.com/43318127/89180822-14d21b00-d582-11ea-9652-cfcc7f9d5576.png)

### Versions

- Browser/version: FF79 and Chromium 84.0.4147.89
- uBlock Origin version: 1.28.4

### Settings

- Default
- AdGuard Annoyances

### Notes

Filter: ##.cookie-consent:not(body):not(html)
Type: dom
Blocked by: 
* AdGuard Annoyances 

OR

Filter: 
* ##.cookie-consent:not(body)
* ##div[class^="cookie-consent_"]
Type:dom
Blocked by:
* Fanboy’s Annoyance 
* EasyList Cookie

**Comment by uBlock-user** [comment]
Breakage created by non-default filterlists is not addressed in uBO lists.
