### ISSUE TITLE
Anti Adblock - mhdtvworld.live

### ISSUE THREAD

**Issue by emlimap** [uBlockOrigin/uAssets#7727]
### URL(s) where the issue occurs

`http://mhdtvworld.live/`

### Describe the issue

 

Anti adblock popup asking for adblock extension to be disabled. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/62358249/89225793-b6815880-d5d2-11ea-81ab-ebea0283986f.png)

### Versions

- Browser/version: Firefox 80.0b3
- uBlock Origin version: 1.28.5b13

### Settings

-

### Notes

Standard ublock filters plus ublock annoyance and Fanboy annoyance

**Comment by stephenhawk8054** [comment]
New anti-adblock.

URL: `https://mhdtvworld.xyz/live/sp-1-select/`

![image](https://user-images.githubusercontent.com/66517106/139564224-c898720f-b4a0-492e-bfa0-bf55d95c326c.png)

Firefox 93, ublock 1.38.6 default

Proposed filter:

`mhdtvworld.xyz##+js(nostif, showModal)`

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/386217e1f07d815c331646680ad30f99dd6fb67e
