### ISSUE TITLE
SFR.FR (customer section) - CSS & images not loaded

### ISSUE THREAD

**Issue by Skip75** [uBlockOrigin/uAssets#7730]
### URL(s) where the issue occurs

`https://www.sfr.fr/mon-espace-client/`

### Describe the issue

Only when uBlock Origin is enabled, it's missing CSS, images and many other content in webpage. Details in below Note.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/44243520/89286971-65fe0f80-d653-11ea-8251-a0dc84f30978.png)

### Versions

- Browser/version: FF 79.0 (64-bit)
- uBlock Origin version: v1.28.4

### Settings

Default settings and filters.

### Notes

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 |  |  | `www.sfr.fr` | 0,1 | script | `https://www.sfr.fr/ngsw-worker.js` |
| +1 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/favicon.png` |
| +1 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/resources/font/sfr-1.0-thin-webfont.woff` |
| +1 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/092018chevron-blanc.png` |
| +1 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/092018assistance.png` |
| +1 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/hec-pattern-box.png` |
| +1 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/hec-pattern-wifi.png` |
| +1 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/hec-pattern-tel.png` |
| +1 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/favicon.png` |
| +1 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/hec-picto-chevron-sfr.png` |
| +1 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/hec-pattern-sim.png` |
| +1 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/hec-picto-arrow-sfr-r.png` |
| +1 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/resources/font/sfr-1.0-bold-webfont.woff` |
| +1 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/resources/font/sfr-1.0-regular-webfont.woff` |
| +1 |  |  | `www.sfr.fr` | 3 | font | `https://static.s-sfr.fr/resources/font/sfr-1.0-thin-webfont.woff` |
| +1 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/092018chevron-blanc.png` |
| +1 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/092018assistance.png` |
| +1 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/hec-pattern-box.png` |
| +1 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/hec-pattern-wifi.png` |
| +1 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/hec-pattern-tel.png` |
| +1 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/hec-picto-chevron-sfr.png` |
| +1 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/hec-pattern-sim.png` |
| +1 | /etagp/* | -- | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/eTagP/IC/horloge.svg` |
| +1 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/hec-picto-arrow-sfr-r.png` |
| +1 | /stats/footer. | -- | `www.sfr.fr` | 3 | script | `https://static.s-sfr.fr/stats/footer.js` |
| +1 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/logo-3.jpg` |
| +1 |  |  | `www.sfr.fr` | 3 | font | `https://static.s-sfr.fr/resources/font/sfr-1.0-bold-webfont.woff` |
| +1 |  |  | `www.sfr.fr` | 3 | font | `https://static.s-sfr.fr/resources/font/sfr-1.0-regular-webfont.woff` |
| +1 | /etagp/* | -- | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/eTagP/IC/ecSFR.svg` |
| +1 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/logo-3.jpg` |
| +1 | /etagp/* | -- | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/eTagP/IC/ecSFR2.svg` |
| +1 | /stats/header. | -- | `www.sfr.fr` | 3 | script | `https://static.s-sfr.fr/stats/header.js` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/logo_h_2x.png` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/forum2018.png` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/youtube2018.png` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/twiter2018.png` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/facebook2018.png` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/sr-icone-demenagement-1.png` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/hec-picto-croix.png` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/group-2-copy-2.jpg` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/group-2-copy.jpg` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/resources/js/frameworks/jquery/sfr.jquery.js` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/group-2.jpg` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/group-2-copy-6.jpg` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/group-2-copy-4.jpg` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/group-2-copy-3.jpg` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/resources/js/SFR-PASS/swiper.min.js` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/hec-picto-telechargement-sfr.png` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/hec-picto-jeux-1-sfr.png` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/hec-picto-film-sfr.png` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/media/hec-picto-plus-sfr.png` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/resources/css/hecS.css` |
| +0 |  |  | `www.sfr.fr` | 0,3 | xhr | `https://static.s-sfr.fr/resources/css/SFR-PASS/sfr.css` |
| +0 | /stats/footer. | -- | `www.sfr.fr` | 3 | script | `https://static.s-sfr.fr/stats/footer.js` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/logo_h_2x.png` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/forum2018.png` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/youtube2018.png` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/twiter2018.png` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/facebook2018.png` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/sr-icone-demenagement-1.png` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/hec-picto-croix.png` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/group-2-copy-2.jpg` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/group-2-copy.jpg` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/group-2.jpg` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/group-2-copy-6.jpg` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/group-2-copy-4.jpg` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/group-2-copy-3.jpg` |
| +0 |  |  | `www.sfr.fr` | 3 | script | `https://static.s-sfr.fr/resources/js/SFR-PASS/swiper.min.js` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/hec-picto-telechargement-sfr.png` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/hec-picto-jeux-1-sfr.png` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/hec-picto-film-sfr.png` |
| +0 |  |  | `www.sfr.fr` | 3 | image | `https://static.s-sfr.fr/media/hec-picto-plus-sfr.png` |
| +0 | /stats/header. | -- | `www.sfr.fr` | 3 | script | `https://static.s-sfr.fr/stats/header.js` |
| +0 |  |  | `www.sfr.fr` | 3 | css | `https://static.s-sfr.fr/resources/css/hecS.css` |
| +0 |  |  | `www.sfr.fr` | 3 | css | `https://static.s-sfr.fr/resources/css/SFR-PASS/sfr.css` |
| +0 |  |  | `www.sfr.fr` | 3 | script | `https://static.s-sfr.fr/resources/js/frameworks/jquery/sfr.jquery.js` |
| +0 | ##+js(aopr, _oEa) |  | `www.sfr.fr` |  | dom | `https://www.sfr.fr/mon-espace-client/` |
| +0 |  |  | `www.sfr.fr` | 0,1 | xhr | `https://www.sfr.fr/mon-espace-client/` |
| +0 |  |  | `www.sfr.fr` | 1 | doc | `https://www.sfr.fr/mon-espace-client/` |
</details>

![image](https://user-images.githubusercontent.com/44243520/89287400-33a0e200-d654-11ea-8ea5-6a30fdef1460.png)

![image](https://user-images.githubusercontent.com/44243520/89287488-6054f980-d654-11ea-8c39-7225fc45048c.png)

![image](https://user-images.githubusercontent.com/44243520/89287525-7367c980-d654-11ea-9444-0ae6e20f633e.png)

**Comment by mapx-** [comment]
- needing an account
- however test this filter:
`@@||static.s-sfr.fr/stats/header.js$script,domain=sfr.fr`

- if does not work open the uBO logger, refresh the page, select in the logger only the blocked items and post them here (as screenshot eventually)

**Comment by Skip75** [comment]
Your filter solve the problem 👍 

![image](https://user-images.githubusercontent.com/44243520/89291078-2be43c00-d65a-11ea-84a6-bf32115ab6c0.png)

+ no more console error.

Maybe should be added in some FR list...

**Comment by mapx-** [comment]
fixed in unbreak list, but this should be fixed (for all adblockers) by EP (easyprivacy list)

@ryanbr
