### ISSUE TITLE
Adding entries against single-letter rules in uAssets Unbreak

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#7732]
### URL(s) where the issue occurs

`https://reports.adblockplus.org/7ce0a615-8bab-4fea-b7eb-1328b0336409?updated=1994#tab=all`

### Describe the issue

Allegedly, according to [an issue that was reported to ABP's filterlist issue tracker](https://reports.adblockplus.org/7ce0a615-8bab-4fea-b7eb-1328b0336409?updated=1994#tab=all), EasyList had an entry for roughly an hour on the morning of the 2nd of August, consisting simply of the letter `c`, causing vast breakage. Note that no list authors have been able to confirm that such an entry ever existed in EasyList, nor did this lead to any other EasyList users reporting such a breakage that I know of.

If we are to consider the report to be valid, I would look into whether it'd be feasible (or not) to add rules against single-letter entries in uAssets Unbreak. Something like:
```
a$badfilter
b$badfilter
c$badfilter
d$badfilter
e$badfilter
f$badfilter
g$badfilter
h$badfilter
i$badfilter
j$badfilter
k$badfilter
l$badfilter
m$badfilter
n$badfilter
o$badfilter
p$badfilter
q$badfilter
r$badfilter
s$badfilter
t$badfilter
u$badfilter
v$badfilter
w$badfilter
x$badfilter
y$badfilter
z$badfilter
```

### Screenshot(s)

![image](https://user-images.githubusercontent.com/22780683/89416576-c1043500-d72d-11ea-9323-98779e3046d8.png)

### Versions

- Browser/version: N/A
- uBlock Origin version: N/A

### Settings

N/A

### Notes

None that I know of and which I didn't describe above.

**Comment by uBlock-user** [comment]
Not needed anymore, dev build already has a preventive measure for this kind of filters. Install the dev-build and you can test it.
