### ISSUE TITLE
magnet-novels.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7734]
### URL(s) where the issue occurs

`https://www.magnet-novels.com/novels/50709/episodes/4522`
Apparently geo-locked tho no message was shown, if you can't access use Japanese VPN.

### Describe the issue

Annoyances: the picker or dev tools are prevented as in the SS below and right-click, copy, etc. are disabled.

### Screenshot(s)

![magnet-novels](https://user-images.githubusercontent.com/58900598/89421771-6a1f4f80-d76f-11ea-9475-b2aa5f5a2207.png)

### Versions

- Browser/version: Brave 1.11.104/Firefox 79.0
- uBlock Origin version: 1.28.4

### Settings

- Default + uBlock Annoyances (+ Fanboy Annoyances + AG JPN)

### Notes

The dev tools/picker could easily be recovered by `magnet-novels.com##+js(aeld, blur)` but I couldn't get copy etc. work except for directly removing attributes via dev tools. So far tried
```
magnet-novels.com##+js(aeld, /blur|contextmenu|copy|cut|dragstart|selectstart/)
magnet-novels.com##+js(aopw, document.onselectstart)
magnet-novels.com##+js(ra, oncontextmenu|onselectstart|ondragstart|oncopy|oncut, div.contentContainer)
```
without success.

**Comment by mapx-** [comment]
anti right click could be:
`||magnet-novels.com^$csp=script-src * 'unsafe-eval'`

**Comment by uBlock-user** [comment]
>  ||magnet-novels.com^$csp=script-src * 'unsafe-eval'

That will bring back the devtools spam, as scriptlets won't be able to execute in Firefox.

**Comment by mapx-** [comment]
yes, FF .. working for chrome

**Comment by uBlock-user** [comment]
`ra` won't work, but my MutationObserver version works(that also requires I remove every attribute individually instead of all in one go) along with one `aopw` filter.

```
magnet-novels.com##+js(rma, oncontextmenu, div.contentContainer)
magnet-novels.com##+js(rma, onselectstart, div.contentContainer)
magnet-novels.com##+js(rma, ondragstart, div.contentContainer)
magnet-novels.com##+js(rma, oncut, div.contentContainer)
magnet-novels.com##+js(rma, oncopy, div.contentContainer)
magnet-novels.com##+js(aopw, document.onselectstart)
```

**Comment by mapx-** [comment]
@gorhill

**Comment by PIZZA90** [comment]
`https://www.magnet-novels.com/novels/50709/episodes/4551`

this is a little broken (try select any color) I don't know what it is but well, maybe you missed that 😅

![Captura0](https://user-images.githubusercontent.com/33556647/94824184-03cc4b80-0405-11eb-9509-082431348cb1.PNG)

**Comment by PIZZA90** [comment]
are you sure? 😁

![Captura3](https://user-images.githubusercontent.com/33556647/94826082-3c6d2480-0407-11eb-9d06-7eae81a744cb.PNG)

**Comment by PIZZA90** [comment]
well im using chrome 😅 maybe in chrome works well with uBO off

**Comment by Yuki2718** [comment]
Ah, I just forgot to click "OK" button. But the function works fine with uBO default + Annoyances enabled too, so no problem. Or it's not on your end?

**Comment by hirorpt** [comment]
The mobile site is still select/copy-disabled.
`https://m.magnet-novels.com/novels/50709/episodes/4522`

**Comment by uBlock-user** [comment]
force update uBlock Annoyances list in a while.
