### ISSUE TITLE
volkskrant.nl / dpgmedia.net

### ISSUE THREAD

**Issue by practik** [uBlockOrigin/uAssets#7735]
### URL(s) where the issue occurs

Any page of the Dutch newspaper de Volkskrant. For example:
`https://www.volkskrant.nl/cultuur-media/the-last-black-man-in-san-francisco-is-een-poetisch-droomdebuut~bf14b06c/`

### Describe the issue

You are automatically taken to a cookie notice on an entirely different site. In the case of this example:
`https://myprivacy.dpgmedia.net/?siteKey=PUBX2BuuZfEPJ6vF&callbackUrl=https%3a%2f%2fwww.volkskrant.nl%2fprivacy-wall%2faccept%3fredirectUri%3d%252fcultuur-media%252fthe-last-black-man-in-san-francisco-is-een-poetisch-droomdebuut%257ebf14b06c%252f`

### Screenshot(s)

![Screenshot_2020-07-30 Privacy settings](https://user-images.githubusercontent.com/12074235/89459005-37e90000-d725-11ea-8ab8-c36a38c6f8cb.png)

### Versions

- Browser/version: Firefox 79.0
- uBlock Origin version: 1.28.4

### Settings

All default settings except: Advanced user features on, disable WebRTC leakage
All default filter lists plus: EasyList Cookie, EasyPrivacy and uBlock Annoyances. I also tried the EasyList Dutch filter list but it didn't help with this.

### Notes

I've also started an EasyList issue for this (https://github.com/ryanbr/fanboy-adblock/issues/1388) but no luck there so far.

**Comment by okiehsch** [comment]
I don't see how that can be fixed short of setting a cookie which uBO does not support.

**Comment by practik** [comment]
Got it, thanks for the quick response!
