### ISSUE TITLE
netclipart.com - CSS

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#7736]
### URL(s) where the issue occurs

Example **URL**:
`https://www.netclipart.com/isee/xRmxix_full-size-of-free-printable-halloween-templates-for/`

### Describe the issue

css blocked: `adstyle.css` 

**DOWNLOAD FREE** button not working.

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.28.4]

### Notes

i dont know if is **uBO** issue.. but frequently i get blank images, even whitelisting `adstyle.css`  

press **DOWNLOAD FREE**, and **Download PNG**, in the next page i get the blank images, see picture:

![Captura1](https://user-images.githubusercontent.com/33556647/89460034-ef076a80-d769-11ea-9b00-e32e8c406b8b.PNG)

when this happens, i get this error in console:

![Captura3](https://user-images.githubusercontent.com/33556647/89460260-486f9980-d76a-11ea-82a9-35edf2eda77a.PNG)

and never with uBO **OFF** but well, maybe nothing important.. 👽

**Comment by okiehsch** [comment]
I can't reproduce.
I don't see how the error in your console can be caused by blocking a stylesheet.
You can add
`@@||netclipart.com/*/adstyle.css$css,1p`
to your filter list if you want to allow it.

**Comment by llacb47** [comment]
Related: https://github.com/easylist/easylist/issues/5619
