### ISSUE TITLE
kisstvshow.to ads

### ISSUE THREAD

**Issue by Fix-ing** [uBlockOrigin/uAssets#7737]
`https://kisstvshow.to/`
This page seems always to get past uBlock so admin Devs please look at this page and make even better coding.
This page get past uBlock every time no matter the new versions!

Thanks for everything you doing and please keep up the good work.

**Comment by llacb47** [comment]
`*$3p,script,domain=kisstvshow.to,denyallow=facebook.com|disqus.com|disquscdn.com|sharethis.com`

?
