### ISSUE TITLE
Recite Me Accessibility tools blocked

### ISSUE THREAD

**Issue by isaacsgraphic** [uBlockOrigin/uAssets#7738]
### URL(s) where the issue occurs

`https://www.strathunion.com/`
`https://kentunion.co.uk/`

### Describe the issue

The red "Accessibility Tools" button in the top left of the Strath Union site brings up a menu with useful tools to help people with vision problems. Unfortunately, it's blocked by uBlock. The tool is created by a company called ReciteMe, and used on quite a few websites. It's not an advert, and it's a useful feature to some users.

It's exactly the same thing with Kent Union, but the button is on the top right.

### Versions

- Browser/version: Chrome, Firefox
- uBlock Origin version: 1.28.4
### Settings

Default settings.
-

**Comment by llacb47** [comment]
Blocked in easyprivacy, report here:
https://github.com/easylist/easylist
or here
https://forums.lanik.us/viewforum.php?f=64

**Comment by isaacsgraphic** [comment]
I'll raise the issue at easylist.
