### ISSUE TITLE
freefilesync.org

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#7742]
### URL(s) where the issue occurs

<https://freefilesync.org/download.php>

### Describe the issue

<https://freefilesync.org/download.php displays a an anti-adblocker warning on the website that isn't dismissible and appears each time you go to the website which says "It looks like an ad blocker has blocked all the ads.
The FreeFileSync project is 100% dependent on ad revenue and donations to stay alive. Instead of the ads, and after FreeFileSync has proven useful to you, please think about supporting with a donation. ". These types of anti-adblocker warnings have become much more common on websites now, and you need to block all of them by default with uBlock Origin, since that's what your users are using uBlock Origin for in the first place. Your users don't want ads or anti-adblocker warnings asking them to disable their adblockers to help support the advertising on websites, otherwise they wouldn't be using uBlock Origin. Stop trying to cater to website owners who are still just trying to display ads and track users, and just make an adblocker that completely disables all ads and anti-adblocker warnings by default, or if you really want to try and support website developers trying to make money from their users, then just give uBlock Origin users an opt-in option in the settings to choose to allow anti-adblocker warnings if they want to. That would make more sense, since the entire purpose of your add-on is to block ads, and so it should block anti-adblocker warnings, and all other annoying popups, advertising, and tracking if possible as well. Thank you for an otherwise great add-on, and have a nice day.> 

### Screenshot(s)

<![freefilesync org](https://user-images.githubusercontent.com/35790889/89691323-acaf6c00-d8d6-11ea-93b8-7471fbbb4ed1.jpg)>

### Versions

- Browser/version: [Firefox 79.0 (64-bit)]
- uBlock Origin version: [1.28.4]

### Settings

<{
  "timeStamp": 1596837231986,
  "version": "1.28.4",
  "userSettings": {
    "advancedUserEnabled": true,
    "alwaysDetachLogger": true,
    "autoUpdate": true,
    "cloudStorageEnabled": false,
    "collapseBlocked": true,
    "colorBlindFriendly": false,
    "contextMenuEnabled": true,
    "dynamicFilteringEnabled": false,
    "externalLists": "https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt\nhttps://mirror.cedia.org.ec/malwaredomains/justdomains\nhttps://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt",
    "firewallPaneMinimized": true,
    "hyperlinkAuditingDisabled": true,
    "ignoreGenericCosmeticFilters": false,
    "largeMediaSize": 50,
    "parseAllABPHideFilters": true,
    "popupPanelSections": 31,
    "prefetchingDisabled": true,
    "requestLogMaxEntries": 1000,
    "showIconBadge": false,
    "tooltipsDisabled": false,
    "webrtcIPAddressHidden": false
  },
  "selectedFilterLists": [
    "user-filters",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-abuse",
    "ublock-unbreak",
    "easylist",
    "easyprivacy",
    "urlhaus-1",
    "adguard-annoyance",
    "adguard-social",
    "fanboy-thirdparty_social",
    "fanboy-cookiemonster",
    "fanboy-annoyance",
    "fanboy-social",
    "plowe-0",
    "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt",
    "https://gitcdn.xyz/repo/NanoMeow/MDLMirror/master/hosts.txt",
    "https://mirror.cedia.org.ec/malwaredomains/justdomains"
  ],
  "hiddenSettings": {
    "allowGenericProceduralFilters": false,
    "assetFetchTimeout": 30,
    "autoCommentFilterTemplate": "{{date}} {{origin}}",
    "autoUpdateAssetFetchPeriod": 120,
    "autoUpdateDelayAfterLaunch": 180,
    "autoUpdatePeriod": 7,
    "benchmarkDatasetURL": "unset",
    "blockingProfiles": "11111/#F00 11011/#C0F 11001/#00F 00001",
    "cacheStorageAPI": "unset",
    "cacheStorageCompression": true,
    "cacheControlForFirefox1376932": "no-cache, no-store, must-revalidate",
    "cnameIgnoreList": "unset",
    "cnameIgnore1stParty": true,
    "cnameIgnoreExceptions": true,
    "cnameIgnoreRootDocument": true,
    "cnameMaxTTL": 120,
    "cnameReplayFullURL": false,
    "cnameUncloak": true,
    "cnameUncloakProxied": false,
    "consoleLogLevel": "unset",
    "debugScriptlets": false,
    "debugScriptletInjector": false,
    "disableWebAssembly": false,
    "extensionUpdateForceReload": false,
    "ignoreRedirectFilters": false,
    "ignoreScriptInjectFilters": false,
    "filterAuthorMode": false,
    "loggerPopupType": "popup",
    "manualUpdateAssetFetchPeriod": 500,
    "popupFontSize": "unset",
    "popupPanelDisabledSections": 0,
    "popupPanelLockedSections": 0,
    "popupPanelHeightMode": 0,
    "requestJournalProcessPeriod": 1000,
    "selfieAfter": 3,
    "strictBlockingBypassDuration": 120,
    "suspendTabsUntilReady": "unset",
    "uiPopupConfig": "undocumented",
    "uiFlavor": "unset",
    "uiStyles": "unset",
    "updateAssetBypassBrowserCache": false,
    "userResourcesLocation": "unset"
  },
  "whitelist": [
    "# edge-scheme",
    "about-scheme",
    "chrome-extension-scheme",
    "chrome-scheme",
    "ctv.ca",
    "moz-extension-scheme",
    "opera-scheme",
    "vivaldi-scheme",
    "wyciwyg-scheme"
  ],
  "netWhitelist": "# edge-scheme\nabout-scheme\nchrome-extension-scheme\nchrome-scheme\nctv.ca\nmoz-extension-scheme\nopera-scheme\nvivaldi-scheme\nwyciwyg-scheme",
  "dynamicFilteringString": "behind-the-scene * * noop\nbehind-the-scene * inline-script noop\nbehind-the-scene * 1p-script noop\nbehind-the-scene * 3p-script noop\nbehind-the-scene * 3p-frame noop\nbehind-the-scene * image noop\nbehind-the-scene * 3p noop",
  "urlFilteringString": "",
  "hostnameSwitchesString": "no-large-media: behind-the-scene false",
  "userFilters": ""
}>
-

**Comment by llacb47** [comment]
> Stop trying to cater to website owners who are still just trying to display ads and track users,

Could you be any politer?

**Comment by okiehsch** [comment]
Fixed in `uBO-annoyances`.

**Comment by mapx-** [comment]
> > Stop trying to cater to website owners who are still just trying to display ads and track users,
> 
> Could you be any politer? Making accusations like that?

I already explained this guy time ago uBO has no general solutions for all the sites ... but he does not understand.
