### ISSUE TITLE
Hidden advertisements https://thepiratebay0.org/

### ISSUE THREAD

**Issue by leodoi3** [uBlockOrigin/uAssets#7743]
### URL(s) where the issue occurs
https://thepiratebay0.org/

### Describe the issue
Clicking anywhere on the site opens a new tab/pop-up advertisement. 

### Versions

- Browser/version: Firefox 78.0.2
- uBlock Origin version: 1.28.4

### Settings

-none

### Notes

If you click anywhere a second time then the new tab does not open. You have to refresh the page to get it to show again.

**Comment by llacb47** [comment]
`thepiratebay0.org##+js(aopw, _pop)`

**Comment by okiehsch** [comment]
Do not post clickable links, especially to dodgy sites!
