### ISSUE TITLE
Pornhub adblock warning message

### ISSUE THREAD

**Issue by leodoi3** [uBlockOrigin/uAssets#7744]
### URL(s) where the issue occurs
`https://www.pornhub.com/`

### Describe the issue
Adblock warning message is displayed near the top.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/46114199/89701714-551cfa80-d8ee-11ea-8560-c4971c1fe352.png)

### Versions

- Browser/version: Firefox 79
- uBlock Origin version: 1.28.4

### Settings

-none

### Notes

Might have to refresh page a couple of times to get it to show.

**Comment by krystian3w** [comment]
`-none`

?
