### ISSUE TITLE
walla.co.il: video not working

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#7746]
I get striped grey boxes.
Default settings + **EasyList Hebrew**
What do you suggest?

**Comment by mapx-** [comment]
test
`@@||pro.ip-api.com/json$xhr,domain=news.walla.co.il`

**Comment by llacb47** [comment]
You didn't provide a video... Always provide a link please. You are familiar with the website not us.

Works for me: `||pro.ip-api.com/json$xhr,domain=walla.co.il,redirect=noopjs`

It happens on `https://vod.walla.co.il/movie/2965514` but only if I visit directly, clicking on it from `vod.walla.co.il` works.
Happens here too: `https://celebs.walla.co.il/item/3378540`

This script looks suspicious, you should block it if it has no side effects: `https://kvdhzjfrudaxrleb.walla.co.il/load.js`
Also this script: `middycdn-a.akamaihd.net/bootstrap/bootstrap.js`

**Comment by mapx-** [comment]
the redirection does not work on my end here (FF): `https://news.walla.co.il/item/3378912`

**Comment by mapx-** [comment]
I removed `news` from the filter to fix other paths

**Comment by llacb47** [comment]
Yeah, redirect works in chrome but not FF. `Reason: CORS request not http` . Ping gorhill about this?

**Comment by uBlock-user** [comment]
Firefox issue --  https://bugzilla.mozilla.org/show_bug.cgi?id=1434357, https://bugzilla.mozilla.org/show_bug.cgi?id=1434357

**Comment by mapx-** [comment]
maybe @ryanbr should fix the issue in EP

**Comment by IsraeliUser** [comment]
Thanks for all the comments!
I temporarily added `@@||pro.ip-api.com/json$xmlhttprequest,domain=sheee.co.il|walla.co.il`.  https://github.com/easylist/EasyListHebrew/commit/3b09f19ae495fd7f34d3c32e091be4714437c124
Should be fixed in EasyPrivacy. @ryanbr 
I will add the suspicious scripts later. First I will try verify it won't break things there.

**Comment by okiehsch** [comment]
>Yeah, redirect works in chrome but not FF. Reason: CORS request not http . Ping gorhill about this?

xhr, redirects usually don't work with Firefox that is a very old browser issue https://github.com/uBlockOrigin/uAssets/issues/242#issuecomment-269249399

**Comment by uBlock-user** [comment]
> xhr- redirects usually don't work with Firefox

They do work in cases where website declares - "no cors", when creating an xhr request via the aa script, therefore, there are filters where I have fixed anti-adblock with `nooptext` redirects via `redirect-rule`.

**Comment by IsraeliUser** [comment]
@ryanbr 
The filter you added doesn't match. It's `/json?` not `/json/`...
You can use `/json^` or just `/json` (which is currently in EasyList Hebrew), or use two different filters - one for `walla.co.il` and `sheee.co.il` and one for the rest.
