### ISSUE TITLE
healthline.com

### ISSUE THREAD

**Issue by BlitW0** [uBlockOrigin/uAssets#7750]
### URL(s) where the issue occurs

`https://www.healthline.com/health/itchy-beard`

### Describe the issue

 

Ads are appearing despite rules in uBlock filters.

### Screenshot(s)

![Screenshot_20200810-235602](https://user-images.githubusercontent.com/42700209/89817011-1e9ce500-db65-11ea-8326-5dc2dd9c7194.png)

### Versions

- Browser/version: Fenix Nightly 200810 06:01
- uBlock Origin version: 1.28.4

### Settings

- All annoyance filters enabled except Fanboy's Social and Easylist Cookie
- All ads filters enabled
- All tracking filters enabled
- All malware filters enabled

**Comment by mapx-** [comment]
Where are the ads ? screenshot ?

**Comment by BlitW0** [comment]
Added screenshot in original post.

**Comment by llacb47** [comment]
Test:

```
healthline.com##[data-ad]:upward(span+aside):upward(div)
healthline.com##a[href*="/confirm_linkout_redirect.aspx?"]:upward(section)
```

**Comment by uBlock-user** [comment]
```
healthline.com##div > .css-11k39sg
healthline.com##.css-1cg0byz
healthline.com##hl-adsense
```

?

**Comment by BlitW0** [comment]
```
healthline.com##a[href*="/confirm_linkout_redirect.aspx?"]:upward(section)
healthline.com##div > .css-11k39sg
```

`healthline.com##hl-adsense` is already in Adguard Base filter.

**Comment by BlitW0** [comment]
Still reproducible on desktop:
* Browser: Firefox 79
* uBlock Origin version: 1.29.0

![Screenshot (21)](https://user-images.githubusercontent.com/42700209/90277047-84011680-de82-11ea-9e3a-5c8acd2892a5.png)
