### ISSUE TITLE
gamersheroes.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#7751]
### URL(s) where the issue occurs

`http://www.gamersheroes.com/`

### Describe the issue

ad pictures on start page and ads on the right side

### Screenshot(s)

<img width="350" alt="Unbenannt1" src="https://user-images.githubusercontent.com/48647394/89818933-e38db800-db4a-11ea-8ced-5466b32b406f.PNG">

### Versions

- Browser/version: Firefox 79
- uBlock Origin version: v1.29.0

**Comment by mapx-** [comment]
it's yavli but is fixed on my end, try refreshing all your lists

**Comment by JobcenterTycoon** [comment]
Now i know why its my adblocker DNS but its possible to defuse the ad script with `gamersheroes.com##^script:has-text(rddywd.com)`
