### ISSUE TITLE
fotocasa.es - the uBO counter not working

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#7755]
### URL(s) where the issue occurs

`https://www.fotocasa.es/`

### Describe the issue

the uBO counter not working for me in this site. in the logs i can see blocked content.. but the counter in the uBO icon, no appears numbers. 

no problem, in any other website.

### Screenshot(s)

![Captura](https://user-images.githubusercontent.com/33556647/89948575-a72f8a00-dc26-11ea-807a-14ee41b88d64.PNG)

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.28.4]

### Settings

- Filter list: https://i.imgur.com/E6aesAu.png

**Comment by PIZZA90** [comment]
i just test with ABP and appears the numbers 🤔
maybe it's problem of my uBO? I'm going to reinstall it

**Comment by PIZZA90** [comment]
was a cookies issue, after clean it.. works well

**Comment by PIZZA90** [comment]
well the solution has been short-duration..  again no numbers.. after 8-9 pages views

**Comment by llacb47** [comment]
It's a service worker making the requests, so they don't show up.

**Comment by uBlock-user** [comment]
Extension pages never show counter. Put the focus back on the webpage tab and the counter will appear.
