### ISSUE TITLE
Instagram.com cannot open a post

### ISSUE THREAD

**Issue by leodoi3** [uBlockOrigin/uAssets#7758]
###  URL(s) where the issue occurs
go to any Intagram profile, example
https://www.instagram.com/instagram

### Describe the issue
When clicking on any post, nothing happens.

### Versions

- Browser/version: 79
- uBlock Origin version: 1.29.0

### Settings

-AdGuard Annoyances
-Anti-Facebook
-uBlock filters

### Notes

Happens when not logged in. With Ublock disabled, then it opens the login prompt.

**Comment by P0Rtvine** [comment]
Now only registration :(

### Screenshot(s)
<details>
<summary>Gif</summary>

![1](https://user-images.githubusercontent.com/57287308/124082048-f35d0600-da54-11eb-9192-0dcf09c8bb7e.gif)
</details>

### Versions

- Browser/version: Google Chrome
- uBlock Origin version: 1.36.0

### Settings
<details>
<summary>Screen</summary>

![2021-01-22_100714](https://user-images.githubusercontent.com/57287308/105464158-c3395c00-5c99-11eb-965b-81215d8f7bec.png)
</details>

**Comment by uBlock-user** [comment]
Server sided, no fix.

**Comment by dportvine** [comment]
Instagram rules from uBO Annoyances are not relevant?

**Comment by dportvine** [comment]
This used to be hidden in uBO Annoyances.
<details>
<summary>Screen</summary>

![2022-09-27_131153](https://user-images.githubusercontent.com/111344219/192499266-6fe5aaf3-ef4a-41a0-9cae-ad6777503153.png)
</details>

**Comment by ThatLadLegend** [comment]
Bump.
