### ISSUE TITLE
toptenz.net

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#776]
Ads are loaded below the site header on http://www.toptenz.net.

**Error URL:** http://www.toptenz.net/

_**Note:** Using uBO 1.14.12 on Chrome with the default filters and settings._

**Comment by mapx-** [comment]
working for me:
`toptenz.net##script:inject(abort-current-inline-script.js, parseInt)`

**Comment by gotitbro** [comment]
@mapx- Any idea on which ad network are they using to display these ads?

**Comment by okiehsch** [comment]
This site uses `uponit`.

**Comment by SMed79** [comment]
@gotitbro https://forums.lanik.us/viewtopic.php?f=62&t=37590
