### ISSUE TITLE
Fox Sports Go (foxsportsgo) anti adb

### ISSUE THREAD

**Issue by Wolfes0** [uBlockOrigin/uAssets#7760]
### URL(s) where the issue occurs

`https://www.foxsportsgo.com/`

### Describe the issue

 This website detects ublock origin and asks you to disable it. If you do not disable it, then the live videos will not load.  

### Screenshot(s)

![image](https://user-images.githubusercontent.com/69611520/90084103-7e6cca80-dce2-11ea-83d3-781915a27a91.png)

### Versions

- Browser/version: [Google chrome Version 84.0.4147.125 ]
- uBlock Origin version: [1.28.4]

### Settings

I added integrated nano defender.
-

### Notes

 After googling, I followed instructions to add integrated nano defender into ublock origin. It did not work.

**Comment by mapx-** [comment]
@Wolfes0 open the logger , refresh the page, select in the logger page only the blocked items, post them here (as 1 or more screenshots)

(be sure there are no other blocking extensions enabled)

**Comment by Wolfes0** [comment]
Hi @mapx- thanks for the help
I disabled nano defender and took screenshots as requested:

![image](https://user-images.githubusercontent.com/69611520/90130674-dafad480-dd38-11ea-8ef8-12d6b00fa025.png)

![image](https://user-images.githubusercontent.com/69611520/90130930-43e24c80-dd39-11ea-8d4e-f807cc9f3f1d.png)


Thanks

**Comment by mapx-** [comment]
try
```
@@||fsgstatic.com^$script,domain=foxsportsgo.com
@@||tags.tiqcdn.com/utag/*/utag.js$script,domain=foxsportsgo.com
@@||foxsportsgo.com^$ghide
```

**Comment by mapx-** [comment]
no feedback ?
