### ISSUE TITLE
google.* (sponsored section)

### ISSUE THREAD

**Issue by bug-rules** [uBlockOrigin/uAssets#7761]
### URL(s) where the issue occurs

`https://www.google.com/search?q=lace+wig&tbm=isch&hl=en`

### Describe the issue

multirow of version: https://github.com/uBlockOrigin/uAssets/blob/1becdb39620374698e131341fbb504a3630a2267/filters/filters.txt#L81

May need logon on specified Google account required, may need change region to specified  aliexperess sales:
`https://pastebin.com/raw/9nD2APM9`

### Screenshot(s)

![screen](https://user-images.githubusercontent.com/66819865/90104744-10a5ba80-dd45-11ea-8814-7c972dc405dc.jpg)

### Versions

- Browser/version: Firefox 79
- uBlock Origin version: 1.29.0

### Settings

stock

### Notes

`##div[data-ismultirow="true"][data-id^="CarouselPLA-"] `

```html
<div data-ismultirow="true" data-ow="370" data-oh="648" data-id="CarouselPLA-1" jsname="N9Xkfe" data-ri="60" class="isv-r PNCib o05QGe" jscontroller="K3moCf" jsmodel="OamUsd" jsdata="j0Opre;CarouselPLA-1;72" data-isl-cs="-1" style="width: 370px; height: 700px;">
    <!-- a lot of div-s... -->
</div>
```

**Comment by ghajini** [comment]
@mapx- there is this thread

`Old.reddit.com/r/uBlockOrigin/comments/i8k3qr/google_ad_firefox_android/`
Somewhat similar

**Comment by llacb47** [comment]
Maybe an A/B test or similar. If I spoof as an iPhone using devtools then I see some ads.

**Comment by krystian3w** [comment]
Maybe better report to @majkiit as long no global?

**Comment by krystian3w** [comment]
`https://www.google.com/search?q=myszka+ps/2`

 without logon on any account:

![obraz](https://user-images.githubusercontent.com/35370833/90314704-038bf580-df16-11ea-8abd-4760bd0abff1.png) |
--- |

**Comment by llacb47** [comment]
Screenshot
![image](https://user-images.githubusercontent.com/16567977/90314922-5f8a5600-dee5-11ea-912e-667e53d9caa4.png)

**Comment by krystian3w** [comment]
as long as there are no preprocessor filters in uBO list for that:
```
!#if env_mobile
google.*##div[data-id^="CarouselPLA-"]:not([data-crl])
!#endif
```

**Comment by krystian3w** [comment]
https://forums.lanik.us/viewtopic.php?p=155950#p155950

> by `shulk-skywalker`
> 4 Google images ad screenshot: `https://imgur.com/a/nM4Uag6` (`http://archive.is/wip/hDs14`)

**Comment by bogachenko** [comment]
@mapx- 

https://user-images.githubusercontent.com/8535285/93012919-c50a5900-f5ef-11ea-84a1-76be194e9568.png

**Comment by mapx-** [comment]
I get sponsored results only on shopping category (which is normal I'd say) not on images like in your case

**Comment by bogachenko** [comment]
> I get sponsored results only on shopping category

me too but any product that I would not enter will show **this block with ads**. I get ads everywhere, whether it's a refrigerator (of any company), a microwave oven (of any company), sony a6500, sony xperia Z, iphone x. in my case, this is definitely an advertisement (most stores are CIS stores)
It even says - `Реклама` aka advertising
