### ISSUE TITLE
hentaifreak.org [NSFW]

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7763]
### URL(s) where the issue occurs

`https://hentaifreak.org/`

### Describe the issue

1. Popup on clicking any video (some video are labeled as AD, the issue is about other normal videos)

2. Redirect when clicking browser's Back button after you moved to individual video. 

### Versions

- Browser/version: Firefox 79.0/Brave 1.11.104
- uBlock Origin version: 1.29.0/1.28.4

### Settings

- Default + AGJPN

### Notes

Maybe
```
||fhgh9sd.com^
hentaifreak.org##+js(nostif, popState)
hentaifreak.org##+js(aopw, onpopstate)
```
For the AD staff, maybe
`hentaifreak.org##.used > .destroy:has-text(AD):upward(3)`
or sth - on my end they happened to be `###post-9486` but likely to change.

**Comment by Yuki2718** [comment]
BTW apparently entire rules for `hentaihaven.org` (NSFW) are no more needed:
```
hentaihaven.org##+js(aopr, popunder_record)
hentaihaven.org##+js(popads-dummy.js)
hentaihaven.org##+js(set, canRunAds, noopFunc)
@@||hentaihaven.org/*-ad-home.js$script,1p
@@||hentaihaven.disqus.com/embed.js$script,domain=hentaihaven.org
@@||disqus.com/next/config.js$script,domain=hentaihaven.org
```
And on my end videos on the site are not playable as `stream.lewd.host ` is dead (not due to uBO).

**Comment by Yuki2718** [comment]
Thx!

**Comment by mapx-** [comment]
thx for your contribution too 👍
