### ISSUE TITLE
https://pimylifeup.com/raspberry-pi-remote-desktop/

### ISSUE THREAD

**Issue by jimmysofat6864** [uBlockOrigin/uAssets#7766]
### URL(s) where the issue occurs
`https://pimylifeup.com/raspberry-pi-remote-desktop`

### Describe the issue
Ads still show up even when updated
 

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [Latest]

### Settings

-None
![ads](https://user-images.githubusercontent.com/69532417/90202051-5f794180-dd91-11ea-8e25-394d64b94f59.png)

**Comment by llacb47** [comment]
@mapx- adthrive

**Comment by SamGurdus1** [comment]
I'm finding that the embedded video tutorials on this site are being blocked by this rule. Here's the page where I'm encountering this: `https://pimylifeup.com/raspberry-pi-plex-server/`

With uBlockOrigin on:
![Screen Shot 2020-11-22 at 4 40 40 AM](https://user-images.githubusercontent.com/45015476/99904252-9effd580-2c7e-11eb-963a-dbfafe84f1ff.png)


Without uBlockOrigin:
![Screen Shot 2020-11-22 at 4 41 00 AM](https://user-images.githubusercontent.com/45015476/99904260-b048e200-2c7e-11eb-8718-aca20f8e6c68.png)

I'm using Chrome and am on uBlock Origin v1.30.6

**Comment by mapx-** [comment]
test

```
@@||ads.adthrive.com/sites/*/ads.min.js$script,domain=pimylifeup.com
@@||ads.adthrive.com/core/$script,domain=pimylifeup.com
@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=pimylifeup.com
@@||securepubads.g.doubleclick.net/gpt/pubads_impl$script,domain=pimylifeup.com
```
