### ISSUE TITLE
Fix to block GDPR popup on all gamepedia.com sites

### ISSUE THREAD

**Issue by Borkason** [uBlockOrigin/uAssets#7769]
### URL(s) where the issue occurs
All wikis (subdomains) on `https://gamepedia.com`

For example: `https://minecraft.gamepedia.com/Minecraft_Wiki`

### Describe the issue

Remove GDPR popup.

### Screenshot(s)

![grafik](https://user-images.githubusercontent.com/2971735/90313694-ba847300-df0e-11ea-8bc3-8eb66567ff41.png)

### How to fix

Add the following filter-rule.

```
! 2020-08-15 https://gamepedia.com
gamepedia.com##div:has(div[data-tracking-opt-in-overlay])
gamepedia.com##body:style(overflow:auto!important)
```

**Comment by llacb47** [comment]
`GDPR messages will not be addressed in uAssets.`

https://github.com/uBlockOrigin/uAssets/blob/master/README.md

Consider reporting to Easylist cookie, Adguard, or IDCAC.

**Comment by krystian3w** [comment]
@llacb47 Easylist cookie still no support add CSS filters like:

> `gamepedia.com##body:style(overflow:auto!important)`

They will still accidentally cut out pop-up with one filter `#?#div:-abp-has(div[data-tracking-opt-in-overlay])` and there will be a worse effect than a pop-up for manual closing.

> or IDCAC

IDCAC also no create file with CSS, recommend use own addon to accept/remove pop-up.

>  Adguard

AdGuard use pur JS filter, They don't like to add CSS filters to solve the problem in uBO.
**In addition, it may have the same bug as  `wikia.com` the vicissitudes that embedded views are irreversible without proper acceptance / removal of GDPR.**

**Comment by krystian3w** [comment]
In summary, there are probably 5 choices:

- Change from Origin uBlock to AdGuard (with Enabled `AdGuard Annoyance`) or combination with the modes of these add-ons with an reversed/inverse trusted list.
    - which means that AdGuard only works on:
       `wikia.com`
       `wikia.org`
       `gamepedia.com`
       `fandom.com`
    - The reversed/inverse list mode will deactivate everything except `AdGuard Annoyance` in AdGuard Adblocker - https://adguard.com/cs/blog/new-extension-version-adguard-2-0-9.html.

- copy AdGuard solution into `.user.js` solution (ViolentMonkey "🙊", TamperMonkey "🙈" , GreaseMonkey "🙉")

- Install IDCAC addon and wait for `v3.2.0`+ release.

- manualy close pop-up, if you like see embeded videos/films on: `wikia.com`/`wikia.org`/`gamepedia.com`/`fandom.com`.

- If you don't track any video on any `gamepedia.com`, maybe report into the project @yourduskquibbles: https://github.com/yourduskquibbles/webannoyances
