### ISSUE TITLE
REMOVE BLANK LINES / WHITE SPACES in uBlock on Google Chrome

### ISSUE THREAD

**Issue by manjusr81** [uBlockOrigin/uAssets#777]
Browser : Google Chrome latest
filter lists : latest as per ublock
uBo version : latest as per install
Extensions used : ublock, tampermonkey, superautorefresh, onetab, https everywhere
NOTE : TRIED REMOVING ALL EXTENSIONS ONE BY ONE CLEARING CACHE AND REBOOTING SYSTEM BUT NO LUCK

Hi
Pls help in removing the blanks lines  /  white spaces as shown in the screenshot below. (i,e above Crude Oil WTI Futures - Nov 17 (CLX7) as shown below in screenshot i,e 5 lines of blanks spaces)

![screenshot - 10_21_2017 2_59_50 pm](https://user-images.githubusercontent.com/9315238/31857895-64b401a2-b707-11e7-8890-42eba4036ef5.png)

**Comment by SMed79** [comment]
Are you intentionally hidding the [navigation bar](http://i.imgur.com/jbhFypw.png) ? 
Do you have added this rule `investing.com###navBar` to your custom filters?

**Comment by manjusr81** [comment]
Yes I am hiding the navigation bar.  I dont need anything else except my chat commentary.  Thats the reason i want to eliminate blank spaces / white spaces.  Also if i eliminate i can view more two comments down easily.  Pls help

**Comment by manjusr81** [comment]
Added these     investing.com###navBar    .  But still i see those white space  / blank lines above

**Comment by SMed79** [comment]
> Yes I am hiding the navigation bar.

You had to say it in your first message !!

add
```
investing.com###navBar
investing.com##.wrapper:style(padding-top: 40px !important;)
```
Change the [padding-top](https://www.w3schools.com/css/css_padding.asp) **40px** as you want.

**Comment by manjusr81** [comment]
That was Excellent.  Amazing.  Its done now.  Thanks a lot.  Working as per.      Ok tell me another thing wheather I can save this page/url permanantly for future use.

Thanks

**Comment by SMed79** [comment]
You can save your custom filters in a text file and host them on `dropbox.com` for example.
... or rent a [safety deposit box](http://i.imgur.com/CKoLn2E.png) in the bank :)
