### ISSUE TITLE
oglobo.globo.com

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#7770]
### URL(s) where the issue occurs

`https://oglobo.globo.com/analitico/`

### Describe the issue

 

Content does not load behind the overlay. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/90319760-4048f400-def8-11ea-8a86-4da8bbd06d14.png)

Expected: 

![image](https://user-images.githubusercontent.com/7283682/90319767-4f2fa680-def8-11ea-9cd7-7827c4602183.png)

### Versions

- Browser/version: Chrome 86
- uBlock Origin version: 1.28.4

### Settings

- Default, tried Portuguese regional filters

**Comment by mapx-** [comment]
@ryanbr due to `/advertising/*$script,domain=~advertising.org.il|~kloterfarms.com|~temple.edu|~themarker.com`
