### ISSUE TITLE
linkvertise.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#7772]
### URL(s) where the issue occurs

`https://linkvertise.com/24388/SpotifyAccount?o=sharing`
### Describe the issue

Anti Adblock

### Screenshot(s)

<img width="763" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/90338582-f2f97f00-dfea-11ea-84f9-25124c82f8e0.PNG">

### Versions

- Browser/version:  Firefox 79
- uBlock Origin version:  v1.29.0

### Settings

default

**Comment by mapx-** [comment]
Did you update the lists ? It was fixed 17 hours ago
https://github.com/uBlockOrigin/uAssets/commit/73fbb511b28a1263c8964fa81d1936b97b22478f

**Comment by JobcenterTycoon** [comment]
ok now thanks
