### ISSUE TITLE
telefe.com

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#7777]
URL(s) where the issue occurs

`https://telefe.com/avenida-brasil/capitulos/capitulo-58/`

Describe the issue

the video doesn't start

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 84 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.28.4

Settings

Default

**Comment by okiehsch** [comment]
I get redirected to `https://www.youtube.com/telefe/` even if I disable `uBO`.

**Comment by llacb47** [comment]
I can see the website but the video is region locked
![image](https://user-images.githubusercontent.com/16567977/90354524-906aa800-e017-11ea-9092-e1b80af8de8a.png)

**Comment by okiehsch** [comment]
To clarify, I can see the website for a second or two and then I get redirected.

**Comment by okiehsch** [comment]
I can kind of reproduce wit an argentinian IP, but the connection is super slow and the video does not start even if I disable `uBO`.

**Comment by mapx-** [comment]
The page / video is working fine on my side (argentinian ip) FF / chrome

![image](https://user-images.githubusercontent.com/10303732/90360013-b6fe0280-e05a-11ea-8274-d1d6bb0d0078.png)

**Comment by uBlock-user** [comment]
That error is 403, not a breakage issue.

**Comment by llacb47** [comment]
@KiLL4FuNK is in argentina according to their profile, can you test again on default settings - if not done already?
