### ISSUE TITLE
anghami.com

### ISSUE THREAD

**Issue by efih** [uBlockOrigin/uAssets#778]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://play.anghami.com/personal-dj`

### Describe the issue

the site show popup all the time with the alert "disable your ad block"

### Versions

- Browser/version: Chrome 61.0.3163.79
- uBlock Origin version: 1.14.12

### Settings

- default settings

**Comment by SMed79** [comment]
@efih Is this message limite the site functionality?

**Comment by okiehsch** [comment]
I signed-up to test and I am unable to sign in without `@@||anghami.com^$generichide`

**Comment by SMed79** [comment]
Thank you for taking time to test.

**Comment by okiehsch** [comment]
No problem, I actually tested before I added the commit, because,  like you, I was not sure if this was more than an annoyance.
