### ISSUE TITLE
Breakage on subaru.com/guides

### ISSUE THREAD

**Issue by kevinoid** [uBlockOrigin/uAssets#7781]
### URL(s) where the issue occurs

`https://www.subaru.com/guides/forester/my20/mobile/style`
`https://www.subaru.com/guides/outback/my20/mobile/style`

### Describe the issue

The big blue "Learn More" buttons do not function correctly.  Some cause page navigation or page reload, some do nothing, with UBO disabled they would show a modal with the relevant information.

### Versions

- Browser/version: Firefox 81.0a1 (2020-08-17) (64-bit)
- uBlock Origin version: uBlock Origin v1.29.0

### Settings

- Default

### Notes

The issue can be avoided by disabling "Peter Lowe’s Ad and tracking server list" or by adding the following filter:

```
@@||www.subaru.com/guides/base/my20/mobile/_assets/js/tracking.js$script,domain=www.subaru.com
```

Without the above filter, the console contains many errors such as the following:

```
Uncaught TypeError: can't access property "trackModalEvent", window.tracker is undefined
Uncaught TypeError: can't access property "trackEvent", window.tracker is undefined
Uncaught TypeError: can't access property "trackPage", window.tracker is undefined
Uncaught TypeError: can't access property "trackScrollEvent", window.tracker is undefined
```

So it seems likely that adding the filter exception would allow rather invasive tracking.  I attempted to use script injection instead, but the same errors persisted:

```
! Does not work:
www.subaru.com##+js(set, tracker.trackEvent, noopFunc)
www.subaru.com##+js(set, tracker.trackModalEvent, noopFunc)
www.subaru.com##+js(set, tracker.trackPage, noopFunc)
www.subaru.com##+js(set, tracker.trackScrollEvent, noopFunc)
```

Perhaps I was using it incorrectly?

Thanks for considering,
Kevin

**Comment by okiehsch** [comment]
With chromium the pictures are also broken if I reload the site. The pictures work fine if I reload bypassing the cache.
````
@@||subaru.com/guides/*/js/tracking.js$script,1p
@@||subaru.com/guides/*/libs/adobe/AppMeasurement.js$script,1p
````
is needed for chromium users.

**Comment by okiehsch** [comment]
>Perhaps I was using it incorrectly?

No your filters are fine, I don't see a way to fix the site without allowing the first-party scripts.

**Comment by kevinoid** [comment]
Looks great, thanks @okiehsch!
