### ISSUE TITLE
rundschau-online.de anti-adblocker

### ISSUE THREAD

**Issue by bandi88** [uBlockOrigin/uAssets#7784]
### URL(s) where the issue occurs

`https://www.rundschau-online.de/ratgeber/reise/nur-60-prozent-auslastung-darf-das-hotel-meinen-urlaub-absagen--wenn-es-zu-voll-ist--36669380`

### Describe the issue

This website does not allow ad-blockers.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/23141180/90551510-bb790700-e191-11ea-8a39-61cbd99029e6.png)

### Versions

- Browser/version: Google Chrome 84.0.4147.105
- uBlock Origin version: 1.28.4

### Settings

Used with Nano Defender together.

**Comment by uBlock-user** [comment]
That's a login wall.

**Comment by mapx-** [comment]
to see the paywall => `@@||track.rundschau-online.de/cre-1.0/tracking/$script,1p`

**Comment by okiehsch** [comment]
Fixed.

**Comment by JobcenterTycoon** [comment]
Please update. Example:

`https://www.rundschau-online.de/news/politik/rundschau-interview-gebauer-will-vor-den-ferien-alle-kinder-in-die-schule-holen-38359932`

`track.rundschau-online.de/cam-1.0/api/auth_v3/public/servicesession/validate/xhr`
`track.rundschau-online.de/cam-1.0/static/jssdk.js`

need to be whitelisted

**Comment by JobcenterTycoon** [comment]
One more site with the same issue: `https://www.stuttgarter-zeitung.de/inhalt.region-stuttgart-an-vielen-badeseen-wird-am-wochenende-kontrolliert.120a5ce1-d211-49a9-97de-63391f33d4da.html?reduced=true`

`stuttgarter-zeitung.de/cre-1.0/tracking` need to be whitelisted
