### ISSUE TITLE
Linkedin login bypass

### ISSUE THREAD

**Issue by leodoi3** [uBlockOrigin/uAssets#7787]
### URL(s) where the issue occurs
Any linkedin profile
https://www.linkedin.com/in/williamhgates

### Describe the issue
Won't let me view profile when not logged in.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/46114199/90576618-94abd800-e173-11ea-92d7-aef0531a3ee6.png)

### Versions

- Browser/version: Firefox 79
- uBlock Origin version: 1.29.0

### Settings

-Adguard Annoyances
-Anti Facebook
-Ublock filters - annoyances

### Notes

The first few times you visit a profile without being logged in, it renders the profile information, but displays a full page blur asking to login (which you can remove by modifying the html).

After a few visits to profiles, LinkedIn no longer longer renders the profile information, and instead brings you to an "authwall" forcing you to login.

You can bypass this by switching to a different IP addresses, but only for a few more profile views. It looks like you used to be able to do this an unlimited amount of times by using Google Translate as a proxy, however this method is pretty old and I haven't been able to get it working.

**Comment by llacb47** [comment]
Server-side, uBo is not a proxy.
