### ISSUE TITLE
driverename.iblogbox.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#7792]
### URL(s) where the issue occurs

`http://driverename.iblogbox.com/` (it might be necessary to install https://gsuite.google.com/marketplace/app/multiple_file_rename_for_google_drive/783878738456 first)

### Describe the issue

Message after selecting the files to be renamed:

>Please disable the adblock for free use.

### Versions

- Browser/version: Chromium stable
- uBlock Origin version: uBlock Origin 1.29.0

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin lists

**Comment by uBlock-user** [comment]
Add `*$script,redirect-rule=noopjs,domain=iblogbox.com` and try again.

**Comment by adranger** [comment]
@uBlock-user it works.

**Comment by adranger** [comment]
@uBlock-user  same problem: `https://speedtesting.herokuapp.com/comicviewer/`
