### ISSUE TITLE
englishlands.net

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7793]
### URL(s) where the issue occurs

`https://englishlands.net/`

### Describe the issue

Annoyances: right click, text selection, and drag disabled

### Versions

- Browser/version: Brave 1.12.112/Firefox 79.0
- uBlock Origin version: 1.29.0

### Settings

- Default + uBlock Annoyances

### Notes

```
englishlands.net##+js(set, document.oncontextmenu, null)
englishlands.net##+js(set, document.onselectstart, null)
englishlands.net##+js(set, document.ondragstart, null)
```
works perfectly on Brave but not on Firefox, only right click recovered.

**Comment by mapx-** [comment]
for FF test:
`englishlands.net##^script:has-text(PT_CV_PUBLIC)`

**Comment by Yuki2718** [comment]
@mapx- Thanks, apparently it works by itself (without scriptlet rules).

**Comment by uBlock-user** [comment]
try `englishlands.net##+js(aopw, document.oncontextmenu)` and report any breakage.

**Comment by Yuki2718** [comment]
@uBlock-user Working without obvious breakage, thanks!
