### ISSUE TITLE
laptopmag.com

### ISSUE THREAD

**Issue by nu8** [uBlockOrigin/uAssets#7794]
> AD BLOCKER INTERFERENCE DETECTED

https://laptopmag.com

I tried this with no luck:

1. Dashboard
2. Filter lists
3. Annoyances
4. **AdGuard Annoyances** and **uBlock filters - Annoyances**

**Comment by llacb47** [comment]
Test:
```
laptopmag.com##+js(aopr, _sp_.mms.startMsg)
*-gb.js|$script,1p,domain=space.com|laptopmag.com|techradar.com|bikeperfect.com|tomshardware.com|whathifi.com|musicradar.com,redirect=noopjs
```

**Comment by nu8** [comment]
Looks like just the second line is enough to fix it

**Comment by uBlock-user** [comment]
Can't reproduce on default settings.

**Comment by nu8** [comment]
Its pretty simple to reproduce, just block 3rd-party scripts...

**Comment by uBlock-user** [comment]
If it's not reproduceable on default settings, it's not addressed in uBO filter lists.

**Comment by uBlock-user** [comment]
As for the filter, you can use `laptopmag.com##+js(aopw, _sp_)`.
