### ISSUE TITLE
gruenderlexikon.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#7795]
### URL(s) where the issue occurs

`https://www.gruenderlexikon.de/news/buchfuehrung/dieses-schreiben-ist-ohne-unterschrift-gueltig-stimmt-das-wirklich-84233542`

### Describe the issue

Ad pictures

### Screenshot(s)

<img width="524" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/90667829-66032f80-e24f-11ea-89fe-109df484816b.PNG">

### Versions

- Browser/version: Firefox 79
- uBlock Origin version: v1.29.0

### Notes

Please delete cache when no ad appear

**Comment by mapx-** [comment]
test for breakages

`gruenderlexikon.de##+js(acis, Number.isNaN)`

**Comment by JobcenterTycoon** [comment]
No breakage
