### ISSUE TITLE
flickr.com

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#7799]
### URL(s) where the issue occurs

`https://www.flickr.com/groups/lifehacker-desktop-showandtell/pool/with/28623117487/`

### Describe the issue

Click any photo to begin the photostream. Keep navigating to the next photo. After a few slides, `Upgrade to Flickr Pro to hide these ads` message comes up with a 5 seconds timer before further navigation is allowed.

### Versions

- Browser/version: Firefox 79.0
- uBlock Origin version: 1.29.0

### Settings

Default

**Comment by DandelionSprout** [comment]
On my end, `flickr.com##+js(set, appContext.adManager.context.current.adFriendly, false)` in uBlock Filters seems to fix it on Chromium-likes, but not on Firefox.

**Comment by llacb47** [comment]
Maybe a bug with set-constant, I have no idea why it would work in one browser and not the other. @gorhill

**Comment by uBlock-user** [comment]
![Capture](https://user-images.githubusercontent.com/21290713/90853242-27788c80-e397-11ea-9962-842b61c85f57.PNG)

Not a set-constant issue, flickr has its own CSP policy, so scriptlets will not work on Firefox.

**Comment by krystian3w** [comment]
https://github.com/JustOff/scriptlet-doctor any help?

**Comment by decembre** [comment]
I have the same problem but only with Waterfox classic 56.3 (no chance , it's my principal browser).

In Chrome or Firefox Quantum, with no special configuration or special filter list:
No nag so... No problem

I have duplicated the same settings than in Firefox Quantum in my Waterfox, but Waterfox continue to show this irritating "Upgrade to Flickr Pro to hide these ads" message.

I have tested too <a href="https://github.com/JustOff/scriptlet-doctor">Scriptlet Doctor</a> but it seems not make any difference.

An other idea ?

**Comment by krystian3w** [comment]
Try classic and manually run addon on flickr with froced inline-script.

![obraz](https://user-images.githubusercontent.com/35370833/97535203-8ff97080-19bb-11eb-915f-25f37ba1438c.png) |
--- |


https://github.com/JustOff/scriptlet-doctor/releases/download/1.2.3/scriptlet-doctor-classic-1.2.3.xpi

**Comment by decembre** [comment]
Hooo,  many thanks !
Seems to be the solution.
I have not understand that "Scriptlet Doctor" as an option, where we need to type domains of sites.
I just click on the icon to highlight it, thinking it was sufficient...
Maybe the author need to specify that in the description.
Anyway that' perfect.

**Comment by krystian3w** [comment]
Operating in any domain reduces the level of safety on all pages.

**Comment by decembre** [comment]
For Google things, yes...
But for Flickr, i think it is possible.

These CSP are difficult for me:
We are protected, yes, but we don't have easy tools to see when CSP is in action on a site and what it block.
And a way to easily to bypass it when "need" and a way to know when it is really problem.

**Comment by decembre** [comment]
It seems the problem return now or it's only for me ?

**Comment by krystian3w** [comment]
For me works `csp.enabled` = `false`.

In ScriptletDoctor maybe you lost `flickr.com` form input due bug in Firefox profile (e.g. breakage "localStorage").

**Comment by decembre** [comment]
Thanks, it work again:
I erase the form input in "Scriplet Doctor" and re add flickr.com in it and...
i work fine !
