### ISSUE TITLE
Gamestop video play reverted to ads player

### ISSUE THREAD

**Issue by tsunami2311** [uBlockOrigin/uAssets#780]
### URL(s) where the issue occurs

https://www.gamespot.com/videos/gs-news-update-wolfenstein-2-the-new-colossus-pc-r/2300-6441483/

Example link to videos all problem happen to all videos

### Describe the issue
I was told to post in assets section if the quality video play reverted back to the ads player, well it did all video have have looked at all using the ads player, the quality video player with quality options was work up until a few  days ago.

### Screenshot(s)

https://screenshots.firefox.com/eloLn1DalitWcBv6/www.gamespot.com

### Versions

- Browser/version: FF 56.0.1
- uBlock Origin version: 1.14.16

### Settings
Enable cloud storage support 
I am an advanced user (required reading)
Disable pre-fetching (to prevent any connection for blocked network requests) 
Disable hyperlink auditing 
Prevent WebRTC from leaking local IP addresses

### Notes
EasyPrivacy
Malvertising filter list by Disconnect
Malware Domain List
Malware domains
Malware filter list by Disconnect
Spam404
Fanboy’s Social Blocking List
MVPS HOSTS
Peter Lowe’s Ad and tracking server list

**Comment by okiehsch** [comment]
`gamespot.com##script:inject(abort-current-inline-script.js, $, sp.blocking)`
works on my end.

**Comment by tsunami2311** [comment]
and where does that  code go?

**Comment by tsunami2311** [comment]
sweet thanks for the filter update
