### ISSUE TITLE
simkl.com anti adb

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#7800]
### URL(s) where the issue occurs

`https://simkl.com/apps/chrome/enhancer/installed/`

### Describe the issue

When you go to `https://simkl.com/apps/chrome/enhancer/installed/` there's an error message that says that the website detected an adblocker and disabled the website features. Is there a way to fix that?

### Screenshot(s)

![simkl com](https://user-images.githubusercontent.com/35790889/90820499-7541b600-e2ff-11ea-8b38-5f2340376bd4.jpg)

### Versions

- Browser/version: Chrome Version 84.0.4147.135 (Official Build) (64-bit)
- uBlock Origin version: 1.28.4

### Settings

-

**Comment by JobcenterTycoon** [comment]
Seems to be all filter are obsolete, can it be confirmed?

**Comment by mapx-** [comment]
yeah, seems to be obsolete, removed
