### ISSUE TITLE
tvserial.it ask to disable adblocker

### ISSUE THREAD

**Issue by findow** [uBlockOrigin/uAssets#7803]
### URL(s) where the issue occurs

https://www.tvserial.it/amazon-prime-video-catalogo/

### Describe the issue

Site asks to disable adblocker

### Screenshot(s)

![Annotazione 2020-08-21 003228](https://user-images.githubusercontent.com/2287498/90832322-cf656a00-e345-11ea-8245-8bd2f812b5be.png)

### Versions

- Browser/version: Brave Beta 1.13.75
- uBlock Origin version: 1.29.0

### Settings

-

**Comment by DandelionSprout** [comment]
I can confirm the problem on Chrome as well. `###deadblocker_dialog` appears to me to remove the overlay.
