### ISSUE TITLE
Microsoft edge ads on Microsoft.com

### ISSUE THREAD

**Issue by neeez** [uBlockOrigin/uAssets#7804]
### URL(s) where the issue occurs

`https://www.microsoft.com/en-US/download/details.aspx?id=5555`

### Describe the issue

 

There is a "The new browser recommended by Microsoft is here" ad that appears on the top of this page. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/41217223/90856674-78b15d80-e350-11ea-96c9-d03821089935.png)

### Versions

- Browser/version: Firefox nightly
- uBlock Origin version: 1.29.0

### Settings

None
-

**Comment by neeez** [comment]
A little confused here - this is an ad, not an annoyance. Is it mis-categorized there? Makes sense go upstream but the reason I opened it is because per @gorhill's recommendations, I try not to enable too many lists, and it wasn't blocked in the base uBlock install.

**Comment by uBlock-user** [comment]
From now on, only annoyances that require extended syntax and anti-adblock will be addressed in uBO Annoyances list, so either add `microsoft.com###epb` to my Filters or subscribe to Fanboy/AdGuard's Annoyances list.

**Comment by neeez** [comment]
My point is that it is clearly not simply an annoyance, but an ad.

**Comment by uBlock-user** [comment]
Self-ad, it's advertising its own product on the same domain which is not blocked in main list but would rather into Annoyances list.
