### ISSUE TITLE
ost.jpoplibs.us [anti-adb]

### ISSUE THREAD

**Issue by What-Zit-Tooya** [uBlockOrigin/uAssets#7805]
### URL(s) where the issue occurs

`https://ost.jpoplibs.us/`
`https://ost.jpoplibs.us/single-jkt48-high-tension.html`

### Describe the issue

Anti-Adblock

### Screenshot(s)

![2020-08-21_201041](https://user-images.githubusercontent.com/9832875/90894187-68e65780-e3ea-11ea-940f-6de9a98554d5.png)

### Versions

- Browser/version: [FF 79.0 x64]
- uBlock Origin version: [1.29.0 + uBlock Protector]

### Settings

`https://pastebin.com/raw/NAq9hukj`

**Comment by stephenhawk8054** [comment]
There's a new anti-adblock now.

URL: `https://ost.jpoplibs.us/single-v-a-koko-kara-koko-kara.html`

![image](https://user-images.githubusercontent.com/66517106/144960474-c6121871-1b9f-4713-a206-cf93c1098fa6.png)

Settings:

<details>

```yaml
uBlock Origin: 1.39.2
Firefox: 94
filterset (summary): 
  network: 78562
  cosmetic: 39412
  scriptlet: 16207
  html: 601
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30417-30, 22m
    ublock-badware: 3543-1, 22m
    ublock-privacy: 188-0, 22m
    ublock-abuse: 72-0, 22m
    ublock-unbreak: 1716-0, 22m
    easylist: 61311-552, 22m
    easyprivacy: 26456-478, 22m
    urlhaus-1: 8593-0, 22m
    plowe-0: 3697-3, 22m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 275
  launchFromSelfie: true
popupPanel: 
  blocked: 5
```
</details>

Proposed filter:

`ost.jpoplibs.us##+js(nosiif, visibility, 1000)`
