### ISSUE TITLE
NSFW pasend.xyz

### ISSUE THREAD

**Issue by ian016** [uBlockOrigin/uAssets#7809]
### URL(s) where the issue occurs

`https://pasend.xyz/lila-irwan-sex-videos/`   

### Describe the issue

Every page, except the main page of the site, can detect adblocks. It takes about three-five seconds before it detects the adblock. Also, the Adblocker lowers the clarity of the entire page, adding blur, and it appears on the middle of the screen stating "Adblock Detected" where under it, "Please Disable AdBlocker to continue". Apart from that, the pages of the site also try to open about 3-4 pop-up windows to which mostly Firefox blocks some of it automatically. The site is also NSFW. 

### Versions

- Browser/version: PC Firefox Browser 79.0 (64-bit)
- uBlock Origin version: [v1.29.2]

**Comment by bug-rules** [comment]
I have only `aliexpress` or dating pop-ups.
