### ISSUE TITLE
Anti-adblock measures used on Slader.com 

### ISSUE THREAD

**Issue by iamLoi** [uBlockOrigin/uAssets#781]
Do we have a way of bypassing all the anti-adblock measures used on Slader.com? I have uBo on and there's some sort of banner that blocks half of the answers when I have uBo turned on. It goes away when I turn it off.

Can we get past this?

Here is what it looks like on my filter

! 10/23/2017, 5:55:12 PM http://slader.com/textbook/9781305480513-calculus-8th-edition/872/exercises/34/ slader.com##.question-and-answers-container.question-feed > .question-subject

(It's the big Calculus Q&A banner that covers half of the answer).

The exercise number changes for every exercise, so the element zapper doesn't work unless there's some sort of wildcard that deals with that. How can I make it work?

Using Chrome and UBo latest version. On uBo I have most 3rd party filters turned on.

**Comment by mapx-** [comment]
Did you read:
https://forums.lanik.us/viewtopic.php?p=126354#p126354

**Comment by okiehsch** [comment]
How about
````
||plus.addkt.com/slader_exdetail.js$script,redirect=noopjs,domain=slader.com
slader.com##.ad.inner
slader.com##.ads-to-hide
slader.com##section.solutions-list.loading:style(height: auto !important;)
````

**Comment by iamLoi** [comment]
@mapx- I added 

`@@||plus.addkt.com/slader_exdetail.js$script,domain=slader.com
slader.com##.ad.inner
slader.com##.ads-to-hide`

and @okiehsch 's and neither seemed to do anything. Added to My Filter.

**Comment by mapx-** [comment]
Did you add them as distinct filters ? From what you posted above it does not seem so

**Comment by iamLoi** [comment]
@mapx- Like this?

`@@||plus.addkt.com/slader_exdetail.js$script,domain=slader.com 
slader.com##.ad.inner 
slader.com##.ads-to-hide`

And they should be added to My Filter? If that's right than no, it doesn't seem to work.

**Comment by mapx-** [comment]
I tested again, all fine here ( @okiehsch  filters work too )
If you have other extensions enabled try disabling all and keep only uBo
Then try keeping only the normal setup lists and test again

**Comment by iamLoi** [comment]
@mapx- You're right. It's working. It was Privacy Badger that was breaking it. Turning PB off and using those filters did the trick. Sent PB a message that they're breaking the site.
