### ISSUE TITLE
Microsoft Edge ads on bing

### ISSUE THREAD

**Issue by neeez** [uBlockOrigin/uAssets#7812]
### URL(s) where the issue occurs

`https://www.bing.com/search?form=MOZSBR&pc=MOZI&q=siberian+tiger`

### Describe the issue

 

There is a " Download the new Microsoft Edge to get the best of the web. ​" ad that appears on the bottom of this page. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/41217223/91017288-0cd32d00-e5bc-11ea-8d7e-b10cea3d6103.png)

### Versions

- Browser/version: Firefox nightly
- uBlock Origin version: 1.29.0

### Settings

None
-

**Comment by uBlock-user** [comment]
Same as #7804 either add `bing.com###b_notificationContainer_bop`  to my Filters or subscribe to Fanboy/AdGuard Annoyances list.
