### ISSUE TITLE
psarips.xyz

### ISSUE THREAD

**Issue by Lukjan37** [uBlockOrigin/uAssets#7813]
nie mozna pobrac pliku torrenta.

**Comment by mapx-** [comment]
1. use english language
2. provide more details (browser, uBO, versions), direct link to the page with the torrent you cannot download, what link are you clicking 

Test using only the default setup of uBO

**Comment by Lukjan37** [comment]
vivaldi 3.2, ublock origin 1.29.2

I will not give you the address because they change every few minutes.

for example https://get-to.link/steel-rain-aka-gangcheolbi-2017-korean-720p-10bit-bluray-6ch-x265-hevc-psa41652/, after clicking on the link, the page opens instead of downloading file

**Comment by mapx-** [comment]
I fixed the popups on `get-to.link` page, so it seems there is no issue with `psarips` page but with the sites used to host their torrent links

**Comment by Lukjan37** [comment]
okay, now what will you correct too?

**Comment by mapx-** [comment]
going to the link you provided I get this page:

![image](https://user-images.githubusercontent.com/10303732/91041477-6c5b2800-e610-11ea-9395-da053e450b45.png)

I guess you have to use one of those links to download your torrent

**Comment by Lukjan37** [comment]
good.
