### ISSUE TITLE
Fix userscloud.com cookie popup

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7815]
### URL(s) where the issue occurs

`https://userscloud.com/007ztluxbpt5/[Soulreaperzone.com]_Gbriel_DropOut_Sp_-_01_BD_HD_DmonHiro.szn`

### Describe the issue

Although cookie consent is out-of-scope, it appears only on uBO for those who subscribe AdGuard Annoyances due to
`@@||userscloud.com^$generichide`
in uBlock filters which disables
`##.cc-window[aria-label="cookieconsent"]`.
Another reason is EasyList's exception
`@@||cdnjs.cloudflare.com^$script,domain=userscloud.com`
which overrides a blocking rule
`/cookieconsent.$domain=~alginor.no`.

### Screenshot(s)

![userscloud](https://user-images.githubusercontent.com/58900598/91041432-0344d600-e64b-11ea-8ae5-5d49cae018b0.png)

### Versions

- Browser/version: Brave 1.12.114
- uBlock Origin version: 1.29.2

### Settings

- Default + Fanboy's Annoyance + AG Annoyances + uBlock Annoyances

**Comment by mapx-** [comment]
I guess we can remove `@@||userscloud.com^$generichide` filter, I get no anti adb anymore
