### ISSUE TITLE
Ublock won't let me sign into Patreon

### ISSUE THREAD

**Issue by ltcars** [uBlockOrigin/uAssets#7816]
### URL(s) where the issue occurs

`https://www.patreon.com/home`

### Describe the issue

When I try to log in to Patreon with Google it immediately logs me out again. I tried enabling Cookies, but it doesn't work. Only when I disabled Ublock it worked. Note that when I successfully logged in and I enabled Ublock again everything worked and I can even close the tab and the go-to Patreon and be logged in automatically. This happened multiple times and with a different adblocker too. 

### Versions

- Browser/version: [New Edge/84.0.522.63]
- uBlock Origin version: [1.29.0]

### Settings

I didn't change any settings, my filterlists are the standard. 
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy 
uBlock filters – Resource abuse 
uBlock filters – Unbreak 
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Peter Lowe’s Ad and tracking server list
DEU: EasyList Germany
Malware Domain List
Malware domains

**Comment by llacb47** [comment]
Fill the template please. What filterlists are you using?

**Comment by ltcars** [comment]
Oh sorry, I didn't change anything from the standard filter lists

**Comment by mapx-** [comment]
- I cannot reproduce the issue FF / edge
- be sure you have only uBO as blocking extension (no other privacy badger, noscript etc )
- try with tracking prevention on basic

**Comment by krystian3w** [comment]
Maybe Google issue with cookies/localstorage/session?

**Comment by ltcars** [comment]
> * I cannot reproduce the issue FF / edge
> * be sure you have only uBO as blocking extension (no other privacy badger, noscript etc )
> * try with tracking prevention on basic
I didn't use any other adblocker, etc.
Where can I change the tracking prevention?
Thank you for your help!

**Comment by krystian3w** [comment]
In settings:
```
edge://settings/privacy
```

set "**basic**" or disable by "![Przechwytywanie](https://user-images.githubusercontent.com/35370833/91286387-b10ccd80-e78e-11ea-9283-4022b40cf15a.JPG)" in right corner.
