### ISSUE TITLE
Youtube chat not working

### ISSUE THREAD

**Issue by grzegorz-janoszka** [uBlockOrigin/uAssets#7817]
### URL(s) where the issue occurs

Any live YT stream, like https://www.youtube.com/watch?v=cOHhA_XIZZw

### Describe the issue

I can see the chat, but messages typed by me are not seen by anyone.

### Versions

- Browser/version: 79.0
- uBlock Origin version: 1.29.0 and earkier

### Settings

mostly default settings, turned off for some sites and that's it

### Notes

Chat works with Chrome and Firefox without UBO. Firefox with UBO somehow block my chat messages.

**Comment by krystian3w** [comment]
You excluded "shadow-ban": `https://www.youtube.com/watch?v=vDfpNXl67bM`?

**Comment by grzegorz-janoszka** [comment]
Ah, indeed. I have used another account for testing without UBO. So it seems despite I have never posted anything political or racist or anything, I got shadowbanned. So now I can call YT a fascist platform and it is fine :)
