### ISSUE TITLE
Some pictures not displayed on lepoint.fr

### ISSUE THREAD

**Issue by M3T4LL1C4** [uBlockOrigin/uAssets#782]
### URL(s) where the issue occurs

`http://www.lepoint.fr/societe/sommeil-les-dernieres-decouvertes-de-la-science-28-09-2017-2160542_23.php`

### Describe the issue

Some picture on many pages of lepoint.fr seems to be blocked by uBlock filters (Filters optimized for uBlock)

### Screenshot(s)

https://screenshots.firefox.com/xAoGJa14l09T8n2o/www.lepoint.fr

### Versions

- Browser/version: firefox 56.0
- uBlock Origin version: 1.14.16

### Notes

The only way I found to display the pictures is to unselect "uBlock filters", the first one, saying "Filters optimized for uBlock" in the comments. Unselecting the other ones does nothing.
I'm not an expert, but there's something I don't understand. In the logger, in the 3rd column, there's nothing blocked by this filter. By the way I tried to exclude everything blocked by the filters (so the logger has no red or yellow line, only green or white lines) but pictures are still blocked.

**Comment by mapx-** [comment]
The filter was added for anti adblocking stuff

```
! https://github.com/gorhill/uBlock/issues/2185
lepoint.fr##script:inject(noeval.js)
```
The injecting filters cannot be seen in the logger (for the moment)

If I whitelist the filter:
`lepoint.fr#@#script:inject(noeval.js)`

I get no warning message, so I guess is not used anymore !?
