### ISSUE TITLE
new title(update filters)

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#7820]
As per discussion https://github.com/uBlockOrigin/uAssets/commit/a844d765c0e3b279c4fa3121311bd527d58451d7
i opened this issue here

### URL(s) where the issue occurs

- [X] `https://hubfiles.ws/77da4d9941a38458` 

- [x] `https://9xupload.xyz/f/n3f4dw-vt301wlhbsflj`
- [x] `https://9xupload.xyz/93z5sy5wydeo`
- [ ] 
- [x] `https://clicknupload.co/k7x5yf7ov3re`
- [x] `https://www.indishare.org/rpm8ovnrief0`
- [x] `https://bdupload.asia/cbeepd91qmk2`
- [x] `https://uploadever.com/666s53g80j6n`
- [x] `https://uploader.link/f/u8w1et-51s87oakn53rq`
- [ ] 
- [x] `https://desiupload.co/f/jfwr15-ywdnykqn157wj`
- [x] `https://desiupload.co/grhqvaedlcjn`
- [ ] 
- [x] `https://zupload.me/4c91d6b3a377d474`
- [ ] 
- [x] `https://9xmovies.media/the-house-bunny-2008-dual-audio-hindi-720p-bluray-800mb/`
- [x] `https://9xmovies.nl`
- [x] `https://9xmovies.fyi`
- [ ] 
- [x] `https://userscloud.com/curjb5q21x5a`
- [x] `http://upindia.mobi/?page=mirror&id=521494&code=pDn5ZPf&req_key=2af46b5dca604caae72e8ac91b30b365&down_key=c6e1239722bbad2acca306dcb425b138`
- [x] `https://pandafiles.com/6v7bbohqzt26/Return_To_Savage_Beach___40_1998__41____Bolly4u.org___Unrated_Dual_Audio_Bluray_480p_300Mb.mkv`
- [x] `https://filerio.in/tepfry61gler`
- [x] `https://9kmovies.top/night-fare-2015-hindi-dual-audio-300mb-bluray-download/`
- [x] `https://uploadfiles.pw/0e756b44eedd4570`
- [x] `http://uppom.live/krvl0lzurlua`
- [x] `https://w4files.ws/13622d7a49bf5d81`
- [x] `https://9xmovie.rocks/wwe-monday-night-raw-24-august-2020-full-show-480p-hdtv-x264-500mb/`
- [ ] 
- [x] `https://7starhd.cash`
- [x] `https://7starhd.com.de/the-assassin-2015-dual-audio-hindi-org-500mb-bluray-720p-hevc-x265-esubs-download/`
- [x] `https://7starhd.show/oh-my-kadavule-2020-720p-900mb-uncut-dual-audio-hindimalayalam/`
- [ ]
- [x] `yomovies.link`
- [ ] 
- [x] `gofilms4u.ws`
- [x] `gofilms4u.pro`
- [ ] 
- [x] `dlfiles.online/80a0df440756d1bb`
### Describe the issue

With respect to above mentioned sites, there are already existing filters for these sites but most of the scriptlet filters are outdated so need update to latest filters.....this way there will be uptodate filters for these shady filters

**In order to reproduce popups some sites may require you to complete full download clicks upto final end**

### Versions

- Browser/version: opera browser stable , firefox for android 79.0.5 ,firefox desktop 79.0
- uBlock Origin version: [here]

### Settings

uBO's default settings
-

### Notes

there are more sites which require updated filters ,eventually i will report

**Comment by okiehsch** [comment]
Can this be closed or are there any outstanding example links?

**Comment by okiehsch** [comment]
Can this be closed or if not which example links still need to be looked at?

**Comment by ghajini** [comment]
@okiehsch will report eventually if any👍

**Comment by ghajini** [comment]
1. 
There are nsfw ads

`https://bdupload.asia/cbeepd91qmk2`

https://user-images.githubusercontent.com/20338483/91652955-981b5980-eab9-11ea-98bf-8bbe8b3a6d00.png

common filter some websites had `||flatlyforensics.com^`

2. 
`https://userscloud.com/curjb5q21x5a`

there is still postlnk crap(overlay covering download link) at last download page ,
can be fixed by userscloud.com##+js(acis, Math, XMLHttpRequest) or any preferred filter

3.
`http://uppom.live/krvl0lzurlua`
there is popads crap at last downoad page ,can be fixed by 

`uppom.*##+js(acis, String.fromCharCode, 'shift')`
`||cdn.dyveon.com^`(zwaar.org ad agency tracker)

4. 
`https://gofilms4u.pro` 
popads crap

**Comment by ghajini** [comment]
@okiehsch @mapx- 

`https://github.com/uBlockOrigin/uAssets/issues/7820#issuecomment-683383589`
Is not yet resolved? 

Am I missing something info that you want to know?

**Comment by okiehsch** [comment]
I can't reproduce popups at number 3, number 1 and 2 are fixed.
I can't reproduce number 4 but I see a webrtc connection.
Does `yandexcdn.com##+js(nowebrtc)` worls for you?

**Comment by ghajini** [comment]
For `http://uppom.live/krvl0lzurlua`
I see popups at intemediate pages as I told previously
`uppom.*##+js(acis, String.fromCharCode, 'shift')`
Will fix it for opera /firefox

**Comment by okiehsch** [comment]
> intemediate pages as I told previously

Actually you said "there is popads crap at last download page" and at the last page, namely
![image](https://user-images.githubusercontent.com/16838044/91824273-cc6a5380-ec3a-11ea-8b4d-c7fbd271c9ce.png)
there is nothing in the source that `uppom.*##+js(acis, String.fromCharCode, 'shift')` can fix.

**Comment by ghajini** [comment]
Page serves differently at each step

### screenshots 

https://user-images.githubusercontent.com/20338483/91825311-b5872980-ec59-11ea-8a79-192544f7e362.png

https://user-images.githubusercontent.com/20338483/91825343-c0da5500-ec59-11ea-9491-40c4461c479f.png

**Comment by okiehsch** [comment]
Thanks.
https://github.com/uBlockOrigin/uAssets/commit/2b25a2cd8b040080ccfdc14227bc0a137cc93efd

**Comment by ghajini** [comment]
`filerio.in/bkjgwtd6u4oi`
Popup ads
Can add
 `filerio.in##+js(nowoif)`

**Comment by ghajini** [comment]
`https://9xmovies.stream/`
popup ads 
firefox

**Comment by ghajini** [comment]
`https://www.indishare.org/ngwqfeev23op`

15 sec time can be boosted....

`indishare.*##+js(nano-setTimeout-booster)`

{As this filter is  in my filters, I observed from many months, I never encountered server side timer so no bad request error ,can be safely added)

**Comment by ghajini** [comment]
`https://fs.bdupload.pw/2jp4emkn3wpz`(`bdupload.asia`)

Popups
![IMG_20201114_005006](https://user-images.githubusercontent.com/20338483/99112281-6d9a6080-2613-11eb-9294-55687629fa37.jpg)

This work for me
`bdupload.*##+js(acis, String.fromCharCode, btoa)`
