### ISSUE TITLE
rarbghd.me

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#7821]
### URL(s) where the issue occurs

`rarbghd.me`

### Describe the issue

Popup ads

### Versions

- Browser/version: firefox quantum 80.0
- uBlock Origin version: 1.29

### Settings

 uBO's default settings
-

**Comment by mapx-** [comment]
I get popups + anti adb on `savelinks.info`

**Comment by ghajini** [comment]
This works
`rarbghd.me##+js(nowebrtc)`
