### ISSUE TITLE
sport1 anti adblock

### ISSUE THREAD

**Issue by nuttenpreller** [uBlockOrigin/uAssets#7823]
`https://www.sport1.de/internationaler-fussball/la-liga/2020/08/fc-barcelona-coach-ronald-koeman-soll-den-verein-zurueck-zum-erfolg-fuehren?utm_medium=Social&utm_source=Twitter#Echobox=1597987406`

![screenshot](https://user-images.githubusercontent.com/67310926/91209311-d0aee200-e70b-11ea-80e8-5f5ea410bbeb.png)

**Comment by JobcenterTycoon** [comment]
i only get this when the site `asadcdn.com` is blocked by a second tracking blocker. I can block the anti adblock overlay without whitelisting with the filter `sport1.de##^script:has-text(adBlockerHandling)`

**Comment by okiehsch** [comment]
I can't reproduce.
