### ISSUE TITLE
hpjav.tv not working well (doesnt allow video player because of tsyndicate)

### ISSUE THREAD

**Issue by yalbv11** [uBlockOrigin/uAssets#7824]
blocking tsyndicate.com, which allow ads, produce a that video player doesn't work

### Screenshot(s) https://ibb.co/ZfxkG12 first screenshot when you enter hpjav.tv
images of the issue when you allo tsyndicate so you can watch a video https://ibb.co/Y7QB1nt and https://ibb.co/b6Q4X1f (it shows  a large white space of ads in between the content of the page)
screenshot if you block the tsyndicate https://ibb.co/Rjm4z3Y the ads and white space dissapears 
but it casues you can play the video (clicking the play button doesn't work as if the video reques is being blocked) as the following screenshot https://ibb.co/vjKkgFN

### Versions

- Opera browser 70.0.3728.119
- uBlock Origin version: 1.29.2

### Settings
 I select the advancer user setting
add the nano defender and nano ad blocker user filter list
so as the anti adblook killer
-

**Comment by mapx-** [comment]
I added a filter to remove the ads above, don't block `tsyndicate`  and remove that outdated list: `anti adblook killer`

**Comment by yalbv11** [comment]
I copied your filter and paste on "My fiters",  and yet it shows the large white space of ads
https://ibb.co/rvsmJY7

**Comment by mapx-** [comment]
still working fine on my end. Test using the default setup.

**Comment by yalbv11** [comment]
is this how you copy the filter?
![Opera Instantánea_2020-08-25_170001_kccohkcpppjjkkjppopfnflnebibpida](https://user-images.githubusercontent.com/70229617/91236205-8f5f0800-e6f4-11ea-875e-bf24024f21c7.png)

**Comment by llacb47** [comment]
the first line is totally wrong. delete everything before the f in `fileone.tv`

**Comment by yalbv11** [comment]
Confirm, it worked
Thank you for your help
