### ISSUE TITLE
comparic.pl

### ISSUE THREAD

**Issue by mat41997** [uBlockOrigin/uAssets#783]
![2017-10-25 16_05_37-forex - gielda gpw analizy forex komentarze gieldowe - comparic pl](https://user-images.githubusercontent.com/5884000/32003117-8199e432-b99e-11e7-8fb0-1338a8f72524.png)

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.35
chrome 62.0.3202.62
win10 x64

**Comment by gwarser** [comment]
`@@/eu-cookie-$domain=comparic.pl`

**Comment by okiehsch** [comment]
Fixed by gwarser's filter and no issue with uBO-default settings.
