### ISSUE TITLE
mail.yandex.ru ublock doesnt work

### ISSUE THREAD

**Issue by papaper21** [uBlockOrigin/uAssets#7830]
### URL(s) where the issue occurs
`https://mail.yandex.ru`

### Describe the issue
uBlock dont block ADS there. One big block on left, under inbox links and one inner mail list (on top).

 

### Screenshot(s)
http://ipic.su/img/img7/fs/mailyandexru.1598449232.png

### Versions

- Browser/version: Mozilla Firefox / 79
- uBlock Origin version: 1.29.2

### Settings

- switched on all RU pressets on the tab in configs
- tried pipette (enter to select mode), it hides until refresh page, so this uselles

### Notes

When ublock switched ON, classes changes names randomly (look at screenshot upper)

**Comment by uBlock-user** [comment]
Is RUADlist activated ?

**Comment by uBlock-user** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
This issue is resolved using the [recommended settings](http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=3#1).

**Comment by papaper21** [comment]
> 
> 
> Is RUADlist activated ?

Yes, activated.

**Comment by papaper21** [comment]
> 
> 
> This issue is resolved using the [recommended settings](http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=3#1).

Thanks , ill try, but add more plugins in browser not a good idea to solve one problem.

**Comment by papaper21** [comment]
> 
> 
> @dimisa-RUAdList

is RUAd list filter author?

**Comment by dimisa-RUAdList** [comment]
In Google Chrome, additional plugins are not required, but Firefox has a bug due to which some rules on Yandex sites are dropped.

Yes, I am the author of RU AdList.

**Comment by papaper21** [comment]
> 
> 
> In Google Chrome, additional plugins are not required, but Firefox has a bug due to which some rules on Yandex sites are dropped.
> 
> Yes, I am the author of RU AdList.

Почему только на яндексе?
Можно как-то в ublock этот фикс запихнуть?
Я прописал свой селектор , удалось скрыть блок рекламы в списке писем, то есть самый верхний блок, боковой не знаю как. Точнее не знаю как удалить DIV со всем содержимым между двумя другими,статичными названиями, то есть как правильно описать фильтр вручную в ublock.

**Comment by dimisa-RUAdList** [comment]
Everything is much more complicated and the rules of hiding this problem cannot be solved. If you want to discuss it in Russian, welcome [here](http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&glp#lt).

**Comment by papaper21** [comment]
> 
> 
> Everything is much more complicated and this problem cannot be solved by the rules of hiding. If you want to discuss it in Russian, welcome [here](http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&glp#lt).

Ok,
...

why only yandex services?
can add this fix into ublock?
I used mine custom selector, now up block near mails hides normal when I changed accounts, refreshes. But i dont know how to hide left side block  under Inbox/out/spam and etc (look at screenshot). More precisely, I don't know how to delete DIV (with all sub-blocks) between static blocks. I mean, how correctly manually write filter in ublock syntax.

**Comment by dimisa-RUAdList** [comment]
Because the Yandex webmasters use very tight CSP settings. At the same time, Firefox has a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027), due to which extensions cannot embed scripts. So far, fixing this browser bug is only possible with the Scriptlet Doctor.

**Comment by warren-ru** [comment]
It's not only the Firefox problem. Google Chrome extension doesn't block this ad either.

**Comment by dimisa-RUAdList** [comment]
@warren-ru
Try to add [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters)

**Comment by warren-ru** [comment]
@dimisa-RUAdList 
this list didn't help

**Comment by dimisa-RUAdList** [comment]
@warren-ru
Please make a screen of the logger.

**Comment by warren-ru** [comment]
@dimisa-RUAdList 
what kind of logger do you mean?

**Comment by bogachenko** [comment]
https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by warren-ru** [comment]
@dimisa-RUAdList 
Log file is attached
[log.txt](https://github.com/uBlockOrigin/uAssets/files/5540378/log.txt)

**Comment by dimisa-RUAdList** [comment]
@warren-ru
How to make a screen is described [here](http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=8#1).

**Comment by warren-ru** [comment]
@dimisa-RUAdList 
I've already attached txt file

**Comment by dimisa-RUAdList** [comment]
@warren-ru
Need a screenshot

**Comment by warren-ru** [comment]
@dimisa-RUAdList 
PickPick doesn't make screenshot of Logger window with scrolling.
Why do you need screenshot?
There's no additional information there.

**Comment by dimisa-RUAdList** [comment]
Then make a [backup](http://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=10#1)

**Comment by warren-ru** [comment]
@dimisa-RUAdList 
made screenshot with FastStone Capture
![log](https://user-images.githubusercontent.com/69246897/99143630-a0833980-2691-11eb-96ac-383ec9c6e3fc.png)

**Comment by dimisa-RUAdList** [comment]
@warren-ru
I don't see you add [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters)

**Comment by warren-ru** [comment]
@dimisa-RUAdList 
It looks like "RU AdList для uBlock Origin" so I thought It was the same list.
Now inbox ad is blocked.
Thanks for your time!

**Comment by muhasturk** [comment]
Adguard Extra user script works as expected, ublock can be develop something like this.

> - Install Tampermonkey
> - Click on this link to install AdGuard Extra: 
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js


[Source](https://github.com/AdguardTeam/AdGuardExtra#userscript)

**Comment by dimisa-RUAdList** [comment]
@muhasturk 
No additional extensions needed. Just plug in the filter [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters).

**Comment by TheSimArchitect** [comment]
Not working here either. I am getting ads if I use Yandex Web Mail.

**Comment by mapx-** [comment]
> Not working here either. I am getting ads if I use Yandex Web Mail.

Did you subscribe [RU AdList: Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters) ?

**Comment by TheSimArchitect** [comment]
Yes, I just found that and another couple of lists that weren't in the default uBlock's list (I didn't know we could subscribe to lists that aren't listed there, I only used what comes with uBlock or custom filters until today).

Thanks!!!
