### ISSUE TITLE
psprices replace games pictures with placeholder

### ISSUE THREAD

**Issue by Gandora64** [uBlockOrigin/uAssets#7831]
### URL(s) where the issue occurs
`
https://psprices.com/region-us/index
`
### Describe the issue

Instead of having every game picture show up, all of them load a placeholder image

### Screenshot(s)

![FireShot Capture 045 - PlayStation Games Deals in Official Store and Retailers • PSprices US_ - psprices com](https://user-images.githubusercontent.com/54451213/91336933-577ec000-e7db-11ea-95ac-16c877589965.png)

### Versions

- Browser/version: Google Chrome Version 85.0.4183.83 (Official Build) (64-bit)
- uBlock Origin version: 1.29.2

### Settings

uBO's default settings

### Notes

i've tried checking the filters and whitelisting some of them but it didn't make a difference, i've also removed the cookies and cache and flushed the DNS but none of them fixed the issue

**Comment by krystian3w** [comment]
Try with other IPS or use VPN?
