### ISSUE TITLE
Admitad dynamic domain tracker injection

### ISSUE THREAD

**Issue by holykol** [uBlockOrigin/uAssets#7833]
### URL(s) where the issue occurs

* `https://frogogo.ru/`
* Probably many other domains

### Describe the issue

Admitad script tag embedded in the page loads tracker script without getting blocked.

### Versions

- Browser/version: FF 68.11.0esr
- uBlock Origin version: v1.29.2

### Notes

Here is the script tag I discovered on mentioned site: https://gist.github.com/holykol/597d38ada367c30eaf0f1e6aaa07ad22
When failing to connect to the main tracker host, the mentioned code tries to generate domains based on the current date. Here is the snippet from the gist:
```js
for (var e = new Date, n = Math.floor(new Date(2020, e.getMonth(), e.getDate()).setUTCHours(0, 0, 0, 0) / 1e3), t = parseInt(1e12 * (Math.sin(n) + 1)).toString(30), i = ["de"], o = [], a = 0; a < i.length; ++a) o.push({
        domain: t + "." + i[a],
        name: t
    });
```
After successful connection attempt the script loads tracker script without getting block by uBO.

**Comment by llacb47** [comment]
`https://listauthorschat.slack.com/archives/C010N14G4TF/p1596912648392900`

**Comment by llacb47** [comment]
I don't think you read the message @okiehsch 

![image](https://user-images.githubusercontent.com/16567977/91369117-e50ce080-e7d8-11ea-8d11-15512b826b62.png)
