### ISSUE TITLE
blocked uk.cdn-net.com js file breaks showroomprive.com cart

### ISSUE THREAD

**Issue by Waether** [uBlockOrigin/uAssets#7834]
### URL(s) where the issue occurs

`https://www.showroomprive.com/monpanier/panier.aspx`

### Describe the issue

Ublock Origin block files coming from uk.cdn-net.com
Unable to validate your cart and pay while Ublock Origin is on.

### Versions

- Browser/version: Chrome 84.0.4147.135
- uBlock Origin version: 1.29.2

### Settings

Default

### Notes

Ublock Origin blocks a js file coming from uk.cdn-net.com
Here's the file https://uk.cdn-net.com/cc.js?ts=1598521891325
This file not being loaded remove the ability to validate your purchase and go further.
Disabling EasyPrivacy filter 'fixes' the issue.

Here are the lines that look related to this.
line: 5985  ||cdn-net.com^$third-party
line: 17192    @@||cdn-net.com/cc.js$script,domain=uber.com|ubereats.com

Don't really know how it could be fixed, and on which side. Any ideas ?
Thanks.

**Comment by okiehsch** [comment]
Does adding
`@@||cdn-net.com/cc.js$script,domain=showroomprive.com`
to your filter list fix the issue?

**Comment by Waether** [comment]
No, unfortunately it still gets blocked. Is there any way to know exactly which rule stops a js file from loading ?

**Comment by okiehsch** [comment]
Sure, open the [logger](https://github.com/gorhill/uBlock/wiki/The-logger) and reload the site,
https://github.com/gorhill/uBlock/wiki/The-logger#finding-from-which-lists-a-static-filter-originates

**Comment by Waether** [comment]
After using the logger I got this line and it works.
`@@||uk.cdn-net.com/cc.js$script,domain=showroomprive.com`
Not sure why your line didn't work since it's roughly the same.
Thanks for your help.

**Comment by llacb47** [comment]
> After using the logger I got this line and it works.
> ...
> Not sure why your line didn't work since it's roughly the same.

That is strange, @okiehsch 's filter is broader than your filter and should've worked.

**Comment by Waether** [comment]
Just tried it on another computer, works fine. I probably went too fast during my testing and did something wrong at some point.
