### ISSUE TITLE
Element zapper and picker doesn't work on a certain website

### ISSUE THREAD

**Issue by idozahavy** [uBlockOrigin/uAssets#7837]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

The ads are showing and there is no way to select them with the element picker or zapper.
looks like they have a script that disables both the zapper and picker, I assume that because while loading the page if I click on element picker, the gray mask appears but it disappears after a second.

### A specific URL where the issue occurs

The website is in Hebrew.
`https://www.walla.co.il/`

### Steps to Reproduce

1. Go to the site
2. Click on element zapper or picker

### Expected behavior:

Element zapper or picker works

### Actual behavior:

Nothing happens

### Your environment

* uBlock Origin version: v1.29.2
* Browser Name and version: Firefox 80.0
* Operating System and version: Window 10 build 18362 (version 1903)

**Comment by llacb47** [comment]
Also happens on this page (same company) as well as ad circumvention: `https://www.zahav.ru/`

**Comment by uBlock-user** [comment]
That's a random sub-domain, shouldn't we go with `##+js(set, Reflect.ownKeys, noopFunc)` ?

**Comment by gorhill** [comment]
I tested with EasyList Hebrew, so whatever solution should involve the list maintainer(s).

**Comment by gorhill** [comment]
> That's a random sub-domain

Maybe a case for `script,denyallow=` or `csp=script-src` if ever the base domain `walla.co.il` is necessary.

**Comment by uBlock-user** [comment]
@IsraeliUser

**Comment by llacb47** [comment]
This site is still messing with the element picker... @mapx- can we fix it in uAssets?
