### ISSUE TITLE
channel1vids.com

### ISSUE THREAD

**Issue by mat41997** [uBlockOrigin/uAssets#784]
i not can close this site before
![2017-10-25 21_07_41-channel1vids com](https://user-images.githubusercontent.com/5884000/32017998-b7def06c-b9c8-11e7-9757-3c0125e39ba0.png)

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.35
chrome 62.0.3202.62
win10 x64

**Comment by mapx-** [comment]
it's malware, see how to remove it:
https://malwaretips.com/blogs/remove-channel1vids-com/

**Comment by okiehsch** [comment]
No filter issue.
