### ISSUE TITLE
Annoyance filter submission: Facebook's new excessive notifications

### ISSUE THREAD

**Issue by cjrobe** [uBlockOrigin/uAssets#7843]
The new Facebook has a really annoying new top bar with redundant and out of control notifications with no way to disable them. While it is already on the left side of the screen with tasteful blue notification text, there is now Video, Group, and Page notifications that will constantly fill up and have red numbers on the top of the your screen just like your standard notification center. Since you can already know if you have Page or new Group posts from your left side notification center, you can filter out just the red numbers and keep the buttons for navigation purposes.

`facebook.com##[aria-label*="Pages"] span span
facebook.com##[aria-label*="Groups"] span span
facebook.com##[aria-label*="Watch"] span span`

Before and after:
![O8VeSK8](https://user-images.githubusercontent.com/5606066/91624757-0fdd6d00-e970-11ea-9b0b-61a68ed1d2e4.jpg)

Not sure if this is the right place to submit such filter for inclusion in the list, but dropping it here in case.

**Comment by uBlock-user** [comment]
Annoyances that are anti-adblock notices(dismissable ones) and the ones that requires uBO's extended syntax are addressed in uBO Annoyances list. So please report this at Fanboy's/AdGuard's Annoyances tracker instead.

**Comment by krystian3w** [comment]
AdGuard no support scriplets and long time ago added support CSS, so imo all can by reported into AdGuard Annoyance and copy only rejected solutions into uBO Annoyance.
