### ISSUE TITLE
dreamstime.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#7844]
`https://www.dreamstime.com/beet-beetroot-food-emoji-emoticon-collection-healthy-concept-cartoon-characters-kids-coloring-book-colouring-pages-t-shirt-image127211808`

Login pop-up with locked scroll after ~5 seconds when this is first visit on site.

`dreamstime.com##+js(nostif, SignUPPopup_load, 5000)`

---

Solution with CSS may break behavior on click "register" 🟢  button on navbar header. The `nostif` imo is safer.
Also no see changes in DOM tree to use [`:watch-attr(foo)`](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectwatch-attrarg).

**Comment by krystian3w** [comment]
@okiehsch  / @yourduskquibbles  today I found pop-up on homepage about free trial to download 15 photos (with locked scroll):

[Screenshot_2020-09-01 Stock Photos Royalty Free Photos By Dreamstime](https://user-images.githubusercontent.com/35370833/91855769-e4a39800-ec65-11ea-8f3d-ea1599a33591.png)

Possible use `set` / `aopr` or a few CSS:

```js
dreamstime.com##+js(set, openfreetrial, 1)
```

```css
dreamstime.com###freetrial_popup
dreamstime.com##html.documentLocked body:style(overflow: visible !important;)
dreamstime.com##html.documentLocked:style(margin-right: 0 !important;)
dreamstime.com##html.documentLocked header:style(padding-right: 0 !important;)
dreamstime.com##.popup:style(overflow: auto !important;)
```

This pop-up this version no have elegant `SetTimeout` if `set`/`aopr` is break something.

CSS also change design pop-ups, webmaster no longer block scroll by use `.documentLocked`.

**Comment by yourduskquibbles** [comment]
Updated, also FYI `dreamstime.com##.popup:style(overflow: auto !important;)` is not needed from my testing so did not include this.

**Comment by krystian3w** [comment]
OK, maybe Stylus break pop-up content due Firefox idea of CSS:

```
 scrollbar-color:
 scrollbar-width:
```

Because see empty scroll without "darker/lighter" rectangle.

**Comment by yourduskquibbles** [comment]
> Because see empty scrollbar (without "darker/lighter" rectangle).

Try test with just uBO? - The class `##.popup.show` is being set to `display: none` by the filter `dreamstime.com###freetrial_popup` so CSS overflow override setting is redundant for the homepage `free trial` popup because the class is hidden with cosmetic filter.

**Comment by krystian3w** [comment]
Same, I mean normal register pop-up opened from header:

https://user-images.githubusercontent.com/35370833/91902562-35d17d00-eca2-11ea-88d1-5f2458f115a0.png

But this empty scrollbar, as you can see, suits the company and webmasters of the site.
