### ISSUE TITLE
Thingiverse.com Downloads Broken

### ISSUE THREAD

**Issue by digitalentropy** [uBlockOrigin/uAssets#7845]
### URL(s) where the issue occurs

Any Thingiverse URL, for example, `https://www.thingiverse.com/thing:3103425`

### Describe the issue

Any attempt to download files results in a "Please help out Thingiverse and disable your ad blocker!" block message from Thingiverse.

### Screenshot(s)

N/A
![image](https://user-images.githubusercontent.com/1412286/91647759-2f79a180-ea13-11ea-8112-ca49bfb17f3e.png)

### Versions

- Browser/version: Firefox 80.0
- uBlock Origin version: 1.29.2

### Settings

Default

### Notes

Disabling uBlock seems to resolve the issue.

**Comment by okiehsch** [comment]
> Any attempt to download files results in a "Please help out Thingiverse and disable your ad blocker!" block message from Thingiverse.

The download starts after 5 seconds. That is only an annoyance and already fixed in `uBlock filters – Annoyances`.
Enable that list or add
````
thingiverse.com##+js(set, blockedElement.className, null)
thingiverse.com##+js(nano-sib)
thingiverse.com##[class^="AdBlockDetect"]
````
to your filter list.

**Comment by digitalentropy** [comment]
okiehsch, thanks for checking this out.

Your reported behavior is very interesting because the file download does not start automatically regardless of how many times I refresh, or how long I wait. Your proposed filters on the other hand, do appear to work.

Which uBlock Annoyance filter should I try selecting? I have been unable to get any of them to work besides the custom rules proposed.

**Comment by uBlock-user** [comment]
No need to, anymore. The filters have been moved to the main list. So force update that and you're done.

**Comment by okiehsch** [comment]
@digitalentropy I moved the filters to the main list after all, sorry that I forgot to reply here as well.

The reason I moved them can be read here. https://github.com/NanoMeow/QuickReports/issues/4598

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/65519

Anybody can test:

```
thingiverse.com#@#+js(set, blockedElement.className, null)
thingiverse.com##+js(set, blockedElement.className, undefined)

**Comment by uBlock-user** [comment]
![Capture](https://user-images.githubusercontent.com/21290713/95862472-98796680-0d80-11eb-8a9a-08c0e10f2807.PNG)
