### ISSUE TITLE
pitchfork.com - GIFs on 404 error pages

### ISSUE THREAD

**Issue by 07416** [uBlockOrigin/uAssets#7847]
### URL(s) where the issue occurs

```
https://pitchfork.com/staff/chris-ott/
https://pitchfork.com/article/record_review/21809-mellon-collie-and-the-infinite-sadness/

```

### Describe the issue

Pitchfork uses varying, troll-like "reaction" GIFs on the 404 error pages. As Pitchfork has deleted hundreds or thousands of their reviews and potentially other articles/pages, people may frequently encounter the dead pages when arriving from Wikipedia for example.

I suggest blocking the images from loading on the error pages.

### Screenshot(s) (non-animated)

![image](https://user-images.githubusercontent.com/14923168/91657704-b25e3300-eacb-11ea-90c0-f14b284bbde4.png)

**Comment by krystian3w** [comment]
I don't think so, probably other sites also have funny gifts for 4XX and 5XX error pages (unless the server crashed so hard that the simplified Apache / ngxin html error is loaded).

**Comment by uBlock-user** [comment]
This belongs to Annoyances category.

**Comment by krystian3w** [comment]
I suspect that AdGuard Team and Fanboy Team are reluctant to block it, maybe @yourduskquibbles  in `ultralist.txt` they are willing and will reject it?

**Comment by uBlock-user** [comment]
Adding `||pitchfork-cdn.s3.amazonaws.com/assets/misc/error-img/$image,3p` takes care of the GIFs.

**Comment by 07416** [comment]
> This belongs to Annoyances category.

My intention was posting there - sorry for the mistake.

**Comment by 07416** [comment]
> I suspect that AdGuard Team and Fanboy Team are reluctant to block it, maybe @yourduskquibbles in `ultralist.txt` they are willing block when rejected it in `uBO -- Annoyance`?

Was this suggestion already rejected?

**Comment by krystian3w** [comment]
Now no, maybe `mapx-` close this with the ['declined'](https://github.com/uBlockOrigin/uAssets/issues?q=label%3Adeclined) label.

**Comment by 07416** [comment]
@yourduskquibbles to webannoyances?

**Comment by krystian3w** [comment]
No no added: https://github.com/yourduskquibbles/webannoyances/commits/master

**Comment by yourduskquibbles** [comment]
I don't think this is really a proper fit or major annoyance that belongs in any centralized list outside of a users own custom filters personally.

**Comment by krystian3w** [comment]
Safe mobile transfer without break any file up 50 KiB globally.
