### ISSUE TITLE
Seemingly obsolete rules

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#7850]
kisscartoon.*##+js(aopw, Fingerprint2) // Fixed

//file-upload.net##+js(aopw, Fingerprint2)

//userscloud.com##+js(aopw, Fingerprint2)

//shink.me##+js(aopw, Fingerprint2)
! Already in EL
@@||ajax.googleapis.com/ajax/libs/jquery/*$script,domain=shink.me // Fixed

//streamplay.*##+js(aopw, Fingerprint2)
//steamplay.*,streamp1ay.*##+js(aopw, Fingerprint2)

! adshort.im/rPOCc
! redirected to adsrt, can't find a link other than their front page
!adshort.*##+js(acis, Math, zfgloaded)
!adshort.*##+js(aopr, app_vars.force_disable_adblock)
!adshort.*##+js(aopw, Fingerprint2)
!adshort.*##+js(nowoif)
!adshort.*##A[href$=".html"][rel="nofollow norefferer noopener"]
!adshort.*##+js(popads-dummy.js)
!adshort.*##[id*="frme"]
!@@||adshort.org^$script,1p
!@@||adshort.*^$ghide
!adshort.org##[id^="p_root_"]:style(max-height: 100px !important;)
!||adshort.org^$csp=connect-src 'self' *.google.com

! adbull.org/3pg4 // Fixed
adbull.org##^script:has-text(shift) // Fixed

//pingit.*##+js(aopr, AaDetector)
//pingit.*##+js(aopw, Fingerprint2)

//tii.ai##+js(aopw, Fingerprint2)
//tii.ai##+js(aopr, LieDetector)

//srt.am##+js(aopw, Fingerprint2)

//oke.io##+js(aopw, Fingerprint2)

//dz4link.com##+js(aopw, Fingerprint2)

! zlshorte.net/3BqbQ4 // Fixed
! redirected to short.imagenesderopaparaperros.com, new rules will be needed
zlshorte.net##+js(aopr, open) // Fixed
zlshorte.net##+js(aopw, Fingerprint2) // Fixed
zlshorte.net##.banner-inner // Fixed

//imgclick.net##+js(aopw, Fingerprint2)

//adsrt.*##+js(aopw, Fingerprint2)

//mp3converter.net##+js(aopw, Fingerprint2)

//megaup.net##+js(aopw, Fingerprint2)

//animeland.*##+js(aopw, Fingerprint2)

//japscan.*##+js(aopw, Fingerprint2)

//likn.xyz##+js(aopw, Fingerprint2)

//pnd.*##+js(aopw, Fingerprint2)
//pnd.*##+js(aopr, AaDetector)

//gounlimited.to##+js(aopw, Fingerprint2)

//0123movies.*,123moviesfun.*##+js(aopw, Fingerprint2)

! filescdn.net/spzsou9wuipv // Fixed
! dead?
filescdn.net##+js(aopw, Fingerprint2) // Fixed

//hqtv.biz##+js(aopw, Fingerprint2)

//nyaa.iss.one##+js(aopr, LieDetector)

//linkshorten.xyz##+js(aopr, LieDetector)

//gomovies-online.me##+js(aopr, LieDetector)

pornhub.*,pornhubthbh7ap3u.onion##+js(aopw, rAb) // Fixed
pornhub.*,pornhubthbh7ap3u.onion##+js(aeld, DOMContentLoaded, [native code]) // Fixed
pornhub.*,pornhubthbh7ap3u.onion##+js(aopw, UAParser) // Fixed

tube8.*##+js(aopw, AdDelivery) // Fixed
tube8.*##+js(aopw, rAb) // Fixed
tube8.*##+js(aopw, loadAdFromHeaderTab) // Fixed

redtube.com,redtube.net,youporn.com,xtube.com##+js(aopw, rAb) // Fixed

**Comment by okiehsch** [comment]
Please post atleast one working example link for all shorteners and file-hosting sites. 

Userscloud still uses Fingerprint2 example link `https://userscloud.com/prjtc1evtau0`
The script - it is already blocked - that uses Fingerprint2  `https://d1r90st78epsag.cloudfront.net/?etsrd=818243`

Same with `shink.me` Example link: `http://shink.me/FBLiV` Fingerprint2 is in `http://d36zfztxfflmqo.cloudfront.net/?tzfzd=872997`

We will not remove script-injections if they are still used in blocked random domains, that's the whole point of them.
It is easy for sites  to use those generic ad/popup scripts and they can easily change the domain triggering them.
They can't change the script itself.

**Comment by Yuki2718** [comment]
Sorry, I basically tracked their original issues and used the URL provided in them, but given your explanation and an assumption this can also apply to LieDetector, I'll withdraw most of the proposals and narrow down to the last porn sites which I just visited their front pages and chose random videos there - but haven't tested .onion domains.

**Comment by Yuki2718** [comment]
Regarading this AdGuard Issue: https://github.com/AdguardTeam/AdguardFilters/issues/62865, some rules for `clipwatching.com` looks like obsolete.

**Comment by Yuki2718** [comment]
Thanks!

**Comment by Yuki2718** [comment]
@okiehsch @mapx- @uBlock-user Just found `redtube.com###pb_block` is already in EL (but .net not) so can be removed.

**Comment by Yuki2718** [comment]
```
txxx.*##+js(aeld, click, pop.beforeOpen)
txxx.*##+js(nostif, t()?n())
```
are obsolete, tested on `txxx.com` (nsfw) both with and without (any) network filters.

**Comment by Yuki2718** [comment]
`clicknupload.co##+js(acis, String.fromCharCode, 'shift')`
needs to be updated, I got popup on the second page in the link at this AG issue:
https://github.com/AdguardTeam/AdguardFilters/issues/63475
AG uses `##+js(acis, String.fromCharCode, /emZnbG9hZGVk|break;case \$\./)` but only `break;case` part matches.

**Comment by ghajini** [comment]
Broken layout of website on firefox web browser

### URL=

`https://clicknupload.co/iqynbfocze5r`

### Screenshot=

https://user-images.githubusercontent.com/20338483/92689664-06370a80-f35d-11ea-8049-2cb59b6d7437.png

**Comment by Yuki2718** [comment]
@ghajini I can't reproduce, probably CNAME issue?

**Comment by okiehsch** [comment]
I can't reproduce looks like some CSS requests are blocked on your end.

**Comment by ghajini** [comment]
Yeah this **WAS** A cname issue
`@@||dotblocking.dummy^$stylesheet,domain=clicknupload.co`
 Used to work

Now I can't reproduce

**Comment by Yuki2718** [comment]
> 
> Now I can't reproduce

I once had a similar case. Try tomorrow again and don't forget to take SS of the logger :)

**Comment by Yuki2718** [comment]
`hentai2w.com###playerOverlay` is now in EL.

**Comment by Yuki2718** [comment]
@mapx- Can you also check rules for `hentai2read.com,hentai2w.com`? Apparently anything other than `hentai2w.com##+js(set, ads, 1)` are outdated at least when network filters do their job.
