### ISSUE TITLE
Latest built-in Privacy filters breaks news site images

### ISSUE THREAD

**Issue by Quisquose** [uBlockOrigin/uAssets#7853]
### URL(s) where the issue occurs
`https://www.express.co.uk/`

### Describe the issue
A recent filter list update (in the last week or so) causes all images on the Express web site home page (and its various sub-sections) to be blank. Individual news story pages are not affected (images continue to display normally there). This site has previously worked fine for years and the breakage only happened recently. Unticking the **uBlock filters – Privacy​​​​​** list restores the web site's images. Re-enabling the uBlock filters – Privacy​​​​​ list causes all the images to disappear again. The problem seems to affect only chrome-based browsers.

### Screenshot(s)
**Privacy filter enabled (images missing)**

![Privacy filter enabled](https://user-images.githubusercontent.com/7541455/91730700-f6216d00-eb9d-11ea-9fec-fb6528931943.png)

**Privacy filter disabled (images display correctly)**

![Privacy filter disabled](https://user-images.githubusercontent.com/7541455/91730723-fe79a800-eb9d-11ea-95e0-61690ef24585.png)

### Versions
- Browser/version: Slimjet 27.07 (a chrome browser clone). Built-in browser adblock _disabled_ (uBlock only).
- Browser/version:  Brave 1.10.90 (same problem)
- uBlock Origin version: 1.29

### Settings
Default uBlock settings used.

### Notes
Firefox is not affected. Web site images continue to display fine with the exact same uBlock settings.

**Comment by uBlock-user** [comment]
Thumbnails/images are served from `cdn.images.express.co.uk` which is not blocked by any **default** filter lists.

**Comment by ghajini** [comment]
But disabling Ubo ,brings back images

**Comment by uBlock-user** [comment]
Run the logger and filter all blocked items, then share it here.

**Comment by ghajini** [comment]
![Screenshot (298)](https://user-images.githubusercontent.com/20338483/91736808-e1f46480-ebcb-11ea-9959-dc3020558d70.png)

![Screenshot (298)](https://user-images.githubusercontent.com/20338483/91736845-ee78bd00-ebcb-11ea-923d-52499316f987.png)

**Comment by uBlock-user** [comment]
Add `||widgets.outbrain.com^$script,redirect-rule=none,domain=express.co.uk` and report if that helps.

**Comment by ghajini** [comment]
Doesn't work

**Comment by uBlock-user** [comment]
now try `||google-analytics.com^$script,redirect-rule=none,domain=express.co.uk`, if that fails, then try --


`||amazon-adsystem.com^$script,redirect-rule=none,domain=express.co.uk`, then try

`||googletagservices.com^$script,redirect-rule=none,domain=express.co.uk`, then try

`||scorecardresearch.com^$script,redirect-rule=none,domain=express.co.uk`

**Comment by ghajini** [comment]
`||googletagservices.com^$script,redirect-rule=none,domain=express.co.uk`
This works on my end but need to be confirmed by op @Quisquose 

Also what `redirect-rule=none` does?🙄

**Comment by uBlock-user** [comment]
> Also what redirect-rule=none does?

Disables redirection

**Comment by llacb47** [comment]
`||googletagservices.com^$script,redirect-rule=none,domain=express.co.uk`

works for me

**Comment by ghajini** [comment]
> > Also what redirect-rule=none does?
> 
> Disables redirection

So block-redirect to neutered version everywhere and just block here only?

**Comment by Quisquose** [comment]
> `_||googletagservices.com^$script,redirect-rule=none,domain=express.co.uk`_
> _This works on my end but need to be confirmed by op @Quisquose_

I can confirm that this works for me too. All images are now visible again.

Many thanks **ghajini** for going to the trouble to post the logger info and test the new rules.
