### ISSUE TITLE
anitoki.com [banner ads]

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#7857]
### URL(s) where the issue occurs

`https://anitoki.com/`
`https://anitoki.com/archives/8086`
`https://anitoki.com/archives/anime/the-god-of-high-school`

### Describe the issue

Banner ads

### Screenshot(s)

![2020-09-01_125037](https://user-images.githubusercontent.com/9832875/91799841-1448a500-ec52-11ea-866e-b6c5daee66e1.png)

### Versions

- Browser/version: [FF 80.0.1 x64]
- uBlock Origin version: [1.29.2]

### Settings

`https://pastebin.com/raw/gABWvhDK`

**Comment by mapx-** [comment]
report at indonesian filters list
https://github.com/ABPindo/indonesianadblockrules/issues
