### ISSUE TITLE
usgamer.net videos not showing on the articles.

### ISSUE THREAD

**Issue by LPatamon** [uBlockOrigin/uAssets#7859]
URL(s) where the issue occurs:

`https://www.usgamer.net/articles/animal-crossing-new-horizons-how-to-catch-a-golden-trout`

Describe the issue

The articles on USGamer.net usually include videos, but they aren't showing, instead all you see is a gray rectangle where the player should be.

Screenshot(s)
![image](https://user-images.githubusercontent.com/6118529/91844945-f06b6c00-ec1d-11ea-9987-c5e1872381a3.png)

Versions

- Browser/version: Firefox 81.0b4 
- uBlock Origin version: 1.29.2 (Updated on August 30, 2020)

Settings:

![image](https://user-images.githubusercontent.com/6118529/91845433-c6ff1000-ec1e-11ea-92c9-23d52228e658.png)
![image](https://user-images.githubusercontent.com/6118529/91845447-ccf4f100-ec1e-11ea-987a-279aac431fb8.png)

No custom filters related to USGamer.net are added in my own filters.

Notes:

The issue gets fixed when I uncheck uBlock filters. When I cliked on the eye icon next to uBlock filters to see the filters content, I found this line that is related to USGamer.net:

! https://github.com/uBlockOrigin/uAssets/issues/2637
usgamer.net##+js(aopr, _sp_._networkListenerData)

I think that somehow not only it disabled the adblock detection, but also disabled the video script that embeds them on the site, since it works if I uncheck uBlock filters so they won't be used.

**Comment by uBlock-user** [comment]
You're using ABP alongside uBlock Origin, that's a bad decision.

**Comment by LPatamon** [comment]
> 
> 
> You're using ABP alongside uBlock Origin, that's a bad decision.

ABP has nothing to do with this issue. I disabled it leaving just uBlock and the issue with usgamer.net remained. it wasn't till I disabled uBlock that it worked. Then I tested going to uBlock settings and removed the checkmark on uBlock filters, and usgamer showed the videos.

I take good care that ABP and uBlock doesn't clash.

All I know is that the issue with usgamer.net has to do with this filter that is included on uBlock's filters included with it:

! https://github.com/uBlockOrigin/uAssets/issues/2637
usgamer.net##+js(aopr, _sp_._networkListenerData)

it is disabling usgamer's own media player.

**Comment by uBlock-user** [comment]
> ABP has nothing to do with this issue.

It's not about this issue. You shouldn't be using two content blockers which make use of Easylist, period. As far this issue is concerned, I see the player broken even after uBlock Filters is disabled, so the filter you posted is not the cause of this issue. 

There's a GDPR consent that appears from `geolocation.onetrust.com` and only selecting `Accept all Cookies`, the video player appears.

**Comment by LPatamon** [comment]
> 
> 
> > ABP has nothing to do with this issue.
> 
> It's not about this issue. You [shouldn't](https://twitter.com/gorhill/status/1296122090026946567) be using two content blockers which make use of Easylist, period. As far this issue is concerned, I see the player broken even after uBlock Filters is disabled, so the filter you posted is not the cause of this issue.
> 
> There's a GDPR consent that appears from `geolocation.onetrust.com` and only after selecting `Accept all Cookies`, the video player appears.

It has nothing to do with cookies in this case. if it was related to cookies, the video won't appear not matter if I disabled uBlock, and it appears only when I disable uBlock or disable to use uBlock filters leaving just my custom filters active.

Here. I disabled ublock and the video (along withe ads on the side and on the top appear. It is uBlock related issue from the filter I mentioned above.

![image](https://user-images.githubusercontent.com/6118529/91855595-04699a80-ec2b-11ea-9569-0e7f16a7f97f.png)

About using ABP and uBlock, I had no issues at all. As I said, I make sure the won't clash. my browser isn't even slow at all.

**Comment by llacb47** [comment]
@uBlock-user OP is right, the videos are broken even after accepting cookies. Did you test the site?

Fix:
```
usgamer.net#@#+js(abort-on-property-read, _sp_._networkListenerData)
@@||usgamer.net/static/scripts/AdsLoad.js$script,1p
@@||usgamer.net/static/scripts/SidebarAds.js$script,1p
```

**Comment by uBlock-user** [comment]
Anti-adblock appears if we disable that scriptlet filter, will need another filter if we have to disable the existing filter.

**Comment by llacb47** [comment]
> will need another filter

`||usgamer.net/static/scripts/musgamer-fsm.js` ?

**Comment by LPatamon** [comment]
> 
> 
> Anti-adblock appears if we disable that scriptlet filter, will need another filter if we have to disable the existing filter.

in my case the Anti-adblock didn't appear since I have the generichide and genericblock filters on ABP. In my case I got the PAX event ads, but I hid them with uBlock block element.

> 
> 
> @uBlock-user OP is right, the videos are broken even after accepting cookies. Did you test the site?
> 
> > About using ABP and uBlock, I have no issues at all. As I said, I make sure the won't clash. my browser isn't even slow at all.
> 
> `https://twitter.com/gorhill/status/1033706103782170625`

Well I have no cpu excessive usage right now is at 1-2% usage, and ram is quite on good level as well.

I disabled on ABP "Block additional tracking" and also have disabled (unchecked) Allow Acceptable Ads

On uBlock I unchecked 4 out of 5 built-in filter lists. on ABP I only have 3 filter list suscriptions active.

As I mentioned before, I know how to handle both add-ons, I have no load delay on any website, but thanks for the advise :)

**Comment by llacb47** [comment]
why cosmetic instead of my suggestion? the script path hasn't changed since at least january `https://web.archive.org/web/20200102175022/https://www.usgamer.net/articles/pokemon-sword-and-shield-mystery-gift-codes-list`

https://github.com/uBlockOrigin/uAssets/commit/f518bbace4d57522fff34985ab65beba8adaf6af

**Comment by uBlock-user** [comment]
They can change the path anytime, so going cosmetic until a scriptlet filter is found.
