### ISSUE TITLE
eBay issues with v.1.29.2

### ISSUE THREAD

**Issue by CaveatEmptor57** [uBlockOrigin/uAssets#7861]
### Versions

- Browser/version: [Firefox 80]
- uBlock Origin version: [1.29.2]

### Settings

-

**Comment by mapx-** [comment]
easyprivacy authors have fixed an issue for ebay sites, update your lists and in the future provide a minimal explanation on your issues

**Comment by CaveatEmptor57** [comment]
Thanks for solving this so quickly - it's much appreciated.

Kind regards,
@CaveatEmptor57

PS I did provide an issue explanation & screenshot but, as a newbie, I didn't realise I had to place them within the square brackets ([...]) whereas I removed the brackets themselves...

________________________________
