### ISSUE TITLE
Ebay.co.uk item image carousel blocked

### ISSUE THREAD

**Issue by laffo16** [uBlockOrigin/uAssets#7862]
### URL(s) where the issue occurs

https://www.ebay.co.uk

### Describe the issue

Open any auction which has multiple thumbnail images of the item.
Clicking any thumbail on the carousel does nothing.
It should switch main preview window to show the clicked image.
Is the javascript blocked?

### Screenshot(s)

No images

### Versions

- Browser/version: Firefox 81
- uBlock Origin version: 1.29.2

### Settings

No changes

### Notes

Only checked that uBlock Origin is the cause, and yes it is.
Thanks for your help!

**Comment by llacb47** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7861#issuecomment-685740709

**Comment by laffo16** [comment]
Settings > Filter Lists tab > EasyPrivacy (click clock icon to update filter list)
Cheers guys! that was fast!
