### ISSUE TITLE
rarbgmirror.org

### ISSUE THREAD

**Issue by electrifying** [uBlockOrigin/uAssets#7863]
`https://rarbgmirror.org/torrents.php`

when you first enter the site, you cannot pass the check from spambots. with ad blocker enabled endless loading

 

https://imgur.com/XkxkRWK

### Versions

- Browser/version: google chrome 85
- uBlock Origin version: 1.29.2

### Settings

uBO's default settings

### Notes

none

**Comment by electrifying** [comment]
@uBlock-user you can check the problem using Russian ip?

**Comment by uBlock-user** [comment]
No change with Russian VPN either, working as expected.
