### ISSUE TITLE
Recent problem when using with Ebay

### ISSUE THREAD

**Issue by NumberNx** [uBlockOrigin/uAssets#7864]
### URL(s) where the issue occurs

 www.­ebay.co.uk

### Describe the issue

 
When Ublock is active, Ebay's;  purchase history is blank, Recently viewed is blank, cannot change images/views of items when on an item page and add to watchlist links or add to list dropdown doesnt work. 
If disabling Ublock on Ebay page all works fine. 

### Versions

- Browser/version: [Chrome  80.0.3987.106 (Official Build) (64-bit)]
- uBlock Origin version: [1.29.2]

### Settings

None, other than enabling / disabling on problem site/pages

**Comment by mapx-** [comment]
Did you update all your lists ?

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7861

**Comment by NumberNx** [comment]
Thanks for the hints, and the link to 7861. Problem only started a week or so ago, did not have problems before then. Have updated lists - same problems, purchase and recently viewed pages blank, and an items images / carousel does not work.
Restarted Chrome, just in case, problems are the same, a noticeable difference post updating lists is that page changes/updates seem slower now with uBlock active, 
I'm only aware of problems on ebay, I was thinking they'd changed/mucked up something, until I started going through addons and found disabling uBlock on ebay 'fixes' the problem.

**Comment by uBlock-user** [comment]
Did you test on default settings ? The issue was of a filter in EasyPrivacy.

**Comment by NumberNx** [comment]
HIya user, I do not recall ever changing any settings, however having reset them to default seems to have 'fixed' it , including after updating the filters.
I have never fiddled/had the need to with settings, just allowing all to do what they do including the automatic updates (although I loath MS/Win10 and its pushed updates. 

So far so good, and thanks all for the pointers.
