### ISSUE TITLE
[Anti-Adblock] https://www.cbssports.com/

### ISSUE THREAD

**Issue by Dan33185** [uBlockOrigin/uAssets#7866]
### URL(s) where the issue occurs

[https://www.cbssports.com/]

### Describe the issue

[I see the following message when going to the website: "Your browser or blocker is impacting your experience. Click below to access the full site."]

### Screenshot(s)

![Untitled1](https://user-images.githubusercontent.com/5460711/92156484-ac7b9100-edee-11ea-9fe0-2d4ab1bb3318.png)]

### Versions

- Browser/version: [Chrome 85.0.4183.83]
- uBlock Origin version: [v1.29.3b8]

### Settings

-

**Comment by mapx-** [comment]
@pgl 
`||plotrabbit.com^`

**Comment by pgl** [comment]
@mapx- Added, thanks.
