### ISSUE TITLE
Annoyance Welt.de

### ISSUE THREAD

**Issue by Symbai** [uBlockOrigin/uAssets#7873]
### URL(s) where the issue occurs

`https://www.welt.de/`

### Describe the issue

Clear cookies and visit website. It shows a data privacy popup which you have to accept first.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/14368203/92305279-0e223380-ef86-11ea-9fd1-2279c5a470b6.png)

### Versions

- Browser/version: Edge 85.0.564.44
- uBlock Origin version: uBlock Origin v1.29.2

### Settings

![image](https://user-images.githubusercontent.com/14368203/92305295-36119700-ef86-11ea-8b25-ac5654f32b74.png)

**Comment by uBlock-user** [comment]
> GDPR messages will not be addressed in uAssets.
