### ISSUE TITLE
Google.com - Before you continue popup

### ISSUE THREAD

**Issue by 0xsuid** [uBlockOrigin/uAssets#7877]
### URL(s) where the issue occurs
`https://www.google.com/search?client=firefox-b-d&q=test`

### Describe the issue
There is "Before you continue" Popup.
 

### Screenshot(s)
![Screenshot](https://i.ibb.co/gb13y9c/test.png)

[Image](https://ibb.co/twf4BK1) will be autodeleted after 2 weeks

### Versions

- Browser/version: Firefox/80.0.1
- uBlock Origin version: 1.29.2

### Settings

- Default

### Notes

- I will create PR in very short time.

**Comment by 0xsuid** [comment]
Added PR #7878

**Comment by krystian3w** [comment]
IMO GDPR so:

> GDPR messages will not be addressed in uAssets.

**Comment by krystian3w** [comment]
Poland users no test two versions:
```
##body.QVCmK:style(position: static !important; overflow-y: visible !important;)
##html.QVCmK:style(overflow-y: visible !important;)
###main #lb > div[id^="_"] > div[class*=" "]:not([id]):empty:matches-css(opacity: 0.7)
###main #lb > div[id^="_"] > div[class*=" "]:not([id]):has( > span > div[role="dialog"] > #cnsw > iframe[src*="://consent.google.com"])
```

```
###main #lb > div[id^="_"] > div[class*=" "]:not([id]):empty:matches-css(opacity: 0.7):remove()
###main #lb > div[id^="_"] > div[class*=" "]:not([id]):has( > span > div[role="dialog"] > #cnsw > iframe[src*="://consent.google.com"]):remove()
```

**Comment by uBlock-user** [comment]
> GDPR messages will not be addressed in uAssets.
