### ISSUE TITLE
torrentfunk.com

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#788]
https://www.torrentfunk.com/contact.html

When you go to the website it doesn't show the contact us email address on the page and other information when uBlock Origin is enabled, but if you disable it, then it shows the email address and other information. Why does it block that, and is there a way to fix it? Thanks.

![torrentfunk contact us with adblocker](https://user-images.githubusercontent.com/26278182/32112986-dc51fdb4-bb0c-11e7-9a3e-e144f1b89968.jpg)

![torrentfunk contact us without adblocker](https://user-images.githubusercontent.com/26278182/32113227-b08b01de-bb0d-11e7-9ce9-3439e9dbdcf7.jpg)

Waterfox 55.2.2
uBlock Origin 1.14.16

**Comment by okiehsch** [comment]
The only way for me to reproduce your issue is to block this request.
![unbenannt](https://user-images.githubusercontent.com/16838044/32115102-ce66b2ce-bb45-11e7-9f0f-6c1a521a98ff.PNG)
So if you open your logger and reload the site, is it blocked on your end?

**Comment by js017** [comment]
Yes that worked. Thank you.
