### ISSUE TITLE
Magoosh fails to detect country and displays international plans

### ISSUE THREAD

**Issue by Silver-Fullbuster** [uBlockOrigin/uAssets#7880]
# URL(s) where the issue occurs

`gre.magoosh.com/plans`

### Describe the issue

Firefox Tracking Protection has the same issue and needs to be disabled as well to reproduce the issue purely through uBlock Origin.
With uBlock Origin on (and Firefox tracking protection off), the url `https://gre.magoosh.com/plans` doesn't redirect to `https://gre.magoosh.com/plans-in`, which I presume is for the Indian audience. There is a price difference in the plans and thus, can lead the user to not realize the existence of the Indian plans.

To reproduce, I imagine you need to access the website through an Indian IP address.

### Versions

- Browser/version: Firefox x64 v80.0.1 on Windows 10 v1909 
- uBlock Origin version: v1.29.2

### Settings

No changes since installation besides some custom blocks on some unrelated webpages

### Notes

Firefox Tracking Protection also has the same issue. If both are on, disabling either the addon or tracking protection doesn't fix the issue, both need to be turned off

**Comment by mapx-** [comment]
@ryanbr

**Comment by krystian3w** [comment]
https://github.com/disconnectme/disconnect-tracking-protection/issues/new if no fixed by Mozilla team.
