### ISSUE TITLE
Musixmatch

### ISSUE THREAD

**Issue by PyIV** [uBlockOrigin/uAssets#7881]
### URL(s) where the issue occurs

`musixmatch.com`
### Describe the issue

 
Searching for songs doesn't work.
### Versions

- Browser/version: [Firefox for Android v80]
- uBlock Origin version: [1.29.2]

### Settings

- All filters are active.

### Notes

Turning uBlock off solves the issue.
I tried whitelisting some domains and elements but couldn't get it to work.

**Comment by uBlock-user** [comment]
Add `musixmatch.com#@#+js(set-constant, MutationObserver, trueFunc)` and report back

**Comment by uBlock-user** [comment]
filter removed - https://github.com/uBlockOrigin/uAssets/commit/3186f701bf5948133c5a408373effa5507c5789e

Force update uBlock Annoyances list for the fix.

**Comment by PyIV** [comment]
Thank you so much. Works now.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/6594
