### ISSUE TITLE
formulatv.com

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#7882]
### URL(s) where the issue occurs

`https://www.formulatv.com/`
`https://www.ecartelera.com/`

### Describe the issue

BIIIIIIG AD

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [v1.29.2]

**Comment by mapx-** [comment]
for the second page:

`ecartelera.com##.pub-prodigal`

for the first where is the ad ? screenshot ?

to be reported here:
https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by PIZZA90** [comment]
first page:

https://i.imgur.com/OedlYXD.png

second page:

https://i.imgur.com/z3A5snQ.png

you filter is working

**Comment by mapx-** [comment]
for the first page I cannot reproduce it, maybe the generic filter `##.pub-prodigal` is working for the first page too

**Comment by PIZZA90** [comment]
i need turn OFF uBO for reproduce the videos, after does that is working even with ubo ON.
someone who enters this site for the first time, without having cookies saved ... the videos will not work.
forcing to disable adblocker for watch videos.

If I clear the cookies and access the videos with the adblocker active, it doesn't work again. 🙄

`https://www.formulatv.com/videos/`
