### ISSUE TITLE
uBlock affecting image loading for emails on mail.yahoo.com

### ISSUE THREAD

**Issue by kcollins7** [uBlockOrigin/uAssets#7883]
### URL(s) where the issue occurs

`https://mail.yahoo.com/`

### Describe the issue

uBlock is preventing emails from loading images properly.

### Versions

- Browser/version: Chrome/85.0.4183.83
- uBlock Origin version: v1.29.2

### Settings

Nano Defender installed and activated, uBlock Origin Extra also installed
Custom Lists:
Adblock Warning Removal List 778 used out of 782
Malware Domain List 1,104 used out of 1,104
Malware domains 26,839 used out of 26,854
Nano Defender Integration 2,611 used out of 2,624
Nano Filters 417 used out of 417
Nano Filters - Whitelist 0 used out of 0
uBlock filters – Experimental 11 used out of 12

Custom Rules:
no-large-media: behind-the-scene false
no-scripting: behind-the-scene false
no-strict-blocking: go.redirectingat.com true
no-strict-blocking: go.skimresources.com true
no-strict-blocking: shareasale.com true
no-strict-blocking: www.anrdoezrs.net true
no-strict-blocking: www.dpbolvw.net true
no-strict-blocking: www.emjcd.com true
no-strict-blocking: www.jdoqocy.com true
behind-the-scene * * noop
behind-the-scene * 1p-script noop
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
behind-the-scene * 3p-script noop
behind-the-scene * image noop
behind-the-scene * inline-script noop

### Notes

Turning off uBlock fixes the issues but the web page is absolutely littered with ads.

**Comment by krystian3w** [comment]
I see - guilty `EasyPrivacy`:

```
||yusercontent.com/mail?url=$image,domain=mail.yahoo.com
```

So try:
```
||yusercontent.com/mail?url=$image,domain=mail.yahoo.com,badfilter
```

---

demo image from Eset:

```
https://ecp.yusercontent.com/mail?url=https%3A%2F%2Fclm.esetstatic.com%2Fimages-generic-modular-templates%2Fhybrid%2Flogo-footer-color-wrapped-claim.png&t=1599480596&ymreqid=e8010723-3f05-8e0b-1c80-c60001012100&sig=cXOB45S.G7NRJ9HSsjcCpw--~D
```

**Comment by kcollins7** [comment]
Appreciate it!

**Comment by uBlock-user** [comment]
filter removed from EasyPrivacy, force update that list.
