### ISSUE TITLE
vidsrc.me

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#7884]
### URL(s) where the issue occurs

`v2.vidsrc.me/embed/tt4682266/`

### Describe the issue

Popup ads

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.29.3b9

### Settings

uBO's default settings
-

**Comment by ghajini** [comment]
When vidsrc2 option is selected, antiadblock is shown irrespective of adblocker enabled or not. ...any fix available?

**Comment by mapx-** [comment]
no issues on option 2 on my end FF / opera

**Comment by ghajini** [comment]
Turn on inbuilt vpn in opera browser & set to optimal location?

**Comment by uBlock-user** [comment]
Opera's likely blocking third-party domains(websocket) which bypasses anti-adblock. Disable Opera's adblocker.

**Comment by ghajini** [comment]
Opera adblocker(Easylist) already disabled completely

**Comment by mapx-** [comment]
yeah, it's vpn in opera which blocks some stuff and trigger anti adb

**Comment by ghajini** [comment]
Link= `v2.vidsrc.me/embed/tt4682266/`

This filter 
`vidsrc.*##+js(set, String.fromCharCode, trueFunc)`
Causes player to not load ....
Dev tools check by site and propeller stuff

**Comment by mapx-** [comment]
test

```
vidsrc.*#@#+js(set-constant, String.fromCharCode, trueFunc)
vidsrc.*#@#+js(abort-on-property-read, AaDetector)
vidsrc.*##+js(aopr, console.clear)
vidsrc.*##+js(acis, String.fromCharCode, break)
```

**Comment by ghajini** [comment]
That help

**Comment by mapx-** [comment]
okiehsch fixed the main issue, so I deleted my first reply
