### ISSUE TITLE
play.tv3.lt video ads aftter filters update

### ISSUE THREAD

**Issue by Vartotojas1234** [uBlockOrigin/uAssets#7886]
`https://play.tv3.lt/tv3-zinios-10965014`

After Ublock origin filter lists updates i see video with ads on play.tv3.lt 

![Untitled](https://user-images.githubusercontent.com/24992139/92403325-e673cc80-f139-11ea-9af7-eaff24dafbd0.png)

- Browser/version: [85.0.4183.83]
- uBlock Origin version: [1.29.2]

filter lists:
![Untitled 2](https://user-images.githubusercontent.com/24992139/92403530-52eecb80-f13a-11ea-9b76-a5b42c37f136.png)
![Untitled 3](https://user-images.githubusercontent.com/24992139/92403546-5b470680-f13a-11ea-96e1-687a9b457491.png)

-

Before filter lists update ads was blocked

**Comment by uBlock-user** [comment]
Add `||freewheel-mtgx-tv.akamaized.net^$media,domain=tv3.lt` and test again

**Comment by martitis** [comment]
Not working on this website again, cant find myself manually why
