### ISSUE TITLE
picload.org

### ISSUE THREAD

**Issue by kasper93** [uBlockOrigin/uAssets#789]
I was cleaning my filters and noticed this for `picload.org` which could be merged, I think.

Test link: `https://picload.org/view/rppiwlgw/v6oxf.png.html`

```
@@||picload.org/image/$image
picload.org##.stageAds
```

**Comment by okiehsch** [comment]
Why is `@@||picload.org/image/$image` necessary on your end?
`https://picload.org/view/rppiwlgw/v6oxf.png.html` works fine without any exception filter on my end.

**Comment by kasper93** [comment]
They do this request to detect adblock
```
https://img2.picload.org/image/rppiwlgw/v6oxf.png#/ad-images/ad/ad/frame1./adbureau./ajax-advert./files/ads/ad/layad./layout/ads/ad/systemad_ad=displayAds&_StickyAdFunc.
```
IIRC preferred way is to allow such request so the site doesn't detect blocker. But actaully in this case if we block both `.stageAds` and `#stageAds` we are fine, so allowing this is optional, I guess.

Easylist has `@@||picload.org^$generichide` So we actually need 
```
@@||picload.org/image/$image
picload.org##.stageAds
picload.org###stageAds
```

First like I said optional to break blocker detection on site. Second for top and bottom boxes. Third for overlay over image, not always loads.
