### ISSUE TITLE
peekvids.com [NSFW]

### ISSUE THREAD

**Issue by electrifying** [uBlockOrigin/uAssets#7891]
`https://www.peekvids.com/sv/czech-stepmom-florane-russell-spanks-blonde-teen-jenny-wild/zrk_xMIC3pl`

blank window from blocked ads on pause and to the right of the player, as well as at the very bottom of the page

 

`https://imgur.com/iIzqjt8`
`https://imgur.com/F8FmXMW`

### Versions

- Browser/version: google chrome 85
- uBlock Origin version: 1.29.2

### Settings

 uBO's default settings

### Notes

none

**Comment by uBlock-user** [comment]
`peekvids.com##.card-deck-promotion`

@ryanbr

**Comment by electrifying** [comment]
> ```
> peekvids.com##.card-deck-promotion
> peekvids.com##.col-lg-auto.col-12
> peekvids.com##.mediaPlayerSponsored
> ```
> 
> @ryanbr

rules works but an empty white window on pause still remains

**Comment by mapx-** [comment]
@uBlock-user we can add cosmetic filters in this case because we already have other filters in our lists

**Comment by uBlock-user** [comment]
@electrifying updated

**Comment by uBlock-user** [comment]
@mapx- https://github.com/uBlockOrigin/uAssets/commit/561a15e4f09f18617568a5becf44e72173bcbbf5

**Comment by electrifying** [comment]
@uBlock-user  @mapx-  `https://imgur.com/DtUb13i`

**Comment by mapx-** [comment]
sponsored + trending stuff ? self-promotion no ad on my side

**Comment by mapx-** [comment]
I added `peekvids.com##.block-advert` => should fix it
