### ISSUE TITLE
Mylead.global domain locks

### ISSUE THREAD

**Issue by myleadd** [uBlockOrigin/uAssets#7892]
### URL(s) where the issue occurs

`https://mylead.global/`

and all sites that use blocked domains

### Describe the issue

uBlock Origin blocks the following domains:

- `static.mylead.global`
- `static2.mylead.global`

As a result, people who have the plug-in installed will not see any graphics on the `mylead.global` website.

### Screenshot(s)

https://prnt.sc/ue9r58
https://prnt.sc/ue9raz
https://prnt.sc/ue9wpl
https://prnt.sc/ue9x47
This is without uBlock: https://prnt.sc/ue9xxy and this is with: https://prnt.sc/ue9yem

### Versions

- Browser/version: Chrome/Firefox/Opera
- uBlock Origin version: newest

### Notes

The static.mylead.global and static2.mylead.global domains do not contain dangerous content. They contain website-related content and content to be used in promotion (e.g. mailings). So I would be very grateful for unlocking these domains.

**Comment by uBlock-user** [comment]
> people who have the plug-in installed will not see any graphics on the mylead.global website.

Not possible, I added `$3p` for that reason, so whoever visits `mylead.global` will not have anything blocked.

**Comment by mapx-** [comment]
@myleadd the problem is you used those subdomains to push ads:

for example (on some shortener)
`https://static2.mylead.global/img/programs/logo/program_195843_1588756133.png`

**Comment by myleadd** [comment]
@mapx- , hmmm. Such graphics are used only in two places - on the campaign list [https://mylead.global/en/list-of-affiliate-programs] and on the subpage of a given campaign [in your case: https://mylead.global/en available-campaigns-in-mylead / flixvod_195843]. We use push notifications only for mobile devices and I don't know anything about the use of static.mylead.global or static2.mylead.global images there.

**Comment by uBlock-user** [comment]
@myleadd It's used here - `https://shortenbuddy.com/J5yQZ7`

**Comment by gorhill** [comment]
> people who have the plug-in installed will not see any graphics on the `mylead.global` website

The block filter `||mylead.global^` is not active on the site `mylead.global`. Something else than this filter is blocking the requests, I don't see them blocked with uBO.

Is it possible the issue is with another blocker making use of uBO filters? If so, the issue is with the other blocker not enforcing the filter properly.

**Comment by krystian3w** [comment]
You have active any regional list e.g. `EasyList Thailand` (I suppose that no block this domain too)?

**Comment by myleadd** [comment]
Hello,
thank you for all the suggestions.

@uBlock-user,
you're right - [https://prnt.sc/uet4em](https://prnt.sc/uet4em). Some advertising from MyLead is displayed here, but it is not related to us in any way. Someone just decided to promote the Flix campaign through this website and earn this way.

We will contact the portal with a request to remove the ad. However, the graphic uses static2.mylead.global. What about static.mylead.global?

@gorhill ,
we checked various ad blockers and another one has a similar problem as uBlock Origin - Adblock for Firefox [[https://addons.mozilla.org/pl/firefox/addon/adblock-by-adbkg/?src=search](https://addons.mozilla.org/pl/firefox/addon/adblock-by-adbkg/?src=search)]. Additionally, uBlock Origin blocks domains on Chrome, Firefox and Opera - we tested them on these browsers and they were always blocked. We are not alone in this problem - the problem was reported to us by the user. We checked and in fact - he was right.

Additionally, we checked:
AdBlock - Chrome - works
uBlock - Chrome - works
Ghostery - Mozilla - works
AdBlocker Ultimate - Mozilla - works
AdGuard AdBlocker - Mozilla - works
Adblock Plus - Opera - works

@krystian3w ,
I don't know anything about it, it's a clean install of uBlock Origin, without adding any additional lists to it.

If I could ask for further support in getting the static.mylead domains up and running, I would be very grateful.

**Comment by uBlock-user** [comment]
> uBlock Origin blocks domains on Chrome, Firefox and Opera - we tested them on these browsers and they were always blocked.

Third-party blockage, not blocked on your own site. So I don't see the issue you claim to have.

> We are not alone in this problem - the problem was reported to us by the user.

Have the user report here itself instead.

> If I could ask for further support in getting the static.mylead domains up and running, I would be very grateful.

Once again, third-party blockage, your site is not affected in any way neither is that domain blocked. Unless you provide a case where your site is broken, this is just turning into back and forth responses with nothing to add.

**Comment by myleadd** [comment]
> Third-party blockage, not blocked on your own site. So I don't see the issue you claim to have.

Okay, could I then ask for information what is "Third-party blockage"? Is this some kind of external locklist? Can you somehow influence it? Because as you can see from the screenshots - the problem exists and the graphics are actually blocked. There is any way to find out what exactly this is at fault?

**Comment by okiehsch** [comment]
Can you post the logger result?
Open the [logger](https://github.com/gorhill/uBlock/wiki/The-logger).
Go to the site were you see the breakage and post the result here.
For example if I go to `https://mylead.global/en` this is what I get.
![image](https://user-images.githubusercontent.com/16838044/92715558-ece28e00-f35d-11ea-8531-660cb2078d09.png)
The red entries are "blocked" requests.

**Comment by mapx-** [comment]
@uBlock-user 

> content to be used in promotion (e.g. mailings)

I guess he is talking about content blocked in some mail / newsletter

**Comment by uBlock-user** [comment]
> what is "Third-party blockage"

`mylead.global` will be blocked every except on `mylead.global` itself

@mapx- We could restrict the filter to the shortener itself since I haven't seen any other case where `mylead.global` is used for ads.

**Comment by krystian3w** [comment]
I found this:

`||static*.mylead.global^$image` in `POL-0`:

![Screenshot_2020-09-10 Affiliate network ☛ The best, global marketing programs to get leads ⭐ MyLead ⭐](https://user-images.githubusercontent.com/35370833/92715981-7f832d00-f35e-11ea-88c2-b2f34f336048.png) |
--- |
example broken homepage |

@majkiit add "`,thrid-party`"

**Comment by myleadd** [comment]
Here are examples for static2.mylead.global
[https://prnt.sc/ue9r58](https://prnt.sc/ue9r58)
[https://prnt.sc/ue9raz](https://prnt.sc/ue9raz)
[https://prnt.sc/ue9wpl](https://prnt.sc/ue9wpl)
[https://prnt.sc/ue9x47](https://prnt.sc/ue9x47)

Here is an example for static.mylead.global
This is without uBlock: [https://prnt.sc/ue9xxy](https://prnt.sc/ue9xxy) and this is with: [https://prnt.sc/ue9yem](https://prnt.sc/ue9yem)

The mylead.global website itself is not blocked. Static2 

@okiehsch,
sure. This is it: [https://prnt.sc/uetvro](https://prnt.sc/uetvro). And still show some new.

I also entered `https://www.beermoneyforum.com/threads/mylead-global-new-standard-of-affiliate-marketing-get-it-on-a-new-level.32714/page-12`, where they are used graphics from static.mylead.global. Here Logger also shows locks: [https://prnt.sc/uetwd0](https://prnt.sc/uetwd0)

**Comment by mapx-** [comment]
@myleadd I guess you could restrict the access to those subdomains at server level (whitelisting only the trusted sites / forums)

**Comment by uBlock-user** [comment]
> I also entered https://www.beermoneyforum.com/threads/mylead-global-new-standard-of-affiliate-marketing-get-it-on-a-new-level.32714/page-12

I see images getting blocked here, will restrict the domain to shortener.

**Comment by okiehsch** [comment]
Thanks, so looking at your logger output you do have the polish list enabled.
It is not enabled by default and we do not have direct control over that list.
If you add `||static*.mylead.global^$image,badfilter` to your personal filter list.
https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters

Does the site work fine after that.

**Comment by uBlock-user** [comment]
> Some advertising from MyLead is displayed here, but it is not related to us in any way. Someone just decided to promote the Flix campaign through this website and earn this way.

@myleadd That wouldn't happen if you restrict [hotlinking](https://simple.wikipedia.org/wiki/Hotlinking) of your server resources to your own domain or your customers.

**Comment by MajkiIT** [comment]
@krystian3w Done

**Comment by myleadd** [comment]
@okiehsch,
yes, when i added `||static*.mylead.global^$image,badfilter`, the problem was completely gone. Additionally, you are right - in the settings I can see that I automatically have filters for Poland turned on - [https://prnt.sc/uf3s5p](https://prnt.sc/uf3s5p).

I checked the situation now and it seems that everything is displayed correctly. @MajkiIT if I could just ask you to remove MyLead from all filters, I would be very grateful. While browsing the files, I found 2 other filters that include static.mylead.global in the list (I don't know if they are used anywhere):
[https://github.com/MajkiIT/polish-ads-filter/blob/f88b1ad31312af97bba66b149c5f31cd0df5ce34/polish-adblock-filters/adblock.txt](https://github.com/MajkiIT/polish-ads-filter/blob/f88b1ad31312af97bba66b149c5f31cd0df5ce34/polish-adblock-filters/adblock.txt)
[https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/adblock.txt](https://github.com/MajkiIT/polish-ads-filter/blob/master/polish-adblock-filters/adblock.txt)

From what I can see the lists are updated every 24 hours [`Expired: 1 day`] so the problem should be completely gone soon :)

Thank you all for your help and time.
