### ISSUE TITLE
Overdue bill not showing up on CAF.FR

### ISSUE THREAD

**Issue by Noideawhattoputhereagain** [uBlockOrigin/uAssets#7899]
### URL(s) where the issue occurs

`https://wwwd.caf.fr/wps/myportal/caffr/moncompte/mesdettes/!ut/p/a1/[UNIQUE&PRIVATE ID]/#/consultation`

### Describe the issue

The issue prevents unpaid bills to show up in the appropriate section of the website. I got an overdue letter from this agency for an overawarded amount that was not showing up on my account. After deactivating uBlock Origin, the line for the bill showed up. Luckily, it was my first warning, so no fine were applied.  
This website is for french social welfare regarding housing aids, family, ... A lot of people in France depend on it as it considerably helps them with various social allowances, with at least 5 millions people receiving some form of aid. So this issue can have very serious implications for people not tech savvy enough to figure out that UO can sometimes hide the wrong things. 

### Screenshot(s)

No screenshot as after paying the overdue amount, the bill disappears from the appropriate section.

### Versions

- Browser/version: Firefox 80.0.1
- uBlock Origin version: 1.29.2

### Settings

-Deactivating uBlock Origin for this website

### Notes

Unfortunately, only eligible people can access this website, so mainly french citizens. I have not the skills to solve this issue by myself, but I'm not sure connecting to the website is required to solve this issue. Maybe just whitelisting caf.fr altogether could prevent this problem to happen again.

**Comment by mapx-** [comment]
- open uBO logger
- refresh page / go to the page where you get the issue
- select only the blocked items in the logger and post them here as screenshots (1 or more pages)

**Comment by uBlock-user** [comment]
try `@@||caf.fr^*/smarttag.js$script,1p`

**Comment by mapx-** [comment]
@Noideawhattoputhereagain  your feedback ?

**Comment by Noideawhattoputhereagain** [comment]
> * open uBO logger
> * refresh page / go to the page where you get the issue
> * select only the blocked items in the logger and post them here as screenshots (1 or more pages)

Hi, sorry for the delay, I'm working on saturdays, long week. Thanks for the reply.  

![image](https://user-images.githubusercontent.com/71005093/93016049-8c9e5700-f5be-11ea-92c5-d537dad4beea.png)

I'm not super duper knowledgeable in this area, so please forgive me if this is not what you asked.

Surprisingly, The payed bill still is blocked if I turn UO on.



> try `@@||caf.fr^*/smarttag.js$script,1p`

Hi, thanks for the help. This is beyond my skills : where and how do I put this line? Thanks.

**Comment by mapx-** [comment]
click uBO button, click "open the dashboard icon" (last at bottom on the right side), click "my filters" tab, put there the filter, test the page, report back

**Comment by mapx-** [comment]
if the first filter still does not work test this 1 too:
`@@||caf.fr^*/ruxitagentjs_$script,1p`

still does not work, test both together

**Comment by Noideawhattoputhereagain** [comment]
> click uBO button, click "open the dashboard icon" (last at bottom on the right side), click "my filters" tab, put there the filter, click "apply changes", test the page, report back

This seems to work. Issue is solved for me, thank you!  

I hope it can be fixed as a whole for people who do not realize that this is happening and don't even suspect uBO to be hiding such an important part of the website. As I said, lots of people in France use this website, some from pretty modest background.

Thanks for the help!

**Comment by mapx-** [comment]
so, the first filter is enough, added to unbreak list

**Comment by mapx-** [comment]
@ryanbr
