### ISSUE TITLE
quickdomainfwd.com

### ISSUE THREAD

**Issue by cron410** [uBlockOrigin/uAssets#79]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://quickdomainfwd.com/`

### Describe the issue

Website and blog hijackers utililize this service to hide their domains. I first encountered the issue at the infected site `http://bakerblegal.com/` by clicking their top menu buttons.

### Screenshot(s)

![image](https://cloud.githubusercontent.com/assets/3082899/16625272/a49010b4-4371-11e6-998d-b0f0bf839bd6.png)

![image](https://cloud.githubusercontent.com/assets/3082899/16625239/8c1f7dc6-4371-11e6-9868-60bc60e2444d.png)

### Versions

- Browser/version: Chrome 51.0.2704.106 m
- uBlock Origin version: 1.7.6

### Settings

- No changes, but I can provide screenshots of that if required.

### Notes

The domain redirect is different for each machine that accesses the site. Sometimes it's a Flexytalk link, sometimes its a fake BSOD site with popup dialogs.

**Comment by gorhill** [comment]
I don't understand the issue you are reporting. What are you asking me? You want a filter for exactly which issue on which site?

**Comment by cron410** [comment]
Bakerblegal.com is an example of a legitimate site that has been
compromised to redirect all links through quicksilver.com to shield the
urls of phishing sites. Should I post this somewhere else?

I don't understand the issue you are reporting. What are you asking me? You
want a filter for exactly which issue on which site?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/uBlockOrigin/uAssets/issues/79#issuecomment-230867478>,
or mute the thread
<https://github.com/notifications/unsubscribe/AC8Kk3CT2oG9VGrstLZPTC1hVUVrrdTgks5qS_gcgaJpZM4JGPj_>
.

**Comment by gorhill** [comment]
First time I tried, I was not redirected when I clicked links on Bakerblegal.com. I just tried again and I was.

For the logger output, I find that `http://www.flexytalk.net/app/js/flexytalk.js` is the bad script. Blocking this script fixes the issue.

**Comment by gorhill** [comment]
I added `flexytalk.net` and `quickdomainfwd.com` to _Badware risks_, is it what you had in mind?

**Comment by cron410** [comment]
Wow you really nailed it. Wasn't aware they had linked an external script.
Thank you!
