### ISSUE TITLE
androidrepublic.org

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#790]
### URL(s) where the issue occurs

`https://androidrepublic.org/forum/`

### Describe the issue

Anti-adblock (not the one at the top; the overlay)

**Comment by mapx-** [comment]
try
`androidrepublic.org##script:inject(abort-on-property-write.js, _0xb110)`

**Comment by terrorist96** [comment]
:+1:

**Comment by uBlock-user** [comment]
It's BAB

`androidrepublic.org##script:inject(bab-defuser.js)`

**Comment by terrorist96** [comment]
That works too.
