### ISSUE TITLE
Allows ads served by tiznmktqel.com

### ISSUE THREAD

**Issue by mishaneah** [uBlockOrigin/uAssets#7909]
### URL(s) where the issue occurs
`https://linuxhint.com`

### Describe the issue
Allows all ads served by tiznmktqel.com
 

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

-

**Comment by mapx-** [comment]
I get no ad on that page.
Provide the details requested by the template (broser, uBO version, default setup, other lists etc)

**Comment by uBlock-user** [comment]
`||tiznmktqel.com^` present in Easylist, so not possible at **default** settings.

**Comment by ghajini** [comment]
If op is asking for a ad to allow then it's not done here
