### ISSUE TITLE
video.foxbusiness.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#791]
### URL(s) where the issue occurs

`http://video.foxbusiness.com/v/5615998852001/?#sp=show-clips`

### Describe the issue

Video won't play

### Notes

Fixed by adding:
```
@@krxd.net
@@visitorapi
```

**Comment by okiehsch** [comment]
This video or any video at `http://video.foxbusiness.com` won't play on my end unless I disable uBO, so somebody else will have to come up with working filters.

**Comment by terrorist96** [comment]
Weird. It also won't work for me unless I disable uBO. If I then re-enable it, the video works (with the two added filters above).

**Comment by okiehsch** [comment]
You are right, I can reproduce, if I re-enable and reload with
````
||cdn.krxd.net/controltag/*.js$script,redirect=noopjs,domain=video.foxbusiness.com
@@||global.fncstatic.com/static/*/VisitorAPI.js$script,domain=video.foxbusiness.com
````
the videos work on my end, the problem is, if I then close and restart the browser, I have to disable uBO again to be able to watch any video, so the videos are basically unusable for the "normal" uBO user.

**Comment by terrorist96** [comment]
Why do you think disabling then re-enabling uBO fixes it? It can't be due to cache because bypass-cache reload will still allow the video to play after uBO has been disabled/re-enabled once.
@gorhill

**Comment by okiehsch** [comment]
Steps to reproduce on my end.
- Disable EasyPrivacy
- Go to `http://video.foxbusiness.com/v/5615998852001/?#sp=show-clips`
- Video won't play
- Disable then re-enable uBO
- Video will play.

- Use Adblock/Plus without EasyPrivacy
- Video will play

Tested with Chrome 62 and Firefox 56

**Comment by terrorist96** [comment]
@okiehsch same issue.
`https://www.foxbusiness.com/retail/dicks-to-remove-hunting-products-in-125-stores-amid-fallout-from-gun-ban`

Hard to reproduce, but I think adding the following and refreshing a few times fixes it.
```
@@googletagmanager.com
@@demdex.net
@@2mdn.net
```

**Comment by okiehsch** [comment]
````
@@||dpm.demdex.net/id?*AdobeOrg&$xhr,domain=foxbusiness.com
@@||smetrics.foxbusiness.com/id?*AdobeOrg&$xhr,1p
````
works for me.

**Comment by terrorist96** [comment]
Same.
