### ISSUE TITLE
Metacritic slideshows revisited

### ISSUE THREAD

**Issue by rpodric** [uBlockOrigin/uAssets#7910]
### URL(s) where the issue occurs

`https://www.metacritic.com/pictures/christopher-nolan-films-ranked-worst-to-best`

But any slideshow links I've tried on that site, including the ones here:
`https://github.com/uBlockOrigin/uAssets/issues/6537`

### Describe the issue

The slideshows do not advance. The image blurs indefinitely.

### Versions

- Browser/version: Chrome 85 and Firefox 80 (Win10)
- uBlock Origin version: 1.29.2 (and Extra 2.88 with Chrome)

### Settings

Tested with default filters

### Notes

The exceptions made last time (see above report) pertained to Doubleclick, so it's reasonable to think something to do with that has changed recently. Thanks!

**Comment by mapx-** [comment]
@ryanbr

**Comment by mapx-** [comment]
it seems we can remove the old exceptions / filters:

```
||doubleclick.net/gpt/pubads_impl_rendering_$script,domain=metacritic.com,important,badfilter
@@||doubleclick.net/gpt/pubads_impl$script,domain=metacritic.com,badfilter
@@||doubleclick.net/tag/js/gpt.js$script,domain=metacritic.com,badfilter
```
