### ISSUE TITLE
Cosmetic filtering blocks incoming share screen on Cisco Webex

### ISSUE THREAD

**Issue by heretoenhance** [uBlockOrigin/uAssets#7911]
### URL(s) where the issue occurs

webex.com

### Describe the issue

Cosmetic filtering blocks receiving screen share

### Screenshot(s)

None

### Versions

- Browser/version: [Firefox 80.0.1 (ArchLinux)]
- uBlock Origin version: [1.29.2]

### Settings

Added all filters except the region ones, ticked "Block CSP reports" and "Prevent WebRTC leak"

### Notes

Disabling cosmetic filtering solves the issue

**Comment by mapx-** [comment]
> Added all filters

- meaning you enabled all annoyances lists, social, tracking etc ? => begin testing using ONLY the default setup, then add one by one the other lists => you'll get the "bad" one => open the logger and see what items and filters are triggered

**Comment by uBlock-user** [comment]
Test on default settings
