### ISSUE TITLE
Disappearing scrollbar at some websites (e.g. www.handelsblatt.com) when consent window is blocked !!!

### ISSUE THREAD

**Issue by mr-gittes** [uBlockOrigin/uAssets#7914]

**Comment by mapx-** [comment]
add something like this:

`example.com##body:style(overflow: auto !important;)`
or
`example.com##html:style(overflow: auto !important;)`

provide exact details if you want something more precise

**Comment by mr-gittes** [comment]
Worked perfectly! Thx!

**Comment by mr-gittes** [comment]
I didn't work, sorry! (actually already pressed "consent button before!)
But this worked for handelsblatt.com:
Added "cmp-sp.handelsblatt.com" in filter rules !! Don't know why...

**Comment by mapx-** [comment]
if you are using firefox => remove all custom filters, update your lists => you cannot block consent stuff

**Comment by okiehsch** [comment]
It's already fixed in Fanboys Annoyance List.
@mr-gittes how exactly did you block the consent window?
