### ISSUE TITLE
One "stable" color for selection? (#338FFF vs #3399FF)

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#7916]
> https://github.com/uBlockOrigin/uAssets/blob/d3c351175fc83f40883b9f0bf40202c26396de4b/filters/annoyances.txt#L54 https://github.com/uBlockOrigin/uAssets/blob/d3c351175fc83f40883b9f0bf40202c26396de4b/filters/annoyances.txt#L1918 https://github.com/uBlockOrigin/uAssets/blob/d3c351175fc83f40883b9f0bf40202c26396de4b/filters/annoyances.txt#L3531 https://github.com/uBlockOrigin/uAssets/blob/d3c351175fc83f40883b9f0bf40202c26396de4b/filters/annoyances.txt#L4219 https://github.com/uBlockOrigin/uAssets/blob/d3c351175fc83f40883b9f0bf40202c26396de4b/filters/annoyances.txt#L4450

<div align="center">

# `#338FFF` `#3399FF`

</div>

`#3399FF` can by shorted to `#39F`

**Comment by okiehsch** [comment]
I don't understand the issue, you want us to change 
`opportunitydesk.org##*::selection:style(background-color: #3399FF !important)`
to 
`opportunitydesk.org##*::selection:style(background-color: #39F !important)`  
?

**Comment by krystian3w** [comment]
More, maybe all five change to `#39F` or `opportunitydesk.org` use `#338FFF` if community see better contrast.

**Comment by uBlock-user** [comment]
He's asking for consistency, instead of using two colors, pick one and stick with it.

**Comment by mapx-** [comment]
maybe we'll stick in the future with `338FFF`
