### ISSUE TITLE
dilbert.com

### ISSUE THREAD

**Issue by in4u** [uBlockOrigin/uAssets#7917]
### URL(s) where the issue occurs

`https://dilbert.com/strip/2020-09-16`

### Describe the issue

Comments section at the bottom of the page is blocked.

### Versions

- Browser/version: Firefox 80.0.1
- uBlock Origin version: 1.29.2

### Settings

Default

**Comment by krystian3w** [comment]
`@@||dilbert.com/assets/ad-*.js$script,~third-party`

broken due `EL`.

**Comment by mapx-** [comment]
@ryanbr

**Comment by in4u** [comment]
Same breakage again. The comments section is blocked.

**Comment by mapx-** [comment]
@ryanbr
