### ISSUE TITLE
False positive: Opening a link in new tab/window on some pages is identified as a pop-up and blocked

### ISSUE THREAD

**Issue by St-Ranger** [uBlockOrigin/uAssets#7918]
### URL(s) where the issue occurs

`http://42graphy.org/tango/`

### Describe the issue

On some pages, when I open certain links in a new window or tab, uBO determines it as a popup and closes the newly opened page, even though no popups are on the original or the child page.  
I have tested, opening in a new window (Shift-click, or right-click & Open Link in New Window ) or a new tab (right-click & Open Link in New Tab) results in the window/tab opened, and immediately closed.
Clicking on the link opens the linked page in the same window without any problem.
If I copy that link and paste it in a new window, no problem is detected by the filter.

For the page used as an example, ` http://42graphy.org/tango/` the "offending" link is named "Denver Memorial Day Tango Festival - 2011", under the "2011" section ( `http://42graphy.org/tango/denvermem-2011/ `).  

### Screenshot(s)

![Github-ArgentineTango-1](https://user-images.githubusercontent.com/23556268/93388043-bca06100-f82f-11ea-8db9-04edeb0fbebf.jpg)
![Github-ArgentineTango-2-filter-rule](https://user-images.githubusercontent.com/23556268/93388045-bd38f780-f82f-11ea-8da2-fae970d8ff10.jpg)
![Github-ArgentineTango-link](https://user-images.githubusercontent.com/23556268/93388614-962ef580-f830-11ea-9f66-758b9de77955.png)

### Versions

- Browser/version: [Firefox, 80.0.1 (64-bit)]
- uBlock Origin version: [1.27.10]

### Settings

- no settings were changed, except for turning it off for some other pages

### Notes

The logger clearly indicates that it is a popup filter issue. 
Copying the link and opening a page in a new window doesn't trigger the filter
The page that is being opened has just a bit of JS in it, but no popups.
Disabling uBO for the website stops nuking the page.

Many other links on the same page work just fine.
I see only one thing that is different about the "offending" page: it has a <base .. > statement:
 `<base href="http://42graphy.org/tango/denvermem-2011/best/" />`, and that URL is one level deeper than the URL called.  So, that works as a type of Redirect. But that still doesn't make it a popup.

**Comment by uBlock-user** [comment]
Because you're using the `no-popups` switch. This isn't a filter issue.

**Comment by St-Ranger** [comment]
Thank you for your quick response.

However, there is a problem with this popup filter, one way or the other: **its behavior is inconsistent.**

I have the default configuration of uBO, with this filter enabled. And I use shift-click on various links many tens of times a day, and most of them (95+%)  open in a new window without being blocked /identified as a popup.

Even on the page in question, out of about 19 links, only 3 do not "Open [Link] in New Window", while the rest do, and they don't get identified as a popup.

So, the bottom line that __the popup filter works inconsistently__. 
And it seems to me that it would make sense to figure out what is the difference between the pages linked from the page in question that allow them to "work", and not work (just for 3 links).

(Given the statistics I've mentioned above, I tend to conclude that it was not intended to treat opening legitimate links in a new window as popups.)


As an aside, in regards to gorhill/uBlock#3282 : I am not even sure if opening a link on the page and opening a highlighted link should necessarily work the same way from the point of view of the filter. In any case, - I am unable to reproduce the problem reported in that ticket. I suspect it might have been gone since it was reported almost 3 years ago.

**Comment by St-Ranger** [comment]
Just in case, links on the reported page that get blocked when you try to open them in a new window:
Tango Show: Marizabel, Todd, Judy, and Mike - December 2007 -> `http://42graphy.komkon.org/tango/show-2007`
Denver Memorial Day Tango Festival - 2011 -> `http://42graphy.org/tango/denvermem-2011/`
Videos posted to YouTube  -> http://youtube.com/SwingStR

The rest of the links work just fine, despite the popup filter.

**Comment by krystian3w** [comment]
Maybe we should start with whether this page has some **ugly javascript** to opening garbage in new cards (tabs) / windows.

If it does not contain it, you unfortunately pack yourself into the swamp using something like that: `||42graphy.org^$popup`

So try use:

```
@@||42graphy.komkon.org^$popup,domain=42graphy.org
        @@||youtube.com^$popup,domain=42graphy.org
       @@||42graphy.org^$popup,domain=42graphy.org

*$popup,domain=42graphy.org
```

Should block only bad "pop-ups" on this page as long nobody write:

`42graphy.org##+js(foo[, foo[, foo]])`

(https://github.com/gorhill/uBlock/wiki/Resources-Library)

And you no report blocked e.g. Vimeo dancing links.
