### ISSUE TITLE
genie.co.kr

### ISSUE THREAD

**Issue by Infinitay** [uBlockOrigin/uAssets#7919]
### URL(s) where the issue occurs

```
https://www.genie.co.kr/player/shareProcessV2?

https://www.genie.co.kr/player/shareProcessV2?mrseq=NzM5OTkz&flag=r&randnom=1600316404083&Shortpath=NFPDR1
```

### Describe the issue

The web page doesn't redirect to where I can listen to the song I was linked. Instead, it detects my ad-blocker, even with using Nano Defender, and asks me to disable my ad-blocker.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/6964154/93420765-a28d6f80-f87d-11ea-8a37-6c6c71936d76.png)

Translation (machine translated)
> Go on a fun music trip with Genie in the new world.
>
> Please turn off Pop-up Blocker to listen to music and select the button below if you can't listen to music|please.

### Versions

- Browser/version: `Chrome Version 85.0.4183.102 (Official Build) (64-bit)`
- uBlock Origin version: `uBlock Origin v1.29.2`

### Settings

- Nano Defender setup
  - `userResourcesLocation https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt`

### Notes

<details><summary>Logger output</summary>

```
+1
www.genie.co.kr
1
image
https://www.genie.co.kr/resources/favicon_32.ico
```
```
+1
www.genie.co.kr
1
css
https://www.genie.co.kr/resources/commons/style/basic.css?v=202009041400
```
```
+0
www.genie.co.kr
1
doc
https://www.genie.co.kr/player/shareProcessV2?mrseq=NzM5OTkz&flag=r&randnom=1600316404083&Shortpath=NFPDR1
```
```
+0
https://www.genie.co.kr/player/shareProcessV2?mrseq=NzM5OTkz&flag=r&randnom=1600316404083&Shortpath=NFPDR1
```
</details>

**Comment by Yuki2718** [comment]
Works fine on my end with default + Yous List but OP didn't show filter lists subscribed.

**Comment by Infinitay** [comment]
I probably should have posted my filters despite there not being asked for it in the template, my mistake. Here is a screenshot of my filters:

![image](https://user-images.githubusercontent.com/6964154/93420975-2ba4a680-f87e-11ea-99d1-48656833b907.png)

**Comment by uBlock-user** [comment]
Disable all other extensions and test on default settings on uBO.

**Comment by Infinitay** [comment]
I'm embarrassed to admit this whole time I never bothered to hit the button on the page to open the web player... Everything is working fine. My apologies.
