### ISSUE TITLE
arenavision2017.ml

### ISSUE THREAD

**Issue by MikeMilligan** [uBlockOrigin/uAssets#792]
### URL(s) where the issue occurs

http://arenavision2017.ml/

### Describe the issue

Overlay antiadblocker making the site unusable.

### Screenshot(s)

https://i.imgur.com/4Hh36BG.png

### Versions

- Browser/version: Firefox 57b12
- uBlock Origin version: 1.14.16

**Comment by mapx-** [comment]
add
`@@||arenavision2017.ml^$generichide`

**Comment by MikeMilligan** [comment]
Thanks a lot. It works.
