### ISSUE TITLE
files.fm

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#7920]
### URL(s) where the issue occurs

files.fm/u/jee22cfd

### Describe the issue
On clicking `download- download this file`
There is redirect malicious content which av block

Pleae block malicious content on this site if possible

### Screenshot(s)

`https://user-images.githubusercontent.com/20338483/93447360-f20c8380-f8ef-11ea-937e-75c3d7ff25a8.jpg`

`https://www.virustotal.com/gui/url/a7e04be57b19e34fe624823a0b6019f8fa52017486efb0d019181ef29a53c6ea/detection`

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: Ubo dev

### Settings

uBO's default settings
-

### Notes

files.im and files.fm are two different sites

**Comment by Yuki2718** [comment]
No redirect here.

**Comment by playonevideo** [comment]
`https://files.fm/f/sdkh8pegckzuxfb6`

Download buttons don't work when uBO is on.

**Comment by gothic-bum** [comment]
@playonevideo 

Test:  

    @@||files.fm/js/analytics_events.js$script,1p

**Comment by playonevideo** [comment]
It worked.

**Comment by gothic-bum** [comment]
Broken by `/analytics_events.js` in EasyPrivacy.

@ryanbr
