### ISSUE TITLE
Notification to accept cookies when entering https://www.google.es/

### ISSUE THREAD

**Issue by Jose1971AB** [uBlockOrigin/uAssets#7921]
Hello friends, good afternoon.

### URL(s) where the issue occurs

 [https://www.google.es/]

### Describe the issue

 
For the last 10-15 days, every time I log on to [https://www.google.es/] I get a warning to accept cookies. I am forced to accept them or to log in. **I don't like to log in to perform searches, is there a possibility to solve this?...**

### Screenshot(s)

 
![Screenshot_2020-09-05 Google](https://user-images.githubusercontent.com/44229110/93464680-d7371080-f8e9-11ea-9edc-1fdee73added.png)

### Versions

- Browser/version: [Firefox 64-bit 80.0.1]
- uBlock Origin version: [v1.29.2]

### Settings

![Filtros Predeterminados](https://user-images.githubusercontent.com/44229110/93464937-56c4df80-f8ea-11ea-8ce3-1fc69d254c79.jpg)

### Notes

Good afternoon and thank you very much

**Comment by mapx-** [comment]
test these filters
```
google.*##[src*="consent"]:upward(5)
google.*##html:style(overflow: auto !important;)
```

**Comment by uBlock-user** [comment]
```
||consent.google.com^
google.com##+js(aeld, DOMContentLoaded, CONSENT)
```

**Comment by krystian3w** [comment]
aeld do not help

**Comment by krystian3w** [comment]
`##html:style(overflow: auto !important;)` may break other subprojects by Google.

@yourduskquibbles often repair glitches with scrolling on Google - has extensive experience with Google "visionary".

**Comment by yourduskquibbles** [comment]
`##html:style(overflow: auto !important;)` shouldn't break any google subdomain pages from what I know and have experienced. 

An issue could arise if one sets either `overflow`, `overflow-y` or `overflow-x` to `hidden` _i.e._ `google.*:style(overflow: hidden !important;)` has high likelihood of unintended breakage if used with `google.*` and not targeted to specific google domain/subdomain. 

In general, google search, google finance, & google news are the only google sites that use the `www` subdomain so if a filter is applied as `www.google.*` it should should not break other subdomains like `account.google.com`, `docs.google.com`, `photos.google.com`, `mail.google.com`, `support.google.com`, etc.

**Comment by krystian3w** [comment]
Maps also use `www.` instead `maps.` subdomain.

**Comment by Jose1971AB** [comment]
Hello mapx, good evening.

Sorry to reopen the subject, I honestly do not know where I should reopen the case and I do it here.

You gave me 2 parameters to add them in the tab of My filters, at least that's how I understood in your answer, to solve my problem, but it turns out that I just realized that it is solved for one thing and breaks other two.

The two parameters in question are
google.*##[src*="consent"]:upward(5)
google.*##html:style(overflow: auto !important;)

I explain...

If I set both parameters, the warning to accept cookies in [https://www.google.es/] is fixed, but it breaks google images. 
**https://i.ibb.co/QdMHdbP/AA.jpg**

I solve this by leaving only the first parameter --> `google.*##[src*="consent"]:upward(5)` That is, so far leaving only google.*##[src*="consent"]:upward(5) fixes the warning to accept cookies in [https://www.google.es/] and google images but breaks for google results, loses the scroll bar, so I can not scroll. See the image
**https://i.ibb.co/Qn2X0mF/3.png**

**Any solution for this?**

Greetings again, good night and thank you very much.

Note: I put the images in URL because it did not let me drag the images into the text box, it did not load them.

**Comment by mapx-** [comment]
I have no idea what to do

**Comment by krystian3w** [comment]
Poland use:
```
www.google.*##body.QVCmK:style(position: static !important; overflow-y: visible !important;)
www.google.*##html.QVCmK:style(overflow-y: visible !important;)

www.google.*###lb > div[id^="_"] > div[class*=" "]:not([id]):empty:matches-css(opacity: 0.7)
www.google.*###lb > div[id^="_"] > div[class*=" "]:not([id]):empty:matches-css(opacity: 0.7):remove()

www.google.*###lb > div[id^="_"] > div[class*=" "]:not([id]):has( > span > div[role="dialog"] > #cnsw > iframe[src*="://consent.google.com"])
www.google.*###lb > div[id^="_"] > div[class*=" "]:not([id]):has( > span > div[role="dialog"] > #cnsw > iframe[src*="://consent.google.com"]):remove()
```

Remove also delete itself `.QVCmK`, so scroll works without CSS.

**Comment by Jose1971AB** [comment]
Hello @krystian3w good evening.

I'm a basic user and reading your answer I don't understand well what you mean, but I've added to the tab My filters the parameters you put and it resolves all the errors. The fact is that it worked.

**Is what I have done correct? put those parameters in the tab My filters?...** 

I hope that no more problems arise regarding the domain of google.

Greetings and good night.

**Note**: thank you for the collaboration of @mapx-

**Comment by krystian3w** [comment]
Well pasted.

The problem may begin when Google activates again that limit around 10 000 images per search result it will show olny around 30 on the screen (The very old version of the pop-up had such a limit/glitch, then you could not hide the pop-up with "CSS" on Google Images).
