### ISSUE TITLE
cookpad.com

### ISSUE THREAD

**Issue by P0Rtvine** [uBlockOrigin/uAssets#7923]
### URL(s) where the issue occurs

`https://cookpad.com/uk/recipes/13473549-spaghetti-della-nonna`

### Describe the issue

You can remove this and unlock the scroll?

### Screenshot(s)

![2020-09-17_192937](https://user-images.githubusercontent.com/57287308/93499931-4b8aa780-f91c-11ea-8e45-304e39aa9035.png)

### Versions

- Browser/version: Opera|Stable
- uBlock Origin version: 1.29.2

### Settings

![2020-09-17_193422](https://user-images.githubusercontent.com/57287308/93500464-d79ccf00-f91c-11ea-99f2-7f27e9cf7add.png)

**Comment by krystian3w** [comment]
Can you reproduce with unGoogledChromium:


OS | Page
-- | --
Windows 32-bit <br> https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/32bit | 84.0.4147.135-1 <br> https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/32bit/84.0.4147.135-1
Windows 64-bit <br> https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit | 84.0.4147.135-1 <br> https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/84.0.4147.135-1

**Comment by P0Rtvine** [comment]
@uBlock-user 
@krystian3w 

Refresh the page 5-10 times

**Comment by krystian3w** [comment]
OK:

`###modals`
`##.overflow-hidden:(overflow: auto !important;)`

---

@DandelionSprout  look, maybe possible kill by block `script` / `xhr`?

**Comment by DandelionSprout** [comment]
I've got at least some NanoMeow/Contrib stuff and a late dinner to take care of first.

**Comment by mapx-** [comment]
another fix
`cookpad.com##+js(cookie-remover, recipe_view_count_en)`

maybe for other languages to be modified (see what cookies are created)

**Comment by krystian3w** [comment]
Yep:

`recipe_view_count_es:2`

So maybe:

`cookpad.com##+js(cookie-remover, /recipe_view_count_/)` 

if valid

**Comment by mapx-** [comment]
yes


```
Parameters:
optional, string/regular expression, matching in the name of the cookie
```
