### ISSUE TITLE
golem.de breakage

### ISSUE THREAD

**Issue by spodermenpls** [uBlockOrigin/uAssets#7926]
### URL(s) where the issue occurs
`https://www.golem.de/sonstiges/zustimmung/auswahl.html?from=https%3A%2F%2Fwww.golem.de%2F`

### Describe the issue
One (or more) rule of the "uBlock filters" list prevents the user from successfully clicking the "Accept" button on the faux-paywall window that pops up when one enters the site, only deactivating "uBlock filters" allows it to work.
 

### Versions

- Browser/version: Firefox 80.0.1 64-bit
- uBlock Origin version: 1.29.2

**Comment by mapx-** [comment]
`Zustimmen` button is working fine using the uBO default setup. What other lists are you using ?

**Comment by spodermenpls** [comment]
I have no clue what may have changed on the site, with my browser or "uBlock filters", the "accept" button and redirect works again now, even with the heavy modifications by uBlock to that window (hence a bit longer button load time compared to the native "stack"). I was hesitant with reporting this issue at first, but I had troubles passing that window for weeks now (not just today), whenever I wanted to read an article on that site, since the site's cookies get deleted on my setup after exit. Thanks anyway!

**Comment by okiehsch** [comment]
>  (hence a bit longer button load time compared to the native "stack")

That I can reproduce..
`golem.de#@#+js(abort-on-property-write, _sp_)`
fixes it. I will comment it out for now.

**Comment by spodermenpls** [comment]
I've seen now that this issue was actually unrelated to "uBlock filters", Adguard Annoyances and Easylist Cookie whitelisted 1-2 days ago the "setconsentcookie.php", which only appears in the logger after clicking the button, which I overlooked. At least I'll know how to pin-point such issues more precisely next time. 😄
