### ISSUE TITLE
La-croix.com detecting uBO and generating a paywall

### ISSUE THREAD

**Issue by Dark-Yox** [uBlockOrigin/uAssets#7927]
### URL(s) where the issue occurs

Any article from `https://www.la-croix.com` like 

`https://www.la-croix.com/Sciences-et-ethique/Covid-19-difficile-hierarchisation-tests-2020-09-19-1201114865`

### Describe the issue

The website detect uBlock Origin and generate a paywall telling you that the article is only for subscribed users but it's a lie you can actually read any article for free if you don't have an adblocker or if you disable JavaScript.

### Screenshot(s)

(With and without first party scripts)
![image](https://user-images.githubusercontent.com/45209462/93662566-63b80f00-fa61-11ea-9236-b591e6bef3c2.png)

### Versions

- Browser/version: Chrome 87.0.4263.3
- uBlock Origin version: 1.29.2

### Settings

Default + FRA: AdGuard Français 

### Notes

This is a contribution and here's the JavaScript file generating the paywall that should be blocked

`pw.la-croix.com/pw/index.min.js`

**Comment by uBlock-user** [comment]
No detection, I get paywall even after I disabled uBO and cleared all site data.

> Circumventing a paywall is considered out of scope.
