### ISSUE TITLE
focus.de breakage

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#7928]
### URL(s) where the issue occurs

`https://www.focus.de/finanzen/banken/konto-angeblich-deaktiviert-verbraucherzentrale-warnt-fiese-betrugsmasche-mit-phishing-mails_id_10083669.html`

### Describe the issue

I can’t play the video because `privacy-mgmt.com` is blocked

### Versions

- Browser/version: Firefox 80.0.1
- uBlock Origin version: v1.29.2

### Settings

default + uBlock Annoyances

**Comment by krystian3w** [comment]
ekstrabladet.dk
manager-magazin.de
spiegel.de
vtm.be

maybe have similar breakage

**Comment by JobcenterTycoon** [comment]
manager-magazin.de and spiegel.de works fine for me

**Comment by okiehsch** [comment]
`ekstrabladet.dk` works fine with the regional list enabled.

**Comment by okiehsch** [comment]
`vtm.be`needs an account to watch full lenght videos, so rather hard to test.
Short videos work fine on my end.
`https://vtm.be/jonge-wolven/alexander-woont-in-co-living-space-tijdens-scheiding`

**Comment by krystian3w** [comment]
xhr and subdocument accepted by EL: https://github.com/easylist/easylist/commit/357ed127a1614f0cf5b6e791115828dc3b714f6f

**Comment by krystian3w** [comment]
@lain566 / @okiehsch / @mapx-:

https://old.reddit.com/r/uBlockOrigin/comments/jjryfp/a_defuser_scriptlet_breaks_livestream_on_spiegelde/

**Comment by krystian3w** [comment]
@kiboke you break GDPR on: 

origin url:

`https://www.spiegel.de/politik/deutschland/angela-merkel-zu-den-ergebnissen-des-corona-gipfels-livestream-a-73ab26a5-ceb9-4a07-812d-e796e703102e`

after redirect:

`https://www.spiegel.de/consent-a-?targetUrl=https%3A%2F%2Fwww.spiegel.de%2Fpolitik%2Fdeutschland%2Fangela-merkel-zu-den-ergebnissen-des-corona-gipfels-livestream-a-73ab26a5-ceb9-4a07-812d-e796e703102e&ref=https%3A%2F%2Fold.reddit.com%2Fr%2FuBlockOrigin%2Fcomments%2Fjjryfp%2Fa_defuser_scriptlet_breaks_livestream_on_spiegelde%2F`

I can't see manuall click button to accept:

![Screenshot_2020-10-29 DER SPIEGEL Online-Nachrichten](https://user-images.githubusercontent.com/35370833/97537409-0ea3dd00-19bf-11eb-9823-bc8198ca9929.png) |
--- |
gone from left column |

**Comment by kiboke** [comment]
@krystian3w I checked it and I see the red button as it should be. Do you have the latest IDCAC filter list version?

**Comment by krystian3w** [comment]
` ! Version: 324.202010280920`
`! Last modified: 28 Oct 2020 08:20 UTC`

On firefox only help:

`@@||privacy-mgmt.com^$script,domain=privacy-mgmt.com`

Strange why this is first party request/resource.

**Comment by krystian3w** [comment]
PS.  Cloudflare ☁️ again fail with your domains.

**Comment by kiboke** [comment]
Don't block privacy-mgmt.com on focus.de, videos will stop working.

**Comment by krystian3w** [comment]
But I am talking about `spiegel.de` - this page uses strange `3,1` "privacy-mgmt.com" conection (masked as first party request/resource).

**Comment by kiboke** [comment]
Ah yeah, sorry. I have no understanding of that "3,1 connection" thing. I can only say it works perfectly on my side.

**Comment by krystian3w** [comment]
uBO `jargon`:

![Przechwytywanie](https://user-images.githubusercontent.com/35370833/97542483-1798ac80-19c7-11eb-994e-e518dd61f68e.JPG)

IMO I see to possible fix this bug:

add `|~privacy-mgmt.com`
```
privacy-mgmt.com$domain=~bild.de|~ekstrabladet.dk|~computerbild.de|~welt.de|~focus.de|~chip.de|~faz.net|~n-tv.de|~manager-magazin.de|~spiegel.de|~vtm.be|~selbst.de|~giga.de|~radio.fr|~radio.at|~radio.de|~radio.net|~radio.pl|~radio.it|~mein-schoener-garten.de|~privacy-mgmt.com
```

or

add `third-party`
```
privacy-mgmt.com$third-party,domain=~bild.de|~ekstrabladet.dk|~computerbild.de|~welt.de|~focus.de|~chip.de|~faz.net|~n-tv.de|~manager-magazin.de|~spiegel.de|~vtm.be|~selbst.de|~giga.de|~radio.fr|~radio.at|~radio.de|~radio.net|~radio.pl|~radio.it|~mein-schoener-garten.de
```

**Comment by kiboke** [comment]
I just updated the list. Please check if everything's ok now.

**Comment by krystian3w** [comment]
Now is better, buttons back.
