### ISSUE TITLE
receivesms.co

### ISSUE THREAD

**Issue by bandi88** [uBlockOrigin/uAssets#7929]
### URL(s) where the issue occurs

`https://www.receivesms.co/`

### Describe the issue

This website does not allow ad-blockers.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/23141180/93671422-2a07f800-faa3-11ea-860b-e4bb30d76716.png)

### Versions

- Browser/version: Google Chrome 85.0.4183.83
- uBlock Origin version: 1.29.2

### Settings

Used with Nano Defender together.

**Comment by uBlock-user** [comment]
Test on default settings and will all other extensions disabled.

**Comment by bandi88** [comment]
> Test on default settings and with all other extensions disabled.

The results are the same. As long as uBlock Origin is on, the message appears. After I disable UBP, the message gone. So it detects UBP, which is bad. :(

**Comment by uBlock-user** [comment]
I can't reproduce this on default settings unless I disable redirection filters from the default lists, you have to investigate what changes you made on your end.

**Comment by DavidGH** [comment]
bad filter */fuckadblock.$script,redirect=fuckadblock.js-3.2.0
fix filter */fuckadblock.$script,redirect=fuckadblock.js-3.2.0,badfilter
or apply my rules
! fuckadblock.sitexw.fr;Valentin Allaire;p:https://github.com/sitexw/BlockAdBlock/
!fix  /fuckadblock.$script [uBf]
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js
@@||cdn.jsdelivr.net/npm/fuckadblock@3.2.1/fuckadblock.min.js
@@/js/blockadblock.js$domain=bitporno.com|bitporno.sx
*/fuckadblock.$script,redirect=fuckadblock.js-3.2.0,badfilter

**Comment by DavidGH** [comment]
Why spam?
