### ISSUE TITLE
Amazon

### ISSUE THREAD

**Issue by Coder-256** [uBlockOrigin/uAssets#793]
### URL(s) where the issue occurs

- `https://www.amazon.com/gp/cart/view.html`
- `https://www.amazon.com/Chinet-Dinner-Plate-100-count-Box/dp/B002YD8GBG`
- `https://www.amazon.com/AmazonBasics-360-Piece-Clear-Plastic-Cutlery/dp/B010RLC7P2`

These filters also block the `smile.amazon.com` variants.

### Describe the issue

Many ads for other products Amazon are not blocked. This is because they only appear on Amazon, and use Amazon's own marketing system.

### Screenshot(s)

> ![Amazon 1](https://user-images.githubusercontent.com/10134823/32137394-de1e1ab6-bbec-11e7-8ee4-324360638935.png)
> ![Amazon 2](https://user-images.githubusercontent.com/10134823/32137395-de2bd714-bbec-11e7-8087-c49d3ad2c11f.png)
> ![Amazon 3](https://user-images.githubusercontent.com/10134823/32137396-de3af096-bbec-11e7-8641-0bfa3fb3f7a4.png)
> ![Amazon 4](https://user-images.githubusercontent.com/10134823/32137397-de490f0a-bbec-11e7-8186-31834d00e5a9.png)
> ![Amazon 5](https://user-images.githubusercontent.com/10134823/32137398-de56eb34-bbec-11e7-88f3-0a09749a5841.png)

### Versions

- Browser/version: Google Chrome Version 63.0.3239.18 (Official Build) beta (64-bit)
- uBlock Origin version: 1.14.12

### Settings

No settings changed.

### Notes

Here is the filter list I made:
```
! Top banner
amazon.com###nav-upnav
! Ads in cart
amazon.com###sc-new-upsell
! Ads around products
amazon.com###detail-ilm_div
amazon.com###productAlert_feature_div
amazon.com###hqpWrapper
amazon.com###hqp
amazon.com###amsDetailRight_feature_div
! Sponsored products
amazon.com###sponsoredProducts_feature_div
amazon.com###sponsoredProducts2_feature_div
! Featured videos (ads)
amazon.com###va-related-videos-widget_feature_div
! Ads (should already be blocked, but this fixes the gap)
amazon.com###dp-ads-center-promo_feature_div
```
Note that it only includes products that are advertised, not ones that are recommended for the user (because those can often be useful). Also not included are unintrusive text-only promotions that also could be useful.

**Comment by mapx-** [comment]
@ryanbr

**Comment by Coder-256** [comment]
Why is this closed?

**Comment by mapx-** [comment]
All the filters above are normal filters you should report to easylist maintainers
https://github.com/ryanbr/fanboy-adblock/issues
https://github.com/easylist/easylist/issues
@Khrin @monzta @ryanbr
