### ISSUE TITLE
nsfw Video player does not load when ubo is enabled on https://bdsmstreak.com

### ISSUE THREAD

**Issue by tmm22** [uBlockOrigin/uAssets#7934]
### Description

When ubo is enabled , the website video player of `https://bdsmstreak.com` the video player does not load

### A specific URL where the issue occurs 
`https://bdsmstreak.com/video/62319/evil-stepmother-vs-horny-bitch` 

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Enable the extension attempt to play video
2. The video will not load and gives an error code, stating that the video player could not load

### Expected behavior:

I expect the video player to load and the selected content

### Actual behavior:

[What actually happened]
the video player gives an error code and states that it cannot load
### Your environment

* uBlock Origin version: uBlock Origin v1.29.2
* Browser Name and version: Google Chrome 
Version 85.0.4183.102 (Official Build) (64-bit)
* Operating System and version:Windows 10 1904

**Comment by mapx-** [comment]
@ryanbr
