### ISSUE TITLE
pagalworld4u.com { Antiadblock }

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#7937]
### URL(s) where the issue occurs

`http://pagalworld4u.com/`

### Describe the issue

Antiadblock 

### Versions

- Browser/version: firefox 80
- uBlock Origin version: 1.29.2

### Settings

 uBO's default settings
-

**Comment by ghajini** [comment]
@mapx- 

##Test environment = firefox android, firefox desktop, opera browser

1.

all sites (100) listed here `http://wapkiz.com/?site=top`  including above original reported in this thread have ads....these are built by `wapkiz.com` 

Here are the filters tested using element picker and logger

`||prownl.com^`
`||prayuserparka.com^`
`##[href^="http://ad.jetx.info/"]`
`kizservice.info###sam`
`##[href^="http://cadsecs.com/"]`
`##[href^="//clk.afftracks.online/"]`
`||afftracks.online^`
`||adzfun.info^
`##[href^="https://prayuserparka.com/"]`
`##[href^="https://wap4dollar.com/ad/nonadult/serve.php"]`
`||adfoz.com^`
`##[href^="http://wap4dollar.com/refer.php"]`
`##[href^="http://wap4dollar.com/ad/nonadult/serve.php"]`
`##[href^="http://ad.jetx.info/red2.php"]`
`##[href^="https://ad.jetx.info/red2.php"]`
`##[href^="http://raboninco.com/"]`




{ these are easylist compatible filters(but i don't when they will test on mobile platform and  add these to easylist ,hence reporting here) }

**Comment by mapx-** [comment]
I notified Ryan and Alex-302 (AdGuard Mobile Ads) , let's see if they add the filters above

**Comment by ghajini** [comment]
Sure👍

**Comment by Alex-302** [comment]
Added some rules.
@ghajini please check with AdGuard Mobile filter after 30-60 minutes.

**Comment by ghajini** [comment]
@Alex-302 @ryanbr 

I tested all sites in `http://wapkiz.com/?site=top` and even gone to their download sites......some filters are still missing which hides fake download  buttons, ads etc....

If you have time to visit such 100 sites then fine...

I mentioned such filters in 
`https://github.com/uBlockOrigin/uAssets/issues/7937#issuecomment-697643354`

hope you add them

**Comment by Alex-302** [comment]
@ghajini better provide the list of all that sites.

**Comment by mapx-** [comment]
> @ghajini better provide the list of all that sites.

that posted above ?
`http://wapkiz.com/?site=top`

**Comment by ghajini** [comment]
Rules not added yet

**Comment by uBlock-user** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/dc000bafa42cd4a67c4fe2db9dbe914caee492ba
https://github.com/easylist/easylist/commit/4b668bcc09658534cf8a6e981245041924c3c5d8

**Comment by ghajini** [comment]
Yes I have seen those commits,

All filters are not added yet

**Comment by uBlock-user** [comment]
Which ones not added ?

**Comment by ghajini** [comment]
those filters https://github.com/uBlockOrigin/uAssets/issues/7937#issuecomment-697643354

`||prownl.com^`
`||prayuserparka.com^`
`kizservice.info###sam`
`##[href^="//cadsecs.com/"]`
`##[href^="//clk.afftracks.online/"]`
`||afftracks.online^`
`##[href^="//prayuserparka.com/"]`
`##[href^="https://wap4dollar.com/ad/nonadult/serve.php"]`
`||adfoz.com^`
`##[href^="//ad.jetx.info/"]`

**Comment by mapx-** [comment]
added
