### ISSUE TITLE
A single Spotify podcast does not function with uBlock Origin enabled

### ISSUE THREAD

**Issue by jthistle** [uBlockOrigin/uAssets#7938]
### URL(s) where the issue occurs

`https://open.spotify.com/show/7BTOsF2boKmlYr76BelijW`

### Describe the issue

 

A certain podcast, _Gemischtes Hack_, does not play on Spotify when uBlock origin with the default filter lists is enabled. This is true for any episode. All other podcasts and music seem to be fine.

As usual with Spotify, the ads pop up for a fraction of a second, followed by the podcast. But then, the podcast doesn't play and behaves like the ads, in that it disappears after a fraction of a second to be replaced by more ads. 

### Screenshot(s)

Here's an example of the logs from after pressing 'play':

![Screenshot from 2020-09-22 16-01-13](https://user-images.githubusercontent.com/8274049/93900170-fae4c700-fcec-11ea-9d3b-3d34737bad98.png)

Note the redirect for the ad audio to `noopmp3-0.1s`.

### Versions

- Browser/version: Firefox 80.0.1
- uBlock Origin version: 1.29.1

### Settings

- [my filter list can be found here](https://gist.github.com/jthistle/5ad1eb41b79d694b53a855000a9ac806)
  - note that there is only a single, cosmetic rule for Spotify
- all other settings are defaults, apart from advanced mode being enabled

### Notes

I looked through the logger with music (which works) and compared it to this podcast. I could honestly not find anything significantly different in the logs. I will keep looking and update this issue if I find anything.

**Comment by uBlock-user** [comment]
Does it work if you add `@@||megaphone.cloud^$cname` ?

**Comment by jthistle** [comment]
Unfortunately not; the issue persists.

**Comment by mapx-** [comment]
this should work

`@@||open.spotify.com^$cname`

**Comment by jthistle** [comment]
Thank you so much! This fixes the issue. Can this be added to the default filter list to help other people coming across this problem? Thanks.
