### ISSUE TITLE
[NSFW] milftoon.site anti-adblock

### ISSUE THREAD

**Issue by cantunborn** [uBlockOrigin/uAssets#7940]
### URL(s) where the issue occurs

`https://milftoon.site/`

### Describe the issue

Anti-adblock warning after 5-10 seconds of staying on homepage. 

### Versions

- Browser/version: Chrome 85.0.4183.121
- uBlock Origin version: uBlock Origin 1.29.2

### Settings

Default uBlock Origin lists + AdGuard Base + AdGuard Tracking Protection + Fanboy’s Enhanced Tracking List + Spam404 + AdGuard Annoyances + Fanboy’s Annoyance + uBlock filters – Annoyances + Nano Defender Integration + Nano Filters

### Notes

Suggested filter: `milftoon.site##+js(nobab)`

**Comment by uBlock-user** [comment]
Test on default settings/filterlists.

**Comment by cantunborn** [comment]
Able to reproduce with default lists. Please check after 5-10 seconds, warning does not appear immediately.

**Comment by uBlock-user** [comment]
Did you also disable all other extensions except uBO ?

**Comment by cantunborn** [comment]
Yes.

**Comment by uBlock-user** [comment]
Bait elements were recently removed from EasyList, force update EasyList if you haven't. To reproduce I had to add `###banner_ad`.

**Comment by cantunborn** [comment]
Ok, I'll do that.
