### ISSUE TITLE
Donation ads on Wikipedia won't go away even after blocking several times

### ISSUE THREAD

**Issue by HyperLemons** [uBlockOrigin/uAssets#7942]
### URL(s) where the issue occurs

[(https://en.wikipedia.org/wiki/Xbox_360)] is good example, if it shows up that is.

### Describe the issue

Donation ads on Wikipedia won't go away even after blocking several times, possibly changing ad url/manifest each time?

### Screenshot(s)

[https://i.imgur.com/AJDw4LN.png, https://i.imgur.com/YwgbqFX.png]

### Versions

- Browser/version: [Firefox Nightly Version 82.0a1 (2020-9-19) (64-bit)]
- uBlock Origin version: [v1.29.2]

### Settings

A bunch of filters of a few sites, Added NanoFilters, Advanced Settings userResourcesLocation replaced with NanoFilters

### Notes

I have no idea why they won't go away.

**Comment by mapx-** [comment]
it's about donations, no ad

**Comment by uBlock-user** [comment]
Subscribe to Fanboy/AdGuard annoyances list.

**Comment by krystian3w** [comment]
or use 🎊 glittered 🎆:

wiki wand `https://www.wikiwand.com/Xbox_360`

**Comment by JaneSmith** [comment]
Shouldn't this be included in uBlock Origin's own annoyances list? Wikipedia is a very common website, and this is therefore a very common annoyance. It doesn't need to be an ad to be an annoyance.

**Comment by uBlock-user** [comment]
because it doesn't require uBO's extended syntax.
