### ISSUE TITLE
kpopstan.com [anti-adb]

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#7945]
### URL(s) where the issue occurs

`https://kpopstan.com/gotothedl.html?url=aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvZmZoaTJ6OTBodXB0ZWg2Lw==`

`https://kpopstan.com/gotothedl.html?url=aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvbnZyMjZlcDRqbGxzeGxxL1h5ZG8rLStLSURVTFRIT09EKy0tLS1lc2NhcGVfc2VtX2F1dG9saW5rX3VyaTo0MjMwOTU1NzFmN2E1ZGY1ZjFkOWVkYjQ3MDBhYjk4Zi0tLS0uN3ovZmlsZQ==`

### Describe the issue

anti adblock

### Versions

- Browser/version: [FF 81.0 x64]
- uBlock Origin version: [1.29.2]

### Settings

`https://pastebin.com/raw/y5a17vkr`

**Comment by krystian3w** [comment]
```
http://www.mediafire.com/file/ffhi2z90hupteh6/UP10TION_-_Light_UP_%255Bkpopstan.com%255D.7z/file
http://www.mediafire.com/file/nvr26ep4jllsxlq/Xydo+-+KIDULTHOOD+----escape_sem_autolink_uri:423095571f7a5df5f1d9edb4700ab98f----.7z/file
```

**Comment by exodius48** [comment]
Fixed by reset to default setting .
