### ISSUE TITLE
Bad filter: /banners/160

### ISSUE THREAD

**Issue by StephenLynx** [uBlockOrigin/uAssets#7946]
I don't know where this filter comes from, but it's giving false positives.

https://i.imgur.com/n6zBqbc.png

**Comment by StephenLynx** [comment]
Thanks, but this only targets one site. A few dozen sites (so far) use my software and all fall into the exact same issue. @uBlock-user

**Comment by uBlock-user** [comment]
Report them all and next fill in the templace along with the correct place.

**Comment by gorhill** [comment]
> A few dozen sites (so far) use my software

Are they variations of `8chan.moe`, such as `8chan.[tld]`?

**Comment by StephenLynx** [comment]
> Are they variations of `8chan.moe`, such as `8chan.[tld]`?

No. They are sites like bunkerchan.xyz, endchan.xyz, onee.ch and several others belonging to several different people.

**Comment by gorhill** [comment]
@uBlock-user 

I think we should badfilter `/banners/160`. The issue I see here is that at this point, JS timestamp has moved to the realm of 160..., so having a filter which ends with `/160` has become an issue, higher chance that filters open-ending with `160` will be false positive given that JS timestamp is often used for uploaded resources.

**Comment by StephenLynx** [comment]
By the way, don't forget there are other similar filters, like /banners/300, I found it on easy-list.
https://easylist.to/easylist/easylist.txt

**Comment by uBlock-user** [comment]
Do these other sites also have the same false positives created via `/banners/160` ?

**Comment by gorhill** [comment]
> like `/banners/300`

That one is less likely to cause false positive, so it will stay unless it is demonstrated that it causes widespread issue. The issue with `/banners/160` is that JS timestamps at this point all starts with `160`.

**Comment by StephenLynx** [comment]
Yes, they all have the EXACT same false positives. The number after the /banners/ are generated through mongodb _id generation. And if I'm not mistaken, the first part of the _id is generated through a timestamp.

**Comment by mapx-** [comment]
maybe these too ?

```
/banners/300
/banners/460
/banners/468
/banners/728
```

**Comment by StephenLynx** [comment]
easy-list removed the filter, so you can remove the exception now.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0ee6fca139061de5f6474edce6c8d376e95ddeae
