### ISSUE TITLE
vipleague.se

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#795]
### URL(s) where the issue occurs

`https://www.vipleague.se/`
`http://www.vipleague.se/motorsports/175778/5/nascar-racehub--stream.html`

### Describe the issue

Popups when clicking around.
Fake stream in HD links.
Some (already) blocked ad overlays on the video.
(I couldn't get any videos to play regardless)

**Comment by okiehsch** [comment]
`vipleague.se` leads to `vipleague.me` and the filters already present in `uBO-filters` prevent all popups on my end.
I also tried some random streams which played fine.
For the fake stream: `vipleague.me##a[href^="http://streamsign.me/"]`

**Comment by terrorist96** [comment]
> `vipleague.se` leads to `vipleague.me`

The `.se` doesn't redirect to `.me` for me. The `.me` actually redirects to `.se`. Maybe the redirect is dependant on your location.

**Comment by SMed79** [comment]
> Maybe the redirect is dependent on your location.

Here, the `.se`, `.me`, `.ch`, `.co`, `.sx`, `.is` and `.tv` redirect me to `vipleague.ws`.

**Comment by KiLL4FuNK** [comment]
`https://es.vipleague.pw/sports/football.html`

Pop-up

**Comment by mapx-** [comment]
`Unable to connect`

**Comment by terrorist96** [comment]
Try `.cc` domain

**Comment by terrorist96** [comment]
![image](https://user-images.githubusercontent.com/12802056/40151493-567e3dde-594e-11e8-85b6-e8d5ebe6ca9f.png)
This is a fake button and should be blocked.

**Comment by okiehsch** [comment]
I can reproduce the fake button, I can't reproduce any popup.

**Comment by terrorist96** [comment]
Yeah, no pop ups for me either.
