### ISSUE TITLE
CNEWS video not loading

### ISSUE THREAD

**Issue by Skip75** [uBlockOrigin/uAssets#7952]
### URL(s) where the issue occurs
`
https://www.cnews.fr/le-direct`

### Describe the issue

Video do not load. Need to disable uBlock to be able to see the content.

### Screenshot(s)

When enabled :
![image](https://user-images.githubusercontent.com/44243520/94273465-beaba380-ff44-11ea-9a5a-9d99fde051ad.png)

When disabled :
![image](https://user-images.githubusercontent.com/44243520/94273511-d08d4680-ff44-11ea-8bfa-cd13c37ed55a.png)

### Versions

- Browser/version: Firefox latest version
- uBlock Origin version: uBlock Origin v1.29.2

### Settings

No custom settings
tested on 2 different workstations

### Notes

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +0 |  |  | `www.cnews.fr` | 1 | image | `https://static.cnews.fr/sites/default/files/styles/image_298_93/public/capture_decran_2020-09-23_a_19.57.05_5f6b8c94aef23_0.png?itok=ZtWxEC-j` |
| +0 |  |  | `www.cnews.fr` | 1 | image | `https://static.cnews.fr/sites/default/files/styles/image_298_93/public/matthew-henry-n5vuec86zg8-unsplash_5f68f08bcdda5.jpg?itok=DFuHuaho` |
| +0 |  |  | `www.cnews.fr` | 1 | image | `https://static.cnews.fr/sites/default/files/styles/image_298_93/public/andrew-welch-i5crg4klbly-unsplash_5f6b547fb5365.jpg?itok=BUBUm1ik` |
| +0 |  |  | `www.cnews.fr` | 1 | image | `https://static.cnews.fr/sites/default/files/styles/image_298_93/public/capture_du2019ecran_2020-09-24_a_11.50.38_5f6c6c1b741b3_0.jpg?itok=DfRuUCTm` |
| +0 |  |  | `www.cnews.fr` | 1 | image | `https://static.cnews.fr/sites/default/files/styles/image_298_93/public/stantec_5f6c6910d8d64.jpg?itok=geOYa6c0` |
| +0 | \|\|js-agent.newrelic.com^ | -- | `www.cnews.fr` | 3 | script | `https://js-agent.newrelic.com/nr-1177.min.js` |
| +0 |  |  | `www.cnews.fr` | 1 | xhr | `https://www.cnews.fr/ajaxblocks?blocks=dm_hpm-header_alert_band/dm_menuburger-dm_menuburger/dm_letop-dm_letop_block` |
| +0 |  |  | `www.cnews.fr` | 1 | image | `https://static.cnews.fr/sites/default/files/styles/image_142_80/public/000_8qp6j6-min_5f6dd74d16c69.jpg?itok=uiwMo2_A` |
| +0 |  |  | `www.cnews.fr` | 1 | image | `https://static.cnews.fr/sites/default/files/styles/image_142_80/public/sex-education_5f6dcf3c3a019_0.jpg?itok=HxW3Gym1` |
| +0 |  |  | `www.cnews.fr` | 1 | image | `https://static.cnews.fr/sites/default/files/styles/image_142_80/public/fridge_5f6de31e58c3b_0.jpg?itok=QRw0geWm` |
| +0 |  |  | `www.cnews.fr` | 1 | image | `https://static.cnews.fr/sites/default/files/styles/image_142_80/public/ch_5f6de67bb7ec0.jpg?itok=MvkMkdYJ` |
| +0 |  |  | `www.cnews.fr` | 1 | image | `https://static.cnews.fr/sites/default/files/styles/image_142_80/public/ch2_5f6dec40b412b.jpg?itok=CbpsfIoh` |
| +0 | \|\|quantcast.mgr.consensu.org^*/cmp2.js | -- | `www.cnews.fr` | 3 | script | `https://quantcast.mgr.consensu.org/tcfv2/cmp2.js` |
| +0 | \|\|quantserve.com^ | -- | `www.cnews.fr` | 3 | image | `https://pixel.quantserve.com/pixel/p-kVj8ZGLNxHTBW.gif` |
| +0 | \|\|quantserve.com^ | -- | `www.cnews.fr` | 3 | script | `https://secure.quantserve.com/quant.js` |
| +0 | @@\|\|ced.sascdn.com/tag/*/smart.js$domain=cnews.fr | ++ | `www.cnews.fr` | 3 | script | `https://ced.sascdn.com/tag/2653/smart.js` |
| +0 |  |  | `www.cnews.fr` | 1 | script | `https://www.cnews.fr/sites/default/files/advagg_js/js__v9daFFJyjal8y61WSPYocmqjP3mGx0jVvNZTAkSgmY8__SoAWRHqBqXOBMXfFQNHZo2bRe5zyRkXLOIXPf4RdrwY__XGjoKAeLwtV_vhCXTa61mI7tYnQcVuMOGZVHbNTe8Wc.js` |
| +0 | \|\|audience.acpm.fr^ | -- | `www.cnews.fr` | 3 | script | `https://tag.audience.acpm.fr/js/on-1.0.min.js` |
| +0 | \|\|estat.com^ | -- | `www.cnews.fr` | 3 | script | `https://w.estat.com/js/whap.js` |
| +0 | google-analytics.com/ga.js | << | `www.cnews.fr` |  | script | `https://ssl.google-analytics.com/ga.js` |
| +0 | \|\|google-analytics.com^ | -- | `www.cnews.fr` | 3 | script | `https://ssl.google-analytics.com/ga.js` |
| +0 |  |  | `www.cnews.fr` | 3 | script | `https://quantcast.mgr.consensu.org/choice/kVj8ZGLNxHTBW/www.cnews.fr/choice.js` |
| +0 |  |  | `www.cnews.fr` | 1 | image | `https://static.cnews.fr/sites/default/files/cnews-favicon_5f170ef448901.ico` |
| +0 |  |  | `www.cnews.fr` | 1 | image | `https://www.cnews.fr/sites/all/themes/directmatinv4/apple-touch-icon-144x144.png` |
| +0 |  |  | `www.cnews.fr` | 1 | image | `https://static.cnews.fr/sites/default/files/styles/image_60_70/public/philippe-labro.png?itok=hfediDT6` |
| +0 |  |  | `www.cnews.fr` | 1 | image | `https://static.cnews.fr/sites/default/files/directmatin/image_placeholder_rect_basic.gif` |
| +0 |  |  | `www.cnews.fr` | 1 | image | `https://static.cnews.fr/sites/all/themes/directmatinv4/cnews-logo.png` |
| +0 |  |  | `www.cnews.fr` | 3 | script | `https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js` |
| +0 |  |  | `www.cnews.fr` | 1 | doc | `https://www.cnews.fr/le-direct` |
</details>

**Comment by mapx-** [comment]
`@@||quantcast.mgr.consensu.org/tcfv2/cmp2.js$script,domain=cnews.fr`

@ryanbr
