### ISSUE TITLE
youtube.com message footer under video

### ISSUE THREAD

**Issue by leodoi3** [uBlockOrigin/uAssets#7954]
### URL(s) where the issue occurs

`https://www.youtube.com/watch?v=E3j8q5m9E5c`

### Describe the issue

Shows ad/ footer message under the video

### Screenshot(s)

![image](https://user-images.githubusercontent.com/46114199/94314553-92d4f180-ff35-11ea-9461-faf418d0a020.png)

### Versions

- Browser/version: Firefox 81.0
- uBlock Origin version: 1.29.2

### Settings

-Adguard Annoyances
-Anti-Facebook
-Fanboys annoyances
-uBlock annoyances

**Comment by uBlock-user** [comment]
Add `youtube.com###clarify-box` to my Filters or report this to Fanboy/ AdGuard Annoyances tracker.
