### ISSUE TITLE
bloomberg.com

### ISSUE THREAD

**Issue by P0Rtvine** [uBlockOrigin/uAssets#7956]
### URL(s) where the issue occurs

`https://www.bloomberg.com/news/articles/2020-09-24/winklevoss-twins-crypto-exchange-is-expanding-into-the-u-k?srnd=technology-vp`

### Describe the issue

Subscribe for unlimited access to Bloomberg.
Refresh the page 5-10 times.

### Screenshot(s)

![2020-09-26_163324](https://user-images.githubusercontent.com/57287308/94343000-c8eda080-001d-11eb-8fae-25da1c1bb313.png)
![2020-09-26_163302](https://user-images.githubusercontent.com/57287308/94343004-cdb25480-001d-11eb-8620-c8280b4ed246.png)

### Versions

- Browser/version: Opera|Stable
- uBlock Origin version: 1.30.0

### Settings

![image](https://user-images.githubusercontent.com/57287308/94343024-f4708b00-001d-11eb-9423-bd18b6aaba38.png)

**Comment by uBlock-user** [comment]
```
bloomberg.com##body:style(overflow:auto !important)
bloomberg.com##+js(nosiif, clearInterval, 10)
```

**Comment by P0Rtvine** [comment]
@uBlock-user 
doesn't work for me
![2020-09-26_163302](https://user-images.githubusercontent.com/57287308/94343335-0f43ff00-0020-11eb-8890-a7dfa415587d.png)

**Comment by uBlock-user** [comment]
Are you on default settings/filterlists ?

**Comment by P0Rtvine** [comment]
Yep,
![image](https://user-images.githubusercontent.com/57287308/94343413-ac069c80-0020-11eb-8617-a8aa6e59f7ba.png)
not help

**Comment by uBlock-user** [comment]
try with 

```
bloomberg.com###graphics-paywall-overlay
bloomberg.com##body:style(overflow:auto !important)
```

**Comment by P0Rtvine** [comment]
Yes, it works, can block the iframe itself?
`||www.bloomberg.com/subscription-offer$subdocument`

**Comment by P0Rtvine** [comment]
@uBlock-user 
Add too 
`bloomberg.com###graphics-paywall-overlay
bloomberg.com##body:style(overflow:auto !important)`

**Comment by uBlock-user** [comment]
Doesn't that work alone ?

**Comment by P0Rtvine** [comment]
![2020-09-26_180255](https://user-images.githubusercontent.com/57287308/94343701-a14d0700-0022-11eb-8225-07e52cb0b3df.png)

**Comment by llacb47** [comment]
Paywalls are not in scope (?)

**Comment by uBlock-user** [comment]
okiehsch fixed it first as per https://github.com/orgs/uBlockOrigin/teams/ublock-filters-volunteers/discussions/239

**Comment by P0Rtvine** [comment]
@uBlock-user 
`https://www.bloomberg.com/news/articles/2020-09-24/amazon-amzn-bribery-scheme-could-be-tip-of-the-iceberg?srnd=premium-europe`

![2020-09-26_183610](https://user-images.githubusercontent.com/57287308/94344327-289c7980-0027-11eb-83e4-4ffd3b6bc773.png)

After updating filters.
Bring back the rule 
`bloomberg.com###paywall-banner`

There are two options for banners

**Comment by okiehsch** [comment]
> okiehsch fixed it first as per https://github.com/orgs/uBlockOrigin/teams/ublock-filters-volunteers/discussions/239


To be transparent I will post part of that discussion.

````
okiehsch
on Sep 25, 2019 • 
https://www.reddit.com/r/uBlockOrigin/comments/d8qeg8/bloomberg_detecting_incognito_mode/
https://www.bloomberg.com/opinion/articles/2019-09-24/don-t-steal-the-payrolls
@gorhill should we fix this issue or should we treat it as a paywall?
If you are a bloomberg subscriber you won't get the incognito wall.

Also if we add the fix

bloomberg.com##+js(raf-if, !paywall-inline-tout)
bloomberg.com###paywall-banner
bloomberg.com##.paywall-inline-tout
this will also break/circumvent their "limited numbers of articles for non subscribers" thing for users browsing the site in normal mode.

 @gorhill
gorhill on Sep 25, 2019
should we fix this issue or should we treat it as a paywall?

What's your opinion?

 @okiehsch
okiehsch on Sep 25, 2019 Author
Users can still use the site in normal mode, so it is only an annoyance in my opinion. I think fixing it in a list that is not enabled by default should be OK.

 @gorhill
gorhill on Sep 25, 2019
Agreed, I was leaning toward an annoyance since they are not asking users to disable their blocker. The real issue is that browsers allow sites to detect incognito mode so best would be for browsers to fix this on their side.
````

The issue I fixed was about a incognito wall and as a byproduct their paywall was also circumvented.
This issue is about the paywall and I can't see any incognito wall.
Fixing paywalls is out of scope, so I will remove the fix
