### ISSUE TITLE
latimes.com

### ISSUE THREAD

**Issue by P0Rtvine** [uBlockOrigin/uAssets#7957]
### URL(s) where the issue occurs
`https://www.latimes.com/politics/story/2020-09-26/with-amy-barrett-conservatives-get-the-supreme-court-champion-theyve-been-seeking`

### Describe the issue
Subscribe for unlimited access

### Screenshot(s)
![2020-09-26_180255](https://user-images.githubusercontent.com/57287308/94343930-6946c380-0024-11eb-9951-1deaa7c1abca.png)
![2020-09-26_181327](https://user-images.githubusercontent.com/57287308/94343931-6b108700-0024-11eb-97be-1183d218a74a.png)

### Versions

- Browser/version: Opera|Stable
- uBlock Origin version:  1.30.0

### Settings
![image](https://user-images.githubusercontent.com/57287308/94343949-8b404600-0024-11eb-8df2-c3bd081dbaa7.png)

**Comment by okiehsch** [comment]
Out of scope declined.

**Comment by cantunborn** [comment]
Try `||metering.platform.latimes.com/v*/meter?$xhr,domain=www.latimes.com`

**Comment by llacb47** [comment]
Add 

```
||californiatimes.com^*/Bootstrap.js$script
||californiatimes.com/meter/$script
||californiatimes.com/meteringjs/$script
```
