### ISSUE TITLE
Google Chrome 84.0.4147.135

### ISSUE THREAD

**Issue by Zed36512** [uBlockOrigin/uAssets#7959]
Google Chrome 84.0.4147.135
uBlock Origin 1.29.0 
default + RU AdList

Rules: `112.ua,4mama.ua,autoua.net,avtovod.com.ua,buhgalter.com.ua,businessua.com,censor.net.ua,dengi.ua,ditey.com,eknigi.org,enovosty.com,epravda.com.ua,eurointegration.com.ua,facenews.ua,football-ukraine.com,football24.ua,footballtransfer.com.ua,gagadget.com,gismeteo.ua,glavcom.ua,gorod.dp.ua,hvylya.net,i.ua,inforesist.org,internetua.com,isport.ua,kolobok.ua,kp.ua,kriminal.tv,lifedon.com.ua,liga.net,mama.ua,mport.ua,nashamama.com,newsyou.info,nnovosti.info,obyava.ua,okino.ua,ostro.org,~passport.i.ua,pogoda.meta.ua,pravda.com.ua,real-vin.com,ringside24.com,segodnya.ua,sinoptik.ua,smak.ua,socportal.info,strana.ua,stravy.net,telegraf.com.ua,tochka.net,tv.ua,tvgid.ua,udoktora.net,vesti.ua,vsetv.com,www.bigmir.net,zdorovia.com.ua,zn.ua##+js(set-constant, String.prototype.charCodeAt, trueFunc)` no longer work.

Example: `https://112.ua/mir/v-minske-prizemlilsya-samolet-tu-214-rossiyskoy-fsb-smi-546940.html`
Ukrainian ip required. You can use [Hola](https://chrome.google.com/webstore/detail/hola-free-vpn-proxy-unblo/gkojfkhlekighikafcpjkiklfbnlmeio).

This problem is not observed when using uBlock Origin 1.28.4.

_Originally posted by @dimisa-RUAdList in https://github.com/uBlockOrigin/uAssets/issues/5696#issuecomment-675757755_

**Comment by mapx-** [comment]
dimisa said here: https://github.com/uBlockOrigin/uAssets/issues/5696#issuecomment-678650738
Everything has already been fixed. Update to version 1.29.2.
