### ISSUE TITLE
https://biqle.ru/

### ISSUE THREAD

**Issue by chickenpizza123** [uBlockOrigin/uAssets#796]
### URL(s) where the issue occurs

`[https://biqle.ru/]`

### Describe the issue

[Pop ups keep popping up on this site. At the top where the search bar is. Type "Porn" in click any random video in try to play the video in a pop up will appear. If you try to fast forward a video a pop up will appear. they also appear if you refresh the page while viewing a video then again trying to fast forward the video. And if you refresh the page again on a video then click on any video on the right side then try to play that video a pop up will appear]

I'm on v1.14.12 & Chrome Version 62.0.3202.75

**Comment by mapx-** [comment]
try
`||pussl*.com^`

**Comment by SMed79** [comment]
or
```
/\/watch\?key\=([\da-f]{32}($))/$popup,third-party
/^https?:\/\/[\da-z]{5,14}\.com\/([\da-z]{2}\/){3}[\da-f]{32}\.js$/$script,third-party
```
([admeasures](https://forums.lanik.us/viewtopic.php?f=62&t=33320))

**Comment by chickenpizza123** [comment]
Thank you guys :) this pop up from real life cam was the only one that came thru after applying both

![real life cam](https://user-images.githubusercontent.com/33193744/32142005-6723fc4e-bc5c-11e7-9f3a-6f5fcdf9adbc.jpg)

**Comment by in4u** [comment]
There's an ad banner now above the video.

**Comment by in4u** [comment]
`https://biqle.ru/watch/-163409565_456239096`

**Comment by mapx-** [comment]
`biqle.ru##.message-container`
report at ruadlist
