### ISSUE TITLE
google.com

### ISSUE THREAD

**Issue by cantunborn** [uBlockOrigin/uAssets#7960]
### URL(s) where the issue occurs
`https://www.google.com`

### Describe the issue
When tapping on the search results, first a google URL is opened and then page is redirected to main search result URL.
The link shown after right-clicking (long press on mobile) is also not the URL of search result. This can also be seen in DOM of webpage where the anchor tag `a` has `ping` and `oncontextmenu` (to prevent copying main URL and to replace it with ping URL) attributes which may be considered tracking, but I'm not sure. It definitely is an annoyance since it brings extra redirection and slows down browsing.

### Screenshot(s)

I have put screenshots in another issue on adguard filters page https://github.com/AdguardTeam/AdguardFilters/issues/64616.

### Versions

- Browser/version: Firefox Fenix Nightly
- uBlock Origin version: 1.29.2

### Settings

Default settings.

### Notes

I bypassed this with `google.com##+js(ra, ping|oncontextmenu, a)`, but it may not be accurate.

**Comment by uBlock-user** [comment]
Click-tracking is not na issue because hyperlink auditing is [disabled](https://github.com/gorhill/uBlock/wiki/Dashboard:-Settings#disable-hyperlink-auditing) by default.

**Comment by cantunborn** [comment]
Yes, I can see in the logger that beacon is blocked but the intermediate page still loads albeit as a blank page. Wouldn't you consider it an annoyance atleast?

**Comment by llacb47** [comment]
Google rewrites the links in results on mousedown, proxying the URLs through `https://www.google.com/url?...`.  I fix this using the filter `google.*##+js(set, rwt, noopFunc)`

**Comment by cantunborn** [comment]
I am talking mainly about mobile devices, try opening any google search result in responsive mode in dev tools.

**Comment by uBlock-user** [comment]
> but the intermediate page still loads albeit as a blank page. Wouldn't you consider it an annoyance atleast?

`google.*##+js(ra, onmousedown, a[href][onmousedown])` works for you ?

**Comment by cantunborn** [comment]
> > but the intermediate page still loads albeit as a blank page. Wouldn't you consider it an annoyance atleast?
> 
> `google.*##+js(ra, onmousedown, a[href][onmousedown])` works for you ?

No, the search results don't have `onmousedown` attribute on mobile. Take a look at the screenshots I posted on the adguard filters issues page.

**Comment by uBlock-user** [comment]
try `google.com##+js(ra, onmousedown|ping, a[href][onmousedown]\, a[href][ping])`

**Comment by llacb47** [comment]
Sneaky google

```
google.ctpacw = {};
google.ctpacw.cm = function(a) {
  a.ping && (a.href = a.ping, a.removeAttribute("ping"))
};
```

**Comment by cantunborn** [comment]
> Sneaky google
> 
> ```js
> google.ctpacw = {};
> google.ctpacw.cm = function(a) {
>   a.ping && (a.href = a.ping, a.removeAttribute("ping"))
> };
> ```

This is what I was talking about 😃.

**Comment by cantunborn** [comment]
> @cantunborn try `google.*##+js(ra, onmousedown|ping, a[href][onmousedown]\, a[href][ping])`

Yes it works.

**Comment by krystian3w** [comment]
"`\,`" no need documented on wiki https://github.com/gorhill/uBlock/wiki/Resources-Library#remove-attrjs-

**Comment by gwarser** [comment]
@krystian3w third point https://github.com/gorhill/uBlock/wiki/Resources-Library#general-purpose-scriptlets

**Comment by cantunborn** [comment]
Similar issue in image results, google uses `mousedown` event listener with [JsAction](https://opensource.google/projects/jsaction) to modify result URL on right-click. Can copy original link using ClearURLs addon's cleaner.

Is it possible to defuse the listener using uBO?

**Comment by krystian3w** [comment]
Maybe not visible in `aell` or need kill all of group events `+js(aeld, /JsAction/i)`  then have similar bugs to events created with jQuery.

**Comment by uBlock-user** [comment]
You can try `www.google.*##+js(ra, jsaction, a[data-ved][jsaction][rel="noopener"][target="_blank"], stay)` or `www.google.*##+js(aeld, contextmenu)`

**Comment by cantunborn** [comment]
`www.google.*##+js(aeld, contextmenu)` does not work. I can't install dev-build currently, so will check other filter when uBO update releases.

**Comment by uBlock-user** [comment]
Scriptlets will not work on google image search page on Firefox because of https://bugzilla.mozilla.org/show_bug.cgi?id=1267027

**Comment by krystian3w** [comment]
Possible with with Scriptlet Doctor or this:


`security.csp.enable` | `false`
-- | --

**Comment by kotarou3** [comment]
Note that this ends up partially disabling search history (which is technically tracking, but I nevertheless find useful).  
Specifically, search history will no longer be able to track which results you clicked on.

I've personally added a filter exception for this filter in my personal list, but leaving a message here in case others come wondering

**Comment by stdedos** [comment]
It also blocks Timeline manipulation from working

**Comment by uBlock-user** [comment]
replaced with `www.google.*##+js(set, rwt, noopFunc)`, report if you still the such breakage.

**Comment by uBlock-user** [comment]
replaced with `www.google.*##+js(set, rwt, noopFunc)`, report if you still experience such breakage.

**Comment by stdedos** [comment]
Is it live? Should I update my filter list now and try it?

I had also opted to disable the filter in The Logger (`#@#`), but I don't find such disable in my filters.
Do I need to do something about it?

**Comment by uBlock-user** [comment]
Remove the filters you added to counter the filter and force update uBlock Annoyances list.

**Comment by stdedos** [comment]
I didn't add a filter manually, and I cannot find any `google` entry in My filters

**Comment by okiehsch** [comment]
Update the `uBlock Annoyances list` to get the new filter.

**Comment by krystian3w** [comment]
Recommend is waiting 10 minutes after update any list on github - glitch with CDN cache...

**Comment by in4u** [comment]
This filter is causing breakage where some PDF files in the search results page do not get downloaded/saved.

Tested using Firefox 100.0.2 with its PDF option set to `Save File` instead of `Open in Firefox`. Search google for `sample pdf`, scroll through results and click on the PDF file link from `pdf995.com`. The file gets saved but is actually empty, i.e. 0 bytes size. If the filter is disabled then things work as expected and the proper file gets saved.

**Comment by mapx-** [comment]
First I get "potential security risk", then I allow the download => the pdf is correctly downloaded

**Comment by in4u** [comment]
@mapx- Your security warning hints at this being a problem only for HTTP (not HTTPS) PDF file link results. My FF has HTTPS-Only mode disabled in favour of `dom.security.https_first = true` (i.e. HTTPS-First mode, which is the FF default for private browsing windows). Can you try again after disabling HTTPS-Only mode in FF settings and searching in private browsing mode instead? Do you still get the proper non-zero byte PDF file saved?

**Comment by mapx-** [comment]
still can not reproducing your issue, @okiehsch could you test ?

**Comment by okiehsch** [comment]
I can't, I tried in a private browsing window as well and I can save the file without issue.

**Comment by Daxy7** [comment]
Is it possible to exclude recaptcha api from this? On some sites it can be called over four times
Test: `https://www.google.com/recaptcha/api2/demo`

**Comment by stephenhawk8054** [comment]
> `https://www.google.com/recaptcha/api2/demo`

Captcha works normally for me on this site. What do you mean?

**Comment by Daxy7** [comment]
I mean uBO puts js on where link tracking doesn't apply
![image](https://github.com/uBlockOrigin/uAssets/assets/91396482/b5fc18a7-0602-4b45-86f4-85995c99d548)

**Comment by stephenhawk8054** [comment]
Yes, currently scriptlets can only be applied on domains. Does it cause any breakages?

**Comment by Daxy7** [comment]
No

**Comment by Daxy7** [comment]
Found occurrence when right clicking an image

https://github.com/uBlockOrigin/uAssets/assets/91396482/a30bc5e8-c8e8-43fe-ae1d-0ab72d6cad33

**Comment by gwarser** [comment]
> Found occurrence when right clicking an image

Occurrence of what?

**Comment by Daxy7** [comment]
link tracking

**Comment by mapx-** [comment]
the original https://github.com/uBlockOrigin/uAssets/issues/20833 converted in discussion:

https://github.com/uBlockOrigin/uAssets/discussions/20846

**Comment by stephenhawk8054** [comment]
@gorhill Sorry, can you take a look? I can reproduce the issue where `google.com##+js(aeld, mousedown)` cannot defuse the above event listener.

**Comment by uBlock-user** [comment]
Can't repro, `www.google.*##+js(set, rwt, noopFunc)` still works.

**Comment by stephenhawk8054** [comment]
I can reproduce in Firefox when right click

![image](https://github.com/uBlockOrigin/uAssets/assets/66517106/08f25b67-3893-4c53-936d-2a684491f0d4)

**Comment by uBlock-user** [comment]
@stephenhawk8054 Need to use -href-cleaner scriptlet for that. The issue is at `href=/url?sa=t&source=web&rct=j&opi=89978449&url=https://en.wikipedia.org/wiki/X-Men:_The_Animated_Series&ved=2ahUKEwjWkrSg05OFAxWKk68BHdF0CToQFnoECC0QAQ&usg=AOvVaw1QZ23LbjrlDMGmvRkROWDH` attribute

**Comment by stephenhawk8054** [comment]
That could be another way, before right clicking on that link the element looks like this

```html
<a jsname="UWckNb" href="https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm" data-ved="2ahUKEwijuJvG1ZOFAxWblK8BHSa6DcoQFnoECAYQAQ" data-sb="/url?sa=t&amp;source=web&amp;rct=j&amp;opi=89978449&amp;url=https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm&amp;ved=2ahUKEwijuJvG1ZOFAxWblK8BHSa6DcoQFnoECAYQAQ&amp;usg=AOvVaw1m9pu35nBXRjvT4aqrVBjR"></a>
```

**Comment by uBlock-user** [comment]
> That's why www.google.*##a[data-sb^="/url?"]:remove-attr(data-sb) works

Indeed, this fixes up. You should add it.

**Comment by stephenhawk8054** [comment]
`href-sanitizer` won't work on desktop. I only set it on mobile

**Comment by Daxy7** [comment]
How to truncate URLs like these in Google images?
`https://www.google.com/search?q=germ+warfare#vhid=gaG-tD5eCpYK3M&vssid=l`
https://github.com/uBlockOrigin/uAssets/assets/91396482/05e5cf0d-4c8c-41ad-b7d7-1f80d493b6a5

**Comment by gwarser** [comment]
`uritransform` https://github.com/uBlockOrigin/uBlock-issues/issues/3084

**Comment by Daxy7** [comment]
Truncation for `GSA Mode`. Enter `test 123` and click on the sidebar links.
```
https://www.google.com/search?udm=50
```

```
https://www.google.com/url?sa=i&source=web&rct=j&url=https://www.123test.com/&ved=2ahUKEwiSgLrO4tiRAXWGQEEAHXQWMdgQqYcPegYIAQgJEAM&opi=89978449&cd&psig=AOvVaw37Eq6YbnIVgc5kBXz0oEjD&ust=1766753179162000
=
https://www.google.com/url?sa=&source=&rct=&url=&ved=&opi=&cd=&psig=&ust=
= 
https://www.123test.com/
```
https://github.com/user-attachments/assets/501ffed1-02f4-4ebb-b198-761320876340

**Comment by ghost** [comment]
I get "Sponsored" images:

https://github.com/user-attachments/assets/036aecf6-2fac-40bb-ac8c-6f9730320745

**Comment by playonevideo** [comment]
If I search something on Google, and click the "News" tab, if I want to clear the search bar (by pressing the "X" button), it doesn't work. I notice the number of blocked elements increases with each click I do on the X button.

Video: https://streamable.com/zizufl

<details>

```yaml
uBlock Origin: 1.71.0
Firefox: 151
filterset (summary):
 network: 171408
 cosmetic: 132680
 scriptlet: 49181
 html: 3761
listset (total-discarded, last-updated):
 added:
  ublock-experimental: 19-0, 3m
  adguard-cookies: 38593-93, 3m
  ublock-cookies-adguard: 5670-80, 3m
  fanboy-cookiemonster: 46521-3789, 3m
  easylist-annoyances: 5201-42, 3m
  easylist-chat: 275-0, 3m
  fanboy-ai-suggestions: 244-1, 3m
  easylist-newsletters: 9310-33, 3m
  easylist-notifications: 2503-175, 3m
  ublock-annoyances: 4928-64, 3m
  HUN-0: 2278-83, 3m
 default:
  user-filters: 78-1, never
  ublock-filters: 52456-70, 3m
  ublock-badware: 10340-28, 3m
  ublock-privacy: 4024-2, 3m
  ublock-unbreak: 2827-1, 3m
  ublock-quick-fixes: 490-14, 3m
  easylist: 91761-127, 3m
  easyprivacy: 55801-33, 3m
  urlhaus-1: 24285-6, 3m
  plowe-0: 3508-1023, 3m
  ROU-1: 1753-37, 3m
filterset (user): [array of 73 redacted]
trustedset:
 added: [array of 9 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 223 ms (selfie)
 maxAssetCacheWait: 124 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 14
 network:
  google.com: 13
  csp.withgoogle.com: 1
 extended:
  ##[role="listitem"]:has(a[href*="aep=1&ntc=1"])
  ##div[class="YNk70c CuvrIe"]
  ###main a[href][data-sb^="/url?"]:remove-attr(data-sb)
  ##+js(set-local-storage-item, mapslitepromosdismissed, 1)
  ##+js(trusted-click-element, button#W0wltc, '', 500)
  ##+js(set-attr, c-wiz[data-p] [data-query] a[target="_blank"][ro…
  ##+js(set-constant, rwt, noopFunc)
```

</details>

**Comment by stephenhawk8054** [comment]
What happens if you turn off uBO?

**Comment by playonevideo** [comment]
The X button works.

**Comment by stephenhawk8054** [comment]
On my side, that button doesn't work even when I don't use any extensions.

**Comment by playonevideo** [comment]
Weird, probably some A/B testing, who knows.

**Comment by uBlock-user** [comment]
Issue happens without uBO too, site issue.

**Comment by krystian3w** [comment]
Google did some A/B Test with a new link format:

```adb
https://www.google.com/goto?url=CAESbAHuR6pNbcvdV8htb7XKFQ8H8biCejSTzl-Xwr1AXlTvYErw2FEvFsZ6oQpGJbODQCc-Lf8dbBev4KT3-9fJ7A3dQSrkIC9P5osYUCt7T9EJrExGB89_M9El6wW-7rHC2fLW0qnPltyR34v1jA==
https://www.google.com/goto?url=CAESbAHuR6pN-KGtLmlS9CgiVq47JltMvXScIcy2KYscuKcbtTKBCEYtOvGvh3IJQethmXHrq1ZfTvlel0Y8RQpELOWKHcEEOxDmP1CHDTv7pG4_HRIGnY1dqz_Oey-SSutu7aVxGSBl2ZHGFb2V7g==
```

The `CAESbAHuR6pN[...]==` equal `https://github.com/uBlockOrigin/uBlock-issues/issues`

Unfortunately it doesn't seem to be base64 (Unless they force the encode several times).

---

<details><summary><b>Response Body:</b><br></summary>

```yml
HTTP/2 302 
location: https://github.com/uBlockOrigin/uBlock-issues/issues
cache-control: private
content-type: text/html; charset=UTF-8
content-security-policy: object-src 'none';base-uri 'self';script-src 'nonce-Ow6e-tEWHLwSiyqbsYwqPg' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
date: Thu, 25 Jun 2026 17:41:20 GMT
server: gws
content-length: 249
x-xss-protection: 0
x-frame-options: SAMEORIGIN
set-cookie: __Secure-STRP=ANmZwa3gRNGeYJ76Hy-77GIUQcBfOOmO_8IHHAPDwTI1zhSRTjXvcnTO8mO2yywPeA4XrnUx0pTauncO1q4R6qpozhMOgerg50lV; expires=Thu, 25-Jun-2026 17:46:20 GMT; path=/; domain=.google.com; Secure; SameSite=strict
set-cookie: NID=532=hsaHEzFikUfnguIvuggyujzNmDyUC0rzfrNbqt6dcRnUPqtsq-e4PyJ8S0X1h9VgVNwVOfbPvvL6SQQAQ9ffaJDodnh76awx1ZEnv76JxpRBmCqjhAPptzG4lhNBBJr1Ii5iihHkX4YGQ9fBOKAsPeNEF1gU75530Sf6gFXLW6vWhpolxewTMKDHOb-6NRCg1wurbIy9lCMxMGlyhdGOYwA; expires=Fri, 25-Dec-2026 17:41:20 GMT; path=/; domain=.google.com; HttpOnly
set-cookie: __Secure-BUCKET=CLAG; expires=Tue, 22-Dec-2026 17:41:20 GMT; path=/; domain=.google.com; Secure; HttpOnly
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://github.com/uBlockOrigin/uBlock-issues/issues">here</A>.
</BODY></HTML>
```

</details>
<details><summary><b>Response MetaData:</b><br></summary>

```yml
Array
(
    [url] => https://www.google.com/goto?url=CAESbAHuR6pNbcvdV8htb7XKFQ8H8biCejSTzl-Xwr1AXlTvYErw2FEvFsZ6oQpGJbODQCc-Lf8dbBev4KT3-9fJ7A3dQSrkIC9P5osYUCt7T9EJrExGB89_M9El6wW-7rHC2fLW0qnPltyR34v1jA==
    [content_type] => text/html; charset=UTF-8
    [http_code] => 302
    [header_size] => 1272
    [request_size] => 316
    [filetime] => -1
    [ssl_verify_result] => 20
    [redirect_count] => 0
    [total_time] => 0.046471
    [namelookup_time] => 0.002343
    [connect_time] => 0.008764
    [pretransfer_time] => 0.019284
    [size_upload] => 0
    [size_download] => 249
    [speed_download] => 5358
    [speed_upload] => 0
    [download_content_length] => 249
    [upload_content_length] => 0
    [starttransfer_time] => 0.046237
    [redirect_time] => 0
    [redirect_url] => https://github.com/uBlockOrigin/uBlock-issues/issues
    [primary_ip] => 2001:4860:482c:7700::
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => 2604:a880:800:10::f9:6001
    [local_port] => 41240
    [http_version] => 3
    [protocol] => 2
    [ssl_verifyresult] => 0
    [scheme] => HTTPS
    [appconnect_time_us] => 19145
    [connect_time_us] => 8764
    [namelookup_time_us] => 2343
    [pretransfer_time_us] => 19284
    [redirect_time_us] => 0
    [starttransfer_time_us] => 46237
    [total_time_us] => 46471
    [request_header] => GET /goto?url=CAESbAHuR6pNbcvdV8htb7XKFQ8H8biCejSTzl-Xwr1AXlTvYErw2FEvFsZ6oQpGJbODQCc-Lf8dbBev4KT3-9fJ7A3dQSrkIC9P5osYUCt7T9EJrExGB89_M9El6wW-7rHC2fLW0qnPltyR34v1jA== HTTP/2
Host: www.google.com
user-agent: Wheregoes.com Redirect Checker/1.0
accept: */*
accept-encoding: gzip
accept-language: en-US,en;q=0.5


    [effective_method] => GET
)
```
</details>


---

Other sample:

```adb
https://www.google.com/goto?url=CAESVQHuR6pN9dQ6OA1MJ4S5AgLT2-M5ZYq7V_BqsyLg5-eaeJ0ofLD6tVIc2KWSLUEJFYTv8zTgJXgIEdrJ4Ko68r1_KZj_ZI48nNBlMwvOqWXYVbAZu28=
! equal https://www.base64decode.org/
```

**Comment by Procyon-b** [comment]
google images is currently A/B testing the layout of the thumbnails. I have the new design ("vertical" layout like pinterest). I have it once every 2 or 3 days.

In this design, "Sponsored" thumbnails aren't hidden.

My current selector for these thumbnails is: `div.kb0PBd.cvP2Ce:not(:has(> [jscontroller], > [data-ved]))`
The first `:not()` element is to distinguish from a normal results. The second is to prevent matching the "Related searches" widget.
I'm testing this for almost a week and it seems to work as expected. (I test with elements "marked", not hidden)

Here is the source code:

<img width="164" height="83" alt="Image" src="https://github.com/user-attachments/assets/ce40ceee-5658-4eab-becd-f092a1461841" />

The sponsored thumbnail is the second one, with the sub-element highlighted.

Here are screenshot

<img width="105" height="61" alt="Image" src="https://github.com/user-attachments/assets/36a8d05b-8115-4aca-95bb-cefbf40ff02a" />
<img width="105" height="55" alt="Image" src="https://github.com/user-attachments/assets/66a6bfed-cf10-4e06-b1da-c01e85f87ad3" />

The sponsored items are outlined in red by my test filter.

**Comment by Yuki2718** [comment]
I'm uneasy to rely on `:not`. What is the element of `Gesponsored`? Are they using an image for that like bing?

**Comment by uBlock-user** [comment]
@Procyon-b sounds like https://github.com/uBlockOrigin/uAssets/issues/33288, nobody could repro that.

Author used  `www.google.com##div:has(> div > div[data-hb="isv"])` as a working filter, try that.

**Comment by playonevideo** [comment]
I also get these "Sponsored" ads:
<img width="1919" height="911" alt="Image" src="https://github.com/user-attachments/assets/ddbd7ca6-34c9-4c68-a4d8-731b65158528" />

**Comment by Procyon-b** [comment]
Sorry for the delay to answer.

@uBlock-user  that selector works.

@Yuki2718 
Here is the entire source code of a normal result node: `https://www.logpasta.com/paste/e59bc4d5-3592-40ad-8b58-fde3f6f1c33d`
And here is the code for a sponsored thumbnail: `https://www.logpasta.com/paste/fdd31dbb-fb2a-43f0-96ca-2695effac166`
(I had the page in NL because it's the default language chosen by google for my country, and changing the language setting also changed the layout at the time. Today I get the new design whatever I do)

Note: I noticed that the sponsored items only appear if the search terms are related to something they have to display. So, not all searches bring sponsored items. Far from it.

**Comment by stephenhawk8054** [comment]
@Procyon-b Does this one work for you?

```adb
www.google.com##div[data-snf][data-snm]:has(> div[class] > div[data-hb="isv"])
```

**Comment by Procyon-b** [comment]
@stephenhawk8054 It works too.

**Comment by krystian3w** [comment]
I'm "infected" with this A/B test `goto?url=` links again (https://github.com/uBlockOrigin/uAssets/issues/7960#issuecomment-4796582010).

Supposedly, the links are already masked at the `view-source:` level (i.e. without breaking the secret encoding in the URL there will probably be no progress).

In theory, deleting the `__Secure-ENID` cookie helps (But this causes the loss of settings, e.g. dark mode - it will be set from the second visit). I will still have to check if cookies can be transferred to another computer (For now, you can import/move between different Firefox forks with that pesky A/B test activated; attempting to import/move to Chromium forks fails - A/B test doesn't activated or I need to convert cookie file to Netscape syntax).

**Comment by Yuki2718** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7960#issuecomment-5140585234 Is that causing slipping ad, or any other privacy issue?

**Comment by krystian3w** [comment]
Theoretically, it violates privacy because I no longer know the original link and I am forced to delete the selected cookie or notify Google that I am interested in opening their link, so they have click statistics collected via the server.

Because it is rather inconvenient to copy the link of their secret a'la json table:

https://www.logpasta.com/paste/raw/e36d8513-167c-4832-9111-7a3e522927d4.txt

**Comment by uBlock-user** [comment]
@gorhill can the links in https://github.com/uBlockOrigin/uAssets/issues/7960#issuecomment-4796582010 be cleansed ?

**Comment by krystian3w** [comment]
It might be easier to do this as a Violentmonkey script.


The all `view-source:` after successfully migrating cookies between different computers, but still within Firefox (Gecko/Servo):

https://www.logpasta.com/paste/raw/d6189077-2f06-4a78-be51-679652c9e7a9.txt

I just don't know if Google has hidden the IP address of my home internet provider or, God forbid, the local branch of "my company".

**Comment by Kinryu** [comment]
> I'm "infected" with this A/B test `goto?url=` links again ([#7960 (comment)](https://github.com/uBlockOrigin/uAssets/issues/7960#issuecomment-4796582010)).

I'm getting the same obfuscated "goto?url=" URLs consistently now. It started sporadically a month ago and now I can't get rid of it. As a result I can't copy a reddit link to view in redlib. Not to mention google is tracking in an even more insidious way.

> I just don't know if Google has hidden the IP address of my home internet provider or, God forbid, the local branch of "my company".

What do you mean Google is hiding your IP? Google punishes you based on your IP and browser fingerprinting among other things.

**Comment by stephenhawk8054** [comment]
They serve those links at `view-source` and the parameters looks encoded by their own ways (maybe on their servers) so I don't know whether there are any ways to retrieve back the real URLs.

**Comment by krystian3w** [comment]
They are still in something resembling arrays/tables in the script tag? If there were still some and it would be necessary to determine whether they were listed in the correct order and perhaps replace them on that basis.

```js
,null,null,null,null,null,null,null,null,["Morele - zalety i właściwości - Czytelnia apteki Cefarm24","Morele mają również dobry wpływ na układ pokarmowy. W owocach tych znajdziemy sporo błonnika oraz pektyn, co pomaga w walce z zaparciami, zgagą ...","Apteka Internetowa Cefarm24.pl","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAXVBMVEVHcEz////////////////////////m9fO459KO2LRpzp9Pxo8AtWqf38Ekvn571Kv2/fvS8eP///+MpsgANowAIYVJdKtih7UASpVxkbzD1eYlXp+twtkAC33b5/IOxSRGAAAAE3RSTlMATr7v9sz////////////////GzuQGRAAAAUNJREFUeAGF0wdiwjAQBVHqrCyvbLnifv9jBktKp7yE+ocOh7vj6Xx54Hw6HoIrT13/7GIya3M1v4ojJE7VOmOsFlp6kuPhRGQ0r0gk04yoPpwJSo1z4vPCszsfLuzynD+chuISA/t3D8V3YJSdCD9Z+xWoQNN2d70nurUDWqXAWBiHSUSmtkl734+YIgWFQDexG5q4z7QLqITAFzCtwq5d0r6tG5QuBM6C3wDC1WFn6QCTh8BakjDFo3E/Eg1BVgGyNP3cDZJ25gbw30GzDremmYCxZ9dN34EzbOtE0g3t7n789RDG0cwkfgqaYZqgKkIgOf24RSS3HiiLMr1RtG0X9CThHVU1McgMD4mTGHjlqRDgsjcBRfUmQOVpcIZX93H++tpbxyOn7x9OVVbCP/efZw2JqKvE//txpiLx/s/+9uf/AVXOIfVPfimZAAAAAElFTkSuQmCC"],[null,1,[null,null,5,null,"Morele - zalety i właściwości - Czytelnia apteki Cefarm24",null,"/goto?url\u003dCAESvgEB6zswFSkFZxvz-1HKLtSgC2o-6lUCip27BqDe3KggDhA05s7I63BB_aFpdc0KwdUz3mhZUOXnR8onBpoOEKl-_f7dx88akjGh-OjAw8GWmuNuOJ4N2247zQqfNq66I0qyFoVCuBRmPLXXIMY5LS0SEB1p9g9XcxmrkEf18vDDkMZKHNOCOQVDWgpqMfJPhaN-YKxleysDg1szMid3D9zDBcWelt5BEC0fmyaV4MtJDCvoUOvQR6L-XUmBiXX1"],["https://www.cefarm24.pl/czytelnia/dieta/morele-zalety-i-wlasciwosci/?srsltid\u003dAfmBOoq70Ak6LwLYZR1-NhMvs2FGIPP8Ff1M-UmD3wK5AsELnFx2DKgf","Morele - zalety i właściwości - Czytelnia apteki Cefarm24","Morele mają również dobry wpływ na układ pokarmowy. W owocach tych znajdziemy sporo błonnika oraz pektyn, co pomaga w walce z zaparciami, zgagą ...",1,"pl","PL",null,"/s?tbm\u003dmap\u0026gs_ri\u003dmaps\u0026suggest\u003dp","AF5tSO6_EkThNdft805ZOseP2vQGilcK0A:1787821798503","Apteka Internetowa Cefarm24.pl"],null,null,null,["/goto?url\u003dCAESvgEB6zswFSkFZxvz-1HKLtSgC2o-6lUCip27BqDe3KggDhA05s7I63BB_aFpdc0KwdUz3mhZUOXnR8onBpoOEKl-_f7dx88akjGh-OjAw8GWmuNuOJ4N2247zQqfNq66I0qyFoVCuBRmPLXXIMY5LS0SEB1p9g9XcxmrkEf18vDDkMZKHNOCOQVDWgpqMfJPhaN-YKxleysDg1szMid3D9zDBcWelt5BEC0fmyaV4MtJDCvoUOvQR6L-XUmBiXX1",null,null,null,35,"Źródło: Apteka Internetowa Cefarm24.pl"]
```

https://www.logpasta.com/paste/raw/0f233607-7d98-4ecc-9aa4-2a43672e0947.txt

Maybe there is some Google switch in the JS jungle since they didn't remove the code.

**Comment by Procyon-b** [comment]
@krystian3w 
When I tried on my side yesterday, the url wasn't present in the source code at all. Even in script tags.

However, when I tried google image a few hours ago, I noticed that if you open the dialog for the result, the real url is displayed. I haven't dug deeper, but from previous userscripts (eg. one recovering the image dimensions), everything info-related to the results is fetched in a single request. So, unless they have changed something, for image results the full url could still be available.

**Comment by Procyon-b** [comment]
@krystian3w 
So, apparently the correct url is still in the page. Someone (found by a user on reddit) has written and published a working userscript on greasyfork.
And today, when I search for the url in the source of the page, I find it. I don't know why it didn't work yestersday.

**Comment by Kinryu** [comment]
> [@krystian3w](https://github.com/krystian3w) So, apparently the correct url is still in the page. Someone (found by a user on reddit) has written and published a working userscript on greasyfork.
Thank you. The scripting solution is rather precarious and I expect this anti-feature to become more obstructive in the future.

**Comment by stephenhawk8054** [comment]
Yeah, looks like they still include original links in `view-source`. Will check how to extract them more easily.

**Comment by stephenhawk8054** [comment]
Can anyone test these filters:

```adb
www.google.com##+js(aeld, mouseover, , elements, #search #rso div[data-rpos] > div[data-ved])
www.google.com##+js(rpnt, script, this.gbar_=, `window.addEventListener("mousemove",(()=>{W_jd&&document.querySelectorAll("#search #rso div[data-rpos]").forEach((t=>{let e=t.querySelector('div[data-hveid] span[jsaction^="trigger."] > a[href^="/goto?url="]');if(!e)return;let r=t.querySelector('div[id^="atritem-"]')?.attributes?.jsdata?.value?.split?.(";_;")?.[1];r&&Object.getOwnPropertySymbols(W_jd[r]).map((t=>{let l=W_jd[r][t];if("object"!=typeof l)return;let s=Object.values(l)?.[0]?.[32];if(console.log(s),s?.[3]?.[0]?.startsWith?.("http"))e.setAttribute("href",s[3][0]);else if(null!==s?.[3]){let t=Object.values(s?.[3]);t?.[0]?.[0]?.startsWith?.("http")&&e.setAttribute("href",t[0][0])}else null===s?.[3]&&s[11]?.[7]?.startsWith?.("http")&&(console.log(s),e.setAttribute("href",s[11][7]))}))}))}));this.gbar_=`)
```

Go to uBO's settings > Add the filter(s) in ["My filters" pane](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) > **Turn on `Allow custom filters requiring trust`** > ✓ Apply changes > Open new tab and test again.

**Comment by krystian3w** [comment]
Apparently, userScript already exists (the one I found is 2 weeks old), but it will probably fall apart quickly when Google tracks the uAssets repository.

**Comment by Yuki2718** [comment]
@stephenhawk8054 Working fine, we can add them. But not working for mobile view.

**Comment by stephenhawk8054** [comment]
Yeah, I'll just address step by step first (maybe only MV2 at the moment) since it's a big site (and a lot of uncovered links too) and there could be a lot of risks.

**Comment by Yuki2718** [comment]
Yeah, especially their DOM structure may be different on some pages or for some people. BTW maybe we can specify `b.src` for the aeld.

**Comment by playonevideo** [comment]
Getting them again:

<img width="336" height="268" alt="Image" src="https://github.com/user-attachments/assets/59054583-4e1e-4539-a1f7-fff5b6e92ea4" />

**Comment by krystian3w** [comment]
Provided, that is, that this section is at all compatible with the remaining JavaScript in the page’s code.

After cropping it like that, I don’t know what I’m looking at.

**Comment by Snuupy** [comment]
please reopen this issue 

as a temporary workaround I've only been able to find this as an alternative but it doesn't work on mobile if you try to long press the url to open it in a new tab

https://greasyfork.org/en/scripts/591392-google-search-direct-links-bypass-goto

**Comment by Procyon-b** [comment]
I don't think that it can be fixed by uBO anymore.
The full link has been removed from the source code of the text results page.
