### ISSUE TITLE
onhax.me

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#797]
Fake download button ads on `https://onhax.me`.

**SS:** https://i.imgur.com/0tZbHtG.jpg (Full page screenshot showing the ads)
**Error URL:** `https://onhax.me/spotify-music-v2-6-0-813-mod-apk-is-here-latest`

_**Note:** Using uBO 1.14.12 on Chrome 62 with the default filters and settings._

**Edit:** They also seem to be using Roughted as they to connect to its domains and also have embedded Roughted code on the pages. This should be blocked as well.

**Comment by mapx-** [comment]
test
```
onhax.me##[id*=prom]
onhax.me##script:inject(window.open-defuser.js)
```
