### ISSUE TITLE
avimobilemovies.net/hackiee.mobi

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#7970]
### URL(s) where the issue occurs

`http://www.avimobilemovies.net`
`http://hackiee.mobi/download.php?file=2626`

### Describe the issue

popup ads

### Versions

- Browser/version: firefox A.
- uBlock Origin version: 1.29.2

### Settings

uBO's default settings
-

### Notes

block filters

`||hackiee.mobi/atag.js$script,1p`
`||www.avimobilemovies.net/atag.js$script,1p`

**Comment by ghajini** [comment]
There are popups on both sites

**Comment by okiehsch** [comment]
Does
````
avimobilemovies.net,hackiee.mobi##+js(nowebrtc)
avimobilemovies.net,hackiee.mobi##+js(acis, Math, zfgloaded)
````
work for you?

**Comment by ghajini** [comment]
> Does
> 
> ```
> avimobilemovies.net,hackiee.mobi##+js(nowebrtc)
> avimobilemovies.net,hackiee.mobi##+js(acis, Math, zfgloaded)
> ```
> 
> work for you?

Not work bro......

Commit by mapx- work but i see consistent crapy requests

Following  work consistently on my end and avoids popups
```
avimobilemovies.net##+js(set-constant, Object.defineProperty, noopFunc)
avimobilemovies.net,hackiee.mobi#@#+js(aopr, btoa)
```

**Comment by okiehsch** [comment]
Thx, added.

**Comment by mapx-** [comment]
some other crao is gone using

`avimobilemovies.net##+js(aopr, String.fromCharCode)`

**Comment by ghajini** [comment]
> some other crap is gone using
> 
What's that mapx-

**Comment by mapx-** [comment]
without `avimobilemovies.net##+js(aopr, String.fromCharCode)`

![image](https://user-images.githubusercontent.com/10303732/98667472-b8378680-234e-11eb-8f0c-d98bcd0c7e3e.png)

with `avimobilemovies.net##+js(aopr, String.fromCharCode)`

only 
![image](https://user-images.githubusercontent.com/10303732/98667638-f339ba00-234e-11eb-8813-c91b40212fb0.png)

**Comment by ghajini** [comment]
> ![image](https://user-images.githubusercontent.com/10303732/98667472-b8378680-234e-11eb-8f0c-d98bcd0c7e3e.png)

So this
https://github.com/uBlockOrigin/uAssets/commit/fe3fc436eec6dcd25402a190c2b62ad9d492d1a9
 doesn't work on your end or default settings?

**Comment by mapx-** [comment]
it seems working 85% in chrome , not in FF

**Comment by ghajini** [comment]
add this site also `hackiee.mobi` to filters above

test link=
`http://hackiee.mobi`
