### ISSUE TITLE
faz.net - with the cookie banner blocked, the page isn't scrollable

### ISSUE THREAD

**Issue by freddyb** [uBlockOrigin/uAssets#7971]
### URL(s) where the issue occurs

`https://www.faz.net/aktuell/`

### Describe the issue

1. Go to the mentioned website above and closely monitor the vertical scrollbar.
2. The vertical scrollbar disappears and the website is not scrollable.

### Screenshot(s)

N/A

### Versions

- Browser/version: Firefox 81 through Firefox Nightly 83 (September 28th).
- uBlock Origin version: 1.29.2

### Settings

Default Settings.

### Notes

The issue disappears when disabling uBlock for the site, but that brings the cookie banner (with the overlay, which eventually allows restoring the scrolling functionality).

**Comment by krystian3w** [comment]
IMO stock config no hide Cookies pop-up.

**Comment by mapx-** [comment]
it's cname
