### ISSUE TITLE
smutty.com [NSFW]

### ISSUE THREAD

**Issue by Rudolpher** [uBlockOrigin/uAssets#7974]
### URL(s) where the issue occurs
https://smutty.com/

### Describe the issue
Back in April @mapx- patched an issue with ADS on smutty, #7290 
Part of the patch now seems to block the log-in window from loading, `||smutty.com^$frame,1p​`

Site attempts to load `https://smutty.com/COMMON/ajax/login.php?iframe=true` when pressing Log In, it results in a blank window while the above filter is enabled. After adding an exception under My Filters for `@@||smutty.com/COMMON/ajax/login.php^$frame,1p` the login window loads properly.

When attempting to log in the same filter blocks `https://smutty.com/COMMON/ajax/sso.php`, 
`@@||smutty.com/COMMON/ajax/sso.php^$frame,1p` is needed for login to go through. User still gets the message 'Request blocked by an extension' due to same filter blocking `https://smutty.com/send_to_top.php`, however a page refresh fixes login.

- Chrome version: 85.0.4183.121 (Official Build) (64-bit)
- uBlock Origin version: 1.29.2

**Comment by Rudolpher** [comment]
Extra ping, there's 2 additional requests it blocks @mapx-   `https://smutty.com/COMMON/ajax/sso.php` (Successful login) + `https://smutty.com/send_to_top.php` (Redirect?)

My apologies for not checking it properly before submitting.

**Comment by Daxy7** [comment]
@mapx- pop-up ads when clicking on any image
log in button says `page has been blocked by an extension`
```
https://smutty.com/
```

```
unknown
```
! pop up
https://github.com/uBlockOrigin/uAssets/assets/91396482/9263f9e4-612f-4ef6-b3ef-39d38a052e8b
! log in error
https://github.com/uBlockOrigin/uAssets/assets/91396482/f9e03760-fed6-430f-8c64-4cdd21ea9ba4

**Comment by stephenhawk8054** [comment]
Caused by

```adb
/^https?:\/\/.*\/[a-z0-9A-Z_]{2,15}\.(php|jx|jsx|1ph|jsf|jz|jsm|j$)/$frame,from=4kporn.xxx|4tube.com|alotporn.com|alphaporno.com|alrincon.com|amateur8.com|anyporn.com|badjojo.com|bdsmstreak.com|bestfreetube.xxx|bigtitslust.com|bravotube.net|cockmeter.com|crazyporn.xxx|daftporn.com|ebony8.com|erome.com|exoav.com|fantasti.cc|fapality.com|fapnado.com|fetishshrine.com|freeporn8.com|gfsvideos.com|gotporn.com|hdporn24.org|hdpornmax.com|hdtube.porn|hellporno.com|hottorrent.org|hqsextube.xxx|hqtube.xxx|iceporn.com|imgderviches.work|imx.to|its.porn|katestube.com|lesbian8.com|love4porn.com|lustypuppy.com|manhwa18.cc|maturetubehere.com|megatube.xxx|milffox.com|momxxxfun.com|openloadporn.co|orsm.net|pervclips.com|porn-plus.com|porndr.com|pornicom.com|pornid.xxx|pornotrack.net|pornrabbit.com|pornwatchers.com|pornwhite.com|pussy.org|redhdtube.xxx|rule34.art|sexvid.porn|sexvid.pro|sexvid.xxx|sexytorrents.info|shameless.com|sleazyneasy.com|smutty.com|sortporn.com|stepmom.one|stileproject.com|str8ongay.com|tnaflix.com|urgayporn.com|vikiporn.com|wankoz.com|xbabe.com|xcafe.com|xhqxmovies.com|xxx-torrent.net|xxxdessert.com|xxxextreme.org|xxxonxxx.com|yourlust.com|youx.xxx|zbporn.com|zbporn.tv
```

in EL.

@ryanbr

**Comment by Daxy7** [comment]
also found adware cookie popups in site page source (left click empty space after 3 seconds have passed):
```
https://pastebin.com/raw/9ujHgxgf
```
