### ISSUE TITLE
Frontapp cannot connect to some kind of notification service and breaks

### ISSUE THREAD

**Issue by CamJN** [uBlockOrigin/uAssets#7975]
### URL(s) where the issue occurs

`https://app.frontapp.com/`, this will redirect to an affected url if you are logged in. Unfortunately you do need an account.

### Describe the issue

The page tries to create a websocket connection to `wss://ws-mt1.pusher.com/app/<app_id_here>?protocol=7&client=js&version=5.1.1&flash=false` or a xhr to either `https://sockjs-mt1.pusher.com/pusher/app/<app_id_here>/<another_int>/<another_id>/xhr?protocol=7&client=js&version=5.1.1&t=<big_int>&n=<connection_attempt>` or `https://sockjs-mt1.pusher.com/pusher/app/<app_id_here>/<another_int>/<another_id>/xhr_streaming?protocol=7&client=js&version=5.1.1&t=<big_int>&n=<connection_attempt>`. When these requests fail the page thinks you have no internet connection and disables input fields and buttons.

### Screenshot(s)

I use front for work, so I'd have to blur out pretty much the whole screenshot, but I've put more info in the notes.

### Versions

- Browser/version: Firefox Developer Edition 82.0b5
- uBlock Origin version: 1.30.0

### Settings

I don't think I've changed anything in the settings.

### Notes

I can fix the page by whitelisting the domains that are blocked with these filter rules:
```
@@||ws-mt1.pusher.com^$domain=app.frontapp.com
@@||sockjs-mt1.pusher.com^$domain=app.frontapp.com
```
But I do not know if this is a good idea or the best approach.

**Comment by mapx-** [comment]
update easyprivacy list and test again (1-2 days ago a fix was added)
