### ISSUE TITLE
Recent update to EasyPrivacy '||pusher.com^$3p' breaks chat on bringatrailer.com

### ISSUE THREAD

**Issue by vikramambrose** [uBlockOrigin/uAssets#7976]
### URL(s) where the issue occurs
Example URL: `https://bringatrailer.com/listing/2005-ferrari-f430-28/`

### Describe the issue

This is an online car auction site that features a live chat at the bottom of the page. Recently (about a week), EasyPrivacy started blocking JS from pusher.com, which breaks the chat feature. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/34391406/94661853-44966880-0310-11eb-8aaf-afbfd15eb5e2.png)

Or sometimes you will see this error at the bottom;
![image](https://user-images.githubusercontent.com/34391406/94661974-6c85cc00-0310-11eb-8836-6534bd520d0c.png)

### Versions

- Browser/version: Firefox for Ubuntu 80.0.1
- uBlock Origin version: 1.29.2

### Settings

None

### Notes

By creating an exception for pusher.com, the site will load the comments but show the error in yellow above after a few seconds.

**Comment by vikramambrose** [comment]
By creating these two rules I'm able to work around the issue;
allow wss://ws-mt1.pusher.com/ap
allow https://js.pusher.com

**Comment by uBlock-user** [comment]
fixed in EasyPrivacy, force update the list.
