### ISSUE TITLE
Cannot post reader comments to articles on the New York Times webste using Firefox Mac

### ISSUE THREAD

**Issue by NormG1** [uBlockOrigin/uAssets#7978]
`https://www.nytimes.com/2020/09/30/opinion/trump-2020-moving-abroad.html?action=click&module=Opinion&pgtype=Homepage#commentsContainer`

### Trying to enter a comment to a NYT article generates an error message. Comments appear in a sidebar until the site closes comments. The error shows up when I press the SUBMIT button says: An error has occurred and we cannot save your comment. Please copy what you’ve written and refresh the page to try again.

No issue posting the exact same comment (cut from Firefox, pasted into Safari) using Safari

 

### Versions

- Browser/version: [Firefox 81.0]
- uBlock Origin version: [1.29.2]

### Settings

-

**Comment by mapx-** [comment]
- test using uBO default setup
- open the logger , refresh the page, select in the logger page only the blocked items, post them here (as 1 or more screenshots)

(be sure there are no other blocking extensions enabled)
