### ISSUE TITLE
magazyn.wp.pl [anti-adblock]

### ISSUE THREAD

**Issue by gargul2** [uBlockOrigin/uAssets#7979]
### URL(s) where the issue occurs

`https://magazyn.wp.pl/`

### Describe the issue

permanent anti-adblock (not annoyance)

### Screenshot(s)

![capture_001_30-09-2020_19-43-11](https://user-images.githubusercontent.com/63287518/94720797-374f9d00-0355-11eb-9511-76dbcb817ae0.gif)

### Versions

- Browser/version: FF 81
- uBlock Origin version: 1.30.1b0

### Settings
Default +
POL: Official Polish Filters for AdBlock, uBlock Origin & AdGuard
POL: Polish Anti Adblock Filters

### Notes

- reported https://github.com/olegwukr/polish-privacy-filters/issues/81 + https://github.com/olegwukr/polish-privacy-filters/issues/120 but they closed 120 and anti-adblock still not fixed hence reporting in uAssets
- enabling AdGuard Base filter doesn't fix the issue neither

**Comment by mapx-** [comment]
test

`magazyn.wp.pl##+js(nostif, block, 0)`

**Comment by gargul2** [comment]
Working, wow - a quick fix! You got big balls man!
