### ISSUE TITLE
Filter works until the page is reloaded

### ISSUE THREAD

**Issue by arbolis** [uBlockOrigin/uAssets#798]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

http://tcec.chessdom.com/live.php

### Describe the issue

The filter: ! 10/29/2017, 1:35:37 PM http://tcec.chessdom.com/live.php
tcec.chessdom.com###tcec_header
works in that the header of the website is removed. But then, refreshing the page makes the header reappear while it should still be disabled.

### Screenshot(s)

Simple enough not to need screenshot I hope.

### Versions

- Browser/version: Firefox 56.0.2 (64-bit) on Arch Linux.
- uBlock Origin version: 1.14.16

### Settings

- Ticked the 3 privacy settings boxes.

### Notes

"tcec header ublock origin" reports 6 results only in Google and none is related to this problem.

**Comment by gwarser** [comment]
Maybe you have "No cosmetic filtering" enabled in UBO Popup:

![Popup](https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/popup-1j.png)

**Comment by arbolis** [comment]
Indeed, for some reason No cosmetic filtering was disabled or enabled (not sure which one it is, but changing it fixed the problem). Thanks a lot, issue closed.
