### ISSUE TITLE
CMC Media Group (many websites) [video hidden]

### ISSUE THREAD

**Issue by gargul2** [uBlockOrigin/uAssets#7980]
### URL(s) where the issue occurs

Many websites of [CMC Media Group](http://cmcmedia.pl/testowa/),
https://github.com/MajkiIT/polish-ads-filter/issues/17140#issuecomment-694974444
except `plonszczak.pl` (they fixed only this)

### Describe the issue

Breakage - hidden video in articles, a filter that causes the breakage:
`||exs.pl/embed*.php$script,domain=~wgospodarce.pl|~szczecinek.com|~polityka.pl|~ototorun.pl|~natemat.pl|~plonszczak.pl` need to exclude many more domains

### Screenshot(s)

https://github.com/MajkiIT/polish-ads-filter/issues/17140#issuecomment-694901664

### Versions

- Browser/version: FF 81
- uBlock Origin version: 1.30.1b0

### Settings
Default +
POL: Official Polish Filters for AdBlock, uBlock Origin & AdGuard
POL: Polish Anti Adblock Filters

### Notes

- reported https://github.com/MajkiIT/polish-ads-filter/issues/17140#issuecomment-694901664 + https://github.com/MajkiIT/polish-ads-filter/issues/17185 + https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2542 + https://github.com/olegwukr/polish-privacy-filters/issues/122#issuecomment-699479975 but they closed them and still not fixed (except `plonszczak.pl`) hence reporting in uAssets

**Comment by mapx-** [comment]
@MajkiIT

**Comment by mapx-** [comment]
nobody cares at the regional lists ? => well, you polish guys could provide a list of example (broken) pages, even better a PR taking care of all these cases.

**Comment by okiehsch** [comment]
They specifically added `||exs.pl/embed*.php$script` maybe the same script is also beeing used to serve ads.

I checked one site, specifically
`https://olawa24.pl/artykul/uwaga-w-naszych-lasach/781491`
to make it easier to reproduce.
The video is about wolves same as the article, so in that cas it appears to be not ad related.

**Comment by gargul2** [comment]
Just:
- add `,badfilter` 
- or add these domains into the filter's exclusions:
`~24jgora.pl,~24wroclaw.pl,~babice2.pl,~brodnica-cbr.pl,~ciechanowinaczej.pl,~ddb24.pl,~e-wyszogrod.pl,~egarwolin.pl,~egorzow.pl,~ekspresjaroslawski.pl,~eprzasnysz.pl,~esiemiatycze.pl,~fakty.bialystok.pl,~galopuje.pl,~golub-cgd.pl,~gpr24.pl,~ibialoleka.pl,~ibielsk.pl,~ikampinos.pl,~imokotow.pl,~inowroclaw.info.pl,~iochota.pl,~iotwock.pl,~ipragapoludnie.pl,~iskierniewice.pl,~itvpiaseczno.pl,~izabelin24.pl,~izoliborz.pl,~izyrardow.pl,~kurierbytowski.com.pl,~kurierpodlaski.pl,~lipno-cli.pl,~lowicz24.eu,~mylomza.pl,~nolesnica.pl,~nowinynyskie.com.pl,~nswiecie.pl,~nwloclawek.pl,~olawa24.pl,~ototorun.pl,~plonszczak.pl,~poluje.pl,~pultusk24.pl,~rypin-cry.pl,~sejny.net,~splendo.pl,~szczecinek.com,~tp.com.pl,~tulegnica.pl,~twojradom.pl,~twojzwolen.pl,~wabrzezno.pl,~wideoportal.tv,~wio.waw.pl,~wolomin24.info.pl,~wterenie.pl,~zambrow.org,~zlotowskie.pl,~zycie.pila.pl,~zyciekalisza.pl`

**Comment by mapx-** [comment]
it's ok if I add

`@@||exs.pl/embed*.php$script`

?
eventually cases with real ads can be reported here

**Comment by gargul2** [comment]
I dunno, do what you think is right.

**Comment by okiehsch** [comment]
No, we don't know why they added that filter we can't simply overrule them if we don't hear from them we can add the exclusions.

**Comment by uBlock-user** [comment]
Make it `@@||exs.pl/embed*.php$script,domain=pl`, so only excepted for polish sites.

**Comment by mapx-** [comment]
@gargul2 give us examples of such pages with real (video) ads

**Comment by gargul2** [comment]
okiehsch, yes, that's what I was asking MajkiIT in my comment https://github.com/MajkiIT/polish-ads-filter/issues/17140#issuecomment-695017253, 
but instead of reply he just ignored and closed the issue...and then he did the same with https://github.com/MajkiIT/polish-ads-filter/issues/17185.
Hard cooperation with MajkiIT.

mapx: give us examples of such pages with real (video) ads

I only provided domains with broken videos as a reporter, you have to talk with MajkiIT about ads...

**Comment by okiehsch** [comment]
The blocking filter was added with https://github.com/MajkiIT/polish-ads-filter/commit/0c45e112cf023c98c7285ec50415aff77095231d
Rather hard to see what was the reason for it ....

**Comment by gargul2** [comment]
Yes, the filters is old, he added it for some small issue, which cannot be reproduced anymore even with the filter removed, not sure whether the filter aims any other issues.

**Comment by okiehsch** [comment]
I agree, well we badfiltered it for now anyway.

**Comment by okiehsch** [comment]
@gargul2 Skip the personal insults.

**Comment by gargul2** [comment]
Lol, sure, but my insults were justified, this troll banned me for no reason, hence why, and before he banned me, he did other rude things I described: https://github.com/uBlockOrigin/uAssets/issues/7980#issuecomment-703219389. If he behaves toxic, I insults him, simple, but hey, ok.
