### ISSUE TITLE
Unblock Bugsnag crash reporting

### ISSUE THREAD

**Issue by bengourley** [uBlockOrigin/uAssets#7983]
I have previously requested (in #7835) that `bugsnag.com` was removed from the block list which was rejected at the time.

However, subsequently #7924 was raised for Sentry, a very similar tool for crash reporting. The action taken for that PR was to unblock Sentry's error reporting endpoint.

May I request that the decision on Bugsnag is reviewed for consistency?

Thanks in advance. Let me know if there are any details that need clarification or if you have any questions I might be able to answer.

**Comment by uBlock-user** [comment]
Removed for now.
