### ISSUE TITLE
NSFW imagefap.com

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#7985]
### URL(s) where the issue occurs

NSFW imagefap.com

### Describe the issue

When you go to NSFW imagefap.com with ublock origin enabled on firefox, none of the pictures load, but when it's disabled, the pictures load properly. This issue only happens on firefox though, because if you go to NSFW imagefap.com with chrome, the pictures load properly if ublock origin is enabled or disabled. 

### Versions

- Firefox 81.0.1 (64-bit)
- Chrome 85.0.4183.121 (Official Build) (64-bit)
- uBlock Origin 1.30.0

**Edit: Removed NSFW picture.**

### Settings

-

**Comment by mapx-** [comment]
@IoanPaleru test in firefox this filter:

`@@||imagefap.com^$cname`

**Comment by okiehsch** [comment]
I can't reproduce using Firefox.

**Comment by mapx-** [comment]
> I can't reproduce using Firefox.

same here, but .. who knows could be for other regions
