### ISSUE TITLE
The yellow Google anti-adblock sticky now also shows up with stock uBO settings

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#7986]
### URL(s) where the issue occurs

```
! https://github.com/NanoMeow/QuickReports/issues/4537
https://www.geekzone.co.nz/forums.asp?forumid=64&topicid=273359

! https://github.com/NanoMeow/QuickReports/issues/4740
https://notalwaysright.com

! https://github.com/NanoMeow/QuickReports/issues/4708
https://gamerant.com/super-mario-3d-all-stars-so-long-bowser-meme-64/
```

### Describe the issue

The yellow Google anti-adblock/anti-cookiemessage-blocking message that shows up at the bottom of many, many websites, seemingly **isn't** defeated by privacy lists anymore. I can only presume this means that a consistent, possibly generic solution would have to be created.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/22780683/94886665-33666c80-0474-11eb-92cc-e7ef6ea6921b.png)

### Versions

- Browser/version: Vivaldi 3.3.2022.47 x64
- uBlock Origin version: 1.29.2

### Settings

![image](https://user-images.githubusercontent.com/22780683/94886772-a1129880-0474-11eb-8581-1924ca354e0c.png)

### Notes

None that would be relevant to the settings shown above.

**Comment by okiehsch** [comment]
Can you reproduce with Chrome, Chromium or Firefox?

**Comment by DandelionSprout** [comment]
I can't reproduce with Firefox. Testing with Chrome would be pretty difficult to the settings I use there, so I'll take your word for it.

So I suppose this is a browser-specific issue after all.

**Comment by okiehsch** [comment]
"The new Vivaldi browser protects you from trackers, blocks unwanted ads, and puts you in control with unique built-in features. "

That could trigger the warning, I don't use Vivaldi, maybe you can find a way to disable those protections and test again.

**Comment by uBlock-user** [comment]
removing/hiding of `##.div-gpt-ad` will trigger the warning.

**Comment by DandelionSprout** [comment]
As for Vivaldi's privacy/adblocker settings, which I only learned about when seeing okiehsch's comment, and before seeing uBlock-user's comment: 
![image](https://user-images.githubusercontent.com/22780683/94890840-bb527380-0480-11eb-9331-2bcad8110f0d.png)

It seems to me that deleting the browser's cookies was enough to prevent the sticky from showing up, although having to delete browser cookies surely can't be a proper solution.

**Comment by uBlock-user** [comment]
Removing cookies makes it disappear only temporarily, it will appear in subsequent visits as site data gets gathered again. Either disable blocking functionality completely in Vivaldi, or make it specific to blocking trackers only(if that works)

**Comment by DandelionSprout** [comment]
I thought I had disabled it completely, though I could try with even fewer privacy settings turned on.

**Comment by krystian3w** [comment]
Also Google could use someting like:

`##.div-gpt-ad-krystian3w` (IDK why my, I don't kill these ads) or maybe `##.div-gpt-ad-smed79` (France pages).
