### ISSUE TITLE
thevideo.io

### ISSUE THREAD

**Issue by mat41997** [uBlockOrigin/uAssets#799]
![2017-10-29 15_55_50-watch tig muxed mp4](https://user-images.githubusercontent.com/5884000/32144983-bd3a0df2-bcc1-11e7-8aac-553734dae801.png)
https://thevideo.io/z0sww6umhzyc

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.44
chrome 62.0.3202.75
win10 x64

**Comment by mapx-** [comment]
```
thevideo.io##script:inject(window.open-defuser.js)
thevideo.io##.vjs-overlay-no-background.vjs-overlay-signup.vjs-overlay-bottom.vjs-overlay
thevideo.io##.vjs-overlay-no-background.hidden-xs-down.vjs-overlay-banner300x.vjs-overlay-top.vjs-overlay
```

**Comment by okiehsch** [comment]
I won't add `##.vjs-overlay-no-background.vjs-overlay-signup.vjs-overlay-bottom.vjs-overlay`, because it is 
self promotion and should not be blocked in my opinion.
