### ISSUE TITLE
gamemod.mobi

### ISSUE THREAD

**Issue by Toshiba1127** [uBlockOrigin/uAssets#7990]
### URL(s) where the issue occurs

`https://gamemod.mobi/download-file?id=9113
`
### Describe the issue

It has countdown from 20 sec until it let you download

### Screenshot(s)

![image](https://user-images.githubusercontent.com/64008639/94941374-1615ba80-04d5-11eb-8417-e30dfdcb5b3c.png)

### Versions

- Browser/version: Chrome 85.0
- uBlock Origin version: 1.29.2

### Settings

- Default

### Notes

Request countdown boost

**Comment by uBlock-user** [comment]
server-sided countdown, not possible.
