### ISSUE TITLE
js Popup is not working with uBlock activated

### ISSUE THREAD

**Issue by stdedos** [uBlockOrigin/uAssets#7992]
### URL(s) where the issue occurs

`https://www.cfos.de/en-gb/cfosspeed/cfosspeed.htm`

### Describe the issue

1. Click the toast box (on the top right!)
2. Click Contact / Support
 

Expected: 
![image](https://user-images.githubusercontent.com/133706/94950579-83cce100-04eb-11eb-9fb5-f1972171f55a.png)
Actual: nothing

### Versions

- Browser/version: Google Chrome 85.0.4183.121
- uBlock Origin version: v1.29.2

### Settings

- _Too many. Is there a quick way to send them?_

### Notes

After reading the logs (which only reveal generic GoogleAd stuff) I am wondering whether the site is at fault, my settings, or something else.

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +7 | ##body:style(overflow: visible!important;) |  | `www.cfos.de` |  | dom | `https://www.cfos.de/en-gb/cfosspeed/cfosspeed.htm` |
| +7 | ##.grecaptcha-badge |  | `www.cfos.de` |  | dom | `https://www.cfos.de/en-gb/cfosspeed/cfosspeed.htm` |
| +7 |  |  | `www.google.com` | 3,3 | script | `https://www.gstatic.com/recaptcha/releases/Y5tQ3lKwn1XL5hGgLz1kR4-1/recaptcha__en.js` |
| +7 |  |  | `www.google.com` | 3,1 | script | `https://www.google.com/recaptcha/api2/webworker.js?hl=en&v=Y5tQ3lKwn1XL5hGgLz1kR4-1` |
| +7 |  |  | `www.google.com` | 3,1 | script | `https://www.google.com/js/bg/KY8PCQen8i8DcjnCV2aLZanzxLrHczPX8AxOogRZAks.js` |
| +7 |  |  | `www.google.com` | 3,3 | css | `https://www.gstatic.com/recaptcha/releases/Y5tQ3lKwn1XL5hGgLz1kR4-1/styles__ltr.css` |
| +7 |  |  | `www.cfos.de` | 3 | frame | `https://www.google.com/recaptcha/api2/anchor?ar=1&k=6LecOeUUAAAAAPFwu4a9PHhiQN7UwXNR5KYhfJsa&co=aHR0cHM6Ly93d3cuY2Zvcy5kZTo0NDM.&hl=en&v=Y5tQ3lKwn1XL5hGgLz1kR4-1&size=invisible&cb=pwwotvsngwq5` |
| +7 |  |  | `www.cfos.de` | 1 | image | `https://www.cfos.de/images/hide-status-window.png` |
| +7 |  |  | `www.cfos.de` | 3 | script | `https://www.gstatic.com/recaptcha/releases/Y5tQ3lKwn1XL5hGgLz1kR4-1/recaptcha__en.js` |
| +7 |  |  | `www.cfos.de` | 1 | xhr | `https://www.cfos.de/en-gb/contact/contact-form.htm` |
| +7 |  |  | `www.cfos.de` | 3 | script | `https://www.recaptcha.net/recaptcha/api.js?render=6LecOeUUAAAAAPFwu4a9PHhiQN7UwXNR5KYhfJsa` |
| +5 | ##body:style(overflow: visible!important;) |  | `www.cfos.de` |  | dom | `https://www.cfos.de/en-gb/cfosspeed/cfosspeed.htm` |
| +5 | `##a[href^="https://twitter.com/intent/tweet?"]` |  | `www.cfos.de` |  | dom | `https://www.cfos.de/en-gb/cfosspeed/cfosspeed.htm` |
| +5 | ##[href*="twitter.com/intent/tweet"] |  | `www.cfos.de` |  | dom | `https://www.cfos.de/en-gb/cfosspeed/cfosspeed.htm` |
| +5 | ##.shariff-button |  | `www.cfos.de` |  | dom | `https://www.cfos.de/en-gb/cfosspeed/cfosspeed.htm` |
| +5 | ##.fade |  | `www.cfos.de` |  | dom | `https://www.cfos.de/en-gb/cfosspeed/cfosspeed.htm` |
| +5 | ##.fa-twitter |  | `www.cfos.de` |  | dom | `https://www.cfos.de/en-gb/cfosspeed/cfosspeed.htm` |
| +5 | ###socialbuttons |  | `www.cfos.de` |  | dom | `https://www.cfos.de/en-gb/cfosspeed/cfosspeed.htm` |
| +1 |  |  | `www.cfos.de` | 3 | script | `https://cse.google.com/cse/brand?form=cse-search-box&lang=en-gb` |
| +1 |  |  | `www.cfos.de` | 1 | script | `https://www.cfos.de/remote_address.shtml` |
| +1 |  |  | `www.cfos.de` | 3 | script | `https://www.google.com/cse/brand?form=cse-search-box&lang=en-gb` |
| +1 | \|\|googlesyndication.com^ | -- | `www.cfos.de` | 3 | script | `https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` |
| +1 | google-analytics.com/analytics.js | << | `www.cfos.de` |  | script | `https://www.google-analytics.com/analytics.js` |
| +1 | \|\|google-analytics.com^ | -- | `www.cfos.de` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +0 |  |  | `www.cfos.de` | 1 | css | `https://www.cfos.de/font-awesome/css/font-awesome.min.css` |
| +0 |  |  | `www.cfos.de` | 1 | css | `https://www.cfos.de/css/shariff.min.css` |
| +0 |  |  | `www.cfos.de` | 1 | css | `https://www.cfos.de/css/cfos-bootstrap.css` |
| +0 |  |  | `www.cfos.de` | 1 | doc | `https://www.cfos.de/en-gb/cfosspeed/cfosspeed.htm` |
</details>

**Comment by mapx-** [comment]
add
`cfos.de#@#.fade`

`AdGuard Annoyances` issue
