### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#7995]
https://github.com/uBlockOrigin/uAssets/blob/f280973fe2867554e6e131e97b348c928e1fdfb9/filters/filters.txt#L21338 https://github.com/uBlockOrigin/uAssets/blob/f280973fe2867554e6e131e97b348c928e1fdfb9/filters/filters.txt#L21341

What page no support CSS from line `21338`  and really need CSS from `21341`?

**Comment by mapx-** [comment]
whitelisting (for google funding in french list) `#@#div[class^="div-gpt-ad"]` then I need 
`*##div[class^="div-gpt-ad"]:style(width:1px!important;height:1px!important;)` 

which take care of `.div-gpt-ad-krystian3w` too not only of `.div-gpt-ad`

**Comment by krystian3w** [comment]
Who used my nick / e-mail in Google Ads?
