### ISSUE TITLE
[nsfw] trakteer.id [right click / copy disabled]

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#7997]
### URL(s) where the issue occurs

`https://trakteer.id/Hanasa/showcase/behind-the-photoshoot-0KSja`

### Describe the issue

right click / copy disabled

### Versions

- Browser/version: [FF 81.0.1 x64]
- uBlock Origin version: [1.30.0]

### Settings

Default , uBO annoyances, easylist cookie, adguard base

### Notes

Need to login to see post, can be bypassed by creating fake account & fake email `https://smailpro.com/`

**Comment by corneolata** [comment]
Lets see
