### ISSUE TITLE
navigaweb.net alert

### ISSUE THREAD

**Issue by happysurf** [uBlockOrigin/uAssets#8]
### Describe the issue:
The site recognize UBO and make an annoying alert on the screen when you start the scrolling.
This is present on every page.

### One or more specific URLs where the issue occurs:
http://www.navigaweb.net/2016/04/portare-chrome-velocita-massima.html

### Your settings:

- Browser/version: [Firefox 46 beta]
- uBlock Origin version: [1.6.9]

**Comment by st4ckz** [comment]
Try with the following filter: www.navigaweb.net##script:contains('afs_ads')

**Comment by gorhill** [comment]
The fix is to block all alerts on the site, including legitimate ones if any (doubtful), and to display whatever message the site was popping to the dev cosole.

**Comment by happysurf** [comment]
Works fine, thank you gorhill.
@st4ckz  = Thanks for your help too.
