### ISSUE TITLE
easylist upornia.com##.mjs-closeplay can't block

### ISSUE THREAD

**Issue by DandyClubs** [uBlockOrigin/uAssets#80]
### URL(s) where the issue occurs

http://upornia.com/videos/346705/japanese-movie3/

### Describe the issue

upornia.com##.mjs-closeplay Block is not work.

### Screenshot(s)

http://image.prntscr.com/image/ad31462369f94327910e3e2215010243.png

### Versions

- Browser/version: CyberFox x86 47.0.2, Chrome  51.0.2704.103 
- uBlock Origin version: 1.7.6

### Settings

http://prntscr.com/br05aa

http://prntscr.com/br05gr

http://prntscr.com/br05qc

### Notes

i test adblock plus, uBlock Origin, AdGuard, Pan(Firefox Add-on)

Easylist Filter Add

Only Pan work Block the upornia.com##.mjs-closeplay

so I add upornia.com##.mjs-closeplay in my filters 

but not block

**Comment by gorhill** [comment]
You need uBO 1.7.7b11 or higher: `upornia.com##.mjs-closeplay:style(z-index:-1)`.
