### ISSUE TITLE
Blocked a milion connection request from a single site - was there something that should be blocked from making these request?

### ISSUE THREAD

**Issue by c933103** [uBlockOrigin/uAssets#800]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://www.businessinsider.jp/post-104782

### Describe the issue

Blocked a milion connection request from a single site - was there something that should be blocked from making these request?

### Screenshot(s)

https://i.imgur.com/fLjv44N.png

### Versions

- Browser/version: 61.0.3163.100
- uBlock Origin version: 1.14.12

### Settings

- enabled filters: ublock filters, badware risk, privacy, unbreak, adblock warning removal, easy list, basic tracking disconnect, easy privacy, fanboy enhanced, malware domain list, malware domain, fanboy annoyance, peter lowe, easylist china, abp japanese 

### Notes

Refresh cause the same problem but not occurring from other pages from the site - haven't tried other browser/etc yet

**Comment by gorhill** [comment]
I was not able to reproduce either -- using only uBO and listed filter lists.
