### ISSUE TITLE
https://fcdot.lc detect Ublock

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#8000]
**(bad example link (mapx))**
`https://fcdot.lc/2020/07/important-steps-to-create-your-perfect-digital-marketing-strategy/?a=ZkY3VA==`

example (mapx)
`fc.lc/WyZL`

**Comment by mapx-** [comment]
provide the original linki and not the page where you landed

**Comment by Dhanamerdeka** [comment]
@mapx- umm what you mean?
source that make me came to that site?

i input the files to https://www.uploadedpremiumlink.net/
and after it some ads make me to came to that link

**Comment by mapx-** [comment]
see https://github.com/uBlockOrigin/uAssets/issues/5495

I mean the real shortcut like `fc.lc/WyZL` which then redirects to 
`https://fcdot.lc/2020/07/technology-based-strategies-to-grow-your-business/?a=V3laTA==`

However, I get no anti adb stuff

Reset to uBO default setup, don't use any other blocking extensions, test again
(you didn't even say browser, lists, uBO versions etc)

**Comment by PIZZA90** [comment]
for me, this URL: `fc.lc/WyZL` redirects to malware site

Something like `https://linx.cloud/get-download/ and a lot of numbers and letters`

![Captura](https://user-images.githubusercontent.com/33556647/95027646-7d309c00-069a-11eb-9992-c54f480c1084.PNG)

**Comment by mapx-** [comment]
yes, `linx.cloud` is a parked domain now

**Comment by okiehsch** [comment]
That's the destonation link.It's a parked site.
Try `https://fc.lc/yKKS` should lead you to a google drive page.

**Comment by PIZZA90** [comment]
`https://fc.lc/yKKS` redirects to:

`https://drive.google.com/file/d/1-PFFikD7ILG_CQmqDSyuX10iCMJmuKss/view?usp=sharing`
