### ISSUE TITLE
vpn-anbieter-vergleich-test.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#8001]
### URL(s) where the issue occurs

`https://vpn-anbieter-vergleich-test.de/`

### Describe the issue

Overlay. When i close this overlay a small window popup appears. Also many frames get loaded

### Screenshot(s)

<img width="826" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/95020685-deda1180-066c-11eb-9b6d-b05e8697e49c.PNG">
<img width="615" alt="93486793-e24b6a00-f904-11ea-8b0c-89b14e54e6cf" src="https://user-images.githubusercontent.com/48647394/95020728-1e086280-066d-11eb-8903-2cda331e6cd9.PNG">

### Versions

- Browser/version: Firefox developer
- uBlock Origin version: v1.30.0

### Settings

default + uBlock Annoyances

**Comment by uBlock-user** [comment]
For overlay, `vpn-anbieter-vergleich-test.de##.popup-wrapper`

**Comment by JobcenterTycoon** [comment]
The overlay is back again and it redirect to the vpn site when i try to close this

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/145b929cde8de84d7ec0c481a30e4efa778174fe
