### ISSUE TITLE
Full page invisible clickable layer on watchseries

### ISSUE THREAD

**Issue by kipmacsaigoren** [uBlockOrigin/uAssets#8002]
The thing with giving me an easy format to fill my info in with got a little messed up here so tell me if this breaks rules of some kind

### URL(s) where the issue occurs

[https://www1.swatchseries.to]

### Describe the issue

Every time I go to a new URL in this site, there is a full page, invisible "almost-ad". I'm not sure how else to describe it. its another layer covering the entire page that must be clicked or added to the element filter before I can interact with the page at all (hover over links and click them mostly). The layer doesn't change what the page looks like at all, but now the entire page is clickable.  

When I use the element zapper, the elements always have names with random looking characters. A few examples of this are 

www1.swatchseries.to###kmaw287
www1.swatchseries.to###lk2srl
www1.swatchseries.to###hyyci84

The problem is that every time I reload the page or navigate to a different part of the site, the random characters change and I have to re add it to the filter list, or be fine with clicking the invisible layer. Usually when I click the invisible layer, nothing (that I can see) happens and the page goes back to normal clickability. 

Every so often though, when I click the layer, a new tab opens into one of those "clean your mac from viruses" pages with a lot of dialogs and spam/virus looking downloads. I've noticed that this happens more often when I click near the search bar but that may be coincidence. to make things even more confusing, when I click the invisible layer, it usually immediately goes away, but sometimes when I use the element zapper, there are two or even three of these layers sitting over the page. 

Let me know if I can give more details or explain this better

### Versions

- Browser/version: [Firefox/81.0 (64 bit)]
- uBlock Origin version: [1.30.0]

### Settings

As far as I know, besides adding filters and adding a few trusted sites, I haven't changed any settings

### Notes

It does the same thing in private mode with all my extensions turned on. As an FYI, I also have these extensions installed:
Privacy badger, Privacy Possum, Disconnect, and smart HTTPS

**Comment by uBlock-user** [comment]
force update uBlock Filters list
