### ISSUE TITLE
[nsfw] streamtape.com [anti-adblock]

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#8003]
### URL(s) where the issue occurs

`https://streamtape.com/v/DMaLm4BAVOSklYa/chss1_mp4.mp4`

### Describe the issue

anti adblock. video streaming isn't working if UBO enabled

### Screenshot(s)

**https://i.postimg.cc/1XBXHy6q/2020-10-05-135301.png**

### Versions

- Browser/version: [FF 81.0.1 x64]
- uBlock Origin version: [1.30.0]

### Settings

Default , AdGuard Base, EasyList Cookie, Fanboy’s Annoyance, uBlock filters – Annoyances , IDN, MYS: ABPindo

**Comment by uBlock-user** [comment]
Test on default settings.

**Comment by exodius48** [comment]
> 
> 
> Test on default settings.

Works now. Anti-banner of Kaspersky Internet Security is the culprit..
