### ISSUE TITLE
How remove scroll event listener at DuckDuckGo?

### ISSUE THREAD

**Issue by KOSHACHIJ** [uBlockOrigin/uAssets#8006]
### URL(s) where the issue occurs

`https://duckduckgo.com`

### Versions
- Browser/version: Chromium 85
- uBlock Origin version: 1.30

I see strange scroll jump if quickly scroll up to the header with mousewheel.

Removing scroll event listener via browser console solves the problem.

Please tell me how remove scroll event listener with uBO?

`duckduckgo.com##+js(aeld, scroll)` doesn't help.

![2020-10-05_181302](https://user-images.githubusercontent.com/67644959/95101154-807b6480-073a-11eb-9955-63c8e70ed615.png)

**Comment by uBlock-user** [comment]
Questions/support is on reddit- `https://old.reddit.com/r/uBlockOrigin/`

**Comment by krystian3w** [comment]
Maybe this event is invisible for `aeld`.

https://www.reddit.com/r/uBlockOrigin/comments/ictc26/how_kill_change_title_by_blur_and_focus_on/ - also not see strict blur from "jQuery".
