### ISSUE TITLE
CPU-World unavoidable anti adblock

### ISSUE THREAD

**Issue by Qattos** [uBlockOrigin/uAssets#8007]
### URL(s) where the issue occurs

`https://www.cpu-world.com/index.html`

### Describe the issue

I'm trying to bypass CPU-World anti adblock but uBO is being detected, I tried using Nano Defender for uBO and followed its steps but it doesn't work either, I have even whitelisted CPU-World but for nothing, it's still detecting uBO and hiding CPU info, maybe something else I'm missing.

### Screenshot(s)

Just go to the website and you'll understand what I'm talking about.
### Versions

- Browser/version: [Firefox/81.0.1 (64-bit)]
- uBlock Origin version: [1.30.0]

### Settings

Nothing except following the guide for installing Nano Defender for uBO

### Notes

I just Googled bypassing CPU-World anti adblock and it led me to [here](https://github.com/uBlockOrigin/uAssets/issues/282), then figured those rules aren't working anymore, nothing else came up on Google and that's why I'm asking here.

The add-ons that I have on Firefox are:
uBlock Origin
HTTPS Everywhere
Decentraleys
ClearURLs
IDMan module
MEGA (cloud storage)
Google Translate
Worldwide radio
Nano Defender

**Comment by Qattos** [comment]
@uBlock-user 
Sorry to bother but why was this issue closed? is it fixed or can't be fixed?
The changes you made didn't work.

**Comment by mapx-** [comment]
I cannot reproduce the issue. Do I need an account ?

**Comment by Qattos** [comment]
@mapx- 
Nope, I don't have an account on it and still having this issue, what's bothering me is I wanna allow its ads but even disabling uBO doesn't resolve it.
See screenshot [here](https://pasteboard.co/JunUkaH.jpg).

**Comment by mapx-** [comment]
well, it's on your side.

Check `Enhanced Tracking Protection` (in privacy & security section in firefox) and disable those protections then test again

**Comment by uBlock-user** [comment]
Works fine, if `doubleclick.net` is blocked on DNS level, then uBO filter might fail to `redirect`.

**Comment by dimisa-RUAdList** [comment]
The problem is observed when opening in incognito mode.

Example: `https://www.cpu-world.com/CPUs/Xeon/Intel-Xeon%20E5-2650%20v2.html`

Fix: `@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/*/show_ads_impl_fy2019.js$domain=cpu-world.com`

**Comment by mapx-** [comment]
> The problem is observed when opening in incognito mode.

If you mean `anti adb` I cannot reproduce it FF / chrome

**Comment by dimisa-RUAdList** [comment]
Yes, I mean `anti adb`. For me, the problem is reproduced with Russian ip, Ukrainian ip, in any browser.

**Comment by mapx-** [comment]
Tried using russian / ukranian vpn ip but .. is seen as spamming address

**Comment by dimisa-RUAdList** [comment]
It's clear. One way or another, fix: `@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/*/show_ads_impl_fy2019.js$domain=cpu-world.com` - solves the problem.

**Comment by mapx-** [comment]
`https://pagead2.googlesyndication.com/pagead/managed/js/adsense/m202202010101/show_ads_impl_with_ama_fy2019.js?client=ca-pub-6693271402725072&plah=www.cpu-world.com`

Weird, I see a different (script) request blocked

**Comment by dimisa-RUAdList** [comment]
In my case, the entire request looks like this: `https://pagead2.googlesyndication.com/pagead/managed/js/adsense/m202202010101/show_ads_impl_fy2019.js`

I guess it's possible to unify the exception: `@@||pagead2.googlesyndication.com/pagead/managed/js/adsense/*/show_ads_*_fy2019.js$domain=cpu-world.com`

**Comment by BottledSoda** [comment]
@dimisa-RUAdList Could you post a screenshot?

**Comment by BottledSoda** [comment]
![image](https://user-images.githubusercontent.com/98048296/152650189-f66269ae-d659-4c5c-beae-b3f34c101fd4.png)

**Comment by dimisa-RUAdList** [comment]
https://i.imgur.com/H4KDAvI.jpg
https://i.imgur.com/qG7hUgq.jpg

**Comment by BottledSoda** [comment]
@dimisa-RUAdList check if you have ABP enabled

**Comment by dimisa-RUAdList** [comment]
No, the ABP is not enabled.

**Comment by BottledSoda** [comment]
Is it Geo / IP specific?

**Comment by BottledSoda** [comment]
is `https://www.cpu-world.com/cpu_world17.js` related to this?

**Comment by mapx-** [comment]
@dimisa-RUAdList ok, I added the exception

**Comment by dimisa-RUAdList** [comment]
@mapx- 
Excellent thank you!
