### ISSUE TITLE
Make this repo Hacktoberfest-compatible according to its new rules

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#8009]
### URL(s) where the issue occurs

`https://hacktoberfest.digitalocean.com/profile`

### Describe the issue

In the past 3-ish years, the Hacktoberfest has been an event where GitHub and DigitalOcean got together to nominally celebrate open-source and its contributors from all walks of life, though in practice it has been a giveaway of free T-shirts and stickers to the ~75,000 first GitHub users to submit 4 PRs to almost any repo.

However, Hacktoberfest in 2020 has been a colossal mess of proportions, with its rules being changed *twice* mid-event in the past 4 days, the most recent of which stipulated that PRs did not count towards the user's tally unless 1) the GitHub repo was tagged with `hacktoberfest`, or 2) every single pull request that did not seem like spam was labelled by the repo owners with `hacktoberfest-approved`, as per https://hacktoberfest.digitalocean.com/hacktoberfest-update

So if we as an adblocker community were to want to give contributors the chance to win free T-shirts, either of the 2 approaches above would have to be implemented by you guys. №1 would take ~20sec, presuming we find it to be worth the effort to continue to support Hacktoberfest after these very huge changes they've done now.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/22780683/95191188-a9e6cf80-07d0-11eb-936a-0aa7fb12b530.png)

### Versions

- Browser/version: Chrome 85.0.4183.121 x64
- uBlock Origin version: 1.30.1b5 + uBlock Origin Extra 2.88

### Settings

N/A

### Notes

I mostly only need the T-shirt reward so I can give it as an annual holiday gift to one of my siblings. I've never wanted to use branded T-shits with words on them myself.

I know that the uAssets repo favours submitting issue reports instead of PRs, so I won't push you all that hard on implementing this request of mine.

**Comment by uBlock-user** [comment]
@gorhill WDYT ?

**Comment by gorhill** [comment]
Nope.

https://news.ycombinator.com/item?id=24643894

Contributions from people who are genuinely interested in the projects in a long-term manner are welcome. I don't want pull requests for the sake of personal statistics.

**Comment by Hrxn** [comment]
*"And All I Got Was a Lousy T-Shirt."*
