### ISSUE TITLE
tune.pk

### ISSUE THREAD

**Issue by mat41997** [uBlockOrigin/uAssets#801]
![2017-10-29 16_57_48- animor tv animegataris - 01 720p by_mero _ tune pk](https://user-images.githubusercontent.com/5884000/32145610-cf0151bc-bccb-11e7-8af4-a11d2d0cf6ba.png)
https://tune.pk/video/7403651/animortv-animegataris-01-720pbymero

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.44
chrome 62.0.3202.75
win10 x64

**Comment by mapx-** [comment]
```
tune.pk###tpk-revenue-sharing-program
@@||tune.pk/js/ads.js
```

**Comment by uBlock-user** [comment]
`*/ads.js$script,important,redirect=noopjs,domain=tune.pk`

**Comment by KonoromiHimaries** [comment]
![2018-04-29-ust rukanime com 002 _ tune pk](https://user-images.githubusercontent.com/5884000/39407233-d0a6b148-4bc2-11e8-908e-036cf0e6da5e.png)

- video has stopped
- video has muted
- cookie alert

**Comment by KonoromiHimaries** [comment]
@mapx-

**Comment by KonoromiHimaries** [comment]
@uBlock-user
