### ISSUE TITLE
zazzle.com - zazzle.es

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#8010]
### URL(s) where the issue occurs

`https://www.zazzle.com/ `
`https://www.zazzle.es/ `

### Describe the issue

is this AntiAdblock? Captcha not working

### Screenshot(s)

![Captura2](https://user-images.githubusercontent.com/33556647/95237240-3b256880-0808-11eb-9efa-88d9c55dac19.png)

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.30.0]

### Settings

**Default** and: 

**spa, por: AdGuard Spanish/Portuguese
spa: EasyList Spanish** 

### Notes

after visit a few pages in `https://www.zazzle.es/ `  that screen appear , and the captcha for me not working

**Comment by llacb47** [comment]
It's perimeterx crap. Captcha working for me. Post logger please

**Comment by PIZZA90** [comment]
well... after doing the captcha is necessary refresh the page? when the captcha appeared not redirect me to the web page, when I clicked

 I cant reproduce now the captcha page🤔 I'm going to close this..

you can see the logs when I was on that captcha page:

![Captura3](https://user-images.githubusercontent.com/33556647/95239100-c69ff900-080a-11eb-9732-40a0481aec98.PNG)
