### ISSUE TITLE
New not blocked Ads on Facebook

### ISSUE THREAD

**Issue by Szewcson** [uBlockOrigin/uAssets#8011]
### URL(s) where the issue occurs

`https://www.facebook.com/`

### Describe the issue

Today Ads appears on the right upper corner of my FB

### Screenshot(s)

![Bez tytułu](https://user-images.githubusercontent.com/29232421/95326331-b20f3f80-08a2-11eb-85f0-0a130a124d29.jpg)

### Versions

- Browser/version: Firefox 81.0.1
- uBlock Origin version: uBlock Origin v1.30.0

### Settings
Default Polish settings
- Prevent WebRTC from leaking local IP address enabled
- Spam404 list added
- CZE, SVK: EasyList Czech and Slovak list added
- `https://hole.cert.pl/domains/domains.txt` list added

also using Privacy Badger and Facebook Container addons

**Comment by ghajini** [comment]
@uBlock-user no one will provide you Facebook account😝 ,you need to create one to diagnose

**Comment by dumbusernameidk** [comment]
Those ads should already be blocked by this Easylist filter:

`facebook.com##a[aria-label="Advertiser link"]`

**Comment by krystian3w** [comment]
France have ads: 

![obraz](https://user-images.githubusercontent.com/35370833/96143920-e8346b00-0f03-11eb-9476-c9c34f46cc34.png) |
--- |

@smed79  fyi! 

`##[aria-label="Lien de l’annonceur"]`

Leftover witch Canadian French:

![obraz](https://user-images.githubusercontent.com/35370833/96144450-7872b000-0f04-11eb-9e53-e3dc97cd94d9.png) |
--- |


---

IMO issue need label `account required`, guest no have ads, also this is language specific if EasyList use someting like:

`facebook.com#?#a[aria-label="Advertiser link"]`

**Comment by krystian3w** [comment]
@Szewcson try:

```
##[data-pagelet="RightRail"] a[aria-label][rel*="nofollow"][role="link"]:not([href="facebook.com/"]):not([href^="/"]):upward(6)
```
