### ISSUE TITLE
samsung.com - download button not working

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#8012]
### URL(s) where the issue occurs

`https://www.samsung.com/es/support/smart-switch/`

### Describe the issue

I have been trying to download samsung **smart-switch**, but it does not start the download, it is more when I try to deactivate ublock origin, and I try to download the program, automatically uBO is activated again. (at least the icon of uBO turns red again)

i had to download it with _**microsoft edge**_, where i don't have adblocker installed

### Screenshot(s)

![Captura3](https://user-images.githubusercontent.com/33556647/95335824-23092400-08b0-11eb-8b25-649e95e34043.PNG)

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.30.0]

**Comment by PIZZA90** [comment]
the **CONSOLE**, and uBO off , when i click the button, a error appears, and _googleads_ still blocked for example..

![4](https://user-images.githubusercontent.com/33556647/95342075-50a59b80-08b7-11eb-8623-55ecaf13d211.PNG)

**error**:

`Mixed Content: The site at 'https://www.samsung.com/' was loaded over a secure connection, but the file at 'https://downloadcenter.samsung.com/content/SW/202007/20200713134355035/SmartSwitchPC_setup.exe' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.`


no issue with **microsoft edge**

**Comment by PIZZA90** [comment]
I have uninstalled **UBO**, and the problem continues 😭 nothing to do with the extension, I don't know what the problem will be.. maybe the browser or something. because with microsoft edge works well 😓

excuse me, it's my side's problem..

**Comment by llacb47** [comment]
Not a uBO problem, it happens in guest mode too (by design).

![image](https://user-images.githubusercontent.com/16567977/95344018-2b009e00-0887-11eb-9b8c-80dc94610c28.png)

`https://bugs.chromium.org/p/chromium/issues/detail?id=960819`

**Comment by llacb47** [comment]
@PIZZA90 just click `Keep`. Or install `HTTPS Everywhere` which may help.
