### ISSUE TITLE
US Bank homepage login form does not render

### ISSUE THREAD

**Issue by stephenliang** [uBlockOrigin/uAssets#8013]
### URL(s) where the issue occurs

`https://www.usbank.com`

### Describe the issue

1. Click red login button on the top right

Expected: Login form renders
Actual: Button turns to X but no login form renders

### Screenshot(s)

<img width="453" alt="Screen Shot 2020-10-07 at 9 14 49 AM" src="https://user-images.githubusercontent.com/538214/95358156-97769f80-087d-11eb-8eb4-68ec391ab63f.png">

### Versions

- Browser/version: Firefox 82.0b1 (64-bit)
- uBlock Origin version: uBlock Origin v1.30.0

### Settings

- Added Fanboy's Annoyances and uBlock Filters - annoyances (not sure if these came by default)

### Notes

Disabling uBlock fixes the issue

**Comment by mapx-** [comment]
test this filter

`@@||usbank.com/LoginModuleHelpers/$script,1p`

**Comment by stephenliang** [comment]
Filter fixes the issue, thank you!

**Comment by mapx-** [comment]
it will be fixed in easyprivacy list @ryanbr
