### ISSUE TITLE
tenki-yoho.com

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#8015]
### URL(s) where the issue occurs

`https://www.tenki-yoho.com/`

### Describe the issue

CNAME issue: the site broken by `||ziyu.net^$third-party` in EP:

### Screenshot(s)

![tenki-yohou1](https://user-images.githubusercontent.com/58900598/95580362-2d731b80-0a72-11eb-8116-7a88ee461f2b.png)

![tenki-yohou2](https://user-images.githubusercontent.com/58900598/95580371-2fd57580-0a72-11eb-9a83-2c9205330a1d.png)

### Versions

- Browser/version: Firefox 81.0.1
- uBlock Origin version: 1.30.2

### Settings

- Default + AGJPN

### Notes

Since it ranges over css, image, script, and frame only solution other than $cname will be
```
!#if env_firefox
@@||ziyu.net^$domain=tenki-yoho.com
!#endif
```
So far reproduced only with ISP DNS but haven't tested other than Cloudflare.

**Comment by gorhill** [comment]
I don't see the need to narrow the fix to Firefox. If the site requires `ziyu.net`, this is true for any browser. If ever the site un-cloak `ziyu.net`, than the site will start to break for Chromium as well.

**Comment by Yuki2718** [comment]
@gorhill Okay then I'll make the same issue in EasyList.

**Comment by uBlock-user** [comment]
> If the site requires ziyu.net, this is true for any browser

Does it on Chromium ? On Firefox it's only uncloaked as a CNAME.

**Comment by Yuki2718** [comment]
AFAICT I don't see requests to `ziyu.net` on Chromium.

**Comment by gorhill** [comment]
> Does it on Chromium ?

It does, you just don't see it because the browser can't uncloak.

**Comment by uBlock-user** [comment]
> It does, you just don't see it because the browser can't uncloak. 

Doesn't it just mean that it is bypassing the filtering of uBO because it can't uncloak  and since it's bypassing it in Chromium it will never require a whitelisting filter. This is how we have been fixing all CNAME issues till now, always restricting to Firefox.

**Comment by uBlock-user** [comment]
> It does, you just don't see it because the browser can't uncloak. 

I meant for everything else except CNAME. So doesn't it just mean that it is bypassing the filtering of uBO because it can't uncloak  and since it's bypassing it in Chromium it will never require a whitelisting filter. This is how we have been fixing all CNAME issues till now, always restricting to Firefox.

**Comment by gorhill** [comment]
> since it's bypassing it in Chromium it will never require a whitelisting filter

Just pointing out my opinion it's not worth to burden/clutter with `!#if env_firefox`, the site **needs** the resources from the 3rd-party domain no matter what. It's just "lucky" that Chromium does not block because it's lacking an API.

**Comment by Yuki2718** [comment]
I interpret the discussion as "Either will be fine" so will save my time to create the same issue.
