### ISSUE TITLE
Rule created for issue 311 breaks Google Form UI

### ISSUE THREAD

**Issue by olamotte** [uBlockOrigin/uAssets#8016]
### URL(s) where the issue occurs

https://www-onepick-opensocial.googleusercontent.com/gadgets/js/rpc.js?c=1&container=onepick
https://jira-frontend-static.prod.public.atl-paas.net/assets-brotli/vendor~748942c6.8e3d7b8ee9c36ae5af7b.8.js

### Describe the issue
It looks like 3rd party scripts are not allowed to be loaded anymore, which greatly impacts navigation libraries loaded from CDNs (cloudflare/cloudfront/google/atlassian)

### Versions

- Browser/version: Chrome Version 86.0.4240.75 (Official Build) beta (64-bit)
- uBlock Origin version: uBlock Origin v1.30.2

### Settings

Only added custom lists

### Notes

This issue seems due to faulty carriage return on Line 9501 of the list ublock-filters, as detected when tracing the issue through asset-viewer.html?url=ublock-filters

**Comment by ntowle** [comment]
This breaks a lot more than the Google Form UI. It's also breaking the login form for my bank, Reddit, etc.

It all traces back to this line:

`*$script,3p,denyallow=9xbud.com|disqus.com|disquscdn.com|jwpsrv.com|plyr.io|jsdelivr.net|twimg.com|twitter.com|fastly.net|fastlylb.net|jquery.com|hwcdn.net|hcaptcha.com|recaptcha.net|cloudflare.com|cloudflare.net|google.com|googleapis.com|g`

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/4a035b82942e64fa91478c7e0079eeca7b5f1ae7

It's a typo
````
Line 9508 // *$script,3p,denyallow=9xbud.com|disqus.com|disquscdn.com|jwpsrv.com|plyr.io|jsdelivr.net|twimg.com|twitter.com|fastly.net|fastlylb.net|jquery.com|hwcdn.net|hcaptcha.com|recaptcha.net|cloudflare.com|cloudflare.net|google.com|googleapis.com|g
Line 9509 // static.com,domain=9xbuddy.*
````
It should obviously only be one line with the filter
````
*$script,3p,denyallow=9xbud.com|disqus.com|disquscdn.com|jwpsrv.com|plyr.io|jsdelivr.net|twimg.com|twitter.com|fastly.net|fastlylb.net|jquery.com|hwcdn.net|hcaptcha.com|recaptcha.net|cloudflare.com|cloudflare.net|google.com|googleapis.com|gstatic.com,domain=9xbuddy.*

**Comment by okiehsch** [comment]
Already fixed with https://github.com/uBlockOrigin/uAssets/commit/82226c595a11b6562488cddfb7beb51e3151f4e0

**Comment by olamotte** [comment]
9 minutes were enough for unlucky me to grab the version and not refresh it for a whole day :| 
Thanks for the investigation and happy to hear it's already solved.

**Comment by krystian3w** [comment]
No work 9 minutes but 4 days (so possible reporoduce for few to `13.10.2020`).
