### ISSUE TITLE
vidlox.tv

### ISSUE THREAD

**Issue by mat41997** [uBlockOrigin/uAssets#802]
![2017-10-29 17_11_46-anime kekkai sensen beyond - odcinek 3 - kreskoweczki pl](https://user-images.githubusercontent.com/5884000/32145645-8c57a676-bccc-11e7-9705-167c7045ffe2.png)
`https://www.kreskoweczki.pl/kreskowka/100284/kekkai-sensen-beyond_odcinek-3`

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.44
chrome 62.0.3202.75
win10 x64

**Comment by gorhill** [comment]
This does not look like an ad to me. If I click that link, a new tab opens with the video as streamed by the video provider -- `vidlox.tv` (please mentions this sort of details next time, I had to spend time guessing how you got that page in your screenshot).

**Comment by mat41997** [comment]
@gorhill How do i can block this element? ublock not detect this.

**Comment by gorhill** [comment]
vidlox.tv##.dwnld

The element picekr does not work in iframes, so you have to cut and paste the iframe URL in the address bar and use the element picker from there.
