### ISSUE TITLE
joska.xyz

### ISSUE THREAD

**Issue by Toshiba1127** [uBlockOrigin/uAssets#8020]
### URL(s) where the issue occurs

`https://joska.xyz/p/hhrC6HRLR`

### Describe the issue

Needed to disable adblock in order to continue

### Screenshot(s)

![image](https://user-images.githubusercontent.com/64008639/95682325-e0fc1d00-0be4-11eb-9171-c81f34e13536.png)

### Versions

- Browser/version: Chrome 86.0
- uBlock Origin version: 1.30.2

### Settings

- Default

### Notes

Also boost countdown if no server-side check

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/84580704/120109743-726bcf80-c173-11eb-8991-b12f357e51ee.png)
