### ISSUE TITLE
walla.co.il - ads are back

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#8021]
Default settings + EasyList Hebrew.
More info: https://github.com/uBlockOrigin/uAssets/issues/7837 and https://github.com/easylist/EasyListHebrew/issues/343
I can reproduce after a couple of reloads or by keeping a tab open in the background for about 10 minutes.
Site is still messing with the element picker.

What do you suggest?

**Comment by uBlock-user** [comment]
try `walla.co.il##+js(set, Reflect.ownKeys, noopFunc)` and report back for any breakage.

**Comment by mapx-** [comment]
try also:

`walla.co.il##+js(aost, JSON, blob)`

**Comment by mapx-** [comment]
> try `walla.co.il##+js(set, Reflect.ownKeys, noopFunc)` and report back for any breakage.

does not work, tested in FF

**Comment by mapx-** [comment]
@IsraeliUser test for breakage too:

`walla.co.il##+js(aopr, Blob)`

**Comment by mapx-** [comment]
You could remove a lot on filters, for example:

```
walla.co.il##+js(abort-current-inline-script, btoa, upManager)
walla.co.il##+js(abort-on-property-read, TextDecoder)
walla.co.il##+js(abort-current-inline-script, decodeURIComponent, encodeURIComponent)
walla.co.il##+js(abort-on-property-write, upManager)
walla.co.il##+js(abort-current-inline-script, atob, TextDecoder)
```

**Comment by llacb47** [comment]
The same code that does the ads is responsible for the site removing the element picker (I think), make sure that is addressed too.

also make sure it works on `zahav.ru`

**Comment by uBlock-user** [comment]
Hebrew list now has `##+js(aopr, btoa)` seems that fixed it.

**Comment by uBlock-user** [comment]
`walla.co.il##+js(aost, Reflect, inlineScript)` works as expected, not seeing any breakage either.

**Comment by mapx-** [comment]
probably it's better for @IsraeliUser to use (`aost` is still .. experimental)

`walla.co.il##+js(aopr, Blob)`

**Comment by Yaron10** [comment]
Can you please try https://usaelections.walla.co.il/item/3391923?
The video is not available now.

Firefox 82 + uBO 1.30.4.

**Comment by mapx-** [comment]
yeah, is broken

add

```
walla.co.il#@#+js(abort-on-property-read, Blob)
walla.co.il##+js(aost, Object, blob)
```

@IsraeliUser

**Comment by Yaron10** [comment]
The video is working now, but I'm getting the "This page is slowing down your browser" banner.

![תמונה](https://user-images.githubusercontent.com/10229320/95861083-9eb01880-0d69-11eb-918f-52aacac478f6.png)

Thank you.

**Comment by mapx-** [comment]
test

```
walla.co.il#@#+js(aost, Object, blob)
walla.co.il##+js(aost, Reflect, blob)
```

@IsraeliUser it seems you have to replace the filter with the second 1

**Comment by Yaron10** [comment]
:+1: 
Thank you.

**Comment by IsraeliUser** [comment]
Sometimes I get commercials before the videos.
@Yaron10  Can you reproduce?
@mapx-  What do you suggest?
I don't know if it's related to the last commit.

**Comment by mapx-** [comment]
I tried here:
`https://usaelections.walla.co.il/item/3388944`

and other videos aside, no ad on my side

**Comment by Yaron10** [comment]
@IsraeliUser,

I don't use that site often.
Playing a few videos now, I did not get any commercials.
I'll try again later.

**Comment by IsraeliUser** [comment]
@mapx- 
Ads are back.
I can see them after keeping tabs open in the background for about 10 minutes.
Can you reproduce?

Race condition?

**Comment by llacb47** [comment]
Yep, I can see ads here `https://celebs.walla.co.il/item/3387207`

**Comment by mapx-** [comment]
test

`walla.co.il##+js(aost, Promise.resolve, injectedScript)`

**Comment by IsraeliUser** [comment]
@mapx- 
Ads are back...

**Comment by mapx-** [comment]
@IsraeliUser test these (first 2 to be removed from your list)

```
walla.co.il#@#+js(abort-on-stack-trace, Promise.resolve, injectedScript)
walla.co.il#@#+js(abort-on-stack-trace, Reflect, blob)
walla.co.il##+js(aost, Math.random, /computed|blob/)
```

**Comment by IsraeliUser** [comment]
@mapx- 
Ads are back.....

**Comment by mapx-** [comment]
Test:

chrome:
`walla.co.il##+js(aost, Math, injectedScript)`

FF:
`walla.co.il##^script:has-text(responseText)`

**Comment by IsraeliUser** [comment]
@mapx- 
Ads are back.

**Comment by llacb47** [comment]
I got ads a few times but I think it's the result of a race condition, nothing we can do. Are you getting the ads on every page? How are you loading it? Test links? Browser?

Try this filter: `walla.co.il##+js(aopr, googletag.cmd)`

**Comment by mapx-** [comment]
try @llacb47 filter, if breaks something test for breakage these ones:

for firefox:
`walla.co.il##^script:has-text((window)}catch)`

chrome:
`walla.co.il##+js(aost, Object, injectedScript)`
or
`walla.co.il##+js(aost, Object, blob)`
