### ISSUE TITLE
glav.su

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#8023]
Google Chrome 86.0.4240.75
uBlock Origin 1.30.2
default + RU AdList + uBlock filters - Annoyances

The rule `glav.su##+js(aopr, console.log)` (uBlock filters - Annoyances) - breaks the opening of spoilers.

Example: https://glav.su/forum/4/3858/5836194/#message5836194

**Comment by okiehsch** [comment]
Thx.
