### ISSUE TITLE
hdmovieplus.site

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8026]
### URL(s) where the issue occurs

`https://hdmovieplus.site/`

### Describe the issue

Popup ads

### Screenshot(s)

![IMG_20201012_163034](https://user-images.githubusercontent.com/20338483/95739403-6f85a280-0ca8-11eb-9df6-dd3b02503998.jpg)

### Versions

- Browser/version: Firefox A.
- uBlock Origin version: 1.30

### Settings

uBO's default settings
-

**Comment by ghajini** [comment]
There are still popups from random domains on chrome/firefox ....

`hdmovieplus.site##+js(acis, String.fromCharCode, btoa)` this doesn't work on firefox

**Comment by ghajini** [comment]
their sites
`https://300mbplus.mobi`
`https://300mbplus.space`

**Comment by mapx-** [comment]
@ghajini 

test these filters for breakages

```
*$script,3p,denyallow=ishort.in|wp.com|cdn77.org|facebook.com|facebook.net|fbcdn.net|instagram.com|disqus.com|disquscdn.com|jwpsrv.com|plyr.io|jsdelivr.net|twimg.com|twitter.com|fastly.net|fastlylb.net|jquery.com|hwcdn.net|hcaptcha.com|recaptcha.net|cloudflare.com|cloudflare.net|google.com|googleapis.com|gstatic.com,domain=300mbplus.*|hdmovieplus.*
||lutcdiimmeze.com^
||bcfabscdt.com^
```

**Comment by ghajini** [comment]
That works if there is already third party adblocking filter .....
Add this
`hdmovieplus.site,300mbplus.*##+js(nowoif)` 

Also add html filtering filter for firefox

**Comment by mapx-** [comment]
> That works if there is already third party adblocking filter .....

I don't understand this.

Do you still get popups after adding the filters above ?

**Comment by ghajini** [comment]
> > That works if there is already third party adblocking filter .....
> 
> I don't understand this.
> 
> Do you still get popups after adding the filters above ?

Okiehsch added this `||bruvwmrxudd.com^$3p`
That time issue was fixed for me on firefox android
Then I tested on opera /edge/firefox desktop, I get new 3rd party random ad request `lutcdiimmeze.com`
So on if new random 3rd party ad appears that will be taken care(defused) of by `hdmovieplus.*,300mbplus.*##+js(nowoif)`

That way I thinked....

**Comment by mapx-** [comment]
The filter above `*$script,3p,denyallow=...` takes care of all random crap.
