### ISSUE TITLE
https://www.viu.com/ott/ph/en-us/category/70/Asian-Movies

### ISSUE THREAD

**Issue by mykeb** [uBlockOrigin/uAssets#8027]
### URL(s) where the issue occurs

`https://www.viu.com/ott/ph/en-us/category/70/Asian-Movies`

### Describe the issue

 
The page is not showing the **Newest Episodes** thumbnails.

### Screenshot(s)

![Screenshot_2020-10-12 Asian Movies - Watch Online For Free](https://user-images.githubusercontent.com/59161287/95746353-3b6ea980-0cc9-11eb-82f5-8b41f047268e.png)
![Screenshot_2020-10-12 Asian Movies - Watch Online For Free(1)](https://user-images.githubusercontent.com/59161287/95746368-3f023080-0cc9-11eb-857b-94f536acb9bf.png)

### Versions

- Browser/version: Firefox/81.0.1
- uBlock Origin version: 1.30.2

### Settings

-Prevent WebRTC from leaking local IP addresses
-Block CSP reports
-AdGuard Annoyances
-uBlock filters – Annoyances

### Notes

I fixed it with @@||www.gstatic.com/firebasejs/7.17.0/firebase-analytics.js$script,domain=www.viu.com which is a filter from EasyPrivacy.

**Comment by mapx-** [comment]
waiting easyprivacy authors to add `viu.com` to 

`@@||gstatic.com^*/firebase-analytics.js$script,domain=999.md|audiomack.com|foreignaffairs.com|games.com|google.com`

**Comment by mapx-** [comment]
fixed 
https://github.com/easylist/easylist/commit/5496c116e09e42d5d93ad534b58236186c7c22bd

just update easyprivacy list
