### ISSUE TITLE
indavideo.hu

### ISSUE THREAD

**Issue by bandi88** [uBlockOrigin/uAssets#8028]
### URL(s) where the issue occurs

`https://indavideo.hu/video/A_fraszt_hozta_ra_a_denever`

### Describe the issue

This website detects the uBlock origin and does not let playing the video if UBO is on.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/23141180/95783304-dcf9f900-0cd1-11eb-97c7-a8aa8dcf2785.png)

### Versions

- Browser/version: Mozilla Firefox 78.3.0esr
- uBlock Origin version: v1.30.2

### Settings

Nothing special. Used with Google Opt-Out add-on (but problem also occurs if GOO is off).

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled.
