### ISSUE TITLE
eBay.fr displaying auction pictures for first 11 auctions. Blank pictures from 12th

### ISSUE THREAD

**Issue by wmarcad** [uBlockOrigin/uAssets#8029]
### URL(s) where the issue occurs

https://www.ebay.fr/sch/i.html?_ftrt=901&_sop=10&_sadis=200&_adv=1&LH_SALE_CURRENCY=0&ssPageName=STRK%3AMEFSRCHX%3ASRCH%7CSTRK%3AMEFSRCHX%3ASRCH&LH_SellerType=1&cmd=Blend%7CBlend&_fslt=1%7C1&_dmd=1&LH_LocatedIn=71&sltpriv=1&_ftrv=1&_from=R40&_nkw=%28synology%2Ccisco%2Csagane%2Cburster%2Ctroemner%2Cadret%2Caoip%2Cjbc%2Cweidmuller%2Cweidm%C3%BCller%2Cnec+mt*%2Cmicromega%2CEtamag*%2CEtameuse%2Ccif%2Ckjaer%29+-tee+-shirt+-femme+-stade+-robe+-pantalon+-jeans+-jean+-kid+-homme+-trench+-connecteur+-chemise+-panini&_sacat=0&_fosrp=1

https://www.ebay.fr/sch/i.html?_from=R40&_nkw=%28arium%2Cpm3632%2C%22pm+3632%22%29&_in_kw=1&_ex_kw=mayer+sartorius+wallet+1915+lily+aqua+canvas+hair+armada+pills+whale+toy+cpa+weather+bumper&_sacat=0&_udlo=&_udhi=&_ftrt=901&_ftrv=1&_sabdlo=&_sabdhi=&_samilow=&_samihi=&_sadis=15&_stpos=76280&_fsradio2=%26LH_PrefLoc%3D1&_sargn=-1%26saslc%3D2&_salic=71&LH_SubLocation=1&_fss=1&_fsradio=%26LH_SpecificSeller%3D1&_saslop=2&_sasl=mrlousstuff%2Cparts_monster&_sop=10&_dmd=1&_ipg=100&_fosrp=1

https://www.ebay.fr/sch/i.html?LH_PrefLoc=3&_ftrt=901&_fsradio=%26LH_SpecificSeller%3D1&_udlo=100&_sop=10&_sadis=15&_udhi=600&_mPrRngCbx=1&_stpos=76280&_saslop=2&_fss=1&_dmd=1&_sasl=phs-electronic%2Cersazza&_ipg=100&_ftrv=1&_from=R40&_nkw=dell+%287050%2C7060%2C7070%2C7080%29+-pompe+-filtre+-roue+-batterie+-febi+-0y949p+-akku&_sacat=0&_fosrp=1

### Describe the issue

 

Good day, strange behaviour that appeared 1 or two weeks ago: any browser-recorded recorded search from https://www.ebay.fr displays no pictures for some auctions. What is extremely strange is that everything works fine for first 11 auction listings, but from 12th listing onwards, there is no picture displayed with auction.
Displaying next page gives exact same result.

### Screenshot(s)

Not attached, since the three examples speak for themselves.

### Versions

- Browser/version: Chrome x64, version 85.0.4183.121 
- uBlock Origin version: 1.30.2
- uBlocl Origin extra version : 2.88

### Settings

-None. Disabling uBlock Origin on ebay.fr solves the issue.

**Comment by okiehsch** [comment]
Does
`@@||ir.ebaystatic.com/pictures/aw/pics/s_1x2.gif$image,domain=ebay.fr`
work for you?

**Comment by llacb47** [comment]
Love to block a harmless and necessary gif in the name of privacy :\

![image](https://user-images.githubusercontent.com/16567977/95796964-3d7e3b80-0cbc-11eb-987b-cb7fd7c2ec0c.png)

![image](https://user-images.githubusercontent.com/16567977/95796999-5a1a7380-0cbc-11eb-9028-f28222db9dc9.png)
