### ISSUE TITLE
https://safelinkconverter.com/js/safelinkconverter.js

### ISSUE THREAD

**Issue by DNx5** [uBlockOrigin/uAssets#803]
### URL(s) where the issue occurs

`https://safelinkconverter.com/js/safelinkconverter.js`

### Describe the issue

It contains crypto-loot mining scripts & causing to RAM usage grows over time. I am not sure if its okay to block the entire scripts.

### Screenshot(s)
-

### Versions

- Browser/version: Chrome 61.0.3163.100 (Official Build) (64 bit)
- uBlock Origin version: 1.14.12

### Settings

- Default

**Comment by okiehsch** [comment]
FYI:
**URL(s) where the issue occurs,** i.e. a link to a site that uses the script for the purpose of mining not the script itself.

I found one: `http://www.infosaget.com`

**Comment by SMed79** [comment]
@okiehsch Should be `||safelinkconverter.com^$third-party` ?

```
http://plusmusic.me/
https://safelinkconverter.com/js/epub.js

http://www.miuitutorial.com/
https://safelinkconverter.com/js/owndomain.js

http://www.xfullgames.com/
http://safelinkconverter.com/js/wp_plugin.js

http://www.ketabfm.com/
https://safelinkconverter.com/js/safelinkconverter.js
```

**Comment by okiehsch** [comment]
Yes, `||safelinkconverter.com^$script,third-party`  seems to be the apropiate fix, thanks for the links.
