### ISSUE TITLE
vanillaereward.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#8034]
### URL(s) where the issue occurs

`https://www.vcdelivery.com/Cert/T2/cert_MyCertificate.aspx?BCNID=xxxxxxxxxxxxxxxxxxxxxxxxx`
which should redirect to
`https://www.vanillaereward.com/VanillaeRewards/loginDetails.html?tx_transdata=xxxxxxxxxxxxxxxxxxxxxxxxxxx&tx_transdataiv=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
but doesn't.

### Describe the issue

Page won't load properly.

### Notes

`@@||prod01.kaxsdc.com/collect/sdk$xhr,domain=vanillaereward.com`
Let me know if you would like me to test a different rule to confirm if it fixes it or not. I cannot send the actual URL used to test this for obvious reasons.

**Comment by mapx-** [comment]
What filter is triggered ?

`/collect/sdk?`  ?

**Comment by terrorist96** [comment]
`||kaxsdc.com^$3p`

**Comment by terrorist96** [comment]
Actually, I can send you the URL since I've depleted the gift card. Check your email.

**Comment by mapx-** [comment]
ok, I notified EP authors @khrin @ryanbr

**Comment by okiehsch** [comment]
Fixed in EasyPrivacy.
