### ISSUE TITLE
lubin.pl (breakage)

### ISSUE THREAD

**Issue by gargul05** [uBlockOrigin/uAssets#8036]
### URL(s) where the issue occurs

`https://www.lubin.pl/`

### Describe the issue

site breakage, caused by this filter from EasyList `||ezoic.net^$third-party`

### Screenshot(s)

<details not-open>
<summary>with EasyList enabled</summary>

![Screenshot_2020-10-15 Lubin - Portal Miasta Oficjalny portal miasta Lubin 1](https://user-images.githubusercontent.com/72875495/96120382-b5cc4300-0eee-11eb-88d5-82cfa82a73b7.png)

</details>

<details not-open>
<summary>without the bad filter</summary>

![Screenshot_2020-10-15 Lubin - Portal Miasta Oficjalny portal miasta Lubin2](https://user-images.githubusercontent.com/72875495/96120425-c54b8c00-0eee-11eb-9473-6ce8e5988ef0.jpg)

</details>

### Versions

- Browser/version: FF 81.0.2
- uBlock Origin version: 1.30.5b1

### Settings

-

**Comment by bug-rules** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/17353
