### ISSUE TITLE
history.com anti-adblock

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#804]
### URL(s) where the issue occurs

`https://www.history.com/news/history-lists/7-things-you-might-not-know-about-the-u-s-supreme-court`

### Describe the issue

Anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/32196998-ff9894fc-bd98-11e7-9322-ca08e0e35520.png)

**Comment by mapx-** [comment]
`@@||mssl.fwmrm.net/p/aetn_live/AdManager.js$script,domain=history.com`

**Comment by terrorist96** [comment]
Seems like it's already been fixed after forcing an update.

**Comment by okiehsch** [comment]
Does
`||mssl.fwmrm.net/*/AdManager.js$script,redirect=noopjs,domain=history.com`
work for you?

**Comment by mapx-** [comment]
yep, seems working fine

**Comment by terrorist96** [comment]
Yep. Thanks

**Comment by terrorist96** [comment]
@okiehsch easylist and peter lowe cause the anti-adblock to appear again.
