### ISSUE TITLE
pixiv.net (ad placeholder cleanup)

### ISSUE THREAD

**Issue by paperclip-dayo** [uBlockOrigin/uAssets#8041]
### URL(s) where the issue occurs

`https://www.pixiv.net/artworks/*`
Example: `https://www.pixiv.net/artworks/84998112`

### Describe the issue

Clicking the bookmark button (heart) slides down a frame below the image with ad banner, UBO removes the banner but doesn't prevent an ad frame from being shown as an empty placeholder. Requires pixiv account (free).

### Screenshot(s)

![example](https://user-images.githubusercontent.com/69221940/96255956-7a9a4480-0fc0-11eb-95e2-32be9bbfc59d.jpg)

### Versions

- Browser/version: Edge 87.0.664.8
- uBlock Origin version: v1.30.5b1

### Settings

All "Ublock" filters + adguard base

### Notes

This has been an issue for quite a long time with vanilla UBO after pixiv made some UI changes (for the 100th time) but I've used NanoContrib filters to deal with empty placeholders. Since Nano project has been sold and turned into malware, it'd be nice to have some of its placeholder fixes incorporated into UBO.
Relevant filter list: `https://github.com/NanoAdblockerLab/NanoContrib/blob/master/dist/placeholder-buster.txt`
Currently using this part of the filter list as my custom filters deals with the placeholder issue but it might be worth reviewing in case there's redundant code or a better solution available before incorporating it into UBO filter list:
```
pixiv.net###js-mount-point-header.with-ad:style(min-height: 0px !important;)
pixiv.net###root > header + div + div:not(:has(a)):not(:has(img))
pixiv.net##.ads-top-info
pixiv.net##.area_new:not(:has(.area_title))
pixiv.net##.sc-AykKF:style(padding-bottom: 0px !important;)
pixiv.net##a[href$="=work_detail_remove_ads"]:upward(3)
pixiv.net##div:has(:scope > div > iframe:not([src])):matches-css(padding-bottom: 56px)
pixiv.net##iframe[height="520"]:not([src]):upward(1)
pixiv.net##iframe[height="60"]:upward(1)
pixiv.net##iframe[height="90"]:upward(1)
pixiv.net##li[size="2"][offset="1"]
```

**Comment by uBlock-user** [comment]
Out of the list, these 4 are getting hits in uBO --

```
pixiv.net##a[href$="=work_detail_remove_ads"]:upward(3)
pixiv.net##div:has(:scope > div > iframe:not([src])):matches-css(padding-bottom: 56px)
pixiv.net##iframe[height="60"]:upward(1)
pixiv.net##iframe[height="90"]:upward(1)
```

Do these 4 only work for you ?

**Comment by paperclip-dayo** [comment]
I tried saving random pics with just these 4 rules in my custom filters and it works randomly, sometimes ad placeholder isn't shown while other times it pops up, even on the same illustration page so it doesn't work all the time.
Straight up blocking an element gives a rule like this: 
`www.pixiv.net##.eFqYrE.sc-185y4-0`
But anything past ## is randomly generated every time.

**Comment by mapx-** [comment]
for that big placeholder (after clicking the heart button), try and see if breaks something

`pixiv.net##+js(norafif, /^/)`

**Comment by paperclip-dayo** [comment]
This one breaks the "recommended images" strip that also slides down when the like button is pressed (below the ad frame).
I also forgot that instead of the under image ad frame there's also an ad frame that can pop up between the image tag list and uploader's other works preview strip.
I've messed around the UBO DOM inspector and found that blocking these two elements gets rid of both ad frames:
```
www.pixiv.net##div#root > div > div.sc-1nr368f-0.kCKAFN > div.sc-1nr368f-1.zgsQC > div.sc-1nr368f-3.iHKGIi > main.sc-1nr368f-6.ertGlR > section.sc-171jvz-1.sc-171jvz-2.bLzALD > div.sc-171jvz-0.ketmXG > div.sc-1yvhotl-2.hGipVQ > div.sc-185y4-0.eFqYrE
www.pixiv.net##div#root > div > div.sc-1nr368f-0.kCKAFN > div.sc-1nr368f-1.zgsQC > div.sc-1nr368f-3.iHKGIi > main.sc-1nr368f-6.ertGlR > section.sc-171jvz-1.sc-171jvz-2.bLzALD > div.sc-1yvhotl-0.cRkQiK > div.sc-1yvhotl-1.bEDiSv
```
Although I'm not sure if this is a permanent solution or names will be scrambled by some script later due to how they look.

**Comment by Yuki2718** [comment]
@DandelionSprout and I are responsible for pixiv entries of Contrib filters. While I don't use pixiv myself (so haven't click buttons, will test later), I don't see placeholders with rules essentially the same as Contrib.  I'm pretty sure there's no need to use random-looking classes. OTOH they injects some placeholder conditionally.

@uBlock-user 
>
> Out of the list, these 4 are getting hits in uBO --
> Do these 4 only work for you ?

You meant "no hits"? To me there two lines looks conflicting but as I'm non-native in English am not sure.

**Comment by Yuki2718** [comment]
The main page:

![pixiv1](https://user-images.githubusercontent.com/58900598/96322104-c1d11580-1052-11eb-931c-539196e2f58d.png)

Turned out two filters targets the same, my bad. Now I think `pixiv.net##iframe[width="728"][height="90"]:upward(2)` may be better.

Another placeholder on the main page:

![pixiv2](https://user-images.githubusercontent.com/58900598/96322219-2ee4ab00-1053-11eb-9f57-df8ef3c15033.png)

Again, `pixiv.net##iframe[width="300"][height="250"]:upward(2)` may be better.

**Comment by DandelionSprout** [comment]
As much as I fully support carrying over entries from Nano Placeholder Buster as a whole (and not just for Pixiv), it'd be difficult for me to comment on individual Pixiv entries, due to the elements they match being spread broadly across the entire site.

**Comment by Yuki2718** [comment]
But I take it a good chance. Like you, I haven't reviewed rules.
Dashboard:

![pixiv3](https://user-images.githubusercontent.com/58900598/96322490-39ec0b00-1054-11eb-9a37-c7710512758a.png)

Turned out `pixiv.net##div:not(.submit-area):has(:scope > iframe:not([src]))` is likely to be obsolete. `pixiv.net##iframe[name="dashboard_home"]:upward(div[span="1"])` works and may be better.

**Comment by Yuki2718** [comment]
@paperclip-dayo Can you test with these only and report any missed placeholder back?
```
pixiv.net##iframe[name="500x500"]:upward(1)
pixiv.net##iframe[name="dashboard_home"]:upward(div[span="1"])
pixiv.net##iframe[width="300"][height="250"]:upward(2)
pixiv.net##iframe[width="468"][height="60"]:upward(1)
pixiv.net##iframe[width="728"][height="90"]:upward(2)
```

**Comment by paperclip-dayo** [comment]
> @paperclip-dayo Can you test with these only and report any missed placeholder or false positive back?

It seems to deal with the iframe below the picture and doesn't break anything obvious but album pages have this ad frame in a different spot and it doesn't get blocked. 
Open any page from rankings for example `https://www.pixiv.net/ranking.php` that has two or more images and press like or "see all" button to trigger the frame. Since this case also gets triggered by "see all" button it doesn't require pixiv account.
Example image `https://www.pixiv.net/artworks/85031644`

![example2](https://user-images.githubusercontent.com/69221940/96335861-353f4b00-1084-11eb-8030-498963059824.jpg)

**Comment by uBlock-user** [comment]
if you add them all in uBO(all the ones you listed), do they work as expected ?

**Comment by paperclip-dayo** [comment]
These ones from the OP?

```
pixiv.net###js-mount-point-header.with-ad:style(min-height: 0px !important;)
pixiv.net###root > header + div + div:not(:has(a)):not(:has(img))
pixiv.net##.ads-top-info
pixiv.net##.area_new:not(:has(.area_title))
pixiv.net##.sc-AykKF:style(padding-bottom: 0px !important;)
pixiv.net##a[href$="=work_detail_remove_ads"]:upward(3)
pixiv.net##div:has(:scope > div > iframe:not([src])):matches-css(padding-bottom: 56px)
pixiv.net##iframe[height="520"]:not([src]):upward(1)
pixiv.net##iframe[height="60"]:upward(1)
pixiv.net##iframe[height="90"]:upward(1)
pixiv.net##li[size="2"][offset="1"]

```
Yeah, they seem to clean up both iframes properly.

**Comment by uBlock-user** [comment]
@Yuki2718 If you want to add some improvements, feel free to open a PR.

**Comment by Yuki2718** [comment]
Yeah, I could reproduce what @paperclip-dayo mentioned:

![pixiv](https://user-images.githubusercontent.com/58900598/96338922-2bd9d100-10cc-11eb-9355-a5d613104cea.png)

Replacing `##iframe[name="500x500"]:upward(1)` with `##iframe[width="500"][height="520"]:upward(1)` will be enough, only reason I used `name` is I thought it's less popular banner size than others. At the ranking page I confirmed `###js-mount-point-header.with-ad:style(min-height: 0px !important;)` works:

![pixiv3](https://user-images.githubusercontent.com/58900598/96338965-778c7a80-10cc-11eb-8634-939b59b0640f.png)

I also spotted yet another PH not covered by any filters posted at upload page:

![pixiv2](https://user-images.githubusercontent.com/58900598/96338979-88d58700-10cc-11eb-8ee9-7bb92b69962a.png)

The reason I prefer `:upward()` in this case is that it's more efficient (the minimal nodes to evaluate procedural) and also more generic (fewer rules to cover all), which I missed when PRed to Contrib. I'll make a PR.

**Comment by krystian3w** [comment]
#8048

**Comment by krystian3w** [comment]
@Yuki2718 pixiv.net glitch: https://old.reddit.com/r/uBlockOrigin/comments/k5o3eq/ublock_makes_pixivnet_really_glitchy/geg2gz3/

**Comment by Yuki2718** [comment]
@krystian3w Fixed: https://github.com/uBlockOrigin/uAssets/commit/99f512fe43713fbfc094ec56c023a3561c6f24f2

**Comment by Yuki2718** [comment]
@krystian3w Fixed: https://github.com/uBlockOrigin/uAssets/commit/99f512fe43713fbfc094ec56c023a3561c6f24f2
