### ISSUE TITLE
Blank page on https://community.nothingmore.net/

### ISSUE THREAD

**Issue by mykeb** [uBlockOrigin/uAssets#8044]
### URL(s) where the issue occurs

https://community.nothingmore.net/

### Describe the issue

The page is blank after it finishes loading.

### Screenshot(s)

Firefox screenshots doesn't even work on the page.

### Versions

- Browser/version: Firefox/81.0.2
- uBlock Origin version: 1.30.4

### Settings

-Prevent WebRTC from leaking local IP addresses 
-Block CSP reports
-AdGuard Annoyances 
-uBlock filters – Annoyances

### Notes

A cosmetic filter from AdGuard Annoyances is causing the issue.

**Comment by okiehsch** [comment]
We only deal with issues caused by lists that are enabled by default.
You can open an issue here: https://github.com/AdguardTeam/AdguardFilters/issues
