### ISSUE TITLE
Quick amendment to the recent Pixiv stuff

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#8048]
### URL(s) where the issue occurs

`https://www.pixiv.net/en/users/13958102` (Replicable both with and without being logged on.)

### Describe the issue

`pixiv.net##iframe[width="728"][height="90"]:upward(2)`, which was very recently added to uAssets Main, breaks the initial page of artists' art archive pages.

(@Yuki2718?)

### Screenshot(s)

With login: 
![image](https://user-images.githubusercontent.com/22780683/96394222-b7815980-11c1-11eb-9495-049e2243578f.png)

Without login: 
![image](https://user-images.githubusercontent.com/22780683/96394184-a89aa700-11c1-11eb-8724-6224be6445b8.png)

### Versions

- Browser/version: Chrome 86.0.4240.75 x64
- uBlock Origin version: 1.30.5.6 + Extra 2.88

### Settings

![image](https://user-images.githubusercontent.com/22780683/96394128-89037e80-11c1-11eb-8cd0-84a2b0398178.png)

### Notes

None in particular.

**Comment by okiehsch** [comment]
You mean
`pixiv.net##iframe[width="728"][height="90"]:upward(2)`
was added, not an exception.

**Comment by DandelionSprout** [comment]
Oh, right. My amendment was maybe a bit *too* quick, in fact. 😅

**Comment by Yuki2718** [comment]
We need to check whether `pixiv.net##div[class^=sc-]:has(> div[style] > iframe[width="728"][height="90"])` covers all what the removed rule covered, but not sure if I can do it soon.

**Comment by krystian3w** [comment]
https://old.reddit.com/r/uBlockOrigin/comments/je0y76/pixiv_hiding_users_images_and_interaction/ - images look as breakage or this is outdated hidden placeholders?

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/8041

**Comment by krystian3w** [comment]
Breakage: https://old.reddit.com/r/uBlockOrigin/comments/jghjku/referrer_page_on_pixivnet_does_not_show_link_to/

maybe works this:

`pixiv.net##iframe[width="500"][height="520"]:upward(1):not(~ div:nth-child(2))`
based on https://github.com/uBlockOrigin/uBlock-issues/issues/612


> The user keeps in secret what  is opening, I do not know the portal and I help on the basis of what the uBO logger spit out and what the chrome devtools suggest.

**Comment by Yuki2718** [comment]
@krystian3w https://github.com/uBlockOrigin/uAssets/pull/8071

**Comment by krystian3w** [comment]
OK, I see page no have `body>div:first-child~div:nth-child(2)`.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/8041#issuecomment-737723258 - possible mark topic as sticky (opened)?
