### ISSUE TITLE
www.bild.de "Bild live"

### ISSUE THREAD

**Issue by TonyTough** [uBlockOrigin/uAssets#8049]
### URL(s) where the issue occurs

`https://www.bild.de`
-> BILD LIVE

### Describe the issue

"Bild Live" livestream does not work if "ublock Annoyances" filter is activated.

### Versions

- Browser/version: Firefox 81.0.2
- uBlock Origin version: 1.30.4

### Settings

default settings

### Notes

I think this filter causes the problem:
! https://github.com/uBlockOrigin/uAssets/issues/7518
!#if env_firefox
bild.de##+js(acis, document.querySelector, Adblocker)
bild.de##+js(set, Object.freeze, noopFunc)
!#endif

**Comment by mapx-** [comment]
@lain566 I commented `bild.de##+js(set, Object.freeze, noopFunc)`
