### ISSUE TITLE
globo.com

### ISSUE THREAD

**Issue by lfmnovaes** [uBlockOrigin/uAssets#805]
### URL(s) where the issue occurs
`http://blogs.oglobo.globo.com/lauro-jardim/post/ibope-lula-e-bolsonaro-na-frente.html`

### Describe the issue
Annoying subscribe popup to see the current content.

### Screenshot(s)
`https://i.imgur.com/g7UXw38.png`

### Versions

- Browser/version: Firefox 56.0.2 (64 bit)
- uBlock Origin version: 1.14.16

### Settings

- Only subscribed more filters than the default. `https://i.imgur.com/f8EGa73.png`

### Notes

It's possible to remove this current window with uBlock's Element Picker, but the scrollbar goes away.
Extracted from My Filters:
```
! 10/30/2017, 8:20:21 PM http://blogs.oglobo.globo.com/lauro-jardim/post/ibope-lula-e-bolsonaro-na-frente.html
blogs.oglobo.globo.com###login-barreira
```

**Comment by okiehsch** [comment]
`||experience.tinypass.com^$script,domain=globo.com` wrks on my end, this will not be included
in uBO-filters.

> We need to draw a line here: the purpose of uBO filters should not be to work around walls, unless the site is asking to disable the blocker. 
https://github.com/uBlockOrigin/uAssets/issues/322#issuecomment-287542113

If I disable uBO I still get the subscribe popup.
