### ISSUE TITLE
dropgalaxy.com

### ISSUE THREAD

**Issue by SeriousHoax** [uBlockOrigin/uAssets#8052]
### URL(s) where the issue occurs
`https://a2zapk.com/941798-truecaller-phone-caller-id-spam-blocking-chat-11-29-7-mod-lite-a2z.html`

### Describe the issue
Anti adblock warrning
 
Visit the page mentioned above. Then click "Go to download page" then "Download APK From Dropgalaxy". 
### Screenshot(s)

<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/29574622/96461545-53ed3f80-1246-11eb-8c5f-61718b0ca325.png)

</details><br/>
### Versions

- Browser/version: Chromium Edge 86, Firefox 81
- uBlock Origin version: 1.30.4

### Settings

Filters: Default built in uBlock Filters, EasyList, EasyPrivacy, Fanboy's Annoyances, Fanboy's Enhanced Tracking List

**Comment by JobcenterTycoon** [comment]
i can’t reproduce .. update your filter lists it got fixed a day ago https://github.com/uBlockOrigin/uAssets/commit/daa6f0d224a9d5ea14a5d97674d43895443ff148

**Comment by SeriousHoax** [comment]
> i can’t reproduce .. update your filter lists it got fixed a day ago https://github.com/uBlockOrigin/uAssets/commit/daa6f0d224a9d5ea14a5d97674d43895443ff148

You're right. Looks like it's related to Adguard DNS that I use. No problem with cloudflare. Sorry about it. I'll create an issue there instead. Closing it.
