### ISSUE TITLE
Anti-AdBlock paperzonevn.com

### ISSUE THREAD

**Issue by scryptio** [uBlockOrigin/uAssets#8053]
### URL(s) where the issue occurs

https://paperzonevn.com/

### Describe the issue

Anti-AdBlock detection. Can't get around that.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/35927526/96491456-914fce00-1242-11eb-9014-d636a128a779.png)

### Versions

- Browser/version: Google Chrome 86.0.4240.75 (Official Build) (64-bit)
- uBlock Origin version: 1.30.4

### Settings

- Don't think I made changes

### Notes

- Also running
  - uBlock Origin Extra
  - Privacy Possum
- Lists
  - uBlock filters 24,268 used out of 24,420
  - uBlock filters – Badware risks 876 used out of 887
  - uBlock filters – Privacy 99 used out of 120
  - uBlock filters – Resource abuse 100 used out of 117
  - uBlock filters – Unbreak 1,506 used out of 1,524
  - EasyList 192 used out of 70,242
  - EasyPrivacy 8 used out of 18,382
  - Fanboy’s Enhanced Tracking List 2 used out of 3,516
  - Online Malicious URL Blocklist 15,461 used out of 15,461
  - Anti-Facebook 48 used out of 68
  - Fanboy’s Annoyance 0 used out of 55,997
  - Fanboy’s Social 0 used out of 24,134
  - uBlock filters – Annoyances 3,631 used out of 3,643
  - Dan Pollock’s hosts file 13,783 used out of 14,540
  - MVPS HOSTS 7,636 used out of 9,513
  - Peter Lowe’s Ad and tracking server list 1,432 used out of 3,545
  - DEU: EasyList Germany 8,901 used out of 8,923
  - AakList (Anti-Adblock Killer) 0 used out of 0
  - Anti popads.net 7,403 used out of 11,929
  - EasyList without element hiding rules 34,635 used out of 34,650
  - Fanboy+Easylist-Merged Ultimate List 112,311 used out of 147,964
  - Malvertising filter list by Disconnect 2,709 used out of 2,735
  - Malware domains (long-lived) 3,196 used out of 3,196
  - Malware filter list by Disconnect 0 used out of 1
  - NoCoin Filter List 1,213 used out of 1,227
  - Prebake - Filter Obtrusive Cookie Notices 1,069 used out of 1,072
  - uBlock Filters Plus 626 used out of 639

Tried the following after some googling to no avail
```
@@||paperzonevn.com/js/wutime_adblock/ads.min.js$script,first-party
@@||paperzonevn.com/js/wutime_adblock/wutime_detect.min.js$script
||paperzonevn.com/js/wutime_adblock/*
```

**Comment by stephenhawk8054** [comment]
Another anti-adblock and countdown annoyance/nuisance (countdown paused when switching to other tabs, title changed to `[PAUSED]` when switching).

Steps:

1. Open in new Private Window/Incognito session
2. Scroll down to the bottom (important step)
3. Wait about 10s, an anti-adblock overlay appears
4. After bypassing anti-adblock, click on `CLICK TO GET` to start downloading
5. Switching to other tabs triggers the site to pause the countdown

URL:
`https://paperzonevn.com/attachments/spiderman-iron-su-rar.12306/`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/146320045-f839b566-2f28-4184-b016-dad4d944c852.png)

</details>

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.39.2
Firefox: 95
filterset (summary): 
  network: 78571
  cosmetic: 41037
  scriptlet: 16349
  html: 607
listset (total-discarded, last updated): 
  added: 
    VIE-1: 2282-2, 5m
  default: 
    ublock-filters: 30569-37, 5m
    ublock-badware: 3573-1, 5m
    ublock-privacy: 184-0, 5m
    ublock-abuse: 81-0, 5m
    ublock-unbreak: 1733-0, 5m
    easylist: 61827-588, 5m
    easyprivacy: 26499-488, 5m
    urlhaus-1: 7394-0, 5m
    plowe-0: 3690-3, 5m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 412
  launchFromSelfie: false
popupPanel: 
  blocked: 3
```
</details>

The code is in the script similar to:
`https://paperzonevn.com/js/xf/notice.min.js?_v=58eb44cc`

Proposed filters:

```
paperzonevn.com##+js(nostif, ads)
paperzonevn.com##+js(aeld, visibilitychange)
```
