### ISSUE TITLE
Broken live chat

### ISSUE THREAD

**Issue by gorhill** [uBlockOrigin/uAssets#8055]
### URL(s) where the issue occurs

    https://www.onecallinsurance.co.uk/

### Describe the issue

Live chat feature is broken. Click the orange Live Chat button at the top.

### Notes

I was notified by email of the breakage.

The issue is EasyPrivacy's `/stat.js?`, this blocks `https://onecall.whoson.com/stat.js?[...]`. Suggested exception filter: `@@||onecall.whoson.com/stat.js$xhr,1p`.

**Comment by gorhill** [comment]
cc @ryanbr

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ae9297ce9486c6879fef1e7a27733550697aeee8

**Comment by gorhill** [comment]
I think using `~thirdparty` was a good, this narrows quite a lot of the exception.
