### ISSUE TITLE
https://chan.sankakucomplex.com Crashes on Vivaldi and doesn't work on Brave with protections on (NSFW)

### ISSUE THREAD

**Issue by YamiryuuZero** [uBlockOrigin/uAssets#8058]
### URL(s) where the issue occurs

(NSFW)
`https://chan.sankakucomplex.com` 
### Describe the issue

Page works fine without adblocks on Vivaldi and Brave, but probelms are introduced when protections are turned on. On Vivaldi, the page crashes (whole page becomes grey with a monochromatic image of a dead bird to indicate the page has crashed), while the main page still works fine on Brave, but after clicking on a thumbnail, the corresponding page fails to load the proper image resulting in a default error template.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12602946/96610291-d838d480-12d1-11eb-94c8-bb8da9e19148.png)
![image](https://user-images.githubusercontent.com/12602946/96610335-e555c380-12d1-11eb-98f5-72a31f9ac27b.png)

### Versions

- Browser/version: Vivaldi | 3.4.2066.7 (Official Build) (64-bit)
                              Brave | Version 1.15.75 Chromium: 86.0.4240.99 (Official Build) (64-bit)
- uBlock Origin version: 1.30.4

### Settings

Default settings apply
-

### Notes

There isn't much to report. Turning the adblocker on crashes the page on Vivaldi and prevents large images from being loaded on Brave, but turning any sort of adblocking software off will result in the website working properly. I suspect the website has a custom adblock killer script, but I could not confirm or deny the existence of a single domain that triggers the crashes.

**Comment by mapx-** [comment]
No issue here on brave.
Are you using the default setup? no other additional list ?

**Comment by uBlock-user** [comment]
uBO cannot crash the browser itself as it's just HTML/JAVASCRIPT/CSS, so report the crash to the Vivaldi team.

**Comment by gwarser** [comment]
Are you blocking referer header? Some privacy protection add-ons?

**Comment by YamiryuuZero** [comment]
> Are you blocking referer header? Some privacy protection add-ons? Incognito/Private browsing?
> 
> This may cause wrong image (logo) being displayed.

Privacy Badger, Ghostery, HTTPS Everywhere and Pop Up Blocker for Chrome are all turned off. Issue persists - any sort of adblock prevents the website from working properly on my end.

**Comment by krystian3w** [comment]
Try fresh profile in Vivaldi with latest uBO?

**Comment by uBlock-user** [comment]
Does this happen without uBO too, like with Ghostery or any other content blocker ?
