### ISSUE TITLE
Unable to add items to cart while shopping on shoes.com

### ISSUE THREAD

**Issue by misc-activities** [uBlockOrigin/uAssets#8059]
### URL(s) where the issue occurs

`https://shoes.com`

### Describe the issue

 
When I have Peter Lowe's Ad and tracking server list enabled, I am unable to add items to cart. When I click on Add To Cart, nothing happens. When I disable the filter, everything works fine.

### Versions

- Browser/version: Firefox 82.0
- uBlock Origin version: 1.30.4

### Settings

-

**Comment by uBlock-user** [comment]
@misc-activities Enable Peter Lowe's list back and add `@@||tags.tiqcdn.com/utag^*/utag.js$script,domain=shoes.com` to my Filters.
