### ISSUE TITLE
Not blocking the anti-adblock on Citation Machine properly

### ISSUE THREAD

**Issue by rogersachan** [uBlockOrigin/uAssets#806]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

http://www.citationmachine.net/apa/cite-a-website

### Describe the issue

Their anti adblock is triggered, but is easily removed via the element zapper. The issue is that the numbers keep changing I don't know how to remove it permanently.

```
! 10/30/2017, 3:37:36 AM http://www.citationmachine.net/bibliographies/243450578?new=true
www.citationmachine.net###_cf941ff9-2e49-43e7-8b48-02541ecce7bc > span > div

! 10/30/2017, 3:38:18 AM http://www.citationmachine.net/items/new
www.citationmachine.net###_c6b0d2f2-490c-4e22-9aae-ee3c6d49abdf > span > div

! 10/30/2017, 3:38:26 AM http://www.citationmachine.net/bibliographies/243450578?new=true
www.citationmachine.net###_5a7002e4-7063-4f20-8e97-9fb1df6495fe > span > div

! 10/30/2017, 3:45:17 AM http://www.citationmachine.net/apa/cite-a-website/manual
www.citationmachine.net###_0217e987-88c9-483e-b414-9043db6d9d16 > span > div

! 10/30/2017, 3:46:19 AM http://www.citationmachine.net/bibliographies/243450578?new=true
www.citationmachine.net###_7b981d03-bbf9-4449-a89f-6e9f544b6529 > span > div

! 10/30/2017, 5:29:34 AM http://www.citationmachine.net/items/new
www.citationmachine.net###_f9382d9c-9a79-4599-9db5-81a7ee747883 > span > div

! 10/30/2017, 5:29:43 AM http://www.citationmachine.net/bibliographies/243450578?new=true
www.citationmachine.net###_8a570bc2-eb0e-4aea-9620-2339a3a22e79 > span > div

! 10/31/2017, 6:03:51 AM http://www.citationmachine.net/items/new
www.citationmachine.net###_e2ecd69b-f7d6-48bc-829d-7486ef337acf > span > div

! 10/31/2017, 6:03:57 AM http://www.citationmachine.net/bibliographies/243450578?new=true
www.citationmachine.net###_537ba3a6-2503-43f1-aa77-b0121243a9ba > span > div
```

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7173984/32218709-37bf523a-be02-11e7-9527-9e0d71cdd3db.png)

### Versions

- Browser/version: `61.0.3163.100 (Official Build) (64-bit) (cohort: Stable)`
- uBlock Origin version: uBlock Origin v1.14.12

### Settings

None

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by okiehsch** [comment]
Does
`citationmachine.net##script:inject(abort-on-property-read.js, canRunAds)`
work for you?

**Comment by terrorist96** [comment]
That works for me.
