### ISSUE TITLE
totalcar.hu

### ISSUE THREAD

**Issue by bandi88** [uBlockOrigin/uAssets#8061]
### URL(s) where the issue occurs

`https://totalcar.hu/magazin/velemeny/2020/10/21/kossuk_pszichologiai_vizsgalathoz_a_jogositvanyszerzest/`

### Describe the issue

This website has an anti ad-blocker script. 

### Screenshot(s)

![grafik](https://user-images.githubusercontent.com/23141180/96706855-6a56e080-1397-11eb-9ff0-3375ea36cdb8.png)

### Versions

- Browser/version: Mozilla Firefox 68.12.0esr (64-Bit)
- uBlock Origin version: 1.30.6

### Settings

Nothing special

**Comment by uBlock-user** [comment]
test on default settings + all other extensions disabled.

**Comment by bandi88** [comment]
The results are the same. :(
Please note: it seems, that this page uses the same anti-ad-blocking mechanism as the divany.hu (https://github.com/uBlockOrigin/uAssets/issues/7765 )

**Comment by okiehsch** [comment]
It's already fixed in uAssets and the regional hungarian list.

**Comment by bandi88** [comment]
Also totalcar.hu? The divany.hu is already on the list, that is sure.
But for me it seems, totalcar.hu not yet.

**Comment by uBlock-user** [comment]
Yes, both fixed and both are non-reproducible.

**Comment by okiehsch** [comment]
If I disable `uBO-filters` or the regional list I can reproduce your screenshot.
It is fixed.
The hungarian list includes
`divany.hu,totalcar.hu,totalbike.hu##+js(acis, document.head, currentScript.remove)`
that filter alone fixes the anti adblock detection.
@uBlock-user I think we can remove the filters in uAssets, tthe regionalfix is good enough.

**Comment by uBlock-user** [comment]
@okiehsch Yes, I was just going to recommend that. Having fixes in both lists doesn't make any sense.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/5fd7bc32c0f6b9e1af82c95c4fb1e11cf6ee9620

**Comment by uBlock-user** [comment]
`divany.hu` needs to be removed too.

**Comment by krystian3w** [comment]
Maybe race condition, how old you have CPU?

Also in Firefox try disable privacy protection embeded in Firefox:
```
about:preferences#privacy
```
