### ISSUE TITLE
Filecrypt Captchas blocked

### ISSUE THREAD

**Issue by MysteryIII** [uBlockOrigin/uAssets#8065]
### URL(s) where the issue occurs

```
https://www.filecrypt.cc/Container/ECF4A77D57.html
https://filecrypt.cc/Container/84A549C862.html
https://www.filecrypt.cc/Container/CA042DF33B.html
```

### Describe the issue

With uBlock Filters (default ones) activated no Captchas will be shown/loaded and therefore passing is not possible.

### Screenshot(s)

uBlock filters activated:
[![Bild filecryptnocaptchaw3jwn.png auf abload.de](https://abload.de/thumb/filecryptnocaptchaw3jwn.png)](https://abload.de/image.php?img=filecryptnocaptchaw3jwn.png)

(only) uBlock filters deactivated:
[![Bild filecryptcaptcha44jk9.png auf abload.de](https://abload.de/thumb/filecryptcaptcha44jk9.png)](https://abload.de/image.php?img=filecryptcaptcha44jk9.png)

### Versions

- Browser/version: Firefox 81.0.2
- uBlock Origin version: 1.30.6

### Settings

- Setup of Nano Defender
- Easylist and smoe other filter lis

### Notes

No other Filter list conflicts, just deactivating "uBlock filters" let Captchas load again.

**Comment by uBlock-user** [comment]
The admin is intentionally breaking the site for blocking his ads.

**Comment by uBlock-user** [comment]
Already fixed in https://github.com/uBlockOrigin/uAssets/commit/444a101106deb23e051579610ff79a2f34216d72

> There is no fine tuning possible?

We can do that, but the admin will match the filters so as to created a false positive just so we will allow his ads to load again and so this will continue. Anyway you don't need to worry about it, just report it again if they do it next time.

**Comment by MysteryIII** [comment]
I get it. Once again thank you and sorry for misplaced comment before.

**Comment by MysteryIII** [comment]
I just checked it: while Captcha is working again, the Click N Load button above links doesn't appear.

**Comment by uBlock-user** [comment]
> the Click N Load button above links doesn't appear.

Aren't those fake buttons when clicked lead to ad-servers ? Can you share a picture ?

**Comment by MysteryIII** [comment]
No they are actual useful. CnL is for directly sending links to JDownloader, while DLC is an encrypted file that conatains the links and is support by a few other Download Manager.

Thanks again for fixing this!

**Comment by MysteryIII** [comment]
Just wanted to report, that the CnL button is blocked again with current rules.
