### ISSUE TITLE
depend.com.au

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8066]
### URL(s) where the issue occurs

`https://www.depend.com.au/incontinence-products/female-products/depend-real-fit-regular-for-women`

### Describe the issue

clicking on `Buy now` as per screenshot below is broken due to peter lowes list

(`||viglink.com^` & `||skimresources.com^`)

### Screenshot(s)

https://user-images.githubusercontent.com/20338483/96881643-1d106700-149c-11eb-8356-5dcc7c0a2c2d.png

### Versions

- Browser/version: firefox 82
- uBlock Origin version: 1.30.4

### Settings

uBO's default settings
-

**Comment by uBlock-user** [comment]
> clicking on Buy now as per screenshot below is broken

clicking on **Buy now** takes me to `https://itrack.where-to-buy.co/wheretobuy/v1/WidgetClicks/?click=inserturlhere` for all the three buttons.

**Comment by uBlock-user** [comment]
![Capture](https://user-images.githubusercontent.com/21290713/96883031-8a70c780-149d-11eb-8b2c-e98b8643cc24.PNG)
![Capture2](https://user-images.githubusercontent.com/21290713/96883035-8cd32180-149d-11eb-8f4c-0574cc612ea8.PNG)

If you click on the magnifying glass, you will see the real URL, just click on it.

**Comment by ghajini** [comment]
it brings me here

https://user-images.githubusercontent.com/20338483/96882970-7b8a1500-149d-11eb-9c66-41638801afce.png

can you block tracking parameter while still retaining functionality of site

block is there for reason @pgl

**Comment by ghajini** [comment]
> If you click on the magnifying glass, you will see the real URL, just click on it.

Done
