### ISSUE TITLE
tio.ch redirecting pages

### ISSUE THREAD

**Issue by osoibol** [uBlockOrigin/uAssets#8068]
### URL(s) where the issue occurs

`https://www.tio.ch/`

### Describe the issue

 
any page visited from this website redirects to `https://www.tio.ch/adblock/redirect` if you don't deactivate uBlock.

### Versions

- Browser/version: Currently tested in Opera 71.0.3770.148 for Linux, but it happens in *ALL* browsers I've used so far
- uBlock Origin version: 1.30.4

### Notes

I've had this issue before with other sites but can't remember right now, my solution then was using Nano Defender, but, well, *you know what happened to it.*

**Comment by osoibol** [comment]
why is this issue closed? does that means it has been or will be fixed? new to this so I don't get how it works.

**Comment by okiehsch** [comment]
> @uBlock-user uBlock-user closed this in e5d1444 yesterday

That means that it was closed via the mentioned commit https://github.com/uBlockOrigin/uAssets/commit/e5d1444928fc0c8a228f988cc060e34f36db44ea

That commit named  "fix #8068" should solve your issue. I can't reproduce it anymore after updating the `uBO-filters` list.
The list auto updates once every 4 days, you can manually update any time.
If you don't know how to manually update a filter list.
https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-Filter-lists#update-now

**Comment by helioshk** [comment]
@uBlock-user 
Happens again, visiting the page redirects to https://www.tio.ch/adblock/redirect

**Comment by osoibol** [comment]
It's happening again. If you disable the adblocker, reload the page, and then enable the adblocker again and reload once more it works... really weird behavior...

**Comment by helioshk** [comment]
I can confirm the behavior which @osoibol describes.

**Comment by uBlock-user** [comment]
It's not new, force update whenever you see the anti-adblock redirect, it's an ongoing battle of attrition with them.
