### ISSUE TITLE
Websites guarded with blockadblock.com is not working

### ISSUE THREAD

**Issue by grande-mephistopheles** [uBlockOrigin/uAssets#8072]
### URL(s) where the issue occurs
`https://blockadblock.com`
`https://www.alltechnerd.com` (an example)

### Describe the issue

 
Websites that uses blockadblock.com for anti-adblock protection stops with the following screenshot.
### Screenshot(s)

![blockadblock](https://user-images.githubusercontent.com/58479925/96988230-9303e500-1513-11eb-973d-7f1c1b3ea03f.jpg)

### Versions

- Browser/version: Firefox 82.0 (64-bit)
- uBlock Origin version: uBlock Origin v1.30.6

### Settings

- All filters on (including region/languages) except *Dan Pollock’s hosts file* and *MVPS HOSTS*
- My own filter: youtube.com##.ytp-ce-element

### Notes

Platform: Linux Mint 20

**Comment by okiehsch** [comment]
**(an example)**

We need to know the websites to fix them.

**Comment by grande-mephistopheles** [comment]
thanks guys for the quick fix. :+1: haven't expected such a quick response. you are the best.

**Comment by uBlock-user** [comment]
Demo sites won't be fixed FYI, only examples such as above will be.

**Comment by mapx-** [comment]
maybe some guys are arriving from nano, they could add 

`*##+js(nosiif, visibility, 1000)`

**Comment by garry-ut99** [comment]
> ghost : `https://www.alltechnerd.com` (an example)

Permanent anti-adblock [SCREENSHOOT](https://github.com/uBlockOrigin/uAssets/assets/72945564/d5b42e10-59ce-407a-877e-c50471636941) :
- on both main page and subpages 
- on both Firefox and Opera (Chromium)

**Comment by garry-ut99** [comment]
> https://github.com/uBlockOrigin/uAssets#uassets : It is preferred to fix filter issues in EasyList. Any filters included in uBO's filter lists must use the [extended syntax](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#extended-syntax).

Strange, because I followed the official guidelines and already reported the ad placeholders separately to https://github.com/easylist/easylist/issues/17457, because they can be easily fixed in EasyList, and it's not a high-traffic website, but despite all this, it still has been fixed in uAssets.
