### ISSUE TITLE
rechtslupe.de

### ISSUE THREAD

**Issue by bandi88** [uBlockOrigin/uAssets#8075]
`
https://www.rechtslupe.de/verwaltungsrecht/heilpraktikererlaubnis-nur-fuer-die-ergotherapie-3119831`

### Describe the issue

This website has an anti-adblocker detector.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/23141180/97060101-aace7e00-1592-11eb-91a9-3083ecc3e13d.png)

### Versions

- Browser/version: Brave 1.15.72
- uBlock Origin version: 1.30.6

### Settings

Used with NanoDefender together.

**Comment by uBlock-user** [comment]
Not anti-adblock, the left modal is for users who want to use the site with ads and links to their GDPR. The right modal is for users who want to use the site ads free via their paid subscription option. 

You can use `rechtslupe.de##+js(nostif, dsgetCookie, 2000)` as a fix.

**Comment by bandi88** [comment]
> rechtslupe.de##+js(nostif, dsgetCookie, 2000)

Can You please add it to the EasyList?

**Comment by okiehsch** [comment]
EasyList does not add script injections and we have nothing to do with EasyList.
https://github.com/easylist/easylist/issues

**Comment by bandi88** [comment]
> rechtslupe.de##+js(nostif, dsgetCookie, 2000)

What if this would be added to "uBlock filters – Privacy" list? I think that place would be appropriate for this.

**Comment by uBlock-user** [comment]
> What if this would be added to "uBlock filters – Privacy" list?


> GDPR messages will not be addressed in uAssets.

**Comment by okiehsch** [comment]
Why? Like I said all trackers are blocked even if you click Einverstanden. It's nothing more than an annoyance and we don't fix GDPR modals as our readme clearly states,

**Comment by uBlock-user** [comment]
Feel free to report this Fanboy/Adguard annoyances tracker.

**Comment by uBlock-user** [comment]
Feel free to report this to Fanboy/Adguard annoyances tracker.

**Comment by krystian3w** [comment]
Fanboy have similar limitations as EasyList, you can block this with `csp`?

**Comment by uBlock-user** [comment]
Sure fanboy can with `rechtslupe.de##.dsoverlay`
