### ISSUE TITLE
Unable to cancel transactions in PayPal

### ISSUE THREAD

**Issue by misc-activities** [uBlockOrigin/uAssets#8077]
### URL(s) where the issue occurs

`
https://www.paypal.com/myaccount/transactions/`

### Screenshot(s)

When I have the 'uBlock filters - Privacy' filter enabled, I am unable to cancel a transaction. When I disable the filter, it works fine.

### Versions

- Browser/version: Firefox 82.0
- uBlock Origin version: 1.30.6

### Settings

I have enabled 'Prevent WebRTC from leaking local IP addresses'.

**Comment by mapx-** [comment]
- test using uBO default setup
- open the uBO logger, go to the page in trouble, select in the logger page only the blocked items, post them here (as 1 or more screenshots)
(be sure there are **no other blocking extensions enabled**)

**Comment by misc-activities** [comment]
Nevermind. It started working again somehow.
