### ISSUE TITLE
Outbrain redirect rule breaking vice.com

### ISSUE THREAD

**Issue by reforget-id** [uBlockOrigin/uAssets#8078]
### URL(s) where the issue occurs

```
https://www.vice.com/en/article/5dpmkx/hit-boy-is-tired-of-making-money-for-his-label
https://www.vice.com/id/article/4ayjd3/sejarah-tawuran-pelajar-stm-boedot-yang-menguasai-jabodetabek
```
### Describe the issue

`||widgets.outbrain.com/outbrain.js$script,redirect=widgets.outbrain.com/outbrain.js`

This rule in `uBlock Filters - Privacy` breaking vice.com articles in my device (Kiwi Browser Android). But in Opera, this only happens if i perform force refresh (shift + f5). It seems fine if i don't use `uBlock Filters - Privacy` list and only block outbrain without redirection, so i assume that happens because the redirection.

### Screenshot(s)

![vice error](https://user-images.githubusercontent.com/58993868/97080430-5fb17b00-1625-11eb-8da1-d78cd6aeb5b8.png)

### Versions

- Browser/version: Kiwi Browser (Android) / Git201022 (Chromium 77)
- uBlock Origin version: 1.30.6

- Browser/version: Opera Browser (Windows) / v68 (Chromium 81)
- uBlock Origin version: 1.30.4

### Settings

N/A

### Notes

So i make this rule to fix this issue and it works fine :

`||widgets.outbrain.com/outbrain.js$script,redirect=empty,domain=www.vice.com`

Redirecting to empty resource but keep using `uBlock Filters - Privacy` list.

But i'm considering if there is a better solution, like modifying the rule in `uBlock Filters - Privacy` to :

`||widgets.outbrain.com/outbrain.js$script,redirect=widgets.outbrain.com/outbrain.js,domain=~www.vice.com`

I have tried it and it works fine.

**Comment by reforget-id** [comment]
I would like to update this filter. It seems that the redirect behavior on uBlock Origin 1.32.0 has changed. And causes these two filters to conflict. 

`@@||widgets.outbrain.com/outbrain.js$script,redirect-rule,domain=www.vice.com`

I think this is better because the main problem of this issue is redirect directives.

**Comment by uBlock-user** [comment]
I don't see outbrain used on vice anymore as per the logger.

**Comment by reforget-id** [comment]
It still, try Shift + F5

![Screenshot (186)](https://user-images.githubusercontent.com/58993868/103208870-4209d600-4934-11eb-9daf-4717754b0d3e.png)

**Comment by uBlock-user** [comment]
url ? I tried existing urls posted here, don't see it there.

**Comment by reforget-id** [comment]
Really ? 
On my browser (Opera), this only happens when you reload without cache (shift + F5). But on my device (Kiwi browser android), this always happens when you reaload even without clearing the cache. 

![Screenshot (186)](https://user-images.githubusercontent.com/58993868/103210288-d32e7c00-4937-11eb-9f24-ef63e3282e66.png)

But my point is, as you can see, it redirect to `widgets.outbrain.com/outbrain.js` not to `empty`  even it specify the domain. It worked fine on 1.31.0 but not 1.32.0.

**Comment by uBlock-user** [comment]
I can only reproduce the issue if I _allow_ some third-party domains which are blocked by default filter lists. I suspect you're not default settings. You should test on default settings.
