### ISSUE TITLE
planetminecraft.com

### ISSUE THREAD

**Issue by mat41997** [uBlockOrigin/uAssets#808]
![2017-10-31 19_47_37-topplay pl minecraft server](https://user-images.githubusercontent.com/5884000/32243129-d81fd44e-be74-11e7-974e-ebc65ea14dba.png)
https://www.planetminecraft.com/server/topplay-pl/

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.48
chrome 62.0.3202.75
win10 x64

**Comment by gorhill** [comment]
Blocking `imgur.com` could break legitimate stuff I supposed given how often `imgur.com` is used to post images.

It seems `planetminecraft.com##.sweet` takes care of that ad and other on the same page. I will add if feedback is positive.

**Comment by mapx-** [comment]
page removed, however testing other pages it's not always imgur hosting.
it seems this div is always there:
`planetminecraft.com###box_large_square_above`

normal filter otherwise the site doesn't need special filters, so it could be used as custom filter

**Comment by Daxy7** [comment]
new annoyance: 5 second wait to download: nano-sib can work but look for specific script to append at the end cuz there's a lot, and to minimize breakage
```
https://www.planetminecraft.com/project/resource-pack-test-world-1-17/download/worldmap/
```
```
planetminecraft.com##+js(nano-sib)
```

**Comment by Daxy7** [comment]
@JobcenterTycoon Sorry, but can you take a look at this?

**Comment by JobcenterTycoon** [comment]
Its fine enough.
