### ISSUE TITLE
jakselnews-pikiran--rakyat-com.cdn.ampproject.org

### ISSUE THREAD

**Issue by realodix** [uBlockOrigin/uAssets#8080]
### URL(s) where the issue occurs

`https://jakselnews-pikiran--rakyat-com.cdn.ampproject.org/c/s/jakselnews.pikiran-rakyat.com/gaya-hidup/amp/pr-61736153/lakukan-tips-ala-jepang-ini-untuk-mencari-kucing-hilang`

### Screenshot(s)

![cats](https://user-images.githubusercontent.com/1314456/97101706-166b3500-16d2-11eb-80fe-b412668a54c0.jpg)

### Versions

- Browser/version: Firefox 82
- uBlock Origin version: uBlock 1.30.7b2

### Settings

- Default

**Comment by mapx-** [comment]
try

`jakselnews-pikiran--rakyat-com.cdn.ampproject.org##center:has-text(Adv)`

You could report it here:
https://github.com/ABPindo/indonesianadblockrules/issues

@gmarcher

**Comment by realodix** [comment]
Thank you
