### ISSUE TITLE
whathifi.com anti-adblock script blocks viewing

### ISSUE THREAD

**Issue by xelaseer** [uBlockOrigin/uAssets#8084]
`www.whathifi.com
`
It appears the above website has an anti-adblocker that will run after several seconds reading an article, and redirect to an anti-adblocker landing page that prevents further reading.

For example, if you go to `https://www.whathifi.com/au/reviews/parasound-zphono-xrm` with uBlock Origin enabled, it will redirect you to `https://www.whathifi.com/cc.html`.

- Browser/version: Firefox 84 Nightly - 20201025
- uBlock Origin version: 1.30.6

All filter lists are enabled.  I have also enabled all uBlock Origin settings under the Privacy heading.

**Comment by uBlock-user** [comment]
Test on default settings.

**Comment by xelaseer** [comment]
Just did so. I reset uBlock Origin to its default settings and was able to reproduce.

**Comment by xelaseer** [comment]
Scratch that. Sorry it was uMatrix causing the issue.

**Comment by PIZZA90** [comment]
**offtopic and nothing important:**

`@@||hawk.whathifi.com/js/w/*$script,domain=www.whathifi.com`

for the `Subscribe` button, in top nav

**Comment by ryanbr** [comment]
That will allow trackers in @PIZZA90
