### ISSUE TITLE
lolesporte.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#8085]
### URL(s) where the issue occurs

`https://forum.lolesporte.com/index.php`

### Describe the issue

Anti-adblock.

### Screenshot(s)

![adblock](https://user-images.githubusercontent.com/35470489/97179347-7a940480-1777-11eb-8737-0ec3066de704.png)

### Versions

- Browser/version: Firefox stable
- uBlock Origin version: 1.30.6

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin lists

**Comment by JobcenterTycoon** [comment]
possible filter: `lolesporte.com##+js(set, blocked, 0)`
