### ISSUE TITLE
mail.com

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#8086]
### URL(s) where the issue occurs

mail.com

### Describe the issue

Hi. When you go to mail.com with ublock origin disabled, mail.com shows a white overlay screen briefly then after a few seconds, loads a settings window asking you to click buttons to either edit settings, or accept mail.com's privacy settings. If you click accept, after another few seconds, it then loads the mail.com homepage normally with ads, and gives you the option of clicking sign in in the top right corner to log into your email account. Then if you go to that page again, it just takes you directly to the normal homepage without showing the popup window again, as long as you haven't cleared your cookies. (See first two screenshots.)

However, if you go to mail.com with ublock origin enabled, it shows a white overlay screen, then after a few seconds a popup window with an error message appears that says "an error has occured. please reload the page." and gives you the option to click a button that says return, then takes you to mail.com's homepage after another few seconds of waiting for the page to load. It'll then take you to the homepage next time you go to mail.com, as long as you haven't cleared the cookies. The mail.com website never used to to that, because I think they've recently changed the design of their website, but something about it seems to be causing ublock origin to interfere with it. (See second two screenshots.)

Being able to go to this website normally without any popup windows or interference from ublock origin, while still being able to block ads on that website is very important to me since it's an important website that I use often. Could you please help me with this issue and tell me if there are any settings that can be configured in ublock origin so that it doesn't interfere with mail.com's website or show any popup windows or ads on it? Thanks, and have a good day.

### Screenshot(s)

![mail com normal page loading after error with ublock origin disabled 1](https://user-images.githubusercontent.com/35790889/97203911-d5375b80-178b-11eb-8ae8-ca5a0d8f1c04.jpg)

![mail com normal page loading after error with ublock origin disabled 2](https://user-images.githubusercontent.com/35790889/97203951-dec0c380-178b-11eb-94d3-eae3ea9e987e.jpg)

![mail com error with ublock origin enabled 1](https://user-images.githubusercontent.com/35790889/97203968-e2ece100-178b-11eb-8968-5ac1b704ad3e.jpg)

![mail com error with ublock origin enabled 2](https://user-images.githubusercontent.com/35790889/97203985-e7b19500-178b-11eb-8eb4-4de5da12f542.jpg)

### Versions

- Browser/version: Firefox 82.0 (64-bit)
- uBlock Origin version: 1.30.6

### Settings

-

**Comment by mapx-** [comment]
add

```
@@||dl.mail.com/permission/oneTrust/consent/*.json$xhr,1p
@@||cdn.cookielaw.org/vendorlist/*.json$xhr,domain=plus.mail.com
@@||mail.com^$ghide
mail.com##.ad-banner
```

@ryanbr

**Comment by uBlock-user** [comment]
Is that really needed ? `@@||mail.com/consentpage/event/visit$xhr,1p` works fine.

**Comment by mapx-** [comment]
did you add EasyList Cookie + fanboy annoyances ?

**Comment by uBlock-user** [comment]
why would I need to ?

**Comment by mapx-** [comment]
- You have to use the default setup, check if it's all ok, then add 1 by 1 the other lists and tell us what is the "bad" list 

> then automatically goes to the normal mail.com homepage

You mean you were inside your account ? provide all the necessary details

**Comment by IoanPaleru** [comment]
With ublock origin's default settings, when you go to mail.com, the page shows a white overlay screen for a few seconds and then automatically loads the normal mail.com homepage without any issues or popup messages like it did before without logging into any accounts. So it seems that mail.com changed something on their website that makes it work better with the ad blocker, and also those filters that everyone provided were helpful as well. Everything seems to be working properly now and no further troubleshooting is necessary. Thanks and have a good day.

**Comment by IoanPaleru** [comment]
Hi. Those filters don't work, but it seems that when these annoyances filter lists are enabled, they causie the mail.com homepage to show a white background page with a loading icon, or an error popup window, instead of allowing it to load properly (see screenshots):

Adguard annoyances
Easylist cookie
Fanboy's annoyance

When going to mail.com with ublock origin enabled, it used to show a mail.com settings configuration popup window before loading mail.com's homepage, but now it just displays the homepage where the news articles and login options are displayed (without any ads), if ublock origin's annoyances filters lists are disabled.

Adguard annoyances enabled:
![mail com adguard annoyances enabled](https://user-images.githubusercontent.com/35790889/98992958-cd054d00-24fb-11eb-9c5e-c3cd43a80689.jpg)

Easylist cookie enabled:
![mail com easylist cookie enabled](https://user-images.githubusercontent.com/35790889/98992979-d393c480-24fb-11eb-8d94-c7d411a3f744.jpg)

Fanboy's annoyance enabled:
![mail com fanboy's annoyance enabled](https://user-images.githubusercontent.com/35790889/98992993-da223c00-24fb-11eb-8e3c-b38841ff292e.jpg)

All annoyances filter lists disabled, mail.com settings configuration popup window:
![mail com filters disabled original](https://user-images.githubusercontent.com/35790889/98993099-05a52680-24fc-11eb-8ff9-1479e375bdd6.jpg)

All annoyances filter lists disabled, homepage displayed normally:
![mail com filters disabled](https://user-images.githubusercontent.com/35790889/98993181-253c4f00-24fc-11eb-8bb5-ed80c95f26da.jpg)

I've already updated all the filter lists and all of ublock origin's other settings are the default settings.

Is there any way to fix those filter lists so they work properly, and don't interfere with mail.com's homepage? Thank you.

**Comment by mapx-** [comment]
add
```
@@||uicdn.com/mailint/*/consent-management.js$script,domain=mail.com
@@||cdn.cookielaw.org^$xmlhttprequest,domain=cnn.com|crfashionbook.com|doctoroz.com|eurogamer.net|mail.com|rockpapershotgun.com|trustpilot.com|tvn24.pl
mail.com#@##onetrust-consent-sdk
```

**Comment by IoanPaleru** [comment]
Ok, thanks. That seems to work well. I don't know why mail.com keeps changing their website. Also, how did you find the "@@||uicdn.com/mailint/*/consent-management.js$script,domain=mail.com
@@||cdn.cookielaw.org^$xmlhttprequest,domain=cnn.com|crfashionbook.com|doctoroz.com|eurogamer.net|mail.com|rockpapershotgun.com|trustpilot.com|tvn24.pl
mail.com#@##onetrust-consent-sdk" filters to use? Could you tell me step by step how to open the developer tools console or whatever in firefox and how to know where and what to look for when trying to find the necessary information like that so that I can learn how to find filters to solve issues on websites myself, instead of always having to ask on github? Thanks and have a nice day.

**Comment by mapx-** [comment]
1. use uBO logger to find what's blocked. Then you can try to whitelist some elements, refresh page, see the result
2. Better report here, this way we can fix the issues for all users in the official lists
