### ISSUE TITLE
Spacing in physicsforums.com

### ISSUE THREAD

**Issue by easyaspi314** [uBlockOrigin/uAssets#809]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`https://www.physicsforums.com/threads/the-ever-so-dreaded-calculus-ii.259807/`

### Describe the issue

Whitespace next to every few posts.

### Screenshot(s)

![screen shot 2017-11-01 at 1 13 17 pm](https://user-images.githubusercontent.com/6258309/32287234-839eafb6-bf06-11e7-9498-6b189cca6f6c.png)

### Versions

- Browser/version: Safari 11.0.1
- uBlock Origin version: 1.14.14

### Settings

- I enabled advanced mode just for information. Not much else.

### Notes

This filter seems to fix it: `physicsforums.com##.adsbygoogle`
(by the way, yes, I hate Calc II)

**Comment by okiehsch** [comment]
This seems to be a Safari issue, the whitespace is dealt with on my end, by the EasyList filter `##.adsbygoogle`, so I can't reproduce your issue,
Tested with Chrome and Firefox stable versions + uBO 1.14.14 and 1.14.17b10
