### ISSUE TITLE
uBlock disabling images on Matomo.org

### ISSUE THREAD

**Issue by Starker3** [uBlockOrigin/uAssets#8090]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Images are broken with uBlock Origin installed

### A specific URL where the issue occurs
`
https://matomo.org/docs/ecommerce-analytics/`

### Steps to Reproduce

1. Go to the URL
2. Scroll down the page until you come to an area where there is a large whitespace (where the images should be)
3. The larger images just show up as white space, the smaller images show a broken image

### Expected behavior:

Images should load normally

### Actual behavior:
Images are broken

### Your environment

* uBlock Origin version: 1.30.6
* Browser Name and version: Firefox 81.0.2
* Operating System and version: Windows verion 1903

![Screenshot](https://user-images.githubusercontent.com/20905821/97254125-95976f00-1872-11eb-94f8-582cf817f8f9.jpg)

**Comment by uBlock-user** [comment]
Fixed in EP. Force update that list.
