### ISSUE TITLE
https://www.citationmachine.net Detects uBlock Origin

### ISSUE THREAD

**Issue by un71** [uBlockOrigin/uAssets#8095]
### URL(s) where the issue occurs

`https://www.citationmachine.net`

### Describe the issue

It detects you are using an ad blocker and makes you turn it off

### Screenshot(s)

![image](https://user-images.githubusercontent.com/58738226/97328463-6c63e800-184c-11eb-8f7b-f311c82aeb5c.png)

### Versions

- Browser/version: ChromeOS 84.0.4147.136
- uBlock Origin version: 1.30.6

### Settings

-Prevent WebRTC from leaking local IP addresses 
-Block CSP reports 
-uBlock filters 23,172 used out of 24,676

-uBlock filters – Badware risks

-uBlock filters – Privacy

-uBlock filters – Resource

-uBlock filters – Unbreak 

-AdGuard Base

-AdGuard Mobile Ads

-EasyList

-AdGuard Tracking Protection

-EasyPrivacy

-AdGuard Annoyances

-AdGuard Social Media

-uBlock filters – Annoyances

-Peter Lowe’s Ad and tracking server list

**Comment by llacb47** [comment]
Test `||studybreakmedia.com^$3p`

if it breaks something try `||atc.studybreakmedia.com/modules/abb/`

**Comment by un71** [comment]
> Test ||studybreakmedia.com^$3p

Works!
