### ISSUE TITLE
virginmobile.ca

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#8097]
### URL(s) where the issue occurs

virginmobile.ca

### Describe the issue

When you go to virginmobile.ca with ublock origin disabled, then click on "mobile", and "plans" from the top of the page, it takes you to a page that shows all the different phone plans. (See first three screenshots.)

However, if you go to virginmobile.ca with ublock origin enabled, then click on "mobile", and "plans" from the top of the page, it doesn't take you to any other page and just stays on the same page that doesn't show you any of the phone plans. (See second five screenshots.)

Is there a way to fix that so that you can use ublock origin on that site, but have everything load normally? Thank you.

### Screenshot(s)

![test 1](https://user-images.githubusercontent.com/35790889/97367197-165c6800-187f-11eb-8eb3-586bc022b175.jpg)

![test 2](https://user-images.githubusercontent.com/35790889/97367213-1ceadf80-187f-11eb-9ee6-e1e611d091bd.jpg)

![test 3](https://user-images.githubusercontent.com/35790889/97367233-23795700-187f-11eb-8ab5-b512d3f35580.jpg)

![test ublock origin 1](https://user-images.githubusercontent.com/35790889/97367247-283e0b00-187f-11eb-9124-5a027346a1dd.jpg)

![test ublock origin 2](https://user-images.githubusercontent.com/35790889/97367260-2d02bf00-187f-11eb-85a0-13a579114298.jpg)

![test ublock origin 3 part 1](https://user-images.githubusercontent.com/35790889/97367276-32600980-187f-11eb-91a9-1b1e62635dc7.jpg)

![test ublock origin 3 part 2](https://user-images.githubusercontent.com/35790889/97367292-368c2700-187f-11eb-9a02-a5fc01b52697.jpg)

![test ublock origin 3 part 3](https://user-images.githubusercontent.com/35790889/97367298-3ab84480-187f-11eb-8556-2b9a8a123760.jpg)

### Versions

- Browser/version: Firefox 82.0.1 (64-bit)
- uBlock Origin version: 1.30.6

### Settings

-

**Comment by mapx-** [comment]
add

`@@||ssl.geoplugin.net/$script,domain=virginmobile.ca`

@ryanbr
