### ISSUE TITLE
einthusan.tv [Anti-Adblock] 

### ISSUE THREAD

**Issue by kickstand03** [uBlockOrigin/uAssets#8099]
### URL(s) where the issue occurs
`https://einthusan.tv/`

### Describe the issue
`https://einthusan.tv` redirects to `https://einthusan.tv/adblocker/`
(Anti-Adblock)

### Screenshot(s)
![image](https://user-images.githubusercontent.com/73573729/97394952-7a942180-18a9-11eb-9196-1215a9387679.png)

### Versions

- Browser/version: Firefox Browser 82.0.1
- uBlock Origin version:  v1.30.6

### Settings

@@||imasdk.googleapis.com^$script,domain=einthusan.tv
@@||einthusan.tv^$generichide
@@||einthusan.ca^$generichide
@@||imasdk.googleapis.com^$domain=einthusan.tv|einthusan.tv
@@||imasdk.googleapis.com^$domain=einthusan.ca|einthusan.ca
@@||ads.adaptv.advertising.com^$xmlhttprequest,domain=imasdk.googleapis.com
@@||video-ads.rubiconproject.com/$xmlhttprequest,domain=imasdk.googleapis.com
@@||einthusan.tv/prebid.js
@@||einthusan.ca/prebid.js
@@||einthusan.ca/prebid.js$script,first-part
@@||einthusan.tv/prebid.js$script,first-part
einthusan.tv/prebid.js##script:inject(bab-defuser.js)
@@||einthusan.tv/prebid.js$script,1p
@@einthusan*$xmlhttprequest,domain=imasdk.googleapis.com
@@||einthusan.tv/gdpr-consent-quantcast.js$script,1p

### Notes

It was working 2 days ago. Not anymore. Turning off scripts does not produce the anti-adblock message but just shows a loading screen.

**Comment by ghajini** [comment]
opera browser stable ,ubo 1.33.3b0

Loading forever
`https://einthusan.tv/movie/watch/4xuh/?lang=hindi`

![image](https://user-images.githubusercontent.com/20338483/107112611-eb6eb080-687e-11eb-9ede-fde3661208b2.png)

**Comment by mapx-** [comment]
chrome / opera all fine on my end, "loading advertisement" for 20-30 seconds then is running

**Comment by ghajini** [comment]
Try this link
`https://einthusan.tv/launcher/?lang=hindi`

**Comment by mapx-** [comment]
```
@@||d2wy8f7a9ursnm.cloudfront.net/v4/bugsnag.min.js$script,domain=einthusan.tv
@@||quantcast.mgr.consensu.org/*/cmp2.js$script,domain=einthusan.tv
```

**Comment by ghajini** [comment]
works

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/de10eccda8fb7e01142ee14c4a3c4e9377403fc8
