### ISSUE TITLE
bild.de social buttons AAK

### ISSUE THREAD

**Issue by wakkabakkamakka** [uBlockOrigin/uAssets#81]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

bild.de
http://www.bild.de/bild-plus/politik/ausland/isis/isis-verliert-gebiete-46724630,var=x,view=conversionToLogin.bild.html

### Describe the issue

Social Buttons at bild.de are not hidden if using AAK. (anti adblock killer) but they say that they cant fix it see here: https://github.com/reek/anti-adblock-killer/issues/1498 (last 2 comments)
i am hoping that with the more advanced ublock origin specific filters it is possible to hide the social buttons but still disable the anti adblock functionality of bild.de

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: firefox 47.0.1
- uBlock Origin version: 1.7.6

### Settings

AAK

### Notes

it is the aak list i reported it to them they say they cant fix it without deblocking the anti adblock too

i also posted it at lanik.us (easy list) they also said they cant fix it: https://forums.lanik.us/viewtopic.php?f=62&t=31471

**Comment by IDKwhattoputhere** [comment]
Have you tried using the [element picker](https://github.com/gorhill/uBlock/wiki/Element-picker)?

**Comment by gorhill** [comment]
> unfortunately the filter @@||bild.de^$elemhide leads to the social buttons resurfacing on bild.de
see issue https://forums.lanik.us/viewtopic.php?f=62&t=31471 (where is was told to report here)

Just create specific cosmetic filters. `elemhide` will prevent generic cosmetic filters to be applied, but not specific ones. This should work even with `elemhide`: `bild.de##.socialbar`.
