### ISSUE TITLE
onlinegamesx.com

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#8101]
### URL(s) where the issue occurs

`https://www.onlinegamesx.com/?postid=OAmu`

### Describe the issue

There is 10 sec countdown

### Screenshot(s)

![image](https://user-images.githubusercontent.com/61142621/97446614-e5d40700-192e-11eb-9671-01001066a79a.png)

### Versions

- Browser/version: Opera 71.0.3770.284
- uBlock Origin version: 1.30.4

### Settings

- Default

**Comment by uBlock-user** [comment]
Timer cannot be fastened, but you can use `onlinegamesx.com###yuidea-snp:style(display:block !important)` to make the button appear always.

**Comment by LGLTeam** [comment]
Okay, thanks

**Comment by krystian3w** [comment]
So CSS is no recommed in `annoyances.txt`

?
