### ISSUE TITLE
blog.linksfire.co

### ISSUE THREAD

**Issue by LGLTeam** [uBlockOrigin/uAssets#8102]
### URL(s) where the issue occurs

`https://blog.linksfire.co/OAmu`

### Describe the issue

An anti-adblock, telling you to disable it

### Screenshot(s)

![image](https://user-images.githubusercontent.com/61142621/97446973-57ac5080-192f-11eb-9982-c7b018fbcf2c.png)

### Versions

- Browser/version: Opera 71.0.3770.284
- uBlock Origin version: 1.30.4

### Settings

- Default

### Notes

This is the new technique i discovered. You can't go to this page directly, it will start over to this page `https://newsified.xyz/game-guardian-unlimited-features-apk-andriod-download/`
1. Go to `https://www.onlinegamesx.com/?postid=OAmu` (this is a shortcut) and wait 10 secs (#8101)
2. Press continue at the bottom. Site will redirect to 
3. Site will now redirect to `https://blog.linksfire.co/OAmu`

**Comment by IThinkIAmCool** [comment]
@ryanbr @uBlock-user @mapx- could you check the link from the issue?

**Comment by krystian3w** [comment]
I suppose webapge is no longer safe, need ban in `badware.txt`.

**Comment by IThinkIAmCool** [comment]
spaces + another "Get Link"
