### ISSUE TITLE
mangahosted.com

### ISSUE THREAD

**Issue by Slasar41** [uBlockOrigin/uAssets#8104]
### URL(s) where the issue occurs

`https://mangahosted.com/`

### Describe the issue

Antiadblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/28888646/97480210-b43a5a80-1985-11eb-9da4-a57c4eb3ea2a.png)

### Versions

- Browser/version: Microsoft Edge 86.0.622.56
- uBlock Origin version: v1.30.6

**Comment by uBlock-user** [comment]
Already fixed with regional list, added the filter to fix the ad-placeholder.

**Comment by lain566** [comment]
I can reproduce anti-adblock with Brazilian VPN

**Comment by uBlock-user** [comment]
@lain even with regional list enabled ?

**Comment by uBlock-user** [comment]
@lain566  even with regional list enabled ?

**Comment by lain566** [comment]
Yes.
