### ISSUE TITLE
[breakage] [bio_ep plugin] wizcase.com

### ISSUE THREAD

**Issue by bug-rules** [uBlockOrigin/uAssets#8108]
### URL(s) where the issue occurs

`https://www.wizcase.com/reviews/ultrasurf-vpn/`
`https://pl.wizcase.com/reviews/ultrasurf-vpn/`

### Describe the issue

Breakage scrolling page due generic block `###bio_ep` by uBlock  Annoyance.

https://github.com/uBlockOrigin/uAssets/blob/fc577e31bb08a6c327cd0c5c584ab560be457045/filters/annoyances.txt#L1847-L1848

### Screenshot(s)

![Przechwytywanie](https://user-images.githubusercontent.com/66819865/97546793-339f4c80-19cd-11eb-8eb9-6b80d1ed48ff.JPG) |
--- |

![Przechwytywanie](https://user-images.githubusercontent.com/66819865/97546842-4c0f6700-19cd-11eb-8e26-3a550b59f3f4.JPG) |
--- |

### Versions

- Browser/version: Firefox 82.0.1
- uBlock Origin version: 1.30.6

### Settings

stock +
- Annoyance

### Notes

Fix by:

```js
wizcase.com##+js(no-setTimeout-if, bioEp.showPopup)
```

@gorhill can you disable this bad added generic filters?

**Comment by krystian3w** [comment]
Why is omitted: `wizcase.com##+js(no-setTimeout-if, bioEp.showPopup)`?

bad filter?
