### ISSUE TITLE
Consider whitelisting Ethical Ads

### ISSUE THREAD

**Issue by SelfhostedPro** [uBlockOrigin/uAssets#8110]
### URL(s) where the issue occurs

*.ethicalads.io

### Describe the issue

EthicalAds is a privacy focused advertising platform that doesn't track users and only allows for a single unintrusive ad per page. The vast majority of sites that publish these ads are open source projects looking to get some support from the community. I definitely understand if this doesn't fit in with the goal of this project but wanted to reach out about it regardless.

Here is a screenshot for an example of how unintrusive they are:
![image](https://user-images.githubusercontent.com/66331933/97586382-6d655880-19b7-11eb-8fe2-6915d8acc70d.png)

**Comment by uBlock-user** [comment]
uBO doesn't maintain any whitelist neither there's any acceptable ads policy here.

**Comment by SelfhostedPro** [comment]
Alright, like I said, just wanted to reach out about it. Thanks for the prompt reply.
