### ISSUE TITLE
No payment with paypal possible

### ISSUE THREAD

**Issue by WinDerFried** [uBlockOrigin/uAssets#8115]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

I only get an error message from PayPal: "Things don't appear to be working at the moment. Please try again later." When I disable uBO it works. How can I whitelist this? The problem is with some pages. For example the Postshop.de and my own website das-bumerang-projekt.de

### A specific URL where the issue occurs

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version:
* Browser Name and version:
* Operating System and version:

**Comment by okiehsch** [comment]
Does it work if you add
`@@||das-bumerang-projekt.de/*/boomerang.js$script,1p`
to your filter list?

**Comment by WinDerFried** [comment]
What do you mean with: Address #8115 ? I do not understand that, sorry. And to answer here: The code you sent did not work if I put it in the whitelist (Positivliste) and not if I put it in "my filter list" (Meine Filter). And I do not think that I have to put it into "My Rules" (Meine Regeln) think that is not the right position... Think we have issues with the language? So - any other idea?

**Comment by WinDerFried** [comment]
And as I wrote - @@||das-bumerang-projekt.de/*/boomerang.js$script,1p does not work If I whitelist it nothing does change and it look like it should and if I do put it into "My Filters" it is looking inthis way: @@||das-bumerang-projekt.de/*/boomerang.js$script,1p @@ is marked green, || is marked pink, * is marked red and $script,1p is marked blue.....

**Comment by okiehsch** [comment]
> What do you mean with: Address #8115 

I added the mentioned filter to the `uBO-unbreak` list because I can reproduce the issue.

If I don't add the filter and go to `https://das-bumerang-projekt.de/bumerang-kaufen/?m=clearwater+ii&id=10` and click "jetzt mit paypal kaufen" I get 
![image](https://user-images.githubusercontent.com/16838044/97709201-3d52ae00-1aba-11eb-90c9-1b9fa32b724c.png)

If I add the filter I get 
![image](https://user-images.githubusercontent.com/16838044/97709417-96badd00-1aba-11eb-9882-a97d29067ce0.png)

Meaninng that filter fixes the issue on my end.

> Think we have issues with the language?

We can continue the discussion in german if you prefer that.

**Comment by WinDerFried** [comment]
And after I did both after a capture I got this: https://www.paypal.com/webapps/hermes?token=0YH62305SG504364A&useraction=commit&mfid=1604063794758_e3de4ded0e923#/checkout/login

**Comment by okiehsch** [comment]
I added the filter to `uBO-unbreak`. If you manually update that list is your issue fixed or not?
If you don't know how to manually update a list. https://github.com/uBlockOrigin/uBlock-issues/wiki/Dashboard:-Filter-lists#update-now

**Comment by WinDerFried** [comment]
Funny - But that, was shown in that link above here is correct - but I did not get it here. Here I got this to read: 
DAS BUMERANG-PROJEKT
PayPal Checkout
20,11 EUR

    You are logging into the account of the seller for this purchase. Please change your login information and try again.

Log In to PayPal
English
or
Continue without a PayPal account
New. Faster. Easier.

Welcome to the new PayPal checkout!
The security you rely on – now even faster.
It’s everything checkout should be.

    ImprintLegalPrivacyKey payment and service description 

© 1999 - 2020 PayPal is the safer, easier way to pay

**Comment by WinDerFried** [comment]
Thank you so much updating the filter list worked!! But funny - I updated that list yesterday! And nothing changed. I did it now again and now it is working, haha! :-) Thank you again!

**Comment by okiehsch** [comment]
> I updated that list yesterday!

I added the filter three hours ago. 😉

**Comment by WinDerFried** [comment]
Lucky me!!!!!! Thank you again!
