### ISSUE TITLE
vvc.vc

### ISSUE THREAD

**Issue by FireMasterK** [uBlockOrigin/uAssets#8116]
### URL(s) where the issue occurs
`
https://vvc.vc/asdfghj`

### Describe the issue
uBlock is detected.
 

### Screenshot(s)
![image](https://user-images.githubusercontent.com/20838718/97704934-443ce900-1ad9-11eb-8d48-92462f13cb9c.png)

### Versions

- Browser/version: Brave 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit)
- uBlock Origin version: 1.30.6

### Settings
- None Modified

### Notes
I tried disabling brave shields, so it's unlikely it's an issue in brave alone.

**Comment by IThinkIAmCool** [comment]
ad @ryanbr
