### ISSUE TITLE
[shadow-root] ultimasnoticias.com.ve ads

### ISSUE THREAD

**Issue by bug-rules** [uBlockOrigin/uAssets#8117]
### URL(s) where the issue occurs

`https://ultimasnoticias.com.ve/noticias/politica/maduro-advierte-que-leopoldo-lopez-esta-desde-espana-en-plan-de-guerra/`

### Describe the issue

Shadow-root ad similar to blocked on `ibb.co`

> https://github.com/uBlockOrigin/uAssets/blob/2745fa9b4cab6de984af827dfbbae210e0ea1a86/filters/filters-2020.txt#L5264-L5267

### Screenshot(s)

`https://ibb.co/zfZgyCX`

### Versions

- Browser/version: Firefox 82.0.2
- uBlock Origin version: 1.30.6

### Settings

Stock

### Notes

```js
ultimasnoticias.com.ve,ibb.co##^script:has-text(/.*track.*atob.*ShadowRoot/):has-text(/[\w\W]{5000,10000}/)
```

**Comment by krystian3w** [comment]
#8387
