### ISSUE TITLE
http://blog.nulledfun.com/

### ISSUE THREAD

**Issue by xisini** [uBlockOrigin/uAssets#812]
`http://blog.nulledfun.com/how-to-list-and-make-a-payeer-accounts-nulledfun-com`

This site has ad blocker detection function that i cannot pass.

![ss23](https://user-images.githubusercontent.com/24823324/32338769-c8063de4-c006-11e7-93fc-2bbcc1db1e43.JPG)

- Browser/version: Chrome Version 61.0.3163.100 (Official Build) (64-bit)
- uBlock Origin version: v1.14.12

These are my active lists

- uBlock filters​
- uBlock filters – Badware risks​
- uBlock filters – Experimental​
- uBlock filters – Privacy​​​​​63 
- uBlock filters – Resource abuse​​​​​
- uBlock filters – Unbreak
- Adblock Warning Removal List​
- EasyList​
- EasyPrivacy
- Malware Domain List​
- Malware domains
- Peter Lowe’s Ad and tracking server list
- TUR: Adguard Turkish Filter
- AakList (Anti-Adblock Killer)

Regards,

**Comment by mapx-** [comment]
add
`@@||nulledfun.com^$generichide`
