### ISSUE TITLE
downfile.site

### ISSUE THREAD

**Issue by Bulogan** [uBlockOrigin/uAssets#8122]
### URL(s) where the issue occurs

`https://downfile.site/`

### Describe the issue

 
adblock detected

### Screenshot(s)

![image](https://user-images.githubusercontent.com/69257763/97768725-249cd380-1b60-11eb-9372-fe34971ecd88.png)

### Versions

- Browser/version: Firefox 63.0b6
- uBlock Origin version: 1.30.9b0

**Comment by mapx-** [comment]
I see anti adb code .. but I cannot reproduce, try:

`downfile.site##+js(acis, jQuery.ajax)`
or only firefox:
`downfile.site##^script:has-text(jQuery.ajax)`

**Comment by uBlock-user** [comment]
Reproducable via `https://megaurl.in/YuIyT9m5`, 

fixed, force update uBlock Filters.
