### ISSUE TITLE
ublock annoyances list triggers copy action when play/pause video

### ISSUE THREAD

**Issue by Tomatoide** [uBlockOrigin/uAssets#8127]
### URL(s) where the issue occurs
m.youtube.com

### Describe the issue
when touching the play/pause icon on mobile youtube website copy/paste/select actions appear as if I'm copying text, pinned it down to ublock annoyances list, when disabled the issue is not there anymore
 

### Versions

- Browser/version: [firefox android 82.1.1]
- uBlock Origin version: [1.30.6]

### Settings

- activated ublock annoyances filter list

**Comment by uBlock-user** [comment]
`m.youtube.com##*:style(-webkit-touch-callout: default !important; -webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)` was added to address https://github.com/uBlockOrigin/uAssets/issues/7718

**Comment by mapx-** [comment]
yeah, breaking filter in real mobile use (in emulation all fine)
