### ISSUE TITLE
9anime detects devtools being opened

### ISSUE THREAD

**Issue by drhouse** [uBlockOrigin/uAssets#8128]
### URL(s) where the issue occurs

```
https://www12.9anime.to/watch/after-school-dice-club-dub.5ojm/ep-7
https://www12.9anime.ru/watch/after-school-dice-club-dub.5ojm/ep-7
```

### Describe the issue

It seems 9anime (both .ru and .to) has implemented anti-devtools code, when I try opening Chrome Developer Tools (devtools): 
i) the video is immediately removed from the video player
ii) the console log is deleted through repeated Console.clear()

### Screenshot(s)

![2020-11-01 14_17_27-Watch After School Dice Club English Subbed Online Free](https://user-images.githubusercontent.com/187476/97812190-af0f3100-1c4d-11eb-9550-87918f9878f7.png)

### Versions

- Browser/version: Google Chrome version 86.0.4240.111 (Official Build) (64-bit)
- uBlock Origin version: v1.30.6

### Settings

No settings were originally changed.
-

### Notes

I tried isolating external scripts to see which one might be causing the issue, strangely as far as I could tell it was:
https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.4.5/js/swiper.min.js
When I blocked it, the video wouldn't load (before or after opening devtools), but the console log messages were no longer being deleted.

**Comment by uBlock-user** [comment]
[debugger](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger) is called from `https://9anime.to/assets/9anime/min/all.js?5f8feb38`

**Comment by drhouse** [comment]
yeah, it seems so... I installed Firefox and the video stayed open after opening devtools. Darn, I'd switch to Firefox, but I have a lot of pre-existing userscript code that works in Chrome, but causes errors in Firefox:
[9anime Bingewatcher]([url](https://greasyfork.org/en/scripts/401339-9anime-bingewatcher-prime/code))
I hope there's a Chrome solution.

**Comment by uBlock-user** [comment]
I also see `debugger` being called from video hosts too like `mcloud.to` and `vidstream`. You could deactivate all breakpoints, that will work in [Chrome](https://stackoverflow.com/questions/4903302/how-to-remove-all-breakpoints-in-one-step-in-google-chrome) and [Firefox](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Disable_breakpoints).

**Comment by drhouse** [comment]
really? could you please tell me how to do that... I know how to deactivate breakpoints I've set myself, but not sure otherwise

**Comment by mapx-** [comment]
for chrome, try blackboxing that script

![image](https://user-images.githubusercontent.com/10303732/97912273-e0225b00-1d4c-11eb-8a8f-800868d30164.png)

https://developer.chrome.com/devtools/docs/blackboxing

**Comment by drhouse** [comment]
hmm, I tried that before... I tried blackboxing it again right now, but didn't work. I mentioned in my report that I tried isolating external scripts to see which one might be causing the issue and didn't really have luck there.

**Comment by uBlock-user** [comment]
@drhouse Add these and test --

```
9anime.*##+js(nosiif, break)
mcloud.*,mcloud2.*##+js(nosiif, break)
vidstream.pro##+js(nosiif, break)
```

**Comment by uBlock-user** [comment]
The above filters are only to stop the dev-tools detection fyi

**Comment by drhouse** [comment]
yay that seems to work, you're a hero :) 
it seems to also have stopped the console.clear()
cheers

**Comment by uBlock-user** [comment]
Does the video still gets removed though ?

**Comment by drhouse** [comment]
yeah the video definitely is staying too

**Comment by ignat980** [comment]
Is it possible to update these filters? I'm having the same issue. On opening the developer tools anywhere on 9anime's site, it just auto-closes everything, clears the log, redirects to the homepage, and forcefully loops to go to an anonymous function with just the word "debugger" in it: 
![Screenshot 2021-11-01 224933](https://user-images.githubusercontent.com/8076691/139732733-1da37766-6b19-42ad-920c-23ea92631d9f.png)

Turning off breakpoints and preserving log allows me to look at the console and continue js execution, but it still redirects to the home site. Adding the all.js script to the ignore list doesn't do anything, I guess it gets injected into the site somehow still.

Maybe I didn't put it in correctly, those lines just go into my custom filter list in uBlock Origin's "My Filters", right? Is there something else I need to do? Thanks.

**Comment by uBlock-user** [comment]
@ignat980 fix is already present. I can't reproduce your issue.

**Comment by drhouse** [comment]
Can confirm the fix no longer works, on Chrome at least... would like one, in case something breaks for the users still using my 9anime userscript. Thanks. 
(btw, can't help notice exactly one year passed since original post, so much happened in the world :open_mouth:)

**Comment by soxyfoxy** [comment]
Also confirming the fix has stopped working on chrome.

**Comment by uBlock-user** [comment]
filter/s added, force updaete ublock filters list in a while.

**Comment by drhouse** [comment]
I tried it, but doesn't seem to be working, I made sure to 'Purge all caches' and 'Update now' all filters. 
It shows the same error as [before](https://github.com/uBlockOrigin/uAssets/issues/8128#issuecomment-956541464)

On a sidenote, I was curious, so I looked a little closer at the filter code, I think [this](https://github.com/uBlockOrigin/uAssets/commit/91a5981128904060950dcc47ea191e571e47c47f#diff-03b955eebef8886aa0f1ef70b305e9b7996de9a9e0adc9fe002db5a21d301c9f) was the related modified filter file, with:
`9anime.*##+js(nosiif, &&)`

I noticed if I manually add the above code to 'My filters', 9anime forwards me to a page saying "AdBlock breaks it!"
If I remove the above code, and instead 'Import > Custom' with the [modified filter file url](https://raw.githubusercontent.com/uBlockOrigin/uAssets/91a5981128904060950dcc47ea191e571e47c47f/filters/filters.txt), I also get "AdBlock breaks it!"
So, if applying the filter code causes "AdBlock breaks it!" to appear, but it didn't appear after using 'Update now', does that mean 'Update now' didn't actually cause the 9anime filter to be added (since "AdBlock breaks it!" should then appear)?

**Comment by gorhill** [comment]
> If I remove the above code, and instead 'Import > Custom' with the modified filter file url, I also get "AdBlock breaks it!"

What you are doing makes no sense, you are subscribing to an old version of the list which does not contain the fix, and which will never contain the fix because it's a specific link to an old version that will never change. Remove all custom filters related to `9anime`, stick stock filter lists and be sure they are all up to date.

**Comment by drhouse** [comment]
the custom filter link I tested did contain:
'`9anime.*##+js(nosiif, &&)`'

I already tried the given answer in the standard way, and it didn't work, that's why testing was being tried

**Comment by gorhill** [comment]
There was a fix [2 days ago](https://github.com/uBlockOrigin/uAssets/issues/10547) for `9anime`, see <https://github.com/uBlockOrigin/uAssets/issues/10547#issuecomment-976652958>:

> As a result of the removal of the filter, you can no longer access dev-tools without getting crashed.

**Comment by uBlock-user** [comment]
@drhouse I remove that filter because the admin is using that to detect adblocking.

**Comment by uBlock-user** [comment]
@drhouse I removed that filter because the admin is using that to detect adblocking.

**Comment by drhouse** [comment]
@uBlock-user gotcha, that explains the inconsistent test results I was getting. I was surprised to see the widespread "AdBlock breaks it!" and "anti-devtools" problems were related, as described in this reddit Ublock mod [post](https://www.reddit.com/r/9anime/comments/r0dd94/ublock_origin_error_message/hlsdrqk/?utm_source=reddit&utm_medium=web2x&context=3).

well, hopefully a mutual solution can still be found

**Comment by uBlock-user** [comment]
> hopefully a mutual solution can still be found

I have the filter I will wait few days until the "AdBlock breaks it!" reports subside.

**Comment by uBlock-user** [comment]
> 9Anime has two bits of JavaScript code that runs in the background which is designed to hinder anyone using the element inspector portion of the web browser. They do this, in order to prevent people from being able to easily just scrape data off the site to copy it. (Stop clone sites from stealing)

Admin's justification for messing with dev-tools, what admin fails to realise is there are other ways to scrape data off his site(ironic he's worried about someone stealing his episodes even he himself uploads pirated content 🙄 ) even without dev-tools.

**Comment by krackers** [comment]
@uBlock-user 
>I have the filter I will wait few days until the 

Could you share the override for those who want to add it manually? Ironically the admin's decision makes it hard to develop extensions/userscripts that would make more people want to use his site.

Also out of curiosity, how exactly is the devtools detected in this particular instance? I know of the standard `toString()` callback trick, but it doesn't seem like that is used in this particular case since nooping `console.log` usually works for that but not this one. There seems to be two separate scripts here, one that performs the `location.replace` redirect when devtools is first opened, and a second that has the `debugger` loop.

**Comment by uBlock-user** [comment]
> Could you share the override for those who want to add it manually?

Not willing, because this isn't the first time they circumvented the filter I added, it's been happening for the past few months now.

**Comment by hyoretsu** [comment]
Well, I reached here trying to Inspect Element on an ad I was seeing sometimes with Vidstream player.

**Comment by cyber-sec0** [comment]
https://greasyfork.org/en/scripts/440060-anti-anti-debugger

**Comment by cyber-sec0** [comment]
@ignat980
@krackers
@hyoretsu

I'm able to open the dev tools on edge without any problems.
I believe that this is what is helping me https://greasyfork.org/en/scripts/440060-anti-anti-debugger

**Comment by ignat980** [comment]
@cyber-sec0 Thanks, but nope, even with that script, any page on 9anime redirects to the front page and clears the console. But no more debugger stops! Thankfully this problem is only in Chrome, in Vivaldi I do not have any problems.

**Comment by SZB3748** [comment]
After doing some poking around, I think I figured out how 9anime's anti-debugger works, at least for Chrome.

It works by using a service worker (sw.js) which calls all.js?62fc2f95 when opening up devtools.

### Steps To Disable Anti-Debugger:

1.  Block the requests for the service worker and all.js?62fc2f95.
Filters I used:
![image](https://user-images.githubusercontent.com/77603256/185262119-43ef7332-e90e-46d8-bb23-620335ac2d1d.png)

2. Clear site data at chrome://settings/siteData and look for 9anime to clear the site data. I cleared everything, but if you want to keep some stuff, you should at least delete service workers and cached files.

**Comment by hyoretsu** [comment]
```
||9anime.id/sw.js$script,1p
||9anime.id/assets/_9anime/min/all.js?62fc2f95$script,domain=9anime.id
||s2.bunnycdn.ru/assets/_9anime/min/all.js?62fc2f062fc2f95$script,domain=9anime.id
```

**Comment by drhouse** [comment]
> It's on the same tab as cosmetic filters, just paste this.
> 
> ```
> ||[9anime.id/sw.js$script,1p](http://9anime.id/sw.js$script,1p)
> ||[9anime.id/assets/_9anime/min/all.js$script,domain=9anime.id](http://9anime.id/assets/_9anime/min/all.js$script,domain=9anime.id)
> ||[s2.bunnycdn.ru/assets/_9anime/min/all.js$script,domain=9anime.id](http://s2.bunnycdn.ru/assets/_9anime/min/all.js$script,domain=9anime.id)
> ```

worked for me, cheers 👍

**Comment by ignat980** [comment]
Still doesn't work for me 😞
Only in Chrome though, if I use a different browser everything works great

**Comment by ApexioDaCoder** [comment]
My current solution for opening devtools in it is using this userscript(https://greasyfork.org/en/scripts/440060-anti-anti-debugger) and opening it in an iframe(like this https://iframetester.com/?url=https://9anime.id/).

**Comment by Joe-theDevel** [comment]
SOLUTION (2022 OCTOBER 25):
USE **_ONLY_** CHROME OR OPERA BROWSER
1.- OPEN YOUR **_"FAULTY"_ PAGE** (BUT WAIT UNTIL IT FINISHES TO LOAD)
2.- OPEN CHROME'S **DEVELOPER TOOLS** (BY MENU OR PRESS F12)
3.- CLICK ON **SOURCES** SECTION ON MENU BAR (PRESS ESC IF NOT VISIBLE)
4.- CLICK ON THE SHOW DEBUGGER ICON ON TOP RIGHT CORNER (ONLY IF DEBUGGER IS HIDDEN)
5.- CLICK ON DEACTIVATE BREAKPOINTS ICON ON TOP RIGHT CORNER (TO TURN IT BLUE)
6.- CLICK ON THE URL (ADDRESS)  BAR TO RELOAD YOUR FAULTY PAGE
7.- IF A **NEW BLUE "PLAY (STEP)" ICON** APEARS IN THE DEBUGGER AREA THEN **CLICK AND HOLD ON THAT ICON** AND SELECT (RELEASE AT) THE **STOP ICON** THAT WILL BE DISPLAYED FROM A THREE ELEMENTS MENU

**Comment by dancin-grain** [comment]
> MY SOLUTION OR AT LEAST KIND OF... ( 2022 OCTOBER 25 ):
> 
> Use **_ONLY_** CHROME or OPERA browsers
> 
> 1.- open your **_"FAULTY"_ PAGE** (and wait until it finishes to load)
> 
> 2.- open CHROME'S **DEVELOPER TOOLS** (by menu, ctr+shift+i or just press F12)
> 
> 3.- click on **_SOURCES_** section on menu bar (press ESC to open lower section (drawer) if sources is not visible)
> 
> 4.- click on the **_SHOW DEBUGGER ICON_** on located on top right corner (only if debugger is hidden)
> 
> 5.- click on **_DEACTIVATE BREAKPOINTS ICON_** on top right corner (to turn it BLUE)
> 
> 6.- click on the URL (ADDRESS) BAR and press enter to RELOAD your faulty page
> 
> 7.- if a **_NEW BLUE "PLAY (STEP)" ICON_** apears in the debugger area then **CLICK AND HOLD ON THAT ICON** and release it at the **STOP (SQUARED) ICON** that will be displayed from a menu with three icons
> 
> AFTER COMPLETING THE PREVIOUS STEPS THE CONSOLE/DEBUGGER/DEVTOOLS DETECTOR SCRIPT FROM THE FAULTY PAGE WILL NO LONGER TRIGGER THE DEBUGGER ANY MORE UNTIL THE DEVTOOLS WINDOWS IS REOPENED
> 
> There is a very similar DEVTOOLS DETECTOR SCRIPT in a TRIPLE PLAY (ISP/TV/TEL) company (faulty) webpage that displays its TVGuide and VOD LIBRARY for their suscribers but restricts (detects) the use of DEVTOOLS by pausing (and sometimes crashing) javascript when devtools opens

it doesn't stop the redirection

**Comment by lapcat** [comment]
What works for me is to force a Content-Security-Policy on the site:

`script-src 'self' https://cdnjs.cloudflare.com https://s2.bunnycdn.ru`

This allows the scripts necessary for the site to function while excluding the anti-debugging scripts.

**Comment by stephenhawk8054** [comment]
I think the CSP will break this link if not adding `unsafe-inline` and `unsafe-eval`

`https://9anime.vc/watch/technoroid-overmind-18306?ep=96946`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/1a2ff01c0b92a64be8957fd4fb6fb05dd003379a

**Comment by gaveitatry2** [comment]
> My current solution for opening devtools in it is using this userscript(https://greasyfork.org/en/scripts/440060-anti-anti-debugger) and opening it in an iframe(like this https://iframetester.com/?url=https://9anime.id/).

This has helped me a lot. Thank you.
