### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by ip018** [uBlockOrigin/uAssets#8129]
### URL(s) where the issue occurs

github.com
github.com/join

### Describe the issue

When you to go github.com with ublock origin enabled, enter a username, email, and password to create a new account, and click "sign up for github", it takes you to github.com/join where it asks you to verify your account with a spambot filter captcha, however it doesn't display the spambot filter captcha, but if you disable ublock origin, it displays it properly. (See screenshots.) Is there a way to fix that? Also, it seems ublock origin doesn't work properly on many websites lately. Page elements either don't load properly, or don't load at all. Is there a way to improve ublock origin so that it works properly on most websites, without any extra user configuration and custom settings and filters necessary? Thanks.

### Screenshot(s)

![github 1](https://user-images.githubusercontent.com/73797335/97814843-25b12c00-1c58-11eb-86f8-131a5925a18e.jpg)

![github 2](https://user-images.githubusercontent.com/73797335/97814849-2a75e000-1c58-11eb-9598-bb522ec5f52e.jpg)

![github 3](https://user-images.githubusercontent.com/73797335/97814851-2ea1fd80-1c58-11eb-869a-debb1aa1e18e.jpg)

### Versions

- Browser/version: Firefox 82.0.2 (64-bit)
- uBlock Origin version: 1.30.6

### Settings

-

**Comment by mapx-** [comment]
1. You didn't provide all the info => what filter lists are enabled in uBO ?
2. Are you using other blocking extensions ?
3. 

>  it seems ublock origin doesn't work properly on many websites lately

Don't make weird statements without any prove / pages links / steps to reproduce such issues

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled.

**Comment by ip018** [comment]
1. I provided all the relevant information from the new issue template. It says "list here all the changes you made to uBO's default settings". So, if I didn't provide any details, it means that I'm using ublock origin's default settings, and didn't make any changes to it. (See screenshot.)

![ublock origin](https://user-images.githubusercontent.com/73797335/98054495-11606100-1e09-11eb-9790-92855db6a892.jpg)

2. I'm not using any other blocking extensions.

3. "it seems ublock origin doesn't work properly on many websites lately "

That's a subjective statement, but there have been many websites that haven't worked properly when ublock origin was enabled, but worked absolutely fine when it was disabled.

Take a look at these previous service requests (including specific links, and steps to reproduce the such issues) for some examples as proof of the many websites that don't work properly when using ublock origin:

https://github.com/uBlockOrigin/uAssets/issues/8086
https://github.com/uBlockOrigin/uAssets/issues/8097
https://github.com/uBlockOrigin/uAssets/issues/7985
https://github.com/uBlockOrigin/uAssets/issues/7742
https://github.com/uBlockOrigin/uAssets/issues/7832
https://github.com/uBlockOrigin/uAssets/issues/7800
https://github.com/uBlockOrigin/uBlock-issues/issues/1218
https://github.com/uBlockOrigin/uAssets/issues/7326
https://github.com/uBlockOrigin/uAssets/issues/7219
https://github.com/uBlockOrigin/uAssets/issues/6870
https://github.com/uBlockOrigin/uAssets/issues/6745
https://github.com/uBlockOrigin/uAssets/issues/6744
https://github.com/uBlockOrigin/uAssets/issues/5859
https://github.com/uBlockOrigin/uAssets/issues/5804
https://github.com/uBlockOrigin/uAssets/issues/5791
https://github.com/uBlockOrigin/uAssets/issues/5732
https://github.com/uBlockOrigin/uAssets/issues/4826
https://github.com/uBlockOrigin/uAssets/issues/4929
https://github.com/uBlockOrigin/uAssets/issues/4928
https://github.com/uBlockOrigin/uAssets/issues/4909
https://github.com/uBlockOrigin/uAssets/issues/4827
https://github.com/uBlockOrigin/uAssets/issues/4452
https://github.com/uBlockOrigin/uAssets/issues/4484
https://github.com/uBlockOrigin/uAssets/issues/4454
https://github.com/uBlockOrigin/uAssets/issues/4315
https://github.com/uBlockOrigin/uAssets/issues/3895
https://github.com/uBlockOrigin/uAssets/issues/3264
https://github.com/uBlockOrigin/uAssets/issues/3189
https://github.com/uBlockOrigin/uAssets/issues/3026
https://github.com/uBlockOrigin/uAssets/issues/2965
https://github.com/uBlockOrigin/uAssets/issues/2477
https://github.com/uBlockOrigin/uAssets/issues/2100
https://github.com/uBlockOrigin/uAssets/issues/1671

Perhaps if you spent more time updating ublock origin to make it compatible with modern websites, and designed it so that it worked better, instead of complaining about new issue requests when it doesn't work properly, you'd have a better program and fewer new issue requests.

Other than that, ublock origin is still quite useful on some websites, when it works properly, so thank you for all your efforts with improving its design, functionality, and reliability. It's definitely appreciated, since it's one of the few good fully featured ad blockers. Have a nice day.

**Comment by mapx-** [comment]
It's all about filters and not about "if you spent more time updating ublock origin to make it compatible with modern websites". The volunteers here dedicated hundreds /thousands hours to help guys like you.

So, open the logger and repeat the steps to create the github account. When you get the issue look into the logger and post here all the blocked items you see there.

Also, be sure you don't block too much using FF settings

![image](https://user-images.githubusercontent.com/10303732/98080981-9e8dcf00-1e76-11eb-87b7-cdce636aad97.png)

**Comment by uBlock-user** [comment]
Once again you make empty arguments and don't do as asked in https://github.com/uBlockOrigin/uAssets/issues/8129#issuecomment-720158289

You're the one with the issue here and yet you want to claim you're default settings by presuming instead of doing exactly as asked. This is not the way to get an issue resolved.

**Comment by uBlock-user** [comment]
> Perhaps if you spent more time updating ublock origin to make it compatible with modern websites, and designed it so that it worked better, instead of complaining about new issue requests when it doesn't work properly, you'd have a better program and fewer new issue requests.

Once again you make empty arguments and don't do as asked in https://github.com/uBlockOrigin/uAssets/issues/8129#issuecomment-720158289

You're the one with the issue here and yet you want to claim you're default settings by presuming instead of doing exactly as asked. This is not the way to get an issue resolved.
