### ISSUE TITLE
los40.com - Updating

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#8133]
### URL(s) where the issue occurs

`https://los40.com/los40/2020/10/29/musica/1603963617_477968.html?int=lomasvisto40`
`https://los40.com/los40/2020/10/29/los40classic/1603979654_969913.html`
### Describe the issue

Right sidebar break.

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [v1.30.6]

### Settings

spa, por: AdGuard Spanish/Portuguese 
spa: EasyList Spanish 
uBlock filters – Annoyances

### Notes

in **uBO Filters Unbreak**:

```
@@||epimg.net/js/pbs/slot_cs.min.js$script,domain=los40.com
@@||epimg.net/js/pbs/prebid$script,domain=los40.com
```

Maybe a **Update**:

```
@@||ak-ads-ns.prisasd.com/slot/cdial/slot.js$script,domain=los40.com
@@||ep00.epimg.net/js/pbs/pbs.slots.elpais.js$script,domain=los40.com
@@||*.safeframe.googlesyndication.com/safeframe/*$subdocument,domain=los40.com

```

**Comment by PIZZA90** [comment]
Video ads also here:

`https://los40.com/los40/2020/10/29/musica/1603988542_655791.html?int=lomasvisto40
`

**Comment by PIZZA90** [comment]
in the last update: https://github.com/uBlockOrigin/uAssets/commit/8f8592be2c15ec7c6793819a200800485638e556 the filter:` los40.com###los40_gpt-MPU1, #los40_gpt-MPU2` maybe is causing the typical crap of the sidebar.

For example here:
`https://los40.com/los40/2020/10/27/videos/1603820391_540028.html`

**Comment by lain566** [comment]
This should fix it.

**Comment by PIZZA90** [comment]
i found other ads..

`https://los40.com/los40/2020/10/30/los40classic/1604048717_594178.html`

in botton of any page, press here:

![Captura](https://user-images.githubusercontent.com/33556647/98086427-0811db80-1e7f-11eb-91d4-671bb8d8bd9d.PNG)

is a instagram style, press the right arrow, in the fourth element, the ads appear

**Comment by lain566** [comment]
Does this filter work for you?
`stories.los40.com##+js(json-prune, config.globalInteractions.[].bsData)`

**Comment by PIZZA90** [comment]
yes, works well

**Comment by PIZZA90** [comment]
anyone can reproduce the "clickable" blank spaces in main page? (background)

`https://los40.com/`

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by lain566** [comment]
Fixed. I can reproduce it, the site seems to have changed.
