### ISSUE TITLE
nwherald.com displaying admiral anti-adblock

### ISSUE THREAD

**Issue by stephenliang** [uBlockOrigin/uAssets#8136]
### URL(s) where the issue occurs

`https://www.nwherald.com/`

### Describe the issue

Visiting the website displays an Admiral anti-adblock popup.

### Screenshot(s)

![](https://user-images.githubusercontent.com/538214/97921001-25c03300-1d0f-11eb-94c8-f53608130186.png)

### Versions

- Browser/version: Firefox 83.0b2 (64-bit)
- uBlock Origin version: uBlock Origin v1.30.6

### Settings

Defaults

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/9912b7e4efe2cdaaaa3e35c60707d44804e4dea4
