### ISSUE TITLE
kickassanime.rs anti-ad block

### ISSUE THREAD

**Issue by Kavex** [uBlockOrigin/uAssets#8137]
### URL(s) where the issue occurs

Main page `https://www1.kickassanime.rs/`

### Describe the issue

Popup asking to whitelist the site because it detects ublock orgins 

### Screenshot(s)

https://i.imgur.com/ci05lIU.png

### Versions

- Browser/version: Chrome 86.0.4240.111
- uBlock Origin version: v1.30.6

### Settings

- Default besides the filter list from UAssets

### Notes

Blocking the wrapper seems to work, just needs to be added to UAssets filter

```
! 2020-11-03 https://www1.kickassanime.rs
www1.kickassanime.rs###modalAblockWrapper
```

**Comment by Yuki2718** [comment]
Actually the suggested filter doesn't help. Wait for a while and you'll be redirected to their FAQ section.

**Comment by uBlock-user** [comment]
> Actually the suggested filter doesn't help.

It did when I added, they implemented the redirection now.

**Comment by Yuki2718** [comment]
> 
> It did when I added, they implemented the redirection now.

Given this anti-adb was not there few days/weeks ago, it's possible they're watching. Let's see how long the new fix will last.

**Comment by gbisheraz581m** [comment]
It's gone and now they started to display to disable your antiadblock popup again @Yuki2718 @uBlock-user  @okiehsch

**Comment by Kavex** [comment]
You have to really admire how fast they fix these changes but they will tried out soon or later because this community is not the only one trying to bypass it. Time to run the site via DNS Ad-Blocking for a bit I guess.

**Comment by uBlock-user** [comment]
fixed, force update uBlock Filters in a while.

**Comment by Kavex** [comment]
well that didn't take long for them to fix the fix, ignoring

**Comment by uBlock-user** [comment]
> well that didn't take long for them to fix

It is to be expected from now on, we're now in battle of attrition ;) force update.
