### ISSUE TITLE
InfinityTrafficBoost.com CoinHive Mining

### ISSUE THREAD

**Issue by remivee** [uBlockOrigin/uAssets#814]
Can someone confirm if this website is using thecoinhive browser mining script? If it is, it's without the users permission.
Thanks!

**Comment by okiehsch** [comment]
I can't reproduce any coinhive-mining at `InfinityTrafficBoost.com`

**Comment by remivee** [comment]
Hmm..thanks for testing it. When I'm on the webpage I'm seeing a coinhive.com when I click on the uBlock icon on chrome.

**Comment by remivee** [comment]
I have enabled advanced settings on uBlock.

**Comment by okiehsch** [comment]
> I'm seeing a coinhive.com when I click on the uBlock icon on chrome.

Can't reproduce.
![infi](https://user-images.githubusercontent.com/16838044/32409859-9a27f8f4-c1b4-11e7-92b3-9801d7f1304c.JPG)

**Comment by remivee** [comment]
Damn..they must have taken it down. It was right there on that list before gstatic.com. Thanks again! I'm closing this issue.

**Comment by remivee** [comment]
I'm reopening this issue since I discovered that this surfing website InfinityTrafficBoost.com is in fact using the CoinHive miner, but only on their surfing pages. It used to be inside the Dashboard as well. No user permission!!

![itb-coinhive2](https://user-images.githubusercontent.com/8017160/32413082-4bc13c26-c212-11e7-8373-606cdaec3748.jpg)
![itb-coinhive](https://user-images.githubusercontent.com/8017160/32413078-426fd560-c212-11e7-9b8a-6de2a6fb296e.jpg)

**Comment by okiehsch** [comment]
`||coinhive.com^$third-party` is already part of the  `uBlock filters – Resource abuse` list and enabled by default.

**Comment by remivee** [comment]
ok. thanks!
