### ISSUE TITLE
Anti adblock warning on gridcoinstats not blocked.

### ISSUE THREAD

**Issue by nathanielcwm** [uBlockOrigin/uAssets#8140]
### URL(s) where the issue occurs

`http://main.gridcoinstats.eu/`

### Describe the issue

Anti adblock warnings are not blocked.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/22572406/98003365-a1ae9e00-1e29-11eb-9a1b-20cd07ff4d3b.png)

### Versions

- Browser/version: Firefox 82.0.2
- uBlock Origin version: 1.30.6

### Settings

[my-ublock-backup_2020-11-03_23.10.33.txt](https://github.com/uBlockOrigin/uAssets/files/5482107/my-ublock-backup_2020-11-03_23.10.33.txt)

### Notes

`##div.col-8 > div > div` seems to block the warning on the main page and it seems to remain static.
`##.col-6 > div > div ` seems to block it on the blocks page and it also seems to remain static.
Picker wants to block `##.col-7 > div > div` in [this page](http://main.gridcoinstats.eu/address/bc3NA8e8E3EoTL1qhRmeprbjWcmuoZ26A2) but that also removes information from the page.

**Comment by mapx-** [comment]
maybe

`main.gridcoinstats.eu##[href="/about#support"]:upward(1)`
