### ISSUE TITLE
Spaces for ads aren't removed on keybr.com

### ISSUE THREAD

**Issue by nathanielcwm** [uBlockOrigin/uAssets#8142]
### URL(s) where the issue occurs

`https://www.keybr.com/
`
### Describe the issue

The tops and sides of the page have sections that are used exclusively for ads. These aren't removed right now and I believe that when they are removed it gives a lot more usable screen real estate.

### Screenshot(s)

Original:
![image](https://user-images.githubusercontent.com/22572406/98011262-957b0e80-1e32-11eb-82c4-01dfaaa3a88d.png)

With header & aside removed:
![image](https://user-images.githubusercontent.com/22572406/98011314-a62b8480-1e32-11eb-8d00-d82be1b6b645.png)

With only header removed:
![image](https://user-images.githubusercontent.com/22572406/98011452-d115d880-1e32-11eb-9e76-0a5e7d8c3a80.png)

### Versions

- Browser/version: Firefox 82.0.2
- uBlock Origin version: 1.30.6

### Settings

[my-ublock-backup_2020-11-03_23.10.33.txt](https://github.com/uBlockOrigin/uAssets/files/5482555/my-ublock-backup_2020-11-03_23.10.33.txt)

### Notes

`www.keybr.com##.Body-aside` removes the left side
`www.keybr.com##.Body-header` removes the header

**Comment by nathanielcwm** [comment]
Actually removing only the header may look better.

**Comment by llacb47** [comment]
Try `keybr.com##div[class^="Supporter"]` from Adguard base

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by nathanielcwm** [comment]
Yep when adguard is enabled the spacing on the left and in the header is greatly minimised.

**Comment by krystian3w** [comment]
Duplicate of #7811
