### ISSUE TITLE
novinky.cz – ads

### ISSUE THREAD

**Issue by pepablock** [uBlockOrigin/uAssets#815]
### URL(s) where the issue occurs

**LINK** **–** `https://www.novinky.cz/kultura/453970-netflix-odrizl-herce-spaceyho-serial-house-of-cards-bude-bez-nej.html`

### Describe the issue

Ads on the top, bottom, side page and above comments. I highlighted them in the screenshot.

### Screenshot(s)

![01](https://user-images.githubusercontent.com/29940017/32405157-cc6cd0aa-c15f-11e7-9970-02ad6f42956c.jpg)

### Versions

- Browser/version: **Firefox 56.0.2 (64-bit)**
- uBlock Origin version: **1.14.16**

### Settings

Default

### Notes

–

**Comment by okiehsch** [comment]
`||novinky.cz/*/json$xmlhttprequest,first-party` works on my end, I don't know if this breaks anything.
If it works for you, you could report it to [EasyList Czech and Slovak](https://github.com/tomasko126/easylistczechandslovak).

**Comment by pepablock** [comment]
Working on my end as well, thanks.

There's already opened issue about this page from 18 days ago. I will post over there as well.

**Comment by r2308145** [comment]
it is not working on my end

**Comment by pepablock** [comment]
Yea, not working anymore. I'm not sure if they changed something, but when it was added into the cz/sk filters it was working, but now I'm seeing ads again.

**Comment by mapx-** [comment]
see if works
```
novinky.cz##script:inject(abort-on-property-write.js, AdBlockTest)
||novinky.cz/*adblock
||novinky.cz/*banner
novinky.cz###adTopsponsor
novinky.cz###adTopBigsponsor
novinky.cz##iframe[src*="rtbimp"]
novinky.cz##a[href*="clickthru"]
novinky.cz##[id^=im-]
novinky.cz###adComm
novinky.cz###adTopprodukt
```

**Comment by pepablock** [comment]
Works on my end, thanks! I will report it again to the [EasyList Czech and Slovak](https://github.com/tomasko126/easylistczechandslovak).

**Comment by r2308145** [comment]
works for me aswell now

**Comment by r2308145** [comment]
its random, one time its clear and one time ad appears
![screenshot-2017-11-12 zahranicni politiku tady delam ja doplnoval babis vystoupeni stropnickeho](https://user-images.githubusercontent.com/33419338/32702076-4dc3d04a-c7e1-11e7-9882-3695fc92fac1.png)


URL: https://www.novinky.cz/domaci/454725-zahranicni-politiku-tady-delam-ja-doplnoval-babis-vystoupeni-stropnickeho.html

**Comment by okiehsch** [comment]
Can't reproduce, works fine with Chrome and Firefox, even if I continuously reload no ads appear on my end at `https://www.novinky.cz/domaci/454725-zahranicni-politiku-tady-delam-ja-doplnoval-babis-vystoupeni-stropnickeho.html`

**Comment by pepablock** [comment]
I can reproduce it in Firefox, it takes a couple reloads for ads to appear on any page.
<img width="1680" alt="01" src="https://user-images.githubusercontent.com/29940017/32702344-1c4f7db6-c7e6-11e7-893b-5217a349eeb6.png">
![02](https://user-images.githubusercontent.com/29940017/32702345-1c6fcca6-c7e6-11e7-949d-ef149735c76d.jpg)

**Comment by pepablock** [comment]
With the new Firefox Quantum release, I can see ads all over the page again. eg. link: `https://www.novinky.cz/zahranicni/blizky-a-stredni-vychod/454969-americane-nechali-z-rakky-odejit-stovky-bojovniku-is-vymenou-za-ropna-pole.html`

**Comment by r2308145** [comment]
@pepablock you're right, I see them too.. the ads strikes back

**Comment by gwarser** [comment]
Their anti-adblocker now causes "never finishing loading" problem. On Firefox ads are blocked only on first load. On Chromium cosmetic filtering looks ok. Problem is solved if I block cookies for page (all subdomains). This is similar to idnes.cz - maybe mark these issues somehow?

https://old.reddit.com/r/uBlockOrigin/comments/8txrpy/some_pages_do_never_finish_loading/

**Comment by gwarser** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/53
