### ISSUE TITLE
Download from thingiverse is blocked whether or not uBO is enabled or disabled

### ISSUE THREAD

**Issue by RedactedCode** [uBlockOrigin/uAssets#8150]
`https://www.thingiverse.com/thing:2510169/makes`

Unable to download STL files even when uBlockOrigin is disabled for the site

1. With uBO enabled

![thing1](https://user-images.githubusercontent.com/31665276/98157859-dc6c1100-1ed1-11eb-892b-938d9abb5ee3.png)

2. With uBO disabled for the site

![thing2](https://user-images.githubusercontent.com/31665276/98157875-e3931f00-1ed1-11eb-970d-bcd6b7827bb1.png)

### Versions

- Browser/version: [VIVALDI 3.3.2022.47 (Stable channel) (64-bit)]
- uBlock Origin version: [uBlock Origin v1.30.6]

### Settings
 default

### Notes

You will see privacy badger icon showing it is enabled in the screenshots
I repeated the tests with it disabled, still unable to download files even if uBO is disabled

Not tested with latest vivaldi 3.4 because it's horrible, slow, unusable

**Comment by uBlock-user** [comment]
Browser issue perhaps,

**Comment by uBlock-user** [comment]
Vivaldi has its own built-in blocker, disable that.

**Comment by RedactedCode** [comment]
> Vivaldi has its own built-in blocker, disable that.

I forgot about that, this is the correct answer
