### ISSUE TITLE
Empty video box with "Skip Ad" when navigating YouTube SPA

### ISSUE THREAD

**Issue by GarbageHamburger** [uBlockOrigin/uAssets#8151]
### URL(s) where the issue occurs

Any monetized video on YouTube, but the issue only occurs when moving to a video by navigating YouTube's UI, direct links are not affected. Also seems to occur kind of randomly.  
Example: `https://www.youtube.com/results?search_query=W8x4m-qpmJ8` and then click the first result.

### Describe the issue

When navigating YouTube's SPA, sometimes you get a white screen in the video, with a "Skip Ad" button. Clicking the button plays the video.

### Screenshot(s)

![Screenshot](https://user-images.githubusercontent.com/63806108/98164381-1510e800-1edc-11eb-88f9-e2ff9deaa7d6.png)

### Versions

- Browser/version: Firefox 81.0 (Debian bullseye)
- uBlock Origin version: 1.30.6

### Settings

No changes.

### Notes

None.

**Comment by uBlock-user** [comment]
Merged in existing thread- https://github.com/uBlockOrigin/uAssets/issues/7636
