### ISSUE TITLE
Adblock detected and warning to accept cookies at https://www.libertaddigital.com/ and https://esradio.libertaddigital.com/

### ISSUE THREAD

**Issue by Jose1971AB** [uBlockOrigin/uAssets#8155]
### URL(s) where the issue occurs

 

```
ttps://www.libertaddigital.com/
https://esradio.libertaddigital.com/
```

### Describe the issue

The warning of adblock detected appears as soon as you enter the page. If I disable uBlock for that site, a warning appears to accept cookies

I'm not sure, but I think that if [https://www.libertaddigital.com/] is solved, [https://esradio.libertaddigital.com/] is also solved because the second link belongs to the first one, i.e. [https://www.libertaddigital.com/] is the main page. 

### Screenshot(s)

 I put only the image of [https://www.libertaddigital.com/] because it is exactly the same for [https://esradio.libertaddigital.com/], although if you require it I will send it in a next message.

![LibertadDigital_AntiAdblock](https://user-images.githubusercontent.com/44229110/98233920-f3594480-1f5f-11eb-8489-a91c39d94182.png)

### Versions
- Browser/version: [Firefox Browser 64-Bit v82.0.2]
- uBlock Origin version: [v1.30.6]

### Settings

![imagen](https://user-images.githubusercontent.com/44229110/98234611-ff91d180-1f60-11eb-8e5b-a05c5320137b.png)
![2-uBloc Predeterminados](https://user-images.githubusercontent.com/44229110/98235239-dde51a00-1f61-11eb-8e4d-ae272d5c4be4.jpg)

**Comment by uBlock-user** [comment]
Anti-adblock fixed yesterdy, cookie overlay s GDPR won't be fixed.

**Comment by Jose1971AB** [comment]
Hello @uBlock-user 

> uBlock-user 
Anti-adblock fixed yesterday, cookie overlay's GDPR won't be fixed.

Sorry, my friend, I'm with the google translator and I didn't understand well. 

Did you say that the blocker warning was solved yesterday?... well I just checked now and it appears again

I don't quite know what you mean when you say cookie overlay's GDPR won't be fixed... can't be fixed?... what is "GDPR"?...

Greetings

**Comment by mapx-** [comment]
for libremercado add

```
libremercado.com#@#+js(set, publd.adBlockerDetected, noopFunc)
@@||libremercado.com^$xhr,1p
```

**Comment by uBlock-user** [comment]
> Did you say that the blocker warning was solved yesterday?... well I just checked now and it appears again

force update uBlock Filters.

**Comment by krystian3w** [comment]
> what is "GDPR"?...

GDPR =  RGPD 

[General Data Protection Regulation](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) - GDPR
[Reglamento General de Protección de Datos](https://es.wikipedia.org/wiki/Reglamento_General_de_Protecci%C3%B3n_de_Datos) - RGPD
[Regulamento Geral sobre a Proteção de Dados](https://pt.wikipedia.org/wiki/Regulamento_Geral_sobre_a_Prote%C3%A7%C3%A3o_de_Dados) RGPD

**Comment by Jose1971AB** [comment]
Hello good evening

**It has been solved**.

Thanks to mapx- @uBlock-user and @krystian3w for your participation

Thanks also to @krystian3w for the explanation of GDPR

Greetings to all

**Comment by PIZZA90** [comment]
what does this filter?: 🤔

`libertaddigital.com##body:style(overflow:auto !important)`

a big scroll in botton page

`https://www.libertaddigital.com/`

**Comment by okiehsch** [comment]
It reenables scrolling on articles, for example go to 
`https://www.libertaddigital.com/espana/2020-11-17/casado-defiende-que-en-su-discurso-de-la-mocion-no-hubo-ataques-personales-contra-santiago-abascal-6681221/`
and disable that filter, you will find that you can't scroll.

**Comment by PIZZA90** [comment]
aahh true.. 👍  but is that filter, making the other scroll appear? 🙄

It's not a annoying, I thought it was an outdated filter.

**Comment by okiehsch** [comment]
> but is that filter, making the other scroll appear? 

Yes, that is a side effect of that filter.
