### ISSUE TITLE
userload.co

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8156]
### URL(s) where the issue occurs

`https://userload.co/e/a76c49afc786`

### Describe the issue

popup ads

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.30.9b7

### Settings

uBO's default settings
-

**Comment by ghajini** [comment]
popups  ,opera browser stable , ubo 1.32.5b4
`https://userload.co/embed/7933660d5c9b/`

**Comment by ghajini** [comment]
Antiadblock

`https://userload.co/embed/17168490b515/`

![image](https://user-images.githubusercontent.com/20338483/107660380-3426cf00-6cae-11eb-82e1-824f65a22d87.png)

**Comment by ghajini** [comment]
Did that work? 

This work for me
`userload.co##+js(nostif, document.getElementById, 500)`

**Comment by mapx-** [comment]
working fine FF / chrome u-u filter

**Comment by uBlock-user** [comment]
> Did that work?

Yes, works for me.

**Comment by ghajini** [comment]
Not work
Firefox /opera
