### ISSUE TITLE
usbank.com: "Log in" button broken

### ISSUE THREAD

**Issue by kevinoid** [uBlockOrigin/uAssets#8158]
### URL(s) where the issue occurs

`https://www.usbank.com/index.html`

### Describe the issue

When displayed in a viewport at least 1140px wide, the login box does not appear by default and clicking the red "Log in" button in the upper-right corner of the page does not display it (although it does dim the lower portion of the page).

### Screenshot(s)

![usbank com-no-log-in](https://user-images.githubusercontent.com/336433/98273574-552ea400-1f8a-11eb-926d-ec46047a9732.png)

### Versions

- Browser/version: Firefox 84.0a1 (2020-11-05) (64-bit)
- uBlock Origin version: 1.30.6

### Settings

Default.

### Notes

Same symptoms as #8013.
Adding `@@||tags.tiqcdn.com/utag/usbank/global-sync/prod/utag.sync.js$script,domain=www.usbank.com` avoids the issue.

**Comment by kevinoid** [comment]
Thanks @mapx-!

**Comment by mapx-** [comment]
thx for reporting 👍
