### ISSUE TITLE
Ublock Origin/Privacy Badger combo returns a 1004 error when accessing the echo test on bigbluebutton (BBB)

### ISSUE THREAD

**Issue by lelibreauquotidien** [uBlockOrigin/uAssets#8159]
Ublock Origin/Privacy Badger combo returns a 1004 error when accessing the echo test on bigbluebutton (BBB)

Hello.
The Ublock Origin/Privacy Badger combo returns a 1004 error when accessing the echo test on bigbluebutton (BBB).
I'm sure it's the fault of these 2 extensions, all my other extensions were disabled.
Deactivating one but leaving the other activated doesn't change anything.
I would like to specify that disabling tracing in the extensions menu is not enough, you have to disable the extension to have an effect.
My OS is Manjaro Linux and my browser is Firefox 82.0.2.
Also published on [Privacy Badger Repo](https://github.com/EFForg/privacybadger/issues/2711) and [BigBlueButton Repo](https://github.com/bigbluebutton/bigbluebutton/issues/10777)

**Comment by uBlock-user** [comment]
> Ublock Origin/Privacy Badger combo returns a 1004 error when accessing the echo test on bigbluebutton (BBB).

Specific page link ?

**Comment by gwarser** [comment]
https://github.com/EFForg/privacybadger/issues/2711#issuecomment-722559038
