### ISSUE TITLE
proxybit.casa

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8161]
### URL(s) where the issue occurs

`tamilmv.proxybit.casa`

### Describe the issue

popup ads as soon as one browses site

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.30.9b7

### Settings

 uBO's default settings
-

**Comment by ghajini** [comment]
1.
please make filter `proxybit.casa##+js(abort-on-property-write, _pop)` ,it will cover many sites as covered on their homepage proxy site
`https://user-images.githubusercontent.com/20338483/98335375-d5a4e180-202a-11eb-807d-4a16123224c0.png`

2.
i noticed popups at here again at
```
https://tamilmv.proxybit.casa/index.php?/forums/topic/106350-gatham-2020-telugu-true-web-dl-1080p-720p-61gb-36gb-18gb-12gb-950mb-650mb-x264-xvid-700mb-400mb-200mb-esub/&__cf_chl_jschl_tk__=16637375fa04e60f4575d15ad3fc494f22ca7cb0-1604645305-0-ATFiEC9Wv4yPL-CU20Nj0233eACmg_XBjhctmLspnnbdICuP35YTtrAjLLq6hqCgE383TYQCDsxG5ZfHP4U1JoPhdmZUOZuWu9BSoxvMjv7542ugvSu-qIrjgOMOqqza5th3hYxQa67gAv91_jwP80XbOkscbQ25xAxEubsX8sKQAWigsERfnxC5zymCcLDWyt8oa2d_opuQqrLsBsxRmqi_WIhLPT8bMuXZIJVoN1dWm6kvJgrHN7PXDANlsCL0D5nnaUoCwRCxHHNVQVgFJpahkFQ2JLi_0GejzBOrLBLlyrq_ulM6gwceR98W3TRqoNS3NkvwoRWMjadrztnxvfm7Xid-I2gOMVJWJmV-TYHyXtkzY3JXt6HeS2bks3Ovj8WLfF1rQoNybyeARjLpWFDAmvKZ1qnB-saRnZJxzUjy8LtiFwvGDb09WjWGBgMVIkXikWaa_ECGDon8I6MPWe0
```

**Comment by okiehsch** [comment]
I can't reproduce point 2.

**Comment by ghajini** [comment]
yeah sometimes produce /sometimes not

this proxy site is nasty

this work on my end

`proxybit.casa##+js(acis, AdservingModule)`
`proxybit.casa##+js(aeld, , _0x)`

need to be confirmed by @mapx- , @uBlock-user

**Comment by ghajini** [comment]
`https://torrentdownload.proxybit.work/20E3FB76585B6D9FC27E83248A7E3C7DAAD42859/Scam-1992-the-Harshad-Mehta-Story-Hindi-S01-Complete-720p-WEBRip-2-9-GB-AAC-x264-Shadow-+BonsaiHD+`

filter
`proxybit.work##+js(acis, adcashMacros)`
