### ISSUE TITLE
arrowos.net (Anti adblock)

### ISSUE THREAD

**Issue by chelseaislan** [uBlockOrigin/uAssets#8163]
### URL(s) where the issue occurs
arrowos.net

### Describe the issue
Opening the site shows a message "Please disable your adblock and script blockers to view this page"

### Screenshot(s)
![image](https://user-images.githubusercontent.com/30471081/98345690-9638be00-2047-11eb-9954-71d8e4ffbe79.png)

### Versions
- Browser/version: Firefox 82.0.2
- uBlock Origin version: 1.30.6

### Settings
Easy mode + dynamic filtering for Facebook domains

**Comment by ChildishGiant** [comment]
This is currently an issue, as the changes explicitly allow the blockAdBlock 
![image](https://user-images.githubusercontent.com/13716824/104137404-3ab2e580-5394-11eb-8a26-9ff3dda200fd.png)

**Comment by okiehsch** [comment]
> This is currently an issue

Do you get an anti adblock message?

**Comment by ChildishGiant** [comment]
If I remove my dynamic filter, yes
![image](https://user-images.githubusercontent.com/13716824/104137712-c0d02b80-5396-11eb-9383-40490eabb961.png)

**Comment by okiehsch** [comment]
Hm, I can't reproduce, I do get the message in the screenshot of the OP if I block the the blockAdBlock request.

Does it work if you add
`arrowos.net##+js(nosiif, visibility, 1000)`
to your filters?

**Comment by uBlock-user** [comment]
`$ghide` filter works exactly for this so the anti-adb never appears, test on default settings.
