### ISSUE TITLE
Change hosting for Easylist Cookie and Annoyances

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uAssets#8166]
Hi,
Just some list host housekeeping, can I remove the following:

Please remove `https://easylist.to/easylist/fanboy-annoyance.txt`

and change `https://easylist-downloads.adblockplus.org/easylist-cookie.txt` too `https://secure.fanboy.co.nz/fanboy-cookiemonster.txt`

**Comment by mapx-** [comment]
@gorhill

**Comment by uBlock-user** [comment]
> Please remove https://easylist.to/easylist/fanboy-annoyance.txt

Why ?

**Comment by ryanbr** [comment]
Legal reasons. I can host these files.

**Comment by uBlock-user** [comment]
You didn't suggest the replacement for Annoyances list in that statement, hence the question. Replacement url ?

**Comment by ryanbr** [comment]
`"https://fanboy.co.nz/fanboy-annoyance.txt` still exists.

**Comment by gorhill** [comment]
Which one is preferable between:

- `https://fanboy.co.nz/fanboy-annoyance.txt`
- `https://secure.fanboy.co.nz/fanboy-annoyance.txt`

?

**Comment by ryanbr** [comment]
`https://secure.fanboy.co.nz/fanboy-annoyance.txt` is fine thanks

**Comment by ryanbr** [comment]
Will it redirect users to the new url's @gorhill  ?

**Comment by gorhill** [comment]
If `https://easylist.to/easylist/fanboy-annoyance.txt` returns an error uBO will fall back to using `https://secure.fanboy.co.nz/fanboy-annoyance.txt`.

**Comment by krystian3w** [comment]
these also remove?

https://easylist.to/easylist/fanboy-annoyance.txt

**Comment by krystian3w** [comment]
What happend with: https://easylist.github.io/easylist/fanboy-annoyance.txt
