### ISSUE TITLE
hiidudemoviez.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8167]
### URL(s) where the issue occurs

`https://hiidudemoviez.com/the-spongebob-movie-sponge-on-the-run-2020-telugu-dubbed-movie.html`

### Describe the issue

popup ads

### Versions

- Browser/version: firefox 82
- uBlock Origin version: 1.30.6

**Comment by ghajini** [comment]
site changed to `https://hiidudemoviez.online` & there are popup ads

**Comment by ghajini** [comment]
Site Changed again

`https://3hiidude.com/watch-master-2021-online-tamil-full-movie-download-4863.html`

Popup ads ,opera browser stable

**Comment by ghajini** [comment]
i see propeller crap requests when clicking play as reported above

**Comment by ghajini** [comment]
on refresh or clicking next player crap is back
![image](https://user-images.githubusercontent.com/20338483/105368994-1a064d80-5c28-11eb-8abf-638e16a54a24.png)

**Comment by mapx-** [comment]
does this work for you ?

`3hiidude.com##+js(aopr, String.fromCharCode)`

**Comment by ghajini** [comment]
yes

**Comment by ghajini** [comment]
Site changed to `3hiidude.me`
Update to

```
3hiidude.*##+js(aopr, String.fromCharCode)
||goaciptu.net^
```
