### ISSUE TITLE
NSFW Gelbooru thumbnails are not being shown

### ISSUE THREAD

**Issue by goldnharl** [uBlockOrigin/uAssets#817]
### URL(s) where the issue occurs

`https://gelbooru.com`

### Describe the issue

Recently (within the past two weeks) Gelbooru has been blocking thumbnails from uBlock users (or any adblock users, I'm sure). Upon loading tags, the first page of images loaded always shows thumbnails, but any subsequent pages default to the "DOWNLOAD" thumbnail.

### Screenshot(s)

N/A

### Versions

- Browser/version: Version 49.0.2623.112 m (Windows XP)
- uBlock Origin version: 1.14.16 (current)

### Settings

- None

### Notes

Disabling of uBlock results in the thumbnails once again reappearing, and no changes to what specific blocklists are enabled or disabled seems to matter. Anti-adblock scripts do not seem to work. Clearing cookies and logging out does not affect whether or not the thumbnails appear or not.

**Comment by goldnharl** [comment]
Browser is Google Chrome, can't edit the post for some reason. Clicking either edit button does nothing.

**Comment by okiehsch** [comment]
Works fine on my end with Chrome, Firefox and uBO-default setup.

You can't edit because Github does not support Chrome 49.

**Comment by lain566** [comment]
It's broken again :weary:

**Comment by okiehsch** [comment]
@lain566  the ads are back, but nothing is "broken" on my end.
This [filter](https://github.com/uBlockOrigin/uAssets/commit/81d5e0c5c67cdbeb8c3549a4a3c73b3a94dd9dde#commitcomment-25414381) still fixes the ad-issue, just add it to your filter list.

**Comment by lain566** [comment]
@okiehsch Yes, I was referring to the filter that I suggested, sorry for the confusion.

**Comment by okiehsch** [comment]
I tried with an old vista laptop and Chrome 49, uBO-1.14.6 and default-setup.
I can't reproduce, the thumbnails wrk fine on my end.
