### ISSUE TITLE
top.gg anti-adblock issues

### ISSUE THREAD

**Issue by soysuva** [uBlockOrigin/uAssets#8172]
### URL(s) where the issue occurs
https://top.gg/bot/555955826880413696/vote

### Describe the issue
The website "top.gg" added an anti-adblock system on their website to prevent users with adblock from voting recently. 
 

### Screenshot(s)
https://i.imgur.com/2647mSr.png

### Versions

- Browser/version: Chrome Version 86.0.4240.183 (PC), Firefox 82.1.1 (mobile)
- uBlock Origin version: 1.30.6 (PC chrome browser), 1.30.6 (mobile firefox browser)

### Settings

Chrome:
- enabled all built-in filters
- enabled all ads filters
- enabled all privacy filters
- enabled all Malware domains filter
- enabled AdGuard Annoyances filter
- enabled Anti-Facebook filter
- enabled EasyList Cookie filter
- enabled FanBoy's Annoyance filter
- enabled ublock 'filters' - Annoyances
- enabled Peter Lowe's Ad and tracking server list filter
- added "BarbBlock" custom filter

Firefox:
- enabled all built-in filters
- enabled all ads filters
- enabled EasyPrivacy filter
- enabled Online Malicious URL Blocklist filter
- enabled AdGuard Annoyances filter
- enabled Anti-Facebook filter
- enabled EasyList Cookie filter
- enabled FanBoy's Annoyance filter
- enabled Fanboy's Social Filter
- enabled ublock 'filters' - Annoyances
- enabled Peter Lowe's Ad and tracking server list filter

### Notes
I've updated my browser, extension, and filter on both my PC and mobile. They all get the same results like in the screenshot I showed, so that doesn't seem to be the issue. I've also tried using only ublock origin extension in incognito mode on the website, same results. It worked a couple of days ago, but now it doesn't work anymore on the website. Firefox with ublock (mobile version) is getting the same problems as well. I'm using chrome for PC browsers, but I'm pretty sure it's the same results with other browsers too.

**Comment by soysuva** [comment]
Okay, I think I solved it. I purged all the caches then updated the filters again. It works on both PC and mobile now.

**Comment by uBlock-user** [comment]
Added the filter yesterday itself, just force update the uBlock Filters list cache.
