### ISSUE TITLE
musicpleer.tv

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#8175]
### URL(s) where the issue occurs

`https://musicpleer.tv/`
Search for "test" and click any of Download button.

### Describe the issue

Popup leading to random crap sites.

### Screenshot(s)

![musicpleer1](https://user-images.githubusercontent.com/58900598/98438563-63b5c080-212e-11eb-8c5b-c12b48e906d0.png)

![musicpleer2](https://user-images.githubusercontent.com/58900598/98438565-66181a80-212e-11eb-8995-622e1d801575.png)

### Versions

- Browser/version: Firefox 82.0.2
- uBlock Origin version: 1.30.6

### Settings

- Default + AGJPN

### Notes

```
musicpleer.tv##+js(set, ADS_ACTIVATED, false)
musicpleer.tv##+js(nostif, ADS_ACTIVATED)
```
work on my end.

**Comment by mapx-** [comment]
Are you sure the site is working ? I get some weird page `lillill.li` always with some error, even on ESC I get a popup

**Comment by Yuki2718** [comment]
On my end working, can you test with Japanese VPN though I don't think the site is JP one.

**Comment by mapx-** [comment]
- sometimes cannot get the mp3 and you get a redirecting crap
- for mp4 I get always this crap: ()

`https://lllili.lillilliiil.li/download?id=yhS9LnDoo_w&t=_1604751243`

`<html><head><title>Please wait...</title></head><body><script>window.location.href = 'https://itnuzleafan.com/4/3372255';</script></body></html>`

**Comment by Yuki2718** [comment]
Hmm, I experience the same after clicking many links - it seems some links always lead to that, but as the domain is different every time (except for consisted only by i and l) maybe difficult to fix?
