### ISSUE TITLE
Outlook mail ad

### ISSUE THREAD

**Issue by ukheather** [uBlockOrigin/uAssets#8176]
### Description

On outlook mail there is a huge area of advertising for the mobile app on the right next to mail which I can't get rid of with any ublock filters.
I was using adguard before and I didn't have this issue with that.

I have tried every single filter including all ad blocking and annoyance filters available including the adguard ones (as this doesn't happen using adguard itself) but it still appears.

All filters tried, all the latest version. Even purged cache and updated and tried again but it remains. 

### A specific URL where the issue occurs

`https://outlook.live.com/mail/0/inbox`

### Steps to Reproduce

1. Open outlook mail
2. do nothing, on the right is your mail list on the left it should say something like "no message selected" but instead there is a huge add for the mobile app
3. 

### Expected behavior:

it should say something like "no message selected" 

### Actual behavior:

A huge mobile app ad
![ad](https://user-images.githubusercontent.com/32431390/98442760-98118880-20fe-11eb-9c6d-62b8fab90d3b.PNG)

### Your environment

* uBlock Origin version: 1.30.6
* Browser Name and version: Firefox 82.0.2 (64 bit)
* Operating System and version: Windows 10

**Comment by gorhill** [comment]
Looks like self-promotion, which might be taken care of with one of the _Annoyances_ lists.

**Comment by ukheather** [comment]
I have tried all of the ad and annoyance filters but not one blocked it sadly

**Comment by krystian3w** [comment]
So report via this:


https://agrd.io/report and mark as active `AdGuard Annoyance`.

**Comment by mapx-** [comment]
test this filter, see if is breaking something:

`outlook.live.com##[href^="https://go.microsoft.com/fwlink/?linkid"][target="_blank"]:upward(6)`

**Comment by llacb47** [comment]
@mapx- not a good idea, that will block all informational popups as well most likely -- too broad.

**Comment by mapx-** [comment]
yeah, I know, I'd not add it in any list - only a suggestion if OP want to use it as custom filter

**Comment by ukheather** [comment]
> 
> 
> So report via this:
> 
> https://agrd.io/report and mark as active `AdGuard Annoyance`.

why would I need to report via adguard? If I use the adguard extension it blocks it fine. It is just using the ublock extension I see the ad

**Comment by krystian3w** [comment]
> ? If I use the adguard extension it blocks it fine.

So check **what filter hide ad** when use AdGuard Adblocker, maybe needed is enable **AdGuard Base** instead of *Adguard Annoyance*.

**Comment by ukheather** [comment]
But as I said I tried all the filters on ublock and none block it.
All of them.
That includes all the adguard filters on unlock

So I could have every single filter ticked on ublock and I still get the ad.

Not sure why this got closed? It’s still happening?

**Comment by mapx-** [comment]
@ukheather did you test the filter I posted above ?

**Comment by mapx-** [comment]
@krystian3w if you don't test the filters it's bad to add just noise to the thread.

**Comment by ukheather** [comment]
The link from 5 hours ago (self-promo.txt)? How do you add that to ublock? 
I have just used the ones that show on the app by default 

I tried the one you posted 20 hours ago but that caused many issues 
“ outlook.live.com##[href^="https://go.microsoft.com/fwlink/?linkid"][target="_blank"]:upward(5).

**Comment by krystian3w** [comment]
Or use inverted whitelist:

`extension://pdffkfellgipmhklpdmokmckkkfcopbh/pages/options.html#whitelist`
`chrome-extension://bgnkhhnnamicmpeenaelnjfhikgbkllg/pages/options.html#whitelist`


![obraz](https://user-images.githubusercontent.com/35370833/98472358-cc667100-21f2-11eb-9846-90fa1681ff5d.png) |
--- |

**Comment by ukheather** [comment]
> @krystian3w if you don't test the filters it's bad to add just noise to the thread.

I had no idea that link was a filter I could ad which is why I just asked..



> Or use inverted whitelist:
> 
> `extension://pdffkfellgipmhklpdmokmckkkfcopbh/pages/options.html#whitelist`
> `chrome-extension://bgnkhhnnamicmpeenaelnjfhikgbkllg/pages/options.html#whitelist`
> 
> ![obraz](https://user-images.githubusercontent.com/35370833/98472358-cc667100-21f2-11eb-9846-90fa1681ff5d.png)


I don’t want to whitelist the domain? I want to block numerous ads on outlook.com. It wasn’t blocking one which is why I posted?

**Comment by krystian3w** [comment]
When AdGuard Adblocker works on only twitch and outlook - is recommended if AdGuard replace hide SSAI ads.

**Comment by ukheather** [comment]
> When AdGuard Adblocker works on only twitch and outlook - is recommended if AdGuard replace hide SSAI ads.

It is recommended to whitelist ads?
But that would defeat the issue I raised initially? I was hoping to block this ad that isn’t getting blocked on ublock.

Getting lost now
The manual filter from yesterday didn’t work, I asked if that link posted to “self promo” was a filter I have to manually add as that wasn’t mentioned hence my issue still is happening but now I feel I’m just causing bother even replying.

The issue was still happening to me today as of 5 hours ago. 
I hadn’t been told to add a new filter or anything but one person told me I’m adding “noise” to the thread even though I’d tried things I have been specifically asked to try. Only thing I didn’t understand was the link from 5 hours ago and white listing ads as I don’t want to unblock ads.

**Comment by mapx-** [comment]
you could at least block the image:

`||outlook-1.cdn.office.net/owamail/*/resources/img/outlook-mobile-apps.png$image`

**Comment by ukheather** [comment]
> you could at least block the image:
> 
> `||outlook-1.cdn.office.net/owamail/*/resources/img/outlook-mobile-apps.png$image`

I tried blocking the image but it just blocks the bottom large phone image one, not the text above which is 3 or 4 different images of the ad rather than one total ad image.
Like top like is one image, second is another etc.

Tried it again and yep it just blocks the phone image not the other parts of the ad so doing that only hides the phones.

I just thought it was weird that the adguard extension blocks it fine yet no ublock filter do even though some are adguard filters

**Comment by krystian3w** [comment]
```
##div[aria-label="Reading Pane"] > div > div > div > div > div:has(> div input[placeholder="+1 (702) 123-4567"])
```

Easy

**Comment by gorhill** [comment]
I am not able to reproduce that big self-promotion ad on my side, I just have a small right bar with _"It looks like you're using an ad blocker. To maximize the space in your inbox, sign up for Ad-Free Outlook."_ -- I would be able to investigate if I could reproduce.

**Comment by krystian3w** [comment]
Right anti-adblock section is hidden by procedural filtering, use  https://github.com/gorhill/uBlock/wiki/Resources-Library maybe better.

**Comment by krystian3w** [comment]
I suppose possible hide self-promotion by some like `nosiif` / `nostif` - ad is loaded by javascript after few seconds.

**Comment by gorhill** [comment]
@krystian3w Which Adguard filter is taking care of this?

**Comment by mapx-** [comment]
it works (but I don't know if breaks something)

`outlook.live.com##+js(nostif, tryRunTask, 500)`

**Comment by mapx-** [comment]
adguard (annoyances enabled) does not hide the mobile stuff

**Comment by krystian3w** [comment]
Now accept hide this crap ad, for my also right column again show anti-adblock info.

**Comment by JJenkx** [comment]
This is what I am using:
```

outlook.live.com##div:has(>div>div>span:has-text(It looks like you're using an ad blocker.))

outlook.live.com##div>button>div>span:has-text(Upgrade to Microsoft 365 with premium Outlook features)
```
