### ISSUE TITLE
clickyfly.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [uBlockOrigin/uAssets#8180]
URL(s) where the issue occurs
`http://clickyfly.com/mBZhvB`

Describe the issue
Anti adblock

Versions
uBlock Origin version 1.30.4

Browser/version
Opera

Settings
Ublock Origin default settings

**Comment by mapx-** [comment]
there are some redirections `clickyfly.com` => `absolutesmmpanel.com` => `myhiddentech.com`
