### ISSUE TITLE
ondebaixo.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#8182]
### URL(s) where the issue occurs

`https://ondebaixo.com/jesus-novela-completa-torrent-nacional-download/`

### Describe the issue

A script changes the download links when you click on them to show you popups. 

### Screenshot(s)

![popup](https://user-images.githubusercontent.com/35470489/98471479-5c90c000-21cb-11eb-944e-9ae6afb09ab6.png)

### Versions

- Browser/version: Firefox stable
- uBlock Origin version: 1.30.6

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin lists

**Comment by adranger** [comment]
@uBlock-user They have another domain too: `https://torrentool.org/jesus-novela-completa-download-torrent/`

**Comment by adranger** [comment]
@uBlock-user `https://ondebaixa.com/jesus-novela-completa-download-via-torrent/`

**Comment by adranger** [comment]
@uBlock-user `https://ondeeubaixo.org/jesus-novela-completa-torrent-download/`

**Comment by uBlock-user** [comment]
If you find more, make a list of them and then post the entire list here.
