### ISSUE TITLE
www.youporn.com [NSFW]

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#8184]
### URL(s) where the issue occurs

`www.youporn.com`
`https://www.youporn.com/watch/16251382/ultrafilms-legendary-ultra-hot-belle-claire-in-her-best-ever-anal-fucking-with-lots-of-orgasms/`

### Describe the issue

Ads

### Screenshot(s)

<details>

![youporn](https://user-images.githubusercontent.com/58900598/98486305-eb4f1c80-225f-11eb-8e14-9f5f3ceee880.png)

</details>

### Versions

- Browser/version: Firefox 82.0.2
- uBlock Origin version: 1.30.6

### Settings

- Default

### Notes

Some interaction will be needed to actually see the ads.
`youporn.com##+js(aopr, page_params.holiday_promo)`
seems to work.

**Comment by Yuki2718** [comment]
@okiehsch I guess I missed @lain566 's commit: https://github.com/uBlockOrigin/uAssets/commit/182ac943abf0223722cd2ab748ff756b35ab1aba

**Comment by okiehsch** [comment]
Oh, me too, I will remove my filter.
