### ISSUE TITLE
Filters wont activate untill new rule is added.

### ISSUE THREAD

**Issue by Frejoh466** [uBlockOrigin/uAssets#819]
### URL(s) where the issue occurs

All sites. For testing purpose using google.se

For example, having added "www.google.se##.fbar", deleting "AppData\Local\Mozilla\Firefox\Profiles\Profile" will make all filters invalid, and the bottom bar at google.se to still appear. In "My filters" the "www.google.com##.fbar" rule is still there. 

After adding a new rule, can be anything. All the filters will start working again, be it "My Filters" or "3rd-party filters". After removing an rule it will still be in effect until I add a new rule.

### Describe the issue

After deleting "AppData\Local\Mozilla\Firefox\Profiles\Profile" (Firefox cache) uBlock Origin will no longer use any filters until a new filter/rule is added. Removing filters/rules wont take effect until new rule is added. 

### Screenshot(s)

Google.se homepage after deleting cache.
https://i.imgur.com/wlrI3QS.jpg

Removing the "I'm lucky bar (Jag har tur).
https://i.imgur.com/yv5bg9K.jpg

Removing the I'm lucky rule, deleting cache in browser settings and updating site.
https://i.imgur.com/GF2CJoN.jpg

### Versions

- OS/version: Microsoft Windows [Version 10.0.16299.19]
- Browser/version: Firefox 57.0b14 (64-bit)
- Browser/version: Chrome Version 62.0.3202.75 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin 1.14.16

### Settings

Setting that are on,
Hide placeholders of blocked elements
Show the number of blocked requests on the icon
Make use of context menu where appropriate 
I am an advanced user
Disable pre-fetching (to prevent any connection for blocked network requests) 
Disable hyperlink auditing
Prevent WebRTC from leaking local IP addresses

##### Your filter lists

All filters except;
uBlock filters – Experimental
Basic tracking list by Disconnect​​​​​​​​​
Regions, languages  filters

##### Your custom filters (if any)

"www.google.se##.fbar"

### Steps for anyone to reproduce the issue

1. Add "www.google.se##.fbar" rule to "My filters"
2. Close Firefox
3. Delete "AppData\Local\Mozilla\Firefox\Profiles\Default.profile"
4. Start Firefox
5. visit google.se
6. Bottom bar is still there
7. Add new rule through the inspect element picker, on anything, and add it as a rule.
8. look at "My filters" and confirm both the old "www.google.se##.fbar" and the newly added rule is there.
9. visit google.se, and bottom bar is gone, with the newly added rule.

### Logger

Not sure how to read the logger but it seems to act just like no filters are there until I add new rule and all the other filters activates. 

When no filters works.
https://i.imgur.com/QSMV1oF.jpg

When filters works.
https://i.imgur.com/Zt5sNbT.jpg

### Notes

This happen both on Chrome and Firefox, adding a new rule will update/activate all filters. This first started happening after updating to Win10 fall update, I reinstalled the OS (formatted the SSD) and created new profiles and fresh installation files from respective web page. I also tried Firefox 56, Chrome 61 and 63, all have same problems.

After reading the contributing guidelines a few times and pondering for two hours while looking around, I decided to assume that this is a filter-related issue. And would be invalid to post on the main issue page.

**Comment by gwarser** [comment]
I cannot confirm on linux. 
Do you have "Show your windows and tabs from last time" enabled?

**Comment by Frejoh466** [comment]
No, I'm using showing blank page. 

I didn't have this problem before the Win 10 fall update.

**Comment by gorhill** [comment]
> After deleting "AppData\Local\Mozilla\Firefox\Profiles\Profile" (Firefox cache) uBlock Origin will no longer use any filters until a new filter/rule is added.

This makes no sense. `AppData\Local\Mozilla\Firefox\Profiles\Profile` is not "Firefox cache", it's your profile data. You are essentially breaking your Firefox and expect that magically uBO will still work all fine after deleting all its files.

**Comment by Frejoh466** [comment]
The path
\AppData\ **Local** \Mozilla\Firefox\Profiles\prqc03lq.default 
contain the folders, Cache2, jumpListCache, OfflineCache, safebrowsing, startupCache, tumbnails, and directoryLinks.json

The path
\AppData\ **Roaming** \Mozilla\Firefox\Profiles\prqc03lq.default
contain the profile folder.

The files and folders under **Local** include the browser cache (mostly html and images) and various non-personal data that Firefox can (eventually will) rebuild if you remove it.

**Comment by gorhill** [comment]
I don't have Windows, but from <https://github.com/gorhill/uBlock/tree/master/dist#firefox-legacy>, my understanding was that you were deleting the main profile.

uBO just uses the Firefox API to store stuff, Firefox decides where things are persisted -- uBO knows nothing about file system: your custom filters are saved through `browser.storage.local.set(...)` API, and read back through the `browser.storage.local.get(...)` API.

**Comment by gorhill** [comment]
> Google.se homepage after deleting cache.
> https://i.imgur.com/wlrI3QS.jpg

How many filters are reported as being loaded for _"My filters"_ in the _"3rd-party filters"_ pane?

**Comment by Frejoh466** [comment]
Updating Firefox 57b to 57 that was released today _seems_ to have fixed it. 

Now I can't update filters as they get stuck in "updating", and can't enter element picker mode, so can't test it more in depth. But it seems that the filter is still working after deleting the cache.

So solution was to update Firefox from 57 beta to 57 stable.

**Comment by Frejoh466** [comment]
I missed that uBlock was updated to uBlock Origin 1.14.18, so that might have been the fix to. Going to try uBlock Origin uBlock Origin 1.14.16 and see if problem is still there.

**Comment by Frejoh466** [comment]
Downgrading to uBlock Origin 1.14.16 with Firefox 57 and deleting the cache make my filters inactive. My filters says that 1 of 1 filter is active.

But upgrading to uBlock Origin 1.14.18 solves that problem. But breaks element picker and updating of filters.
