### ISSUE TITLE
Recent change to filters completely broke javascript on next-episode.net

### ISSUE THREAD

**Issue by santah** [uBlockOrigin/uAssets#8191]
As I'm not sure where the best place to report it is - I've commented on the commit, but also here:

This commit:

https://github.com/uBlockOrigin/uAssets/commit/1662e682d2d065bbfa037740ba5020a7d89bbfac

broke javascript on next-episode.net

Please revert it.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/5f1440687ff3e72f8e6ddd12b2725e7f172c6204
