### ISSUE TITLE
Wstream detect adblock

### ISSUE THREAD

**Issue by tonicofonico** [uBlockOrigin/uAssets#8193]
### URL(s) where the issue occurs

`https://wstream.video/video6zvimpy52/4zq6zkzjsfdp`

### Describe the issue

Now wstream detect ublock

### Screenshot(s)
![Screenshot_2020-11-10 Wstream Free Streaming Service](https://user-images.githubusercontent.com/20930461/98693100-26d90c00-2370-11eb-8c06-4ed680bd1c0c.png)

### Versions

- Browser/version: Firefox 82.0.3
- uBlock Origin version: 1.30.6

**Comment by Yuki2718** [comment]
No actual issue thx to @@ exception in Unbreak but `hcaptcha.com` should be added to denyallow.
