### ISSUE TITLE
animesonline.cz has detected adblock

### ISSUE THREAD

**Issue by HenriqueVP** [uBlockOrigin/uAssets#8194]
### URL(s) where the issue occurs
https://www.animesonline.cz/

### Describe the issue
JW Player 8.16.0 is detecting adblock and requesting to disable it. The website and the video player are detecting adblock. The website has a popup screen warning of adblock but you can just close it.
 

### Versions

- Browser/version: Google Chrome 86.0.4240.183
- uBlock Origin version: uBlock Origin v1.30.6

### Settings
I did some changes way back when nano defender existed and dont remember everything. I also use Tampermonkey with antiadblock scripts.

-

**Comment by HenriqueVP** [comment]
Nevermind, I updated the filter list and chrome and now the problem is gone

**Comment by HenriqueVP** [comment]
WTF, the problem came back out of nowhere.

**Comment by mapx-** [comment]
fixed
