### ISSUE TITLE
GMX "consent-management" redirection

### ISSUE THREAD

**Issue by H34dl3ss** [uBlockOrigin/uAssets#8196]
### URL(s) where the issue occurs
`https://www.gmx.net/`

### Describe the issue
It seems to happen randomly, as a topic is selected, the target will be replaced with

`https://www.gmx.net/magazine/consent-management/`

Deleting the part /consent-management/ in the adress bar will allow you to browse without interruption for some time until the
redirection kicks in again.

Is there a way to prevent the redirection?

### Versions

- Browser/version: FF 82.0.3
- uBlock Origin version: uBlock Origin v1.30.6

### Settings

- just some filters to block google and utube cookie popup

### Notes
Searched through the issues and didn't found a solution yet.

**Comment by uBlock-user** [comment]
> GDPR messages will not be addressed in uAssets.

**Comment by smed79** [comment]
To avoid the "consent-management" redirection bookmark `https://www.gmx.net/?origin=lpc`

https://www.camp-firefox.de/forum/thema/131271-datenschutzhinweis-auf-gmx/?postID=1153960#post1153960
