### ISSUE TITLE
Spanishdict Detects Adblock

### ISSUE THREAD

**Issue by SupremMotu** [uBlockOrigin/uAssets#8197]
### URL(s) where the issue occurs

https://www.spanishdict.com/

### Describe the issue

 
On the homepage and when I search a term, there is a box that indicates that SpanishDict detects my adblocker.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/47583325/98895105-27020600-245b-11eb-8ec6-0d496a420106.png)

![image](https://user-images.githubusercontent.com/47583325/98895132-3aad6c80-245b-11eb-917e-f6d7ee229fcf.png)

### Versions

- Browser/version: Chromium Version 86.0.4240.193 (Official Build) Arch Linux (64-bit)
- uBlock Origin version: 1.30.9.15 (although it happens on previous versions too)

### Settings

- no changes to any uBO default settings

### Notes

-  This didn't happen to me on NanoDefender, but Nano isn't exactly around anymore.

**Comment by llacb47** [comment]
Enable the annoyances list.

**Comment by okiehsch** [comment]
In contrast to Nano we fix anti adblock messages that don't block access to the site in the annoyance list.
This site is fixed if you enable `uBO-annoyances`.

**Comment by SupremMotu** [comment]
On the home page, the message is removed, but when I search something, the spacing is weird. 
![image](https://user-images.githubusercontent.com/47583325/98896261-6d586480-245d-11eb-817a-73ca5ceea38d.png)
