### ISSUE TITLE
hubdrive.xyz

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8198]
### URL(s) where the issue occurs

`hubdrive.xyz/file/2138091739`

### Describe the issue

Popup ads

### Versions

- Browser/version: opera and firefox browser stable
- uBlock Origin version: 1.30.6

### Settings

 uBO's default settings
-

**Comment by ghajini** [comment]
Also address 3rd party requests
![IMG_20201112_134544](https://user-images.githubusercontent.com/20338483/98913486-70029a80-24ed-11eb-8778-82d04d8d8b43.jpg)

With 

`hubdrive.xyz##+js(abort-current-inline-script, Math.imul)` 

Also block common trackers
(Last time I remember on `gdshare.xyz` ,now this website)

`||ejirytuw.xyz^`
`||ytymetuw.xyz^`

**Comment by ghajini** [comment]
another site where this crap main.js exists
`https://moviezcrush.com/download-scam-1992-the-harshad-mehta-story-season-1/`
i want to block that shady domains that always are random `*.main.js` 
how do i achieve with scriptlets

**Comment by mapx-** [comment]
race condition, only 
`*$script,3p,domain=moviezcrush.com` or csp filter
