### ISSUE TITLE
All aws s3 assets are blocked

### ISSUE THREAD

**Issue by jannes-io** [uBlockOrigin/uAssets#8199]
### URL(s) where the issue occurs

`https://acsystems-central-account-assets.s3-eu-west-1.amazonaws.com/production/applications.json`
`https://acsystems-central-account-assets.s3-eu-west-1.amazonaws.com/production/switcher/app-switcher.min.js`
`https://acsystems-central-account-assets.s3-eu-west-1.amazonaws.com/production/profile/my-account.min.js`

### Describe the issue

It appears that ALL AWS S3 links are blocked.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/9079379/98937214-5dd12e00-24e6-11eb-8013-98ac0851cfb8.png)

### Versions

- Browser/version: Firefox Developer Edition 83.0b10
- uBlock Origin version: 1.30.6

### Settings

- None, standard installation

### Notes

I did a quick ctrl+f on the filters but wasn't able to really locate a single one that just blocks all of S3. I am also not familiar with filters and their syntax.

**Comment by mapx-** [comment]
update easyprivacy list then test again

**Comment by okiehsch** [comment]
Have you updated you filter lists? Specifically EasyPrivacy.
https://github.com/easylist/easylist/commit/b7d89d6417166c6a247fdb782903db40781e2732
was blocking those requests bit it has since then been updated.

**Comment by jannes-io** [comment]
Awsome! That has fixed it for us.

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/commit/2a4434cb2fbc643cd3c056d4bd7cb6984c30762e
