### ISSUE TITLE
MindGeek (Pornhub Network and Spankwire Sites) crawler

### ISSUE THREAD

**Issue by flyingzebras** [uBlockOrigin/uAssets#82]
@gorhill 

Here's a script I made to index ads from the most popular pornsites.

https://github.com/abby-sergz/abpcrawler/compare/master...flyingzebras:patch-1
https://github.com/abby-sergz/abpcrawler/compare/master...flyingzebras:patch-2
https://github.com/abby-sergz/abpcrawler/compare/master...flyingzebras:patch-3

Why do I post here? Because the Adblock Plus company, Eyeo Inc., do not use it yet. It would be good if it came to use.

I would be glad if you tried it just to see how it works. Even if you won't use it might inspire you to do similar works for Assets.

Regards!

**Comment by flyingzebras** [comment]
https://github.com/gorhill/uBlock/issues/1357

**Comment by gorhill** [comment]
> I would be glad if you tried it just to see how it works

Just do not have the time.

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by gorhill** [comment]
Blocked for spamming issue tracker.
