### ISSUE TITLE
Blocking Google Analytics breaks flipagram

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#820]
### URL(s) where the issue occurs

`https://flipagram.com/`

### Describe the issue

Select any video. Then select any video on the right "related videos" section. Won't work unless you right click>open in new tab. (Or let the selected video finish and it won't auto-advance to the next video). Also breaks comments. Also can't click on the person's profile (bottom left of video). And heart button broken.

### Versions

- Browser/version: [Chrome 61]
- uBlock Origin version: [1.14.16]

### Settings

Default

**Comment by mapx-** [comment]
add
`@@||google-analytics.com/analytics.js$script,domain=flipagram.com`

if you enabled also experimental filters, well, you have to disable the google-analytics filter using:
`||google-analytics.com/analytics.js$important,script,badfilter`

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/de377f48fa3c31b06c97348ee26f83fdfc463fa3

**Comment by LoganDark** [comment]
This pull request is hilarious. I'm disappointed it was accepted.

**Comment by gorhill** [comment]
If a site breaks, users may be motivated to disable entirely their blocker to unbreak it. This is a worst outcome than just allowing `google-analytics.com`. For those who feels strongly about exceptions for `gogle-analytics.com`, use dynamic filtering to override exception filters, it's one of its main purpose.
