### ISSUE TITLE
store.petvalu.com/us/

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#8200]
### URL(s) where the issue occurs

`https://store.petvalu.com/us/`

### Describe the issue

Deny location permission. Unable to manually enter location.

### Notes

`@@||extreme-ip-lookup.com/json/*$xhr,domain=store.petvalu.com`

**Comment by krystian3w** [comment]
For me found few locations when sended twice `NewYork`.

**Comment by okiehsch** [comment]
@terrorist96 Is
`store.petvalu.com##.store_locator_loading`
fixing the issue for you?

**Comment by terrorist96** [comment]
Yes.
