### ISSUE TITLE
Blocking acces to video.

### ISSUE THREAD

**Issue by yalbv11** [uBlockOrigin/uAssets#8201]
### Versions

- Browser/version: [Opera browser 72.0.3815.320]
- uBlock Origin version: [1.30.6]

### Settings

Ubo restored to default setting because of this issue 
-

**Comment by mapx-** [comment]
I guess this filter will help you:

`@@||cdn.tsyndicate.com/sdk/$script,domain=hpjav.tv`

**Comment by yalbv11** [comment]
Thank you for your help, but still doesn't work. I try to click but stil player doesn't load nor access to video

**Comment by mapx-** [comment]
Did you update all your lists (purge all caches) after resetting to default ?

**Comment by yalbv11** [comment]
yes

**Comment by mapx-** [comment]
Are you using some other blocking extension ? I tested in opera and it's working fine ... maybe you should provide a video (link) which does not work for you

**Comment by mapx-** [comment]
Did you disable Opera builtin adblocker ?

**Comment by yalbv11** [comment]
I did, even before restore to default.

**Comment by yalbv11** [comment]
Restored ubo, from a file to the previous settings I had, added your filter and started to work
