### ISSUE TITLE
https://plugins.matomo.org/*

### ISSUE THREAD

**Issue by Starker3** [uBlockOrigin/uAssets#8204]
### URL(s) where the issue occurs
Multiple sub pages on: `https://plugins.matomo.org/`
For example:
`https://plugins.matomo.org/ActivityLog#preview`

### Describe the issue

 
Multiple sub-pages images do not show
### Screenshot(s)
![image](https://user-images.githubusercontent.com/20905821/99025430-b16a7700-25cd-11eb-869b-064c3fe7dfdb.png)

### Versions

- Browser/version: Firefox 82.0.3
- uBlock Origin version: 1.30.6

### Settings
Default settings

-

### Notes
Previously reported some pages here with broken images, but there are several others that are broken, and if any new ones get added those might be broken as well

**Comment by uBlock-user** [comment]
@ryanbr
