### ISSUE TITLE
prank.show

### ISSUE THREAD

**Issue by bogachenko** [uBlockOrigin/uAssets#8208]
This site - `https://prank.show/pranks` has a stub installed, it starts after listening to 10 pranks. On the 11th prank, the player is paused and an audio file is played that lasts exactly 11 seconds, here it is (for me, your hash may differ) `https://cdn.prank.show/prank/18445?session_token=l3ULz9YCS125iP3NLsHOA3CFhsrAXke4` This audio file says that today, based on the free account, your listening is over, can you get around it? I tried, it didn't work.

<details><summary><b>Login</b></summary>
Email - jafaj23438@testbnk.com<br/>
Pass - jafaj23438
</details><br/>

**Comment by mapx-** [comment]
invalid email

![image](https://user-images.githubusercontent.com/10303732/99079273-030c0500-25c0-11eb-9f82-62e39a4e9bf7.png)

**Comment by bogachenko** [comment]
Strange, I'm in the system under this email. You can register yourself using temp-mai.org. PLZ. There you will receive a verification email and you will be allowed in.

**Comment by mapx-** [comment]
However, I guess it's nothing to do for

> based on the free account, your listening is over

**Comment by mapx-** [comment]
It's equivalent to a paywall, so .. closing

**Comment by bogachenko** [comment]
Do you have a paywall point? Don't you work with him anymore?
