### ISSUE TITLE
ntn24america.com

### ISSUE THREAD

**Issue by MikeMilligan** [uBlockOrigin/uAssets#821]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://www.ntn24america.com/noticia/aparece-golpeado-desorientado-y-semidesnudo-el-reportero-venezolano-jesus-medina-tras-tres-dias-157174`

### Describe the issue

With uBlock Origin enabled I cannot play the videos since the site asks me to disable my ad blocker.

### Screenshot(s)

https://i.imgur.com/mJgtJlB.png

### Versions

- Browser/version: Firefox 57.0
- uBlock Origin version: 1.14.18

### Settings

Default

**Comment by mapx-** [comment]
add
```
@@||ntn24america.com/*ads
@@||freegeoip.net/json/*$xmlhttprequest,domain=ntn24america.com
```

**Comment by MikeMilligan** [comment]
Thanks a lot. It works!
