### ISSUE TITLE
montrealgazette.com

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#8210]
### URL(s) where the issue occurs

`https://montrealgazette.com/news/police-operation-at-ubisoft-montreal-offices`

### Describe the issue

Due to `@@||montrealgazette.com^$generichide` in uAssets Main, there's a large placeholder in the middle of the article. I propose `montrealgazette.com##.ad__section-border`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/22780683/99113619-e091e000-25ef-11eb-99c7-2b8f83843ef4.png)

### Versions

- Browser/version: Chrome 86.0.4240.198 x64
- uBlock Origin version: 1.30.9rc0 + IDCAC 3.2.4

### Settings

![image](https://user-images.githubusercontent.com/22780683/99113755-0f0fbb00-25f0-11eb-9414-a76031eec9e8.png)
![image](https://user-images.githubusercontent.com/22780683/99113792-1b941380-25f0-11eb-8917-dbf429378a85.png)

### Notes

None that I'm currently aware of.

**Comment by nqlp** [comment]
There is a few ads leftovers:

https://github.com/user-attachments/assets/d0f850f5-2a47-4a17-9094-1a0cfc89a324

<details>

```
uBlock Origin: 1.66.0
Chromium: 140
filterset (summary):
 network: 181228
 cosmetic: 167140
 scriptlet: 42622
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 87662-270, now
  FRA-0: 19331-68, now
  fanboy-cookiemonster: 46307-3939, now
  fanboy-thirdparty_social: 69-0, now
  ublock-annoyances: 4672-157, now
  adguard-cookies: 35178-35178, now
  ublock-cookies-adguard: 5073-80, now
  ublock-cookies-easylist: 5073-5073, now
  adguard-popup-overlays: 28247-28247, now
  adguard-mobile-app-banners: 6345-6345, now
  adguard-other-annoyances: 14944-14944, now
  easylist-annoyances: 5144-409, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 22-0, never
  easylist: 80399-456, now
  easyprivacy: 54561-751, now
  plowe-0: 3432-0, now
  ublock-badware: 10993-73, now
  ublock-filters: 41188-530, now
  ublock-privacy: 3505-20, now
  ublock-quick-fixes: 312-1, now
  ublock-unbreak: 2683-43, now
  urlhaus-1: 31175-5, now
filterset (user): [array of 22 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 296 ms (selfie)
 maxAssetCacheWait: 52 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 22
 network:
  montrealgazette.com: 3
  ads-twitter.com: 1
  amplitude.com: 1
  braze.com: 1
  facebook.net: 1
  googletagmanager.com: 2
  htlbid.com: 2
  imrworldwide.com: 1
  licdn.com: 1
  ml314.com: 1
  parsely.com: 1
  quantserve.com: 1
  redditstatic.com: 1
  scorecardresearch.com: 1
  stackadapt.com: 1
  thecontentserver.com: 1
  trueanthem.com: 1
  viafoura.co: 1
 extended:
  ###googlead
```

</details>

**Comment by mapx-** [comment]
```adb
montrealgazette.com##[data-type="ad"]
montrealgazette.com###zoneContainer:has([data-type="ad"])
```

**Comment by nqlp** [comment]
Huge banner ad leftover:

<img width="1440" height="649" alt="Image" src="https://github.com/user-attachments/assets/fe025448-48d6-404a-919d-cb7d8162dd56" />

<details>

```yml

uBlock Origin: 1.73.0
Chromium: 151
filterset (summary):
 network: 201669
 cosmetic: 178122
 scriptlet: 57301
 html: 0
listset (total-discarded, last-updated):
 added:
  ublock-experimental: 11-2, now
  adguard-cookies: 39960-111, now
  ublock-cookies-adguard: 5831-80, now
  fanboy-cookiemonster: 47745-3997, now
  ublock-cookies-easylist: 5831-5831, now
  adguard-popup-overlays: 32933-255, now
  adguard-mobile-app-banners: 7911-108, now
  adguard-other-annoyances: 16565-200, now
  easylist-annoyances: 5256-381, now
  easylist-notifications: 2544-619, now
  ublock-annoyances: 4970-163, now
  FRA-0: 17571-263, now
 default:
  user-filters: 4-0, never
  ublock-filters: 53033-87, now
  ublock-badware: 10204-17, now
  ublock-privacy: 4134-4, now
  ublock-unbreak: 2802-1, now
  ublock-quick-fixes: 493-0, now
  easylist: 86446-482, now
  easyprivacy: 56399-733, now
  urlhaus-1: 47345-6, now
  plowe-0: 3516-0, now
filterset (user): [array of 4 redacted]
userSettings:
 advancedUserEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings:
 userResourcesLocation: [redacted]
supportStats:
 allReadyAfter: 354 ms (selfie)
 maxAssetCacheWait: 130 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 54
 network:
  amazon-adsystem.com: 1
  amplitude.com: 1
  connatix.com: 4
  criteo.net: 1
  doubleclick.net: 1
  googlesyndication.com: 2
  googletagmanager.com: 1
  imasdk.googleapis.com: 2
  jsdelivr.net: 1
  jwpltx.com: 14
  kindhush.com: 2
  liadm.com: 2
  permutive.app: 5
  permutive.com: 7
  q0losid.com: 1
  qortex.ai: 1
  rapidedge.io: 1
  rubiconproject.com: 2
  scorecardresearch.com: 2
  wp.com: 3
 extended:
  ##[data-ad-position]
  ##+js(remove-node-text, script, /\(\)=>eval|html-load\.com|await…
  ##+js(trusted-replace-argument, Element.prototype.setAttribute, …
  ##+js(remove-node-text, script, /window\.admiral|adblockerDisabl…
  ##+js(prevent-clipboard-write, /^mshta |^msiexec |^(bash <<<|cur…
```

</details>

**Comment by gothic-bum** [comment]
@nqlp 

Unable to reproduce the issue using `https://montrealgazette.com/news/quebec-wakes-to-worst-case-scenario-as-trump-slaps-new-50-tariffs-on-canada/`

Please test again using a new browser profile with only uBO and its default settings.

**Comment by nqlp** [comment]
So I've tried on Edge with a new browser profile with its default settings and it is still happening.

**Comment by gothic-bum** [comment]
Can you test:  

    ||montrealgazette.com/wp-content/themes/postmedia-master/build/components/timed-sticky/index.js^

**Comment by nqlp** [comment]
> Can you test:
> 
> ```
> ||montrealgazette.com/wp-content/themes/postmedia-master/build/components/timed-sticky/index.js^
> ```

Unfortunately, it doesn't work

**Comment by gothic-bum** [comment]
Using the new Edge profile, can you post the troubleshooting information from: `https://montrealgazette.com/news/quebec-wakes-to-worst-case-scenario-as-trump-slaps-new-50-tariffs-on-canada/`

**Comment by nqlp** [comment]
```yml

uBlock Origin: 1.73.0
Chromium: 151
filterset (summary):
 network: 181746
 cosmetic: 43604
 scriptlet: 37462
 html: 0
listset (total-discarded, last-updated):
 default:
  user-filters: 1-0, never
  ublock-filters: 53032-76, 35m
  ublock-badware: 10204-17, 35m
  ublock-privacy: 4134-3, 35m
  ublock-unbreak: 2802-1, 35m
  ublock-quick-fixes: 493-9, 35m
  easylist: 86345-139, 35m
  easyprivacy: 56399-43, 35m
  urlhaus-1: 47345-6, 35m
  plowe-0: 3516-1035, 35m
filterset (user): [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1265 ms
 maxAssetCacheWait: 3 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 43
 network:
  montrealgazette.com: 1
  amazon-adsystem.com: 2
  amplitude.com: 1
  connatix.com: 2
  criteo.net: 1
  doubleclick.net: 2
  googlesyndication.com: 2
  googletagmanager.com: 2
  imasdk.googleapis.com: 2
  jsdelivr.net: 1
  jwpltx.com: 5
  kindhush.com: 2
  liadm.com: 2
  permutive.app: 3
  permutive.com: 5
  q0losid.com: 1
  qortex.ai: 1
  rapidedge.io: 1
  rubiconproject.com: 2
  scorecardresearch.com: 2
  wp.com: 3
 extended:
  ##+js(remove-node-text, script, /\(\)=>eval|html-load\.com|await…
  ##+js(trusted-replace-argument, Element.prototype.setAttribute, …
  ##+js(remove-node-text, script, /window\.admiral|adblockerDisabl…
  ##+js(prevent-clipboard-write, /^mshta |^msiexec |^(bash <<<|cur…
```

**Comment by gothic-bum** [comment]
I'm not sure why your troubleshooting info isn't showing that any cosmetic filters are being applied on the page. 
  
Try testing again after adding to "My filters":  
  
    montrealgazette.com###ad-1
    montrealgazette.com###ad-2
    montrealgazette.com##.pm-ad
    montrealgazette.com##.pmd-ad-content

**Comment by nqlp** [comment]
Nope. Still doesn't work

**Comment by gothic-bum** [comment]
Can you try using Firefox?
  
This may help to determine if the issue is browser-specific.

**Comment by nqlp** [comment]
> Can you try using Firefox?
> 
> This may help to determine if the issue is browser-specific.

I can confirm that it's only happening on Chromium. Firefox has no issue

**Comment by gothic-bum** [comment]
Perhaps a volunteer who uses Edge can investigate further.

That said, you should be aware that Edge is dropping support for MV2 soon, and uBO will no longer function on Edge once that happens: https://blogs.windows.com/msedgedev/2026/08/07/moving-the-microsoft-edge-extensions-ecosystem-forward-with-manifest-version-3/

So switching to Firefox may be something you want to consider doing if you want to continue using uBO.

**Comment by nqlp** [comment]
> Perhaps a volunteer who uses Edge can investigate further.
> 
> That said, you should be aware that Edge is dropping support for MV2 soon, and uBO will no longer function on Edge once that happens: https://blogs.windows.com/msedgedev/2026/08/07/moving-the-microsoft-edge-extensions-ecosystem-forward-with-manifest-version-3/
> 
> So switching to Firefox may be something you want to consider doing if you want to continue using uBO.

Thanks for letting me know, but I'm using Brave as my main browser

**Comment by stephenhawk8054** [comment]
It's AS.
