### ISSUE TITLE
twitter.com: you cannot tweet "推荐".

### ISSUE THREAD

**Issue by fireattack** [uBlockOrigin/uAssets#8214]
### URL(s) where the issue occurs

https://twitter.com

### Describe the issue

Due to the rule (or similar, there a few of them)
```
twitter.com##:xpath(//span[(text()='Promoted' or text()='Gesponsert' or text()='Promocionado' or text()='Sponsorisé' or text()='Uitgelicht' or text()='推荐' or text()='プロモーション')]/../../../../..)
```

I can't type anything includes 推荐 or プロモーション in tweet, which will cause the text area to disappear.

### Screenshot(s)

![gifski75](https://user-images.githubusercontent.com/4130991/99140604-e516c280-2608-11eb-8352-1f6baa893ccf.gif)

### Versions

- Browser/version: [here] Chrome 86.0.4240.193
- uBlock Origin version: [here] v1.30.6

### Settings

- ublock filters

**Comment by llacb47** [comment]
Off-topic but what input tools are you using? It looks cool

**Comment by fireattack** [comment]
> Off-topic but what input tools are you using? It looks cool

Just a typical Chinese IME (Sogou IME)
