### ISSUE TITLE
www.toptenreviews.com

### ISSUE THREAD

**Issue by grande-mephistopheles** [uBlockOrigin/uAssets#8215]
### URL(s) where the issue occurs
`https://www.toptenreviews.com`

### Describe the issue
When visiting the site this notice comes up: "AD BLOCKER INTERFERENCE DETECTED"
 

### Versions

- Browser/version: Firefox 82.0.3 (64-bit)
- uBlock Origin version: 1.30.6

### Settings

All filters enabled

**Comment by uBlock-user** [comment]
Test on default settings.

**Comment by grande-mephistopheles** [comment]
> Test on default settings.

Same result

**Comment by uBlock-user** [comment]
Disable any other extension too, something is blocking the third-party CDN script on your end which triggers this anti-adblock.

**Comment by grande-mephistopheles** [comment]
Okay unblocking 3rd party scripts fixes this. but I don't want to allow it. Is there any dynamic filtering I can use?

**Comment by uBlock-user** [comment]
```
www.toptenreviews.com stackpathcdn.com * noop
www.toptenreviews.com footprint.net * noop
www.toptenreviews.com futurecdn.net * noop
```

on Firefox, nooping `futurecdn.net` on Chromium is enough.
