### ISSUE TITLE
billboard.com

### ISSUE THREAD

**Issue by heismauri** [uBlockOrigin/uAssets#8217]
### URLs

```
https://www.billboard.com/charts/billboard-global-200
https://www.billboard.com/charts/billboard-global-excl-us
```

### Describe the issue

script react-charts.js blocking the songs from 101-200, if blocked it can be seen but it breaks all the other elements in the page (no images and some pixelated images)

 

### Screenshot(s)
Without JS blocked

![Screenshot_2020-11-14 Billboard Global Excl US Chart Billboard](https://user-images.githubusercontent.com/47569205/99151549-de289800-267a-11eb-9f1e-f11524f241db.png)

With JS blocked

![Screenshot_2020-11-14 Billboard Global Excl US Chart Billboard(1)](https://user-images.githubusercontent.com/47569205/99151552-e4b70f80-267a-11eb-9998-b9c15c440ee2.png)

### Versions

- Browser/version: Latest
- uBlock Origin version: Latest

**Comment by mapx-** [comment]
It's kind of paywall, out of uBO's scope

**Comment by krystian3w** [comment]
@mapx- possible block this floating player in right corner, or also is out of scope?

`Demo:`

`##.brightcove-react-player-loader:matches-css(position: fixed):matches-css(bottom: 0):matches-css(right: 0)`

**Comment by mapx-** [comment]
It's not an ad, not even an annoyance
