### ISSUE TITLE
hikarinoakari.com 

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#8222]
### URL(s) where the issue occurs

`https://hikarinoakari.com/`
`https://hikarinoakari.com/the-idolmster-sidem-new-stage-episode-04-cafe-parade/`

### Describe the issue

Right click and copy disabled

### Versions

- Browser/version: [FF 82.0.3 X64]
- uBlock Origin version: [1.30.6]

### Settings

Default, AdGuard Base, AdGuard Annoyances, uBlock filters – Annoyances, EasyList Cookie, Fuck Fuckadblock, IDN, MYS: ABPindo ,

**Comment by uBlock-user** [comment]
> Right click 

Can't reproduce that, right click is working as expected. Selection fixed.

**Comment by exodius48** [comment]
> 
> 
> > Right click
> 
> Can't reproduce that, right click is working as expected. Selection fixed.

Now fixed, yes i mean selection , right click become '??' before but now fixed. Nice
