### ISSUE TITLE
bing.com

### ISSUE THREAD

**Issue by slaeprop** [uBlockOrigin/uAssets#8223]
### URL(s) where the issue occurs

`https://www.bing.com/search?q=test&cvid=8f7d2e372e94478b97e79feef0b31b10&pglt=129&FORM=ANNTA1&PC=U531`

### Describe the issue

scrolling does not work

### Versions

- Browser/version: [Microsoft Edge  86.0.622.69]
- uBlock Origin version: [1.30.6]

### Settings

uBlock filters – Annoyances, Fanboy’s Annoyance

**Comment by slaeprop** [comment]
when i am logged in it does not work. when i am logged out it works

**Comment by mapx-** [comment]
add

`bing.com#@##bnp_cookie_banner`

@ryanbr
