### ISSUE TITLE
update (add new)

### ISSUE THREAD

**Issue by retta1** [uBlockOrigin/uAssets#8224]
```
! 2020-11-12 https://forum.xda-developers.com
forum.xda-developers.com###adhesive_container
```

```
! 2020-11-13 https://www.youtube.com
www.youtube.com###masthead-ad
```

```
! 2020-11-15 https://filmakinesi.com
filmakinesi.com##.player-ustu-metin
filmakinesi.com##.player-alti-metin
```

```
! 2020-11-15 https://www.youtube.com
www.youtube.com##ytd-rich-item-renderer.ytd-rich-grid-renderer.style-scope:nth-of-type(1)
```

**Comment by krystian3w** [comment]
Try first report ads to EasyList.

@ryanbr / @khrin.

**Comment by krystian3w** [comment]
@pentagramtr  - have you ads on `filmakinesi.com`?

**Comment by mapx-** [comment]
- first YT filter already in easylist
- for the others you have to report to EL repository (YT, xda) indicating HOW-TO reproduce the ads
- for turkish site report at adguard filters repository

**Comment by PentagramTr** [comment]
@krystian3w 

Yes

<details><summary>Screenshot:</summary>

![filmakinesi com](https://user-images.githubusercontent.com/34379403/99199014-3cee2e80-27ad-11eb-9fde-61cd58bb6452.png)


</details>
