### ISSUE TITLE
magazyn.wp.pl [anti-adblock]

### ISSUE THREAD

**Issue by keczuppp** [uBlockOrigin/uAssets#8225]
### URL(s) where the issue occurs

`https://magazyn.wp.pl/`

### Describe the issue

permanent anti-adblock

### Screenshot(s)

![](https://camo.githubusercontent.com/5459b16e9a5d6f599e748df858d6e7af23b667bd/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f37696d6c3745302e6a7067)

### Versions

- Browser/version: Firefox 82.0.3 & Chropera 72.0
- uBlock Origin version: 1.30.9rc0

### Settings

default

### Notes / Hints

- the previous issue in uAssets somehow dissappeared nor the solution is working anymore
https://github.com/uBlockOrigin/uAssets/blob/7853b66ccb73ef0a327d0bc2904ccb061e27b030/filters/filters-2020.txt#L4900-L4901
- after enabling AdGuard Base list, the anti-adblock is gone but on Chrome-browsers only (related comments: https://github.com/AdguardTeam/AdguardFilters/issues/65865#issuecomment-713432295 + https://github.com/AdguardTeam/AdguardFilters/issues/65865#issuecomment-713480892)
- current issue in POL tracker: https://github.com/MajkiIT/polish-ads-filter/issues/17391
- helpful resources:
https://github.com/MajkiIT/polish-ads-filter/issues?q=is:issue+in:title+magazyn.wp.pl
https://github.com/olegwukr/polish-privacy-filters/issues?q=is:issue+in:title+magazyn.wp.pl
https://github.com/AdguardTeam/AdguardFilters/issues?q=is:issue+in:title+magazyn.wp.pl

**Comment by uBlock-user** [comment]
@keczuppp I see the same anti-adb overlay at `money.pl,komorkomania.pl,abczdrowie.pl,wiadomosci.wp.pl`, are they all owned by the same company ?

**Comment by uBlock-user** [comment]
Are these domains going to be fixed in the regional list ?

**Comment by bug-rules** [comment]
This is not certain, the problem can come back after 8-24 hours and MajkiIT and Olegwukr were not trained to quickly update the "`+js(`" filters.

The exceptions of cosmetic and network filters (`#@#` / `@@`) are rather no longer good for WP.

**Comment by keczuppp** [comment]
uBlock-user in case you or anybody from uAssets is interested, in [THIS](https://github.com/abp-filters/abp-filters-anti-cv/issues/183#issuecomment-622925067) comment (in the spoiler) is a complete list of all websites of WP Group (about ~ 100 !) and some additional info as well.

**Comment by Infiexe** [comment]
Not fixed
