### ISSUE TITLE
hurriyet.com.tr

### ISSUE THREAD

**Issue by BSboysan** [uBlockOrigin/uAssets#8226]
### URL(s) where the issue occurs

`https://www.hurriyet.com.tr/
`
### Describe the issue

It show up only when uBlock is enabled.
Cannot be reproduced with AdGuard.

### Screenshot(s)

<details>
 <summary>IMG</summary>

 
![www hurriyet com tr](https://user-images.githubusercontent.com/74098460/99200837-c8b98800-27b8-11eb-98c6-e8dbcad70982.png)

</details>

### Versions

- Browser/version: Chrome 86
- uBlock Origin version: 1.30.6

### Settings

```
AdGuard Base
AdGuard Tracking Protection
AdGuard Social Media
AdGuard Annoyance
AdGuard Turkish
NoCoin filter

```

**Comment by okiehsch** [comment]
It's fixed in `uBO-annoyances`.
If you click "Kapat" meaninng "Close" you can continue to use the site, so as far as uBO is cencerned it is an annoyance.
