### ISSUE TITLE
www.jpnn.com [weird copy]

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#8227]
### URL(s) where the issue occurs

`https://www.jpnn.com/news/warning-dari-avast-7-aplikasi-merugikan-di-hp-android-buruan-hapus`

### Describe the issue

When i select text/article, then copy it (ctrl+c), then IDM auto open and will download the link. Also at the end of copy result always there embedded text:

> Artikel ini telah tayang di
JPNN.com
dengan judul
"7 Aplikasi Merugikan di Hp Android, Buruan Hapus!",
`https://www.jpnn.com/news/warning-dari-avast-7-aplikasi-merugikan-di-hp-android-buruan-hapus`

### Versions

- Browser/version: [Firefox 82.0.3 X64]
- uBlock Origin version: [1.30.6]

### Settings

Default, AdGuard Base, AdGuard Annoyances, uBlock filters – Annoyances, EasyList Cookie, Fuck Fuckadblock, IDN, MYS: ABPindo , EasyList Cookie , Fanboy’s Enhanced Tracking List

**Comment by mapx-** [comment]
Idk for IDM, test:

`jpnn.com##+js(aopr, document.oncopy)`

**Comment by exodius48** [comment]
> 
> 
> Idk for IDM, test:
> 
> `jpnn.com##+js(aopr, document.oncopy)`

IDM auto open the link also `https://www.jpnn.com/news/warning-dari-avast-7-aplikasi-merugikan-di-hp-android-buruan-hapus` after i press ctrl+c, that filter seems work btw
