### ISSUE TITLE
businessinsider.in

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#823]
The comments section gets broken on http://www.businessinsider.in when uBO is enabled. It loads fine when its disabled. There are some blank ads in between articles as well.

**SS:** https://i.imgur.com/4sw3IRO.png

**Error URL:** 
http://www.businessinsider.in/disney-tried-to-hide-the-millennium-falcon-with-shipping-containers-but-its-on-google-maps/articleshow/61583817.cms

_**Note:** Using uBO 1.14.16 on Chrome 62 with the default filters and settings._

**Comment by mapx-** [comment]
add
```
@@||businessinsider.in/analytics_js/
@@||static.clmbtech.com^$script,domain=businessinsider.in
businessinsider.in##div.ArtInnerCont > div.mobile_padding > div > div:has-text(Promoted Stories)
businessinsider.in##DIV[data-fn*="data-ad-slot"]
```
