### ISSUE TITLE
Sushiswap.fi pools don't load - Etherscan queries blocked

### ISSUE THREAD

**Issue by LufyCZ** [uBlockOrigin/uAssets#8234]
### URL(s) where the issue occurs

```
https://sushiswap.fi/pools
https://sushiswap.fi/weekly
```

### Describe the issue

The screenshots explain it better than words could.

### Screenshot(s)

![chrome_2uUAOI536b](https://user-images.githubusercontent.com/20911347/99377232-ce77a200-287a-11eb-8f77-07ecbf43b642.png)
![chrome_FshHoMtK8x](https://user-images.githubusercontent.com/20911347/99377240-d0d9fc00-287a-11eb-8687-0d725f1537b3.png)

### Versions

- Browser/version: Chrome, Firefox - latest versions. Doesn't work on Brave either, but that's not under uBlock if I understand correctly.
- uBlock Origin version: 1.30.6

**Comment by mapx-** [comment]
test

`@@||api.etherscan.io/api$xhr,domain=sushiswap.fi`

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/72bd2806415aa4ab619f0ca28b2419846ff0e66e
