### ISSUE TITLE
nintendo.com issues

### ISSUE THREAD

**Issue by qhr-slava** [uBlockOrigin/uAssets#8239]
### URL(s) where the issue occurs

`https://www.nintendo.com/holiday/deals/`

And some other nintendo pages as well.

### Describe the issue

Ublock blocks everything on this page, it is empty.

### Screenshot(s)
Zoomed out up to 30% to show that there is no content on the page when ublock enabled.
![image](https://user-images.githubusercontent.com/59942112/99432245-b7f43980-28c0-11eb-96c4-3046984fc5e3.png)

Disabled ublock here, everything is fine.
![image](https://user-images.githubusercontent.com/59942112/99432372-eb36c880-28c0-11eb-8ed7-a4da28e9e971.png)

### Versions

- Browser/version: [Firefox 83.0]
- uBlock Origin version: [1.30.6]

### Settings

Advanced user enabled.
-

### Notes

Didn't investigate a lot, just checked that page loads without ublock

**Comment by mapx-** [comment]
add

`@@||nintendo.com/apps/*/scripts/analytics.js$script,1p`
