### ISSUE TITLE
streamp1ay.cc

### ISSUE THREAD

**Issue by aldiener58** [uBlockOrigin/uAssets#8244]
<I am new here and I am really trying to follow the rules as well as get support. If I make a mistake presenting my issue, please excuse my ignorance. 

It appears streamp1ay.cc is being highjacked to streanplay.cc
and videos no longer play. 

For transparency, I have posted this issue on EasyList Forums
and I have been assured the issue has been resolved. However, I have
taken extensive steps to implement the "new" filters and nothing seems
to work. I have deleted uBo entirely, clear browsing history, tried it on different
browsers, shut down my computer, etc. Nothing is working.>

<An example:>
###https://www1.swatchseries.to/freecale.html?r=bemyJkjdCI6IjBLVnNINhTVJYVBNbFzBuUUcrMmNbHQ2NlaXdzTXhZek42ZGFEYzdENG13NUdcL1wveDQrMlc0Z0xGNEk1TVY3U0pcL3IiLCJpdiI6IjVkNDFjZmQ0ZjEwYWVjZWZiMmI1OGQzNzUzNGM0OTg0IiwicyI6IjIyNjBmNjJjMGU4ODkwYTYifQ==

<Once you CLICK TO PLAY

You are briefly taken to the streamp1ay website and then are immediately re-directed to streanplay

An example:
The correct website is> 

###h??ps://streamp1ay.cc/m0ofro2l3bq5

<and the redirect is>

###h??ps://streanplay.cc/m0ofro2l3bq5 

<I couldn't figure out to stop these from showing up as links so I subbed ?? for the t's>

-Chrome Version 86.0.4240.198 (Official Build) (x86_64)
-uBo v1.30.6

<Did I do this right? Thank you for reading and any support you can offer. Sincerely, AD>

**Comment by aldiener58** [comment]
<If at the very least someone would be willing to point me to the Easy List Subscription filter that addresses this issue, I would be most grateful>

**Comment by okiehsch** [comment]
If I add
````
streanplay.cc##+js(nowebrtc)
streanplay.cc##+js(nowoif)
*$xhr,frame,3p,domain=streanplay.cc,denyallow=spcdn.cc
streanplay.cc##.ad
````
I can play the video at `streanplay.cc/m0ofro2l3bq5` without issue.

**Comment by aldiener58** [comment]
Thank you @okiehsch for your prompt and thoughtful response. However, I want to use streamp1ay. My choice is being hijacked to a different website that I don't know or use. I would like help developing and/or accessing the filters to prevent this from happening. I hope this makes sense. Sincerely, AD

**Comment by okiehsch** [comment]
That domain is down on my end.
![image](https://user-images.githubusercontent.com/16838044/99612050-2518e380-2a15-11eb-891b-58e620f3c00f.png)

> My choice is being hijacked to a different website that I don't know or use.

I doub that can be fixed, pretty sure both domains are owned by the same entity and the redirections are mandatory server side.

**Comment by aldiener58** [comment]
@okiehsch That is very strange @okiehsch. All day if I changed streanplay to streamp1ay on the web address line on chrome I could play the video. Now I tried it and I get the very same error as you. I am hoping that is not a permanent situation. And now I am particularly glad you gave me an alternative workaround. I will keep you posted @okiehsch and I am very grateful you took the time to respond :-)

**Comment by aldiener58** [comment]
@okiehsch I added the filters you propose on uBo and I am stuck on Proceed to Video. It does not move me forward from there. Any thoughts?

**Comment by okiehsch** [comment]
Hm, works for me after solving the captcha and clicking "proceed"
![image](https://user-images.githubusercontent.com/16838044/99612978-ff8cd980-2a16-11eb-90e0-67f40f80c81a.png)



 I go to
![image](https://user-images.githubusercontent.com/16838044/99612904-dc622a00-2a16-11eb-97cc-b50a650ca424.png)

**Comment by okiehsch** [comment]
I do have to click proceed twice.

**Comment by aldiener58** [comment]
I am not seeing the captcha. It flashes and disappears. I fear I have changed a setting to prevent it from showing on streanplay. I was able to do as you said this afternoon but I was insistent on going back to my original site which also was working with some perseverance. Any other thoughts?

**Comment by okiehsch** [comment]
> I removed one of your proposed filters and I could see the I AM NOT A ROBOT captcha flash. Not being able
to check that box is preventing me from playing the video.

Does it work if you remove all of my filters and update the uBO-filters list.
![image](https://user-images.githubusercontent.com/16838044/99613439-dc165e80-2a17-11eb-82f6-0de4ffb49a4c.png)


>  I fear I have changed a setting to prevent it from showing on streanplay.

Without knowing what you changed I can't really help.

**Comment by okiehsch** [comment]
You can restore to default settings if you don't know yourself.

**Comment by aldiener58** [comment]
@okiehsch It is now working. And I still hope my original website returns but in the meantime you have restored use for me and I am a happy camper. Thank you so much @okiehsch

**Comment by ghajini** [comment]
URL =
`https://streanplay.cc/rq06edz8o51o`

How to avoid these requests
![IMG_20201119_094329](https://user-images.githubusercontent.com/20338483/99620554-c4f16400-2a4b-11eb-8e94-ac7839a3bb6f.jpg)

It originates from 
`https://streanplay.cc/jquery-1.8.3.min.js`

**Comment by aldiener58** [comment]
I wish I understood how to make use and meaning of this chart.
If you ever care to explain, would you please let me know?

I appreciate your time and thoughtfulness.

Sincerely,
AD

**Comment by ghajini** [comment]
@aldiener58 you can have lookup at 

`https://github.com/gorhill/uBlock/wiki/The-logger`
`https://github.com/gorhill/uBlock/wiki/`

More support questions at 
`https://old.reddit.com/r/uBlockOrigin/`

**Comment by krystian3w** [comment]
File use fake name, IMO possible safe block with network filter.

**Comment by yourduskquibbles** [comment]
There is some crazy behavior still going on when visiting a `streanplay.cc` link where 
1. The console gets cleared and it looping endlessly
as well as 
2. Two hidden div boxes (maybe used to launch ads that are getting defused) that will flash between `display: block` and `display: none` when hovering over them that are being overlaid on TOP of the `recaptcha` and the `Proceed to video` buttons which is why you have to sometimes click "twice" (or a thousand times if your timing is wrong). 

Both issues seems to be fixed for me with 
```
streanplay.*##+js(aopr, console.log)
streanplay.*##div[style*="z-index: 2147483647;"][style*="position: fixed;"]
```

**Comment by yourduskquibbles** [comment]
Further testing `streanplay.*##+js(aopr, console.log)` seems to prevent the video from loading after going through the captcha and clicking `proceed to video`.

Could be because [the script](https://streanplay.cc/js/jquery.1.1.1g-min.js) the video is loading from is now aborting too early, maybe setting a constant somewhere to just ignore that section of the would work better if someone else can look over the code and suggest filter.

**Comment by mapx-** [comment]
replace by
`streanplay.*##+js(set, console.log, noopFunc)`
