### ISSUE TITLE
uBo causes rte.ie/archives player to not load & no play button

### ISSUE THREAD

**Issue by germaloney11** [uBlockOrigin/uAssets#8245]
uBo causes rte.ie/archives player to not load & no play button

### URL(s) where the issue occurs

`https://www.rte.ie/archives/2020/1112/1177759-what-future-for-dublin-dockers`

### Describe the issue

uBo causes the rte.ie/archives player to not load and there is no play button. Turning uBo off fixes this issue. 
Also occurs on `https://www.rte.ie/player/onnow` and `https://www.rte.ie/player/`

eg. `https://www.rte.ie/player/onnow/66546216066`
eg. `https://www.rte.ie/player/series/the-secrets-she-keeps/SI0000006990?epguid=AQ000269212`

### Screenshot(s)

https://i.imgur.com/gWfbgXf.png

### Versions

- Browser/version: Version 87.0.4280.66 (Official Build) (64-bit)
- uBlock Origin version: 1.30.6

### Settings

N/A
-

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled.

**Comment by mapx-** [comment]
I guess you are using annoyances lists (fanboy or adguard)

add

```
@@||cdn.cookielaw.org/consent/$script,domain=rte.ie
@@||cdn.cookielaw.org/scripttemplates/$script,domain=rte.ie
```
