### ISSUE TITLE
aternos.org - Anti-Adblock

### ISSUE THREAD

**Issue by dexeonify** [uBlockOrigin/uAssets#8246]
### URL(s) where the issue occurs
`https://aternos.org/server/`

### Describe the issue
So it seems like this issue is back again. Clicking on anything will result in an anti-adblock page. There's a 3 second cooldown upon clicking "Continue with adblocker anyway".
 

### Screenshot(s)
![image](https://user-images.githubusercontent.com/72267349/99782521-3ae0f280-2b54-11eb-8ed2-b9d7ffb8c358.png)

### Versions

- Browser/version: Chrome Version 87.0.4280.66 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.30.6

### Settings

- Default lists with AdGuard Base, Spam404 and uBlock Annoyances

### Notes
It's the exact same issue from April: `https://github.com/uBlockOrigin/uAssets/issues/7207`
It seems that they haven't given up on this yet.

**Comment by uBlock-user** [comment]
> It's the exact same issue from April: https://github.com/uBlockOrigin/uAssets/issues/7207

It's going since [2018](https://github.com/uBlockOrigin/uAssets/issues/1494)

**Comment by uBlock-user** [comment]
> It's the exact same issue from April: https://github.com/uBlockOrigin/uAssets/issues/7207

It's going on since [2018](https://github.com/uBlockOrigin/uAssets/issues/1494)

**Comment by dexeonify** [comment]
Soo is this going to get fixed anytime soon? It seems they also "spy" on here which makes this whole process even harder. Just a matter of time I guess.

**Comment by krystian3w** [comment]
If possible add new filters daily and no need `.user.js` for non-standard repair methods.

**Comment by uBlock-user** [comment]
```
aternos.org##+js(ra, style, div.body\, header.header)
aternos.org##div[id][style^="opacity: 1;"]
```

That does it except for Start button not working...

**Comment by uBlock-user** [comment]
Executing `$('#start').each(function() { this._ready = true; });` at the console makes the Start button working again.

**Comment by dexeonify** [comment]
> `+js(ra, style, div.body\, header.header)`
> `aternos.org##div[id][style^="opacity: 1;"]`

I'm supposed to put these in "My Filters" right? I did that and the site is breaking.
![image](https://user-images.githubusercontent.com/72267349/99865675-5c8aba00-2be6-11eb-9cf6-0cf5486e2c46.png)

Executing `$('#start').each(function() { this._ready = true; });` didn't do anything.

**Comment by llacb47** [comment]
@dexeonify I have a userscript that solves the issue but if it's posted publicly the aternos devs will fix it quickly. For now there is no way to fix this with vanilla uBlock Origin.

**Comment by uBlock-user** [comment]
@dexeonify 
![Capture](https://user-images.githubusercontent.com/21290713/99868801-d5d8db80-2beb-11eb-93b5-170c98218fbe.PNG)

Works for me, except for the start button, for which you need to run `$('#start').each(function() { this._ready = true; });` at the web page console.

**Comment by dexeonify** [comment]
Oops. But I did copy and pasted correctly into my filters. The fix works fine in firefox but not in chrome.
In chrome everything is squashed into this one small line:
![image](https://user-images.githubusercontent.com/72267349/99869366-6839a900-2c05-11eb-9ca0-28a1497cc6a4.png)
Whereas in Firefox everything works as expected:
![image](https://user-images.githubusercontent.com/72267349/99869386-94552a00-2c05-11eb-9a26-17ba813a9553.png)

**Comment by uBlock-user** [comment]
Race condition in Chrome or Chrome specific quirk, I tested with Chrome's UA too in Firefox and it still works.

**Comment by dexeonify** [comment]
So I tested this in Edge Chromium and it's also facing the same problem like Chrome. I guess it's something to do with Chromium?

**Comment by uBlock-user** [comment]
@dexeonify can you try the dev-build of uBO on Chrome/Edge and replace `aternos.org##+js(ra, style, div.body\, header.header)` with `aternos.org##+js(ra, style, div.body\, header.header, stay)` ?

**Comment by P0Rtvine** [comment]
@uBlock-user 
Google Chrome
uBlock Origin development build v1.32.5b10

`aternos.org##+js(ra, style, div.body\, header.header, stay)`

don't working

<details>
<summary>Gif</summary>

![1](https://user-images.githubusercontent.com/57287308/104455749-6a3e3980-55b0-11eb-997f-53943c5d107d.gif)
</details>

**Comment by uBlock-user** [comment]
@P0Rtvine did you also add `aternos.org##div[id][style^="opacity: 1;"]` ?

**Comment by P0Rtvine** [comment]
@uBlock-user 
Oops.. yep it's working

**Comment by dexeonify** [comment]
Sorry for the late reply, just noticed this in my inbox.

> can you try the dev-build of uBO on Chrome/Edge and replace `aternos.org##+js(ra, style, div.body\, header.header)` with `aternos.org##+js(ra, style, div.body\, header.header, stay)`

@uBlock-user Yep, can confirm it's working. Should I close this issue?

**Comment by krystian3w** [comment]
After publish for Chrome uBO with updated `remove-attr` with supported `stay` or `complete` varible.

**Comment by uBlock-user** [comment]
Start button still won't work, not a complete fix fyi.

**Comment by RandomModderJDK** [comment]
The easiest way would be to just block the functtion BxGmhKKZpYRYvWkWqFGKYyxkkfZhZaOzNwjjzI() in the base64 script at the end of the website. But I didn't get it working with `aternos.org##+js(acis, $, BxGmhKKZpYRYvWkWqFGKYyxkkfZhZaOzNwjjzI) `, i guess because of the base64 encoded String.

**Comment by RandomModderJDK** [comment]
The only thing you need to add is `aternos.org###headstart:style(display: flex !important)` and then you have a working start button. But idk for what this button is actually used for. But it works

**Comment by dexeonify** [comment]
As of recently, the issue seems to have returned again. It's happening on both Firefox, Chrome/Edge. None of the filters seems to work.

Firefox:
```
aternos.org##+js(ra, style, div.body\, header.header)
aternos.org##div[id][style^="opacity: 1;"]
```

Chrome/Edge:
```
aternos.org##+js(ra, style, div.body\, header.header, stay)
aternos.org##div[id][style^="opacity: 1;"]
```

**Comment by techtanic** [comment]
This still exists

**Comment by RandomModderJDK** [comment]
Right

**Comment by Liebelts** [comment]
Has anybody found a solution?

**Comment by krystian3w** [comment]
@llacb47  by `.user.js` file but after public also fastly can by outdated.

**Comment by eplayerclick** [comment]
if you do not want ads pay for servers, stop enjoyinh stuff for free and be so whiny about ads

**Comment by Cavernosa** [comment]
> if you do not want ads pay for servers, stop enjoyinh stuff for free and be so whiny about ads

And aternos is whiny about a dozen of people not giving them income. lol
