### ISSUE TITLE
FoodNetwork.com videos break until adobedtm unblocked

### ISSUE THREAD

**Issue by rodeodomino** [uBlockOrigin/uAssets#8251]
`
https://www.foodnetwork.com/recipes/ina-garten/roasted-brussels-sprouts-recipe2-1941953`

On foodnetwork.com, the videos won't play button doesn't work unless adobedtm.com is allowed.

 

### Versions

- Browser/version: Chrome 86
- uBlock Origin version: 1.30.6

### Settings

-

### Notes

By manually allowing adobedtm.com, the video plays fine.

@@||adobedtm.com$script,domain=foodnetwork.com

This may be an issue on all the Discovery sites, but I haven't tested it that far.

**Comment by llacb47** [comment]
Plays fine for me.

**Comment by mapx-** [comment]
I need

`@@||assets.adobedtm.com/extensions/*/AppMeasurement$script,domain=foodnetwork.com`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/035e166d27f0aa13b3ff71ac989d9520ea2a4916
