### ISSUE TITLE
[Anti Adblock] askquds.com

### ISSUE THREAD

**Issue by FireMasterK** [uBlockOrigin/uAssets#8252]
### URL(s) where the issue occurs

`https://askquds.com/watch/38060`

### Describe the issue

Ublock is detected twice on this page. (blockadblock and something else)
 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/20838718/99898764-13139b00-2cca-11eb-9d02-355a93f91dd2.png)
![image](https://user-images.githubusercontent.com/20838718/99898848-c41a3580-2cca-11eb-8afa-d6ec32ed65aa.png)

### Versions

- Browser/version: Brave nightly, doesn't work even with disabled shields
- uBlock Origin version: 1.30.6

### Settings

- None, just the default.

### Notes

`https://blockadblock.com/` seems to detect ublock origin too.

**Comment by okiehsch** [comment]
Try updating your filter lists, filters for that site have been added a few days ago.

**Comment by FireMasterK** [comment]
That seems to be it, thanks!
