### ISSUE TITLE
change.org

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8253]
### URL(s) where the issue occurs

`https://change.org/p/authackeray-convert-the-mumbai-zoo-into-a-wildlife-rescue-and-rehabilitation-centre-mumbaizoo?source_location=petitions_browse`

### Describe the issue

`sign this petition` not working .....
Click on **sign this petition**
Enter some random name,email and click **sign petition**
After that doesn't work anything 

### Screenshot(s)

https://user-images.githubusercontent.com/20338483/99899047-350e1d00-2ccc-11eb-9607-fa2bf90ead6d.png

https://user-images.githubusercontent.com/20338483/99899054-41927580-2ccc-11eb-8c67-8af272ba2933.jpg

### Versions

- Browser/version: firefox android nightly
- uBlock Origin version: 1.30.6

### Settings

uBO's default settings
-

**Comment by ghajini** [comment]
Its easyprivacy block filter causing this....

![IMG_20201122_155119](https://user-images.githubusercontent.com/20338483/99901257-43176a00-2cdb-11eb-869a-759f41f3090a.jpg)
![IMG_20201122_155103](https://user-images.githubusercontent.com/20338483/99901261-4d396880-2cdb-11eb-9ff9-99f0c36c0b45.jpg)

I just disabled filter via

`||change.org/nslc0hv5/$badfilter`


 and iam back to normal
![IMG_20201122_155423](https://user-images.githubusercontent.com/20338483/99901238-2418d800-2cdb-11eb-84f5-8874a8a70f4f.jpg)

**Comment by mapx-** [comment]
does this help

`@@||change.org^*/captcha`

**Comment by ghajini** [comment]
Sorry for taking time, since I already verified captcha I was not getting reverified by site 

So I used another name,email till o get their verification
This much minimum exceptions are required

```
@@||change.org^*/captcha$1p
@@||change.org/*/init.js$script,1p
@@||www.change.org/*/xhr/res/uc$xhr,domain=www.change.org
```

**Comment by mapx-** [comment]
init is perimeterx

**Comment by ryanbr** [comment]
What should replace this filter, perimeterx is a tracker.

**Comment by mapx-** [comment]
weird, I can reproduce the issue in opera but in firefox / chrome

**Comment by ghajini** [comment]
@ryanbr ,@mapx- ,would you block tracking parameters via ubo's existing solutions while leaving useful things to work. ...I will provide all logs you require if you all not reproduce

**Comment by mapx-** [comment]
even disabling uBO in opera wont make make the signing working

**Comment by ghajini** [comment]
Yes I got that as well. ....just reload the page or clear cookies/data then browse another petition, enter some fishy names,email and they will send verification email to sign petition

**Comment by mapx-** [comment]
They (`change.org`) complicated their lives adopting perimeterx system

**Comment by ghajini** [comment]
Adguard didn't blocked perimeterx 
![Screenshot_2020-11-22-19-17-50-585_org mozilla fenix](https://user-images.githubusercontent.com/20338483/99905593-c8107c80-2cf7-11eb-9440-6fdbf4a76df3.png) 
So no problem with them

**Comment by ryanbr** [comment]
I wasn't able to reproduce this either, with or without a vpn

**Comment by ghajini** [comment]
i can say this only 
`https://gifyu.com/image/iOvO`

**Comment by ghajini** [comment]
Should I close this thread?
Only perimeterx is problem here😑
Because this site is used by peoples to appeal to change something ,bring attention to govt for problems

**Comment by ghost** [comment]
Got a cookie notice on the page.

<details>
<summary>Screenshot(s)</summary>




<img width="2552" height="1290" alt="Image" src="https://github.com/user-attachments/assets/863ca344-5206-424a-9ffa-f18de3cb2c62" />



</details>

<details>
<summary>Config</summary>

```yaml
name: uBlock Origin Lite
version: 2025.804.1547
browser: Edge 139 (win)
filtering:
 site: complete
 default: complete
rulesets:
 ublock-filters
 easylist
 easyprivacy
 pgl
 ublock-badware
 urlhaus-full
 block-lan
 adguard-spyware-url
 annoyances-cookies
 annoyances-overlays
 annoyances-social
 annoyances-widgets
 annoyances-others
 deu-0
```


</details>
