### ISSUE TITLE
akwams.co anti-adb

### ISSUE THREAD

**Issue by Iaycomand** [uBlockOrigin/uAssets#8258]
`https://akwams.co/search?q=jujutsu+kaisen`

### Describe the issue

showing targeted message powered by blockadblock.com especially when using search function.
### Screenshot(s)

![image](https://user-images.githubusercontent.com/39984795/99911531-cfd31f80-2cfd-11eb-9574-8e84587875de.png)

### Versions

- Browser/version: Chrome Version 86.0.4240.198 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.30.6

**Comment by uBlock-user** [comment]
post url where it occurs, dont skip the template like this.

**Comment by Iaycomand** [comment]
> post url where it occurs, dont skip the template like this.

Forgot to remove the comment.

**Comment by uBlock-user** [comment]
Test these filters --

```
@@||akwams.*^$ghide
akwams.*##.adsbygoogle
akwams.*##.ads
```

**Comment by Iaycomand** [comment]
> Test these filters --
> 
> ```
> @@||akwams.*^$ghide
> akwams.*##.adsbygoogle
> akwams.*##.ads
> ```

Filters worked fine
