### ISSUE TITLE
kissasian.ch blocking uBlock again

### ISSUE THREAD

**Issue by MarsWanKenobi** [uBlockOrigin/uAssets#826]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`www.kissasian.ch/Drama/*`

### Describe the issue

Trying to watch any drama results in video not loading and "disable adblocker" to proceed.

### Screenshot(s)

https://screenshots.firefox.com/TQ0Jn4qXp5ecbHVf/kissasian.ch

### Versions

- Browser/version: Firefox Nightly 58.0a1 (2017-11-10)
- uBlock Origin version: 1.14.18

### Settings

- Enabled that filter list which blocks coinhive & similar.

### Notes

Disabling Privacy Badger and even Safe Mode. Works without uBlock enabled obviously.  Gorhill previously added an exception in one of the filters and it worked for a while but I noticed just today it stopped.

**Comment by gorhill** [comment]
I can't reproduce with default lists/settings. I tested this URL: <http://kissasian.ch/Drama/14-Blades/Movie?id=6234>. (Please provide an exact URL next time to eliminate _all_ instances of guesswork).

**Comment by gorhill** [comment]
Maybe you had Tracking Protection enabled?
