### ISSUE TITLE
uBlock Origin blocking styles & scripts from *.piwik.pro subdomains

### ISSUE THREAD

**Issue by Marcin-PiwkPRO** [uBlockOrigin/uAssets#8260]
### URL(s) where the issue occurs

All assets from *.piwik.pro subdomains

### Describe the issue

uBlock Origin blocks scripts, styles and pictures on websites requesting them from *.piwik.pro subdomains making it inoperable for the users.

### Screenshot(s)

![clearcode cc](https://user-images.githubusercontent.com/67640881/99953963-56c9db80-2d82-11eb-94b2-f835bd845217.png)
![bmctoday com](https://user-images.githubusercontent.com/67640881/99953979-5af5f900-2d82-11eb-8a36-c9b2af854564.png)
![ahk de](https://user-images.githubusercontent.com/67640881/99953983-5df0e980-2d82-11eb-9577-e54153f0cbe3.png)

### Versions

- Browser/version: all browsers
- uBlock Origin version: current version

### Settings

uBlock Origin on default settings.
-

### Notes

We suggest changing default filter settings to not block *.piwik.pro subdomains.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/c3a6ed2

**Comment by uBlock-user** [comment]
@Marcin-PiwkPRO specific url ?

**Comment by Marcin-PiwkPRO** [comment]
Example domains: clearcode.cc 
Please remember that all  *.piwik.pro subdomains are being blocked. Not only the specific ones. 
Please exclude all  *.piwik.pro subdomains.

**Comment by mapx-** [comment]
already fixed in easyprivacy list (see above the commit), just update all your lists and test again

**Comment by mapx-** [comment]
mmhmm, @ryanbr `clearcode.cc` too ?

**Comment by ryanbr** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7613

From here, why suddenly drawing on assets from a knowingly blocked item @Marcin-PiwkPRO ?   Not a recent filter either https://github.com/easylist/easylist/commit/7679662180fb5c056b70080349a5057531ccb61a

**Comment by Marcin-PiwkPRO** [comment]
@ryanbr 
We’re using .piwik.pro subdomain to load assets. It is used both by our website (assets.piwik.pro) as well as our product ([clientname].piwik.pro).  To answer your questions:

- we cannot and should not use a different domain for assets, because it will be regarded as a third-party domain when visiting piwik.pro website.

- clients use a dedicated subdomain in .piwik.pro - blocking it, not only prevents them from logging in to the UI, but also using the product in any way

**Comment by krystian3w** [comment]
CC also whitelisted: https://github.com/easylist/easylist/commit/4e45994207878872400c271d705c17219c1cb19d

**Comment by Marcin-PiwkPRO** [comment]
@krystian3w 

- Both companies used a shared CDN in the past, and since then, that has been corrected. Each (piwik.pro, clearcode) use their own subdomain for assets.

- But this is only part of the impact, additionally the filter blocks actual login screens & UI of the products used by clients in [clientname].piwik.pro domains.

**Comment by krystian3w** [comment]
Well, I only see an option to convert to regex or 4 simple network filters:

`/^https?\:\/\/(www\.)piwik\.pro/$script,image,xmlhttprequest,subdocument`


```
|http://piwik.pro^
|http://www.piwik.pro^
|https//piwik.pro^
|https://www.piwik.pro^
```

when remove filter generate lack of privacy.

**Comment by uBlock-user** [comment]
`clearcode.cc` has been exempted in EP, so closing.

**Comment by Marcin-PiwkPRO** [comment]
@krystian3w 
- Our main problem is that our product can't be used when uBlock Origin is active. This feature request was about piwik.pro domain & *.piwik.pro subdomains, clearcode.cc website was only an example.

- The suggested regexps by krystian3w will work partially,  could you consider allowing script,image for subdomains as well? (so that we can load e.g. images for blog posts from assets.piwik.pro as well as  the assets for [clientname].piwik.pro loads correctly?)

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by mapx-** [comment]
@Marcin-PiwkPRO you should tell us what really is needed to unbreak the functionalities on your side (obviously not including stuff regarding the privacy like ppms.js script for example => otherwise nobody would unlock your stuff anymore) .

**Comment by krystian3w** [comment]
Maybe he needed add exception into:

https://github.com/easylist/easylist/blob/6216cbb7cdd1ba8d89f030cb6c78479abd61aca4/easyprivacy/easyprivacy_general.txt#L5149

but maybe faster is no use as `clearcode.cc` as "CDN" for polish domain?

```
clearcode.pl
|
| --- piwik.pro.clearcode.cc
```

**Comment by Marcin-PiwkPRO** [comment]
@mapx- @krystian3w 
We’d like you to whitelist the subdomains of *.piwik.pro, specifically to allow loading JS, CSS & image assets to unbreak UI of the product. We have complaints about these filters - it’s about using the product, not tracking users.

There are several other rules that block the tracking (see the rules on the attached image below) which completely block collecting any data by our product about users who installed the list.
![fail tracker](https://user-images.githubusercontent.com/67640881/100100793-a59a7280-2e61-11eb-811f-1969f9b2574a.png)

**Comment by Marcin-PiwkPRO** [comment]
@mapx- @ryanbr @krystian3w so what do you think? can it be done?

**Comment by mapx-** [comment]
Can you confirm 100% if easyprivacy removes the general filter `||piwik.pro^$third-party`
and add:
`||piwik.pro/ppms`

**all the tracking will still be blocked** ?

This **have to be available for the future too**, otherwise I guess the general block will return very fast

**Comment by Marcin-PiwkPRO** [comment]
Yes, I can confirm that and we are aware of the consequences. Big thanks for this! <3

**Comment by mapx-** [comment]
Let's see if @ryanbr is ok with this proposal

**Comment by ryanbr** [comment]
`||piwik.pro/ppms` won't cover many domains.  From what I see `piwik.pro` (still) is sharing resources on its own sites and then using the same domain to serve up tracking. If `piwik.pro` can't separate this, it should remain blocked.

**Samples:** 

`https://www.bang-olufsen.com/en`
`https://bang-olufsen.containers.piwik.pro/ad2e80e2-6747-4919-8ab0-7135801dab21.js`


`https://www.waca.associates/en/`
`https://waca.containers.piwik.pro/0d480677-be5b-4887-90b1-c9f2fd013614.sync.js`
`https://waca.containers.piwik.pro/0d480677-be5b-4887-90b1-c9f2fd013614.js`

`https://www.academiccourses.com/`
`https://keystone.containers.piwik.pro/a1fa26b2-9906-42a3-bd3c-9bc3c73be271.js?data_layer_name=piwikDataLayer`


`https://boell.org/`
`https://boell.piwik.pro/piwik.js`

`https://www.zim.com/`
`https://zta.containers.piwik.pro/923228e7-d119-45eb-a025-e4d1b1af6e1b.js`


`https://www.artscyclery.com/`
`https://smartetailing.piwik.pro/ppms.js`

**Comment by Marcin-PiwkPRO** [comment]
Thanks for your feedback. The files loaded from containers and ppms.js (or older version piwik.js) are not going to track user, because the tracking requests invoked by them are going to be blocked by rule suggested by @mapx-  above:

`||piwik.pro/ppms`

You may consider why loading them in the first place, if they are invoking the tracking request, but the containers load also content (e.g. we provide functionality to serve dynamic content on the sites) as well as scripts that are configured by the customer (but these will be blocked according to other rules, e.g. when Google Analytics is added it will not be loaded due to other rules). 

 We suggest that you could extend the rule to block ppms.js/piwik.js in the following way:

```
||piwik.pro/ppms
||piwik.pro/piwik
```

But not block the containers & assets this way.

**Comment by Marcin-PiwkPRO** [comment]
@mapx- @ryanbr @krystian3w what do you think?

**Comment by Marcin-PiwkPRO** [comment]
And now there's another thing. 
Since filters in uBlock Origin have been updated to the newest version, we see all our assets on piwik.pro website are blocked again (they were unblocked in this ticket:[ #7613](https://github.com/uBlockOrigin/uAssets/issues/7613)).

![image (13)](https://user-images.githubusercontent.com/67640881/100660562-806e9e00-3352-11eb-80c4-6a8c57b1e437.png)

**Comment by uBlock-user** [comment]
@Marcin-PiwkPRO force update all default lists by purging all caches.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/bdec5660d6912db9eec5a9121cdeaa53e8741d94

**Comment by Marcin-PiwkPRO** [comment]
@ryanbr so what do you think about proposition from here?
https://github.com/uBlockOrigin/uAssets/issues/8260#issuecomment-734823797

**Comment by ryanbr** [comment]
I'm happy to leave this. We've fixed what we needed too.
