### ISSUE TITLE
vidsaver.net

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8262]
### URL(s) where the issue occurs

`https://vidsaver.net/private-video-downloader`

### Describe the issue
popup ads

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.31.1b2

### Settings

 uBO's default settings
-

### Notes
1.
This works for me on first visit of site

`vidsaver.net##+js(acis, String.fromCharCode, btoa)`
2.
doing subsequent reloads (or say 1 reload) of the page filter `vidsaver.net##+js(acis, String.fromCharCode, btoa)`
doesn't act

**Comment by mapx-** [comment]
working fine even after reload in opera on my side

**Comment by ghajini** [comment]
i tried firefox desktop also ,there also same happening

**Comment by mapx-** [comment]
same, FF ok

**Comment by bogachenko** [comment]
@ghajini What sites are being opened? I was able to reproduce 2 different ad windows.

1. `agacelebir.com`
2. `boaphaps.net`

**Comment by ghajini** [comment]
@bogachenko this one `boaphaps.net`

@mapx- would you do reloads of the page may be 10 times 
![Screenshot (10)](https://user-images.githubusercontent.com/20338483/99977177-51907f00-2dca-11eb-94ac-829237b8b992.png)
![Screenshot (11)](https://user-images.githubusercontent.com/20338483/99977188-535a4280-2dca-11eb-8e11-7828febd796f.png)

**Comment by mapx-** [comment]
nothing .. perhaps you get some race condition, what about `(aopr, btoa)` ?

**Comment by ghajini** [comment]
that straightway not work

**Comment by gwarser** [comment]
@ghajini can you try:

	||azoaltou.com/apu.php?zoneid*$xhr,domain=vidsaver.net,empty
	||azoaltou.com/tag.min.js$script,domain=vidsaver.net,empty

**Comment by ghajini** [comment]
@gwarser 
Popups after reloads of the page when clicked in page
This filter not work when reload page few times
`vidsaver.net##+js(acis, String.fromCharCode, btoa)`
https://user-images.githubusercontent.com/20338483/100041330-1f653880-2e2f-11eb-9ca4-31210edcf28d.jpg

**Comment by okiehsch** [comment]
@gwarser does 
`vidsaver.net##+js(aeld, /^(?:click|mousedown)$/, break;case)`
prevent the popups`without breaking anything on your end?

**Comment by okiehsch** [comment]
Does it break anything, meaning can you still download?
I can reproduce the race condition sometimes and that filter works for me using Chromium.

**Comment by mapx-** [comment]
try

`||vidsaver.net^$csp=sandbox allow-forms allow-same-origin allow-scripts allow-modals allow-orientation-lock allow-pointer-lock allow-presentation allow-top-navigation`

**Comment by ghajini** [comment]
@okiehsch certainly no breakage with your filter ,i can download
@mapx- with your filter i see those requests still but this time no popups now

as a side note i tried vidsaver.net##+js(noeval)
i got this in console
```
Document tried to eval... (function () {
    var PROXY_NAMES = {
        u: 'UNKNOWN',
        j: 'PROXY_JS',
        c: 'PROXY_CSS',
        p: 'PROXY_PNG',
        x: 'PROXY_XHR',
        s: 'DELIVERY_JS',
        f: 'PROXY_IFRAME',
    };

    var generateRandomPHPUrl = () => {
        var uri = Math.random().toString(36).slice(2);
        return ['https://boaphaps.net/', uri, '.php'].join('');
    };

    var getDomainFromUrl = (url) => {
        try {
            return new URL(url).hostname;
        } catch(e) {
            return '';
        }
    };

    var sendData = (data, type) => {
        try {
            var iframe = [].find.call(document.getElementsByTagName('iframe'), i => i.src === 'about:blank');
            var request = (iframe && new iframe.contentWindow.XMLHttpRequest()) || new XMLHttpRequest();
            var trackLink = generateRandomPHPUrl();
            request.open('POST', trackLink, true);
            request.setRequestHeader('X-Log-Type', type);
            request.setRequestHeader('Content-Type', 'application/json');
            request.send(JSON.stringify(data));
        } catch (e) {}
    };
    var zoneid = 3409262;
    var format = 'onclick';

    var aab = window.zfgformats.filter((f) => f.zoneId === zoneid && f.sourceZoneId).shift();
    if (!aab) {
        return;
    }

    var type = 'request';
    var { referrer } = document;
    var currentUrl = window.location.href;
    var successMethodKey = ['t4kd70d8cge', aab.zoneId.toString(36)].join('');
    var storageMethod = localStorage[successMethodKey] || 'u';
    var successMethodName = PROXY_NAMES[storageMethod];
    var info = {
        format,
        referrer,
        zone_id: zoneid,
        current_url: currentUrl,
        aab_version: aab.version,
        method: successMethodName,
        user_agent: navigator.userAgent,
        referrer_domain: getDomainFromUrl(referrer),
        current_url_domain: getDomainFromUrl(currentUrl),
    };

    sendData(info, type);
})()
```

**Comment by okiehsch** [comment]
>  with your filter i see those requests still but this time no popups now

The requests will be there with my filter too. That can't be helped if a race condition occurs.
**mapx-** works for me too, so adding that and blocking `boaphaps.net` is as good as it gets probably.

**Comment by ghajini** [comment]
Yes my bad, I got race condition on 3 different browsers firefox A., firefox desktop,  opera browser

**Comment by uBlock-user** [comment]
`boaphaps.net` has been blocked with https://github.com/uBlockOrigin/uAssets/commit/25d49bedf8dd2eb2cb8cdb4ef5afbcdce93a9822 @okiehsch

**Comment by okiehsch** [comment]
Thanks, I missed that, so only **mapx-** is needed. I will add it.
