### ISSUE TITLE
musicradar.com

### ISSUE THREAD

**Issue by Kyuzial** [uBlockOrigin/uAssets#8263]
### URL(s) where the issue occurs
`
https://www.musicradar.com`

### Describe the issue

Redirect to `https://www.musicradar.com/cc.html` when using an adblocker

### Versions

- Browser/version: [84.0b4]
- uBlock Origin version: [1.31.1.2]

### Settings
 - Medium mode

### Notes

Here's how adguard fixed this https://github.com/AdguardTeam/AdguardFilters/commit/92247f5aa484640b191598a3d4782ae6ce3d68fd

**Comment by uBlock-user** [comment]
Test on default settings, you're likely blocking 3rd-party CDN scripts which is what triggers this anti-adblock
