### ISSUE TITLE
"No AdBlock" issue with Magesy.blog website

### ISSUE THREAD

**Issue by FinleyGomez** [uBlockOrigin/uAssets#8266]
### URL(s) where the issue occurs

`https://magesy.blog/`

### Describe the issue

A "No AdBlock" popup appears and disables the use of scrolling on the website, and it can't be removed. I have tried blocking the element myself using the Element Picker mode, however, while it does remove the popup, I am unable to scroll on the website

### Screenshot(s)

Screenshot 2020-11-24 at 14 29 35](https://user-images.githubusercontent.com/25120572/100108012-3a9d6b80-2e62-11eb-9146-7fe5b15c70bd.png)

### Versions

- Browser/version: Firefox/83.0 (64-bit)
- uBlock Origin version: 1.31.0

### Settings

*$image,redirect-rule=2x2.png,domain=magesy.blog|magesy.eu|majesy.com,badfilter
*$image,redirect-rule=1x1.gif,domain=majesy.org|magesy.pw|magesy.fr,badfilter
magesy.*#@#+js(abort-on-stack-trace, Math.floor, onload)
majesy.*#@#+js(abort-on-stack-trace, Math.floor, onload)
magesy.*,majesy.*##+js(aost, onload, inlineScript, 2)

### Notes

After trying various different techniques, I was unsuccessful in fixing it myself. Some help on how to fix the issue for this site would be massively grateful. Thanks in advance

**Comment by mapx-** [comment]
- use only the default lists, all updated
- remove other personal filters for that page

**Comment by ishikawamaako** [comment]
+1 for that site..
