### ISSUE TITLE
Twitter tweet react popup

### ISSUE THREAD

**Issue by leodoi3** [uBlockOrigin/uAssets#8272]
Is there any way to get rid of this popup when reacting to a tweet?

### URL(s) where the issue occurs

Example tweet here:
https://twitter.com/charliekirk11/status/1329481338450112512

### Describe the issue
There is a popup when reacting to tweets with warning labels.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/46114199/100183512-5de50c80-2e9c-11eb-936f-d432f4707d6b.png)

### Versions
- uBlock Origin version: 1.31.0

**Comment by uBlock-user** [comment]
With `twitter.com##.r-1knelpx.r-1j3t67a.r-19yat4t.r-jgcjvd.r-z2wwpe.r-1uaug3w.r-1awozwy.css-1dbjc4n` won't be added in uAssets though. You can use it for yourself.

**Comment by krystian3w** [comment]
Or this when no generate race-condition with position pop-up:

`##a[href="/i/events/1308626736066617344"]:upward(1)`
