### ISSUE TITLE
Songs are skiping/stopping in Spotify web player

### ISSUE THREAD

**Issue by grande-mephistopheles** [uBlockOrigin/uAssets#8279]
### URL(s) where the issue occurs
`https://open.spotify.com`

### Describe the issue
Songs are skipping after starting and playing for 2-3 seconds. Sometimes they also stop altogether. Can't listen to music. I'm using the web player.
 

### Screenshot(s)
N/A

### Versions
- OS: Linux Mint 20
- Browser/version: Mozilla Firefox 83.0 64-bit
- uBlock Origin version: 1.31.0

### Settings

- Default filter lists
- WebRTC and CSP reports blocked
- Spotify specific dynamic rules:
     - spotify.com scdn.co * noop
     - spotify.com google.com * noop
     - spotify.com gstatic.com * noop
     - spotify.com spotify.map.fastly.net * noop

### Notes
- I don't keep cache/cookies, using Temporary Containers addon. Hardened Firefox. 3rd-party scripts and frames blocked.

**Comment by grande-mephistopheles** [comment]
Note: This happens sometimes, sometimes not. I'm guessing it triggers when advertisement video from Spotify is blocked

**Comment by okiehsch** [comment]
Ok, now I could reproduce, but the songs skip on my end even if I dusable uBO.

**Comment by okiehsch** [comment]
>  I'm guessing it triggers when advertisement video from Spotify is blocked

That was my first thought too, but it skips songs that don't have pre-rolls, so I don't know.
I can't consistently reproduce.

**Comment by okiehsch** [comment]
You can try adding
`@@||akamaized.net/audio/*$media,domain=open.spotify.com`
and test if that solves the skipping issue on your end.
Note that you will hear pre-rolls after adding that filter, it is meant to pinpoint the issue,

**Comment by grande-mephistopheles** [comment]
Right now I'm listening fine and no interference even though the number of blocked ads crossed 1k+ and rising (closing 2k). So I'm not sure what are you suggesting.

**Comment by okiehsch** [comment]
Well, if it works for you right now, no need to add my suggested filter.
I don't know what else to tell you, best to wait and see if other users can consistently reproduce.
I can't and I am not sure what triggers the occasional skipping.
