### ISSUE TITLE
hltv.org

### ISSUE THREAD

**Issue by kasper93** [uBlockOrigin/uAssets#828]
### URL(s) where the issue occurs

`https://www.hltv.org/`
`https://www.hltv.org/ranking/teams`
`https://www.hltv.org/events/2574/dreamhack-open-winter-2017`

### Describe the issue

`https://www.hltv.org/ranking/teams`
Gif at the top. This one should replace `.png` filter that we already have in uBO filters.
```
||hltv.org/img/static/egbranking$image
```

----------------

`https://www.hltv.org/events/2574/dreamhack-open-winter-2017`
Fantasy games ad.  I have two suggestions
```
hltv.org##.gtSmartphone-only:if(>div.section-header:first-child:has-text(Fantasy games))
```
or
```
hltv.org##.event-fantasy
hltv.org##.gtSmartphone-only > .section-header:has-text(Fantasy games)
```
---------------

`https://www.hltv.org/`
Left ads placeholders, they break page layout especially on lower res devices. 
```
hltv.org##[class^="col-rek"][id]
```

---- 

Hope I didn't miss anything :>

**Comment by okiehsch** [comment]
Thx.
