### ISSUE TITLE
lookmovie.ag adblock detection

### ISSUE THREAD

**Issue by SamVicious** [uBlockOrigin/uAssets#8282]
### URL(s) where the issue occurs

 `https://lookmovie.ag/shows/view/11165358-adventure-time-distant-lands-2020#S1-E1-98410
`
### Describe the issue

The website works all fine but displays an adblock detection overlay whenever trying to play the videos.

### Screenshot(s)

https://imgur.com/a/aLVMqzy

### Versions

- Browser/version: [Microsoft Edge Version 87.0.664.47 (Official build) (64-bit)]
- uBlock Origin version: [1.30.6]

### Settings

Default

**Comment by mapx-** [comment]
Did you test keeping only uBO enabled ? (no other extension)

**Comment by garry-ut99** [comment]
Breakage - thumbnails not loading: [screenshoot](https://user-images.githubusercontent.com/72945564/220690740-4e3dff1f-249a-478f-b1fb-81bfacb12afc.png), this when fixed: [screenshoot](https://user-images.githubusercontent.com/72945564/220690911-11dfff27-cb2d-42d1-8fc9-dce08a3ba473.png)
