### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [uBlockOrigin/uAssets#8288]
hi , i have question how can translate this
$$script[tag-content="Please disable AdBlock"] 

work with adguard but not work with ublock idk how translate rule for ublock origin ty

**Comment by uBlock-user** [comment]
For support/questions/help, there is [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/) on Reddit.

**Comment by mapx-** [comment]
You should at least provide the page you need to fix
