### ISSUE TITLE
www1.swatchseries.to

### ISSUE THREAD

**Issue by aldiener58** [uBlockOrigin/uAssets#8289]
[I am still very new to this site and I have tried to honor all posting rules]

I am having issues with the above referenced website:

It appears everything associated with ###h??ps://www1.swatchseries.to/ is
being redirected to ###h??ps://www1.watch-series.la/ (?s subbed for t to prevent active link)

As a result none of the links are working. Can someone please help?

Thank you,
AD

Google Chrome Version 87.0.4280.67 (Official Build) (x86_64)
uBlock Origin v1.30.6 (caches cleared, filters updated)

**Comment by mapx-** [comment]
it seems to be the new site, then choosing a movie / server I get an empty thing, no play button (even disabling uBO on page)

**Comment by mapx-** [comment]
@aldiener58 try this site, it seems to be the real one:
`https://wwvv.watchseries.ovh/`

**Comment by ghajini** [comment]
Everything works perfectly
I get redirected from `swatchseries.to`
to
`https://www1.watch-series.la/`

![Screenshot_2020-11-29-19-36-36-625_org mozilla fenix](https://user-images.githubusercontent.com/20338483/100544259-74afa880-327a-11eb-98ec-7413a9509317.png)

Not a ubo issue

**Comment by mapx-** [comment]
@ghajini do you get a play button ?

**Comment by ghajini** [comment]
Yes I get
eg
`https://www1.watch-series.la/episode/the_walking_dead_world_beyond_s1_e9.html`

![IMG_20201129_200251](https://user-images.githubusercontent.com/20338483/100544775-171d5b00-327e-11eb-8e6e-f4b971fead1b.jpg)

**Comment by mapx-** [comment]
not here but after you land on the next page

**Comment by aldiener58** [comment]
@mapx Thank you so much for exploring this issue. I have only tested the
new site a bit but so far so good :-)

@ghajini holy smokes... the functionality for h??ps://www1.watch-series.la/1
was implemented as I was typing the same response as @mapx.
I will save both websites for future reference.

Thank you both :-)

**Comment by ghajini** [comment]
Yes every video server works correctly

**Comment by aldiener58** [comment]
@ghajini and @mapx This issue is not completely resolved.

For example:
I choose the link h??ps://
www1.watch-series.la/episode/black_hands_s1_e5.html
and get sent to the broken site h??ps://
www1.watch-series.la/freecale.html?r=fepyJojdCI6InpZOVFyWeGMrZDltYlfNNeFJYVkdrXako3NUVBVUF2NlwvbUxFTlB1dWY3dEs5RjBFUmp5cVRVK1hOWlFQSkc3STczIiwiaXYiOiIyZjk2NjA5Zjk1NGNlMWJlZDNhZmY0MjU5OWM3YjQ2NiIsInMiOiI2OTBiMjcwYTllYWY4MjU2In0=

which displays no play button

The plain difference between the two sites is as follows:
-The working site says "PLEASE DISABLE ADBLOCK IF YOU HAVE ISSUES WITH THE
FEATURES ON THE SITE."
and the nonworking site says "swatchseries.to is our new domain. Please
update your bookmarks!!!"

Somehow I am getting bounced between the two sites. I have delete caches,
cookies, updated filters, etc.

Can we reopen this topic? Any thoughts?

Thank you,
AD

**Comment by aldiener58** [comment]
Can we please re-open this issue? There seems to be something working intermittently. I tried to send a post but it was rejected due to the issue being closed.

**Comment by mapx-** [comment]
@aldiener58 did you test 

`https://wwvv.watchseries.ovh/`

**Comment by aldiener58** [comment]
oops doing so now...

**Comment by aldiener58** [comment]
@mapx- @ghajini
The search feature does not work on h??ps://wwvv.watchseries.ovh/
and does work on h??ps://www1.watch-series.la/

However so far the links on h??ps://wwvv.watchseries.ovh/ do appear to be
working.

Please let me know if search issue is something that can be addressed on
github.
Again thank you for your patience.

Thank you,
AD

**Comment by mapx-** [comment]
The search is working fine on my side - tested chrome / firefox

**Comment by aldiener58** [comment]
@mapx-
from Google Chrome Version 87.0.4280.67 (Official Build) (x86_64)

I start on h??ps://wwvv.watchseries.ovh/

I search for The Walking Dead

In response I am taken to the following page
h??ps://wwvv.watchseries.ovh/search/the%20walking%20dead

I believe it is working for you and if you have any further suggestions
please let me know.

Thank you,
AD

**Comment by mapx-** [comment]
Put `The Walking Dead` in the search box, wait 1-2 seconds, a list will be shown just choose what you want (I guess `The Walking Dead (2010)`) click etc

**Comment by aldiener58** [comment]
@mapx-
Now how in the world did you figure that out? I of course assumed hitting
search would work :-)

Thank you as always for your time and support.

**Comment by mapx-** [comment]
An intelligent search feature is always done this way (predictive / autocomplete)

**Comment by ghajini** [comment]
These are typical site errors I get http error 428 when use search function
Screenshot=

https://user-images.githubusercontent.com/20338483/100547929-82bbf400-328f-11eb-876f-8f4de8034ec8.jpg



@aldiener58 
If you continue to see this problem
1. Be sure to use only ublock origin, using other similar purpose blocker gives trouble
2.reset to default ublock origin settings
Or just reinstall ublock origin(`https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm` or
`https://addons.mozilla.org/addon/ublock-origin/`

**Comment by aldiener58** [comment]
@mapx-
an intelligent search feature either requires instructions or an
intelligent user :-)

@mapx- and @ghajini I am very grateful for the support you provide.

**Comment by ghajini** [comment]
fake buttons
`www1.watch-series.la##.freeEpisode`

**Comment by aldiener58** [comment]
@ghajini I wish I understood what your message means...

**Comment by gwarser** [comment]
He is reporting another issue.

**Comment by uBlock-user** [comment]
The website has the same layout as `swatchseries`, so same filters will be required to fix all the crap that was fixed for `swatchseries`.

**Comment by aldiener58** [comment]
@gwarser thank you for the translation :-)
