### ISSUE TITLE
UBlock Origin is blocking the comentaries in Youtube videos on Google Chrome

### ISSUE THREAD

**Issue by er5manu** [uBlockOrigin/uAssets#8291]
### URL(s) where the issue occurs

https://www.youtube.com/watch?v=LLSdy1vqBQU

### Describe the issue

The comentaries get filtered and the 3 points button for reporting and etc is not showed with the default filters

### Screenshot(s)

https://ibb.co/Yc0YjMp with the default filters and https://ibb.co/qJZVLtC with filters off

### Versions

- Browser/version: [Google Chrome Versión 87.0.4280.66 (Build oficial) (64 bits)]
- uBlock Origin version: [1.31.0]

### Settings

It's default i think

### Notes

I don't know what investigation work i'm supposed to do

**Comment by uBlock-user** [comment]
Purge caches and force update filterlists.

**Comment by gwarser** [comment]
Check you custom filters in My filters for YT entries.

**Comment by er5manu** [comment]
> Check you custom filters in My filters for YT entries.

I don't see "my filters" anywhere

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/100547176-8f2b5700-3265-11eb-86cc-cbcb9d97d650.png)

**Comment by er5manu** [comment]
alright, i see the youtube filters but how do i know what do they mean? what element reffer each filter?

**Comment by mapx-** [comment]
remove or comment (using `!` ) all the filters for YT in your `my filters` tab, then test again

**Comment by er5manu** [comment]
> remove or comment (using `!` ) all the filters for YT in your `my filters` tab, then test again
where do i comment that

**Comment by gwarser** [comment]
Put `!` before the filter:

    ! example.com##filter

Or you can copy them if you care about and just remove.

**Comment by er5manu** [comment]
> Put `!` before the filter:
> 
> ```
> ! example.com##filter
> ```
> 
> Or you can copy them if you care about and just remove.

oh, the ! thing works thanks. It's what i was looking for

**Comment by uBlock-user** [comment]
>  the ! thing works thanks. 

So the issue is fixed ?

**Comment by krystian3w** [comment]
Nope, we need found safe filter to kill "sign into youtube".
