### ISSUE TITLE
Website goes blank when clicking any link

### ISSUE THREAD

**Issue by iamtherik** [uBlockOrigin/uAssets#8293]
URL(s) where the issue occurs

`www.aristeguinoticias.com`

Describe the issue

Page loads fine, but whenever you click something the page goes blank, only way to open an article is to open it on a new tab. some elements can't be right click it to open in a new tab.
Screenshot(s)

![image](https://user-images.githubusercontent.com/69179397/100551680-d99ddb00-3247-11eb-9c18-988bc5652232.png)

Versions

    Browser/version: Firefox 83.0 (64-bit)
    uBlock Origin version: 1.31

Settings
default
Notes
previous fix#7728
! https://github.com/uBlockOrigin/uAssets/issues/7728
@@||doubleclick.net/gpt/pubads_impl$script,domain=aristeguinoticias.com
@@||doubleclick.net/tag/js/gpt.js$script,domain=aristeguinoticias.com
is no longer working

Website works well if i disable the adblock haven't found exact element to whitelist hoping to find any ideas.

**Comment by PIZZA90** [comment]
i can reproduce sometimes without this list:

**spa, por: AdGuard Spanish/Portuguese 
spa: EasyList Spanish**

so.. is fixed in that lists i think

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled.

**Comment by krystian3w** [comment]
try these:
```
aristeguinoticias.com##html:root[lang="es"]:lang(es) > head + body:style(display: block !important;)
```

**Comment by iamtherik** [comment]
> 
> 
> Test on default settings + all other extensions disabled.

Tested on a New windows install, new Firefox install, only ublock added to Firefox.

**Comment by krystian3w** [comment]
Try Disable these:

- [ ] spa, por: AdGuard Spanish/Portuguese
- [ ] spa: EasyList Spanish

**Comment by PIZZA90** [comment]
I have all the filters updated. and i can confirm it. 

disabling:

 **spa, por: AdGuard Spanish/Portuguese
 spa: EasyList Spanish**

that issue appears, maybe in any of that list or both, i dont know 🤔

**Comment by iamtherik** [comment]
My Firefox is in English and so it is Windows. filter lists for SPA have never been enabled.
![image](https://user-images.githubusercontent.com/69179397/100642489-73c05a80-32fe-11eb-9e94-a5fa6b894923.png)

**Comment by krystian3w** [comment]
I no use `Spanish/Portuguese` "suplement" and page is visible.

If you can try use this in `My Filters` (Mis filtros): https://github.com/uBlockOrigin/uAssets/issues/8293#issuecomment-735605485

**Comment by iamtherik** [comment]
> 
> 
> I no use `Spanish/Portuguese` "suplement" and page is visible.
> 
> If you can try use this in `My Filters` 🇺🇸 🇬🇧 (Mis filtros 🇪🇸 🇲🇽 ): [#8293 (comment)](https://github.com/uBlockOrigin/uAssets/issues/8293#issuecomment-735605485)

I already  used your filter Krystian and it didn't work, Page is Visible.
What the underlying issue is when you click any article the website goes blank.

**Comment by PIZZA90** [comment]
using **Chrome** and this filter:

```
! sepcificity: 0-3-3
aristeguinoticias.com##html:root[lang="es"]:lang(es) > head + body:style(display: block !important;)
```

not working, that issue continue with regional list **OFF**

**Comment by krystian3w** [comment]
For my is loaded after ~1 s.

**Comment by PIZZA90** [comment]
when this issue appear:

![Captura](https://user-images.githubusercontent.com/33556647/100644352-8016d880-333b-11eb-8325-738e5ce6b27a.PNG)

when all ok, and not appear:

![Captura2](https://user-images.githubusercontent.com/33556647/100644378-8a38d700-333b-11eb-8912-f44ab60efc3e.PNG)

**Comment by mapx-** [comment]
@iamtherik add both spanish lists and test again

**Comment by iamtherik** [comment]
> 
> 
> @iamtherik add both spanish lists and test again

I added both lists and issue persist. 
![image](https://user-images.githubusercontent.com/69179397/100645079-1941f100-3334-11eb-8706-d0b3a955b994.png)

**Comment by mapx-** [comment]
I get no blanl page with / without spanish lists

for example on the main page I click "Robo di licores", no breakage

![image](https://user-images.githubusercontent.com/10303732/100645786-77270680-333d-11eb-842f-0ffc9cd8b883.png)

**Comment by uBlock-user** [comment]
need Spanish locale IP to repro ?

**Comment by mapx-** [comment]
tested using Barcelona ip, no dice

**Comment by iamtherik** [comment]
I used my work vpn based in the u.s. and no breakage.

**Comment by krystian3w** [comment]
So geo-specific.

**Comment by uBlock-user** [comment]
Tested with Mexican VPN, no issues there.
