### ISSUE TITLE
yts.mx popup

### ISSUE THREAD

**Issue by kookook820** [uBlockOrigin/uAssets#8295]
this ad always popup in yts.mx site. very annoying

`https://ohrdsplu.com/jump/next.php?r=1221179&padbl=1`

**Comment by grande-mephistopheles** [comment]
@kookook820 `ohrdsplu.com` is already blocked in the EasyList. Cannot reproduce on my end. Please test again with default uBO settings

**Comment by ghajini** [comment]
propeller crap
`https://yts.movie/torrent/my-chauffeur/18706/`
