### ISSUE TITLE
abcvideo.cc warning & IP ban when open dev console

### ISSUE THREAD

**Issue by jjohns71** [uBlockOrigin/uAssets#8297]
### URL(s) where the issue occurs

`https://abcvideo.cc/1u8trpslsfqa.html`

### Describe the issue

when try access developer console it pops up warning message and then bans your IP after doing attempt twice

### Screenshot(s)

![abcvideo](https://user-images.githubusercontent.com/6795795/100637103-79b73b00-3300-11eb-9efc-caf78e174b34.png)

### Versions

- Browser/version: Chrome latest
- uBlock Origin version: 1.31.1b10

### Settings

default settings and filter
-

**Comment by uBlock-user** [comment]
Clear cookies and site data if you're already banned.
