### ISSUE TITLE
directrev.com popunder

### ISSUE THREAD

**Issue by brbsix** [uBlockOrigin/uAssets#83]
### URL(s) where the issue occurs

`watchseries-online.la`

### Describe the issue

Upon right/left clicking anywhere on the page at `watchseries-online.la`, a new page opens up with the url `watchseries-online.la`. The old page is now blank and the url is `https://ad.directrev.com/RealMedia/ads/adstream_sx.ads/S0001613/151835390301298620@x10?uln=en-us&je=false&ce=true&sr=1366x768&kw=&ref=`.

I've noticed similar (though not quite as aggressive) behavior with directrev ads on `monova.org` as well.

### Versions

- Browser/version: Google Chrome 52.0.2743.75 beta (64-bit) on Ubuntu 15.10
- uBlock Origin version: uBlock v0.9.5.0

### Settings

The issue occurs with no changes to uBO's default settings.

### Notes

I'm not terribly familiar with the rule syntax but I have tried all sorts of additions to the "My Filters" list, e.g. `||watchseries-online.la^$document,inline,popunder,popup,redirects,scripts,third-party` and `||directrev.com^$document,inline,popunder,popup,redirects,scripts,third-party` to no avail.

**Comment by Snapy** [comment]
Are your filter lists up to date ?
I see `/realmedia/ads/*$popup` in EasyList and `||ad.directrev.com^` in Peter Lowe’s Ad server list which take care of the popup on my side.
Also use the [logger] (/gorhill/uBlock/wiki/The-logger) to create filters.

**Comment by brbsix** [comment]
Filter lists are up to date. I purged then updated.

This is what the request log looks for `watchseries-online.la` when I right or left click anywhere on the page and the popunder (or whatever it's called) occurs:

![screenshot_2016-07-17_16-29-21](https://cloud.githubusercontent.com/assets/6672131/16903762/ddfb4d96-4c3b-11e6-9fbd-dd749e650612.png)

**Comment by Snapy** [comment]
I changed my previous comment, did you read it ?

**Comment by gorhill** [comment]
uBO works fine, the popunders are closed by the EasyList filter `||directrev.com^$third-party,popup`.

**Comment by brbsix** [comment]
That clears things up, apologies for the confusion.
