### ISSUE TITLE
radioloyalty.com

### ISSUE THREAD

**Issue by js017** [uBlockOrigin/uAssets#830]
When you go to http://player.radioloyalty.com/html5/index.html?stationID=2831&affiliateID=1 it says "please wait for your station to load" and doesn't load the radio station.

![radioloyalty com 001](https://user-images.githubusercontent.com/26278182/32693752-040a9756-c6fe-11e7-8437-3725b0fc0523.jpg)

![radioloyalty com 002](https://user-images.githubusercontent.com/26278182/32693753-07381bce-c6fe-11e7-9ffc-f3370b43694e.jpg)

Waterfox 55.2.2
uBlock Origin 1.14.18

If you disable uBlock Origin then the radio station looks like it's loaded, although it has ads, and still music doesn't actually play. Is there a way to fix that? Thanks.

**Comment by okiehsch** [comment]
The site does not play music with uBO-disabled, so there is no filter that can fix that.
To make the site "look like it is loaded" you can add
`@@||ad.lkqd.net/vpaid/formats.js$script,domain=player.radioloyalty.com`

**Comment by js017** [comment]
Ok. Thanks.
