### ISSUE TITLE
ublock origin detected

### ISSUE THREAD

**Issue by BajulaSupSap** [uBlockOrigin/uAssets#8303]
### URL(s) where the issue occurs

[https://lookmovie.io/]

### Describe the issue

[uBlock gets detected when trying to watch any film or series. This was not happening a few days ago.]

### Screenshot(s)

[https://imgur.com/a/oUOuaRP]

### Versions

- Browser/version: [Google Chrome 87.0.4280.66]
- uBlock Origin version: [v1.31.0]

### Settings

[No changes]
-

### Notes

[Disabled uBlock, was able to use the site properly. Enabled, it gets detected. Reinstalled uBlock, same result.]

**Comment by mapx-** [comment]
force updating all your lists (purge all caches then click "update now")
