### ISSUE TITLE
mitele.es broken

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#8304]
### URL(s) where the issue occurs

```
https://www.mitele.es/directo/
https://www.mitele.es/directo/divinity/
https://www.mitele.es/directo/mtmad-24h/
```

### Describe the issue

videos and live TV, no works

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.31.0]

### Settings

Default

### Notes

maybe this works:

`@@||pubads.g.doubleclick.net/gampad/ads*mitele.es$xhr,domain=imasdk.googleapis.com`

**Comment by mapx-** [comment]
@PIZZA90 needing account ?

**Comment by PIZZA90** [comment]
the filter works but is showing ads

`https://www.mitele.es/directo/telecinco/`

`@@||pubads.g.doubleclick.net/gampad/ads*mitele.es$xhr,domain=imasdk.googleapis.com`

**Comment by mapx-** [comment]
Can you provide an account ?

For ads (I guess video ads) try:
`*$media,redirect=noopmp3-0.1s,domain=mitele.es`

**Comment by PIZZA90** [comment]
other example URL ( no need account ) 

```
https://www.mitele.es/programas-tv/la-casa-fuerte/temporada-2/codigo-secreto/codigo-secreto-4-40_1008718075010/player/
https://www.mitele.es/programas-tv/el-programa-de-ana-rosa/2020/progr-3983-40_1008718075011/player/
```

both filters works well

**Comment by mapx-** [comment]
ok, so:
- no needing account only using a spanish ip
- I need another filter to whitelist a frame

so, these all the filters:
```
@@||imasdk.googleapis.com/js/core/$frame,domain=mitele.es
@@||pubads.g.doubleclick.net/*.mitele.es$xhr,domain=imasdk.googleapis.com
*$media,redirect=noopmp3-0.1s,domain=mitele.es
```

**Comment by mapx-** [comment]
maybe @lain566 could find better filters ? these ones above are identical to those I added for `vvvvid`

**Comment by PIZZA90** [comment]
in the same company, adding two new domains

`https://www.yasss.es/` and `https://www.uppers.es/`

! https://github.com/uBlockOrigin/uAssets/issues/1660

```
yasss.es,uppers.es,bemad.es,divinity.es,eltiempohoy.es,energytv.es,factoriadeficcion.com,mtmad.es,radioset.es##+js(aopw, adsInfoClient)
yasss.es,uppers.es,emad.es,cincomas.com,divinity.es,eltiempohoy.es,energytv.es,factoriadeficcion.com,mtmad.es,radioset.es##+js(aeld, load, hasAdblock)
```

**Comment by PIZZA90** [comment]
well.. this filter is breaking the comment system of all domains incorporated

`yasss.es,uppers.es,bemad.es,cincomas.com,divinity.es,eltiempohoy.es,energytv.es,factoriadeficcion.com,mtmad.es,radioset.es##+js(aeld, load, hasAdblock)`

however with the element picker of uBO it can be removed the antiadblock

**Comment by mapx-** [comment]
test

`uppers.es,yasss.es##+js(set, $MICROSITE_INFO.blockAdBlock, false)`

then see if works for all other pages

**Comment by PIZZA90** [comment]
apparently the other domains is fixed in **spa, por: AdGuard Spanish/Portuguese**

https://github.com/AdguardTeam/AdguardFilters/issues/69084

maybe the filter:
`##+js(aeld, load, hasAdblock)`  should be deleted, i dont know 🤔

**Comment by mapx-** [comment]
ok, I removed both filters

**Comment by lain566** [comment]
I can't reproduce any breakage, the player works fine for me.

@PIZZA90  update your filter lists and add these filters and try again
```
@@||imasdk.googleapis.com/js/core/$frame,domain=mitele.es,badfilter
@@||pubads.g.doubleclick.net/*.mitele.es$xhr,domain=imasdk.googleapis.com,badfilter
```
Is the video player still broken for you?

**Comment by mapx-** [comment]
Still needing at least in firefox the first filter (using Madrid ip)

**Comment by lain566** [comment]
That filter is already added in Easylist

<details>

![Captura de pantalla 2020-12-02 201724](https://user-images.githubusercontent.com/27441315/100920705-c86cfc80-34db-11eb-949e-5c4d055602b8.png)
</detalis>

**Comment by mapx-** [comment]
mhm .. right, restarting FF is all fine now, so, it seems no filter is necessary anymore

**Comment by lain566** [comment]
At least for me, those filters are not necessary.

**Comment by mapx-** [comment]
@PIZZA90 in the end no filter is needed, can you test again updating first all your lists ?

**Comment by PIZZA90** [comment]
solved in easylist?

you are using this lists?

**spa, por: AdGuard Spanish/Portuguese 
spa: EasyList Spanish**

if I deactivate them, it doesn't work well, i need 1 minute for reproduce the video. anyway with default settings all is ok.

![Captura](https://user-images.githubusercontent.com/33556647/100927274-f4d94680-34e4-11eb-8d3b-c8e26aae3d07.PNG)
