### ISSUE TITLE
spleis.no

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#8305]
### URL(s) where the issue occurs

`https://www.spleis.no/`

### Describe the issue

Fullpage animated snowfall, which takes up considerable CPU resources (Around 25% of my Intel i4-4770), and which requires `##+js` to fix as far as I can personally determine.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/22780683/100857881-8a48ec00-348d-11eb-81c0-da77eef82336.png)

### Versions

- Browser/version: Chrome 87.0.4280.66 x64
- uBlock Origin version: 1.31.1b12 + IDCAC 3.2.5

### Settings

![image](https://user-images.githubusercontent.com/22780683/100858124-dbf17680-348d-11eb-8f05-e0e65a9e5d0f.png)
![image](https://user-images.githubusercontent.com/22780683/100858162-e9a6fc00-348d-11eb-8368-b104f2052d0b.png)

### Notes

The snowfall seems to be embedded into `https://spleis.freetls.fastly.net/public/app.js?v=2uuhg-9czigh`, but I was unable to determine exactly how they did so.

Presuming this gets added to uAssets Annoyances, I'll borrow you guys' eventual fix and add it to Nordic Filters' anti-'CPU slaughtering' section as well.

**Comment by mapx-** [comment]
add

`spleis.no##+js(set, __INITIAL_STATE__.features.should-show-snow, false)`

working only for chrome, FF seems to have some policy on page

**Comment by DandelionSprout** [comment]
Thanks for the help once again.

**Comment by uBlock-user** [comment]
>  FF seems to have some policy on page

CSP header is present in response header, scriptlets won't work on Firefox.

**Comment by mapx-** [comment]
yeah .. working only with scriptlet-doctor
https://github.com/JustOff/scriptlet-doctor/releases
