### ISSUE TITLE
worldfree4u.ws

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#831]
Popup ads and and malware download buttons on `https://www.worldfree4u.ws`.

**SS:** https://i.imgur.com/1MDymuK.png
**Error URL:** `https://www.worldfree4u.ws/watch/tt3437996`

These domains should be blocked
```
cashinme.com
linkforyoud.com
```

`worldfree4u.ws##.adButton`

_**Note:** Using uBO 1.14.16 on Chrome 62 with the default filters and settings._

**Comment by mapx-** [comment]
```
@@||content.jwplatform.com/libraries/$script,domain=worldfree4u.ws
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/$script,domain=worldfree4u.ws
@@||worldfree4u.ws^$generichide
||worldfree4u.ws/promotion/$subdocument
```

**Comment by ghajini** [comment]
Antiadblock 

`https://www8.world4free.mobi/movies/bollywood/bollywood-480p-movies/kabir-singh-2019-movie-400mb-dvdscr-cleaned-audio/`
