### ISSUE TITLE
random shein popups

### ISSUE THREAD

**Issue by aldiener58** [uBlockOrigin/uAssets#8310]
I am a bit reluctant to open such a broad issue but this issue is happening over and over again.

I can be watching a video, browsing, or opening a new tab and suddenly a new tab is opened with an ad to the same website. The website is  

```
https://us.shein.com/style/Glamorous-Dresses-sc-00100595.html?utm_source=popads.net&utm_medium=cpm&url_from=popadsus_20190320_LuxeDress
```

I have cleared caches, deleted cookies, restarted my computer, and updated filters on uBo.

I have never had this happen before and I am at a complete loss as to how this is happening.
Any thoughts?

Thank you,
AD
uBo Version 1.31.0
Google Chrome Version 87.0.4280.88

**Comment by mapx-** [comment]
You have to provide the previous page where when clicking you get redirected to this one

**Comment by aldiener58** [comment]
@mapx- I have no previous page because sometimes it simply open a new tab without exhibiting any pattern. I will keep an eye out for the next time to see what I was doing just before. I wish I had more information to provide :-) If you want, I will delete the post and wait until I have more information to share.

**Comment by mapx-** [comment]
In this case could be your system is infested by some malware or .. did you install some other extension recently ?

**Comment by aldiener58** [comment]
I have added no new extensions and I only have LastPass and uBo running.

**Comment by mapx-** [comment]
You should scan your system for malware, use:
https://www.malwarebytes.com/mwb-download/

Stay on free trial.

**Comment by aldiener58** [comment]
Thank you @mapx-. I will try this suggestion.
