### ISSUE TITLE
(Annoyances Request) Instagram turn on notifications popup

### ISSUE THREAD

**Issue by aviegdown** [uBlockOrigin/uAssets#8315]
### URL(s) where the issue occurs
`https://www.instagram.com/`

### Describe the issue

instagram keep asking to enable notification when first time logged in
 

### Screenshot(s)
![ubo](https://user-images.githubusercontent.com/72583750/101027438-970f3200-35aa-11eb-92df-5eddfa1ec8ae.png)

### Versions

- Browser/version: firefox 83.0
- uBlock Origin version: 1.31.0

### Settings

- default filter + annoyances

### Notes

i created this filters, works fine

`www.instagram.com##body:style(overflow: auto !important;)`
`www.instagram.com##[src*="/static/images/ico/"]:upward(7)`

**Comment by Yuki2718** [comment]
Fixed, made more specific to avoid false positive.

**Comment by Yuki2718** [comment]
Hiding that caused problem after I went somewhere, returned back with browser's back button, and clicked home icon i.e. can't enter home as it only prompts the hidden popup. I have to take video SS but now don't have time. Disabled temporary.
@krystian3w Can you take a look?

**Comment by krystian3w** [comment]
maybe something like:

`##+js(set, ips.utils.notification.supported, false)`

`##+js(aopr, Notification.requestPermission)`

**Comment by krystian3w** [comment]
or legacy:

`##+js(grant-fake-notification)`

```js
# Grant fake notification permission
grant-fake-notification.js application/javascript
(function() {
    Notification = function() { };
    Notification.permission = 'default';
    Notification.requestPermission = function(callback) {
        Notification.permission = 'granted';
        if ( callback ) {
            setTimeout(callback, 0, 'granted');
        }
        return Promise.resolve('granted');
    };
})();
```

if serviceWorker no tests your accept/reject.

**Comment by Yuki2718** [comment]
@krystian3w non-procedural filter `instagram.com##.Yx5HN.RnEpo` also doesn't cause blink, but I'm not sure if it's universal.

**Comment by mapx-** [comment]
could you test for breakage ?

`instagram.com##:xpath(//*[contains(@src,'static')]):upward([role="presentation"])`

**Comment by krystian3w** [comment]
IMO blink less if manually accept cookies before logon.

**Comment by Yuki2718** [comment]
@mapx- Still causes blink.

**Comment by Yuki2718** [comment]
@krystian3w Does `instagram.com##.Yx5HN.RnEpo` work for you and doesn't cause FP?

**Comment by krystian3w** [comment]
See these:

https://github.com/uBlockOrigin/uAssets/commit/aaddd2b9a110da3ee8ee3f39a5f4ac84cd1653ba

@yourduskquibbles  where I found "followers"?

**Comment by aviegdown** [comment]
omg I got too much overthink, `instagram.com##.Yx5HN` work for me. however that element similar to logout popup 
![IMG_20201210_022822](https://user-images.githubusercontent.com/72583750/101677900-c7b20880-3a8f-11eb-8b89-3629277fdbf3.jpg)

`www.instagram.com##.Yx5HN:not(h3:has-text(Log))` is this good?

**Comment by krystian3w** [comment]
IMO still can generate heavy blinks with push notifications.

but good know:

`##.Yx5HN.RnEpo` = almost any instagram pop-up
