### ISSUE TITLE
Inoreader anti-adb

### ISSUE THREAD

**Issue by mbnoimi** [uBlockOrigin/uAssets#8316]
### URL(s) where the issue occurs

`https://www.inoreader.com/all_articles`

### Describe the issue

During using inoreader I'm unable to see any ads but periodically I get a popup ad as shown below

### Screenshot(s)

![Screenshot_2020-12-03_22-26-41](https://user-images.githubusercontent.com/284547/101084367-e95a4e00-35be-11eb-8df0-788498b4e40b.png)

### Versions

- Browser/version: Firefox 83.0 (64-bit)
- uBlock Origin v1.31.0

### Settings

Default settings

### Notes

To be able to catch this popup you need to make sign in.

**Comment by mapx-** [comment]
It's very difficult for me to reproduce anti adb for this page.
However, as a workaround, add:

```
inoreader.com##.inno_dialog_content_scrollable
inoreader.com##.inno_dialog_scroll_overlay
inoreader.com##.inno_dialog_modal_overlay
||inoreader.com/sinner.php$subdocument
inoreader.com##[id^="leaderboard_ad"]
inoreader.com##.ad_title
inoreader.com##.bottom-center
inoreader.com###sinner_container:style(height: 1px !important; width: 1px !important;)
inoreader.com##[id^="leaderboard_ad]"
||inoreader.com/adv/$image
inoreader.com##[src^="https://www.inoreader.com/adv/"]
```

.. but it has a bad side: you cannot open the settings or add a new subscription. When you want to add a new subscription just comment the filters above (only the first 3 ..)

**Comment by krystian3w** [comment]
No help `:has-text` or `:watch-attr()`?

**Comment by duhd1993** [comment]
It's actually very easy to block this. ``inoreader.com##+js(aopr, gc)`` I'm leaving it here for anyone searching hard enough.
