### ISSUE TITLE
bloomberg video content 

### ISSUE THREAD

**Issue by jahnson** [uBlockOrigin/uAssets#8317]
### URL(s) where the issue occurs

`https://www.bloomberg.com/news/videos/2020-12-03/musk-is-highly-confident-we-ll-get-to-mars-in-six-years-video`

### Describe the issue

Any video content on bloomberg.com such as the one above does not play.  It did play as of a few weeks ago.    

### Versions

- Browser/version: [FF 83.0 ]
- uBlock Origin version: [1.31.0]

### Settings

Default Settings 
Block media elements larger than 768K (but even if I uncheck this it makes no difference) 
the rest of the settings under Default behavior are not checked 

-

### Notes

i have globally blocked all 3rd party scripts, but for bloomberg.com I have locally nooped them.  
I have also local noop'd all of the individual trackers one by one in the settings, and there are a lot of them!  Yet the video is blocked.  
If I turn off UBO for this site and reload the page, it plays, as do subsequent videos on this site, until I remove all of the cookies and reload the page, and then it does not play.  
Interestingly, in another browser where I use ghostery, I only have to enable 2 trackers for this video to play.  But enabling those in UBO does not do the job.  So I wonder if the problem is in something else that UBO is doing.  

I have looked in the logger, and things like:
`https://www.googletagmanager.com/gtm.js?id=GTM-MNTH5N`
are red, despite me having locally nooped google tag manager, so I do not understand what UBO is doing there.  

Thank you in advance.

**Comment by llacb47** [comment]
Plays for me after spinning for 15 seconds.

**Comment by mapx-** [comment]
well, FF / chrome, needing 

```
@@||sourcepointcmp.bloomberg.com^$xhr,1p
@@||location.bloomberg.com/query$xhr,1p
```

**Comment by ryanbr** [comment]
Suggested fixes not working for me, looking into it

**Comment by jahnson** [comment]
That did the job - thanks everyone
