### ISSUE TITLE
needgayporn.com - broken video NSFW

### ISSUE THREAD

**Issue by Innerbeard** [uBlockOrigin/uAssets#8318]
### URL(s) where the issue occurs

`https://www.needgayporn.com/videos/7566/tom-lord-mike-rios-prime-beef/`

### Describe the issue

When opening this webpage the video / video player loads normally and is visible, but disappears the moment the page is finished loading. This happens only when the adblocking is active, so I assume this is caused by some type of anti-adblock.

### Screenshot(s)

https://ibb.co/1786x10

### Versions

- Browser/version: Google Chrome Version 87.0.4280.88 (Official Build) (64-bit)
- uBlock Origin version: 1.31.0

**Comment by Innerbeard** [comment]
Unable to reproduce? So the video player loads normally for you?

**Comment by okiehsch** [comment]
Yes. I can watch the videos without issue using Chrome and uBO 1.31.0 with a default setup.

**Comment by Yuki2718** [comment]
Yes video is working fine with default filter lists. But you didn't write down what filter lists you use.
(I suspect the current instruction `<!-- [List here all the changes you made to uBO's default settings] -->` may not be clear enough - it doesn't help if regional list is causing a problem.)

**Comment by Yuki2718** [comment]
Do you have Liste FR or AdGuard Français subscribed?

**Comment by mapx-** [comment]
yeah it's `##.is-ad-visible`

**Comment by uBlock-user** [comment]
fixed with https://github.com/uBlockOrigin/uAssets/commit/9e6c327e7ca7dfed7a4a8e9a245af06676031c43
