### ISSUE TITLE
Video not loading on WashingtonPost

### ISSUE THREAD

**Issue by thrwat** [uBlockOrigin/uAssets#832]
### URL(s) where the issue occurs
https://www.washingtonpost.com/news/worldviews/wp/2017/11/12/pray-for-an-islamic-holocaust-tens-of-thousands-from-europes-far-right-march-in-poland/?tid=sm_fb&utm_term=.313882a1a961
### Describe the issue

Video does not load

### Versions

- Browser/version: Chrome Latest
- uBlock Origin version:  Latest

**Comment by gorhill** [comment]
Video loads fine here.

**Comment by thrwat** [comment]
Go the the url, and try to play the video. Then try to block off. The video does not correctly play.

**Comment by okiehsch** [comment]
The video plays fine.
![unbenannt](https://user-images.githubusercontent.com/16838044/32740022-e621183c-c8a1-11e7-9e02-babcabd34e87.JPG)
