### ISSUE TITLE
stages.defense.gouv.fr is blank when uBlock is enabled

### ISSUE THREAD

**Issue by Axel57000** [uBlockOrigin/uAssets#8322]
### URL(s) where the issue occurs

`https://www.stages.defense.gouv.fr/`

### Describe the issue

Site is blank when uBlock is enabled. The problem seems to come from the script "​`https://www.stages.defense.gouv.fr/lib/tarteaucitron/tarteaucitron.js`" which is blocked by the lists EasyList Cookie and Fanboy's Annoyance

### Screenshot(s)

![Logger_stages_defense_gouv](https://user-images.githubusercontent.com/31167833/101198191-5f17f580-3663-11eb-9ce7-77c92b7e712f.png)

### Versions

- Browser/version: Firefox 83.0 x64 on Windows 10 Pro 20H2 19042.630
- uBlock Origin version: 1.31.3b0

### Settings

All integrated uBlock lists + regional lists from France, Russia and Iran

### Notes

To fix the problem, either disable EasyList Cookie and Fanboy's Annoyance lists or apply this filter: @@||www.stages.defense.gouv.fr/lib/tarteaucitron/tarteaucitron.js$script,domain=www.stages.defense.gouv.fr

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by ryanbr** [comment]
Fixed
