### ISSUE TITLE
tf1.fr replay player doesn't work when uBlock is enabled

### ISSUE THREAD

**Issue by Axel57000** [uBlockOrigin/uAssets#8323]
### URL(s) where the issue occurs

`https://www.tf1.fr/tmc/quotidien-avec-yann-barthes/videos/quotidien-premiere-partie-du-3-decembre-2020-81342277.html`

### Describe the issue

Replay player doens't work when uBlock is enabled. The problem seems to come from the script "`https://www.tf1.fr/public/2.14.5/universal-view-ui-button-share-ShareButton_4f2e08a0715de4cfdc18.js`" blocked by Fanboy's Annoyance and Fanboy's Social lists.

### Screenshot(s)

Site: 
![image](https://user-images.githubusercontent.com/31167833/101202537-b02ae800-3669-11eb-8162-c16cda2bef6f.png)
Logger: 
![image](https://user-images.githubusercontent.com/31167833/101202562-bae57d00-3669-11eb-9d50-05c0315c9348.png)

### Versions

- Browser/version: Firefox 83.0 x64 on Windows 10 Pro 20H2 19042.630
- uBlock Origin version: 1.31.3b0

### Settings

All integrated uBlock lists + regional lists from France, Russia and Iran

### Notes

To fix the problem, 2 solutions: disabled Fanboy's Annoyance and Fanboy's Social lists or apply this filter: @@||www.tf1.fr/public/2.14.5/universal-view-ui-button-share-ShareButton_4f2e08a0715de4cfdc18.js$script,domain=www.tf1.fr

This will allow the video to launch.
However, even if the video launches, ads will appear. To remove them, switch uBlock Origin to hard mode and allow only the scripts necessary for the site and video playback.

Example: 
![Capture d’écran (81)](https://user-images.githubusercontent.com/31167833/101203039-6262af80-366a-11eb-886a-573f742f9047.png)

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by mapx-** [comment]
yeah, tested, needing

`@@||tf1.fr/public/*/universal-view-ui-button-share-ShareButton$script,1p`
