### ISSUE TITLE
https://www.lowesgiftcardbonus.com/#/ppdpromodisplay

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#8324]
### URL(s) where the issue occurs

`https://www.lowesgiftcardbonus.com/#/ppdpromodisplay`

### Describe the issue

 

Blank page

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

-

### Notes

`@@||www.lowesgiftcardbonus.com/js/third-party/angulartics-google-analytics/dist/angulartics-ga.min.js$script,domain=www.lowesgiftcardbonus.com`

**Comment by mapx-** [comment]
`@@||lowesgiftcardbonus.com/js/third-party/angulartics-google-analytics/dist/angulartics-ga.min.js$script,1p`

@ryanbr
