### ISSUE TITLE
rapidvideo.com

### ISSUE THREAD

**Issue by mat41997** [uBlockOrigin/uAssets#833]
**steps to reproduct**

*problem 1*
- install popup strict
`https://add0n.com/popup-blocker.html`
- join to 
`https://otakustream.tv/anime/hokuto-no-ken/episode-3/` or `https://www.rapidvideo.com/?v=FKKQ4JUN0Z`
![2017-11-13 16_08_14-hokuto no ken episode 3 - watch anime online english subbed](https://user-images.githubusercontent.com/5884000/32732934-4622336a-c88e-11e7-98cd-41a49d854579.png)
- clear cookie/cache and refresh this site
- click play on `rapidvideo` player
![2017-11-13 16_07_23-profitmaximizer osiaga duze dochody uzywajac autopilota](https://user-images.githubusercontent.com/5884000/32733240-0369ff2a-c88f-11e7-8cf8-03b9aa415283.png)

*problem 2*
- join to
`https://www.rapidvideo.com/?v=FKKQ4JUN0Z`
- clear cookie/cache and refresh this site
- and i don't can move here when ublock is on
![2017-11-13 16_41_48-003](https://user-images.githubusercontent.com/5884000/32734213-a038e1e8-c891-11e7-9949-07c893db7f64.png)

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

popup strict
ubo 1.14.16 & ubo-pe 12.73
chrome 62.0.3202.89
win10 x64

**Comment by uBlock-user** [comment]
`otakustream.tv##script:inject(abort-current-inline-script.js, parseInt, tabunder)`

**Comment by gorhill** [comment]
I can't reproduce an issue with `https://www.rapidvideo.com/?v=FKKQ4JUN0Z`.

**Comment by uBlock-user** [comment]
There's already a filter for rapidvideo - `rapidvideo.com##script:inject(abort-current-inline-script.js, atob, tabunder)`

however, I'm still able to reproduce the tabunder on rapidvideo too.

**Comment by gorhill** [comment]
I can't reproduce, someone else will have to investigate. Note that there is no support for when an issue occurs only with another extension -- the filters added to uBO's own filters are those needed when uBO is used alone and with default filter lists/settings.

**Comment by uBlock-user** [comment]
I disabled all other extensions and it still happens on my end on Chromium 64, but it's fine if you want to keep it closed, I only posted for rapidvideo as I was also able to reproduce the tabunder.

**Comment by gorhill** [comment]
Does your own suggested filter fix your case?

**Comment by lain566** [comment]
I can't reproduce it on `rapidvideo.com`

**Comment by uBlock-user** [comment]
Yes, it does.

**Comment by okiehsch** [comment]
I can't reproduce, but I get the `4f6b2af479d337cf.com` request, which "normally" leads to popups,
If I add `rapidvideo.com##script:inject(abort-current-inline-script.js, parseInt, tabunder)` there is no request to `4f6b2af479d337cf.com`.

**Comment by mapx-** [comment]
here `https://www.rapidvideo.com/e/FH7AT7LMK1` I get a redirect / tabunder

I cannot find something better than `||rapidvideo.com$inline-script`

from https://forums.lanik.us/viewtopic.php?f=62&t=34331

**Comment by okiehsch** [comment]
`rapidvideo.com##script:inject(abort-current-inline-script.js, atob, tabunder)`

**Comment by mapx-** [comment]
and this existent filter why does not work ?
`rapidvideo.com##script:inject(abort-current-inline-script.js, parseInt, tabunder)`

**Comment by okiehsch** [comment]
I don't know, the inline script triggering the popunders is basically the same on all sites, as far as I can see.
In all cases either `##script:inject(abort-current-inline-script.js, atob, tabunder)` or
`##script:inject(abort-current-inline-script.js, parseInt, tabunder)` fixes the issue.

**Comment by gorhill** [comment]
Without looking at the code, by the look of it, it could be because sometimes they use built-in base64 decoding (`atob`), sometimes they use js-based base64 decoding (`parseInt`).

**Comment by mapx-** [comment]
I edited the last chromium uBo release, adding the logger changes here:
https://github.com/gorhill/uBlock/issues/2877#issuecomment-330429588

I switched OFF ublock filters and tested both filters (separately). 
The fact is both are logged but only `atob / tabunder` works. 

```
(function() { var target = 'atob'; if ( target === '' || target === '{{1}}' ) { return; } var needle = 'tabunder', ...
(function() { var target = 'parseInt'; if ( target === '' || target === '{{1}}' ) { return; } var needle = 'tabunder', ....

```

**Comment by gorhill** [comment]
Ok, about that silly comment... If needed, I could modify the scriptlet to be able to hook into more than one global property:

    ##script:inject(abort-current-inline-script.js, atob|parseInt, tabunder)

Just ask if you think it would be convenient.

**Comment by mapx-** [comment]
why not if it's not big deal adding multiple global properties

**Comment by okiehsch** [comment]
Is it really **needed**?
In this issue all that is required is hooking into `atob` **or** `parseInt`.
Just my two cents.

**Comment by gorhill** [comment]
Sure, just throwing the idea out there if ever it becomes convenient.

**Comment by sebast889** [comment]
@okiehsch
> In this issue all that is required is hooking into atob or parseInt

Am wondering why are there 2 filters for both parseInt and atob in uBO filters then? Is the parseInt filter not needed anymore? Or if it is needed isn't it better like @gorhill suggested to modify scriptlet to use just 1 filter as `##script:inject(abort-current-inline-script.js, atob|parseInt, tabunder)`?

**Comment by okiehsch** [comment]
I never saw an issue were both were needed, I agree one of the two is  probably redundant, do you have an example link?

**Comment by uBlock-user** [comment]
> I never saw an issue were both were needed, 

Happens on https://www4.9anime.is/ on my end, and on every domain where this tabunder script is used. One is just not enough anymore. I have to use the other to neuter it. I hope gorhill considers modifying the scriptlet nonetheless.

**Comment by okiehsch** [comment]
`9anime.*##script:inject(abort-current-inline-script.js, parseInt, tabunder)` works fine on my end, but if this is does not work for everyone then of course I agree, gorhill should modify the scriptlet.

**Comment by uBlock-user** [comment]
Unfortunately  it doesn't, on my end atleast, and everywhere the same script is used, I have been using them in pairs that's why. It used to work but I think the author modified it and now it requires two of them.

**Comment by sebast889** [comment]
@gorhill's post https://github.com/uBlockUrigin/uAssets/issues/833#issuecomment-347030057 is true and both can be used on the same website because these webmasters will just keep rotating the scripts. I also agree that modifying the scriplet would be best so we don't have to worry about which one works for who and it will also reduce duplicate filters.

**Comment by ghajini** [comment]
`https://www.rapidvideo.com/v/G49561S7S8`
Popup ads

**Comment by bogachenko** [comment]
mmmmmmmmmmaaaaaaaapx-

add the rule
`||rapidvideo.com^$script,badfilter`

**Comment by mapx-** [comment]
provide a valid reason for your request

**Comment by bogachenko** [comment]
because it blocks the scripts on this site, see for yourself

**Comment by bogachenko** [comment]
can not play anything. + player's design breaks (it becomes default from the browser)

**Comment by uBlock-user** [comment]
I have it in [my list](https://github.com/uBlock-user/uBO-Personal-Filters/blob/master/uPF.txt#L166) for long time, it's a bad filter.

**Comment by gorhill** [comment]
I am pretty sure @mapx- is asking for specific URLs where the filter is causing issues.

**Comment by bogachenko** [comment]
@gorhill > https://github.com/uBlockOrigin/uAssets/issues/833#issuecomment-504691489

all url starting with `rapidvideo.com`

**Comment by gorhill** [comment]
I just tried the URL last posted in thread and it played fine. You need to make the case why `||rapidvideo.com^$script,badfilter` is needed, throwing a couple of words is not helpful and just waste time really. Provide all the details, specific URLs, steps to reproduce, and explain exactly what is not working along with screenshots ("player's design breaks" is too vague), otherwise there is nothing actionable.

**Comment by bogachenko** [comment]
I will not do this. We have been discussing one filter for too long. I will add to my custom list how the anime boy did.

have a nice day.

**Comment by ghajini** [comment]
`www.rapidvideo.com/v/G70VZE2VY3`

Anyone able to play the video?
,may be some filters broke playback

**Comment by uBlock-user** [comment]
RapidVideo sunsetted itself -- `https://torrentfreak.com/rapidvideo-shuts-down-following-legal-pressure-from-warner-bros-and-netflix-191021/`

You may remove all the filters associated with both the domains now.
