### ISSUE TITLE
Block new tab with blocked content

### ISSUE THREAD

**Issue by erosman** [uBlockOrigin/uAssets#8332]
### URL(s) where the issue occurs
For example navigation on : `https://www.cocomanhua.com/show?orderBy=update&page=2`

```
uBlock Origin has prevented the following page from loading:

https://syndication.exdynsrv.com/splash.php?cat=&idzone=3945090&type=8&p=https%3A%2F%2Fwww.cocomanhua.com%2Fshow%3ForderBy%3Dupdate&sub=&block=1&el=&tags=&scr_info=aW5saW5lfHBvcE1hZ2ljfDEuMC4w

Because of the following filter:

||exdynsrv.com^

Found in: EasyList 
```

For example: `https://mangahub.io/`

```
uMatrix has prevented the following page from loading:

https://syndication.exdynsrv.com/splash.php?cat=&idzone=4074916&type=8&p=https%3A%2F%2Fmangahub.io%2Fmanga%2Fxian-ni&sub=&block=1&el=&tags=&scr_info=aW5saW5lfHBvcE1hZ2ljfDEuMC4w

    without parameters = https://syndication.exdynsrv.com/splash.php
    cat
    idzone = 4074916
    type = 8
    p = https://mangahub.io/manga/xian-ni
    sub
    block = 1
    el
    tags
    scr_info = aW5saW5lfHBvcE1hZ2ljfDEuMC4w
```

### Describe the issue

Sites create a new tab with the link URL and load the ads in the current tab. Is it possible to prevent this behaviour? For example, prevent the action or auto-close the ad tab?

### Versions

- Browser/version: Firefox 85.0a1 (2020-12-05) (64-bit)
- uBlock Origin version: 1.31.0
- uMatrix version: 1.4.0

### Settings

- default

**Comment by keczuppp** [comment]
> Sites create a new tab with the link URL and load the ads in the current tab. Is it possible to prevent this behaviour? For example, prevent the action or auto-close the ad tab?

- yes, `uBO` has `$popunder` option https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#popunder designed exactly for that purpose, we use it recently here:
https://github.com/MajkiIT/polish-ads-filter/issues/17906 ([ site 1](https://rabatio.com )) or
https://github.com/MajkiIT/polish-ads-filter/issues/18048 ([ site 2]( https://alerabat.com), [site 3](https://kodyrabatowe.olx.pl/), [site 4](https://kod.rabatowy.pl/benevento), [site 5](https://salesandshopping.pl/wydarzenia/weekend-znizek-z-magazynem-wysokie-obcasy-extra-w-calej-polsce-17-19-wrzesnia-2020-29631) )
https://github.com/MajkiIT/polish-ads-filter/commit/57df5d80972737cdf3b3183a4723ea1d5cba63e4
- other adblockers like `ABP` and `AG` lack `$popunder` functionality so they require scriplets like 
https://github.com/MajkiIT/polish-ads-filter/commit/5603191d62ae3e9f7fd924fe0c132ceacc7ba9da#diff-b254bffa93224baeab9ba8bde874f3c03bd0e13ebdb062a35f08720ebf33229fR194

@krystian3w
