### ISSUE TITLE
Doubleclick / GoogleAds found a way to bypass your filters

### ISSUE THREAD

**Issue by yorktown48** [uBlockOrigin/uAssets#8334]
### URL(s) where the issue occurs
`
https://www.ebay.com/itm/3ft-USB-Cable-For-LaCie-Rugged-Thunderbolt-1TB-STEV1000400-2TB-STEV2000400-Drive/132042216676?hash=item1ebe5454e4:g:gecAAOSwEMxa6V9g`

### Describe the issue

SEE VIDEO:  `https://www.dailymotion.com/video/x7xxg9h`  
PASSWORD:  dec7ublock
(all lower case)

 

### Screenshot(s)

Video shows the screenshots:  `https://www.dailymotion.com/video/x7xxg9h`  
PASSWORD:  dec7ublock
(all lower case)

### Versions

- Browser/version: Firefox 82.0.3
- uBlock Origin version: uBlock Origin v1.31.0

### Settings
(all the below boxes were checked)

Hide placeholders of blocked elements
Show the number of blocked requests on the icon
Make use of context menu where appropriate
I am an advanced user (required reading)
Disable pre-fetching (to prevent any connection for blocked network requests) 
Disable hyperlink auditing 
Prevent WebRTC from leaking local IP addresses 
Block CSP reports

Filter lists:  All boxes checked except: Ignore generic cosmetic filters

### Notes

AS you see in the video,  Google has found a way to bypass the filter.   I tried individually blocking each of the ebay scripts as well.  Unless Google ads are being sent through the `www.ebay.com` domain directly, they or ebay found a way to bypass your system.  Its not on other sites I surf.  Just ebay.

**Comment by uBlock-user** [comment]
As per the video you're using `allow` instead of `noop`, which is disabling existing filters fromm EasyPrivacy and Easylist as a result, for two domains `ebay.com` and `ebaystatic.com`

**Comment by uBlock-user** [comment]
On a second note, you also have `ebay.com` whitelisted(uBO power button appears in white instead of blue) which is why dynamic filtering is also of no use as uBO is completely disabled on `ebay.com`.

**Comment by yorktown48** [comment]
Thanks.  I didn't see that I listed ebay as a trusted site.   I removed it and now the google ads are gone.   Thanks
