### ISSUE TITLE
bdb.com.pl

### ISSUE THREAD

**Issue by bug-rules** [uBlockOrigin/uAssets#8335]
`https://www.bdb.com.pl/`

blocked right click and some more by:

`oncontextmenu="return false" onselectstart="return false" onselect="return false" oncopy="return false" ondragstart="return false" ondrag="return false" onbeforeprint="document.body.style.visibility = 'hidden'; alert('Wydruk jest niedostępny!')" onafterprint="document.body.style.visibility = 'visible'" >`

**Comment by JobcenterTycoon** [comment]
They defuse printing again

**Comment by uBlock-user** [comment]
It's an annoyance now, click OK on the alert dialog and you will be able to print, you can use `bdb.com.pl##+js(alert-buster)`
