### ISSUE TITLE
telepisodes.org

### ISSUE THREAD

**Issue by jjohns71** [uBlockOrigin/uAssets#8336]
### URL(s) where the issue occurs
1. `https://www1.telepisodes.org/tv-series/gold-rush-alaska/season-11/episode-7/`

After bunch of pop ads and successful click a `host link` button a second page (below) with more ads is presented. 

2. `https://www1.telepisodes.org/open/link/16623150/`
Need to click `click here to visit this link!` at least twice to get through popads and to the actual video host.

### Describe the issue

pop ads when clicking a host link. "new message" ads, flashing titlebar after clicking through to a secondary link, more popads

### Versions

- Browser/version: Chrome Version 88.0.4324.27 (Official Build) beta (64-bit)
- uBlock Origin version: Latest dev build

### Settings

Default uBO and filter lists
-

**Comment by jjohns71** [comment]
`Play video` button on second link `https://www1.telepisodes.org/open/link/16623150/` is also fake and should be removed

**Comment by jjohns71** [comment]
5 second countdown and hidden link on secondary link `https://www1.telepisodes.org/open/link/16623150/` appears to be completely fake as well

Could also add 
`telepisodes.org###play_button:style(display:block!important;)`
`telepisodes.org###loading_button`

**Comment by stephenhawk8054** [comment]
There's an anti-adblock after a few seconds.

URL: `https://www1.telepisodes.org/open/link/17402602/`

![image](https://user-images.githubusercontent.com/66517106/140441911-ee8052a1-853d-4038-89f1-4fbfe777de57.png)

Firefox 94.0.1, ublock 1.38.6 default

Proposed filter:

`@@||telepisodes.org^$ghide`
