### ISSUE TITLE
[Breakage] https://informaxonline.com

### ISSUE THREAD

**Issue by sanGtH** [uBlockOrigin/uAssets#8339]
### URL(s) where the issue occurs

`https://informaxonline.com/?link=Ispwi`

### Describe the issue

When UBlockOrigin is ON, the **"Double click to generate the link"** button disappears. Because of this, 
we can't proceed to the next link.

### Versions

- Browser/version: **FF 80.x and Chrome 87.xx**
- uBlock Origin version: **v1.31.2**

### Settings
All default settings.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/101432237-c73b3580-3908-11eb-85bb-6fc0d1267332.png)

**Comment by sanGtH** [comment]
I just cheked. It's working on FF but not on chrome. The issue  still persists in chrome.
![image](https://user-images.githubusercontent.com/13797193/101432842-a20ded80-392f-11eb-9f23-781bda4109ba.png)

**Comment by okiehsch** [comment]
My screenshot is was taken using Chrome.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/101433267-ad9aed80-390a-11eb-9846-35fcc2ed5163.png)

**Comment by okiehsch** [comment]
Have you tried updating your filter lists?

**Comment by ghajini** [comment]
From where you get the link?

**Comment by okiehsch** [comment]
I pasted your link `https://informaxonline.com/?link=Ispwi` then I had to solve a captcha and that results in the screenshot you see.

**Comment by sanGtH** [comment]
I have updated the filters but maybe purge and update would work. So i shall try and check.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/8339#issuecomment-740342616

**Comment by sanGtH** [comment]
Here's how I got the link :
https://pngit.live/vZeC
https://informaxonline.com/?link=PKqT
Here  i see the **"I am not a robot"** button. After solving the captcha, it redirects to https://informaxonline.com/#
where i don't see the **"double click to generate the link"** button.

**Comment by okiehsch** [comment]
Well, I don't know what to tell you it works on my end.
The countdown timer does not seem to work on your end. 
`informaxonline.com##+js(nano-sib)`
works as expected for me using Chrome.

**Comment by sanGtH** [comment]
Could you please suggest me a workaround at my end?

**Comment by ghajini** [comment]
**Reset browser settings, update to new
reset ubo settings or reinstall ublock origin
Restart browser, go to ubo options purge all caches>update now
now test with ublock origin enabled **ONLY**

**Comment by uBlock-user** [comment]
Did you also disable all other extensions when testing ?

**Comment by sanGtH** [comment]
I found that "fuckfuckadblock" was to be blamed.. after disabling it, the button appears

**Comment by uBlock-user** [comment]
Remove that list from uBO.

**Comment by ghajini** [comment]
You don't need fuckfuckadblock or sort of this....all are taken care by ublock origin

**Comment by ghajini** [comment]
@uBlock-user how about adding these to template
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

**Comment by sanGtH** [comment]
@ghajini I use the fuckfuckadblock to bypass the annoying Adblock detection scripts on the websites.

**Comment by uBlock-user** [comment]
@sanGtH uBO already adds fixes for that, you don't need anything else for anti-adblock, just report sites on the tracker and fixes will be added promptly.

**Comment by ghajini** [comment]
Just report here issues
fuckfuckadblock uses same ubo filters syntax, nothing new

**Comment by sanGtH** [comment]
Ok,, i see, well then i will do as you suggest. Thanks for the suggestion to all.
Please close this issue.
