### ISSUE TITLE
Hindustantimes.com {Antiadblock }

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8340]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.hindustantimes.com/delhi-news/bharat-bandh-aap-alleges-arvind-kejriwal-under-house-arrest-delhi-police-deny/story-LbjXD4WmuKTtcFJNoDjJiK.html`

### Describe the issue

Antiadblock preventing site access

### Screenshot(s)

![Screenshot (28)](https://user-images.githubusercontent.com/20338483/101450565-badacb00-3950-11eb-973a-66c7107d46c1.png)

### Versions

- Browser/version: google chrome Version 87.0.4280.88 (Official Build) (64-bit)
- uBlock Origin version: 1.31.2

### Settings

uBO's default settings
-

### Notes

use indian ip if you can't reproduce

**Comment by uBlock-user** [comment]
Tested with Indian VPN, can't reproduce.

On Reddit, another user reported [this issue](https://www.reddit.com/r/uBlockOrigin/comments/k8c5jy/hindustan_times_antiadblock_help/), but he was on Edge and TP was causing the trigger.

**Comment by uBlock-user** [comment]
Try disabling Chrome's built-in adblocker/filterer.

**Comment by ghajini** [comment]
i read reddit report already before issue here....there's no such privacy protection/inbuilt blocker/filterer option in google chrome ,can you point where exactly in settings,i searched a lot?

**Comment by uBlock-user** [comment]
https://support.google.com/chrome/answer/7632919?co=GENIE.Platform%3DDesktop&hl=en

**Comment by mapx-** [comment]
@ghajini does this work ?

`hindustantimes.com##+js(nostif, stackTrace)`

**Comment by ghajini** [comment]
that setting is disabled on my side

**Comment by uBlock-user** [comment]
Seems like a Chrome issue where the `redirect-rule` filter might not be working for you.

**Comment by ghajini** [comment]
@uBlock-user ,iam updated to ubo 1.31.3b4 on opera,there also i can reproduce issue

@mapx- works on articles but when clicked on homepage icon antiadblock back...

i see this btw
```

<script>
--
  | $( document ).ready(function() {
  | function areAdsBlocked(callback) {
  | var URL = 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js';
  | fetch(URL, {
  | method: 'HEAD',
  | mode: 'no-cors'
  | })
  | .then(response => callback(false))
  | .catch(error => callback(true));
  | }
  | function checkAdBlocker() {
  | areAdsBlocked(function(isBlocked){
  | var str = '';
  | if(isBlocked){
  | var adDivID = 'id-modal-backdrop';
  | var slotDiv = document.createElement('div');
  | slotDiv.id = adDivID;
  | document.body.appendChild(slotDiv);
  |  
  | str += '<div class="addPopup-main">';
  | str += '<div class="container adflex">';
  | //str += '<div class="cross-adblocker"></div>';
  | str += '<img src="https://www.hindustantimes.com/images/app-images/2020/10/adblocker.svg" class="adblocker-circle" alt="" title="" />';
  | str += '<div class="info-cont">';
  | str += '<a href="https://www.hindustantimes.com/" title="class="adblocker-button"">';
  | str += '<img src="https://www.hindustantimes.com/images/app-images/ht2020/desktop.svg" alt="" title="" />';
  | str += '</a>';
  | str += '<h2>It looks like you are using an ad blocker!</h2>';
  | str += '<p>To continue reading you need to turnoff adblocker and refresh the page</p>';
  | str += '</div>';
  | // str += '<a href="#" class="adblocker-button">Turn Off ad Blocker</a>';
  | str += '<div class="adblocker-button">REFRESH PAGE</div>';
  | str += '</div>';
  | str += '</div>';
  |  
  | $('html').addClass("scrolloff");
  | $("#"+adDivID).addClass("modal-backdrop");
  | $("#"+adDivID).append(str);
  | ga('send', 'event', 'AdBlocker', 'Installed');
  | }else{
  | ga('send', 'event', 'AdBlocker', 'Not Installed');
  | }
  | })
  | }
  |  
  | function checkGEOLocation() {
  | var xhr = new XMLHttpRequest();
  | xhr.open('GET','https://www.hindustantimes.com/resources/img/hindustantimes_notification_logo.png', true);
  | xhr.timeout = 1000; // time in milliseconds
  | xhr.onreadystatechange = function () {
  | if (this.readyState == this.HEADERS_RECEIVED) {
  | let metaGeoHeader = xhr.getResponseHeader("meta-geo");
  | if (metaGeoHeader) {
  | let header = metaGeoHeader.split('--');
  | let country = header[0].trim();
  | if (country == "US") {
  | checkAdBlocker();
  | }
  | }
  | xhr.abort();
  | }
  | }
  |  
  | xhr.send(null);
  | }
  | checkAdBlocker();
  | //checkGEOLocation();
  | });
  |  
  | $(document).on('click','.adblocker-button', function(){
  | location.reload();
  | });
```

**Comment by mapx-** [comment]
test

`hindustantimes.com##+js(aeld, , ready)`

**Comment by mapx-** [comment]
@uBlock-user it's the same `livemint` issue

**Comment by uBlock-user** [comment]
@ghajini Opera's based on Chromium, so ofcourse it will occur.

@mapx- yep was just going to say that.

**Comment by ghajini** [comment]
this work `hindustantimes.com##+js(aeld, , ready)`

**Comment by mapx-** [comment]
> this work `hindustantimes.com##+js(aeld, , ready)`

yeah .. BUT is breaking stuff, see the video thumbnails 

https://www.hindustantimes.com/videos/india-news/kejriwal-under-house-arrest-orders-from-mha-aap-mla-slams-centre/video-hMShpIF4o6p2CTQcPL4TQN.html

**Comment by mapx-** [comment]
this exception is working but ...

`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,domain=hindustantimes.com`

**Comment by ghajini** [comment]
> 
> 
> > this work `hindustantimes.com##+js(aeld, , ready)`
> 
> yeah .. BUT is breaking stuff, see the video thumbnails
> 
> https://www.hindustantimes.com/videos/india-news/kejriwal-under-house-arrest-orders-from-mha-aap-mla-slams-centre/video-hMShpIF4o6p2CTQcPL4TQN.html

yes i was trying to report only that 
`https://www.hindustantimes.com/videos/india-news/bharat-bandh---farmers-stop-train-in-maharashtras-buldhana-several-detainedvideo/video-VnJCImv4TElNT07ZtAhWhN.html`
under other videos section

**Comment by ghajini** [comment]
Btw everything works in firefox ,what's wrong with chrome?

**Comment by uBlock-user** [comment]
try  `hindustantimes.com##+js(set, fetch, noopFunc)` and report for breakages.

A no-fetch-if scriptlet would be rather be needed if exception is the only other way then.

![Capture](https://user-images.githubusercontent.com/21290713/101455172-25dbd000-3958-11eb-82c7-d26b1ed9b760.PNG)

**Comment by ghajini** [comment]
yes give me some time b4 commit

**Comment by lain566** [comment]
@ghajini  Does this work for you?
`hindustantimes.com##+js(acis, $, adsbygoogle)`

**Comment by mapx-** [comment]
working for me

`hindustantimes.com##+js(acis, $, HEAD)`

**Comment by uBlock-user** [comment]
> hindustantimes.com##+js(acis, $, HEAD)

go with that, this issue seems to be happening when `HEAD` is used.

**Comment by ghajini** [comment]
1.
`hindustantimes.com##+js(set, fetch, noopFunc)`
video thumbnails will be blocked when using above

2.
work
```
hindustantimes.com##+js(acis, $, adsbygoogle)
hindustantimes.com##+js(acis, $, HEAD)
hindustantimes.com##+js(acis, $, fetch)
```
i see no breakage so far but i will report if found ,at least i can see the news,watch videos ,sign in-out ,see epaper 
 
3.
also can you block push notifications at `https://www.hindustantimes.com/search?q=gh` as a annoyance

**Comment by krystian3w** [comment]
> push notifications at 

firefox show only icon instead all popup, this is accepted situation, Chrome also try implement this with shaked icon without pop-up.

**Comment by ghajini** [comment]
hence i said as an _**annoyance**_

**Comment by krystian3w** [comment]
But worth for EasyList projects.

**Comment by ghajini** [comment]
Also
`www.hindustantimes.com##.m_ads_unit` for ad remnant due to generichide exception filter

**Comment by ghajini** [comment]
test link=
`https://www.hindustantimes.com/`
`https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.hindustantimes.com%2Findia-news%2Fsheena-bora-murder-indrani-wanted-to-kill-both-her-children-ex-driver-tells-court%2Fstory-DdGdNuF07QUQFjqck6wiHI.html&psig=AOvVaw07xOnDxExX6gAEpd3C67C_&ust=1611064220670000&source=images&cd=vfe&ved=0CAkQjhxqFwoTCJCYoajQpe4CFQAAAAAdAAAAABAD`

thumbnails doesn't load
![image](https://user-images.githubusercontent.com/20338483/104924609-ad8b1480-59c3-11eb-8214-917070356784.png)

**Comment by mapx-** [comment]
I cannot reproduce your issue FF / opera

**Comment by ghajini** [comment]
they have broken themselves(want to behave like mobile app/livemint.com but can't ,poor webmasters)

**Comment by ghajini** [comment]
stories not load,i can reproduce now @uBlock-user findings `hindustantimes.com##+js(ra, onclick, a[href][onclick^="getFullStory"])`

**read full story** button will remain broken

**Comment by uBlock-user** [comment]
@ghajini Want me to add that filter now ?

**Comment by ghajini** [comment]
yes sir

**Comment by ghajini** [comment]
Now stories don't load
Ubo Dev, opera browser /firefox

`https://www.hindustantimes.com`

**Comment by mapx-** [comment]
test now

**Comment by ghajini** [comment]
Works
Can we have adguard like solution ie no whitelist
