### ISSUE TITLE
filmyzilla.xyz

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8341]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://filmyzilla.xyz/files/2730/the-christmas-chronicles-2-2020-full-movies.html`

### Describe the issue

Update already existing filter as site name is changed filmyzilla.life>filmyzilla.xyz

### Versions

- Browser/version: firefox a.
- uBlock Origin version: 1.31

### Settings

uBO's default settings
-

**Comment by mapx-** [comment]
yeah, changed but no trace of popups, btoa, break etc

**Comment by ghajini** [comment]
At this url
`https://filmyzilla.xyz/download/2732/hillbilly-elegy-2020-full-movies.html`
![Screenshot_2020-12-09-00-08-34-806_org mozilla fenix](https://user-images.githubusercontent.com/20338483/101526606-da0a4480-39b2-11eb-9df5-b2f276e94810.png)
