### ISSUE TITLE
moviesdaweb.blogspot.com & isaiminiweb.online

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8342]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://moviesdaweb.blogspot.com/2020/12/download-file.html?m=1#?o=8eeb784588b578909b2e5ded96eaee6d6a76604767b9767093c761f32f719be1eb7f4c2c7e8d58305ec318a7bad9e236173e839c9e73633bbeea7995be9943d386b748ec9abb370e5cfbb6a2185f2086d60380cbc1c13a5fc50380f6c2560a0b280d017a8f239663a3ad529c2d7011b723ec7b27a12e1aa2f6cf2614705e7f55de24cc4953cce34f8325d8f92a311bcfa32f663375b753deb24ec3a8fd7cae2831d8998913bd7e85ba81a4327878cd3f9c6ddccea079de00a01c9cb6d9a91f4d8a3a6e35be04c46a7fd0eb4b4f21f764fdea0963eb9e2bd80c2fb4e03d6c1b53fe75ba57719901f19b168ba6c1bb09d675b6f5b17039195527c1ddfc60a1f5b33a1a2668b0a5fb617d598963eccdd9b70ae176034002abb9fe02df8bb54985253b7352575f54ed2f46574d1d09ef954e13c2772ced5b73e66f381f2c990b41023799c334b0cfd7e7667c90a735a74b88e77485f34a7048659c4d7cfd728700459c851ac0d1bd6ea266548579c755de009d45c8bafd3aef23f328eba29ffd44dd6872e8e23a0c7c1b5d8f9e78c5442e9c17c7dfb49e25a8498b3cae9929fc881058b47dc9df957ce79440a3049f1da0704f7813e2d6b25a2719dd6c465cc5ba844c24af13321df0eaf2a4cc6d6c4646a18e4370da0b55d7ad947c2392928fb507add9bfa94835a4da83a99073269a2fe8ad46616837810fd9ae2f61e60480f58ae15dd131b06d98442beaa30484eee0c62aff4d6811ab55060f81a929cbfd3f5748528a291a64e949fe4c60c3b04158a44e0be6b7f390b09e8fd2a101f194ffc91005b6cda1bbe042ea355557f6f46462ad80f4423323dcb48dc8d0de3e422d4c306d74199c7255b9ac346b3c6d300bdaf401f1d304d778147a3ad899e5b098c7c81a1d7130d2820469bd995f11b53957d325b3dcc353ebe7e44ca2c4b9cb24d0366061cd3b33c8e0fb193e484618cce7d28ee1afa4b5447156c7e43d2e8ec47fc40b67b64eefe6ee94743d1911b3091f2297b27e87032e854724f081178b0601185ae1568e5632858f5bf5f784c18b692392c766586655fca8848cbc6c1d23d979fa737d0c308b5f7aaa7fdb7069e53bf58c71ab821fcb2f1f5bb594a0d3a60895ae48589388e9db1d25e7ded8d8752fc8acab9c06d2ebe2774ec93c3f68e410b280e9d8b61bb1003287a6a1598ba1fa6a476e6eceecceb85762ed61d4549c461f7cd7a8a47d3d9279449620b2467329eec12141227d479f1184f32941597a4487faef5347ba5bd1c95f4291a8399332a94b4db07d930fac3e5b95c80e2c20c9c4f197d54c8e2de7`

`https://www.isaiminiweb.online/tamil-bluray-movies-mega-collection-56-movies-720p-90gb/`
### Describe the issue

1. Popup ads

2.
Clicking **download torrent** results in popup ads
### Screenshot(s)

![Screenshot_2020-12-09-00-34-26-671_org mozilla fenix](https://user-images.githubusercontent.com/20338483/101529750-ff00b680-39b6-11eb-9bc1-ab4465bc5281.png)

### Versions

- Browser/version: firefox android stable
- uBlock Origin version: 1.30

### Settings

uBO's default settings
-

**Comment by mapx-** [comment]
test

```
*$script,3p,denyallow=fastly.net|fastlylb.net|jquery.com|hwcdn.net|hcaptcha.com|recaptcha.net|cloudflare.com|cloudflare.net|google.com|googleapis.com|gstatic.com|sharethis.com|stackpathcdn.com|blogger.com|googleusercontent.com|rawgit.com|rawgitcdn.b-cdn.net|githack.com,domain=moviesdaweb.blogspot.com|isaiminiweb.online
||tamilrockers.isaiminiweb.online/ads1.js$script
```

**Comment by ghajini** [comment]
1.
`https://moviesdaweb.blogspot.com` blog removed/doesn't exist

2.
on reaching here `https://www.isaiminiweb.online`
immediately within seconds redirects to strict blocking page in current page only as if page wants ads but caught by ublock(this restricts webpage access)
![image](https://user-images.githubusercontent.com/20338483/104193854-8faf3400-5446-11eb-8f78-b73ff3416eab.png)

**Comment by ghajini** [comment]
how to prevent redirect?

**Comment by mapx-** [comment]
fixed for firefox, chrome didn't still adress an old issue with refresh

`<meta http-equiv="refresh" content="10;URL=//luvaihoo.com/afu.php?zoneid=3785595">`

**Comment by ghajini** [comment]
Is there any workaround for chrome? because if this strict block page happens ,user may fedup with why ublock do that(because site is replaced by strict block page in current tab only)

**Comment by uBlock-user** [comment]
No filter for chrome, this only be fixed with HTML filtering.
