### ISSUE TITLE
AD loading placeholders are not filtered by global filters on AMP sites

### ISSUE THREAD

**Issue by Smart123s** [uBlockOrigin/uAssets#8343]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.xda-developers.com/unofficial-lineageos-17-1-asus-rog-phone-3-nubia-red-magic-5g/amp/`

### Describe the issue

 
The "Loading AD" placeholders are visible if I use global filters, but disappear when I use site-only filters.
The same issue is present for most AMP sites.

Global Filters:
```
##div.amp-ad-alignment
##.amp-ad-in-content
```

Site-Only Filters:
```
www.xda-developers.com##div.amp-ad-alignment
www.xda-developers.com##.amp-ad-in-content
```

### Screenshot(s)

Site-Only filters

![Screenshot_2020-12-08-20-47-19-549_org mozilla firefox](https://user-images.githubusercontent.com/28480228/101534285-36f80180-3997-11eb-9397-32fbd865bb13.jpg)

Global Filters
![Screenshot_2020-12-08-20-48-02-019_org mozilla firefox](https://user-images.githubusercontent.com/28480228/101534322-411a0000-3997-11eb-818b-5fdc21323fcb.jpg)

### Versions

- Browser/version: Firefox (Android)/83.1.0
- uBlock Origin version: 1.31.0

### Settings

-

### Notes

The issue was not present on Chrome on Windows

**Comment by mapx-** [comment]
go into the settings, `Filter lists` tab, disable `Ignore generic cosmetic filters`

![image](https://user-images.githubusercontent.com/10303732/101535687-4ed08500-3999-11eb-91ec-4c195047f62b.png)

**Comment by ghajini** [comment]
@stephenhawk8054 it just matter of unchecking **ignore generic cosmetic filters**

**Comment by stephenhawk8054** [comment]
I think for the ones that look really annoyed, they can be addressed so users don't have to [enable the whole (performance-affected) generic filters just for those sites](https://github.com/uBlockOrigin/uBlock-discussions/discussions/310#discussioncomment-5306757).
