### ISSUE TITLE
https://www.gmx.com - isn't loading

### ISSUE THREAD

**Issue by Chris-Rockn** [uBlockOrigin/uAssets#8344]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://www.gmx.com/`

### Describe the issue
Hi, website `https://www.gmx.com/` isn't loading. Please see the screenshot.
 

### Screenshot(s)

https://i5.imageban.ru/out/2020/12/09/b4d957cdf57950588e6207b4f5834703.png
### Versions

- Browser/version: Chrome 74
- uBlock Origin version: 1.31.0

### Settings

-

**Comment by okiehsch** [comment]
What is your setup?

**Comment by Chris-Rockn** [comment]
Here's the backup file of my uBlock settings.
[my-ublock-backup_2020-12-09_11.45.56.txt](https://github.com/uBlockOrigin/uAssets/files/5664596/my-ublock-backup_2020-12-09_11.45.56.txt)

**Comment by okiehsch** [comment]
You are actively using "Dynamic Filtering"?
Meaning you are blocking third-party scripts by default?

**Comment by Chris-Rockn** [comment]
Not that I know of. Is there a special setting for it? 
https://i1.imageban.ru/out/2020/12/09/6783fd61e08493928add7f6093427d07.png

**Comment by okiehsch** [comment]
I can see from your screenshot that you don't.

Can you post a screenshot of your logger showing all blocked requests on `gmx.com`.
Here is a screenshot from my end.
![image](https://user-images.githubusercontent.com/16838044/101608004-81b06280-3a05-11eb-8b1e-de82d63ce678.png)

**Comment by okiehsch** [comment]
If you don't now how to filter the logger output.
https://github.com/gorhill/uBlock/wiki/The-logger#filtering-the-logger-output

**Comment by Chris-Rockn** [comment]
This? 
![2020-12-09_120654](https://user-images.githubusercontent.com/75723100/101608819-4028b300-3a17-11eb-8d7c-49fb74214562.png)

**Comment by okiehsch** [comment]
Yes. Does not help me.

I think I found your issue, though it is hard for me to find the exact filter causing it.
I can reproduce if I add `https://easylist-downloads.adblockplus.org/bitblock.txt` 
According to your backup file you have that list enabled.
if you disable that list it does the site load succesfully?

**Comment by Chris-Rockn** [comment]
Yes! Thank you so much for your help! It works now just fine. Have a good day sir!

**Comment by okiehsch** [comment]
`###onetrust-consent-sdk`
is causing the breakage. 
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
This has already been fixed: https://github.com/easylist/ruadlist/commit/2bba5912d1171f4f9a4f60db15680baabf80e60d

**Comment by okiehsch** [comment]
Oh, sorry forgot to check before I posted.
