### ISSUE TITLE
Amazon.com Track Package

### ISSUE THREAD

**Issue by leodoi3** [uBlockOrigin/uAssets#8346]
### URL(s) where the issue occurs

`https://www.amazon.com/progress-tracker/package/`

### Describe the issue

Go to your Amazon orders and click Track Package for any order. Below still shows the related sponsored items element. 

### Screenshot(s)
![image](https://user-images.githubusercontent.com/46114199/101669232-e7edb300-3a0e-11eb-97a6-dabb81f424dc.png)

### Versions

- Browser/version: FF 83.0
- uBlock Origin version: 1.31.0

### Settings

![image](https://user-images.githubusercontent.com/46114199/101669765-90037c00-3a0f-11eb-944c-0035eacf0567.png)
![image](https://user-images.githubusercontent.com/46114199/101669799-9c87d480-3a0f-11eb-8d79-9fd5e20782e7.png)

**Comment by mapx-** [comment]
You should use element picker to find some useful filter.

I clicked `track package` in some old amazon email => I get `order details` page but I get no sponsored items.

I get only:

![image](https://user-images.githubusercontent.com/10303732/102009905-e38d0700-3d3a-11eb-997b-e16ad3d10d46.png)
