### ISSUE TITLE
https://forum.release-apk.com detects AdBlocker

### ISSUE THREAD

**Issue by Chris-Rockn** [uBlockOrigin/uAssets#8347]
### URL(s) where the issue occurs
`https://forum.release-apk.com/`

### Describe the issue
Website detects adblocker 
 

### Screenshot(s)
https://i2.imageban.ru/out/2020/12/10/3f58161bc754e07ef630a4474fe6cb22.png

### Versions

- Browser/version: Chromium 74
- uBlock Origin version: 1.31.2

### Settings

-

**Comment by uBlock-user** [comment]
```
@@||pagead2.googlesyndication.com/pagead/js$script,3p,domain=forum.release-apk.com
forum.release-apk.com##div.phpbb-ads-center
```

seems to be working.., lets see if we can come up without having to create an ad-server exception.

**Comment by uBlock-user** [comment]
```
@@||pagead2.googlesyndication.com/pagead/js$script,3p,domain=forum.release-apk.com
forum.release-apk.com##div.phpbb-ads-center
```

seems to be working..

**Comment by Chris-Rockn** [comment]
> ```
> @@||pagead2.googlesyndication.com/pagead/js$script,3p,domain=forum.release-apk.com
> forum.release-apk.com##div.phpbb-ads-center
> ```
> 
> seems to be working..

And what do i do with this? Tried to add it to "My filters" section - nothing's changed for me

**Comment by Chris-Rockn** [comment]
Sorry, got it

**Comment by uBlock-user** [comment]
already added in uBlock Filters, just force update that list.

**Comment by Chris-Rockn** [comment]
Thank you

**Comment by mapx-** [comment]
maybe

```
||release-apk.com^$csp=style-src *
forum.release-apk.com##.rules
```

**Comment by uBlock-user** [comment]
Works but messes up the telegram button

**Comment by uBlock-user** [comment]
Fixed by `forum.release-apk.com##img[src="./ext/dark1/releasecord/image/telegram.png"]:style(width:15px !important;height:15px !important;padding-right:2px !important)`

**Comment by uBlock-user** [comment]
@Chris-Rockn post it here instead of opening a new issue, this continue to happen as the admin is fighting back against our fixes.

**Comment by uBlock-user** [comment]
@Chris-Rockn post it here instead of opening a new issue, this will continue to happen as the admin is fighting back against our fixes.

**Comment by Chris-Rockn** [comment]
@uBlock-user OK. Thanks a lot for your help!  But now if go into any topic there is no content showing -  https://i1.imageban.ru/out/2020/12/14/cb68288e029618d60debca51b46b7403.png

**Comment by uBlock-user** [comment]
@Chris-Rockn Avoid posting clickable links please and wrap all site links via between < and >, so they render themselves as code instead of hyperlinks.

**Comment by Chris-Rockn** [comment]
> @Chris-Rockn Avoid posting clickable links please and wrap all site links between backticks like `https://www.example.com`, so they render themselves as code instead of hyperlinks.

Gotcha. Same with screenshots links?

**Comment by uBlock-user** [comment]
Screenshots are fine.

**Comment by Chris-Rockn** [comment]
Also regarding this `forum.release-apk.com`. Now it shows adblocking detection at the very top of the page -  https://i2.imageban.ru/out/2020/12/14/6bd9e2936af38db6462ac6eb7dc58e12.png
It doesn't effect the forum browsing experience but for the sake of eyes pleasing is it possible to block that one element on main page only? Because if I block it globally like this `forum.release-apk.com##.bg2.has-profile.post` then it blocks topics content. 
Is there such an exception as "main page only" or something like that? Tried to google it but couldn't find anything useful.
I'd use that rule in "My filters" section. Thanks.

**Comment by uBlock-user** [comment]
Can't reproduce, force update uBlock Filters.

**Comment by Chris-Rockn** [comment]
Hm, weird. I did update the filters - still nothing. Could it be the browser (Chromium 86)?  Or should i try to reinstall uBlock? I'll try the latter.

**Comment by Chris-Rockn** [comment]
> I'll try the latter.

Didn't help. Oh well, lets leave it at that. But please tell me if its possible to apply this rule specifically to the main page only?
`forum.release-apk.com##.bg2.has-profile.post`

**Comment by mapx-** [comment]
try

`forum.release-apk.com##.bg2.has-profile.post:has-text(/adblock/i)`

**Comment by Chris-Rockn** [comment]
> try
> 
> `forum.release-apk.com##.bg2.has-profile.post:has-text(/adblock/i)`
Thanks a lot! It worked )

**Comment by mapx-** [comment]
I'll add it to the annoyances list

**Comment by Chris-Rockn** [comment]
> I'll add it to the annoyances list. 

You know, I just thought about this - the topic might have something about adblocking that is different from adblocking detecting. This particular rule will probably block anything with "adblock" in it.

**Comment by uBlock-user** [comment]
The question should be why is `forum.release-apk.com##.bg2:not(div[id][class$="bg2"])` not working for you ?

**Comment by Chris-Rockn** [comment]
> The question should be why is `forum.release-apk.com##.bg2:not(div[id][class$="bg2"])` not working for you ?

I agree. I don't think its the browser though - its not that old. But I guess I'll try a different one to see if the problem persists.

**Comment by Chris-Rockn** [comment]
@uBlock-user I went to the uBlock filters section and here's what I saw - https://i1.imageban.ru/out/2020/12/14/dca768643eebfb6485f83b6d54874bb8.png
That particular rule is red underlined. So that's why I guess it doesn't work for me - uBlock doesn't like it. But how come it works for you? I don't get it,

**Comment by uBlock-user** [comment]
@Chris-Rockn It shouldn't be, what version was this on ?

**Comment by Chris-Rockn** [comment]
@uBlock-user I'm on 1.31.2

**Comment by uBlock-user** [comment]
![Capture](https://user-images.githubusercontent.com/21290713/102088290-bcb8f880-3e40-11eb-96e2-dd8edec52480.PNG)

@gorhill, any idea why uBlock on stable build 1.31.* sees `:not()` as invalid ?

**Comment by gorhill** [comment]
Can put here the filter text so that I can copy & paste?

**Comment by uBlock-user** [comment]
`forum.release-apk.com##.bg2:not(div[id][class$="bg2"])`

**Comment by gorhill** [comment]
The browser does not consider this to be a valid selector, you can try it in any dev console:

> document.querySelector('.bg2:not(div[id][class$="bg2"])');
> Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '.bg2:not(div[id][class$="bg2"])' is not a valid selector.

It works if you split into multiple `:not`:

> document.querySelector('.bg2:not(div):not([class$="bg2"]):not([id])');

**Comment by uBlock-user** [comment]
how come this does not happen on the dev build of uBO ?

**Comment by gorhill** [comment]
This happens on dev build of uBO, I just did test on it.

**Comment by uBlock-user** [comment]
firefox 83?

**Comment by gwarser** [comment]
Implemented in Fx 84 https://bugzilla.mozilla.org/show_bug.cgi?id=933562

**Comment by gorhill** [comment]
> Some dummy procedural filter inside `:not()` will make it work.

But this will change the semantic of the filter from _"does match..."_ to _"contains an element containing..."_.

**Comment by uBlock-user** [comment]
Unfortunately `'.bg2:not(div):not([class$="bg2"]):not([id])` doesn't work as a replacement for `.bg2:not(div[id][class$="bg2"])`(matches `0` as per picker) on the site, so removed.
