### ISSUE TITLE
kod.rabatowy.pl ($popunder works in Opera but not in Firefox)

### ISSUE THREAD

**Issue by keczuppp** [uBlockOrigin/uAssets#8348]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://kod.rabatowy.pl/benevento`

### Describe the issue
- visit the url and click a green button labeled "Pokaż kod rabatowy"
- filter `kod.rabatowy.pl$popunder` works in Opera but not in Firefox
- same filter works in Firefox just fine for other similiar websites:
`$popunder,domain=rabatio.com|alerabat.com|salesandshopping.pl|kodyrabatowe.olx.pl`
https://github.com/MajkiIT/polish-ads-filter/blob/7334eec147caed2434f5bdf4d745fcc5f817c2e0/polish-adblock-filters/adblock_ublock.txt#L390
- orginal issue: https://github.com/MajkiIT/polish-ads-filter/issues/18048 + https://github.com/uBlockOrigin/uAssets/issues/8332#issuecomment-739552506
- so for `kod.rabatowy.pl` in Firefox we are going to add also an alternative filter: 
```
!#if env_firefox
kod.rabatowy.pl##+js(nostif, gotoUrl, 300)
!#endif
```
 as well, but it is not a full replacament as it will only prevent the orginal tab from redirecting to new/ads url instead of closing it completely
- I'm not sure whether it is just a filter issue or a uBO bug, in case it turns out to be a uBO bug, the issue should be transferred to appropriate issue tracker https://github.com/uBlockOrigin/uBlock-issues/issues

 

### Screenshot(s)

![222222](https://user-images.githubusercontent.com/74409207/101764764-bcd39400-3ae0-11eb-936f-59220b21f388.png)

### Versions

- Browser/version: [Firefox 83]
- uBlock Origin version: [1.31.3b6]

### Settings

-

### Notes

@bug-rules

**Comment by keczuppp** [comment]
- guys wth? Not even anybody replied whether he can reproduce or not...
- also here ignored as well https://github.com/uBlockOrigin/uAssets/issues/8261#issuecomment-742901051
- hence closing it and moving to uBO tracker

**Comment by okiehsch** [comment]
So you are annoyed that nobody responds to this thread within 15 hours?
Wow.
For the record I can't reproduce.

**Comment by okiehsch** [comment]
Actually I can reproduce, I forgot to disable your filter `kod.rabatowy.pl##+js(nostif, gotoUrl, 300)`

Looks like a bug to me.

**Comment by keczuppp** [comment]
> okiehsch : https://github.com/uBlockOrigin/uAssets/issues/8348#issuecomment-742919785 : So you are annoyed that nobody responds to this thread within 15 hours?
> Wow.

- not exactly, either you should buy better glasses, or go to math tutoring, or you are just intentionally manipluating, bacause in your reply about "15 hours" followed by "Wow." you somehow ommited a part of my comment in which I said that another reason was also, that nobody responded previoulsly in the another issue (for 3 days), hence I realised I'm clearly being ignored here and should move to somewhere else. ("Wow.")
- I hope you will not get offended now just because in my reply I mentioned about glasses or math, I had no intention to offend you, nor I am angry, just wanted to clarify certain points clearly and just retor to your amazing comment follwoed by "Wow."

> okiehsch : Looks like a bug to me.

Yep, seems so.

**Comment by okiehsch** [comment]
>  hope you will not get offended now just because in my reply I mentioned about glasses or math

I am not offended.
I did not mention the other issue because it has nothing to do with this one.
If you look through the thousands of opened  issues do you see a patern of us taking "forever" to respond?
Complaining and closing an issue because nobody responds within 14 hours is silly in my opinion.

Nobody is deliberately ignoring you, why should we.

**Comment by keczuppp** [comment]
> I did not mention the other issue because it has nothing to do with this one.
> Complaining and closing an issue because nobody responds within 15 hours is silly in my opinion.

- you were trying to prove that my discouragement from waiting was only because of "15 hours" spent in this issue, where the truth is it was also because of 3 days spent in the previous issue, it accumulated together as I was still awaiting response in the previous issue at the same time
- if it makes you feel better you can stick to your opinion that it was "15 hours" only...

> If you look through the thousands of opened issues do you see a patern of us taking "forever" to respond?

- you just have been talking about the 2 issues being unrelated (where I've proven anyway they were indeed related in a case of the accumulated time spent) and now yourself are talking about unrelated issues...
- my discouragement from waiting was only because of the 2 issues in which I was involved, I nowhere was mentioning about other issues as of the cause, if you're asking me about the whole opinion, I say `uAssets` and `AdGuard` are two fastest filters related issue trackers on Earth, they usually reply and fix issues very fast, and I was surprised by lack of such fast response in case of the 2 issues we are talking about, and nobody still answered why there was no response in the `o2.pl` issue for 3 days...

> Nobody is deliberately ignoring you, why should we.

- don't ask me about it, I'm curious as well, but then why in the `o2.pl` issue nobody reopened the issue when I asked for it for 3 days...

**Comment by okiehsch** [comment]
> did you guys even received notifications from github about my reopen comments / request in the o2.pl ?

Pretty sure we did, 
I can only speak for myself. I get notified about every comment, opened and closed issue in this and a few other repos.
That's a lot of notifications. 
The one in the o2.pl thread is not the first won't be the last I overlooked or forgot about.
I replied in this thread as soon as I checked the notification today, so I am certainly not deliberately ignoring you or anybody else.

**Comment by uBlock-user** [comment]
> hmm did you guys even received notifications from github about my reopen comments / request in the o2.pl ? 

I recieved today's one, not the one 3 days ago. 

Instead of claiming that we're purposefully ignoring, how about you just ping someone from the team if something like this happens ? That way, it doesn't get "ignored". Just because we're faster for the most time, doesn't mean we will always, stuff like this can happen anytime, we're volunteers after all, pinging makes sure that the issue doesn't get ignored for days.

**Comment by keczuppp** [comment]
> okiehsch : https://github.com/uBlockOrigin/uAssets/issues/8348#issuecomment-743184148

- I see..., but it is just weird, because it's almost impossible that several devs missed the same comments/notifications in the same thread at the same time what is the chance...

> uBlock-user : https://github.com/uBlockOrigin/uAssets/issues/8348#issuecomment-743193354 : I recieved today's one, not the one 3 days ago.

- weird

> uBlock-user : https://github.com/uBlockOrigin/uAssets/issues/8348#issuecomment-743193354 :  Instead of claiming that we're purposefully ignoring
- I nowhere was claiming anybody ignoring me purposefully, I was assuming that only in case you all received notifications from github and still not responded in the thread, but as seen there seem to be some problems on github with notifications, because like I already said it's almost impossible that several devs missed the same comments/notifications in the same thread at the same time...

> uBlock-user : https://github.com/uBlockOrigin/uAssets/issues/8348#issuecomment-743193354 : how about you just ping someone from the team if something like this happens ? That way, it doesn't get "ignored". Just because we're faster for the most time, doesn't mean we will always, stuff like this can happen anytime, we're volunteers after all, pinging makes sure that the issue doesn't get ignored for days.

- you must be kidding... wait, I already heard the same story about pinging devs....I got it, here it is: one of devs (ZaphodBeebblebrox) said to ping devs if needed, and then this is the "nice" reply of another dev after he got pinged: https://github.com/uBlockOrigin/uAssets/issues/3975#issuecomment-436276119 , and then you are another dev who saying about pinging devs, no thanks...unless you want me to not stick to what he said, and to stick to what you said instead, but now I don't know who to listen to...you guys definately are not one voice of  collective Borg
- what is more funny, uBlock-user, your argumentation **to ping** devs is the same like maps-'s argumentation **to not ping** devs

**Comment by uBlock-user** [comment]
Now you're comparing to yourself to kulfoon ? You have been advised what to do, this back and forth arguement only adds further noise here.
