### ISSUE TITLE
newyorker.com

### ISSUE THREAD

**Issue by llacb47** [uBlockOrigin/uAssets#8350]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.newyorker.com/news/news-desk/dianne-feinsteins-missteps-raise-a-painful-age-question-among-senate-democrats`

### Describe the issue

New yorker anti-adblock

### Versions

n/a

### Settings

n/a

### Notes

```
newyorker.com##.paywall-registration-gate
newyorker.com##+js(set, paywallGateway.truncateContent, noopFunc)
```

**Comment by uBlock-user** [comment]
> newyorker.com##+js(set, paywallGateway.truncateContent, noopFunc)

That will fix the paywall too.

**Comment by llacb47** [comment]
> > newyorker.com##+js(set, paywallGateway.truncateContent, noopFunc)

There is still a modal

![image](https://user-images.githubusercontent.com/16567977/101808128-efcb5700-3ae3-11eb-8bbd-71996fc9face.png)
