### ISSUE TITLE
"Sign in to medium.com with Google"

### ISSUE THREAD

**Issue by makeworld-the-better-one** [uBlockOrigin/uAssets#8351]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://medium.com/` , and any of its article pages.

### Describe the issue

 

A "Sign into medium.com with Google" popup appears on the right side, displaying the logged-in Google account(s) I have. This makes a connection to `accounts.google.com`, tracking the articles I read. The same popup is blocked on a non-Medium page like [this one](https://venturebeat.com/2020/06/03/google-faces-5-billion-lawsuit-for-tracking-users-in-incognito-mode/), thanks to the `||google.com^*/log?` filter from Easy Privacy.

### Versions

- Browser/version: Firefox 83.0
- uBlock Origin version: v1.31.0

### Notes

There are three `accounts.google.com` requests made when visiting Medium:
- GET `https://accounts.google.com/gsi/client`
- GET `https://accounts.google.com/gsi/status?<redacted>`
- GET `https://accounts.google.com/gsi/iframe/select?<redacted>`

---

Let me know if this should be sent to EasyList, but the README of the repo mentions that issues with popups are accepted, and that fixes for "high-traffic sites" should be added. I believe Medium qualifies.

**Comment by yourduskquibbles** [comment]
You can test `||accounts.google.com/gsi/*$xhr,script,3p` but not sure if this belongs in `uAssets`, probably better in `EasyPrivacy` or personal block list since some people may want the ability to sign-in through Google

**Comment by makeworld-the-better-one** [comment]
I can confirm that works, thanks. I'd appreciate if someone could ask for that to be added to EasyPrivacy as I don't have a forum account. And yeah it makes sense that can't be added to uAssets, I forgot some people would want to use that.

**Comment by krystian3w** [comment]
try here:

https://github.com/easylist/easylist/issues/new

Maybe added in Febuary 2021.

**Comment by makeworld-the-better-one** [comment]
@krystian3w Thank you, I didn't realize they have a GitHub repo.

I have opened easylist/easylist#6661 describing this issue.
