### ISSUE TITLE
khatrimazafull.fun { Antiadblock }

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8354]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.  > 

**since nano quickreports(`https://github.com/NanoMeow/QuickReports/issues/3758`) is archived ,i will prefer to open new issue here instead of referencing from there** 
do close if violates guidelines here

- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://khatrimazafull.fun/durgamati-the-myth-2020-hindi-movie-720p-hdrip-x264-1-2gb/`

### Describe the issue
Antiadblock
popup ads

### Screenshot(s)

![image](https://user-images.githubusercontent.com/20338483/101877830-a0a12700-3bb4-11eb-85f4-27b1c6249c6e.png)

### Versions

- Browser/version: firefox ,opera stable
- uBlock Origin version: 1.31

### Settings

uBO's default settings
-

### Notes

Any Regex modification required to catch these requests? (because regex in ublock filters doesn't catch these)

1.
`https://son-in-lawmorbid.com/17/65/64/17656449924a9384cdc17bfdb91e06d3.js`
`https://son-in-lawmorbid.com/16/99/44/169944b5f7f74692610d593b35f05890.js`

2.
`https://son-in-lawmorbid.com/ba/68/c9/ba68c9773c04d7dfd1076913f6491ca4.js` 
got from `https://fullmaza.best/2020/12/the-queens-gambit-s01-hindi-dual-audio-hdrip-720p-complete/`

3.
also these
`https://janitoraccrue.com/5c/7a/2b/5c7a2be964ddfccff060efb0450b95dd.js`
`https://janitoraccrue.com/b4/32/c3/b432c3061a4648eca687d56d96459777.js`

(for this 3rd case i disabled ublock filters to know effectiveness of regex filter)

got from
`https://firefiles.org/5hnio7j5mrn7o.html`

**Comment by ghajini** [comment]
@mapx- @Yuki2718 pinging regarding regex filters modification

**Comment by Yuki2718** [comment]
@ghajini fixed, it was because the domain included `-` missed in the regex.
