### ISSUE TITLE
sourceforge.net

### ISSUE THREAD

**Issue by AroKol78** [uBlockOrigin/uAssets#8359]
applies to all projects - cannot see the list - example:
```
https://sourceforge.net/projects/pioneerspacesim/
https://sourceforge.net/projects/ufoai/
```
![sfufoai](https://user-images.githubusercontent.com/70756447/101913856-dac5f500-3bc3-11eb-967d-d005b2d33f9b.PNG)
Basilisk v2020.11.25 - uBlock-for-firefox-legacy-1.16.4.26
![db1fix](https://user-images.githubusercontent.com/70756447/99152904-1e047500-26a5-11eb-81aa-d0561833c5ed.PNG)

**Comment by uBlock-user** [comment]
fixes with `sourceforge.net##.v_300_large.visibility_rules`

**Comment by AroKol78** [comment]
@uBlock-user
**bad fix** ![sf02bug](https://user-images.githubusercontent.com/70756447/101982752-48caf480-3c76-11eb-9328-cd8c2b76167b.PNG)

**if disabled "uBlock filters"**
![sf03ok](https://user-images.githubusercontent.com/70756447/101982797-9a737f00-3c76-11eb-8bb2-13efe783340b.PNG)

**Comment by uBlock-user** [comment]
@AroKol78 fixed, force update in a while.
