### ISSUE TITLE
anti-adblock on dejure.org

### ISSUE THREAD

**Issue by zarillo2000** [uBlockOrigin/uAssets#836]
### URL(s) where the issue occurs

dejure.org

### Describe the issue

When I open the website there is a annoying screen that I have to click away asking me to disable my adblocker. 

### Versions

- Browser/version: FF 57
- uBlock Origin version: 1.14.18

### Settings

default

**Comment by mapx-** [comment]
`dejure.org##script:inject(abort-on-property-read.js, a_allowed)
`
or

`@@||dejure.org/jcg/banner-ad.js`

**Comment by gorhill** [comment]
Suggested solution works fine.

Closing, as these filters won't be added to uBO's filters because it's just an annoyance which can be dismissed and the dismissal is remembered.
