### ISSUE TITLE
gamesarkadium.bild.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#8360]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x]  I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x]  I tried to reproduce the issue when...
    - [x]  uBlock Origin is the only extension
    - [x]  uBlock Origin with default lists/settings
    - [x]  using a new, unmodified browser profile
- [x]  I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://gamesarkadium.bild.de/games/sweet-shuffle/`

### Describe the issue

Anti Adblock 

### Screenshot(s)

![Unbenannt](https://user-images.githubusercontent.com/48647394/101962652-00c3b780-3c0d-11eb-96af-95549993dc7c.PNG)

### Versions

- Browser/version: Firefox developer
- uBlock Origin version: v1.31.0

### Settings

default + uBlock Annoyances

**Comment by JobcenterTycoon** [comment]
Domain changed to `spiele.bild.de`. Example `https://spiele.bild.de/solitaer/`

**Comment by JobcenterTycoon** [comment]
Ads are back `https://spiele.bild.de/sudoku/` (gets blank or 20 second ad)

**Comment by JobcenterTycoon** [comment]
Ok i see its enough to block `servedby.adbility-media.com`

**Comment by okiehsch** [comment]
Yes, simply add
`||servedby.adbility-media.com^$3p`

**Comment by Yuki2718** [comment]
Can these safely be blocked?
```
​https://spiele.bild.de/js/track.js
https://spiele.bild.de/games/bilddenew_Sudoku4/js/track.js?cb=3.0.8.930
```

**Comment by JobcenterTycoon** [comment]
No both breaks the page
