### ISSUE TITLE
https://tracking.shopback.com/client/v1/events

### ISSUE THREAD

**Issue by c2xusnpq6** [uBlockOrigin/uAssets#8361]
```
https://www.shopback.com.tw/nordvpn --> https://tracking.shopback.com/client/v1/events
```

**Comment by uBlock-user** [comment]
Fill the template completely and demonstrate the issue.

**Comment by c2xusnpq6** [comment]
![圖片](https://user-images.githubusercontent.com/75058881/102000627-576fe500-3d24-11eb-9cd0-6d26169506a9.png)
![圖片](https://user-images.githubusercontent.com/75058881/102000633-65be0100-3d24-11eb-84e8-efc030c389f6.png)
tracker

**Comment by c2xusnpq6** [comment]
https://github.com/FutaGuard/FutaFilter/issues/23

**Comment by Yuki2718** [comment]
@ryanbr  Having read the arguments in FutaFilter, I suspect the change should be reverted. The OP's request was rejected by the maintainer for potential problem, and OP admitted he didn't check normal operation of the site. But the maintainer and contributor's argument is not so strong, basically saying shopback is a reward site where user engage in ads and in turn get cash back, and they prohibit use of adblocker (written in image of `https://www.shopback.com.tw/how-it-works`) so they don't want to risk their user for potential problem - and as a result of being added to EP they whitelisted the request. Nevertheless they have a point, I think. Anyway what we received here is a low-quality report, ignoring template and I can't even reproduce the request.

**Comment by tasi788** [comment]
As far as I am concerned, the reason why the site is not good enough to be included in the list is simple. According the site says `https://www.shopback.com.tw/how-it-works`

```
3. Can I have adBlock/uBlock installed and still earn Cashback? 
Please note the use of adblock/uBlock software may affect Cashback tracking. If installed, please disable your ad blocking software entirely during your shopping sessions.
```

The website has already clarify that to use their services **DO NOT** turn on adblock or related blocks, besides I've never seen or hear any report says `shopback` inject their tracking code to other site.

The above only represents my personal views.

**Comment by Yuki2718** [comment]
@tasi788 I see, it's not straightforward to be honest. If user follow the instruction and disabled blocker, whatever filters on the list is irrelevant. If he didn't, he should accept the risk. And it's not easy to check unless you actually engage in the service, which involves money and thus your real identity or finance.

**Comment by bestpika** [comment]
@Yuki2718 The problem is that this tracking is for users who have applied for an account and who have agreed to the user agreement for the service at the time they apply for the account.
When the other party has already agreed to the user agreement, why do we need to do the job?

**Comment by bestpika** [comment]
My principle is that if this rule affects the functionality of the site itself, then it should not be blocked or should be added to the whitelist.

**Comment by Yuki2718** [comment]
@bestpika Thank you for your comment. In my understanding uBlock team also don't want to actively block non-third-party tracker which may affect site functionality, and thus we just pinged @ryanbr , a EasyPrivacy maintainer, for him to determine. Personally I'm on your side as [commented](https://github.com/uBlockOrigin/uAssets/issues/8361#issuecomment-745180756) above, but EP has their own criteria and we unblock only if an actual problem occurred.
