### ISSUE TITLE
adf.ly malicious links causing UBlockOrigin crash

### ISSUE THREAD

**Issue by sanGtH** [uBlockOrigin/uAssets#8364]
### URL(s) where the issue occurs

`https://www14.eloypatrick.pro/pushredirect/?network=3&site=adfly&ppi=2220594&pci=6702255727&t=1607793008&dest=https%3A%2F%2Fonleech.me%2Fshort%3Fomg%3DiZTCQ5sT5sqSUlGIBRgBmGIWHqh7Wcn4evd1FcYZusNG3RX7Lnzp1M7I7Dz9m_jXKC5uKbnaaA35bFfpTAvo_VKuCNHMJFKC7koCjqHpLgxeRNHwROkDwIA-jaTPTyQW`

### Describe the issue
The above link (which is a adf.ly link) is causing the extensions to crash
How to get to the above link?
1. go to onleech.me.
2. generate a link for your file.
3. The download link takes you to one of exe.io link (in my case `https://exe.app/Kf3Yvsop`  ).
    Here you solve the captcha and then it redirects to one malicious adfl.ly link which casues the crash when there are
    4-5 tabs open in Chrome.
4. This link is detected as malicious by AV.

### Versions

- Browser/version: [Chrome 87.x] 
- uBlock Origin version: [v1.31.2]

### Settings

All default settings.

**Comment by uBlock-user** [comment]
The link you posted doesn't crash and leads to `https://pngit.live/Dy6y8o`

**Comment by sanGtH** [comment]
Did you have  4-5 tabs open in chrome?

**Comment by uBlock-user** [comment]
No, also crashes are browser issues and are to reported to respective browser vendors.

**Comment by ghajini** [comment]
Forced notifications
https://github.com/uBlockOrigin/uAssets/issues/5890
