### ISSUE TITLE
sdk.privacy-center.org not blocked

### ISSUE THREAD

**Issue by Axel57000** [uBlockOrigin/uAssets#8365]
### URL(s) where the issue occurs

For example : https://www.jeuxvideo.com/ or other sites that use this query

### Describe the issue

I noticed that the domain "sdk.privacy-center.org" is not blocked whereas it is an GDPR cookie related domain. This domain is blocked by the extension (or filter) "I don't care about cookies".
This domain should be added to EasyList Cookie list or Fanboy's Annoyance list.

### Screenshot(s)

Log uBO:  ![Log_JVC](https://user-images.githubusercontent.com/31167833/101991101-b2fd8c80-3caa-11eb-8cec-2a4a932ec78c.png)

Log Firefox: 
![Log_JVC_Firefox](https://user-images.githubusercontent.com/31167833/101991149-20a9b880-3cab-11eb-807d-34e2fa8ff9a4.png)

### Versions

- Browser/version: Firefox 83.0 x64 on Windows 10 Pro 20H2 19042.685
- uBlock Origin version: 1.31.3b12

### Settings

All integrated uBlock lists + regional lists from France, Russia and Iran

### Notes

Solution : use I don't care about cookies extension or subscribe to the list, or block this request with dynamic filtering.

**Comment by uBlock-user** [comment]
> it is an GDPR cookie related domain

yes and whereever GDPR modal is used, site became broken, so it was removed from EasyPrivacy. You can block it yourself if you want.

**Comment by krystian3w** [comment]
This can break page.
