### ISSUE TITLE
coches.net "unexpected error"

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#8366]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [❌] uBlock Origin is the only extension
    - [✔] uBlock Origin with default lists/settings
    - [❌] using a new, unmodified browser profile
    - [✔] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.coches.net/`

### Describe the issue

an error appears every time the main page is visited 🤔

### Screenshot(s)

![Captura](https://user-images.githubusercontent.com/33556647/101999300-ca08a280-3cdb-11eb-8d36-5bef89e0c59a.PNG)

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.31.2]

### Settings

- uBlock filters – Annoyances
- spa, por: AdGuard Spanish/Portuguese
- spa: EasyList Spanish

**Comment by okiehsch** [comment]
Does
`@@||tags.tiqcdn.com/utag/*/coches.net/prod/utag.js$script,domain=coches.net`
work for you?

**Comment by PIZZA90** [comment]
still not working

**Comment by mapx-** [comment]
re-tested using even a spanish ip => all fine on my end in chrome

**Comment by PIZZA90** [comment]
test here: `https://motos.coches.net/`

**Comment by PIZZA90** [comment]
`https://tags.tiqcdn.com/utag/schibsted/motos.net/prod/utag.js`

**Comment by mapx-** [comment]
test again

**Comment by PIZZA90** [comment]
all ok
