### ISSUE TITLE
voe.sx

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8368]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://voe.sx/d55a7584jjdm`

### Describe the issue

Popup ads

### Versions

- Browser/version: firefox A. Stable
- uBlock Origin version: 1.31

### Settings

 uBO's default settings
-

**Comment by ghajini** [comment]
Does not work ,still popup in all browsers 
`https://voe.sx/d55a7584jjdm`

**Comment by RandyJackson59** [comment]
Hi sorry i'm not sure why this is closed but i just want to confirm i am having the same issue with popup ads from voe.sx

**Comment by gwarser** [comment]
Purge and update uBlock filters.

**Comment by uBlock-user** [comment]
I get a popup from the page url itself opening in a new tab, try  -- `voe.sx##+js(aopw, open)`

**Comment by RandyJackson59** [comment]
Purging and updating uBlock Filters unfortunately didn't do anything, but after adding `voe.sx##+js(aopw, open)` to My Filters, the popups are indeed gone.
Thank you very much guys, the problem is solved (for now?)

**Comment by MakFred86** [comment]
https://voe.sx/2xk9tk38gs4s 
- Video no longer starts when UBlock is enabled
- Download button does not work anymore

**Comment by ghajini** [comment]
`https://voe.sx/e/vzfdaknmqsg0`

popup ads

**Comment by MakFred86** [comment]
With the fix, the download/embed button does not seem to work again: https://voe.sx/vzfdaknmqsg0

**Comment by ghajini** [comment]
`https://voe.sx/o1yb90pwyooi`

the download/embed button does not seem to work

**Comment by MakFred86** [comment]
The download/embed button doesn't work again, yesterday's fix made the buttons unclickable...
https://github.com/uBlockOrigin/uAssets/commit/6465eaf83c268fd722099f8927e3b78fbd43ea39

https://voe.sx/o1yb90pwyooi

**Comment by ghajini** [comment]
Don't type clickable links
Test 
```
voe.sx#@#+js(aeld, , _0x)
voe.sx##+js(aopw, targets)
```

**Comment by ghajini** [comment]
Popup ads again ,firefox A

`https://voe.sx/q5p6qh5v9vo0`
![Screenshot_2021-02-02-10-43-34-639_org mozilla fenix](https://user-images.githubusercontent.com/20338483/106555523-bf33f680-6543-11eb-803a-9f91449b47d4.png)

**Comment by okiehsch** [comment]
Does 
`voe.sx##+js(aopr, document.head.appendChild)`
work for you?

**Comment by ghajini** [comment]
> Does
> `voe.sx##+js(aopr, document.head.appendChild)`
> work for you?

Yes it will work👍

**Comment by ghajini** [comment]
Popups again

**Comment by uBlock-user** [comment]
`||voe.sx^$csp=sandbox allow-forms allow-same-origin allow-scripts allow-modals allow-orientation-lock allow-pointer-lock allow-presentation allow-top-navigation`

**Comment by ghajini** [comment]
With your filter,
Clicking download results in
![IMG_20210204_140617](https://user-images.githubusercontent.com/20338483/106866317-50e16680-66f2-11eb-8f7e-c8b6fd2d21fb.jpg)

**Comment by ghajini** [comment]
`https://voe.sx/q5p6qh5v9vo0`

1. opera -
popups

2. firefox-
download doesn't work

**Comment by mapx-** [comment]
yeah, they already fighted back

**Comment by ghajini** [comment]
yes few hours back everything good on my usual firefox A ,then checked back they literally checking everything here

**Comment by ghajini** [comment]
They reverted again.....they are changing frequently

**Comment by Esokrates** [comment]
Yep, still an issue, see https://github.com/uBlockOrigin/uAssets/issues/8536

**Comment by ghajini** [comment]
Ads back

**Comment by ghajini** [comment]
May be NSFW
`https://voe.sx/3forx77x7xk8`

popups

downloads are also blocked

**Comment by JobcenterTycoon** [comment]
popups are back

**Comment by ghajini** [comment]
@uBlock-user download doesn't work
`https://voe.sx/7hehhxk5aoto`

**Comment by ghajini** [comment]
still download request is closed by easylist filter
![Screenshot_2021-03-30-00-36-42-078_org mozilla fenix](https://user-images.githubusercontent.com/20338483/112886826-11326c00-90f0-11eb-845b-59bc67ab5262.png)

Need to understand how to defuse this piece of code which determines whether you are served with ad or download page from same url
```
function download_file() {
        let code = '7hehhxk5aoto';
        let quality = 'n';
        let hash = '1419585-103-20-1617044969-8feb4071e1447e77d1d4cbd1c994e8fb';
        var ca760df91aa72f469badd2dbb2fa1dd3=['4199cjbmuL','preconnect','click','length','167235hIMyJR','createElement','#ffffff','fromCharCode','getTime','186NozUNB','17401nKHECI','exec','head','getElementsByTagName','&hash=','41576ShPHGs','exp','http://e61c8ad1ad.xyz','290866rCrJYX','open','atob','name','link','7HQSLaS','getAttribute','location','content','&mode=','https://voe.sx/dl?op=download_orig&id=break#btoa','1JKpwzr','&domain=comfortlessweave.com','Unfortunately,\x20your\x20browser\x20blocks\x20the\x20download\x20function,\x20e.g.\x20by\x20an\x20adblocker.','replaceChild','1336KmstvB','https://voe.sx/dl?op=download_orig&key=summer&id=','href','104791MdVGHs','msapplication-TileColor','body','link.href','addEventListener'];var Ca760df91aa72f469badd2dbb2fa1dd3=function(cA760df91aa72f469badd2dbb2fa1dd3,CA760df91aa72f469badd2dbb2fa1dd3){cA760df91aa72f469badd2dbb2fa1dd3=cA760df91aa72f469badd2dbb2fa1dd3-0x1e0;var ca760Df91aa72f469badd2dbb2fa1dd3=ca760df91aa72f469badd2dbb2fa1dd3[cA760df91aa72f469badd2dbb2fa1dd3];return ca760Df91aa72f469badd2dbb2fa1dd3;};var ca760dF91aa72f469badd2dbb2fa1dd3=Ca760df91aa72f469badd2dbb2fa1dd3;(function(CA760df91aa72f469badd2dbb2fa1dd3,ca760Df91aa72f469badd2dbb2fa1dd3){var CA760Df91aa72f469badd2dbb2fa1dd3=Ca760df91aa72f469badd2dbb2fa1dd3;while(!![]){try{var Ca760Df91aa72f469badd2dbb2fa1dd3=parseInt(CA760Df91aa72f469badd2dbb2fa1dd3(0x200))+parseInt(CA760Df91aa72f469badd2dbb2fa1dd3(0x1e1))*parseInt(CA760Df91aa72f469badd2dbb2fa1dd3(0x1ee))+-parseInt(CA760Df91aa72f469badd2dbb2fa1dd3(0x204))+parseInt(CA760Df91aa72f469badd2dbb2fa1dd3(0x1fb))*parseInt(CA760Df91aa72f469badd2dbb2fa1dd3(0x1f4))+parseInt(CA760Df91aa72f469badd2dbb2fa1dd3(0x1e6))+parseInt(CA760Df91aa72f469badd2dbb2fa1dd3(0x1f8))*-parseInt(CA760Df91aa72f469badd2dbb2fa1dd3(0x1e0))+parseInt(CA760Df91aa72f469badd2dbb2fa1dd3(0x1e9));if(Ca760Df91aa72f469badd2dbb2fa1dd3===ca760Df91aa72f469badd2dbb2fa1dd3)break;else CA760df91aa72f469badd2dbb2fa1dd3['push'](CA760df91aa72f469badd2dbb2fa1dd3['shift']());}catch(cA760Df91aa72f469badd2dbb2fa1dd3){CA760df91aa72f469badd2dbb2fa1dd3['push'](CA760df91aa72f469badd2dbb2fa1dd3['shift']());}}}(ca760df91aa72f469badd2dbb2fa1dd3,0x24034));try{function gone(){}var _0x16d=window['btoa'](String['fromCharCode'](0x68,0x74,0x74,0x70,0x73,0x3a,0x2f,0x2f,0x76,0x6f,0x65,0x2e,0x73,0x78,0x2f,0x64,0x6c,0x3f,0x6f,0x70,0x3d,0x64,0x6f,0x77,0x6e,0x6c,0x6f,0x61,0x64,0x5f,0x6f,0x72,0x69,0x67,0x26,0x69,0x64,0x3d,0x62,0x72,0x65,0x61,0x6b,0x23,0x62,0x74,0x6f,0x61));if(window[ca760dF91aa72f469badd2dbb2fa1dd3(0x1eb)](_0x16d)===ca760dF91aa72f469badd2dbb2fa1dd3(0x1f3)){var URL=ca760dF91aa72f469badd2dbb2fa1dd3(0x1f9),base=window[ca760dF91aa72f469badd2dbb2fa1dd3(0x1ea)]('https://comfortlessweave.com/bcbmixj4p3?download=7417876c302ab06a36929e8&pub_monetizer=5690c2107417876c302ab06a36929e81&c_id=5690c2107417876c302ab06a36929e81&ad_code=5690c2107417876c302ab06a36929e81&key=5690c2107417876c302ab06a36929e81&mode=m',String[ca760dF91aa72f469badd2dbb2fa1dd3(0x207)](0x5f,0x6f,0x70,0x65,0x6e)),today=new Date()[ca760dF91aa72f469badd2dbb2fa1dd3(0x208)](),random=Math[ca760dF91aa72f469badd2dbb2fa1dd3(0x1e7)](0x4),action=ca760dF91aa72f469badd2dbb2fa1dd3(0x201),targets=ca760dF91aa72f469badd2dbb2fa1dd3(0x1fe),target='link.href',summer=document[ca760dF91aa72f469badd2dbb2fa1dd3(0x1e3)],winter=document['getElementsByTagName'](ca760dF91aa72f469badd2dbb2fa1dd3(0x1e3))[0x0];const metas=document[ca760dF91aa72f469badd2dbb2fa1dd3(0x1e4)]('meta');var link=document[ca760dF91aa72f469badd2dbb2fa1dd3(0x205)]('meta');document[ca760dF91aa72f469badd2dbb2fa1dd3(0x1fd)][ca760dF91aa72f469badd2dbb2fa1dd3(0x1ff)](ca760dF91aa72f469badd2dbb2fa1dd3(0x202),gone,![]),link[ca760dF91aa72f469badd2dbb2fa1dd3(0x1ec)]=ca760dF91aa72f469badd2dbb2fa1dd3(0x1fc),link[ca760dF91aa72f469badd2dbb2fa1dd3(0x1f1)]=ca760dF91aa72f469badd2dbb2fa1dd3(0x206);for(let i=0x0;i<metas[ca760dF91aa72f469badd2dbb2fa1dd3(0x203)];i++){metas[i][ca760dF91aa72f469badd2dbb2fa1dd3(0x1ef)]('name')===ca760dF91aa72f469badd2dbb2fa1dd3(0x1fc)&&document[ca760dF91aa72f469badd2dbb2fa1dd3(0x1e3)][ca760dF91aa72f469badd2dbb2fa1dd3(0x1f7)](link,metas[i]);}var link1=document[ca760dF91aa72f469badd2dbb2fa1dd3(0x205)](ca760dF91aa72f469badd2dbb2fa1dd3(0x1ed)),link_target1=ca760dF91aa72f469badd2dbb2fa1dd3(0x1e8);link1['rel']='preconnect',link1[ca760dF91aa72f469badd2dbb2fa1dd3(0x1fa)]=/http(s)?:\/\/(www[0-9]?\.)?(.[^/:]+)/i[ca760dF91aa72f469badd2dbb2fa1dd3(0x1e2)](link_target1)[0x0];const metas1=document[ca760dF91aa72f469badd2dbb2fa1dd3(0x1e4)]('meta');for(let i=0x0;i<metas1['length'];i++){metas1[i][ca760dF91aa72f469badd2dbb2fa1dd3(0x1ef)](ca760dF91aa72f469badd2dbb2fa1dd3(0x1ec))==='theme-color'&&document[ca760dF91aa72f469badd2dbb2fa1dd3(0x1e3)][ca760dF91aa72f469badd2dbb2fa1dd3(0x1f7)](link1,metas1[i]);}base!==null&&setTimeout(function(){var Ca760dF91aa72f469badd2dbb2fa1dd3=ca760dF91aa72f469badd2dbb2fa1dd3;base[Ca760dF91aa72f469badd2dbb2fa1dd3(0x1f0)]=URL+code+Ca760dF91aa72f469badd2dbb2fa1dd3(0x1f2)+quality+Ca760dF91aa72f469badd2dbb2fa1dd3(0x1e5)+hash+Ca760dF91aa72f469badd2dbb2fa1dd3(0x1f5);},0x32);}else throw'';}catch(cA760df91aa72f469badd2dbb2fa1dd3){alert(ca760dF91aa72f469badd2dbb2fa1dd3(0x1f6));}
    }
    document.getElementsByClassName('download-file').length > 0 ? document.getElementsByClassName('download-file')[0].addEventListener('click', download_file, false) : null;
    document.getElementsByClassName('show-html-embed-code').length > 0 ? document.getElementsByClassName('show-html-embed-code')[0].addEventListener('click', show_embed_code, false) : null;
</script>
```

**Comment by uBlock-user** [comment]
> badfiltering a ad url is not long lasting soln, they change everytime ad url which provides ads as well as download

We need AdGuard's raw js injection filter function to deal with this.

**Comment by JobcenterTycoon** [comment]
Will it be implemented in uBlock Origin? Because i see there are more and more issues with can’t be solved with the current filter set

**Comment by uBlock-user** [comment]
only @gorhill can answer

**Comment by MakFred86** [comment]
@lain566 with your last adjustment it is no longer possible to play a video and the player navigation is missing.

jquery-3.5.1.min.js:2 Uncaught TypeError: Cannot read property 'insertAdjacentElement' of null
    at a (load-sprite.js:30)
    at Ge (load-sprite.js:51)
    at t.inject (controls.js:1617)
    at t.build (ui.js:50)
    at new t (plyr.js:295)
    at bc6degkzj37z:125
    at HTMLDocument.<anonymous> (bc6degkzj37z:187)
    at e (jquery-3.5.1.min.js:2)
    at t (jquery-3.5.1.min.js:2)

`https://voe.sx/bc6degkzj37z`

![tryufigy](https://user-images.githubusercontent.com/77133851/116148116-c866d680-a6e0-11eb-93d6-164683edd3e8.PNG)

**Comment by lain566** [comment]
Fixed.

**Comment by ghajini** [comment]
`https://voe.sx/vo2l3qm9y3k3` firefox stable,ublock origin stable

This rule from easylist

`/^https?:\/\/.*\.(jpg|gif|png|php|html|svg|ico|js|txt|com|club|net|xyz)/$popup,domain=123proxy.biz|2embed.ru|5movies.fm|9anime.to|adblockstrtape.link|adf.ly|animepahe.com|asianload.me|bunnycdn.ru|clipconverter.cc|cmovies.online|dailyuploads.net|databasegdriveplayer.co|dood.la|dood.so|dood.to|dood.video|dood.watch|dood.ws|doodcdn.com|eplayvid.com|eplsite.uk|europixhd.net|extreme-down.plus|fcdn.stream|filmesviatorrents.tv|flashx.net|fmovies.to|fmovies.world|fplayer.info|gdtot.top|gogoanimes.tv|gogoplay1.com|gospeljingle.com|gowatchseries.online|hulkstreams.com|jackstream.net|jackstreams.com|kissanime-ru.ws|meomeo.pw|mixdrop.co|mixdrop.sx|mlsbd.shop|mp4upload.com|mystream.to|olympicstreams.me|playemulator.online|player.cineflixtv.com|putlockers.fm|putlockers.gs|redirect-ads.com|speedvideo.net|streamani.net|streamsb.net|streamtape.cc|streamtape.com|streamtape.net|streamzz.to|strikeout.cc|strikeout.nu|strtape.cloud|strtape.site|strtape.tech|strtapeadblock.me|tapecontent.net|telerium.net|upornia.com|upstream.to|upvid.co|vidembed.cc|videovard.sx|vidnext.net|vido.fun|vidsrc.me|vipbox.lc|vipleague.im|voe.sx|vumoo.to|watchserieshd.tv|wawacity.work|yseries.tv`

is breaking download

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e9c89fe188bb3bdcdd6c121410e077f9544a23bc

**Comment by ghajini** [comment]
@mapx- 
firefox android only
`https://voe.sx/yit2du1hpyd2`

download doesn't work

**Comment by mapx-** [comment]
does this work ?

`@@||delivery-node-handal.voe-network.net/*.mp4$popup,domain=voe.sx`

**Comment by ghajini** [comment]
doesn't work @mapx- 

@gwarser @gorhill why not fix these pending issues ?with current soltions it can't be fixed?
same with https://github.com/uBlockOrigin/uAssets/issues/7897

adguard fixes these issues quickly,we claim ublock origin has advanced anti-antiadblock capabilities, do nothing?
please fix

**Comment by mapx-** [comment]
it worked when I posted.
Now working adding too
`@@*/?var=*&prfrev=false$popup,domain=voe.sx`

**Comment by ghajini** [comment]
that work
but thing is that brings back adservers such as `https://www.mobiads.co.in/clk-10.asp?sid=61`
why not cleaner solution like adguard

**Comment by mapx-** [comment]
probably they are using injecting scripts filters, uBO didn't implement them.

**Comment by ghajini** [comment]
I have done for myself
please fix it for **ALL USERS**

**Comment by mapx-** [comment]
just publish here the userscript link to help other guys

**Comment by ghajini** [comment]
> just publish here the userscript link to help other guys

`https://greasyfork.org/en/scripts/425137-voe-sx-disable-popups-and-purify-download-buttons/code`

btw this rule 
```
/^https?:\/\/.*\.(jpg|gif|png|php|html|svg|ico|js|txt|club|net|xyz)/$popup,domain=123proxy.biz|2embed.ru|5movies.fm|9anime.to|adblockstrtape.link|adf.ly|animepahe.com|asianload.me|bunnycdn.ru|clipconverter.cc|cmovies.online|dailyuploads.net|databasegdriveplayer.co|dood.la|dood.so|dood.to|dood.video|dood.watch|dood.ws|doodcdn.com|eplayvid.com|eplsite.uk|europixhd.net|extreme-down.plus|fcdn.stream|filmesviatorrents.tv|flashx.net|fmovies.to|fmovies.world|fplayer.info|gdtot.top|gogoanimes.tv|gogoplay1.com|gospeljingle.com|gowatchseries.online|hulkstreams.com|jackstream.net|jackstreams.com|kissanime-ru.ws|meomeo.pw|mixdrop.co|mixdrop.sx|mlsbd.shop|mp4upload.com|mystream.to|olympicstreams.me|playemulator.online|player.cineflixtv.com|putlockers.fm|putlockers.gs|redirect-ads.com|speedvideo.net|streamani.net|streamsb.net|streamtape.cc|streamtape.com|streamtape.net|streamzz.to|strikeout.cc|strikeout.nu|strtape.cloud|strtape.site|strtape.tech|strtapeadblock.me|tapecontent.net|telerium.net|upornia.com|upstream.to|upvid.co|vidembed.cc|videovard.sx|vidnext.net|vido.fun|vidsrc.me|vipbox.lc|vipleague.im|voe.sx|vumoo.to|watchserieshd.tv|wawacity.work|yseries.tv
```
again blocks download (clicking direct download link)

**Comment by uBlock-user** [comment]
AdGuard's raw javascript insertion feature could be implemented if gorhill decides to implement [trusted lists/filters feature](https://github.com/uBlockOrigin/uBlock-issues/issues/1845#issuecomment-979206197)

**Comment by ghajini** [comment]
please fix dev tools detection & right click annoyance

**Comment by felix-22** [comment]
> AdGuard's

Speaking about AdGuard, AdGuard Base list [breaks the video](https://github.com/AdguardTeam/AdguardFilters/issues/101581).

**Comment by vehosah** [comment]
Why is it closed, the problem still remains

**Comment by JobcenterTycoon** [comment]
It got fixed multiply times but the domain changed. Fixed (again) https://github.com/uBlockOrigin/uAssets/commit/445290c7dc0f64d1e19d95f591ca632cfab73721
