### ISSUE TITLE
https://1.1.1.1/help Issue with Built-In uBlock filters 

### ISSUE THREAD

**Issue by x8009** [uBlockOrigin/uAssets#8369]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
https://1.1.1.1/help

### Describe the issue
Enable uBlock filters 25,773 used out of 25,801 .
Doesn't finish the checking of the server. When uBlock Origin disabled it works.
 

### Versions

- Browser/version: Chrome Version 87.0.4280.88 (Official Build) (64-bit)
- uBlock Origin version: version:1.31.2

### Settings

- uBlock filters 25,773 used out of 25,801 .    With this disabled, it works/or ublock disabled

**Comment by IsraeliUser** [comment]
@okiehsch @mapx- 

Also:
```
https://1.0.0.1/help
https://1.0.0.2/help
https://1.0.0.3/help
https://cloudflare-dns.com/help
https://one.one.one.one/help
```

What about:
`/cdn-cgi/trace$xhr,1p,important,domain=~1.0.0.1|~1.0.0.2|~1.0.0.3|~1.1.1.1|~1.1.1.2|~1.1.1.3|~cloudflare-dns.com|~one.one.one.one`
or
`/cdn-cgi/trace$xhr,1p,domain=~1.0.0.1|~1.0.0.2|~1.0.0.3|~1.1.1.1|~1.1.1.2|~1.1.1.3|~cloudflare-dns.com|~one.one.one.one`
?

**Comment by okiehsch** [comment]
Well, at this point I think it is preferable to make the blocking filter domain specific, who knows what else ot breaks.

**Comment by ghajini** [comment]
Need to find on how many sites cloudfare trace present `https://gist.github.com/ikawka/6efa4551ca765d7d14e00e9a5ea539f8`

I guess its present on many sites
