### ISSUE TITLE
anti adblock on bookfi.net

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#837]
#### URL(s) where the issue occurs

`http://en.bookfi.net/s/?q=Discrete-Event+System+Simulation&t=0`

#### Describe the issue

Adding `||piguiqproxy.com^` to rules will completely block contents of page. Changing it with `*n*-*.piguiqproxy.com^` will allow contents, but blocks CSS and page style.
Could you please help on it to block ads?

#### B section: Other rules applied:
Peter Lowe’s Ad and tracking server list
Easylist
EasyPrivacy
I have also defined the following rules:
`||topadvert.ru^`
`||admixer.net^`
`*_ads.*`

#### Screenshot(s)

Ads location:
`https://imgur.com/a/l9HGd`

How it looks with `*n*-*.piguiqproxy.com^` and rules in **B section** :
`https://imgur.com/a/3ZMKC`

#### Versions

- Browser/version: Chrome 62.0.3202.94 (Official Build) (64-bit)
- uBlock Origin version: v1.14.18

**Comment by zaphodbeebblebrox** [comment]
@okiehsch Ads 
Example url: `http://en.bookfi.net/book/1273184`
```
||postimg.org^$image,domain=en.bookfi.net
en.bookfi.net##noindex
```
