### ISSUE TITLE
https://forum.release-apk.com detecting AdBlock again

### ISSUE THREAD

**Issue by Chris-Rockn** [uBlockOrigin/uAssets#8370]
### URL(s) where the issue occurs
`https://forum.release-apk.com/`

### Describe the issue
The website is detecting adblock again. I have addressed this issue before (8347) and it seemed to be working fine until today.
The site lets you in only if you turn off 2 filters - uBlock filters & Easylist.
With both filters turned on I get 1 warning on the dark background - screenshot 1. With uBlock filters turned off I get pretty much 2 warnings (screenshot 2) - first one is using white background, the second one is kinda showing through the white one - its the one you see when both filters are being used.

And also for a split second I get the warning about "JavaScript has to be activated" which disappears by itself right away(Screenshot 3). Not sure if its an important information but don't think it should be happening.  
### Screenshot(s)
Screenshot 1 - https://i2.imageban.ru/out/2020/12/14/024b5de88ac0424d1e24d0963d2d2fa6.png
Screenshot 2 - https://i4.imageban.ru/out/2020/12/14/dc9c93148b0d050f605e6dc57c69bfc1.png
Screenshot 3 - https://i1.imageban.ru/out/2020/12/14/e0d556921c964c4e5293239863ef97bb.png

### Versions

- Browser/version: Cent Browser Version 4.3.9.226 (Official Build) (64-bit) (Portable) (Chromium 86.0.4240.198)
- uBlock Origin version: 1.31.2

### Settings
[my-ublock-backup_2020-12-14_11.19.56.txt](https://github.com/uBlockOrigin/uAssets/files/5687660/my-ublock-backup_2020-12-14_11.19.56.txt)

-

**Comment by cantunborn** [comment]
Still getting detected.

**Comment by JobcenterTycoon** [comment]
Anti Adblock is back again

**Comment by okiehsch** [comment]
Works fine on my end.

**Comment by JobcenterTycoon** [comment]
The anti adblock only appear on sub sites like `https://forum.release-apk.com/viewforum.php?f=63`. When i click on one topic the anti adblock appears

**Comment by okiehsch** [comment]
If I click on a topic a ant-adb message appears for maybe a second and then.
![image](https://user-images.githubusercontent.com/16838044/103593239-95ac8e80-4ef5-11eb-91fc-066eb9174126.png)

**Comment by okiehsch** [comment]
Are your filters up to date?
If you disable cosmetic filtering for the site can you still reproduce?

**Comment by JobcenterTycoon** [comment]
Yes all filters are updated and i still can reproduce with disabled cosmetic filtering. But um using Firefox not Chrome.

**Comment by okiehsch** [comment]
With Firefox
![image](https://user-images.githubusercontent.com/16838044/103594366-c8a45180-4ef8-11eb-99f2-717160cf63bd.png)

I could reproduce one time but after reloading it worked as expected, let's wait and see if others can consistently reproduce.
