### ISSUE TITLE
videohelp.com broken

### ISSUE THREAD

**Issue by roquez** [uBlockOrigin/uAssets#8372]
### URL(s) where the issue occurs

`https://www.videohelp.com/`
`https://www.videohelp.com/*`

### Describe the issue

Main content of the site is hidden.

### Screenshot(s)
- uBlock Origin enabled
<img src="https://i.imgur.com/HNnEFhk.png">

- uBlock Origin disabled 
<img src="https://i.imgur.com/dtYRig3.png">

### Versions

- Browser/version: Chrome 87
- uBlock Origin version: 1.30.6

**Comment by lain566** [comment]
Fixed.
