### ISSUE TITLE
[Anti adblock] dropgalaxy.in

### ISSUE THREAD

**Issue by sanGtH** [uBlockOrigin/uAssets#8373]
### URL(s) where the issue occurs

`https://dropgalaxy.in/tlb2r848l9ix`

### Describe the issue

The website is detecting the Adblock and disabling the download button,
Even after solving the captcha, you can't proceed to the download link.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/13797193/102229210-84cdb600-3f11-11eb-9ee8-aecb0747ec80.png)

### Versions

- Browser/version: [Chrome 87.x and FF 79.x]
- uBlock Origin version: [1.31.2]

### Settings

All default values

**Comment by ghajini** [comment]
This `||dropgalaxy.com^$inline-script`
works mapx- with **DEFAULT** settings

**Comment by mapx-** [comment]
well, if I cannot reproduce, maybe the other maintainers ..

**Comment by sanGtH** [comment]
@ghajini Thanks for the  script bro.. it works.

**Comment by okiehsch** [comment]
> This ||dropgalaxy.com^$inline-script
works mapx- with DEFAULT settings on my side ; just need confirmation from op

That breaks the countdown on my end.

**Comment by ghajini** [comment]
> > This ||dropgalaxy.com^$inline-script
> > works mapx- with DEFAULT settings on my side ; just need confirmation from op
> 
> That breaks the countdown on my end.

I know,one can download the file but better than n no of whitelists for adservers

**Comment by okiehsch** [comment]
> one can download the file 

I can't, if I click "create download link", the site simply reloads on my end.

**Comment by okiehsch** [comment]
OK, I will add the inline block filter.

**Comment by Mrsihag** [comment]
Owner of Dropgalaxy.com is working hard to pay users for downloads . And you are bypassing because you don't have that much talent to run pay per download site. Do something good which is providing forced ads. Dropgalaxy is only giving Adsense ads , what is issue with developer of adblock. Stop this shit and go and get a job somewhere

**Comment by uplinksadmin** [comment]
please don't spam  any reason i am using dropgalaxy.this best upload and download site in the world.very easy interface.no complence of my user . i am using no captha free upload and download site also.but many  user like to download forom dropglaxy . 
dorpglexy is best user friendly and resposive site.
payment and soupport system is very good .
there are no competitors of dropgalaxy.

**Comment by ricktoronto** [comment]
||dropgalaxy.com^$inline-script

Prevents you from uploading to their service.  It is too general and forces one to disable the ublock filter if you want to upload.

**Comment by ghajini** [comment]
Now they detect again adblockers with default ubo settings
Firefox android ubo 1.31

`https://dropgalaxy.in/7oww8yx2igxd`

![Screenshot_2020-12-22-12-00-24-969_org mozilla fenix](https://user-images.githubusercontent.com/20338483/102856970-994c0a00-444d-11eb-8ff6-94b3826e7b57.png)

**Comment by uBlock-user** [comment]
@ghajini how about `||tmp.dropgalaxy.in^` ?

**Comment by ghajini** [comment]
That was working.....
So all whitelists and redirect filters can be removed....adding whitelists is what they want.
These filters still work on my end
```
||tmp.dropgalaxy.in^
*$image,redirect-rule=2x2.png,domain=dropgalaxy.com,badfilter
*$script,redirect-rule=noopjs,domain=dropgalaxy.com,badfilter
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=dropgalaxy.com,important
||contextual.media.net/dmedianet.js$script,domain=dropgalaxy.com,important
||tpc.googlesyndication.com^$script,domain=dropgalaxy.com,important
||dropgalaxy.com^$generichide,important
```

& if they circumvent your `||tmp.dropgalaxy.in^` then inline script blocking is option

**Comment by sanGtH** [comment]
@adminrocky : Bro, the users who download from your site become frustrated. After solving the captcha and going through
ads filled page, at the  end they get only **50-60 kbps download speed**.  Please increase the download speeds.

**Comment by okiehsch** [comment]
Inline script blocking breaks upload functionality.
I can't reproduce anti adblock message.

**Comment by okiehsch** [comment]
@ghajini does 
`dropgalaxy.com##+js(acis, $, getScript)`
work for you, that will break the timer but upload should still be possible.

**Comment by ghajini** [comment]
That also work
Iam aware of blocking inline script will block something but that's ultimate strong option 😊

**Comment by ricktoronto** [comment]
The download speed is limited unless you are a paid subscriber.  No different than rapidgator and like services. Want faster downloads?  subscribe.

The adblock detection is only valid if the person whom uploaded the file has marked the file as "no adblock"; a file not marked by the uploader as such worked without any changes to ublock.

This is not my website; I happen to be a user (both uploader and downloader)

**Comment by ghajini** [comment]
NSFW
`https://dropgalaxy.in/nb6mmby8r11t`
Antiadblock
Firefox A

Verify captcha> create download link> in next page antiadblock appears 
![Screenshot_2021-03-09-15-19-43-374_org mozilla fenix](https://user-images.githubusercontent.com/20338483/110452194-f66d6880-80ea-11eb-8aa7-0686c3055c2d.png)
