### ISSUE TITLE
Blocked element image

### ISSUE THREAD

**Issue by SoniEx2** [uBlockOrigin/uAssets#838]
I am currently using/making these filters for performance:

```
! hide tumblr images by default
||media.tumblr.com^$image,domain=www.tumblr.com,redirect=32x32-transparent.png,~elemhide
! show avatars, tho
@@||media.tumblr.com/avatar*$image,domain=www.tumblr.com
```

To be able to use a "blocked element" image instead of the transparent PNG, I need uBlock support. Can you include a "blocked element" or "blocked image" or just a general "blocked" image to the resources list? Thanks.

**Comment by gorhill** [comment]
> Can you include a "blocked element" or "blocked image"

Why not use _"Block media elements larger than [...]"_ for that site?

**Comment by SoniEx2** [comment]
I don't remember being able to do it per-site?

**Comment by mapx-** [comment]
add a rule in my rules:
`no-large-media: www.example.com true`

or click uBo icon (while on that page) click the second icon at the bottom

**Comment by SoniEx2** [comment]
Can I adjust the size per-site, both in terms of display width/height and actual size??
