### ISSUE TITLE
r18hub.com [NSFW]

### ISSUE THREAD

**Issue by dumbusernameidk** [uBlockOrigin/uAssets#8385]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### Describe the issue
-Pressing play on a video causes popunder.
-Videos have ads w/timer.

### Versions

- Browser/version: [Chrome latest]
- uBlock Origin version: [latest]

### Settings

default.

**Comment by okiehsch** [comment]
Disabling the popunder causes site breakage on my end.
`https://r18hub.com/assets/scripts/common.js?3b7e69`
triggers the popunder, blocking or disabling it breaks photos on for example
`https://r18hub.com/photo/babylonx-emma-watson-capery-celebrities-exbii`

**Comment by ghajini** [comment]
Preroll video ads
`||r18hub.com/assets/vast/videos/*$xhr,1p`

**Comment by okiehsch** [comment]
@ghajini thx, I overlooked the pre roll ads.
