### ISSUE TITLE
kzclip.com

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#8387]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://kzclip.com/video/23QmCAR8WBI/classic-wow-mage-maraudon-1-pull-boost-gold-farm-100k-exp-200-gph-no-consumables.html`

### Describe the issue

ads

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.31.2]

### Settings

Default

### Notes

I thought it was the Russian language (but not), and with the RU List, the ads disappear, but other annoyance appear with RU list.

**Comment by krystian3w** [comment]
Ad in embeded YT video or these (placeholder/leftover):

`kzclip.com###morev`

---

And what is broken by RU AdList?

**Comment by krystian3w** [comment]
#8117

**Comment by mapx-** [comment]
@PIZZA90 test:

`||kzclip.com^$csp=style-src *`

**Comment by krystian3w** [comment]
Still visible:

![Przechwytywanie](https://user-images.githubusercontent.com/35370833/102773697-f67e8780-4389-11eb-97cd-5d8247826d30.JPG)

**Comment by PIZZA90** [comment]
ads:
https://imgur.com/a/xccn1ae

RU List Active:

https://i.imgur.com/cmGS2Vq.png

**Comment by PIZZA90** [comment]
maybe **krystian3w** you cant reproduce

`kzclip.com##^script:has-text(/.*track.*atob.*ShadowRoot/):has-text(/[\w\W]{5000,10000}/)` 🤔

this filter nothing do

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/8387#issuecomment-748941637 - For Firefox only
