### ISSUE TITLE
Add filters for session-replay scripts

### ISSUE THREAD

**Issue by cynddl** [uBlockOrigin/uAssets#839]
### URL(s) where the issue occurs

* https://bonobos.com
* https://www.walgreens.com
* https://membership.theguardian.com

### Describe the issue

Following the recent article on “Exfiltration of personal data by session-replay scripts” [1], multiple large tracking domains have been shown to exfiltrate emails, phone numbers, CC numbers, along with personal identifiers. These platforms are widely use online (at least on 482 of the Alexa top 50,000 sites).

[1] https://freedom-to-tinker.com/2017/11/15/no-boundaries-exfiltration-of-personal-data-by-session-replay-scripts/

Proposed solution:
```
||www.fullstory.com/s/*$script,third-party
||rs.fullstory.com*http%$script,third-party

||cdn.userreplay.net*http%$script,third-party

||static.hotjar.com*http%$script,third-party

||mtproxy.yandex.net*http%$script,third-party

||rec.smartlook.com*http%$script,third-party
```

SessionCam seemed to be blocked (tracking script URL is _//d2oh4tlt9mrke9.cloudfront.net/Record/js/sessioncam.recorder.js_)

### Versions

- Browser/version: N/A
- uBlock Origin version: N/A

**Comment by okiehsch** [comment]
I am pretty sure they have all been added to `EasyPrivacy` by now.
The article mentions, that "EasyList and EasyPrivacy do not block FullStory, Smartlook, or UserReplay scripts."
I just checked and those three scripts are now part of `EasyPrivacy`.
