### ISSUE TITLE
loadout.tf vertical bar (again)

### ISSUE THREAD

**Issue by Tiagoquix** [uBlockOrigin/uAssets#8392]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`http://loadout.tf/`

### Describe the issue

In the right corner of the page, there is a vertical bar that is supposed to show an ad, but since uBlock Origin blocks the ad, the bar just stays all black. The bar is not removed by uBlock Origin.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/30274161/102858936-d8f10280-4409-11eb-8030-3eb04124fd5c.png)

### Versions

- Browser/version: Google Chrome 87.0.4280.88 (Official version) 64 bits
- uBlock Origin version: 1.31.2

### Settings

All settings are with their default values. I only use two custom filters that aren't related with `loadout.tf`.

### Notes

[I reported this before](https://github.com/uBlockOrigin/uAssets/issues/7490), but apparently the site's owner has created another bar in the same place.

**Comment by uBlock-user** [comment]
`loadout.tf##custom-panel[style="display: flex; flex-direction: column; width: 300px;"]`

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by Tiagoquix** [comment]
@uBlock-user I forgot to mention the versions of my browser and of the extension. I don't think these were extremely necessary, but, anyways, I edited my original post and added them.

**Comment by uBlock-user** [comment]
fixed in EasyList.
