### ISSUE TITLE
pixelcounter.com incorrectly blocked

### ISSUE THREAD

**Issue by johnkavanagh** [uBlockOrigin/uAssets#8393]
### URL(s) where the issue occurs

`pixelcounter.com`

### Describe the issue

I'm the owner of `pixelcounter.com`, and have owned it for over a decade.  As far as I am aware, the domain has never been used for nefarious purposes.

At present it is only a holding page.  However, uBlock Origin intercepts and blocks all network requests for static assets on the page: images, fonts, javascript, etc.

### Screenshot(s)

Network showing blocked requests:
<img width="1303" alt="Screenshot 2020-12-22 at 10 25 23" src="https://user-images.githubusercontent.com/2272755/102878648-7b2bdd00-4440-11eb-8d20-754907eed6d6.png">

Page loads without graphic/font/etc assets:
<img width="1052" alt="Screenshot 2020-12-22 at 10 31 55" src="https://user-images.githubusercontent.com/2272755/102879017-0a38f500-4441-11eb-91a6-b43c848619f8.png">

### Versions

- Browser/version: Chrome 87.0.4280.88 (OSX)
- uBlock Origin version: 1.31.2

### Settings

Default.

### Notes

This one is relatively simple to verify:

- with uBlock Origin switched _on_ the page will load with a blurred (version of the logo, and the font will revert to browser default (see screenshot above);
- with uBlock Origin disabled, the full-quality logo will load, and the font will switch to a web font.

It is my suspicion that it may be as simple as the fact that the domain contains the word 'pixel' that is causing it to trigger the block.

**Comment by uBlock-user** [comment]
Assets blocked via `/pixelcounter.` in EasyPrivacy @ryanbr

**Comment by johnkavanagh** [comment]
@ryanbr would you mind doing the same to unblock `pixelcounter.dev` please?  This is another of my domains, I'm presently finding the same issues with it being blocked.
