### ISSUE TITLE
doctorofcredit.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#8395]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.doctorofcredit.com/celsius-network-earn-interest-on-crypto-deposit-promo-codes/`

### Describe the issue

Clicking in the comment box doesn't load properly. It should expand to include name, email, post button. But it doesn't work consistently. 

### Screenshot

![image](https://user-images.githubusercontent.com/12802056/102930353-3d43ae80-446a-11eb-9161-a3cdd49771ec.png)

vs

![image](https://user-images.githubusercontent.com/12802056/102930443-6bc18980-446a-11eb-9d0c-7e3e7c9058ed.png)

### Notes

I tried reproducing with the logs open but wasn't having luck. Sorry I can't be of more help.

**Comment by uBlock-user** [comment]
Site issue, happens with uBO disabled too.

Console reports  --
![Capture](https://user-images.githubusercontent.com/21290713/102932053-9ab91900-44c5-11eb-9435-4a182c65239a.PNG)

That needs to reported to the site admin.
