### ISSUE TITLE
Ladbible.com anti-adblock

### ISSUE THREAD

**Issue by ACMEd** [uBlockOrigin/uAssets#8396]
### Prerequisites

- [x] This is not a support issue or a question

    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

Videos on `www.ladbible.com`

`https://www.ladbible.com/community/daily-ladness-lad-has-picked-up-bin-bags-of-litter-and-wants-to-do-it-full-time-20201130`

### Describe the issue

 

The video frame is blacked out and says "Please turn off your ad blocking software to view this video"

### Versions

- Browser/version: Firefox 84.0
- uBlock Origin version: 1.31.0

### Settings

All stock lists enabled (except for mobile and regional)

**Comment by ACMEd** [comment]
Still broken, now I just see a black rectangle instead of a video.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/102957101-de1d8280-44d9-11eb-98cb-2a11d1b38f41.png)

**Comment by okiehsch** [comment]
I tried with your setup,  i.e. all filter lists enabled except for mobile and regional and the fix works on my end using Chromium and Firefox.

**Comment by ACMEd** [comment]
Ah, `static.adsafeprotected.com` was being blocked by firefox's enhanced browser protection and by my hosts file. Issue resolved.

**Comment by ACMEd** [comment]
Is allowing `adsafeprotected.com/vans-adapter-google-ima.js` a privacy concern?
