### ISSUE TITLE
Custom filter only replaces ad with black screen on TubiTV

### ISSUE THREAD

**Issue by Usalabs** [uBlockOrigin/uAssets#8397]
Someone posted on Reddit a created a custom filter to prevent ads on TubiTV, it was working for about 3 weeks, then all it does now is just replace the ads with a black screen and at the bottom left corner is "The video will resume after this break", and a hidden timer is running for whatever the length of the ad that would have been shown.

I'm using windows 10 home version 1909 with all updates current, my primary browser is Chrome Version 87.0.4280.88 (Official Build) (64-bit), I only have uBlock origin, uBlock origin extra and FVD speed dial extensions installed, I have not changed any default settings at all, everything with exception to the addition of the custom filter is default.

This is the custom filter for Chrome browser:-

`||adrise.tv/*.mp4$media,redirect=noopmp3-0.1s,domain=tubitv.com`

And being that there's no way of inserting an image here, this is the link to my Google Drive that has the screenshot.

[TubiTV Screen shot](https://drive.google.com/open?id=1IPH0XsyXraIihaSTocM8EGQycapvN7ns)
Notice at the bottom left corner,

**Comment by mapx-** [comment]
I tested a random video, no ads on my end. 

Could you provide a test link where you get ads ? preroll ads ? midroll ? etc

**Comment by uBlock-user** [comment]
Yes, that's what a `$redirect` does. You're not going to see an ad, bu the ad-insertion is still present and running.

**Comment by Usalabs** [comment]
> I tested a random video, no ads on my end.
> 
> Could you provide a test link where you get ads ? preroll ads ? midroll ? etc

[America's Dumbest Criminals](https://tubitv.com/tv-shows/521691?start=true)

**Comment by Usalabs** [comment]
> Yes, that's what a `$redirect` does. You're not going to see an ad, but the ad-insertion is still present and running.
> 
> I'm not seeing an ad-insertion though fyi, you also removed the template and didn't fill it in, which would have made the issue you face clear.

It never did it before, it used to just jump ahead past the ad then continue on, but it suddenly stopped doing that, and did what I described, it could be a Chrome update, or something with tubiTV, idk, and as for as the 'template'?  It's far to confusing, when a simple explanation is far better and more understandable.

**Comment by mapx-** [comment]
Watching first 90 seconds, still cannot get ads.

**Comment by Usalabs** [comment]
> Watching first 90 seconds, still not getting ads.

Then I have no idea what it is, and being that it can't be re-produced, by anyone and it only happens to me, I'll have to use Primewire with a VPN, and substitute uBlock with Adblock and AdBlock+, along with Scriptsafe.

**Comment by llacb47** [comment]
Probably ads in US/NA only, try watching for more than 90 seconds also. @mapx-

**Comment by mapx-** [comment]
I used US ip otherwise from Europe it's avoided

**Comment by krystian3w** [comment]
Maybe test:

`||adrise.tv/*.mp4$media,redirect=noopmp3-0.1s:99,domain=tubitv.com`

**Comment by Usalabs** [comment]
> Maybe test:
> 
> `||adrise.tv/*.mp4$media,redirect=noopmp3-0.1s:99,domain=tubitv.com`

It works for TV Shows that have minimal ads, the 'black screen' flashes on then off and continues the show, but for movies that have longer ads, it still doesn't work, the black screen is still there, but I have found a better solution, and that is to change streaming services to crackle, it seems uBlock origin does stop those ads and all I see on there is just 3 dots being animated for a very brief time then the movie continues.
