### ISSUE TITLE
news.yandex.ru

### ISSUE THREAD

**Issue by TheFinalCut83** [uBlockOrigin/uAssets#84]
### URL(s) where the issue occurs
- `https://news.yandex.ru`
- `https://news.yandex.ru/yandsearch?text=%D1%85%D0%BE%D0%BB%D0%BE%D0%B4%D0%B8%D0%BB%D1%8C%D0%BD%D0%B8%D0%BA%D0%B8&rpt=nnews2&grhow=clutop`
### Describe the issue

There is an Yandex Direct ad in the right frame. 
### Screenshot(s)

![1](https://cloud.githubusercontent.com/assets/16985985/16911510/8f5e1f40-4ce7-11e6-840a-4ae8886eecb4.jpg)
### Versions
- Browser/version: Firefox 48.0b7 / Cyberfox 47.0.1
- uBlock Origin version: 1.7.7b14
### Settings

Subscriptions:
1. uBlock filters
2. uBlock filters – Badware risks‎
3. uBlock filters – Privacy‎
4. uBlock filters – Unbreak‎
5. Adblock Warning Removal List
6. Anti-Adblock Killer | Reek
7. EasyList
8. EasyPrivacy‎
9. Malvertising filter list by Disconnect‎
10. RUS: Adguard Russian Filter
11. RUS: BitBlock List
12. RUS: RU AdList

![2](https://cloud.githubusercontent.com/assets/16985985/16911767/126de446-4ce9-11e6-925d-30d497ba545b.jpg)
### Notes

Maybe is it possible to adapt [this filter](https://github.com/uBlockOrigin/uAssets/commit/346866b38241cc7462851194453d60a129cf41ce) for news.yandex.ru (.by/.ua/.kz/)?

**Comment by gorhill** [comment]
I don't read Russian. Which part of the page is an ad> Can you highlight it in the screenshot?

**Comment by TheFinalCut83** [comment]
Pardon me
![1](https://cloud.githubusercontent.com/assets/16985985/16912017/892648ca-4cea-11e6-9329-1e0dc8a15a9f.jpg)

**Comment by gorhill** [comment]
Can you see if this one works?

    news.yandex.ru##:xpath(//ul[contains(@class,"search-list")]/li[contains(@class,"search-item")][.//text()="Яндекс.Директ"])

**Comment by TheFinalCut83** [comment]
Unfortunately, yes and no. It works fine in case of searching news via search bar (at the top, with yellow border and "Кремль" text on the pic)
![4](https://cloud.githubusercontent.com/assets/16985985/16914126/65afd8bc-4cf8-11e6-829b-eeb65c60da77.jpg)
But on the main page and various pages with news ads are still appear.
![5](https://cloud.githubusercontent.com/assets/16985985/16914273/71f580da-4cf9-11e6-9066-aec82932571d.jpg)

![6](https://cloud.githubusercontent.com/assets/16985985/16914276/78342064-4cf9-11e6-84f5-066e3c60c2bb.jpg)

![7](https://cloud.githubusercontent.com/assets/16985985/16914280/7bb56bee-4cf9-11e6-9ddf-69df44f06712.jpg)

**Comment by gorhill** [comment]
I was looking at `https://www.yandex.com/search/`, but not being able to read Russian, I can't tell whether there are ads in the page. I would appreciate if you assist me for this -- I would like to be sure that `yandex.ru` is all covered by uBO's filters.

**Comment by TheFinalCut83** [comment]
All is ok without logging in (or incognito mode). When logging in, ads are appear. Firefox 48, uBO 1.8.0, with custom filter `news.yandex.ru##:xpath(//ul[contains(@class,"search-list")]/li[contains(@class,"search-item")][.//text()="Яндекс.Директ"])`
![1](https://cloud.githubusercontent.com/assets/16985985/17337331/d37d6bae-58ea-11e6-9c7d-23b1e8a9be05.jpg)

**Comment by aggat** [comment]
Странная ошибка, если у вас действительно включен EasyPrivacy. У меня Яндекс Директ появляется только если разблокировать `an.yandex.ru`, заблокированный в EasyPrivacy
Потробуйте добавить
`||an.yandex.ru^$important` в "Мои фильтры"

**Comment by TheFinalCut83** [comment]
Спасибо, фильтр, который вы предложили, действительно помогает. Не вижу
вашего сообщения в топике, думаю, стоит написать об этом фильтре туда.

2 августа 2016 г., 20:41 пользователь aggat <notifications@github.com>
написал:

**Comment by gorhill** [comment]
I just completed prototype code to implement a new operator which will solve the issue more easily: `:csstext()`. It was pretty straightforward to add after the refactoring of the content script code.

Note of caution: despite the resemblance, this is _not_ `-abp-properties`. The purpose of `-abp-properties` is to reverse lookup CSS selector by scanning _all_ existing CSS rules. The purpose of `:csstext(...)` is to _directly_ match DOM elements (not CSS rules) using the `cssText` of their computed style. For example, a cosmetic filter which appear to work well is for the case here:

    news.yandex.ru##.story[id]:csstext(position: absolute)

This new cosmetic filter operator requires that there is a CSS selector prefix, i.e. `:csstext(...)` alone will be discarded, and just like other new cosmetic filter operator, must be specific, i.e. apply to at least one specific hostname.

The filter above works this way:

- uBO will lookup all nodes which match the CSS selector suffix `.story[id]` (there were 8 such nodes in my text case).
- For each node in the set, uBO will further narrow the resultset by retaining only the nodes which computed style matches the content of `:csstext(...)`.
- The resulting set will be hidden just like the matching nodes from `:has()` or `:xpath()` currently are.

Theoretically, some cosmetic filters based on `-abp-properties` could be converted to the `:csstext()` operator. However, efficient `:csstext()` cosmetic filters require to chose a good CSS selector prefix. The existing filter in RUAdlist, `news.yandex.ru##.story[-abp-properties="position: absolute"]` is unfortunately not specific enough, the resultset for `.story` is above 60 nodes in my test case, while `.story[id]` is less than 10.

Conclusion is that it's best to craft uBO-specific efficient filters. Filter list maintainers could theoretically mind to pick efficient CSS selector prefix to accommodate efficiency (this would not improve ABP's efficiency however), in which case I would be open to add code to transpose `-abp-properties` where possible (when all conditions are fulfilled), but by the look of it the not-invented-by-ABP mindset is still going strong with some filter list maintainers.

**Comment by aggat** [comment]
Фильтр `||an.yandex.ru^` уже есть в EasyPrivacy и должен работать, если  EasyPrivacy у вас включен. Фильтры можно отключать `@@||an.yandex.ru^` и, возможно, какая-то из ваших подписок отключает фильтр из EasyPrivacy. Опция `$important`, например `||an.yandex.ru^$important` задает повышенный приоритет. В [логгере](https://github.com/gorhill/uBlock/wiki/The-logger) проблема должна быть [видна](https://github.com/gorhill/uBlock/wiki/The-logger#finding-from-which-lists-a-static-filter-originates)

**Comment by gorhill** [comment]
Experimental: 1.8.1b0 + `news.yandex.by,news.yandex.kz,news.yandex.ru,news.yandex.ua##.search-item[id] > .story-item:matches-css(border-bottom-style:none; margin-bottom:0px;)`

**Comment by TheFinalCut83** [comment]
No, still doesn't work even with that filters (uBO 1.8.1b0):
- news.yandex.ru##:xpath(//ul[contains(@class,"search-list")]/li[contains(@class,"search-item")][.//text()="Яндекс.Директ"])
- ||an.yandex.ru^$important
- news.yandex.by,news.yandex.kz,news.yandex.ru,news.yandex.ua##.search-item[id] > .story-item:matches-css(border-bottom-style:none; margin-bottom:0px;)
![2](https://cloud.githubusercontent.com/assets/16985985/17374775/d7e84444-59b6-11e6-8a80-64e4f91c11dc.jpg)

**Comment by gorhill** [comment]
For any case which does not work, I need an exact URL to be able to reproduce on my side. For now, the filter `news.yandex.by,news.yandex.kz,news.yandex.ru,news.yandex.ua##.search-item[id] > .story-item:matches-css(border-bottom-style:none; margin-bottom:0px;)` work on my side, for get about the others. Also, be sure cosmetic filtering is not toggled off -- it happens to me sometimes when I investigate a site.

**Comment by gorhill** [comment]
The page serves these ads in many ways, so I finally reproduce a case where I see ads as above. So add this other filter:

    news.yandex.by,news.yandex.kz,news.yandex.ru,news.yandex.ua##.story[id]:matches-css(position: absolute;)

**Comment by TheFinalCut83** [comment]
With this filter Yandex ad appears rarely, but this is much better, thanks.

**Comment by fedorvinogradov** [comment]
I have a problem with a page [https://news.yandex.ru/quotes/2002.html](https://news.yandex.ru/quotes/2002.html).

The cosmetic filter hides this element:
`##.b-page__inner > .page-content_js_inited.i-bem.page-content_exp-newrtb_yes.page-content > .page-content__layout > .page-content__left`
which is the main information on the page.

But if I turn off cosmetic filters I start to see ads which are being discussed in this thread.
Is it possible to make an exception for this element?

**Comment by gorhill** [comment]
Where is this filter coming from? It's not a uBO filter. Even using all RU filter lists I do not see the main information being hidden. Is this a custom filter?

**Comment by fedorvinogradov** [comment]
I found the code of this element by turning off cosmetic filters and clicking on it with element picker.
I tried to turn off all of my filters but the result was the same.
And then your question aimed me to purge all caches, update the list, reload the web page and the problem gone.
Thanks for your app!

**Comment by TheFinalCut83** [comment]
Already seen this behavior yesterday, updating the filter lists manually helped.

**Comment by TheFinalCut83** [comment]
https://news.yandex.ru/yandsearch?lr=10710&cl4url=ria.ru%2Fincidents%2F20170615%2F1496530209.html&lang=ru&rubric=index&from=index
Yandex.Direct [appears again](http://i.imgur.com/8Bkflxv.jpg).
These filters:
```
news.yandex.ru##.page-content__left > div[class]:has(a[href*="/clck/jsredir"]) 
news.yandex.ru##.page-content__right > .page-content__col > div[class]:has(a[href*="/clck/jsredir"]) 
news.yandex.ru##.page-content__right > div[class]:not(.page-content__col):has(a[href*="/clck/jsredir"])
```
seems to be helpful. @gorhill, please add them to uBlock filters.

**Comment by dimisa-RUAdList** [comment]
Up! >
`news.yandex.ru##.page-content__left > div[class]:has(a[href*="/clck/jsredir"]) 
news.yandex.ru##.page-content__right > .page-content__col > div[class]:has(a[href*="/clck/jsredir"]) 
news.yandex.ru##.page-content__right > div[class]:not(.page-content__col):has(a[href*="/clck/jsredir"])`
