### ISSUE TITLE
nbcsports.com anti-adblock

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#840]
### URL(s) where the issue occurs

`http://stream.nbcsports.com/rsn/nba-wizards-live-stream`

### Describe the issue

Anti-adblock.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/32875372-a0b01896-ca65-11e7-8d97-d719268a6eef.png)

### Versions

- Browser/version: Chrome/62
- uBlock Origin version: 1.14.18

### Settings

Default

### Notes

May need to sign in.

**Comment by okiehsch** [comment]
Well, yes I need to sign in via my Cable, Satellite, Or Telco TV Provider, which I do not have, so somebody else will have to come up with a solution.

**Comment by uBlock-user** [comment]
bait - http://stream.nbcsports.com/assets/page/general/ads.js

**Comment by terrorist96** [comment]
`@@general/ads` gets rid of the adblock message, but video still won't play. Adding `@@-720x90-` will fix it.

**Comment by mapx-** [comment]
@terrorist96  do you have a working fix ?

**Comment by terrorist96** [comment]
No. It's hard to pin down. Plus, this happened on a relative's computer, and I don't have an account either, so I can't readily reproduce it.

**Comment by jspenguin2017** [comment]
I have a working solution in Nano Defender: 
```
@@||stream.nbcsports.com^$generichide
```
then
```js
if (a.domCmp(["stream.nbcsports.com"])) {
    a.loopbackXHR((ignored, url) => {
        if (url.includes(".v.fwmrm.net/ad/g/1")) {
            return `<VAST version='3.0' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='vast.xsd'>
</VAST>`;
        }
    });
}
if (a.domCmp(["nbcsports.com", "knowyourmeme.com"])) {
    a.readOnly("adblockDetect", () => { });
}
if (a.domCmp(["swissadspaysfaucet.com", "swissadspaysethfaucet.com", "stream.nbcsports.com"])) {
    a.readOnly("adBlockEnabled", false);
}
```

**Comment by mapx-** [comment]
could be something like 
https://github.com/uBlockOrigin/uAssets/issues/218#issuecomment-351215589

? I cannot test the issue.

**Comment by misha-kotov** [comment]
has anyone else found a solution to this?

**Comment by jspenguin2017** [comment]
Can someone try: 
```
@@||stream.nbcsports.com^$generichide
||v.fwmrm.net/ad/g/1$xmlhttprequest,domain=stream.nbcsports.com,redirect=nano-noop-vast-3.0
nbcsports.com##script:inject(set-constant.js, adblockDetect, noopFunc)
stream.nbcsports.com##script:inject(set-constant.js, adBlockEnabled, false)
```

`nano-noopvast-3.0` is defined as: 
```
nano-noopvast-3.0 text/xml
<VAST version="3.0"></VAST>
```

**Comment by yourduskquibbles** [comment]
@mapx- the filters suggested by @jspenguin2017 work when I login with xfinity/comcast.

Please add to uBlock filters!

**Comment by yourduskquibbles** [comment]
Getting an adblock warning when I am trying to [stream a live event.](http://stream.nbcsports.com/nhl/vegas-golden-knights-washington-capitals?pid=207115)


Screenshot of adblock message:
![adblock](https://user-images.githubusercontent.com/22258847/40948030-6fd0c1e2-6855-11e8-9368-56058ad01c6c.PNG)


logger screenshot: 
![logger](https://user-images.githubusercontent.com/22258847/40948043-8815c89c-6855-11e8-8660-db9c248d2f0d.PNG)

**Comment by jspenguin2017** [comment]
Is `nano-noopvast-3.0` properly defined in your installation of uBO? 
This is really difficult to test because the type of account it asks.

**Comment by yourduskquibbles** [comment]
Updated the rules to the following 

``@@||stream.nbcsports.com^$generichide
||v.fwmrm.net/ad/g/1$xmlhttprequest,domain=stream.nbcsports.com,redirect=nano-tiny-noopvast-3.0
nbcsports.com##script:inject(set-constant.js, adblockDetect, noopFunc)
stream.nbcsports.com##script:inject(set-constant.js, adBlockEnabled, false)``

and added [NanoResources](https://jspenguin.com/NanoAdblocker/AssetsMirror/NanoResources.txt) to userResourcesLocation and still getting adblock message when I hit the play button on the video.


Screenshot of logger with the `nano-tiny-noopvast-3.0` request 
![logger2](https://user-images.githubusercontent.com/22258847/40949998-537c5cb2-6860-11e8-9510-c213562d8d4d.PNG)

**Comment by jspenguin2017** [comment]
Can you check if Nano Defender works? The rule is slightly different.

**Comment by yourduskquibbles** [comment]
@jspenguin2017 Yes! It now seems to work with [Nano Defender](https://chrome.google.com/webstore/detail/nano-defender/ggolfgbegefeeoocgjbmkembbncoadlb/related) installed and uBlock Origin Extra 2.71 disabled.

![screen](https://user-images.githubusercontent.com/22258847/40950403-11f3d2f0-6862-11e8-8001-fcccd8f6eeb7.PNG)


I followed the [Extra Installation Steps for Nano Defender](https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin) for uBlock Origin and added the additional filter lists as well for anyone else finding this issue in the future...


I'm curious, what is the difference in Nano Defender and how can your fixes be incorporated into base uBlock Origin/UBO Extra installation?

**Comment by jspenguin2017** [comment]
Do you know how to launch a local server? Create a file with following content: 
```
nano-tiny-noopvast-3.0 text/xml

<?xml version="1.0" encoding="UTF-8"?>
<VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="3.0">
</VAST>
```

Put uBO back to default, disable Nano Defender, load the file from local server into uBO's advanced settings, and add rules above. And let me know if it works. 

Alternatively, you can give uBO access to your file system and serve the file directly.

**Comment by jspenguin2017** [comment]
> the `nano-tiny-noopvast-3.0` will be triggered by a different filter from Easylist

That's OK, I have a different payload posted above, can you try that too?

**Comment by yourduskquibbles** [comment]
The alt resources.txt payload also does _NOT_ work. I saved it as a separate txt file with unique name just to make sure it wasn't loading from cache or something.

![altpayload](https://user-images.githubusercontent.com/22258847/40951877-f1b5457a-6846-11e8-9ae4-20777e4e84b1.PNG)

![altpayloadsetting](https://user-images.githubusercontent.com/22258847/40951884-f9f17056-6846-11e8-836d-b9b151f85bbf.PNG)

**Comment by jspenguin2017** [comment]
Does the console says something about `access control allow origin`? 
If yes, then you can try to patch uBO and put the resource in WAR. 
Otherwise the fix needs to be a pretty big scriptlet, which gorhill won't accept according to his past decisions. 

```
nbcsports.com##+js(nbcsports-defuser.js)
@@||stream.nbcsports.com^$generichide
nbcsports.com##script:inject(set-constant.js, adblockDetect, noopFunc)
stream.nbcsports.com##script:inject(set-constant.js, adBlockEnabled, false)
```

```js
nbcsports-defuser.js application/javascript

(() => {
        "use strict";
        const replace = (that, text) => {
            window.Object.defineProperty(that, "responseText", {
                configurable: false,
                set() { },
                get() {
                    return text;
                },
            });
            window.Object.defineProperty(that, "response", {
                configurable: false,
                set() { },
                get() {
                    return text;
                },
            });
        };
        try {
            const _open = window.XMLHttpRequest.prototype.open;
            window.XMLHttpRequest.prototype.open = function (method, url, ...rest) {
                const [isAsync, user, passwd] = rest;
                ((ignored, url) => {
        if (url.includes(".v.fwmrm.net/ad/g/1")) {
            return `<VAST version='3.0' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='vast.xsd'>
</VAST>`;
        }
    })();
                return _open.call(this, method, url, ...rest);
            };
        } catch (err) {
            window.console.error("[Nano] Failed :: XMLHttpRequest Replace Engine");
        }
})();
```

**Comment by yourduskquibbles** [comment]
Yes, there is an error for `Access-Control-Allow-Credentials` in the Console.

![fail2](https://user-images.githubusercontent.com/22258847/40952433-40bdab06-6849-11e8-9a50-febfc14e2809.PNG)

**Comment by jspenguin2017** [comment]
If it says `Credentials` then WAR probably won't work, I haven't tried it but it's over-complicated anyway. 

Yea, this would be really difficult to fix with uBO alone. I don't have a better solution. The scriptlet above is the last resort, otherwise, there is Nano Defender.

**Comment by yourduskquibbles** [comment]
If a solution can't / won't be added to uBlock Origin I've detailed the steps required to fix this for yourself for anyone finding this in the future.


## Fix for adblock message preventing video playback on nbcsports.com
1) Install [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm)
2) Install [Nano Defender](https://chrome.google.com/webstore/detail/nano-defender/ggolfgbegefeeoocgjbmkembbncoadlb) 
3) Follow Nano Defender [extra installation steps for uBlock Origin](https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin)
4) Add the following filters to 'My Filters' in uBlock Origin
``@@||stream.nbcsports.com^$generichide
||v.fwmrm.net/ad/g/1$xmlhttprequest,domain=stream.nbcsports.com,redirect=nano-tiny-noopvast-3.0
nbcsports.com##script:inject(set-constant.js, adblockDetect, noopFunc)
stream.nbcsports.com##script:inject(set-constant.js, adBlockEnabled, false)``

* The fix works as of 2018-06-04

**Comment by jspenguin2017** [comment]
If you use Nano Defender, the custom filters would not be needed.

**Comment by yourduskquibbles** [comment]
Updated to remove step 4 with the custom filters

**Comment by misha-kotov** [comment]
Thanks for looking into this annoying issue! Cannot wait to try it out. Go Caps! 😬

**Comment by ghajini** [comment]
@gorhill working solution described by jspenguin2017

**Comment by misha-kotov** [comment]
The [solution above](https://github.com/uBlockOrigin/uAssets/issues/840#issuecomment-394565728) works for me!
