### ISSUE TITLE
Startpage.com "abp.js?adType=1&advertiser=1&advertising=1"

### ISSUE THREAD

**Issue by runboy93** [uBlockOrigin/uAssets#8400]
This looks very suspious to me, anyway if it's not adding any ads (?) then very likely it's checking out if user is using adblock or similar script action related to ads (tracking)?

`https://eu.startpage.com/sp/cdn/abp.js?adType=1&advertiser=1&advertising=1`

I already added it to my own list, nothing negative so far, if someone else would check this out or know more about this?

**Comment by uBlock-user** [comment]
That's the bait script, which they're hoping you would block.

**Comment by uBlock-user** [comment]
That's the bait script, which they're hoping you would block. 

You can trap the bait with  `startpage.com##+js(aeld, load, #abp)`
