### ISSUE TITLE
c-api-bit.shopeemobile.com seller.shopee.sg

### ISSUE THREAD

**Issue by c2xusnpq6** [uBlockOrigin/uAssets#8404]
`https://c-api-bit.shopeemobile.com/tw/tr`
![圖片](https://user-images.githubusercontent.com/75058881/103146643-8d32b600-4787-11eb-9a72-ca4fe4c06f2e.png)

`https://seller.shopee.sg/api/pap/report`
![圖片](https://user-images.githubusercontent.com/75058881/103146661-bfdcae80-4787-11eb-86d7-2c355aca13a5.png)

**Comment by uBlock-user** [comment]
https://github.com/easylist/easylist/issues/6837
