### ISSUE TITLE
fssquad.com [Anti-Adblock]

### ISSUE THREAD

**Issue by KiLL4FuNK** [uBlockOrigin/uAssets#8406]
URL(s) where the issue occurs

`https://fssquad.com/threads/teen-italian-10gb-mega-nz.58705/page-40#post-610751`

Describe the issue

Anti-Adblock

![01024504054](https://user-images.githubusercontent.com/36675858/49224096-48c56800-f3bf-11e8-98ae-280e58ed9b06.png)
Microsoft Windows 8.1 Version : Update 3 (64-bit)

![0102454256](https://user-images.githubusercontent.com/36675858/49224125-58dd4780-f3bf-11e8-84e6-e4a105e5d10d.png)
Google Chrome Version : 87 (Official Build) (64-bit)

![105404212565](https://user-images.githubusercontent.com/36675858/49224135-64307300-f3bf-11e8-971b-cdbed773d43f.png)
uBlock Origin Version: 1.31.2

Settings

Default

**Comment by Rust1667** [comment]
This site is detecting uBlock again.
But it only happens when you are logged-in
Account: username:`mario9385` - password:`fYrB$9A~E"a?r:x`
Example URL: `https://fssquad.com/forums/rules-announcements.49/`
