### ISSUE TITLE
Pioneer.eu - Broken (uBlock filters - Privacy)

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uAssets#8408]
### Affected site:
`https://www.pioneer.eu/`

### Issue:
No matter what you click on, nothing happens!

### Screenshot:
Not needed, as the problem is obvious.

### Problem filter:
* **uBlock filters - Privacy**

### Problem rule:
`||googletagmanager.com/gtm.js$script,redirect=googletagmanager.com/gtm.js`

### Blocked script:
`https://www.googletagmanager.com/gtm.js`

### Possible fix:
`@@||googletagmanager.com/gtm.js$domain=pioneer.eu`

### Other problem filters:
* **AdGuard Tracking Protection filter** https://github.com/AdguardTeam/AdguardFilters/issues/70941/
`||googletagmanager.com/gtm.js?$third-party`

* **EasyPrivacy** https://github.com/easylist/easylist/issues/6845/
`/gtm.js`

* **hpHosts - Ad and Tracking servers only** _(DISCONTINUED)_
`googletagmanager.com`
`www.googletagmanager.com`

* **Peter Lowe's Ad and tracking server list** (@pgl)
`googletagmanager.com`

--

### System info:
* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.17.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.27 (XUL)

**Comment by uBlock-user** [comment]
`pioneer.eu##+js(ra, onclick, a[href][onclick^="trackOutboundLink"])` works.
