### ISSUE TITLE
Unsubscribe request on Burger King newsletter from Belgium gets filtered

### ISSUE THREAD

**Issue by azertyfun** [uBlockOrigin/uAssets#8409]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://burgerbrands.slgnt.eu/optiext/optiextension.dll`

### Describe the issue

Unsubscribing from the Burger King (Belgium) newsletter does not work because uBlock prevents the POST request from going through. This is the request copied as cURL from the Network tab of my firefox dev tools (personal identifiers redacted):

```
curl 'https://burgerbrands.slgnt.eu/optiext/optiextension.dll?ID=[REDACTED]' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://burgerbrands.slgnt.eu/' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'X-Requested-With: XMLHttpRequest' -H 'Origin: https://burgerbrands.slgnt.eu' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Cookie: __cfduid=[REDACTED]; SERVERIDpe=[REDACTED]' --data-raw ''
```

The issue was not immediately apparent as BK does not have any error handler, only in the Network tab did I realize what was going wrong. Disabling uBlock for that page fixes the issue (see screenshot).

### Screenshot(s)

![image](https://user-images.githubusercontent.com/1971608/103178331-2fcf5f80-4882-11eb-8357-57923bf50a4d.png)
Fourth request was after disabling uBlock.

### Versions

- Browser/version: Firefox 84.0
- uBlock Origin version: 1.31.0

### Settings

- No changes from default

### Notes

I'm not sure why the request is blocked as I do not get a warning accessing the page, and the `POST` request is for that very same URI. I'm not familiar with uBlock's blocking mechanisms, is there something that only targets XHR requests? If so can this be disabled for that use-case?

**Comment by uBlock-user** [comment]
Open the logger and look for that blocked URL and then click on that which will reveal which filter and from which list is causing the block.

**Comment by gwarser** [comment]
EasyPrivacy `/optiextension.dll?$~subdocument`?

**Comment by uBlock-user** [comment]
@ryanbr
