### ISSUE TITLE
piguiqproxy on putlocker.today

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#841]
#### URL(s) where the issue occurs

`http://putlocker.today/`

#### Describe the issue

Ads are shown in screenshot. It's similar to the issue at https://github.com/uBlockOrigin/uAssets/issues/837 using piguiqproxy.com
I can block them with following rule, but its place holder will still exist. I'd be thankful if you come up with a better rule.
`||piguiqproxy.com/api$xmlhttprequest,redirect=nooptext`

#### Screenshot(s)

`https://imgur.com/a/7wqE4`

#### Other rules applied:
`||e85440ec98f04725.com^$popup`

#### Versions

- Browser/version: Chrome 62.0.3202.94 (Official Build) (64-bit)
- uBlock Origin version: 1.14.18

**Comment by uBlock-user** [comment]
You can use `putlocker.today##script:inject(abort-on-property-read.js, performance)`. With that no need to whitelist or redirect that ad-server's connection requests.

**Comment by okiehsch** [comment]
`putlocker.*##script:inject(abort-current-inline-script.js, parseInt, tabunder)` is already part of `uBO- filters`.

**Comment by uBlock-user** [comment]
Ah yes, I see. Edited the post.

**Comment by uBlock-user** [comment]
@okiehsch Speaking of which, could you please also add `kimcartoon.me` to the list ? It's also running the tabunder script .

**Comment by nimasaj** [comment]
@okiehsch, Could you please explain on how you add these rules? more on defining parameters please. How did you choose `parseInt, tabunder`?

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/618#issuecomment-321842729 for a basic explanation of that scriptlet.

I can't give you a tutorial.

**Comment by okiehsch** [comment]
@uBlock-user https://github.com/uBlockOrigin/uAssets/commit/7f91af429e7e63be9b7b7c1632b9eed8db23923f

**Comment by uBlock-user** [comment]
Another thing, `kimcartoon.me` has removed the script through which they were making connections to `piguiqproxy.com` and fetching ads, so you may want to remove `MutationObserver` filter, just an FYI

**Comment by theinstantmatrix** [comment]
Popunders are back at `https://www6.putlocker.ninja/`

can the old filter be updated with `putlocker.*##+js(abort-current-inline-script.js, Math, zfgloaded)`?
