### ISSUE TITLE
EasyList FR

### ISSUE THREAD

**Issue by tistoubapt** [uBlockOrigin/uAssets#8412]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Possible to re add EasyList FR (https://easylist-downloads.adblockplus.org/liste_fr.txt) in Region, Language ?

Since some versions of Origin, this list has been replaced by FRA: AdGuard Français

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected behavior:

[What you expected to happen]

### Actual behavior:

[What actually happened]

### Your environment

* uBlock Origin version: 1.28.4
* Browser Name and version: Edge Canary 86.0.585.0 
* Operating System and version: Windows 10 Pro 2009 x64

**Comment by mapx-** [comment]
@tistoubapt usually the adguard list is the same liste fr list with some corrections.

Explain again here what's wrong (provide links, explain the issue)

**Comment by tistoubapt** [comment]
Hi @mapx- 

From the `forum.hardware.fr forum`, if I click on a link pointing to `fr.aliexpress.com`, the page opens and closes directly
If I disable the "FRA Adgaurd" list, it's good

at the time adding the `||digidip.net^$third-party` filter fixed the problem

the forum in question adds a redirect link it would seem

Thanks

**Comment by mapx-** [comment]
- That filter `||digidip.net^$third-party` is already in adguard list
- I cannot reproduce your issue on this page:
`https://forum.hardware.fr/hfr/OverclockingCoolingModding/Water-Xtreme-Cooling/watercooling-optimisations-debat-sujet_263441_1063.htm#t2524731`

Maybe you can reproduce the issue **only if you use an account ?**

**Comment by tistoubapt** [comment]
Inded, this link work

Bit not this one

https://forum.hardware.fr/hfr/Hardware/Boitier/topic-unique-hfriens-sujet_604307_420.htm#t10920659

Thanks

**Comment by mapx-** [comment]
the bad filter is:
`||aliexpress.com^*&aff_platform=$popup,3p,domain=~alibaba.com`

which is in Liste FR and also adguard french list

add
`@@||aliexpress.com/$popup,domain=forum.hardware.fr`

**Comment by mapx-** [comment]
and provide here
https://forums.lanik.us/viewtopic.php?f=91&p=158069#p158069

the test link, nobody can guess what's in your mind

**Comment by tistoubapt** [comment]
Yes, it's good

Thanks so much and indicated in the Lanik forum

**Comment by uBlock-user** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/f0b25ffd1f2eee0a2717e38487b2512cd23b9a9c

**Comment by tistoubapt** [comment]
It's good, thanks so much
