### ISSUE TITLE
loadout.tf (again!)

### ISSUE THREAD

**Issue by Tiagoquix** [uBlockOrigin/uAssets#8413]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

``loadout.tf``

### Describe the issue

 

The website was working fine since my last report #8392, but apparently the website owner now has decided that the ad-free experience will only be avaible for Patreon members. If I try to load the site with uBlock enabled, it shows an entire black screen with the text "Advertisement / How to remove it ?". Disabling uBlock makes the website load normally, but an ad is show.

Also, I tried to delete certain elements to remove the black screen covering the website. Fortunately, I could remove the black screen covering the entire website but a vertical bar remained on the right. When I removed the bar, it appared again and again. It spawns infinitely. The bar contains an ad.

### Screenshot(s)

With uBlock enabled:
![image](https://user-images.githubusercontent.com/30274161/103408876-19a3f680-4b43-11eb-949a-6e0382429528.png)

With uBlock disabled:
![image](https://user-images.githubusercontent.com/30274161/103408908-393b1f00-4b43-11eb-81f5-7f17694318ca.png)

The vertical bar on the right cannot be removed. I tried to remove it but like I said, it spawns infinitely.

### Versions

- Browser/version: Google Chrome Version 87.0.4280.88 (Official version) 64 bits
- uBlock Origin version: 1.31.2

### Settings

I use the default settings.

### Notes

No additional notes.

**Comment by Tiagoquix** [comment]
@mapx- Thanks for the fix, but the vertical bar still remains on the site.

![image](https://user-images.githubusercontent.com/30274161/103409508-eca51300-4b45-11eb-8e79-9dbf86418b97.png)

Could you remove it too?
There is a filter to remove the bar in EasyList but the filter doesn't have any effects currently.

The filter present in [EasyList](https://easylist.to/easylist/easylist.txt) is `loadout.tf##.loadout-application-top > custom-panel:last-child`.

**Comment by mapx-** [comment]
Don't open 7777 issues.

Does this work for you ?

`loadout.tf##.adsbygoogle:upward(2)`

**Comment by Tiagoquix** [comment]
> Don't open 7777 issues.
> 
> Does this work for you ?
> 
> `loadout.tf##.adsbygoogle:upward(2)`

Sorry for the inconvenience, I opened another issue because I thought you wouldn't see my comment here.

About your filter, it works, but the page flashes black sometimes. The page should probably be trying to create the vertical bar again.

**Comment by uBlock-user** [comment]
> About your filter, it works, but the page flashes black sometimes.

A procedural cosmetic filter has been added, so that will happen.

**Comment by Tiagoquix** [comment]
> > About your filter, it works, but the page flashes black sometimes.
> 
> A procedural cosmetic filter has been added, so that will happen.

All right, but, there is not a workaround for the black flashes?

If not, then please add the mapx-'s filter in some uBlock list or in EasyList.

**Comment by Tiagoquix** [comment]
And, since this filter (`loadout.tf##.loadout-application-top > custom-panel:last-child`) does apparently nothing, it should be removed from EasyList.

**Comment by uBlock-user** [comment]
> All right, but, there is not a workaround for the black flashes?

Don't use a procedural filter and add a plain cosmetic filter for yourself ?

**Comment by Tiagoquix** [comment]
An update about this issue:

The page is literally unusable.

![image](https://user-images.githubusercontent.com/30274161/103431430-5e18ac00-4bae-11eb-8098-2ac209422b49.png)

The page tries to create a new vertical bar every time the old is removed. This lags the page so hard that it becomes unusable.

@uBlock-user

**Comment by uBlock-user** [comment]
Intentionally done by the site admin as a counter against the filter. I don't get any lag though.

**Comment by Tiagoquix** [comment]
> Intentionally done by the site admin as a counter against the filter. I don't get any lag though.

There isn't a workaround to this?

About the lag, you will only feel it if you try to load some character on the site.  If the character's animation feels a little slow, it means you are experiencing lag. In my case, through the Inspect Element the "warnings" (orange triangle on Google Chrome) were being spammed all the time.

**Comment by mapx-** [comment]
I removed `loadout.tf##.adsbygoogle:upward(2)`

**Comment by uBlock-user** [comment]
> There isn't a workaround to this?
you can use `loadout.tf##.adsbygoogle:upward(2):style(left-3000px !important;position:absolute !important)`

**Comment by Tiagoquix** [comment]
> > There isn't a workaround to this?
> 
> you can use `loadout.tf##.adsbygoogle:upward(2):style(left-3000px !important;position:absolute !important)`

Thanks! This filter works absolutely fine. Please, add it to the global uBlock's list.
