### ISSUE TITLE
dubisthalle.de ads

### ISSUE THREAD

**Issue by slaeprop** [uBlockOrigin/uAssets#8415]
`https://dubisthalle.de/gruppierung-zieht-durch-halle-mann-im-suedpark-niedergestochen-koerperverletzung-auf-dem-marktplatz`

Firefox 84.0.1 (64-Bit)
uBlock Origin 1.32.2

**Comment by mapx-** [comment]
add

`dubisthalle.de##.dbh-widget.widget`

@monzta
@ryanbr

**Comment by slaeprop** [comment]
> 
> 
> add
> 
> `dubisthalle.de##.dbh-widget.widget`
> 
> @monzta
> @ryanbr

still not fixed

**Comment by mapx-** [comment]
try reporting again here:
https://github.com/easylist/easylistgermany/issues
