### ISSUE TITLE
Page broken: https://www.ileak.xyz/

### ISSUE THREAD

**Issue by Talented-X-Coder-X** [uBlockOrigin/uAssets#8416]
### URL(s) where the issue occurs

`https://www.ileak.xyz`

### Describe the issue

Pictures are not showing. 

### Screenshot(s)

<
![image](https://user-images.githubusercontent.com/76836980/103456815-ac57b780-4d34-11eb-9232-9005437e8fa8.png)
>

### Versions

- Browser/version: [Latest Chrome]
- uBlock Origin version: [Latest uBlock Origin]

### Settings

All filters checked which are installed by default when uBlock Origin first downloaded. 
-

**Comment by mapx-** [comment]
After installing uBO you have to update all lists:

- dashboard, filters list tab, click `purge all caches`, click `update now`

**Comment by Talented-X-Coder-X** [comment]
> After installing uBO you have to update all lists:
> 
> * dashboard, filters list tab, click `purge all caches`, click `update now`

I did, no difference.

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled.

**Comment by mapx-** [comment]
open the logger, refresh the page, see (select) only what items are blocked, post here the screenshot

**Comment by Talented-X-Coder-X** [comment]
> open the logger, refresh the page, see (select) only what items are blocked, post here the screenshot

Seems like it's working now. Thanks.
