### ISSUE TITLE
playing videos with delays on MSN.com with uBO turned on

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#842]
#### URL(s) where the issue occurs

`https://www.msn.com/en-us/news/travelarticle/timelapse-shows-piloting-filming-over-iran/vi-BBF1HrF`

#### Describe the issue

Video starts playing with a delay (after few minutes) when uBO is on. And when uBO is not running, video starts playing instantly.

#### Versions

- Browser/version: 62.0.3202.94 (Official Build) (64-bit)
- uBlock Origin version: 1.14.18

#### Notes

I tried to define rules based on following rule (playing with different words included in inline script), but I was unsuccessful. I'd be thankful if you let me know how you determine parameters in parenthesis (XXX).

`msn.com##script:inject(abort-on-property-read.js, XXX)`

Do you read and analyze whole the scripts in page? or get help from uBO on detecting some keywords?

**Comment by okiehsch** [comment]
Does
````
@@||fwmrm.net/*/AdManager.js$script,domain=msn.com
@@||fwmrm.net/ad/*$script,domain=msn.com
||msavideo-a.akamaihd.net^$media,redirect=noopmp3-0.1s,domain=msn.com
````
work for you?

**Comment by nimasaj** [comment]
Yes, thanks 👍

**Comment by ghajini** [comment]
`https://www.msn.com/en-in/video/entertainment/big-b-and-everest-spices-served-notices-regarding-new-commercial/vi-BBPcD8W?ocid=spartandhp`
video player not showing here with ublock turned on
@mapx-

**Comment by kulfoon** [comment]
`...,msn.com,...##[style*="background-image:"]` from EasyList is causing it
