### ISSUE TITLE
Pop-Ups (Right and left side of the page)

### ISSUE THREAD

**Issue by Talented-X-Coder-X** [uBlockOrigin/uAssets#8421]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

dizigang.com

### Describe the issue

When the right or left side is clicked, pops up to a new website. Some kind of annoyance.

### Versions

- Browser/version: [Latest]
- uBlock Origin version: [Latest]

### Settings

All filters checked which are installed by default when uBlock Origin first added.
-

**Comment by mapx-** [comment]
add

`dizigang.com##[href^="https://media.tebanner.com/redirect.aspx"]`

for adguard turkish list => @Alex-302
