### ISSUE TITLE
Ads, Anti-AdBlock message

### ISSUE THREAD

**Issue by wout-codes** [uBlockOrigin/uAssets#8422]
### URL(s) where the issue occurs

`https://www.bolec.info/index.php`

### Describe the issue

Like no filter lists works in this website. Please fix. 

### Versions

- Browser/version: [Latest Version]
- uBlock Origin version: [1.31.2]

### Settings

All Filters checked. 
-

**Comment by uBlock-user** [comment]
> All Filters checked.

Test on default settings + all other extensions disabled. A generic fix already is present in uBlock Filters.

**Comment by wout-codes** [comment]
Seems to block cookie notices and anti adblock. Can't block the ads still. Maybe you can update the filter list.

**Comment by uBlock-user** [comment]
Ads are already blocked in Polish lists, activate those if they're not already.

**Comment by krystian3w** [comment]
Maybe this is invalid: https://github.com/uBlockOrigin/uAssets/blob/2065abf5b2cb9c4552d9c2c1a1fc4315a77c37d3/filters/filters.txt#L21142-L21150

If he see anti-adblock.
