### ISSUE TITLE
Filter ##.slick-track incorrect, this is not ad, used in many sites and is a slide class

### ISSUE THREAD

**Issue by JorisvanW** [uBlockOrigin/uAssets#8424]
Slick Slider (https://kenwheeler.github.io/slick/)  is a wide used slider and had a class .slick-track, this not for tracking but a class used in the slider.

This is now blocked....

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ee9d294a2d6898b70be54801cf7f5cc9c543d8c4

force update uBlock Filters.

**Comment by JorisvanW** [comment]
@uBlock-user is here a doc how to do? So our customers can follow this, our dashboard (like Disney+) uses Slick Slider....

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now
