### ISSUE TITLE
Breakage problem on iFate.com

### ISSUE THREAD

**Issue by Bangkokian** [uBlockOrigin/uAssets#8425]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://www.ifate.com/free-tarot.html`
`https://www.ifate.com/runes.html`

### Describe the issue
The main slider on the page is getting blocked, preventing the main js application from working.

 

### Screenshot(s)

`https://imgur.com/a/ybPFSfj`

### Versions

- Browser/version: [Chrome MacOS Version 87.0.4280.88 (Official Build) (x86_64)]
- uBlock Origin version: [1.31.2]

### Settings

- (None)

### Notes

It looks like the issue is a global filter of the slick-slider javascript widget?

**Comment by uBlock-user** [comment]
force update uBlock Filters list.
