### ISSUE TITLE
Slick carousel not working with uBlock origin 

### ISSUE THREAD

**Issue by grialexandru** [uBlockOrigin/uAssets#8427]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

    https://kenwheeler.github.io/slick/

### Describe the issue

Slick carousel does not work anymore with uBO enabled on chrome 87

### Screenshot(s)

![Screenshot 2021-01-05 at 11 11 25](https://user-images.githubusercontent.com/49556786/103627866-dc76a480-4f46-11eb-899e-0331703bde33.png)
![Screenshot 2021-01-05 at 11 11 36](https://user-images.githubusercontent.com/49556786/103627882-e00a2b80-4f46-11eb-94c1-f515caac821d.png)

### Versions

- Browser/version: [Chrome 87]
- uBlock Origin version: [1.31.2]

### Settings

-

**Comment by grialexandru** [comment]
closing this to post in apropiate location

**Comment by mapx-** [comment]
update uBlock filters list then test again

**Comment by grialexandru** [comment]
> update `uBlock filters list` then test again

Worked thanks ;). I will close this issue
