### ISSUE TITLE
Facebook - Fail to open notification. Need to disable ublock to fix it.

### ISSUE THREAD

**Issue by DjDiabolik** [uBlockOrigin/uAssets#8431]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
Facebook.com

### Describe the issue
Very often when I open facebook.com from my pc i see the number how the active notification need to read.
I click on it but the list it's not correctly opened....... i obtain a white empty list.

For fix it i need to disable ublock origin and refresh the page. It's apparently need to do this one time because after that i can reactivate ublock origin and all back to works normally.

### Screenshot(s)

![immagine](https://user-images.githubusercontent.com/9040397/103771063-5716f100-5027-11eb-9603-ee67ae61b956.png)

### Versions

- Browser/version: Firefox 64bit 84.0.1
- uBlock Origin version: 1.32.4

### Settings

Nothings... this is the default setting whit all default list activated:

### Notes

Nothings to add at moment....

**Comment by uBlock-user** [comment]
force update uBlock Filters list and report back.

**Comment by DjDiabolik** [comment]
Oh ok... wait a moment......

**Comment by DjDiabolik** [comment]
OMG.. now it's loaded correctly. why did this happen? It's somethings like cache broken/corrupted for example after a component or browser update himself ?

**Comment by uBlock-user** [comment]
`##.slick-track` might have been causing this, as a result remedial action was taken by make it specific to domains.

**Comment by DjDiabolik** [comment]
Oh ok...... thanks for support that. I hope I have not disturbed too much 👍
