### ISSUE TITLE
Streameast.live detecting uBlock Origin

### ISSUE THREAD

**Issue by emcai** [uBlockOrigin/uAssets#8432]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### Versions

- Browser/version: Google Chrome 87.0.4280.88
- uBlock Origin version: 1.31.2

### Settings

-

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/cdfb21fbc967112e1d156ae8cf797b0aea208924

force update uBlock Filters list if you haven't already.

**Comment by emcai** [comment]
Thank you!
