### ISSUE TITLE
loadout.tf advertisement text

### ISSUE THREAD

**Issue by Tiagoquix** [uBlockOrigin/uAssets#8433]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

``loadout.tf``

### Describe the issue

 

Sometimes, when loading the website, the text

```
Advertisement
How to remove it ?
```

remains on the page.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/30274161/103964001-24f5b400-5139-11eb-96bd-54e798e25101.png)

### Versions

- Browser/version: Google Chrome Version 87.0.4280.141 (Official version) 64 bits
- uBlock Origin version: 1.31.2

### Settings

I use the default settings.

### Notes

Apparently, removing the elements `#advertisement` and `#how_to_remove` seem to fix the issue:

![image](https://user-images.githubusercontent.com/30274161/103964335-f4624a00-5139-11eb-8c0a-f566c01c2592.png)

Using **Delete element**:
![image](https://user-images.githubusercontent.com/30274161/103964260-c8df5f80-5139-11eb-882e-dda07a5d36f8.png)

Do not try to remove the `loadout-application-advertisement-header`, since removing it will cause the page to clone it infinitely.

**Comment by uBlock-user** [comment]
`loadout.tf##.loadout-application-advertisement-header:style(position:absolute!important;left:-3000px !important)` does that work for you ?

**Comment by Tiagoquix** [comment]
@uBlock-user You are more likely to be able to reproduce it if you let the page to be loaded in the background. Does not happen always.

About the filter: apparently yes. I tried loading the page several times and the advertisement text didn't come back.

**Comment by uBlock-user** [comment]
Does this happen on Firefox too ?

**Comment by Tiagoquix** [comment]
> Does this happen on Firefox too ?

I do not know, I do not use Firefox.

**Comment by uBlock-user** [comment]
> You are more likely to be able to reproduce it if you let the page to be loaded in the background. Does not happen always.

Tried it numerous times, no change.

> Do not try to remove the loadout-application-advertisement-header, since removing it will cause the page to clone it infinitely.

I don't see any issue with `loadout.tf##.loadout-application-advertisement-header`

**Comment by Tiagoquix** [comment]
> Tried it numerous times, no change.

Well, here it happens frequently to be honest.

> I don't see any issue with `loadout.tf##.loadout-application-advertisement-header`

If you use `Delete element` on it, it will get deleted but also it will clone itself infinitely. This lags the page.
The filter you gave to me is working fine. Maybe not many people have the same issue.

**Comment by uBlock-user** [comment]
Why do you want to delete it ? `loadout.tf##.loadout-application-advertisement-header` hides the CSS selector, so no issue.

**Comment by Tiagoquix** [comment]
Your new fix seems to be working fine. Thanks!
