### ISSUE TITLE
infomercado.pe

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#8436]
### URL(s) where the issue occurs

`https://infomercado.pe/category/emprendimientos/`

### Describe the issue
Overlay when you move the mouse cursor to another tab.

### Screenshot(s)

![overlay](https://user-images.githubusercontent.com/35470489/104041939-8c9f1400-51b8-11eb-9ff2-d02418dddea2.png)

### Versions

- Browser/version: Firefox stable
- uBlock Origin version: 1.32.4

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin lists

**Comment by uBlock-user** [comment]
fixed in Fanboy Annoyances with `/plugins/wordpress-popup/*$script`
