### ISSUE TITLE
Unable to login to Discovery+ website

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uAssets#8439]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] Using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.discoveryplus.it/myaccount/login`

### Describe the issue

When I enter the credentials and click on the "Accedi" button in the specified URL, the website remains stuck in the login screen rather than redirecting me to the home page.

### Screenshot(s)

![immagine](https://user-images.githubusercontent.com/62190484/104105070-05cb6380-52ac-11eb-911b-114e5dc8b2e7.png)

### Versions

- Browser/version: Firefox 84.0.2
- uBlock Origin version: 1.32.4

### Settings

- Prevent WebRTC from leaking local IP address
- Block CSP reports

### Notes

Nothing else.

**Comment by mapx-** [comment]
Open uBO logger, go to `discoveryplus` logging page and repeat the steps above to reproduce the issue.
In the logger select **only** the blocked items and post here the screenshot(s) with those entries

**Comment by fabriziobagala** [comment]
<img width="1552" alt="immagine" src="https://user-images.githubusercontent.com/62190484/104105408-285e7c00-52ae-11eb-9831-bc2bb4a5348a.png">

**Comment by mapx-** [comment]
test this filter

`@@||identity.mparticle.com^$xmlhttprequest,domain=discoveryplus.*`

**Comment by fabriziobagala** [comment]
With this filter, the issue no longer occurs
