### ISSUE TITLE
4chan-x Greasemonkey Script is broken

### ISSUE THREAD

**Issue by BoBeR182** [uBlockOrigin/uAssets#844]
### URL(s) where the issue occurs

`[https://boards.4chan.org/g/thread/63409935#p63414862]`

### Describe the issue

[https://boards.4chan.org/g/thread/63409935#p63414862]

### Versions

- Browser/version: [46.0.2]
- uBlock Origin version: [1.14.18]

### Settings

- [none]

### Notes

[Here is the fix https://boards.4chan.org/g/thread/63409935#p63414862]
New Greasemonkey is backwards incompatible, which broke existing scripts.
https://www.greasespot.net/2017/09/greasemonkey-4-for-users.html

Tampermonkey works but it has analytics built-in, not really liking that.

Violentmonkey also works but some ublock filters can interfere with it on 4chan-x, putting on

@@||4chan.org^*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'

on custom ublock filters solves it.

**Comment by mapx-** [comment]
Which is the issue ? (the thread on 4chan has been deleted)
