### ISSUE TITLE
HDblog with wrong background

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uAssets#8440]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.hdblog.it/`

### Describe the issue

The background of the website is all white.

### Screenshot(s)

<img width="1552" alt="immagine" src="https://user-images.githubusercontent.com/62190484/104105800-103c2c00-52b1-11eb-84ec-02ccb6e067a9.png">

### Versions

- Browser/version: Firefox 84.0.2
- uBlock Origin version: 1.32.4

### Settings

- Prevent WebRTC from leaking local IP address
- Block CSP reports

### Notes

If I turn off the website's cosmetic filtering, I get the correct background color.

**Comment by mapx-** [comment]
test

```
hdblog.it#@#body:style(background: none !important; overflow: auto !important;)
hdblog.it##.ads_container_top
hdblog.it#@#+js(no-setTimeout-if, CANG, 3000)
hdblog.it#@#+js(no-setInterval-if, (), 1000)
```

**Comment by fabriziobagala** [comment]
Works 💪
