### ISSUE TITLE
Space issues on LinkedIn

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uAssets#8441]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.linkedin.com/feed/`

### Describe the issue

There is no space between the header and the body of the page.

### Screenshot(s)

- Issue

![immagine](https://user-images.githubusercontent.com/62190484/104121227-efb9b380-533c-11eb-855c-cde4556d452c.png)

- uBlock Origin logger

<img width="1552" alt="immagine" src="https://user-images.githubusercontent.com/62190484/104121229-f5af9480-533c-11eb-8087-4ae9415c6edd.png">

### Versions

- Browser/version: Firefox 84.0.2
- uBlock Origin version: 1.32.4

### Settings

- Prevent WebRTC from leaking local IP address
- Block CSP reports

### Notes

Removing the cosmetic filters does not cause the problem, but the ad banner appears. I think the best solution is to hide the container of the advertising banner. For example:

```html
<main id="ads-container" class="..." role="presentation" style="display: none;">
...
</main>
```

**Comment by mapx-** [comment]
- it's the place where the ads were removed
- so, add this exception as custom filter
`linkedin.com#@#.ad-banner-container`

**Comment by fabriziobagala** [comment]
I think visually it's better than before. What do you think about it @mapx-?

![immagine](https://user-images.githubusercontent.com/62190484/104121566-91420480-533f-11eb-9990-581a46467d70.png)

**Comment by mapx-** [comment]
De gustibus non est disputandum

**Comment by fabriziobagala** [comment]
😂 good answer

**Comment by uBlock-user** [comment]
consequence of blocking ad banner, not an issue.
