### ISSUE TITLE
Anti Adblock on hindustantimes.com

### ISSUE THREAD

**Issue by skarthik345** [uBlockOrigin/uAssets#8445]
Screenshot:
![image](https://user-images.githubusercontent.com/6513090/104130553-f7765980-5336-11eb-8b78-841794587269.png)

Steps to reproduce:
1. Open link "(https://www.hindustantimes.com/india-news/slave-of-your-own-greed-kangana-ranaut-s-salvo-at-twitter-ceo-jack-dorsey-101610245791865.html)"
2. Scroll down a bit.
3. Wait 10 seconds.

Other details:
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] I am running the latest version of uBlock Origin

### Versions

- Browser/version: Edge/Version 87.0.664.75 (Official build) (64-bit)
- uBlock Origin version: uBlock Origin v1.32.4

**Comment by uBlock-user** [comment]
force update uBlock Filters list, fixed yesterday.

**Comment by skarthik345** [comment]
Can confirm working after updating filter lists. Hence closing issue.
Thank you!
