### ISSUE TITLE
reuters.com: breakage

### ISSUE THREAD

**Issue by Wuffeh** [uBlockOrigin/uAssets#8447]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.reuters.com/video/`

### Describe the issue

The video will not play unless the website "cookielaw.org" is allowed by overriding the filter lists. Without this override, the video will not play. (This workaround may be exposing users to tracking, I do not know.)

 

### Versions

- Browser/version: [84.0.2]
- uBlock Origin version: [1.32.5b9]

### Settings

- Relevant is I enabled additional included lists.

**Comment by okiehsch** [comment]
> Relevant is I enabled additional included lists.

We only add filters for issues reproducable with a default setup.
You can add `@@||cdn.cookielaw.org^$script,domain=reuters.com`
to your filter list to fix the issue on your end.

@ryanbr cookielaw is blocked in `Fanboy's Annoyance List`.

**Comment by PIZZA90** [comment]
`https://www.reuters.com/video/breakingviews`

`@@||imasdk.googleapis.com/js/sdkloader/ima3_debug.js$script,domain=reuters.com`

**Comment by mapx-** [comment]
I need in chrome

```
@@||cdn.segment.com/analytics.js/*/analytics.min.js$script,domain=reuters.com
@@||imasdk.googleapis.com/js/sdkloader/ima3_debug.js$script,domain=reuters.com
```

**Comment by okiehsch** [comment]
Hm, I don't.
![image](https://user-images.githubusercontent.com/16838044/159944417-f22a0ff3-6c38-4bac-90aa-8f3b33fa3b35.png)

**Comment by mapx-** [comment]
I notified @ryanbr let's see if he needs it

**Comment by mraonea** [comment]
Videos in articles broken again with default lists

**Comment by mapx-** [comment]
> Videos in articles broken again with default lists

provide an example page

**Comment by okiehsch** [comment]
> is broken for me too
`https://www.reuters.com/world/uk/harry-give-evidence-uk-lawsuit-against-tabloid-publisher-2023-06-05/`



The videos under the article play fine on my end.

**Comment by okiehsch** [comment]
Ok. I can reproduce.

**Comment by okiehsch** [comment]
Does adding
`@@||api.permutive.com/v2.0/*$xhr,domain=reuters.com`
work for you?
