### ISSUE TITLE
Block one specific thing on an site

### ISSUE THREAD

**Issue by TheHacki** [uBlockOrigin/uAssets#845]
**Describe the issue**

Hello there,(I hope this is the right section) I have an issue with an ad, which dosen't go away, even if i blocked it directly
The ad appears at every video even with specific filters, what am I doing wrong?
**One or more specific URLs where the issue occurs**

watchbox.de
almost every video
Direct link to one video(random):
https://www.watchbox.de/filme/boulevard-15365.html
**Steps for anyone to reproduce the issue**

I open a video, normally, it appears ads.
Then i tried to block them manually without blocking the whole server because then the video doesn't load (ssl.*.damoh.watchbox.de)
**Your settings**

I don't have many specific setting, the only thing I edited was
-blocking local IP Adress with WebRTC

    OS/version: Linux Solus MATE 1.18.2
    Browser/version: Firefox 57.0 (64 bit)
    uBlock Origin version: uBlock 1.14.18

**Your filter lists**

Default filter list
**Your custom filters (if any)**

ssl..damoh.watchbox.de^$mp4
||ssl..damoh.watchbox.de^$mp4
https://ssl.*.damoh.watchbox.de^$mp4
||https://ssl.*.damoh.watchbox.de^$mp4
http://ssl.*.damoh.watchbox.de^$mp4
||http://ssl.*.damoh.watchbox.de^$mp4

Please tell me, what am I doing wrong if you have enough time for my problem
Thanks a lot
TheHacki

**Comment by uBlock-user** [comment]
Does `||damoh.*$media` work ?

**Comment by TheHacki** [comment]
Seems to work, thank you

**Comment by TheHacki** [comment]
What happend now actually:
The filter had worked, but now they had upgraded their site:
If you now use the filter, it still block the ads, but after that it just stop/close the video player
Media:
[https://imgur.com/a/PfAJn](url)
[http://gph.is/2iGBuax](url)

Have anyone an solution for that problem?
Thank you
TheHacki

//Movie in the video/example link to the page
[https://www.watchbox.de/filme/scrooge-15497.html](url)

**Comment by SMed79** [comment]
> DIESES VIDEO IST IN DEINEM LAND NICHT VERFÜGBAR.
* http://i.imgur.com/KRjPQc9.png

blind test this filter:
```
/global_config.json^$xmlhttprequest,redirect=nooptext,domain=vgtv.no
```

**Comment by mapx-** [comment]
it seems xmlhttprequest redirects don't work in FF 57

**Comment by TheHacki** [comment]
First, thank you for you answers @SMed79 and @mapx- ,
I think the video doesn't load, because it is an german website,
I testet the filter you wrote 

> /global_config.json^$xmlhttprequest,redirect=nooptext,domain=watchbox.de

But sadly it didn't worked,  I hope, that anybody will fand a solution, and I will test it myself of course.
Is there any other option for `xmlhttpprequest`?

**Comment by mapx-** [comment]
I was able (using socks 5 poxy) to test 2 movies, no ads here.

**Comment by TheHacki** [comment]
@mapx- Yeah, they have an special system to get people on the site:
First they don't show you ads, but then they will start one day.
I think the system is built on cookies etc, not on an IP list(at least not complete), but I am not sure.
