### ISSUE TITLE
assets of our WGACT WooCommerce plugin get blocked

### ISSUE THREAD

**Issue by alewolf** [uBlockOrigin/uAssets#8450]
### Prerequisites

- [yes] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [yes] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [yes] I tried to reproduce the issue when...
    - [yes] uBlock Origin is the only extension
    - [yes] uBlock Origin with default lists/settings
    - [yes] using a new, unmodified browser profile
- [yes] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

This is a local server. (The issue happens in the backend of WooCommerce installations)

WooCommerce plugin admin area:
`https://wordpress.test/wp-admin/admin.php?page=wgact&section=main&subsection=google-ads`

Files that get blocked (I probably didn't catch all files)
`https://wordpress.test/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/js/admin/tabs.js?ver=1.7.6`
`https://wordpress.test/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/js/admin/helpers.js?ver=1.7.6`
`https://wordpress.test/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/js/admin/ask-for-rating.js?ver=1.7.6`
`https://wordpress.test/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/css/admin.css?ver=1.7.6`
`https://wordpress.test/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/freemius/assets/css/admin/common.css?ver=5.6`

### Describe the issue

 

Our WooCommerce plugin injects Google Ads tracking pixels in order to track if ads successfully triggered a conversion on the shop. (link to our plugin: https://wordpress.org/plugins/woocommerce-google-adwords-conversion-tracking-tag/)

Because of this functionality our plugin files have been added to a privacy filter list, which is why uBlock is blocking them for uBlock users. 

That is ok for users of the front end of a WooCommerce shop. 

But, we have at least one WooCommerce shop owner who is experiencing issues in the backend of his shop. All the admin scripts and files get blocked in the back end too. 

All of the affected files I found use "admin" somewhere in the URL path and they all get only loaded for admins of the shop, not in the front end. 

Is there a way to exclude those files from blocking? 

### Versions

- Browser/version: [87.0.4280.88]
- uBlock Origin version: [1.32.4]

### Settings

-

**Comment by okiehsch** [comment]
> All of the affected files I found use "admin" somewhere in the URL path and they all get only loaded for admins of the shop, not in the front end.

So it's only broken for admins nothing is broken for users of those sites?

> Is there a way to exclude those files from blocking?

It would help to know what filters exactly cause the blocking of those files.
You can open the [logger](https://github.com/gorhill/uBlock/wiki/The-logger) to investigate.

For the files you posted adding
`@@||/wordpress.test/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/*/admin`
to the personal filter lists of the admin should work.

**Comment by alewolf** [comment]
> It would help to know what filters exactly cause the blocking of those files.

![image](https://user-images.githubusercontent.com/7146794/104274013-2fe57700-54a0-11eb-953b-6fed1b2f6492.png)


> For the files you posted adding
@@||wordpress.test/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/*/admin
to the personal filter lists of the admin should work.

Is this something the user of uBlock need to do himself, or can I add this exclusion to my plugin?

**Comment by okiehsch** [comment]
> Is this something the user of uBlock need to do himself, or can I add this exclusion to my plugin?

Every user that has this issue can add that filter to their [personal filter list](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters)

Now as you say that only site admins will encounter this issue I would say if they run an adblocker on the sites that they are maintaining they are responsible for adding the fix themselves.
If every user would have this issue we would add my suggested filter to our own list which every uBO-user would receive via auto-update.

@gorhill what do you think should we add the fix to `uBO-unbreak` even though it only concerns site admins?

**Comment by okiehsch** [comment]
Alternatively they - site admins - could simply [whitelist](https://github.com/gorhill/uBlock/wiki/Dashboard:-Trusted-sites)  `wordpress.test`.

**Comment by alewolf** [comment]
> Every user that has this issue can add that filter to their personal filter list

I already suggested this to the user who reported this issue to me. 

But the problem is also, that many others who just run into the issue  give us bad ratings for the plugin, because they think it is broken. Others simply stop using our plugin.

So I would appreciate if you could install that filter exclusion globally. 

If you do so, you need to adjust the filter slightly, not to include the server, because the plugin is installed on many different servers.

**Comment by okiehsch** [comment]
> But the problem is also, that many others who run into the issue just give us bad ratings for the plugin, because they think it is broken. Others simply stop using our plugin.


That is a fair point imo, I will add 
`@@/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/*/admin/*$1p`
for now.

**Comment by alewolf** [comment]
Thanks!

How do I update my local uBlock in order to see if the fix works?

**Comment by okiehsch** [comment]
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now

I just added the filter to `uBO-unbreak` you will have to wait approximately 5 minutes after the commit before updating will include it.

**Comment by alewolf** [comment]
It works partially now. 

This CSS file still gets blocked:

`/wp-content/plugins/woocommerce-google-adwords-conversion-tracking-tag/css/admin.css`

Could you exclude CSS files too?

**Comment by okiehsch** [comment]
Done.

**Comment by alewolf** [comment]
I can confirm it works perfectly now. Thanks a lot !
