### ISSUE TITLE
ayehosting.online

### ISSUE THREAD

**Issue by etpjhwpknwk** [uBlockOrigin/uAssets#8453]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`ayehosting.online`

### Describe the issue
Malicious host, suspected phishing, not blocked by uBO
 

### Screenshot(s)
https://i.imgur.com/ces0Kpb.png

### Versions

- Browser/version: Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.32.4

### Settings

- Default uBO settings

**Comment by mapx-** [comment]
To get that domain you visited some page. Which one ?

**Comment by etpjhwpknwk** [comment]
> To get that domain you visited some page. Which one ?

I visited the domain directly.

**Comment by Yuki2718** [comment]
`ayehosting.online` is dead. I'll remove it.
