### ISSUE TITLE
PCH.com (Publisher's Clearing House) 

### ISSUE THREAD

**Issue by leodoi3** [uBlockOrigin/uAssets#8456]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

https://www.pch.com/

### Describe the issue

1. I cannot login when uBlock is enabled. 
2. Many elements are incorrectly labeled as an ad
3. Most of the site functionality is broken and buttons don't do anything. 
4. Pages where sponsored videos are displayed are supposed to redirect after video finishes playing. 

### Screenshot(s)
Homepage - uBlock disabled:
![1](https://user-images.githubusercontent.com/46114199/104400389-a7062400-550f-11eb-9ad3-229ba096a6a6.png)
Homepage - uBlock enabled:
![1a](https://user-images.githubusercontent.com/46114199/104400432-b71e0380-550f-11eb-9ad9-1694e9f1aa4c.png)

Homepage (logged out) - uBlock disabled:
![image](https://user-images.githubusercontent.com/46114199/104412602-d3c73500-5529-11eb-8697-37ab23f334d7.png)

Homepage (logged out) - uBlock enabled:
![image](https://user-images.githubusercontent.com/46114199/104412568-c316bf00-5529-11eb-8232-4575c125b81d.png)

Sponsored message- uBlock disabled:
![3](https://user-images.githubusercontent.com/46114199/104400460-c00ed500-550f-11eb-98dd-f9a75c49273b.png)

Sponsored message- uBlock enabled
![4](https://user-images.githubusercontent.com/46114199/104400470-c43af280-550f-11eb-9c56-86d9637159c7.png)

:

### Versions

- Browser/version: FF 84.0.1
- uBlock Origin version: 1.32.4

### Settings

-
![image](https://user-images.githubusercontent.com/46114199/104400649-06643400-5510-11eb-8316-a6f44f4eb78d.png)
![image](https://user-images.githubusercontent.com/46114199/104400671-0d8b4200-5510-11eb-9833-7c8a1416040f.png)

**Comment by uBlock-user** [comment]
You have enabled filter lists which are not enabled by default, test on default settings.

**Comment by leodoi3** [comment]
Tried it with the default lists as well, same behavior.

**Comment by uBlock-user** [comment]
Add `@@||pch.com^$cname` and report back.

**Comment by leodoi3** [comment]
That seemed to do the trick. Looks like most of the functionality is working . I will continue to keep testing it.
