### ISSUE TITLE
NSFW totv.org { Antiadblock }

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8461]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### Describe the issue

Antiadblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/20338483/104423356-feee6a80-55a3-11eb-99f8-40a7bbc8674c.png)

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.32.5b10

### Settings

uBO's default settings
-

**Comment by mapx-** [comment]
maybe 
`@@||google-analytics.com/analytics.js$script,domain=totv.org`

"maybe" because no channel is really working ?!
for example:

`http://totv.org/tv-al-jazeera`

**Comment by ghajini** [comment]
sorry i forgot to paste nsfw link,wait i will see

**Comment by uBlock-user** [comment]
> "maybe" because no channel is really working ?!

`totv.org###ad`

**Comment by mapx-** [comment]
yes, that channel is working fine using `totv.org###ad`

**Comment by uBlock-user** [comment]
All other channels are also working fine..

**Comment by ghajini** [comment]
this `totv.org###ad` will work

**Comment by uBlock-user** [comment]
I don't see any anti-adblock as you're reporting.

**Comment by ghajini** [comment]
see able to reproduce
`https://i.imgur.com/XUFL95p.gif`

**Comment by uBlock-user** [comment]
Disable Opera's built-in blocker.

**Comment by mapx-** [comment]
it's not about opera, I get the anti adb stuff in chrome

**Comment by ghajini** [comment]
Opera built in blocker is always OFF
