### ISSUE TITLE
NSFW milffox.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8463]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
NSFW
`https://www.milffox.com/porn-movies/Daisy-Gets-Nailed-By-A-Cable-Guy-While-Mom-Is-In-Other-Room/`

### Describe the issue

POPUP ADS

### Versions

- Browser/version: opera stable
- uBlock Origin version: 1.32.5b10

### Settings

uBO's default settings
-

**Comment by mapx-** [comment]
getting no popup

**Comment by uBlock-user** [comment]
```
milffox.com##.offer
milffox.com##div#side_content:nth-of-type(2)
milffox.com##.signup
||glxmnews.pro^

```

**Comment by uBlock-user** [comment]
`*$3p,script,denyallow=google.com|gstatic.com|cloudflare.com|googleapis.com|recaptcha.net|hcaptcha.com|twitter.com,domain=milffox.com ` for good measure.

**Comment by ghajini** [comment]
yes not reproducing now ,it was there few hours back

**Comment by ghajini** [comment]
Preroll ad
NSFW
`https://www.milffox.com/porn-movies/Red-Haired-Babe-Got-Banged-Good/`

**Comment by mapx-** [comment]
I get no preroll, I get only in android an ad over the video

`milffox.com###el-ab-a`

**Comment by ghajini** [comment]
Like "ads by clickaine" ,skip in 5s?

**Comment by mapx-** [comment]
No such ads on my side
