### ISSUE TITLE
vanillaprepaid.com

### ISSUE THREAD

**Issue by IoanPaleru** [uBlockOrigin/uAssets#8465]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

vanillaprepaid.com

### Describe the issue

When you enter your credit card information and try to sign in to check your account balance on vanillaprepaid.com with ublock origin enabled, it shows an error message at the top of the page that says "A system error has occurred. Please try again later.", but when you disable ublock origin and then log in, it shows you the normal google recaptcha and then logs you in properly. Is there a way to fix that? Thank you and have a nice day.

### Screenshot(s)

![a system error has occurred](https://user-images.githubusercontent.com/35790889/104498385-9b673b80-55a9-11eb-88a2-a17368325f21.jpg)

### Versions

- Chrome 87.0.4280.141 (Official Build) (64-bit)
- uBlock Origin 1.32.4

### Settings

-

**Comment by mapx-** [comment]
Open uBO logger, repeat the steps above to reproduce the issue.
In the logger **select only the blocked items** and post here the **screenshot**(s) with those entries

**Comment by mapx-** [comment]
I tested with fake data and I get the error message even whitelisting the page

**Comment by uBlock-user** [comment]
same as https://www.reddit.com/r/uBlockOrigin/comments/ktyjup/onevanillacom_broken/

Site is broken.
