### ISSUE TITLE
cybermania.ws — Ad Block Popup

### ISSUE THREAD

**Issue by doio** [uBlockOrigin/uAssets#8467]
### Prerequisites

- [  √ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ √ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [  √ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ √] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.cybermania.ws/`

### Describe the issue

A popup "Please Disable AdBlocker" will show shortly after the page is loaded.

### Versions

- Browser/version: Firefox 84.0.2 (64-bit)
- uBlock Origin version: v1.32.5b10

### Settings

-

**Comment by doio** [comment]
This site updated its adblock and the rule is no longer working.

**Comment by exodius48** [comment]
Adblock detected again @uBlock-user @okiehsch @mapx-

**Comment by exodius48** [comment]
Adblock detected again @okiehsch

**Comment by What-Zit-Tooya** [comment]
Adblock detected again @uBlock-user @okiehsch @mapx-

**Comment by Trum00thay** [comment]
Adblock detected again
