### ISSUE TITLE
dizi5.plus wont work if ublock origin is enabled

### ISSUE THREAD

**Issue by muhasturk** [uBlockOrigin/uAssets#8473]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
Video never starts on `dizi5.plus`

### A specific URL where the issue occurs
`https://dizi5.plus/dizi/iste-bu-benim-masalim/sezon-1/bolum-2`

### Steps to Reproduce

1. Open following url or any other video page on domain which contains series
`https://dizi5.plus/dizi/iste-bu-benim-masalim/sezon-1/bolum-2`
2. Press start button on player
3. Video never starts if ublock origin enabled
4. If you disable extension by pressing big gear button on extension page and reload site, video starts playing.

### Expected behavior:
Video should be started after ads new tab opened

### Actual behavior:
Video never starts, loading animation spinning forever

### Your environment
* uBlock Origin version:
* 1.32.4

* Browser Name and version:
Microsoft Edge
Version 87.0.664.75 (Official build) (64-bit
* Operating System and version:
Windows 10 Pro 20H2

**Comment by mapx-** [comment]
- no issue on my side, tracking prevention => balanced in edge
- there's a popup on clicking play, add:

`dizi5.plus##[href^="https://www.evobahisaffiliate.com/"]`

**Comment by muhasturk** [comment]
Well I figured out something strange. If I enable both RUS and TUR regional filter, video wont start, however if I disabled RUS regional filter, the site works as expected.

Something on RUS filter cause a problem.

Broken Filter Selection
![image](https://user-images.githubusercontent.com/4077401/104783969-489fa680-5798-11eb-8053-fb49cf508132.png)

Working Filter choice
![image](https://user-images.githubusercontent.com/4077401/104783936-302f8c00-5798-11eb-875b-4a8be796722c.png)

**Comment by mapx-** [comment]
if you keep russian list and add

`@@||image2optimize.xyz/hls/$xhr,domain=flowcdn.nl`

does it work ?

**Comment by muhasturk** [comment]
Yes, now works as expected. Could please give me short explanation why these rule required to work and how is it work?

`@@||image2optimize.xyz/hls/$xhr,domain=flowcdn.nl`

**Comment by mapx-** [comment]
a russian filter si blocking all *.xyz xhr requests and consequence is will break the player

`||xyz^$xmlhttprequest,3p,domain=~anidub.com|~animedia.pro|~animeheaven.ru|~app.element.io|~assistir-filme.biz|~avtomaty-i-bonusy.com|~chelentano.top|~coomeet.com|~crackstreams.com|~crackstreams.ga|~csgoreports.com|~cvid.kiev.ua|~estream.to|~europixhd.io|~films.hds-stream.com|~funtik.tv|~getvi.tv|~hanime.tv|~hentaiz.org|~herokuapp.com|~infoua.biz|~jokehd.com|~jokerswidget.com|~kinobig.me|~kinoguru.be|~kinoguru.me|~kristinita.ru|~live-golf.stream|~lookbase.xyz|~magicfilm.net|~mail.google.com|~map-a-date.cc|~matchat.online|~mikeamigorein.xyz|~miranimbus.ru|~my.mail.ru|~nccg.ru|~newdeaf.club|~newdmn.icu|~onmovies.se|~playjoke.xyz|~roadhub.ru|~roblox.com|~sextop.net|~soccer365.ru|~soonwalk.net|~sportsbay.org|~streetbee.io|~streetbee.ru|~telerium.club|~telerium.live|~uacycling.info|~uploadedpremiumlink.net|~vk.com|~vmeste.tv|~web.app`

**Comment by mapx-** [comment]
I've notified russian list maintainer, we'll see if he is willing to fix it

**Comment by muhasturk** [comment]
Thank you for your help. Can we  add following rule to turkish list? Should I sent PR to Adguard?
`dizi5.plus##[href^="https://www.evobahisaffiliate.com/"]`

https://github.com/AdguardTeam/AdguardFilters/tree/master/TurkishFilter

**Comment by mapx-** [comment]
yeah, report to adguard

However, it seems you need:

`@@*/hls/$xhr,domain=flowcdn.nl`

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/65c13e3724df105059c2e3be03ba9b8af6d0941f
