### ISSUE TITLE
bittools.net

### ISSUE THREAD

**Issue by AndnixSH** [uBlockOrigin/uAssets#8477]
### Prerequisites

- [x] This is not a support issue or a question (PS. I'm not sure if this request is count as question, if so I won't do it again)
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.bittools.net/mining-code`

### Describe the issue

This has 30 sec of countdown.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/40742924/104823091-cec6f600-5847-11eb-9a13-c9bf5ef5f218.png)

### Versions

- Browser/version: Chrome Version 87.0.4280.141 (Officiel version) (64-bit)
- uBlock Origin version: 1.32.4

### Settings

- Default

**Comment by okiehsch** [comment]
We can boost the timer
`bittools.net##+js(nano-sib)`
but the mining code will only show up after some time that is implemented server side.

**Comment by AndnixSH** [comment]
Oh okay, thanks for trying
