### ISSUE TITLE
Spotify Web re-started to pause

### ISSUE THREAD

**Issue by thekillgfx** [uBlockOrigin/uAssets#8478]
### Prerequisites

- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x ] I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [ x] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://open.spotify.com/`

### Describe the issue
The behavior of it is inconstant. Sometimes it plays for an hour before get paused sometimes it only allow 2-3 songs to listen to. Pressing pause icon restarts the cycle.
 

### Versions

- Browser/version: Google Chrome v87.0.4280.141 (Official build) (64 bit)
- uBlock Origin version: [1.32.5b10

**Comment by uBlock-user** [comment]
Site issue, sometimes works, sometimes doesn't.

**Comment by uBlock-user** [comment]
see -- https://github.com/uBlockOrigin/uAssets/issues/8279
