### ISSUE TITLE
EasyPrivacy list is broken again with these site (like livescience, tomshardware,...)

### ISSUE THREAD

**Issue by Trung0246** [uBlockOrigin/uAssets#8479]
Apparently EasyPrivacy list is broken again with these site (like livescience, tomshardware,...).

However, I found the root cause which is this problematic obfuscated inline script:
![image](https://user-images.githubusercontent.com/11626920/104832408-b48c1880-5845-11eb-87a6-56809319d7ea.png)

I tried to write a tampermonkey script to prevent this by using Object.defineProperty but it doesn't work so far honestly (due to I'm being stupid 😅): https://gist.github.com/Trung0246/a2d55cc854acca2bb79adbc359037e9c

Any idea?

_Originally posted by @Trung0246 in https://github.com/uBlockOrigin/uAssets/issues/8079#issuecomment-761739955_

**Comment by uBlock-user** [comment]
How can a list be broken ? Doesn't make sense.

**Comment by Trung0246** [comment]
I don't mean the list is broken, I mean that the filter to block the ads is not work.

**Comment by uBlock-user** [comment]
Be specific, what filter doesn't work ? where do you see ads ? Take screenshots and show it here.

**Comment by uBlock-user** [comment]
EasyList blocks ads, not EasyPrivacy.

**Comment by Trung0246** [comment]
The obfuscated script is an anti-adblock script that will execute `window.location.href = "https://livescience.com/cc.html";` when it's detect adblock. I'm not really sure if it came from EasyPrivacy list or not but seems like it's related:
![image](https://user-images.githubusercontent.com/11626920/104833796-43059780-5850-11eb-85b0-79dc16f99e31.png)
![image](https://user-images.githubusercontent.com/11626920/104833801-5153b380-5850-11eb-8921-87fcf8e6be17.png)

You can test it here: https://www.livescience.com/us-life-expectancy-drop-covid-19.html

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled. Blocking the CDN causes anti-adblock to occur, this has already been addressed numerous other times.

**Comment by Trung0246** [comment]
Seems like reset to default settings will also trigger the "AD BLOCKER INTERFERENCE DETECTED" screen.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7527
https://github.com/uBlockOrigin/uAssets/issues/8030
https://github.com/uBlockOrigin/uAssets/issues/8079

**Comment by uBlock-user** [comment]
You don't need to whitelist anything on default settings fyi.

**Comment by Trung0246** [comment]
Yeah it's just that I'm stupid so no worry 😅

For anyone looking how to fix it due to too much configuration: whitelisting CDN will fix it for me.
![image](https://user-images.githubusercontent.com/11626920/104834337-8281b300-5853-11eb-8ec5-67b990f00a90.png)

**Comment by uBlock-user** [comment]
That's bad, use `noop` instead of `allow`.

**Comment by Trung0246** [comment]
Interesting, seems like putting those rules into "My filter" list and clicking middle gray block for noop rule didn't work (I'm testing local noop rule first right now) ?
![image](https://user-images.githubusercontent.com/11626920/104834552-fec8c600-5854-11eb-80c6-46ad47131a92.png)
![image](https://user-images.githubusercontent.com/11626920/104834578-43ecf800-5855-11eb-8bd0-af7853f267c0.png)

**Comment by uBlock-user** [comment]
Rules go in my rules tab, you really should read the wiki.
