### ISSUE TITLE
digitalspy.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#848]
Anti adblock notice is served on `http://www.digitalspy.com`.

**Error URL:** 
`http://www.digitalspy.com/tv/ustv/feature/a840827/mindhunter-season-2-release-date-cast-plot-netflix/`

_**Note:** Using uBO 1.14.18 on Chrome 62 with the default filters and settings._

**Comment by mapx-** [comment]
try (I cannot reproduce it ...)
`digitalspy.com##script:inject(abort-on-property-write.js, _sp_)`

**Comment by gotitbro** [comment]
@mapx- Thanks for checking. Looks like even I can't reproduce the anti adb notice after I cleared my browser history. But yes the anti adb message was from Sourcepoint.

**Comment by okiehsch** [comment]
I can reproduce.
![unnt](https://user-images.githubusercontent.com/16838044/32995104-3e85c63a-cd70-11e7-8474-4f035ca77de1.JPG)

**Comment by gotitbro** [comment]
@okiehsch I was getting the exact same notice but for some reason I do not anymore.

**Comment by okiehsch** [comment]
I get it only with Firefox.

**Comment by ghost** [comment]
If uBO is on, the "What to Read Next" section is broken, it doesn't show any suggested articles.
https://github.com/user-attachments/assets/4133884c-f0db-4d1a-a8bb-b8f5640b9c0d

With uBO off, they appear:
https://github.com/user-attachments/assets/913a5ae3-8029-416f-b31c-acab69d9f666

I tested this on: `https://www.digitalspy.com/tech/a402975/tcm-movies-channel-launching-in-hd-on-sky/`

Troubleshooting info:
<details>

```yaml
uBlock Origin: 1.66.0
Firefox: 142
filterset (summary):
 network: 160947
 cosmetic: 83106
 scriptlet: 32681
 html: 2363
listset (total-discarded, last-updated):
 added:
  fanboy-cookiemonster: 46298-152, 3h.33m
  ublock-cookies-easylist: 5063-39, 3h.33m
 default:
  user-filters: 65-1, never
  ublock-filters: 41266-87, 1h.32m
  ublock-badware: 10989-31, 1h.32m
  ublock-privacy: 3475-3, 1h.32m
  ublock-unbreak: 2744-1, 1h.30m Δ
  ublock-quick-fixes: 315-0, 35m Δ
  easylist: 79855-200, 1h.47m Δ
  easyprivacy: 54548-60, 3h.34m
  urlhaus-1: 31145-5, 3h.33m
  plowe-0: 3421-905, 3h.33m
  ROU-1: 1572-38, 3h.33m
filterset (user): [array of 60 redacted]
switchRuleset:
 removed:
  no-csp-reports: * true
userSettings:
 userFiltersTrusted: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 287 ms (selfie)
 maxAssetCacheWait: 107 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 10
 network:
  amazon-adsystem.com: 1
  cookielaw.org: 1
  cxense.com: 2
  doubleclick.net: 1
  ensighten.com: 1
  googlesyndication.com: 3
  hearstapps.com: 1
 extended:
  ###gpt-leaderboard-ad
  ##.ad-disclaimer
  ##.gpt-breaker-container
  ##.breaker-ad
  ##.ot-sdk-show-settings
  ##.vertical-ad
  ##+js(abort-on-property-read, _sp_._networkListenerData)
```

</details>

**Comment by stephenhawk8054** [comment]
It requires unblocking the tracking domain `cxense.com`. I don't think it should be unblocked for the section that is not about the article content. You can add these as your custom filters

```adb
@@||cdn.cxense.com/cx.$domain=digitalspy.com
@@||api.cxense.com/public/widget/data$script,domain=digitalspy.com
digitalspy.com#@#+js(abort-on-property-read, _sp_._networkListenerData)
digitalspy.com#@#section.inline-content-module
```
