### ISSUE TITLE
selcuksportshd**.live

### ISSUE THREAD

**Issue by bug-rules** [uBlockOrigin/uAssets#8480]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`selcuksportshd60.live`

### Describe the issue

ads

### Screenshot(s)

N/A

### Versions

- Browser/version: Firefox 85.b.9
- uBlock Origin version: 1.32.4

### Settings

- stock

### Notes

domain change numbers weekly, may need implement someting new for uBlock Origin like wildard in domain name?

**Comment by mapx-** [comment]
turkish sites

you could keep the scriptlet filters now in adguard for `live`:

`live##+js(abort-on-property-read, rndMax)`
