### ISSUE TITLE
skidrowreloaded.com virus JS on the site

### ISSUE THREAD

**Issue by belnet** [uBlockOrigin/uAssets#8482]
### URL(s) where the issue occurs
`https://www.skidrowreloaded.com/`

### Describe the issue
when trying to enter the site,  a virus java script is detected.
domain owners are definitely not to blame, obviously there is a leaky site engine that someone has infected.

I ask you to block the domains from where and where the virus refers to. (just not the skidrow site itself).

### Screenshot(s)
https://klikr.org/3e44d9f7d0e0c50d4b22727a77f8.png
(ESET detected).

### Versions
- Browser/version: [FF 84.0.2 x64]
- uBlock Origin version: [latest]

### Notes
I hope I can get in touch with the owners of the skidrow site to clean it up, but the WordPress engine is one big eternal vulnerability ...

**Comment by uBlock-user** [comment]
I see a popup -- `skidrowreloaded.com##+js(nowoif)`

**Comment by P0Rtvine** [comment]
`https://www.skidrowreloaded.com/`

### Screenshot(s)
<details>
<summary>Gif</summary>

![1](https://user-images.githubusercontent.com/57287308/121416957-132b6d80-c972-11eb-9aa6-f1aa85cb7b4f.gif)
</details>

### Versions

- Browser/version: Google Chrome
- uBlock Origin version: 1.35.2

### Settings
<details>
<summary>Screen</summary>

![2021-01-22_100714](https://user-images.githubusercontent.com/57287308/105464158-c3395c00-5c99-11eb-965b-81215d8f7bec.png)
</details>

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/df24fded446ee27bcf9c8d70b3876fff2227dc3e
