### ISSUE TITLE
adblock detected - www.livehindustan.com

### ISSUE THREAD

**Issue by Lucifer879** [uBlockOrigin/uAssets#8483]
**URL(s) where the issue occurs**
`https://www.livehindustan.com`

**Describe the issue**
Getting AdBlock detected popup when trying to read a post/news.

**Screenshot(s)**
![LiveHindusthan](https://user-images.githubusercontent.com/48880976/105068031-6f1a5600-5aa6-11eb-813f-c7b11bdb0a87.PNG)

**Versions**

- Browser/version: Chrome : 88.0.4324.96
- uBlock Origin version: 1.32.5b11

**Comment by uBlock-user** [comment]
`livehindustan.com##+js(no-fetch-if, adsbygoogle.js)` 

does that work ?
