### ISSUE TITLE
[feature request] Block COVID media bloatware

### ISSUE THREAD

**Issue by HLFH** [uBlockOrigin/uAssets#8485]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

Example: `https://www.lemonde.fr/`

Many media websites

### Describe the issue

**We have an inalienable right to privacy.**
Ads, "unintrusive" or not, are just the visible portions of privacy-invading apparatus entering your browser when you visit most sites nowadays. **uBlock Origin's main goal is to help users neutralize such privacy-invading apparatus**. The most privacy-invading apparatus nowadays is the COVID media bloatware. I am saying health policies in the West have been purposely mismanaged to enforce among other objectives the goal of establishing a vaccination passport that invades completely privacy. This mismanagement has been done thanks to the corruption in politics, media, health and finance. **I do believe uBlock should block media bloatwares that contains anti-privacy weapons.** I am saying national & global health policies have been poorly handled and the news media - that are generally owned by oligarchs - played a role in it. The European Commission has a [vaccination roadmap where in 2022](https://ec.europa.eu/health/sites/health/files/vaccination/docs/2019-2022_roadmap_en.pdf), it plans to deliver a _Commission proposal for a common vaccination card/passport for EU citizens_. In order to do that, they will fight against _vaccine hesitancy_. In uBlock's manifesto, it is being said the user decides what web content is acceptable or not in their browser. I do believe the progressive fusion of our physical, digital and biological identity is a global threat to privacy, and to all Internet users. uBlock should provide the feature to block any website having any text related to `corona`, `covid`, or have a more complex blocking filter related to it that would contribute to block media bloatwares.

**Comment by uBlock-user** [comment]
Subscribe to a list which does that. Default lists are not to be expected to block such things.
