### ISSUE TITLE
premid.app - broken intervals

### ISSUE THREAD

**Issue by ririxidev** [uBlockOrigin/uAssets#8486]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

https://premid.app
https://beta.premid.app

### Describe the issue

Hello! I'm ririxi - PreMiD Developer. I am writing issue there because we noticed that your rules for our website (https://premid.app/downloads) that boosts intervals, messes up our homepage. We added the remaining/elapsed time on user cards and now they are boosted - we can't do anything about it because it's in your rules. Can rules be changed to /downloads exclusive or removed?

Regards,
ririxi / mail@ririxi.dev

### Screenshot(s)

Link to video of described issue: https://i.ririxi.dev/issue.mp4

### Versions

- Browser/version: Microsoft Edge Version 89.0.771.0 (Official build) canary (64-bit)
- uBlock Origin version: uBlock Origin v1.32.4

### Settings

-

**Comment by mapx-** [comment]
@okiehsch we could add

`premid.app##+js(nano-sib, countDownBtn)`

before they used `countDownValue`  , some months ago the filter has been modified (maybe because they keep changing) .. so the dev is here ..

**Comment by uBlock-user** [comment]
Yes, they made sneaky changes to undermine the booster filter

**Comment by okiehsch** [comment]
> we could add
`premid.app##+js(nano-sib, countDownBtn)`

Sure, go ahead.

**Comment by mapx-** [comment]
@ririxidev well it's clear why happened, right ? so, please don't circumvent again our filter otherwise you got the consequences

**Comment by ririxidev** [comment]
Yes, we know because we use ads on our downloads site to download your program. But thanks for fixing it.
