### ISSUE TITLE
forum.release-apk.com anti-adb

### ISSUE THREAD

**Issue by Cyberavater** [uBlockOrigin/uAssets#8489]
### URL(s) where the issue occurs

`https://forum.release-apk.com/index.php`

### Describe the issue

 

The ad is removed but left an empty space there.

### Screenshot(s)

![Screenshot (58)](https://user-images.githubusercontent.com/32187927/105461763-d8bd7e80-5cb7-11eb-90f3-dbcf355fc123.png)

**Comment by ghajini** [comment]
`forum.release-apk.com##.adsbygoogle`

**Comment by mapx-** [comment]
go into some subforum, does not work will trigger anti adb.

**Comment by ghajini** [comment]
correct if i use `forum.release-apk.com##.adsbygoogle`
at
`https://forum.release-apk.com/viewforum.php?f=41`
antiadb triggered

**Comment by cantunborn** [comment]
Check out the script blocked by matching rule `||forum.release-apk.com/ext/*ReleaseAPK+shows+online+advertisements+to+our+visitors+to+cover+the+cost+of+hosting.$script,domain=forum.release-apk.com`.

**Comment by PIZZA90** [comment]
AntiAdblock:

`forum.release-apk.com##+js(aopr, eval)`

**Comment by exodius48** [comment]
> 
> 
> AntiAdblock:
> 
> `forum.release-apk.com##+js(aopr, eval)`

this filter does not work in FF 85.0

**Comment by krystian3w** [comment]
So try these:

`! chromium and fallback for html filtering`
`forum.release-apk.com##div.phpbb-ads-center:nth-of-type(2):nth-child(3):remove()`

`Firefox and Waterfox Classic`
`forum.release-apk.com##^div.phpbb-ads-center:nth-of-type(2):nth-child(3)`

---

Bottom leftover must by visible when I delete top `.adsbygoogle`

**Comment by Alex4567890** [comment]
forum.release-apk.com##div.phpbb-ads-center

**Comment by IThinkIAmCool** [comment]
Should this be closed? https://github.com/uBlockOrigin/uBlock-issues/issues/1494

**Comment by krystian3w** [comment]
Empty spaces is still active/visible.

With `:remove()` possible delete top placeholder but buttom not.

**Comment by avotoko** [comment]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://forum.release-apk.com/viewforum.php?f=41`


### Describe the issue

The anti-adblock message appears and I cannot browse the later part of the content.  
The Issue occurs in firefox, not in chrome.

### Screenshot(s)

**anti-adblock message at the later part:**
![ng](https://user-images.githubusercontent.com/53560467/120246560-89154200-c2ab-11eb-83d2-c9c37642cffd.jpg)
**expected:**
![expected](https://user-images.githubusercontent.com/53560467/120246566-8fa3b980-c2ab-11eb-8a33-10774508ddd8.jpg)


### Versions

- Browser/version: Firefox 88.0.1
- uBlock Origin version: v1.35.2

### Settings


- JPN: AdGuard Japanese (default)

### Notes


filters to resolve the issue.
```
!#if env_firefox
forum.release-apk.com#@#+js(aopw, document.onload)
forum.release-apk.com#@#^script:has-text(/'load'|document.onload/)
forum.release-apk.com##+js(acis, jQuery, 'load')
!#endif
```

**Comment by uBlock-user** [comment]
@avotoko 

```
forum.release-apk.com#@#+js(aopw, document.onload)
forum.release-apk.com#@#^script:has-text(/'load'|document.onload/)
```

will disable those filters and will cause Firefox's tab crash.

**Comment by avotoko** [comment]
> will disable those filters and will cause Firefox's tab crash.

On my PC, firefox slows down but doesn't crash.

> Does the tab crash on mobile with those filters ?

I hadn't thought about the mobile environment.
I tried to view the page with firefox nightly 90.0a1 and uBO 1.35.2 on android with all filters updated and no MyFilter.
As with the PC, the last part of the page showed the anti-adblock message and did not show the expected content.
I'm not familiar with mobile environments.
So I'm not going to do any more research by writing my own filters.

**Comment by uBlock-user** [comment]
`forum.release-apk.com##^script:has-text(/'load'|document.onload/)` is there to prevent tab crash in Firefox -- https://www.reddit.com/r/uBlockOrigin/comments/noyx16/ublock_origin_is_slowing_down_firefox_to_speed_up/.

**Comment by avotoko** [comment]
I understand that the filter prevents crashes. 
But is it correct that it doesn't address the issue of not displaying the expected content because it prioritizes preventing crashes?

**Comment by uBlock-user** [comment]
>  But is it correct that it doesn't address the issue of not displaying the expected content because it prioritizes preventing crashes?

I added that filter to fix the crash only, there's no known fix for anti-adblock currently

**Comment by avotoko** [comment]
I understand. Thank you for your kind answer.

**Comment by dimisa-RUAdList** [comment]
Fix, only for google chrome:
```
forum.release-apk.com##.phpbb-ads-center:style(pointer-events: none !important)
forum.release-apk.com###page-header:style(margin-bottom: -310px !important)
forum.release-apk.com###subheader
forum.release-apk.com##+js(remove-attr, style, ins, complete)
forum.release-apk.com#@#+js(abort-on-property-write, document.onload)
```

**Comment by krystian3w** [comment]
Added to ru ad list?

**Comment by maxelo** [comment]
> **Fix, only for google chrome**
> 
> Test link: `https://forum.release-apk.com/viewtopic.php?t=98786&start=10`
> 
> `forum.release-apk.com##+js(remove-attr, style, ins, complete)`
> -removing the style that sets the height of an empty ad item
> 
> `forum.release-apk.com###page-header:has(+ .phpbb-ads-center:matches-css(height: 280px)):style(margin-bottom: -265px !important)`
> -safe style to quickly remove empty space at the top of the page
> 
> `forum.release-apk.com##.phpbb-ads-center:style(pointer-events: none !important)`
> -fix for cases, where empty ad frames are on top of functional links, making them unclickable
> 
> Applying the above rules will trigger the detector. This problem is solved with:
> `forum.release-apk.com#@#+js(abort-on-property-write, document.onload)`

Thanks for your work, it works flawlessly on Chrome. But is there any way to make it work on Firefox?

**Comment by dimisa-RUAdList** [comment]
**Fix for firefox (actual versions)**

Test link: `https://forum.release-apk.com/viewtopic.php?t=98786&start=10`

```
forum.release-apk.com#@#^script:has-text(/'load'|document.onload/)
@@||googleads.g.doubleclick.net/pagead/*forum.release-apk.com$subdocument,domain=forum.release-apk.com
forum.release-apk.com##ins:style(opacity: 0 !important; pointer-events: none !important)
```

**Comment by uBlock-user** [comment]
@dimisa-RUAdList Site tab doesn't hang/freeze if you add `forum.release-apk.com#@#^script:has-text(/'load'|document.onload/)` ?

**Comment by dimisa-RUAdList** [comment]
In one case out of ten, not for long.

**Comment by uBlock-user** [comment]
I can still reproduce the hang/freeze on every refresh.

**Comment by dimisa-RUAdList** [comment]
Without disabling this rule, the site does not work in any case.

[Here's what happens - gif](https://imgur.com/cX0woty)

**Comment by uBlock-user** [comment]
Imported your filters, lets see if we get another Firefox crash report.

**Comment by stacieelton** [comment]
I am[ ](https://apkbattle.com/pubg-mobile-mod-apk/)having the same issue.

**Comment by jsteave** [comment]
I am having the same issue.

**Comment by jsteave** [comment]
[visit](https://www.apptros.com/bus-rush-mod-apk/) this also

**Comment by jsteave** [comment]
The filter, as far as I can [see](https://depositphotos.com/vector-images/comic-background.html), prevents crashes.
Is it correct, however, that because it prioritizes preventing crashes, it does not address the issue of not displaying the desired content?

**Comment by jsteave** [comment]
The filter, as far as I can [see](https://www.noyafa.net/multifunction-cable-tester/), prevents crashes.
Is it correct, however, that because it prioritizes preventing crashes, it does not address the issue of not displaying the desired content?
