### ISSUE TITLE
nsfw pornhub.com

### ISSUE THREAD

**Issue by Jason682** [uBlockOrigin/uAssets#849]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://www.pornhub.com/view_video.php?viewkey=ph5973eb091627f

### Describe the issue
video wont load completely,the grey bar above were the play button is stops and i cant see the whole video

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]
http://i65.tinypic.com/2lmuuti.png
### Versions

- Browser/version:    mozilla firefox 57,but i had the same issue with the previous version of firefox
- uBlock Origin version: 1.14.18

### Settings

- i havent made any settings changes except for forcing an update on my filters when it happens but i still seem to have the issue 

### Notes

ive had this issue on other webpages like pornhub and other web browsers with the same version of ublock origin

**Comment by gorhill** [comment]
Unable to reproduce, using default settings/lists.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by Jason682** [comment]
could it possibly be my web browser? i guess i just assumed it was a ublock origin problem because ive loaded the same video on 2 different web browsers and it worked fine on the one that didnt have ublock origin its just firefox is the browser i usually use
