### ISSUE TITLE
docviewer.yandex.com.tr Unblocked Header Ads

### ISSUE THREAD

**Issue by muhasturk** [uBlockOrigin/uAssets#8495]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://docviewer.yandex.com.tr/view/137163141/?*=alwGfrdO74RnXCfC6GzH%2FqbLwqh7InVybCI6InlhLWRpc2stcHVibGljOi8vRVIyTWNZS2tnejNMaVdKTllLVG1DSmJPZXZ4S3B0cXRvTDJNakN4NitjRGdvUytZdnlDdjZ2SlZEUk93Szl5L3EvSjZicG1SeU9Kb25UM1ZvWG5EYWc9PSIsInRpdGxlIjoiUTE1NDI4X1JPR19TVFJJWF9QU1VfUVNHXzEwNVgxNDhfV0VCLnBkZiIsIm5vaWZyYW1lIjpmYWxzZSwidWlkIjoiMTM3MTYzMTQxIiwidHMiOjE2MTEzMjczMjkwMjIsInl1IjoiNzExODc4NzMxMTYwNjU2NTY5MyJ9`

### Describe the issue
- `docviewer.yandex.com.tr` has unblocked ads on header.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/4077401/105506079-b6892800-5cda-11eb-8d30-9019854ae163.png)

### Versions

- Browser/version:  Microsoft Edge Version 87.0.664.75 (Official build) (64-bit)
- uBlock Origin version: 1.32.4

### Settings
![image](https://user-images.githubusercontent.com/4077401/105506225-e0dae580-5cda-11eb-8ee3-0c025f05eff8.png)

**Comment by mapx-** [comment]
see https://github.com/uBlockOrigin/uAssets/issues/7830#issuecomment-765478795
