### ISSUE TITLE
kickasstorrents2.net & related

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8497]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://kickasstorrents2.net/t3-Kaagaz-2021-Hindi-720p-ZEE5-WEB-DL-AAC2-0-H-264-Shadow-BonsaiHD-tt4732776.html`
`https://kkat.net`
`https://kat2.website`
### Describe the issue
popup ads

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.34.2

### Settings

uBO's default settings
-

### Notes

propeller crap at `https://kat2.website`

**Comment by ghajini** [comment]
i just edited title to report kickasstorrents sites and their mirrors to be reported in this thread only,hope you don't mind

**Comment by okiehsch** [comment]
No problem.

**Comment by ghajini** [comment]
ok thanks,i edited above these 2 sites

ads at `https://kkat.net`

ads & propeller crap at `https://kat2.website`

**Comment by ghajini** [comment]
`https://kickassgo.com/t3-ZAYN-Nobody-Is-Listening-2021-Mp3-320kbps-PMEDIA-tt4741729.html`
popup ads & propeller crap

`||kickassgo.com/x9.php$script,1p`
`kickassgo.com##+js(aopr, String.fromCharCode)`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/764a5dcbf41bfd34a848fd0ac3fba1820afe16d8

**Comment by ghajini** [comment]
Kickass & their related websites

**Issue=**
 Popup ads /propeller crap

**Platform=**
opera browser/firefox & ubo stable

**URL's=**

``
kat.fun
kat.sx

kickass.onl
kickass.cd
kickass.earth
kickass.id
kickass.kim
kickass.name
kickass.one
kickass.red
kickass.ws
kickass.love

kickass2.app
kickass2.fun
kickass2.mobi
kickass2.online
kickass2.space
Kickass2.top
Kickass2.website
Kickass2.xyz
kickass.me.uk

kickasstorrents.id
kickasstorrents.fun
kickasstorrents.icu
kickasstorrents.mobi
kickasstorrents.space
kickasstorrents.pw/games.html

kat2.website/
kat2.app
kat2.space
kat2.xyz

https://kattracker.com/movies/
https://thekat.info/
thekickass.org
kickassz.com
kickasstorrents2.net
https://thekat.cc/full/
https://topkickass.org/music/
kickassgo.com
https://kkickass.com/
https://kkat.net/new/
https://kickasst.net/
https://kick4ss.net/full/ 
kickasstorrentcr.top
``

**Comment by ghajini** [comment]
Some cosmetic filters needs to update for specific website, I will update above message pls wait

**Comment by mapx-** [comment]
no popups for `kickasstorrentcr`

test

```
kick4ss.*,topkickass.*,kickasstorrents2.*,kickassz.*,thekickass.*,kattracker.*,kickass2.*,kat2.*,kickassgo.*,kick4ss.com,kat.*,kickass.*,kickasst.*,kickasstorrents.*,kickass-kat.*,kkat.*,kkickass.*,thekat.*##+js(aeld, click, Cookie)
kick4ss.*,topkickass.*,kickasstorrents2.*,kickassz.*,thekickass.*,kattracker.*,kickass2.*,kat2.*,kickassgo.*,kick4ss.com,kat.*,kickass.*,kickasst.*,kickasstorrents.*,kickass-kat.*,kkat.*,kkickass.*,thekat.*##+js(aopr, LieDetector)
kick4ss.*,topkickass.*,kickasstorrents2.*,kickassz.*,thekickass.*,kattracker.*,kickass2.*,kat2.*,kickassgo.*,kick4ss.com,kat.*,kickass.*,kickasst.*,kickasstorrents.*,kickass-kat.*,kkat.*,kkickass.*,thekat.*##:xpath(//*[contains(text(),"Protect")]):upward(3)
```

**Comment by ghajini** [comment]
1. popup ads at
`https://kat.sx/movies/`

2.
```
propeller crap at `https://kickass2.online/movies/`
https://kickass2.space
https://kickass2.top
https://kickass2.website/movies/
https://kickass2.xyz/movies/
https://kattracker.com/movies/
https://kickassz.com/movies/
https://topkickass.org/music/
https://kick4ss.net/full/
```

**Comment by mapx-** [comment]
no issue on my end for `kat.sx`

**Comment by ghajini** [comment]
This works for me
```
||kat.sx/89tmo.js$script
||cfts1tifqr.com^$all
```

**Comment by ghajini** [comment]
I know but its not  defused....
Load `https://kat.sx/wonder-woman-1984-2020-imax-hdrip-xvid-ac3-evo-tgx-tt38960068.html`
&then again reload after some time, popup ads start when clicking anywhere

**Comment by lain566** [comment]
`:xpath` is causing breakage, I have removed it
```
https://kickasstorrents.space/usearch/Staff/
https://kickasstorrents.space/t3-Cyberpunk-2077-Update-v1-1-CODEX-tt4750115.html
https://kickasstorrents.space/t0-Emily_Mena_-_Daddys_Girl_Emily_Mena_Fucks_The_Hotel_Staff-tt19995778.html
```

and also removed `kick4ss.com`  duplicate domain

**Comment by ghajini** [comment]
`kat.*##.doublecelltable`
is causing breakage(blank page) at `https://kat.sx/movies/` & may be other sites listed in commit

![image](https://user-images.githubusercontent.com/20338483/105869511-52899b00-601d-11eb-9fd6-536ce7c5d714.png)

also iam getting still popups `kat.sx/movies`

**Comment by lain566** [comment]
> also iam getting still popups `kat.sx/movies`

I can't reproduce any popup on  `kat.sx/movies`

**Comment by ghajini** [comment]
on going  `kat.sx/movies` ,wait for page to load completely ,again refresh the page ,then click anywhere,popup ads start

**Comment by ghajini** [comment]
popup ads 
opera browser stable, ubo 1.32.5rc3

```
https://kat2.website/t3-Tandav-2021-Hindi-S01-Complete-720p-AMZN-WEBRip-DD-5-1-ESub-x265-Shadow-BonsaiHD-tt4741758.html
https://kat.fun/movies/
https://kickass.onl/movies/
https://kickass.earth/movies/
https://kickass.id/movies/
https://kickass.kim/movies/
https://kickass.name/movies/
https://kickass.one/movies/
https://kickass.red/movies/
https://kickass.love/movies/
https://kickass2.app/movies/
https://kickass2.fun/movies/
https://kickass2.mobi/movies/
https://kickass2.online/movies/
https://kickass2.space/movies/
https://kickass2.top/movies/
https://kickass2.website/movies/
https://kickass2.xyz/movies/
https://kickass.me.uk/movies/
https://kickasstorrents.id/movies/
https://kickasstorrents.fun/movies/
https://kickasstorrents.icu/movies/
https://kickasstorrents.mobi/movies/
https://kickasstorrents.space/movies/
https://kat2.app/movies/
https://kat2.space/movies/
https://kat2.xyz/movies/
https://thekat.info/movies/
https://thekickass.org/movies/
https://kickassz.com/movies/
https://kickasstorrents2.net/movies/
https://thekat.cc/movies/
https://topkickass.org/movies/
https://kickassgo.com/movies/
https://kkickass.com/movies/
https://kkat.net/movies/
https://kick4ss.net
```

**Comment by lain566** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a0d5dea4b1e1130360d10777ad29fee9a00ce9dc

**Comment by ghajini** [comment]
Again circumvention of all filters

**Comment by ghajini** [comment]
@mapx- 
meanwhile as suggested by you
such a filter 
 `*$popup,domain=` 

remembering partyness can be added for all above kickass domains if they are hourly circumventing the ubo filters

**Comment by mapx-** [comment]
test filters like these:

```
||kat2.*^$script,1p
||kat2.*^$csp=script-src *
kat2.*##[style*="decoration"]:not([style^="width"])
```

**Comment by ghajini** [comment]
Let me check all sites

**Comment by ghajini** [comment]
mirrors
popup ads
`https://katbay.org/movies/`
`https://kickasshydra.dev`

**Comment by ghajini** [comment]
they changed & previous cosmetic filter not work.
new mirrors from kickasshydra. net( .dev)

1.
update to 
```
kat.*,kickass.*,kickass2.*,kickasstorrents.*,kat2.*,kattracker.*,thekat.*,thekickass.*,kickassz.*,kickasstorrents2.*,topkickass.*,kickassgo.*,kkickass.*,kkat.*,kickasst.*,kick4ss.*,katbay.*,kickasshydra.*,kickasskat.*,kickassbay.*,torrentkat.*,kickassuk.*,torrentskickass.*,kickasspk.*,kickasstrusty.*,katkickass.*,kickassindia.*,kickass-usa.*,kickassaustralia.*,kickassdb.*,kathydra.*,kickassminds.*,katkickass.*,kickassunlocked.*,kickassmovies.*,kickassfull.*,bigkickass.*,kickasstracker.*,katfreak.*##[style*="decoration"]:not([style^="width"])

kat.*,katbay.*,kickass.*,kickasshydra.*,kickasskat.*,kickass2.*,kickasstorrents.*,kat2.*,kattracker.*,thekat.*,thekickass.*,kickassz.*,kickasstorrents2.*,topkickass.*,kickassgo.*,kkickass.*,kkat.*,kickasst.*,kick4ss.*##[href="/k.php?q=q"]
```

2.
new sites ,pls add in existing filters if you prefer
```
*$script,1p,domain=kickassbay.*|torrentkat.*|kickassuk.*|torrentskickass.*|kickasspk.*|kickasstrusty.*|katkickass.*|kickassindia.*|kickass-usa.*|kickassaustralia.*|kickassdb.*|kathydra.*|kickassminds.*|katkickass.*|kickassunlocked.*|kickassmovies.*|kickassfull.*|bigkickass.*|kickasstracker.*|katfreak.*

*$csp=script-src *,domain=kickassbay.*|torrentkat.*|kickassuk.*|torrentskickass.*|kickasspk.*|kickasstrusty.*|katkickass.*|kickassindia.*|kickass-usa.*|kickassaustralia.*|kickassdb.*|kathydra.*|kickassminds.*|katkickass.*|kickassunlocked.*|kickassmovies.*|kickassfull.*|bigkickass.*|kickasstracker.*|katfreak.*
```

**Comment by gorhill** [comment]
<https://twitter.com/capJavert/status/1360382264950063104>:

> my personal website https://kickass.website is blocked by uBlock filters, is there anything we can do about that?

**Comment by andresavic** [comment]
@gorhill The website of our client "kat.at" and "www.kat.at" gets blocked by this kind of filter. Would be awesome if this could be resolved. Thanks in advance.
