### ISSUE TITLE
EASY LIST AND EASY PRIVACY NOT  UPDATE IN GOOGLE CHROME>>>>>>>>PLEASE FIX THIS

### ISSUE THREAD

**Issue by applesam** [uBlockOrigin/uAssets#85]
![fireshot screen capture 002 - -](https://cloud.githubusercontent.com/assets/20497954/17010838/5cafd0da-4f25-11e6-9567-90170aea8787.png)
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`[At least one URL for a web page where the clearly described issue occurs is **mandatory**. The backticks surrounding the URLs is important, it prevents the URL from being clickable. Warn with "NSFW" where applicable.]`

### Describe the issue

[Be as clear as possible: nobody can read mind, and nobody is looking at your issue over your shoulder.]

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

- [List here all the changes you made to uBO's default settings]

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by applesam** [comment]
IN FIREFOX>>>>
![fireshot screen capture 006 - ublock dashboard - chrome___ublock0_content_dashboard_html 3p-filters_html](https://cloud.githubusercontent.com/assets/20497954/17010928/2b2069b6-4f26-11e6-9763-132a8aac8270.png)

**Comment by gorhill** [comment]
If you click on <https://easylist.to/easylist/easylist.txt> in Chrome, can you see the list?

**Comment by applesam** [comment]
https://easylist.to/easylist/easylist.txt 
![fireshot screen capture 003 - -](https://cloud.githubusercontent.com/assets/20497954/17011196/c2a17832-4f28-11e6-8920-0d410b040b25.png)
RC4 not safe protocal  not support google chrome

**Comment by gorhill** [comment]
What version of Google Chrome are you using?

**Comment by applesam** [comment]
google chrome  49.0.2623.112 m

**Comment by gorhill** [comment]
What OS?

**Comment by gorhill** [comment]
Can you see this one: <https://easylist-downloads.adblockplus.org/easylist.txt>?

**Comment by applesam** [comment]
google chrome 49.0.2623.112 m and ublock Origin 1.7.6 win xp pro sp3
![fireshot screen capture 004 - - easylist-downloads_adblockplus_org_easylist_t](https://cloud.githubusercontent.com/assets/20497954/17011304/2f4a4a4e-4f2a-11e6-8fd1-21e9cfee6e1d.png)

**Comment by gorhill** [comment]
You will have to add:

- https://easylist-downloads.adblockplus.org/easylist.txt
- https://easylist-downloads.adblockplus.org/easyprivacy.txt

as custom URLs at the bottom of the _3rd-party filters_ pane, then click _Parse_. Un-select the stock EasyPrivacy and EasyPrivacy, then click _Apply changes_.

**Comment by applesam** [comment]
Thanks
![fireshot screen capture 005 - -](https://cloud.githubusercontent.com/assets/20497954/17011379/2e6e7ce8-4f2b-11e6-9fae-c555d8b93350.png)

**Comment by gorhill** [comment]
I see you did not un-select the default EasyList and EasyPrivacy -- I suggest you do so, or else you may be left stuck with obsolete filters which could break web pages.

**Comment by applesam** [comment]
ok

**Comment by thegoodthings** [comment]
@applesam, judging by your screenshots, you're using Windows XP.  

Chrome (and all Chromium-based browsers, as far as I know) use the system's encryption stack, meaning Chrome under Windows XP doesn't support any newer encryption standards (such as those used by https://easylist.to/, it seems).

**Comment by TheRyuu** [comment]
> Chrome (like all Chromium-based browsers, as far as I know) uses the system's encryption stack

This is incorrect.  Chrome uses BoringSSL[1] which is a fork of OpenSSL.  Chrome used to use NSS (what Firefox uses) but switched to BoringSSL.  At no point did Chrome ever use the systems encryption stack by default AFAIK.  I don't know what other Chromium based browsers uses but it's unlikely to use the systems encryption stack since the code for that was removed long ago.

[1] https://boringssl.googlesource.com/boringssl/

**Comment by thegoodthings** [comment]
Sorry about the misinformation - @TheRyuu is correct.  I had just done a quick search on the error message, and that was the info I found.  Turns out it's only correct for Chrome 5 and earlier, which did indeed use the built-in Windows SChannel SSL library

**Comment by 123466769999Ram** [comment]
# I think i've found the  solution. 
The main problem was with EasyList and EasyList associated filters. They do not work properly sometimes, or to be fair, most of the times.  This is my settings, I remove every EasyList filter and some filters that are directing you to "forums.lanik.us" which is a EasyList assocaited forum. So this is my seetings: 
![screenshot_2](https://cloud.githubusercontent.com/assets/20622871/17083038/3cd8c956-519b-11e6-9080-08f5b1d77baa.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/20622871/17083039/3cd99d90-519b-11e6-91a6-feed0d75b37e.png)



[ublock-backup_24.7.2016_12-14-14.txt](https://github.com/uBlockOrigin/uAssets/files/380212/ublock-backup_24.7.2016_12-14-14.txt)

Here is proof:
![screenshot_5](https://cloud.githubusercontent.com/assets/20622871/17083062/fd07ce02-519b-11e6-8c1c-f6db510ac21a.png)

I hope that helped you, with this settings, where EasyList's filters and "forums.lanik.us" are disabled, everything with Google pictures should be fine.  Good Luck.

**Comment by Hrxn** [comment]
But this does not change the fact that Windows XP is no longer supported (by Microsoft itself as well as by Chrome), so this might be the likely cause if you run into any problems.
