### ISSUE TITLE
iesnare.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#850]
### URL(s) where the issue occurs

`https://citiretailservices.citibankonline.com/RSnextgen/svc/launch/index.action?siteId=PLCN_MACYS`
`https://citiretailservices.citibankonline.com/RSnextgen/svc/launch/index.action?siteId=PLCN_BLOOMINGDALES`
and perhaps others. This is the portal to pay credit cards from Macy's, Bloomingdales, etc.

### Describe the issue

Page won't load.

### Versions

- Browser/version: Chrome 62
- uBlock Origin version: 1.14.18

### Settings

Default

### Notes

`@@iesnare.com` fixes it. Should be applied to `https://citiretailservices.citibankonline.com`

**Comment by okiehsch** [comment]
Does 
`@@||mpsnare.iesnare.com/snare.js$script,domain=citiretailservices.citibankonline.com`
work for you?

**Comment by terrorist96** [comment]
Yes. Thanks!
