### ISSUE TITLE
biznes.interia.pl | pomponik.pl

### ISSUE THREAD

**Issue by AroKol78** [uBlockOrigin/uAssets#8509]
`https://www.pomponik.pl/` `https://biznes.interia.pl/` back "adblock detect"

"uBlock filters – Privacy" ? 
`||securepubads.g.doubleclick.net/tag/js/gpt.js$script,redirect=googletagservices_gpt.js`

ubo legacy [myList](https://user-images.githubusercontent.com/70756447/102889523-1a5dce00-445b-11eb-9dfa-8919f5ae110c.PNG) +"Polskie Filtry Elementów Irytujących - Scrollujące Filmiki"

https://github.com/uBlockOrigin/uBlock-issues/issues/1397
https://github.com/MajkiIT/polish-ads-filter/issues/17220

**Comment by uBlock-user** [comment]
fixed in polish lists, force update.

**Comment by uBlock-user** [comment]
You're not on default lists as per the list snapshot, so disable all the custom lists if it doesn't work for you.

**Comment by AroKol78** [comment]
not fixed in polish lists

test: default lists only enabled - i force update
did not help
```
uBlock filters
uBlock filters - Legacy
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Peter Lowe’s Ad and tracking server list
POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
POL: Oficjalne polskie filtry przeciwko alertom o Adblocku
```

helps:
- off "uBlock filters – Privacy"
- `biznes.interia.pl,pomponik.pl##+js(no-setTimeout-if.js, , 500)`
- `interia.pl,pomponik.pl##+js(no-setTimeout-if.js, , 500)`
- `@@||securepubads.g.doubleclick.net/tag/js/gpt.js$script,domain=biznes.interia.pl|pomponik.pl|iplsc.com`

if the page is in the background - it does not appear "adblock detect"

**Comment by uBlock-user** [comment]
```
~poczta.interia.pl,interia.pl,pomponik.pl##+js(set, Inpl.Abd.onDetected, noopFunc)
interia.pl,pomponik.pl##+js(set, isAdblockDetected, 0)
```

is present in `POL: Oficjalne polskie filtry przeciwko alertom o Adblocku` so works.

**Comment by AroKol78** [comment]
it doesn't help anymore after adding
`||securepubads.g.doubleclick.net/tag/js/gpt.js$script,redirect=googletagservices_gpt.js`
 to "uBlock filters – Privacy" 

https://github.com/uBlockOrigin/uBlock-issues/issues/1397#issuecomment-765574758

**Comment by uBlock-user** [comment]
Sounds like a uBO Legacy issue..

**Comment by uBlock-user** [comment]
Sounds like a uBO Legacy issue..

**Comment by uBlock-user** [comment]
> uBlockOrigin/uBlock-issues#1397 (comment)

Does that work for you ?

**Comment by uBlock-user** [comment]
> uBlockOrigin/uBlock-issues#1397 (comment)

Does that work for you ?
