### ISSUE TITLE
comenity.net

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#851]
### URL(s) where the issue occurs

`https://c.comenity.net/express/`
`https://d.comenity.net/ultamaterewardsmastercard/pub/Home.xhtml`
and perhaps others

### Describe the issue

Need to sign in. Using a new device, and having to confirm it, it will not load the text box to enter the confirmation code that is texted/emailed to you.

### Versions

- Browser/version: Chrome 62
- uBlock Origin version: 1.14.18

### Settings

Default

### Notes

`@@adobedtm.com` fixes it. Apply to `*.comenity.net`

**Comment by okiehsch** [comment]
Does
`@@||adobedtm.com^*/satellitelib-$script,domain=comenity.net`
work for you?

**Comment by terrorist96** [comment]
Yes, thanks!
