### ISSUE TITLE
Momentary lack of scrolling on NYT homepage (mobile)

### ISSUE THREAD

**Issue by dbenjaminmiller** [uBlockOrigin/uAssets#8511]
### Prerequisites

- [X] This is not a support issue or a question
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`http://www.nytimes.com/`

### Describe the issue

 

Somewhat similar to #5677, this appears to be an issue on mobile. For a few moments, the NYT homepage loads something that inhibits scrolling (similar to the "remnant" in the aforementioned issue). This does not happen on desktop mode. To test this out, try using the Firefox responsive browsing mode on desktop, and use the S9 profile. You will be unable to scroll for a few seconds. Reflects the temporary modal for subscription that you will see when you disable uBO, which also goes away after a few seconds.

### Screenshot(s)

![No scrollbar, during the few seconds when scrolling is impossible](https://user-images.githubusercontent.com/43855846/105914316-30cbec00-5ffc-11eb-8a79-bc9c63161dcc.png)

(Note the lack of scrollbar; I have them enabled, but scrolling is disabled for a few seconds.)

### Versions

- Browser/version: Firefox 84 (both desktop simulating mobile as well as mobile)
- uBlock Origin version: 1.32.4

**Comment by yourduskquibbles** [comment]
Please enable and/or update `uBlock filters – Annoyances` list it should be fixed now. Thanks for repro steps.
