### ISSUE TITLE
calcioefinanza.it

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#8512]
FF 85.0
uBO 1.32.5rc3 default + RU AdList 

Due to blocking of the clickiocdn.com adserver using cname breaks the layout in Firefox.

Example: `https://www.calcioefinanza.it/2021/01/27/agnelli-positivo-linteresse-dei-fondi-per-il-calcio/`

Please add in uBlock filters – Unbreak: `@@||wpcdn-eu.clickiocdn.com/|$domain=calcioefinanza.it`

or: `@@||calcioefinanza.it^$cname`

**Comment by uBlock-user** [comment]
> Due to blocking of the clickiocdn.com adserver

`clickiocdn.com` is not blocked in any default lists, I do see `||clickiocdn.com^$3p` present in Fanboy's Annoyances

**Comment by dimisa-RUAdList** [comment]
`||clickiocdn.com^$third-party` occurs in: [RU AdList](https://easylist-downloads.adblockplus.org/advblock.txt), [AdGuard Russian filter](https://filters.adtidy.org/extension/chromium/filters/1.txt), [Fanboy's Annoyance List](https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt).

The problem is specific only to uBO for FF and is related to blocking cname.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/6d40d0831c157c4d3a34a389da99245242fd0807
