### ISSUE TITLE
embedstream.me

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#8514]
Google Chrome 88.0.4324.104
uBlock Origin 1.32.5rc3 default

Example: `http://cdn.livetv382.me/webplayer.php?t=ifr&c=1530821&lang=ru&eid=1025234&lid=1530821&ci=167&si=2`

[Screen](https://i.imgur.com/V16r41j.jpg)

May be: `embedstream.me##body > .position-absolute`?

**Comment by okiehsch** [comment]
Video does not work on my end.
If the proposed filter works for you we can add it.

**Comment by dimisa-RUAdList** [comment]
Yes, add please.
