### ISSUE TITLE
Broken shopping buttons on www.indigenousoap.com

### ISSUE THREAD

**Issue by arthuredelstein** [uBlockOrigin/uAssets#8515]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.indigenousoap.com/collections/fine-soaps/products/aina`

### Describe the issue

Console errors and "Add to Cart" button fails to appear.

 
![image](https://user-images.githubusercontent.com/355566/106065200-cbd1ce00-60af-11eb-8954-1c5db6152a9e.png)

### Screenshot(s)

uBO "privacy" filter disabled:
![image](https://user-images.githubusercontent.com/355566/106065349-0c314c00-60b0-11eb-8e31-87b0b0833e1f.png)

uBO "privacy" filter enabled: 
![image](https://user-images.githubusercontent.com/355566/106065148-b361b380-60af-11eb-912f-763cd2bcf631.png)

### Versions

- Browser/version: Firefox 85.0
- uBlock Origin version: 1.32.4

### Notes

I believe I have narrowed it down to uBlock's "Privacy" filter.

**Comment by arthuredelstein** [comment]
(Originally reported by https://twitter.com/crwbot/status/1354527567869407232)

**Comment by gwarser** [comment]
Seems to be
		    
	  Filter /fbevents.js
	  Filter list EasyPrivacy

**Comment by okiehsch** [comment]
It's caused by the redirection
````
@@||google-analytics.com/analytics.js$script,redirect-rule=google-analytics.com/analytics.js
````
