### ISSUE TITLE
Isohunt.* & related

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8519]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
```
https://isohuntz.net/torrents
https://isohunts.net/torrents/
https://isohunt.soy/torrents
https://isohuntx.com/torrents
https://isohunthydra.com
https://isohunt.io/torrents
https://isohunters.org/torrents
https://isohunt.bz/torrents
https://isohunting.com/torrents
https://isohunt.how/torrents
https://myisohunt.com/torrents
https://isohunt.lol/torrents/
```
### Describe the issue

popup ads
vpn promotion

### Versions

- Browser/version: opera browser stable
- uBlock Origin version: 1.32.5rc3

### Settings

 uBO's default settings
-

**Comment by mapx-** [comment]
test all pages

```
*$script,1p,domain=isohuntz.*|isohunt.*|isohunts.*|isohuntx.*|isohunthydra.*|isohunters.*|isohunting.*|myisohunt.*
*$csp=script-src *,domain=isohuntz.*|isohunt.*|isohunts.*|isohuntx.*|isohunthydra.*|isohunters.*|isohunting.*|myisohunt.*
*$frame,domain=isohuntz.*|isohunt.*|isohunts.*|isohuntx.*|isohunthydra.*|isohunters.*|isohunting.*|myisohunt.*
```

**Comment by ghajini** [comment]
this dropdown menu & its contents are blocked
![image](https://user-images.githubusercontent.com/20338483/106247453-8f2fdf00-6235-11eb-96ec-aae340024604.png)
