### ISSUE TITLE
androidcentral anti-adblock

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#852]
### URL(s) where the issue occurs

`https://www.androidcentral.com/`

### Describe the issue

anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/33038768-bccdc090-ce03-11e7-928d-93d75fe77707.png)

**Comment by uBlock-user** [comment]
Add `windowscentral.com` too

**Comment by okiehsch** [comment]
I did. https://github.com/uBlockOrigin/uAssets/commit/eae57534e8e339a3fdefd3dafe3c756f1246bee1
````
androidcentral.com,crackberry.com,imore.com,windowscentral.com##script:inject(abort-current-inline-script.js, Promise, Adblocker)
````

**Comment by KiLL4FuNK** [comment]
> I did. [eae5753](https://github.com/uBlockOrigin/uAssets/commit/eae57534e8e339a3fdefd3dafe3c756f1246bee1)
> 
> ```
> androidcentral.com,crackberry.com,imore.com,windowscentral.com##script:inject(abort-current-inline-script.js, Promise, Adblocker)
> ```

anti-adblock

**Comment by okiehsch** [comment]
Fixed in annoyances.
