### ISSUE TITLE
Cannot download VMware Fusion Player

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uAssets#8521]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

https://my.vmware.com/group/vmware/evalcenter?p=fusion-player-personal

### Describe the issue

The "Manually Download" button does not work. 

### Screenshot(s)

![immagine](https://user-images.githubusercontent.com/62190484/106311607-b2728280-6265-11eb-80e5-830a18338078.png)

### Versions

- Browser/version: Firefox 85
- uBlock Origin version: 1.32.4

### Settings

- Prevent WebRTC from leaking local IP address
- Block CSP reports

### Notes

Disabling uBlock Origin makes the button work.

**Comment by mapx-** [comment]
test

`@@||tags.tiqcdn.com/utag/vmware/myvmware-privacy/prod/utag.sync.js$script,domain=vmware.com`

If still does not work add also and test again:
`@@||tags.tiqcdn.com/utag/vmware/myvmware-privacy/prod/utag.js$script,domain=vmware.com`

**Comment by fabriziobagala** [comment]
Adding both works.
