### ISSUE TITLE
help with getting detected by quackr

### ISSUE THREAD

**Issue by evq3-lalala** [uBlockOrigin/uAssets#8524]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://quackr.io/`
just select any number

### Describe the issue

I first go into the website with my ubo turned on and it shows the result but suddenly turn into "pic1".
Then i turned off ubo by clicking the big blue "click to disable" button and refresh then the problem solved . 
But even after ubo was turned on and  i tried to refresh the page with cache disabled using the developer tools ,the problem won't reproduce.
Just wondering how ubo got detected .  Is it just me ?
If there is a way to avoid getting detected that would be great .

 

### Screenshot(s)
(pic1)![20210201-issue-quackr-webpage1](https://user-images.githubusercontent.com/74836487/106405465-31b2b280-642e-11eb-9c16-a75a858fd311.jpg)

### Versions

- Browser/version: [Firefox x64 85.0 ]
- uBlock Origin version: [1.32.4]

### Settings

-

### Notes
I found others and this `https://quackr.io/adblocker.js` got blocked . dunno if  it's related.

**Comment by evq3-lalala** [comment]
just want to know how exactly ubo was still turn on but not getting detected . hope i can solve this on my own if i ever encounter this kind of problem . maybe add a simple whitelist rule?

**Comment by uBlock-user** [comment]
force update EasyList, the bait is no longer a bait.
