### ISSUE TITLE
thevotingnews.com

### ISSUE THREAD

**Issue by Woofy-Wolf** [uBlockOrigin/uAssets#8526]
### Prerequisites

- [ x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x ] I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [ x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://thevotingnews.com/`

### Describe the issue

Hi everyone,
this site lists recent news stories. please scroll to the bottom of the page and click the "load more" button. instead of loading more stories, the icon becomes a circle that turns infinitely, i.e., "wait please," forever.

### Screenshot(s)

![Screenshot_2021-02-02 The Voting News(2)](https://user-images.githubusercontent.com/40744508/106547484-31d1b180-6505-11eb-9673-9c0ac808d65d.png)

![Screenshot_2021-02-02 The Voting News(3)](https://user-images.githubusercontent.com/40744508/106547862-e79d0000-6505-11eb-98c4-d444a806a900.png)

### Versions

- Browser/version: [Firefox 85.0 (64-bit)]
- uBlock Origin version: [v1.33.2]

### Settings

- new profile, default firefox settings, ublock only extension, default ublock settings, default filters (updated)

### Notes

No clue. only googletagmanager appears in the log as blocked. ¯ \ ( ツ ) / ¯

**Comment by okiehsch** [comment]
> instead of loading more stories, the icon becomes a circle that turns infinitely, i.e., "wait please," forever.

It's broken even with uBO disabled.

**Comment by Woofy-Wolf** [comment]
Oof. that was dumb of me. Sorry @okiehsch .
