### ISSUE TITLE
hobbyconsolas.com

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#8528]
### URL(s) where the issue occurs

```
https://www.hobbyconsolas.com/noticias/wonder-woman-1984-hunde-taquilla-china-durante-segunda-semana-783001
https://www.hobbyconsolas.com/noticias/scott-lowe-responsable-marketing-naughty-dog-abandona-estudio-cinco-anos-803527
```

### Describe the issue

look like "awin1" ads

### Screenshot(s)

![Captura](https://user-images.githubusercontent.com/33556647/106662647-f08fdf00-65a2-11eb-8ca3-2289d2ce71f2.PNG)

![Captura2](https://user-images.githubusercontent.com/33556647/106662653-f2f23900-65a2-11eb-9c0e-11554cba0134.PNG)

### Versions

- Browser/version: [CHROME]
- uBlock Origin version: [1.32.4]

### Notes

maybe this filter is the problem:

https://github.com/uBlockOrigin/uAssets/blob/ce6ff118127ac5337afbd1124ad4b9268faf5f41/filters/unbreak.txt#L2361

**Comment by mapx-** [comment]
That filter is ok

test
`hobbyconsolas.com##[href^="https://www.awin1.com/awclick.php"]:upward([data-embed-button])`

**Comment by PIZZA90** [comment]
working in the first link

what about here:

`https://www.hobbyconsolas.com/noticias/scott-lowe-responsable-marketing-naughty-dog-abandona-estudio-cinco-anos-803527`

here uBO yes warn me when i do click.. (different adserver?)

`https://www.hobbyconsolas.com/reportajes/avance-mass-effect-legendary-edition-sera-renacer-shepard-802283`

**Comment by PIZZA90** [comment]
ok this works
```
hobbyconsolas.com##[href^="https://www.awin1.com/"]:upward([data-embed-button])
hobbyconsolas.com##[href^="http://disneyplus.bn5x.net/"]:upward([data-embed-button])
```
these filters are uBO specific?? or should be added in spanish easylist?

**Comment by PIZZA90** [comment]
well tested in ABP with firefox.. i dont know why not working in ABP

**Comment by mapx-** [comment]
ABP didn't implement `:upward`

**Comment by mapx-** [comment]
ABP filter:
`hobbyconsolas.com#?#[data-embed-button]:-abp-has([href^="https://www.awin1.com/"])`
