### ISSUE TITLE
devharry.cc

### ISSUE THREAD

**Issue by etpjhwpknwk** [uBlockOrigin/uAssets#8530]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://www.devharry.cc`
`https://devharry.cc`

### Describe the issue

Website visited directly
Malware host - examples of malicious content involve the files svchost.exe and System.exe which are on the root of the site
 

### Screenshot(s)
not applicable

### Versions

- Browser/version: Google Chrome Version 88.0.4324.104 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.32.4

### Settings

- Default settings

**Comment by okiehsch** [comment]
https://urlhaus.abuse.ch/url/987877/
https://www.virustotal.com/gui/url/7236b61d9ab9764250d4011dec2d322371652a3160903a5d071e838de380fc47/detection
