### ISSUE TITLE
Peacock starting showing ads

### ISSUE THREAD

**Issue by Movisivi** [uBlockOrigin/uAssets#8532]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.peacocktv.com/watch/playback/vod/GMO_00000000009305_01/db8364f6-f050-36b2-934d-b9af48092947`

### Describe the issue

 

Ads randomly started playing today. 

### Versions

- Browser/version: Firefox Nightly 86
- uBlock Origin version:  v1.33.2

### Settings

-

**Comment by uBlock-user** [comment]
> https://www.peacocktv.com/watch/playback/vod/GMO_00000000009305_01/db8364f6-f050-36b2-934d-b9af48092947

Redirects to `https://www.peacocktv.com/getpremium?return=%2Fwatch%2Fasset%2Ftv%2Fbrooklyn-nine-nine%2F5265505461484962112%2Fseasons%2F2%2Fepisodes%2Fchocolate-milk-episode-2%2Fdb8364f6-f050-36b2-934d-b9af48092947%3Fsection%3Depisodes` so can't be tested without a premium account.

**Comment by Movisivi** [comment]
This should get you in without an account `https://www.peacocktv.com/watch/playback/vod/GMO_00000000059625_01/58fabbf4-9291-3575-bcdc-bd25eee192c8` My bad.

**Comment by mapx-** [comment]
test

```
||video-ads-module.ad-tech.nbcuni.com/$xhr,redirect=nooptext,domain=peacocktv.com
@@||peacocktv.com^$ghide
```

**Comment by Movisivi** [comment]
Yup that indeed fixes it! Thank you

**Comment by uBlock-user** [comment]
> This should get you in without an account

They're also detecting VPN...
