### ISSUE TITLE
Linkvertise no longer blocking and now site is detecting the adblock

### ISSUE THREAD

**Issue by flomanto** [uBlockOrigin/uAssets#8533]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

-

**Comment by JobcenterTycoon** [comment]
Example: ` https://linkvertise.com/72834/M00nfrmatn`
