### ISSUE TITLE
upload.ee

### ISSUE THREAD

**Issue by P0Rtvine** [uBlockOrigin/uAssets#8534]
### URL(s) where the issue occurs

`https://www.upload.ee/files/12839313/b90f60019962e302bf6fa8478c602aa6.gif.html`

### Describe the issue

Ads

### Screenshot(s)
<details>
<summary>Screen</summary>

![2021-02-04_131253](https://user-images.githubusercontent.com/57287308/106885044-bdf0fe00-66ea-11eb-9919-55f872d8de2e.png)
![2021-02-04_131306](https://user-images.githubusercontent.com/57287308/106885054-c0ebee80-66ea-11eb-84fa-d17aeeb1d33d.png)
</details>

### Versions

- Browser/version: Google Chrome
- uBlock Origin version:  1.33.2

### Settings
<details>
<summary>Screen</summary>

![2021-01-22_100714](https://user-images.githubusercontent.com/57287308/105464158-c3395c00-5c99-11eb-965b-81215d8f7bec.png)
</details>

**Comment by dportvine** [comment]
`https://www.upload.ee/files/16237853/noads.jpg.html`

<details>
<summary>Screen</summary>

![2024-02-03_175635](https://github.com/uBlockOrigin/uAssets/assets/111344219/43a910f1-20dc-4124-9bb5-b95c59a427f9)
![2024-02-03_175651](https://github.com/uBlockOrigin/uAssets/assets/111344219/46d9bdf7-471b-400d-bea5-da5ac391cdb0)
</details>


<details>

```yaml
uBlock Origin: 1.55.0
Firefox: 122
filterset (summary):
 network: 116189
 cosmetic: 45333
 scriptlet: 18839
 html: 2072
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 37467-222, now
  ublock-badware: 7812-10, now
  ublock-privacy: 994-0, now Δ
  ublock-unbreak: 2252-0, now
  ublock-quick-fixes: 156-0, now
  easylist: 80128-562, now Δ
  easyprivacy: 43623-840, now Δ
  urlhaus-1: 8000-0, 1m
  plowe-0: 3784-1, now
filterset (user): [empty]
userSettings:
 advancedUserEnabled: true
 contextMenuEnabled: false
 showIconBadge: false
hiddenSettings:
 filterAuthorMode: true
 popupPanelHeightMode: 1
supportStats:
 allReadyAfter: 3144 ms
 maxAssetCacheWait: 9 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 8
 network:
  addthis.com: 4
  du0pud0sdlmzf.cloudfront.net: 2
  googlesyndication.com: 1
  googletagmanager.com: 1
 extended:
  ##+js(nowebrtc)
```
</details>

**Comment by mapx-** [comment]
`upload.ee##[href*=".php"]`

@ryanbr
