### ISSUE TITLE
Popups appearing on voe.sx

### ISSUE THREAD

**Issue by Esokrates** [uBlockOrigin/uAssets#8536]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

Disclaimer: The following link contains a video that clearly infringes copyright, it is only linked here as an example to reproduce the issue.
https://voe.sx/txzjbymzdvjz

### Describe the issue

 

When clicking the play button on the linked video, links to spam sites are opened in new tabs.

### Versions

- Browser/version: Firefox 84
- uBlock Origin version: 1.33.2

### Settings

Default settings

**Comment by mapx-** [comment]
update your lists before reporting

**Comment by Esokrates** [comment]
@mapx- I did and I even repeated it now, still happens. Not reproducible in Chromium though. Any idea what the culprit could be?

**Comment by mapx-** [comment]
I cannot reproduce popups in FF

**Comment by mapx-** [comment]
However, they fighted back twice today

**Comment by Esokrates** [comment]
@mapx- Please, could you carefully check again? It's 100% reproducible for me, see here, with a completely fresh profile:
https://youtu.be/V_ejd3CREA4

**Comment by Esokrates** [comment]
Also reproduced with the latest firefox 85 from Flathub.

**Comment by mapx-** [comment]
After installing uBO, did you update all lists ? ("purge all caches", then "update now")

**Comment by mapx-** [comment]
hmm, no .. they already changed the page code

**Comment by Esokrates** [comment]
@mapx- Yes, I did, just not in the video I uploaded. Please reopen this issue here.

**Comment by mapx-** [comment]
add
`voe.sx##^script:has-text(&key=)`

**Comment by Esokrates** [comment]
@mapx- Thanks, that works, is that already committed somewhere?
