### ISSUE TITLE
MAKO.co.il discovers uBO

### ISSUE THREAD

**Issue by blephmstr** [uBlockOrigin/uAssets#8537]
Hello,
I'm using the latest version of Chrome with the latest version of uBO on MacOS (also on the latest version). 
The website `https://www.mako.co.il/mako-vod-live-tv/` discovers the adblock and I can't watch the video. You need to register (for free) so you could watch the content. 

I would appreciate a fix!

Thanks

**Comment by mapx-** [comment]
Did you enable `ISR: EasyList Hebrew` ?

I'm able to watch free content (your link point to paid content)
`https://www.mako.co.il/mako-vod-music24/skaat_with_medalie-s1/VOD-e1d59e45ba35171026.htm?sCh=c7bbbe8b8e841710&pId=957463908`

**Comment by mapx-** [comment]
However, if still happens you should follow this repository (issue):

https://github.com/easylist/EasyListHebrew/issues/357

**Comment by blephmstr** [comment]
> Did you enable `ISR: EasyList Hebrew` ?
> 
> I'm able to watch free content (your link is pointing to paid content)
> `https://www.mako.co.il/mako-vod-music24/skaat_with_medalie-s1/VOD-e1d59e45ba35171026.htm?sCh=c7bbbe8b8e841710&pId=957463908`

I had to enable it. That did the trick :) thanks!
