### ISSUE TITLE
www.foodnetwork.com

### ISSUE THREAD

**Issue by Mezito80** [uBlockOrigin/uAssets#854]
### URL(s) where the issue occurs

http://www.foodnetwork.com/

### Describe the issue

There is an anti-adblock banner at the bottom of the page to 'Turn Off Adblocker.' You can not make it dissapear without turning off uBlock Origin.

### Screenshot(s)

https://screenshots.firefox.com/XSJsWj3U1NtbRRok/www.foodnetwork.com

### Versions

- Browser/version: FF 57
- uBlock Origin version: 1.14.18
### Settings

- No changes

### Notes
I have tried using only Privacy Badger without any positive results. I have discovered that turning on Adguard Annoyance List clears up the issue, but I'd rather use uBlock Origin with default settings. Thanks for your assistance and consideration.

**Comment by uBlock-user** [comment]
`||adsales.snidigital.com^`

**Comment by Mezito80** [comment]
The filter rule did not work. It seemed to create a blank placeholder at the top of the page.

Without Filter rule:
https://screenshots.firefox.com/tbhuPdVUCFxWaiwP/www.foodnetwork.com

With Filter rule: (It seems that a blank placeholder for an ad is created)
https://screenshots.firefox.com/yYtqSalYVcvCWRv8/www.foodnetwork.com

**Comment by mapx-** [comment]
add
`||assets.sni-dat.com/raven/raven.js`

**Comment by uBlock-user** [comment]
Works for me, that's all I have blocked from that domain and I can't reproduce it.

**Comment by Mezito80** [comment]
May I ask a different question: What list or filter rules should I have in place to avoid social networks from tracking my activity?

**Comment by uBlock-user** [comment]
Fanboy Anti Third-party Social, Adguard Social Media Filter and many more you can find at filterlists.com
