### ISSUE TITLE
malwat.ch

### ISSUE THREAD

**Issue by etpjhwpknwk** [uBlockOrigin/uAssets#8540]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://malwat.ch/malware`

### Describe the issue
(Site visited directly)
Malware links/downloads
 

### Versions

- Browser/version: Google Chrome 88.0.4324.150 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.32.4

### Settings

- Default

### Notes
https://www.virustotal.com/gui/url/b81c92b593685ef8d073125511b951edb687c67edf2b0488cc8cdc8e4beaa9d9/detection
Domain blocked by OpenDNS: ![image](https://user-images.githubusercontent.com/77238694/107118007-74391c80-687e-11eb-95b5-9e0976c1a194.png)

**Comment by okiehsch** [comment]
That's the website of https://github.com/Endermanch

He provides malware samples.
![image](https://user-images.githubusercontent.com/16838044/107118943-85852780-6884-11eb-8f89-90dd8bb0066e.png)

**Comment by etpjhwpknwk** [comment]
I didn't check who it belonged to, I just saw that it was marked malicious by multiple AV companies and also that I actually had to make an exception in my OpenDNS settings so I could even visit the page because they blocked it due to "Phishing", but if it belonging to someone who is on GitHub makes it so hosting malware is actually okay, then so be it.

**Comment by okiehsch** [comment]
I posted the link and the screenshot to make it clear that the intent of the site is to provide malware samples and that the site makes that abundantely clear.
I can understand that some AV  block the site and that you thought it was a malicious stie because of that.
