### ISSUE TITLE
1plus1.video

### ISSUE THREAD

**Issue by dimisa-RUAdList** [uBlockOrigin/uAssets#8542]
When placing the player frame on third-party sites, the video quality is limited to 360p: 
`https://glavpost.ua/videos/prostoy-retsept-na-vykhodnye-gotovim-yablochnyy-pirog-po-niderlandski/` 

There is no limitation on the original video address: 
`https://1plus1.video/ru/novosti-snidanku-z-11/2021/1-vypusk-prostij-recept-na-vihidni-gotuemo-yabluchnij-pirig-po-niderlandski`

<details>
<summary>Config</summary>

Google Chrome 88.0.4324.150
Firefox 85.0.1
uBlock Origin 1.33.3b0 default + [RU AdList](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/advblock%2Bcssfixes.txt&title=RU%20AdList%20for%20uBlock%20Origin), [Counters](https://subscribe.adblockplus.org/?location=https://easylist-downloads.adblockplus.org/cntblock.txt&title=RU%20AdList:%20Counters)
</details>

**Comment by uBlock-user** [comment]
![Capture](https://user-images.githubusercontent.com/21290713/107144986-a45aeb00-6964-11eb-9525-e5dc81927de0.PNG)

Works with referrer spoofing(done via uMatrix) on my end.

**Comment by dimisa-RUAdList** [comment]
Yes, blocking the referrer solves the problem. However, there is no such feature in uBO.

So far I have worked directly on the player functions, as for example here: https://hg.adblockplus.org/ruadlist/rev/41b1597dbdde#l1.12

But in the case of 1plus1.video, the player's code is partially obfuscated and minified, which means that in order to create rules for it, you first need to do decoding and debugging.

It would be much more convenient for filter authors if there was a scriptlet like "referrer-cleaner".

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/issues/3604

@gorhill

**Comment by gorhill** [comment]
> When placing the player frame on third-party sites, the video quality is limited to 360p

So the issue would still happen without uBO?

**Comment by uBlock-user** [comment]
> So the issue would still happen without uBO?

Yes.

**Comment by uBlock-user** [comment]
AdGuard comes with Stealth Mode where one of the functionalities is blocking referrer info from third-parties, so the issue will not occur with AdGuard with SM enabled.

**Comment by gorhill** [comment]
I tried to reproduce with RU AdList and without Counters, and I can use higher resolutions on my side.

**Comment by dimisa-RUAdList** [comment]
The problem was solved in an alternative way: https://hg.adblockplus.org/ruadlist/rev/e8b269a56178

**Comment by dimisa-RUAdList** [comment]
It would be much more convenient for filter authors if there was a scriptlet like "referrer-cleaner".

**Comment by P0Rtvine** [comment]
@gorhill
What's stopping you from making changes? In the future, the functionality will still have to be expanded.
