### ISSUE TITLE
LCPDFR.com ad spaces

### ISSUE THREAD

**Issue by Alex4567890** [uBlockOrigin/uAssets#8546]
### Prerequisites
- [X] This is not a support issue or a question
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
https://www.lcpdfr.com/lspdfr/
### Describe the issue
The spaces for ads, they can be picked with the element picker, I just wanted to let you know.

### Screenshot(s)
![Screenshot_11](https://user-images.githubusercontent.com/78655307/107203111-ad4ec980-6a03-11eb-9ec9-76c1da147445.png)
![Screenshot_12](https://user-images.githubusercontent.com/78655307/107203115-ae7ff680-6a03-11eb-88c8-7fc23ba4c40a.png)
I took the second screenshot after scrolling down as far as I could.
### Versions

- Browser/version: Firefox Version 85.0.1 (64-bit)
- uBlock Origin version: 1.33.2

### Settings
Only a couple filter lists for other websites.

### Notes
www.lcpdfr.com##div.ipsSpacer_top > .ipsAreaBackground.ipsPad
www.lcpdfr.com###ipsLayout_mainArea > .ipsAreaBackground.ipsPad
Seemed to remove the areas.

**Comment by uBlock-user** [comment]
`lcpdfr.com##.ipsAreaBackground.ipsPad`

@ryanbr

**Comment by Fogest** [comment]
https://www.lcpdfr.com/forums/topic/111732-using-an-adblocker-disable-it-before-reporting-an-issue/?tab=comments#comment-678322

This change breaks key features of the site.

**Comment by Alex4567890** [comment]
There still is one. It can be observed when scrolling to the bottom.
