### ISSUE TITLE
728x90.jpg| - the rule doesn't work 

### ISSUE THREAD

**Issue by P0Rtvine** [uBlockOrigin/uAssets#8548]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

`728x90.jpg|` ~> **EasyList** - doesn't work in uBO, but works in ABP.

### A specific URL where the issue occurs

`http://progolovne.ck.ua/`

### Steps to Reproduce

1. Go to `http://progolovne.ck.ua/`
2. [Second Step]
3. [and so on...]

### Expected behavior:

Hiding an element

<details>
<summary>Screen - uBO</summary>

![7yPv1o](https://user-images.githubusercontent.com/57287308/107215683-4ede1700-6a14-11eb-8a62-9023536c9086.png)
</details>

<details>
<summary>Screen - ABP</summary>

![2021-02-08_140217](https://user-images.githubusercontent.com/57287308/107217150-71712f80-6a16-11eb-90ac-0fcdb6433f25.png)
</details>

### Actual behavior:

Element is not hidden

<details>
<summary>Screen</summary>

![7yPv1z](https://user-images.githubusercontent.com/57287308/107215927-b005ea80-6a14-11eb-8a42-ba7861f37f12.png)
![7yPv1A](https://user-images.githubusercontent.com/57287308/107215932-b1cfae00-6a14-11eb-9bc5-e13957559963.png)
</details>

### Your environment

* uBlock Origin version: 1.33.2
* Browser Name and version: Google Chrome ( 88.0.4324.150)
* Operating System and version: Windows 8.1x64

**Comment by gorhill** [comment]
I transfered here because we should add `ad728x90.jpg`?

**Comment by gorhill** [comment]
cc @dimisa-RUAdList

**Comment by uBlock-user** [comment]
It's a telegram group link of that website. not an ad. Should we still block it ?

**Comment by dimisa-RUAdList** [comment]
No, you don't need to add anything. Specifically this problem was solved here: https://github.com/easylist/ruadlist/commit/ba2a92e800b31d4149134eb0c0232f20550aa3b2#diff-f755aab522aa5f7274e4a9cae748b359c0910553178eb3d00504408c376ad826R1116

In general, the point was that some of the rules really do not work. But in most cases, I fix this with additional rules.
