### ISSUE TITLE
TD Ameritrade saved account application complete application page breaks with uBlock Origin enabled

### ISSUE THREAD

**Issue by jasonkhanlar** [uBlockOrigin/uAssets#8549]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://invest-tx.tdameritrade.com/grid/p/completeApplication`

but only after logging in to account, and during account creation sequence that previously was saved to continue later

### Describe the issue

 
After logging in to an account that the application process is not fully completed, saved for later, during next login attempt, directing to this page that immediately appears at log in, with uBlock Origin enabled, there are JavaScript errors and the page appears blank/empty. With uBlock Origin disabled, the page loads fine.

Console shows these lines only when uBlock Origin is enabled during the page load:
```
dojo.js.uncompressed.js:1833 GET https://invest-tx.tdameritrade.com/release/ent/module/OpinionLab/Static/Anchor.js?dev_OLA_2020.12_21.1_Build_14 net::ERR_BLOCKED_BY_CLIENT

dojo.js.uncompressed.js:7329 Error: scriptError
    at p (dojo.js.uncompressed.js:327)
    at HTMLScriptElement.<anonymous> (dojo.js.uncompressed.js:1804)

dojo.js.uncompressed.js:7329 Error: timeout
    at p (dojo.js.uncompressed.js:327)
    at dojo.js.uncompressed.js:1
```

### Versions

- Browser/version: Chromium Version 88.0.4324.146 (Official Build) Arch Linux (64-bit)
- uBlock Origin version: v1.32.4

### Settings

- I don't remember, but I don't think any of the settings would affect

### Notes

I didn't pursue much investigation, since it is not an immediately important concern (as of yet), since so far, it only seems to affect the single page, which is part of account creation process, and if might not happen after I complete the application, but I thought it is worth mentioning anyway in case anyone else doesn't know. I was almost prepared to contact the website to let them know their website is broken.

**Comment by uBlock-user** [comment]
Add `@@||invest-tx.tdameritrade.com/release/ent/module/OpinionLab/Static/Anchor.js^$script,1p` to my filters and report back.
