### ISSUE TITLE
Pocket Now

### ISSUE THREAD

**Issue by Mezito80** [uBlockOrigin/uAssets#855]
### URL(s) where the issue occurs

http://pocketnow.com/2017/11/19/sprint-black-friday-essential-phone-deal

### Describe the issue

It looks like advertisement at the top of the page which is not blocked. It takes about 5 seconds, after the page has loaded, for the ads to show up.

### Screenshot(s)

https://screenshots.firefox.com/BEBOElrNQNZq1YR1/pocketnow.com

### Versions

- Browser/version: FF 57
- uBlock Origin version: 1.14.18
### Settings

- No changes

### Notes

I have not tried any workarounds. Thank you for your assistance and consideration.

**Comment by uBlock-user** [comment]
`||pocketnow.com/*/uponit.js^`

**Comment by Mezito80** [comment]
That worked! Thank you
