### ISSUE TITLE
Pbinfo.ro (a romanian website) Ad Spaces + Message regarding my ad blocking module after removing the ad spaces

### ISSUE THREAD

**Issue by Alex4567890** [uBlockOrigin/uAssets#8551]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [] uBlock Origin with default lists/settings
    - []using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://pbinfo.ro`

### Describe the issue

I don't want to see the ad spaces/blocks. Removing the ad spaces/blocks seems to trigger a message regarding my ad blocking module.

### Screenshot(s)
1.
![Screenshot_19](https://user-images.githubusercontent.com/78655307/107393471-84adf900-6b03-11eb-9659-d51173634a99.png)
2.
![Screenshot_20](https://user-images.githubusercontent.com/78655307/107393188-2da82400-6b03-11eb-87ed-c92ad6fa4f79.png)
3.
![Screenshot_21](https://user-images.githubusercontent.com/78655307/107393194-300a7e00-6b03-11eb-97a5-64e21acc15e0.png)

### Versions

- Browser/version: Firefox Version 85.0.1 (64-bit)
- uBlock Origin version: 1.33.2

### Settings

Filter lists: the default filter lists + Fanboy’s Annoyance + uBlock filters – Annoyances + Romanian Ad (ROad) Block List Light

**Comment by mapx-** [comment]
Is it an annoyance or you cannot use the site ?

test
```
pbinfo.ro##div.center.well-sm.well
pbinfo.ro##+js(set, pbi_analytics, true)
```

**Comment by Alex4567890** [comment]
> 
> 
> Is it an annoyance or you cannot use the site ?
The message about the adblocker or whatever is an annoyance since it does not restrict the access to the website.
The ad spaces could be added to EasyList or uBlock filters I think.

**Comment by Alex4567890** [comment]
> ```
> pbinfo.ro##div.center.well-sm.well
> pbinfo.ro##+js(set, pbi_analytics, true)
> ```
The filters work, the only problem is that the message about my adblocking module or whatever isn't there anymore even without uBlock -- Annoyances.

**Comment by Alex4567890** [comment]
> ```
> pbinfo.ro##div.center.well-sm.well
> ``` could be added in uBlock filters or EasyList.

And the other filter could be added in uBlock -- Annoyances.
