### ISSUE TITLE
htmlgames.com annoying message about the adblocker

### ISSUE THREAD

**Issue by Alex4567890** [uBlockOrigin/uAssets#8554]
### Prerequisites
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.htmlgames.com/`

### Describe the issue
Banner(s) telling me I have an AdBlocker.
### Screenshot(s)

![Screenshot_23](https://user-images.githubusercontent.com/78655307/107410647-4110ba80-6b16-11eb-91d9-f22337a0dfcc.png)

![Screenshot_23](https://user-images.githubusercontent.com/78655307/107409916-4f120b80-6b15-11eb-9fee-e54e391101b8.png)

### Versions

- Browser/version: Firefox 85.0.1
- uBlock Origin version: 1.33.2

### Settings

Default filter lists + Fanboy's Annoyance + uBlock filters – Annoyances + Romanian Ad (ROad) Block List Light

**Comment by Alex4567890** [comment]
they/it appear/appears at least two more times.

**Comment by IThinkIAmCool** [comment]
I think this should be addressed in EasyList. I added `htmlgames.com#@#.banner` and only saw somethings that looked like placeholders but no anti-adb.

**Comment by uBlock-user** [comment]
@IThinkIAmCool Add `@@*$redirect-rule` too and you will see anti-adblock banners.
