### ISSUE TITLE
Problems loading videos from external server (Hydrax)

### ISSUE THREAD

**Issue by T-Tar** [uBlockOrigin/uAssets#8557]
### Prerequisites

- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x ] I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [ x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
´https://moviesjoy.to/watch-tv/the-office-39383.2198050´
´https://moviesjoy.to/watch-tv/the-office-39383.2197660´

### Describe the issue
Since yesterday (10/2-2021) I'm unable to load streamed videos from Hydrax servers. The page loads normally without ads but when you press play a "disable ad-block prompt" appears. This might seem very specific but it's one of the biggest and most reliable servers. Also I have seen the same issue in the past from other streaming servers. I guess they pretty much say what needs to be done (see screenshot). This might be a common variation of existing issues but I haven't seen this kind before hence the report. 

 

### Screenshot(s)
![image](https://user-images.githubusercontent.com/71447433/107613984-b7620980-6c49-11eb-9022-876fb058b8cc.png)

### Versions

- Browser/version: Chrome Version 88.0.4324.150
- uBlock Origin version: uBlock Origin v1.33.2

### Settings
- Only running default settings

### Notes
I barely use any other extensions and I have tried running with only uBO activated.

EDIT: Also cleared cache and made sure to update my filters.

**Comment by mapx-** [comment]
Did you update `uBlock filters` list before reporting ?

**Comment by T-Tar** [comment]
> Did you update `uBlock filters` list before reporting ?

Yes I did! Cleared cache and updated again to be sure.

**Comment by mapx-** [comment]
Do you get (see in the logger) this filter

`*$popup,3p,domain=redirect-ads.com`

**Comment by T-Tar** [comment]
Well, it works now. Restarted browser and did a cache clear again. Seems something wasn't up to date in the end... Sorry if I wasted you time but thanks for your help anyway @mapx- , now I know more things to try before reporting in the future!

**Comment by mapx-** [comment]
It was fixed yesterday => the reason I asked you about updating the uBO main list

**Comment by T-Tar** [comment]
> It was fixed yesterday => the reason I asked you about updating the uBO main list

I see! Although the box for automatic updates was ticked and "Update now" button grayed out from the start when the problems started but that might be another issue. I'm sure it wasn't working before I manually updated the list after cache clear.

**Comment by mapx-** [comment]
The lists are automatically updated every 4 days .. so only updating manually (clar cache too etc) you could get last updates for such pages
