### ISSUE TITLE
indystar.com

### ISSUE THREAD

**Issue by Mezito80** [uBlockOrigin/uAssets#856]
### URL(s) where the issue occurs

https://www.indystar.com/story/news/2017/11/22/where-they-now-greenwood-dad-3-continues-fight-his-life/868818001/

https://www.indystar.com/story/news/local/2017/11/22/changes-coming-2017-circle-lights-downtown-indianapolis/884541001/

### Describe the issue

The play button for videos appear, but when clicked nothing happens.

### Screenshot(s)

N/A

### Versions

- Browser/version: FF 57
- uBlock Origin version: 1.14.18
### Settings

- [List here all the changes you made to uBO's default settings]

Added:
-Adguard Base Filters
- Fanboy's Social Blocking

**Comment by gorhill** [comment]
I can make the video playback button work with the filter below, but the video does not playback, including if disabling uBO:

    @@||cpt-static.gannettdigital.com^$domain=indystar.com

**Comment by Mezito80** [comment]
I see what you mean. I tried the same set-up on Chrome and the videos played. It must be Firefox related. Thank you for your help.

**Comment by mapx-** [comment]
working for me in FF 58.0b9 (64-bit)
```
@@/video-ads.html$xmlhttprequest,domain=indystar.com
@@*indystar*$xmlhttprequest,domain=imasdk.googleapis.com
```

**Comment by mapx-** [comment]
@ryanbr @monzta
