### ISSUE TITLE
msn.com/en-us/entertainment top banner or whatever

### ISSUE THREAD

**Issue by Alex4567890** [uBlockOrigin/uAssets#8563]
It/they appear/appears on: msn.com/en-us/entertainment & msn.com/en-us/entertainment/gaming

I had one about Microsoft Edge or whatever and one about Microsoft News Extension.

`||msn.com/en-us/entertainment/irisbannerajax?position=top&canvas=vlp$xhr,domain=www.msn.com` fixes it/them

It's up to the filter lists maintainers if they will or will not add a filter to prevent the banner(s) from appearing.

**Comment by mapx-** [comment]
as I said, you could report such banners at easylist repository

`msn.com###irisbanner`

@ryanbr

**Comment by Alex4567890** [comment]
> 
> 
> as I said, you could report such banners at easylist repository
Is it not a high traffic website?

**Comment by mapx-** [comment]
It will be added to easylist if reported, did you already report the banner at EL repository ?

**Comment by Alex4567890** [comment]
> 
> 
> It will be added to easylist if reported, did you already report the banner at EL repository ?

No, but is it needed? Won't he see this issue?
