### ISSUE TITLE
gaming-style.com/RushTeam/index.php?page=Game - my ad-blocker is detected

### ISSUE THREAD

**Issue by Alex4567890** [uBlockOrigin/uAssets#8564]
`https://www.gaming-style.com/RushTeam/index.php` -> Play now
I'm using uBlock Origin 1.33.2
Filter lists: Default + Fanboy's Annoyance + uBlock -- Annoyances
(I know about uBO being a wide-spectrum blocker.)

**Comment by sugarfreesweetener** [comment]
@mapx- I guess https://github.com/uBlockOrigin/uAssets/blob/528ec68e5dd7488d47aca28812014aa5133de503/filters/filters-2020.txt#L1706-L1707 could be removed from `filters-2020.txt` due to https://github.com/uBlockOrigin/uAssets/commit/bc627ba01be8f1b3d541c2ad50aa7b6c3ca9f3b2
