### ISSUE TITLE
ProSiebenSat.1 Media Livestreams & VOD detect adblock

### ISSUE THREAD

**Issue by Magicool-1** [uBlockOrigin/uAssets#8567]
### URL(s) where the issue occurs
(these are all owned by the same company and the websites are using identical backend, only difference is of course they are modified to represent the corresponding TV channel)

Livestreams:
```
https://www.kabeleins.de/livestream
https://www.prosieben.de/livestream
https://www.prosiebenmaxx.de/livestream
https://www.kabeleinsdoku.de/livestream
https://www.sixx.de/livestream
https://www.sat1.de/livestream
https://www.sat1gold.de/livestream

```

VOD:
```
https://www.kabeleins.de/videos
https://www.prosieben.de/video
https://www.prosiebenmaxx.de/video
https://www.kabeleinsdoku.de/mediathek
https://www.sixx.de/video
https://www.sat1.de/videos
https://www.sat1gold.de/video
```

### Describe the issue

When opening any of the livestreams with uBO running the player stays completely black after hitting play.
VOD dont even show the play button with uBO active. 
When disabling uBO to start video and then enabling uBO again adblock detection warning shows up

### Screenshot(s)

![adblock](https://user-images.githubusercontent.com/12387733/107771399-fde36100-6d3a-11eb-9b86-378214311565.png)

### Versions

- Browser/version: Firefox 87.0a1 (2021-02-12) (64-Bit)
- uBlock Origin version: 1.33.3b0

### Settings

![adblocksettings](https://user-images.githubusercontent.com/12387733/107772150-215adb80-6d3c-11eb-96ac-8472c24a35ac.jpg)
![filters](https://user-images.githubusercontent.com/12387733/107772151-21f37200-6d3c-11eb-8b72-cf342b87e1be.png)

### Notes
-

**Comment by mapx-** [comment]
tested the first 1 `https://www.kabeleins.de/livestream` => all fine on my end.
You should reset uBO to default settings, update all lists and test again

**Comment by Magicool-1** [comment]
Huh, I tried with default settings  (resetting via UI and the issue stayed) before opening the ticked and the issue remaind.
So I tried just now again with resetting settings and it indeed did work ads blocked and video/streams available. 
I will see with of the filter list/setting is interfiering with it and see if I can live without out. 
You can close this then :)
