### ISSUE TITLE
issue "bloomberg video content #8317" was resolved but now is not working again  

### ISSUE THREAD

**Issue by jahnson** [uBlockOrigin/uAssets#8568]
I do not see how to re-open an issue.  
Please see issue #8317, the problem is identical.  

The solution suggested there worked for me, almost daily until now, but as of today it does not.  
With uBlockOrigin off it plays, 

The same sample URL I gave there does not play, or you could also try this one:
`https://www.bloomberg.com/news/videos/2021-02-12/solar-industry-can-t-escape-ties-to-xinjiang-china-video`

- Browser/version: 84.0.2 
- uBlock Origin version: 1.33.2 

Thank you in advance.

**Comment by mapx-** [comment]
add

`@@||sourcepointcmp.bloomberg.com/ccpa.js$script,domain=bloomberg.com`

**Comment by jahnson** [comment]
Yup, that resolved it again.  
Thank you!
