### ISSUE TITLE
[Filter? Firefox issue?] Fullscreen popup trying to install plugin

### ISSUE THREAD

**Issue by onetimereporting** [uBlockOrigin/uAssets#857]
### URL(s) where the issue occurs

`http://www.finalupdater.com/firefox/?clickid=w4F1LUJURF40E2S915KF77QK&language=en`
(page opened as a pop-under on //putlockers.movies)

### Describe the issue
even with uBlockOrigin I've encountered a new(?) scheme repeatedly:

1. Websites prompts for username + password via http: "Click cancel to continue!"
2. Message-popup: "You have to install a firefox update - OK / Cancel"
3. Message-popup: "Firefox has to resend form data - Resend / Cancel"
4. Firefox enters Fullscreen-mode automatically
5. Website tries to install some kind of plugin (malware?)

cycle repeats at 1. if you exit fullscreen mode 
until you are able to close the page via keyboard-shortcut (or install plugin) 

### Versions

- Browser/version: Firefox Quantum 57.0 (64bit)
- uBlock Origin version: 1.14.18

### Settings

- uBO's default settings

**Comment by okiehsch** [comment]
The fix prevents the popup/under which causes you to end up with the obvoiusly malicious "plugin" installer.

> until you are able to close the page via keyboard-shortcut (or install plugin)

Never, ever install the plugin.
