### ISSUE TITLE
Audit of domains in uAssets (possibly dead domains)

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uAssets#8570]
While auditing Easylist, I've run PyFunceble https://github.com/funilrys/PyFunceble

It won't pick up wildcard'd domains, onion domains, or IP's and occasionally false positives. But it should give authors an idea if it needs to be checked. See INACTIVE

Was ran on 14/02/2021:

done => `Filters.txt:` https://secure.fanboy.co.nz/uBO-Cleanup/ubo-filters.txt
done => `Filters-2020.txt` https://secure.fanboy.co.nz/uBO-Cleanup/ubo-fiilters-2020.txt
done => `Filters-2021.txt` https://secure.fanboy.co.nz/uBO-Cleanup/ubo-fiilters-2021.txt
done => `Annoyances.txt:` https://secure.fanboy.co.nz/uBO-Cleanup/ubo-annoy.txt
done => `Badware.txt:` https://secure.fanboy.co.nz/uBO-Cleanup/ubo-badware.txt
done => `Unbreak.txt` https://secure.fanboy.co.nz/uBO-Cleanup/ubo-unbreak.txt

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/107849284-8a088d80-6dfa-11eb-9e5a-80455537d17a.png)

**Comment by ryanbr** [comment]
Fixed.

**Comment by mapx-** [comment]
maybe with blogspot has some issues => `eskiceviri.blogspot.com` seems ok

**Comment by ryanbr** [comment]
Yeah, I think blogspot is one of those false positives

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/107851184-43219480-6e08-11eb-86ce-98cad96d89ba.png)

thanks
