### ISSUE TITLE
fakty.com.ua

### ISSUE THREAD

**Issue by P0Rtvine** [uBlockOrigin/uAssets#8576]
### URL(s) where the issue occurs

`https://fakty.com.ua/ua/ukraine/20210214-na-donbasi-zagynuly-troye-bijtsiv-zsu-pidirvavshys-na-nevidomomu-vybuhovomu-prystroyi/`

### Describe the issue

`#@#div[class^="div-gpt-ad"]` ~> **uBlock filters**

### Screenshot(s)
<details>
<summary>Screen</summary>

![image](https://user-images.githubusercontent.com/57287308/107916172-88f86d00-6f6e-11eb-969b-d7110fcb607d.png)
</details>

### Versions

- Browser/version: Google Chrome
- uBlock Origin version:  1.33.2

### Settings
<details>
<summary>Screen</summary>

![2021-01-22_100714](https://user-images.githubusercontent.com/57287308/105464158-c3395c00-5c99-11eb-965b-81215d8f7bec.png)
</details>

**Comment by P0Rtvine** [comment]
Maybee?
`*##.div-gpt-ad:style(width:1px!important;height:1px!important;min-height:1px!important;)`
`*##div[class^="div-gpt-ad"]:style(width:1px!important;height:1px!important;min-height:1px!important;)`

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/cf32466cc74ddf15e42c0d2d249152c5cf38f5ef
https://github.com/uBlockOrigin/uAssets/commit/163f828090a3d78b1d8ee98dafd08a65b93f1f7f
