### ISSUE TITLE
I got an ad on alibaba.com

### ISSUE THREAD

**Issue by Alex4567890** [uBlockOrigin/uAssets#8579]
When I searched for something on the website I got an ad.

**Comment by mapx-** [comment]
For complex pages like alibaba you have to provide useful info on how to reproduce the issue.

**Comment by Alex4567890** [comment]
> 
> 
> When I searched for something

I just used the search bar (I clicked on the search bar, typed 'radio' and then pressed enter i think)

**Comment by uBlock-user** [comment]
Do not remove the template, it exists for a reason, fill it in.

**Comment by mapx-** [comment]
yeah, you get an _Ad_ but clicking it you'll land on the same alibaba (on some store hosted by the same alibaba) => it's self-promotion

![image](https://user-images.githubusercontent.com/10303732/107989858-6f3d4100-6fd3-11eb-8603-d8b79da2507b.png)

**Comment by Alex4567890** [comment]
Ok.
