### ISSUE TITLE
http://freebytecoin.cf

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#858]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://freebytecoin.cf`

### Describe the issue

Anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12802056/33150175-558c95b6-cfa0-11e7-9b6a-54f3d254ff59.png)

Page redirects to `http://freebytecoin.cf/blocker.php?ad2`

**Comment by mapx-** [comment]
```
@@||freebytecoin.cf^$generichide
freebytecoin.cf##script:inject(abort-current-inline-script.js, miner, isAdBlockActive)
```

**Comment by gotitbro** [comment]
@terrorist96 What a weird website. They run a faucet network and also use Coinhive to utilize a user's CPU resources.
