### ISSUE TITLE
britannica.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#8581]
### URL(s) where the issue occurs

`https://www.britannica.com/video/180277/crisis-deaths-Black-September-1972-Munich-Olympic-1972`

### Describe the issue

Video doesn't load

### Notes

`@@||britannica.com/resources/js/libs/prebid*.js$script,1p`

**Comment by mapx-** [comment]
@ryanbr

**Comment by Tim676o** [comment]
The issue persists...

**Comment by mapx-** [comment]
https://github.com/easylist/easylist/commit/88cd64679708d0d3ff9914628d2111c7f602ab55

**Comment by Tim676o** [comment]
> [easylist/easylist@88cd646](https://github.com/easylist/easylist/commit/88cd64679708d0d3ff9914628d2111c7f602ab55)

Thanks ! Even if I force update Easyprivacy though, the filters aren't changed. Is there a delay until this change is effectively taken into account in ublock ? Or there's more steps to achieve until the filters are fully re-updated ?

**Comment by mapx-** [comment]
if uBO (not uBOL):

use this link for updating the lists

https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=easyprivacy,ublock-annoyances&manual=1

or add this exception
`britannica.com#@#+js(abort-current-script, document.createElement, admiral)`
