### ISSUE TITLE
[Anti-adblock] userupload.net

### ISSUE THREAD

**Issue by Cyberavater** [uBlockOrigin/uAssets#8583]
Eg link: `https://userupload.net/qqn6sh46gcox`

OS: Android 10
Browser: kiwi

![Screenshot_20210216-222137837 (1)](https://user-images.githubusercontent.com/32187927/108091046-33f24f00-7073-11eb-83a3-ff992babfb69.jpg)

**Comment by mapx-** [comment]
already fixed, update your lists
