### ISSUE TITLE
Twitter.com is not working

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uAssets#8587]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

https://twitter.com/

### Describe the issue

A black screen is displayed.

### Screenshot(s)

<img width="1552" alt="screenshot" src="https://user-images.githubusercontent.com/62190484/108177024-fc32e800-7102-11eb-92b6-b136e2ef8506.png">

### Versions

- Browser/version: Google Chrome 88.0.4324.150
- uBlock Origin version: 1.33.2

### Settings

- Prevent WebRTC from leaking local IP address
- Block CSP reports

### Notes

Disabling uBlock Origin displays the screen correctly.

**Comment by okiehsch** [comment]
I can reproduce in inognito mode only.

**Comment by fabriziobagala** [comment]
As an operating system, I use macOS Big Sur 11.2.1.

**Comment by okiehsch** [comment]
It's weird only the homepage seems to be affected.

**Comment by okiehsch** [comment]
@fabriziobagala does adding
`twitter.com#@#[href*="/twitter-cookies"]:upward(3)`
work for you?

**Comment by fabriziobagala** [comment]
> @fabriziobagala does adding
> `twitter.com#@#[href*="/twitter-cookies"]:upward(3)`
> work for you?

Yep, this filter works for me.

**Comment by okiehsch** [comment]
Update the `uBO-annoyances` list in a few minutes, should fix the issue

**Comment by fabriziobagala** [comment]
> Update the `uBO-annoyances` list in a few minutes, should fix the issue.

I believe the label "unable to reproduce" is incorrect.

**Comment by uBlock-user** [comment]
> I can reproduce in incognito mode only.

exact page link ?

**Comment by okiehsch** [comment]
I use the english homepage. I don't have an account though, so I am not logged in.

**Comment by in4u** [comment]
https://github.com/uBlockOrigin/uAssets/commit/96c6ef4375b772df6d79c011f0739eae2cb46e7e is causing breakage now as it's hiding the login / signup block below the line `Join Twitter today.`

**Comment by AroKol78** [comment]
i have the same as in the previous comment
problem with (i checked) uBlock filters – Annoyances `twitter.com##[href*="/twitter-cookies"]:upward(2)`

**Comment by madsmtm** [comment]
Ping @mapx-
