### ISSUE TITLE
pcgamer.com white bar

### ISSUE THREAD

**Issue by Tiagoquix** [uBlockOrigin/uAssets#8589]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

``https://www.pcgamer.com/after-2-years-the-epic-games-store-is-still-a-golden-ticket-for-devs-and-irresistible-bait-for-gamers/``

### Describe the issue

There is a white bar on the bottom that is a bit annoying. Probably it shows an ad but since the ad isn't loaded, the bar just remains there and therefore I have to manually close it, which is annoying.

 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/30274161/108303657-10b7c480-7185-11eb-97bc-cddb02c1bdef.png)

### Versions

- Browser/version: Google Chrome 64 bits (Official Version) 88.0.4324.182
- uBlock Origin version: 1.33.2

### Settings

I use the default settings.

### Notes

No additional notes.

**Comment by Tiagoquix** [comment]
@okiehsch Hey! Thank you for the fix and for some improvements to the site.

I noticed that there is an empty space on the bottom of the article (maybe it is for ads) but I do not know exactly why it is there. It is present on every PC Gamer's articles.

![image](https://user-images.githubusercontent.com/30274161/108431457-a739c380-7221-11eb-9209-c52d4cc8286e.png)

The page element that creates this space is ``<div class="onesignal-customlink-container"></div>``.

![image](https://user-images.githubusercontent.com/30274161/108431549-c6385580-7221-11eb-83a3-51c69330701a.png)

Could you remove it too? The page is better without it.

![image](https://user-images.githubusercontent.com/30274161/108431690-f97ae480-7221-11eb-8e78-52819c399454.png)

Thanks in advance.

**Comment by Tiagoquix** [comment]
@okiehsch The white bar is appearing again.

Tested on some random articles, like these:

```
https://www.pcgamer.com/hp-to-acquire-hyperx-for-dollar245m/
https://www.pcgamer.com/activision-details-how-call-of-duty-cold-wars-zombies-outbreak-mode-will-actually-work/```

**Comment by gorhill** [comment]
I removed `pcgamer.com##div[style*="z-index:"]`, this was causing an issue, see <https://www.reddit.com/r/uBlockOrigin/comments/onzgyq/when_ublock_filters_is_enabled_it_blocks_stylebot/>. I didn't see white bar after removal.

**Comment by Tiagoquix** [comment]
> I removed `pcgamer.com##div[style*="z-index:"]`, this was causing an issue, see https://www.reddit.com/r/uBlockOrigin/comments/onzgyq/when_ublock_filters_is_enabled_it_blocks_stylebot/. I didn't see white bar after removal.

I see the white bar after the removal.

![image](https://user-images.githubusercontent.com/30274161/126877396-721e2b44-2f42-49ea-8907-b77431c2992e.png)
