### ISSUE TITLE
movieflixpro.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8593]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://movieflixpro.com/legacies-season-3-web-series-download/`

### Describe the issue

**Go to download** /download link not available 

### Screenshot(s)

![Screenshot_2021-02-18-16-50-42-550_org mozilla fenix](https://user-images.githubusercontent.com/20338483/108350254-07bd0680-720a-11eb-97bb-232f7fbbb8a5.png)

### Versions

- Browser/version: firefox A nightly
- uBlock Origin version: 1.33.2

### Settings

uBO's default settings
-

### Notes

No cosmetic filtering (ie generichide exception filter) works
![Screenshot_2021-02-18-16-57-31-809_org mozilla fenix](https://user-images.githubusercontent.com/20338483/108350715-96318800-720a-11eb-86b7-07df7b6076eb.png)

**Comment by mapx-** [comment]
working fine on my side

`@@||movieflixpro.com^$ghide`

or
`movieflixpro.com#@#.ads_single_center`

**Comment by ghajini** [comment]
Both of them will work
