### ISSUE TITLE
[Ads] deadtoonsindia.info

### ISSUE THREAD

**Issue by Cyberavater** [uBlockOrigin/uAssets#8595]
Eg link: `https://deadtoonsindia.info/`

![Screenshot (146)](https://user-images.githubusercontent.com/32187927/108412010-7b373600-7253-11eb-97bc-5564a23123a1.png)

**Comment by PIZZA90** [comment]
a simple picture can help xD, no ads for me. and al links redirect to: `https://techsmoon.com/`

**Comment by Cyberavater** [comment]
Screenshot added. Not really a full-fledged ad but it's still annoying.

**Comment by PIZZA90** [comment]
ohhh im using `AdGuard Annoyances` and no problem

**Comment by Cyberavater** [comment]
Okay, thanks for letting me know. So, it should be closed right?

**Comment by PIZZA90** [comment]
wait a developer anyways

**Comment by mapx-** [comment]
fixed by `Fanboy’s Annoyance` too

**Comment by uBlock-user** [comment]
https://github.com/easylist/easylist/commit/3a0e898560554f4e059c944826a5ef7019443396

moved to EasyPrivacy from Fanboy Annoyances, force update
