### ISSUE TITLE
Wayback Machine does not work for some or all sites

### ISSUE THREAD

**Issue by GoblinLegislator** [uBlockOrigin/uAssets#8597]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://web.archive.org/save/https://www.imdb.com/user/ur98727037/ratings`

### Describe the issue

I wanted to save this user's ratings to wayback machine, and unlike previously, red letters appear saying 'Job failed.'

### Screenshot(s)

![Untitled](https://user-images.githubusercontent.com/76570449/108453741-5f3f8e80-726b-11eb-9811-d038db1ebb93.jpg)

### Versions

- Browser/version: Firefox 86.0b9
- uBlock Origin version: 1.33.2

### Settings

I enabled `uBlock filters – Annoyances` and `Fanboy's Annoyance List` filters.

### Notes
I don't think it is caused by additional filters but by default ones blocking analytics.archive.org.
When I disable uBlock, then I can finally save that page `https://www.imdb.com/user/ur98727037/ratings` on url `https://web.archive.org/save`

**Comment by llacb47** [comment]
It is not caused by uBlock Origin or its filters. The Wayback Machine is just unreliable.

**Comment by GoblinLegislator** [comment]
I don't agree.

**Comment by uBlock-user** [comment]
Works for me..

<details>

![Capture](https://user-images.githubusercontent.com/21290713/108465592-502b0180-72a8-11eb-8fa0-adfaa8f95754.PNG)

</details>

**Comment by mapx-** [comment]
Tested (chrome): 1. getting `job failed`  2. shortly after the first attempt (after a simple refresh) it worked as expected

**Comment by uBlock-user** [comment]
Sounds like a site issue.

**Comment by GoblinLegislator** [comment]
Well, if you say so...
