### ISSUE TITLE
Peter Lowe's "snoobi.com" rule breaks sato.fi

### ISSUE THREAD

**Issue by gitarra** [uBlockOrigin/uAssets#86]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://www.sato.fi/en/sato

### Describe the issue

Scroll down to "Interested?" section at the bottom. Click "Show the apartments" on the right side "Available right now" box.

Nothing happens. Console shows error "snoobi undefined"

### Versions

- Browser/version: Firefox Nightly
- uBlock Origin version: 1.7.6

**Comment by zummuz** [comment]
Caused by `||snoobi.com^` from Peter Lowe’s Ad server list.
You can add `@@||snoobi.com^$script,domain=sato.fi` to *My filters* list tab
