### ISSUE TITLE
bestforkodi.com

### ISSUE THREAD

**Issue by mat41997** [uBlockOrigin/uAssets#860]
![2017-11-24 06_30_18-best for kodi - the best tip tricks addons and tv boxes for the world of kodi](https://user-images.githubusercontent.com/5884000/33196672-ff43f086-d0e0-11e7-859d-ae18a4f2f689.png)
`http://bestforkodi.com/?`

description
i don't can copy the text of this site

https://github.com/MajkiIT/polish-ads-filter/issues/4549

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.104
chrome 62.0.3202.94

**Comment by okiehsch** [comment]
````
||bestforkodi.com^$inline-script
bestforkodi.com##body:style(-webkit-touch-callout: default !important; -webkit-user-select: text !important;-moz-user-select: text !important;-ms-user-select: text !important;user-select: text !important;)
````
as suggested [here](https://github.com/MajkiIT/polish-ads-filter/issues/4549#issuecomment-346803380) works on my end.

This is an annoyance and I will not add a filter.

**Comment by zaphodbeebblebrox** [comment]
@okiehsch Ads, disabled right click, disabled F12. I believe the latter two are now added in uBlock-Annoyances?
