### ISSUE TITLE
Propaganda filter

### ISSUE THREAD

**Issue by leodoi3** [uBlockOrigin/uAssets#8601]
Is it possible to have a propaganda filter that blocks all these various propaganda messages? Frankly you could add them to the annoyance filter but might be better to have a seperate filter for these.

Youtube
![image](https://user-images.githubusercontent.com/46114199/108584178-7bd7d700-72fc-11eb-9fa7-8e066a3330ff.png)
Amazon
![image](https://user-images.githubusercontent.com/46114199/108584006-ff90c400-72fa-11eb-903c-66e748ad4a0d.png)
Google
![image](https://user-images.githubusercontent.com/46114199/108584234-e9840300-72fc-11eb-9fec-9108f6aec24a.png)
Google maps
![image](https://user-images.githubusercontent.com/46114199/108584045-50082180-72fb-11eb-9a4c-1d6d6294eb4d.png)
Linkedin
![image](https://user-images.githubusercontent.com/46114199/108584063-7ded6600-72fb-11eb-8731-5aea6706608a.png)
Tripadvisor
![image](https://user-images.githubusercontent.com/46114199/108584124-0835ca00-72fc-11eb-835c-265fc11f0f9b.png)
Prime video
![image](https://user-images.githubusercontent.com/46114199/108584151-4337fd80-72fc-11eb-9824-f7f89e1caf2d.png)

**Comment by okiehsch** [comment]
We don't block the promotion of political views or ideas. You are free to block whatever you like on your end.
