### ISSUE TITLE
franceinter.fr and franceculture.fr play button not working anymore on firefox and firefox mobile

### ISSUE THREAD

**Issue by johnchristopher** [uBlockOrigin/uAssets#8603]
### Describe the issue

https://www.franceinter.fr and https://www.franceculture.fr play button not working anymore on firefox and firefox mobile

https://www.franceinter.fr/emissions/interception/interception-21-fevrier-2021 : clik on "écouter", nothing happens (see console.log for unloaded javascript error).

### Versions

- Browser/version: ff/85.0.1
- uBlock Origin version: 1.26.0

### Settings

Default settings, clean profile

### Notes

Noticed it two or three days ago. Both on mobile and desktop.

**Comment by mapx-** [comment]
No issue on my end (FF desktop).

Your uBO is outdated ?! 1.26.0 => the last one is **1.33.2**

**Comment by mapx-** [comment]
it seems you are using Fanboy’s Annoyance. In this case just add

`@@||sdk.privacy-center.org^$script,domain=franceinter.fr`

**Comment by johnchristopher** [comment]
@mapx- : Thanks, I didn't notice I was out of date, I thought auto-update was applied. Updating and applying your fix did it.

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/e0c27e993a64d999b08623a28a4e2f08ff5cd2f2
