### ISSUE TITLE
curseforge.com

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#8606]
### URL(s) where the issue occurs

`https://www.curseforge.com/wow/addons/nova-world-buffs`

### Describe the issue

300x250 ad in sidebar

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.33.2]

**Comment by Mennaruuk** [comment]
I can't reproduce on Firefox, same version.
uBlock Origin ON: `https://i.imgur.com/c7lfQth.png`
uBlock Origin OFF: `https://i.imgur.com/1LafCC6.png`

**Comment by mapx-** [comment]
`||media.forgecdn.net/*campaignUrl`
or
`forgecdn.net##[onclick="window.open(campaignUrl)"]`

@ryanbr

**Comment by theinstantmatrix** [comment]
Request for timer boost

Example: `https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack/files/3512279`, then click "Download"

**Comment by Xastabus** [comment]
As of this morning, Curseforge frequently redirects to a Cloudflare CAPTCHA for humanity verification.
