### ISSUE TITLE
getwallpapers.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#861]
### URL(s) where the issue occurs

`http://getwallpapers.com/image/670193`

### Describe the issue

Click Download. Cosmetic filtering blocks download dialog.

### Notes

Disabling cosmetic filtering will allow you load the overlay and the download button.

**Comment by mapx-** [comment]
add
`getwallpapers.com#@#.ads1`

**Comment by terrorist96** [comment]
Thanks

**Comment by mapx-** [comment]
fixed in easylist
https://github.com/easylist/easylist/commit/ef44065c28667ca6e60c7ed1152ecf96480bf3d2

**Comment by okiehsch** [comment]
You can now close issues 😉 .

**Comment by mapx-** [comment]
Oh, I Still have the old `skin` :D
