### ISSUE TITLE
userreport.com script gets blocked

### ISSUE THREAD

**Issue by null096** [uBlockOrigin/uAssets#8611]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://mhc2k.csb.app/`
any other URL with the blocked js script.

### Describe the issue

Basically, the problem is that UserReport script is being blocked. Because of that, the feedback button is not shown(a light-blue button on the right side of a screen). But it's not "an Ad" of any kind, and it should work properly. The link to the script that is blocked: 
`https://sak.userreport.com/computools/launcher.js`

When uBlock is turned on, the script is being blocked but doesn't happen when uBlock is turned off. uBlock also blocks similar URLs, because "computools" part in the URL can be any string.

 

### Screenshot(s)
With uBlock **enabled**:
https://user-images.githubusercontent.com/33376471/108862604-0e2bf380-75f9-11eb-8b37-01c45734eea5.png
With uBlock **disabled**:
https://user-images.githubusercontent.com/33376471/108862934-5ba86080-75f9-11eb-9e02-2b2596f182b4.png

### Versions

- Browser/version: Chrome version 88.0.4324.96 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.33.2

### Settings

No changes.

### Notes
See "Describe the issue" above

**Comment by mapx-** [comment]
test

```
||userreport.com^$3p,badfilter
||userreport.com/*analytics$script,xhr
*$image,xhr,domain=tag.userreport.com
```

**Comment by ryanbr** [comment]
Investigating, though the filter isn't new https://github.com/easylist/easylist/commit/f3ad7eb57f6f283273420fb7620fa60ac0a41cac

**Comment by mapx-** [comment]
wow, 10 years, Ares2 ..

**Comment by ryanbr** [comment]
Allowing all userreport scripts seem to be a major privacy issue. We have no other fixes for userreport (in the last 10years), why is the feedback button is dependent on a tracking script?

**Comment by null096** [comment]
@ryanbr good question, there's an option to use google analytic inside of userreport settings. But there seems to be no option to turn it off. And it actually gest loaded inside of an iframe of userreport feedback modal window when it's opened.

The filter above works as expected, analytics is blocked and the feedback tool works fine.

I may say that userreport by itself doesn't seem to introduce tracking, it just makes use of google analytics. The filter rules block only the analytics part and will be sufficient in this case. But it's true that it may hard to keep an eye on everything that userreport does and thus blocking userreport, as it's done in https://github.com/easylist/easylist/commit/f3ad7eb57f6f283273420fb7620fa60ac0a41cac, makes more sense. What do you guys think about that?

**Comment by ryanbr** [comment]
From what I see, it depends on many changes (basically whitelisting the entire userreport domain) to allow the feedback to work. If the site was designed to just allow `https://sak.userreport.com/computools/launcher.js`  then it might easier to swallow.

Maybe adjust the feedback script (or the website), to be loaded independent of userreports.

**Comment by null096** [comment]
What do you mean in particular by adjusting the feedback script or website?
