### ISSUE TITLE
thiruttuvcd.xyz

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8613]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.thiruttuvcd.xyz/the-white-tiger-2021-telugu-full-movie-watch-online/`

### Describe the issue

Popup ads

### Versions

- Browser/version: Firefox A.
- uBlock Origin version: 1.32.2

### Settings

uBO's default settings
-

### Notes

These work
```
thiruttuvcd.xyz##+js(aopw, _pop)
||pcdodues.com^
||fdwbhggm.com^
||njmkilpqzibv.com^
```

**Comment by Infrastructural** [comment]
Could someone take a look at the the scriptlet and see if it is obsolete?
