### ISSUE TITLE
copyrightcontent.org/unblocker detect uBO and show FAB dialog

### ISSUE THREAD

**Issue by AnnAngela** [uBlockOrigin/uAssets#8615]
Please forgive my poor english _(:з」∠)_

### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

https://imginn.com/p/CLp3eooLPB-/

### Describe the issue

This page contains a anti-adblock script that src is `https://copyrightcontent.org/unblocker/ub/ub.js?ai=*******&pp=*******&unblockerPaymentToken=*******` which injected by inline script that has an id `ub-script`, and that script file will detect uBlock origin and show a dialog.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/9762652/108952928-4b4dbf80-76a5-11eb-92f1-5699034f6528.png)

### Versions

- Browser/version: Microsoft Edge Version 90.0.803.0 (Insider) dev (x64)
- uBlock Origin version: uBlock Origin v1.33.2

### Settings

Reproduced with default settings.

### Notes

The script will inject a css file `https://copyrightcontent.org/unblocker/ub/ub.css`, and that css file defines `.unblocker-container` as `all: revert;`. But I can use custom rule `imginn.com##.unblocker` to block the `div` easily.

**Comment by AnnAngela** [comment]
@okiehsch I think that script `https://copyrightcontent.org/unblocker/ub/ub.js?ai=*******&pp=*******&unblockerPaymentToken=*******` should be filtered as well.

**Comment by llacb47** [comment]
`||copyrightcontent.org^$3p`

?

**Comment by okiehsch** [comment]
Is it always used for anti adblock purposes?
Any other domains that use it?

**Comment by Yuki2718** [comment]
@okiehsch 
From AG Base:
```
! https://github.com/AdguardTeam/AdguardFilters/issues/74176
! https://github.com/AdguardTeam/AdguardFilters/issues/75599
||copyrightcontent.org/unblocker/ub/$domain=finchtechs.com|imginn.com
```
