### ISSUE TITLE
techrepublic.com

### ISSUE THREAD

**Issue by pintassilgo** [uBlockOrigin/uAssets#8616]
### URL(s) where the issue occurs

`https://www.techrepublic.com/blog/five-apps/five-note-taking-add-ons-for-firefox/`

### Describe the issue

Images don't load (except the first one with Firefox logo).

### Versions

- Browser/version: Firefox 86
- uBlock Origin version: 1.33.2

### Settings

[×] EasyPrivacy

### Notes

EasyPrivacy has this filter: `/dw-tracking-`.
The link above needs to load `https://www.techrepublic.com/a/fly/bundles/flyjs/js/managers/dw-tracking-1.0.js` in order to display images. This simple filter solves the issue:
`||techrepublic.com/*/dw-tracking-$script,redirect=noop.js`

But you should notice that Unbreak List already has something very similar, but restricted to `cbsistatic.com`, which is not the case here.
https://github.com/uBlockOrigin/uAssets/blob/d9b5069bff30ed2411d09482227149d83a56083e/filters/unbreak.txt#L2117

**Comment by PIZZA90** [comment]
`https://www.techrepublic.com/videos` videos not working

**Comment by yourduskquibbles** [comment]
@PIZZA90 Can you verify now working after purge cache and update filters?

**Comment by PIZZA90** [comment]
the videos work correctly

**Comment by mduchev** [comment]
@R-Ata I think that this is still not fixed. The images are not loading on my end. 

E.g. https://www.techrepublic.com/article/how-to-clean-up-your-gmail-inbox-with-this-mass-delete-trick/
There, all of the figures (Figure A, Figure B, etc) are not visible. I've tried to purge cache and update filters, but the images are still not visible.

Images are hosted on "https://www.techrepublic.com/a/hub/i/r/..."

**Comment by R-Ata** [comment]
Yes well... I have not tried it with uBO .. now I'm using adguard adblocker, the images don't work.

this filter in adguard base `||redventures.io^$third-party` is doing the problem i dont know 😅

cheers..

**Comment by mduchev** [comment]
@mapx- Will you reopen this?

**Comment by okiehsch** [comment]
`||adtech.redventures.io/lib/*/bidbarrel-techrepublic-$script,redirect-rule=noop.js,domain=techrepublic.com`
works for me.

**Comment by Yuki2718** [comment]
@okiehsch By https://github.com/easylist/easylist/commit/03f6c0bfae9d5324c526c57a2fc41a24b7dfdcfe we need to either use `$important` or remove the filter.

**Comment by okiehsch** [comment]
Why would we remove our filter if the redirect fixes the issue?

**Comment by Yuki2718** [comment]
> Why would we remove our filter if the redirect fixes the issue?

Well, `important,redirect-rule=` doesn't override whitelist. We have to use `important,redirect=` to assure redirect, which means we explicitly block the request so need to be sure that it won't cause problems.

**Comment by okiehsch** [comment]
> important,redirect-rule= doesn't override whitelist.

Well, that's a pretty obvious mistake on my part... thanks.

> means we explicitly block the request so need to be sure that it won't cause problems.

The redirection - which already includes the blocked request - did not cause any issues, so I don't see why that would change if we explicitly block it.
If it does we should remove it of course.

**Comment by Yuki2718** [comment]
Maybe just my overthinking ;)
