### ISSUE TITLE
Myanimelist campaign banner

### ISSUE THREAD

**Issue by runboy93** [uBlockOrigin/uAssets#8619]
`https://myanimelist.net/`

Banner campaign advert image on bottom:

`https://myanimelist.net/dea_campaign?utm_source=mal&utm_medium=minibanner&utm_campaign=dea_202102`

Using Fanboy Ultimate list, along with Adguard lists (base, trackers, social, mobile, annoyances), uBlock filters (Filters, Filters 2020, Filters 2021, Annoyances, Privacy, Resource-abuse) Spam404, urlhaus filter + phishing filter.

OS/version: Lubuntu 20.04.1
Browser/version: Firefox 86
Adblock Extension/version: uBlock Origin v1.33.3b8

**Comment by mapx-** [comment]
self-promotion banner
