### ISSUE TITLE
Session recording/replay

### ISSUE THREAD

**Issue by srsl** [uBlockOrigin/uAssets#862]
Here are some resources :
https://webtransparency.cs.princeton.edu/no_boundaries/session_replay_sites.html
(list, stats, detection methodology)

**Comment by gorhill** [comment]
I checked and all is already in EasyPrivacy and/or Peter Lowe's. One exception is that `yandex.ru` is not wholly blocked as a 3rd-party, but there are filters for specific `yandex.ru` resources and I will assume they are targeting the session replay scripts.

**Comment by srsl** [comment]
Excellent, I wasn't sure about the support.
Thanks for your reply and congrats for all your work !
