### ISSUE TITLE
userupload.in anti-adblock

### ISSUE THREAD

**Issue by cantunborn** [uBlockOrigin/uAssets#8620]
### URL(s) where the issue occurs

`https://userupload.in/etvdy7ekenza`

### Describe the issue

 

Anti-adblock.

### Versions

- Browser/version: Chrome 88.0.4324.182
- uBlock Origin version: 1.33.2

### Settings

- All lists except regional and adguard mobile ads

### Notes

Change `userupload.net` rules to `userupload.*`.

**Comment by ghajini** [comment]
provide the link to test

**Comment by stephenhawk8054** [comment]
Example link: `https://userupload.in/jbqe0th3jxkn`

But it works fine on firefox for me.

**Comment by ghajini** [comment]
i can't reproduce at that link

**Comment by ghajini** [comment]
can't reproduce, are you accessing from vpn
`https://user-images.githubusercontent.com/20338483/198818649-3281fff1-086a-4761-85c7-422071ac3a2c.png`

**Comment by okiehsch** [comment]
Add
`userupload.*#@#+js(nano-stb)`
to your filter list.
