### ISSUE TITLE
Tesco.com locks up, with frequent attempts to contact sentry.io

### ISSUE THREAD

**Issue by markuslaker** [uBlockOrigin/uAssets#8621]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

https://www.tesco.com

### Describe the issue

 

Go to <https://www.tesco.com>.  There's no need to set up an account.  From the home page, search for a product (such as eggs).  Once the results page appears, look at the uBO icon.  You'll see that the number of blocked items increases rapidly -- by almost a thousand items a second on my PC.  Wait a few seconds.  There's no need to add any items to your basket -- it makes no difference either way.  Now search for a second item (such as apples).  Firefox locks up.  The Linux `top' command shows that the browser is using large amount of CPU time.

If you open the uBO logging window before starting this procedure, you'll see repeated attempts to contact sentry.io.  However, the lockup occurs readily, even if the logging window has never been opened.

### Versions

- Browser/version: [Firefox 85.0.1 64-bit on Fedora 33]
- uBlock Origin version: [1.33.2]

### Settings

I haven't changed the default settings.  In fact, I've just installed uBO and disabled uMatrix after finding that uMatrix caused the same problem.

### Notes

I also use Pi-Hole.  Hence a DNS lookup of sentry.io returns 0.0.0.0.

If I disable uBO, Wireshark does not show continual traffic to sentry.io, even with Pi-Hole enabled.  Something about the way uBO blocks resources causes Tesco's (questionable) code to keep retrying sentry.io; in contrast, DNS-level blocking doesn't cause the same problem.

As I say, until now, I've been using uMatrix.  uMatrix caused the same problem today; it didn't cause this problem a week or two ago.  So the chances are that some script on the Tesco Web site has changed recently.

Many thanks for looking into this, and for your work on uBO generally.

**Comment by okiehsch** [comment]
Update the `EasyPrivacy` list.
