### ISSUE TITLE
linuxh2o.com anti adblock

### ISSUE THREAD

**Issue by lepz0r** [uBlockOrigin/uAssets#8623]
### Prerequisites

- 

- [x]  This is not a support issue or a question

    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

https://linuxh2o.com/best-5-cursor-icon-themes-for-linux-rgb-edition/

### Describe the issue

Adblock is detected & scroll is disabled

### Screenshot(s)

![Screenshot from 2021-02-26 09-10-44](https://user-images.githubusercontent.com/7135180/109245890-2eb2a400-77d9-11eb-842c-30b1f91155c9.png)

### Versions

- Browser/version: [Firefox 86.0 64-bit on Artix Linux]
- Browser/version (default uBO settings): [ungoogled-chromium 88.0.4324.182 on Artix Linux (jk-aur repo)]
- uBlock Origin version: [1.33.2]

### Settings

Mostly nothing beside filter list, i also tried with default settings on ungoogled-chromium

### Notes
Added this filters but scroll still not working:
```
||https://linuxh2o.com/wp-content/plugins/dh-anti-adblocker/*
||linuxh2o.com/wp-content/plugins/dh-anti-adblocker/*$script,1p
||linuxh2o.com/wp-content/plugins/dh-anti-adblocker/*$1p
```

**Comment by okiehsch** [comment]
Update the `uBO-filters` list.
