### ISSUE TITLE
badware risk sites

### ISSUE THREAD

**Issue by gerwusa1823** [uBlockOrigin/uAssets#8626]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`104.219.234.138`
`computernewb.com`

### Describe the issue
malicious domain + related IP
https://urlhaus.abuse.ch/url/1031711/
https://www.virustotal.com/gui/domain/computernewb.com/relations
https://www.virustotal.com/gui/ip-address/104.219.234.138/relations
 

### Versions

- Browser/version: Google Chrome Version 88.0.4324.190 
- uBlock Origin version:  v1.33.2

### Settings

-

**Comment by dfault-user** [comment]
Can this issue be re-opened? It appears our website was attacked earlier and this was used to report us to uBlock and URLhaus.
It'd be best if this was removed as the 'badware' was already removed from the domain.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/4c67d83ee3bf27e5a100f0b11fedd721bbdb0752
