### ISSUE TITLE
Requesting removal of computernewb.com from blacklist

### ISSUE THREAD

**Issue by computernewb** [uBlockOrigin/uAssets#8627]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`http://computernewb.com`
`https://computernewb.com`

### Describe the issue

Greetings,

I am requesting the removal of my website Computernewb from the UBlock "badware" list. The reason being is the only reason the website is blacklisted is because a malicious troll uploaded a file (a fake PNG file, which was really an EXE) to our MediaWiki website, who then reported it themselves to get our website on blacklists. I understand this probably sounds quite silly, but this is actually what they are trying to do.

I have already contacted Spamhaus, and verified our domain was clean, and I have prevented anyone from being able to upload files through MediaWiki at all, so there should be no more issues. Therefore, I am requesting removal of the domain from the blacklist.

If further explanation is needed, let me know.

 

### Screenshot(s)

N/A

### Versions

- Browser/version: All
- uBlock Origin version: All

### Settings

- N/A

### Notes

All forms of file uploads have been disabled from the website, so the incident can never happen again.

**Comment by dfault-user** [comment]
Vouching for immediate removal of this domain from the badware list.

**Comment by okiehsch** [comment]
The file Spamhaus flagged has been removed.
