### ISSUE TITLE
indavideo.hu

### ISSUE THREAD

**Issue by pcroland** [uBlockOrigin/uAssets#8628]
### URL(s) where the issue occurs
`https://indavideo.hu`

### Describe the issue
indavideo detects uBlock Origin and doesn't play videos.

### Screenshot(s)
![image](https://i.kek.sh/nioeNnmbDiL.png)
translation:
```
Video doesn't start?
We blocked the content because you also blocked the ads.
Here's how to disable your adblocker and you are ready to watch the video!
```
### Versions
- Browser/version: 88.0.4324.190
- uBlock Origin version: v1.33.2

### Settings
I just enabled some annoyances filters but it also does not work with default settings.

**Comment by mapx-** [comment]
Did you enable `HUN: hufilter` list ?

**Comment by lain566** [comment]
`HUN: hufilter` doesn't fix anti-adblock for me.

**Comment by pcroland** [comment]
> Did you enable `HUN: hufilter` list ?

Yes, it's enabled.

**Comment by pcroland** [comment]
This is still not fixed.
