### ISSUE TITLE
badware

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#8630]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`http://mediazlez.pp.ua/d/nEDt2mkU17` 
click on the yellow button it redirects to badware crap

### Describe the issue

badware. Virustotal scan: `https://www.virustotal.com/gui/file/afa45ed317b277c3a16b4f47c48c20a370089b8187d9cdcadfcea1baf9933a03/detection`

### Versions

- Browser/version: firefox developer
- uBlock Origin version: ublock origin
### Settings

default + uBlock Annoyances

### Notes
possible fix:

`||puzzceworkdistkebur.tk^$all`

**Comment by JobcenterTycoon** [comment]
Same redirect: `http://failsame.ru/file/7b289e`

possible fix:  
`||suzamense.com^$all`
`||sevenonex.space^$all`

**Comment by JobcenterTycoon** [comment]
Ok i see they change the domain really quickly ...

`||recangedesna.ml^$all`
`||newfind.cloudns.cl^$all`

is not persistent ... but regex or generic filter to hide the download button looks very risky

**Comment by okiehsch** [comment]
So you want me to completely block `walhalagame.fun`?
They use `mediazlez.pp.ua` and `walhalagames.pw` to download all of their scripts, hacks and cracks.
Blocking all three seems like overkill to me.
How about I add
`||walhalagame.fun^$doc`
that way the user can decide if he wants to continue after the warning or not.

**Comment by JobcenterTycoon** [comment]
Im tried different downloads but every redirect to the same badware links listed above (`mediazlez.pp.ua` and `walhalagames.pw` redirect to it after clicking on download). `mediazlez.pp.ua` says the file is clean but when i check the file its not clean.

Cheating software for big games like fortnite are very expensive because they use a good anticheat so why so many cheats for so many games are free on this site?

`||walhalagame.fun^$doc` is a good filter when blocking all three is overkill

**Comment by okiehsch** [comment]
Malware free publicly downloadable cheats, hacks and cracks are rather rare imo. 😉

**Comment by JobcenterTycoon** [comment]
Already changed ... im underrated the amount of spam and the huge amount of domains

`||caumammilodorf.cf^$all`
`||linked.cloudns.asia^$all`

**Comment by okiehsch** [comment]
Shouldn't the blocking of `walhalagame.fun` be good enough?
Is there a way to get to `caumammilodorf.cf` without visiting `walhalagame.fun` first?

**Comment by JobcenterTycoon** [comment]
Yes looks like the site `mediazlez.pp.ua` just redirect to these crap random domains. second example: `http://mediazlez.pp.ua/d/azgxfgvA9b`

Im searched but i can’t find any legitimate link (all links just redirect to the same). On the site no contact no data protection nothing is clickable except the download button. The site says "Without viruses" but its a lie ... hmmm better to block this?

But the site `mediazlez.pp.ua` is often linked so its effective to block this.

**Comment by JobcenterTycoon** [comment]
I have more very suspect domains (stable - exist over multiply weeks).

`https://zhirhacks.pro/fortnite` or `https://zhirhacks.pro/csgo` or `https://zhirhacks.pro/overwatch` redirect to mega.nz sites with malware downloads. I already reportet many domains to mega.nz but they get nearly every day a new mega.nz domain. They protect the zip with a password to avoid antivirus detection and putting the password (simple passwords like 1234 or 1111) under the download link

`https://nemosiau.icu/wCKsn5` same as above ... this site have no main site (just redirect to google) so its looks like they just use the domain to redirect to malware crap

`https://fortniteswapper.fun` link to malware downloads. First they used mega.nz but now they use another file hoster without fast malware file deletion

`http://injectx.online/` redirector

`https://app-inject.com/` just redirect to ads and scam (the complete spectrum ... fake captchas, fake giveaway, hundrets of redirects, ...)

**Comment by okiehsch** [comment]
> `http://injectx.online` redirector

If it is ad related that can be added to `EasyList`.
@ryanbr

**Comment by JobcenterTycoon** [comment]
I have one more Domain `http://www.supra.dns-cloud.net`

**Comment by JobcenterTycoon** [comment]
I have one more domain: `tophacks.pro` example: `https://tophacks.pro/fortnite`
