### ISSUE TITLE
vexfile.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#8631]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://vexfile.com/download/e9uz7cJXWt/7848f`

### Describe the issue

green fake buttons

### Screenshot(s)

<img width="489" alt="Unbenannt1" src="https://user-images.githubusercontent.com/48647394/109434116-f4811680-7a13-11eb-936f-a7d10784bc5a.PNG">

### Versions

- Browser/version: firefox developer
- uBlock Origin version: v1.33.2

### Settings

default + uBlock Annoyances

**Comment by Mennaruuk** [comment]
Can you add
`||vexfile.com/img/cofksar.png`
Above worked for me.

**Comment by JobcenterTycoon** [comment]
there is a typo on the last entry (`^$3` instead of `^$3p)`
