### ISSUE TITLE
uBlock is blocking ~40K elements on Tesco webpage which makes Firefox unusable (uses 400% CPU)

### ISSUE THREAD

**Issue by stransky** [uBlockOrigin/uAssets#8633]
### Prerequisites

- [ ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin
- [ ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

[Description of the bug or feature]
Firefox 86.0, uBlock installed from Mozilla AMO site, default uBlock setting (no custom filters, any preference was not changed). When browse to Tesco site, Firefox is unusable.

### A specific URL where the issue occurs
https://nakup.itesco.cz/groceries/cs-CZ/shop/ovoce-a-zelenina/ovoce/jablka-a-hrusky

[A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"]

### Steps to Reproduce

1. Open Firefox 86 with uBlock installed from Firefox addons site.
2. Go to https://nakup.itesco.cz/groceries/cs-CZ/shop/ovoce-a-zelenina/ovoce/jablka-a-hrusky
4. browse the items
5. Firefox is very slow, uses 400% CPU.

* uBlock Origin version:
uBlock Origin v1.33.2
* Browser Name and version:
Firefox 86
* Operating System and version:
Fedora 33 Linux

Firefox profiler data:
https://share.firefox.dev/37X1MvG

**Comment by gorhill** [comment]
Fixed with <https://github.com/uBlockOrigin/uAssets/commit/b52b9fbd7e8719c6dfa2dcfe9d5869293c95d4b5>.
