### ISSUE TITLE
Block sp-prod.net - wrapperMessagingWithoutDetection.js

### ISSUE THREAD

**Issue by huornlmj** [uBlockOrigin/uAssets#8636]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

`https://gdpr-tcfv2.sp-prod.net/wrapperMessagingWithoutDetection.js` should be added to the block list.

### A specific URL where the issue occurs

The issue does not occur here, this link is an example I know of that uses this script and which has started to be blocked nativly by Vivaldi's built-in tracker blocking.  `https://planetradio.co.uk/jazz-fm/player/152908871/`

### Steps to Reproduce

None

### Expected behavior:

Block the tracker

### Actual behavior:

The tracker is allowed by uBlock.

### Your environment

* uBlock Origin version: 1.33.2
* Browser Name and version: Vivaldi 3.6.2165.40 (Stable channel) (64-bit)
* Operating System and version: Windows 10

**Comment by uBlock-user** [comment]
>  GDPR messages will not be addressed in uAssets

**Comment by okiehsch** [comment]
That request was part of `EasyPrivacy` and they removed it because it lead to site breakage on quite a few sites.

**Comment by uBlock-user** [comment]
Blocking the script that the OP's requesting results in the GDPR modal never being shown.

**Comment by huornlmj** [comment]
> That request was part of `EasyPrivacy` and they removed it because it lead to site breakage on quite a few sites.

But isn't the breakage the desired result and force the site owners to fix it rather than allow it to pass by?  After all wrapperMessagingWithoutDetection.js is a blatant CNAME based side skirting of protections to go by under the radar?

Reference: https://news.ycombinator.com/item?id=22535303

Only those using Vivaldi with native tracking will be protected even if they use uBlock Origin.

**Comment by uBlock-user** [comment]
> But isn't the breakage the desired result and force the site owners to fix it rather than allow it to pass by?

We don't intentionally break sites, that's never been the case, also site owners wouldn't care at all, they will simply put the blame on uBO and users will simply disable uBO to bypass which is fare worse than allowing a script to load from a third-party domain.

**Comment by okiehsch** [comment]
> But isn't the breakage the desired result

If you break the site many users will simply disable the blocker. We have millions of users most of them are not tech savvy.
Site breakage caused by the default setup is a no no. 

> force the site owners to fix it

I doubt they care and in the EU they are legally obliged to show the GDPR message.
That they could use a mechanism to do that without breaking the site if blocked goes without saying.

**Comment by uBlock-user** [comment]
> Only those using Vivaldi with native tracking will be protected even if they use uBlock Origin.

You can use Fanboy's Annoyances
