### ISSUE TITLE
This is not a issue.

### ISSUE THREAD

**Issue by kam92** [uBlockOrigin/uAssets#8639]
Im sorry I dont know how to do a pull request to github.

I want to add the filter for https://ijuinews.com.br available to all, its just add ||www.ijuinews.com.br/upload/banners/* and it blocks all ads. If you can add this I would be grateful.

**Comment by mapx-** [comment]
report here: https://github.com/AdguardTeam/AdguardFilters/issues

to be added to this list: `spa, por: AdGuard Spanish/Portuguese`
