### ISSUE TITLE
Jwplayer  being blocked by easylist how to exclude?

### ISSUE THREAD

**Issue by molitar** [uBlockOrigin/uAssets#864]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
https://www.tomsguide.com/us/galaxy-x-foldable-phone,news-24862.html

### Describe the issue
Unable to play jwplayer video when uBlock enabled. How can I exclude jwplayer media?

### Versions
Browser/version: Cyberfox 52.4.1 (same core as Firefox with old UI style)
uBlock Origin version: uBlock Origin v1.14.18

### Settings

sankakucomplex.com##cloudflare-app[app-id="no-adblock"]
sankakucomplex.com##script:inject(abort-on-property-read.js, BetterJsPop)

@@||images-amazon.com/images//video$object,domain=amazon.com
@@||images-amazon.com/.mp4$object,domain=amazon.com
||images-amazon.com$object,domain=amazon.com
||images-amazon.com$object,domain=amazon.com
||images-amazon.com$object,domain=amazon.ca
||images-amazon.com$object,domain=amazon.co.uk
||images-amazon.com$object,domain=amazon.co.jp

### Notes

Disabled Easylist and the video would than play. The video will not play if the ad does not play.

**Comment by okiehsch** [comment]
I already fixed that. https://github.com/uBlockOrigin/uAssets/commit/81039ee9336d2c671f639f13815b4902bf77394e
Update your `uBlock filters – Unbreak` list.

**Comment by molitar** [comment]
Ok great thanks!  Will do.
