### ISSUE TITLE
Site detects uBlock Origins and locks the game

### ISSUE THREAD

**Issue by Endor8** [uBlockOrigin/uAssets#8640]
### Prerequisites

- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x ] I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [ x] using a new, unmodified browser profile
- [ x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs:

`https://www.sudoku-aktuell.de/sudoku-online.html`

### Describe the issue

The site detects uBlock Origin and locks the game and I need to disable uBlock Origin on this site. 
       Only than I am able to play sudoku. On top is a line who says: Adblocker must be deactivated!
       The site will check if ads are loaded, if not the game will be locked.

 

### Screenshot(s)

![ublock1](https://user-images.githubusercontent.com/1267601/109798446-0a145d00-7c1b-11eb-8032-a0f17743f6e5.png)

### Versions

- Browser/version: [Firefox 86.0]
- uBlock Origin version: [1.33.2]

### Settings

![ublock2](https://user-images.githubusercontent.com/1267601/109802969-c1f83900-7c20-11eb-853a-9ec06609952f.png)

**Comment by okiehsch** [comment]
Update the `uBO-filters` list, should work after that.

**Comment by Endor8** [comment]
Thank you very much. It works again.
You are great.
Cheers
Endor
