### ISSUE TITLE
pornoham.me [NSFW]

### ISSUE THREAD

**Issue by P0Rtvine** [uBlockOrigin/uAssets#8641]
### URL(s) where the issue occurs

`https://pornoham.me/videos/240138/lesbi-podrugi-laskayut-kiski-i-mnogo-konchayut/`

### Describe the issue

Adblock detected in player

### Screenshot(s)
<details>
<summary>Screen</summary>

![2021-03-03_085736](https://user-images.githubusercontent.com/57287308/109800442-da1e8700-7c25-11eb-9098-0a1ef9ba549a.png)
</details>

### Versions

- Browser/version: Google Chrome
- uBlock Origin version:  1.33.2

### Settings
<details>
<summary>Screen</summary>

![2021-01-22_100714](https://user-images.githubusercontent.com/57287308/105464158-c3395c00-5c99-11eb-965b-81215d8f7bec.png)
</details>

**Comment by okiehsch** [comment]
@dimisa-RUAdList

````
@@||pornham.me^$ghide
*$frame,redirect-rule=noopframe,domain=pornham.me,1p
````
works for me.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/c5cafdd104a7340b76800d559f72356a6685db4e
