### ISSUE TITLE
Some sites very slow with uBlock Origin enabled

### ISSUE THREAD

**Issue by billysielu** [uBlockOrigin/uAssets#8645]
Chrome 88
uBlock Origin 1.33.2

Seen this on several websites, but here's an example:
Example URL: `https://www.net-aware.org.uk/`

Loading Times
uBlock Origin enabled: about 6 seconds
uBlock Origin disabled: 0.2 seconds

This is a problem because it forces people to choose between performance and privacy. Historically, blocking ads led to better performance so you got the best of both worlds, but this is increasingly no longer the case.

Please ensure that the extension does not cause significant performance impact. Either by removing the offending rule, or dealing with the performance consequences of rules.

**Comment by mapx-** [comment]
@billysielu  test this filter:

`@@||googletagmanager.com/gtm.js$xhr,domain=net-aware.org.uk`

**Comment by mapx-** [comment]
> Seen this on several websites

provide all the info (specific pages / links)

**Comment by billysielu** [comment]
Another example: https://www.thomas.co/

**Comment by mapx-** [comment]
`@@||thomas.co/sites/default/files/google_tag/primary/google_tag.script.js$script,1p`
