### ISSUE TITLE
NSFW poringa.net ublock blocks an (util) banner (it is not an ad)

### ISSUE THREAD

**Issue by jazei-AR** [uBlockOrigin/uAssets#8646]
the banner filtered is this: 
![Poringa!](https://user-images.githubusercontent.com/72522918/109956502-7b5b1b00-7cc2-11eb-95c2-e06aa2315363.jpg)
https://images2.imgbox.com/4e/47/McqVq9bF_o.jpg

(porn) website: `https://www.poringa.net/`
this banner goes to a webpage about advises, helps, things to do a well made post in that site, it is not an ad.
the banner is the first line of the list at top of the webpage

**Comment by jazei-AR** [comment]
![Poringa!](https://user-images.githubusercontent.com/72522918/109955599-6df16100-7cc1-11eb-8eff-08ff83563dbe.jpg)

**Comment by mapx-** [comment]
it's blocked by spa: `EasyList Spanish`

`poringa.net##.banner`

report here: 
`https://forums.lanik.us/viewforum.php?f=103`

add in "my filters" 
`poringa.net#@#.banner`
