### ISSUE TITLE
connery.dk

### ISSUE THREAD

**Issue by DandelionSprout** [uBlockOrigin/uAssets#8648]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin (1.33.3b11)

### URL(s) where the issue occurs

`https://connery.dk/de-danske-kokke-jakob-mielcke.135222.html`

### Describe the issue

A fairly aggressive and uncloseable anti-adblock.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/22780683/109966908-12d76280-7cf1-11eb-8bb0-6108fc177e9f.png)

### Versions

- Browser/version: Chrome 89.0.4389.72 x64
- uBlock Origin version: 1.33.3b11 + IDCAC 3.2.8

### Settings

![image](https://user-images.githubusercontent.com/22780683/109967061-3ef2e380-7cf1-11eb-839c-74661884909b.png)

![image](https://user-images.githubusercontent.com/22780683/109967110-50d48680-7cf1-11eb-8147-271c1f4430c5.png)

### Notes

Using `$ghide` doesn't seem to fix the problem.

**Comment by uBlock-user** [comment]
`connery.dk##+js(set, adblockerAlert, noopFunc)`  

any breakage with that ?

**Comment by DandelionSprout** [comment]
No breakage that I can see, so I'll add it to Nordic Filters right away (presuming that is what I'm implied to do).

**Comment by uBlock-user** [comment]
The bait is `dotbanner.dk/advert.js` fyi.. if that filter ever stop working, whitelist that url.
