### ISSUE TITLE
Up-to-date Disconnect.me tracking-protection list available

### ISSUE THREAD

**Issue by overlayfs** [uBlockOrigin/uAssets#865]
An up-to-date version of Disconnect.me's tracking-protection list can be found at the following urls:

https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json
https://disconnect.me/trackerprotection/blocked
https://disconnect.me/trackerprotection

The list contains about 5k entries, including about 1.5k 'new' entries (relative to existing filters in UBO and https://s3.amazonaws.com/lists.disconnect.me/* ).

**Comment by gorhill** [comment]
Declined. This list would break major sites, for example I see `facebook.com` in there. Furthermore, that list is not in a format compatible with uBO. One is a web page, and the other is JSON.
