### ISSUE TITLE
mp3saleem.blogspot.com / kindaunique.me

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8655]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://mp3saleem.blogspot.com/2020/03/mere-baad-kisko-sataoge-song.html?m=1`

`https://www.kindaunique.me/download/gangster-%E0%A6%97-%E0%A6%AF-%E0%A6%B8-%E0%A6%9F-%E0%A6%B0-movie-dialogue-part-1-heart-touching-dialogue-yash-mimi-eXQtLUIzSGg5RUV4b3hN`

### Describe the issue

Popup ads 

Fake links at `https://www.kindaunique.me/download/gangster-%E0%A6%97-%E0%A6%AF-%E0%A6%B8-%E0%A6%9F-%E0%A6%B0-movie-dialogue-part-1-heart-touching-dialogue-yash-mimi-eXQtLUIzSGg5RUV4b3hN`

### Versions

- Browser/version: Firefox A nightly
- uBlock Origin version: 1.33.2

### Settings

 uBO's default settings
-

### Notes
```
mp3saleem.blogspot.com##+js(nowoif)
||www.kindaunique.me/links.php$popup,3p
||dagolor.pw^
||matswhyask.cam^
||petfoppew.com^
||idswinpole.casa^
www.kindaunique.me##[href="http://kindaunique.me/link.php"]
```

**Comment by ghajini** [comment]
Download providers from these sites

1.
Popunder at this page replaces whole page

`https://geektopia.info/download?v=IodHCWtvj6o`

2. Fake links at 

`https://studioonehyderabad.co/dl/?g=IodHCWtvj6o`

**Comment by ghajini** [comment]
@mapx- pls see above comment

**Comment by mapx-** [comment]
1. nothing to do for now => @uBlock-user could explain better why not 
2. test
```
studioonehyderabad.co##.download:has-text(Fast)
||studioonehyderabad.co/convert.php$subdocument
||studioonehyderabad.co/convert3.php$subdocument
```

**Comment by ghajini** [comment]
Iam just curious about 1St part, I know its stopped by ublock strict blocking page filter
`||daglor.pw^`

Which script provokes redirect after waiting 10-15s btw?

**Comment by mapx-** [comment]
open the network tab, go to the second request (page response) and you'll see on the right 

**refresh: 16; url=https://www.kindaunique.me/link.php**
which means after 16 seconds will redirect to that link

It's an old (non)standard heritage from the first browsers (netscape), similar with meta refresh

![image](https://user-images.githubusercontent.com/10303732/110123305-09b5c680-7dc1-11eb-930c-08df956b83d5.png)

**Comment by uBlock-user** [comment]
```
HTTP/2 200 OK
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
link: <https://geektopia.info/wp-json/>; rel="https://api.w.org/"
link: <https://geektopia.info/wp-json/wp/v2/pages/26>; rel="alternate"; type="application/json"
link: <https://geektopia.info/?p=26>; rel=shortlink
refresh: 16; url=https://kindaunique.me/link.php
cf-cache-status: DYNAMIC
cf-request-id: 08a337d45a0000de1558ab0000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=n5q8lxiploduwgh9uwJcNQzSgEW5%2BRQY6ZlmfbNVGp5m7xUR2Yj1VHKRXEEy7dE5q%2BE9QgvuG2C8Nt6SOlPRA9dfOT%2FMnGg37etT7HMawQ%3D%3D"}]}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
content-encoding: gzip
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
X-Firefox-Spdy: h2
```

`refresh` is present as a response header sent via the site, unless we can do something about it, there's no way to stop this redirection. Site might be redirectionware.

gorhill's response --

Given that we usually can prevent such refresh with filters like:

    megasubtitles.com##^meta[http-equiv="refresh"]

I am thinking of extending HTML filtering capabilities to also filter out header entries. Maybe a special operator:

    geektopia.info##^httpheader(refresh)

**Comment by ghajini** [comment]
As per https://github.com/gorhill/uBlock/commit/f876b68171ff307f27601225607a6801f400437d
this work `geektopia.info##^responseheader(refresh)` in dev build
