### ISSUE TITLE
NSFW | porndish.com adblock detection

### ISSUE THREAD

**Issue by Alex4567890** [uBlockOrigin/uAssets#8657]
In at least one of its video players adblock is detected.

**Comment by Alex4567890** [comment]
I think it didn't happen a couple of minutes ago (only once) in one of the video players.

**Comment by Alex4567890** [comment]
or twice idk

**Comment by mapx-** [comment]
Provide video / page link.

**Comment by Alex4567890** [comment]
Is it possible that it happened due to Google Chrome's ad blocker and/or third-party cookie blocker?

**Comment by Alex4567890** [comment]
I'll see if I can reproduce

**Comment by mapx-** [comment]
Use only uBO while testing

**Comment by Alex4567890** [comment]
> Use only uBO while testing

I did but Google Chrome still blocked ads due to them being 'misleading' and blocked third-party cookies because of the incognito mode.

**Comment by Alex4567890** [comment]
The message appeared again.

**Comment by Alex4567890** [comment]
Yeah so it appears that it was due to Google Chrome blocking one or more ads.

**Comment by mapx-** [comment]
> Provide video / page link.

**Comment by Alex4567890** [comment]
![Screenshot_83](https://user-images.githubusercontent.com/78655307/110022651-daf20e80-7d34-11eb-8b1c-01dd5961a0f7.png)

**Comment by Alex4567890** [comment]
It seems that the issue doesn't occur anymore.

**Comment by Alex4567890** [comment]
It occurred again. This time on: https://www.porndish.com/fit18-tristan-summers-initial-casting/
![Screenshot_86](https://user-images.githubusercontent.com/78655307/110023357-c6fadc80-7d35-11eb-8151-b7675db0762f.png)
![Screenshot_84](https://user-images.githubusercontent.com/78655307/110023359-c7937300-7d35-11eb-9aa6-599a8381ca99.png)
![Screenshot_85](https://user-images.githubusercontent.com/78655307/110023361-c7937300-7d35-11eb-948f-092ab1d1fc93.png)
