### ISSUE TITLE
qub.ca unbreak

### ISSUE THREAD

**Issue by maforget** [uBlockOrigin/uAssets#8658]
### URL(s) where the issue occurs

https://www.qub.ca/tvaplus/tva/les-beaux-malaises-2-0/saison-1/episode-6-50-ans-1038776776

### Describe the issue

Adblock detected

### Screenshot(s)

![Screenshot_2021-03-04 Épisode 06 - 50 ans - Les beaux malaises 2 0 - TVA en rattrapage TVA+](https://user-images.githubusercontent.com/11904426/110059760-db89a580-7d32-11eb-80c8-8c8cf6d2d53f.png)

### Versions

- Browser/version: Chrome/88.0.4324.190 && Firefox/86.0
- uBlock Origin version: 1.33.2

### Settings

Filter Easylist

### Notes

I believe I found the culprit and this code seems to work
`qub.ca#@#.adsbox`

Also in Firefox when unblocking with the above, there is an element that blocks the page and won't permit clicking on the page I had to add the following to prevent this. I don't see this behavior in Chrome. The site does say to use Chrome.

`qub.ca##.jss205.jss201.jss2`

**Comment by okiehsch** [comment]
`qub.ca##.jss2`
works for me without any noticable breakage using Firefox.

**Comment by nqlp** [comment]
uBO is being detected so I can't play the video: 

<details>

<img width="930" height="525" alt="Image" src="https://github.com/user-attachments/assets/7d1d5076-8d73-4dc5-9e76-7581de95d732" />

</details>

<details>

```yml
uBlock Origin: 1.66.4
Chromium: 141
filterset (summary):
 network: 180697
 cosmetic: 167398
 scriptlet: 43061
 html: 0
listset (total-discarded, last-updated):
 added:
  https://filters.adtidy.org/extension/ublock/filters/14.txt: 88128-4230, now
  FRA-0: 19395-34, now
  fanboy-cookiemonster: 46417-145, now
  fanboy-thirdparty_social: 69-0, now
  ublock-annoyances: 4677-157, now
  adguard-cookies: 35415-35415, now
  ublock-cookies-adguard: 5094-80, now
  ublock-cookies-easylist: 5094-5094, now
  adguard-popup-overlays: 28361-28361, now
  adguard-mobile-app-banners: 6367-6367, now
  adguard-other-annoyances: 15023-15023, now
  easylist-annoyances: 5199-444, now
  [1 lists not shown]: [too many]
 default:
  user-filters: 22-0, never
  easylist: 79707-363, now
  easyprivacy: 54673-699, now
  plowe-0: 3439-23, now
  ublock-badware: 10927-74, now
  ublock-filters: 41139-534, now
  ublock-privacy: 3522-20, now
  ublock-quick-fixes: 362-1, now
  ublock-unbreak: 2696-43, now
  urlhaus-1: 31275-5, now
filterset (user): [array of 22 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings:
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 254 ms (selfie)
 maxAssetCacheWait: 60 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 16
 network:
  brightcove.com: 6
  chartbeat.com: 1
  cxense.com: 1
  doubleclick.net: 1
  facebook.com: 1
  googletagmanager.com: 1
  imasdk.googleapis.com: 2
  optable.co: 1
  rubiconproject.com: 1
  scorecardresearch.com: 1
 extended:
  ##.vjs-ima3-ad-container
  ##+js(set-constant, ima, {})
```

</details>

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by nqlp** [comment]
So I've created a new profile on Brave and uBO on its default settings and it is still happening: 

<img width="1918" height="954" alt="Image" src="https://github.com/user-attachments/assets/e9392c51-9c63-4dbd-a601-e3a1211823f4" />

**Comment by stephenhawk8054** [comment]
Please give exact link where you see the issue.

**Comment by stephenhawk8054** [comment]
Forgot to note that you need to enable `AdGuard Français` list as well.

**Comment by nqlp** [comment]
```https://www.qub.ca/article/coups-de-feu-dans-un-bar-du-plateau-mont-royal-deux-hommes-succombent-a-leurs-blessures-1413606792?silent_auth=true```

Adguard French is enabled:
<img width="473" height="72" alt="Image" src="https://github.com/user-attachments/assets/006265e9-309d-4458-8f4f-497cd043c82a" />

**Comment by stephenhawk8054** [comment]
Thanks. I can reproduce now.
