### ISSUE TITLE
fshost.me anti adb

### ISSUE THREAD

**Issue by Alex4567890** [uBlockOrigin/uAssets#8665]
https://github.com/AdguardTeam/AdguardFilters/issues/76337

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/110122703-3e754e00-7dc0-11eb-92fb-f3b34176cb6b.png)

uBO filters list includes already anti adb filters. If you want to help go ahead, create an account, check if still an issue.

**Comment by Alex4567890** [comment]
> ![image](https://user-images.githubusercontent.com/10303732/110122703-3e754e00-7dc0-11eb-92fb-f3b34176cb6b.png)
> 
> uBO filters list already includes anti adb filters for this site. If you want to help go ahead, create an account, check if still an issue.

I created an account and got the thing.  That's why I posted it here.

**Comment by uBlock-user** [comment]
Does `fshost.me##+js(acis, onload, ajax)` work for you ?

**Comment by Alex4567890** [comment]
> Does `fshost.me##+js(acis, onload, ajax)` work for you ?

yes

**Comment by Alex4567890** [comment]
I haven't updated 'uBlock filters' after https://github.com/uBlockOrigin/uAssets/commit/8d441f37558c041945217f62d9da09d97c949967

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/801766f115d71e8744bbad4ed47670d3be9d1467
