### ISSUE TITLE
Problem on a URL through google

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#8666]
### Describe the issue

Searching for: `Maraudon Vanilla` in **Google** i found a site "blocked" for uBO when i click in the title, but if i copy the URL with (right click) and paste in the browser, uBO does not warn of anything.

![Captura](https://user-images.githubusercontent.com/33556647/110138537-5eae0880-7dd2-11eb-896b-bea4c413e5e4.PNG)

this is the URL:
`https://www.eturbonews.com/wp-content/?lose=legends-of-maraudon-vanilla_Cut-Fat.html`
accessible, but not via google

### Screenshot

![Captura1](https://user-images.githubusercontent.com/33556647/110138918-c82e1700-7dd2-11eb-8210-82d18679913f.PNG)

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.33.2]

## Notes

is it normal that I can access with the link but not through google? is a fake positive?🤔

**Comment by uBlock-user** [comment]
Site's redirecting to the ad-server if the referrer is found to be `google.com`, so either visit via a direct link or spoof the referrer or use a different search engine until a solution is decided upon.

**Comment by mapx-** [comment]
`startpage.com` is ok for searching that site

**Comment by strict-block** [comment]
Malware injected due plugin or 0-day security vulnerability in Wordpress 5.3.2?

**Comment by strict-block** [comment]
On firefox can use these:

https://addons.mozilla.org/pl/firefox/addon/smart-referer/

**Comment by uBlock-user** [comment]
Working fix possible with currently dev-build.

**Comment by strict-block** [comment]
Possible use this to repair instagram.com with used VPN? Or need more functional remove "location".

**Comment by uBlock-user** [comment]
@strict-block we can stop the redirection, but instagram is not serving any content, so you will see empty page.

**Comment by peace2000** [comment]
![kuva](https://user-images.githubusercontent.com/17256841/112171652-b1722780-8bfc-11eb-90a2-8af76b5959d4.png)

There seems to be a syntax error. @uBlock-user

**Comment by uBlock-user** [comment]
@peace2000 https://github.com/uBlockOrigin/uAssets/issues/8666#issuecomment-799407980

**Comment by PIZZA90** [comment]
looking for how to remove ads from twitch, until yesterday an extension called "Twich Adblock" worked.

i found other similar issue about this post, but this time the destination website "no exist" "error 404".

I write in Google `twitch adblock best solution reddit` and in the second page of google search

![Captura222](https://user-images.githubusercontent.com/33556647/113434161-bc893c80-93e0-11eb-8b8a-522263920bf0.PNG)

clicking in the URL:

![Captura123123](https://user-images.githubusercontent.com/33556647/113434968-33730500-93e2-11eb-8810-d1976457d0c4.png)


the website looks: `http://laselvadelleneviere.it` but not working.
maybe is FAKE websites idk, but I just wanted to let you know.

Cheers.

**Comment by strict-block** [comment]
bait pages with malware report to https://gitlab.com/curben/urlhaus-filter/-/issues

**Comment by PIZZA90** [comment]
I can find tons of malware domains in the "last" pages of google with any browser, in almost any search, usually `.it` domains

Related:
`https://localsearchforum.com/threads/spam-scam-it-domains-and-sub-domains-flooding-google-results-pages.55571/`
