### ISSUE TITLE
mail.com can't click anything

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#8669]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.mail.com/` then it redirect to` https://www.mail.com/int/` => `https://www.mail.com/consentpage`

### Describe the issue

Endless loading

### Screenshot(s)

![2021-03-06_071753](https://user-images.githubusercontent.com/9832875/110188855-c2c2e200-7e4f-11eb-9c38-311897b89e35.png)

### Versions

- Browser/version: [FF 86]
- uBlock Origin version: [1.33.2]

### Settings

- default, Fanboy’s Annoyance , uBlock filters – Annoyances

### Notes

When i disabled UBO, it works normally

**Comment by llacb47** [comment]
Fanboy's annoyance is blocking the GDPR modal.  Not a uAssets issue.

**Comment by okiehsch** [comment]
@ryanbr 
````
mail.com#@##onetrust-banner-sdk
mail.com#@##onetrust-consent-sdk
````
