### ISSUE TITLE
Filters stuck on updating

### ISSUE THREAD

**Issue by Frejoh466** [uBlockOrigin/uAssets#867]
### URL(s) where the issue occurs

All

### Describe the issue

Filters wont update, the spinning wheel is there for hours. 

### Screenshot(s)

https://i.imgur.com/G2wC0ZH.jpg

### Versions

- Browser/version: Firefox 58.0b6 (64-bit)
- uBlock Origin version: 1.14.18

### Settings

Default, but tried with different filters enabled.

### Notes

Chrome Version 62.0.3202.75 (Official Build) (64-bit) works fine, and able to update in a minute or so. I had Firefox on for 14 hours and no filter was downloaded. Tried with default settings and a fresh install with uBlock and the only addon enabled.

**Comment by gorhill** [comment]
Inesvtigate fully on your side please, something specific on your side is causing this.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
