### ISSUE TITLE
Annoyance: nytimes.com "expand full article"

### ISSUE THREAD

**Issue by dbenjaminmiller** [uBlockOrigin/uAssets#8670]
### URL(s) where the issue occurs

Some, but not all nytimes.com articles, e.g., 
`https://www.nytimes.com/2021/03/04/opinion/biden-american-rescue-plan.html` 
— often only on mobile; load with a mobile view on desktop [ed. this is not based on UA, but on browser width]

### Describe the issue

JavaScript is used while the article loads to truncate it and add a "Show Full Article" button. This is an annoyance, and this functionality should be blocked.

### Versions

- Browser/version: FF86
- uBlock Origin version: v1.33.2

**Comment by ghajini** [comment]
So you want to disable ''show full article" and load article by default full?

**Comment by dbenjaminmiller** [comment]
Yep, exactly. There is some JS in there which truncates the article. You can see this as the page loads. The idea, I suppose, would be to block this.

**Comment by mapx-** [comment]
I don't know if possible without breaking a bunch of other functionalities.

For example add:
`nytimes.com##^script:has-text(__preloadedData)`

**Comment by uBlock-user** [comment]
`nytimes.com##+js(aopr, __preloadedData.config.initialDeviceType)`

try that too

**Comment by mapx-** [comment]
same breakage (no comments, editor's picks, more popular etc etc)

**Comment by uBlock-user** [comment]
How about `||samizdat-graphql.nytimes.com/graphql/$xhr,1p`  ?

**Comment by mapx-** [comment]
I guess you can see the same breakages

**Comment by uBlock-user** [comment]
I don't see any breakages with `||samizdat-graphql.nytimes.com/graphql/$xhr,1p`

**Comment by mapx-** [comment]
with your filter
![image](https://user-images.githubusercontent.com/10303732/110202554-b77cb000-7e69-11eb-81af-2e3c6aecdad3.png)

without
![image](https://user-images.githubusercontent.com/10303732/110202574-e72bb800-7e69-11eb-9ff7-12be88c46cb3.png)

**Comment by uBlock-user** [comment]
No, that's desktop, you should check on mobile with responsive design mode. If we add this filter it will be mobile specific only.

**Comment by mapx-** [comment]
same breakage, no comments, no other sections at bottom

**Comment by uBlock-user** [comment]
Well then, there's no need to fix it, we already posted the filter, so user can add it if he wants to.
