### ISSUE TITLE
www.discovermagazine.com

### ISSUE THREAD

**Issue by cantunborn** [uBlockOrigin/uAssets#8674]
### URL(s) where the issue occurs

```
https://www.discovermagazine.com/
https://www.discovermagazine.com/technology
https://www.discovermagazine.com/planet-earth/the-amazon-rainforest-could-die-in-your-lifetime-heres-why
```

### Describe the issue

Sponsored posts on home page and topic page.  Ad placeholders.

### Versions

- Browser/version: Chrome 89.0.4389.82
- uBlock Origin version: 1.33.2

### Settings

- All uBO lists enabled except regional and adguard mobile ads.

### Notes

Some filters:
```
www.discovermagazine.com##span:has-text(/Sponsored/):upward(1)
www.discovermagazine.com##.adunitContainer:upward(1)
```

**Comment by Yuki2718** [comment]
We don't block sponsored posts. Addressed placeholder and "X article left" annoyance.

**Comment by Yuki2718** [comment]
@mapx- @okiehsch Is the banner I addressed may possibly be counted as paywall?

**Comment by okiehsch** [comment]
It's not a hard paywall, so the filter is OK.

**Comment by uBlock-user** [comment]
EL usually blocks sponsored posts, should ping them.

**Comment by Yuki2718** [comment]
@cantunborn Sorry I was wrong. We discussed internally and since this sponsored articles lead to third-party products which the website advertises for affiliate commission, we blocked them too.
