### ISSUE TITLE
skandynawiainfo.pl

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#8677]
`https://skandynawiainfo.pl/szwecja-rezygnuje-z-paliw-kopalnych-sily-zbrojne-protestuja/`

- blocked right click actions,
- blocked keyboard functions: `F12` / `Ctrl` + `A` or `R`

**Comment by PIZZA90** [comment]
`Crl + R` works for me (reload page in chrome)

`Ctrl + U ` is blocked too (font code)

**Comment by krystian3w** [comment]
So maybe glitched in my profile, you can close as invalid.

**Comment by PIZZA90** [comment]
:D Nice irony, It was other information, and participation, from another point of view.

I'm going to switch to adguard adblocker, and stop reporting here all the sh*t that I find. 

bye.

**Comment by mapx-** [comment]
@PIZZA90 tbh I don't understand your logic. 
krystian3w is not part of uBO team.
