### ISSUE TITLE
anti adblock on caranddriver.com

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#868]
### URL(s) where the issue occurs

`https://blog.caranddriver.com/musk-alludes-to-model-3s-battery-capacity-on-conference-call/`

### Describe the issue

Page won't be shown until you disable adblock.

### Versions

- Browser/version: Chrome 62.0.3202.94 (Official Build) (64-bit)
- uBlock Origin version: v1.14.18

**Comment by okiehsch** [comment]
Do you use your filterlist `https://github.com/nimasaj/uBO_Filterlist/blob/master/BLF.txt`?

**Comment by nimasaj** [comment]
Yes, 
I see `##*[class^="ads-"]` is making the issue.
Hmmm, Element hiding rule.

**Comment by okiehsch** [comment]
If you want to keep the generic rule `##*[class^="ads-"]` in your list, just
add `caranddriver.com#@#*[class^="ads-"]` to fix your issue.
