### ISSUE TITLE
derstandard.de breakage

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#8680]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.derstandard.de/story/2000086662517/hausdurchsuchungen-und-abmahnungen-wie-epic-gegen-fortnite-cheater-vorgeht`

### Describe the issue

Can’t past the cookie banner

### Screenshot(s)

<img width="564" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/110253219-6532b080-7f89-11eb-8648-6ab7fd5f35d6.PNG">

### Versions

- Browser/version: Firefox developer
- uBlock Origin version: uBlock Origin v1.33.2

### Settings

default + uBlock Origin annoyances

### Notes

bad filter: `derstandard.*##+js(abort-on-property-write, _sp_)`

**Comment by mapx-** [comment]
Do you get anti adb stuff without that filter ?

**Comment by okiehsch** [comment]
No.
