### ISSUE TITLE
UStream.to Adblock Detected

### ISSUE THREAD

**Issue by Vaskiemaia** [uBlockOrigin/uAssets#8681]
When opening any channel on UStream it will detect Ublock Origin and it won't work until it's disabled.

Upon disabling the page will be filled with redirects, popups and ads

**Comment by Vaskiemaia** [comment]
Checking the logger, UStream will change the key for the stream.

For example: https://www.ustream.to/live?id=sic-portugale&program=2b44bd0096f425813299c2b1539b90cc

UBlock Disabled: https://hls.ustream.to/SIC-Portugal.m3u8?token=dec-4f3-99d-e6c-bce-aef-c6f-c94-c5e-ab7-1d9-b0e-d2c-853-5f6-70f-f78-797-256-eef-85c-9-a5d-d1c-e8t-f6c

UBlock Enabled: https://hls.ustream.to/SIC-Portugal.m3u8?token=adblocker-a5d-d1c-e8t-f6c

**Comment by mapx-** [comment]
test

```
*$script,redirect-rule=noopjs,domain=beef1999.blogspot.com
@@||bestdisplayformats.com^$script,domain=beef1999.blogspot.com
beef1999.blogspot.com##+js(aopr, console.clear)
beef1999.blogspot.com##+js(aopr, LieDetector)
```

**Comment by Vaskiemaia** [comment]
That worked perfectly!

I got two questions for you:

- How can i do that myself in the future in case they change the page it's pointing to (how did you figure it out) ?
- Could this filter be added to any of the lists, so it also works on Android when using one of the many adblocks

**Comment by mapx-** [comment]
> How can i do that myself in the future in case they change the page it's pointing to (how did you figure it out) ?

You need some experience, to know how to read the page code - scripts, to know what weapons (uBO features, scriptlets) could be used, to study and understand other fixes for other pages.

**Comment by Vaskiemaia** [comment]
I definitely don't have those, but just looking at your code, i could probably change the link it's pointing so in case they modify that.

Could this be added to one of the many filter lists ?

**Comment by mapx-** [comment]
The filters were already added, look above => `closed this in b9e814b`

**Comment by Vaskiemaia** [comment]
I am new to Github so excuse my ignorance. Your work is very much appreciated and i don't mean to undermine it.

**Comment by mapx-** [comment]
continuing this one

**Comment by wout-codes** [comment]
@mapx- You're great! Can you try these rules ?

@Vaskiemaia Can you too try these rules? Make sure to disable uBlock Filters.

```
beef1999.blogspot.com##+js(abort-on-property-read, AaDetector)
ustream.to##+js(acis, String.fromCharCode, constructor)
beef1999.blogspot.com##+js(aopw, LieDetector)
beef1999.blogspot.com##+js(aeld, , [$.)
```

**Comment by mapx-** [comment]
last commit was
https://github.com/uBlockOrigin/uAssets/commit/fd9de0f1c9e415a30a92ece6e4d5b4b2f4e52be1

still working

**Comment by wout-codes** [comment]
@mapx- whitelists causes problems like popups.

**Comment by mapx-** [comment]
> whitelists causes problems like popups

There is no whitelist actually

**Comment by wout-codes** [comment]
> > whitelists causes problems like popups
> 
> There is no whitelist actually

Yeah you're right. But check, there are some popups I can see.

**Comment by wout-codes** [comment]
Weird. 3 hours ago I tried I got bunch of popups, and now it's gone.

**Comment by mapx-** [comment]
maybe they are trying to replace their crap

**Comment by wout-codes** [comment]
@mapx- They replaced their crap. I fixed it for AdGuard yesterday, and now it's all back except for popups. 😢😒

**Comment by okiehsch** [comment]
The site is down atm.
![image](https://user-images.githubusercontent.com/16838044/110723091-cb326880-8213-11eb-881d-b3f5b8855053.png)

**Comment by wout-codes** [comment]
> The site is down atm.

Yeah. 20 minutes ago it was working fine and now it's down. Probably updating their scripts.

**Comment by okiehsch** [comment]
````
@@||profitabletrustednetwork.com^$script,domain=beef1999.blogspot.com
||profitabletrustednetwork.com^$xhr,redirect-rule=noop.js,domain=beef1999.blogspot.com
````
works on my end.

**Comment by wout-codes** [comment]
I will try to fix with scriptlets. Lemme get back to it.

**Comment by okiehsch** [comment]
To be clear my filters are fixing the anti adblock message I get.
Your filter does not fix that issue.

**Comment by wout-codes** [comment]
I think emptying the whole script is the only way. I will craft a rule to empty it and add it.

**Comment by okiehsch** [comment]
Hm, actually looking at it further the exception is not needed for me.
`||profitabletrustednetwork.com^$xhr,redirect-rule=noop.js,domain=beef1999.blogspot.com`
alone works fine.

**Comment by Vaskiemaia** [comment]
I am so very sorry to have given everyone so much trouble.
Unfortunately it seems as if they will keep updating their scripts to fight adblocking.

**Comment by wout-codes** [comment]
@okiehsch @mapx- Add this, they changed their code. I am not sure if this is the correct uBO's Syntax.
`beef1999.blogspot.com#%#//scriptlet("prevent-eval-if", "use_adebloker")`   == > (AdGuard)
`beef1999.blogspot.com##+js(noeval-if.js, use_adebloker)` == > (uBO)

**Comment by okiehsch** [comment]
@wout-codes still works fine, i.e. no anti adblock message stream plays without issue, on my end.

**Comment by okiehsch** [comment]
Does your confused emoji mean that you can reproduce with `uBO`?

**Comment by wout-codes** [comment]
> Does your confused emoji mean that you can reproduce with `uBO`?

Yeah.

**Comment by okiehsch** [comment]
The example link of the OP?
What browser?

**Comment by wout-codes** [comment]
> The example link of the OP?
> What browser?

Chrome. And this link: `https://www.ustream.to/live?id=sic-portugale&program=2b44bd0096f425813299c2b1539b90cc`. I check for anti-adb in this everyday, and fix it. Fixed in AdGuard yesterday, but if disabled, I can reproduce with uBO.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/111014639-f5676000-83a4-11eb-9e92-32c8fea4f166.png)

With chrome and uBO.

**Comment by wout-codes** [comment]
> ![image](https://user-images.githubusercontent.com/16838044/111014639-f5676000-83a4-11eb-9e92-32c8fea4f166.png)
> 
> With chrome and uBO.

I am not sure why. I will check later on again.
