### ISSUE TITLE
Fanboy’s Annoyance filter list prevents the arrivals/departures tables being displayed

### ISSUE THREAD

**Issue by pubmikeb** [uBlockOrigin/uAssets#8685]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://www.iaa.gov.il/en/airports/ben-gurion/flight-board/?flightType=arrivals`

### Describe the issue
With enabled **Fanboy’s Annoyance** filter list the arrivals/departures tables can't be displayed, once this list is disabled, the website look correctly.

### Screenshot(s)
Without **Fanboy’s Annoyance** filter list:
![08_092057](https://user-images.githubusercontent.com/17231333/110287746-acec2300-7fef-11eb-9ecb-711478f181f3.png)

With **Fanboy’s Annoyance** filter list:
![08_092037](https://user-images.githubusercontent.com/17231333/110287762-b5dcf480-7fef-11eb-9bf2-5a8caf07f13f.png)

### Versions

- Browser/version: 
  * Microsoft Edge 89.0.774.45 (Official build) (64-bit)
  * Google Chrome 90.0.4430.11 (Official Build) dev (64-bit)

- uBlock Origin version: [uBlock Origin development build v1.33.3rc1]

### Settings
Only **Fanboy’s Annoyance** on/off impacts this issue.

**Comment by mapx-** [comment]
add
`iaa.gov.il#@##toTop`

@ryanbr
