### ISSUE TITLE
pixelcounter.dev incorrectly blocked

### ISSUE THREAD

**Issue by johnkavanagh** [uBlockOrigin/uAssets#8688]
Related to #8393 which was opened and resolved very quickly (thank you!) back in December.

### URL(s) where the issue occurs

`pixelcounter.dev`

### Describe the issue

I'm the owner of `pixelcounter.dev`, at present uBlockOrigin blocks AJAX calls to this domain.

This appears to be a bit of an on-going issue with `EasyPrivacy` and domains which contain 'pixelcounter'.

### Screenshot(s)

<img width="1124" alt="Screenshot 2021-03-08 at 14 46 04" src="https://user-images.githubusercontent.com/2272755/110336712-0880d580-801d-11eb-8427-925ca82ae205.png">

### Versions

- Browser/version: Chrome 88.0.4324.192 (OSX)
- uBlock Origin version: 1.33.2

### Settings

Default

### Notes

Replica #8393, only with the domain `pixelcounter.dev` instead of `pixelcounter.com`.  For what it's worth, I also own:

- `pixelcounter.co.uk`
- `pixelcounter.org`
- `pixelcounters.co.uk`
- `pixelcounters.uk`

... all of which will also fall foul of this particular issue.

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by uBlock-user** [comment]
Can't reproduce any issue at `https://johnkavanagh.co.uk/contact`

**Comment by uBlock-user** [comment]
Run the uBO logger which will show if there's anything blocked by any filterlist, `(blocked:other)` means something else is blocking the resource, not the extension.

**Comment by johnkavanagh** [comment]
@uBlock-user please do give it another go.  You need to attempt to submit the Contact Form on https://johnkavanagh.co.uk/contact/ to connect to the `pixelcounter.dev` endpoint .

uBO Blocker confirms that it's the extension blocking it:

<img width="1431" alt="Screenshot 2021-03-08 at 15 15 38" src="https://user-images.githubusercontent.com/2272755/110340507-4253db00-8021-11eb-98be-1b1c52dc0a08.png">

**Comment by johnkavanagh** [comment]
@ryanbr was able to resolve this last time by editing EasyPrivacy here:

https://github.com/easylist/easylist/commit/a48588e802a4d7039c9da3c18e1951a1e4aafe82

I'm happy for this just to be another case of getting the domains white-listed, but perhaps we could take another look at why domains containing 'pixelcounter' are being blocked at all?  It strikes me that if there are problem domains, it might make more sense to include them explicitly, rather than having to whitelist each time..

Just to confirm again, I own (and do not use for any nefarious reasons):

- `pixelcounter.com`
- `pixelcounter.dev`
- `pixelcounter.co.uk`
- `pixelcounter.org`
- `pixelcounters.co.uk`
- `pixelcounters.uk`

For reference, my company is called PixelCounter Ltd, hence the domains! :)
