### ISSUE TITLE
Annoying cookie/GDPR css

### ISSUE THREAD

**Issue by romulasry** [uBlockOrigin/uAssets#8689]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://ubuntu.com//blog/why-is-ubuntu-linux-the-leading-choice-to-replace-centos-for-finserv-infrastructure`

Some news sites,, I will add if I find them again.

### Describe the issue
Cookie setting thing, would like a bypass
 

### Screenshot(s)

Can't find at the moment. Exited it; will get it if I get it again.
### Versions

- Browser/version: [Firefox/85.0]
- uBlock Origin version: [1.33.2]

### Settings

-Added annoyances filter because that is what this is.

### Notes

https://css-tricks.com/why-every-website-wants-you-to-accept-its-cookies/
https://www.reddit.com/r/web_design/comments/93o0eg/cookie_policy_notifications_have_ruined_user/
https://premium.wpmudev.org/blog/cookie-consent-notices/

**Comment by mapx-** [comment]
Enable Fanboy's Annoyances list or add:

`ubuntu.com##.cookie-policy`
