### ISSUE TITLE
[NSFW] Multiple Redirections / Pop-ups Appearance

### ISSUE THREAD

**Issue by elsy04** [uBlockOrigin/uAssets#869]
**### URL(s) where the issue occurs**

`https://www.porntrex.com/*
`

**### Describe the issue**

Right opening this site for the first time (with clean cookies), by just using the right scroll bar or doing a left-click on a free space of the main website, it will start redirecting and opening pop-ups in new tabs as well as new external windows. It will keep doing it frequently, till the point even videos can't be watched correctly, since new redirections and pop-ups will show up and stop the video completely randomly after doing some click anywhere. 

Some of the redirections/pop-ups sites:

```
https://bfc70a51929fff2d7fe.com/*
livejasmin.com (external window)
```

**### Screenshot(s)**

[Will post them if needed]

**### Versions**

Browser/version: [Firefox ESR v52.4.0 x64]
uBlock Origin version: [1.14.18]

**### Settings**

No changes but updating the default filters' list.

****### Notes****

Using UBlock's own pop-up blocker isn't enough.

**Comment by okiehsch** [comment]
````
porntrex.com##script:inject(abort-current-inline-script.js, parseInt, tabunder)
porntrex.com##script:inject(popads-dummy.js)
````
takes care of all popups on my end.

**Comment by elsy04** [comment]
Effectively, all the crap is gone with those filters.

Thanks a lot for that. :+1: 

**P.D.** As with my previous post, I just saw threads are closed in a very quick way here, sometimes without even waiting for the members' feedback. Luckily enough, this one is still open, so I'm able to give thanks and confirm that all is fine (not as with my previous "xmovies" thread).

**Comment by okiehsch** [comment]
@elsy04 there is a difference between a `closed` issue and a `locked` issue, like your previous issue https://github.com/uBlockOrigin/uAssets/issues/723.
If an issue is `closed`, like this one, you can still comment and give feedback.
If an issue is `locked` you can't. this is usually the case , if comments are deemed to be not constructive, or offensive.

**Comment by elsy04** [comment]
OK, thanks for the clarification.

I see my previous post was locked by "gorhill", because "no point adding more to it"; but it weren't even a few hours since I created that thread, when it was already locked, which didn't allowed me to even comment about the proposed workarounds.

Anyway, I see it was re-opened again, and the filters are still working fine so far. :+1:

**Comment by KiLL4FuNK** [comment]
ADS PLAY VIDEO
