### ISSUE TITLE
linkpoi.me anti-adb

### ISSUE THREAD

**Issue by ikhoeyZX** [uBlockOrigin/uAssets#8695]
### URL(s) where the issue occurs
[NSFW] `https://linkpoi.me/LqDyNLzm`

### Describe the issue
can't show real page (page was replaced by adblock detector)

### Screenshot(s)
![Screenshot_20210310-020847](https://user-images.githubusercontent.com/79812109/110517259-9821a380-8145-11eb-92f5-82765a3410f5.png)

### Versions

- Browser/version: [firefox mobile 68.11 x86]
- uBlock Origin version: [1.33.2]

### Settings

-. Default settings.
-. mark spesific content

### Notes

it's look like they change new web page bypasser with special adblock detector, so disable it only work but it's hard to push download button due ads

**Comment by JobcenterTycoon** [comment]
`linkpoi.me##+js(nobab)`
`linkpoi.me##+js(aopr, app_vars.force_disable_adblock)`

works for me
