### ISSUE TITLE
www.mobileread.com

### ISSUE THREAD

**Issue by cantunborn** [uBlockOrigin/uAssets#8696]
### URL(s) where the issue occurs

```
https://www.mobileread.com/forums/ebooks.php?order=desc&sort=dateline
https://www.mobileread.com/forums/showthread.php?t=11988
```

### Describe the issue

Ad placeholder in 1st link.
Ad leftovers between posts in 2nd link.

### Versions

- Browser/version: Chrome 89.0.4389.82
- uBlock Origin version: 1.33.2

### Settings

- All uBO lists enabled except regional and adguard mobile ads.

**Comment by Caramel7** [comment]
You can submit an issue on https://github.com/easylist/easylist/issues and https://github.com/adguardteam/adguardfilters/issues.
Also, if you are using Fanboy's Annoyance and Fanboy's Social I'd suggest removing Fanboy's Social since it's included in Fanboy's Annoyance.

**Comment by cantunborn** [comment]
I created the issue here since it may not be possible to fix using only easylist syntax.

**Comment by mapx-** [comment]
```
mobileread.com##tbody [style]:has(.adsbygoogle)
mobileread.com##tbody:has-text(Advert)

```
@ryanbr

**Comment by mapx-** [comment]
EL can use the syntax above (in ABP syntax => uBO is able to translate ABP syntax)

**Comment by cantunborn** [comment]
Is `:upward()` supported in EL?

**Comment by mapx-** [comment]
I didn't use upward

**Comment by cantunborn** [comment]
I am asking because I don't know. Wouldn't `mobileread.com##tbody:has(.thead:has-text(Advert))` avoid false positives better?
