### ISSUE TITLE
[Anti-Adblock] www.genelpara.com

### ISSUE THREAD

**Issue by Mspy1** [uBlockOrigin/uAssets#8699]
### URL(s) where the issue occurs

`https://www.genelpara.com`

### Describe the issue

An Anti-Adblock banner appears in Turkish language.

 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/33182973/110665659-a3beaa00-81d9-11eb-8d2b-252562fea93c.png)

### Versions

- Browser/version: Chrome 88.0.4324.190
- uBlock Origin version: uBlock Origin v1.33.2

### Settings

All annoyances filters are selected.

### Notes

Self-explanatory.

**Comment by 96273** [comment]
no longer seems to be using anti-adblock
