### ISSUE TITLE
Video ads as well as "picture" ads on sueddeutsche.de

### ISSUE THREAD

**Issue by Snow8** [uBlockOrigin/uAssets#87]
### Describe the issue

When starting a video on sueddeutsche, the video plays for maybe a second before an ad video starts playing in its place.

There are also a lot of "picture" ads shown on the page.

### One or more specific URLs where the issue occurs

http://www.sueddeutsche.de/
http://www.sueddeutsche.de/bayern/anschlag-nahe-musikfestival-angreifer-von-ansbach-besass-islamistische-gewaltvideos-1.3094000

### Screenshot in which the issue can be seen

![untitled](https://cloud.githubusercontent.com/assets/11486958/17103824/8371ac12-5280-11e6-84a8-4e1c446a2318.png)
![untitled2](https://cloud.githubusercontent.com/assets/11486958/17103830/88fe57de-5280-11e6-94f7-ae04d7f39e8d.png)

### Steps for anyone to reproduce the issue

Just go to the side and start playing the video/look around for the "picture" ads.

### Your settings

- Browser/version: Opera 39.0.2256.37 
- uBlock Origin version: 1.7.6

##### Your filter lists

Advanced user, no "my filter" entries, Globally blocked 3rd-Party Frames, no other settings for sueddeutsche.de

![untitled3](https://cloud.githubusercontent.com/assets/11486958/17103929/f2dd8a44-5280-11e6-9583-6bcec3161268.png)
![untitled4](https://cloud.githubusercontent.com/assets/11486958/17103935/f71ca0d6-5280-11e6-9ab0-6d230c5c848e.png)

Thank you for looking into this.

**Comment by gorhill** [comment]
Is the video player on your side Flash-based or HTML5-based?

**Comment by Snow8** [comment]
It is HTML5 based. Flash is disabled in my Opera.

**Comment by gorhill** [comment]
For the video ad, can you try:

    ||s3.amazonaws.com/homad-global-configs.schneevonmorgen.com/hd-main.js$script,domain=sueddeutsche.de,redirect=hd-main.js

For the image ad, can you try:

    ||polpix.sueddeutsche.de/$image

For the image ad, best would be to ask EasyList Germany author to add it to their list.

**Comment by Snow8** [comment]
wow. Thanks a lot. That seems to did it so far. I just did a quick check and the pictures are gone and the video plays without interruption.

I will look into contacting the EasyList Germany author :)

Thanks again.

**Comment by gorhill** [comment]
The solution for the video ads is specific to uBO, so I added it to uBO's own filters. For the image ad, best is to have the filter added to EasyList Germany.
