### ISSUE TITLE
[NSFW] Redirecting Annoyance

### ISSUE THREAD

**Issue by elsy04** [uBlockOrigin/uAssets#870]
**### URL(s) where the issue occurs**

`https://yourporn.sexy/*
`

**### Describe the issue**

This site has script which redirects every now and then (according to cookies state AFAIK). Its behavior is the same as the one I reported before here: #723.

In this case, the buggering site is:

`bfc70a51929fff2d7fe.com
`

**### Screenshot(s)**

[Will post them if needed]

**### Versions**

Browser/version: [Firefox ESR v52.4.0 x64]
uBlock Origin version: [1.14.18]

**### Settings**

No changes but updating the default filters' list.

**### Notes**

I already tried the methods mentioned in the other thread, but most of them don't work; the only one that works is the "defuser" related one, but it will block the thumbnails preview.

Thanks.

**Comment by okiehsch** [comment]
Does
````
yourporn.sexy##script:inject(abort-on-property-write.js, Fingerprint2)
yourporn.sexy##script:inject(noeval.js)
````
work without breaking anything?

**Comment by elsy04** [comment]
Effectively, those ones work rightly. :+1: 

Thanks for your prompt reply. :)

**Comment by dumbusernameidk** [comment]
@okiehsch 
Site name has changed to `sxyprn.com`

**Comment by okiehsch** [comment]
I don't get any redirections at `sxyprn.com`, do you have a specific example?

**Comment by dumbusernameidk** [comment]
Redirections as in popups? I don't think so not from what i've seen. But all the cosmetic filtering will need to be re-added since the site went from `yourporn.sexy` > `sxyprn.com`

**Comment by Omega-6** [comment]
(nsfw) `https://sxyprn.net/post/656f6a14e651b`
