### ISSUE TITLE
Washington Post Anti-Adblock

### ISSUE THREAD

**Issue by 1zaman** [uBlockOrigin/uAssets#8700]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - I found some old issues that showed the same issue, but they were all closed, and apparently fixed at that time.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.washingtonpost.com/world/national-security/in-nsa-intercepted-data-those-not-targeted-far-outnumber-the-foreigners-who-are/2014/07/05/8139adf8-045a-11e4-8572-4b1b969b6322_story.html`

### Describe the issue

A Washington Post article displays an anti-adblock banner and only shows a small preview of the full article beneath it. The full article is originally loaded, but it's replaced with the preview once the anti-adblock banner is displayed.

 

### Screenshot(s)

![Screenshot_2021-03-11 In NSA-intercepted data, those not targeted far outnumber the foreigners who are](https://user-images.githubusercontent.com/4244109/110719285-6c2e1d00-822e-11eb-8ae8-845d111ed018.png)

### Versions

- Browser/version: Firefox 86.0
- uBlock Origin version: 1.33.2

### Settings

I have all the Annoyances filters toggled on, as well as a few other non-default filters. I also tried installing Nano Defender for Firefox, which didn't help. I have also tested and verified this on a clean profile of Firefox, with only uBlock Origin installed with the default settings.

### Notes

Toggling off EasyList and Peter Lowe's Ad and tracking server list fixes it. Disabling inline scripts also fixes it, but breaks images and similar resources.

**Comment by llacb47** [comment]
Can't reproduce. Filters in uBlock filters still working

**Comment by Pccode66** [comment]
I also can't reproduce it

**Comment by uBlock-user** [comment]
I can reproduce on Firefox.

**Comment by okiehsch** [comment]
`washingtonpost.com##^script:has-text(_0x)`
works for me.

**Comment by okiehsch** [comment]
@uBlock-user can you reproduce on any "new" articles on the site?

Seems to be only occuring on very old articles like the seven year old linked in the OP's post.

**Comment by uBlock-user** [comment]
I was going with `washingtonpost.com##^script:has-text(displayOverlay)`, but if there's no breakage, then okay. 

@okiehsch No, but I can consistently reproduce on the OP's page.

**Comment by okiehsch** [comment]
> No, but I can consistently reproduce on the OP's page.

Same here, newer articles don't have that part in their source, so the filter should not break anything.
