### ISSUE TITLE
Wired login-wall

### ISSUE THREAD

**Issue by 1zaman** [uBlockOrigin/uAssets#8702]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.wired.com/story/what-we-talk-about-when-we-talk-about-movies/`

### Describe the issue

 

Wired blocks an article from reading without signing in if uBlock Origin is installed. The article is briefly loaded, but then the content is removed and a bottom banner appears requiring the user to sign in to keep reading the article. This does not happen if uBlock Origin is disabled, though the page might need to be reloaded multiple times after disabling in order to work properly.

### Screenshot(s)

![Screenshot_2021-03-12 Authority Figures Movie Talk and the Rise of Review Culture](https://user-images.githubusercontent.com/4244109/110894077-08cce980-8319-11eb-8f3b-f3f546850153.png)

### Versions

- Browser/version: Firefox 86.0.1
- uBlock Origin version: 1.34.0

### Settings

I have all the Annoyances filters toggled on, as well as a few other non-default filters. I also tried installing Nano Defender for Firefox, which didn't help. I have also tested and verified this on a clean profile of Firefox, with only uBlock Origin installed with the default settings.

### Notes

Blocking requests to `h2.condenast.map.fastly.net` fixes the issue, but at the cost of image and video resources not being loaded, as well as the right sidebar with links to the most popular articles.

**Comment by uBlock-user** [comment]
`wired.com##.paywall-modal` works

**Comment by uBlock-user** [comment]
Looks like a paywall/login-wall fixable with `||journey.wired.com^`

**Comment by 1zaman** [comment]
Thanks @uBlock-user, the issue with the login wall always showing with uBlock Origin seems to be fixed now after updating the filters.

However, now the login wall is also blocked when the article is not fully loaded due to having exhausted the free articles quota or viewing a sponsored article. In that case only a preview of the article is shown (usually just the first paragraph of it) instead of the full article, but due to the login wall being hidden in this case as well, this can be a bit unclear as to what happened and why.

If there is a way to only block the adblock-detection part of the script, instead of completely blocking the login wall in every case, then that might be a less confusing solution. However, if there's no way to achieve that outcome, than I am fine with the current solution.

I am attaching a full-page screenshot below of an article that is shown only as a preview due to having exhausted the free articles quota, without this being completely clear due to the blocking of the login wall:

![Screenshot_2021-03-12 Good-Bye Zoom Hello Low-Key Ambient Snooping](https://user-images.githubusercontent.com/4244109/110962370-ba4c3900-8372-11eb-8886-44622158251b.png)

**Comment by uBlock-user** [comment]
They have a paywall too and we don't fix paywalls.

**Comment by 1zaman** [comment]
> They have a paywall too and we don't fix paywalls.

OK, though I was able to get access to the article by creating a free account.

> You can use `wired.com##+js(cookie-remover, /^/)` to avoid the paywall.

Thanks for the tip, that seems to work!

----

I also noticed that the issue with the login banner always being shown with uBlock Origin seems to be gone now, even without the annoyances filter toggled on 🤷‍♂️
