### ISSUE TITLE
dnsperf.com is broken

### ISSUE THREAD

**Issue by huupoke12** [uBlockOrigin/uAssets#8705]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://www.dnsperf.com`

### Describe the issue
The site is broken.
 

### Screenshot(s)
![image](https://user-images.githubusercontent.com/16283764/110969722-9cd79900-838b-11eb-840d-b2bfd7641c73.png)

### Versions

- Browser/version: Firefox 78.8.0esr
- uBlock Origin version: 1.34.0

**Comment by uBlock-user** [comment]
force update EasyPrivacy
