### ISSUE TITLE
send.cm

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8706]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where this occurs

`https://send.cm/xm2n3sets3ot`

### Describe the issue

Popup ads

### Versions

- Browser/version: Firefox a nightly
- uBlock Origin version: 1.33.2

### Settings

 uBO's default settings
-

**Comment by ghajini** [comment]
there's popup

`https://send.cm/fyorljhkqqt2`

**Comment by Wassss** [comment]
`send.cm##^script:has-text(FingerprintJS)` break download link
how can i remove it ?

**Comment by mapx-** [comment]
test link ?

**Comment by ghajini** [comment]
**Test link=**

`https://send.cm/9r1esq0jf16o`

where's broken, i can download the file

**Screenshots=**

https://user-images.githubusercontent.com/20338483/142376088-c4bf1382-c08b-4923-ba60-7e9c675b90fe.png

https://user-images.githubusercontent.com/20338483/142376098-35c8f102-bd54-4b7c-8388-6e7eb50bb377.png

**Comment by Wassss** [comment]
@mapx- it work now
thank you

**Comment by Demanding0536** [comment]
Annoyance: On video file pages, right click is blocked and a keyboard shortcut to open dev tools is blocked (ctrl+shift+i). Opening dev tools/inspect causes the page to close itself, and loading the page with it enabled will cause it to close itself during load.

Test link: `https://send.cm/d/naW4`

Tested with latest Firefox and uBO, default lists and default + all annoyance filters.
