### ISSUE TITLE
uBlock blocks files&folders in Nextcloud that contain word "adtech"

### ISSUE THREAD

**Issue by hanswundersam** [uBlockOrigin/uAssets#8708]
I have battled a long time with `https://nextcloud.com` behaving weirdly with some of my folders and files until I realised that uBlockOrigin prevents the Nextcloud web interface from accessing, renaming, changing, and even deleting any file or folder with a name that includes the term "adtech" or "ad tech". I assume this is potentially true for other black-listed terms. Big problem for people working on studying (and fighting against :) the ad tech industry.

Only solution is to whitelist the Nextcloud's domain in uBlock settings.

Not sure if this can be considered an issue, it's certainly breaking things, so I decided to flag it here. If this cannot be fixed in uBlock, perhaps it's worth for @Nextcloud to mention this in their documentation given how popular ad blockers are.

**Comment by okiehsch** [comment]
> Only solution is to whitelist the Nextcloud's domain in uBlock settings.

I think that's the only practical solution. There are a huge number of keywords in `EasyList` and `EasyPrivacy` that could conceivably be used to name some private folders.

**Comment by hanswundersam** [comment]
Thanks @okiehsch. Do you know if there is anything the people at Nextcloud could do to prevent this from happening?

**Comment by okiehsch** [comment]
Other than mentioning it in the documentation I don't see what they can do.

**Comment by uBlock-user** [comment]
You can use `@@||nextcloud.com^$1p` and provide feedback on that.

**Comment by okiehsch** [comment]
@uBlock-user you can see the breakag yourself if you start a demo session and create a folder called "adtech".
Open it and you will get a notifcation .
![image](https://user-images.githubusercontent.com/16838044/111027463-d1317080-83f0-11eb-85e3-68445c8c8372.png)

That is caused by
![image](https://user-images.githubusercontent.com/16838044/111027475-e60e0400-83f0-11eb-9f67-17989d013dc0.png)


Your filter would solve that issue.

**Comment by uBlock-user** [comment]
@okiehsch tried at `https://demo1.nextcloud.com/apps/files/`, can't reproduce it, deletion worked, there's no first-party blockage as per the logger.

**Comment by uBlock-user** [comment]
I had to create a txt file inside adtech folder to reproduce, creating a folder doesn't break anything.

@ryanbr

**Comment by okiehsch** [comment]
>  creating a folder alone doesn't break anything.

Depends on what you name the folder.
Try creating one named ".adsremote."

**Comment by okiehsch** [comment]
That fixes the publicly reachable demo site, if self hosting is still broken because of  domain changes there is nothing we can do.
