### ISSUE TITLE
List of web pages that I found they are detecting uBlock as an adblocker

### ISSUE THREAD

**Issue by Ish020** [uBlockOrigin/uAssets#8718]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

```
https://live.giscr.ac.th/
https://100count.net/
https://faucet.100count.net/
https://faupto.com/
https://ccurl.net/
https://bitcoinly.in/
```

### Describe the issue

 
When using shortlinks from the pages described above, seems that uBlock is detected as an adblocker so, in most of the cases, I can reach the link just by disabling cosmetic filter, but in some of them (ccurl.net), I just have to disable extension to make the shortlink appear as expected.

### Versions

- Browser/version: [Brave v1.21.74]
- uBlock Origin version: [v1.33.2]

### Settings

- Image attached
- 
https://user-images.githubusercontent.com/80630203/111070569-9dc71280-84d2-11eb-9e7c-58fb2607f17e.jpg

### Notes

Just having in mind that the settings from the image attached and that I'm using Brave browser which already has its own adblocker, to report these sites I've tried to assure that uBo was the only working extension, so I could say that there's not expected collision between them.

**Comment by uBlock-user** [comment]
> When using shortlinks from the pages described above

Post those links

**Comment by Ish020** [comment]
https://ccurl.net/redirectpage/aJuP
https://100count.net/pageone/first_page.php
https://faucet.100count.net/clickit/sh/rJZY
https://faupto.com/sldoge/
https://live.giscr.ac.th/QBi2
https://bitcoinly.in/H0jS
