### ISSUE TITLE
1001tracklists.com adblock warning message

### ISSUE THREAD

**Issue by tommy3093** [uBlockOrigin/uAssets#8719]
### URL(s) where the issue occurs

`https://www.1001tracklists.com/dj/oliverheldens/index.html`

### Describe the issue

When you click on any tracklist/DJ/track it shows warning message to disable adblock. Happens like every 30 minutes and first time you visit the page.

### Screenshot(s)

![popup](https://user-images.githubusercontent.com/155648/111080180-949f6b00-84fd-11eb-9f85-69fa812bc1f3.png)

### Versions

- Browser/version: Firefox 86.0.1
- uBlock Origin version: 1.34.0

### Settings

Default + added uBlock, AdGuard, Fanboy filter annoyances.

**Comment by tommy3093** [comment]
Hi,

Thank you for quick provided fix. I have been trying to add something similar through element picker, the issue with this is, page is not scrollable and needs refresh to work.

**Comment by uBlock-user** [comment]
fixed, force update uBlock Filters list in a while.

**Comment by tommy3093** [comment]
Now it seems resolved. Thanks a lot!

**Comment by mapx-** [comment]
I cannot reproduce the detection

**Comment by mapx-** [comment]
social stuff

```adb
@@||1001tracklists.com^$ghide
```
