### ISSUE TITLE
wzamrani.com

### ISSUE THREAD

**Issue by Toshiba1127** [uBlockOrigin/uAssets#8723]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.wzamrani.com/internet-download-manager-idm-6-38-build-18/`

### Describe the issue

Countdown begins in 48 seconds

### Screenshot(s)

![image](https://user-images.githubusercontent.com/64008639/111145063-2358ca00-8588-11eb-99c6-f1240a8502ea.png)

### Versions

- Browser/version: Chrome Version 89.0.4389.82
- uBlock Origin version: v1.33.2

### Settings

- Default

**Comment by uBlock-user** [comment]
Timer can't be sped up, but the button will now be visible.
