### ISSUE TITLE
CleverPush button blocked on Bsdex.de

### ISSUE THREAD

**Issue by rugk** [uBlockOrigin/uAssets#8727]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile (only enabled AdGuard Annoyances)
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://app.bsdex.de`

### Describe the issue

There is no bell allowing me to opt-in to notifications (and the banner for that is blocked too).

### Screenshot(s)

![profileNoPushIcon](https://user-images.githubusercontent.com/11966684/111383995-47f89300-86a9-11eb-8569-4466fef505b7.png)

It should be this:
![grafik](https://user-images.githubusercontent.com/11966684/111384389-bb9aa000-86a9-11eb-9820-7124076a47b1.png)

### Versions

- Browser/version: Firefox 86.0.1
- uBlock Origin version:  v1.34.0

### Settings

- enable _AdGuard Annoyances_ as a filter list

I also disabled Firefox internal tracking protection for the current site as a test. :slightly_smiling_face: 

### Notes

Apparently it's the `cleverpush.com` server that is totally blocked. IMHO this is too much, as it's still a useful feature, at least when there is a clear opt-in/button I have to click on.

![grafik](https://user-images.githubusercontent.com/11966684/111385037-82aefb00-86aa-11eb-9e30-baf231401a27.png)

![grafik](https://user-images.githubusercontent.com/11966684/111384878-4ed3d580-86aa-11eb-8037-681f660fb958.png)

The uBlock window says it's also included(?) in EasyPrivacy though, but I can only reproduce the issue with  _AdGuard Annoyances_. _EasyPrivacy_ is enabled by default AFAIK.

**Comment by JobcenterTycoon** [comment]
Better to report it here: `https://github.com/AdguardTeam/AdguardFilters/issues`

**Comment by uBlock-user** [comment]
Currently under maintenance as per `https://www.bsdex.de/maintenance.html`

**Comment by rugk** [comment]
Seeing this has been fixed here, now, should I still report it at https://github.com/AdguardTeam/AdguardFilters/issues?

I'm a little confused.
I guess this is a upstream  though, so I'll just do so: https://github.com/AdguardTeam/AdguardFilters/issues/77724

**Comment by krystian3w** [comment]
AdGuard annoyance no based on EasyPrivacy, better no remove created report.

I suppose AdGuard Spyware also no copy filter from EasyPrivacy: https://github.com/AdguardTeam/AdguardFilters/tree/master/SpywareFilter/sections

**Comment by rugk** [comment]
They have fixed it too, now.
