### ISSUE TITLE
[UPDATE] Request Domains to be added to Resource Abuse list

### ISSUE THREAD

**Issue by DaBomby** [uBlockOrigin/uAssets#873]
Please consider adding the following domains/rules to the uBlock resource abuse list.

||gus.host/coins.js
||miner.pr0gramm.com^$third-party
||miner.pr0gramm.com^$websocket
||miner.pr0gramm.com/cryptonight-worker.js
||xbasfbno.info^$third-party
||azvjudwr.info^$third-party
||jroqvbvw.info^$third-party
||jyhfuqoh.info^$third-party
||kdowqlpt.info^$third-party
||minero-proxy-01.now.sh^$third-party
||minero-proxy-02.now.sh^$third-party
||minero-proxy-03.now.sh^$third-party
||kiwifarms.net/js/Jawsh/xmr/xmr.min.js
||api.inwemo.com^$third-party
||rocks.io^$third-party
||adminer.com^$third-party
||77.162.125.199^$third-party

Thanks in advance!

**Comment by mapx-** [comment]
`https://kiwifarms.net/js/Jawsh/xmr/xmr.min.js` does not exist anymore

All others are already in `easyprivacy` list => part of default setup in uBo
