### ISSUE TITLE
megaup.net - Anti-Adblock

### ISSUE THREAD

**Issue by Joyer1234** [uBlockOrigin/uAssets#8737]
**URL(s) where the issue occurs**
https://megaup.net/VXvw/Superman.and.Lois.S01E03.720p.HDTV.2CH.x265.HEVC-PSA.rar

**Describe the issue**
After 5 second cooldown on any  megaup.net file links result in an anti-adblock page.

**Screenshot(s)**

![Screenshot 2021-03-18 072153](https://user-images.githubusercontent.com/43067841/111559887-91390780-87bb-11eb-836f-936a29d78701.jpg)

**Versions**
    Browser/version: Firefox Version 86.0.1 (Official Build) (64-bit)
    uBlock Origin version: uBlock Origin v1.34

**Settings**
    Default lists with AdGuard Base and uBlock Annoyance

**Comment by okiehsch** [comment]
Already fixed update `uBO-filters`.

**Comment by What-Zit-Tooya** [comment]
@okiehsch anti-adb appear again.
new link if needed `https://megaup.net/1Cqju/New.Gods.Nezha.Reborn.2021.1080p.NF.WEB-DL.x264.6CH-Pahe.in.mkv`

**Comment by okiehsch** [comment]
Force update your filter lists and try again.

**Comment by What-Zit-Tooya** [comment]
> 
> 
> Force update your filter lists and try again.

Already did, + using default filter but UBO still detected. Its weird

**Comment by okiehsch** [comment]
> using default filter but UBO still detected.

I can't reproduce. I can reproduce if I use out of date filters, to be precise this two days olf commit fixes the issue for me.
https://github.com/uBlockOrigin/uAssets/commit/87f1a78f25a8f11726d0a855047ac2a7cb1562d1
