### ISSUE TITLE
Add ABP Japanese to badlists

### ISSUE THREAD

**Issue by Yuki2718** [uBlockOrigin/uAssets#8738]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

Many, e.g.
`https://www.youtube.com/`

### Describe the issue

Those who have installed uBO years ago still have the list and are experiencing various problems:
`https://twitter.com/root_T2/status/1353281297007874053`
`https://twitter.com/tameguro/status/1363152271471611909`

### Screenshot(s)

NA

### Versions

NA

### Settings

NA

### Notes

Apparently removing AdBlock Warning Removal List is also forgotten.

**Comment by uBlock-user** [comment]
@gorhill

**Comment by gorhill** [comment]
Are we talking about [this list](https://github.com/gorhill/uBlock/commit/e4f3559db1a7b9c0fd912d35d70f36b08b089599)?

I want to be sure I am badlisting the correct one.

**Comment by Yuki2718** [comment]
@gorhill Yes, that one.

**Comment by gorhill** [comment]
Whoever would still want to use the list despite the undue breakage it causes and despite being seemingly no longer maintainer can still import it by appending a dummy parameter at the end of the URL, like so:

    https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abpjf.txt?_

**Comment by krystian3w** [comment]
Or use CDN delivery similar added on newest uBO to help block content in India.
