### ISSUE TITLE
Unblocked Pop-up

### ISSUE THREAD

**Issue by elsy04** [uBlockOrigin/uAssets#874]
**### URL(s) where the issue occurs**

`http://www.identi.li
`

**### Describe the issue**

There are two instances of the same popup which shows up every now and then (according to cookies' state) right after doing a click anywhere on the site.

The destination address of the popup:

`http://www.navegacom.com/protect/redirect4.php
`

The cookies have a "BetterJsPop0" and "BetterJsPop1" names.

**### Screenshot(s)**

`https://i.imgur.com/lGyjh89.png
`

**### Versions**

Browser/version: [Firefox ESR v52.4.0 x64]
uBlock Origin version: [1.14.18]

**### Settings**

No changes but updating the default filters' list.

**### Notes**

I already tried with these filters (adapted from other of my requests):

```
identi.li##script:inject(abort-current-inline-script.js, parseInt, tabunder)
identi.li##script:inject(popads-dummy.js)
```

And although they stop the pop-up appearance, the clickable bullet points at the right side of the titles lose their function.

Thanks.

**Comment by mapx-** [comment]
try
`identi.li##script:inject(abort-on-property-read.js, BetterJsPop)`

> the clickable bullet points at the right side of the titles lose their function

What should that function do?

**Comment by elsy04** [comment]
Thanks, but it has the very same effect as when using the filters I tried before. All the titles have a tiny button, which once pressed, unfold a little comment and after a while close themselves if the mouse is not over them.

**Comment by elsy04** [comment]
Thanks, but it has the very same effect as when using the filters I tried before. All the titles have a tiny button, which once pressed, unfold a little comment and after a while close themselves if the mouse is not over them.

**Comment by okiehsch** [comment]
````
||identi.li/cacho/license*.js$script,first-party
````
works for me with Firefox , with Chrome the button works only after I reload the site once, best I can do.
You have to remove 
````
identi.li##script:inject(abort-current-inline-script.js, parseInt, tabunder)
identi.li##script:inject(abort-on-property-read.js, BetterJsPop)
identi.li##script:inject(popads-dummy.js)
````

**Comment by mapx-** [comment]
working too
`||identi.li/cacho/` and yes, nothing better to do for that button

**Comment by okiehsch** [comment]
`||identi.li/cacho/` breaks the button and other functionality, for example
the Jdownloader-link at `http://www.identi.li/index.php?topic=493845`

**Comment by elsy04** [comment]
I tried okiehsch's proposed filter and it does work perfectly.

I tried it with SRWare Iron latest version as well and uBlock 1.14.2, and it didn't worked; but after I updated uBlock to 1.14.20, it works as fine as with Firefox, without having to reload even once.

Thanks to both of you. 👍

**Comment by elsy04** [comment]
Since some days ago, the clickable bullet points at the right side of the titles can't be clicked anymore. Maybe they did some little change to the script, which produced that situation?

**Comment by mapx-** [comment]
I tried even disabling uBo (in chrome) I see no differences. Could you test without uBo enabled ?

**Comment by elsy04** [comment]
Using SRWare Iron v63.0.3300 with uBlock enabled or disabled, the bullets keep working, but a pop-up will open up every now and then (according to cookies' state) after doing a click anywhere in the screen. The pop-up points to:

`http://kazagames.com/c#http://larosquilla.com/RANDOM/
`

**Comment by elsy04** [comment]
I finally found out why the above problem started occurring again: a third-party filter's update.

**||identi.li/cacho/$script**

Somebody included that line in a recent "**EasyList Spanish**" filters' update , which paradoxically makes the problem I was already avoiding correctly with the similar filter proposed by @okiehsch, return.

**Comment by mapx-** [comment]
@elsy04  you can add:
`||identi.li/cacho/$script,badfilter`

**Comment by elsy04** [comment]
Effectively, that ",badfilter" addition to it made I don't have to disable the whole list.

Thanks. 👍
