### ISSUE TITLE
1001tracklists.com

### ISSUE THREAD

**Issue by Barticf** [uBlockOrigin/uAssets#8740]
`https://www.1001tracklists.com/edit/tracklist.php`

### Describe the issue
I can't save edited tracklist when "uBlock filters" list is active. When I disable it problem is gone. When I click to save button, site just go to right.

video sample
`https://streamable.com/nsqy0r`

### Versions

- Browser/version: Firefox / 86
- uBlock Origin version: 1.34

Edit: When I added to my static filters 
`1001tracklists.com#@#.messagePaneDiv`
`1001tracklists.com#@#.modal-backdrop`
problem gone

**Comment by okiehsch** [comment]
If you add
````
1001tracklists.com#@#.messagePaneDiv
1001tracklists.com#@#.modal-backdrop
`````
to your filter list the issue is solved?

**Comment by Barticf** [comment]
@okiehsch 
yes, I solved it before your post, but thanks :)

**Comment by okiehsch** [comment]
Update the `uBO-filters` list in a few minutes, should work as expected after that.

**Comment by uBlock-user** [comment]
Those filters fix the anti-adblock issue, did you add filters to address that now ?

**Comment by okiehsch** [comment]
I checked https://github.com/uBlockOrigin/uAssets/issues/8719 and I can't reproduce the anti adblock message after disabling those filters.

**Comment by uBlock-user** [comment]
Happens after a while of browsing, I can reproduce at `https://www.1001tracklists.com/tracklist/ucb7k8t/alex-nocera-one-dance-one-night-18-march-2021-03-18.html`

**Comment by uBlock-user** [comment]
```
1001tracklists.com##.in.fade.modal.messagePaneDiv
1001tracklists.com##.in.fade.modal-backdrop
```

Shouldn't break anything.

**Comment by okiehsch** [comment]
@Barticf can you check adding
````
1001tracklists.com##.in.fade.modal.messagePaneDiv
1001tracklists.com##.in.fade.modal-backdrop
````

**Comment by Barticf** [comment]
@okiehsch 
@uBlock-user not working with this https://github.com/uBlockOrigin/uAssets/issues/8740#issuecomment-802674063

**Comment by uBlock-user** [comment]
``` 
var jsbuffer = []; var ab = false; function domReady(fn){ document.addEventListener('DOMContentLoaded',fn);if(document.readyState==='interactive'||document.readyState==='complete'){ fn(); } } function adbChk() { return false; } 

```

inlineScript is the very first script, so scriptlets won't work.

**Comment by okiehsch** [comment]
I can reproduce, this will take a while to debug need to open a new session every time...

**Comment by uBlock-user** [comment]
If nothing else we can still fix it for FF. Disabled anti-adblock filters, so we can address later. Very tedious to reproduce.

**Comment by okiehsch** [comment]
`1001tracklists.com##+js(nostif, outdated)`
seems to work on my end.
@Barticf sorry to bother you again can you check to see if 
`1001tracklists.com##+js(nostif, outdated)`
causes your issue to reappear?

**Comment by Barticf** [comment]
@okiehsch only `1001tracklists.com##+js(nostif, outdated)` or with https://github.com/uBlockOrigin/uAssets/issues/8740#issuecomment-802660364 ? 
When it's only `1001tracklists.com##+js(nostif, outdated)` not working.

**Comment by okiehsch** [comment]
Both, add
````
1001tracklists.com#@#.messagePaneDiv
1001tracklists.com#@#.modal-backdrop
1001tracklists.com##+js(nostif, outdated)
````
to your filter list.

**Comment by uBlock-user** [comment]
`1001tracklists.com##div#adframe:style(display:block !important;height:1px !important;width:1px !important)`

For anti-adblock, try that too.

**Comment by Barticf** [comment]
@okiehsch it's working, but it causes a different error. I can't create tracklist, calendar not working. 
with `1001tracklists.com##+js(nostif, outdated)`
![Przechwytywanie](https://user-images.githubusercontent.com/32641928/111760690-4bee0600-889f-11eb-8546-9e53d9669d18.PNG)

without
![Przechwytywanie](https://user-images.githubusercontent.com/32641928/111760810-6fb14c00-889f-11eb-814f-4ed1eb8c8948.PNG)

**Comment by uBlock-user** [comment]
Will go with `1001tracklists.com##div#adframe:style(display:block !important;height:1px !important;width:1px !important)` then.

**Comment by okiehsch** [comment]
Ok, thx @Barticf if you update `uBO-filters` now it should work fine on your end.

**Comment by Barticf** [comment]
@uBlock-user 
`1001tracklists.com#@#.messagePaneDiv`
`1001tracklists.com#@#.modal-backdrop`
`1001tracklists.com##div#adframe:style(display:block !important;height:1px !important;width:1px !important)`

No problem with creating, editing tracklist. But last one not resolve problem with anti adblock info

**Comment by uBlock-user** [comment]
@Barticf I don't see anti-adblock after adding `1001tracklists.com##div#adframe:style(display:block !important;height:1px !important;width:1px !important)`

**Comment by Barticf** [comment]
@okiehsch `1001tracklists.com#@#body:style(overflow:auto !important)` this one can be add ? Without it, when I click save, site going to right. Like here `https://streamable.com/nsqy0r`

**Comment by uBlock-user** [comment]
made it less specific https://github.com/uBlockOrigin/uAssets/commit/730328c4d3636233bf947416026c3e3cbe3eafd5

**Comment by okiehsch** [comment]
A very annoying issue.....
![image](https://user-images.githubusercontent.com/16838044/111762278-2104b180-88a1-11eb-99dc-b0989e52ac43.png)

**Comment by Barticf** [comment]
@uBlock-user I see anti-adblock in Firefox incognito. I have 
`1001tracklists.com#@#.messagePaneDiv`
`1001tracklists.com#@#.modal-backdrop`
`1001tracklists.com###adframe:style(display:block !important;height:1px !important;width:1px !important)`
![Przechwytywanie](https://user-images.githubusercontent.com/32641928/111762042-d5520800-88a0-11eb-86f2-6debe1e75f61.PNG)

**Comment by uBlock-user** [comment]
Remove those filters and add these --

```
1001tracklists.com#@##adframe:style(display:block !important;height:1px !important;width:1px !important)
1001tracklists.com###adframe:style(display:block !important;height:100px !important;width:100px !important;left:-3000px !important;position:absolute !important)
```

Report back with feedback

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/111763457-74c3ca80-88a2-11eb-847e-73da02b5a41d.png)

**Comment by Barticf** [comment]
@uBlock-user without `1001tracklists.com#@#.messagePaneDiv`
`1001tracklists.com#@#.modal-backdrop`
I can't save tracklists.

**Comment by uBlock-user** [comment]
@Barticf force update uBlock Filters list please

**Comment by uBlock-user** [comment]
@okiehsch try `1001tracklists.com###adframe:remove()`

**Comment by Barticf** [comment]
@uBlock-user I still got AA info with `1001tracklists.com###adframe:remove()`

**Comment by okiehsch** [comment]
````
||cdn.intergi.com/hera/tyche.js$script,redirect-rule=noop.js,domain=1001tracklists.com
||cdn.intergi.com/hera/tyche.js$xhr,redirect-rule=noop.js,domain=1001tracklists.com
````
wworks on my end.

**Comment by okiehsch** [comment]
Well, it only works woth chromium because of the old issue with xhr-redirections using Firefox, I give up.

**Comment by uBlock-user** [comment]
@okiehsch will you try `1001tracklists.com##+js(ra, class, body[class="modal-open"][style^="padding-right", stay]` ?

**Comment by okiehsch** [comment]
That's not a valid filter, I will edit your post.

**Comment by uBlock-user** [comment]
Okay, will go with 

```
1001tracklists.com##^script:has-text(document.readyState)
||cdn.intergi.com/hera/tyche.js$script,xhr,redirect-rule=noop.js,domain=1001tracklists.com
```

**Comment by Barticf** [comment]
@uBlock-user 
![obraz](https://user-images.githubusercontent.com/32641928/111765667-f0267b80-88a4-11eb-8a6c-f56fe4084179.png)

**Comment by okiehsch** [comment]
````
||cdn.intergi.com/hera/tyche.js$script,redirect-rule=noop.js,domain=1001tracklists.com
||cdn.intergi.com/hera/tyche.js$xhr,redirect-rule=noop.js,domain=1001tracklists.com
````
and then Firefox specific
````
@@||cdn.intergi.com/hera/tyche.js$script,domain=1001tracklists.com
````
works for me using Firefox and chromium, no ads and there should be no breakage.

**Comment by uBlock-user** [comment]
`@@||cdn.intergi.com/hera/tyche.js$script,domain=1001tracklists.com` can just use that for both.

**Comment by okiehsch** [comment]
Well, it's not necessary for chromium but it's no big deal if you think we should allow it.

**Comment by Barticf** [comment]
@uBlock-user can you add `1001tracklists.com#@#body:style(overflow:auto !important)` to prevent website going to left like in this video `https://streamable.com/nsqy0r` ?
Same problem when you click Explore -> Genres etc.

**Comment by okiehsch** [comment]
That filter has already been removed just update the `uBO-filters` list one more time.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/111768414-3204f100-88a8-11eb-81ac-0a10664fae36.png)

https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/335590be520d3b99ced7027bdf7fad39f11504d9
