### ISSUE TITLE
pornhub.com [NSFW]

### ISSUE THREAD

**Issue by Neurotoxin001** [uBlockOrigin/uAssets#8741]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://www.pornhub.com/` and all sub-domains like `https://rt.pornhub.com/`

### Describe the issue
First for all we need make this rule https://github.com/uBlockOrigin/uAssets/commit/64d70a18930165064e0a86d56968ac601880ad95
`rt.pornhub.*##div[id^="customSkin"]` for all pornhub sub-domains, because not all russians using rt sub-domain. And these background ads appears on all sub-domains.

Second issue is in "upgrade to premium" button. For russian ip's it's "make a bet" - russian betting service ad.
`###headerUpgradePremiumBtn`
And this button appears on all sub-domains too.
 

### Screenshot(s)
https://i.imgur.com/pGW2PJA.png
https://i.imgur.com/1F1mxw9.png

### Versions

- Browser/version: Google Chrome 89.0.4389.90
- uBlock Origin version: 1.33.2

### Settings

My filters:
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
EasyPrivacy
uBlock filters – Annoyances
RUS: RU AdList
RU AdList: BitBlock + Fanboy's General
RU AdList: Counters

**Comment by okiehsch** [comment]
The second filter `###headerUpgradePremiumBtn` would block selfadvertisment on non russian pornhub sites, so that has been removed from EasyList.
If it is different for russian users it can be fixed in the regional russian list.
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/easylist/commit/60777a8a1c6d0aeb5369ee3cdec2994cadacf9d7

**Comment by okiehsch** [comment]
The first filter was later removed. 
https://github.com/easylist/easylist/commit/765f102f7c2d1f37e009cb7f3828c19f88dbfa68

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/ruadlist/commit/e2dc8e98d88f21c9ad51d619782d683ccb8105d2

**Comment by PIZZV** [comment]
ads

**Comment by PIZZV** [comment]
Could someone attempt to encounter and address ads?
