### ISSUE TITLE
https://www.cyclingnews.com/ comments are blocked again

### ISSUE THREAD

**Issue by whdmike** [uBlockOrigin/uAssets#8743]
`https://www.cyclingnews.com/` 
comments are blocked again 

Script is blocking qisqus.com

### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

-

**Comment by mapx-** [comment]
add
```
@@||quantcast.mgr.consensu.org/choice/*/choice.js$script,domain=cyclingnews.com
@@||googletagmanager.com/gtm.js$script,domain=cyclingnews.com
```

**Comment by whdmike** [comment]
Thank you. But where to add.

**Comment by mapx-** [comment]
(in "my filters") but now is fixed in the official lists so just update all your lists
