### ISSUE TITLE
healthline.com annoyance

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#8746]

**Comment by mapx-** [comment]
add the info requested, screenshot with whatever annoyance.

**Comment by IThinkIAmCool** [comment]
Browser: Google Chrome
uBO version: 1.33.2
![Screenshot_122](https://user-images.githubusercontent.com/80760045/111871360-31488980-8992-11eb-9f61-96b75ae1a436.png) (I hope I cropped it well)
I have the base/default filter lists + 'uBlock filters -- Annoyances' & Fanboy's Annoyance.

**Comment by IThinkIAmCool** [comment]
I got the annoyance in an incognito window/tab.

**Comment by uBlock-user** [comment]
GDPR ?

**Comment by wout-codes** [comment]
Fixed in `AdGuard Annoyances`.

**Comment by IThinkIAmCool** [comment]
> GDPR ?

I'm not sure what to say.

**Comment by uBlock-user** [comment]
Looks like GDPR and we don't fix GDPR notices.
