### ISSUE TITLE
'uBlock filters -- Annoyances' breaks the Facebook comment section of a website

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#8748]
If you go on `https://www.stiripesurse.ro/marian-godina-uime--te-se-pricepe-si-la-medicina---cum-o-ironizeaza-pe-doctorita-flavia-grosan_1700815.html` for example you can see that if you have 'uBlock filters -- Annoyances' enabled, the comment section looks weird.

**Comment by mapx-** [comment]
it looks ok

![image](https://user-images.githubusercontent.com/10303732/111873571-27725680-8991-11eb-9631-0277a1be8704.png)

**Comment by uBlock-user** [comment]
I see nothing weird, which filter from uBlock Filters -- Annoyances ?

**Comment by IThinkIAmCool** [comment]
I'm also unable to reproduce it. It may have been due to a filter of mine.

**Comment by uBlock-user** [comment]
Always test on default filterlists when you report.
