### ISSUE TITLE
ads on https://www.csid.ro/dictionar-medical/ratie-alimentara-11327902/

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#8756]
Does anybody know an active Romanian ad filter list?

**Comment by mapx-** [comment]
the one where you already reported using "n" users
https://github.com/tcptomato/ROad-Block

**Comment by IThinkIAmCool** [comment]
Isn't it inactive?

**Comment by mapx-** [comment]
This issue will be fixed directly here => yavli ads

**Comment by IThinkIAmCool** [comment]
@ryanbr Could you add the domain?

**Comment by LikesHisComputer** [comment]
@mapx- could you check for obsolete filter(s) against Yavli ads on .ro sites specifically?

**Comment by mapx-** [comment]
provide the specific pages

**Comment by LikesHisComputer** [comment]
@mapx- `prosport.ro` => present in `Acceptable Ads`. 
Also, the filter(s) enabled-by-default in uBlock Origin may be be breaking something on it.

**Comment by LikesHisComputer** [comment]
Did you not find any obsolete filters?

**Comment by mapx-** [comment]
I'll keep the filters for a while. For example `raziculacrimi` still using yavli crap but not very seriously (using a third party script but the domain seems to be dead)

**Comment by Branzeturi** [comment]
@mapx- 

`https://www.cancan.ro/` => third-party `stats-dev.brid.tv` connections

**Comment by sugarfreesweetener** [comment]
@mapx- https://github.com/AdguardTeam/AdguardFilters/issues/130025 

`https://www.phoenixnewtimes.com/news/katie-hobbs-wont-debate-kari-lake-in-arizona-governors-race-14441025`

scrolling down may be a requirement for encountering advertising
