### ISSUE TITLE
dood.to anti adblock (imbeded video player on a NSFW website)

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#8761]
It can be recreated on a <details><summary>**NSFW** website</summary> (porndish.com).</details>

How to recreate in a Private Window on Firefox:

 * open a video in another tab and wait for it to load (that is using doostream.com/dood.to)
 * go to the tab, play the video and skip a bit further
Note that you may encounter another video player.

**Comment by uBlock-user** [comment]
Be sure to test on default settings + all other extensions disabled.

**Comment by IThinkIAmCool** [comment]
![Screenshot_128](https://user-images.githubusercontent.com/81077706/111969878-5dcfe300-8b03-11eb-9ffa-1b32884fe1ab.png)

**Comment by IThinkIAmCool** [comment]
Doesn't Firefox have an ad blocker for Private windows?

**Comment by IThinkIAmCool** [comment]
I also have Fanboy's Annoyance enabled.

**Comment by IThinkIAmCool** [comment]
Refreshing the page makes the message disappear.

**Comment by uBlock-user** [comment]
page-link ?

**Comment by IThinkIAmCool** [comment]
It doesn't seem to be specific to a page (it has to be a a doodstream video though)

**Comment by IThinkIAmCool** [comment]
Without Fanboy's Annoyance it doesn't seem to occur anymore (the anti adblock)

**Comment by uBlock-user** [comment]
try at `https://dood.to/e/kdfcr2kbift3?subtitle_json=https%3A%2F%2Ffmovies.love%2Fajax%2Fepisode%2Fsubtitles%2Ffa6047274dc29f663e47a4211e17db81%3Fformat%3Dstreamtape&autostart=true`

**Comment by IThinkIAmCool** [comment]
> https://dood.to/e/kdfcr2kbift3?subtitle_json=https%3A%2F%2Ffmovies.love%2Fajax%2Fepisode%2Fsubtitles%2Ffa6047274dc29f663e47a4211e17db81%3Fformat%3Dstreamtape&autostart=true

It starts but it runs weird.

**Comment by IThinkIAmCool** [comment]
Have you tried reproducing the anti adblock in a Private Window in Firefox and by opening a video in a new tab (in the same Private Window), by going on the page only after it has loaded and then by playing the doodstream video and maybe skipping forward?

**Comment by uBlock-user** [comment]
If you have tracking protection enabled, disable that on Firefox.

**Comment by IThinkIAmCool** [comment]
That seems to have fixed the issue. Couldn't there be a way to defuse/remove the anti adblock with the tracking protection?

**Comment by uBlock-user** [comment]
I have tracking protecting set to strict and I still don't reproduce it.

**Comment by ghajini** [comment]
antiadblock saying `The publisher doesnt allow adblock, please disable and reload to continue watching!`

**URL**= 
NSFW 
`https://freeomovie.co.in/her-first-bbc-Watch-online-on-freeomovie/`

Opera browser/firefox stable

**Comment by mapx-** [comment]
no anti adb chrome / FF
