### ISSUE TITLE
www.cybermania.ws

### ISSUE THREAD

**Issue by HP-N550** [uBlockOrigin/uAssets#8762]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.cybermania.ws/`
`https://www.cybermania.ws/software/teracopy-3/`

### Describe the issue

Anti-adblock

### Versions

- Browser/version: [FF 86.0.1]
- uBlock Origin version: [1.34.0]

### Settings

Default
AdGuard Annoyances
Fanboy’s Annoyance
uBlock filters – Annoyances

**Comment by HP-N550** [comment]
adblock detected again for this site @uBlock-user

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0b6e342c8e895f3eead7b8e9544df1df943b7f9b

**Comment by What-Zit-Tooya** [comment]
@uBlock-user adblock detected again
