### ISSUE TITLE
Anti Ad-Block => maisgasolina.com

### ISSUE THREAD

**Issue by StrawbarryVan** [uBlockOrigin/uAssets#8763]
- [ X ] This is not a support issue or a question

- [ X ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue

- [ X ] I tried to reproduce the issue when...
    - [ X ] uBlock Origin is the only extension
    - [ X ] uBlock Origin with default lists/settings
    - [ X ] using a new, unmodified browser profile

- [ X ] I am running the latest version of uBlock Origin (I think)

### URL(s) where the issue occurs

`https://www.maisgasolina.com`
`https://www.maisgasolina.com/lista-de-postos/faro/portimao/`

### Describe the issue

All content from the page is replaced by Anti Ad-Block images.

### Screenshot(s)

`https://i.ibb.co/zbkv68d/antiadblock.jpg`

### Versions

- Browser/version: Firefox v86.0.1 (but also tried Chrome, Brave, Opera, Avast, and Comodo - all have the same result)
- uBlock Origin version: v1.34,0

### Settings

No alteration. All stock.

### Notes

None.

**Comment by StrawbarryVan** [comment]
The links are not harmful, but apparently I don't know how to add "back ticks" to make links non-clickable :(

If anyone can teach me how, I'd appreciate it. And apologies for leaving the links like this.

**Comment by mapx-** [comment]
select the url then click "insert code", see bellow

![image](https://user-images.githubusercontent.com/10303732/111977377-f31ea780-8b02-11eb-816a-aaa50e9a595c.png)

**Comment by mapx-** [comment]
or use [Alt] + [96] for `

**Comment by mapx-** [comment]
However, it seems ok if you use the spanish list: `spa, por: AdGuard Spanish/Portuguese`

**Comment by uBlock-user** [comment]
fix is present in the regional list.

**Comment by StrawbarryVan** [comment]
First of all, thank you for the help. The fix you suggested (turn on spa/por language) did work on Firefox. However, this solution did NOT work with the other browsers I mentioned (Chromium based).

As a last ditch attempt, I tried turning on ALL filters for ALL languages, but nothing works. This website still blocks UBlock Origin on Chrome, Brave, etc.

Not sure if a closed issue can be reopened but if someone reads this, can you help, please?

**Comment by mapx-** [comment]
working fine for chrome too. Be sure you didn't enable some protection in chrome / brave

**Comment by StrawbarryVan** [comment]
That solved it for Brave, thanks! Most of the other browsers are working fine, too. The only exception now is Opera (doesn't work at all), and I'm still having issues with Google Chrome (worked temporarily, but then I refreshed the page and stopped working again).

I've tried closing and reopening, I've tried clear cache... not sure what else to try.

**Comment by uBlock-user** [comment]
> Opera

Disable its built-in adblocker too

**Comment by StrawbarryVan** [comment]
> > Opera
> 
> Disable its built-in adblocker too

That worked too. With all these browsers, I sometimes forget which have built-in adblockers and which don't.

Now, only Google Chrome left. Only thing I haven't tried is uninstalling it completely and reinstalling.

Anyway, thanks to both users who guided me along. Appreciate it.

**Comment by mapx-** [comment]
chrome => settings => privacy & security => try to switch on "no protection"

**Comment by mapx-** [comment]
maybe in chrome you should also allow pop-ups & redirects
chrome://settings/content/popups

**Comment by StrawbarryVan** [comment]
Thank you for giving me some options to try, but nothing else worked. I uninstalled Chrome twice (the first time also didn't clear everything for me), but on the second time I restarted the whole PC, and then it worked.

So, all seems well now. Thanks again.
