### ISSUE TITLE
shrinkzzy.link anti adb

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#8764]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://shrinkzzy.link/GHclP`

### Describe the issue

antiadblock

### Screenshot(s)

![IMG_20210322_155248](https://user-images.githubusercontent.com/20338483/111976015-30952c00-8b27-11eb-9d7b-6ccad68c9b0b.jpg)

### Versions

- Browser/version: firefox a.
- uBlock Origin version: 1.34

### Settings

 uBO's default settings
-

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/84580704/120026157-555fc100-bffa-11eb-96ed-231e03db9cde.png)
@ryanbr
