### ISSUE TITLE
[Anti adblock] https://dropgalaxy.in/fkqlb29nxfdk

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#8769]
### URL(s) where the issue occurs
`https://dropgalaxy.in/fkqlb29nxfdk`

### Describe the issue
The webpage detects adblock

### Screenshot(s)
![image](https://user-images.githubusercontent.com/80951522/112082228-fcfbe580-8baa-11eb-9161-e38b7dbe9859.png)

### Versions

- Browser/version: Chrome v89.xx
- uBlock Origin version: v1.34.0

### Settings
All default settings

**Comment by IThinkIAmCool** [comment]
Have you updated your filter lists?

**Comment by JobcenterTycoon** [comment]
Possible fix:
`@@||services.vlitag.com$script,domain=dropgalaxy.com`

**Comment by blazesprings** [comment]
Sorry @JobcenterTycoon I applied the above code but still I get the adblock screen+timer
![image](https://user-images.githubusercontent.com/80951522/112345668-3fc4d700-8ceb-11eb-80f6-d43b1afa785a.png)

**Comment by JobcenterTycoon** [comment]
Ok for Chrome this works:
`@@||services.vlitag.com$script,domain=dropgalaxy.com`
`@@||tag.vlitag.com$script,domain=dropgalaxy.com`

But the timer cant be bypassed

**Comment by uBlock-user** [comment]
anti-adb script --

```
$(window).load(function() {
    if (window.location.hostname == "dropgalaxy.com") {
        function ab2str(buf) {
            return String.fromCharCode.apply(null, new Uint8Array(buf))
        }
        function str2ab(str) {
            var buf = new ArrayBuffer(str.length * 2);
            var bufView = new Uint8Array(buf);
            for (var i = 0, strLen = str.length; i < strLen; i++) {
                bufView[i] = str.charCodeAt(i)
            }
            return buf
        }
        var headddhtml = document.head.innerHTML;
        var outhtml = document.documentElement.outerHTML;
        var viptags = '';
        viptags += '[rand=' + $("#rand").val() + ']';
        viptags += '[id=' + $("#fileid").val() + ']';
        viptags += '[dropgalaxyisbest=' + $("#dropgalaxyisbest").val() + ']';
        viptags += '[adblock_detected=' + $("#adblock_detected").val() + ']';
        viptags += '[downloadhash=' + $("#downloadhash").val() + ']';
        viptags += '[downloadhashad=' + $("#downloadhashad").val() + ']';
        var dd = $(outhtml).filter('.adsbygoogle').each(function(i, e) {
            viptags += e['outerHTML']
        });
        $(outhtml).filter('script').each(function(i, e) {
            var ccc = $(this).filter('script').attr("src");
            if (typeof ccc !== 'undefined') {
                if (ccc.indexOf('https://dropgalaxy.com/') == -1) {
                    viptags += '[scr=' + ccc + ']'
                }
            }
        });
        var bufff = str2ab(viptags);
        var unit = new Uint8Array(bufff);
        var unitstr = unit.toString();
        var unitstr = unitstr.replace(/2/g, "004");
        var unitstr = unitstr.replace(/3/g, "005");
        var unitstr = unitstr.replace(/7/g, "007");
        var unitstr = unitstr.replace(/,0,0,0/g, "");
        var randd = $("#rand").val();
        $.ajax({
            type: "POST",
            url: "https://tmp.dropgalaxy.in/gettoken.php",
            data: {
                rand: randd,
                msg: unitstr
            },
            success: function(result) {
                $("#xd").val(result)
            },
            error: function(result) {}
        })
    }
});
```

credits to @AdamWr for de-ofuscating it.

**Comment by avotoko** [comment]
It looks like some changes have been made to the site. 


### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://dropgalaxy.in/fkqlb29nxfdk`


### Describe the issue

The anti-adblock message appears and I cannot proceed.

### Screenshot(s)

![step-1](https://user-images.githubusercontent.com/53560467/117184464-be954f80-ae13-11eb-8bfe-0f5a69e38387.jpg)
[step 1] click [Free Download] button.

![step-2](https://user-images.githubusercontent.com/53560467/117184483-c2c16d00-ae13-11eb-83d7-919ed27aed4e.jpg)
[step 2] redirect message shown and redirected to google.

![step-3](https://user-images.githubusercontent.com/53560467/117184514-c6ed8a80-ae13-11eb-80ac-2827ad82b4a9.jpg)
[step 3] click [Techssting -] on google.

![step-4-ng](https://user-images.githubusercontent.com/53560467/117184542-cb19a800-ae13-11eb-8a92-c1e54865dc50.jpg)
[step 4] anti-adblock message appears and I cannot proceed.

### Versions

- Browser/version: Firefox 88.0.1
- uBlock Origin version: v1.35.2

### Settings


- JPN: AdGuard Japanese (default)

### Notes


filters to resolve the issue.
`@@||glogoowo.net/pfe/current/tag.min.js$xhr,redirect-rule=noopjs,domain=dropgalaxy.com
@@||cloudfront.net^$xhr,redirect-rule=noopjs,domain=techssting.com
techssting.com#@#.showads
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=techssting.com
@@||tpc.googlesyndication.com/simgad/*$image,domain=techssting.com
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl_$script,domain=techssting.com
`

**Comment by ghajini** [comment]
Antiadblock
`https://dropgalaxy.in/po8xcn2x2ztq`

firefox a

![IMG_20210516_221251](https://user-images.githubusercontent.com/20338483/118405185-2fe6c500-b694-11eb-9968-169aaea175f8.jpg)

**Comment by ghajini** [comment]
Adblock detected
`https://dropgalaxy.in/txroo6ka7egs`
![IMG_20210517_050755](https://user-images.githubusercontent.com/20338483/118416548-e5823a00-b6cd-11eb-9e8a-fdd54e1e8f89.jpg)

**Comment by JobcenterTycoon** [comment]
`@@||adservice.google.*/adsid/integrator.js$script,domain=dropgalaxy.*|techssting.com`
`@@||techssting.com^$ghide`

works for me

**Comment by Mennaruuk** [comment]
> 
> 
> `@@||adservice.google.*/adsid/integrator.js$script,domain=dropgalaxy.*|techssting.com`
> `@@||techssting.com^$ghide`
> 
> works for me

I tried this on both https://dropgalaxy.in/txroo6ka7egs and https://dropgalaxy.in/po8xcn2x2ztq, and adblock is gone.
![image](https://user-images.githubusercontent.com/52135169/130333442-d30c0269-f2d1-464e-b1bc-889fcd86f8b3.png)

**Comment by ghajini** [comment]
Adblock detection
`https://dropgalaxy.in/d9pk321i9crb`
from `https://financemonk.net/`

**Comment by avotoko** [comment]
On my end, I jumped from dropgalaxy.in to financemonk.net only once at first, but after that I always jump from dropgalaxy.in to dropgalaxy.com. dropgalaxy.com detects adblock.

![screenshot](https://user-images.githubusercontent.com/53560467/134270628-6d375910-b68a-4820-81c7-f3aa9f857ab8.jpg)

The site recently changed the way it detects adblock. The following filters work for me.
```
@@||services.vlitag.com^$script,domain=dropgalaxy.com
@@||tag.vlitag.com^$script,domain=dropgalaxy.com
@@||adsco.re^$script,xhr,domain=dropgalaxy.com
```

**Comment by avotoko** [comment]
The site behaves differently than yesterday. The filter I posted last time doesn't work. Seems to need further investigation.

**Comment by rickninja765** [comment]
> The site behaves differently than yesterday. The filter I posted last time doesn't work. Seems to need further investigation

Yeah Same happened with me.

**Comment by okiehsch** [comment]
I get redirected to `financemonk.net`.
Is it the same domain for everyone here?

**Comment by ghajini** [comment]
yes, antiadblock on that domain

**Comment by uBlock-user** [comment]
So they're swapping only domains ?

**Comment by okiehsch** [comment]
Yes, they used techsting for a while and now financemonk.
https://github.com/uBlockOrigin/uAssets/commit/85a8c2ae7b15fc97d7ee751c1d5b29a702177ae2

**Comment by JobcenterTycoon** [comment]
Ads on `techyneed.com`  coming from `tmp.dropgalaxy.in/advertisement` but blocking this will trigger anti adblock even with noopframe redirect
<details>
<img width="330" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/136104022-d4dfb8c2-7dc0-4d93-a98a-fa86efb538ff.PNG">
</details>

Working filter:

`techyneed.com##iframe`

**Comment by blazesprings** [comment]
**Check the link:** https://dropgalaxy.in/tmq142h4u0sk
**Category:** Anti-adblock
**Browser:** Chrome  96.xx
**Extension or program:** Ublock Origin 1.38.6
