### ISSUE TITLE
storypick.com

### ISSUE THREAD

**Issue by gotitbro** [uBlockOrigin/uAssets#877]
The comments section does not load on `http://www.storypick.com`. This seems to be due to EasyPrivacy but when EasyPrivacy is disabled Taboola ads are loaded along with the comments section.

**Error URL:** `http://www.storypick.com/prince-harry-meghan-markle-engaged/`

_**Note:** Using uBO 1.14.18 on Chrome 62 with the the default filters and settings._

**Comment by mapx-** [comment]
try
```
@@||cdn.taboola.com/libtrc/$script,domain=storypick.com
##.trc_rbox_container
```

**Comment by gorhill** [comment]
How about:

    ||cdn.taboola.com/libtrc/$script,redirect=noopjs,domain=storypick.com

**Comment by mapx-** [comment]
still no comments (fb plugin comments) at the bottom.
As I can see fb comments are somehow inside the taboola widget

**Comment by gorhill** [comment]
Ok I am unable to understand the issue reported here. I see no comments even without uBO. The only thing I saw broken was the infinite scroll down, which the redirect filter fixed.

**Comment by gotitbro** [comment]
@gorhill Sorry for the late reply. I meant the Facebook comments section does not load. This is with completely default settings on uBO.

**SS:** https://i.imgur.com/RO9mo7G.png (uBO enabled with default settings and filters)
**SS:** https://i.imgur.com/YTZRSUu.png (uBO disabled)

**Error URL:** `http://www.storypick.com/must-visit-places-mumbai/`

The above filter `||cdn.taboola.com/libtrc/$script,redirect=noopjs,domain=storypick.com` does not seem to work. 

@mapx- The filters work but looks like all the ads are loaded as well along with the comments section.

**Comment by mapx-** [comment]
Which ads ? screenshot ? I see no ad.

**Comment by gotitbro** [comment]
@mapx- I tested again, cleared the cookies and cache for the website. The comments section seems to load but the **Taboola** recommendations still appear even though they should be blocked by 
`127.0.0.1 taboola.com` in **_Peter Lowe’s list_**.

**SS:** https://i.imgur.com/1eNOerP.png (_Recommendations from Taboola_)
**Error URL:** `http://www.storypick.com/pet-calendar-shout-out/`

From what I can see these Taboola ads are loaded through `XHR` requests sent by `storypick.com`: https://i.imgur.com/dl0K5lq.png

I can block the Taboola ads by: 
`||storypick.com/cdn-cgi/pe/bag2?r[]=*.taboola.com`
OR
`||storypick.com^$xmlhttprequest`

But if the Taboola ads are blocked (as through the above filters) the comments section does not load.

**Comment by mapx-** [comment]
Did you add both filters I indicated above ?

**Comment by gotitbro** [comment]
@mapx- I did. The result seems to be the same, i.e., **Taboola** ads downloaded along with the comments section. If I try to block the Taboola ads (`XHR`) the comments section does not load.

While the ads are hidden when I add the filters:
```
@@||cdn.taboola.com/libtrc/$script,domain=storypick.com
##.trc_rbox_container
```
The ad images still load using bandwidth in the background. You can check by disabling cosmetic filtering.

**Comment by gotitbro** [comment]
@mapx- Looks like they have integrated the Facebook comments section into the Taboola widget. I think it will be better to block the Taboola ads by blocking the XHR rather than allowing the Taboola ads simply for the comments section.

**Comment by mapx-** [comment]
So, if you use correctly both filters you see no ads. In this case the site is using FB comments embedded in taboola crap.

**Comment by gotitbro** [comment]
@mapx- I see this when I add both filters: https://i.imgur.com/WZOJ1kt.png

A lot of ad images still download but are hidden. If I don't add the filters the **_Taboola_** ads/recommendations still load but aren't hidden. 

I think it will be nice if we can block the XHR request creating the Taboola ads:
`||storypick.com/cdn-cgi/pe/bag2?r[]=*.taboola.com`

The comments section won't load but at least the ads will be blocked.

**Comment by mapx-** [comment]
Taboola stuff is already blocked if you don't add the filters above.

**Comment by gotitbro** [comment]
@mapx- With default settings I see that the Taboola stuff still loads but is hidden. It is completely blocked if I block the XHR request.

Can you see if the Taboola ads are loaded by disabling cosmetic filtering on this page `http://www.storypick.com/pet-calendar-shout-out/` ?

**Comment by gotitbro** [comment]
@mapx- Okay, I have understood why the ads were infrequently showing for me. The website is loading resources via XHR through **_Cloudflare's Rocketloader_** (`/cdn-cgi/pe/bag2?`). 

While **EasyPrivacy** blocks the tracking requests that load via _Rocketloader_, the ad requests are getting through (https://i.imgur.com/NUumhmD.png). 

I have opened a relevant thread on the _EasyList forums_ 
https://forums.lanik.us/viewtopic.php?f=62&t=39457.

uBO should block these ad requests until **EasyList** fixes it. The _Rocketloader_ ad requests should be blocked by:
```
/cdn-cgi/pe/bag2?*taboola.com
/cdn-cgi/pe/bag2?*affinity.com
/cdn-cgi/pe/bag2?*adservice.google.com
/cdn-cgi/pe/bag2?*pagead2.googlesyndication.com
/cdn-cgi/pe/bag2?*criteo.com
```
