### ISSUE TITLE
RTE Player playing ads 

### ISSUE THREAD

**Issue by germaloney11** [uBlockOrigin/uAssets#8771]
### URL(s) where the issue occurs

```
https://www.rte.ie/player/series/claire-byrne-live/SI0000000325?epguid=IH000398316
https://www.rte.ie/player/movie/se%C3%A1n/144135208371
```

### Describe the issue

3 ad roll at the start of the video and through in segments.

### Screenshot(s)

https://i.imgur.com/jIH2Y5E.png

### Versions

- Browser/version: Google Chrome is up to date Version 89.0.4389.90 (Official Build) (64-bit)
- uBlock Origin version: 1.34.0

### Settings

Easylist, easyprivacy, online malicious url blocklist, adguard annoyances, easylist cookie, fanboys annoyance, peter lowers ad and tracking server list, easylist cookie list. enabled

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled.
