### ISSUE TITLE
https://lenta.ru

### ISSUE THREAD

**Issue by Vitalik93** [uBlockOrigin/uAssets#8772]
### URL(s) where the issue occurs

`https://lenta.ru/`

### Describe the issue

Yandex ads at the top of the site.

### Screenshot(s)

<a href="https://ibb.co/8Y6B740"><img src="https://i.ibb.co/6XgZWJm/Screenshot-2021-03-23.png" alt="Screenshot-2021-03-23" border="0"></a>

### Versions

- Browser/version: Firefox 87.0
- uBlock Origin version: uBlock 1.34.0

### Settings

Turned on 4 Adguard and 4 EasyList filters: Russian, English, Social and Annoyances.

**Comment by dimisa-RUAdList** [comment]
[Recommended uBO settings for runet](https://forum.ru-board.com/topic.cgi?forum=5&topic=50474&start=0&limit=1&m=3#1)
