### ISSUE TITLE
http://jetvis.ru

### ISSUE THREAD

**Issue by Vitalik93** [uBlockOrigin/uAssets#8774]
### URL(s) where the issue occurs

`http://jetvis.ru`

### Describe the issue

Social buttons at the top of the site.

### Screenshot(s)

<a href="https://ibb.co/pnfrvtK"><img src="https://i.ibb.co/b7sRgSv/Screenshot-2021-03-23-Jetvis-Studio.png" alt="Screenshot-2021-03-23-Jetvis-Studio" border="0" /></a>

### Versions

- Browser/version: Firefox 87.0
- uBlock Origin version: uBlock 1.34.0

### Settings

Enable these filters: uBlock filters, Block filters – Unbreak, uBlock filters – Annoyances, EasyList, RU AdList, Fanboy’s Annoyance, Fanboy’s Social, BitBlock, Counters.

**Comment by uBlock-user** [comment]
`jetvis.ru###soc`

**Comment by Vitalik93** [comment]
Можно в фильтры это правило добавить? Помогает...

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/2aeb75f4f8ccb9810ea992c81e739e5dafe8c1e4

**Comment by Vitalik93** [comment]
@dimisa-RUAdList Появился баннер (или остаток) на сайте - черный прямоугольник в правом нижнем углу.

![Снимок экрана 2022-03-19 033435](https://user-images.githubusercontent.com/34383288/159101704-c6a9f486-415f-44ce-9ee8-eccf58c56c29.png)

**Comment by dimisa-RUAdList** [comment]
Not reproduced.

**Comment by Vitalik93** [comment]
> Not reproduced.

Странно. Даже после обновления фильтров всё равно висит. В чем может быть причина?

**Comment by dimisa-RUAdList** [comment]
The discussion here is in English only.

Create a topic here: https://forums.lanik.us/viewforum.php?f=102

Here are the rules for how to do it: https://forums.lanik.us/viewtopic.php?t=24280

When the situation clears up, it will be possible to return with the solution to the github.
