### ISSUE TITLE
Steam store widgets are being blocked.

### ISSUE THREAD

**Issue by Saishy** [uBlockOrigin/uAssets#8776]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://kitsunegames.com/kitsunetails/`

### Describe the issue

The steam widget is being blocked.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/2012108/112241927-a7b2e900-8c29-11eb-8400-bdbc5d221166.png)

### Versions

- Browser/version: 86.0.1
- uBlock Origin version: 1.34.0

### Settings

Default

### Notes

store.steampowered.com/widget is being blocked.

**Comment by Enichan** [comment]
For the record, we have replaced the widgets at that URL with images as a temporary workaround. The issue can still be seen at https://kitsunegames.com/buy/kitsunetails/ where a Steam store widget is supposed to appear underneath the heading "Wishlist on Steam"

**Comment by okiehsch** [comment]
`@@||store.steampowered.com/widget/*$frame,3p`
would fix the issue for you?

**Comment by okiehsch** [comment]
https://github.com/easylist/easylist/commit/890ca45b6f1c68a5a484e6936cd7d335571a8425

`EasyList` has removed the filter causing the breakage.
