### ISSUE TITLE
Adding ClearURLs rules as filter list

### ISSUE THREAD

**Issue by cantunborn** [uBlockOrigin/uAssets#8778]
The extension [ClearURLs](https://chrome.google.com/webstore/detail/clearurls/lckanjgmijmafbedllaakclkaicjfmnk?hl=en) was removed from the chrome webstore today. ([r/privacytoolsIO post](https://www.reddit.com/r/privacytoolsIO/comments/mbwr4j/clearurls_removed_from_chrome_webstore/))

Is there any possibility of adding the ClearURLs rules as `$removeparam` filters in the form of a separate filter list?

[Relevant AdguardFilters thread 1](https://github.com/AdguardTeam/FiltersRegistry/issues/448).
[Relevant AdguardFilters thread 2](https://github.com/AdguardTeam/FiltersRegistry/issues/401).

[Pre-existing filter list](https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt).

**Comment by uBlock-user** [comment]
@gorhill

**Comment by gorhill** [comment]
I consider this feature creep, this is best handled by a specialized extension, and specifically I do not want URL rewriting in uBO, removing URL parameter from outgoing network requests is as far as uBO will go, and this ability is already available through the `removeparam` option.

**Comment by cantunborn** [comment]
Obviously I am not talking about complete feature parity with ClearURLs. The `$removeparam` option can be used, but its not always easy to figure out which parameters are being used for tracking.

I guess my question was whether the parameters could be maintained through an official filter list by current filter list maintainers. Tracking parameters can be considered a privacy issue, a list that removes them can help increase privacy.

**Comment by gorhill** [comment]
> a list that removes them can help increase privacy.

Sure, but then that is a filter list issue -- whoever is welcome to create such list and if it ends up being well maintained and has a long enough history, I will consider adding it in the stock lists.

**Comment by cantunborn** [comment]
The only one I have currently come across is maintained by DandelionSprout [here](https://github.com/DandelionSprout/adfilt/blob/master/LegitimateURLShortener.txt). Maybe it can be evaluated for uBO.

**Comment by gorhill** [comment]
I have been tempted to add it, but two points:

- From it's namesake, _"Legitimate URL Shortener_ , the primary purpose is to shorten URL, not to reduce privacy exposure. It would be weird to put such list under _Privacy_ section
- I wouldn't want to add it without asking permission @DandelionSprout, as this could add burden on him through more opened issues
- I have no idea how much breakage to expect if the list was enabled by default, this is something to evaluate

**Comment by DandelionSprout** [comment]
I hereby give my permission to add my list to uBO. Worth noting is that it is an anti-annoyances list by heart, and I normally consider it to be merely one component of https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList.

I would be able to handle user support in the short term, but URL Shortener is in dire need of beta testing so that I'll get to know that the list works anywhere close to expected. I am currently only aware of minor issues in Google Search's image tab, so who knows what kind of other breakages people dig up.

**Comment by gorhill** [comment]
Another thing is that such list would benefit from being able to be maintained in a repo with multiple volunteers with commit rights, just like uBO's own lists are -- as soon as an issue is reported, having many volunteers able to fix it make it more likely that it would be solved quickly.

**Comment by DandelionSprout** [comment]
I have in the past (2019 - early 2020) considered spinning off a few of my lists into a separate repo where additional members would be added; however, all my top picks for potential team members rejected my offer.

**Comment by Yuki2718** [comment]
> * I have no idea how much breakage to expect if the list was enabled by default, this is something to evaluate

Not sure about the list but if all parameters in ClearURLs are blindly added I'd say many. I had been used the extension with my own custom whitelist but finally removed for the amount of trouble it caused. AdGuard has similar feature called stealth mode, and despite it's disabled by default and removes relatively limited parameters there're already tremendous troubles fixed.
