### ISSUE TITLE
cookuve.com adblock detector

### ISSUE THREAD

**Issue by ikhoeyZX** [uBlockOrigin/uAssets#8779]
### URL(s) where the issue occurs
[NSFW] `https://cookuve.com/nGekqKe`

### Describe the issue
can't click continue, continue button replaced by "please disable your adblock"

### Screenshot(s)
![Screenshot_20210325-030349](https://user-images.githubusercontent.com/79812109/112369114-cf33af80-8d16-11eb-90e6-4b92ec1d9e1b.png)

### Versions

- Browser/version: firefox mobile 68.11
- uBlock Origin version: 1.34.0

### Settings

-. cookuve.com##+js(aopr, app_vars.force_disable_adblock)

### Notes
add setting to that also not working

**Comment by uBlock-user** [comment]
forece update uBlock Filters list.
