### ISSUE TITLE
Videos not loading on Forbes

### ISSUE THREAD

**Issue by thrwat** [uBlockOrigin/uAssets#878]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://www.forbes.com

### Describe the issue

Video's on Forbes is not loading. 

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Chrome, latest
- uBlock Origin version: latest

### Settings

- Default

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by mapx-** [comment]
test these filters
```
||adservex.media.net/videoAds.js$script,redirect=noopjs,domain=forbes.com
forbes.com##fbs-ad
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=forbes.com
```
