### ISSUE TITLE
imgur.com

### ISSUE THREAD

**Issue by Vitalik93** [uBlockOrigin/uAssets#8780]
### URL(s) where the issue occurs

`https://imgur.com/`

### Describe the issue

2 ads at this site - "imgur emerald" and privacy notification.

### Screenshot(s)

<a href="https://ibb.co/mSJyXYn"><img src="https://i.ibb.co/4JWSYDb/Screenshot-2021-03-24-Imgur-1.png" alt="Screenshot-2021-03-24-Imgur-1" border="0"></a>
<a href="https://ibb.co/dfSdh5X"><img src="https://i.ibb.co/Fh9SPDc/Screenshot-2021-03-24-Imgur.png" alt="Screenshot-2021-03-24-Imgur" border="0"></a>

### Versions

- Browser/version: Firefox 87.0
- uBlock Origin version: uBlock 1.34.0

### Settings

Enabled filters: all uBlock filters, EasyList, Ru Adlist, RU AdList: BitBlock + Fanboy's General, RU AdList: Counters

**Comment by uBlock-user** [comment]
> ads at this site - "imgur emerald"

self promos, not blocked in default lists, you can reports to Annoyances see if they want to block

> privacy notification.

we don't block GDPR consents either.
