### ISSUE TITLE
go.menjelajahi.com

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#8781]
`https://go.menjelajahi.com/FcwHPdp`

anti adblock issue

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled.

**Comment by Dhanamerdeka** [comment]
on my side, the anti-adblock still appear. even when i already turned off all of my plugin.
idk why but the problem happen...
i really sure i already report this to add for anti adblock
but now it broke....
(maybe get patched?)

**Comment by uBlock-user** [comment]
are you on default settings ?

**Comment by Dhanamerdeka** [comment]
what you mean with default?
and also i sure that chrome didn't have any built in adblock
so i think nothing will trigger adblock except ublock itself

it's weired....
because i already report this sites like... yesterday if i not wrong...
and someone added it and on the morning the anti adblock not triggered
but on this night... when i go to that link... the anti adblock triggered....

i have no idea which things that i messed up

**Comment by dumbusernameidk** [comment]
default as in the filter lists that come pre-enabled after installing UBO.

**Comment by okiehsch** [comment]
Site works fine with an up to date default setup using chromium or firefox.
