### ISSUE TITLE
[Breakage] Tweakers.net - top-right menus for messages; notifications; and account settings broken for signed-in users

### ISSUE THREAD

**Issue by rjgotten** [uBlockOrigin/uAssets#8782]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://tweakers.net`
(only when signed in)

### Describe the issue

Signed in users on Tweakers.net have a set of options for managing private messages; notifications of reactions to postings; and general account settings. These are foldout menus that should open on a click. When the built-in "uBlock filters" filter list is active, these are broken.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/442808/112436562-21d89000-8d46-11eb-91a0-faf13389fffc.png)

### Versions

- Browser/version: Firefox 87.0
- uBlock Origin version: 1.34.0

### Settings

[ default ]

### Notes

Menus in question are initialized from a central 'behavior manager' class by executing:
```js
if(window.BehaviourManager)BehaviourManager.exec();
```
This seems to be part of a script element that is dynamically injected and contains a lot more minified logic:
![image](https://user-images.githubusercontent.com/442808/112437075-d672b180-8d46-11eb-8858-f5d5b4df1ecb.png)

When the "uBlock filters" built-in list is active, this element is not injected and the menus are broken.
Said element contains more site-related logic than just the initialization of the menus. Also contains JS logic to bootstrap some responsive rendering, among other things. So I expect other things to be broken as well.

If one edits the source of the script element in Firefox's dev tools, the original white-space and newlines of the script source are restored. This reveals that the set of manager classes that is being initialized at the top of the code are _not_ minified like the rest of the code is. I.e. these were intentionally added to the minified code later. Smells like a purposeful attempt to thwart ad-blockers  from preventing the injection of tracking code.

**Comment by mapx-** [comment]
does this work for you ?

`tweakers.net#@#^script:has-text(Inject=!)`

**Comment by JHBonarius** [comment]
That custom filter rule seems to solve it for me

**Comment by JHBonarius** [comment]
@mapx- I'm not the TS... just somebody with the same issue... I think you're quite fast with closing this
I don't even know what I did...

**Comment by mapx-** [comment]
I wanted just another confirmation (after my own test).

**Comment by JHBonarius** [comment]
@mapx- will this be fixed in uBlock, Or will I have to always add this rule for this site? Furthermore, I notices the desktop site has no issues. I only see this on Android 10 Firefox v86.1.1 uBlock v1.34.0

**Comment by mapx-** [comment]
see above => `closed this in b072f30` , it means it was fixed with that commit
