### ISSUE TITLE
Images not uploading to Disqus comments in forums

### ISSUE THREAD

**Issue by Peano56** [uBlockOrigin/uAssets#879]
### URL(s) where the issue occurs
https://pjmedia.com/instapundit/

### Describe the issue
Images fail to upload and embed in comments section.

### Screenshot(s)
Error message when trying to embed image in comment:
https://s2.postimg.org/j1flhp7g9/errormessage.jpg

### Versions
- Browser/version: [Pale Moon 27.6.2]
- uBlock Origin version: [1.13.8]

### Settings
When I disabled Ads > EasyList, problem was resolved. Images would upload as usual.

**Comment by okiehsch** [comment]
I can upload images without any issues. Tested with Chrome and Firefox.
![uins](https://user-images.githubusercontent.com/16838044/33576578-902072ac-d940-11e7-8ae0-154e84ae6c6e.PNG)

**Comment by Peano56** [comment]
> I can upload images without issue. Tested with Chrome and Firefox.

Do you have the filter Ads > EasyList active? When I untick that filter, images will upload properly. When I activate that filter, I get the error message.

**Comment by okiehsch** [comment]
Yes, I have `EasyList` enabled.

**Comment by gorhill** [comment]
@Peano56 use [the logger](https://github.com/gorhill/uBlock/wiki/The-logger), see if and what gets blocked when you try to upload.

**Comment by okiehsch** [comment]
Looking at what `EasyList` blocks at `https://pjmedia.com/instapundit/` in reagards to `Disqus`
you can try adding `@@||links.services.disqus.com^$xmlhttprequest,domain=pjmedia.com`,

**Comment by Peano56** [comment]
I just tried another image upload with EasyList active, and the upload ran fine. So I don't have any idea what is causing the problem. I guess I'll submit this to the Journal of Unrepeatable Experiments.

Thanks for your replies.
