### ISSUE TITLE
The "Vai de Visa" site freezes when Ublock is active

### ISSUE THREAD

**Issue by J41319** [uBlockOrigin/uAssets#8790]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

When accessing the "Vai de Visa" website with adblock enabled, the website freezes and the counter goes over 12k and the RAM memory increases absurdly. Then it is necessary to close the browser via the task manager since it freezes, I tested it on Chrome and the problem is similar, I don't know if it is something related to the site, the adblock or the rules.

### A specific URL where the issue occurs

`https://vaidevisa.visa.com.br/vdv/minha-conta/login`

### Steps to Reproduce

1. [First Step] - Access the website
2. [Second Step] - Navigate through the options and click on access my account
3. [and so on ...] After a few seconds the site will freeze and the memory will increase

### Expected behavior:

The website should function normally 

### Actual behavior: 

The site freezes

### Your environment

* uBlock Origin version: v1.34.0
* Browser Name and version: Firefox 64bit 87
* Operating System and version: Windows 10
* Rules: 
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
AdGuard Base
EasyList
AdGuard Tracking Protection
EasyPrivacy 
Online Malicious URL Blocklist
AdGuard Annoyances
EasyList Cookie
uBlock filters – Annoyances 
Dan Pollock’s hosts file
Peter Lowe’s Ad and tracking server list
spa, por: AdGuard Spanish/Portuguese

Issue: https://1drv.ms/u/s!AhHaljE4bL52gu1vtTlgIB09c4apgw?e=aCd4Df

**Comment by uBlock-user** [comment]
Can't reproduce, does we need to login ?

**Comment by uBlock-user** [comment]
Can't reproduce, do we need to login ?

**Comment by J41319** [comment]
> 
> 
> Can't reproduce, do we need to login ?

Yes, where can I send you my login, since the site has private information. I send it to you without problems, for testing.

**Comment by uBlock-user** [comment]
Add `@@||tags.tiqcdn.com/utag/visa/br-vdv/prod/utag.js^$script,domain=vaidevisa.visa.com.br` and try again

**Comment by J41319** [comment]
> 
> 
> Add `@@||tags.tiqcdn.com/utag/visa/br-vdv/prod/utag.js^$script,domain=vaidevisa.visa.com.br` and try again

After adding the rule in my filters, the site no longer freezes, I tested the site without the rule and with the rule, without the rule the site freezes, with the rule it works as it should. Feel free to end the problem.
