### ISSUE TITLE
"privacy"list causes errors with Twitter.

### ISSUE THREAD

**Issue by denholm-hsun** [uBlockOrigin/uAssets#8796]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

https://mobile.twitter.com/home

### Describe the issue

I use this filter list https://github.com/uBlockOrigin/uAssets/blob/master/filters/privacy.txt" in Vivaldi(android) built-in blocker, then there was an issue with not being able to browse Tweets properly.
When I replaced it with the original filter list, the problem disappeared.This issue only arises when this filter list is in use.

### Screenshot(s)

![PSX_20210327_151838](https://user-images.githubusercontent.com/81460927/112714070-7d0bad80-8f13-11eb-8816-2fbcde2b7b57.jpg)
![Screenshot_20210327_151615](https://user-images.githubusercontent.com/81460927/112714075-8563e880-8f13-11eb-8ba0-1bf9063a8e82.jpg)

### Versions

- Browser/version: [Vivaldi 3.7.2221.27]
- uBlock Origin version: [here]

### Settings

-

**Comment by uBlock-user** [comment]
Disable the built-in blocker and try again.

**Comment by denholm-hsun** [comment]
> Disable the built-in blocker and try again.
> 
> Don't use two blockers at once, see https://twitter.com/gorhill/status/1033706103782170625.

I now this works, but if it is better that some rules can be optimised so that I can use the blocker for Twitter.

**Comment by uBlock-user** [comment]
> if it is better that some rules can be optimised so that I can use the blocker for Twitter.

uBO's filterlists is NOT supposed to be used with any other blocker, it's for uBO only.
