### ISSUE TITLE
issue "bloomberg video content #8317 & #8568" was resolved but now is not working again

### ISSUE THREAD

**Issue by jahnson** [uBlockOrigin/uAssets#8799]
### URL(s) where the issue occurs

`https://www.bloomberg.com/news/videos/2021-03-26/green-hydrogen-race-video`

### Describe the issue

content does not play with uBlockOrigin enabled, plays when disabled 

### Versions

- Browser/version: 84.0.2
- uBlock Origin version: 1.34.0

Thank you in advance for your assistance

**Comment by ryanbr** [comment]
Fixed
