### ISSUE TITLE
golem.de video ad

### ISSUE THREAD

**Issue by alexara** [uBlockOrigin/uAssets#88]
### URL(s) where the issue occurs

`http://www.golem.de/news/formel-e-die-elektrorenner-bekommen-einen-futuristischen-frontfluegel-1607-122418.html`

### Describe the issue

Immediately after the video video starts, an ad (of  about 20 seconds) interrupts the movie.

### Screenshot(s)

![screenshot_golem_video_ad](https://cloud.githubusercontent.com/assets/13819719/17263301/9c8c6f9e-55e0-11e6-9cca-e44fac14e34c.png)

### Versions

- Browser/version: FF 47.0
- uBlock Origin version: 1.7.6

### Settings

- uBO's default setting 
- Peter Lowe’s Ad server list‎
-  DEU: EasyList Germany‎

- Purged all caches before and updated the filter lists
- No other addons installed 

### Notes

* This is the HTML part of the video ad, obviously it uses a random ID: 

![screenshot_golem](https://cloud.githubusercontent.com/assets/13819719/17263740/fb1a1bcc-55e2-11e6-8577-152ea4d1826e.png)

* When clicking on the advertisement,

`http://servedby.flashtalking.com/click/2/65693;1987309;1492091;211;0/?random=1509745315&ft_width=640&ft_height=360&url=http://donnerstalk.zdf.de/`

 opens, which is blocked due to `||flashtalking.com^` found in `Peter Lowe’s Ad server list`

**Comment by alexara** [comment]
@gorhill  Thank you very much, your solution (still) works fine for the video found in the article from the opening post.

Unfortunately it doesn't seem to be a general solution as I encountered another video ad in a different article:

`http://www.golem.de/news/document-foundation-libreoffice-5-2-unterstuetzt-geheime-dokumente-1608-122499.html`

I cannot give you any additional information as all settings ( the configuration, the HTML part, requests and the source of the ad) are the same as before.

**Comment by gorhill** [comment]
I don't see any video ad in the embedded video.

**Comment by alexara** [comment]
> I don't see any video ad in the embedded video.

I just figured out, that you can trigger the ad **by clicking on the big "play"** button which overlays the video:
![golem_video_ad_2](https://cloud.githubusercontent.com/assets/13819719/17371228/669d3dba-599f-11e6-81e5-7523c9491226.png)

The **logger** tells us .... (is there a way to export the logger content to XML or something else?)

![golem_video_ad](https://cloud.githubusercontent.com/assets/13819719/17371073/ddd2f970-599e-11e6-9376-fc60d89b0e2f.png)

... that the e.g. the following **video ad** is played instead of the actual content:
`http://9c00ff199562b47364184db7e55a8c7f3a3ec2dd.2.damoh.golem.de/`

**Comment by gorhill** [comment]
Even with that button I do not get the ad.

Show me the output of the logger for everything which is not blocked/allowed/redirected -- enter `-- || ++ || <<' as filter expression. Specifically, I want to see if the following line exists:

    hd-main.js    <<    script    http://hgcorigin.svonm.com/hd-main.js?cache=...

The fix requires that the resource `hd-main.js` is being redirected to uBO's own local version.

**Comment by alexara** [comment]
> Even with that button I do not get the ad.

I made a tiny but important mistake: I obviously did not completely turn off  NoScript  this time and it blocked scripts from `svonm.com`.
This made it possible to load the ad despite uBO.

> I want to see if the following line exists:

It exists if NoScript is turned off, it doesn't if NoScript is turned on ...

I am very sorry for taking your and my own time!
