### ISSUE TITLE
YouTube end of video recommendations

### ISSUE THREAD

**Issue by LunarTwilight** [uBlockOrigin/uAssets#880]
### URL(s) where the issue occurs
`https://www.youtube.com/watch?v=v7wTWuaHG58`

### Describe the issue
With the Adguard Spyware Filters enabled, the end of video recommendations (somewhat) break

### Screenshot(s)
Before:
![image](https://user-images.githubusercontent.com/13520392/33531935-ba41055c-d840-11e7-9558-2af1e39c26a9.png)
After:
![image](https://user-images.githubusercontent.com/13520392/33531925-9ee9f5f2-d840-11e7-84ea-b8800c2c8af9.png)

### Versions
- Browser/version: Firefox 58.0b8
- uBlock Origin version: 1.14.20

### Settings
- Settings:
![image](https://user-images.githubusercontent.com/13520392/33531845-8596f916-d83f-11e7-8826-d6a7a496fa6a.png)
- 3rd party filters
![image](https://user-images.githubusercontent.com/13520392/33531868-dd58b680-d83f-11e7-913e-735498b9941b.png)
- My filters
![image](https://user-images.githubusercontent.com/13520392/33531870-ed865436-d83f-11e7-875f-433d933de19d.png)

### Notes
Tried `@@||youtube.com/api/stats/watchtime^$~script` and it seems to fix the issue. Also you don't have to watch the full video, you can just skip to a few seconds before it ends.

**Comment by okiehsch** [comment]
Well, if `@@||youtube.com/api/stats/watchtime^$~script` fixes your issue there is nothing more to add.
`Adguard Spyware Filters` is not part of uBO's default setup, so no filter will be added to one of uBO's filter lists.

**Comment by LunarTwilight** [comment]
> Adguard Spyware Filters is not part of uBO's default setup, so no filter will be added to one of uBO's filter lists.
Ah

**Comment by LunarTwilight** [comment]
@okiehsch could this be reopened? The fix I had stopped working.

**Comment by okiehsch** [comment]
I can't reproduce, so smebody else will have to come up with a fix.

**Comment by LunarTwilight** [comment]
Seems to only happen when playing the video fully now. Also having YouTube randomly pause when starting to play a video. Also I now have every filter but the ones under "Regions, languages" and "Annoyances" enabled.

**Comment by anewuser** [comment]
Report this to https://github.com/AdguardTeam/AdguardFilters/issues
