### ISSUE TITLE
skmedix.pl

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#8802]
`https://skmedix.pl/sklauncher/downloads`

---

loop loading download button due EasyPrivacy/Peter Lowe:

---

```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=skmedix.pl
@@||static.cloudflareinsights.com/beacon.min.js$domain=skmedix.pl
```

**Comment by mapx-** [comment]
test

```
@@||skmedix.pl^$ghide
skmedix.pl##.adsbygoogle:style(max-height: 1px !important;)
```

**Comment by krystian3w** [comment]
No works, I can't time to analyse why CSS no enough.

**Comment by mapx-** [comment]
meaning together other exception, I updated the filters above

**Comment by sugarfreesweetener** [comment]
![image](https://user-images.githubusercontent.com/113248817/191843545-d06c0e80-0294-4025-ab84-002bf361820b.png)

**Comment by Emalcat** [comment]
I'm still having problems with this site
![image](https://user-images.githubusercontent.com/88663610/213682160-83f45dad-20fc-42f9-8ee4-d3b358e6cb2e.png)

**Comment by seedoils** [comment]
again, seems to be cosmetic filtering-related

**Comment by FanOfRootBeer** [comment]
`https://skmedix.pl/downloads` => detection

**Comment by PottersGame** [comment]
![Snímka obrazovky 2023-12-17 192213](https://github.com/uBlockOrigin/uAssets/assets/69338453/94153828-57ed-41fa-8f7a-76d292f4dbd8)
Still does not work

**Comment by stephenhawk8054** [comment]
@Yuki2718 These work for me

```adb
@@||fundingchoicesmessages.google.com/i/*$script,domain=skmedix.pl
@@||googleads.g.doubleclick.net/pagead/html/*/zrt_lookup$subdocument,domain=skmedix.pl
@@||googleads.g.doubleclick.net/pagead/ads$subdocument,domain=skmedix.pl
@@||googlesyndication.com^$script,domain=skmedix.pl
```

However, the ads will appear because of

```adb
@@||tpc.googlesyndication.com/pagead/js/$domain=googleads.g.doubleclick.net
```

The filter above is quite broad. Should we still keep it? I know it's to solve a game site, but allowing it would cause ads in other sites.

**Comment by Yuki2718** [comment]
But only if you already allowed `doubleclick.net` and the rule is not only for one or two sites. I use cosmetic filters for such ads. It will probably be possible to create a redirect resource or somthing to solve this without the exception as I see these reward ads use the same codes, but that's beyond me.
