### ISSUE TITLE
[Question] About uMatrix for gorhill

### ISSUE THREAD

**Issue by levicki** [uBlockOrigin/uAssets#8806]
@gorhill 

Latest stable version of uMatrix is 1.40 from November 2019.
Latest development version of uMatrix is 1.41b6 from February 2020.

Given that both releases are now more than a year old I have two questions:

1. Is uMatrix still being maintained?
2. If it is, where to report issues which are not related to content blocking?

In particular, I would appreciate if there was an update that removed the now dead blocklists (all that lead to malwarebytes and also recipes for English websites seem to be broken now as well):

![image](https://user-images.githubusercontent.com/16415478/112802613-ad1d9280-9072-11eb-9e89-3dfb8d9a6448.png)

Perhaps it would be a good idea not to hardcode those lists in the extension resources, but to fetch a JSON file from GitHub so you can change the links to blocklists in GUI without having to update the extension itself?

I apologize for posting here, I don't use Twitter and Reddit and I have no other way to reach you given that both uMatrix and uMatrix-Issues repos are either read-only or archived.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uMatrix-issues/issues/291#issuecomment-694988696

**Comment by levicki** [comment]
Thanks for clarifying, I somehow missed that comment.

**Comment by sergeevabc** [comment]
> 1. Is uMatrix still being maintained?

Great question that is still relevant. And even if we already know the answer, it's hard to resist expressing gratitude, delight and hope for the resumption of development, because uMatrix is the lighter extension than uBlock that allows you to browse the web with almost no ads, thereby easing the burden of using vintage computers.
