### ISSUE TITLE
I can't open https://forums.overclockers.ru with ublock origin on

### ISSUE THREAD

**Issue by Githubaccountforrandomshit** [uBlockOrigin/uAssets#8808]
I have the latest version of Firefox and ublock origin but the `https://forums.overclockers.ru` won't let me load the forum if I have ublock origin on. It just shows blank page

**Comment by uBlock-user** [comment]
Add `forums.overclockers.ru#@#div[id^="yandex_ad"]`

**Comment by Githubaccountforrandomshit** [comment]
> 
> 
> Add `forums.overclockers.ru#@#div[id^="yandex_ad"]`

Thank you so much. The problem is solved.

**Comment by uBlock-user** [comment]
Reported to regional list maintainer
