### ISSUE TITLE
Avoiding the Cookie message showing on hardware.info

### ISSUE THREAD

**Issue by ryanbr** [uBlockOrigin/uAssets#881]
### URL(s) where the issue occurs
`https://nl.hardware.info/nieuws/54379/amd-bevestigt-raven-ridge-vega-11-en-stopzetting-productie-vega-referentiekaarten`

### Describe the issue

Wanting a uBo way to ignore the cookie file "cookiebar", so I can bypass in Cookiemonster. If you clear the cookies on the site manually, it will show a overlay when you refresh the site. Once you press the green button the site will insert "cookiebar" cookie name. Trying to figure a way to get around this.

### Versions

- Browser/version: Firefox Nightly
- uBlock Origin version: 1.14.20

### Settings

Just Easylist/Easprivacy/and various Fanboy subs.

### Notes

Looking at including uBo filters for sites we can't block normally in ABP into Cookiemonster.

**Comment by gorhill** [comment]
I don't think it's possible, the page to serve is picked server-side according to whether the cookie is set or not, it's not done through javascript. Injecting a `cookiebar` cookie in the header would be the only way I can think of which might work to avoid having a `cookiebar` set client side.

**Comment by uBlock-user** [comment]
It's a cookiewall.

**Comment by uBlock-user** [comment]
Set `cookiebar` to `1` to skip the cookiewall msg.

**Comment by userOperaFF** [comment]
https://www.i-dont-care-about-cookies.eu/, create cookie after ~5 seconds and refresh page.

**Comment by jspenguin2017** [comment]
Just set the cookie and reload the page, no need to mess with headers.

**Comment by DrIT2016** [comment]
@jspenguin2017: How do i use this fix from NanoAnnoyance.txt in uBlock?

**Comment by jspenguin2017** [comment]
You need to load Nano's extra resources using advanced settings.

**Comment by jspenguin2017** [comment]
For full filter incompatibility, see: https://github.com/NanoAdblocker/NanoCore/blob/master/Notes/FilterIncompatibility.MD

**Comment by DrIT2016** [comment]
i'm trying to find out how this works, but can not find much info on this.
Do i need to add "https://github.com/NanoAdblocker/NanoFilters/blob/master/NanoFilters/NanoResources.txt" to userResourcesLocation in advanced settings and then mentioned line "hardware.info##script:inject(nano-hardware-info.js)" in my filters?

**Comment by jspenguin2017** [comment]
That's right. 
It is pre-configured in Nano.

**Comment by jspenguin2017** [comment]
Actually, you need the raw version of it.

**Comment by DrIT2016** [comment]
Got it, used raw version "https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt" in userResourcesLocation (restart browser needed) and after that used raw version "https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoAnnoyance.txt" to add in 3rd party custom filters, now it's working, thanks!

Btw also useful to add some of your other filters (Base, Timer)?

**Comment by jspenguin2017** [comment]
If you want all Nano's filters why don't just go use Nano?

**Comment by DrIT2016** [comment]
Just switched to uBlock from ADB, but will keep an eye on it!

**Comment by DrIT2016** [comment]
Damn, just switched to uBlock, hoping with adguard and fanboy annoyance it would keep on bypassing all cookie walls. Disabled "i don't care about cookies" addon to test it, But after fixing hardware.info, now again another one which won't work (https://jouw.postnl.nl/#!/overzicht). Also the ADB filter from "i don't care about cookies" does not work correctly (blank page, like on hardware.info), so guess best way which takes the least time is to switch that addon back on, pitty :(

**Comment by jspenguin2017** [comment]
That one is really complicated, the flag is saved in a configuration JSON string in LocalStorage. Probably should just click on the button.

**Comment by jspenguin2017** [comment]
That one is pretty complicated, probably should just click on the button automatically. 
![image](https://user-images.githubusercontent.com/7283682/34446385-af298f20-ec97-11e7-9503-5256427b0e08.png)

**Comment by jspenguin2017** [comment]
```
jouw.postnl.nl##pnl-cookiebar
jouw.postnl.nl##.hide-scroll:style(overflow: initial !important;)
```

**Comment by DrIT2016** [comment]
Thanks. 
I read and experienced a lot (so much wiser on ublock possibilities now ;)) and added following to filter which also worked:
https://jouw.postnl.nl/widgets/cookie-widget

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2229
