### ISSUE TITLE
1337x.to new malware link

### ISSUE THREAD

**Issue by minhngoc25a** [uBlockOrigin/uAssets#8815]
![image](https://user-images.githubusercontent.com/33834488/112981594-a0d62a00-9185-11eb-94e8-d6b1c964ccb8.png)

1337x added a new button like that on every torrent information page. BitLord is malware, so it should be blocked from downloading and showing on the page.

If there were filters to block that button already, the button still shows while turning on uBlock origin.

**Comment by in4u** [comment]
The official mirrors are listed at `https://1337x.to/about` so the filter should perhaps be updated to include `x1337x.*` too like was done [here](https://github.com/uBlockOrigin/uAssets/issues/4225#issuecomment-447078244).
