### ISSUE TITLE
[Anti adblock] http://gestyy.com/

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#8818]
### URL(s) where the issue occurs
`http://gestyy.com/eyUh8Y`

### Describe the issue
The anti adblock message doesn't appear but the page does detect the UBlock and doesn't redirect.
But as soon as I disabled UB, the page redirected.

### Versions

- Browser/version: 89.xx
- uBlock Origin version: v1.34.0

### Settings

All default settings

**Comment by uBlock-user** [comment]
`http://gestyy.com/eyUh8Y` redirects me to `https://simcast.com/?s=PLF&d=viid.me&ref=`

**Comment by ghajini** [comment]
works ,no antiadblock
![image](https://user-images.githubusercontent.com/20338483/113106176-142c7a00-9220-11eb-8b1f-9d180cd67aff.png)

**Comment by Yuki2718** [comment]
On my end redirects to `https://shrinke.me/EjP1UwK`
