### ISSUE TITLE
discoveryplus.in anti-adblock and breakage

### ISSUE THREAD

**Issue by llacb47** [uBlockOrigin/uAssets#8823]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [] I tried to reproduce the issue when...
    - [] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.discoveryplus.in/videos/cry-wolfe/shopaholic?seasonId=2&type=EPISODE`

### Describe the issue

Anti-adblock and breakage

### Screenshot(s)

![image](https://user-images.githubusercontent.com/16567977/113238861-95632b80-9277-11eb-9cfe-9696e90c3ec9.png)
![image](https://user-images.githubusercontent.com/16567977/113239006-d0fdf580-9277-11eb-9c1b-7498d7b5881f.png)

### Versions

- Browser/version: Firefox 89.0a1
- uBlock Origin version: uBo 1.34.0

### Settings

N/A

### Notes

Use India proxy/VPN

`@@||discoveryplus.in/*/ads/banner_$xhr,1p` fixes anti-adblock
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=discoveryplus.in` fixes breakage

**Comment by llacb47** [comment]
I don't know if this happens on other discoveryplus country sites, and I don't have time to check right now... @DandelionSprout do you know?

**Comment by DandelionSprout** [comment]
On their Norwegian site, `||prod-adops-proxy.dnitv.net^$empty,domain=discoveryplus.*` seemed to fix a similar-looking problem I had 3 weeks ago, but I'm suspecting them of running considerably different scripts in each country.
