### ISSUE TITLE
anti adblock list

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#883]
### URL(s) where the issue occurs

http://viwright.com/7azK
http://babblecase.com/1R3E
http://adyou.me/0Aqs
http://yoalizer.com/1QWs
http://qe.pe/f69MBmb
http://onlinebee.in/VZcSigdvW
http://kializer.com/3AoC
http://dataurbia.com/BHG
http://pintient.com/27OK
https://coinlink.us/cSHI
http://adbull.me/3pg4
http://casualient.com/3ZI
http://tinyium.com/39mi
http://mmoity.com/1IRF
http://atomcurve.com/1SVd
http://skamason.com/8W6E
http://viahold.com/2rrc
http://microify.com/DZ7
http://srt.am/9SCLoi
http://riffhold.com/wUl
http://j.gs/2b0o
http://q.gs/5YDFw
http://picocurl.com/nYB
http://kaitect.com/21ZJ
http://coginator.com/lt7
http://quamiller.com/MYg
http://twineer.com/3nYx
http://bluenik.com/KGy

### Describe the issue

in all the links the anti adblock appears

### Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

### Settings

I use the configuration that comes already in ublock when one installs the Extension

### Notes

most are adfly clones

**Comment by okiehsch** [comment]
@gorhill seeing the increasing amount of adfly sites, maybe you should consider the idea of a generic solution for this issue, as [mentioned](https://github.com/reek/anti-adblock-killer/issues/3774#issuecomment-348536138) by @jspenguin2017

**Comment by gorhill** [comment]
I added the scriptlet: `adfly-defuser.js` -- no parameters for now.

**Comment by okiehsch** [comment]
Can't reproduce anti-adblock messages at `qe.pe` and `onlinebee.in`.

**Comment by jspenguin2017** [comment]
I have a couple more: 
```
http://adf.ly/1XHJoS
http://ay.gy/1kXaTE
http://atominik.com/TG2
http://rd1.gamecopyworld.click/OrPg
http://redir2.auto-login-xxx.com/14557011/sexart
http://sostieni.ilwebmaster21.com/15p
```

**Comment by okiehsch** [comment]
I will remove all obsolete `adf.ly` filters once Firefox users will have access to `adfly-defuser.js`.

**Comment by jspenguin2017** [comment]
The old filters don't work anyway, whats the point of keeping them? 
![image](https://user-images.githubusercontent.com/7283682/33584789-39867418-d91e-11e7-802a-70bc330dd9ed.png)

**Comment by jspenguin2017** [comment]
Does the old solution work for most of the sites or just `q.gs`? Those guys might get pretty motivated if it's fixed in uBO, we'd better have a plan B.

**Comment by okiehsch** [comment]
I had a quick glance  and`q.gs` is the only one that still works as far as I could see.

**Comment by xDarkARG** [comment]
here I found another one @okiehsch


http://yamechanic.com/2F0q
http://kibuilder.com/2YKw

If I find others I will report them

**Comment by xDarkARG** [comment]
here I found another one @mapx-

http://tinyical.com/UOw
http://kimechanic.com/1pV3
http://vializer.com/4CmZ

**Comment by xDarkARG** [comment]
update the filters of these @mapx-

http://qe.pe/f69MBmb

http://onlinebee.in/VZcSigdvW

**Comment by xDarkARG** [comment]
here I found another one @mapx-

http://zo.ee/6azD

**Comment by KiLL4FuNK** [comment]
@mapx- @okiehsch

http://threadsphere.bid/-20DKIM/5YDFv?rndad=3047765491-1520017491

**Comment by KiLL4FuNK** [comment]
@mapx- @okiehsch

`http://clearload.bid/-36715NGEV/G5HA?rndad=3047765491-1527165253`

**Comment by KiLL4FuNK** [comment]
anti adblock

`http://swiftviz.net/-12YGWK/3eu4?rndad=3203667098-1541524969`

**Comment by KiLL4FuNK** [comment]
anti adblock

`http://briskgram.net/-28386JVBD/zsm?rndad=3203662002-1544017105`

**Comment by KiLL4FuNK** [comment]
anti adblock

`http://baymaleti.net/-1EGZC/A15HV?rndad=3203664803-1545143455`

**Comment by KiLL4FuNK** [comment]
anti adblock

`http://cinebo.net/-1RJVT/Qe0iF?rndad=3203664803-1545918890`

**Comment by theinstantmatrix** [comment]
another one

`http://uclaut.net` `/-15347LIUN/1i?rndad=3267098940-1550314730`

**Comment by theinstantmatrix** [comment]
`http://gloyah.net/rweasy/-1TQUY/404181/http://optifine.net/adloadx?f=OptiFine_1.13.2_HD_U_E7.jar&x=1ce2&rndad=1199544563-1555448747`

**Comment by theinstantmatrix** [comment]
`http://larati.net/rweasy/-1PNZL/11374213/https://aristois.net/download?zip&bn=19100816171610&rndad=2601401c5008af25cb7e8049893eab2-1566069370`

from AdguardTeam/AdguardFilters#38768

**Comment by KiLL4FuNK** [comment]
`http://gusimp.net/-12EHIZ/DW8H?rndad=3203662711-1576815611`

**Comment by KiLL4FuNK** [comment]
`http://scuseami.net/-12DZCT/Dbdc?rndad=3203662711-1579645084`

**Comment by KiLL4FuNK** [comment]
`http://gatustox.net/-12ZVTR/DlCT?rndad=3203662435-1582321179`

**Comment by mapx-** [comment]
on my side it redirects to `https://tmearn.com/KA1Y5` which is working fine

**Comment by uBlock-user** [comment]
Redirection here is controlled by the server, so no fix for that.

**Comment by mapx-** [comment]
@KiLL4FuNK  does this work for you ?
`gatustox.net##+js(aopr, app_vars.force_disable_adblock)`

**Comment by lain566** [comment]
Redirection occurs by this filter, https://github.com/uBlockOrigin/uAssets/commit/69e0fae37e69d68128e9b5936a121278dcdca7da
maybe he just has to force an update

**Comment by mapx-** [comment]
right, @KiLL4FuNK just update uBO list

**Comment by KiLL4FuNK** [comment]
ready it works

**Comment by KiLL4FuNK** [comment]
`http://fiaharam.net/-12MARY/DusN?rndad=3203662435-1585616537`

**Comment by KiLL4FuNK** [comment]
`http://gdanstum.net/-12XFIE/EQ9v?rndad=3129675910-1594769054`

**Comment by KiLL4FuNK** [comment]
http://atharori.net/-12FWZU/Eh4M?rndad=3051752123-1600630123

**Comment by WaterIsH2O** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/106503
