### ISSUE TITLE
protocol.com

### ISSUE THREAD

**Issue by cantunborn** [uBlockOrigin/uAssets#8830]
### URL(s) where the issue occurs

```
https://www.protocol.com/mitchell-baker-mozilla
```

### Describe the issue

- Sponsored posts
- Newsletter popup, scroll down the article to trigger

### Versions

- Browser/version: Chrome 89.0.4389.90
- uBlock Origin version: 1.34.0

### Settings

- All uBO lists enabled except regional & Fanboy's Social.

### Notes

Proposed filters:
```
protocol.com##.tag-sponsored
protocol.com###form_out
protocol.com##body:style(overflow: auto !important)
```

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by krystian3w** [comment]
how fix broken scrolling for this site? by network filter or danger CSP blockade?

**Comment by uBlock-user** [comment]
https://github.com/easylist/easylist/commit/335d2ff64f3fbea535a5bc05b8dc5ff7ca6f4085

**Comment by cantunborn** [comment]
No fix for newsletter popup?

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/773dfac75c9a891ab515f60349eb9c4d66e12405
