### ISSUE TITLE
Maybe this rule is outdated

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#8835]
https://github.com/uBlockOrigin/uAssets/blob/7d3f34edcab3a3d9547cb456bb704be7b3415be5/filters/filters.txt#L14186

On line 14186 of the current list there is the following rule: kijk.nl##+js(set, canPlayAds, true)
This rule was made because of adblock detection.
But when I disabled this rule I didn't get a warning like "you are using an adblocker" or couldn't play videos anymore
So, in my opinion this rule is outdated.

I am using the following filterlist:
EasyList
EasyPrivacy
uBlock filters

Other details:
Windows 10 build 19042.867
Edge version: 89.0.774.63 (64 bits)

**Comment by stephenhawk8054** [comment]
There's an anti-adblock on Android version.

URL: `https://www.kijk.nl`

Click on any video links below (For example the `Undercover` video). There's an anti-adblock message appears on the player. This doesn't happen with PC version. You may need a VPN to Netherlands to access the video player.

![image](https://user-images.githubusercontent.com/66517106/140629565-6120c438-6125-4203-a42d-9fff6e131903.png)

Firefox Android 94.1.1, ublock 1.38.6 default settings.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a3d11f38f3e26a1dbe4dd62bde9761a3f993e39f
