### ISSUE TITLE
ah.nl doesn't detect an adblocker anymore

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#8836]
https://github.com/uBlockOrigin/uAssets/blob/eef6eac7aee084b0a9c0434f45f15bbc5744c197/filters/filters-2020.txt#L2795

On line 2795 of this list there is the following rule: @@||ah.nl^$ghide
This rule was made because of adblock detection.
But when I disabled this rule I didn't get a warning like "you are using an adblocker."
So, in my opinion this rule is outdated.

I am using the following filterlist:
EasyList
EasyPrivacy
uBlock filters

Other details:
Windows 10 build 19042.867
Edge version: 89.0.774.63 (64 bits)

**Comment by okiehsch** [comment]
I can still reproduce if I scroll down.
![image](https://user-images.githubusercontent.com/16838044/113387647-047e7400-938d-11eb-9a63-893343c26b01.png)
