### ISSUE TITLE
[QUESTION] uBlock Filters vs Adguard Base

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uAssets#8837]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### Describe the issue

 

Just a question about which filterlist is most preferred. How useful is it to use both uBlock Filter and Adguard Base along EasyList? Should I use only uBlock or Adguard, which one is more useful?

**Comment by uBlock-user** [comment]
Ask such questions at https://old.reddit.com/r/uBlockOrigin/
