### ISSUE TITLE
[Maybe Asking, Maybe Bug] https://eririo.club/

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#8838]
`https://eririo.club/1zCzZS`
adblock detector appear....

**Comment by uBlock-user** [comment]
fixes are already present in the filter list, test on default settings + all other extensions disabled and any built-in adblock in your browser.

**Comment by Dhanamerdeka** [comment]
ah thanks great...
ummm one question again
is this repo can request things like... auto click or something like bypass?
(i mean like that sites have "click here to continue")
can i request in here to make something like... automatically click that button... so the ads will skipped automatically?

(i hope you answer this, after that i will close the issue :) )

**Comment by okiehsch** [comment]
> automatically click that button... so the ads will skipped automatically?

No, that is considered out of scope and won't be fixed due to security concerns.

**Comment by Dhanamerdeka** [comment]
ahh i see
okay i got it
thanks
