### ISSUE TITLE
thevideo.me

### ISSUE THREAD

**Issue by mat41997** [uBlockOrigin/uAssets#884]
when player has stopped
![2017-12-05 21_16_21-https___thevideo us_embed-bois2mybu135-800x450 html](https://user-images.githubusercontent.com/5884000/33628630-ac019f3e-da01-11e7-854b-a016020b44ad.png)
`thevideo.me/embed-bois2mybu135-800x450.html`

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.128
chrome 62.0.3202.94

**Comment by mapx-** [comment]
`thevideo.me` redirects in my case to `thevideo.us`
