### ISSUE TITLE
https://terraria.fandom.com/

### ISSUE THREAD

**Issue by rmcin329** [uBlockOrigin/uAssets#8840]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
https://terraria.fandom.com/wiki/Terraria_Wiki
Just visit any random page after arriving at the wiki
### Describe the issue

A gamepedia pro ad appears in the upper right, and scrolls the page with you looking rather ugly

### Screenshot(s)

https://imgur.com/G76YmiL

### Versions

- Browser/version: Firefox 87.0 64 bit
- uBlock Origin version: 1.34.0

### Settings
currently using default settings
-

### Notes
Browse to any random page on the wiki after visiting the homepage to produce this issue. I have tried using the element picker to block the ad, this results in a large ugly blank column going down the page in the same place the ad was at.

**Comment by mapx-** [comment]
add
`terraria.fandom.com###siderail_terraria_gamepedia`

@ryanbr

**Comment by rmcin329** [comment]
Adding that as a "my filter" does get rid of the ad, but it still leaves a large blank column on the right side of the page, is it possible to get rid of that too?

**Comment by uBlock-user** [comment]
@rmcin329 Add `terraria.fandom.com###bodyContent:style(width:calc(100% - 20px) !important)`

**Comment by rmcin329** [comment]
That worked! Thank you

**Comment by uBlock-user** [comment]
updated to avoid flashing and resizing on some pages.

**Comment by rmcin329** [comment]
I was randomly browsing pages and ran across an ad on this page of the wiki https://terraria.fandom.com/wiki/Journey_Mode I can block it with the element picker, but thought it should be mentioned

**Comment by rmcin329** [comment]
I'm seeing the same ad on some other wikis i visit as well. I think its just a fandom ad in general of some kind. I can block it on a case by case basis with the element picker, but obviously that isn't fun to do for several pages/sites

**Comment by uBlock-user** [comment]
Then replace `terraria.fandom.com` with `fandom.com`

**Comment by krystian3w** [comment]
Maybe better add generic:

`###bodyContent ~ div[id^="siderail_"][id$="_gamepedia"]`

because Fandom eaten gamepadia.
