### ISSUE TITLE
[Anti-Adblock] sky.shiiyu.me

### ISSUE THREAD

**Issue by TheDGOfficial** [uBlockOrigin/uAssets#8841]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`sky.shiiyu.me`

### Describe the issue

 

Shows ad block detected text that instructs to disable the ad blocker and prevents entering the root site and sub-pages etc.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/24778409/113515007-81227580-957a-11eb-81e8-bc7865eddfb6.png)

### Versions

- Browser/version: Firefox Developer Edition 88.0b6 running on Ubuntu 20.10 with flags modified to allow HTTP/3, WebRender and TLS ECH with uBlock Origin and Privacy Pass (an extension that skips captcha pages, I get many of them since I'm using Cloudflare WARP frequently because of my country blocking even the pastebin.com).
- uBlock Origin version: 1.34.0

### Settings

- Tried with default settings, then after I got the ad block block page, I also selected the uBlock - Annoyances list that is not selected by default, but it does not fixed it so I'm reporting it.

### Notes

I did not change settings and when inspecting the block page I did not find anything useful (not a web guy, mostly a Java dev), but seems like the site first tries to load the normal page but after detecting the adblock it replaces the all HTML with the block page.

**Comment by TheDGOfficial** [comment]
Nevermind it was a typo of `sky.shiiyu.moe`, I accidentally wrote me all the time and I just realized it was wrong after creating the issue and disabling the adblocker temporarily to access the site. It showed a parked domain site or such with ads. Though I still think this is a valid issue? Can close otherwise.

**Comment by mapx-** [comment]
parked domain

**Comment by uBlock-user** [comment]
We have fixed some parked domains too in the list.

Anyways the fix -- `||sky.shiiyu.me/px.gif^$image,redirect-rule=1x1.gif,1p`
