### ISSUE TITLE
[Anti-Adblock] rules from former Nano Bitdefender list

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#8843]
Because the NanoBitDefender list is archived and isn't updated anymore 
I thought maybe some of their rules could be added to the uBlock Filter list. 
Here are some rules: 

||doubleclick.net/instream/ad_status.js$script,redirect=doubleclick.net/instream/ad_status.js
||stopadblock.org/adblocker-deaktivieren$subdocument
###adblockBanner
##.admania_adblock_detector
##.deadblocker-header-bar
/AdblockDetector/handler.min.js$script
/adblock_detection/*
/adblock-detector/*
/adblock-popup.
/ad-blocking-detector/*
/plugins/adblock-notify-by-bweb/*
/plugins/anti-block/*
/plugins/better-stop-adblock/*
/plugins/no-adblock/*
/plugins/ibd-block-adblocker/*$script,stylesheet
/wp-content/plugins/ad-block-defender/*$script
/wp-content/plugins/ad-blocking-advisor/*$script,stylesheet
/wp-content/plugins/deadblocker/*$script,stylesheet
/antipubblicita.js
/anti-ad-buster.js$script
/anti-block-modal.js$script
/blockadblock.js$script
/blockcake.js$script
/fuckadblock.js$script
/kill-adblock//js/function.js$script
/kill-adblock/js/function.js$script
/jquery.adblock.js|$script
/jquery.adblock-detector.js|$script
/jquery.antiadsblock.js|$script
/js/adbuddy.min.js$script
/js/bsa-script-doctype.js$script
/js/bsa-script-no-doctype.js$script
/wp-content/plugins/sorry-adblocker/js/sab.js$script
/wp-content/themes/rehub/js/adblock_notify.js$script
/blockBlock.jquery.js$script
/blockadblock.min.js$script
/fuckadblock.min.js$script
/js/an-detect.min.js$script
/wp-content/plugins/*/adblock-detector.min.js$script
/noadblock.jpg
@@/plugins/blockalyzer-adblock-counter/img/ads/$image
@@/plugins/blockalyzer-adblock-counter/js/advert.js$script
@@/plugins/ad-blocking-detector/assets/js/*$script
@@/plugins/noadblock-nice-message/assets/js/ads.js?$script,~third-party

Note: I don't no if those rules can cause sites to brake up, but these rules work fine for me.

### List Subscriptions you're using: EasyList, EasyPrivacy and Easylist Dutch and uBlock Filters

- OS/version: Windows 10 Home, 20H2, build 19042.867
- Browser/version: Edge, version 89.0.774.63 (Official build) (64-bits)
- Adblock Extension/version: uBlock Origin, version 1.34.0

**Comment by uBlock-user** [comment]
Anti-Adblock filters are added on a case-by-case basis and as per what the filter list maintainer thinks is right, not inherited from any third-party list.

**Comment by krystian3w** [comment]
Bitdefender created list for ublock origin?

**Comment by JohnyP36** [comment]
> Bitdefender created list for ublock origin?

I don't no, but I guest the answer is negative.

**Comment by okiehsch** [comment]
Show me the filter in that list that fixes an anti-adblock issue on a specific site and I will add it.
We don't add filters simply because they are part of some other list.

**Comment by uBlock-user** [comment]
There is NanoDefender list, but there's no Nano BitDefender list, google search reveals no results for that either.

**Comment by JohnyP36** [comment]
> Show me the filter in that list that fixes an anti-adblock issue on a specific site and I will add it.
> We don't add filters simply because they are part of some other list.

As far as I now those filters don't solve a issue on a specific site. 

It are general rules, that will fix anti-adblock in case of an adblocke would be detected and there is no specific rule.

**Comment by okiehsch** [comment]
> don't solve a issue on a specific site.
 general rules, that will fix anti-adblock in case of an adblocke would be detected and there is no specific rule.

I know, what I meant is show me one of those general rules that fixes an actual issue on "one site" and I will consider adding it.
