### ISSUE TITLE
Outdated anti-adblock rule

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#8845]
The following rule is outdated:

! https://github.com/NanoMeow/QuickReports/issues/2667
knack.be##+js(nostif, Bait)

As far as I search this site I don't get along an adblock warning 
I use the following lists: uBlock Filter, EasyList, EasyPrivacy and EasyList Dutch.

I can't find in which list this rule is (in the filters 2020.txt or another one)

**Comment by mapx-** [comment]
The check code is still there (but lastly were removed lots of baits so the script does not kick in). Let's keep the filter.
