### ISSUE TITLE
Struggling to remove affiliate links that use obfuscation

### ISSUE THREAD

**Issue by chrissnell** [uBlockOrigin/uAssets#8848]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://thumpertalk.com/forums/topic/1366781-beware-fuel-tank-floatys/`

### Describe the issue

This is one of many forums using an annoying affiliate link insertion script.  When the script detects certain words (in this page, for example, `tank`, `ktm`, `gas gas`), it adds a `<a>` tag, making the posts hard to read.  It looks like this:

![2021-04-06-02_164x88](https://user-images.githubusercontent.com/54363132/113661085-74ce1380-9673-11eb-81fc-c517edb6eae3.png)

The links have random IDs that start with `ips_uid`.  There is a pseudo-element called `a[data-autoLink]::after` that I've tried filtering for, to no effect.

Here's what I want to do:

- Remove the "page opens in new window" icon next to the next (`content` in the `a[data-autoLink]::after` rule)
- Remove the `<a>` tag but **leaving the content of the `<a>` tag** so that the page is still readable

 

### Screenshot(s)

![2021-04-06-46_2124x522](https://user-images.githubusercontent.com/54363132/113661236-b6f75500-9673-11eb-992f-1da3825d29db.png)

### Versions

- Browser/version: Firefox Nightly 88.0a1 (2021-03-01)
- uBlock Origin version: v1.34.0

### Settings

- Using default settings 

### Notes

- I've tried removing the `content` attribute of the  `a[data-autoLink]::after`  with remove-attr.js but not having any luck.

**Comment by chrissnell** [comment]
Here's one of the rules I tried:

```##+js(ra.js, a[data-autoLink]::after, content)```

This doesn't work.  Does ra.js work on pseudo-elements?

**Comment by okiehsch** [comment]
How about
`thumpertalk.com##+js(ra, href|target, a[href^="https://thumpertalk.com/link/click/"][target="_blank"], stay)`

**Comment by uBlock-user** [comment]
`thumpertalk.com##+js(ra, href|target|data-ipshover-target|data-ipshover|data-autolink|rel, a[href^="https://thumpertalk.com/link/click/"][target="_blank"])` normalises the link so no more affiliate link distractions.

**Comment by okiehsch** [comment]
Yes, that's even better.

**Comment by uBlock-user** [comment]
You could further normalise it and remove the underline with `thumpertalk.com##.ipsType_richText a:style(text-decoration: none !important)`

**Comment by okiehsch** [comment]
That will also normalise "sign in now" at the bottom.

**Comment by uBlock-user** [comment]
Underline disappears, not seeing any other issue.

**Comment by okiehsch** [comment]
I think that is good enough to fix the issue. 
@chrissnell

**Comment by okiehsch** [comment]
> Underline disappears, not seeing any other issue.

That's what I meant it's now less obvious that "sign in now" is clickable.

**Comment by uBlock-user** [comment]
You could still add `thumpertalk.com##.ipsType_richText a:hover:style(color:currentcolor !important)`

**Comment by okiehsch** [comment]
That does not work, using chromium, on my end.

**Comment by uBlock-user** [comment]
It should, `:style` rules don't have any compatibility issues with browser vendors.

**Comment by uBlock-user** [comment]
How about `thumpertalk.com##a:hover:style(color:currentcolor !important)` ?

**Comment by okiehsch** [comment]
The hover part does not work on my end.
`thumpertalk.com##.ipsType_richText a:style(color:currentcolor !important)`
works.

**Comment by okiehsch** [comment]
The picker does not even indicate a hit with
`##.ipsType_richText a:hover:style(color:currentcolor !important)`

**Comment by uBlock-user** [comment]
`:hover` is only activated when you hover your mouse on the element

**Comment by okiehsch** [comment]
Well, yes but the color does not change if I add
`##.ipsType_richText a:hover:style(color:currentcolor !important)`
it does change if I add
`##.ipsType_richText a:style(color:currentcolor !important)`.

**Comment by uBlock-user** [comment]
> but the color does not change if I add
##.ipsType_richText a:hover:style(color:currentcolor !important)

An interesting conundrum, perhaps @gorhill knows better.

**Comment by krystian3w** [comment]
Bottom link possible don't touching by:

`##.ipsType_richText a:not([href]):style(color:currentcolor !important)`

or

`##.ipsComment.cPost .ipsType_richText a:style(color:currentcolor !important)`

---

Maybe page use mouseover fallback i `:hover` fail...

**Comment by chrissnell** [comment]
Thank you so much @okiehsch, @uBlock-user, and @krystian3w.  For what it's worth, I don't consider the "sign in now" link at the very bottom (if that's what y'all are talking about) to be insidious.  In fact, I think it's pretty good to have so that non-members can understand what they need to do in order to join the forum.

**Comment by chrissnell** [comment]
Oh, never mind.  Haven't had my coffee yet.  I see that you were trying to remove the underline decoration without breaking "sign in now".  Carry on.
