### ISSUE TITLE
vidlox.tv

### ISSUE THREAD

**Issue by mat41997** [uBlockOrigin/uAssets#885]
popup when video be played or stoped

![2017-12-05 21_31_44-https___vidlox tv_embed-zi6j41qoyx09 html](https://user-images.githubusercontent.com/5884000/33629291-c8ffb786-da03-11e7-9718-04ebecaac300.png)
`https://vidlox.tv/embed-zi6j41qoyx09.html`

![2017-12-05 21_31_55-newtabtv_ watch tv football tv shows stream tv free](https://user-images.githubusercontent.com/5884000/33629318-e22e1c7a-da03-11e7-8727-504526e7ef80.png)
`http://pl.newtabtv.com/lp16?type=media&pub_id=3288&srcid=9225325b-0778-4b3a-80bd-ad6f5b882333&sub_id=wIQVSRNG3LPDTS5A1B096NFQ`

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.20 & ubo-pe 12.128
chrome 62.0.3202.94

**Comment by KonoromiHimaries** [comment]
pops back
