### ISSUE TITLE
Couldn't play videos on bbc.com

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#8850]
### List the website(s) you're having issues: 
bbc.com

### What happens?
Because of the rule   ||fundingchoicesmessages.google.com^$3p   I can't see the popup where you can consent cookies and because this popup isn't show I can't watch videos.

### List Subscriptions you're using: EasyList, EasyPrivacy and EasyList Dutch + uBlock Filters

- OS/version:  latest version of Windows 10 Home
- Browser/version: Edge, 89.0.774.68 (Official build) (64-bits)
- Adblock Extension/version: uBlock, 1.34.0

**Comment by mapx-** [comment]
I've tested this video FF / chrome, no `fundingchoicesmessages` requests on my end

**Comment by uBlock-user** [comment]
`https://www.bbc.com/news/av/world-europe-56596351` works fine, no issue here.

**Comment by JohnyP36** [comment]
I saw what the problem was: I had a rule "+js(nowebrtc) and because of that the video wasn't loading.

**Comment by JohnyP36** [comment]
I checked out this site again 
The following things are blocked: 

||fundingchoicesmessages.google.com^$3p
*##.div-gpt-ad:style(width:1px!important;height:1px!important;min-height:1px!important;)
*##[class^="div-gpt-ad"]:style(width:1px!important;height:1px!important;min-height:1px!important)
*##div[class^="div-gpt-ad"]:style(width:1px!important;height:1px!important;min-height:1px!important)
#@#[class^="div-gpt-ad"]

After cleaning my browser history and deleting all cookies the problem occurs again. 
In my opinion because of the the blocking of fundingchoicesmessages.google.com bbc.com wouldn't load the cookies that are necessary for playing videos.

I use uBlock filters, EasyList and EasyPrivacy

**Comment by JohnyP36** [comment]
Here is a printscreen from the logger: 

![image](https://user-images.githubusercontent.com/81161435/113828428-a7b3fc80-9784-11eb-99db-280bc5bb2948.png)

**Comment by okiehsch** [comment]
I can reproduce, example link:
`https://www.bbc.com/news/av/world-asia-56608495`

**Comment by BPower0036** [comment]
Just to add. Because ||fundingchoicesmessages.google.com^$3p was blocked. The cookie consent didn't load and so you couldn't watch the videos
