### ISSUE TITLE
Rules for tweakers.net

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#8854]
In uBlock Filters there are 2 rules for tweakers.net : 
tweakers.net##+js(aost, setTimeout, /HTMLDocument.*inlineScript/)
@@||tweakers.net^$ghide

https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L141

As far as I can see I don't understand why those are necessary. I think you don't need them (or are outdated?)

I uses: uBlock Filters, EasyList and EasyPrivacy

**Comment by mapx-** [comment]
nasty ads

**Comment by uBlock-user** [comment]
Disable them and see what happens.

**Comment by JohnyP36** [comment]
I see nothing change.

**Comment by uBlock-user** [comment]
Ads get inserted after seconds...

**Comment by JohnyP36** [comment]
> Ads get inserted after seconds...

Those are blocked by the rules from EasyList and/or EasyPrivacy
##.AD-POST
##.adLoader
##.advertorial
/promotools/*

**Comment by uBlock-user** [comment]
No they're not, they detect adblock because of those rules and as a result, ads are reinserted see--

https://github.com/uBlockOrigin/uAssets/issues/8839#issuecomment-812539849
https://github.com/uBlockOrigin/uAssets/issues/8839#issuecomment-812540806

**Comment by JohnyP36** [comment]
Thank you for your time and explaining. You are right.

**Comment by gitthehubs** [comment]
It will block the ads from for example Coolblue. Ads will load after a few seconds.

See https://github.com/uBlockOrigin/uAssets/issues/8851 for pics. :)
