### ISSUE TITLE
zive.cz adblock warning message

### ISSUE THREAD

**Issue by tommy3093** [uBlockOrigin/uAssets#8857]
### URL(s) where the issue occurs

`https://www.zive.cz/clanky/tyka-se-vas-velky-unik-dat-facebooku-uz-si-to-muzete-snadno-overit/sc-3-a-209418/default.aspx`

### Describe the issue

When you click on any article from main page, it shows warning message to disable adblock.

### Screenshot(s)

![Untitled](https://user-images.githubusercontent.com/155648/113893780-9fc97c00-97c7-11eb-982a-9374278f7b7b.png)

### Versions

- Browser/version: Firefox 87.0
- uBlock Origin version: 1.34.0

### Settings

Default + added uBlock, AdGuard, Fanboy filter annoyances

**Comment by tommy3093** [comment]
Hi,

Thanks for quick provided fix. I have purged all caches, but I'm still getting the warning message.

**Comment by uBlock-user** [comment]
fixed in https://github.com/uBlockOrigin/uAssets/commit/a2bed09aefe110fc2182dda0db314279d2675327

**Comment by uBlock-user** [comment]
updated

**Comment by tommy3093** [comment]
still there

### Versions

- Browser/version: Firefox 88.0
- uBlock Origin version: 1.35.0
