### ISSUE TITLE
Several similar streaming Website Popups

### ISSUE THREAD

**Issue by RandyJackson59** [uBlockOrigin/uAssets#8858]
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

```
https://anicloud.io/
https://serien.vc/

https://burningseries.co/
bs.to
```

### Describe the issue

When you click anywhere, the site(s) try to open a popup or popunder. It only happens once every few minutes though, so it's not reproducable right away. Except when you delete your cache i guess.
These are partner sites or similar sites, if i need to make seperate threads for the sites i'm sorry, i will do that if you tell me to.

### Versions

- Browser/version: Firefox newest as of today
- uBlock Origin version: newest as of today

**Comment by mapx-** [comment]
I get no popup on
```
https://burningseries.co/
bs.to
```

**Comment by RandyJackson59** [comment]
> 
> 
> I get no popup on
> 
> ```
> https://burningseries.co/
> bs.to
> ```

Sorry popup is not the right word, it opens a new tab and closes it right away
it happens on anicloud.io and serien.vc for sure, but on the other two it doesn't seem to happen right now.. weird
on their alternative domains it happens though, like burningseries.vc or burningseries.ma
