### ISSUE TITLE
Ublock Origin is being bypassed/not working on multiup site

### ISSUE THREAD

**Issue by harrywon2022** [uBlockOrigin/uAssets#8859]
https://multiup.org/en/mirror/377e4f76912e837da7177a16c23236e0/ShadowOfWar_DLCs.rar

If you go and click download under 1fichier.com it redirects you to an ad page which completely bypasses ublock somehow.

Browser/version: Chrome v89.xx
uBlock Origin version: v1.34.0

Default filters (All up to date too).

**Comment by harrywon2022** [comment]
Browser/version: Chrome v89.xx
uBlock Origin version: v1.34.0

Default filters (All up to date too).

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/7897
