### ISSUE TITLE
igram.im anti-adblock

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#886]
URL(s) where the issue occurs

http://igram.im/jZKB

Describe the issue

anti-adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
update the filters of these @mapx-

**Comment by xDarkARG** [comment]
update the filters of these @mapx-

**Comment by KiLL4FuNK** [comment]
`http://igram.cc/jZKB ` @mapx-  Anti-Adblock

**Comment by KiLL4FuNK** [comment]
`http://igram.im/jZKB`
`http://igram.cc/jZKB`

the page died you can remove the filters
