### ISSUE TITLE
eschenker.dbschenker.com

### ISSUE THREAD

**Issue by strict-block** [uBlockOrigin/uAssets#8860]
`https://eschenker.dbschenker.com/app/launch-page/public`

cookie pop-up to analyse - exclude GDPR connexion

```css
eschenker.dbschenker.com###es-shell-overlay-container:has(es-privacy-modal)
eschenker.dbschenker.com##.es-shell-global-scrollblock:style(overflow-y: auto !important;)
```

related: https://github.com/uBlockOrigin/uBlock-issues/issues/1549

**Comment by uBlock-user** [comment]
> GDPR messages will not be addressed in uAssets.

**Comment by strict-block** [comment]
@llacb47 / @okiehsch can recheck to exlude GDPR in this pop-up?

**Comment by uBlock-user** [comment]
The filters you suggested do not exclude but block it instead, hence declined.

**Comment by strict-block** [comment]
My question is whether their cookie policy clearly talks about GDPR.

**Comment by uBlock-user** [comment]
It allows you to select which specific cookies you want to to allow to insert which is typical of a GDPR modal, this is GDPR.

**Comment by okiehsch** [comment]
> whether their cookie policy clearly talks about GDPR.

![image](https://user-images.githubusercontent.com/16838044/113989890-2aa28900-9851-11eb-9201-17beb16ee0a9.png)
