### ISSUE TITLE
gmx.net Anti Adblock Script

### ISSUE THREAD

**Issue by akks1981** [uBlockOrigin/uAssets#8866]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

Anti Adblock Script

```
https://www.gmx.net/fairplay/#.68ceb1c13adf29cfebbeb20898599b90

https://www.gmx.net/fairplay/
```

### Describe the issue

It is always advised to deactivate the blocking. 

### Screenshot(s)

https://camo.githubusercontent.com/b7c80ca5bcaec543595e64a47e9db6af008812fddb7b32afcb3bdb3bd40d7659/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f54476838396d492e6a7067

### Versions

- Browser/version: Firefox 88beta9
- uBlock Origin version: uBlock Origin v1.34.1b3

### Settings
Standart

**Comment by uBlock-user** [comment]
needs a gmx account ?

**Comment by akks1981** [comment]
I think so

**Comment by uBlock-user** [comment]
Do not post clickable links.

**Comment by akks1981** [comment]
ok

**Comment by akks1981** [comment]
THX :)
