### ISSUE TITLE
ynet.co.il - video not working

### ISSUE THREAD

**Issue by IsraeliUser** [uBlockOrigin/uAssets#8867]
`https://www.ynet.co.il/environment-science/article/HJodWcar00#autoplay`

Default settings + **EasyList Hebrew**
What do you suggest?

Thanks

**Comment by mapx-** [comment]
chrome ok, FF failed (even disabling uBO after the video ad the real video is failing)

**Comment by uBlock-user** [comment]
Tested on Firefox, working as expected

**Comment by llacb47** [comment]
If it doesn't play on firefox at all can one of you report it here: `https://webcompat.com`

Thanks
