### ISSUE TITLE
www.ytddownloader.com

### ISSUE THREAD

**Issue by What-Zit-Tooya** [uBlockOrigin/uAssets#8868]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.ytddownloader.com/`

### Describe the issue

Cookie annoyance

### Screenshot(s)

![1](https://user-images.githubusercontent.com/9832875/114290382-849d8b80-9aa9-11eb-8ea9-a8d4bfd64718.png)

### Versions

- Browser/version: [FF 87.0]
- uBlock Origin version: [1.34.0]

### Settings

- default
- adgguard + UBO annoyance

**Comment by okiehsch** [comment]
Fixed in `Fanboy’s Annoyance` list. If you don't want to enable that list add
`ytddownloader.com##.cookie`
to your filter list.
