### ISSUE TITLE
Block revercecaptcha.com

### ISSUE THREAD

**Issue by qaisjp** [uBlockOrigin/uAssets#8869]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://c.revercecaptcha.com/robot4/index.html?c=foobar`

### Describe the issue

This website needs to be blocked. `||revercecaptcha.com^$all` seems to work here.
 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/923242/114310666-694f7200-9ae3-11eb-9bf5-d4983f0f800a.png)

### Versions

- Browser/version: n/a
- uBlock Origin version: n/a

### Settings

-

**Comment by JobcenterTycoon** [comment]
and `get-instant-prize.life` can be blocked too

**Comment by qaisjp** [comment]
Thanks both!

**Comment by Yuki2718** [comment]
> and `get-instant-prize.life` can be blocked too

I have seen some different patterns of this prize staff. Will add regex to block them all.

**Comment by krystian3w** [comment]
Also started block `s` `e` `x` Badoo e-mail spam ads:

`https://find-yourprizes.life/?u=4kawkwf&o=8zep4zh&m=1&t=wpo2`

**Comment by Daxy7** [comment]
Hacked domain[s] with random keywords. [Screenshot](https://user-images.githubusercontent.com/91396482/226358837-710d862e-63fc-45f8-ba94-5192cb4dc77b.png)
`https://www.google.com/search?q=Grrr%27ungar`


Redirection chain:
`https://www.edfringe.com/ox/www/delivery/ck.php?ct=1&oaparams=2__bannerid=1477__zoneid=37__cb=899e48c70d__oadest=//guegnoswarwestpol.ga/199WLJedfringe652`
`https://guegnoswarwestpol.ga/199WLJedfringe652`
`https://szexma.com/?u=n7rwwwl&o=at3ruqf&t=197` (blocked with regex)

**Comment by mattnotmitt** [comment]
Why did edfringe.com get blocked? This is the official site of the edinburgh fringe festival...

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0ff23717391b17a8259f17f77f1bb04f3f7416c7

**Comment by mapx-** [comment]
@mattnotmitt however the site has some malicious content / has been hacked ?!

`https://www.edfringe.com/ox/www/delivery/ck.php?ct=1&oaparams=2__bannerid=1477__zoneid=37__cb=899e48c70d__oadest=//guegnoswarwestpol.ga/199WLJedfringe652`

**Comment by mattnotmitt** [comment]
Hm, that's a little worrying. I'll reach out to them :)

**Comment by Yuki2718** [comment]
> Why did edfringe.com get blocked? This is the official site of the edinburgh fringe festival...

Apparently the site was abused for open-redirect, but I should have checked.

**Comment by hvdijk** [comment]
> Apparently the site ~was~ is abused for open-redirect, but I should have checked.

The screenshot in @Daxy7's comment shows it wasn't just an open redirect, it is (or was) actively serving illegitimate content. I had also reached out to them, and they just completely deny that this happened.

**Comment by Daxy7** [comment]
Would regex work on these [types of domains](https://pastebin.com/raw/ZLKnTT6k)

Entered one of those domains into google and these are apparently many compromised domains using a lone redirect
`https://www.google.com/search?q=namebawancitel.gq`
