### ISSUE TITLE
doodrive.com

### ISSUE THREAD

**Issue by What-Zit-Tooya** [uBlockOrigin/uAssets#8875]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://doodrive.com/f/w83eq?f=ee571bcf475d352daa7a403f`

### Describe the issue

Banner ads NordVPN on right side

### Screenshot(s)

![x](https://user-images.githubusercontent.com/9832875/114531785-6933ab80-9c76-11eb-9ed5-56f50a71151d.png)

### Versions

- Browser/version: [FF/87.0]
- uBlock Origin version: [1.34.0]

### Settings

- Default
- EasylistCookie
- AdGuard Annoyance
- uBO Annoyance

**Comment by IThinkIAmCool** [comment]
@ryanbr
