### ISSUE TITLE
foreca.com

### ISSUE THREAD

**Issue by P0Rtvine** [uBlockOrigin/uAssets#8877]
### URL(s) where the issue occurs

`https://www.foreca.com/weathermap/rain`

### Describe the issue

You can hide empty spaces?

### Screenshot(s)
<details>
<summary>Screen</summary>

![2021-04-13_132820](https://user-images.githubusercontent.com/57287308/114538873-85c2ea00-9c5c-11eb-9a0d-071b93ddb6f5.png)
![2021-04-13_132835](https://user-images.githubusercontent.com/57287308/114538870-852a5380-9c5c-11eb-9c77-4a6f12b0cd02.png)
</details>

### Versions

- Browser/version: Google Chrome
- uBlock Origin version: 1.34.0

### Settings
<details>
<summary>Screen</summary>

![2021-01-22_100714](https://user-images.githubusercontent.com/57287308/105464158-c3395c00-5c99-11eb-965b-81215d8f7bec.png)
</details>

**Comment by uBlock-user** [comment]
@ryanbr
