### ISSUE TITLE
diep.io anti-adb

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#8878]
### Prerequisites
I encountered a message and I thougt that this could be addressed in the included (but not enabled by default) 'uBlock filters -- Annoyances' filter list.

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
I just found out that an issue (https://github.com/uBlockOrigin/uAssets/issues/155) was opened for this website.
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://diep.io`

### Describe the issue

Already described.

### Screenshot(s)
![Screenshot 2021-04-13 204129](https://user-images.githubusercontent.com/81419637/114596741-a6109a00-9c98-11eb-9575-e4fa8f653ab9.png)

### Versions

- Browser/version: Firefox Version 87.0
- uBlock Origin version: 1.34.0

### Notes

I already opened an issue about this (https://github.com/uBlockOrigin/uAssets/issues/8876).

A screenshot that shows what filter lists I have enabled in uBO:
![image](https://user-images.githubusercontent.com/81419637/114597105-0dc6e500-9c99-11eb-9ecf-bdc795e840dd.png)

**Comment by IThinkIAmCool** [comment]
I encountered the message after proceeding to spawn.

**Comment by mapx-** [comment]
I noted anti adblocking code in wasm source (script + xhr)

**Comment by uBlock-user** [comment]
Easylist's filter takes care of it.

**Comment by IThinkIAmCool** [comment]
So is it caused by Firefox's Enhanced Tracking Protection?

**Comment by uBlock-user** [comment]
Could be, are test on default settings + all other extensions disabled, if that doesn't help disable ETP and try again.

**Comment by IThinkIAmCool** [comment]
I reproduced with Firefox's Enhanced Tracking Protection being disabled on the website.

**Comment by IThinkIAmCool** [comment]
Should I test without Fanboy's Annoyance?

**Comment by IThinkIAmCool** [comment]
> 
> 
> Should I test without Fanboy's Annoyance?

I did and still encountered the message.

**Comment by mapx-** [comment]
@uBlock-user 

press enter

![image](https://user-images.githubusercontent.com/10303732/114602647-2504d300-9c97-11eb-8474-fd030a6496c5.png)

**Comment by uBlock-user** [comment]
I did, still nothing...

**Comment by uBlock-user** [comment]
@mapx- are you able to reproduce ?

**Comment by mapx-** [comment]
sure, chrome / FF

**Comment by mapx-** [comment]
sometimes is appearing after 5-10 sec

**Comment by uBlock-user** [comment]
I don't see unless I override the EL filter with `||static.diep.io/a.js$script,important`

**Comment by IThinkIAmCool** [comment]
@uBlock-user are you using uBlock Origin in anything else than the default mode?

**Comment by uBlock-user** [comment]
I can reproduce in private browsing mode,hmmm

**Comment by uBlock-user** [comment]
If you do not pick the nick and wait for 20 secs, the check kicks in, looks for `#ac1 > div > iframe[id^="google_ads_iframe_"]`, seems that elements needs to be created to bypass this.

**Comment by JobcenterTycoon** [comment]
So a custom script like https://github.com/AdguardTeam/AdguardFilters/commit/3c013221db6e843f8b22ea50b016221365efedfc is needed

**Comment by llacb47** [comment]
I seem to recall another site targeting these elements, maybe we need a scriptlet that creates fake google ad iframes to trick this site.

**Comment by CyberMan571** [comment]
![image](https://user-images.githubusercontent.com/30759335/126406843-afe0d8ea-3044-45c6-9dda-82914408eb94.png)

**Comment by CyberMan571** [comment]
@ghost
do you use else adblocker ? + try adguard dns

**Comment by CyberMan571** [comment]
![image](https://user-images.githubusercontent.com/30759335/126417718-d89c8b59-5142-4725-8554-b5c76250bc89.png)
Maybe, maybe, different on you

**Comment by CyberMan571** [comment]
ads scripts in these!
```
https://diep.io/build_596b764e82eeb36f6f29fbf855f90cbdaa5fa3ad.wasm.js
https://diep.io/c.js?2
```
check its, please
```
diep.io##+js(acis, document.getElementById, adSlot)
diep.io##+js(aost, document.getElementById, canvas)
diep.io##^script:has-text(window.aiptag)
diep.io##^script:has-text(googletag)
ad_box_^$document,script,1p,3p
```

`window["ads"] = true;`

```js
("Ad started")});Bolt["on"](playerName,Bolt["BOLT_AD_ERROR"],function(){console.log("Ad error");_videoads_done()});Bolt["on"](playerName,Bolt["BOLT_AD_COMPLETE"],function(){console.log("Ad complete");_videoads_done()})};window["onBoltLoaded"]=f},8631:function(){var player=document.getElementById("player")
```

**Comment by CyberMan571** [comment]
WebAssembly Binary File
also, ads is in below file!
`​https://static.diep.io/build_596b764e82eeb36f6f29fbf855f90cbdaa5fa3ad.wasm.wasm`

**Comment by CyberMan571** [comment]
If  no block to m28n.net it causes high process,  noisy fan! and  need  it   for playing game!
Versatile, advanced ad blocking is a must.

in AdGuard Annoyances filter
`@@||static.diep.io/*.js$~third-party`
is false filter

**Comment by CyberMan571** [comment]
@ghost
The request log(list)  can different for you!
Can you send logger list during ads showing(ads pop up)

**Comment by CyberMan571** [comment]
`(data (i32.const 14748)
    "\d7\00\00\00.\01\00\00/\01\00\000\01\00\001\01\00\002\01\00\003\01\00\00This game mode is disabled for adblock users\00Connecting...\00Disable VPNs or proxies if this takes too long\00Changelog\00{ window.open(UTF8ToString($0), \22_blank\22); }\00https://digdig.io/\00{ cp5.contexts[$0].lineCap = \22butt\22; }\00{ cp5.contexts[$0].lineCap = \22round\22; }\00{ cp5.contexts[$0].lineCap = \22square\22; }\00{ cp5.contexts[$0].quadraticCurveTo($1, $2, $3, $4); }\00google_play.png\00https://play.google.com/store/apps/details?id=com.miniclip.diep.io\00app_store.svg\00https://itunes.apple.com/app/diep.io/id1114751883?mt=8&at=1l3vajp\00reddit.png\00https://www.reddit.com/r/diepio/\00wiki.png\00https://diepio.gamepedia.com/Diep.io_Wiki\00facebook.png\00https://www.facebook.com/officialdiepio\00youtube.png\00https://www.youtube.com/channel/UCVtlkiQcG3iJPXtqynyNVoQ?sub_confirmation=1\00Privacy Policy\00pp.txt\00Terms of Service\00tos.txt\00More games\00https://iogames.space/\00{ var img = cp5.images[$1]; if(!img.isLoaded) return; if(img.width == 0 || img.height == 0) return; cp5.contexts[$0].drawImage(img, 0, 0, img.width, img.height, 0, 0, 1, 1); }\00Last updated: July 2nd 2021\0a\0a* We invite you to play our latest game: digdig.io\0a\0a\00\00\00\00<"
  )
`
>---
```
(data(i32.const 24624)
    "\8d\01\00\00\9a\01\00\00\9b\01\00\00\9c\01\00\00\9d\01\00\00\9e\01\00\00\9f\01\00\00You're using an adblocker, please consider disabling it to support the game\00adblock\00diep.io.\00{ return curScript != null ? allocateUTF8(curScript.src) : 0; }\00{ return curScript != null ? allocateUTF8(curScript.innerHTML) : 0; }\00pla.upo\00=gsc()\00{ return document.querySelector(UTF8ToString($0)) != null; }\00script[src~=\22.tk/\22]\00[class~=\22minimap\22]\00script[src~=\22diep.js\22]\00#loading\00#canvas\00script[src~=\22hooks.js\22]\00#extension_override\00#optnAutoRespawnz\00#optnAutoRespawn\00#optnAutoFire\00#optnAutoSpin\00#gameOptions\00#notificationPopups\00#topRight\00#tankMarker\00#as0\00#ffad\00script[src*=\22chitika.net\22]\00#chitikaAdBlock-0\00script[src*=\22dl.dropbox.com\22]\00script[src*=\22jquery.com\22]\00ins[data-ad-client=\22ca-pub-8318511014856551\22]\00{ return Function.prototype.toString != originalFunctionToString; }\00{ var r = UTF8ToString($0); return document.getElementById(\22canvas\22)[r] !== document.body[r]; }\00shadowRoot\00{ return document.body[UTF8ToString($0)] !== void 0; }\00{ return !!document.body[UTF8ToString($0)]; }\00{ var f = UTF8ToString($0); var d = document.createElement('div'); if(!d[f]) return false; return d[f]() == document.body[UTF8ToString($1)]; }\00ii\00createShadowRoot\00{; var s0 = UTF8ToString($0); var s1 = UTF8ToString($1); var t = window[s0][s1]; window[s0][s1] = function(){ return \22abcdef\22; }; var res = window[s0][s1].toString().indexOf(\22abcdef\22) == -1; window[s0][s1] = t; return res; }\00document\00getElementById\00{ return document.getElementById(UTF8ToString($0)) != null; }\00minimap\00dark-theme\00{ return document.getElementsByClassName(UTF8ToString($0)).length > 0; }\00panel\00connect-ip\00refresh-room\00input-change-color\00gui-dieptooI\00{ return typeof window[UTF8ToString($0)] != \22undefined\22; }\00navigator\00heuristic\00__WS\00editScript\00g_zoom\00iDiep\00_alert\00{ return !!window.WebSocket.prototype[\22_send\22]; }\00{ return allocateUTF8(document.body.innerHTML); }\0078233995\00{ return (function(){}).prototype.constructor.toString.apply(document.querySelector).indexOf(\22return\22) != -1; }\00{ return document.body.parentElement != document.documentElement; }\00{ return allocateUTF8(window.navigator.userAgent); }\00Trident\00{ var s0 = UTF8ToString($0); return window[UTF8ToString($2)].prototype[s0][UTF8ToString($1)] != s0; }\00iii\00measureText\00name\00CanvasRenderingContext2D\00fillText\00getImageData\00toString\00Function\00darkMenu\00optnAutoRespawn\00tempMsg\00DTTOKEN\00DTTOKEN_zeach_ily\00DTTOKEN_zeach_iIy\00{ return allocateUTF8((function(){}).prototype.constructor.toString.apply(document.querySelector)); }\00{ return allocateUTF8((function(){}).prototype.constructor.toString.apply(window.alert)); }\00{ return allocateUTF8((function(){}).prototype.constructor.toString.apply(CanvasRenderingContext2D.prototype.fillText)); }\00{ return allocateUTF8((function(){}).prototype.constructor.toString.apply(CanvasRenderingContext2D.prototype.strokeRect)); }\00{ return allocateUTF8((function(){}).prototype.constructor.toString.apply(CanvasRenderingContext2D.prototype.strokeText)); }\00{ return allocateUTF8((function(){}).prototype.constructor.toString.apply(CanvasRenderingContext2D.prototype.scale)); }\00{ return allocateUTF8((function(){}).prototype.constructor.toString.apply(CanvasRenderingContext2D.prototype.translate)); }\00{ return allocateUTF8((function(){}).prototype.constructor.toString.apply(CanvasRenderingContext2D.prototype.fillRect)); }\00{ return allocateUTF8((function(){}).prototype.constructor.toString.apply(CanvasRenderingContext2D.prototype.rotate)); }\00{ return allocateUTF8((function(){}).prototype.constructor.toString.apply(CanvasRenderingContext2D.prototype.getImageData)); }\00return\00[native code]\00{ delete window.localStorage[UTF8ToString($0)]; }\00{ return \22google_ad_client\22 in window && typeof window.google_ad_client == \22undefined\22; }\00google_ad_client\00CHITIKA\00{ var ctx = cp5.contexts[$0]; var canvas = ctx.canvas; ctx.clearRect(0, 0, canvas.width, canvas.height); }\00{ var ctx = document.createElement('canvas').getContext('2d'); for(var i = 0; i < cp5.contexts.length; ++i){ if(cp5.contexts[i] != null) continue; cp5.contexts[i] = ctx; return i; } cp5.contexts.push(ctx); return cp5.contexts.length - 1; }\00{ cp5.contexts[$0].miterLimit = $1; }\00Function is not reentrant, this is bad\00Corruption at %p %02X\0a\00{ return allocateUTF8(window.location.hash); }\00{ if(window['setLoadingStatus']) window['setLoadingStatus'](UTF8ToString($0)); }\00diepio\00-")
```
`
You're using an adblocker, please consider disabling it to support the game\00adblock\00diep.io.\00`
`Connecting...\00Disable VPNs or proxies if this takes too long`
Please, can you more understandable wiki page!

**Comment by Mennaruuk** [comment]
I don't see adblock anymore, without adding any filters.
![image](https://user-images.githubusercontent.com/52135169/130333529-e6e7540f-432a-4dba-89a4-2b6de205122a.png)
![image](https://user-images.githubusercontent.com/52135169/130333549-fdbf1bf2-b92f-457d-8d5b-f7cec0a57c4a.png)

**Comment by uBlock-user** [comment]
try to repro as per https://github.com/uBlockOrigin/uAssets/issues/8878#issuecomment-819882155

**Comment by Mennaruuk** [comment]
Can't reproduce after three minutes

https://user-images.githubusercontent.com/52135169/130333849-459a59ed-b049-4082-94e9-7724aa35ea37.mp4

**Comment by uBlock-user** [comment]
Think they removed the anti-adb, none of the filters are fired.

**Comment by CyberMan571** [comment]
the ad blocker issue(not appearing popup) is about developer however this problem on diep.io  has  causes freeze  or hot cpu and gpu to your computer.
you can buy Laptop cooler

**Comment by CyberMan571** [comment]
> Can't reproduce after three minutes
> X3DkrYlNoX_Trim.mp4

it is filter error.(if you used new filter )

**Comment by CyberMan571** [comment]
> I don't see adblock anymore, without adding any filters.
Because, it   appears on(in) some game mode
`This game mode is disabled for adblock users`
