### ISSUE TITLE
bobs-tube.com  ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#888]
URL(s) where the issue occurs

https://bobs-tube.com/videos/2469516/petite-teenage-fuck-doll-named-elsa-jean-sucks-and-gets-rammed-so-hard/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
Anti-Adblock @mapx-    start video and wait 15 seconds

**Comment by KiLL4FuNK** [comment]
ADS
