### ISSUE TITLE
is that possible to block this type of ads? (youtube)

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#8880]
![Screenshot (2254)](https://user-images.githubusercontent.com/29838157/114654107-a732dd00-9d13-11eb-9098-853cd67066f3.png)
most of annoying ads is already blocked
but pre-play video ads still present even without any ads on it....
(just blank but need to waiting some second before video started)

**Comment by okiehsch** [comment]
We have an "All youtube issues thread".
https://github.com/uBlockOrigin/uAssets/issues/7636
