### ISSUE TITLE
Popup annoying hiperdex.com

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#8881]
`https://hiperdex.com/`
when need to login or click on any manga/comic on sites, the popup will trigger

**Comment by okiehsch** [comment]
What browser are you using?

**Comment by okiehsch** [comment]
Nvm, I can reproduce using Firefox.

**Comment by Dhanamerdeka** [comment]
thanks :)

**Comment by frjoethesecond** [comment]
This appears to be happening again. I've gotten a bunch of persistent popup tabs on here lately.
