### ISSUE TITLE
Anti-adblock on nu.nl

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#8883]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
nu.nl
### Describe the issue
nu.nl detects an adblocker. 
With the following rule this is tagled `nu.nl##+js(set, is_adblocker_in_use, false)`
But last time when I checked this site they didn't detect. So I don't no if this rule is necessary or not.
### Versions

- Browser/version: **Edge** _latest version_
- uBlock Origin version: **1.34.0**

### Filters in use
- uBlock Filter
- EasyPrivacy
- EasyList
- EasyList Dutch

**Comment by okiehsch** [comment]
That filter
`nu.nl##+js(set, is_adblocker_in_use, false)` 
is already part of `uBO-annoyances`.
I can't reproduce, can you post a screenshot of the anti adblock message?

**Comment by JohnyP36** [comment]
Last time I checked this site I didn't get a message anymore. So maybe this rule is outdated. 
I'm not able to reproduce it.

**Comment by BPower0036** [comment]
Tested it. The rule is not outdated.
