### ISSUE TITLE
a little adjustment in filters lists

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#8885]
### URL(s) where the issue occurs

videos break

`https://www.lavanguardia.com/vivo/lifestyle/20210413/6656476/efectos-secundarios-vacunas-covid-coronavirus.html`

### Describe the issue

**Easyprivacy**: 

`@@||scorecardresearch.com/c2/plugins/streamingtag_plugin_jwplayer.js`

**Peter Lowe’s Ad and tracking server list** is blocking this 

`sb.scorecardresearch.com/internal-c2/plugins/streamingtag_plugin_jwplayer.js`

Well you understand about this... 😁

**Comment by uBlock-user** [comment]
@ryanbr 

@@||sb.scorecardresearch.com^*/streamingtag_plugin_jwplayer.js$script,domain=lavanguardia.com
