### ISSUE TITLE
megaup anti adblock 

### ISSUE THREAD

**Issue by subby2006** [uBlockOrigin/uAssets#8886]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://megaup.net`

### Describe the issue
Anti-Adblock on download page
 

### Versions

- Browser/version: Firefox mobile
- uBlock Origin version: 1.34

### Settings
Default filter lists

-

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0864f662ab4c63416a2672ebc285a0f880c7ada3

force update uBlock Filters list.
