### ISSUE TITLE
player.tubia.com video wouldn't load

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#8890]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
example: https://www.spel.nl/spel/basketballijn
### Describe the issue
The walkthtrough video at the bottom of the site wouldn't load. 
In uBlock there is the filter `||adservice.google.*/adsid/integrator.js$xmlhttprequest,redirect-rule=nooptext,domain=tubia.com`
This filter don't work for, I gues. 

Maybe add the rules: 
`@@||adservice.google.*/adsid/integrator.js$domain=player.tubia.com` 
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$domain=player.tubia.com`

### Screenshot(s)
The frame where the video has to be show it just gives a black field.

### Versions

- Browser/version: **Edge** _latest version_
- uBlock Origin version: **1.34.0**

### Filters in use
- uBlock Filter
- EasyPrivacy
- EasyList
- EasyList Dutch

**Comment by okiehsch** [comment]
Works fine on my end wwith a default setup.

**Comment by BPower0036** [comment]
Works also fine on my end

**Comment by JohnyP36** [comment]
> Works fine on my end wwith a default setup.



> Works also fine on my end

When I checked it out I had no problem anymore. Sorry for your time.
