### ISSUE TITLE
ublock breaks elitepvpers.com

### ISSUE THREAD

**Issue by Zerebokep** [uBlockOrigin/uAssets#8891]
### URL(s) where the issue occurs
`
https://www.elitepvpers.com/forum/`

### Describe the issue

All dropdowns on the site don't work if ublock is enabled, e.g. the one when clicking on "your notifications" at the top-bar. The site also looking sometimes broken on sub-pages, unfortunately I'm not able to reproduce this, as that issue isn't permanently.

### Screenshot(s)

https://i.imgur.com/ivc7JMo.png

### Versions

- Browser/version: Chrome v89.xx
- uBlock Origin version: v1.34.0

### Settings

- none

**Comment by lain566** [comment]
Can't reproduce, Works for me.

<details><summary>Screenshot</summary>

![Captura de pantalla 2021-04-15 181904](https://user-images.githubusercontent.com/27441315/114904647-5d7fea80-9e18-11eb-8160-26abb4a66963.png)
</details>

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled.

**Comment by Zerebokep** [comment]
It got fixed by the last filter update I guess? In the meantime I've used Safari, now there is the same problem (Chrome is working fine for me now).

https://i.imgur.com/DWSB2Mc.png

**Comment by uBlock-user** [comment]
uBO is not available in Safari, what extension are you using ?

**Comment by Zerebokep** [comment]
I'm using this fork: https://github.com/el1t/uBlock-Safari
