### ISSUE TITLE
t-online.de

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#8892]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.t-online.de/nachhaltigkeit/`

### Describe the issue

Ad pictures

### Screenshot(s)

<img width="759" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/114888277-5ef5e680-9e09-11eb-87e6-fdfcde41f94b.PNG">

### Versions

- Browser/version: firefox developer
- uBlock Origin version: v1.34.0

### Settings

default

**Comment by JobcenterTycoon** [comment]
I get adreinsertion again here (example): `https://www.t-online.de/nachrichten/`

**Comment by okiehsch** [comment]
Works fine on my end.
I get the reinserstion if I disable `uBO-filters` and the ads are gone if I enable it.

**Comment by JobcenterTycoon** [comment]
Im checked the logger and see requests from `https://edioca.com` with these ad pictures.

![Unbenannt](https://user-images.githubusercontent.com/48647394/116767839-f9257380-aa32-11eb-8c90-0b5c66b2865c.PNG)

Do you can reproduce in private mode (Firefox)?

**Comment by okiehsch** [comment]
> can reproduce in private mode (Firefox)? 

Yes, that's the only way I can reproduce. No ads using chromium in incognito mode.
I notified `EasyList` simply blocking `edioca.com` works fine.

**Comment by okiehsch** [comment]
https://github.com/easylist/easylist/commit/2906738ad187fd57caa781bf9a1183d9e8442429

**Comment by JobcenterTycoon** [comment]
Looks like its a bigger network with 88 ad or tracking Domains all based on the IP 136.243.25.9 (reverse check: `https://hackertarget.com/reverse-ip-lookup/`). when i check all domains i get: PTR `api.addefend.com`

URL list:

`aaroaj.com` (+ i saw this on a discussion about tracking)
`addefend-platform.com`
`addefend-platform.de`
`addefend-platform.net`
`benelph.de`
`bjakku.com`
`builfico.de`
`uobsoe.com`
`unaealay.net`
`tabsepin.net`
`presbu.de` (1x1 pixel)
`planeos.de`
`pabionak.net`
`odillees.de`
`manughl.de`
`letiva.de` (1x1 pixel)
`jubbie.de`
`itectale.de`
`intectwo.de`
`inforts.de`
`incown.de`
`idoliga.de`
`iefpiu.com`
`hobodoka.de`
`hirsung.de`
`fruited.de`
`frantro.de`
`fexzuf.com`
`ethnarc.de`
`eltelmis.de` (1x1 pixel)
`efadip.com`
`dywolfer.de`
`digentu.de`
`def-service.net`
`def-service.de`
`def-service.com`
`def-platform.net`
`def-platform.de`
`cussixia.de`
`cuiron.de`
`coordur.de`
`contentchoice.de`

blocked by EasyList:
`alysson.de`
`atonato.de`
`utoumine.net`
`unifini.de`
`skilyake.net`
`servote.de` (EL germany)
`readiong.net`
`qozveo.com`
`qivaiw.com`
`outhulem.net`
`oiycak.com`
`netwayer.de` (EL germany)
`mellodur.net`
`lasagneandands.com` (EL privacy)
`healte.de` (EL privacy)
`gearwom.de` (peter lowes ad and tracking filter)
`feadrope.net`
`||vidapi.expepp.de/files/*$media,domain=moviepilot.de` (uBlock main filter)
`edioca.com` (this issue, got blocked now)

What is the best option here? block all unblocked domains?

**Comment by okiehsch** [comment]
> What is the best option here? block all unblocked domains?

I don't remember seeing addefend using revolving adservers and we don't block domains preemptively. 
If they are actively used for ads or tracking purposes we can add them.
