### ISSUE TITLE
videoplaza.tv 

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uAssets#8896]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
videoplaza.tv

### Describe the issue
videoplaza.tv doesn't exist, so the following rules can be deleted:
`@@||videoplaza.tv^$script,domain=7sur7.be`
`@@||service.videoplaza.tv/proxy/pulse-sdk-html5/$script,domain=lalibre.be`
`@@||vp.videoplaza.tv/resources/pulse-sdk-html5/$script,domain=lalibre.be`

### Screenshot(s)
![image](https://user-images.githubusercontent.com/80090789/114974056-f860df00-9e81-11eb-9dcb-7d241b2482a4.png)

### Versions

- Browser/version: [Edge 89.]
- uBlock Origin version: [1.34.0]

**Comment by okiehsch** [comment]
`https://www.7sur7.be/belgique/les-contaminations-et-deces-en-hausse-les-hospitalisations-en-baisse~a6f27e8a/`
![image](https://user-images.githubusercontent.com/16838044/114975104-f4ce5780-9e83-11eb-925c-24accde15159.png)

**Comment by okiehsch** [comment]
Example for the second site you mentioned.
`https://www.lalibre.be/belgique/societe/a-9-ans-ce-belge-va-devenir-le-plus-jeune-diplome-universitaire-du-monde-5dcfbbcd9978e272f9e693b4`
