### ISSUE TITLE
[QUESTION] about  [class^="div-gpt-ad"]

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#8897]
In uBlock Filers there is a filer `#@#[class^="div-gpt-ad"]`
Why is this element general unblocked? Because other filters block them.

**Comment by uBlock-user** [comment]
Direct all your questions to https://old.reddit.com/r/uBlockOrigin/

**Comment by krystian3w** [comment]
or in new layout

https://www.reddit.com/r/uBlockOrigin/
https://new.reddit.com/r/uBlockOrigin/
