### ISSUE TITLE
poebuilds.net - blank spaces

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#8899]
### URL(s) where the issue occurs

`https://www.poebuilds.net/`

### Describe the issue

horrible blank spaces load after 20-30 seconds

### IMAGE1

![Captura2](https://user-images.githubusercontent.com/33556647/115016764-cff2d800-9eb5-11eb-95dc-36c2095c1551.PNG)

### IMAGE2

![Captura1](https://user-images.githubusercontent.com/33556647/115016781-d719e600-9eb5-11eb-9300-c9dacacb61fd.PNG)

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.34.0]

### Settings

Default

**Comment by mapx-** [comment]
test

`||static.parastorage.com^$xhr,domain=poebuilds.net`

**Comment by PIZZA90** [comment]
no blank spaces, but for some reason.. the slider, chat box, and contact form , i think is break.

if i block this: `/bundles/_generated/santa_viewer_*.json` similar issue, (no blank spaces, but "break")


![Captura123123](https://user-images.githubusercontent.com/33556647/115084910-ce52ff80-9f09-11eb-8dfa-090f79ac5509.PNG)

 i think this is site is created with **wix.com** ???

**Comment by mapx-** [comment]
what about

`||poebuilds.net^$csp=child-src`

**Comment by krystian3w** [comment]
`##div[id*="comp-"][id*="unavailableMessageOverlay"], div[id*="comp-"][id*="preloaderOverlay"]`

**Comment by PIZZA90** [comment]
`https://www.poebuilds.net/`
