### ISSUE TITLE
alotporn.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#890]
URL(s) where the issue occurs

http://www.alotporn.com/148189/sexy-brunette-teen-takes-a-huge-cock-in-her-tight-ass/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
ADS
