### ISSUE TITLE
[NSFW] redgifs.com ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#8904]
URL `https://www.redgifs.com/watch/closewarlikecygnet`
Firefox Nightly 89.0a1 (2021-04-16) (64-Bit)
uBlock Origin 1.34.0
Screenshot https://pic.infini.fr/r70u0rLR/Z4HDg1kQ.png

**Comment by uBlock-user** [comment]
`||bestcontentproject.top^`

Report to Easylist.
