### ISSUE TITLE
[Anti Ad-block] AnimeFever

### ISSUE THREAD

**Issue by TearJoy** [uBlockOrigin/uAssets#8905]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.animefever.tv/series/5551-fatestay-night-unlimited-blade-works-2nd-season-4ed452bb-1bbf-43a4-859e-0e32df49b30d/episode/11647-episode-6-the-beginning-of-the-circle `
and other episode links

### Describe the issue

 
AnimeFever blocks the usage of ublock origin
### Screenshot(s)
![image](https://user-images.githubusercontent.com/81557214/115055712-5a950080-9ed1-11eb-840d-25d04ba48bac.png)

### Versions

- Browser/version: Firefox 87 Stable
- uBlock Origin version: 1.34.0

### Settings

uBlock medium mode with malware domains disabled
![image](https://user-images.githubusercontent.com/81557214/115055850-93cd7080-9ed1-11eb-832a-5d26b6d5bb57.png)
and these are the settings i normally use for the site

**Comment by uBlock-user** [comment]
Test on default settings.

**Comment by TearJoy** [comment]
Okay, it suddenly fixed itself. Sorry for the trouble
