### ISSUE TITLE
Images are not visible with uBlock Orign active on some specific website.

### ISSUE THREAD

**Issue by elnath78** [uBlockOrigin/uAssets#8913]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.johnhardy.com/men/`

### Describe the issue

On Firefox 87.x the images are not being loaded, disabling uBlock Origin the images are visible.

### Screenshot(s)

![f27f086e](https://user-images.githubusercontent.com/17726947/115168510-79ef8180-a0bb-11eb-9e07-5f241df36ab9.jpg) 

### Versions

- Browser/version: [87]
- uBlock Origin version: [1.34.0]

### Settings

[none]

### Notes

[disabled the plugin via its UI button turning it off for that website]

**Comment by okiehsch** [comment]
Update the `uBO-unbreak` list, the site should work as expected after that.

**Comment by elnath78** [comment]
> Update the `uBO-unbreak` list, the site should work as expected after that.

Hello, sorry but I have no idea what you are talking about, how do I do that?

**Comment by okiehsch** [comment]
https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now

**Comment by elnath78** [comment]
> The lists also auto update, so you will get the fix eventually but if you want to use the site as soon as possible you have to manually update.

Fixed, thank you!
