### ISSUE TITLE
[NSFW] biguz.net

### ISSUE THREAD

**Issue by Toshiba1127** [uBlockOrigin/uAssets#8915]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://biguz.net/watch.php?id=3159889&name=sagging-grey-pants`

### Describe the issue

It has 5-10 sec ads

### Screenshot(s)

N/A due to NSFW

### Versions

- Browser/version: Chrome Version 89.0.4389.90
- uBlock Origin version: 1.34.0

### Settings

- Default

**Comment by AndroidMaster25** [comment]
I'm getting the same issue. I'm using Firefox nightly Android with clean profile. 

uBlock Origin version: 1.67.0

`https://biguz.net/watch.php?id=2815738&name=s044mov001-both-in-p-leather-jeans-and-heels`
