### ISSUE TITLE
uBlock Filters - Privacy breaks academicwork.se login button

### ISSUE THREAD

**Issue by Dyras** [uBlockOrigin/uAssets#8918]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.academicwork.se/`

### Describe the issue

With "uBlock Filters - Privacy" enabled, the login button in the top right corner doesn't work.

### Screenshot(s)

![grafik](https://user-images.githubusercontent.com/12563436/115213456-d1184500-a101-11eb-88f2-9d9d8e598824.png)

### Versions

- Browser/version: [Firefox 87.0]
- uBlock Origin version: [1.34.0]

### Settings

None. It happens on a stock install.

### Notes

This has been happening for ages on a stock install, and it's just now that I've reported it.

Hopefully this is the right place for this. Thanks for making these lists possible. <3

**Comment by uBlock-user** [comment]
Add `@@||googletagmanager.com/gtm.js$script,redirect-rule,domain=academicwork.se` to my Filters and report back.

**Comment by Dyras** [comment]
Seems to work just fine now :)
