### ISSUE TITLE
unblocked ad-placeholders

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uAssets#8920]
These site below have their ads blocked but the spaces where the ads are shown arent removed.

`https://cdromance.com/psp/blazblue-calamity-trigger-europe`/ (the 3 grey spaces show where the ads are)

`https://www.softexia.com/ `(no grey spaces but there are also 3 places of ads that should be removed but they arent)

**Comment by uBlock-user** [comment]
```
cdromance.com##.support-us
softexia.com##div.offer
```

@ryanbr

**Comment by Felipefpl** [comment]
I dont understand, the issue was closed because it was fixed in ublock or the issue was just dismissed?

**Comment by uBlock-user** [comment]
Fixed in Easylist.

**Comment by Felipefpl** [comment]
> Fixed in Easylist.

I see, thanks for the reply.
