### ISSUE TITLE
play.acast.com audio ads

### ISSUE THREAD

**Issue by mimmiechan** [uBlockOrigin/uAssets#8922]
~~EDIT: Sorry for the incomplete Title. I accidentally hit Enter before I was finished.~~

### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://play.acast.com/s/arkivsamtal/457.christoffernyqvistomsittmindregenombrott`

### Describe the issue

 
The podcast platform `Acast` (one of the most popular in Sweden) forces you to listen to ads, in the beginning of an episode, at the end and somewhere in the middle. They are un-skipable. This is not the case for every podcast, merely the ones that are monetized via their own advertising system, or so it seems.

### Versions

- Browser/version: 88.0 (64-bit)
- uBlock Origin version: 1.34.0

### Settings

- Defualt

### Notes

The ads are actually contained in the media file itself. But are separated by the player. Like an episode can be 1 h 10 min, but when you inspect the actual media file it's 1 h 12 min.

The podcast I linked to is available on other podcast players as well. When I play it on my regular pod catcher [Antennapod](https://github.com/AntennaPod/AntennaPod/), there are no ads.

There was one pod that I used to listen to that had the `Acast` ads in them (identifiable by their short ad break melody) but you could just skip forward in the file like a video tape when the ad started playing.

**Comment by uBlock-user** [comment]
> Like an episode can be 1 h 10 min, but when you inspect the actual media file it's 1 h 12 min.

This episode has 1 second difference between the time mentioned on the page and the actual audio time in the media file while few others I inspected are an exact match, no discrepancies found anywhere else.

**Comment by mapx-** [comment]
I'm able to reproduce, ads part of mp3 file

**Comment by krystian3w** [comment]
`Json-prune.js` see someting to cut?

**Comment by Daxy7** [comment]
still ads, any new counters?
https://github.com/easylist/easylist/issues/22928
(100 second ad united kingdom ip)
https://github.com/user-attachments/assets/74af94b8-f59b-48ea-8847-ffd75792cff4

**Comment by stephenhawk8054** [comment]
We can only remove the ads interface by

```adb
embed.acast.com##+js(json-edit-xhr-response, .result.timeline.*[?.type=="ad"], propsToMatch, /livestitch)
```

However, the audio is an mp3 file which includes the ads inside

```yml
 https://stitcher2.acast.com/livestitches/652c09cd551019aad5676e05a6be4a2a.mp3?aid=...
```

Nothing we can do with it.
