### ISSUE TITLE
10play.com.au

### ISSUE THREAD

**Issue by rachylou** [uBlockOrigin/uAssets#8929]
10play.com.au is now detecting ad-blockers.

Is there any way of fixing this?

url -- `https://10play.com.au/neighbours`

![Image 001](https://user-images.githubusercontent.com/46512068/115349791-6fd09e80-a1f3-11eb-84c3-df80b341b718.png)

**Comment by rachylou** [comment]
Sorry

URL(s) where the issue occurs
https://10play.com.au/neighbours/episodes/season-39/episode-8596/tpv210407fhvqo

Describe the issue
When trying to play any content containing ads, the player doesn't initiate and a message is displayed asking to disable ad-blocker. This has happened very recently as I was using it fine a few weeks ago.

Screenshot

![Image 001](https://user-images.githubusercontent.com/46512068/115349791-6fd09e80-a1f3-11eb-84c3-df80b341b718.png)

Versions
Browser/version: Brave / Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)
uBlock Origin version: 1.34.0
Settings
N/A

Notes
I tried disabling ublock and starting the player, but that didn't work. The ad played anyway.
I have only tried one TV program but I am guessing it would be sitewide.

**Comment by uBlock-user** [comment]
Disable Brave's built-in adblocker and try again.

**Comment by ghajini** [comment]
This work `@@||imasdk.googleapis.com^$script,domain=10play.com.au`

account logins at `http://bugmenot.com/view/10play.com.au`
hola vpn

**Comment by uBlock-user** [comment]
@ghajini `@@||imasdk.googleapis.com/js/sdkloader/ima3.js^$script,domain=10play.com.au` isn't that enough ?

**Comment by ghajini** [comment]
yes enough @uBlock-user

**Comment by rachylou** [comment]
Thank you - works :)

**Comment by uBlock-user** [comment]
@ghajini Does it still work ?
