### ISSUE TITLE
pornohans.com [NSFW]

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#8940]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.pornohans.com/film/bruenette-mit-brille-beim-rudelfick-11900/`

### Describe the issue

Many Ads 

### Versions

- Browser/version: Firefox developer
- uBlock Origin version:  v1.34.0

### Settings

default + uBlock Annoyances

### Notes

ok i see its a network with more sites with the same ads (tested):

`pornoente.tv`
`nursexfilme.com`
`milffabrik.com` ads left
`pornohirsch.net`
`pornozebra.com`
`xhamster-sexvideos.com`
`pornoschlange.com`
`https://xhamsterdeutsch.xyz/modeln-und-flirten-mit-der-kamera-eingeoelte-girls-in-bikinis/` (video ads)
`hdpornos.net`
`gutesexfilme.com`
`pornotom.com`

**Comment by mapx-** [comment]
test all those sites with filter like this 1

`pornohans.com##+js(aopr, runAfterLoad)`

**Comment by uBlock-user** [comment]
Also needed --

```
pornohans.com###PTwb2LABo
pornohans.com##.spc_height_60
pornohans.com##.vjs-overlay
pornohans.com###wa_10
```

**Comment by mapx-** [comment]
`||xhamsterdeutsch.xyz/bilder/mp4/amateur_6mb.mp4$media,1p`

**Comment by okiehsch** [comment]
If 
`pornohans.com##+js(aopr, runAfterLoad)`
breaks anything.
`pornohans.com##+js(nostif, detectAdblock)`
will also stop the reinsertion ads.

**Comment by JobcenterTycoon** [comment]
I still get all picture ads

**Comment by JobcenterTycoon** [comment]
Not working for me after a reload all ads are back

**Comment by uBlock-user** [comment]
`pornohans.com##+js(aopr, detectAdBlock)` works ?

**Comment by JobcenterTycoon** [comment]
I tried all suggested filters. None works (not only pornohans all other sites too except xhamsterdeutsch)

**Comment by uBlock-user** [comment]
@JobcenterTycoon try `pornohans.com##+js(aost, Object.prototype.hasOwnProperty, inlineScript)`

**Comment by mapx-** [comment]
try

`deinesexfilme.com##+js(nostif, appendChild)`

**Comment by JobcenterTycoon** [comment]
Not working but i know now the bait is `###advertise` so
`pornoaffe.com,pornodavid.com,pornofisch.com,pornofelix.com,pornohammer.com,pornoklinge.com,pornohelm.com,pornotom.com,pornotommy.com,pornovideos-hd.com,porndrake.com,porn-monkey.com,lesbenhd.com,hd-pornos.net,herzporno.com,halloporno.com,einfachtitten.com,deinesexfilme.com,pornotom.com,gutesexfilme.com,hdpornos.net,pornoschlange.com,xhamster-sexvideos.com,pornozebra.com,pornohirsch.net,pornoente.tv,nursexfilme.com,milffabrik.com#@##advertise`

`pornoaffe.com,pornodavid.com,pornofisch.com,pornofelix.com,pornohammer.com,pornoklinge.com,pornohelm.com,pornotom.com,pornotommy.com,pornovideos-hd.com,porndrake.com,porn-monkey.com,lesbenhd.com,hd-pornos.net,herzporno.com,halloporno.com,einfachtitten.com,deinesexfilme.com,pornotom.com,gutesexfilme.com,hdpornos.net,pornoschlange.com,xhamster-sexvideos.com,pornozebra.com,pornohirsch.net,pornoente.tv,nursexfilme.com,milffabrik.com###wa_10`

will fix the issue on all sites

**Comment by mapx-** [comment]
yeah, it seems it's something in FF

**Comment by mapx-** [comment]
needing for FF

`deinesexfilme.com##^script:has-text(detectAdblock)`

**Comment by JobcenterTycoon** [comment]
It break the thumpnails

**Comment by mapx-** [comment]
it seems this 1 is working too

`deinesexfilme.com##+js(aeld, , Math.random)`

**Comment by JobcenterTycoon** [comment]
the ghide filter works better for me because `deinesexfilme.com##+js(aeld, , Math.random)` leaves a few ads unblocked like 
<img width="234" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/115602800-a388f280-a2df-11eb-9d53-0fbc8e1102b0.PNG">

**Comment by JobcenterTycoon** [comment]
I found a few Domains with unblocked Ads from the EasyList Germany:

`beeg-pornos.com`
`https://www.german-porno-deutsch.info/urlaubsfotos-und-milf-sex/` (breakage video doens’t load)
`hd-sexfilme.com`
`meinyouporn.com`
`reifporn.de` (popup)
`exvideos-hd.com`
`tube8-pornos.com`
`https://www.xhamster-sexvideos.com/videos/nach-dem-solosex-die-blonde-tittenstute-genagelt-20510/` (ads not completely blocked and placeholder)

**Comment by JobcenterTycoon** [comment]
@ryanbr @Khrin please unbreak `german-porno-deutsch.info` because the video is broken by this filter `/^https?:\/\/.*\/[a-z0-9A-Z]{3,15}\.(php|jsx|1ph)/$subdocument,domain` in EasyList Germany

**Comment by JobcenterTycoon** [comment]
Hello there is one more site with these ads:
`https://www.momo-net.com/`

and the video ads on `https://xhamsterdeutsch.xyz/modeln-und-flirten-mit-der-kamera-eingeoelte-girls-in-bikinis/` are back because they changed the video ad url
