### ISSUE TITLE
MyDealz menu popup hower issue

### ISSUE THREAD

**Issue by rugk** [uBlockOrigin/uAssets#8941]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

I could not reproduce it there though.
If I disable uBlock Origin, on the site, however, it works.

The issue happens since a few days with uBlock.

### URL(s) where the issue occurs

 

When you hover over “Menu” (or any other menu/popup when logged in) no popup is opened.

**What happens:**:
![grafik](https://user-images.githubusercontent.com/11966684/115464909-13d73b80-a22e-11eb-8604-3848265bd54d.png)

**What should happen:**
![grafik](https://user-images.githubusercontent.com/11966684/115465399-d7f0a600-a22e-11eb-948c-c6664c5d155a.png)

### Screenshot(s)

**Broken version:**
![grafik](https://user-images.githubusercontent.com/11966684/115465494-fd7daf80-a22e-11eb-97e6-326d75bd66f3.png)

### Versions

- Browser/version: Firefox 87
- uBlock Origin version:  v1.34.0

### Settings

![grafik](https://user-images.githubusercontent.com/11966684/115465653-374eb600-a22f-11eb-96fb-a96fe867987f.png)
![grafik](https://user-images.githubusercontent.com/11966684/115465696-446ba500-a22f-11eb-8505-01b98b0872e1.png)

### Notes

As said I’ve tried to reproduce it in a fresh browser profile in Firefox 88, enabling the same sets, but I was unable to do so:

![grafik](https://user-images.githubusercontent.com/11966684/115465863-8563b980-a22f-11eb-989f-7a971d225455.png)
![grafik](https://user-images.githubusercontent.com/11966684/115465896-9280a880-a22f-11eb-99b3-176b990a049a.png)

Also have Privacy Badger installed and use Firefox internal tracking protection.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/e510201159f7c994be70d4cfab9598d132fb6cca

force update uBlock Annoyances list.
