### ISSUE TITLE
Redundant ublock filters

### ISSUE THREAD

**Issue by zinklog** [uBlockOrigin/uAssets#8942]
found a lot of reduntant filters using abpvn.com
![image](https://user-images.githubusercontent.com/51337096/115505721-85979f80-a297-11eb-9001-d47074b45269.png)
Should I remove them or is it something discussed before ?

**Comment by uBlock-user** [comment]
Individually collect and report those redundant filters here, not via a snapshot.

**Comment by zinklog** [comment]
@@||svonm.com/hd-main.js$script,domain=kicker.de|kino.de|videos.giga.de|video.spieletipps.de,badfilter has been made redundant by @@||svonm.com/hd-main.js$script,domain=kicker.de|kino.de|videos.giga.de|video.spieletipps.de,badfilter
kissasian.sh##.glx-teaser has been made redundant by ##.glx-teaser
kiminime.com##.visible.glx-teaser has been made redundant by ##.glx-teaser
games.dailymail.co.uk##div.RightRail__displayAdRight___1U1Q7llw has been made redundant by ##div[class*="displayAdRight"]
atresplayer.com##[href^="https://www3.smartadserver.com/click"] has been made redundant by ##[href*=".smartadserver.com"]
hdjavonline.com##.happy-inside-player has been made redundant by ##.happy-inside-player
taivenhanh.com##.blocker-notice has been made redundant by ##.blocker-notice
taivenhanh.com##.blocker-overlay has been made redundant by ##.blocker-overlay
pornhail.com##.ave-pl has been made redundant by ##.ave-pl
sonorousporn.com##.ave-pl has been made redundant by ##.ave-pl
reamporn.com##.ave-pl has been made redundant by ##.ave-pl
hulkstream.com###lads1 has been made redundant by ###lads1
mlbstream.tv,nbastream.tv,nhlstream.tv##[href^="https://pl.allsports4free.club/"] has been made redundant by ##[href^="https://pl.allsports4free.club/"]
rawstory.com##.amp-unresolved has been made redundant by ##.amp-unresolved
intoupload.net##a[href*="/go.php?a_aid="] has been made redundant by ##a[href*="/go.php?a_aid="]
hobby-machinist.com##.samCodeUnit has been made redundant by ##.samBannerUnit, .samCodeUnit
konstantinova.net##[href^="//mellowads.com/"] has been made redundant by ##[href^="//mellowads.com/"]
sextube-6.com##.full-ave-pl has been made redundant by ##.full-ave-pl
nylonbabez.net,nylonpornpictures.net,stockingspornpics.com##.full-ave-pl has been made redundant by ##.full-ave-pl
beegsexxx.com##.full-ave-pl has been made redundant by ##.full-ave-pl
asiansex.life##.full-ave-pl has been made redundant by ##.full-ave-pl
freeporncave.com##.full-ave-pl has been made redundant by ##.full-ave-pl
camcam.cc##.wps-player__happy-inside has been made redundant by ##.wps-player__happy-inside
teenager365.com##.wps-player__happy-inside has been made redundant by ##.wps-player__happy-inside
colegialamateur.com,culonas.com.ve,pornovenezolano.com.ve,puroanal.com,purovirgen.com,tetonas.xxx,venezporn.com,verhentai.org,videosxx.xxx##.wps-player__happy-inside has been made redundant by ##.wps-player__happy-inside
nightlifeporn.com##.wps-player__happy-inside--pause.wps-player__happy-inside has been made redundant by ##.wps-player__happy-inside
clicporn.com##.wps-player__happy-inside has been made redundant by ##.wps-player__happy-inside
gaytail.com##.wps-player__happy-inside has been made redundant by ##.wps-player__happy-inside
cartoon.porn##.wps-player__happy-inside has been made redundant by ##.wps-player__happy-inside
hanime.tv##.desktop.htvad has been made redundant by hanime.tv##.htvad
mywatchseries.*##+js(nosiif, visibility, 1000) has been made redundant by watchseries.*##+js(nosiif, visibility, 1000)
google.*###center_col > #resultStats + #tads + #res + #tads has been made redundant by google.*###center_col > #resultStats + #tads
google.*###mn #center_col > div > h2.spon:first-child + ol:last-child has been made redundant by google.*###mn #center_col > div > h2.spon:first-child
0123movies.*,123movieshub.*##+js(aopr, AaDetector) has been made redundant by 123movies.*##+js(aopr, AaDetector)
thefmovies.*##+js(nowoif) has been made redundant by fmovies.*##+js(nowoif)
ffmovies.*##+js(nowoif) has been made redundant by fmovies.*##+js(nowoif)
allfeeds.*,bfst.xyz,dubsstreamz.com,live-golf.stream,live-stream365.com,lowend.xyz,sporting77.*,sport24hd.net,sportustv4.ru,wstream.to##+js(nowoif) has been made redundant by streamz.*##+js(nowoif)
watch-series.*,watchseries.*##+js(acis, Math, XMLHttpRequest) has been made redundant by watchseries.*##+js(acis, Math, XMLHttpRequest)
databasegdriveplayer.*##+js(acis, Math, XMLHttpRequest) has been made redundant by gdriveplayer.*##+js(acis, Math, XMLHttpRequest)
kissasian.*##[id*="ScriptRoot"] has been made redundant by *##[id*="ScriptRoot"]
watchcartoonsonline.*##[id*="ScriptRoot"] has been made redundant by *##[id*="ScriptRoot"]
putlocker.*##[id*="ScriptRoot"] has been made redundant by *##[id*="ScriptRoot"]
arawatch.*##[id*="ScriptRoot"] has been made redundant by *##[id*="ScriptRoot"]
ouo.*##[id*="ScriptRoot"] has been made redundant by *##[id*="ScriptRoot"]
megaurl.*##[id*="ScriptRoot"] has been made redundant by *##[id*="ScriptRoot"]
dutchycorp.*##[id*="ScriptRoot"] has been made redundant by *##[id*="ScriptRoot"]
upclips.*##[id*="ScriptRoot"] has been made redundant by *##[id*="ScriptRoot"]
watch-series.*,watchseries.*##.sp-leader-bottom has been made redundant by watch-series.*,watchseries.*##.sp-leader
||shon.xyz^$csp=script-src 'self' 'unsafe-inline' *.gstatic.com *.google.com *.googletagmanager.com *.googleapis.com;frame-src 'self' *.google.com;connect-src 'self' has been made redundant by ||shon.xyz^$csp=sandbox allow-forms allow-same-origin allow-scripts allow-modals allow-orientation-lock allow-pointer-lock allow-presentation allow-top-navigation
||cloudgallery.net^$csp=sandbox allow-forms allow-same-origin allow-scripts allow-modals allow-orientation-lock allow-pointer-lock allow-presentation allow-top-navigation has been made redundant by ||cloudgallery.net^$csp=script-src * 'unsafe-inline'
||imghot.net^$csp=sandbox allow-forms allow-same-origin allow-scripts allow-modals allow-orientation-lock allow-pointer-lock allow-presentation allow-top-navigation has been made redundant by ||imghot.net^$csp=script-src * 'unsafe-inline'
||imgzong.*^$csp=sandbox allow-forms allow-same-origin allow-scripts allow-modals allow-orientation-lock allow-pointer-lock allow-presentation allow-top-navigation has been made redundant by ||imgzong.*^$csp=script-src * 'unsafe-inline'
canaisgratis.*,redecanais.*###guerejoback has been made redundant by canaisgratis.*,redecanais.*###guerejo
magesy.*##.adsbygoogle has been made redundant by *##.adsbygoogle
shrtfly.*##.adsbygoogle has been made redundant by *##.adsbygoogle
redtube.*##.adsbytrafficjunky:upward(li) has been made redundant by redtube.*##.adsbytrafficjunky
lindung.*##.adsbygoogle has been made redundant by *##.adsbygoogle
stfly.*##.adsbygoogle has been made redundant by *##.adsbygoogle
uploadproper.*##.adsbygoogle has been made redundant by *##.adsbygoogle
stadionowioprawcy.*##.adsbygoogle has been made redundant by *##.adsbygoogle
dutchycorp.*##.adsbygoogle has been made redundant by *##.adsbygoogle
getfreecourses.*##.adsbygoogle has been made redundant by *##.adsbygoogle
safetxt.*##.adsbygoogle has been made redundant by *##.adsbygoogle
evileaks.*##.adsbygoogle has been made redundant by *##.adsbygoogle
btdb.*##.alert-dismissible has been made redundant by btdb.*##.alert
bfstrms.*##.in.modal-backdrop has been made redundant by bfstrms.*##.in.modal
akwams.*##.adsbygoogle has been made redundant by akwams.*##.ads
100percentfedup.com,activistpost.com,addictinginfo.*,allthingsvegas.com,americasfreedomfighters.com,appleeats.com,bestfunnyjokes4u.com,bighealthreport.com,breakingfirst.com,bugout.news,bulletsfirst.net,canadafreepress.com,cheapism.com,cheatsheet.com,chicksonright.com,clashdaily.com,constitution.com,craigjames.com,dailyheadlines.net,dailysurge.com,deneenborelli.com,designbump.com,enstarz.com,evil.news,faithit.com,firstinfreedomdaily.com,foreverymom.com,freedom.news,godfatherpolitics.com,grammarist.com,greatamericanrepublic.com,hackspirit.com,latinpost.com,madworldnews.com,moneyversed.com,musictimes.com,naturalblaze.com,newser.com,opednews.com,patriotoutdoornews.com,politicaloutcast.com,realmomsrealreviews.com,realtytoday.com,redmaryland.com,reviveusa.com,rightwingtribune.com,rollingout.com,sciencetimes.com,shark-tank.com,sonsoflibertymedia.com,stupid.news,survivalnation.com,telexplorer.com.ar,thealternativedaily.com,theblacksphere.net,thedesigninspiration.com,thefreethoughtproject.com,thegatewaypundit.com,thehayride.com,thelastlineofdefense.org,thelibertydaily.com,themattwalshblog.com,thepoke.co.uk,thepolitistick.com,therealside.com,threepercenternation.com,tiebreaker.com,tosavealife.com,twisted.news,universityherald.com,vcpost.com,videogamesblogger.com,viralnova.com,wakingtimes.com,westernjournalism.com,worldlifestyle.com,youthhealthmag.com##.adsbygoogle has been made redundant by *##.adsbygoogle
vinaurl.*##.adsbygoogle:style(max-height: 1px !important;) has been made redundant by *##.adsbygoogle
file-upload.*##.adsbygoogle has been made redundant by *##.adsbygoogle
xhardhempus.*##.adsbygoogle:style(max-height: 1px !important;) has been made redundant by *##.adsbygoogle
zt-protect.*##.adsbygoogle has been made redundant by *##.adsbygoogle
dropgalaxy.*##.adsbygoogle:style(max-height: 1px !important;) has been made redundant by *##.adsbygoogle

**Comment by uBlock-user** [comment]
When I said "Individually collect and report those redundant filters", I meant do it yourself, not by that ABP tool which doesn't report correctly.

Lots of invalid entries, for example --

>  kissasian.sh##.glx-teaser has been made redundant by ##.glx-teaser

The tool failed to take into account the presense of `@@||kissasian.*^$ghide`

> vinaurl.##.adsbygoogle:style(max-height: 1px !important;) has been made redundant by ##.adsbygoogle
file-upload.##.adsbygoogle has been made redundant by ##.adsbygoogle
xhardhempus.##.adsbygoogle:style(max-height: 1px !important;) has been made redundant by ##.adsbygoogle
zt-protect.##.adsbygoogle has been made redundant by ##.adsbygoogle
dropgalaxy.##.adsbygoogle:style(max-height: 1px !important;) has been made redundant by *##.adsbygoogle

Fails to distinguish `:style` syntax from the plain cosmetic filter.

**Comment by mapx-** [comment]
The tool is obsolete

this one is ridiculous

`akwams.##.adsbygoogle has been made redundant by akwams.##.ads`

**Comment by uBlock-user** [comment]
> Individually collect and report those redundant filters

Like this -- https://github.com/uBlockOrigin/uAssets/issues/7044
