### ISSUE TITLE
mshare.xyz [Anti-Adblock]

### ISSUE THREAD

**Issue by Robbie8592** [uBlockOrigin/uAssets#8946]
### URL(s) where the issue occurs

`https://mshare.xyz/file/9UHliA`

### Describe the issue

Getting a banner to disable my adblocker 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/29841633/115642181-7a209480-a2e8-11eb-9960-918670848d10.png)

### Versions

- Browser/version: Firefox 88.0
- uBlock Origin version: 1.34.0

### Settings

Default Settings
-

### Notes

None

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled.

**Comment by krystian3w** [comment]
Try without Nano Dedender.
