### ISSUE TITLE
Falsely blocked doubleclick.net on Google's consent

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uAssets#8947]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://consent.google.com/dl?continue=https://translate.google.com/`

### Describe the issue
Falsely blocked doubleclick.net.
If you get the redirect cookie consent of Google and you click 'custom' and then set every think 'off' and agree. google redirects via doubleclick.net which is then blocked because of Pete Lowe List.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/80090789/115664572-4ffbc080-a342-11eb-9c9d-700de44c7acd.png)
![image](https://user-images.githubusercontent.com/80090789/115664584-51c58400-a342-11eb-9a86-9ec2c181e523.png)

### Versions

- Browser/version: [Edge 90.]
- uBlock Origin version: [1.34.0]

### Settings

-

**Comment by okiehsch** [comment]
Does
`@@||googleads.g.doubleclick.net/ads/preferences/*/optout?continue$doc`
work for you?

**Comment by BPower0036** [comment]
Yes it worked.
