### ISSUE TITLE
Site break babiato.co

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#8952]
`https://babiato.co/conversations/<ID Of THE CHAT>/`

can't send messages with ublock turned on...

**Comment by uBlock-user** [comment]
can't reproduce

![Capture](https://user-images.githubusercontent.com/21290713/115745569-2fb71a80-a3b1-11eb-83a5-8e045bdc726c.PNG)

**Comment by Dhanamerdeka** [comment]
@uBlock-user ummm
the problem appear when i reply the message from other people
not for sending

btw for reply... is on you there's are loading icon on top right corner on the screen?
is yes

nah that's the problem
when using ublock
that's icon not appear so when you click reply
the page not doing anything.... maybe the javascript blocked..... that's all i think...

can you check it again?
let me know again after you check it again

**Comment by uBlock-user** [comment]
I can reply just fine, you should have filled the template instead of skipping it. Test on default settings + all other extensions disabled.

**Comment by Dhanamerdeka** [comment]
hmmm okay...
maybe you can close this issue....

because when i disable the ublock, the message system working...
if the ublock on, they wont.....

for extra info... not all messages have this problem...
idk what wrong.... or this just some random bug or something

**Comment by okiehsch** [comment]
Can you post your logger output when you encounter your issue?
That way we can see what is blocked on your end.
https://github.com/gorhill/uBlock/wiki/The-logger
