### ISSUE TITLE
Fake twitch/facepunch rust drop website

### ISSUE THREAD

**Issue by accurateisaiah** [uBlockOrigin/uAssets#8953]
### Prerequisites

- [x]  This is not a support issue or a question 

    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

```
https://twitch.facepunch.com/
https://facepunchskin.com/
```

### Describe the issue
Phishing link. Steals steam credentials 
 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/44090193/115793427-1ce51b80-a39a-11eb-8dc0-96c1348161c1.png)
![image](https://user-images.githubusercontent.com/44090193/115793447-23739300-a39a-11eb-817f-cec1f6fcafa7.png)

### Versions

- Browser/version: Firefox 88.0
- uBlock Origin version: v1.35.0

### Settings

- Did not change any settings

### Notes

All links lead to a fake steam login page. just a phishing link

**Comment by krystian3w** [comment]
For me first is unlocked and second now offline.

So first is official?

**Comment by okiehsch** [comment]
> So first is official?

Yes.

**Comment by accurateisaiah** [comment]
https://twitch.facepunch.com/ this is the offical website for drops. 

there is a scam going around that makes the scam sites look like this

**Comment by krystian3w** [comment]
Looks like offline error?  IMO offline for most popular DNS'es providers.

![obraz](https://user-images.githubusercontent.com/35370833/118861483-d7563880-b8dc-11eb-8782-2581ca0414d0.png) |
--- |
