### ISSUE TITLE
adblock detect on fantasyfootballgeek.co.uk

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#8955]
`https://www.fantasyfootballgeek.co.uk/fantasy-premier-league-captain-poll-gw33-transfer-polls-bgw33/`

please fix

**Comment by patrickdrd** [comment]
I can't scroll, can someone check please?

**Comment by mapx-** [comment]
You are using fanboy's annoyances list, add

```
fantasyfootballgeek.co.uk#@#[aria-label="cookieconsent"]
fantasyfootballgeek.co.uk#@##cookie-law-info-bar
fantasyfootballgeek.co.uk#@#.wt-cli-cookie-bar-container
```

@ryanbr
