### ISSUE TITLE
FontAwesome Instagram icon breaks

### ISSUE THREAD

**Issue by dheera** [uBlockOrigin/uAssets#8956]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://fontawesome.com/icons?d=gallery&p=2&q=instagram`

### Describe the issue

Instagram icons on Font Awesome disappear

### Screenshot(s)

![2021-04-22_23-44](https://user-images.githubusercontent.com/1786477/115899723-f368d600-a413-11eb-94c6-0b759b4d1dfb.png)

### Versions

- Browser/version: Chrome, Linux
- uBlock Origin version: 1.34.0

### Settings

-

**Comment by Yuki2718** [comment]
Can't happen in default setting, must be some custom lists/filters. Fill all the template in.

**Comment by dheera** [comment]
![2021-04-23_17-27](https://user-images.githubusercontent.com/1786477/115908068-8575dc00-a41e-11eb-86d3-2d1f0f9cd002.png)
Disabling these default filters fixes it.

**Comment by uBlock-user** [comment]
You're not default settings as per the above picture. Test on default settings.

**Comment by krystian3w** [comment]
disable last two: 
![obraz](https://user-images.githubusercontent.com/35370833/115911698-b1b94900-a46e-11eb-9d30-787f14f5c6ac.png)

**Comment by krystian3w** [comment]
@yourduskquibbles can you fix this in your project?

**Comment by uBlock-user** [comment]
Broken by Web Annoyances Ultralist's generic cosmetic filter.
