### ISSUE TITLE
YouTube ad in protected video link

### ISSUE THREAD

**Issue by tommy3093** [uBlockOrigin/uAssets#8957]
### URL(s) where the issue occurs

`https://sledujserialy.to/episode/fatmagul-s01e01`

### Describe the issue

I'm not sure if this is even possible to fix, but want to at least know/try to ask. Under URL above, there is a video link when you click on "1. díl" which goes through protected link (need to click on play button few times) that started to show youtube ads recently before episode is played.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/155648/115902003-35b90400-a462-11eb-9b6c-a2772827927d.png)

### Versions

- Browser/version: Firefox 88.0
- uBlock Origin version: 1.35.0

### Settings

Default + added uBlock, AdGuard, Fanboy filter annoyances

**Comment by krystian3w** [comment]
EasyList Czech and Slovak can't help?

**Comment by llacb47** [comment]
That looks like the netu player, which should be taken care of. Do you get a similar ad preroll video here? `https://llacb47.github.io/netutest/`

**Comment by krystian3w** [comment]
Trojan on:

```
Malwarebytes
www.malwarebytes.com

-details raport-
When: 23.04.2021
When: 20:34
In: 9c035f80-a462-11eb-a38f-001999eae06b.json

-What version detected-
version: 4.3.0.98
component version: 1.0.1273
packet version: 1.0.39747
license: trial version

-About system-
OS: Windows 10 (Build 19042.928)
Processor: x64
filetype drive: NTFS
User: System

-what is blocked on WWW-
malware WWW page: 1
, C:\Program Files\Mozilla Firefox\firefox.exe, blocked, -1, -1, 0.0.0, , 

-about WWW-
category: Trojan
domain: instashowe.com
Adress IP: 172.67.183.242
Port: 443
by: outside / forward
Plik: C:\Program Files\Mozilla Firefox\firefox.exe



(end)
```

**Comment by tommy3093** [comment]
@krystian3w sorry I didn't mention it, I'm also using that list
@llacb47 yes, it is the same preroll ad there
