### ISSUE TITLE
Sponsored results on Ebay

### ISSUE THREAD

**Issue by j-james** [uBlockOrigin/uAssets#8958]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.ebay.com/sch/i.html?_nkw=the+secret+history`

### Describe the issue

"Sponsored results" on Ebay take up the first four slots of most searches. They're indicated as such by a light grey "Sponsored" banner at the top of the result.

### Screenshot(s)

![Screenshot from 2021-04-23 19-48-58](https://user-images.githubusercontent.com/35242550/115944934-cb0dc580-a46d-11eb-978d-8df1840dd7c6.png)

### Versions

- Browser/version: Ungoogled Chromium 88
- uBlock Origin version: 1.34.0

### Settings

N/A

### Notes

I'm not sure if this is in-scope.

**Comment by llacb47** [comment]
Try `ebay.com##.s-item__link[href*="cksum"]:upward(.s-item)`

**Comment by Mennaruuk** [comment]
Unfortunately, I'm still getting sponsored results :(

@uBlock-user

**Comment by ads2357** [comment]
Same. Ebay have implemented a scrambling mechanism for the word "sponsored" - each letter is in its own <span> and is interleaved with additional letters with display: none set. And there's no sign of cksum either, could be an obsolete filter.

Given Ebay's active countermeasures it could be that a dedicated browser extension containing tailored JavaScript is the only option - that or have ublock remove the invisible c*** and then apply the filter.

**Comment by mapx-** [comment]
test

```
ebay.com##.s-item__sep:matches-css(display: none):remove()
ebay.com##:xpath(//span[(text()='S')]):upward(.s-item)
```
