### ISSUE TITLE
uBlock detected at https://megaup.net/

### ISSUE THREAD

**Issue by darkRaspberry** [uBlockOrigin/uAssets#8961]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://megaup.net/1CDk4/test`

### Describe the issue

ublock Origin Detected.
 

### Screenshot(s)
![Screenshot from 2021-04-24 20-16-49](https://user-images.githubusercontent.com/56693429/115962666-20afa400-a53a-11eb-9b62-16f2e4b6bbf6.png)

### Versions

- Browser/version: Version 90.0.4430.85 (Official Build) (64-bit)
- uBlock Origin version: 1.34.0

### Settings

- Activate all the filters except language.
- change I'm advance user
- add cloud storage support,

### Notes

Sometimes It works. On a very rare situation.

https://github.com/uBlockOrigin/uAssets/issues/8886 I saw this fresh issue. And tried to update by force. But it didn't happen.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/a782a6e4d5d4607b61fedc1af9102c349f7f7e55

force update ublock filters list

**Comment by darkRaspberry** [comment]
> #8886 I saw this fresh issue. And tried to update by force. But it didn't happen.

@uBlock-user I mentioned this in my issue. That forced update filter doesn't solve my issue.

**Comment by uBlock-user** [comment]
You're not on default settings. Test on default settings.
