### ISSUE TITLE
A&E TV (USA) anti adblock

### ISSUE THREAD

**Issue by Movisivi** [uBlockOrigin/uAssets#8962]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [ x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://play.aetv.com/shows/wwes-most-wanted-treasures/season-1/episode-1`

### Describe the issue

A&E detects adblock

> It's not you...It's your ad blocker.

> To continue watching video, please disable your ad blocking software and reload the page. For instructions,click here.

### Versions

- Browser/version: Firefox Nightly
- uBlock Origin version:  v1.35.0

### Settings

https://i.imgur.com/Lm2PK3A.png
-

**Comment by Movisivi** [comment]
Doesn't work after purging all caches and updating filters. Manually adding the line from your commit breaks the video player

**Comment by okiehsch** [comment]
You added
`@@||aetv.com^$ghide`
and that broke the video player?

**Comment by Movisivi** [comment]
Yup. The player controls disappear after the page is finished loading and shows only the screenshot. CTRL + SHIFT + R got it going for the first time but a second refresh killed it.

**Comment by mapx-** [comment]
Running fine here chrome / FF. 
I added an exception, it's impossible to have broken it.

**Comment by okiehsch** [comment]
I can't reproduce and like @mapx- said the mentioned filter should not break anything and should certainly not hide parts of a site because it disables all cosmetic filters on the site.

**Comment by Movisivi** [comment]
All is well.  Thanks for the assistance. The issue was Firefox Nightly and autoplay. Re-enabling autoplay for that site (set to block audio/video by default) fixes playback and the player controls are visible. Such bad design.
