### ISSUE TITLE
[Anti-Adblock] falixnodes.net

### ISSUE THREAD

**Issue by gerwusa1823** [uBlockOrigin/uAssets#8964]
**Previous issue: https://github.com/uBlockOrigin/uAssets/issues/8605**

### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`falixnodes.net` (entire site)

### Describe the issue
Adblock is detected, they broke the old anti-anti-adblock
 

### Screenshot(s)
![image](https://user-images.githubusercontent.com/79057113/116100940-b28bee00-a6ad-11eb-8933-a0b137fd1b43.png)

### Versions

- Browser/version: Chrome 90.0.4430.85
- uBlock Origin version: v1.34.0

### Settings

- default

### Notes
Extracted anti adblock scripts:

Script 1
```js
$(document).ready(function() {


    function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }


        var pog = document.getElementsByTagName("ins");

            if (0 < pog.length) {
                sleep(2569).then(() => {
                    if (document.getElementById('aswift_0')) {
                    } else {
                        if (document.getElementById('aswift_1')) {
                        } else {
                            window.location.href = "https://falixnodes.net/disableadblock.php";
                        }
                    }
        }
            }
});
```

Script 2
```js
let script = document.createElement('script');
script.setAttribute('async','async');
script.setAttribute('data-ad-client','ca-pub-5572567098969441');
script.src = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js";
document.head.append(script);

script.onerror = function() {
  window.location.href = "https://falixnodes.net/disableadblock.php";
};
```

**Comment by uBlock-user** [comment]
generic redirection filter working as expected -- `||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect-rule=googlesyndication_adsbygoogle.js`

**Comment by uBlock-user** [comment]
Disable Chrome's built-in ad filterer and try again.

**Comment by gerwusa1823** [comment]
well, it seems that out of the blue it started working normally again (i didn't change anything), strange

**Comment by gerwusa1823** [comment]
(side note: it was not uBO that was being detected, apparently the site does not like when other extensions (such as NoScript) block `https://pagead2.googlesyndication.com`)

**Comment by uBlock-user** [comment]
uBO is never detected, easylist's filters are, they always use that as baits.

**Comment by gerwusa1823** [comment]
well yes, but in this case the issue actually was that NoScript (which was not shown on the screenshot but it was enabled) was preventing `pagead2.googlesyndication.com` from loading and that was causing the redirect, I thought it was uBO at first, which is why I opened this at first, a bit of a mistake on my part, sorry about that

**Comment by uBlock-user** [comment]
> in this case the issue actually was that NoScript (which was not shown on the screenshot but it was enabled) was preventing pagead2.googlesyndication.com from loading and that was causing the redirect

https://twitter.com/gorhill/status/1033706103782170625.

**Comment by gerwusa1823** [comment]
this is the first time NoScript caused this sort of an issue for me when used alongside uBO, which is a bit strange given how i've been using this configuration for years now, but i guess i can sort of see why.

**Comment by uBlock-user** [comment]
In this case, NoScript **intercepted** the script first and blocked the network request, thereby hampering the chance for uBO to intercept first and then **redirect** to local neutered version of _adsbygoogle.js_ If redirection fails in any chance, antiadblock detection occurs.

**Comment by gerwusa1823** [comment]
hm, that brings up another question though, wouldn't it be possible to stop these two scripts above from even running to begin with, so the detection would never even get a chance to run to begin with?

**Comment by uBlock-user** [comment]
>  so the detection would never even get a chance to run to begin with?

Race condition, the scripts are placed very early in the source page accessible via `view-source:`, you can try though -- 

```
falixnodes.net##+js(acis, $, Promise)
falixnodes.net##+js(acis, document.createElement, data-ad-client)
```

**Comment by gerwusa1823** [comment]
that worked

**Comment by stephenhawk8054** [comment]
Anti-adblock is back.

URL:
`https://panel.falixnodes.net/auth/login`

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.40.8
Firefox: 96
filterset (summary): 
  network: 78163
  cosmetic: 40678
  scriptlet: 16442
  html: 615
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30832-30, 31m
    ublock-badware: 3805-1, 31m
    ublock-privacy: 194-0, 31m
    ublock-abuse: 76-0, 31m
    ublock-unbreak: 1706-0, 31m
    easylist: 63364-591, 31m
    easyprivacy: 26666-480, 31m
    urlhaus-1: 6832-0, 31m
    plowe-0: 3679-2, 31m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 714 ms
popupPanel: 
  blocked: 1
```
</details>

Proposed filter:

`falixnodes.net##+js(no-xhr-if, securepubads)`

**Comment by gunawan092w** [comment]
2024-05-10 - client.falixnodes.net remove script onloadcheck(). which redirects to /disableadblock if adblock detected

```client.falixnodes.net##+js(remove-node-text, script, /onloadcheck|_0x/)```
