### ISSUE TITLE
Yandex disk no image issue

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uAssets#8965]
### URL(s) where the issue occurs

`https://disk.yandex.com/`

### Describe the issue

Yandex disk won't show images with uBlock enabled

### Screenshot(s)

Added

### Versions

- Browser/version: Brave version 1.23.73 Chromium: 90.0.4430.85 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.34.0

![Screenshot 2021-04-26 175931](https://user-images.githubusercontent.com/18757054/116114283-81b1b600-a6b9-11eb-8e52-75939088397c.jpg)

**Comment by uBlock-user** [comment]
Disable Brave's built-in adblocker, and try again.

**Comment by mapx-** [comment]
switch OFF all shields (there are lot of pages with such issues) for that site

![image](https://user-images.githubusercontent.com/10303732/116117290-5a101d00-a6bc-11eb-91f1-1823bb66b32b.png)

**Comment by GKid94** [comment]
I did turn off the shields and it still doesn't work, try this link https://disk.yandex.com/i/YpBFohvWSZaCoQ

**Comment by dimisa-RUAdList** [comment]
Try adding to "My Filters": `yandex.com#@#.content_ads`

**Comment by mapx-** [comment]
yeah needing `disk.yandex.com#@#.content_ads`

@ryanbr

**Comment by dimisa-RUAdList** [comment]
Fix: https://github.com/easylist/ruadlist/commit/782fe00cab71a9579a0a608720310c2eb9963a1e

**Comment by mapx-** [comment]
maybe it would be better to be fixed by @ryanbr in EL (yandex disk could be used by english people too ?!)

**Comment by dimisa-RUAdList** [comment]
Ok, I will remove the exception from the RuAdList filter when it is added to the EasyList.

**Comment by GKid94** [comment]
I updated the filter list and I still don't see the image
