### ISSUE TITLE
Babiato site breakage

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#8966]
Before i explain what i found, first i want to explain why i creating this...
on past few days i complaining about messages system on babiato not working
and yeah... that's problem appear on me when reply someone messages

and when i send messages on logger i see this
![image](https://user-images.githubusercontent.com/29838157/116131448-9b252300-a6f6-11eb-9234-4c67c8779929.png)
can you add those 2 last query to exception?
that's not ads...
that's is some code to send messages i belive

i really sure about this....
when i click send... those last query appear...

i hope someone can fix this
thanks

Note
I REALLY SURE, because when i turned off ublock
i can continue to send some messages to other's people
recently some contributor check it and all things seems fine
but idk why, this problem continue to appear on me
i also try to reinstall the ublock. and the best things i can do for now is turned off ublock and then send messages and turn on it again

**Comment by Dhanamerdeka** [comment]
i send messages with https://babiato.co/conversations/adsense.46850/#convMessage-267216
but since messages different for every person... 
maybe it's says adsense so the ublock blocked it

**Comment by uBlock-user** [comment]
@ryanbr broken by `/adsense.$~script,domain=~adsense.az|~adsense.googleblog.com` in EasyList
