### ISSUE TITLE
History.com Anti-AdBlock Message

### ISSUE THREAD

**Issue by participationaward** [uBlockOrigin/uAssets#8967]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X ] I tried to reproduce the issue when...
    - [X ] uBlock Origin is the only extension
    - [X ] uBlock Origin with default lists/settings
    - [ X] using a new, unmodified browser profile
- [X ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://play.history.com/shows/pawn-stars/season-18/episode-12`

### Describe the issue

Pop Up that says: It's not you...
It's your ad blocker.
To continue watching video, please disable your ad blocking software and reload the page. For instructions,click here.

### Versions

- Browser/version: Chrome
- uBlock Origin version: Latest Release Build

**Comment by MattMills** [comment]
`@@||history.com^$ghide` fixes this, same as here, different domain: https://github.com/uBlockOrigin/uAssets/issues/8962

**Comment by participationaward** [comment]
> 
> 
> `@@||history.com^$ghide` fixes this, same as here, different domain: #8962

This worked perfectly, thank you.

**Comment by snowsign** [comment]
> `@@||history.com^$ghide` fixes this, same as here, different domain: #8962

Does not appear to work as of 12/15/21 (Chrome 94.0.4606.124).
