### ISSUE TITLE
revistavanityfair.es / Anti Adblock  & "Break"

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#8968]
### URL(s) where the issue occurs

`https://www.revistavanityfair.es/`

### Describe the issue

Anti Adblock ( you can close the notice but , the images is break )

### ANTIADBLOCK
![Capturaqwe](https://user-images.githubusercontent.com/33556647/116161397-fb669580-a6f3-11eb-8a95-68d12c8c5b96.PNG)

### Settings

- Browser/version: [Chrome]
- uBlock Origin version: [1.34.0]

![Capturaa](https://user-images.githubusercontent.com/33556647/116161272-c22e2580-a6f3-11eb-8d3a-427578d8b7bd.PNG)

**Comment by uBlock-user** [comment]
> but , the images is break

Doesn't happen on default settings, likely caused by Cookie list or AdGuard Annoyances list.

**Comment by PIZZA90** [comment]
this issue continues:

![Capturaa](https://user-images.githubusercontent.com/33556647/117737604-7a7ec200-b1fa-11eb-9d27-5801cb7f9dd6.PNG)
