### ISSUE TITLE
watchmyexgf.net ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#897]
URL(s) where the issue occurs

https://www.watchmyexgf.net/videos/32220/with-giant-tits-like-that-you-know-she-loves-getting-choked/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
ads
