### ISSUE TITLE
badass downloader blocked on chrome

### ISSUE THREAD

**Issue by natemust** [uBlockOrigin/uAssets#8972]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://badassdownloader.com/`

### Describe the issue

when trying to download from the site it displays a message blocking access

### Screenshot(s)

https://imgur.com/a/519Pvn7

### Versions

- CHROME Version 85.0.4183.102 (Official Build) (64-bit)
- uBlock Origin v1.34.0

### Settings

i have made no changes
-

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled.
