### ISSUE TITLE
allestoringen.*, allestörungen.*, downdetector.* - blocked load disqus comments

### ISSUE THREAD

**Issue by strict-block** [uBlockOrigin/uAssets#8974]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

direct url as example:

`https://downdetector.co.uk/status/000webhost/`

I suppose almost all domains from group `downdetector`:

```
allestoringen.be
allestoringen.nl
```
```
allestörungen.at
allestörungen.ch
allestörungen.de
```

<details> <summary> long list <code>downdetector.*</code></summary>

```
downdetector.ae
downdetector.ca
downdetector.cl
downdetector.co.nz
downdetector.co.uk
downdetector.co.za
downdetector.com
downdetector.com.ar
downdetector.com.au
downdetector.com.br
downdetector.com.co
downdetector.cz
downdetector.dk
downdetector.ec
downdetector.es
downdetector.fi
downdetector.fr
downdetector.gr
downdetector.hk
downdetector.hr
downdetector.hu
downdetector.id
downdetector.ie
downdetector.in
downdetector.it
downdetector.jp
downdetector.mx
downdetector.my
downdetector.no
downdetector.pe
downdetector.ph
downdetector.pk
downdetector.pl
downdetector.pt
downdetector.ro
downdetector.ru
downdetector.se
downdetector.sg
downdetector.sk
downdetector.web.tr
```

</details>

### Describe the issue

Problem may need use VPN to mask as EU country.

---

No possible load Disqus comments due block `doubleclick.net` by:

1. **Peter Lowe** or _Polish regional_ **stock** list.

    bad are: https://github.com/uBlockOrigin/uAssets/blob/1de71bed4c143140c9212b51d4948baaf65e3b40/thirdparties/pgl.yoyo.org/as/serverlist#L1641

    converted into `||doubleclick.net^`

2. Later by EasyList:
 
    `||g.doubleclick.net^` from EasyList: https://github.com/uBlockOrigin/uAssets/blob/1de71bed4c143140c9212b51d4948baaf65e3b40/thirdparties/easylist-downloads.adblockplus.org/easylist.txt#L45039

    and later `/securepubads.` or `/pubads_` - also from EasyList.

---

In this submission, we do not analyze that hiding the GPDR pop-up is out of scope the repository rules - Peter Lowe does not provide permission to allow load `doubleclick.net` or use `redirect-rule`.

*In the future, these can be retired as EasyList will allow the script to load and there will be no benefit from `redirect-rule`.*

### Screenshot(s)

frozen on:

![obraz](https://user-images.githubusercontent.com/79422224/116333030-14924380-a7d3-11eb-9e46-0fdcb27ad75d.png)

### Versions

- Browser/version: Firefox 88
- uBlock Origin version: 1.35.0

### Settings

- stock

### Notes

Maybe fix with `redirect-rule` or allow load file:

```
||securepubads.g.doubleclick.net/gpt/pubads_*.js$script,domain=allestoringen.*|allestörungen.*|downdetector.*,redirect-rule=googletagservices_gpt.js
```

```
@@||securepubads.g.doubleclick.net/gpt/pubads_*.js$script,domain=allestoringen.*|allestörungen.*|downdetector.*
```

**Comment by okiehsch** [comment]
@BPower0036 for your list
`@@||securepubads.g.doubleclick.net/gpt/pubads_*.js$script,domain=allestoringen.*`

**Comment by krystian3w** [comment]
In Chromium again load fancy interface and add comment function down:

```
https://downdetector.pl/status/vectra/
```

On my PC works:

```adb
! override EP:
||doubleclick.net/pagead/managed/js/gpt$script,important,domain=allestoringen.*|allestörungen.*|downdetector.*
! tmp works redirect-rule:
||doubleclick.net/pagead/managed/js/gpt$script,domain=allestoringen.*|allestörungen.*|downdetector.*,redirect-rule=googletagservices_gpt.js:5
```
