### ISSUE TITLE
hclips.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#898]
URL(s) where the issue occurs

https://www.hclips.com/videos/my-dirty-hobby-redhead-bbw-queen-of-asses/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
@mapx- ADS video
