### ISSUE TITLE
Anti-adblock icttipsandtricks.nl

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uAssets#8984]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://www.icttipsandtricks.nl/2021/04/16/nvidia-stel-je-voorkeurs-vga-kaart-in-per-applicatie/`

### Describe the issue
Anti-adblock detected

### Screenshot(s)
Before:
![image](https://user-images.githubusercontent.com/80090789/116567379-db0f2480-a907-11eb-8002-bf69b64fbb9f.png)
After:
![image](https://user-images.githubusercontent.com/80090789/116567525-fed26a80-a907-11eb-9808-1e929acdb354.png)

### Versions

- Browser/version: [Edge 90.]
- uBlock Origin version: [1.35.0]

### Notes
In uBlock filters the filter `icttipsandtricks.nl#@#+js(acis, jQuery, ai_adb)` didn't work, I used `icttipsandtricks.nl#@#+js(acis, jQuery, ai_adb)` to test the following rule.
So I added to [EasyDutch](https://github.com/BPower0036/AdBlockFilters/blob/main/EasyDutch/Anti-Adblock.txt) this rule which seems to work: `icttipsandtricks.nl##+js(aopw, jQuery, ai_adb)`

**Comment by BPower0036** [comment]
If both `icttipsandtricks.nl#@#+js(acis, jQuery, ai_adb)` and `icttipsandtricks.nl##+js(aopw, jQuery, ai_adb)` are used. It doesn't work.

**Comment by uBlock-user** [comment]
@BPower0036 If you already fixed it in EasyDutch, why open the issue here ?

**Comment by uBlock-user** [comment]
`icttipsandtricks.nl##+js(aopw, jQuery, ai_adb)` will break site and is syntactically wrong.

**Comment by BPower0036** [comment]
> If both `icttipsandtricks.nl#@#+js(acis, jQuery, ai_adb)` and `icttipsandtricks.nl##+js(aopw, jQuery, ai_adb)` are used. It doesn't work.

Because both enabled didn't work.

**Comment by uBlock-user** [comment]
Remove both, fixed in ublock main list now.
