### ISSUE TITLE
https://answers.microsoft.com/en-us/newthread

### ISSUE THREAD

**Issue by emilio** [uBlockOrigin/uAssets#8985]
(Reported from https://bugzilla.mozilla.org/show_bug.cgi?id=1708214)

### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`
https://answers.microsoft.com/en-us/newthread` (needs login)

### Describe the issue

Only the first dropdown at the bottom appears (Category), while normally, once you select one there are other dropdowns appearing like Version or what not.

### Versions

- Browser/version: Firefox Nightly and Firefox 88.0
- uBlock Origin version: 1.35.0

### Settings

- None

### Notes

This is the relevant exception:

```
Uncaught ReferenceError: oneDSWeb is not defined
    CapturePageAction https://answersstaticfilecdnv2.azureedge.net/static/js/bundle/bundle.core.1.0.3.80.min.js:1
    onForumSelectChange https://answersstaticfilecdnv2.azureedge.net/static/js/bundle/bundle.newthread.1.0.3.80.min.js:1
    setEventHandler https://answersstaticfilecdnv2.azureedge.net/static/js/bundle/bundle.newthread.1.0.3.80.min.js:1
    jQuery 2
```

oneDSWeb relies on oneDS, which is defined in `https://js.monitor.azure.com/scripts/c/ms.analytics-web-2.min.js.`

**Comment by uBlock-user** [comment]
Add `@@||js.monitor.azure.com/scripts/c/ms.analytics-web-2.min.js^$script,domain=answers.microsoft.com` to my Filters and report back.

**Comment by emilio** [comment]
Yep, that fixes it as expected.
