### ISSUE TITLE
Notices to accept cookies on https://www.facebook.com/ https://www.google.es/ https://www.youtube.com/ (and login)

### ISSUE THREAD

**Issue by Jose1971AB** [uBlockOrigin/uAssets#8989]
### Prerequisites
Hello friends. Sorry folks, I'm with the help of a translator, so I don't quite understand the prerequisites section. I will see what I can do.

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ X] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

```
https://www.facebook.com/
https://www.google.es/
https://www.youtube.com/
```
### Describe the issue

 
On `https://www.facebook.com/`
Notice to accept cookies and sponsored advertising (see screenshot). 
You will notice in the screenshot that it is the red box, I do not know if this advertising can be removed but if not it would not affect me so much, I am more interested in removing the notice to accept cookies.

Warning to accept cookies when opening `https://www.google.es/` (see screenshot) 

`https://www.youtube.com/`
Notice to accept cookies and central login box (see screenshot) 

### Screenshot(s)

1.- `https://www.google.es/`

![1-Google](https://user-images.githubusercontent.com/44229110/116779280-afaa4800-aa75-11eb-9cff-19504d31f893.png)

2.- `https://www.facebook.com/`

![Aviso de cookies y publicidad en Facebook](https://user-images.githubusercontent.com/44229110/116779320-ef712f80-aa75-11eb-8df6-744ab36152a5.jpg)

3.- `https://www.youtube.com/` (There are two)

- Notice to accept cookies
![2-Antes de ir a  YouTube](https://user-images.githubusercontent.com/44229110/116779385-758d7600-aa76-11eb-8b6b-89646bb82dcf.png)

- Login Announcement
![3-Al entrar en YouTube](https://user-images.githubusercontent.com/44229110/116779399-8938dc80-aa76-11eb-96f7-d4f812e46ae0.png)

### Versions

- Browser/version: [Firefox 64 Bits/88.0.0]
- uBlock Origin version: [1.35.0]

### Settings

uBlock Origin
![2](https://user-images.githubusercontent.com/44229110/116779219-4cb8b100-aa75-11eb-997d-66590fa2f72b.jpg)

**Comment by uBlock-user** [comment]
https://www.reddit.com/r/uBlockOrigin/wiki/solutions

**Comment by krystian3w** [comment]
Possible use project addon **I don't care about cookies** if you clear cookies in browser "daily".

**Comment by Jose1971AB** [comment]
Thank you very much for answering friends... @uBlock-user @krystian3w 

**Unfortunately only the I don't care about cookies extension and two filters for Facebook ads/marketplace work for me. Let me explain...**

**I don't know what to try anymore, I've tried all the filters**, the ones you offer me in this forum and the ones from `https://www.reddit.com/r/uBlockOrigin/wiki/solutions`... **I've been trying all afternoon and I don't know what to do anymore.** 

(I could list all the filters I have tried but it would be a very long message. Each and every one of those that you offer me in this forum and those of `https://www.reddit.com/r/uBlockOrigin/wiki/solutions`)

I don't know if I've done it right, **but I think I've done it as indicated in the link you sent me** (`https://www.reddit.com/r/uBlockOrigin/wiki/solutions`), **only the warning to accept cookies for google works.**

**On YouTube nothing works, neither for the notice to accept cookies nor for the login box**. I have set the filter `youtube.com##+js(set, yt_logging_screen, undefined)` for the login prompt and it only works for the main page, because if you go directly to a video sometimes it appears and sometimes not.

For YouTube I have also tried what it says on `https://www.reddit.com/r/uBlockOrigin/comments/mh2su3/` but it doesn't work either. 

**For Facebook I haven't found anything on** `https://www.reddit.com/r/uBlockOrigin/wiki/solutions` **about removing the notice to accept cookies**, I have only found two filters for the ads on the right side and Marketplace which seems to be working for the moment, although I would have to try more.

**Please, I would appreciate if you could give me a solution, I use YouTube and Facebook a lot and it is really tiring**.

Let's see if you can think of a custom filter or something and you could tell me how and where to include it, **I'm a basic user and despite the help of the translator I find it hard to understand**.

**Couldn't it be solved with filters instead of using the I don't care about cookies extension?... it would be much better with filters**. Let's see if you can think of a custom filter or something and you could tell me how and where to include it, **I'm a basic user and despite the help of the translator I find it hard to understand**.

I have noticed that **with the extension the page loading is a bit delayed**, for a moment it goes blank until it loads. This happens mostly on Facebook. On YouTube, for example, the notice to accept cookies appears for a moment and then disappears. **That's why I'm asking if it's possible to solve it with filters instead of the extension**.

Thank you very much and best regards...

**Comment by uBlock-user** [comment]
`google.com,facebook.com,youtube.com##+js(set, navigator.cookieEnabled, false)`

does that work ?

**Comment by krystian3w** [comment]
Facebook may no use `navigator.cookieEnabled` to show pop-up - is still visible.

Facebook need something to simulate error with loaded pop-up to unlock load infinity posts on homepage "wall"/"table". without accept infinity load post is broken.

**Comment by krystian3w** [comment]
Google still need someting other than `+js(set, navigator.cookieEnabled, false)` to disable cookie-wall sudomains:

`//consent.google.com/m?continue=`
`//consent.youtube.com/m?continue=`

Maybe Joe like use google maps (have cookie wall) or search news as results (also hidden by cookie wall):

`https://www.google.com/search?q=left&tbm=nws`

**Comment by Jose1971AB** [comment]
Hola **@uBlock-usuario** @krystian3w

Let's see @krystian3w... I'm going to go in parts in order to be as less confusing as possible, in the order of your answers.

**First**

> Facebook may no use navigator.cookieEnabled to show pop-up - is still visible for guest and logged users (have account).
> Facebook need something to simulate error with loaded pop-up to unlock load infinity posts on homepage "wall"/"table". without accept infinity load posts are broken:

Let's see if I didn't get confused between so many tests.... Now I have disabled the extension and in addition to the two filters that work for me (see my previous message) I have added the one sent to me by @uBlock-user, but it doesn't work, that is, I only have these three... 

**youtube.com##+js(set, yt_logging_screen, undefined)** --> for YouTube login.

**facebook.com##div[role="complementary"] > div > div > div > div > div > div > div > span** --> for Facebook ads/marketplace.

**google.com,facebook.com,youtube.com##+js(set, navigator.cookieEnabled, false)** --> the new one that @uBlock-user sends me.

**Maybe I need to add some more?.... because only with those three it doesn't work**.

**Second**

> Google still need someting other than +js(set, navigator.cookieEnabled, false) to disable cookie-wall sudomains:
> //consent.google.com/m?continue=
> //consent.youtube.com/m?continue=
> Maybe "Jose" like use google maps (have cookie wall) or search news as results (also hidden by cookie wall):
> https://www.google.com/search?q=left&tbm=nws
> Disable clear cookies for google domains/subdomains and logon to "Gmail" also good disable cookie pop-up and subdomain cookie walls.
> Addon IDCAC use click method because system "I accepted cookie/privacy policy" use no readable+unique cookies/localStorage/sessionStorage.

The two filters you are sending me now I have tried them in the My Filters tab and they don't work. I don't quite know how to do it and what you mean, sorry.

Excuse me my friend, but I must leave you, I have to go to work. I'll continue tomorrow.

Regards and thanks

**Comment by Jose1971AB** [comment]
Hello friends again, **@uBlock-usuario** @krystian3w good afternoon....

Well nothing... I do not know what to do, through filters I can not remove the consent to accept cookies.

**The only thing that works for me at the moment is the extension I don't care about cookies and two filters...**

```
youtube.com##+js(set, yt_logging_screen, undefined)
facebook.com##div[role="complementary"] > div > div > div > div > div > div > div > span
```

**Can you think of anything other than the extension...? any filter?....**

Best regards and thank you very much
