### ISSUE TITLE
Can I report related to AdguardTeam/AdguardFilters Issues?

### ISSUE THREAD

**Issue by avotoko** [uBlockOrigin/uAssets#8991]
I enjoy parsing the anti adblock script.
 Some of the problems reported in the AdguardTeam/AdguardFilters Issues are also reproduced by uBlock Origin.
Can I report the filter that solves it here with the url to the AdguardFilters Issues?

**Comment by uBlock-user** [comment]
Yes.

**Comment by krystian3w** [comment]
Or anonymus by https://agrd.io/report
