### ISSUE TITLE
Chatango script fails to execute

### ISSUE THREAD

**Issue by panicfarm** [uBlockOrigin/uAssets#8992]
### Prerequisites

- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x ] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

http://web24.chatango.com/demo.html

### Describe the issue
This is an example of the embeddable Chatango chat in a third party web page. Chatango chats have over 400 million pageviews per month.
When uBlockOrigin is disabled, clicking on Set Name in the lower right corner produces a login dialog. When it's enabled, no login dialog comes up.

### Versions

- Browser/version: Chrome/90.0.4430.93
- uBlock Origin version: 1.34.0

### Notes

Clicking on Set Name downloads JavaScript from https://st.chatango.com/js/gz/rNNNNNN/LoginModule.js but uBlockOrigin stops the script from executing.

**Comment by llacb47** [comment]
It does not fail to execute, there is a bad cosmetic filter from Easylist. `st.chatango.com##.sdlg-main-cbdr-cpbg`

**Comment by okiehsch** [comment]
Fixed in `EasyList`.
