### ISSUE TITLE
Anti-AdBlock -- MegaUp.net

### ISSUE THREAD

**Issue by StrawbarryVan** [uBlockOrigin/uAssets#8993]
### Prerequisites

- [ X ] This is not a support issue or a question
- [ X ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- [ X ] I tried to reproduce the issue when...
    - [ X ] uBlock Origin is the only extension
    - [ X ] uBlock Origin with default lists/settings
    - [ X ] using a new, unmodified browser profile
- [ X ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://megaup.net/2iIov/TEST.txt`

### Describe the issue

It happens on every file like the TEST one above. The page has a spinning thing for 5 seconds but, instead of showing the Download button, it prompts to turn off any AbBlocker.

I tried several browsers (Avast, Brave, Chrome, Firefox, Opera, and Vivaldi), all updated to the latest version, all with uBlock Origin as the only extension, and all show the same result.

### Screenshot(s)

![MegaUpNet](https://user-images.githubusercontent.com/81157283/116809736-7803d480-ab37-11eb-8256-04c67fbd5625.jpg)

### Versions

- Browser/version: Avast 90.0.9316.94 / Brave 1.23.75 / Chrome 90.0.4430.93 / Firefox 88.0 / Opera 76.0.4017.94 / Vivaldi 3.8.2259.37
- uBlock Origin version: v1.34.0 and v1.35.0

### Settings

Currently, it's all on Default, with only Regional filters for my language turned on. But I also tried turning on ALL options in Filter Lists, but that didn't change anything.
-

### Notes

After searching for this problem, I ended up on another Github page where someone created an Anti-AdBlock script with an offensive name (not sure if I can write it here). Regardless, it didn't work. I also tried installing GreaseMonkey and TamperMonkey to try an older Anti-AdBlock script (anti-adblock-killer) but it did nothing.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0399098d88aababe79f1250f088596a2a1187e97

did you force update ublock filters list ?

**Comment by Felipefpl** [comment]
the same problem happens here http://www.ovagames.com/

**Comment by Dhanamerdeka** [comment]
working good on me
![image](https://user-images.githubusercontent.com/29838157/116812513-47dd2580-ab79-11eb-9291-82e464a29d7a.png)

**Comment by uBlock-user** [comment]
> the same problem happens here http://www.ovagames.com/

Working as expected, open a new issue if you see anti-adblock
