### ISSUE TITLE
[Breakage] Tweakers.net images and videos in articles

### ISSUE THREAD

**Issue by kellyz73** [uBlockOrigin/uAssets#8994]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
    - [X] disabling uBlock
    - [X] disabling specific filter rule
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

```
https://tweakers.net/reviews/8954/all/draadloze-gaming-headsets-voor-de-nieuwe-generatie-consoles.html
https://tweakers.net/reviews/8974/de-beste-beeldinstellingen-voor-je-tv.html
https://tweakers.net/nieuws/181140/microsoft-edge-krijgt-functie-om-tabbladen-te-delen-tussen-windows-en-android.html
```

### Describe the issue

In articles on Tweakers.net images and video's do not show anymore. In some cases 'placeholders' are visible.

### Screenshot(s)

Missing video:
![image](https://user-images.githubusercontent.com/83537700/116810986-1f3c3800-ab47-11eb-8ad6-8816c867953a.png)

No images:
![image](https://user-images.githubusercontent.com/83537700/116810996-324f0800-ab47-11eb-925a-9e43995f3f60.png)

### Versions

- Browser/version: Firefox 88.0
- uBlock Origin version: v1.35.0

### Settings

- Default

### Notes

It seems to be the rule that was added here: https://github.com/uBlockOrigin/uAssets/commit/788d7dcea1e4dfc6fb189e14e96e05d548559934
When I add this as a custom rule it works again:

`tweakers.net#@#+js(aost, JSON.parse, inlineScript)`

According to the developer on the forum (see `https://gathering.tweakers.net/forum/list_message/67143528#67143528` - in Dutch) the mentioned rule causes a piece of script not to be executed anymore:

`if(window.LazyLoadImages)LazyLoadImages.init();`

**Comment by uBlock-user** [comment]
That was added to disable their ad-resinertion crap script AdDefend, they saw the rule and now they're intentionally sabotaging thir site ;)

**Comment by mapx-** [comment]
yes, 
`if(window.LazyLoadImages)LazyLoadImages.init();` was added in the same adddefend inline script on purpose to break functionalities on site

**Comment by crisp-tweakers** [comment]
I can assure you that we have not made any changes to our site.

**Comment by uBlock-user** [comment]
`view-source` never lies.

**Comment by mapx-** [comment]
> I can assure you that we have not made any changes to our site.

not now. You should separate the horrible addefend from your own functionalities in that inline script.

**Comment by rjgotten** [comment]
Makes me wonder: how long until uBO starts shipping a JS rewriter to forcibly spoon out the AdDefend stuff?
This is an arms race where there are only losers.
