### ISSUE TITLE
[Anti adblock] my.pornobit.me

### ISSUE THREAD

**Issue by avotoko** [uBlockOrigin/uAssets#8995]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
[NSFW] `https://my.pornobit.me/videos/242859/u-nachalnika-v-kabinete-seks-v-ofise-s-grudastoy-sekretarshey/`

### Describe the issue
The anti-adblock message will appear a few seconds after the video starts playing.
 

### Versions

- Browser/version: Firefox 88.0
- uBlock Origin version: v1.35.0

### Settings

default

### Notes

filter to resolve the issue.
`pornobit.mobi##+js(nostif, offsetWidth<1)
`

**Comment by uBlock-user** [comment]
fixed in RuAdlist, regional sites usually get fixed in regional lists.
