### ISSUE TITLE
Bug popup appear again Hiperdex

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#8996]
`https://hiperdex.com/`
well. the problem like what i write on the title...

some popup appear again,

**Comment by Dhanamerdeka** [comment]
eh wait...
unable to reproduce?

well... i have this problem on firefox
does you check it with firefox?

**Comment by okiehsch** [comment]
No popups using Firefox on my end.

**Comment by Dhanamerdeka** [comment]
eh really?
on my side, there's new popup appear...
the link different from last time i reported this...
(link popup)


hmmmmm

**Comment by okiehsch** [comment]
I get a popup if I disable `uBO-filters`, so 
`hiperdex.com##^script:has-text({}.constructor)`
which I added to fix https://github.com/uBlockOrigin/uAssets/issues/8881 still works for me.

**Comment by Dhanamerdeka** [comment]
i haven't tested on chrome yet
but on firefox this things still appear

i will check it again at 18.00 GMT+7

**Comment by uBlock-user** [comment]
You should fill the template for once, you always skip that.

**Comment by Dhanamerdeka** [comment]
so i need to make some custom template?
on past issue you add some of this
||ejyrabeonmyh.com^$3p
||ptcqjliwwkldm.com^$3p

and what i think is, the sites changed
umm is that not a problem?
i mean...

like....
we should add other link too to prevent the popup?

**Comment by okiehsch** [comment]
> on past issue you add some of this

I also added this
`hiperdex.com##^script:has-text({}.constructor)`
and that still works.

**Comment by Dhanamerdeka** [comment]
hello it's me again
hmmm i check the ublock with chrome it working good
no popup or whatever
but when i tested it with firefox the popup still there...

idk why.... i have no idea where its coming from
but i think this is bug or just for me maybe
because sometime the popup appear and sometime popup don't....

maybe we can close this issue?
