### ISSUE TITLE
[Anti adblock] promo-visits.site

### ISSUE THREAD

**Issue by avotoko** [uBlockOrigin/uAssets#8997]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://promo-visits.site/iMXGT`

### Describe the issue
Aniti-adblock message appears and I cannot proceed.
 

### Screenshot(s)

![screenshot](https://user-images.githubusercontent.com/53560467/116822038-b2ad5180-abb7-11eb-9888-28a9835eb717.jpg)
### Versions

- Browser/version: Firefox 88.0
- uBlock Origin version: v1.35.0

### Settings

default

### Notes

filter to resolve the issue.
`promo-visits.site##+js(aopr, app_vars.force_disable_adblock)
`

**Comment by uBlock-user** [comment]
Avoid posting clickable urls, put it between the backticks  ``

**Comment by avotoko** [comment]
I understand.
and prevent popups.
```
promo-visits.site##+js(nosiif, blockClick)
promo-visits.site##+js(ra, onclick, button[type="submit"])

```

**Comment by uBlock-user** [comment]
popups also fixed in https://github.com/uBlockOrigin/uAssets/commit/fe983e49e0960126996db02b071f75cde17d7292

**Comment by stephenhawk8054** [comment]
Another anti-adblock appears.

URL: `https://promo-visits.site/iMXGT`

![image](https://user-images.githubusercontent.com/66517106/139777532-299ae7c7-35ac-4eeb-8bf3-7fa0ae060b9d.png)

Firefox 93, ublock 1.38.6 default.

Proposed filter:

`@@||promo-visits.site^$ghide`
