### ISSUE TITLE
sembilhete.tv

### ISSUE THREAD

**Issue by SW1FT** [uBlockOrigin/uAssets#9]
### Describe the issue

sembilhete.tv is using "fuckadblock" to insert an annoying anti-adb notice. 
Using `sembilhete.tv##script:inject(fuckadblock.js-3.2.0)` fixes this.

### One or more specific URLs where the issue occurs

sembilhete.tv

### Screenshot(s)

![fabsb](https://cloud.githubusercontent.com/assets/6627739/14412062/873b1d24-ff51-11e5-98ab-59b39b1f6342.png)

### Your settings

- Browser/version: Mozilla Firefox Dev Edition 47.0a2
- uBlock Origin version: 1.6.9

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
