### ISSUE TITLE
pikabu.ru

### ISSUE THREAD

**Issue by zummuz** [uBlockOrigin/uAssets#90]
### URL(s) where the issue occurs

http://pikabu.ru/

### Describe the issue

This site actively avoids ad blocking by changing element's properties as soon as they are added to the list (a pinned post at the top of a main page), and also has ads which are impossible to hide with regular selectors 

### Screenshot(s)

Top pinned post:
![1](https://cloud.githubusercontent.com/assets/13698274/17370542/783de5f2-59ad-11e6-8edd-db40a25eb4b5.png)

Clean cookies, go to the main page, press End - it should scroll just to the hard ad (or ctrl+F for 'спонсор')
![screenshot from 2016-08-03 18-41-45](https://cloud.githubusercontent.com/assets/13698274/17371954/faaa87ca-59b2-11e6-900f-a80ed3acfb81.png)

... autoloading new posts, again to the End for the second ad
![screenshot from 2016-08-03 18-41-58](https://cloud.githubusercontent.com/assets/13698274/17372013/2079ccf4-59b3-11e6-84cc-8acec1e67a03.png)

### Versions

- Browser/version: FF 47
- uBlock Origin version: 1.8.1b0 and older

### Settings

- Almost default +    
 RUS: BitBlock List (Дополнительная подписка фильтров)‎     
RUS: RU AdList (Дополнительная региональная подписка)‎   

### Notes

Looks like `pikabu.ru##.story:has(a[href*='pikabu.ru/html.php?id=ad'])` hides all this ads

**Comment by gorhill** [comment]
On my side I do not see the ads, the filter `pikabu.ru##.page-story` from RU Adlist is taking care of them.

**Comment by zummuz** [comment]
Yesterday, ad at the top was hidden with `pikabu.ru##td[style] > div[style] > .story` 
Like 5 hours ago it was `pikabu.ru##.story_perm` 
`pikabu.ru##.page-story` was added a few hours ago    

When I reload the page I don't see the 2nd and the 3rd ads. I can make the 2nd ad appear by opening that site in incognito window, I don't see the 3rd ad right now though

**Comment by gorhill** [comment]
I disabled RUAdlist and Bitblock. I do not understand Russian, but I think the `.page-story`-based filter is breaking the site: when I click on an entry, the top post -- the story -- is being hidden by the filter -- surely it should not be.

I am completely unable to get the ads except for the top one.

The filter you suggest seems saner, so I will add it to uBlock's filters, and the maintainers of RUAdlist will have to fix their own filter if it does break stuff.

**Comment by zummuz** [comment]
Okay, thanks 
If you click at the right of the title (areas on the screenshot below) the post's body is supposed to be minimised to the title only, so its not a breakage, if we are talking about the same thing
Also you can see that the filter should hide this ads
![screenshot from 2016-08-03 22-01-33](https://cloud.githubusercontent.com/assets/13698274/17378950/280087a6-59d1-11e6-8ee3-64f4730a6ebc.png)

**Comment by bibikot** [comment]
Злобные пикабушники и сюда добрались без мыла... ))
