### ISSUE TITLE
Xhamster Videos not playing on Firefox for Android

### ISSUE THREAD

**Issue by N8Z7JMYLU** [uBlockOrigin/uAssets#9000]
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x ] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.xhamster.com/` - any video

This is an issue that is specific to the new Android version of Firefox. The classic (v68) and desktop versions are not affected.

No videos are playing if uBlock filters are enabled. One of these filters is the culprit:

```
xhamster.*##[class*="-vspot-container"]
xhamster.*##+js(addEventListener-defuser, , pop)
xhamster.*##+js(abort-on-property-read, wih-popunder)
xhamster.*##+js(abort-current-inline-script, Array.protoype.indexOf, popunder)
xhamster.*##^script:has-text(window.initials)
```

### Versions

- Browser/version: Firefox Beta for Android 89.0.0-beta3
- uBlock Origin version: 1.35.0

**Comment by uBlock-user** [comment]
Add `xhamster.*#@#^script:has-text(window.initials)` and report back.

**Comment by N8Z7JMYLU** [comment]
That exception rule solves it. Thanks.

**Comment by mapx-** [comment]
update uBlock filters list, it was replaced by another filter
