### ISSUE TITLE
scam/scummy website

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9003]
I do not assume responsability for what may or may not happen if you visit any website or webpage.

proof:
![image](https://user-images.githubusercontent.com/83162792/116827764-6e17bb00-aba3-11eb-8750-622a3357c9f3.png)
![image](https://user-images.githubusercontent.com/83162792/116827783-81c32180-aba3-11eb-9bcf-4dc0dc621830.png)

**Comment by mapx-** [comment]
@IThinkIAmCool lastly you don't post any link, only screenshots. **We need links and an explanation** !
