### ISSUE TITLE
[Anti adblock] seriesdonghua.com

### ISSUE THREAD

**Issue by avotoko** [uBlockOrigin/uAssets#9005]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://seriesdonghua.com/`

### Describe the issue

The anti-adblock message appears and I cannot browse the content.

### Screenshot(s)

![screenshot](https://user-images.githubusercontent.com/53560467/116842038-15353a80-ac16-11eb-9d8d-caf302792a8c.jpg)

### Versions

- Browser/version: Firefox 88.0
- uBlock Origin version: v1.35.0

### Settings

default

### Notes

filter to resolve the issue.
`seriesdonghua.com##+js(nostif, /aadb_recheck|Tamamo_Blocker/)
`

**Comment by uBlock-user** [comment]
fix present in AdGuard Spanish/Portuguese.
