### ISSUE TITLE
[Anti adblock] www.mta-resource.ru

### ISSUE THREAD

**Issue by avotoko** [uBlockOrigin/uAssets#9007]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.mta-resource.ru/load`

### Describe the issue

The anti-adblock message appears and I cannot browse the page.

### Screenshot(s)

![screenshot](https://user-images.githubusercontent.com/53560467/116845181-14a1a180-ac20-11eb-8812-116bd47522bd.jpg)

### Versions

- Browser/version: Firefox 88.0
- uBlock Origin version: v1.35.0

### Settings

default

### Notes

filter to resolve the issue.
`mta-resource.ru##+js(set,isMeowMeowHidden, falseFunc)
`

**Comment by uBlock-user** [comment]
fixed in RUAdlist list.
