### ISSUE TITLE
stopped working on Hulu in Chromium (Brave)

### ISSUE THREAD

**Issue by arderyp** [uBlockOrigin/uAssets#9008]
### Prerequisites

- [X ] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [X ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [X ] uBlock Origin is the only extension
    - [X ] uBlock Origin with default lists/settings
    - [X ] using a new, unmodified browser profile
- [X ] I am running the latest version of uBlock Origin
- [X ] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

UBO used to block adds on Hulu.  Now it doesn't.  I don't even see the well-known black screen about being unable to server ads, I actually see 3 minutes of video ads.

### A specific URL where the issue occurs

`https://www.hulu.com/watch/7eb35b57-9825-4b28-a076-74b5563a2327`

### Steps to Reproduce

1. log into Hulu
2. watch a video
3. see ads during ad breaks

### Expected behavior:

Ads are supressed, so no discernible ad breaks or dead space.

### Actual behavior:

See ads.

### Your environment

* uBlock Origin version: v1.34.0 
* Browser Name and version: Brave V1.23.75 
* Operating System and version: Ubuntu 20.04 (latest)

**Comment by uBlock-user** [comment]
Did you disable Brave's built-in blocker ? It's known to interfere with uBO's filters.

**Comment by lain566** [comment]
I can't reproduce any ads on hulu with Chrome/Firefox.

**Comment by arderyp** [comment]
I have tried disabling, no luck.  I will keep testing to see if I can get it to work.  I should note, the ads were not showing yesterday morning.  Then, yesterday night, they started appearing.  No updates were run in that time.

**Comment by arderyp** [comment]
the issue seems to have gone away spontaneously.  I can't figure it out, but no longer an issue.
