### ISSUE TITLE
tny.ec [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#901]
URL(s) where the issue occurs

https://tny.ec/2vxRZx

Describe the issue

anti-adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
anti-adblock
