### ISSUE TITLE
overzealous filters on tumblr.com partially breaks site

### ISSUE THREAD

**Issue by AprilSylph** [uBlockOrigin/uAssets#9010]
### Prerequisites

- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

-  `https://www.tumblr.com/dashboard`

### Describe the issue

3c8c3db5c8947588cc4b8bd8a602dc69142ba751 introduced some filters which breaks some features of the site.

1. Any post including the text " tags" is removed (including any post hidden by tag filtering), along with its proceeding post
2. Any post containing the text "Trending on" or "Check out " will be removed, along with their proceeding posts
3. The upper post element `div[tabindex="-1"]` is hidden when only the descendent `article` should be hidden; using a keyboard shortcut to scroll back to a post with a hidden `div[tabindex="-1"]` will instead scroll to the top of the page

1 and 2 are especially problematic considering that posts usually contain user-submitted text. 3 is extremely annoying when using keyboard shortcuts as the primary method of scrolling, especially when Tumblr's "endless scrolling" is enabled (which it is by default).

### Screenshot(s)

N/A

### Versions

- Browser/version: Firefox 88.0 (64-bit)
- uBlock Origin version: 1.35.0

### Settings

- N/A

### Notes

~~As far as I can see, the only filter that's actually needed from the problem commit is L2937, though it should be modified to only hide the descendant `article`.~~ While the recommended tag and blog carousels can be considered annoyances by some, they are not advertisements and should not be treated as such.

Apologies if any of this Tumblr-specific terminology is inappropriate/confusing, let me know if any elaboration is needed.

**Comment by uBlock-user** [comment]
@mapx-

**Comment by AprilSylph** [comment]
Playing around, it appears that EasyList now handles sponsored post containers correctly without any of the issues I described. None of the filters introduced by the problem commit need to be present in uBlock filters at all.
