### ISSUE TITLE
[Anti adblock] www.lcpdfr.com

### ISSUE THREAD

**Issue by avotoko** [uBlockOrigin/uAssets#9012]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.lcpdfr.com/`

### Describe the issue

The anti-adblock message appears at the top of the page.

### Screenshot(s)

![screenshot](https://user-images.githubusercontent.com/53560467/116948296-fb4d3380-acb9-11eb-955f-9b8a92346759.jpg)

### Versions

- Browser/version: Firefox 88.0
- uBlock Origin version: v1.35.0

### Settings

default

### Notes

filter to resolve the issue.
`lcpdfr.com##+js(aopr, FuckAdBlock)
`

**Comment by okiehsch** [comment]
That is already fixed in`uBO-annoyances`, we consider adblock messages that don't block access to the sites or a site functionality to be annoyances only.

**Comment by avotoko** [comment]
I understand.
