### ISSUE TITLE
[Anti Adblock] jaanmusic.in

### ISSUE THREAD

**Issue by Cyberavater** [uBlockOrigin/uAssets#9013]
Eg link: 
`https://a2zapk.com/417143-device-id-masker-pro-xposed-1-16-paid-a2z.html`

1. Click on Go to Download page
2. Click on Direct Download APK fromA2ZAPK

I can't directly share the links cause they are useless in different browsers.

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled + disable any built-in blocker of your browser.

**Comment by Cyberavater** [comment]
Well, I don't have any other blockers but I don't remember what filter I've selected that was unselected before, so I'm sending SS of currently selected filters.

![Screenshot (13)](https://user-images.githubusercontent.com/32187927/116970204-5d696100-acd9-11eb-8fce-ae351d1e8c9b.png)
![Screenshot (14)](https://user-images.githubusercontent.com/32187927/116970210-5fcbbb00-acd9-11eb-87a7-414a2d248cba.png)
![Screenshot (15)](https://user-images.githubusercontent.com/32187927/116970212-61957e80-acd9-11eb-941a-c035ac9c6e68.png)

**Comment by Cyberavater** [comment]
Ahh, I've found it. Another (non-blocker) extension is causing this, sorry for the trouble.

**Comment by uBlock-user** [comment]
That's why I told you to disable all other extensions. uBO cannot work if there's any interference at all.
