### ISSUE TITLE
Ads for LaPoliticaOnline.com.ar don't blocked anymore

### ISSUE THREAD

**Issue by antekgla** [uBlockOrigin/uAssets#9020]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
    - [x] using another browser with the last version installed
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.lapoliticaonline.com.ar/`

a news site from Argentina.

### Describe the issue

 

Ads don't get blocked anymore. Until today 05/05/2021 ads was blocked.

### Screenshot(s)

**The areas marked as PINK are noted by me to show the ads**

![LaPoliticaOnlineAds](https://user-images.githubusercontent.com/24402722/117189128-37fd5580-adb4-11eb-99f2-29df640f1075.jpg)

### Versions

- Browser/version: [Firefox 87.0 / Chrome 90.0.4430.93]
- uBlock Origin version: [v1.35.2]

### Settings

-

**Comment by uBlock-user** [comment]
```
lapoliticaonline.com.ar###header-banner-wrapper
lapoliticaonline.com.ar##div.standard.banner
```

**Comment by uBlock-user** [comment]
```
lapoliticaonline.com.ar###header-banner-wrapper
lapoliticaonline.com.ar##.banner
```
