### ISSUE TITLE
[Anti adblock] www.allmusic.com

### ISSUE THREAD

**Issue by avotoko** [uBlockOrigin/uAssets#9021]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.allmusic.com/artist/bob-seger-mn0000072041/discography`

### Describe the issue

The anti-adblock message appears and I cannot browse the page.

### Screenshot(s)
![screenshot](https://user-images.githubusercontent.com/53560467/117226135-eeae1400-ae4e-11eb-9a4d-a588c6510441.jpg)

### Versions

- Browser/version: Firefox 88.0.1
- uBlock Origin version: v1.35.2

### Settings

- JPN: AdGuard Japanese (default)

### Notes

filter to resolve the issue.
`@@||allmusic.com/images/tracking/tracking_pixel.jpg$xhr,domain=allmusic.com
`

**Comment by Pccode66** [comment]
Try turning uBlock filters – Annoyances on. You could also click "Continue on AllMusic"

**Comment by okiehsch** [comment]
> Try turning uBlock filters – Annoyances on. You could also click "Continue on AllMusic"

Yes, it's fixed in annoyances and after clicking "Continue on AllMusic" I don't get the message anymore unless I delete cookies.

**Comment by avotoko** [comment]
I understand.
It's hard to judge Annoyances for me. 
Should I always keep [uBlock filters - Annoyances] turned on?

**Comment by Pccode66** [comment]
The Annoyances filter should block "Disable your Adblock" nagging (nagging means that you can still use the website), and lots of other stuff, such as newsletters pop-ups, websites blocking right click, etc.
