### ISSUE TITLE
NSFW upvideo.to antiadb

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#9023]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

NSFW

`https://upvideo.to/v/jfiqnfdkwqpd`

source link in case above link expires `9xmoviehd.com`

### Describe the issue

Antiadblock

### Screenshot(s)

![Screenshot_2021-05-07-09-23-45-090_org mozilla fenix](https://user-images.githubusercontent.com/20338483/117398030-094dbf00-af1b-11eb-84bb-af4ea64cbefb.png)

### Versions

- Browser/version: firefox a nightly
- uBlock Origin version: 1.35

### Settings

 uBO's default settings
-

### Notes

This work for above tested browser, not access to test on other browsers

```
upvideo.to##+js(nowoif)
||imasdk.googleapis.com/js/sdkloader/ima3.js$xhr,redirect=nooptext,domain=upvideo.to
||derevya2sh8ka09.com^
```

**Comment by ghajini** [comment]
Antiadblock

**Comment by ghajini** [comment]
can't reproduce firefox/chrome

**Comment by mapx-** [comment]
@x-R0b0T-x did you disable brave's adblocker ?
