### ISSUE TITLE
github.com/explore

### ISSUE THREAD

**Issue by t3hmrman** [uBlockOrigin/uAssets#9024]
### Prerequisites

- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://github.com/explore`

### Describe the issue

GitHub shows ads in the "explore" feed

### Screenshot(s)

Same spot, 2 different ad placements:

![github-explore-feed-ad-2](https://user-images.githubusercontent.com/1085750/117405663-ed601280-af46-11eb-816a-0d30e536f2f8.png)

![github-explore-feed-ad](https://user-images.githubusercontent.com/1085750/117405668-ee913f80-af46-11eb-81b1-9511ae5d23ec.png)

These aren't really clearly marked as ads outside of "recommended by GitHub".

### Versions

- Browser/version: Firefox 89.0b6 (64-bit)
- uBlock Origin version: uBlock Origin v1.35.0

### Settings

No changes made to UBlock Origin

**Comment by t3hmrman** [comment]
HTML looks like this:

```html
<!--// Marketplace Listing //-->
<article class="border rounded color-shadow-small color-bg-primary my-4"> ... </article>
```

A ruleset based on a comment is obviously not the way to go but as I'm not super familiar with how uBlock works just yet wanted to at least post this

**Comment by uBlock-user** [comment]
First-party recommendations are not ads, at best annoyances, added filter for the `octoprint.org` ad.

**Comment by t3hmrman** [comment]
Sorry for the wasted time, thank you! :bow:
