### ISSUE TITLE
ecosia.org

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#9025]
### URL(s) where the issue occurs

`https://www.ecosia.org/search?q=bicicletas`

### Describe the issue

looks like ads

### FIRST PAGE

![Captura](https://user-images.githubusercontent.com/33556647/117416078-4dd85b00-af19-11eb-8a07-24888d3d6b50.PNG)

### SECOND PAGE

![Captura2](https://user-images.githubusercontent.com/33556647/117416415-a4459980-af19-11eb-8be8-f322e5b83b8d.PNG)

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.34.0]

**Comment by PIZZA90** [comment]
and the first page? usually random when refreshing page.

**Comment by ryanbr** [comment]
I couldn't see anything here, I searched for phones, only saw it then. but only at the top.

**Comment by PIZZA90** [comment]
![Captura2](https://user-images.githubusercontent.com/33556647/117422066-7cf1cb00-af1f-11eb-852f-7da41c654b42.PNG)

uBO picker
`www.ecosia.org##.sidebar-product-ad-container.sidebar-product-ad.product-ad
`

**Comment by PIZZA90** [comment]
Navigation buttons, of ads carousel. `https://www.ecosia.org/search?p=2&q=bicicletas`



```
ecosia.org##.slider-next.slider-control.icon-button--large.icon-button
ecosia.org##.slider-prev.slider-control.icon-button--large.icon-button
```

![Captura0](https://user-images.githubusercontent.com/33556647/122230643-1ebeed00-ceba-11eb-9dcc-b430b9dbf35b.PNG)
