### ISSUE TITLE
ergasiakanea.eu adblock detect

### ISSUE THREAD

**Issue by patrickdrd** [uBlockOrigin/uAssets#9029]
also there is a small rectangle shown on the bottom left corner 
(for me at least),

example url:
`https://ergasiakanea.eu/koinonikos-toyrismos-2021-extra-enischymeno-programma/`

**Comment by uBlock-user** [comment]
> there is a small rectangle shown on the bottom left corner

`||dalecta.com^`

Does that help ?

**Comment by patrickdrd** [comment]
yes, this rule helps,
here's mine

![image](https://user-images.githubusercontent.com/24896778/117444286-f0a4cf80-af41-11eb-91f0-21ee0647d0ee.png)

**Comment by mapx-** [comment]
Did you disable any other extension ? browser ?

**Comment by uBlock-user** [comment]
Fill the template completely as asked, this guesswork doesn't help

**Comment by uBlock-user** [comment]
Adding `||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect-rule=googlesyndication_adsbygoogle.js,badfilter` makes it able to reproduce the issue, so redirection is not happening on your side, likely browser intereference from the built-in blocker present in your browser.

**Comment by patrickdrd** [comment]
I don't think my browser has a built in adblocker,
anyway, I'm running 
Cent Browser
Version 4.3.9.248 (Official Build) (32-bit) (Portable) (Chromium 86.0.4240.198)

I'm going to check in chrome latest (with same setup) and I'll post results in a bit

**Comment by uBlock-user** [comment]
Cent is not officially supported fyi, test on chrome + firefox and only on default settings.

**Comment by patrickdrd** [comment]
the exact same screen with chrome latest

Version 90.0.4430.93 (Official Build) (32-bit)

**Comment by uBlock-user** [comment]
Add `ergasiakanea.eu##+js(acis, String.prototype.charCodeAt, ai_)` and report back.

**Comment by patrickdrd** [comment]
nope, still the same :(

**Comment by uBlock-user** [comment]
That redirection filter is what prevent the anti-adblock on Firefox,

try `ergasiakanea.eu##+js(noeval-if, deblocker)`

**Comment by patrickdrd** [comment]
yes, it worked with this!
so are you gonna commit the 2 entries?
tell me if you won't to add them in my filters,
thanks
