### ISSUE TITLE
tv-porinternet.com [ADS] [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#903]
URL(s) where the issue occurs

http://www.tv-porinternet.com/2014/07/directv-sports-en-vivo-por-internet.html

Describe the issue

ADS Pop-up

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
https://forums.lanik.us/viewtopic.php?p=128816#p128816

**Comment by xDarkARG** [comment]
Pop-up when one pauses the video @mapx-
`http://www.tv-porinternet.com/2013/03/disney-channel-en-vivo-por-internet.html`
