### ISSUE TITLE
pcgamer.com's "RECOMMENDED VIDEOS FOR YOU..." not appearing when uBO is enabled

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9035]
On `https://www.pcgamer.com/steam-sale-dates/` there is a blank a space when uBO is enabled. It turns out that when I disable uBO on that page a "RECOMMENDED VIDEOS FOR YOU..." thing appears. I'm not sure if this is intentional.

**Comment by uBlock-user** [comment]
They come from `ultimedia.com` blocked by EasyList.

@ryanbr

**Comment by ryanbr** [comment]
Intentional, cleaned up a bit more.

**Comment by IThinkIAmCool** [comment]
@ryanbr 
![Untitled](https://user-images.githubusercontent.com/83162792/117532266-3bc8ec00-afef-11eb-9308-e1b7399bd293.png)

**Comment by ryanbr** [comment]
From your screenshot, maybe you should enable uBO? @IThinkIAmCool
