### ISSUE TITLE
romaniataramea.com share to unlock

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9037]
Could it be bypassed?

To encouter it, you will need to look at an article (I'm not sure if all articles have share to unlock). The recent articles that I checked out had it.

**Comment by uBlock-user** [comment]
can't reproduce, fill the template as asked.

**Comment by IThinkIAmCool** [comment]
https://github.com/uBlockOrigin/uAssets/issues/9039

**Comment by llacb47** [comment]
Next time just edit the original issue.
