### ISSUE TITLE
romaniataramea.com share to unlock

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9039]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://romaniataramea.com/explicatia-pentru-trecerea-brusca-de-la-ninsoare-la-temperaturi-de-30-de-grade-climatolog-sa-ne-pregatim-pentru-noi-fenomene-extreme/`

### Describe the issue
Share to unlock.
 

### Screenshot(s)
![image](https://user-images.githubusercontent.com/83162792/117484910-61fb7700-af70-11eb-840c-a25c1a1b5086.png)

### Versions

- Browser/version: Chrome Version 90.0.4430.93
- uBlock Origin version: 1.34.0

### Settings
![image](https://user-images.githubusercontent.com/83162792/117485024-8f482500-af70-11eb-8ab6-c7627f3174b7.png)

-

**Comment by mapx-** [comment]
I guess it's better:
```
romaniataramea.com##+js(aopr, bizpanda)
*/wp-content/plugins/sociallocker-next-premium/$script,css
```
