### ISSUE TITLE
romania-insider.com

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9041]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### Describe the issues
I don't have some of the images unless I disable uBO for that romania-insider.com.
 

### Versions

- Browser/version: Version 90.0.4430.93 (Official Build) (64-bit)
- uBlock Origin version: 1.35.2

### Settings

![image](https://user-images.githubusercontent.com/83162792/117491706-3630bf00-af79-11eb-9785-8886a7ee3b0e.png)

**Comment by mapx-** [comment]
> some of the images

provide complete info, link, screenshot, don't waste our time.

**Comment by IThinkIAmCool** [comment]
> > some of the images
> 
> provide complete info, link, screenshot, don't waste our time.

will do, sorry

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/83162792/117492617-83f9f700-af7a-11eb-97e2-201915b9a8e4.png)
![image](https://user-images.githubusercontent.com/83162792/117492645-8f4d2280-af7a-11eb-86e7-aea0e54be804.png)

**Comment by uBlock-user** [comment]
Broken by Fanboy's Annoyances list.

@ryanbr

**Comment by IThinkIAmCool** [comment]
It may be because of some cookie(s).

**Comment by uBlock-user** [comment]
I see it broken with and without private browsing mode on Firefox, need that filter or some raw js injection
