### ISSUE TITLE
mrunblock.surf

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#9043]
### URL(s) where the issue occurs

example site: `https://torrentdownloads.mrunblock.surf`

### Describe the issue

Popups 💩

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.35.2]

**Comment by PIZZA90** [comment]
in main page... `https://mrunblock.surf/` some privacy crap should be resolved. ip.. location.. and the cores of microprocessor 🤬

**Comment by mapx-** [comment]
I get only a banner

`torrentdownloads.mrunblock.surf###lb-banner`

**Comment by mapx-** [comment]
Does this work for you ?

`torrentdownloads.mrunblock.surf##+js(aopw, _pop)`

**Comment by IThinkIAmCool** [comment]
![Screenshot 2021-05-08 112723](https://user-images.githubusercontent.com/83162792/117532471-61a2c080-aff0-11eb-8265-7c40c2712d97.png)

**Comment by IThinkIAmCool** [comment]
@ryanbr
