### ISSUE TITLE
Breaks starfiles.co

### ISSUE THREAD

**Issue by QuixThe2nd** [uBlockOrigin/uAssets#9047]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://starfiles.co`
`https://starfiles.ml`

### Describe the issue

The main JS file:
`https://cdn.jsdelivr.net/combine/gh/QuixThe2nd/Starfiles-JSDelivr@24/js/functions.min.js,gh/QuixThe2nd/Starfiles-JSDelivr@24/js/head.min.js,gh/QuixThe2nd/Starfiles-JSDelivr@24/js/analytics.min.js,npm/crypto-js@4/crypto-js.min.js,npm/intro.js@3/intro.min.js,npm/@popperjs/core@2.0/dist/umd/popper.js?e9c654833f2a1e543a11dac9dc751bf8d6523b601cf48d97d71de7a01ef5adb8fdef0ac70ce21b2559ef0e88fb32d011` as of writing this does not load, which breaks many essential functions. An example of this is the getScript function is never declared.
 

### Screenshot(s)
![image](https://user-images.githubusercontent.com/25378634/117536514-b53bfb00-b03e-11eb-9a9d-8ed7ac5c8094.png)
![image](https://user-images.githubusercontent.com/25378634/117536525-cab12500-b03e-11eb-89cc-e1cfc1dc66aa.png)

### Versions

- Browser/version: Chrome 90.0.4430.93
- uBlock Origin version: 1.34.0

### Settings

No changes

### Notes

Listed above

**Comment by QuixThe2nd** [comment]
That link changes frequently, I just sent it to explain what was happening

**Comment by uBlock-user** [comment]
> That link changes frequently

Changes how ? Give an example.

**Comment by QuixThe2nd** [comment]
As its a JSDelivr link, the files included change and the version numbers change. Right now its @24 for some, in the future that will be different. Also more files are added to it by adding something like `,gh/user/repo@version/file_path` to the end. Hope that explains it.

**Comment by QuixThe2nd** [comment]
Thanks!
It might be best to change it from:
`@@||cdn.jsdelivr.net^*/js/analytics.min.js$script,domain=starfiles.co|starfiles.ml`
To:
`@@||cdn.jsdelivr.net^*.js$script,domain=starfiles.co|starfiles.ml`
as /js/analytics.min.js could get changed.

**Comment by uBlock-user** [comment]
> as /js/analytics.min.js could get changed.

I disagree, you're the one in charge of the site, so don't change it or don't use baits from EasyPrivacy.

**Comment by QuixThe2nd** [comment]
Yeah, I get what you're saying. Thanks for the help, I really appreciate it.

**Comment by jiopolm** [comment]
Ublock once again breaks the website. I just checked and the new URL is:
`https://cdn.jsdelivr.net/combine/gh/QuixThe2nd/Starfiles-JSDelivr@238/js/functions.min.js,gh/QuixThe2nd/Starfiles-JSDelivr@238/js/head.min.js,gh/QuixThe2nd/Starfiles-JSDelivr@238/js/analytics.min.js,npm/jszip@3/dist/jszip.min.js,npm/@popperjs/core@2.0/dist/umd/popper.js,npm/@fingerprintjs/fingerprintjs-pro@3/dist/fp.min.js,npm/pace-js@1/pace.min.js`
You could switch it to:
`@@||cdn.jsdelivr.net^*/pace.min.js$script,domain=starfiles.co|starfiles.ml`
Or maybe use another method to prevent it from returning false positives in the future.

**Comment by uBlock-user** [comment]
> Ublock once again breaks the website. I just checked and the new URL is:

Can't reproduce, nothing from jsDelivr is blocked as per the logger.
