### ISSUE TITLE
fux.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#905]
URL(s) where the issue occurs

https://www.fux.com/videos/551193/big-thai-masseuse-big-tits-works-magic

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
test
```
fux.com##script:inject(abort-on-property-read.js, ExoLoader)
||fux.com/*banner$image
||fux.com^$script
@@||fux.com/assets/$script
@@||fux.com/js/player/$script
@@||fux.com/*dynamic_js_en.js
```
