### ISSUE TITLE
obsolete filters

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9063]
![image](https://user-images.githubusercontent.com/83162792/117565775-c70fb380-b0bb-11eb-8e13-761dabfec322.png)

Edit: The filters for likn.xyz are not obsolete

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/83162792/117565813-f2929e00-b0bb-11eb-9c4c-7a8261dc654c.png)

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/83162792/117568628-ff1df300-b0c9-11eb-9fca-353343fe7d45.png)

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/83162792/117568650-1d83ee80-b0ca-11eb-89ec-9fff6ffc98fb.png)

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/83162792/117568776-05f93580-b0cb-11eb-93fa-59634cf1790e.png)
I'm not sure if these are still needed.

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/83162792/117568801-21644080-b0cb-11eb-9853-0763c9dd8f72.png)
![image](https://user-images.githubusercontent.com/83162792/117568804-2628f480-b0cb-11eb-847e-cbf83eb8d94e.png)

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/83162792/117569239-5ffafa80-b0cd-11eb-8c14-a327222c37ed.png)
I'm not sure about this one.

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/83162792/117569342-eadbf500-b0cd-11eb-857c-7003c7c452d2.png)
Is this filter still needed?

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/83162792/117569384-270f5580-b0ce-11eb-97e8-017ad9f2d9bd.png)

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/83162792/117569422-41493380-b0ce-11eb-98e2-b73cd3c74505.png)

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/83162792/117569580-0693cb00-b0cf-11eb-8d04-457064320ac4.png)
Is this still needed?

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/83162792/117569642-4c509380-b0cf-11eb-812b-f9fa36ff77cf.png)

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/83162792/117569665-67bb9e80-b0cf-11eb-9b33-8a3a40d79ef2.png)

**Comment by mapx-** [comment]
We prefer to have the text links not those pics, ok ?

**Comment by IThinkIAmCool** [comment]
> We prefer to have the text links / filters not those pics, ok ?

Ok.
