### ISSUE TITLE
Obsolete filter?

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9068]
Is `185.153.231.222##+js(nowebrtc)` an obsolete filter?
![image](https://user-images.githubusercontent.com/83162792/117580283-eb8d7f00-b0ff-11eb-8470-7cf9fb3591d5.png)
@ghajini

**Comment by ghajini** [comment]
domain is active on alemdarleech.com and filter won't hurt for that leeching site
