### ISSUE TITLE
clik.pw [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#907]
URL(s) where the issue occurs

http://clik.pw/lxAOw

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
Pop-up CAPTCHA

**Comment by KiLL4FuNK** [comment]
Pop-up

`http://clik.pw/7ArUDp`

**Comment by lain566** [comment]
Captcha not showing
`http://clik.pw/8itZB`

**Comment by lain566** [comment]
Anti adblock after solving the captcha.

**Comment by lain566** [comment]
The captcha is broken, it does not show the text to enter in the box.
`https://clik.pw/0Ezt4`

**Comment by lain566** [comment]
Anti adblock again.

**Comment by lain566** [comment]
Does not load the web page
`http://clik.pw/8itZB`

**Comment by lain566** [comment]
There's a popup
