### ISSUE TITLE
akwam new-tab ads

### ISSUE THREAD

**Issue by Iaycomand** [uBlockOrigin/uAssets#9077]
### URL(s) where the issue occurs
[https://eg.akwam.cx/series/1622/%D9%84%D8%B9%D8%A8%D8%A9-%D9%86%D9%8A%D9%88%D8%AA%D9%86](url)
[https://eg.akwam.cx/](url)

### Describe the issue

Any spot on the site or a clickable link opens a new tab ad, you have to click several times to get the action you want.

### Versions

- Browser/version: Google chrome - Version 90.0.4430.93 (Official Build) (64-bit)
- uBlock Origin version: v1.35.2

**Comment by Iaycomand** [comment]
issue still occur

**Comment by okiehsch** [comment]
Is it fixed now?

**Comment by Iaycomand** [comment]
Yeas, Thank you!
