### ISSUE TITLE
Service Worker Blocked - Breaking PWA (9xbuddy + OFFMP3)

### ISSUE THREAD

**Issue by sudovijay** [uBlockOrigin/uAssets#9078]
These two filters actually breaking the functionality of my sites. can assure there are no ads in service worker. it just caching network request for pwa

```
||offmp3.*/sw.js$script,1p
||9xbuddy.*/sw.js$script,1p
```

### URL(s) where the issue occurs

```
https://9xbuddy.com/sw.js
https://offmp3.com/sw.js

```
### Versions

- Browser/version: Chrome/ 92.0.4496.0 
- uBlock Origin version: uBlock Origin v1.35.2

### Notes

it would be great if you can check and maybe remove those filters

**Comment by uBlock-user** [comment]
> breaking the functionality of my sites.

What is broken ?

**Comment by sudovijay** [comment]
There's no adware, just advertisement on some pages to support site, not even any kind of tracker. just give it a try, you'll know for youreself

And it has reference to this issue #311 which is from 2017 just for popups, there's nothin worng with service worker. just look at the code.

**Comment by sudovijay** [comment]
> Nothing's broken on both sites, functionality is working as expected.
> 
> > #311 which is from 2017 just for popups
> 
> Followup commits are from 2019/2020.

ServiceWorker can't be registered so user can't install this as desktop app, (PWA)

And about those popups is still there on download page, only way to keep this thing going.
