### ISSUE TITLE
https://click.accesstra.de

### ISSUE THREAD

**Issue by extrange** [uBlockOrigin/uAssets#9080]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://complaintsingapore.com/2021/04/20/same-quantity-of-hash-browns-for-different-sizes-from-fast-food-joint/`

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

-

**Comment by uBlock-user** [comment]
@ryanbr lots of unblocked ads
