### ISSUE TITLE
Blocked an image on wiki

### ISSUE THREAD

**Issue by shachar700** [uBlockOrigin/uAssets#9085]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Blocked this image to appear even though it is not an ad

### A specific URL where the issue occurs

`https://splatoonwiki.org/wiki/File:17XX_advertisement_A.png`

### Steps to Reproduce

1. Have the addon on
2. Go to the site
3. See if it's visible in the image

### Expected behavior:

To see the image with big size and at the thumbnail sections

### Actual behavior:

No image was seen

### Your environment

* uBlock Origin version: 1.35.2
* Browser Name and version: Firefox
* Operating System and version: Win 10

**Comment by uBlock-user** [comment]
@ryanbr Broken by EasyList filter
