### ISSUE TITLE
pdfrecover.herokuapp.com

### ISSUE THREAD

**Issue by strict-block** [uBlockOrigin/uAssets#9087]
1 more web app with detect anti-adblock based on EL/EP blockade:

`https://pdfrecover.herokuapp.com/swftoexe/`

can help add subdomain here:

https://github.com/uBlockOrigin/uAssets/blob/d9dccd585c3cd8e29b8222f52fa967eff061ca67/filters/filters-2020.txt#L4112

test no need found vaild `.swf` file, after click convert now see:

> Please disable the adblock for free use.

But correct is:

> Please select SWF files.

**Comment by strict-block** [comment]
a little diffrent is:

`https://pdfrecover.herokuapp.com/swfdecompiler/`

this may need valid `.swf` file, to see "Please disable the adblock for free use.".

**Comment by uBlock-user** [comment]
`*$script,redirect-rule=noopjs,domain=pdfrecover.herokuapp.com` works for that too. Download a sample .swf, upload it and test it yourself.
