### ISSUE TITLE
adbilty.me [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#909]
URL(s) where the issue occurs

http://adbilty.me/DmAych

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
Pop-up @mapx-

**Comment by gorhill** [comment]
||dc08i221b0n8a.cloudfront.net^

**Comment by xDarkARG** [comment]
Pop-up @mapx-

**Comment by KiLL4FuNK** [comment]
Bad Request
