### ISSUE TITLE
Program blocks ublock

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uAssets#9090]
This site demands to disable ublock and even after i did so, it showed me a msg saying to disable it.
`
https://uploadbox.io/8w5be3y7irx5`

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled.

**Comment by Felipefpl** [comment]
i only have ublock.

**Comment by uBlock-user** [comment]
but you're not on default settings/lists as per https://github.com/uBlockOrigin/uAssets/issues/9011#issuecomment-831547272

**Comment by Felipefpl** [comment]
so you meant the default filters, not settings? Ok.

**Comment by uBlock-user** [comment]
Both actually
