### ISSUE TITLE
news-world24.com antiadb

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#9092]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://urlshortner.news-world24.com/?go=06ad7179`

link from `unlimitmovies.com`

### Describe the issue

Antiadblock preventing access

### Screenshot(s)

![IMG_20210514_223212](https://user-images.githubusercontent.com/20338483/118310666-8de8a080-b50c-11eb-8664-99fa22c73f52.jpg)

### Versions

- Browser/version: firefox nightly A
- uBlock Origin version: 1.35

### Settings

 uBO's default settings
-

**Comment by mapx-** [comment]
test

`@@||pagead2.googlesyndication.com^$xhr,domain=urlshortner.news-world24.com`

**Comment by ghajini** [comment]
that also work
btw this also work

`urlshortner.news-world24.com##+js(no-fetch-if, adsbygoogle.js)`
