### ISSUE TITLE
Youtube Ads Germany not blocked every time

### ISSUE THREAD

**Issue by Kusurisan** [uBlockOrigin/uAssets#9094]
### Prerequisites

- [x] This is not a support issue or a question
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
- [x] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://www.youtube.com/watch?v=kZM92urNWrQ`

### Describe the issue

from time to time i open a youtube video and at the start of the video youtube shows me ads. sometimes ublock origin seem to block the ad after like 2-4 seconds so the ad stops and the video starts playing, but sometimes i need to reload the whole website to skip / block the ad.

### Screenshot(s)

https://i.imgur.com/WYIYEYG.png

### Versions

- Browser/version: Firefox 80.0 (64-Bit)
- uBlock Origin version: newest (fresh updated manually few minutes ago to make sure)

### Settings
default

### Notes
i tried to find out when or why this happens but it seems to be random. even on the same video it just happens sometimes (a few times a day).

### Installed Addons
- Alternate Player for Twitch.tv
- Blocktube
- CORS Everywhere (not relevant since i installed it after first encountering the issue)
- Greasemonkey (tried to disable it without effect)
- Popup Blocker Ultimate
- RES (reddit)
- Sponsorblock
- Tab Session Manager
- Ublock Origin
- The Stream Detector
- Unwanted Twitch

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636
