### ISSUE TITLE
problem with Youtube autoplay

### ISSUE THREAD

**Issue by FlowerPowerFYeah** [uBlockOrigin/uAssets#9096]
### Prerequisites

- [ x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x ] I tried to reproduce the issue when...
    - [yes ] uBlock Origin is the only extension
    - [yes ] uBlock Origin with default lists/settings
    - [ues ] using a new, unmodified browser profile
- [ yes] I am running the latest version of uBlock Origin

### Versions

- Browser/version: [firefox 88.0.1]
- uBlock Origin version: [v1.35.2]

### Settings

-

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636#issuecomment-841761727
