### ISSUE TITLE
tranzystor.pl

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#9097]
`https://www.tranzystor.pl/`

blocked right click by JavaScript.

**Comment by uBlock-user** [comment]
`/wp-content/plugins/image-watermark/js/no-right-click.js$script`

**Comment by krystian3w** [comment]
OK, so I try report to Fanboy's and AdGuard team.

**Comment by uBlock-user** [comment]
@krystian3w are you reproducing this on Chrome ?

**Comment by krystian3w** [comment]
No.

I just like to use RCM instead of use the element picker built into the uBO pop-up and in Firefox I can't do that.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/6086ded202f0e502fd52cf96a572a08736148442#diff-c602d2bfb71b89b2a64418c9e910b7ef0dbddfa7ace28cd8b7fdae000739cee3R1184

Possible revert.
