### ISSUE TITLE
Alienvault OSSIM and USM

### ISSUE THREAD

**Issue by Peetz0r** [uBlockOrigin/uAssets#91]
### URL(s) where the issue occurs

https://demo.alienvault.com/ossim/#analysis/alarms/alarms-1E5697B759C511E69DEC0A830B0255F0
- user: **guest**
- password: **alienvault**

### Describe the issue

The alarm details don't display on that page.

### Screenshot(s)

http://i.imgur.com/zuYlH2b.png
http://i.imgur.com/yPfl6t4.png

### Versions

- uBO 1.7.6 in Chrome 52 on Windows 10
- uBO 1.8.0 in Chromium 51 on Ubuntu 14.04

### Settings

Default

### Notes

This is because the page uses divs named **ad_header** and **ad_content** and more (see uBO log) which are seen as ads but ad stands for alarm detail.

This happens not just for me, but for all of my coworkers. We use Alienvault OSSIM inside our company, but the public Alienvault USM demo linked above has the exact same behavior.

**Comment by gorhill** [comment]
Are there any ads on this page? If not, I suppose disabling generic cosmetic filters would be the best solution: `@@||alienvault.com^$generichide`.

**Comment by Peetz0r** [comment]
There aren't any, but a filter like that wouldn't work anywhere else than the demo site. We (and many others) run Alienvault somewhere inside our own network. I was lookin trough the filter documentation, but it seems like there's no way to just filter for `*/ossim/alarm/alarm_detail.php*`

**Comment by gorhill** [comment]
How about `@@/ossim/*$generichide`? You should report the issue to EasyList maintainers, they might have a batter idea on how to solve the issue: <https://forums.lanik.us/viewforum.php?f=64>.

**Comment by Peetz0r** [comment]
Yes, `@@/ossim/*$generichide` works great.

But it would be bad to see advertisers changing all their urls to something with /ossim/ in them, wouldn't it?

**Comment by gorhill** [comment]
Yes, it's why the fix should be only on your side. I was not planning to bring a fix for this in uBO's filters anyways, the issue is when using EasyList filters, so whatever fix if any has to go in there.

**Comment by Peetz0r** [comment]
Let's see what they make out of this at https://github.com/easylist/easylist/issues/108

**Comment by gorhill** [comment]
Can't you ask Alienvault to change their ids in the DOM?

**Comment by Peetz0r** [comment]
Maybe, but they don't seem to have any kind of public issue tracker...

**Comment by gorhill** [comment]
Until there is a solution, if you use uBO, one can always easily toggle off cosmetic filtering (which is the issue here) for whatever site that Alienvault panel is served: <https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering>.
