### ISSUE TITLE
uBlock and Pardot

### ISSUE THREAD

**Issue by yatishmadhav** [uBlockOrigin/uAssets#9100]
Hi there

We use uBlock Origin within our organization but recently when starting to use Pardot, we have noticed that some email images are blocked from go.pardot.com.

Looks like it is under EasyPrivacy at Adblock Plus 1.1.

Please advise why this is and how to resolve globally/generally?

Thank you

**Comment by uBlock-user** [comment]
`go.pardot.com` is an e-mail tracker, hence blocked in EP and Peter Lowe's list. You could whitelist the domain if you want under your organisation setup.

**Comment by uBlock-user** [comment]
`go.pardot.com` is an e-mail tracker, hence blocked in EP. You could whitelist the domain if you want under your organisation setup.

**Comment by ryanbr** [comment]
https://old.reddit.com/r/uBlockOrigin/comments/mwwvde/how_to_avoid_blocking_pardot_by_ublockorigin/

Addressed here

**Comment by yatishmadhav** [comment]
Thank you for the quick replies ... How do we address this to update for the whole organization? ie. I can whitelist it for my only Chrome extension installation but we would like to resolve for the entire org users.

**Comment by ryanbr** [comment]
The fix needs to come from pardot, they're using go.pardot as the cname tracker, if they separated the tracking to actual functionality then would resolve this issue.

**Comment by uBlock-user** [comment]
https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin
