### ISSUE TITLE
kruidvat.nl

### ISSUE THREAD

**Issue by g-k-m** [uBlockOrigin/uAssets#9103]
### Prerequisites

- [√] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [√] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [√] I tried to reproduce the issue when...
    - [√] uBlock Origin is the only extension
    - [] uBlock Origin with default lists/settings
    - [] using a new, unmodified browser profile
- [√] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.kruidvat.nl/`

### Describe the issue

This happened not just to me but to many people on a security forum that I participate in. When not blocking trackers, everything works fine. However, when blocking trackers with ublock origin (or dev tools, doesn't matter), the site takes like 3 seconds to load, showing a white screen while it's loading. So i'm not sure if it's a ublock origin problem, but there's something with the blocking of the trackers that's causing it, and I'm interested if there's a way to fix it (apart from contacting the site admins ofc)?

### Versions

- Browser/version: Latest few versions of Chromium-based browser. At least 10 people had this issue on the forum, so it must be universal
-  uBlock Origin version: [1.35.2]

### Settings

Privacy

Disable pre-fetching (to prevent any connection for blocked network requests) 
Disable hyperlink auditing 
Prevent WebRTC from leaking local IP addresses 
all checked

also advanced user mode checked but nothing modified

### Notes

Someone on the forum said he experienced the issue with just EasyList and EasyPrivacy lists enabled.

**Comment by uBlock-user** [comment]
Add -- 

```
*$script,redirect-rule=noopjs,domain=kruidvat.nl
kruidvat.nl##.async-hide:style(opacity:1.0 !important)
```

to my filters and report back.

**Comment by g-k-m** [comment]
Isn't this supposed to  be by default in ublock origin so we don't have to inspect every site this happens in manually and make rules manually? But yeah it works for me thx

**Comment by g-k-m** [comment]
And also, why redirect all scripts, why not redirect just the blocked ones? Doesn't that slow it down?

**Comment by uBlock-user** [comment]
> Isn't this supposed to be by default in ublock origin

No.

> And also, why redirect all scripts, why not redirect just the blocked ones? Doesn't that slow it down?

`redirect-rule` only redirects blocked ones.

Thirdly, this is not a ubo issue, the admin has installed two scripts (one of them is google optimise crap, the other checks whether `unless.com` loads or not) that check if the tracker load or not, and if they don't, then set the opacity to `' '` for 3 secs, this is done intensionally.
