### ISSUE TITLE
obsolete filter for uploadhaven.com?

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9104]
`||uploadhaven.com/sw.js$script,1p` is a problematic filter.
Upon "Download Now" this:
![image](https://user-images.githubusercontent.com/84325511/118487331-46882d00-b723-11eb-81b0-b6a889f9b905.png) appeared on my screen.

**Comment by IThinkIAmCool** [comment]
Or maybe it's not because of that filter

**Comment by IThinkIAmCool** [comment]
Nvm, I think it was caused by the 'AdGuard Annoyances' filter list.

**Comment by IThinkIAmCool** [comment]
`||uploadhaven.com/sw.js$script,1p` might be obsolete though

**Comment by IThinkIAmCool** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
Provide a test link.

**Comment by uBlock-user** [comment]
Don't ask questions, provide links and make a case as to why do you think it's obsolete or broken.

**Comment by IThinkIAmCool** [comment]
For example, `https://steamunlocked.net/minecraft-free-pc-download/` has 
![image](https://user-images.githubusercontent.com/84325511/118521483-c2926d00-b743-11eb-8d39-3f9e7d6346b6.png)

Upon clicking on "Download Now" with AdGuard Annoyances enabled I encounter this:
![image](https://user-images.githubusercontent.com/84325511/118521622-ddfd7800-b743-11eb-9536-5dbf28620fbe.png)

I think `||uploadhaven.com/sw.js$script,1p` might be obsolete because last time I checked, the timer wasn't being sped up/bypassed.

**Comment by Yuki2718** [comment]
The download works fine with sw.js blocked.

**Comment by Yuki2718** [comment]
The Session expired is caused by, as you guessed, AG Annoyances so I'll fix in the according AG issue: https://github.com/AdguardTeam/AdguardFilters/issues/83371

**Comment by IThinkIAmCool** [comment]
@Yuki2718 I think `||uploadhaven.com/sw.js$script,1p` is supposed to bypass something or make the time go faster, which I didn't encounter.

**Comment by uBlock-user** [comment]
> I think ||uploadhaven.com/sw.js$script,1p is supposed to bypass something or make the time go faster, which I didn't encounter.

No, it creates popups.

**Comment by IThinkIAmCool** [comment]
Oh, I thought the filter was meant for some sort of a bypass since I found the filter in this ! `https://github.com/timmyrs/Universal-Bypass/issues/247
||uploadhaven.com/sw.js$script,1p` form

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/84325511/118527085-97128100-b749-11eb-9778-a85b640a048f.png)
