### ISSUE TITLE
Broken sites: www.totaaltv.nl, www.dagelijksestandaard.nl/

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uAssets#9106]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
```
https://www.totaaltv.nl/nieuws/kpn-wijzigt-digitenne-in-noordholland-en-texel/
https://www.dagelijksestandaard.nl/
```

### Screenshot(s)
totaaltv.nl how it should be:
![image](https://user-images.githubusercontent.com/80090789/118515982-30d03300-b736-11eb-84d1-c8ee266c0985.png)
how it is currently:
![image](https://user-images.githubusercontent.com/80090789/118516065-46455d00-b736-11eb-8c3a-7e3e450123ea.png)
dagelijksestandaar.nl: how is should be:
![image](https://user-images.githubusercontent.com/80090789/118516222-69700c80-b736-11eb-8fa6-f33ef1b1d762.png)
how it is currently:
![image](https://user-images.githubusercontent.com/80090789/118516287-77259200-b736-11eb-8c3b-e03ec53574b0.png)

### Versions

- Browser/version: [Edge Stable newest]
- uBlock Origin version: [1.35.2]

### Settings

-

### Notes
Because those blocks contains some form of tracking `||sprinklecontent.com^$3p` which is block by `EasyPrivacy` and also some ads of `adnxs.com` the whole block is blocked. Which is not how it should be.

**Comment by IThinkIAmCool** [comment]
@pgl 
![image](https://user-images.githubusercontent.com/84325511/118539014-94b72380-b757-11eb-9439-74c203104d30.png)

**Comment by okiehsch** [comment]
Allowing it works for me at `https://www.totaaltv.nl/nieuws/kpn-wijzigt-digitenne-in-noordholland-en-texel/`
`||plista.com^$badfilter`
fixes the breakage.
@pgl looks like legitimate content.

**Comment by okiehsch** [comment]
@BPower0036 

````
@@||widgets.sprinklecontent.com^$script,xhr,domain=dagelijksestandaard.nl
@@||widgets.spklw.com/v1/data/*$xhr,domain=dagelijksestandaard.nl
````
works for me at `https://www.dagelijksestandaard.nl/`

**Comment by uBlock-user** [comment]
![Capture](https://user-images.githubusercontent.com/21290713/118550984-fe94f480-b77a-11eb-8fd0-0ecf90af550e.PNG)

They do some click and mouse tracking..

**Comment by BPower0036** [comment]
@okiehsch 
When i added your rules. It is still a little bit broken. In stead of showing 3 articles suggestions it shows 1
![image](https://user-images.githubusercontent.com/80090789/118595127-c9a09600-b7aa-11eb-860a-1b33c4998a3a.png)

**Comment by okiehsch** [comment]
The third one is an ad on my end.
I can see it if I disable cosmetic filtering.
![image](https://user-images.githubusercontent.com/16838044/118595513-809d1180-b7ab-11eb-836b-cbbbc56d9479.png)

**Comment by BPower0036** [comment]
If I add this one in addition to `@@||widgets.sprinklecontent.com^$script,xhr,domain=dagelijksestandaard.nl`
`@@||widgets.spklw.com/v1/data/*$xhr,domain=dagelijksestandaard.nl`
`dagelijksestandaard.nl##.spklw-tracked-sent.spklw-tracked.spklw-swiper-slide-visible.spklw-swiper-slide:has([data-url^="https://ad."])`
I get a broken image
![image](https://user-images.githubusercontent.com/80090789/118596727-0d47cf80-b7ac-11eb-9d6e-d2713ac3196d.png)

**Comment by BPower0036** [comment]
Maybe adding some sort of scriptlet (`##+js()`) can solve the problem. Because this article block is loaded via `//widgets.sprinklecontent.com/v2/sprinkle.js` as you can see in `view-source`
![image](https://user-images.githubusercontent.com/80090789/118597719-59474400-b7ad-11eb-9ad0-46104af023c4.png)

**Comment by okiehsch** [comment]
If I add your suggested filters
````
@@||widgets.sprinklecontent.com^$script,xhr,domain=dagelijksestandaard.nl
@@||widgets.spklw.com/v1/data/*$xhr,domain=dagelijksestandaard.nl
dagelijksestandaard.nl##.spklw-tracked-sent.spklw-tracked.spklw-swiper-slide-visible.spklw-swiper-slide:has([data-url^="https://ad."])
````
I still see only two articles at the most.

**Comment by BPower0036** [comment]
> If I add your suggested filters
> 
> ```
> @@||widgets.sprinklecontent.com^$script,xhr,domain=dagelijksestandaard.nl
> @@||widgets.spklw.com/v1/data/*$xhr,domain=dagelijksestandaard.nl
> dagelijksestandaard.nl##.spklw-tracked-sent.spklw-tracked.spklw-swiper-slide-visible.spklw-swiper-slide:has([data-url^="https://ad."])
> dagelijksestandaard.nl##.spklw-tracked-sent.spklw-tracked.spklw-swiper-slide-visible.spklw-swiper-slide:has([data-url^="https://itx4.smartadserver.com/"])
> ```
> 
> I still see only two articles at the most.

I understand. You have to wait +/- 20 sec. to see more article titles with broken images as you can see in the above added screenshots of me.

**Comment by pgl** [comment]
> @pgl looks like legitimate content.

In this case, I think the entire domain is dedicated to ads. plista describe themselves like this:

> plista is a global platform for data-driven native advertising in premium editorial environments and offers advertisers and publishers direct, single-source access

So if there are assets hosted on the domain, I would imagine they are used for ad display. If another site is tied to their functionality then I think the site should fix it really. Sorry.

**Comment by okiehsch** [comment]
Fine by me.

@BPower0036 do you want to fix `https://www.totaaltv.nl/nieuws/kpn-wijzigt-digitenne-in-noordholland-en-texel/` in your list?

**Comment by BPower0036** [comment]
@okiehsch No. If it is what @pgl says that  `So if there are assets hosted on the domain, I would imagine they are used for ad display. If another site is tied to their functionality then I think the site should fix it really.` I don't feel the need to fix it, unless `totaaltv.nl` works differently then `dagelijksestandaard.nl`

**Comment by BPower0036** [comment]
i found out that `totaaltv.nl` works differently then `dagelijksestandaard.nl`
For me these rules works, maybe the are to broad?
`@@||static-nl.plista.com/*$script,domain=totaaltv.nl`
`@@||farm-nl.plista.com^$script,domain=totaaltv.nl`
`@@||plista.com^$image,domain=totaaltv.nl`

**Comment by okiehsch** [comment]
That would allow some tracking pixels.
´```
@@||plista.com/async$script,domain=totaaltv.nl
@@||media.plista.com^*$image,domain=totaaltv.nl
````
worls for me.

**Comment by BPower0036** [comment]
You're right your suggested rules work. Thanks.
I will add them to me list.
