### ISSUE TITLE
kisscartoon.sh

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9107]
Issue: pop-up
Can be reproduced by using a "Hserver" video player and clicking on "Fullscreen" twice.
![image](https://user-images.githubusercontent.com/84325511/118522083-595f2980-b744-11eb-8229-dd13ece27860.png)

**Comment by IThinkIAmCool** [comment]
@uBlock-user I'm still able to reproduce (after updating uBO's 'uBlock filters')

**Comment by uBlock-user** [comment]
> after updating uBO's 'uBlock filters')

Did you get the latest update or cached asset ? Open the list (via the eye button in filter lists pane) and search for  `redirect-ads.com##+js(nowoif, /^/, 1)`,

**Comment by IThinkIAmCool** [comment]
Yeah, I found it after updating and I didn't encounter any popup afterwards. I think I u[dated too quickly. Sorry for wasting your time.

**Comment by uBlock-user** [comment]
Always wait upto 10 mins after commits are pushed here.
