### ISSUE TITLE
Ads spaces not removed - ublock 1.35.2 - default settings

### ISSUE THREAD

**Issue by Felipefpl** [uBlockOrigin/uAssets#9108]
The site below has this problem:

`https://cdromance.com/`

**Comment by uBlock-user** [comment]
`cdromance.com##div.game-container[style="grid-column: span 2;"]`

@ryanbr

**Comment by Felipefpl** [comment]
Thanks for the fix, found another one in the right side of this site:

https://animefire.net/animes/kono-subarashii-sekai-ni-shukufuku-wo/8

**Comment by IThinkIAmCool** [comment]
What about `cdromance.com##div + div:has-text(Advertisements)`?

**Comment by uBlock-user** [comment]
`animefire.net##.divSection3`

Report to Easylist, it's going to get blocked in that list anyway.

**Comment by Felipefpl** [comment]
ok, thanks for this last addition.
