### ISSUE TITLE
adshort.im [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#911]
URL(s) where the issue occurs

http://adshort.im/rPOCc

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
Pop-up fill the Captcha @mapx-

**Comment by xDarkARG** [comment]
@mapx- clone Anti-Adblock  `http://adsrt.com/hMZEjIA`

**Comment by KiLL4FuNK** [comment]
@mapx- Pop-up

**Comment by KiLL4FuNK** [comment]
the page does not show well

**Comment by KiLL4FuNK** [comment]
the page does not show well

**Comment by ZaphodBeebblebrox** [comment]
The site still works. I guess I could add something like `adsrt.com###captchaShortlink:style(display: block !important; margin-left: 35% !important;)` if it works for you.

**Comment by okiehsch** [comment]
Do also add
`||adsrt.com/sw.js$script`

**Comment by smed79** [comment]
@okiehsch It is possible to disable the dynamic background in the annoyance list because it causes unnecessary use of CPU resources ?

![https://i.imgur.com/M94FwOJ.png](https://i.imgur.com/M94FwOJ.png)

**Comment by greatwolf** [comment]
> The site still works. I guess I could add something like `adsrt.com###captchaShortlink:style(display: block !important; margin-left: 35% !important;)` if it works for you.

This rule is stopping the site from properly loading the captcha. I need the captcha to properly load, how can I disable this rule?

**Comment by okiehsch** [comment]
> This rule is stopping the site from properly loading the captcha. 

Not on my end.
`||adsrt.*^$csp=script-src 'self' 'unsafe-inline' data: *.google.com *.gstatic.com`
is breaking the captcha, I will remove it.

> how can I disable this rule?

To disable a cosmetic filter like
`example.com###whatever`
add
`example.com#@##whatever`
to your filter list.

**Comment by greatwolf** [comment]
Thanks, You're right it looks like `||adsrt.*^$csp=script-src 'self' 'unsafe-inline' data: *.google.com *.gstatic.com` is breaking the captcha. Allowing that shows the google recaptcha properly.

**Comment by ghajini** [comment]
URL=
`https://adsrt.org/fP7qAv62`

Environment = firefox android stable, ublock origin 1.26

Issue= can't see captcha clearly with ublock enabled

Screenshots=
***ublock enabled=*** 

https://user-images.githubusercontent.com/20338483/79234778-6433f480-7e88-11ea-9762-30a3d10974e3.jpg

***Ublock disabled=***

https://user-images.githubusercontent.com/20338483/79234871-82015980-7e88-11ea-993a-ed18eb28f7c7.jpg

Note=workaround I do is request desktop mode enabled

**Comment by mapx-** [comment]
could be this cosmetic filter ?

try the exception
`adsrt.*#@##captchaShortlink:style(display: block !important; margin-left: 35% !important;)`

**Comment by ghajini** [comment]
Yes I guessed that, it works on my end
