### ISSUE TITLE
chatmilkprude.casa

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9111]
![image](https://user-images.githubusercontent.com/84325511/118540509-51f64b00-b759-11eb-8506-84d08bba1bed.png)

**Comment by mapx-** [comment]
Where did you find this domain ? What page ?

**Comment by IThinkIAmCool** [comment]
`steamhub.co`

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/84325511/118549505-3b092600-b764-11eb-9a7b-6009358bf369.png)

**Comment by IThinkIAmCool** [comment]
@ryanbr
