### ISSUE TITLE
I got a popup while checking if gamesforyou.co had ad placeholders (with uBO disabled)

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9113]
![image](https://user-images.githubusercontent.com/84325511/118540923-c6c98500-b759-11eb-8f7e-4e8d862a59cb.png)

**Comment by okiehsch** [comment]
> with uBO disabled

You get a popup with uBO-disabled???
Shocking.

I can't reproduce any popups with uBO enabled.

**Comment by IThinkIAmCool** [comment]
> > with uBO disabled
> 
> You get a popup with uBO-disabled???
> Shocking.
> 
> I can't reproduce any popups with uBO enabled.

It's on purpose. I posted this to let filter list maintainers know about the domain.

**Comment by IThinkIAmCool** [comment]
@ryanbr

**Comment by okiehsch** [comment]
You can open EasyList issues for `ryanbr` here https://github.com/easylist/easylist/issues
