### ISSUE TITLE
ublockorigin[.]com malware

### ISSUE THREAD

**Issue by iam-py-test** [uBlockOrigin/uAssets#9117]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://ublockorigin.com` (The malware url - I have not visited it for security reasons)
`https://duckduckgo.com/?q=ublock+origin&ia=web` (The DuckDuckGo search results)

### Describe the issue
`ublockorigin.com` is a fake uBlock Origin website which is at the top of the DuckDuckGo search results and appears to serve malware. Because uAssets has blocked other fake uBlock Origin websites (Examples, https://github.com/uBlockOrigin/uAssets/issues/5854, https://github.com/gorhill/uBlock/wiki/Badware-risks#ublockorg)
 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/84232764/118559297-b7384500-b735-11eb-8262-afd17356d00e.png)
![image](https://user-images.githubusercontent.com/84232764/118559349-cdde9c00-b735-11eb-866a-30d7f51940d6.png)

### Versions

- Browser/version: Firefox 88.0.1
- uBlock Origin version: uBlock Origin v1.35.2 (Can also reproduce with uBlock Origin development build v1.35.3b3)

### Settings

- For antimalware lists I have uBlock filters – Badware risks, [💊 Dandelion Sprout's Anti-Malware List](https://github.com/DandelionSprout/adfilt/blob/master/Dandelion%20Sprout's%20Anti-Malware%20List.txt), [Phishing URL Blocklist](https://gitlab.com/curben/phishing-filter#url-based), [The Block List Project - Ransomware List](https://github.com/blocklistproject/Lists/blob/master/ransomware.txt), [Antimalware](https://github.com/iam-py-test/my_filters_001/blob/main/antimalware.txt)*, and a few others (All listed in settings images). 
![image](https://user-images.githubusercontent.com/84232764/118559586-231aad80-b736-11eb-97fb-5ab479639f15.png)
![image](https://user-images.githubusercontent.com/84232764/118560312-4a25af00-b737-11eb-8f67-58704b7f7b86.png)

Advanced User Mode is on. 
![image](https://user-images.githubusercontent.com/84232764/118559626-362d7d80-b736-11eb-8e59-964877d83a2f.png)

### Notes

`ublockorigin.com` is the top result in DuckDuckGo so people will click on it:
https://duckduckgo.com/?q=ublock+origin&ia=web

![image](https://user-images.githubusercontent.com/84232764/118558637-f0bc8080-b734-11eb-909f-ab8a24288972.png)

`ublockorigin.com` tries to look like a real uBlock Origin related site, even their favicon is the uBlock Origin symbol: 

![image](https://user-images.githubusercontent.com/84232764/118558951-4abd4600-b735-11eb-9222-3e6e8af08346.png)

curl shows it claims it is the real uBlock Origin:
![image](https://user-images.githubusercontent.com/84232764/118559074-72aca980-b735-11eb-9be1-a1c6ec8c71cf.png)
![image](https://user-images.githubusercontent.com/84232764/118559840-8f95ac80-b736-11eb-8ff9-6b1c8c4e81cd.png)
![image](https://user-images.githubusercontent.com/84232764/118559863-98867e00-b736-11eb-9899-f69c874f0ac7.png)

`ublockorigin.com` is identified by McAfee WebAdvisor as malicious: 
https://www.siteadvisor.com/sitereport.html?url=ublockorigin.com
VirusTotal: https://www.virustotal.com/gui/url/1a306d3988f539861d6c6f62018dbea77250ecc353e39732640be5113b036d74/detection

There are no issues about `ublockorigin.com` in uAssets or uBlock:
https://github.com/uBlockOrigin/uAssets/issues?q=ublockorigin.com
https://github.com/gorhill/uBlock/issues?q=ublockorigin.com
No entries in badware.txt (I just updated it)
![image](https://user-images.githubusercontent.com/84232764/118559173-8a842d80-b735-11eb-80f5-b634f2e80f6a.png)
 

*Which is a custom list I created

**Comment by iam-py-test** [comment]
I can provide other information (i.e. OS) if needed

**Comment by mapx-** [comment]
https://www.reddit.com/r/uBlockOrigin/comments/hyct22/i_created_an_unofficial_ublockorigincom_homepage/

**Comment by iam-py-test** [comment]
Oh.
Sorry, I did not see that.

**Comment by krystian3w** [comment]
Maybe need daily checking whois to exclude problem of ensuring the continuity of domain/hosting payments.

**Comment by ajayyy** [comment]
ublockorigin.com is now misleading people into thinking some "AI" tools are created by the same people as uBlock Origin

![image](https://github.com/uBlockOrigin/uAssets/assets/12688112/7bd7a65b-d9c5-40c1-ac1a-6e477e16d831)
