### ISSUE TITLE
Getting an advertisement from google on top of the IGN sitemap

### ISSUE THREAD

**Issue by popemichael** [uBlockOrigin/uAssets#9118]
Greetings,

I'm getting an advertisement from google on top of the IGN sitemap despite manually blocking. (ISP Verizon)

I switched computers to an unrelated laptop on a separate tethered network. The advertisement is there as well.  (ISP T-Mobile) 

URL: `https://www.ign.com/sitemaps`

You have to scroll down a little and the scroll up as the advertisement is not there when you first goto the page. 

Manual blocking via the zapper and picker do no work in blocking for me.

https://i.imgur.com/f6VF459.png

Thank you!

**Comment by okiehsch** [comment]
@popemichael What browser do you use?

Can't reproduce, I can only guess it has something to do with `g01.ign` requests.
The inline-script triggering those requests can't be aborted using chromium because of a race condition.

**Comment by mapx-** [comment]
I get the ads:

`ign.com##+js(aost, Math.random, inlineScript)`
