### ISSUE TITLE
tmearn.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#912]
URL(s) where the issue occurs

http://tmearn.com/qTQH8

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
Pop-up @mapx-

**Comment by xDarkARG** [comment]
ADS @mapx-

**Comment by gorhill** [comment]
I got popups on my side -- blocking `https://web.tmearn.com/aaa.js` made them go away.

**Comment by gorhill** [comment]
How about:

    tmearn.com##script:inject(noeval-if.js, clickAnywhere)
