### ISSUE TITLE
H&M site content blocked when extension is installed

### ISSUE THREAD

**Issue by joannajjliu** [uBlockOrigin/uAssets#9121]
https://www2.hm.com/en_ca/productpage.0602673029.html
^ Cannot switch colors, or add to cart while on site with extension installed

### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### Versions

- Browser/version: [here]
- uBlock Origin version: [here]

### Settings

-

**Comment by okiehsch** [comment]
> add to cart

I can add to the "shoping bag" on my end.
I fixed the "Cannot switch colors" issue.
