### ISSUE TITLE
uBlock/assets/assets.json uses combinatronics.com instead of combinatronics.io

### ISSUE THREAD

**Issue by Combinatronics-commits** [uBlockOrigin/uAssets#9122]
The Combinatronics team is continuing it's support of this project.

Since the high traffic combinatronics.com urls now 302 redirects to combinatronics.io (to enable them to load faster) we suggest you update the project to make direct use of combinatronics.io since it saves a redirect (millions of unecessary requests per month for us) , lowers latency since combinatronics.io has more points of presence. combinatronics.io cache updates take two hours max.

To bypass censorship in specific countries we suggest for specific countries you continue to use combinatronics.com.

This might not be the right bug tracker but on the main bug tracker we get:
"An owner of this repository has limited the ability to open an issue from new users."

**Comment by uBlock-user** [comment]
@gorhill

**Comment by gorhill** [comment]
> it saves a redirect (millions of unecessary requests per month for us)

Sorry about this. The changes I made may take up to ~14 days to make it to all users, so these requests to `combinatronics.com` will gradually cease over the course of ~14 days.
