### ISSUE TITLE
add to list please: onelinks.site, linkgoo.site

### ISSUE THREAD

**Issue by pastormorris** [uBlockOrigin/uAssets#9125]
Good evening beautiful community, can you add these domains to the list? I give an example of each.

```
https://onelinks.site/
https://gdrivelatinohd.net/raya-y-el-ultimo-dragon-2021-bd50-full-1080p-latino-ingles-iso/
```
```

https://linkgoo.site/
https://www.descargatepelis.com/facultad-de-derecho-2021-temporada-1-1080p-web-dl/
```

This one does work:
```
https://drivelinks.me
https://www.peliculasgoogledrive.info/del-crepusculo-al-amanecer-1996-latino-bdrip-google-drive-onix/
```

Thank you!!

**Comment by krystian3w** [comment]
* to [filters-2021.txt](/uBlockOrigin/uAssets/blob/master/filters/filters-2021.txt) because you see ads?

* to [badware.txt](/uBlockOrigin/uAssets/blob/master/filters/badware.txt) because these are fake free streamings/downloading pages?

* IMO not for `resource-abuse.txt`, pages no have crypto mainers.

**Comment by pastormorris** [comment]
> * to [filters-2021.txt](/uBlockOrigin/uAssets/blob/master/filters/filters-2021.txt) because you see ads?
> * to [badware.txt](/uBlockOrigin/uAssets/blob/master/filters/badware.txt) because these are fake free streamings/downloading pages?
> * IMO not for `resource-abuse.txt`, pages no have crypto mainers.

quiero evitar el boton de espera de los 30 segundos, por cual para llegar a 0 debo hacer click en una publicidad.
https://gdrivelatinohd.net/raya-y-el-ultimo-dragon-2021-bd50-full-1080p-latino-ingles-iso/
En esa página se encuentran dos botones un para usuarios vip y otro para usuarios publico. Al hacer click me lleva al boton de los 30 segundos.

todo lo contrario sucede con esta página
https://www.peliculasgoogledrive.info/del-crepusculo-al-amanecer-1996-latino-bdrip-google-drive-onix/
al hacer click en el enlace publico el boton de los 30 segundos es filtrado (drivelinks.me) y me direcciona automaticamente al enlace: https://exey.io/PBkXiffK

perdón por la escritura, soy de argentina y utilizo google traductor.

Saludos!

**Comment by What-Zit-Tooya** [comment]
> 
> 
> > * to [filters-2021.txt](/uBlockOrigin/uAssets/blob/master/filters/filters-2021.txt) because you see ads?
> > * to [badware.txt](/uBlockOrigin/uAssets/blob/master/filters/badware.txt) because these are fake free streamings/downloading pages?
> > * IMO not for `resource-abuse.txt`, pages no have crypto mainers.
> 
> I want to avoid the 30 second wait button, for which to get to 0 I must click on an advertisement.

For bypass it, report it [here ](https://github.com/Sainan/Universal-Bypass), may be it will be added bypassed for it

**Comment by pastormorris** [comment]
> > > * to [filters-2021.txt](/uBlockOrigin/uAssets/blob/master/filters/filters-2021.txt) because you see ads?
> > > * to [badware.txt](/uBlockOrigin/uAssets/blob/master/filters/badware.txt) because these are fake free streamings/downloading pages?
> > > * IMO not for `resource-abuse.txt`, pages no have crypto mainers.
> > 
> > 
> > I want to avoid the 30 second wait button, for which to get to 0 I must click on an advertisement.
> 
> For bypass it, report it [here ](https://github.com/Sainan/Universal-Bypass), may be it will be added bypassed for it

https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt
In this list is the one that I want to add these two domains onelinks.site, linkgoo.site

For example there is this domain:
! https://github.com/uBlockOrigin/uAssets/issues/2760
@@ || googledrivelinks.com ^ $ ghide
googledrivelinks.com ### custom_html-7
googledrivelinks.com ##. adsbygoogle
googledrivelinks.com ### ai_widget-8
googledrivelinks.com ### ai_widget-10

and it works perfect, you can try here: https://www.peliculasgoogledrive.info/violento-y-furioso-2019-latino-1080p-google-drive-onix/

**Comment by pastormorris** [comment]
to download ;-)

**Comment by krystian3w** [comment]
uBO have fast working scriptlets:

https://github.com/gorhill/uBlock/wiki/Resources-Library#nano-sibjs-
https://github.com/gorhill/uBlock/wiki/Resources-Library#nano-stbjs-

IMO good decision is delete `nano-` prefix.

**Comment by pastormorris** [comment]
Thank you!
onelinks.site works perfect
linkgoo.site still not working

**Comment by mapx-** [comment]
update & test again

**Comment by pastormorris** [comment]
Good morning
updated list but not work (linkgoo.site)
[https://ibb.co/KG1jfm8](url)

**Comment by mapx-** [comment]
what does not work ??

**Comment by krystian3w** [comment]
Also try found filter "`*$xhr,redirect-rule=nooptext,domain=costumbresmexico.com"` in uBo logger:

https://github.com/gorhill/uBlock/wiki/The-logger

This exclude problem with see outdated file from `raw.githubusercontent.com` / CDN's (maybe useful try use [`updateAssetBypassBrowserCache`](https://github.com/gorhill/uBlock/wiki/Advanced-settings#updateassetbypassbrowsercache).

**Comment by pastormorris** [comment]
i need to skip that page eg public links button
https://www.descargatepelis.com/el-nieto-de-sardar-2021-1080p-web-dl-latino/

I need to skip https://linkgoo.site/ to go directly to the link, which would be this: https://pastes.descargatepelis.com/?v=Gvg

**Comment by uBlock-user** [comment]
@pastormorris do not post clickable links.

**Comment by pastormorris** [comment]
> @pastormorris do not post clickable links.

I'm sorry

**Comment by uBlock-user** [comment]
> i need to skip

uBO doesn't skip.
