### ISSUE TITLE
Could you considering combine "filters.txt,filters-2020.txt,filters-2021.txt"to one big list?

### ISSUE THREAD

**Issue by yeezylife** [uBlockOrigin/uAssets#9126]
It could be easier for people to subscribe.

**Comment by okiehsch** [comment]
It is "one big list", `filters-2020.txt`, and `filters-2021.txt` are sublists of `filters.txt` you only subscribe to one.

**Comment by gwarser** [comment]
> It could be easier for people to subscribe.

These lists are enabled by default - no need to subscribe manually. If you want to use it in other blocker, then it's pointless - they don't support the syntax.

**Comment by yeezylife** [comment]
> > It could be easier for people to subscribe.
> 
> These lists are enabled by default - no need to subscribe manually. If you want to use it in other blocker, then it's pointless - they don't support the syntax.

Thanks for explaining, And I just found out that other blocker won't work with ublock list indeed.

**Comment by yeezylife** [comment]
> Maybe run almost OK in only AdGuard.
> 
> Now AdGuard need only implement:
> 
> * `redirect-rule`
> * `dennyallow`
> * `*##` aka all urls (to property convert)
> * allow use  in any place of procedural cosmetic filter (ExtendedCSS) - now is limited to use at end due limitation of used  instead vanilla .`:upward()``Sizzle``document.querySelector`
> * maybe  if still are used for longer time on e.g.  pages`shide``.de`
> * disable generichide by network block filter  - AdGuard only allow version with `||*$ghide``,badfilter`
> * regex in  - coreLibs 1.8 no support regex but in Agust will be released coreLibs 1.9 with support regex for removeparam`removeparam`

I was using adguard for PC(I thought maybe it could filter out more ads on PC,not just in brosers),and I still seeing ads before youtube video.   When I switch to ublock origin,same list,no ad anymore!

**Comment by krystian3w** [comment]
AdGuard have other syntax for `json-prune` like:

`#%#//scriptlet("json-prune", [].bla-bla-car, uber)`

vs

`##+js(json-prune, *.bla-bla-car, uber)`

so then latest uBO filters no help and `Yuki2718` must manually try add new in "AdGuard Expermiental" before start in "AdGuard Base".
