### ISSUE TITLE
blocking resources may cause high cpu usage on some site

### ISSUE THREAD

**Issue by AdClear247** [uBlockOrigin/uAssets#9128]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported
- [x] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
    - If the issue is still present after wholly disabling uBO in the browser, then the issue is unrelated to uBO
- I tried to reproduce the issue when...
    - [x] uBO is the only extension
    - [x] uBO with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Basically you should find some way to prevent high cpu usage by scripts of site when we block some elements like images. I think redirection would work perfectly. I noticed few more websites exhibiting same behavior, kind of like punishes us for blocking resources or tries to load resource until it succeeds.

### A specific URL where the issue occurs

`https://forum.klix.ba/`

### Steps to Reproduce

1. go to url
2. block all images using this filter: `forum.klix.ba/$image`
3. refresh page

### Expected behavior:

should just block all images

### Actual behavior:

Blocks all images but counter shows increasing count >1k and in network monitor we can observe same image trying to reload.
You can verify this by watching counter or by watching network monitor of web browser or log of extension.
This images reloads billions times: `https://forum.klix.ba/styles/prosilver_se/theme/images/no_avatar.gif`
This script is guilty: `https://forum.klix.ba/ext/vse/topicpreview/styles/all/template/topicpreview.js?assets_version=254`
When I block that script too using filter `||forum.klix.ba/*topicpreview.js$script,` issue is resolved.
Result of network monitor: ![Screenshot](https://user-images.githubusercontent.com/81487643/118841881-fe0a7400-b8c8-11eb-9775-52cc38b20840.jpg)

### Your environment

* uBlock Origin version: 1.35.2
* Browser Name and version: Firefox 90.0a1
* Operating System and version: Windows 10 20H2

**Comment by gorhill** [comment]
Filter issues are to be reported at uAssets, as requested in template.
