### ISSUE TITLE
[breakage] tweakers.net , notifications icon is not working with updated uBO "uBlock filters" list

### ISSUE THREAD

**Issue by gitthehubs** [uBlockOrigin/uAssets#9129]
Exactly the same issue again as reported before:
https://github.com/uBlockOrigin/uAssets/issues/8839

**Describe the issue**

At the site `https://tweakers.net/` there is an icon for accessing your notifications and that is not working anymore, when you press the icon your notifications list is not opened anymore. No errors in the uBO logger.

**Versions**

-    Browser/version: Firefox 88.0.1 x64 / Windows 10 x64 all updated.
-    uBlock Origin version: 1.35.2

**Comment by XWB** [comment]
Might be related to https://github.com/uBlockOrigin/uAssets/commit/eef92196bd3a04da94ad48a93546fb2993df94c3

**Comment by crisp-tweakers** [comment]
Also images are (again) broken in articles: https://tweakers.net/nieuws/181910/ford-introduceert-elektrische-f-150-pick-uptruck-die-9-komma-6kw-kan-terugleveren.html

**Comment by XWB** [comment]
Images in news articles are broken as well.

**Before:**

![image](https://user-images.githubusercontent.com/1032281/118984994-5c455e80-b97e-11eb-9e7c-3bbe4fc11d62.png)

**After:**

![image](https://user-images.githubusercontent.com/1032281/118984970-5485ba00-b97e-11eb-9616-84b09d390474.png)

**Comment by gitthehubs** [comment]
> 
> 
> Might be related to [eef9219](https://github.com/uBlockOrigin/uAssets/commit/eef92196bd3a04da94ad48a93546fb2993df94c3)

That could be correct, I think I have this problem since 2 days.

**Comment by gitthehubs** [comment]
@crisp-tweakerss @XWB
Correct, same here with this filter list enabled. If I uncheck this filter list it works again.

**Comment by Wendelstein7** [comment]
I can confirm this issue! Toggling uBlock Origin toggles the breaking of lazyloaded media such as images and video.

**Comment by Smultie** [comment]
Does <Closed> mean it will be fixed?

**Comment by mapx-** [comment]
Did you update all lists ? then test again and report back
