### ISSUE TITLE
altadefinizione.pink

### ISSUE THREAD

**Issue by NessunoIM** [uBlockOrigin/uAssets#913]
Site: http://altadefinizione.pink
Page with problem: http://altadefinizione.pink/lost-translation-lamore-tradotto/ 
(or any film page on the site)

The issue is that I'm costricted to click on X to watch the film, but clicking on it cause to open a fake player with ads

![pppp](https://user-images.githubusercontent.com/19640640/33691084-df288324-dae6-11e7-9aaa-d9f220ae5271.png)

I use
- Browser/version: 57.0.1 (64 bit)
- uBlock Origin version: 1.14.20

### Notes
If I block the static elements (like fake play button or X button) I can't play the video.

**Comment by mapx-** [comment]
try this filter
`/watch.php?$popup`

**Comment by NessunoIM** [comment]
Oooh thanks, it works like a charm :D

**Comment by NessunoIM** [comment]
If I would the same rule on another site, how can I do?
This is http://hdpass.net/film.php?idFilm=11352?alta
It's the same site but rule doesn't work

**Comment by gorhill** [comment]
The following filter should work:

    hdpass.net##script:inject(disable-newtab-links.js)

**However**, since it uses a new scriptlet, this means that this will work only for the next release of uBO on AMO. With Chromium/Chrome, it should work immediately after forcing an update of _"uBlock filters"_.

**Comment by NessunoIM** [comment]
I add the filter but the new tab/popup has opened

**Comment by mapx-** [comment]
The `resources.txt` wasn't updated, still wait, better re-test tomorrow after updating "ublock filters"

**Comment by NessunoIM** [comment]
Ok, thanks to all :D

**Comment by okiehsch** [comment]
You are using Firefox, it will only work after the next release of uBlock on AMO `addons.mozilla.org`

**Comment by okiehsch** [comment]
@mapx- `ressource.txt`  has been updated and the new scriptlet works on my end.

**Comment by mapx-** [comment]
I meant on the user system, mine still ..old even purging all the caches

**Comment by okiehsch** [comment]
Oh, OK sorry I misunderstood if you have updated `ublock filters` in the last hour you need to clear
chrome-cache then update `ublock filters` or wait 60 minutes.

**Comment by gorhill** [comment]
There is also a delay from GitHub, often I have to wait a bit before GitHub serves me a just committed version.

**Comment by okiehsch** [comment]
It is 5 minutes after I commit before I get the updated list/version on my end.

**Comment by gorhill** [comment]
@NessunoIM You can install the dev build of uBO (1.14.21rc2) if you want: <https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta>. It contains the scriptlet needed for the filter above to work.

**Comment by NessunoIM** [comment]
Ok, thanks!

**Comment by NessunoIM** [comment]
I've installed now.
The difference is that now the newtab is opened in this link http://altadefinizone.click/HD/watch.php?u=
while before the newtab was opened in a link like this http://altadefinizone.click/HD/watch.php?u=aHR0cDovL2FsdGFkZWZpbml6aW9uZS5waW5rL2xvc3QtdHJhbnNsYXRpb24tbGFtb3JlLXRyYWRvdHRvLw==

The problem persist but is less annoying

**Comment by gorhill** [comment]
I don't get a new tab, either ways.

Did you add the following filter to _"My filters"_?

    hdpass.net##script:inject(disable-newtab-links.js)

**Comment by NessunoIM** [comment]
Ok, now is ok! I just restart the browser and now works perfectly.
Thank you so much :D

**Comment by MasterKia** [comment]
@gorhill 

Is it _**technically**_ possible to make a change that allows specifying URL parameter for `disable-newtab-links.js` scriptlet?

The use case would be similar to `window.open-defuser.js`: `example.com##+js(nowoif, adserver.com)`
