### ISSUE TITLE
imdb.com image viewer

### ISSUE THREAD

**Issue by leodoi3** [uBlockOrigin/uAssets#9131]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.imdb.com/name/nm0000237/mediaviewer/rm2009650945/?context=default`

### Describe the issue

 
When looking through image gallery there is a banner ad thats not being blocked, and a blank interstitial ad , but I still have to click next.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/46114199/119048164-b68cf200-b973-11eb-8e13-e9f0c915393d.png)
![image](https://user-images.githubusercontent.com/46114199/119048515-2d29ef80-b974-11eb-9fea-05221c1a9389.png)

### Versions

- Browser/version: FF 88.0
- uBlock Origin version: 1.35.2

### Settings

![image](https://user-images.githubusercontent.com/46114199/119048253-d4f2ed80-b973-11eb-9e6e-2a01df9fb0ef.png)
![image](https://user-images.githubusercontent.com/46114199/119048292-e2a87300-b973-11eb-9a5d-5e555d83848a.png)

### Notes
This may require multiple attempts as it doesn't always happen immediately.

**Comment by mapx-** [comment]
for the banner ad
`imdb.com##[data-testid="media-sheet__attr-banner"]`

I get no interstitial ad

@ryanbr

**Comment by leodoi3** [comment]
> 
> 
> I get no interstitial ad
> 
> @ryanbr

Actually it does block it , but i would still have to click next , it would be nice if it could just skip that altogether.
