### ISSUE TITLE
Lower quality videos with enabled adblocker issue

### ISSUE THREAD

**Issue by GKid94** [uBlockOrigin/uAssets#9133]
### URL(s) where the issue occurs

`https://www.telegraf.rs/jetset/vesti-jetset/3245399-marija-savic-stamenic-intervju-novinari-su-postali-lake-mete-od-dacica-i-dalje-cekam-odgovor-na-1-pitanje`

### Describe the issue

Some website show videos with a lower quality when adblock is enabled, is there a way that you can fix that with a filter or a uBlock option?

### Screenshot(s)

Attached

### Versions

- Browser/version: Brave 1.24.86 Chromium: 90.0.4430.212 (Official Build) (64-bit)
- uBlock Origin version: 1.35.2

![Screenshot 2021-05-21 121331](https://user-images.githubusercontent.com/18757054/119122203-91a98500-ba2e-11eb-887e-cb645c278ba9.jpg)

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled.

**Comment by uBlock-user** [comment]
Repro'd with `https://www.telegraf.tv/jetset/48504-oglasile-se-uraganke-nakon-nastupa-kakav-je-ovo-bio-vrisak`

**Comment by GKid94** [comment]
Sorry it was an issue with the Brave Shield in the browser, it was enabled

![Screenshot 2021-05-22 034429](https://user-images.githubusercontent.com/18757054/119211014-12f52c00-bab0-11eb-956f-06db28b030c0.jpg)
