### ISSUE TITLE
[NSFW] povaddict.com popunder

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9139]

**Comment by IThinkIAmCool** [comment]
still occurring on my phone (browser: Firefox)

**Comment by Yuki2718** [comment]
Can't reproduce but blocked crap script.

**Comment by IThinkIAmCool** [comment]
@Yuki2718 Ocurred again.

**Comment by Yuki2718** [comment]
Can't reproduce on Firefox desktop.

**Comment by ButterVsMargarine** [comment]
@Yuki2718 `[title="FREE FULL DOWNLOAD"]` Adsterra direct link ad. Could you add the regex filter to EasyList also and also add a regex that blocks direct links?

**Comment by Yuki2718** [comment]
Hm, I don't see any generic rule for document-block in EL.

**Comment by ButterVsMargarine** [comment]
There's a regex for Adsterra stuff in uBO - could you also add it in EasyList
And Asterra also has direct link ads => those could be addressed generically as well

**Comment by Yuki2718** [comment]
> There's a regex for Adsterra stuff in uBO

I know, and it seems EL doesn't have any such rule. I'd rather add to AG.

**Comment by ButterVsMargarine** [comment]
It used to use regex, can't you just add `/^https?:\/\/(?:www\.|[0-9a-z]{7,10}\.)?[-0-9a-z]{5,}\.com\/\/?(?:[0-9a-f]{2}\/){2,3}[0-9a-f]{32}\.js/$script,3p` to adservers?

**Comment by Yuki2718** [comment]
That's not my job and the EL authors know the rule.

**Comment by ButterVsMargarine** [comment]
@ryanbr

**Comment by huyszn** [comment]
There is also an ad link with the title `FREE DOWNLOAD` at the footer.
