### ISSUE TITLE
[Anti adblock] Simple Adblock Notice Pro WP plugin

### ISSUE THREAD

**Issue by hirorpt** [uBlockOrigin/uAssets#9146]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://baikin.net`

### Describe the issue

 
After waiting 10 seconds, you will see an adblock detection notification. 

### Screenshot(s)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/82331005/119223115-99525200-bb32-11eb-9f9a-9413d75d482e.png)
</details><br/>

### Versions

- Browser/version: Firefox/88.0.1
- uBlock Origin version: 1.35.2

### Settings

- Default + Fanboy’s Annoyance + uBlock filters – Annoyances  + JPN: AdGuard Japanese

### Notes

`/wp-content/plugins/simple-adblock-notice-pro^` in AdGuard Base works fine. (https://github.com/AdguardTeam/AdguardFilters/issues/15843)
Distribution site: `http://techsini.com/our-wordpress-plugins/simple-adblock-notice/`
Same plugin?: https://github.com/AdguardTeam/AdguardFilters/issues/83793

**Comment by IThinkIAmCool** [comment]
Right click and F12 are disabled on the distribution site.

**Comment by IThinkIAmCool** [comment]
And I also can't highlight text.

**Comment by uBlock-user** [comment]
@IThinkIAmCool link ?

**Comment by IThinkIAmCool** [comment]
`http://techsini.com/our-wordpress-plugins/simple-adblock-notice/`

**Comment by IThinkIAmCool** [comment]
I have uBO's 'uBlock filters -- Annoyances' enabled.

**Comment by IThinkIAmCool** [comment]
And Fanboy's Annoyance.

**Comment by hirorpt** [comment]
`techsini.com##+js(aeld, /^(?:contextmenu|cut|copy|keydown)$/)`
`techsini.com##p,h1,h2,h3,h4,h5,h6:style(-webkit-touch-callout: default !important; -webkit-user-select: text !important; -moz-user-select: text !important; -ms-user-select: text !important; user-select: text !important;)`
