### ISSUE TITLE
hdpornt.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#915]
URL(s) where the issue occurs

https://www.hdpornt.com/en/video/11511/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by zero77** [comment]
Try this for the top:
||ads2.contentabc.com/ads

and for the bottom:
 ###place_d_ehndp_footer
