### ISSUE TITLE
cutpaid.com popup

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9152]
I was checking for obsolete filters and needed fixes and I stumbled across some filters for cutpaid.com in uBO's 'uBlock filters' along  with `! https://forums.lanik.us/viewtopic.php?f=62&t=41669#p140881` so I visited `https://forums.lanik.us/viewtopic.php?f=62&t=41669#p140881`.

**Comment by IThinkIAmCool** [comment]
After I clicked for the first time on "Click here to continue" I encountered/got the popup.

**Comment by uBlock-user** [comment]
Test on default settings..

**Comment by IThinkIAmCool** [comment]
`https://cutpaid.com/7UC6pyKk` -> "Click here to continue"
