### ISSUE TITLE
simista.net "Ad block detected"

### ISSUE THREAD

**Issue by wxMichael** [uBlockOrigin/uAssets#9154]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://ww7.simista.net/`

### Describe the issue

uBO is detected and the page is replaced with the message "Ad block detected. Please disable your ad blocker and reload the page."

### Screenshot(s)

![image](https://user-images.githubusercontent.com/10516759/119245748-7e3f0c80-bb49-11eb-8455-d12cb63e8bc9.png)

### Versions

- Browser/version: Firefox Nightly 90.0a1 (2021-05-22) (64-bit)
- uBlock Origin version: 1.35.2

### Settings

- Default

### Notes

I created a new Firefox profile and set up uBO with default settings.

**Comment by okiehsch** [comment]
Looks like a parked domain.

**Comment by uBlock-user** [comment]
parked domain.
