### ISSUE TITLE
Streamsb  & its Mirrors {Ads}

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#9155]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
```
https://sbembed.com/embed-2hn7wzlg34v2.html
https://sbvideo.net/embed-2hn7wzlg34v2.html
https://sbembed1.com/d/2hn7wzlg34v2.html
```

source link= `cmovies.ac`

### Describe the issue

Popup ads

### Versions

- Browser/version: firefox A
- uBlock Origin version: 1.35

### Settings

uBO's default settings
-

**Comment by ghajini** [comment]
download is blocked due to `sbvideo.net##+js(nowoif)`
![IMG_20210523_121123](https://user-images.githubusercontent.com/20338483/119250990-8175df00-bbc1-11eb-9acc-ece8b93384fa.jpg)

**Comment by ghajini** [comment]
its opening popups again
add
`sbvideo.net##+js(aeld, click, popunder)`

**Comment by ghajini** [comment]
popup ads
firefox android, ubo 1.35.2

`https://sbplay.org/play/j4y747gqw8u2`

**Comment by mapx-** [comment]
test

```
sbplay.org##+js(aopr, console.clear)
sbplay.org##+js(nostif, Pop)
```

**Comment by ghajini** [comment]
still popups

**Comment by ghajini** [comment]
popups, using firefox

@`https://cloudemb.com/4otil2fa3kpv.html`
