### ISSUE TITLE
https://megaup.net

### ISSUE THREAD

**Issue by Jorge9811** [uBlockOrigin/uAssets#9165]
### URL(s) where the issue occurs

`https://megaup.net`

### Describe the issue

Anti ad-block

### Screenshot(s)

![megaUp](https://user-images.githubusercontent.com/54429803/119253415-8cac1900-bb87-11eb-8d0a-118c18055b1f.png)

### Versions

- Browser/version: Mozilla Firefox v88.0 x86
- uBlock Origin version: 1.35.2

### Settings

![Untitled3541](https://user-images.githubusercontent.com/54429803/108611606-d3d71200-73be-11eb-9183-cbddede51a17.png)

### Notes

[Add here the result of whatever investigation work you have done: please investigate the issues you report -- this prevents burdening other volunteers. This is especially true for issues arising from settings which are very different from default ones.]

**Comment by uBlock-user** [comment]
url ?

This doesn't happen on homepage.

**Comment by uBlock-user** [comment]
tested with `https://megaup.net/X5db/uBO.txt`

Working as expected...

test on default settings/lists and disable all other extensions

**Comment by What-Zit-Tooya** [comment]
> 
> 
> tested with `https://megaup.net/X5db/uBO.txt`
> 
> Working as expected...
> 
> test on default settings/lists and disable all other extensions

Tested on default and all addons disabled still detected on FF

**Comment by uBlock-user** [comment]
@What-Zit-Tooya Disable FF's tracking protection

**Comment by What-Zit-Tooya** [comment]
> 
> 
> @What-Zit-Tooya Disable FF's tracking protection

![1](https://user-images.githubusercontent.com/9832875/119259229-763da600-bbf7-11eb-8418-a7bed3c3c79c.png)
Already did on whitelist (FF does not provide disabled ETP, only standard, strict and custom) but problem still exist

**Comment by uBlock-user** [comment]
@What-Zit-Tooya something is blocking `adskeeper.co.uk` on your end, we have created specific exceptions that whitelist this ad-server, so if that domain is blocked you will see anti-adblock notice, this is for you to investigate.

**Comment by IThinkIAmCool** [comment]
Update uBlock Origin's 'uBlock filters'.

**Comment by What-Zit-Tooya** [comment]
@uBlock-user `adskeeper.co.uk` is inside of Peter Lowe's adservers & it also part of default list of UBO, how i can whitelist if its part of default setting of UBO?

**Comment by uBlock-user** [comment]
You don't have to, the exceptions are already part of the ublock filters list --


```
@@||jsc.adskeeper.co.uk/*/megaup.net$script,domain=megaup.net
@@||servicer.adskeeper.co.uk^$script,domain=megaup.net
```

**Comment by What-Zit-Tooya** [comment]
@uBlock-user Thank you, the problem is my DNS server is blocked `adskeeper.co.uk` , now fixed even ETP in strict mode.

**Comment by uBlock-user** [comment]
latest commit - https://github.com/uBlockOrigin/uAssets/commit/950355c829230315dc1049b1809aa80b04b95779

force update ublock filters list

**Comment by Jorge9811** [comment]
The problem was caused by blocking adskeeper.co.uk globally. Once I unblocked it and reloaded, it worked.
![](https://user-images.githubusercontent.com/54429803/119973985-87393f00-bf8a-11eb-8d3f-27542ec51e9e.png)

**Comment by Jorge9811** [comment]
@uBlock-user, could you please try to reproduce once more and reopen this issue if you can? Because it's happening again and unlike the last time, unblocking adskeeper.co.uk doesn't solve it.
I updated the filter lists too, for whatever that's worth.
![Untitled](https://user-images.githubusercontent.com/54429803/123276170-4e35b100-d4db-11eb-8772-53a0be143645.png)
![Untitled2](https://user-images.githubusercontent.com/54429803/123275564-ccde1e80-d4da-11eb-860d-f02c882c9f8d.png)

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/57b0371abf30baf11c1a69b684f1ea592f6e0112
