### ISSUE TITLE
tgpdog.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#917]
URL(s) where the issue occurs

https://www.tgpdog.com/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
update the filters of these @mapx- 

https://www.tgpdog.com/video/7678/sins-life-johnny-and-kissa-love-each-other

**Comment by mapx-** [comment]
I see no ads, provide complete info (what, where, etc)
