### ISSUE TITLE
Malware domain

### ISSUE THREAD

**Issue by iam-py-test** [uBlockOrigin/uAssets#9180]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - The only related issue is https://github.com/uBlockOrigin/uAssets/issues/960
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`thegay.com`

### Describe the issue
`thegay.com` is a malware site I discovered by reading https://github.com/easylist/easylist/issues/7918
It is not blocked by uBlock Origin
 

### Screenshot(s)
N/A

### Versions

- Browser/version: Edge  90.0.818.66
- uBlock Origin version: uBlock Origin development build v1.35.3b5

### Settings
Advanced user mode: On (No relevant rules)

-
![image](https://user-images.githubusercontent.com/84232764/119387510-0c74d900-bc97-11eb-8301-b47f7880148b.png)
![image](https://user-images.githubusercontent.com/84232764/119387645-37f7c380-bc97-11eb-879f-a6ab45d12e25.png)
![1](https://raw.githubusercontent.com/iam-py-test/Assets-001/main/images/Screenshot%202021-05-24%20135147.jpeg)
### Notes
I would like to see this malware domain blocked by uBlock Origin.
There are no references to it in uBlock Origin badware and URLHaus 
This domain is still online according to ping.
Verification: 
https://www.fortiguard.com/webfilter?q=thegay.com
https://safeweb.norton.com/report/show?url=thegay.com
https://www.siteadvisor.com/sitereport.html?url=thegay.com
https://quttera.com/detailed_report/thegay.com
https://sitecheck.sucuri.net/results/thegay.com
https://www.mywot.com/en/scorecard/thegay.com
https://www.virustotal.com/gui/url/4c0a08dc7b1e241b3f612b0552784fa5ab4ef9fac76ecb0afa2998ff6c4d3817/detection
https://www.urlvoid.com/scan/thegay.com/
https://github.com/iam-py-test/my_filters_001/commit/c65cac99993208e428221b92094edfe27ffa7e69
https://duckduckgo.com/?q=thegay.com+malware&ia=web (no relevant results)

**Comment by uBlock-user** [comment]
Adult content  !== malware domain

**Comment by iam-py-test** [comment]
@uBlock-user I did not open this issue because it is porn.
Check the links in the comment:
https://safeweb.norton.com/report/show?url=thegay.com

**Comment by iam-py-test** [comment]
![image](https://user-images.githubusercontent.com/84232764/119393209-a4c28c00-bc9e-11eb-8a68-c751a91d6cc6.png)
![image](https://user-images.githubusercontent.com/84232764/119393225-ab510380-bc9e-11eb-8650-aab117be7663.png)

**Comment by iam-py-test** [comment]
https://www.urlvoid.com/scan/thegay.com/

**Comment by uBlock-user** [comment]
Antivirues reports don't take uBlock Origin's default filter lists into into account when reporting it as possibly "risky".

**Comment by iam-py-test** [comment]
> Antiviruses reports don't take uBlock Origin's default filter lists into into account when reporting it as possibly "risky".

Is there is uBlock Origin's default filters that prevents this site from installing malware?
`/\/[a-z]{4,13}\/[a-z]{3,6}(\d\.){3}[0-9a-f]{32}\.js$/$script,1p,domain=hclips.com|hdzog.com|hotmovs.com|porn555.com|pornforrelax.com|pornj.com|pornl.com|pornq.com|puporn.com|see.xxx|shemalez.com|sss.xxx|thegay.com|thegay.porn|tubepornclassic.com|tuberel.com|txxx.com|upornia.com|voyeurhit.com`?

**Comment by uBlock-user** [comment]
There is _Online Malicious URL Blocklist_ enabled by default.

**Comment by iam-py-test** [comment]
Should I report it to them then?

**Comment by uBlock-user** [comment]
Your choice.

**Comment by iam-py-test** [comment]
Ok! Sorry for wasting your time
