### ISSUE TITLE
All Science X Network sites complain about adblockers

### ISSUE THREAD

**Issue by Nojuuu** [uBlockOrigin/uAssets#9182]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://techxplore.com/`
`https://medicalxpress.com`
`https://phys.org/`

### Describe the issue

Sites complain about using Enhanced Tracking Protection and maybe other blockers on Firefox.

Seems to also happen with strict blocking enabled on Edge. 

 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/84513173/119406541-a23a5380-bceb-11eb-9156-f797157c58c9.png)

### Versions

- Browser/version: 88.0.1 (64-bit)
- uBlock Origin version: 1.35.2

### Settings

-

### Notes
Maybe `+js(aopr, adBlockAlert)`  to block it?

**Comment by okiehsch** [comment]
We only add filters for issues reproducible with a default setup.
`medicalxpress.com##+js(nostif, check)`
works on my end, you can add that to your filter list.
