### ISSUE TITLE
Studeersnel.nl wrongly blocked

### ISSUE THREAD

**Issue by SamuelNorbury** [uBlockOrigin/uAssets#9184]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
https://studeersnel.nl

### Describe the issue

StudeerSnel.nl is wrongly blocked. Somehow it ended up on the list of issue #9105. We have no indication the website is compromised.

### Versions

- Browser/version: Mozilla Firefox 88.0.1 on ubuntu
- uBlock Origin version: v1.35.2

### Notes
The list of domains in #9105 is huge and possibly contains more incorrect blocks. The user who made that issue is also called "randomtroller", and that might be an indication of the _real_ issue at hand.

**Comment by JobcenterTycoon** [comment]
`issuu.nl` is ok too it just redirect to `https://issuu.com/`

**Comment by okiehsch** [comment]
`https://docplayer.nl` is also not a badware site.
