### ISSUE TITLE
justeat.it (can't select menu items)

### ISSUE THREAD

**Issue by Gigabyte29** [uBlockOrigin/uAssets#9191]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`www.justeat.it`

### Describe the issue

I can't click on any item from the restaurant menu with Ublock enabled.
To reproduce the issue:
1. Insert your address
2. Select a restaurant to order from
3. Try to select any item from the menu

### Versions

- Browser/version: [Firefox 88.0.1]
- uBlock Origin version: [1.35.2]

### Notes

I think that it occurs from blocking `d2egcvq7li5bpq.cloudfront.net` because when I disable Ublock and I block it manually with Noscript the same issue appears

**Comment by uBlock-user** [comment]
Broken by Fanboy Annoyances list, report to Fanboy.

@ryanbr

**Comment by Gigabyte29** [comment]
I've removed Fanboy annoyances list, updated and cleared cache but the issue remains.
Screenshots after removing Fanboy's list: `https://imgur.com/K7vybB1` `https://imgur.com/9gqYRZv`

**Comment by uBlock-user** [comment]
EasyList Cookie also has it. You're not default settings/lists.

**Comment by Gigabyte29** [comment]
Thank you and sorry for not having checked with default filters
