### ISSUE TITLE
kisscartoon.info - popup

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9195]
I got it after going to `https://kisscartoon.info/episode/american-dad-season-18-episode-6/` and clicking on the Play symbol/button.
![image](https://user-images.githubusercontent.com/84580704/119535027-41188b80-bd90-11eb-90db-cec150ec9140.png)

**Comment by IThinkIAmCool** [comment]
It got closed afterwards.

**Comment by mapx-** [comment]
@smed79 @AdamWr

bad filters in Liste FR

```
*$xmlhttprequest,3p,domain=gogomovies.to,badfilter
*$script,3p,domain=gogomovies.to,badfilter
```

tested link
`https://kisscartoon.info/episode/the-owl-house-season-2-episode-17/`

**Comment by AdamWr** [comment]
Okay, I have added these rules.

**Comment by ghost** [comment]
Does this one count as self-promotion or annoyance? (on kisscartoon.nz - new domain)

<img width="874" height="454" alt="Image" src="https://github.com/user-attachments/assets/bb946d96-c8b0-4f04-a92d-c6eb18fa8c11" />

**Comment by stephenhawk8054** [comment]
Any annoyances should be reported to https://github.com/easylist/easylist/issues/
