### ISSUE TITLE
[Anti Adblock] imgfrost.net

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#9196]
Link : `http://imgfrost.net/aucw5bhn`
Now as if malicious redirects weren't enough for this creepy developer, the site is now detecting adblock.
Specifically he has mentioned UB. Just see his banner. It looks so comic. Hehehe
![image](https://user-images.githubusercontent.com/80951522/119610763-584e8c00-be17-11eb-8d8b-27cb23f513b8.png)

**Comment by uBlock-user** [comment]
Already being worked in https://github.com/uBlockOrigin/uAssets/issues/9123
