### ISSUE TITLE
Blocked API request from PR-CY

### ISSUE THREAD

**Issue by iglv** [uBlockOrigin/uAssets#9197]
### URL(s) where the issue occurs

`https://pr-cy.ru/site-statistics/?domain=bing.com`

### Describe the issue

The API of the address for receiving data is being blocked and the tool does not work.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/1250680/119639765-98663c80-be20-11eb-8267-a987c1fa905c.png)
![image](https://user-images.githubusercontent.com/1250680/119639878-b338b100-be20-11eb-9342-daae0b275fe3.png)

### Versions

- Browser/version:  chrome 90.0.4430.212
- uBlock Origin version: 1.35.2

### Settings

default

### Notes

Blocked: `*##+js(no-floc)`

**Comment by uBlock-user** [comment]
![Capture](https://user-images.githubusercontent.com/21290713/119642436-5a751280-be38-11eb-8fff-6ce93dfda4eb.PNG)

**Comment by uBlock-user** [comment]
Happens even after disabling the filter, your site is broken due to CORS. Nothing to do with `no-floc`.

**Comment by iglv** [comment]
> Happens even after disabling the filter, your site is broken due to CORS. Nothing to do with `no-floc`.
> 
> Issue occurs even after disabling uBO.

Without uBO, everything works completely.

**Comment by uBlock-user** [comment]
share the picture of it working completely.

I see the same issue with Firefox where `no-floc` is never applied.

**Comment by iglv** [comment]
The error cannot be reproduced without uBO

**Comment by uBlock-user** [comment]
> share the picture of it working completely.

**Comment by mapx-** [comment]
> The error cannot be reproduced without uBO

I get the cors errors even disabling uBO, even using a russian ip

**Comment by uBlock-user** [comment]
`https://pr-cy.io/site-statistics/?domain=bing.com` with uBO and `no-floc` filter present on Chrome works fine.

**Comment by iglv** [comment]
Thanks a lot to everyone for help. The problem was due to the server's protection from DDOS.
