### ISSUE TITLE
ads not blocked

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#92]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

www.songspk.tv

redirected link=

http://104.154.237.93/MTcxNzgwNDg5OTA3LzE3MTc4MTc4NDAxNi8wN2dvbGxqcmVh?k=57a35f36cfe2d12712179.53211513&h=cac6728180b8baf312ee7f223185a14d95fcaeac&ban=12712179&iid=1470324534073733363092284481697409&r=1294109&ci=ERUCJ8gCDsRVY90Sc10VQZmXXBVSJhlWbURCJ0wDBMwGdZFULxVSm51VQlUSYp1GV4QDPoQAN4QDIswAbwFTVh1Tm51VQlUSYp1GCNwG7tRFElwAbUFWPtEXNdFUm51VQlUSYp1GVkwAb0lVQtEXJZmXXBVSJhlWbURCDsBXMVFWPZmXXBVSJhlWbI0Abk2GVQUCDsRVY90Sc10VQZmXXBVSJhlWbURCDsRXWB1SclkZedFUJlEWatRFJMwGcxUVY9kZedFUJlEWathQDshebUBRJMwGVh1TLxVTXBlZedFUJlEWatRFJkQAIMwGdZFULxVSm51VQlUSYp1GVgwAbwFTVh1Tm51VQlUSYp1GCNwGjthQ&pm=%3DsxWDlkWmVFWLx1Vc5lZUV1G&pabt=%3D%3DQVVx0V&pc=%3D%3DQALgwDAkQCMEgCMwACBcRC&sst=57%2F82%2F0%2F0%2F8&cbiframe=0&sgl=%3D%3DwG3B3G&id=12712179&crr=e698d1722f6035bfa20b%2C%2CwL2RnLrB3cn52bz5yd3d3LvoDc0RHa8a8c4150a4e89f1330c6&optt=b0FXVtFWXxFFwBnZNkAFBkwG&iuh=EtxDKchDKwgFlB1SY9FWqlxDIgwFK0gDLcRCXsADWUGXUZ1SRpXGQYlUaxlfZwlUQVVGVUHdtFncRkxDKchDKwgFl1EUytFXuxVVJlEeZARDPEUGC0wDXBlbZIQCXkACZ02dZokTW11VQ5WEZkwFMYRZYVVVQNkV0txAbgFTbUxGPsACXAQCLcxCNswFK0wGDsRSQthQ&ttc=4j994rrc

### Describe the issue

on going to www.songspk.tv, clicking anywhere in page opens a popup of long url 104.154.237.93 showing to update flash, install flv player or install this and that software...it should be blocked by ublock

### Screenshot(s)

will upload soon

### Versions

- Browser/version: google chrome Version 52.0.2743.116 m (64-bit)
and mozilla firefox 48  

- uBlock Origin version: 1.8.0

### Settings

- all default settoings

### Notes
intial redirecting url is  i think adexec.net/....... something long url or starting with 104.154.237.93 to whipzmarketing.........something like that...
![screenshot 23](https://cloud.githubusercontent.com/assets/20338483/17406976/3fb51e4a-5a83-11e6-9770-4af7b81be34d.png)
![screenshot 24](https://cloud.githubusercontent.com/assets/20338483/17406975/3fad7294-5a83-11e6-86ed-9d9da38702b6.png)
![screenshot 25](https://cloud.githubusercontent.com/assets/20338483/17406974/3fac1f3e-5a83-11e6-80b2-e74344f7d99c.png)
![screenshot 27](https://cloud.githubusercontent.com/assets/20338483/17407957/e2d34e6e-5a86-11e6-9682-02ca06776c15.png)

**Comment by ghajini** [comment]
is it filter related issue

**Comment by lewisje** [comment]
> is it filter related issue

That's what you're supposed to investigate; then if it is a filter issue, and it's with one of the lists that @gorhill maintains, that's what issues in this repository are for.

**Comment by ghajini** [comment]
i think privacy badgers heuristic blocking works fine than ublock origin

**Comment by gorhill** [comment]
Try `||104.154.237.93^$popup`.

**Comment by ghajini** [comment]
still popup opens....please fix

**Comment by gorhill** [comment]
I had a very hard time to reproduce. So here what will happen: since you can reproduce, use the logger and craft a filter to properly stop the popup, then submit your findings to whatever filter list maintainers are taking care of filter list for your region.

Alternatively, just use the no-popups switch for the site.
