### ISSUE TITLE
lasexta.com - antena3.com ( Anti right click in video )

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#9204]
### URL(s) where the issue occurs

```
https://www.lasexta.com/noticias/cultura/intrigas-censura-consternacion-cartas-ineditas-cela-muestran-texto-que-nunca-llego-ver-luz-papeles-son-armadans_2021032360ae28573610570001392e8b.html

https://www.antena3.com/series/mujer/noticias/evidente-demostracion-arif-sigue-enamorado-bahar_2021052660adf33b3610570001391674.html
```

### Describe the issue

Anti right click in video.

### Screenshot(s)

![Captura12314](https://user-images.githubusercontent.com/33556647/119724462-09ccdc00-be6f-11eb-82e0-7e6fce4b80bd.PNG)

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.35.2]

### Settings

Default and:

- spa, por: AdGuard Spanish/Portuguese 
- spa: EasyList Spanish

**Comment by mapx-** [comment]
@Yuki2718
