### ISSUE TITLE
[AntiAdBlock] nbcsports.com --  - Admiral

### ISSUE THREAD

**Issue by hirorpt** [uBlockOrigin/uAssets#9208]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.nbcsports.com/`

### Versions

- Browser/version: Firefox/88
- uBlock Origin version: 1.35.2

### Settings

Default + Fanboy Annoyance + uBO Annoyanse

### Notes
`||reconditerake.com^$third-party`
or
nbcsports.com##+js(acis, document.createElement, admiral)
``

**Comment by IThinkIAmCool** [comment]
@uBlock-user Why not also add `||reconditerake.com^$3p`

**Comment by uBlock-user** [comment]
@IThinkIAmCool because of EL DMCA notice incident of 2017, @pgl will add it.
