### ISSUE TITLE
corporacionwarez.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#921]
URL(s) where the issue occurs

https://corporacionwarez.com/

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
ADS

`https://corporacionwarez.com/windows-10-pro-1803-build-17134-285-64-bit-idioma-espanol/`

**Comment by smed79** [comment]
```
/display/items.*&
```
