### ISSUE TITLE
`||adjust.com^` is getting blocked…

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [uBlockOrigin/uAssets#9214]
### Prerequisites

- [X] This is not a support issue or a question
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

Any link with the domain name adjust.
https://www.adjust.com/

You can test is here: https://codepen.io/ThibaultJanBeyer/pen/gOmxZvp

### Describe the issue

Well. Adjust is in the blocked list. So even a link to the website like that:
```
<a href="https://www.adjust.com/">Adjust</a>
```
Is blocked when the user clicks on it.

I believe that this is faulty. Since adjust is a click tracking tool. We use adjust to wrap our links, something like this `https://app.adjust.com/<our-code>?redirect=https://<some-website>`. That gives us anonymous metrics on how many times the link was clicked, not even personal info on the user or something.

Seems heavy to me that an adblocker blocks harmless URLs even on a user-initiated action like a click on an A tag.

### Screenshot(s)

![image (1)](https://user-images.githubusercontent.com/12467511/119853696-b743fc00-bf10-11eb-92f3-6eaf5f61e9f6.png)

And other times

<img width="1440" alt="screenshot_2021-05-27_at_16 43 39" src="https://user-images.githubusercontent.com/12467511/119855285-122a2300-bf12-11eb-8168-19fcade0008e.png">

### Versions

- Browser/version: Chrome / 90.0.4430.212 (Official Build) (x86_64)
- uBlock Origin version: 1.34.0

### Settings

- No changes

**Comment by IThinkIAmCool** [comment]
Are you sure no IP address is sent whatsoever?

**Comment by IThinkIAmCool** [comment]
@pgl

**Comment by llacb47** [comment]
Adjust is click tracking and campaign tracking. Why shouldn't it be blocked. The user can bypass the block screen if they want to.

**Comment by uBlock-user** [comment]
> Since adjust is a click tracking tool.

Asked and answered yourself.

**Comment by ThibaultJanBeyer** [comment]
Ok well, seems pretty drastic to me. Even just a link to their website adjust.com is blocked 😅

Anyways. Thanks for your quick responses and your point that the user can bypass it makes sense, one would hope all users understand what they are doing and where this is coming from if they use your blocker :)

Cheers

**Comment by pgl** [comment]
@ThibaultJanBeyer Two things real quick:

1. If the service owner supplies a more specific list of subdomains that are dedicated to ads and tracking, then I will replace the entry for the main domain.
2. I constantly find it weird that people who are interested in tracking services like Adjust, but blocking tracking services, complain that the parent domains are blocked (and don't just add the relevant domain to their allow lists). I mean... I just don't get it.

**Comment by ThibaultJanBeyer** [comment]
Hey @pgl,
Yes I don't use uBlock and would not. This was a complaint from a customer. As an engineer, Adjust is super helpful, click tracking but also for deep link handling and redirects depending on OS. I assume that a good uBlock customer experience would be to block adjust but still redirect the user on the <a> tags, but I can see that technically it's not impossible on your end.
Anyways, your call. Was just expressing my thoughts. I understand your arguments, you want to have one of the most restrictive blocker out there, fine. We're looking into writing our own trackers/redirects in the long run.
Thanks for your feedback.

**Comment by pgl** [comment]
@ThibaultJanBeyer OK, so when uBlock blocks the tracking redirect, they are then aware that they're being tracked in this way (which they may not have been before), and they also get a clear option to permanently allow it if they choose. This is one of the primary purposes of uBlock Origin and other blockers.

I do understand that it prevents behaviour that's useful from your perspective, and sorry for the inconvenience, but putting agency back into the hands of users is, I think, important.

**Comment by ryanbr** [comment]
Sorry for being late to this. From `https://publicwww.com/websites/%22adjust.com%22/` it's just href links, not a network server item. (example, https://www.lamoda.ru/   , Google play/appstore links)

Blocking `||adjust.com` only affects the main www site. The better option is either @pgl to remove adjust or uBO badfilter it. @uBlock-user

**Comment by uBlock-user** [comment]
@ryanbr share one where I can see it happening in action.

**Comment by pgl** [comment]
Hey @ryanbr, I consider this a bounce tracker so for now I'll leave it on my list.

If someone supplies a more specific list of subdomains, then I can replace the main entry with those.

**Comment by ryanbr** [comment]
https://app.adjust.com could replace adjust.com if you want to prevent the clickthrough @pgl

**Comment by pgl** [comment]
@ryanbr Hmm - there seem to be quite a few other subdomains that are available: https://subdomainfinder.c99.nl/scans/2021-06-25/adjust.com

`app-<n>.adjust.com`, `*.ulink.adjust.com`, `c.`, etc.
