### ISSUE TITLE
anti-adb + anti-f12

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9216]
I commented on https://github.com/AdguardTeam/AdguardFilters/issues/81867 - https://github.com/AdguardTeam/AdguardFilters/issues/81867#issuecomment-849736462

**Comment by uBlock-user** [comment]
Don't open issues like this, just ping at the existing issue if it needs an update.

**Comment by IThinkIAmCool** [comment]
I didn't know if pinging you, for example, was appropriate.
