### ISSUE TITLE
simply-hentai.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#922]
URL(s) where the issue occurs

http://www.simply-hentai.com/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by zero77** [comment]
Try this:

||ads.theporndb.com/www/delivery/afr.php$subdocument

||util.sh-cdn.com/b331c5137ffe198b8307f7500b0ea39d$image

**Comment by KiLL4FuNK** [comment]
ADS

**Comment by utlasidyo** [comment]
Please update filters, it's filled with ads.

**Comment by utlasidyo** [comment]
Welp, it didn't lasted long.
