### ISSUE TITLE
www.clark.de signature service is being blocked 

### ISSUE THREAD

**Issue by Michael-Raudies** [uBlockOrigin/uAssets#923]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

https://www.clark.de/de/app/mandate/confirming

to get there, you can start to register on:

https://www.clark.de

### Describe the issue

We are an online broker and need to verify our customers by signature.

We use a service called "inSign".

Therefore we need an iframe to call that service.

Unfortunately uBlock interpretes the iframe as ad.
As the service is blocked our potential customers cannot register.

The signature is mandatory for registration.
We had several (potential) customers this week, reporting this issue.

How to reproduce:
Given I've uBlock installed on my webbrowser (mine is chrome)
Given I'm interested in using the services of clark, then I go to the website "clark.de".
I click the Button "Registrieren" and follow the steps.
Given I'm on the page https://www.clark.de/de/app/mandate/confirming I'm asked to give a signature, then I click on the signature field, an overlay occurs and there is an endless spinner.

### Screenshot(s)

uBlock turned on:
![image](https://user-images.githubusercontent.com/34337529/33714549-a2fd4a88-db4f-11e7-8430-4e370f7969b5.png)

uBlock turned off:
![image](https://user-images.githubusercontent.com/34337529/33714636-f707011e-db4f-11e7-89e5-8c84a65a2883.png)

Funktion of the field (no advertisement):
![image](https://user-images.githubusercontent.com/34337529/33715604-6a72d5b2-db53-11e7-9a51-2f3e0e4e83d9.png)

### Versions

- Browser/version: Chrome 62.0.3202.62 (Official Build) (64-bit)
- uBlock Origin version: uBlock Origin v1.14.20

### Settings

![image](https://user-images.githubusercontent.com/34337529/33714948-238c2056-db51-11e7-9902-a7dcfb450c56.png)

### Notes

I tried a lot of things before someone came up with the idea an ad blocker could be the problem.
Usual stuff like deleting cache and cookies, try in manipulate to reproduce our customers behaviour.
In the end just switching uBlock on and off is showing the results I screenshoted above. 

I tried with 
- Browser/version: safari Version 9.1.2 (11601.7.7)
- uBlock Origin version:  1.11.3.1

there was no problem at all.

**Comment by mapx-** [comment]
You should provide a test account.

**Comment by Michael-Raudies** [comment]
Thanks for the quick response.

Please go to:
https://www.clark.de/de/app/mandate/confirming

There will be a redirect.
Than you can click the following button to get to the page:

![image](https://user-images.githubusercontent.com/34337529/33718654-7d872d5a-db5e-11e7-85d9-f490fe9d43f2.png)

afterwards you have the step with the signing field.
I discovered, that it's the same issue on 

- firefox 57.0.1 (64-Bit).
- uBlock Origin v1.14.20

**Comment by mapx-** [comment]
if you add 
`@@||honeybadger.io/*/honeybadger.min.js$script,domain=clark.de`
does it work ?

If all ok I'll add temporarily the exception to the unbreak list so uBo users will be able to use the service.

However you'd need a fix in easyprivacy list @ryanbr @monzta

**Comment by Michael-Raudies** [comment]
Hi there,
it worked to add @@||honeybadger.io/*/honeybadger.min.js$script,domain=clark.de to my filters.

that would be awesome if you guys could adapt that!
