### ISSUE TITLE
memoryhackers anti-adblock

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#9230]
`https://ui.memoryhackers.org/game/pubg-mobile`
- Need account to test it
- when click load, no response
![image](https://user-images.githubusercontent.com/29838157/119918115-13029980-bf92-11eb-9a19-fbf558b227d0.png)

**Comment by mapx-** [comment]
do these filters work ?

```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=memoryhackers.org
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl$script,domain=memoryhackers.org
```
