### ISSUE TITLE
MyWOT.com Annoyances

### ISSUE THREAD

**Issue by iam-py-test** [uBlockOrigin/uAssets#9235]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://www.mywot.com/scorecard/google.com`

### Describe the issue
A fullpage, closable (via `X` in the corner), alert telling you to install its extension plus a banner which moves as you scroll. Blocking these does not prevent installation of their extension. There are also ads promoting their extension on the page. 
You will have to wait for the fullpage alert, but other annoyances and ads can be seen once the page loads.
I can also reproduce on other urls (i.e. `https://www.mywot.com/scorecard/duckduckgo.com`, `https://www.mywot.com/scorecard/pornhat.one`), but can not reproduce full-page alert or scrolling banner on home page.  However, homepage is almost completely promoting their extension and service.

 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/84232764/119979695-4bea4080-bf89-11eb-8a97-fb710b93838b.png)
![image](https://user-images.githubusercontent.com/84232764/119981194-57d70200-bf8b-11eb-93ef-bd606d4b27bb.png)
![image](https://user-images.githubusercontent.com/84232764/119981261-6a513b80-bf8b-11eb-8901-96a94ee7ece9.png)
![image](https://user-images.githubusercontent.com/84232764/119981277-71784980-bf8b-11eb-9e0d-4c06f927f895.png)
![image](https://user-images.githubusercontent.com/84232764/119981575-cddb6900-bf8b-11eb-9b48-ff96caa9fd32.png)

### Versions

- Browser/version: Firefox 88.0.1
- uBlock Origin version: uBlock Origin v1.35.2

### Settings

- Advanced User Mode: On
![image](https://user-images.githubusercontent.com/84232764/119980460-4ccfa200-bf8a-11eb-8da4-5212f9c1d133.png)
![image](https://user-images.githubusercontent.com/84232764/119980500-5a852780-bf8a-11eb-844e-05a5c0826a47.png)
![image](https://user-images.githubusercontent.com/84232764/119980700-a46e0d80-bf8a-11eb-9875-0853167b4190.png)
![image](https://user-images.githubusercontent.com/84232764/119980723-afc13900-bf8a-11eb-83ac-c68d6f59eae6.png)

All 3rd party frames and scripts blocked globally.

### Notes
Can reproduce with Annoyances enabled and disabled. Can also reproduce in another browser with different settings. 
I also can reproduce with uBlock Origin disabled. (or not installed - Safari iOS)
Not sure if these should be added as ads or annoyances. 
Once closed, the full page alert will not return until cookies are cleared, but ads and banner will persist.

**Comment by IThinkIAmCool** [comment]
cookie messages are not fixed by uAssets. You can report them to EasyList -- https://github.com/easylist/easylist/issues / https://forums.lanik.us/viewforum.php?f=62

**Comment by uBlock-user** [comment]
Ads are self promos(promoting their browser extensions), we don't fix these. As for other annoyances, you can report those to Fanboy and AdGuard's maintainers.

**Comment by krystian3w** [comment]
Page has double scroll due generic:

```
mywot.com##html:style(overflow: auto !important;)
```

![obraz](https://user-images.githubusercontent.com/35370833/142949138-29658896-a5e6-4fda-87c3-21d2685dbbcc.png)
