### ISSUE TITLE
Memoryhacker Comment forum

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#9236]
`https://memoryhackers.org/konular/get-confirmed-d.210896/`
forum can't comment/reply because adblock
need account

also pls support this `https://memoryhackers.org/forums/q-a.756/post-thread`

    post box didn't appear, just title form that appear when using ublock

if the link (`https://memoryhackers.org/forums/q-a.756/post-thread`) doesn't open, you can click "new thread" and make new thread... the form for the details is not appear... when ublock disabled... that appear...

**Comment by Dhanamerdeka** [comment]
also pls support this https://memoryhackers.org/forums/q-a.756/post-thread
- post box didn't appear, just title form that appear when using ublock

**Comment by Dhanamerdeka** [comment]
if the link (https://memoryhackers.org/forums/q-a.756/post-thread) doesn't open, you can click "new thread" and make new thread... the form for the details is not appear... when ublock disabled... that appear...

**Comment by uBlock-user** [comment]
Don't spam, use the edit button !

**Comment by Dhanamerdeka** [comment]
> Don't spam, use the edit button !

noted, sorry for that... i think since it different things, i using new comment instead edit it....
sorry
