### ISSUE TITLE
savelink.site issue

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9251]
https://github.com/AdguardTeam/AdguardFilters/issues/66542#issuecomment-850599178

**Comment by mapx-** [comment]
link ?

**Comment by IThinkIAmCool** [comment]
`https://savelink.site/sQUvXx7R` will delete soon I don't wanna get doxxed.

**Comment by IThinkIAmCool** [comment]
https://github.com/uBlockOrigin/uAssets/pull/9252
