### ISSUE TITLE
Outdated badware.txt

### ISSUE THREAD

**Issue by vladatros** [uBlockOrigin/uAssets#926]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
https://github.com/gorhill/uBlock/wiki/Badware-risks

### Describe the issue
Badware risk list seems to be outdated and not consistently enforced. Most of the articles are from 2012-2015 and some have been updated since.

Filter for some of the sites on the list is either not enforced, or the list need to be updated, or the sies found a way to circumvent it. Check out hard blocks for Chip.de and Softonic.net. If they have been removed from the list they need to be removed.
### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**]

### Versions

- Browser/version: Google Chrome 63
- uBlock Origin version: 1.14.20

### Settings

- no changes

**Comment by okiehsch** [comment]
> Filter for some of the sites on the list is either not enforced, or the list need to be updated

You link to the wiki article about the list, which was last updated 4 Aug 2016, not the actual list. https://github.com/uBlockOrigin/uAssets/blob/master/filters/badware.txt

**Comment by vladatros** [comment]
Fair enough, thanks for the updated list. It seems the issue still stands, softonic.net is in the updated list but I don't see any warnings

**Comment by okiehsch** [comment]
Softonic has been commented out.
To comment out is to render a block of code inert by turning it into a comment.
`! ||softonic.com^$document`

**Comment by vladatros** [comment]
What's the process for removal from the list? have there been any significant changes in softonic's behavior?

**Comment by okiehsch** [comment]
Regarding softonic read https://github.com/uBlockOrigin/uAssets/issues/476

**Comment by vladatros** [comment]
Got it. Thanks for this! I was worried these guys found a way to circumvent the filter. 

One more comment. If a wrapper was the only issue with Softonic then some others can also be removed, it seems

https://www.howtogeek.com/264592/download.com-has-finally-stopped-bundling-crapware/
Thanks!

**Comment by okiehsch** [comment]
@gorhill 
I tried a few links at `download.cnet.com` and all links were clean, so you could consider removing
`download.cnet.com` from the `badware.txt` list

**Comment by gorhill** [comment]
Sure.

If this starts to happen again, hopefully there will be coverage in the media and this will be ground to enable back the filter.
