### ISSUE TITLE
kpopsea.com [anti-adb]

### ISSUE THREAD

**Issue by What-Zit-Tooya** [uBlockOrigin/uAssets#9291]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://kpopsea.com/`

### Describe the issue

Anti adblock

### Screenshot(s)

![1](https://user-images.githubusercontent.com/9832875/120103925-2bcea300-c17c-11eb-8a63-596ad27f444e.png)

### Versions

- Browser/version: [FF 88.0.1]
- uBlock Origin version: [1.35.2]

### Settings

Default

### Notes

Recently updated all filters, but still detected

**Comment by JobcenterTycoon** [comment]
And anti right click
