### ISSUE TITLE
`newtorrentgame.com`-related

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9295]
So I found a supposedly adfly-related link by clicking on "Download" on like 2 "games".

I ended up adding these:
```
darenjarvis.pro##+js(adfly-defuser)
||setoyourad.biz^
||omyourfir.club^
||sinaunrelean.info^
```
to 'My filters'

**Comment by uBlock-user** [comment]
> adfly-related link 

care to share ?

**Comment by IThinkIAmCool** [comment]
> > adfly-related link
> 
> care to share ?

Sure! https://www30.darenjarvis.pro/pushredirect/?tmp=1&network=3&ios=0&site=adfly&c=3&ppi=16437565&pci=6417825055&t=1622382787&dest=https%3A%2F%2Fwww.file-up.org%2Fo99er973hqvl

**Comment by IThinkIAmCool** [comment]
There are more, but I'm not sure of the order

**Comment by IThinkIAmCool** [comment]
Also, popunder on `http://onizatop.net/ad/locked?rndad=1333102194-1622386063&url=DO5N&t=s&subid=16437565&h=12`

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/84580704/120108746-3c2c5100-c16f-11eb-9835-5c70c3dd7879.png)

**Comment by IThinkIAmCool** [comment]
`https://www55.darenjarvis.pro/pushredirect/?network=3&site=adfly&ppi=16437565&pci=6391426779&t=1622386128&dest=https%3A%2F%2Fwww.file-up.org%2F6yhxufmvop7v`

**Comment by IThinkIAmCool** [comment]
`https://www55.darenjarvis.pro/pushredirect/?network=3&site=adfly&ppi=16437565&pci=6391426779&t=1622386128&dest=https%3A%2F%2Fwww.file-up.org%2F6yhxufmvop7v`
