### ISSUE TITLE
www.auto-motor-und-sport.de

### ISSUE THREAD

**Issue by TonyTough** [uBlockOrigin/uAssets#93]
www.auto-motor-und-sport.de now uses "FuckAdBlock"

### URL(s) where the issue occurs

All subsites, i.e.
[http://www.auto-motor-und-sport.de/news/audi-mesarthim-gt-vision-und-f-tron-concept-sportler-mit-atomantrieb-11506685.html]
[http://www.auto-motor-und-sport.de/fahrberichte/jaguar-f-type-svr-tracktest-2016-11505463.html]

### Describe the issue

On subsites: Overlay is loaded, that says you have to deactivate your adblocker

### Versions

- Browser/version: Firefox 48.0 64bit
- uBlock Origin version: 1.8.0

### Settings

- default settings

### Notes

This filter works for Firefox:
www.auto-motor-und-sport.de##script:contains(FuckAdBlock)

**Comment by gorhill** [comment]
A simple ABP-compatible filter works: `@@||auto-motor-und-sport.de/werb.gif`. This should go into EasyList Germany.

**Comment by TonyTough** [comment]
Thanks,
that filter also works for me.

[I posted it to the Easylist Germany forum](https://forums.lanik.us/viewtopic.php?f=90&t=31474).

**Comment by ghost** [comment]
### Category

nuisance

### Description

Cookie notice

### Browser name and version

Microsoft Edge
Version 149.0.4022.52

### Other extensions used

- Bitwarden Passwortmanager
- SponsorBlock
- YouTube No Translation
- YouTube Row Fixer
- Return YouTube Dislike

### Country

Germany

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>




<img width="2552" height="1274" alt="Image" src="https://github.com/user-attachments/assets/c58bbd50-61a0-479e-b51e-afa44bce42a7" />



</details>


### Configuration

```yaml
name: uBlock Origin Lite
version: 2026.529.1448
browser: Edge 149 (win)
filtering:
 site: complete
 default: complete
permission: all
badge: 6
rules: 25726
rulesets:
 +adguard-spyware-url
 +annoyances-ai
 +annoyances-cookies
 +annoyances-notifications
 +annoyances-others
 +annoyances-overlays
 +annoyances-social
 +annoyances-widgets
 +block-lan
 deu-0
 easylist
 easyprivacy
 pgl
 ublock-badware
 ublock-filters
 urlhaus-full
scripting:
 ublock-filters.main
 ublock-filters.isolated
 easyprivacy.main
 easyprivacy.isolated
 ublock-badware.main
 annoyances-cookies.main
 annoyances-cookies.isolated
 annoyances-overlays.main
 annoyances-overlays.isolated
 annoyances-social.isolated
 annoyances-others.main
 annoyances-others.isolated
 annoyances-notifications.main
 annoyances-notifications.isolated
 css-generic-all
 css-generic-some
 prevent-popup
 css-specific
console:
 [0605.1241]insertCSS/Error: No frame with id 39 in tab with id 72666887
```
