### ISSUE TITLE
https://www.marinetraffic.com

### ISSUE THREAD

**Issue by DiaoulDu** [uBlockOrigin/uAssets#9312]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.marinetraffic.com`
### Describe the issue

When ublock-origin is enabled, you cannot see any relevant infos about vessels sailing. Desabling ublock and it runs well.

### Versions

- Browser/version: [Firefox 88.0.1]
- uBlock Origin version: [v1.35.2]

### Settings
Other extensions : I Dont care about cookies / Neat URL / Cookie Quick Manager / LightBeam / DecentralEyes

**Comment by uBlock-user** [comment]
> you cannot see any relevant infos about vessels sailing

Where is this present ?

**Comment by DiaoulDu** [comment]
with ub enabled you only get a kind of blue screen, without it you can see a lot of stuff and in the upper right a "Search Marine Traffic" letting you to enter the name of a vessel and see where he was located for the last time (on a live map).
Marine Traffic is based on AIS system installed worldwide on all sorts of vessels ...

**Comment by uBlock-user** [comment]
> you can see a lot of stuff and in the upper right a "Search Marine Traffic" letting you to enter the name of a vessel and see where he was located for the last time (on a live map).

Yeah I can do all of that with uBO enabled. Test on default settings + all other extensions disabled.

**Comment by DiaoulDu** [comment]
Ok, I'll do that , thanx.

**Comment by DiaoulDu** [comment]
unfortunately I've disabled extensions one by one, erased cache and cookies, back to default ubo config ... and does not work
any more ...
Hum, sounds strange, will try tomorrow without my firefow account.
Cheers.

**Comment by uBlock-user** [comment]
what doesn't work exactly ? Show us a picture or two

**Comment by DiaoulDu** [comment]
https://www.marinetraffic.com/fr/ais/home/centerx:-4.4/centery:48.8/zoom:10

is the URL redirected when I try to access https://www.marinetraffic.com, 4.4 / 48.8 is the last GPS point I enter some
days ago. Looks like the whole stuff is well printed first and then all my screen get blue. No need image, the whole
page is just blue without anything else.
What  is amazing is that I'm redirected to the URL below and cache and cookies are been erased, so the site seems to keep what I've done recently.

**Comment by DiaoulDu** [comment]
<body >
    
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MPLMZR5"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <main role="main" style="height: 100%;">
    <div id="app" style="height: 100%;">
        <div style="height:1000px; width:100%; clear:both;"></div>
    </div>
</main>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"657a7c696e293329","token":"4041645118394dfe82ed1a62f21ff397","version":"2021.5.2","si":10}'></script>
</body>
<script type="text/javascript" src="/js/70.mtapp.380.8381c0.js" async></script><script type="text/javascript" src="/js/69.mtapp.380.8381c0.js" async></script><script type="text/javascript" src="/js/71.mtapp.380.8381c0.js" async></script><script type="text/javascript" src="/js/74.mtapp.380.8381c0.js" async></script><script type="text/javascript" src="/js/73.mtapp.380.8381c0.js" async></script><script type="text/javascript" src="/js/72.mtapp.380.8381c0.js" async></script><script type="text/javascript" src="/js/65.mtapp.380.8381c0.js" async></script><script type="text/javascript" src="/js/67.mtapp.380.8381c0.js" async></script><script type="text/javascript" src="/js/66.mtapp.380.8381c0.js" async></script><script type="text/javascript" src="/js/mtapp.380.8381c0.js" async></script></html>

**Comment by DiaoulDu** [comment]
Sorry for this last not relevant cut/paste ...

**Comment by DiaoulDu** [comment]
![marineTraffic](https://user-images.githubusercontent.com/8970219/120118335-53306a80-c192-11eb-8d2c-9fad535b3e84.PNG)

**Comment by uBlock-user** [comment]
> is the URL redirected when I try to access https://www.marinetraffic.com, 4.4 / 48.8 is the last GPS point I enter some
days ago. Looks like the whole stuff is well printed first and then all my screen get blue. No need image, the whole
page is just blue without anything else.
What is amazing is that I'm redirected to the URL below and cache and cookies are been erased, so the site seems to keep what I've done recently.

Site issue, I started experiencing the redirection on Nightly too even with uBO disabled but not on stable...yet.
