### ISSUE TITLE
video player not working on eu.usatoday.com

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9320]
`https://eu.usatoday.com/story/news/health/2021/05/27/covid-global-infections-variant-vaccine-fda-biden/7457447002/`

**Comment by mapx-** [comment]
@ryanbr

**Comment by ryanbr** [comment]
WFM. which filter is causing it?

**Comment by mapx-** [comment]
![image](https://user-images.githubusercontent.com/10303732/120145262-82bb9300-c1e3-11eb-8707-a1d3b7221ab2.png)

@ryanbr
