### ISSUE TITLE
[anti-adblock] innal.top

### ISSUE THREAD

**Issue by avotoko** [uBlockOrigin/uAssets#9326]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://seedoff6.innal.top/`

### Describe the issue

The anti-adblock message appears and I cannot browse the page.

### Screenshot(s)

![screenshot](https://user-images.githubusercontent.com/53560467/120171845-6c422580-c23d-11eb-9413-f957c21895de.jpg)

### Versions

- Browser/version: Firefox 88.0.1
- uBlock Origin version: v1.35.2

### Settings

- RUS: RU AdList

### Notes

filter to resolve the issue.
```
innal.top###e7af0de8b4:style(height:15px;display:none)
```

**Comment by P0Rtvine** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
These sites have been promoting malware for many years, and they require disabling the blocker. And those rules that should prevent the anti-adblock from being triggered are bypassed very quickly. I've changed them many times to make sure it doesn't make any sense. These sites just need to be blocked as malicious.

As an experiment to check the response time: https://github.com/easylist/ruadlist/commit/7c4dd1daff8259b107843867d703ed08b5b9a370

**Comment by uBlock-user** [comment]
@dimisa-RUAdList They're targeting you btw as per the logs.

**Comment by dimisa-RUAdList** [comment]
@uBlock-user Yes I know. If within 24 hours the added scriptlet becomes useless, I will return the blocking of these sites so that when they are opened there is just a blank sheet.

**Comment by dimisa-RUAdList** [comment]
As far as I can see, the scriptlet has already become useless, and the detector is triggered on any transition.

https://github.com/easylist/ruadlist/commit/0a44731ba7c2fc89819b200ae9fb43ef2fa6df33

**Comment by uBlock-user** [comment]
@dimisa-RUAdList okay I will remove the filters added in ublock list.
