### ISSUE TITLE
mofos.com [NSFW]

### ISSUE THREAD

**Issue by electrifying** [uBlockOrigin/uAssets#9327]
### URL(s) where the issue occurs

`https://www.mofos.com/`
### Describe the issue

add rules from the uBlock filters – Annoyances to remove the banner at the bottom
### Screenshot(s)
`https://imgur.com/ml0g7wS`

### Versions

- Browser/version: google chrome 91
- uBlock Origin version: 1.35.2

### Settings

uBO's default settings
-

### Notes

none

**Comment by uBlock-user** [comment]
Self promo, we don't fix these in uBO.
