### ISSUE TITLE
holyclock.com bad redirect

### ISSUE THREAD

**Issue by HLFH** [uBlockOrigin/uAssets#933]
### URL(s) where the issue occurs

`http://www.leava.fr/`

### Describe the issue

On Saturday, access to this website is blocked and redirects to holyclock.com.
I do not consider that blocking a website, whatever the reason is, is a good thing.

```js
                <!-- HolyClock.com <HEAD> code for leava.fr -->
        <script type="text/psajs" orig_index="6">//<![CDATA[
_holyclock_id="bb85a1671890f6643970029eb14cb08e";_holyclock_tag='<s'+'cript src\x3d"//www.holyclock.com/holyclock.js?'+Math.floor(+new Date/864E5)+'">\x3c/script>';null!==document.cookie.match(/(?:^|;)\s*_holyclock_qr=\s*\w/)&&null===window.location.hash.match(/#holyclock=qr(?=#|$)/)&&document.write(_holyclock_tag);
//]]></script>
        <!-- HolyClock.com <HEAD> code for leava.fr -->
```

### Versions

- Browser/version: Chrome Version 62.0.3202.94 x64
- uBlock Origin version: v1.14.20

### Notes

Adding `||holyclock.com^$third-party` in **My Filters** fixes the issue.

**Comment by gorhill** [comment]
That is not an ad, it's just a religious thing. That is outside the purpose of uBO's filters.

**Comment by mapx-** [comment]
use it as custom filter
`||holyclock.com/holyclock.js$domain=leava.fr`

**Comment by HLFH** [comment]
@gorhill You were saying in your `README.md` that:

> uBlock Origin is NOT an "ad blocker": it is a wide-spectrum blocker. 

You demonstrate here it is only an ad blocker.

**Comment by gorhill** [comment]
> You demonstrate here it is only an ad blocker

There is no uBO filter lists for _annoyances_. Use dynamic filtering to block `holyclock.com` as you wish -- dynamic filtering is what makes uBO a wide-spectrum blocker, one can work in [default-deny](https://github.com/gorhill/uBlock/wiki/Blocking-mode) mode out of it.
