### ISSUE TITLE
foreca.com

### ISSUE THREAD

**Issue by Nojuuu** [uBlockOrigin/uAssets#9333]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.foreca.com/`

### Describe the issue

Ad placeholders on mobile,

 

### Screenshot(s)
![image](https://user-images.githubusercontent.com/84513173/120218103-ec6a8a00-c241-11eb-987f-a4fd50520fdc.png)

### Versions

- Browser/version: Firefox 88.0.1 
- uBlock Origin version: 1.35.2

### Settings

- No changes

### Notes

To fix:

```
!#if env_mobile
! -- AD PLACEHOLDERS --
foreca.com##.a1i32s5g
!#endif
```
or just:
```
foreca.com##.a1i32s5g
```

**Comment by Nojuuu** [comment]
Or maybe not mobile only since these appear on desktop too when your window is small enough.

**Comment by Nojuuu** [comment]
![image](https://user-images.githubusercontent.com/84513173/120224233-c21dca00-c24b-11eb-8245-1f71d805e0c2.png)


Also just noticed this on **desktop** version.

```
foreca.com##.aoju7e5
```

**Comment by uBlock-user** [comment]
@ryanbr `foreca.com##.aoju7e5`

**Comment by Nojuuu** [comment]
![image](https://user-images.githubusercontent.com/84513173/120229988-0c587880-c257-11eb-93c1-299487638ff8.png)

**Comment by uBlock-user** [comment]
`foreca.com##main > div > div > div[class]:matches-css(width:350px)` will work

**Comment by Nojuuu** [comment]
@uBlock-user 

Didn't work,

But maybe this would be better in EasyList. I can post this issue there if that's ok?

**Comment by uBlock-user** [comment]
> Didn't work,

on mobile ?

**Comment by Nojuuu** [comment]
> 
> 
> > Didn't work,
> 
> on mobile ?

Yes, Purged cache and updated everything, still there. 

I'd maybe just add these to EasyList: 
`foreca.com##.a1i32s5g`
`foreca.com##.aoju7e5`

**Comment by uBlock-user** [comment]
try `foreca.com##main > div > div > div > div[class]:matches-css(min-height:326px)`

**Comment by Nojuuu** [comment]
> 
> 
> try `foreca.com##main > div > div > div > div[class]:matches-css(min-height:326px)` on mobile
> 
> 

That seems to work for first one but theres two more if you check image i posted in OP. All three have same className.

**Comment by uBlock-user** [comment]
fixed with https://github.com/uBlockOrigin/uAssets/commit/224aa2eff92a640bc2fe527cac40f79a31df77fb

**Comment by Nojuuu** [comment]
> 
> 
> fixed with [224aa2e](https://github.com/uBlockOrigin/uAssets/commit/224aa2eff92a640bc2fe527cac40f79a31df77fb)

Still there. 
Purged, updated etc.

**Comment by uBlock-user** [comment]
Add --

```
foreca.com##main > div > div > div > div[class]:matches-css(min-height:326px)
foreca.com##main > div > div > div > div > div[class]:matches-css(min-height:326px)
```

to my Filters then. 

Seems adding them to the list and they don't get applied, but they work when present in my Filters....

**Comment by Nojuuu** [comment]
> 
> 
> Add --
> 
> ```
> foreca.com##main > div > div > div > div[class]:matches-css(min-height:326px)
> foreca.com##main > div > div > div > div > div[class]:matches-css(min-height:326px)
> ```
> 
> to my Filters then.
> 
> Seems adding them to the list and they don't get applied, but they work when present in my Filters....

Yeah, seems to work in My Filters.

**Comment by Nojuuu** [comment]
@uBlock-user  I tried and noticed it worked on other FF Android versions. so I went to spam force update couple times to all lists and seems like it started to work now. 

No need to tag gorhill, problem was on my end.

**Comment by uBlock-user** [comment]
@Nojuuu I can still reproduce it in _Responsive Design mode_

**Comment by Nojuuu** [comment]
> 
> 
> @Nojuuu I can still reproduce it in _Responsive Design mode_

You need to remove env_mobile if you want it to work on desktop too.

`!#if env_mobile` seems to only work when you are actually on mobile device.

**Comment by gorhill** [comment]
> Would be nice though if env_mobile would work also when trying to emulate a mobile device in dev tools.

It should work if you select a specific device in dev tools.

**Comment by Nojuuu** [comment]
> It should work if you select a specific device in dev tools.

Chrome:
![image](https://user-images.githubusercontent.com/84513173/120246680-a3362c80-c279-11eb-8f1e-caf545f4e06a.png)

FF:
![image](https://user-images.githubusercontent.com/84513173/120246895-543cc700-c27a-11eb-8be8-f82ef5187680.png)

**Comment by gorhill** [comment]
Force a reload of the page after you select a device -- but anyways, the user agent change is only seen by the page, not by the rest of the browser (including uBO), so this won't affect uBO's behavior. I could add an advanced setting to force uBO into a specific flavor so as to modify its behavior.

**Comment by gorhill** [comment]
Right, the user agent change is only seen by the page, not by the rest of the browser (including uBO), so this won't affect uBO's behavior. I could add an advanced setting to force uBO into a specific flavor so as to modify its behavior.
