### ISSUE TITLE
streaminglearningcenter.com

### ISSUE THREAD

**Issue by strict-block** [uBlockOrigin/uAssets#9339]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://streaminglearningcenter.com/codecs/google-adding-hevc-playback-to-chrome-seems-like-a-longshot.html`

### Describe the issue

* Pop-up with locked scroll, but now @ryanbr can these cut in Fanboy Annoyance, 
 
* also AdGuard Annoyance like use filters with `:style(` or `+js(` to abort/hide pop-ups if page have visitors in Alexa Ranks (if no have visitors then prefere copy filters to own "user rules" (Yes, AdGuard use "rule" then uBo use "Filters", also "Filter" = "list with many rules").

Pop-up should be loaded after few minutes, no need click anywhere on page or use scroll.

### Screenshot(s)

![obraz](https://user-images.githubusercontent.com/79422224/120317682-3eadb880-c2df-11eb-87ff-c81f56192110.png)

### Versions

- Browser/version: Firefox 89 / Chrome 91
- uBlock Origin version: 1.35.5b7

### Settings

- stock + uBO Annoyances (no tested how help network rules from Fanboy's Annoyances or fixing by AdGuard Annoyance).

### Notes

May works these:

```css
streaminglearningcenter.com##.tl-states-root
streaminglearningcenter.com##body.tve-hide-overflow, html.tve-hide-overflow:style(overflow: auto !important; padding-right: 0 !important;)
```

**Comment by uBlock-user** [comment]
I see a different popup which is dismissable --

<details>

![Capture](https://user-images.githubusercontent.com/21290713/120366187-fe752700-c32c-11eb-9c1a-a7938be5f2cf.PNG)

</details>

**Comment by strict-block** [comment]
My also have close button, I mean trouble with locked scroll:

`##body.tve-hide-overflow, html.tve-hide-overflow:style(overflow: auto !important; padding-right: 0 !important;)`

Maybe good is write something:

> Due to the new idea development of the Fanboy's Annoyance project (project started added scriptlets and `:style(`), we are no longer accepting submissions of irtating items with blocked scrolling, please submit them overridden to the EasyList repository.

**Comment by strict-block** [comment]
Compressed to zip page with enabled pop-up:

[Google Adding HEVC Playback to Chrome Seems like a Longshot - Streaming Learning Center.zip](https://github.com/uBlockOrigin/uAssets/files/6580757/Google.Adding.HEVC.Playback.to.Chrome.Seems.like.a.Longshot.-.Streaming.Learning.Center.zip)

@okiehsch  / @mapx- / @yourduskquibbles
