### ISSUE TITLE
Should trafic-site.ro as a third party be blocked for privacy reasons?

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9343]
![image](https://user-images.githubusercontent.com/84580704/120476387-33c45800-c3b3-11eb-9a8c-e5fa29a357dd.png)

**Comment by uBlock-user** [comment]
Questions are to be posted on reddit -- https://www.reddit.com/r/uBlockOrigin/

**Comment by IThinkIAmCool** [comment]
It's also meant to let filter list developers know about this.

**Comment by uBlock-user** [comment]
> let filter list developers know about this.

Make a case about it by filling in the template and justifying why it shuld be blocked. This is NOT the place to ask questions.
