### ISSUE TITLE
uiz.io

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9344]
![image](https://user-images.githubusercontent.com/84580704/120496977-b4d91a80-c3c6-11eb-9f1b-f700cd2b7d45.png)
Should this be addressed?

**Comment by JobcenterTycoon** [comment]
its scam but the fake survey page `ogtrk.net` is already blocked

**Comment by iam-py-test** [comment]
For me visiting the domain mentioned redirects to `https://appcall.me/nms/login`.

**Comment by iam-py-test** [comment]
Appears to be a url shortener? 
https://www.mywot.com/scorecard/uiz.io
https://translate.google.com/?sl=auto&tl=en&text=Этот%20сайт%20делает%20вредоносные%20ссылки%20из%20нормальных%20ссылок%20!!!%0A&op=translate
https://translate.google.com/?sl=auto&tl=en&text=СУПЕР%20САЙТ%20НОРМАЛЬНЫЙ%20ЗАРАБОТОК%20НО%20ЕСТЬ%20ЕЩЕ%20КУЧА%20ПОДОБНЫХ%20СМ%20ЗДЕСЬ%20%20yadi.sk%2Fi%2FCB-Gfq33OUvT1g%0A%0A&op=translate

**Comment by iam-py-test** [comment]
https://trustscam.com/uiz.io
