### ISSUE TITLE
mediafax.ro / youbora

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9345]
![image](https://user-images.githubusercontent.com/84580704/120498353-d4bd0e00-c3c7-11eb-8048-98d75f72a77b.png)

`https://segment.com/integrations/youbora/`
`https://www.youtube.com/watch?v=QzBb_RkTmuI`
`https://www.youtube.com/watch?v=zcmMWeW7obU`

**Comment by IThinkIAmCool** [comment]
@ryanbr @pgl

**Comment by llacb47** [comment]
Would it kill you to write some words about 
1) what you are reporting
2) where you found it
3) why it needs to be blocked

???

**Comment by IThinkIAmCool** [comment]
> `https://segment.com/integrations/youbora/`
> `https://www.youtube.com/watch?v=QzBb_RkTmuI`

**Comment by IThinkIAmCool** [comment]
> 
> 
> Would it kill you to write some _words_ about
> 
>     1. what you are reporting
> 
![image](https://user-images.githubusercontent.com/84580704/120499264-96741e80-c3c8-11eb-94a5-fa860d995856.png)

>     2. where you found it
> 
`https://www.mediafax.ro/`
>     3. why it needs to be blocked
> 
It might need to be, that's why I mentioned Fanboy and Peter Lowe.
Could you check out: `https://segment.com/integrations/youbora/` and `https://www.youtube.com/watch?v=QzBb_RkTmuI`?
>

**Comment by mapx-** [comment]
Report directly at EL repository.

**Comment by IThinkIAmCool** [comment]
I wasn't sure if this was going to be blocked in 'uBlock filters -- Privacy', 'Peter Lowe’s Ad and tracking server list' or 'EasyPracy'.

**Comment by IThinkIAmCool** [comment]
Nevermind, I found `@@||youbora.com/*/js/adapters/jwplayer$script` in EasyPrivacy.

**Comment by pgl** [comment]
@IThinkIAmCool 

For future reference, the uBlock Origin logger will tell you exactly which filter list entry is causing a block.

I do have to say, this is a rather low-effort issue report. It really would be appreciated if you could would be a bit more considerate of people's time.
