### ISSUE TITLE
ghacks.net

### ISSUE THREAD

**Issue by Pccode66** [uBlockOrigin/uAssets#9348]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.ghacks.net/latest-posts/`

### Describe the issue
 
There are "Ghacks Deals" (ads) in the latest posts page, and they look the same as normal posts.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/49125134/120563199-620b5d00-c3de-11eb-8e54-f659e5eac7c9.png)

### Versions

- Browser/version: 89.0
- uBlock Origin version: 1.35.2

### Settings

- Default Settings

### Notes

`ghacks.net##.home-category-post:has( > .home-intro-post-meta:has-text(in Deals))` does work, but I can't figure out how to not mess up the formatting of the page (the 3rd and 4th posts of every row stick together). I think the solution may involve changing some CSS parameters.

With my filter:
![image](https://user-images.githubusercontent.com/49125134/120563488-16a57e80-c3df-11eb-9e02-e44c552e0d3d.png)

**Comment by mapx-** [comment]
maybe @ryanbr
