### ISSUE TITLE
thepostmillennial.com ads left-overs

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uAssets#9349]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://thepostmillennial.com/breaking-amazon-barnes-and-noble-scrub-faucis-book-amid-backlash`

### Describe the issue
There are several ads left-overs

### Versions

- Browser/version: [Edge 91.]
- uBlock Origin version: [1.35.2]

### Notes
Adding this rule works for me: `thepostmillennial.com##.mot-container`

**Comment by IThinkIAmCool** [comment]
@uBlock-user addressed by Fanboy.
