### ISSUE TITLE
[Question] Documentation On Blocking

### ISSUE THREAD

**Issue by zero77** [uBlockOrigin/uAssets#935]
Hi @mapx- 

Is there any documentation on the ##script:inject(abort-current-inline-script.js, blocking method you are using, instead of the standard block element method.
Because, I couldn’t sea any in the uBlock wiki.

Thanks

**Comment by mapx-** [comment]
read here (when the scriptlet was born)
https://github.com/uBlockOrigin/uAssets/issues/618#issuecomment-321842729

**Comment by zero77** [comment]
thanks

**Comment by uBlock-user** [comment]
You supply atleast one param out of the two. The first is a `window` property and the second one is a needle.
