### ISSUE TITLE
livenewschat.eu anti-adb

### ISSUE THREAD

**Issue by unknownsoldierx** [uBlockOrigin/uAssets#9354]
### Prerequisites

- [x ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x ] I tried to reproduce the issue when...
    - [x ] uBlock Origin is the only extension
    - [ x] uBlock Origin with default lists/settings
    - [x ] using a new, unmodified browser profile
- [x ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://livenewschat.eu/jazzyi/`

### Describe the issue

Site detects adblocking using service provided by blockadblock.com

### Screenshot(s)

![ub](https://user-images.githubusercontent.com/2564116/120711812-6f2f5700-c485-11eb-9cbb-81c75acd3ca6.png)

### Versions

- Browser/version: Firefox 89.0
- uBlock Origin version: 1.35.2

### Settings

Default settings

### Notes

Happens even when uB is turned off or extension is disabled. Does not occur when site is opened in a private window.

Firefox privacy setting is set to standard. No other privacy extensions are installed.

**Comment by uBlock-user** [comment]
Test on default settings/default filter lists with all other extensions disabled.

**Comment by unknownsoldierx** [comment]
Turns out the extension "Windscribe - Free Proxy and Ad Blocker" is the culprit. They must have recently started calling it an ad blocker.

This may be out of the scope of what uBO does, but is there a way to prevent sites from detecting such an extension?

**Comment by uBlock-user** [comment]
Do not use multiple blockers alongside uBO.
