### ISSUE TITLE
TotalAV fake av

### ISSUE THREAD

**Issue by iam-py-test** [uBlockOrigin/uAssets#9355]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`totalav.com`

### Describe the issue
This is a known scam site; see https://github.com/VernonStow/Filterlist/issues/3#issuecomment-854248189, https://malwaretips.com/threads/total-av-is-it-a-scam.80362/, https://www.mywot.com/scorecard/totalav.com, and https://www.virustotal.com/gui/url/ea25fed9a0c7e2e4e53e312ed8679aec71177f7fbf62c4efc2318d44a6d4cb29/detection.
There is even a YouTube video saying it is a scam: https://www.youtube.com/watch?v=HIPmnzH-Pr4
 

### Screenshot(s)

N/A
### Versions

- Browser/version: Edge Version 91.0.864.41
- uBlock Origin version: uBlock Origin development build v1.35.3b7

### Settings
![image](https://user-images.githubusercontent.com/84232764/120725663-7580fb80-c4a4-11eb-810d-11dff34a93e0.png)
![image](https://user-images.githubusercontent.com/84232764/120725683-82055400-c4a4-11eb-8a4d-0f3b9dfe76de.png)
![image](https://user-images.githubusercontent.com/84232764/120725708-8e89ac80-c4a4-11eb-85b7-3c4ad65a5d8f.png)

-

### Notes
I found this domain via a link in the spamy-paied Google results with uBo disabled. The owner/developer has created fake review sites (i.e. https://www.mywot.com/scorecard/safetydetectives.com ) and fake reviews to trick people into installing this scam av.
https://www.productreview.com.au/listings/total-av has reports from only a few days ago saying it is a scam

**Comment by iam-py-test** [comment]
@DandelionSprout maybe this could also be fixed in your list? (considering it is used in other extensions)

**Comment by protected-net** [comment]
I would like to request the removal of totalav.com from your list.

The classification is misleading as TotalAV is one of a few antivirus vendors recommended by Microsoft on their website. 
https://support.microsoft.com/en-US/windows-antivirus-software-providers

Consistently performs highly in Independent Industry Testing.
https://www.av-comparatives.org/awards/total-av/
https://www.av-test.org/en/antivirus/home-windows/manufacturer/protectednet/

Over 90,000 Trustpilot Reviews with a 4.4 rating: https://www.trustpilot.com/review/totalav.com

A member of AMTSO (Anti-Malware Testing Standards Organization): https://www.amtso.org/members

We understand that there maybe an occasional unhappy customer experience online as we have over 35 million users so there will be a high chance of some negatively but as you can see from above we are in no way a threat or fake as you have classified our website.

Thank you for your time and we very much hope you can be kind enough to re-consider this classification.

**Comment by okiehsch** [comment]
Done.

**Comment by iam-py-test** [comment]
Protected Net has engaged in a long history of deceptive advertising with TotalAV, and TotalAdBlock (which is blocklisted in EasyList; just ask ryanbr).
Earlier this year. An ad on the file sharing platform AnonFiles opens this deceptive popup:
![image](https://github.com/uBlockOrigin/uAssets/assets/84232764/ea69e54f-d817-4827-9161-a1b9635bc876)
Clicking Clean leads to TotalAV: https://tria.ge/230720-3qya9sbh2t/behavioral2

July, a scam notification claiming the system is infected leads to TotalAV: https://app.any.run/tasks/cc0dd977-97e3-4b4a-833b-dfc4d5f0be55/
You can never see a clear view of the URL, so it's impossible to say if there was an affiliate code or not.

Another deceptive ad. This one asks "is your device at risk" and pretends to be an android alert:
![image](https://github.com/uBlockOrigin/uAssets/assets/84232764/8d1a38e9-7454-483d-af8d-07318f6540a0)
Where does it lead? TotalAV: https://tria.ge/230724-z8hfzsha64/behavioral1

The actual TotalAV program is deceptive: https://www.youtube.com/watch?v=PcS3EozgyhI

Protected Net cited community reviews on Trustpilot. Look at the positive reviews? They were all "invited" and all have only ever reviewed one thing. This isn't true of all the positive reviews.
What about other similar websites? Things aren't so great:
https://www.mywot.com/scorecard/totalav.com
https://www.virustotal.com/gui/url/42047d9bd1c0a9ffda3b38dc9e7e95d809a5b7f4b345dce42088d0ada486f6fb/community
Community reviews aren't that reliable though.

Lightly covers one of their *three* lookalike antiviruses: https://www.youtube.com/watch?v=bIpYJoE7CxA

More sources: https://github.com/notracking/hosts-blocklists/issues/756#issuecomment-1172973042 https://github.com/hagezi/dns-blocklists/issues/1154
I don't have time today to find more sources, but will look later this week.

**Comment by okiehsch** [comment]
The reason I removed the filter is that the software isrecommended by Microsoft atm,  now maybe they have been scammed too.
I can't say but the badlist is for cut and dried cases only imo.

**Comment by DandelionSprout** [comment]
>The classification is misleading as TotalAV is one of a few antivirus vendors recommended by Microsoft on their website.
>https://support.microsoft.com/en-US/windows-antivirus-software-providers

The same Microsoft page also recommends McAfee, an AV I wouldn't have recommended to my worst enemies. So I don't think that page is a valid metric.

**Comment by okiehsch** [comment]
So you think we should block McAfee because you wouldn't recommend it to your worst enemies?

**Comment by iam-py-test** [comment]
IMO McAfee isn't TotalAV. TotalAV is a PUP/scam, McAfee is legitimate just annoying and bad.
Norton is also listed on that page, and is a massive privacy offender, and and like McAfee is bundled with OEM Windows installs. It's not malware (though their cryptominer does bring them close). Neither should IMO be blocked as malware.

**Comment by DandelionSprout** [comment]
I've had big gripes with McAfee, mostly from tech shops whose half of their display PCs show "Your McAfee protection has expired". But that's a topic for another time and place.

**Comment by okiehsch** [comment]
I wouldn't use McAfee or Norton either but that does not mean the microsoft recomendation isn't a "valid metric".
