### ISSUE TITLE
Sflasers.us detects uBO

### ISSUE THREAD

**Issue by wecex47579** [uBlockOrigin/uAssets#9356]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://sflasers.us/`

### Describe the issue

Site detects adblock:

Ad block detected
Please disable your ad blocker and reload the page.

### Screenshot(s)

![1](https://user-images.githubusercontent.com/85324668/120735582-dd414180-c4b8-11eb-9748-cf3ee985435c.png)

### Versions

- Browser/version: Firefox 89
- uBlock Origin version: 1.35.2

### Settings

Default settings

### Notes

Tried new browser profile, added uBlock Origin -> same result

**Comment by uBlock-user** [comment]
parked domain.
