### ISSUE TITLE
[Anti-Adblock] udemydownload.com

### ISSUE THREAD

**Issue by Cyberavater** [uBlockOrigin/uAssets#9357]
Eg link: `udemydownload.com`

**Comment by Cyberavater** [comment]
Can you re-check if it's actually fixed? Doesn't seem to work for me.

**Comment by uBlock-user** [comment]
No issues here

**Comment by Cyberavater** [comment]
I've just installed UBO in clean FF installation to check, it's not working there too.

**Comment by mapx-** [comment]
"purge all caches", then "update now"

**Comment by Cyberavater** [comment]
Yes, this fixes it on clean FF, but wasn't working on chrome because of a userscript on my Chome. I'm linking the userscript in case anyone else anyone needs to know which needs to be disabled (if anyone using it), https://timer.palerock.cn/
