### ISSUE TITLE
"Deceptive site ahead"

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9364]
![Captură de ecran 2021-06-04 235421](https://user-images.githubusercontent.com/84580704/120861632-45168b80-c590-11eb-9140-555851586dfd.png)

**Comment by mapx-** [comment]
again & again you don't provide the normal test link

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/84580704/120863023-90ca3480-c592-11eb-8a0f-65d12d9e09d2.png)

**Comment by IThinkIAmCool** [comment]
`https://urlcero.co`

**Comment by uBlock-user** [comment]
Disable Safe Browsing, nothing to do with uBO.

**Comment by IThinkIAmCool** [comment]
I created the issue to let you know, in case you wanted to address it in 'uBlock filters -- Badware risks"
