### ISSUE TITLE
healthline.com

### ISSUE THREAD

**Issue by Pccode66** [uBlockOrigin/uAssets#9366]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.healthline.com/nutrition/top-13-evidence-based-health-benefits-of-coffee`

### Describe the issue

 
There are "Healthline Tool" ads. 

### Screenshot(s)

https://user-images.githubusercontent.com/49125134/120877492-29f64c80-c58d-11eb-9e6b-85c3d7554e3c.png

### Versions

- Browser/version: 89.0
- uBlock Origin version: 1.35.2

### Settings

- Default Settings

### Notes

The filter `healthline.com##.css-11k39sg` does work, but a more specific filter may be needed.
I noticed the text of the ad may change, and you might not be able to reproduce it: so here's the HTML of that portion of the webpage just in case:
```
                                        <div>
                                            <section class="css-11k39sg">
                                                <div class="css-1x6oboy"></div>
                                                <div class="css-rp3d6">
                                                    <div class="css-fwihi8">HEALTHLINE TOOL</div>
                                                    <div class="css-kp58b2">
                                                        <div class="css-1dtbtvx">Find wellness tools that work for you</div>
                                                        <p class="css-1cr3nkl">Learn the best beauty tips and healthy eating hacks from the experts themselves when you sign up for one of our wellness courses.</p>
                                                    </div>
                                                    <div class="css-8nu43k">
                                                        <div class="css-l48fio">
                                                            <a class="css-1uj038b" target="_blank" rel="noopener noreferrer" href="https://activation.healthline.com/assessment/assessment/challenge-products/prompt/goals?subid=greatistchallenge[REDACTED]_hl_middle_[REDACTED]&amp;correlationId=[REDACTED]">
                                                                <span class="css-14ktbsh"><span class="css-1huyk6v">LEARN MORE</span></span>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="css-1tuviqo"></div>
                                            </section>
                                        </div>
```

**Comment by mapx-** [comment]
use
`healthline.com##:xpath(//*[contains(text(),"HEALTHLINE TOOL")]/../..)`

self-promotion stuff

**Comment by Pccode66** [comment]
I'm sorry, I didn't notice it was self promotion.
