### ISSUE TITLE
Change ABPVN List url to uBlock specific rule support

### ISSUE THREAD

**Issue by hoang-rio** [uBlockOrigin/uAssets#9367]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### Describe the issue

This issue only create to request change url of ABPVN List to uBlock specific rule support.

### Versions

- Browser/version: all
- uBlock Origin version: lastest

### Settings

-

### Notes

ABPVN now support uBlock specific syntax with abpvn_ublock.txt file. Please change ABPVN List url to new file. Currenly only one rule is uBlock specific but it will be add more in the future.
Please see commit: https://github.com/gorhill/uBlock/commit/c16f080cc7bac11bf002f424bc15b6a6026d7611
[uBlockOrigin](https://github.com/gorhill/uBlock) repository limit contributed users to create pull request so i can not create new one so I report issue here.

**Comment by uBlock-user** [comment]
@gorhill

**Comment by gwarser** [comment]
https://github.com/abpvn/abpvn/tree/master/filter

**Comment by gwarser** [comment]
`!#include` does not work for you: https://github.com/uBlockOrigin/uBlock-issues/issues/1574#issuecomment-830658529

**Comment by gorhill** [comment]
Thanks, patch imported: <https://github.com/gorhill/uBlock/commit/c16f080cc7bac11bf002f424bc15b6a6026d7611>. It will take a few days before this change reaches everybody.
