### ISSUE TITLE
Parts of kawasaki do not load properly

### ISSUE THREAD

**Issue by Evernow** [uBlockOrigin/uAssets#9368]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
```

https://www.kawasaki.com/en-us/research-tools/dealer-locator?cm_re=GLOBALNAV-_-HEADER-_-LOCATEADEALER#dealerSearchResults

https://www.kawasaki.com/en-us/owner-center/warranty/frequently-asked-questions

```
### Describe the issue

Kawasaki dealer map does not show the pins on the map when uBlock Origin is enabled (first link). One also cannot open the FAQ sections with uBlock Origin enabled (second link)

### Screenshot(s)

uBlock Origin disabled on the left, enabled on the right

![Screenshot 2021-06-05 004936](https://user-images.githubusercontent.com/44484725/120880331-ebb25a80-c597-11eb-81be-a3601dff1e9a.png)

### Versions

- Browser/version: Firefox 89.0
- uBlock Origin version: v1.35.2

### Settings

This was all done on a factory reset uBlock Origin.

**Comment by IThinkIAmCool** [comment]
I have reproduced the issue.
Adding
```
@@||googletagmanager.com/gtag/js?id=UA-131977867-1$script,domain=kawasaki.com
@@||libs.coremetrics.com/eluminate.js^$script,domain=kawasaki.com
```
fixess the issue.

**Comment by IThinkIAmCool** [comment]
@ryanbr The issue with the map is also related with EasyList.

**Comment by IThinkIAmCool** [comment]
@ryanbr The issue with the map is also related with EasyPrivacy.

**Comment by mapx-** [comment]
add
```
@@||googletagmanager.com/gtag/js$script,domain=kawasaki.com
@@||kawasaki.com/Scripts/Analytics/BaseAnalytics.js$script,1p
```
@ryanbr

**Comment by Evernow** [comment]
Note @ryanbr that the Fanboy’s Annoyance list also breaks the map.


![Screenshot from 2021-06-05 04-50-28](https://user-images.githubusercontent.com/44484725/120886078-9ac45580-c5db-11eb-9953-458349b9c14c.png)

**Comment by Evernow** [comment]
Can reproduce the same for EasyList Cookie and AdGuard Annoyances. I can enable all lists in uBlock Origin but the three mentions and the map works.
