### ISSUE TITLE
tui.click [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#938]
RL(s) where the issue occurs

http://tui.click/ZZ7Zo

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
![](https://i.imgur.com/qAGSBn0.png)
