### ISSUE TITLE
technipages.com ad-placeholders

### ISSUE THREAD

**Issue by Pccode66** [uBlockOrigin/uAssets#9399]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.technipages.com/how-to-setup-mame-for-playing-arcade-games-on-your-pc`

### Describe the issue

 
There are blank ad spaces

### Screenshot(s)

![image](https://user-images.githubusercontent.com/49125134/120929116-29a99e80-c6be-11eb-8063-382cf70720b4.png)

### Versions

- Browser/version: Firefox 89.0
- uBlock Origin version: 1.35.2

### Settings

- Default Settings

### Notes

`technipages.com##.adsbygoogle:upward(div[style*="height: 185px;"])` works for the first ad box, the second one is not clearly an ad box, but it's empty, and can be fixed with `technipages.com##.textwidget > div[style="height: 300px;"]`
The following filters removes excessive empty spaces, but these may be just annoyances:
```
technipages.com##.widget.widget_search:style(margin-bottom: 0px !important;)
technipages.com##.widget.user-profile:style(margin-bottom: 0px !important;)
technipages.com##article[class^=post]:style(margin-bottom: 0px !important;)
```

**Comment by uBlock-user** [comment]
```
technipages.com##div[style="display:block;float:center;margin: 0px 0px 10px 0px; height: 185px;"]
technipages.com##div[style="height: 300px;"]
```

@ryanbr

**Comment by Pccode66** [comment]
I only posted here because I thought :upward would be better. It looks like the style is specific enough for EasyList

**Comment by uBlock-user** [comment]
> I only posted here because I thought :upward would be the only option.

I pull style and other properties from the DOM tree before trying any procedural cosmetic filter.

**Comment by Pccode66** [comment]
Added to EasyList on https://github.com/easylist/easylist/commit/1dfc832fc2ade028eb6a336186a9b8962f6b5b8d
