### ISSUE TITLE
anigod.com

### ISSUE THREAD

**Issue by WindSekirun** [uBlockOrigin/uAssets#94]
### URL(s) where the issue occurs
https://anigod.com/
and all subpages.

### Describe the issue
Before describe issue, this site provide japanese anime streaming service **Illegally**. although this site is illegal site, i think i should upload issue to prevent make them earn money by ADs.
  
They using FuckAdblock to bypass Adblock, but they have different solution to block ad-block users.

1. display alert() message (not div-based popup) - i have screenshot.
2. execute removeChild() to remove their content.

also, i apply some filters to prevent their solution of block ad-block users, not working. 

### Screenshot(s)
![edi1t 2016-08-07 01-49-40](https://cloud.githubusercontent.com/assets/3054645/17458056/63cb8e5c-5c42-11e6-9be5-cdc9e3ceca10.png)

### Versions

- Browser/version: Firefox, Ubuntu 16.04.1LTS , 47.0 (it also not working in Firefox for Windows OS 64bit, Firefox for Android. but i don't know specific browser version)
- uBlock Origin version: v1.8.2

### Settings
add these filter. 
```
@@||anigod.com$elemhide
anigod.com#@#var adBlockDetected = false
anigod.com##script:inject(fuckadblock.js)
anigod.com##script:contains(adBlockDetected)
||anigod.com/vendor/fuckadblock/fuckadblock.js$script,redirect=fuckadblock.js-3.2.0
anigod.com##script:contains(adBlock)
/fuckadblock.$script,redirect=fuckadblock.js-3.2.0
anigod.com#%#(function(){var a={debug:{set:function(){return a}},on:function(b,c){b||setTimeout(function(){c()},1);return a}};Object.defineProperty(window,"fuckAdBlock",{get:function(){return a}})})();
gryfindor.com$elemhide
anigod.com##.container > .article
```
### Notes
I think 'shencomics.com', 'yuncomics.com' (also known as 'Marumaru (marumaru.in)' ) using fuckadblock solution also, and these site working properly in same environment. 

Also, i try 'disable javascript in site' solution using YesScript, but this site(anigod) provide direct-video playback feature, so i think this solution isn't perfect solution.

**Comment by gorhill** [comment]
Try:

    ||static.exoclick.com/*.png$image,redirect=2x2-transparent.png,domain=anigod.com|anigod.gryfindor.com

**Comment by gorhill** [comment]
Add also:

    @@||anigod.com/js/ads.js

**Comment by WindSekirun** [comment]
it works fine, but there is one problem. 

Problem link: [this link](http://anigod.gryfindor.com/ads/%ED%94%8C%EB%9D%BC%EB%84%A4%ED%83%80%EB%A6%AC%EC%95%88-%EC%9E%91%EC%9D%80-%EB%B3%84%EC%9D%98-%EA%BF%88-3%ED%99%94-23488)

Issue:
```
 <a class="ads-link" href="/ads/%ed%94%8c%eb%9d%bc%eb%84%a4%ed%83%80%eb%a6%ac%ec%95%88-%ec%9e%91%ec%9d%80-%eb%b3%84%ec%9d%98-%ea%bf%88-3%ed%99%94-23488" hidden="">플라네타리안 작은 별의 꿈 3화 바로가기</a>
```
 will not showing when turn on ublock origin. (when turn off ublock origin, it will show.)

**Comment by gorhill** [comment]
So how about all this:

    ||static.exoclick.com/*.png$image,redirect=2x2-transparent.png,domain=anigod.com|anigod.gryfindor.com
    @@||anigod.com/js/ads.js
    anigod.gryfindor.com#@#.ads-link

uBO already redirect fuckadblock by default, no need for that rule in your 1st comment.

**Comment by gorhill** [comment]
Maybe even these two?

    anigod.gryfindor.com##.realclick
    anigod.gryfindor.com##.clickmon

**Comment by WindSekirun** [comment]
I think these filters doesn't need. 
```
anigod.gryfindor.com##.realclick
anigod.gryfindor.com##.clickmon
```
It works fine, thanks for fast reply!
