### ISSUE TITLE
`corona-virus-map[.]com` malware

### ISSUE THREAD

**Issue by iam-py-test** [uBlockOrigin/uAssets#9400]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`corona-virus-map.com`

### Describe the issue
This domain is malware; it has a fake SARS-CoV2 map and tricks users into downloading malware
See https://www.reddit.com/r/CoronavirusGA/comments/fiks3v/warning_fake_coronavirus_website_infecting/, https://www.kxan.com/news/fake-online-coronavirus-map-infects-computers-with-malware/, https://www.virustotal.com/gui/url/479d7ed77f18dad04ea84ea56ec09608b72a6c65415b3b7d25fe5173f1d87b6c/detection, https://sitecheck.sucuri.net/results/corona-virus-map.com, https://safeweb.norton.com/report/show?url=corona-virus-map.com, https://www.fortiguard.com/webfilter?q=corona-virus-map.com
 

### Screenshot(s)
N/A

### Versions

- Browser/version: Edge Version 91.0.864.41
- uBlock Origin version: uBlock Origin development build v1.35.3rc1

### Settings

![](https://user-images.githubusercontent.com/84232764/120907219-c8d28580-c62d-11eb-8b10-fde1d9a27580.png)

![](https://user-images.githubusercontent.com/84232764/120907264-1e0e9700-c62e-11eb-9f13-ea809a69cca5.png)

![](https://user-images.githubusercontent.com/84232764/120907269-2666d200-c62e-11eb-8d2f-c23d4081b4d3.png)

- Advanced user mode: On

### Notes

This domain is still online

**Comment by llacb47** [comment]
The website does not seem to be serving any content at the moment

**Comment by iam-py-test** [comment]
> The website does not seem to be serving any content at the moment

How do you know?
