### ISSUE TITLE
g1.globo.com

### ISSUE THREAD

**Issue by Pccode66** [uBlockOrigin/uAssets#9404]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://g1.globo.com/`

### Describe the issue

 
When accessing `g1.globo.com`, `globoesporte.globo.com` and `gshow.globo.com`, they always unnecessarily ask the user's location.

### Screenshot(s)

![globo](https://user-images.githubusercontent.com/49125134/121078769-bda76300-c7af-11eb-8479-2e3225216aff.png)

### Versions

- Browser/version: Firefox 89.0
- uBlock Origin version: 1.35.2

### Settings

- Default Settings

### Notes

Using the browser's developer tools, I found that `navigator.geolocation.getCurrentPosition` is called from the following window property:
```
window.buildGeoTrackingLoadUp = function (e, t, n, r, o, i) {
    return new Promise(function (l, f) {
      let d;
      if (function () {
        var e = window.safari,
        t = window.navigator,
        n = t.userAgent,
        r = t.vendor,
        o = n.toLowerCase().indexOf('safari') > - 1,
        i = r.toLowerCase().indexOf('apple') > - 1;
        return e || o && i
...
```
The name shows that the intent is probably to track the user when the webpage loads up. It's also present on `globoesporte.globo.com` and `gshow.globo.com` (not all Globo websites though). The following filters work: 
```
g1.globo.com##+js(aopw, buildGeoTrackingLoadUp)
globoesporte.globo.com##+js(aopw, buildGeoTrackingLoadUp)
gshow.globo.com##+js(aopw, buildGeoTrackingLoadUp)
```

**Comment by mapx-** [comment]
test (for breakage too)

```
||globo.com/sw.js$script
||glbimg.com/cdn/libs/element-tracker/$script
||glbimg.com/*/globo-ab/$script
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by Pccode66** [comment]
The location tracking is (as of now) coming from `https://s3.glbimg.com/v1/AUTH_b002e0039b9f46a5a4a94ff667d31e2d/assets/dist/447b6774c1de621d296ba32a58e239f9.js`

**Comment by Pccode66** [comment]
I ckicked close by accident

**Comment by Pccode66** [comment]
I clicked close by accident

**Comment by iam-py-test** [comment]
The following seemed to get rid of the location request:
```
||horizon-track.globo.com/event/g1$ping,domain=g1.globo.com
||barra.globo.com/gl/ba/oidcprodutos/js/barra-globocom.min.js$script,domain=g1.globo.com
||s3.glbimg.com/v1/AUTH_c631e406debd4c4fac98a09d48dc17d1/bastian-post/prod/g1/482bc3fc-9648-47ac-a337-15cf285fc778/1afbfdd7-9a8c-44d4-8868-ba6be67998f2.js$script,domain=g1.globo.com
||g1.globo.com/sw.js$script,domain=g1.globo.com
```

**Comment by Pccode66** [comment]
> 
> 
> The following seemed to get rid of the location request:
> 
> ```
> ||horizon-track.globo.com/event/g1$ping,domain=g1.globo.com
> ||barra.globo.com/gl/ba/oidcprodutos/js/barra-globocom.min.js$script,domain=g1.globo.com
> ||s3.glbimg.com/v1/AUTH_c631e406debd4c4fac98a09d48dc17d1/bastian-post/prod/g1/482bc3fc-9648-47ac-a337-15cf285fc778/1afbfdd7-9a8c-44d4-8868-ba6be67998f2.js$script,domain=g1.globo.com
> ||g1.globo.com/sw.js$script,domain=g1.globo.com
> ```

These filters did not work for me

**Comment by iam-py-test** [comment]
> > The following seemed to get rid of the location request:
> > ```
> > ||horizon-track.globo.com/event/g1$ping,domain=g1.globo.com
> > ||barra.globo.com/gl/ba/oidcprodutos/js/barra-globocom.min.js$script,domain=g1.globo.com
> > ||s3.glbimg.com/v1/AUTH_c631e406debd4c4fac98a09d48dc17d1/bastian-post/prod/g1/482bc3fc-9648-47ac-a337-15cf285fc778/1afbfdd7-9a8c-44d4-8868-ba6be67998f2.js$script,domain=g1.globo.com
> > ||g1.globo.com/sw.js$script,domain=g1.globo.com
> > ```
> 
> These filters did not work for me

@Pccode66  figured out why; my browser autoblocked the location request after a few times.
Sorry my filters don't work

**Comment by iam-py-test** [comment]
Blocking inline scripts seems to work but it also breaks the page

**Comment by Pccode66** [comment]
Why not use these filters?: 
```
g1.globo.com##+js(aopw, buildGeoTrackingLoadUp)
globoesporte.globo.com##+js(aopw, buildGeoTrackingLoadUp)
gshow.globo.com##+js(aopw, buildGeoTrackingLoadUp)
```
You can't block the whole script (`https://s3.glbimg.com/v1/AUTH_b002e0039b9f46a5a4a94ff667d31e2d/assets/dist/447b6774c1de621d296ba32a58e239f9.js`) because it contains other stuff.

**Comment by iam-py-test** [comment]
> Why not use these filters?:
> 
> ```
> g1.globo.com##+js(aopw, buildGeoTrackingLoadUp)
> globoesporte.globo.com##+js(aopw, buildGeoTrackingLoadUp)
> gshow.globo.com##+js(aopw, buildGeoTrackingLoadUp)
> ```
> 
> You can't block the whole script (`https://s3.glbimg.com/v1/AUTH_b002e0039b9f46a5a4a94ff667d31e2d/assets/dist/447b6774c1de621d296ba32a58e239f9.js`) because it contains other stuff.

Your filters seem to work

**Comment by iam-py-test** [comment]
Tried `g1.globo.com##+js(set,navigator.geolocation.getCurrentPosition,noopFunc)` and it worked

**Comment by Pccode66** [comment]
It might cause a false positive, the website may use location legitimately sometimes.

**Comment by Pccode66** [comment]
It says "buildGeoTrackingLoadUp", or in other words, track the user when the webpage loads up.

**Comment by iam-py-test** [comment]
> It might cause a false positive, the website may use location legitimately sometimes.

Ok. Why do you think it asks for location in the first place?

**Comment by Pccode66** [comment]
I know some videos on Globo may be geolocked

**Comment by iam-py-test** [comment]
> I know some videos on Globo may be geolocked

Which filter do you think this should go in? uBlock filters? Privacy? Badware?

**Comment by uBlock-user** [comment]
or you could just `about:preferences#privacy`  >>  Permissions >> Location >> _Block new requests asking to access your location_ 

No more location requests after that.

**Comment by iam-py-test** [comment]
Probably for Annoyances because the user can just deny access

**Comment by Pccode66** [comment]
The tracking that loads with the page is totally unnecessary; You would have to block the location permission on every browser you use, and after every settings reset.

**Comment by uBlock-user** [comment]
> The tracking that loads with the page is totally unnecessary

What tracking ?

> You would have to block the location permission on every browser

Only once when you install or use the first time

**Comment by Pccode66** [comment]
> 
> 
> > The tracking that loads with the page is totally unnecessary
> 
> What tracking ?
> 
> > You would have to block the location permission on every browser
> 
> Only once when you install or use the first time

I mean location popup

**Comment by Pccode66** [comment]
Doesn't this count as Annoyances? What do you think?

**Comment by iam-py-test** [comment]
> Doesn't this count as Annoyances? What do you think?

@uBlock-user this counts as an annoyance because it pops up on page load & would be annoying if you visited the page for your first time.
If you did, you would not have blocked it before

**Comment by iam-py-test** [comment]
@mapx- what do you think

**Comment by uBlock-user** [comment]
>  would be annoying if you visited the page for your first time. If you did, you would not be able to block the permission before hand

I can't reproduce this popup in the first place as I have _Location_ permissioned blocked for good.

**Comment by Pccode66** [comment]
That happens if you block Location by default; The default option in my browser is to ask the user.

**Comment by Pccode66** [comment]
It's not an Annoyance if the permission is for something useful or necessary. `g1.globo.com`, `globoesporte.globo.com` and `gshow.globo.com` ask for the user's location after the webpage loads (assuming default browser settings), even though in this circumstance it serves no purpose other than to track the users who accepted the location prompt.

**Comment by Pccode66** [comment]
Make a new browser profile, and go to one of these websites: `g1.globo.com`, `globoesporte.globo.com`, `gshow.globo.com`. You would see a Location Prompt from the web browser.

**Comment by iam-py-test** [comment]
I think that, because the location prompt serves only one purpose – to track the user – and because it appears on page load (no interaction needed), it is an annoyance. Unless people are using Noscript or uBo in hard mode, this annoyance would appear.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by iam-py-test** [comment]
> Why not use these filters?:
> 
> ```
> g1.globo.com##+js(aopw, buildGeoTrackingLoadUp)
> globoesporte.globo.com##+js(aopw, buildGeoTrackingLoadUp)
> gshow.globo.com##+js(aopw, buildGeoTrackingLoadUp)
> ```
> 
> You can't block the whole script (`https://s3.glbimg.com/v1/AUTH_b002e0039b9f46a5a4a94ff667d31e2d/assets/dist/447b6774c1de621d296ba32a58e239f9.js`) because it contains other stuff.

Maybe replace with this:
```
g1.globo.com,globoesporte.globo.com,gshow.globo.com##+js(aopw, buildGeoTrackingLoadUp)
```

**Comment by uBlock-user** [comment]
Those who see this as an Annoyance will simply click the **_Block_** button and be done with it, simply breaking it with uBO filter will cause others who may want to share their location for location specific services will not get a chance, we have never blocked something that makes use of **_Permissions API_** of a browser.
