### ISSUE TITLE
heraldsun.com.au video won't load (or other news. corp. australia websites)

### ISSUE THREAD

**Issue by swiftybleed** [uBlockOrigin/uAssets#9406]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
    - Issue was [reported](https://www.reddit.com/r/uBlockOrigin/comments/n2fiiz/newscomau_embedded_video_wont_play/) as to news.com.au but the issue still remains as to this website.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.heraldsun.com.au/coronavirus/melbourne-finally-set-for-lockdown-reprieve-on-friday/news-story/ec7e2159ba5af1fb83974aa4bd6fee3f` (for example, putting this one in here as its one of the non-paywalled articles)

### Describe the issue

The video player is broken and is just continuously loads and doesn't play.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/80717307/121123396-821ba000-c866-11eb-9b64-b5bbed830cbb.png)

### Versions

- Browser/version: Google Chrome Version 91.0.4472.77
- uBlock Origin version: uBlock Origin v1.35.2

### Settings

Enabled uBlock - Annoyances filter but just default settings aside from that

### Notes
I noticed that a fix was implemented for this as to `news.com.au` by adding `@@||tags.news.com.au/prod/heartbeat/v2.2.0/MediaSDK.min.js^$script,1p` to uBo filters but as the other Australian media websites owned by the same company (like the one here) rely on the same video player which continues to be blocked as a third-party script, the videos won't load. Allowing that script to run on the Herald Sun website fixed the issue when I attempted.

Other websites owned by the same company that, I presume because of their general uniformity (although I haven't tested) that are also affected are:
`https://www.dailytelegraph.com.au/
https://www.couriermail.com.au/
https://www.adelaidenow.com.au/
theaustralian.com.au
https://www.themercury.com.au/
https://www.geelongadvertiser.com.au/
https://www.cairnspost.com.au/
https://www.goldcoastbulletin.com.au/
https://www.townsvillebulletin.com.au/
https://www.thechronicle.com.au/
https://www.weeklytimesnow.com.au/
https://www.ntnews.com.au/`

**Comment by okiehsch** [comment]
`||tags.news.com.au/prod/heartbeat/*/MediaSDK.min.js$script,redirect-rule=noop.js`
works for me.

**Comment by swiftybleed** [comment]
Awesome, thanks
