### ISSUE TITLE
televisionparatodos.tv [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#941]
URL(s) where the issue occurs

http://www.televisionparatodos.tv/directv-player/

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
Mining Anti-Adblock 

`http://www.televisionparatodos.tv/tycsports/`

**Comment by mapx-** [comment]
try (popups, mining)
```
onplay.tv##+js(abort-on-property-read.js, Date.prototype.toUTCString)
televisionparatodos.tv##+js(abort-on-property-read.js, smrtAdSySPop)
||nimiq.com^
```

only in chrome an overlay appears on the first player - but it can be closed

**Comment by okiehsch** [comment]
````
televisionparatodos.tv##+js(abort-on-property-write.js, smrtSP)
onplay.tv##+js(abort-on-property-read.js, AaDetector)
onplay.tv##+js(abort-on-property-read.js, Nimiq)
````
is preferable completely blocking `nimiq.com` seems a little bit harsh.

**Comment by okiehsch** [comment]
I can't reproduce any Anti-Adblock message.

**Comment by KiLL4FuNK** [comment]
watch the video for a while and it will appear

**Comment by KiLL4FuNK** [comment]
Fake Button player

`http://www.televisionparatodos.tv/fox-sports/`

**Comment by KiLL4FuNK** [comment]
Pop-up

`http://www.televisionparatodos.tv/fox-sports-repro/`
