### ISSUE TITLE
Is `ublock-origin.com` related to uBlock Origin?

### ISSUE THREAD

**Issue by iam-py-test** [uBlockOrigin/uAssets#9412]
### Prerequisites

- [ ] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`ublock-origin.com`

### Describe the issue
This website promotes uBlock Origin, so I wanted to know if it was legit
 

### Screenshot(s)
Translated version: ![image](https://user-images.githubusercontent.com/84232764/121376297-65877280-c90f-11eb-8658-721998d5d515.png)
![image](https://user-images.githubusercontent.com/84232764/121377779-a03dda80-c910-11eb-99d6-94a33a6f80aa.png)

### Versions

- Browser/version: Edge Version 91.0.864.41
- uBlock Origin version: uBlock Origin development build v1.35.3rc1

### Settings
![image](https://user-images.githubusercontent.com/84232764/121376480-91a2f380-c90f-11eb-9874-d0bd4de9f281.png)
![image](https://user-images.githubusercontent.com/84232764/121376601-a97a7780-c90f-11eb-8b54-194a52557bb3.png)
![image](https://user-images.githubusercontent.com/84232764/121376655-b13a1c00-c90f-11eb-99f7-81a7de2700d7.png)

-

### Notes
This site is in another language, so if you do not speak that language (like me), you will need a translator. 

This site (as far as I can tell) has no link to the real uBlock Origin's GitHub repo.

**Comment by llacb47** [comment]
> Questions are to be posted on reddit -- https://www.reddit.com/r/uBlockOrigin/

* https://github.com/uBlockOrigin/uAssets/issues/9343#issuecomment-852971247

**Comment by iam-py-test** [comment]
> > Questions are to be posted on reddit -- https://www.reddit.com/r/uBlockOrigin/
> 
> * [#9343 (comment)](https://github.com/uBlockOrigin/uAssets/issues/9343#issuecomment-852971247)

@llacb47 
1. I don't have a reddit account
2. This is a badware report; https://github.com/uBlockOrigin/uAssets/issues/5854

**Comment by uBlock-user** [comment]
There's no official home-page as uBO doesn't phone-home, but some fan-made sites promote the extension.
