### ISSUE TITLE
sobatkerenz.xyz

### ISSUE THREAD

**Issue by SuperMarioMakerII** [uBlockOrigin/uAssets#9415]
`https://sobatkerenz.xyz/mortal-kombat/`
anti adb video player

<details>
 <summary>SS</summary>

![Untitled](https://user-images.githubusercontent.com/60994762/121398508-a323e400-c97f-11eb-93d6-c54d0b376389.jpg)

</details>

**Comment by uBlock-user** [comment]
Test on default settings/lists + all other extensions disabled.

**Comment by SuperMarioMakerII** [comment]
ok tq
