### ISSUE TITLE
waploaded.com

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#9419]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://series.waploaded.com/series/437102/the-irregulars`

### Describe the issue

on closing  this 

![IMG_20210611_151958](https://user-images.githubusercontent.com/20338483/121669325-d4103000-cac9-11eb-80d4-86088f95fe79.jpg)

popups arise

### Versions

- Browser/version: firefox android 
- uBlock Origin version: 1.35.2

### Settings

uBO's default settings
-

**Comment by uBlock-user** [comment]
```
||cybertronads.com^
waploaded.com##.advert
waploaded.com##.ad
```

All ads. @ryanbr

**Comment by ghajini** [comment]
i still see this 
![IMG_20210611_153818](https://user-images.githubusercontent.com/20338483/121670654-4df4e900-cacb-11eb-973b-1da3fe2464cf.jpg)

after clicking particular portions of page eg
![IMG_20210611_154037](https://user-images.githubusercontent.com/20338483/121670805-7a106a00-cacb-11eb-926e-af764afeed5c.jpg)

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by ghajini** [comment]
did you cleared cookies

**Comment by uBlock-user** [comment]
Yes, twice, no popups/unders

**Comment by uBlock-user** [comment]
Mobile-specific

**Comment by ghajini** [comment]
there are popup ads
`https://dl.waploaded.ng/download/XZ_khM33DSA/John-Abraham--Full-Hindi-Movie--John-Abraham--Latest-Movie-2021--New-Bollywood-Movies-2021/`

& clicking download mp3 here `http://dlmovies.waploaded.ng/?id=XZ_khM33DSA`

**Comment by Infrastructural** [comment]
Is any filter for `meetdownload.com` needed?
