### ISSUE TITLE
dvdcover.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#942]
URL(s) where the issue occurs

https://dvdcover.com/

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by uBlock-user** [comment]
`dvdcover.com##script:inject(abort-on-property-read.js, anOptions)`
