### ISSUE TITLE
pcgamingwiki.com

### ISSUE THREAD

**Issue by Pccode66** [uBlockOrigin/uAssets#9420]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.pcgamingwiki.com/wiki/Home`

### Describe the issue

 
There are Sponsors on the Homepage. [I have already reported the GOG ad to EasyList](https://forums.lanik.us/viewtopic.php?f=62&t=46276).

### Screenshot(s)

![image](https://user-images.githubusercontent.com/49125134/121722221-8d1b3e00-cabb-11eb-8e68-a15ae604ed7a.png)

### Versions

- Browser/version: Firefox 89.0
- uBlock Origin version: 1.35.2

### Settings

- Default Settings + Adguard Annoyances + Fanboy's Annoyance + Ublock Annoyances

### Notes

I suggest `pcgamingwiki.com##div.upcoming-releases.home-card:has(> div.section-title:has-text(Sponsors))`.

I don't recommend adding just `pcgamingwiki.com##div.upcoming-releases.home-card:has-text(Sponsors)`, because if a game had the word "Sponsors", it would block the whole "Notable releases" section.

**Comment by uBlock-user** [comment]
```
pcgamingwiki.com##div.upcoming-releases.home-card:first-child
pcgamingwiki.com###gog_summer_sale_2021
```

@ryanbr

**Comment by Pccode66** [comment]
> pcgamingwiki.com##div.upcoming-releases.home-card:first-child

Are you sure the first one is always going to be Sponsors? Just curious

**Comment by uBlock-user** [comment]
@Pccode66 has there been an incident when it's not ?

**Comment by Pccode66** [comment]
> 
> 
> @Pccode66 has there been an incident when it's not ?

OK, very smart use of CSS operators.

**Comment by Pccode66** [comment]
I always try my best when suggesting filters.

**Comment by uBlock-user** [comment]
To me, it appears the centre one would be temp., and would get replaced post summer.

**Comment by DandelionSprout** [comment]
Note that the Summer Sale banner is **not** an ad, despite it being conspicuous that GOG's summer sale got a banner, when EGS' summer sale did not.

I know this because I also happen to have contributed extensively to PCGamingWiki in the past 6 months.

**Comment by Pccode66** [comment]
> 
> 
> Note that the Summer Sale banner is **not** an ad, despite it being conspicuous that GOG's summer sale got a banner, when EGS' summer sale did not.
> 
> I know this because I also happen to have contributed extensively to PCGamingWiki in the past 6 months.

Well, the link of GOG summer sale is `https://www.gog.com/?pp=708a77db476d737e54b8bf4663fc79b346d696d2`, and this `https://www.pcgamingwiki.com/wiki/MediaWiki:Captcha-addurl-whitelist` does mention that code under a section called "## ... force affiliate"

**Comment by Pccode66** [comment]
Does that just refer to game links?

**Comment by DandelionSprout** [comment]
This is the first time during my time there that they've ever had such a banner, so I'm not entirely sure.

**Comment by Pccode66** [comment]
`https://easylist.to/2011/07/11/the-definition-of-advert-and-link-exchange-policy.html` defines an advert as  

> "the promotion of third party content in return for goods or services"

The banner has Promotion, because it has 
> a marketing aspect

The banner is a "third party", because GOG doesn't own PCGamingWiki and vice-versa.
> The aim of a website is to entice people to read more of **its content**

The banner was (possibly?) added in return for goods and services. `https://www.pcgamingwiki.com/wiki/PCGamingWiki:Partnerships` says that it 

> has partnered with GOG.com who have provided a shared community account with access to all new games on request for the benefit of the GOG.com Enhancement Project.

That wouldn't include the banner, however, as seen on the front page, GOG is labeled as one of their "Sponsors", and the banner link contains the same code as the one that's labeled as "affiliate" on `https://www.pcgamingwiki.com/wiki/MediaWiki:Captcha-addurl-whitelist`. I would just say it's **possibly** an advert.
