### ISSUE TITLE
https://al.ly/

### ISSUE THREAD

**Issue by blazesprings** [uBlockOrigin/uAssets#9423]
### URL(s) where the issue occurs
`https://al.ly/O6H4Bv`

### Describe the issue
Even after solving the captcha corrctly, the website keeps throwing error "Please check the CAPTCHA box correctly"

### Screenshot(s)
![image](https://user-images.githubusercontent.com/80951522/121812902-6447a400-cc87-11eb-97f3-4fadc89913d4.png)

### Versions
- Browser/version: [Chrome 90.xx]
- uBlock Origin version: [v1.35.2]

### Settings
All defaults.

**Comment by uBlock-user** [comment]
Site is broken, same issue with uBO disabled.
