### ISSUE TITLE
Specific id "pub01" prevents list item from being shown [FRA: AdGuard Français]

### ISSUE THREAD

**Issue by malparti** [uBlockOrigin/uAssets#9429]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://bug1715977.bmoattachments.org/attachment.cgi?id=9226493`

### Describe the issue

 

Specific ids, such as `"pub01"` prevent list items from being displayed. Note that list ids such as `"pub00"` and `"pub02"` seem to work fine.

### Screenshot(s)

![screen_shot_ublock](https://user-images.githubusercontent.com/85755504/121890562-29934980-cd23-11eb-87c4-52fa8cea2b0c.png)

### Versions

- Browser/version: Firefox 78.11.0esr (64 bits)
- uBlock Origin version: v1.35.2

### Settings

I made no change to the default uBlock Origin settings.

The filter FRA: AdGuard Français was automatically added based on my region and language.

### Notes

The problem seems to comes from the filter FRA: AdGuard Français.

It started after I upgraded Firefox from 78.10 to 78.11. I do not know what version of uBlock Origin I was using before that.

**Comment by mapx-** [comment]
@Alex-302

**Comment by Alex-302** [comment]
@malparti `bug1715977.bmoattachments.org#@##pub01`
Is `#pub01` used in that bug only?

**Comment by malparti** [comment]
@Alex-302 sorry I do not understand the question.

**Comment by Alex-302** [comment]
@malparti I mean `bug1715977`. Or it is used anywhere on bmoattachments.org?


@smed79 Please take a look.

**Comment by malparti** [comment]
@Alex-302 `bmoattachments.org` is Bugzilla's domain for hosting attachments. I first reported the bug to the Firefox issue tracker because it started occurring after I upgraded from Firefox 78.10 to 78.11, so I thought the problem came from there. The link I gave is the MWE I submitted to Bugzilla.

I do not know whether `#pub01` is used anywhere on `bmoattachments.org` and have no way to know. However, when I create a local file containing the following:
```html
 <!DOCTYPE html>
<html>
<body>
    <ol>
      <li id="pub00">Test 0</li>
      <li id="pub01">Test 1</li>
      <li id="pub02">Test 2</li>
    </ol> 
</body>
</html>
```
and open it in Firefox with  uBO + FRA: AdGuard Français, then the item `pub01` is not displayed. If I deactivate FRA: AdGuard Français, then the item is displayed, which is why I think the problem comes from there.

Note that "pub" means "ad" in French. However, it can also be used for "publication" (e.g: [PubPeer](https://pubpeer.com)) so I think it is fairly problematic if items labeled `pub01` are not displayed on a website. I first noticed the issue on a including on a plain html website that does not include any ads hosted on an academic domain.

That is all I know about this issue, and I do not know anything about how uBO works, I'm just an end-user. I can do some more testing if required.

**Comment by uBlock-user** [comment]
Already fixed in uBO with https://github.com/uBlockOrigin/uAssets/commit/19af1311d846535bdc3282233ccf72d4bb0b95a0 fyi

**Comment by malparti** [comment]
@uBlock-user I saw that commit, but I do not think it fixes the bug. The behavior I observed is on *any* website -- and even on a local file -- a list-item labeled `pub01` will not be displayed. Does that commit fix that?

**Comment by malparti** [comment]
Also, why that that behavior happen with `pub01` but not `pub00` or `pub02`?

**Comment by uBlock-user** [comment]
>  The behavior I observed is on any website -- and even on a local file -- a list-item labeled pub01 will not be displayed. Does that commit fix that?

There's a generic filter `###pub01` in the French list, so it applies on all domains, you only reported `bmoattachments.org` so obviously a fix will be added for that website.

**Comment by uBlock-user** [comment]
>  The behavior I observed is on any website -- and even on a local file -- a list-item labeled pub01 will not be displayed. Does that commit fix that?

There's a generic filter `###pub01` in the French list, so it applies on all domains, you only reported `bmoattachments.org` so obviously a fix will be added for that website only.

> Also, why that that behavior happen with pub01 but not pub00 or pub02?

Ask the french list maintainer.

**Comment by malparti** [comment]
@uBlock-user I didn't mean to report the bug for `bmoattachments.org`, I merely did my best to follow the (somewhat complicated) template to open issue that required me to provide a URL where the problem occurred. I thought the screenshot would make it reasonably clear that this was a MWE, not a website that should be added to a whitelist.

Again, I'm not familiar with how uBO works and how you deal with issues -- I'm just an end-user who has found a bug in uBO and has created a GitHub account specifically to report that bug.

> Ask the french list maintainer.

(1) I do not know who that is and how to do this (2) my goal when opening this issue what to point out to the uBO team that there is a pretty significant problem with the default installation of uBO on Firefox with French setting (I never asked for `FRA: AdGuard Français` to be installed, in fact I had never heard about uBO filters until yesterday).

Now, if that can help I can write something to explain why it is *not* a good idea to have a filter that just removes any item named `pub01` on any page, and someone from the uBO team can forward that to the relevant person. What I cannot do is find out who maintains what part of the code to send it to the right person myself.

**Comment by malparti** [comment]
Also, this issue should probably be re-opened, since 19af131 does not fix it. I cannot, not having the required rights.

**Comment by Alex-302** [comment]
Ok, fixed in our filter.

**Comment by uBlock-user** [comment]
> I do not know who that is and how to do this

Open a new issue at - https://github.com/AdguardTeam/AdguardFilters/issues, the filter is present in the french list, so best would for the AdGuard Team to address your bug/issue there.

**Comment by malparti** [comment]
@Alex-302 As discussed above, I do not think your commit fixes the issue. There is no point in whitelisting bmoattachments.org, which is only a website used to host attachments used to report bugs to Mozilla. The question is whether it is a good idea to block every item with id `pub01` on any website.

> Open a new issue at - https://github.com/AdguardTeam/AdguardFilters/issues, the filter is present in the french list, so best would for the AdGuard Team to address your bug/issue there.

@uBlock-user OK I will do that.

**Comment by krystian3w** [comment]
@smed79

**Comment by malparti** [comment]
@krystian3w I saw that but I don't understand why. If the reason for closing the thread is 6539bd8, then that makes no sense. Maybe I am missing something?

**Comment by krystian3w** [comment]
Maybe marked rule as useful with 0 real FP.
