### ISSUE TITLE
lilymanga.com - anti-adblock

### ISSUE THREAD

**Issue by SwiftWinds** [uBlockOrigin/uAssets#9438]
### URL(s) where the issue occurs

`https://lilymanga.com/ys/kimi-ni-tsumugu-bouhaku/chapter-08-5/`

### Describe the issue

First an anti-adblock popup appears; you can click anywhere to dismiss it. Then, scroll down somewhat slowly for about 5-10 seconds (as if you're reading it), and the below screen appears.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12981958/122340708-77f94180-cef7-11eb-84bc-8cbb1d17e300.png)

### Versions

* Browser/version: **Firefox Developer Edition 90.0b8**

* uBlock Origin version: **v1.35.2**

### Settings

All default settings.

**Comment by SwiftWinds** [comment]
Thanks a lot for the really quick fix :)

**Comment by reeeech** [comment]
It happwns to me too but I don't have any AdBlocker downloaded or any blocking setting set up T_T
![Screenshot_2023-01-30-01-12-22-85_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/48107936/215364616-4d0d97be-185b-40ea-ae34-b33608d72f7b.jpg)
