### ISSUE TITLE
last.fm

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#9442]
### Prerequisites

- [x] This is not a support issue or a question

    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://www.last.fm/zh/home`

### Describe the issue
Hello!
The site requires an account and password, so I have registered a temporary account for you to test.
Account number: zfsqla38916@chacuo.net
Password: 123abc@
The top one is an ad placeholder, it means "Want to avoid ads? Upgrade now", especially on mobile devices, very annoying!
The next one is a self-promotion, reminding users to upgrade
By the way, the same problem exists in the English version of this page, you can test it in the English page.
Thanks!

 

### Screenshot(s)
![image](https://user-images.githubusercontent.com/66902050/122343134-f269a600-cf77-11eb-87dc-3a9d8b4ebfe3.png)

### Versions

- Browser/version: ---
- uBlock Origin version: 1.35.2

### Settings

-

**Comment by uBlock-user** [comment]
```
last.fm##.mpu-subscription-upsell
last.fm##.subscribe-cta
```

Both are self promotion, hence won't be fixed in uBO. First one is fixed in Fanboy Annoyances. You can add the second to my Filters or report to Fanboy Annoyances list.

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by shenzhiming88** [comment]
@uBlock-user @ryanbr Thanks!
