### ISSUE TITLE
techyneed.com detects adblock

### ISSUE THREAD

**Issue by johnth3doe** [uBlockOrigin/uAssets#9444]
### Prerequisites

- [x] This is not a support question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/).
    
- [x] I performed a cursory search of the issue tracker on github to avoid opening a duplicate issue
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin 

### URL(s) where the issue occurs

`https://techyneed.com/wp/5-things-you-need-to-do-right-now-during-your-career-for-a-successful-campaign/` 
- That being said, because of a technicality, please see "Notes" section of this issue.

### Describe the issue

As the title shows, the site detects adblocking and does not allow for further navigation.

### Screenshot(s)

Please see "Reference B"

### Versions

- Browser/version: [Chrome 90]
- uBlock Origin version: [1.35.2]

### Settings

- No settings were changed, only lists were added.

### Notes

- This issue has also been mentioned in "Reference A", however, even after force updating uBO and adding the advised addresses to the filter-list; the issue still persists as shown in "Reference B".

-[Reference A](https://old.reddit.com/r/uBlockOrigin/comments/nrs529/adblock_detected_on_techyneedcom/)
-[Reference B](https://i.redd.it/wwerj4jd75371.jpg)

- Steps to reproduce the issue:
1) Go to `a2zapk.com` and select any link provided there, I used 
`https://a2zapk.com/1089090-smarttube-next-11-40-beta-no-ads-no-root-android-tv-mod-dark-a2z.html` 
when encountering the issue.
2) Click on the "go to download page" button, this causes a redirect (in my case) to 
`https://www.google.com/url?sa=t&source=web&rct=j&url=https://techyneed.com/wp/5-things-you-need-to-do-right-now-during-your-career-for-a-successful-campaign/&ved=2ahUKEwi5rp_s5ObwAhWRyzgGHRqOBTsQFjAAegQIAxAC&usg=AOvVaw0xK6cdQgbjIWrTEvuWWBsF`

This ultimately leads to the 
`https://techyneed.com/wp/5-things-you-need-to-do-right-now-during-your-career-for-a-successful-campaign/`
that this issue is based upon.
3) A "direct download" link button (that initially checks for adblock) will load and when clicking it, you will be redirected to another page that (does detect adblock) presents the message shown in "Reference B".
___
Thank you for your time and consideration.
Stay safe.

**Comment by uBlock-user** [comment]
>only lists were added.

Test on default lists/settings + all other extensions disabled. Disable any OS wide block list you have too, because the filters that were added require `googleadsyndication`  server to not be blocked.

**Comment by johnth3doe** [comment]
First of all, thank you for your swift response, @uBlock-user.

>> only lists were added

Here is the list that I had before making the changes: [uBO BackupList.txt](https://github.com/uBlockOrigin/uAssets/files/6682200/uBO.BackupList.txt)
 
> Test on default lists/settings + all other extensions disabled. Disable any OS wide block list you have too, because the filters that were added require `googleadsyndication` server to not be blocked.

I have (to the best of my knowledge) made the required changes, however am still getting the same error. Also, I apologize but I am not technically astute and do not know what an "OS wide block list" is.

Just to ensure that I am not making a mistake; these are the screenshots of the only settings that I have active:
![S1](https://user-images.githubusercontent.com/34193676/122671933-f4cb3a80-d1d9-11eb-8a44-65cd4f89033d.jpg)
![S2](https://user-images.githubusercontent.com/34193676/122671934-f694fe00-d1d9-11eb-80f4-8785b0438826.jpg)

I apologize if I have misinterpreted anything.

**Comment by uBlock-user** [comment]
Your backup list has external imported lists, so thats not default, Open settings in the dashboard and click _**Reset to default settings**_ button, that will bring you back to factory setup.

**Comment by johnth3doe** [comment]
> Your backup list has external imported lists, so thats not default, 

Just to be clear, the backup list I uploaded was to show what I had before, not what I was using while submitting the issue. The screenshots were the only options I had active at the time of testing.

>Open settings in the dashboard and click _**Reset to default settings**_ button, that will bring you back to factory setup.

I did that. It showed me a warning message, which I accepted.
![S3](https://user-images.githubusercontent.com/34193676/122675889-8fcd1000-d1ec-11eb-85ec-ef9f4d692cb2.jpg)

That being said, I still get the same error and cannot get the result that you posted in your previous comment.
 The only extensions I had were "ScriptSafe", "ViewImage" and "IDM Integration", I had already disabled all of them too. 
___
Thank you for your time and consideration.

**Comment by uBlock-user** [comment]
From here on, you need to investigate what's causing it to occur.

**Comment by uBlock-user** [comment]
Try disabling Chrome's built-in ad-filterer present in chrome://settings. From here on, you need to investigate what's causing it to occur.

**Comment by mapx-** [comment]
- after reset to default you have to update all your lists (purge all caches and then "update now")
- check your antivirus and (if ON) disable the web shields

**Comment by johnth3doe** [comment]
> Try disabling Chrome's built-in ad-filterer present in burger menu > More > Settings > Advanced > Site Settings > Ads. 

I followed that (thank you so much for the step-by-step) and found that the built-in ad-filterer was already disabled.

>From here on, you need to investigate what's causing it to occur.

I understand, and appreciate your support and patience with me.
____

> * after reset to default you have to update all your lists ("purge all caches" and then "update now")

Pardon me @mapx- , but you are amazing; first you edit my original post, then you give me the missing piece of the puzzle for the solution to my problem.
I did the extra steps and now it functions as intended. 
Thank you very much.
____
Thank you @mapx- and @uBlock-user. I reciprocate the respect that you have shown me.

Stay safe be well.

**Comment by johnth3doe** [comment]
The issue has resurfaced (again) for me. I have made no changes on my part since the last time we communicated. Kindly verify if this is an isolated incident or not.

Thank you for your time and attention.

**Comment by uBlock-user** [comment]
Still can't reproduce on either browser/s.

**Comment by uBlock-user** [comment]
Besure to disable all other extensions that you enabled again.

**Comment by johnth3doe** [comment]
Thank you once again for the swift response.

> Besure to disable all other extensions that you enabled again.

I have disabled all other extensions, still saw the error message. It was functional until 3/4 days ago, and in that time nothing else was added or edited on my part.

**Comment by uBlock-user** [comment]
Disable any DNS blocker you have, as there are some exception filters which open connection to `googlesyndication` and `steep.to`

**Comment by johnth3doe** [comment]
> Disable any DNS blocker you have, as there are some exception filters which open connection to `googlesyndication` and `steep.to`

I don't have any "DNS blocker" installed, I have mentioned all the variables that could be influencing the issue from my side. As I have said, I have also tried accessing the website with no active extensions at all (on both device types) with all the previous recommendations and information being taken into consideration, and still face the issue; I would assume this would rule out any erroneous setting/permission.
 
> Beyond this, you will need to start investigating this issue yourself, all the known ideas have already been posted here.

It seems I have no other choice, since I have also tried and retried
>all the known ideas...already posted here.

That being said, if you have any other ideas where I can begin my own investigation I would appreciate it.  I am afraid that my limited technical aptitude leaves me at a disadvantage when trying to figure out what to do intrinsically.
Nevertheless, (unless it is deemed otherwise) I would like to leave this issue open until  (hopefully) a solution is found, just in case there _IS_ a solution that can benefit an outlying case. 
___
Thank you for your time and attention.

**Comment by uBlock-user** [comment]
Do what you did at https://github.com/uBlockOrigin/uAssets/issues/9444#issuecomment-864559415

> Nevertheless, (unless it is deemed otherwise) I would like to leave this issue open until (hopefully) a solution is found, just in case there IS a solution that can benefit an outlying case.

This is not a uBO issue, only those issues are kept open where we have something to address, there is nothing to address here.

**Comment by johnth3doe** [comment]
>> Do what you did at [#9444 (comment)](https://github.com/uBlockOrigin/uAssets/issues/9444#issuecomment-864559415)

I did [mentioned here](https://github.com/uBlockOrigin/uAssets/issues/9444#issuecomment-873408512) :
>  I have even redone all of the previous instructions; reset to default settings -> update -> purge -> update.

I apologize if I had not made that explicitly clear before.

> This is not a uBO issue, only those issues are kept open where we have something to address, there is nothing to address here.

I see, well, that settles that point then,

I thank you for your continued support until this point and hope that it continues in the future.
With that statement I shall close this issue myself; that being said, I would still like it if you or anyone reading this would be able to point me in the right direction or advise me on what other possibilities that have not yet been considered.
___
Until next time,
Thank you for your time and attention.
Stay safe, be well.

**Comment by CyberMan571** [comment]
If you use android chrome, You may have  able to  infected malware to your phone! You can do this; Backup and clear all data to chrome! 
IF Grammarly meaning is false, sorry.

**Comment by stephenhawk8054** [comment]
`a2zapk.com` has another redirected domain to detect adblock now: `rtxkeeda.com`

URL: `https://a2zapk.com/1138873-photoshop-express-photo-editor-7-8-918-premium-arm64-v8a-a2z.html`

After clicking on `Go To Download Page` the anti-adblock message appears:
![image](https://user-images.githubusercontent.com/66517106/136303133-86844a6d-a210-4a8a-a472-3e410f000b97.png)

Firefox 92.0.1/93.0, ublock 1.38.2 with default settings.

Applying the old filters with previous domains `jaanmusic.in` and `techyneed.com` helps bypass the anti-adblock:

```
rtxkeeda.com,jaanmusic.in,techyneed.com##+js(nosiif, _0x)
@@*$ghide,domain=jaanmusic.in|techyneed.com|rtxkeeda.com
@@||googlesyndication.com/pagead/$script,domain=jaanmusic.in|techyneed.com|rtxkeeda.com
@@*$image,domain=jaanmusic.in|techyneed.com|rtxkeeda.com
rtxkeeda.com,jaanmusic.in,techyneed.com##.adsbygoogle
rtxkeeda.com,jaanmusic.in,techyneed.com##div[style="background:#ededed;"]
rtxkeeda.com,jaanmusic.in,techyneed.com###galax2
@@||js.mobileapps-v-download.com/$script,domain=techyneed.com|rtxkeeda.com
```

However, that leaves an advertisement in the middle of the page:
![image](https://user-images.githubusercontent.com/66517106/136303518-9e0bfe08-83f1-4589-af90-0774e23ca923.png)

These additional filters helps block it:
```
||tmp.dropgalaxy.in/adspopup.js$script,domain=rtxkeeda.com
||tmp.dropgalaxy.in/adddds.js$script,domain=rtxkeeda.com
||tmp.dropgalaxy.in/advertisement/*$subdocument,domain=rtxkeeda.com
rtxkeeda.com###vipada
```

**Comment by stephenhawk8054** [comment]
I think there's a suspicious 3rd party tracking script with domain `housewifehaunted.com` in `techyneed.com` site now?

URL: `https://dropgalaxy.in/tmq142h4u0sk`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/142970709-9a6cceef-2a98-40cd-bb38-d3185e8a322d.png)

</details>

Firefox 94.0.1 (with Firefox Enhanced Tracking Protection turned off), ublock 1.38.6 default

Proposed filter:

`||housewifehaunted.com^`

**Comment by Yuki2718** [comment]
@stephenhawk8054 I suspect something was just broken on your end, no actual script on the path in the screenshot and the scripts fromt this domain is fully blocked by regex on my end.

**Comment by stephenhawk8054** [comment]
> @stephenhawk8054 I suspect something was just broken on your end, no actual script on the path in the screenshot and the scripts fromt this domain is fully blocked by regex on my end.

Ah yeah, I'm not sure what's wrong. I just checked again and there are other 2 scripts from that domain, but with full `.js` URLs (I forgot to include in previous screenshot), not sure why there's another "script" URL without parameters

<details>

![image](https://user-images.githubusercontent.com/66517106/143024966-851973f1-7860-4b28-8ba6-6fe8c411c937.png)

</details>

(I've just updated the filter lists, so it's in the blocked section now)
