### ISSUE TITLE
genius.com placeholders

### ISSUE THREAD

**Issue by dinuto** [uBlockOrigin/uAssets#9446]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://genius.com/The-story-so-far-placeholder-lyrics`

### Describe the issue

There are ads placeholders in the top of the site and between the lyrics lines.

### Versions

- Browser/version: [Firefox 89.0]
- uBlock Origin version: [1.35.2]

### Notes

I created filters for this:

`genius.com###application > div[class^=LeaderboardOrMarquee__]`
or
`genius.com###application > div:nth-child(1):has(:upward(1)>main)`

and

`genius.com##div[class^=InreadAd__Container]`
or
`genius.com###application > main:xpath(div[2]/div[3]/div/div[3])`
`genius.com###application > main:xpath(div[2]/div[3]/div/div[6])`

**Comment by mapx-** [comment]
to be added in easylist

```
genius.com###application > div[class^=LeaderboardOrMarquee__]
genius.com##div[class^=InreadAd__Container]
```

@ryanbr

**Comment by dinuto** [comment]
sorry for submitting it to the wrong place

**Comment by ryanbr** [comment]
Unless I'm blind, the site looks fine here.

**Comment by dinuto** [comment]
<details>
  <summary>top placeholder</summary>
  
![picture](https://user-images.githubusercontent.com/76748920/122753174-87cba980-d29a-11eb-95ed-95757eb935f9.png)
</details>

<details>
  <summary>placeholder between the lyrics</summary>
  
![picture](https://user-images.githubusercontent.com/76748920/122753656-3e2f8e80-d29b-11eb-8f99-07452ce201e3.png)
</details>

**Comment by Yuki2718** [comment]
I could reproduce on one profile but not on another. @mapx- 's filters work fine.

**Comment by dinuto** [comment]
I agree, when I use a new profile the whole UI is different.
But since the filters does help at least sometimes, I suggest they still should be added.
