### ISSUE TITLE
Sponsored offers on wsj.com

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#9447]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

``https://www.wsj.com``
### Describe the issue

 
The Wall Street Journal has sponsored offers at the bottom. Not only do these return a 502 error, they're ads. It'd be nice if a filter could be added to EasyList or a comparable list. The problem is that the filter looks like this:

``www.wsj.com##.style--padding-right--3ZOC7BEg.style--padding-left--2oKDp1LY.style--column-16--3PkqkhOO.style--column-top--3Nm75EtS.style--column--1p190TxH > .style--grid--SxS2So51``

I'm not sure if this filter will continue to work.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/122687192-2d234680-d1e3-11eb-9c9e-e53b35a3c057.png)

### Versions

- **Browser/version:** Firefox 89.0.1
- **uBlock Origin version:** 1.35.2

### Settings

- N/A

**Comment by mapx-** [comment]
`wsj.com##[class^="style--grid"] [class^="style--grid"]:has([aria-label^="Sponsored"])`

@ryanbr

**Comment by Mennaruuk** [comment]
thank you!!!
