### ISSUE TITLE
Ad reinsertion by elo.io

### ISSUE THREAD

**Issue by ACMEd** [uBlockOrigin/uAssets#9448]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

- `www.dotabuff.com`
- `www.speedrun.com`
- `www.overbuff.com`
- `www.trackdota.com`
- `www.valorbuff.com`
- `www.tracklol.com`
- ...maybe others?

### Describe the issue

 

Ad banners _sometimes_ appearing on some of these sites (difficult to reproduce). Visit `speedrun.com` or `overbuff.com` and browse around the website until an ad banner appears.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/65193398/122691213-898a6400-d1eb-11eb-93f1-018d41a10241.png)

### Versions

- Browser/version: Firefox 89
- uBlock Origin version: 1.35.2

### Settings

- All stock lists enabled (except for mobile and regional)

### Notes

Each website has its own subdomain used to load ads (and possibly tracking?). I suggest blocking all of these domains. @easylist @AdguardTeam @StevenBlack you may be interested in adding these domains to your lists.

- `nyx-nyx-nyx.dotabuff.com` - AdGuard base list already has `||nyx-nyx-nyx.dotabuff.com/a.js` (I can't find the relevant commit)
- `cloud-strife.speedrun.com`
- `junkrat-tire.overbuff.com`
- `magic-stick.trackdota.com`
- `tethered-realms.valorbuff.com`
- `elder-dragon.tracklol.com`

These are six websites owned by `elo.io`. Elo describes their ad platform as "elusive to ad blockers." It is possible other websites (not owned by Elo) could be using the same ad platform.

**Comment by uBlock-user** [comment]
> All stock lists enabled 

Do not do this. Go back to default lists/settings. Ads are blocked by filter present in uBlock unbreak list.

**Comment by uBlock-user** [comment]
I only see an ad-placeholder on `www.dotabuff.com`  no ads or placeholders on any other sites.

**Comment by mapx-** [comment]
@ryanbr

**Comment by PIZZA90** [comment]
im trying remove the ads whitout break de top game-tracker... no way for me xD
that ads appears only with the Adblocker active

`https://www.dotabuff.com`

**Comment by mapx-** [comment]
test

```
dotabuff.com##+js(no-fetch-if, ads)
dotabuff.com##.retaliate.mana-void
```

**Comment by PIZZA90** [comment]
second filter doing the work

**Comment by mapx-** [comment]
The first one neutralizes the ads, the second is hiding the PH

**Comment by PIZZA90** [comment]
the idea was not break the top-game tracker
