### ISSUE TITLE
In website native Ads

### ISSUE THREAD

**Issue by Legendofallpro** [uBlockOrigin/uAssets#9449]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [ ] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://smallseotools.com/grammar-checker/`

### Describe the issue

![image](https://user-images.githubusercontent.com/85796039/122718253-564ae200-d28a-11eb-94bf-707548c8cf74.png)
Think this website is using in web ads with link shorteners for fooling adblockers...
Can anything be done for this or not?

### Screenshot(s)

![image](https://user-images.githubusercontent.com/85796039/122718338-7084c000-d28a-11eb-9a99-2cb977355926.png)

### Versions

- Browser/version: [91.0.4472.106]
- uBlock Origin version: [1.35.2]

### Settings
Only using a custom filter from `https://bit.ly/3vT3pnr`
-

### Notes

Think they are using link shorteners as link to the ad website instead of using popular ad services to fool ad blockers
Saw them using link shorteners for putting different ads all over their website.
Can anything be done about it? If not close this issue :)

**Comment by JobcenterTycoon** [comment]
Ads are back

**Comment by JobcenterTycoon** [comment]
Ads are back

**Comment by Legendofallpro** [comment]
ummm, not for me
it works fine for me

**Comment by JobcenterTycoon** [comment]
I get ads after a few seconds (Firefox) thats why i report it to the contributer.

**Comment by Legendofallpro** [comment]
now ads are back for me 
![image](https://user-images.githubusercontent.com/85796039/128023673-b15f348a-3bcb-4556-848a-50a400958ac8.png)

**Comment by JobcenterTycoon** [comment]
Update filter lists and try again

**Comment by Legendofallpro** [comment]
Ok now, fixed i guess...

**Comment by JobcenterTycoon** [comment]
Ads are back

**Comment by JobcenterTycoon** [comment]
`smallseotools.com##.p10` need to be removed it breaks the list on `https://smallseotools.com/online-virus-scan/`

**Comment by Daxy7** [comment]
[more Grammarly ads (and modal when you leave the page)](https://user-images.githubusercontent.com/91396482/228943007-8f750d15-d8f2-4dfd-a46e-ace84f1140da.png)

**Comment by JobcenterTycoon** [comment]
Fixed.

**Comment by Daxy7** [comment]
Grammarly ads, now under a new cosmetic div  `##.new___s_`   but have placeholders
[Image](https://user-images.githubusercontent.com/91396482/230712889-7035f1fe-e7e9-47f2-83b8-1ea649e03c58.png)
