### ISSUE TITLE
computerbase.de ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#9450]
URL `https://www.computerbase.de/forum/forums/sicherheit.141/`
Screenshot `https://pic.infini.fr/Vz5OCm4Y/404oCqmQ.png`

Firefox 89.0.1 (64-Bit)
uBlock Origin 1.35.2

**Comment by uBlock-user** [comment]
`computerbase.de##a[href^="https://www.amazon.de/"]`

@ryanbr
