### ISSUE TITLE
"Delete My Personal Data" link not working on Pluralsight website

### ISSUE THREAD

**Issue by fabriziobagala** [uBlockOrigin/uAssets#9451]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://app.pluralsight.com/id/account#`

### Describe the issue

When you click on the "Delete My Personal Data" link, the popup window does not appear.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/62190484/122741180-fd2c7f80-d284-11eb-9dcd-9d32dec5310d.png)

### Versions

- Browser/version: Microsoft Edge 91.0.864.54 (Official build) (x86_64)
- uBlock Origin version: 1.35.2

### Settings

- Enabled "uBlock filters – Annoyances"

### Notes

Disabling uBlock Origin makes the popup window appear and everything works correctly.

**Comment by uBlock-user** [comment]
Add `@@||pluralsight.com/analytics/analytics-facade$script,1p` to my Filters and try again

**Comment by fabriziobagala** [comment]
> Add `@@||pluralsight.com/analytics/analytics-facade$script,1p` to my Filters and try again

This filter works.
