### ISSUE TITLE
zive.cz adblock warning message

### ISSUE THREAD

**Issue by tommy8372** [uBlockOrigin/uAssets#9454]
### URL(s) where the issue occurs

`https://www.zive.cz/clanky/tyka-se-vas-velky-unik-dat-facebooku-uz-si-to-muzete-snadno-overit/sc-3-a-209418/default.aspx`

### Describe the issue

When you click on any article from main page, it shows warning message to disable adblock.

### Screenshot(s)

![Untitled](https://user-images.githubusercontent.com/155648/113893780-9fc97c00-97c7-11eb-982a-9374278f7b7b.png)

### Versions

- Browser/version: Firefox 89.0.1
- uBlock Origin version: 1.35.2

### Settings

Default + added uBlock, AdGuard, Fanboy filter annoyances, CZE, SVK: EasyList

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/20d21ad7e92539660c7cde4c5884b3e234854264
