### ISSUE TITLE
[Anti-Adblock] tutflix.org

### ISSUE THREAD

**Issue by Cyberavater** [uBlockOrigin/uAssets#9456]
Eg link: `https://tutflix.org/resources/android-app-development-bootcamp-2021-build-a-portfolio.3623/`

**Comment by uBlock-user** [comment]
Fill the template and provide all the details as asked.

**Comment by Cyberavater** [comment]
You need to wait sometime before the warning shows up, like 10sec or so.

![Screenshot (45)](https://user-images.githubusercontent.com/32187927/123043505-30544780-d41a-11eb-9930-1c7feeb91949.png)

**Comment by uBlock-user** [comment]
I waited a minute, still nothing.

**Comment by Cyberavater** [comment]
I've found it, you have to be logged in to be triggered by it. What relevant information can I send for you to fix it without you logging in? (or maybe you can sign up?)

**Comment by uBlock-user** [comment]
@Cyberavater Add `tutflix.org##+js(acis, $, test)` to my Filters and report.

**Comment by Cyberavater** [comment]
Yes, that fixes it! Thanks!

**Comment by anburocky3** [comment]
Thanks, for asking @Cyberavater. Was useful for me.

**Comment by Cyberavater** [comment]
Welcome, but actually @uBlock-user and the other team members here are the real heroes, who are working day and night to keep the filters updated. <3

**Comment by Cyberavater** [comment]
@uBlock-user Anti-Adblock is back here, please have a look if possible.

**Comment by Cyberavater** [comment]
![Screenshot (18)](https://user-images.githubusercontent.com/32187927/132139564-81ba7587-1ab2-4b9e-a66e-a624ce65cc03.png)

**Comment by anburocky3** [comment]
Yes the script is from: 

> https://blockadblock.com/

**Comment by anburocky3** [comment]
That was fast! Looks like the ads are not showing anymore. :) <3

**Comment by Cyberavater** [comment]
It appeared again.
![Screenshot (19)](https://user-images.githubusercontent.com/32187927/132972928-bb0abc83-0aaa-450b-b7d9-d0d099b1b68c.png)

**Comment by Cyberavater** [comment]
@anburocky3  Do you have telegram or other mediums to contact? It seems they banned me because I reported their website to ublock. It'd be nice if you could get me a resource from there.

**Comment by uBlock-user** [comment]
@Cyberavater try `tutflix.org##+js(acis, String.prototype.charCodeAt, 'replace')`

**Comment by Cyberavater** [comment]
I dunno, I'm banned there :) it's not showing ads or anything to me now!
