### ISSUE TITLE
mylink.st [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#946]
URL(s) where the issue occurs

https://mylink.st/r9OOnW1

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by gotitbro** [comment]
@okiehsch Was authedmine blocked before or has it always been unblocked?

**Comment by xDarkARG** [comment]
update the filters of these @mapx-

**Comment by KiLL4FuNK** [comment]
@mapx-  Anti-Adblock

**Comment by mapx-** [comment]
tell me if works for you
`@@||authedmine.com/lib/captcha.min.js$script,domain=mylink.li`

**Comment by okiehsch** [comment]
You have to allow the `authedmine` frame too.
`@@||authedmine.com^$subdocument,domain=mylink.li`

**Comment by mapx-** [comment]
well, this means enabling websocket / mining on site, so ...

**Comment by okiehsch** [comment]
They use `authedmine.com` as a captcha, there is no way to cirumvent that as far as I can see.

**Comment by KiLL4FuNK** [comment]
this works great @mapx- @okiehsch
`@@||authedmine.com^$domain=mylink.li`

**Comment by mapx-** [comment]
...but is enabling mining on your system, are you ok with that ?

**Comment by KiLL4FuNK** [comment]
it works well and I do not have any mining and the Captcha works great  who wait Add it

`@@||authedmine.com^$domain=mylink.li`

**Comment by KiLL4FuNK** [comment]
it works well and I do not have any mining and the Captcha works great who wait Add it

@@||authedmine.com^$domain=mylink.li

@mapx-
