### ISSUE TITLE
[Advertising placeholders] last.fm

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#9460]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://www.last.fm/home`

### Describe the issue
Hello!
Thank you for your previous quick reply.
The page has an ad placeholder that is not blocked cleanly. It is especially noticeable on the mobile page. There was originally an ad in that spot, and after blocking it there is still a bit of space left. This is shown in the picture.
The site may require an account, so I have created a temporary account for you to test
Account: zfsqla38916@chacuo.net
Password: 123abc@
Thanks!

 

### Screenshot(s)
![IMG_20210624_234917](https://user-images.githubusercontent.com/66902050/123294745-b621e100-d547-11eb-894d-c0956335247f.jpg)

![IMG_20210624_235001](https://user-images.githubusercontent.com/66902050/123295090-f8e3b900-d547-11eb-8451-f0e223749118.jpg)

**Comment by uBlock-user** [comment]
Link the chinese version of the page

**Comment by shenzhiming88** [comment]
> Link the chinese version of the page

`https://www.last.fm/zh/home`

**Comment by shenzhiming88** [comment]
Actually, it can reproduce on the any version of the page, but it may not be very obvious
![IMG_20210625_001631](https://user-images.githubusercontent.com/66902050/123298091-bd96b980-d54a-11eb-8bf2-8f4756426062.jpg)

**Comment by uBlock-user** [comment]
Still don't see it on mobile or desktop, be sure to test on default settings + all other extensions disabled.

**Comment by uBlock-user** [comment]
on mobile, ad leftover is blocked by AdGuard's Mobile Ads list.

**Comment by shenzhiming88** [comment]
Hello!
I have done what you said and updated the filter list to the latest, but the placeholder is still there
![IMG_20210625_002755](https://user-images.githubusercontent.com/66902050/123299834-7d383b00-d54c-11eb-9db5-35dd148514b3.jpg)

**Comment by uBlock-user** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/c78214b44a1bd7acc732cfa08eea2ac673b1b0f2

**Comment by shenzhiming88** [comment]
Hello
I used the account I provided and this placeholder is located between these two songs
![IMG_20210625_003304](https://user-images.githubusercontent.com/66902050/123300224-f5066580-d54c-11eb-92fd-14a8c5a23100.jpg)

**Comment by Alex-302** [comment]
> force update AdGuard Mobile Ads list

Filters builded once per hour.

**Comment by shenzhiming88** [comment]
That's fine, thank you @uBlock-user

**Comment by uBlock-user** [comment]
>  I used the account I provided and this placeholder is located between these two songs

can't reproduce.
