### ISSUE TITLE
[ad][unbreak] ad hides video element after 30s playback

### ISSUE THREAD

**Issue by alexchandel** [uBlockOrigin/uAssets#9461]
### URL(s) where the issue occurs

`https://www1.123movies.domains/tvseries/spongebob-squarepants-season-3/RujicGhe/MhsejGGD/ePOIuNm8-watch-free.html`

### Describe the issue

Some ad script hides the jwplayer (nested within `watch._playerInfo`, after `.player-frame`) after ~30s of playback, and replaces it with an ad (the `.player-frame`).

### Versions

- Browser/version: Chrome latest
- uBlock Origin version: v1.35.2

### Settings

- None

### Notes
The resource is still accessible, the ad's JS just hides the div.  Deleting the overlay & all the video's event listeners, and calling `.play()`, continues it as usual.  However, another ad script pauses it ~1s after it's played.

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disbaled.

**Comment by alexchandel** [comment]
That's how I tested, it still happened.

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

Tested in Chrome 91.0.4472.114, macOS 11.4.  I tried removing some default lists, and adding additional ones too, no luck.
