### ISSUE TITLE
[unbreak] site navigates away whenever DevTools is opened

### ISSUE THREAD

**Issue by alexchandel** [uBlockOrigin/uAssets#9462]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

- `https://123movies.page/`
- any subpage, `https://123movies.page/tv/spongebob-squarepants-37322.282348`

### Describe the issue

When you open DevTools on any page on the site (e.g. `https://123movies.page/`, `https://123movies.page/tv/spongebob-squarepants-37322.282348`), the site immediately begins repeatedly navigating to its home page, until DevTools is closed.

### Versions

- Browser/version: Chrome latest
- uBlock Origin version: v1.35.2

### Settings

- Default

### Notes

It seemed to test `window.__REACT_DEVTOOLS_GLOBAL_HOOK__`.  Setting this to `null` tricked it.

**Comment by okiehsch** [comment]
Fixed in `uBO-annoyances`

**Comment by JobcenterTycoon** [comment]
The fix doesn’t work for Firefox

**Comment by uBlock-user** [comment]
@JobcenterTycoon try `123movies.*##+js(set, console.clear, noopFunc)`
