### ISSUE TITLE
[Self Promotion] 699pic.com

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#9463]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://699pic.com`

### Describe the issue
Hello!
As shown in the picture, the content of the frame is the self-promotion of the website.
 

### Screenshot(s)
![image](https://user-images.githubusercontent.com/66902050/123442211-3bb89600-d607-11eb-8df4-f09505a6b709.png)

### Settings
![image](https://user-images.githubusercontent.com/66902050/123442253-46732b00-d607-11eb-963a-d38edc9620e9.png)

### Notes
I think these filtering rules will work
`699pic.com###landlord`
`699pic.com##.springtime-floatLink`
`699pic.com##.springtime-pop`
`699pic.com##.winpopbg`

**Comment by uBlock-user** [comment]
We don't address self promos. Better report to Fanboy/AdGuard.

**Comment by shenzhiming88** [comment]
@ryanbr

**Comment by shenzhiming88** [comment]
> We don't address self promos. Better report to Fanboy/AdGuard.

OK, anyway, thank you!

**Comment by shenzhiming88** [comment]
@uBlock-user 
Hello!
It has been solved in the latest Fanboy's Annoyance.
https://github.com/easylist/easylist/commit/2a6b5493f1082dc5823221948176c78561ce9234
