### ISSUE TITLE
Youtube subtitle not work?

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#9464]
idk this is happen since when...
but today, when i watching some video, i realize that the video doesn't have any subtitle (idk what you guys called this things)

so i tested with other video... and yeah... no annotation appear....
https://www.youtube.com/watch?v=KHNwu5ZOLyI

so i decide to test without ublock and BOOM
the subtitle appear...
is ublock accidentaly block the subtitle too?
if yes how can i fix it or you guys will do the fix?

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/123500737-6c68f180-d640-11eb-89b8-e72a941fadbd.png)

**Comment by Dhanamerdeka** [comment]
eh wait... why on me the sub can't show... wait i will uninstall the ublock and reinstall it again

**Comment by Dhanamerdeka** [comment]
wat.... now after reinstall it. the sub appear again... now i really confuse.... lol
thanks
