### ISSUE TITLE
gelomanias.blogspot.com - anti "Go-Back"

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#9469]
### URL(s) where the issue occurs

```
https://gelomanias.blogspot.com/
https://gelomanias.blogspot.com/2018/10/como-instalar-mods-en-euro-truck.html
```

### Describe the issue

Hi, i dont know if is possible fix this issue, really dont know if is browser problem or site problem.

( try to enter this site through google for example, you will not be able to return to google, with the back button of the browser or the mouse ) It will take you to the main page of the site, but no to Google.

this type of annoyances could be fixed with **uBO**?

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.35.2]

### Settings

Default + Spain Region Lists

**Comment by avotoko** [comment]
works for me.
```
gelomanias.blogspot.com##+js(acis, history.pushState, campaign_link)
```
