### ISSUE TITLE
platinmods.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#948]
URL(s) where the issue occurs

https://platinmods.com/

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
or

```
platinmods.com###exposeMask
platinmods.com##.xenOverlay
```

**Comment by zaphodbeebblebrox** [comment]
Block Ad Block. Fixed with `platinmods.com##script:inject(bab-defuser.js)`
