### ISSUE TITLE
Ad pops-up in media player at "https://ask4movie.cc"

### ISSUE THREAD

**Issue by shell-inator3000** [uBlockOrigin/uAssets#9480]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://ask4movie.cc/a-quiet-place-part-ii-2021`
Pop-up is NSFW
### Describe the issue

 I have uBlock enabled with default settings yet a pop up is showing up inside the media player after some time (about a few minutes in) that is not being blocked by ublock as it is a part of the media player itself
### Screenshot(s)

"https://imgur.com/a/skBAAvp" NSFW. "https://imgur.com/a/JMaksrB" NSFW

- Browser/version: Chrome/Version 91.0.4472.114 
- uBlock Origin version: 1.36.0
### Settings

None

### Notes

 It is tougher to block as it is a part of the media player and is not being picked up by the element picker. The issue is also harder to reproduce and inconsistent.

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled.
