### ISSUE TITLE
freemcserver.net - anti adb

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9481]

**Comment by IThinkIAmCool** [comment]
`@@||cdn.insurads.com/bootstrap/CZLGEQQY.js$domain=freemcserver.net`

**Comment by thinksheiscool** [comment]
@uBlock-user admiral anti adb

**Comment by thinksheiscool** [comment]
@uBlock-user could you take a look?

**Comment by JobcenterTycoon** [comment]
Can anyone reproduce CSP reports to `csp-reporting.cloudflare.com/cdn-cgi/script_monitor/report?` on this site?

@mapx- @Yuki2718

I got one time mass requests which got blocked and my browser crashed

**Comment by mapx-** [comment]
I get almost 45 requests but not a crashing mass ..

![image](https://user-images.githubusercontent.com/10303732/169588400-38ba6011-1920-4c85-bbfa-fcb74cd80089.png)

**Comment by ButterVsMargarine** [comment]
anti-adb

**Comment by Yuki2718** [comment]
> Can anyone reproduce CSP reports 

Does that require login?

**Comment by JobcenterTycoon** [comment]
Yes
