### ISSUE TITLE
sultanovic.net [Anti-Adblock]

### ISSUE THREAD

**Issue by Robbie8592** [uBlockOrigin/uAssets#9488]
### URL(s) where the issue occurs
`
http://sultanovic.net/forum/`

### Describe the issue

Getting a banner to disable my adblocker

### Screenshot(s)

![image](https://user-images.githubusercontent.com/29841633/123880985-c3f1b080-d911-11eb-8a21-c0859d082ad7.png)

### Versions

- Browser/version: Firefox 89.0.2
- uBlock Origin version: 1.36.0

### Settings

Default Settings
-

### Notes

Only get this banner when connected to a VPN.

**Comment by uBlock-user** [comment]
> Only get this banner when connected to a VPN.

Does that VPN come with built-in blocker of its own ?

**Comment by uBlock-user** [comment]
Issue caused by other extensions are not addressed in uAssets.
