### ISSUE TITLE
Youtube filter

### ISSUE THREAD

**Issue by Githuborian** [uBlockOrigin/uAssets#9489]
For a very very very long time i am hating YT stuff that i cannot seem to fix myself with ublock so i was wondering if you guys could help me out.
How to (without a extension, just ublock), no YT account:
- force 720p video's (they keep changing quality to lower every time)
- disable autoplay of video on channel page (introduction video only, not the other autoplays of videos)
- force the playback speed to 1,25x by default.
- disable all types of notifications of cookies and all of that.
- disable auto-next video button (forced) but allow the playlist auto-next only.
Thank you guys!

**Comment by mapx-** [comment]
YT stuff here => https://github.com/uBlockOrigin/uAssets/issues/7636
