### ISSUE TITLE
whentai.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#949]
URL(s) where the issue occurs

https://whentai.com/

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
it seems working too:
`||whentai.com/js/wh.modal.js`

**Comment by gotitbro** [comment]
@mapx- Please add an NSFW tag.
