### ISSUE TITLE
athernos.org

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9499]
athernos.org redirected me and it looks like aternos.org(a legitimate website).
Should it be added to uBlock filters or badware?

**Comment by uBlock-user** [comment]
Use reddit for asking questions.

**Comment by IThinkIAmCool** [comment]
It's letting you know about athernos.org nonetheless.

**Comment by uBlock-user** [comment]
Do it via reddit, this is not the place to "let me know".
