### ISSUE TITLE
togetter.com crashes on Firefox

### ISSUE THREAD

**Issue by hirorpt** [uBlockOrigin/uAssets#9501]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://togetter.com/li/1738227`

### Describe the issue

Error: This page slowing down Firefox.
`https://twitter.com/tg_editor/status/1410197243538202624`

### Screenshot(s)
<details><summary>Screenshot</summary>

![Screenshot](https://user-images.githubusercontent.com/82331005/123970233-e9ef8180-d9f3-11eb-8d2c-70a4b61feec3.png)
</details>

### Versions

- Browser/version: Firefox/89.0.2
- uBlock Origin version: v1.36.0

### Settings

- uBO defaults + AdGuard Japanese

### Notes
Maybe
`togetter.com#@##ad_overlay`

`

**Comment by uBlock-user** [comment]
That's not breakage, that some untested code on Firefox, `togetter.com###ad_overlay:remove()`
 works fine. Blocking a CSS selector will never cause a browser to freeze.

**Comment by hirorpt** [comment]
@uBlock-user 
This issue can still be reproduced on Chromium.
<details><summary>Screenshot</summary>

![Screenshot](https://user-images.githubusercontent.com/82331005/123997850-c9cbbc80-da0b-11eb-91a0-6a43a0bb3bdf.png)
</details>

**Comment by avotoko** [comment]
I get a dialog “Page(s) Unresponsive” too on chrome + ubo,
In my experience, this problem can be solved by unsubscribing EasyList or using the following filter.
```
@@||togetter.com^$ghide
! followings are generic cosmetic filters in AdGuard Japanese
togetter.com##.ad_rectangle
togetter.com##.ad_list_top
togetter.com##.ad_custom
```

**Comment by uBlock-user** [comment]
@hirorpt even after I added the filter in unbreak list ?

**Comment by hirorpt** [comment]
Yes. Unlike Firefox, for some reason the logger does not show any cosmetic filter on Chromium.
If you add `togetter.com#@##ad_overlay`, the crash will be fixed and all cosmetic filters will appear properly in the logger.

**Comment by uBlock-user** [comment]
> If you add togetter.com#@##ad_overlay, the crash will be fixed and all cosmetic filters will appear properly in the logger.

That will also allow the ad-placeholder to load 

`togetter.com##+js(aost, addEventListener, ad_overlay)` works ?

**Comment by hirorpt** [comment]
> That will also allow the ad-placeholder to load
There is no problem because `togetter.com###ad_overlay:remove()` is valid.

> `togetter.com##+js(aost, addEventListener, ad_overlay)` works ?

It doesn't not work.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/7e0c1f6f3ca9442079c6bac759ed3db9ab14c15f

**Comment by uBlock-user** [comment]
> because togetter.com###ad_overlay:remove() is valid.

:remove() will supersede (unless there's a race condition) so having an exception cosmetic filter along with `:remove()` won't make any difference.

**Comment by hirorpt** [comment]
I know about the uBO static filters grammar you noted, but this case is an exception. I can't read JS, so I don't know the cause.

<details><summary>Screenshot 1 (<code>togetter.com###ad_overlay:remove()</code> only)</summary>

![Screenshot 1](https://user-images.githubusercontent.com/82331005/124005136-b1f83680-da13-11eb-8bee-333d3ce77737.png)
</details>

<details><summary>Screenshot 2 (<code>togetter.com###ad_overlay:remove()</code>  and <code>togetter.com#@##ad_overlay</code>)</summary>

![Screenshot 2](https://user-images.githubusercontent.com/82331005/124005125-b02e7300-da13-11eb-93e8-442f676b1581.png)
</details>

**Comment by avotoko** [comment]
Identified the cause of this issue. The #fixed_social_footer is being positioned 1000 times per second as shown in the following inline script.
```
setTimeout(() => {
	fixed_footer = new FixedSocialFooter();
}, 1);
```
The following works.
```
togetter.com##+js(nostif, fixed_footer)
```

**Comment by hirorpt** [comment]
The code that caused the crash has been fixed. It's okay to remove the Unbreak filter.
`https://twitter.com/togetter_jp/status/1410852654968840192`

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/8f904bde899434006e879de7ac51523cced07e7b
