### ISSUE TITLE
br.noticias.yahoo.com

### ISSUE THREAD

**Issue by Pccode66** [uBlockOrigin/uAssets#9504]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://br.noticias.yahoo.com/ministerio-publico-pf-vao-investigar-esquema-da-covaxin-213345377.html`

### Describe the issue

 
Video ad on Brazilian version of Yahoo News

### Screenshot(s)

![image](https://user-images.githubusercontent.com/49125134/124047246-1dc5a980-d9ea-11eb-9bdf-3ad940f3f56f.png)

### Versions

- Browser/version: Firefox 89.0.2
- uBlock Origin version: 1.36.0

### Settings

- Default Settings

**Comment by llacb47** [comment]
blocked with `||edgecast-vod.yimg.com/$media,redirect-rule=noopmp3-0.1s,domain=yahoo.com` on my end (from uBlock filters)

**Comment by Pccode66** [comment]
Removing `,domain=yahoo.com` works for me. Does the domain `br.noticias.yahoo.com` redirect to another domain for you?

**Comment by Pccode66** [comment]
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect-rule says that 

> The above filter **will not cause a block filter to be created**, only a redirect directive will be created. Standalone redirect directives are useful when the blocking of a resource is optional but we still want the resource to be redirected should it ever be blocked by whatever mean - whether through a separate block filter, a dynamic filtering rule, etc.

**Comment by Pccode66** [comment]
Try accessing from a Brazilian IP address.

**Comment by llacb47** [comment]
> [gorhill/uBlock/wiki/Static-filter-syntax#redirect-rule](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect-rule) says that
> 
> > The above filter **will not cause a block filter to be created**, only a redirect directive will be created. Standalone redirect directives are useful when the blocking of a resource is optional but we still want the resource to be redirected should it ever be blocked by whatever mean - whether through a separate block filter, a dynamic filtering rule, etc.

The preroll video is blocked/thwarted/stopped by the redirect filter. I don't see your point.

**Comment by Pccode66** [comment]
![yahoo](https://user-images.githubusercontent.com/49125134/124050911-db07cf80-d9f1-11eb-8773-11a3cbfcc492.png)

**Comment by Pccode66** [comment]
I tested a few filters:

`||edgecast-vod.yimg.com/$media,redirect=noop-0.1s.mp3,domain=s.yimg.com` works, but may play a short blank  video instead of the ad.

`||edgecast-vod.yimg.com$media,domain=s.yimg.com` or `||edgecast-vod.yimg.com/$media,domain=s.yimg.com` completely work.

I suggest:

- The `domain` part must be removed, or changed to include `s.yimg.com`
- `redirect-rule` must be removed or changed to `redirect`.

**Comment by Pccode66** [comment]
I can't reproduce it anymore.

**Comment by Pccode66** [comment]
I am getting videos ads on `https://br.vida-estilo.yahoo.com/bem-humorado-silvio-santos-volta-a-gravar-no-sbt-161403621.html`. This is the ad video URL `https://s.yimg.com/cv/apiv2/AOS_BR2020/RCHLO_VINHO_CTA_16x9.mp4`. Its' HTTP Referer is something like `https://s.yimg.com/rx/vrm/builds/RANDOMNUMBERSHERE/xdomain-vpaid.html?id=0`. The id parameter can change, but I don't know whether the numbers part changes.

**Comment by Pccode66** [comment]
The filter ||s.yimg.com/rx/vrm/builds/*/xdomain-vpaid.html does work.
