### ISSUE TITLE
[breakage] sankei.com on v1.36.x

### ISSUE THREAD

**Issue by hirorpt** [uBlockOrigin/uAssets#9505]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://www.sankei.com/`

### Describe the issue
Can't click any links on v1.36.0. It is not reproduced on v1.35.2.
Similar issue: https://github.com/easylist/easylist/pull/8200#issuecomment-870198471

### Versions

- Browser/version: Firefox/89.0.2
- uBlock Origin version: 1.36.0

### Settings

- uBO's default settings + AdGuard Japanese

### Notes
`||googletagmanager.com/gtm.js$script,domain=sankei.com,important`
EasyList authors allowed gtm in order to fix login, but now I can't reproduce such an issue even without the exception filter.
https://github.com/easylist/easylist/commit/0b4564563da588c0f788f7df716d5eb85c4b266f

**Comment by uBlock-user** [comment]
@ryanbr
