### ISSUE TITLE
Need to estimate negative effects of updated google-analytics_analytics.js in v1.36

### ISSUE THREAD

**Issue by hirorpt** [uBlockOrigin/uAssets#9506]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### Describe the issue
I have investigated roughly on some Japanese sites, but I don't know if the same problem occurs worldwide.

#### Critical breakages
It has been reported that some sites make all links unclickable by not blocking `googletagmanager.com/gtm.js` and adopting  `||google-analytics.com/analytics.js$script,redirect-rule=google-analytics.com/analytics.js`. https://github.com/tofukko/filter/issues/40
Fortunately, the default filterlists is not this setting basically, but there are still many gtm exception filters. In fact, it caused the following issue.
- https://github.com/uBlockOrigin/uAssets/issues/9505

#### Regression of breakages
Breakages that could be fixed with only the gtm exception filter until v1.35.2 may require another filter `
@@||google-analytics.com/analytics.js$redirect` from v1.36.
- https://github.com/easylist/easylist/pull/8200
- https://github.com/easylist/easylist/pull/8193
- https://github.com/easylist/easylist/pull/8195

### Versions

- Browser/version: Firefox/89.0.2
- uBlock Origin version: 1.36.0

### Settings

- uBO's default

### Notes
Since it is somewhat off-topic to discuss this issue in https://github.com/easylist/easylist/pull/8200, I have created a new issue.

**Comment by uBlock-user** [comment]
From the reports so far, only japanese sites are affected, no need to look for any other regions.

**Comment by gorhill** [comment]
https://github.com/uBlockOrigin/uAssets/commit/46da3a22ffce0feba64ba320504b992a8e85530a

**Comment by uBlock-user** [comment]
No longer need to track the negative effects, fixed in https://github.com/gorhill/uBlock/commit/d3b1ca333c5a3685ada8d1afddb0030edfdf60b8
