### ISSUE TITLE
search ads on duckduckgo.com

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9514]
Encountered in Opera with a VPN

![image](https://user-images.githubusercontent.com/86536735/124299034-a2890280-db65-11eb-8d48-390744db0f15.png)

**Comment by uBlock-user** [comment]
> with a VPN

which VPN ?

**Comment by IThinkIAmCool** [comment]
> > with a VPN
> 
> which VPN ?

Opera's built-in. It can be enabled in its settings.

**Comment by IThinkIAmCool** [comment]
![image](https://user-images.githubusercontent.com/86536735/124300059-cd278b00-db66-11eb-96a0-21c298ed6533.png)

**Comment by uBlock-user** [comment]
Opera disables extensions on search engines, find that settings and enable uBO to work on search engines.

**Comment by IThinkIAmCool** [comment]
> Opera disables extensions on search engines, find that setting and enable uBO to work on search engines.

![image](https://user-images.githubusercontent.com/86536735/124301458-8b97df80-db68-11eb-8368-40d383586793.png)
Yup. Thanks!

**Comment by UnreachableCode** [comment]
This should be enabled by default.
