### ISSUE TITLE
freemcserver.net

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9522]
anti adb

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/9522

**Comment by IThinkIAmCool** [comment]
Could you test in Opera with its built-in VPN?

**Comment by uBlock-user** [comment]
I can reproduce, report there, do not open a new issue everything they change the code to fight us.
