### ISSUE TITLE
reddit.com outbound url blocked

### ISSUE THREAD

**Issue by umergionVaj** [uBlockOrigin/uAssets#9525]
### Prerequisites

- [x] This is not a support issue or a question

    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

 ` https://www.reddit.com/ ` (if logged in and the new reddit design is disabled in preferences)
and
` https://old.reddit.com/ `

### Describe the issue

uBlock Origin changing the reddit galleries links to the subreddit url. Disabling the 'uBlock filters – Privacy' filter solves the problem. 

Example:
-  Go to ` https://old.reddit.com/r/Windows11/ `
-  There is a reddit gallery post `https://old.reddit.com/r/Windows11/comments/oc2497/from_microsofts_blog_post_office_redesign_link_in/ `
- If hovering the link the url is ` https://old.reddit.com/r/Windows11/ `. The url should be ` https://www.reddit.com/gallery/oc2497 ` .
- After disabling the 'uBlock filters – Privacy' filter and refreshing the page the url goes to ` https://www.reddit.com/gallery/oc2497 ` .

 

### Versions

- Browser/version: Firefox 89.0.2
- uBlock Origin version: v1.36.0

### Settings

-

**Comment by uBlock-user** [comment]
Which filter in 'uBlock filters – Privacy' do you think does this ?

**Comment by umergionVaj** [comment]
> 
> 
> Which filter in 'uBlock filters – Privacy' do you think does this ?
> 
 I meant this:  `https://imgur.com/a/C6MVaey`.




> > If hovering the link the url is `https://old.reddit.com/r/Windows11/`. The url should be `https://www.reddit.com/gallery/oc2497`
> 
> This never happens whether I enable or disable Privacy list.

My mistake, sorry. After trying to figure out what is happening. It seems not uBlock Origin changing the galleries url, its reddit. uBlock Origin simply (?) prevents the reddit changing url from subreddit `https://old.reddit.com/r/Windows11/` to gallery `https://www.reddit.com/gallery/oc2497`.
So
With uBlock Origin disabled:
- Go to `https://old.reddit.com/r/Windows11/`
- Check the url of this post: `From Microsoft's blog post, office redesign. Link in comments.`
- Its `https://old.reddit.com/r/Windows11/`
- Wait after ~1ms, reddit changing the url to `https://www.reddit.com/gallery/oc2497`

With uBlock Origin enabled:
- Go to `https://old.reddit.com/r/Windows11/`
- Check the url of this post: `From Microsoft's blog post, office redesign. Link in comments.`
- Its `https://old.reddit.com/r/Windows11/`
- Reddit can't change the url to `https://www.reddit.com/gallery/oc2497`

With uBlock Origin enabled but 'uBlock filters – Privacy' disabled ( `https://imgur.com/a/C6MVaey` )
- Go to `https://old.reddit.com/r/Windows11/`
- Check the url of this post: `From Microsoft's blog post, office redesign. Link in comments.`
- Its `https://old.reddit.com/r/Windows11/`
- Wait after ~1ms, reddit changing the url to `https://www.reddit.com/gallery/oc2497`

**Comment by uBlock-user** [comment]
> uBlock Origin simply (?) prevents the reddit changing url from subreddit

Okay which filter in Privacy list does this ?

**Comment by umergionVaj** [comment]
Honestly, sadly i don't know. Disabling the whole filter solves the problem, so i thought reddit changed something and the filter preventing the url change.

**Comment by uBlock-user** [comment]
try `old.reddit.com#@#+js(ra, data-outbound-url)` on that page

**Comment by umergionVaj** [comment]
Thank you. It seems working, but only if im not loggen in reddit.

**Comment by uBlock-user** [comment]
> but only if im not logged in reddit.

You said before that you need to login ?

**Comment by umergionVaj** [comment]
You need to be logged in and disable the new design in preferences, if you want to stay on the old reddit design and don't want to use the reddit new design and the `https://old.reddit.com/` url while logged in. 
Thats why i wrote the ` https://www.reddit.com/ (if logged in and the new reddit design is disabled in preferences) ` in the URL description. 
Sorry if i wasn't more specific.
