### ISSUE TITLE
veoplanet.com / Video ADS

### ISSUE THREAD

**Issue by PIZZA90** [uBlockOrigin/uAssets#9528]
### URL(s) where the issue occurs

`https://www.veoplanet.com/embedveoplanet17new.php?id=4847`
`https://www.veoplanet.com/video/como-aplicar-spin-bits-de-x-sauce/4935`

### Describe the issue

Video AD every time. when start video.
years ago I reported here: https://forums.lanik.us/viewtopic.php?f=103&t=38812

but stop work.. maybe need a update

### Versions

- Browser/version: [Chrome]
- uBlock Origin version: [1.36.0]

**Comment by PIZZA90** [comment]
Example of the ads ( tested in 4 different videos of veoplanet)

https://user-images.githubusercontent.com/33556647/124331100-0b38a500-db8f-11eb-9640-58529b44c06d.mp4

**Comment by mapx-** [comment]
firefox:
`veoplanet.com##^source[src*="SPOT"]`

**Comment by uBlock-user** [comment]
try `veoplanet.com##a[class="is-advert"][data-index="0"]:remove()`

**Comment by mapx-** [comment]
try
`veoplanet.com##+js(ra, type, [src*="SPOT"])`

**Comment by PIZZA90** [comment]
`veoplanet.com##^source[src*="SPOT"]` tested in firefox, works well.. is the only one that work in FF

in chrome none works.

**Comment by PIZZA90** [comment]
this filter: `veoplanet.com##+js(ra, type, [src*="SPOT"])` 

works here:
`https://www.veoplanet.com/embedveoplanet17new.php?id=4847`

but not here:
`https://www.veoplanet.com/video/como-aplicar-spin-bits-de-x-sauce/4935`

what??

**Comment by mapx-** [comment]
@PIZZA90 does this filter work for you in chrome ? (it does not on my side)

`veoplanet.com##+js(ra, type, [src*="SPOT"], stay)`

**Comment by PIZZA90** [comment]
no ☹

**Comment by mapx-** [comment]
> no ☹

yeah, gorhill just added am improvement for such cases

**Comment by PIZZA90** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7202  is a similar case? i open that post but i cant reproduce the ads now in mega

**Comment by uBlock-user** [comment]
@PIZZA90 do video ads no longer appear in mega ?

**Comment by PIZZA90** [comment]
since a lot of months ago, i cant reproduce the ads at start like before. 

I don't know if it's fixed, or they removed the ad.

**Comment by mapx-** [comment]
I added the filter but it will be effective on the next release

**Comment by PIZZA90** [comment]
a something weird..

Pausing the video and a moving the scroll to the end ( 2 times ) black screen will appear, and start the ads.

`https://www.bikezona.com/videotv/`

Video example ( steps ) using only `development build 1.36.1b3`

https://user-images.githubusercontent.com/33556647/124741036-9ca37080-df1b-11eb-9b6e-c44d08bac8da.mp4

😂😂😂 well maybe is a stupid thing
