### ISSUE TITLE
badware incorrectly blocking a discord login callback

### ISSUE THREAD

**Issue by tcprescott** [uBlockOrigin/uAssets#9529]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://sahasrahbotapi.synack.live/callback/?code=r6OkdIXcoNe2bwrFKOvQfgqgKwixZ2&state=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZWRpcmVjdCI6Ii9tZS8iLCJfX3N0YXRlX3NlY3JldF8iOiJ3M0dwRFB3dDlmNFVtazBHbFpZNmFvWTc1cEpsUWwifQ.zmvL_nJh9JalbFNiRBBoksGHJMLyVrrZ7uZCTC2UKz0`

### Describe the issue

The above URL is getting blocked by the rule `/^https:\/\/[a-z]{3,}\d{0,3}\.?[a-z]{3,}\.li[fv]e\/[a-z]{8}\/\?/$document,domain=life|live` in uBlock Filters - Badware links

This is a callback URL after performing a discord login for a small site that I have.  I'm looking for some advice on this, or maybe a refactoring of this rule?  Thanks!

### Screenshot(s)

![image](https://user-images.githubusercontent.com/11680686/124333489-f988da80-db59-11eb-9865-69a5642fb419.png)

### Versions

- Browser/version: Chrome Version 91.0.4472.124 (Official Build) (64-bit)
- uBlock Origin version: v1.35.2

### Settings

No changes made.

### Notes

Cause is line 603 of badware
https://github.com/uBlockOrigin/uAssets/blob/1a83771f65e03d3ece4ed4e7b11a404d3702ac50/filters/badware.txt#L603

**Comment by uBlock-user** [comment]
@Yuki2718

**Comment by tcprescott** [comment]
I changed my application a bit so it wouldn't hit this rule, but this could happen in the future under these circumstances.

**Comment by Yuki2718** [comment]
Apparently bad guys switched to .club so removed these old rules.
