### ISSUE TITLE
txxx.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#953]
URL(s) where the issue occurs

https://www.txxx.com/videos/146498/filmati-vecchi-e-meno-vecchi-ritrovati-di-ofelia/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by ghajini** [comment]
Popup ads back
Nsfw
`https://txxx.com/videos/10612963/college-girl-loves-her-first-anal-fuck/#section__panel--info`

**Comment by dumbusernameidk** [comment]
Popups again `https://txxx.com/videos/1304969/liza-del-sierra-in-tout-a-declarer/`.
