### ISSUE TITLE
bmf

### ISSUE THREAD

**Issue by IThinkIAmCool** [uBlockOrigin/uAssets#9531]
https://github.com/bogachenko/fuckfuckadblock/commit/91c2eb52ddd93bc5d53528af4eb4895e288f0d83

**Comment by mapx-** [comment]
no description, no examples.

**Comment by IThinkIAmCool** [comment]
@mapx- ![image](https://user-images.githubusercontent.com/86536735/124348428-8bdcbd00-dbf2-11eb-9c0d-3f5ed9d9392d.png)

**Comment by mapx-** [comment]
`bluemediafiles.net` => empty page

**Comment by IThinkIAmCool** [comment]
https://github.com/Sainan/Universal-Bypass/issues/2010
