### ISSUE TITLE
dailynewsandmore.com

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#9543]
### URL(s) where the issue occurs

`http://www.dailynewsandmore.com/editorial/sabine-county-resolution-2nd-amendment-sanctuary-county/video_e5ce77e4-6354-11ea-8e6c-c3d83d1306fb.html`

### Describe the issue

Video blocked

### Notes

`@@||bloximages.newyork1.vip.townnews.com^$script,domain=www.dailynewsandmore.com`

**Comment by mapx-** [comment]
`@@||bloximages.newyork1.vip.townnews.com/dailynewsandmore.com/shared-content/art/tncms/templates/libraries/flex/components/video/resources/scripts/tnt.video.ads.vast-ima.$script,domain=dailynewsandmore.com`

@ryanbr
