### ISSUE TITLE
thepiratebay.org VPN ad

### ISSUE THREAD

**Issue by jxu** [uBlockOrigin/uAssets#9547]
### Prerequisites

- [X] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [X] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [X] I tried to reproduce the issue when...
    - [X] uBlock Origin is the only extension
    - [X] uBlock Origin with default lists/settings
    - [X] using a new, unmodified browser profile
- [X] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

Shows up on any torrent page, ex. 
`https://thepiratebay.org/description.php?id=7867922`

### Describe the issue

site has VPN ad annoyance appearing on right

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7989982/124698977-ece8e700-deb7-11eb-9de9-b4bf993fef17.png)

### Versions

- Browser/version: Chrome 91.0, also latest FF
- uBlock Origin version: 1.35.2

### Notes

    thepiratebay.org###meta-right

Element

    <a href="https://ttf.trmobc.com/aff_ad?campaign_id=6&amp;aff_id=460" style="text-decoration:none; border-bottom:none; color:none;"><img src="https://torrindex.net/images/epv/300.png"></a>

**Comment by jxu** [comment]
nvm this is handled by adguard base

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by jxu** [comment]
I put it in https://github.com/easylist/easylist/issues/8293
