### ISSUE TITLE
AGAIN Ads on naturalnews.com 

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uAssets#9555]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [ ] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs

`https://www.naturalnews.com/2021-07-06-82-percent-pregnant-women-vaccinated-covid-miscarriage.html#`
### Describe the issue
 
 Again ads on the right sidebar when opening an article
### Versions
- Browser/version: [FireFox 89.0.2]
- uBlock Origin version: [1.36.0]
### Settings

-
### Notes

Adding those rules solves the ongoing problem:
`||naturalnews.com/wp-content/themes/js/ads.js$script,domain=naturalnews.com`
`||naturalnews.com/ARF/$script,domain=naturalnews.com`

**Comment by JobcenterTycoon** [comment]
Ads are back

**Comment by mapx-** [comment]
disabling the last filter
`naturalnews.com#@#+js(abort-on-stack-trace, Math.floor, HTMLDocument)`

you'll get the ads

Maybe you are talking about other ads, `brighteon` ones ?

**Comment by JobcenterTycoon** [comment]
No the stuff on the right side

<details>
<img width="334" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/125051341-23cf2080-e0a3-11eb-8e89-7a64023bb92e.PNG">

</details>

When i disable `naturalnews.com#@#+js(abort-on-stack-trace, Math.floor, HTMLDocument)` i see no difference

**Comment by mapx-** [comment]
ok, they changed again, see now

**Comment by PIZZA90** [comment]
🤔 why not:

```
||naturalnews.com$script
@@||naturalnews.com/wp$script
```

i remember this in `activistpost`
 https://github.com/uBlockOrigin/uAssets/commit/25563f7084f7cb999c45879b5e11e10c71225661

**Comment by uBlock-user** [comment]
@PIZZA90 does that work ?

**Comment by BPower0036** [comment]
@PIZZA90 @uBlock-user Since the beginning of this issue this one worked for all the time:
`||naturalnews.com/ARF/$script,1p`
And recently I added `||naturalnews.com/wp-content/themes/js/ads.js$script,1p` which also works.

> Adding those rules solves the ongoing problem:
> `||naturalnews.com/wp-content/themes/js/ads.js$script,domain=naturalnews.com`
> `||naturalnews.com/ARF/$script,domain=naturalnews.com`
https://github.com/uBlockOrigin/uAssets/issues/9555#issue-938761725

**Comment by uBlock-user** [comment]
> /ARF/

it works because we're not filtering that, as soon as we add the filter you suggested, they will change it immediately. 

This is a battle of attrition.

**Comment by PIZZA90** [comment]
🤣🤣😂🤣😂🤣😂🤣🤣🤣😂

`https://www.naturalnews.com/`

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/c082a22517fc904d2cf78a99179833827944d0a4

**Comment by JobcenterTycoon** [comment]
Ads are back

**Comment by PIZZA90** [comment]
😱 they use uBO ... Because it seems fixed by adguard for a month.

with a filter that works for uBO too

**Comment by uBlock-user** [comment]
`naturalnews.com##+js(set, vADBlock, noopFunc)`

**Comment by JobcenterTycoon** [comment]
`naturalnews.com##+js(set, vADBlock, noopFunc)` doesn’t work
