### ISSUE TITLE
Imgur.com Anti-Adblock

### ISSUE THREAD

**Issue by shadoxxhd** [uBlockOrigin/uAssets#9557]
### Prerequisites

- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin

### URL(s) where the issue occurs
`https://imgur.com/upload
`

### Describe the issue
There is a anti-adblock script blocking the user from uploading an image.
 

### Versions

- Browser/version: Opera GX (LVL2 (core: 76.0.4017.208)) 
- uBlock Origin version: 1.36.0

### Settings

Active Filters:
- all built-in
- AdGuard Base + Easylist
- AdGuard Tracking Protection, AdGuard URL Tracking Protection, EasyPrivacy
- both Malware Domains lists
- all Annoyances lists
- Peter Lowes Ad and Tracking server list

### Notes
 The same issue occurs with only inbuilt lists active.

**Comment by uBlock-user** [comment]
Reset to default settings / lists and try again.

**Comment by shadoxxhd** [comment]
I still have the same problem after the reset.

**Comment by shadoxxhd** [comment]
Nvm, the integrated tracking blocker of opera must have turned on by itself in a recent update and was causing the issue.
