### ISSUE TITLE
Anti-adblock on megaup.net

### ISSUE THREAD

**Issue by 3bsa** [uBlockOrigin/uAssets#9562]
### URL(s) where the issue occurs

`https://megaup.net/1Dioi/Infinite.2021.720p.WEBRip.2CH.x265.HEVC-PSA.rar
`

### Describe the issue

Anti-adblock on megaup.net
 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12448559/124804260-c3d16080-df62-11eb-8f84-5b8603b2101e.png)

### Versions

- Browser/version: Chrome 91.0.4472.124 (Official Build) (64-bit)
- uBlock Origin version: 1.36.2

### Settings

- uBO with default settings

**Comment by avotoko** [comment]
works for me.
```
megaup.net#@#.mgbox:style(transform:translate(-999999px,0))
megaup.net##.mgbox
megaup.net##.metaRedirectWrapperBottomAds:style(height:100px)
```
