### ISSUE TITLE
upornia.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#957]
URL(s) where the issue occurs

https://upornia.com/videos/157553/mother-i-d-like-to-fuck-copulates-son-s-coach-cireman/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by dumbusernameidk** [comment]
popups when pressing play on video.

filter works for me:
`upornia.com##+js(aopr, vdaVars)`

**Comment by dumbusernameidk** [comment]
ads again seems they come from this script `https://upornia.com/roman/teo3.1.16.c48421c42b46285e8f79b9ad9ac64770.js`

**Comment by ghajini** [comment]
Popup ads
NSFW
`https://upornia.com/videos/721360/indian-girlfriend-miya-stone-assfucked/`

**Comment by ghajini** [comment]
`||krenovo.online^`
