### ISSUE TITLE
[Privacy] Login is broken on lingvolive.com

### ISSUE THREAD

**Issue by yurikoles** [uBlockOrigin/uAssets#9575]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.lingvolive.com/`

### Describe the issue

Login or Sign up buttons doesn't work with `uBlock filters – Privacy`

### uBlock Origin version

1.36.2

### Browser name and version

Google Chrome Beta 92.0.4515.93

### Settings

I verified that this problem is reproducible with all other filter disabled except `uBlock filters – Privacy`.

### Notes

Investigated down to exact filter.

**Comment by yurikoles** [comment]
They use social networks for login, but there is also plain email / password login, which is on the same pop-up widget, that doesn't open with aforementioned filter.

**Comment by yurikoles** [comment]
As a workaround, one may disable filtering on this site, login and enable it back without lose of session.

**Comment by uBlock-user** [comment]
Add `||app.link^$script,redirect-rule=noopjs,domain=lingvolive.com` to my Filters and try again.

**Comment by yurikoles** [comment]
That works on clean profile, thanks.
