### ISSUE TITLE
hotmovs.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#958]
URL(s) where the issue occurs

http://hotmovs.com/videos/1096493/misa-makise-uncensored-hardcore-video/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
ads @mapx-
