### ISSUE TITLE
Broken site zavedenia.com

### ISSUE THREAD

**Issue by coladict** [uBlockOrigin/uAssets#9581]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://burgas.zavedenia.com/`
`https://varna.zavedenia.com/`
`https://plovdiv.zavedenia.com/`
`https://sofia.zavedenia.com/`
`https://bansko.zavedenia.com/`

### Describe the issue

Pages crash entirely blank.

### uBlock Origin version

1.36.2

### Browser name and version

Mozilla Firefox 85.0.1 (64-bit)

### Settings

No changes. All defaults.

### Notes

Investigating the problem revealed that it's an Angular site using an "angularytics" module which is blocked. After unminifying the module itself is revealed to be just an abstraction layer above the Google Analytics object call, which is already shimmed by default.

Adding the following exceptions fixed the site to open normally and I observed no analytics event requests being sent in the network monitor in the dev tools.

    @@*.zavedenia.com/resources/js/angularytics.min.js$script,domain=*.zavedenia.com
    @@zavedenia.com/resources/js/angularytics.min.js$script,domain=zavedenia.com

I don't know if the second one is necessary, but I added it anyway.

**Comment by mapx-** [comment]
`@@||zavedenia.com/resources/js/angularytics.min.js$script,1p`
