### ISSUE TITLE
"Block all popups" Failed 16+/46 Tests, Is This Right?

### ISSUE THREAD

**Issue by IndividualFuture976497** [uBlockOrigin/uAssets#9587]
### Prerequisites

- [x] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://webbrowsertools.com/popup-blocker/`

### Describe the issue

Hi.

I wanted to test uBlock's "Block all popups" feature, specifically because malware sites are now targeting popups and doing quick code injection vulnerabilities.

I went to https://webbrowsertools.com/popup-blocker/ to do my testing.

Using Firefox I disabled their "Block pop-up windows" option to fully test uBlock's.

I found that uBlock failed to block 16+ out of 46 popups. The reason I say "plus" is because at the end of the tests there are 3 more methods to try.

"Click this button" to overwrite "window.open" / "MouseEvent.prototype.preventDefault" ect.

Can you confirm the feature is working as intended? The best thing about this site is it explains how the popups is triggered.

When you're testing, **"... iframe ..."** `Method #5 and #6` a small window will appear on the bottom right hand side. Imagine if that was a malware site, by the time you see that window their code has already injected.

And if try you without blocking "all popups" you'll see almost every method works. I don't think every method needs to work right?

Maybe uBlock should make a filter to block some of these type of popups, I'd be happy to test it and report any problems.

### uBlock Origin version

1.36.2

### Browser name and version

Firefox

### Settings

None

**Comment by uBlock-user** [comment]
Malware sites are blocked in malware list. Report malware sites itself.

**Comment by uBlock-user** [comment]
> Maybe uBlock should make a filter to block some of these type of popups,

That's simply not possible. Fixes are added on per-site basis. If you want to report an issue with no-popups switch, do it at the uBO issue tracker -- https://github.com/uBlockOrigin/uBlock-issues/issues

**Comment by gwarser** [comment]
This is test page, so if you want to test without "no-popups" switch, you should add specific static filter to My filters. Maybe `||webbrowsertools.com^$popup,pupunder`, but test may use other domains. Ad block specific test pages have descriptions which instruct you to add specific filter or they rely on some generic filters from popular lists. Demo or test pages will not be "fixed" in uBO filters.

Right now, tests with `target="_blank"` may not work because of bug in Firefox: https://github.com/uBlockOrigin/uBlock-issues/issues/1393#issuecomment-869834409 Workaround filters can be created in such cases.
