### ISSUE TITLE
vjav.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#959]
URL(s) where the issue occurs

https://www.vjav.com/videos/46877/exotic-japanese-whore-ai-uehara-in-crazy-doggy-style-small-tits-jav-clip95206/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by okiehsch** [comment]
@mapx- all of them have the same fix, it is the same "network".

**Comment by KiLL4FuNK** [comment]
ADS
