### ISSUE TITLE
rutracker.org has ads

### ISSUE THREAD

**Issue by gemoshi07** [uBlockOrigin/uAssets#9591]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

On the main page are most ads: [rutracker.org](rutracker.org) and on [threads](https://rutracker.org/forum/viewtopic.php?t=5757854) are ads between posts.

### Describe the issue

I see ads on the rutracker.org website.

### Screenshot(s)

https://imgur.com/a/kywrVJZ

### uBlock Origin version

1.36.2

### Browser name and version

Firefox 89.0.2

### Settings

-Default filter lists
-Ublock Annoyance

### Notes

I propose these filters:
rutracker.org##div.bn-idx:nth-of-type(3)
rutracker.org##.ext-links.products.bn-idx
rutracker.org##.ext-links.products.bn-bottom
rutracker.org##.products.bn-topic

**Comment by uBlock-user** [comment]
Activate RU Adlist for russian sites.
