### ISSUE TITLE
[Anti-Adblock] miniwebtool.com

### ISSUE THREAD

**Issue by Cyberavater** [uBlockOrigin/uAssets#9593]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

Eg linK: `https://miniwebtool.com/modulo-calculator/?number1=10&number2=3
`
### Describe the issue

Anti-Adblock

### uBlock Origin version

Latest

### Browser name and version

Latest

### Settings

Default

### Notes

Please allow opening issues with only the example link. I don't like filling out boring/unnecessary parts.

**Comment by uBlock-user** [comment]
> Please allow opening issues with only the example link. I don't like filling out boring/unnecessary parts.

Template was always there, you and some others removed it, now it's enforced, so everyone has to fill, no exceptions, we don't want to guess anything here.
