### ISSUE TITLE
google.com

### ISSUE THREAD

**Issue by Pccode66** [uBlockOrigin/uAssets#9597]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.google.com/search?q=DOOM+Eternal`

### Describe the issue

The commit https://github.com/uBlockOrigin/uAssets/commit/0888cb5327e18b80fb0e8c62433ae3f09918a6f1 does not completely remove the ads on the right side of this Google search.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/49125134/125864437-0a9d89df-c702-4327-ab3c-cb2f36b5a846.png)

### uBlock Origin version

1.36.2

### Browser name and version

Firefox 90.0

### Settings

- Default Settings

### Notes

The ad link looks something like `href="https://www.googleadservices.com/pagead/aclk?REDACTED&adurl="`. Notice that in this circumstance, the href parameter doesn't start with `/aclk`. The filter `www.google.*##[href^="https://www.googleadservices.com/pagead/aclk?"][href$="adurl="]:upward(3)` does work. I'm accessing the webpage from Brazil, therefore, you may need to access the webpage from a Brazilian IP address to see the same ads.

**Comment by Pccode66** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0888cb5327e18b80fb0e8c62433ae3f09918a6f1 is causing the results of the Shopping section of Google search to go blank. Example: `https://www.google.com/search?q=smartphone&tbm=shop`

**Comment by uBlock-user** [comment]
> is causing the results of the Shopping section of Google search to go blank. 

I don't see any fix for this, would have to remove the entire filter because that page is an ad itself.

**Comment by uBlock-user** [comment]
@Pccode66 https://github.com/uBlockOrigin/uAssets/commit/3776b1f7243f3766d6f45622ac029026a5fd6324

**Comment by Pccode66** [comment]
"Best Match" and some products are still hidden.
![](https://user-images.githubusercontent.com/49125134/126028542-77fc83a9-0c1a-4836-a0ca-1fe467459a6a.png)

**Comment by uBlock-user** [comment]
which filter ?

**Comment by Pccode66** [comment]
I suggest `www.google.*##[href^="/aclk"][href$="adurl="]:not(:scope > :upward([class^="sh-sr__shop-result-group"])):upward(3)` to substitute https://github.com/uBlockOrigin/uAssets/blob/d9a42cd2a3e5de6ce16bfe8a33b9cf05a9acd3ca/filters/filters.txt#L105.
