### ISSUE TITLE
userscloud toomuch popup issue

### ISSUE THREAD

**Issue by ghajini** [uBlockOrigin/uAssets#96]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs
https://userscloud.com/0481ucc2y8l3
### Describe the issue
too much popups on this site.....i can't browse this site to download
clickanywhere in page 2-4 times.even if 1 popup blocked another popup opens

### Versions

- Browser/version: google chrome Version 52.0.2743.116 m (64-bit)
- uBlock Origin version: 1.8.4
### Settings

- uBO's default settings
### Notes

too much popups even if i blocked them in advanced features...
also in this site popups redirect to malware sites like zp1.november-lax.com which is blocked by my antivirus but sometimes my antivirus couldn'tpick them all

**Comment by gorhill** [comment]
I was not able to get any popups, they were all blocked with default filter lists.

Look at the logger, select _All_ in the dropdown list, and report your findings.

**Comment by ghajini** [comment]
![screenshot 29](https://cloud.githubusercontent.com/assets/20338483/17462472/c4b54e36-5ccb-11e6-8eb7-4e75ba9adfcb.png)
![screenshot 30](https://cloud.githubusercontent.com/assets/20338483/17462474/c4bcd818-5ccb-11e6-889a-5d6315bc78d9.png)
![screenshot 31](https://cloud.githubusercontent.com/assets/20338483/17462473/c4bccae4-5ccb-11e6-8232-8fd4451a3c87.png)
![screenshot 32](https://cloud.githubusercontent.com/assets/20338483/17462476/c4c042c8-5ccb-11e6-9cd6-61b6b595eed9.png)
![screenshot 33](https://cloud.githubusercontent.com/assets/20338483/17462475/c4be3ae6-5ccb-11e6-9350-fd6841e5691c.png)

**Comment by ghajini** [comment]
fungetbag.info sending popups
newartspy.link is malware site a/t virustotal

**Comment by gorhill** [comment]
If this occurs again, use the filter expression `pop` to filter out non-popup-related rows, this way only one screenshot should suffice.

Btw, I did get a non-blocked popup after many trials.

@ryanbr: should probably be added to EasyList.

**Comment by ghajini** [comment]
whats the solution then?

**Comment by gorhill** [comment]
006138061795e7f21441463438f56ee5c0d12ede

**Comment by ghajini** [comment]
I have set No popups option for this site...
So what matter site change ,popups will be closed...
