### ISSUE TITLE
Zkillboard.com has an annoying anti-adblock.

### ISSUE THREAD

**Issue by Lucius-Q-User** [uBlockOrigin/uAssets#9602]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://zkillboard.com`

### Describe the issue

The website has anti-adblock code that shows a fullscreen popup when an adblocker is detected.

### uBlock Origin version

1.36.2

### Browser name and version

Firefox Nightly 92.0a1 (2021-07-18)

### Settings

Running default settings.

**Comment by Lucius-Q-User** [comment]
The pull request to fix it is #9603

**Comment by okiehsch** [comment]
I can't reproduce. Do you need to be logged in?

**Comment by Lucius-Q-User** [comment]
I did a view source, and it appears that the website owner has recently disabled the anti-adblock annoyances by inserting a `return` at the beginning of offending functions.

**Comment by okiehsch** [comment]
So, this can be closed?
FYI ypur pull request
`````
zkillboard.com##+js(set-constant, showAds, 0)
zkillboard.com##+js(set-constant, knowledgeCheck, noopFunc)
````
uses syntax we don't use in our lists we always use the abbreviation of the injected script.
````
zkillboard.com##+js(set, showAds, 0)
zkillboard.com##+js(set, knowledgeCheck, noopFunc)
````

**Comment by Lucius-Q-User** [comment]
I guess i will monitor how it goes and reopen it if the owner re-enables the annoyances.
