### ISSUE TITLE
appofmirror.com [anti-adblock]

### ISSUE THREAD

**Issue by What-Zit-Tooya** [uBlockOrigin/uAssets#9604]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://appofmirror.com/canva-mod-apk/`

### Describe the issue

Anti adblock with black background 

### Screenshot(s)

![1](https://user-images.githubusercontent.com/9832875/126154051-182155b1-a117-4d88-ad6f-e96de78ed54e.png)

### uBlock Origin version

1.36.2

### Browser name and version

FF 90.0

### Settings

Default
AdblockID
Fanboy & uBO annoyance

**Comment by What-Zit-Tooya** [comment]
I still have anti adblock after few seconds, weird.
Reset uBO setting to default still not solved

**Comment by mapx-** [comment]
Do you start your test with this link ?
`https://appofmirror.com/canva-mod-apk/`

or that one is the final one with anti adb msg ?

**Comment by okiehsch** [comment]
I can reproduce the screenshot at that link if I disable `uBO-filters`, so it's some issue on the OP's end.

**Comment by okiehsch** [comment]
`||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect-rule=googlesyndication_adsbygoogle.js`
in `uBO-filters` is fixing the anti adblock issue.

**Comment by What-Zit-Tooya** [comment]
My mistake.Seems `pagead2.googlesyndication.com` is being blocked by DNS or my networks administrator. probably it will solved if its unblocked

**Comment by okiehsch** [comment]
Adding
`appofmirror.com##+js(nostif, css_class.show)`
to your filter list could also work.

**Comment by What-Zit-Tooya** [comment]
> 
> 
> Adding
> `appofmirror.com##+js(nostif, css_class.show)`
> to your filter list could also work.

Thank you, works on my end.
Can you add it into `uBO filterlist`?

**Comment by okiehsch** [comment]
We only add filters for issues that can be reproduced with a default setup.
