### ISSUE TITLE
New Ads for Fandom WIki

### ISSUE THREAD

**Issue by watatomo** [uBlockOrigin/uAssets#9607]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.*.fandom.com/`

### Describe the issue

Fandom Wiki has rolled out a new ad system that bypasses even users that are logged in and has uBlock Origin installed. Examples can be seen here. This specific wiki is the [Ensemble Stars Wiki](https://ensemble-stars.fandom.com/wiki/The_English_Ensemble_Stars_Wiki) but it also applies to every wiki on their platform. Because of this, it makes element picking quite tedious.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/23179278/126235392-8644e57b-0803-4f74-b94a-279e31e52df5.png)
![image](https://user-images.githubusercontent.com/23179278/126235416-643609d0-5fcd-445c-8c2b-b632e3927cfc.png)

### uBlock Origin version

uBlock Origin v1.36.2

### Browser name and version

Google Chrome 91.0.4472.124

### Settings

- N/A

**Comment by llacb47** [comment]
```
fandom.com##.ad-slot-placeholder
||fandomsearch.cps.ampfeed.com^
```

**Comment by mapx-** [comment]
@ryanbr

**Comment by llacb47** [comment]
@mapx- @ryanbr `||ampfeed.com^$3p` is needed to block the affiliate ads when searching. 

![image](https://user-images.githubusercontent.com/16567977/126338488-86076e3a-1f4e-4c79-ad02-b9ffd83c9bd9.png)
![image](https://user-images.githubusercontent.com/16567977/126338617-9468364f-9825-448f-bdb9-15e5a929952e.png)
