### ISSUE TITLE
spankwire.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#961]
URL(s) where the issue occurs

https://www.spankwire.com/pal-s-step-daughter-old-enough-and-fucking-my-teen-Worlds-Greatest/video14715402/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
ADS
