### ISSUE TITLE
elitepvpers non functional with the last filter update

### ISSUE THREAD

**Issue by Zerebokep** [uBlockOrigin/uAssets#9610]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.elitepvpers.com/forum/` (everywhere)

### Describe the issue

The screenshot should be self explanatory, everything seems to be broken, it's currently not possible to create new threads, replies and so on. 

### Screenshot(s)

https://imgur.com/a/U4hnJB8

### uBlock Origin version

v1.36.2

### Browser name and version

Chrome 91.0.4472.77

### Settings

none (default)

**Comment by Zerebokep** [comment]
nvm, seems to be an easylist issue.

**Comment by JobcenterTycoon** [comment]
Not completely

EasyList breakage
`elitepvpers.com##a[href] > img[src][height]`
`elitepvpers.com##a[href] > img[src][width]`
`elitepvpers.com##a[href][target*="blank"] > img[src]`
`elitepvpers.com##img[height="60"]` (break logos)

uBlock Filters breakage (break attachments)
`elitepvpers.com##[target="_blank"] [src*=".png"]`

possible fix: `elitepvpers.com##a[target="_blank"][rel]:has(img:not([src^="https://www.elitepvpers.com/forum/attachments/"])):not([href*="trello.com"])`
