### ISSUE TITLE
[NSFW] xvideos has ads

### ISSUE THREAD

**Issue by gemoshi07** [uBlockOrigin/uAssets#9611]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.xvideos.com/video29502093/shaundamxxx_k._that_asian_booty`

### Describe the issue

I see some ads when I open a video on xvideos.com. Below I posted a screenshot of the ads. I tried to reinstall ublock, reset to default ublock, clear data from Firefox but ads are still there. 

### Screenshot(s)

Here are the ads: https://ibb.co/HX8Bsbd

### uBlock Origin version

1.36.2

### Browser name and version

Firefox 90

### Settings

I'm using only the default filters.

### Notes

I propose this filter that can fix the problem: `www.xvideos.com##.xv-cams-block`

**Comment by okiehsch** [comment]
That's self advertisement, they lead to `cams.xvideos.com` a subsite of `xvideos.com`.
We don't block that.

**Comment by uBlock-user** [comment]
`cams.xvideos.com` redirects to `xvideos-cams.com`, this looks like cross-site advertisement, should be blocked.

**Comment by okiehsch** [comment]
Not for me.

**Comment by uBlock-user** [comment]
happens at `https://cams.xvideos.com/?model=devious-angell`

**Comment by okiehsch** [comment]
I think it's because of your geo location if I use a VPN with your geo IP I get redirected, with my IP.
![image](https://user-images.githubusercontent.com/16838044/126655365-55d53024-982e-4145-8e04-d143033a9483.png)

**Comment by uBlock-user** [comment]
Happens with US IP too, not specific to one location.

**Comment by okiehsch** [comment]
It's the same site right down to the IP address.
````
https://www.site24x7.com/tools/public/t/results-1626964195962.html`
https://www.site24x7.com/tools/public/t/results-1626964171403.html
````

**Comment by uBlock-user** [comment]
Yeah that's why I said cross-site advertisement, we do block such cam ads for `xhamster`.

**Comment by okiehsch** [comment]
OK, if we already do it for cam ads for sub sites, ket's be consistent.

**Comment by gemoshi07** [comment]
> Happens with US IP too, not specific to one location.

With NL IP too. Sorry but I'm not sure if the filter I provided in the main post is the one that should be added. It seems, at least for me, that is not blocking the cams anymore. I guess I messed up something.

**Comment by uBlock-user** [comment]
For xhamster we did it because we were also blocking popups/unders, this one can be taken care by EL, if there is no other issue.

**Comment by okiehsch** [comment]
> this one can be taken care by EL

With what filter?

**Comment by uBlock-user** [comment]
Thought OP's filter worked, but doesn't, needs `xvideos.com##a[href^="https://cams.xvideos.com"]:upward(1)`
