### ISSUE TITLE
[annoyance] blog.csdn.net

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#9612]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://blog.csdn.net/zouheliang/article/details/80975928`

### Describe the issue

Hello!
When you slide down the page (mobile) and click on "Click to read more"(`点击阅读全文`), the page will pop up and recommend installing their software.

### Screenshot(s)

![IMG_20210722_235321](https://user-images.githubusercontent.com/66902050/126669984-d5c3cf25-8a83-472f-a0ea-de9ca831a665.jpg)

### uBlock Origin version

-

### Browser name and version

-

### Settings

-

**Comment by uBlock-user** [comment]
`blog.csdn.net##.weixin-shadowbox` works

**Comment by shenzhiming88** [comment]
@uBlock-user 
Hello!
It worked, but it broke the page, and now when you click on it, it doesn't load the rest of the content properly.
![2021-07-23_20-46-14](https://user-images.githubusercontent.com/66902050/126783556-e002dbf4-4eec-4dea-b469-4f1a5d0e3e54.gif)

@ryanbr
Hello!
I think it would be more appropriate to add this filter rule to `fanboy_annoyance_international.txt`.

**Comment by shenzhiming88** [comment]
@uBlock-user @ryanbr Hello!
Tested on mobile and got the same result that the page is broken

**Comment by shenzhiming88** [comment]
@uBlock-user Could you please fix it?

**Comment by shenzhiming88** [comment]
@uBlock-user Hello!
I think using the basic filter rules is ineffective, it would be better to automatically expand this interface so you don't need to open that annoying pop-up window

**Comment by shenzhiming88** [comment]
@uBlock-user Hello!
I think using the basic filter rules is ineffective, it would be better to automatically expand this interface so you don't need to open that annoying pop-up window
