### ISSUE TITLE
highgame.pro

### ISSUE THREAD

**Issue by VanHoevenTR** [uBlockOrigin/uAssets#9616]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://highgame.pro/get-mod-info/?pid=346`

### Describe the issue

Request boost countdown

### Screenshot(s)

![image](https://user-images.githubusercontent.com/70694330/126816082-f02f11ff-e9ec-480e-b0d9-d73907e3efe1.png)

### uBlock Origin version

1.36.2

### Browser name and version

Chrome Version 91.0.4472.77 (64-bit)

### Settings

- Default

**Comment by uBlock-user** [comment]
Server-sided, not possible.
