### ISSUE TITLE
[unbreak] blog.csdn.net

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#9617]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://blog.csdn.net/zouheliang/article/details/80975928`

### Describe the issue

Hello!
https://github.com/uBlockOrigin/uAssets/issues/9612
It worked, but it broke the page, and now when you click on it, it doesn't load the rest of the content properly.
Btw, many Chinese sites are very rogue in this way, so can I list these sites together in one Issue?
![2021-07-23_20-46-14](https://user-images.githubusercontent.com/66902050/126783556-e002dbf4-4eec-4dea-b469-4f1a5d0e3e54.gif)

### uBlock Origin version

-

### Browser name and version

-

### Settings

-

**Comment by uBlock-user** [comment]
The filter was added in Easylist cookie, report to them.

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by shenzhiming88** [comment]
@uBlock-user Hello!
By the way, do you deal with adding small tails when copying? This site does that behavior

**Comment by uBlock-user** [comment]
> with adding small tails when copying

what is "small tails" ?

**Comment by shenzhiming88** [comment]
> > with adding small tails when copying
> 
> what is "small tails" ?

It refers some additional information, such as copyright information, which is not wanted

**Comment by shenzhiming88** [comment]
For example.
When you copy the text of this page (`https://blog.csdn.net/qq_45704528/article/details/118635841`) (after a certain amount of text has been copied), a copyright notice will be added to the clipboard

(in English)
Copyright: This article is an original article by CSDN blogger "Serendipity sn" and follows the CC 4.0 BY-SA copyright agreement, please include the original source link and this statement.
Link to original article: `https://blog.csdn.net/qq_45704528/article/details/118635841`

(in Chinese)
版权声明：本文为CSDN博主「Serendipity  sn」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：`https://blog.csdn.net/qq_45704528/article/details/118635841`
