### ISSUE TITLE
extremetube.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#962]
URL(s) where the issue occurs

https://www.extremetube.com/video/angell-summers-gaping-asshole-3903761

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
ads @mapx-

**Comment by KiLL4FuNK** [comment]
ADS
