### ISSUE TITLE
[Anti-select] www.zhihu.com

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#9620]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.zhihu.com/question/273976149/answer/704821886`
`https://www.zhihu.com/question/369889419/answer/1969303985`

### Describe the issue

Hello
This page prevents selection, copying and adds copyright information
Thanks

### uBlock Origin version

No need

### Browser name and version

No need

### Settings

No need

**Comment by uBlock-user** [comment]
Removes copied  text from clipboard and replaces it with something else. Fixed for Chrome.

**Comment by shenzhiming88** [comment]
@uBlock-user Hello!
- Anti-copy
Address: `https://www.zhihu.com/question/310734451/answer/722735074`
![2021-07-24_23-10-51](https://user-images.githubusercontent.com/66902050/126872731-027baa17-bf91-46a4-b2dc-6933a212e75e.gif)
- Clipboard manipulation
Address:`https://www.zhihu.com/question/34315119/answer/59239683`
```
作者：高松
链接：https://www.zhihu.com/question/34315119/answer/59239683
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
```

**Comment by uBlock-user** [comment]
fixed on Chrome, I can't reproduce it anymore on Chrome.

**Comment by shenzhiming88** [comment]
> fixed on Chrome, I can't reproduce it anymore on Chrome.

When I added these filter rules, it did work, thank you
