### ISSUE TITLE
carousell.com.hk

### ISSUE THREAD

**Issue by otksm** [uBlockOrigin/uAssets#9621]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,redirect-rule,domain=carousell.com.hk`

### Describe the issue

Not sure why we are now allowing adsense scripts to pass through just because of ad placeholders. Anyways these work quite well on my end (at least on Firefox).

```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,redirect-rule,domain=carousell.com.hk,badfilter
au.carousell.com,ca.carousell.com,www.carousell.com.hk,id.carousell.com,www.carousell.com.my,nz.carousell.com,www.carousell.ph,www.carousell.sg,tw.carousell.com##div[id="adTopLeaderboardDesktop-container"]:upward(1)
au.carousell.com,ca.carousell.com,www.carousell.com.hk,id.carousell.com,www.carousell.com.my,nz.carousell.com,www.carousell.ph,www.carousell.sg,tw.carousell.com##div[id="adWideMPU-container"]
au.carousell.com,ca.carousell.com,www.carousell.com.hk,id.carousell.com,www.carousell.com.my,nz.carousell.com,www.carousell.ph,www.carousell.sg,tw.carousell.com##div[id="adWideMPU2-container"]
au.carousell.com,ca.carousell.com,www.carousell.com.hk,id.carousell.com,www.carousell.com.my,nz.carousell.com,www.carousell.ph,www.carousell.sg,tw.carousell.com##div[id="adBottomLeaderboardDesktop-container"]:upward(1)
```

And since the site came up these should probably be blocked as well:

```
/api-service/track/|$xmlhttprequest,1p,domain=au.carousell.com|ca.carousell.com|www.carousell.com.hk|id.carousell.com|www.carousell.com.my|nz.carousell.com|www.carousell.ph|www.carousell.sg|tw.carousell.com
/api-service/experiment/|$xmlhttprequest,1p,domain=au.carousell.com|ca.carousell.com|www.carousell.com.hk|id.carousell.com|www.carousell.com.my|nz.carousell.com|www.carousell.ph|www.carousell.sg|tw.carousell.com
! devicefingerprint
/api-service/session/|$xmlhttprequest,1p,domain=au.carousell.com|ca.carousell.com|www.carousell.com.hk|id.carousell.com|www.carousell.com.my|nz.carousell.com|www.carousell.ph|www.carousell.sg|tw.carousell.com
```

These URL tracking filters won't work unless you also block the click eventListener, and if you do then clicking on images (to zoom in) won't work. I will let you decide what to do with these.

```
! eventListener in place so these don't work
t-id$queryprune=t-id,domain=au.carousell.com|ca.carousell.com|www.carousell.com.hk|id.carousell.com|www.carousell.com.my|nz.carousell.com|www.carousell.ph|www.carousell.sg|tw.carousell.com
t-source$queryprune=t-source,domain=au.carousell.com|ca.carousell.com|www.carousell.com.hk|id.carousell.com|www.carousell.com.my|nz.carousell.com|www.carousell.ph|www.carousell.sg|tw.carousell.com
t-product_id$queryprune=t-product_id,domain=au.carousell.com|ca.carousell.com|www.carousell.com.hk|id.carousell.com|www.carousell.com.my|nz.carousell.com|www.carousell.ph|www.carousell.sg|tw.carousell.com
t-referrer_browse_type$queryprune=t-referrer_browse_type,domain=au.carousell.com|ca.carousell.com|www.carousell.com.hk|id.carousell.com|www.carousell.com.my|nz.carousell.com|www.carousell.ph|www.carousell.sg|tw.carousell.com
t-referrer_category_id$queryprune=t-referrer_category_id,domain=au.carousell.com|ca.carousell.com|www.carousell.com.hk|id.carousell.com|www.carousell.com.my|nz.carousell.com|www.carousell.ph|www.carousell.sg|tw.carousell.com
t-referrer_product_id$queryprune=t-referrer_product_id,domain=au.carousell.com|ca.carousell.com|www.carousell.com.hk|id.carousell.com|www.carousell.com.my|nz.carousell.com|www.carousell.ph|www.carousell.sg|tw.carousell.com
t-referrer_request_id$queryprune=t-referrer_request_id,domain=au.carousell.com|ca.carousell.com|www.carousell.com.hk|id.carousell.com|www.carousell.com.my|nz.carousell.com|www.carousell.ph|www.carousell.sg|tw.carousell.com
t-referrer_sort_by$queryprune=t-referrer_sort_by,domain=au.carousell.com|ca.carousell.com|www.carousell.com.hk|id.carousell.com|www.carousell.com.my|nz.carousell.com|www.carousell.ph|www.carousell.sg|tw.carousell.com
t-referrer_source$queryprune=t-referrer_source,domain=au.carousell.com|ca.carousell.com|www.carousell.com.hk|id.carousell.com|www.carousell.com.my|nz.carousell.com|www.carousell.ph|www.carousell.sg|tw.carousell.com
t-tap_index$queryprune=t-tap_index,domain=au.carousell.com|ca.carousell.com|www.carousell.com.hk|id.carousell.com|www.carousell.com.my|nz.carousell.com|www.carousell.ph|www.carousell.sg|tw.carousell.com
! breaks image viewimg
! au.carousell.com,ca.carousell.com,www.carousell.com.hk,id.carousell.com,www.carousell.com.my,nz.carousell.com,www.carousell.ph,www.carousell.sg,tw.carousell.com##+js(aeld, click, [native code])
```

### uBlock Origin version

1.36.2

### Browser name and version

Firefox 90.0.2

### Settings

Default Settings

**Comment by uBlock-user** [comment]
Don't see any ad placeholders

**Comment by Yuki2718** [comment]
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,redirect-rule,domain=carousell.com.hk` doesn't allow anything. It disables resource-redirect to neutered script so that the request will simply be blocked.
I see ad placeholders on *.carousell.com as currently no redirect rules for them.

**Comment by Yuki2718** [comment]
I don't see `/api-service/session/`. `/api-service/track/` and `/api-service/experiment/` can probably be blocked @ryanbr
But I tend expect those who report tracker to confirm blocking them doesn't affect operation of the sites including purchase, particularly on shopping sites.

**Comment by otksm** [comment]
> 
> Nothing is passing through, redirection is disabled for that url only


> 
> `@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,redirect-rule,domain=carousell.com.hk` doesn't allow anything. It disables resource-redirect to neutered script so that the request will simply be blocked.

Oops, my bad.

>
> But I tend to expect those who report tracker to confirm blocking them doesn't affect operation of the sites including purchase, particularly on shopping sites.

Unfortunately I don't really use the site so I would not be able to confirm if this affects purchase, but it certainly does not seem to affect general browsing.

**Comment by tkp206093** [comment]
If you add Fuck Fuckadblock
Use sarch or go to checkbox
The position where the ad will be displayed is not effectively cleared
![image](https://user-images.githubusercontent.com/29872453/126883398-16a44dc3-a726-461a-8570-6f7249d0ba19.png)
![image](https://user-images.githubusercontent.com/29872453/126883405-161d2e83-e045-45d6-af25-fba2870df176.png)

off the Fuck Fuckadblock
![image](https://user-images.githubusercontent.com/29872453/126883418-fce547ec-7f56-4c6d-9da2-0c73d8a39da3.png)
![image](https://user-images.githubusercontent.com/29872453/126883422-cc45afee-0823-493b-9c80-7161aa760f20.png)

**Comment by uBlock-user** [comment]
> If you add Fuck Fuckadblock

It's not a default list, so issue caused by that list should only be reported there.

**Comment by tkp206093** [comment]
> > 如果你添加他媽的Fuckadblock
> 
> 它不是默認列表，因此由該列表引起的問題應該只在那里報告。

https://github.com/bogachenko/fuckfuckadblock/issues/207

Is he referred here

**Comment by uBlock-user** [comment]
@tkp206093 and the original issue was resolved in https://github.com/uBlockOrigin/uAssets/commit/ebe1125b8dfebaa3bdf5c32e8e8bfdfe2e08e0bd
