### ISSUE TITLE
[anti-copy] book.zhulang.com

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#9627]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`http://book.zhulang.com/399241/122293.html`

### Describe the issue

Hello!
This page prevents copying
Thanks!

### uBlock Origin version

v1.36.2

### Browser name and version

Microsoft Edge 91.0.864.70

### Settings

No need

**Comment by dev-1a** [comment]
I think it is not fixed

**Comment by gwarser** [comment]
Try:

    book.zhulang.com##+js(aeld, /contextmenu|selectstart/)

**Comment by uBlock-user** [comment]
whats not fixed ? Fix is present in uBlock Annoyances list.

**Comment by okiehsch** [comment]
Right click is disabled with up to date annoyance list on my end.
