### ISSUE TITLE
bloomberg.com - broken video player

### ISSUE THREAD

**Issue by thinksheiscool** [uBlockOrigin/uAssets#9630]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.bloomberg.com/news/articles/2021-07-25/fauci-says-u-s-moving-in-wrong-direction-in-combating-covid?srnd=premium-europe`

### Describe the issue

The video player that is present in the given URL does not work properly.

### uBlock Origin version

1.37.0

### Browser name and version

Google Chrome 92.0.4515.107 (Official Build) (64-bit)

### Settings

none

**Comment by thinksheiscool** [comment]
It may actually not be broken.

**Comment by uBlock-user** [comment]
You have to wait few seconds for the video to start.
