### ISSUE TITLE
brainly.com.br

### ISSUE THREAD

**Issue by Pccode66** [uBlockOrigin/uAssets#9632]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://brainly.com.br/tarefa/46687798` after accessing `https://brainly.com.br/tarefa/20204402`

### Describe the issue

Brainly is blocking access to answers when you access more than one question. I have reproduced this on Firefox and Chrome.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/49125134/126914562-49afc839-6625-45ca-85a8-e95707761687.png)

### uBlock Origin version

1.37.0 in Chrome and 1.36.2 in Firefox

### Browser name and version

Firefox 90.0.2 / Chrome 91.0.4472.164

### Settings

- Default Settings

### Notes

Clearing Local Storage works. Disabling JavaScript breaks some features, but also works. I haven't figured out how to bypass it with static filtering.

**Comment by uBlock-user** [comment]
Blocking cookies seems to work, also this cannot be fixed without breaking the localStorage somehow.

**Comment by gorhill** [comment]
This works:

    brainly.com##+js(set-local-storage-item, social-qa/telemetry)

Does this qualify for annoyances list?

**Comment by stephenhawk8054** [comment]
Oops, I've just addressed it in annoyances list: https://github.com/uBlockOrigin/uAssets/commit/e9ba4e046213e80c11a96ab74336da6e6fbabb4f

I thought `/` would require `trusted`, so cannot be addressed in EL. I think it's qualified for annoyances list at least. The site also has an option to bypass by watching ads (which would require turning off uBO), which IMO is also suitable for main lists.

**Comment by gorhill** [comment]
> I thought `/` would require trusted

Only for `set-cookie`, not `set-local-storage-item`. But then I realise I forgot to use `$remove$` and it still worked. I need to fix this to comply with the [documentation](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#set-local-storage-item).

**Comment by stephenhawk8054** [comment]
> Only for `set-cookie`, not `set-local-storage-item`. But then I realise I forgot to use `$remove$` and it still worked.

I thought it meant set local storage to empty string, hence it worked?

---

cc @ryanbr For loginwall annoyance list

Just a note that the site has many TLDs (`brainly.com`, `brainly.com.br`...)

```adb
brainly.*##+js(set-local-storage-item, social-qa/machineId, $remove$)
```

**Comment by Freduser9** [comment]
The reported problem is occurring again: *blocking access to answers*, and there are also blank spaces between them.
I was able to reproduce the problem by accessing `https://brainly.com.br/tarefa/65032692` and after `https://brainly.com.br/tarefa/60220678`

<details>
<summary>Space</summary>

<img width="1365" height="767" alt="Image" src="https://github.com/user-attachments/assets/8bb2a2ff-0e89-469b-a448-09c6d1c69cf4" />

</details>

**Comment by Freduser9** [comment]
I enabled the `uBlock filters – Annoyances` list and the blocking problem was resolved.
With the help of AI, the white spaces were removed using this filter.

```adb
brainly.*##[data-testid^="ad_below"]
```
