### ISSUE TITLE
online-fix.me anti-adblock 

### ISSUE THREAD

**Issue by subby2006** [uBlockOrigin/uAssets#9633]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://online-fix.me/games/rpg/16269-monster-hunter-world-po-seti.html`
You will need an account to see download links, use bugmenot or I can provide you one

### Describe the issue

Download links not available, please turn off Adblock instead of download links showing

### uBlock Origin version

1.36.2

### Browser name and version

Firefox Mobile 90.1.2 

### Settings

Stock uBO

**Comment by dimisa-RUAdList** [comment]
@uBlock-user 
@mapx- 
@Yuki2718 
Please del: `online-fix.me##+js(nostif, /width|innerHTML/)`
No longer required.
