### ISSUE TITLE
Add NSO Group Orgasus spyware infection domain blocklist to malware domains



### ISSUE THREAD

**Issue by ccuser44** [uBlockOrigin/uAssets#9640]
It would be nice if this block list would be added: AmnestyTech/investigations#4

Here is a blocklist which can be used: https://github.com/travisboss/Jefe-Lists/blob/main/pegasus_blocklist.txt
This blocklist can be used automaticly

**Comment by uBlock-user** [comment]
> Opening issues for adding new filter lists is now disallowed and such issues will be declined and closed.

Already told you that once, must you open it again ?

**Comment by uBlock-user** [comment]
New filter lists are only added based on internal discussions with the team and gorhill.
