### ISSUE TITLE
megaup.net anti adblock again

### ISSUE THREAD

**Issue by subby2006** [uBlockOrigin/uAssets#9643]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://megaup.net/1E24y/837626250330636298.png`

### Describe the issue

anti adblock is back.
these sites get stubborn every day

### uBlock Origin version

1.37.0

### Browser name and version

Firefox Mobile 90.1.2

### Settings

Default

**Comment by avotoko** [comment]
Works for me.
```
megaup.net#@#[id*="ScriptRootC"]:upward(1):style(position:absolute !important;left:-3000px !important)
megaup.net##[id*="ScriptRootC"]:upward(1):style(position:absolute !important;right:3000px !important)
```

**Comment by avotoko** [comment]
Anti-adblock is back. `https://megaup.net/2keal/Car.Mechanic.Simulator.2021-DOGE.part1.rar`
This works.
```
megaup.net#@#[id*="ScriptRootC"]:upward(1):style(position:absolute !important;left:-3000px !important)
megaup.net##[id*="ScriptRootC"]:upward(1):style(position:absolute !important;right:3000px !important)
```
