### ISSUE TITLE
www.msn.cn

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#9650]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.msn.cn/zh-cn/money/news/%E5%8F%B0%E9%A3%8E-%E7%83%9F%E8%8A%B1-%E7%99%BB%E9%99%86%E5%8D%8A%E5%B0%8F%E6%97%B6%E5%89%8D-%E4%B8%8A%E6%B5%B7%E5%B7%B2%E5%AE%89%E5%85%A8%E8%BD%AC%E7%A7%BB36%E4%B8%87%E4%BA%BA-%E6%97%A0%E4%BA%BA%E5%91%98%E4%BC%A4%E4%BA%A1/ar-AAMwKy8?ocid=winp1taskbar`

### Describe the issue

You may need Microsoft Edge browser to see this ad
Easylist China does not seem to be able to solve this problem

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66902050/127155591-3ab1d403-4977-4819-a160-065b2fc6f02f.png)

### uBlock Origin version

v1.36.2

### Browser name and version

Microsoft Edge 91.0.864.70

### Settings

![image](https://user-images.githubusercontent.com/66902050/127155632-11d4be88-9f84-4d44-90c6-b307e51e3327.png)

**Comment by uBlock-user** [comment]
Did you report this to AdGuard first ?

**Comment by shenzhiming88** [comment]
> Did you report this to AdGuard first ?

No, but I can block this ad by AdGuard

**Comment by uBlock-user** [comment]
Unblocked ads on should be reported to AdGuard first, thats what AdGuard Chinese is for.

**Comment by uBlock-user** [comment]
@AdamWr

**Comment by AdamWr** [comment]
Hmm, I can't reproduce this ad with AdGuard extension.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/127159118-f42f054e-262a-44c9-a6f6-dd5ca2f302ec.png)

</details>

I will add some rules, but I'm not sure if it will works with uBlock Origin.

**Comment by shenzhiming88** [comment]
@AdamWr Thank you, but it looks like these rules don't apply to uBlock

**Comment by uBlock-user** [comment]
```
msn.cn##+js(json-prune, *, list.*.link.ad list.*.link.kicker)
msn.cn##msft-article[id^="native_ad_nativead"]
```

@shenzhiming88 works ?

**Comment by shenzhiming88** [comment]
@uBlock-user Yes, but there is still a gap here
![image](https://user-images.githubusercontent.com/66902050/127162477-c1e18052-74cd-4710-a9f0-505dba538a48.png)

**Comment by uBlock-user** [comment]
I don't see any ads anyway, so you will have to come up with a filter or find the element so we can hide it.

**Comment by shenzhiming88** [comment]
@uBlock-user Sorry, but I can't find the specific element
![image](https://user-images.githubusercontent.com/66902050/127163119-d7f77a05-52e2-454b-910d-855d76633c34.png)

**Comment by AdamWr** [comment]
Probably there is no easy way to fix this gap.

**Comment by shenzhiming88** [comment]
@uBlock-user Hmm, when I update the filter rules, this blank is still here
![image](https://user-images.githubusercontent.com/66902050/127269390-7fd1b18b-4423-4836-9666-998a9f17019f.png)

**Comment by uBlock-user** [comment]
@shenzhiming88 I never fixed that, as I can't reproduce any ads on Chrome or Firefox.

**Comment by shenzhiming88** [comment]
@uBlock-user Yes, I can't see any ads either, but the gap is still here, even after I do a hard refresh
Should I give feedback to AdGuard?
