### ISSUE TITLE
[Anti-copy] time.geekbang.org

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#9654]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://time.geekbang.org/column/article/397646`

### Describe the issue

Hello!
Although you can copy using C-C on this page, the content is incomplete and the format is corrupted
Thank you

### uBlock Origin version

v1.36.2

### Browser name and version

Microsoft Edge 91.0.864.70

### Settings

No need

**Comment by shenzhiming88** [comment]
@uBlock-user Hello!
This may not be fully fixed
![2021-08-01_19-08-07](https://user-images.githubusercontent.com/66902050/127768593-dfbd203b-dc12-4fd4-9d00-6066e8c33f72.gif)

**Comment by uBlock-user** [comment]
@uBlock-user Whats not fixed ? Describe in words.

**Comment by uBlock-user** [comment]
@shenzhiming88 whats not fixed ? Describe in words.

**Comment by uBlock-user** [comment]
`time.geekbang.org##.RichContentPC_mask_16_RZ` will hide the invisible layer that appears after selecting some text, black menu appearing and causing anything else to be unselectable.

**Comment by shenzhiming88** [comment]
@uBlock-user Hello! Yes, as you said, the right-click menu will not work on the selected text after it is selected, please add `time.geekbang.org##.RichContentPC_mask_16_RZ` to the filter rule.
