### ISSUE TITLE
adbar repository broken

### ISSUE THREAD

**Issue by adbar** [uBlockOrigin/uAssets#9668]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://github.com/adbar/`

### Describe the issue

Hi,

Unfortunately my GitHub nickname falls prey to uBlock's `/adbar/` scheme, users can't interact properly with my repository: https://github.com/adbar/trafilatura/issues/104
I was able to reproduce the bug with my navigator.

Is there a way to whitelist GitHub or at least to restrict this behavior?

### uBlock Origin version

1.37.0

### Browser name and version

Mozilla Firefox 90.0

### Settings

None.

**Comment by uBlock-user** [comment]
temp fix `@@/adbar/*$domain=github.com` until @ryanbr fixes it in EasyList.

**Comment by adbar** [comment]
@uBlock-user Thanks!
