### ISSUE TITLE
vimm.net

### ISSUE THREAD

**Issue by subby2006** [uBlockOrigin/uAssets#9669]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://vimm.net/vault/17629`

### Describe the issue

Error on download page, possible anti adblock

### uBlock Origin version

1.37.0

### Browser name and version

Firefox Mobile 90.1.2

### Settings

Stock

**Comment by kaikyoofers** [comment]
Site is detecting ad blocker

<details>

```yml
name: uBlock Origin Lite
version: 2026.901.1442
browser: Chrome 152 (linux)
filtering:
 site: optimal
 default: optimal
permission: all
badge: 5
rules: 30740
rulesets:
 +annoyances-cookies
 +annoyances-notifications
 +annoyances-others
 +annoyances-overlays
 +annoyances-widgets
 +chn-0
 +jpn-1
 easylist
 easyprivacy
 pgl
 spa-1
 ublock-badware
 ublock-filters
 urlhaus-full
scripting:
 ublock-filters.main
 ublock-filters.isolated
 easyprivacy.main
 easyprivacy.isolated
 ublock-badware.main
 ublock-badware.isolated
 annoyances-cookies.main
 annoyances-cookies.isolated
 annoyances-overlays.main
 annoyances-overlays.isolated
 annoyances-others.main
 annoyances-others.isolated
 annoyances-notifications.main
 annoyances-notifications.isolated
 chn-0.main
 chn-0.isolated
 jpn-1.main
 jpn-1.isolated
 spa-1.main
 spa-1.isolated
 prevent-popup
 css-specific
 css-user
```

</details>

<details>

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/f71e3dac-a3fb-4b1b-883e-4dacc4031f65" />

</details>

**Comment by gothic-bum** [comment]
@kaikyoofers 

I just tested and there was no detection.

Test again using a new browser profile with only uBO and its default settings. If your browser provides built-in content blocking (Brave, Edge, Opera, etc), make sure it is disabled when testing.
