### ISSUE TITLE
cheatsquad.gg scrollbar 

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#9672]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://cheatsquad.gg/csgo`

### Describe the issue

anti scrollbar

### uBlock Origin version

1.37.0

### Browser name and version

Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)

### Settings

"I am an advanced user"

**Comment by thinksheiscool** [comment]
@uBlock-user 


https://user-images.githubusercontent.com/87933966/127617489-adaa9be3-0f99-4522-be98-54280332e196.mp4

**Comment by uBlock-user** [comment]
Scrolling works, but the scroll bar doesn't appear in Chromium, is that the issue ?

**Comment by thinksheiscool** [comment]
> Scrolling works, but the scroll bar doesn't appear in Chromium, is that the issue ?

yes

**Comment by uBlock-user** [comment]
see - https://github.com/uBlockOrigin/uBlock-issues/issues/1247

**Comment by krystian3w** [comment]
But my issue is about recover scroll arrows - possible is recover hidden scrollbar middle button by uBO 1.8.0+.

**Comment by uBlock-user** [comment]
@krystian3w Until @gorhill implements support for `::-webkit-*` I can't add a `:style()` rule for it.

**Comment by krystian3w** [comment]
IMO better recover middle button if is hidden than waiting to allow stylize arrows in `-webkit-` CSS.

**Comment by krystian3w** [comment]
Also possible follow this project:

https://github.com/ubershmekel/default-scrollbar

https://chrome.google.com/webstore/detail/default-scrollbar/nkjmoagfbmeafonfhbkeicjdhjlofplo

**Comment by krystian3w** [comment]
@okiehsch / @mapx- test these and found better "default" colors:

```css
cheatsquad.gg##*::-webkit-scrollbar:style(width: 17px !important; display: initial !important;)
cheatsquad.gg##*::-webkit-scrollbar-thumb:style(background: #5e5e5e;  border: 0 none #fff !important;  border-radius: 0 !important; display: initial !important;)
```

---

@lassekongo83 are you fixed `proffs.se` in Sweeden list or move this to uAssets?

> https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-685464983
> https://github.com/DandelionSprout/adfilt/issues/63#issuecomment-685640124

**Comment by uBlock-user** [comment]
@krystian3w added
