### ISSUE TITLE
www.techilife.com - Anti-Adblock message (filter in notes)

### ISSUE THREAD

**Issue by m0nstrz** [uBlockOrigin/uAssets#9674]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.techilife.com`

### Describe the issue

After loading the website a message appears stating the following:

Techilife
We Detected an AdBlock on Your Browser
Please help us continue to provide you with free, quality journalism by disabling your ad blocker on www.techilife.com / Ads Help us pay for the server fee and other charges to keep providing you non stop services. Thanks!

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7475724/127622347-cf01b9f5-a0c7-4640-a0c2-6ae9e3eaa198.png)

### uBlock Origin version

uBlock Origin 1.37.0

### Browser name and version

Firefox 90.0.2 (64-bit)

### Settings

N/A

### Notes

Here is my filter to remove the pop-up:

techilife.com##.jconfirm-no-transition.jconfirm-animated.jconfirm-box-container
techilife.com##.jconfirm-bg
techilife.com##.jconfirm-holder
techilife.com##.jconfirm-cell
techilife.com##.jconfirm-scrollpane
techilife.com##.jconfirm-open.jquery-css.jconfirm-white.jconfirm
techilife.com##body:style(overflow: auto !important;)

**Comment by thinksheiscool** [comment]
It looks there are placeholders on the right.
