### ISSUE TITLE
Subscribe dropdown on doctorofcredit.com pages does not expand

### ISSUE THREAD

**Issue by Ryan-Goldstein** [uBlockOrigin/uAssets#9678]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.doctorofcredit.com/arcadia-power-pay-your-electric-bill-with-credit-card-for-no-fee-available-nationwide/`
`https://www.doctorofcredit.com/mn-pa-mi-genisys-credit-union-4-06-apy-high-yield-checking-account-up-to-7500/`
(every article on the website seems to be affected)

### Describe the issue

The Subscribe dropdown above the comments - ![screenshot](https://user-images.githubusercontent.com/8300089/127721149-0b95472b-5f91-4e2d-b146-bbf7b42c142c.png) - does not expand with uBlock Origin enabled. The only two assets on the page blocked upon load are `||googlesyndication.com^` and `||googletagmanager.com^`, both from Peter Lowe’s Ad and tracking server list. Disabling uBlock Origin and reloading the page fixes it, such that the Subscribe dropdown can expand.

### uBlock Origin version

1.37.2

### Browser name and version

Chrome 93.0.4577.18 beta (64-bit)

### Settings

N/A

**Comment by okiehsch** [comment]
![Unbenannt](https://user-images.githubusercontent.com/16838044/127728147-8127488f-bcbb-412c-8a4c-55f5d4cb451a.PNG)

**Comment by uBlock-user** [comment]
Test on default settings/lists.
