### ISSUE TITLE
Video does not load in Firefox, but does in Chrome

### ISSUE THREAD

**Issue by xclm** [uBlockOrigin/uAssets#9681]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Recently, I switched from Chrome to Firefox and uBlock Origin works fine.
The only thing i noticed is that videos on a specific website (spiegel.de) dont load, while they do when using chrome.

`https://www.spiegel.de/panorama/syrische-fluechtlinge-helfen-bei-aufraeumarbeiten-in-ahrweiler-nach-der-flutkatastrophe-a-c928692c-433f-44c6-aa80-6779b688b831`

I use the same filters, settings and exceptions in both browsers but only in Chrome the video plays.

### A specific URL where the issue occurs

`https://www.spiegel.de/panorama/syrische-fluechtlinge-helfen-bei-aufraeumarbeiten-in-ahrweiler-nach-der-flutkatastrophe-a-c928692c-433f-44c6-aa80-6779b688b831`

### Steps to Reproduce

Try to watch the video in example link

### Expected behavior

Video plays

### Actual behavior

Video loads forever

### uBlock Origin version

uBlock Origin 1.37.2

### Browser name and version

Firefox 91

### Operating System and version

Windows 10

**Comment by uBlock-user** [comment]
Reset to default settings and try again.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/127764347-d87e4f07-a63d-41f8-a3fb-4411d25ba822.png)

Works fine on my end.
