### ISSUE TITLE
DubsStreamz detecting ublock origin

### ISSUE THREAD

**Issue by notnottonystark** [uBlockOrigin/uAssets#9682]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### Description

Uhm guys, do you know what filters I need to add? cause purge cache and update now doesn't seem to work. Also I haven't messed with any of the settings and what I think what's tricky is that they only live during events.

Here's their discord:https://discord.gg/nTdC4sW9 where they post links for the live events

### A specific URL where the issue occurs

`http://www.dubzstreams.com/livegames/2021/08/liveolympics/olympics-channel/`

### Steps to Reproduce

.

### Expected behavior

.

### Actual behavior

.

### uBlock Origin version

.

### Browser name and version

.

### Operating System and version

.

**Comment by uBlock-user** [comment]
@BlueBurn100 Would you stop removing the url please ? This issue is linked in the filter for when next time we need to look for a fix.
