### ISSUE TITLE
tyfloswiat.pl - referer infection

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#9685]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.google.com/search?q=https%3A%2F%2Ftyfloswiat.pl%2Fartykul-balabolka-zamiast-instrukcji-obslugi%2F`
`https://www.google.com/search?q=Artyku%C5%82%3A%20Balabolka.%20Zamiast%20instrukcji%20obs%C5%82ugi`

### Describe the issue

Another page with crapware installed into Wordpress by outdated plugins/version of WP engine similar to #9601 (and maybe #8666)

To reproduce open any `tyfloswiat.pl` form Google (but i prefere article "Artykuł: Balabolka. Zamiast instrukcji obsługi").

---

Bad page opened by referer:

[NSFW] `https://bedcity-lake.top/?t=main9&x=3` [NSFW]

maybe needed is update regex @Yuki2718:
https://github.com/uBlockOrigin/uAssets/blob/78f23f7491e219cc9ca285ec51c0a06513ccb175/filters/badware.txt#L654-L655

### Screenshot(s)

N/A = NSFW

### uBlock Origin version

1.37.2

### Browser name and version

FF 90

### Settings

- Enabled annoyances

### Notes

If Polish page must by fixed in MajkiIT suplement I try report this later in https://github.com/MajkiIT/polish-ads-filter/issues.

Now only can try block whole "`.top`" domains in Polish "Kad - Przekręty", optionaly fix referer too on `tyfloswiat.pl`

**Comment by Yuki2718** [comment]
@krystian3w Blocked the domain, need more examples to use regex.
