### ISSUE TITLE
Send Anywhere has apparently unskippable ad/timer

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#9686]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://send-anywhere.com`

### Describe the issue

Send Anywhere is a file transfer site.

It has ads that are seemingly unskippable.

To reproduce, try to send a file from your phone to your computer. You should get a code. Input the code you get on your phone into your computer.

Then, the ad appears. It isn't really an ad, since nothing shows but a five-second timer. When the timer ends, the skip button shows. But it's still annoying.

### Screenshot(s)

https://user-images.githubusercontent.com/52135169/127789604-1f13035d-e0ec-4b87-8c45-e6177fe0b99d.mp4

### uBlock Origin version

1.37.2

### Browser name and version

Mozilla Firefox 90.0.2

### Settings

N/A

**Comment by uBlock-user** [comment]
ad cannot be completely blocked, so skipped it.
