### ISSUE TITLE
uBlock Origin blocks jen.jiji.com

### ISSUE THREAD

**Issue by stm-x** [uBlockOrigin/uAssets#9688]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://jen.jiji.com/jc/eng_afp?k=20210802041848a`

### Describe the issue

> Machine translation is used
Please let me know if there are any sentences that are not clear.

jen.jiji.com is the English site of Jiji Press, but it is Blocked by `||jen.jiji.com^` rules

### Screenshot(s)

![image](https://user-images.githubusercontent.com/86018494/127832116-a16b8bcd-2983-46f4-8670-724278de84b2.png)

### uBlock Origin version

1.37.2

### Browser name and version

edge 92

### Settings

Default lists + AdGuard Japanese

### Notes

Maybe `jen.jiji.com` is a tracker for the Japanese version of the site `https://www.jiji.com/`
![キャプチャ](https://user-images.githubusercontent.com/86018494/127837476-9a685184-0118-4503-8a74-2ec84d64b3b6.PNG)
![キャプチャ](https://user-images.githubusercontent.com/86018494/127838141-13698fa5-5662-49f3-9cdd-1385f343c6d0.PNG)

**Comment by okiehsch** [comment]
@stm-x This has now been fixed in `EasyPrivacy`, if you update that list the site should work as expected.

**Comment by stm-x** [comment]
It works fine.
thanks.
