### ISSUE TITLE
pirateproxy.wtf (timer)

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uAssets#9689]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://pirateproxy.wtf` and click at a link or go directly `https://pirateproxy.wtf/?piratebay.uno`

### Describe the issue

Timer after clicking at a link for ex. `https://pirateproxy.wtf/?piratebay.uno`

### Screenshot(s)

![Nagrywaj_2021_08_02_11_09_35_33](https://user-images.githubusercontent.com/75935068/127840634-6686b214-49b0-48e9-8013-e4b7c0e2d3b9.gif)

### uBlock Origin version

1.37.3b3

### Browser name and version

FF 90.0.2

### Settings

-

### Notes

Tried to speed up the timer by `pirateproxy.wtf##+js(nano-sib, countdown, 1000)` but it does not work, any idea why?

```js
<h3>Please Wait....You will be redirected in <span id="counter">12</span> second(s).<h3>
<script type="text/javascript">
function countdown() {
    var i = document.getElementById('counter');
    if (parseInt(i.innerHTML)<=0) {
        location.href ="https://piratebay.uno";
    }
    i.innerHTML = parseInt(i.innerHTML)-1;
}
setInterval(function(){ countdown(); },1000);
</script>
```

**Comment by uBlock-user** [comment]
server sided timer.
