### ISSUE TITLE
[Anti-Adblock Banner] Adblock Detection Nag on Alternativeto.Net

### ISSUE THREAD

**Issue by Targren** [uBlockOrigin/uAssets#9690]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://alternativeto.net`

### Describe the issue

I'm not sure if nag banners are even on the radar.

### Screenshot(s)

![Capture](https://user-images.githubusercontent.com/11566412/127919480-871b6d8b-d070-434a-a13f-a1aab4dadca6.PNG)

### uBlock Origin version

1.37.2

### Browser name and version

Chrome 92, Vivaldi 4.1.2369.11

### Settings

- None that I remember

**Comment by uBlock-user** [comment]
Test on default settings + all other extensions disabled.

**Comment by Targren** [comment]
Well, that's certainly odd.  Resetting both to default settings, the banner disappears on chrome, still appears on Vivalid.  Guess we can pin this one on "unsupported browser." 

Thanks for the quick response!

**Comment by uBlock-user** [comment]
> still appears on Vivalidi

Vivaldi comes with built-in adblock, disable that too.

**Comment by Targren** [comment]
> > still appears on Vivalidi
> 
> Vivaldi comes with built-in adblock, disable that too.

That was it! Thanks!

**Comment by KhalilOuali** [comment]
> Vivaldi comes with built-in adblock, disable that too.

Same issue on Brave, same fix. Thank you!
