### ISSUE TITLE
Peter Lowes block list blocks affiliate links

### ISSUE THREAD

**Issue by stm-x** [uBlockOrigin/uAssets#9692]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

###  `https://twitter.com/sm_room8/status/1421696779309879300`
`https://rcm-fe.amazon-adsystem.com/e/cm?ref=qf_sp_asin_til&t=smroom8-22&m=amazon&o=9&p=8&l=as1&IS1=1&detail=1&asins=B07RGZ5NKS&linkId=9d8593ce8f88154114763e5821dde863&bc1=FFFFFF&lt1=_top&fc1=333333&lc1=0066C0&bg1=FFFFFF&f=ifr`
`https://ws-fe.assoc-amazon.com/widgets/cm?ref=qf_sp_asin_til&t=smroom8-22&m=amazon&o=9&p=8&l=as1&IS1=1&detail=1&asins=B07RGZ5NKS&linkId=9d8593ce8f88154114763e5821dde863&bc1=FFFFFF&lt1=_top&fc1=333333&lc1=0066C0&bg1=FFFFFF&f=ifr`
### `https://www.wata-ridley.com/entry/joy-con-repair`
`https://hb.afl.rakuten.co.jp/hgc/0c15d030.dfeb806c.0c208255.96ceb2e4/738778333_800837?pc=https%3A%2F%2Fsearch.rakuten.co.jp%2Fsearch%2Fmall%2F%25E3%2582%25A8%25E3%2583%25AC%25E3%2582%25B3%25E3%2583%25A0%2B%25E3%2582%25A8%25E3%2582%25A2%25E3%2583%2580%25E3%2582%25B9%25E3%2582%25BF%25E3%2583%25BC%2F`

### Describe the issue

> Machine translation is used
Please let me know if there are any sentences that are not clear.

The amazon-adsystem.com link is rarely used, but hb.afl.rakuten.co.jp is often used by many sites.

### uBlock Origin version

1.37.2

### Browser name and version

edge 92

### Settings

Default lists + AdGuard Japanese

**Comment by uBlock-user** [comment]
> amazon-adsystem.com

Amazon's ad-server, so would be blocked.

**Comment by stm-x** [comment]
How about limiting it to third parties like easylist?

**Comment by uBlock-user** [comment]
Link would still remain semi-broken -- `https://ws-fe.assoc-amazon.com/widgets/cm?ref=qf_sp_asin_til&t=smroom8-22&m=amazon&o=9&p=8&l=as1&IS1=1&detail=1&asins=B07RGZ5NKS&linkId=9d8593ce8f88154114763e5821dde863&bc1=FFFFFF&lt1=_top&fc1=333333&lc1=0066C0&bg1=FFFFFF&f=ifr`

because resources(images) comes from that ad-server.

**Comment by pgl** [comment]
What @uBlock-user said. It's an ad server.

**Comment by uBlock-user** [comment]
@pgl Is `rakuten.co.jp` an ad-server ?

**Comment by pgl** [comment]
@uBlock-user Not the parent domain, I only have entries for:

`ba.afl.rakuten.co.jp`
`hb.afl.rakuten.co.jp`
`hbb.afl.rakuten.co.jp`

**Comment by uBlock-user** [comment]
Yes are they involved in tracking or serving ads ?

**Comment by pgl** [comment]
These are tracking servers - they register link clicks and use it for marketing purposes.

**Comment by uBlock-user** [comment]
@pgl Is `assoc-amazon.com` also an ad-server ?

**Comment by pgl** [comment]
@uBlock-user I consider it another tracking server.

**Comment by Yuki2718** [comment]
> 
> `ba.afl.rakuten.co.jp`
> `hb.afl.rakuten.co.jp`
> `hbb.afl.rakuten.co.jp`

FWIW among them `hb.afl.rakuten.co.jp` is used solely as click-through tracker and not as third-party: https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/441
