### ISSUE TITLE
Alexa plugin popup blocked in Chrome

### ISSUE THREAD

**Issue by gaomengzhou** [uBlockOrigin/uAssets#9695]
### Prerequisites

- [X] I verified that this is not a filter issue (MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues))
- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues) to avoid opening a duplicate issue
- [X] The issue is not present after wholly disabling uBlock Origin ("uBO") in the browser
- [X] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [x] using a new, unmodified browser profile

### Description

这个插件屏敝了Alexa统计网站排名插件.

### A specific URL where the issue occurs

https://chrome.google.com/webstore/detail/alexa-traffic-rank/cknebhggccemgcnbidipinkifmmegdel?utm_source=chrome-ntp-icon

### Steps to Reproduce

1.开起uBlock
2.点击Alexa插件
3.显示此页面以被某个扩展程序屏敝

![16cdfd1c-a046-4744-b59b-9966feb91e20](https://user-images.githubusercontent.com/45467244/128131052-bc33c037-421a-4cba-90b7-27489b03b20f.jpg)

### Expected behavior

不要屏敝这个插件

### Actual behavior

屏敝了ALEXA 插件

### uBlock Origin version

1.37.2

### Browser name and version

chrome    version:92.0.4515.107

### Operating System and version

 WIN10

**Comment by uBlock-user** [comment]
Test on default settings/lists.

**Comment by gaomengzhou** [comment]
Before enabling
![0efeeff6-da66-4851-929c-51c6140ec039](https://user-images.githubusercontent.com/45467244/128157775-dd1238c1-9600-4f1f-9cce-6de21634c3ce.jpg)

After enabling
![50b1b5e5-eec8-4249-a4a0-2c89e9461903](https://user-images.githubusercontent.com/45467244/128157815-211b4eb0-e7cb-4943-a94a-81a38b313c46.jpg)

**Comment by uBlock-user** [comment]
Reset uBO to default settings/lists.

**Comment by gaomengzhou** [comment]
> Reset uBO to default settings/lists.

Thanks!!
