### ISSUE TITLE
techpowerup.com

### ISSUE THREAD

**Issue by AroKol78** [uBlockOrigin/uAssets#9696]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.techpowerup.com/`

### Describe the issue

adblock detect 
some pictures are missing  

### Screenshot(s)

![gp001](https://user-images.githubusercontent.com/70756447/128165201-3245691b-7f4a-4422-8a21-7e8bd1ecf145.PNG)

### uBlock Origin version

legacy 1.16.4.30

### Browser name and version

Serpent52 20210730

### Settings

uBlock filters – Annoyances
KAD - Przekręty
NoCoin Filter List

**Comment by uBlock-user** [comment]
>  some pictures are missing

No such issue on Firefox or Chrome.

**Comment by JobcenterTycoon** [comment]
@uBlock-user article pictures are still broken by `techpowerup.com##[target="_blank"] [src^="https://www.techpowerup.com/"].` 

Example: `https://www.techpowerup.com/284232/nintendo-announces-nintendo-switch-oled-model-with-a-vibrant-7-inch-oled-screen-launching-october-8th`

**Comment by AroKol78** [comment]
broken `https://www.techpowerup.com/forums/` (uBlock filters `techpowerup.com###top > div > div[class]`)
helps me `techpowerup.com#@##top > div > div[class]`

**Comment by JobcenterTycoon** [comment]
a bit modified: `techpowerup.com##header[id="top"] > div + div > div[class]` blocks the ad for me without breakage

@uBlock-user images from `techpowerup.com/img/` need to be whitelistet too because it breaks article images when i click on it to get a better view
<img width="533" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/128222041-4232e49e-37ea-4330-b0b9-fe6dd1364d94.PNG">

**Comment by AroKol78** [comment]
yesterday was good and today broken `https://www.techpowerup.com/download/techpowerup-gpu-z/`
by `techpowerup.com##header img[src]:upward(div[class]):has(img[src])`

**Comment by uBlock-user** [comment]
@AroKol78 because the admin is self-sabotaging the site, so you can come here and report about it believing we broke it.

**Comment by AroKol78** [comment]
i added to "My filters" `techpowerup.com##header.site-header img[src]:upward(div[class]):has(img[src])` from https://github.com/uBlockOrigin/uAssets/commit/2e4055c781fddd2478a545a4228cf940780693ba for checking and it seems to be fine

**Comment by uBlock-user** [comment]
@AroKol78 admin will use that to break his own site within hours and it won't be fine anymore

**Comment by JobcenterTycoon** [comment]
The ads got fixed by EasyList a few hours ago and the breakage got fixed too

**Comment by IMayKnow** [comment]
ads

**Comment by IMayKnow** [comment]
I encountered ads.

**Comment by JobcenterTycoon** [comment]
`techpowerup.com##a[rel^="nofollow"][target="_blank"]:has(img)`
`techpowerup.com##div[id][class] > *:has(label):not(article[class^="content"]) > *:has(a):has(img)`
`techpowerup.com##div[class]:has(label + script + a) + [class]:has(a):has(img)`

Works for me and i not see any breakage at the first look but i can’t check the complete site. But the admin like to break their own site when a filter get added

**Comment by JobcenterTycoon** [comment]
Ads are back. The filter above still working

**Comment by uBlock-user** [comment]
Gets fixed within hours, so need to add to the list, use it until it lasts. More people need to come up with solutions.

**Comment by JobcenterTycoon** [comment]
It was a nice try to wait 10 days but no they still watching us

**Comment by uBlock-user** [comment]
`techpowerup.com##a[href][rel="nofollow"][target="_blank"] > img[src]` works fine.

**Comment by ThinksHeIsCool** [comment]
ads

**Comment by JobcenterTycoon** [comment]
```
techpowerup.com##div[id][class] > *:has(label):not(article[class^="content"]) > *:has(a):has(img)
techpowerup.com##[id][class] > div[class]:has(label) + [class]:has(a[target="_blank"]):has(img)
```

**Comment by JobcenterTycoon** [comment]
simpler: `techpowerup.com##a[href][target="_blank"]:not([data-width][data-height][data-fancybox]):has(img)`

**Comment by dPoRtvine** [comment]
`https://www.techpowerup.com/`

<details>
<summary>Screen</summary>

![2021-10-29_222530](https://user-images.githubusercontent.com/57287308/139491150-2a8ed76f-c251-4d28-867a-26b2ebe1c22b.png)
</details>

**Comment by dPoRtvine** [comment]
`https://www.techpowerup.com/`

<details>
<summary>Screen</summary>

![2021-10-30_084612](https://user-images.githubusercontent.com/57287308/139521934-0f481fa0-6542-4778-9bb1-b63fa3abf9d9.png)
</details>

**Comment by JobcenterTycoon** [comment]
Ads are back. Possible filters:

<details

`techpowerup.com##[id][class]:not(html) > *:has(label):not(article[class^="content"]) > *:has(a):has(img)`
`techpowerup.com##[id][class]:not(html) > [class]:has(label) + [class]:has(a):has(img):not(aside[class^="side-"])`

`techpowerup.com##[src]:not([src^="https://tpucdn.com/forums/data/avatars/"][loading][class]):not([src^="/gpu-specs/images/b/"][alt][height][width]):upward([href*="."]:not([href*="jpg"]):not([href*="png"]))`
</details>

**Comment by dPoRtvine** [comment]
`https://www.techpowerup.com/`

<details>
<summary>Screen</summary>

![2021-11-01_094358](https://user-images.githubusercontent.com/57287308/139638417-846a29d1-eea4-497b-aed4-32a705ebdfd5.png)
</details>

**Comment by dPoRtvine** [comment]
`https://www.techpowerup.com/`

<details>
<summary>Screen</summary>

![2021-11-01_121701](https://user-images.githubusercontent.com/57287308/139662905-607d86b4-01f7-4e3d-984b-5baada552a0f.png)
</details>

**Comment by dPoRtvine** [comment]
`https://www.techpowerup.com/`

<details>
<summary>Screen</summary>

![2021-11-01_140141](https://user-images.githubusercontent.com/57287308/139668396-40ac5509-6f1c-4420-9364-3eb42cb02235.png)
</details>

**Comment by JobcenterTycoon** [comment]
```
techpowerup.com##[src]:not([src^="https://tpucdn.com/forums/data/avatars/"][loading][class]):not([src^="/gpu-specs/images/b/"][alt][height][width]):upward([href*="."]):not([href*="/forums/attachments/"][data-fancybox]):not([href^="https://www.techpowerup.com/img/"][target="_blank"][data-width][data-height][data-fancybox])
techpowerup.com##body > div > div:has(img[class] + a[rel][target] + a[rel][target] + style)
techpowerup.com##body:style(background-color: whitesmoke !important)
```

?

**Comment by dPoRtvine** [comment]
`https://www.techpowerup.com/`

<details>
<summary>Screen</summary>

![2021-11-02_112653](https://user-images.githubusercontent.com/57287308/139820681-4613762d-3e4c-4a75-9e70-6f3182d43bf5.png)
</details>

**Comment by dPoRtvine** [comment]
`https://www.techpowerup.com/`

<details>
<summary>Screen</summary>

![2021-11-03_074642](https://user-images.githubusercontent.com/57287308/140015928-211d0e0a-590d-4b05-bf58-7561fbb604d0.png)
</details>
Maybe just? Will bypass but less problems.

`techpowerup.com##body > #viewport > header > span ~ div`
`techpowerup.com##.sidebar-item > i > [href] > img`

**Comment by dPoRtvine** [comment]
`https://www.techpowerup.com/`

<details>
<summary>Screen</summary>

![2021-11-04_090708](https://user-images.githubusercontent.com/57287308/140271725-237ea107-a91d-489b-b7fb-b280598d1ad4.png)
</details>

**Comment by No-ADS** [comment]
`https://www.techpowerup.com/`

<details>

![2021-12-03_154910](https://user-images.githubusercontent.com/94611448/144613204-bb6fd52f-6e30-46cd-af14-5fa55c725af4.png)
<summary>Screen</summary>
</details>

**Comment by JobcenterTycoon** [comment]
Background ads are back

**Comment by dmitryportvine** [comment]
`https://www.techpowerup.com/`
<details>
<summary>Screenshot(s)</summary>

![2022-01-14_002647](https://user-images.githubusercontent.com/97522612/149418856-9f4a58de-1ede-4c2b-b489-ef09dacd865f.png)
</details>

<details>

```yaml
uBlock Origin: 1.40.9b0
Firefox: 96
filterset (summary): 
  network: 94560
  cosmetic: 106244
  scriptlet: 20915
  html: 643
listset (total-discarded, last updated): 
  removed: 
    urlhaus-1: null
    plowe-0: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 29661-246, now
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1378-0, now
    fanboy-cookiemonster: 21506-121, now
    ublock-annoyances: 4373-4, now
    RUS-0: 40862-298, now
  default: 
    user-filters: 0-0, never
    ublock-filters: 30742-51, now
    ublock-badware: 3723-1, now
    ublock-privacy: 184-0, now
    ublock-abuse: 76-0, now
    ublock-unbreak: 1732-6, now
    easylist: 62917-240, now
    easyprivacy: 26622-328, now
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
  webrtcIPAddressHidden: true
modifiedHiddenSettings: 
  autoUpdateDelayAfterLaunch: 60
  autoUpdatePeriod: 1
  filterAuthorMode: true
  uiFlavor: classic
supportStats: 
  allReadyAfter: 672 ms (selfie)
popupPanel: null
```
</details>

**Comment by BottledSoda** [comment]
`https://www.techpowerup.com/`
with uBO => ads
with uBO + AdGuard Extra => ads are countered
