### ISSUE TITLE
[Auto-login pop-ups] blog.csdn.net

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#9697]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://blog.csdn.net/weixin_42350212/article/details/118111210`

### Describe the issue

Hello!
The page will automatically pop up the login window, is it possible to make it not pop up automatically? Thank you!
(You may need to clear the cookies, the popup only seems to appear once)

### Screenshot(s)

![2021-08-04_20-58-25](https://user-images.githubusercontent.com/66902050/128184856-d35fbebd-ef2f-4187-80a4-8da8f04b272c.gif)

### uBlock Origin version

v1.37.0

### Browser name and version

Microsoft Edge 92.0.902.62

### Settings

No need

**Comment by uBlock-user** [comment]
```
blog.csdn.net##.login-mark
blog.csdn.net###passportbox
```

**Comment by shenzhiming88** [comment]
@uBlock-user No, this breaks the page and prevents users from logging in

**Comment by uBlock-user** [comment]
How ? Clicking the login button leads users to `https://passport.csdn.net/account/login?spm=1001.2101.3001.5105`

**Comment by shenzhiming88** [comment]
> How ? Clicking the login button leads users to `https://passport.csdn.net/account/login?spm=1001.2101.3001.5105`

Fine. Thank you

**Comment by shenzhiming88** [comment]
@uBlock-user 
It doesn't look like they are going to fix
https://github.com/easylist/easylist/pull/8564#issuecomment-894186569
> We won't break logins in Annoyances,
