### ISSUE TITLE
[Anti-select] www.hongxiu.com

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#9699]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.hongxiu.com/chapter/19945470701280804/53540736566002722`

### Describe the issue

This page prevents selection, copying
Thank you

### uBlock Origin version

v1.37.0

### Browser name and version

Microsoft Edge 92.0.902.62

### Settings

No need

**Comment by shenzhiming88** [comment]
@okiehsch Hello!
It still doesn't seem to copy (either right-click menu or C-C)

**Comment by okiehsch** [comment]
Should work now
