### ISSUE TITLE
duplichecker.com

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#9701]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.duplichecker.com/`

### Describe the issue

Ads like https://github.com/uBlockOrigin/uAssets/issues/9449

### Screenshot(s)

<img width="574" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/128225239-8d63c016-4c9c-44e6-9528-a9ea411dd546.PNG">

### uBlock Origin version

1.37.2

### Browser name and version

Firefox developer

### Settings

- Enabled uBlock filters – Annoyances

**Comment by JobcenterTycoon** [comment]
Ads are back

**Comment by JobcenterTycoon** [comment]
Ads are back

**Comment by JobcenterTycoon** [comment]
this works for me

```
duplichecker.com##+js(no-xhr-if, adsbygoogle)
duplichecker.com#@#.adsbygoogle:upward(1)
```

**Comment by uBlock-user** [comment]
`duplichecker.com##.adsbygoogle:upward(1)` keeps placeholders hidden, need to add it back.

**Comment by Yuki2718** [comment]
@JobcenterTycoon Since `prevent-xhr` scriptlet is not supported on legacy AG ext, I went with classic fix: https://github.com/AdguardTeam/AdguardFilters/commit/034fabee622f799c454d9bec812b58bdb7b4be9b

**Comment by JobcenterTycoon** [comment]
Ads are back

`duplichecker.com##+js(no-xhr-if, adsense)` work or `@@||duplichecker.com^$xhr,1p`

**Comment by Yuki2718** [comment]
Used classic fix as prevent-xhr scriptlet doesn't work on legacy version.

**Comment by JobcenterTycoon** [comment]
Ads are back

**Comment by JobcenterTycoon** [comment]
Ads are back

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/commit/fce34f7a7e86dae1c691de2f1cde05c4bcc138d3
