### ISSUE TITLE
redundant filter on spel.nl

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#9703]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`spel.nl`

### Describe the issue

In `uBlock Filters` is the rule `||googlesyndication.com/pagead/show_ads.js$script,redirect=noopjs,domain=spel.nl`, because of [this issue](https://github.com/uBlockOrigin/uAssets/issues/5610)

However, I can't reproduce this anymore.

### uBlock Origin version

1.37.0

### Browser name and version

MS Edge v92

### EXTRA List enabled
- EasyList Dutch

### Default List disabled
- Peter Lowe

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/128329187-5bdb57b2-6a14-423e-8c7f-bc74d73d8d79.png)
