### ISSUE TITLE
redundant filter on modekoninginmaxima.nl

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#9705]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`modekoninginmaxima.nl`

### Describe the issue

Because of [this issue](https://github.com/uBlockOrigin/uAssets/issues/4368#issuecomment-628873080) the rule `@@*$ghide,domain=modekoninginmaxima.nl` was made. 

However, there is no more anti-adblock message if I disable this rule. 

So it could be removed.

### uBlock Origin version

1.37.0

### Browser name and version

MS Edge v92

#### Enabled
1. EasyList Dutch

#### Disabled
1. Peter Lowe

**Comment by okiehsch** [comment]
Blockadblock is still in the source of that site.

**Comment by garry-ut99** [comment]
(no AA for me with `ghide` off) Ad placeholders caused by `ghide` from "uBlock Filters":  [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218125697-0a168427-fa76-4cc2-8311-2049ccf2a5f3.png)

**Comment by JohnyP36** [comment]
@garry-ut99 if you enable the Dutch Filter list ***EasyDutch*** it should be fixed. 

https://github.com/EasyDutch-uBO/EasyDutch/commit/3b52e84ef5050954ece0c205eeaa632941b1440a

**Comment by garry-ut99** [comment]
> if you enable the Dutch Filter list **EasyDutch** it should be fixed.

I did, but EasyList Dutch refuses to update, no matter how many times I'm trying to update it, despite https://github.com/gorhill/uBlock/wiki/Advanced-settings#updateassetbypassbrowsercache set to true, I guess it finally will update sometime, maybe EasyDutch is updated every X hours on the server, anyway the filter works when added manually temporarily.

> Blockadblock is still in the source of that site.

Not anymore it seems, but I guess that maybe EasyDutch prefers to keep `ghide` in case it will be back sometime in the future.

**Comment by JohnyP36** [comment]
> > if you enable the Dutch Filter list **EasyDutch** it should be fixed.
> 
> I did, but EasyList Dutch refuses to update, no matter how many times I'm trying to update it, despite https://github.com/uBlockOrigin/uBlock-issues/wiki/Advanced-settings#updateassetbypassbrowsercache set to true, I guess it finally will update sometime, maybe EasyDutch is updated every X hours on the server, anyway the filter works when added manually temporarily.
> 
> > Blockadblock is still in the source of that site.
> 
> Not anymore it seems, but I guess that maybe EasyDutch prefers to keep `ghide` in case it will be back sometime in the future.

I'm one of the maintainers. 

Regarding the filterlist not getting updated: If you manually empty all caches and then update it, it should be fine. Otherwise you have to wait max three days.

Regarding the rule `ghide`. Next week I will take a closer look at this. 

##### Note: for issues regarding Dutch domains you can [report here](https://github.com/EasyDutch-uBO/EasyDutch/issues) as this is the standard filterlist in uBo for Dutch language/NLD.

**Comment by garry-ut99** [comment]
> Regarding the filterlist not getting updated: If you manually empty all caches and then update it, it should be fine. Otherwise you have to wait max three days.

No, 
I already cleared the cache multiple times using the both methods:
- big Clear All Cache button (clearing the cache for all lists)
- clock icon nearby the filter list (clearing the cache for a selected list)

I even:
- restarted uBO (disabled/enabled in the browser's extension pane)
- restarted the browser (Firefox)

and it still wasn't updating.

Now I have repeated all this again and still nothing for EasyDutch.
Looking at one of the EasyDutch components where the commit should have landed:
https://easydutch-ubo.github.io/EasyDutchCDN/EasyDutch/Hide_Specific.txt
there is still no commit in the file.

**Comment by garry-ut99** [comment]
Finally, after 4 hours, the CDN commit has landed, and it says now: `Last updated: Fri, 10 Feb 2023 16:00:35 +0000`
https://github.com/EasyDutch-uBO/EasyDutchCDN/tree/main/EasyDutch ==>
https://github.com/EasyDutch-uBO/EasyDutchCDN/commit/abc765aa167f7cd1254651d468b1a707a19b58ba ==> [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/218191489-37d7c41e-042b-465f-a553-fa6306a05bb0.png)

 Looking at this:
>https://github.com/community/community/discussions/19713#discussioncomment-3051461 :
> Usually it takes a few minutes but this time it took several hours for the changes to show up on my webpage. 

Either:
-  some `github.io` CDN caching delay issue
-  or it's just how the EasyDutch `github.io` site is configured, to be updated every X (4) hours intervals

**Comment by JohnyP36** [comment]
@garry-ut99 Oké. Thanks for the information. I looked it up and indeed the CDN only updates once in 4 hours.

The `Github Actions` is scheduled as follows

```
schedule:
    - cron: "00 12,20 * * *"
```

I could have manually run the workflow, but I forgot, so you had to wait. Next time I will manually run the workflow for the CDN.
