### ISSUE TITLE
Anti-adblock on looopings.nl

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#9706]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`looopings.nl`

### Describe the issue

I was checking dutch domains on anti-adblock. 

This site doesn't give an anti-adblock message, but you can see in the page source that it uses an anti-adblock script. 

I already look in the Wiki of uBlock, but I have no idea how to solve it. 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/81161435/128354934-a3ffa626-cb08-48ed-8e4d-85c19e531755.png)

### uBlock Origin version

1.37.0

### Browser name and version

MS Edge v92

### Settings

I enabled `EasyList Dutch` and disabled `Peter Lowe`

**Comment by okiehsch** [comment]
The site checks if `https://www.looopings.nl/ad-blocker.js` is blocked or not.
The reason you dont see an anti adblock message is that no filter blocks that request. 😁 
Add 
` ||looopings.nl/ad-blocker.js`
if you want to see the anti adblock message.

**Comment by okiehsch** [comment]
After adding that filter you have to reload the site bypassing the cache one time to get the anti adblock message.
![image](https://user-images.githubusercontent.com/16838044/128357032-24a37f68-8749-4120-894e-042882380dec.png)

**Comment by JohnyP36** [comment]
Thank you! thank very much. 
I'm sorry for your time. It was so easy.
