### ISSUE TITLE
Change filter for quickclaims.nl

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#9713]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`quickclaims.nl`

### Describe the issue

In the `uBlock Filters` is a filter, namely: `@@*$ghide,domain=quickclaims.nl`

As in the [wiki](https://github.com/gorhill/uBlock/wiki/Resources-Library#nobabjs-) it says: 
>nobab.js /
bab-defuser.js ↪
Defuses BlockAdblock. Prevents executing of *`eval()`* on sets of predefined payloads.  

And as you can see in the screenshot `eval()` is in the source code of this site. 

I guess, it's better to use `quickclaims.nl##+js(nobab)` 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/81161435/128464329-5dfe2fe5-9a69-4ead-b156-d891ffce6367.png)
![image](https://user-images.githubusercontent.com/81161435/128464370-68da5c64-a918-4abc-9ea9-2d7b26568065.png)

### uBlock Origin version

1.37.0

### Browser name and version

MS Edge v92

### Enabled 
- EasyList Dutch
- Adguard Base

### Disabled
- Peter Lowe
- Online Malicious URL...

**Comment by uBlock-user** [comment]
> If not could you explain why?

https://github.com/AdguardTeam/Scriptlets/issues/21

**Comment by JohnyP36** [comment]
@uBlock-user 
I search for the difference between `@@*$ghide,domain=example.com` and `@@||example.com^$ghide`.  
 But I really don't get it.

**Comment by okiehsch** [comment]
The difference is that if you want to add two ghide to more than one domain in one filter you have to use `@@*$ghide,domain`-
` @@*$ghide,domain=example.com|example1.com`

With `@@||example.com^$ghide` that does not work.

**Comment by krystian3w** [comment]
Also diffrent is:

`||example.com^$all`
vs
`$all,domain=example.com`

first don't block thrid-party resource on pages, but second better block malware pages if user omit strict block pop-up.
