### ISSUE TITLE
Redundant filter on girlscene.nl

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#9714]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`girlscene.nl`

### Describe the issue

In `uBlock Filters` is the following rule: 
```
! https://github.com/uBlockOrigin/uAssets/issues/8888
girlscene.nl##.ad-container
||mmcdn.nl^$3p
```

Those rules only hide the anti-adblock message. 
So instead of those 2 rules  
it's better to use `girlscene.nl##+js(set, adblock, undefined)`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/81161435/128467887-fb8d0015-e88f-4881-b28f-b9599e025d6e.png)

### uBlock Origin version

1.37.0

### Browser name and version

MS Edge v92

### Disabled
- Peter Lowe
- Malicious URL Tracking

### Enabled
- EasyList Dutch

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/af4d0d156260672dce4714b150ae6ace5af8c54a
