### ISSUE TITLE
Anti-adblock spele.nl

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uAssets#9715]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://spele.nl/spel/lingo/`

### Describe the issue

Anti-adblock banners right and under game

### Screenshot(s)

![afbeelding](https://user-images.githubusercontent.com/80090789/128482995-7b670ffd-b068-477b-a2f0-2fd1229a9ce2.png)

### uBlock Origin version

1.37.2

### Browser name and version

FireFox 91

### Settings

- EasyDutch

### Notes

`||improvedigital.com/*/headerlift.min.js$script,redirect-rule=noop.js,domain=spele.nl` isn't working
The only solution I found is allowing the request.

**Comment by BPower0036** [comment]
I'm sorry but the redirecting `*$script,redirect-rule=noopjs,domain=spele.nl` didn't solve it 
and `spele.nl##.is-skyscraper`, `spele.nl##.is-billboard` only hides the message. 
You can still see the messages if you disable cometic filtering.

**Comment by okiehsch** [comment]
> You can still see the messages if you disable cometic filtering.

Well, why do you disable cosmetic filtering.
I don't understand, what's your issue?

**Comment by BPower0036** [comment]
@okiehsch that `*$script,redirect-rule=noopjs,domain=spele.nl` doesn't do a thing, so it is useless.

**Comment by okiehsch** [comment]
Well, ok but that's not what I was replying to.

@uBlock-user

**Comment by uBlock-user** [comment]
> *$script,redirect-rule=noopjs,domain=spele.nl 

I don't see banners  when that filter is added, so it's not useless as you say.

Placeholders are still present, for which cosmetic filters were added.

**Comment by okiehsch** [comment]
@BPower0036 the redirection was added to the annoyance list, do you have that enabled?

**Comment by uBlock-user** [comment]
With the redirection filter --

![Capture](https://user-images.githubusercontent.com/21290713/128497423-8a606247-ff46-4c2f-be4b-86f3e5fa2772.PNG)

So, working as expected.

**Comment by uBlock-user** [comment]
> You can still see the messages

Test on default settings/lists with all other extensions disabled.

**Comment by BPower0036** [comment]
@okiehsch @uBlock-user did test it on default settings/lists + uBO Annoyances list enabled, but you can still it (if disabling cosmetic filtering) after 30 sec. So after waiting 30 sec. I see it again

**Comment by uBlock-user** [comment]
> but you can still it (if disabling cosmetic filtering) after 30 sec. So after waiting 30 sec. I see it again

Waited 2 full minutes and still nothing, @okiehsch can you reproduce this way ?

**Comment by okiehsch** [comment]
Yes.

**Comment by uBlock-user** [comment]
on Firefox or Chrome ?

**Comment by okiehsch** [comment]
Chromium, I am still testing a possible fix, it's a pain to debug.

**Comment by okiehsch** [comment]
@BPower0036 does
`spele.nl##+js(nostif, HeaderLift)`
work for you?

**Comment by uBlock-user** [comment]
@okiehsch `nostif, /^/` or `nosiif, /^/` doesn't work, atleast on Firefox.

**Comment by uBlock-user** [comment]
`spele.nl##+js(aeld, error)` works fine @BPower0036 try that too

**Comment by okiehsch** [comment]
`spele.nl##+js(nostif, HeaderLift)`
works for me using Firefox.

**Comment by okiehsch** [comment]
The problem I have that the redirection causes the game to load after 30 seconds as well, if I remove the redirection the game starts instantly.

**Comment by uBlock-user** [comment]
`spele.nl##+js(aeld, error)` works fine on both Firefox and Chrome.

**Comment by okiehsch** [comment]
The game loads instantly for you?

That's what I am seeing for 30 seconds.
![image](https://user-images.githubusercontent.com/16838044/128501516-4025499e-576f-4b29-9e07-cef7b808b402.png)

After 30 seconds
![image](https://user-images.githubusercontent.com/16838044/128501633-b06b365d-a8ef-4cfe-9cf8-8b763f8ab9a4.png)


`spele.nl##+js(aeld, error)`
does not work for me.
![image](https://user-images.githubusercontent.com/16838044/128501792-6c811b19-47d5-4513-b8c5-34e0330152c8.png)

**Comment by okiehsch** [comment]
How about we remove the redirection and simply hide the anti adblock message.
That works for everybody.

**Comment by uBlock-user** [comment]
> The game loads instantly for you?

Didn't look for that, but I have removed the redirection because of this.

**Comment by uBlock-user** [comment]
@okiehsch https://github.com/uBlockOrigin/uAssets/commit/0ec836479ef339089a5e24f2ea872a8a6fd1c6ec
