### ISSUE TITLE
Anti-adblock lovetheboxx.be

### ISSUE THREAD

**Issue by BPower0036** [uBlockOrigin/uAssets#9733]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://lovetheboxx.be/`

### Describe the issue

Anti-Adblock message

### Screenshot(s)

![afbeelding](https://user-images.githubusercontent.com/80090789/128704457-5f878370-f043-4db8-8d82-20131013ff91.png)

### uBlock Origin version

1.37.2

### Browser name and version

FireFox 90.

### Settings

EasyDutch

**Comment by uBlock-user** [comment]
Parked domain, site is dead.

You can add `/px.gif?$image,redirect-rule=1x1.gif` to defuse the anti-adblock.
