### ISSUE TITLE
Multiple errors on `rtl.be`

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#9734]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`rtl.be`

##### example
`https://www.rtl.be/info/belgique/societe/peut-on-deja-mesurer-les-effets-du-rechauffement-climatique-en-belgique--1317715.aspx`

### Describe the issue

I couldn't play the video and below the article there is an empty space in which normally articles are shown, but I don't see them. 

I disabled `My Filters` and enabled `uBlock Unbreak` but the site is still not working properly. 

Only after I had disabled uBlock I could play the video and see the articles below the main article.

### Screenshot(s)

Couldn't play video
![image](https://user-images.githubusercontent.com/81161435/128705578-c2306771-7b07-4cec-b18c-839f6d9dbab5.png)

Don't see other articles 
![image](https://user-images.githubusercontent.com/81161435/128705731-5e480606-0e17-408d-a999-8173366b8762.png)

After disabling uBlock
![image](https://user-images.githubusercontent.com/81161435/128705902-14d97311-ed17-441f-868f-8b45ad6bb108.png)

### uBlock Origin version

1.37.0

### Browser name and version

MS Edge v92

### Settings

![image](https://user-images.githubusercontent.com/81161435/128706567-3834754b-b094-4173-a87c-67ed02580d20.png)

**Comment by okiehsch** [comment]
The video plays fine on my end.

> Don't see other articles

You mean the articles in the "publicité"  section?

**Comment by JohnyP36** [comment]
> > Don't see other articles
> 
> You mean the articles in the "publicité" section?

Yeah, I don't see the articles in the "publicité" section.

The video not playing was my fault.

**Comment by okiehsch** [comment]
Well, your french is certainly much better than mine but "publicité" means advertisement and those articles are links to third-party sites via outbrain, they are clearly adverts.

**Comment by JohnyP36** [comment]
@okiehsch oke I see. 
Thanks
