### ISSUE TITLE
pilot.wp.pl

### ISSUE THREAD

**Issue by hawkeye116477** [uBlockOrigin/uAssets#974]
### URL(s) where the issue occurs

https://pilot.wp.pl/tv

### Describe the issue

Go to the website and choose some channel in the right, for example TV4 and antyadblock message appears „Please turn off Adblock/uBlock" („Prosimy, wyłącz Adblock/uBlock")

### Screenshot(s)

![screenshot_20171212_103627](https://user-images.githubusercontent.com/19818572/33877341-5d93e7e0-df28-11e7-8cd6-28270ca4e22a.png)

### Versions

- Browser/version: Waterfox 56.0/Firefox 56.0.2
- uBlock Origin version: 1.14.20

### Settings

- https://gist.githubusercontent.com/hawkeye116477/32fb4ffe0e43b8295282662485cfec18/raw/d7f93000d57c2449e9de2e878c382aa29f1e7a54/uBlockOrigin_settings

**Comment by mapx-** [comment]
```
@@||pagead2.googlesyndication.com^$script,domain=pilot.wp.pl
@@||wp.hit.gemius.pl/gplayer.js$script,domain=pilot.wp.pl
||wp.hit.gemius.pl/gdejs/xgde.js$script,redirect=noopjs,domain=pilot.wp.pl
```

**Comment by hawkeye116477** [comment]
@mapx- Thanks, works correct.

**Comment by mapx-** [comment]
Let's see if @gorhill or @okiehsch will find something better ..

**Comment by gorhill** [comment]
I created a scriptlet to allow for a getter to return a specific value. Example:

    pilot.wp.pl##script:inject(getter-value.js, PWA_adbd, 0, number)

This fixes the case here, and the scriptlet is generic enough to quite probably be useful many other places.

Currently only accept bool, number and string values.

Any reason why I should not ship this scriptlet? Trying to figure how it could be misused.

**Comment by jspenguin2017** [comment]
I wouldn't allow a string, that's just too powerful.

**Comment by gorhill** [comment]
@jspenguin2017 Can you elaborate what you have in mind?

**Comment by jspenguin2017** [comment]
Like a website save a string as HTML template, or save messages in global variables, etc. 
This is my implementation, it's even more restrictive. I'm worried `Infinity` can mess with stuff. 
https://github.com/NanoAdblocker/NanoFilters/blob/42b2b0054b65f938f4b0e8a8f1b702510335cb30/NanoFilters/NanoResources.txt#L157

**Comment by KiLL4FuNK** [comment]
Anti-Adblock @mapx-

**Comment by mapx-** [comment]
report at polish list, https://github.com/MajkiIT/polish-ads-filter/issues
@MajkiIT
