### ISSUE TITLE
sidereel.com

### ISSUE THREAD

**Issue by zero77** [uBlockOrigin/uAssets#975]
Delayed pop-up entitled `With SideReel you can`

https://www.sidereel.com or any page

**Comment by mapx-** [comment]
annoyance
try
`||cloudfront.net/assets/widget_common/lib/jqModal$script,domain=sidereel.com`

to be reported to easylist authors

@ryanbr @monzta

**Comment by zero77** [comment]
It doesnt seam to work on this page. https://www.sidereel.com/calendar

**Comment by mapx-** [comment]
what about
```
sidereel.com##.reveal-modal-bg
sidereel.com###sign-up-prompt
```

**Comment by zero77** [comment]
Yes, that looks like its working so far, thank you.
