### ISSUE TITLE
roboxfilme4k.com ads

### ISSUE THREAD

**Issue by andreewmat** [uBlockOrigin/uAssets#9751]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://roboxfilme4k.com/emperor-2022-watch-movies-online-subtitled-hd`

### Describe the issue

I see ads on this website. And on the "Server 1" I can't see play it because of the pop-up. 

### Screenshot(s)

![screen](https://user-images.githubusercontent.com/79897301/129242153-1366762c-4d23-49e0-a044-b0588cbf946c.jpg)
![screen01](https://user-images.githubusercontent.com/79897301/129242156-bcdc9f80-f9ef-4ce9-afdb-d0caa922788d.jpg)
![screen02](https://user-images.githubusercontent.com/79897301/129242160-47cd8466-50c8-4f44-bb14-1a3a0eb6088a.jpg)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91

### Settings

Default lists

**Comment by uBlock-user** [comment]
`roboxfilme4k.com##a[href^="https://www.udont2021.com/"]` blocks ads, that page doesn't have any player embedded on Server 1 or Server 2, other movies/tv shows do, anyways report these ads to https://github.com/tcptomato/ROad-Block/issues
