### ISSUE TITLE
wenku.baidu.com paywall

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#9753]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://wenku.baidu.com/view/e3cdcc0f900ef12d2af90242a8956bec0875a510.html`

### Describe the issue

When you click on "Continue Reading(`继续阅读`)", you will be redirected to another page to promote your own membership.

### Screenshot(s)

![2021-08-13_10-56-53](https://user-images.githubusercontent.com/66902050/129298710-bd2ad77d-e6a9-46db-9da8-28b6fda45e8d.gif)

### uBlock Origin version

v1.37.0

### Browser name and version

Microsoft Edge 92.0.902.62

### Settings

_No need_

**Comment by uBlock-user** [comment]
We don't fix paywalls.
