### ISSUE TITLE
Can't load ygosu.com images when uBlock Origin is enabled.

### ISSUE THREAD

**Issue by blocky9** [uBlockOrigin/uAssets#9754]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://ygosu.com/community/best_article/yeobgi/1846024/?type=daily&sdate=2021-08-13&frombest=Y`

### Describe the issue

Can't load ygosu.com images when uBlock Origin is enabled.
I think uBlock Origin blocks content images.

### When uBlock Origin is not enabled
![image](https://user-images.githubusercontent.com/86645381/129341937-a982ab45-36d7-4b42-afd2-895e3b1f77e1.png)

### When uBlock Origin is enabled
![image](https://user-images.githubusercontent.com/86645381/129341996-69ab731c-f14c-45d4-a47b-7b26d361f170.png)

### Screenshot(s)

https://user-images.githubusercontent.com/86645381/129341937-a982ab45-36d7-4b42-afd2-895e3b1f77e1.png
https://user-images.githubusercontent.com/86645381/129341996-69ab731c-f14c-45d4-a47b-7b26d361f170.png

### uBlock Origin version

1.35.2

### Browser name and version

Chrome latest

### Settings

Nothing

**Comment by uBlock-user** [comment]
Due to anti-adblock detection, fix appended.
