### ISSUE TITLE
Anti-adblock on fok.nl

### ISSUE THREAD

**Issue by JohnyP36** [uBlockOrigin/uAssets#9755]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`forum.fok.nl`  
[`example`](https://forum.fok.nl/topic/2617721)

### Describe the issue

In uBo filters is an anti-adblock rule `fok.nl##+js(aeld, , DAB)`  
I looked into the `view-source` of forum.fok and saw that it must be a correct rule.  <br> 
Since I'm also using EasyList Dutch - **so this issue does not occur when only enabling the default list** - and in their list they block `#advertentie` I see an anti-adblock warning.  

Is their an solution or do I have to make an `#@#`-rule for `#advertentie` on `fok.nl`?

### Screenshot(s)

![image](https://user-images.githubusercontent.com/81161435/129344570-7aa2f4e8-21f8-4cc0-98bd-9f8d9596a61b.png)

### uBlock Origin version

1.37.0

### Browser name and version

MS Edge v92

### Settings

Enabled  `EasyList Dutch`

**Comment by okiehsch** [comment]
I am not sure I understand what you are asking.

> Is their an solution or do I have to make an #@#-rule for #advertentie on fok.nl?

`EasyList Dutch` already includes that rule.
![image](https://user-images.githubusercontent.com/16838044/129351562-8bee0150-b6d1-4ff7-9b39-59306f8c618d.png)

**Comment by JohnyP36** [comment]
I mean that I think the only solution is an `#@#`-rule. 
But as I see something must have gone wrong on my end.
