### ISSUE TITLE
anti adblock on taroot-rangi.com

### ISSUE THREAD

**Issue by nimasaj** [uBlockOrigin/uAssets#976]
### URL(s) where the issue occurs

`http://www.taroot-rangi.com/`

### Describe the issue

Ads appear after few seconds at the end of the page. Coming from inline script.

### Screenshot(s)

`https://imgur.com/a/e8Qlc`

### Versions

- Browser/version: Google Chrome 63.0.3239.84 (Official Build) (64-bit)
- uBlock Origin version: v1.14.20

**Comment by okiehsch** [comment]
I can't read farsi, so even though this fix should not break anything, some feedback would be appreciated.

**Comment by nimasaj** [comment]
@okiehsch , It's working properly. Thanks
