### ISSUE TITLE
Adblock https://expertvn.com/

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#9760]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://expertvn.com/wordpress-ra-mat-phien-ban-quan-ly-tren-mac-chua-co-thong-tin-cho-windows.html#2TFCl`
(from `http://megaurl.in/2TFCl`)

`https://downfile.site/huong-dan-responsive-facebook-comment-bang-css.html`
(From `http://megafly.in/zC4D` )

### Describe the issue

the anti adblock detect ublock

### uBlock Origin version

Ublock Lastest

### Browser name and version

Chrome lastest

### Settings

-

**Comment by dumbusernameidk** [comment]
`http://megaurl.in/zILN`

redirects > `trangchu.news` has anti-right click and cannot use console.

**Comment by stephenhawk8054** [comment]
> `http://megaurl.in/zILN`
> 
> redirects > `trangchu.news` has anti-right click and cannot use console.

Fixed. Enable `uBlock filters – Annoyances` and force update the filter lists in about 10 minutes.
