### ISSUE TITLE
ui.memoryhackers.org

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#9761]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://ui.memoryhackers.org/game/pubg-mobile`

### Describe the issue

Can't load the cheat if ublock on.
maybe you need the app to check it (maybe)

here if you want to test it with app https://raw.githubusercontent.com/YKSLFF/Download/master/XFProject.zip
password mh

### uBlock Origin version

Ublock Lastest

### Browser name and version

Chrome lastest

### Settings

=

**Comment by uBlock-user** [comment]
`YÜKLE` button doesn't do anything even if uBO is disabled(both in Chrome and Firefox), seems site is broken.

**Comment by Dhanamerdeka** [comment]
i don't know what you mean with YÜKLE because i change language to english
first you must have the app
and then click load on the sites

if without ublock, after load button there's appear some popup loading that connected to the app and then loaded the cheat
if we using ublock, nothing will came out when we click that button

btw the change language is on bottom left of your screen
change it to english

**Comment by uBlock-user** [comment]
>  first you must have the app

Never had to use app the before, but not going to install the app  -- https://www.virustotal.com/gui/file/bfdef92424cfb649efb47d168dcffd3c54f77accf8e50b50e74dc770a241ed43/detection

YUKLE = LOAD in English

**Comment by uBlock-user** [comment]
@Dhanamerdeka add 

```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=memoryhackers.org
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl$script,domain=memoryhackers.org
```

and test

**Comment by Dhanamerdeka** [comment]
> > first you must have the app
> 
> Never had to use app the before, but not going to install the app -- https://www.virustotal.com/gui/file/bfdef92424cfb649efb47d168dcffd3c54f77accf8e50b50e74dc770a241ed43/detection
> 
> YUKLE = LOAD in English

yeah the app detected as trojan.... well i use it along time ago and now i came back and still works like before...

btw thanks i done do that. and the sites works now...
i think this is enough :) thanks
