### ISSUE TITLE
Can't watch videos on sky.it

### ISSUE THREAD

**Issue by Mons1990** [uBlockOrigin/uAssets#9763]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://video.sky.it/`

### Describe the issue

It's a video streaming website. I can't see the buttons to start playing video with uBlock Origin enabled. The problem seems related with the "uBlock filters – Unbreak" list, because if i de-activate it I can use the website flawlessly.

### uBlock Origin version

1.37.0

### Browser name and version

Microsoft Edge 92.0.902.73

### Settings

None

### Notes

Thank you everyone for your work

**Comment by uBlock-user** [comment]
Videos play as expected

<details>

![Capture](https://user-images.githubusercontent.com/21290713/129475804-84e386c2-26af-4c91-9627-a851a012fe2d.PNG)

</details>

Reset to default settings + disable all other extensions + disable Edge's built-in blocker.

**Comment by okiehsch** [comment]
I can reproduce, example link
`https://video.sky.it/news/mondo/video/kabul-levacuazione-degli-italiani-video-esclusivo-688998`

**Comment by uBlock-user** [comment]
Seems specific to Chrome, don't see it on Firefox.

**Comment by okiehsch** [comment]
Yes, the video works fine with Firefox for me.
