### ISSUE TITLE
pluto.tv: ads

### ISSUE THREAD

**Issue by cglong** [uBlockOrigin/uAssets#9764]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://pluto.tv/en/on-demand/movies/the-matrix-1991-1-1`

### Describe the issue

When watching the video, ads are injected into the stream and (usually) disable pause/fast-forward controls. They appear to be added after the video starts (because the total runtime increases shortly after loading and is variable depending on where the video starts playing).

### Screenshot(s)

https://user-images.githubusercontent.com/137214/129507295-46ba0d57-bca3-4dae-9831-5e0a435a9b63.png

### uBlock Origin version

1.37.2

### Browser name and version

Chrome 92.0.4515.131

### Settings

None

**Comment by uBlock-user** [comment]
We can block the ads, but the video will not begin playing untill the ads are stitched inside the video

**Comment by uBlock-user** [comment]
Should be fixed with AdGuard's `$replace` -- https://github.com/AdguardTeam/AdguardFilters/commit/c17ecc5487f0fed29be96eefb8d1ba6c0db2da6e

**Comment by uBlock-user** [comment]
Closing for https://github.com/uBlockOrigin/uAssets/issues/1905#issuecomment-899302051

**Comment by cglong** [comment]
Great, thank you for the fast and thorough investigation @uBlock-user! 🙂

**Comment by krystian3w** [comment]
@[mapx-](https://github.com/mapx-) mapx- added the[ SSAI ](https://github.com/uBlockOrigin/uAssets/labels/SSAI)label [on 7 Apr 2018](https://github.com/uBlockOrigin/uAssets/issues/1905#event-1562292997)
@[jspenguin2017](https://github.com/jspenguin2017) [jspenguin2017](https://github.com/jspenguin2017) mentioned this issue on 9 May 2018
[Ads] cwtv.com NanoAdblocker/NanoFilters#25
Closed
@jspenguin2017 jspenguin2017 mentioned this issue on 3 Jun 2018
nbc.com #2409
Closed
@[okiehsch](https://github.com/okiehsch) okiehsch changed the title Cwtv video ads Websites using SSAI (server side ad injection) [on 3 Jun 2018](https://github.com/uBlockOrigin/uAssets/issues/1905#event-1659832690)
This was referenced on 3 Jun 2018
Viceland Video Ads #1541
Closed
uBO on Chrome not blocking fox.com #772
Closed
abc7.com #794
Closed
@[jspenguin2017](https://github.com/jspenguin2017) jspenguin2017 mentioned this issue on 22 Jul 2018
[Anti-adblock] investigationdiscovery.com #2966
Closed
@[SkeletalDemise](https://github.com/SkeletalDemise) SkeletalDemise mentioned this issue on 22 Jul 2018
anti Adblocker on discovery.com sciencechannel.com #2931
Closed
@[terrorist96](https://github.com/terrorist96) terrorist96 mentioned this issue on 2 Sep 2018
Ads Loading gorhill/uBO-Extra#76
Closed
@[jspenguin2017](https://github.com/jspenguin2017) jspenguin2017 mentioned this issue on 15 Sep 2018
Ads while watching shows on FOX #3486
Closed
@[uBlock-user](https://github.com/uBlock-user) uBlock-user mentioned this issue on 27 Oct 2018
Midroll Ads Aren't being blocked CityTV.com #3847
Closed
@[mapx-](https://github.com/mapx-) mapx- mentioned this issue on 17 Nov 2018
rediff.com | Tracking #4138
Closed
@[terrorist96](https://github.com/terrorist96) terrorist96 mentioned this issue on 23 Nov 2018
Fails to Block Ads on The CW - http://thecwtv.com #4179
Closed
@[stoically](https://github.com/stoically) stoically mentioned this issue on 20 Mar 2019
ALL twitch.tv issues #5184
Open
@[okiehsch](https://github.com/okiehsch) okiehsch mentioned this issue on 11 Jun 2019
https://www.brighteon.com/ #5803
Closed
@[llacb47](https://github.com/llacb47) llacb47 mentioned this issue on 17 Jun 2019
discovery.com videos not working easylist/easylist#3636
Closed
@https://github.com/uBlockOrigin uBlockOrigin deleted a comment from [prateekrastogi](https://github.com/prateekrastogi) [on 26 Jan 2020](https://github.com/uBlockOrigin/uAssets/issues/1905#event-2979959103)
@[uBlock-user](https://github.com/uBlock-user) uBlock-user added the[ can't fix ](https://github.com/uBlockOrigin/uAssets/labels/can%27t%20fix)label [on 17 Jun 2020](https://github.com/uBlockOrigin/uAssets/issues/1905#event-3453347081)
@[nebchan](https://github.com/nebchan) nebchan mentioned this issue on 29 Sep 2020
Twitch TV now injecting ads #7968
Closed
@[llacb47](https://github.com/llacb47) llacb47 mentioned this issue on 1 Nov 2020
Add queryprune filters to deal with SSAI #8131
Merged
@[uBlock-user](https://github.com/uBlock-user) uBlock-user mentioned this issue on 16 Aug 2021
pluto.tv: Ads not being blocked #9764
Closed
6 tasks
@[subby2006](https://github.com/subby2006) subby2006 mentioned this issue on 1 Sep 2021
sbs.com.au ondemand has a new player and it detects ublock #7836
Closed
[uBlock-user](https://github.com/uBlock-user) added a commit that referenced this issue on 20 Jan
@uBlock-user
[update](https://github.com/uBlockOrigin/uAssets/commit/eb9148f1e001b8862c044b8884a27c09a607fe1a) https://github.com/uBlockOrigin/uAssets/issues/1905#issuecomment-394129540
[eb9148f](https://github.com/uBlockOrigin/uAssets/commit/eb9148f1e001b8862c044b8884a27c09a607fe1a)
This was referenced on 21 Jan
go.tlc.com: ads #11419
Closed
go.discovery.com: ads #11420
Closed
@[uBlock-user](https://github.com/uBlock-user) uBlock-user closed this as [completed](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/uBlockOrigin/uAssets/commit/ac8860312f726292bd3e7c2f34a82f6d20614dbe [on 9 Feb](https://github.com/uBlockOrigin/uAssets/issues/1905#event-6035560189)
@[uBlock-user](https://github.com/uBlock-user) uBlock-user reopened this [on 9 Feb](https://github.com/uBlockOrigin/uAssets/issues/1905#event-6035564682)
[uBlock-user](https://github.com/uBlock-user) added a commit that referenced this issue on 9 Feb
@uBlock-user
[append](https://github.com/uBlockOrigin/uAssets/commit/fe89b1b850dc070f09914e36b5520e955a5ad3a6) https://github.com/uBlockOrigin/uAssets/issues/1905#issuecomment-1033865488
[fe89b1b](https://github.com/uBlockOrigin/uAssets/commit/fe89b1b850dc070f09914e36b5520e955a5ad3a6)
@[uBlock-user](https://github.com/uBlock-user) uBlock-user mentioned this issue on 17 Feb
discovery plus italy showing ads #11772
Closed
6 tasks
@https://github.com/uBlockOrigin uBlockOrigin deleted a comment [on 9 Mar](https://github.com/uBlockOrigin/uAssets/issues/1905#event-6207603084)
@[mapx-](https://github.com/mapx-) mapx- mentioned this issue on 25 Mar
hulu.com: ads #12407
Closed
8 tasks
This was referenced on 27 Mar
philo.com: ads #12469
Closed
player.stv.tv: ads #12513
Closed
@[stephenhawk8054](https://github.com/stephenhawk8054) stephenhawk8054 mentioned this issue on 4 Apr
mech-plus.com: ads #12589
Closed
8 tasks
@[stephenhawk8054](https://github.com/stephenhawk8054) stephenhawk8054 mentioned this issue on 4 May
amc.com: ads #13065
Closed
8 tasks
This was referenced on 4 Jul
primevideo.com: ads #13906
Closed
animalplanet.com: ads #13969
Closed
tvbanywherena.com: video ads #13978
Closed
This was referenced 23 days ago
vix.com: ads #14213
Closed
discoveryplus.com: ads #10870
Closed
discoveryplus.com: ads #14365
Closed
@[mapx-](https://github.com/mapx-) mapx- mentioned this issue 6 days ago
go.tlc.com: ads #14451
Closed
8 tasks
@[MasterKia](https://github.com/MasterKia) MasterKia mentioned this issue 5 days ago
primevideo.com: ads #14512

**Comment by mapx-** [comment]
on live is broken

`https://pluto.tv/en/live-tv/il-mio-amico-arnold`

`@@||imasdk.googleapis.com/pal/sdkloader/pal.js$script,domain=pluto.tv`

**Comment by mapx-** [comment]
@cdanapol a on-demand example where you get ads ?

**Comment by cdanapol** [comment]
How do you do that in the app?

**Comment by cdanapol** [comment]
It did not work.

**Comment by mapx-** [comment]
> It did not work.

- still ads or what ?
- reset uBO to default, update all filter lists, disable other blocking extensions

**Comment by cdanapol** [comment]
There is still ads

**Comment by cdanapol** [comment]
What do I turn on?
![image](https://github.com/uBlockOrigin/uAssets/assets/71908016/0641eba6-f418-4f3d-b464-1c7a8f45e6ad)

**Comment by cdanapol** [comment]
?

**Comment by mapx-** [comment]
I cannot reproduce any (video)ad.

I told you above what to try:
**reset uBO to default, update all filter lists, disable other blocking extensions**

**Comment by cdanapol** [comment]
how do u  update all filter lists

**Comment by mapx-** [comment]
go into uBO dashboard, `filter lists` tab:

Click the ["Purge all caches"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches) button while holding the 'Shift' key, then click the ["Update now"](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) button

**Comment by cdanapol** [comment]
![image](https://github.com/uBlockOrigin/uAssets/assets/71908016/4b66900b-f13b-4155-813a-8bbcfb4e53a3)
black screen now

**Comment by cdanapol** [comment]
it worked

**Comment by cdanapol** [comment]
Can you do a mobile device the on the web browser?

**Comment by mapx-** [comment]
Test only in firefox mobile.

**Comment by cdanapol** [comment]
How do you get uBlockOrigin mobile

**Comment by cdanapol** [comment]
Do you need to do the steps every time?

**Comment by mapx-** [comment]
- search in google for ublock origin android and install it in FF mobile
- do those steps when install / reset uBO and do not add 777 other extensions

**Comment by cdanapol** [comment]
It only worked on time.

**Comment by cdanapol** [comment]
Running to reset the page. to

**Comment by cdanapol** [comment]
?

**Comment by Residentcl** [comment]
Will it be possible to see this advertising and block it?
https://pluto.tv/es/on-demand/series/rutas-mortales-2/episode/tumba-helada-2015-9-2-ptv3

![pluto](https://github.com/uBlockOrigin/uAssets/assets/1659401/7ae15086-e112-44f5-ac6f-7a68b8fedaad)

**Comment by mapx-** [comment]
I'm able to see that episode using a chilean ip, but ... where are the (video)ads ? I tried at 35:00 , other random positions.

**Comment by Residentcl** [comment]
It leaves every x time, I think it's every 15 minutes on average...

**Comment by mapx-** [comment]
What country are you watching the movie from?

**Comment by Residentcl** [comment]
Chile.

**Comment by krystian3w** [comment]
Or "Polsza Premium" based on TikTok community by Ukrainan/Russian people on that platform.

🇨🇱 ≈ 🇵🇱

**Comment by mapx-** [comment]
Still cannot reproduce ads.

**Comment by Residentcl** [comment]
@mapx- Any way I can help?

**Comment by Residentcl** [comment]
Can I open another report from this page?

**Comment by mapx-** [comment]
You can continue here.

**Comment by Residentcl** [comment]
Will it be possible to reopen this case?

**Comment by krystian3w** [comment]
Technically it is possible, rather github did not bug to make this issue have a corrupt "reopen" action.

**Comment by Residentcl** [comment]
In that case someone with permission should do it.

**Comment by krystian3w** [comment]
Yep, only users with premissions to moderate issues due uBlock-user closed in 2021 instead by wait for [cglong](https://github.com/cglong).

**Comment by stephenhawk8054** [comment]
A bit information is pluto ads can appear sporadically (not every refresh has ads) and the ads often occur in the middle of the video.

But currently `xml-prune` does not quite work yet (or at least last time I checked) I don't know why: https://github.com/uBlockOrigin/uBlock-discussions/discussions/792#discussioncomment-6536598

**Comment by mapx-** [comment]
- it needs spanish ip
- I added:

`pluto.tv##+js(xml-prune, xpath(//*[name()="Period"][.//*[name()="BaseURL" and contains(text()\,'_ad')]]), ,.mpd, log, 1)`

I'm not sure if matches or not, I get an error in console (executing the scriptlet):

![image](https://github.com/uBlockOrigin/uAssets/assets/10303732/96d515ca-5e77-482b-9e62-348fb12ddcbf)

@gorhill

**Comment by gorhill** [comment]
That is a site error, it tries to fetch using an invalid URL, `"https://undefined/infinity/session/start?sessionRoot=undefined&sessionId=undefined&accountCode=plutotvdev&timemark=1698258644915"`, the scriptlet just delegates to the browser at that point, and the browser throws because of the invalid URL.

**Comment by gorhill** [comment]
If you ignore the errors from the site, I do see the scriptlet doing stuff as per console:

![image](https://github.com/uBlockOrigin/uAssets/assets/585534/41be3448-12e9-4d8f-9c95-fa612a5f7d70)

**Comment by mapx-** [comment]
> If you ignore the errors from the site

What should I do ?

**Comment by stephenhawk8054** [comment]
@mapx- If I'm not mistaken, the scriptlet can log elements removed successfully but the ads will still be there when navigating to the ads timer. I'm not sure how it behaves now, you can check it again.

**Comment by mapx-** [comment]
I see in console 
```
[uBO] xmlPrune: removing 3 items
[uBO] xmlPrune: Element.Period removed
```
but ... still an ad sequence after some minutes

**Comment by stephenhawk8054** [comment]
@mapx- If you remove the whole `Period` sections, do the video still play on your side? Mine was still playing normally.

**Comment by mapx-** [comment]
mmhmm, meaning there is another way the ads slips in ?

**Comment by stephenhawk8054** [comment]
Yeah, that's what I was stuck with this case. Not sure if there's something else happening or the .mpd response is cached/cloned somewhere.

**Comment by mapx-** [comment]
or simply is all stitched in - not controlled by m3u8 / mpd ways

**Comment by mapx-** [comment]
`Rather than dynamic ad calls triggered by the ad breaks on a consumer’s device, SSAI stitches together the entire video stream with ads before the consumer sees it, so there’s pretty much no ad-serving flexibility throughout an on-demand stream.` 

`https://www.adexchanger.com/ctv-roundup/pluto-tvs-ad-insertion-tech-has-a-frequency-problem/`

**Comment by mapx-** [comment]
However, if I add

`pluto.tv##+js(no-xhr-if, /_Ad_|_ad/)`

I see that message (you cannot stop the stream during the ads) but the real video is running

**Comment by mapx-** [comment]
@DefconTwo

test:

```
pluto.tv##+js(xml-prune, xpath(//*[name()="Period"][.//*[name()="BaseURL" and (contains(text()\,'_ad') or contains(text()\,'_Ad_'))]]), ,.mpd)
pluto.tv##+js(no-xhr-if, /_Ad_|_ad/)
```

**Comment by DefconTwo** [comment]
yeah .. same problem , the controls is bugged but no ads

**Comment by Residentcl** [comment]
Hi. any update on video advertising?

**Comment by stephenhawk8054** [comment]
@Residentcl Can you give exact links where you see the issue, and at which time did you see the ads? Also which country are you when accessing the site?

**Comment by Residentcl** [comment]
[](https://pluto.tv/latam/on-demand/series/65f471e8ea323e0013229abc/episode/65f471fcea323e0013229f92?lang=en)
every 10 minutes on average.
From: Chile.
I'll make a more detailed report on this tomorrow....

**Comment by mapx-** [comment]
using a chilean vpn:

```
¡Ay no! Quizá estés usando un VPN o proxy
Para continuar viendo, desactive cualquiera de estos servicios e inténtelo de nuevo.
¿Tiene preguntas? Por favor, visite nuestra página de Soporte en https://support.pluto.tv
```

`Oh no! You may be using a VPN or proxy. To continue watching, please disable any of these services and try again. Have questions? Please visit our Support page https://support.pluto.tv`

**Comment by Residentcl** [comment]
Here is a short video with one of the 2 problems,
in this one the advertisement does not appear, but it has some kind of problem.

10:50 > `https://youtu.be/KLlqDTjOEYk`

also a log with the requests:
[log.txt](https://github.com/user-attachments/files/17286648/log.txt)

If you tell me how I can add more information to see the problem, tell me how to do it.

**Comment by stephenhawk8054** [comment]
@Residentcl Can you add this filter and get the log again?

```adb
@@||a-fds.youborafds01.com/data?$xhr,domain=pluto.tv
```

**Comment by Residentcl** [comment]
Solved. Thanks!
I'll see if the other problem comes up and make the report.

**Comment by poemathesonking** [comment]
I am seeing ads on Pluto now. Started yesterday, while watching X-Files around season 1 Ep 5.

**Comment by stephenhawk8054** [comment]
Please give exact link where you see the issue, and share your uBO troubleshooting information to here.

**Comment by Sheriff-Unit-3** [comment]
Also seeing ads on [Star Trek: Voyager S04E01](https://pluto.tv/us/on-demand/series/63daf1c0ff32c10013d73240/episode/63eaa90a1fdb9b00139aa8f1), showed up today. The method of stitching in the ads seems to have changed, the ads are only 1 every 10-15 mins. They also no longer show an overlay when a ad is playing.

Debug:

<details>

```yml
uBlock Origin: 1.71.0
Firefox: 151
filterset (summary):
 network: 186397
 cosmetic: 43050
 scriptlet: 33411
 html: 3628
listset (total-discarded, last-updated):
 default:
  user-filters: 0-0, never
  ublock-filters: 52421-70, 1h.33m Δ
  ublock-badware: 10390-38, 1h.33m Δ
  ublock-privacy: 4040-2, 1h.33m Δ
  ublock-unbreak: 2831-1, 1h.33m Δ
  ublock-quick-fixes: 459-13, 1h.33m Δ
  easylist: 88977-128, 1h.33m Δ
  easyprivacy: 55856-40, 1h.33m Δ
  urlhaus-1: 49450-0, 1h.33m
  plowe-0: 3505-1022, 11d.21h.35m
filterset (user): [empty]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 36710 ms (selfie)
 maxAssetCacheWait: 1332 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 664
 network:
  pluto.tv: 637
  browser-intake-datadoghq.com: 17
  doubleclick.net: 4
  googleadservices.com: 2
  googlesyndication.com: 2
  googletagmanager.com: 2
 extended:
  ##+js(xml-prune, 'xpath(//*[name()="Period"][.//*[name()="BaseUR…
  ##+js(json-prune-fetch-response, adBreaks.[].startingOffset adBr…
```

</details>
