### ISSUE TITLE
elitepvpers.com ads

### ISSUE THREAD

**Issue by i8cczshd** [uBlockOrigin/uAssets#9768]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.elitepvpers.com/forum/`

### Describe the issue

the page is full of advertising

### Screenshot(s)

![Screenshot 2021-08-16 at 11-56-06 elitepvpers](https://user-images.githubusercontent.com/81616288/129546522-75d2b956-cf8a-4262-8c45-59b412edadc9.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0 (64-Bit)

### Settings

Fanboy’s Annoyance
uBlock filters – Annoyances
Block access to LAN
AdGuard URL Tracking Protection

**Comment by uBlock-user** [comment]
Are you logged in when you see ads ?

**Comment by uBlock-user** [comment]
Reset to default settings + all other extensions disabled and then try again.

**Comment by i8cczshd** [comment]
> 
> 
> Reset to default settings + all other extensions disabled and then try again.

does not work. same problem in microsoft edge 

https://user-images.githubusercontent.com/81616288/129561717-164cf48b-933a-4ec6-a760-11c247e80a34.mp4

**Comment by uBlock-user** [comment]
![Capture](https://user-images.githubusercontent.com/21290713/129565830-2f563404-bce1-44a7-87ff-65900dbfda97.PNG)

I don't see ads whatsoever on Firefox and Chrome, so you will have to investigate on your own as to why uBO is not blocking. Use the logger for that.

**Comment by JobcenterTycoon** [comment]
Ads coming from `cdn.discordapp.com/attachments/` but a filter got removed from EasyList a few days ago
<img width="580" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/129578454-dadec1bd-88a4-453e-9d69-ea35c9b8347a.PNG">

**Comment by uBlock-user** [comment]
@JobcenterTycoon which commit in EasyList ?

**Comment by JobcenterTycoon** [comment]
I can’t find the commit at the moment

**Comment by uBlock-user** [comment]
https://github.com/easylist/easylist/commit/c7d4398734d4a372bacf0cabecc7d6a653bae74

**Comment by JobcenterTycoon** [comment]
Ads are back

**Comment by JobcenterTycoon** [comment]
Ads are back. The attributes `ugc` and `nofollow` need to be added

**Comment by JobcenterTycoon** [comment]
The ad images are here again

**Comment by JobcenterTycoon** [comment]
Ads coming from `f00f00.bar`
