### ISSUE TITLE
downloads.descendant.me [Anti AdBlock]

### ISSUE THREAD

**Issue by alkanna** [uBlockOrigin/uAssets#9769]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

downloads.descendant.me

![Screenshot_20210816-183153505](https://user-images.githubusercontent.com/30343764/129598140-a4db77c4-d831-437a-a35f-d3292c633e94.jpg)

### Describe the issue

Timer goes away then this message appears

### uBlock Origin version

1.37.2

### Browser name and version

Kiwi browser latest

### Settings

None

**Comment by uBlock-user** [comment]
force update ublock filters list.

**Comment by linuxct** [comment]
This does not work anymore, and the site is showing other annoyances. Consider removing the current rule as it is difficulting browsing the website. 

![image](https://user-images.githubusercontent.com/3966313/129990040-96d1c9d6-b8e0-4108-bd48-6fe8ffe4e3f0.png)

**Comment by uBlock-user** [comment]
@linuxct which current rule ?

**Comment by linuxct** [comment]
> @linuxct which current rule ?

I think the one causing the graphical glitches is https://github.com/uBlockOrigin/uAssets/commit/e672e03f6ca4534d69d0c67b77747233f676bd11  

Open the site again with the current version of filters-2021.txt, you will see the glitches I am talking about. Also, even submitting the form manually doesn't work now, and is showing the same error @alkanna reported.  

(I am running latest updated filters on Chromium Linux, for that matter)

**Comment by uBlock-user** [comment]
@linuxct They have compounded their anti-adblock check with another server-sided and client-sided check, there's no graphical glitches whatsoever, if I remove the current rules, the pevious client-sided check antiadblock will be back.

**Comment by uBlock-user** [comment]
The original issue tracker is at https://github.com/uBlockOrigin/uAssets/issues/9756, so post there from now on. This one is a duplicate.
