### ISSUE TITLE
zerocat.eu

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#977]
### URL(s) where the issue occurs

`https://zerocat.eu/` redirects to: `https://zerocat.eu/1HeLLo4uzjaLetFx6NH3PMwFP3qbRbTf3D`
another example: `https://www.zerocat.eu/1AnimePihDhcbVdK1nvnbSEtH4oKU8RAYG/`

### Describe the issue

Mining-wall. Can't access site without allowing mining. Is this something that could/should be dealt with by uBO?

**Comment by mapx-** [comment]
try (it seems the mining is still blocked with this exception)
`@@||zerocat.eu/uimedia/miner.js`

**Comment by okiehsch** [comment]
You can also add `@@||authedmine.com^$domain=zerocat.eu` without any mining taking place, but
I do not see how to use that site without allowing mining.

**Comment by terrorist96** [comment]
Yeah, neither filter will allow access to the sites.

**Comment by mapx-** [comment]
seems working using:
```
@@||zerocat.eu/uimedia/miner.js
zerocat.eu##DIV[style^="z-index: 99999999;"]
```

I'm able to download (via torrents) the various things. Could you test it ?

**Comment by okiehsch** [comment]
Works on my end.
