### ISSUE TITLE
readthedocs.io ads

### ISSUE THREAD

**Issue by pavel-lexyr** [uBlockOrigin/uAssets#9773]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://docs.readthedocs.io/en/stable/`

### Describe the issue

Ads appear in the footer of `readthedocs.io` documentation.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/69010336/129794914-15d3ddd6-5c67-40b8-9df9-f1d808f8d757.png)

### uBlock Origin version

Latest

### Browser name and version

Firefox

### Settings

-

### Notes

Suggested change:

`readthedocs.io##.ethical-rtd`
`readthedocs.io##.keep-us-sustainable`

**Comment by uBlock-user** [comment]
Report to https://github.com/easylist/easylist/issues
