### ISSUE TITLE
annoyances on mmwu webpage

### ISSUE THREAD

**Issue by thinksheiscool** [uBlockOrigin/uAssets#9777]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://makemoneywithurl.com/2020/09/best-paying-url-shortener-or-highest-paying-url-shortener-sites-list`

### Describe the issue

- anti right click
- anti dev tools (f12 did not make the developer tools appear)
- anti select
- ctrl+u did not work as I may have expected

### uBlock Origin version

1.37.2

### Browser name and version

Google Chrome 92.0.4515.107 (Official Build) (64-bit)

### Settings

-  ![image](https://user-images.githubusercontent.com/89113298/129838299-184a435f-a4d1-4763-b93e-d63a8a1a0bd4.png)
-  ![image](https://user-images.githubusercontent.com/89113298/129822807-fff4a1e9-2f56-44da-923d-3665e9bacdba.png)
-  ![image](https://user-images.githubusercontent.com/89113298/129822913-daef1b17-5a9f-491e-a433-3330f0394ae6.png)

**Comment by uBlock-user** [comment]
which url sent you to `https://makemoneywithurl.com/2020/09/best-paying-url-shortener-or-highest-paying-url-shortener-sites-list` ?

**Comment by thinksheiscool** [comment]
I'm not sure what happened.
