### ISSUE TITLE
katestube.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#978]
URL(s) where the issue occurs

https://www.katestube.com/videos/51982/callie-calypso-gets-smashed-hard-from-behind-by-huge-cock/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
I got only popups

**Comment by xDarkARG** [comment]
update the filters of these @mapx-

**Comment by KiLL4FuNK** [comment]
play the video the ads appear in random videos @mapx-

`https://i.imgur.com/5pOPhoq.png`

**Comment by SMed79** [comment]
```
||jsmptjmp.com^$popup
/contents/other/player/*$media,~third-party
```
same to `cnnamador.com`

**Comment by KiLL4FuNK** [comment]
ADS PLAY VIDEO

`https://www.katestube.com/videos/43456/a-big-penis-is-annas-favourite-thing/`
