### ISSUE TITLE
technicalatg.xyz anti adb

### ISSUE THREAD

**Issue by thinksheiscool** [uBlockOrigin/uAssets#9781]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://technicalatg.xyz/`

### Describe the issue

anti adblock

### uBlock Origin version

1.37.2

### Browser name and version

Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)

### Settings

![image](https://user-images.githubusercontent.com/89113298/129836510-a9a9bc80-348c-41f2-80b2-73ca683d2cc5.png)
![image](https://user-images.githubusercontent.com/89113298/129836524-ba8fc9b6-fd99-4216-a60b-76efb221aa0f.png)

### Notes

https://github.com/AdguardTeam/AdguardFilters/issues/90583

**Comment by uBlock-user** [comment]
Don't see anti-adblock but I see rapid spam of `adsbygoogle.js` XHRs being fired infinitely as per the logger, so addressed in the filter.
