### ISSUE TITLE
lubuntu [dot] net is not a legit website

### ISSUE THREAD

**Issue by NotAProton** [uBlockOrigin/uAssets#9785]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://lubuntu.net/`

This site should be added to the badware list

### Describe the issue

The official website of Lubuntu is `https://lubuntu.me` , lubuntu [dot] net distributes old version and poses as the official site.

Proof:

`https://en.wikipedia.org/wiki/Talk:Lubuntu#Website_change_(.net_%3E_.me)`

"Hi, I'm Lubuntu's Release Manager. We actually no longer have control of Lubuntu dot net, which is being squatted by FOSSASIA at the moment. We'll redirect net to me when it's sorted. " -[Simon Quigley]

`https://ubuntu.com/download/flavours` links the `https://lubuntu.me` website

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0

### Settings

no changes

**Comment by livvy94** [comment]
Thank you so much! I just encountered a "Best Linux distros for low-end laptops" type article that links to the bad link. So weird. The article in question is here in case anyone has the energy to contact them & ask them to change it: https://linuxhint.com/best-old-laptop-linux-distributions/
