### ISSUE TITLE
[Anti-adblock] rodjulian.com

### ISSUE THREAD

**Issue by Cyberavater** [uBlockOrigin/uAssets#9786]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

Eg linK: `https://link.bonghd.com/?x_data=nUE0pUZ6Yl9hMKphM2E0o3DhL29gY2McoTHiBGN1AGV0Awp4:1`

### Describe the issue

[Anti-adblock] rodjulian.com

### uBlock Origin version

Latest

### Browser name and version

Chrome Latest

### Settings

N/A

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/eb8f3bcd444be3d4388b6d0dc1c63810bd9bff2e

**Comment by Cyberavater** [comment]
Try to complete their steps, they have Anti-adblock even in step 2.

**Comment by Cyberavater** [comment]
marharo.com, medcpu.com.
