### ISSUE TITLE
gotporn.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#979]
URL(s) where the issue occurs

https://www.gotporn.com/carne-del-mercado---intense-pickup-and-fuck-with-fiery-brunette-latina-babe/video-5959909

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
update the filters of these @mapx-

**Comment by ghajini** [comment]
`https://www.gotporn.com/teen-takes-a-big-cock-in-her-ravaged-pussy/video-2880859`
popup ads

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by mapx-** [comment]
using `Mobile View Switcher` addon I get:

![image](https://user-images.githubusercontent.com/10303732/102683529-2edb6580-41d2-11eb-8dff-56aa404f45d6.png)

@ghajini test:

`gotporn.com##+js(aeld, , open)`

**Comment by ghajini** [comment]
These are ads
![IMG_20201219_131444](https://user-images.githubusercontent.com/20338483/102684178-4fb8b080-41fc-11eb-83cf-bf3a1ef07819.jpg)
![IMG_20201219_131505](https://user-images.githubusercontent.com/20338483/102684185-5e06cc80-41fc-11eb-8248-b4fc50be02f6.jpg)


Yes fixed **mapx-** with your filter...

**Comment by mapx-** [comment]
I get no such ad, if you have a filter just provide it

**Comment by ghajini** [comment]
Your filter `gotporn.com##+js(aeld, , open)` works

**Comment by mapx-** [comment]
meaning https://user-images.githubusercontent.com/20338483/102684185-5e06cc80-41fc-11eb-8248-b4fc50be02f6.jpg

**Comment by mapx-** [comment]
or is the same thing (without my filter you get that ad)

**Comment by ghajini** [comment]
Yes that's just continuation of popups from `syndication.dynsrvwer.com......`,nothing new....your filter stops that from root....
