### ISSUE TITLE
[Anti-adblock] link1s.com (truebrandy.com, aemenstore.com, *)

### ISSUE THREAD

**Issue by Cyberavater** [uBlockOrigin/uAssets#9792]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://link1s.com/2k9vs2k12`

### Describe the issue

Try the given link at least 10 or more times, you'd find more than 2 domains where UBO is detected. 

### uBlock Origin version

Latest

### Browser name and version

Chrome Latest

### Settings

N/A

**Comment by uBlock-user** [comment]
mind listing all the domains other than these two ?

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/82382227d9e095a9e4cc5761cd4a376ce0a9ff40

**Comment by Cyberavater** [comment]
marharo.com, medcpu.com.

**Comment by Cyberavater** [comment]
anhdep24.com
