### ISSUE TITLE
youtube.com - ads when clicking on Discord embeds

### ISSUE THREAD

**Issue by Tiagoquix** [uBlockOrigin/uAssets#9793]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [x] uBO with default lists/settings
- [ ] using a new, unmodified browser profile

### URL(s) where the issue occurs

Any YouTube video, but I will use this to give an example.

https://www.youtube.com/watch?v=msPCQgRPPjI

### Describe the issue

YouTube does display ADs if you click on the title of the Discord embed (lime green in the screenshot) but it doesn't if you click on the link sent (cyan in the screenshot).

### Screenshot(s)

![image](https://user-images.githubusercontent.com/30274161/129990721-32c47893-2e0b-4981-b07d-8f84f6a8f2f8.png)

### uBlock Origin version

1.37.2

### Browser name and version

Google Chrome - Official Build 92.0.4515.159

### Settings

The unique change I made was to enable the "spa, por: AdGuard Spanish/Portuguese" filter.

### Notes

This happens with any YouTube video that has ADs.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7636
