### ISSUE TITLE
indavideo.hu

### ISSUE THREAD

**Issue by pcroland** [uBlockOrigin/uAssets#9794]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://indavideo.hu`

### Describe the issue

indavideo detects uBlock Origin and doesn't play videos.

### Screenshot(s)

`https://i.kek.sh/nioeNnmbDiL.png`

### uBlock Origin version

v1.37.2

### Browser name and version

92.0.4515.159

### Settings

I just enabled some annoyances filters but it also does not work with default settings.

### Notes

It was already reported at #8628 but it was closed without any solution.

**Comment by uBlock-user** [comment]
Solution was already added - https://github.com/uBlockOrigin/uAssets/commit/d832ce87febc4cc5c389f8aca57660b56dd265e1

**Comment by okiehsch** [comment]
That filter still works for me, if I disable it I get the adblock detection message shown in the screenshot.

**Comment by uBlock-user** [comment]
`embed.indavideo.hu##+js(set-constant, AdHandler.checkAdblock, noopFunc)` is present in HUN list.

**Comment by uBlock-user** [comment]
Post in https://github.com/uBlockOrigin/uAssets/issues/8628, do not open new issues for this, it's closed because the fix was added.
