### ISSUE TITLE
Again adblock notice detected at https://elarconte.com/

### ISSUE THREAD

**Issue by Jose1971AB** [uBlockOrigin/uAssets#9797]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

 
`https://elarconte.com/`

### Describe the issue

The ad blocker notice on this page was fixed some time ago but is reappearing.

### Screenshot(s)

https://ibb.co/x3TkwwD

### uBlock Origin version

 Versión1.37.2 

### Browser name and version

Mozilla Firefox 91.0.1

### Settings

https://ibb.co/3swWvyJ

**Comment by uBlock-user** [comment]
force update ublock filters list.

**Comment by Jose1971AB** [comment]
Hello @uBlock-user, good afternoon 🙋‍♂️😀

**At the moment it works perfect**, to see how long it lasts 👍👌👏👏👏

Very grateful for everything 😎

A cordial greeting 🤝🤝👋👋
