### ISSUE TITLE
facebook.com

### ISSUE THREAD

**Issue by Uricorn** [uBlockOrigin/uAssets#98]
### URL(s) where the issue occurs

facebook.com

### Describe the issue

Facebook is now showing ads for desktop users "[who currently use ad blocking software.](http://newsroom.fb.com/news/2016/08/a-new-way-to-control-the-ads-you-see-on-facebook-and-an-update-on-ad-blocking/)"

### Screenshot(s)

![capture](https://cloud.githubusercontent.com/assets/5571265/17570691/22911d78-5f56-11e6-9f99-3a6f010e3f72.png)

### Versions

- Browser/version: Waterfox/47.0.1
- uBlock Origin version: 1.8.4

### Settings

![capture](https://cloud.githubusercontent.com/assets/5571265/17570807/969b7952-5f56-11e6-8c60-9a3d8f2717dc.png)

### Notes

Only started noticing it today, also at least one other user reported the same issue. https://github.com/gorhill/uBlock/issues/1886

**Comment by gorhill** [comment]
I will need to reproduce to be able to figure what filter is needed. So far, I haven't been able to reproduce (it's a brand new account I created for that purpose). any hint on how to reproduce is welcomed.

**Comment by warthog3** [comment]
Those posts can be blocked with the following filter:

facebook.com##:xpath(//*/a[@class='uiStreamSponsoredLink']/ancestor::div[contains(concat(' ',normalize-space(@id),' '),'hyperfeed_story_id_')])

Source: https://www.reddit.com/r/ublock/comments/4wye33/does_ublock_monitor_this_site_if_so_can_any/d6cdlei

**Comment by gorhill** [comment]
Thanks @warthog3. I will try to understand the DOM layout for that ad according to your xpath:

    div#hyperfeed_story_id_[...]
        a.uiStreamSponsoredLink

If this is it, would this also work?

    div[id^="hyperfeed_story_id_"]:has(a.uiStreamSponsoredLink)

**Comment by collinbarrett** [comment]
@gorhill and @warthog3 both of your solutions seem to be effective. though I am not 100% confident in my ability to verify it will always work. the new Suggested Posts seem to show up near the top of the feed on every refresh, and with either of your rules added, I am not seeing them.

**Comment by collinbarrett** [comment]
I am seeing it show up in uBlock's logger as blocking something with that filter on occassion. So, yes, I think it is working.

**Comment by gorhill** [comment]
For those who can have these ads at will, to confirm it works is just a matter of toggling on/off cosmetic filtering in the popup panel -- they will be shown/hidden as one toggle off/on cosmetic filtering.

**Comment by gorhill** [comment]
At this point it comes down to pick which selector runs most efficiently.

Does that work?

    facebook.com###stream_pagelet div[id^="feed_stream"] > div[id^="substream_"] div[id^="hyperfeed_story_id_"]:has(a.uiStreamSponsoredLink)

**Comment by collinbarrett** [comment]
@gorhill that last rule does not seem to work. the first two still do. not sure how to compare which is most efficient.

**Comment by gorhill** [comment]
Ok, I see the DOM layout can vary a bit more than I expected. Try:

    facebook.com###stream_pagelet div[id^="feed_stream_"] div[id^="substream_"] div[id^="hyperfeed_story_id_"]:has(a.uiStreamSponsoredLink)

**Comment by collinbarrett** [comment]
@gorhill yes, that one seems to work. so, to summarize, any of the three below seem to be working for me. which would be more efficient?

`facebook.com##:xpath(//*/a[@class='uiStreamSponsoredLink']/ancestor::div[contains(concat(' ',normalize-space(@id),' '),'hyperfeed_story_id_')])`

`facebook.com##div[id^="hyperfeed_story_id_"]:has(a.uiStreamSponsoredLink)`

`facebook.com###stream_pagelet div[id^="feed_stream_"] div[id^="substream_"] div[id^="hyperfeed_story_id_"]:has(a.uiStreamSponsoredLink)`

**Comment by gorhill** [comment]
I modified my comment above. For now, I will prefer the `:has` version. It will work declaratively whenever a browser supports it, and I without any basis whatsoever I have the feeling it might be more efficient.

**Comment by gorhill** [comment]
Taking into account the [information gathered on reddit](https://www.reddit.com/r/ublock/comments/4wye33/does_ublock_monitor_this_site_if_so_can_any/), and given your confirmation that it works, for now I will go with:

    facebook.com###stream_pagelet div[id^="hyperfeed_story_id_"]:has(a.uiStreamSponsoredLink)

**Comment by Uricorn** [comment]
It works after I clicked the update filters button just now, so unless facebook makes any new changes I think this can be considered resolved.

Thank you!

**Comment by peopledrivemecrazy** [comment]
I have added these filters in my filters tab, but still continue to see sponsored post.

**Comment by collinbarrett** [comment]
@gorhill it looks like EasyList implemented a different rule. not sure if having both rules hurts (since many users of uBlock are probably subscribed to both uAssets and EasyList)

https://adblockplus.org/blog/fb-reblock-ad-blocking-community-finds-workaround-to-facebook

**Comment by gorhill** [comment]
Having both does not hurt -- like he is saying, Facebook may change a few things to make that filter stop working. On my side I still haven't been able to get any ads, so I rely completely on others to figure the DOM details of these ads.

**Comment by Uricorn** [comment]
I just got an ad in my feed, so I guess they found a way to get around it.

**Comment by gorhill** [comment]
> I just got an ad in my feed

Whoever get an ad in their feed, what help is to provide the DOM details for that ad. oTherwise nobody can figure what filter could work.

**Comment by jcallen-gentoo** [comment]
I just got an ad, and have some information on the DOM:

The class names all appear obfuscated (names like "_x72" and "_5jmm"), but the outer <div> of the ad has an ID beginning with "hyperfeed_story_id_" and contains a <div> that contains a <div> that contains a <div> that has class="... userContentWrapper ..." and contains a <div> that contains a <div> that contains a <span> without a class and with the exact content "Suggested Post"

**Comment by gorhill** [comment]
> with the exact content "Suggested Post"

Aren't ads supposed to be "Sponsored Post"?

**Comment by gorhill** [comment]
I still do not have ads in my stream with cosmetic filtering disabled, however I have that annoying "People You May Know" box appearing all the time. I could make it go away with:

    facebook.com##:xpath(//div[@id="stream_pagelet"]//div[starts-with(@id,"hyperfeed_story_id_")][.//text()="People You May Know"])

So the same can be done for "Suggested Post" for those who get them:

    facebook.com##:xpath(//div[@id="stream_pagelet"]//div[starts-with(@id,"hyperfeed_story_id_")][.//text()="Suggested Post"])

And for "Sponsored Post":

    facebook.com##:xpath(//div[@id="stream_pagelet"]//div[starts-with(@id,"hyperfeed_story_id_")][.//text()="Sponsored Post"])

However, this works for English Facebook, this would need to be adapted for other languages.

**Comment by genev** [comment]
The filters in the previous comment work great for me, but would this block my friends' posts that include the word "Sponsored"?

**Comment by gorhill** [comment]
> but would this block my friends' posts that include the word "Sponsored"?

Yes, I though about that afterward -- try:

    facebook.com##:xpath(//div[@id="stream_pagelet"]//div[starts-with(@id,"hyperfeed_story_id_")][.//h6//span/text()="Sponsored"])

Or, somebody tell me the ancestors of the "Sponsored" text -- I am assuming `h6` is one of them (just like in 994985e472ebab240b4a399edeee10b8daf02c2a).

**Comment by gorhill** [comment]
By the way, what is the best way for one to see these ads? What specific feed do I need to activate? Currently using _"News Feed"_/_"Most Recent"_. Is _"Pages Feed"_ better if trying to get these ads?

**Comment by collinbarrett** [comment]
Yeah, I'm having a hard time seeing any of them as of late, either. Last week when they first rolled them out I was seeing them a lot. Now, I don't see any in my feed or blocks of them in the uBlock logger... When I was seeing them, though, they were just in the standard News Feed almost always as like the 2nd or 3rd card down.

**Comment by gorhill** [comment]
> in the uBlock logger

On my side I find it easier to toggle on/off the [no-cosmetic-filter switch](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering) to see what is being hidden by uBO. So far, I only got the _"People You May Know"_ cards.

**Comment by JTBrinkmann** [comment]
Ads are personalised, so I guess it helps if Facebook knows a bit more about you and what you like. Maybe if you'd like some companies, you see more suggested posts?

**Comment by gorhill** [comment]
Yes, I did "liked" stuff just for the sake of getting a feed with something in it. Currently tech news, science news. Maybe I should go with something more likely to generate ads. Clues?

**Comment by Uricorn** [comment]
Facebook might not be showing ads to you if your account is too new or you don't have enough friends. (They might have data suggesting that showing ads to those types of people causes people to use Facebook less or close their account.)

Some companies will try to aggressively target you if you visit their site a few times. https://www.invisionapp.com/ and https://www.intercom.io/ might be some of those sites.. not certain.

Either way I haven't seen any ads again, so maybe they were trying to test something but it broke the site.

**Comment by gorhill** [comment]
Is that feed supposed to update itself regularly with new posts at the top? I can see the right-hand bar content change, but the first post in my feed seems to not change.

**Comment by yonjah** [comment]
I addded the 3 rules suggested by @collinbarrett and it seemd to be working for a bit, but now
I'm seeing ads again. not sure if facebook changed something or I just didn't noticed the ads initially.
I added the following rule and it for now I think it's working

```
facebook.com##div[aria-label=Story]:has(a.uiStreamSponsoredLink)
```

I'm not sure but it seems if your scrolling your feed quickly (like when your searching for ads or a specific post) you won't get any ads, so it's kinda hard to check if any of the filters actually work with a quick glance

**Comment by gorhill** [comment]
I repeat:

> Whoever get an ad in their feed, what helps is to provide the DOM details for that ad.

If you provide me with the appropriate details, I will be able to come up with an optimal filter.

To provide DOM details is easy:

Right-click on _"Sponsored"_, click _"Inspect"_ in context menu. Provide screenshot of inspector content, large enough to include as much information as possible.

**Comment by yonjah** [comment]
@gorhill Sorry I thought about it only after I tested the filter, but it was too late.
I tried turning it off and looking for some ads, but as I wrote I think facebook try to deliver ads when your more engage with the content and not just scrolling. If I'll see any ads I'll get their HTML and paste it here.
A screenshot will probably won't be enough since when I looked at it there were at least 10 nested divs of junk just for the tiny box "Sponsored" link

**Comment by dxo** [comment]
gorhill,

I was doing fine with the last snippet, but the posts returned the last time I logged on to FB. Same type of suggested/sponsored posts. I screen captured an inspect element content. Let me know if you need more info. I'm not a code whiz, but I can find what you need if you tell me where to look. Thanks for your efforts. 

![fbadpo1](https://cloud.githubusercontent.com/assets/456761/17758241/bc03637a-64bb-11e6-9a8b-5d383a30f1c5.png)

**Comment by gorhill** [comment]
This is weird. The presence of `#shadow-root` suggests the post has been hidden by uBO, but if so, there is missing details in there.

Can you expand the `#shadow-root (open)` node?

**Comment by dxo** [comment]
The next post I looked at when I got back on FB did not have the shadow root in there. I was going to copy the inspect, but there's so many nested divs it will take at least 5 screenshots and an edit to get it all in one pic. I've never seen that many nested divs...for one post. No wonder FB is sucking up so much resources. The "sponsored" notation is under the page name, the suggested is above the post, as usual. I didn't see any string that made a reference to it.

Attached is an image of the inspect that shows the div the "sponsored" notation below the page name is sitting in.
![fbadpo2](https://cloud.githubusercontent.com/assets/456761/17761303/f3f13646-64d3-11e6-9ed0-06cf57ead799.png)

**Comment by gorhill** [comment]
Sorry, nothing I can do with this, missing too much information.

**Comment by dxo** [comment]
Here's a complete screenshot of the inspect with the shadow root expanded. I didn't expand anything esle, but I left the the tab open and the inspect window, etc if you need more.
![fbnewin1](https://cloud.githubusercontent.com/assets/456761/17761700/5fc94f18-64d7-11e6-8679-15d513e4e377.png)

**Comment by neilmcd** [comment]
I'm not sure if this is new, but it appears that the 'Sponsored' text is injected from CSS rather than in the HTML itself.

![image](https://cloud.githubusercontent.com/assets/81166/17771706/6347a576-653c-11e6-8409-120a13a828b4.png)

**Comment by gorhill** [comment]
> it appears that the 'Sponsored' text is injected from CSS rather than in the HTML itself

Can you confirm that nowhere in this specific post there is the `uiStreamSponsoredLink` class? Just to rule out that this is a uBO issue rather than a filter issue.

**Comment by gorhill** [comment]
I looked at the difference from my own no-ads feed, and I see differences in the DOM below `<div class="_5pcp">`. If I execute in the console:

    document.querySelectorAll('[data-ft="{\\"tn\\":\\"j\\"}"]')

I get nothing. Can someone try the same and see if the resultset if any, all matches "Sponsored" content on the page?

**Comment by neilmcd** [comment]
> Can you confirm that nowhere in this specific post there is the uiStreamSponsoredLink class?

There's no 'uiStreamSponsoredLink' class in the post

> Can someone try the same and see if the resultset if any, all matches "Sponsored" content on the page?

I get a few matches and one of them is the sponsored text

<img width="906" alt="screen shot 2016-08-18 at 13 08 29" src="https://cloud.githubusercontent.com/assets/81166/17773176/fee54620-6544-11e6-86ca-aa4fd098f93d.png">

**Comment by gorhill** [comment]
Thanks for helping narrowing this.

Are the normal post looking the same, i.e. do they also have a `::after` pseudo-class and do hey also have the `href="#"` attribute?

**Comment by neilmcd** [comment]
No problem, thanks for looking at it. 

The `f_18zevbflxz:after` CSS rule seems to be the differentiating factor as the other posts use `f_18zevbh_2l` without the `::after` pseudo-class. The names change on each reload though.

They all have the `href="#"` attribute

<img width="855" alt="screen shot 2016-08-18 at 13 23 50" src="https://cloud.githubusercontent.com/assets/81166/17773562/0663f50c-6547-11e6-9f3a-be4f9eafcccd.png">

<img width="561" alt="screen shot 2016-08-18 at 13 26 31" src="https://cloud.githubusercontent.com/assets/81166/17773681/66187bbc-6547-11e6-8188-7a9fe359f5c3.png">

**Comment by neilmcd** [comment]
> The names change on each reload though

Actually, no they don't. But I suspect that they will or are different for other users.

**Comment by yonjah** [comment]
I just got an ad ion my feed now -
I pasted the entire HTML to -
http://pastebin.com/Higv7YpD

removed some unique identifiers and user names (all the *** and XXX) but that shouldn't be much relevant

Notice that this post came with some general facebook message about ad management
I atttached the containing DIV just in case tit might be relevant but the actual ad is in the DIV with id "u_ps_0_0_b"

I still have it open if there is some more info I can add

**Comment by gorhill** [comment]
@yonjah How did you get that HTML code? There are comments (`<!-- ... ->`) in there -- and these comments are not supposed to be instanciated into DOM nodes.

**Comment by yonjah** [comment]
I just copied the HTML out of the inspector.
The inspector let you see the entire HTML regardless if it's a comment or not.

But I think facebook is doing something really shady with the DOM.
This ad is different than the one I saw earlier  there is no href with the class `uiStreamSponsoredLink` in the feed. in fact I couldn't find any element with this class nowhere on the page.

**Comment by gorhill** [comment]
> The inspector let you see the entire HTML regardless if it's a comment or not.

What browser was this? Both Chromium/Firefox show me the live DOM (which is what uBO works with), not the pre-parsed DOM, which is what you seem to have extracted somehow.

**Comment by yonjah** [comment]
This is firefox 48.0 using the builtin devtools

**Comment by gorhill** [comment]
Ok, somehow I never realized the comment were visible in the DOM.

So how about:

    facebook.com##:xpath(//div[@id="stream_pagelet"]//div[starts-with(@id,"hyperfeed_story_id_")][.//div[@data-reactroot]//button[@title="Remove"]])

I get no result on my side, but then I have no ads in the first place.

**Comment by yonjah** [comment]
I'm still seeing some ads
new HTML http://pastebin.com/KvkzK3vY
also this rule seems to catch some genuine posts as well.

**Comment by lassekongo83** [comment]
I don't use Facebook, but I took a look and noticed that their images still loads from slash ads. Maybe you could try something simple like this?`facebook.com##div[class^="userContentWrapper"]:has(img[src*="facebook.com%2Fads"])`

**Comment by neilmcd** [comment]
They seem to have changed it back and the old rules are working again for me now. The `uiStreamSponsoredLink` class is back when inspecting the 'Sponsored' text.

**Comment by gorhill** [comment]
Would

    facebook.com##:xpath(//div[@id="stream_pagelet"]//div[starts-with(@id,"hyperfeed_story_id_")][.//span="Suggested Post"])

Also remove legit post?

In any case, I will go through the cosmetic filtering engine and prepare for what Facebook may come up again if the problem resurface. This will not be next version though, rather the one after this. I already modified the new `:matches-css` selector to be able to "see" `:after` style, not what is missing is the ability to allow more than one of these new operators into the same filter. That will be for another version, not 1.8.6.

**Comment by dxo** [comment]
I'm getting the same result as neilmcd. The previous filter snippet has resumed working again. Thanks gorhill and those who contribute their time and efforts to this project and others like it.

**Comment by yonjah** [comment]
@gorhill The last rule you added seems to be working ok and doesn't remove any legit posts.

**Comment by taliarbel** [comment]
I'm a reporter doing a story for AP about ad blocking, and am interested in talking to people who write the filters that block ads -- would you want to explain the process to me and what motivates you? I'm at 212-621-7629 and tarbel@ap.org. Thanks, Tali

**Comment by gorhill** [comment]
> would you want to explain the process to me and what motivates you?

Aside all the obvious reasons (privacy invasion, malvertising, bloat, bandwidth, attempt at manipulation, bullshit, noise to signal ratio, etc.), blockers and filter lists help ensure **user** agents (i.e. browsers) keep working on behalf of **users**.

**Comment by taliarbel** [comment]
Could you talk on the phone for an interview?

-------- Original message --------

**Comment by IOUTODAY** [comment]
Just found you and your work - I would like to pick your brain on my efforts - ioutoday.org - if you don't mind and can spare a free minute I can be reached at jd@ioutoday.org

**Comment by gorhill** [comment]
@taliarbel 

Sorry, I do not give interview. The whole project is developed completely publicly, so whatever else is not answered by what is public here should be assumed to be private matter which I rather keep private.

**Comment by momphis** [comment]
Are you looking for a deeper motivation other than what gorhill has already said?  I can't speak for him, only as a user of his code.  I use uBlock origin because my browser performs much better without ads, I'm at less risk of getting infected with malware, and it's easier to view the content I want to view.  There's no deep, political reason for me: I just want to use the internet.  uBlock origin makes it easier.

**Comment by taliarbel** [comment]
I'm not interested in motivation as much as process...is all the code open-source and unpaid, or does ublock origin have paid employees too? how hard is it to write filters that bypass walls and hide reinserted ads? how quickly do publishers react, if they do at all? do all these filters get automatically sent to all ublock origin users or is there individual tweaking that many people have to do?

**Comment by IDKwhattoputhere** [comment]
> does ublock origin have paid employees too?

Cute. Paid with what money?
This thread is about the ongoing issue with facebook.com though. Just saying, not sure how @gorhill sees this.

**Comment by gorhill** [comment]
It's all volunteer-based work, nobody is paid (it's a hobby).

How hard it is to create filter is a case-by-case basis, there is no generic answer. When it gets too difficult I take it as a sign it's time to extend the blocker capabilities. Probably best is to ask to those who spend a lot of time writing filters, [the volunteers maintaining EasyList, EasyPrivacy](https://forums.lanik.us/search.php?search_id=active_topics) and all other major filter lists.

Filter lists are updated automatically, so when a new filter is added, eventually everybody will have it. The goal is for the blocker to work seamlessly, requiring no tweaking by users -- but they can tweak however they want if they want to.

**Comment by taliarbel** [comment]
OK, but for example, with Facebook ads - a user would have to do more than simply install ublock to block those ads, no? that's what this whole message board is about?

**Comment by kosmonautbruce** [comment]
Tali, you will get a much better understanding of the process of development by familiarizing yourself with GitHub. All of the development of uBlock Origin is done very much out in the open, transparently. With some research, you can see it all, back to the beginning (almost). 

gorhill's recommendation of going to the EasyList forum is a great one, if you want to see how that side of the equation occurs, as well, fwiw.

**Comment by gorhill** [comment]
> with Facebook ads - a user would have to do more than simply install ublock to block those ads, no?

Users are not supposed to do anything special. So far it appears the current filter is working, until people starts to report that it does not, in which case this will have to be looked into.

**Comment by taliarbel** [comment]
well, for example for me, after downloading ublock to both firefox and chrome, i still see in-feed facebook ads today. i've not made any changes to the default version.

**Comment by gorhill** [comment]
>  i still see in-feed facebook ads today

If one installs for the first time, the filter lists might not be up to date. They will update on their own within one hour, or you can force an update by visiting the _"3rd-party filters"_ pane and clicking _"Update now"_.

**Comment by taliarbel** [comment]
Magic! Thanks. This discussion has been helpful. Again, if any of you would want to talk about the process behind this in more detail, I'm always available - tarbel@ap.org and at 212-621-7629.  @gorhill, how do you extend the blocker capabilities? Are you limited in what you can do by the fact that you're not running an entire browser itself?

**Comment by dexiz** [comment]
@taliarbel
You would want to hear directly from gorhill, but it is hard for everyone to reveal one's weakness publicly.

In my opinion, any adblock browser extensions shares the limitation: video ads. Why is it so easy to remove facebook sponsored ads? Because this is about **element hiding**. If element hiding is the matter, one can write a javascript code to block them, and if something is possible with javascript, it can be implemented to blockers.
This is also why many anti-adblock solutions fail. Most of them relying on detecting hidden elements, which can simply nullified by un-hiding them.

Video ads are different. This is about **url blocking**, among two things that blockers do. Video ads can't just be hidden via element hiding rules as otherwise it will hide the main video too. Also, video ads are more closely related to the main content, so it's possible to make it hard to distinguish ads and the main content, or it can stop users if the video ads content is not downloaded to the browser, to which you can even use [Subresource Integrity](https://www.w3.org/TR/SRI/).
Currently there are some anti-adblock solutions which detects **url blocking**, but they all try to load some stuffs that are not necessarily needed to the browser so it can just be unblocked, or they uses a separate script for it which can be blocked by some blockers like ubo.
Think about hulu.com - it has claimed long before that their video ads are unblockable, and it is still true.

**Comment by collinbarrett** [comment]
Facebook must have changed something recently. I am seeing sponsored posts again in my timeline as of a couple days ago. Here's a screenshot. I am using uBlock Origin's Wiki "Hard Mode" with a few additional lists as well as Reek's AAK userscript.

![pic_censored](https://cloud.githubusercontent.com/assets/6483057/21296643/2968388e-c536-11e6-98a5-29f8967565ab.jpg)

**Comment by gorhill** [comment]
Do the filters suggested at <https://github.com/uBlockOrigin/uAssets/issues/233> works?

**Comment by IOUTODAY** [comment]
Mr. Hill,
 
Would you consider working with me to develop an open source version of this for the mass - meaning marketing to mothers and fathers - I am a non-profit that wants to be a path to families to help keep their familes experiences on line a pure as possible.
 
Thanks for any consideration.
 
JD Grant
 
Founder/CEO, IOU, Inc.

 
IOUToday.org
 
jd@ioutoday.org
404-721-6940
IOU is a 501c3 non-profit based in Georgia.



 
 
--------- Original Message --------- Subject: Re: [uBlockOrigin/uAssets] facebook.com (#98)

**Comment by karbassi** [comment]
@gorhill Can confirm that #233 works until FB changes things again.

**Comment by IOUTODAY** [comment]
Mr. Hill,
 
Would you consider working with IOU on a version of uBlock or other open source apps - we are a non-profit that wants to help families protect their privacy and redefine their digital life.
 
Please check us out at - IOUToday.org - if nothing else would you consider helping/advising me on getting  a project started to develop the various open source projects we feel are needed for families world wide?
 
Thanks in advance and I hope we can work together soon.
 
All the best,
 
JD Grant
 
--------- Original Message --------- Subject: Re: [uBlockOrigin/uAssets] facebook.com (#98)
