### ISSUE TITLE
walterfootball.com

### ISSUE THREAD

**Issue by thinksheiscool** [uBlockOrigin/uAssets#9804]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://walterfootball.com/index.php`

### Describe the issue

Placeholder + blocked video player.

### uBlock Origin version

1.37.2

### Browser name and version

Google Chrome 92.0.4515.159 (Official Build) (64-bit)

### Settings

![image](https://user-images.githubusercontent.com/89113298/130167784-7bbd4e0d-7433-44e7-a949-d766cd31d073.png)
![image](https://user-images.githubusercontent.com/89113298/130167770-6da9b10c-d5cd-4bbe-a9c6-2242e13c2d80.png)
![image](https://user-images.githubusercontent.com/89113298/130167813-4389e7a1-8de5-420d-9190-6128b12ae6e2.png)

### Notes

I was looking for anti adb from https://github.com/AdguardTeam/AdguardFilters/issues/88868

**Comment by uBlock-user** [comment]
> blocked video player.

how does this video player look like ?

**Comment by thinksheiscool** [comment]
> > blocked video player.
> 
> how does this video player look like ?

Have you disabled uBO on the webpage?

**Comment by uBlock-user** [comment]
Don't see any video player after disabling. Post a screenshot.

**Comment by thinksheiscool** [comment]
![image](https://user-images.githubusercontent.com/89113298/130248608-0d0b80d6-06d7-4d7b-86ac-b6c033187b49.png)

**Comment by thinksheiscool** [comment]
@uBlock-user Have you tried with a US IP?

**Comment by uBlock-user** [comment]
That's an ad video, not a website video, blocked by EasyList as a result.

**Comment by uBlock-user** [comment]
Report placeholders to EasyList.

**Comment by thinksheiscool** [comment]
@uBlock-user
- While it may have advertising, it still contains a video which looks like is related to WalterFootball.
- I don't think EasyList will address anything on this page (if there is any anti adblocking mechanism).

**Comment by uBlock-user** [comment]
> While it may have advertising, it still contains a video which looks like is related to WalterFootball.

It's from `aniview.com` which produces video ads content very specific to site's content, but still an ad.
