### ISSUE TITLE
tech.hindustantimes.com/gaming

### ISSUE THREAD

**Issue by thinksheiscool** [uBlockOrigin/uAssets#9805]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://tech.hindustantimes.com/gaming`

### Describe the issue

Ad leftovers/placeholders.
I decided to report this here because of a filter from uBlock Origin's 'uBlock filters'.
![image](https://user-images.githubusercontent.com/89113298/130170024-fb8493d8-cc59-4e22-89ae-78d11ea17b47.png)

### uBlock Origin version

1.37.2

### Browser name and version

Version 92.0.4515.107 (Official Build) (64-bit)

### Settings

![image](https://user-images.githubusercontent.com/89113298/130170058-4a8483b7-8349-4029-bc84-5ed3ca9cdf3f.png)

**Comment by Mennaruuk** [comment]
Let me take my first dig at filters, anyone feel free to add better ones:
```
tech.hindustantimes.com##.min-adsheight-250
tech.hindustantimes.com##.header-ad
```
