### ISSUE TITLE
independent.co.uk placeholder

### ISSUE THREAD

**Issue by ghost** [uBlockOrigin/uAssets#9807]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.independent.co.uk/us`

### Describe the issue

space

### uBlock Origin version

1.37.2

### Browser name and version

Google Chrome 92.0.4515.159 (Official Build) (64-bit)

### Settings

![image](https://user-images.githubusercontent.com/89113298/130172983-accc65de-3005-41c4-bccb-10864268aee8.png)
![image](https://user-images.githubusercontent.com/89113298/130172973-cfdb5c89-8ebe-49d2-bc6c-fce2fc166970.png)

**Comment by Mennaruuk** [comment]
![image](https://user-images.githubusercontent.com/52135169/130180151-2afa5b27-faa9-4e7f-bfd2-137f14b8f89d.png)

**Comment by mapx-** [comment]
@PIZZA90 

test

```
@@||pubmatic.com^$frame,script,domain=independentespanol.com
independentespanol.com##[class^="TopBanner"]
independentespanol.com###taboola-below-article-1
```

could be necessary refreshing twice the page

**Comment by mapx-** [comment]
Test

```
@@||pub.pixels.ai/wrap-independent-prebid-lib.js$script,domain=independent.co.uk
@@||static.adsafeprotected.com/iasPET.1.js$script,domain=independent.co.uk
```

**Comment by mapx-** [comment]
- eng is working fine on my end. just some delay
- for the spanish try:
```
@@||static.adsafeprotected.com/iasPET.1.js$script,domain=independentespanol.com
@@||permutive.app/*web.js$script,domain=independentespanol.com
@@||cdn.permutive.com^$xhr,domain=independentespanol.com
@@||api.permutive.com^$xhr,domain=independentespanol.com
```

**Comment by garry-ut99** [comment]
> eng is working fine on my end. just some delay

For me:
- on Firefox doesn't work at all, no matter F5 or CTRL + F5
- on Opera works only when CTRL + F5, and never when F5
- with uBO disabled, works on both Firefox & Opera wit  F5 being sufficient

**Comment by mapx-** [comment]
test

`independent.co.uk##+js(no-fetch-if, doubleclick)`

**Comment by garry-ut99** [comment]
Works.

**Comment by Yuki2718** [comment]
Is this about the video? Doesn't work even with blocker disabled.

**Comment by mapx-** [comment]
`pixels` is already whitelisted by [spa: EasyList Spanish](moz-extension://230da6df-3db3-4965-80cb-7d4b6f8405ca/asset-viewer.html?url=spa-0)

**Comment by stephenhawk8054** [comment]
> ~Is this about the video? Doesn't work even with blocker disabled.~ On my end also have to allow `pub.pixels.ai/wrap-independent-no-prebid-lib.js` (ESP, blocked by EL `-prebid-`). Can you guys reproduce?

Mine's already allowed in EL, but video still could not start

![image](https://user-images.githubusercontent.com/66517106/222387116-8a45ef18-79c1-4545-a034-6ab65f4be538.png)

**Comment by mapx-** [comment]
did you add the filters above ?

```
@@||static.adsafeprotected.com/iasPET.1.js$script,domain=independentespanol.com
@@||permutive.app/*web.js$script,domain=independentespanol.com
@@||cdn.permutive.com^$xhr,domain=independentespanol.com
@@||api.permutive.com^$xhr,domain=independentespanol.com
```

**Comment by Yuki2718** [comment]
Yes, with them still need the exception.

**Comment by mapx-** [comment]
> pixels is already whitelisted by spa: EasyList Spanish

**Comment by Yuki2718** [comment]
> `pixels` is already whitelisted by `spa: EasyList Spanish`

Are, all right I only enabled AG Spanish.

**Comment by stephenhawk8054** [comment]
> did you add the filters above ?
> 
> ```
> @@||static.adsafeprotected.com/iasPET.1.js$script,domain=independentespanol.com
> @@||permutive.app/*web.js$script,domain=independentespanol.com
> @@||cdn.permutive.com^$xhr,domain=independentespanol.com
> @@||api.permutive.com^$xhr,domain=independentespanol.com
> ```

Oh right, I forgot. I thought they are already added :D But I also the `no-fetch-if` one

**Comment by mapx-** [comment]
add

`@@||googletagmanager.com/gtag/js$script,domain=independentespanol.com`

**Comment by mapx-** [comment]
@Yuki2718

**Comment by Yuki2718** [comment]
Something has changed since https://github.com/uBlockOrigin/uAssets/issues/9807#issuecomment-1450742935 ?

**Comment by Yuki2718** [comment]
@mapx- GTM is EP.

**Comment by Yuki2718** [comment]
> yeah something weird XD

Don't know why but on my end still works without allowing GTM. Weird indeed.

**Comment by Daxy7** [comment]
`https://www.independent.co.uk/news/world/americas/us-politics/trump-arrested-today-indict-stormy-daniels-manhattan-b2304990.html`

`jwplayer/pixels.ai` inline video not loading. Loads with `EasyList` disabled
