### ISSUE TITLE
yandex.com

### ISSUE THREAD

**Issue by adranger** [uBlockOrigin/uAssets#9810]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://yandex.com/images/search?text=cat`

### Describe the issue

Annoyance when you use the `Open` button to view an image.

### Screenshot(s)

![screenshot](https://user-images.githubusercontent.com/35470489/130197174-fd7d593d-4350-4036-bc3f-8061c8be8f26.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox stable

### Settings

Adguard Base + Annoyances + Portuguese + Russian + Social Media + Tracking Protection
uBlock Origin lists

**Comment by uBlock-user** [comment]
fixed in BitBlock - https://github.com/easylist/ruadlist/wiki/RU-Adlist-links

**Comment by adranger** [comment]
`yandex.com` is an international English-language site. Russian speakers use `yandex.ru`.

**Comment by uBlock-user** [comment]
Yandex is Russian with an option for English locale and maintained by @dimisa-RUAdList, report russian sites to him.

**Comment by adranger** [comment]
The `.com` domain is marketed to international users who are unlikely to be subscribed to Russian lists. Russian IPs are redirected to `yandex.ru`.

Anyway, the extended syntax is necessary because just hiding the modal has the below effect, so users still have to click twice (and this time without knowing it, since the modal `X` button is hidden):

>Not good enough. I can keep the nag message from appearing, and I do, but that doesn't solve the problem. Blocking the nag message just saves me the trouble of having to close it. But the result is that the first time I click the Similar Images button, it does nothing. I have to click it and then click it again before it will work.
> https://greasyfork.org/en/discussions/requests/78187-two-requests-for-yandex-searches

If getting around that event listener with uBlock Origin is too much trouble, it is better to leave the modal as it is.

**Comment by dimisa-RUAdList** [comment]
https://github.com/easylist/ruadlist/commit/874de0311880a9dbfdbc4dc4b6b519f080b499a2 > fixed in Counters

Counters: https://github.com/easylist/ruadlist/wiki/RU-Adlist-links

**Comment by uBlock-user** [comment]
If anybody is going to use Yandex(regardless of locale), it is expected to subscribe to RUAdlist and all the lists dimisa mentions for Yandex.
