### ISSUE TITLE
Instagram anti-login pop up no longer working

### ISSUE THREAD

**Issue by dezraj** [uBlockOrigin/uAssets#9812]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

Any public Instagram profile (it could be tested in private profiles too, but you will only see the notice "this account is private").

### Describe the issue

When using the "Annoyances -> uBlock filters - Annoyances" filter, the "Log in to view a profile" pop up is no longer blocked, therefore I cannot see public Instagram profiles without logging in a profile first.

I've tried both in Firefox and Chrome in Windows, and also in Firefox for Android. Sometimes if I change from a wi-fi connection to a mobile network it will bypass the log in pop up and load the page, but just for a brief time it seems. So I suspected it was related to cookies and deleted them all and also used a private tab, but it didn't work. Then maybe it's related to the IP address?

Anyway, I hope it could be fixed, otherwise I'll have to create an Instagram account myself, which is not a big deal, by the way.

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.1, Chrome 92.0.4515.159, Firefox for android 91.2.0

### Settings

All default settings, just enabled Annoyances -> uBlock filters - Annoyances filter.

**Comment by uBlock-user** [comment]
Works fine at `https://www.instagram.com/Disney/` Besure to test it on default settings + uBO Annoyances list enabled.

**Comment by uBlock-user** [comment]
Works fine at `https://www.instagram.com/Disney/` 

> All default settings, just enabled Annoyances -> uBlock filters - Annoyances filter.

Disable any other extensions you have enabled except uBO.

**Comment by dezraj** [comment]
> 
> 
> Works fine at `https://www.instagram.com/Disney/`
> 
> > All default settings, just enabled Annoyances -> uBlock filters - Annoyances filter.
> 
> Disable any other extensions you have enabled except uBO.

I have already. The issue persists. I've tried Disney's Instagram profile too, same results. As I said. I suppose it's related to IP address or cookies or something else, because I've checked quite a bunch of Instagram profiles lately and the ad-block has just started failing recently, so perhaps it's related to the number of times you can bypass the log in process? Anyway, thanks for your help!

**Comment by uBlock-user** [comment]
@dezraj Do you get redirected to a login page ?

**Comment by dezraj** [comment]
> 
> 
> @dezraj Do you get redirected to the login page ?

Yes, that's it. When the bypass fails it redirects me to https://www.instagram.com/accounts/login/ with an e-mail and password log in box (this is what I was calling "pop up" ad, sorry about the misunderstanding).

**Comment by uBlock-user** [comment]
Sorry, that's server-sided, no fix for that.
