### ISSUE TITLE
temporarymail.com

### ISSUE THREAD

**Issue by thinksheiscool** [uBlockOrigin/uAssets#9816]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://temporarymail.com/`

### Describe the issue

anti adb when attempting to change the address

### uBlock Origin version

1.37.2

### Browser name and version

Google Chrome 92.0.4515.159 (Official Build) (64-bit)

### Settings

![image](https://user-images.githubusercontent.com/89113298/130326634-6abeb21a-add4-4978-8ea1-34134204e99c.png)

### Notes

Discovered from https://github.com/AdguardTeam/AdguardFilters/issues/91911.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/55c73cd9082f45580d97bc171fa4ba71b203cdec
