### ISSUE TITLE
voxfilmeonline.biz pop-up

### ISSUE THREAD

**Issue by andreewmat** [uBlockOrigin/uAssets#9819]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://voxfilmeonline.biz/the-secret-diary-of-an-exchange-student-2021-online-hd-subtitrat/`

### Describe the issue

On the link from above, there is a red 'x' on every source from that movie.

### Screenshot(s)

![screen](https://user-images.githubusercontent.com/79897301/130334247-cd1daca6-8cb4-412b-856f-ac935fad8220.jpg)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.1

### Settings

Default filter lists

**Comment by sugarfreesweetener** [comment]
should/could filters for this issue be moved to `road-block lite` ?
