### ISSUE TITLE
smutindia.com ads [NSFW]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#982]
URL(s) where the issue occurs

https://www.smutindia.com/video/amateur-big-boob-desi-gf-xxx-porn-videos-iJuuqL5VHb3.html

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
"normal" filters, add as custom filters (in "my filters"
```
||smutindia.com^*banners$image
||smutindia.com^*.gif$image
```

**Comment by KiLL4FuNK** [comment]
ADS

**Comment by okiehsch** [comment]
The filters mapx- suggeested still work on my end.
