### ISSUE TITLE
bt.dk

### ISSUE THREAD

**Issue by AndnixSH** [uBlockOrigin/uAssets#9821]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.bt.dk/superligaen/en-hotdog-han-husker-den-blev-jo-spraengt-i-luften`

### Describe the issue

Adblock warning in danish

### Screenshot(s)

![image](https://user-images.githubusercontent.com/88159598/130353607-d8b74068-07c6-4f72-af32-155a06e3b95f.png)

### uBlock Origin version

1.37.2

### Browser name and version

Chrome 92.0.4515.107

### Settings

Default

**Comment by okiehsch** [comment]
@DandelionSprout 
`@@||fwmrm.net/ad/*$script,domain=viafree.dk`
works for me.

**Comment by uBlock-user** [comment]
@okiehsch Doesn't `@@||bt.dk/build/prebid-ads-$script,1p` work ?

**Comment by okiehsch** [comment]
No, the anti adblock message is shown  directly in the videoframe on my end.
`https://www.viafree.dk/embed/sport/id/09c202bd-385e-4e38-ba7a-a8c1417ae501?autoplay=true`

**Comment by okiehsch** [comment]
The `bt.dk/build/prebid-ads-` request can stay blocked, it makes no difference.

**Comment by uBlock-user** [comment]
I thought the player was first-party, nvm.

**Comment by DandelionSprout** [comment]
Of all possible things, it was `||freewheel-mtgx-tv.akamaized.net^` in EasyList Lithuania that caused the AAB message on my end, which I've fixed now.

**Comment by okiehsch** [comment]
How can a blocking filter in EasyList Lithuania cause an anti adblock message for the OP, or me for that matter?
I assume the OP has not enabled that list and I certainly don't have.

**Comment by DandelionSprout** [comment]
Good question, because I don't receive the AAB message when EasyList Lithuania is turned off.

**Comment by okiehsch** [comment]
Well, OK, I have fixed it in uAssets.

**Comment by DandelionSprout** [comment]
On further inspection, the reason I don't receive the AAB, was because I have AdGuard Base turned on, which contains `@@||v.fwmrm.net/ad/g/1$domain=viafree.dk|viafree.fi|viafree.no|viafree.se`

This means that https://github.com/uBlockOrigin/uAssets/commit/492eacc2597bc0d562371b853ec7b7dff2101def is by all signs a valid fix.

**Comment by okiehsch** [comment]
So, will you add it the danish list?

**Comment by DandelionSprout** [comment]
I guess I can just as well do that. Give me 3min.
