### ISSUE TITLE
Megaup.net adblocker

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#9822]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://megaup.net/2hFwf/KMSpico_10.2.0.kuyhAa.7z

### Describe the issue

After loading to download. the word change to adblock detected

### uBlock Origin version

Ublock Lastest

### Browser name and version

Chrome lastest

### Settings

-

**Comment by SakhJack** [comment]
<details><summary>It's back</summary>

`https://megaup.net/1ELxa/adblocktest.txt`
![image](https://user-images.githubusercontent.com/10335530/132117594-3dcae070-eaa5-4330-9de2-b94221707449.png)
</details>

**Comment by uBlock-user** [comment]
force update ublock filters list.

**Comment by SakhJack** [comment]
ah it was 3rd party filter fault, need to allow `jsc.adskeeper.co.uk` and `servicer.adskeeper.co.uk`

**Comment by uBlock-user** [comment]
Stick to default lists/settings, that ad-server has already been allowed in the filter list.
