### ISSUE TITLE
pornxp.com redirecting [NSFW]

### ISSUE THREAD

**Issue by gemoshi07** [uBlockOrigin/uAssets#9830]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://pornxp.com/videos/15009092322`

### Describe the issue

When I play the video from the link above, I get redirected to a new window. 

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91

### Settings

N/A

**Comment by uBlock-user** [comment]
Redirection is done via popups...the main issue is the popups.

**Comment by gemoshi07** [comment]
> Redirection is done via third-party popups...the main issue is the popups.

Yes, there is a popup after I press the play buttom, not a redirection, my bad. Can be fixed?

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/88d25eef8d51ddee3ac8ee57943cce44e26f9ab7
https://github.com/uBlockOrigin/uAssets/commit/8b7a6cd4ab9bd604f9a494aefe977026df43bd77
https://github.com/uBlockOrigin/uAssets/commit/9a199eefe515c1d58bda3ccf975e8aec1e336e62
