### ISSUE TITLE
up-load .io timer defuse

### ISSUE THREAD

**Issue by cantunborn** [uBlockOrigin/uAssets#9832]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://up-load.io/trh4str3nfza`

### Describe the issue

Timer not defused.

### uBlock Origin version

1.37.2

### Browser name and version

Chrome 92.0.4515.159

### Settings

All lists except regional.

### Notes

This worked: `up-load.io##+js(nano-stb, , , 0.02)`

**Comment by uBlock-user** [comment]
![Capture](https://user-images.githubusercontent.com/21290713/130654797-8a7b6922-51ab-413c-acce-d87d2488b5d0.PNG)

**Comment by cantunborn** [comment]
Strange, worked for me for the first time but showed this message on the next time. Is this server-side or client-side?

**Comment by uBlock-user** [comment]
Server-sided countdowns can detect what uBO does, so the download will never occur. A server-sided countdown is typically longer than 10 secs.

**Comment by uBlock-user** [comment]
Server-sided runs concurrently with client-sided countdown, so a sped up client-sided countdown won't match the server-sided countdown, so the download will never occur. A server-sided countdown is typically longer than 10 secs.

**Comment by cantunborn** [comment]
I was testing the filter so I might have let it run for the whole 30 seconds, makes sense it worked due to that.
