### ISSUE TITLE
Something in EasyList is blocking content on ZDNET's All About Microsoft page

### ISSUE THREAD

**Issue by jmwoods301** [uBlockOrigin/uAssets#9834]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.zdnet.com/blog/microsoft/`

### Describe the issue

Content under Latest Posts is blocked when EasyList is checked.

Unchecking EasyList displays the blocked content.

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.02 and Edge 92.0.902.78

### Settings

Unchecked EasyList.

### Notes

Unchecking EasyList resolves the issue.

**Comment by okiehsch** [comment]
@ryanbr 
`zdnet.com#@#.sponsoredItem`
fixes the issue.
