### ISSUE TITLE
bestsimsmods.com - Anti-Adblock

### ISSUE THREAD

**Issue by JlNX** [uBlockOrigin/uAssets#9842]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://bestsimsmods.com/`

### Describe the issue

The site throws up
##section > div
##p > ins > div

And it blocks being able to interact with the site. Blocking the element is temporary. The site will generate more "div". The site still allows scrolling.

### uBlock Origin version

1.37.2

### Browser name and version

Google Chrome 84.0.4147.105

### Settings

Using custom list https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

**Comment by FanOfRootBeer** [comment]
anti-ad-blocking

maybe `/wp-content/themes/soledad/js/detector.js?ver=8.3.1` ?
