### ISSUE TITLE
nanimex.com

### ISSUE THREAD

**Issue by What-Zit-Tooya** [uBlockOrigin/uAssets#9845]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://nanimex.com/episode/yugioh-duel-monsters-episode-011`

### Describe the issue

Ads when click play button

### Screenshot(s)

![1](https://user-images.githubusercontent.com/9832875/131216420-b4a9c796-e5ba-4ed4-b1f8-0175d2de32b1.png)

### uBlock Origin version

1.37.2

### Browser name and version

91.0.2

### Settings

- Default
- AdGuard Annoyances
- EasyList Cookie
- uBlock filters – Annoyances
- IDN, MYS: ABPindo
- AdBlockID

### Notes

Tested on Firefox Android too, it also show ads

**Comment by uBlock-user** [comment]
I only see ads on the site, for which filters are --

```
||img.topddl.net^$image,domain=nanimex.com
||nanime.biz^$3p
nanimex.com##.iklan-tengah
```

Report these to the regional list -- https://github.com/ABPindo/indonesianadblockrules/issues

**Comment by uBlock-user** [comment]
@gmarcher
