### ISSUE TITLE
anydebrid.com - anti-adblock

### ISSUE THREAD

**Issue by SwiftWinds** [uBlockOrigin/uAssets#9849]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://anydebrid.com/

### Describe the issue

1. visit https://anydebrid.com/
2. put any link in the big textbox (e.g., https://anydebrid.com/)
3. press generate
4. observe anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/12981958/131266221-5aa90685-f15c-4b87-839f-054596d596f0.png)

### uBlock Origin version

1.37.2

### Browser name and version

Chrome 92.0.4515.159

### Settings

Default

**Comment by SwiftWinds** [comment]
Thanks! :)

**Comment by dumbusernameidk** [comment]
anti-adblock again.

**Comment by stephenhawk8054** [comment]
There's a new anti-adblock again. Put any link (e.g `https://www.fshare.vn/file/5LBICXFY97WP`) to the box then there's this screen
![image](https://user-images.githubusercontent.com/66517106/135236803-cda618a2-96e9-42c9-9ce9-f2e46b8bed14.png)
Whitelisting this filter helps it:
`anydebrid.com#@#.adsbygoogle:style(position:absolute !important;left:-9999px !important)`

**Comment by stephenhawk8054** [comment]
The anti-adblock appears again when putting any links to the box. Looks like the script with the domain `main.exoclick.com` is a bait one. When I clicked on the link, it just returned 404 error.

Proposed filter:

`@@||main.exoclick.com^$script,domain=anydebrid.com`
