### ISSUE TITLE
sintelevisor.com [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#985]
URL(s) where the issue occurs

http://www.sintelevisor.com/tv/nickelodeon.html

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by mapx-** [comment]
see if works
```
livesports.pw##script:inject(fuckadblock.js-3.2.0)
@@||cinestrenostv.tv^$generichide
||cinestrenostv.tv/*ad$image,redirect=1x1-transparent.gif
||pop.verplusonline.com
```

**Comment by okiehsch** [comment]
`||livesports.pw/adblock.js$script,first-party,redirect=fuckadblock.js-3.2.0` instead of the `script:inject`
works on my end.

**Comment by KiLL4FuNK** [comment]
Pop-up PLAY VIDEO

`http://www.sintelevisor.com/tv/espn.html`
