### ISSUE TITLE
kiss-cartoon.tv

### ISSUE THREAD

**Issue by IMayKnow** [uBlockOrigin/uAssets#9850]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://kiss-cartoon.tv/episode/family-guy-season-3-episode-1/`

### Describe the issue

After I clicked on the play symbol, I encountered a popup.

### uBlock Origin version

1.37.2

### Browser name and version

Google Chrome 92.0.4515.159 (Official Build) (64-bit)

### Settings

![image](https://user-images.githubusercontent.com/89752791/131267882-de9ca8ed-aa0b-423c-8cac-6c31d1b06a6b.png)

**Comment by uBlock-user** [comment]
Error 524 

Site is timing out.
