### ISSUE TITLE
streameast.live redirects to anti adblock page

### ISSUE THREAD

**Issue by craigchis** [uBlockOrigin/uAssets#9853]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.streameast.live/

### Describe the issue

When loading any page on streameast.live, it redirects to streameast.live/ab

### uBlock Origin version

1.37.2

### Browser name and version

Chrome 92.0.4515.159

### Settings

All defaults

**Comment by Yuki2718** [comment]
https://github.com/uBlockOrigin/uAssets/commit/b4a51fd86ed8469baabd3b0d8a10a54d5dbb9666
Force update filter lists and check again.

**Comment by craigchis** [comment]
Fixed, thanks!
