### ISSUE TITLE
movie website pop-up appear

### ISSUE THREAD

**Issue by andreewmat** [uBlockOrigin/uAssets#9854]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://voxfilmeonline.biz/ghost-in-the-graveyard-2019-film-subtitrat-in-romana-hd/#`

### Describe the issue

On the server 2 after I press the play button a pop-up appear.

### Screenshot(s)

N/A

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.2

### Settings

Default settings

**Comment by andreewmat** [comment]
@okiehsch Also on this [link](https://voxfilmeonline.biz/scary-stories-to-tell-in-the-dark-2019-online-hd-in-romana/) I see the same issue on Server 2 after that I press play.

**Comment by okiehsch** [comment]
I can't reproduce.

**Comment by andreewmat** [comment]
> I can't reproduce.

A purge cache fixed. Thanks again for the help!
