### ISSUE TITLE
elahmad.com detects adblock

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#9855]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.elahmad.com/tv/aljazeera.htm`
`http://www.elahmad.com/tv/qurantv.php`
`http://www.elahmad.com/tv/sunnatv.php`

### Describe the issue

Elahmad.com detects adblock. I enabled Liste AR filter list, but it didn't help.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/131419583-938c05d1-513a-4800-b8a1-57668c1c3ddc.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.2

### Settings

- enabled Liste AR

### Notes

This overlay also appears:
![image](https://user-images.githubusercontent.com/52135169/131419634-45274cb2-01b2-443a-bd70-8662b99703f7.png)

**Comment by Mennaruuk** [comment]
@okiehsch hey! I found another link where site detects content blocker and prompts that overlay with a white X, may you please take a look at it? Thanks!

`https://www.elahmad.com/tv/live/sl.php?id=alfallujah_tv`

![image](https://user-images.githubusercontent.com/52135169/133004785-13a9ef2c-b0d5-4c5b-bb31-4465dc65e162.png)

**Comment by Mennaruuk** [comment]
@okiehsch hey! I found more, the site keeps finding new ways to avoid detection:

1. Go to this site: `http://www.elahmad.com/tv/mbc.php?autoplay=1`
2. Click on any of the channels on the left side of the screen

![image](https://user-images.githubusercontent.com/52135169/139604223-cb86c345-a13d-4edf-9d33-e6db2d47e5da.png)

Another link: `http://www.elahmad.com/tv/alsharqiyatv.php`

Another link: `http://www.elahmad.com/tv/watchtv.php?id=mbc2tv`

Also: site disallows right clicking.

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/3f74896b8424089eb1daf8cce3aa9ebd15394203

**Comment by mapx-** [comment]
no anti adb on my side, but the streaming was broken => the first commit above fixes it
