### ISSUE TITLE
Tutanota website not working at all!

### ISSUE THREAD

**Issue by DodoLeDev** [uBlockOrigin/uAssets#9859]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://tutanota.com/*`

### Describe the issue

The _JavaScript language scripts_ on the Tutanota website are **blocked** by uBlock Origin, which leaves the user **with a blank page.**

### Screenshot(s)

*Tutanota shows a blank page, and some contents from the website have been blocked*
![firefox_po6XpqMxyt](https://user-images.githubusercontent.com/59477313/131422662-6d275e04-af1f-401c-9fd5-ad0238075fa7.png)

---

*A script has been blocked...*
![firefox_b2ckljkAHV](https://user-images.githubusercontent.com/59477313/131422784-fdbebc11-f6ee-4714-b0fa-d59b4e3002dd.png)

---

*Blocked request details*
![firefox_aaPOCbxAMr](https://user-images.githubusercontent.com/59477313/131422942-e6c22288-83ef-42fc-b397-bb0ef2e698a2.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox Nightly 93.0a1 (2021-08-30) (64 bits)

### Settings

None.

### Notes

That seems to be caused by the default uBlock Origin filter, then fixes have to be made from there.

**Comment by uBlock-user** [comment]
Site loads fine, do I need to login to reproduce ?

**Comment by gwarser** [comment]
French UI? I see `https://tutanota.com/en.js` not blocked.

**Comment by DodoLeDev** [comment]
Yep, French UI

**Comment by okiehsch** [comment]
Should work now if you update the `uBO-unbreak` list.

**Comment by DodoLeDev** [comment]
### **It works !!** 🥳

Thanks a lot! 🙏

![image](https://user-images.githubusercontent.com/59477313/131508414-5e556682-69e1-40d7-90e6-c7ecb342a41e.png)
