### ISSUE TITLE
ddmix.net ADS

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#986]
URL(s) where the issue occurs

https://ddmix.net/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
ADS @mapx-

**Comment by xDarkARG** [comment]
@mapx- Pop-up

**Comment by KiLL4FuNK** [comment]
@mapx- ADS Anti-Adblock

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters
