### ISSUE TITLE
UK Sainsbury's Sponsored content

### ISSUE THREAD

**Issue by fugkco** [uBlockOrigin/uAssets#9864]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.sainsburys.co.uk/shop/favourites-as-list`

### Describe the issue

There are sponsored content items in the favourites list.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/59912404/131559776-deba55cc-cdc4-4db1-a76e-de03ec33446a.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 90

### Settings

N/A

### Notes

Below filter removes sponsored content. I'm reporting it so it can be shared with the community. Not sure which list it would go under!

```
www.sainsburys.co.uk##li:has(.product-header:contains(Sponsored))
```

**Comment by uBlock-user** [comment]
Redirects to `https://account.sainsburys.co.uk/gol/login?login_challenge=585a6fff10d045e4baf2d28905de7c19`

**Comment by fugkco** [comment]
Yes, it's only available for logged in users.

**Comment by uBlock-user** [comment]
Will address the issue when the login credentials are provided.
