### ISSUE TITLE
foropolicia.es ADS

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#987]
URL(s) where the issue occurs

https://www.foropolicia.es/examenes-oficiales-t14137.html

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by okiehsch** [comment]
````
||netpol.es^$subdocument,domain=foropolicia.es
foropolicia.es##.content > a[href^="/publicidad.php"] > table
````
