### ISSUE TITLE
downloadcenter.intel.com now redirects to intel.com

### ISSUE THREAD

**Issue by stm-x** [uBlockOrigin/uAssets#9871]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`downloadcenter.intel.com`

### Describe the issue

There is a rule in the annoyance filter.
I don't know if I need that filter.
I simply thought you should know.

### uBlock Origin version

N/A

### Browser name and version

N/A

### Settings

N/A

**Comment by ghajini** [comment]
what's the exact issue?

**Comment by stm-x** [comment]
It's not that there was a problem with the site.
I just wanted to let you know that this filter is no longer in use and needs to be updated or removed.
https://github.com/uBlockOrigin/uAssets/blob/dd3066e60a0b67d8e12203033d95da1f41b83d2d/filters/annoyances.txt#L2073
