### ISSUE TITLE
menrec.com

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#9874]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://menrec.com/donor-dashboard`

### Describe the issue

Ads are showing at the bottom of articles.

### Screenshot(s)
<details><summary>Screenshot (a little NSFW):</summary>

![image](https://user-images.githubusercontent.com/52135169/131603365-5cfb44f4-5525-4c98-bade-a96cc32c3215.png)

</details><br/>

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.2

### Settings

N/A

### Notes

N/A

**Comment by Mennaruuk** [comment]
At least with the bottom ones, I think they can be blocked with the following:

`menrec.com##.r224wc9l9`

Right-hand side ads are more challenging.

**Comment by uBlock-user** [comment]
```
menrec.com##+js(nosiif, offsetHeight)
menrec.com##+js(acis, document.createElement, onload)
*$script,redirect-rule=noopjs,domain=menrec.com
```

Defuses Yavli shit.
