### ISSUE TITLE
mydailyfreedom.com

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#9875]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://mydailyfreedom.com/640-afghans-usc17`

### Describe the issue

Ads on right-hand side halfway through the page.

### Screenshot(s)

![Screenshot 2021-08-31 at 23-13-32 640 Afghans Packed Inside A US C-17 Trying To Escape The Taliban](https://user-images.githubusercontent.com/52135169/131605831-146641ee-e7af-4e79-9760-a2f436031bb7.jpg)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.2

### Settings

N/A

### Notes

N/A

**Comment by uBlock-user** [comment]
To be fixed in EasyList.

**Comment by uBlock-user** [comment]
`mydailyfreedom.com##.ai_widget`
