### ISSUE TITLE
kawarthanow.com

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#9876]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://kawarthanow.com/2021/08/26/most-new-covid-19-cases-in-peterborough-among-unvaccinated-people-under-30`

### Describe the issue

Ad placeholders.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/131607285-b61fe7c6-243f-49e2-a605-f6d1bf480237.png)

![image](https://user-images.githubusercontent.com/52135169/131607344-17430ca3-9697-4c3e-910e-fcba4c23e914.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.2

### Settings

N/A

### Notes

N/A

**Comment by Mennaruuk** [comment]
`kawarthanow.com###td-post-content > div`
`kawarthanow.com##p.custom_divider:nth-of-type(13)`
`kawarthanow.com##p.custom_divider:nth-of-type(12)`

(Hoping the dividers aren't used for other articles for non-advertising purposes.)

**Comment by uBlock-user** [comment]
```
kawarthanow.com##div.gpt-container
kawarthanow.com##div[style="margin: 0 auto;width:100%;text-align:center;"]
kawarthanow.com##p.custom_divider
```

To be fixed in EasyList. Report there.

**Comment by huyszn** [comment]
The site detects uBO (https://github.com/uBlockOrigin/uAssets/assets/46979193/c0d50f0e-e4fe-44c4-984f-c653a2850e0b).

This filter seems to work to stop the detection.
`kawarthanow.com##+js(nosiif, daadb)`
