### ISSUE TITLE
puromarketing.com ADS

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#988]
URL(s) where the issue occurs

http://www.puromarketing.com/42/29627/millonarios-ingresos-reyes-youtube.html

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by okiehsch** [comment]
`||puromarketing.com//modules/pinpan/inc_ifra.php?$subdocument`
