### ISSUE TITLE
pctechmag.com

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#9880]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://pctechmag.com/2021/08/jumia-centenary-bank-to-promote-online-card-payments`

### Describe the issue

Ads are not being blocked.

Additionally, once one reaches the end of the page, there is this overlay that slides in from the right.

### Screenshot(s)

<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/52135169/131610018-e7bca172-f878-419b-8cf4-9ec3e01b78cc.png)

</details><br/>

<details><summary>Screenshot 2:</summary>

![image](https://user-images.githubusercontent.com/52135169/131610233-e8ec40fd-d4e7-4869-a948-b4f726a9b2bd.png)

</details><br/>

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.2

### Settings

N/A

### Notes

N/A

**Comment by Mennaruuk** [comment]
`pctechmag.com##.theiaStickySidebar > .widget_media_image.widget.container-wrapper`
`||pctechmag.com/wp-content/uploads/2021/08/yellow-card-2.gif$image`
`pctechmag.com##.show-check-also.check-also-right.container-wrapper` (sliding overlay at bottom)
`pctechmag.com##.theiaStickySidebar > .text-html.widget.container-wrapper` (right-hand side _Advertisements_ section)

**Comment by uBlock-user** [comment]
```
pctechmag.com##[href^="//sharzconsults.com/"]
pctechmag.com##.theiaStickySidebar > .text-html.widget.container-wrapper
```

To be fixed in EasyList.
