### ISSUE TITLE
1001tracklists.com adblock warning message

### ISSUE THREAD

**Issue by tommy8372** [uBlockOrigin/uAssets#9881]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.1001tracklists.com/dj/oliverheldens/index.html`

### Describe the issue

When you click on any tracklist it shows warning message to disable adblock. Happens like every 30 minutes and first time you visit the page.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/155648/131653598-0fd01830-f08e-432e-b13e-73570a642d67.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.2

### Settings

added filter lists: uBlock, AdGuard, Fanboy filter annoyances; CZE, SVK: EasyList

**Comment by uBlock-user** [comment]
Last solution filter still works, reset back to default settings + disable all other extensions

**Comment by uBlock-user** [comment]
Seems to be occuring randomly on Chromium, Firefox is fine.

**Comment by tommy8372** [comment]
thank you

**Comment by uBlock-user** [comment]
They're changing the CSS selectors so unsure as to how long will this last.

**Comment by okiehsch** [comment]
Um, I did not fix the anti adblock message, atleast not intentionally because I only got it one time and can't reproduce since.
I simply blocked some ads.

**Comment by uBlock-user** [comment]
Blocking those ads will also be used as the cause to trigger the overlay modal.
