### ISSUE TITLE
dramacool download links blocked

### ISSUE THREAD

**Issue by greatagnostic** [uBlockOrigin/uAssets#9882]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://dramacool.pe/the-priceless-2021-episode-3.html`

### Describe the issue

Can't access download links

### Screenshot(s)

![Screenshot_20210901-180120](https://user-images.githubusercontent.com/89909437/131653531-84cf22cc-3d3b-42c4-bd0d-070c017089ee.png)

### uBlock Origin version

1.37.2

### Browser name and version

91.4

### Settings

Unchecked adguard mobile ads 
Unchecked Peter ads

### Notes

It will automatic blocked download link while using ublock.

**Comment by uBlock-user** [comment]
force update ublock filters list.

**Comment by greatagnostic** [comment]
> force update ublock filters list.

![Screenshot_20210901-182555](https://user-images.githubusercontent.com/89909437/131655927-b4cf4d99-270e-4547-94b4-93a7200940a2.png)

**Comment by uBlock-user** [comment]
Click on the clock icon and then the update button besides it.

**Comment by greatagnostic** [comment]
> Click on the clock icon and then the update button besides it.

Still didn't work 
![Screenshot_20210901-183107](https://user-images.githubusercontent.com/89909437/131656792-d1035bb2-bed9-4818-ab11-8044cb3cf980.png)

**Comment by uBlock-user** [comment]
Reset to default settings.

**Comment by okiehsch** [comment]
I don't get the issue.
You say
`Can't access download links`
The site states 
`For downloading this video, please login first.`
So are you logged in?

**Comment by greatagnostic** [comment]
> Reset to default settings.

Didn't work

**Comment by uBlock-user** [comment]
Fixed iframe video server download button 2-3 days ago, so I don't know whats on your side causing this. Now you will have to being investigating the cause on your own.

**Comment by greatagnostic** [comment]
> I don't get the issue.
> You say
> `Can't access download links`
> The site states
> `For downloading this video, please login first.`
> So are you logged in?

You don't need to login
Just click the download icon

**Comment by okiehsch** [comment]
> Just click the download icon

![image](https://user-images.githubusercontent.com/16838044/131659763-24164a22-d9c4-4f39-8a04-4d8eb4b2845f.png)

**Comment by greatagnostic** [comment]
> > Just click the download icon
> 
> ![image](https://user-images.githubusercontent.com/16838044/131659763-24164a22-d9c4-4f39-8a04-4d8eb4b2845f.png)

I can't proceed or access that.site by using dramacool download icon link

**Comment by greatagnostic** [comment]
Thanks alot  it.works now ☺️☺️☺️
