### ISSUE TITLE
gab.com

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#9887]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://gab.com/explore`
`https://gab.com/timeline/pro`

### Describe the issue

Gab.com has implemented Facebook-style sponsored ads in timeline.

### Screenshot(s)

<details><summary>Screenshot 1:</summary>

![Screenshot 2021-09-01 at 17-51-16 Explore Gab Social](https://user-images.githubusercontent.com/52135169/131750345-98cea2d2-f742-453d-aca2-33e309a01a0a.png)

</details><br/>

<details><summary>Screenshot 2:</summary>

![Screenshot 2021-09-01 at 17-51-31 Explore Gab Social](https://user-images.githubusercontent.com/52135169/131750363-836ab64a-1fae-43ec-bc07-b120cb40a764.png)

</details><br/>

<details><summary>Screenshot 3:</summary>

![Screenshot 2021-09-01 175232_censored](https://user-images.githubusercontent.com/52135169/131750834-2f32be4e-24e7-4c57-9c3c-0e80fdd372b3.jpg)

</details><br/>

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.2

### Settings

N/A

### Notes

Requires login.

**Comment by uBlock-user** [comment]
Second and Third screenshots are self promos won't get addressed in uBO, will go in external Annoyances list.

**Comment by uBlock-user** [comment]
`gab.com##div[class] > span[class]:has-text(Sponsored):upward(5)`

Test @Mennaruuk

**Comment by Mennaruuk** [comment]
Tested. Works well. Thanks.
