### ISSUE TITLE
maxedtech.com

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#9894]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://maxedtech.com/how-to-enable-or-disable-secure-boot`

### Describe the issue

Site detects content blocker.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/131780601-e3876a0a-756e-4be9-9c18-05d137d52f5e.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.2

### Settings

N/A

### Notes

N/A

**Comment by uBlock-user** [comment]
Subscribe to uBlock Annoyances list.

**Comment by Mennaruuk** [comment]
Is it in that list? I’m subscribed to it.

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/b24494a1e750374481f47615f928e8779eeec267
