### ISSUE TITLE
teknofilo.com ADS

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#990]
URL(s) where the issue occurs

https://www.teknofilo.com/gfycat-quiere-mejorar-tus-gifs-de-baja-calidad-mediante-inteligencia-artificial/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by okiehsch** [comment]
`teknofilo.com##a[href="//amzn.to/2qrvd3A"]`
