### ISSUE TITLE
9to5 websites: youtube player and disqus comments not appear

### ISSUE THREAD

**Issue by stephenhawk8054** [uBlockOrigin/uAssets#9903]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://9to5google.com/2021/08/23/google-maps-navigation-data/`

`https://9to5mac.com/2021/08/29/kuo-iphone-13-to-support-leo-satellite-communication-allowing-users-to-make-phone-calls-and-send-texts-without-cell-signal/`

### Describe the issue

YouTube player and Disqus comments section do not display (loading icon with YouTube and blank white space with Disqus).

### Screenshot(s)

![9to5mac](https://user-images.githubusercontent.com/66517106/131830216-97edcac7-ce32-440f-927c-3fc56d007e8a.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.2

### Settings

Default settings

### Notes

Whitelist these 2 scripts help display both

`@@||cdn.ampproject.org/*/amp-consent$script,domain=9to5google.com|9to5mac.com`

`@@||cdn.ampproject.org/*/amp-geo$script,domain=9to5google.com|9to5mac.com`

**Comment by okiehsch** [comment]
`cdn.ampproject.org/*/amp-consent`
what is blocking that request on your end?
It's not blocked for me.
![image](https://user-images.githubusercontent.com/16838044/131831936-09a043e9-f597-4749-94dd-267e378e5303.png)

**Comment by stephenhawk8054** [comment]
> 
> 
> `cdn.ampproject.org/*/amp-consent`
> what is blocking that request on your end?
> It's not blocked for me.
> ![image](https://user-images.githubusercontent.com/16838044/131831936-09a043e9-f597-4749-94dd-267e378e5303.png)

Ah sorry my mistake, it's just `@@||cdn.ampproject.org/*/amp-geo`

**Comment by okiehsch** [comment]
Fixed.
