### ISSUE TITLE
[Anti-Adblock] Ad-Blockers are prohibited in vivo.st

### ISSUE THREAD

**Issue by Kokujou** [uBlockOrigin/uAssets#9911]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://vivo.st`

### Describe the issue

the website works when disabling uBlock while it does not work with it enabled.
all lists are updated, the extension itself is also up to date. same goes for the browser. it is a recent problem actually, because i earlier ( I can't specify the exact date) the website worked without trouble. so either it is a recent update of uBlock or it's filters or it's a recent update of the website

### uBlock Origin version

1.37.2

### Browser name and version

Mozilla Firefox 91.0.2

### Settings

  "selectedFilterLists": [
    "user-filters",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-abuse",
    "ublock-unbreak",
    "adguard-generic",
    "adguard-mobile",
    "easylist",
    "adguard-spyware",
    "adguard-spyware-url",
    "block-lan",
    "easyprivacy",
    "urlhaus-1",
    "spam404-0",
    "adguard-annoyance",
    "adguard-social",
    "fanboy-thirdparty_social",
    "fanboy-cookiemonster",
    "fanboy-annoyance",
    "fanboy-social",
    "ublock-annoyances",
    "plowe-0",
    "DEU-0"
  ]

**Comment by Kokujou** [comment]
if it helps this is my current configuration

[ublock-sicherung_2021-09-02_21.25.53.txt](https://github.com/uBlockOrigin/uAssets/files/7101263/ublock-sicherung_2021-09-02_21.25.53.txt)

**Comment by uBlock-user** [comment]
Tested at `https://vivo.st/cf2137f496#tab-kt3bkwvf`, other than a popup, everything else works fine. 

Reset to default settings and try again.

**Comment by Kokujou** [comment]
you're right, that's strange it seems to be a specific vivo website, if this even makes sense, could you try
https://vivo.st/f310579555

your link actually works

**Comment by Kokujou** [comment]
i resetted to default - no success

**Comment by okiehsch** [comment]
Add
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=vivo.st`
to your filter list.

**Comment by Kokujou** [comment]
that was it !! thank you :)
is there already a filter list which includes this filter? if yes then it'd be nice to enable it by default or so :)

**Comment by okiehsch** [comment]
> is there already a filter list which includes this filter?

No, I will add it to `uBO-filters`.

**Comment by uBlock-user** [comment]
@okiehsch are you able to reproduce ? I don't see any anti-adblock notice.

**Comment by okiehsch** [comment]
> are you able to reproduce ? I don't see any anti-adblock notice.

Yes. With the link the OP provided.
![image](https://user-images.githubusercontent.com/16838044/131906502-9d65c273-c37c-40e8-9edf-54aacac62ba3.png)
