### ISSUE TITLE
dailymail.co.uk

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#9912]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.dailymail.co.uk/news/article-9952403/Jen-Psaki-snaps-male-reporter-asking-Biden-supports-abortion.html`

`https://www.dailymail.co.uk/news/article-9951333/26-Republicans-demand-Biden-reveal-Americans-allies-stranded-Afghanistan.html`

`https://www.dailymail.co.uk/news/article-9943331/Mystery-online-charter-high-school-football-team-lands-coveted-ESPN-televised-game.html`

`https://www.dailymail.co.uk/news/article-9951919/Tennessee-father-shot-fires-gender-reveal-party-three-schools-went-lockdown.html`

`https://www.dailymail.co.uk/news/canada/index.html`

### Describe the issue

Ad at the very bottom right. Sometimes, I see an ad for Farm Heroes. Other times, I see an ad for recipe starters.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/131929020-b771002d-b965-405a-a928-189c69768e25.png)

![image](https://user-images.githubusercontent.com/52135169/131929368-209b93c9-3707-44d3-a553-3bc6007f5ce7.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.2

### Settings

N/A

### Notes

An archive link if it is of any help:
`https://archive.is/bC2iX`

**Comment by uBlock-user** [comment]
Don't see any such ad..

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/1e363650333d4caadd218e5458da3e7cde2d44fe

**Comment by mapx-** [comment]
Where do you get these ads / ph ? home page, specific pages ? android or desktop ?
