### ISSUE TITLE
myuploadedpremium.de

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#9916]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://myuploadedpremium.de/uploaded`

### Describe the issue

Site detects content blocker.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/132026349-cad4d133-1a09-49cc-88be-432a2e266095.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.2

### Settings

N/A

### Notes

Just this week, [it was using BlockAdBlock](https://github.com/AdguardTeam/AdguardFilters/issues/93343). Looks like this script is culprit:

`https://myuploadedpremium.de/js/main.js?v=580`

**Comment by uBlock-user** [comment]
Tested with `https://uploaded.net/file/33brpy` as a link, no anti-adblock

**Comment by Mennaruuk** [comment]
Interesting. Do you have an idea of which filter treats this anti-adblock? I see you put the link where no anti-adblock shows, but does this apply to the link in my original comment?

**Comment by uBlock-user** [comment]
> Do you have an idea of which filter list treats this anti-adblock

uBlock's lists ofcourse.
