### ISSUE TITLE
mypapercraft.net [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#992]
URL(s) where the issue occurs

http://www.mypapercraft.net/shimamura-uzuki-paper-craft/10989/

Describe the issue

Anti-Adblock

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by KiLL4FuNK** [comment]
Anti-Adblock
