### ISSUE TITLE
mmohuts.com

### ISSUE THREAD

**Issue by R-Ata** [uBlockOrigin/uAssets#9920]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://mmohuts.com/`
`https://mmohuts.com/video/ninjala-season-4-trailer/`

### Describe the issue

ads

### Screenshot(s)

![Captur](https://user-images.githubusercontent.com/33556647/132076022-5b2e6478-ba13-45f3-8d23-cea2a73e50fc.PNG)

### uBlock Origin version

1.37.2

### Browser name and version

CHROME - 93.0.4577.63

### Settings

Default

### Notes

other extension using:
- Malwarebytes Browser Guard

**Comment by uBlock-user** [comment]
`mmohuts.com##[href^="http://gamer.mmohuts.com/"]`

or 

`||gamer.mmohuts.com^`
