### ISSUE TITLE
[Annoyance] qb.zuoyebang.com

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#9926]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://qb.zuoyebang.com/xfe-question/question/58d3999e32c66c898a71677d99ee0686.html`

### Describe the issue

The page has a lot of self-promotion
But the names of these classes seem to change frequently, so I can't find a suitable filter rule to filter them

The site conducts self-promotion, as shown in the figure
When you click on "More answers(1)"(`更多答案(1)`), a window will pop up on this page

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66902050/126786566-cbecd335-c485-4aa9-9d9b-4f63182753f1.png)
![2021-07-23_21-27-33](https://user-images.githubusercontent.com/66902050/126788560-2739c102-fc70-4948-8d3e-fb3c2ad3e178.gif)

### uBlock Origin version

v1.37.0

### Browser name and version

Microsoft Edge 92.0.902.62

### Settings

_No need_

**Comment by krystian3w** [comment]
MS landed Edge 93 based on Chromium 93.

**Comment by krystian3w** [comment]
`##img[class*="bottomBanner_"]`

@cjx82630 fyi.

**Comment by shenzhiming88** [comment]
@krystian3w Thank you. I thought this might be placed in `Fanboy's Annoyance` rather than in `uBlock filters - Annoyances`

**Comment by krystian3w** [comment]
Oh, I found this: https://github.com/cjx82630/cjxlist/issues/34 (36 days/5weeks and 0 reaction).

![obraz](https://user-images.githubusercontent.com/35370833/132110930-f89c0cd2-8535-4351-aa38-f3517107e2be.png)

**Comment by krystian3w** [comment]
https://github.com/cjx82630/cjxlist/commit/3872ef4688c06b0ccd506162571af9503c5e5079

**Comment by krystian3w** [comment]
https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt&title=CN%20AdList

**Comment by shenzhiming88** [comment]
@krystian3w Fine. Thank you for your help!
