### ISSUE TITLE
http://ww7.moviezflix.org/ (Anti-adblock)

### ISSUE THREAD

**Issue by Happypig375** [uBlockOrigin/uAssets#9928]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`http://ww7.moviezflix.org/`

### Describe the issue

"Ad block detected
Please disable your ad blocker and reload the page."

### Screenshot(s)

![image](https://user-images.githubusercontent.com/19922066/132127298-d492c55e-1c04-4fe3-b73b-77cc13b95641.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.2

### Settings

None

### Notes

It seems to detect loading of AdSense files?
![image](https://user-images.githubusercontent.com/19922066/132127493-066b4678-0ff0-401a-a28f-08998482ae5c.png)

**Comment by uBlock-user** [comment]
`/px.gif?$image,redirect-rule=1x1.gif`

Domain is parked, dead site.

**Comment by krystian3w** [comment]
I found big dead page on cpu-z: https://www.cpuid.com/softwares/cpu-z.htmlfooter-sitemap

`TPFanControl` - scroll to footer and possible found: `http://www.tpfancontrol.com/`
