### ISSUE TITLE
hackerrank.com

### ISSUE THREAD

**Issue by krystian3w** [uBlockOrigin/uAssets#9930]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.hackerrank.com/challenges/equal-stacks/problem`
`https://www.hackerrank.com/challenges/equal-stacks/forum`

### Describe the issue

Login pop-up wall on load page, after any refresh

I reported here, because page block scroll and pop-up must works after click in real button in right corner.

Very similar to https://github.com/uBlockOrigin/uAssets/issues/7550

### Screenshot(s)

![obraz](https://user-images.githubusercontent.com/35370833/132138509-0dbd1902-9b8c-45a9-b51a-7273f9d72ecb.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92 RC 3

### Settings

- uBlock Annoyances

### Notes

I tested CSS + `:remove()`  / procedural cosmetic filter but break function from header buttons.

**Comment by krystian3w** [comment]
Also `DandelionSprout` is busy to fix that page: https://github.com/DandelionSprout/adfilt/issues/264 (too many lists for 1 creator).

**Comment by uBlock-user** [comment]
You can use --

```
hackerrank.com##div.message-info.form-alert:upward(div.portal-wrapper)
hackerrank.com##body,html:style(overflow:auto !important;padding-right:0px !important)
```

but that will break the page when loaded via --

Visiting - https://www.hackerrank.com/domains/data-structures?filters[subdomains][]=stacks
Clicking **Solve Challenge**

page won't fully appear.

**Comment by krystian3w** [comment]
Maybe `:upward(div.portal-wrapper:not(:last-child))`

So page really hide event as no readable for humans or logger version of scriptlets?

**Comment by uBlock-user** [comment]
> Maybe

That doesn't change anything.

The page doesn't hide, more like halts page loading when the annoyance appears, so hiding the annoyance doesn't make the partially loaded page to load fully.

You could just use `hackerrank.com##+js(set, HR.development, true)` this will not the above issue but Login and Signup button will also get disabled, but if you're never going to create an account, that would be an acceptable choice.

**Comment by krystian3w** [comment]
I mean "page no use visible event listener/setTimout/setInterval".

**Comment by uBlock-user** [comment]
Not without any breakage.
