### ISSUE TITLE
Pastebin content is removed

### ISSUE THREAD

**Issue by Mipsters** [uBlockOrigin/uAssets#9931]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://pastebin.com/EZVjSyVv`

### Describe the issue

the content of the paste is gone
this is canceled when disabling cosmetics

the rule that cause it is `pastebin.com##.adsbyvli:upward(1)`

when  I checked, there were four elements that were suppose to be removed by this rule
and most cosmetic issues are resolved with removing the elements themselves and not their parents
so I think it should just be changed to `pastebin.com##.adsbyvli`

### Screenshot(s)

![image](https://user-images.githubusercontent.com/4920832/132190596-0ca111a8-4e2b-4cb8-acfc-2e90b69a51d9.png)

when disabling cosmetic changes:
![image](https://user-images.githubusercontent.com/4920832/132190698-3d26cd72-30d1-46ae-aa4b-74f0d4caa12e.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.2 (64-bit)

### Settings

- no changes

**Comment by okiehsch** [comment]
Try updating your filter lists.
The filter
`pastebin.com##.adsbyvli:upward(1)`
is not part of the up to date `uBO-filter` list.

**Comment by lain566** [comment]
The issue was fixed 3 days ago https://github.com/uBlockOrigin/uAssets/commit/3c7cd0c0c2076fb118f0b29df2b66ad0733c10c6
