### ISSUE TITLE
Even more scam domains

### ISSUE THREAD

**Issue by iam-py-test** [uBlockOrigin/uAssets#9933]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

```
navman-gpsupdate.online
repeatstomach.cyou
greenadblocker.com
```

### Describe the issue

These domains are scams. The first one redirects to the second one, and the second redirects to the third

### Screenshot(s)

![image](https://user-images.githubusercontent.com/84232764/132228087-d0466669-f07c-448b-96f1-1e926d79a9af.png)

### uBlock Origin version

uBlock Origin 1.37.2

### Browser name and version

Firefox 91.0.2

### Settings

- All built in lists: ON
- All Ads and Malware lists: ON
- All privacy except AdGuard URL Tracking: ON
- All Multipurpose: ON
- All annoyances: OFF
- Remaining:
![image](https://user-images.githubusercontent.com/84232764/132228950-589eb5de-f74d-43f3-9962-3f8ceec49d32.png)
![image](https://user-images.githubusercontent.com/84232764/132229015-33952bbb-bb76-4ed3-9e83-872df3dc17e7.png)

### Notes

The domain has banned my IP, so I can not provide more screenshots easily.

**Comment by JobcenterTycoon** [comment]
`1redirb.com` is already blocked and `navman-gpsupdate.online` is parked on my end

**Comment by iam-py-test** [comment]
> `navman-gpsupdate.online` is parked on my end

The domain redirected to a parked page after a few times, but the first time it redirected to the end point.
Are you in the US?

**Comment by iam-py-test** [comment]
@JobcenterTycoon added the scam domain you reported. Thanks
How did you find it?

**Comment by JobcenterTycoon** [comment]
@iam-py-test from a random popup on `flashx.tv` while i tested something. uBlock Origin blocks the popups very well but without uBlock Origin it open 10+ Popups 🙃 After the test i know the "anti Adblock" on the site is fake

**Comment by Mennaruuk** [comment]
Found one more, their number goes to a scam call center:

`https://lp1.limafoxtrot.online`

**Comment by iam-py-test** [comment]
@Mennaruuk is that domain relevant to the domains I am submitting?
Where did you find it?

**Comment by Mennaruuk** [comment]
Unlikely they’re owned by the same people. McAfee scam popups roughly similar. You can read more about them [here.](https://www.mcafee.com/blogs/other-blogs/mcafee-labs/how-to-stop-the-popups)

**Comment by iam-py-test** [comment]
@Mennaruuk is the whole domain a scam or just that sub domain?

**Comment by Mennaruuk** [comment]
The domain is `limafoxtrot.online`, but it redirects to the one above.

**Comment by iam-py-test** [comment]
@Mennaruuk I have added them to my malware blocklist, but will open an issue here or in Adfilt when I get a chance.

**Comment by uBlock-user** [comment]
Parked domains can't do anything, they're parked, period.

**Comment by Yuki2718** [comment]
Not much sure if `greenadblocker.com` is scam, their extension is on AMO tho "is not actively monitored for security by Mozilla". 

@iam-py-test For the McAfee staff or anything similar, please report full URL as far as possible (beware that your IP may be included in query. In that case it's okay to remove it and comment about this). These domain changes too often and it may be better to use pattern-based filter if possible. Here's a brief history of filters for a similar scam:
Domain filters => `||cloudfront.net/*/?phone=$doc,popup` => `||stackpathcdn.com/*/?phone=$doc,popup` => (they switched to raw IPs) `/?phone=*&aff_pid=$doc` => `/?phone=*&geo=$doc`
I'll keep cloudfront and stackpathcdn filters for a while in case they returned back to these cdn with modified parameter.

Also it's not uncommon they accept accesses only if having valid parameter, tho sometimes also check referrer.

**Comment by uBlock-user** [comment]
@Yuki2718 I added it based on https://malwaretips.com/blogs/remove-green-blocker/
