### ISSUE TITLE
anti adblock https://simcompanies.proboards.com

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#9934]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://simcompanies.proboards.com/thread/35/personal-assistant-quests`

### Describe the issue

can you remove this annoying popup? it seems had random string before popup name so if we hide it by ublock feature, the popup will still remain (btw if you want to test it, maybe it will be good if you guys clear cache/Incognito mode every test)

### Screenshot(s)

![image](https://user-images.githubusercontent.com/29838157/132239429-43f7ade4-628c-4e11-88d0-42c76e07734b.png)

### uBlock Origin version

Ublock Lastest

### Browser name and version

Chrome lastest

### Settings

-

**Comment by okiehsch** [comment]
Already fixed in `uBO-annoyances`.
