### ISSUE TITLE
https://babiato.co/ adblock

### ISSUE THREAD

**Issue by Dhanamerdeka** [uBlockOrigin/uAssets#9935]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs
`
https://babiato.co/`

### Describe the issue

Anti adblock notif show

### uBlock Origin version

Ublock Lastest

### Browser name and version

Chrome lastest

### Settings

-

**Comment by okiehsch** [comment]
Already fixed in `uBO-annoyances`.

**Comment by uBlock-user** [comment]
`babiato.co##+js(acis, $, test)` needed
