### ISSUE TITLE
lookmovie.io popup

### ISSUE THREAD

**Issue by Mennaruuk** [uBlockOrigin/uAssets#9936]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://lookmovie.io/movies/view/0285182-la-plus-haute-cible-2002`

### Describe the issue

If you click the play button, a popup appears linking to an image.

### Screenshot(s)

https://user-images.githubusercontent.com/52135169/132259266-7f2f051b-13c2-4f86-b439-0d953d566add.mp4

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91.0.2

### Settings

N/A

### Notes

This is the popup URL:

`https://lookmovie.io/images/logo1.png`

**Comment by ghajini** [comment]
`https://lookmovie.club/american-badger-fgjhfj/`
video is blocked here due to denyallow rule
