### ISSUE TITLE
Q-Global online rating scales Peason Assessments

### ISSUE THREAD

**Issue by dfreeman50** [uBlockOrigin/uAssets#9938]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

qosa.pearsonclinical.com
`www.pearsonclinical.com`

### Describe the issue

I am a school psychologist and we use an online rating scale program from Pearson Assessments called Q-Global.  It appears uBlock is blocking this site from working and our teachers just get a spinning icon unless they disable uBlock for the sites.  

Can you add the URLs to the safe list?   Thanks, David

### Screenshot(s)

![Screenshot (2)](https://user-images.githubusercontent.com/90279759/132393722-61ef0a10-e346-48af-bf99-c8198234f4c5.png)

### uBlock Origin version

1.37.2

### Browser name and version

Chrome 92.0.4515.159

### Settings

The program seems to work once uBlock is disabled, but that's an extra step for teachers not technologically gifted.

### Notes

The problem only seems to be affecting our teachers on our domain who use Chrome with the uBlock extension.

**Comment by okiehsch** [comment]
> Can you add the URLs to the safe list?

No, we don't add sites to "safe lists".
What I can do is try to unbreak the site.
It needs an account, so I can't reproduce the breakage.
I can see from your screenshot that uBO blocks one request.
Can you check what is blocked?

To do open the [logger](https://github.com/gorhill/uBlock/wiki/The-logger) then load the broken site.
The logger will list all request the blocked ones are the ones in red color.
