### ISSUE TITLE
outlook.live.com makes continuous blocked xhr requests

### ISSUE THREAD

**Issue by peace2000** [uBlockOrigin/uAssets#9939]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://outlook.live.com/mail/0/inbox`

### Describe the issue

Easyprivacy blocks this xhr-request correctly:

![kuva](https://user-images.githubusercontent.com/17256841/132394800-edb234da-bc6d-48df-8f7e-f949ed067e33.png)

But the site tries to make it again and again. Would it be possible to stop them completely by uAssets?

Edit, also this request happens continuosly, though not so often:

![kuva](https://user-images.githubusercontent.com/17256841/132511859-c0439e32-b4f7-4d98-876f-e49aa3ad73ae.png)

I opened this in the spirit of this topic: `https://www.reddit.com/r/uBlockOrigin/comments/pikci6/1000_blocks_on_whatsappcom_thats_insane_thanks/`

### uBlock Origin version

1.37.3rc0

### Browser name and version

Firefox 91.0.2

### Settings

Can be reproduced with defaults

### Notes

Tested when logged in to Outlook, it acts differently for logged in users (I'm a logged in user).

This happens for logged in users: https://github.com/uBlockOrigin/uAssets/issues/9939#issuecomment-915070243

**Comment by uBlock-user** [comment]
> Would it be possible to stop them completely by uAssets?

Try  `outlook.live.com##+js(no-fetch-if, url:collector)`

**Comment by peace2000** [comment]
I tried a similar filter but didn't work and that doesn't either.

**Comment by uBlock-user** [comment]
`||microsoft.com/collector/$xhr,redirect-rule=nooptext` works ?

**Comment by peace2000** [comment]
Nope, I also tried a filter like that...

**Comment by uBlock-user** [comment]
If you're willing to experiment, then install my custom scriptlets JS via `https://raw.githubusercontent.com/uBlock-user/uBO-Scriptlets/master/scriptlets.js` at `userResourceLocation` setting, followed by adding this filter to my filters --

`outlook.live.com##+js(no-xhr-if, collector)`

**Comment by peace2000** [comment]
I actually installed that set of custom scriplets some time ago so had it ready to go...

But no, doesn't help either.

**Comment by uBlock-user** [comment]
I don't have any account so can't try for a better filter.

**Comment by uBlock-user** [comment]
`outlook.live.com` re-defines XMLHttpRequest via its js library, so scriptlet's definition is getting over-ridden.

**Comment by peace2000** [comment]
Hi, `outlook.live.com##+js(no-xhr-if, Collector)` didn't work either.

> `outlook.live.com` re-defines XMLHttpRequest via its js library, so scriptlet's definition is getting over-ridden.

Did someone check that for you (you said you don't have an account?) I can make a test account for you if you are ok with that.

**Comment by uBlock-user** [comment]
Add `outlook.live.com##+js(set, XMLHttpRequest.prototype.open, undefined)` refresh the page and then open the console, copy-paste `XMLHttpRequest.prototype.open` in the console, hit enter, report value.

**Comment by peace2000** [comment]
// >>>> start of private namespace

try {
(function() {
    const chain = 'XMLHttpRequest.prototype.open';
    let cValue = 'undefined';
    const thisScript = document.currentScript;
    if ( cValue === 'undefined' ) {
        cValue = undefined;
    } else if ( cValue === 'false' ) {
        cValue = false;
    } else if ( cValue === 'true' ) {
        cValue = true;
    } else if ( cValue === 'null' ) {
        cValue = null;
    } else if ( cValue === "''" ) {
        cValue = '';
    } else if ( cValue === '[]' ) {
        cValue = [];
    } else if ( cValue === '{}' ) {
        cValue = {};
    } else if ( cValue === 'noopFunc' ) {
        cValue = function(){};
    } else if ( cValue === 'trueFunc' ) {
        cValue = function(){ return true; };
    } else if ( cValue === 'falseFunc' ) {
        cValue = function(){ return false; };
    } else if ( /^\d+$/.test(cValue) ) {
        cValue = parseFloat(cValue);
        if ( isNaN(cValue) ) { return; }
        if ( Math.abs(cValue) > 0x7FFF ) { return; }
    } else {
        return;
    }
    let aborted = false;
    const mustAbort = function(v) {
        if ( aborted ) { return true; }
        aborted =
            (v !== undefined && v !== null) &&
            (cValue !== undefined && cValue !== null) &&
            (typeof v !== typeof cValue);
        return aborted;
    };
    // https://github.com/uBlockOrigin/uBlock-issues/issues/156
    //   Support multiple trappers for the same property.
    const trapProp = function(owner, prop, configurable, handler) {
        if ( handler.init(owner[prop]) === false ) { return; }
        const odesc = Object.getOwnPropertyDescriptor(owner, prop);
        let prevGetter, prevSetter;
        if ( odesc instanceof Object ) {
            if ( odesc.configurable === false ) { return; }
            if ( odesc.get instanceof Function ) {
                prevGetter = odesc.get;
            }
            if ( odesc.set instanceof Function ) {
                prevSetter = odesc.set;
            }
        }
        Object.defineProperty(owner, prop, {
            configurable,
            get() {
                if ( prevGetter !== undefined ) {
                    prevGetter();
                }
                return handler.getter(); // cValue
            },
            set(a) {
                if ( prevSetter !== undefined ) {
                    prevSetter(a);
                }
                handler.setter(a);
            }
        });
    };
    const trapChain = function(owner, chain) {
        const pos = chain.indexOf('.');
        if ( pos === -1 ) {
            trapProp(owner, chain, false, {
                v: undefined,
                init: function(v) {
                    if ( mustAbort(v) ) { return false; }
                    this.v = v;
                    return true;
                },
                getter: function() {
                    return document.currentScript === thisScript
                        ? this.v
                        : cValue;
                },
                setter: function(a) {
                    if ( mustAbort(a) === false ) { return; }
                    cValue = a;
                }
            });
            return;
        }
        const prop = chain.slice(0, pos);
        const v = owner[prop];
        chain = chain.slice(pos + 1);
        if ( v instanceof Object || typeof v === 'object' && v !== null ) {
            trapChain(v, chain);
            return;
        }
        trapProp(owner, prop, true, {
            v: undefined,
            init: function(v) {
                this.v = v;
                return true;
            },
            getter: function() {
                return this.v;
            },
            setter: function(a) {
                this.v = a;
                if ( a instanceof Object ) {
                    trapChain(a, chain);
                }
            }
        });
    };
    trapChain(window, chain);
})();
} catch ( e ) { }

// <<<< end of private namespace
})();.

**Comment by uBlock-user** [comment]
That's not what I asked.

Like this -- 

![Capture](https://user-images.githubusercontent.com/21290713/132489278-c340e536-8824-4e86-a69b-7d1ffb98efe0.PNG)

**Comment by peace2000** [comment]
```

open()
​
length: 2
​
name: "open"
​
<prototype>: function ()

Hopefully got it right now :D
```

**Comment by uBlock-user** [comment]
Did you add `outlook.live.com##+js(set, XMLHttpRequest.prototype.open, undefined)` and refreshed the page ?

**Comment by peace2000** [comment]
Yes

**Comment by peace2000** [comment]
More info if I open "prototype":

![image](https://user-images.githubusercontent.com/17256841/132490913-eb8b970a-9854-4632-b5b3-33f559d96aad.png)

**Comment by uBlock-user** [comment]
The value should be `undefined`, NOT `open()`, so you just proved my point in https://github.com/uBlockOrigin/uAssets/issues/9939#issuecomment-915070243

**Comment by uBlock-user** [comment]
@gorhill

**Comment by uBlock-user** [comment]
@gorhill your thoughts ?

**Comment by peace2000** [comment]
![kuva](https://user-images.githubusercontent.com/17256841/132511490-c5fb2191-9692-4998-80cf-9c2ce3532ba3.png)

This request also happens again and again, even though not so often. I'll add it to the description.

**Comment by uBlock-user** [comment]
> This request also happens again and again

When logged in ?

**Comment by peace2000** [comment]
@uBlock-user Yes

**Comment by uBlock-user** [comment]
They're not overriding `XMLHttpRequest` if you're not logged in to Outlook, as seen via `outlook.live.com##+js(set, XMLHttpRequest.prototype.open, undefined)` and then stepping into the code via console again after logging out.

**Comment by peace2000** [comment]
> 
> 
> They're not overriding `XMLHttpRequest` if you're not logged in to Outlook, as seen via `outlook.live.com##+js(set, XMLHttpRequest.prototype.open, undefined)` and then stepping into the code via console again after logging out.

True, I can repro:

![kuva](https://user-images.githubusercontent.com/17256841/132513720-c2053e12-e062-4c1d-b563-abad8d8320bb.png)

I'll edit this post a bit...

**Comment by gorhill** [comment]
> though not so often

Given this, it does not seem worth to me to invest huge amount of time to solve what is a non-issue in the end.

**Comment by peace2000** [comment]
@gorhill I was referring to requests concerning "onecollector". Collector request happens pretty often. This is from 2 min period:

![kuva](https://user-images.githubusercontent.com/17256841/132515623-5c4e989a-7936-4894-98b5-a672097f3aad.png)

I'm not sure what should be considered much and what not, I was worrying performance as there were continuos requests.

**Comment by gorhill** [comment]
> This is from approx. 2 min period:

This amount to a request per ~5 seconds. The original screenshot shows a request per ~9 seconds. So maybe these occur when you interact with the UI, and in the latest screenshot you interacted more and as a result there are more requests per unit of time? Regardless, a request per 5 seconds is a non-issue.

The point is I was asked to weight in here, and I don't see this as an issue, I personally won't invest precious time on what I consider a non-issue, but whoever thinks it's an issue is free to invest their own time to contribute a solution.

Also, did you check whether those specific network requests are _not_ made as often when _not_ blocked?

> I was worrying performance

Worries about performance should be accompanied by action, i.e. profile to make the case the worries are founded or not.

The static network filtering engine takes at most low double-digit microseconds to filter such requests, so consider a worst case scenario of 100µs per 5,000,000µs and you get 0.002%, which overhead maybe could have been "worse" had the request not been blocked -- so clearly performance worries are completely unwarranted.

**Comment by peace2000** [comment]
I don't need to interact at all on Outlook, requests still happen. (And I checked now that they happen even if I disable EP).

But anyway, if a request count of that doesn't affect virtually anything, then I agree it's a non-issue. Thanks for perspective, I'm not a programmer so my perspective might be very different. I thought that continuous requests are an issue because you offered filters to stop continuous requests concerning Whatsapp: `https://www.reddit.com/r/uBlockOrigin/comments/pikci6/1000_blocks_on_whatsappcom_thats_insane_thanks/`

Thanks for your efforts @uBlock-user @gorhill

**Comment by gorhill** [comment]
> because you offered filters to stop continuous requests concerning Whatsapp

It's fine if there is an existing trivial solution with the current existing syntax, otherwise it's not something worth adding new capabilities in uBO, that part is non-trivial.

**Comment by krystian3w** [comment]
I use these on MS pages:

`||login.live.com/*.srf$frame,domain=support.microsoft.com`
