### ISSUE TITLE
beelink.in [Anti-Adblock]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#994]
URL(s) where the issue occurs

http://beelink.in/34733/Essential-Future-Bass-Vol.1-MULTiFORMAT.html

Describe the issue

Anti-Adblock ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by xDarkARG** [comment]
Anti-Adblock  @mapx-

**Comment by KiLL4FuNK** [comment]
Anti-Adblock @mapx-

**Comment by KiLL4FuNK** [comment]
Anti-Adblock
