### ISSUE TITLE
yonsandileer.com too many popups or ads

### ISSUE THREAD

**Issue by greatagnostic** [uBlockOrigin/uAssets#9940]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://yonsandileer.com/4/3601343/?var=3601343&ab2r=0&prfrev=false`

### Describe the issue

Annoying pop ups or ads and indirect links

### uBlock Origin version

1.37.2

### Browser name and version

firefox 91.4

### Settings

Unchecked peter ads

**Comment by greatagnostic** [comment]
![Screenshot_20210908-100813](https://user-images.githubusercontent.com/89909437/132434805-d74dabba-9d2e-4178-b63c-ece601bb7f8d.png)

**Comment by greatagnostic** [comment]
![Screenshot_20210908-101121](https://user-images.githubusercontent.com/89909437/132435094-8b182954-6e14-4bfd-a104-d6987a2da6b4.png)

**Comment by What-Zit-Tooya** [comment]
`yonsandileer.com` blocked (in easylist) due to malware site, deliver pop up and probably viruses inside ads. you should not visit it.

**Comment by greatagnostic** [comment]
> `yonsandileer.com` blocked (in easylist) due to malware site, deliver pop up and probably viruses inside ads. you should not visit it.

Easylist didn't block that site

**Comment by bogachenko** [comment]
@greatagnostic The site yonsandileer.com is advertising, it redirects to other advertising domains and, as already mentioned above, it is (quite appropriately) blocked by Easylist.

I noticed in one of your screenshots that you were about to download some kind of video from the sbplay.one site, I dare to assume that is where you found the site yonsandileer.com. Give a link to that video and sites like yonsandileer.com will be blocked.

**Comment by greatagnostic** [comment]
> @greatagnostic The site yonsandileer.com is advertising, it redirects to other advertising domains and, as already mentioned above, it is (quite appropriately) blocked by Easylist.
> 
> I noticed in one of your screenshots that you were about to download some kind of video from the sbplay.one site, I dare to assume that is where you found the site yonsandileer.com. Give a link to that video and sites like yonsandileer.com will be blocked.

https://sbplay.one/dl?op=download_orig&id=b5v6dlhnjapn&mode=n&hash=10940585-180-194-1631074241-d88be7bba36cf55e2bf461cd9f481716

**Comment by greatagnostic** [comment]
> @greatagnostic The site yonsandileer.com is advertising, it redirects to other advertising domains and, as already mentioned above, it is (quite appropriately) blocked by Easylist.
> 
> I noticed in one of your screenshots that you were about to download some kind of video from the sbplay.one site, I dare to assume that is where you found the site yonsandileer.com. Give a link to that video and sites like yonsandileer.com will be blocked.

https://sbplay.one/d/sz7qvxupdj0j.html

**Comment by bogachenko** [comment]
@greatagnostic Yup, I already found it myself, add [this rule](https://github.com/bogachenko/fuckfuckadblock/commit/126a0f1b6c40888b22e496fb9cadf7f7e55504a3#diff-ac0872947e3c56d2fa2f9a9dd233b78915de893c0aa602b74643c4929f426a74R284) to My Filters
