### ISSUE TITLE
[Anti-adblock] pcbeta.com

### ISSUE THREAD

**Issue by shenzhiming88** [uBlockOrigin/uAssets#9946]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.pcbeta.com/`

### Describe the issue

The page prompts the user to close the ad blocking software

### Screenshot(s)

![image](https://user-images.githubusercontent.com/66902050/132706294-d329bb48-47b6-41f3-9a3a-fcd269ff9933.png)

### uBlock Origin version

v1.37.0

### Browser name and version

Microsoft Edge 92.0.902.62

### Settings

_No need_

**Comment by uBlock-user** [comment]
try `pcbeta.com###append_parent`

**Comment by shenzhiming88** [comment]
@uBlock-user This does not seem to work, the ad placeholder is still there and the page uses a notification reminder to turn off the ad filter
![image](https://user-images.githubusercontent.com/66902050/132711322-0b46ae65-a6d5-4e14-9a41-1ce77014001c.png)

**Comment by uBlock-user** [comment]
Updated

> the ad placeholder is still there

`pcbeta.com##body > div#wp div[class]:matches-css(height: 60px)`

helps ?

**Comment by shenzhiming88** [comment]
@uBlock-user Yes, but the ad placeholder is still there
I think this rule can work
```
/\/data\/cache\/(?! (common|forum|home|portal))[a-zA-Z]+\.js/$script,domain=pcbeta.com
```
(Ref: `https://github.com/cjx82630/cjxlist/commit/26f7cd2ca61da81deef0dc09e96f80c53333120d`)

**Comment by uBlock-user** [comment]
@gorhill Seems site's MutationObserver is overiding `pcbeta.com##body > div#wp div[class]:matches-css(height: 60px)` any way to defuse the MO ?

**Comment by uBlock-user** [comment]
>  I think this rule can work

doesn't match any script there, so not working.

**Comment by shenzhiming88** [comment]
@uBlock-user
This is odd. On my computer, the first time I open the page, it seems to request a js script, such as `www.pcbeta.com/data/cache/blstGHLORZ.js`, but the name of this script seems to change. When this script is disabled, both the ad placeholder and the prompt to turn off the filter disappear

**Comment by uBlock-user** [comment]
@shenzhiming88 try `pcbeta.com##+js(aost, Math.floor, append)`

**Comment by gorhill** [comment]
> Seems site's MutationObserver is overriding

Probably because you are filtering based on element height, and this changes when you hide the element.

**Comment by uBlock-user** [comment]
@gorhill What filter would you suggest ? `:style()` doesn't work either.

**Comment by gorhill** [comment]
> but the name of this script seems to change

Yes, it's a different name on my side. How about a negative lookahead regex?

    /^https://www\.pcbeta\.com/data/cache/(?!common|portal)/$1p,script

**Comment by uBlock-user** [comment]
Can use `pcbeta.com##+js(aost, Math.floor, append)` instead

**Comment by shenzhiming88** [comment]
> 
> 
> @shenzhiming88 try `pcbeta.com##+js(aost, Math.floor, append)`

Yes, it works

**Comment by uBlock-user** [comment]
@shenzhiming88 doesn't break anything on your end ?

**Comment by shenzhiming88** [comment]
@uBlock-user Yes, at least for now, thanks
