### ISSUE TITLE
techlicious.com popup

### ISSUE THREAD

**Issue by Giwayume** [uBlockOrigin/uAssets#9949]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://www.techlicious.com/`

### Describe the issue

Disable adblock popup blocks site interaction

### Screenshot(s)

![image](https://user-images.githubusercontent.com/4075314/132745429-e8650a5b-d6c5-4656-a04b-b6c300ec53ca.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 91

### Settings

Default

**Comment by uBlock-user** [comment]
Susbcribe to uBlock Annoyances List.

**Comment by Giwayume** [comment]
This blocks access to the site, I wouldn't consider it an annoyance. There is no way for the user to close.

**Comment by uBlock-user** [comment]
> This blocks access to the site, I wouldn't consider it an annoyance. There is no way for the user to close.

_Continue without allowing ads_ button is right there.

**Comment by Giwayume** [comment]
Wow I didn't even see it. That's a dark UI pattern.
