### ISSUE TITLE
[Anti-adblock] sms24.me

### ISSUE THREAD

**Issue by Cyberavater** [uBlockOrigin/uAssets#9950]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`sms24.me`

### Describe the issue

[Anti-adblock]

### uBlock Origin version

Latest

### Browser name and version

Chrome Latest

### Settings

N/A

**Comment by uBlock-user** [comment]
force update ublock filters list.

**Comment by stephenhawk8054** [comment]
Anti-adblock again.

URL:
`https://sms24.me/en/countries/`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/66517106/148199536-18f46115-2fdb-4f43-b30e-14dc0f4e657c.png)

</details>

<details><summary>Configuration</summary>

```yaml
uBlock Origin: 1.40.2
Firefox: 95
filterset (summary): 
  network: 77892
  cosmetic: 40300
  scriptlet: 16366
  html: 616
listset (total-discarded, last updated): 
  default: 
    ublock-filters: 30621-29, 1h.11m
    ublock-badware: 3652-1, 1h.11m
    ublock-privacy: 182-0, 1h.11m
    ublock-abuse: 76-0, 1h.11m
    ublock-unbreak: 1721-0, 1h.11m
    easylist: 62630-579, 1h.11m
    easyprivacy: 26597-482, 1h.11m
    urlhaus-1: 7251-0, 1h.11m
    plowe-0: 3683-2, 1h.11m
filterset (user): [empty]
modifiedUserSettings: 
  advancedUserEnabled: true
modifiedHiddenSettings: [none]
supportStats: 
  launchToReadiness: 660 ms
popupPanel: 
  blocked: 4
```
</details>

Proposed filters:

```
@@||cdn.adoptum.net/ado.js$script,domain=sms24.me
sms24.me##body > div[style]
```
