### ISSUE TITLE
app.utm.io

### ISSUE THREAD

**Issue by herbertpimentel** [uBlockOrigin/uAssets#9952]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://app.utm.io`

### Describe the issue

Several of our users are reporting problem to login with their google account. This only happens when they have installed your extension. 

is there anything of our side that we can do, to ensure our users can use your extension on our platform with no problems ?

We use sentry and segment to track our users events and better respond to they acctions, and looks like those requests beign blocked 

### Screenshot(s)

![image](https://user-images.githubusercontent.com/1668448/132914317-29422171-fd8b-4c49-bc2f-6b56fd39047c.png)

### uBlock Origin version

uBlock Origin 1.37.2

### Browser name and version

Google Chrome Version 93.0.4577.63 / 64 bits

### Settings

None was made to the extension. We just install it, and our login with google process get stuck.

### Notes

Please, this is really affecting a lot of our customers. We did a lot from our side trying to find and undernstand the reason of that.

**Comment by uBlock-user** [comment]
> Several of our users are reporting problem to login with their google account. This only happens when they have installed your extension.

I clicked Login with Google and got logged in, no issues, tell them to reset uBO to default settings and then test it again.
