### ISSUE TITLE
megaup.net

### ISSUE THREAD

**Issue by electrifying** [uBlockOrigin/uAssets#9954]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://megaup.net/30MYf/`

### Describe the issue

it is impossible to download the file, as it works anti-adblock

### Screenshot(s)

https://imgur.com/utJrBlB

### uBlock Origin version

1.37.2

### Browser name and version

google chrome 93

### Settings

default

**Comment by electrifying** [comment]
@uBlock-user I renewed subscriptions, but the detector is still triggered

**Comment by uBlock-user** [comment]
@electrifying Works fine.

<details>

![Capture](https://user-images.githubusercontent.com/21290713/132948122-be48aa40-ff85-4aaf-b249-acc3a6e4a128.PNG)

</details>

Besure to --

- Test on default settings along with all other extensions disabled.
- Disable any HOSTS lists that have configured on OS level(we have allow ad-server scripts to load so anything blocking the ad-server will trigger the detector)

**Comment by SakhJack** [comment]
https://github.com/uBlockOrigin/uAssets/commit/536783287e99ddaed1d787dee78aa1e82a29e0b6 now actually breaks the website again

direct exception fixes the issue:
 `megaup.net#@#[id*="ScriptRootC"]:upward(1):style(position:absolute !important;left:-99999px !important)`

**Comment by uBlock-user** [comment]
addressed, force update in a while.

**Comment by SakhJack** [comment]
broken again, this time exception is a fix
`megaup.net#@#.metaRedirectWrapperBottomAds:style(pointer-events: none !important;opacity: 0 !important)`
it seems they monitor this page or something

**Comment by SakhJack** [comment]
another one...
`megaup.net#@#.mgbox:style(pointer-events:none !important;opacity:0 !important)`
P.S. firefox users need to disable tracking protection as well

**Comment by SakhJack** [comment]
okay, now they are not even using `adskeeper.co.uk` anymore
`@@||tm-offers.gamingadult.com^$frame,domain=megaup.net` does the trick this time

**Comment by SakhJack** [comment]
`*$image,redirect-rule=1x1.gif,domain=megaup.net,badfilter`

**Comment by stephenhawk8054** [comment]
There's a new anti-adblock.

URL: `https://megaup.net/rkxY/Dishonored.2.v1.77.9.part1.rar`

![image](https://user-images.githubusercontent.com/66517106/140689063-6b29589c-1608-4b94-9efc-e67e66d30fcb.png)

Firefox 94.0.1, ublock 1.38.6 default settings

Looks like the empty image redirect filter causes the anti-adblock.

Proposed filter:

```
*$image,redirect-rule=empty,domain=megaup.net,badfilter
||megaup.net/imageads/*$image,redirect=32x32.png,1p
```

**Comment by stephenhawk8054** [comment]
New anti-adblock.

URL: `https://megaup.net/rkxY/Dishonored.2.v1.77.9.part1.rar`

Proposed filter:

`||megaup.net/imageads/*$image,redirect=32x32.png,1p`

**Comment by stephenhawk8054** [comment]
Anti-adblock again.

URL: `https://megaup.net/Y0xo/The.Sims.4.Cottage.Living-CODEX.part03.rar`

Looks like removing this filter helps:

`*$image,redirect-rule=32x32.png,domain=megaup.net`

as there's already a `noopframe` filter for it

`||megaup.net/imageads/$image,1p,redirect-rule=noopframe`

**Comment by Jorge9811** [comment]
broken again @mapx-

**Comment by stephenhawk8054** [comment]
Looks like back to `noopframe`

`||megaup.net/imageads/*$image,redirect=noopframe,1p`

**Comment by stephenhawk8054** [comment]
Anti-adblock again.

`||megaup.net/imageads/*$image,redirect=32x32.png,1p`

**Comment by megarock1985** [comment]
any solution megaup is on again adblock detect pls help
https://megaup.net/2mPw6

**Comment by stephenhawk8054** [comment]
`noopframe` again?

```
||megaup.net/imageads/$image,1p,redirect-rule=32x32.png,badfilter
||megaup.net/imageads/$image,1p,redirect-rule=noopframe
```

**Comment by Jorge9811** [comment]
broken again @mapx-

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ba3860be3f617d2c3642891a59887018e5cbd885

**Comment by Smokemic** [comment]
broken again

**Comment by uBlock-user** [comment]
force update ublock filter list.

**Comment by Jorge9811** [comment]
> force update ublock filter list.

broken again and that doesn't fix it

**Comment by uBlock-user** [comment]
> and that doesn't fix it

because I have not added a new fix till now.

**Comment by Jorge9811** [comment]
broken again

how do they keep doing this shit ffs

**Comment by uBlock-user** [comment]
ongoing since https://github.com/uBlockOrigin/uAssets/issues/4430#issuecomment-542274535
