### ISSUE TITLE
Scam sites

### ISSUE THREAD

**Issue by JobcenterTycoon** [uBlockOrigin/uAssets#9955]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://filepapa.com/techsmith-camtasia-2019-0-10-build-17662-keygen-full/1983/`
`https://serialkey89.com/music/make-video/camtasia-studio-2021-06/`
`https://goharpc.com/camtasia-studio-crack-keygen-download1/`
`https://free4pc.org/nordvpn-crack/`

### Describe the issue

The complete site is fake and every click on any "download" button redirect to the same crap. Found these sites while im searched "camtasia 2019.0.10 download". 

The zip file with the virus "setup" is password protected to avoid to be removed but they are so "nice" to put the password in the txt file

### uBlock Origin version

1.37.2

### Browser name and version

Firefox developer

### Settings

- Enabled uBlock filters – Annoyances

**Comment by uBlock-user** [comment]
> The zip file with the virus "setup" is password protected to avoid to be removed but they are so "nice" to put the password in the txt file

VT reports ?

**Comment by JobcenterTycoon** [comment]
`https://www.virustotal.com/gui/file/57cba944a647a3d591b45725f875f3a25e1ccb809dc1c3631c37ed4d3fd89fc7` 
`https://www.virustotal.com/gui/file/d696719f64bcb0a27786ab6943ed8a68849be962f4abc085107c416db3bf79e4`
