### ISSUE TITLE
tooldefendext.com 

### ISSUE THREAD

**Issue by Siarl** [uBlockOrigin/uAssets#996]
### URL(s) where the issue occurs

Edit:

popups / tabunders / redirects

`http://arawatch.online/series-house-m.d-episode-7-season-1-s01e07-watch-free-stream-download-online-english-tv-video.html`
--------------------

### Describe the issue

Edit:

Once you press the next-button underneath the video view on arawatch.com, a new window pops up with the next episode. The original page gets redirected to e85440ec98f04725.com. This site redirects to random malware / advertisement sites

---------------------------
This site hosts fake browser updates. Urges you to download a file.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/9255132/33993497-118a1e04-e0d7-11e7-8272-c98ec25525b8.png)

### Versions

- Browser/version: Firefox Developer Edition 58.0b9 64-bit
- uBlock Origin version: uBlock Origin v1.14.20

### Settings

- Activated regional blacklist besides standard settings

**Comment by mapx-** [comment]
Are you usually visiting this page ? You should provide the starting page where you got a popup / tabunder / redirection to that malicious site.

**Comment by Siarl** [comment]
I see. Should I place the redirect right here or open another issue?

I'll edit my issue in the meantime

**Comment by mapx-** [comment]
Post the original page and how to get (what to click ..) the redirection.

**Comment by Siarl** [comment]
I completely misunderstood all parts of everything. Thanks for explaining, I'll edit one more time.

**Comment by mapx-** [comment]
try
```
arawatch.online##[id*="ScriptRoot"]
||arawatch.online^$popunder
```

**Comment by okiehsch** [comment]
There is no way to disable the popunder script, because of a race condition.

````
arawatch.online##script:inject(addEventListener-defuser.js, mousedown, cssText)
arawatch.online##[id*="ScriptRoot"]
arawatch.online##a[href="https://vidfast.co"]
````
disables the popunder and works on my end.

**Comment by mapx-** [comment]
Did you try to click play in firefox ? no issue on chrome

**Comment by okiehsch** [comment]
You are right, in Firefox I only tested if the Popunder was disabled, my bad.

**Comment by mapx-** [comment]
`||arawatch.online$inline-script` is working , sure .. but breaks the hosts menu on the right

**Comment by mapx-** [comment]
or `arawatch.online##a[href*=".html"]` working but breaks the episodes links bellow the video

**Comment by mapx-** [comment]
this 1 seems ok, could you test it ?
`arawatch.online##A[rel="nofollow norefferer noopener"]`

**Comment by okiehsch** [comment]
Works fine with Chrome and Firefox on my end, best solution I can see.

**Comment by mapx-** [comment]
to be sure
`arawatch.online##A[href$=".html"][rel="nofollow norefferer noopener"]`

**Comment by okiehsch** [comment]
@mapx- `arawatch.online##script:inject(abort-on-property-read.js, zfgloadedpopup)` works on my end,
there is no need to change your fix, I am just curious if you can reproduce,

**Comment by mapx-** [comment]
No, it does not work (tested FF 58.0b11 (64-bit), last beta uBo), same tabunder crap.
