### ISSUE TITLE
[NSFW] freehotporntubes.com

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uAssets#9963]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`http://freehotporntubes.com/`

### Describe the issue

Exo ads

### uBlock Origin version

1.37.3rc1

### Browser name and version

FF 92 / O 78

### Settings

AdGuard Base Filter

**Comment by felix-22** [comment]
There are still big empty ad placholder left, (am I supposed to report it to EasyList?).

![capture_002_13-09-2021_10-47-42](https://user-images.githubusercontent.com/75935068/133053489-e8cc55a3-0ab1-4792-b9bd-5b208e83382c.png)

**Comment by spirillen** [comment]
This one could be nice as well

`freehotporntubes.com###stop_ad2`

**Comment by Yuki2718** [comment]
Made generic: https://github.com/uBlockOrigin/uAssets/commit/0d3671e7539b54677bdb067936f9e0084b4db629

**Comment by spirillen** [comment]
Another Q with of the BlackLists from the https://github.com/uBlockOrigin/uAssets/tree/master/filters should I import to my lists https://mypdns.org/my-external-stuff/ublockorigin-rules/-/blob/master/ublockorigin-rules.template ?

**Comment by Yuki2718** [comment]
Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/).

**Comment by spirillen** [comment]
nope, not going to that domain. just like google, i endorse my privacy

**Comment by Yuki2718** [comment]
@spirillen 
Then ask me personally: https://github.com/Yuki2718/adblock/issues/4. I'll remove this post soon.
