### ISSUE TITLE
[NSFW] sharpporn.com

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uAssets#9964]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

NSFW subpages only, example: `http://www.sharpporn.com/niches.shtml?tag=sweet`

### Describe the issue

Popunders when clicking at empty space of website, on subpages only.

### uBlock Origin version

1.37.3rc1

### Browser name and version

FF 92 / O 78

### Settings

AdGuard Base Filter

**Comment by Yuki2718** [comment]
This site leads to another circle of porn farm. I don't have time to investigate now.

**Comment by spirillen** [comment]
Guessing I'm going to feel like a lucky punk... I didn't experience any redirects....

**Comment by felix-22** [comment]
Or just your uBO filter lists have been updated meanwhile, as there was a fix:

> Yuki2718 added a commit that referenced this issue 21 hours ago : https://github.com/uBlockOrigin/uAssets/commit/e6fd5e7067ed0a6047b9664beea7811cd780e39d
