### ISSUE TITLE
NSFW Exit redirects. Seems likely to share script

### ISSUE THREAD

**Issue by spirillen** [uBlockOrigin/uAssets#9968]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [ ] uBO with default lists/settings
- [ ] using a new, unmodified browser profile

### URL(s) where the issue occurs

A bit unorthodox but in this case I would like to reference to https://github.com/easylist/easylist/issues/9079 for all preliminary informations

### Describe the issue

Exit redirect / pop-(up|under)

### Screenshot(s)

Follow the links:
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/616
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/619
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/505
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/619
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/620
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/622
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/462
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/624
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/625
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/626
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/627
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/628
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/629
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/631
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/632
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/633
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/634
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/635
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/636
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/637
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/623
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/638
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/639
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/640
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/641
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/281
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/277
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/629
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/642
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/643
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/644
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/645
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/274
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/508
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/444
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/646
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/269
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/648
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/263
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/649
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/650
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/651
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/647
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/652
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/402
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/131
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/653
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/387
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/654
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/655
- https://mypdns.org/my-privacy-dns/porn-records/-/issues/656

### uBlock Origin version

uBlock Origin 1.37.2

### Browser name and version

FF + Tor

### Settings

- Changes? like what?

But a little export button could be smart

### Notes

> @felix-22 wrote in https://github.com/easylist/easylist/issues/9079#issuecomment-917624839
> 
>Hey my NFSW buddy, do you mean the ~8000 popit script porn sites I found https://github.com/easylist/easylist/issues/8703#issuecomment-903119076 ?
> If so, then you most likely want to report them to [uAssets Tracker](https://github.com/uBlockOrigin/uAssets/issues), because they can't be fixed in EasyList...

This is my followup from https://github.com/easylist/easylist/issues/9079#issuecomment-917634576

**Comment by uBlock-user** [comment]
> Seems likely to share script

Do you know which script is being shared ? If so, URL ?


> https://mypdns.org/my-privacy-dns/porn-records/-/issues/616

Redirects to login page.

**Comment by felix-22** [comment]
> uBlock-user : Do you know which script is being shared ? If so, URL ?

Most likely this one, it's found on over `~8000` porn sites:

> felix-22 : https://github.com/easylist/easylist/issues/8703#issuecomment-903119076 : 
> https://publicwww.com/websites/popit/ returns 8151 web pages,
> and "only" 260 are fixed already in uBO: uBlockOrigin/uAssets@7b1f737

I see that AdGuard Base Filter conatinas a filter which has over ~1000 such sites fixed compared to uBO ~200, maybe just copy & paste domains from AdGuard Base Filter to uBO filters, here is the big filter from AdGuard Base: [LINK](https://github.com/AdguardTeam/AdguardFilters/blob/e07641682cf875780ea47ac1f1d4e6c34808f93d/EnglishFilter/sections/general_extensions.txt#L193-L195)

<details not-open>
<summary>popit</summary>


```js
<script type = "text/javascript" >
    var popit = true;
window.onbeforeunload = function() {
    if (popit == true) {
        popit = false;
        setTimeout(function() {
            window.open("/ivideo.php", "_blank");
            window.location.href = "/ivideo.php";

        }, 0);
        return "Thatsallfalks, leaving???";
    }
    popit = true;
}

function noPop() {
    popit = false;
}
(function(w, l, d) {
    var cloc = l.pathname + l.search;
    history.replaceState(null, d.title, l.pathname + "#!/back");
    history.pushState(null, d.title, l.pathname);
    w.addEventListener("popstate", function() {
        if (l.hash === "#!/back") {
            noPop();
            history.replaceState(null, d.title, l.pathname);
            setTimeout(function() {
                l.replace("/ivideo.php");
            }, 0);
        }
    }, false);
}(window, location, document));
```
</details>

**Comment by uBlock-user** [comment]
> Just singin and you are there. It also have relation to the fact I'm unable to load a "Are 18+ to enter" script. this way you need to do something acutly to actually get acces.

> You should be able to use both github and gitlab oauth login api's

Post the url's here.

**Comment by uBlock-user** [comment]
> Just singin and you are there. It also have relation to the fact I'm unable to load a "Are 18+ to enter" script. this way you need to do something acutly to actually get acces.

> You should be able to use both github and gitlab oauth login api's

Post the urls here.

**Comment by uBlock-user** [comment]
https://github.com/easylist/easylist/issues/9079

Are those all the urls ?

**Comment by felix-22** [comment]
All of them is ~8000: https://publicwww.com/websites/popit/ but most of them are not revealed, 
however AdGuard found over ~1000 domains already: [> LINK <](https://github.com/AdguardTeam/AdguardFilters/blob/e07641682cf875780ea47ac1f1d4e6c34808f93d/EnglishFilter/sections/general_extensions.txt#L193-L195)

@Yuki2718 can you help us

**Comment by spirillen** [comment]
> [easylist/easylist#9079](https://github.com/easylist/easylist/issues/9079)
> 
> Are those all the urls ?

Sites that  is redirecting to each other with the  more or less same `exit.php` scripts and they keep circling to each other, thefore do it **_likely_** they share the same script. No more | No Less

**Comment by spirillen** [comment]
> > Seems likely to share script
> 
> Do you know which script is being shared ? If so, URL ?
> 
> > https://mypdns.org/my-privacy-dns/porn-records/-/issues/616
> 
> Redirects to login page.

You should now see the following text on the login screen. https://mypdns.org/infrastructure/workboard/-/issues/22

Please add any suggestion you feel likes in the linked issue

**Comment by Yuki2718** [comment]
> maybe just copy & paste domains from the BIG AdGuard filter to the uBO filter

I disagree, on these sites often scriptlet doesn't work for race condition (story is different for AG apps independent of browser) hence I often use `$inline-script` or nostif (more resilient to race condition). If we copy and paste, it's likely ending up adding many useless filters for uBO.

**Comment by felix-22** [comment]
Okay, seems that spirillen will have to report all of the porn sites separately then.

**Comment by Yuki2718** [comment]
I don't think we have to fix all. I already explained my aim in EL repo.

**Comment by felix-22** [comment]
So what determines which pages will be fixed and which will not be fixed? Popularity? What about the approach: fix all or none.

**Comment by Yuki2718** [comment]
> So what determines which pages will be fixed and which will not be fixed? 

Amount of time we can spent. If one comes with a report of thousands of domains, it will never be addressed.

> What about the approach: fix all or none.

Don't fall in perfectionism. Fixing some is far better than no fix.

**Comment by felix-22** [comment]
> Amount of time we can spent. If one comes with a report of thousands of domains, it will never be addressed.

Easy,  I didn't say it had to be all at once, but X per day (let's say spirillen will report 10 porn sites per day).

> Don't fall in perfectionism. Fixing some is far better than no fix.

Easy, it was just a question / idea (to you), not a claim that I want it that way.

spirillen, as seen, websites must be reported separately, and try to not to exceed ~10 per day.

**Comment by uBlock-user** [comment]
> So what determines which pages will be fixed and which will not be fixed? Popularity?

https://github.com/uBlockOrigin/uAssets/issues/7468#issuecomment-635422293

what gorhill said.

**Comment by uBlock-user** [comment]
> spirillen, as seen, in this case, websites must be reported separately, and try to not to exceed ~10 per day.

For this case, one could report 10 in one new report.

**Comment by uBlock-user** [comment]
Those 8000 or something are not going to get fixed just for the sake of fixing, so only the ones reported in EL issue.

**Comment by felix-22** [comment]
Yeah, whatever, but:
- it was mostly about generic filters
- these DO have been mass fixed "just for the sake of fixing"
   - https://github.com/uBlockOrigin/uAssets/issues/5305
   - https://github.com/uBlockOrigin/uAssets/issues/5489

Many of them have been mass added, only randomly checked, it contradicts what you're writing...

Either way, I'm done in this thread.

**Comment by uBlock-user** [comment]
In the past, not anymore. I would have declined fixing those also if I had participated back then, it was pointless as those domains were also pulled from the crawler like you're doing. We're not going to fix domains pulled from the crawler.

**Comment by felix-22** [comment]
> In the past, not anymore.

Okay then, that's what bothered me, it's clear to me now.

**Comment by spirillen** [comment]
> spirillen, as seen, in this case, websites must be reported separately, and try to not to exceed ~10 per day.

I don't think so.... The future looks like zero will be reported.

Before reading, be aware I'm pissed off, that you believe I only here to give and never get...


PS: You are WAY over your head here: https://github.com/uBlockOrigin/uAssets/issues/9968#issuecomment-918172121
Please stick to what you know and ask for the rest.

<details><summary>Pissed off.</summary>

Pornographic sites are reported and maintained here: <https://mypdns.org/my-privacy-dns/porn-records> no where else by me.

It is a Privacy enhanced site without any kind of tracking/spam/adware or what so ever junk you find everywhere else like on github and gitlab any everyone maintaining Blacklisting- and projects advocating for privacy are welcome to get a space.
 
[My Privacy DNS](https://mypdns.org/explore) is 100% a FOSS project  without any pitfalls.

I'm not supporting github nor gitlab or any other anti privacy spyware site in any way shape or form.
I am only here because , this kind of work requires me to, and you, yes you, still are using dearly paid services like gh , gl , reddit or a likes.

This was a friendly sharing to the public for other to benefit from. Don't expect I'm going to add a lot to third parties, based on any regular basis, as I couldn't [care less](https://github.com/Clefspeare13/pornhosts/blob/master/CONTRIBUTING.md#notes) for porn site and blacklisting them.
If I should, well I supposed it will help if you gave back to mypdns, not only taking and craving.

Meaning if you want 10 a day, feel free to pick 10 a days form the [tree](https://mypdns.org/my-privacy-dns/porn-records/-/commits/master)

</details>

**Comment by felix-22** [comment]
Is this directed at me or them? I have no power here on this repo, they decided, not me, I just wanted to help you and bargain for you at least 10 porn issues a day, so I understand that your complaints are directed at them and not me... I still can't perfectly understand from the translator what exactly your comment is about, only know you got "pissed off" about something or misunderstood something?

**Comment by gorhill** [comment]
> he wanted so badly to fix all the porn sites he found)

Why not just create his own filter list for this? We do not want to unduly bloat uBlock filters with speculated solutions to speculated issues -- it could very well be that nobody visits sites found by a crawler.

**Comment by felix-22** [comment]
> Why not just create his own filter list for this?

I'm not him, but I think that's because he is simply not so advanced in creating adblock filters...

> We do not want to unduly bloat uBlock filters with speculated solutions to speculated issues -- and also it could very well be that nobody visits sites found by a crawler.

We already understood it, like I said in https://github.com/uBlockOrigin/uAssets/issues/9968#issuecomment-918172121 I'm done with this thread already, I only have written back to spirillen because  I don't understand what and to whom he has complains, can't understand fullly trought a transaltor.

**Comment by spirillen** [comment]
Why am I writing in this repo, your clearly doesn't understand what I'm writing anyway and keeps sailing down a road that never have existed...

So let me put in plain schoolyard language

I'll give a fuck in blackilisting porn in any way shape or form, I solely does this for 2 reasons, 1 help other, 2 transfer it into RPZ AND clean lists.

I visit this site twice, one time with the www and one time without the www = I give a damned if anything gets fixed, I have the screenshot, @funilrys/pyfunceble handle the rest and nobody else who would have a verification of proof can find the more or less sfw srenshot in the representing issue (Why one domain = one issue)

I do not have any gain by posting these issue to you, it is everyone else who might visit the sites later and I only post these bulks list as it seems plausible they share bad scripts.

> Why not just create his own filter list for this?

@gorhill it is called [adult.mypdns.cloud](https://mypdns.org/mypdns/support/-/wikis/RPZ-List#adultmypdnscloud) and runs on port 53? And as Dane, who gave the porn free as the first in 1972, I do not have any issues with this.

AS said, it is for everyone else. If you find something useful, fine otherwise nobody died today.

Should we get this one back on track please and stop turning things upside down #:unamused:

**Comment by felix-22** [comment]
> spirilllen : Why am I writing in this repo, your clearly doesn't understand what I'm writing anyway and keeps sailing down a road that never have existed...

Possibly, as I already mentioned I had temporary problems with understanding what you wrote maybe I was tired or the translator did not translate perfectly, but after resting, with a fresh mind, I have tried to read again with the help of translator and finally I understood something.

> felix-22 : spirillen, as seen, in this case, websites must be reported separately, and try to not to exceed ~10 per day.

As far as I can see your comlaints started by quoting above sentence - it was not an order or that I want something from you, which is what you're trying to accuse me of, and which made you so unnecessarily pissed off, it was just a hint, I was just trying to explain to you the technical side of the rules on how to report pages on the tracker. So you most likely picked up the wrong context of what I wrote...It's entirely up to you whether you want to report anything here or not, in the end, you are the one who created the thread here, not me, no one forced you to do it, like I already said all I wanted was to try to help you with your issue you created.

As for dns, I don't use any dns, just uBO, so most likely I'm not interested in reporting anything to any dns, nor I'm interested in creating additional accounts to login.

I hope you understand now, try to control your temper and next time try to ask first if you are not sure of the context, there is no need to create problems where there are none...especially since not everyone speaks native English and translators do not always translate perfectly.

**Comment by spirillen** [comment]
Hey @felix-22 thanks for reaching out to get back to the middle and be able to talk with each other in a better manor.

I'm very open to this and have been giving it some thoughts myself for doing the same.

First of, what is your native language since you are using a translator?? Maybe I happen to know some words that could make it easier for us to communicate.

So let me explain what happen from my perspective.

Where things started to go wrong, is not the "post 10 a day", not even close, it was the drop that tipped it all on a bad day. where I got worn out by a lot reporting of things that should have been rather straight forward.

The hole down-spiral actually stared by another comments of your, which I can't find  right now, but something about I would like to block all the porn in the world...!
Then you posted the "10 a day" like you completely forgot who actually requested this issue in the first place.... 
> @felix-22 wrote in https://github.com/easylist/easylist/issues/9079#issuecomment-917624839
> If so, then you most likely want to report them to uAssets Tracker, because they can't be fixed in EasyList...

So what happend
- I never claimed I would stop all the porn, I have actually giving the full story about how it all stared by a friendly maintenance of @Clefspeare13 pornhosts and how he throw the key and left of for Mars.
- I should limit me to 10? who requested the post?

So from my perspective it started to looks like you was trying to make me responsible for things you requested yourself and at the same time accusing me for things I never have said or even indicated to have any interests in. Maybe who should be careful about telling third-parties (the lost comment from before) what other want's, thinks or believes in without being certain.

I hope your translator can hack this one, and try control your accusations i the future.

**Comment by felix-22** [comment]
> spirillen :  First of, what is your native language since you are using a translator?? Maybe I happen to know some words that could make it easier for us to communicate.

Polish.

> spirillen : The hole down-spiral actually stared by another comments of your, which I can't find right now, but something about I would like to block all the porn in the world...!

You mean this:? 

> felix-22 : https://github.com/uBlockOrigin/uAssets/issues/9968#issuecomment-918172121 : (I just wanted to support him a bit because he wanted so badly to fix all the porn sites he found)

What's wrong with it?...

> spirillen : 
> 
> Then you posted the "10 a day" like you completely forgot who actually requested this issue in the first place....
> >@felix-22 wrote in [easylist/easylist#9079 (comment)](https://github.com/easylist/easylist/issues/9079#issuecomment-917624839)
> >If so, then you most likely want to report them to uAssets Tracker, because they can't be fixed in EasyList...

It was not a request, nor an order, just a logical hint...

> spirillen : So from my perspective it started to looks like you was trying to make me responsible for things you requested yourself and at the same time accusing me for things I never have said or even indicated to have any interests in. Maybe who should be careful about telling third-parties (the lost comment from before) what other want's, thinks or believes in without being certain.

I didn't accuse you of anything, I just wanted to help you and give you guidance, it seems it was quite the opposite, you were the one who started accusing first....
