### ISSUE TITLE
pelispedia.tv ADS [Pop-up]

### ISSUE THREAD

**Issue by xDarkARG** [uBlockOrigin/uAssets#997]
URL(s) where the issue occurs

https://www.pelispedia.tv/

Describe the issue

ADS

Versions

Browser/version: Chrome 62.0.3202.62
uBlock Origin version: 1.14.20

Settings

I use the configuration that comes already in ublock when one installs the Extension

**Comment by lain566** [comment]
@okiehsch  There is a popup when playing videos
https://www.pelispedia.tv/pelicula/the-punisher-season-1-episode-1/

**Comment by okiehsch** [comment]
Is it fixed if you add
`pelispedia.co##script:inject(nowebrtc.js)`?

**Comment by lain566** [comment]
Yep, that works

**Comment by lain566** [comment]
@mapx- There are popups when you click on the player, especially the button called `Fast`, the first button is fake.
`https://www.pelispedia.tv/pelicula/mis-huellas-a-casa/`

![Anotación 2019-04-18 172804](https://user-images.githubusercontent.com/27441315/56372650-b0117680-61ff-11e9-843b-e42ad5f680f3.png)

**Comment by smed79** [comment]
@lain566 test
```
fembed.com,pelispedia.*##+js(abort-on-property-read.js, AaDetector)
```

**Comment by lain566** [comment]
@smed79 That does not work

**Comment by smed79** [comment]
test again `##a[href^="https://adsrv4k.com/"]`

**Comment by lain566** [comment]
if I add this
`pelispedia.*##[href^="https://adsrv4k.com/"]`

Pop-up do not appear anymore, but I can not continue.

**Comment by lain566** [comment]
These filters work on the button called `Opción 1`
```
pelispedia.*##[class^="bloque_ads"]
pelispedia.*##[href^="https://adsrv4k.com/"]
```

**Comment by mapx-** [comment]
```
pelispedia.*##+js(remove-attr.js, oncontextmenu)
##[href^="https://adsrv4k"]
||pelispedia.tv/Native.html
```

When you want to play one of the last 3 servers just click on top right of the video not on the play button

**Comment by mapx-** [comment]
the first 2 buttons seem to be fake, right ?

**Comment by lain566** [comment]
only the first `Opción HD`
this filter appears in adguard list
`||pelispedia.tv/Native.html`
![Anotación 2019-04-18 184133](https://user-images.githubusercontent.com/27441315/56377088-d76d4100-6209-11e9-8c0f-b10fed316e26.png)

**Comment by lain566** [comment]
These three work for me
```
pelispedia.*##[class^="bloque_ads"]
pelispedia.*##[href^="https://adsrv4k.com/"]
pelispedia.*##[id^="ap"]
```

**Comment by mapx-** [comment]
clicking fast I get only popups

**Comment by lain566** [comment]
You're right 😕

**Comment by mapx-** [comment]
hiding those buttons
```
pelispedia.*##:xpath(//span[contains(text(),"Opción")]/../..)
pelispedia.*##:xpath(//span[contains(text(),"Fast")]/../..)
```

**Comment by lain566** [comment]
Those buttons are not fake

**Comment by smed79** [comment]
Fast button is not a fake https://imgur.com/a/jcvICyX

**Comment by mapx-** [comment]
I get no functionality on the first 1

**Comment by smed79** [comment]
also "Opción 1" button also is not a fake https://imgur.com/a/fylOxLF

**Comment by lain566** [comment]
@mapx-  because there is an invisible frame 
this fixes it
`pelispedia.*##[class^="bloque_ads"]`

**Comment by mapx-** [comment]
ok, now is working fine, the invisible stuff I guess is gone away due to AaDetector filter

**Comment by smed79** [comment]
PR https://github.com/easylist/easylist/pull/3288/files#diff-eff6174a52fcc75be714f55adb5e94eb
