### ISSUE TITLE
DriverFix.com False Positive on Badware filter - Reblock removal request 

### ISSUE THREAD

**Issue by kobyharding** [uBlockOrigin/uAssets#9974]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

https://www.driverfix.com

### Describe the issue

Hi,
It seems uBlock Origin Badware filter is including driverfix.com - ||driverfix.com^$document

**Case history -**
- It was added originally at uAssets - back in November 2018 and was solved om March 2021. 
- It was added again on 28/08/2021 on issue #9840

**Current block reasons on issue #9840**
- Old Malwarebytes ADWCleaner PUP detection 
- Blog article of Malwarebytes (https://blog.malwarebytes.com/detections/pup-optional-driverfix/)

**Request for removal**
Malwarebytes isn't blocking DriverFix for over a year now.
These are old remnants.
We contacted Malwarebytes great team and asked to confirm and remove the blog article and remove ADWCleaner detection. 

They confirmed they did:
- Blog article
https://blog.malwarebytes.com/detections/pup-optional-driverfix/
It will just redirect to the general PUP.Optional explanation page -
https://blog.malwarebytes.com/detections/pup-optional/
- ADWCleaner detection - We ran the application on multiple machines running DriverFix and no detection were found.

If you will check DriverFix production (from the website) files or the domain on VirusTotal or Scumware it will be 100% clean, also from Malwarebytes engine. 

See example -
![image](https://user-images.githubusercontent.com/84786433/133071047-35d696bd-b37e-46ed-92f6-7808adaf0748.png)

Would you kindly remove the the website from the Badware filter list?

Thanks!
Koby from DriverFix
VP Product

### uBlock Origin version

1.37.2

### Browser name and version

Chrome Version 93.0.4577.63

### Settings

Used default settings

**Comment by uBlock-user** [comment]
@iam-py-test Does it still happen ?

**Comment by iam-py-test** [comment]
@uBlock-user I can confirm the article redirects but can’t investigate further until later today
@kobyharding if you contacted Malwarebytes, can you post proof (I think they normally handle False Positives on their public forums, as I have dealt with them before)
Later today I can check and verify that the installer changed.

**Comment by kobyharding** [comment]
@iam-py-test 
We are contacting on private emails and not on the general forum so I would prefer not to post the emails here.
Please update after you can also confirm that the ADWCleaner detections have been solved.

**Comment by iam-py-test** [comment]
> @iam-py-test
> We are contacting on private emails and not on the general forum so I would prefer not to post the emails here.
> Please update after you can also confirm that the ADWCleaner detections have been solved.

@kobyharding understand 
I guess that the end result (Malwarebytes no longer detecting you) is the same
I will update when I have checked (which will be later today)

**Comment by iam-py-test** [comment]
@kobyharding
My objections: 
- Your site seems to lack HTTPS, which is a _really_ bad idea for sites hosting executables (for obvious reasons), and which is _really_ easy to do 
- The exe is the same as the one I collected when I determined your site was malware (I verified it)
- The program its self does not seem to have changed at all 
- Your account - @kobyharding - has no real content. All it seems to have ever done was open this issue and https://github.com/uBlockOrigin/uAssets/issues/9206, which is _very_ suspicious

However, it does seem that your program is no longer detected by my scanners:
![image](https://user-images.githubusercontent.com/84232764/133152590-3e5cfa36-a8c6-4ad2-b9c4-c9c77c88cc25.png)

I think the decision is up to @uBlock-user and @gorhill of whether your site should be unblocked
I think you should add HTTPS to your site, as any site hosting executable and possibly handling sensitive information - or really any site - should have the protections of HTTPS and TLS

I am going to be watching you and your site, and if I see _anything_ I will reconsider my verdict
CC @DandelionSprout @blocklistproject

**Comment by uBlock-user** [comment]
@okiehsch what do you think ?

**Comment by okiehsch** [comment]
I am no malware expert, if @iam-py-test says the file is clean now we should comment out the filter for now imo.

While I agree it would be better to use HTTPS - I certainly would not download an executable from a site that usses HTTP - we don't block sites because they don't.

**Comment by uBlock-user** [comment]
> the file is clean now we should comment out the filter for now imo.

I find the timing very suspicious given the last filter time-stamp, so commenting it out for now.
