### ISSUE TITLE
[NSFW] youngpussies.xyz and others

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uAssets#9976]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

NSFW `http://youngpussies.xyz/`

### Describe the issue

Pop(ups/unders) when clicking anywhere in website.

### uBlock Origin version

1.37.3rc2

### Browser name and version

FF 92 / O 78

### Settings

- AdGuard Base Filter

**Comment by Disqu3-mirOir-qt** [comment]
not pop-up , this agregator porn gallery photo just redirect website

**Comment by felix-22** [comment]
![rec](https://user-images.githubusercontent.com/75935068/133077022-5b3c5705-c0fa-4247-a5fc-c93c602f0c5a.gif)

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/9977
https://github.com/uBlockOrigin/uAssets/issues/9978
https://github.com/uBlockOrigin/uAssets/issues/9979
https://github.com/uBlockOrigin/uAssets/issues/9980
https://github.com/uBlockOrigin/uAssets/issues/9981
https://github.com/uBlockOrigin/uAssets/issues/9982

**Comment by felix-22** [comment]
Last 5 as for today:

https://github.com/uBlockOrigin/uAssets/issues/9984
https://github.com/uBlockOrigin/uAssets/issues/9985
https://github.com/uBlockOrigin/uAssets/issues/9986
https://github.com/uBlockOrigin/uAssets/issues/9987
https://github.com/uBlockOrigin/uAssets/issues/9988

**Comment by uBlock-user** [comment]
After [internal discussion](https://github.com/orgs/uBlockOrigin/teams/ublock-filters-volunteers/discussions/364) with the team, it was decided not fix any porn farms group of sites.
