### ISSUE TITLE
[NSFW] hd-porno.cz

### ISSUE THREAD

**Issue by felix-22** [uBlockOrigin/uAssets#9988]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

[NSFW] `http://www.hd-porno.cz/`

### Describe the issue

Pop(ups/unders) when clicking anywhere on website.

### uBlock Origin version

1.37.3rc2

### Browser name and version

FF 92 / O 78

### Settings

- AdGuard Base Filter

**Comment by Yuki2718** [comment]
1. Please do not open and close issues one after another, use the open issue #9976 in this case.
2. However, these sites are not very important. 99% user will never visit any of them. None of us who spend some of our free time as volunteer is willing to fix them anything more than what we can afford. This is **not** something like "3 sites are okay, 4 not" - we can find these sites like you and we don't.

**Comment by uBlock-user** [comment]
I thought the msg was clear - do not report any new sites you find from any crawler.

**Comment by felix-22** [comment]
> Yuki2718 : Please do not open and close issues one after another, use the open issue [[NSFW] youngpussies.xyz and others #9976](https://github.com/uBlockOrigin/uAssets/issues/9976) in this case.

I did the same thing uBlock-user did, I thought that's what he meant - to close issues and put links into META thread, if it wasn't what he expected, it's not my fault, let him be clearer next time...

> uBlock-user : I thought the msg was clear - do not report any new sites you find from any crawler.

Okay, I can click/visit links on a website in a typical way most users do, but in many cases it will still lead me to similiar websites...so don't blame me then.

**Comment by felix-22** [comment]
> uBlock-user: https://github.com/uBlockOrigin/uAssets/issues/9976#issuecomment-918411841 : After [internal discussion](https://github.com/orgs/uBlockOrigin/teams/ublock-filters-volunteers/discussions/364) with the team, it was decided not to fix any porn farms group of sites.

Any quick and easy way, for a typical Internet user, how to determine if a website is allowed to report on the uAssets tracker or not, in terms of: "porn farm", " these sites are not very important. 99% of users will never visit any of them." ? For now, all I know is to avoid crawlers and browse trough Google, but I would like to not be blamed or hear complaints if it turns out I submitted accidentaly a "junk" site again without realizing it.

For example: I've just Googled for a phrase: https://www.google.pl/search?q=tranny+porn+pics
and I went to the 3rd page from the top suggested by Google: `https://www.xemales.com/`, and the pornsite contains Exo Ads, so I'm reporting it to uAssets, is it fine?

**Comment by felix-22** [comment]
For example, comparing  `xemales.com` vs `q1003.com` ( https://github.com/uBlockOrigin/uAssets/issues/9996 ) tells me that it's most probably everything ok with `xemales.com` being reported to uAssets as it's more popular than `q1003.com` which increases the likelihood that it is not a junk page (I don't know how much you can trust this link checker and whether it can detect fake sites):

`q1003.com`
![q1003_com](https://user-images.githubusercontent.com/75935068/133224721-e60daf8a-8caa-4c43-87f8-b03016be075b.png)

`xemales.com`
![xemales_com](https://user-images.githubusercontent.com/75935068/133224765-f4abf551-d70b-4638-a04d-8e01fa0c127c.png)

**Comment by okiehsch** [comment]
>  comparing `xemales.com`vs `q1003.com`

What is this, why are you comparing ratings of  a porn site with a radio station? 
I don't care if the most blatant porn farm in the history of mankind has a higher rating than a radio station, it's obviously irrelevant.

What amounts to a porn farm is at the sole discretion of the filter list maintainers in this repo.

**Comment by felix-22** [comment]
> What is this, why are you comparing ratings of a porn site with a radio station?
> I don't care if the most blatant porn farm in the history of mankind has a higher rating than a radio station, it's obviously irrelevant.

Try to read carefully, that's why I wrote at the end in my previous comment: "But on the other side I'm not sure, as I don't know how much you can trust this link checker's rating system and whether it can detect fake / farm sites..." which simply means that this was just an example comparison and I was not sure if it makes sense, and I was just waiting for someone to clear up the doubt, nowhere did I claim that this tool/comparison was 100 percent appropriate, I can try to find another if the current one doesn't suit you.

> What amounts to a porn farm is at the sole discretion of the filter list maintainers in this repo.

That's even good, they will have no right to complain and blame if sometimes the submitter accidentally report a junk page without being aware of it.

**Comment by okiehsch** [comment]
> Closing the ticket, giving the declined label and providing a short reason will be sufficient I think.

That's we intend to do from now on.

**Comment by felix-22** [comment]
With the assumption that you will not abuse it and will follow your own rules (https://github.com/uBlockOrigin/uAssets/issues/9968#issuecomment-918158175 : "are not going to get fixed just for the sake of fixing"): and you will not "reject submissions for the sake of rejecting", as you can see, this principle works both ways...

**Comment by felix-22** [comment]
> What amounts to a porn farm is at the sole discretion of the filter list maintainers in this repo.

I would prefer not to waste time submitting sites that will be rejected anyway, nor would I like to hear complaints that I submit too many sites that don't qualify or that I abuse the tracker. If you cannot provide an easy and quick way to distinguish between a site that is suitable for reporting and a site that is not, it may happen that out of 10 submitted sites half will not be suitable...
