### ISSUE TITLE
aftonbladet.se

### ISSUE THREAD

**Issue by jspenguin2017** [uBlockOrigin/uAssets#999]
### URL(s) where the issue occurs

`https://www.aftonbladet.se/sportbladet/a/Xw8jno/erik-skoglund-fortfarande-nedsovd `

### Describe the issue

Anti-adblock

### Screenshot(s)

![image](https://user-images.githubusercontent.com/7283682/34017689-f8f78b3a-e0e3-11e7-9170-42df33b3c6b5.png)

### Versions

- Browser/version: Firefox 57.0.2
- uBlock Origin version: 1.14.20

### Settings

All default, all updated

**Comment by gorhill** [comment]
aftonbladet.se##._2V5Ts:style(filter: none !important;)
    aftonbladet.se##._199I6 > div:has(> ._2BiUa)

Works?

**Comment by okiehsch** [comment]
````
@@/hyper-assets/app*$script,domain=aftonbladet.se
/hyper-assets/$script,domain=aftonbladet.se
````
works on my end.

**Comment by okiehsch** [comment]
Actually 
````
@@/hyper-assets/app*$script,domain=aftonbladet.se
@@/hyper-assets/preload*$script,domain=aftonbladet.se
/hyper-assets/$script,domain=aftonbladet.se
````

**Comment by gorhill** [comment]
@okiehsch Your last set of filters work. Adding:

    aftonbladet.se##[id^=innerabAdArea-]

Also takes care of placeholders

**Comment by gorhill** [comment]
By the way, did you meant:

    /hyper-assets/$script,domain=aftonbladet.se

To be:

    /hyper-assets/*$script,domain=aftonbladet.se

**Comment by jspenguin2017** [comment]
I'm adding a linting rule for that, it's common mistake.

**Comment by okiehsch** [comment]
Yeah, my bad.

**Comment by okiehsch** [comment]
If you use the logger to craft the static filter you also automatically get the correct
`||www.aftonbladet.se/hyper-assets/*$script,domain=www.aftonbladet.se`.

**Comment by jspenguin2017** [comment]
Nano Highlighter and Nano Linter will be needed either way, it already found 5 mistakes in Adguard's filters.

**Comment by okiehsch** [comment]
**Off topic** I think the swedish regional list "shipping" with uBO is clearly lacking, so I googled for an alternative and I think [this list](https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/Frellwits-Swedish-Filter.txt) should be considered, if the author agrees of course.
It uses extended filter syntax, and actually includes a fix for this issue.

**Comment by gorhill** [comment]
@okiehsch You can still add your filters until the new list widespread enough, `assets.json` updates only every 13 days.

**Comment by gorhill** [comment]
@lassekongo83, I added your list as the official regional one for SWE, it looks like the Fanboy one is no longer maintained.
