### ISSUE TITLE
RuneScape Wiki - blocked images

### ISSUE THREAD

**Issue by invalidCards** [uBlockOrigin/uAssets#9990]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://runescape.wiki/w/Special:NewFiles`
`https://runescape.wiki/w/Ancient_Gnomish`

### Describe the issue

Images with the words "advertisment" or "advertisement" in the title or tooltip get blocked by uBO. The wiki does not serve any ads itself, these are official in-game names of objects within the game. I have little experience with writing filters myself, but it would be appreciated if this were applied to runescape.wiki and all of its subdomains, if that distinction is required.

### Screenshot(s)

On Special:NewFiles, with uBlock Origin on:
![image](https://user-images.githubusercontent.com/842080/133153843-1af563f4-7844-4237-b49b-c3d30a612257.png)

With uBlock Origin disabled for the website:
![image](https://user-images.githubusercontent.com/842080/133153903-6eb38187-1f71-4654-ba70-89fdd762529e.png)

### uBlock Origin version

uBlock Origin 1.37.2

### Browser name and version

Mozilla Firefox 92.0 (64-bit)

### Settings

No settings were changed, but for posterity, I will list the filter lists that I normally have enabled:
* All in Built-in
* All in Ads
* All in Privacy except Block access to LAN
* All in Malware domains
* All in Annoyances except Fanboy's Annoyance and Fanboy's Social
* Peter Lowe's Ad and tracking server list

**Comment by uBlock-user** [comment]
`@@||runescape.wiki/images/thumb/$image,1p`

@ryanbr

**Comment by invalidCards** [comment]
Please note that this also affects full-size image previews, which don't have `thumb` in the url, just `runescape.wiki/images/`

(Also, it seems to be blocked by EasyList - should I perhaps ask for the fix there instead so users of all anti-advertisement plugins benefit from it?)

**Comment by uBlock-user** [comment]
> Please note that this also affects full-size image previews

Where ? Post a link, so to as to verify

**Comment by invalidCards** [comment]
`https://runescape.wiki/w/Ancient_Gnomish#/media/File:Gnome_Stronghold_agility_course_advertisment.png` and `https://runescape.wiki/w/File:Gnome_Stronghold_agility_course_advertisment.png`, for instance.

**Comment by uBlock-user** [comment]
rule modified.

**Comment by uBlock-user** [comment]
https://github.com/easylist/easylist/commit/8070f3c4507a71eb06c9a6e5ee71f32d213d74fd
