### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by Stateofminf** [uBlockOrigin/uAssets#9991]
- `#```

_Originally posted by @Stateofminf in https://github.com/uBlockOrigin/uBlock-issues/issues/1722#issuecomment-918582684_

**Comment by iam-py-test** [comment]
@Stateofminf please do not open spam issues
You are just wasting the time of people who are taking time out of their life to help for free

**Comment by uBlock-user** [comment]
@gwarser He's spamming around -- 

https://github.com/uBlockOrigin/uBlock-issues/issues/1722
https://github.com/uBlockOrigin/uAssets/pull/9989

**Comment by iam-py-test** [comment]
Also https://github.com/luckman666/deploy_Kubernetes-v1.15.0/pull/4

**Comment by gwarser** [comment]
Already banned in organization.
